EIC Software: CbmRichRingFinderHoughImpl Class Reference
CbmRichRingFinderHoughImpl Class Reference
Ring finder implementation based on Hough Transform method.
#include <EicRoot/blob/master/rich/finder/CbmRichRingFinderHoughImpl.h>
Public Member Functions
CbmRichRingFinderHoughImpl ()
Standard constructor.
virtual ~CbmRichRingFinderHoughImpl ()
Distructor.
void SetParameters ()
Set parameters of the algorithm.
void CalculateRingParameters (float x[], float y[], float *xc, float *yc, float *r)
Calculate circle center and radius.
virtual void HoughTransformReconstruction ()
Run HT for each hit.
virtual void DefineLocalAreaAndHits (float x0, float y0, int *indmin, int *indmax)
Find hits in a local area.
virtual void HoughTransform (unsigned short indmin, unsigned short indmax)
Run HoughTransformGroup for each group of hits.
virtual void HoughTransformGroup (unsigned short indmin, unsigned short indmax, int iPart)
Main procedure for Hough Transform.
void FindPeak (int indmin, int indmax)
Find peak in the HT histograms.
void RingSelection ()
Ring selection procedure.
void ReAssignSharedHits (int ringInd1, int ringInd2)
Reassign shared hits from two rings to only one of the rings.
int GetHitIndex (unsigned short hitInd)
Return hit indez in the internal Array.
void RemoveHitsAroundRing (int indmin, int indmax, CbmRichRingLight *ring)
Set fIsUsed flag to true for hits attached to the ring.
void Init ()
void DoFind ()
Start point to run algorithm.
void SetData (const vector< CbmRichHoughHit > &data)
Set array of hits.
vector< CbmRichRingLight * > & GetFoundRings ()
Return vector of found rings.
CbmRichRingFinderHoughImpl ()
virtual ~CbmRichRingFinderHoughImpl ()
void SetParameters ()
virtual void HoughTransformReconstruction ()
virtual void DefineLocalAreaAndHits (float x0, float y0, int *indmin, int *indmax)
virtual void HoughTransform (unsigned short indmin, unsigned short indmax)
virtual void HoughTransformGroup (unsigned short indmin, unsigned short indmax, int iPart)
void FindPeak (int indmin, int indmax)
void RingSelection ()
void ReAssingSharedHits (int ringInd1, int ringInd2)
int GetHitIndex (unsigned short hitInd)
void RemoveHitsAroundRing (int indmin, int indmax, CbmRichRingLight *ring)
void Init ()
void DoFind ()
void SetData (const std::vector< CbmRichHoughHit > &data)
std::vector< CbmRichRingLight * > & GetFoundRings ()
Protected Attributes
unsigned short fNofParts
float fMaxDistance
float fMinDistance
float fMinDistanceSq
float fMaxDistanceSq
= fMinDistance*fMinDistance
float fMinRadius
float fMaxRadius
float fDx
float fDy
float fDr
unsigned short fNofBinsX
unsigned short fNofBinsY
unsigned short fNofBinsXY
unsigned short fHTCut
unsigned short fNofBinsR
unsigned short fHTCutR
unsigned short fMinNofHitsInArea
float fRmsCoeffEl
float fMaxCutEl
float fRmsCoeffCOP
float fMaxCutCOP
float fAnnCut
float fUsedHitsAllCut
float fCurMinX
float fCurMinY
vector< CbmRichHoughHit > fData
vector< unsigned short > fHist
vector< unsigned short > fHistR
vector< vector< unsigned short > > fHitInd
vector< CbmRichRingLight * > fFoundRings
CbmRichRingFitterCOP * fFitCOP
CbmRichRingSelectAnn * fANNSelect
unsigned short fHitCut
unsigned short fHitCutR
float fUsedHitsCut
std::vector< CbmRichHoughHit > fData
std::vector< CbmRichHoughHit > fDataPart1
Rich hits.
std::vector< CbmRichHoughHit > fDataPart2
Rich hits.
std::vector< unsigned short > fHist
Rich hits.
std::vector< unsigned short > fHistR
std::vector< std::vector
< unsigned short > > fHitInd
std::vector< CbmRichRingLight * > fFoundRings
CbmRichRingFitterCOPLight * fFitCOP
collect found rings
CbmRichRingSelectNeuralNet * fANNSelect
Static Protected Attributes
static const unsigned short MAX_NOF_HITS = 65000
static const unsigned short kMAX_NOF_HITS = 65500
static const unsigned short fNofParts = 2
Private Member Functions
CbmRichRingFinderHoughImpl (const CbmRichRingFinderHoughImpl &)
Copy constructor.
CbmRichRingFinderHoughImpl & operator= (const CbmRichRingFinderHoughImpl &)
Assignment operator.
Detailed Description
Ring finder implementation based on Hough Transform method.
Author
Semen Lebedev
Date
2008
Definition at line 33 of file CbmRichRingFinderHoughImpl.h.
View newest version in sPHENIX GitHub at line 33 of file CbmRichRingFinderHoughImpl.h
Constructor & Destructor Documentation
CbmRichRingFinderHoughImpl::CbmRichRingFinderHoughImpl ()
Standard constructor.
Definition at line 29 of file CbmRichRingFinderHoughImpl.cxx.
View newest version in sPHENIX GitHub at line 29 of file CbmRichRingFinderHoughImpl.cxx
CbmRichRingFinderHoughImpl::~CbmRichRingFinderHoughImpl () virtual
Distructor.
Definition at line 76 of file CbmRichRingFinderHoughImpl.cxx.
View newest version in sPHENIX GitHub at line 76 of file CbmRichRingFinderHoughImpl.cxx
References fANNSelect, and fFitCOP.
CbmRichRingFinderHoughImpl::CbmRichRingFinderHoughImpl (const CbmRichRingFinderHoughImpl &) private
Copy constructor.
CbmRichRingFinderHoughImpl::CbmRichRingFinderHoughImpl ()
virtual CbmRichRingFinderHoughImpl::~CbmRichRingFinderHoughImpl () virtual
Member Function Documentation
void CbmRichRingFinderHoughImpl::CalculateRingParameters (float x[], float y[], float * xc, float * yc, float * r)
Calculate circle center and radius.
Parameters
[in] x[] Array of 3 X coordinates.
[in] y[] Array of 3 Y coordinates.
[out] xc X coordinate of the ring center.
[out] yc Y coordinate of the ring center.
[out] r Ring radius.
Definition at line 494 of file CbmRichRingFinderHoughImpl.cxx.
View newest version in sPHENIX GitHub at line 494 of file CbmRichRingFinderHoughImpl.cxx
References t1, and t2.
virtual void CbmRichRingFinderHoughImpl::DefineLocalAreaAndHits (float x0, float y0, int * indmin, int * indmax) virtual
void CbmRichRingFinderHoughImpl::DefineLocalAreaAndHits (float x0, float y0, int * indmin, int * indmax) virtual
Find hits in a local area.
Parameters
[in] x0 X coordinate of the local area center.
[in] y0 Y coordinate of the local area center.
[out] indmin Minimum index of the hit in local area.
[out] indmax Maximum index of the hit in local area.
Definition at line 162 of file CbmRichRingFinderHoughImpl.cxx.
View newest version in sPHENIX GitHub at line 162 of file CbmRichRingFinderHoughImpl.cxx
References d, fData, fHist, fHistR, CbmRichHoughHit::fHit, fHitInd, fMaxDistance, fMaxDistanceSq, fMinNofHitsInArea, fNofBinsR, fNofBinsXY, fNofParts, CbmRichHitLight::fX, and k.
Referenced by CbmRichRingFinderHoughSimd::HoughTransformReconstruction(), and HoughTransformReconstruction().
void CbmRichRingFinderHoughImpl::DoFind ()
void CbmRichRingFinderHoughImpl::DoFind ()
Start point to run algorithm.
Definition at line 95 of file CbmRichRingFinderHoughImpl.cxx.
View newest version in sPHENIX GitHub at line 95 of file CbmRichRingFinderHoughImpl.cxx
References fData, fFoundRings, HoughTransformReconstruction(), MAX_NOF_HITS, and RingSelection().
Referenced by CbmRichRingFinderHough::DoFind(), and FinderTask::operator()().
void CbmRichRingFinderHoughImpl::FindPeak (int indmin, int indmax)
void CbmRichRingFinderHoughImpl::FindPeak (int indmin, int indmax)
Find peak in the HT histograms.
Parameters
[in] indmin Minimum index of the hit in local area.
[in] indmax Maximum index of the hit in local area.
Definition at line 297 of file CbmRichRingFinderHoughImpl.cxx.
View newest version in sPHENIX GitHub at line 297 of file CbmRichRingFinderHoughImpl.cxx
References CbmRichRingLight::AddHit(), CbmRichRingFitterCOP::DoFit(), CbmRichRingSelectAnn::DoSelect(), fAnnCut, fANNSelect, fCurMinX, fCurMinY, fData, fDr, fDx, fDy, fFitCOP, fFoundRings, fHist, fHistR, fHTCut, fHTCutR, fMaxCutCOP, fNofBinsX, fRmsCoeffCOP, CbmRichRingLight::GetCenterX(), CbmRichRingLight::GetCenterY(), CbmRichRingLight::GetChi2(), CbmRichRingLight::GetNofHits(), CbmRichRingLight::GetRadius(), CbmRichRingLight::GetSelectionNN(), k, and RemoveHitsAroundRing().
Referenced by CbmRichRingFinderHoughSimd::HoughTransformReconstruction(), and HoughTransformReconstruction().
std::vector<CbmRichRingLight*>& CbmRichRingFinderHoughImpl::GetFoundRings () inline
Definition at line 126 of file CbmRichRingFinderHoughImpl.h.
View newest version in sPHENIX GitHub at line 126 of file CbmRichRingFinderHoughImpl.h
References fFoundRings.
vector<CbmRichRingLight*>& CbmRichRingFinderHoughImpl::GetFoundRings () inline
Return vector of found rings.
Definition at line 217 of file CbmRichRingFinderHoughImpl.h.
View newest version in sPHENIX GitHub at line 217 of file CbmRichRingFinderHoughImpl.h
References fFoundRings.
Referenced by CbmRichRingFinderHough::DoFind(), and CbmRichRingFinderHough::DoFindParallel().
int CbmRichRingFinderHoughImpl::GetHitIndex (unsigned short hitInd)
int CbmRichRingFinderHoughImpl::GetHitIndex (unsigned short hitInd)
Return hit indez in the internal Array.
Parameters
[in] hitInd Index in TClonesArray.
Definition at line 484 of file CbmRichRingFinderHoughImpl.cxx.
View newest version in sPHENIX GitHub at line 484 of file CbmRichRingFinderHoughImpl.cxx
References fData.
Referenced by ReAssignSharedHits(), and ReAssingSharedHits().
virtual void CbmRichRingFinderHoughImpl::HoughTransform (unsigned short indmin, unsigned short indmax) virtual
virtual void CbmRichRingFinderHoughImpl::HoughTransform (unsigned short indmin, unsigned short indmax) virtual
Run HoughTransformGroup for each group of hits.
Parameters
[in] indmin Minimum index of the hit in local area.
[in] indmax Maximum index of the hit in local area.
Referenced by CbmRichRingFinderHoughSimd::HoughTransformReconstruction(), and HoughTransformReconstruction().
virtual void CbmRichRingFinderHoughImpl::HoughTransformGroup (unsigned short indmin, unsigned short indmax, int iPart) virtual
virtual void CbmRichRingFinderHoughImpl::HoughTransformGroup (unsigned short indmin, unsigned short indmax, int iPart) virtual
Main procedure for Hough Transform.
Parameters
[in] indmin Minimum index of the hit in local area.
[in] indmax Maximum index of the hit in local area.
[in] iPart Index of the hit group.
virtual void CbmRichRingFinderHoughImpl::HoughTransformReconstruction () virtual
Reimplemented in CbmRichRingFinderHoughSimd.
void CbmRichRingFinderHoughImpl::HoughTransformReconstruction () virtual
Run HT for each hit.
Reimplemented in CbmRichRingFinderHoughSimd.
Definition at line 146 of file CbmRichRingFinderHoughImpl.cxx.
View newest version in sPHENIX GitHub at line 146 of file CbmRichRingFinderHoughImpl.cxx
References DefineLocalAreaAndHits(), fCurMinX, fCurMinY, fData, FindPeak(), fMaxDistance, and HoughTransform().
Referenced by DoFind().
void CbmRichRingFinderHoughImpl::Init ()
void CbmRichRingFinderHoughImpl::Init (void)
Initialize algorithm parameters.
Definition at line 82 of file CbmRichRingFinderHoughImpl.cxx.
View newest version in sPHENIX GitHub at line 82 of file CbmRichRingFinderHoughImpl.cxx
References fANNSelect, fFitCOP, fHist, fHistR, fHitInd, fNofBinsR, fNofBinsXY, fNofParts, CbmRichRingSelectAnn::Init(), and SetParameters().
Referenced by CbmRichRingFinderHough::CbmRichRingFinderHough().
CbmRichRingFinderHoughImpl& CbmRichRingFinderHoughImpl::operator= (const CbmRichRingFinderHoughImpl &) private
Assignment operator.
void CbmRichRingFinderHoughImpl::ReAssignSharedHits (int ringInd1, int ringInd2)
Reassign shared hits from two rings to only one of the rings.
Parameters
[in,out] ringInd1 Index of the first ring.
[in,out] ringInd2 Index of the second ring.
Definition at line 450 of file CbmRichRingFinderHoughImpl.cxx.
View newest version in sPHENIX GitHub at line 450 of file CbmRichRingFinderHoughImpl.cxx
References fData, fFoundRings, CbmRichRingLight::GetCenterX(), CbmRichRingLight::GetCenterY(), CbmRichRingLight::GetHitId(), GetHitIndex(), CbmRichRingLight::GetNofHits(), CbmRichRingLight::GetRadius(), and CbmRichRingLight::RemoveHit().
Referenced by RingSelection().
void CbmRichRingFinderHoughImpl::ReAssingSharedHits (int ringInd1, int ringInd2)
Definition at line 432 of file CbmRichRingFinderHoughImpl.cxx.
View newest version in sPHENIX GitHub at line 432 of file CbmRichRingFinderHoughImpl.cxx
References fData, fFoundRings, CbmRichRingLight::GetCenterX(), CbmRichRingLight::GetCenterY(), CbmRichRingLight::GetHitId(), GetHitIndex(), CbmRichRingLight::GetNofHits(), CbmRichRingLight::GetRadius(), and CbmRichRingLight::RemoveHit().
void CbmRichRingFinderHoughImpl::RemoveHitsAroundRing (int indmin, int indmax, CbmRichRingLight * ring)
void CbmRichRingFinderHoughImpl::RemoveHitsAroundRing (int indmin, int indmax, CbmRichRingLight * ring)
Set fIsUsed flag to true for hits attached to the ring.
Parameters
[in] indmin Minimum index of the hit in local area.
[in] indmax Maximum index of the hit in local area.
[in] ring Found ring.
Definition at line 388 of file CbmRichRingFinderHoughImpl.cxx.
View newest version in sPHENIX GitHub at line 388 of file CbmRichRingFinderHoughImpl.cxx
References fData, fMaxCutEl, fRmsCoeffEl, CbmRichRingLight::GetCenterX(), CbmRichRingLight::GetCenterY(), CbmRichRingLight::GetChi2(), CbmRichRingLight::GetNofHits(), and CbmRichRingLight::GetRadius().
Referenced by FindPeak().
void CbmRichRingFinderHoughImpl::RingSelection ()
void CbmRichRingFinderHoughImpl::RingSelection ()
Ring selection procedure.
Definition at line 408 of file CbmRichRingFinderHoughImpl.cxx.
View newest version in sPHENIX GitHub at line 408 of file CbmRichRingFinderHoughImpl.cxx
References fFoundRings, fUsedHitsAllCut, CbmRichRingLight::GetHitId(), CbmRichRingLight::GetNofHits(), it, ReAssignSharedHits(), and CbmRichRingLight::SetRecFlag().
Referenced by DoFind().
void CbmRichRingFinderHoughImpl::SetData (const std::vector< CbmRichHoughHit > & data) inline
Definition at line 121 of file CbmRichRingFinderHoughImpl.h.
View newest version in sPHENIX GitHub at line 121 of file CbmRichRingFinderHoughImpl.h
References data, and fData.
void CbmRichRingFinderHoughImpl::SetData (const vector< CbmRichHoughHit > & data) inline
Set array of hits.
Parameters
[in] data Array of hits.
Definition at line 207 of file CbmRichRingFinderHoughImpl.h.
View newest version in sPHENIX GitHub at line 207 of file CbmRichRingFinderHoughImpl.h
References data, and fData.
Referenced by CbmRichRingFinderHough::DoFind(), and CbmRichRingFinderHough::DoFindParallel().
void CbmRichRingFinderHoughImpl::SetParameters ()
Set parameters of the algorithm.
Definition at line 113 of file CbmRichRingFinderHoughImpl.cxx.
View newest version in sPHENIX GitHub at line 113 of file CbmRichRingFinderHoughImpl.cxx
References fAnnCut, fDr, fDx, fDy, fHTCut, fHTCutR, fMaxCutCOP, fMaxCutEl, fMaxDistance, fMaxDistanceSq, fMaxRadius, fMinDistance, fMinDistanceSq, fMinNofHitsInArea, fMinRadius, fNofBinsR, fNofBinsX, fNofBinsXY, fNofBinsY, fNofParts, fRmsCoeffCOP, fRmsCoeffEl, and fUsedHitsAllCut.
Referenced by Init().
void CbmRichRingFinderHoughImpl::SetParameters ()
Member Data Documentation
float CbmRichRingFinderHoughImpl::fAnnCut protected
Definition at line 69 of file CbmRichRingFinderHoughImpl.h.
View newest version in sPHENIX GitHub at line 69 of file CbmRichRingFinderHoughImpl.h
Referenced by FindPeak(), and SetParameters().
CbmRichRingSelectAnn* CbmRichRingFinderHoughImpl::fANNSelect protected
Definition at line 81 of file CbmRichRingFinderHoughImpl.h.
View newest version in sPHENIX GitHub at line 81 of file CbmRichRingFinderHoughImpl.h
Referenced by FindPeak(), Init(), and ~CbmRichRingFinderHoughImpl().
CbmRichRingSelectNeuralNet* CbmRichRingFinderHoughImpl::fANNSelect protected
Definition at line 101 of file CbmRichRingFinderHoughImpl.h.
View newest version in sPHENIX GitHub at line 101 of file CbmRichRingFinderHoughImpl.h
float CbmRichRingFinderHoughImpl::fCurMinX protected
Definition at line 72 of file CbmRichRingFinderHoughImpl.h.
View newest version in sPHENIX GitHub at line 72 of file CbmRichRingFinderHoughImpl.h
Referenced by FindPeak(), CbmRichRingFinderHoughSimd::HoughTransformGroup(), CbmRichRingFinderHoughSimd::HoughTransformReconstruction(), and HoughTransformReconstruction().
float CbmRichRingFinderHoughImpl::fCurMinY protected
Definition at line 73 of file CbmRichRingFinderHoughImpl.h.
View newest version in sPHENIX GitHub at line 73 of file CbmRichRingFinderHoughImpl.h
Referenced by FindPeak(), CbmRichRingFinderHoughSimd::HoughTransformGroup(), CbmRichRingFinderHoughSimd::HoughTransformReconstruction(), and HoughTransformReconstruction().
vector<CbmRichHoughHit> CbmRichRingFinderHoughImpl::fData protected
Definition at line 75 of file CbmRichRingFinderHoughImpl.h.
View newest version in sPHENIX GitHub at line 75 of file CbmRichRingFinderHoughImpl.h
Referenced by DefineLocalAreaAndHits(), DoFind(), FindPeak(), GetHitIndex(), CbmRichRingFinderHoughSimd::HoughTransformGroup(), CbmRichRingFinderHoughSimd::HoughTransformReconstruction(), HoughTransformReconstruction(), ReAssignSharedHits(), ReAssingSharedHits(), RemoveHitsAroundRing(), and SetData().
std::vector<CbmRichHoughHit> CbmRichRingFinderHoughImpl::fData protected
Definition at line 90 of file CbmRichRingFinderHoughImpl.h.
View newest version in sPHENIX GitHub at line 90 of file CbmRichRingFinderHoughImpl.h
std::vector<CbmRichHoughHit> CbmRichRingFinderHoughImpl::fDataPart1 protected
Rich hits.
Definition at line 91 of file CbmRichRingFinderHoughImpl.h.
View newest version in sPHENIX GitHub at line 91 of file CbmRichRingFinderHoughImpl.h
std::vector<CbmRichHoughHit> CbmRichRingFinderHoughImpl::fDataPart2 protected
Rich hits.
Definition at line 92 of file CbmRichRingFinderHoughImpl.h.
View newest version in sPHENIX GitHub at line 92 of file CbmRichRingFinderHoughImpl.h
float CbmRichRingFinderHoughImpl::fDr protected
Definition at line 52 of file CbmRichRingFinderHoughImpl.h.
View newest version in sPHENIX GitHub at line 52 of file CbmRichRingFinderHoughImpl.h
Referenced by FindPeak(), CbmRichRingFinderHoughSimd::HoughTransformGroup(), and SetParameters().
float CbmRichRingFinderHoughImpl::fDx protected
Definition at line 50 of file CbmRichRingFinderHoughImpl.h.
View newest version in sPHENIX GitHub at line 50 of file CbmRichRingFinderHoughImpl.h
Referenced by FindPeak(), CbmRichRingFinderHoughSimd::HoughTransformGroup(), and SetParameters().
float CbmRichRingFinderHoughImpl::fDy protected
Definition at line 51 of file CbmRichRingFinderHoughImpl.h.
View newest version in sPHENIX GitHub at line 51 of file CbmRichRingFinderHoughImpl.h
Referenced by FindPeak(), CbmRichRingFinderHoughSimd::HoughTransformGroup(), and SetParameters().
CbmRichRingFitterCOP* CbmRichRingFinderHoughImpl::fFitCOP protected
Definition at line 80 of file CbmRichRingFinderHoughImpl.h.
View newest version in sPHENIX GitHub at line 80 of file CbmRichRingFinderHoughImpl.h
Referenced by FindPeak(), Init(), and ~CbmRichRingFinderHoughImpl().
CbmRichRingFitterCOPLight* CbmRichRingFinderHoughImpl::fFitCOP protected
collect found rings
Definition at line 100 of file CbmRichRingFinderHoughImpl.h.
View newest version in sPHENIX GitHub at line 100 of file CbmRichRingFinderHoughImpl.h
vector<CbmRichRingLight*> CbmRichRingFinderHoughImpl::fFoundRings protected
Definition at line 79 of file CbmRichRingFinderHoughImpl.h.
View newest version in sPHENIX GitHub at line 79 of file CbmRichRingFinderHoughImpl.h
Referenced by DoFind(), FindPeak(), GetFoundRings(), ReAssignSharedHits(), ReAssingSharedHits(), and RingSelection().
std::vector<CbmRichRingLight*> CbmRichRingFinderHoughImpl::fFoundRings protected
Definition at line 98 of file CbmRichRingFinderHoughImpl.h.
View newest version in sPHENIX GitHub at line 98 of file CbmRichRingFinderHoughImpl.h
vector<unsigned short> CbmRichRingFinderHoughImpl::fHist protected
Definition at line 76 of file CbmRichRingFinderHoughImpl.h.
View newest version in sPHENIX GitHub at line 76 of file CbmRichRingFinderHoughImpl.h
Referenced by DefineLocalAreaAndHits(), FindPeak(), CbmRichRingFinderHoughSimd::HoughTransformGroup(), and Init().
std::vector<unsigned short> CbmRichRingFinderHoughImpl::fHist protected
Rich hits.
Definition at line 94 of file CbmRichRingFinderHoughImpl.h.
View newest version in sPHENIX GitHub at line 94 of file CbmRichRingFinderHoughImpl.h
vector<unsigned short> CbmRichRingFinderHoughImpl::fHistR protected
Definition at line 77 of file CbmRichRingFinderHoughImpl.h.
View newest version in sPHENIX GitHub at line 77 of file CbmRichRingFinderHoughImpl.h
Referenced by DefineLocalAreaAndHits(), FindPeak(), CbmRichRingFinderHoughSimd::HoughTransformGroup(), and Init().
std::vector<unsigned short> CbmRichRingFinderHoughImpl::fHistR protected
Definition at line 95 of file CbmRichRingFinderHoughImpl.h.
View newest version in sPHENIX GitHub at line 95 of file CbmRichRingFinderHoughImpl.h
unsigned short CbmRichRingFinderHoughImpl::fHitCut protected
Definition at line 70 of file CbmRichRingFinderHoughImpl.h.
View newest version in sPHENIX GitHub at line 70 of file CbmRichRingFinderHoughImpl.h
unsigned short CbmRichRingFinderHoughImpl::fHitCutR protected
Definition at line 74 of file CbmRichRingFinderHoughImpl.h.
View newest version in sPHENIX GitHub at line 74 of file CbmRichRingFinderHoughImpl.h
vector< vector<unsigned short> > CbmRichRingFinderHoughImpl::fHitInd protected
Definition at line 78 of file CbmRichRingFinderHoughImpl.h.
View newest version in sPHENIX GitHub at line 78 of file CbmRichRingFinderHoughImpl.h
Referenced by DefineLocalAreaAndHits(), CbmRichRingFinderHoughSimd::HoughTransformGroup(), and Init().
std::vector< std::vector<unsigned short> > CbmRichRingFinderHoughImpl::fHitInd protected
Definition at line 96 of file CbmRichRingFinderHoughImpl.h.
View newest version in sPHENIX GitHub at line 96 of file CbmRichRingFinderHoughImpl.h
unsigned short CbmRichRingFinderHoughImpl::fHTCut protected
Definition at line 57 of file CbmRichRingFinderHoughImpl.h.
View newest version in sPHENIX GitHub at line 57 of file CbmRichRingFinderHoughImpl.h
Referenced by FindPeak(), and SetParameters().
unsigned short CbmRichRingFinderHoughImpl::fHTCutR protected
Definition at line 60 of file CbmRichRingFinderHoughImpl.h.
View newest version in sPHENIX GitHub at line 60 of file CbmRichRingFinderHoughImpl.h
Referenced by FindPeak(), and SetParameters().
float CbmRichRingFinderHoughImpl::fMaxCutCOP protected
Definition at line 67 of file CbmRichRingFinderHoughImpl.h.
View newest version in sPHENIX GitHub at line 67 of file CbmRichRingFinderHoughImpl.h
Referenced by FindPeak(), and SetParameters().
float CbmRichRingFinderHoughImpl::fMaxCutEl protected
Definition at line 65 of file CbmRichRingFinderHoughImpl.h.
View newest version in sPHENIX GitHub at line 65 of file CbmRichRingFinderHoughImpl.h
Referenced by RemoveHitsAroundRing(), and SetParameters().
float CbmRichRingFinderHoughImpl::fMaxDistance protected
Definition at line 42 of file CbmRichRingFinderHoughImpl.h.
View newest version in sPHENIX GitHub at line 42 of file CbmRichRingFinderHoughImpl.h
Referenced by DefineLocalAreaAndHits(), CbmRichRingFinderHoughSimd::HoughTransformReconstruction(), HoughTransformReconstruction(), and SetParameters().
float CbmRichRingFinderHoughImpl::fMaxDistanceSq protected
= fMinDistance*fMinDistance
Definition at line 45 of file CbmRichRingFinderHoughImpl.h.
View newest version in sPHENIX GitHub at line 45 of file CbmRichRingFinderHoughImpl.h
Referenced by DefineLocalAreaAndHits(), CbmRichRingFinderHoughSimd::HoughTransformGroup(), and SetParameters().
float CbmRichRingFinderHoughImpl::fMaxRadius protected
Definition at line 48 of file CbmRichRingFinderHoughImpl.h.
View newest version in sPHENIX GitHub at line 48 of file CbmRichRingFinderHoughImpl.h
Referenced by SetParameters().
float CbmRichRingFinderHoughImpl::fMinDistance protected
Definition at line 43 of file CbmRichRingFinderHoughImpl.h.
View newest version in sPHENIX GitHub at line 43 of file CbmRichRingFinderHoughImpl.h
Referenced by SetParameters().
float CbmRichRingFinderHoughImpl::fMinDistanceSq protected
Definition at line 44 of file CbmRichRingFinderHoughImpl.h.
View newest version in sPHENIX GitHub at line 44 of file CbmRichRingFinderHoughImpl.h
Referenced by CbmRichRingFinderHoughSimd::HoughTransformGroup(), and SetParameters().
unsigned short CbmRichRingFinderHoughImpl::fMinNofHitsInArea protected
Definition at line 62 of file CbmRichRingFinderHoughImpl.h.
View newest version in sPHENIX GitHub at line 62 of file CbmRichRingFinderHoughImpl.h
Referenced by DefineLocalAreaAndHits(), CbmRichRingFinderHoughSimd::HoughTransformGroup(), and SetParameters().
float CbmRichRingFinderHoughImpl::fMinRadius protected
Definition at line 47 of file CbmRichRingFinderHoughImpl.h.
View newest version in sPHENIX GitHub at line 47 of file CbmRichRingFinderHoughImpl.h
Referenced by SetParameters().
unsigned short CbmRichRingFinderHoughImpl::fNofBinsR protected
Definition at line 59 of file CbmRichRingFinderHoughImpl.h.
View newest version in sPHENIX GitHub at line 59 of file CbmRichRingFinderHoughImpl.h
Referenced by DefineLocalAreaAndHits(), CbmRichRingFinderHoughSimd::HoughTransformGroup(), Init(), and SetParameters().
unsigned short CbmRichRingFinderHoughImpl::fNofBinsX protected
Definition at line 53 of file CbmRichRingFinderHoughImpl.h.
View newest version in sPHENIX GitHub at line 53 of file CbmRichRingFinderHoughImpl.h
Referenced by FindPeak(), CbmRichRingFinderHoughSimd::HoughTransformGroup(), and SetParameters().
unsigned short CbmRichRingFinderHoughImpl::fNofBinsXY protected
Definition at line 55 of file CbmRichRingFinderHoughImpl.h.
View newest version in sPHENIX GitHub at line 55 of file CbmRichRingFinderHoughImpl.h
Referenced by DefineLocalAreaAndHits(), CbmRichRingFinderHoughSimd::HoughTransformGroup(), Init(), and SetParameters().
unsigned short CbmRichRingFinderHoughImpl::fNofBinsY protected
Definition at line 54 of file CbmRichRingFinderHoughImpl.h.
View newest version in sPHENIX GitHub at line 54 of file CbmRichRingFinderHoughImpl.h
Referenced by SetParameters().
unsigned short CbmRichRingFinderHoughImpl::fNofParts protected
Definition at line 40 of file CbmRichRingFinderHoughImpl.h.
View newest version in sPHENIX GitHub at line 40 of file CbmRichRingFinderHoughImpl.h
Referenced by DefineLocalAreaAndHits(), Init(), and SetParameters().
const unsigned short CbmRichRingFinderHoughImpl::fNofParts = 2 static protected
Definition at line 53 of file CbmRichRingFinderHoughImpl.h.
View newest version in sPHENIX GitHub at line 53 of file CbmRichRingFinderHoughImpl.h
float CbmRichRingFinderHoughImpl::fRmsCoeffCOP protected
Definition at line 66 of file CbmRichRingFinderHoughImpl.h.
View newest version in sPHENIX GitHub at line 66 of file CbmRichRingFinderHoughImpl.h
Referenced by FindPeak(), and SetParameters().
float CbmRichRingFinderHoughImpl::fRmsCoeffEl protected
Definition at line 64 of file CbmRichRingFinderHoughImpl.h.
View newest version in sPHENIX GitHub at line 64 of file CbmRichRingFinderHoughImpl.h
Referenced by RemoveHitsAroundRing(), and SetParameters().
float CbmRichRingFinderHoughImpl::fUsedHitsAllCut protected
Definition at line 70 of file CbmRichRingFinderHoughImpl.h.
View newest version in sPHENIX GitHub at line 70 of file CbmRichRingFinderHoughImpl.h
Referenced by RingSelection(), and SetParameters().
float CbmRichRingFinderHoughImpl::fUsedHitsCut protected
Definition at line 84 of file CbmRichRingFinderHoughImpl.h.
View newest version in sPHENIX GitHub at line 84 of file CbmRichRingFinderHoughImpl.h
const unsigned short CbmRichRingFinderHoughImpl::kMAX_NOF_HITS = 65500 static protected
Definition at line 52 of file CbmRichRingFinderHoughImpl.h.
View newest version in sPHENIX GitHub at line 52 of file CbmRichRingFinderHoughImpl.h
const unsigned short CbmRichRingFinderHoughImpl::MAX_NOF_HITS = 65000 static protected
Definition at line 37 of file CbmRichRingFinderHoughImpl.h.
View newest version in sPHENIX GitHub at line 37 of file CbmRichRingFinderHoughImpl.h
Referenced by DoFind().
The documentation for this class was generated from the following files:
EicRoot/blob/master/rich/finder/CbmRichRingFinderHoughImpl.h
EicRoot/blob/master/rich/standalone/algorithm/CbmRichRingFinderHoughImpl.h
EicRoot/blob/master/rich/finder/CbmRichRingFinderHoughImpl.cxx
EicRoot/blob/master/rich/standalone/algorithm/CbmRichRingFinderHoughImpl.cxx