EIC Software: FairGeaneUtil Class Reference
FairGeaneUtil Class Reference
#include <EicRoot/blob/master/trackbase/FairGeaneUtil.h>
Public Types
typedef Double_t sixMat [6][6]
typedef Double_t fiveMat [5][5]
Public Member Functions
FairGeaneUtil ()
~FairGeaneUtil ()
void FromPtToSC (Double_t PC[3], Double_t RC[15], Double_t *PD, Double_t *RD, Int_t &IERR)
void FromPtToSD (Double_t PD[3], Double_t RD[15], Double_t H[3], Int_t CH, Double_t SPU, Double_t DJ[2], Double_t DK[2], Int_t &IERR, Double_t *PC, Double_t *RC)
void FromSCToPt (Double_t PC[3], Double_t RC[15], Double_t *PD, Double_t *RD, Int_t &IERR)
void FromSCToSD (Double_t PC[3], Double_t RC[15], Double_t H[3], Int_t CH, Double_t DJ[3], Double_t DK[3], Int_t &IERR, Double_t &SPU, Double_t *PD, Double_t *RD)
void FromSD1ToSD2 (Double_t PD1[2], Double_t RD1[15], Double_t H[2], Int_t CH, Double_t SP1, Double_t DJ1[2], Double_t DK1[2], Double_t DJ2[2], Double_t DK2[2], Int_t &IERR, Double_t &SP2, Double_t *PD2, Double_t *RD2)
void FromSDToPt (Double_t PD[3], Double_t RD[15], Double_t H[3], Int_t CH, Double_t SPU, Double_t DJ[3], Double_t DK[3], Int_t &IERR, Double_t *PC, Double_t *RC)
void FromSDToSC (Double_t PD[3], Double_t RD[15], Double_t H[3], Int_t CH, Double_t SPU, Double_t DJ[3], Double_t DK[3], Int_t &IERR, Double_t *PC, Double_t *RC)
void FromSCToMars (Double_t PC[3], Double_t RC[15], Double_t H[3], Int_t CH, Double_t *PD, sixMat &RD)
void FromMarsToSC (Double_t PD[3], Double_t RD[6][6], Double_t H[3], Int_t CH, Double_t *PC, Double_t *RC)
void FromSDToMars (Double_t PC[3], Double_t RC[15], Double_t H[3], Int_t CH, Double_t SP1, Double_t DJ1[3], Double_t DK1[3], Double_t *PD, sixMat &RD)
void FromMarsToSD (Double_t PD[3], Double_t RD[6][6], Double_t H[3], Int_t CH, Double_t DJ1[3], Double_t DK1[3], Int_t &IERR, Double_t &SP1, Double_t *PC, Double_t *RC)
void FromMat25ToVec15 (Double_t A[5][5], Double_t *V)
void FromMatToVec (Double_t A[5][5], Double_t *V)
void FromVec15ToMat25 (Double_t V[15], fiveMat &A)
void FromVecToMat (fiveMat &A, Double_t V[25])
void SymmProd (Double_t A[25], Double_t S[15], Double_t *R)
TVector3 FromMARSToSDCoord (TVector3 xyz, TVector3 o, TVector3 di, TVector3 dj, TVector3 dk)
TVector3 FromSDToMARSCoord (TVector3 uvw, TVector3 o, TVector3 di, TVector3 dj, TVector3 dk)
ClassDef (FairGeaneUtil, 1)
Detailed Description
Definition at line 8 of file FairGeaneUtil.h.
View newest version in sPHENIX GitHub at line 8 of file FairGeaneUtil.h
Member Typedef Documentation
typedef Double_t FairGeaneUtil::fiveMat[5][5]
Definition at line 70 of file FairGeaneUtil.h.
View newest version in sPHENIX GitHub at line 70 of file FairGeaneUtil.h
typedef Double_t FairGeaneUtil::sixMat[6][6]
Definition at line 46 of file FairGeaneUtil.h.
View newest version in sPHENIX GitHub at line 46 of file FairGeaneUtil.h
Constructor & Destructor Documentation
FairGeaneUtil::FairGeaneUtil ()
Definition at line 13 of file FairGeaneUtil.cxx.
View newest version in sPHENIX GitHub at line 13 of file FairGeaneUtil.cxx
FairGeaneUtil::~FairGeaneUtil ()
Definition at line 15 of file FairGeaneUtil.cxx.
View newest version in sPHENIX GitHub at line 15 of file FairGeaneUtil.cxx
Member Function Documentation
FairGeaneUtil::ClassDef (FairGeaneUtil , 1)
void FairGeaneUtil::FromMarsToSC (Double_t PD[3], Double_t RD[6][6], Double_t H[3], Int_t CH, Double_t * PC, Double_t * RC)
Definition at line 975 of file FairGeaneUtil.cxx.
View newest version in sPHENIX GitHub at line 975 of file FairGeaneUtil.cxx
References Acts::UnitConstants::e, FromMarsToSD(), and FromSDToSC().
Referenced by FairTrackParH::FairTrackParH().
void FairGeaneUtil::FromMarsToSD (Double_t PD[3], Double_t RD[6][6], Double_t H[3], Int_t CH, Double_t DJ1[3], Double_t DK1[3], Int_t & IERR, Double_t & SP1, Double_t * PC, Double_t * RC)
Definition at line 1156 of file FairGeaneUtil.cxx.
View newest version in sPHENIX GitHub at line 1156 of file FairGeaneUtil.cxx
References Acts::UnitConstants::e, FromMat25ToVec15(), I, k, and lit::Sign().
Referenced by FairTrackParP::FairTrackParP(), FromMarsToSC(), and FairTrackParP::SetTrackPar().
TVector3 FairGeaneUtil::FromMARSToSDCoord (TVector3 xyz, TVector3 o, TVector3 di, TVector3 dj, TVector3 dk)
Definition at line 1762 of file FairGeaneUtil.cxx.
View newest version in sPHENIX GitHub at line 1762 of file FairGeaneUtil.cxx
References matrix(), and Acts::Test::origin().
Referenced by FairTrackParP::FairTrackParP(), and FairTrackParP::SetTrackPar().
void FairGeaneUtil::FromMat25ToVec15 (Double_t A[5][5], Double_t * V)
Definition at line 1635 of file FairGeaneUtil.cxx.
View newest version in sPHENIX GitHub at line 1635 of file FairGeaneUtil.cxx
Referenced by GeaneTrackRep::extrapolateToLine(), FromMarsToSD(), and GeaneTrackRep::getPosMomCov().
void FairGeaneUtil::FromMatToVec (Double_t A[5][5], Double_t * V)
Definition at line 1669 of file FairGeaneUtil.cxx.
View newest version in sPHENIX GitHub at line 1669 of file FairGeaneUtil.cxx
Referenced by FromPtToSC(), FromPtToSD(), FromSCToPt(), FromSCToSD(), FromSD1ToSD2(), FromSDToPt(), and FromSDToSC().
void FairGeaneUtil::FromPtToSC (Double_t PC[3], Double_t RC[15], Double_t * PD, Double_t * RD, Int_t & IERR)
Definition at line 17 of file FairGeaneUtil.cxx.
View newest version in sPHENIX GitHub at line 17 of file FairGeaneUtil.cxx
References cos(), Acts::UnitConstants::e, FromMatToVec(), I, and SymmProd().
void FairGeaneUtil::FromPtToSD (Double_t PD[3], Double_t RD[15], Double_t H[3], Int_t CH, Double_t SPU, Double_t DJ[2], Double_t DK[2], Int_t & IERR, Double_t * PC, Double_t * RC)
Definition at line 89 of file FairGeaneUtil.cxx.
View newest version in sPHENIX GitHub at line 89 of file FairGeaneUtil.cxx
References Acts::UnitConstants::e, FromMatToVec(), I, and SymmProd().
void FairGeaneUtil::FromSCToMars (Double_t PC[3], Double_t RC[15], Double_t H[3], Int_t CH, Double_t * PD, sixMat & RD)
Definition at line 1064 of file FairGeaneUtil.cxx.
View newest version in sPHENIX GitHub at line 1064 of file FairGeaneUtil.cxx
References Acts::UnitConstants::e, FromSCToSD(), FromSDToMars(), and I.
Referenced by FairTrackParH::FairTrackParH(), and FairTrackParH::SetTrackPar().
void FairGeaneUtil::FromSCToPt (Double_t PC[3], Double_t RC[15], Double_t * PD, Double_t * RD, Int_t & IERR)
Definition at line 225 of file FairGeaneUtil.cxx.
View newest version in sPHENIX GitHub at line 225 of file FairGeaneUtil.cxx
References cos(), Acts::UnitConstants::e, FromMatToVec(), I, and SymmProd().
void FairGeaneUtil::FromSCToSD (Double_t PC[3], Double_t RC[15], Double_t H[3], Int_t CH, Double_t DJ[3], Double_t DK[3], Int_t & IERR, Double_t & SPU, Double_t * PD, Double_t * RD)
Definition at line 297 of file FairGeaneUtil.cxx.
View newest version in sPHENIX GitHub at line 297 of file FairGeaneUtil.cxx
References Acts::UnitConstants::e, FromMatToVec(), I, and SymmProd().
Referenced by FairTrackParP::FairTrackParP(), and FromSCToMars().
void FairGeaneUtil::FromSD1ToSD2 (Double_t PD1[2], Double_t RD1[15], Double_t H[2], Int_t CH, Double_t SP1, Double_t DJ1[2], Double_t DK1[2], Double_t DJ2[2], Double_t DK2[2], Int_t & IERR, Double_t & SP2, Double_t * PD2, Double_t * RD2)
Definition at line 443 of file FairGeaneUtil.cxx.
View newest version in sPHENIX GitHub at line 443 of file FairGeaneUtil.cxx
References Acts::UnitConstants::e, FromMatToVec(), I, and SymmProd().
void FairGeaneUtil::FromSDToMars (Double_t PC[3], Double_t RC[15], Double_t H[3], Int_t CH, Double_t SP1, Double_t DJ1[3], Double_t DK1[3], Double_t * PD, sixMat & RD)
Definition at line 1405 of file FairGeaneUtil.cxx.
View newest version in sPHENIX GitHub at line 1405 of file FairGeaneUtil.cxx
References FromVec15ToMat25(), I, and k.
Referenced by FairTrackParP::FairTrackParP(), FromSCToMars(), and FairTrackParP::SetTrackPar().
TVector3 FairGeaneUtil::FromSDToMARSCoord (TVector3 uvw, TVector3 o, TVector3 di, TVector3 dj, TVector3 dk)
Definition at line 1798 of file FairGeaneUtil.cxx.
View newest version in sPHENIX GitHub at line 1798 of file FairGeaneUtil.cxx
References matrix(), and Acts::Test::origin().
Referenced by FairTrackParP::FairTrackParP(), and FairTrackParP::SetTrackPar().
void FairGeaneUtil::FromSDToPt (Double_t PD[3], Double_t RD[15], Double_t H[3], Int_t CH, Double_t SPU, Double_t DJ[3], Double_t DK[3], Int_t & IERR, Double_t * PC, Double_t * RC)
Definition at line 623 of file FairGeaneUtil.cxx.
View newest version in sPHENIX GitHub at line 623 of file FairGeaneUtil.cxx
References Acts::UnitConstants::e, FromMatToVec(), I, and SymmProd().
void FairGeaneUtil::FromSDToSC (Double_t PD[3], Double_t RD[15], Double_t H[3], Int_t CH, Double_t SPU, Double_t DJ[3], Double_t DK[3], Int_t & IERR, Double_t * PC, Double_t * RC)
Definition at line 760 of file FairGeaneUtil.cxx.
View newest version in sPHENIX GitHub at line 760 of file FairGeaneUtil.cxx
References Acts::UnitConstants::e, FromMatToVec(), I, and SymmProd().
Referenced by FairTrackParH::FairTrackParH(), and FromMarsToSC().
void FairGeaneUtil::FromVec15ToMat25 (Double_t V[15], fiveMat & A)
Definition at line 895 of file FairGeaneUtil.cxx.
View newest version in sPHENIX GitHub at line 895 of file FairGeaneUtil.cxx
References I, and k.
Referenced by FromSDToMars().
void FairGeaneUtil::FromVecToMat (fiveMat & A, Double_t V[25])
Definition at line 932 of file FairGeaneUtil.cxx.
View newest version in sPHENIX GitHub at line 932 of file FairGeaneUtil.cxx
Referenced by FairGeanePro::Propagate().
void FairGeaneUtil::SymmProd (Double_t A[25], Double_t S[15], Double_t * R)
Definition at line 1712 of file FairGeaneUtil.cxx.
View newest version in sPHENIX GitHub at line 1712 of file FairGeaneUtil.cxx
References I, T1, T2, T3, T4, and T5.
Referenced by FromPtToSC(), FromPtToSD(), FromSCToPt(), FromSCToSD(), FromSD1ToSD2(), FromSDToPt(), and FromSDToSC().
The documentation for this class was generated from the following files:
EicRoot/blob/master/trackbase/FairGeaneUtil.h
EicRoot/blob/master/trackbase/FairGeaneUtil.cxx