EIC Software: GFFieldManager Class Reference
GFFieldManager Class Reference
Genfit
Singleton which provides access to magnetic field for track representations.
#include <EicRoot/blob/master/genfit/GFFieldManager.h>
Public Member Functions
GFAbsBField * getField ()
void init (GFAbsBField *b)
set the magntic field here. Magnetic field classes must be derived from GFAbsBField
Static Public Member Functions
static TVector3 getFieldVal (const TVector3 &x)
static GFFieldManager * getInstance ()
Private Member Functions
GFFieldManager ()
Static Private Attributes
static GFFieldManager * fInstance = NULL
static GFAbsBField * fField = NULL
Detailed Description
Singleton which provides access to magnetic field for track representations.
Author
Christian Höppner (Technische Universität München, original author)
Sebastian Neubert (Technische Universität München, original author)
Definition at line 37 of file GFFieldManager.h.
View newest version in sPHENIX GitHub at line 37 of file GFFieldManager.h
Constructor & Destructor Documentation
GFFieldManager::GFFieldManager () inline private
Definition at line 39 of file GFFieldManager.h.
View newest version in sPHENIX GitHub at line 39 of file GFFieldManager.h
Referenced by getInstance().
Member Function Documentation
GFAbsBField* GFFieldManager::getField () inline
Definition at line 44 of file GFFieldManager.h.
View newest version in sPHENIX GitHub at line 44 of file GFFieldManager.h
References fField.
static TVector3 GFFieldManager::getFieldVal (const TVector3 & x) inline static
Definition at line 52 of file GFFieldManager.h.
View newest version in sPHENIX GitHub at line 52 of file GFFieldManager.h
References fField, fInstance, and GFAbsBField::get().
Referenced by RKTrackRep::RKutta().
static GFFieldManager* GFFieldManager::getInstance () inline static
Definition at line 69 of file GFFieldManager.h.
View newest version in sPHENIX GitHub at line 69 of file GFFieldManager.h
References fInstance, and GFFieldManager().
Referenced by PndRecoDafFit::Init(), and PndRecoKalmanFit::Init().
void GFFieldManager::init (GFAbsBField * b) inline
set the magntic field here. Magnetic field classes must be derived from GFAbsBField
Definition at line 65 of file GFFieldManager.h.
View newest version in sPHENIX GitHub at line 65 of file GFFieldManager.h
References fField.
Referenced by PndRecoDafFit::Init(), and PndRecoKalmanFit::Init().
Member Data Documentation
GFAbsBField * GFFieldManager::fField = NULL static private
Definition at line 41 of file GFFieldManager.h.
View newest version in sPHENIX GitHub at line 41 of file GFFieldManager.h
Referenced by getField(), getFieldVal(), and init().
GFFieldManager * GFFieldManager::fInstance = NULL static private
Definition at line 40 of file GFFieldManager.h.
View newest version in sPHENIX GitHub at line 40 of file GFFieldManager.h
Referenced by getFieldVal(), and getInstance().
The documentation for this class was generated from the following files:
EicRoot/blob/master/genfit/GFFieldManager.h
EicRoot/blob/master/genfit/GFFieldManager.cxx