EIC Software: FairParSet Class Reference
FairParSet Class Reference
#include <EicRoot/blob/master/parbase/FairParSet.h>
Public Member Functions
FairParSet (const char *name="", const char *title="", const char *context="")
virtual ~FairParSet ()
virtual Bool_t init ()
virtual Bool_t init (FairParIo *io)
virtual Int_t write ()
virtual Int_t write (FairParIo *)
virtual void clear ()
virtual void print ()
const char * getDetectorName ()
void resetInputVersions ()
void setInputVersion (Int_t v=-1, Int_t i=0)
Int_t getInputVersion (Int_t i)
void setStatic (Bool_t flag=kTRUE)
Bool_t isStatic ()
void setChanged (Bool_t flag=kTRUE)
Bool_t hasChanged ()
const char * getParamContext () const
void setAuthor (const char *s)
const char * getAuthor () const
void setDescription (const char *s)
const char * getDescription () const
void copyComment (FairParSet &r)
Protected Attributes
TString detName
Int_t versions [3]
name of the detector the container belongs to
Bool_t status
versions of container in the 2 possible inputs
Bool_t changed
static flag
TString paramContext
flag is kTRUE if parameters have changed
TString author
TString description
FairLogger * fLogger
Private Member Functions
FairParSet & operator= (const FairParSet &)
FairParSet (const FairParSet &)
Detailed Description
Definition at line 10 of file FairParSet.h.
View newest version in sPHENIX GitHub at line 10 of file FairParSet.h
Constructor & Destructor Documentation
FairParSet::FairParSet (const char * name = "", const char * title = "", const char * context = "")
virtual FairParSet::~FairParSet () inline virtual
Definition at line 24 of file FairParSet.h.
View newest version in sPHENIX GitHub at line 24 of file FairParSet.h
FairParSet::FairParSet (const FairParSet &) private
Member Function Documentation
virtual void FairParSet::clear (void) inline virtual
Reimplemented in CbmGeoRichPar, FairBaseParSet, PndSensorNamePar, EicGeoPar, and PndGeoPassivePar.
Definition at line 29 of file FairParSet.h.
View newest version in sPHENIX GitHub at line 29 of file FairParSet.h
Referenced by FairDetParRootFileIo::read().
void FairParSet::copyComment (FairParSet & r) inline
Definition at line 54 of file FairParSet.h.
View newest version in sPHENIX GitHub at line 54 of file FairParSet.h
References author, description, getAuthor(), and getDescription().
const char* FairParSet::getAuthor () const inline
Definition at line 49 of file FairParSet.h.
View newest version in sPHENIX GitHub at line 49 of file FairParSet.h
References author.
Referenced by copyComment(), FairDetParTSQLIo::write(), and FairDetParAsciiFileIo::writeComment().
const char* FairParSet::getDescription () const inline
Definition at line 52 of file FairParSet.h.
View newest version in sPHENIX GitHub at line 52 of file FairParSet.h
References description.
Referenced by copyComment(), FairDetParTSQLIo::write(), and FairDetParAsciiFileIo::writeComment().
const char* FairParSet::getDetectorName () inline
Definition at line 31 of file FairParSet.h.
View newest version in sPHENIX GitHub at line 31 of file FairParSet.h
References detName.
Referenced by FairDetParTSQLIo::write().
Int_t FairParSet::getInputVersion (Int_t i) inline
Definition at line 37 of file FairParSet.h.
View newest version in sPHENIX GitHub at line 37 of file FairParSet.h
References versions.
Referenced by FairRuntimeDb::findOutputVersion(), FairDetParRootFileIo::read(), and FairRuntimeDb::writeContainer().
const char* FairParSet::getParamContext () const inline
Definition at line 46 of file FairParSet.h.
View newest version in sPHENIX GitHub at line 46 of file FairParSet.h
References paramContext.
Referenced by FairDetParTSQLIo::write(), FairGenericParAsciiFileIo::writeGenericSet(), and FairGenericParTSQLIo::writeSet().
Bool_t FairParSet::hasChanged () inline
Definition at line 44 of file FairParSet.h.
View newest version in sPHENIX GitHub at line 44 of file FairParSet.h
References changed.
Referenced by FairRuntimeDb::findOutputVersion(), and FairRuntimeDb::writeContainer().
Bool_t FairParSet::init () virtual
Definition at line 33 of file FairParSet.cxx.
View newest version in sPHENIX GitHub at line 33 of file FairParSet.cxx
References FairLogger::Error(), fLogger, FairRuntimeDb::getFirstInput(), FairRuntimeDb::getSecondInput(), FairRuntimeDb::instance(), MESSAGE_ORIGIN, and setInputVersion().
Referenced by FairRuntimeDb::initContainers().
virtual Bool_t FairParSet::init (FairParIo * io) inline virtual
Reimplemented in FairParGenericSet.
Definition at line 26 of file FairParSet.h.
View newest version in sPHENIX GitHub at line 26 of file FairParSet.h
Bool_t FairParSet::isStatic () inline
Definition at line 42 of file FairParSet.h.
View newest version in sPHENIX GitHub at line 42 of file FairParSet.h
References status.
Referenced by FairRuntimeDb::initContainers(), and FairRuntimeDb::resetInputVersions().
FairParSet& FairParSet::operator= (const FairParSet &) private
void FairParSet::print () virtual
Definition at line 71 of file FairParSet.cxx.
View newest version in sPHENIX GitHub at line 71 of file FairParSet.cxx
References author, changed, description, paramContext, status, and versions.
void FairParSet::resetInputVersions ()
Definition at line 86 of file FairParSet.cxx.
View newest version in sPHENIX GitHub at line 86 of file FairParSet.cxx
References changed, status, and versions.
Referenced by FairRuntimeDb::resetInputVersions().
void FairParSet::setAuthor (const char * s) inline
Definition at line 48 of file FairParSet.h.
View newest version in sPHENIX GitHub at line 48 of file FairParSet.h
References author, and Acts::UnitConstants::s.
Referenced by FairDetParAsciiFileIo::readComment().
void FairParSet::setChanged (Bool_t flag = kTRUE) inline
Definition at line 43 of file FairParSet.h.
View newest version in sPHENIX GitHub at line 43 of file FairParSet.h
References changed.
Referenced by PndSensorNamePar::AddSensorName(), ClassImp(), PndMagnet::ConstructASCIIGeometry(), CbmRich::ConstructAsciiGeometry(), PndTarget::ConstructGeometry(), EicDetector::ConstructGeometry(), PndConstField::FillParContainer(), PndMultiField::FillParContainer(), PndTransMap::FillParContainer(), FairRunSim::Init(), FairDetParRootFileIo::read(), FairDetParTSQLIo::setChanged(), FairDetParRootFileIo::write(), FairRuntimeDb::writeContainer(), and FairGenericParAsciiFileIo::writeGenericSet().
void FairParSet::setDescription (const char * s) inline
Definition at line 51 of file FairParSet.h.
View newest version in sPHENIX GitHub at line 51 of file FairParSet.h
References description, and Acts::UnitConstants::s.
Referenced by FairDetParAsciiFileIo::readComment(), and FairDetParTSQLIo::setChanged().
void FairParSet::setInputVersion (Int_t v = -1, Int_t i = 0) inline
Definition at line 34 of file FairParSet.h.
View newest version in sPHENIX GitHub at line 34 of file FairParSet.h
References v, and versions.
Referenced by PndSensorNamePar::AddSensorName(), ClassImp(), PndMagnet::ConstructASCIIGeometry(), CbmRich::ConstructAsciiGeometry(), PndTarget::ConstructGeometry(), EicDetector::ConstructGeometry(), PndConstField::FillParContainer(), PndMultiField::FillParContainer(), PndTransMap::FillParContainer(), init(), FairRunSim::Init(), FairDetParRootFileIo::read(), and PndMultiFieldPar::SetParameters().
void FairParSet::setStatic (Bool_t flag = kTRUE) inline
Definition at line 41 of file FairParSet.h.
View newest version in sPHENIX GitHub at line 41 of file FairParSet.h
References status.
Referenced by FairRuntimeDb::setContainersStatic().
Int_t FairParSet::write () virtual
Definition at line 59 of file FairParSet.cxx.
View newest version in sPHENIX GitHub at line 59 of file FairParSet.cxx
References FairLogger::Error(), fLogger, FairRuntimeDb::getOutput(), FairRuntimeDb::instance(), and MESSAGE_ORIGIN.
Referenced by FairRuntimeDb::writeContainer().
virtual Int_t FairParSet::write (FairParIo *) inline virtual
Reimplemented in FairParGenericSet.
Definition at line 28 of file FairParSet.h.
View newest version in sPHENIX GitHub at line 28 of file FairParSet.h
Member Data Documentation
TString FairParSet::author protected
Definition at line 18 of file FairParSet.h.
View newest version in sPHENIX GitHub at line 18 of file FairParSet.h
Referenced by copyComment(), getAuthor(), print(), FairParGenericSet::printParams(), and setAuthor().
Bool_t FairParSet::changed protected
static flag
Definition at line 16 of file FairParSet.h.
View newest version in sPHENIX GitHub at line 16 of file FairParSet.h
Referenced by hasChanged(), print(), resetInputVersions(), and setChanged().
TString FairParSet::description protected
Definition at line 19 of file FairParSet.h.
View newest version in sPHENIX GitHub at line 19 of file FairParSet.h
Referenced by copyComment(), getDescription(), print(), FairParGenericSet::printParams(), and setDescription().
TString FairParSet::detName protected
Definition at line 13 of file FairParSet.h.
View newest version in sPHENIX GitHub at line 13 of file FairParSet.h
Referenced by getDetectorName().
FairLogger* FairParSet::fLogger protected
Fair Logger
Definition at line 21 of file FairParSet.h.
View newest version in sPHENIX GitHub at line 21 of file FairParSet.h
Referenced by init(), and write().
TString FairParSet::paramContext protected
flag is kTRUE if parameters have changed
Definition at line 17 of file FairParSet.h.
View newest version in sPHENIX GitHub at line 17 of file FairParSet.h
Referenced by getParamContext(), print(), and FairParGenericSet::printParams().
Bool_t FairParSet::status protected
versions of container in the 2 possible inputs
Definition at line 15 of file FairParSet.h.
View newest version in sPHENIX GitHub at line 15 of file FairParSet.h
Referenced by isStatic(), print(), resetInputVersions(), and setStatic().
Int_t FairParSet::versions[3] protected
name of the detector the container belongs to
Definition at line 14 of file FairParSet.h.
View newest version in sPHENIX GitHub at line 14 of file FairParSet.h
Referenced by getInputVersion(), print(), resetInputVersions(), and setInputVersion().
The documentation for this class was generated from the following files:
EicRoot/blob/master/parbase/FairParSet.h
EicRoot/blob/master/parbase/FairParSet.cxx