EIC Software: EicRoot/blob/master/eic/cad/elmer/plugins/egutils.h File Reference
egutils.h File Reference
Macros
#define Rvector dvector
#define Ivector ivector
#define Rmatrix dmatrix
#define Imatrix imatrix
#define free_Rvector free_dvector
#define free_Ivector free_ivector
#define free_Rmatrix free_dmatrix
#define free_Imatrix free_imatrix
#define TRUE 1
#define FALSE 0
Typedefs
typedef double Real
Functions
int MemoryUsage ()
void nrerror (const char error_text[])
float * vector (int, int)
int * ivector (int, int)
unsigned char * cvector (int, int)
unsigned long * lvector (int, int)
double * dvector (int, int)
float ** matrix (int, int, int, int)
double ** dmatrix (int, int, int, int)
int ** imatrix (int, int, int, int)
void free_vector (float *, int, int)
void free_ivector (int *, int, int)
void free_cvector (unsigned char *, int, int)
void free_lvector (unsigned long *, int, int)
void free_dvector (double *, int, int)
void free_matrix (float **, int, int, int, int)
void free_dmatrix (double **, int, int, int, int)
void free_imatrix (int **, int, int, int, int)
void bigerror (const char error_text[])
void smallerror (const char error_text[])
int FileExists (char *filename)
Real Minimum (Real *vector, int first, int last)
int Minimi (Real *vector, int first, int last)
Real Maximum (Real *vector, int first, int last)
int Maximi (Real *vector, int first, int last)
void AddExtension (const char *fname1, char *fname2, const char *newext)
int StringToStrings (const char *buf, char argv[10][10], int argc, char separator)
int StringToReal (const char *buf, Real *dest, int maxcnt, char separator)
int StringToInteger (const char *buf, int *dest, int maxcnt, char separator)
int next_int (char **start)
Real next_real (char **start)
void SortIndex (int n, double *arr, int *indx)
Macro Definition Documentation
#define FALSE 0
Definition at line 20 of file egutils.h.
View newest version in sPHENIX GitHub at line 20 of file egutils.h
#define free_Imatrix free_imatrix
Definition at line 18 of file egutils.h.
View newest version in sPHENIX GitHub at line 18 of file egutils.h
Referenced by CloneMeshes(), CreateAllBoundaries(), CreateBoundaryLayer(), DestroyKnots(), ElementsToBoundaryConditions(), ElementsToTriangles(), FindEdges(), IncreaseElementOrder(), LoadFidapInput(), LoadGidInput(), MirrorMeshes(), ReorderAutomatic(), and UniteMeshes().
#define free_Ivector free_ivector
Definition at line 16 of file egutils.h.
View newest version in sPHENIX GitHub at line 16 of file egutils.h
Referenced by CloneMeshes(), CreateBoundaryLayer(), CreateInverseTopology(), CreateKnotsExtruded(), CylindricalCoordinateTransformation(), DestroyBoundary(), DestroyDualGraph(), DestroyKnots(), ElementsToBoundaryConditions(), ElementsToTriangles(), FindBoundaryBoundary(), FindBulkBoundary(), FindEdges(), FindPointParents(), LoadAbaqusInput(), LoadAnsysInput(), LoadGidInput(), LoadGmshInput1(), LoadGmshInput2(), LoadUniversalMesh(), MergeElements(), MeshTypeStatistics(), MirrorMeshes(), RemoveUnusedNodes(), RenumberBoundaryTypes(), RenumberMaterialTypes(), ReorderAutomatic(), ReorderElements(), SetDiscontinuousBoundary(), SideAndBulkBoundaries(), and UniteMeshes().
#define free_Rmatrix free_dmatrix
Definition at line 17 of file egutils.h.
View newest version in sPHENIX GitHub at line 17 of file egutils.h
#define free_Rvector free_dvector
Definition at line 15 of file egutils.h.
View newest version in sPHENIX GitHub at line 15 of file egutils.h
Referenced by CloneMeshes(), CreateBoundaryLayer(), CreateKnotsExtruded(), CreateNewNodes(), DestroyKnots(), FindBoundaryBoundary(), FindBulkBoundary(), IncreaseElementOrder(), MergeElements(), MirrorMeshes(), ReduceElementOrder(), ReorderAutomatic(), ReorderElements(), and UniteMeshes().
#define Imatrix imatrix
Definition at line 14 of file egutils.h.
View newest version in sPHENIX GitHub at line 14 of file egutils.h
Referenced by AllocateKnots(), CloneMeshes(), CreateAllBoundaries(), CreateBoundaryLayer(), CreateBoundaryLayerDivide(), ElementsToBoundaryConditions(), ElementsToTriangles(), FindEdges(), IncreaseElementOrder(), LoadFidapInput(), LoadFieldviewInput(), LoadGidInput(), MirrorMeshes(), ReorderAutomatic(), ReorderElements(), and UniteMeshes().
#define Ivector ivector
Definition at line 12 of file egutils.h.
View newest version in sPHENIX GitHub at line 12 of file egutils.h
Referenced by AllocateBoundary(), AllocateKnots(), CloneMeshes(), CreateAllBoundaries(), CreateBoundary(), CreateBoundaryLayer(), CreateBoundaryLayerDivide(), CreateDualGraph(), CreateInverseTopology(), CreateKnotsExtruded(), CreateNewNodes(), CylindricalCoordinateTransformation(), ElementsToBoundaryConditions(), ElementsToTriangles(), FindBoundaryBoundary(), FindBulkBoundary(), FindEdges(), FindPeriodicBoundary(), FindPeriodicNodes(), FindPointParents(), LoadAbaqusInput(), LoadAnsysInput(), LoadFieldviewInput(), LoadGidInput(), LoadGmshInput1(), LoadGmshInput2(), LoadTriangleInput(), LoadUniversalMesh(), MergeElements(), MeshTypeStatistics(), MirrorMeshes(), ReduceElementOrder(), RemoveUnusedNodes(), RenumberBoundaryTypes(), RenumberMaterialTypes(), ReorderAutomatic(), ReorderElements(), SeparateMainaxisBoundaries(), SetConnectedBoundary(), SetDiscontinuousBoundary(), SideAndBulkBoundaries(), and UniteMeshes().
#define Rmatrix dmatrix
Definition at line 13 of file egutils.h.
View newest version in sPHENIX GitHub at line 13 of file egutils.h
#define Rvector dvector
Definition at line 11 of file egutils.h.
View newest version in sPHENIX GitHub at line 11 of file egutils.h
Referenced by AllocateKnots(), CloneMeshes(), CreateBoundaryLayer(), CreateBoundaryLayerDivide(), CreateKnotsExtruded(), CreateNewNodes(), CreateVariable(), ExampleGrid2D(), FindBoundaryBoundary(), FindBulkBoundary(), FindEdges(), FindPeriodicNodes(), IncreaseElementOrder(), LoadElmergrid(), LoadFieldviewInput(), MergeElements(), MirrorMeshes(), ReduceElementOrder(), ReorderAutomatic(), ReorderElements(), and UniteMeshes().
#define TRUE 1
Definition at line 19 of file egutils.h.
View newest version in sPHENIX GitHub at line 19 of file egutils.h
Typedef Documentation
typedef double Real
Definition at line 10 of file egutils.h.
View newest version in sPHENIX GitHub at line 10 of file egutils.h
Function Documentation
void AddExtension (const char * fname1, char * fname2, const char * newext)
Definition at line 388 of file egutils.cpp.
View newest version in sPHENIX GitHub at line 388 of file egutils.cpp
Referenced by LoadAbaqusInput(), LoadCGsimMesh(), LoadCommands(), LoadComsolMesh(), LoadElmergrid(), LoadFidapInput(), LoadFieldviewInput(), LoadGidInput(), LoadNastranInput(), LoadUniversalMesh(), and SaveElmergrid().
void bigerror (const char error_text[])
Definition at line 298 of file egutils.cpp.
View newest version in sPHENIX GitHub at line 298 of file egutils.cpp
References exit().
Referenced by IncreaseElementOrder(), and LoadUniversalMesh().
unsigned char* cvector (int , int)
Definition at line 97 of file egutils.cpp.
View newest version in sPHENIX GitHub at line 97 of file egutils.cpp
References nrerror(), and v.
double** dmatrix (int , int , int , int)
Definition at line 166 of file egutils.cpp.
View newest version in sPHENIX GitHub at line 166 of file egutils.cpp
References Acts::UnitConstants::m, MemoryUsage(), and nrerror().
double* dvector (int , int)
Definition at line 120 of file egutils.cpp.
View newest version in sPHENIX GitHub at line 120 of file egutils.cpp
References MemoryUsage(), nrerror(), and v.
int FileExists (char * filename)
Definition at line 317 of file egutils.cpp.
View newest version in sPHENIX GitHub at line 317 of file egutils.cpp
References FALSE, in, and TRUE.
void free_cvector (unsigned char * , int , int)
Definition at line 247 of file egutils.cpp.
View newest version in sPHENIX GitHub at line 247 of file egutils.cpp
References FREE_ARG.
void free_dmatrix (double ** , int , int , int , int)
Definition at line 273 of file egutils.cpp.
View newest version in sPHENIX GitHub at line 273 of file egutils.cpp
References FREE_ARG.
void free_dvector (double * , int , int)
Definition at line 258 of file egutils.cpp.
View newest version in sPHENIX GitHub at line 258 of file egutils.cpp
References FREE_ARG.
void free_imatrix (int ** , int , int , int , int)
Definition at line 285 of file egutils.cpp.
View newest version in sPHENIX GitHub at line 285 of file egutils.cpp
References FREE_ARG.
void free_ivector (int * , int , int)
Definition at line 238 of file egutils.cpp.
View newest version in sPHENIX GitHub at line 238 of file egutils.cpp
References FREE_ARG.
Referenced by LoadAbaqusInput(), and SortIndex().
void free_lvector (unsigned long * , int , int)
Definition at line 252 of file egutils.cpp.
View newest version in sPHENIX GitHub at line 252 of file egutils.cpp
References FREE_ARG.
void free_matrix (float ** , int , int , int , int)
Definition at line 267 of file egutils.cpp.
View newest version in sPHENIX GitHub at line 267 of file egutils.cpp
References FREE_ARG.
void free_vector (float * , int , int)
Definition at line 233 of file egutils.cpp.
View newest version in sPHENIX GitHub at line 233 of file egutils.cpp
References FREE_ARG.
int** imatrix (int , int , int , int)
Definition at line 199 of file egutils.cpp.
View newest version in sPHENIX GitHub at line 199 of file egutils.cpp
References Acts::UnitConstants::m, MemoryUsage(), and nrerror().
int* ivector (int , int)
Definition at line 78 of file egutils.cpp.
View newest version in sPHENIX GitHub at line 78 of file egutils.cpp
References MemoryUsage(), nrerror(), and v.
Referenced by LoadAbaqusInput(), LoadFidapInput(), and SortIndex().
unsigned long* lvector (int , int)
Definition at line 108 of file egutils.cpp.
View newest version in sPHENIX GitHub at line 108 of file egutils.cpp
References nrerror(), and v.
float** matrix (int , int , int , int)
Definition at line 141 of file egutils.cpp.
View newest version in sPHENIX GitHub at line 141 of file egutils.cpp
References Acts::UnitConstants::m, and nrerror().
Referenced by Acts::Test::BOOST_AUTO_TEST_CASE(), FairGeaneUtil::FromMARSToSDCoord(), FairGeaneUtil::FromSDToMARSCoord(), Acts::CylinderSurface::normal(), ActsTransformations::printMatrix(), Acts::ConeSurface::rotSymmetryAxis(), genfit::TMatrixDSymToCovariance3D(), Acts::Surface::toStream(), Acts::toString(), and CylinderGeomMicromegas::transformation_matrix().
int Maximi (Real * vector, int first, int last)
Definition at line 373 of file egutils.cpp.
View newest version in sPHENIX GitHub at line 373 of file egutils.cpp
References max.
Real Maximum (Real * vector, int first, int last)
Definition at line 359 of file egutils.cpp.
View newest version in sPHENIX GitHub at line 359 of file egutils.cpp
References max.
int MemoryUsage ()
Referenced by dmatrix(), dvector(), imatrix(), and ivector().
int Minimi (Real * vector, int first, int last)
Definition at line 344 of file egutils.cpp.
View newest version in sPHENIX GitHub at line 344 of file egutils.cpp
References min.
Real Minimum (Real * vector, int first, int last)
Definition at line 330 of file egutils.cpp.
View newest version in sPHENIX GitHub at line 330 of file egutils.cpp
References min.
int next_int (char ** start)
Definition at line 496 of file egutils.cpp.
View newest version in sPHENIX GitHub at line 496 of file egutils.cpp
Referenced by LoadAnsysInput(), LoadCGsimMesh(), LoadCommands(), LoadComsolMesh(), LoadElmergrid(), LoadFidapInput(), LoadFieldviewInput(), LoadGidInput(), LoadGmshInput1(), LoadGmshInput2(), LoadMeditInput(), LoadNastranInput(), LoadTriangleInput(), and LoadUniversalMesh().
Real next_real (char ** start)
Definition at line 507 of file egutils.cpp.
View newest version in sPHENIX GitHub at line 507 of file egutils.cpp
Referenced by LoadAnsysInput(), LoadCGsimMesh(), LoadCommands(), LoadComsolMesh(), LoadElmergrid(), LoadGidInput(), LoadGmshInput1(), LoadGmshInput2(), LoadMeditInput(), LoadNastranInput(), LoadTriangleInput(), and LoadUniversalMesh().
void nrerror (const char error_text[])
Definition at line 55 of file egutils.cpp.
View newest version in sPHENIX GitHub at line 55 of file egutils.cpp
References exit().
Referenced by cvector(), dmatrix(), dvector(), imatrix(), ivector(), lvector(), matrix(), and vector().
void smallerror (const char error_text[])
Definition at line 307 of file egutils.cpp.
View newest version in sPHENIX GitHub at line 307 of file egutils.cpp
References exit().
Referenced by CreateInverseTopology().
void SortIndex (int n, double * arr, int * indx)
Definition at line 525 of file egutils.cpp.
View newest version in sPHENIX GitHub at line 525 of file egutils.cpp
References free_ivector(), ir(), ivector(), k, M, n, NSTACK, printf(), and SWAPI.
Referenced by FindEdges(), ReorderAutomatic(), and ReorderElements().
int StringToInteger (const char * buf, int * dest, int maxcnt, char separator)
Definition at line 479 of file egutils.cpp.
View newest version in sPHENIX GitHub at line 479 of file egutils.cpp
Referenced by LoadAbaqusInput().
int StringToReal (const char * buf, Real * dest, int maxcnt, char separator)
Definition at line 455 of file egutils.cpp.
View newest version in sPHENIX GitHub at line 455 of file egutils.cpp
Referenced by LoadAbaqusInput().
int StringToStrings (const char * buf, char argv[10][10], int argc, char separator)
Definition at line 410 of file egutils.cpp.
View newest version in sPHENIX GitHub at line 410 of file egutils.cpp
Referenced by eg_transfermesh().
float* vector (int , int)
Definition at line 66 of file egutils.cpp.
View newest version in sPHENIX GitHub at line 66 of file egutils.cpp
References nrerror(), and v.
Referenced by Acts::BinnedSPGroup< external_spacepoint_t >::BinnedSPGroup(), Acts::Test::BOOST_AUTO_TEST_CASE(), Acts::Test::BOOST_DATA_TEST_CASE(), KFParticle_eventReconstruction::buildChain(), AnyVector::create(), Acts::Cuda::SeedFinder< external_spacepoint_t >::createSeedsForGroup(), Acts::Sycl::Seedfinder< external_spacepoint_t >::createSeedsForGroup(), Acts::Seedfinder< external_spacepoint_t, Acts::Cuda >::createSeedsForGroup(), Acts::Seedfinder< external_spacepoint_t, platform_t >::createSeedsForGroup(), TestHostCuts::cutPerMiddleSP(), readLuminosity::e_read(), Acts::SeedFilter< external_spacepoint_t >::filterSeeds_2SpFixed(), HelixHough::HelixHough(), HelixHough::initHelixHough(), eASTMagneticFieldMap::Load(), Acts::Test::benchmark_tools_internal::microBenchmarkImpl(), Acts::Legacy::AtlasSeedfinder< SpacePoint >::newOneSeedWithCurvaturesComparison(), Smear::FormulaString::Parse(), PHField3DCylindrical::PHField3DCylindrical(), PHG4InttSubsystem::PHG4InttSubsystem(), RawClusterBuilderTopo::process_event(), ParticleFlowReco::process_event(), Fun4AllServer::process_event(), sPHENIXSeedFinder::sPHENIXSeedFinder(), sPHENIXTracker::sPHENIXTracker(), and sPHENIXTrackerTpc::sPHENIXTrackerTpc().