EIC Software: CbmDetectorList Class Reference
CbmDetectorList Class Reference
Provides some utility functions for DetectorId.
#include <EicRoot/blob/master/cbmdata/CbmDetectorList.h>
Public Member Functions
CbmDetectorList ()
virtual ~CbmDetectorList ()
ClassDef (CbmDetectorList, 1)
Static Public Member Functions
static void GetSystemName (DetectorId det, TString &name)
static void GetSystemName (Int_t det, TString &name)
static void GetSystemNameCaps (DetectorId det, TString &name)
static void GetSystemNameCaps (Int_t det, TString &name)
Detailed Description
Provides some utility functions for DetectorId.
Author
V.Friese V.Fri.nosp@m.ese@.nosp@m.Gsi.D.nosp@m.e
Date
29.04.2010
Definition at line 48 of file CbmDetectorList.h.
View newest version in sPHENIX GitHub at line 48 of file CbmDetectorList.h
Constructor & Destructor Documentation
CbmDetectorList::CbmDetectorList ()
Constructor
Definition at line 12 of file CbmDetectorList.cxx.
View newest version in sPHENIX GitHub at line 12 of file CbmDetectorList.cxx
virtual CbmDetectorList::~CbmDetectorList () inline virtual
Destructor
Definition at line 58 of file CbmDetectorList.h.
View newest version in sPHENIX GitHub at line 58 of file CbmDetectorList.h
Member Function Documentation
CbmDetectorList::ClassDef (CbmDetectorList , 1)
void CbmDetectorList::GetSystemName (DetectorId det, TString & name) static
Get system name
Parameters
det System identifier (type DetectorId)
name (return) System name (lower case)
Definition at line 19 of file CbmDetectorList.cxx.
View newest version in sPHENIX GitHub at line 19 of file CbmDetectorList.cxx
References kECAL, kMUCH, kMVD, kPSD, kREF, kRICH, kSTS, kTOF, and kTRD.
Referenced by GetSystemName(), and CbmMCEpoch::Print().
void CbmDetectorList::GetSystemName (Int_t det, TString & name) static
Definition at line 42 of file CbmDetectorList.cxx.
View newest version in sPHENIX GitHub at line 42 of file CbmDetectorList.cxx
References GetSystemName(), and kNOFDETS.
void CbmDetectorList::GetSystemNameCaps (DetectorId det, TString & name) static
Get system name in capitals
Parameters
det System identifier (type DetectorId)
name (return) System name (lower case)
Definition at line 53 of file CbmDetectorList.cxx.
View newest version in sPHENIX GitHub at line 53 of file CbmDetectorList.cxx
References kECAL, kMUCH, kMVD, kPSD, kREF, kRICH, kSTS, kTOF, and kTRD.
Referenced by GetSystemNameCaps().
void CbmDetectorList::GetSystemNameCaps (Int_t det, TString & name) static
Definition at line 76 of file CbmDetectorList.cxx.
View newest version in sPHENIX GitHub at line 76 of file CbmDetectorList.cxx
References GetSystemNameCaps(), and kNOFDETS.
The documentation for this class was generated from the following files:
EicRoot/blob/master/cbmdata/CbmDetectorList.h
EicRoot/blob/master/cbmdata/CbmDetectorList.cxx