EIC Software: FairDbOutRowStream Class Reference
FairDbOutRowStream Class Reference
#include <EicRoot/blob/master/dbase/dbInterface/FairDbOutRowStream.h>
Public Member Functions
FairDbOutRowStream (const FairDbTableMetaData *metaData)
virtual ~FairDbOutRowStream ()
Bool_t HasGoodData () const
const string & GetCSV () const
Bool_t IsComplete () const
FairDbOutRowStream & operator<< (Bool_t src)
FairDbOutRowStream & operator<< (Char_t src)
FairDbOutRowStream & operator<< (const Char_t *src)
FairDbOutRowStream & operator<< (Short_t src)
FairDbOutRowStream & operator<< (UShort_t src)
FairDbOutRowStream & operator<< (Int_t src)
FairDbOutRowStream & operator<< (UInt_t src)
FairDbOutRowStream & operator<< (Float_t src)
FairDbOutRowStream & operator<< (Double_t src)
FairDbOutRowStream & operator<< (const string &src)
FairDbOutRowStream & operator<< (const ValTimeStamp &src)
void Clear ()
void Store (const string &str)
Bool_t StoreDefaultIfInvalid (FairDb::DataTypes type)
Public Member Functions inherited from FairDbRowStream
FairDbRowStream (const FairDbTableMetaData *metaData)
virtual ~FairDbRowStream ()
virtual const FairDbFieldType & ColFieldType (UInt_t col) const
virtual string ColName (UInt_t col) const
virtual const FairDbFieldType & CurColFieldType () const
virtual string CurColName () const
virtual UInt_t CurColNum () const
Bool_t HasRowCounter () const
virtual UInt_t NumCols () const
virtual string TableName () const
virtual string TableNameTc () const
virtual const FairDbTableMetaData * MetaData () const
virtual void DecrementCurCol ()
virtual void IncrementCurCol ()
Private Attributes
Bool_t fBadData
string fCSV
Additional Inherited Members
Protected Member Functions inherited from FairDbRowStream
virtual void ClearCurCol ()
Detailed Description
Definition at line 13 of file FairDbOutRowStream.h.
View newest version in sPHENIX GitHub at line 13 of file FairDbOutRowStream.h
Constructor & Destructor Documentation
FairDbOutRowStream::FairDbOutRowStream (const FairDbTableMetaData * metaData)
FairDbOutRowStream::~FairDbOutRowStream () virtual
Definition at line 47 of file FairDbOutRowStream.cxx.
View newest version in sPHENIX GitHub at line 47 of file FairDbOutRowStream.cxx
Member Function Documentation
void FairDbOutRowStream::Clear () inline
Definition at line 39 of file FairDbOutRowStream.h.
View newest version in sPHENIX GitHub at line 39 of file FairDbOutRowStream.h
References FairDbRowStream::ClearCurCol(), fBadData, and fCSV.
const string& FairDbOutRowStream::GetCSV () const inline
Definition at line 24 of file FairDbOutRowStream.h.
View newest version in sPHENIX GitHub at line 24 of file FairDbOutRowStream.h
References fCSV.
Referenced by FairDbSqlValPacket::AddRow(), and FairDbSqlValPacket::Recreate().
Bool_t FairDbOutRowStream::HasGoodData () const inline
Definition at line 23 of file FairDbOutRowStream.h.
View newest version in sPHENIX GitHub at line 23 of file FairDbOutRowStream.h
References fBadData, and IsComplete().
Referenced by FairDbSqlValPacket::AddRow().
Bool_t FairDbOutRowStream::IsComplete () const inline
Definition at line 25 of file FairDbOutRowStream.h.
View newest version in sPHENIX GitHub at line 25 of file FairDbOutRowStream.h
References FairDbRowStream::CurColNum(), and FairDbRowStream::NumCols().
Referenced by FairDbSqlValPacket::AddRow(), and HasGoodData().
FairDbOutRowStream & FairDbOutRowStream::operator<< (Bool_t src)
Definition at line 54 of file FairDbOutRowStream.cxx.
View newest version in sPHENIX GitHub at line 54 of file FairDbOutRowStream.cxx
References FairDb::kBool, and OUT.
FairDbOutRowStream & FairDbOutRowStream::operator<< (Char_t src)
Definition at line 60 of file FairDbOutRowStream.cxx.
View newest version in sPHENIX GitHub at line 60 of file FairDbOutRowStream.cxx
References FairDb::kChar, and OUT.
FairDbOutRowStream & FairDbOutRowStream::operator<< (const Char_t * src)
Definition at line 66 of file FairDbOutRowStream.cxx.
View newest version in sPHENIX GitHub at line 66 of file FairDbOutRowStream.cxx
References FairDb::kString, and OUT.
FairDbOutRowStream & FairDbOutRowStream::operator<< (Short_t src)
Definition at line 72 of file FairDbOutRowStream.cxx.
View newest version in sPHENIX GitHub at line 72 of file FairDbOutRowStream.cxx
References FairDb::kShort, and OUT.
FairDbOutRowStream & FairDbOutRowStream::operator<< (UShort_t src)
Definition at line 78 of file FairDbOutRowStream.cxx.
View newest version in sPHENIX GitHub at line 78 of file FairDbOutRowStream.cxx
References FairDb::kUShort, and OUT2.
FairDbOutRowStream & FairDbOutRowStream::operator<< (Int_t src)
Definition at line 84 of file FairDbOutRowStream.cxx.
View newest version in sPHENIX GitHub at line 84 of file FairDbOutRowStream.cxx
References FairDb::kInt, and OUT.
FairDbOutRowStream & FairDbOutRowStream::operator<< (UInt_t src)
Definition at line 90 of file FairDbOutRowStream.cxx.
View newest version in sPHENIX GitHub at line 90 of file FairDbOutRowStream.cxx
References FairDb::kUInt, and OUT2.
FairDbOutRowStream & FairDbOutRowStream::operator<< (Float_t src)
Definition at line 96 of file FairDbOutRowStream.cxx.
View newest version in sPHENIX GitHub at line 96 of file FairDbOutRowStream.cxx
References FairDb::kFloat, and OUT.
FairDbOutRowStream & FairDbOutRowStream::operator<< (Double_t src)
Definition at line 102 of file FairDbOutRowStream.cxx.
View newest version in sPHENIX GitHub at line 102 of file FairDbOutRowStream.cxx
References FairDb::kDouble, and OUT.
FairDbOutRowStream & FairDbOutRowStream::operator<< (const string & src)
Definition at line 108 of file FairDbOutRowStream.cxx.
View newest version in sPHENIX GitHub at line 108 of file FairDbOutRowStream.cxx
References FairDb::kString, and OUT.
FairDbOutRowStream & FairDbOutRowStream::operator<< (const ValTimeStamp & src)
Definition at line 114 of file FairDbOutRowStream.cxx.
View newest version in sPHENIX GitHub at line 114 of file FairDbOutRowStream.cxx
References FairDb::kDate, FairDb::MakeDateTimeString(), Store(), and StoreDefaultIfInvalid().
void FairDbOutRowStream::Store (const string & str)
Definition at line 144 of file FairDbOutRowStream.cxx.
View newest version in sPHENIX GitHub at line 144 of file FairDbOutRowStream.cxx
References FairDbRowStream::CurColFieldType(), FairDbRowStream::CurColNum(), fCSV, FairDbFieldType::GetConcept(), FairDbRowStream::IncrementCurCol(), FairDb::kChar, FairDb::kDate, FairDb::kString, and FairUtilString::MakePrintable().
Referenced by operator<<(), FairDbConfigSet::Store(), and StoreDefaultIfInvalid().
Bool_t FairDbOutRowStream::StoreDefaultIfInvalid (FairDb::DataTypes type)
Definition at line 123 of file FairDbOutRowStream.cxx.
View newest version in sPHENIX GitHub at line 123 of file FairDbOutRowStream.cxx
References FairDbFieldType::AsString(), FairDbRowStream::CurColFieldType(), FairDbRowStream::CurColName(), FairDbRowStream::CurColNum(), fBadData, FairDbFieldType::IsCompatible(), Store(), FairDbRowStream::TableNameTc(), and FairDbFieldType::UndefinedValue().
Referenced by operator<<().
Member Data Documentation
Bool_t FairDbOutRowStream::fBadData private
Definition at line 45 of file FairDbOutRowStream.h.
View newest version in sPHENIX GitHub at line 45 of file FairDbOutRowStream.h
Referenced by Clear(), HasGoodData(), and StoreDefaultIfInvalid().
string FairDbOutRowStream::fCSV private
Definition at line 46 of file FairDbOutRowStream.h.
View newest version in sPHENIX GitHub at line 46 of file FairDbOutRowStream.h
Referenced by Clear(), GetCSV(), and Store().
The documentation for this class was generated from the following files:
EicRoot/blob/master/dbase/dbInterface/FairDbOutRowStream.h
EicRoot/blob/master/dbase/dbInterface/FairDbOutRowStream.cxx