EIC Software: PEPSI/blob/master/pepsi/gamma.F File Reference
gamma.F File Reference
Functions/Subroutines
function gamma (XX)
Function/Subroutine Documentation
function gamma (real XX)
Definition at line 6 of file gamma.F.
View newest version in sPHENIX GitHub at line 6 of file gamma.F
References Acts::Logger::log(), x, and y.
Referenced by lorentzVector::Boost(), Acts::Test::BOOST_AUTO_TEST_CASE(), Acts::Test::BOOST_DATA_TEST_CASE(), erhic::LeptonKinematicsComputer::Calculate(), erhic::DoubleAngleComputer::ComputeQSquared(), erhic::DoubleAngleComputer::ComputeY(), VstGeoParData::ConstructGeometry(), genfit::MaterialEffects::dEdx(), Gammaavectormeson::e_produceEvent(), genfit::MaterialEffects::effects(), ActsExamples::HelloRandomAlgorithm::execute(), PHG4GDMLWriteStructure::ExportEnergyCuts(), PHG4HcalDetector::GetLength(), genfit::MaterialEffects::getMomGammaBeta(), Acts::detail::IntersectionHelper2D::intersectEllipse(), lmsimp(), twoPhotonLuminosity::Nphoton(), parton(), beamBeamSystem::probabilityOfHadronBreakup(), PHG4ParticleGeneratorD0::process_event(), PHSartre::process_event(), pygdir(), pyveto(), Acts::detail::RealQuadraticEquation::RealQuadraticEquation(), riwibd(), beam::setBeamLorentzGamma(), eventChannel::transform(), and Acts::TrapezoidVolumeBounds::TrapezoidVolumeBounds().