EIC Software: FairDbValRecSet Class Reference
FairDbValRecSet Class Reference
#include <EicRoot/blob/master/dbase/dbInterface/FairDbValRecSet.h>
Public Member Functions
FairDbValRecSet (const string &tableName, UInt_t dbNo, UInt_t seqNo=0)
virtual ~FairDbValRecSet ()
UInt_t GetDbNo () const
UInt_t GetNumRows () const
const string GetTableName () const
const FairDbValidityRec * GetTableRow (UInt_t rowNum) const
const FairDbValidityRec * GetTableRowBySeqNo (UInt_t seqNo) const
Private Member Functions
FairDbValRecSet (const FairDbValRecSet &)
FairDbValRecSet operator= (const FairDbValRecSet &)
Private Attributes
UInt_t fDbNo
FairDbResult * fResult
Result holding table of FairDbValidityRec.
map< UInt_t, const
FairDbValidityRec * > fSeqNoToRec
Detailed Description
Definition at line 11 of file FairDbValRecSet.h.
View newest version in sPHENIX GitHub at line 11 of file FairDbValRecSet.h
Constructor & Destructor Documentation
FairDbValRecSet::FairDbValRecSet (const string & tableName, UInt_t dbNo, UInt_t seqNo = 0)
FairDbValRecSet::~FairDbValRecSet () virtual
Definition at line 34 of file FairDbValRecSet.cxx.
View newest version in sPHENIX GitHub at line 34 of file FairDbValRecSet.cxx
References fResult.
FairDbValRecSet::FairDbValRecSet (const FairDbValRecSet &) private
Member Function Documentation
UInt_t FairDbValRecSet::GetDbNo () const inline
Definition at line 21 of file FairDbValRecSet.h.
View newest version in sPHENIX GitHub at line 21 of file FairDbValRecSet.h
References fDbNo.
UInt_t FairDbValRecSet::GetNumRows () const
Definition at line 42 of file FairDbValRecSet.cxx.
View newest version in sPHENIX GitHub at line 42 of file FairDbValRecSet.cxx
References fResult, and FairDbResult::GetNumRows().
Referenced by GetTableRowBySeqNo().
const string FairDbValRecSet::GetTableName () const
Definition at line 49 of file FairDbValRecSet.cxx.
View newest version in sPHENIX GitHub at line 49 of file FairDbValRecSet.cxx
References fResult, and FairDbResult::TableName().
const FairDbValidityRec * FairDbValRecSet::GetTableRow (UInt_t rowNum) const
Definition at line 56 of file FairDbValRecSet.cxx.
View newest version in sPHENIX GitHub at line 56 of file FairDbValRecSet.cxx
References fResult, and FairDbResult::GetTableRow().
Referenced by GetTableRowBySeqNo().
const FairDbValidityRec * FairDbValRecSet::GetTableRowBySeqNo (UInt_t seqNo) const
Definition at line 65 of file FairDbValRecSet.cxx.
View newest version in sPHENIX GitHub at line 65 of file FairDbValRecSet.cxx
References fSeqNoToRec, GetNumRows(), FairDbValidityRec::GetSeqNo(), and GetTableRow().
FairDbValRecSet FairDbValRecSet::operator= (const FairDbValRecSet &) private
Member Data Documentation
UInt_t FairDbValRecSet::fDbNo private
Definition at line 34 of file FairDbValRecSet.h.
View newest version in sPHENIX GitHub at line 34 of file FairDbValRecSet.h
Referenced by GetDbNo().
FairDbResult* FairDbValRecSet::fResult private
Result holding table of FairDbValidityRec.
Definition at line 37 of file FairDbValRecSet.h.
View newest version in sPHENIX GitHub at line 37 of file FairDbValRecSet.h
Referenced by GetNumRows(), GetTableName(), GetTableRow(), and ~FairDbValRecSet().
map<UInt_t,const FairDbValidityRec*> FairDbValRecSet::fSeqNoToRec mutable private
Lookup SeqNo -> FairDbValidityRec lazy creation - see GetTableRowBySeqNo
Definition at line 41 of file FairDbValRecSet.h.
View newest version in sPHENIX GitHub at line 41 of file FairDbValRecSet.h
Referenced by GetTableRowBySeqNo().
The documentation for this class was generated from the following files:
EicRoot/blob/master/dbase/dbInterface/FairDbValRecSet.h
EicRoot/blob/master/dbase/dbInterface/FairDbValRecSet.cxx