EIC Software: surface_t Class Reference
surface_t Class Reference
#include <EicRoot/blob/master/eic/cad/elmer/src/meshtype.h>
Public Member Functions
surface_t ()
~surface_t ()
void setEdges (int)
int getEdges () const
void setEdgeIndex (int, int)
int getEdgeIndex (int) const
void newEdgeIndexes (int)
void deleteEdgeIndexes ()
void setElements (int)
int getElements () const
void setElementIndex (int, int)
int getElementIndex (int) const
void newElementIndexes (int)
void deleteElementIndexes ()
void setNormalVec (double *)
double * getNormalVec ()
double getNormal (int) const
void setNormal (int, double)
void setVertexNormalVec (int, double *)
void addVertexNormalVec (int, double *)
void subVertexNormalVec (int, double *)
double * getVertexNormalVec (int)
Public Member Functions inherited from element_t
element_t ()
~element_t ()
void setNature (int)
int getNature () const
void setCode (int)
int getCode () const
void setNodes (int)
int getNodes () const
void setIndex (int)
int getIndex () const
void setSelected (int)
int getSelected () const
int getNodeIndex (int) const
void setNodeIndex (int, int)
int * getNodeIndexes () const
void newNodeIndexes (int)
void deleteNodeIndexes ()
Private Attributes
int edges
int * edge
int elements
int * element
double normal [3]
double vertex_normals [4][3]
Detailed Description
Definition at line 157 of file meshtype.h.
View newest version in sPHENIX GitHub at line 157 of file meshtype.h
Constructor & Destructor Documentation
surface_t::surface_t ()
Definition at line 305 of file meshtype.cpp.
View newest version in sPHENIX GitHub at line 305 of file meshtype.cpp
surface_t::~surface_t ()
Definition at line 309 of file meshtype.cpp.
View newest version in sPHENIX GitHub at line 309 of file meshtype.cpp
Member Function Documentation
void surface_t::addVertexNormalVec (int n, double * d)
Definition at line 402 of file meshtype.cpp.
View newest version in sPHENIX GitHub at line 402 of file meshtype.cpp
References n.
void surface_t::deleteEdgeIndexes ()
Definition at line 338 of file meshtype.cpp.
View newest version in sPHENIX GitHub at line 338 of file meshtype.cpp
void surface_t::deleteElementIndexes ()
Definition at line 368 of file meshtype.cpp.
View newest version in sPHENIX GitHub at line 368 of file meshtype.cpp
int surface_t::getEdgeIndex (int n) const
Definition at line 328 of file meshtype.cpp.
View newest version in sPHENIX GitHub at line 328 of file meshtype.cpp
References n.
int surface_t::getEdges () const
Definition at line 318 of file meshtype.cpp.
View newest version in sPHENIX GitHub at line 318 of file meshtype.cpp
Referenced by ConvertEgTypeToMeshType(), and mesh_t::load().
int surface_t::getElementIndex (int n) const
Definition at line 358 of file meshtype.cpp.
View newest version in sPHENIX GitHub at line 358 of file meshtype.cpp
References n.
Referenced by mesh_t::save().
int surface_t::getElements () const
Definition at line 348 of file meshtype.cpp.
View newest version in sPHENIX GitHub at line 348 of file meshtype.cpp
Referenced by ConvertEgTypeToMeshType(), and mesh_t::load().
double surface_t::getNormal (int n) const
Definition at line 385 of file meshtype.cpp.
View newest version in sPHENIX GitHub at line 385 of file meshtype.cpp
References n.
double * surface_t::getNormalVec ()
Definition at line 373 of file meshtype.cpp.
View newest version in sPHENIX GitHub at line 373 of file meshtype.cpp
double * surface_t::getVertexNormalVec (int n)
Definition at line 416 of file meshtype.cpp.
View newest version in sPHENIX GitHub at line 416 of file meshtype.cpp
References n.
void surface_t::newEdgeIndexes (int n)
Definition at line 333 of file meshtype.cpp.
View newest version in sPHENIX GitHub at line 333 of file meshtype.cpp
References n.
Referenced by ConvertEgTypeToMeshType(), and mesh_t::load().
void surface_t::newElementIndexes (int n)
Definition at line 363 of file meshtype.cpp.
View newest version in sPHENIX GitHub at line 363 of file meshtype.cpp
References n.
Referenced by ConvertEgTypeToMeshType(), and mesh_t::load().
void surface_t::setEdgeIndex (int m, int n)
Definition at line 323 of file meshtype.cpp.
View newest version in sPHENIX GitHub at line 323 of file meshtype.cpp
References Acts::UnitConstants::m, and n.
Referenced by ConvertEgTypeToMeshType(), and mesh_t::load().
void surface_t::setEdges (int n)
Definition at line 313 of file meshtype.cpp.
View newest version in sPHENIX GitHub at line 313 of file meshtype.cpp
References n.
Referenced by ConvertEgTypeToMeshType(), and mesh_t::load().
void surface_t::setElementIndex (int m, int n)
Definition at line 353 of file meshtype.cpp.
View newest version in sPHENIX GitHub at line 353 of file meshtype.cpp
References Acts::UnitConstants::m, and n.
Referenced by ConvertEgTypeToMeshType(), and mesh_t::load().
void surface_t::setElements (int n)
Definition at line 343 of file meshtype.cpp.
View newest version in sPHENIX GitHub at line 343 of file meshtype.cpp
References n.
Referenced by ConvertEgTypeToMeshType(), and mesh_t::load().
void surface_t::setNormal (int n, double d)
Definition at line 390 of file meshtype.cpp.
View newest version in sPHENIX GitHub at line 390 of file meshtype.cpp
References d, and n.
Referenced by ConvertEgTypeToMeshType().
void surface_t::setNormalVec (double * d)
Definition at line 378 of file meshtype.cpp.
View newest version in sPHENIX GitHub at line 378 of file meshtype.cpp
void surface_t::setVertexNormalVec (int n, double * d)
Definition at line 395 of file meshtype.cpp.
View newest version in sPHENIX GitHub at line 395 of file meshtype.cpp
References n.
void surface_t::subVertexNormalVec (int n, double * d)
Definition at line 409 of file meshtype.cpp.
View newest version in sPHENIX GitHub at line 409 of file meshtype.cpp
References n.
Member Data Documentation
int* surface_t::edge private
Definition at line 185 of file meshtype.h.
View newest version in sPHENIX GitHub at line 185 of file meshtype.h
int surface_t::edges private
Definition at line 184 of file meshtype.h.
View newest version in sPHENIX GitHub at line 184 of file meshtype.h
int* surface_t::element private
Definition at line 187 of file meshtype.h.
View newest version in sPHENIX GitHub at line 187 of file meshtype.h
int surface_t::elements private
Definition at line 186 of file meshtype.h.
View newest version in sPHENIX GitHub at line 186 of file meshtype.h
double surface_t::normal[3] private
Definition at line 188 of file meshtype.h.
View newest version in sPHENIX GitHub at line 188 of file meshtype.h
double surface_t::vertex_normals[4][3] private
Definition at line 189 of file meshtype.h.
View newest version in sPHENIX GitHub at line 189 of file meshtype.h
The documentation for this class was generated from the following files:
EicRoot/blob/master/eic/cad/elmer/src/meshtype.h
EicRoot/blob/master/eic/cad/elmer/src/meshtype.cpp