EIC Software: east/blob/main/Components/ECCE/Extract_ECCE_gdml.C File Reference
Extract_ECCE_gdml.C File Reference
#include <GlobalVariables.C>
#include <G4Setup_EICDetector.C>
#include <G4_Global.C>
#include <G4_Input.C>
#include <G4_Production.C>
#include <G4_User.C>
#include <TROOT.h>
#include <fun4all/Fun4AllDstOutputManager.h>
#include <fun4all/Fun4AllOutputManager.h>
#include <fun4all/Fun4AllServer.h>
#include <phool/recoConsts.h>
#include <RooUnblindPrecision.h>
Macros
#define EXTRACT_ECCE_GDML_C
Functions
int Extract_ECCE_gdml (string subsys="all", const string outbase="")
Macro Definition Documentation
#define EXTRACT_ECCE_GDML_C
Definition at line 2 of file Extract_ECCE_gdml.C.
View newest version in sPHENIX GitHub at line 2 of file Extract_ECCE_gdml.C
Function Documentation
int Extract_ECCE_gdml (string subsys = "all", const string outbase = "")
Definition at line 38 of file Extract_ECCE_gdml.C.
View newest version in sPHENIX GitHub at line 38 of file Extract_ECCE_gdml.C
References Enable::BARREL, Enable::BECAL, Enable::BECAL_CELL, Enable::BECAL_CLUSTER, BECAL_Clusters(), Enable::BECAL_EVAL, Enable::BECAL_TOWER, BECAL_Towers(), Enable::BLACKHOLE, c, Enable::CEMC_CELL, CEMC_Cells(), Enable::CEMC_CLUSTER, CEMC_Clusters(), Enable::CEMC_TOWER, CEMC_Towers(), Enable::CTTL, Enable::DIRC, G4TRACKING::DISPLACED_VERTEX, Enable::DRCALO, Enable::DRCALO_CELL, Enable::DRCALO_CLUSTER, DRCALO_Clusters(), Enable::DRCALO_EVAL, Enable::DRCALO_TOWER, DRCALO_Towers(), Enable::DSTOUT_COMPRESS, PHG4Reco::Dump_G4_GDML(), Enable::EEMC_CLUSTER, EEMC_Clusters(), Enable::EEMC_TOWER, EEMC_Towers(), Enable::EEMCH, Enable::EEMCH_CLUSTER, EEMCH_Clusters(), Enable::EEMCH_EVAL, Enable::EEMCH_TOWER, EEMCH_Towers(), Enable::EGEM, Enable::EHCAL, Enable::EHCAL_CELL, Enable::EHCAL_CLUSTER, EHCAL_Clusters(), Enable::EHCAL_EVAL, Enable::EHCAL_TOWER, EHCAL_Towers(), Fun4AllServer::End(), Enable::ETTL, Enable::FEMC, Enable::FEMC_CLUSTER, FEMC_Clusters(), Enable::FEMC_EVAL, Enable::FEMC_TOWER, FEMC_Towers(), Enable::FGEM, Enable::FHCAL_CLUSTER, FHCAL_Clusters(), Enable::FHCAL_TOWER, FHCAL_Towers(), Enable::FST, Enable::FTTL, g4, G4Init(), G4Setup(), Fun4AllServer::getSubsysReco(), Enable::HCALIN, Enable::HCALIN_CELL, Enable::HCALIN_CLUSTER, Enable::HCALIN_EVAL, Enable::HCALIN_TOWER, HCALInner_Cells(), HCALInner_Clusters(), HCALInner_Towers(), Enable::HCALOUT, Enable::HCALOUT_CELL, Enable::HCALOUT_CLUSTER, Enable::HCALOUT_EVAL, Enable::HCALOUT_TOWER, HCALOuter_Cells(), HCALOuter_Clusters(), HCALOuter_Towers(), Enable::HFARFWD_MAGNETS, Enable::HFARFWD_VIRTUAL_DETECTORS, recoConsts::instance(), Fun4AllServer::instance(), Enable::IP6, Enable::LFHCAL, Enable::LFHCAL_ABSORBER, Enable::LFHCAL_CELL, Enable::LFHCAL_CLUSTER, LFHCAL_Clusters(), Enable::LFHCAL_EVAL, Enable::LFHCAL_TOWER, LFHCAL_Towers(), G4MAGNET::magfield_rescale, Enable::MAGNET, Enable::mRICH, G4TTL::SETTING::optionCEMC, G4TTL::SETTING::optionDR, G4TTL::SETTING::optionEEMCH, G4TTL::SETTING::optionGeo, Enable::PIPE, Enable::PLUGDOOR, G4TRACKING::PROJECTION_CEMC, G4TRACKING::PROJECTION_EEMC, G4TRACKING::PROJECTION_EHCAL, G4TRACKING::PROJECTION_FEMC, G4TRACKING::PROJECTION_FHCAL, Enable::RICH, Fun4AllServer::run(), PHFlag::set_IntFlag(), ShowerCompress(), Enable::TRACKING, Enable::TRACKING_EVAL, Enable::TrackingService, G4PIPE::use_forward_pipes, and Fun4AllBase::Verbosity().