EIC Software: EicToyModel/blob/master/fun4all_with_eicroot/macro/Fun4All_G4_QtDisplay.C File Reference
Fun4All_G4_QtDisplay.C File Reference
#include <fun4all/Fun4AllServer.h>
#include <g4main/PHG4Reco.h>
#include <g4main/PHG4Detector.h>
#include <EicToyModelSubsystem.h>
#include <EicRootVstSubsystem.h>
#include <EtmOrphans.h>
Macros
#define _USE_INTEGRATION_VOLUMES_
Functions
void Fun4All_G4_QtDisplay (void)
Macro Definition Documentation
#define _USE_INTEGRATION_VOLUMES_
Definition at line 17 of file Fun4All_G4_QtDisplay.C.
View newest version in sPHENIX GitHub at line 17 of file Fun4All_G4_QtDisplay.C
Function Documentation
void Fun4All_G4_QtDisplay (void)
Definition at line 19 of file Fun4All_G4_QtDisplay.C.
View newest version in sPHENIX GitHub at line 19 of file Fun4All_G4_QtDisplay.C
References PHG4Reco::ApplyDisplayAction(), g4, ibcell, EicGeoParData::ImportMediaFile(), PHG4Reco::InitRun(), Fun4AllServer::instance(), etm::mm, Fun4AllServer::registerSubsystem(), PHG4Reco::registerSubsystem(), PHG4Reco::save_DST_geometry(), PHG4Reco::StartGui(), Fun4AllServer::topNode(), and vst().