EIC Software: FW::RootMaterialDecorator Class Reference
FW::RootMaterialDecorator Class Reference
Read the collection of SurfaceMaterial & VolumeMaterial.
#include <fun4all_acts/blob/master/Examples/Io/Root/include/ACTFW/Io/Root/RootMaterialDecorator.hpp>
Classes
class Config
Public Member Functions
RootMaterialDecorator (const Config &cfg)
~RootMaterialDecorator ()
Destructor.
void decorate (Acts::Surface &surface) const final
void decorate (Acts::TrackingVolume &volume) const final
Public Member Functions inherited from Acts::IMaterialDecorator
virtual ~IMaterialDecorator ()=default
Virtual Destructor.
Private Member Functions
const Acts::Logger & logger () const
Private access to the logging instance.
Private Attributes
Config m_cfg
The config class.
TFile * m_inputFile {nullptr}
The input file.
Acts::SurfaceMaterialMap m_surfaceMaterialMap
Surface based material.
Acts::VolumeMaterialMap m_volumeMaterialMap
Volume based material.
bool m_clearSurfaceMaterial {true}
Detailed Description
Read the collection of SurfaceMaterial & VolumeMaterial.
Definition at line 38 of file RootMaterialDecorator.hpp.
View newest version in sPHENIX GitHub at line 38 of file RootMaterialDecorator.hpp
Constructor & Destructor Documentation
FW::RootMaterialDecorator::RootMaterialDecorator (const Config & cfg)
Constructor
Parameters
cfg configuration struct for the reader
Definition at line 30 of file RootMaterialDecorator.cpp.
View newest version in sPHENIX GitHub at line 30 of file RootMaterialDecorator.cpp
References ACTS_VERBOSE, FW::RootMaterialDecorator::Config::apptag, FW::RootMaterialDecorator::Config::atag, FW::RootMaterialDecorator::Config::boutag, dz, FW::RootMaterialDecorator::Config::fileName, FW::RootMaterialDecorator::Config::folderNameBase, FW::RootMaterialDecorator::Config::l0tag, FW::RootMaterialDecorator::Config::laytag, FW::RootMaterialDecorator::Config::logger, m_cfg, m_inputFile, m_surfaceMaterialMap, max, FW::RootMaterialDecorator::Config::maxtag, min, FW::RootMaterialDecorator::Config::mintag, n, FW::RootMaterialDecorator::Config::name, FW::RootMaterialDecorator::Config::ntag, FW::RootMaterialDecorator::Config::otag, FW::RootMaterialDecorator::Config::rhotag, rmax(), FW::RootMaterialDecorator::Config::sentag, Acts::GeometryID::setApproach(), Acts::GeometryID::setBoundary(), Acts::GeometryID::setLayer(), Acts::GeometryID::setSensitive(), Acts::GeometryID::setVolume(), t, FW::RootMaterialDecorator::Config::ttag, v, FW::RootMaterialDecorator::Config::voltag, FW::RootMaterialDecorator::Config::vtag, FW::RootMaterialDecorator::Config::x0tag, and FW::RootMaterialDecorator::Config::ztag.
FW::RootMaterialDecorator::~RootMaterialDecorator ()
Destructor.
Definition at line 192 of file RootMaterialDecorator.cpp.
View newest version in sPHENIX GitHub at line 192 of file RootMaterialDecorator.cpp
Member Function Documentation
void FW::RootMaterialDecorator::decorate (Acts::Surface & surface) const inline final virtual
Decorate a surface
Parameters
surface the non-cost surface that is decorated
Implements Acts::IMaterialDecorator.
Definition at line 105 of file RootMaterialDecorator.hpp.
View newest version in sPHENIX GitHub at line 105 of file RootMaterialDecorator.hpp
References m_clearSurfaceMaterial, and m_surfaceMaterialMap.
void FW::RootMaterialDecorator::decorate (Acts::TrackingVolume & volume) const inline final virtual
Decorate a TrackingVolume
Parameters
volume the non-cost volume that is decorated
Implements Acts::IMaterialDecorator.
Definition at line 120 of file RootMaterialDecorator.hpp.
View newest version in sPHENIX GitHub at line 120 of file RootMaterialDecorator.hpp
References m_clearSurfaceMaterial, m_volumeMaterialMap, and Acts::Test::volume.
const Acts::Logger& FW::RootMaterialDecorator::logger () const inline private
Private access to the logging instance.
Definition at line 148 of file RootMaterialDecorator.hpp.
View newest version in sPHENIX GitHub at line 148 of file RootMaterialDecorator.hpp
References FW::RootMaterialDecorator::Config::logger, and m_cfg.
Member Data Documentation
Config FW::RootMaterialDecorator::m_cfg private
The config class.
Definition at line 134 of file RootMaterialDecorator.hpp.
View newest version in sPHENIX GitHub at line 134 of file RootMaterialDecorator.hpp
Referenced by logger(), and RootMaterialDecorator().
bool FW::RootMaterialDecorator::m_clearSurfaceMaterial {true} private
Definition at line 145 of file RootMaterialDecorator.hpp.
View newest version in sPHENIX GitHub at line 145 of file RootMaterialDecorator.hpp
Referenced by decorate().
TFile* FW::RootMaterialDecorator::m_inputFile {nullptr} private
The input file.
Definition at line 137 of file RootMaterialDecorator.hpp.
View newest version in sPHENIX GitHub at line 137 of file RootMaterialDecorator.hpp
Referenced by RootMaterialDecorator().
Acts::SurfaceMaterialMap FW::RootMaterialDecorator::m_surfaceMaterialMap private
Surface based material.
Definition at line 140 of file RootMaterialDecorator.hpp.
View newest version in sPHENIX GitHub at line 140 of file RootMaterialDecorator.hpp
Referenced by decorate(), and RootMaterialDecorator().
Acts::VolumeMaterialMap FW::RootMaterialDecorator::m_volumeMaterialMap private
Volume based material.
Definition at line 143 of file RootMaterialDecorator.hpp.
View newest version in sPHENIX GitHub at line 143 of file RootMaterialDecorator.hpp
Referenced by decorate().
The documentation for this class was generated from the following files:
fun4all_acts/blob/master/Examples/Io/Root/include/ACTFW/Io/Root/RootMaterialDecorator.hpp
fun4all_acts/blob/master/Examples/Io/Root/src/RootMaterialDecorator.cpp