EIC Software: EicFluxMonitorTask Class Reference
EicFluxMonitorTask Class Reference
#include <EicRoot/blob/master/eic/base/EicRunSim.h>
Public Member Functions
EicFluxMonitorTask ()
~EicFluxMonitorTask ()
void FinishEvent ()
void FinishTask ()
Public Member Functions inherited from FairTask
FairTask ()
FairTask (const char *name, Int_t iVerbose=1)
virtual ~FairTask ()
void InitTask ()
void ReInitTask ()
void SetParTask ()
void SetVerbose (Int_t iVerbose)
void SetInputPersistance (Bool_t val)
void CheckInputPersistance (TString branchName)
Private Member Functions
ClassDef (EicFluxMonitorTask, 2)
Private Attributes
UInt_t mStat
Additional Inherited Members
Protected Member Functions inherited from FairTask
virtual InitStatus Init ()
virtual InitStatus ReInit ()
virtual void SetParContainers ()
virtual void Finish ()
void InitTasks ()
void ReInitTasks ()
void SetParTasks ()
void FinishTasks ()
void FinishEvents ()
Protected Attributes inherited from FairTask
Int_t fVerbose
Int_t fInputPersistance
Indicates if input branch is persistant.
FairLogger * fLogger
Detailed Description
Definition at line 231 of file EicRunSim.h.
View newest version in sPHENIX GitHub at line 231 of file EicRunSim.h
Constructor & Destructor Documentation
EicFluxMonitorTask::EicFluxMonitorTask () inline
Definition at line 233 of file EicRunSim.h.
View newest version in sPHENIX GitHub at line 233 of file EicRunSim.h
EicFluxMonitorTask::~EicFluxMonitorTask () inline
Definition at line 234 of file EicRunSim.h.
View newest version in sPHENIX GitHub at line 234 of file EicRunSim.h
Member Function Documentation
EicFluxMonitorTask::ClassDef (EicFluxMonitorTask , 2) private
void EicFluxMonitorTask::FinishEvent () inline virtual
Action at end of event. For this task and all of the subtasks.
Reimplemented from FairTask.
Definition at line 237 of file EicRunSim.h.
View newest version in sPHENIX GitHub at line 237 of file EicRunSim.h
References FairTask::FinishEvent(), and mStat.
void EicFluxMonitorTask::FinishTask () virtual
Action at end of run. For this task and all of the subtasks.
Reimplemented from FairTask.
Definition at line 638 of file EicRunSim.cxx.
View newest version in sPHENIX GitHub at line 638 of file EicRunSim.cxx
References FluxMonitorGrid::FillOutHistograms(), FairTask::FinishTask(), EicRunSim::GetFluxMonitorGrid(), EicRunSim::Instance(), mStat, and printf().
Member Data Documentation
UInt_t EicFluxMonitorTask::mStat private
Definition at line 242 of file EicRunSim.h.
View newest version in sPHENIX GitHub at line 242 of file EicRunSim.h
Referenced by FinishEvent(), and FinishTask().
The documentation for this class was generated from the following files:
EicRoot/blob/master/eic/base/EicRunSim.h
EicRoot/blob/master/eic/base/EicRunSim.cxx