EIC Software: EicGeoParData Class Reference
EicGeoParData Class Reference
#include <EicRoot/blob/master/eic/base/EicGeoParData.h>
Public Types
enum GeometryType {
Undefined, NoStructure, SimpleStructure, FullStructure,
Undefined, NoStructure, SimpleStructure, FullStructure
}
enum IDXYZ {
IDX =0, IDY, IDZ, IDX =0,
IDY, IDZ
}
enum GeometryType {
Undefined, NoStructure, SimpleStructure, FullStructure,
Undefined, NoStructure, SimpleStructure, FullStructure
}
enum IDXYZ {
IDX =0, IDY, IDZ, IDX =0,
IDY, IDZ
}
Public Member Functions
EicGeoParData (const char *detName=0, int version=-1, int subVersion=0)
~EicGeoParData ()
void ResetVars ()
void SetGeometryType (GeometryType gType)
GeometryType GetGeometryType () const
void SetTestGeometryFlag (bool flag=true)
bool IsTestGeometry () const
int GetVersion () const
int GetSubVersion () const
void SetFileName (const char *fileName)
void SetFileNameFormat (const char *fileNameFormat)
void SetComment (const char *comment)
int AttachSourceFile (const char *fileName)
void PrintAttachedSourceFile (const char *fileName)
EicGeoMap * CreateNewMap ()
int SetCircularX (unsigned group=0)
int SetCircularY (unsigned group=0)
int SetCircularZ (unsigned group=0)
bool GetCircularX (unsigned group=0) const
bool GetCircularY (unsigned group=0) const
bool GetCircularZ (unsigned group=0) const
bool GetCircular (unsigned group, unsigned what) const
int SetMappingTableEntry (EicGeoMap *map, const unsigned geant[], unsigned group, unsigned logical[])
int AddLogicalVolumeGroup (unsigned dimX=0, unsigned dimY=0, unsigned dimZ=0)
void AddBlackHoleVolume (const char *vName)
void AddStepEnforcedVolume (const char *vName)
void AddStepEnforcedVolumeLookupEntry (int volumeID, double step)
const TGeoMedium * GetMedium (const char *medium)
void SetTopVolumeTransformation (TGeoMatrix *transformation)
const TGeoMatrix * GetTopVolumeTransformation () const
TString GetGeometryFileName (bool root=true) const
virtual void Print (const char *option=0) const
virtual int ConstructGeometry (bool root=true, bool gdml=false, bool check=false)
TGeoVolume * GetTopVolume () const
TGeoManager * GetRootGeoManager ()
void FinalizeOutput (bool root=true, bool gdml=false, bool check=false)
UInt_t GetMapNum () const
EicGeoMap * GetMapPtrViaMapID (unsigned mapId) const
const EicGeoMap * GetMapPtrViaHitMultiIndex (ULong64_t multi) const
int CalculateMappingTableSignatures ()
unsigned GetMaxVolumeLevelNum () const
ULogicalIndex_t GeantMultiToLogicalIndex (ULong64_t multi) const
unsigned GetDimX (unsigned group=0) const
unsigned GetDimY (unsigned group=0) const
unsigned GetDimZ (unsigned group=0) const
unsigned GetDim (unsigned group, unsigned what) const
unsigned GetGroup (ULogicalIndex_t logicalID) const
unsigned GetX (ULogicalIndex_t logicalID) const
unsigned GetY (ULogicalIndex_t logicalID) const
unsigned GetZ (ULogicalIndex_t logicalID) const
unsigned GetCoord (unsigned what, ULogicalIndex_t logicalID) const
bool IsBlackHoleVolume (const char *vName) const
const std::set< TString > & GetBlackHoleVolumes () const
double GetEnforcedStep (int volumeID)
const std::set< TString > & GetStepEnforcedVolumes () const
void InitializeLookupTables ()
LogicalVolumeLookupTableEntry * GetLookupTableNode (ULogicalIndex_t xy) const
LogicalVolumeLookupTableEntry * GetLookupTableNode (const TGeoNode *node) const
EicNamePatternHub< Color_t > * GetColorTable ()
EicNamePatternHub< Char_t > * GetTransparencyTable ()
virtual bool AreNeighbours (ULogicalIndex_t l1, ULogicalIndex_t l2, unsigned maxLinearDist=1, unsigned maxChebyshevDist=0) const
const EicDetName * GetDetName () const
void AddWantedParticle (const char *vName, int pdg)
bool IsWantedParticle (const char *vName, int pdg) const
EicGeoParData (const char *detName=0, int version=-1, int subVersion=0)
~EicGeoParData ()
void ResetVars ()
void SetGeometryType (GeometryType gType)
GeometryType GetGeometryType () const
void SetTestGeometryFlag (bool flag=true)
bool IsTestGeometry () const
int GetVersion () const
int GetSubVersion () const
void SetFileName (const char *fileName)
void SetFileNameFormat (const char *fileNameFormat)
void SetTransparency (unsigned value)
void SetComment (const char *comment)
int AttachSourceFile (const char *fileName)
void PrintAttachedSourceFile (const char *fileName)
EicGeoMap * CreateNewMap ()
int SetCircularX (unsigned group=0)
int SetCircularY (unsigned group=0)
int SetCircularZ (unsigned group=0)
bool GetCircularX (unsigned group=0) const
bool GetCircularY (unsigned group=0) const
bool GetCircularZ (unsigned group=0) const
bool GetCircular (unsigned group, unsigned what) const
int SetMappingTableEntry (EicGeoMap *map, const unsigned geant[], unsigned group, unsigned logical[])
int AddLogicalVolumeGroup (unsigned dimX=0, unsigned dimY=0, unsigned dimZ=0)
void AddBlackHoleVolume (const char *vName)
void AddStepEnforcedVolume (const char *vName)
void AddStepEnforcedVolumeLookupEntry (int volumeID, double step)
const TGeoMedium * GetMedium (const char *medium)
void SetTopVolumeTransformation (TGeoMatrix *transformation)
const TGeoMatrix * GetTopVolumeTransformation () const
TString GetGeometryFileName (bool root=true) const
virtual void Print (const char *option=0) const
virtual int ConstructGeometry (bool root=true, bool gdml=false, bool check=false)
TGeoVolume * GetTopVolume () const
TGeoManager * GetRootGeoManager ()
void FinalizeOutput (bool root=true, bool gdml=false, bool check=false)
UInt_t GetMapNum () const
EicGeoMap * GetMapPtrViaMapID (unsigned mapId) const
const EicGeoMap * GetMapPtrViaHitMultiIndex (ULong64_t multi) const
int CalculateMappingTableSignatures ()
unsigned GetMaxVolumeLevelNum () const
ULogicalIndex_t GeantMultiToLogicalIndex (ULong64_t multi) const
void PlaceG4Volume (G4LogicalVolume *mother, bool check=false, void *pRot=0, void *tlate=0)
unsigned GetDimX (unsigned group=0) const
unsigned GetDimY (unsigned group=0) const
unsigned GetDimZ (unsigned group=0) const
unsigned GetDim (unsigned group, unsigned what) const
unsigned GetGroup (ULogicalIndex_t logicalID) const
unsigned GetX (ULogicalIndex_t logicalID) const
unsigned GetY (ULogicalIndex_t logicalID) const
unsigned GetZ (ULogicalIndex_t logicalID) const
unsigned GetCoord (unsigned what, ULogicalIndex_t logicalID) const
bool IsBlackHoleVolume (const char *vName) const
const std::set< TString > & GetBlackHoleVolumes () const
double GetEnforcedStep (int volumeID)
const std::set< TString > & GetStepEnforcedVolumes () const
void InitializeLookupTables ()
LogicalVolumeLookupTableEntry * GetLookupTableNode (ULogicalIndex_t xy) const
LogicalVolumeLookupTableEntry * GetLookupTableNode (const TGeoNode *node) const
EicNamePatternHub< Color_t > * GetColorTable ()
EicNamePatternHub< Char_t > * GetTransparencyTable ()
virtual bool AreNeighbours (ULogicalIndex_t l1, ULogicalIndex_t l2, unsigned maxLinearDist=1, unsigned maxChebyshevDist=0) const
const EicDetName * GetDetName () const
void AddWantedParticle (const char *vName, int pdg)
bool IsWantedParticle (const char *vName, int pdg) const
void SetTGeoGeometryCheckPrecision (double value)
void TurnTGeoGeometryCheckOff (void)
const std::vector
< G4VPhysicalVolume * > & GetG4Volumes (void) const
const std::map
< G4VPhysicalVolume
*, unsigned > & GetG4SensitiveVolumes (void) const
ClassDef (EicGeoParData, 51)
Static Public Member Functions
static int ImportMediaFile (const char *fname)
Protected Attributes
GeometryType mGeometryType
Bool_t mTestGeometryFlag
EicDetName * mDetName
respective lookup table (for efficiency)
unsigned char mTransparency
Private Member Functions
int SetCircularCore (unsigned group, unsigned what)
bool GetCircularCore (unsigned group, unsigned what) const
unsigned GetDimCore (unsigned group, unsigned what) const
unsigned GetLogicalCoordCore (unsigned what, ULogicalIndex_t logicalID) const
ClassDef (EicGeoParData, 48)
int SetCircularCore (unsigned group, unsigned what)
bool GetCircularCore (unsigned group, unsigned what) const
void AssignG4Colors (G4VPhysicalVolume *pvol)
unsigned GetDimCore (unsigned group, unsigned what) const
unsigned GetLogicalCoordCore (unsigned what, ULogicalIndex_t logicalID) const
void SwitchGeoManager (void)
void RestoreGeoManager (void)
Private Attributes
Int_t mVersion
Int_t mSubVersion
TString mFileName
TString mFileNameFormat
excplicit file name
TString mAuthor
explicit file name formatting string
TString mComment
std::vector< SourceFile * > mSourceFiles
TTimeStamp mTimeStamp
TGeoMatrix * mTopVolumeTransformation
std::vector< EicGeoMap * > mGeantVolumeMaps
UInt_t mMaxVolumeLevelNum
std::vector< LogicalVolumeGroup * > mLogicalVolumeGroups
max number of volume levels on any of the maps
std::set< TString > mBlackHoleVolumes
std::set< std::pair< TString,
Int_t > > mWantedParticles
std::set< TString > mStepEnforcedVolumes
std::map< int, double > mStepEnforcedVolumesLookup
TGeoManager * mRootGeoManager
TGeoVolume * mWrapperVolume
TGeoVolume * mTopVolume
FairGeoLoader * mGeoLoad
FairGeoInterface * mGeoFace
FairGeoMedia * mFairMedia
FairGeoBuilder * mGeobuild
std::set< const char * > mMediaCache
std::map< const TGeoNode
*, LogicalVolumeLookupTableEntry * > mGeantToLogicalLookupTable
EicNamePatternHub< Color_t > * mColorRequests
EicNamePatternHub< Char_t > * mTransparencyRequests
TGeoManager * mSavedGeoManager
TGeoIdentity * mSavedGeoIdentity
std::map< TString, unsigned > mSensitiveVolumeNames
std::vector< G4VPhysicalVolume * > mG4Volumes
std::map< G4VPhysicalVolume
*, unsigned > mG4SensitiveVolumes
double mGeometryCheckPrecision
Static Private Attributes
static EicGeoMedia * mEicMedia = 0
Detailed Description
Definition at line 171 of file EicGeoParData.h.
View newest version in sPHENIX GitHub at line 171 of file EicGeoParData.h
Member Enumeration Documentation
enum EicGeoParData::GeometryType
Enumerator:
Undefined
NoStructure
SimpleStructure
FullStructure
Undefined
NoStructure
SimpleStructure
FullStructure
Definition at line 179 of file EicGeoParData.h.
View newest version in sPHENIX GitHub at line 179 of file EicGeoParData.h
enum EicGeoParData::GeometryType
Enumerator:
Undefined
NoStructure
SimpleStructure
FullStructure
Undefined
NoStructure
SimpleStructure
FullStructure
Definition at line 181 of file EicGeoParData.h.
View newest version in sPHENIX GitHub at line 181 of file EicGeoParData.h
enum EicGeoParData::IDXYZ
Enumerator:
IDX
IDY
IDZ
IDX
IDY
IDZ
Definition at line 278 of file EicGeoParData.h.
View newest version in sPHENIX GitHub at line 278 of file EicGeoParData.h
enum EicGeoParData::IDXYZ
Enumerator:
IDX
IDY
IDZ
IDX
IDY
IDZ
Definition at line 282 of file EicGeoParData.h.
View newest version in sPHENIX GitHub at line 282 of file EicGeoParData.h
Constructor & Destructor Documentation
EicGeoParData::EicGeoParData (const char * detName = 0, int version = -1, int subVersion = 0)
Definition at line 58 of file EicGeoParData.cxx.
View newest version in sPHENIX GitHub at line 58 of file EicGeoParData.cxx
References FairGeoLoader::getGeoBuilder(), FairGeoLoader::getGeoInterface(), FairGeoInterface::getMedia(), FairGeoLoader::Instance(), FairRun::Instance(), mDetName, mFairMedia, mGeobuild, mGeoFace, mGeoLoad, mRootGeoManager, mTopVolume, mWrapperVolume, EicDetName::NAME(), EicDetName::Name(), FairGeoInterface::readMedia(), ResetVars(), and FairGeoInterface::setMediaFile().
EicGeoParData::~EicGeoParData () inline
Definition at line 175 of file EicGeoParData.h.
View newest version in sPHENIX GitHub at line 175 of file EicGeoParData.h
EicGeoParData::EicGeoParData (const char * detName = 0, int version = -1, int subVersion = 0)
EicGeoParData::~EicGeoParData () inline
Definition at line 177 of file EicGeoParData.h.
View newest version in sPHENIX GitHub at line 177 of file EicGeoParData.h
Member Function Documentation
void EicGeoParData::AddBlackHoleVolume (const char * vName) inline
Definition at line 234 of file EicGeoParData.h.
View newest version in sPHENIX GitHub at line 234 of file EicGeoParData.h
References mBlackHoleVolumes.
Referenced by femc(), and hcal().
void EicGeoParData::AddBlackHoleVolume (const char * vName) inline
Definition at line 238 of file EicGeoParData.h.
View newest version in sPHENIX GitHub at line 238 of file EicGeoParData.h
References mBlackHoleVolumes.
int EicGeoParData::AddLogicalVolumeGroup (unsigned dimX = 0, unsigned dimY = 0, unsigned dimZ = 0)
Definition at line 113 of file EicGeoParData.cxx.
View newest version in sPHENIX GitHub at line 113 of file EicGeoParData.cxx
References _LOGICAL_GROUP_NUM_MAX_, _LOGICAL_VOLUME_GROUP_COORD_NUM_, _LOGICAL_XYZ_BIT_NUM_, Acts::Test::dim, EicBitMask< T >::GetBitNum(), max, LogicalVolumeGroupProjection::mBitMask, mLogicalVolumeGroups, LogicalVolumeGroup::mProjections, printf(), and EicBitMask< T >::SetShift().
Referenced by b0tracker(), FstGeoParData::ConstructGeometry(), femc(), hcal(), ip(), ippt(), lqst(), rich(), romanPot_v2(), rp(), tpc(), tracker(), and zdc().
int EicGeoParData::AddLogicalVolumeGroup (unsigned dimX = 0, unsigned dimY = 0, unsigned dimZ = 0)
void EicGeoParData::AddStepEnforcedVolume (const char * vName) inline
Definition at line 237 of file EicGeoParData.h.
View newest version in sPHENIX GitHub at line 237 of file EicGeoParData.h
References mStepEnforcedVolumes.
Referenced by tpc().
void EicGeoParData::AddStepEnforcedVolume (const char * vName) inline
Definition at line 241 of file EicGeoParData.h.
View newest version in sPHENIX GitHub at line 241 of file EicGeoParData.h
References mStepEnforcedVolumes.
void EicGeoParData::AddStepEnforcedVolumeLookupEntry (int volumeID, double step) inline
Definition at line 240 of file EicGeoParData.h.
View newest version in sPHENIX GitHub at line 240 of file EicGeoParData.h
References mStepEnforcedVolumesLookup.
Referenced by EicDetector::ConstructGeometry().
void EicGeoParData::AddStepEnforcedVolumeLookupEntry (int volumeID, double step) inline
Definition at line 244 of file EicGeoParData.h.
View newest version in sPHENIX GitHub at line 244 of file EicGeoParData.h
References mStepEnforcedVolumesLookup.
void EicGeoParData::AddWantedParticle (const char * vName, int pdg) inline
Definition at line 370 of file EicGeoParData.h.
View newest version in sPHENIX GitHub at line 370 of file EicGeoParData.h
References mWantedParticles.
Referenced by zdc().
void EicGeoParData::AddWantedParticle (const char * vName, int pdg) inline
Definition at line 383 of file EicGeoParData.h.
View newest version in sPHENIX GitHub at line 383 of file EicGeoParData.h
References mWantedParticles.
bool EicGeoParData::AreNeighbours (ULogicalIndex_t l1, ULogicalIndex_t l2, unsigned maxLinearDist = 1, unsigned maxChebyshevDist = 0) const virtual
Definition at line 657 of file EicGeoParData.cxx.
View newest version in sPHENIX GitHub at line 657 of file EicGeoParData.cxx
References _LOGICAL_VOLUME_GROUP_COORD_NUM_, kdfinder::abs(), Acts::Test::dim, GetCircularX(), GetCircularY(), GetCircularZ(), GetDimX(), GetDimY(), GetDimZ(), GetGroup(), GetX(), GetY(), GetZ(), and x2.
Referenced by EicCalorimeterReconstruction::AreNeighbors().
virtual bool EicGeoParData::AreNeighbours (ULogicalIndex_t l1, ULogicalIndex_t l2, unsigned maxLinearDist = 1, unsigned maxChebyshevDist = 0) const virtual
void EicGeoParData::AssignG4Colors (G4VPhysicalVolume * pvol) private
Definition at line 265 of file EicGeoParData.cxx.
View newest version in sPHENIX GitHub at line 265 of file EicGeoParData.cxx
References EicNamePatternHub< T >::AnyMatch(), GetColorTable(), GetTransparencyTable(), mG4SensitiveVolumes, mG4Volumes, and mSensitiveVolumeNames.
Referenced by PlaceG4Volume().
int EicGeoParData::AttachSourceFile (const char * fileName)
Definition at line 298 of file EicGeoParData.cxx.
View newest version in sPHENIX GitHub at line 298 of file EicGeoParData.cxx
References eicpy.qaplots::file, SourceFile::IsOk(), and mSourceFiles.
Referenced by aerogel(), fbgt(), fbst(), mumegas(), tpc(), and vst().
int EicGeoParData::AttachSourceFile (const char * fileName)
Int_t EicGeoParData::CalculateMappingTableSignatures ()
Definition at line 494 of file EicGeoParData.cxx.
View newest version in sPHENIX GitHub at line 494 of file EicGeoParData.cxx
References EicGeoMap::CalculateMappingTableSignature(), EicGeoMap::GetGeantVolumeLevelNum(), mGeantVolumeMaps, and mMaxVolumeLevelNum.
Referenced by EicDetector::Initialize().
int EicGeoParData::CalculateMappingTableSignatures ()
EicGeoParData::ClassDef (EicGeoParData , 48) private
EicGeoParData::ClassDef (EicGeoParData , 51)
virtual int EicGeoParData::ConstructGeometry (bool root = true, bool gdml = false, bool check = false) inline virtual
Reimplemented in GemGeoParData, GemGeoParData, MuMegasGeoParData, MuMegasGeoParData, FstGeoParData, FstGeoParData, VstGeoParData, and VstGeoParData.
Definition at line 263 of file EicGeoParData.h.
View newest version in sPHENIX GitHub at line 263 of file EicGeoParData.h
Referenced by aerogel(), and PlaceG4Volume().
virtual int EicGeoParData::ConstructGeometry (bool root = true, bool gdml = false, bool check = false) inline virtual
Reimplemented in GemGeoParData, GemGeoParData, MuMegasGeoParData, MuMegasGeoParData, FstGeoParData, FstGeoParData, VstGeoParData, and VstGeoParData.
Definition at line 267 of file EicGeoParData.h.
View newest version in sPHENIX GitHub at line 267 of file EicGeoParData.h
EicGeoMap * EicGeoParData::CreateNewMap ()
Definition at line 104 of file EicGeoParData.cxx.
View newest version in sPHENIX GitHub at line 104 of file EicGeoParData.cxx
References mGeantVolumeMaps.
Referenced by b0tracker(), VstGeoParData::ConstructGeometry(), FstGeoParData::ConstructGeometry(), femc(), hcal(), ip(), ippt(), lqst(), rich(), romanPot_v2(), rp(), tpc(), tracker(), and zdc().
EicGeoMap* EicGeoParData::CreateNewMap ()
void EicGeoParData::FinalizeOutput (bool root = true, bool gdml = false, bool check = false)
Definition at line 381 of file EicGeoParData.cxx.
View newest version in sPHENIX GitHub at line 381 of file EicGeoParData.cxx
References EicNamePatternHub< T >::AnyMatch(), GetColorTable(), GetGeometryFileName(), GetTransparencyTable(), mDetName, mRootGeoManager, mTopVolume, mTopVolumeTransformation, mWrapperVolume, EicDetName::Name(), and Acts::Test::volume.
Referenced by aerogel(), EicCadWizard::AssembleRootFiles(), b0tracker(), FstGeoParData::ConstructGeometry(), BeamPipeGeoParData::ConstructGeometry(), EicCadWizard::CreateBooleanSolidRootFile(), EicCadWizard::CreateGhostSolidRootFile(), EicCadWizard::CreateStlSolidRootFile(), femc(), hcal(), ip(), ippt(), lqst(), rich(), romanPot_v2(), rp(), tpc(), tracker(), and zdc().
void EicGeoParData::FinalizeOutput (bool root = true, bool gdml = false, bool check = false)
ULogicalIndex_t EicGeoParData::GeantMultiToLogicalIndex (ULong64_t multi) const
Definition at line 642 of file EicGeoParData.cxx.
View newest version in sPHENIX GitHub at line 642 of file EicGeoParData.cxx
References _GEANT_INDEX_BIT_MASK_, _GEANT_INDEX_BIT_NUM_, _SERVICE_BIT_MASK_, and mGeantVolumeMaps.
Referenced by EicHtcTask::Exec(), EicTrackingRecoHit::GetLookupTableNode(), EicDetectorGroup::GetSensitiveVolume(), EicCalorimeterDigiHitProducer::HandleHit(), and EicTrackingDigiHitProducer::HandleHit().
ULogicalIndex_t EicGeoParData::GeantMultiToLogicalIndex (ULong64_t multi) const
const std::set<TString>& EicGeoParData::GetBlackHoleVolumes () const inline
Definition at line 329 of file EicGeoParData.h.
View newest version in sPHENIX GitHub at line 329 of file EicGeoParData.h
References mBlackHoleVolumes.
Referenced by EicDetector::BeginEvent().
const std::set<TString>& EicGeoParData::GetBlackHoleVolumes () const inline
Definition at line 342 of file EicGeoParData.h.
View newest version in sPHENIX GitHub at line 342 of file EicGeoParData.h
References mBlackHoleVolumes.
bool EicGeoParData::GetCircular (unsigned group, unsigned what) const inline
Definition at line 225 of file EicGeoParData.h.
View newest version in sPHENIX GitHub at line 225 of file EicGeoParData.h
References GetCircularCore().
bool EicGeoParData::GetCircular (unsigned group, unsigned what) const inline
Definition at line 229 of file EicGeoParData.h.
View newest version in sPHENIX GitHub at line 229 of file EicGeoParData.h
References GetCircularCore().
bool EicGeoParData::GetCircularCore (unsigned group, unsigned what) const private
Definition at line 477 of file EicGeoParData.cxx.
View newest version in sPHENIX GitHub at line 477 of file EicGeoParData.cxx
References mLogicalVolumeGroups.
Referenced by GetCircular(), GetCircularX(), GetCircularY(), and GetCircularZ().
bool EicGeoParData::GetCircularCore (unsigned group, unsigned what) const private
bool EicGeoParData::GetCircularX (unsigned group = 0) const inline
Definition at line 222 of file EicGeoParData.h.
View newest version in sPHENIX GitHub at line 222 of file EicGeoParData.h
References GetCircularCore(), and IDX.
Referenced by AreNeighbours().
bool EicGeoParData::GetCircularX (unsigned group = 0) const inline
Definition at line 226 of file EicGeoParData.h.
View newest version in sPHENIX GitHub at line 226 of file EicGeoParData.h
References GetCircularCore(), and IDX.
bool EicGeoParData::GetCircularY (unsigned group = 0) const inline
Definition at line 223 of file EicGeoParData.h.
View newest version in sPHENIX GitHub at line 223 of file EicGeoParData.h
References GetCircularCore(), and IDY.
Referenced by AreNeighbours().
bool EicGeoParData::GetCircularY (unsigned group = 0) const inline
Definition at line 227 of file EicGeoParData.h.
View newest version in sPHENIX GitHub at line 227 of file EicGeoParData.h
References GetCircularCore(), and IDY.
bool EicGeoParData::GetCircularZ (unsigned group = 0) const inline
Definition at line 224 of file EicGeoParData.h.
View newest version in sPHENIX GitHub at line 224 of file EicGeoParData.h
References GetCircularCore(), and IDZ.
Referenced by AreNeighbours().
bool EicGeoParData::GetCircularZ (unsigned group = 0) const inline
Definition at line 228 of file EicGeoParData.h.
View newest version in sPHENIX GitHub at line 228 of file EicGeoParData.h
References GetCircularCore(), and IDZ.
EicNamePatternHub<Color_t>* EicGeoParData::GetColorTable () inline
Definition at line 350 of file EicGeoParData.h.
View newest version in sPHENIX GitHub at line 350 of file EicGeoParData.h
References mColorRequests.
Referenced by aerogel(), EicCadWizard::AssembleRootFiles(), AssignG4Colors(), b0tracker(), beampipe(), EicCadWizard::CreateBooleanSolidRootFile(), EicCadWizard::CreateGhostSolidRootFile(), EicCadWizard::CreateStlSolidRootFile(), fbgt(), femc(), FinalizeOutput(), hcal(), ip(), ippt(), lqst(), mumegas(), rich(), rp(), tpc(), tracker(), and zdc().
EicNamePatternHub<Color_t>* EicGeoParData::GetColorTable () inline
Definition at line 363 of file EicGeoParData.h.
View newest version in sPHENIX GitHub at line 363 of file EicGeoParData.h
References mColorRequests.
unsigned EicGeoParData::GetCoord (unsigned what, ULogicalIndex_t logicalID) const inline
Definition at line 319 of file EicGeoParData.h.
View newest version in sPHENIX GitHub at line 319 of file EicGeoParData.h
References GetLogicalCoordCore().
Referenced by GetLookupTableNode().
unsigned EicGeoParData::GetCoord (unsigned what, ULogicalIndex_t logicalID) const inline
Definition at line 332 of file EicGeoParData.h.
View newest version in sPHENIX GitHub at line 332 of file EicGeoParData.h
References GetLogicalCoordCore().
const EicDetName* EicGeoParData::GetDetName () const inline
Definition at line 368 of file EicGeoParData.h.
View newest version in sPHENIX GitHub at line 368 of file EicGeoParData.h
References mDetName.
Referenced by EicCadWizard::AssembleRootFiles(), femc(), hcal(), and make_single_tower().
const EicDetName* EicGeoParData::GetDetName () const inline
Definition at line 381 of file EicGeoParData.h.
View newest version in sPHENIX GitHub at line 381 of file EicGeoParData.h
References mDetName.
unsigned EicGeoParData::GetDim (unsigned group, unsigned what) const inline
Definition at line 301 of file EicGeoParData.h.
View newest version in sPHENIX GitHub at line 301 of file EicGeoParData.h
References GetDimCore().
Referenced by InitializeLookupTables().
unsigned EicGeoParData::GetDim (unsigned group, unsigned what) const inline
Definition at line 312 of file EicGeoParData.h.
View newest version in sPHENIX GitHub at line 312 of file EicGeoParData.h
References GetDimCore().
unsigned EicGeoParData::GetDimCore (unsigned group, unsigned what) const private
Definition at line 447 of file EicGeoParData.cxx.
View newest version in sPHENIX GitHub at line 447 of file EicGeoParData.cxx
References mLogicalVolumeGroups.
Referenced by GetDim(), GetDimX(), GetDimY(), and GetDimZ().
unsigned EicGeoParData::GetDimCore (unsigned group, unsigned what) const private
unsigned EicGeoParData::GetDimX (unsigned group = 0) const inline
Definition at line 298 of file EicGeoParData.h.
View newest version in sPHENIX GitHub at line 298 of file EicGeoParData.h
References GetDimCore(), and IDX.
Referenced by AreNeighbours().
unsigned EicGeoParData::GetDimX (unsigned group = 0) const inline
Definition at line 309 of file EicGeoParData.h.
View newest version in sPHENIX GitHub at line 309 of file EicGeoParData.h
References GetDimCore(), and IDX.
unsigned EicGeoParData::GetDimY (unsigned group = 0) const inline
Definition at line 299 of file EicGeoParData.h.
View newest version in sPHENIX GitHub at line 299 of file EicGeoParData.h
References GetDimCore(), and IDY.
Referenced by AreNeighbours().
unsigned EicGeoParData::GetDimY (unsigned group = 0) const inline
Definition at line 310 of file EicGeoParData.h.
View newest version in sPHENIX GitHub at line 310 of file EicGeoParData.h
References GetDimCore(), and IDY.
unsigned EicGeoParData::GetDimZ (unsigned group = 0) const inline
Definition at line 300 of file EicGeoParData.h.
View newest version in sPHENIX GitHub at line 300 of file EicGeoParData.h
References GetDimCore(), and IDZ.
Referenced by AreNeighbours().
unsigned EicGeoParData::GetDimZ (unsigned group = 0) const inline
Definition at line 311 of file EicGeoParData.h.
View newest version in sPHENIX GitHub at line 311 of file EicGeoParData.h
References GetDimCore(), and IDZ.
double EicGeoParData::GetEnforcedStep (int volumeID) inline
Definition at line 332 of file EicGeoParData.h.
View newest version in sPHENIX GitHub at line 332 of file EicGeoParData.h
References mStepEnforcedVolumesLookup.
Referenced by EicDetector::ProcessHits().
double EicGeoParData::GetEnforcedStep (int volumeID) inline
Definition at line 345 of file EicGeoParData.h.
View newest version in sPHENIX GitHub at line 345 of file EicGeoParData.h
References mStepEnforcedVolumesLookup.
const std::map<G4VPhysicalVolume*, unsigned>& EicGeoParData::GetG4SensitiveVolumes (void) const inline
Definition at line 506 of file EicGeoParData.h.
View newest version in sPHENIX GitHub at line 506 of file EicGeoParData.h
References mG4SensitiveVolumes.
Referenced by EicRootGemSubsystem::GetG4SensitiveVolumes(), EicRootVstSubsystem::GetG4SensitiveVolumes(), and EicRootMuMegasSubsystem::GetG4SensitiveVolumes().
const std::vector<G4VPhysicalVolume*>& EicGeoParData::GetG4Volumes (void) const inline
Definition at line 505 of file EicGeoParData.h.
View newest version in sPHENIX GitHub at line 505 of file EicGeoParData.h
References mG4Volumes.
TString EicGeoParData::GetGeometryFileName (bool root = true) const
Definition at line 332 of file EicGeoParData.cxx.
View newest version in sPHENIX GitHub at line 332 of file EicGeoParData.cxx
References FullStructure, GetGeometryType(), GetSubVersion(), GetVersion(), IsTestGeometry(), mDetName, mFileName, mFileNameFormat, EicDetName::name(), NoStructure, SimpleStructure, Undefined, and conf::version.
Referenced by FinalizeOutput().
TString EicGeoParData::GetGeometryFileName (bool root = true) const
GeometryType EicGeoParData::GetGeometryType () const inline
Definition at line 186 of file EicGeoParData.h.
View newest version in sPHENIX GitHub at line 186 of file EicGeoParData.h
References mGeometryType.
Referenced by GetGeometryFileName().
GeometryType EicGeoParData::GetGeometryType () const inline
Definition at line 188 of file EicGeoParData.h.
View newest version in sPHENIX GitHub at line 188 of file EicGeoParData.h
References mGeometryType.
unsigned EicGeoParData::GetGroup (ULogicalIndex_t logicalID) const inline
Definition at line 303 of file EicGeoParData.h.
View newest version in sPHENIX GitHub at line 303 of file EicGeoParData.h
References _LOGICAL_GROUP_MASK_, and _LOGICAL_XYZ_BIT_NUM_.
Referenced by AreNeighbours(), GetLogicalCoordCore(), and GetLookupTableNode().
unsigned EicGeoParData::GetGroup (ULogicalIndex_t logicalID) const inline
Definition at line 314 of file EicGeoParData.h.
View newest version in sPHENIX GitHub at line 314 of file EicGeoParData.h
References _LOGICAL_GROUP_MASK_, and _LOGICAL_XYZ_BIT_NUM_.
unsigned EicGeoParData::GetLogicalCoordCore (unsigned what, ULogicalIndex_t logicalID) const private
Definition at line 459 of file EicGeoParData.cxx.
View newest version in sPHENIX GitHub at line 459 of file EicGeoParData.cxx
References EicBitMask< T >::GetBitMask(), GetGroup(), EicBitMask< T >::GetShift(), and mLogicalVolumeGroups.
Referenced by GetCoord(), GetX(), GetY(), and GetZ().
unsigned EicGeoParData::GetLogicalCoordCore (unsigned what, ULogicalIndex_t logicalID) const private
LogicalVolumeLookupTableEntry * EicGeoParData::GetLookupTableNode (ULogicalIndex_t xy) const
Definition at line 611 of file EicGeoParData.cxx.
View newest version in sPHENIX GitHub at line 611 of file EicGeoParData.cxx
References _LOGICAL_VOLUME_GROUP_COORD_NUM_, GetCoord(), GetGroup(), mLogicalVolumeGroups, LogicalVolumeGroup::mLookup, LogicalVolumeGroup::mRealDim, and offset.
Referenced by EicHtcTask::DeclareSensitiveVolumes(), EicHtcTask::Exec(), EicTrackingRecoHit::GetLookupTableNode(), EicDetectorGroup::GetSensitiveVolume(), EicCalorimeterDigiHitProducer::HandleHit(), EicTrackingDigiHitProducer::HandleHit(), and InitializeLookupTables().
LogicalVolumeLookupTableEntry * EicGeoParData::GetLookupTableNode (const TGeoNode * node) const
Definition at line 629 of file EicGeoParData.cxx.
View newest version in sPHENIX GitHub at line 629 of file EicGeoParData.cxx
References mGeantToLogicalLookupTable.
LogicalVolumeLookupTableEntry* EicGeoParData::GetLookupTableNode (ULogicalIndex_t xy) const
LogicalVolumeLookupTableEntry* EicGeoParData::GetLookupTableNode (const TGeoNode * node) const
UInt_t EicGeoParData::GetMapNum () const inline
Definition at line 280 of file EicGeoParData.h.
View newest version in sPHENIX GitHub at line 280 of file EicGeoParData.h
References mGeantVolumeMaps.
Referenced by EicDetector::ConstructGeometry(), EicCalorimeterDigiHitProducer::ExtraInit(), EicDetector::GetNodeMultiIndex(), EicDigiHitProducer::Init(), and PlaceG4Volume().
UInt_t EicGeoParData::GetMapNum () const inline
Definition at line 284 of file EicGeoParData.h.
View newest version in sPHENIX GitHub at line 284 of file EicGeoParData.h
References mGeantVolumeMaps.
const EicGeoMap* EicGeoParData::GetMapPtrViaHitMultiIndex (ULong64_t multi) const inline
Definition at line 285 of file EicGeoParData.h.
View newest version in sPHENIX GitHub at line 285 of file EicGeoParData.h
References _GEANT_INDEX_BIT_NUM_, _SERVICE_BIT_MASK_, and GetMapPtrViaMapID().
Referenced by EicCalorimeterDigiHitProducer::HandleHit(), and EicTrackingDigiHitProducer::HandleHit().
const EicGeoMap* EicGeoParData::GetMapPtrViaHitMultiIndex (ULong64_t multi) const inline
Definition at line 289 of file EicGeoParData.h.
View newest version in sPHENIX GitHub at line 289 of file EicGeoParData.h
References _GEANT_INDEX_BIT_NUM_, _SERVICE_BIT_MASK_, and GetMapPtrViaMapID().
EicGeoMap* EicGeoParData::GetMapPtrViaMapID (unsigned mapId) const inline
Definition at line 282 of file EicGeoParData.h.
View newest version in sPHENIX GitHub at line 282 of file EicGeoParData.h
References mGeantVolumeMaps.
Referenced by EicDetector::ConstructGeometry(), EicCalorimeterDigiHitProducer::ExtraInit(), femc(), GetMapPtrViaHitMultiIndex(), EicDetector::GetNodeMultiIndex(), EicDigiHitProducer::Init(), InitializeLookupTables(), and PlaceG4Volume().
EicGeoMap* EicGeoParData::GetMapPtrViaMapID (unsigned mapId) const inline
Definition at line 286 of file EicGeoParData.h.
View newest version in sPHENIX GitHub at line 286 of file EicGeoParData.h
References mGeantVolumeMaps.
unsigned EicGeoParData::GetMaxVolumeLevelNum () const inline
Definition at line 291 of file EicGeoParData.h.
View newest version in sPHENIX GitHub at line 291 of file EicGeoParData.h
References mMaxVolumeLevelNum.
Referenced by EicDetector::GetNodeMultiIndex().
unsigned EicGeoParData::GetMaxVolumeLevelNum () const inline
Definition at line 295 of file EicGeoParData.h.
View newest version in sPHENIX GitHub at line 295 of file EicGeoParData.h
References mMaxVolumeLevelNum.
const TGeoMedium * EicGeoParData::GetMedium (const char * medium)
Definition at line 315 of file EicGeoParData.cxx.
View newest version in sPHENIX GitHub at line 315 of file EicGeoParData.cxx
References FairGeoBuilder::createMedium(), FairGeoMedia::getMedium(), mFairMedia, mGeobuild, mMediaCache, and mRootGeoManager.
Referenced by aerogel(), b0tracker(), FstGeoParData::ConstructGeometry(), BeamPipeGeoParData::ConstructGeometry(), LqstCell::createCell(), fbst(), femc(), hcal(), ip(), ippt(), lqst(), make_single_tower(), GemGeoParData::PlaceMaterialLayer(), rich(), romanPot_v2(), rp(), tpc(), tracker(), and zdc().
const TGeoMedium* EicGeoParData::GetMedium (const char * medium)
TGeoManager* EicGeoParData::GetRootGeoManager () inline
Definition at line 269 of file EicGeoParData.h.
View newest version in sPHENIX GitHub at line 269 of file EicGeoParData.h
References mRootGeoManager.
TGeoManager* EicGeoParData::GetRootGeoManager () inline
Definition at line 273 of file EicGeoParData.h.
View newest version in sPHENIX GitHub at line 273 of file EicGeoParData.h
References mRootGeoManager.
const std::set<TString>& EicGeoParData::GetStepEnforcedVolumes () const inline
Definition at line 338 of file EicGeoParData.h.
View newest version in sPHENIX GitHub at line 338 of file EicGeoParData.h
References mStepEnforcedVolumes.
Referenced by EicDetector::ConstructGeometry().
const std::set<TString>& EicGeoParData::GetStepEnforcedVolumes () const inline
Definition at line 351 of file EicGeoParData.h.
View newest version in sPHENIX GitHub at line 351 of file EicGeoParData.h
References mStepEnforcedVolumes.
int EicGeoParData::GetSubVersion () const inline
Definition at line 193 of file EicGeoParData.h.
View newest version in sPHENIX GitHub at line 193 of file EicGeoParData.h
References mSubVersion.
Referenced by GetGeometryFileName().
int EicGeoParData::GetSubVersion () const inline
Definition at line 195 of file EicGeoParData.h.
View newest version in sPHENIX GitHub at line 195 of file EicGeoParData.h
References mSubVersion.
TGeoVolume* EicGeoParData::GetTopVolume () const inline
Definition at line 268 of file EicGeoParData.h.
View newest version in sPHENIX GitHub at line 268 of file EicGeoParData.h
References mTopVolume.
Referenced by aerogel(), EicCadWizard::AssembleRootFiles(), b0tracker(), VstGeoParData::ConstructGeometry(), FstGeoParData::ConstructGeometry(), BeamPipeGeoParData::ConstructGeometry(), EicCadWizard::CreateBooleanSolidRootFile(), EicCadWizard::CreateGhostSolidRootFile(), EicCadWizard::CreateStlSolidRootFile(), fbst(), femc(), hcal(), ip(), ippt(), lqst(), rich(), romanPot_v2(), rp(), tpc(), tracker(), and zdc().
TGeoVolume* EicGeoParData::GetTopVolume () const inline
Definition at line 272 of file EicGeoParData.h.
View newest version in sPHENIX GitHub at line 272 of file EicGeoParData.h
References mTopVolume.
const TGeoMatrix* EicGeoParData::GetTopVolumeTransformation () const inline
Definition at line 250 of file EicGeoParData.h.
View newest version in sPHENIX GitHub at line 250 of file EicGeoParData.h
References mTopVolumeTransformation.
const TGeoMatrix* EicGeoParData::GetTopVolumeTransformation () const inline
Definition at line 254 of file EicGeoParData.h.
View newest version in sPHENIX GitHub at line 254 of file EicGeoParData.h
References mTopVolumeTransformation.
EicNamePatternHub<Char_t>* EicGeoParData::GetTransparencyTable () inline
Definition at line 355 of file EicGeoParData.h.
View newest version in sPHENIX GitHub at line 355 of file EicGeoParData.h
References mTransparencyRequests.
Referenced by aerogel(), EicCadWizard::AssembleRootFiles(), AssignG4Colors(), b0tracker(), EicCadWizard::CreateBooleanSolidRootFile(), EicCadWizard::CreateGhostSolidRootFile(), EicCadWizard::CreateStlSolidRootFile(), FinalizeOutput(), ip(), ippt(), lqst(), rich(), rp(), tpc(), tracker(), and zdc().
EicNamePatternHub<Char_t>* EicGeoParData::GetTransparencyTable () inline
Definition at line 368 of file EicGeoParData.h.
View newest version in sPHENIX GitHub at line 368 of file EicGeoParData.h
References mTransparencyRequests.
int EicGeoParData::GetVersion () const inline
Definition at line 192 of file EicGeoParData.h.
View newest version in sPHENIX GitHub at line 192 of file EicGeoParData.h
References mVersion.
Referenced by GetGeometryFileName().
int EicGeoParData::GetVersion () const inline
Definition at line 194 of file EicGeoParData.h.
View newest version in sPHENIX GitHub at line 194 of file EicGeoParData.h
References mVersion.
unsigned EicGeoParData::GetX (ULogicalIndex_t logicalID) const inline
Definition at line 310 of file EicGeoParData.h.
View newest version in sPHENIX GitHub at line 310 of file EicGeoParData.h
References GetLogicalCoordCore(), and IDX.
Referenced by AreNeighbours(), and EicCalorimeterReconstruction::Exec().
unsigned EicGeoParData::GetX (ULogicalIndex_t logicalID) const inline
Definition at line 323 of file EicGeoParData.h.
View newest version in sPHENIX GitHub at line 323 of file EicGeoParData.h
References GetLogicalCoordCore(), and IDX.
unsigned EicGeoParData::GetY (ULogicalIndex_t logicalID) const inline
Definition at line 313 of file EicGeoParData.h.
View newest version in sPHENIX GitHub at line 313 of file EicGeoParData.h
References GetLogicalCoordCore(), and IDY.
Referenced by AreNeighbours(), and EicCalorimeterReconstruction::Exec().
unsigned EicGeoParData::GetY (ULogicalIndex_t logicalID) const inline
Definition at line 326 of file EicGeoParData.h.
View newest version in sPHENIX GitHub at line 326 of file EicGeoParData.h
References GetLogicalCoordCore(), and IDY.
unsigned EicGeoParData::GetZ (ULogicalIndex_t logicalID) const inline
Definition at line 316 of file EicGeoParData.h.
View newest version in sPHENIX GitHub at line 316 of file EicGeoParData.h
References GetLogicalCoordCore(), and IDZ.
Referenced by AreNeighbours(), and EicTrackingDigiHitProducer::HandleHit().
unsigned EicGeoParData::GetZ (ULogicalIndex_t logicalID) const inline
Definition at line 329 of file EicGeoParData.h.
View newest version in sPHENIX GitHub at line 329 of file EicGeoParData.h
References GetLogicalCoordCore(), and IDZ.
int EicGeoParData::ImportMediaFile (const char * fname) static
Definition at line 134 of file EicGeoParData.cxx.
View newest version in sPHENIX GitHub at line 134 of file EicGeoParData.cxx
References in, mEicMedia, printf(), and EicGeoMedia::read().
Referenced by Fun4All_G4_QtDisplay(), Fun4All_G4_Tracking(), and main().
void EicGeoParData::InitializeLookupTables ()
Definition at line 519 of file EicGeoParData.cxx.
View newest version in sPHENIX GitHub at line 519 of file EicGeoParData.cxx
References _LOGICAL_VOLUME_GROUP_COORD_NUM_, buffer, EicGeoMap::GetBaseVolumePath(), GetDim(), EicGeoMap::GetGeantVolumeLevelNum(), EicGeoMap::GetGeantVolumeLevelPtr(), GetLookupTableNode(), EicGeoMap::GetMappingTable(), EicGeoMap::GetMappingTableDim(), GetMapPtrViaMapID(), GeantVolumeLevel::GetMaskedBits(), EicGeoMap::GetSingleSensorContainerVolumeName(), GeantVolumeLevel::GetVolumeName(), LogicalVolumeGroup::mDim3D, mGeantToLogicalLookupTable, mGeantVolumeMaps, LogicalVolumeLookupTableEntry::mGeoMtx, LogicalVolumeLookupTableEntry::mGeoNode, mLogicalVolumeGroups, LogicalVolumeGroup::mLookup, LogicalVolumeGroup::mRealDim, and LogicalVolumeLookupTableEntry::mVolumePath.
Referenced by EicDigiHitProducer::Init(), and EicHtcTask::Init().
void EicGeoParData::InitializeLookupTables ()
bool EicGeoParData::IsBlackHoleVolume (const char * vName) const inline
Definition at line 323 of file EicGeoParData.h.
View newest version in sPHENIX GitHub at line 323 of file EicGeoParData.h
References mBlackHoleVolumes.
Referenced by EicMCApplication::Stepping().
bool EicGeoParData::IsBlackHoleVolume (const char * vName) const inline
Definition at line 336 of file EicGeoParData.h.
View newest version in sPHENIX GitHub at line 336 of file EicGeoParData.h
References mBlackHoleVolumes.
bool EicGeoParData::IsTestGeometry () const inline
Definition at line 190 of file EicGeoParData.h.
View newest version in sPHENIX GitHub at line 190 of file EicGeoParData.h
References mTestGeometryFlag.
Referenced by GetGeometryFileName().
bool EicGeoParData::IsTestGeometry () const inline
Definition at line 192 of file EicGeoParData.h.
View newest version in sPHENIX GitHub at line 192 of file EicGeoParData.h
References mTestGeometryFlag.
bool EicGeoParData::IsWantedParticle (const char * vName, int pdg) const inline
Definition at line 373 of file EicGeoParData.h.
View newest version in sPHENIX GitHub at line 373 of file EicGeoParData.h
References mWantedParticles.
Referenced by EicDetector::ProcessHits().
bool EicGeoParData::IsWantedParticle (const char * vName, int pdg) const inline
Definition at line 386 of file EicGeoParData.h.
View newest version in sPHENIX GitHub at line 386 of file EicGeoParData.h
References mWantedParticles.
void EicGeoParData::PlaceG4Volume (G4LogicalVolume * mother, bool check = false, void * pRot = 0, void * tlate = 0)
Definition at line 185 of file EicGeoParData.cxx.
View newest version in sPHENIX GitHub at line 185 of file EicGeoParData.cxx
References AssignG4Colors(), ConstructGeometry(), EicGeoMap::GetInnermostVolumeName(), GetMapNum(), GetMapPtrViaMapID(), mG4SensitiveVolumes, mG4Volumes, mSensitiveVolumeNames, offset, RestoreGeoManager(), and SwitchGeoManager().
Referenced by BasicDetectorConstruction::Construct(), EicRootVstSubsystem::PlaceG4Volume(), EicRootMuMegasSubsystem::PlaceG4Volume(), and EicRootGemSubsystem::PlaceG4Volume().
void EicGeoParData::Print (const char * option = 0) const virtual
Definition at line 706 of file EicGeoParData.cxx.
View newest version in sPHENIX GitHub at line 706 of file EicGeoParData.cxx
References data, mAuthor, mComment, mSubVersion, mTimeStamp, mVersion, offset, and printf().
Referenced by EicDetector::ConstructGeometry().
virtual void EicGeoParData::Print (const char * option = 0) const virtual
void EicGeoParData::PrintAttachedSourceFile (const char * fileName)
Definition at line 282 of file EicGeoParData.cxx.
View newest version in sPHENIX GitHub at line 282 of file EicGeoParData.cxx
References eicpy.qaplots::file, SourceFile::GetFileName(), mSourceFiles, SourceFile::Print(), and printf().
Referenced by EicDetector::ConstructGeometry().
void EicGeoParData::PrintAttachedSourceFile (const char * fileName)
void EicGeoParData::ResetVars ()
Definition at line 32 of file EicGeoParData.cxx.
View newest version in sPHENIX GitHub at line 32 of file EicGeoParData.cxx
References mAuthor, mColorRequests, mDetName, mFairMedia, mGeobuild, mGeoFace, mGeoLoad, mGeometryType, mMaxVolumeLevelNum, mRootGeoManager, mTestGeometryFlag, mTimeStamp, mTopVolume, mTopVolumeTransformation, mTransparencyRequests, mWrapperVolume, and Undefined.
Referenced by EicGeoParData().
void EicGeoParData::ResetVars ()
void EicGeoParData::RestoreGeoManager (void) private
Definition at line 172 of file EicGeoParData.cxx.
View newest version in sPHENIX GitHub at line 172 of file EicGeoParData.cxx
References mRootGeoManager, mSavedGeoIdentity, and mSavedGeoManager.
Referenced by PlaceG4Volume().
int EicGeoParData::SetCircularCore (unsigned group, unsigned what) private
Definition at line 156 of file EicGeoParData.cxx.
View newest version in sPHENIX GitHub at line 156 of file EicGeoParData.cxx
References mLogicalVolumeGroups.
Referenced by SetCircularX(), SetCircularY(), and SetCircularZ().
int EicGeoParData::SetCircularCore (unsigned group, unsigned what) private
int EicGeoParData::SetCircularX (unsigned group = 0) inline
Definition at line 215 of file EicGeoParData.h.
View newest version in sPHENIX GitHub at line 215 of file EicGeoParData.h
References IDX, and SetCircularCore().
Referenced by BarrelGeoParData::ResetVars().
int EicGeoParData::SetCircularX (unsigned group = 0) inline
Definition at line 219 of file EicGeoParData.h.
View newest version in sPHENIX GitHub at line 219 of file EicGeoParData.h
References IDX, and SetCircularCore().
int EicGeoParData::SetCircularY (unsigned group = 0) inline
Definition at line 216 of file EicGeoParData.h.
View newest version in sPHENIX GitHub at line 216 of file EicGeoParData.h
References IDY, and SetCircularCore().
int EicGeoParData::SetCircularY (unsigned group = 0) inline
Definition at line 220 of file EicGeoParData.h.
View newest version in sPHENIX GitHub at line 220 of file EicGeoParData.h
References IDY, and SetCircularCore().
int EicGeoParData::SetCircularZ (unsigned group = 0) inline
Definition at line 217 of file EicGeoParData.h.
View newest version in sPHENIX GitHub at line 217 of file EicGeoParData.h
References IDZ, and SetCircularCore().
int EicGeoParData::SetCircularZ (unsigned group = 0) inline
Definition at line 221 of file EicGeoParData.h.
View newest version in sPHENIX GitHub at line 221 of file EicGeoParData.h
References IDZ, and SetCircularCore().
void EicGeoParData::SetComment (const char * comment) inline
Definition at line 205 of file EicGeoParData.h.
View newest version in sPHENIX GitHub at line 205 of file EicGeoParData.h
References mComment.
void EicGeoParData::SetComment (const char * comment) inline
Definition at line 209 of file EicGeoParData.h.
View newest version in sPHENIX GitHub at line 209 of file EicGeoParData.h
References mComment.
void EicGeoParData::SetFileName (const char * fileName) inline
Definition at line 200 of file EicGeoParData.h.
View newest version in sPHENIX GitHub at line 200 of file EicGeoParData.h
References mFileName.
Referenced by EicCadWizard::AssembleRootFiles(), b0tracker(), EicCadWizard::CreateBooleanSolidRootFile(), EicCadWizard::CreateGhostSolidRootFile(), EicCadWizard::CreateStlSolidRootFile(), ip(), ippt(), lqst(), rp(), tracker(), and zdc().
void EicGeoParData::SetFileName (const char * fileName) inline
Definition at line 202 of file EicGeoParData.h.
View newest version in sPHENIX GitHub at line 202 of file EicGeoParData.h
References mFileName.
void EicGeoParData::SetFileNameFormat (const char * fileNameFormat) inline
Definition at line 201 of file EicGeoParData.h.
View newest version in sPHENIX GitHub at line 201 of file EicGeoParData.h
References mFileNameFormat.
void EicGeoParData::SetFileNameFormat (const char * fileNameFormat) inline
Definition at line 203 of file EicGeoParData.h.
View newest version in sPHENIX GitHub at line 203 of file EicGeoParData.h
References mFileNameFormat.
void EicGeoParData::SetGeometryType (GeometryType gType) inline
Definition at line 185 of file EicGeoParData.h.
View newest version in sPHENIX GitHub at line 185 of file EicGeoParData.h
References mGeometryType.
Referenced by DefinitionParser(), femc(), hcal(), and tpc().
void EicGeoParData::SetGeometryType (GeometryType gType) inline
Definition at line 187 of file EicGeoParData.h.
View newest version in sPHENIX GitHub at line 187 of file EicGeoParData.h
References mGeometryType.
Int_t EicGeoParData::SetMappingTableEntry (EicGeoMap * map, const unsigned geant[], unsigned group, unsigned logical[])
Definition at line 173 of file EicGeoParData.cxx.
View newest version in sPHENIX GitHub at line 173 of file EicGeoParData.cxx
References _LOGICAL_GROUP_NUM_MAX_, _LOGICAL_XYZ_BIT_NUM_, EicBitMask< T >::GetBitMask(), EicBitMask< T >::GetShift(), LogicalVolumeGroupProjection::mBitMask, mLogicalVolumeGroups, LogicalVolumeGroupProjection::mMaxEntryNum, printf(), EicGeoMap::SetMappingTableEntry(), and value.
Referenced by b0tracker(), VstGeoParData::ConstructGeometry(), femc(), hcal(), ip(), ippt(), lqst(), rich(), romanPot_v2(), rp(), tpc(), tracker(), and zdc().
int EicGeoParData::SetMappingTableEntry (EicGeoMap * map, const unsigned geant[], unsigned group, unsigned logical[])
void EicGeoParData::SetTestGeometryFlag (bool flag = true) inline
Definition at line 189 of file EicGeoParData.h.
View newest version in sPHENIX GitHub at line 189 of file EicGeoParData.h
References mTestGeometryFlag.
Referenced by aerogel(), DefinitionParser(), fbgt(), mumegas(), and tpc().
void EicGeoParData::SetTestGeometryFlag (bool flag = true) inline
Definition at line 191 of file EicGeoParData.h.
View newest version in sPHENIX GitHub at line 191 of file EicGeoParData.h
References mTestGeometryFlag.
void EicGeoParData::SetTGeoGeometryCheckPrecision (double value) inline
Definition at line 499 of file EicGeoParData.h.
View newest version in sPHENIX GitHub at line 499 of file EicGeoParData.h
References mGeometryCheckPrecision.
void EicGeoParData::SetTopVolumeTransformation (TGeoMatrix * transformation) inline
Definition at line 247 of file EicGeoParData.h.
View newest version in sPHENIX GitHub at line 247 of file EicGeoParData.h
References mTopVolumeTransformation.
Referenced by aerogel(), fbgt(), femc(), hcal(), romanPot_v2(), and tracker().
void EicGeoParData::SetTopVolumeTransformation (TGeoMatrix * transformation) inline
Definition at line 251 of file EicGeoParData.h.
View newest version in sPHENIX GitHub at line 251 of file EicGeoParData.h
References mTopVolumeTransformation.
void EicGeoParData::SetTransparency (unsigned value) inline
Definition at line 207 of file EicGeoParData.h.
View newest version in sPHENIX GitHub at line 207 of file EicGeoParData.h
References mTransparency.
Referenced by BasicDetectorConstruction::Construct().
void EicGeoParData::SwitchGeoManager (void) private
Definition at line 152 of file EicGeoParData.cxx.
View newest version in sPHENIX GitHub at line 152 of file EicGeoParData.cxx
References mDetName, mRootGeoManager, mSavedGeoIdentity, mSavedGeoManager, mWrapperVolume, EicDetName::NAME(), and EicDetName::Name().
Referenced by PlaceG4Volume().
void EicGeoParData::TurnTGeoGeometryCheckOff (void) inline
Definition at line 503 of file EicGeoParData.h.
View newest version in sPHENIX GitHub at line 503 of file EicGeoParData.h
References mGeometryCheckPrecision.
Member Data Documentation
TString EicGeoParData::mAuthor private
explicit file name formatting string
Definition at line 389 of file EicGeoParData.h.
View newest version in sPHENIX GitHub at line 389 of file EicGeoParData.h
Referenced by Print(), and ResetVars().
std::set< TString > EicGeoParData::mBlackHoleVolumes private
Definition at line 437 of file EicGeoParData.h.
View newest version in sPHENIX GitHub at line 437 of file EicGeoParData.h
Referenced by AddBlackHoleVolume(), GetBlackHoleVolumes(), and IsBlackHoleVolume().
EicNamePatternHub< Color_t > * EicGeoParData::mColorRequests private
Definition at line 472 of file EicGeoParData.h.
View newest version in sPHENIX GitHub at line 472 of file EicGeoParData.h
Referenced by GetColorTable(), and ResetVars().
TString EicGeoParData::mComment private
Definition at line 390 of file EicGeoParData.h.
View newest version in sPHENIX GitHub at line 390 of file EicGeoParData.h
Referenced by Print(), and SetComment().
EicDetName * EicGeoParData::mDetName protected
respective lookup table (for efficiency)
Definition at line 450 of file EicGeoParData.h.
View newest version in sPHENIX GitHub at line 450 of file EicGeoParData.h
Referenced by FstGeoParData::ConstructGeometry(), BeamPipeGeoParData::ConstructGeometry(), EicGeoParData(), FinalizeOutput(), GetDetName(), GetGeometryFileName(), ResetVars(), and SwitchGeoManager().
EicGeoMedia * EicGeoParData::mEicMedia = 0 static private
Definition at line 480 of file EicGeoParData.h.
View newest version in sPHENIX GitHub at line 480 of file EicGeoParData.h
Referenced by ImportMediaFile().
FairGeoMedia* EicGeoParData::mFairMedia private
Definition at line 462 of file EicGeoParData.h.
View newest version in sPHENIX GitHub at line 462 of file EicGeoParData.h
Referenced by EicGeoParData(), GetMedium(), and ResetVars().
TString EicGeoParData::mFileName private
Definition at line 386 of file EicGeoParData.h.
View newest version in sPHENIX GitHub at line 386 of file EicGeoParData.h
Referenced by GetGeometryFileName(), and SetFileName().
TString EicGeoParData::mFileNameFormat private
excplicit file name
Definition at line 387 of file EicGeoParData.h.
View newest version in sPHENIX GitHub at line 387 of file EicGeoParData.h
Referenced by GetGeometryFileName(), and SetFileNameFormat().
std::map<G4VPhysicalVolume*, unsigned> EicGeoParData::mG4SensitiveVolumes private
Definition at line 494 of file EicGeoParData.h.
View newest version in sPHENIX GitHub at line 494 of file EicGeoParData.h
Referenced by AssignG4Colors(), GetG4SensitiveVolumes(), and PlaceG4Volume().
std::vector<G4VPhysicalVolume*> EicGeoParData::mG4Volumes private
Definition at line 493 of file EicGeoParData.h.
View newest version in sPHENIX GitHub at line 493 of file EicGeoParData.h
Referenced by AssignG4Colors(), GetG4Volumes(), and PlaceG4Volume().
std::map< const TGeoNode *, LogicalVolumeLookupTableEntry * > EicGeoParData::mGeantToLogicalLookupTable private
Definition at line 469 of file EicGeoParData.h.
View newest version in sPHENIX GitHub at line 469 of file EicGeoParData.h
Referenced by GetLookupTableNode(), and InitializeLookupTables().
std::vector< EicGeoMap * > EicGeoParData::mGeantVolumeMaps private
Definition at line 400 of file EicGeoParData.h.
View newest version in sPHENIX GitHub at line 400 of file EicGeoParData.h
Referenced by CalculateMappingTableSignatures(), CreateNewMap(), GeantMultiToLogicalIndex(), GetMapNum(), GetMapPtrViaMapID(), and InitializeLookupTables().
FairGeoBuilder* EicGeoParData::mGeobuild private
Definition at line 463 of file EicGeoParData.h.
View newest version in sPHENIX GitHub at line 463 of file EicGeoParData.h
Referenced by EicGeoParData(), GetMedium(), and ResetVars().
FairGeoInterface* EicGeoParData::mGeoFace private
Definition at line 460 of file EicGeoParData.h.
View newest version in sPHENIX GitHub at line 460 of file EicGeoParData.h
Referenced by EicGeoParData(), and ResetVars().
FairGeoLoader* EicGeoParData::mGeoLoad private
Definition at line 459 of file EicGeoParData.h.
View newest version in sPHENIX GitHub at line 459 of file EicGeoParData.h
Referenced by EicGeoParData(), and ResetVars().
double EicGeoParData::mGeometryCheckPrecision private
Definition at line 496 of file EicGeoParData.h.
View newest version in sPHENIX GitHub at line 496 of file EicGeoParData.h
Referenced by SetTGeoGeometryCheckPrecision(), and TurnTGeoGeometryCheckOff().
GeometryType EicGeoParData::mGeometryType protected
Definition at line 376 of file EicGeoParData.h.
View newest version in sPHENIX GitHub at line 376 of file EicGeoParData.h
Referenced by GetGeometryType(), MapsGeoParData::MapsGeoParData(), ResetVars(), and SetGeometryType().
std::vector< LogicalVolumeGroup * > EicGeoParData::mLogicalVolumeGroups private
max number of volume levels on any of the maps
Definition at line 411 of file EicGeoParData.h.
View newest version in sPHENIX GitHub at line 411 of file EicGeoParData.h
Referenced by AddLogicalVolumeGroup(), GetCircularCore(), GetDimCore(), GetLogicalCoordCore(), GetLookupTableNode(), InitializeLookupTables(), SetCircularCore(), and SetMappingTableEntry().
UInt_t EicGeoParData::mMaxVolumeLevelNum private
Definition at line 404 of file EicGeoParData.h.
View newest version in sPHENIX GitHub at line 404 of file EicGeoParData.h
Referenced by CalculateMappingTableSignatures(), GetMaxVolumeLevelNum(), and ResetVars().
std::set< const char * > EicGeoParData::mMediaCache private
Definition at line 467 of file EicGeoParData.h.
View newest version in sPHENIX GitHub at line 467 of file EicGeoParData.h
Referenced by GetMedium().
TGeoManager * EicGeoParData::mRootGeoManager private
Definition at line 455 of file EicGeoParData.h.
View newest version in sPHENIX GitHub at line 455 of file EicGeoParData.h
Referenced by EicGeoParData(), FinalizeOutput(), GetMedium(), GetRootGeoManager(), ResetVars(), RestoreGeoManager(), and SwitchGeoManager().
TGeoIdentity* EicGeoParData::mSavedGeoIdentity private
Definition at line 476 of file EicGeoParData.h.
View newest version in sPHENIX GitHub at line 476 of file EicGeoParData.h
Referenced by RestoreGeoManager(), and SwitchGeoManager().
TGeoManager* EicGeoParData::mSavedGeoManager private
Definition at line 475 of file EicGeoParData.h.
View newest version in sPHENIX GitHub at line 475 of file EicGeoParData.h
Referenced by RestoreGeoManager(), and SwitchGeoManager().
std::map<TString, unsigned> EicGeoParData::mSensitiveVolumeNames private
Definition at line 492 of file EicGeoParData.h.
View newest version in sPHENIX GitHub at line 492 of file EicGeoParData.h
Referenced by AssignG4Colors(), and PlaceG4Volume().
std::vector< SourceFile * > EicGeoParData::mSourceFiles private
Definition at line 392 of file EicGeoParData.h.
View newest version in sPHENIX GitHub at line 392 of file EicGeoParData.h
Referenced by AttachSourceFile(), and PrintAttachedSourceFile().
std::set< TString > EicGeoParData::mStepEnforcedVolumes private
Definition at line 445 of file EicGeoParData.h.
View newest version in sPHENIX GitHub at line 445 of file EicGeoParData.h
Referenced by AddStepEnforcedVolume(), and GetStepEnforcedVolumes().
std::map< int, double > EicGeoParData::mStepEnforcedVolumesLookup private
Definition at line 446 of file EicGeoParData.h.
View newest version in sPHENIX GitHub at line 446 of file EicGeoParData.h
Referenced by AddStepEnforcedVolumeLookupEntry(), and GetEnforcedStep().
Int_t EicGeoParData::mSubVersion private
Definition at line 384 of file EicGeoParData.h.
View newest version in sPHENIX GitHub at line 384 of file EicGeoParData.h
Referenced by GetSubVersion(), and Print().
Bool_t EicGeoParData::mTestGeometryFlag protected
Definition at line 380 of file EicGeoParData.h.
View newest version in sPHENIX GitHub at line 380 of file EicGeoParData.h
Referenced by IsTestGeometry(), ResetVars(), and SetTestGeometryFlag().
TTimeStamp EicGeoParData::mTimeStamp private
Definition at line 394 of file EicGeoParData.h.
View newest version in sPHENIX GitHub at line 394 of file EicGeoParData.h
Referenced by Print(), and ResetVars().
TGeoVolume * EicGeoParData::mTopVolume private
Definition at line 457 of file EicGeoParData.h.
View newest version in sPHENIX GitHub at line 457 of file EicGeoParData.h
Referenced by EicGeoParData(), FinalizeOutput(), GetTopVolume(), and ResetVars().
TGeoMatrix * EicGeoParData::mTopVolumeTransformation private
Definition at line 397 of file EicGeoParData.h.
View newest version in sPHENIX GitHub at line 397 of file EicGeoParData.h
Referenced by FinalizeOutput(), GetTopVolumeTransformation(), ResetVars(), and SetTopVolumeTransformation().
unsigned char EicGeoParData::mTransparency protected
Definition at line 466 of file EicGeoParData.h.
View newest version in sPHENIX GitHub at line 466 of file EicGeoParData.h
Referenced by SetTransparency().
EicNamePatternHub< Char_t > * EicGeoParData::mTransparencyRequests private
Definition at line 473 of file EicGeoParData.h.
View newest version in sPHENIX GitHub at line 473 of file EicGeoParData.h
Referenced by GetTransparencyTable(), and ResetVars().
Int_t EicGeoParData::mVersion private
Definition at line 383 of file EicGeoParData.h.
View newest version in sPHENIX GitHub at line 383 of file EicGeoParData.h
Referenced by GetVersion(), and Print().
std::set< std::pair< TString, Int_t > > EicGeoParData::mWantedParticles private
Definition at line 439 of file EicGeoParData.h.
View newest version in sPHENIX GitHub at line 439 of file EicGeoParData.h
Referenced by AddWantedParticle(), and IsWantedParticle().
TGeoVolume * EicGeoParData::mWrapperVolume private
Definition at line 456 of file EicGeoParData.h.
View newest version in sPHENIX GitHub at line 456 of file EicGeoParData.h
Referenced by EicGeoParData(), FinalizeOutput(), ResetVars(), and SwitchGeoManager().
The documentation for this class was generated from the following files:
EicRoot/blob/master/eic/base/EicGeoParData.h
EicToyModel/blob/master/include/EicGeoParData.h
EicRoot/blob/master/eic/base/EicGeoParData.cxx
EicToyModel/blob/master/source/eicroot/EicGeoParData.cxx