EIC Software: PHG4StepStatusDecode Namespace Reference
PHG4StepStatusDecode Namespace Reference
Functions
std::string GetStepStatus (const int istatus)
Function Documentation
string PHG4StepStatusDecode::GetStepStatus (const int istatus)
Definition at line 13 of file PHG4StepStatusDecode.cc.
View newest version in sPHENIX GitHub at line 13 of file PHG4StepStatusDecode.cc
References stepstatus.
Referenced by PHG4TpcSteppingAction::UserSteppingAction(), G4Example01SteppingAction::UserSteppingAction(), G4JLeicBeamLineMagnetSteppingAction::UserSteppingAction(), G4JLeicDIRCSteppingAction::UserSteppingAction(), G4JLeicVTXSteppingAction::UserSteppingAction(), PHG4PSTOFSteppingAction::UserSteppingAction(), G4LBLVtxSteppingAction::UserSteppingAction(), G4Example03SteppingAction::UserSteppingAction(), G4Example02SteppingAction::UserSteppingAction(), PHG4BlockSteppingAction::UserSteppingAction(), AllSi_Al_support_SteppingAction::UserSteppingAction(), BeastMagnetSteppingAction::UserSteppingAction(), PHG4EPDSteppingAction::UserSteppingAction(), PHG4CylinderStripSteppingAction::UserSteppingAction(), GdmlImportDetectorSteppingAction::UserSteppingAction(), PHG4OuterHcalSteppingAction::UserSteppingAction(), AllSiliconTrackerSteppingAction::UserSteppingAction(), EicFRichSteppingAction::UserSteppingAction(), PHG4InnerHcalSteppingAction::UserSteppingAction(), BeamLineMagnetSteppingAction::UserSteppingAction(), EICG4dRICHSteppingAction::UserSteppingAction(), PHG4BbcSteppingAction::UserSteppingAction(), EICG4ZDCSteppingAction::UserSteppingAction(), PHG4TpcEndCapSteppingAction::UserSteppingAction(), PHG4CylinderSteppingAction::UserSteppingAction(), EICG4RPSteppingAction::UserSteppingAction(), G4EicDircSteppingAction::UserSteppingAction(), PHG4MicromegasSteppingAction::UserSteppingAction(), EICG4B0ECALSteppingAction::UserSteppingAction(), EICG4BwdSteppingAction::UserSteppingAction(), EICG4B0SteppingAction::UserSteppingAction(), and EICG4LumiSteppingAction::UserSteppingAction().