EIC Software: PEPSI/blob/master/pepsiMaineRHIC_radcorr.f File Reference
pepsiMaineRHIC_radcorr.f File Reference
Functions/Subroutines
program pepsimainerhic
Function/Subroutine Documentation
program pepsimainerhic ()
Definition at line 1 of file pepsiMaineRHIC_radcorr.f.
View newest version in sPHENIX GitHub at line 1 of file pepsiMaineRHIC_radcorr.f
References dfe::Variable::as(), c, FairMesh::calculate(), nlohmann::basic_json::count(), PHTFileServer::SafeTFile::counter(), d, Acts::AtlasStepper< bfield_t >::direction(), dx, Acts::GeometryHierarchyMap< value_t >::end(), ActsExamples::HepMC3Particle::energy(), eps, TrackEvaluationContainerv1::events(), f2(), false, for(), ActsFatras::Barcode::generation(), genevent(), in, info, init(), Acts::Navigator::initialize(), Acts::FiniteStateMachine< Derived, States >::is(), k, lepto(), linit(), Acts::SurfaceArray::ISurfaceGridLookup::lookup(), max, min, mkasym(), mkf2(), mkr(), name, nlohmann::detail::dtoa_impl::diyfp::normalize(), Acts::Logging::TimedOutputDecorator::now(), of, eicpy.qaplots.EventHists::output(), p, ActsFatras::LandauDistribution::param(), particle, print(), Acts::ConeBounds::r(), radgen(), radgen_event(), radgen_init(), nBodyPhaseSpaceGen::random(), Acts::Extent::range(), rlu(), rndmq(), s, t1, t2, this, genfit::GFRavePropagator::to(), true, v, Acts::AssertionFailureException::what(), x, xmax, xmin, y, ymax, and ymin.