EIC Software: FairDbConfigurable Class Reference
FairDbConfigurable Class Reference abstract
#include <EicRoot/blob/master/dbase/dbInterface/FairDbConfigurable.h>
Public Member Functions
FairDbConfigurable ()
virtual ~FairDbConfigurable ()
virtual void Config ()=0
virtual const FairRegistry & DefaultConfig () const
FairRegistry & GetConfig ()
const FairRegistry & GetConfig () const
int Update ()
void Set (FairDbConfDialog *d=0)
void Set (const char *s)
Protected Member Functions
virtual void CommitDefaultConfig (const FairRegistry &r)
Private Attributes
FairRegistry fDefConfig
FairRegistry fConfig
Detailed Description
Definition at line 15 of file FairDbConfigurable.h.
View newest version in sPHENIX GitHub at line 15 of file FairDbConfigurable.h
Constructor & Destructor Documentation
FairDbConfigurable::FairDbConfigurable ()
FairDbConfigurable::~FairDbConfigurable () virtual
Definition at line 14 of file FairDbConfigurable.cxx.
View newest version in sPHENIX GitHub at line 14 of file FairDbConfigurable.cxx
Member Function Documentation
void FairDbConfigurable::CommitDefaultConfig (const FairRegistry & r) protected virtual
====================================================================== Subclass must call this before the Configurable can have
meaningful entries
Definition at line 18 of file FairDbConfigurable.cxx.
View newest version in sPHENIX GitHub at line 18 of file FairDbConfigurable.cxx
References fDefConfig.
virtual void FairDbConfigurable::Config () pure virtual
Implemented in FairDbTableProxyRegistry.
Referenced by Update().
const FairRegistry & FairDbConfigurable::DefaultConfig () const virtual
====================================================================== Eventually this might go in the database and load the
configuration. This would take a name or something.
Definition at line 29 of file FairDbConfigurable.cxx.
View newest version in sPHENIX GitHub at line 29 of file FairDbConfigurable.cxx
References fDefConfig.
Referenced by Set().
FairRegistry & FairDbConfigurable::GetConfig ()
====================================================================== Returns the configuration FairRegistry, this is non-const as the user
is user is free to modify
Definition at line 38 of file FairDbConfigurable.cxx.
View newest version in sPHENIX GitHub at line 38 of file FairDbConfigurable.cxx
References fConfig.
Referenced by FairDbTableProxyRegistry::Config(), Set(), and FairDbTableProxyRegistry::~FairDbTableProxyRegistry().
const FairRegistry & FairDbConfigurable::GetConfig () const
====================================================================== Returns the configuration FairRegistry. This const version denies the user any freedom to modify it, but does mean that a
configurable object can use it in a const method.
Definition at line 47 of file FairDbConfigurable.cxx.
View newest version in sPHENIX GitHub at line 47 of file FairDbConfigurable.cxx
References fConfig.
void FairDbConfigurable::Set (FairDbConfDialog * d = 0)
Definition at line 74 of file FairDbConfigurable.cxx.
View newest version in sPHENIX GitHub at line 74 of file FairDbConfigurable.cxx
References d, DefaultConfig(), GetConfig(), FairRegistry::LockValues(), FairRegistry::Merge(), FairDbConfDialog::Query(), FairDbConfDialog::SetCurrent(), FairDbConfDialog::SetDefault(), and FairRegistry::UnLockValues().
Referenced by FairDbTableProxyRegistry::SetConfigFromEnvironment().
void FairDbConfigurable::Set (const char * s)
====================================================================== Update the configuration given a text string s. Format:
"key1=true, key2=10, key3=11.1, key4='A string'"
Definition at line 103 of file FairDbConfigurable.cxx.
View newest version in sPHENIX GitHub at line 103 of file FairDbConfigurable.cxx
References GetConfig(), FairRegistry::LockValues(), FairRegistry::Merge(), FairDbConf::StringToRegistry(), and FairRegistry::UnLockValues().
int FairDbConfigurable::Update ()
====================================================================== Update the class's state given the current configuration. If there is nothing to do just return w/o taking any action. Return's 0 if
no action was taken, >0 if the object was reconfigured.
Definition at line 59 of file FairDbConfigurable.cxx.
View newest version in sPHENIX GitHub at line 59 of file FairDbConfigurable.cxx
References Config(), fConfig, FairRegistry::IsDirty(), and FairRegistry::SetDirty().
Referenced by FairDbTableProxyRegistry::SetConfigFromEnvironment().
Member Data Documentation
FairRegistry FairDbConfigurable::fConfig private
Definition at line 45 of file FairDbConfigurable.h.
View newest version in sPHENIX GitHub at line 45 of file FairDbConfigurable.h
Referenced by GetConfig(), and Update().
FairRegistry FairDbConfigurable::fDefConfig private
Definition at line 45 of file FairDbConfigurable.h.
View newest version in sPHENIX GitHub at line 45 of file FairDbConfigurable.h
Referenced by CommitDefaultConfig(), and DefaultConfig().
The documentation for this class was generated from the following files:
EicRoot/blob/master/dbase/dbInterface/FairDbConfigurable.h
EicRoot/blob/master/dbase/dbInterface/FairDbConfigurable.cxx