EIC Software: TpcSpaceChargeCorrection Class Reference
TpcSpaceChargeCorrection Class Reference
#include <fun4all_coresoftware/blob/master/offline/packages/tpc/TpcSpaceChargeCorrection.h>
Public Types
enum CoordMask { COORD_PHI = 1<<0, COORD_R = 1<<1, COORD_Z = 1<<2 }
Public Member Functions
TpcSpaceChargeCorrection (const std::string &="TpcSpaceChargeCorrection")
constructor
virtual int InitRun (PHCompositeNode *)
global initialization
virtual int process_event (PHCompositeNode *)
event processing
void set_distortion_filename (const std::string &value)
distortion filename
void set_coordinates (unsigned int value)
Public Member Functions inherited from SubsysReco
virtual ~SubsysReco ()
virtual int End (PHCompositeNode *)
Called at the end of all processing.
virtual int EndRun (const int)
Called at the end of each run.
virtual int Init (PHCompositeNode *)
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
virtual void Print (const std::string &what="ALL") const
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Private Member Functions
int load_nodes (PHCompositeNode *)
load nodes
void transform_clusters ()
transform clusters
void transform_cluster (TrkrCluster *)
transform clusters
Private Attributes
TrkrClusterContainer * m_cluster_map = nullptr
cluster container
std::string m_distortion_filename
space charge correction file name
TFile * m_distortion_tfile = nullptr
bool m_fullzrange = true
true if the maps contain the full z range assume it only contains positive z otherwise
unsigned int m_coordinates = COORD_PHI|COORD_R|COORD_Z
space charge distortion histograms
TH3 * m_hDRint = nullptr
TH3 * m_hDPint = nullptr
TH3 * m_hDZint = nullptr
Additional Inherited Members
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Detailed Description
Definition at line 14 of file TpcSpaceChargeCorrection.h.
View newest version in sPHENIX GitHub at line 14 of file TpcSpaceChargeCorrection.h
Member Enumeration Documentation
enum TpcSpaceChargeCorrection::CoordMask
Enumerator:
COORD_PHI
COORD_R
COORD_Z
Definition at line 31 of file TpcSpaceChargeCorrection.h.
View newest version in sPHENIX GitHub at line 31 of file TpcSpaceChargeCorrection.h
Constructor & Destructor Documentation
TpcSpaceChargeCorrection::TpcSpaceChargeCorrection (const std::string & name = "TpcSpaceChargeCorrection")
constructor
Definition at line 22 of file TpcSpaceChargeCorrection.cc.
View newest version in sPHENIX GitHub at line 22 of file TpcSpaceChargeCorrection.cc
Member Function Documentation
int TpcSpaceChargeCorrection::InitRun (PHCompositeNode *) virtual
global initialization
Reimplemented from SubsysReco.
Definition at line 27 of file TpcSpaceChargeCorrection.cc.
View newest version in sPHENIX GitHub at line 27 of file TpcSpaceChargeCorrection.cc
References Fun4AllReturnCodes::EVENT_OK, exit(), m_coordinates, m_distortion_filename, m_distortion_tfile, m_fullzrange, m_hDPint, m_hDRint, and m_hDZint.
int TpcSpaceChargeCorrection::load_nodes (PHCompositeNode * topNode) private
load nodes
Definition at line 69 of file TpcSpaceChargeCorrection.cc.
View newest version in sPHENIX GitHub at line 69 of file TpcSpaceChargeCorrection.cc
References Fun4AllReturnCodes::EVENT_OK, and m_cluster_map.
Referenced by process_event().
int TpcSpaceChargeCorrection::process_event (PHCompositeNode * topNode) virtual
event processing
Reimplemented from SubsysReco.
Definition at line 58 of file TpcSpaceChargeCorrection.cc.
View newest version in sPHENIX GitHub at line 58 of file TpcSpaceChargeCorrection.cc
References Fun4AllReturnCodes::EVENT_OK, load_nodes(), analysis::res, and transform_clusters().
void TpcSpaceChargeCorrection::set_coordinates (unsigned int value) inline
Definition at line 39 of file TpcSpaceChargeCorrection.h.
View newest version in sPHENIX GitHub at line 39 of file TpcSpaceChargeCorrection.h
References m_coordinates, and value.
void TpcSpaceChargeCorrection::set_distortion_filename (const std::string & value) inline
distortion filename
Definition at line 28 of file TpcSpaceChargeCorrection.h.
View newest version in sPHENIX GitHub at line 28 of file TpcSpaceChargeCorrection.h
References m_distortion_filename, and value.
Referenced by TPC_Clustering().
void TpcSpaceChargeCorrection::transform_cluster (TrkrCluster * cluster) private
transform clusters
Definition at line 95 of file TpcSpaceChargeCorrection.cc.
View newest version in sPHENIX GitHub at line 95 of file TpcSpaceChargeCorrection.cc
References kdfinder::abs(), COORD_PHI, COORD_R, COORD_Z, cos(), TrkrCluster::getX(), TrkrCluster::getY(), TrkrCluster::getZ(), m_coordinates, m_fullzrange, m_hDPint, m_hDRint, m_hDZint, M_PI, phi, r, TrkrCluster::setX(), TrkrCluster::setY(), TrkrCluster::setZ(), square(), and z.
Referenced by transform_clusters().
void TpcSpaceChargeCorrection::transform_clusters () private
transform clusters
Definition at line 77 of file TpcSpaceChargeCorrection.cc.
View newest version in sPHENIX GitHub at line 77 of file TpcSpaceChargeCorrection.cc
References TrkrClusterContainer::getClusters(), TrkrDefs::getTrkrId(), m_cluster_map, TrkrDefs::tpcId, and transform_cluster().
Referenced by process_event().
Member Data Documentation
TrkrClusterContainer* TpcSpaceChargeCorrection::m_cluster_map = nullptr private
cluster container
Definition at line 54 of file TpcSpaceChargeCorrection.h.
View newest version in sPHENIX GitHub at line 54 of file TpcSpaceChargeCorrection.h
Referenced by load_nodes(), and transform_clusters().
unsigned int TpcSpaceChargeCorrection::m_coordinates = COORD_PHI|COORD_R|COORD_Z private
Definition at line 74 of file TpcSpaceChargeCorrection.h.
View newest version in sPHENIX GitHub at line 74 of file TpcSpaceChargeCorrection.h
Referenced by InitRun(), set_coordinates(), and transform_cluster().
std::string TpcSpaceChargeCorrection::m_distortion_filename private
space charge correction file name
Definition at line 57 of file TpcSpaceChargeCorrection.h.
View newest version in sPHENIX GitHub at line 57 of file TpcSpaceChargeCorrection.h
Referenced by InitRun(), and set_distortion_filename().
TFile* TpcSpaceChargeCorrection::m_distortion_tfile = nullptr private
Definition at line 58 of file TpcSpaceChargeCorrection.h.
View newest version in sPHENIX GitHub at line 58 of file TpcSpaceChargeCorrection.h
Referenced by InitRun().
bool TpcSpaceChargeCorrection::m_fullzrange = true private
true if the maps contain the full z range assume it only contains positive z otherwise
Definition at line 71 of file TpcSpaceChargeCorrection.h.
View newest version in sPHENIX GitHub at line 71 of file TpcSpaceChargeCorrection.h
Referenced by InitRun(), and transform_cluster().
TH3* TpcSpaceChargeCorrection::m_hDPint = nullptr private
Definition at line 63 of file TpcSpaceChargeCorrection.h.
View newest version in sPHENIX GitHub at line 63 of file TpcSpaceChargeCorrection.h
Referenced by InitRun(), and transform_cluster().
TH3* TpcSpaceChargeCorrection::m_hDRint = nullptr private
Definition at line 62 of file TpcSpaceChargeCorrection.h.
View newest version in sPHENIX GitHub at line 62 of file TpcSpaceChargeCorrection.h
Referenced by InitRun(), and transform_cluster().
TH3* TpcSpaceChargeCorrection::m_hDZint = nullptr private
Definition at line 64 of file TpcSpaceChargeCorrection.h.
View newest version in sPHENIX GitHub at line 64 of file TpcSpaceChargeCorrection.h
Referenced by InitRun(), and transform_cluster().
The documentation for this class was generated from the following files:
fun4all_coresoftware/blob/master/offline/packages/tpc/TpcSpaceChargeCorrection.h
fun4all_coresoftware/blob/master/offline/packages/tpc/TpcSpaceChargeCorrection.cc