EIC Software: G4DIRCTree Class Reference
G4DIRCTree Class Reference
#include <fun4all_eicdetectors/blob/master/simulation/g4simulation/g4eicdirc/G4DIRCTree.h>
Public Member Functions
G4DIRCTree (const std::string &name="G4DIRCTree", const std::string &filename="G4DIRCTree.root")
constructor
~G4DIRCTree () override
destructor
int Init (PHCompositeNode *) override
full initialization
int process_event (PHCompositeNode *) override
event processing method
int process_hit (PHG4HitContainer *hits, const std::string &dName, int detid, int &nhits)
hit processing method
int End (PHCompositeNode *) override
end of run method
void AddNode (const std::string &name, const int detid=0)
Public Member Functions inherited from SubsysReco
~SubsysReco () override
virtual int EndRun (const int)
Called at the end of each run.
virtual int InitRun (PHCompositeNode *)
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
void Print (const std::string &="ALL") const override
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Public Attributes
int evt_num = 0
Protected Attributes
int nblocks
std::string _filename
std::set< std::string > _node_postfix
std::map< std::string, int > _detid
TTree * g4tree
G4EventTree mG4EvtTree
TFile * outfile
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = INT_MAX - 10
}
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Detailed Description
Definition at line 19 of file G4DIRCTree.h.
View newest version in sPHENIX GitHub at line 19 of file G4DIRCTree.h
Constructor & Destructor Documentation
G4DIRCTree::G4DIRCTree (const std::string & name = "G4DIRCTree", const std::string & filename = "G4DIRCTree.root")
constructor
Definition at line 23 of file G4DIRCTree.cc.
View newest version in sPHENIX GitHub at line 23 of file G4DIRCTree.cc
G4DIRCTree::~G4DIRCTree () inline override
destructor
Definition at line 26 of file G4DIRCTree.h.
View newest version in sPHENIX GitHub at line 26 of file G4DIRCTree.h
Member Function Documentation
void G4DIRCTree::AddNode (const std::string & name, const int detid = 0)
Definition at line 149 of file G4DIRCTree.cc.
View newest version in sPHENIX GitHub at line 149 of file G4DIRCTree.cc
References _detid, _node_postfix, and name.
int G4DIRCTree::End (PHCompositeNode * topNode) override virtual
end of run method
Reimplemented from SubsysReco.
Definition at line 139 of file G4DIRCTree.cc.
View newest version in sPHENIX GitHub at line 139 of file G4DIRCTree.cc
References g4tree, and outfile.
int G4DIRCTree::Init (PHCompositeNode *) override virtual
full initialization
Event level
Hit level
Reimplemented from SubsysReco.
Definition at line 32 of file G4DIRCTree.cc.
View newest version in sPHENIX GitHub at line 32 of file G4DIRCTree.cc
References _filename, G4EventTree::detid, G4EventTree::edep, g4tree, G4EventTree::hit_digiPos, G4EventTree::hit_globalPos, G4EventTree::hit_localPos, G4EventTree::hit_mom, G4EventTree::hit_pathId, G4EventTree::hit_pos, G4EventTree::hitid, G4EventTree::lead_time, G4EventTree::mcp_id, mG4EvtTree, G4EventTree::momentum, G4EventTree::nhits, G4EventTree::nrefl, outfile, G4EventTree::phi, G4EventTree::pid, G4EventTree::pixel_id, G4EventTree::px, G4EventTree::py, G4EventTree::pz, G4EventTree::theta, G4EventTree::trkid, G4EventTree::wavelength, G4EventTree::x0, G4EventTree::x1, G4EventTree::y0, G4EventTree::y1, G4EventTree::z0, and G4EventTree::z1.
int G4DIRCTree::process_event (PHCompositeNode * topNode) override virtual
event processing method
Reimplemented from SubsysReco.
Definition at line 83 of file G4DIRCTree.cc.
View newest version in sPHENIX GitHub at line 83 of file G4DIRCTree.cc
References _detid, _node_postfix, evt_num, g4tree, PHG4TruthInfoContainer::GetPrimaryParticleRange(), mG4EvtTree, G4EventTree::momentum, G4EventTree::nhits, p, G4EventTree::phi, phi, G4EventTree::pid, pid, process_hit(), G4EventTree::px, G4EventTree::py, G4EventTree::pz, G4EventTree::theta, and theta().
int G4DIRCTree::process_hit (PHG4HitContainer * hits, const std::string & dName, int detid, int & nhits)
hit processing method
Definition at line 156 of file G4DIRCTree.cc.
View newest version in sPHENIX GitHub at line 156 of file G4DIRCTree.cc
References G4EventTree::detid, G4EventTree::edep, PHG4Hitv1::get_edep(), PHG4Hitv1::get_hit_id(), PHG4Hitv1::get_trkid(), PHG4Hitv1::get_x(), PHG4Hitv1::get_y(), PHG4Hitv1::get_z(), PrtHit::GetDigiPos(), PrtHit::GetGlobalPos(), PHG4HitContainer::getHits(), PrtHit::GetLeadTime(), PrtHit::GetLocalPos(), PrtHit::GetMcpId(), PrtHit::GetMomentum(), PrtHit::GetNreflectionsInPrizm(), PrtHit::GetPathInPrizm(), PrtHit::GetPixelId(), PrtHit::GetPosition(), PrtHit::GetTotTime(), G4EventTree::hit_digiPos, G4EventTree::hit_globalPos, G4EventTree::hit_localPos, G4EventTree::hit_mom, G4EventTree::hit_pathId, G4EventTree::hit_pos, G4EventTree::hitid, G4EventTree::lead_time, G4EventTree::mcp_id, mG4EvtTree, G4EventTree::nrefl, G4EventTree::pixel_id, G4EventTree::trkid, G4EventTree::wavelength, G4EventTree::x0, G4EventTree::x1, G4EventTree::y0, G4EventTree::y1, G4EventTree::z0, and G4EventTree::z1.
Referenced by process_event().
Member Data Documentation
std::map<std::string, int> G4DIRCTree::_detid protected
Definition at line 48 of file G4DIRCTree.h.
View newest version in sPHENIX GitHub at line 48 of file G4DIRCTree.h
Referenced by AddNode(), and process_event().
std::string G4DIRCTree::_filename protected
Definition at line 46 of file G4DIRCTree.h.
View newest version in sPHENIX GitHub at line 46 of file G4DIRCTree.h
Referenced by Init().
std::set<std::string> G4DIRCTree::_node_postfix protected
Definition at line 47 of file G4DIRCTree.h.
View newest version in sPHENIX GitHub at line 47 of file G4DIRCTree.h
Referenced by AddNode(), and process_event().
int G4DIRCTree::evt_num = 0
Definition at line 41 of file G4DIRCTree.h.
View newest version in sPHENIX GitHub at line 41 of file G4DIRCTree.h
Referenced by process_event().
TTree* G4DIRCTree::g4tree protected
Definition at line 50 of file G4DIRCTree.h.
View newest version in sPHENIX GitHub at line 50 of file G4DIRCTree.h
Referenced by End(), Init(), and process_event().
G4EventTree G4DIRCTree::mG4EvtTree protected
Definition at line 51 of file G4DIRCTree.h.
View newest version in sPHENIX GitHub at line 51 of file G4DIRCTree.h
Referenced by Init(), process_event(), and process_hit().
int G4DIRCTree::nblocks protected
Definition at line 44 of file G4DIRCTree.h.
View newest version in sPHENIX GitHub at line 44 of file G4DIRCTree.h
TFile* G4DIRCTree::outfile protected
Definition at line 52 of file G4DIRCTree.h.
View newest version in sPHENIX GitHub at line 52 of file G4DIRCTree.h
Referenced by End(), and Init().
The documentation for this class was generated from the following files:
fun4all_eicdetectors/blob/master/simulation/g4simulation/g4eicdirc/G4DIRCTree.h
fun4all_eicdetectors/blob/master/simulation/g4simulation/g4eicdirc/G4DIRCTree.cc