EIC Software: FairMCTracks Class Reference
FairMCTracks Class Reference
#include <EicRoot/blob/master/eventdisplay/FairMCTracks.h>
Public Member Functions
FairMCTracks ()
FairMCTracks (const char *name, Int_t iVerbose=1)
virtual ~FairMCTracks ()
void SetVerbose (Int_t iVerbose)
virtual void Exec (Option_t *option)
virtual InitStatus Init ()
virtual void SetParContainers ()
virtual void Finish ()
void Reset ()
TEveTrackList * GetTrGroup (TParticle *P)
Public Member Functions inherited from FairTask
FairTask ()
FairTask (const char *name, Int_t iVerbose=1)
virtual ~FairTask ()
void InitTask ()
void ReInitTask ()
void SetParTask ()
virtual void FinishTask ()
virtual void FinishEvent ()
void SetVerbose (Int_t iVerbose)
void SetInputPersistance (Bool_t val)
void CheckInputPersistance (TString branchName)
Protected Attributes
TClonesArray * fTrackList
TEveTrackPropagator * fTrPr
FairEventManager * fEventManager
TObjArray * fEveTrList
TString fEvent
TEveTrackList * fTrList
Double_t MinEnergyLimit
Double_t MaxEnergyLimit
Double_t PEnergy
Protected Attributes inherited from FairTask
Int_t fVerbose
Int_t fInputPersistance
Indicates if input branch is persistant.
FairLogger * fLogger
Private Member Functions
FairMCTracks (const FairMCTracks &)
FairMCTracks & operator= (const FairMCTracks &)
ClassDef (FairMCTracks, 1)
Additional Inherited Members
Protected Member Functions inherited from FairTask
virtual InitStatus ReInit ()
void InitTasks ()
void ReInitTasks ()
void SetParTasks ()
void FinishTasks ()
void FinishEvents ()
Detailed Description
Definition at line 28 of file FairMCTracks.h.
View newest version in sPHENIX GitHub at line 28 of file FairMCTracks.h
Constructor & Destructor Documentation
FairMCTracks::FairMCTracks ()
Default constructor
Definition at line 24 of file FairMCTracks.cxx.
View newest version in sPHENIX GitHub at line 24 of file FairMCTracks.cxx
FairMCTracks::FairMCTracks (const char * name, Int_t iVerbose = 1)
Standard constructor
Parameters
name Name of task
iVerbose Verbosity level
Definition at line 41 of file FairMCTracks.cxx.
View newest version in sPHENIX GitHub at line 41 of file FairMCTracks.cxx
FairMCTracks::~FairMCTracks () virtual
Destructor
Definition at line 134 of file FairMCTracks.cxx.
View newest version in sPHENIX GitHub at line 134 of file FairMCTracks.cxx
FairMCTracks::FairMCTracks (const FairMCTracks &) private
Member Function Documentation
FairMCTracks::ClassDef (FairMCTracks , 1) private
void FairMCTracks::Exec (Option_t * option) virtual
Executed task
Definition at line 76 of file FairMCTracks.cxx.
View newest version in sPHENIX GitHub at line 76 of file FairMCTracks.cxx
References FairEventManager::Color(), fEventManager, fEveTrList, fTrackList, fTrList, fTrPr, FairTask::fVerbose, FairEventManager::GetCurrentPDG(), FairEventManager::GetMaxEnergy(), FairEventManager::GetMinEnergy(), GetTrGroup(), FairEventManager::IsPriOnly(), MaxEnergyLimit, MinEnergyLimit, n, PEnergy, pos(), Reset(), FairEventManager::SetEvtMaxEnergy(), and FairEventManager::SetEvtMinEnergy().
void FairMCTracks::Finish (void) virtual
Action after each event
Reimplemented from FairTask.
Definition at line 144 of file FairMCTracks.cxx.
View newest version in sPHENIX GitHub at line 144 of file FairMCTracks.cxx
TEveTrackList * FairMCTracks::GetTrGroup (TParticle * P)
Definition at line 158 of file FairMCTracks.cxx.
View newest version in sPHENIX GitHub at line 158 of file FairMCTracks.cxx
References FairEventManager::Color(), fEventManager, fEveTrList, fTrList, and fTrPr.
Referenced by Exec().
InitStatus FairMCTracks::Init (void) virtual
Intialisation at begin of run. To be implemented in the derived class. Success If not kSUCCESS, task will be set inactive.
Reimplemented from FairTask.
Definition at line 55 of file FairMCTracks.cxx.
View newest version in sPHENIX GitHub at line 55 of file FairMCTracks.cxx
References fEvent, fEventManager, fTrackList, FairTask::fVerbose, FairEventManager::GetEvtMaxEnergy(), FairEventManager::GetEvtMinEnergy(), FairRootManager::GetObject(), FairEventManager::Instance(), FairRootManager::Instance(), kERROR, kSUCCESS, MaxEnergyLimit, MinEnergyLimit, and PEnergy.
FairMCTracks& FairMCTracks::operator= (const FairMCTracks &) private
void FairMCTracks::Reset ()
Definition at line 149 of file FairMCTracks.cxx.
View newest version in sPHENIX GitHub at line 149 of file FairMCTracks.cxx
References fEventManager, and fEveTrList.
Referenced by Exec().
void FairMCTracks::SetParContainers () virtual
Intialise parameter containers. To be implemented in the derived class.
Reimplemented from FairTask.
Definition at line 138 of file FairMCTracks.cxx.
View newest version in sPHENIX GitHub at line 138 of file FairMCTracks.cxx
void FairMCTracks::SetVerbose (Int_t iVerbose) inline
Set verbosity level. For this task and all of the subtasks.
Definition at line 47 of file FairMCTracks.h.
View newest version in sPHENIX GitHub at line 47 of file FairMCTracks.h
References FairTask::fVerbose.
Member Data Documentation
TString FairMCTracks::fEvent protected
Definition at line 65 of file FairMCTracks.h.
View newest version in sPHENIX GitHub at line 65 of file FairMCTracks.h
Referenced by Init().
FairEventManager* FairMCTracks::fEventManager protected
Definition at line 63 of file FairMCTracks.h.
View newest version in sPHENIX GitHub at line 63 of file FairMCTracks.h
Referenced by Exec(), GetTrGroup(), Init(), and Reset().
TObjArray* FairMCTracks::fEveTrList protected
Definition at line 64 of file FairMCTracks.h.
View newest version in sPHENIX GitHub at line 64 of file FairMCTracks.h
Referenced by Exec(), GetTrGroup(), and Reset().
TClonesArray* FairMCTracks::fTrackList protected
Definition at line 61 of file FairMCTracks.h.
View newest version in sPHENIX GitHub at line 61 of file FairMCTracks.h
Referenced by Exec(), and Init().
TEveTrackList* FairMCTracks::fTrList protected
Definition at line 66 of file FairMCTracks.h.
View newest version in sPHENIX GitHub at line 66 of file FairMCTracks.h
Referenced by Exec(), and GetTrGroup().
TEveTrackPropagator* FairMCTracks::fTrPr protected
Definition at line 62 of file FairMCTracks.h.
View newest version in sPHENIX GitHub at line 62 of file FairMCTracks.h
Referenced by Exec(), and GetTrGroup().
Double_t FairMCTracks::MaxEnergyLimit protected
Definition at line 70 of file FairMCTracks.h.
View newest version in sPHENIX GitHub at line 70 of file FairMCTracks.h
Referenced by Exec(), and Init().
Double_t FairMCTracks::MinEnergyLimit protected
Definition at line 69 of file FairMCTracks.h.
View newest version in sPHENIX GitHub at line 69 of file FairMCTracks.h
Referenced by Exec(), and Init().
Double_t FairMCTracks::PEnergy protected
Definition at line 71 of file FairMCTracks.h.
View newest version in sPHENIX GitHub at line 71 of file FairMCTracks.h
Referenced by Exec(), and Init().
The documentation for this class was generated from the following files:
EicRoot/blob/master/eventdisplay/FairMCTracks.h
EicRoot/blob/master/eventdisplay/FairMCTracks.cxx