EIC Software: PHG4ProjCrystalCalorimeterDetector Class Reference
PHG4ProjCrystalCalorimeterDetector Class Reference
#include <fun4all_eicdetectors/blob/master/simulation/g4simulation/g4eiccalos/PHG4ProjCrystalCalorimeterDetector.h>
Public Member Functions
PHG4ProjCrystalCalorimeterDetector (PHG4Subsystem *subsys, PHCompositeNode *Node, PHParameters *parameters, const std::string &dnam)
constructor
virtual ~PHG4ProjCrystalCalorimeterDetector ()
destructor
virtual void ConstructMe (G4LogicalVolume *world) override
construct
Public Member Functions inherited from PHG4CrystalCalorimeterDetector
PHG4CrystalCalorimeterDetector (PHG4Subsystem *subsys, PHCompositeNode *Node, PHParameters *parameters, const std::string &dnam)
constructor
virtual ~PHG4CrystalCalorimeterDetector ()
destructor
void SuperDetector (const std::string &name)
const std::string SuperDetector () const
int get_DetectorId () const
void DetectorId (const int i)
PHParameters * GetParams ()
Public Member Functions inherited from PHG4Detector
PHG4Detector ()=delete
constructor
PHG4Detector (PHG4Subsystem *subsys, PHCompositeNode *Node, const std::string &nam)
virtual ~PHG4Detector (void)
destructor
virtual void Construct (G4LogicalVolume *world) final
construct method
virtual void PostConstruction ()
Optional PostConstruction call after all geometry is constructed.
virtual void Verbosity (const int v)
virtual int Verbosity () const
virtual G4UserSteppingAction * GetSteppingAction ()
virtual std::string GetName () const
virtual void OverlapCheck (const bool chk)
virtual bool OverlapCheck () const
virtual void Print (const std::string &="ALL") const
virtual int DisplayVolume (G4VSolid *volume, G4LogicalVolume *logvol, G4RotationMatrix *rotm=nullptr)
virtual int DisplayVolume (G4LogicalVolume *checksolid, G4LogicalVolume *logvol, G4RotationMatrix *rotm=nullptr)
virtual PHCompositeNode * topNode ()
virtual PHG4Subsystem * GetMySubsystem ()
volume accessors
G4double _dx_front
G4double _dy_front
G4double _dx_back
G4double _dy_back
G4double _dz_crystal
std::string _crystallogicnameprefix
std::set< G4VPhysicalVolume * > m_ActiveVolumeSet
std::set< G4VPhysicalVolume * > m_PassiveVolumeSet
int m_IsActive
int m_AbsorberActive
virtual int IsInCrystalCalorimeter (G4VPhysicalVolume *) const override
check if volume is in this calorimeter
void SetCrystalSize (G4double dx_front, G4double dy_front, G4double dx_back, G4double dy_back, G4double dz)
void GetCrystalSize (G4double &dx_front, G4double &dy_front, G4double &dx_back, G4double &dy_back, G4double &dz)
void GetCarbonFiberAdjustments (G4double &adjust_width, G4double &adjust_length)
void GetCarbonFiberSpacing (G4double &CF_width, G4double &Air_CF, G4double &Air_Cry)
int GetCaloType () const override
int ConstructProjectiveCrystals (G4LogicalVolume *envelope)
int Fill4x4Unit (G4LogicalVolume *crystal_logic)
int FillSpecialUnit (G4LogicalVolume *crystal_logic, G4int ident)
Additional Inherited Members
Static Public Member Functions inherited from PHG4Detector
static G4Material * GetDetectorMaterial (const std::string &name, const bool quit=true)
static G4Element * GetDetectorElement (const std::string &name, const bool quit=true)
Protected Member Functions inherited from PHG4CrystalCalorimeterDetector
PHG4CrystalCalorimeterDisplayAction * GetDisplayAction ()
G4Material * GetCarbonFiber ()
Detailed Description
Definition at line 27 of file PHG4ProjCrystalCalorimeterDetector.h.
View newest version in sPHENIX GitHub at line 27 of file PHG4ProjCrystalCalorimeterDetector.h
Constructor & Destructor Documentation
PHG4ProjCrystalCalorimeterDetector::PHG4ProjCrystalCalorimeterDetector (PHG4Subsystem * subsys, PHCompositeNode * Node, PHParameters * parameters, const std::string & dnam)
constructor
Definition at line 39 of file PHG4ProjCrystalCalorimeterDetector.cc.
View newest version in sPHENIX GitHub at line 39 of file PHG4ProjCrystalCalorimeterDetector.cc
virtual PHG4ProjCrystalCalorimeterDetector::~PHG4ProjCrystalCalorimeterDetector () inline virtual
destructor
Definition at line 34 of file PHG4ProjCrystalCalorimeterDetector.h.
View newest version in sPHENIX GitHub at line 34 of file PHG4ProjCrystalCalorimeterDetector.h
Member Function Documentation
void PHG4ProjCrystalCalorimeterDetector::ConstructMe (G4LogicalVolume * world) override virtual
construct
Reimplemented from PHG4CrystalCalorimeterDetector.
Definition at line 81 of file PHG4ProjCrystalCalorimeterDetector.cc.
View newest version in sPHENIX GitHub at line 81 of file PHG4ProjCrystalCalorimeterDetector.cc
References PHG4CrystalCalorimeterDisplayAction::AddVolume(), Acts::UnitConstants::cm, ConstructProjectiveCrystals(), exit(), PHFlag::get_StringFlag(), PHG4Detector::GetDetectorMaterial(), PHG4CrystalCalorimeterDetector::GetDisplayAction(), PHG4CrystalCalorimeterDetector::GetParams(), recoConsts::instance(), M_PI, PHG4Detector::OverlapCheck(), PHG4Detector::Verbosity(), and G4WORLD::WorldMaterial.
int PHG4ProjCrystalCalorimeterDetector::ConstructProjectiveCrystals (G4LogicalVolume * envelope) private
Definition at line 1092 of file PHG4ProjCrystalCalorimeterDetector.cc.
View newest version in sPHENIX GitHub at line 1092 of file PHG4ProjCrystalCalorimeterDetector.cc
References _dx_back, _dx_front, _dz_crystal, PHG4CrystalCalorimeterDisplayAction::AddVolume(), Acts::UnitConstants::cm, dz, Fill4x4Unit(), FillSpecialUnit(), PHParameters::get_double_param(), PHParameters::get_string_param(), PHFlag::get_StringFlag(), GetCrystalSize(), PHG4Detector::GetDetectorMaterial(), PHG4CrystalCalorimeterDetector::GetDisplayAction(), getline, PHG4CrystalCalorimeterDetector::GetParams(), in, recoConsts::instance(), k, Acts::UnitConstants::mm, name, PHG4Detector::OverlapCheck(), Acts::UnitConstants::rad, nlohmann::to_string(), and G4WORLD::WorldMaterial.
Referenced by ConstructMe().
int PHG4ProjCrystalCalorimeterDetector::Fill4x4Unit (G4LogicalVolume * crystal_logic) private
Definition at line 137 of file PHG4ProjCrystalCalorimeterDetector.cc.
View newest version in sPHENIX GitHub at line 137 of file PHG4ProjCrystalCalorimeterDetector.cc
References _crystallogicnameprefix, _dx_back, _dx_front, _dy_back, _dy_front, _dz_crystal, PHG4CrystalCalorimeterDisplayAction::AddVolume(), dz, PHParameters::get_string_param(), PHFlag::get_StringFlag(), PHG4CrystalCalorimeterDetector::GetCarbonFiber(), GetCarbonFiberAdjustments(), GetCarbonFiberSpacing(), PHG4Detector::GetDetectorMaterial(), PHG4CrystalCalorimeterDetector::GetDisplayAction(), getline, PHG4CrystalCalorimeterDetector::GetParams(), in, recoConsts::instance(), k, m_ActiveVolumeSet, m_PassiveVolumeSet, Acts::UnitConstants::mm, PHG4Detector::OverlapCheck(), Acts::UnitConstants::rad, nlohmann::to_string(), and G4WORLD::WorldMaterial.
Referenced by ConstructProjectiveCrystals().
int PHG4ProjCrystalCalorimeterDetector::FillSpecialUnit (G4LogicalVolume * crystal_logic, G4int ident) private
Definition at line 514 of file PHG4ProjCrystalCalorimeterDetector.cc.
View newest version in sPHENIX GitHub at line 514 of file PHG4ProjCrystalCalorimeterDetector.cc
References _crystallogicnameprefix, _dx_back, _dx_front, _dy_back, _dy_front, _dz_crystal, PHG4CrystalCalorimeterDisplayAction::AddVolume(), dz, PHParameters::get_string_param(), PHFlag::get_StringFlag(), PHG4CrystalCalorimeterDetector::GetCarbonFiber(), GetCarbonFiberAdjustments(), GetCarbonFiberSpacing(), GetCrystalSize(), PHG4Detector::GetDetectorMaterial(), PHG4CrystalCalorimeterDetector::GetDisplayAction(), getline, PHG4CrystalCalorimeterDetector::GetParams(), in, recoConsts::instance(), k, m_ActiveVolumeSet, m_PassiveVolumeSet, Acts::UnitConstants::mm, PHG4Detector::OverlapCheck(), Acts::UnitConstants::rad, nlohmann::to_string(), and G4WORLD::WorldMaterial.
Referenced by ConstructProjectiveCrystals().
int PHG4ProjCrystalCalorimeterDetector::GetCaloType () const inline override protected virtual
Reimplemented from PHG4CrystalCalorimeterDetector.
Definition at line 67 of file PHG4ProjCrystalCalorimeterDetector.h.
View newest version in sPHENIX GitHub at line 67 of file PHG4ProjCrystalCalorimeterDetector.h
References PHG4CrystalCalorimeterDefs::projective.
Referenced by IsInCrystalCalorimeter().
void PHG4ProjCrystalCalorimeterDetector::GetCarbonFiberAdjustments (G4double & adjust_width, G4double & adjust_length)
Definition at line 123 of file PHG4ProjCrystalCalorimeterDetector.cc.
View newest version in sPHENIX GitHub at line 123 of file PHG4ProjCrystalCalorimeterDetector.cc
References Acts::UnitConstants::mm.
Referenced by Fill4x4Unit(), and FillSpecialUnit().
void PHG4ProjCrystalCalorimeterDetector::GetCarbonFiberSpacing (G4double & CF_width, G4double & Air_CF, G4double & Air_Cry)
Definition at line 129 of file PHG4ProjCrystalCalorimeterDetector.cc.
View newest version in sPHENIX GitHub at line 129 of file PHG4ProjCrystalCalorimeterDetector.cc
References Acts::UnitConstants::mm.
Referenced by Fill4x4Unit(), and FillSpecialUnit().
void PHG4ProjCrystalCalorimeterDetector::GetCrystalSize (G4double & dx_front, G4double & dy_front, G4double & dx_back, G4double & dy_back, G4double & dz) inline
Definition at line 53 of file PHG4ProjCrystalCalorimeterDetector.h.
View newest version in sPHENIX GitHub at line 53 of file PHG4ProjCrystalCalorimeterDetector.h
References _dx_back, _dx_front, _dy_back, _dy_front, and _dz_crystal.
Referenced by ConstructProjectiveCrystals(), and FillSpecialUnit().
int PHG4ProjCrystalCalorimeterDetector::IsInCrystalCalorimeter (G4VPhysicalVolume * volume) const override virtual
check if volume is in this calorimeter
Reimplemented from PHG4CrystalCalorimeterDetector.
Definition at line 58 of file PHG4ProjCrystalCalorimeterDetector.cc.
View newest version in sPHENIX GitHub at line 58 of file PHG4ProjCrystalCalorimeterDetector.cc
References GetCaloType(), m_AbsorberActive, m_ActiveVolumeSet, m_IsActive, and m_PassiveVolumeSet.
void PHG4ProjCrystalCalorimeterDetector::SetCrystalSize (G4double dx_front, G4double dy_front, G4double dx_back, G4double dy_back, G4double dz) inline
Definition at line 44 of file PHG4ProjCrystalCalorimeterDetector.h.
View newest version in sPHENIX GitHub at line 44 of file PHG4ProjCrystalCalorimeterDetector.h
References _dx_back, _dx_front, _dy_back, _dy_front, _dz_crystal, and dz.
Member Data Documentation
std::string PHG4ProjCrystalCalorimeterDetector::_crystallogicnameprefix private
Definition at line 81 of file PHG4ProjCrystalCalorimeterDetector.h.
View newest version in sPHENIX GitHub at line 81 of file PHG4ProjCrystalCalorimeterDetector.h
Referenced by Fill4x4Unit(), and FillSpecialUnit().
G4double PHG4ProjCrystalCalorimeterDetector::_dx_back private
Definition at line 77 of file PHG4ProjCrystalCalorimeterDetector.h.
View newest version in sPHENIX GitHub at line 77 of file PHG4ProjCrystalCalorimeterDetector.h
Referenced by ConstructProjectiveCrystals(), Fill4x4Unit(), FillSpecialUnit(), GetCrystalSize(), and SetCrystalSize().
G4double PHG4ProjCrystalCalorimeterDetector::_dx_front private
Definition at line 75 of file PHG4ProjCrystalCalorimeterDetector.h.
View newest version in sPHENIX GitHub at line 75 of file PHG4ProjCrystalCalorimeterDetector.h
Referenced by ConstructProjectiveCrystals(), Fill4x4Unit(), FillSpecialUnit(), GetCrystalSize(), and SetCrystalSize().
G4double PHG4ProjCrystalCalorimeterDetector::_dy_back private
Definition at line 78 of file PHG4ProjCrystalCalorimeterDetector.h.
View newest version in sPHENIX GitHub at line 78 of file PHG4ProjCrystalCalorimeterDetector.h
Referenced by Fill4x4Unit(), FillSpecialUnit(), GetCrystalSize(), and SetCrystalSize().
G4double PHG4ProjCrystalCalorimeterDetector::_dy_front private
Definition at line 76 of file PHG4ProjCrystalCalorimeterDetector.h.
View newest version in sPHENIX GitHub at line 76 of file PHG4ProjCrystalCalorimeterDetector.h
Referenced by Fill4x4Unit(), FillSpecialUnit(), GetCrystalSize(), and SetCrystalSize().
G4double PHG4ProjCrystalCalorimeterDetector::_dz_crystal private
Definition at line 79 of file PHG4ProjCrystalCalorimeterDetector.h.
View newest version in sPHENIX GitHub at line 79 of file PHG4ProjCrystalCalorimeterDetector.h
Referenced by ConstructProjectiveCrystals(), Fill4x4Unit(), FillSpecialUnit(), GetCrystalSize(), and SetCrystalSize().
int PHG4ProjCrystalCalorimeterDetector::m_AbsorberActive private
Definition at line 89 of file PHG4ProjCrystalCalorimeterDetector.h.
View newest version in sPHENIX GitHub at line 89 of file PHG4ProjCrystalCalorimeterDetector.h
Referenced by IsInCrystalCalorimeter().
std::set<G4VPhysicalVolume*> PHG4ProjCrystalCalorimeterDetector::m_ActiveVolumeSet private
Definition at line 83 of file PHG4ProjCrystalCalorimeterDetector.h.
View newest version in sPHENIX GitHub at line 83 of file PHG4ProjCrystalCalorimeterDetector.h
Referenced by Fill4x4Unit(), FillSpecialUnit(), and IsInCrystalCalorimeter().
int PHG4ProjCrystalCalorimeterDetector::m_IsActive private
Definition at line 88 of file PHG4ProjCrystalCalorimeterDetector.h.
View newest version in sPHENIX GitHub at line 88 of file PHG4ProjCrystalCalorimeterDetector.h
Referenced by IsInCrystalCalorimeter().
std::set<G4VPhysicalVolume*> PHG4ProjCrystalCalorimeterDetector::m_PassiveVolumeSet private
Definition at line 84 of file PHG4ProjCrystalCalorimeterDetector.h.
View newest version in sPHENIX GitHub at line 84 of file PHG4ProjCrystalCalorimeterDetector.h
Referenced by Fill4x4Unit(), FillSpecialUnit(), and IsInCrystalCalorimeter().
The documentation for this class was generated from the following files:
fun4all_eicdetectors/blob/master/simulation/g4simulation/g4eiccalos/PHG4ProjCrystalCalorimeterDetector.h
fun4all_eicdetectors/blob/master/simulation/g4simulation/g4eiccalos/PHG4ProjCrystalCalorimeterDetector.cc