EIC Software: CbmTrackMatch Class Reference
CbmTrackMatch Class Reference
#include <EicRoot/blob/master/cbmdata/CbmTrackMatch.h>
Public Member Functions
CbmTrackMatch ()
CbmTrackMatch (Int_t mcTrackID, Int_t nTrue, Int_t nWrong, Int_t nFake, Int_t nTracks)
virtual ~CbmTrackMatch ()
Int_t GetMCTrackId () const
Int_t GetNofTrueHits () const
Int_t GetNofWrongHits () const
Int_t GetNofFakeHits () const
Int_t GetNofMCTracks () const
Private Member Functions
ClassDef (CbmTrackMatch, 1)
Private Attributes
Int_t fMCTrackId
Int_t fNofTrueHits
Int_t fNofWrongHits
Int_t fNofFakeHits
Int_t fNofMCTracks
Detailed Description
CbmStsTrackMatch.h
Author
V.Friese v.fri.nosp@m.ese@.nosp@m.gsi.d.nosp@m.e
Since
07.05.2009
Data structure describing the matching of a reconstructed track with a Monte Carlo track on the base of corresponding hits/points. This requires matching of hits to MC points.
Definition at line 19 of file CbmTrackMatch.h.
View newest version in sPHENIX GitHub at line 19 of file CbmTrackMatch.h
Constructor & Destructor Documentation
CbmTrackMatch::CbmTrackMatch ()
Default constructor
CbmStsTrackMatch.cxx
Author
V.Friese v.fri.nosp@m.ese@.nosp@m.gsi.d.nosp@m.e
Since
07.05.2009
Definition at line 12 of file CbmTrackMatch.cxx.
View newest version in sPHENIX GitHub at line 12 of file CbmTrackMatch.cxx
CbmTrackMatch::CbmTrackMatch (Int_t mcTrackID, Int_t nTrue, Int_t nWrong, Int_t nFake, Int_t nTracks)
Standard constructor
Parameters
mcTrackID Index of matched MCTrack
nTrue Number of true hits (belonging to matched MCTrack)
nWrong Number of wrong Hits (from other MCTracks)
nFake Number of fake hits (not belonging to any MCTrack)
nTracks Number of MCTracks with common hits
Definition at line 24 of file CbmTrackMatch.cxx.
View newest version in sPHENIX GitHub at line 24 of file CbmTrackMatch.cxx
CbmTrackMatch::~CbmTrackMatch () virtual
Destructor
Definition at line 40 of file CbmTrackMatch.cxx.
View newest version in sPHENIX GitHub at line 40 of file CbmTrackMatch.cxx
Member Function Documentation
CbmTrackMatch::ClassDef (CbmTrackMatch , 1) private
Int_t CbmTrackMatch::GetMCTrackId () const inline
Index of matched MC track
Definition at line 47 of file CbmTrackMatch.h.
View newest version in sPHENIX GitHub at line 47 of file CbmTrackMatch.h
References fMCTrackId.
Referenced by CbmRichTrainAnnElectrons::DiffElandPi(), CbmRichRingTrackAssignIdeal::DoAssign(), CbmRichTrackExtrapolationIdeal::DoExtrapolation(), CbmRichTrackExtrapolationMirrorIdeal::DoExtrapolation(), CbmRichUrqmdTest::NofRings(), CbmRichGeoTest::RingParameters(), and CbmRichTrainAnnSelect::SetRecFlag().
Int_t CbmTrackMatch::GetNofFakeHits () const inline
Number of fake hits on track (from no MC track)
Definition at line 56 of file CbmTrackMatch.h.
View newest version in sPHENIX GitHub at line 56 of file CbmTrackMatch.h
References fNofFakeHits.
Referenced by CbmRichTrainAnnElectrons::DiffElandPi(), and CbmRichTrainAnnSelect::SetRecFlag().
Int_t CbmTrackMatch::GetNofMCTracks () const inline
Number of MCTracks with common hits
Definition at line 59 of file CbmTrackMatch.h.
View newest version in sPHENIX GitHub at line 59 of file CbmTrackMatch.h
References fNofMCTracks.
Int_t CbmTrackMatch::GetNofTrueHits () const inline
Number of true hits on track (from matched MC track)
Definition at line 50 of file CbmTrackMatch.h.
View newest version in sPHENIX GitHub at line 50 of file CbmTrackMatch.h
References fNofTrueHits.
Referenced by CbmRichTrainAnnElectrons::DiffElandPi(), and CbmRichTrainAnnSelect::SetRecFlag().
Int_t CbmTrackMatch::GetNofWrongHits () const inline
Number of wrong hits on track (from other MC tracks)
Definition at line 53 of file CbmTrackMatch.h.
View newest version in sPHENIX GitHub at line 53 of file CbmTrackMatch.h
References fNofWrongHits.
Referenced by CbmRichTrainAnnElectrons::DiffElandPi(), and CbmRichTrainAnnSelect::SetRecFlag().
Member Data Documentation
Int_t CbmTrackMatch::fMCTrackId private
Index of matched CbmMCTrack
Definition at line 59 of file CbmTrackMatch.h.
View newest version in sPHENIX GitHub at line 59 of file CbmTrackMatch.h
Referenced by GetMCTrackId().
Int_t CbmTrackMatch::fNofFakeHits private
Number of fake hits (belonging to no MCTrack)
Definition at line 74 of file CbmTrackMatch.h.
View newest version in sPHENIX GitHub at line 74 of file CbmTrackMatch.h
Referenced by GetNofFakeHits().
Int_t CbmTrackMatch::fNofMCTracks private
Number of MCTrackx with common hits
Definition at line 77 of file CbmTrackMatch.h.
View newest version in sPHENIX GitHub at line 77 of file CbmTrackMatch.h
Referenced by GetNofMCTracks().
Int_t CbmTrackMatch::fNofTrueHits private
Number of true hits (belonging to the matched MCTrack)
Definition at line 68 of file CbmTrackMatch.h.
View newest version in sPHENIX GitHub at line 68 of file CbmTrackMatch.h
Referenced by GetNofTrueHits().
Int_t CbmTrackMatch::fNofWrongHits private
Number of wrong hits (belonging to other MCTracks)
Definition at line 71 of file CbmTrackMatch.h.
View newest version in sPHENIX GitHub at line 71 of file CbmTrackMatch.h
Referenced by GetNofWrongHits().
The documentation for this class was generated from the following files:
EicRoot/blob/master/cbmdata/CbmTrackMatch.h
EicRoot/blob/master/cbmdata/CbmTrackMatch.cxx