EIC Software: eicsmeardetectors/blob/master/tests/ffqaplots.cxx File Reference
ffqaplots.cxx File Reference
#include "ffqaplots.hh"
#include <eicsmear/functions.h>
#include <eicsmear/smear/functions.h>
#include "eicsmear/erhic/EventBase.h"
#include "eicsmear/erhic/EventPythia.h"
#include "eicsmear/erhic/Particle.h"
#include "eicsmear/smear/EventSmear.h"
#include "eicsmear/smear/EventS.h"
#include "eicsmear/smear/Smear.h"
#include "eicsmear/smear/ParticleMCS.h"
#include "eicsmear/smear/Detector.h"
#include "eicsmeardetectors.hh"
#include <TSystem.h>
#include <TDatabasePDG.h>
#include <TFile.h>
#include <TChain.h>
#include <TCanvas.h>
#include <TProfile.h>
#include <TLegend.h>
#include <TText.h>
#include <TStyle.h>
#include <string>
#include <iomanip>
#include <cctype>
#include <exception>
#include <vector>
#include <map>
Functions
static const TString getrootname (const qaparameters &qapars)
static void initializepidqabook (const qaparameters &qapars, map< int, pidqacollection > &qabook)
static void initializeeventqa (const qaparameters &qapars, eventqacollection &eventqa)
static void FillEventQA (eventqacollection &eventqa, const erhic::EventMC *const inEvent, const Smear::Event *const inEventS)
static void FillParticleQA (map< int, pidqacollection > &qabook, const Particle *const inParticle, const Smear::ParticleMCS *const inParticleS, const qaparameters &qapars)
static void PlotQA (const qaparameters &qapars, eventqacollection &eventqa, map< int, pidqacollection > &qabook)
int main (int argc, char *argv[])
qaparameters ParseArguments (int argc, char *argv[])
Function Documentation
void FillEventQA (eventqacollection & eventqa, const erhic::EventMC *const inEvent, const Smear::Event *const inEventS) static
Definition at line 198 of file ffqaplots.cxx.
View newest version in sPHENIX GitHub at line 198 of file ffqaplots.cxx
void FillParticleQA (map< int, pidqacollection > & qabook, const Particle *const inParticle, const Smear::ParticleMCS *const inParticleS, const qaparameters & qapars) static
Definition at line 220 of file ffqaplots.cxx.
View newest version in sPHENIX GitHub at line 220 of file ffqaplots.cxx
References qaparameters::beam_mom_nn, erhic::ParticleMCbase::GetP(), erhic::ParticleMCbase::GetPdgCode(), erhic::ParticleMCbase::GetPhi(), erhic::ParticleMCbase::GetPt(), erhic::ParticleMCbase::GetTheta(), and pid.
const TString getrootname (const qaparameters & qapars) static
Definition at line 309 of file ffqaplots.cxx.
View newest version in sPHENIX GitHub at line 309 of file ffqaplots.cxx
References qaparameters::nevents, qaparameters::outpath, and qaparameters::txtfilename.
Referenced by main().
void initializeeventqa (const qaparameters & qapars, eventqacollection & eventqa) static
Definition at line 387 of file ffqaplots.cxx.
View newest version in sPHENIX GitHub at line 387 of file ffqaplots.cxx
Referenced by main().
void initializepidqabook (const qaparameters & qapars, map< int, pidqacollection > & qabook) static
Definition at line 336 of file ffqaplots.cxx.
View newest version in sPHENIX GitHub at line 336 of file ffqaplots.cxx
References qaparameters::beam_mom_nn, qaparameters::detstring, phibins, phimin, pid, qaparameters::pids, Acts::UnitConstants::s, and t.
int main (int argc, char * argv[])
Definition at line 62 of file ffqaplots.cxx.
View newest version in sPHENIX GitHub at line 62 of file ffqaplots.cxx
References qaparameters::beam_mom_nn, erhic::DisKinematics::BoundaryWarning, BuildByName(), BuildTree(), qaparameters::detstring, Smear::Detector::GetNDevices(), getrootname(), initializeeventqa(), qaparameters::nevents, qaparameters::outfilebase, qaparameters::outpath, ParseArguments(), qaparameters::pids, SmearTree(), and qaparameters::txtfilename.
qaparameters ParseArguments (int argc, char * argv[])
Definition at line 252 of file ffqaplots.cxx.
View newest version in sPHENIX GitHub at line 252 of file ffqaplots.cxx
Referenced by main().
void PlotQA (const qaparameters & qapars, eventqacollection & eventqa, map< int, pidqacollection > & qabook) static
Definition at line 427 of file ffqaplots.cxx.
View newest version in sPHENIX GitHub at line 427 of file ffqaplots.cxx
References qaparameters::beam_mom_nn, qaparameters::detstring, qaparameters::outfilebase, pid, qaparameters::pids, and t.