EIC Software: EicRoot/blob/master/eic/htc/runge-kutta.cxx File Reference
runge-kutta.cxx File Reference
#include <cassert>
#include <cstdlib>
#include <htclib.h>
#include <TrKalmanFilter.h>
Macros
#define _SMALL_STEP_ORDER_PREFIX_ "small-step-order="
Functions
int parse_htc_interpolation_string (char *string, t_htc_interpolation *htci)
int runge_kutta_fun (int argc, char **argv)
Variables
double RK_cell_width_max
double RK_fixed_cell_width
double RK_small_step_limit = _RK_SMALL_STEP_DEFAULT_
int RK_small_step_order = _RK_ORDER_4_
t_htc_interpolation RK_htci = {_MODE_ADIM_, {2, 2, 1}}
int field_missing_flags [_FIELD_AREA_NUM_MAX_]
int RK_flavor = _RK_HERMES_
static t_cmd_line_variable_array RK_array
Macro Definition Documentation
#define _SMALL_STEP_ORDER_PREFIX_ "small-step-order="
Definition at line 40 of file runge-kutta.cxx.
View newest version in sPHENIX GitHub at line 40 of file runge-kutta.cxx
Referenced by runge_kutta_fun().
Function Documentation
int parse_htc_interpolation_string (char * string, t_htc_interpolation * htci)
Definition at line 44 of file runge-kutta.cxx.
View newest version in sPHENIX GitHub at line 44 of file runge-kutta.cxx
References _INTERPOLATION_PREFIX_, _MODE_ADIM_, _MODE_HRC_, _MODE_OFF_, t_htc_interpolation::adim, check_prefix(), t_htc_interpolation::mode, and x.
Referenced by runge_kutta_fun().
int runge_kutta_fun (int argc, char ** argv)
Definition at line 103 of file runge-kutta.cxx.
View newest version in sPHENIX GitHub at line 103 of file runge-kutta.cxx
References _INTERPOLATION_PREFIX_, _MODE_ADIM_, _RETURN_, _RK_HERA_B_, _RK_HERMES_, _RK_ORDER_2_, _RK_ORDER_4_, _SMALL_STEP_ORDER_PREFIX_, _Z_, t_htc_interpolation::adim, check_prefix(), cmd_line_variable_parser(), t_htc_interpolation::mode, parse_htc_interpolation_string(), printf(), RK_flavor, and RK_small_step_order.
Referenced by EicHtcTask::ConfigureKalmanFilter().
Variable Documentation
int field_missing_flags[_FIELD_AREA_NUM_MAX_]
Definition at line 24 of file runge-kutta.cxx.
View newest version in sPHENIX GitHub at line 24 of file runge-kutta.cxx
t_cmd_line_variable_array RK_array static
Initial value:
=
  {3,
   {{(char*)"cell-width-max=",   (char*)"cm",  &RK_cell_width_max,   2.0,   10.0, 0, 0},
    {(char*)"fixed-cell-width=", (char*)"cm",  &RK_fixed_cell_width, 2.0,   10.0, 0, 0},
    {(char*)"small-step-limit=", (char*)"cm",  &RK_small_step_limit, 0.1,  100.0, 0, 0}}}
Definition at line 34 of file runge-kutta.cxx.
View newest version in sPHENIX GitHub at line 34 of file runge-kutta.cxx
double RK_cell_width_max
Definition at line 17 of file runge-kutta.cxx.
View newest version in sPHENIX GitHub at line 17 of file runge-kutta.cxx
double RK_fixed_cell_width
Definition at line 17 of file runge-kutta.cxx.
View newest version in sPHENIX GitHub at line 17 of file runge-kutta.cxx
int RK_flavor = _RK_HERMES_
Definition at line 27 of file runge-kutta.cxx.
View newest version in sPHENIX GitHub at line 27 of file runge-kutta.cxx
Referenced by runge_kutta_fun().
t_htc_interpolation RK_htci = {_MODE_ADIM_, {2, 2, 1}}
Definition at line 21 of file runge-kutta.cxx.
View newest version in sPHENIX GitHub at line 21 of file runge-kutta.cxx
Referenced by HtcKalmanFilter::InitializeMgridSlice().
double RK_small_step_limit = _RK_SMALL_STEP_DEFAULT_
Definition at line 18 of file runge-kutta.cxx.
View newest version in sPHENIX GitHub at line 18 of file runge-kutta.cxx
Referenced by TrKalmanFilter::InitializeRungeKuttaFrames().
int RK_small_step_order = _RK_ORDER_4_
Definition at line 20 of file runge-kutta.cxx.
View newest version in sPHENIX GitHub at line 20 of file runge-kutta.cxx
Referenced by TrKalmanFilter::InitializeRungeKuttaFrames(), and runge_kutta_fun().