EIC Software: EICPIDParticleContainer Class Reference
EICPIDParticleContainer Class Reference
#include <fun4all_eicdetectors/blob/master/reconstruction/eicpidbase/EICPIDParticleContainer.h>
Public Types
typedef std::map
< EICPIDDefs::keytype,
EICPIDParticle * > Map
typedef Map::iterator Iterator
typedef Map::const_iterator ConstIterator
typedef std::pair< Iterator,
Iterator > Range
typedef std::pair
< ConstIterator, ConstIterator > ConstRange
typedef std::set< unsigned int >
::const_iterator LayerIter
Public Member Functions
EICPIDParticleContainer ()
~EICPIDParticleContainer () override
void Reset () override
Clear Event.
void identify (std::ostream &os=std::cout) const override
ConstIterator AddPIDParticle (EICPIDParticle *newhit)
Iterator findOrAddPIDParticle (EICPIDDefs::keytype key)
EICPIDParticle * findEICPIDParticle (EICPIDDefs::keytype key)
ConstRange getPIDParticles (void) const
return all hist
unsigned int size (void) const
Public Member Functions inherited from PHObject
PHObject ()
ctor
~PHObject () override
dtor
virtual PHObject * CloneMe () const
Virtual copy constructor.
virtual PHObject * clone () const final
PHObject * Clone (const char *newname="") const final
void Copy (TObject &object) const final
virtual int isValid () const
isValid returns non zero if object contains vailid data
virtual int isValid (const float) const
virtual int isValid (const double) const
virtual int isValid (const int) const
virtual int isValid (const unsigned int) const
virtual int isImplemented (const float f) const
virtual int isImplemented (const double f) const
virtual int isImplemented (const int i) const
virtual int isImplemented (const unsigned int i) const
virtual int Integrate () const
virtual int Integrate (PHObject *)
virtual void CopyFrom (const PHObject *obj)
Protected Attributes
Map m_particleMap
Detailed Description
Definition at line 18 of file EICPIDParticleContainer.h.
View newest version in sPHENIX GitHub at line 18 of file EICPIDParticleContainer.h
Member Typedef Documentation
typedef Map::const_iterator EICPIDParticleContainer::ConstIterator
Definition at line 23 of file EICPIDParticleContainer.h.
View newest version in sPHENIX GitHub at line 23 of file EICPIDParticleContainer.h
typedef std::pair<ConstIterator, ConstIterator> EICPIDParticleContainer::ConstRange
Definition at line 25 of file EICPIDParticleContainer.h.
View newest version in sPHENIX GitHub at line 25 of file EICPIDParticleContainer.h
typedef Map::iterator EICPIDParticleContainer::Iterator
Definition at line 22 of file EICPIDParticleContainer.h.
View newest version in sPHENIX GitHub at line 22 of file EICPIDParticleContainer.h
typedef std::set<unsigned int>::const_iterator EICPIDParticleContainer::LayerIter
Definition at line 26 of file EICPIDParticleContainer.h.
View newest version in sPHENIX GitHub at line 26 of file EICPIDParticleContainer.h
typedef std::map<EICPIDDefs::keytype, EICPIDParticle*> EICPIDParticleContainer::Map
Definition at line 21 of file EICPIDParticleContainer.h.
View newest version in sPHENIX GitHub at line 21 of file EICPIDParticleContainer.h
typedef std::pair<Iterator, Iterator> EICPIDParticleContainer::Range
Definition at line 24 of file EICPIDParticleContainer.h.
View newest version in sPHENIX GitHub at line 24 of file EICPIDParticleContainer.h
Constructor & Destructor Documentation
EICPIDParticleContainer::EICPIDParticleContainer ()
Definition at line 13 of file EICPIDParticleContainer.cc.
View newest version in sPHENIX GitHub at line 13 of file EICPIDParticleContainer.cc
EICPIDParticleContainer::~EICPIDParticleContainer () inline override
Definition at line 30 of file EICPIDParticleContainer.h.
View newest version in sPHENIX GitHub at line 30 of file EICPIDParticleContainer.h
Member Function Documentation
EICPIDParticleContainer::ConstIterator EICPIDParticleContainer::AddPIDParticle (EICPIDParticle * newhit)
Definition at line 40 of file EICPIDParticleContainer.cc.
View newest version in sPHENIX GitHub at line 40 of file EICPIDParticleContainer.cc
References EICPIDParticle::get_id().
EICPIDParticle * EICPIDParticleContainer::findEICPIDParticle (EICPIDDefs::keytype key)
Definition at line 69 of file EICPIDParticleContainer.cc.
View newest version in sPHENIX GitHub at line 69 of file EICPIDParticleContainer.cc
References it.
Referenced by EventEvaluatorEIC::fillOutputNtuples().
EICPIDParticleContainer::Iterator EICPIDParticleContainer::findOrAddPIDParticle (EICPIDDefs::keytype key)
Definition at line 56 of file EICPIDParticleContainer.cc.
View newest version in sPHENIX GitHub at line 56 of file EICPIDParticleContainer.cc
References it, and EICPIDParticle::set_id().
EICPIDParticleContainer::ConstRange EICPIDParticleContainer::getPIDParticles (void) const
return all hist
Definition at line 51 of file EICPIDParticleContainer.cc.
View newest version in sPHENIX GitHub at line 51 of file EICPIDParticleContainer.cc
void EICPIDParticleContainer::identify (std::ostream & os = std::cout) const override virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from PHObject.
Definition at line 27 of file EICPIDParticleContainer.cc.
View newest version in sPHENIX GitHub at line 27 of file EICPIDParticleContainer.cc
References identify().
Referenced by identify().
void EICPIDParticleContainer::Reset () override virtual
Clear Event.
Reimplemented from PHObject.
Definition at line 17 of file EICPIDParticleContainer.cc.
View newest version in sPHENIX GitHub at line 17 of file EICPIDParticleContainer.cc
unsigned int EICPIDParticleContainer::size (void) const inline
Definition at line 45 of file EICPIDParticleContainer.h.
View newest version in sPHENIX GitHub at line 45 of file EICPIDParticleContainer.h
References m_particleMap.
Member Data Documentation
Map EICPIDParticleContainer::m_particleMap protected
Definition at line 51 of file EICPIDParticleContainer.h.
View newest version in sPHENIX GitHub at line 51 of file EICPIDParticleContainer.h
Referenced by size().
The documentation for this class was generated from the following files:
fun4all_eicdetectors/blob/master/reconstruction/eicpidbase/EICPIDParticleContainer.h
fun4all_eicdetectors/blob/master/reconstruction/eicpidbase/EICPIDParticleContainer.cc