EIC Software: CbmRichReconstruction Class Reference
CbmRichReconstruction Class Reference
Main class for running event reconstruction in the RICH detector.
#include <EicRoot/blob/master/rich/CbmRichReconstruction.h>
Public Member Functions
CbmRichReconstruction ()
Default constructor.
virtual ~CbmRichReconstruction ()
Destructor.
void SetParContainers ()
Inherited from FairTask.
virtual InitStatus Init ()
Inherited from FairTask.
virtual void Exec (Option_t *opt)
Inherited from FairTask.
virtual void Finish ()
Inherited from FairTask.
void SetRunExtrapolation (bool b)
void SetRunProjection (bool b)
void SetRunFinder (bool b)
void SetRunFitter (bool b)
void SetRunTrackAssign (bool b)
void SetExtrapolationName (const string &n)
void SetProjectionName (const string &n)
void SetFinderName (const string &n)
void SetFitterName (const string &n)
void SetTrackAssignName (const string &n)
void SetZTrackExtrapolation (Double_t z)
Set Z coordinate where STS tracks will be extrapolated.
void SetMinNofStsHits (Int_t minNofStsHits)
Set minimum number of STS hits.
Public Member Functions inherited from FairTask
FairTask ()
FairTask (const char *name, Int_t iVerbose=1)
virtual ~FairTask ()
void InitTask ()
void ReInitTask ()
void SetParTask ()
virtual void FinishTask ()
virtual void FinishEvent ()
void SetVerbose (Int_t iVerbose)
void SetInputPersistance (Bool_t val)
void CheckInputPersistance (TString branchName)
Private Member Functions
void InitExtrapolation ()
void InitProjection ()
void InitFinder ()
void InitFitter ()
void InitTrackAssign ()
void RunExtrapolation ()
void RunProjection ()
void RunFinder ()
void RunFitter ()
void RunTrackAssign ()
CbmRichReconstruction (const CbmRichReconstruction &)
Copy constructor.
CbmRichReconstruction & operator= (const CbmRichReconstruction &)
Assignment operator.
ClassDef (CbmRichReconstruction, 1)
Private Attributes
TClonesArray * fRichHits
TClonesArray * fRichRings
TClonesArray * fRichProjections
TClonesArray * fRichTrackParamZ
TClonesArray * fGlobalTracks
CbmRichRingFinder * fRingFinder
CbmRichRingFitterBase * fRingFitter
CbmRichTrackExtrapolationBase * fTrackExtrapolation
CbmRichProjectionProducerBase * fProjectionProducer
CbmRichRingTrackAssignBase * fRingTrackAssign
bool fRunExtrapolation
bool fRunProjection
bool fRunFinder
bool fRunFitter
bool fRunTrackAssign
string fExtrapolationName
string fProjectionName
string fFinderName
string fFitterName
string fTrackAssignName
Double_t fZTrackExtrapolation
Int_t fMinNofStsHits
Additional Inherited Members
Protected Member Functions inherited from FairTask
virtual InitStatus ReInit ()
void InitTasks ()
void ReInitTasks ()
void SetParTasks ()
void FinishTasks ()
void FinishEvents ()
Protected Attributes inherited from FairTask
Int_t fVerbose
Int_t fInputPersistance
Indicates if input branch is persistant.
FairLogger * fLogger
Detailed Description
Main class for running event reconstruction in the RICH detector.
Author
Semen Lebedev
Date
2012
Definition at line 34 of file CbmRichReconstruction.h.
View newest version in sPHENIX GitHub at line 34 of file CbmRichReconstruction.h
Constructor & Destructor Documentation
CbmRichReconstruction::CbmRichReconstruction ()
Default constructor.
Definition at line 46 of file CbmRichReconstruction.cxx.
View newest version in sPHENIX GitHub at line 46 of file CbmRichReconstruction.cxx
CbmRichReconstruction::~CbmRichReconstruction () virtual
Destructor.
Definition at line 78 of file CbmRichReconstruction.cxx.
View newest version in sPHENIX GitHub at line 78 of file CbmRichReconstruction.cxx
References fProjectionProducer, fRingFinder, fRingFitter, and fTrackExtrapolation.
CbmRichReconstruction::CbmRichReconstruction (const CbmRichReconstruction &) private
Copy constructor.
Member Function Documentation
CbmRichReconstruction::ClassDef (CbmRichReconstruction , 1) private
void CbmRichReconstruction::Exec (Option_t * opt) virtual
Inherited from FairTask.
Definition at line 130 of file CbmRichReconstruction.cxx.
View newest version in sPHENIX GitHub at line 130 of file CbmRichReconstruction.cxx
References fRunExtrapolation, fRunFinder, fRunFitter, fRunProjection, fRunTrackAssign, RunExtrapolation(), RunFinder(), RunFitter(), RunProjection(), and RunTrackAssign().
void CbmRichReconstruction::Finish (void) virtual
Inherited from FairTask.
Reimplemented from FairTask.
Definition at line 274 of file CbmRichReconstruction.cxx.
View newest version in sPHENIX GitHub at line 274 of file CbmRichReconstruction.cxx
InitStatus CbmRichReconstruction::Init (void) virtual
Inherited from FairTask.
Reimplemented from FairTask.
Definition at line 97 of file CbmRichReconstruction.cxx.
View newest version in sPHENIX GitHub at line 97 of file CbmRichReconstruction.cxx
References fGlobalTracks, fRichHits, fRichProjections, fRichRings, fRichTrackParamZ, fRunExtrapolation, fRunFinder, fRunFitter, fRunProjection, fRunTrackAssign, FairRootManager::GetObject(), InitExtrapolation(), InitFinder(), InitFitter(), InitProjection(), InitTrackAssign(), FairRootManager::Instance(), kSUCCESS, and FairRootManager::Register().
void CbmRichReconstruction::InitExtrapolation () private
Definition at line 140 of file CbmRichReconstruction.cxx.
View newest version in sPHENIX GitHub at line 140 of file CbmRichReconstruction.cxx
References FairLogger::endl(), FATAL, fExtrapolationName, fProjectionProducer, fTrackExtrapolation, CbmRichTrackExtrapolationBase::Init(), and CbmRichProjectionProducerBase::SetZFlag().
Referenced by Init().
void CbmRichReconstruction::InitFinder () private
Definition at line 166 of file CbmRichReconstruction.cxx.
View newest version in sPHENIX GitHub at line 166 of file CbmRichReconstruction.cxx
References FairLogger::endl(), FATAL, fFinderName, fRingFinder, and CbmRichRingFinder::Init().
Referenced by Init().
void CbmRichReconstruction::InitFitter () private
Definition at line 190 of file CbmRichReconstruction.cxx.
View newest version in sPHENIX GitHub at line 190 of file CbmRichReconstruction.cxx
References FairLogger::endl(), FATAL, fFitterName, fRingFitter, and CbmRichConverter::Init().
Referenced by Init().
void CbmRichReconstruction::InitProjection () private
Definition at line 161 of file CbmRichReconstruction.cxx.
View newest version in sPHENIX GitHub at line 161 of file CbmRichReconstruction.cxx
References fProjectionProducer, and CbmRichProjectionProducerBase::Init().
Referenced by Init().
void CbmRichReconstruction::InitTrackAssign () private
Definition at line 218 of file CbmRichReconstruction.cxx.
View newest version in sPHENIX GitHub at line 218 of file CbmRichReconstruction.cxx
References FairLogger::endl(), FATAL, fRingTrackAssign, fTrackAssignName, and CbmRichRingTrackAssignBase::Init().
Referenced by Init().
CbmRichReconstruction& CbmRichReconstruction::operator= (const CbmRichReconstruction &) private
Assignment operator.
void CbmRichReconstruction::RunExtrapolation () private
Definition at line 230 of file CbmRichReconstruction.cxx.
View newest version in sPHENIX GitHub at line 230 of file CbmRichReconstruction.cxx
References CbmRichTrackExtrapolationBase::DoExtrapolation(), fGlobalTracks, fMinNofStsHits, fRichTrackParamZ, fTrackExtrapolation, and fZTrackExtrapolation.
Referenced by Exec().
void CbmRichReconstruction::RunFinder () private
Definition at line 241 of file CbmRichReconstruction.cxx.
View newest version in sPHENIX GitHub at line 241 of file CbmRichReconstruction.cxx
References CbmRichRingFinder::DoFind(), fRichHits, fRichProjections, fRichRings, and fRingFinder.
Referenced by Exec().
void CbmRichReconstruction::RunFitter () private
Definition at line 247 of file CbmRichReconstruction.cxx.
View newest version in sPHENIX GitHub at line 247 of file CbmRichReconstruction.cxx
References CbmRichConverter::CopyHitsToRingLight(), CbmRichConverter::CopyParamsToRing(), CbmRichRingFitterBase::DoFit(), fRichRings, and fRingFitter.
Referenced by Exec().
void CbmRichReconstruction::RunProjection () private
Definition at line 236 of file CbmRichReconstruction.cxx.
View newest version in sPHENIX GitHub at line 236 of file CbmRichReconstruction.cxx
References CbmRichProjectionProducerBase::DoProjection(), fProjectionProducer, and fRichProjections.
Referenced by Exec().
void CbmRichReconstruction::RunTrackAssign () private
Definition at line 261 of file CbmRichReconstruction.cxx.
View newest version in sPHENIX GitHub at line 261 of file CbmRichReconstruction.cxx
References CbmRichRingTrackAssignBase::DoAssign(), fRichProjections, fRichRings, and fRingTrackAssign.
Referenced by Exec().
void CbmRichReconstruction::SetExtrapolationName (const string & n) inline
Definition at line 74 of file CbmRichReconstruction.h.
View newest version in sPHENIX GitHub at line 74 of file CbmRichReconstruction.h
References fExtrapolationName, and n.
void CbmRichReconstruction::SetFinderName (const string & n) inline
Definition at line 76 of file CbmRichReconstruction.h.
View newest version in sPHENIX GitHub at line 76 of file CbmRichReconstruction.h
References fFinderName, and n.
void CbmRichReconstruction::SetFitterName (const string & n) inline
Definition at line 77 of file CbmRichReconstruction.h.
View newest version in sPHENIX GitHub at line 77 of file CbmRichReconstruction.h
References fFitterName, and n.
void CbmRichReconstruction::SetMinNofStsHits (Int_t minNofStsHits) inline
Set minimum number of STS hits.
Parameters
[in] minNofStsHits minimum number of STS hits.
Definition at line 90 of file CbmRichReconstruction.h.
View newest version in sPHENIX GitHub at line 90 of file CbmRichReconstruction.h
References fMinNofStsHits.
void CbmRichReconstruction::SetParContainers () virtual
Inherited from FairTask.
Reimplemented from FairTask.
Definition at line 86 of file CbmRichReconstruction.cxx.
View newest version in sPHENIX GitHub at line 86 of file CbmRichReconstruction.cxx
References FairLogger::endl(), FATAL, fProjectionName, fProjectionProducer, and CbmRichProjectionProducerBase::SetParContainers().
void CbmRichReconstruction::SetProjectionName (const string & n) inline
Definition at line 75 of file CbmRichReconstruction.h.
View newest version in sPHENIX GitHub at line 75 of file CbmRichReconstruction.h
References fProjectionName, and n.
void CbmRichReconstruction::SetRunExtrapolation (bool b) inline
Definition at line 68 of file CbmRichReconstruction.h.
View newest version in sPHENIX GitHub at line 68 of file CbmRichReconstruction.h
References fRunExtrapolation.
void CbmRichReconstruction::SetRunFinder (bool b) inline
Definition at line 70 of file CbmRichReconstruction.h.
View newest version in sPHENIX GitHub at line 70 of file CbmRichReconstruction.h
References fRunFinder.
void CbmRichReconstruction::SetRunFitter (bool b) inline
Definition at line 71 of file CbmRichReconstruction.h.
View newest version in sPHENIX GitHub at line 71 of file CbmRichReconstruction.h
References fRunFitter.
void CbmRichReconstruction::SetRunProjection (bool b) inline
Definition at line 69 of file CbmRichReconstruction.h.
View newest version in sPHENIX GitHub at line 69 of file CbmRichReconstruction.h
References fRunProjection.
void CbmRichReconstruction::SetRunTrackAssign (bool b) inline
Definition at line 72 of file CbmRichReconstruction.h.
View newest version in sPHENIX GitHub at line 72 of file CbmRichReconstruction.h
References fRunTrackAssign.
void CbmRichReconstruction::SetTrackAssignName (const string & n) inline
Definition at line 78 of file CbmRichReconstruction.h.
View newest version in sPHENIX GitHub at line 78 of file CbmRichReconstruction.h
References fTrackAssignName, and n.
void CbmRichReconstruction::SetZTrackExtrapolation (Double_t z) inline
Set Z coordinate where STS tracks will be extrapolated.
Parameters
[in] z Z coordinate.
Definition at line 84 of file CbmRichReconstruction.h.
View newest version in sPHENIX GitHub at line 84 of file CbmRichReconstruction.h
References fZTrackExtrapolation, and z.
Member Data Documentation
string CbmRichReconstruction::fExtrapolationName private
Definition at line 113 of file CbmRichReconstruction.h.
View newest version in sPHENIX GitHub at line 113 of file CbmRichReconstruction.h
Referenced by InitExtrapolation(), and SetExtrapolationName().
string CbmRichReconstruction::fFinderName private
Definition at line 115 of file CbmRichReconstruction.h.
View newest version in sPHENIX GitHub at line 115 of file CbmRichReconstruction.h
Referenced by InitFinder(), and SetFinderName().
string CbmRichReconstruction::fFitterName private
Definition at line 116 of file CbmRichReconstruction.h.
View newest version in sPHENIX GitHub at line 116 of file CbmRichReconstruction.h
Referenced by InitFitter(), and SetFitterName().
TClonesArray* CbmRichReconstruction::fGlobalTracks private
Definition at line 97 of file CbmRichReconstruction.h.
View newest version in sPHENIX GitHub at line 97 of file CbmRichReconstruction.h
Referenced by Init(), and RunExtrapolation().
Int_t CbmRichReconstruction::fMinNofStsHits private
Definition at line 120 of file CbmRichReconstruction.h.
View newest version in sPHENIX GitHub at line 120 of file CbmRichReconstruction.h
Referenced by RunExtrapolation(), and SetMinNofStsHits().
string CbmRichReconstruction::fProjectionName private
Definition at line 114 of file CbmRichReconstruction.h.
View newest version in sPHENIX GitHub at line 114 of file CbmRichReconstruction.h
Referenced by SetParContainers(), and SetProjectionName().
CbmRichProjectionProducerBase* CbmRichReconstruction::fProjectionProducer private
Definition at line 102 of file CbmRichReconstruction.h.
View newest version in sPHENIX GitHub at line 102 of file CbmRichReconstruction.h
Referenced by InitExtrapolation(), InitProjection(), RunProjection(), SetParContainers(), and ~CbmRichReconstruction().
TClonesArray* CbmRichReconstruction::fRichHits private
Definition at line 93 of file CbmRichReconstruction.h.
View newest version in sPHENIX GitHub at line 93 of file CbmRichReconstruction.h
Referenced by Init(), and RunFinder().
TClonesArray* CbmRichReconstruction::fRichProjections private
Definition at line 95 of file CbmRichReconstruction.h.
View newest version in sPHENIX GitHub at line 95 of file CbmRichReconstruction.h
Referenced by Init(), RunFinder(), RunProjection(), and RunTrackAssign().
TClonesArray* CbmRichReconstruction::fRichRings private
Definition at line 94 of file CbmRichReconstruction.h.
View newest version in sPHENIX GitHub at line 94 of file CbmRichReconstruction.h
Referenced by Init(), RunFinder(), RunFitter(), and RunTrackAssign().
TClonesArray* CbmRichReconstruction::fRichTrackParamZ private
Definition at line 96 of file CbmRichReconstruction.h.
View newest version in sPHENIX GitHub at line 96 of file CbmRichReconstruction.h
Referenced by Init(), and RunExtrapolation().
CbmRichRingFinder* CbmRichReconstruction::fRingFinder private
Definition at line 99 of file CbmRichReconstruction.h.
View newest version in sPHENIX GitHub at line 99 of file CbmRichReconstruction.h
Referenced by InitFinder(), RunFinder(), and ~CbmRichReconstruction().
CbmRichRingFitterBase* CbmRichReconstruction::fRingFitter private
Definition at line 100 of file CbmRichReconstruction.h.
View newest version in sPHENIX GitHub at line 100 of file CbmRichReconstruction.h
Referenced by InitFitter(), RunFitter(), and ~CbmRichReconstruction().
CbmRichRingTrackAssignBase* CbmRichReconstruction::fRingTrackAssign private
Definition at line 103 of file CbmRichReconstruction.h.
View newest version in sPHENIX GitHub at line 103 of file CbmRichReconstruction.h
Referenced by InitTrackAssign(), and RunTrackAssign().
bool CbmRichReconstruction::fRunExtrapolation private
Definition at line 106 of file CbmRichReconstruction.h.
View newest version in sPHENIX GitHub at line 106 of file CbmRichReconstruction.h
Referenced by Exec(), Init(), and SetRunExtrapolation().
bool CbmRichReconstruction::fRunFinder private
Definition at line 108 of file CbmRichReconstruction.h.
View newest version in sPHENIX GitHub at line 108 of file CbmRichReconstruction.h
Referenced by Exec(), Init(), and SetRunFinder().
bool CbmRichReconstruction::fRunFitter private
Definition at line 109 of file CbmRichReconstruction.h.
View newest version in sPHENIX GitHub at line 109 of file CbmRichReconstruction.h
Referenced by Exec(), Init(), and SetRunFitter().
bool CbmRichReconstruction::fRunProjection private
Definition at line 107 of file CbmRichReconstruction.h.
View newest version in sPHENIX GitHub at line 107 of file CbmRichReconstruction.h
Referenced by Exec(), Init(), and SetRunProjection().
bool CbmRichReconstruction::fRunTrackAssign private
Definition at line 110 of file CbmRichReconstruction.h.
View newest version in sPHENIX GitHub at line 110 of file CbmRichReconstruction.h
Referenced by Exec(), Init(), and SetRunTrackAssign().
string CbmRichReconstruction::fTrackAssignName private
Definition at line 117 of file CbmRichReconstruction.h.
View newest version in sPHENIX GitHub at line 117 of file CbmRichReconstruction.h
Referenced by InitTrackAssign(), and SetTrackAssignName().
CbmRichTrackExtrapolationBase* CbmRichReconstruction::fTrackExtrapolation private
Definition at line 101 of file CbmRichReconstruction.h.
View newest version in sPHENIX GitHub at line 101 of file CbmRichReconstruction.h
Referenced by InitExtrapolation(), RunExtrapolation(), and ~CbmRichReconstruction().
Double_t CbmRichReconstruction::fZTrackExtrapolation private
Definition at line 119 of file CbmRichReconstruction.h.
View newest version in sPHENIX GitHub at line 119 of file CbmRichReconstruction.h
Referenced by RunExtrapolation(), and SetZTrackExtrapolation().
The documentation for this class was generated from the following files:
EicRoot/blob/master/rich/CbmRichReconstruction.h
EicRoot/blob/master/rich/CbmRichReconstruction.cxx