EIC Software: FairDbResultAgg Class Reference
FairDbResultAgg Class Reference
#include <EicRoot/blob/master/dbase/dbInterface/FairDbResult.h>
Public Member Functions
FairDbResultAgg (const string &tableName="Unknown", const FairDbTableRow *tableRow=0, FairDbCache *cache=0, const FairDbValidityRecBuilder *vrecBuilder=0, const FairDbProxy *proxy=0, const string &sqlQualifiers="")
virtual ~FairDbResultAgg ()
virtual FairDbResultKey * CreateKey () const
virtual UInt_t GetNumAggregates () const
virtual UInt_t GetNumRows () const
virtual const FairDbTableRow * GetTableRow (UInt_t row) const
virtual const FairDbValidityRec & GetValidityRec (const FairDbTableRow *row=0) const
virtual Bool_t Satisfies (const string &sqlQualifiers)
virtual void Streamer (FairDbBinaryFile &bf)
Public Member Functions inherited from FairDbResult
FairDbResult (FairDbResultSet *resultSet=0, const FairDbValidityRec *vrec=0, const string &sqlQualifiers="")
FairDbResult (const FairDbResult &)
virtual ~FairDbResult ()
virtual Bool_t CanReuse () const
virtual Bool_t CanSave () const
virtual void Connect () const
virtual void Disconnect () const
Int_t GetID () const
virtual const FairDbResultKey * GetKey () const
virtual UInt_t GetNumClients () const
const string & GetSqlQualifiers () const
virtual const FairDbTableRow * GetTableRowByIndex (UInt_t index) const
virtual const FairDbValidityRec & GetValidityRecGlobal () const
Bool_t IsExtendedContext () const
virtual Bool_t Owns (const FairDbTableRow *table) const
Bool_t ResultsFromDb () const
virtual const string & TableName () const
virtual Bool_t CanDelete (const FairDbResult *res=0)
virtual Bool_t Satisfies (const ValContext &vc, const FairDb::Task &task)
virtual Bool_t Satisfies (const FairDbValidityRec &, const string &="")
virtual void DeRegisterKey ()
virtual void RegisterKey ()
virtual void SetCanReuse (Bool_t reuse)
void CaptureExceptionLog (UInt_t startFrom)
Private Attributes
std::vector< const FairDbResult * > fResults
std::vector< const
FairDbTableRow * > fRowKeys
UInt_t fSize
Additional Inherited Members
Protected Member Functions inherited from FairDbResult
void SetResultsFromDb ()
void BuildLookUpTable () const
Bool_t LookUpBuilt () const
virtual void SetTableName (const string &tableName)
virtual void SetValidityRec (const FairDbValidityRec &vRec)
Detailed Description
Definition at line 276 of file FairDbResult.h.
View newest version in sPHENIX GitHub at line 276 of file FairDbResult.h
Constructor & Destructor Documentation
FairDbResultAgg::FairDbResultAgg (const string & tableName = "Unknown", const FairDbTableRow * tableRow = 0, FairDbCache * cache = 0, const FairDbValidityRecBuilder * vrecBuilder = 0, const FairDbProxy * proxy = 0, const string & sqlQualifiers = "")
FairDbResultAgg::~FairDbResultAgg () virtual
Definition at line 681 of file FairDbResult.cxx.
View newest version in sPHENIX GitHub at line 681 of file FairDbResult.cxx
Member Function Documentation
FairDbResultKey * FairDbResultAgg::CreateKey () const virtual
Implements FairDbResult.
Definition at line 691 of file FairDbResult.cxx.
View newest version in sPHENIX GitHub at line 691 of file FairDbResult.cxx
References FairDbResultKey::AddVRecKey(), FairDbResult::CreateKey(), FairDbValidityRec::GetCreationDate(), FairDbValidityRec::GetSeqNo(), and FairDbResult::GetValidityRec().
virtual UInt_t FairDbResultAgg::GetNumAggregates () const inline virtual
Implements FairDbResult.
Definition at line 294 of file FairDbResult.h.
View newest version in sPHENIX GitHub at line 294 of file FairDbResult.h
References fResults.
virtual UInt_t FairDbResultAgg::GetNumRows () const inline virtual
Implements FairDbResult.
Definition at line 297 of file FairDbResult.h.
View newest version in sPHENIX GitHub at line 297 of file FairDbResult.h
References fSize.
const FairDbTableRow * FairDbResultAgg::GetTableRow (UInt_t row) const virtual
Implements FairDbResult.
Definition at line 721 of file FairDbResult.cxx.
View newest version in sPHENIX GitHub at line 721 of file FairDbResult.cxx
const FairDbValidityRec & FairDbResultAgg::GetValidityRec (const FairDbTableRow * row = 0) const virtual
Reimplemented from FairDbResult.
Definition at line 729 of file FairDbResult.cxx.
View newest version in sPHENIX GitHub at line 729 of file FairDbResult.cxx
References FairDbTableRow::GetOwner(), and FairDbResult::GetValidityRecGlobal().
Bool_t FairDbResultAgg::Satisfies (const string & sqlQualifiers) virtual
Reimplemented from FairDbResult.
Definition at line 739 of file FairDbResult.cxx.
View newest version in sPHENIX GitHub at line 739 of file FairDbResult.cxx
References FairDbResult::CanReuse(), and FairDbResult::GetSqlQualifiers().
void FairDbResultAgg::Streamer (FairDbBinaryFile & bf) virtual
Reimplemented from FairDbResult.
Definition at line 750 of file FairDbResult.cxx.
View newest version in sPHENIX GitHub at line 750 of file FairDbResult.cxx
References FairDbResult::GetValidityRecGlobal(), and FairDbValidityRec::IsGap().
Member Data Documentation
std::vector<const FairDbResult*> FairDbResultAgg::fResults private
Definition at line 310 of file FairDbResult.h.
View newest version in sPHENIX GitHub at line 310 of file FairDbResult.h
Referenced by GetNumAggregates().
std::vector<const FairDbTableRow*> FairDbResultAgg::fRowKeys private
Definition at line 311 of file FairDbResult.h.
View newest version in sPHENIX GitHub at line 311 of file FairDbResult.h
UInt_t FairDbResultAgg::fSize private
Definition at line 312 of file FairDbResult.h.
View newest version in sPHENIX GitHub at line 312 of file FairDbResult.h
Referenced by GetNumRows().
The documentation for this class was generated from the following files:
EicRoot/blob/master/dbase/dbInterface/FairDbResult.h
EicRoot/blob/master/dbase/dbInterface/FairDbResult.cxx