EIC Software: PndVertex Class Reference
PndVertex Class Reference
#include <EicRoot/blob/master/pnddata/TrackData/PndVertex.h>
Public Member Functions
PndVertex ()
PndVertex (double x, double y, double z)
virtual ~PndVertex ()
ClassDef (PndVertex, 0)
Public Member Functions inherited from FairHit
FairHit ()
FairHit (Int_t detID, TVector3 &pos, TVector3 &dpos, Int_t index)
FairHit (Int_t detID, TVector3 &pos, Int_t index)
virtual ~FairHit ()
Double_t GetDx () const
Double_t GetDy () const
Double_t GetDz () const
Int_t GetRefIndex () const
void PositionError (TVector3 &dpos) const
Int_t GetDetectorID () const
Double_t GetX () const
Double_t GetY () const
Double_t GetZ () const
void Position (TVector3 &pos) const
void SetDx (Double_t dx)
void SetDy (Double_t dy)
void SetDz (Double_t dz)
void SetDxyz (Double_t dx, Double_t dy, Double_t dz)
void SetPositionError (const TVector3 &dpos)
void SetRefIndex (Int_t index)
void SetDetectorID (Int_t detID)
void SetX (Double_t x)
void SetY (Double_t y)
void SetZ (Double_t z)
void SetXYZ (Double_t x, Double_t y, Double_t z)
void SetPosition (const TVector3 &pos)
virtual void Print (const Option_t *opt="") const
Public Member Functions inherited from FairTimeStamp
FairTimeStamp ()
FairTimeStamp (Double_t time)
FairTimeStamp (Double_t time, Double_t timeerror)
virtual ~FairTimeStamp ()
virtual Double_t GetTimeStamp () const
virtual Double_t GetTimeStampError () const
virtual FairLink GetEntryNr () const
virtual void SetTimeStamp (Double_t t)
virtual void SetTimeStampError (Double_t t)
virtual void SetEntryNr (FairLink entry)
virtual Int_t Compare (const TObject *obj) const
void Print (std::ostream &out=std::cout) const
virtual Bool_t IsSortable () const
virtual bool equal (FairTimeStamp *data)
Public Member Functions inherited from FairMultiLinkedData
FairMultiLinkedData ()
Default constructor.
FairMultiLinkedData (std::set< FairLink > links, Bool_t persistanceCheck=kTRUE)
Constructor.
FairMultiLinkedData (TString dataType, std::vector< Int_t > links, Int_t fileId=-1, Int_t evtId=-1, Bool_t persistanceCheck=kTRUE, Bool_t bypass=kFALSE, Float_t mult=1.0)
Constructor.
FairMultiLinkedData (Int_t dataType, std::vector< Int_t > links, Int_t fileId=-1, Int_t evtId=-1, Bool_t persistanceCheck=kTRUE, Bool_t bypass=kFALSE, Float_t mult=1.0)
Constructor.
virtual ~FairMultiLinkedData ()
virtual std::set< FairLink > GetLinks () const
returns stored links as FairLinks
virtual Int_t GetNLinks () const
returns the number of stored links
virtual FairLink GetLink (Int_t pos) const
returns the FairLink at the given position
virtual FairMultiLinkedData GetLinksWithType (Int_t type) const
Gives you a list of links which contain the given type.
TObject * GetData (FairLink &myLink)
Get the TObject the Link is pointing to.
virtual Int_t GetDefaultType ()
Bool_t GetPersistanceCheck ()
Returns the value of PersistanceCheck.
Int_t GetVerbose ()
Returns the verbosity level.
virtual void SetDefaultType (Int_t type)
virtual void SetPersistanceCheck (Bool_t check)
Controls if a persistance check of a link is done or not.
virtual void SetVerbose (Int_t level)
Sets the verbosity level.
virtual void SetLinks (FairMultiLinkedData links, Float_t mult=1.0)
Sets the links as vector of FairLink.
virtual void SetLink (FairLink link, Bool_t bypass=kFALSE, Float_t mult=1.0)
Sets the Links with a single FairLink.
virtual void AddLinks (FairMultiLinkedData links, Float_t mult=1.0)
Adds a List of FairLinks (FairMultiLinkedData) to fLinks.
virtual void AddLink (FairLink link, Bool_t bypass=kFALSE, Float_t mult=1.0)
Adds a FairLink link at the end of fLinks. If multi is kTRUE a link is allowed more than once otherwise it is stored only once.
virtual void InsertLink (FairLink link)
Inserts a link into the list of links without persistance checking.
virtual void AddAllWeights (Double_t weight)
Adds weight to all Links.
virtual void SetAllWeights (Double_t weight)
Sets a common weight for Links.
virtual void MultiplyAllWeights (Double_t weight)
Multiplies all Links with weight.
virtual Bool_t IsLinkInList (FairLink link)
Test if a given link is in fLinks.
virtual Bool_t IsLinkInList (Int_t type, Int_t index)
Same as IsLinkInList(FairLink) just with type and index given separately.
virtual Int_t LinkPosInList (FairLink link)
returns position of link in fLinks. If it is not in the list -1 is returned
virtual Int_t LinkPosInList (Int_t type, Int_t index)
Same as LinkPosInList(FairLink)
virtual void DeleteLink (FairLink link)
Deletes a link ouf of fLinks.
virtual void DeleteLink (Int_t type, Int_t index)
Deletes a link ouf of fLinks.
virtual void Reset ()
virtual void ResetLinks ()
Clears fLinks.
void Print (std::ostream &out=std::cout) const
Output.
Additional Inherited Members
Protected Member Functions inherited from FairHit
ClassDef (FairHit, 2)
Protected Attributes inherited from FairHit
Double32_t fDx
Double32_t fDy
Double32_t fDz
Errors of position [cm].
Int_t fRefIndex
Index of FairMCPoint for this hit.
Int_t fDetectorID
Detector unique identifier.
Double32_t fX
Double32_t fY
Double32_t fZ
Position of hit [cm].
Detailed Description
Definition at line 13 of file PndVertex.h.
View newest version in sPHENIX GitHub at line 13 of file PndVertex.h
Constructor & Destructor Documentation
PndVertex::PndVertex ()
Definition at line 10 of file PndVertex.cxx.
View newest version in sPHENIX GitHub at line 10 of file PndVertex.cxx
PndVertex::PndVertex (double x, double y, double z) inline
Definition at line 16 of file PndVertex.h.
View newest version in sPHENIX GitHub at line 16 of file PndVertex.h
References FairHit::SetX(), FairHit::SetY(), and FairHit::SetZ().
PndVertex::~PndVertex () virtual
Definition at line 15 of file PndVertex.cxx.
View newest version in sPHENIX GitHub at line 15 of file PndVertex.cxx
Member Function Documentation
PndVertex::ClassDef (PndVertex , 0)
The documentation for this class was generated from the following files:
EicRoot/blob/master/pnddata/TrackData/PndVertex.h
EicRoot/blob/master/pnddata/TrackData/PndVertex.cxx