EIC Software: EicBeamLineElementMap Class Reference
EicBeamLineElementMap Class Reference
#include <EicRoot/blob/master/eic/field/EicBeamLineElementMap.h>
Public Member Functions
EicBeamLineElementMap (const char *fileName=0)
~EicBeamLineElementMap ()
int Initialize ()
int GetFieldValue (const double xx[], double B[]) const
void SetFieldScale (const double fieldScaler)
bool CapableToBuildYoke () const
TString GetDetectorName () const
int ConstructGeometry ()
TGeoVolume * GetYokeVolume () const
Public Member Functions inherited from EicMagneticFieldMap
EicMagneticFieldMap (const char *fileName=0, TGeoMatrix *transformation=0, TGeoShape *shape=0, int color=_DEFAULT_YOKE_COLOR_)
~EicMagneticFieldMap ()
bool Initialized () const
TGeoShape * GetShape () const
virtual bool Contains (const double xx[]) const
const TString & GetFileName () const
void SetYokeColor (int color)
int GetYokeColor () const
Private Member Functions
ClassDef (EicBeamLineElementMap, 4)
yoke TGeo volume
Private Attributes
Mgrid * mGrid
Double_t mLength
structure describing the magnetic field map in HTC-style
Double_t mAngle
Double_t mBore
Double_t mScale
TGeoVolume * mYoke
Additional Inherited Members
Protected Member Functions inherited from EicMagneticFieldMap
const char * BasenameWrapper (const char *fname) const
int GetMD5Signature (unsigned char output[])
Protected Attributes inherited from EicMagneticFieldMap
UInt_t mMD5BufferSize
UChar_t * mMD5Signature
Bool_t mInitialized
TGeoMatrix * mTransformation
indicates whether Initialize() call was made or not
TGeoShape * mShape
Int_t mColor
Detailed Description
Definition at line 15 of file EicBeamLineElementMap.h.
View newest version in sPHENIX GitHub at line 15 of file EicBeamLineElementMap.h
Constructor & Destructor Documentation
EicBeamLineElementMap::EicBeamLineElementMap (const char * fileName = 0) inline
Definition at line 20 of file EicBeamLineElementMap.h.
View newest version in sPHENIX GitHub at line 20 of file EicBeamLineElementMap.h
EicBeamLineElementMap::~EicBeamLineElementMap () inline
Definition at line 25 of file EicBeamLineElementMap.h.
View newest version in sPHENIX GitHub at line 25 of file EicBeamLineElementMap.h
Member Function Documentation
bool EicBeamLineElementMap::CapableToBuildYoke () const inline virtual
Reimplemented from EicMagneticFieldMap.
Definition at line 35 of file EicBeamLineElementMap.h.
View newest version in sPHENIX GitHub at line 35 of file EicBeamLineElementMap.h
EicBeamLineElementMap::ClassDef (EicBeamLineElementMap , 4) private
yoke TGeo volume
int EicBeamLineElementMap::ConstructGeometry () virtual
Reimplemented from EicMagneticFieldMap.
Definition at line 258 of file EicBeamLineElementMap.cxx.
View newest version in sPHENIX GitHub at line 258 of file EicBeamLineElementMap.cxx
References _EXTRA_BORE_WIDTH_, _IRON_, _VACUUM_, GetDetectorName(), EicMediaHub::GetMedium(), EicMagneticFieldMap::GetYokeColor(), EicMediaHub::Init(), mBore, mLength, EicMagneticFieldMap::mTransformation, mYoke, and Acts::Test::origin().
TString EicBeamLineElementMap::GetDetectorName () const inline virtual
Reimplemented from EicMagneticFieldMap.
Definition at line 36 of file EicBeamLineElementMap.h.
View newest version in sPHENIX GitHub at line 36 of file EicBeamLineElementMap.h
References _CSV_EXTENSION_, EicMagneticFieldMap::BasenameWrapper(), and EicMagneticFieldMap::GetFileName().
Referenced by ConstructGeometry().
int EicBeamLineElementMap::GetFieldValue (const double xx[], double B[]) const virtual
Implements EicMagneticFieldMap.
Definition at line 199 of file EicBeamLineElementMap.cxx.
View newest version in sPHENIX GitHub at line 199 of file EicBeamLineElementMap.cxx
References EicMagneticFieldMap::Contains(), exit(), Mgrid::getCartesianFieldValue(), mGrid, EicMagneticFieldMap::mTransformation, and printf().
TGeoVolume* EicBeamLineElementMap::GetYokeVolume () const inline virtual
Reimplemented from EicMagneticFieldMap.
Definition at line 41 of file EicBeamLineElementMap.h.
View newest version in sPHENIX GitHub at line 41 of file EicBeamLineElementMap.h
int EicBeamLineElementMap::Initialize () virtual
Reimplemented from EicMagneticFieldMap.
Definition at line 32 of file EicBeamLineElementMap.cxx.
View newest version in sPHENIX GitHub at line 32 of file EicBeamLineElementMap.cxx
References _CARTESIAN_, _FIELD_COMPONENT_VALUES_, MgridCell::B, Mgrid::cellPtrToLinear(), Mgrid::coordToCellPtr(), create_single_mgrid_header(), Acts::Test::dim, dx, dy, dz, ExpandedFileName(), EicMagneticFieldMap::GetFileName(), EicMagneticFieldMap::Initialize(), Mgrid::initializeAsSingleMgrid(), mAngle, Mgrid::markCellAsSafe(), max, mBore, mGrid, min, mLength, mScale, EicMagneticFieldMap::mShape, EicMagneticFieldMap::mTransformation, Acts::Test::origin(), printf(), rw, Mgrid::turnInterpolationOff(), XYZ, and z1.
void EicBeamLineElementMap::SetFieldScale (const double fieldScaler)
Definition at line 187 of file EicBeamLineElementMap.cxx.
View newest version in sPHENIX GitHub at line 187 of file EicBeamLineElementMap.cxx
References mScale.
Member Data Documentation
Double_t EicBeamLineElementMap::mAngle private
Definition at line 49 of file EicBeamLineElementMap.h.
View newest version in sPHENIX GitHub at line 49 of file EicBeamLineElementMap.h
Referenced by Initialize().
Double_t EicBeamLineElementMap::mBore private
Definition at line 50 of file EicBeamLineElementMap.h.
View newest version in sPHENIX GitHub at line 50 of file EicBeamLineElementMap.h
Referenced by ConstructGeometry(), and Initialize().
Mgrid* EicBeamLineElementMap::mGrid private
Definition at line 41 of file EicBeamLineElementMap.h.
View newest version in sPHENIX GitHub at line 41 of file EicBeamLineElementMap.h
Referenced by GetFieldValue(), and Initialize().
Double_t EicBeamLineElementMap::mLength private
structure describing the magnetic field map in HTC-style
Definition at line 48 of file EicBeamLineElementMap.h.
View newest version in sPHENIX GitHub at line 48 of file EicBeamLineElementMap.h
Referenced by ConstructGeometry(), and Initialize().
Double_t EicBeamLineElementMap::mScale private
Definition at line 51 of file EicBeamLineElementMap.h.
View newest version in sPHENIX GitHub at line 51 of file EicBeamLineElementMap.h
Referenced by Initialize(), and SetFieldScale().
TGeoVolume* EicBeamLineElementMap::mYoke private
Definition at line 53 of file EicBeamLineElementMap.h.
View newest version in sPHENIX GitHub at line 53 of file EicBeamLineElementMap.h
Referenced by ConstructGeometry().
The documentation for this class was generated from the following files:
EicRoot/blob/master/eic/field/EicBeamLineElementMap.h
EicRoot/blob/master/eic/field/EicBeamLineElementMap.cxx