EIC Software: TpcClusterizer Class Reference
TpcClusterizer Class Reference
#include <fun4all_coresoftware/blob/master/offline/packages/tpc/TpcClusterizer.h>
Public Member Functions
TpcClusterizer (const std::string &name="TpcClusterizer")
virtual ~TpcClusterizer ()
int InitRun (PHCompositeNode *topNode)
int process_event (PHCompositeNode *topNode)
int End (PHCompositeNode *topNode)
Called at the end of all processing.
void set_sector_fiducial_cut (const double cut)
void set_search_bins (const int bins)
Public Member Functions inherited from SubsysReco
virtual ~SubsysReco ()
virtual int EndRun (const int)
Called at the end of each run.
virtual int Init (PHCompositeNode *)
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
virtual void Print (const std::string &what="ALL") const
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Private Member Functions
bool is_local_maximum (int phi, int z, std::vector< std::vector< double >> &adcval)
bool is_in_sector_boundary (int phibin, int sector, PHG4CylinderCellGeom *layergeom)
void get_cluster (int phibin, int zbin, std::vector< std::vector< double >> &adcval, std::vector< ihit > &ihit_list)
void find_z_range (int phibin, int zbin, std::vector< std::vector< double >> &adcval, int &zdown, int &zup)
void find_phi_range (int phibin, int zbin, std::vector< std::vector< double >> &adcval, int &phidown, int &phiup)
void remove_hit (double adc, int phibin, int zbin, std::multimap< double, ihit > &all_hit_map, std::vector< std::vector< double >> &adcval)
void remove_hits (std::vector< ihit > &ihit_list, std::multimap< double, ihit > &all_hit_map, std::vector< std::vector< double >> &adcval)
void calc_cluster_parameter (std::vector< ihit > &ihit_list, int iclus, PHG4CylinderCellGeom *layergeom, TrkrHitSet *hitset)
void print_cluster (std::vector< ihit > &ihit_list)
Private Attributes
TrkrHitSetContainer * m_hits
TrkrClusterContainer * m_clusterlist
TrkrClusterHitAssoc * m_clusterhitassoc
double zz_shaping_correction
double pedestal
double SectorFiducialCut
int NSearch
int NPhiBinsMax
int NPhiBinsMin
int NZBinsMax
int NZBinsMin
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = INT_MAX - 10
}
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Detailed Description
Definition at line 19 of file TpcClusterizer.h.
View newest version in sPHENIX GitHub at line 19 of file TpcClusterizer.h
Constructor & Destructor Documentation
TpcClusterizer::TpcClusterizer (const std::string & name = "TpcClusterizer")
Definition at line 50 of file TpcClusterizer.cc.
View newest version in sPHENIX GitHub at line 50 of file TpcClusterizer.cc
virtual TpcClusterizer::~TpcClusterizer () inline virtual
Definition at line 23 of file TpcClusterizer.h.
View newest version in sPHENIX GitHub at line 23 of file TpcClusterizer.h
Member Function Documentation
void TpcClusterizer::calc_cluster_parameter (std::vector< ihit > & ihit_list, int iclus, PHG4CylinderCellGeom * layergeom, TrkrHitSet * hitset) private
HERE TODO
Definition at line 149 of file TpcClusterizer.cc.
View newest version in sPHENIX GitHub at line 149 of file TpcClusterizer.cc
References TrkrClusterHitAssoc::addAssoc(), cos(), DIM, TrkrClusterContainer::findOrAddCluster(), TpcDefs::genClusKey(), TpcDefs::genHitKey(), PHG4CylinderCellGeom::get_phicenter(), PHG4CylinderCellGeom::get_phistep(), PHG4CylinderCellGeom::get_radius(), PHG4CylinderCellGeom::get_zcenter(), PHG4CylinderCellGeom::get_zstep(), TrkrHitSet::getHitSetKey(), m_clusterhitassoc, m_clusterlist, square(), z, and zz_shaping_correction.
Referenced by process_event().
int TpcClusterizer::End (PHCompositeNode *) virtual
Called at the end of all processing.
Reimplemented from SubsysReco.
Definition at line 687 of file TpcClusterizer.cc.
View newest version in sPHENIX GitHub at line 687 of file TpcClusterizer.cc
References Fun4AllReturnCodes::EVENT_OK.
void TpcClusterizer::find_phi_range (int phibin, int zbin, std::vector< std::vector< double >> & adcval, int & phidown, int & phiup) private
Definition at line 389 of file TpcClusterizer.cc.
View newest version in sPHENIX GitHub at line 389 of file TpcClusterizer.cc
References NPhiBinsMax, and Fun4AllBase::Verbosity().
Referenced by get_cluster().
void TpcClusterizer::find_z_range (int phibin, int zbin, std::vector< std::vector< double >> & adcval, int & zdown, int & zup) private
Definition at line 335 of file TpcClusterizer.cc.
View newest version in sPHENIX GitHub at line 335 of file TpcClusterizer.cc
References NZBinsMax, and Fun4AllBase::Verbosity().
Referenced by get_cluster().
void TpcClusterizer::get_cluster (int phibin, int zbin, std::vector< std::vector< double >> & adcval, std::vector< ihit > & ihit_list) private
Definition at line 445 of file TpcClusterizer.cc.
View newest version in sPHENIX GitHub at line 445 of file TpcClusterizer.cc
References find_phi_range(), find_z_range(), and Fun4AllBase::Verbosity().
Referenced by process_event().
int TpcClusterizer::InitRun (PHCompositeNode *) virtual
Called for first event when run number is known. Typically this is where you may want to fetch data from database, because you know the run number.
Reimplemented from SubsysReco.
Definition at line 468 of file TpcClusterizer.cc.
View newest version in sPHENIX GitHub at line 468 of file TpcClusterizer.cc
References Fun4AllReturnCodes::ABORTRUN, PHCompositeNode::addNode(), Fun4AllReturnCodes::EVENT_OK, PHNodeIterator::findFirst(), and PHWHERE.
bool TpcClusterizer::is_in_sector_boundary (int phibin, int sector, PHG4CylinderCellGeom * layergeom) private
Definition at line 91 of file TpcClusterizer.cc.
View newest version in sPHENIX GitHub at line 91 of file TpcClusterizer.cc
References PHG4CylinderCellGeom::get_phibins(), PHG4CylinderCellGeom::get_radius(), M_PI, and SectorFiducialCut.
bool TpcClusterizer::is_local_maximum (int phi, int z, std::vector< std::vector< double >> & adcval) private
Definition at line 67 of file TpcClusterizer.cc.
View newest version in sPHENIX GitHub at line 67 of file TpcClusterizer.cc
References NPhiBinsMax, NPhiBinsMin, NSearch, NZBinsMax, and NZBinsMin.
void TpcClusterizer::print_cluster (std::vector< ihit > & ihit_list) private
Definition at line 325 of file TpcClusterizer.cc.
View newest version in sPHENIX GitHub at line 325 of file TpcClusterizer.cc
References Fun4AllBase::Verbosity().
int TpcClusterizer::process_event (PHCompositeNode *) virtual
Called for each event. This is where you do the real work.
Reimplemented from SubsysReco.
Definition at line 519 of file TpcClusterizer.cc.
View newest version in sPHENIX GitHub at line 519 of file TpcClusterizer.cc
References Fun4AllReturnCodes::ABORTRUN, calc_cluster_parameter(), Fun4AllReturnCodes::EVENT_OK, PHNodeIterator::findFirst(), get_cluster(), PHG4CylinderCellGeom::get_phibins(), PHG4CylinderCellGeom::get_zbins(), TrkrHitSet::getHits(), TrkrHitSetContainer::getHitSets(), TrkrDefs::getLayer(), PHG4CylinderCellGeomContainer::GetLayerCellGeom(), TpcDefs::getPad(), TpcDefs::getSectorId(), TpcDefs::getSide(), TpcDefs::getTBin(), m_clusterhitassoc, m_clusterlist, m_hits, NPhiBinsMax, NPhiBinsMin, NZBinsMax, NZBinsMin, pedestal, PHWHERE, remove_hits(), TrkrHitSet::size(), TrkrDefs::tpcId, and Fun4AllBase::Verbosity().
void TpcClusterizer::remove_hit (double adc, int phibin, int zbin, std::multimap< double, ihit > & all_hit_map, std::vector< std::vector< double >> & adcval) private
Definition at line 122 of file TpcClusterizer.cc.
View newest version in sPHENIX GitHub at line 122 of file TpcClusterizer.cc
References it, and Fun4AllBase::Verbosity().
Referenced by remove_hits().
void TpcClusterizer::remove_hits (std::vector< ihit > & ihit_list, std::multimap< double, ihit > & all_hit_map, std::vector< std::vector< double >> & adcval) private
Definition at line 137 of file TpcClusterizer.cc.
View newest version in sPHENIX GitHub at line 137 of file TpcClusterizer.cc
References remove_hit(), and Fun4AllBase::Verbosity().
Referenced by process_event().
void TpcClusterizer::set_search_bins (const int bins) inline
Definition at line 30 of file TpcClusterizer.h.
View newest version in sPHENIX GitHub at line 30 of file TpcClusterizer.h
References charm_jet_strange_helicity::bins, and NSearch.
void TpcClusterizer::set_sector_fiducial_cut (const double cut) inline
Definition at line 29 of file TpcClusterizer.h.
View newest version in sPHENIX GitHub at line 29 of file TpcClusterizer.h
References SectorFiducialCut.
Member Data Documentation
TrkrClusterHitAssoc* TpcClusterizer::m_clusterhitassoc private
Definition at line 45 of file TpcClusterizer.h.
View newest version in sPHENIX GitHub at line 45 of file TpcClusterizer.h
Referenced by calc_cluster_parameter(), and process_event().
TrkrClusterContainer* TpcClusterizer::m_clusterlist private
Definition at line 44 of file TpcClusterizer.h.
View newest version in sPHENIX GitHub at line 44 of file TpcClusterizer.h
Referenced by calc_cluster_parameter(), and process_event().
TrkrHitSetContainer* TpcClusterizer::m_hits private
Definition at line 43 of file TpcClusterizer.h.
View newest version in sPHENIX GitHub at line 43 of file TpcClusterizer.h
Referenced by process_event().
int TpcClusterizer::NPhiBinsMax private
Definition at line 53 of file TpcClusterizer.h.
View newest version in sPHENIX GitHub at line 53 of file TpcClusterizer.h
Referenced by find_phi_range(), is_local_maximum(), and process_event().
int TpcClusterizer::NPhiBinsMin private
Definition at line 54 of file TpcClusterizer.h.
View newest version in sPHENIX GitHub at line 54 of file TpcClusterizer.h
Referenced by is_local_maximum(), and process_event().
int TpcClusterizer::NSearch private
Definition at line 51 of file TpcClusterizer.h.
View newest version in sPHENIX GitHub at line 51 of file TpcClusterizer.h
Referenced by is_local_maximum(), and set_search_bins().
int TpcClusterizer::NZBinsMax private
Definition at line 55 of file TpcClusterizer.h.
View newest version in sPHENIX GitHub at line 55 of file TpcClusterizer.h
Referenced by find_z_range(), is_local_maximum(), and process_event().
int TpcClusterizer::NZBinsMin private
Definition at line 56 of file TpcClusterizer.h.
View newest version in sPHENIX GitHub at line 56 of file TpcClusterizer.h
Referenced by is_local_maximum(), and process_event().
double TpcClusterizer::pedestal private
Definition at line 48 of file TpcClusterizer.h.
View newest version in sPHENIX GitHub at line 48 of file TpcClusterizer.h
Referenced by process_event().
double TpcClusterizer::SectorFiducialCut private
Definition at line 50 of file TpcClusterizer.h.
View newest version in sPHENIX GitHub at line 50 of file TpcClusterizer.h
Referenced by is_in_sector_boundary(), and set_sector_fiducial_cut().
double TpcClusterizer::zz_shaping_correction private
Definition at line 47 of file TpcClusterizer.h.
View newest version in sPHENIX GitHub at line 47 of file TpcClusterizer.h
Referenced by calc_cluster_parameter().
The documentation for this class was generated from the following files:
fun4all_coresoftware/blob/master/offline/packages/tpc/TpcClusterizer.h
fun4all_coresoftware/blob/master/offline/packages/tpc/TpcClusterizer.cc