EIC Software: eASTRunAction Class Reference
eASTRunAction Class Reference
#include <east/blob/main/Core/include/eASTRunAction.hh>
Public Member Functions
eASTRunAction ()
virtual ~eASTRunAction ()
virtual G4Run * GenerateRun ()
virtual void BeginOfRunAction (const G4Run *)
virtual void EndOfRunAction (const G4Run *)
void SetVerbose (G4int)
void ListHistograms ()
G4bool Open (G4int)
G4bool SetAllPlotting (G4bool val=true)
G4bool SetPlotting (G4int, G4bool val=true)
void Flush ()
void Reset ()
G4int Create1D (G4String &, G4String &, G4int)
G4int Create1DForPlotter (G4String &, G4String &, G4bool)
G4bool Set1D (G4int, G4int, G4double, G4double, G4String &, G4String &, G4bool)
G4bool Set1DTitle (G4int, G4String &, G4String &, G4String &)
G4bool Set1DYAxisLog (G4int, G4bool)
G4int Create1P (G4String &, G4String &, G4int)
G4bool Set1P (G4int, G4double, G4double, G4String &, G4String &, G4String &, G4String &)
G4bool Set1PTitle (G4int, G4String &, G4String &, G4String &)
G4int NtupleColumn (G4String &, G4String &, G4String &, G4int)
void SetFileName (G4String &fn)
const G4String & GetFileName () const
G4int GetVerbose () const
void SetCarry (G4bool val=true)
G4bool GetCarry () const
Private Member Functions
void OpenFile ()
void DefineNTColumn ()
void MergeNtuple ()
Private Attributes
eASTRunActionMessenger * messenger
G4String fileName = "eASTOut"
G4bool fileOpen = false
G4int verbose = 0
G4bool ifCarry = false
G4int id_offset = 100
G4int id_factor = 100
std::map< G4int, eASTHistoType * > IDMap
std::map< G4int, eASTHistoType * > NTMap
Friends
class eASTRun
Detailed Description
Definition at line 53 of file eASTRunAction.hh.
View newest version in sPHENIX GitHub at line 53 of file eASTRunAction.hh
Constructor & Destructor Documentation
eASTRunAction::eASTRunAction ()
Definition at line 25 of file eASTRunAction.cc.
View newest version in sPHENIX GitHub at line 25 of file eASTRunAction.cc
References messenger, and verbose.
eASTRunAction::~eASTRunAction () virtual
Definition at line 38 of file eASTRunAction.cc.
View newest version in sPHENIX GitHub at line 38 of file eASTRunAction.cc
References messenger.
Member Function Documentation
void eASTRunAction::BeginOfRunAction (const G4Run * run) virtual
Definition at line 46 of file eASTRunAction.cc.
View newest version in sPHENIX GitHub at line 46 of file eASTRunAction.cc
References DefineNTColumn(), eASTUserActionDispatcher::GetRunActions(), eASTUserActionDispatcher::Instance(), and OpenFile().
G4int eASTRunAction::Create1D (G4String & mName, G4String & pName, G4int cn)
Definition at line 164 of file eASTRunAction.cc.
View newest version in sPHENIX GitHub at line 164 of file eASTRunAction.cc
References eASTHistoType::collID, and verbose.
Referenced by eASTRunActionMessenger::SetNewValue().
G4int eASTRunAction::Create1DForPlotter (G4String & mName, G4String & pName, G4bool)
Definition at line 193 of file eASTRunAction.cc.
View newest version in sPHENIX GitHub at line 193 of file eASTRunAction.cc
References eASTHistoType::collID, and verbose.
Referenced by eASTRunActionMessenger::SetNewValue().
G4int eASTRunAction::Create1P (G4String & mName, G4String & pName, G4int cn)
Definition at line 323 of file eASTRunAction.cc.
View newest version in sPHENIX GitHub at line 323 of file eASTRunAction.cc
References eASTHistoType::collID, and verbose.
Referenced by eASTRunActionMessenger::SetNewValue().
void eASTRunAction::DefineNTColumn () private
Definition at line 415 of file eASTRunAction.cc.
View newest version in sPHENIX GitHub at line 415 of file eASTRunAction.cc
Referenced by BeginOfRunAction().
void eASTRunAction::EndOfRunAction (const G4Run * run) virtual
Definition at line 77 of file eASTRunAction.cc.
View newest version in sPHENIX GitHub at line 77 of file eASTRunAction.cc
References Flush(), eASTUserActionDispatcher::GetRunActions(), ifCarry, and eASTUserActionDispatcher::Instance().
void eASTRunAction::Flush ()
Definition at line 91 of file eASTRunAction.cc.
View newest version in sPHENIX GitHub at line 91 of file eASTRunAction.cc
References fileName, fileOpen, MergeNtuple(), and verbose.
Referenced by EndOfRunAction(), and eASTRunActionMessenger::SetNewValue().
virtual G4Run* eASTRunAction::GenerateRun () inline virtual
Definition at line 60 of file eASTRunAction.hh.
View newest version in sPHENIX GitHub at line 60 of file eASTRunAction.hh
References eASTRun.
G4bool eASTRunAction::GetCarry () const inline
Definition at line 103 of file eASTRunAction.hh.
View newest version in sPHENIX GitHub at line 103 of file eASTRunAction.hh
References ifCarry.
Referenced by eASTRunActionMessenger::GetCurrentValue().
const G4String& eASTRunAction::GetFileName () const inline
Definition at line 97 of file eASTRunAction.hh.
View newest version in sPHENIX GitHub at line 97 of file eASTRunAction.hh
References fileName.
Referenced by eASTRunActionMessenger::GetCurrentValue().
G4int eASTRunAction::GetVerbose () const inline
Definition at line 99 of file eASTRunAction.hh.
View newest version in sPHENIX GitHub at line 99 of file eASTRunAction.hh
References verbose.
Referenced by eASTRunActionMessenger::GetCurrentValue().
void eASTRunAction::ListHistograms ()
Definition at line 111 of file eASTRunAction.cc.
View newest version in sPHENIX GitHub at line 111 of file eASTRunAction.cc
References IDMap.
Referenced by eASTRunActionMessenger::SetNewValue().
void eASTRunAction::MergeNtuple () private
Definition at line 441 of file eASTRunAction.cc.
View newest version in sPHENIX GitHub at line 441 of file eASTRunAction.cc
References in, charm_jet_tagging_optimization_study::target, and title().
Referenced by Flush().
G4int eASTRunAction::NtupleColumn (G4String & mName, G4String & pName, G4String & unit, G4int cn)
Definition at line 388 of file eASTRunAction.cc.
View newest version in sPHENIX GitHub at line 388 of file eASTRunAction.cc
References eASTHistoType::collID, and verbose.
Referenced by eASTRunActionMessenger::SetNewValue().
G4bool eASTRunAction::Open (G4int id)
Definition at line 126 of file eASTRunAction.cc.
View newest version in sPHENIX GitHub at line 126 of file eASTRunAction.cc
References IDMap.
Referenced by eASTRunActionMessenger::SetNewValue().
void eASTRunAction::OpenFile () private
Definition at line 66 of file eASTRunAction.cc.
View newest version in sPHENIX GitHub at line 66 of file eASTRunAction.cc
References fileName, fileOpen, and verbose.
Referenced by BeginOfRunAction().
void eASTRunAction::Reset ()
G4bool eASTRunAction::Set1D (G4int id0, G4int nBin, G4double valMin, G4double valMax, G4String & unit, G4String & schem, G4bool logVal)
Definition at line 246 of file eASTRunAction.cc.
View newest version in sPHENIX GitHub at line 246 of file eASTRunAction.cc
References verbose.
Referenced by eASTRunActionMessenger::SetNewValue().
G4bool eASTRunAction::Set1DTitle (G4int id, G4String & title, G4String & x_axis, G4String & y_axis)
Definition at line 293 of file eASTRunAction.cc.
View newest version in sPHENIX GitHub at line 293 of file eASTRunAction.cc
Referenced by eASTRunActionMessenger::SetNewValue().
G4bool eASTRunAction::Set1DYAxisLog (G4int id0, G4bool val)
Definition at line 306 of file eASTRunAction.cc.
View newest version in sPHENIX GitHub at line 306 of file eASTRunAction.cc
Referenced by eASTRunActionMessenger::SetNewValue().
G4bool eASTRunAction::Set1P (G4int id, G4double valYMin, G4double valYMax, G4String & unit, G4String & funcX, G4String & funcY, G4String & schem)
Definition at line 348 of file eASTRunAction.cc.
View newest version in sPHENIX GitHub at line 348 of file eASTRunAction.cc
References verbose.
Referenced by eASTRunActionMessenger::SetNewValue().
G4bool eASTRunAction::Set1PTitle (G4int id, G4String & title, G4String & x_axis, G4String & y_axis)
Definition at line 373 of file eASTRunAction.cc.
View newest version in sPHENIX GitHub at line 373 of file eASTRunAction.cc
Referenced by eASTRunActionMessenger::SetNewValue().
G4bool eASTRunAction::SetAllPlotting (G4bool val = true)
Definition at line 135 of file eASTRunAction.cc.
View newest version in sPHENIX GitHub at line 135 of file eASTRunAction.cc
References Acts::IntegrationTest::valid().
Referenced by eASTRunActionMessenger::SetNewValue().
void eASTRunAction::SetCarry (G4bool val = true) inline
Definition at line 101 of file eASTRunAction.hh.
View newest version in sPHENIX GitHub at line 101 of file eASTRunAction.hh
References ifCarry.
Referenced by eASTRunActionMessenger::SetNewValue().
void eASTRunAction::SetFileName (G4String & fn) inline
Definition at line 95 of file eASTRunAction.hh.
View newest version in sPHENIX GitHub at line 95 of file eASTRunAction.hh
References fileName.
Referenced by eASTRunActionMessenger::SetNewValue().
G4bool eASTRunAction::SetPlotting (G4int id, G4bool val = true)
Definition at line 146 of file eASTRunAction.cc.
View newest version in sPHENIX GitHub at line 146 of file eASTRunAction.cc
Referenced by eASTRunActionMessenger::SetNewValue().
void eASTRunAction::SetVerbose (G4int val)
Definition at line 104 of file eASTRunAction.cc.
View newest version in sPHENIX GitHub at line 104 of file eASTRunAction.cc
References verbose.
Referenced by eASTRunActionMessenger::SetNewValue().
Friends And Related Function Documentation
friend class eASTRun friend
Definition at line 55 of file eASTRunAction.hh.
View newest version in sPHENIX GitHub at line 55 of file eASTRunAction.hh
Referenced by GenerateRun().
Member Data Documentation
G4String eASTRunAction::fileName = "eASTOut" private
Definition at line 107 of file eASTRunAction.hh.
View newest version in sPHENIX GitHub at line 107 of file eASTRunAction.hh
Referenced by Flush(), GetFileName(), OpenFile(), and SetFileName().
G4bool eASTRunAction::fileOpen = false private
Definition at line 108 of file eASTRunAction.hh.
View newest version in sPHENIX GitHub at line 108 of file eASTRunAction.hh
Referenced by Flush(), and OpenFile().
G4int eASTRunAction::id_factor = 100 private
Definition at line 112 of file eASTRunAction.hh.
View newest version in sPHENIX GitHub at line 112 of file eASTRunAction.hh
G4int eASTRunAction::id_offset = 100 private
Definition at line 111 of file eASTRunAction.hh.
View newest version in sPHENIX GitHub at line 111 of file eASTRunAction.hh
std::map<G4int,eASTHistoType*> eASTRunAction::IDMap private
Definition at line 115 of file eASTRunAction.hh.
View newest version in sPHENIX GitHub at line 115 of file eASTRunAction.hh
Referenced by ListHistograms(), Open(), and eASTRun::RecordEvent().
G4bool eASTRunAction::ifCarry = false private
Definition at line 110 of file eASTRunAction.hh.
View newest version in sPHENIX GitHub at line 110 of file eASTRunAction.hh
Referenced by EndOfRunAction(), GetCarry(), and SetCarry().
eASTRunActionMessenger* eASTRunAction::messenger private
Definition at line 66 of file eASTRunAction.hh.
View newest version in sPHENIX GitHub at line 66 of file eASTRunAction.hh
Referenced by eASTRunAction(), and ~eASTRunAction().
std::map<G4int,eASTHistoType*> eASTRunAction::NTMap private
Definition at line 116 of file eASTRunAction.hh.
View newest version in sPHENIX GitHub at line 116 of file eASTRunAction.hh
Referenced by eASTRun::RecordEvent().
G4int eASTRunAction::verbose = 0 private
Definition at line 109 of file eASTRunAction.hh.
View newest version in sPHENIX GitHub at line 109 of file eASTRunAction.hh
Referenced by eASTRunAction(), Flush(), GetVerbose(), OpenFile(), and SetVerbose().
The documentation for this class was generated from the following files:
east/blob/main/Core/include/eASTRunAction.hh
east/blob/main/Core/src/eASTRunAction.cc