EIC Software: PndFileNameCreator Class Reference
PndFileNameCreator Class Reference
A simple class which adds the corresponding file extensions to a given base class.
#include <EicRoot/blob/master/PndTools/generalTools/PndFileNameCreator.h>
Public Member Functions
PndFileNameCreator ()
PndFileNameCreator (std::string fileName)
void SetFileName (std::string fileName)
void SetVerbose (Int_t v)
std::string GetFileName () const
std::string GetParFileName (std::string addon="", bool cut=false)
std::string GetSimFileName (std::string addon="", bool cut=false)
std::string GetDigiFileName (std::string addon="", bool cut=false)
std::string GetRecoFileName (std::string addon="", bool cut=false)
std::string GetTrackFindingFileName (std::string addon="", bool cut=false)
std::string GetRiemannFileName (std::string addon="", bool cut=false)
std::string GetCombinedRiemannFileName (std::string addon="", bool cut=false)
std::string GetIdealTrackFindingFileName (std::string addon="", bool cut=false)
std::string GetKalmanFileName (std::string addon="", bool cut=false)
std::string GetVertexFileName (std::string addon="", bool cut=false)
std::string GetCustomFileName (std::string ext, std::string addon="", bool cut=false)
std::string GetCustomFileNameInitial (std::string ext)
std::string GetPath ()
std::string GetFileName ()
Private Member Functions
std::string TruncateFileName (bool cut)
std::string TruncateInitial ()
ClassDef (PndFileNameCreator, 2)
Private Attributes
std::string fFileName
std::string fExtPar
std::string fExtSim
std::string fExtDigi
std::string fExtReco
std::string fExtTrackF
std::string fExtIdealTrackF
std::string fExtRiemann
std::string fExtCombinedRiemann
std::string fExtKalman
std::string fExtVertex
Int_t fVerbose
Detailed Description
A simple class which adds the corresponding file extensions to a given base class.
PndFileNameCreator.h
Author
Tobias Stockmanns t.sto.nosp@m.ckma.nosp@m.nns@f.nosp@m.z-ju.nosp@m.elich.nosp@m..de PndFileNameCreator takes the simulation filename and creates all the other filenames of a simulation chain by adding an extension to the simulation filename. Example: <SimulationFileName>.root –> <SimulationFileName>_<extension>.root. The Extension is predefined for the different simulation stages but a custom extension can be given in the method: GetCustomFileName. If the cut parameter is set to true an existing extension of the given fileName is replaced by a new extension. Example: <SimulationFileName>_<OldExtension>.root –> <SimulationFileName>_<NewExtension>.root. An extension is defined as the last part of a FileName which is separated by a "_" from the rest of the FileName.
Definition at line 21 of file PndFileNameCreator.h.
View newest version in sPHENIX GitHub at line 21 of file PndFileNameCreator.h
Constructor & Destructor Documentation
PndFileNameCreator::PndFileNameCreator ()
Definition at line 7 of file PndFileNameCreator.cxx.
View newest version in sPHENIX GitHub at line 7 of file PndFileNameCreator.cxx
PndFileNameCreator::PndFileNameCreator (std::string fileName)
Definition at line 15 of file PndFileNameCreator.cxx.
View newest version in sPHENIX GitHub at line 15 of file PndFileNameCreator.cxx
Member Function Documentation
PndFileNameCreator::ClassDef (PndFileNameCreator , 2) private
std::string PndFileNameCreator::GetCombinedRiemannFileName (std::string addon = "", bool cut = false)
Definition at line 61 of file PndFileNameCreator.cxx.
View newest version in sPHENIX GitHub at line 61 of file PndFileNameCreator.cxx
References fExtCombinedRiemann, and GetCustomFileName().
std::string PndFileNameCreator::GetCustomFileName (std::string ext, std::string addon = "", bool cut = false)
Definition at line 139 of file PndFileNameCreator.cxx.
View newest version in sPHENIX GitHub at line 139 of file PndFileNameCreator.cxx
References fVerbose, and TruncateFileName().
Referenced by GetCombinedRiemannFileName(), GetDigiFileName(), GetIdealTrackFindingFileName(), GetKalmanFileName(), GetParFileName(), GetRecoFileName(), GetRiemannFileName(), GetSimFileName(), GetTrackFindingFileName(), and GetVertexFileName().
std::string PndFileNameCreator::GetCustomFileNameInitial (std::string ext)
Definition at line 163 of file PndFileNameCreator.cxx.
View newest version in sPHENIX GitHub at line 163 of file PndFileNameCreator.cxx
References fVerbose, and TruncateInitial().
std::string PndFileNameCreator::GetDigiFileName (std::string addon = "", bool cut = false)
Definition at line 36 of file PndFileNameCreator.cxx.
View newest version in sPHENIX GitHub at line 36 of file PndFileNameCreator.cxx
References fExtDigi, and GetCustomFileName().
std::string PndFileNameCreator::GetFileName (void) const inline
Definition at line 29 of file PndFileNameCreator.h.
View newest version in sPHENIX GitHub at line 29 of file PndFileNameCreator.h
References fFileName.
Referenced by TruncateFileName(), and TruncateInitial().
std::string PndFileNameCreator::GetFileName (void)
Definition at line 188 of file PndFileNameCreator.cxx.
View newest version in sPHENIX GitHub at line 188 of file PndFileNameCreator.cxx
References fFileName, and PndStringSeparator::GetStringVector().
std::string PndFileNameCreator::GetIdealTrackFindingFileName (std::string addon = "", bool cut = false)
Definition at line 51 of file PndFileNameCreator.cxx.
View newest version in sPHENIX GitHub at line 51 of file PndFileNameCreator.cxx
References fExtIdealTrackF, and GetCustomFileName().
std::string PndFileNameCreator::GetKalmanFileName (std::string addon = "", bool cut = false)
Definition at line 67 of file PndFileNameCreator.cxx.
View newest version in sPHENIX GitHub at line 67 of file PndFileNameCreator.cxx
References fExtKalman, and GetCustomFileName().
std::string PndFileNameCreator::GetParFileName (std::string addon = "", bool cut = false)
Definition at line 26 of file PndFileNameCreator.cxx.
View newest version in sPHENIX GitHub at line 26 of file PndFileNameCreator.cxx
References fExtPar, and GetCustomFileName().
std::string PndFileNameCreator::GetPath ()
Definition at line 172 of file PndFileNameCreator.cxx.
View newest version in sPHENIX GitHub at line 172 of file PndFileNameCreator.cxx
References fFileName, fVerbose, PndStringSeparator::GetStringVector(), and PndStringSeparator::Print().
Referenced by TruncateFileName(), and TruncateInitial().
std::string PndFileNameCreator::GetRecoFileName (std::string addon = "", bool cut = false)
Definition at line 41 of file PndFileNameCreator.cxx.
View newest version in sPHENIX GitHub at line 41 of file PndFileNameCreator.cxx
References fExtReco, and GetCustomFileName().
std::string PndFileNameCreator::GetRiemannFileName (std::string addon = "", bool cut = false)
Definition at line 56 of file PndFileNameCreator.cxx.
View newest version in sPHENIX GitHub at line 56 of file PndFileNameCreator.cxx
References fExtRiemann, and GetCustomFileName().
std::string PndFileNameCreator::GetSimFileName (std::string addon = "", bool cut = false)
Definition at line 31 of file PndFileNameCreator.cxx.
View newest version in sPHENIX GitHub at line 31 of file PndFileNameCreator.cxx
References fExtSim, and GetCustomFileName().
std::string PndFileNameCreator::GetTrackFindingFileName (std::string addon = "", bool cut = false)
Definition at line 46 of file PndFileNameCreator.cxx.
View newest version in sPHENIX GitHub at line 46 of file PndFileNameCreator.cxx
References fExtTrackF, and GetCustomFileName().
std::string PndFileNameCreator::GetVertexFileName (std::string addon = "", bool cut = false)
Definition at line 72 of file PndFileNameCreator.cxx.
View newest version in sPHENIX GitHub at line 72 of file PndFileNameCreator.cxx
References fExtVertex, and GetCustomFileName().
void PndFileNameCreator::SetFileName (std::string fileName) inline
Definition at line 27 of file PndFileNameCreator.h.
View newest version in sPHENIX GitHub at line 27 of file PndFileNameCreator.h
References fFileName.
void PndFileNameCreator::SetVerbose (Int_t v) inline
Definition at line 28 of file PndFileNameCreator.h.
View newest version in sPHENIX GitHub at line 28 of file PndFileNameCreator.h
References fVerbose, and v.
std::string PndFileNameCreator::TruncateFileName (bool cut) private
Definition at line 199 of file PndFileNameCreator.cxx.
View newest version in sPHENIX GitHub at line 199 of file PndFileNameCreator.cxx
References GetFileName(), GetPath(), PndStringSeparator::GetStringVector(), and name.
Referenced by GetCustomFileName().
std::string PndFileNameCreator::TruncateInitial () private
Definition at line 234 of file PndFileNameCreator.cxx.
View newest version in sPHENIX GitHub at line 234 of file PndFileNameCreator.cxx
References GetFileName(), GetPath(), PndStringSeparator::GetStringVector(), and name.
Referenced by GetCustomFileNameInitial().
Member Data Documentation
std::string PndFileNameCreator::fExtCombinedRiemann private
Definition at line 71 of file PndFileNameCreator.h.
View newest version in sPHENIX GitHub at line 71 of file PndFileNameCreator.h
Referenced by GetCombinedRiemannFileName().
std::string PndFileNameCreator::fExtDigi private
Definition at line 66 of file PndFileNameCreator.h.
View newest version in sPHENIX GitHub at line 66 of file PndFileNameCreator.h
Referenced by GetDigiFileName().
std::string PndFileNameCreator::fExtIdealTrackF private
Definition at line 69 of file PndFileNameCreator.h.
View newest version in sPHENIX GitHub at line 69 of file PndFileNameCreator.h
Referenced by GetIdealTrackFindingFileName().
std::string PndFileNameCreator::fExtKalman private
Definition at line 72 of file PndFileNameCreator.h.
View newest version in sPHENIX GitHub at line 72 of file PndFileNameCreator.h
Referenced by GetKalmanFileName().
std::string PndFileNameCreator::fExtPar private
Definition at line 64 of file PndFileNameCreator.h.
View newest version in sPHENIX GitHub at line 64 of file PndFileNameCreator.h
Referenced by GetParFileName().
std::string PndFileNameCreator::fExtReco private
Definition at line 67 of file PndFileNameCreator.h.
View newest version in sPHENIX GitHub at line 67 of file PndFileNameCreator.h
Referenced by GetRecoFileName().
std::string PndFileNameCreator::fExtRiemann private
Definition at line 70 of file PndFileNameCreator.h.
View newest version in sPHENIX GitHub at line 70 of file PndFileNameCreator.h
Referenced by GetRiemannFileName().
std::string PndFileNameCreator::fExtSim private
Definition at line 65 of file PndFileNameCreator.h.
View newest version in sPHENIX GitHub at line 65 of file PndFileNameCreator.h
Referenced by GetSimFileName().
std::string PndFileNameCreator::fExtTrackF private
Definition at line 68 of file PndFileNameCreator.h.
View newest version in sPHENIX GitHub at line 68 of file PndFileNameCreator.h
Referenced by GetTrackFindingFileName().
std::string PndFileNameCreator::fExtVertex private
Definition at line 73 of file PndFileNameCreator.h.
View newest version in sPHENIX GitHub at line 73 of file PndFileNameCreator.h
Referenced by GetVertexFileName().
std::string PndFileNameCreator::fFileName private
Definition at line 63 of file PndFileNameCreator.h.
View newest version in sPHENIX GitHub at line 63 of file PndFileNameCreator.h
Referenced by GetFileName(), GetPath(), and SetFileName().
Int_t PndFileNameCreator::fVerbose private
Definition at line 77 of file PndFileNameCreator.h.
View newest version in sPHENIX GitHub at line 77 of file PndFileNameCreator.h
Referenced by GetCustomFileName(), GetCustomFileNameInitial(), GetPath(), and SetVerbose().
The documentation for this class was generated from the following files:
EicRoot/blob/master/PndTools/generalTools/PndFileNameCreator.h
EicRoot/blob/master/PndTools/generalTools/PndFileNameCreator.cxx