EIC Software: e_starlightStandalone Class Reference
e_starlightStandalone Class Reference
#include <estarlight/blob/master/include/e_starlightStandalone.h>
Public Member Functions
e_starlightStandalone ()
~e_starlightStandalone ()
bool init ()
reads configuration file and initializes startlight
bool run ()
creates output file and runs starlight
const std::string & baseFileName () const
const std::string & configFileName () const
returns path to config file
const std::string & eventDataFileName () const
returns path to output file
void setBaseFileName (const std::string &baseFileName)
sets path to base file
void setConfigFileName (const std::string &configFileName)
sets path to config file
void setEventDataFileName (const std::string &eventDataFileName)
sets path to output file
void boostEvent (eXEvent &e)
Boost event from beam CMS to lab system.
void reflectEvent (eXEvent &e)
flip z to -z for all output particles
Private Attributes
std::string _baseFileName
path to base filename
std::string _configFileName
path to configuration file
std::string _eventDataFileName
path to output file
e_starlight * _starlight
pointer to starlight instance
inputParameters * _inputParameters
pointer to parameter instance
unsigned int _nmbEventsTot
total number of events to generate (taken from configuration file)
unsigned int _nmbEventsPerFile
maximum number of events written to a single file (not yet implemented)
Detailed Description
Definition at line 45 of file e_starlightStandalone.h.
View newest version in sPHENIX GitHub at line 45 of file e_starlightStandalone.h
Constructor & Destructor Documentation
e_starlightStandalone::e_starlightStandalone ()
Definition at line 46 of file e_starlightStandalone.cpp.
View newest version in sPHENIX GitHub at line 46 of file e_starlightStandalone.cpp
e_starlightStandalone::~e_starlightStandalone ()
Definition at line 54 of file e_starlightStandalone.cpp.
View newest version in sPHENIX GitHub at line 54 of file e_starlightStandalone.cpp
Member Function Documentation
const std::string& e_starlightStandalone::baseFileName () const inline
Definition at line 55 of file e_starlightStandalone.h.
View newest version in sPHENIX GitHub at line 55 of file e_starlightStandalone.h
References _baseFileName.
Referenced by setBaseFileName().
void e_starlightStandalone::boostEvent (eXEvent & e)
Boost event from beam CMS to lab system.
Definition at line 184 of file e_starlightStandalone.cpp.
View newest version in sPHENIX GitHub at line 184 of file e_starlightStandalone.cpp
References _inputParameters, inputParameters::rap_CM(), and inputParameters::targetBeamLorentzGamma().
Referenced by run().
const std::string& e_starlightStandalone::configFileName () const inline
returns path to config file
Definition at line 56 of file e_starlightStandalone.h.
View newest version in sPHENIX GitHub at line 56 of file e_starlightStandalone.h
References _configFileName.
Referenced by setConfigFileName().
const std::string& e_starlightStandalone::eventDataFileName () const inline
returns path to output file
Definition at line 57 of file e_starlightStandalone.h.
View newest version in sPHENIX GitHub at line 57 of file e_starlightStandalone.h
References _eventDataFileName.
Referenced by setEventDataFileName().
bool e_starlightStandalone::init ()
reads configuration file and initializes startlight
Definition at line 59 of file e_starlightStandalone.cpp.
View newest version in sPHENIX GitHub at line 59 of file e_starlightStandalone.cpp
References _baseFileName, _configFileName, _inputParameters, _nmbEventsPerFile, _nmbEventsTot, _starlight, inputParameters::baseFileName(), inputParameters::configureFromFile(), e_starlight::init(), inputParameters::init(), inputParameters::nmbEvents(), printWarn, and e_starlight::setInputParameters().
Referenced by main().
void e_starlightStandalone::reflectEvent (eXEvent & e)
flip z to -z for all output particles
Definition at line 197 of file e_starlightStandalone.cpp.
View newest version in sPHENIX GitHub at line 197 of file e_starlightStandalone.cpp
Referenced by run().
bool e_starlightStandalone::run ()
creates output file and runs starlight
Definition at line 111 of file e_starlightStandalone.cpp.
View newest version in sPHENIX GitHub at line 111 of file e_starlightStandalone.cpp
References _baseFileName, _eventDataFileName, _inputParameters, _nmbEventsPerFile, _nmbEventsTot, _starlight, inputParameters::baseFileName(), boostEvent(), eventFileWriter::close(), e_starlight::getTotalCrossSection(), inputParameters::hepmc3FullEventRecord(), inputParameters::inputBranchingRatio(), inputParameters::lundFullEventRecord(), e_starlight::nmbAccepted(), e_starlight::nmbAttempts(), fileWriter::open(), printInfo, printWarn, e_starlight::produceEvent(), progressIndicator(), inputParameters::pythiaFullEventRecord(), reflectEvent(), eventFileWriter::writeEvent(), eventFileWriter::writeEventLUND(), eventFileWriter::writeFullHepMC3Info(), eventFileWriter::writeFullPythiaInfo(), eventFileWriter::writeInit(), and eventFileWriter::writeInitLUND().
Referenced by main().
void e_starlightStandalone::setBaseFileName (const std::string & baseFileName) inline
sets path to base file
Definition at line 59 of file e_starlightStandalone.h.
View newest version in sPHENIX GitHub at line 59 of file e_starlightStandalone.h
References _baseFileName, and baseFileName().
void e_starlightStandalone::setConfigFileName (const std::string & configFileName) inline
sets path to config file
Definition at line 60 of file e_starlightStandalone.h.
View newest version in sPHENIX GitHub at line 60 of file e_starlightStandalone.h
References _configFileName, and configFileName().
void e_starlightStandalone::setEventDataFileName (const std::string & eventDataFileName) inline
sets path to output file
Definition at line 61 of file e_starlightStandalone.h.
View newest version in sPHENIX GitHub at line 61 of file e_starlightStandalone.h
References _eventDataFileName, and eventDataFileName().
Member Data Documentation
std::string e_starlightStandalone::_baseFileName private
path to base filename
Definition at line 68 of file e_starlightStandalone.h.
View newest version in sPHENIX GitHub at line 68 of file e_starlightStandalone.h
Referenced by baseFileName(), init(), run(), and setBaseFileName().
std::string e_starlightStandalone::_configFileName private
path to configuration file
Definition at line 69 of file e_starlightStandalone.h.
View newest version in sPHENIX GitHub at line 69 of file e_starlightStandalone.h
Referenced by configFileName(), init(), and setConfigFileName().
std::string e_starlightStandalone::_eventDataFileName private
path to output file
Definition at line 70 of file e_starlightStandalone.h.
View newest version in sPHENIX GitHub at line 70 of file e_starlightStandalone.h
Referenced by eventDataFileName(), run(), and setEventDataFileName().
inputParameters* e_starlightStandalone::_inputParameters private
pointer to parameter instance
Definition at line 73 of file e_starlightStandalone.h.
View newest version in sPHENIX GitHub at line 73 of file e_starlightStandalone.h
Referenced by boostEvent(), init(), and run().
unsigned int e_starlightStandalone::_nmbEventsPerFile private
maximum number of events written to a single file (not yet implemented)
Definition at line 75 of file e_starlightStandalone.h.
View newest version in sPHENIX GitHub at line 75 of file e_starlightStandalone.h
Referenced by init(), and run().
unsigned int e_starlightStandalone::_nmbEventsTot private
total number of events to generate (taken from configuration file)
Definition at line 74 of file e_starlightStandalone.h.
View newest version in sPHENIX GitHub at line 74 of file e_starlightStandalone.h
Referenced by init(), and run().
e_starlight* e_starlightStandalone::_starlight private
pointer to starlight instance
Definition at line 72 of file e_starlightStandalone.h.
View newest version in sPHENIX GitHub at line 72 of file e_starlightStandalone.h
Referenced by init(), and run().
The documentation for this class was generated from the following files:
estarlight/blob/master/include/e_starlightStandalone.h
estarlight/blob/master/src/e_starlightStandalone.cpp