EIC Software: TrKalmanNodeLocation Class Reference
TrKalmanNodeLocation Class Reference
#include <EicRoot/blob/master/eic/htc/TrKalmanNodeLocation.h>
Public Member Functions
TrKalmanNodeLocation (double z)
~TrKalmanNodeLocation ()
void SetPrev (TrKalmanNodeLocation *location)
void SetNext (TrKalmanNodeLocation *location)
ProcessNoise * InitializeProcessNoiseMatrices (KalmanFilter::Direction fb)
void AddNode (TrKalmanNode *node)
void AddSensitiveVolume (SensitiveVolume *sv)
TrKalmanNodeLocation * GetNext (unsigned fb)
TrKalmanNodeLocation * GetPrev (unsigned fb)
unsigned GetNodeCount () const
TrKalmanNode * GetNode (unsigned nd) const
double GetZ () const
unsigned GetFiredNodeCount ()
bool HasSensitiveVolumes () const
const std::set
< SensitiveVolume * > & GetSensitiveVolumes () const
const t_3d_plane * GetPlane () const
void SetNextMdimValue (unsigned mdim)
unsigned GetSensitiveVolumeNodeWrapperCount () const
unsigned GetMdim (unsigned nd) const
void SetNextNodeToMaster (const TGeoHMatrix *mtx)
const TGeoHMatrix * GetNodeToMaster (unsigned nd) const
void SetNextTemplate (const EicKfNodeTemplate *tmpl)
const EicKfNodeTemplate * GetTemplate (unsigned nd) const
Public Attributes
MediaSliceArray * mMediaSliceArray
ProcessNoise * mProcessNoise [2]
RungeKutta mRungeKutta [2]
Private Attributes
t_3d_plane mPlane
std::vector< TrKalmanNode * > mNodes
TrKalmanNodeLocation * mPrev
TrKalmanNodeLocation * mNext
std::set< SensitiveVolume * > mSensitiveVolumes
std::vector< unsigned > mDims
std::vector< const TGeoHMatrix * > mNodeToMasters
std::vector< const
EicKfNodeTemplate * > mDigiTemplates
Detailed Description
Definition at line 37 of file TrKalmanNodeLocation.h.
View newest version in sPHENIX GitHub at line 37 of file TrKalmanNodeLocation.h
Constructor & Destructor Documentation
TrKalmanNodeLocation::TrKalmanNodeLocation (double z) inline
Definition at line 39 of file TrKalmanNodeLocation.h.
View newest version in sPHENIX GitHub at line 39 of file TrKalmanNodeLocation.h
References mPlane, mProcessNoise, and mRungeKutta.
TrKalmanNodeLocation::~TrKalmanNodeLocation () inline
Definition at line 46 of file TrKalmanNodeLocation.h.
View newest version in sPHENIX GitHub at line 46 of file TrKalmanNodeLocation.h
Member Function Documentation
void TrKalmanNodeLocation::AddNode (TrKalmanNode * node) inline
Definition at line 63 of file TrKalmanNodeLocation.h.
View newest version in sPHENIX GitHub at line 63 of file TrKalmanNodeLocation.h
References mNodes.
Referenced by KalmanNodeWrapper::AllocateNewKfNode(), and TrKalmanFilter::SetUpLocations().
void TrKalmanNodeLocation::AddSensitiveVolume (SensitiveVolume * sv) inline
Definition at line 64 of file TrKalmanNodeLocation.h.
View newest version in sPHENIX GitHub at line 64 of file TrKalmanNodeLocation.h
References mSensitiveVolumes.
Referenced by TrKalmanFilter::SetUpLocations().
unsigned TrKalmanNodeLocation::GetFiredNodeCount ()
Definition at line 150 of file TrKalmanNodeLocation.cxx.
View newest version in sPHENIX GitHub at line 150 of file TrKalmanNodeLocation.cxx
References TrKalmanNode::IsActive(), KalmanNode::IsFired(), and mNodes.
unsigned TrKalmanNodeLocation::GetMdim (unsigned nd) const inline
Definition at line 88 of file TrKalmanNodeLocation.h.
View newest version in sPHENIX GitHub at line 88 of file TrKalmanNodeLocation.h
References mDims.
Referenced by FwdHoughTree::AddNodeGroup().
TrKalmanNodeLocation* TrKalmanNodeLocation::GetNext (unsigned fb) inline
Definition at line 66 of file TrKalmanNodeLocation.h.
View newest version in sPHENIX GitHub at line 66 of file TrKalmanNodeLocation.h
References mNext, and mPrev.
Referenced by FwdTrackFinder::Init(), TrKalmanFilter::InitializeMediaSlices(), TrKalmanFilter::InitializeRungeKuttaFrames(), TrKalmanFilter::SelectActiveNodes(), and TrKalmanFilter::SetUpLocations().
TrKalmanNode* TrKalmanNodeLocation::GetNode (unsigned nd) const inline
Definition at line 70 of file TrKalmanNodeLocation.h.
View newest version in sPHENIX GitHub at line 70 of file TrKalmanNodeLocation.h
References mNodes.
Referenced by FwdHoughTree::AddNodeGroup().
unsigned TrKalmanNodeLocation::GetNodeCount () const inline
Definition at line 69 of file TrKalmanNodeLocation.h.
View newest version in sPHENIX GitHub at line 69 of file TrKalmanNodeLocation.h
References mNodes.
Referenced by FwdHoughTree::AddNodeGroup().
const TGeoHMatrix* TrKalmanNodeLocation::GetNodeToMaster (unsigned nd) const inline
Definition at line 93 of file TrKalmanNodeLocation.h.
View newest version in sPHENIX GitHub at line 93 of file TrKalmanNodeLocation.h
References mNodeToMasters.
Referenced by FwdHoughTree::AddNodeGroup().
const t_3d_plane* TrKalmanNodeLocation::GetPlane () const inline
Definition at line 80 of file TrKalmanNodeLocation.h.
View newest version in sPHENIX GitHub at line 80 of file TrKalmanNodeLocation.h
References mPlane.
Referenced by FwdHoughTree::MappingCall().
TrKalmanNodeLocation* TrKalmanNodeLocation::GetPrev (unsigned fb) inline
Definition at line 67 of file TrKalmanNodeLocation.h.
View newest version in sPHENIX GitHub at line 67 of file TrKalmanNodeLocation.h
References mNext, and mPrev.
Referenced by InitializeProcessNoiseMatrices().
unsigned TrKalmanNodeLocation::GetSensitiveVolumeNodeWrapperCount () const inline
Definition at line 87 of file TrKalmanNodeLocation.h.
View newest version in sPHENIX GitHub at line 87 of file TrKalmanNodeLocation.h
References mDims.
const std::set<SensitiveVolume*>& TrKalmanNodeLocation::GetSensitiveVolumes () const inline
Definition at line 76 of file TrKalmanNodeLocation.h.
View newest version in sPHENIX GitHub at line 76 of file TrKalmanNodeLocation.h
References mSensitiveVolumes.
const EicKfNodeTemplate* TrKalmanNodeLocation::GetTemplate (unsigned nd) const inline
Definition at line 100 of file TrKalmanNodeLocation.h.
View newest version in sPHENIX GitHub at line 100 of file TrKalmanNodeLocation.h
References mDigiTemplates.
Referenced by FwdHoughTree::AddNodeGroup().
double TrKalmanNodeLocation::GetZ () const inline
Definition at line 71 of file TrKalmanNodeLocation.h.
View newest version in sPHENIX GitHub at line 71 of file TrKalmanNodeLocation.h
References t_3d_plane::GetCoord(), and mPlane.
Referenced by FwdHoughTree::AddNodeGroup(), TrKalmanFilter::InitializeRungeKuttaFrames(), FwdHoughTree::MappingCall(), and TrKalmanFilter::SetUpLocations().
bool TrKalmanNodeLocation::HasSensitiveVolumes () const inline
Definition at line 75 of file TrKalmanNodeLocation.h.
View newest version in sPHENIX GitHub at line 75 of file TrKalmanNodeLocation.h
References mSensitiveVolumes.
ProcessNoise * TrKalmanNodeLocation::InitializeProcessNoiseMatrices (KalmanFilter::Direction fb)
Definition at line 59 of file TrKalmanNodeLocation.cxx.
View newest version in sPHENIX GitHub at line 59 of file TrKalmanNodeLocation.cxx
References MediaSlice::_RCxx, MediaSlice::_RCxy, MediaSlice::_RCyy, allocate_2dim_double_array(), F, fill_lower_triangle(), KalmanFilter::Forward, MediaLayer::GetMaterial(), MediaSlice::GetMediaLayer(), MediaSliceArray::GetMediaSlice(), MediaSliceArray::GetMediaSliceCount(), MediaLayer::GetMoliereChc(), GetPrev(), MediaSlice::GetReducedRadiationLength(), MediaSliceArray::GetThickness(), MediaSlice::GetThickness(), MediaSliceArray::GetZ0(), MediaSlice::GetZ0(), ip(), ir(), ProcessNoise::mCxx, ProcessNoise::mCxy, ProcessNoise::mCyy, mMediaSliceArray, and SQR.
void TrKalmanNodeLocation::SetNext (TrKalmanNodeLocation * location) inline
Definition at line 49 of file TrKalmanNodeLocation.h.
View newest version in sPHENIX GitHub at line 49 of file TrKalmanNodeLocation.h
References mNext.
Referenced by TrKalmanFilter::SetUpLocations().
void TrKalmanNodeLocation::SetNextMdimValue (unsigned mdim) inline
Definition at line 82 of file TrKalmanNodeLocation.h.
View newest version in sPHENIX GitHub at line 82 of file TrKalmanNodeLocation.h
References mDims.
void TrKalmanNodeLocation::SetNextNodeToMaster (const TGeoHMatrix * mtx) inline
Definition at line 89 of file TrKalmanNodeLocation.h.
View newest version in sPHENIX GitHub at line 89 of file TrKalmanNodeLocation.h
References mNodeToMasters.
void TrKalmanNodeLocation::SetNextTemplate (const EicKfNodeTemplate * tmpl) inline
Definition at line 96 of file TrKalmanNodeLocation.h.
View newest version in sPHENIX GitHub at line 96 of file TrKalmanNodeLocation.h
References mDigiTemplates.
void TrKalmanNodeLocation::SetPrev (TrKalmanNodeLocation * location) inline
Definition at line 48 of file TrKalmanNodeLocation.h.
View newest version in sPHENIX GitHub at line 48 of file TrKalmanNodeLocation.h
References mPrev.
Referenced by TrKalmanFilter::SetUpLocations().
Member Data Documentation
std::vector<const EicKfNodeTemplate*> TrKalmanNodeLocation::mDigiTemplates private
Definition at line 141 of file TrKalmanNodeLocation.h.
View newest version in sPHENIX GitHub at line 141 of file TrKalmanNodeLocation.h
Referenced by GetTemplate(), and SetNextTemplate().
std::vector<unsigned> TrKalmanNodeLocation::mDims private
Definition at line 132 of file TrKalmanNodeLocation.h.
View newest version in sPHENIX GitHub at line 132 of file TrKalmanNodeLocation.h
Referenced by GetMdim(), GetSensitiveVolumeNodeWrapperCount(), and SetNextMdimValue().
MediaSliceArray* TrKalmanNodeLocation::mMediaSliceArray
Definition at line 55 of file TrKalmanNodeLocation.h.
View newest version in sPHENIX GitHub at line 55 of file TrKalmanNodeLocation.h
Referenced by TrKalmanFilter::AccountIonizationLosses(), and InitializeProcessNoiseMatrices().
TrKalmanNodeLocation * TrKalmanNodeLocation::mNext private
Definition at line 121 of file TrKalmanNodeLocation.h.
View newest version in sPHENIX GitHub at line 121 of file TrKalmanNodeLocation.h
Referenced by GetNext(), GetPrev(), and SetNext().
std::vector<TrKalmanNode*> TrKalmanNodeLocation::mNodes private
Definition at line 118 of file TrKalmanNodeLocation.h.
View newest version in sPHENIX GitHub at line 118 of file TrKalmanNodeLocation.h
Referenced by AddNode(), GetFiredNodeCount(), GetNode(), and GetNodeCount().
std::vector<const TGeoHMatrix*> TrKalmanNodeLocation::mNodeToMasters private
Definition at line 139 of file TrKalmanNodeLocation.h.
View newest version in sPHENIX GitHub at line 139 of file TrKalmanNodeLocation.h
Referenced by GetNodeToMaster(), and SetNextNodeToMaster().
t_3d_plane TrKalmanNodeLocation::mPlane private
Definition at line 102 of file TrKalmanNodeLocation.h.
View newest version in sPHENIX GitHub at line 102 of file TrKalmanNodeLocation.h
Referenced by GetPlane(), GetZ(), and TrKalmanNodeLocation().
TrKalmanNodeLocation* TrKalmanNodeLocation::mPrev private
Definition at line 121 of file TrKalmanNodeLocation.h.
View newest version in sPHENIX GitHub at line 121 of file TrKalmanNodeLocation.h
Referenced by GetNext(), GetPrev(), and SetPrev().
ProcessNoise* TrKalmanNodeLocation::mProcessNoise[2]
Definition at line 58 of file TrKalmanNodeLocation.h.
View newest version in sPHENIX GitHub at line 58 of file TrKalmanNodeLocation.h
Referenced by TrKalmanFilter::CalculateProcessNoise(), and TrKalmanNodeLocation().
RungeKutta TrKalmanNodeLocation::mRungeKutta[2]
Definition at line 61 of file TrKalmanNodeLocation.h.
View newest version in sPHENIX GitHub at line 61 of file TrKalmanNodeLocation.h
Referenced by TrKalmanNode::GetMagneticField(), TrKalmanNode::PerformRungeKuttaStep(), and TrKalmanNodeLocation().
std::set<SensitiveVolume*> TrKalmanNodeLocation::mSensitiveVolumes private
Definition at line 126 of file TrKalmanNodeLocation.h.
View newest version in sPHENIX GitHub at line 126 of file TrKalmanNodeLocation.h
Referenced by AddSensitiveVolume(), GetSensitiveVolumes(), and HasSensitiveVolumes().
The documentation for this class was generated from the following files:
EicRoot/blob/master/eic/htc/TrKalmanNodeLocation.h
EicRoot/blob/master/eic/htc/TrKalmanNodeLocation.cxx