EIC Software: MatchCandidate Class Reference
MatchCandidate Class Reference abstract
#include <EicRoot/blob/master/eic/htree/MatchCandidate.h>
Public Member Functions
MatchCandidate (const HoughTree *tree=0)
~MatchCandidate ()
virtual void ShapeItUpForInspection (const HoughTree *tree, const unsigned id[])
virtual bool IsReadyForFinalFit () const =0
void ResetToTheVirginState ()
void ResetOkGroupCounter ()
unsigned GetOkGroupCounter () const
void IncrementOkGroupCounter (unsigned add)
void SetGroupedStatus (bool status)
bool IsGrouped () const
void SetInactive ()
bool IsActive () const
const unsigned * GetIdPtr () const
bool IsSubset (const HoughTree *tree, const MatchCandidate *reference) const
void ResetMemberPtr (unsigned gr, unsigned mm)
void ResetMemberPtr (unsigned gr, GroupMember *member)
void ResetMemberCount (unsigned gr)
unsigned GetLinearMemberCount (unsigned gr) const
unsigned GetAliveMemberCount (unsigned gr) const
GroupMember * GetFirstAliveMember (unsigned gr) const
unsigned GetAliveGroupCount () const
unsigned GetAliveMemberCount () const
void AddMember (unsigned gr, GroupMember *member)
GroupMember * GetSelMember (unsigned gr, unsigned mm)
virtual double GetTrackQualityParameter () const =0
bool HasAmbiguousHits () const
__u64 Ambiguity () const
bool SiamGroupCandidate (unsigned minHitCount)
unsigned GetGdim () const
Private Member Functions
ClassDef (MatchCandidate, 3)
Private Attributes
bool mActive
bool mGrouped
unsigned mGdim
unsigned * mId
unsigned * mMemberCount
std::vector< GroupMember * > * mSelMembers
unsigned mOkGroupCounter
Detailed Description
Definition at line 20 of file MatchCandidate.h.
View newest version in sPHENIX GitHub at line 20 of file MatchCandidate.h
Constructor & Destructor Documentation
MatchCandidate::MatchCandidate (const HoughTree * tree = 0)
Definition at line 28 of file MatchCandidate.cxx.
View newest version in sPHENIX GitHub at line 28 of file MatchCandidate.cxx
References HoughTree::GetDdim(), HoughTree::GetGdim(), mGdim, mId, mMemberCount, and mSelMembers.
MatchCandidate::~MatchCandidate () inline
Definition at line 24 of file MatchCandidate.h.
View newest version in sPHENIX GitHub at line 24 of file MatchCandidate.h
References mId, mMemberCount, and mSelMembers.
Member Function Documentation
void MatchCandidate::AddMember (unsigned gr, GroupMember * member)
Definition at line 80 of file MatchCandidate.cxx.
View newest version in sPHENIX GitHub at line 80 of file MatchCandidate.cxx
References mMemberCount, and mSelMembers.
Referenced by HoughTree::CheckCell().
__u64 MatchCandidate::Ambiguity () const
Definition at line 137 of file MatchCandidate.cxx.
View newest version in sPHENIX GitHub at line 137 of file MatchCandidate.cxx
References GetGdim(), Acts::UnitConstants::mm, mMemberCount, and mSelMembers.
Referenced by MatchCandidateGroup::AddCandidate(), and HasAmbiguousHits().
MatchCandidate::ClassDef (MatchCandidate , 3) private
unsigned MatchCandidate::GetAliveGroupCount () const inline
Definition at line 104 of file MatchCandidate.h.
View newest version in sPHENIX GitHub at line 104 of file MatchCandidate.h
References GetAliveMemberCount(), and GetGdim().
Referenced by FwdHoughTree::FinalFit(), and HoughTree::LaunchPatternFinder().
unsigned MatchCandidate::GetAliveMemberCount (unsigned gr) const inline
Definition at line 87 of file MatchCandidate.h.
View newest version in sPHENIX GitHub at line 87 of file MatchCandidate.h
References Acts::UnitConstants::mm, mMemberCount, and mSelMembers.
Referenced by HoughTree::CheckCell(), FwdHoughTree::FinalFit(), IsSubset(), HoughTree::IsSubset(), HoughTree::LaunchPatternFinder(), FwdHoughTree::ResolveAmbiguitiesNg(), and FwdHoughTree::SetupKalmanFilter().
unsigned MatchCandidate::GetAliveMemberCount () const inline
Definition at line 113 of file MatchCandidate.h.
View newest version in sPHENIX GitHub at line 113 of file MatchCandidate.h
References GetGdim().
Referenced by GetAliveGroupCount(), IsSubset(), and SiamGroupCandidate().
GroupMember* MatchCandidate::GetFirstAliveMember (unsigned gr) const inline
Definition at line 97 of file MatchCandidate.h.
View newest version in sPHENIX GitHub at line 97 of file MatchCandidate.h
References Acts::UnitConstants::mm, mMemberCount, and mSelMembers.
Referenced by HoughTree::CheckCell(), and HoughTree::LaunchPatternFinder().
unsigned MatchCandidate::GetGdim () const inline
Definition at line 133 of file MatchCandidate.h.
View newest version in sPHENIX GitHub at line 133 of file MatchCandidate.h
Referenced by MatchCandidateGroup::AddCandidate(), Ambiguity(), GetAliveGroupCount(), GetAliveMemberCount(), SetInactive(), ShapeItUpForInspection(), and SiamGroupCandidate().
const unsigned* MatchCandidate::GetIdPtr () const inline
Definition at line 63 of file MatchCandidate.h.
View newest version in sPHENIX GitHub at line 63 of file MatchCandidate.h
References mId.
Referenced by HoughTree::CheckCell(), FwdTrackFinder::ResetVtxNode(), and FwdHoughTree::SetupKalmanFilter().
unsigned MatchCandidate::GetLinearMemberCount (unsigned gr) const inline
Definition at line 84 of file MatchCandidate.h.
View newest version in sPHENIX GitHub at line 84 of file MatchCandidate.h
References mMemberCount.
Referenced by MatchCandidateGroup::AddCandidate(), FwdHoughTree::FinalFit(), HoughTree::IsSubset(), FwdHoughTree::ResolveAmbiguitiesNg(), SetInactive(), FwdHoughTree::SetupKalmanFilter(), and ShapeItUpForInspection().
unsigned MatchCandidate::GetOkGroupCounter () const inline
Definition at line 44 of file MatchCandidate.h.
View newest version in sPHENIX GitHub at line 44 of file MatchCandidate.h
References mOkGroupCounter.
Referenced by HoughTree::CheckCell().
GroupMember* MatchCandidate::GetSelMember (unsigned gr, unsigned mm) inline
Definition at line 124 of file MatchCandidate.h.
View newest version in sPHENIX GitHub at line 124 of file MatchCandidate.h
References Acts::UnitConstants::mm, and mSelMembers.
Referenced by MatchCandidateGroup::AddCandidate(), FwdHoughTree::FinalFit(), FwdHoughTree::GetKfNode(), HoughTree::IsSubset(), ResetMemberPtr(), FwdHoughTree::SetupKalmanFilter(), and ShapeItUpForInspection().
virtual double MatchCandidate::GetTrackQualityParameter () const pure virtual
Implemented in FwdMatchCandidate.
Referenced by HoughTree::LaunchPatternFinder().
bool MatchCandidate::HasAmbiguousHits () const
Definition at line 161 of file MatchCandidate.cxx.
View newest version in sPHENIX GitHub at line 161 of file MatchCandidate.cxx
References Ambiguity().
Referenced by FwdMatchCandidate::IsReadyForFinalFit(), HoughTree::LaunchPatternFinder(), and FwdHoughTree::ResolveAmbiguitiesNg().
void MatchCandidate::IncrementOkGroupCounter (unsigned add) inline
Definition at line 45 of file MatchCandidate.h.
View newest version in sPHENIX GitHub at line 45 of file MatchCandidate.h
References add(), and mOkGroupCounter.
Referenced by HoughTree::CheckCell().
bool MatchCandidate::IsActive () const inline
Definition at line 60 of file MatchCandidate.h.
View newest version in sPHENIX GitHub at line 60 of file MatchCandidate.h
References mActive.
Referenced by MatchCandidateGroup::AddCandidate(), HoughTree::CheckCell(), FwdTrackFinder::Exec(), HoughTree::LaunchPatternFinder(), and HoughTree::PurgeDuplicateTracks().
bool MatchCandidate::IsGrouped () const inline
Definition at line 51 of file MatchCandidate.h.
View newest version in sPHENIX GitHub at line 51 of file MatchCandidate.h
References mGrouped.
Referenced by MatchCandidateGroup::AddCandidate(), and HoughTree::LaunchPatternFinder().
virtual bool MatchCandidate::IsReadyForFinalFit () const pure virtual
Implemented in FwdMatchCandidate.
Referenced by HoughTree::CheckCell(), and HoughTree::LaunchPatternFinder().
bool MatchCandidate::IsSubset (const HoughTree * tree, const MatchCandidate * reference) const
Definition at line 99 of file MatchCandidate.cxx.
View newest version in sPHENIX GitHub at line 99 of file MatchCandidate.cxx
References GetAliveMemberCount(), HoughTree::GetGdim(), Acts::UnitConstants::mm, mMemberCount, and mSelMembers.
Referenced by HoughTree::CheckCell(), and HoughTree::PurgeDuplicateTracks().
void MatchCandidate::ResetMemberCount (unsigned gr) inline
Definition at line 81 of file MatchCandidate.h.
View newest version in sPHENIX GitHub at line 81 of file MatchCandidate.h
References mMemberCount.
Referenced by ResetToTheVirginState().
void MatchCandidate::ResetMemberPtr (unsigned gr, unsigned mm) inline
Definition at line 67 of file MatchCandidate.h.
View newest version in sPHENIX GitHub at line 67 of file MatchCandidate.h
References GroupMember::EraseMatchCandidate(), GetSelMember(), Acts::UnitConstants::mm, and mSelMembers.
Referenced by FwdHoughTree::FinalFit(), HoughTree::LaunchPatternFinder(), ResetMemberPtr(), FwdHoughTree::ResolveAmbiguitiesNg(), SetInactive(), and FwdHoughTree::SetupKalmanFilter().
void MatchCandidate::ResetMemberPtr (unsigned gr, GroupMember * member) inline
Definition at line 76 of file MatchCandidate.h.
View newest version in sPHENIX GitHub at line 76 of file MatchCandidate.h
References Acts::UnitConstants::mm, mMemberCount, mSelMembers, and ResetMemberPtr().
void MatchCandidate::ResetOkGroupCounter () inline
Definition at line 43 of file MatchCandidate.h.
View newest version in sPHENIX GitHub at line 43 of file MatchCandidate.h
References mOkGroupCounter.
Referenced by ResetToTheVirginState().
void MatchCandidate::ResetToTheVirginState ()
Definition at line 14 of file MatchCandidate.cxx.
View newest version in sPHENIX GitHub at line 14 of file MatchCandidate.cxx
References mActive, mGdim, mGrouped, ResetMemberCount(), and ResetOkGroupCounter().
Referenced by HoughTree::GetCurrentMatchBufferPtr().
void MatchCandidate::SetGroupedStatus (bool status) inline
Definition at line 50 of file MatchCandidate.h.
View newest version in sPHENIX GitHub at line 50 of file MatchCandidate.h
References mGrouped.
Referenced by MatchCandidateGroup::AddCandidate().
void MatchCandidate::SetInactive () inline
Definition at line 53 of file MatchCandidate.h.
View newest version in sPHENIX GitHub at line 53 of file MatchCandidate.h
References GetGdim(), GetLinearMemberCount(), mActive, Acts::UnitConstants::mm, and ResetMemberPtr().
Referenced by FwdHoughTree::FinalFit(), HoughTree::LaunchPatternFinder(), and HoughTree::PurgeDuplicateTracks().
void MatchCandidate::ShapeItUpForInspection (const HoughTree * tree, const unsigned id[]) virtual
Reimplemented in FwdMatchCandidate.
Definition at line 56 of file MatchCandidate.cxx.
View newest version in sPHENIX GitHub at line 56 of file MatchCandidate.cxx
References HoughTree::GetDdim(), GetGdim(), GetLinearMemberCount(), GetSelMember(), GroupMember::InsertMatchCandidate(), mActive, mId, and Acts::UnitConstants::mm.
Referenced by HoughTree::CheckCell(), and FwdMatchCandidate::ShapeItUpForInspection().
bool MatchCandidate::SiamGroupCandidate (unsigned minHitCount)
Definition at line 168 of file MatchCandidate.cxx.
View newest version in sPHENIX GitHub at line 168 of file MatchCandidate.cxx
References GetAliveMemberCount(), GetGdim(), Acts::UnitConstants::mm, and mMemberCount.
Referenced by HoughTree::LaunchPatternFinder().
Member Data Documentation
bool MatchCandidate::mActive private
Definition at line 133 of file MatchCandidate.h.
View newest version in sPHENIX GitHub at line 133 of file MatchCandidate.h
Referenced by IsActive(), ResetToTheVirginState(), SetInactive(), and ShapeItUpForInspection().
unsigned MatchCandidate::mGdim private
Definition at line 146 of file MatchCandidate.h.
View newest version in sPHENIX GitHub at line 146 of file MatchCandidate.h
Referenced by MatchCandidate(), and ResetToTheVirginState().
bool MatchCandidate::mGrouped private
Definition at line 140 of file MatchCandidate.h.
View newest version in sPHENIX GitHub at line 140 of file MatchCandidate.h
Referenced by IsGrouped(), ResetToTheVirginState(), and SetGroupedStatus().
unsigned* MatchCandidate::mId private
Definition at line 151 of file MatchCandidate.h.
View newest version in sPHENIX GitHub at line 151 of file MatchCandidate.h
Referenced by GetIdPtr(), MatchCandidate(), ShapeItUpForInspection(), and ~MatchCandidate().
unsigned* MatchCandidate::mMemberCount private
Definition at line 163 of file MatchCandidate.h.
View newest version in sPHENIX GitHub at line 163 of file MatchCandidate.h
Referenced by AddMember(), Ambiguity(), GetAliveMemberCount(), GetFirstAliveMember(), GetLinearMemberCount(), IsSubset(), MatchCandidate(), ResetMemberCount(), ResetMemberPtr(), SiamGroupCandidate(), and ~MatchCandidate().
unsigned MatchCandidate::mOkGroupCounter private
Definition at line 170 of file MatchCandidate.h.
View newest version in sPHENIX GitHub at line 170 of file MatchCandidate.h
Referenced by GetOkGroupCounter(), IncrementOkGroupCounter(), and ResetOkGroupCounter().
std::vector<GroupMember*>* MatchCandidate::mSelMembers private
Definition at line 167 of file MatchCandidate.h.
View newest version in sPHENIX GitHub at line 167 of file MatchCandidate.h
Referenced by AddMember(), Ambiguity(), GetAliveMemberCount(), GetFirstAliveMember(), GetSelMember(), IsSubset(), MatchCandidate(), ResetMemberPtr(), and ~MatchCandidate().
The documentation for this class was generated from the following files:
EicRoot/blob/master/eic/htree/MatchCandidate.h
EicRoot/blob/master/eic/htree/MatchCandidate.cxx