EIC Software: CbmRichGeoTest Class Reference
CbmRichGeoTest Class Reference
RICH geometry checking and testing.
#include <EicRoot/blob/master/rich/qa/CbmRichGeoTest.h>
Public Member Functions
CbmRichGeoTest ()
Standard constructor.
virtual ~CbmRichGeoTest ()
Standard destructor.
void SetParContainers ()
SetParContainers.
virtual InitStatus Init ()
Inherited from FairTask.
virtual void Exec (Option_t *option)
Inherited from FairTask.
virtual void Finish ()
Inherited from FairTask.
void CreateStudyReport (const string &title, const vector< string > &resultDirectories, const vector< string > &studyNames, const string &outputDir)
Creates summary report for different simulations. This is just an interface. All functionality is implemented in CbmRichGeoTestStudyReport class.
void SetOutputDir (const string &dir)
Set output directory where you want to write results (figures and json).
void SetRichDetectorType (const string &type)
Set detector type ("standard" or "prototype").
Public Member Functions inherited from FairTask
FairTask ()
FairTask (const char *name, Int_t iVerbose=1)
virtual ~FairTask ()
void InitTask ()
void ReInitTask ()
void SetParTask ()
virtual void FinishTask ()
virtual void FinishEvent ()
void SetVerbose (Int_t iVerbose)
void SetInputPersistance (Bool_t val)
void CheckInputPersistance (TString branchName)
Private Member Functions
void InitHistograms ()
Initialize histograms.
void DrawSummaryPlotsTemp ()
Temporary function for summary plots drawing.
void FillMcHist ()
Fill MC histogram for detector acceptance calculation.
void RingParameters ()
Loop over all rings in array and fill ring parameters histograms.
void FitAndFillHistEllipse (Int_t histIndex, CbmRichRingLight *ring, Double_t momentum)
Fit ring using ellipse fitter and fill histograms.
void FitAndFillHistCircle (Int_t histIndex, CbmRichRingLight *ring, Double_t momentum)
Fit ring using circle fitter and fill histograms.
void FillMcVsHitFitEllipse (CbmRichRingLight *ring, CbmRichRingLight *ringMc)
Calculate difference between ellipse parameters for two fitting using hits and MC points for fit and fill corresponding histograms.
void FillMcVsHitFitCircle (CbmRichRingLight *ring, CbmRichRingLight *ringMc)
Calculate difference between circle parameters for two fittings using hits and MC points for fit and fill corresponding histograms.
void HitsAndPoints ()
Calculate residuals between hits and MC points and fill histograms.
TH1D * CreateAccVsMinNofHitsHist ()
Create histogram: RICH detector acceptance vs. minimum required number of hits in ring.
void DrawHist ()
Draw histograms.
void DrawRing (CbmRichRingLight *ringHit, CbmRichRingLight *ringPoint)
Draw ring in separate TCanvas.
void CreateH2MeanRms (TH2D *hist, TH1D **meanHist, TH1D **rmsHist)
Creates two histogram. First is mean value vs. x axis, errors represents RMS. Second is RMS value vs. x axis.
void DrawH1andFit (TH1D *hist)
void DrawH2MeanRms (TH2D *hist, const string &canvasName)
void FitH1OneOverX (TH1D *hist, double xMinFit, double xMaxFit, double xMin, double xMax, const string &canvasName)
string CalcEfficiency (TH1 *histRec, TH1 *histAcc)
Create property tree an store different statistics there.
TH1D * DivideH1 (TH1D *h1, TH1D *h2, const string &name, const string &title, const string &axisX, const string &axisY)
Divide two histograms and create third one.
TH2D * DivideH2 (TH1D *h1, TH1D *h2, const string &name, const string &title, const string &axisX, const string &axisY, const string &axisZ)
TCanvas * CreateCanvas (const string &name, const string &title, int width, int height)
void DrawH3 (TH3D *h, const string &cName, const string &zAxisTitle, double zMin, double zMax, bool doFit=false)
void SaveCanvasToImage ()
CbmRichGeoTest (const CbmRichGeoTest &)
Copy constructor.
CbmRichGeoTest & operator= (const CbmRichGeoTest &)
Assignment operator.
Private Attributes
string fRichDetectorType
string fOutputDir
TClonesArray * fRichHits
TClonesArray * fRichRings
TClonesArray * fRichPoints
TClonesArray * fMCTracks
TClonesArray * fRichRingMatches
Double_t fDetZOrig
Double_t fTheta
Double_t fPhi
TObjArray * fSensNodes
TObjArray * fPassNodes
CbmGeoRichPar * fPar
CbmRichRingFitterCOP * fCopFit
CbmRichRingFitterEllipseTau * fTauFit
vector< TCanvas * > fCanvas
Int_t fEventNum
Int_t fMinNofHits
TH2D * fhHitsXY
TH2D * fhPointsXY
TH1D * fhNofPhotonsPerHit
vector< TH1D * > fhNofHits
vector< TH2D * > fhAaxisVsMom
vector< TH2D * > fhBaxisVsMom
vector< TH1D * > fhBoverA
vector< TH2D * > fhXcYcEllipse
vector< TH2D * > fhChi2EllipseVsMom
vector< TH2D * > fhXcYcCircle
vector< TH2D * > fhRadiusVsMom
vector< TH2D * > fhChi2CircleVsMom
vector< TH2D * > fhDRVsMom
TH2D * fhRadiusVsNofHits
TH2D * fhAaxisVsNofHits
TH2D * fhBaxisVsNofHits
TH2D * fhDiffAaxis
TH2D * fhDiffBaxis
TH2D * fhDiffXcEllipse
TH2D * fhDiffYcEllipse
TH2D * fhDiffXcCircle
TH2D * fhDiffYcCircle
TH2D * fhDiffRadius
TH1D * fhDiffXhit
TH1D * fhDiffYhit
Double_t fMinAaxis
Double_t fMaxAaxis
Double_t fMinBaxis
Double_t fMaxBaxis
Double_t fMinRadius
Double_t fMaxRadius
TH1D * fhNofHitsAll
TH1D * fhNofHitsCircleFit
TH1D * fhNofHitsEllipseFit
TH1D * fhNofHitsCircleFitEff
TH1D * fhNofHitsEllipseFitEff
TH1D * fh_mc_mom_el
TH2D * fh_mc_pty_el
TH1D * fh_acc_mom_el
TH2D * fh_acc_pty_el
TH1D * fh_mc_mom_pi
TH2D * fh_mc_pty_pi
TH1D * fh_acc_mom_pi
TH2D * fh_acc_pty_pi
TH3D * fhNofHitsXYZ
TH3D * fhNofPointsXYZ
TH3D * fhBoverAXYZ
TH3D * fhBaxisXYZ
TH3D * fhAaxisXYZ
TH3D * fhRadiusXYZ
TH3D * fhdRXYZ
vector< TH1 * > fHists
Int_t fNofDrawnRings
Additional Inherited Members
Protected Member Functions inherited from FairTask
virtual InitStatus ReInit ()
void InitTasks ()
void ReInitTasks ()
void SetParTasks ()
void FinishTasks ()
void FinishEvents ()
Protected Attributes inherited from FairTask
Int_t fVerbose
Int_t fInputPersistance
Indicates if input branch is persistant.
FairLogger * fLogger
Detailed Description
RICH geometry checking and testing.
Author
Semen Lebedev s.leb.nosp@m.edev.nosp@m.@gsi..nosp@m.de
Date
2011
Definition at line 39 of file CbmRichGeoTest.h.
View newest version in sPHENIX GitHub at line 39 of file CbmRichGeoTest.h
Constructor & Destructor Documentation
CbmRichGeoTest::CbmRichGeoTest ()
Standard constructor.
Definition at line 59 of file CbmRichGeoTest.cxx.
View newest version in sPHENIX GitHub at line 59 of file CbmRichGeoTest.cxx
References fEventNum, fMaxAaxis, fMaxBaxis, fMaxRadius, fMinAaxis, fMinBaxis, fMinNofHits, fMinRadius, and fNofDrawnRings.
CbmRichGeoTest::~CbmRichGeoTest () virtual
Standard destructor.
Definition at line 163 of file CbmRichGeoTest.cxx.
View newest version in sPHENIX GitHub at line 163 of file CbmRichGeoTest.cxx
CbmRichGeoTest::CbmRichGeoTest (const CbmRichGeoTest &) private
Copy constructor.
Member Function Documentation
string CbmRichGeoTest::CalcEfficiency (TH1 * histRec, TH1 * histAcc) private
Create property tree an store different statistics there.
Calculate efficiency.
Parameters
[in] histRec
[in] histAcc
Definition at line 1157 of file CbmRichGeoTest.cxx.
View newest version in sPHENIX GitHub at line 1157 of file CbmRichGeoTest.cxx
Referenced by DrawHist().
TH1D * CbmRichGeoTest::CreateAccVsMinNofHitsHist () private
Create histogram: RICH detector acceptance vs. minimum required number of hits in ring.
Definition at line 716 of file CbmRichGeoTest.cxx.
View newest version in sPHENIX GitHub at line 716 of file CbmRichGeoTest.cxx
References fh_mc_mom_el, and fhNofHits.
Referenced by DrawHist().
TCanvas * CbmRichGeoTest::CreateCanvas (const string & name, const string & title, int width, int height) private
Definition at line 1206 of file CbmRichGeoTest.cxx.
View newest version in sPHENIX GitHub at line 1206 of file CbmRichGeoTest.cxx
References c, fCanvas, and width().
Referenced by DrawH2MeanRms(), DrawH3(), DrawHist(), DrawRing(), DrawSummaryPlotsTemp(), and FitH1OneOverX().
void CbmRichGeoTest::CreateH2MeanRms (TH2D * hist, TH1D ** meanHist, TH1D ** rmsHist) private
Creates two histogram. First is mean value vs. x axis, errors represents RMS. Second is RMS value vs. x axis.
Parameters
[in] hist Input 2D histogram.
[out] meanHist Histogram of mean values.
[out] rmsHist Histogram of RMS values.
Definition at line 730 of file CbmRichGeoTest.cxx.
View newest version in sPHENIX GitHub at line 730 of file CbmRichGeoTest.cxx
Referenced by DrawH2MeanRms(), and DrawHist().
void CbmRichGeoTest::CreateStudyReport (const string & title, const vector< string > & resultDirectories, const vector< string > & studyNames, const string & outputDir)
Creates summary report for different simulations. This is just an interface. All functionality is implemented in CbmRichGeoTestStudyReport class.
Parameters
[in] title Report title.
[in] resultDirectories Paths to directories with results for each simulation.
[in] studyNames Name of each study.
[in] outputDir Path to the output directory.
Definition at line 1130 of file CbmRichGeoTest.cxx.
View newest version in sPHENIX GitHub at line 1130 of file CbmRichGeoTest.cxx
References CbmStudyReport::Create(), and title().
TH1D * CbmRichGeoTest::DivideH1 (TH1D * h1, TH1D * h2, const string & name, const string & title, const string & axisX, const string & axisY) private
Divide two histograms and create third one.
Definition at line 1172 of file CbmRichGeoTest.cxx.
View newest version in sPHENIX GitHub at line 1172 of file CbmRichGeoTest.cxx
Referenced by DrawHist().
TH2D * CbmRichGeoTest::DivideH2 (TH1D * h1, TH1D * h2, const string & name, const string & title, const string & axisX, const string & axisY, const string & axisZ) private
Definition at line 1188 of file CbmRichGeoTest.cxx.
View newest version in sPHENIX GitHub at line 1188 of file CbmRichGeoTest.cxx
Referenced by DrawHist().
void CbmRichGeoTest::DrawH1andFit (TH1D * hist) private
Definition at line 796 of file CbmRichGeoTest.cxx.
View newest version in sPHENIX GitHub at line 796 of file CbmRichGeoTest.cxx
References DrawH1(), func, Acts::UnitConstants::m, and Acts::UnitConstants::s.
Referenced by DrawH3(), and DrawHist().
void CbmRichGeoTest::DrawH2MeanRms (TH2D * hist, const string & canvasName) private
Definition at line 750 of file CbmRichGeoTest.cxx.
View newest version in sPHENIX GitHub at line 750 of file CbmRichGeoTest.cxx
References c1, c2, c3, CreateCanvas(), CreateH2MeanRms(), and DrawH1().
Referenced by DrawHist().
void CbmRichGeoTest::DrawH3 (TH3D * h, const string & cName, const string & zAxisTitle, double zMin, double zMax, bool doFit = false) private
Definition at line 1069 of file CbmRichGeoTest.cxx.
View newest version in sPHENIX GitHub at line 1069 of file CbmRichGeoTest.cxx
References CreateCanvas(), DrawH1andFit(), DrawH2(), func, Acts::Test::hz, Acts::UnitConstants::m, Acts::UnitConstants::s, x, and y.
Referenced by DrawHist().
void CbmRichGeoTest::DrawHist () private
Draw histograms.
Definition at line 857 of file CbmRichGeoTest.cxx.
View newest version in sPHENIX GitHub at line 857 of file CbmRichGeoTest.cxx
References CalcEfficiency(), CreateAccVsMinNofHitsHist(), CreateCanvas(), CreateH2MeanRms(), DivideH1(), DivideH2(), DrawH1(), DrawH1andFit(), DrawH2(), DrawH2MeanRms(), DrawH3(), fh_acc_mom_el, fh_acc_mom_pi, fh_acc_pty_el, fh_acc_pty_pi, fh_mc_mom_el, fh_mc_mom_pi, fh_mc_pty_el, fh_mc_pty_pi, fhAaxisVsMom, fhAaxisVsNofHits, fhAaxisXYZ, fhBaxisVsMom, fhBaxisVsNofHits, fhBaxisXYZ, fhBoverA, fhBoverAXYZ, fhChi2CircleVsMom, fhChi2EllipseVsMom, fhDiffAaxis, fhDiffBaxis, fhDiffRadius, fhDiffXcCircle, fhDiffXcEllipse, fhDiffXhit, fhDiffYcCircle, fhDiffYcEllipse, fhDiffYhit, fhDRVsMom, fhdRXYZ, fhHitsXY, fhNofHits, fhNofHitsAll, fhNofHitsCircleFit, fhNofHitsCircleFitEff, fhNofHitsEllipseFit, fhNofHitsEllipseFitEff, fhNofHitsXYZ, fhNofPhotonsPerHit, fhNofPointsXYZ, fhPointsXY, fhRadiusVsMom, fhRadiusVsNofHits, fhRadiusXYZ, fhXcYcCircle, fhXcYcEllipse, FitH1OneOverX(), Acts::UnitConstants::h, kLinear, kLog, and SetDefaultDrawStyle().
Referenced by Finish().
void CbmRichGeoTest::DrawRing (CbmRichRingLight * ringHit, CbmRichRingLight * ringPoint) private
Draw ring in separate TCanvas.
Parameters
[in] ring Ring with RICH hits.
[in] ringPoint Ring with MC RICH points.
Definition at line 659 of file CbmRichGeoTest.cxx.
View newest version in sPHENIX GitHub at line 659 of file CbmRichGeoTest.cxx
References c, CreateCanvas(), fNofDrawnRings, CbmRichHitLight::fX, CbmRichHitLight::fY, CbmRichRingLight::GetCenterX(), CbmRichRingLight::GetCenterY(), CbmRichRingLight::GetHit(), CbmRichRingLight::GetNofHits(), CbmRichRingLight::GetRadius(), xmax, xmin, ymax, and ymin.
Referenced by RingParameters().
void CbmRichGeoTest::DrawSummaryPlotsTemp () private
Temporary function for summary plots drawing.
Definition at line 372 of file CbmRichGeoTest.cxx.
View newest version in sPHENIX GitHub at line 372 of file CbmRichGeoTest.cxx
References c1, c2, CreateCanvas(), DrawGraph(), f2(), kLinear, leg(), lit::NumberToString(), x, and x2.
Referenced by InitHistograms().
void CbmRichGeoTest::Exec (Option_t * option) virtual
Inherited from FairTask.
Definition at line 223 of file CbmRichGeoTest.cxx.
View newest version in sPHENIX GitHub at line 223 of file CbmRichGeoTest.cxx
References fEventNum, FillMcHist(), HitsAndPoints(), and RingParameters().
void CbmRichGeoTest::FillMcHist () private
Fill MC histogram for detector acceptance calculation.
Definition at line 430 of file CbmRichGeoTest.cxx.
View newest version in sPHENIX GitHub at line 430 of file CbmRichGeoTest.cxx
References fh_mc_mom_el, fh_mc_mom_pi, fh_mc_pty_el, fh_mc_pty_pi, fMCTracks, CbmMCTrack::GetMotherId(), CbmMCTrack::GetP(), CbmMCTrack::GetPdgCode(), CbmMCTrack::GetPt(), CbmMCTrack::GetRapidity(), and pdg.
Referenced by Exec().
void CbmRichGeoTest::FillMcVsHitFitCircle (CbmRichRingLight * ring, CbmRichRingLight * ringMc) private
Calculate difference between circle parameters for two fittings using hits and MC points for fit and fill corresponding histograms.
Parameters
[in] ring Ring fitted using hits.
[in] ringMc Ring fitted using MC points
Definition at line 618 of file CbmRichGeoTest.cxx.
View newest version in sPHENIX GitHub at line 618 of file CbmRichGeoTest.cxx
References fhDiffRadius, fhDiffXcCircle, fhDiffYcCircle, CbmRichRingLight::GetCenterX(), CbmRichRingLight::GetCenterY(), CbmRichRingLight::GetNofHits(), and CbmRichRingLight::GetRadius().
Referenced by RingParameters().
void CbmRichGeoTest::FillMcVsHitFitEllipse (CbmRichRingLight * ring, CbmRichRingLight * ringMc) private
Calculate difference between ellipse parameters for two fitting using hits and MC points for fit and fill corresponding histograms.
Parameters
[in] ring Ring fitted using hits.
[in] ringMc Ring fitted using MC points
Definition at line 608 of file CbmRichGeoTest.cxx.
View newest version in sPHENIX GitHub at line 608 of file CbmRichGeoTest.cxx
References fhDiffAaxis, fhDiffBaxis, fhDiffXcEllipse, fhDiffYcEllipse, CbmRichRingLight::GetAaxis(), CbmRichRingLight::GetBaxis(), CbmRichRingLight::GetCenterX(), CbmRichRingLight::GetCenterY(), and CbmRichRingLight::GetNofHits().
Referenced by RingParameters().
void CbmRichGeoTest::Finish (void) virtual
Inherited from FairTask.
Reimplemented from FairTask.
Definition at line 1145 of file CbmRichGeoTest.cxx.
View newest version in sPHENIX GitHub at line 1145 of file CbmRichGeoTest.cxx
References DrawHist(), fHists, fhNofHits, fhNofPhotonsPerHit, and SaveCanvasToImage().
void CbmRichGeoTest::FitAndFillHistCircle (Int_t histIndex, CbmRichRingLight * ring, Double_t momentum) private
Fit ring using circle fitter and fill histograms.
Parameters
[in] histIndex Fitting type index, 0 - hit fitting, 1 - MC points fitting.
[in] ring Pointer to CbmRichRingLight to be fitted and filled in histograms.
[in] momentum MC momentum of particle produced ring.
Definition at line 578 of file CbmRichGeoTest.cxx.
View newest version in sPHENIX GitHub at line 578 of file CbmRichGeoTest.cxx
References CbmRichRingFitterCOP::DoFit(), fCopFit, fhChi2CircleVsMom, fhDRVsMom, fhRadiusVsMom, fhRadiusVsNofHits, fhXcYcCircle, CbmRichHitLight::fX, CbmRichHitLight::fY, CbmRichRingLight::GetCenterX(), CbmRichRingLight::GetCenterY(), CbmRichRingLight::GetChi2(), CbmRichRingLight::GetHit(), CbmRichRingLight::GetNofHits(), CbmRichRingLight::GetRadius(), and G4BECAL::radius.
Referenced by RingParameters().
void CbmRichGeoTest::FitAndFillHistEllipse (Int_t histIndex, CbmRichRingLight * ring, Double_t momentum) private
Fit ring using ellipse fitter and fill histograms.
Parameters
[in] histIndex Fitting type index, 0 - hit fitting, 1 - MC points fitting.
[in] ring Pointer to CbmRichRing to be fitted and filled in histograms.
[in] momentum MC momentum of particle produced ring.
Definition at line 553 of file CbmRichGeoTest.cxx.
View newest version in sPHENIX GitHub at line 553 of file CbmRichGeoTest.cxx
References CbmRichRingFitterEllipseTau::DoFit(), fhAaxisVsMom, fhAaxisVsNofHits, fhBaxisVsMom, fhBaxisVsNofHits, fhBoverA, fhChi2EllipseVsMom, fhNofHits, fhXcYcEllipse, fMaxBaxis, fMinAaxis, fMinBaxis, fTauFit, CbmRichRingLight::GetAaxis(), CbmRichRingLight::GetBaxis(), CbmRichRingLight::GetCenterX(), CbmRichRingLight::GetCenterY(), CbmRichRingLight::GetChi2(), and CbmRichRingLight::GetNofHits().
Referenced by RingParameters().
void CbmRichGeoTest::FitH1OneOverX (TH1D * hist, double xMinFit, double xMaxFit, double xMin, double xMax, const string & canvasName) private
Definition at line 818 of file CbmRichGeoTest.cxx.
View newest version in sPHENIX GitHub at line 818 of file CbmRichGeoTest.cxx
References c1, CreateCanvas(), DrawH1(), leg(), and lit::NumberToString().
Referenced by DrawHist().
void CbmRichGeoTest::HitsAndPoints () private
Calculate residuals between hits and MC points and fill histograms.
Definition at line 627 of file CbmRichGeoTest.cxx.
View newest version in sPHENIX GitHub at line 627 of file CbmRichGeoTest.cxx
References fDetZOrig, fhDiffXhit, fhDiffYhit, fhHitsXY, fhNofPhotonsPerHit, fhPointsXY, fPhi, fRichHits, fRichPoints, fTheta, CbmRichHit::GetNPhotons(), CbmBaseHit::GetRefId(), FairMCPoint::GetX(), CbmPixelHit::GetX(), FairMCPoint::GetY(), CbmPixelHit::GetY(), FairMCPoint::GetZ(), and CbmRichHitProducer::TiltPoint().
Referenced by Exec().
InitStatus CbmRichGeoTest::Init (void) virtual
Inherited from FairTask.
Reimplemented from FairTask.
Definition at line 175 of file CbmRichGeoTest.cxx.
View newest version in sPHENIX GitHub at line 175 of file CbmRichGeoTest.cxx
References fCopFit, fDetZOrig, fMCTracks, fPar, fPassNodes, fPhi, fRichDetectorType, fRichHits, fRichPoints, fRichRingMatches, fRichRings, fSensNodes, fTauFit, fTheta, FairGeoNode::getCenterPosition(), CbmGeoRichPar::GetGeoPassiveNodes(), CbmGeoRichPar::GetGeoSensitiveNodes(), FairGeoNode::getLabTransform(), FairRootManager::GetObject(), FairGeoTransform::getRotMatrix(), FairGeoTransform::getTranslation(), InitHistograms(), FairRootManager::Instance(), kSUCCESS, and FairGeoVector::Z().
void CbmRichGeoTest::InitHistograms () private
Initialize histograms.
Definition at line 233 of file CbmRichGeoTest.cxx.
View newest version in sPHENIX GitHub at line 233 of file CbmRichGeoTest.cxx
References DrawSummaryPlotsTemp(), fh_acc_mom_el, fh_acc_mom_pi, fh_acc_pty_el, fh_acc_pty_pi, fh_mc_mom_el, fh_mc_mom_pi, fh_mc_pty_el, fh_mc_pty_pi, fhAaxisVsMom, fhAaxisVsNofHits, fhAaxisXYZ, fhBaxisVsMom, fhBaxisVsNofHits, fhBaxisXYZ, fhBoverA, fhBoverAXYZ, fhChi2CircleVsMom, fhChi2EllipseVsMom, fhDiffAaxis, fhDiffBaxis, fhDiffRadius, fhDiffXcCircle, fhDiffXcEllipse, fhDiffXhit, fhDiffYcCircle, fhDiffYcEllipse, fhDiffYhit, fhDRVsMom, fhdRXYZ, fhHitsXY, fHists, fhNofHits, fhNofHitsAll, fhNofHitsCircleFit, fhNofHitsCircleFitEff, fhNofHitsEllipseFit, fhNofHitsEllipseFitEff, fhNofHitsXYZ, fhNofPhotonsPerHit, fhNofPointsXYZ, fhPointsXY, fhRadiusVsMom, fhRadiusVsNofHits, fhRadiusXYZ, fhXcYcCircle, fhXcYcEllipse, fRichDetectorType, and t.
Referenced by Init().
CbmRichGeoTest& CbmRichGeoTest::operator= (const CbmRichGeoTest &) private
Assignment operator.
void CbmRichGeoTest::RingParameters () private
Loop over all rings in array and fill ring parameters histograms.
Definition at line 450 of file CbmRichGeoTest.cxx.
View newest version in sPHENIX GitHub at line 450 of file CbmRichGeoTest.cxx
References CbmRichRingLight::AddHit(), CbmRichConverter::CopyHitsToRingLight(), DrawRing(), fDetZOrig, fh_acc_mom_el, fh_acc_mom_pi, fh_acc_pty_el, fh_acc_pty_pi, fhAaxisXYZ, fhBaxisXYZ, fhBoverAXYZ, fhdRXYZ, fhNofHitsAll, fhNofHitsCircleFit, fhNofHitsEllipseFit, fhNofHitsXYZ, fhNofPointsXYZ, fhRadiusXYZ, FillMcVsHitFitCircle(), FillMcVsHitFitEllipse(), FitAndFillHistCircle(), FitAndFillHistEllipse(), fMaxAaxis, fMaxBaxis, fMaxRadius, fMCTracks, fMinAaxis, fMinBaxis, fMinNofHits, fMinRadius, fNofDrawnRings, fPhi, fRichPoints, fRichRingMatches, fRichRings, fTheta, CbmRichHitLight::fX, CbmRichHitLight::fY, CbmRichRingLight::GetAaxis(), CbmRichRingLight::GetBaxis(), CbmRichRingLight::GetCenterX(), CbmRichRingLight::GetCenterY(), CbmRichRingLight::GetHit(), CbmTrackMatch::GetMCTrackId(), CbmMCTrack::GetMotherId(), CbmRichRing::GetNofHits(), CbmRichRingLight::GetNofHits(), CbmMCTrack::GetP(), CbmMCTrack::GetPdgCode(), CbmMCTrack::GetPt(), CbmRichRingLight::GetRadius(), CbmMCTrack::GetRapidity(), FairMCPoint::GetTrackID(), momentum, pdg, FairMCPoint::Position(), and CbmRichHitProducer::TiltPoint().
Referenced by Exec().
void CbmRichGeoTest::SaveCanvasToImage () private
Definition at line 1217 of file CbmRichGeoTest.cxx.
View newest version in sPHENIX GitHub at line 1217 of file CbmRichGeoTest.cxx
References fCanvas, fOutputDir, and lit::SaveCanvasAsImage().
Referenced by Finish().
void CbmRichGeoTest::SetOutputDir (const string & dir) inline
Set output directory where you want to write results (figures and json).
Parameters
[in] dir Path to the output directory.
Definition at line 92 of file CbmRichGeoTest.h.
View newest version in sPHENIX GitHub at line 92 of file CbmRichGeoTest.h
void CbmRichGeoTest::SetParContainers () virtual
SetParContainers.
Reimplemented from FairTask.
Definition at line 168 of file CbmRichGeoTest.cxx.
View newest version in sPHENIX GitHub at line 168 of file CbmRichGeoTest.cxx
References fPar, FairRuntimeDb::getContainer(), FairRun::GetRuntimeDb(), and FairRunAna::Instance().
void CbmRichGeoTest::SetRichDetectorType (const string & type) inline
Set detector type ("standard" or "prototype").
Parameters
[in] type Detector type.
Definition at line 98 of file CbmRichGeoTest.h.
View newest version in sPHENIX GitHub at line 98 of file CbmRichGeoTest.h
Member Data Documentation
vector<TCanvas*> CbmRichGeoTest::fCanvas private
Definition at line 299 of file CbmRichGeoTest.h.
View newest version in sPHENIX GitHub at line 299 of file CbmRichGeoTest.h
Referenced by CreateCanvas(), and SaveCanvasToImage().
CbmRichRingFitterCOP* CbmRichGeoTest::fCopFit private
Definition at line 296 of file CbmRichGeoTest.h.
View newest version in sPHENIX GitHub at line 296 of file CbmRichGeoTest.h
Referenced by FitAndFillHistCircle(), and Init().
Double_t CbmRichGeoTest::fDetZOrig private
Definition at line 288 of file CbmRichGeoTest.h.
View newest version in sPHENIX GitHub at line 288 of file CbmRichGeoTest.h
Referenced by HitsAndPoints(), Init(), and RingParameters().
Int_t CbmRichGeoTest::fEventNum private
Definition at line 301 of file CbmRichGeoTest.h.
View newest version in sPHENIX GitHub at line 301 of file CbmRichGeoTest.h
Referenced by CbmRichGeoTest(), and Exec().
TH1D* CbmRichGeoTest::fh_acc_mom_el private
Definition at line 361 of file CbmRichGeoTest.h.
View newest version in sPHENIX GitHub at line 361 of file CbmRichGeoTest.h
Referenced by DrawHist(), InitHistograms(), and RingParameters().
TH1D* CbmRichGeoTest::fh_acc_mom_pi private
Definition at line 366 of file CbmRichGeoTest.h.
View newest version in sPHENIX GitHub at line 366 of file CbmRichGeoTest.h
Referenced by DrawHist(), InitHistograms(), and RingParameters().
TH2D* CbmRichGeoTest::fh_acc_pty_el private
Definition at line 362 of file CbmRichGeoTest.h.
View newest version in sPHENIX GitHub at line 362 of file CbmRichGeoTest.h
Referenced by DrawHist(), InitHistograms(), and RingParameters().
TH2D* CbmRichGeoTest::fh_acc_pty_pi private
Definition at line 367 of file CbmRichGeoTest.h.
View newest version in sPHENIX GitHub at line 367 of file CbmRichGeoTest.h
Referenced by DrawHist(), InitHistograms(), and RingParameters().
TH1D* CbmRichGeoTest::fh_mc_mom_el private
Definition at line 359 of file CbmRichGeoTest.h.
View newest version in sPHENIX GitHub at line 359 of file CbmRichGeoTest.h
Referenced by CreateAccVsMinNofHitsHist(), DrawHist(), FillMcHist(), and InitHistograms().
TH1D* CbmRichGeoTest::fh_mc_mom_pi private
Definition at line 364 of file CbmRichGeoTest.h.
View newest version in sPHENIX GitHub at line 364 of file CbmRichGeoTest.h
Referenced by DrawHist(), FillMcHist(), and InitHistograms().
TH2D* CbmRichGeoTest::fh_mc_pty_el private
Definition at line 360 of file CbmRichGeoTest.h.
View newest version in sPHENIX GitHub at line 360 of file CbmRichGeoTest.h
Referenced by DrawHist(), FillMcHist(), and InitHistograms().
TH2D* CbmRichGeoTest::fh_mc_pty_pi private
Definition at line 365 of file CbmRichGeoTest.h.
View newest version in sPHENIX GitHub at line 365 of file CbmRichGeoTest.h
Referenced by DrawHist(), FillMcHist(), and InitHistograms().
vector<TH2D*> CbmRichGeoTest::fhAaxisVsMom private
Definition at line 312 of file CbmRichGeoTest.h.
View newest version in sPHENIX GitHub at line 312 of file CbmRichGeoTest.h
Referenced by DrawHist(), FitAndFillHistEllipse(), and InitHistograms().
TH2D* CbmRichGeoTest::fhAaxisVsNofHits private
Definition at line 325 of file CbmRichGeoTest.h.
View newest version in sPHENIX GitHub at line 325 of file CbmRichGeoTest.h
Referenced by DrawHist(), FitAndFillHistEllipse(), and InitHistograms().
TH3D* CbmRichGeoTest::fhAaxisXYZ private
Definition at line 375 of file CbmRichGeoTest.h.
View newest version in sPHENIX GitHub at line 375 of file CbmRichGeoTest.h
Referenced by DrawHist(), InitHistograms(), and RingParameters().
vector<TH2D*> CbmRichGeoTest::fhBaxisVsMom private
Definition at line 313 of file CbmRichGeoTest.h.
View newest version in sPHENIX GitHub at line 313 of file CbmRichGeoTest.h
Referenced by DrawHist(), FitAndFillHistEllipse(), and InitHistograms().
TH2D* CbmRichGeoTest::fhBaxisVsNofHits private
Definition at line 326 of file CbmRichGeoTest.h.
View newest version in sPHENIX GitHub at line 326 of file CbmRichGeoTest.h
Referenced by DrawHist(), FitAndFillHistEllipse(), and InitHistograms().
TH3D* CbmRichGeoTest::fhBaxisXYZ private
Definition at line 374 of file CbmRichGeoTest.h.
View newest version in sPHENIX GitHub at line 374 of file CbmRichGeoTest.h
Referenced by DrawHist(), InitHistograms(), and RingParameters().
vector<TH1D*> CbmRichGeoTest::fhBoverA private
Definition at line 314 of file CbmRichGeoTest.h.
View newest version in sPHENIX GitHub at line 314 of file CbmRichGeoTest.h
Referenced by DrawHist(), FitAndFillHistEllipse(), and InitHistograms().
TH3D* CbmRichGeoTest::fhBoverAXYZ private
Definition at line 373 of file CbmRichGeoTest.h.
View newest version in sPHENIX GitHub at line 373 of file CbmRichGeoTest.h
Referenced by DrawHist(), InitHistograms(), and RingParameters().
vector<TH2D*> CbmRichGeoTest::fhChi2CircleVsMom private
Definition at line 320 of file CbmRichGeoTest.h.
View newest version in sPHENIX GitHub at line 320 of file CbmRichGeoTest.h
Referenced by DrawHist(), FitAndFillHistCircle(), and InitHistograms().
vector<TH2D*> CbmRichGeoTest::fhChi2EllipseVsMom private
Definition at line 316 of file CbmRichGeoTest.h.
View newest version in sPHENIX GitHub at line 316 of file CbmRichGeoTest.h
Referenced by DrawHist(), FitAndFillHistEllipse(), and InitHistograms().
TH2D* CbmRichGeoTest::fhDiffAaxis private
Definition at line 330 of file CbmRichGeoTest.h.
View newest version in sPHENIX GitHub at line 330 of file CbmRichGeoTest.h
Referenced by DrawHist(), FillMcVsHitFitEllipse(), and InitHistograms().
TH2D* CbmRichGeoTest::fhDiffBaxis private
Definition at line 331 of file CbmRichGeoTest.h.
View newest version in sPHENIX GitHub at line 331 of file CbmRichGeoTest.h
Referenced by DrawHist(), FillMcVsHitFitEllipse(), and InitHistograms().
TH2D* CbmRichGeoTest::fhDiffRadius private
Definition at line 337 of file CbmRichGeoTest.h.
View newest version in sPHENIX GitHub at line 337 of file CbmRichGeoTest.h
Referenced by DrawHist(), FillMcVsHitFitCircle(), and InitHistograms().
TH2D* CbmRichGeoTest::fhDiffXcCircle private
Definition at line 335 of file CbmRichGeoTest.h.
View newest version in sPHENIX GitHub at line 335 of file CbmRichGeoTest.h
Referenced by DrawHist(), FillMcVsHitFitCircle(), and InitHistograms().
TH2D* CbmRichGeoTest::fhDiffXcEllipse private
Definition at line 332 of file CbmRichGeoTest.h.
View newest version in sPHENIX GitHub at line 332 of file CbmRichGeoTest.h
Referenced by DrawHist(), FillMcVsHitFitEllipse(), and InitHistograms().
TH1D* CbmRichGeoTest::fhDiffXhit private
Definition at line 340 of file CbmRichGeoTest.h.
View newest version in sPHENIX GitHub at line 340 of file CbmRichGeoTest.h
Referenced by DrawHist(), HitsAndPoints(), and InitHistograms().
TH2D* CbmRichGeoTest::fhDiffYcCircle private
Definition at line 336 of file CbmRichGeoTest.h.
View newest version in sPHENIX GitHub at line 336 of file CbmRichGeoTest.h
Referenced by DrawHist(), FillMcVsHitFitCircle(), and InitHistograms().
TH2D* CbmRichGeoTest::fhDiffYcEllipse private
Definition at line 333 of file CbmRichGeoTest.h.
View newest version in sPHENIX GitHub at line 333 of file CbmRichGeoTest.h
Referenced by DrawHist(), FillMcVsHitFitEllipse(), and InitHistograms().
TH1D* CbmRichGeoTest::fhDiffYhit private
Definition at line 341 of file CbmRichGeoTest.h.
View newest version in sPHENIX GitHub at line 341 of file CbmRichGeoTest.h
Referenced by DrawHist(), HitsAndPoints(), and InitHistograms().
vector<TH2D*> CbmRichGeoTest::fhDRVsMom private
Definition at line 321 of file CbmRichGeoTest.h.
View newest version in sPHENIX GitHub at line 321 of file CbmRichGeoTest.h
Referenced by DrawHist(), FitAndFillHistCircle(), and InitHistograms().
TH3D* CbmRichGeoTest::fhdRXYZ private
Definition at line 377 of file CbmRichGeoTest.h.
View newest version in sPHENIX GitHub at line 377 of file CbmRichGeoTest.h
Referenced by DrawHist(), InitHistograms(), and RingParameters().
TH2D* CbmRichGeoTest::fhHitsXY private
Definition at line 304 of file CbmRichGeoTest.h.
View newest version in sPHENIX GitHub at line 304 of file CbmRichGeoTest.h
Referenced by DrawHist(), HitsAndPoints(), and InitHistograms().
vector<TH1*> CbmRichGeoTest::fHists private
Definition at line 379 of file CbmRichGeoTest.h.
View newest version in sPHENIX GitHub at line 379 of file CbmRichGeoTest.h
Referenced by Finish(), and InitHistograms().
vector<TH1D*> CbmRichGeoTest::fhNofHits private
Definition at line 310 of file CbmRichGeoTest.h.
View newest version in sPHENIX GitHub at line 310 of file CbmRichGeoTest.h
Referenced by CreateAccVsMinNofHitsHist(), DrawHist(), Finish(), FitAndFillHistEllipse(), and InitHistograms().
TH1D* CbmRichGeoTest::fhNofHitsAll private
Definition at line 350 of file CbmRichGeoTest.h.
View newest version in sPHENIX GitHub at line 350 of file CbmRichGeoTest.h
Referenced by DrawHist(), InitHistograms(), and RingParameters().
TH1D* CbmRichGeoTest::fhNofHitsCircleFit private
Definition at line 351 of file CbmRichGeoTest.h.
View newest version in sPHENIX GitHub at line 351 of file CbmRichGeoTest.h
Referenced by DrawHist(), InitHistograms(), and RingParameters().
TH1D* CbmRichGeoTest::fhNofHitsCircleFitEff private
Definition at line 355 of file CbmRichGeoTest.h.
View newest version in sPHENIX GitHub at line 355 of file CbmRichGeoTest.h
Referenced by DrawHist(), and InitHistograms().
TH1D* CbmRichGeoTest::fhNofHitsEllipseFit private
Definition at line 353 of file CbmRichGeoTest.h.
View newest version in sPHENIX GitHub at line 353 of file CbmRichGeoTest.h
Referenced by DrawHist(), InitHistograms(), and RingParameters().
TH1D* CbmRichGeoTest::fhNofHitsEllipseFitEff private
Definition at line 356 of file CbmRichGeoTest.h.
View newest version in sPHENIX GitHub at line 356 of file CbmRichGeoTest.h
Referenced by DrawHist(), and InitHistograms().
TH3D* CbmRichGeoTest::fhNofHitsXYZ private
Definition at line 371 of file CbmRichGeoTest.h.
View newest version in sPHENIX GitHub at line 371 of file CbmRichGeoTest.h
Referenced by DrawHist(), InitHistograms(), and RingParameters().
TH1D* CbmRichGeoTest::fhNofPhotonsPerHit private
Definition at line 306 of file CbmRichGeoTest.h.
View newest version in sPHENIX GitHub at line 306 of file CbmRichGeoTest.h
Referenced by DrawHist(), Finish(), HitsAndPoints(), and InitHistograms().
TH3D* CbmRichGeoTest::fhNofPointsXYZ private
Definition at line 372 of file CbmRichGeoTest.h.
View newest version in sPHENIX GitHub at line 372 of file CbmRichGeoTest.h
Referenced by DrawHist(), InitHistograms(), and RingParameters().
TH2D* CbmRichGeoTest::fhPointsXY private
Definition at line 305 of file CbmRichGeoTest.h.
View newest version in sPHENIX GitHub at line 305 of file CbmRichGeoTest.h
Referenced by DrawHist(), HitsAndPoints(), and InitHistograms().
vector<TH2D*> CbmRichGeoTest::fhRadiusVsMom private
Definition at line 319 of file CbmRichGeoTest.h.
View newest version in sPHENIX GitHub at line 319 of file CbmRichGeoTest.h
Referenced by DrawHist(), FitAndFillHistCircle(), and InitHistograms().
TH2D* CbmRichGeoTest::fhRadiusVsNofHits private
Definition at line 324 of file CbmRichGeoTest.h.
View newest version in sPHENIX GitHub at line 324 of file CbmRichGeoTest.h
Referenced by DrawHist(), FitAndFillHistCircle(), and InitHistograms().
TH3D* CbmRichGeoTest::fhRadiusXYZ private
Definition at line 376 of file CbmRichGeoTest.h.
View newest version in sPHENIX GitHub at line 376 of file CbmRichGeoTest.h
Referenced by DrawHist(), InitHistograms(), and RingParameters().
vector<TH2D*> CbmRichGeoTest::fhXcYcCircle private
Definition at line 318 of file CbmRichGeoTest.h.
View newest version in sPHENIX GitHub at line 318 of file CbmRichGeoTest.h
Referenced by DrawHist(), FitAndFillHistCircle(), and InitHistograms().
vector<TH2D*> CbmRichGeoTest::fhXcYcEllipse private
Definition at line 315 of file CbmRichGeoTest.h.
View newest version in sPHENIX GitHub at line 315 of file CbmRichGeoTest.h
Referenced by DrawHist(), FitAndFillHistEllipse(), and InitHistograms().
Double_t CbmRichGeoTest::fMaxAaxis private
Definition at line 345 of file CbmRichGeoTest.h.
View newest version in sPHENIX GitHub at line 345 of file CbmRichGeoTest.h
Referenced by CbmRichGeoTest(), and RingParameters().
Double_t CbmRichGeoTest::fMaxBaxis private
Definition at line 347 of file CbmRichGeoTest.h.
View newest version in sPHENIX GitHub at line 347 of file CbmRichGeoTest.h
Referenced by CbmRichGeoTest(), FitAndFillHistEllipse(), and RingParameters().
Double_t CbmRichGeoTest::fMaxRadius private
Definition at line 349 of file CbmRichGeoTest.h.
View newest version in sPHENIX GitHub at line 349 of file CbmRichGeoTest.h
Referenced by CbmRichGeoTest(), and RingParameters().
TClonesArray* CbmRichGeoTest::fMCTracks private
Definition at line 285 of file CbmRichGeoTest.h.
View newest version in sPHENIX GitHub at line 285 of file CbmRichGeoTest.h
Referenced by FillMcHist(), Init(), and RingParameters().
Double_t CbmRichGeoTest::fMinAaxis private
Definition at line 344 of file CbmRichGeoTest.h.
View newest version in sPHENIX GitHub at line 344 of file CbmRichGeoTest.h
Referenced by CbmRichGeoTest(), FitAndFillHistEllipse(), and RingParameters().
Double_t CbmRichGeoTest::fMinBaxis private
Definition at line 346 of file CbmRichGeoTest.h.
View newest version in sPHENIX GitHub at line 346 of file CbmRichGeoTest.h
Referenced by CbmRichGeoTest(), FitAndFillHistEllipse(), and RingParameters().
Int_t CbmRichGeoTest::fMinNofHits private
Definition at line 302 of file CbmRichGeoTest.h.
View newest version in sPHENIX GitHub at line 302 of file CbmRichGeoTest.h
Referenced by CbmRichGeoTest(), and RingParameters().
Double_t CbmRichGeoTest::fMinRadius private
Definition at line 348 of file CbmRichGeoTest.h.
View newest version in sPHENIX GitHub at line 348 of file CbmRichGeoTest.h
Referenced by CbmRichGeoTest(), and RingParameters().
Int_t CbmRichGeoTest::fNofDrawnRings private
Definition at line 381 of file CbmRichGeoTest.h.
View newest version in sPHENIX GitHub at line 381 of file CbmRichGeoTest.h
Referenced by CbmRichGeoTest(), DrawRing(), and RingParameters().
string CbmRichGeoTest::fOutputDir private
Definition at line 280 of file CbmRichGeoTest.h.
View newest version in sPHENIX GitHub at line 280 of file CbmRichGeoTest.h
Referenced by SaveCanvasToImage().
CbmGeoRichPar* CbmRichGeoTest::fPar private
Definition at line 293 of file CbmRichGeoTest.h.
View newest version in sPHENIX GitHub at line 293 of file CbmRichGeoTest.h
Referenced by Init(), and SetParContainers().
TObjArray* CbmRichGeoTest::fPassNodes private
Definition at line 292 of file CbmRichGeoTest.h.
View newest version in sPHENIX GitHub at line 292 of file CbmRichGeoTest.h
Referenced by Init().
Double_t CbmRichGeoTest::fPhi private
Definition at line 290 of file CbmRichGeoTest.h.
View newest version in sPHENIX GitHub at line 290 of file CbmRichGeoTest.h
Referenced by HitsAndPoints(), Init(), and RingParameters().
string CbmRichGeoTest::fRichDetectorType private
Definition at line 278 of file CbmRichGeoTest.h.
View newest version in sPHENIX GitHub at line 278 of file CbmRichGeoTest.h
Referenced by Init(), and InitHistograms().
TClonesArray* CbmRichGeoTest::fRichHits private
Definition at line 282 of file CbmRichGeoTest.h.
View newest version in sPHENIX GitHub at line 282 of file CbmRichGeoTest.h
Referenced by HitsAndPoints(), and Init().
TClonesArray* CbmRichGeoTest::fRichPoints private
Definition at line 284 of file CbmRichGeoTest.h.
View newest version in sPHENIX GitHub at line 284 of file CbmRichGeoTest.h
Referenced by HitsAndPoints(), Init(), and RingParameters().
TClonesArray* CbmRichGeoTest::fRichRingMatches private
Definition at line 286 of file CbmRichGeoTest.h.
View newest version in sPHENIX GitHub at line 286 of file CbmRichGeoTest.h
Referenced by Init(), and RingParameters().
TClonesArray* CbmRichGeoTest::fRichRings private
Definition at line 283 of file CbmRichGeoTest.h.
View newest version in sPHENIX GitHub at line 283 of file CbmRichGeoTest.h
Referenced by Init(), and RingParameters().
TObjArray* CbmRichGeoTest::fSensNodes private
Definition at line 291 of file CbmRichGeoTest.h.
View newest version in sPHENIX GitHub at line 291 of file CbmRichGeoTest.h
Referenced by Init().
CbmRichRingFitterEllipseTau* CbmRichGeoTest::fTauFit private
Definition at line 297 of file CbmRichGeoTest.h.
View newest version in sPHENIX GitHub at line 297 of file CbmRichGeoTest.h
Referenced by FitAndFillHistEllipse(), and Init().
Double_t CbmRichGeoTest::fTheta private
Definition at line 289 of file CbmRichGeoTest.h.
View newest version in sPHENIX GitHub at line 289 of file CbmRichGeoTest.h
Referenced by HitsAndPoints(), Init(), and RingParameters().
The documentation for this class was generated from the following files:
EicRoot/blob/master/rich/qa/CbmRichGeoTest.h
EicRoot/blob/master/rich/qa/CbmRichGeoTest.cxx