EIC Software: G4JLeicBeamLineMagnetSteppingAction Class Reference
G4JLeicBeamLineMagnetSteppingAction Class Reference
#include <fun4all_eicdetectors/blob/master/simulation/g4simulation/g4jleic/G4JLeicBeamLineMagnetSteppingAction.h>
Public Member Functions
G4JLeicBeamLineMagnetSteppingAction (G4JLeicBeamLineMagnetDetector *, const PHParameters *parameters)
constructor
virtual ~G4JLeicBeamLineMagnetSteppingAction ()
destructor
virtual bool UserSteppingAction (const G4Step *, bool)
stepping action
virtual void SetInterfacePointers (PHCompositeNode *)
reimplemented from base class
G4JLeicBeamLineMagnetSteppingAction (G4JLeicBeamLineMagnetDetector *, const PHParameters *parameters)
constructor
virtual ~G4JLeicBeamLineMagnetSteppingAction ()
destructor
virtual bool UserSteppingAction (const G4Step *, bool)
stepping action
virtual void SetInterfacePointers (PHCompositeNode *)
reimplemented from base class
Public Member Functions inherited from PHG4SteppingAction
PHG4SteppingAction (const std::string &name, const int i=0)
virtual ~PHG4SteppingAction ()
virtual void Verbosity (const int i)
virtual int Verbosity () const
virtual int Init ()
virtual double GetScintLightYield (const G4Step *step)
get scintillation photon count. It require a custom set SCINTILLATIONYIELD property to work
virtual double GetVisibleEnergyDeposition (const G4Step *step)
get amount of energy that can make scintillation light, in Unit of GeV.
virtual void StoreLocalCoordinate (PHG4Hit *hit, const G4Step *step, const bool do_prepoint, const bool do_postpoint)
Extract local coordinate of the hit and save to PHG4Hit.
virtual void Print (const std::string &) const
std::string GetName () const
void SetName (const std::string &name)
virtual void SetLightCorrection (const double inner_radius, const double inner_corr, const double outer_radius, const double outer_corr)
virtual double GetLightCorrection (const double r) const
virtual double GetLightCorrection (const double xpos, const double ypos) const
virtual bool ValidCorrection () const
virtual void SetHitNodeName (const std::string &, const std::string &)
Set the G4HIT node names from Subsystem rather than constructing your own.
Private Attributes
G4JLeicBeamLineMagnetDetector * m_Detector
pointer to the detector
PHG4HitContainer * m_HitContainer
pointer to hit container
PHG4HitContainer * m_AbsorberHitContainer
PHG4Hit * m_Hit
PHG4HitContainer * m_SaveHitContainer
G4VPhysicalVolume * m_SaveVolPre
G4VPhysicalVolume * m_SaveVolPost
int m_SaveTrackId
int m_SavePreStepStatus
int m_SavePostStepStatus
double m_EdepSum
double m_EionSum
Detailed Description
Definition at line 16 of file G4JLeicBeamLineMagnetSteppingAction.h.
View newest version in sPHENIX GitHub at line 16 of file G4JLeicBeamLineMagnetSteppingAction.h
Constructor & Destructor Documentation
G4JLeicBeamLineMagnetSteppingAction::G4JLeicBeamLineMagnetSteppingAction (G4JLeicBeamLineMagnetDetector * detector, const PHParameters * parameters)
constructor
Definition at line 41 of file G4JLeicBeamLineMagnetSteppingAction.cc.
View newest version in sPHENIX GitHub at line 41 of file G4JLeicBeamLineMagnetSteppingAction.cc
G4JLeicBeamLineMagnetSteppingAction::~G4JLeicBeamLineMagnetSteppingAction () virtual
destructor
Definition at line 58 of file G4JLeicBeamLineMagnetSteppingAction.cc.
View newest version in sPHENIX GitHub at line 58 of file G4JLeicBeamLineMagnetSteppingAction.cc
References m_Hit.
G4JLeicBeamLineMagnetSteppingAction::G4JLeicBeamLineMagnetSteppingAction (G4JLeicBeamLineMagnetDetector * , const PHParameters * parameters)
constructor
virtual G4JLeicBeamLineMagnetSteppingAction::~G4JLeicBeamLineMagnetSteppingAction () virtual
destructor
Member Function Documentation
void G4JLeicBeamLineMagnetSteppingAction::SetInterfacePointers (PHCompositeNode * topNode) virtual
reimplemented from base class
Reimplemented from PHG4SteppingAction.
Definition at line 282 of file G4JLeicBeamLineMagnetSteppingAction.cc.
View newest version in sPHENIX GitHub at line 282 of file G4JLeicBeamLineMagnetSteppingAction.cc
References PHG4Detector::GetName(), m_AbsorberHitContainer, m_Detector, m_HitContainer, G4JLeicBeamLineMagnetDetector::SuperDetector(), and PHG4SteppingAction::Verbosity().
virtual void G4JLeicBeamLineMagnetSteppingAction::SetInterfacePointers (PHCompositeNode *) virtual
reimplemented from base class
Reimplemented from PHG4SteppingAction.
virtual bool G4JLeicBeamLineMagnetSteppingAction::UserSteppingAction (const G4Step * , bool) virtual
stepping action
Implements PHG4SteppingAction.
bool G4JLeicBeamLineMagnetSteppingAction::UserSteppingAction (const G4Step * aStep, bool was_used) virtual
stepping action
Implements PHG4SteppingAction.
Definition at line 68 of file G4JLeicBeamLineMagnetSteppingAction.cc.
View newest version in sPHENIX GitHub at line 68 of file G4JLeicBeamLineMagnetSteppingAction.cc
References PHG4HitContainer::AddHit(), Acts::UnitConstants::cm, PHG4Hit::get_hit_id(), PHG4Hit::get_x(), PHG4HitContainer::GetID(), PHG4SteppingAction::GetName(), PHG4StepStatusDecode::GetStepStatus(), Acts::UnitConstants::GeV, G4JLeicBeamLineMagnetDetector::IsInBeamLineMagnet(), m_AbsorberHitContainer, m_Detector, m_EdepSum, m_EionSum, m_Hit, m_HitContainer, m_SaveHitContainer, m_SavePostStepStatus, m_SavePreStepStatus, m_SaveTrackId, m_SaveVolPost, m_SaveVolPre, p, PHG4Hit::Reset(), PHG4Hit::set_edep(), PHG4Hit::set_eion(), PHG4Hit::set_layer(), PHG4Hit::set_t(), PHG4Hit::set_trkid(), PHG4Hit::set_x(), PHG4Hit::set_y(), PHG4Hit::set_z(), and Acts::Test::volume.
Member Data Documentation
PHG4HitContainer * G4JLeicBeamLineMagnetSteppingAction::m_AbsorberHitContainer private
Definition at line 36 of file G4JLeicBeamLineMagnetSteppingAction.h.
View newest version in sPHENIX GitHub at line 36 of file G4JLeicBeamLineMagnetSteppingAction.h
Referenced by SetInterfacePointers(), and UserSteppingAction().
G4JLeicBeamLineMagnetDetector * G4JLeicBeamLineMagnetSteppingAction::m_Detector private
pointer to the detector
Definition at line 33 of file G4JLeicBeamLineMagnetSteppingAction.h.
View newest version in sPHENIX GitHub at line 33 of file G4JLeicBeamLineMagnetSteppingAction.h
Referenced by SetInterfacePointers(), and UserSteppingAction().
double G4JLeicBeamLineMagnetSteppingAction::m_EdepSum private
Definition at line 45 of file G4JLeicBeamLineMagnetSteppingAction.h.
View newest version in sPHENIX GitHub at line 45 of file G4JLeicBeamLineMagnetSteppingAction.h
Referenced by UserSteppingAction().
double G4JLeicBeamLineMagnetSteppingAction::m_EionSum private
Definition at line 46 of file G4JLeicBeamLineMagnetSteppingAction.h.
View newest version in sPHENIX GitHub at line 46 of file G4JLeicBeamLineMagnetSteppingAction.h
Referenced by UserSteppingAction().
PHG4Hit * G4JLeicBeamLineMagnetSteppingAction::m_Hit private
Definition at line 37 of file G4JLeicBeamLineMagnetSteppingAction.h.
View newest version in sPHENIX GitHub at line 37 of file G4JLeicBeamLineMagnetSteppingAction.h
Referenced by UserSteppingAction(), and ~G4JLeicBeamLineMagnetSteppingAction().
PHG4HitContainer * G4JLeicBeamLineMagnetSteppingAction::m_HitContainer private
pointer to hit container
Definition at line 35 of file G4JLeicBeamLineMagnetSteppingAction.h.
View newest version in sPHENIX GitHub at line 35 of file G4JLeicBeamLineMagnetSteppingAction.h
Referenced by SetInterfacePointers(), and UserSteppingAction().
PHG4HitContainer * G4JLeicBeamLineMagnetSteppingAction::m_SaveHitContainer private
Definition at line 38 of file G4JLeicBeamLineMagnetSteppingAction.h.
View newest version in sPHENIX GitHub at line 38 of file G4JLeicBeamLineMagnetSteppingAction.h
Referenced by UserSteppingAction().
int G4JLeicBeamLineMagnetSteppingAction::m_SavePostStepStatus private
Definition at line 44 of file G4JLeicBeamLineMagnetSteppingAction.h.
View newest version in sPHENIX GitHub at line 44 of file G4JLeicBeamLineMagnetSteppingAction.h
Referenced by UserSteppingAction().
int G4JLeicBeamLineMagnetSteppingAction::m_SavePreStepStatus private
Definition at line 43 of file G4JLeicBeamLineMagnetSteppingAction.h.
View newest version in sPHENIX GitHub at line 43 of file G4JLeicBeamLineMagnetSteppingAction.h
Referenced by UserSteppingAction().
int G4JLeicBeamLineMagnetSteppingAction::m_SaveTrackId private
Definition at line 42 of file G4JLeicBeamLineMagnetSteppingAction.h.
View newest version in sPHENIX GitHub at line 42 of file G4JLeicBeamLineMagnetSteppingAction.h
Referenced by UserSteppingAction().
G4VPhysicalVolume * G4JLeicBeamLineMagnetSteppingAction::m_SaveVolPost private
Definition at line 41 of file G4JLeicBeamLineMagnetSteppingAction.h.
View newest version in sPHENIX GitHub at line 41 of file G4JLeicBeamLineMagnetSteppingAction.h
Referenced by UserSteppingAction().
G4VPhysicalVolume * G4JLeicBeamLineMagnetSteppingAction::m_SaveVolPre private
Definition at line 40 of file G4JLeicBeamLineMagnetSteppingAction.h.
View newest version in sPHENIX GitHub at line 40 of file G4JLeicBeamLineMagnetSteppingAction.h
Referenced by UserSteppingAction().
The documentation for this class was generated from the following files:
fun4all_eicdetectors/blob/master/simulation/g4simulation/g4jleic/G4JLeicBeamLineMagnetSteppingAction.h
fun4all_g4jleic/blob/master/source/G4JLeicBeamLineMagnetSteppingAction.h
fun4all_eicdetectors/blob/master/simulation/g4simulation/g4jleic/G4JLeicBeamLineMagnetSteppingAction.cc
fun4all_g4jleic/blob/master/source/G4JLeicBeamLineMagnetSteppingAction.cc