EIC Software: FairGeoOldAsciiIo Class Reference
FairGeoOldAsciiIo Class Reference
#include <EicRoot/blob/master/geobase/FairGeoOldAsciiIo.h>
Public Member Functions
FairGeoOldAsciiIo ()
~FairGeoOldAsciiIo ()
void setDirectory (const char *fDir)
const char * getDirectory ()
const char * getFilename ()
Bool_t open (const char *, const Text_t *status="in")
Bool_t isOpen ()
Bool_t isWritable ()
void close ()
void print ()
Bool_t read (FairGeoMedia *)
Bool_t read (FairGeoSet *, FairGeoMedia *)
Bool_t write (FairGeoMedia *)
Bool_t write (FairGeoSet *set)
Bool_t readGeomConfig (FairGeoInterface *)
Bool_t readDetectorSetup (FairGeoInterface *)
Bool_t setSimulRefRun (const char *)
Bool_t setHistoryDate (const char *)
Private Member Functions
Bool_t calculateShapePoints (Double_t *, FairGeoNode *)
FairGeoOldAsciiIo (const FairGeoOldAsciiIo &)
FairGeoOldAsciiIo & operator= (const FairGeoOldAsciiIo &)
Private Attributes
TString filename
TString filedir
Bool_t writable
std::fstream * file
Detailed Description
Class for geometry I/O from ASCII file in FAIR format
Author
Ilse koenig
Definition at line 16 of file FairGeoOldAsciiIo.h.
View newest version in sPHENIX GitHub at line 16 of file FairGeoOldAsciiIo.h
Constructor & Destructor Documentation
FairGeoOldAsciiIo::FairGeoOldAsciiIo ()
FairGeoOldAsciiIo::~FairGeoOldAsciiIo ()
Definition at line 37 of file FairGeoOldAsciiIo.cxx.
View newest version in sPHENIX GitHub at line 37 of file FairGeoOldAsciiIo.cxx
References close(), and file.
FairGeoOldAsciiIo::FairGeoOldAsciiIo (const FairGeoOldAsciiIo &) private
Member Function Documentation
Bool_t FairGeoOldAsciiIo::calculateShapePoints (Double_t * par, FairGeoNode * volu) private
Definition at line 192 of file FairGeoOldAsciiIo.cxx.
View newest version in sPHENIX GitHub at line 192 of file FairGeoOldAsciiIo.cxx
References FairGeoVolume::createPoints(), FairGeoBasicShape::getNumPoints(), FairGeoNode::getShapePointer(), n, FairGeoVolume::setPoint(), x, y, and z.
Referenced by read().
void FairGeoOldAsciiIo::close () virtual
Implements FairGeoIo.
Definition at line 96 of file FairGeoOldAsciiIo.cxx.
View newest version in sPHENIX GitHub at line 96 of file FairGeoOldAsciiIo.cxx
References file, filename, and isOpen().
Referenced by open(), and ~FairGeoOldAsciiIo().
const char* FairGeoOldAsciiIo::getDirectory () inline
Definition at line 26 of file FairGeoOldAsciiIo.h.
View newest version in sPHENIX GitHub at line 26 of file FairGeoOldAsciiIo.h
References filedir.
const char* FairGeoOldAsciiIo::getFilename () inline
Definition at line 27 of file FairGeoOldAsciiIo.h.
View newest version in sPHENIX GitHub at line 27 of file FairGeoOldAsciiIo.h
References filename.
Bool_t FairGeoOldAsciiIo::isOpen () virtual
Implements FairGeoIo.
Definition at line 82 of file FairGeoOldAsciiIo.cxx.
View newest version in sPHENIX GitHub at line 82 of file FairGeoOldAsciiIo.cxx
References file.
Referenced by close(), isWritable(), open(), print(), and read().
Bool_t FairGeoOldAsciiIo::isWritable () virtual
Implements FairGeoIo.
Definition at line 89 of file FairGeoOldAsciiIo.cxx.
View newest version in sPHENIX GitHub at line 89 of file FairGeoOldAsciiIo.cxx
References isOpen(), and writable.
Bool_t FairGeoOldAsciiIo::open (const char * fname, const Text_t * status = "in") virtual
Implements FairGeoIo.
Definition at line 47 of file FairGeoOldAsciiIo.cxx.
View newest version in sPHENIX GitHub at line 47 of file FairGeoOldAsciiIo.cxx
References close(), file, filedir, filename, in, isOpen(), and writable.
FairGeoOldAsciiIo& FairGeoOldAsciiIo::operator= (const FairGeoOldAsciiIo &) private
void FairGeoOldAsciiIo::print () virtual
Implements FairGeoIo.
Definition at line 105 of file FairGeoOldAsciiIo.cxx.
View newest version in sPHENIX GitHub at line 105 of file FairGeoOldAsciiIo.cxx
References filename, isOpen(), and writable.
Bool_t FairGeoOldAsciiIo::read (FairGeoMedia *) inline virtual
Implements FairGeoIo.
Definition at line 33 of file FairGeoOldAsciiIo.h.
View newest version in sPHENIX GitHub at line 33 of file FairGeoOldAsciiIo.h
Bool_t FairGeoOldAsciiIo::read (FairGeoSet * set, FairGeoMedia * media) virtual
Implements FairGeoIo.
Definition at line 114 of file FairGeoOldAsciiIo.cxx.
View newest version in sPHENIX GitHub at line 114 of file FairGeoOldAsciiIo.cxx
References FairGeoMedia::addMedium(), calculateShapePoints(), file, FairGeoMedia::getMedium(), FairGeoBasicShape::getNumParam(), FairGeoVolume::getTransform(), isOpen(), FairGeoNode::print(), FairGeoShapes::selectShape(), sensitivity(), FairGeoNode::setMedium(), FairGeoNode::setMother(), FairGeoTransform::setRotMatrix(), FairGeoNode::setShape(), FairGeoTransform::setTransVector(), t, and writable.
Bool_t FairGeoOldAsciiIo::readDetectorSetup (FairGeoInterface *) inline
Definition at line 38 of file FairGeoOldAsciiIo.h.
View newest version in sPHENIX GitHub at line 38 of file FairGeoOldAsciiIo.h
Bool_t FairGeoOldAsciiIo::readGeomConfig (FairGeoInterface *) inline virtual
Implements FairGeoIo.
Definition at line 37 of file FairGeoOldAsciiIo.h.
View newest version in sPHENIX GitHub at line 37 of file FairGeoOldAsciiIo.h
void FairGeoOldAsciiIo::setDirectory (const char * fDir) inline
Definition at line 25 of file FairGeoOldAsciiIo.h.
View newest version in sPHENIX GitHub at line 25 of file FairGeoOldAsciiIo.h
References filedir.
Bool_t FairGeoOldAsciiIo::setHistoryDate (const char *) inline virtual
Implements FairGeoIo.
Definition at line 40 of file FairGeoOldAsciiIo.h.
View newest version in sPHENIX GitHub at line 40 of file FairGeoOldAsciiIo.h
Bool_t FairGeoOldAsciiIo::setSimulRefRun (const char *) inline virtual
Implements FairGeoIo.
Definition at line 39 of file FairGeoOldAsciiIo.h.
View newest version in sPHENIX GitHub at line 39 of file FairGeoOldAsciiIo.h
Bool_t FairGeoOldAsciiIo::write (FairGeoMedia *) inline virtual
Implements FairGeoIo.
Definition at line 35 of file FairGeoOldAsciiIo.h.
View newest version in sPHENIX GitHub at line 35 of file FairGeoOldAsciiIo.h
Bool_t FairGeoOldAsciiIo::write (FairGeoSet * set) inline virtual
Implements FairGeoIo.
Definition at line 36 of file FairGeoOldAsciiIo.h.
View newest version in sPHENIX GitHub at line 36 of file FairGeoOldAsciiIo.h
Member Data Documentation
std::fstream* FairGeoOldAsciiIo::file private
Definition at line 21 of file FairGeoOldAsciiIo.h.
View newest version in sPHENIX GitHub at line 21 of file FairGeoOldAsciiIo.h
Referenced by close(), isOpen(), open(), read(), and ~FairGeoOldAsciiIo().
TString FairGeoOldAsciiIo::filedir private
Definition at line 19 of file FairGeoOldAsciiIo.h.
View newest version in sPHENIX GitHub at line 19 of file FairGeoOldAsciiIo.h
Referenced by getDirectory(), open(), and setDirectory().
TString FairGeoOldAsciiIo::filename private
Definition at line 18 of file FairGeoOldAsciiIo.h.
View newest version in sPHENIX GitHub at line 18 of file FairGeoOldAsciiIo.h
Referenced by close(), getFilename(), open(), and print().
Bool_t FairGeoOldAsciiIo::writable private
Definition at line 20 of file FairGeoOldAsciiIo.h.
View newest version in sPHENIX GitHub at line 20 of file FairGeoOldAsciiIo.h
Referenced by isWritable(), open(), print(), and read().
The documentation for this class was generated from the following files:
EicRoot/blob/master/geobase/FairGeoOldAsciiIo.h
EicRoot/blob/master/geobase/FairGeoOldAsciiIo.cxx