EIC Software: FW::ParametricProcessGenerator Class Reference
FW::ParametricProcessGenerator Class Reference
#include <fun4all_acts/blob/master/Examples/Algorithms/Generators/ACTFW/Generators/ParametricProcessGenerator.hpp>
Classes
struct Config
Public Member Functions
ParametricProcessGenerator (const Config &cfg)
std::vector< SimVertex > operator() (RandomEngine &rng) const
Generate a single process vertex with the given number of particles.
Private Attributes
Config m_cfg
double m_charge
double m_mass
Detailed Description
Generate particles from uniform parameter distributions.
Generates a single process vertex with the given number of tracks. Each track's momentum and direction is drawn from uniform parameter distributions. Position and time are always set to zero.
Definition at line 27 of file ParametricProcessGenerator.hpp.
View newest version in sPHENIX GitHub at line 27 of file ParametricProcessGenerator.hpp
Constructor & Destructor Documentation
FW::ParametricProcessGenerator::ParametricProcessGenerator (const Config & cfg)
Definition at line 16 of file ParametricProcessGenerator.cpp.
View newest version in sPHENIX GitHub at line 16 of file ParametricProcessGenerator.cpp
Member Function Documentation
std::vector< FW::SimVertex > FW::ParametricProcessGenerator::operator() (FW::RandomEngine & rng) const
Generate a single process vertex with the given number of particles.
Definition at line 22 of file ParametricProcessGenerator.cpp.
View newest version in sPHENIX GitHub at line 22 of file ParametricProcessGenerator.cpp
References cos(), Acts::Test::d0Dist(), Acts::VectorHelpers::eta(), Acts::Test::etaDist(), ip(), Acts::makeDirectionUnitFromPhiEta(), FW::SimVertex::outgoing, particle, pdg, phi, Acts::Test::phiDist(), pid, ActsFatras::Particle::setAbsMomentum(), ActsFatras::Particle::setDirection(), ActsFatras::Barcode::setParticle(), ActsFatras::Particle::setPosition4(), Acts::UnitConstants::u, and Acts::Test::z0Dist().
Member Data Documentation
Config FW::ParametricProcessGenerator::m_cfg private
Definition at line 57 of file ParametricProcessGenerator.hpp.
View newest version in sPHENIX GitHub at line 57 of file ParametricProcessGenerator.hpp
double FW::ParametricProcessGenerator::m_charge private
Definition at line 59 of file ParametricProcessGenerator.hpp.
View newest version in sPHENIX GitHub at line 59 of file ParametricProcessGenerator.hpp
double FW::ParametricProcessGenerator::m_mass private
Definition at line 60 of file ParametricProcessGenerator.hpp.
View newest version in sPHENIX GitHub at line 60 of file ParametricProcessGenerator.hpp
The documentation for this class was generated from the following files:
fun4all_acts/blob/master/Examples/Algorithms/Generators/ACTFW/Generators/ParametricProcessGenerator.hpp
fun4all_acts/blob/master/Examples/Algorithms/Generators/ACTFW/Generators/ParametricProcessGenerator.cpp