EIC Software: eASTStackingAction Class Reference
eASTStackingAction Class Reference
#include <east/blob/main/Core/include/eASTStackingAction.hh>
Public Member Functions
eASTStackingAction ()
virtual ~eASTStackingAction ()
virtual G4ClassificationOfNewTrack ClassifyNewTrack (const G4Track *)
virtual void NewStage ()
virtual void PrepareNewEvent ()
Detailed Description
Definition at line 19 of file eASTStackingAction.hh.
View newest version in sPHENIX GitHub at line 19 of file eASTStackingAction.hh
Constructor & Destructor Documentation
eASTStackingAction::eASTStackingAction ()
Definition at line 16 of file eASTStackingAction.cc.
View newest version in sPHENIX GitHub at line 16 of file eASTStackingAction.cc
eASTStackingAction::~eASTStackingAction () virtual
Definition at line 19 of file eASTStackingAction.cc.
View newest version in sPHENIX GitHub at line 19 of file eASTStackingAction.cc
Member Function Documentation
G4ClassificationOfNewTrack eASTStackingAction::ClassifyNewTrack (const G4Track * trk) virtual
Definition at line 22 of file eASTStackingAction.cc.
View newest version in sPHENIX GitHub at line 22 of file eASTStackingAction.cc
References eASTUserActionDispatcher::GetStackingActions(), and eASTUserActionDispatcher::Instance().
void eASTStackingAction::NewStage () virtual
Definition at line 37 of file eASTStackingAction.cc.
View newest version in sPHENIX GitHub at line 37 of file eASTStackingAction.cc
References eASTUserActionDispatcher::GetStackingActions(), and eASTUserActionDispatcher::Instance().
void eASTStackingAction::PrepareNewEvent () virtual
Definition at line 47 of file eASTStackingAction.cc.
View newest version in sPHENIX GitHub at line 47 of file eASTStackingAction.cc
References eASTUserActionDispatcher::GetStackingActions(), and eASTUserActionDispatcher::Instance().
The documentation for this class was generated from the following files:
east/blob/main/Core/include/eASTStackingAction.hh
east/blob/main/Core/src/eASTStackingAction.cc