EIC Software: delphes_EIC/blob/master/SimpleAnalysis/scripts/PlotFunctions.h File Reference
PlotFunctions.h File Reference
#include "TROOT.h"
#include "TChain.h"
#include "TEfficiency.h"
#include "TH1.h"
#include "TGraphErrors.h"
#include "TCut.h"
#include "TCanvas.h"
#include "TStyle.h"
#include "TLegend.h"
#include "TMath.h"
#include "TLine.h"
#include "TLatex.h"
#include "TRatioPlot.h"
#include "TString.h"
#include <glob.h>
#include <iostream>
#include <iomanip>
#include <vector>
Classes
struct plot_config
Functions
Int_t getHistUID ()
float smart_legend_x (float x_trial, float x_width)
float smart_legend_y (float y_trial, float y_height)
TLegend * smart_legend (std::string where="upper right", float legend_width=0.30, float legend_height=0.10)
void set_axis_range (TH1F *hist, float min, float max, std::string which="X")
template<class T >
void configure_plot (T *object, plot_config options, std::string which="")
TLatex make_title (TString text="CC-DIS, 10GeVx275GeV, Q^{2}>100 GeV^{2}")
std::vector< std::string > fileVector (const std::string &pattern)
float LookupCrossSection (TString samplename)
TH1F * GeneratePlot (plot_config draw_config, TTree *data, TString name, TString x, TCut selection)
Variables
float u_fb = 1.0
float u_mb = 1.0e12 * u_fb
float u_GeV = 1.0
float u_MeV = 1.0e3 * u_GeV
float u_mm = 1.0
float u_cm = 1e2 * u_mm
static Int_t histUID = 0
Function Documentation
template<class T > void configure_plot (T * object, plot_config options, std::string which = "")
Definition at line 150 of file PlotFunctions.h.
View newest version in sPHENIX GitHub at line 150 of file PlotFunctions.h
std::vector<std::string> fileVector (const std::string & pattern) inline
Definition at line 186 of file PlotFunctions.h.
View newest version in sPHENIX GitHub at line 186 of file PlotFunctions.h
References eicpy.build::files.
Referenced by CharmJetClassification(), CharmJetGlobalTagger(), CharmTagPlots(), KaonIDStudy(), main(), StrangeJetClassification(), and StrangeTagPlots().
TH1F* GeneratePlot (plot_config draw_config, TTree * data, TString name, TString x, TCut selection)
Definition at line 213 of file PlotFunctions.h.
View newest version in sPHENIX GitHub at line 213 of file PlotFunctions.h
References plot_config::fillcolor, plot_config::fillstyle, getHistUID(), plot_config::htemplate, plot_config::linecolor, plot_config::linestyle, plot_config::markercolor, plot_config::markerstyle, plot(), plot_config::xtitle, and plot_config::ytitle.
Referenced by KaonIDStudy(), and StrangeTagPlots().
Int_t getHistUID () inline
Definition at line 63 of file PlotFunctions.h.
View newest version in sPHENIX GitHub at line 63 of file PlotFunctions.h
References histUID.
Referenced by CharmTagPlots(), and GeneratePlot().
float LookupCrossSection (TString samplename)
Definition at line 198 of file PlotFunctions.h.
View newest version in sPHENIX GitHub at line 198 of file PlotFunctions.h
References u_mb, and charm_jet_tagging_optimization_study::xsection.
Referenced by CharmJetMVAOptimization().
TLatex make_title (TString text = "CC-DIS, 10GeVx275GeV, Q^{2}>100 GeV^{2}") inline
Definition at line 175 of file PlotFunctions.h.
View newest version in sPHENIX GitHub at line 175 of file PlotFunctions.h
Referenced by CharmTagPlots(), DrawTagEfficiencyPlot(), DrawTagYieldPlot(), and StrangeTagPlots().
void set_axis_range (TH1F * hist, float min, float max, std::string which = "X") inline
Definition at line 137 of file PlotFunctions.h.
View newest version in sPHENIX GitHub at line 137 of file PlotFunctions.h
Referenced by CharmTagPlots(), DrawTagEfficiencyPlot(), and DrawTagYieldPlot().
TLegend* smart_legend (std::string where = "upper right", float legend_width = 0.30, float legend_height = 0.10) inline
Definition at line 99 of file PlotFunctions.h.
View newest version in sPHENIX GitHub at line 99 of file PlotFunctions.h
References smart_legend_x(), and smart_legend_y().
Referenced by CharmJetClassification_Plots(), CharmTagPlots(), DrawTagEfficiencyPlot(), DrawTagYieldPlot(), KaonIDStudy(), and StrangeTagPlots().
float smart_legend_x (float x_trial, float x_width) inline
Definition at line 71 of file PlotFunctions.h.
View newest version in sPHENIX GitHub at line 71 of file PlotFunctions.h
Referenced by smart_legend().
float smart_legend_y (float y_trial, float y_height) inline
Definition at line 85 of file PlotFunctions.h.
View newest version in sPHENIX GitHub at line 85 of file PlotFunctions.h
Referenced by smart_legend().
Variable Documentation
Int_t histUID = 0 static
Definition at line 61 of file PlotFunctions.h.
View newest version in sPHENIX GitHub at line 61 of file PlotFunctions.h
Referenced by DifferentialTaggingEfficiency(), DifferentialTaggingYield(), and getHistUID().
float u_cm = 1e2 * u_mm
Definition at line 35 of file PlotFunctions.h.
View newest version in sPHENIX GitHub at line 35 of file PlotFunctions.h
float u_fb = 1.0
Definition at line 28 of file PlotFunctions.h.
View newest version in sPHENIX GitHub at line 28 of file PlotFunctions.h
Referenced by CharmJetMVAOptimization().
float u_GeV = 1.0
Definition at line 31 of file PlotFunctions.h.
View newest version in sPHENIX GitHub at line 31 of file PlotFunctions.h
float u_mb = 1.0e12 * u_fb
Definition at line 29 of file PlotFunctions.h.
View newest version in sPHENIX GitHub at line 29 of file PlotFunctions.h
Referenced by LookupCrossSection().
float u_MeV = 1.0e3 * u_GeV
Definition at line 32 of file PlotFunctions.h.
View newest version in sPHENIX GitHub at line 32 of file PlotFunctions.h
float u_mm = 1.0
Definition at line 34 of file PlotFunctions.h.
View newest version in sPHENIX GitHub at line 34 of file PlotFunctions.h