EIC Software: CbmMCObject Class Reference
CbmMCObject Class Reference
#include <EicRoot/blob/master/cbmbase/CbmMCObject.h>
Public Member Functions
CbmMCObject ()
CbmMCObject (DataType type)
CbmMCObject (const CbmMCObject &obj)
CbmMCObject (DataType type, std::vector< CbmMCEntry > stage)
virtual ~CbmMCObject ()
void SetStageId (DataType type)
void SetEntry (std::vector< Int_t > type, std::vector< Int_t > link, int index)
void SetEntry (FairMultiLinkedData *data, int index)
void SetEntry (CbmMCEntry link)
void SetStage (std::vector< CbmMCEntry > stage)
void SetLink (FairLink link, int index)
void AddLink (FairLink link, int index)
CbmMCEntry GetEntry (int index) const
FairLink GetSingleLink (int entryIndex, int linkIndex) const
DataType GetStageId (void) const
CbmMCEntry GetMCLink (Int_t index)
int GetNEntries () const
int GetNLinks (int entryIndex) const
std::vector< CbmMCEntry > GetEntryVector () const
FairMultiLinkedData PosInList (FairLink link)
FairMultiLinkedData GetLinksWithType (DataType type)
virtual void ClearEntries ()
virtual void Print (std::ostream &out=std::cout)
CbmMCObject & operator= (const CbmMCObject &obj)
Private Member Functions
void AdoptSize (int index)
ClassDef (CbmMCObject, 0)
Private Attributes
std::vector< CbmMCEntry > fStage
DataType fStageId
Friends
std::ostream & operator<< (std::ostream &out, const CbmMCObject &obj)
Detailed Description
Definition at line 21 of file CbmMCObject.h.
View newest version in sPHENIX GitHub at line 21 of file CbmMCObject.h
Constructor & Destructor Documentation
CbmMCObject::CbmMCObject ()
Definition at line 12 of file CbmMCObject.cxx.
View newest version in sPHENIX GitHub at line 12 of file CbmMCObject.cxx
CbmMCObject::CbmMCObject (DataType type) inline
Definition at line 24 of file CbmMCObject.h.
View newest version in sPHENIX GitHub at line 24 of file CbmMCObject.h
CbmMCObject::CbmMCObject (const CbmMCObject & obj) inline
Definition at line 25 of file CbmMCObject.h.
View newest version in sPHENIX GitHub at line 25 of file CbmMCObject.h
CbmMCObject::CbmMCObject (DataType type, std::vector< CbmMCEntry > stage) inline
Definition at line 28 of file CbmMCObject.h.
View newest version in sPHENIX GitHub at line 28 of file CbmMCObject.h
CbmMCObject::~CbmMCObject () virtual
Definition at line 20 of file CbmMCObject.cxx.
View newest version in sPHENIX GitHub at line 20 of file CbmMCObject.cxx
Member Function Documentation
void CbmMCObject::AddLink (FairLink link, int index)
Definition at line 58 of file CbmMCObject.cxx.
View newest version in sPHENIX GitHub at line 58 of file CbmMCObject.cxx
References AdoptSize(), and fStage.
Referenced by SetLink().
void CbmMCObject::AdoptSize (int index) private
Definition at line 65 of file CbmMCObject.cxx.
View newest version in sPHENIX GitHub at line 65 of file CbmMCObject.cxx
References fStage, GetStageId(), CbmMCEntry::SetPos(), CbmMCEntry::SetSource(), and start().
Referenced by AddLink(), and SetEntry().
CbmMCObject::ClassDef (CbmMCObject , 0) private
virtual void CbmMCObject::ClearEntries () inline virtual
Reimplemented in CbmMCStage.
Definition at line 70 of file CbmMCObject.h.
View newest version in sPHENIX GitHub at line 70 of file CbmMCObject.h
References fStage.
Referenced by CbmMCStage::ClearEntries().
CbmMCEntry CbmMCObject::GetEntry (int index) const inline
Definition at line 46 of file CbmMCObject.h.
View newest version in sPHENIX GitHub at line 46 of file CbmMCObject.h
References fStage.
std::vector<CbmMCEntry> CbmMCObject::GetEntryVector () const inline
Definition at line 57 of file CbmMCObject.h.
View newest version in sPHENIX GitHub at line 57 of file CbmMCObject.h
References fStage.
Referenced by operator=().
FairMultiLinkedData CbmMCObject::GetLinksWithType (DataType type) inline
Definition at line 62 of file CbmMCObject.h.
View newest version in sPHENIX GitHub at line 62 of file CbmMCObject.h
References FairMultiLinkedData::AddLinks(), GetMCLink(), and GetNEntries().
CbmMCEntry CbmMCObject::GetMCLink (Int_t index) inline
Definition at line 53 of file CbmMCObject.h.
View newest version in sPHENIX GitHub at line 53 of file CbmMCObject.h
References fStage.
Referenced by CbmMCMatchCreatorTask::Exec(), and GetLinksWithType().
int CbmMCObject::GetNEntries () const inline
Definition at line 55 of file CbmMCObject.h.
View newest version in sPHENIX GitHub at line 55 of file CbmMCObject.h
References fStage.
Referenced by CbmMCMatchCreatorTask::Exec(), GetLinksWithType(), CbmMCMatch::GetMCInfoBackward(), and CbmMCMatch::GetMCInfoForward().
int CbmMCObject::GetNLinks (int entryIndex) const inline
Definition at line 56 of file CbmMCObject.h.
View newest version in sPHENIX GitHub at line 56 of file CbmMCObject.h
References fStage.
FairLink CbmMCObject::GetSingleLink (int entryIndex, int linkIndex) const inline
Definition at line 47 of file CbmMCObject.h.
View newest version in sPHENIX GitHub at line 47 of file CbmMCObject.h
References fStage.
DataType CbmMCObject::GetStageId (void) const inline
Definition at line 51 of file CbmMCObject.h.
View newest version in sPHENIX GitHub at line 51 of file CbmMCObject.h
References fStageId.
Referenced by AdoptSize(), CbmMCMatchCreatorTask::Exec(), CbmMCMatch::GetMCInfoForward(), operator=(), and PosInList().
CbmMCObject& CbmMCObject::operator= (const CbmMCObject & obj) inline
Definition at line 74 of file CbmMCObject.h.
View newest version in sPHENIX GitHub at line 74 of file CbmMCObject.h
References fStage, fStageId, GetEntryVector(), and GetStageId().
Referenced by CbmMCResult::operator=(), and CbmMCStage::operator=().
FairMultiLinkedData CbmMCObject::PosInList (FairLink link)
Definition at line 78 of file CbmMCObject.cxx.
View newest version in sPHENIX GitHub at line 78 of file CbmMCObject.cxx
References FairMultiLinkedData::AddLink(), fStage, FairLink::GetIndex(), GetStageId(), and FairLink::GetType().
virtual void CbmMCObject::Print (std::ostream & out = std::cout) inline virtual
Reimplemented in CbmMCStage, and CbmMCResult.
Definition at line 72 of file CbmMCObject.h.
View newest version in sPHENIX GitHub at line 72 of file CbmMCObject.h
void CbmMCObject::SetEntry (std::vector< Int_t > type, std::vector< Int_t > link, int index)
Definition at line 34 of file CbmMCObject.cxx.
View newest version in sPHENIX GitHub at line 34 of file CbmMCObject.cxx
References FairMultiLinkedData::AddLink(), and CbmMCEntry::SetPos().
Referenced by CbmMCMatch::GetMCInfoBackward(), and CbmMCMatch::GetMCInfoForward().
void CbmMCObject::SetEntry (FairMultiLinkedData * data, int index)
Definition at line 43 of file CbmMCObject.cxx.
View newest version in sPHENIX GitHub at line 43 of file CbmMCObject.cxx
References AdoptSize(), fStage, and FairMultiLinkedData::GetLinks().
void CbmMCObject::SetEntry (CbmMCEntry link)
Definition at line 25 of file CbmMCObject.cxx.
View newest version in sPHENIX GitHub at line 25 of file CbmMCObject.cxx
References AdoptSize(), fStage, and CbmMCEntry::GetPos().
void CbmMCObject::SetLink (FairLink link, int index)
Definition at line 49 of file CbmMCObject.cxx.
View newest version in sPHENIX GitHub at line 49 of file CbmMCObject.cxx
References AddLink(), and fStage.
void CbmMCObject::SetStage (std::vector< CbmMCEntry > stage) inline
Definition at line 42 of file CbmMCObject.h.
View newest version in sPHENIX GitHub at line 42 of file CbmMCObject.h
References fStage.
void CbmMCObject::SetStageId (DataType type) inline
Definition at line 36 of file CbmMCObject.h.
View newest version in sPHENIX GitHub at line 36 of file CbmMCObject.h
References fStageId.
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & out, const CbmMCObject & obj) friend
Definition at line 81 of file CbmMCObject.h.
View newest version in sPHENIX GitHub at line 81 of file CbmMCObject.h
Member Data Documentation
std::vector<CbmMCEntry> CbmMCObject::fStage private
Definition at line 92 of file CbmMCObject.h.
View newest version in sPHENIX GitHub at line 92 of file CbmMCObject.h
Referenced by AddLink(), AdoptSize(), ClearEntries(), GetEntry(), GetEntryVector(), GetMCLink(), GetNEntries(), GetNLinks(), GetSingleLink(), operator=(), PosInList(), SetEntry(), SetLink(), and SetStage().
DataType CbmMCObject::fStageId private
Definition at line 93 of file CbmMCObject.h.
View newest version in sPHENIX GitHub at line 93 of file CbmMCObject.h
Referenced by GetStageId(), operator=(), and SetStageId().
The documentation for this class was generated from the following files:
EicRoot/blob/master/cbmbase/CbmMCObject.h
EicRoot/blob/master/cbmbase/CbmMCObject.cxx