EIC Software: GeantVolumeLevel Class Reference
GeantVolumeLevel Class Reference
#include <EicRoot/blob/master/eic/base/EicGeoMap.h>
Public Member Functions
GeantVolumeLevel ()
~GeantVolumeLevel ()
const TString & GetVolumeName () const
const EicBitMask< UGeantIndex_t > * GetBitMaskPtr () const
UGeantIndex_t GetMaxEntryNum () const
UGeantIndex_t GetMaskedBits (UGeantIndex_t value) const
GeantVolumeLevel ()
~GeantVolumeLevel ()
const TString & GetVolumeName () const
const EicBitMask< UGeantIndex_t > * GetBitMaskPtr () const
UGeantIndex_t GetMaxEntryNum () const
UGeantIndex_t GetMaskedBits (UGeantIndex_t value) const
Private Member Functions
ClassDef (GeantVolumeLevel, 1)
ClassDef (GeantVolumeLevel, 1)
Private Attributes
UGeantIndex_t mMaxEntryNum
TString mVolumeName
UInt_t mVolumeID
EicBitMask< UGeantIndex_t > * mBitMask
GEANT volume ID in the complete simulation geometry tree;.
Friends
class EicGeoMap
class EicGeoParData
Detailed Description
Definition at line 110 of file EicGeoMap.h.
View newest version in sPHENIX GitHub at line 110 of file EicGeoMap.h
Constructor & Destructor Documentation
GeantVolumeLevel::GeantVolumeLevel () inline
Definition at line 117 of file EicGeoMap.h.
View newest version in sPHENIX GitHub at line 117 of file EicGeoMap.h
GeantVolumeLevel::~GeantVolumeLevel () inline
Definition at line 118 of file EicGeoMap.h.
View newest version in sPHENIX GitHub at line 118 of file EicGeoMap.h
References mBitMask.
GeantVolumeLevel::GeantVolumeLevel () inline
Definition at line 117 of file EicGeoMap.h.
View newest version in sPHENIX GitHub at line 117 of file EicGeoMap.h
GeantVolumeLevel::~GeantVolumeLevel () inline
Definition at line 118 of file EicGeoMap.h.
View newest version in sPHENIX GitHub at line 118 of file EicGeoMap.h
References mBitMask.
Member Function Documentation
GeantVolumeLevel::ClassDef (GeantVolumeLevel , 1) private
GeantVolumeLevel::ClassDef (GeantVolumeLevel , 1) private
const EicBitMask<UGeantIndex_t>* GeantVolumeLevel::GetBitMaskPtr () const inline
Definition at line 121 of file EicGeoMap.h.
View newest version in sPHENIX GitHub at line 121 of file EicGeoMap.h
References mBitMask.
Referenced by EicDetector::GetNodeMultiIndex().
const EicBitMask<UGeantIndex_t>* GeantVolumeLevel::GetBitMaskPtr () const inline
Definition at line 121 of file EicGeoMap.h.
View newest version in sPHENIX GitHub at line 121 of file EicGeoMap.h
References mBitMask.
UGeantIndex_t GeantVolumeLevel::GetMaskedBits (UGeantIndex_t value) const inline
Definition at line 124 of file EicGeoMap.h.
View newest version in sPHENIX GitHub at line 124 of file EicGeoMap.h
References EicBitMask< T >::GetMaskedBits(), and mBitMask.
UGeantIndex_t GeantVolumeLevel::GetMaskedBits (UGeantIndex_t value) const inline
Definition at line 124 of file EicGeoMap.h.
View newest version in sPHENIX GitHub at line 124 of file EicGeoMap.h
References EicBitMask< T >::GetMaskedBits(), and mBitMask.
Referenced by EicGeoParData::InitializeLookupTables().
UGeantIndex_t GeantVolumeLevel::GetMaxEntryNum () const inline
Definition at line 122 of file EicGeoMap.h.
View newest version in sPHENIX GitHub at line 122 of file EicGeoMap.h
References mMaxEntryNum.
UGeantIndex_t GeantVolumeLevel::GetMaxEntryNum () const inline
Definition at line 122 of file EicGeoMap.h.
View newest version in sPHENIX GitHub at line 122 of file EicGeoMap.h
References mMaxEntryNum.
Referenced by EicDetector::GetNodeMultiIndex().
const TString& GeantVolumeLevel::GetVolumeName () const inline
Definition at line 120 of file EicGeoMap.h.
View newest version in sPHENIX GitHub at line 120 of file EicGeoMap.h
References mVolumeName.
const TString& GeantVolumeLevel::GetVolumeName () const inline
Definition at line 120 of file EicGeoMap.h.
View newest version in sPHENIX GitHub at line 120 of file EicGeoMap.h
References mVolumeName.
Referenced by EicGeoMap::GetInnermostVolumeName(), EicGeoParData::InitializeLookupTables(), and EicGeoMap::SetMappingTableEntry().
Friends And Related Function Documentation
EicGeoMap friend
Definition at line 113 of file EicGeoMap.h.
View newest version in sPHENIX GitHub at line 113 of file EicGeoMap.h
EicGeoParData friend
Definition at line 114 of file EicGeoMap.h.
View newest version in sPHENIX GitHub at line 114 of file EicGeoMap.h
Member Data Documentation
EicBitMask< UGeantIndex_t > * GeantVolumeLevel::mBitMask private
GEANT volume ID in the complete simulation geometry tree;.
Definition at line 134 of file EicGeoMap.h.
View newest version in sPHENIX GitHub at line 134 of file EicGeoMap.h
Referenced by EicGeoMap::CalculateBitPattern(), GetBitMaskPtr(), GetMaskedBits(), EicGeoMap::SetMappingTableEntry(), and ~GeantVolumeLevel().
UGeantIndex_t GeantVolumeLevel::mMaxEntryNum private
Definition at line 126 of file EicGeoMap.h.
View newest version in sPHENIX GitHub at line 126 of file EicGeoMap.h
Referenced by EicGeoMap::AddGeantVolumeLevel(), EicGeoMap::CalculateBitPattern(), GetMaxEntryNum(), and EicGeoMap::SetMappingTableEntry().
UInt_t GeantVolumeLevel::mVolumeID private
Definition at line 132 of file EicGeoMap.h.
View newest version in sPHENIX GitHub at line 132 of file EicGeoMap.h
Referenced by EicGeoMap::CalculateMappingTableSignature(), and EicGeoMap::IsMySignature().
TString GeantVolumeLevel::mVolumeName private
Definition at line 130 of file EicGeoMap.h.
View newest version in sPHENIX GitHub at line 130 of file EicGeoMap.h
Referenced by EicGeoMap::AddGeantVolumeLevel(), EicGeoMap::CalculateMappingTableSignature(), and GetVolumeName().
The documentation for this class was generated from the following files:
EicRoot/blob/master/eic/base/EicGeoMap.h
EicToyModel/blob/master/include/EicGeoMap.h