EIC Software: BinaryFunctor Class Reference
BinaryFunctor Class Reference abstract
Base class for all functors which are used in the FairTSBufferFunctional.
#include <EicRoot/blob/master/base/FairTSBufferFunctional.h>
Public Member Functions
virtual bool operator() (FairTimeStamp *a, double b)
virtual bool Call (FairTimeStamp *a, double b)=0
virtual bool TimeOut ()
virtual void ResetTimeOut ()
Detailed Description
Base class for all functors which are used in the FairTSBufferFunctional.
See Also
FairTSBufferFunctional
The class is a base class to control which data is extracted by the FairTSBufferFunctional class for processing. The important method to overwrite is Call. It gets the actual data which is read in from the tree and a parameter. If the actual data is not anymore part of the data you want to have Call returns true to stop the reading of data. Otherwise it should return false. The method TimeOut is used to break the processing if for example always the same data is requested.
Definition at line 27 of file FairTSBufferFunctional.h.
View newest version in sPHENIX GitHub at line 27 of file FairTSBufferFunctional.h
Member Function Documentation
virtual bool BinaryFunctor::Call (FairTimeStamp * a, double b) pure virtual
Implemented in TimeGap, and StopTime.
Referenced by operator()().
virtual bool BinaryFunctor::operator() (FairTimeStamp * a, double b) inline virtual
Definition at line 30 of file FairTSBufferFunctional.h.
View newest version in sPHENIX GitHub at line 30 of file FairTSBufferFunctional.h
References Call().
virtual void BinaryFunctor::ResetTimeOut () inline virtual
Reimplemented in StopTime.
Definition at line 33 of file FairTSBufferFunctional.h.
View newest version in sPHENIX GitHub at line 33 of file FairTSBufferFunctional.h
virtual bool BinaryFunctor::TimeOut () inline virtual
Reimplemented in StopTime.
Definition at line 32 of file FairTSBufferFunctional.h.
View newest version in sPHENIX GitHub at line 32 of file FairTSBufferFunctional.h
Referenced by FairTSBufferFunctional::TimeOut().
The documentation for this class was generated from the following file:
EicRoot/blob/master/base/FairTSBufferFunctional.h