EIC Software: EicRoot/blob/master/eic/cad/elmer/plugins/egmain.h File Reference
egmain.h File Reference
Functions
int eg_loadmesh (const char *filename)
int eg_transfermesh (mesh_t *mesh, const char *str)
Function Documentation
int eg_loadmesh (const char * filename)
Definition at line 1313 of file egmain.cpp.
View newest version in sPHENIX GitHub at line 1313 of file egmain.cpp
References DetermineFileType(), Filename, info, Inmethod, printf(), and TRUE.
int eg_transfermesh (mesh_t * mesh, const char * str)
Definition at line 1335 of file egmain.cpp.
View newest version in sPHENIX GitHub at line 1335 of file egmain.cpp
References activemesh, ConvertEgTypeToMeshType(), data, DestroyBoundary(), DestroyKnots(), eg, FALSE, Filename, ElmergridType::filesin, ImportMeshDefinition(), info, InitGrid(), InitParameters(), InlineParameters(), Inmethod, ElmergridType::inmethod, IOmethods, k, LoadCommands(), ManipulateMeshDefinition(), MAXBOUNDARIES, MAXCASES, MAXFILESIZE, nogrids, nomeshes, printf(), ElmergridType::relh, mesh_t::setEdges(), mesh_t::setElements(), mesh_t::setNodes(), mesh_t::setPoints(), mesh_t::setSurfaces(), ElmergridType::silent, StringToStrings(), and TRUE.