EIC Software: fun4all_macros/blob/master/common/G4_TPC.C File Reference
G4_TPC.C File Reference
#include <GlobalVariables.C>
#include <QA.C>
#include <G4_Intt.C>
#include <G4_Mvtx.C>
#include <g4tpc/PHG4TpcCentralMembrane.h>
#include <g4tpc/PHG4TpcDigitizer.h>
#include <g4tpc/PHG4TpcDirectLaser.h>
#include <g4tpc/PHG4TpcDistortion.h>
#include <g4tpc/PHG4TpcElectronDrift.h>
#include <g4tpc/PHG4TpcEndCapSubsystem.h>
#include <g4tpc/PHG4TpcPadPlane.h>
#include <g4tpc/PHG4TpcPadPlaneReadout.h>
#include <g4tpc/PHG4TpcSubsystem.h>
#include <g4main/PHG4Reco.h>
#include <tpc/TpcClusterizer.h>
#include <tpc/TpcClusterCleaner.h>
#include <tpc/TpcLoadDistortionCorrection.h>
#include <tpccalib/TpcDirectLaserReconstruction.h>
#include <qa_modules/QAG4SimulationTpc.h>
#include <fun4all/Fun4AllServer.h>
Namespaces
namespace Enable
namespace G4TPC
Macros
#define MACRO_G4TPC_C
Functions
void TPCInit ()
void TPC_Endcaps (PHG4Reco *g4Reco)
TPC end cap, wagon wheel, electronics.
double TPC (PHG4Reco *g4Reco, double radius)
void TPC_Cells ()
void TPC_Clustering ()
void TPC_QA ()
Variables
bool Enable::TPC_CELL = false
bool Enable::TPC_CLUSTER = false
bool Enable::TPC_QA = false
int Enable::TPC_VERBOSITY = 0
int G4TPC::n_gas_layer = n_tpc_layer_inner + n_tpc_layer_mid + n_tpc_layer_outer
double G4TPC::tpc_outer_radius = 77. + 2.
double G4TPC::drift_velocity_scale = 1.0
bool G4TPC::ENABLE_STATIC_DISTORTIONS = false
auto G4TPC::static_distortion_filename = std::string(getenv("CALIBRATIONROOT")) + "/TPC/DistortionMaps/fluct_average.rev3.1side.3d.file0.h_negz.real_B1.4_E-400.0.ross_phi1_sphenix_phislice_lookup_r26xp40xz40.distortion_map.hist.root"
bool G4TPC::ENABLE_TIME_ORDERED_DISTORTIONS = false
std::string G4TPC::time_ordered_distortion_filename = "/gpfs/mnt/gpfs02/sphenix/user/klest/TimeOrderedDistortions.root"
bool G4TPC::ENABLE_CORRECTIONS = false
auto G4TPC::correction_filename = std::string(getenv("CALIBRATIONROOT")) + "/TPC/DistortionMaps/fluct_average.rev3.1side.3d.file0.h_negz.real_B1.4_E-400.0.ross_phi1_sphenix_phislice_lookup_r26xp40xz40.distortion_map.hist.root"
bool G4TPC::ENABLE_CENTRAL_MEMBRANE_HITS = false
bool G4TPC::ENABLE_DIRECT_LASER_HITS = false
bool G4TPC::DIRECT_LASER_SAVEHISTOGRAMS = false
std::string G4TPC::DIRECT_LASER_ROOTOUTPUT_FILENAME = "TpcSpaceChargeMatrices.root"
std::string G4TPC::DIRECT_LASER_HISTOGRAMOUTPUT_FILENAME = "TpcDirectLaserReconstruction.root"
Macro Definition Documentation
#define MACRO_G4TPC_C
Definition at line 2 of file G4_TPC.C.
View newest version in sPHENIX GitHub at line 2 of file G4_TPC.C
Function Documentation
double TPC (PHG4Reco * g4Reco, double radius)
Definition at line 135 of file G4_TPC.C.
View newest version in sPHENIX GitHub at line 135 of file G4_TPC.C
References Enable::ABSORBER, no_overlapp, Enable::OVERLAPCHECK, PHG4DetectorSubsystem::OverlapCheck(), G4BECAL::radius, PHG4Reco::registerSubsystem(), PHG4DetectorSubsystem::set_double_param(), PHG4DetectorSubsystem::SetAbsorberActive(), PHG4DetectorSubsystem::SetActive(), PHG4DetectorSubsystem::SuperDetector(), tpc(), Enable::TPC_ABSORBER, Enable::TPC_ENDCAP, TPC_Endcaps(), G4TPC::tpc_outer_radius, and Enable::TPC_OVERLAPCHECK.
void TPC_Cells ()
Definition at line 166 of file G4_TPC.C.
View newest version in sPHENIX GitHub at line 166 of file G4_TPC.C
References deg_to_rad, PHG4TpcElectronDrift::Detector(), G4TPC::ENABLE_CENTRAL_MEMBRANE_HITS, G4TPC::ENABLE_DIRECT_LASER_HITS, G4TPC::ENABLE_STATIC_DISTORTIONS, G4TPC::ENABLE_TIME_ORDERED_DISTORTIONS, Fun4AllServer::instance(), M_PI, max, G4INTT::n_intt_layer, G4MVTX::n_maps_layer, G4TPC::n_tpc_layer_inner, PHG4TpcDistortion::set_do_static_distortions(), PHG4TpcDigitizer::SetADCThreshold(), PHG4TpcCentralMembrane::setCentralMembraneDelay(), PHG4TpcDigitizer::SetENC(), PHG4TpcDigitizer::SetTpcMinLayer(), G4TPC::static_distortion_filename, G4TPC::time_ordered_distortion_filename, G4TPC::tpc_layer_rphi_count_inner, Enable::TPC_VERBOSITY, Enable::VERBOSITY, and Fun4AllBase::Verbosity().
Referenced by Fun4All_AnaTutorial_sPHENIX(), Fun4All_AnaTutorial_sPHENIX_Jets(), Fun4All_G4_fsPHENIX(), and Fun4All_G4_sPHENIX().
void TPC_Clustering ()
Definition at line 246 of file G4_TPC.C.
View newest version in sPHENIX GitHub at line 246 of file G4_TPC.C
References G4TPC::correction_filename, G4TPC::DIRECT_LASER_HISTOGRAMOUTPUT_FILENAME, G4TPC::DIRECT_LASER_ROOTOUTPUT_FILENAME, G4TPC::DIRECT_LASER_SAVEHISTOGRAMS, G4TPC::drift_velocity_scale, G4TPC::ENABLE_CORRECTIONS, G4TPC::ENABLE_DIRECT_LASER_HITS, Fun4AllServer::instance(), max, Fun4AllServer::registerSubsystem(), TpcLoadDistortionCorrection::set_distortion_filename(), TpcClusterizer::set_drift_velocity_scale(), TpcDirectLaserReconstruction::set_outputfile(), Enable::TPC_VERBOSITY, Enable::VERBOSITY, and Fun4AllBase::Verbosity().
Referenced by Fun4All_AnaTutorial_sPHENIX(), Fun4All_AnaTutorial_sPHENIX_Jets(), Fun4All_G4_fsPHENIX(), and Fun4All_G4_sPHENIX().
void TPC_Endcaps (PHG4Reco * g4Reco)
TPC end cap, wagon wheel, electronics.
Definition at line 117 of file G4_TPC.C.
View newest version in sPHENIX GitHub at line 117 of file G4_TPC.C
References Enable::ABSORBER, Enable::OVERLAPCHECK, PHG4DetectorSubsystem::OverlapCheck(), PHG4Reco::registerSubsystem(), PHG4DetectorSubsystem::SetActive(), PHG4DetectorSubsystem::SuperDetector(), Enable::TPC_ABSORBER, and Enable::TPC_OVERLAPCHECK.
void TPC_QA ()
Definition at line 292 of file G4_TPC.C.
View newest version in sPHENIX GitHub at line 292 of file G4_TPC.C
References Fun4AllServer::instance(), max, Enable::QA_VERBOSITY, Fun4AllServer::registerSubsystem(), Enable::TPC_VERBOSITY, and Fun4AllBase::Verbosity().
Referenced by Fun4All_AnaTutorial_sPHENIX(), Fun4All_AnaTutorial_sPHENIX_Jets(), and Fun4All_G4_sPHENIX().
void TPCInit ()
Definition at line 88 of file G4_TPC.C.
View newest version in sPHENIX GitHub at line 88 of file G4_TPC.C
References Enable::INTT, max, BlackHoleGeometry::max_radius, BlackHoleGeometry::max_z, min, BlackHoleGeometry::min_z, Enable::MVTX, G4INTT::n_intt_layer, G4MVTX::n_maps_layer, Enable::TPC_ENDCAP, and G4TPC::tpc_outer_radius.