EIC Software: EicRoot/blob/master/eic/cad/tetgen/tetgen.cxx File Reference
tetgen.cxx File Reference
#include "tetgen.h"
Macros
#define SETVECTOR3(V, a0, a1, a2) (V)[0] = (a0); (V)[1] = (a1); (V)[2] = (a2)
#define SWAP2(a0, a1, tmp) (tmp) = (a0); (a0) = (a1); (a1) = (tmp)
Functions
void swapBytes (unsigned char *var, int size)
bool testIsBigEndian ()
void tetrahedralize (tetgenbehavior *b, tetgenio *in, tetgenio *out, tetgenio *addin, tetgenio *bgmin)
int main (int argc, char *argv[])
Macro Definition Documentation
#define SETVECTOR3 (V, a0, a1, a2) (V)[0] = (a0); (V)[1] = (a1); (V)[2] = (a2)
Definition at line 4988 of file tetgen.cxx.
View newest version in sPHENIX GitHub at line 4988 of file tetgen.cxx
Referenced by tetgenmesh::tri_edge_2d(), and tetgenmesh::tri_edge_tail().
#define SWAP2 (a0, a1, tmp) (tmp) = (a0); (a0) = (a1); (a1) = (tmp)
Definition at line 4990 of file tetgen.cxx.
View newest version in sPHENIX GitHub at line 4990 of file tetgen.cxx
Function Documentation
int main (int argc, char * argv[])
Definition at line 31204 of file tetgen.cxx.
View newest version in sPHENIX GitHub at line 31204 of file tetgen.cxx
References tetgenmesh::addin, tetgenbehavior::addinfilename, tetgenmesh::b, tetgenbehavior::bgmeshfilename, tetgenmesh::in, tetgenbehavior::infilename, tetgenbehavior::insertaddpoints, tetgenio::load_node(), tetgenio::load_plc(), tetgenio::load_tetmesh(), tetgenbehavior::metric, tetgenbehavior::object, tetgenbehavior::parse_commandline(), tetgenbehavior::refine, terminatetetgen(), and tetrahedralize().
void swapBytes (unsigned char * var, int size)
Definition at line 2102 of file tetgen.cxx.
View newest version in sPHENIX GitHub at line 2102 of file tetgen.cxx
References c.
Referenced by tetgenio::load_vtk().
bool testIsBigEndian ()
Definition at line 2114 of file tetgen.cxx.
View newest version in sPHENIX GitHub at line 2114 of file tetgen.cxx
Referenced by tetgenio::load_vtk().
void tetrahedralize (tetgenbehavior * b, tetgenio * in, tetgenio * out, tetgenio * addin, tetgenio * bgmin)
Definition at line 30860 of file tetgen.cxx.
View newest version in sPHENIX GitHub at line 30860 of file tetgen.cxx
References tetgenmesh::addin, tetgenmesh::b, tetgenmesh::bgm, tetgenmesh::carveholes(), tetgenmesh::checkdelaunay(), tetgenmesh::checkmesh(), tetgenmesh::checksegments(), tetgenmesh::checkshells(), tetgenbehavior::coarsen, tetgenmesh::constraineddelaunay(), tetgenbehavior::convex, tetgenmesh::delaunayrefinement(), tetgenmesh::detectinterfaces(), tetgenbehavior::diagnose, tetgenbehavior::docheck, tetgenmesh::dupverts, tetgenbehavior::edgesout, exactinit(), tetgenbehavior::facesout, tetgenio::firstnumber, tetgenmesh::highorder(), tetgenmesh::in, tetgenmesh::incrementaldelaunay(), tetgenmesh::initializepools(), tetgenbehavior::insertaddpoints, tetgenmesh::insertconstrainedpoints(), tetgenmesh::interpolatemeshsize(), tetgenmesh::memorypool::items, tetgenmesh::jettisonnodes(), Acts::UnitConstants::m, tetgenbehavior::meditview, tetgenio::mesh_dim, tetgenmesh::meshcoarsening(), tetgenmesh::meshsurface(), tetgenbehavior::metric, tetgenbehavior::neighout, tetgenbehavior::nobisect, tetgenbehavior::noelewritten, tetgenbehavior::noexact, tetgenbehavior::nofacewritten, tetgenbehavior::noiterationnum, tetgenbehavior::nojettison, tetgenbehavior::nonodewritten, tetgenbehavior::nostaticfilter, tetgenio::numberofcorners, tetgenio::numberofpoints, tetgenbehavior::object, tetgenmesh::arraypool::objects, tetgenbehavior::OFF, tetgenmesh::optimizemesh(), tetgenbehavior::optlevel, tetgenbehavior::order, tetgenmesh::outedges(), tetgenmesh::outelements(), tetgenmesh::outfaces(), tetgenbehavior::outfilename, tetgenmesh::outhullfaces(), tetgenmesh::outmesh2medit(), tetgenmesh::outmesh2vtk(), tetgenmesh::outmetrics(), tetgenmesh::outneighbors(), tetgenmesh::outnodes(), tetgenmesh::outsmesh(), tetgenmesh::outsubfaces(), tetgenmesh::outsubsegments(), tetgenmesh::outvoronoi(), tetgenbehavior::plc, tetgenbehavior::PLY, printf(), tetgenbehavior::quality, tetgenbehavior::quiet, REAL, tetgenmesh::reconstructmesh(), tetgenmesh::recoverboundary(), tetgenmesh::recoverdelaunay(), tetgenbehavior::refine, tetgenmesh::statistics(), tetgenbehavior::STL, tetgenmesh::subfaces, tetgenmesh::subvertstack, tetgenmesh::suppresssteinerpoints(), tetgenmesh::tetgenmesh(), tetgenmesh::tetrahedrons, tetgenmesh::transfernodes(), tetgenmesh::unuverts, tetgenbehavior::verbose, tetgenbehavior::voroout, tetgenbehavior::vtkview, tetgenmesh::xmax, tetgenmesh::xmin, tetgenmesh::ymax, tetgenmesh::ymin, tetgenmesh::zmax, and tetgenmesh::zmin.
Referenced by EicStlFactory::_ConstructGeometry(), EicStlFactory::CreateRootFile(), and main().