EIC Software: TrkrClusterv3 Class Reference
TrkrClusterv3 Class Reference
Version 3 of TrkrCluster.
#include <fun4all_coresoftware/blob/master/offline/packages/trackbase/TrkrClusterv3.h>
Public Member Functions
TrkrClusterv3 ()
ctor
~TrkrClusterv3 () override
dtor
void identify (std::ostream &os=std::cout) const override
void Reset () override
Clear Event.
int isValid () const override
isValid returns non zero if object contains vailid data
PHObject * CloneMe () const override
Virtual copy constructor.
void CopyFrom (const TrkrCluster &) override
copy content from base class
void CopyFrom (TrkrCluster *source) override
copy content from base class
void setClusKey (TrkrDefs::cluskey id) override
TrkrDefs::cluskey getClusKey () const override
float getPosition (int coor) const override
void setPosition (int coor, float xi) override
float getLocalX () const override
void setLocalX (float loc0) override
float getLocalY () const override
void setLocalY (float loc1) override
void setActsLocalError (unsigned int i, unsigned int j, float value) override
Acts functions, for Acts module use only.
float getActsLocalError (unsigned int i, unsigned int j) const override
TrkrDefs::subsurfkey getSubSurfKey () const override
void setSubSurfKey (TrkrDefs::subsurfkey id) override
unsigned int getAdc () const override
void setAdc (unsigned int adc) override
float getRPhiError () const override
float getZError () const override
float getX () const override
deprecated global funtions with a warning
float getY () const override
float getZ () const override
void setX (float) override
void setY (float) override
void setZ (float) override
float getSize (unsigned int, unsigned int) const override
void setSize (unsigned int, unsigned int, float) override
float getError (unsigned int, unsigned int) const override
void setError (unsigned int, unsigned int, float) override
float getPhiSize () const override
float getZSize () const override
float getPhiError () const override
Public Member Functions inherited from TrkrCluster
~TrkrCluster () override
dtor
virtual void setGlobal ()
virtual void setLocal ()
virtual bool isGlobal () const
Public Member Functions inherited from PHObject
PHObject ()
ctor
~PHObject () override
dtor
virtual PHObject * clone () const final
PHObject * Clone (const char *newname="") const final
void Copy (TObject &object) const final
virtual int isValid (const float) const
virtual int isValid (const double) const
virtual int isValid (const int) const
virtual int isValid (const unsigned int) const
virtual int isImplemented (const float f) const
virtual int isImplemented (const double f) const
virtual int isImplemented (const int i) const
virtual int isImplemented (const unsigned int i) const
virtual int Integrate () const
virtual int Integrate (PHObject *)
virtual void CopyFrom (const PHObject *obj)
Protected Attributes
TrkrDefs::cluskey m_cluskey
TrkrDefs::subsurfkey m_subsurfkey
unsigned int m_adc
float m_local [2]
float m_actsLocalErr [2][2]
Additional Inherited Members
Protected Member Functions inherited from TrkrCluster
TrkrCluster ()=default
Detailed Description
Version 3 of TrkrCluster.
This version of TrkrCluster contains Acts source link objects as member variables, to join the Svtx and Acts worlds
Definition at line 22 of file TrkrClusterv3.h.
View newest version in sPHENIX GitHub at line 22 of file TrkrClusterv3.h
Constructor & Destructor Documentation
TrkrClusterv3::TrkrClusterv3 ()
ctor
Definition at line 19 of file TrkrClusterv3.cc.
View newest version in sPHENIX GitHub at line 19 of file TrkrClusterv3.cc
References m_actsLocalErr, and m_local.
Referenced by CloneMe().
TrkrClusterv3::~TrkrClusterv3 () inline override
dtor
Definition at line 30 of file TrkrClusterv3.h.
View newest version in sPHENIX GitHub at line 30 of file TrkrClusterv3.h
Member Function Documentation
PHObject* TrkrClusterv3::CloneMe () const inline override virtual
Virtual copy constructor.
Reimplemented from PHObject.
Definition at line 35 of file TrkrClusterv3.h.
View newest version in sPHENIX GitHub at line 35 of file TrkrClusterv3.h
References TrkrClusterv3().
void TrkrClusterv3::CopyFrom (const TrkrCluster & source) override virtual
copy content from base class
Reimplemented from TrkrCluster.
Definition at line 72 of file TrkrClusterv3.cc.
View newest version in sPHENIX GitHub at line 72 of file TrkrClusterv3.cc
References TrkrCluster::CopyFrom(), TrkrCluster::getActsLocalError(), TrkrCluster::getAdc(), TrkrCluster::getClusKey(), TrkrCluster::getLocalX(), TrkrCluster::getLocalY(), TrkrCluster::getSubSurfKey(), setActsLocalError(), setAdc(), setClusKey(), setLocalX(), setLocalY(), and setSubSurfKey().
void TrkrClusterv3::CopyFrom (TrkrCluster * source) inline override virtual
copy content from base class
Reimplemented from TrkrCluster.
Definition at line 41 of file TrkrClusterv3.h.
View newest version in sPHENIX GitHub at line 41 of file TrkrClusterv3.h
References CopyFrom().
Referenced by CopyFrom().
float TrkrClusterv3::getActsLocalError (unsigned int i, unsigned int j) const inline override virtual
Reimplemented from TrkrCluster.
Definition at line 60 of file TrkrClusterv3.h.
View newest version in sPHENIX GitHub at line 60 of file TrkrClusterv3.h
References m_actsLocalErr.
Referenced by identify(), and isValid().
unsigned int TrkrClusterv3::getAdc () const inline override virtual
Reimplemented from TrkrCluster.
Definition at line 67 of file TrkrClusterv3.h.
View newest version in sPHENIX GitHub at line 67 of file TrkrClusterv3.h
References m_adc.
Referenced by identify().
TrkrDefs::cluskey TrkrClusterv3::getClusKey () const inline override virtual
Reimplemented from TrkrCluster.
Definition at line 45 of file TrkrClusterv3.h.
View newest version in sPHENIX GitHub at line 45 of file TrkrClusterv3.h
References m_cluskey.
Referenced by identify().
float TrkrClusterv3::getError (unsigned int , unsigned int) const inline override virtual
Reimplemented from TrkrCluster.
Definition at line 93 of file TrkrClusterv3.h.
View newest version in sPHENIX GitHub at line 93 of file TrkrClusterv3.h
float TrkrClusterv3::getLocalX () const inline override virtual
Reimplemented from TrkrCluster.
Definition at line 53 of file TrkrClusterv3.h.
View newest version in sPHENIX GitHub at line 53 of file TrkrClusterv3.h
References m_local.
Referenced by identify().
float TrkrClusterv3::getLocalY () const inline override virtual
Reimplemented from TrkrCluster.
Definition at line 55 of file TrkrClusterv3.h.
View newest version in sPHENIX GitHub at line 55 of file TrkrClusterv3.h
References m_local.
Referenced by identify().
float TrkrClusterv3::getPhiError () const inline override virtual
Reimplemented from TrkrCluster.
Definition at line 101 of file TrkrClusterv3.h.
View newest version in sPHENIX GitHub at line 101 of file TrkrClusterv3.h
float TrkrClusterv3::getPhiSize () const inline override virtual
Reimplemented from TrkrCluster.
Definition at line 97 of file TrkrClusterv3.h.
View newest version in sPHENIX GitHub at line 97 of file TrkrClusterv3.h
float TrkrClusterv3::getPosition (int coor) const inline override virtual
Reimplemented from TrkrCluster.
Definition at line 51 of file TrkrClusterv3.h.
View newest version in sPHENIX GitHub at line 51 of file TrkrClusterv3.h
References m_local.
Referenced by isValid().
float TrkrClusterv3::getRPhiError () const override virtual
Reimplemented from TrkrCluster.
Definition at line 92 of file TrkrClusterv3.cc.
View newest version in sPHENIX GitHub at line 92 of file TrkrClusterv3.cc
References m_actsLocalErr.
float TrkrClusterv3::getSize (unsigned int , unsigned int) const inline override virtual
Reimplemented from TrkrCluster.
Definition at line 89 of file TrkrClusterv3.h.
View newest version in sPHENIX GitHub at line 89 of file TrkrClusterv3.h
TrkrDefs::subsurfkey TrkrClusterv3::getSubSurfKey () const inline override virtual
Reimplemented from TrkrCluster.
Definition at line 61 of file TrkrClusterv3.h.
View newest version in sPHENIX GitHub at line 61 of file TrkrClusterv3.h
References m_subsurfkey.
float TrkrClusterv3::getX () const inline override virtual
deprecated global funtions with a warning
Reimplemented from TrkrCluster.
Definition at line 77 of file TrkrClusterv3.h.
View newest version in sPHENIX GitHub at line 77 of file TrkrClusterv3.h
float TrkrClusterv3::getY () const inline override virtual
Reimplemented from TrkrCluster.
Definition at line 79 of file TrkrClusterv3.h.
View newest version in sPHENIX GitHub at line 79 of file TrkrClusterv3.h
float TrkrClusterv3::getZ () const inline override virtual
Reimplemented from TrkrCluster.
Definition at line 81 of file TrkrClusterv3.h.
View newest version in sPHENIX GitHub at line 81 of file TrkrClusterv3.h
float TrkrClusterv3::getZError () const override virtual
Reimplemented from TrkrCluster.
Definition at line 95 of file TrkrClusterv3.cc.
View newest version in sPHENIX GitHub at line 95 of file TrkrClusterv3.cc
References m_actsLocalErr.
float TrkrClusterv3::getZSize () const inline override virtual
Reimplemented from TrkrCluster.
Definition at line 99 of file TrkrClusterv3.h.
View newest version in sPHENIX GitHub at line 99 of file TrkrClusterv3.h
void TrkrClusterv3::identify (std::ostream & os = std::cout) const override virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from TrkrCluster.
Definition at line 34 of file TrkrClusterv3.cc.
View newest version in sPHENIX GitHub at line 34 of file TrkrClusterv3.cc
References getActsLocalError(), getAdc(), getClusKey(), getLocalX(), and getLocalY().
int TrkrClusterv3::isValid () const override virtual
isValid returns non zero if object contains vailid data
Reimplemented from TrkrCluster.
Definition at line 58 of file TrkrClusterv3.cc.
View newest version in sPHENIX GitHub at line 58 of file TrkrClusterv3.cc
References getActsLocalError(), getPosition(), m_adc, and m_cluskey.
void TrkrClusterv3::Reset () inline override virtual
Clear Event.
Reimplemented from TrkrCluster.
Definition at line 33 of file TrkrClusterv3.h.
View newest version in sPHENIX GitHub at line 33 of file TrkrClusterv3.h
void TrkrClusterv3::setActsLocalError (unsigned int i, unsigned int j, float value) override virtual
Acts functions, for Acts module use only.
Reimplemented from TrkrCluster.
Definition at line 98 of file TrkrClusterv3.cc.
View newest version in sPHENIX GitHub at line 98 of file TrkrClusterv3.cc
References m_actsLocalErr, and value.
Referenced by CopyFrom().
void TrkrClusterv3::setAdc (unsigned int adc) inline override virtual
Reimplemented from TrkrCluster.
Definition at line 68 of file TrkrClusterv3.h.
View newest version in sPHENIX GitHub at line 68 of file TrkrClusterv3.h
References m_adc.
Referenced by CopyFrom().
void TrkrClusterv3::setClusKey (TrkrDefs::cluskey id) inline override virtual
Reimplemented from TrkrCluster.
Definition at line 44 of file TrkrClusterv3.h.
View newest version in sPHENIX GitHub at line 44 of file TrkrClusterv3.h
References m_cluskey.
Referenced by CopyFrom().
void TrkrClusterv3::setError (unsigned int , unsigned int , float) inline override virtual
Reimplemented from TrkrCluster.
Definition at line 95 of file TrkrClusterv3.h.
View newest version in sPHENIX GitHub at line 95 of file TrkrClusterv3.h
void TrkrClusterv3::setLocalX (float loc0) inline override virtual
Reimplemented from TrkrCluster.
Definition at line 54 of file TrkrClusterv3.h.
View newest version in sPHENIX GitHub at line 54 of file TrkrClusterv3.h
References m_local.
Referenced by CopyFrom().
void TrkrClusterv3::setLocalY (float loc1) inline override virtual
Reimplemented from TrkrCluster.
Definition at line 56 of file TrkrClusterv3.h.
View newest version in sPHENIX GitHub at line 56 of file TrkrClusterv3.h
References m_local.
Referenced by CopyFrom().
void TrkrClusterv3::setPosition (int coor, float xi) inline override virtual
Reimplemented from TrkrCluster.
Definition at line 52 of file TrkrClusterv3.h.
View newest version in sPHENIX GitHub at line 52 of file TrkrClusterv3.h
References m_local.
void TrkrClusterv3::setSize (unsigned int , unsigned int , float) inline override virtual
Reimplemented from TrkrCluster.
Definition at line 91 of file TrkrClusterv3.h.
View newest version in sPHENIX GitHub at line 91 of file TrkrClusterv3.h
void TrkrClusterv3::setSubSurfKey (TrkrDefs::subsurfkey id) inline override virtual
Reimplemented from TrkrCluster.
Definition at line 62 of file TrkrClusterv3.h.
View newest version in sPHENIX GitHub at line 62 of file TrkrClusterv3.h
References m_subsurfkey.
Referenced by CopyFrom().
void TrkrClusterv3::setX (float) inline override virtual
Reimplemented from TrkrCluster.
Definition at line 83 of file TrkrClusterv3.h.
View newest version in sPHENIX GitHub at line 83 of file TrkrClusterv3.h
void TrkrClusterv3::setY (float) inline override virtual
Reimplemented from TrkrCluster.
Definition at line 85 of file TrkrClusterv3.h.
View newest version in sPHENIX GitHub at line 85 of file TrkrClusterv3.h
void TrkrClusterv3::setZ (float) inline override virtual
Reimplemented from TrkrCluster.
Definition at line 87 of file TrkrClusterv3.h.
View newest version in sPHENIX GitHub at line 87 of file TrkrClusterv3.h
Member Data Documentation
float TrkrClusterv3::m_actsLocalErr[2][2] protected
Definition at line 112 of file TrkrClusterv3.h.
View newest version in sPHENIX GitHub at line 112 of file TrkrClusterv3.h
Referenced by getActsLocalError(), getRPhiError(), getZError(), setActsLocalError(), and TrkrClusterv3().
unsigned int TrkrClusterv3::m_adc protected
Definition at line 109 of file TrkrClusterv3.h.
View newest version in sPHENIX GitHub at line 109 of file TrkrClusterv3.h
Referenced by getAdc(), isValid(), and setAdc().
TrkrDefs::cluskey TrkrClusterv3::m_cluskey protected
Definition at line 106 of file TrkrClusterv3.h.
View newest version in sPHENIX GitHub at line 106 of file TrkrClusterv3.h
Referenced by getClusKey(), isValid(), and setClusKey().
float TrkrClusterv3::m_local[2] protected
Definition at line 111 of file TrkrClusterv3.h.
View newest version in sPHENIX GitHub at line 111 of file TrkrClusterv3.h
Referenced by getLocalX(), getLocalY(), getPosition(), setLocalX(), setLocalY(), setPosition(), and TrkrClusterv3().
TrkrDefs::subsurfkey TrkrClusterv3::m_subsurfkey protected
Definition at line 107 of file TrkrClusterv3.h.
View newest version in sPHENIX GitHub at line 107 of file TrkrClusterv3.h
Referenced by getSubSurfKey(), and setSubSurfKey().
The documentation for this class was generated from the following files:
fun4all_coresoftware/blob/master/offline/packages/trackbase/TrkrClusterv3.h
fun4all_coresoftware/blob/master/offline/packages/trackbase/TrkrClusterv3.cc