EIC Software: Smear::Event Class Reference
Smear::Event Class Reference
#include <eic-smear/blob/master/include/eicsmear/smear/EventSmear.h>
Public Member Functions
Event ()
virtual ~Event ()
virtual void Reset ()
virtual void ClearParticles ()
virtual UInt_t GetNTracks () const
virtual const ParticleMCS * GetTrack (UInt_t) const
virtual ParticleMCS * GetTrack (UInt_t)
virtual void SetQ2 (double Q2)
virtual void SetX (double xB)
virtual void SetY (double inelasticity)
virtual void SetW2 (double W2)
virtual void SetNu (double Nu)
virtual const ParticleMCS * BeamLepton () const
virtual const ParticleMCS * BeamHadron () const
virtual const ParticleMCS * ExchangeBoson () const
virtual const ParticleMCS * ScatteredLepton () const
virtual void AddLast (ParticleMCS *particle)
void HadronicFinalState (ParticlePtrList &) const
std::vector< const
erhic::VirtualParticle * > GetTracks () const
virtual void SetScattered (int index)
virtual void Print (Option_t *="") const
Public Member Functions inherited from erhic::EventDis
virtual ~EventDis ()
EventDis ()
EventDis (const EventDis &)
EventDis & operator= (const EventDis &)
virtual Double_t GetX () const
virtual Double_t GetQ2 () const
virtual Double_t GetY () const
virtual Double_t GetYPlus () const
virtual Double_t GetW2 () const
virtual Double_t GetNu () const
virtual double GetXDoubleAngle () const
virtual double GetQ2DoubleAngle () const
virtual double GetYDoubleAngle () const
virtual double GetW2DoubleAngle () const
virtual double GetXJacquetBlondel () const
virtual double GetQ2JacquetBlondel () const
virtual double GetYJacquetBlondel () const
virtual double GetW2JacquetBlondel () const
virtual void SetLeptonKinematics (const DisKinematics &)
virtual void SetJacquetBlondelKinematics (const DisKinematics &)
virtual void SetDoubleAngleKinematics (const DisKinematics &)
virtual void CopyKinematics (const EventDis &)
Public Member Functions inherited from erhic::VirtualEvent
virtual ~VirtualEvent ()
Protected Attributes
Int_t nTracks
Number of particles (intermediate + final)
std::vector< ParticleMCS * > particles
The smeared particle list.
Int_t mScatteredIndex
Additional Inherited Members
Public Types inherited from erhic::VirtualEvent
typedef std::vector< const
erhic::VirtualParticle * > ParticlePtrList
Public Attributes inherited from erhic::EventDis
Double32_t x
Bjorken scaling variable.
Double32_t QSquared
Q2 calculated from scattered electron.
Double32_t y
Inelasticity.
Double32_t WSquared
Invariant mass of the hadronic system.
Double32_t nu
Energy transfer from the electron.
Double32_t yJB
y calculated via the Jacquet-Blondel method
Double32_t QSquaredJB
Q2 calculated via the Jacquet-Blondel method.
Double32_t xJB
x calculated via the Jacquet-Blondel method
Double32_t WSquaredJB
W2 calculated via the Jacquet-Blondel method.
Double32_t yDA
y calculated via the double-angle method
Double32_t QSquaredDA
Q2 calculated via the double-angle method.
Double32_t xDA
x calculated via the double-angle method
Double32_t WSquaredDA
W2 calculated via the double-angle method.
Detailed Description
Definition at line 29 of file EventSmear.h.
View newest version in sPHENIX GitHub at line 29 of file EventSmear.h
Constructor & Destructor Documentation
Event::Event ()
Default constructor.
Definition at line 17 of file EventSmear.cxx.
View newest version in sPHENIX GitHub at line 17 of file EventSmear.cxx
Referenced by Reset().
Event::~Event () virtual
Destructor.
Definition at line 22 of file EventSmear.cxx.
View newest version in sPHENIX GitHub at line 22 of file EventSmear.cxx
References ClearParticles().
Member Function Documentation
void Event::AddLast (ParticleMCS * particle) virtual
Add a new track to the end of the track list. The track must be allocated via new and is subsequently owned by the Event.
Definition at line 39 of file EventSmear.cxx.
View newest version in sPHENIX GitHub at line 39 of file EventSmear.cxx
References particles.
const ParticleMCS * Event::BeamHadron () const inline virtual
Returns a pointer to the incident hadron beam particle. See also notes in BeamLepton().
In the standard eRHIC Monte Carlo format, the incident hadron beam is assumed to be the second particle in the particle list.
Implements erhic::EventDis.
Definition at line 177 of file EventSmear.h.
View newest version in sPHENIX GitHub at line 177 of file EventSmear.h
References particles.
const ParticleMCS * Event::BeamLepton () const inline virtual
Returns a pointer to the incident lepton beam particle. Returns a NULL pointer if the particle cannot be located in the event. IMPORTANT - DO NOT DELETE THE POINTER OR BAD THINGS WILL HAPPEN!
In the standard eRHIC Monte Carlo format, the incident lepton beam is assumed to be the first particle in the particle list. This is the behaviour implemented here. Derived classes can implement other selection mechanisms depending on their data format.
Implements erhic::EventDis.
Definition at line 173 of file EventSmear.h.
View newest version in sPHENIX GitHub at line 173 of file EventSmear.h
References particles.
void Event::ClearParticles () virtual
Clears particle array, leaves event variables unchanged.
Definition at line 26 of file EventSmear.cxx.
View newest version in sPHENIX GitHub at line 26 of file EventSmear.cxx
References GetTrack(), and particles.
Referenced by Reset(), and ~Event().
const ParticleMCS * Event::ExchangeBoson () const inline virtual
Returns a pointer to the exchanged boson. See also notes in BeamLepton().
In the standard eRHIC Monte Carlo format, the exchanged boson is assumed to be the third particle in the particle list.
Implements erhic::EventDis.
Definition at line 181 of file EventSmear.h.
View newest version in sPHENIX GitHub at line 181 of file EventSmear.h
UInt_t Event::GetNTracks () const inline virtual
Returns the number of tracks in the event.
Implements erhic::VirtualEvent.
Definition at line 161 of file EventSmear.h.
View newest version in sPHENIX GitHub at line 161 of file EventSmear.h
References particles.
Referenced by GetTracks(), HadronicFinalState(), main(), Print(), and ScatteredLepton().
const Smear::ParticleMCS * Event::GetTrack (UInt_t u) const inline virtual
Returns the nth track. Returns NULL if the track number is out of the range [0, GetNTracks()).
Parameters
[in] The track index, in the range [0, GetNTracks()).
Implements erhic::VirtualEvent.
Definition at line 165 of file EventSmear.h.
View newest version in sPHENIX GitHub at line 165 of file EventSmear.h
References particles.
Referenced by ClearParticles(), GetTracks(), HadronicFinalState(), main(), Print(), and ScatteredLepton().
Smear::ParticleMCS * Event::GetTrack (UInt_t u) inline virtual
Returns the nth track. Returns NULL if the track number is out of the range [0, GetNTracks()).
Parameters
[in] The track index, in the range [0, GetNTracks()).
Implements erhic::VirtualEvent.
Definition at line 169 of file EventSmear.h.
View newest version in sPHENIX GitHub at line 169 of file EventSmear.h
References particles.
std::vector< const erhic::VirtualParticle * > Event::GetTracks () const
Returns a vector of pointers to all tracks in the event. Note that this includes NULL pointers to tracks that were not detected. Do not delete the pointers.
Definition at line 68 of file EventSmear.cxx.
View newest version in sPHENIX GitHub at line 68 of file EventSmear.cxx
References GetNTracks(), and GetTrack().
void Event::HadronicFinalState (ParticlePtrList & final) const virtual
Yields all particles that belong to the hadronic final state. This is the same as the result of FinalState(), minus the scattered beam lepton (i.e. including leptons and bosons).
Reimplemented from erhic::VirtualEvent.
Definition at line 56 of file EventSmear.cxx.
View newest version in sPHENIX GitHub at line 56 of file EventSmear.cxx
References GetNTracks(), GetTrack(), and ScatteredLepton().
void Event::Print (Option_t * = "") const virtual
Prints the attributes of this event to standard output. Prints event-wise kinematic values, and all tracks in the event.
Definition at line 81 of file EventSmear.cxx.
View newest version in sPHENIX GitHub at line 81 of file EventSmear.cxx
References GetNTracks(), erhic::EventDis::GetQ2(), GetTrack(), erhic::EventDis::GetX(), erhic::EventDis::GetY(), and Smear::ParticleMCS::Print().
void Event::Reset () virtual
Clear the particle list, sets event properties to default values.
Definition at line 34 of file EventSmear.cxx.
View newest version in sPHENIX GitHub at line 34 of file EventSmear.cxx
References ClearParticles(), and Event().
const ParticleMCS * Event::ScatteredLepton () const virtual
Returns a pointer to the lepton beam particle after scattering. See also notes in BeamLepton().
In the standard eRHIC Monte Carlo format, the scattered lepton beam is assumed to be the first final-state particle in the particle list with the same PDG code as the incident lepton beam.
Implements erhic::EventDis.
Definition at line 44 of file EventSmear.cxx.
View newest version in sPHENIX GitHub at line 44 of file EventSmear.cxx
References GetNTracks(), GetTrack(), and mScatteredIndex.
Referenced by Smear::Detector::FillEventKinematics(), and HadronicFinalState().
virtual void Smear::Event::SetNu (double Nu) inline virtual
Definition at line 78 of file EventSmear.h.
View newest version in sPHENIX GitHub at line 78 of file EventSmear.h
References erhic::EventDis::nu.
virtual void Smear::Event::SetQ2 (double Q2) inline virtual
Definition at line 70 of file EventSmear.h.
View newest version in sPHENIX GitHub at line 70 of file EventSmear.h
References erhic::EventDis::QSquared.
void Event::SetScattered (int index) virtual
Set which particle is the scattered lepton.
Definition at line 76 of file EventSmear.cxx.
View newest version in sPHENIX GitHub at line 76 of file EventSmear.cxx
References mScatteredIndex.
virtual void Smear::Event::SetW2 (double W2) inline virtual
Definition at line 76 of file EventSmear.h.
View newest version in sPHENIX GitHub at line 76 of file EventSmear.h
References erhic::EventDis::WSquared.
virtual void Smear::Event::SetX (double xB) inline virtual
Definition at line 72 of file EventSmear.h.
View newest version in sPHENIX GitHub at line 72 of file EventSmear.h
References erhic::EventDis::x.
virtual void Smear::Event::SetY (double inelasticity) inline virtual
Definition at line 74 of file EventSmear.h.
View newest version in sPHENIX GitHub at line 74 of file EventSmear.h
References erhic::EventDis::y.
Member Data Documentation
Int_t Smear::Event::mScatteredIndex protected
Definition at line 156 of file EventSmear.h.
View newest version in sPHENIX GitHub at line 156 of file EventSmear.h
Referenced by ScatteredLepton(), and SetScattered().
Int_t Smear::Event::nTracks protected
Number of particles (intermediate + final)
Definition at line 154 of file EventSmear.h.
View newest version in sPHENIX GitHub at line 154 of file EventSmear.h
std::vector<ParticleMCS*> Smear::Event::particles protected
The smeared particle list.
Definition at line 155 of file EventSmear.h.
View newest version in sPHENIX GitHub at line 155 of file EventSmear.h
Referenced by AddLast(), BeamHadron(), BeamLepton(), ClearParticles(), GetNTracks(), and GetTrack().
The documentation for this class was generated from the following files:
eic-smear/blob/master/include/eicsmear/smear/EventSmear.h
eic-smear/blob/master/src/smear/EventSmear.cxx