EIC Software: EicEventAssembler Class Reference
EicEventAssembler Class Reference
#include <EicRoot/blob/master/eic/event/EicEventAssembler.h>
Public Member Functions
EicEventAssembler ()
~EicEventAssembler ()
InitStatus Init ()
void Exec (Option_t *opt)
void FinishTask ()
int AddEmCal (const char *name)
int AddHCal (const char *name)
Public Member Functions inherited from FairTask
FairTask ()
FairTask (const char *name, Int_t iVerbose=1)
virtual ~FairTask ()
void InitTask ()
void ReInitTask ()
void SetParTask ()
virtual void FinishEvent ()
void SetVerbose (Int_t iVerbose)
void SetInputPersistance (Bool_t val)
void CheckInputPersistance (TString branchName)
Private Member Functions
int AddCalorimeterCore (const char *name, CalorimeterType type)
void ComposeCalorimeterInformation ()
void PerformPidCalculations ()
void ReAssignMomentumValue ()
void AssignScatteredLepton ()
ClassDef (EicEventAssembler, 15)
Private Attributes
TClonesArray * mPndMCTracks
TClonesArray * mPndPidChargedCand
erhic::EventMC * mGeneratorEvent
ParticleMappingTable * mMappingTable
Bool_t mPersistency
EicRcEvent * mEicRcEvent
TBranch * mEicRcEventBranch
reconstructed event as a whole
std::vector< EicCalorimeterHub * > mCalorimeters
Additional Inherited Members
Protected Member Functions inherited from FairTask
virtual InitStatus ReInit ()
virtual void SetParContainers ()
virtual void Finish ()
void InitTasks ()
void ReInitTasks ()
void SetParTasks ()
void FinishTasks ()
void FinishEvents ()
Protected Attributes inherited from FairTask
Int_t fVerbose
Int_t fInputPersistance
Indicates if input branch is persistant.
FairLogger * fLogger
Detailed Description
Definition at line 56 of file EicEventAssembler.h.
View newest version in sPHENIX GitHub at line 56 of file EicEventAssembler.h
Constructor & Destructor Documentation
EicEventAssembler::EicEventAssembler ()
Definition at line 20 of file EicEventAssembler.cxx.
View newest version in sPHENIX GitHub at line 20 of file EicEventAssembler.cxx
EicEventAssembler::~EicEventAssembler () inline
Definition at line 59 of file EicEventAssembler.h.
View newest version in sPHENIX GitHub at line 59 of file EicEventAssembler.h
Member Function Documentation
int EicEventAssembler::AddCalorimeterCore (const char * name, CalorimeterType type) private
Definition at line 35 of file EicEventAssembler.cxx.
View newest version in sPHENIX GitHub at line 35 of file EicEventAssembler.cxx
References mCalorimeters.
Referenced by AddEmCal(), and AddHCal().
int EicEventAssembler::AddEmCal (const char * name)
Definition at line 45 of file EicEventAssembler.cxx.
View newest version in sPHENIX GitHub at line 45 of file EicEventAssembler.cxx
References AddCalorimeterCore(), and qEmCal.
Referenced by reconstruction().
int EicEventAssembler::AddHCal (const char * name)
Definition at line 52 of file EicEventAssembler.cxx.
View newest version in sPHENIX GitHub at line 52 of file EicEventAssembler.cxx
References AddCalorimeterCore(), and qHCal.
Referenced by reconstruction().
void EicEventAssembler::AssignScatteredLepton () private
Definition at line 280 of file EicEventAssembler.cxx.
View newest version in sPHENIX GitHub at line 280 of file EicEventAssembler.cxx
References EicRcEvent::BeamLepton(), EicRcParticle::GetE(), EicRcParticle::GetMcPdgCode(), erhic::ParticleMCbase::GetPdgCode(), erhic::Pid::Info(), mEicRcEvent, EicRcEvent::mParticles, EicRcParticle::mRcPdgCode, EicRcEvent::mScatteredLeptonID, particle, and printf().
Referenced by Exec().
EicEventAssembler::ClassDef (EicEventAssembler , 15) private
void EicEventAssembler::ComposeCalorimeterInformation () private
Definition at line 110 of file EicEventAssembler.cxx.
View newest version in sPHENIX GitHub at line 110 of file EicEventAssembler.cxx
References EicCalorimeterHub::EnergyErrorEstimate(), it, mCalorimeters, EicRcParticle::mCellGroups, EicCalorimeterHub::mClusters, mEicRcEvent, EicRcParticle::mEmCal, EicRcCalorimeterHit::mEnergy, CalorimeterCellGroup::mEnergyPerParent, EicRcCalorimeterHit::mEnergySigma, EicRcParticle::mHCal, EicRcEvent::mParticles, EicRcParticle::mPndMCTrackIndex, EicCalorimeterHub::mType, particle, qEmCal, and value.
Referenced by Exec().
void EicEventAssembler::Exec (Option_t * opt)
Definition at line 312 of file EicEventAssembler.cxx.
View newest version in sPHENIX GitHub at line 312 of file EicEventAssembler.cxx
References _EIC_RC_BRANCH_, _EIC_RC_TREE_, AssignScatteredLepton(), ComposeCalorimeterInformation(), PndPidCandidate::GetCov(), ParticleMappingTable::GetData(), EicRcParticle::GetE(), PndPidCandidate::GetMcIndex(), EicRcParticle::GetMcPdgCode(), PndPidCandidate::GetMomentum(), FairRootManager::GetObject(), PndPidCandidate::GetPosition(), FairRootManager::Instance(), it, mCalorimeters, EicRcParticle::mCellGroups, EicCalorimeterHub::mClusters, mEicRcEvent, mEicRcEventBranch, CalorimeterCellGroup::mEnergyPerParent, EicRcParticle::mGeneratorEventIndex, mMappingTable, EicCalorimeterHub::mName, EicRcEvent::mParticles, EicRcParticle::mPndMCTrackIndex, mPndPidChargedCand, EicRcParticle::mPndPidChargedCandIndex, EicRcParticle::mRcTrackerMomentumSigma, EicRcParticle::mRcVertex, EicRcParticle::mRcVtxMomentum, EicDetName::Name(), particle, PerformPidCalculations(), printf(), and ReAssignMomentumValue().
void EicEventAssembler::FinishTask () virtual
Action at end of run. For this task and all of the subtasks.
Reimplemented from FairTask.
Definition at line 473 of file EicEventAssembler.cxx.
View newest version in sPHENIX GitHub at line 473 of file EicEventAssembler.cxx
References FairTask::FinishTask(), mEicRcEventBranch, and mPersistency.
InitStatus EicEventAssembler::Init () virtual
Intialisation at begin of run. To be implemented in the derived class. Success If not kSUCCESS, task will be set inactive.
Reimplemented from FairTask.
Definition at line 59 of file EicEventAssembler.cxx.
View newest version in sPHENIX GitHub at line 59 of file EicEventAssembler.cxx
References _EIC_GENERATOR_EVENT_BRANCH_, _EIC_GENERATOR_TREE_, _EIC_MAPPING_BRANCH_, _PND_MC_BRANCH_, _PND_RC_TRACK_BRANCH_, FairRootManager::GetInFile(), FairRootManager::GetInTree(), FairRootManager::GetObject(), FairRootManager::Instance(), kERROR, kFATAL, kSUCCESS, mEicRcEvent, mGeneratorEvent, mMappingTable, mPndMCTracks, and mPndPidChargedCand.
void EicEventAssembler::PerformPidCalculations () private
Definition at line 167 of file EicEventAssembler.cxx.
View newest version in sPHENIX GitHub at line 167 of file EicEventAssembler.cxx
References _PHOTON_PDG_CODE_, _PION_PDG_CODE_, _POSITRON_PDG_CODE_, PndPidCandidate::GetCharge(), mEicRcEvent, EicRcParticle::mEmCal, EicRcCalorimeterHit::mEnergy, EicRcCalorimeterHit::mEnergySigma, EicRcEvent::mParticles, mPndPidChargedCand, EicRcParticle::mPndPidChargedCandIndex, EicRcParticle::mRcPdgCode, EicRcParticle::mRcTrackerMomentumSigma, EicRcParticle::mRcVtxMomentum, and particle.
Referenced by Exec().
void EicEventAssembler::ReAssignMomentumValue () private
Definition at line 218 of file EicEventAssembler.cxx.
View newest version in sPHENIX GitHub at line 218 of file EicEventAssembler.cxx
References _PHOTON_PDG_CODE_, _PION_PDG_CODE_, _POSITRON_PDG_CODE_, kdfinder::abs(), mEicRcEvent, EicRcParticle::mEmCal, EicRcCalorimeterHit::mEnergy, EicRcCalorimeterHit::mEnergySigma, EicRcParticle::mHCal, EicRcCalorimeterHit::mLocation, EicRcEvent::mParticles, EicRcParticle::mRcPdgCode, EicRcParticle::mRcTrackerMomentumSigma, EicRcParticle::mRcVtxMomentum, and particle.
Referenced by Exec().
Member Data Documentation
std::vector<EicCalorimeterHub*> EicEventAssembler::mCalorimeters private
Definition at line 84 of file EicEventAssembler.h.
View newest version in sPHENIX GitHub at line 84 of file EicEventAssembler.h
Referenced by AddCalorimeterCore(), ComposeCalorimeterInformation(), and Exec().
EicRcEvent* EicEventAssembler::mEicRcEvent private
Definition at line 81 of file EicEventAssembler.h.
View newest version in sPHENIX GitHub at line 81 of file EicEventAssembler.h
Referenced by AssignScatteredLepton(), ComposeCalorimeterInformation(), Exec(), Init(), PerformPidCalculations(), and ReAssignMomentumValue().
TBranch* EicEventAssembler::mEicRcEventBranch private
reconstructed event as a whole
Definition at line 82 of file EicEventAssembler.h.
View newest version in sPHENIX GitHub at line 82 of file EicEventAssembler.h
Referenced by Exec(), and FinishTask().
erhic::EventMC* EicEventAssembler::mGeneratorEvent private
Definition at line 75 of file EicEventAssembler.h.
View newest version in sPHENIX GitHub at line 75 of file EicEventAssembler.h
Referenced by Init().
ParticleMappingTable* EicEventAssembler::mMappingTable private
Definition at line 76 of file EicEventAssembler.h.
View newest version in sPHENIX GitHub at line 76 of file EicEventAssembler.h
Referenced by Exec(), and Init().
Bool_t EicEventAssembler::mPersistency private
Object persistency flag
Definition at line 79 of file EicEventAssembler.h.
View newest version in sPHENIX GitHub at line 79 of file EicEventAssembler.h
Referenced by FinishTask().
TClonesArray* EicEventAssembler::mPndMCTracks private
input arrays of MC and PandaRoot-reconstructed tracks
Definition at line 73 of file EicEventAssembler.h.
View newest version in sPHENIX GitHub at line 73 of file EicEventAssembler.h
Referenced by Init().
TClonesArray * EicEventAssembler::mPndPidChargedCand private
Definition at line 73 of file EicEventAssembler.h.
View newest version in sPHENIX GitHub at line 73 of file EicEventAssembler.h
Referenced by Exec(), Init(), and PerformPidCalculations().
The documentation for this class was generated from the following files:
EicRoot/blob/master/eic/event/EicEventAssembler.h
EicRoot/blob/master/eic/event/EicEventAssembler.cxx