EIC Software: fun4all_coresoftware/blob/master/calibrations/tpc/generator/generate_distortion_map.C File Reference
generate_distortion_map.C File Reference
#include "AnnularFieldSim.h"
#include "TTree.h"
#include "TCanvas.h"
Functions
AnnularFieldSim * SetupDefaultSphenixTpc (bool twinMe=false, bool useSpacecharge=true)
AnnularFieldSim * SetupDigitalCurrentSphenixTpc (bool twinMe=false, bool useSpacecharge=true)
void TestSpotDistortion (AnnularFieldSim *t)
void SurveyFiles (TFileCollection *filelist)
void generate_distortion_map (const char *inputpattern="./evgeny_apr/Smooth*.root", const char *outputfilebase="./apr07_maps/apr07", bool hasSpacecharge=true, bool isDigitalCurrent=false)
Variables
char field_string [200]
char lookup_string [200]
Function Documentation
void generate_distortion_map (const char * inputpattern = "./evgeny_apr/Smooth*.root", const char * outputfilebase = "./apr07_maps/apr07", bool hasSpacecharge = true, bool isDigitalCurrent = false)
Definition at line 17 of file generate_distortion_map.C.
View newest version in sPHENIX GitHub at line 17 of file generate_distortion_map.C
References MultiArray< T >::dim, field_string, AnnularFieldSim::GenerateSeparateDistortionMaps(), MultiArray< T >::GetFlat(), AnnularFieldSim::GetInnerEdge(), AnnularFieldSim::GetOuterEdge(), k, MultiArray< T >::Length(), AnnularFieldSim::load_and_resample_spacecharge(), AnnularFieldSim::load_spacecharge(), lookup_string, AnnularFieldSim::PlotFieldSlices(), AnnularFieldSim::populate_fieldmap(), pos(), printf(), AnnularFieldSim::q, SetupDefaultSphenixTpc(), SurveyFiles(), tpc(), and AnnularFieldSim::twin.
AnnularFieldSim * SetupDefaultSphenixTpc (bool twinMe = false, bool useSpacecharge = true)
Definition at line 145 of file generate_distortion_map.C.
View newest version in sPHENIX GitHub at line 145 of file generate_distortion_map.C
References AnnularFieldSim::borrow_epartial_from(), AnnularFieldSim::borrow_rossegger(), field_string, AnnularFieldSim::FromFile, AnnularFieldSim::green, AnnularFieldSim::load3dBfield(), AnnularFieldSim::load_phislice_lookup(), AnnularFieldSim::load_rossegger(), AnnularFieldSim::loadEfield(), lookup_string, AnnularFieldSim::NoSpacecharge, AnnularFieldSim::PhiSlice, AnnularFieldSim::populate_lookup(), printf(), AnnularFieldSim::save_phislice_lookup(), AnnularFieldSim::set_twin(), AnnularFieldSim::setFlatFields(), tpc(), and AnnularFieldSim::UpdateEveryN().
Referenced by generate_distortion_map().
AnnularFieldSim * SetupDigitalCurrentSphenixTpc (bool twinMe = false, bool useSpacecharge = true)
Definition at line 280 of file generate_distortion_map.C.
View newest version in sPHENIX GitHub at line 280 of file generate_distortion_map.C
References AnnularFieldSim::borrow_epartial_from(), AnnularFieldSim::borrow_rossegger(), field_string, AnnularFieldSim::FromFile, AnnularFieldSim::green, AnnularFieldSim::load3dBfield(), AnnularFieldSim::load_phislice_lookup(), AnnularFieldSim::load_rossegger(), AnnularFieldSim::loadEfield(), lookup_string, AnnularFieldSim::NoSpacecharge, AnnularFieldSim::PhiSlice, AnnularFieldSim::populate_lookup(), printf(), AnnularFieldSim::save_phislice_lookup(), AnnularFieldSim::set_twin(), AnnularFieldSim::setFlatFields(), tpc(), and AnnularFieldSim::UpdateEveryN().
void SurveyFiles (TFileCollection * filelist)
Definition at line 413 of file generate_distortion_map.C.
View newest version in sPHENIX GitHub at line 413 of file generate_distortion_map.C
References printf().
Referenced by generate_distortion_map().
void TestSpotDistortion (AnnularFieldSim * t)
Definition at line 136 of file generate_distortion_map.C.
View newest version in sPHENIX GitHub at line 136 of file generate_distortion_map.C
References AnnularFieldSim::GetStepDistortion(), and AnnularFieldSim::twin.
Variable Documentation
char field_string[200]
Definition at line 8 of file generate_distortion_map.C.
View newest version in sPHENIX GitHub at line 8 of file generate_distortion_map.C
Referenced by generate_distortion_map(), SetupDefaultSphenixTpc(), and SetupDigitalCurrentSphenixTpc().
char lookup_string[200]
Definition at line 9 of file generate_distortion_map.C.
View newest version in sPHENIX GitHub at line 9 of file generate_distortion_map.C
Referenced by generate_distortion_map(), SetupDefaultSphenixTpc(), and SetupDigitalCurrentSphenixTpc().