EIC Software: eic-smear/blob/master/include/eicsmear/functions.h File Reference
functions.h File Reference
#include <string>
#include <Rtypes.h>
#include <TString.h>
#include "eicsmear/smear/Smear.h"
#include "eicsmear/smear/Detector.h"
Classes
class EventToDot
Namespaces
namespace erhic
Enumerations
enum erhic::HepMC_outtype { erhic::HepMC3, erhic::HepMC2, erhic::RootTree, erhic::Root }
Functions
char getFirstNonBlank (const std::string &)
double computeHermesPhiH (const TLorentzVector &hadronInPrf, const TLorentzVector &leptonInPrf, const TLorentzVector &photonInPrf)
Long64_t BuildTree (const std::string &inputFileName, const std::string &outputDirName=".", const Long64_t maxEvent=0, const std::string &logFileName="")
Long64_t TreeToHepMC (const std::string &inputFileName, const std::string &outputDirName=".", Long64_t maxEvent=0, const erhic::HepMC_outtype outtype=erhic::HepMC_outtype::HepMC3)
Long64_t TreeToHepMC (const std::string &inputFileName, const std::string &outputDirName, Long64_t maxEvent, const bool createHepMC2=false)
Variables
const std::string erhic::EicSmearVersionString = "1.1.12"
Detailed Description
Global function declarations.
Author
Thomas Burton
Date
2011-07-07
Copyright
2011 Brookhaven National Lab
Definition in file functions.h.
Function Documentation
Long64_t BuildTree (const std::string & inputFileName, const std::string & outputDirName, const Long64_t maxEvent, const std::string & logFileName)
This is an example function to generate ROOT files. It can be used "out of the box". If more control over the output is desired, then the settings of the Forester can be tweaked to do so.
Definition at line 25 of file BuildTree.cxx.
View newest version in sPHENIX GitHub at line 25 of file BuildTree.cxx
References erhic::FileType::CreateLogReader(), erhic::LogReader::Extract(), erhic::Forester::GetFileType(), erhic::LogReaderFactory::GetInstance(), erhic::LogReaderFactory::Locate(), erhic::Forester::Plant(), reader(), erhic::LogReader::Save(), erhic::Forester::SetBeVerbose(), erhic::Forester::SetBranchName(), erhic::Forester::SetInputFileName(), erhic::Forester::SetMaxNEvents(), erhic::Forester::SetMessageInterval(), and erhic::Forester::SetOutputFileName().
Referenced by build(), ConvertFile(), main(), and make_tree().
double computeHermesPhiH (const TLorentzVector & hadronInPrf, const TLorentzVector & leptonInPrf, const TLorentzVector & photonInPrf)
Calculate the hadron azimuthal angle around the virtual photon direction with respect to the lepton scattering plane in the proton rest frame. We use the HERMES convention, returning an angle in the range [0,2pi]. The vectors passed as arguments should already be boosted to the proton rest frame. Incident and scattered leptons, incident protons and virtual photons all return -999.
Definition at line 52 of file functions.cxx.
View newest version in sPHENIX GitHub at line 52 of file functions.cxx
References Acts::UnitConstants::e, k, and phi.
Referenced by erhic::ParticleMCbase::ComputeEventDependentQuantities().
char getFirstNonBlank (const std::string & line)
Returns the first non-blank character in a line. Returns \0 if there are no non-blank characters in the line.
Definition at line 31 of file functions.cxx.
View newest version in sPHENIX GitHub at line 31 of file functions.cxx
Referenced by erhic::EventFromAsciiFactory< T >::Create().
Long64_t TreeToHepMC (const std::string & inputFileName, const std::string & outputDirName, Long64_t maxEvent, const erhic::HepMC_outtype outtype)
This function converts our tree format to HepMC3 It would be better to skip the ROOT step, but that would require a lot of duplication and/or refactorization
Definition at line 56 of file TreeToHepMC.cxx.
View newest version in sPHENIX GitHub at line 56 of file TreeToHepMC.cxx
References kdfinder::abs(), erhic::EventMC::BeamHadron(), erhic::EventMC::BeamLepton(), c, c1, erhic::EventMC::ExchangeBoson(), eicpy.qaplots::file, erhic::ParticleMCbase::GetChild1Index(), erhic::ParticleMCbase::GetChildNIndex(), erhic::ParticleMCbase::GetE(), erhic::ParticleMCbase::GetIndex(), erhic::ParticleMCbase::GetM(), erhic::ParticleMCbase::GetNChildren(), erhic::EventMC::GetNTracks(), erhic::ParticleMC::GetParent(), erhic::ParticleMCbase::GetParentIndex(), erhic::ParticleMCbase::GetParentIndex1(), erhic::ParticleMCbase::GetPx(), erhic::ParticleMCbase::GetPy(), erhic::ParticleMCbase::GetPz(), erhic::ParticleMCbase::GetStatus(), erhic::EventMC::GetTrack(), erhic::ParticleMCbase::GetVertex(), erhic::HepMC2, erhic::HepMC3, erhic::ParticleMCbase::Id(), max, charm_jet_coverage::mom, p, pdg, erhic::ParticleMCbase::Print(), erhic::Root, erhic::RootTree, Acts::PrimitivesView3DTest::run(), erhic::EventMC::ScatteredLepton(), erhic::ParticleMCbase::SetChild1Index(), erhic::ParticleMCbase::SetChildNIndex(), erhic::ParticleMCbase::SetParentIndex(), erhic::ParticleMCbase::SetParentIndex1(), erhic::ParticleMCbase::SetStatus(), boost::swap(), t, and value.
Referenced by TreeToHepMC().
Long64_t TreeToHepMC (const std::string & inputFileName, const std::string & outputDirName, Long64_t maxEvent, const bool createHepMC2)
Deprecated legacy wrapper
Definition at line 808 of file TreeToHepMC.cxx.
View newest version in sPHENIX GitHub at line 808 of file TreeToHepMC.cxx
References erhic::HepMC2, erhic::HepMC3, and TreeToHepMC().