EIC Software: Nystrom Class Reference
Nystrom Class Reference
#include <EicRoot/blob/master/GenfitTools/trackrep/LSLtrackRep/Nystrom.h>
Public Member Functions
Nystrom (AbsNystromEQM *eqm)
~Nystrom ()
void setFunction (AbsNystromEQM *eqm)
void setAccuracy (double a)
void setAdaptive (bool flag=true)
void step (const TVectorT< double > &u, const TVectorT< double > &uprime, const TVectorT< double > &par, TVectorT< double > &newu, TVectorT< double > &newuprime, double h)
double adaptiveStep (const TVectorT< double > &u, const TVectorT< double > &uprime, const TVectorT< double > &par, TVectorT< double > &newu, TVectorT< double > &newuprime, double &stepdone, double h, double sign, double reststep)
double propagate (double start, double end, const TVectorT< double > &u, const TVectorT< double > &uprime, const TVectorT< double > &par, TVectorT< double > &newu, TVectorT< double > &newuprime)
Private Attributes
AbsNystromEQM * _eqm
double _acc
bool _adaptive
Detailed Description
Definition at line 51 of file Nystrom.h.
View newest version in sPHENIX GitHub at line 51 of file Nystrom.h
Constructor & Destructor Documentation
Nystrom::Nystrom (AbsNystromEQM * eqm)
Definition at line 52 of file Nystrom.cxx.
View newest version in sPHENIX GitHub at line 52 of file Nystrom.cxx
Nystrom::~Nystrom () inline
Definition at line 56 of file Nystrom.h.
View newest version in sPHENIX GitHub at line 56 of file Nystrom.h
Member Function Documentation
double Nystrom::adaptiveStep (const TVectorT< double > & u, const TVectorT< double > & uprime, const TVectorT< double > & par, TVectorT< double > & newu, TVectorT< double > & newuprime, double & stepdone, double h, double sign, double reststep)
Definition at line 81 of file Nystrom.cxx.
View newest version in sPHENIX GitHub at line 81 of file Nystrom.cxx
References _acc, d, Acts::Test::delta, Acts::UnitConstants::h, n, sign(), and step().
Referenced by propagate().
double Nystrom::propagate (double start, double end, const TVectorT< double > & u, const TVectorT< double > & uprime, const TVectorT< double > & par, TVectorT< double > & newu, TVectorT< double > & newuprime)
Definition at line 177 of file Nystrom.cxx.
View newest version in sPHENIX GitHub at line 177 of file Nystrom.cxx
References _acc, _adaptive, adaptiveStep(), dx, dy, Acts::UnitConstants::h, G4BARRELHCAL::length, Acts::UnitConstants::s, sign(), start(), step(), propagation_timing::steps, Acts::UnitConstants::u, and z.
Referenced by LSLTrackRep::extrapolate().
void Nystrom::setAccuracy (double a) inline
Definition at line 60 of file Nystrom.h.
View newest version in sPHENIX GitHub at line 60 of file Nystrom.h
References _acc.
Referenced by LSLTrackRep::extrapolate().
void Nystrom::setAdaptive (bool flag = true) inline
Definition at line 61 of file Nystrom.h.
View newest version in sPHENIX GitHub at line 61 of file Nystrom.h
References _adaptive.
Referenced by LSLTrackRep::extrapolate().
void Nystrom::setFunction (AbsNystromEQM * eqm) inline
Definition at line 59 of file Nystrom.h.
View newest version in sPHENIX GitHub at line 59 of file Nystrom.h
References _eqm.
void Nystrom::step (const TVectorT< double > & u, const TVectorT< double > & uprime, const TVectorT< double > & par, TVectorT< double > & newu, TVectorT< double > & newuprime, double h)
Definition at line 57 of file Nystrom.cxx.
View newest version in sPHENIX GitHub at line 57 of file Nystrom.cxx
References _eqm, AbsNystromEQM::eval(), Acts::UnitConstants::h, h2, k1, k2, and sign().
Referenced by adaptiveStep(), and propagate().
Member Data Documentation
double Nystrom::_acc private
Definition at line 91 of file Nystrom.h.
View newest version in sPHENIX GitHub at line 91 of file Nystrom.h
Referenced by adaptiveStep(), propagate(), and setAccuracy().
bool Nystrom::_adaptive private
Definition at line 92 of file Nystrom.h.
View newest version in sPHENIX GitHub at line 92 of file Nystrom.h
Referenced by propagate(), and setAdaptive().
AbsNystromEQM* Nystrom::_eqm private
Definition at line 90 of file Nystrom.h.
View newest version in sPHENIX GitHub at line 90 of file Nystrom.h
Referenced by setFunction(), and step().
The documentation for this class was generated from the following files:
EicRoot/blob/master/GenfitTools/trackrep/LSLtrackRep/Nystrom.h
EicRoot/blob/master/GenfitTools/trackrep/LSLtrackRep/Nystrom.cxx