EIC Software: EicMoCaPoint Class Reference
EicMoCaPoint Class Reference
#include <EicRoot/blob/master/eic/base/EicMoCaPoint.h>
Public Member Functions
EicMoCaPoint ()
EicMoCaPoint (Int_t trackID, Int_t primaryMotherId, Int_t secondaryMotherId, Int_t detID, ULong64_t multiIndex, const TVector3 &PosIn, const TVector3 &PosOut, const TVector3 &MomIn, const TVector3 &MomOut, Double_t tof, Double_t length, Double_t eLoss, Double_t step)
virtual ~EicMoCaPoint ()
virtual void Print (const Option_t *opt="") const
Test.
void SetStep (Double_t step)
Double_t GetStep () const
TVector3 GetPosIn () const
const TVector3 & GetPosOut () const
TVector3 GetPosAvg () const
TVector3 GetMomAvg () const
Int_t GetPrimaryMotherID () const
Int_t GetSecondaryMotherID () const
void SetPointID (int id)
Int_t GetPointID () const
ULong64_t GetMultiIndex () const
Public Member Functions inherited from FairMCPoint
FairMCPoint ()
FairMCPoint (Int_t trackID, Int_t detID, TVector3 pos, TVector3 mom, Double_t tof, Double_t length, Double_t eLoss, UInt_t EventId=0)
virtual ~FairMCPoint ()
UInt_t GetEventID () const
Int_t GetTrackID () const
event identifier
Double_t GetPx () const
Double_t GetPy () const
Double_t GetPz () const
Double_t GetTime () const
Double_t GetLength () const
Double_t GetEnergyLoss () const
void Momentum (TVector3 &mom)
Int_t GetDetectorID () const
Double_t GetX () const
Double_t GetY () const
Double_t GetZ () const
void Position (TVector3 &pos) const
void SetEventID (UInt_t eventId)
virtual void SetTrackID (Int_t id)
void SetTime (Double_t time)
void SetLength (Double_t length)
void SetEnergyLoss (Double_t eLoss)
void SetMomentum (const TVector3 &mom)
void SetDetectorID (Int_t detID)
void SetX (Double_t x)
void SetY (Double_t y)
void SetZ (Double_t z)
void SetXYZ (Double_t x, Double_t y, Double_t z)
void SetPosition (const TVector3 &pos)
Public Member Functions inherited from FairMultiLinkedData
FairMultiLinkedData ()
Default constructor.
FairMultiLinkedData (std::set< FairLink > links, Bool_t persistanceCheck=kTRUE)
Constructor.
FairMultiLinkedData (TString dataType, std::vector< Int_t > links, Int_t fileId=-1, Int_t evtId=-1, Bool_t persistanceCheck=kTRUE, Bool_t bypass=kFALSE, Float_t mult=1.0)
Constructor.
FairMultiLinkedData (Int_t dataType, std::vector< Int_t > links, Int_t fileId=-1, Int_t evtId=-1, Bool_t persistanceCheck=kTRUE, Bool_t bypass=kFALSE, Float_t mult=1.0)
Constructor.
virtual ~FairMultiLinkedData ()
virtual std::set< FairLink > GetLinks () const
returns stored links as FairLinks
virtual Int_t GetNLinks () const
returns the number of stored links
virtual FairLink GetLink (Int_t pos) const
returns the FairLink at the given position
virtual FairMultiLinkedData GetLinksWithType (Int_t type) const
Gives you a list of links which contain the given type.
TObject * GetData (FairLink &myLink)
Get the TObject the Link is pointing to.
virtual Int_t GetDefaultType ()
Bool_t GetPersistanceCheck ()
Returns the value of PersistanceCheck.
Int_t GetVerbose ()
Returns the verbosity level.
virtual void SetDefaultType (Int_t type)
virtual void SetPersistanceCheck (Bool_t check)
Controls if a persistance check of a link is done or not.
virtual void SetVerbose (Int_t level)
Sets the verbosity level.
virtual void SetLinks (FairMultiLinkedData links, Float_t mult=1.0)
Sets the links as vector of FairLink.
virtual void SetLink (FairLink link, Bool_t bypass=kFALSE, Float_t mult=1.0)
Sets the Links with a single FairLink.
virtual void AddLinks (FairMultiLinkedData links, Float_t mult=1.0)
Adds a List of FairLinks (FairMultiLinkedData) to fLinks.
virtual void AddLink (FairLink link, Bool_t bypass=kFALSE, Float_t mult=1.0)
Adds a FairLink link at the end of fLinks. If multi is kTRUE a link is allowed more than once otherwise it is stored only once.
virtual void InsertLink (FairLink link)
Inserts a link into the list of links without persistance checking.
virtual void AddAllWeights (Double_t weight)
Adds weight to all Links.
virtual void SetAllWeights (Double_t weight)
Sets a common weight for Links.
virtual void MultiplyAllWeights (Double_t weight)
Multiplies all Links with weight.
virtual Bool_t IsLinkInList (FairLink link)
Test if a given link is in fLinks.
virtual Bool_t IsLinkInList (Int_t type, Int_t index)
Same as IsLinkInList(FairLink) just with type and index given separately.
virtual Int_t LinkPosInList (FairLink link)
returns position of link in fLinks. If it is not in the list -1 is returned
virtual Int_t LinkPosInList (Int_t type, Int_t index)
Same as LinkPosInList(FairLink)
virtual void DeleteLink (FairLink link)
Deletes a link ouf of fLinks.
virtual void DeleteLink (Int_t type, Int_t index)
Deletes a link ouf of fLinks.
virtual void Reset ()
virtual void ResetLinks ()
Clears fLinks.
void Print (std::ostream &out=std::cout) const
Output.
Private Attributes
Double32_t mStep
TVector3 mPosOut
TVector3 mMomOut
Int_t mPointID
ULong64_t mMultiIndex
Int_t mPrimaryMotherID
Int_t mSecondaryMotherID
Additional Inherited Members
Protected Member Functions inherited from FairMultiLinkedData
virtual void SimpleAddLinks (Int_t fileId, Int_t evtId, Int_t dataType, std::vector< Int_t > links, Bool_t bypass, Float_t mult)
ClassDef (FairMultiLinkedData, 3)
Protected Attributes inherited from FairMCPoint
Int_t fTrackID
Track index.
UInt_t fEventId
MC Event id.
Double32_t fPx
Double32_t fPy
Double32_t fPz
Momentum components [GeV].
Double32_t fTime
Time since event start [ns].
Double32_t fLength
Track length since creation [cm].
Double32_t fELoss
Energy loss at this point [GeV].
Int_t fDetectorID
Detector unique identifier.
Double32_t fX
Double32_t fY
Double32_t fZ
Position of hit [cm].
Detailed Description
Definition at line 16 of file EicMoCaPoint.h.
View newest version in sPHENIX GitHub at line 16 of file EicMoCaPoint.h
Constructor & Destructor Documentation
EicMoCaPoint::EicMoCaPoint () inline
Definition at line 18 of file EicMoCaPoint.h.
View newest version in sPHENIX GitHub at line 18 of file EicMoCaPoint.h
EicMoCaPoint::EicMoCaPoint (Int_t trackID, Int_t primaryMotherId, Int_t secondaryMotherId, Int_t detID, ULong64_t multiIndex, const TVector3 & PosIn, const TVector3 & PosOut, const TVector3 & MomIn, const TVector3 & MomOut, Double_t tof, Double_t length, Double_t eLoss, Double_t step)
Definition at line 13 of file EicMoCaPoint.cxx.
View newest version in sPHENIX GitHub at line 13 of file EicMoCaPoint.cxx
References mMomOut, mMultiIndex, mPosOut, mPrimaryMotherID, mSecondaryMotherID, mStep, and Acts::Test::step().
virtual EicMoCaPoint::~EicMoCaPoint () inline virtual
Definition at line 25 of file EicMoCaPoint.h.
View newest version in sPHENIX GitHub at line 25 of file EicMoCaPoint.h
Member Function Documentation
TVector3 EicMoCaPoint::GetMomAvg () const inline
Definition at line 36 of file EicMoCaPoint.h.
View newest version in sPHENIX GitHub at line 36 of file EicMoCaPoint.h
References FairMCPoint::fPx, FairMCPoint::fPy, FairMCPoint::fPz, and mMomOut.
Referenced by PndRecoKalmanFit::Fit().
ULong64_t EicMoCaPoint::GetMultiIndex () const inline
Definition at line 46 of file EicMoCaPoint.h.
View newest version in sPHENIX GitHub at line 46 of file EicMoCaPoint.h
Referenced by EicTrackingDigiHit::EicTrackingDigiHit(), EicTpcDigiHitProducer::HandleHit(), EicCalorimeterDigiHitProducer::HandleHit(), and EicTrackingDigiHitProducer::HandleHit().
Int_t EicMoCaPoint::GetPointID () const inline
Definition at line 44 of file EicMoCaPoint.h.
View newest version in sPHENIX GitHub at line 44 of file EicMoCaPoint.h
References mPointID.
Referenced by EicTrackingDigiHit::EicTrackingDigiHit().
TVector3 EicMoCaPoint::GetPosAvg () const inline
Definition at line 35 of file EicMoCaPoint.h.
View newest version in sPHENIX GitHub at line 35 of file EicMoCaPoint.h
References GetPosIn(), and GetPosOut().
Referenced by PndRecoKalmanFit::Fit().
TVector3 EicMoCaPoint::GetPosIn () const inline
Definition at line 33 of file EicMoCaPoint.h.
View newest version in sPHENIX GitHub at line 33 of file EicMoCaPoint.h
References FairMCPoint::Position().
Referenced by EicDetector::EndOfEvent(), GetPosAvg(), EicTpcDigiHitProducer::HandleHit(), EicCalorimeterDigiHitProducer::HandleHit(), and EicTrackingDigiHitProducer::HandleHit().
const TVector3& EicMoCaPoint::GetPosOut () const inline
Definition at line 34 of file EicMoCaPoint.h.
View newest version in sPHENIX GitHub at line 34 of file EicMoCaPoint.h
References mPosOut.
Referenced by GetPosAvg(), EicTpcDigiHitProducer::HandleHit(), EicCalorimeterDigiHitProducer::HandleHit(), and EicTrackingDigiHitProducer::HandleHit().
Int_t EicMoCaPoint::GetPrimaryMotherID () const inline
Definition at line 40 of file EicMoCaPoint.h.
View newest version in sPHENIX GitHub at line 40 of file EicMoCaPoint.h
References mPrimaryMotherID.
Referenced by EicCalorimeterDigiHitProducer::HandleHit().
Int_t EicMoCaPoint::GetSecondaryMotherID () const inline
Definition at line 41 of file EicMoCaPoint.h.
View newest version in sPHENIX GitHub at line 41 of file EicMoCaPoint.h
References mSecondaryMotherID.
Referenced by EicCalorimeterDigiHitProducer::HandleHit().
Double_t EicMoCaPoint::GetStep () const inline
Definition at line 30 of file EicMoCaPoint.h.
View newest version in sPHENIX GitHub at line 30 of file EicMoCaPoint.h
References mStep.
Referenced by EicCalorimeterDigiHitProducer::HandleHit().
void EicMoCaPoint::Print (const Option_t * opt = "") const virtual
Test.
Implements FairMCPoint.
Definition at line 37 of file EicMoCaPoint.cxx.
View newest version in sPHENIX GitHub at line 37 of file EicMoCaPoint.cxx
References FairMCPoint::fELoss, FairMCPoint::fTrackID, FairMCPoint::fX, FairMCPoint::fY, and FairMCPoint::fZ.
void EicMoCaPoint::SetPointID (int id) inline
Definition at line 43 of file EicMoCaPoint.h.
View newest version in sPHENIX GitHub at line 43 of file EicMoCaPoint.h
References mPointID.
Referenced by EicDigiHitProducer::Exec().
void EicMoCaPoint::SetStep (Double_t step) inline
Definition at line 29 of file EicMoCaPoint.h.
View newest version in sPHENIX GitHub at line 29 of file EicMoCaPoint.h
References mStep, and Acts::Test::step().
Member Data Documentation
TVector3 EicMoCaPoint::mMomOut private
Definition at line 52 of file EicMoCaPoint.h.
View newest version in sPHENIX GitHub at line 52 of file EicMoCaPoint.h
Referenced by EicMoCaPoint(), and GetMomAvg().
ULong64_t EicMoCaPoint::mMultiIndex private
Definition at line 59 of file EicMoCaPoint.h.
View newest version in sPHENIX GitHub at line 59 of file EicMoCaPoint.h
Referenced by EicMoCaPoint().
Int_t EicMoCaPoint::mPointID private
Definition at line 57 of file EicMoCaPoint.h.
View newest version in sPHENIX GitHub at line 57 of file EicMoCaPoint.h
Referenced by GetPointID(), and SetPointID().
TVector3 EicMoCaPoint::mPosOut private
Definition at line 52 of file EicMoCaPoint.h.
View newest version in sPHENIX GitHub at line 52 of file EicMoCaPoint.h
Referenced by EicMoCaPoint(), and GetPosOut().
Int_t EicMoCaPoint::mPrimaryMotherID private
Definition at line 61 of file EicMoCaPoint.h.
View newest version in sPHENIX GitHub at line 61 of file EicMoCaPoint.h
Referenced by EicMoCaPoint(), and GetPrimaryMotherID().
Int_t EicMoCaPoint::mSecondaryMotherID private
Definition at line 66 of file EicMoCaPoint.h.
View newest version in sPHENIX GitHub at line 66 of file EicMoCaPoint.h
Referenced by EicMoCaPoint(), and GetSecondaryMotherID().
Double32_t EicMoCaPoint::mStep private
Definition at line 46 of file EicMoCaPoint.h.
View newest version in sPHENIX GitHub at line 46 of file EicMoCaPoint.h
Referenced by EicMoCaPoint(), GetStep(), and SetStep().
The documentation for this class was generated from the following files:
EicRoot/blob/master/eic/base/EicMoCaPoint.h
EicRoot/blob/master/eic/base/EicMoCaPoint.cxx