EIC Software: Smear::Acceptance Class Reference
Smear::Acceptance Class Reference
#include <eic-smear/blob/master/include/eicsmear/smear/Acceptance.h>
Classes
class CustomCut
class CustomCutFunction
class Zone
Public Member Functions
virtual ~Acceptance ()
Acceptance (int genre=kAll)
void AddZone (const Zone &)
UInt_t GetNZones () const
Int_t GetGenre () const
void SetGenre (int genre)
void SetCharge (ECharge charge)
ECharge GetCharge () const
void AddParticle (int particle)
bool Is (const erhic::VirtualParticle &prt) const
Protected Attributes
int mGenre
ECharge mCharge
std::vector< Zone > mZones
std::set< int > mParticles
Detailed Description
Defines a range of acceptance in one or more of: theta, phi, E, p, pt, pz. Comprises one or more acceptance zones, which may or may not overlap.
Definition at line 38 of file Acceptance.h.
View newest version in sPHENIX GitHub at line 38 of file Acceptance.h
Constructor & Destructor Documentation
Smear::Acceptance::~Acceptance () virtual
Destructor
Definition at line 18 of file Acceptance.cxx.
View newest version in sPHENIX GitHub at line 18 of file Acceptance.cxx
Smear::Acceptance::Acceptance (int genre = kAll) explicit
Default constructor. The genre sets which particle types are accepted (see Smear::EGenre). By default, the device has 4pi coverage, and accepts particles with all energy and momenta.
Definition at line 21 of file Acceptance.cxx.
View newest version in sPHENIX GitHub at line 21 of file Acceptance.cxx
Member Function Documentation
void Smear::Acceptance::AddParticle (int particle)
Add a particle type to the list of particles to be smeared. If you never add anything, the device will smear all stable particles within its acceptance. Must use PDG particle codes.
Definition at line 42 of file Acceptance.cxx.
View newest version in sPHENIX GitHub at line 42 of file Acceptance.cxx
References mParticles.
Referenced by Smear::Bremsstrahlung::Bremsstrahlung(), BuildBeAST_0_0(), BuildBeAST_0_1(), BuildHandBook_1_2(), BuildJLEIC_0_1(), BuildMatrixDetector_0_1(), BuildMatrixDetector_0_1_FF(), and BuildMatrixDetector_0_1_TOF().
void Smear::Acceptance::AddZone (const Zone & z)
Add a new zone with user-specified coverage. Particles will be accepted if they fall within any acceptance zone.
Definition at line 26 of file Acceptance.cxx.
View newest version in sPHENIX GitHub at line 26 of file Acceptance.cxx
References mZones.
Referenced by AssembleCoreTracker(), BuildBeAST_0_0(), BuildBeAST_0_1(), BuildCore_0_1(), BuildCore_0_1_B3T(), BuildePHENIX_0_0(), BuildeSTAR_0_0(), BuildHandBook_1_2(), BuildJLEIC_0_1(), BuildMatrixDetector_0_1(), BuildMatrixDetector_0_1_FF(), BuildMatrixDetector_0_1_TOF(), BuildMatrixDetector_0_2_B1_5T(), BuildMatrixDetector_0_2_B3T(), BuildPerfectDetector(), BuildSTAR_0_0(), BuildTrackingPreview_0_2_B1_5T(), BuildTrackingPreview_0_2_B3T(), BuildWithTof(), and BuildZEUS_0_0().
ECharge Smear::Acceptance::GetCharge () const inline
Returns the charge of particles to accept.
Definition at line 201 of file Acceptance.h.
View newest version in sPHENIX GitHub at line 201 of file Acceptance.h
References mCharge.
Int_t Smear::Acceptance::GetGenre () const inline
Returns the "genre" of the particle (em, hadronic or all).
Definition at line 197 of file Acceptance.h.
View newest version in sPHENIX GitHub at line 197 of file Acceptance.h
References mGenre.
UInt_t Smear::Acceptance::GetNZones () const inline
Returns the number of acceptance zones.
Definition at line 193 of file Acceptance.h.
View newest version in sPHENIX GitHub at line 193 of file Acceptance.h
References mZones.
bool Smear::Acceptance::Is (const erhic::VirtualParticle & prt) const
This function determines if the particle provided lies within the acceptance of the detector. Default acceptance is a full 4*pi solid angle, with E and p in (0.,1e12) GeV. This function automatically fixes polar and azimuthal angles which are not within their proper range.
Definition at line 46 of file Acceptance.cxx.
View newest version in sPHENIX GitHub at line 46 of file Acceptance.cxx
References erhic::VirtualParticle::Id(), erhic::Pid::Info(), Smear::kAllCharges, Smear::kCharged, Smear::kNeutral, mCharge, mGenre, mParticles, mZones, pdg, and Smear::PGenre().
Referenced by Smear::Tracker::Smear(), Smear::Device::Smear(), and Smear::ParticleID::Smear().
void Smear::Acceptance::SetCharge (ECharge charge)
Select the charges of particles to accept.
Definition at line 38 of file Acceptance.cxx.
View newest version in sPHENIX GitHub at line 38 of file Acceptance.cxx
References charge, and mCharge.
Referenced by AssembleCoreTracker(), BuildBeAST_0_0(), BuildBeAST_0_1(), BuildCore_0_1(), BuildCore_0_1_B3T(), BuildeSTAR_0_0(), BuildHandBook_1_2(), BuildJLEIC_0_1(), BuildMatrixDetector_0_1(), BuildMatrixDetector_0_1_FF(), BuildMatrixDetector_0_1_TOF(), BuildMatrixDetector_0_2_B1_5T(), BuildMatrixDetector_0_2_B3T(), BuildSTAR_0_0(), BuildTrackingPreview_0_2_B1_5T(), BuildTrackingPreview_0_2_B3T(), BuildWithTof(), and EPhenixMomentum::EPhenixMomentum().
void Smear::Acceptance::SetGenre (int genre)
Select the class(es) of particles to accept.
Definition at line 30 of file Acceptance.cxx.
View newest version in sPHENIX GitHub at line 30 of file Acceptance.cxx
References mGenre, and n.
Referenced by BuildBeAST_0_0(), BuildBeAST_0_1(), BuildCore_0_1(), BuildCore_0_1_B3T(), BuildHandBook_1_2(), BuildJLEIC_0_1(), BuildMatrixDetector_0_1(), BuildMatrixDetector_0_1_FF(), BuildMatrixDetector_0_1_TOF(), BuildMatrixDetector_0_2_B1_5T(), BuildMatrixDetector_0_2_B3T(), BuildTrackingPreview_0_2_B1_5T(), BuildTrackingPreview_0_2_B3T(), Smear::Device::Device(), and Smear::Device::Init().
Member Data Documentation
ECharge Smear::Acceptance::mCharge protected
Definition at line 186 of file Acceptance.h.
View newest version in sPHENIX GitHub at line 186 of file Acceptance.h
Referenced by GetCharge(), Is(), and SetCharge().
int Smear::Acceptance::mGenre protected
Definition at line 185 of file Acceptance.h.
View newest version in sPHENIX GitHub at line 185 of file Acceptance.h
Referenced by GetGenre(), Is(), and SetGenre().
std::set<int> Smear::Acceptance::mParticles protected
Definition at line 188 of file Acceptance.h.
View newest version in sPHENIX GitHub at line 188 of file Acceptance.h
Referenced by AddParticle(), and Is().
std::vector<Zone> Smear::Acceptance::mZones protected
Definition at line 187 of file Acceptance.h.
View newest version in sPHENIX GitHub at line 187 of file Acceptance.h
Referenced by AddZone(), GetNZones(), and Is().
The documentation for this class was generated from the following files:
eic-smear/blob/master/include/eicsmear/smear/Acceptance.h
eic-smear/blob/master/src/smear/Acceptance.cxx