EIC Software: RawTowerZDCContainer Class Reference
RawTowerZDCContainer Class Reference
#include <fun4all_eicdetectors/blob/master/reconstruction/eiczdcbase/RawTowerZDCContainer.h>
Public Types
typedef std::map
< RawTowerZDCDefs::keytype,
RawTowerZDC * > Map
typedef Map::iterator Iterator
typedef Map::const_iterator ConstIterator
typedef std::pair< Iterator,
Iterator > Range
typedef std::pair
< ConstIterator, ConstIterator > ConstRange
Public Member Functions
RawTowerZDCContainer (RawTowerZDCDefs::CalorimeterId caloid=RawTowerZDCDefs::NONE)
~RawTowerZDCContainer () override
void Reset () override
Clear Event.
int isValid () const override
isValid returns non zero if object contains vailid data
void identify (std::ostream &os=std::cout) const override
void setCalorimeterID (RawTowerZDCDefs::CalorimeterId caloid)
RawTowerZDCDefs::CalorimeterId getCalorimeterID ()
ConstIterator AddTower (const unsigned int ieta, const unsigned int iphi, const unsigned int il, RawTowerZDC *twr)
ConstIterator AddTower (RawTowerZDCDefs::keytype key, RawTowerZDC *twr)
RawTowerZDC * getTower (RawTowerZDCDefs::keytype key)
const RawTowerZDC * getTower (RawTowerZDCDefs::keytype key) const
RawTowerZDC * getTower (const unsigned int ieta, const unsigned int iphi, const unsigned int il)
const RawTowerZDC * getTower (const unsigned int ieta, const unsigned int iphi, const unsigned int il) const
ConstRange getTowers (void) const
return all towers
Range getTowers (void)
unsigned int size () const
void compress (const double emin)
double getTotalEdep () const
Public Member Functions inherited from PHObject
PHObject ()
ctor
~PHObject () override
dtor
virtual PHObject * CloneMe () const
Virtual copy constructor.
virtual PHObject * clone () const final
PHObject * Clone (const char *newname="") const final
void Copy (TObject &object) const final
virtual int isValid (const float) const
virtual int isValid (const double) const
virtual int isValid (const int) const
virtual int isValid (const unsigned int) const
virtual int isImplemented (const float f) const
virtual int isImplemented (const double f) const
virtual int isImplemented (const int i) const
virtual int isImplemented (const unsigned int i) const
virtual int Integrate () const
virtual int Integrate (PHObject *)
virtual void CopyFrom (const PHObject *obj)
Protected Attributes
RawTowerZDCDefs::CalorimeterId _caloid
Map _towers
Detailed Description
Definition at line 14 of file RawTowerZDCContainer.h.
View newest version in sPHENIX GitHub at line 14 of file RawTowerZDCContainer.h
Member Typedef Documentation
typedef Map::const_iterator RawTowerZDCContainer::ConstIterator
Definition at line 19 of file RawTowerZDCContainer.h.
View newest version in sPHENIX GitHub at line 19 of file RawTowerZDCContainer.h
typedef std::pair<ConstIterator, ConstIterator> RawTowerZDCContainer::ConstRange
Definition at line 21 of file RawTowerZDCContainer.h.
View newest version in sPHENIX GitHub at line 21 of file RawTowerZDCContainer.h
typedef Map::iterator RawTowerZDCContainer::Iterator
Definition at line 18 of file RawTowerZDCContainer.h.
View newest version in sPHENIX GitHub at line 18 of file RawTowerZDCContainer.h
typedef std::map<RawTowerZDCDefs::keytype, RawTowerZDC *> RawTowerZDCContainer::Map
Definition at line 17 of file RawTowerZDCContainer.h.
View newest version in sPHENIX GitHub at line 17 of file RawTowerZDCContainer.h
typedef std::pair<Iterator, Iterator> RawTowerZDCContainer::Range
Definition at line 20 of file RawTowerZDCContainer.h.
View newest version in sPHENIX GitHub at line 20 of file RawTowerZDCContainer.h
Constructor & Destructor Documentation
RawTowerZDCContainer::RawTowerZDCContainer (RawTowerZDCDefs::CalorimeterId caloid = RawTowerZDCDefs::NONE) inline
Definition at line 23 of file RawTowerZDCContainer.h.
View newest version in sPHENIX GitHub at line 23 of file RawTowerZDCContainer.h
RawTowerZDCContainer::~RawTowerZDCContainer () inline override
Definition at line 28 of file RawTowerZDCContainer.h.
View newest version in sPHENIX GitHub at line 28 of file RawTowerZDCContainer.h
Member Function Documentation
ConstIterator RawTowerZDCContainer::AddTower (const unsigned int ieta, const unsigned int iphi, const unsigned int il, RawTowerZDC * twr)
Referenced by RawTowerZDCCalibration::process_event(), EICG4ZDCRawTowerBuilderByHitIndex::process_event(), and RawTowerZDCDigitizer::process_event().
RawTowerZDCContainer::ConstIterator RawTowerZDCContainer::AddTower (RawTowerZDCDefs::keytype key, RawTowerZDC * twr)
Definition at line 56 of file RawTowerZDCContainer.cc.
View newest version in sPHENIX GitHub at line 56 of file RawTowerZDCContainer.cc
References RawTowerZDCDefs::decode_caloid(), exit(), and RawTowerZDC::set_id().
void RawTowerZDCContainer::compress (const double emin)
Definition at line 10 of file RawTowerZDCContainer.cc.
View newest version in sPHENIX GitHub at line 10 of file RawTowerZDCContainer.cc
References CEMC_TOWER::emin, and RawTowerZDC::get_energy().
Referenced by EICG4ZDCRawTowerBuilderByHitIndex::process_event().
RawTowerZDCDefs::CalorimeterId RawTowerZDCContainer::getCalorimeterID () inline
Definition at line 35 of file RawTowerZDCContainer.h.
View newest version in sPHENIX GitHub at line 35 of file RawTowerZDCContainer.h
References _caloid.
Referenced by RawTowerZDCCalibration::CreateNodes(), and RawTowerZDCDigitizer::CreateNodes().
double RawTowerZDCContainer::getTotalEdep () const
Definition at line 128 of file RawTowerZDCContainer.cc.
View newest version in sPHENIX GitHub at line 128 of file RawTowerZDCContainer.cc
Referenced by RawTowerZDCCalibration::process_event(), EICG4ZDCRawTowerBuilderByHitIndex::process_event(), and RawTowerZDCDigitizer::process_event().
RawTowerZDC * RawTowerZDCContainer::getTower (RawTowerZDCDefs::keytype key)
Definition at line 72 of file RawTowerZDCContainer.cc.
View newest version in sPHENIX GitHub at line 72 of file RawTowerZDCContainer.cc
References it.
Referenced by EICG4ZDCRawTowerBuilderByHitIndex::process_event(), and RawTowerZDCDigitizer::process_event().
const RawTowerZDC * RawTowerZDCContainer::getTower (RawTowerZDCDefs::keytype key) const
Definition at line 83 of file RawTowerZDCContainer.cc.
View newest version in sPHENIX GitHub at line 83 of file RawTowerZDCContainer.cc
References it.
RawTowerZDC * RawTowerZDCContainer::getTower (const unsigned int ieta, const unsigned int iphi, const unsigned int il)
Definition at line 94 of file RawTowerZDCContainer.cc.
View newest version in sPHENIX GitHub at line 94 of file RawTowerZDCContainer.cc
References RawTowerZDCDefs::encode_towerid_zdc().
const RawTowerZDC * RawTowerZDCContainer::getTower (const unsigned int ieta, const unsigned int iphi, const unsigned int il) const
Definition at line 101 of file RawTowerZDCContainer.cc.
View newest version in sPHENIX GitHub at line 101 of file RawTowerZDCContainer.cc
References RawTowerZDCDefs::encode_towerid_zdc().
RawTowerZDCContainer::ConstRange RawTowerZDCContainer::getTowers (void) const
return all towers
Definition at line 34 of file RawTowerZDCContainer.cc.
View newest version in sPHENIX GitHub at line 34 of file RawTowerZDCContainer.cc
Referenced by RawTowerZDCCalibration::process_event(), and EICG4ZDCRawTowerBuilderByHitIndex::process_event().
RawTowerZDCContainer::Range RawTowerZDCContainer::getTowers (void)
Definition at line 40 of file RawTowerZDCContainer.cc.
View newest version in sPHENIX GitHub at line 40 of file RawTowerZDCContainer.cc
void RawTowerZDCContainer::identify (std::ostream & os = std::cout) const override virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from PHObject.
Definition at line 122 of file RawTowerZDCContainer.cc.
View newest version in sPHENIX GitHub at line 122 of file RawTowerZDCContainer.cc
Referenced by EICG4ZDCRawTowerBuilderByHitIndex::process_event().
int RawTowerZDCContainer::isValid () const override virtual
isValid returns non zero if object contains vailid data
Reimplemented from PHObject.
Definition at line 108 of file RawTowerZDCContainer.cc.
View newest version in sPHENIX GitHub at line 108 of file RawTowerZDCContainer.cc
void RawTowerZDCContainer::Reset () override virtual
Clear Event.
Reimplemented from PHObject.
Definition at line 113 of file RawTowerZDCContainer.cc.
View newest version in sPHENIX GitHub at line 113 of file RawTowerZDCContainer.cc
void RawTowerZDCContainer::setCalorimeterID (RawTowerZDCDefs::CalorimeterId caloid) inline
Definition at line 34 of file RawTowerZDCContainer.h.
View newest version in sPHENIX GitHub at line 34 of file RawTowerZDCContainer.h
References _caloid.
unsigned int RawTowerZDCContainer::size (void) const inline
Definition at line 50 of file RawTowerZDCContainer.h.
View newest version in sPHENIX GitHub at line 50 of file RawTowerZDCContainer.h
References _towers.
Referenced by EICG4ZDCRawTowerBuilderByHitIndex::process_event().
Member Data Documentation
RawTowerZDCDefs::CalorimeterId RawTowerZDCContainer::_caloid protected
Definition at line 55 of file RawTowerZDCContainer.h.
View newest version in sPHENIX GitHub at line 55 of file RawTowerZDCContainer.h
Referenced by getCalorimeterID(), and setCalorimeterID().
Map RawTowerZDCContainer::_towers protected
Definition at line 56 of file RawTowerZDCContainer.h.
View newest version in sPHENIX GitHub at line 56 of file RawTowerZDCContainer.h
Referenced by size().
The documentation for this class was generated from the following files:
fun4all_eicdetectors/blob/master/reconstruction/eiczdcbase/RawTowerZDCContainer.h
fun4all_eicdetectors/blob/master/reconstruction/eiczdcbase/RawTowerZDCContainer.cc