EIC Software: GFPseudoSpacepointWireHitPolicy Class Reference
GFPseudoSpacepointWireHitPolicy Class Reference
Genfit
Policy class implementing a poseudo space point hit geometry.
#include <EicRoot/blob/master/genfit/GFPseudoSpacepointWireHitPolicy.h>
Public Member Functions
GFPseudoSpacepointWireHitPolicy ()
const GFDetPlane & detPlane (GFAbsRecoHit *, GFAbsTrackRep *)
Get detector plane perpendicular to track.
TMatrixT< double > hitCoord (GFAbsRecoHit *, const GFDetPlane &)
Hit coordinates in detector plane.
TMatrixT< double > hitCov (GFAbsRecoHit *, const GFDetPlane &)
Hit covariances in detector plane.
virtual ~GFPseudoSpacepointWireHitPolicy ()
double getMaxDistance ()
void setMaxDistance (double d)
TVector3 getWireDirection ()
void setWireDirection (TVector3 &dir)
const std::string & getName ()
ClassDef (GFPseudoSpacepointWireHitPolicy, 1)
Private Attributes
GFDetPlane fDetPlane
double fMaxdistance
TVector3 fWireDirection
Static Private Attributes
static const std::string fPolicyName = "GFPseudoSpacepointWireHitPolicy"
Detailed Description
Policy class implementing a poseudo space point hit geometry.
Author
Johannes Rauch (Technische Universität München, original author)
RecoHits for detectors measuring 3D space points with errors in one direction (the "wire direction") much larger than the errors perpendicular should inherit from RecoHitIfc<GFPseudoSpacepointWireHitPolicy>.
For these hits, a virtual detector plane lying in the POCA and perpendicular to the track yields wrong results. Instead, the plane should contain the direction of the largest error (i.e. the "wire direction").
The "wire direction" can be set. Standard is in z.
Definition at line 50 of file GFPseudoSpacepointWireHitPolicy.h.
View newest version in sPHENIX GitHub at line 50 of file GFPseudoSpacepointWireHitPolicy.h
Constructor & Destructor Documentation
GFPseudoSpacepointWireHitPolicy::GFPseudoSpacepointWireHitPolicy ()
Definition at line 31 of file GFPseudoSpacepointWireHitPolicy.cxx.
View newest version in sPHENIX GitHub at line 31 of file GFPseudoSpacepointWireHitPolicy.cxx
virtual GFPseudoSpacepointWireHitPolicy::~GFPseudoSpacepointWireHitPolicy () inline virtual
Definition at line 73 of file GFPseudoSpacepointWireHitPolicy.h.
View newest version in sPHENIX GitHub at line 73 of file GFPseudoSpacepointWireHitPolicy.h
Member Function Documentation
GFPseudoSpacepointWireHitPolicy::ClassDef (GFPseudoSpacepointWireHitPolicy , 1)
const GFDetPlane & GFPseudoSpacepointWireHitPolicy::detPlane (GFAbsRecoHit * hit, GFAbsTrackRep * rep)
Get detector plane perpendicular to track.
The detector plane is contructed from the position of the hit and the track representation. For this the track is extrapolated to the point of closest approach to a line parallel to z and containing the hit.
Definition at line 99 of file GFPseudoSpacepointWireHitPolicy.cxx.
View newest version in sPHENIX GitHub at line 99 of file GFPseudoSpacepointWireHitPolicy.cxx
References GFDetPlane::dist(), Acts::UnitConstants::e, GFAbsTrackRep::extrapolateToLine(), fDetPlane, fMaxdistance, fWireDirection, and GFAbsRecoHit::getRawHitCoord().
double GFPseudoSpacepointWireHitPolicy::getMaxDistance () inline
Definition at line 75 of file GFPseudoSpacepointWireHitPolicy.h.
View newest version in sPHENIX GitHub at line 75 of file GFPseudoSpacepointWireHitPolicy.h
References fMaxdistance.
const std::string& GFPseudoSpacepointWireHitPolicy::getName () inline
Definition at line 81 of file GFPseudoSpacepointWireHitPolicy.h.
View newest version in sPHENIX GitHub at line 81 of file GFPseudoSpacepointWireHitPolicy.h
References fPolicyName.
TVector3 GFPseudoSpacepointWireHitPolicy::getWireDirection () inline
Definition at line 78 of file GFPseudoSpacepointWireHitPolicy.h.
View newest version in sPHENIX GitHub at line 78 of file GFPseudoSpacepointWireHitPolicy.h
References fWireDirection.
TMatrixT< double > GFPseudoSpacepointWireHitPolicy::hitCoord (GFAbsRecoHit * hit, const GFDetPlane & plane)
Hit coordinates in detector plane.
Definition at line 40 of file GFPseudoSpacepointWireHitPolicy.cxx.
View newest version in sPHENIX GitHub at line 40 of file GFPseudoSpacepointWireHitPolicy.cxx
References GFDetPlane::getO(), GFAbsRecoHit::getRawHitCoord(), GFDetPlane::getU(), and GFDetPlane::getV().
TMatrixT< double > GFPseudoSpacepointWireHitPolicy::hitCov (GFAbsRecoHit * hit, const GFDetPlane & plane)
Hit covariances in detector plane.
Definition at line 69 of file GFPseudoSpacepointWireHitPolicy.cxx.
View newest version in sPHENIX GitHub at line 69 of file GFPseudoSpacepointWireHitPolicy.cxx
References GFAbsRecoHit::getRawHitCov(), GFDetPlane::getU(), and GFDetPlane::getV().
void GFPseudoSpacepointWireHitPolicy::setMaxDistance (double d) inline
Definition at line 76 of file GFPseudoSpacepointWireHitPolicy.h.
View newest version in sPHENIX GitHub at line 76 of file GFPseudoSpacepointWireHitPolicy.h
References d, and fMaxdistance.
void GFPseudoSpacepointWireHitPolicy::setWireDirection (TVector3 & dir) inline
Definition at line 79 of file GFPseudoSpacepointWireHitPolicy.h.
View newest version in sPHENIX GitHub at line 79 of file GFPseudoSpacepointWireHitPolicy.h
References fWireDirection.
Member Data Documentation
GFDetPlane GFPseudoSpacepointWireHitPolicy::fDetPlane private
Definition at line 87 of file GFPseudoSpacepointWireHitPolicy.h.
View newest version in sPHENIX GitHub at line 87 of file GFPseudoSpacepointWireHitPolicy.h
Referenced by detPlane().
double GFPseudoSpacepointWireHitPolicy::fMaxdistance private
Definition at line 88 of file GFPseudoSpacepointWireHitPolicy.h.
View newest version in sPHENIX GitHub at line 88 of file GFPseudoSpacepointWireHitPolicy.h
Referenced by detPlane(), getMaxDistance(), and setMaxDistance().
const std::string GFPseudoSpacepointWireHitPolicy::fPolicyName = "GFPseudoSpacepointWireHitPolicy" static private
Definition at line 84 of file GFPseudoSpacepointWireHitPolicy.h.
View newest version in sPHENIX GitHub at line 84 of file GFPseudoSpacepointWireHitPolicy.h
Referenced by getName().
TVector3 GFPseudoSpacepointWireHitPolicy::fWireDirection private
Definition at line 89 of file GFPseudoSpacepointWireHitPolicy.h.
View newest version in sPHENIX GitHub at line 89 of file GFPseudoSpacepointWireHitPolicy.h
Referenced by detPlane(), getWireDirection(), and setWireDirection().
The documentation for this class was generated from the following files:
EicRoot/blob/master/genfit/GFPseudoSpacepointWireHitPolicy.h
EicRoot/blob/master/genfit/GFPseudoSpacepointWireHitPolicy.cxx