EIC Software: FairGeoBuilder Class Reference
FairGeoBuilder Class Reference abstract
#include <EicRoot/blob/master/geobase/FairGeoBuilder.h>
Public Member Functions
virtual ~FairGeoBuilder ()
virtual Bool_t createNode (FairGeoNode *, Int_t hadFormat=0)=0
virtual Int_t createMedium (FairGeoMedium *)=0
virtual void finalize ()
Protected Member Functions
FairGeoBuilder ()
FairGeoBuilder (const char *name, const char *title)
Protected Attributes
Int_t nRot
Int_t nMed
Detailed Description
abstract base class for geometry builders
Author
ilse koenig
Definition at line 14 of file FairGeoBuilder.h.
View newest version in sPHENIX GitHub at line 14 of file FairGeoBuilder.h
Constructor & Destructor Documentation
FairGeoBuilder::FairGeoBuilder () protected
FairGeoBuilder::FairGeoBuilder (const char * name, const char * title) protected
Definition at line 23 of file FairGeoBuilder.cxx.
View newest version in sPHENIX GitHub at line 23 of file FairGeoBuilder.cxx
virtual FairGeoBuilder::~FairGeoBuilder () inline virtual
Definition at line 23 of file FairGeoBuilder.h.
View newest version in sPHENIX GitHub at line 23 of file FairGeoBuilder.h
Member Function Documentation
virtual Int_t FairGeoBuilder::createMedium (FairGeoMedium *) pure virtual
Implemented in FairGeoRootBuilder.
Referenced by FairModule::AssignMediumAtImport(), CbmRich::ConstructGdmlGeometry(), PndPipe::ConstructGeometry(), CbmRich::ExpandNodeForGdml(), EicMediaHub::GetMedium(), and EicGeoParData::GetMedium().
virtual Bool_t FairGeoBuilder::createNode (FairGeoNode * , Int_t hadFormat = 0) pure virtual
Implemented in FairGeoRootBuilder.
Referenced by FairGeoSet::create().
virtual void FairGeoBuilder::finalize () inline virtual
Reimplemented in FairGeoRootBuilder.
Definition at line 26 of file FairGeoBuilder.h.
View newest version in sPHENIX GitHub at line 26 of file FairGeoBuilder.h
Referenced by FairGeoInterface::createAll(), and FairGeoInterface::createGeometry().
Member Data Documentation
Int_t FairGeoBuilder::nMed protected
Definition at line 18 of file FairGeoBuilder.h.
View newest version in sPHENIX GitHub at line 18 of file FairGeoBuilder.h
Referenced by FairGeoRootBuilder::createMedium().
Int_t FairGeoBuilder::nRot protected
Definition at line 17 of file FairGeoBuilder.h.
View newest version in sPHENIX GitHub at line 17 of file FairGeoBuilder.h
Referenced by FairGeoRootBuilder::createNode().
The documentation for this class was generated from the following files:
EicRoot/blob/master/geobase/FairGeoBuilder.h
EicRoot/blob/master/geobase/FairGeoBuilder.cxx