EIC Software: fun4all_GenFit/blob/master/GBL/src/GFGbl.cc File Reference
GFGbl.cc File Reference
#include "GFGbl.h"
#include "GblTrajectory.h"
#include "GblPoint.h"
#include "MyDebugTools.h"
#include "AbsMeasurement.h"
#include "PlanarMeasurement.h"
#include "KalmanFitterInfo.h"
#include "Track.h"
#include <TFile.h>
#include <TH1F.h>
#include <TTree.h>
#include <string>
#include <list>
#include <FieldManager.h>
#include <HMatrixU.h>
#include <HMatrixV.h>
#include <Math/SMatrix.h>
#include <TMatrixD.h>
#include <TVectorDfwd.h>
#include <TMatrixT.h>
#include <TVector3.h>
Functions
void getScattererFromMatList (double &length, double &theta, double &s, double &ds, const double p, const double mass, const double charge, const std::vector< MatStep > &steps)
Evaluates moments of radiation length distribution from list of material steps and computes parameters describing a corresponding thick scatterer.
Variables
gbl::MilleBinary * milleFile
const double scatEpsilon = 1.e-8
Function Documentation
void getScattererFromMatList (double & length, double & theta, double & s, double & ds, const double p, const double mass, const double charge, const std::vector< MatStep > & steps)
Evaluates moments of radiation length distribution from list of material steps and computes parameters describing a corresponding thick scatterer.
Based on input from Claus Kleinwort (DESY), adapted for continuous material distribution represented by a sum of step functions. Returned thick scatterer can be represented by two GBL scattering points at (s - ds) and (s + ds) with variance of theta equal to theta/sqrt(2) for both points. Calculates variance of theta from total sum of radiation lengths instead of summimg squares of individual deflection angle variances.
Parameters
length returned: Length of the track
theta returned: Variation of distribution of deflection angle
s returned: First moment of material scattering distribution
ds returned: Second moment (variance) of material scattering distribution
p Particle momentum magnitude (GeV/c)
mass Mass of particle (GeV/c/c)
steps Vector of material steps from (RKTrackRep) extrapolation
Returns
void
Definition at line 263 of file GFGbl.cc.
View newest version in sPHENIX GitHub at line 263 of file GFGbl.cc
References Acts::UnitConstants::e, genfit::MatStep::material_, charm_jet_strange_helicity::N, genfit::Material::radiationLength, Acts::UnitConstants::s, Acts::Test::step(), genfit::MatStep::stepSize_, xmax, and xmin.
Referenced by genfit::GblFitter::constructGblInfo(), and genfit::GFGbl::processTrackWithRep().
Variable Documentation
gbl::MilleBinary* milleFile
Definition at line 166 of file GFGbl.cc.
View newest version in sPHENIX GitHub at line 166 of file GFGbl.cc
Referenced by genfit::GFGbl::endRun().
const double scatEpsilon = 1.e-8
Definition at line 168 of file GFGbl.cc.
View newest version in sPHENIX GitHub at line 168 of file GFGbl.cc
Referenced by genfit::GblFitter::constructGblInfo().