EIC Software: PHG4CylinderStripSteppingAction Class Reference
PHG4CylinderStripSteppingAction Class Reference
#include <fun4all_eicdetectors/blob/master/simulation/g4simulation/g4barrelmmg/PHG4CylinderStripSteppingAction.h>
Public Member Functions
PHG4CylinderStripSteppingAction (PHG4CylinderStripDetector *, const PHParameters *parameters)
constructor
virtual ~PHG4CylinderStripSteppingAction ()
destructor
bool UserSteppingAction (const G4Step *, bool)
stepping action
void SetInterfacePointers (PHCompositeNode *)
reimplemented from base class
void SaveLightYield (const int i=1)
Public Member Functions inherited from PHG4SteppingAction
PHG4SteppingAction (const std::string &name, const int i=0)
virtual ~PHG4SteppingAction ()
virtual void Verbosity (const int i)
virtual int Verbosity () const
virtual int Init ()
virtual double GetScintLightYield (const G4Step *step)
get scintillation photon count. It require a custom set SCINTILLATIONYIELD property to work
virtual double GetVisibleEnergyDeposition (const G4Step *step)
get amount of energy that can make scintillation light, in Unit of GeV.
virtual void StoreLocalCoordinate (PHG4Hit *hit, const G4Step *step, const bool do_prepoint, const bool do_postpoint)
Extract local coordinate of the hit and save to PHG4Hit.
virtual void Print (const std::string &) const
std::string GetName () const
void SetName (const std::string &name)
virtual void SetLightCorrection (const double inner_radius, const double inner_corr, const double outer_radius, const double outer_corr)
virtual double GetLightCorrection (const double r) const
virtual double GetLightCorrection (const double xpos, const double ypos) const
virtual bool ValidCorrection () const
virtual void SetHitNodeName (const std::string &, const std::string &)
Set the G4HIT node names from Subsystem rather than constructing your own.
Private Attributes
PHG4CylinderStripDetector * m_Detector
pointer to the detector
const PHParameters * m_Params
PHG4HitContainer * m_HitContainer
pointer to hit container
PHG4Hit * m_Hit
PHG4Shower * m_SaveShower
G4VPhysicalVolume * m_SaveVolPre
G4VPhysicalVolume * m_SaveVolPost
int m_SaveLightYieldFlag
int m_SaveTrackId
int m_SavePreStepStatus
int m_SavePostStepStatus
int m_ActiveFlag
int m_BlackHoleFlag
int m_UseG4StepsFlag
double m_Zmin
double m_Zmax
double m_Tmin
double m_Tmax
Detailed Description
Definition at line 17 of file PHG4CylinderStripSteppingAction.h.
View newest version in sPHENIX GitHub at line 17 of file PHG4CylinderStripSteppingAction.h
Constructor & Destructor Documentation
PHG4CylinderStripSteppingAction::PHG4CylinderStripSteppingAction (PHG4CylinderStripDetector * detector, const PHParameters * parameters)
constructor
Definition at line 47 of file PHG4CylinderStripSteppingAction.cc.
View newest version in sPHENIX GitHub at line 47 of file PHG4CylinderStripSteppingAction.cc
References Acts::UnitConstants::cm, m_Zmax, and m_Zmin.
PHG4CylinderStripSteppingAction::~PHG4CylinderStripSteppingAction () virtual
destructor
Definition at line 73 of file PHG4CylinderStripSteppingAction.cc.
View newest version in sPHENIX GitHub at line 73 of file PHG4CylinderStripSteppingAction.cc
References m_Hit.
Member Function Documentation
void PHG4CylinderStripSteppingAction::SaveLightYield (const int i = 1) inline
Definition at line 32 of file PHG4CylinderStripSteppingAction.h.
View newest version in sPHENIX GitHub at line 32 of file PHG4CylinderStripSteppingAction.h
References m_SaveLightYieldFlag.
void PHG4CylinderStripSteppingAction::SetInterfacePointers (PHCompositeNode * topNode) virtual
reimplemented from base class
Reimplemented from PHG4SteppingAction.
Definition at line 332 of file PHG4CylinderStripSteppingAction.cc.
View newest version in sPHENIX GitHub at line 332 of file PHG4CylinderStripSteppingAction.cc
References PHG4Detector::GetName(), m_BlackHoleFlag, m_Detector, m_HitContainer, and PHG4CylinderStripDetector::SuperDetector().
bool PHG4CylinderStripSteppingAction::UserSteppingAction (const G4Step * aStep, bool) virtual
stepping action
Implements PHG4SteppingAction.
Definition at line 83 of file PHG4CylinderStripSteppingAction.cc.
View newest version in sPHENIX GitHub at line 83 of file PHG4CylinderStripSteppingAction.cc
References PHG4Shower::add_g4hit_id(), PHG4HitContainer::AddHit(), Acts::UnitConstants::cm, PHG4Hit::get_edep(), PHG4Hit::get_eion(), PHG4Hit::get_hit_id(), PHG4CylinderStripDetector::get_Layer(), PHG4Hit::get_light_yield(), PHG4Hit::get_x(), PHG4Hit::get_z(), PHG4HitContainer::GetID(), PHG4SteppingAction::GetName(), PHG4StepStatusDecode::GetStepStatus(), PHG4SteppingAction::GetVisibleEnergyDeposition(), Acts::UnitConstants::GeV, PHG4CylinderStripDetector::IsInTileC(), PHG4CylinderStripDetector::IsInTileZ(), m_ActiveFlag, m_BlackHoleFlag, m_Detector, m_Hit, m_HitContainer, m_SaveLightYieldFlag, m_SavePostStepStatus, m_SavePreStepStatus, m_SaveShower, m_SaveTrackId, m_SaveVolPost, m_SaveVolPre, m_Tmax, m_Tmin, m_UseG4StepsFlag, m_Zmax, m_Zmin, p, PHG4Hit::Reset(), PHG4Hit::set_edep(), PHG4Hit::set_eion(), PHG4Hit::set_hit_type(), PHG4Hit::set_layer(), PHG4Hit::set_light_yield(), PHG4Hit::set_px(), PHG4Hit::set_py(), PHG4Hit::set_pz(), PHG4Hit::set_shower_id(), PHG4Hit::set_t(), PHG4Hit::set_trkid(), PHG4Hit::set_x(), PHG4Hit::set_y(), PHG4Hit::set_z(), PHG4CylinderStripDetector::SuperDetector(), and Acts::Test::volume.
Member Data Documentation
int PHG4CylinderStripSteppingAction::m_ActiveFlag private
Definition at line 50 of file PHG4CylinderStripSteppingAction.h.
View newest version in sPHENIX GitHub at line 50 of file PHG4CylinderStripSteppingAction.h
Referenced by UserSteppingAction().
int PHG4CylinderStripSteppingAction::m_BlackHoleFlag private
Definition at line 51 of file PHG4CylinderStripSteppingAction.h.
View newest version in sPHENIX GitHub at line 51 of file PHG4CylinderStripSteppingAction.h
Referenced by SetInterfacePointers(), and UserSteppingAction().
PHG4CylinderStripDetector* PHG4CylinderStripSteppingAction::m_Detector private
pointer to the detector
Definition at line 36 of file PHG4CylinderStripSteppingAction.h.
View newest version in sPHENIX GitHub at line 36 of file PHG4CylinderStripSteppingAction.h
Referenced by SetInterfacePointers(), and UserSteppingAction().
PHG4Hit* PHG4CylinderStripSteppingAction::m_Hit private
Definition at line 42 of file PHG4CylinderStripSteppingAction.h.
View newest version in sPHENIX GitHub at line 42 of file PHG4CylinderStripSteppingAction.h
Referenced by UserSteppingAction(), and ~PHG4CylinderStripSteppingAction().
PHG4HitContainer* PHG4CylinderStripSteppingAction::m_HitContainer private
pointer to hit container
Definition at line 41 of file PHG4CylinderStripSteppingAction.h.
View newest version in sPHENIX GitHub at line 41 of file PHG4CylinderStripSteppingAction.h
Referenced by SetInterfacePointers(), and UserSteppingAction().
const PHParameters* PHG4CylinderStripSteppingAction::m_Params private
Definition at line 38 of file PHG4CylinderStripSteppingAction.h.
View newest version in sPHENIX GitHub at line 38 of file PHG4CylinderStripSteppingAction.h
int PHG4CylinderStripSteppingAction::m_SaveLightYieldFlag private
Definition at line 46 of file PHG4CylinderStripSteppingAction.h.
View newest version in sPHENIX GitHub at line 46 of file PHG4CylinderStripSteppingAction.h
Referenced by SaveLightYield(), and UserSteppingAction().
int PHG4CylinderStripSteppingAction::m_SavePostStepStatus private
Definition at line 49 of file PHG4CylinderStripSteppingAction.h.
View newest version in sPHENIX GitHub at line 49 of file PHG4CylinderStripSteppingAction.h
Referenced by UserSteppingAction().
int PHG4CylinderStripSteppingAction::m_SavePreStepStatus private
Definition at line 48 of file PHG4CylinderStripSteppingAction.h.
View newest version in sPHENIX GitHub at line 48 of file PHG4CylinderStripSteppingAction.h
Referenced by UserSteppingAction().
PHG4Shower* PHG4CylinderStripSteppingAction::m_SaveShower private
Definition at line 43 of file PHG4CylinderStripSteppingAction.h.
View newest version in sPHENIX GitHub at line 43 of file PHG4CylinderStripSteppingAction.h
Referenced by UserSteppingAction().
int PHG4CylinderStripSteppingAction::m_SaveTrackId private
Definition at line 47 of file PHG4CylinderStripSteppingAction.h.
View newest version in sPHENIX GitHub at line 47 of file PHG4CylinderStripSteppingAction.h
Referenced by UserSteppingAction().
G4VPhysicalVolume* PHG4CylinderStripSteppingAction::m_SaveVolPost private
Definition at line 45 of file PHG4CylinderStripSteppingAction.h.
View newest version in sPHENIX GitHub at line 45 of file PHG4CylinderStripSteppingAction.h
Referenced by UserSteppingAction().
G4VPhysicalVolume* PHG4CylinderStripSteppingAction::m_SaveVolPre private
Definition at line 44 of file PHG4CylinderStripSteppingAction.h.
View newest version in sPHENIX GitHub at line 44 of file PHG4CylinderStripSteppingAction.h
Referenced by UserSteppingAction().
double PHG4CylinderStripSteppingAction::m_Tmax private
Definition at line 56 of file PHG4CylinderStripSteppingAction.h.
View newest version in sPHENIX GitHub at line 56 of file PHG4CylinderStripSteppingAction.h
Referenced by UserSteppingAction().
double PHG4CylinderStripSteppingAction::m_Tmin private
Definition at line 55 of file PHG4CylinderStripSteppingAction.h.
View newest version in sPHENIX GitHub at line 55 of file PHG4CylinderStripSteppingAction.h
Referenced by UserSteppingAction().
int PHG4CylinderStripSteppingAction::m_UseG4StepsFlag private
Definition at line 52 of file PHG4CylinderStripSteppingAction.h.
View newest version in sPHENIX GitHub at line 52 of file PHG4CylinderStripSteppingAction.h
Referenced by UserSteppingAction().
double PHG4CylinderStripSteppingAction::m_Zmax private
Definition at line 54 of file PHG4CylinderStripSteppingAction.h.
View newest version in sPHENIX GitHub at line 54 of file PHG4CylinderStripSteppingAction.h
Referenced by PHG4CylinderStripSteppingAction(), and UserSteppingAction().
double PHG4CylinderStripSteppingAction::m_Zmin private
Definition at line 53 of file PHG4CylinderStripSteppingAction.h.
View newest version in sPHENIX GitHub at line 53 of file PHG4CylinderStripSteppingAction.h
Referenced by PHG4CylinderStripSteppingAction(), and UserSteppingAction().
The documentation for this class was generated from the following files:
fun4all_eicdetectors/blob/master/simulation/g4simulation/g4barrelmmg/PHG4CylinderStripSteppingAction.h
fun4all_eicdetectors/blob/master/simulation/g4simulation/g4barrelmmg/PHG4CylinderStripSteppingAction.cc