EIC Software: FairParVersion Class Reference
FairParVersion Class Reference
#include <EicRoot/blob/master/parbase/FairRtdbRun.h>
Public Member Functions
FairParVersion ()
FairParVersion (Text_t *name)
~FairParVersion ()
void setInputVersion (Int_t v=-1, Int_t i=0)
Int_t getInputVersion (Int_t i)
void resetInputVersions ()
void setRootVersion (Int_t v)
Int_t getRootVersion ()
Protected Attributes
Int_t inputVersions [3]
Int_t rootVersion
version of the parameter container in the 2 possible inputs
Detailed Description
Definition at line 12 of file FairRtdbRun.h.
View newest version in sPHENIX GitHub at line 12 of file FairRtdbRun.h
Constructor & Destructor Documentation
FairParVersion::FairParVersion () inline
Definition at line 18 of file FairRtdbRun.h.
View newest version in sPHENIX GitHub at line 18 of file FairRtdbRun.h
FairParVersion::FairParVersion (Text_t * name)
FairParVersion::~FairParVersion () inline
Definition at line 20 of file FairRtdbRun.h.
View newest version in sPHENIX GitHub at line 20 of file FairRtdbRun.h
Member Function Documentation
Int_t FairParVersion::getInputVersion (Int_t i) inline
Definition at line 24 of file FairRtdbRun.h.
View newest version in sPHENIX GitHub at line 24 of file FairRtdbRun.h
References inputVersions.
Referenced by FairDetParRootFileIo::findInputVersion(), FairRuntimeDb::findOutputVersion(), FairRtdbRun::print(), and FairRtdbRun::write().
Int_t FairParVersion::getRootVersion () inline
Definition at line 32 of file FairRtdbRun.h.
View newest version in sPHENIX GitHub at line 32 of file FairRtdbRun.h
References rootVersion.
Referenced by FairDetParRootFileIo::findInputVersion(), FairRuntimeDb::findOutputVersion(), FairRtdbRun::print(), FairRtdbRun::write(), and FairRuntimeDb::writeContainer().
void FairParVersion::resetInputVersions () inline
Definition at line 28 of file FairRtdbRun.h.
View newest version in sPHENIX GitHub at line 28 of file FairRtdbRun.h
References inputVersions.
Referenced by FairRtdbRun::resetInputVersions().
void FairParVersion::setInputVersion (Int_t v = -1, Int_t i = 0) inline
Definition at line 21 of file FairRtdbRun.h.
View newest version in sPHENIX GitHub at line 21 of file FairRtdbRun.h
References inputVersions, and v.
Referenced by FairRuntimeDb::setInputVersion(), and FairRuntimeDb::writeContainer().
void FairParVersion::setRootVersion (Int_t v) inline
Definition at line 31 of file FairRtdbRun.h.
View newest version in sPHENIX GitHub at line 31 of file FairRtdbRun.h
References rootVersion, and v.
Referenced by FairRtdbRun::resetOutputVersions(), FairRuntimeDb::setRootOutputVersion(), and FairRuntimeDb::writeContainer().
Member Data Documentation
Int_t FairParVersion::inputVersions[3] protected
Definition at line 15 of file FairRtdbRun.h.
View newest version in sPHENIX GitHub at line 15 of file FairRtdbRun.h
Referenced by getInputVersion(), resetInputVersions(), and setInputVersion().
Int_t FairParVersion::rootVersion protected
version of the parameter container in the 2 possible inputs
Definition at line 16 of file FairRtdbRun.h.
View newest version in sPHENIX GitHub at line 16 of file FairRtdbRun.h
Referenced by getRootVersion(), and setRootVersion().
The documentation for this class was generated from the following file:
EicRoot/blob/master/parbase/FairRtdbRun.h