EIC Software: eASTSupportStructure Class Reference
eASTSupportStructure Class Reference
#include <east/blob/main/Components/Beampipe/include/eASTSupportStructure.hh>
Public Member Functions
eASTSupportStructure (G4String compName, G4int vl=0, const G4bool validate_gdml=false)
virtual ~eASTSupportStructure ()
virtual void SetUp ()
virtual void Construct (G4VPhysicalVolume *)
void SetGDML (G4String fn)
void SetMatFile (G4String fn)
Public Member Functions inherited from eASTVDetectorComponent
eASTVDetectorComponent (G4String compName, G4int vl=0)
virtual ~eASTVDetectorComponent ()
virtual void ConstructActionForMaster ()
virtual void ConstructSD ()
virtual void ConstructActions ()
void SetUpBase (G4int vl=0)
virtual G4VPhysicalVolume * GetEnvelope ()
virtual G4Region * GetRegion ()
void SetLocation (G4ThreeVector pos)
void SetRotation (G4String ax, G4double ang)
G4ThreeVector GetLocation ()
G4RotationMatrix GetRotation ()
Protected Attributes
const G4bool m_validate_gdml =false
Protected Attributes inherited from eASTVDetectorComponent
G4String componentName
G4String commandDir
G4int verboseLevel
G4VPhysicalVolume * pEnvelopePhys = nullptr
G4Region * pRegion = nullptr
Private Attributes
G4GenericMessenger * messenger = nullptr
G4String gdmlFileName = "*NOTDEFINED*"
G4String matFileName = "*NOTDEFINED*"
G4bool materialToBeSet = false
Additional Inherited Members
Protected Member Functions inherited from eASTVDetectorComponent
void Locate (G4LogicalVolume *compLogVol, G4VPhysicalVolume *worldPhys)
G4String LocateDataFile (const G4String fn) const
Utility method to locate data files in the MacroSearchPath.
void RegisterUserAction (G4UserRunAction *)
void RegisterUserAction (G4UserEventAction *)
void RegisterUserAction (G4UserStackingAction *)
void RegisterUserAction (G4UserTrackingAction *)
void RegisterUserAction (G4UserSteppingAction *)
void ReadMaterialFile (G4String)
Detailed Description
Definition at line 18 of file eASTSupportStructure.hh.
View newest version in sPHENIX GitHub at line 18 of file eASTSupportStructure.hh
Constructor & Destructor Documentation
eASTSupportStructure::eASTSupportStructure (G4String compName, G4int vl = 0, const G4bool validate_gdml = false)
Definition at line 25 of file eASTSupportStructure.cc.
View newest version in sPHENIX GitHub at line 25 of file eASTSupportStructure.cc
eASTSupportStructure::~eASTSupportStructure () virtual
Definition at line 29 of file eASTSupportStructure.cc.
View newest version in sPHENIX GitHub at line 29 of file eASTSupportStructure.cc
References messenger.
Member Function Documentation
void eASTSupportStructure::Construct (G4VPhysicalVolume * worldPhys) virtual
Implements eASTVDetectorComponent.
Definition at line 51 of file eASTSupportStructure.cc.
View newest version in sPHENIX GitHub at line 51 of file eASTSupportStructure.cc
References eASTVDetectorComponent::componentName, gdmlFileName, eASTVDetectorComponent::GetLocation(), eASTVDetectorComponent::GetRotation(), G4GDMLParser::GetWorldVolume(), m_validate_gdml, materialToBeSet, matFileName, charm_jet_coverage::parser, eASTVDetectorComponent::pRegion, G4GDMLParser::Read(), eASTVDetectorComponent::ReadMaterialFile(), G4GDMLParser::SetReverseSearch(), and G4GDMLParser::SetStripFlag().
void eASTSupportStructure::SetGDML (G4String fn) inline
Definition at line 38 of file eASTSupportStructure.hh.
View newest version in sPHENIX GitHub at line 38 of file eASTSupportStructure.hh
References gdmlFileName, and eASTVDetectorComponent::LocateDataFile().
Referenced by SetUp().
void eASTSupportStructure::SetMatFile (G4String fn) inline
Definition at line 40 of file eASTSupportStructure.hh.
View newest version in sPHENIX GitHub at line 40 of file eASTSupportStructure.hh
References eASTVDetectorComponent::LocateDataFile(), materialToBeSet, and matFileName.
Referenced by SetUp().
void eASTSupportStructure::SetUp () virtual
Implements eASTVDetectorComponent.
Definition at line 38 of file eASTSupportStructure.cc.
View newest version in sPHENIX GitHub at line 38 of file eASTSupportStructure.cc
References eASTVDetectorComponent::commandDir, messenger, SetGDML(), and SetMatFile().
Member Data Documentation
G4String eASTSupportStructure::gdmlFileName = "*NOTDEFINED*" private
Definition at line 30 of file eASTSupportStructure.hh.
View newest version in sPHENIX GitHub at line 30 of file eASTSupportStructure.hh
Referenced by Construct(), and SetGDML().
const G4bool eASTSupportStructure::m_validate_gdml =false protected
Definition at line 35 of file eASTSupportStructure.hh.
View newest version in sPHENIX GitHub at line 35 of file eASTSupportStructure.hh
Referenced by Construct().
G4bool eASTSupportStructure::materialToBeSet = false private
Definition at line 32 of file eASTSupportStructure.hh.
View newest version in sPHENIX GitHub at line 32 of file eASTSupportStructure.hh
Referenced by Construct(), and SetMatFile().
G4String eASTSupportStructure::matFileName = "*NOTDEFINED*" private
Definition at line 31 of file eASTSupportStructure.hh.
View newest version in sPHENIX GitHub at line 31 of file eASTSupportStructure.hh
Referenced by Construct(), and SetMatFile().
G4GenericMessenger* eASTSupportStructure::messenger = nullptr private
Definition at line 29 of file eASTSupportStructure.hh.
View newest version in sPHENIX GitHub at line 29 of file eASTSupportStructure.hh
Referenced by SetUp(), and ~eASTSupportStructure().
The documentation for this class was generated from the following files:
east/blob/main/Components/Beampipe/include/eASTSupportStructure.hh
east/blob/main/Components/Beampipe/src/eASTSupportStructure.cc