EIC Software: FairAnaSelector Class Reference
FairAnaSelector Class Reference
#include <EicRoot/blob/master/base/FairAnaSelector.h>
Public Member Functions
FairAnaSelector (TTree *=0)
virtual ~FairAnaSelector ()
virtual Int_t Version () const
virtual void Begin (TTree *tree)
virtual void SlaveBegin (TTree *tree)
virtual void Init (TTree *tree)
virtual Bool_t Notify ()
virtual Bool_t Process (Long64_t entry)
virtual Int_t GetEntry (Long64_t entry, Int_t getall=0)
virtual void SetOption (const char *option)
virtual void SetObject (TObject *obj)
virtual void SetInputList (TList *input)
virtual TList * GetOutputList () const
virtual void SlaveTerminate ()
virtual void Terminate ()
void SetFairRunAna (FairRunAna *runAna)
Public Attributes
TProofOutputFile * fProofFile
TFile * fFile
TTree * fChain
FairRunAna * fRunAna
pointer to the analyzed TTree or TChain
Private Member Functions
FairAnaSelector (const FairAnaSelector &)
FairAnaSelector operator= (const FairAnaSelector &)
ClassDef (FairAnaSelector, 0)
Detailed Description
Definition at line 21 of file FairAnaSelector.h.
View newest version in sPHENIX GitHub at line 21 of file FairAnaSelector.h
Constructor & Destructor Documentation
FairAnaSelector::FairAnaSelector (TTree * = 0) inline
Definition at line 29 of file FairAnaSelector.h.
View newest version in sPHENIX GitHub at line 29 of file FairAnaSelector.h
virtual FairAnaSelector::~FairAnaSelector () inline virtual
Definition at line 30 of file FairAnaSelector.h.
View newest version in sPHENIX GitHub at line 30 of file FairAnaSelector.h
FairAnaSelector::FairAnaSelector (const FairAnaSelector &) private
Member Function Documentation
void FairAnaSelector::Begin (TTree * tree) virtual
Definition at line 202 of file FairAnaSelector.cxx.
View newest version in sPHENIX GitHub at line 202 of file FairAnaSelector.cxx
FairAnaSelector::ClassDef (FairAnaSelector , 0) private
virtual Int_t FairAnaSelector::GetEntry (Long64_t entry, Int_t getall = 0) inline virtual
Definition at line 39 of file FairAnaSelector.h.
View newest version in sPHENIX GitHub at line 39 of file FairAnaSelector.h
References fChain.
virtual TList* FairAnaSelector::GetOutputList () const inline virtual
Definition at line 51 of file FairAnaSelector.h.
View newest version in sPHENIX GitHub at line 51 of file FairAnaSelector.h
void FairAnaSelector::Init (TTree * tree) virtual
Definition at line 39 of file FairAnaSelector.cxx.
View newest version in sPHENIX GitHub at line 39 of file FairAnaSelector.cxx
References fFile, fRunAna, FairRunAna::GetContainerStatic(), FairTask::Init(), FairRunAna::InitContainers(), FairRootManager::Instance(), FairParAsciiFileIo::open(), FairParRootFileIo::open(), FairRootManager::OpenInTree(), writeMapConfig::outFileName, FairRuntimeDb::setFirstInput(), FairRunAna::SetInTree(), and FairRuntimeDb::setSecondInput().
Bool_t FairAnaSelector::Notify () virtual
Definition at line 188 of file FairAnaSelector.cxx.
View newest version in sPHENIX GitHub at line 188 of file FairAnaSelector.cxx
FairAnaSelector FairAnaSelector::operator= (const FairAnaSelector &) private
Bool_t FairAnaSelector::Process (Long64_t entry) virtual
Definition at line 228 of file FairAnaSelector.cxx.
View newest version in sPHENIX GitHub at line 228 of file FairAnaSelector.cxx
References fRunAna, and FairRunAna::RunOneEvent().
void FairAnaSelector::SetFairRunAna (FairRunAna * runAna) inline
Definition at line 57 of file FairAnaSelector.h.
View newest version in sPHENIX GitHub at line 57 of file FairAnaSelector.h
References fRunAna.
virtual void FairAnaSelector::SetInputList (TList * input) inline virtual
Definition at line 48 of file FairAnaSelector.h.
View newest version in sPHENIX GitHub at line 48 of file FairAnaSelector.h
virtual void FairAnaSelector::SetObject (TObject * obj) inline virtual
Definition at line 45 of file FairAnaSelector.h.
View newest version in sPHENIX GitHub at line 45 of file FairAnaSelector.h
virtual void FairAnaSelector::SetOption (const char * option) inline virtual
Definition at line 42 of file FairAnaSelector.h.
View newest version in sPHENIX GitHub at line 42 of file FairAnaSelector.h
void FairAnaSelector::SlaveBegin (TTree * tree) virtual
Definition at line 213 of file FairAnaSelector.cxx.
View newest version in sPHENIX GitHub at line 213 of file FairAnaSelector.cxx
void FairAnaSelector::SlaveTerminate () virtual
Definition at line 257 of file FairAnaSelector.cxx.
View newest version in sPHENIX GitHub at line 257 of file FairAnaSelector.cxx
References fFile, fProofFile, fRunAna, and FairRunAna::TerminateRun().
void FairAnaSelector::Terminate () virtual
Definition at line 302 of file FairAnaSelector.cxx.
View newest version in sPHENIX GitHub at line 302 of file FairAnaSelector.cxx
virtual Int_t FairAnaSelector::Version () const inline virtual
Definition at line 31 of file FairAnaSelector.h.
View newest version in sPHENIX GitHub at line 31 of file FairAnaSelector.h
Member Data Documentation
TTree* FairAnaSelector::fChain
Definition at line 26 of file FairAnaSelector.h.
View newest version in sPHENIX GitHub at line 26 of file FairAnaSelector.h
Referenced by GetEntry().
TFile* FairAnaSelector::fFile
Definition at line 25 of file FairAnaSelector.h.
View newest version in sPHENIX GitHub at line 25 of file FairAnaSelector.h
Referenced by Init(), and SlaveTerminate().
TProofOutputFile* FairAnaSelector::fProofFile
Definition at line 24 of file FairAnaSelector.h.
View newest version in sPHENIX GitHub at line 24 of file FairAnaSelector.h
Referenced by SlaveTerminate().
FairRunAna* FairAnaSelector::fRunAna
pointer to the analyzed TTree or TChain
Definition at line 27 of file FairAnaSelector.h.
View newest version in sPHENIX GitHub at line 27 of file FairAnaSelector.h
Referenced by Init(), Process(), SetFairRunAna(), and SlaveTerminate().
The documentation for this class was generated from the following files:
EicRoot/blob/master/base/FairAnaSelector.h
EicRoot/blob/master/base/FairAnaSelector.cxx