EIC Software: FwdMatchCandidate Class Reference
FwdMatchCandidate Class Reference
#include <EicRoot/blob/master/eic/htree/FwdMatchCandidate.h>
Public Member Functions
FwdMatchCandidate (const HoughTree *tree=0)
~FwdMatchCandidate ()
void ShapeItUpForInspection (const HoughTree *tree, const unsigned id[])
void AssertKalmanFilterPassedFlag ()
bool IsReadyForFinalFit () const
void SetFilterChiSquare (double chiSquare, double chiSquareCCDF, unsigned ndf)
void SetMcTrackId (int id)
int GetMcTrackId () const
void SetWrongHitCount (unsigned count)
unsigned GetWrongHitCount () const
void SetAmbiguityFlag (bool flag)
bool IsAmbiguous () const
void SetVtxCoord (double x, double y, double z)
void SetVtxMomentum (double sx, double sy, double invp)
void SetVtxCoordSigma (double sigmaX, double sigmaY)
void SetVtxSlopeSigma (double sigmaX, double sigmaY)
double GetX () const
double GetY () const
double GetZ () const
double GetVtxCoordSigma (unsigned xy) const
double GetVtxSlopeSigma (unsigned xy) const
int GetFilterNdf () const
double GetFilterChiSquareCCDF () const
double GetTrackQualityParameter () const
const TVector3 & GetMomentum () const
double GetSlopeX () const
double GetSlopeY () const
double GetP () const
int GetCharge () const
Public Member Functions inherited from MatchCandidate
MatchCandidate (const HoughTree *tree=0)
~MatchCandidate ()
void ResetToTheVirginState ()
void ResetOkGroupCounter ()
unsigned GetOkGroupCounter () const
void IncrementOkGroupCounter (unsigned add)
void SetGroupedStatus (bool status)
bool IsGrouped () const
void SetInactive ()
bool IsActive () const
const unsigned * GetIdPtr () const
bool IsSubset (const HoughTree *tree, const MatchCandidate *reference) const
void ResetMemberPtr (unsigned gr, unsigned mm)
void ResetMemberPtr (unsigned gr, GroupMember *member)
void ResetMemberCount (unsigned gr)
unsigned GetLinearMemberCount (unsigned gr) const
unsigned GetAliveMemberCount (unsigned gr) const
GroupMember * GetFirstAliveMember (unsigned gr) const
unsigned GetAliveGroupCount () const
unsigned GetAliveMemberCount () const
void AddMember (unsigned gr, GroupMember *member)
GroupMember * GetSelMember (unsigned gr, unsigned mm)
bool HasAmbiguousHits () const
__u64 Ambiguity () const
bool SiamGroupCandidate (unsigned minHitCount)
unsigned GetGdim () const
Private Attributes
unsigned mNdf
double mFilterChiSquare
double mFilterChiSquareCCDF
int mMcTrackId
unsigned mWrongHitCount
bool mMcTrackAssociationAmbiguous
TVector3 mVertex
TVector3 mMomentum
double mCoordSigma [2]
double mSlopeSigma [2]
int mCharge
bool mPassedKalmanFilterOnce
Detailed Description
Definition at line 19 of file FwdMatchCandidate.h.
View newest version in sPHENIX GitHub at line 19 of file FwdMatchCandidate.h
Constructor & Destructor Documentation
FwdMatchCandidate::FwdMatchCandidate (const HoughTree * tree = 0) inline
Definition at line 21 of file FwdMatchCandidate.h.
View newest version in sPHENIX GitHub at line 21 of file FwdMatchCandidate.h
References mCoordSigma, and mSlopeSigma.
FwdMatchCandidate::~FwdMatchCandidate () inline
Definition at line 39 of file FwdMatchCandidate.h.
View newest version in sPHENIX GitHub at line 39 of file FwdMatchCandidate.h
Member Function Documentation
void FwdMatchCandidate::AssertKalmanFilterPassedFlag () inline
Definition at line 46 of file FwdMatchCandidate.h.
View newest version in sPHENIX GitHub at line 46 of file FwdMatchCandidate.h
References mPassedKalmanFilterOnce.
Referenced by FwdHoughTree::ResolveAmbiguitiesNg().
int FwdMatchCandidate::GetCharge () const inline
Definition at line 91 of file FwdMatchCandidate.h.
View newest version in sPHENIX GitHub at line 91 of file FwdMatchCandidate.h
double FwdMatchCandidate::GetFilterChiSquareCCDF () const inline
Definition at line 83 of file FwdMatchCandidate.h.
View newest version in sPHENIX GitHub at line 83 of file FwdMatchCandidate.h
References mFilterChiSquareCCDF.
Referenced by GetTrackQualityParameter().
int FwdMatchCandidate::GetFilterNdf () const inline
Definition at line 82 of file FwdMatchCandidate.h.
View newest version in sPHENIX GitHub at line 82 of file FwdMatchCandidate.h
References mNdf.
int FwdMatchCandidate::GetMcTrackId () const inline
Definition at line 59 of file FwdMatchCandidate.h.
View newest version in sPHENIX GitHub at line 59 of file FwdMatchCandidate.h
References mMcTrackId.
Referenced by FwdMcTrackMapper::Rebuild().
const TVector3& FwdMatchCandidate::GetMomentum () const inline
Definition at line 87 of file FwdMatchCandidate.h.
View newest version in sPHENIX GitHub at line 87 of file FwdMatchCandidate.h
References mMomentum.
double FwdMatchCandidate::GetP () const inline
Definition at line 90 of file FwdMatchCandidate.h.
View newest version in sPHENIX GitHub at line 90 of file FwdMatchCandidate.h
References mMomentum.
double FwdMatchCandidate::GetSlopeX () const inline
Definition at line 88 of file FwdMatchCandidate.h.
View newest version in sPHENIX GitHub at line 88 of file FwdMatchCandidate.h
References mMomentum.
double FwdMatchCandidate::GetSlopeY () const inline
Definition at line 89 of file FwdMatchCandidate.h.
View newest version in sPHENIX GitHub at line 89 of file FwdMatchCandidate.h
References mMomentum.
double FwdMatchCandidate::GetTrackQualityParameter () const inline virtual
Implements MatchCandidate.
Definition at line 85 of file FwdMatchCandidate.h.
View newest version in sPHENIX GitHub at line 85 of file FwdMatchCandidate.h
References GetFilterChiSquareCCDF().
double FwdMatchCandidate::GetVtxCoordSigma (unsigned xy) const inline
Definition at line 79 of file FwdMatchCandidate.h.
View newest version in sPHENIX GitHub at line 79 of file FwdMatchCandidate.h
References mCoordSigma.
double FwdMatchCandidate::GetVtxSlopeSigma (unsigned xy) const inline
Definition at line 80 of file FwdMatchCandidate.h.
View newest version in sPHENIX GitHub at line 80 of file FwdMatchCandidate.h
References mSlopeSigma.
unsigned FwdMatchCandidate::GetWrongHitCount () const inline
Definition at line 61 of file FwdMatchCandidate.h.
View newest version in sPHENIX GitHub at line 61 of file FwdMatchCandidate.h
References mWrongHitCount.
double FwdMatchCandidate::GetX () const inline
Definition at line 76 of file FwdMatchCandidate.h.
View newest version in sPHENIX GitHub at line 76 of file FwdMatchCandidate.h
References mVertex.
double FwdMatchCandidate::GetY () const inline
Definition at line 77 of file FwdMatchCandidate.h.
View newest version in sPHENIX GitHub at line 77 of file FwdMatchCandidate.h
References mVertex.
double FwdMatchCandidate::GetZ () const inline
Definition at line 78 of file FwdMatchCandidate.h.
View newest version in sPHENIX GitHub at line 78 of file FwdMatchCandidate.h
References mVertex.
bool FwdMatchCandidate::IsAmbiguous () const inline
Definition at line 63 of file FwdMatchCandidate.h.
View newest version in sPHENIX GitHub at line 63 of file FwdMatchCandidate.h
References mMcTrackAssociationAmbiguous.
bool FwdMatchCandidate::IsReadyForFinalFit () const inline virtual
Implements MatchCandidate.
Definition at line 47 of file FwdMatchCandidate.h.
View newest version in sPHENIX GitHub at line 47 of file FwdMatchCandidate.h
References MatchCandidate::HasAmbiguousHits(), and mPassedKalmanFilterOnce.
void FwdMatchCandidate::SetAmbiguityFlag (bool flag) inline
Definition at line 62 of file FwdMatchCandidate.h.
View newest version in sPHENIX GitHub at line 62 of file FwdMatchCandidate.h
References mMcTrackAssociationAmbiguous.
Referenced by FwdHoughTree::FinalFit().
void FwdMatchCandidate::SetFilterChiSquare (double chiSquare, double chiSquareCCDF, unsigned ndf) inline
Definition at line 51 of file FwdMatchCandidate.h.
View newest version in sPHENIX GitHub at line 51 of file FwdMatchCandidate.h
References mFilterChiSquare, mFilterChiSquareCCDF, and mNdf.
Referenced by FwdHoughTree::FinalFit().
void FwdMatchCandidate::SetMcTrackId (int id) inline
Definition at line 58 of file FwdMatchCandidate.h.
View newest version in sPHENIX GitHub at line 58 of file FwdMatchCandidate.h
References mMcTrackId.
Referenced by FwdHoughTree::FinalFit().
void FwdMatchCandidate::SetVtxCoord (double x, double y, double z) inline
Definition at line 65 of file FwdMatchCandidate.h.
View newest version in sPHENIX GitHub at line 65 of file FwdMatchCandidate.h
References mVertex.
Referenced by FwdHoughTree::FinalFit().
void FwdMatchCandidate::SetVtxCoordSigma (double sigmaX, double sigmaY) inline
Definition at line 67 of file FwdMatchCandidate.h.
View newest version in sPHENIX GitHub at line 67 of file FwdMatchCandidate.h
References mCoordSigma.
Referenced by FwdHoughTree::FinalFit().
void FwdMatchCandidate::SetVtxMomentum (double sx, double sy, double invp)
Definition at line 14 of file FwdMatchCandidate.cxx.
View newest version in sPHENIX GitHub at line 14 of file FwdMatchCandidate.cxx
References mCharge, mMomentum, p, and printf().
Referenced by FwdHoughTree::FinalFit().
void FwdMatchCandidate::SetVtxSlopeSigma (double sigmaX, double sigmaY) inline
Definition at line 71 of file FwdMatchCandidate.h.
View newest version in sPHENIX GitHub at line 71 of file FwdMatchCandidate.h
References mSlopeSigma.
Referenced by FwdHoughTree::FinalFit().
void FwdMatchCandidate::SetWrongHitCount (unsigned count) inline
Definition at line 60 of file FwdMatchCandidate.h.
View newest version in sPHENIX GitHub at line 60 of file FwdMatchCandidate.h
References mWrongHitCount.
Referenced by FwdHoughTree::FinalFit().
void FwdMatchCandidate::ShapeItUpForInspection (const HoughTree * tree, const unsigned id[]) inline virtual
Reimplemented from MatchCandidate.
Definition at line 41 of file FwdMatchCandidate.h.
View newest version in sPHENIX GitHub at line 41 of file FwdMatchCandidate.h
References mPassedKalmanFilterOnce, and MatchCandidate::ShapeItUpForInspection().
Member Data Documentation
int FwdMatchCandidate::mCharge private
Definition at line 117 of file FwdMatchCandidate.h.
View newest version in sPHENIX GitHub at line 117 of file FwdMatchCandidate.h
Referenced by SetVtxMomentum().
double FwdMatchCandidate::mCoordSigma[2] private
Definition at line 115 of file FwdMatchCandidate.h.
View newest version in sPHENIX GitHub at line 115 of file FwdMatchCandidate.h
Referenced by FwdMatchCandidate(), GetVtxCoordSigma(), and SetVtxCoordSigma().
double FwdMatchCandidate::mFilterChiSquare private
Definition at line 97 of file FwdMatchCandidate.h.
View newest version in sPHENIX GitHub at line 97 of file FwdMatchCandidate.h
Referenced by SetFilterChiSquare().
double FwdMatchCandidate::mFilterChiSquareCCDF private
Definition at line 97 of file FwdMatchCandidate.h.
View newest version in sPHENIX GitHub at line 97 of file FwdMatchCandidate.h
Referenced by GetFilterChiSquareCCDF(), and SetFilterChiSquare().
bool FwdMatchCandidate::mMcTrackAssociationAmbiguous private
Definition at line 110 of file FwdMatchCandidate.h.
View newest version in sPHENIX GitHub at line 110 of file FwdMatchCandidate.h
Referenced by IsAmbiguous(), and SetAmbiguityFlag().
int FwdMatchCandidate::mMcTrackId private
Definition at line 100 of file FwdMatchCandidate.h.
View newest version in sPHENIX GitHub at line 100 of file FwdMatchCandidate.h
Referenced by GetMcTrackId(), and SetMcTrackId().
TVector3 FwdMatchCandidate::mMomentum private
Definition at line 113 of file FwdMatchCandidate.h.
View newest version in sPHENIX GitHub at line 113 of file FwdMatchCandidate.h
Referenced by GetMomentum(), GetP(), GetSlopeX(), GetSlopeY(), and SetVtxMomentum().
unsigned FwdMatchCandidate::mNdf private
Definition at line 91 of file FwdMatchCandidate.h.
View newest version in sPHENIX GitHub at line 91 of file FwdMatchCandidate.h
Referenced by GetFilterNdf(), and SetFilterChiSquare().
bool FwdMatchCandidate::mPassedKalmanFilterOnce private
Definition at line 120 of file FwdMatchCandidate.h.
View newest version in sPHENIX GitHub at line 120 of file FwdMatchCandidate.h
Referenced by AssertKalmanFilterPassedFlag(), IsReadyForFinalFit(), and ShapeItUpForInspection().
double FwdMatchCandidate::mSlopeSigma[2] private
Definition at line 115 of file FwdMatchCandidate.h.
View newest version in sPHENIX GitHub at line 115 of file FwdMatchCandidate.h
Referenced by FwdMatchCandidate(), GetVtxSlopeSigma(), and SetVtxSlopeSigma().
TVector3 FwdMatchCandidate::mVertex private
Definition at line 113 of file FwdMatchCandidate.h.
View newest version in sPHENIX GitHub at line 113 of file FwdMatchCandidate.h
Referenced by GetX(), GetY(), GetZ(), and SetVtxCoord().
unsigned FwdMatchCandidate::mWrongHitCount private
Definition at line 102 of file FwdMatchCandidate.h.
View newest version in sPHENIX GitHub at line 102 of file FwdMatchCandidate.h
Referenced by GetWrongHitCount(), and SetWrongHitCount().
The documentation for this class was generated from the following files:
EicRoot/blob/master/eic/htree/FwdMatchCandidate.h
EicRoot/blob/master/eic/htree/FwdMatchCandidate.cxx