EIC Software: EicKfNodeTemplateOrth3D Class Reference
EicKfNodeTemplateOrth3D Class Reference
#include <EicRoot/blob/master/eic/tracking/EicTrackingDigiHitProducer.h>
Public Member Functions
EicKfNodeTemplateOrth3D (TGeoMatrix *transformation=0)
~EicKfNodeTemplateOrth3D ()
unsigned GetMdim () const
double GetSigma (unsigned iq) const
double GetPitch (unsigned iq) const
double GetPixelCenterOffset (unsigned iq) const
void FillGranularityArray (bool useCartesian, double spGranularity, double aGranularity, double gra[]) const
double GetSmearingValue (double spSmearing, const EicTrackingDigiHit *hit, unsigned iq) const
void FillMinMaxArrays (bool useCartesian, const std::set< double > &xMin, const std::set< double > &xMax, const std::set< double > &yMin, const std::set< double > &yMax, const std::set< double > &rMin, const std::set< double > &rMax, double min[], double max[]) const
void SmearLocalCoord (TVector3 &local, EicDigiHitProducer::SmearingModel smearing_model)
void PackSmearedHit (TClonesArray *arr, const TString &detName, const EicMoCaPoint *point, unsigned kfNodeID, TVector3 &global, TVector3 &local)
KfMatrix * GetMeasurementNoise (const EicTrackingDigiHit *hit) const
Public Member Functions inherited from EicKfNodeTemplate
EicKfNodeTemplate (TGeoMatrix *node2sv=0)
~EicKfNodeTemplate ()
virtual bool CylindricalThreeDeeOnly () const
virtual bool CartesianThreeDeeOnly () const
virtual double GetSpatialSigma () const
virtual double GetAngularSigma () const
bool IsCompatible (const EicKfNodeTemplate *sample)
int IncrementLinearTrackFitMatrices (SensitiveVolume *sv, EicTrackingDigiHit *hit, double zRef, KfMatrix *A, KfMatrix *b)
virtual TVector3 TemplateToThreeDee (const double tmplCoord[]) const
virtual void ThreeDeeToTemplate (const TVector3 &crs, double tmplCoord[]) const
virtual void CartesianToCylindrical (const TVector3 &crs, double tmplCoord[]) const
Private Member Functions
void SetSigma (double sigmaX, double sigmaY, double sigmaZ)
Private Attributes
Double_t mSigma [3]
Friends
class EicTrackingDigiHitProducer
Additional Inherited Members
Protected Member Functions inherited from EicKfNodeTemplate
double GetSmearedValue (double value, unsigned iq, EicDigiHitProducer::SmearingModel smearing_model)
void StoreDigiHit (TClonesArray *arr, const TString &detName, const EicMoCaPoint *point, unsigned kfNodeID, TVector3 &global, TVector3 &local, EicDigiHitProducer::SmearingModel smearing_model)
Detailed Description
Definition at line 538 of file EicTrackingDigiHitProducer.h.
View newest version in sPHENIX GitHub at line 538 of file EicTrackingDigiHitProducer.h
Constructor & Destructor Documentation
EicKfNodeTemplateOrth3D::EicKfNodeTemplateOrth3D (TGeoMatrix * transformation = 0) inline
Definition at line 543 of file EicTrackingDigiHitProducer.h.
View newest version in sPHENIX GitHub at line 543 of file EicTrackingDigiHitProducer.h
References mSigma.
EicKfNodeTemplateOrth3D::~EicKfNodeTemplateOrth3D () inline
Definition at line 546 of file EicTrackingDigiHitProducer.h.
View newest version in sPHENIX GitHub at line 546 of file EicTrackingDigiHitProducer.h
Member Function Documentation
void EicKfNodeTemplateOrth3D::FillGranularityArray (bool useCartesian, double spGranularity, double aGranularity, double gra[]) const inline virtual
Implements EicKfNodeTemplate.
Definition at line 553 of file EicTrackingDigiHitProducer.h.
View newest version in sPHENIX GitHub at line 553 of file EicTrackingDigiHitProducer.h
void EicKfNodeTemplateOrth3D::FillMinMaxArrays (bool useCartesian, const std::set< double > & xMin, const std::set< double > & xMax, const std::set< double > & yMin, const std::set< double > & yMax, const std::set< double > & rMin, const std::set< double > & rMax, double min[], double max[]) const inline virtual
Implements EicKfNodeTemplate.
Definition at line 560 of file EicTrackingDigiHitProducer.h.
View newest version in sPHENIX GitHub at line 560 of file EicTrackingDigiHitProducer.h
unsigned EicKfNodeTemplateOrth3D::GetMdim () const inline virtual
Implements EicKfNodeTemplate.
Definition at line 548 of file EicTrackingDigiHitProducer.h.
View newest version in sPHENIX GitHub at line 548 of file EicTrackingDigiHitProducer.h
KfMatrix * EicKfNodeTemplateOrth3D::GetMeasurementNoise (const EicTrackingDigiHit * hit) const virtual
Implements EicKfNodeTemplate.
Definition at line 311 of file EicTrackingDigiHitProducer.cxx.
View newest version in sPHENIX GitHub at line 311 of file EicTrackingDigiHitProducer.cxx
References EicTrackingDigiHit::GetCovariance(), ip(), and KfMatrix::KFM().
double EicKfNodeTemplateOrth3D::GetPitch (unsigned iq) const inline virtual
Implements EicKfNodeTemplate.
Definition at line 550 of file EicTrackingDigiHitProducer.h.
View newest version in sPHENIX GitHub at line 550 of file EicTrackingDigiHitProducer.h
double EicKfNodeTemplateOrth3D::GetPixelCenterOffset (unsigned iq) const inline virtual
Implements EicKfNodeTemplate.
Definition at line 551 of file EicTrackingDigiHitProducer.h.
View newest version in sPHENIX GitHub at line 551 of file EicTrackingDigiHitProducer.h
double EicKfNodeTemplateOrth3D::GetSigma (unsigned iq) const inline virtual
Implements EicKfNodeTemplate.
Definition at line 549 of file EicTrackingDigiHitProducer.h.
View newest version in sPHENIX GitHub at line 549 of file EicTrackingDigiHitProducer.h
References mSigma.
double EicKfNodeTemplateOrth3D::GetSmearingValue (double spSmearing, const EicTrackingDigiHit * hit, unsigned iq) const inline virtual
Implements EicKfNodeTemplate.
Definition at line 557 of file EicTrackingDigiHitProducer.h.
View newest version in sPHENIX GitHub at line 557 of file EicTrackingDigiHitProducer.h
void EicKfNodeTemplateOrth3D::PackSmearedHit (TClonesArray * arr, const TString & detName, const EicMoCaPoint * point, unsigned kfNodeID, TVector3 & global, TVector3 & local) inline virtual
Implements EicKfNodeTemplate.
Definition at line 573 of file EicTrackingDigiHitProducer.h.
View newest version in sPHENIX GitHub at line 573 of file EicTrackingDigiHitProducer.h
void EicKfNodeTemplateOrth3D::SetSigma (double sigmaX, double sigmaY, double sigmaZ) inline private
Definition at line 603 of file EicTrackingDigiHitProducer.h.
View newest version in sPHENIX GitHub at line 603 of file EicTrackingDigiHitProducer.h
References mSigma.
Referenced by EicTrackingDigiHitProducer::DefineKfNodeTemplateOrth3D().
void EicKfNodeTemplateOrth3D::SmearLocalCoord (TVector3 & local, EicDigiHitProducer::SmearingModel smearing_model) inline virtual
Implements EicKfNodeTemplate.
Definition at line 570 of file EicTrackingDigiHitProducer.h.
View newest version in sPHENIX GitHub at line 570 of file EicTrackingDigiHitProducer.h
Friends And Related Function Documentation
friend class EicTrackingDigiHitProducer friend
Definition at line 540 of file EicTrackingDigiHitProducer.h.
View newest version in sPHENIX GitHub at line 540 of file EicTrackingDigiHitProducer.h
Member Data Documentation
Double_t EicKfNodeTemplateOrth3D::mSigma[3] private
Definition at line 605 of file EicTrackingDigiHitProducer.h.
View newest version in sPHENIX GitHub at line 605 of file EicTrackingDigiHitProducer.h
Referenced by EicKfNodeTemplateOrth3D(), GetSigma(), and SetSigma().
The documentation for this class was generated from the following files:
EicRoot/blob/master/eic/tracking/EicTrackingDigiHitProducer.h
EicRoot/blob/master/eic/tracking/EicTrackingDigiHitProducer.cxx