EIC Software: MediaSliceArray Class Reference
MediaSliceArray Class Reference
#include <EicRoot/blob/master/eic/htc/MediaSliceArray.h>
Public Member Functions
MediaSliceArray (MediaBank *bank, double z1, double z2)
double GetZ0 () const
double GetThickness () const
unsigned GetMediaSliceCount () const
MediaSlice * GetMediaSlice (unsigned iq)
double GetDE (t_particle_group *pgroup, int charge, double e0_kin)
Private Attributes
double mZ0
double mThickness
std::vector< MediaSlice > mMediaSlices
Detailed Description
Definition at line 17 of file MediaSliceArray.h.
View newest version in sPHENIX GitHub at line 17 of file MediaSliceArray.h
Constructor & Destructor Documentation
MediaSliceArray::MediaSliceArray (MediaBank * bank, double z1, double z2)
Definition at line 18 of file MediaSliceArray.cxx.
View newest version in sPHENIX GitHub at line 18 of file MediaSliceArray.cxx
References MediaBank::GetMediaLayer(), MediaBank::GetMediaLayerCount(), MediaLayer::GetThickness(), MediaSlice::GetThickness(), MediaLayer::GetZ0(), mMediaSlices, mThickness, mZ0, thickness, z1, and z2.
Member Function Documentation
double MediaSliceArray::GetDE (t_particle_group * pgroup, int charge, double e0_kin)
Definition at line 65 of file MediaSliceArray.cxx.
View newest version in sPHENIX GitHub at line 65 of file MediaSliceArray.cxx
References _DEDX_ELECTRON_, _DEDX_HADRON_, t_particle_group::dE_dx_model, G3DRELX, MediaLayer::GetMaterial(), MediaSlice::GetMediaLayer(), MediaSlice::GetThickness(), t_particle_group::mass, material(), and mMediaSlices.
Referenced by TrKalmanFilter::AccountIonizationLosses().
MediaSlice* MediaSliceArray::GetMediaSlice (unsigned iq) inline
Definition at line 24 of file MediaSliceArray.h.
View newest version in sPHENIX GitHub at line 24 of file MediaSliceArray.h
References mMediaSlices.
Referenced by TrKalmanNodeLocation::InitializeProcessNoiseMatrices().
unsigned MediaSliceArray::GetMediaSliceCount () const inline
Definition at line 23 of file MediaSliceArray.h.
View newest version in sPHENIX GitHub at line 23 of file MediaSliceArray.h
References mMediaSlices.
Referenced by TrKalmanNodeLocation::InitializeProcessNoiseMatrices().
double MediaSliceArray::GetThickness () const inline
Definition at line 22 of file MediaSliceArray.h.
View newest version in sPHENIX GitHub at line 22 of file MediaSliceArray.h
References mThickness.
Referenced by TrKalmanNodeLocation::InitializeProcessNoiseMatrices().
double MediaSliceArray::GetZ0 () const inline
Definition at line 21 of file MediaSliceArray.h.
View newest version in sPHENIX GitHub at line 21 of file MediaSliceArray.h
References mZ0.
Referenced by TrKalmanNodeLocation::InitializeProcessNoiseMatrices().
Member Data Documentation
std::vector<MediaSlice> MediaSliceArray::mMediaSlices private
Definition at line 34 of file MediaSliceArray.h.
View newest version in sPHENIX GitHub at line 34 of file MediaSliceArray.h
Referenced by GetDE(), GetMediaSlice(), GetMediaSliceCount(), and MediaSliceArray().
double MediaSliceArray::mThickness private
Definition at line 32 of file MediaSliceArray.h.
View newest version in sPHENIX GitHub at line 32 of file MediaSliceArray.h
Referenced by GetThickness(), and MediaSliceArray().
double MediaSliceArray::mZ0 private
Definition at line 32 of file MediaSliceArray.h.
View newest version in sPHENIX GitHub at line 32 of file MediaSliceArray.h
Referenced by GetZ0(), and MediaSliceArray().
The documentation for this class was generated from the following files:
EicRoot/blob/master/eic/htc/MediaSliceArray.h
EicRoot/blob/master/eic/htc/MediaSliceArray.cxx