EIC Software: vector3 Class Reference
vector3 Class Reference
#include <estarlight/blob/master/include/vector3.h>
Public Member Functions
vector3 ()
vector3 (const vector3 &)=default
vector3 (double *vec)
vector3 (double x, double y, double z)
virtual ~vector3 ()
const double * GetVector () const
void SetVector (double x, double y, double z)
void SetVector (double *vec)
vector3 & operator= (const vector3 &vec)
vector3 & operator+= (const vector3 &vec)
vector3 & operator-= (const vector3 &vec)
double X () const
double Y () const
double Z () const
double Mag2 () const
double Mag () const
Private Attributes
double _vec [3]
Friends
std::ostream & operator<< (std::ostream &out, const vector3 &vec)
Detailed Description
Definition at line 42 of file vector3.h.
View newest version in sPHENIX GitHub at line 42 of file vector3.h
Constructor & Destructor Documentation
vector3::vector3 ()
Definition at line 37 of file vector3.cpp.
View newest version in sPHENIX GitHub at line 37 of file vector3.cpp
References _vec.
vector3::vector3 (const vector3 &) default
vector3::vector3 (double * vec)
vector3::vector3 (double x, double y, double z)
Definition at line 45 of file vector3.cpp.
View newest version in sPHENIX GitHub at line 45 of file vector3.cpp
References _vec, x, y, and z.
vector3::~vector3 () virtual
Definition at line 53 of file vector3.cpp.
View newest version in sPHENIX GitHub at line 53 of file vector3.cpp
Member Function Documentation
const double* vector3::GetVector () const inline
Definition at line 51 of file vector3.h.
View newest version in sPHENIX GitHub at line 51 of file vector3.h
References _vec.
Referenced by lorentzVector::GetPx(), lorentzVector::GetPy(), and lorentzVector::GetPz().
double vector3::Mag () const inline
Definition at line 82 of file vector3.h.
View newest version in sPHENIX GitHub at line 82 of file vector3.h
References Mag2().
double vector3::Mag2 () const inline
Definition at line 81 of file vector3.h.
View newest version in sPHENIX GitHub at line 81 of file vector3.h
References _vec.
Referenced by lorentzVector::Boost(), lorentzVector::M2(), and Mag().
vector3& vector3::operator+= (const vector3 & vec) inline
Definition at line 64 of file vector3.h.
View newest version in sPHENIX GitHub at line 64 of file vector3.h
References _vec.
vector3& vector3::operator-= (const vector3 & vec) inline
Definition at line 70 of file vector3.h.
View newest version in sPHENIX GitHub at line 70 of file vector3.h
References _vec.
vector3& vector3::operator= (const vector3 & vec) inline
Definition at line 56 of file vector3.h.
View newest version in sPHENIX GitHub at line 56 of file vector3.h
References _vec.
void vector3::SetVector (double x, double y, double z)
Definition at line 57 of file vector3.cpp.
View newest version in sPHENIX GitHub at line 57 of file vector3.cpp
References _vec, x, y, and z.
Referenced by lorentzVector::reflect(), and lorentzVector::SetXYZT().
void vector3::SetVector (double * vec)
Definition at line 65 of file vector3.cpp.
View newest version in sPHENIX GitHub at line 65 of file vector3.cpp
References _vec.
double vector3::X (void) const inline
Definition at line 77 of file vector3.h.
View newest version in sPHENIX GitHub at line 77 of file vector3.h
References _vec.
Referenced by lorentzVector::Boost(), lorentzVector::BoostVector(), and lorentzVector::reflect().
double vector3::Y () const inline
Definition at line 78 of file vector3.h.
View newest version in sPHENIX GitHub at line 78 of file vector3.h
References _vec.
Referenced by lorentzVector::Boost(), lorentzVector::BoostVector(), and lorentzVector::reflect().
double vector3::Z () const inline
Definition at line 79 of file vector3.h.
View newest version in sPHENIX GitHub at line 79 of file vector3.h
References _vec.
Referenced by lorentzVector::Boost(), lorentzVector::BoostVector(), and lorentzVector::reflect().
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & out, const vector3 & vec) friend
Definition at line 84 of file vector3.h.
View newest version in sPHENIX GitHub at line 84 of file vector3.h
Member Data Documentation
double vector3::_vec[3] private
Definition at line 93 of file vector3.h.
View newest version in sPHENIX GitHub at line 93 of file vector3.h
Referenced by GetVector(), Mag2(), operator+=(), operator-=(), operator=(), SetVector(), vector3(), X(), Y(), and Z().
The documentation for this class was generated from the following files:
estarlight/blob/master/include/vector3.h
estarlight/blob/master/src/vector3.cpp