EIC Software: PHActsSourceLinks Class Reference
PHActsSourceLinks Class Reference
#include <fun4all_coresoftware/blob/master/offline/packages/trackreco/PHActsSourceLinks.h>
Public Member Functions
PHActsSourceLinks (const std::string &name="PHActsSourceLinks")
Default constructor.
virtual ~PHActsSourceLinks ()
Destructor.
int End (PHCompositeNode *topNode)
SubsysReco inherited functions.
int Init (PHCompositeNode *topNode)
int InitRun (PHCompositeNode *topNode)
int process_event (PHCompositeNode *topNode)
int ResetEvent (PHCompositeNode *topNode)
Clean up after each event.
void useVertexAsMeasurement (bool useVertexMeasurement)
void setMagField (const std::string &magField)
void setMagFieldRescale (double magFieldRescale)
void SetUseTruthClusters (bool setit)
Public Member Functions inherited from SubsysReco
virtual ~SubsysReco ()
virtual int EndRun (const int)
Called at the end of each run.
virtual int Reset (PHCompositeNode *)
Reset.
virtual void Print (const std::string &what="ALL") const
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Private Member Functions
void createNodes (PHCompositeNode *topNode)
Create sourceLink related nodes on tree if they don't yet exist.
int getNodes (PHCompositeNode *topNode)
Function to get necessary nodes off node tree.
TGeoNode * getNodeFromClusterMap (TrkrDefs::hitsetkey hitSetKey)
Get a TGeoNode from the m_clusterNodeMap.
Surface getSurfaceFromClusterMap (TrkrDefs::hitsetkey hitSetKey)
Get a Surface from the m_surfaceNodeMap;.
Acts::BoundMatrix getMvtxCovarLocal (const unsigned int layer, const unsigned int staveid, const unsigned int chipid, TMatrixD world_err)
Acts::BoundMatrix getInttCovarLocal (const unsigned int layer, const unsigned int ladderZId, const unsigned int ladderPhiId, TMatrixD worldErr)
TMatrixD transformCovarToLocal (const double ladderPhi, TMatrixD worldErr)
Transform the covariance to the local coordinate frame.
Surface getMvtxLocalCoords (Acts::Vector2D &local2D, Acts::BoundMatrix &localErr, const TrkrCluster *cluster, const TrkrDefs::cluskey clusKey)
Surface getInttLocalCoords (Acts::Vector2D &local2D, Acts::BoundMatrix &localErr, const TrkrCluster *cluster, const TrkrDefs::cluskey clusKey)
Same as above, except for INTT.
Surface getTpcLocalCoords (Acts::Vector2D &local2D, Acts::BoundMatrix &localErr, const TrkrCluster *cluster, const TrkrDefs::cluskey clusKey)
Same as above, except for TPC.
Surface getMmLocalCoords (Acts::Vector2D &local2D, Acts::BoundMatrix &localErr, const TrkrCluster *cluster, const TrkrDefs::cluskey clusKey)
void addVerticesAsSourceLinks (PHCompositeNode *topNode, unsigned int &hitId)
Surface getTpcSurfaceFromCoords (TrkrDefs::hitsetkey hitsetkey, std::vector< double > &world)
Surface getMmSurfaceFromCoords (TrkrDefs::hitsetkey hitsetkey, std::vector< double > &world)
Private Attributes
bool m_useVertexMeasurement = false
bool _use_truth_clusters = false
TrkrClusterContainer * m_clusterMap = nullptr
SvtxCluster node.
CluskeyBimap * m_hitIdClusKey
std::map< unsigned int,
SourceLink > * m_sourceLinks
Map for source hitid:sourcelink, to be put on node tree by this module.
std::string m_magField = "1.4"
Magnetic field components to set Acts magnetic field.
double m_magFieldRescale = -1.
PHG4CylinderGeomContainer * m_geomContainerMvtx = nullptr
Tracking geometry objects.
PHG4CylinderGeomContainer * m_geomContainerIntt = nullptr
PHG4CylinderCellGeomContainer * m_geomContainerTpc = nullptr
ActsTrackingGeometry * m_tGeometry = nullptr
ActsSurfaceMaps * m_surfMaps = nullptr
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = INT_MAX - 10
}
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Detailed Description
This class is responsible for creating Acts TrkrClusterSourceLinks from the SvtxClusters. The class creates a node of TrkrClusterSourceLinks and places it on the node tree for other Acts modules to use (e.g. for use of track propagation or track fitting). SourceLinks are created from the SvtxClusterContainer contents (SvtxClusters) and are put into a special SourceLinkContainer that is defined in TrkrClusterSourceLink.hpp
Definition at line 63 of file PHActsSourceLinks.h.
View newest version in sPHENIX GitHub at line 63 of file PHActsSourceLinks.h
Constructor & Destructor Documentation
PHActsSourceLinks::PHActsSourceLinks (const std::string & name = "PHActsSourceLinks")
Default constructor.
See header file for comments on class, functions, member variables.
Tracking includes Fun4All includes Acts includes std (and the like) includes Root includes
Definition at line 54 of file PHActsSourceLinks.cc.
View newest version in sPHENIX GitHub at line 54 of file PHActsSourceLinks.cc
References Fun4AllBase::Verbosity().
virtual PHActsSourceLinks::~PHActsSourceLinks () inline virtual
Destructor.
Definition at line 70 of file PHActsSourceLinks.h.
View newest version in sPHENIX GitHub at line 70 of file PHActsSourceLinks.h
Member Function Documentation
void PHActsSourceLinks::addVerticesAsSourceLinks (PHCompositeNode * topNode, unsigned int & hitId) private
Make a perigee surface corresponding to the vertex for the "measurement" to live on
Definition at line 820 of file PHActsSourceLinks.cc.
View newest version in sPHENIX GitHub at line 820 of file PHActsSourceLinks.cc
References SvtxVertexMap::begin(), Acts::UnitConstants::cm, Acts::UnitConstants::cm2, Acts::eBoundLoc0, Acts::eBoundLoc1, SvtxVertexMap::end(), ActsTrackingGeometry::geoContext, SvtxVertex::get_error(), SvtxVertex::get_x(), SvtxVertex::get_y(), SvtxVertex::get_z(), m_sourceLinks, m_tGeometry, phi, PHWHERE, transformCovarToLocal(), and Fun4AllBase::Verbosity().
Referenced by process_event().
void PHActsSourceLinks::createNodes (PHCompositeNode * topNode) private
Create sourceLink related nodes on tree if they don't yet exist.
Functions
Get the DST Node
Check that it is there
Get the tracking subnode
Check that it is there
See if the map is already on the node tree
If not add it
Definition at line 996 of file PHActsSourceLinks.cc.
View newest version in sPHENIX GitHub at line 996 of file PHActsSourceLinks.cc
References PHCompositeNode::addNode(), PHNodeIterator::findFirst(), m_hitIdClusKey, and m_sourceLinks.
Referenced by InitRun().
int PHActsSourceLinks::End (PHCompositeNode * topNode) virtual
SubsysReco inherited functions.
Reimplemented from SubsysReco.
Definition at line 262 of file PHActsSourceLinks.cc.
View newest version in sPHENIX GitHub at line 262 of file PHActsSourceLinks.cc
References Fun4AllReturnCodes::EVENT_OK, and Fun4AllBase::Verbosity().
Acts::BoundMatrix PHActsSourceLinks::getInttCovarLocal (const unsigned int layer, const unsigned int ladderZId, const unsigned int ladderPhiId, TMatrixD worldErr) private
Get the local covariance matrix for the Intt cluster in a form Acts can accept
Get the 2D location covariance uncertainty for the cluster (y and z)
Definition at line 1156 of file PHActsSourceLinks.cc.
View newest version in sPHENIX GitHub at line 1156 of file PHActsSourceLinks.cc
References Acts::UnitConstants::cm2, Acts::eBoundLoc0, Acts::eBoundLoc1, CylinderGeomIntt::find_segment_center(), PHG4CylinderGeomContainer::GetLayerGeom(), m_geomContainerIntt, matrix(), transformCovarToLocal(), and Fun4AllBase::Verbosity().
Referenced by getInttLocalCoords().
Surface PHActsSourceLinks::getInttLocalCoords (Acts::Vector2D & local2D, Acts::BoundMatrix & localErr, const TrkrCluster * cluster, const TrkrDefs::cluskey clusKey) private
Same as above, except for INTT.
Extract detector element IDs to access the correct Surface
Get the INTT geometry
Get the TGeoNode
Now we have the geo node, so find the corresponding Acts::Surface
Otherwise use manual calculation, same as Acts
Test that Acts surface transforms correctly back
Get the local covariance error
Definition at line 584 of file PHActsSourceLinks.cc.
View newest version in sPHENIX GitHub at line 584 of file PHActsSourceLinks.cc
References Acts::UnitConstants::cm, CylinderGeomIntt::find_segment_center(), InttDefs::genHitSetKey(), ActsTrackingGeometry::geoContext, CylinderGeomIntt::get_local_from_world_coords(), TrkrCluster::getError(), getInttCovarLocal(), InttDefs::getLadderPhiId(), InttDefs::getLadderZId(), TrkrDefs::getLayer(), PHG4CylinderGeomContainer::GetLayerGeom(), getNodeFromClusterMap(), TrkrCluster::getPosition(), getSurfaceFromClusterMap(), m_geomContainerIntt, m_tGeometry, PHWHERE, Fun4AllBase::Verbosity(), Acts::Test::world, x, analysis::y, and z.
Referenced by process_event().
Surface PHActsSourceLinks::getMmLocalCoords (Acts::Vector2D & local2D, Acts::BoundMatrix & localErr, const TrkrCluster * cluster, const TrkrDefs::cluskey clusKey) private
Extract detector element IDs to access the correct Surface
Get some geometry values (lengths in mm)
Get the surface key to find the surface from the map
Use helper function since many surfaces can exist on a given readout module
If surface can't be found (shouldn't happen) return nullptr and skip this cluster
Transformation of cluster to local surface coords Coords are r*phi relative to surface r-phi center, and z relative to surface z center lengths in mm
Otherwise use manual calculation, which is the same as Acts
Test that Acts surface transforms correctly back
Get the 2D location covariance uncertainty for the cluster (y and z)
Definition at line 422 of file PHActsSourceLinks.cc.
View newest version in sPHENIX GitHub at line 422 of file PHActsSourceLinks.cc
References Acts::UnitConstants::cm, Acts::UnitConstants::cm2, Acts::eBoundLoc0, Acts::eBoundLoc1, MicromegasDefs::genHitSetKey(), ActsTrackingGeometry::geoContext, TrkrCluster::getError(), TrkrDefs::getLayer(), getMmSurfaceFromCoords(), TrkrCluster::getPosition(), m_tGeometry, PHWHERE, PHG4InttDefs::SEGMENTATION_PHI, PHG4InttDefs::SEGMENTATION_Z, transformCovarToLocal(), Fun4AllBase::Verbosity(), Acts::Test::world, x, analysis::y, and z.
Referenced by process_event().
Surface PHActsSourceLinks::getMmSurfaceFromCoords (TrkrDefs::hitsetkey hitsetkey, std::vector< double > & world) private
Get some geometry values from the geom builder for parsing surfaces
Check if the cluster is geometrically within the surface boundaries The MMs surfaces span the entire length in z, so we don't divide by 2 in the z direction since the center of the surface is z=0
Definition at line 1224 of file PHActsSourceLinks.cc.
View newest version in sPHENIX GitHub at line 1224 of file PHActsSourceLinks.cc
References ActsTrackingGeometry::geoContext, m_surfMaps, m_tGeometry, ActsSurfaceMaps::mmSurfaceMap, and PHWHERE.
Referenced by getMmLocalCoords().
Acts::BoundMatrix PHActsSourceLinks::getMvtxCovarLocal (const unsigned int layer, const unsigned int staveid, const unsigned int chipid, TMatrixD world_err) private
Get the local covariance matrix for the Mvtx cluster in a form Acts can accept
Get the 2D location covariance uncertainty for the cluster (x and z)
Definition at line 1110 of file PHActsSourceLinks.cc.
View newest version in sPHENIX GitHub at line 1110 of file PHActsSourceLinks.cc
References Acts::UnitConstants::cm2, Acts::eBoundLoc0, Acts::eBoundLoc1, CylinderGeom_Mvtx::find_sensor_center(), CylinderGeom_Mvtx::get_stave_phi_tilt(), PHG4CylinderGeomContainer::GetLayerGeom(), m_geomContainerMvtx, matrix(), transformCovarToLocal(), and Fun4AllBase::Verbosity().
Referenced by getMvtxLocalCoords().
Surface PHActsSourceLinks::getMvtxLocalCoords (Acts::Vector2D & local2D, Acts::BoundMatrix & localErr, const TrkrCluster * cluster, const TrkrDefs::cluskey clusKey) private
Function which returns MVTX local coordinates and error, as well as corresponding surface
Extract detector element IDs to access the correct Surface
Get the Mvtx geometry
Generate the hitsetkey
Get the TGeoNode
Now we have the geo node, so find the corresponding Acts::Surface
Otherwise use our by hand calculation - they are the same as Acts
Test that Acts surface transforms correctly back
Definition at line 699 of file PHActsSourceLinks.cc.
View newest version in sPHENIX GitHub at line 699 of file PHActsSourceLinks.cc
References Acts::UnitConstants::cm, CylinderGeom_Mvtx::find_sensor_center(), MvtxDefs::genHitSetKey(), ActsTrackingGeometry::geoContext, CylinderGeom_Mvtx::get_local_from_world_coords(), MvtxDefs::getChipId(), TrkrCluster::getError(), TrkrDefs::getLayer(), PHG4CylinderGeomContainer::GetLayerGeom(), getMvtxCovarLocal(), getNodeFromClusterMap(), TrkrCluster::getPosition(), MvtxDefs::getStaveId(), getSurfaceFromClusterMap(), m_geomContainerMvtx, m_tGeometry, PHWHERE, Fun4AllBase::Verbosity(), Acts::Test::world, x, analysis::y, and z.
Referenced by process_event().
TGeoNode * PHActsSourceLinks::getNodeFromClusterMap (TrkrDefs::hitsetkey hitSetKey) private
Get a TGeoNode from the m_clusterNodeMap.
Get the TGeoNode for this hit set key
Make sure we found it
If it couldn't be found then return nullptr
Definition at line 1046 of file PHActsSourceLinks.cc.
View newest version in sPHENIX GitHub at line 1046 of file PHActsSourceLinks.cc
References m_surfMaps, ActsSurfaceMaps::tGeoNodeMap, and Fun4AllBase::Verbosity().
Referenced by getInttLocalCoords(), and getMvtxLocalCoords().
int PHActsSourceLinks::getNodes (PHCompositeNode * topNode) private
Function to get necessary nodes off node tree.
Definition at line 929 of file PHActsSourceLinks.cc.
View newest version in sPHENIX GitHub at line 929 of file PHActsSourceLinks.cc
References _use_truth_clusters, Fun4AllReturnCodes::ABORTEVENT, Fun4AllReturnCodes::EVENT_OK, findNode::getClass(), m_clusterMap, m_geomContainerIntt, m_geomContainerMvtx, m_geomContainerTpc, m_surfMaps, m_tGeometry, and PHWHERE.
Referenced by process_event().
Surface PHActsSourceLinks::getSurfaceFromClusterMap (TrkrDefs::hitsetkey hitSetKey) private
Get a Surface from the m_surfaceNodeMap;.
Check to make sure we found the surface in the map
If it doesn't exit, return nullptr
Definition at line 1077 of file PHActsSourceLinks.cc.
View newest version in sPHENIX GitHub at line 1077 of file PHActsSourceLinks.cc
References ActsTrackingGeometry::geoContext, m_surfMaps, m_tGeometry, ActsSurfaceMaps::siliconSurfaceMap, and Fun4AllBase::Verbosity().
Referenced by getInttLocalCoords(), and getMvtxLocalCoords().
Surface PHActsSourceLinks::getTpcLocalCoords (Acts::Vector2D & local2D, Acts::BoundMatrix & localErr, const TrkrCluster * cluster, const TrkrDefs::cluskey clusKey) private
Same as above, except for TPC.
Extract detector element IDs to access the correct Surface
Get some geometry values (lengths in mm)
Get the surface key to find the surface from the map
Use helper function since many surfaces can exist on a given readout module
If surface can't be found (shouldn't happen) return nullptr and skip this cluster
Transformation of cluster to local surface coords Coords are r*phi relative to surface r-phi center, and z relative to surface z center lengths in mm
Otherwise use manual calculation, which is the same as Acts
Test that Acts surface transforms correctly back
Get the 2D location covariance uncertainty for the cluster (y and z)
Definition at line 272 of file PHActsSourceLinks.cc.
View newest version in sPHENIX GitHub at line 272 of file PHActsSourceLinks.cc
References Acts::UnitConstants::cm, Acts::UnitConstants::cm2, Acts::eBoundLoc0, Acts::eBoundLoc1, TpcDefs::genHitSetKey(), ActsTrackingGeometry::geoContext, TrkrCluster::getError(), TrkrDefs::getLayer(), TrkrCluster::getPosition(), TpcDefs::getSectorId(), TpcDefs::getSide(), getTpcSurfaceFromCoords(), m_tGeometry, PHWHERE, transformCovarToLocal(), Fun4AllBase::Verbosity(), Acts::Test::world, x, analysis::y, and z.
Referenced by process_event().
Surface PHActsSourceLinks::getTpcSurfaceFromCoords (TrkrDefs::hitsetkey hitsetkey, std::vector< double > & world) private
Gets tpc surface from a cluster coordinate and hitsetkey. Necessary since there are many tpc surfaces per read out module
Definition at line 1284 of file PHActsSourceLinks.cc.
View newest version in sPHENIX GitHub at line 1284 of file PHActsSourceLinks.cc
References ActsTrackingGeometry::geoContext, m_surfMaps, m_tGeometry, PHWHERE, and ActsSurfaceMaps::tpcSurfaceMap.
Referenced by getTpcLocalCoords().
int PHActsSourceLinks::Init (PHCompositeNode *) virtual
Called during initialization. Typically this is where you can book histograms, and e.g. register them to Fun4AllServer (so they can be output to file using Fun4AllServer::dumpHistos() method).
Reimplemented from SubsysReco.
Definition at line 62 of file PHActsSourceLinks.cc.
View newest version in sPHENIX GitHub at line 62 of file PHActsSourceLinks.cc
References Fun4AllReturnCodes::EVENT_OK.
int PHActsSourceLinks::InitRun (PHCompositeNode *) virtual
Called for first event when run number is known. Typically this is where you may want to fetch data from database, because you know the run number.
Check and create nodes that this module will build
Check if Acts geometry has been built and is on the node tree
Reimplemented from SubsysReco.
Definition at line 67 of file PHActsSourceLinks.cc.
View newest version in sPHENIX GitHub at line 67 of file PHActsSourceLinks.cc
References createNodes(), Fun4AllReturnCodes::EVENT_OK, and Fun4AllBase::Verbosity().
int PHActsSourceLinks::process_event (PHCompositeNode *) virtual
Called for each event. This is where you do the real work.
Get the nodes from the node tree
Arbitrary hitId that is used to map between cluster key and an unsigned int which Acts can take
Create the clusKey hitId pair to insert into the map
Local coordinates and surface to be set by the correct tracking detector function below
Run the detector specific function for getting the local coordinates of the cluster, as well as the corresponding Acts::Surface
Make sure things returned appropriately
if we couldn't find the surface (shouldn't happen) just skip this hit
if we couldn't find the surface (shouldn't happen) just skip this hit
if we couldn't find the surface (shouldn't happen) just skip this hit
if we couldn't find the surface (shouldn't happen) just skip this hit Finished with detector specific cluster stuff We have the data needed to construct an Acts measurement
for this cluster
local and localErr contain the position and covariance matrix in local coords
Cluster positions on GeoObject/Surface
TrkrClusterSourceLink creates an Acts::FittableMeasurement
Add the sourceLink to the container
Reimplemented from SubsysReco.
Definition at line 86 of file PHActsSourceLinks.cc.
View newest version in sPHENIX GitHub at line 86 of file PHActsSourceLinks.cc
References Fun4AllReturnCodes::ABORTEVENT, addVerticesAsSourceLinks(), Acts::eBoundLoc0, Acts::eBoundLoc1, Fun4AllReturnCodes::EVENT_OK, TrkrClusterContainer::getClusters(), getInttLocalCoords(), TrkrDefs::getLayer(), getMmLocalCoords(), getMvtxLocalCoords(), getNodes(), getTpcLocalCoords(), TrkrDefs::getTrkrId(), TrkrDefs::inttId, it, m_clusterMap, m_hitIdClusKey, m_sourceLinks, m_useVertexMeasurement, TrkrDefs::micromegasId, TrkrDefs::mvtxId, PHWHERE, TrkrDefs::tpcId, and Fun4AllBase::Verbosity().
int PHActsSourceLinks::ResetEvent (PHCompositeNode *) virtual
Clean up after each event.
Clear out the maps for the next event
Reimplemented from SubsysReco.
Definition at line 251 of file PHActsSourceLinks.cc.
View newest version in sPHENIX GitHub at line 251 of file PHActsSourceLinks.cc
References Fun4AllReturnCodes::EVENT_OK, m_hitIdClusKey, and m_sourceLinks.
void PHActsSourceLinks::setMagField (const std::string & magField) inline
Definition at line 80 of file PHActsSourceLinks.h.
View newest version in sPHENIX GitHub at line 80 of file PHActsSourceLinks.h
References m_magField.
Referenced by Tracking_Reco().
void PHActsSourceLinks::setMagFieldRescale (double magFieldRescale) inline
Definition at line 82 of file PHActsSourceLinks.h.
View newest version in sPHENIX GitHub at line 82 of file PHActsSourceLinks.h
References m_magFieldRescale.
Referenced by Tracking_Reco().
void PHActsSourceLinks::SetUseTruthClusters (bool setit) inline
Definition at line 85 of file PHActsSourceLinks.h.
View newest version in sPHENIX GitHub at line 85 of file PHActsSourceLinks.h
References _use_truth_clusters.
TMatrixD PHActsSourceLinks::transformCovarToLocal (const double ladderPhi, TMatrixD worldErr) private
Transform the covariance to the local coordinate frame.
Definition at line 1196 of file PHActsSourceLinks.cc.
View newest version in sPHENIX GitHub at line 1196 of file PHActsSourceLinks.cc
References cos().
Referenced by addVerticesAsSourceLinks(), getInttCovarLocal(), getMmLocalCoords(), getMvtxCovarLocal(), and getTpcLocalCoords().
void PHActsSourceLinks::useVertexAsMeasurement (bool useVertexMeasurement) inline
Definition at line 78 of file PHActsSourceLinks.h.
View newest version in sPHENIX GitHub at line 78 of file PHActsSourceLinks.h
References m_useVertexMeasurement.
Member Data Documentation
bool PHActsSourceLinks::_use_truth_clusters = false private
Definition at line 161 of file PHActsSourceLinks.h.
View newest version in sPHENIX GitHub at line 161 of file PHActsSourceLinks.h
Referenced by getNodes(), and SetUseTruthClusters().
TrkrClusterContainer* PHActsSourceLinks::m_clusterMap = nullptr private
SvtxCluster node.
Definition at line 164 of file PHActsSourceLinks.h.
View newest version in sPHENIX GitHub at line 164 of file PHActsSourceLinks.h
Referenced by getNodes(), and process_event().
PHG4CylinderGeomContainer* PHActsSourceLinks::m_geomContainerIntt = nullptr private
Definition at line 179 of file PHActsSourceLinks.h.
View newest version in sPHENIX GitHub at line 179 of file PHActsSourceLinks.h
Referenced by getInttCovarLocal(), getInttLocalCoords(), and getNodes().
PHG4CylinderGeomContainer* PHActsSourceLinks::m_geomContainerMvtx = nullptr private
Tracking geometry objects.
Definition at line 178 of file PHActsSourceLinks.h.
View newest version in sPHENIX GitHub at line 178 of file PHActsSourceLinks.h
Referenced by getMvtxCovarLocal(), getMvtxLocalCoords(), and getNodes().
PHG4CylinderCellGeomContainer* PHActsSourceLinks::m_geomContainerTpc = nullptr private
Definition at line 180 of file PHActsSourceLinks.h.
View newest version in sPHENIX GitHub at line 180 of file PHActsSourceLinks.h
Referenced by getNodes().
CluskeyBimap* PHActsSourceLinks::m_hitIdClusKey private
Map relating arbitrary hitid to TrkrDef::cluskey for SourceLink, to be put on node tree by this module
Definition at line 168 of file PHActsSourceLinks.h.
View newest version in sPHENIX GitHub at line 168 of file PHActsSourceLinks.h
Referenced by createNodes(), process_event(), and ResetEvent().
std::string PHActsSourceLinks::m_magField = "1.4" private
Magnetic field components to set Acts magnetic field.
Definition at line 174 of file PHActsSourceLinks.h.
View newest version in sPHENIX GitHub at line 174 of file PHActsSourceLinks.h
Referenced by setMagField().
double PHActsSourceLinks::m_magFieldRescale = -1. private
Definition at line 175 of file PHActsSourceLinks.h.
View newest version in sPHENIX GitHub at line 175 of file PHActsSourceLinks.h
Referenced by setMagFieldRescale().
std::map<unsigned int, SourceLink>* PHActsSourceLinks::m_sourceLinks private
Map for source hitid:sourcelink, to be put on node tree by this module.
Definition at line 171 of file PHActsSourceLinks.h.
View newest version in sPHENIX GitHub at line 171 of file PHActsSourceLinks.h
Referenced by addVerticesAsSourceLinks(), createNodes(), process_event(), and ResetEvent().
ActsSurfaceMaps* PHActsSourceLinks::m_surfMaps = nullptr private
Definition at line 183 of file PHActsSourceLinks.h.
View newest version in sPHENIX GitHub at line 183 of file PHActsSourceLinks.h
Referenced by getMmSurfaceFromCoords(), getNodeFromClusterMap(), getNodes(), getSurfaceFromClusterMap(), and getTpcSurfaceFromCoords().
ActsTrackingGeometry* PHActsSourceLinks::m_tGeometry = nullptr private
Definition at line 182 of file PHActsSourceLinks.h.
View newest version in sPHENIX GitHub at line 182 of file PHActsSourceLinks.h
Referenced by addVerticesAsSourceLinks(), getInttLocalCoords(), getMmLocalCoords(), getMmSurfaceFromCoords(), getMvtxLocalCoords(), getNodes(), getSurfaceFromClusterMap(), getTpcLocalCoords(), and getTpcSurfaceFromCoords().
bool PHActsSourceLinks::m_useVertexMeasurement = false private
Member variables
Definition at line 160 of file PHActsSourceLinks.h.
View newest version in sPHENIX GitHub at line 160 of file PHActsSourceLinks.h
Referenced by process_event(), and useVertexAsMeasurement().
The documentation for this class was generated from the following files:
fun4all_coresoftware/blob/master/offline/packages/trackreco/PHActsSourceLinks.h
fun4all_coresoftware/blob/master/offline/packages/trackreco/PHActsSourceLinks.cc