EIC Software: EicRunAna Class Reference
EicRunAna Class Reference
#include <EicRoot/blob/master/eic/base/EicRunAna.h>
Public Member Functions
EicRunAna ()
~EicRunAna ()
void SetSeed (unsigned seed)
void SetInputFile (TString fname)
const TString & GetInputFileName () const
int AddFriend (const char *fName)
void Init ()
void Run (Int_t NStart=0, Int_t NStop=0)
void RunCoreStart (Int_t NStart=0, Int_t NStop=0)
bool RunCoreImportNextEvent (void)
void RunCoreProcessNextEvent (void)
void RunCoreFinish (void)
const std::vector< TString > & GetFriendFiles ()
Public Member Functions inherited from FairRunAna
virtual ~FairRunAna ()
FairRunAna ()
FairRunAna (const char *type, const char *proofName="")
void AddFriend (TString fName)
void Run (Double_t delta_t)
void Run (Long64_t entry)
void RunOneEvent (Long64_t entry)
void RunMixed (Int_t NStart, Int_t NStop)
void RunTSBuffers ()
void DummyRun (Int_t NStart, Int_t NStop)
void RunOnProof (Int_t NStart, Int_t NStop)
void RunOnLmdFiles (UInt_t NStart=0, UInt_t NStop=0)
void TerminateRun ()
void SetSignalFile (TString name, UInt_t identifier)
void SetBackgroundFile (TString name)
void AddBackgroundFile (TString name)
void AddSignalFile (TString name, UInt_t identifier)
void AddFile (TString name)
void Reinit (UInt_t runId)
UInt_t getRunId ()
FairField * GetField ()
void SetField (FairField *ffield)
void SetGeomFile (const char *GeoFileName)
TFile * GetGeoFile ()
void InitContainers ()
void SetInTree (TTree *tempTree)
void SetContainerStatic (Bool_t tempBool=kTRUE)
Bool_t GetContainerStatic ()
void RunWithTimeStamps ()
Bool_t IsTimeStamp ()
void CompressData ()
void SetEventTimeInterval (Double_t min, Double_t max)
void SetEventMeanTime (Double_t mean)
void BGWindowWidthNo (UInt_t background, UInt_t Signalid)
void BGWindowWidthTime (Double_t background, UInt_t Signalid)
TProof * GetProof ()
void SetRunOnProofWorker (Bool_t tb=kTRUE)
void SetProofParName (TString parName)
void SetOutputDirectory (TString dirName)
void SetProofOutputStatus (TString outStat)
void StopProcessingLMD (void)
Bool_t GetLMDProcessingStatus (void)
Public Member Functions inherited from FairRun
FairRun ()
virtual ~FairRun ()
virtual void AddTask (FairTask *t)
virtual void SetTask (FairTask *t)
virtual void SetOutputFile (const char *fname)
void SetOutputFile (TFile *f)
void SetEventHeader (FairEventHeader *EvHeader)
FairRuntimeDb * GetRuntimeDb (void)
TFile * GetOutputFile ()
Int_t GetRunId ()
FairEventHeader * GetEventHeader ()
Bool_t IsAna ()
FairTask * GetTask (const char *taskName)
FairTask * GetMainTask ()
Int_t GetNTasks ()
void CreateGeometryFile (const char *geofile)
void SetWriteRunInfoFile (Bool_t write)
Bool_t GetWriteRunInfoFile ()
virtual bool JanaLoopPossible (void) const
int GetCurrentEventIndex (void) const
Static Public Member Functions
static EicRunAna * Instance ()
Static Public Member Functions inherited from FairRunAna
static FairRunAna * Instance ()
Static Public Member Functions inherited from FairRun
static FairRun * Instance ()
static void JanaPluginMode (bool what)
static bool JanaPluginMode (void)
Private Attributes
TString mInputFileName
singelton instance
Bool_t mInitCallHappened
UInt_t mSeed
std::vector< TString > mFriendFiles
unsigned mEvStart
unsigned mEvEnd
Static Private Attributes
static EicRunAna * mInstance = 0
Additional Inherited Members
Protected Attributes inherited from FairRunAna
FairRunInfo fRunInfo
Bool_t fIsInitialized
TFile * fInputGeoFile
Bool_t fLoadGeo
FairEventHeader * fEvtHeader
FairMCEventHeader * fMCHeader
Bool_t fStatic
FairField * fField
Bool_t fTimeStamps
Bool_t fInFileIsOpen
Bool_t fMixedInput
Double_t fEventTimeMin
Double_t fEventTimeMax
Double_t fEventTime
Double_t fEventMeanTime
TF1 * fTimeProb
TProof * fProof
Bool_t fProofAnalysis
Bool_t fRunOnProofWorker
TString fProofServerName
TString fProofParName
TString fOutputDirectory
TString fProofOutputStatus
Bool_t fFinishProcessingLMDFile
Static Protected Attributes inherited from FairRunAna
static FairRunAna * fgRinstance = 0
Detailed Description
Definition at line 17 of file EicRunAna.h.
View newest version in sPHENIX GitHub at line 17 of file EicRunAna.h
Constructor & Destructor Documentation
EicRunAna::EicRunAna ()
Definition at line 22 of file EicRunAna.cxx.
View newest version in sPHENIX GitHub at line 22 of file EicRunAna.cxx
References mInstance.
EicRunAna::~EicRunAna () inline
Definition at line 21 of file EicRunAna.h.
View newest version in sPHENIX GitHub at line 21 of file EicRunAna.h
Member Function Documentation
int EicRunAna::AddFriend (const char * fName) inline
Definition at line 31 of file EicRunAna.h.
View newest version in sPHENIX GitHub at line 31 of file EicRunAna.h
References FairRunAna::AddFriend(), and mFriendFiles.
Referenced by reconstruction().
const std::vector<TString>& EicRunAna::GetFriendFiles () inline
Definition at line 51 of file EicRunAna.h.
View newest version in sPHENIX GitHub at line 51 of file EicRunAna.h
Referenced by EicCalorimeterReconstruction::Init(), and EicHtcTask::Init().
const TString& EicRunAna::GetInputFileName () const inline
Definition at line 29 of file EicRunAna.h.
View newest version in sPHENIX GitHub at line 29 of file EicRunAna.h
References mInputFileName.
Referenced by EicCalorimeterReconstruction::Init().
void EicRunAna::Init () virtual
initialize the run manager
Set the IO Manager to run with time stamps
Reimplemented from FairRunAna.
Definition at line 44 of file EicRunAna.cxx.
View newest version in sPHENIX GitHub at line 44 of file EicRunAna.cxx
References FairRun::GetRuntimeDb(), FairRunAna::Init(), mInitCallHappened, mInputFileName, FairParRootFileIo::open(), and FairRuntimeDb::setFirstInput().
Referenced by EicEventManager::Init(), and RunCoreStart().
static EicRunAna* EicRunAna::Instance () inline static
Definition at line 24 of file EicRunAna.h.
View newest version in sPHENIX GitHub at line 24 of file EicRunAna.h
References mInstance.
Referenced by EicTrackingDigiHitProducer::EicTrackingDigiHitProducer(), EicCalorimeterReconstruction::Init(), and EicHtcTask::Init().
void EicRunAna::Run (Int_t NStart = 0, Int_t NStop = 0) virtual
Run from event number NStart to event number NStop
if we have simulation files then they have MC Event Header and the Run Id is in it, any way it would be better to make FairMCEventHeader a subclass of FairEvtHeader.
Reimplemented from FairRunAna.
Definition at line 59 of file EicRunAna.cxx.
View newest version in sPHENIX GitHub at line 59 of file EicRunAna.cxx
References exit(), FairRun::mJanaPluginMode, RunCoreFinish(), RunCoreImportNextEvent(), RunCoreProcessNextEvent(), and RunCoreStart().
Referenced by digitization(), and reconstruction().
void EicRunAna::RunCoreFinish (void) virtual
Reimplemented from FairRun.
Definition at line 192 of file EicRunAna.cxx.
View newest version in sPHENIX GitHub at line 192 of file EicRunAna.cxx
References _GPHYSI_DAT_, FairTask::FinishTask(), FairRun::fRootManager, FairRunAna::fRunInfo, FairRun::fTask, FairRun::fWriteRunInfo, FairRootManager::LastFill(), FairRootManager::StoreAllWriteoutBufferData(), FairRootManager::Write(), and FairRunInfo::WriteInfo().
Referenced by Run().
bool EicRunAna::RunCoreImportNextEvent (void) virtual
Reimplemented from FairRun.
Definition at line 143 of file EicRunAna.cxx.
View newest version in sPHENIX GitHub at line 143 of file EicRunAna.cxx
References FairRun::fRootManager, FairRun::mEvCurrent, mEvEnd, and FairRootManager::ReadEvent().
Referenced by Run().
void EicRunAna::RunCoreProcessNextEvent (void) virtual
if we have simulation files then they have MC Event Header and the Run Id is in it, any way it would be better to make FairMCEventHeader a subclass of FairEvtHeader.
Reimplemented from FairRun.
Definition at line 152 of file EicRunAna.cxx.
View newest version in sPHENIX GitHub at line 152 of file EicRunAna.cxx
References FairRootManager::DeleteOldWriteoutBufferData(), FairRunAna::fEvtHeader, FairRootManager::Fill(), FairTask::FinishEvent(), FairRunAna::fMCHeader, FairRun::fRootManager, FairRun::fRunId, FairRunAna::fRunInfo, FairRunAna::fStatic, FairRun::fTask, FairRootManager::GetEventTime(), FairEventHeader::GetRunId(), FairMCEventHeader::GetRunID(), FairTrajFilter::Instance(), FairRootManager::IsEvtHeaderNew(), FairRunAna::Reinit(), FairTask::ReInitTask(), FairTrajFilter::Reset(), FairRunInfo::StoreInfo(), and FairRootManager::StoreWriteoutBufferData().
Referenced by Run().
void EicRunAna::RunCoreStart (Int_t NStart = 0, Int_t NStop = 0) virtual
Reimplemented from FairRun.
Definition at line 86 of file EicRunAna.cxx.
View newest version in sPHENIX GitHub at line 86 of file EicRunAna.cxx
References FairRunAna::fInFileIsOpen, FairRunAna::fMixedInput, FairRunAna::fProofAnalysis, FairRun::fRootManager, FairRunAna::fRunInfo, FairRunAna::fTimeStamps, FairRootManager::GetInChain(), Init(), FairRun::mEvCurrent, mEvEnd, mEvStart, mInitCallHappened, mSeed, and FairRunInfo::Reset().
Referenced by Run().
void EicRunAna::SetInputFile (TString fname) virtual
Set the input file by name
Reimplemented from FairRunAna.
Definition at line 35 of file EicRunAna.cxx.
View newest version in sPHENIX GitHub at line 35 of file EicRunAna.cxx
References mInputFileName, and FairRunAna::SetInputFile().
Referenced by digitization(), and reconstruction().
void EicRunAna::SetSeed (unsigned seed) inline
Definition at line 26 of file EicRunAna.h.
View newest version in sPHENIX GitHub at line 26 of file EicRunAna.h
References mSeed.
Referenced by digitization(), and reconstruction().
Member Data Documentation
unsigned EicRunAna::mEvEnd private
Definition at line 73 of file EicRunAna.h.
View newest version in sPHENIX GitHub at line 73 of file EicRunAna.h
Referenced by RunCoreImportNextEvent(), and RunCoreStart().
unsigned EicRunAna::mEvStart private
Definition at line 73 of file EicRunAna.h.
View newest version in sPHENIX GitHub at line 73 of file EicRunAna.h
Referenced by RunCoreStart().
std::vector<TString> EicRunAna::mFriendFiles private
Definition at line 71 of file EicRunAna.h.
View newest version in sPHENIX GitHub at line 71 of file EicRunAna.h
Referenced by AddFriend().
Bool_t EicRunAna::mInitCallHappened private
Definition at line 61 of file EicRunAna.h.
View newest version in sPHENIX GitHub at line 61 of file EicRunAna.h
Referenced by Init(), and RunCoreStart().
TString EicRunAna::mInputFileName private
singelton instance
Definition at line 59 of file EicRunAna.h.
View newest version in sPHENIX GitHub at line 59 of file EicRunAna.h
Referenced by GetInputFileName(), Init(), and SetInputFile().
EicRunAna * EicRunAna::mInstance = 0 static private
Definition at line 51 of file EicRunAna.h.
View newest version in sPHENIX GitHub at line 51 of file EicRunAna.h
Referenced by EicRunAna(), and Instance().
UInt_t EicRunAna::mSeed private
Definition at line 67 of file EicRunAna.h.
View newest version in sPHENIX GitHub at line 67 of file EicRunAna.h
Referenced by RunCoreStart(), and SetSeed().
The documentation for this class was generated from the following files:
EicRoot/blob/master/eic/base/EicRunAna.h
EicRoot/blob/master/eic/base/EicRunAna.cxx