EIC Software: B0TrackFastSim Class Reference
B0TrackFastSim Class Reference
#include <fun4all_eicdetectors/blob/master/simulation/g4simulation/g4b0/B0TrackFastSim.h>
Public Types
enum DETECTOR_TYPE { Vertical_Plane = 0, Cylinder = 1 }
Public Member Functions
B0TrackFastSim (const std::string &name="B0TrackFastSim")
Default constructor.
~B0TrackFastSim () override
dtor
int InitRun (PHCompositeNode *) override
Initialization Run, called for initialization of a run.
int process_event (PHCompositeNode *) override
Process Event, called for each event.
int End (PHCompositeNode *) override
End, write and close files.
bool is_do_evt_display () const
void set_do_evt_display (bool doEvtDisplay)
const std::string & get_fit_alg_name () const
void set_fit_alg_name (const std::string &fitAlgName)
const std::vector< std::string > & get_phg4hits_names () const
void add_phg4hits (const std::string &phg4hitsNames, const DETECTOR_TYPE phg4dettype, const float radres, const float phires, const float lonres, const float eff, const float noise)
void add_state_name (const std::string &stateName)
void add_zplane_state (const std::string &stateName, const double zplane)
void add_cylinder_state (const std::string &stateName, const double radius)
const std::string & get_trackmap_out_name () const
void set_trackmap_out_name (const std::string &trackmapOutName)
const std::string & get_sub_top_node_name () const
void set_sub_top_node_name (const std::string &subTopNodeName)
bool is_use_vertex_in_fitting () const
void set_use_vertex_in_fitting (bool useVertexInFitting)
double get_vertex_xy_resolution () const
void set_vertex_xy_resolution (double vertexXyResolution)
double get_vertex_z_resolution () const
void set_vertex_z_resolution (double vertexZResolution)
int get_primary_assumption_pid () const
void set_primary_assumption_pid (int primaryAssumptionPid)
void set_primary_tracking (int pTrk)
const std::string & get_vertexing_method () const
https://rave.hepforge.org/trac/wiki/RaveMethods
void set_vertexing_method (const std::string &vertexingMethod)
https://rave.hepforge.org/trac/wiki/RaveMethods
double get_vertex_min_ndf () const
void set_vertex_min_ndf (double vertexMinNdf)
void enable_vertexing (const bool &b=true)
void DisplayEvent () const
void Smearing (const bool b)
Public Member Functions inherited from SubsysReco
~SubsysReco () override
virtual int EndRun (const int)
Called at the end of each run.
virtual int Init (PHCompositeNode *)
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
void Print (const std::string &="ALL") const override
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Protected Attributes
gsl_rng * m_RandomGenerator
random generator that conform with sPHENIX standard
PHGenFit::Fitter * m_Fitter
genfit::GFRaveVertexFactory * m_RaveVertexFactory
PHG4TruthInfoContainer * m_TruthContainer
Input Node pointers.
SvtxTrackMap * m_SvtxTrackMapOut
SvtxVertexMap * m_SvtxVertexMap
std::vector< PHG4HitContainer * > m_PHG4HitContainer
std::vector< std::string > m_PHG4HitsNames
std::vector< DETECTOR_TYPE > m_phg4_detector_type
std::vector< float > m_phg4_detector_radres
std::vector< float > m_phg4_detector_phires
std::vector< float > m_phg4_detector_lonres
std::vector< float > m_phg4_detector_hitfindeff
std::vector< float > m_phg4_detector_noise
std::map< std::string,
std::pair< int, double > > m_ProjectionsMap
std::string m_SubTopnodeName
std::string m_TrackmapOutNodeName
std::string m_VertexingMethod
https://rave.hepforge.org/trac/wiki/RaveMethods
std::string m_FitAlgoName
double m_VertexMinNdf
double m_VertexXYResolution
double m_VertexZResolution
int m_EventCnt
Event counter.
int m_PrimaryAssumptionPid
bool m_SmearingFlag
bool m_DoEvtDisplayFlag
bool m_UseVertexInFittingFlag
int m_PrimaryTrackingFlag
bool m_DoVertexingFlag
PHParameters * m_Parameter = nullptr
Static Protected Attributes
static const std::set
< std::string > reserved_cylinder_projection_names {}
static const std::set
< std::string > reserved_zplane_projection_names {"B0ECAL"}
Private Types
typedef std::map< const
genfit::Track *, unsigned int > GenFitTrackMap
Private Member Functions
int CreateNodes (PHCompositeNode *)
int GetNodes (PHCompositeNode *)
int PseudoPatternRecognition (const PHG4Particle *particle, std::vector< PHGenFit::Measurement * > &meas_out, SvtxTrack *track_out, TVector3 &seed_pos, TVector3 &seed_mom, TMatrixDSym &seed_cov, const bool do_smearing=true)
PHGenFit::PlanarMeasurement * PHG4HitToMeasurementVerticalPlane (const PHG4Hit *g4hit, const double phi_resolution, const double r_resolution)
PHGenFit::PlanarMeasurement * PHG4HitToMeasurementCylinder (const PHG4Hit *g4hit, const double phi_resolution, const double z_resolution)
PHGenFit::Measurement * VertexMeasurement (const TVector3 &vtx, double dxy, double dz)
bool MakeSvtxTrack (SvtxTrack *track_out, const PHGenFit::Track *phgf_track_in, const unsigned int truth_track_id=UINT_MAX, const unsigned int nmeas=0, const TVector3 &vtx=TVector3(0.0, 0.0, 0.0))
bool FillSvtxVertexMap (const std::vector< genfit::GFRaveVertex * > &rave_vertices, const GenFitTrackMap &gf_tracks)
Additional Inherited Members
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Detailed Description
Definition at line 59 of file B0TrackFastSim.h.
View newest version in sPHENIX GitHub at line 59 of file B0TrackFastSim.h
Member Typedef Documentation
typedef std::map<const genfit::Track*, unsigned int> B0TrackFastSim::GenFitTrackMap private
Definition at line 240 of file B0TrackFastSim.h.
View newest version in sPHENIX GitHub at line 240 of file B0TrackFastSim.h
Member Enumeration Documentation
enum B0TrackFastSim::DETECTOR_TYPE
Enumerator:
Vertical_Plane
Cylinder
Definition at line 62 of file B0TrackFastSim.h.
View newest version in sPHENIX GitHub at line 62 of file B0TrackFastSim.h
Constructor & Destructor Documentation
B0TrackFastSim::B0TrackFastSim (const std::string & name = "B0TrackFastSim") explicit
Default constructor.
Definition at line 102 of file B0TrackFastSim.cc.
View newest version in sPHENIX GitHub at line 102 of file B0TrackFastSim.cc
References m_Parameter, m_RandomGenerator, and Fun4AllBase::Name().
B0TrackFastSim::~B0TrackFastSim () override
dtor
Definition at line 131 of file B0TrackFastSim.cc.
View newest version in sPHENIX GitHub at line 131 of file B0TrackFastSim.cc
References m_Fitter, m_RandomGenerator, and m_RaveVertexFactory.
Member Function Documentation
void B0TrackFastSim::add_cylinder_state (const std::string & stateName, const double radius)
Definition at line 1119 of file B0TrackFastSim.cc.
View newest version in sPHENIX GitHub at line 1119 of file B0TrackFastSim.cc
References m_ProjectionsMap, PHWHERE, reserved_cylinder_projection_names, and reserved_zplane_projection_names.
void B0TrackFastSim::add_phg4hits (const std::string & phg4hitsNames, const DETECTOR_TYPE phg4dettype, const float radres, const float phires, const float lonres, const float eff, const float noise) inline
adding hits from a PHG4Hit node, which usually belong to one detector or a sub group of detectors Orders of adding detectors do not matter as the hits are internally assembled in the time order
Parameters
[in] phg4hitsNames node name such as "G4HIT_SVTX"
[in] PHG4TrackFastSim::Vertical_Plane or PHG4TrackFastSim::Cylinder
[in] radres radial resolution [cm], not used for PHG4TrackFastSim::Cylinder
[in] phires azimuthal resolution [cm]
[in] lonres z-resolution [cm], not used for PHG4TrackFastSim::Vertical_Plane
[in] eff Efficiency [0-1] for a existing hit to be included in the tracking
[in] noise Noise hit propability [0-1]
Definition at line 117 of file B0TrackFastSim.h.
View newest version in sPHENIX GitHub at line 117 of file B0TrackFastSim.h
References m_phg4_detector_hitfindeff, m_phg4_detector_lonres, m_phg4_detector_noise, m_phg4_detector_phires, m_phg4_detector_radres, m_phg4_detector_type, and m_PHG4HitsNames.
void B0TrackFastSim::add_state_name (const std::string & stateName)
Definition at line 1088 of file B0TrackFastSim.cc.
View newest version in sPHENIX GitHub at line 1088 of file B0TrackFastSim.cc
References m_ProjectionsMap, PHWHERE, reserved_cylinder_projection_names, and reserved_zplane_projection_names.
void B0TrackFastSim::add_zplane_state (const std::string & stateName, const double zplane)
Definition at line 1136 of file B0TrackFastSim.cc.
View newest version in sPHENIX GitHub at line 1136 of file B0TrackFastSim.cc
References m_ProjectionsMap, PHWHERE, reserved_cylinder_projection_names, and reserved_zplane_projection_names.
int B0TrackFastSim::CreateNodes (PHCompositeNode * topNode) private
Create needed nodes.
Definition at line 546 of file B0TrackFastSim.cc.
View newest version in sPHENIX GitHub at line 546 of file B0TrackFastSim.cc
References Fun4AllReturnCodes::ABORTEVENT, PHCompositeNode::addNode(), Fun4AllReturnCodes::EVENT_OK, PHNodeIterator::findFirst(), m_SubTopnodeName, m_SvtxTrackMapOut, m_SvtxVertexMap, m_TrackmapOutNodeName, PHWHERE, and Fun4AllBase::Verbosity().
Referenced by InitRun().
void B0TrackFastSim::DisplayEvent () const
Definition at line 1079 of file B0TrackFastSim.cc.
View newest version in sPHENIX GitHub at line 1079 of file B0TrackFastSim.cc
References PHGenFit::Fitter::displayEvent(), m_DoEvtDisplayFlag, and m_Fitter.
void B0TrackFastSim::enable_vertexing (const bool & b = true) inline
Definition at line 230 of file B0TrackFastSim.h.
View newest version in sPHENIX GitHub at line 230 of file B0TrackFastSim.h
References m_DoVertexingFlag.
int B0TrackFastSim::End (PHCompositeNode *) override virtual
End, write and close files.
Reimplemented from SubsysReco.
Definition at line 233 of file B0TrackFastSim.cc.
View newest version in sPHENIX GitHub at line 233 of file B0TrackFastSim.cc
References PHGenFit::Fitter::displayEvent(), Fun4AllReturnCodes::EVENT_OK, m_DoEvtDisplayFlag, and m_Fitter.
bool B0TrackFastSim::FillSvtxVertexMap (const std::vector< genfit::GFRaveVertex * > & rave_vertices, const GenFitTrackMap & gf_tracks) private
Definition at line 488 of file B0TrackFastSim.cc.
View newest version in sPHENIX GitHub at line 488 of file B0TrackFastSim.cc
References SvtxVertexMap::insert_clone(), LogError, m_SvtxVertexMap, and PHWHERE.
Referenced by process_event().
const std::string& B0TrackFastSim::get_fit_alg_name () const inline
Definition at line 93 of file B0TrackFastSim.h.
View newest version in sPHENIX GitHub at line 93 of file B0TrackFastSim.h
References m_FitAlgoName.
const std::vector<std::string>& B0TrackFastSim::get_phg4hits_names () const inline
Definition at line 103 of file B0TrackFastSim.h.
View newest version in sPHENIX GitHub at line 103 of file B0TrackFastSim.h
References m_PHG4HitsNames.
int B0TrackFastSim::get_primary_assumption_pid () const inline
Definition at line 193 of file B0TrackFastSim.h.
View newest version in sPHENIX GitHub at line 193 of file B0TrackFastSim.h
References m_PrimaryAssumptionPid.
const std::string& B0TrackFastSim::get_sub_top_node_name () const inline
Definition at line 153 of file B0TrackFastSim.h.
View newest version in sPHENIX GitHub at line 153 of file B0TrackFastSim.h
References m_SubTopnodeName.
const std::string& B0TrackFastSim::get_trackmap_out_name () const inline
Definition at line 143 of file B0TrackFastSim.h.
View newest version in sPHENIX GitHub at line 143 of file B0TrackFastSim.h
References m_TrackmapOutNodeName.
double B0TrackFastSim::get_vertex_min_ndf () const inline
Definition at line 220 of file B0TrackFastSim.h.
View newest version in sPHENIX GitHub at line 220 of file B0TrackFastSim.h
References m_VertexMinNdf.
double B0TrackFastSim::get_vertex_xy_resolution () const inline
Definition at line 173 of file B0TrackFastSim.h.
View newest version in sPHENIX GitHub at line 173 of file B0TrackFastSim.h
References m_VertexXYResolution.
double B0TrackFastSim::get_vertex_z_resolution () const inline
Definition at line 183 of file B0TrackFastSim.h.
View newest version in sPHENIX GitHub at line 183 of file B0TrackFastSim.h
References m_VertexZResolution.
const std::string& B0TrackFastSim::get_vertexing_method () const inline
https://rave.hepforge.org/trac/wiki/RaveMethods
Definition at line 209 of file B0TrackFastSim.h.
View newest version in sPHENIX GitHub at line 209 of file B0TrackFastSim.h
References m_VertexingMethod.
int B0TrackFastSim::GetNodes (PHCompositeNode * topNode) private
Get all the all the required nodes off the node tree.
Definition at line 608 of file B0TrackFastSim.cc.
View newest version in sPHENIX GitHub at line 608 of file B0TrackFastSim.cc
References Fun4AllReturnCodes::ABORTEVENT, Fun4AllReturnCodes::EVENT_OK, PHNodeIterator::findFirst(), PHG4HitContainer::GetID(), PHObject::identify(), m_EventCnt, m_FitAlgoName, m_Parameter, m_phg4_detector_hitfindeff, m_phg4_detector_lonres, m_phg4_detector_noise, m_phg4_detector_phires, m_phg4_detector_radres, m_phg4_detector_type, m_PHG4HitContainer, m_PHG4HitsNames, m_SubTopnodeName, m_SvtxTrackMapOut, m_TrackmapOutNodeName, m_TruthContainer, m_VertexingMethod, Fun4AllBase::Name(), PHWHERE, PHParameters::SaveToNodeTree(), PHParameters::set_int_param(), PHParameters::set_string_param(), and Fun4AllBase::Verbosity().
Referenced by InitRun().
int B0TrackFastSim::InitRun (PHCompositeNode * topNode) override virtual
Initialization Run, called for initialization of a run.
Reimplemented from SubsysReco.
Definition at line 138 of file B0TrackFastSim.cc.
View newest version in sPHENIX GitHub at line 138 of file B0TrackFastSim.cc
References Fun4AllReturnCodes::ABORTEVENT, Fun4AllReturnCodes::ABORTRUN, CreateNodes(), Fun4AllReturnCodes::EVENT_OK, RawTowerGeom::get_center_x(), RawTowerGeom::get_center_y(), RawTowerGeom::get_center_z(), RawTowerGeomContainer::get_radius(), RawTowerGeomContainer::get_tower_geometries(), PHFieldUtility::GetFieldMapNode(), PHGenFit::Fitter::getInstance(), GetNodes(), PHGeomUtility::GetTGeoManager(), m_DoEvtDisplayFlag, m_DoVertexingFlag, m_EventCnt, m_FitAlgoName, m_Fitter, m_ProjectionsMap, m_RaveVertexFactory, m_VertexingMethod, PHWHERE, PHGenFit::Fitter::set_verbosity(), genfit::GFRaveVertexFactory::setMethod(), and Fun4AllBase::Verbosity().
bool B0TrackFastSim::is_do_evt_display () const inline
Definition at line 83 of file B0TrackFastSim.h.
View newest version in sPHENIX GitHub at line 83 of file B0TrackFastSim.h
References m_DoEvtDisplayFlag.
bool B0TrackFastSim::is_use_vertex_in_fitting () const inline
Definition at line 163 of file B0TrackFastSim.h.
View newest version in sPHENIX GitHub at line 163 of file B0TrackFastSim.h
References m_UseVertexInFittingFlag.
bool B0TrackFastSim::MakeSvtxTrack (SvtxTrack * track_out, const PHGenFit::Track * phgf_track_in, const unsigned int truth_track_id = UINT_MAX, const unsigned int nmeas = 0, const TVector3 & vtx = TVector3(0.0, 0.0, 0.0)) private
Make SvtxTrack from PHGenFit::Track
TODO: check the definition 1/p, u'/z', v'/z', u, v u is defined as mom X beam line at POCA so u is the dca2d direction
Definition at line 863 of file B0TrackFastSim.cc.
View newest version in sPHENIX GitHub at line 863 of file B0TrackFastSim.cc
References SvtxTrack::begin_states(), Acts::Test::cov, PHGenFit::Track::extrapolateToCylinder(), PHGenFit::Track::extrapolateToLine(), PHGenFit::Track::extrapolateToPlane(), genfit::MeasuredStateOnPlane::get6DCov(), PHGenFit::Track::get_charge(), PHGenFit::Track::get_chi2(), PHGenFit::Track::get_ndf(), genfit::MeasuredStateOnPlane::getCov(), genfit::StateOnPlane::getMom(), genfit::StateOnPlane::getPos(), genfit::StateOnPlane::getState(), SvtxTrack::insert_state(), LogError, m_ProjectionsMap, charm_jet_coverage::mom, pos(), SvtxTrack::set_charge(), SvtxTrack::set_chisq(), SvtxTrack::set_dca(), SvtxTrack::set_dca2d(), SvtxTrack::set_dca2d_error(), SvtxTrackState::set_error(), SvtxTrack::set_error(), SvtxTrackState::set_name(), SvtxTrack::set_ndf(), SvtxTrack::set_num_measurements(), SvtxTrackState::set_px(), SvtxTrack::set_px(), SvtxTrackState::set_py(), SvtxTrack::set_py(), SvtxTrackState::set_pz(), SvtxTrack::set_pz(), SvtxTrack::set_truth_track_id(), SvtxTrackState::set_x(), SvtxTrack::set_x(), SvtxTrackState::set_y(), SvtxTrack::set_y(), SvtxTrackState::set_z(), SvtxTrack::set_z(), and Fun4AllBase::Verbosity().
Referenced by process_event().
PHGenFit::PlanarMeasurement * B0TrackFastSim::PHG4HitToMeasurementCylinder (const PHG4Hit * g4hit, const double phi_resolution, const double z_resolution) private
Definition at line 1025 of file B0TrackFastSim.cc.
View newest version in sPHENIX GitHub at line 1025 of file B0TrackFastSim.cc
References PHG4Hit::get_avg_x(), PHG4Hit::get_avg_y(), PHG4Hit::get_avg_z(), m_RandomGenerator, m_SmearingFlag, pos(), Acts::UnitConstants::u, and v.
Referenced by PseudoPatternRecognition().
PHGenFit::PlanarMeasurement * B0TrackFastSim::PHG4HitToMeasurementVerticalPlane (const PHG4Hit * g4hit, const double phi_resolution, const double r_resolution) private
Definition at line 989 of file B0TrackFastSim.cc.
View newest version in sPHENIX GitHub at line 989 of file B0TrackFastSim.cc
References PHG4Hit::get_avg_x(), PHG4Hit::get_avg_y(), PHG4Hit::get_avg_z(), m_RandomGenerator, m_SmearingFlag, pos(), Acts::UnitConstants::u, and v.
Referenced by PseudoPatternRecognition().
int B0TrackFastSim::process_event (PHCompositeNode *) override virtual
Process Event, called for each event.
Create measurements
Build TrackRep from particle assumption
mu+: -13 mu-: 13 pi+: 211 pi-: -211 e-: 11 e+: -11
Initialize track with seed from pattern recognition
Add measurements to track
Fit the track
add tracks to event display
Reimplemented from SubsysReco.
Definition at line 243 of file B0TrackFastSim.cc.
View newest version in sPHENIX GitHub at line 243 of file B0TrackFastSim.cc
References Fun4AllReturnCodes::ABORTRUN, genfit::EventDisplay::addEvent(), PHGenFit::Track::addMeasurements(), Acts::Test::cov, Fun4AllReturnCodes::EVENT_OK, FillSvtxVertexMap(), genfit::GFRaveVertexFactory::findVertices(), PHG4Particle::get_track_id(), PHG4VtxPoint::get_x(), PHG4VtxPoint::get_y(), PHG4VtxPoint::get_z(), genfit::FitStatus::getCharge(), genfit::FitStatus::getChi2(), PHGenFit::Fitter::getEventDisplay(), genfit::Track::getFitStatus(), genfit::Track::getFittedState(), PHGenFit::Track::getGenFitTrack(), genfit::FitStatus::getNdf(), PHG4TruthInfoContainer::GetParticleRange(), genfit::MeasuredStateOnPlane::getPosMomCov(), PHG4TruthInfoContainer::GetPrimaryParticleRange(), PHG4TruthInfoContainer::GetPrimaryVertexIndex(), PHG4TruthInfoContainer::GetPrimaryVtx(), SvtxTrack::identify(), it, LogError, m_DoEvtDisplayFlag, m_DoVertexingFlag, m_EventCnt, m_Fitter, m_PrimaryAssumptionPid, m_PrimaryTrackingFlag, m_RandomGenerator, m_RaveVertexFactory, m_SvtxTrackMapOut, m_SvtxVertexMap, m_TruthContainer, m_UseVertexInFittingFlag, m_VertexMinNdf, m_VertexXYResolution, m_VertexZResolution, MakeSvtxTrack(), charm_jet_coverage::mom, particle, PHWHERE, pos(), PHGenFit::Fitter::processTrack(), PseudoPatternRecognition(), Fun4AllBase::Verbosity(), VertexMeasurement(), and vtx().
int B0TrackFastSim::PseudoPatternRecognition (const PHG4Particle * particle, std::vector< PHGenFit::Measurement * > & meas_out, SvtxTrack * track_out, TVector3 & seed_pos, TVector3 & seed_mom, TMatrixDSym & seed_cov, const bool do_smearing = true) private
Definition at line 693 of file B0TrackFastSim.cc.
View newest version in sPHENIX GitHub at line 693 of file B0TrackFastSim.cc
References Fun4AllReturnCodes::ABORTEVENT, SvtxTrack::add_g4hit_id(), Cylinder, Fun4AllReturnCodes::EVENT_OK, PHG4Hit::get_avg_t(), PHG4Hit::get_hit_id(), PHG4Particle::get_px(), PHG4Particle::get_py(), PHG4Particle::get_pz(), PHG4Particle::get_track_id(), PHG4Hit::get_trkid(), PHG4Particle::identify(), PHG4Hit::identify(), LogDebug, LogError, m_phg4_detector_hitfindeff, m_phg4_detector_lonres, m_phg4_detector_noise, m_phg4_detector_phires, m_phg4_detector_radres, m_phg4_detector_type, m_PHG4HitContainer, m_PHG4HitsNames, M_PI, m_RandomGenerator, PHG4HitToMeasurementCylinder(), PHG4HitToMeasurementVerticalPlane(), Fun4AllBase::Verbosity(), and Vertical_Plane.
Referenced by process_event().
void B0TrackFastSim::set_do_evt_display (bool doEvtDisplay) inline
Definition at line 88 of file B0TrackFastSim.h.
View newest version in sPHENIX GitHub at line 88 of file B0TrackFastSim.h
References m_DoEvtDisplayFlag.
void B0TrackFastSim::set_fit_alg_name (const std::string & fitAlgName) inline
Definition at line 98 of file B0TrackFastSim.h.
View newest version in sPHENIX GitHub at line 98 of file B0TrackFastSim.h
References m_FitAlgoName.
void B0TrackFastSim::set_primary_assumption_pid (int primaryAssumptionPid) inline
Definition at line 198 of file B0TrackFastSim.h.
View newest version in sPHENIX GitHub at line 198 of file B0TrackFastSim.h
References m_PrimaryAssumptionPid.
void B0TrackFastSim::set_primary_tracking (int pTrk) inline
Definition at line 203 of file B0TrackFastSim.h.
View newest version in sPHENIX GitHub at line 203 of file B0TrackFastSim.h
References m_PrimaryTrackingFlag.
void B0TrackFastSim::set_sub_top_node_name (const std::string & subTopNodeName) inline
Definition at line 158 of file B0TrackFastSim.h.
View newest version in sPHENIX GitHub at line 158 of file B0TrackFastSim.h
References m_SubTopnodeName.
void B0TrackFastSim::set_trackmap_out_name (const std::string & trackmapOutName) inline
Definition at line 148 of file B0TrackFastSim.h.
View newest version in sPHENIX GitHub at line 148 of file B0TrackFastSim.h
References m_TrackmapOutNodeName.
void B0TrackFastSim::set_use_vertex_in_fitting (bool useVertexInFitting) inline
Definition at line 168 of file B0TrackFastSim.h.
View newest version in sPHENIX GitHub at line 168 of file B0TrackFastSim.h
References m_UseVertexInFittingFlag.
void B0TrackFastSim::set_vertex_min_ndf (double vertexMinNdf) inline
Definition at line 225 of file B0TrackFastSim.h.
View newest version in sPHENIX GitHub at line 225 of file B0TrackFastSim.h
References m_VertexMinNdf.
void B0TrackFastSim::set_vertex_xy_resolution (double vertexXyResolution) inline
Definition at line 178 of file B0TrackFastSim.h.
View newest version in sPHENIX GitHub at line 178 of file B0TrackFastSim.h
References m_VertexXYResolution.
void B0TrackFastSim::set_vertex_z_resolution (double vertexZResolution) inline
Definition at line 188 of file B0TrackFastSim.h.
View newest version in sPHENIX GitHub at line 188 of file B0TrackFastSim.h
References m_VertexZResolution.
void B0TrackFastSim::set_vertexing_method (const std::string & vertexingMethod) inline
https://rave.hepforge.org/trac/wiki/RaveMethods
Definition at line 215 of file B0TrackFastSim.h.
View newest version in sPHENIX GitHub at line 215 of file B0TrackFastSim.h
References m_VertexingMethod.
void B0TrackFastSim::Smearing (const bool b) inline
Definition at line 237 of file B0TrackFastSim.h.
View newest version in sPHENIX GitHub at line 237 of file B0TrackFastSim.h
References m_SmearingFlag.
PHGenFit::Measurement * B0TrackFastSim::VertexMeasurement (const TVector3 & vtx, double dxy, double dz) private
Definition at line 1061 of file B0TrackFastSim.cc.
View newest version in sPHENIX GitHub at line 1061 of file B0TrackFastSim.cc
References Acts::Test::cov, dz, pos(), and vtx().
Referenced by process_event().
Member Data Documentation
bool B0TrackFastSim::m_DoEvtDisplayFlag protected
Definition at line 337 of file B0TrackFastSim.h.
View newest version in sPHENIX GitHub at line 337 of file B0TrackFastSim.h
Referenced by DisplayEvent(), End(), InitRun(), is_do_evt_display(), process_event(), and set_do_evt_display().
bool B0TrackFastSim::m_DoVertexingFlag protected
Definition at line 348 of file B0TrackFastSim.h.
View newest version in sPHENIX GitHub at line 348 of file B0TrackFastSim.h
Referenced by enable_vertexing(), InitRun(), and process_event().
int B0TrackFastSim::m_EventCnt protected
Event counter.
Definition at line 330 of file B0TrackFastSim.h.
View newest version in sPHENIX GitHub at line 330 of file B0TrackFastSim.h
Referenced by GetNodes(), InitRun(), and process_event().
std::string B0TrackFastSim::m_FitAlgoName protected
Available choices: KalmanFitter KalmanFitterRefTrack DafSimple DafRef
Definition at line 323 of file B0TrackFastSim.h.
View newest version in sPHENIX GitHub at line 323 of file B0TrackFastSim.h
Referenced by get_fit_alg_name(), GetNodes(), InitRun(), and set_fit_alg_name().
PHGenFit::Fitter* B0TrackFastSim::m_Fitter protected
GenFit fitter interface
Definition at line 290 of file B0TrackFastSim.h.
View newest version in sPHENIX GitHub at line 290 of file B0TrackFastSim.h
Referenced by DisplayEvent(), End(), InitRun(), process_event(), and ~B0TrackFastSim().
PHParameters* B0TrackFastSim::m_Parameter = nullptr protected
Definition at line 350 of file B0TrackFastSim.h.
View newest version in sPHENIX GitHub at line 350 of file B0TrackFastSim.h
Referenced by B0TrackFastSim(), and GetNodes().
std::vector<float> B0TrackFastSim::m_phg4_detector_hitfindeff protected
Definition at line 305 of file B0TrackFastSim.h.
View newest version in sPHENIX GitHub at line 305 of file B0TrackFastSim.h
Referenced by add_phg4hits(), GetNodes(), and PseudoPatternRecognition().
std::vector<float> B0TrackFastSim::m_phg4_detector_lonres protected
Definition at line 304 of file B0TrackFastSim.h.
View newest version in sPHENIX GitHub at line 304 of file B0TrackFastSim.h
Referenced by add_phg4hits(), GetNodes(), and PseudoPatternRecognition().
std::vector<float> B0TrackFastSim::m_phg4_detector_noise protected
Definition at line 306 of file B0TrackFastSim.h.
View newest version in sPHENIX GitHub at line 306 of file B0TrackFastSim.h
Referenced by add_phg4hits(), GetNodes(), and PseudoPatternRecognition().
std::vector<float> B0TrackFastSim::m_phg4_detector_phires protected
Definition at line 303 of file B0TrackFastSim.h.
View newest version in sPHENIX GitHub at line 303 of file B0TrackFastSim.h
Referenced by add_phg4hits(), GetNodes(), and PseudoPatternRecognition().
std::vector<float> B0TrackFastSim::m_phg4_detector_radres protected
Definition at line 302 of file B0TrackFastSim.h.
View newest version in sPHENIX GitHub at line 302 of file B0TrackFastSim.h
Referenced by add_phg4hits(), GetNodes(), and PseudoPatternRecognition().
std::vector<DETECTOR_TYPE> B0TrackFastSim::m_phg4_detector_type protected
Definition at line 301 of file B0TrackFastSim.h.
View newest version in sPHENIX GitHub at line 301 of file B0TrackFastSim.h
Referenced by add_phg4hits(), GetNodes(), and PseudoPatternRecognition().
std::vector<PHG4HitContainer*> B0TrackFastSim::m_PHG4HitContainer protected
Definition at line 299 of file B0TrackFastSim.h.
View newest version in sPHENIX GitHub at line 299 of file B0TrackFastSim.h
Referenced by GetNodes(), and PseudoPatternRecognition().
std::vector<std::string> B0TrackFastSim::m_PHG4HitsNames protected
Definition at line 300 of file B0TrackFastSim.h.
View newest version in sPHENIX GitHub at line 300 of file B0TrackFastSim.h
Referenced by add_phg4hits(), get_phg4hits_names(), GetNodes(), and PseudoPatternRecognition().
int B0TrackFastSim::m_PrimaryAssumptionPid protected
Definition at line 332 of file B0TrackFastSim.h.
View newest version in sPHENIX GitHub at line 332 of file B0TrackFastSim.h
Referenced by get_primary_assumption_pid(), process_event(), and set_primary_assumption_pid().
int B0TrackFastSim::m_PrimaryTrackingFlag protected
Definition at line 346 of file B0TrackFastSim.h.
View newest version in sPHENIX GitHub at line 346 of file B0TrackFastSim.h
Referenced by process_event(), and set_primary_tracking().
std::map<std::string, std::pair<int, double> > B0TrackFastSim::m_ProjectionsMap protected
Definition at line 309 of file B0TrackFastSim.h.
View newest version in sPHENIX GitHub at line 309 of file B0TrackFastSim.h
Referenced by add_cylinder_state(), add_state_name(), add_zplane_state(), InitRun(), and MakeSvtxTrack().
gsl_rng* B0TrackFastSim::m_RandomGenerator protected
random generator that conform with sPHENIX standard
Definition at line 285 of file B0TrackFastSim.h.
View newest version in sPHENIX GitHub at line 285 of file B0TrackFastSim.h
Referenced by B0TrackFastSim(), PHG4HitToMeasurementCylinder(), PHG4HitToMeasurementVerticalPlane(), process_event(), PseudoPatternRecognition(), and ~B0TrackFastSim().
genfit::GFRaveVertexFactory* B0TrackFastSim::m_RaveVertexFactory protected
Definition at line 291 of file B0TrackFastSim.h.
View newest version in sPHENIX GitHub at line 291 of file B0TrackFastSim.h
Referenced by InitRun(), process_event(), and ~B0TrackFastSim().
bool B0TrackFastSim::m_SmearingFlag protected
Definition at line 334 of file B0TrackFastSim.h.
View newest version in sPHENIX GitHub at line 334 of file B0TrackFastSim.h
Referenced by PHG4HitToMeasurementCylinder(), PHG4HitToMeasurementVerticalPlane(), and Smearing().
std::string B0TrackFastSim::m_SubTopnodeName protected
Definition at line 311 of file B0TrackFastSim.h.
View newest version in sPHENIX GitHub at line 311 of file B0TrackFastSim.h
Referenced by CreateNodes(), get_sub_top_node_name(), GetNodes(), and set_sub_top_node_name().
SvtxTrackMap* B0TrackFastSim::m_SvtxTrackMapOut protected
Definition at line 296 of file B0TrackFastSim.h.
View newest version in sPHENIX GitHub at line 296 of file B0TrackFastSim.h
Referenced by CreateNodes(), GetNodes(), and process_event().
SvtxVertexMap* B0TrackFastSim::m_SvtxVertexMap protected
Definition at line 297 of file B0TrackFastSim.h.
View newest version in sPHENIX GitHub at line 297 of file B0TrackFastSim.h
Referenced by CreateNodes(), FillSvtxVertexMap(), and process_event().
std::string B0TrackFastSim::m_TrackmapOutNodeName protected
Definition at line 312 of file B0TrackFastSim.h.
View newest version in sPHENIX GitHub at line 312 of file B0TrackFastSim.h
Referenced by CreateNodes(), get_trackmap_out_name(), GetNodes(), and set_trackmap_out_name().
PHG4TruthInfoContainer* B0TrackFastSim::m_TruthContainer protected
Input Node pointers.
Definition at line 294 of file B0TrackFastSim.h.
View newest version in sPHENIX GitHub at line 294 of file B0TrackFastSim.h
Referenced by GetNodes(), and process_event().
bool B0TrackFastSim::m_UseVertexInFittingFlag protected
For PseudoPatternRecognition function.
Definition at line 343 of file B0TrackFastSim.h.
View newest version in sPHENIX GitHub at line 343 of file B0TrackFastSim.h
Referenced by is_use_vertex_in_fitting(), process_event(), and set_use_vertex_in_fitting().
std::string B0TrackFastSim::m_VertexingMethod protected
https://rave.hepforge.org/trac/wiki/RaveMethods
Definition at line 314 of file B0TrackFastSim.h.
View newest version in sPHENIX GitHub at line 314 of file B0TrackFastSim.h
Referenced by get_vertexing_method(), GetNodes(), InitRun(), and set_vertexing_method().
double B0TrackFastSim::m_VertexMinNdf protected
Definition at line 325 of file B0TrackFastSim.h.
View newest version in sPHENIX GitHub at line 325 of file B0TrackFastSim.h
Referenced by get_vertex_min_ndf(), process_event(), and set_vertex_min_ndf().
double B0TrackFastSim::m_VertexXYResolution protected
Definition at line 326 of file B0TrackFastSim.h.
View newest version in sPHENIX GitHub at line 326 of file B0TrackFastSim.h
Referenced by get_vertex_xy_resolution(), process_event(), and set_vertex_xy_resolution().
double B0TrackFastSim::m_VertexZResolution protected
Definition at line 327 of file B0TrackFastSim.h.
View newest version in sPHENIX GitHub at line 327 of file B0TrackFastSim.h
Referenced by get_vertex_z_resolution(), process_event(), and set_vertex_z_resolution().
const std::set< std::string > B0TrackFastSim::reserved_cylinder_projection_names {} static protected
Definition at line 352 of file B0TrackFastSim.h.
View newest version in sPHENIX GitHub at line 352 of file B0TrackFastSim.h
Referenced by add_cylinder_state(), add_state_name(), and add_zplane_state().
const std::set< std::string > B0TrackFastSim::reserved_zplane_projection_names {"B0ECAL"} static protected
Definition at line 353 of file B0TrackFastSim.h.
View newest version in sPHENIX GitHub at line 353 of file B0TrackFastSim.h
Referenced by add_cylinder_state(), add_state_name(), and add_zplane_state().
The documentation for this class was generated from the following files:
fun4all_eicdetectors/blob/master/simulation/g4simulation/g4b0/B0TrackFastSim.h
fun4all_eicdetectors/blob/master/simulation/g4simulation/g4b0/B0TrackFastSim.cc