EIC Software: CMFlashCluster Class Reference
CMFlashCluster Class Reference
Base class for Central Membrane flassh combined cluster object.
#include <fun4all_coresoftware/blob/master/offline/packages/trackbase/CMFlashCluster.h>
Public Member Functions
~CMFlashCluster () override
dtor
void identify (std::ostream &os=std::cout) const override
void Reset () override
Clear Event.
int isValid () const override
isValid returns non zero if object contains vailid data
virtual void CopyFrom (const CMFlashCluster &)
copy content from base class
virtual void CopyFrom (CMFlashCluster *)
copy content from base class
virtual unsigned int getClusKey () const
virtual void setClusKey (unsigned int)
virtual float getX () const
virtual void setX (float)
virtual float getY () const
virtual void setY (float)
virtual float getZ () const
virtual void setZ (float)
virtual void setAdc (unsigned int)
virtual unsigned int getAdc () const
Public Member Functions inherited from PHObject
PHObject ()
ctor
~PHObject () override
dtor
virtual PHObject * CloneMe () const
Virtual copy constructor.
virtual PHObject * clone () const final
PHObject * Clone (const char *newname="") const final
void Copy (TObject &object) const final
virtual int isValid (const float) const
virtual int isValid (const double) const
virtual int isValid (const int) const
virtual int isValid (const unsigned int) const
virtual int isImplemented (const float f) const
virtual int isImplemented (const double f) const
virtual int isImplemented (const int i) const
virtual int isImplemented (const unsigned int i) const
virtual int Integrate () const
virtual int Integrate (PHObject *)
virtual void CopyFrom (const PHObject *obj)
Protected Member Functions
CMFlashCluster ()=default
Detailed Description
Base class for Central Membrane flassh combined cluster object.
Virtual base class for TPC CM flash cluster object
Definition at line 23 of file CMFlashCluster.h.
View newest version in sPHENIX GitHub at line 23 of file CMFlashCluster.h
Constructor & Destructor Documentation
CMFlashCluster::~CMFlashCluster () inline override
dtor
Definition at line 27 of file CMFlashCluster.h.
View newest version in sPHENIX GitHub at line 27 of file CMFlashCluster.h
CMFlashCluster::CMFlashCluster () protected default
Member Function Documentation
virtual void CMFlashCluster::CopyFrom (const CMFlashCluster &) inline virtual
copy content from base class
Reimplemented in CMFlashClusterv1.
Definition at line 41 of file CMFlashCluster.h.
View newest version in sPHENIX GitHub at line 41 of file CMFlashCluster.h
Referenced by CMFlashClusterv1::CopyFrom().
virtual void CMFlashCluster::CopyFrom (CMFlashCluster *) inline virtual
copy content from base class
Reimplemented in CMFlashClusterv1.
Definition at line 44 of file CMFlashCluster.h.
View newest version in sPHENIX GitHub at line 44 of file CMFlashCluster.h
virtual unsigned int CMFlashCluster::getAdc () const inline virtual
Reimplemented in CMFlashClusterv1.
Definition at line 66 of file CMFlashCluster.h.
View newest version in sPHENIX GitHub at line 66 of file CMFlashCluster.h
Referenced by CMFlashClusterv1::CopyFrom().
virtual unsigned int CMFlashCluster::getClusKey () const inline virtual
Reimplemented in CMFlashClusterv1.
Definition at line 49 of file CMFlashCluster.h.
View newest version in sPHENIX GitHub at line 49 of file CMFlashCluster.h
Referenced by CMFlashClusterContainerv1::addCluster(), CMFlashClusterv1::CopyFrom(), and CMFlashClusterContainerv1::removeCluster().
virtual float CMFlashCluster::getX () const inline virtual
Reimplemented in CMFlashClusterv1.
Definition at line 55 of file CMFlashCluster.h.
View newest version in sPHENIX GitHub at line 55 of file CMFlashCluster.h
Referenced by CMFlashClusterv1::CopyFrom().
virtual float CMFlashCluster::getY () const inline virtual
Reimplemented in CMFlashClusterv1.
Definition at line 57 of file CMFlashCluster.h.
View newest version in sPHENIX GitHub at line 57 of file CMFlashCluster.h
Referenced by CMFlashClusterv1::CopyFrom().
virtual float CMFlashCluster::getZ () const inline virtual
Reimplemented in CMFlashClusterv1.
Definition at line 59 of file CMFlashCluster.h.
View newest version in sPHENIX GitHub at line 59 of file CMFlashCluster.h
Referenced by CMFlashClusterv1::CopyFrom().
void CMFlashCluster::identify (std::ostream & os = std::cout) const inline override virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from PHObject.
Reimplemented in CMFlashClusterv1.
Definition at line 29 of file CMFlashCluster.h.
View newest version in sPHENIX GitHub at line 29 of file CMFlashCluster.h
int CMFlashCluster::isValid () const inline override virtual
isValid returns non zero if object contains vailid data
Reimplemented from PHObject.
Reimplemented in CMFlashClusterv1.
Definition at line 34 of file CMFlashCluster.h.
View newest version in sPHENIX GitHub at line 34 of file CMFlashCluster.h
void CMFlashCluster::Reset () inline override virtual
Clear Event.
Reimplemented from PHObject.
Reimplemented in CMFlashClusterv1.
Definition at line 33 of file CMFlashCluster.h.
View newest version in sPHENIX GitHub at line 33 of file CMFlashCluster.h
virtual void CMFlashCluster::setAdc (unsigned int) inline virtual
Reimplemented in CMFlashClusterv1.
Definition at line 65 of file CMFlashCluster.h.
View newest version in sPHENIX GitHub at line 65 of file CMFlashCluster.h
virtual void CMFlashCluster::setClusKey (unsigned int) inline virtual
Reimplemented in CMFlashClusterv1.
Definition at line 50 of file CMFlashCluster.h.
View newest version in sPHENIX GitHub at line 50 of file CMFlashCluster.h
virtual void CMFlashCluster::setX (float) inline virtual
Reimplemented in CMFlashClusterv1.
Definition at line 56 of file CMFlashCluster.h.
View newest version in sPHENIX GitHub at line 56 of file CMFlashCluster.h
virtual void CMFlashCluster::setY (float) inline virtual
Reimplemented in CMFlashClusterv1.
Definition at line 58 of file CMFlashCluster.h.
View newest version in sPHENIX GitHub at line 58 of file CMFlashCluster.h
virtual void CMFlashCluster::setZ (float) inline virtual
Reimplemented in CMFlashClusterv1.
Definition at line 60 of file CMFlashCluster.h.
View newest version in sPHENIX GitHub at line 60 of file CMFlashCluster.h
The documentation for this class was generated from the following file:
fun4all_coresoftware/blob/master/offline/packages/trackbase/CMFlashCluster.h