EIC Software: EicDetName Class Reference
EicDetName Class Reference
Detector name in all flavors like TPC, Tpc, tpc.
#include <EicRoot/blob/master/eic/base/EicDetName.h>
Public Member Functions
EicDetName ()
EicDetName (const char *name)
virtual ~EicDetName ()
TString const & NAME () const
TString const & name () const
TString const & Name () const
EicDetName ()
EicDetName (const char *name)
virtual ~EicDetName ()
TString const & NAME () const
TString const & name () const
TString const & Name () const
Private Member Functions
ClassDef (EicDetName, 1)
ClassDef (EicDetName, 1)
Private Attributes
TString mUname
TString mLname
TString mCname
Detailed Description
Detector name in all flavors like TPC, Tpc, tpc.
Definition at line 14 of file EicDetName.h.
View newest version in sPHENIX GitHub at line 14 of file EicDetName.h
Constructor & Destructor Documentation
EicDetName::EicDetName () inline
Default constructor
Definition at line 18 of file EicDetName.h.
View newest version in sPHENIX GitHub at line 18 of file EicDetName.h
EicDetName::EicDetName (const char * name)
Main constructor
Parameters
name detector name
Definition at line 13 of file EicDetName.cxx.
View newest version in sPHENIX GitHub at line 13 of file EicDetName.cxx
References mCname, mLname, mUname, FairUtilString::ToLower(), and FairUtilString::ToUpper().
virtual EicDetName::~EicDetName () inline virtual
Destructor
Definition at line 27 of file EicDetName.h.
View newest version in sPHENIX GitHub at line 27 of file EicDetName.h
EicDetName::EicDetName () inline
Default constructor
Definition at line 18 of file EicDetName.h.
View newest version in sPHENIX GitHub at line 18 of file EicDetName.h
EicDetName::EicDetName (const char * name)
Main constructor
Parameters
name detector name
virtual EicDetName::~EicDetName () inline virtual
Destructor
Definition at line 27 of file EicDetName.h.
View newest version in sPHENIX GitHub at line 27 of file EicDetName.h
Member Function Documentation
EicDetName::ClassDef (EicDetName , 1) private
EicDetName::ClassDef (EicDetName , 1) private
TString const& EicDetName::NAME () const inline
upper case name, like TPC
Definition at line 31 of file EicDetName.h.
View newest version in sPHENIX GitHub at line 31 of file EicDetName.h
References mUname.
Referenced by EicDetector::ConstructGeometry(), EicDigiHitProducer::EicDigiHitProducer(), EicGeoParData::EicGeoParData(), EicHtcTask::Exec(), EicCalorimeterDigiHitProducer::ExtraInit(), EicTrackingDigiHitProducer::ExtraInit(), EicTrackingDigiHitProducer::HandleHit(), EicCalorimeterReconstruction::Init(), EicCalorimeterDigiHitProducer::PostExec(), and EicGeoParData::SwitchGeoManager().
TString const& EicDetName::NAME () const inline
upper case name, like TPC
Definition at line 31 of file EicDetName.h.
View newest version in sPHENIX GitHub at line 31 of file EicDetName.h
References mUname.
TString const& EicDetName::name () const inline
lower case name, like tpc
Definition at line 34 of file EicDetName.h.
View newest version in sPHENIX GitHub at line 34 of file EicDetName.h
References mLname.
Referenced by eicpy.verify.PythiaHistograms::__init__(), eicpy.verify.DjangohHistograms::__init__(), EicCadWizard::AssembleRootFiles(), EicDetector::ConstructGeometry(), and EicGeoParData::GetGeometryFileName().
TString const& EicDetName::name () const inline
lower case name, like tpc
Definition at line 34 of file EicDetName.h.
View newest version in sPHENIX GitHub at line 34 of file EicDetName.h
References mLname.
TString const& EicDetName::Name () const inline
mixed case name, starting with capital letter, like Tpc
Definition at line 37 of file EicDetName.h.
View newest version in sPHENIX GitHub at line 37 of file EicDetName.h
References mCname.
Referenced by EicHtcTask::ConfigureKalmanFilter(), FstGeoParData::ConstructGeometry(), EicCadFile::ConstructGeometry(), EicDetector::ConstructGeometry(), BeamPipeGeoParData::ConstructGeometry(), EicHtcTask::DeclareSensitiveVolumes(), EicDetector::EicDetector(), EicGeoParData::EicGeoParData(), EicEventAssembler::Exec(), EicDigiHitProducer::Exec(), EicHtcTask::Exec(), EicCalorimeterDigiHitProducer::ExtraInit(), EicTrackingDigiHitProducer::ExtraInit(), femc(), EicGeoParData::FinalizeOutput(), EicCalorimeterReconstruction::Finish(), EicCalorimeterDigiHitProducer::Finish(), EicTrackingDigiHitProducer::Finish(), EicDetector::FinishRun(), EicDetector::GetNodeMultiIndex(), EicTrackingDigiHitProducer::HandleHit(), hcal(), EicDigiHitProducer::Init(), EicCalorimeterReconstruction::Init(), EicHtcTask::Init(), make_single_tower(), EicDetector::Print(), EicDetector::Register(), and EicGeoParData::SwitchGeoManager().
TString const& EicDetName::Name () const inline
mixed case name, starting with capital letter, like Tpc
Definition at line 37 of file EicDetName.h.
View newest version in sPHENIX GitHub at line 37 of file EicDetName.h
References mCname.
Member Data Documentation
TString EicDetName::mCname private
Definition at line 41 of file EicDetName.h.
View newest version in sPHENIX GitHub at line 41 of file EicDetName.h
Referenced by EicDetName(), and Name().
TString EicDetName::mLname private
Definition at line 41 of file EicDetName.h.
View newest version in sPHENIX GitHub at line 41 of file EicDetName.h
Referenced by EicDetName(), and name().
TString EicDetName::mUname private
Definition at line 41 of file EicDetName.h.
View newest version in sPHENIX GitHub at line 41 of file EicDetName.h
Referenced by EicDetName(), and NAME().
The documentation for this class was generated from the following files:
EicRoot/blob/master/eic/base/EicDetName.h
EicToyModel/blob/master/include/EicDetName.h
EicRoot/blob/master/eic/base/EicDetName.cxx
EicToyModel/blob/master/source/eicroot/EicDetName.cxx