EIC Software: eASTHepMC3Interface Class Reference
eASTHepMC3Interface Class Reference
#include <east/blob/main/PrimGenInterface/include/eASTHepMC3Interface.hh>
Public Member Functions
virtual ~eASTHepMC3Interface ()
virtual void GeneratePrimaryVertex (G4Event *)
G4bool OpenFile (G4String)
void SetVertexPosition (G4ThreeVector vPos)
G4ThreeVector GetVertexPosition () const
void SetVertexTime (G4double t0)
G4double GetVertexTime () const
void SetVerbose (G4int vl)
Static Public Member Functions
static eASTHepMC3Interface * GetInstance ()
Private Member Functions
eASTHepMC3Interface ()
G4PrimaryParticle * MakeParticle (const HepMC3::ConstGenParticlePtr hep_p, const bool safetycheck, std::set< int > &used)
Private Attributes
G4String fileName
G4GenericMessenger * messenger
G4ThreeVector vPosition = G4ThreeVector(0.,0.,0.)
G4double vTime = 0.
G4int verboseLevel = 1
std::shared_ptr< HepMC3::Reader > HepMC3Reader
std::map< int,
G4PrimaryParticle * > created_daughters
Static Private Attributes
static eASTHepMC3Interface * instance = nullptr
static G4bool instantiated = false
Detailed Description
Definition at line 26 of file eASTHepMC3Interface.hh.
View newest version in sPHENIX GitHub at line 26 of file eASTHepMC3Interface.hh
Constructor & Destructor Documentation
eASTHepMC3Interface::eASTHepMC3Interface () private
Definition at line 47 of file eASTHepMC3Interface.cc.
View newest version in sPHENIX GitHub at line 47 of file eASTHepMC3Interface.cc
References instantiated, messenger, OpenFile(), SetVerbose(), SetVertexPosition(), and SetVertexTime().
Referenced by GetInstance().
eASTHepMC3Interface::~eASTHepMC3Interface () virtual
Definition at line 78 of file eASTHepMC3Interface.cc.
View newest version in sPHENIX GitHub at line 78 of file eASTHepMC3Interface.cc
References instance, and messenger.
Member Function Documentation
void eASTHepMC3Interface::GeneratePrimaryVertex (G4Event * g4event) virtual
Definition at line 110 of file eASTHepMC3Interface.cc.
View newest version in sPHENIX GitHub at line 110 of file eASTHepMC3Interface.cc
References created_daughters, HepMC3Reader, MakeParticle(), Acts::UnitConstants::mm, and pos().
eASTHepMC3Interface * eASTHepMC3Interface::GetInstance () static
Definition at line 39 of file eASTHepMC3Interface.cc.
View newest version in sPHENIX GitHub at line 39 of file eASTHepMC3Interface.cc
References eASTHepMC3Interface(), instance, and instantiated.
Referenced by eASTActionInitialization::BuildForMaster(), eASTPrimaryGeneratorAction::eASTPrimaryGeneratorAction(), and eASTPrimaryGeneratorAction::~eASTPrimaryGeneratorAction().
G4ThreeVector eASTHepMC3Interface::GetVertexPosition () const inline
Definition at line 56 of file eASTHepMC3Interface.hh.
View newest version in sPHENIX GitHub at line 56 of file eASTHepMC3Interface.hh
References vPosition.
G4double eASTHepMC3Interface::GetVertexTime () const inline
Definition at line 62 of file eASTHepMC3Interface.hh.
View newest version in sPHENIX GitHub at line 62 of file eASTHepMC3Interface.hh
References vTime.
G4PrimaryParticle * eASTHepMC3Interface::MakeParticle (const HepMC3::ConstGenParticlePtr hep_p, const bool safetycheck, std::set< int > & used) private
Definition at line 214 of file eASTHepMC3Interface.cc.
View newest version in sPHENIX GitHub at line 214 of file eASTHepMC3Interface.cc
References Acts::UnitConstants::GeV, p, and verboseLevel.
Referenced by GeneratePrimaryVertex().
G4bool eASTHepMC3Interface::OpenFile (G4String fName)
Definition at line 85 of file eASTHepMC3Interface.cc.
View newest version in sPHENIX GitHub at line 85 of file eASTHepMC3Interface.cc
References HepMC3::deduce_reader(), fileName, HepMC3Reader, and verboseLevel.
Referenced by eASTHepMC3Interface().
void eASTHepMC3Interface::SetVerbose (G4int vl) inline
Definition at line 66 of file eASTHepMC3Interface.hh.
View newest version in sPHENIX GitHub at line 66 of file eASTHepMC3Interface.hh
References verboseLevel.
Referenced by eASTHepMC3Interface().
void eASTHepMC3Interface::SetVertexPosition (G4ThreeVector vPos) inline
Definition at line 54 of file eASTHepMC3Interface.hh.
View newest version in sPHENIX GitHub at line 54 of file eASTHepMC3Interface.hh
References vPosition.
Referenced by eASTHepMC3Interface().
void eASTHepMC3Interface::SetVertexTime (G4double t0) inline
Definition at line 60 of file eASTHepMC3Interface.hh.
View newest version in sPHENIX GitHub at line 60 of file eASTHepMC3Interface.hh
References vTime.
Referenced by eASTHepMC3Interface().
Member Data Documentation
std::map<int,G4PrimaryParticle*> eASTHepMC3Interface::created_daughters private
Definition at line 81 of file eASTHepMC3Interface.hh.
View newest version in sPHENIX GitHub at line 81 of file eASTHepMC3Interface.hh
Referenced by GeneratePrimaryVertex().
G4String eASTHepMC3Interface::fileName private
Definition at line 70 of file eASTHepMC3Interface.hh.
View newest version in sPHENIX GitHub at line 70 of file eASTHepMC3Interface.hh
Referenced by OpenFile().
std::shared_ptr<HepMC3::Reader> eASTHepMC3Interface::HepMC3Reader private
Definition at line 77 of file eASTHepMC3Interface.hh.
View newest version in sPHENIX GitHub at line 77 of file eASTHepMC3Interface.hh
Referenced by GeneratePrimaryVertex(), and OpenFile().
eASTHepMC3Interface * eASTHepMC3Interface::instance = nullptr static private
Definition at line 29 of file eASTHepMC3Interface.hh.
View newest version in sPHENIX GitHub at line 29 of file eASTHepMC3Interface.hh
Referenced by GetInstance(), and ~eASTHepMC3Interface().
G4bool eASTHepMC3Interface::instantiated = false static private
Definition at line 30 of file eASTHepMC3Interface.hh.
View newest version in sPHENIX GitHub at line 30 of file eASTHepMC3Interface.hh
Referenced by eASTHepMC3Interface(), and GetInstance().
G4GenericMessenger* eASTHepMC3Interface::messenger private
Definition at line 71 of file eASTHepMC3Interface.hh.
View newest version in sPHENIX GitHub at line 71 of file eASTHepMC3Interface.hh
Referenced by eASTHepMC3Interface(), and ~eASTHepMC3Interface().
G4int eASTHepMC3Interface::verboseLevel = 1 private
Definition at line 75 of file eASTHepMC3Interface.hh.
View newest version in sPHENIX GitHub at line 75 of file eASTHepMC3Interface.hh
Referenced by MakeParticle(), OpenFile(), and SetVerbose().
G4ThreeVector eASTHepMC3Interface::vPosition = G4ThreeVector(0.,0.,0.) private
Definition at line 73 of file eASTHepMC3Interface.hh.
View newest version in sPHENIX GitHub at line 73 of file eASTHepMC3Interface.hh
Referenced by GetVertexPosition(), and SetVertexPosition().
G4double eASTHepMC3Interface::vTime = 0. private
Definition at line 74 of file eASTHepMC3Interface.hh.
View newest version in sPHENIX GitHub at line 74 of file eASTHepMC3Interface.hh
Referenced by GetVertexTime(), and SetVertexTime().
The documentation for this class was generated from the following files:
east/blob/main/PrimGenInterface/include/eASTHepMC3Interface.hh
east/blob/main/PrimGenInterface/src/eASTHepMC3Interface.cc