EIC Software: Experiment Namespace Reference
Experiment Namespace Reference
Typedefs
typedef enum
Experiment::EExperiment Experiment_t
Enumerations
enum EExperiment {
kUnknown = 0x00, kS001 = 0x01, kS002 = 0x02, kS003 = 0x04,
kS004 = 0x08, kS005 = 0x10, kS006 = 0x11
}
Functions
Int_t FullMask ()
const Char_t * AsString (Experiment_t detector)
Experiment::Experiment_t CharToEnum (Char_t c)
Char_t * MaskToString (Int_t mask)
Experiment::Experiment_t StringToEnum (const Char_t *chars, Int_t maxChar=0)
Int_t StringToMask (const Char_t *chars, Int_t maxChar=0)
Typedef Documentation
typedef enum Experiment::EExperiment Experiment::Experiment_t
Enumeration Type Documentation
enum Experiment::EExperiment
Enumerator:
kUnknown
kS001
kS002
kS003
kS004
kS005
kS006
Definition at line 22 of file Experiment.h.
View newest version in sPHENIX GitHub at line 22 of file Experiment.h
Function Documentation
const Char_t * Experiment::AsString (Experiment_t detector)
Definition at line 13 of file Experiment.cxx.
View newest version in sPHENIX GitHub at line 13 of file Experiment.cxx
References kS001, kS002, kS003, kS004, kS005, and kS006.
Referenced by MaskToString().
Experiment::Experiment_t Experiment::CharToEnum (Char_t c)
Definition at line 41 of file Experiment.cxx.
View newest version in sPHENIX GitHub at line 41 of file Experiment.cxx
References kS001, kS002, kS003, kS004, kS005, and kUnknown.
Int_t Experiment::FullMask ()
Definition at line 8 of file Experiment.cxx.
View newest version in sPHENIX GitHub at line 8 of file Experiment.cxx
References kS001, kS002, kS003, kS004, kS005, and kS006.
Referenced by MaskToString().
Char_t * Experiment::MaskToString (Int_t mask)
Definition at line 74 of file Experiment.cxx.
View newest version in sPHENIX GitHub at line 74 of file Experiment.cxx
References AsString(), and FullMask().
Experiment::Experiment_t Experiment::StringToEnum (const Char_t * chars, Int_t maxChar = 0)
Definition at line 104 of file Experiment.cxx.
View newest version in sPHENIX GitHub at line 104 of file Experiment.cxx
References kS001, kS002, kS003, kS004, kS005, kS006, kUnknown, and StringToMask().
Int_t Experiment::StringToMask (const Char_t * chars, Int_t maxChar = 0)
Definition at line 137 of file Experiment.cxx.
View newest version in sPHENIX GitHub at line 137 of file Experiment.cxx
References kS001, kS002, kS003, kS004, and kS005.
Referenced by StringToEnum().