EIC Software: fun4all_macros/blob/master/macros/sPHENIXStyle/test_style.C File Reference
test_style.C File Reference
Functions
TH1F h1 ("h1","H1;Mass [GeV];Counts [/ GeV];", 20, 0, 20)
TH1F h2 ("h2","H2;Mass [GeV];Counts [/ GeV];", 20, 0, 20)
for (int i=0;i< 1000;i++)
h1 Draw ("e1")
h2 Draw ("same")
h2 SetFillColor (5)
h1 Draw ("e1same")
TLegend leg (.55,.70,.85,.93)
leg AddEntry ("","#it{#bf{sPHENIX}} Simulation","")
leg AddEntry ("","Au+Au #sqrt{s_{NN}}=200 GeV","")
leg Draw ()
c RedrawAxis ()
c Print ("test_style.pdf")
c Print ("test_style.png")
c2 SetRightMargin (.2)
TF2 f2 ("f2","exp(-x/5)*sin(y)",-5, 5,-5, 5)
f2 SetNpx (100)
f2 SetNpy (100)
f2 Draw ("surf2z")
f2 GetXaxis () -> SetTitle("X")
f2 GetYaxis () -> SetTitle("Y")
f2 GetZaxis () -> SetTitle("Z")
c2 Print ("test_style_f2.pdf")
c2 Print ("test_style_f2.png")
Variables
leg AddEntry & h1
leg AddEntry & h2
TCanvas c2
Function Documentation
leg AddEntry ("" , "#it{#bf{sPHENIX}} Simulation" , "")
Referenced by EtmDetectorStack::add(), FairDbExceptionLog::AddLog(), analysis_resolution(), and material_scan().
leg AddEntry ("")
h1 Draw ("e1")
h2 Draw ("same")
h1 Draw ("e1same")
leg Draw ()
f2 Draw ("surf2z")
TF2 f2 ("f2" , "exp(-x/5)*sin(y)" , - 5, 5 , - 5, 5)
Referenced by CbmRichRingFitterQa::CalculateFitErrors(), CbmRichGeoTest::DrawSummaryPlotsTemp(), LiteCaloEval::End(), FitProfile(), FitResolution(), gadap(), gadap2(), gadapf(), spectrum::generateKdouble(), spectrum::generateKsingle(), PHGeomIOTGeo::GetGeometryCopy(), FairEventManagerEditor::Init(), LoopEvalFR(), LoopEvalHR(), mkf2(), GFMaterialEffects::noiseBetheBloch(), genfit::MaterialEffects::noiseBetheBloch(), pepsimainerhic(), pyofsh(), pyoper(), pyrnm3(), pyrnmq(), pytbdy(), pyxxga(), kdfinder::LinearFit< T >::RobustFit(), TPCDaqDefs::FEEv1::SampleFit_PowerLawDoubleExp(), erhic::EventPythia::SetF2(), strf(), tetgenmesh::tetalldihedral(), tetgenmesh::unifysegments(), vegas(), and photonNucleusLuminosity::vmsigmapt().
for ()
Definition at line 6 of file test_style.C.
View newest version in sPHENIX GitHub at line 6 of file test_style.C
References h1.
f2 GetXaxis () -> SetTitle("X")
Definition at line 279 of file acceptance.C.
View newest version in sPHENIX GitHub at line 279 of file acceptance.C
Referenced by PrettyTGraphErrors(), and prettyTH1F().
f2 GetYaxis () -> SetTitle("Y")
f2 GetZaxis () -> SetTitle("Z")
TH1F h1 ("h1" , "H1;Mass ;Counts ;" [GeV][/GeV], 20 , 0 , 20)
TH1F h2 ("h2" , "H2;Mass ;Counts ;" [GeV][/GeV], 20 , 0 , 20)
TLegend leg (. 55, . 70, . 85, . 93)
Referenced by compareDistributions(), compareHistograms(), CbmRichGeoTest::DrawSummaryPlotsTemp(), errorOf1DHistograms(), CbmRichGeoTest::FitH1OneOverX(), main(), Mat_map(), and material_scan().
c Print ("test_style.pdf")
Referenced by analysis_resolution(), ClassImp(), compareForthBackJacNoise(), PHFlag::get_CharFlag(), PHFlag::get_DoubleFlag(), PHFlag::get_FloatFlag(), PHFlag::get_IntFlag(), genfit::Exception::info(), material_scan(), PgPostBankBackupStorage::Print(), erhic::EventMC::Print(), EicHtcTask::Print(), genfit::KalmanFitterRefTrack::processTrackPoint(), and genfit::KalmanFitterRefTrack::processTrackPointSqrt().
c Print ("test_style.png")
c2 Print ("test_style_f2.pdf")
c2 Print ("test_style_f2.png")
c RedrawAxis ()
h2 SetFillColor (5)
f2 SetNpx (100)
f2 SetNpy (100)
c2 SetRightMargin (. 2)
Referenced by material_scan().
Variable Documentation
TCanvas c2
Definition at line 24 of file test_style.C.
View newest version in sPHENIX GitHub at line 24 of file test_style.C
Referenced by kdfinder::angle_between_vectors(), boundParamResolution(), CMDistortionAnalysis(), CMDistortionAnalysisCart(), CMDistortionAnalysisPhiR(), CbmRichRingFitterQa::Draw(), CbmRichTrainAnnSelect::Draw(), CbmRichTrainAnnElectrons::Draw(), CbmRichGeoTest::DrawH2MeanRms(), CbmRichUrqmdTest::DrawHist(), CbmRichGeoTest::DrawSummaryPlotsTemp(), FitNewton::NewtonMinimizerGradHessian::findSaddlePoint(), genfit::GblFitterInfo::getCovariance(), AnnularFieldSim::GetStepDistortion(), main(), material_scan(), FitNewton::NewtonMinimizerGradHessian::minimize(), perigeeParamResolution(), plot(), plot_ratio(), genfit::GFGbl::processTrackWithRep(), FairGeoRotation::setEulerAngles(), and FairGeanePro::Track3ToLine().
leg AddEntry& h1
Definition at line 17 of file test_style.C.
View newest version in sPHENIX GitHub at line 17 of file test_style.C
Referenced by VertexFitFunc::calcValGradHessian(), compareDistributions(), compareHistograms(), decode_idhammond(), errorOf1DHistograms(), errorOf2DHistograms(), FitProfile(), FitResolution(), for(), BEmcRec::HitACompare(), G4SnglNtuple::Init(), G4TowerNtuple::Init(), SimpleNtuple::Init(), G4CellNtuple::Init(), G4HitNtuple::Init(), lmidat(), MergeRootfile(), odeint(), pyhisigh(), pysigh(), sPHENIXTrackerTpc::tripletRejection(), sPHENIXTracker::tripletRejection(), and sPHENIXSeedFinder::tripletRejection().
leg AddEntry& h2
Definition at line 18 of file test_style.C.
View newest version in sPHENIX GitHub at line 18 of file test_style.C
Referenced by Acts::Test::BOOST_AUTO_TEST_CASE(), VertexFitFunc::calcValGradHessian(), compareDistributions(), compareHistograms(), decode_idhammond(), errorOf1DHistograms(), errorOf2DHistograms(), BEmcRec::HitACompare(), CbmRichRingFinderHoughSimd::HoughTransformGroup(), MergeRootfile(), FairRKPropagator::OneStepRungeKutta(), plot_matscan(), QAG4SimulationCalorimeterSum::process_event_Cluster(), QAG4SimulationEicCalorimeterSum::process_event_Cluster(), pyhisigh(), pysigh(), Nystrom::step(), Acts::EigenStepper< bfield_t, extensionlist_t, auctioneer_t >::step(), GPUTPCTrackParam::TransportToX(), sPHENIXTrackerTpc::tripletRejection(), sPHENIXTracker::tripletRejection(), and sPHENIXSeedFinder::tripletRejection().