EIC Software: fun4all_eicmacros/blob/master/common/G4_FEMC.C File Reference
G4_FEMC.C File Reference
#include <GlobalVariables.C>
#include <g4calo/RawTowerBuilderByHitIndex.h>
#include <g4calo/RawTowerDigitizer.h>
#include <g4eiccalos/PHG4ForwardCalCellReco.h>
#include <g4eiccalos/PHG4ForwardEcalSubsystem.h>
#include <g4eval/CaloEvaluator.h>
#include <g4main/PHG4Reco.h>
#include <caloreco/RawClusterBuilderFwd.h>
#include <caloreco/RawClusterBuilderTemplate.h>
#include <caloreco/RawTowerCalibration.h>
#include <fun4all/Fun4AllServer.h>
Namespaces
namespace Enable
namespace G4FEMC
Macros
#define MACRO_G4FEMC_C
Enumerations
enum G4FEMC::enu_Femc_clusterizer {
G4FEMC::kFemcGraphClusterizer, G4FEMC::kFemcTemplateClusterizer, G4FEMC::kFemcGraphClusterizer, G4FEMC::kFemcTemplateClusterizer,
G4FEMC::kFemcGraphClusterizer, G4FEMC::kFemcTemplateClusterizer
}
Functions
void FEMCInit ()
void FEMCSetup (PHG4Reco *g4Reco, const int absorberactive=0)
void FEMC_Cells ()
void FEMC_Towers ()
void FEMC_Clusters ()
void FEMC_Eval (std::string outputfile)
Variables
bool Enable::FEMC = false
bool Enable::FEMC_ABSORBER = false
bool Enable::FEMC_CELL = false
bool Enable::FEMC_TOWER = false
bool Enable::FEMC_CLUSTER = false
bool Enable::FEMC_EVAL = false
bool Enable::FEMC_OVERLAPCHECK = false
int Enable::FEMC_VERBOSITY = 0
double G4FEMC::Gz0 = 305.
double G4FEMC::Gdz = 40.
double G4FEMC::outer_radius = 180.
string G4FEMC::calibfile = "/ForwardEcal/mapping/towerMap_FEMC_fsPHENIX_v004.txt"
enu_Femc_clusterizer G4FEMC::Femc_clusterizer = kFemcTemplateClusterizer
Macro Definition Documentation
#define MACRO_G4FEMC_C
Definition at line 2 of file G4_FEMC.C.
View newest version in sPHENIX GitHub at line 2 of file G4_FEMC.C
Function Documentation
void FEMC_Cells ()
Definition at line 92 of file G4_FEMC.C.
View newest version in sPHENIX GitHub at line 92 of file G4_FEMC.C
Referenced by Fun4All_G4_LBLDetector(), and Fun4All_G4_sPHENIX().
void FEMC_Clusters ()
Definition at line 217 of file G4_FEMC.C.
View newest version in sPHENIX GitHub at line 217 of file G4_FEMC.C
References RawClusterBuilderTemplate::Detector(), RawClusterBuilderFwd::Detector(), exit(), G4FEMC::Femc_clusterizer, Enable::FEMC_VERBOSITY, Fun4AllServer::instance(), G4FEMC::kFemcGraphClusterizer, G4FEMC::kFemcTemplateClusterizer, RawClusterBuilderTemplate::LoadProfile(), max, Fun4AllServer::registerSubsystem(), RawClusterBuilderFwd::set_threshold_energy(), RawClusterBuilderTemplate::set_threshold_energy(), Enable::VERBOSITY, and Fun4AllBase::Verbosity().
Referenced by Extract_ECCE_gdml(), Fun4All_AnaTutorial_sPHENIX(), Fun4All_AnaTutorial_sPHENIX_Jets(), Fun4All_G4_CEMC(), Fun4All_G4_EICDetector(), Fun4All_G4_EICDetector_AnaTutorial(), Fun4All_G4_FEMC(), Fun4All_G4_FHCAL(), Fun4All_G4_fsPHENIX(), Fun4All_G4_FullDetectorModular(), Fun4All_G4_FullDetectorModularBeast(), Fun4All_G4_HCALIN(), Fun4All_G4_HCALOUT(), Fun4All_G4_LBLDetector(), and Fun4All_G4_sPHENIX().
void FEMC_Eval (std::string outputfile)
Definition at line 252 of file G4_FEMC.C.
View newest version in sPHENIX GitHub at line 252 of file G4_FEMC.C
References Enable::FEMC_VERBOSITY, Fun4AllServer::instance(), max, Fun4AllServer::registerSubsystem(), Enable::VERBOSITY, and Fun4AllBase::Verbosity().
Referenced by Fun4All_AnaTutorial_sPHENIX(), Fun4All_AnaTutorial_sPHENIX_Jets(), Fun4All_G4_CEMC(), Fun4All_G4_EICDetector(), Fun4All_G4_EICDetector_AnaTutorial(), Fun4All_G4_FEMC(), Fun4All_G4_FHCAL(), Fun4All_G4_fsPHENIX(), Fun4All_G4_HCALIN(), Fun4All_G4_HCALOUT(), Fun4All_G4_LBLDetector(), and Fun4All_G4_sPHENIX().
void FEMC_Towers ()
Definition at line 97 of file G4_FEMC.C.
View newest version in sPHENIX GitHub at line 97 of file G4_FEMC.C
References G4FEMC::calibfile, RawTowerDigitizer::Detector(), RawTowerCalibration::Detector(), RawTowerBuilderByHitIndex::Detector(), Enable::FEMC_VERBOSITY, RawTowerBuilderByHitIndex::GeometryTableFile(), Fun4AllServer::instance(), RawTowerDigitizer::kNo_digitization, RawTowerCalibration::kSimple_linear_calibration, max, Fun4AllServer::registerSubsystem(), RawTowerCalibration::set_calib_algorithm(), RawTowerCalibration::set_calib_const_GeV_ADC(), RawTowerDigitizer::set_digi_algorithm(), RawTowerCalibration::set_pedstal_ADC(), RawTowerBuilderByHitIndex::set_sim_tower_node_prefix(), RawTowerDigitizer::TowerType(), RawTowerCalibration::TowerType(), Enable::VERBOSITY, and Fun4AllBase::Verbosity().
Referenced by Extract_ECCE_gdml(), Fun4All_AnaTutorial_sPHENIX(), Fun4All_AnaTutorial_sPHENIX_Jets(), Fun4All_G4_CEMC(), Fun4All_G4_EICDetector(), Fun4All_G4_EICDetector_AnaTutorial(), Fun4All_G4_FEMC(), Fun4All_G4_FHCAL(), Fun4All_G4_fsPHENIX(), Fun4All_G4_FullDetectorModular(), Fun4All_G4_FullDetectorModularBeast(), Fun4All_G4_HCALIN(), Fun4All_G4_HCALOUT(), Fun4All_G4_LBLDetector(), and Fun4All_G4_sPHENIX().
void FEMCInit ()
Definition at line 58 of file G4_FEMC.C.
View newest version in sPHENIX GitHub at line 58 of file G4_FEMC.C
References G4FEMC::Gdz, G4FEMC::Gz0, max, BlackHoleGeometry::max_radius, BlackHoleGeometry::max_z, min, BlackHoleGeometry::min_z, and G4FEMC::outer_radius.
Referenced by G4Init().
void FEMCSetup (PHG4Reco * g4Reco, const int absorberactive = 0)
Use dedicated FEMC module
Definition at line 65 of file G4_FEMC.C.
View newest version in sPHENIX GitHub at line 65 of file G4_FEMC.C
References Enable::ABSORBER, G4FEMC::calibfile, femc(), Enable::FEMC_ABSORBER, Enable::FEMC_OVERLAPCHECK, Fun4AllServer::instance(), Enable::OVERLAPCHECK, PHG4DetectorSubsystem::OverlapCheck(), PHG4Reco::registerSubsystem(), PHG4DetectorSubsystem::SetAbsorberActive(), PHG4DetectorSubsystem::SetActive(), PHG4ForwardEcalSubsystem::SetDetailed(), PHG4ForwardEcalSubsystem::SetfsPHENIXDetector(), PHG4ForwardEcalSubsystem::SetTowerMappingFile(), and PHG4DetectorSubsystem::SuperDetector().
Referenced by G4Setup().