EIC Software: FairDb Namespace Reference
FairDb Namespace Reference
Typedefs
typedef Int_t Task
Enumerations
enum TaskTypes { kAnyTask = -1, kDefaultTask = 0 }
enum TypeRegimes { kRootRegime = 0, kSQLRegime = 1 }
enum DataTypes {
kUnknown, kBool, kChar, kUChar,
kTiny, kUTiny, kShort, kUShort,
kInt, kUInt, kLong, kULong,
kFloat, kDouble, kString, kTString,
kDate
}
enum DbTypes { kUnknownDbType = -1, kMySQL = 0, kOracle = 1 }
enum AbortTest { kDisabled, kTableMissing, kDataMissing }
enum { kMAXLOCALSEQNO = 99999999, kMAXTABLENAMELEN = 80 }
Functions
Int_t GetTimeGate (const std::string &tableName)
void SetTimeGate (const std::string &tableName, Int_t timeGate)
TString MakeDateTimeString (const ValTimeStamp &timeStamp)
ValTimeStamp MakeTimeStamp (const std::string &sqlDateTime, Bool_t *ok=0)
TString GetValDescr (const char *tableName, Bool_t isTemporary=kFALSE)
Bool_t NotGlobalSeqNo (UInt_t seqNo)
Typedef Documentation
typedef Int_t FairDb::Task
Definition at line 22 of file FairDb.h.
View newest version in sPHENIX GitHub at line 22 of file FairDb.h
Enumeration Type Documentation
anonymous enum
Enumerator:
kMAXLOCALSEQNO
kMAXTABLENAMELEN
Definition at line 64 of file FairDb.h.
View newest version in sPHENIX GitHub at line 64 of file FairDb.h
enum FairDb::AbortTest
Enumerator:
kDisabled
kTableMissing
kDataMissing
Definition at line 59 of file FairDb.h.
View newest version in sPHENIX GitHub at line 59 of file FairDb.h
enum FairDb::DataTypes
Enumerator:
kUnknown
kBool
kChar
kUChar
kTiny
kUTiny
kShort
kUShort
kInt
kUInt
kLong
kULong
kFloat
kDouble
kString
kTString
kDate
Definition at line 34 of file FairDb.h.
View newest version in sPHENIX GitHub at line 34 of file FairDb.h
enum FairDb::DbTypes
Enumerator:
kUnknownDbType
kMySQL
kOracle
Definition at line 54 of file FairDb.h.
View newest version in sPHENIX GitHub at line 54 of file FairDb.h
enum FairDb::TaskTypes
Enumerator:
kAnyTask
kDefaultTask
Definition at line 24 of file FairDb.h.
View newest version in sPHENIX GitHub at line 24 of file FairDb.h
enum FairDb::TypeRegimes
Enumerator:
kRootRegime
kSQLRegime
Definition at line 28 of file FairDb.h.
View newest version in sPHENIX GitHub at line 28 of file FairDb.h
Function Documentation
Int_t FairDb::GetTimeGate (const std::string & tableName)
Definition at line 6 of file FairDb.cxx.
View newest version in sPHENIX GitHub at line 6 of file FairDb.cxx
References SetTimeGate().
Referenced by ClassImp(), FairDbProxy::FindTimeBoundaries(), FairDbValidityRecBuilder::MakeGapRec(), and FairDbProxy::QueryValidity().
TString FairDb::GetValDescr (const char * tableName, Bool_t isTemporary = kFALSE)
Definition at line 21 of file FairDb.cxx.
View newest version in sPHENIX GitHub at line 21 of file FairDb.cxx
Referenced by FairDbMultConnector::CreateTemporaryTable().
TString FairDb::MakeDateTimeString (const ValTimeStamp & timeStamp)
Definition at line 45 of file FairDb.cxx.
View newest version in sPHENIX GitHub at line 45 of file FairDb.cxx
References ValTimeStamp::AsString().
Referenced by FairDbProxy::FindTimeBoundaries(), FairDbOutRowStream::operator<<(), FairDbProxy::QueryValidity(), FairDbRollbackDates::Set(), and FairDbSqlValPacket::Store().
ValTimeStamp FairDb::MakeTimeStamp (const std::string & sqlDateTime, Bool_t * ok = 0)
Definition at line 52 of file FairDb.cxx.
View newest version in sPHENIX GitHub at line 52 of file FairDb.cxx
References ValTimeStamp::GetDate(), in, and min.
Referenced by FairDbSqlValPacket::Fill(), FairDbProxy::FindTimeBoundaries(), FairDbResultSet::operator>>(), and FairDbRollbackDates::Set().
Bool_t FairDb::NotGlobalSeqNo (UInt_t seqNo)
Definition at line 122 of file FairDb.cxx.
View newest version in sPHENIX GitHub at line 122 of file FairDb.cxx
References kMAXLOCALSEQNO.
void FairDb::SetTimeGate (const std::string & tableName, Int_t timeGate)
Definition at line 108 of file FairDb.cxx.
View newest version in sPHENIX GitHub at line 108 of file FairDb.cxx
Referenced by ClassImp(), and GetTimeGate().