EIC Software: FW::PrintHits Class Reference
FW::PrintHits Class Reference
Print hits within some geometric region-of-interest.
#include <fun4all_acts/blob/master/Examples/Algorithms/Printers/ACTFW/Printers/PrintHits.hpp>
Classes
struct Config
Public Member Functions
PrintHits (const Config &cfg, Acts::Logging::Level level)
ProcessCode execute (const AlgorithmContext &ctx) const
Public Member Functions inherited from FW::BareAlgorithm
BareAlgorithm (std::string name, Acts::Logging::Level level=Acts::Logging::INFO)
std::string name () const finaloverride
The algorithm name.
Private Attributes
Config m_cfg
Additional Inherited Members
Protected Member Functions inherited from FW::BareAlgorithm
const Acts::Logger & logger () const
Detailed Description
Print hits within some geometric region-of-interest.
Definition at line 19 of file PrintHits.hpp.
View newest version in sPHENIX GitHub at line 19 of file PrintHits.hpp
Constructor & Destructor Documentation
FW::PrintHits::PrintHits (const Config & cfg, Acts::Logging::Level level)
Definition at line 21 of file PrintHits.cpp.
View newest version in sPHENIX GitHub at line 21 of file PrintHits.cpp
Member Function Documentation
FW::ProcessCode FW::PrintHits::execute (const AlgorithmContext & context) const virtual
Execute the algorithm for one event.
This function must be implemented by subclasses.
Implements FW::BareAlgorithm.
Definition at line 25 of file PrintHits.cpp.
View newest version in sPHENIX GitHub at line 25 of file PrintHits.cpp
References ACTS_INFO, c, Acts::PlanarModuleCluster::digitizationCells(), FW::AlgorithmContext::eventStore, FW::WhiteBoard::get(), FW::makeRange(), p, FW::selectLayer(), FW::selectModule(), FW::selectVolume(), and SUCCESS.
Member Data Documentation
Config FW::PrintHits::m_cfg private
Definition at line 43 of file PrintHits.hpp.
View newest version in sPHENIX GitHub at line 43 of file PrintHits.hpp
The documentation for this class was generated from the following files:
fun4all_acts/blob/master/Examples/Algorithms/Printers/ACTFW/Printers/PrintHits.hpp
fun4all_acts/blob/master/Examples/Algorithms/Printers/ACTFW/Printers/PrintHits.cpp