EIC Software: eicsmear-jetexample/blob/master/src/extendedjetexample.cxx File Reference
extendedjetexample.cxx File Reference
#include "eicsmear/erhic/EventBase.h"
#include "eicsmear/erhic/EventPythia.h"
#include "eicsmear/erhic/Particle.h"
#include "eicsmear/smear/EventSmear.h"
#include "eicsmear/smear/EventS.h"
#include "eicsmear/smear/Smear.h"
#include "eicsmear/smear/ParticleMCS.h"
#include <TDatabasePDG.h>
#include <TFile.h>
#include <TChain.h>
#include <TH1.h>
#include <TH2.h>
#include <TCanvas.h>
#include <TLegend.h>
#include <TText.h>
#include <TStyle.h>
#include <vector>
#include <map>
#include "fastjet/ClusterSequence.hh"
#include "fastjet/PseudoJet.hh"
Functions
int main (int argc, char *argv[])
Function Documentation
int main (int argc, char * argv[])
Definition at line 42 of file extendedjetexample.cxx.
View newest version in sPHENIX GitHub at line 42 of file extendedjetexample.cxx
References kdfinder::abs(), Acts::UnitConstants::e, epsilon, Smear::ParticleMCS::GetE(), erhic::ParticleMCbase::GetE(), erhic::ParticleMCbase::GetEta(), Smear::Event::GetNTracks(), Smear::ParticleMCS::GetP(), erhic::ParticleMCbase::GetPdgCode(), Smear::ParticleMCS::GetPx(), erhic::ParticleMCbase::GetPx(), Smear::ParticleMCS::GetPy(), erhic::ParticleMCbase::GetPy(), Smear::ParticleMCS::GetPz(), erhic::ParticleMCbase::GetPz(), erhic::EventDis::GetQ2(), erhic::EventDis::GetQ2DoubleAngle(), erhic::ParticleMCbase::GetStatus(), Smear::Event::GetTrack(), erhic::EventMC::GetTrack(), erhic::EventDis::GetX(), erhic::EventDis::GetXDoubleAngle(), erhic::EventDis::GetY(), erhic::EventDis::GetYDoubleAngle(), Acts::UnitConstants::m, nevents, Acts::IntegrationTest::R, ran(), xmax, xmin, ymax, and ymin.