EIC Software: RungeKuttaRequest Class Reference
RungeKuttaRequest Class Reference
#include <EicRoot/blob/master/eic/htc/RungeKuttaRequest.h>
Private Member Functions
int kk (MgridSlice *slice, double z, double x[4], double k[4])
int serveRequest (double in[], double _q, double out[], int _repetition_flag)
Private Attributes
double z0
double h
RungeKutta * rk
int repetition_flag
double q
Friends
class TrKalmanNode
Detailed Description
Definition at line 35 of file RungeKuttaRequest.h.
View newest version in sPHENIX GitHub at line 35 of file RungeKuttaRequest.h
Member Function Documentation
int RungeKuttaRequest::kk (MgridSlice * slice, double z, double x[4], double k[4]) private
Definition at line 36 of file RungeKuttaRequest.cxx.
View newest version in sPHENIX GitHub at line 36 of file RungeKuttaRequest.cxx
References _LIGHT_SPEED_, _X_, _Y_, _Z_, Mgrid::getCartesianFieldValue(), h, MgridSlice::mGrid, MgridSlice::mLastUnboundCallStatus, q, repetition_flag, Mgrid::repetition_flag, SQR, and VZERO.
Referenced by jewel(), pytbhg(), pytbhq(), and serveRequest().
int RungeKuttaRequest::serveRequest (double in[], double _q, double out[], int _repetition_flag) private
Definition at line 79 of file RungeKuttaRequest.cxx.
View newest version in sPHENIX GitHub at line 79 of file RungeKuttaRequest.cxx
References RungeKutta::_order, _RK_ORDER_2_, _RK_ORDER_4_, _RK_ORDER_5_, a2, a3, a4, a5, a6, b21, b31, b32, b41, b42, b43, b51, b52, b53, b54, b61, b62, b63, b64, b65, c1, c2, c3, c4, c5, c6, h, k1, k2, kk(), RungeKutta::m1, RungeKutta::m2, RungeKutta::m3, RungeKutta::m4, RungeKutta::m5, RungeKutta::m6, q, repetition_flag, rk, s1, s2, s3, s4, s5, s6, and z0.
Referenced by TrKalmanNode::PerformRungeKuttaStep().
Friends And Related Function Documentation
friend class TrKalmanNode friend
Definition at line 36 of file RungeKuttaRequest.h.
View newest version in sPHENIX GitHub at line 36 of file RungeKuttaRequest.h
Member Data Documentation
double RungeKuttaRequest::h private
Definition at line 44 of file RungeKuttaRequest.h.
View newest version in sPHENIX GitHub at line 44 of file RungeKuttaRequest.h
Referenced by kk(), TrKalmanNode::PerformRungeKuttaStep(), and serveRequest().
double RungeKuttaRequest::q private
Definition at line 51 of file RungeKuttaRequest.h.
View newest version in sPHENIX GitHub at line 51 of file RungeKuttaRequest.h
Referenced by kk(), and serveRequest().
int RungeKuttaRequest::repetition_flag private
Definition at line 48 of file RungeKuttaRequest.h.
View newest version in sPHENIX GitHub at line 48 of file RungeKuttaRequest.h
Referenced by kk(), and serveRequest().
RungeKutta* RungeKuttaRequest::rk private
Definition at line 45 of file RungeKuttaRequest.h.
View newest version in sPHENIX GitHub at line 45 of file RungeKuttaRequest.h
Referenced by TrKalmanNode::PerformRungeKuttaStep(), and serveRequest().
double RungeKuttaRequest::z0 private
Definition at line 44 of file RungeKuttaRequest.h.
View newest version in sPHENIX GitHub at line 44 of file RungeKuttaRequest.h
Referenced by TrKalmanNode::PerformRungeKuttaStep(), and serveRequest().
The documentation for this class was generated from the following files:
EicRoot/blob/master/eic/htc/RungeKuttaRequest.h
EicRoot/blob/master/eic/htc/RungeKuttaRequest.cxx