EIC Software: FairTimeStamp Class Reference
FairTimeStamp Class Reference
#include <EicRoot/blob/master/base/FairTimeStamp.h>
Public Member Functions
FairTimeStamp ()
FairTimeStamp (Double_t time)
FairTimeStamp (Double_t time, Double_t timeerror)
virtual ~FairTimeStamp ()
virtual Double_t GetTimeStamp () const
virtual Double_t GetTimeStampError () const
virtual FairLink GetEntryNr () const
virtual void SetTimeStamp (Double_t t)
virtual void SetTimeStampError (Double_t t)
virtual void SetEntryNr (FairLink entry)
virtual Int_t Compare (const TObject *obj) const
void Print (std::ostream &out=std::cout) const
virtual Bool_t IsSortable () const
virtual bool equal (FairTimeStamp *data)
Public Member Functions inherited from FairMultiLinkedData
FairMultiLinkedData ()
Default constructor.
FairMultiLinkedData (std::set< FairLink > links, Bool_t persistanceCheck=kTRUE)
Constructor.
FairMultiLinkedData (TString dataType, std::vector< Int_t > links, Int_t fileId=-1, Int_t evtId=-1, Bool_t persistanceCheck=kTRUE, Bool_t bypass=kFALSE, Float_t mult=1.0)
Constructor.
FairMultiLinkedData (Int_t dataType, std::vector< Int_t > links, Int_t fileId=-1, Int_t evtId=-1, Bool_t persistanceCheck=kTRUE, Bool_t bypass=kFALSE, Float_t mult=1.0)
Constructor.
virtual ~FairMultiLinkedData ()
virtual std::set< FairLink > GetLinks () const
returns stored links as FairLinks
virtual Int_t GetNLinks () const
returns the number of stored links
virtual FairLink GetLink (Int_t pos) const
returns the FairLink at the given position
virtual FairMultiLinkedData GetLinksWithType (Int_t type) const
Gives you a list of links which contain the given type.
TObject * GetData (FairLink &myLink)
Get the TObject the Link is pointing to.
virtual Int_t GetDefaultType ()
Bool_t GetPersistanceCheck ()
Returns the value of PersistanceCheck.
Int_t GetVerbose ()
Returns the verbosity level.
virtual void SetDefaultType (Int_t type)
virtual void SetPersistanceCheck (Bool_t check)
Controls if a persistance check of a link is done or not.
virtual void SetVerbose (Int_t level)
Sets the verbosity level.
virtual void SetLinks (FairMultiLinkedData links, Float_t mult=1.0)
Sets the links as vector of FairLink.
virtual void SetLink (FairLink link, Bool_t bypass=kFALSE, Float_t mult=1.0)
Sets the Links with a single FairLink.
virtual void AddLinks (FairMultiLinkedData links, Float_t mult=1.0)
Adds a List of FairLinks (FairMultiLinkedData) to fLinks.
virtual void AddLink (FairLink link, Bool_t bypass=kFALSE, Float_t mult=1.0)
Adds a FairLink link at the end of fLinks. If multi is kTRUE a link is allowed more than once otherwise it is stored only once.
virtual void InsertLink (FairLink link)
Inserts a link into the list of links without persistance checking.
virtual void AddAllWeights (Double_t weight)
Adds weight to all Links.
virtual void SetAllWeights (Double_t weight)
Sets a common weight for Links.
virtual void MultiplyAllWeights (Double_t weight)
Multiplies all Links with weight.
virtual Bool_t IsLinkInList (FairLink link)
Test if a given link is in fLinks.
virtual Bool_t IsLinkInList (Int_t type, Int_t index)
Same as IsLinkInList(FairLink) just with type and index given separately.
virtual Int_t LinkPosInList (FairLink link)
returns position of link in fLinks. If it is not in the list -1 is returned
virtual Int_t LinkPosInList (Int_t type, Int_t index)
Same as LinkPosInList(FairLink)
virtual void DeleteLink (FairLink link)
Deletes a link ouf of fLinks.
virtual void DeleteLink (Int_t type, Int_t index)
Deletes a link ouf of fLinks.
virtual void Reset ()
virtual void ResetLinks ()
Clears fLinks.
void Print (std::ostream &out=std::cout) const
Output.
Protected Member Functions
ClassDef (FairTimeStamp, 2)
indicates where the data is stored in the branch
Protected Member Functions inherited from FairMultiLinkedData
virtual void SimpleAddLinks (Int_t fileId, Int_t evtId, Int_t dataType, std::vector< Int_t > links, Bool_t bypass, Float_t mult)
ClassDef (FairMultiLinkedData, 3)
Protected Attributes
Double_t fTimeStamp
Double_t fTimeStampError
FairLink fEntryNr
Protected Attributes inherited from FairMultiLinkedData
std::set< FairLink > fLinks
Bool_t fPersistanceCheck
Int_t fVerbose
Int_t fDefaultType
Friends
std::ostream & operator<< (std::ostream &out, const FairTimeStamp &link)
Detailed Description
Base class for Time stamp information Aug. 2010
Author
M.Al-Turany m.al-.nosp@m.tura.nosp@m.ny@gs.nosp@m.i.de
Definition at line 9 of file FairTimeStamp.h.
View newest version in sPHENIX GitHub at line 9 of file FairTimeStamp.h
Constructor & Destructor Documentation
FairTimeStamp::FairTimeStamp ()
Default constructor
Definition at line 4 of file FairTimeStamp.cxx.
View newest version in sPHENIX GitHub at line 4 of file FairTimeStamp.cxx
FairTimeStamp::FairTimeStamp (Double_t time)
Constructor with time
Definition at line 12 of file FairTimeStamp.cxx.
View newest version in sPHENIX GitHub at line 12 of file FairTimeStamp.cxx
FairTimeStamp::FairTimeStamp (Double_t time, Double_t timeerror)
Constructor with time and time error
Definition at line 20 of file FairTimeStamp.cxx.
View newest version in sPHENIX GitHub at line 20 of file FairTimeStamp.cxx
FairTimeStamp::~FairTimeStamp () virtual
Destructor
Definition at line 28 of file FairTimeStamp.cxx.
View newest version in sPHENIX GitHub at line 28 of file FairTimeStamp.cxx
Member Function Documentation
FairTimeStamp::ClassDef (FairTimeStamp , 2) protected
indicates where the data is stored in the branch
virtual Int_t FairTimeStamp::Compare (const TObject * obj) const inline virtual
Definition at line 29 of file FairTimeStamp.h.
View newest version in sPHENIX GitHub at line 29 of file FairTimeStamp.h
References fTimeStamp, fTimeStampError, GetTimeStamp(), and GetTimeStampError().
virtual bool FairTimeStamp::equal (FairTimeStamp * data) inline virtual
Definition at line 45 of file FairTimeStamp.h.
View newest version in sPHENIX GitHub at line 45 of file FairTimeStamp.h
References fTimeStamp, fTimeStampError, GetTimeStamp(), and GetTimeStampError().
Referenced by FairWriteoutBuffer::FillDataToDeadTimeMap().
virtual FairLink FairTimeStamp::GetEntryNr () const inline virtual
Definition at line 24 of file FairTimeStamp.h.
View newest version in sPHENIX GitHub at line 24 of file FairTimeStamp.h
References fEntryNr.
virtual Double_t FairTimeStamp::GetTimeStamp () const inline virtual
Accessors
Definition at line 22 of file FairTimeStamp.h.
View newest version in sPHENIX GitHub at line 22 of file FairTimeStamp.h
References fTimeStamp.
Referenced by PndTrackCand::CalcTimeStamp(), StopTime::Call(), TimeGap::Call(), Compare(), equal(), FairRingSorterTask::Exec(), FairTSBufferFunctional::GetData(), FairTimeStampPointDraw::GetValue(), PndTrack::PndTrack(), Print(), FairWriteoutBuffer::PrintData(), and FairWriteoutBuffer::PrintStartTimeMap().
virtual Double_t FairTimeStamp::GetTimeStampError () const inline virtual
Definition at line 23 of file FairTimeStamp.h.
View newest version in sPHENIX GitHub at line 23 of file FairTimeStamp.h
References fTimeStampError.
Referenced by PndTrackCand::CalcTimeStamp(), Compare(), equal(), PndTrack::PndTrack(), and Print().
virtual Bool_t FairTimeStamp::IsSortable () const inline virtual
Definition at line 42 of file FairTimeStamp.h.
View newest version in sPHENIX GitHub at line 42 of file FairTimeStamp.h
void FairTimeStamp::Print (std::ostream & out = std::cout) const
Definition at line 34 of file FairTimeStamp.cxx.
View newest version in sPHENIX GitHub at line 34 of file FairTimeStamp.cxx
References fEntryNr, GetTimeStamp(), GetTimeStampError(), and FairMultiLinkedData::Print().
Referenced by FairRingSorter::AddElement(), FairRingSorterTask::Exec(), and FairWriteoutBuffer::FillDataToDeadTimeMap().
virtual void FairTimeStamp::SetEntryNr (FairLink entry) inline virtual
Definition at line 28 of file FairTimeStamp.h.
View newest version in sPHENIX GitHub at line 28 of file FairTimeStamp.h
References fEntryNr.
Referenced by FairRingSorterTask::Exec().
virtual void FairTimeStamp::SetTimeStamp (Double_t t) inline virtual
Modifiers
Definition at line 26 of file FairTimeStamp.h.
View newest version in sPHENIX GitHub at line 26 of file FairTimeStamp.h
References fTimeStamp, and t.
Referenced by PndTrackCand::CalcTimeStamp(), and PndTrack::PndTrack().
virtual void FairTimeStamp::SetTimeStampError (Double_t t) inline virtual
Definition at line 27 of file FairTimeStamp.h.
View newest version in sPHENIX GitHub at line 27 of file FairTimeStamp.h
References fTimeStampError, and t.
Referenced by PndTrackCand::CalcTimeStamp(), and PndTrack::PndTrack().
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & out, const FairTimeStamp & link) friend
Definition at line 49 of file FairTimeStamp.h.
View newest version in sPHENIX GitHub at line 49 of file FairTimeStamp.h
Member Data Documentation
FairLink FairTimeStamp::fEntryNr protected
Error on time stamp
Definition at line 58 of file FairTimeStamp.h.
View newest version in sPHENIX GitHub at line 58 of file FairTimeStamp.h
Referenced by GetEntryNr(), Print(), and SetEntryNr().
Double_t FairTimeStamp::fTimeStamp protected
Definition at line 56 of file FairTimeStamp.h.
View newest version in sPHENIX GitHub at line 56 of file FairTimeStamp.h
Referenced by Compare(), equal(), GetTimeStamp(), and SetTimeStamp().
Double_t FairTimeStamp::fTimeStampError protected
Time of digit or Hit [ns]
Definition at line 57 of file FairTimeStamp.h.
View newest version in sPHENIX GitHub at line 57 of file FairTimeStamp.h
Referenced by Compare(), equal(), GetTimeStampError(), and SetTimeStampError().
The documentation for this class was generated from the following files:
EicRoot/blob/master/base/FairTimeStamp.h
EicRoot/blob/master/base/FairTimeStamp.cxx