EIC Software: Acts::SingleFreeParameters< ChargePolicy > Class Template Reference
Acts::SingleFreeParameters< ChargePolicy > Class Template Reference
Container class for free parameters.
#include <fun4all_acts/blob/master/Core/include/Acts/EventData/SingleFreeParameters.hpp>
Public Types
using CovMatrix_t = FreeSymMatrix
Public Member Functions
~SingleFreeParameters ()=default
Default virtual destructor.
template<typename T = ChargePolicy, std::enable_if_t< std::is_same< T, ChargedPolicy >::value, int > = 0>
SingleFreeParameters (std::optional< CovMatrix_t > cov, const FreeVector &parValues)
Standard constructor for track parameters of charged particles.
template<typename T = ChargePolicy, std::enable_if_t< std::is_same< T, NeutralPolicy >::value, int > = 0>
SingleFreeParameters (std::optional< CovMatrix_t > cov, const FreeVector &parValues)
Standard constructor for track parameters of neutral particles.
SingleFreeParameters
< ChargePolicy > & operator= (const SingleFreeParameters< ChargePolicy > &rhs)
Copy assignment operator.
SingleFreeParameters
< ChargePolicy > & operator= (SingleFreeParameters< ChargePolicy > &&rhs)
Move assignment operator.
SingleFreeParameters (const SingleFreeParameters< ChargePolicy > &copy)
Default copy constructor.
SingleFreeParameters (SingleFreeParameters< ChargePolicy > &&copy)
Default move constructor.
FreeVector parameters () const
Access all parameters.
Detailed Description
template<class ChargePolicy>
class Acts::SingleFreeParameters< ChargePolicy >
Container class for free parameters.
This is a base class for neutral and charged free parameters. All parameters and the corresponding covariance matrix is stored in global coordinates. It is assumed that the order of the parameters (and thereby the order of the entries of the covariance as well) is given as (position_x, position_y, position_z, time, direction_x, direction_y, direction_z, charge / |momentum|).
Template Parameters
ChargePolicy Parameter that describes if the particle is charged or neutral
Note
It is assumed that a charged particle has a charge of +/-1
Definition at line 33 of file SingleFreeParameters.hpp.
View newest version in sPHENIX GitHub at line 33 of file SingleFreeParameters.hpp
Member Typedef Documentation
template<class ChargePolicy> using Acts::SingleFreeParameters< ChargePolicy >::CovMatrix_t = FreeSymMatrix
Public typedefs Type of covariance matrix
Definition at line 42 of file SingleFreeParameters.hpp.
View newest version in sPHENIX GitHub at line 42 of file SingleFreeParameters.hpp
Constructor & Destructor Documentation
template<class ChargePolicy> Acts::SingleFreeParameters< ChargePolicy >::~SingleFreeParameters () default
Default virtual destructor.
template<class ChargePolicy> template<typename T = ChargePolicy, std::enable_if_t< std::is_same< T, ChargedPolicy >::value, int > = 0> Acts::SingleFreeParameters< ChargePolicy >::SingleFreeParameters (std::optional< CovMatrix_t > cov, const FreeVector & parValues) inline
Standard constructor for track parameters of charged particles.
Template Parameters
T Type of the charge policy (ChargedPolicy)
Parameters
[in] cov The covariance matrix
[in] parValues Vector with parameter values
Definition at line 54 of file SingleFreeParameters.hpp.
View newest version in sPHENIX GitHub at line 54 of file SingleFreeParameters.hpp
template<class ChargePolicy> template<typename T = ChargePolicy, std::enable_if_t< std::is_same< T, NeutralPolicy >::value, int > = 0> Acts::SingleFreeParameters< ChargePolicy >::SingleFreeParameters (std::optional< CovMatrix_t > cov, const FreeVector & parValues) inline
Standard constructor for track parameters of neutral particles.
Template Parameters
T Type of the charge policy (NeutralPolicy)
Parameters
[in] cov The covariance matrix
[in] parValues Vector with parameter values
Definition at line 67 of file SingleFreeParameters.hpp.
View newest version in sPHENIX GitHub at line 67 of file SingleFreeParameters.hpp
template<class ChargePolicy> Acts::SingleFreeParameters< ChargePolicy >::SingleFreeParameters (const SingleFreeParameters< ChargePolicy > & copy) inline
Default copy constructor.
Parameters
[in] copy The object to copy from
Definition at line 108 of file SingleFreeParameters.hpp.
View newest version in sPHENIX GitHub at line 108 of file SingleFreeParameters.hpp
template<class ChargePolicy> Acts::SingleFreeParameters< ChargePolicy >::SingleFreeParameters (SingleFreeParameters< ChargePolicy > && copy) inline
Default move constructor.
Parameters
[in] copy The object to move from
Definition at line 116 of file SingleFreeParameters.hpp.
View newest version in sPHENIX GitHub at line 116 of file SingleFreeParameters.hpp
References Acts::forward, and Acts::SingleFreeParameters< ChargePolicy >::operator=().
Member Function Documentation
template<class ChargePolicy> SingleFreeParameters<ChargePolicy>& Acts::SingleFreeParameters< ChargePolicy >::operator= (const SingleFreeParameters< ChargePolicy > & rhs) inline
Copy assignment operator.
Parameters
[in] rhs Object to be copied
Returns
The assigned-to object *this
Definition at line 78 of file SingleFreeParameters.hpp.
View newest version in sPHENIX GitHub at line 78 of file SingleFreeParameters.hpp
Referenced by Acts::SingleFreeParameters< ChargePolicy >::SingleFreeParameters().
template<class ChargePolicy> SingleFreeParameters<ChargePolicy>& Acts::SingleFreeParameters< ChargePolicy >::operator= (SingleFreeParameters< ChargePolicy > && rhs) inline
Move assignment operator.
Parameters
[in] rhs object to be movied into *this
Returns
The assigned-to object *this
Definition at line 94 of file SingleFreeParameters.hpp.
View newest version in sPHENIX GitHub at line 94 of file SingleFreeParameters.hpp
template<class ChargePolicy> FreeVector Acts::SingleFreeParameters< ChargePolicy >::parameters () const inline
Access all parameters.
Returns
Vector containing the store parameters
Definition at line 124 of file SingleFreeParameters.hpp.
View newest version in sPHENIX GitHub at line 124 of file SingleFreeParameters.hpp
Referenced by Acts::Test::BOOST_AUTO_TEST_CASE().
The documentation for this class was generated from the following file:
fun4all_acts/blob/master/Core/include/Acts/EventData/SingleFreeParameters.hpp