EIC Software: fun4all_GenFit/blob/master/test/fitterTests/main.cc File Reference
main.cc File Reference
#include <iostream>
#include <execinfo.h>
#include <signal.h>
#include <stdlib.h>
#include <AbsFinitePlane.h>
#include <AbsFitterInfo.h>
#include <AbsMeasurement.h>
#include <AbsTrackRep.h>
#include <ConstField.h>
#include <DetPlane.h>
#include <Exception.h>
#include <FieldManager.h>
#include <KalmanFittedStateOnPlane.h>
#include <AbsKalmanFitter.h>
#include <KalmanFitter.h>
#include <KalmanFitterRefTrack.h>
#include <KalmanFitterInfo.h>
#include <KalmanFitStatus.h>
#include <DAF.h>
#include <GFGbl.h>
#include <MeasuredStateOnPlane.h>
#include <MeasurementOnPlane.h>
#include <FullMeasurement.h>
#include <PlanarMeasurement.h>
#include <ProlateSpacepointMeasurement.h>
#include <RectangularFinitePlane.h>
#include <ReferenceStateOnPlane.h>
#include <SharedPlanePtr.h>
#include <SpacepointMeasurement.h>
#include <StateOnPlane.h>
#include <Tools.h>
#include <TrackCand.h>
#include <TrackCandHit.h>
#include <Track.h>
#include <TrackPoint.h>
#include <WireMeasurement.h>
#include <WirePointMeasurement.h>
#include <MaterialEffects.h>
#include <RKTools.h>
#include <RKTrackRep.h>
#include <StepLimits.h>
#include <TGeoMaterialInterface.h>
#include <EventDisplay.h>
#include <HelixTrackModel.h>
#include <MeasurementCreator.h>
#include <TApplication.h>
#include <TCanvas.h>
#include <TDatabasePDG.h>
#include <TEveManager.h>
#include <TGeoManager.h>
#include <TH1D.h>
#include <TRandom.h>
#include <TStyle.h>
#include <TVector3.h>
#include <vector>
#include <TROOT.h>
#include <TFile.h>
#include <TTree.h>
#include <TMath.h>
#include <TString.h>
#include <memory>
Macros
#define CALLGRIND_START_INSTRUMENTATION
#define CALLGRIND_STOP_INSTRUMENTATION
#define CALLGRIND_DUMP_STATS
Functions
void handler (int sig)
int randomPdg ()
int randomSign ()
int main ()
Macro Definition Documentation
#define CALLGRIND_DUMP_STATS
Definition at line 130 of file main.cc.
View newest version in sPHENIX GitHub at line 130 of file main.cc
Referenced by main().
#define CALLGRIND_START_INSTRUMENTATION
Definition at line 128 of file main.cc.
View newest version in sPHENIX GitHub at line 128 of file main.cc
Referenced by main().
#define CALLGRIND_STOP_INSTRUMENTATION
Definition at line 129 of file main.cc.
View newest version in sPHENIX GitHub at line 129 of file main.cc
Referenced by main().
Function Documentation
void handler (int sig)
Definition at line 72 of file main.cc.
View newest version in sPHENIX GitHub at line 72 of file main.cc
References exit().
Referenced by Acts::Sycl::createSeedsForGroupSycl(), and main().
int main (void)
Definition at line 133 of file main.cc.
View newest version in sPHENIX GitHub at line 133 of file main.cc
References genfit::EventDisplay::addEvent(), genfit::Track::addTrackRep(), c1, c2, c3, CALLGRIND_DUMP_STATS, CALLGRIND_START_INSTRUMENTATION, CALLGRIND_STOP_INSTRUMENTATION, charge, genfit::Track::checkConsistency(), genfit::AbsTrackRep::clone(), Acts::Test::cov, genfit::MeasurementCreator::create(), genfit::DafRef, genfit::DafSimple, Acts::Test::debug, Acts::UnitConstants::e, genfit::AbsTrackRep::extrapolateToPlane(), genfit::AbsTrackRep::get6DStateCov(), genfit::Track::getCardinalRep(), genfit::MeasuredStateOnPlane::getCov(), genfit::Track::getFitStatus(), genfit::Track::getFittedState(), genfit::TrackPoint::getFitterInfo(), genfit::MaterialEffects::getInstance(), genfit::EventDisplay::getInstance(), genfit::FieldManager::getInstance(), genfit::Track::getNumPointsWithMeasurement(), genfit::StateOnPlane::getPlane(), genfit::Track::getPointWithMeasurement(), genfit::Track::getPointWithMeasurementAndFitterInfo(), genfit::FitStatus::getPruneFlags(), genfit::AbsKalmanFitter::getPVal(), genfit::FitStatus::getPVal(), genfit::StateOnPlane::getState(), genfit::Track::getTOF(), genfit::Track::getTrackLen(), handler(), genfit::TrackPoint::hasFitterInfo(), genfit::MaterialEffects::init(), genfit::FieldManager::init(), genfit::Track::insertPoint(), genfit::FitStatus::isFitConverged(), genfit::Track::mergeTrack(), charm_jet_coverage::mom, momentum, nEvents, genfit::EventDisplay::open(), pdg, pos(), genfit::PruneFlags::Print(), genfit::MeasuredStateOnPlane::Print(), genfit::FitStatus::Print(), genfit::Track::Print(), genfit::AbsFitter::processTrack(), genfit::KalmanFitter::processTrackWithRep(), genfit::Track::prune(), genfit::RefKalman, genfit::EventDisplay::reset(), genfit::MeasurementCreator::setDebug(), genfit::MeasurementCreator::setIdealLRResolution(), genfit::MeasurementCreator::setMaxDrift(), genfit::AbsKalmanFitter::setMaxIterations(), genfit::MeasurementCreator::setMinDrift(), genfit::AbsKalmanFitter::setMultipleMeasurementHandling(), genfit::MaterialEffects::setNoEffects(), genfit::MeasurementCreator::setNSuperLayer(), genfit::EventDisplay::setOptions(), genfit::MeasurementCreator::setOutlierProb(), genfit::MeasurementCreator::setOutlierRange(), genfit::MeasurementCreator::setPhiDetPlane(), genfit::AbsTrackRep::setPosMomCov(), genfit::MeasurementCreator::setResolution(), genfit::MeasurementCreator::setResolutionWire(), genfit::MeasurementCreator::setSkewAngle(), genfit::MeasurementCreator::setThetaDetPlane(), genfit::MeasurementCreator::setTrackModel(), genfit::MeasurementCreator::setUseSkew(), genfit::MeasurementCreator::setWireDir(), sign(), genfit::SimpleKalman, theta(), genfit::unweightedClosestToPredictionWire, genfit::FieldManager::useCache(), genfit::weightedClosestToPrediction, and genfit::Exception::what().
int randomPdg ()
Definition at line 85 of file main.cc.
View newest version in sPHENIX GitHub at line 85 of file main.cc
References pdg.
Referenced by checkErrorPropagation(), checkExtrapolateBy(), checkExtrapolateToCylinder(), checkExtrapolateToLine(), checkExtrapolateToPoint(), checkExtrapolateToSphere(), checkSetGetPosMom(), checkStopAtBoundary(), compareForthBackExtrapolation(), and compareForthBackJacNoise().
int randomSign ()
Definition at line 111 of file main.cc.
View newest version in sPHENIX GitHub at line 111 of file main.cc
Referenced by checkErrorPropagation(), checkExtrapolateBy(), checkExtrapolateToCylinder(), checkExtrapolateToLine(), checkExtrapolateToPoint(), checkExtrapolateToSphere(), checkSetGetPosMom(), checkStopAtBoundary(), compareForthBackExtrapolation(), and compareForthBackJacNoise().