EIC Software: vc2020_03_20 Class Reference
vc2020_03_20 Class Reference
#include <EicToyModel/blob/master/include/vc2020_03_20.h>
Public Member Functions
vc2020_03_20 (void)
~vc2020_03_20 ()
void CreateGeometry (void)
bool ConfigurableCrossingAngle (void) const
Public Member Functions inherited from EtmVacuumChamber
EtmVacuumChamber (void)
~EtmVacuumChamber ()
void DrawMe (void)
void SetHadronBeamPipeOpening (double value)
double GetHadronBeamPipeOpening (void) const
double GetRadialSize (double z, double phi)
TGeoManager * GetWorld (void) const
void CheckGeometry (bool force=false)
void Export (const char *fname)
virtual double FixedCrossingAngle (void) const
bool CrossingAngleResetPossible (double value) const
G4VSolid * CutThisSolid (G4VSolid *solid, double dz)
void StoreGDMLdump (void)
*, const std::vector<TVector2> &polygon*/);
Additional Inherited Members
Protected Attributes inherited from EtmVacuumChamber
TGeoManager * mTGeoModel
double mHadronBeamPipeOpening
double mActualCrossingAngle
Detailed Description
Definition at line 7 of file vc2020_03_20.h.
View newest version in sPHENIX GitHub at line 7 of file vc2020_03_20.h
Constructor & Destructor Documentation
vc2020_03_20::vc2020_03_20 (void)
Definition at line 43 of file vc2020_03_20.cc.
View newest version in sPHENIX GitHub at line 43 of file vc2020_03_20.cc
References _HADRON_PIPE_OPENING_DEFAULT_, and EtmVacuumChamber::mHadronBeamPipeOpening.
vc2020_03_20::~vc2020_03_20 () inline
Definition at line 10 of file vc2020_03_20.h.
View newest version in sPHENIX GitHub at line 10 of file vc2020_03_20.h
Member Function Documentation
bool vc2020_03_20::ConfigurableCrossingAngle (void) const inline virtual
Implements EtmVacuumChamber.
Definition at line 13 of file vc2020_03_20.h.
View newest version in sPHENIX GitHub at line 13 of file vc2020_03_20.h
void vc2020_03_20::CreateGeometry (void) virtual
Implements EtmVacuumChamber.
Definition at line 65 of file vc2020_03_20.cc.
View newest version in sPHENIX GitHub at line 65 of file vc2020_03_20.cc
References _0_127_, _ACCELERATOR_VACUUM_, _BERYLLIUM_PIPE_INNER_DIAMETER_, _BERYLLIUM_PIPE_OUTER_DIAMETER_, _ESIDE_ALUMINUM_PIPE_HEIGHT_, _ESIDE_ALUMINUM_PIPE_USLOPE_, _ESIDE_BERYLLIUM_PIPE_LENGTH_, _HADRON_PIPE_OPENING_DELTA_, _HSIDE_ALUMINUM_PIPE_DIAMETER_, _HSIDE_BERYLLIUM_PIPE_LENGTH_, dz, eic, EtmVacuumChamber::GetWorld(), Acts::Test::green, EicToyModel::Instance(), G4BARRELHCAL::length, M_PI, EtmVacuumChamber::mHadronBeamPipeOpening, rmax(), rw, Acts::Test::world, z1, and z2.
The documentation for this class was generated from the following files:
EicToyModel/blob/master/include/vc2020_03_20.h
EicToyModel/blob/master/source/vc2020_03_20.cc