EIC Software: GFTrackCand Class Reference
GFTrackCand Class Reference
Genfit
Track candidate – a list of cluster indices.
#include <EicRoot/blob/master/genfit/GFTrackCand.h>
Public Member Functions
GFTrackCand ()
~GFTrackCand ()
void getHit (unsigned int i, unsigned int &detId, unsigned int &hitId) const
Get detector ID and cluster index (hitId) for hit number i.
void getHit (unsigned int i, unsigned int &detId, unsigned int &hitId, double &rho) const
Get detector ID and cluster index (hitId) for hit number i with ordering parameter rho.
void getHitWithPlane (unsigned int i, unsigned int &detId, unsigned int &hitId, unsigned int &planeId) const
Get detector ID and cluster index (hitId) for hit number i with plane id.
unsigned int getNHits () const
double getCurv () const
double getDip () const
std::vector< unsigned int > getHitIDs (int detId=-1) const
std::vector< unsigned int > GetHitIDs (int detId=-1) const
std::vector< unsigned int > getDetIDs () const
std::vector< unsigned int > GetDetIDs () const
std::vector< double > getRhos () const
std::vector< double > GetRhos () const
std::set< unsigned int > getUniqueDetIDs () const
int getMcTrackId () const
get the MCT track id, for MC simulations - def. value -1
TVector3 getPosSeed () const
get the seed value for track: pos. Identical to the first 3 components of getStateSeed
TVector3 getMomSeed () const
get the seed value for track: mom. Identical to the last 3 components of getStateSeed
TVector3 getDirSeed () const
get the seed value for track: direction
double getQoverPseed () const
get the seed value for track: qoverp
TMatrixD getStateSeed () const
TMatrixD getCovSeed () const
double getChargeSeed () const
int getPdgCode () const
get the PDG code
void addHit (unsigned int detId, unsigned int hitId, double rho=0., unsigned int planeId=0)
void setCurv (double c)
void setDip (double d)
void setMcTrackId (int i)
set the MCT track id, for MC simulations
bool hitInTrack (unsigned int detId, unsigned int hitId) const
Test if hit already is part of this track candidate.
void setComplTrackSeed (const TVector3 &pos, const TVector3 &mom, const int pdgCode, TVector3 posError=TVector3(1.0, 1.0, 1.0), TVector3 dirError=TVector3(1.0, 1.0, 1.0))
set the seed values for track: pos, momentum, pdgCode, pos error, momentum error (errors are optional and will be set to 1,1,1 if not given)
void setPdgCode (int pdgCode)
set a particle hypothesis in form of a PDG code. This will also set the charge attribute
void append (const GFTrackCand &)
void sortHits ()
sort the hits that were already added to the trackCand using the rho parameter. After this function was called rho will determine the order of propagation not the order of the original addHit calls
void sortHits (std::vector< unsigned int > indices)
void reset ()
void Print (const Option_t *="") const
write the content of all private attributes to the terminal
void set6DSeed (const TMatrixD &state6D, const double charge, TMatrixD cov6D=-1.0 *TMatrixD(TMatrixD::kUnit, TMatrixD(6, 6)))
sets the state to seed the track fitting. State has to be a TMatrixD(6,1). First 3 elements are the staring postion second 3 elements the starting momentum. Everything in global coordinates charge is the charge hypotheses of the particle charge ATTENTION: If you set the cov6D covariance matrix of the state remember that there ar VARIANCES not STANDARD DEVIATIONS on the diagonal
void set6DSeedAndPdgCode (const TMatrixD &state6D, const int pdgCode, TMatrixD cov6D=-1.0 *TMatrixD(TMatrixD::kUnit, TMatrixD(6, 6)))
This function works the same as set6DSeed but instead of a charge hypothesis you can set a pdg code which will set the charge automatically ATTENTION: If you set the cov6D covariance matrix of the state remember that there are VARIANCES not standard deviations on the diagonal.
void setPosMomSeed (const TVector3 &pos, const TVector3 &mom, const double charge, TMatrixD cov6D=-1.0 *TMatrixD(TMatrixD::kUnit, TMatrixD(6, 6)))
sets the state to seed the track fitting. State has to be a TVector3 for position and a TVector3 for momentum. Everything in global coordinates charge is the charge hypotheses of the particle charge ATTENTION: If you set the cov6D covariance matrix of the state remember that there ar VARIANCES not STANDARD DEVIATIONS on the diagonal
void setPosMomSeedAndPdgCode (const TVector3 &pos, const TVector3 &mom, const int pdgCode, TMatrixD cov6D=-1.0 *TMatrixD(TMatrixD::kUnit, TMatrixD(6, 6)))
This function works the same as setPosMomSeed but instead of a charge hypothesis you can set a pdg code which will set the charge automatically ATTENTION: If you set the cov6D covariance matrix of the state remember that there are VARIANCES not standard deviations on the diagonal.
Private Attributes
std::vector< unsigned int > fDetId
std::vector< unsigned int > fHitId
std::vector< unsigned int > fPlaneId
std::vector< double > fRho
double fCurv
double fDip
int fMcTrackId
int fPdg
TMatrixD fState6D
TMatrixD fCov6D
double fQ
Friends
bool operator== (const GFTrackCand &lhs, const GFTrackCand &rhs)
Detailed Description
Track candidate – a list of cluster indices.
Author
Christian Höppner (Technische Universität München, original author)
Sebastian Neubert (Technische Universität München, original author)
Moritz Nadler (maintainer during 2012) The main task of the GFTrackCand object is to store a list of indices to cluster objects. Each cluster in the Track is identified by it's detector ID and it's index in the corresponding TClonesArray. Also there is a ordering parameter rho, to order hits. Optionally, plane indices for the hits can be stored (most importantly for fitting with the GFDaf). This information is used by the RecoHitFactory to automatically load RecoHits into a Track. Through this it is possible to define Tracks over an arbitrary number of different detectors.
In addition GFTrackCand offers members to store starting values for the fit. The starting values (seeds) for the fit are stored as a 6D state (x,y,z,px,py,pz) and its corresponding 6x6 covariance matrix. All seed getter and setter manipulate these two members but the user can chose using TVector3 or TMatrixD to get/set the seed state. However this information is not automatically used in Genfit. But a pointer to a GFTrackCand can be passed to the a RKTrackRep constructor to make use of this information without manually extracting it from the GFTRackCand object.
See Also
RecoHitFactory
Definition at line 63 of file GFTrackCand.h.
View newest version in sPHENIX GitHub at line 63 of file GFTrackCand.h
Constructor & Destructor Documentation
GFTrackCand::GFTrackCand ()
GFTrackCand::~GFTrackCand ()
Definition at line 30 of file GFTrackCand.cxx.
View newest version in sPHENIX GitHub at line 30 of file GFTrackCand.cxx
Member Function Documentation
void GFTrackCand::addHit (unsigned int detId, unsigned int hitId, double rho = 0., unsigned int planeId = 0)
Definition at line 33 of file GFTrackCand.cxx.
View newest version in sPHENIX GitHub at line 33 of file GFTrackCand.cxx
References fDetId, fHitId, fPlaneId, and fRho.
Referenced by GFTrack::addHit(), append(), and PndTrackCand2GenfitTrackCand().
void GFTrackCand::append (const GFTrackCand & rhs)
Definition at line 112 of file GFTrackCand.cxx.
View newest version in sPHENIX GitHub at line 112 of file GFTrackCand.cxx
References addHit(), getHit(), and getNHits().
double GFTrackCand::getChargeSeed () const inline
Definition at line 163 of file GFTrackCand.h.
View newest version in sPHENIX GitHub at line 163 of file GFTrackCand.h
References fQ.
Referenced by GenfitTrackCand2PndTrackCand().
TMatrixD GFTrackCand::getCovSeed () const inline
returns the 6D covariance matrix of the seed state; should be in global coordinates
Definition at line 160 of file GFTrackCand.h.
View newest version in sPHENIX GitHub at line 160 of file GFTrackCand.h
References fCov6D.
Referenced by RKTrackRep::RKTrackRep().
double GFTrackCand::getCurv () const inline
Definition at line 106 of file GFTrackCand.h.
View newest version in sPHENIX GitHub at line 106 of file GFTrackCand.h
References fCurv.
std::vector<unsigned int> GFTrackCand::getDetIDs () const inline
Definition at line 115 of file GFTrackCand.h.
View newest version in sPHENIX GitHub at line 115 of file GFTrackCand.h
References fDetId.
std::vector<unsigned int> GFTrackCand::GetDetIDs () const inline
Definition at line 116 of file GFTrackCand.h.
View newest version in sPHENIX GitHub at line 116 of file GFTrackCand.h
References fDetId.
double GFTrackCand::getDip () const inline
Definition at line 109 of file GFTrackCand.h.
View newest version in sPHENIX GitHub at line 109 of file GFTrackCand.h
References fDip.
TVector3 GFTrackCand::getDirSeed () const inline
get the seed value for track: direction
Definition at line 143 of file GFTrackCand.h.
View newest version in sPHENIX GitHub at line 143 of file GFTrackCand.h
References fState6D, and p.
void GFTrackCand::getHit (unsigned int i, unsigned int & detId, unsigned int & hitId) const inline
Get detector ID and cluster index (hitId) for hit number i.
Definition at line 76 of file GFTrackCand.h.
View newest version in sPHENIX GitHub at line 76 of file GFTrackCand.h
References fDetId, fHitId, and getNHits().
Referenced by append(), GFRecoHitFactory::createMany(), GenfitTrackCand2PndTrackCand(), GFTrack::getResiduals(), and GFTrack::mergeHits().
void GFTrackCand::getHit (unsigned int i, unsigned int & detId, unsigned int & hitId, double & rho) const inline
Get detector ID and cluster index (hitId) for hit number i with ordering parameter rho.
Definition at line 85 of file GFTrackCand.h.
View newest version in sPHENIX GitHub at line 85 of file GFTrackCand.h
References fDetId, fHitId, fRho, and getNHits().
std::vector< unsigned int > GFTrackCand::getHitIDs (int detId = -1) const
Definition at line 42 of file GFTrackCand.cxx.
View newest version in sPHENIX GitHub at line 42 of file GFTrackCand.cxx
References fDetId, fHitId, and n.
std::vector< unsigned int > GFTrackCand::GetHitIDs (int detId = -1) const
Definition at line 57 of file GFTrackCand.cxx.
View newest version in sPHENIX GitHub at line 57 of file GFTrackCand.cxx
References fDetId, fHitId, and n.
void GFTrackCand::getHitWithPlane (unsigned int i, unsigned int & detId, unsigned int & hitId, unsigned int & planeId) const inline
Get detector ID and cluster index (hitId) for hit number i with plane id.
Definition at line 96 of file GFTrackCand.h.
View newest version in sPHENIX GitHub at line 96 of file GFTrackCand.h
References fDetId, fHitId, fPlaneId, and getNHits().
Referenced by GFTrack::getHitsByPlane().
int GFTrackCand::getMcTrackId () const inline
get the MCT track id, for MC simulations - def. value -1
Definition at line 131 of file GFTrackCand.h.
View newest version in sPHENIX GitHub at line 131 of file GFTrackCand.h
References fMcTrackId.
Referenced by PrimSelector::Exec(), and GenfitTrackCand2PndTrackCand().
TVector3 GFTrackCand::getMomSeed () const inline
get the seed value for track: mom. Identical to the last 3 components of getStateSeed
Definition at line 138 of file GFTrackCand.h.
View newest version in sPHENIX GitHub at line 138 of file GFTrackCand.h
References fState6D.
Referenced by GenfitTrackCand2PndTrackCand().
unsigned int GFTrackCand::getNHits () const inline
Definition at line 105 of file GFTrackCand.h.
View newest version in sPHENIX GitHub at line 105 of file GFTrackCand.h
References fDetId.
Referenced by append(), GFRecoHitFactory::createMany(), GFTrack::fillGeoTrack(), GenfitTrackCand2PndTrackCand(), getHit(), GFTrack::getHitsByPlane(), getHitWithPlane(), operator==(), GFTrack::sortHits(), and sortHits().
int GFTrackCand::getPdgCode () const inline
get the PDG code
Definition at line 167 of file GFTrackCand.h.
View newest version in sPHENIX GitHub at line 167 of file GFTrackCand.h
References fPdg.
Referenced by RKTrackRep::RKTrackRep().
TVector3 GFTrackCand::getPosSeed () const inline
get the seed value for track: pos. Identical to the first 3 components of getStateSeed
Definition at line 133 of file GFTrackCand.h.
View newest version in sPHENIX GitHub at line 133 of file GFTrackCand.h
References fState6D.
Referenced by GenfitTrackCand2PndTrackCand().
double GFTrackCand::getQoverPseed () const inline
get the seed value for track: qoverp
Definition at line 150 of file GFTrackCand.h.
View newest version in sPHENIX GitHub at line 150 of file GFTrackCand.h
References fQ, fState6D, and p.
std::vector<double> GFTrackCand::getRhos () const inline
Definition at line 117 of file GFTrackCand.h.
View newest version in sPHENIX GitHub at line 117 of file GFTrackCand.h
References fRho.
std::vector<double> GFTrackCand::GetRhos () const inline
Definition at line 118 of file GFTrackCand.h.
View newest version in sPHENIX GitHub at line 118 of file GFTrackCand.h
References fRho.
TMatrixD GFTrackCand::getStateSeed () const inline
returns the 6D seed state; should be in global coordinates
Definition at line 156 of file GFTrackCand.h.
View newest version in sPHENIX GitHub at line 156 of file GFTrackCand.h
References fState6D.
Referenced by RKTrackRep::RKTrackRep().
std::set<unsigned int> GFTrackCand::getUniqueDetIDs () const inline
Definition at line 122 of file GFTrackCand.h.
View newest version in sPHENIX GitHub at line 122 of file GFTrackCand.h
References fDetId.
bool GFTrackCand::hitInTrack (unsigned int detId, unsigned int hitId) const
Test if hit already is part of this track candidate.
Definition at line 78 of file GFTrackCand.cxx.
View newest version in sPHENIX GitHub at line 78 of file GFTrackCand.cxx
References fDetId, and fHitId.
void GFTrackCand::Print (const Option_t * option = "") const
write the content of all private attributes to the terminal
Definition at line 95 of file GFTrackCand.cxx.
View newest version in sPHENIX GitHub at line 95 of file GFTrackCand.cxx
References fCov6D, fDetId, fHitId, fMcTrackId, fPdg, fQ, fRho, and fState6D.
void GFTrackCand::reset ()
Definition at line 73 of file GFTrackCand.cxx.
View newest version in sPHENIX GitHub at line 73 of file GFTrackCand.cxx
References fDetId, and fHitId.
void GFTrackCand::set6DSeed (const TMatrixD & state6D, const double charge, TMatrixD cov6D = -1.0 * TMatrixD(TMatrixD::kUnit, TMatrixD(6, 6))) inline
sets the state to seed the track fitting. State has to be a TMatrixD(6,1). First 3 elements are the staring postion second 3 elements the starting momentum. Everything in global coordinates charge is the charge hypotheses of the particle charge ATTENTION: If you set the cov6D covariance matrix of the state remember that there ar VARIANCES not STANDARD DEVIATIONS on the diagonal
Definition at line 214 of file GFTrackCand.h.
View newest version in sPHENIX GitHub at line 214 of file GFTrackCand.h
References charge, fCov6D, fQ, and fState6D.
void GFTrackCand::set6DSeedAndPdgCode (const TMatrixD & state6D, const int pdgCode, TMatrixD cov6D = -1.0 * TMatrixD(TMatrixD::kUnit, TMatrixD(6, 6))) inline
This function works the same as set6DSeed but instead of a charge hypothesis you can set a pdg code which will set the charge automatically ATTENTION: If you set the cov6D covariance matrix of the state remember that there are VARIANCES not standard deviations on the diagonal.
Definition at line 222 of file GFTrackCand.h.
View newest version in sPHENIX GitHub at line 222 of file GFTrackCand.h
References fCov6D, fState6D, and setPdgCode().
void GFTrackCand::setComplTrackSeed (const TVector3 & pos, const TVector3 & mom, const int pdgCode, TVector3 posError = TVector3(1.0, 1.0, 1.0), TVector3 dirError = TVector3(1.0, 1.0, 1.0))
set the seed values for track: pos, momentum, pdgCode, pos error, momentum error (errors are optional and will be set to 1,1,1 if not given)
Definition at line 121 of file GFTrackCand.cxx.
View newest version in sPHENIX GitHub at line 121 of file GFTrackCand.cxx
References fCov6D, fState6D, and setPdgCode().
void GFTrackCand::setCurv (double c) inline
Definition at line 170 of file GFTrackCand.h.
View newest version in sPHENIX GitHub at line 170 of file GFTrackCand.h
References c, and fCurv.
void GFTrackCand::setDip (double d) inline
Definition at line 174 of file GFTrackCand.h.
View newest version in sPHENIX GitHub at line 174 of file GFTrackCand.h
References d, and fDip.
void GFTrackCand::setMcTrackId (int i) inline
set the MCT track id, for MC simulations
Definition at line 181 of file GFTrackCand.h.
View newest version in sPHENIX GitHub at line 181 of file GFTrackCand.h
References fMcTrackId.
Referenced by PndTrackCand2GenfitTrackCand().
void GFTrackCand::setPdgCode (int pdgCode) inline
set a particle hypothesis in form of a PDG code. This will also set the charge attribute
Definition at line 191 of file GFTrackCand.h.
View newest version in sPHENIX GitHub at line 191 of file GFTrackCand.h
References fPdg, fQ, and part.
Referenced by set6DSeedAndPdgCode(), setComplTrackSeed(), and setPosMomSeedAndPdgCode().
void GFTrackCand::setPosMomSeed (const TVector3 & pos, const TVector3 & mom, const double charge, TMatrixD cov6D = -1.0 * TMatrixD(TMatrixD::kUnit, TMatrixD(6, 6))) inline
sets the state to seed the track fitting. State has to be a TVector3 for position and a TVector3 for momentum. Everything in global coordinates charge is the charge hypotheses of the particle charge ATTENTION: If you set the cov6D covariance matrix of the state remember that there ar VARIANCES not STANDARD DEVIATIONS on the diagonal
Definition at line 231 of file GFTrackCand.h.
View newest version in sPHENIX GitHub at line 231 of file GFTrackCand.h
References charge, fCov6D, fQ, and fState6D.
Referenced by PndTrackCand2GenfitTrackCand().
void GFTrackCand::setPosMomSeedAndPdgCode (const TVector3 & pos, const TVector3 & mom, const int pdgCode, TMatrixD cov6D = -1.0 * TMatrixD(TMatrixD::kUnit, TMatrixD(6, 6))) inline
This function works the same as setPosMomSeed but instead of a charge hypothesis you can set a pdg code which will set the charge automatically ATTENTION: If you set the cov6D covariance matrix of the state remember that there are VARIANCES not standard deviations on the diagonal.
Definition at line 244 of file GFTrackCand.h.
View newest version in sPHENIX GitHub at line 244 of file GFTrackCand.h
References fCov6D, fState6D, and setPdgCode().
void GFTrackCand::sortHits ()
sort the hits that were already added to the trackCand using the rho parameter. After this function was called rho will determine the order of propagation not the order of the original addHit calls
Definition at line 139 of file GFTrackCand.cxx.
View newest version in sPHENIX GitHub at line 139 of file GFTrackCand.cxx
References fRho, and getNHits().
Referenced by GFTrack::sortHits().
void GFTrackCand::sortHits (std::vector< unsigned int > indices)
Definition at line 158 of file GFTrackCand.cxx.
View newest version in sPHENIX GitHub at line 158 of file GFTrackCand.cxx
References fDetId, fHitId, fPlaneId, fRho, and getNHits().
Friends And Related Function Documentation
bool operator== (const GFTrackCand & lhs, const GFTrackCand & rhs) friend
Definition at line 88 of file GFTrackCand.cxx.
View newest version in sPHENIX GitHub at line 88 of file GFTrackCand.cxx
Member Data Documentation
TMatrixD GFTrackCand::fCov6D private
global 6D position plus momentum covariance matrix
Definition at line 269 of file GFTrackCand.h.
View newest version in sPHENIX GitHub at line 269 of file GFTrackCand.h
Referenced by getCovSeed(), Print(), set6DSeed(), set6DSeedAndPdgCode(), setComplTrackSeed(), setPosMomSeed(), and setPosMomSeedAndPdgCode().
double GFTrackCand::fCurv private
Definition at line 262 of file GFTrackCand.h.
View newest version in sPHENIX GitHub at line 262 of file GFTrackCand.h
Referenced by getCurv(), and setCurv().
std::vector<unsigned int> GFTrackCand::fDetId private
Definition at line 257 of file GFTrackCand.h.
View newest version in sPHENIX GitHub at line 257 of file GFTrackCand.h
Referenced by addHit(), getDetIDs(), GetDetIDs(), getHit(), getHitIDs(), GetHitIDs(), getHitWithPlane(), getNHits(), getUniqueDetIDs(), hitInTrack(), operator==(), Print(), reset(), and sortHits().
double GFTrackCand::fDip private
Definition at line 263 of file GFTrackCand.h.
View newest version in sPHENIX GitHub at line 263 of file GFTrackCand.h
Referenced by getDip(), and setDip().
std::vector<unsigned int> GFTrackCand::fHitId private
Definition at line 258 of file GFTrackCand.h.
View newest version in sPHENIX GitHub at line 258 of file GFTrackCand.h
Referenced by addHit(), getHit(), getHitIDs(), GetHitIDs(), getHitWithPlane(), hitInTrack(), operator==(), Print(), reset(), and sortHits().
int GFTrackCand::fMcTrackId private
if MC simulation, store the mct track id here
Definition at line 265 of file GFTrackCand.h.
View newest version in sPHENIX GitHub at line 265 of file GFTrackCand.h
Referenced by getMcTrackId(), Print(), and setMcTrackId().
int GFTrackCand::fPdg private
particle data groupe's id for a particle
Definition at line 266 of file GFTrackCand.h.
View newest version in sPHENIX GitHub at line 266 of file GFTrackCand.h
Referenced by getPdgCode(), Print(), and setPdgCode().
std::vector<unsigned int> GFTrackCand::fPlaneId private
Definition at line 259 of file GFTrackCand.h.
View newest version in sPHENIX GitHub at line 259 of file GFTrackCand.h
Referenced by addHit(), getHitWithPlane(), and sortHits().
double GFTrackCand::fQ private
the charge of the particle in units of elementary charge
Definition at line 270 of file GFTrackCand.h.
View newest version in sPHENIX GitHub at line 270 of file GFTrackCand.h
Referenced by getChargeSeed(), getQoverPseed(), Print(), set6DSeed(), setPdgCode(), and setPosMomSeed().
std::vector<double> GFTrackCand::fRho private
Definition at line 260 of file GFTrackCand.h.
View newest version in sPHENIX GitHub at line 260 of file GFTrackCand.h
Referenced by addHit(), getHit(), getRhos(), GetRhos(), Print(), and sortHits().
TMatrixD GFTrackCand::fState6D private
global 6D position plus momentum state
Definition at line 268 of file GFTrackCand.h.
View newest version in sPHENIX GitHub at line 268 of file GFTrackCand.h
Referenced by getDirSeed(), getMomSeed(), getPosSeed(), getQoverPseed(), getStateSeed(), Print(), set6DSeed(), set6DSeedAndPdgCode(), setComplTrackSeed(), setPosMomSeed(), and setPosMomSeedAndPdgCode().
The documentation for this class was generated from the following files:
EicRoot/blob/master/genfit/GFTrackCand.h
EicRoot/blob/master/genfit/GFTrackCand.cxx