EIC Software: Acts::BinUtility Class Reference
Acts::BinUtility Class Reference
#include <fun4all_acts/blob/master/Core/include/Acts/Utilities/BinUtility.hpp>
Public Member Functions
BinUtility ()
Constructor for equidistant.
BinUtility (const BinningData &bData, const std::shared_ptr< const Transform3D > &tForm=nullptr)
BinUtility (size_t bins, float min, float max, BinningOption opt=open, BinningValue value=binX, const std::shared_ptr< const Transform3D > &tForm=nullptr)
BinUtility (std::vector< float > &bValues, BinningOption opt=open, BinningValue value=binPhi, const std::shared_ptr< const Transform3D > &tForm=nullptr)
BinUtility (const BinUtility &sbu)
BinUtility & operator= (const BinUtility &sbu)
BinUtility & operator+= (const BinUtility &gbu)
~BinUtility ()=default
Virtual Destructor.
const std::vector< BinningData > & binningData () const
return the binning data vector
size_t bins () const
Return the total number of bins.
std::array< size_t, 3 > binTriple (const Vector3D &position) const
size_t bin (const Vector3D &position, size_t ba=0) const
std::vector< size_t > neighbourRange (const Vector3D &position, size_t ba=0) const
int nextDirection (const Vector3D &position, const Vector3D &direction, size_t ba=0) const
size_t bin (const Vector2D &lposition, size_t ba=0) const
bool inside (const Vector3D &position) const
bool inside (const Vector2D &lposition) const
size_t dimensions () const
size_t max (size_t ba=0) const
size_t bins (size_t ba) const
std::shared_ptr< const
Transform3D > transform () const
BinningValue binningValue (size_t ba=0) const
size_t serialize (const std::array< size_t, 3 > &bin) const
std::ostream & toStream (std::ostream &sl) const
Private Attributes
std::vector< BinningData > m_binningData
std::shared_ptr< const
Transform3D > m_transform
vector of BinningData
std::unique_ptr< const
Transform3D > m_itransform
shared transform
Detailed Description
The BinUtility class that translated global and local position into a bins of a BinnedArray, most performant is equidistant binning without a transform, however, optionally a transform can be provided, e.g. for binning on shifted object, the transform is usually shared with the geometric object the Array is defined on, for performance reasons, also the inverse transform is stored.
Definition at line 34 of file BinUtility.hpp.
View newest version in sPHENIX GitHub at line 34 of file BinUtility.hpp
Constructor & Destructor Documentation
Acts::BinUtility::BinUtility () inline
Constructor for equidistant.
Definition at line 37 of file BinUtility.hpp.
View newest version in sPHENIX GitHub at line 37 of file BinUtility.hpp
References m_binningData.
Acts::BinUtility::BinUtility (const BinningData & bData, const std::shared_ptr< const Transform3D > & tForm = nullptr) inline
Constructor from BinningData directly
Parameters
bData is the provided binning data
tForm is the (optional) transform
Definition at line 45 of file BinUtility.hpp.
View newest version in sPHENIX GitHub at line 45 of file BinUtility.hpp
References m_binningData.
Acts::BinUtility::BinUtility (size_t bins, float min, float max, BinningOption opt = open, BinningValue value = binX, const std::shared_ptr< const Transform3D > & tForm = nullptr) inline
Constructor for equidistant
Parameters
bins is the number of bins
min in the minimal value
max is the maximal value
opt is the binning option : open, closed
value is the binninb value : binX, binY, binZ, etc.
tForm is the (optional) transform
Definition at line 62 of file BinUtility.hpp.
View newest version in sPHENIX GitHub at line 62 of file BinUtility.hpp
References m_binningData, and value.
Acts::BinUtility::BinUtility (std::vector< float > & bValues, BinningOption opt = open, BinningValue value = binPhi, const std::shared_ptr< const Transform3D > & tForm = nullptr) inline
Constructor for arbitrary
Parameters
bValues is the boundary values of the binning
opt is the binning option : open, closed
value is the binninb value : binX, binY, binZ, etc.
tForm is the (optional) transform
Definition at line 78 of file BinUtility.hpp.
View newest version in sPHENIX GitHub at line 78 of file BinUtility.hpp
References m_binningData, and value.
Acts::BinUtility::BinUtility (const BinUtility & sbu) inline
Copy constructor
Parameters
sbu is the source bin utility
Definition at line 91 of file BinUtility.hpp.
View newest version in sPHENIX GitHub at line 91 of file BinUtility.hpp
Acts::BinUtility::~BinUtility () default
Virtual Destructor.
Member Function Documentation
size_t Acts::BinUtility::bin (const Vector3D & position, size_t ba = 0) const inline
Bin from a 3D vector (already in binning frame)
Parameters
position is the 3D position to be evaluated
ba is the bin dimension
Returns
is the bin value
Definition at line 180 of file BinUtility.hpp.
View newest version in sPHENIX GitHub at line 180 of file BinUtility.hpp
References m_binningData, and m_itransform.
Referenced by linit(), lmcmnd(), lmidat(), lmsimp(), neighbourRange(), pollinit(), pybook(), pydump(), pyfact(), pyfill(), pyhist(), pynull(), pyoper(), and pyplot().
size_t Acts::BinUtility::bin (const Vector2D & lposition, size_t ba = 0) const inline
Bin from a 2D vector (following local parameters defintitions)
no optional transform applied
USE WITH CARE !!
You need to make sure that the local position is actually in the binning frame of the BinUtility
Parameters
lposition is the local position to be set
ba is the bin dimension
Returns
bin calculated from local
Definition at line 248 of file BinUtility.hpp.
View newest version in sPHENIX GitHub at line 248 of file BinUtility.hpp
References m_binningData.
const std::vector<BinningData>& Acts::BinUtility::binningData () const inline
return the binning data vector
Definition at line 147 of file BinUtility.hpp.
View newest version in sPHENIX GitHub at line 147 of file BinUtility.hpp
References m_binningData.
Referenced by Acts::adjustBinUtility(), Acts::Test::BOOST_AUTO_TEST_CASE(), Acts::createGrid2D(), Acts::createGrid3D(), Acts::detail::findLocalTopAndBottomEnd(), operator+=(), Acts::JsonGeometryConverter::surfaceMaterialToJson(), Acts::JsonGeometryConverter::volumeMaterialToJson(), and FW::RootMaterialWriter::write().
BinningValue Acts::BinUtility::binningValue (size_t ba = 0) const inline
The type/value of the binning
Parameters
ba is the binaccessor
Returns
the binning value of the accessor entry
Definition at line 325 of file BinUtility.hpp.
View newest version in sPHENIX GitHub at line 325 of file BinUtility.hpp
References m_binningData.
size_t Acts::BinUtility::bins () const inline
Return the total number of bins.
Definition at line 150 of file BinUtility.hpp.
View newest version in sPHENIX GitHub at line 150 of file BinUtility.hpp
References bins().
Referenced by Acts::AccumulatedSurfaceMaterial::AccumulatedSurfaceMaterial(), bins(), Acts::Test::BOOST_AUTO_TEST_CASE(), Acts::JsonGeometryConverter::jsonToSurfaceMaterial(), max(), and FW::RootMaterialWriter::write().
size_t Acts::BinUtility::bins (size_t ba) const inline
Number of bins
Parameters
ba is the binaccessor
Returns
size_t is the bins of the accessor entry
Definition at line 308 of file BinUtility.hpp.
View newest version in sPHENIX GitHub at line 308 of file BinUtility.hpp
References bins(), and m_binningData.
std::array<size_t, 3> Acts::BinUtility::binTriple (const Vector3D & position) const inline
Bin-triple fast access
calculate the bin triple with one transform
Parameters
position is the 3D position to be evaluated
Returns
is the bin value in 3D
transform or not
now get the bins
return the triple
Definition at line 159 of file BinUtility.hpp.
View newest version in sPHENIX GitHub at line 159 of file BinUtility.hpp
References m_binningData, m_itransform, and Acts::VectorHelpers::position().
Referenced by Acts::Test::BOOST_AUTO_TEST_CASE().
size_t Acts::BinUtility::dimensions () const inline
First bin maximal value
Returns
the dimenstion of the binning data
Definition at line 289 of file BinUtility.hpp.
View newest version in sPHENIX GitHub at line 289 of file BinUtility.hpp
References m_binningData.
Referenced by Acts::Test::BOOST_AUTO_TEST_CASE(), and Acts::JsonGeometryConverter::jsonToVolumeMaterial().
bool Acts::BinUtility::inside (const Vector3D & position) const inline
Check if bin is inside from Vector2D - optional transform applied
Parameters
position is the global position to be evaluated
Returns
is a boolean check
transform or not
Definition at line 258 of file BinUtility.hpp.
View newest version in sPHENIX GitHub at line 258 of file BinUtility.hpp
References m_binningData, m_itransform, and Acts::VectorHelpers::position().
bool Acts::BinUtility::inside (const Vector2D & lposition) const inline
Check if bin is inside from Vector2D - no optional transform applied
Parameters
lposition is the local position to be evaluated
Returns
is a boolean check
Definition at line 276 of file BinUtility.hpp.
View newest version in sPHENIX GitHub at line 276 of file BinUtility.hpp
References m_binningData.
size_t Acts::BinUtility::max (size_t ba = 0) const inline
First bin maximal value
Parameters
ba is the binaccessor
Returns
size_t is the maximal bin of the accessor entry
Definition at line 296 of file BinUtility.hpp.
View newest version in sPHENIX GitHub at line 296 of file BinUtility.hpp
References bins(), and m_binningData.
Referenced by Acts::InterpolatedMaterialMap< Mapper_t >::toStream().
std::vector<size_t> Acts::BinUtility::neighbourRange (const Vector3D & position, size_t ba = 0) const inline
Bin neighbour range this method calls the increment/decreement methods the bin itself is also contained, so if not an edge-case this would be | n | c | p |
Parameters
position is the position for the neighbour Range test
ba is the binning accessor
Returns
a vector of neighbour sizes
Definition at line 201 of file BinUtility.hpp.
View newest version in sPHENIX GitHub at line 201 of file BinUtility.hpp
References bin(), and m_binningData.
Referenced by Acts::Test::BOOST_AUTO_TEST_CASE().
int Acts::BinUtility::nextDirection (const Vector3D & position, const Vector3D & direction, size_t ba = 0) const inline
Return the oder direction for fast interlinking
Parameters
position is the global position for the next search
direction is the global position for the next search
ba is the bin accessor
Returns
the next bin
Definition at line 229 of file BinUtility.hpp.
View newest version in sPHENIX GitHub at line 229 of file BinUtility.hpp
References m_binningData.
Referenced by Acts::Layer::nextLayer().
BinUtility& Acts::BinUtility::operator+= (const BinUtility & gbu) inline
Operator++ to make multidimensional BinUtility
Parameters
gbu is the additional BinUtility to be chosen
Definition at line 116 of file BinUtility.hpp.
View newest version in sPHENIX GitHub at line 116 of file BinUtility.hpp
References binningData(), m_binningData, m_itransform, m_transform, and transform().
BinUtility& Acts::BinUtility::operator= (const BinUtility & sbu) inline
Assignment operator
Parameters
sbu is the source bin utility
Definition at line 101 of file BinUtility.hpp.
View newest version in sPHENIX GitHub at line 101 of file BinUtility.hpp
References m_binningData, m_itransform, and m_transform.
size_t Acts::BinUtility::serialize (const std::array< size_t, 3 > & bin) const inline
Serialize the bin triple
this creates a simple size_t from a triple object
Parameters
bin is the bin to be serialized
Definition at line 336 of file BinUtility.hpp.
View newest version in sPHENIX GitHub at line 336 of file BinUtility.hpp
References m_binningData.
std::ostream& Acts::BinUtility::toStream (std::ostream & sl) const inline
Output Method for std::ostream, to be overloaded by child classes
Parameters
sl is the ostream to be dumped into
Definition at line 350 of file BinUtility.hpp.
View newest version in sPHENIX GitHub at line 350 of file BinUtility.hpp
References Acts::equidistant, and m_binningData.
Referenced by Acts::operator<<().
std::shared_ptr<const Transform3D> Acts::BinUtility::transform () const inline
Transform applied to global positions before lookup
Returns
Shared pointer to transform
Definition at line 318 of file BinUtility.hpp.
View newest version in sPHENIX GitHub at line 318 of file BinUtility.hpp
References m_transform.
Referenced by operator+=().
Member Data Documentation
std::vector<BinningData> Acts::BinUtility::m_binningData private
Definition at line 376 of file BinUtility.hpp.
View newest version in sPHENIX GitHub at line 376 of file BinUtility.hpp
Referenced by bin(), binningData(), binningValue(), bins(), binTriple(), BinUtility(), dimensions(), inside(), max(), neighbourRange(), nextDirection(), operator+=(), operator=(), serialize(), and toStream().
std::unique_ptr<const Transform3D> Acts::BinUtility::m_itransform private
shared transform
Definition at line 378 of file BinUtility.hpp.
View newest version in sPHENIX GitHub at line 378 of file BinUtility.hpp
Referenced by bin(), binTriple(), inside(), operator+=(), and operator=().
std::shared_ptr<const Transform3D> Acts::BinUtility::m_transform private
vector of BinningData
Definition at line 377 of file BinUtility.hpp.
View newest version in sPHENIX GitHub at line 377 of file BinUtility.hpp
Referenced by operator+=(), operator=(), and transform().
The documentation for this class was generated from the following file:
fun4all_acts/blob/master/Core/include/Acts/Utilities/BinUtility.hpp