EIC Software: PndTrackArrayMerger Class Reference
PndTrackArrayMerger Class Reference
#include <EicRoot/blob/master/PndTools/generalTools/PndTrackArrayMerger.h>
Public Member Functions
PndTrackArrayMerger ()
PndTrackArrayMerger (TString s)
virtual ~PndTrackArrayMerger ()
virtual void SetParContainers ()
virtual InitStatus Init ()
virtual InitStatus ReInit ()
virtual void Exec (Option_t *opt)
virtual void FinishEvent ()
void SetPersistance (Bool_t p=kTRUE)
void AddInputBranch (TString s)
void SetOutputBranch (TString s)
ClassDef (PndTrackArrayMerger, 1)
Public Member Functions inherited from FairTask
FairTask ()
FairTask (const char *name, Int_t iVerbose=1)
virtual ~FairTask ()
void InitTask ()
void ReInitTask ()
void SetParTask ()
virtual void FinishTask ()
void SetVerbose (Int_t iVerbose)
void SetInputPersistance (Bool_t val)
void CheckInputPersistance (TString branchName)
Private Member Functions
PndTrackArrayMerger (const PndTrackArrayMerger &L)
PndTrackArrayMerger & operator= (const PndTrackArrayMerger &)
Private Attributes
Bool_t fPersistance
TString fOutputBranch
Flag if to store.
TClonesArray * fOutputArray
std::vector< TString > fInputBranchList
std::vector< TClonesArray * > fInputArrayList
Additional Inherited Members
Protected Member Functions inherited from FairTask
virtual void Finish ()
void InitTasks ()
void ReInitTasks ()
void SetParTasks ()
void FinishTasks ()
void FinishEvents ()
Protected Attributes inherited from FairTask
Int_t fVerbose
Int_t fInputPersistance
Indicates if input branch is persistant.
FairLogger * fLogger
Detailed Description
Definition at line 8 of file PndTrackArrayMerger.h.
View newest version in sPHENIX GitHub at line 8 of file PndTrackArrayMerger.h
Constructor & Destructor Documentation
PndTrackArrayMerger::PndTrackArrayMerger ()
Definition at line 13 of file PndTrackArrayMerger.cxx.
View newest version in sPHENIX GitHub at line 13 of file PndTrackArrayMerger.cxx
PndTrackArrayMerger::PndTrackArrayMerger (TString s)
Definition at line 17 of file PndTrackArrayMerger.cxx.
View newest version in sPHENIX GitHub at line 17 of file PndTrackArrayMerger.cxx
PndTrackArrayMerger::~PndTrackArrayMerger () virtual
Definition at line 21 of file PndTrackArrayMerger.cxx.
View newest version in sPHENIX GitHub at line 21 of file PndTrackArrayMerger.cxx
PndTrackArrayMerger::PndTrackArrayMerger (const PndTrackArrayMerger & L) private
Member Function Documentation
void PndTrackArrayMerger::AddInputBranch (TString s) inline
Definition at line 23 of file PndTrackArrayMerger.h.
View newest version in sPHENIX GitHub at line 23 of file PndTrackArrayMerger.h
References fInputBranchList.
PndTrackArrayMerger::ClassDef (PndTrackArrayMerger , 1)
void PndTrackArrayMerger::Exec (Option_t * opt) virtual
Definition at line 65 of file PndTrackArrayMerger.cxx.
View newest version in sPHENIX GitHub at line 65 of file PndTrackArrayMerger.cxx
References FairMultiLinkedData::AddLink(), fInputArrayList, fInputBranchList, fOutputArray, PndTrack::GetChi2(), PndTrack::GetFlag(), FairMultiLinkedData::GetLink(), PndTrack::GetNDF(), FairMultiLinkedData::GetNLinks(), PndTrack::GetParamFirst(), PndTrack::GetParamLast(), PndTrack::GetPidHypo(), PndTrack::GetTrackCandPtr(), and FairMultiLinkedData::Reset().
void PndTrackArrayMerger::FinishEvent () virtual
Action at end of event. For this task and all of the subtasks.
Reimplemented from FairTask.
Definition at line 108 of file PndTrackArrayMerger.cxx.
View newest version in sPHENIX GitHub at line 108 of file PndTrackArrayMerger.cxx
References FairTask::FinishEvents().
InitStatus PndTrackArrayMerger::Init (void) virtual
Intialisation at begin of run. To be implemented in the derived class. Success If not kSUCCESS, task will be set inactive.
Reimplemented from FairTask.
Definition at line 31 of file PndTrackArrayMerger.cxx.
View newest version in sPHENIX GitHub at line 31 of file PndTrackArrayMerger.cxx
References fInputArrayList, fInputBranchList, fOutputArray, fOutputBranch, fPersistance, FairRootManager::GetObject(), FairRootManager::Instance(), kFATAL, kSUCCESS, and FairRootManager::Register().
PndTrackArrayMerger& PndTrackArrayMerger::operator= (const PndTrackArrayMerger &) inline private
Definition at line 34 of file PndTrackArrayMerger.h.
View newest version in sPHENIX GitHub at line 34 of file PndTrackArrayMerger.h
InitStatus PndTrackArrayMerger::ReInit () virtual
Reinitialisation. To be implemented in the derived class. Success If not kSUCCESS, task will be set inactive.
Reimplemented from FairTask.
Definition at line 27 of file PndTrackArrayMerger.cxx.
View newest version in sPHENIX GitHub at line 27 of file PndTrackArrayMerger.cxx
References kSUCCESS.
void PndTrackArrayMerger::SetOutputBranch (TString s) inline
Definition at line 24 of file PndTrackArrayMerger.h.
View newest version in sPHENIX GitHub at line 24 of file PndTrackArrayMerger.h
References fOutputBranch, and Acts::UnitConstants::s.
void PndTrackArrayMerger::SetParContainers () virtual
Intialise parameter containers. To be implemented in the derived class.
Reimplemented from FairTask.
Definition at line 24 of file PndTrackArrayMerger.cxx.
View newest version in sPHENIX GitHub at line 24 of file PndTrackArrayMerger.cxx
void PndTrackArrayMerger::SetPersistance (Bool_t p = kTRUE) inline
Definition at line 22 of file PndTrackArrayMerger.h.
View newest version in sPHENIX GitHub at line 22 of file PndTrackArrayMerger.h
References fPersistance, and p.
Member Data Documentation
std::vector<TClonesArray*> PndTrackArrayMerger::fInputArrayList private
Definition at line 31 of file PndTrackArrayMerger.h.
View newest version in sPHENIX GitHub at line 31 of file PndTrackArrayMerger.h
Referenced by Exec(), and Init().
std::vector<TString> PndTrackArrayMerger::fInputBranchList private
Definition at line 30 of file PndTrackArrayMerger.h.
View newest version in sPHENIX GitHub at line 30 of file PndTrackArrayMerger.h
Referenced by AddInputBranch(), Exec(), and Init().
TClonesArray* PndTrackArrayMerger::fOutputArray private
Definition at line 29 of file PndTrackArrayMerger.h.
View newest version in sPHENIX GitHub at line 29 of file PndTrackArrayMerger.h
Referenced by Exec(), and Init().
TString PndTrackArrayMerger::fOutputBranch private
Flag if to store.
Definition at line 28 of file PndTrackArrayMerger.h.
View newest version in sPHENIX GitHub at line 28 of file PndTrackArrayMerger.h
Referenced by Init(), and SetOutputBranch().
Bool_t PndTrackArrayMerger::fPersistance private
Definition at line 27 of file PndTrackArrayMerger.h.
View newest version in sPHENIX GitHub at line 27 of file PndTrackArrayMerger.h
Referenced by Init(), and SetPersistance().
The documentation for this class was generated from the following files:
EicRoot/blob/master/PndTools/generalTools/PndTrackArrayMerger.h
EicRoot/blob/master/PndTools/generalTools/PndTrackArrayMerger.cxx