EIC Software: EICG4B0Detector Class Reference
EICG4B0Detector Class Reference
#include <fun4all_eicdetectors/blob/master/simulation/g4simulation/g4b0/EICG4B0Detector.h>
Public Member Functions
EICG4B0Detector (PHG4Subsystem *subsys, PHCompositeNode *Node, PHParameters *parameters, const std::string &dnam, const int layer=0)
constructor
virtual ~EICG4B0Detector () override
destructor
virtual void ConstructMe (G4LogicalVolume *world) override
construct
void Print (const std::string &what="ALL") const override
int GetDetId (G4VPhysicalVolume *) const
void SuperDetector (const std::string &name)
const std::string SuperDetector () const
int get_Layer () const
PHParameters * getParams ()
volume accessors
int IsInDetector (G4VPhysicalVolume *) const
Public Member Functions inherited from PHG4Detector
PHG4Detector ()=delete
constructor
PHG4Detector (PHG4Subsystem *subsys, PHCompositeNode *Node, const std::string &nam)
virtual ~PHG4Detector (void)
destructor
virtual void Construct (G4LogicalVolume *world) final
construct method
virtual void PostConstruction ()
Optional PostConstruction call after all geometry is constructed.
virtual void Verbosity (const int v)
virtual int Verbosity () const
virtual G4UserSteppingAction * GetSteppingAction ()
virtual std::string GetName () const
virtual void OverlapCheck (const bool chk)
virtual bool OverlapCheck () const
virtual int DisplayVolume (G4VSolid *volume, G4LogicalVolume *logvol, G4RotationMatrix *rotm=nullptr)
virtual int DisplayVolume (G4LogicalVolume *checksolid, G4LogicalVolume *logvol, G4RotationMatrix *rotm=nullptr)
virtual PHCompositeNode * topNode ()
virtual PHG4Subsystem * GetMySubsystem ()
Private Attributes
PHParameters * m_Params
std::set< G4VPhysicalVolume * > m_PhysicalVolumesSet
std::map< G4VPhysicalVolume
*, int > m_PhysicalVolumesDet
int m_Layer
std::string m_SuperDetector
Additional Inherited Members
Static Public Member Functions inherited from PHG4Detector
static G4Material * GetDetectorMaterial (const std::string &name, const bool quit=true)
static G4Element * GetDetectorElement (const std::string &name, const bool quit=true)
Detailed Description
Definition at line 18 of file EICG4B0Detector.h.
View newest version in sPHENIX GitHub at line 18 of file EICG4B0Detector.h
Constructor & Destructor Documentation
EICG4B0Detector::EICG4B0Detector (PHG4Subsystem * subsys, PHCompositeNode * Node, PHParameters * parameters, const std::string & dnam, const int layer = 0)
constructor
Definition at line 61 of file EICG4B0Detector.cc.
View newest version in sPHENIX GitHub at line 61 of file EICG4B0Detector.cc
virtual EICG4B0Detector::~EICG4B0Detector () inline override virtual
destructor
Definition at line 25 of file EICG4B0Detector.h.
View newest version in sPHENIX GitHub at line 25 of file EICG4B0Detector.h
Member Function Documentation
void EICG4B0Detector::ConstructMe (G4LogicalVolume * world) override virtual
construct
Implements PHG4Detector.
Definition at line 92 of file EICG4B0Detector.cc.
View newest version in sPHENIX GitHub at line 92 of file EICG4B0Detector.cc
References Acts::UnitConstants::cm, Acts::UnitConstants::degree, PHParameters::get_double_param(), PHParameters::get_string_param(), PHG4Detector::GetDetectorMaterial(), m_Params, m_PhysicalVolumesDet, m_PhysicalVolumesSet, PHG4Detector::OverlapCheck(), and PHG4Detector::Verbosity().
int EICG4B0Detector::get_Layer () const inline
Definition at line 40 of file EICG4B0Detector.h.
View newest version in sPHENIX GitHub at line 40 of file EICG4B0Detector.h
References m_Layer.
Referenced by EICG4B0SteppingAction::UserSteppingAction().
int EICG4B0Detector::GetDetId (G4VPhysicalVolume * volume) const
Definition at line 82 of file EICG4B0Detector.cc.
View newest version in sPHENIX GitHub at line 82 of file EICG4B0Detector.cc
References IsInDetector().
PHParameters * EICG4B0Detector::getParams ()
Definition at line 189 of file EICG4B0Detector.cc.
View newest version in sPHENIX GitHub at line 189 of file EICG4B0Detector.cc
References m_Params.
int EICG4B0Detector::IsInDetector (G4VPhysicalVolume * volume) const
Definition at line 72 of file EICG4B0Detector.cc.
View newest version in sPHENIX GitHub at line 72 of file EICG4B0Detector.cc
References m_PhysicalVolumesSet.
Referenced by GetDetId(), and EICG4B0SteppingAction::UserSteppingAction().
void EICG4B0Detector::Print (const std::string & what = "ALL") const override virtual
Reimplemented from PHG4Detector.
Definition at line 177 of file EICG4B0Detector.cc.
View newest version in sPHENIX GitHub at line 177 of file EICG4B0Detector.cc
References m_Params, and PHParameters::Print().
Referenced by EICG4B0Subsystem::Print().
void EICG4B0Detector::SuperDetector (const std::string & name) inline
Definition at line 38 of file EICG4B0Detector.h.
View newest version in sPHENIX GitHub at line 38 of file EICG4B0Detector.h
References m_SuperDetector, and name.
Referenced by EICG4B0Subsystem::InitRunSubsystem(), and EICG4B0SteppingAction::UserSteppingAction().
const std::string EICG4B0Detector::SuperDetector () const inline
Definition at line 39 of file EICG4B0Detector.h.
View newest version in sPHENIX GitHub at line 39 of file EICG4B0Detector.h
References m_SuperDetector.
Member Data Documentation
int EICG4B0Detector::m_Layer private
Definition at line 50 of file EICG4B0Detector.h.
View newest version in sPHENIX GitHub at line 50 of file EICG4B0Detector.h
Referenced by get_Layer().
PHParameters* EICG4B0Detector::m_Params private
Definition at line 44 of file EICG4B0Detector.h.
View newest version in sPHENIX GitHub at line 44 of file EICG4B0Detector.h
Referenced by ConstructMe(), getParams(), and Print().
std::map<G4VPhysicalVolume *, int> EICG4B0Detector::m_PhysicalVolumesDet private
Definition at line 48 of file EICG4B0Detector.h.
View newest version in sPHENIX GitHub at line 48 of file EICG4B0Detector.h
Referenced by ConstructMe().
std::set<G4VPhysicalVolume *> EICG4B0Detector::m_PhysicalVolumesSet private
Definition at line 46 of file EICG4B0Detector.h.
View newest version in sPHENIX GitHub at line 46 of file EICG4B0Detector.h
Referenced by ConstructMe(), and IsInDetector().
std::string EICG4B0Detector::m_SuperDetector private
Definition at line 51 of file EICG4B0Detector.h.
View newest version in sPHENIX GitHub at line 51 of file EICG4B0Detector.h
Referenced by SuperDetector().
The documentation for this class was generated from the following files:
fun4all_eicdetectors/blob/master/simulation/g4simulation/g4b0/EICG4B0Detector.h
fun4all_eicdetectors/blob/master/simulation/g4simulation/g4b0/EICG4B0Detector.cc
fun4all_eicdetectors/blob/master/simulation/g4simulation/g4b0/EICG4B0Detector_Pipe.cc