EIC Software: PHGhostRejection Class Reference
PHGhostRejection Class Reference
#include <fun4all_coresoftware/blob/master/offline/packages/trackreco/PHGhostRejection.h>
Public Member Functions
PHGhostRejection (const std::string &name="PHGhostRejection")
Tracking includes.
~PHGhostRejection () override
int InitRun (PHCompositeNode *topNode) override
int process_event (PHCompositeNode *topNode) override
int End (PHCompositeNode *topNode) override
Called at the end of all processing.
void set_track_map_name (const std::string &map_name)
void SetIteration (int iter)
Public Member Functions inherited from SubsysReco
~SubsysReco () override
virtual int EndRun (const int)
Called at the end of each run.
virtual int Init (PHCompositeNode *)
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
void Print (const std::string &="ALL") const override
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Private Member Functions
int GetNodes (PHCompositeNode *topNode)
void findGhostTracks ()
bool checkClusterSharing (SvtxTrack *tr1, SvtxTrack *tr2)
Private Attributes
SvtxTrackMap * _track_map {nullptr}
double _phi_cut = 0.01
double _eta_cut = 0.004
double _x_cut = 0.3
double _y_cut = 0.3
double _z_cut = 0.4
int _n_iteration = 0
std::string _track_map_name = "SvtxTrackMap"
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = INT_MAX - 10
}
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Detailed Description
Definition at line 25 of file PHGhostRejection.h.
View newest version in sPHENIX GitHub at line 25 of file PHGhostRejection.h
Constructor & Destructor Documentation
PHGhostRejection::PHGhostRejection (const std::string & name = "PHGhostRejection")
Tracking includes.
Definition at line 26 of file PHGhostRejection.cc.
View newest version in sPHENIX GitHub at line 26 of file PHGhostRejection.cc
PHGhostRejection::~PHGhostRejection () override
Definition at line 33 of file PHGhostRejection.cc.
View newest version in sPHENIX GitHub at line 33 of file PHGhostRejection.cc
Member Function Documentation
bool PHGhostRejection::checkClusterSharing (SvtxTrack * tr1, SvtxTrack * tr2) private
Definition at line 188 of file PHGhostRejection.cc.
View newest version in sPHENIX GitHub at line 188 of file PHGhostRejection.cc
References SvtxTrack::begin_cluster_keys(), SvtxTrack::end_cluster_keys(), SvtxTrack::get_id(), and Fun4AllBase::Verbosity().
Referenced by findGhostTracks().
int PHGhostRejection::End (PHCompositeNode *) override virtual
Called at the end of all processing.
Reimplemented from SubsysReco.
Definition at line 65 of file PHGhostRejection.cc.
View newest version in sPHENIX GitHub at line 65 of file PHGhostRejection.cc
References Fun4AllReturnCodes::EVENT_OK.
void PHGhostRejection::findGhostTracks () private
Definition at line 83 of file PHGhostRejection.cc.
View newest version in sPHENIX GitHub at line 83 of file PHGhostRejection.cc
References _eta_cut, _phi_cut, _track_map, _x_cut, _y_cut, _z_cut, SvtxTrackMap::begin(), checkClusterSharing(), SvtxTrackMap::end(), SvtxTrackMap::erase(), SvtxTrackMap::get(), SvtxTrack::get_chisq(), it, and Fun4AllBase::Verbosity().
Referenced by process_event().
int PHGhostRejection::GetNodes (PHCompositeNode * topNode) private
Definition at line 70 of file PHGhostRejection.cc.
View newest version in sPHENIX GitHub at line 70 of file PHGhostRejection.cc
References _track_map, _track_map_name, Fun4AllReturnCodes::ABORTEVENT, Fun4AllReturnCodes::EVENT_OK, and PHWHERE.
Referenced by InitRun().
int PHGhostRejection::InitRun (PHCompositeNode *) override virtual
Called for first event when run number is known. Typically this is where you may want to fetch data from database, because you know the run number.
Reimplemented from SubsysReco.
Definition at line 39 of file PHGhostRejection.cc.
View newest version in sPHENIX GitHub at line 39 of file PHGhostRejection.cc
References Fun4AllReturnCodes::EVENT_OK, and GetNodes().
int PHGhostRejection::process_event (PHCompositeNode *) override virtual
Called for each event. This is where you do the real work.
Reimplemented from SubsysReco.
Definition at line 48 of file PHGhostRejection.cc.
View newest version in sPHENIX GitHub at line 48 of file PHGhostRejection.cc
References _track_map, Fun4AllReturnCodes::EVENT_OK, findGhostTracks(), PHWHERE, SvtxTrackMap::size(), and Fun4AllBase::Verbosity().
void PHGhostRejection::set_track_map_name (const std::string & map_name) inline
Definition at line 36 of file PHGhostRejection.h.
View newest version in sPHENIX GitHub at line 36 of file PHGhostRejection.h
References _track_map_name.
void PHGhostRejection::SetIteration (int iter) inline
Definition at line 37 of file PHGhostRejection.h.
View newest version in sPHENIX GitHub at line 37 of file PHGhostRejection.h
References _n_iteration.
Member Data Documentation
double PHGhostRejection::_eta_cut = 0.004 private
Definition at line 48 of file PHGhostRejection.h.
View newest version in sPHENIX GitHub at line 48 of file PHGhostRejection.h
Referenced by findGhostTracks().
int PHGhostRejection::_n_iteration = 0 private
Definition at line 52 of file PHGhostRejection.h.
View newest version in sPHENIX GitHub at line 52 of file PHGhostRejection.h
Referenced by SetIteration().
double PHGhostRejection::_phi_cut = 0.01 private
Definition at line 47 of file PHGhostRejection.h.
View newest version in sPHENIX GitHub at line 47 of file PHGhostRejection.h
Referenced by findGhostTracks().
SvtxTrackMap* PHGhostRejection::_track_map {nullptr} private
Definition at line 45 of file PHGhostRejection.h.
View newest version in sPHENIX GitHub at line 45 of file PHGhostRejection.h
Referenced by findGhostTracks(), GetNodes(), and process_event().
std::string PHGhostRejection::_track_map_name = "SvtxTrackMap" private
Definition at line 53 of file PHGhostRejection.h.
View newest version in sPHENIX GitHub at line 53 of file PHGhostRejection.h
Referenced by GetNodes(), and set_track_map_name().
double PHGhostRejection::_x_cut = 0.3 private
Definition at line 49 of file PHGhostRejection.h.
View newest version in sPHENIX GitHub at line 49 of file PHGhostRejection.h
Referenced by findGhostTracks().
double PHGhostRejection::_y_cut = 0.3 private
Definition at line 50 of file PHGhostRejection.h.
View newest version in sPHENIX GitHub at line 50 of file PHGhostRejection.h
Referenced by findGhostTracks().
double PHGhostRejection::_z_cut = 0.4 private
Definition at line 51 of file PHGhostRejection.h.
View newest version in sPHENIX GitHub at line 51 of file PHGhostRejection.h
Referenced by findGhostTracks().
The documentation for this class was generated from the following files:
fun4all_coresoftware/blob/master/offline/packages/trackreco/PHGhostRejection.h
fun4all_coresoftware/blob/master/offline/packages/trackreco/PHGhostRejection.cc