EIC Software: starlightParticle Class Reference
starlightParticle Class Reference
#include <estarlight/blob/master/include/starlightparticle.h>
Public Member Functions
starlightParticle ()
starlightParticle (double px, double py, double pz, double e, double mass, int pdgCode, short charge, double vx=0., double vy=0, double vz=0, double vt=0, int firstParent=0, int lastParent=0, int firstDaughter=0, int lastDaughter=0, int status=0)
virtual ~starlightParticle ()
void setPdgCode (int pdgCode)
int getPdgCode () const
void setCharge (short charge)
short getCharge () const
void setMass (short mass)
short getMass () const
void setFirstParent (int parent)
void setLastParent (int parent)
int getFirstParent () const
int getLastParent () const
void setFirstDaughter (int first)
int getFirstDaughter () const
void setLastDaughter (int first)
int getLastDaughter () const
void setStatus (int status)
int getStatus () const
void setVertex (lorentzVector v)
lorentzVector getVertex () const
void reflect ()
Public Member Functions inherited from lorentzVector
lorentzVector ()
virtual ~lorentzVector ()
lorentzVector (double x, double y, double z, double t)
void SetXYZT (double x, double y, double z, double t)
void SetPxPyPzE (double px, double py, double pz, double e)
double GetPx () const
double GetPy () const
double GetPz () const
double GetE () const
lorentzVector & operator+= (const lorentzVector &vec)
lorentzVector & operator-= (const lorentzVector &vec)
double M2 () const
double M () const
vector3 BoostVector () const
void Boost (const vector3 &beta)
Private Attributes
lorentzVector _vertex
int _pdgCode
short _charge
double _mass
int _firstParent
int _lastParent
int _firstDaughter
int _lastDaughter
int _status
Detailed Description
Definition at line 41 of file starlightparticle.h.
View newest version in sPHENIX GitHub at line 41 of file starlightparticle.h
Constructor & Destructor Documentation
starlightParticle::starlightParticle ()
Definition at line 37 of file starlightparticle.cpp.
View newest version in sPHENIX GitHub at line 37 of file starlightparticle.cpp
starlightParticle::starlightParticle (double px, double py, double pz, double e, double mass, int pdgCode, short charge, double vx = 0., double vy = 0, double vz = 0, double vt = 0, int firstParent = 0, int lastParent = 0, int firstDaughter = 0, int lastDaughter = 0, int status = 0)
Definition at line 51 of file starlightparticle.cpp.
View newest version in sPHENIX GitHub at line 51 of file starlightparticle.cpp
starlightParticle::~starlightParticle () virtual
Definition at line 67 of file starlightparticle.cpp.
View newest version in sPHENIX GitHub at line 67 of file starlightparticle.cpp
Member Function Documentation
short starlightParticle::getCharge () const inline
Definition at line 55 of file starlightparticle.h.
View newest version in sPHENIX GitHub at line 55 of file starlightparticle.h
References _charge.
int starlightParticle::getFirstDaughter () const inline
Definition at line 66 of file starlightparticle.h.
View newest version in sPHENIX GitHub at line 66 of file starlightparticle.h
References _firstDaughter.
int starlightParticle::getFirstParent () const inline
Definition at line 62 of file starlightparticle.h.
View newest version in sPHENIX GitHub at line 62 of file starlightparticle.h
References _firstParent.
int starlightParticle::getLastDaughter () const inline
Definition at line 69 of file starlightparticle.h.
View newest version in sPHENIX GitHub at line 69 of file starlightparticle.h
References _lastDaughter.
int starlightParticle::getLastParent () const inline
Definition at line 63 of file starlightparticle.h.
View newest version in sPHENIX GitHub at line 63 of file starlightparticle.h
References _lastParent.
short starlightParticle::getMass () const inline
Definition at line 58 of file starlightparticle.h.
View newest version in sPHENIX GitHub at line 58 of file starlightparticle.h
References _mass.
int starlightParticle::getPdgCode () const inline
Definition at line 52 of file starlightparticle.h.
View newest version in sPHENIX GitHub at line 52 of file starlightparticle.h
References _pdgCode.
Referenced by pythiaDecayer::addParticle().
int starlightParticle::getStatus () const inline
Definition at line 72 of file starlightparticle.h.
View newest version in sPHENIX GitHub at line 72 of file starlightparticle.h
References _status.
lorentzVector starlightParticle::getVertex () const inline
Definition at line 75 of file starlightparticle.h.
View newest version in sPHENIX GitHub at line 75 of file starlightparticle.h
References _vertex.
void starlightParticle::reflect () inline virtual
Reimplemented from lorentzVector.
Definition at line 77 of file starlightparticle.h.
View newest version in sPHENIX GitHub at line 77 of file starlightparticle.h
References _vertex, lorentzVector::GetE(), lorentzVector::GetPx(), lorentzVector::GetPy(), lorentzVector::GetPz(), lorentzVector::reflect(), and lorentzVector::SetXYZT().
void starlightParticle::setCharge (short charge) inline
Definition at line 54 of file starlightparticle.h.
View newest version in sPHENIX GitHub at line 54 of file starlightparticle.h
References _charge, and charge.
void starlightParticle::setFirstDaughter (int first) inline
Definition at line 65 of file starlightparticle.h.
View newest version in sPHENIX GitHub at line 65 of file starlightparticle.h
References _firstDaughter.
Referenced by starlightPythia::produceEvent().
void starlightParticle::setFirstParent (int parent) inline
Definition at line 60 of file starlightparticle.h.
View newest version in sPHENIX GitHub at line 60 of file starlightparticle.h
References _firstParent.
void starlightParticle::setLastDaughter (int first) inline
Definition at line 68 of file starlightparticle.h.
View newest version in sPHENIX GitHub at line 68 of file starlightparticle.h
References _lastDaughter.
Referenced by starlightPythia::produceEvent().
void starlightParticle::setLastParent (int parent) inline
Definition at line 61 of file starlightparticle.h.
View newest version in sPHENIX GitHub at line 61 of file starlightparticle.h
References _lastParent.
void starlightParticle::setMass (short mass) inline
Definition at line 57 of file starlightparticle.h.
View newest version in sPHENIX GitHub at line 57 of file starlightparticle.h
References _mass, and mass.
void starlightParticle::setPdgCode (int pdgCode) inline
Definition at line 51 of file starlightparticle.h.
View newest version in sPHENIX GitHub at line 51 of file starlightparticle.h
References _pdgCode.
void starlightParticle::setStatus (int status) inline
Definition at line 71 of file starlightparticle.h.
View newest version in sPHENIX GitHub at line 71 of file starlightparticle.h
References _status.
Referenced by starlightPythia::produceEvent().
void starlightParticle::setVertex (lorentzVector v) inline
Definition at line 74 of file starlightparticle.h.
View newest version in sPHENIX GitHub at line 74 of file starlightparticle.h
References _vertex, and v.
Member Data Documentation
short starlightParticle::_charge private
Definition at line 89 of file starlightparticle.h.
View newest version in sPHENIX GitHub at line 89 of file starlightparticle.h
Referenced by getCharge(), and setCharge().
int starlightParticle::_firstDaughter private
Definition at line 94 of file starlightparticle.h.
View newest version in sPHENIX GitHub at line 94 of file starlightparticle.h
Referenced by getFirstDaughter(), and setFirstDaughter().
int starlightParticle::_firstParent private
Definition at line 92 of file starlightparticle.h.
View newest version in sPHENIX GitHub at line 92 of file starlightparticle.h
Referenced by getFirstParent(), and setFirstParent().
int starlightParticle::_lastDaughter private
Definition at line 95 of file starlightparticle.h.
View newest version in sPHENIX GitHub at line 95 of file starlightparticle.h
Referenced by getLastDaughter(), and setLastDaughter().
int starlightParticle::_lastParent private
Definition at line 93 of file starlightparticle.h.
View newest version in sPHENIX GitHub at line 93 of file starlightparticle.h
Referenced by getLastParent(), and setLastParent().
double starlightParticle::_mass private
Definition at line 90 of file starlightparticle.h.
View newest version in sPHENIX GitHub at line 90 of file starlightparticle.h
Referenced by getMass(), and setMass().
int starlightParticle::_pdgCode private
Definition at line 88 of file starlightparticle.h.
View newest version in sPHENIX GitHub at line 88 of file starlightparticle.h
Referenced by getPdgCode(), and setPdgCode().
int starlightParticle::_status private
Definition at line 97 of file starlightparticle.h.
View newest version in sPHENIX GitHub at line 97 of file starlightparticle.h
Referenced by getStatus(), and setStatus().
lorentzVector starlightParticle::_vertex private
Definition at line 81 of file starlightparticle.h.
View newest version in sPHENIX GitHub at line 81 of file starlightparticle.h
Referenced by getVertex(), reflect(), and setVertex().
The documentation for this class was generated from the following files:
estarlight/blob/master/include/starlightparticle.h
estarlight/blob/master/src/starlightparticle.cpp