EIC Software: FairVTrack Class Reference
FairVTrack Class Reference
#include <EicRoot/blob/master/base/FairVTrack.h>
Public Member Functions
FairVTrack ()
FairVTrack (const FairVTrack &pts)
FairVTrack (Int_t nhits)
virtual ~FairVTrack ()
void SetTrack (TGeoTrack *Tr)
virtual Int_t DistancetoPrimitive (Int_t px, Int_t py)
virtual void ExecuteEvent (Int_t event, Int_t px, Int_t py)
Int_t GetIndex () const
virtual const Text_t * GetName () const
virtual void InspectParticle () const
virtual void DumpParticle () const
virtual Text_t * GetObjectInfo (Int_t px, Int_t py) const
virtual void SetParticle (TParticle *p)
TParticle * GetParticle () const
FairVTrack & operator= (const FairVTrack &pts)
Protected Member Functions
void Copy (TObject &pts) const
Int_t Color (Int_t pdg)
Protected Attributes
TGeoTrack * fTrack
Int_t fIndex
TParticle * fParticle
Detailed Description
Definition at line 15 of file FairVTrack.h.
View newest version in sPHENIX GitHub at line 15 of file FairVTrack.h
Constructor & Destructor Documentation
FairVTrack::FairVTrack ()
FairVTrack::FairVTrack (const FairVTrack & pts)
Definition at line 28 of file FairVTrack.cxx.
View newest version in sPHENIX GitHub at line 28 of file FairVTrack.cxx
References Copy().
FairVTrack::FairVTrack (Int_t nhits)
Definition at line 41 of file FairVTrack.cxx.
View newest version in sPHENIX GitHub at line 41 of file FairVTrack.cxx
FairVTrack::~FairVTrack () virtual
Definition at line 55 of file FairVTrack.cxx.
View newest version in sPHENIX GitHub at line 55 of file FairVTrack.cxx
Member Function Documentation
Int_t FairVTrack::Color (Int_t pdg) protected
Definition at line 186 of file FairVTrack.cxx.
View newest version in sPHENIX GitHub at line 186 of file FairVTrack.cxx
Referenced by SetParticle(), and SetTrack().
void FairVTrack::Copy (TObject & pts) const protected
Definition at line 63 of file FairVTrack.cxx.
View newest version in sPHENIX GitHub at line 63 of file FairVTrack.cxx
References fIndex, and fParticle.
Referenced by FairVTrack(), and operator=().
Int_t FairVTrack::DistancetoPrimitive (Int_t px, Int_t py) virtual
Definition at line 78 of file FairVTrack.cxx.
View newest version in sPHENIX GitHub at line 78 of file FairVTrack.cxx
void FairVTrack::DumpParticle () const virtual
Definition at line 98 of file FairVTrack.cxx.
View newest version in sPHENIX GitHub at line 98 of file FairVTrack.cxx
References fParticle.
void FairVTrack::ExecuteEvent (Int_t event, Int_t px, Int_t py) virtual
Definition at line 108 of file FairVTrack.cxx.
View newest version in sPHENIX GitHub at line 108 of file FairVTrack.cxx
References fParticle.
Int_t FairVTrack::GetIndex () const inline
Definition at line 25 of file FairVTrack.h.
View newest version in sPHENIX GitHub at line 25 of file FairVTrack.h
References fIndex.
const Text_t * FairVTrack::GetName () const virtual
Definition at line 131 of file FairVTrack.cxx.
View newest version in sPHENIX GitHub at line 131 of file FairVTrack.cxx
References fParticle.
Text_t * FairVTrack::GetObjectInfo (Int_t px, Int_t py) const virtual
Definition at line 142 of file FairVTrack.cxx.
View newest version in sPHENIX GitHub at line 142 of file FairVTrack.cxx
References fParticle.
TParticle * FairVTrack::GetParticle () const
Definition at line 155 of file FairVTrack.cxx.
View newest version in sPHENIX GitHub at line 155 of file FairVTrack.cxx
References fParticle.
void FairVTrack::InspectParticle () const virtual
Definition at line 163 of file FairVTrack.cxx.
View newest version in sPHENIX GitHub at line 163 of file FairVTrack.cxx
References fParticle.
FairVTrack& FairVTrack::operator= (const FairVTrack & pts) inline
Definition at line 32 of file FairVTrack.h.
View newest version in sPHENIX GitHub at line 32 of file FairVTrack.h
References Copy().
void FairVTrack::SetParticle (TParticle * p) virtual
Definition at line 172 of file FairVTrack.cxx.
View newest version in sPHENIX GitHub at line 172 of file FairVTrack.cxx
References Color(), fParticle, p, and SetLineColor().
void FairVTrack::SetTrack (TGeoTrack * Tr)
Definition at line 179 of file FairVTrack.cxx.
View newest version in sPHENIX GitHub at line 179 of file FairVTrack.cxx
References Color(), fTrack, and SetLineColor().
Member Data Documentation
Int_t FairVTrack::fIndex protected
Definition at line 38 of file FairVTrack.h.
View newest version in sPHENIX GitHub at line 38 of file FairVTrack.h
Referenced by Copy(), and GetIndex().
TParticle* FairVTrack::fParticle protected
Definition at line 39 of file FairVTrack.h.
View newest version in sPHENIX GitHub at line 39 of file FairVTrack.h
Referenced by Copy(), DumpParticle(), ExecuteEvent(), GetName(), GetObjectInfo(), GetParticle(), InspectParticle(), and SetParticle().
TGeoTrack* FairVTrack::fTrack protected
Definition at line 37 of file FairVTrack.h.
View newest version in sPHENIX GitHub at line 37 of file FairVTrack.h
Referenced by SetTrack().
The documentation for this class was generated from the following files:
EicRoot/blob/master/base/FairVTrack.h
EicRoot/blob/master/base/FairVTrack.cxx