EIC Software: PndRecoKalmanFit Class Reference
PndRecoKalmanFit Class Reference
#include <EicRoot/blob/master/GenfitTools/recotasks/PndRecoKalmanFit.h>
Public Member Functions
PndRecoKalmanFit ()
~PndRecoKalmanFit ()
void SetGeane (Bool_t opt=kTRUE)
void SetPropagateToIP (Bool_t opt=kTRUE)
void SetPerpPlane (Bool_t opt=kTRUE)
void SetNumIterations (Int_t num)
void SetTrackRep (Int_t num)
void SetVerbose (Int_t verb)
void SetMvdBranchName (const TString &name)
void SetCentralTrackerBranchName (const TString &name)
Bool_t Init ()
PndTrack * Fit (PndTrack *tBefore, Int_t PDG, bool store_track_parameterization=false)
GFRecoHitFactory * GetRecoHitFactory ()
Private Member Functions
ClassDef (PndRecoKalmanFit, 0)
Verbose level.
Private Attributes
GFRecoHitFactory * fTheRecoHitFactory
GFKalman fGenFitter
FairGeanePro * fPro
TString fMvdBranchName
Geane Propagator.
TString fCentralTrackerBranchName
Name of the TCA for MVD.
Bool_t fUseGeane
Name of the TCA for central tracker.
Bool_t fPropagateToIP
Flag to use Geane.
Bool_t fPerpPlane
Flag to propagate to the interaction point.
Int_t fNumIt
Flag to use as initial plane the one perpendicular to the track.
Short_t fTrackRep
Number of iterations.
Int_t fVerbose
(0) GeaneTrackRep, 1 RKTrackRep
Detailed Description
Definition at line 31 of file PndRecoKalmanFit.h.
View newest version in sPHENIX GitHub at line 31 of file PndRecoKalmanFit.h
Constructor & Destructor Documentation
PndRecoKalmanFit::PndRecoKalmanFit ()
Definition at line 58 of file PndRecoKalmanFit.cxx.
View newest version in sPHENIX GitHub at line 58 of file PndRecoKalmanFit.cxx
References PndGeoHandling::Instance().
PndRecoKalmanFit::~PndRecoKalmanFit ()
Definition at line 105 of file PndRecoKalmanFit.cxx.
View newest version in sPHENIX GitHub at line 105 of file PndRecoKalmanFit.cxx
Member Function Documentation
PndRecoKalmanFit::ClassDef (PndRecoKalmanFit , 0) private
Verbose level.
PndTrack * PndRecoKalmanFit::Fit (PndTrack * tBefore, Int_t PDG, bool store_track_parameterization = false)
Definition at line 111 of file PndRecoKalmanFit.cxx.
View newest version in sPHENIX GitHub at line 111 of file PndRecoKalmanFit.cxx
References PndTrackCand::_GetSortedHits(), GFTrack::addHitVector(), GFRecoHitFactory::createMany(), Acts::UnitConstants::e, fGenFitter, fPerpPlane, fPro, fPropagateToIP, fTheRecoHitFactory, fTrackRep, fVerbose, GenfitTrack2PndTrack(), GFTools::getBiasedSmoothedMomXYZ(), GFTools::getBiasedSmoothedPosXYZ(), GFTrack::getCand(), PndTrackCandHit::GetDetId(), FairRootManager::GetDigiLookup(), FairTrackPar::GetDPx(), FairTrackPar::GetDPy(), FairTrackPar::GetDPz(), FairTrackPar::GetDX(), FairTrackPar::GetDY(), FairTrackPar::GetDZ(), PndTrackCandHit::GetHitId(), FairRootManager::GetMoCaLookup(), EicMoCaPoint::GetMomAvg(), GFTrack::getNumHits(), PndTrack::GetParamFirst(), EicMoCaPoint::GetPosAvg(), FairTrackPar::GetPx(), FairTrackPar::GetPy(), FairTrackPar::GetPz(), FairTrackPar::GetQ(), FairHit::GetRefIndex(), PndTrack::GetTrackCand(), PndTrack::GetTrackCandPtr(), FairTrackPar::GetX(), FairTrackParH::GetX(), FairTrackPar::GetY(), FairTrackParH::GetY(), FairTrackPar::GetZ(), FairTrackParH::GetZ(), FairRootManager::Instance(), PndTrack::mParameterizations, PndTrackCand2GenfitTrackCand(), GFKalman::processTrack(), FairGeanePro::Propagate(), FairGeanePro::PropagateToPCA(), GFTrack::setCandidate(), PndTrack::SetFlag(), NaiveTrackParameterization::SetMoCaMomentum(), NaiveTrackParameterization::SetMoCaPosition(), FairGeanePro::SetPoint(), GeaneTrackRep::setPropDir(), NaiveTrackParameterization::SetRecoMomentum(), NaiveTrackParameterization::SetRecoPosition(), GFTrack::setSmoothing(), and GFException::what().
Referenced by PndRecoMultiKalmanTask::Exec(), and PndRecoKalmanTask::Exec().
GFRecoHitFactory* PndRecoKalmanFit::GetRecoHitFactory () inline
Definition at line 52 of file PndRecoKalmanFit.h.
View newest version in sPHENIX GitHub at line 52 of file PndRecoKalmanFit.h
References fTheRecoHitFactory.
Referenced by EicRecoKalmanTask::Init().
Bool_t PndRecoKalmanFit::Init (void)
Definition at line 65 of file PndRecoKalmanFit.cxx.
View newest version in sPHENIX GitHub at line 65 of file PndRecoKalmanFit.cxx
References fGenFitter, fNumIt, fPro, fTheRecoHitFactory, fTrackRep, fUseGeane, fVerbose, GFFieldManager::getInstance(), GFFieldManager::init(), FairRootManager::Instance(), GFException::quiet(), and GFKalman::setNumIterations().
Referenced by PndRecoMultiKalmanTask::Init(), and PndRecoKalmanTask::Init().
void PndRecoKalmanFit::SetCentralTrackerBranchName (const TString & name) inline
Definition at line 47 of file PndRecoKalmanFit.h.
View newest version in sPHENIX GitHub at line 47 of file PndRecoKalmanFit.h
References fCentralTrackerBranchName, and name.
Referenced by PndRecoMultiKalmanTask::Init(), and PndRecoKalmanTask::Init().
void PndRecoKalmanFit::SetGeane (Bool_t opt = kTRUE) inline
Definition at line 40 of file PndRecoKalmanFit.h.
View newest version in sPHENIX GitHub at line 40 of file PndRecoKalmanFit.h
References fUseGeane.
Referenced by PndRecoMultiKalmanTask::Init(), and PndRecoKalmanTask::Init().
void PndRecoKalmanFit::SetMvdBranchName (const TString & name) inline
Definition at line 46 of file PndRecoKalmanFit.h.
View newest version in sPHENIX GitHub at line 46 of file PndRecoKalmanFit.h
References fMvdBranchName, and name.
Referenced by PndRecoMultiKalmanTask::Init(), and PndRecoKalmanTask::Init().
void PndRecoKalmanFit::SetNumIterations (Int_t num) inline
Definition at line 43 of file PndRecoKalmanFit.h.
View newest version in sPHENIX GitHub at line 43 of file PndRecoKalmanFit.h
References fNumIt, and num.
Referenced by PndRecoMultiKalmanTask::Init(), and PndRecoKalmanTask::Init().
void PndRecoKalmanFit::SetPerpPlane (Bool_t opt = kTRUE) inline
Definition at line 42 of file PndRecoKalmanFit.h.
View newest version in sPHENIX GitHub at line 42 of file PndRecoKalmanFit.h
References fPerpPlane.
Referenced by PndRecoKalmanTask::Init().
void PndRecoKalmanFit::SetPropagateToIP (Bool_t opt = kTRUE) inline
Definition at line 41 of file PndRecoKalmanFit.h.
View newest version in sPHENIX GitHub at line 41 of file PndRecoKalmanFit.h
References fPropagateToIP.
Referenced by PndRecoKalmanTask::Init().
void PndRecoKalmanFit::SetTrackRep (Int_t num) inline
Definition at line 44 of file PndRecoKalmanFit.h.
View newest version in sPHENIX GitHub at line 44 of file PndRecoKalmanFit.h
References fTrackRep, and num.
Referenced by PndRecoKalmanTask::Init().
void PndRecoKalmanFit::SetVerbose (Int_t verb) inline
Definition at line 45 of file PndRecoKalmanFit.h.
View newest version in sPHENIX GitHub at line 45 of file PndRecoKalmanFit.h
References fVerbose.
Referenced by PndRecoKalmanTask::Init().
Member Data Documentation
TString PndRecoKalmanFit::fCentralTrackerBranchName private
Name of the TCA for MVD.
Definition at line 63 of file PndRecoKalmanFit.h.
View newest version in sPHENIX GitHub at line 63 of file PndRecoKalmanFit.h
Referenced by SetCentralTrackerBranchName().
GFKalman PndRecoKalmanFit::fGenFitter private
Definition at line 58 of file PndRecoKalmanFit.h.
View newest version in sPHENIX GitHub at line 58 of file PndRecoKalmanFit.h
Referenced by Fit(), and Init().
TString PndRecoKalmanFit::fMvdBranchName private
Geane Propagator.
Definition at line 62 of file PndRecoKalmanFit.h.
View newest version in sPHENIX GitHub at line 62 of file PndRecoKalmanFit.h
Referenced by SetMvdBranchName().
Int_t PndRecoKalmanFit::fNumIt private
Flag to use as initial plane the one perpendicular to the track.
Definition at line 68 of file PndRecoKalmanFit.h.
View newest version in sPHENIX GitHub at line 68 of file PndRecoKalmanFit.h
Referenced by Init(), and SetNumIterations().
Bool_t PndRecoKalmanFit::fPerpPlane private
Flag to propagate to the interaction point.
Definition at line 67 of file PndRecoKalmanFit.h.
View newest version in sPHENIX GitHub at line 67 of file PndRecoKalmanFit.h
Referenced by Fit(), and SetPerpPlane().
FairGeanePro* PndRecoKalmanFit::fPro private
Definition at line 60 of file PndRecoKalmanFit.h.
View newest version in sPHENIX GitHub at line 60 of file PndRecoKalmanFit.h
Referenced by Fit(), and Init().
Bool_t PndRecoKalmanFit::fPropagateToIP private
Flag to use Geane.
Definition at line 66 of file PndRecoKalmanFit.h.
View newest version in sPHENIX GitHub at line 66 of file PndRecoKalmanFit.h
Referenced by Fit(), and SetPropagateToIP().
GFRecoHitFactory* PndRecoKalmanFit::fTheRecoHitFactory private
Definition at line 52 of file PndRecoKalmanFit.h.
View newest version in sPHENIX GitHub at line 52 of file PndRecoKalmanFit.h
Referenced by Fit(), GetRecoHitFactory(), and Init().
Short_t PndRecoKalmanFit::fTrackRep private
Number of iterations.
Definition at line 69 of file PndRecoKalmanFit.h.
View newest version in sPHENIX GitHub at line 69 of file PndRecoKalmanFit.h
Referenced by Fit(), Init(), and SetTrackRep().
Bool_t PndRecoKalmanFit::fUseGeane private
Name of the TCA for central tracker.
Definition at line 65 of file PndRecoKalmanFit.h.
View newest version in sPHENIX GitHub at line 65 of file PndRecoKalmanFit.h
Referenced by Init(), and SetGeane().
Int_t PndRecoKalmanFit::fVerbose private
(0) GeaneTrackRep, 1 RKTrackRep
Definition at line 70 of file PndRecoKalmanFit.h.
View newest version in sPHENIX GitHub at line 70 of file PndRecoKalmanFit.h
Referenced by Fit(), Init(), and SetVerbose().
The documentation for this class was generated from the following files:
EicRoot/blob/master/GenfitTools/recotasks/PndRecoKalmanFit.h
EicRoot/blob/master/GenfitTools/recotasks/PndRecoKalmanFit.cxx