EIC Software: acts/blob/sPHENIX/Tests/UnitTests/Plugins/Sycl/Seeding/SeedfinderSyclTest.cpp File Reference
SeedfinderSyclTest.cpp File Reference
#include "Acts/Plugins/Sycl/Seeding/Seedfinder.hpp"
#include "Acts/Plugins/Sycl/Utilities/QueueWrapper.hpp"
#include "Acts/Seeding/BinFinder.hpp"
#include "Acts/Seeding/BinnedSPGroup.hpp"
#include "Acts/Seeding/InternalSeed.hpp"
#include "Acts/Seeding/InternalSpacePoint.hpp"
#include "Acts/Seeding/Seed.hpp"
#include "Acts/Seeding/SeedFilter.hpp"
#include "Acts/Seeding/Seedfinder.hpp"
#include "Acts/Seeding/SeedfinderConfig.hpp"
#include "Acts/Seeding/SpacePointGrid.hpp"
#include <chrono>
#include <cmath>
#include <ctime>
#include <fstream>
#include <iomanip>
#include <iostream>
#include <limits>
#include <memory>
#include <sstream>
#include <string>
#include <boost/type_erasure/any_cast.hpp>
#include "ATLASCuts.hpp"
#include "CommandLineArguments.h"
#include "SpacePoint.hpp"
Functions
auto readFile (const std::string &filename) -> std::vector< const SpacePoint * >
template<typename external_spacepoint_t >
auto setupSeedfinderConfiguration () -> Acts::SeedfinderConfig< external_spacepoint_t >
template<typename external_spacepoint_t >
auto setupSpacePointGridConfig (const Acts::SeedfinderConfig< external_spacepoint_t > &config) -> Acts::SpacePointGridConfig
auto main (int argc, char **argv) -> int
Function Documentation
auto main (int argc, char ** argv) -> int
Definition at line 122 of file SeedfinderSyclTest.cpp.
View newest version in sPHENIX GitHub at line 122 of file SeedfinderSyclTest.cpp
References CommandLineArguments::allgroup, configureMap::config, Acts::Sycl::Seedfinder< external_spacepoint_t >::createSeedsForGroup(), Acts::Seedfinder< external_spacepoint_t, platform_t >::createSeedsForGroup(), CommandLineArguments::csvFormat, CommandLineArguments::deviceName, CommandLineArguments::groups, CommandLineArguments::inpFileExists, CommandLineArguments::inpFileName, CommandLineArguments::matches, CommandLineArguments::onlyGpu, CommandLineArguments::parse(), readFile(), setupSpacePointGridConfig(), Acts::BinnedSPGroup< external_spacepoint_t >::size(), nlohmann::to_string(), SpacePoint::varianceR, and SpacePoint::varianceZ.
auto readFile (const std::string & filename) -> std::vector<const SpacePoint*>
Definition at line 38 of file SeedfinderSyclTest.cpp.
View newest version in sPHENIX GitHub at line 38 of file SeedfinderSyclTest.cpp
References kdfinder::abs(), Acts::Test::cov, INPUTHEPMC::filename, getline, G4TTL::layer, x, y, and z.
template<typename external_spacepoint_t > auto setupSeedfinderConfiguration () -> Acts::SeedfinderConfig<external_spacepoint_t>
Definition at line 81 of file SeedfinderSyclTest.cpp.
View newest version in sPHENIX GitHub at line 81 of file SeedfinderSyclTest.cpp
References Acts::SeedfinderConfig< SpacePoint >::beamPos, Acts::SeedfinderConfig< SpacePoint >::bFieldInZ, Acts::SeedfinderConfig< SpacePoint >::collisionRegionMax, Acts::SeedfinderConfig< SpacePoint >::collisionRegionMin, configureMap::config, Acts::SeedfinderConfig< SpacePoint >::cotThetaMax, Acts::SeedfinderConfig< SpacePoint >::deltaRMax, Acts::SeedfinderConfig< SpacePoint >::deltaRMin, Acts::SeedfinderConfig< SpacePoint >::impactMax, Acts::SeedfinderConfig< SpacePoint >::maxSeedsPerSpM, Acts::SeedfinderConfig< SpacePoint >::minPt, Acts::SeedfinderConfig< SpacePoint >::nAvgTrplPerSpBLimit, Acts::SeedfinderConfig< SpacePoint >::nTrplPerSpBLimit, Acts::SeedfinderConfig< SpacePoint >::rMax, Acts::SeedfinderConfig< SpacePoint >::sigmaScattering, Acts::SeedfinderConfig< SpacePoint >::zMax, and Acts::SeedfinderConfig< SpacePoint >::zMin.
template<typename external_spacepoint_t > auto setupSpacePointGridConfig (const Acts::SeedfinderConfig< external_spacepoint_t > & config) -> Acts::SpacePointGridConfig
Definition at line 108 of file SeedfinderSyclTest.cpp.
View newest version in sPHENIX GitHub at line 108 of file SeedfinderSyclTest.cpp
References Acts::SpacePointGridConfig::bFieldInZ, and configureMap::config.
Referenced by main().