EIC Software: EicPndFieldMap Class Reference
EicPndFieldMap Class Reference
#include <EicRoot/blob/master/eic/field/EicMagneticField.h>
Public Member Functions
EicPndFieldMap (PndFieldMap *map=0)
~EicPndFieldMap ()
int Initialize ()
bool Contains (const double xx[]) const
int GetFieldValue (const double xx[], double B[]) const
Public Member Functions inherited from EicMagneticFieldMap
EicMagneticFieldMap (const char *fileName=0, TGeoMatrix *transformation=0, TGeoShape *shape=0, int color=_DEFAULT_YOKE_COLOR_)
~EicMagneticFieldMap ()
bool Initialized () const
TGeoShape * GetShape () const
const TString & GetFileName () const
virtual bool CapableToBuildYoke () const
virtual TString GetDetectorName () const
virtual int ConstructGeometry ()
void SetYokeColor (int color)
int GetYokeColor () const
virtual TGeoVolume * GetYokeVolume () const
Private Member Functions
ClassDef (EicPndFieldMap, 1)
Private Attributes
PndFieldMap * mMap
Additional Inherited Members
Protected Member Functions inherited from EicMagneticFieldMap
const char * BasenameWrapper (const char *fname) const
int GetMD5Signature (unsigned char output[])
Protected Attributes inherited from EicMagneticFieldMap
UInt_t mMD5BufferSize
UChar_t * mMD5Signature
Bool_t mInitialized
TGeoMatrix * mTransformation
indicates whether Initialize() call was made or not
TGeoShape * mShape
Int_t mColor
Detailed Description
Definition at line 32 of file EicMagneticField.h.
View newest version in sPHENIX GitHub at line 32 of file EicMagneticField.h
Constructor & Destructor Documentation
EicPndFieldMap::EicPndFieldMap (PndFieldMap * map = 0) inline
Definition at line 35 of file EicMagneticField.h.
View newest version in sPHENIX GitHub at line 35 of file EicMagneticField.h
EicPndFieldMap::~EicPndFieldMap () inline
Definition at line 46 of file EicMagneticField.h.
View newest version in sPHENIX GitHub at line 46 of file EicMagneticField.h
Member Function Documentation
EicPndFieldMap::ClassDef (EicPndFieldMap , 1) private
bool EicPndFieldMap::Contains (const double xx[]) const inline virtual
Reimplemented from EicMagneticFieldMap.
Definition at line 57 of file EicMagneticField.h.
View newest version in sPHENIX GitHub at line 57 of file EicMagneticField.h
References dx, dy, dz, PndFieldMap::IsInside(), and mMap.
int EicPndFieldMap::GetFieldValue (const double xx[], double B[]) const inline virtual
Implements EicMagneticFieldMap.
Definition at line 64 of file EicMagneticField.h.
View newest version in sPHENIX GitHub at line 64 of file EicMagneticField.h
References mMap.
int EicPndFieldMap::Initialize () inline virtual
Reimplemented from EicMagneticFieldMap.
Definition at line 48 of file EicMagneticField.h.
View newest version in sPHENIX GitHub at line 48 of file EicMagneticField.h
References PndFieldMap::Init(), EicMagneticFieldMap::Initialize(), and mMap.
Member Data Documentation
PndFieldMap* EicPndFieldMap::mMap private
Definition at line 72 of file EicMagneticField.h.
View newest version in sPHENIX GitHub at line 72 of file EicMagneticField.h
Referenced by Contains(), GetFieldValue(), and Initialize().
The documentation for this class was generated from the following file:
EicRoot/blob/master/eic/field/EicMagneticField.h