EIC Software: g4lblvtx/blob/master/macros/auxiliary_studies/hadron_phi_asymmetry/Fun4All_G4_simple_hadron_GEM.C File Reference
Fun4All_G4_simple_hadron_GEM.C File Reference
#include <phgenfit/Track.h>
#include <fun4all/Fun4AllDstInputManager.h>
#include <fun4all/Fun4AllDstOutputManager.h>
#include <fun4all/Fun4AllDummyInputManager.h>
#include <fun4all/Fun4AllInputManager.h>
#include <fun4all/Fun4AllNoSyncDstInputManager.h>
#include <fun4all/Fun4AllOutputManager.h>
#include <fun4all/Fun4AllServer.h>
#include <fun4all/SubsysReco.h>
#include <g4detectors/PHG4DetectorSubsystem.h>
#include <g4detectors/PHG4CylinderSubsystem.h>
#include <g4histos/G4HitNtuple.h>
#include <g4main/PHG4ParticleGenerator.h>
#include <g4main/PHG4ParticleGeneratorBase.h>
#include <g4main/PHG4Reco.h>
#include <g4main/PHG4TruthSubsystem.h>
#include <g4trackfastsim/PHG4TrackFastSim.h>
#include <g4trackfastsim/PHG4TrackFastSimEval.h>
#include <phool/recoConsts.h>
#include <g4lblvtx/EicFRichSubsystem.h>
#include "G4_GEM.C"
Functions
void Fun4All_G4_simple_hadron_GEM (int nEvents=-1, float phi_deg_min=0, TString out_name="out_AKiselev_GEM")
Function Documentation
void Fun4All_G4_simple_hadron_GEM (int nEvents = -1, float phi_deg_min = 0, TString out_name = "out_AKiselev_GEM")
Definition at line 30 of file Fun4All_G4_simple_hadron_GEM.C.
View newest version in sPHENIX GitHub at line 30 of file Fun4All_G4_simple_hadron_GEM.C
References PHG4TrackFastSim::add_phg4hits(), Acts::UnitConstants::e, Fun4AllServer::End(), FGEM_Init(), FGEMSetup(), in, Fun4AllServer::instance(), Fun4AllServer::registerInputManager(), Fun4AllServer::registerOutputManager(), Fun4AllServer::registerSubsystem(), PHG4Reco::registerSubsystem(), RICH, Fun4AllServer::run(), PHG4DetectorSubsystem::set_double_param(), PHG4ParticleGenerator::set_eta_range(), PHG4Reco::set_field(), PHG4TrackFastSimEval::set_filename(), PHG4ParticleGenerator::set_mom_range(), PHG4ParticleGeneratorBase::set_name(), PHG4ParticleGenerator::set_phi_range(), PHG4DetectorSubsystem::set_string_param(), PHG4TrackFastSim::set_sub_top_node_name(), PHG4TrackFastSim::set_trackmap_out_name(), PHG4TrackFastSim::set_use_vertex_in_fitting(), PHG4ParticleGeneratorBase::set_vtx(), PHG4ParticleGenerator::set_z_range(), PHG4DetectorSubsystem::SetActive(), PHG4Reco::SetWorldMaterial(), PHG4DetectorSubsystem::SuperDetector(), Fun4AllBase::Verbosity(), and PHG4TrackFastSim::Vertical_Plane.