EIC Software: FwdTrackFinder Class Reference
FwdTrackFinder Class Reference
#include <EicRoot/blob/master/eic/htree/FwdTrackFinder.h>
Public Member Functions
FwdTrackFinder ()
FwdTrackFinder (EicIdealTrackingCode *ideal, MfieldMode fieldMode=WithField)
~FwdTrackFinder ()
void ResetVtxNode (MatchCandidate *match)
void UpdateVtxNode ()
InitStatus Init ()
void Exec (Option_t *opt)
void FinishTask ()
int DefinePhiRange (double min, double max, double gra)
int DefineInversedMomentumRange (double min, double max, double gra)
int DefineInversedPtRange (double min, double max, double gra)
int DefineThetaRange (double min, double max, double gra)
void SetVerbosityLevel (unsigned level)
int AddDimension (const char *name, double min, double max)
void SetFastTreeSearchMode (unsigned qualityItrNum)
void AddResolutionLevel (const unsigned div[], unsigned count)
MediaBank * ConfigureMediaBank ()
void SetRelativeHitSmearing (double smearing)
void SetAbsoluteSpatialSmearing (double smearing)
double GetAbsoluteSpatialSmearing () const
void SetBorrowedHitCounterLimit (unsigned max)
void SetMissingHitCounterLimit (unsigned max)
void SetBorrowedPlusMissingHitCounterLimit (unsigned max)
void SetBlindCellDecisionLevel (unsigned level)
void PreferCylindricalCoordinates ()
TrKalmanNode * GetVtxNode () const
EicBoxGenerator * GetEicBoxGenerator () const
bool WithMagneticField () const
void SetMeasurementNoiseInflationFactor (double scale)
double GetMeasurementNoiseInflationFactor () const
void SetMinFilterChiSquareCCDF (double value)
double GetStoredMinFilterChiSquareCCDF () const
void SetLocationSeparationDistance (double value)
void SetExtraNdfCount (int count)
void AccountEnergyLosses (bool flag)
unsigned GetMissingHitCounterMax () const
void SetExtraGranularityFactor (double value)
double GetExtraGranularityFactor () const
int GetThetaId () const
int GetPhiId () const
int GetInvMomentumId () const
int GetInvPtId () const
int GetMomentumRelatedId () const
int ConfigureResolutionLevels (unsigned id)
Public Member Functions inherited from EicHtcTask
EicHtcTask ()
EicHtcTask (EicIdealTrackingCode *ideal, MfieldMode fieldMode=WithField)
void ResetVars ()
~EicHtcTask ()
void Exec (Option_t *opt)
void Print (Option_t *option="") const
void SetTrackOutBranchName (const TString &name)
int SetParticleHypothesis (const char *name, double momentumSeed=0.0)
void SetMediaScanThetaPhi (double theta, double phi)
TVector3 GetMediaScanDirection () const
void SetHitOutputCoordinateScaleXY (double scale)
void SetHitOutputSlopeScale (double scale)
void SetHitOutputResidualScaleXY (double scale)
void SetResolutionByHand (const char *plName, double value)
double GetResolutionByHand (const char *plName)
HtcKalmanFilter * GetKalmanFilter () const
Public Member Functions inherited from FairTask
FairTask ()
FairTask (const char *name, Int_t iVerbose=1)
virtual ~FairTask ()
void InitTask ()
void ReInitTask ()
void SetParTask ()
virtual void FinishEvent ()
void SetVerbose (Int_t iVerbose)
void SetInputPersistance (Bool_t val)
void CheckInputPersistance (TString branchName)
Public Attributes
TH1D * ccdf
Public Attributes inherited from EicHtcTask
TString mParticleHypothesis
Double_t mParticleMomentumSeed
Private Member Functions
ClassDef (FwdTrackFinder, 17)
Private Attributes
FwdHoughTree * mFwdHoughTree
TrKalmanNode * mVtxKfNode
EicBoxGenerator * mEicBoxGenerator
bool mCylindricalCoordPreference
double mExtraGranularityFactor
int mPhiId
int mThetaId
int mInvMomentumId
int mInvPtId
std::vector< PhaseSpaceVariable > mPhaseSpaceVariables
double mAngularCovMtxEstimate
double mInversedMomentumRelatedCovMtxEstimate
std::vector
< ResolutionLevelPattern * > mResolutionLevelPatterns
unsigned mBorrowedHitCounterMax
unsigned mBorrowedPlusMissingHitCounterMax
unsigned mMissingHitCounterMax
unsigned mBlindCellDecisionLevel
double mMeasurementNoiseInflationFactor
TClonesArray * mTracks
double mRelativeHitSmearing
Array of found tracks.
double mAbsoluteSpatialSmearing
double mStoredMinFilterChiSquareCCDF
Additional Inherited Members
Protected Member Functions inherited from EicHtcTask
unsigned GetMaxPossibleHitCount () const
Kalman filter pointer.
Protected Attributes inherited from EicHtcTask
EicIdealTrackingCode * mIdealTrCode
HtcKalmanFilter * mKalmanFilter
Detailed Description
Definition at line 68 of file FwdTrackFinder.h.
View newest version in sPHENIX GitHub at line 68 of file FwdTrackFinder.h
Constructor & Destructor Documentation
FwdTrackFinder::FwdTrackFinder () inline
Definition at line 73 of file FwdTrackFinder.h.
View newest version in sPHENIX GitHub at line 73 of file FwdTrackFinder.h
FwdTrackFinder::FwdTrackFinder (EicIdealTrackingCode * ideal, MfieldMode fieldMode = WithField) inline
Definition at line 74 of file FwdTrackFinder.h.
View newest version in sPHENIX GitHub at line 74 of file FwdTrackFinder.h
References ccdf, mAngularCovMtxEstimate, mFwdHoughTree, mInversedMomentumRelatedCovMtxEstimate, mInvMomentumId, mInvPtId, mPhiId, mStoredMinFilterChiSquareCCDF, mThetaId, and mTracks.
FwdTrackFinder::~FwdTrackFinder () inline
Definition at line 99 of file FwdTrackFinder.h.
View newest version in sPHENIX GitHub at line 99 of file FwdTrackFinder.h
Member Function Documentation
void FwdTrackFinder::AccountEnergyLosses (bool flag) inline
Definition at line 177 of file FwdTrackFinder.h.
View newest version in sPHENIX GitHub at line 177 of file FwdTrackFinder.h
References TrKalmanFilter::AccountEnergyLosses(), and EicHtcTask::GetKalmanFilter().
int FwdTrackFinder::AddDimension (const char * name, double min, double max) inline
Definition at line 120 of file FwdTrackFinder.h.
View newest version in sPHENIX GitHub at line 120 of file FwdTrackFinder.h
References HoughTree::AddDimension(), and mFwdHoughTree.
void FwdTrackFinder::AddResolutionLevel (const unsigned div[], unsigned count) inline
Definition at line 134 of file FwdTrackFinder.h.
View newest version in sPHENIX GitHub at line 134 of file FwdTrackFinder.h
References HoughTree::GetDdim(), mFwdHoughTree, and mResolutionLevelPatterns.
FwdTrackFinder::ClassDef (FwdTrackFinder , 17) private
MediaBank * FwdTrackFinder::ConfigureMediaBank () virtual
Reimplemented from EicHtcTask.
Definition at line 18 of file FwdTrackFinder.cxx.
View newest version in sPHENIX GitHub at line 18 of file FwdTrackFinder.cxx
References EicHtcTask::GetMediaScanDirection(), EicProtoGenerator::GetVz(), and mEicBoxGenerator.
int FwdTrackFinder::ConfigureResolutionLevels (unsigned id)
Definition at line 90 of file FwdTrackFinder.cxx.
View newest version in sPHENIX GitHub at line 90 of file FwdTrackFinder.cxx
References HoughTree::AddResolutionLevel(), PhaseSpaceVariable::GetGra(), PhaseSpaceVariable::GetRange(), kERROR, mFwdHoughTree, and mPhaseSpaceVariables.
Referenced by Init().
int FwdTrackFinder::DefineInversedMomentumRange (double min, double max, double gra)
Definition at line 49 of file FwdTrackFinder.cxx.
View newest version in sPHENIX GitHub at line 49 of file FwdTrackFinder.cxx
References HoughTree::AddDimension(), mFwdHoughTree, mInvMomentumId, mInvPtId, and mPhaseSpaceVariables.
int FwdTrackFinder::DefineInversedPtRange (double min, double max, double gra)
Definition at line 62 of file FwdTrackFinder.cxx.
View newest version in sPHENIX GitHub at line 62 of file FwdTrackFinder.cxx
References HoughTree::AddDimension(), mFwdHoughTree, mInvMomentumId, mInvPtId, and mPhaseSpaceVariables.
int FwdTrackFinder::DefinePhiRange (double min, double max, double gra)
Definition at line 36 of file FwdTrackFinder.cxx.
View newest version in sPHENIX GitHub at line 36 of file FwdTrackFinder.cxx
References HoughTree::AddDimension(), mFwdHoughTree, mPhaseSpaceVariables, and mPhiId.
int FwdTrackFinder::DefineThetaRange (double min, double max, double gra)
Definition at line 75 of file FwdTrackFinder.cxx.
View newest version in sPHENIX GitHub at line 75 of file FwdTrackFinder.cxx
References HoughTree::AddDimension(), mFwdHoughTree, mPhaseSpaceVariables, and mThetaId.
void FwdTrackFinder::Exec (Option_t * opt)
Definition at line 420 of file FwdTrackFinder.cxx.
View newest version in sPHENIX GitHub at line 420 of file FwdTrackFinder.cxx
References EicDetectorGroup::_fHits, HoughNodeGroup::AddMember(), EicIdealTrackingCode::fGroups, HoughTree::GetGroup(), HoughTree::GetGroupCount(), EicTrackingDigiHit::GetKfNodeID(), SensitiveVolume::GetKfNodeWrapper(), HoughTree::GetLinearMatchCandidateCount(), HoughTree::GetMatchCandidate(), SensitiveVolume::GetNodeGroup(), EicDetectorGroup::GetSensitiveVolume(), MatchCandidate::IsActive(), HoughTree::LaunchPatternFinder(), mAbsoluteSpatialSmearing, mFwdHoughTree, EicHtcTask::mIdealTrCode, mRelativeHitSmearing, mTracks, FwdHoughNodeGroup::PackFrom(), FwdHoughNodeGroup::PackTo(), printf(), and HoughNodeGroup::ResetMemberCounter().
void FwdTrackFinder::FinishTask () virtual
Action at end of run. For this task and all of the subtasks.
Reimplemented from EicHtcTask.
Definition at line 484 of file FwdTrackFinder.cxx.
View newest version in sPHENIX GitHub at line 484 of file FwdTrackFinder.cxx
References ccdf, FairTask::FinishTask(), FairRun::GetOutputFile(), and FairRun::Instance().
double FwdTrackFinder::GetAbsoluteSpatialSmearing () const inline
Definition at line 144 of file FwdTrackFinder.h.
View newest version in sPHENIX GitHub at line 144 of file FwdTrackFinder.h
References mAbsoluteSpatialSmearing.
EicBoxGenerator* FwdTrackFinder::GetEicBoxGenerator () const inline
Definition at line 161 of file FwdTrackFinder.h.
View newest version in sPHENIX GitHub at line 161 of file FwdTrackFinder.h
References mEicBoxGenerator.
double FwdTrackFinder::GetExtraGranularityFactor () const inline
Definition at line 182 of file FwdTrackFinder.h.
View newest version in sPHENIX GitHub at line 182 of file FwdTrackFinder.h
References mExtraGranularityFactor.
Referenced by FwdHoughTree::AddNodeGroup().
int FwdTrackFinder::GetInvMomentumId () const inline
Definition at line 186 of file FwdTrackFinder.h.
View newest version in sPHENIX GitHub at line 186 of file FwdTrackFinder.h
References mInvMomentumId.
Referenced by FwdHoughTree::MappingCall(), and ResetVtxNode().
int FwdTrackFinder::GetInvPtId () const inline
Definition at line 187 of file FwdTrackFinder.h.
View newest version in sPHENIX GitHub at line 187 of file FwdTrackFinder.h
References mInvPtId.
Referenced by Init(), and FwdHoughTree::MappingCall().
double FwdTrackFinder::GetMeasurementNoiseInflationFactor () const inline
Definition at line 166 of file FwdTrackFinder.h.
View newest version in sPHENIX GitHub at line 166 of file FwdTrackFinder.h
References mMeasurementNoiseInflationFactor.
Referenced by FwdHoughTree::SetupKalmanFilter().
unsigned FwdTrackFinder::GetMissingHitCounterMax () const inline virtual
Reimplemented from EicHtcTask.
Definition at line 179 of file FwdTrackFinder.h.
View newest version in sPHENIX GitHub at line 179 of file FwdTrackFinder.h
References mMissingHitCounterMax.
int FwdTrackFinder::GetMomentumRelatedId () const inline
Definition at line 189 of file FwdTrackFinder.h.
View newest version in sPHENIX GitHub at line 189 of file FwdTrackFinder.h
References mInvMomentumId, and mInvPtId.
Referenced by Init(), FwdHoughTree::MappingCall(), and ResetVtxNode().
int FwdTrackFinder::GetPhiId () const inline
Definition at line 185 of file FwdTrackFinder.h.
View newest version in sPHENIX GitHub at line 185 of file FwdTrackFinder.h
References mPhiId.
Referenced by Init(), FwdHoughTree::MappingCall(), and ResetVtxNode().
double FwdTrackFinder::GetStoredMinFilterChiSquareCCDF () const inline
Definition at line 172 of file FwdTrackFinder.h.
View newest version in sPHENIX GitHub at line 172 of file FwdTrackFinder.h
References mStoredMinFilterChiSquareCCDF.
Referenced by FwdHoughTree::SetupTrackQualityIteration().
int FwdTrackFinder::GetThetaId () const inline
Definition at line 184 of file FwdTrackFinder.h.
View newest version in sPHENIX GitHub at line 184 of file FwdTrackFinder.h
References mThetaId.
Referenced by Init(), FwdHoughTree::MappingCall(), and ResetVtxNode().
TrKalmanNode* FwdTrackFinder::GetVtxNode () const inline
Definition at line 160 of file FwdTrackFinder.h.
View newest version in sPHENIX GitHub at line 160 of file FwdTrackFinder.h
References mVtxKfNode.
Referenced by FwdHoughTree::MappingCall().
InitStatus FwdTrackFinder::Init () virtual
Intialisation at begin of run. To be implemented in the derived class. Success If not kSUCCESS, task will be set inactive.
Reimplemented from EicHtcTask.
Definition at line 112 of file FwdTrackFinder.cxx.
View newest version in sPHENIX GitHub at line 112 of file FwdTrackFinder.cxx
References KalmanFilter::AddNode(), FwdHoughTree::AddNodeGroup(), HoughTree::AllocateLookUpTable(), ConfigureResolutionLevels(), KalmanFilter::Forward, ResolutionLevel::GetCellSize(), FairRootManager::GetInFile(), GetInvPtId(), EicHtcTask::GetKalmanFilter(), HoughTree::GetLdim(), HoughTree::GetLevel(), FairPrimaryGenerator::GetListOfGenerators(), TrKalmanFilter::GetLocationHead(), SensitiveVolume::GetLogicalNode(), EicHtcTask::GetMaxPossibleHitCount(), GetMomentumRelatedId(), TrKalmanNodeLocation::GetNext(), GetPhiId(), FairBaseParSet::GetPriGen(), TrKalmanNode::GetSensitiveVolume(), GetThetaId(), EicProtoGenerator::GetVz(), SensitiveVolume::GetXmax(), SensitiveVolume::GetXmin(), SensitiveVolume::GetYmax(), SensitiveVolume::GetYmin(), EicHtcTask::Init(), FairRootManager::Instance(), it, kERROR, kSUCCESS, LocalToMaster(), mAngularCovMtxEstimate, MasterToLocal(), mBlindCellDecisionLevel, mBorrowedHitCounterMax, mBorrowedPlusMissingHitCounterMax, mCylindricalCoordPreference, mEicBoxGenerator, mFwdHoughTree, LogicalVolumeLookupTableEntry::mGeoMtx, mInversedMomentumRelatedCovMtxEstimate, mMissingHitCounterMax, mPhaseSpaceVariables, mTracks, mVtxKfNode, printf(), RADIANS, FairRootManager::Register(), HoughTree::SetBlindCellDecisionLevel(), HoughTree::SetBorrowedHitCounterLimit(), HoughTree::SetBorrowedPlusMissingHitCounterLimit(), HoughTree::SetOkHitCounterLimits(), SQR, WithMagneticField(), xmax, xmin, ymax, and ymin.
void FwdTrackFinder::PreferCylindricalCoordinates () inline
Definition at line 158 of file FwdTrackFinder.h.
View newest version in sPHENIX GitHub at line 158 of file FwdTrackFinder.h
References mCylindricalCoordPreference.
void FwdTrackFinder::ResetVtxNode (MatchCandidate * match)
Definition at line 288 of file FwdTrackFinder.cxx.
View newest version in sPHENIX GitHub at line 288 of file FwdTrackFinder.cxx
References _COVARIANCE_FIRST_BLOWUP_CFF_, _QP_, _SX_, _SY_, _X_, cos(), ResolutionLevel::GetCellSize(), KalmanNode::GetCP(), HoughTree::GetDdim(), HoughTree::GetDimension(), TrKalmanFilter::GetFieldMode(), MatchCandidate::GetIdPtr(), GetInvMomentumId(), EicHtcTask::GetKalmanFilter(), HoughTree::GetLdim(), HoughTree::GetLevel(), HoughDimension::GetMin(), GetMomentumRelatedId(), GetPhiId(), GetThetaId(), EicProtoGenerator::GetVx(), EicProtoGenerator::GetVxSmearing(), EicProtoGenerator::GetVy(), EicProtoGenerator::GetVySmearing(), KalmanNode::GetX0(), KalmanNode::GetXp(), ip(), KfMatrix::KFM(), KfMatrix::KFV(), mAngularCovMtxEstimate, mEicBoxGenerator, mFwdHoughTree, mInversedMomentumRelatedCovMtxEstimate, EicHtcTask::mParticleMomentumSeed, mVtxKfNode, NoField, p, RADIANS, KfMatrix::Reset(), TrKalmanNode::SetMomentum(), and SQR.
Referenced by FwdHoughTree::ResolveAmbiguitiesNg(), and FwdHoughTree::SetupKalmanFilter().
void FwdTrackFinder::SetAbsoluteSpatialSmearing (double smearing) inline
Definition at line 143 of file FwdTrackFinder.h.
View newest version in sPHENIX GitHub at line 143 of file FwdTrackFinder.h
References mAbsoluteSpatialSmearing.
void FwdTrackFinder::SetBlindCellDecisionLevel (unsigned level) inline
Definition at line 154 of file FwdTrackFinder.h.
View newest version in sPHENIX GitHub at line 154 of file FwdTrackFinder.h
References mBlindCellDecisionLevel.
void FwdTrackFinder::SetBorrowedHitCounterLimit (unsigned max) inline
Definition at line 146 of file FwdTrackFinder.h.
View newest version in sPHENIX GitHub at line 146 of file FwdTrackFinder.h
References max, and mBorrowedHitCounterMax.
void FwdTrackFinder::SetBorrowedPlusMissingHitCounterLimit (unsigned max) inline
Definition at line 151 of file FwdTrackFinder.h.
View newest version in sPHENIX GitHub at line 151 of file FwdTrackFinder.h
References max, and mBorrowedPlusMissingHitCounterMax.
void FwdTrackFinder::SetExtraGranularityFactor (double value) inline
Definition at line 181 of file FwdTrackFinder.h.
View newest version in sPHENIX GitHub at line 181 of file FwdTrackFinder.h
References mExtraGranularityFactor, and value.
void FwdTrackFinder::SetExtraNdfCount (int count) inline
Definition at line 176 of file FwdTrackFinder.h.
View newest version in sPHENIX GitHub at line 176 of file FwdTrackFinder.h
References EicHtcTask::GetKalmanFilter(), and KalmanFilter::SetExtraNdfCount().
void FwdTrackFinder::SetFastTreeSearchMode (unsigned qualityItrNum) inline
Definition at line 123 of file FwdTrackFinder.h.
View newest version in sPHENIX GitHub at line 123 of file FwdTrackFinder.h
References mFwdHoughTree, and HoughTree::SetFastTreeSearchMode().
void FwdTrackFinder::SetLocationSeparationDistance (double value) inline
Definition at line 173 of file FwdTrackFinder.h.
View newest version in sPHENIX GitHub at line 173 of file FwdTrackFinder.h
References EicHtcTask::GetKalmanFilter(), and TrKalmanFilter::SetLocationSeparationDistance().
void FwdTrackFinder::SetMeasurementNoiseInflationFactor (double scale) inline
Definition at line 165 of file FwdTrackFinder.h.
View newest version in sPHENIX GitHub at line 165 of file FwdTrackFinder.h
References mMeasurementNoiseInflationFactor.
void FwdTrackFinder::SetMinFilterChiSquareCCDF (double value) inline
Definition at line 168 of file FwdTrackFinder.h.
View newest version in sPHENIX GitHub at line 168 of file FwdTrackFinder.h
References EicHtcTask::GetKalmanFilter(), mStoredMinFilterChiSquareCCDF, KalmanFilter::SetMinFilterChiSquareCCDF(), and value.
void FwdTrackFinder::SetMissingHitCounterLimit (unsigned max) inline
Definition at line 148 of file FwdTrackFinder.h.
View newest version in sPHENIX GitHub at line 148 of file FwdTrackFinder.h
References max, and mMissingHitCounterMax.
void FwdTrackFinder::SetRelativeHitSmearing (double smearing) inline
Definition at line 142 of file FwdTrackFinder.h.
View newest version in sPHENIX GitHub at line 142 of file FwdTrackFinder.h
References mRelativeHitSmearing.
void FwdTrackFinder::SetVerbosityLevel (unsigned level) inline
Definition at line 119 of file FwdTrackFinder.h.
View newest version in sPHENIX GitHub at line 119 of file FwdTrackFinder.h
References mFwdHoughTree, and HoughTree::SetVerbosityLevel().
void FwdTrackFinder::UpdateVtxNode ()
Definition at line 371 of file FwdTrackFinder.cxx.
View newest version in sPHENIX GitHub at line 371 of file FwdTrackFinder.cxx
References _COVARIANCE_FINAL_BLOWUP_CFF_, _QP_, _SX_, _SY_, _X_, KalmanNode::GetCP(), KalmanNode::GetCS(), TrKalmanFilter::GetFieldMode(), EicHtcTask::GetKalmanFilter(), EicProtoGenerator::GetVx(), EicProtoGenerator::GetVxSmearing(), EicProtoGenerator::GetVy(), EicProtoGenerator::GetVySmearing(), KalmanNode::GetX0(), KalmanNode::GetXp(), KalmanNode::GetXs(), ip(), KfMatrix::KFM(), KfMatrix::KFV(), mEicBoxGenerator, mVtxKfNode, NoField, KfMatrix::Reset(), SQR, and TrKalmanNode::UpdateInversedMomentum().
Referenced by FwdHoughTree::FinalFit().
bool FwdTrackFinder::WithMagneticField () const inline
Definition at line 163 of file FwdTrackFinder.h.
View newest version in sPHENIX GitHub at line 163 of file FwdTrackFinder.h
References TrKalmanFilter::GetFieldMode(), EicHtcTask::GetKalmanFilter(), and WithField.
Referenced by FwdHoughTree::FinalFit(), and Init().
Member Data Documentation
TH1D* FwdTrackFinder::ccdf
Definition at line 108 of file FwdTrackFinder.h.
View newest version in sPHENIX GitHub at line 108 of file FwdTrackFinder.h
Referenced by FwdHoughTree::FinalFit(), FinishTask(), and FwdTrackFinder().
double FwdTrackFinder::mAbsoluteSpatialSmearing private
Definition at line 231 of file FwdTrackFinder.h.
View newest version in sPHENIX GitHub at line 231 of file FwdTrackFinder.h
Referenced by Exec(), GetAbsoluteSpatialSmearing(), and SetAbsoluteSpatialSmearing().
double FwdTrackFinder::mAngularCovMtxEstimate private
Definition at line 210 of file FwdTrackFinder.h.
View newest version in sPHENIX GitHub at line 210 of file FwdTrackFinder.h
Referenced by FwdTrackFinder(), Init(), and ResetVtxNode().
unsigned FwdTrackFinder::mBlindCellDecisionLevel private
Definition at line 219 of file FwdTrackFinder.h.
View newest version in sPHENIX GitHub at line 219 of file FwdTrackFinder.h
Referenced by Init(), and SetBlindCellDecisionLevel().
unsigned FwdTrackFinder::mBorrowedHitCounterMax private
Definition at line 216 of file FwdTrackFinder.h.
View newest version in sPHENIX GitHub at line 216 of file FwdTrackFinder.h
Referenced by Init(), and SetBorrowedHitCounterLimit().
unsigned FwdTrackFinder::mBorrowedPlusMissingHitCounterMax private
Definition at line 216 of file FwdTrackFinder.h.
View newest version in sPHENIX GitHub at line 216 of file FwdTrackFinder.h
Referenced by Init(), and SetBorrowedPlusMissingHitCounterLimit().
bool FwdTrackFinder::mCylindricalCoordPreference private
Definition at line 202 of file FwdTrackFinder.h.
View newest version in sPHENIX GitHub at line 202 of file FwdTrackFinder.h
Referenced by Init(), and PreferCylindricalCoordinates().
EicBoxGenerator* FwdTrackFinder::mEicBoxGenerator private
Definition at line 200 of file FwdTrackFinder.h.
View newest version in sPHENIX GitHub at line 200 of file FwdTrackFinder.h
Referenced by ConfigureMediaBank(), GetEicBoxGenerator(), Init(), ResetVtxNode(), and UpdateVtxNode().
double FwdTrackFinder::mExtraGranularityFactor private
Definition at line 204 of file FwdTrackFinder.h.
View newest version in sPHENIX GitHub at line 204 of file FwdTrackFinder.h
Referenced by GetExtraGranularityFactor(), and SetExtraGranularityFactor().
FwdHoughTree* FwdTrackFinder::mFwdHoughTree private
Definition at line 196 of file FwdTrackFinder.h.
View newest version in sPHENIX GitHub at line 196 of file FwdTrackFinder.h
Referenced by AddDimension(), AddResolutionLevel(), ConfigureResolutionLevels(), DefineInversedMomentumRange(), DefineInversedPtRange(), DefinePhiRange(), DefineThetaRange(), Exec(), FwdTrackFinder(), Init(), ResetVtxNode(), SetFastTreeSearchMode(), and SetVerbosityLevel().
double FwdTrackFinder::mInversedMomentumRelatedCovMtxEstimate private
Definition at line 210 of file FwdTrackFinder.h.
View newest version in sPHENIX GitHub at line 210 of file FwdTrackFinder.h
Referenced by FwdTrackFinder(), Init(), and ResetVtxNode().
int FwdTrackFinder::mInvMomentumId private
Definition at line 208 of file FwdTrackFinder.h.
View newest version in sPHENIX GitHub at line 208 of file FwdTrackFinder.h
Referenced by DefineInversedMomentumRange(), DefineInversedPtRange(), FwdTrackFinder(), GetInvMomentumId(), and GetMomentumRelatedId().
int FwdTrackFinder::mInvPtId private
Definition at line 208 of file FwdTrackFinder.h.
View newest version in sPHENIX GitHub at line 208 of file FwdTrackFinder.h
Referenced by DefineInversedMomentumRange(), DefineInversedPtRange(), FwdTrackFinder(), GetInvPtId(), and GetMomentumRelatedId().
double FwdTrackFinder::mMeasurementNoiseInflationFactor private
Definition at line 221 of file FwdTrackFinder.h.
View newest version in sPHENIX GitHub at line 221 of file FwdTrackFinder.h
Referenced by GetMeasurementNoiseInflationFactor(), and SetMeasurementNoiseInflationFactor().
unsigned FwdTrackFinder::mMissingHitCounterMax private
Definition at line 218 of file FwdTrackFinder.h.
View newest version in sPHENIX GitHub at line 218 of file FwdTrackFinder.h
Referenced by GetMissingHitCounterMax(), Init(), and SetMissingHitCounterLimit().
std::vector<PhaseSpaceVariable> FwdTrackFinder::mPhaseSpaceVariables private
Definition at line 209 of file FwdTrackFinder.h.
View newest version in sPHENIX GitHub at line 209 of file FwdTrackFinder.h
Referenced by ConfigureResolutionLevels(), DefineInversedMomentumRange(), DefineInversedPtRange(), DefinePhiRange(), DefineThetaRange(), and Init().
int FwdTrackFinder::mPhiId private
Definition at line 208 of file FwdTrackFinder.h.
View newest version in sPHENIX GitHub at line 208 of file FwdTrackFinder.h
Referenced by DefinePhiRange(), FwdTrackFinder(), and GetPhiId().
double FwdTrackFinder::mRelativeHitSmearing private
Array of found tracks.
Definition at line 226 of file FwdTrackFinder.h.
View newest version in sPHENIX GitHub at line 226 of file FwdTrackFinder.h
Referenced by Exec(), and SetRelativeHitSmearing().
std::vector<ResolutionLevelPattern*> FwdTrackFinder::mResolutionLevelPatterns private
Definition at line 212 of file FwdTrackFinder.h.
View newest version in sPHENIX GitHub at line 212 of file FwdTrackFinder.h
Referenced by AddResolutionLevel().
double FwdTrackFinder::mStoredMinFilterChiSquareCCDF private
Definition at line 233 of file FwdTrackFinder.h.
View newest version in sPHENIX GitHub at line 233 of file FwdTrackFinder.h
Referenced by FwdTrackFinder(), GetStoredMinFilterChiSquareCCDF(), and SetMinFilterChiSquareCCDF().
int FwdTrackFinder::mThetaId private
Definition at line 208 of file FwdTrackFinder.h.
View newest version in sPHENIX GitHub at line 208 of file FwdTrackFinder.h
Referenced by DefineThetaRange(), FwdTrackFinder(), and GetThetaId().
TClonesArray* FwdTrackFinder::mTracks private
Definition at line 223 of file FwdTrackFinder.h.
View newest version in sPHENIX GitHub at line 223 of file FwdTrackFinder.h
Referenced by Exec(), FwdTrackFinder(), and Init().
TrKalmanNode* FwdTrackFinder::mVtxKfNode private
Definition at line 198 of file FwdTrackFinder.h.
View newest version in sPHENIX GitHub at line 198 of file FwdTrackFinder.h
Referenced by GetVtxNode(), Init(), ResetVtxNode(), and UpdateVtxNode().
The documentation for this class was generated from the following files:
EicRoot/blob/master/eic/htree/FwdTrackFinder.h
EicRoot/blob/master/eic/htree/FwdTrackFinder.cxx