EIC Software: hepMC3Writer Class Reference
hepMC3Writer Class Reference
#include <estarlight/blob/master/include/hepmc3writer.h>
Public Member Functions
hepMC3Writer ()
~hepMC3Writer ()
int initWriter (const inputParameters &param)
int writeEvent (const eXEvent &event, int eventnumber)
void close ()
Private Member Functions
int initBeamHepMC3 (const inputParameters &param)
Private Attributes
WriterAscii * _hepmc3_output
FourVector hepmc3_electronBeam_four_vector_
FourVector hepmc3_targetBeam_four_vector_
int electronBeam_pdg_id_
int targetBeam_pdg_id_
Detailed Description
Definition at line 13 of file hepmc3writer.h.
View newest version in sPHENIX GitHub at line 13 of file hepmc3writer.h
Constructor & Destructor Documentation
hepMC3Writer::hepMC3Writer ()
Default Constructor
Definition at line 16 of file hepmc3writer.cpp.
View newest version in sPHENIX GitHub at line 16 of file hepmc3writer.cpp
hepMC3Writer::~hepMC3Writer ()
Member Function Documentation
void hepMC3Writer::close () inline
Definition at line 28 of file hepmc3writer.h.
View newest version in sPHENIX GitHub at line 28 of file hepmc3writer.h
References _hepmc3_output.
int hepMC3Writer::initBeamHepMC3 (const inputParameters & param) private
Init HepMC3 Beam Four Vectors
Definition at line 31 of file hepmc3writer.cpp.
View newest version in sPHENIX GitHub at line 31 of file hepmc3writer.cpp
References electronBeam_pdg_id_, inputParameters::electronBeamLorentzGamma(), hepmc3_electronBeam_four_vector_, hepmc3_targetBeam_four_vector_, targetBeam_pdg_id_, inputParameters::targetBeamA(), inputParameters::targetBeamLorentzGamma(), and inputParameters::targetBeamZ().
Referenced by initWriter().
int hepMC3Writer::initWriter (const inputParameters & param)
Init HepMC3 Writer with input parameters
need to pass the parameters to HepMC3
Definition at line 20 of file hepmc3writer.cpp.
View newest version in sPHENIX GitHub at line 20 of file hepmc3writer.cpp
References _hepmc3_output, inputParameters::baseFileName(), and initBeamHepMC3().
int hepMC3Writer::writeEvent (const eXEvent & event, int eventnumber)
Write an eX event to file
Make HepMC3 Event and Vertex ... Currently only two Vertices per Event, the beam and gamma
Add beam particles to beam vertex
Get starlight particle vector
Takes e_starlight events and converts to hepmc3 format
pass to HepMC3 FourVector
add vertex to HepMC3 Event
Definition at line 54 of file hepmc3writer.cpp.
View newest version in sPHENIX GitHub at line 54 of file hepmc3writer.cpp
References _hepmc3_output, electronBeam_pdg_id_, lorentzVector::GetE(), lorentzVector::GetPx(), lorentzVector::GetPy(), lorentzVector::GetPz(), hepmc3_electronBeam_four_vector_, hepmc3_targetBeam_four_vector_, and targetBeam_pdg_id_.
Member Data Documentation
WriterAscii* hepMC3Writer::_hepmc3_output private
Definition at line 35 of file hepmc3writer.h.
View newest version in sPHENIX GitHub at line 35 of file hepmc3writer.h
Referenced by close(), initWriter(), and writeEvent().
int hepMC3Writer::electronBeam_pdg_id_ private
Definition at line 38 of file hepmc3writer.h.
View newest version in sPHENIX GitHub at line 38 of file hepmc3writer.h
Referenced by initBeamHepMC3(), and writeEvent().
FourVector hepMC3Writer::hepmc3_electronBeam_four_vector_ private
Definition at line 36 of file hepmc3writer.h.
View newest version in sPHENIX GitHub at line 36 of file hepmc3writer.h
Referenced by initBeamHepMC3(), and writeEvent().
FourVector hepMC3Writer::hepmc3_targetBeam_four_vector_ private
Definition at line 37 of file hepmc3writer.h.
View newest version in sPHENIX GitHub at line 37 of file hepmc3writer.h
Referenced by initBeamHepMC3(), and writeEvent().
int hepMC3Writer::targetBeam_pdg_id_ private
Definition at line 39 of file hepmc3writer.h.
View newest version in sPHENIX GitHub at line 39 of file hepmc3writer.h
Referenced by initBeamHepMC3(), and writeEvent().
The documentation for this class was generated from the following files:
estarlight/blob/master/include/hepmc3writer.h
estarlight/blob/master/src/hepmc3writer.cpp