EIC Software: Acts::Test Namespace Reference
Acts::Test Namespace Reference
Namespace for ATS unit tests.
Namespaces
namespace benchmark_tools_internal
namespace events
namespace float_compare_internal
namespace Layers
namespace states
Classes
struct MicroBenchmarkResult
struct CubicTrackingGeometry
struct CylindricalTrackingGeometry
class DetectorElementStub
class LineSurfaceStub
struct ObjTestWriter
struct meas_factory
struct MeasurementCreator
This struct creates FittableMeasurements on the detector surfaces, according to the given smearing xxparameters.
struct MaterialScattering
Simplified material interaction effect by pure gaussian deflection.
struct MinimalOutlierFinder
class AlignmentContext
class AlignableDetectorElement
struct StepVolumeCollector
struct LayerCreatorFixture
struct SurfaceArrayCreatorFixture
struct NavigatorState
struct PropagatorState
mockup of propagtor state
struct Stepper
This is a struct to mimic the stepper.
struct Result
struct ActorA
struct ActorB
struct AborterWithResultA
struct AborterWithResultInvalid
struct AborterWithResultB
struct AborterWithoutResult
struct AborterWithoutResultInvalid
struct DistanceObserver
A distance observer struct as an actor.
struct CallCounter
A call counter struct as an actor.
struct PropState
Simplified propagator state.
struct PlaneSelector
struct StepWiseActor
the bound state propagation
struct SteppingState
mockup of stepping state
struct NavigationState
mockup of navigation state
struct Options
mockup of the Propagator Options
struct PerpendicularMeasure
An observer that measures the perpendicular distance.
struct SurfaceObserver
An observer that measures the perpendicular distance.
struct EndOfWorld
Aborter for the case that a particle leaves the detector or reaches a custom made threshold.
struct StepCollector
Data collector while propagation.
struct SurfaceArrayFixture
struct ExtendedMinimalSourceLink
struct Object
struct fsm
struct fsm2
struct S1
struct S2
struct S3
struct E1
struct E2
class E3
struct fsm3
struct MyStruct
struct functor
struct variadic_struct
struct tuple_helper
struct NoCopy
struct E
struct M
struct M2
struct M3
struct M4
class M5
struct N
struct N2
struct N3
struct A
struct A2
struct B
struct C
struct D
struct InputTrack
struct PlyElement
Ply element struct.
Typedefs
using par_t = ParID_t
using SourceLink = MinimalSourceLink
template<ParID_t... params>
using MeasurementType = Measurement< SourceLink, params...>
using FittableMeasurement = FittableMeasurement< SourceLink >
using Parameters = BoundVector
using Covariance = BoundSymMatrix
using ParVec_t = BoundParameters::ParVector_t
using CovMat_t = BoundParameters::CovMatrix_t
template<ParID_t... params>
using ParSet = ParameterSet< params...>
using BoundTrackState = TrackState< SourceLink, BoundParameters >
using Jacobian = BoundParameters::CovMatrix_t
using TrackState = TrackState< SourceLink, BoundParameters >
using Resolution = std::pair< ParID_t, double >
using ElementResolution = std::vector< Resolution >
using VolumeResolution = std::map< GeometryID::Value, ElementResolution >
using DetectorResolution = std::map< GeometryID::Value, VolumeResolution >
using DebugOutput = DebugOutputActor
using SrfVec = std::vector< std::shared_ptr< const Surface >>
using Box = Acts::Volume::BoundingBox
using Ray = Acts::Ray< double, 3 >
using grid_t = detail::Grid< ActsVectorF< 5 >, detail::EquidistantAxis, detail::EquidistantAxis >
using RecordedMaterial = std::vector< std::pair< Acts::Material, Acts::Vector3D >>
using EAxis = Acts::detail::EquidistantAxis
using Grid2D = Acts::detail::Grid< Acts::AccumulatedVolumeMaterial, EAxis, EAxis >
using Grid3D = Acts::detail::Grid< Acts::AccumulatedVolumeMaterial, EAxis, EAxis, EAxis >
using MaterialGrid2D = Acts::detail::Grid< Acts::ActsVectorF< 5 >, EAxis, EAxis >
using MaterialGrid3D = Acts::detail::Grid< Acts::ActsVectorF< 5 >, EAxis, EAxis, EAxis >
using PathLimit = PathLimitReached
using EndOfWorld = EndOfWorldReached
using BField = ConstantBField
using Stepper = EigenStepper< BField >
using ReferencePropagator = Propagator< Stepper, Navigator >
using DirectPropagator = Propagator< Stepper, DirectNavigator >
using path_limit = PathLimitReached
using BFieldType = ConstantBField
using EigenStepperType = EigenStepper< BFieldType >
using EigenPropagatorType = Propagator< EigenStepperType, Navigator >
using AtlasStepperType = AtlasStepper< BFieldType >
using EigenStepper = EigenStepper< BField >
using EigenPropagator = Propagator< EigenStepper >
using StraightLinePropagator = Propagator< StraightLineStepper, Navigator >
using ObjectBBox = Acts::AxisAlignedBoundingBox< Object, float, 3 >
template<typename T >
using member_a_t = decltype(std::declval< T >().member_a)
template<typename T >
using member_b_t = decltype(std::declval< T >().member_b)
template<typename T >
using nested_a_t = typename T::NestedA
template<typename T >
using nested_b_t = typename T::NestedB
template<typename T >
using member_t = decltype(std::declval< T >().member)
template<typename T >
using nested_t = typename T::Nested
template<typename T >
using meta_t = typename T::template meta< void, void >
using Propagator = Propagator< EigenStepper< ConstantBField >>
using Linearizer = HelicalTrackLinearizer< Propagator >
using Linearizer_t = HelicalTrackLinearizer< Propagator >
Functions
Vector3D origin (0., 0., 0.)
Vector3D originStraw (0.3_m,-0.2_m, 11_m)
template<typename surface_t >
MicroBenchmarkResult intersectionTest (const surface_t &surface, double phi, double theta)
BOOST_DATA_TEST_CASE (benchmark_surface_intersections, bdata::random((bdata::seed=21, bdata::distribution=std::uniform_real_distribution<>(-M_PI, M_PI)))^bdata::random((bdata::seed=22, bdata::distribution=std::uniform_real_distribution<>(-0.3, 0.3)))^bdata::xrange(ntests), phi, theta, index)
template<typename T >
void assumeAccessed (T &&clobber)
template<typename T >
void assumeRead (const T &clobber)
template<typename T >
void assumeWritten (T &clobber)
template<typename Callable >
MicroBenchmarkResult microBenchmark (Callable &&iteration, size_t iters_per_run, size_t num_runs=20000, std::chrono::milliseconds warmup_time=std::chrono::milliseconds(2000))
template<typename Callable , typename Input >
MicroBenchmarkResult microBenchmark (Callable &&iterationWithInput, const std::vector< Input > &inputs, size_t num_runs=20000, std::chrono::milliseconds warmup_time=std::chrono::milliseconds(2000))
template<typename T , typename U >
boost::test_tools::predicate_result checkCloseRel (const T &val, const U &ref, double reltol)
template<typename T , typename U >
boost::test_tools::predicate_result checkCloseAbs (const T &val, const U &ref, double abstol)
template<typename T >
boost::test_tools::predicate_result checkSmall (const T &val, double small)
template<typename T , typename U >
boost::test_tools::predicate_result checkCloseOrSmall (const T &val, const U &ref, double reltol, double small)
template<typename Scalar , int dim>
boost::test_tools::predicate_result checkCloseCovariance (const ActsSymMatrix< Scalar, dim > &val, const ActsSymMatrix< Scalar, dim > &ref, double tol)
constexpr Material makeBeryllium ()
constexpr Material makeSilicon ()
MaterialProperties makeUnitSlab ()
Build material slab corresponding to 1 radiation and interaction length.
MaterialProperties makePercentSlab ()
Build material slab corresponding to 1% of radiation and interaction length.
BOOST_AUTO_TEST_CASE (assume_accessed)
BOOST_AUTO_TEST_CASE (assume_read)
BOOST_AUTO_TEST_CASE (assume_written)
BOOST_AUTO_TEST_CASE (micro_benchmark_result)
BOOST_AUTO_TEST_CASE (micro_benchmark)
BOOST_DATA_TEST_CASE (bound_to_plane_test, bdata::random((bdata::seed=1240, bdata::distribution=std::uniform_real_distribution<>(-1000., 1000.)))^bdata::random((bdata::seed=2351, bdata::distribution=std::uniform_real_distribution<>(-1000., 1000.)))^bdata::random((bdata::seed=3412, bdata::distribution=std::uniform_real_distribution<>(-1000., 1000.)))^bdata::random((bdata::seed=5732, bdata::distribution=std::uniform_real_distribution<>(0., M_PI)))^bdata::random((bdata::seed=8941, bdata::distribution=std::uniform_real_distribution<>(0., M_PI)))^bdata::random((bdata::seed=1295, bdata::distribution=std::uniform_real_distribution<>(0., M_PI)))^bdata::xrange(100), x, y, z, a, b, c, index)
Unit test for parameters at a plane.
BOOST_DATA_TEST_CASE (bound_to_disc_test, bdata::random((bdata::seed=9810, bdata::distribution=std::uniform_real_distribution<>(-1000., 1000.)))^bdata::random((bdata::seed=1221, bdata::distribution=std::uniform_real_distribution<>(-1000., 1000.)))^bdata::random((bdata::seed=12132, bdata::distribution=std::uniform_real_distribution<>(-1000., 1000.)))^bdata::random((bdata::seed=16783, bdata::distribution=std::uniform_real_distribution<>(0., M_PI)))^bdata::random((bdata::seed=13984, bdata::distribution=std::uniform_real_distribution<>(0., M_PI)))^bdata::random((bdata::seed=77615, bdata::distribution=std::uniform_real_distribution<>(0., M_PI)))^bdata::xrange(100), x, y, z, a, b, c, index)
Unit test for parameters at a disc.
BOOST_DATA_TEST_CASE (bound_to_cylinder_test, bdata::random((bdata::seed=39810, bdata::distribution=std::uniform_real_distribution<>(-1000., 1000.)))^bdata::random((bdata::seed=21221, bdata::distribution=std::uniform_real_distribution<>(-1000., 1000.)))^bdata::random((bdata::seed=62132, bdata::distribution=std::uniform_real_distribution<>(-1000., 1000.)))^bdata::random((bdata::seed=91683, bdata::distribution=std::uniform_real_distribution<>(0., M_PI)))^bdata::random((bdata::seed=39847, bdata::distribution=std::uniform_real_distribution<>(0., M_PI)))^bdata::random((bdata::seed=72615, bdata::distribution=std::uniform_real_distribution<>(0., M_PI)))^bdata::xrange(100), x, y, z, a, b, c, index)
Unit test for parameters at a cylinder.
BOOST_DATA_TEST_CASE (bound_to_perigee_test, bdata::random((bdata::seed=3980, bdata::distribution=std::uniform_real_distribution<>(-10., 10.)))^bdata::random((bdata::seed=2221, bdata::distribution=std::uniform_real_distribution<>(-10., 10.)))^bdata::random((bdata::seed=2132, bdata::distribution=std::uniform_real_distribution<>(-10., 10.)))^bdata::random((bdata::seed=9183, bdata::distribution=std::uniform_real_distribution<>(0., 0.05)))^bdata::random((bdata::seed=3947, bdata::distribution=std::uniform_real_distribution<>(0., 0.05)))^bdata::xrange(100), x, y, z, a, b, index)
Unit test for parameters at the perigee.
BOOST_DATA_TEST_CASE (bound_to_line_test, bdata::random((bdata::seed=73980, bdata::distribution=std::uniform_real_distribution<>(-1000., 1000.)))^bdata::random((bdata::seed=21221, bdata::distribution=std::uniform_real_distribution<>(-1000., 1000.)))^bdata::random((bdata::seed=62992, bdata::distribution=std::uniform_real_distribution<>(-1000., 1000.)))^bdata::random((bdata::seed=900683, bdata::distribution=std::uniform_real_distribution<>(0., M_PI)))^bdata::random((bdata::seed=5439847, bdata::distribution=std::uniform_real_distribution<>(0., M_PI)))^bdata::random((bdata::seed=1972615, bdata::distribution=std::uniform_real_distribution<>(0., M_PI)))^bdata::xrange(100), x, y, z, a, b, c, index)
Unit test for parameters at a line.
BOOST_AUTO_TEST_CASE (curvilinear_initialization)
Unit test for Curvilinear parameters.
BOOST_AUTO_TEST_CASE (index_combination_generation_test)
constexpr par_t operator""_p (unsigned long long i)
BOOST_AUTO_TEST_CASE (variant_measurement_generation_test)
BOOST_AUTO_TEST_CASE (free_initialization)
Unit test for free parameters.
BOOST_AUTO_TEST_CASE (getSurface_test)
BOOST_AUTO_TEST_CASE (getSize_test)
BOOST_AUTO_TEST_CASE (MinimalSourceLinkTest)
BOOST_AUTO_TEST_CASE (visit_measurement_test)
BOOST_AUTO_TEST_CASE (measurement_initialization)
Unit test for creation of Measurement object.
CurvilinearParameters make_params ()
TrackState< SourceLink,
CurvilinearParameters > make_rand_trackstate ()
auto make_trackstate ()
BOOST_AUTO_TEST_CASE (multitrajectory_build)
BOOST_AUTO_TEST_CASE (visit_apply_abort)
BOOST_AUTO_TEST_CASE (trackstate_add_bitmask)
BOOST_AUTO_TEST_CASE (trackstate_proxy_cross_talk)
BOOST_AUTO_TEST_CASE (trackstate_reassignment)
BOOST_AUTO_TEST_CASE (storage_consistency)
BOOST_AUTO_TEST_CASE (parset_consistency_tests)
Unit test for checking consistency of ParameterSet class.
BOOST_AUTO_TEST_CASE (parset_copy_assignment_tests)
Unit test for copy/assignment/swap in ParameterSet class.
BOOST_AUTO_TEST_CASE (parset_comparison_tests)
Unit test for comparison operators in ParameterSet.
BOOST_AUTO_TEST_CASE (parset_projection_tests)
Unit test for projection matrices in ParameterSet.
BOOST_AUTO_TEST_CASE (parset_residual_tests)
Unit test for residuals between different ParameterSet objects.
BOOST_AUTO_TEST_CASE (parset_parID_mapping)
Unit test for index-/type-based access of coordinates.
template<typename Parameter >
void consistencyCheck (const Parameter &pars, const Vector3D &position, const Vector3D &momentum, double charge, double time, std::array< double, eBoundParametersSize > values)
BOOST_AUTO_TEST_CASE (track_state_initialization)
Unit test for creation of Measurement object.
BOOST_AUTO_TEST_CASE (gain_matrix_smoother)
BOOST_AUTO_TEST_CASE (gain_matrix_updater)
std::normal_distribution< double > gauss (0., 1.)
std::default_random_engine generator (42)
BOOST_AUTO_TEST_CASE (kalman_fitter_zero_field)
Unit test for Kalman fitter with measurements along the x-axis.
BOOST_AUTO_TEST_CASE (AlignmentContextTests)
Unit test for creating compliant/non-compliant Surface object.
BOOST_AUTO_TEST_CASE (CuboidVolumeConstruction)
BOOST_AUTO_TEST_CASE (CuboidVolumeRecreation)
BOOST_AUTO_TEST_CASE (CuboidVolumeException)
BOOST_AUTO_TEST_CASE (CuboidVolumeProperties)
BOOST_AUTO_TEST_CASE (CuboidVolumeBuilderTest)
BOOST_AUTO_TEST_CASE (CutoutCylinderVolumeBoundsConstruction)
BOOST_AUTO_TEST_CASE (CutoutCylinderVolumeBoundsRecreation)
BOOST_AUTO_TEST_CASE (CutoutCylinderVolumeBoundsExceptions)
BOOST_AUTO_TEST_CASE (CutoutCylinderVolumeBoundsAccess)
BOOST_AUTO_TEST_CASE (CutoutCylinderVolumeBoundsInside)
BOOST_AUTO_TEST_CASE (CutoutCylinderVolumeBoundsBoundingBox)
BOOST_AUTO_TEST_CASE (CylinderVolumeBoundsConstruction)
BOOST_AUTO_TEST_CASE (CylinderVolumeBoundsRecreation)
BOOST_AUTO_TEST_CASE (CylinderVolumeBoundsExceptions)
BOOST_AUTO_TEST_CASE (CylinderVolumeBoundsAccess)
BOOST_DATA_TEST_CASE (CylinderVolumeBoundsDecomposeToSurfaces, bdata::random(-M_PI, M_PI)^bdata::random(-M_PI, M_PI)^bdata::random(-M_PI, M_PI)^bdata::random(-10., 10.)^bdata::random(-10., 10.)^bdata::random(-10., 10.)^bdata::xrange(100), alpha, beta, gamma, posX, posY, posZ, index)
Unit test for testing the decomposeToSurfaces() function.
BOOST_AUTO_TEST_CASE (CylinderVolumeBoundsBoundingBox)
BOOST_DATA_TEST_CASE (CylinderVolumeBuilder_wraps, bdata::random(-11.,-15.)^bdata::random(11., 15.)^bdata::random(-10., 10.)^bdata::random(0., 4.)^bdata::random(11., 15.)^bdata::random(10., 15.)^bdata::xrange(100), left, right, central, inner, outer, length, index)
Unit test for testing the wraps() function of the CylinderVolumeBuilder.
BOOST_DATA_TEST_CASE (CylinderVolumeBuilder_containes, bdata::random(-11.,-15.)^bdata::random(11., 15.)^bdata::random(-10., 10.)^bdata::random(0., 4.)^bdata::random(10., 15.)^bdata::random(10., 15.)^bdata::xrange(100), left, right, central, inner, outer, length, index)
BOOST_DATA_TEST_CASE (CylinderVolumeBuilder_overlapsInR, bdata::random(0., 4.)^bdata::random(11., 15.)^bdata::xrange(100), inner, outer, index)
BOOST_DATA_TEST_CASE (CylinderVolumeBuilder_overlapsInZ, bdata::random(-11.,-15.)^bdata::random(11., 15.)^bdata::random(0., 4.)^bdata::xrange(100), left, right, inner, index)
BOOST_AUTO_TEST_CASE (ExtentTest)
Unit tests for Polyderon construction & operator +=.
BOOST_AUTO_TEST_CASE (construction_test)
BOOST_AUTO_TEST_CASE (decomposeToSurfaces)
BOOST_AUTO_TEST_CASE (ply_test)
BOOST_AUTO_TEST_CASE (bounding_box_creation)
BOOST_AUTO_TEST_CASE (GeometryID_construct_default)
BOOST_AUTO_TEST_CASE (GeometryID_construct_encoded)
BOOST_AUTO_TEST_CASE (GeometryID_max_values)
BOOST_AUTO_TEST_CASE (GeometryID_order)
void draw_surfaces (const SrfVec &surfaces, const std::string &fname)
BOOST_FIXTURE_TEST_CASE (LayerCreator_createCylinderLayer, LayerCreatorFixture)
BOOST_FIXTURE_TEST_CASE (LayerCreator_createDiscLayer, LayerCreatorFixture)
BOOST_FIXTURE_TEST_CASE (LayerCreator_barrelStagger, LayerCreatorFixture)
BOOST_AUTO_TEST_CASE (PolyhedronTest)
Unit tests for Polyderon construction & operator +=.
BOOST_AUTO_TEST_CASE (PolyhedronExtent)
Unit tests for Polyderon construction & operator +=.
BOOST_AUTO_TEST_CASE (SimpleGeometryTest)
Unit test for a three layer detector parameters Testing the Tool chain in the geometry building process.
void draw_surfaces (SrfVec surfaces, const std::string &fname)
BOOST_FIXTURE_TEST_CASE (SurfaceArrayCreator_createEquidistantAxis_Phi, SurfaceArrayCreatorFixture)
BOOST_FIXTURE_TEST_CASE (SurfaceArrayCreator_createEquidistantAxis_Z, SurfaceArrayCreatorFixture)
BOOST_FIXTURE_TEST_CASE (SurfaceArrayCreator_createEquidistantAxis_R, SurfaceArrayCreatorFixture)
BOOST_FIXTURE_TEST_CASE (SurfaceArrayCreator_dependentBinCounts, SurfaceArrayCreatorFixture)
BOOST_FIXTURE_TEST_CASE (SurfaceArrayCreator_completeBinning, SurfaceArrayCreatorFixture)
BOOST_FIXTURE_TEST_CASE (SurfaceArrayCreator_barrelStagger, SurfaceArrayCreatorFixture)
BOOST_AUTO_TEST_CASE (GeometryID_closeGeometry_test)
BOOST_AUTO_TEST_CASE (TrackingGeometry_testVisitSurfaces)
BOOST_AUTO_TEST_CASE (CylindricalTrackingGeometryTest)
BOOST_AUTO_TEST_CASE (CubicTrackingGeometryTest)
BOOST_AUTO_TEST_CASE (GeometryID_innervolume_test)
BOOST_AUTO_TEST_CASE (GeometryID_outervolume_test)
BOOST_AUTO_TEST_CASE (GeometryID_containervolume_test)
pre-check on GeometryID
std::tuple< std::vector< const
Volume * >, std::shared_ptr
< TrackingGeometry > > gridBoxFactory (size_t n=NBOXES, double hl=1000, size_t octd=5)
BOOST_DATA_TEST_CASE (bvhnavigation_test, bdata::random((bdata::seed=7, bdata::engine=std::mt19937(), bdata::distribution=std::uniform_real_distribution<>(-5, 5)))^bdata::random((bdata::seed=2, bdata::engine=std::mt19937(), bdata::distribution=std::uniform_real_distribution<>(-M_PI, M_PI)))^bdata::random((bdata::seed=3, bdata::engine=std::mt19937(), bdata::distribution=std::uniform_real_distribution<>(-100, 100)))^bdata::random((bdata::seed=4, bdata::engine=std::mt19937(), bdata::distribution=std::uniform_real_distribution<>(-100, 100)))^bdata::random((bdata::seed=5, bdata::engine=std::mt19937(), bdata::distribution=std::uniform_real_distribution<>(-100, 100)))^bdata::xrange(NTESTS), eta, phi, x, y, z, index)
BOOST_DATA_TEST_CASE (ConstantBField_components, bdata::random(-2_T, 2_T)^bdata::random(-1_T, 4_T)^bdata::random(0_T, 10_T)^bdata::random(-10_m, 10_m)^bdata::random(-10_m, 10_m)^bdata::random(-10_m, 10_m)^bdata::xrange(10), x, y, z, bx, by, bz, index)
unit test for construction of constant magnetic field
BOOST_DATA_TEST_CASE (ConstantBField_update, bdata::random(-2_T, 2_T)^bdata::random(-1_T, 4_T)^bdata::random(0_T, 10_T)^bdata::random(-10_m, 10_m)^bdata::random(-10_m, 10_m)^bdata::random(-10_m, 10_m)^bdata::xrange(10), x, y, z, bx, by, bz, index)
unit test for update of constant magnetic field
BOOST_AUTO_TEST_CASE (InterpolatedBFieldMap_rz)
template<class BField_t >
void testInterfaceConsistency (const BField_t &field)
BOOST_AUTO_TEST_CASE (TestConstantBFieldInterfaceConsistency)
BOOST_AUTO_TEST_CASE (TestSolenoidBFieldInterfaceConsistency)
BOOST_AUTO_TEST_CASE (TestInterpolatedBFieldMapInterfaceConsistency)
BOOST_AUTO_TEST_CASE (TestSharedBFieldInterfaceConsistency)
BOOST_AUTO_TEST_CASE (TestSolenoidBField)
BOOST_AUTO_TEST_CASE (AccumulatedMaterialProperties_construction_test)
Test the constructors.
BOOST_AUTO_TEST_CASE (AccumulatedMaterialProperties_trackaverage_test)
Test the event averaging behavior.
BOOST_AUTO_TEST_CASE (AccumulatedMaterialProperties_totalaverage_test)
Test the total averaging behavior.
BOOST_AUTO_TEST_CASE (AccumulatedSurfaceMaterial_construction_test)
Test the constructors.
BOOST_AUTO_TEST_CASE (AccumulatedSurfaceMaterial_fill_convert_0D)
Test the filling and conversion.
BOOST_AUTO_TEST_CASE (AccumulatedSurfaceMaterial_fill_convert_1D)
Test the filling and conversion.
BOOST_AUTO_TEST_CASE (vacuum)
BOOST_AUTO_TEST_CASE (single_material)
BOOST_AUTO_TEST_CASE (two_materials)
BOOST_AUTO_TEST_CASE (two_materials_different_lengh)
BOOST_AUTO_TEST_CASE (BinnedSurfaceMaterial_construction_test)
Test the constructors.
BOOST_AUTO_TEST_CASE (HomogeneousSurfaceMaterial_construction_test)
Test the constructors.
BOOST_AUTO_TEST_CASE (HomogeneousSurfaceMaterial_scaling_test)
BOOST_AUTO_TEST_CASE (HomogeneousSurfaceMaterial_access_test)
BOOST_AUTO_TEST_CASE (HomogeneousVolumeMaterial_construction_test)
Test the constructors.
BOOST_AUTO_TEST_CASE (HomogeneousVolumeMaterial_access_test)
ActsVectorD< dim > trafoGlobalToLocal (const Vector3D &global)
BOOST_AUTO_TEST_CASE (InterpolatedMaterialMap_MaterialCell_test)
BOOST_AUTO_TEST_CASE (InterpolatedMaterialMap_MaterialMapper_test)
BOOST_AUTO_TEST_CASE (InterpolatedMaterialMap_test)
BOOST_AUTO_TEST_CASE (construct_element_fraction)
BOOST_AUTO_TEST_CASE (construct_with_fractions)
BOOST_AUTO_TEST_CASE (construct_with_weights)
BOOST_AUTO_TEST_CASE (Square_Grid_test)
Various test for the Material in the case of a Cuboid volume and 2D Grid.
BOOST_AUTO_TEST_CASE (PhiZ_Grid_test)
Various test for the Material in the case of a Cylindrical volume with a 2D grid.
BOOST_AUTO_TEST_CASE (Cubic_Grid_test)
Various test for the Material in the case of a Cuboid volume.
BOOST_AUTO_TEST_CASE (Cylindrical_Grid_test)
Various test for the Material in the case of a Cylindrical volume.
BOOST_AUTO_TEST_CASE (ProtoSurfaceMaterial_construction_test)
Test the constructors.
BOOST_AUTO_TEST_CASE (ProtoVolumeMaterial_construction_test)
Test the constructors.
BOOST_AUTO_TEST_CASE (SurfaceMaterialMapper_tests)
Test the filling and conversion.
BOOST_AUTO_TEST_CASE (VolumeMaterialMapper_comparison_tests)
Test case for comparison between the mapped material and the associated material by propagation.
BOOST_AUTO_TEST_CASE (AbortListTest_PathLimit)
BOOST_AUTO_TEST_CASE (AbortListSignatureTest)
BOOST_AUTO_TEST_CASE (ActionListTest_Distance)
BOOST_AUTO_TEST_CASE (ActionListTest_TwoActions)
BOOST_AUTO_TEST_CASE (atlas_stepper_state_test)
These tests are aiming to test whether the state setup is working properly.
BOOST_AUTO_TEST_CASE (atlas_stepper_test)
BOOST_AUTO_TEST_CASE (AuctioneerTest_VoidAuctioneer)
BOOST_AUTO_TEST_CASE (AuctioneerTest_FirstValidAuctioneer)
BOOST_AUTO_TEST_CASE (AuctioneerTest_HighestValidAuctioneer)
BOOST_AUTO_TEST_CASE (ConstrainedStepTest)
BOOST_AUTO_TEST_CASE (covariance_engine_test)
ReferencePropagator rpropagator (std::move(estepper), std::move(navigator))
DirectPropagator dpropagator (std::move(dstepper), std::move(dnavigator))
template<typename rpropagator_t , typename dpropagator_t >
void runTest (const rpropagator_t &rprop, const dpropagator_t &dprop, double pT, double phi, double theta, int charge, double time, int index)
BOOST_DATA_TEST_CASE (test_direct_navigator, bdata::random((bdata::seed=20, bdata::distribution=std::uniform_real_distribution<>(0.15_GeV, 10_GeV)))^bdata::random((bdata::seed=21, bdata::distribution=std::uniform_real_distribution<>(-M_PI, M_PI)))^bdata::random((bdata::seed=22, bdata::distribution=std::uniform_real_distribution<>(1.0, M_PI-1.0)))^bdata::random((bdata::seed=23, bdata::distribution=std::uniform_int_distribution<>(0, 1)))^bdata::random((bdata::seed=24, bdata::distribution=std::uniform_int_distribution<>(0, 100)))^bdata::xrange(ntests), pT, phi, theta, charge, time, index)
CylindricalTrackingGeometry cGeometry (tgContext)
Navigator navigator (tGeometry)
BFieldType bField (0, 0, 2_T)
EigenStepperType estepper (bField)
EigenPropagatorType epropagator (std::move(estepper), std::move(navigator))
BOOST_DATA_TEST_CASE (test_extrapolation_, bdata::random((bdata::seed=0, bdata::distribution=std::uniform_real_distribution<>(0.4_GeV, 10_GeV)))^bdata::random((bdata::seed=1, bdata::distribution=std::uniform_real_distribution<>(-M_PI, M_PI)))^bdata::random((bdata::seed=2, bdata::distribution=std::uniform_real_distribution<>(1.0, M_PI-1.0)))^bdata::random((bdata::seed=3, bdata::distribution=std::uniform_int_distribution<>(0, 1)))^bdata::random((bdata::seed=4, bdata::distribution=std::uniform_int_distribution<>(0, 100)))^bdata::xrange(ntests), pT, phi, theta, charge, time, index)
BOOST_DATA_TEST_CASE (test_surface_collection_, bdata::random((bdata::seed=10, bdata::distribution=std::uniform_real_distribution<>(0.4_GeV, 10_GeV)))^bdata::random((bdata::seed=11, bdata::distribution=std::uniform_real_distribution<>(-M_PI, M_PI)))^bdata::random((bdata::seed=12, bdata::distribution=std::uniform_real_distribution<>(1.0, M_PI-1.0)))^bdata::random((bdata::seed=13, bdata::distribution=std::uniform_int_distribution<>(0, 1)))^bdata::random((bdata::seed=14, bdata::distribution=std::uniform_int_distribution<>(0, 100)))^bdata::xrange(ntests), pT, phi, theta, charge, time, index)
BOOST_DATA_TEST_CASE (test_material_interactor_, bdata::random((bdata::seed=20, bdata::distribution=std::uniform_real_distribution<>(0.4_GeV, 10_GeV)))^bdata::random((bdata::seed=21, bdata::distribution=std::uniform_real_distribution<>(-M_PI, M_PI)))^bdata::random((bdata::seed=22, bdata::distribution=std::uniform_real_distribution<>(1.0, M_PI-1.0)))^bdata::random((bdata::seed=23, bdata::distribution=std::uniform_int_distribution<>(0, 1)))^bdata::random((bdata::seed=24, bdata::distribution=std::uniform_int_distribution<>(0, 100)))^bdata::xrange(ntests), pT, phi, theta, charge, time, index)
BOOST_DATA_TEST_CASE (loop_protection_test, bdata::random((bdata::seed=20, bdata::distribution=std::uniform_real_distribution<>(0.1_GeV, 0.5_GeV)))^bdata::random((bdata::seed=21, bdata::distribution=std::uniform_real_distribution<>(-M_PI, M_PI)))^bdata::random((bdata::seed=22, bdata::distribution=std::uniform_real_distribution<>(1.0, M_PI-1.0)))^bdata::random((bdata::seed=23, bdata::distribution=std::uniform_int_distribution<>(0, 1)))^bdata::random((bdata::seed=24, bdata::distribution=std::uniform_int_distribution<>(0, 100)))^bdata::xrange(ntests), pT, phi, theta, charge, time, index)
std::shared_ptr< Transform3D > createCylindricTransform (const Vector3D &nposition, double angleX, double angleY)
std::shared_ptr< Transform3D > createPlanarTransform (const Vector3D &nposition, const Vector3D &nnormal, double angleT, double angleU)
BoundToFreeMatrix convertToMatrix (const std::array< double, 60 > P)
template<typename Parameters >
void testJacobianToGlobal (const Parameters &pars)
BOOST_AUTO_TEST_CASE (JacobianCurvilinearToGlobalTest)
This tests the jacobian of local curvilinear -> global.
BOOST_AUTO_TEST_CASE (JacobianCylinderToGlobalTest)
This tests the jacobian of local cylinder -> global.
BOOST_AUTO_TEST_CASE (JacobianDiscToGlobalTest)
This tests the jacobian of local disc -> global.
BOOST_AUTO_TEST_CASE (JacobianPlaneToGlobalTest)
This tests the jacobian of local plane -> global.
BOOST_AUTO_TEST_CASE (JacobianPerigeeToGlobalTest)
This tests the jacobian of local perigee -> global.
BOOST_AUTO_TEST_CASE (JacobianStrawToGlobalTest)
This tests the jacobian of local straw -> global.
BOOST_AUTO_TEST_CASE (kalman_extrapolator)
Unit test for Kalman fitter propagation.
BOOST_DATA_TEST_CASE (loop_aborter_test, bdata::random((bdata::seed=21, bdata::distribution=std::uniform_real_distribution<>(-M_PI, M_PI)))^bdata::random((bdata::seed=22, bdata::distribution=std::uniform_real_distribution<>(-M_PI, M_PI)))^bdata::xrange(1), phi, deltaPhi, index)
BOOST_DATA_TEST_CASE (propagator_loop_protection_test, bdata::random((bdata::seed=20, bdata::distribution=std::uniform_real_distribution<>(0.5_GeV, 10_GeV)))^bdata::random((bdata::seed=21, bdata::distribution=std::uniform_real_distribution<>(-M_PI, M_PI)))^bdata::random((bdata::seed=22, bdata::distribution=std::uniform_real_distribution<>(1.0, M_PI-1.0)))^bdata::random((bdata::seed=23, bdata::distribution=std::uniform_int_distribution<>(0, 1)))^bdata::xrange(ntests), pT, phi, theta, charge, index)
BField bField (0, 0, Bz)
EigenPropagator epropagator (std::move(estepper), std::move(navigatorES))
StraightLinePropagator slpropagator (std::move(slstepper), std::move(navigatorSL))
template<typename propagator_t >
void runTest (const propagator_t &prop, double pT, double phi, double theta, int charge, double time, int index)
BOOST_DATA_TEST_CASE (test_material_collector, bdata::random((bdata::seed=20, bdata::distribution=std::uniform_real_distribution<>(0.5_GeV, 10_GeV)))^bdata::random((bdata::seed=21, bdata::distribution=std::uniform_real_distribution<>(-M_PI, M_PI)))^bdata::random((bdata::seed=22, bdata::distribution=std::uniform_real_distribution<>(1.0, M_PI-1.0)))^bdata::random((bdata::seed=23, bdata::distribution=std::uniform_int_distribution<>(0, 1)))^bdata::random((bdata::seed=24, bdata::distribution=std::uniform_int_distribution<>(0, 100)))^bdata::xrange(ntests), pT, phi, theta, charge, time, index)
template<typename stepper_state_t >
void step (stepper_state_t &sstate)
BOOST_AUTO_TEST_CASE (Navigator_methods)
EigenPropagatorType epropagator (std::move(estepper))
BOOST_AUTO_TEST_CASE (PropagatorOptions_)
BOOST_DATA_TEST_CASE (cylinder_passage_observer_, bdata::random((bdata::seed=0, bdata::distribution=std::uniform_real_distribution<>(0.4_GeV, 10_GeV)))^bdata::random((bdata::seed=1, bdata::distribution=std::uniform_real_distribution<>(-M_PI, M_PI)))^bdata::random((bdata::seed=2, bdata::distribution=std::uniform_real_distribution<>(1.0, M_PI-1.0)))^bdata::random((bdata::seed=3, bdata::distribution=std::uniform_int_distribution<>(0, 1)))^bdata::random((bdata::seed=4, bdata::distribution=std::uniform_int_distribution<>(0, 100)))^bdata::xrange(ntests), pT, phi, theta, charge, time, index)
BOOST_DATA_TEST_CASE (curvilinear_additive_, bdata::random((bdata::seed=0, bdata::distribution=std::uniform_real_distribution<>(0.4_GeV, 10_GeV)))^bdata::random((bdata::seed=1, bdata::distribution=std::uniform_real_distribution<>(-M_PI, M_PI)))^bdata::random((bdata::seed=2, bdata::distribution=std::uniform_real_distribution<>(1.0, M_PI-1.0)))^bdata::random((bdata::seed=3, bdata::distribution=std::uniform_int_distribution<>(0, 1)))^bdata::random((bdata::seed=4, bdata::distribution=std::uniform_int_distribution<>(0, 100)))^bdata::xrange(ntests), pT, phi, theta, charge, time, index)
BOOST_DATA_TEST_CASE (cylinder_additive_, bdata::random((bdata::seed=0, bdata::distribution=std::uniform_real_distribution<>(0.4_GeV, 10_GeV)))^bdata::random((bdata::seed=1, bdata::distribution=std::uniform_real_distribution<>(-M_PI, M_PI)))^bdata::random((bdata::seed=2, bdata::distribution=std::uniform_real_distribution<>(1.0, M_PI-1.0)))^bdata::random((bdata::seed=3, bdata::distribution=std::uniform_int_distribution<>(0, 1)))^bdata::random((bdata::seed=4, bdata::distribution=std::uniform_int_distribution<>(0, 100)))^bdata::xrange(ntests), pT, phi, theta, charge, time, index)
BOOST_AUTO_TEST_CASE (eigen_stepper_state_test)
These tests are aiming to test whether the state setup is working properly.
BOOST_AUTO_TEST_CASE (eigen_stepper_test)
BOOST_AUTO_TEST_CASE (step_extension_vacuum_test)
This function tests the EigenStepper with the DefaultExtension and the DenseEnvironmentExtension. The focus of this tests lies in the choosing of the right extension for the individual use case. This is performed with three different detectors: a) Pure vaccuum -> DefaultExtension needs to act b) Pure Be -> DenseEnvironmentExtension needs to act c) Vacuum - Be - Vacuum -> Both should act and switch during the propagation.
BOOST_AUTO_TEST_CASE (step_extension_material_test)
BOOST_AUTO_TEST_CASE (step_extension_vacmatvac_test)
BOOST_AUTO_TEST_CASE (step_extension_trackercalomdt_test)
BOOST_AUTO_TEST_CASE (straight_line_stepper_state_test)
These tests are aiming to test whether the state setup is working properly.
BOOST_AUTO_TEST_CASE (straight_line_stepper_test)
Vector2D offset (-2., 2.)
BOOST_AUTO_TEST_CASE (AnnulusBoundsConstruction)
BOOST_AUTO_TEST_CASE (AnnulusBoundsRecreation)
BOOST_AUTO_TEST_CASE (AnnulusBoundsExcpetion)
BOOST_AUTO_TEST_CASE (AnnulusBoundsProperties)
Unit tests for AnnulusBounds properties.
BOOST_AUTO_TEST_CASE (BoundaryCheckBoxSimple)
BOOST_AUTO_TEST_CASE (BoundaryCheckBoxToleranceLoc0)
BOOST_AUTO_TEST_CASE (BoundaryCheckBoxDistance)
BOOST_AUTO_TEST_CASE (BoundaryCheckBoxCovariance)
BOOST_AUTO_TEST_CASE (BoundaryCheckPolyDistance)
BOOST_AUTO_TEST_CASE (BoundaryCheckTriangleSimple)
BOOST_AUTO_TEST_CASE (BoundaryCheckTriangleCovariance)
BOOST_AUTO_TEST_CASE (ConeBoundsConstruction)
Unit test for creating compliant/non-compliant ConeBounds object.
BOOST_AUTO_TEST_CASE (ConeBoundsRecreation)
BOOST_AUTO_TEST_CASE (ConeBoundsExceptions)
BOOST_AUTO_TEST_CASE (ConeBoundsProperties)
Unit tests for properties of ConeBounds object.
BOOST_AUTO_TEST_CASE (ConeBoundsAssignment)
BOOST_AUTO_TEST_CASE (ConeSurfaceConstruction)
Unit test for creating compliant/non-compliant ConeSurface object.
BOOST_AUTO_TEST_CASE (ConeSurfaceProperties)
Unit test for testing ConeSurface properties.
BOOST_AUTO_TEST_CASE (EqualityOperators)
BOOST_AUTO_TEST_CASE (ConvexPolygonBoundsConvexity)
BOOST_AUTO_TEST_CASE (ConvexPolygonBoundsConstruction)
BOOST_AUTO_TEST_CASE (ConvexPolygonBoundsRecreation)
BOOST_AUTO_TEST_CASE (ConvexPolygonBoundsDynamicTest)
BOOST_AUTO_TEST_CASE (CylinderBoundsConstruction)
Unit test for creating compliant/non-compliant CylinderBounds object.
BOOST_AUTO_TEST_CASE (CylinderBoundsRecreation)
BOOST_AUTO_TEST_CASE (CylinderBoundsException)
BOOST_AUTO_TEST_CASE (CylinderBoundsProperties)
Unit tests for CylinderBounds properties.
BOOST_AUTO_TEST_CASE (CylinderBoundsAssignment)
Unit test for testing CylinderBounds assignment.
BOOST_AUTO_TEST_CASE (CylinderSurfaceConstruction)
Unit test for creating compliant/non-compliant CylinderSurface object.
BOOST_AUTO_TEST_CASE (CylinderSurfaceProperties)
Unit test for testing CylinderSurface properties.
BOOST_AUTO_TEST_CASE (DiamondBoundsConstruction)
Unit test for creating compliant/non-compliant DiamondBounds object.
BOOST_AUTO_TEST_CASE (DiamondBoundsProperties)
Unit tests for DiamondBounds properties.
BOOST_AUTO_TEST_CASE (DiamondBoundsAssignment)
Unit test for testing DiamondBounds assignment.
BOOST_AUTO_TEST_CASE (DiscSurface_constructors_test)
Unit tests for creating DiscSurface object.
BOOST_AUTO_TEST_CASE (DiscSurface_properties_test,*utf::expected_failures(2))
Unit tests of all named methods.
BOOST_AUTO_TEST_CASE (DiscSurface_assignment_test)
Unit test for testing DiscSurface assignment and equality.
BOOST_AUTO_TEST_CASE (DiscTrapezoidBoundsConstruction)
Unit tests for DiscTrapezoidBounds constrcuctors.
BOOST_AUTO_TEST_CASE (DiscTrapezoidBoundsRecreation)
BOOST_AUTO_TEST_CASE (DiscTrapezoidBoundsExceptions)
BOOST_AUTO_TEST_CASE (DiscTrapezoidBoundsProperties)
Unit tests for DiscTrapezoidBounds properties.
BOOST_AUTO_TEST_CASE (DiscTrapezoidBoundsAssignment)
Unit test for testing DiscTrapezoidBounds assignment.
BOOST_AUTO_TEST_CASE (EllipseBoundsConstruction)
Unit test for creating compliant/non-compliant EllipseBounds object.
BOOST_AUTO_TEST_CASE (EllipseBoundsRecreation)
BOOST_AUTO_TEST_CASE (EllipseBoundsProperties)
Unit tests for EllipseBounds properties.
BOOST_AUTO_TEST_CASE (EllipseBoundsAssignment)
Unit test for testing EllipseBounds assignment.
BOOST_AUTO_TEST_CASE (InfiniteBoundsConstruction)
Unit test for creating compliant/non-compliant InfiniteBounds object.
BOOST_AUTO_TEST_CASE (InfiniteBoundsProperties)
Unit tests for InfiniteBounds properties.
BOOST_AUTO_TEST_CASE (LineBoundsConstruction)
Unit test for creating compliant/non-compliant LineBounds object.
BOOST_AUTO_TEST_CASE (LineBoundsRecreation)
Unit test for testing LineBounds recreation from streaming.
BOOST_AUTO_TEST_CASE (LineBoundsExceptions)
Unit test for testing LineBounds exceptions.
BOOST_AUTO_TEST_CASE (LineBoundsAssignment)
Unit test for testing LineBounds assignment.
BOOST_AUTO_TEST_CASE (LineBoundsProperties)
Unit tests for LineBounds properties.
BOOST_AUTO_TEST_CASE (LineSurface_Constructors_test)
Unit test for creating compliant/non-compliant LineSurface object.
BOOST_AUTO_TEST_CASE (LineSurface_allNamedMethods_test)
Unit tests of all named methods.
BOOST_AUTO_TEST_CASE (LineSurface_assignment_test)
Unit test for testing LineSurface assignment.
BOOST_AUTO_TEST_CASE (PerigeeSurfaceConstruction)
Unit test for creating compliant/non-compliant PerigeeSurface object.
BOOST_AUTO_TEST_CASE (PerigeeSurfaceProperties)
Unit test for testing PerigeeSurface properties.
BOOST_AUTO_TEST_CASE (PlaneSurfaceConstruction)
Unit test for creating compliant/non-compliant PlaneSurface object.
BOOST_AUTO_TEST_CASE (PlaneSurfaceProperties)
Unit test for testing PlaneSurface properties.
BOOST_AUTO_TEST_CASE (ConeSurfacePolyhedrons)
Unit tests for Cone Surfaces.
BOOST_AUTO_TEST_CASE (CylinderSurfacePolyhedrons)
Unit tests for Cylinder Surfaces.
BOOST_AUTO_TEST_CASE (DiscSurfacePolyhedrons)
Unit tests for Disc Surfaces.
BOOST_AUTO_TEST_CASE (PlaneSurfacePolyhedrons)
Unit tests for Plane Surfaces.
BOOST_AUTO_TEST_CASE (RadialBoundsConstruction)
Unit tests for RadialBounds constrcuctors.
BOOST_AUTO_TEST_CASE (RadialBoundsRecreation)
BOOST_AUTO_TEST_CASE (RadialBoundsException)
BOOST_AUTO_TEST_CASE (RadialBoundsProperties)
Unit tests for RadialBounds properties.
BOOST_AUTO_TEST_CASE (RadialBoundsAssignment)
Unit test for testing RadialBounds assignment.
void dumpVertices (const RectangleBounds &r)
bool approximatelyEqual (const Vector2D &a, const Vector2D &b)
BOOST_AUTO_TEST_CASE (RectangleBoundsConstruction)
Unit test for creating compliant/non-compliant RectangleBounds object.
BOOST_AUTO_TEST_CASE (RectangleBoundsRecreation)
Recreation.
BOOST_AUTO_TEST_CASE (RectangleBoundsProperties)
Unit test for testing RectangleBounds properties.
BOOST_AUTO_TEST_CASE (RectangleBoundsAssignment)
BOOST_AUTO_TEST_CASE (StrawSurfaceConstruction)
Unit test for creating compliant/non-compliant StrawSurface object.
BOOST_AUTO_TEST_CASE (StrawSurfaceProperties)
Unit test for testing StrawSurface properties.
BOOST_FIXTURE_TEST_CASE (SurfaceArray_create, SurfaceArrayFixture)
BOOST_AUTO_TEST_CASE (SurfaceArray_singleElement)
BOOST_AUTO_TEST_CASE (SurfaceBoundsConstruction)
Unit test for creating compliant/non-compliant SurfaceBounds object.
BOOST_AUTO_TEST_CASE (SurfaceBoundsProperties)
BOOST_AUTO_TEST_CASE (SurfaceBoundsEquality)
Unit test for testing SurfaceBounds properties.
BOOST_AUTO_TEST_CASE (CylinderIntersectionTests)
BOOST_AUTO_TEST_CASE (ConeIntersectionTest)
BOOST_AUTO_TEST_CASE (PlanarIntersectionTest)
BOOST_AUTO_TEST_CASE (LineIntersectionTest)
BOOST_AUTO_TEST_CASE (SurfaceConstruction)
todo: make test fixture; separate out different cases
BOOST_AUTO_TEST_CASE (SurfaceProperties,*utf::expected_failures(1))
Unit test for testing Surface properties.
BOOST_AUTO_TEST_CASE (TrapezoidBoundsConstruction)
Unit test for creating compliant/non-compliant TrapezoidBounds object.
BOOST_AUTO_TEST_CASE (TrapezoidBoundsRecreated)
Unit test for creating compliant/non-compliant TrapezoidBounds object.
BOOST_AUTO_TEST_CASE (TrapezoidBoundsException)
BOOST_AUTO_TEST_CASE (TrapezoidBoundsProperties,*utf::expected_failures(3))
Unit tests for TrapezoidBounds properties.
BOOST_AUTO_TEST_CASE (TrapezoidBoundsAssignment)
Unit test for testing TrapezoidBounds assignment.
BOOST_AUTO_TEST_CASE (comb_kalman_filter_zero_field)
Unit test for CombinatorialKalmanFilter with measurements along the x-axis.
BOOST_AUTO_TEST_CASE (annealing_tool_singleChi2_tests)
BOOST_AUTO_TEST_CASE (annealing_tool_multiChi2_tests)
BOOST_AUTO_TEST_CASE (equidistant_axis)
BOOST_AUTO_TEST_CASE (variable_axis)
BOOST_AUTO_TEST_CASE (open_axis)
BOOST_AUTO_TEST_CASE (closed_axis)
BOOST_AUTO_TEST_CASE (neighborhood)
BOOST_AUTO_TEST_CASE (wrapBin)
BOOST_AUTO_TEST_CASE (bfield_creation)
BOOST_AUTO_TEST_CASE (bfield_symmetry)
BOOST_DATA_TEST_CASE (bfield_symmetry_random, bdata::random((bdata::seed=0, bdata::distribution=std::uniform_real_distribution<>(-10., 10.)))^bdata::random((bdata::seed=0, bdata::distribution=std::uniform_real_distribution<>(-10., 10.)))^bdata::random((bdata::seed=0, bdata::distribution=std::uniform_real_distribution<>(-20., 20.)))^bdata::xrange(10), x, y, z, index)
Unit test for testing the decomposeToSurfaces() function.
Vector3D xyzPosition (0.5, 1.5, 2.5)
Vector3D xyzPositionOutside (30.,-30., 200.)
Vector3D phi0Position (0.5, 0., 2.5)
Vector3D phiPihPosition (0., 1.5, 2.5)
Vector3D eta0Position (0.5, 1.5, 0.)
Vector2D xyPosition (0.5, 1.5)
Vector2D rphizPosition (0.1, 2.5)
Vector2D rphiPosition (3.5, M_PI/8.)
BinningData xData_add (open, binX, main_sstr, std::move(xData_sstr_add))
BOOST_AUTO_TEST_CASE (BinningData_BinningValue)
BOOST_AUTO_TEST_CASE (BinningData_bins)
BOOST_AUTO_TEST_CASE (BinningData_inside_outside)
BOOST_AUTO_TEST_CASE (BinningData_open_close)
BOOST_AUTO_TEST_CASE (BinningData_boundaries)
BOOST_AUTO_TEST_CASE (BinningData_bincenter)
BOOST_AUTO_TEST_CASE (BinningData_phi_modules)
BOOST_AUTO_TEST_CASE (BinUtility_equidistant_binning)
BOOST_AUTO_TEST_CASE (box_construction)
BOOST_AUTO_TEST_CASE (intersect_points)
BOOST_AUTO_TEST_CASE (intersect_rays)
BOOST_AUTO_TEST_CASE (ray_obb_intersect)
BOOST_AUTO_TEST_CASE (frustum_intersect)
BOOST_AUTO_TEST_CASE (Extendable_)
BOOST_AUTO_TEST_CASE (Transitions)
BOOST_AUTO_TEST_CASE (Terminted)
BOOST_AUTO_TEST_CASE (Arguments)
BOOST_AUTO_TEST_CASE (InternalTransitions)
BOOST_AUTO_TEST_CASE (frustum_construction)
BOOST_AUTO_TEST_CASE (grid_test_1d_equidistant)
BOOST_AUTO_TEST_CASE (grid_test_2d_equidistant)
BOOST_AUTO_TEST_CASE (grid_test_3d_equidistant)
BOOST_AUTO_TEST_CASE (grid_test_1d_variable)
BOOST_AUTO_TEST_CASE (grid_test_2d_variable)
BOOST_AUTO_TEST_CASE (grid_test_3d_variable)
BOOST_AUTO_TEST_CASE (grid_test_2d_mixed)
BOOST_AUTO_TEST_CASE (grid_test_2d_mixed_at)
BOOST_AUTO_TEST_CASE (grid_interpolation)
BOOST_AUTO_TEST_CASE (closestPoints)
BOOST_AUTO_TEST_CASE (bitset_to_matrix_to_bitset)
BOOST_AUTO_TEST_CASE (phi_helper_test)
BOOST_AUTO_TEST_CASE (perp_helper_test)
BOOST_AUTO_TEST_CASE (theta_eta_test_helper)
BOOST_AUTO_TEST_CASE (cross_test_helper)
BOOST_AUTO_TEST_CASE (toString_test_helper)
BOOST_AUTO_TEST_CASE (shared_vector_helper_test)
BOOST_AUTO_TEST_CASE (time_helper_test)
BOOST_AUTO_TEST_CASE (position_helper_test)
BOOST_AUTO_TEST_CASE (test_matrix_dimension_switch)
BOOST_AUTO_TEST_CASE (interpolation_1d)
BOOST_AUTO_TEST_CASE (interpolation_2d)
BOOST_AUTO_TEST_CASE (interpolation_3d)
BOOST_AUTO_TEST_CASE (interpolation_mixed_point_values)
BOOST_AUTO_TEST_CASE (IntersectionTest)
test of the intersection class
BOOST_AUTO_TEST_CASE (ObjectIntersectionTest)
test of the object intersection class
BOOST_AUTO_TEST_CASE (FATAL_test)
unit test for FATAL debug level
BOOST_AUTO_TEST_CASE (ERROR_test)
unit test for ERROR debug level
BOOST_AUTO_TEST_CASE (WARNING_test)
unit test for WARNING debug level
BOOST_AUTO_TEST_CASE (INFO_test)
unit test for INFO debug level
BOOST_AUTO_TEST_CASE (DEBUG_test)
unit test for DEBUG debug level
BOOST_AUTO_TEST_CASE (VERBOSE_test)
unit test for VERBOSE debug level
BOOST_AUTO_TEST_CASE (materialmap_creation)
BOOST_AUTO_TEST_CASE (all_of_test)
BOOST_AUTO_TEST_CASE (hana_set_union_test)
BOOST_AUTO_TEST_CASE (hana_set_to_tuple_test)
BOOST_AUTO_TEST_CASE (unpack_boost_set_as_template_test)
BOOST_AUTO_TEST_CASE (type_collector_test)
BOOST_AUTO_TEST_CASE (has_duplicates_test)
BOOST_AUTO_TEST_CASE (any_of_test)
BOOST_AUTO_TEST_CASE (are_sorted_helper_tests)
Unit test for Acts::anonymous_namespace{ParameterSet.h}::are_sorted helper.
BOOST_AUTO_TEST_CASE (are_within_helper_tests)
Unit test for Acts::anonymous_namespace{ParameterSet.h}::are_within helper.
BOOST_AUTO_TEST_CASE (at_index_helper_tests)
Unit test for Acts::details::at_index helper.
BOOST_AUTO_TEST_CASE (ray_construction)
BOOST_AUTO_TEST_CASE (RealQuadraticEquationConstruction)
Unit test for creating RealQuadraticEquation object.
BOOST_AUTO_TEST_CASE (RealQuadraticEquationProperties)
Unit test for RealQuadraticEquation properties.
BOOST_AUTO_TEST_CASE (RealQuadraticEquationAssignment)
Unit test for testing RealQuadraticEquation assignment.
BOOST_AUTO_TEST_CASE (TestConstruction)
BOOST_AUTO_TEST_CASE (TestErrorCodes)
Result< NoCopy > make_nocopy (int i, bool v=true)
BOOST_AUTO_TEST_CASE (CopyBehaviour)
Result< void > void_res_func (int b)
BOOST_AUTO_TEST_CASE (VoidResult)
BOOST_AUTO_TEST_CASE (BoolResult)
METHOD_TRAIT (foo_method_t, foo)
METHOD_TRAIT (bar_method_t, bar)
BOOST_AUTO_TEST_CASE (TypeTraitsMethods)
BOOST_AUTO_TEST_CASE (TypeTraitsMember)
BOOST_AUTO_TEST_CASE (TypeTraitsNestedType)
BOOST_AUTO_TEST_CASE (TypeTraitsConcepts)
BOOST_AUTO_TEST_CASE (adaptive_multi_vertex_finder_test)
BOOST_AUTO_TEST_CASE (adaptive_multi_vertex_finder_usertype_test)
std::uniform_real_distribution vXYDist (-0.1_mm, 0.1_mm)
std::uniform_real_distribution vZDist (-20_mm, 20_mm)
std::uniform_real_distribution d0Dist (-0.01_mm, 0.01_mm)
std::uniform_real_distribution z0Dist (-0.2_mm, 0.2_mm)
std::uniform_real_distribution pTDist (1._GeV, 30._GeV)
std::uniform_real_distribution phiDist (-M_PI, M_PI)
std::uniform_real_distribution thetaDist (1.0, M_PI-1.0)
std::uniform_real_distribution qDist (-1, 1)
std::uniform_real_distribution resIPDist (0., 100._um)
std::uniform_real_distribution resAngDist (0., 0.1)
std::uniform_real_distribution resQoPDist (-0.1, 0.1)
std::uniform_int_distribution nTracksDist (3, 10)
BOOST_AUTO_TEST_CASE (adaptive_multi_vertex_fitter_test)
Unit test for AdaptiveMultiVertexFitter.
BOOST_AUTO_TEST_CASE (adaptive_multi_vertex_fitter_test_athena)
Unit test for AdaptiveMultiVertexFitter based on Athena unit test, i.e. same setting and test values are used here.
std::vector< BoundParameters > getAthenaTracks ()
BOOST_AUTO_TEST_CASE (billoir_vertex_fitter_empty_input_test)
Unit test for FullBilloirVertexFitter.
std::uniform_real_distribution pTDist (0.4_GeV, 10_GeV)
std::uniform_real_distribution resIPDist (0., 100_um)
BOOST_AUTO_TEST_CASE (billoir_vertex_fitter_defaulttrack_test)
Unit test for FullBilloirVertexFitter with default input track type (= BoundParameters)
BOOST_AUTO_TEST_CASE (billoir_vertex_fitter_usertrack_test)
Unit test for FullBilloirVertexFitter with user-defined InputTrack type.
std::uniform_real_distribution pTDist (0.4_GeV, 10._GeV)
BOOST_AUTO_TEST_CASE (impactpoint_estimator_params_distance_test)
Unit test for ImpactPointEstimator params and distance.
BOOST_AUTO_TEST_CASE (impactpoint_estimator_compatibility_test)
Unit test for ImpactPointEstimator compatibility estimator.
BOOST_AUTO_TEST_CASE (impactpoint_estimator_athena_test)
Unit test for ImpactPoint 3d estimator, using same configuration and test values as in Athena unit test algorithm Tracking/TrkVertexFitter/TrkVertexFitterUtils/test/ImpactPointEstimator_test.
BOOST_AUTO_TEST_CASE (impactpoint_estimator_parameter_estimation_test)
Unit test for impact parameter estimation.
std::uniform_int_distribution nVertexDist (1, 6)
std::uniform_int_distribution nTracksDist (5, 15)
BOOST_AUTO_TEST_CASE (iterative_finder_test)
Unit test for IterativeVertexFinder for BoundParameters.
BOOST_AUTO_TEST_CASE (iterative_finder_test_user_track_type)
Unit test for IterativeVertexFinder for user defined InputTrack track type.
BOOST_AUTO_TEST_CASE (Kalman_Vertex_TrackUpdater)
Unit test for KalmanVertexTrackUpdater.
BOOST_AUTO_TEST_CASE (Kalman_Vertex_Updater)
Unit test for KalmanVertexUpdater.
BOOST_AUTO_TEST_CASE (linearized_track_factory_test)
Unit test for HelicalTrackLinearizer.
BOOST_AUTO_TEST_CASE (linearized_track_factory_straightline_test)
Unit test for HelicalTrackLinearizer.
BOOST_AUTO_TEST_CASE (track_density_finder_test)
Unit test for TrackDensityVertexFinder using same configuration and values as VertexSeedFinderTestAlg in Athena implementation, i.e. tests if reordering tracks returns the same result.
BOOST_AUTO_TEST_CASE (track_density_finder_constr_test)
Unit test for TrackDensityVertexFinder using same configuration and values as VertexSeedFinderTestAlg in Athena implementation.
std::normal_distribution< double > xdist (1_mm, 0.1_mm)
std::normal_distribution< double > ydist (-0.7_mm, 0.1_mm)
std::normal_distribution< double > z1dist (zVertexPos *1_mm, 1_mm)
std::normal_distribution< double > z2dist (-3_mm, 0.5_mm)
std::uniform_real_distribution
< double > pTDist (0.1_GeV, 100_GeV)
std::uniform_real_distribution
< double > etaDist (-4., 4.)
BOOST_AUTO_TEST_CASE (track_density_finder_random_test)
Unit test for TrackDensityVertexFinder using same configuration and values as VertexSeedFinderTestAlg in Athena implementation.
BOOST_AUTO_TEST_CASE (track_density_finder_usertrack_test)
Unit test for TrackDensityVertexFinder with user-defined input track type with same values as in other tests.
BOOST_AUTO_TEST_CASE (zscan_finder_test)
Unit test for ZScanVertexFinder.
BOOST_AUTO_TEST_CASE (zscan_finder_usertrack_test)
Unit test for ZScanVertexFinder with user-defined input track type.
BOOST_AUTO_TEST_CASE (EventDataVisualizationObj)
BOOST_AUTO_TEST_CASE (EventDataVisualizationPly)
BOOST_AUTO_TEST_CASE (VisualizationHelpers)
BOOST_AUTO_TEST_CASE (PrimitivesVisualizationObj)
BOOST_AUTO_TEST_CASE (PrimitivesVisualizationPly)
BOOST_AUTO_TEST_CASE (SurfaceVisualizationObj)
This tests if the corresponding obj output is well formatted.
BOOST_AUTO_TEST_CASE (SurfaceVisualizationPly)
This tests if the corresponding ply output is well formatted.
static std::vector< std::string > testObjString (const std::string &tString, bool triMesh=false)
static std::vector< std::string > testPlyString (const std::string &tString, bool triMesh=false)
BOOST_AUTO_TEST_CASE (VisualizationTesterObj)
BOOST_AUTO_TEST_CASE (VisualizationTesterPly)
BOOST_AUTO_TEST_CASE (VisualizationConstruction)
BOOST_AUTO_TEST_CASE (PlyOutputTest)
BOOST_AUTO_TEST_CASE (ObjOutputTest)
BOOST_AUTO_TEST_CASE (VolumeVisualizationObj)
BOOST_AUTO_TEST_CASE (VolumeVisualizationPly)
BOOST_AUTO_TEST_CASE (cartesian_segmentation)
Unit test for the Cartesian segmentation.
BOOST_AUTO_TEST_CASE (create_Clusters1)
BOOST_AUTO_TEST_CASE (create_Clusters2)
BOOST_DATA_TEST_CASE (DoubleHitsSpacePointBuilder_basic, bdata::xrange(1), index)
BOOST_DATA_TEST_CASE (readout_counter_test, bdata::random((bdata::seed=0, bdata::distribution=std::uniform_real_distribution<>(-halfX+sguardX, halfX-sguardX)))^bdata::random((bdata::seed=1, bdata::distribution=std::uniform_real_distribution<>(-halfX+sguardX, halfX-sguardX)))^bdata::random((bdata::seed=2, bdata::distribution=std::uniform_real_distribution<>(-halfY, halfY)))^bdata::random((bdata::seed=3, bdata::distribution=std::uniform_int_distribution<>(-halfY, halfY)))^bdata::xrange(ntests), entryX, entryY, exitX, exitY, index)
BOOST_DATA_TEST_CASE (SingleHitSpacePointBuilder_basic, bdata::xrange(1), index)
BOOST_AUTO_TEST_CASE (Json_conversion)
Variables
unsigned int ntests = 10
unsigned int nrepts = 2000
const bool boundaryCheck = false
const bool testPlane = true
const bool testDisc = true
const bool testCylinder = true
const bool testStraw = true
GeometryContext tgContext = GeometryContext()
Transform3D at
auto rb = std::make_shared<RectangleBounds>(1_m, 1_m)
auto aPlane
auto db = std::make_shared<RadialBounds>(0.2_m, 1.2_m)
auto aDisc
auto cb = std::make_shared<CylinderBounds>(10_m, 100_m)
auto aCylinder
auto aStraw
constexpr size_t bench_iters = 1'000
GeometryContext gctx = GeometryContext()
ActsSymMatrixD< 1 > cov1D
ActsSymMatrixD< 2 > cov2D
bool debugMode = false
MagneticFieldContext mfContext = MagneticFieldContext()
CalibrationContext calContext = CalibrationContext()
double dX
double dY
Vector3D pos
const Surface * sur
double hx {10.}
double hy {20.}
double hz {30.}
double surfaceHalfLengthZ = 50_mm
double surfaceRstagger = 5_mm
double surfaceZoverlap = 10_mm
double layerEnvelope = 0.5_mm
double volumeEnvelope = 10_mm
double iiv_surfaceR = 25_mm
double iiv_volumeR
double iov_surfaceR = 100_mm
inner outer volume defininitions
double iov_volumeR
auto iiVolume
inner inner volume
auto ioVolume
inner outer volume
double volumeHalfZ
auto iVolume
the inner volume
double ov_surfaceR = 150_mm
double ov_volumeR
auto oVolume
inner outer volume
auto volume
the inner volume
TrackingGeometry tGeometry (volume) = cGeometry()
auto world = tGeometry.highestTrackingVolume()
double iVsurfaceHalfLengthZ = 50_mm
double iVsurfaceR = 25_mm
double iVsurfaceRstagger = 5_mm
double iVsurfaceZoverlap = 10_mm
double iVlayerEnvelope = 0.5_mm
double iVvolumeEnvelope = 10_mm
double iVvolumeR
double oVsurfaceHalfLengthZ = 50_mm
the surface radius (will also be the layer radius)
double oVsurfaceR = 100_mm
double oVsurfaceRstagger = 5_mm
double oVsurfaceZoverlap = 10_mm
double oVlayerEnvelope = 0.5_mm
double oVvolumeEnvelope = 10_mm
double oVvolumeR
double oVvolumeHalfZ
auto hVolume
auto [volumes, tg] = gridBoxFactory()
constexpr unsigned int dim = 2
constexpr float eps = 1.0f / 255u
template<typename P , typename S , typename... As>
constexpr bool signature_check
CylindricalTrackingGeometry cGeometry (tgContext)
Navigator navigator (tGeometry)
DirectNavigator dnavigator
const double Bz = 2_T
BField bField (0, 0, Bz)
Stepper estepper (bField)
Stepper dstepper (bField)
const int skip = 0
bool referenceTiming = false
bool oversteppingTest = false
double oversteppingMaxStepSize = 1_mm
std::vector< std::unique_ptr
< const Surface > > stepState
Navigator navigatorES (tGeometry)
Navigator navigatorSL (tGeometry)
StraightLineStepper slstepper
bool debugModeFwd = false
bool debugModeBwd = false
bool debugModeFwdStep = false
bool debugModeBwdStep = false
bool debug = true
auto mCylinder = std::make_shared<CylinderBounds>(10_mm, 1000_mm)
auto mSurface = Surface::makeShared<CylinderSurface>(nullptr, mCylinder)
auto cCylinder = std::make_shared<CylinderBounds>(150_mm, 1000_mm)
auto cSurface = Surface::makeShared<CylinderSurface>(nullptr, cCylinder)
double minRadius = 7.2
double maxRadius = 12.0
double minPhi = 0.74195
double maxPhi = 1.33970
GeometryContext testContext = GeometryContext()
std::vector< std::tuple
< std::string, bool, unsigned
int > > testModes
auto transform = std::make_shared<Transform3D>(Transform3D::Identity())
BinningData xData_eq (open, binX, 10, 0., 10.)
BinningData yData_eq (open, binY, 10, 0., 10.)
BinningData zData_eq (open, binZ, 10, 0., 10.)
BinningData rData_eq (open, binR, 10, 0., 10.)
BinningData phiData_eq (closed, binPhi, 5,-M_PI, M_PI)
BinningData rPhiData_eq (closed, binRPhi, 5,-M_PI, M_PI)
BinningData hData_eq (open, binH, 5, 0., 10.)
BinningData etaData_eq (open, binEta, 5,-2.5, 2.5)
std::vector< float > values = {0., 1., 2., 3., 4., 10.}
BinningData xData_arb (open, binX, values)
BinningData yData_arb (open, binY, values)
std::vector< float > phiValues = {-M_PI, -2., -1., 1., 2., M_PI}
BinningData phiData_arb (closed, binPhi, phiValues)
size_t nBins_binary = 59
double valueMin = 0.
double phiMin = -M_PI
double delta = 0.5
double phiDelta = 0.1064
std::vector< float > sstr = {0., 1., 1.5, 2., 3.}
auto xData_sstr_mult = std::make_unique<const BinningData>(open, binX, sstr)
BinningData xData_mult (open, binX, 3, 0., 9., std::move(xData_sstr_mult))
std::vector< float > main_sstr = {0., 3., 4., 5.}
additive
auto xData_sstr_add = std::make_unique<const BinningData>(open, binX, sstr)
template<typename T >
constexpr bool SomeConcept
GeometryContext geoContext = GeometryContext()
MagneticFieldContext magFieldContext = MagneticFieldContext()
const double zVertexPos = 12.
size_t nbinsx = 100
size_t nbinsy = 200
double hThickness = 75_um
double lAngle = 0.1
auto moduleBounds = std::make_shared<const RectangleBounds>(5_mm, 10_mm)
CartesianSegmentation cSegmentation (moduleBounds, nbinsx, nbinsy)
double halfX = 5_mm
double halfY = 10_mm
double tanAlpha = tan(lAngle)
double sguardX = 2 * hThickness * abs(tanAlpha)
DigitizationModule pdModule (cSegmentation, hThickness, 1, lAngle, 0., true)
DigitizationModule ndModule (cSegmentation, hThickness,-1, lAngle, 0., true)
std::vector< DigitizationModule > testModules
PlanarModuleStepper pmStepper
The Planar module stepper.
Detailed Description
Namespace for ATS unit tests.
Typedef Documentation
using Acts::Test::AtlasStepperType = typedef AtlasStepper<BFieldType>
Definition at line 35 of file JacobianTests.cpp.
View newest version in sPHENIX GitHub at line 35 of file JacobianTests.cpp
typedef ConstantBField Acts::Test::BField
Definition at line 47 of file DirectNavigatorTests.cpp.
View newest version in sPHENIX GitHub at line 47 of file DirectNavigatorTests.cpp
typedef ConstantBField Acts::Test::BFieldType
Definition at line 54 of file ExtrapolatorTests.cpp.
View newest version in sPHENIX GitHub at line 54 of file ExtrapolatorTests.cpp
using Acts::Test::BoundTrackState = typedef TrackState<SourceLink, BoundParameters>
Definition at line 33 of file TrackStateTests.cpp.
View newest version in sPHENIX GitHub at line 33 of file TrackStateTests.cpp
using Acts::Test::Box = typedef Acts::Volume::BoundingBox
Definition at line 11 of file TrackingVolumeTests.cpp.
View newest version in sPHENIX GitHub at line 11 of file TrackingVolumeTests.cpp
typedef BoundSymMatrix Acts::Test::Covariance
Definition at line 32 of file MultiTrajectoryTests.cpp.
View newest version in sPHENIX GitHub at line 32 of file MultiTrajectoryTests.cpp
using Acts::Test::CovMat_t = typedef BoundParameters::CovMatrix_t
Definition at line 46 of file MultiTrajectoryTests.cpp.
View newest version in sPHENIX GitHub at line 46 of file MultiTrajectoryTests.cpp
typedef DebugOutputActor Acts::Test::DebugOutput
Definition at line 59 of file KalmanFitterTests.cpp.
View newest version in sPHENIX GitHub at line 59 of file KalmanFitterTests.cpp
typedef std::map< GeometryID::Value, VolumeResolution > Acts::Test::DetectorResolution
Definition at line 57 of file KalmanFitterTests.cpp.
View newest version in sPHENIX GitHub at line 57 of file KalmanFitterTests.cpp
using Acts::Test::DirectPropagator = typedef Propagator<Stepper, DirectNavigator>
Definition at line 50 of file DirectNavigatorTests.cpp.
View newest version in sPHENIX GitHub at line 50 of file DirectNavigatorTests.cpp
using Acts::Test::EAxis = typedef Acts::detail::EquidistantAxis
Definition at line 24 of file MaterialGridHelperTests.cpp.
View newest version in sPHENIX GitHub at line 24 of file MaterialGridHelperTests.cpp
typedef Propagator< EigenStepper, Navigator > Acts::Test::EigenPropagator
Definition at line 142 of file LoopProtectionTests.cpp.
View newest version in sPHENIX GitHub at line 142 of file LoopProtectionTests.cpp
typedef Propagator< EigenStepperType > Acts::Test::EigenPropagatorType
Definition at line 56 of file ExtrapolatorTests.cpp.
View newest version in sPHENIX GitHub at line 56 of file ExtrapolatorTests.cpp
typedef EigenStepper< BField > Acts::Test::EigenStepper
Definition at line 141 of file LoopProtectionTests.cpp.
View newest version in sPHENIX GitHub at line 141 of file LoopProtectionTests.cpp
typedef EigenStepper< BFieldType > Acts::Test::EigenStepperType
Definition at line 55 of file ExtrapolatorTests.cpp.
View newest version in sPHENIX GitHub at line 55 of file ExtrapolatorTests.cpp
typedef std::vector< Resolution > Acts::Test::ElementResolution
Definition at line 55 of file KalmanFitterTests.cpp.
View newest version in sPHENIX GitHub at line 55 of file KalmanFitterTests.cpp
using Acts::Test::EndOfWorld = typedef EndOfWorldReached
Definition at line 34 of file AbortListTests.cpp.
View newest version in sPHENIX GitHub at line 34 of file AbortListTests.cpp
typedef FittableMeasurement< SourceLink > Acts::Test::FittableMeasurement
Definition at line 25 of file MeasurementHelpersTests.cpp.
View newest version in sPHENIX GitHub at line 25 of file MeasurementHelpersTests.cpp
using Acts::Test::Grid2D = typedef Acts::detail::Grid<Acts::AccumulatedVolumeMaterial, EAxis, EAxis>
Definition at line 26 of file MaterialGridHelperTests.cpp.
View newest version in sPHENIX GitHub at line 26 of file MaterialGridHelperTests.cpp
using Acts::Test::Grid3D = typedef Acts::detail::Grid<Acts::AccumulatedVolumeMaterial, EAxis, EAxis, EAxis>
Definition at line 28 of file MaterialGridHelperTests.cpp.
View newest version in sPHENIX GitHub at line 28 of file MaterialGridHelperTests.cpp
using Acts::Test::grid_t = typedef detail::Grid<ActsVectorF<5>, detail::EquidistantAxis, detail::EquidistantAxis>
Definition at line 28 of file InterpolatedMaterialMapTests.cpp.
View newest version in sPHENIX GitHub at line 28 of file InterpolatedMaterialMapTests.cpp
typedef BoundParameters::CovMatrix_t Acts::Test::Jacobian
Definition at line 25 of file GainMatrixSmootherTests.cpp.
View newest version in sPHENIX GitHub at line 25 of file GainMatrixSmootherTests.cpp
typedef HelicalTrackLinearizer< Propagator > Acts::Test::Linearizer
Definition at line 36 of file AdaptiveMultiVertexFinderTests.cpp.
View newest version in sPHENIX GitHub at line 36 of file AdaptiveMultiVertexFinderTests.cpp
using Acts::Test::Linearizer_t = typedef HelicalTrackLinearizer<Propagator>
Definition at line 36 of file ZScanVertexFinderTests.cpp.
View newest version in sPHENIX GitHub at line 36 of file ZScanVertexFinderTests.cpp
using Acts::Test::MaterialGrid2D = typedef Acts::detail::Grid<Acts::ActsVectorF<5>, EAxis, EAxis>
Definition at line 29 of file MaterialGridHelperTests.cpp.
View newest version in sPHENIX GitHub at line 29 of file MaterialGridHelperTests.cpp
using Acts::Test::MaterialGrid3D = typedef Acts::detail::Grid<Acts::ActsVectorF<5>, EAxis, EAxis, EAxis>
Definition at line 31 of file MaterialGridHelperTests.cpp.
View newest version in sPHENIX GitHub at line 31 of file MaterialGridHelperTests.cpp
template<ParID_t... params> typedef Measurement< SourceLink, params...> Acts::Test::MeasurementType
Definition at line 24 of file MeasurementHelpersTests.cpp.
View newest version in sPHENIX GitHub at line 24 of file MeasurementHelpersTests.cpp
template<typename T > using Acts::Test::member_a_t = typedef decltype(std::declval<T>().member_a)
Definition at line 89 of file TypeTraitsTest.cpp.
View newest version in sPHENIX GitHub at line 89 of file TypeTraitsTest.cpp
template<typename T > using Acts::Test::member_b_t = typedef decltype(std::declval<T>().member_b)
Definition at line 92 of file TypeTraitsTest.cpp.
View newest version in sPHENIX GitHub at line 92 of file TypeTraitsTest.cpp
template<typename T > using Acts::Test::member_t = typedef decltype(std::declval<T>().member)
Definition at line 168 of file TypeTraitsTest.cpp.
View newest version in sPHENIX GitHub at line 168 of file TypeTraitsTest.cpp
template<typename T > using Acts::Test::meta_t = typedef typename T::template meta<void, void>
Definition at line 176 of file TypeTraitsTest.cpp.
View newest version in sPHENIX GitHub at line 176 of file TypeTraitsTest.cpp
template<typename T > using Acts::Test::nested_a_t = typedef typename T::NestedA
Definition at line 138 of file TypeTraitsTest.cpp.
View newest version in sPHENIX GitHub at line 138 of file TypeTraitsTest.cpp
template<typename T > using Acts::Test::nested_b_t = typedef typename T::NestedB
Definition at line 140 of file TypeTraitsTest.cpp.
View newest version in sPHENIX GitHub at line 140 of file TypeTraitsTest.cpp
template<typename T > using Acts::Test::nested_t = typedef typename T::Nested
Definition at line 172 of file TypeTraitsTest.cpp.
View newest version in sPHENIX GitHub at line 172 of file TypeTraitsTest.cpp
using Acts::Test::ObjectBBox = typedef Acts::AxisAlignedBoundingBox<Object, float, 3>
Definition at line 32 of file BoundingBoxTest.cpp.
View newest version in sPHENIX GitHub at line 32 of file BoundingBoxTest.cpp
using Acts::Test::par_t = typedef ParID_t
Definition at line 74 of file FittableTypeTests.cpp.
View newest version in sPHENIX GitHub at line 74 of file FittableTypeTests.cpp
using Acts::Test::Parameters = typedef BoundVector
Definition at line 31 of file MultiTrajectoryTests.cpp.
View newest version in sPHENIX GitHub at line 31 of file MultiTrajectoryTests.cpp
template<ParID_t... params> using Acts::Test::ParSet = typedef ParameterSet<params...>
Definition at line 580 of file ParameterSetTests.cpp.
View newest version in sPHENIX GitHub at line 580 of file ParameterSetTests.cpp
using Acts::Test::ParVec_t = typedef BoundParameters::ParVector_t
Definition at line 45 of file MultiTrajectoryTests.cpp.
View newest version in sPHENIX GitHub at line 45 of file MultiTrajectoryTests.cpp
typedef PathLimitReached Acts::Test::path_limit
Definition at line 44 of file ExtrapolatorTests.cpp.
View newest version in sPHENIX GitHub at line 44 of file ExtrapolatorTests.cpp
using Acts::Test::PathLimit = typedef PathLimitReached
Definition at line 31 of file AbortListTests.cpp.
View newest version in sPHENIX GitHub at line 31 of file AbortListTests.cpp
typedef Acts::Test::Propagator< EigenStepper< ConstantBField >> Propagator
Definition at line 35 of file AdaptiveMultiVertexFinderTests.cpp.
View newest version in sPHENIX GitHub at line 35 of file AdaptiveMultiVertexFinderTests.cpp
using Acts::Test::Ray = typedef Acts::Ray<double, 3>
Definition at line 12 of file TrackingVolumeTests.cpp.
View newest version in sPHENIX GitHub at line 12 of file TrackingVolumeTests.cpp
using Acts::Test::RecordedMaterial = typedef std::vector<std::pair<Acts::Material, Acts::Vector3D>>
Definition at line 23 of file MaterialGridHelperTests.cpp.
View newest version in sPHENIX GitHub at line 23 of file MaterialGridHelperTests.cpp
using Acts::Test::ReferencePropagator = typedef Propagator<Stepper, Navigator>
Definition at line 49 of file DirectNavigatorTests.cpp.
View newest version in sPHENIX GitHub at line 49 of file DirectNavigatorTests.cpp
typedef std::pair< ParID_t, double > Acts::Test::Resolution
Definition at line 54 of file KalmanFitterTests.cpp.
View newest version in sPHENIX GitHub at line 54 of file KalmanFitterTests.cpp
typedef ExtendedMinimalSourceLink Acts::Test::SourceLink
Definition at line 75 of file FittableTypeTests.cpp.
View newest version in sPHENIX GitHub at line 75 of file FittableTypeTests.cpp
using Acts::Test::SrfVec = typedef std::vector<std::shared_ptr<const Surface>>
Definition at line 46 of file LayerCreatorTests.cpp.
View newest version in sPHENIX GitHub at line 46 of file LayerCreatorTests.cpp
using Acts::Test::Stepper = typedef EigenStepper<BField>
Definition at line 48 of file DirectNavigatorTests.cpp.
View newest version in sPHENIX GitHub at line 48 of file DirectNavigatorTests.cpp
using Acts::Test::StraightLinePropagator = typedef Propagator<StraightLineStepper, Navigator>
Definition at line 58 of file MaterialCollectionTests.cpp.
View newest version in sPHENIX GitHub at line 58 of file MaterialCollectionTests.cpp
typedef TrackState< SourceLink, BoundParameters > Acts::Test::TrackState
Definition at line 32 of file GainMatrixSmootherTests.cpp.
View newest version in sPHENIX GitHub at line 32 of file GainMatrixSmootherTests.cpp
typedef std::map< GeometryID::Value, ElementResolution > Acts::Test::VolumeResolution
Definition at line 56 of file KalmanFitterTests.cpp.
View newest version in sPHENIX GitHub at line 56 of file KalmanFitterTests.cpp
Function Documentation
bool Acts::Test::approximatelyEqual (const Vector2D & a, const Vector2D & b)
Definition at line 33 of file RectangleBoundsTests.cpp.
View newest version in sPHENIX GitHub at line 33 of file RectangleBoundsTests.cpp
References kdfinder::abs(), and analysis::e.
template<typename T > void Acts::Test::assumeAccessed (T && clobber)
Definition at line 128 of file BenchmarkTools.hpp.
View newest version in sPHENIX GitHub at line 128 of file BenchmarkTools.hpp
Referenced by assumeRead(), assumeWritten(), and BOOST_AUTO_TEST_CASE().
template<typename T > void Acts::Test::assumeRead (const T & clobber) inline
Definition at line 151 of file BenchmarkTools.hpp.
View newest version in sPHENIX GitHub at line 151 of file BenchmarkTools.hpp
References assumeAccessed().
Referenced by BOOST_AUTO_TEST_CASE(), Acts::Test::benchmark_tools_internal::MicroBenchmarkIterImpl< Callable, Input, Result >::iter(), and Acts::Test::benchmark_tools_internal::MicroBenchmarkIterImpl< Callable, void, Result >::iter().
template<typename T > void Acts::Test::assumeWritten (T & clobber) inline
Definition at line 167 of file BenchmarkTools.hpp.
View newest version in sPHENIX GitHub at line 167 of file BenchmarkTools.hpp
References assumeAccessed().
Referenced by BOOST_AUTO_TEST_CASE(), Acts::Test::benchmark_tools_internal::MicroBenchmarkIterImpl< Callable, Input, Result >::iter(), Acts::Test::benchmark_tools_internal::MicroBenchmarkIterImpl< Callable, Input, void >::iter(), Acts::Test::benchmark_tools_internal::MicroBenchmarkIterImpl< Callable, void, Result >::iter(), and Acts::Test::benchmark_tools_internal::MicroBenchmarkIterImpl< Callable, void, void >::iter().
BFieldType Acts::Test::bField (0 , 0 , 2_T)
BField Acts::Test::bField (0 , 0 , Bz)
Acts::Test::BOOST_AUTO_TEST_CASE (GeometryID_construct_default)
Definition at line 16 of file GeometryIDTests.cpp.
View newest version in sPHENIX GitHub at line 16 of file GeometryIDTests.cpp
References Acts::UnitConstants::u, and volume.
Acts::Test::BOOST_AUTO_TEST_CASE (ProtoVolumeMaterial_construction_test)
Test the constructors.
Definition at line 18 of file ProtoVolumeMaterialTests.cpp.
View newest version in sPHENIX GitHub at line 18 of file ProtoVolumeMaterialTests.cpp
References Acts::binX, Acts::binY, Acts::binZ, and Acts::open.
Acts::Test::BOOST_AUTO_TEST_CASE (AuctioneerTest_VoidAuctioneer)
Definition at line 18 of file AuctioneerTests.cpp.
View newest version in sPHENIX GitHub at line 18 of file AuctioneerTests.cpp
Acts::Test::BOOST_AUTO_TEST_CASE (equidistant_axis)
Definition at line 19 of file AxesTests.cpp.
View newest version in sPHENIX GitHub at line 19 of file AxesTests.cpp
References a, and Acts::UnitConstants::u.
Acts::Test::BOOST_AUTO_TEST_CASE (vacuum)
Definition at line 20 of file AccumulatedVolumeMaterialTests.cpp.
View newest version in sPHENIX GitHub at line 20 of file AccumulatedVolumeMaterialTests.cpp
References Acts::AccumulatedVolumeMaterial::accumulate(), and Acts::AccumulatedVolumeMaterial::average().
Acts::Test::BOOST_AUTO_TEST_CASE (ProtoSurfaceMaterial_construction_test)
Test the constructors.
Definition at line 20 of file ProtoSurfaceMaterialTests.cpp.
View newest version in sPHENIX GitHub at line 20 of file ProtoSurfaceMaterialTests.cpp
References Acts::binX, Acts::binY, and Acts::open.
Acts::Test::BOOST_AUTO_TEST_CASE (annealing_tool_singleChi2_tests)
Definition at line 20 of file AnnealingUtilityTests.cpp.
View newest version in sPHENIX GitHub at line 20 of file AnnealingUtilityTests.cpp
References Acts::AnnealingUtility::anneal(), configureMap::config, Acts::AnnealingUtility::State::currentTemperatureIndex, Acts::AnnealingUtility::Config::cutOff, Acts::AnnealingUtility::State::equilibriumReached, Acts::AnnealingUtility::getWeight(), and Acts::UnitConstants::u.
Acts::Test::BOOST_AUTO_TEST_CASE (IntersectionTest)
test of the intersection class
let's make a bunch of negative solution
Definition at line 20 of file IntersectionTests.cpp.
View newest version in sPHENIX GitHub at line 20 of file IntersectionTests.cpp
Acts::Test::BOOST_AUTO_TEST_CASE (AccumulatedSurfaceMaterial_construction_test)
Test the constructors.
Definition at line 20 of file AccumulatedSurfaceMaterialTests.cpp.
View newest version in sPHENIX GitHub at line 20 of file AccumulatedSurfaceMaterialTests.cpp
References Acts::AccumulatedSurfaceMaterial::accumulatedMaterial(), Acts::binX, Acts::binY, Acts::open, and Acts::UnitConstants::u.
Acts::Test::BOOST_AUTO_TEST_CASE (InfiniteBoundsConstruction)
Unit test for creating compliant/non-compliant InfiniteBounds object.
Definition at line 21 of file InfiniteBoundsTests.cpp.
View newest version in sPHENIX GitHub at line 21 of file InfiniteBoundsTests.cpp
References Acts::SurfaceBounds::eBoundless, Acts::InfiniteBounds::type(), Acts::UnitConstants::u, and v.
Acts::Test::BOOST_AUTO_TEST_CASE (construct_element_fraction)
Definition at line 21 of file MaterialCompositionTests.cpp.
View newest version in sPHENIX GitHub at line 21 of file MaterialCompositionTests.cpp
References a, b, CHECK_CLOSE_REL, Acts::ElementFraction::element(), eps, Acts::ElementFraction::fraction(), and Acts::UnitConstants::u.
Acts::Test::BOOST_AUTO_TEST_CASE (BinUtility_equidistant_binning)
Definition at line 21 of file BinUtilityTests.cpp.
View newest version in sPHENIX GitHub at line 21 of file BinUtilityTests.cpp
References Acts::BinUtility::bins(), Acts::BinUtility::binTriple(), Acts::binX, Acts::binY, Acts::binZ, Acts::BinUtility::dimensions(), Acts::BinUtility::neighbourRange(), Acts::open, Acts::UnitConstants::u, and xyzPosition().
Acts::Test::BOOST_AUTO_TEST_CASE (CylindricalTrackingGeometryTest)
Definition at line 21 of file TrackingGeometryCreationTests.cpp.
View newest version in sPHENIX GitHub at line 21 of file TrackingGeometryCreationTests.cpp
References cGeometry, tgContext, and tGeometry.
Acts::Test::BOOST_AUTO_TEST_CASE (AccumulatedMaterialProperties_construction_test)
Test the constructors.
Check the move construction
Check the move assignment
All of the material should be invalid (the accessible ones)
All of the material should be invalid (the accessible ones)
All of the material should be invalid (the accessible ones)
Definition at line 21 of file AccumulatedMaterialPropertiesTests.cpp.
View newest version in sPHENIX GitHub at line 21 of file AccumulatedMaterialPropertiesTests.cpp
References a, b, c, Acts::AccumulatedMaterialProperties::totalAverage(), and Acts::UnitConstants::u.
Acts::Test::BOOST_AUTO_TEST_CASE (LineBoundsConstruction)
Unit test for creating compliant/non-compliant LineBounds object.
test LineBounds(double, double)
test copy construction;
Definition at line 22 of file LineBoundsTests.cpp.
View newest version in sPHENIX GitHub at line 22 of file LineBoundsTests.cpp
References Acts::SurfaceBounds::eLine, and Acts::LineBounds::type().
Acts::Test::BOOST_AUTO_TEST_CASE (free_initialization)
Unit test for free parameters.
Repeat constructing and assignment with neutral parameters
Test getters/setters
Definition at line 22 of file FreeParametersTests.cpp.
View newest version in sPHENIX GitHub at line 22 of file FreeParametersTests.cpp
References CHECK_CLOSE_ABS, CHECK_CLOSE_COVARIANCE, analysis::e, Acts::SingleFreeParameters< ChargePolicy >::parameters(), pos, and t.
Acts::Test::BOOST_AUTO_TEST_CASE (frustum_construction)
Definition at line 22 of file FrustumTest.cpp.
View newest version in sPHENIX GitHub at line 22 of file FrustumTest.cpp
References CHECK_CLOSE_ABS, analysis::e, M_PI, and Acts::UnitConstants::u.
Acts::Test::BOOST_AUTO_TEST_CASE (interpolation_1d)
Definition at line 22 of file InterpolationTests.cpp.
View newest version in sPHENIX GitHub at line 22 of file InterpolationTests.cpp
References CHECK_CLOSE_REL, analysis::e, Acts::interpolate(), and v.
Acts::Test::BOOST_AUTO_TEST_CASE (ray_construction)
Definition at line 22 of file RayTest.cpp.
View newest version in sPHENIX GitHub at line 22 of file RayTest.cpp
References CHECK_CLOSE_ABS, analysis::e, and matrix().
Acts::Test::BOOST_AUTO_TEST_CASE (BinnedSurfaceMaterial_construction_test)
Test the constructors.
Definition at line 23 of file BinnedSurfaceMaterialTests.cpp.
View newest version in sPHENIX GitHub at line 23 of file BinnedSurfaceMaterialTests.cpp
References Acts::binX, Acts::binY, eic::m, and Acts::open.
Acts::Test::BOOST_AUTO_TEST_CASE (HomogeneousSurfaceMaterial_construction_test)
Test the constructors.
Definition at line 23 of file HomogeneousSurfaceMaterialTests.cpp.
View newest version in sPHENIX GitHub at line 23 of file HomogeneousSurfaceMaterialTests.cpp
Acts::Test::BOOST_AUTO_TEST_CASE (HomogeneousVolumeMaterial_construction_test)
Test the constructors.
Definition at line 23 of file HomogeneousVolumeMaterialTests.cpp.
View newest version in sPHENIX GitHub at line 23 of file HomogeneousVolumeMaterialTests.cpp
Acts::Test::BOOST_AUTO_TEST_CASE (bitset_to_matrix_to_bitset)
Definition at line 23 of file HelpersTests.cpp.
View newest version in sPHENIX GitHub at line 23 of file HelpersTests.cpp
References Acts::matrixToBitset().
Acts::Test::BOOST_AUTO_TEST_CASE (ConstrainedStepTest)
Definition at line 24 of file ConstrainedStepTests.cpp.
View newest version in sPHENIX GitHub at line 24 of file ConstrainedStepTests.cpp
References Acts::ConstrainedStep::aborter, Acts::ConstrainedStep::accuracy, Acts::ConstrainedStep::actor, max, Acts::ConstrainedStep::release(), Acts::ConstrainedStep::update(), Acts::ConstrainedStep::user, and Acts::ConstrainedStep::values.
Acts::Test::BOOST_AUTO_TEST_CASE (Extendable_)
Definition at line 24 of file ExtendableTests.cpp.
View newest version in sPHENIX GitHub at line 24 of file ExtendableTests.cpp
References Acts::detail::Extendable< extensions_t >::append(), c, Acts::detail::Extendable< extensions_t >::get(), Acts::UnitConstants::u, value, and nlohmann::detail::void().
Acts::Test::BOOST_AUTO_TEST_CASE (grid_test_1d_equidistant)
Definition at line 24 of file GridTests.cpp.
View newest version in sPHENIX GitHub at line 24 of file GridTests.cpp
References a, g(), Acts::detail::Grid< T, Axes >::globalBinFromLocalBins(), Acts::detail::Grid< T, Axes >::globalBinFromPosition(), Acts::detail::Grid< T, Axes >::localBinsFromGlobalBin(), Acts::detail::Grid< T, Axes >::numLocalBins(), Acts::detail::Grid< T, Axes >::size(), and Acts::UnitConstants::u.
Acts::Test::BOOST_AUTO_TEST_CASE (BoundaryCheckBoxSimple)
Definition at line 24 of file BoundaryCheckTests.cpp.
View newest version in sPHENIX GitHub at line 24 of file BoundaryCheckTests.cpp
References Acts::BoundaryCheck::isInside().
Acts::Test::BOOST_AUTO_TEST_CASE (RadialBoundsConstruction)
Unit tests for RadialBounds constrcuctors.
Test construction with radii and default sector
Test construction with radii and sector half angle
Copy constructor
Definition at line 25 of file RadialBoundsTests.cpp.
View newest version in sPHENIX GitHub at line 25 of file RadialBoundsTests.cpp
References Acts::SurfaceBounds::eDisc, M_PI, maxRadius, and minRadius.
Acts::Test::BOOST_AUTO_TEST_CASE (covariance_engine_test)
These tests do not test for a correct covariance transport but only for the correct conservation or modification of certain variables. A test suite for the numerical correctness is performed in the integration tests.
Definition at line 25 of file CovarianceEngineTests.cpp.
View newest version in sPHENIX GitHub at line 25 of file CovarianceEngineTests.cpp
References Acts::detail::boundState(), Acts::detail::covarianceTransport(), Acts::detail::curvilinearState(), Dataset::parameters, Acts::VectorHelpers::position(), tgContext, and Acts::VectorHelpers::time().
Acts::Test::BOOST_AUTO_TEST_CASE (GeometryID_construct_encoded)
Definition at line 25 of file GeometryIDTests.cpp.
View newest version in sPHENIX GitHub at line 25 of file GeometryIDTests.cpp
References Acts::UnitConstants::u, and volume.
Acts::Test::BOOST_AUTO_TEST_CASE (CylinderBoundsConstruction)
Unit test for creating compliant/non-compliant CylinderBounds object.
test default construction
test copy construction;
Definition at line 25 of file CylinderBoundsTests.cpp.
View newest version in sPHENIX GitHub at line 25 of file CylinderBoundsTests.cpp
References Acts::SurfaceBounds::eCylinder, and M_PI.
Acts::Test::BOOST_AUTO_TEST_CASE (DiamondBoundsConstruction)
Unit test for creating compliant/non-compliant DiamondBounds object.
Test construction with dimensions
Copy constructor
Definition at line 25 of file DiamondBoundsTests.cpp.
View newest version in sPHENIX GitHub at line 25 of file DiamondBoundsTests.cpp
References db, Acts::SurfaceBounds::eDiamond, and Acts::DiamondBounds::type().
Acts::Test::BOOST_AUTO_TEST_CASE (DiscTrapezoidBoundsConstruction)
Unit tests for DiscTrapezoidBounds constrcuctors.
Test construction with dimensions and default stereo
Test construction with all dimensions
Copy constructor
Definition at line 25 of file DiscTrapezoidBoundsTests.cpp.
View newest version in sPHENIX GitHub at line 25 of file DiscTrapezoidBoundsTests.cpp
References Acts::SurfaceBounds::eDiscTrapezoid, and Acts::DiscTrapezoidBounds::type().
Acts::Test::BOOST_AUTO_TEST_CASE (CuboidVolumeConstruction)
Definition at line 25 of file CuboidVolumeBoundsTests.cpp.
View newest version in sPHENIX GitHub at line 25 of file CuboidVolumeBoundsTests.cpp
References hx, hy, and hz.
Acts::Test::BOOST_AUTO_TEST_CASE (EllipseBoundsConstruction)
Unit test for creating compliant/non-compliant EllipseBounds object.
Test construction with dimensions
Copy constructor
Definition at line 25 of file EllipseBoundsTests.cpp.
View newest version in sPHENIX GitHub at line 25 of file EllipseBoundsTests.cpp
References Acts::SurfaceBounds::eEllipse, and M_PI.
Acts::Test::BOOST_AUTO_TEST_CASE (curvilinear_initialization)
Unit test for Curvilinear parameters.
create curvilinear parameters without covariance +1/-1 charge
check local coordinates
copy construction test
modification test with set methods
Definition at line 26 of file CurvilinearParametersTests.cpp.
View newest version in sPHENIX GitHub at line 26 of file CurvilinearParametersTests.cpp
References Acts::units::_e, Acts::units::_GeV, Acts::units::_mm, Acts::units::_s, Acts::Surface::center(), CHECK_CLOSE_OR_SMALL, CHECK_CLOSE_REL, consistencyCheck(), cos(), analysis::e, Acts::eLOC_0, Acts::eLOC_1, Acts::ePHI, Acts::eQOP, Acts::eT, Acts::eTHETA, charm_jet_coverage::mom, Acts::Surface::normal(), phi, pos, Acts::SingleCurvilinearTrackParameters< ChargePolicy >::referenceFrame(), Acts::SingleCurvilinearTrackParameters< ChargePolicy >::referenceSurface(), tgContext, ds::theta, Acts::Surface::transform(), Acts::UnitConstants::u, ux, and uy.
Acts::Test::BOOST_AUTO_TEST_CASE (Json_conversion)
Definition at line 26 of file JsonConversionTest.cpp.
View newest version in sPHENIX GitHub at line 26 of file JsonConversionTest.cpp
References Acts::JsonGeometryConverter::jsonToMaterialMaps(), and Acts::JsonGeometryConverter::materialMapsToJson().
Acts::Test::BOOST_AUTO_TEST_CASE (getSurface_test)
Definition at line 27 of file MeasurementHelpersTests.cpp.
View newest version in sPHENIX GitHub at line 27 of file MeasurementHelpersTests.cpp
References Acts::UnitConstants::fm, Acts::MeasurementHelpers::getSurface(), eic::m, and Acts::UnitConstants::m2.
Acts::Test::BOOST_AUTO_TEST_CASE (TrapezoidBoundsConstruction)
Unit test for creating compliant/non-compliant TrapezoidBounds object.
Test construction with defining half lengths
Copy constructor
Definition at line 27 of file TrapezoidBoundsTests.cpp.
View newest version in sPHENIX GitHub at line 27 of file TrapezoidBoundsTests.cpp
References Acts::SurfaceBounds::eTrapezoid, and halfY.
Acts::Test::BOOST_AUTO_TEST_CASE (bfield_creation)
Definition at line 27 of file BFieldMapUtilsTests.cpp.
View newest version in sPHENIX GitHub at line 27 of file BFieldMapUtilsTests.cpp
References CHECK_CLOSE_ABS, analysis::e, Acts::fieldMapperRZ(), Acts::fieldMapperXYZ(), and Acts::VectorHelpers::perp().
Acts::Test::BOOST_AUTO_TEST_CASE (CubicTrackingGeometryTest)
Definition at line 27 of file TrackingGeometryCreationTests.cpp.
View newest version in sPHENIX GitHub at line 27 of file TrackingGeometryCreationTests.cpp
References cGeometry, tgContext, and tGeometry.
Acts::Test::BOOST_AUTO_TEST_CASE (EventDataVisualizationObj)
Definition at line 27 of file EventDataVisualizationTests.cpp.
View newest version in sPHENIX GitHub at line 27 of file EventDataVisualizationTests.cpp
References Acts::EventDataVisualization::test(), and testObjString().
Acts::Test::BOOST_AUTO_TEST_CASE (SurfaceVisualizationObj)
This tests if the corresponding obj output is well formatted.
Definition at line 27 of file SurfaceVisualizationTests.cpp.
View newest version in sPHENIX GitHub at line 27 of file SurfaceVisualizationTests.cpp
References Acts::SurfaceVisualization::test(), and testObjString().
Acts::Test::BOOST_AUTO_TEST_CASE (VisualizationTesterObj)
Definition at line 27 of file VisualizationTests.cpp.
View newest version in sPHENIX GitHub at line 27 of file VisualizationTests.cpp
References testObjString().
Acts::Test::BOOST_AUTO_TEST_CASE (VolumeVisualizationObj)
Definition at line 27 of file VolumeVisualizationTests.cpp.
View newest version in sPHENIX GitHub at line 27 of file VolumeVisualizationTests.cpp
References Acts::VolumeVisualization::test(), and testObjString().
Acts::Test::BOOST_AUTO_TEST_CASE (assume_accessed)
Definition at line 28 of file BenchmarkTools.cpp.
View newest version in sPHENIX GitHub at line 28 of file BenchmarkTools.cpp
References assumeAccessed(), and x.
Acts::Test::BOOST_AUTO_TEST_CASE (measurement_initialization)
Unit test for creation of Measurement object.
Definition at line 28 of file MeasurementTests.cpp.
View newest version in sPHENIX GitHub at line 28 of file MeasurementTests.cpp
References generator(), eic::m, Acts::Measurement< source_link_t, params >::parameters(), and Acts::PrimitivesVisualization::plane.
Acts::Test::BOOST_AUTO_TEST_CASE (ConvexPolygonBoundsConvexity)
Definition at line 28 of file ConvexPolygonBoundsTests.cpp.
View newest version in sPHENIX GitHub at line 28 of file ConvexPolygonBoundsTests.cpp
Acts::Test::BOOST_AUTO_TEST_CASE (CutoutCylinderVolumeBoundsConstruction)
Definition at line 29 of file CutoutCylinderVolumeBoundsTests.cpp.
View newest version in sPHENIX GitHub at line 29 of file CutoutCylinderVolumeBoundsTests.cpp
References Acts::CutoutCylinderVolumeBounds::toStream().
Acts::Test::BOOST_AUTO_TEST_CASE (RealQuadraticEquationConstruction)
Unit test for creating RealQuadraticEquation object.
Test construction with parameters
Copy constructor (implicit), void removes 'unused' compiler warning
Definition at line 29 of file RealQuadraticEquationTests.cpp.
View newest version in sPHENIX GitHub at line 29 of file RealQuadraticEquationTests.cpp
References a, b, c, and nlohmann::detail::void().
Acts::Test::BOOST_AUTO_TEST_CASE (VisualizationHelpers)
The tests in this section are regression tests only in order to catch any unexpected changes in the output format.
Definition at line 29 of file PrimitivesVisualizationTests.cpp.
View newest version in sPHENIX GitHub at line 29 of file PrimitivesVisualizationTests.cpp
References CHECK_CLOSE_ABS, Acts::Visualization::decomposeCovariance(), and M_PI.
Acts::Test::BOOST_AUTO_TEST_CASE (TestSolenoidBField)
Definition at line 29 of file SolenoidBFieldTests.cpp.
View newest version in sPHENIX GitHub at line 29 of file SolenoidBFieldTests.cpp
References _T, Acts::IntegrationTest::bField, Acts::SolenoidBField::Config::bMagCenter, CHECK_CLOSE_ABS, Acts::SolenoidBField::getField(), Acts::SolenoidBField::Config::length, mfContext, Acts::SolenoidBField::Config::nCoils, and Acts::SolenoidBField::Config::radius.
Acts::Test::BOOST_AUTO_TEST_CASE (InfiniteBoundsProperties)
Unit tests for InfiniteBounds properties.
test for type()
test for inside()
test for distanceToBoundary
test for dump
Definition at line 30 of file InfiniteBoundsTests.cpp.
View newest version in sPHENIX GitHub at line 30 of file InfiniteBoundsTests.cpp
References Acts::InfiniteBounds::distanceToBoundary(), Acts::SurfaceBounds::eBoundless, Acts::InfiniteBounds::inside(), Acts::InfiniteBounds::toStream(), and Acts::InfiniteBounds::type().
Acts::Test::BOOST_AUTO_TEST_CASE (AuctioneerTest_FirstValidAuctioneer)
Definition at line 30 of file AuctioneerTests.cpp.
View newest version in sPHENIX GitHub at line 30 of file AuctioneerTests.cpp
Acts::Test::BOOST_AUTO_TEST_CASE (single_material)
Definition at line 31 of file AccumulatedVolumeMaterialTests.cpp.
View newest version in sPHENIX GitHub at line 31 of file AccumulatedVolumeMaterialTests.cpp
References Acts::AccumulatedVolumeMaterial::accumulate(), Acts::Material::Ar(), Acts::AccumulatedVolumeMaterial::average(), CHECK_CLOSE_REL, analysis::e, Acts::Material::L0(), Acts::Material::massDensity(), Acts::Material::X0(), and Acts::Material::Z().
Acts::Test::BOOST_AUTO_TEST_CASE (CylinderVolumeBoundsConstruction)
Definition at line 31 of file CylinderVolumeBoundsTests.cpp.
View newest version in sPHENIX GitHub at line 31 of file CylinderVolumeBoundsTests.cpp
References Acts::CylinderVolumeBounds::decomposeToSurfaces(), M_PI, and rmax().
Acts::Test::BOOST_AUTO_TEST_CASE (construction_test)
Definition at line 31 of file GenericCuboidVolumeBoundsTests.cpp.
View newest version in sPHENIX GitHub at line 31 of file GenericCuboidVolumeBoundsTests.cpp
References Acts::GenericCuboidVolumeBounds::inside().
Acts::Test::BOOST_AUTO_TEST_CASE (ExtentTest)
Unit tests for Polyderon construction & operator +=.
Definition at line 31 of file ExtentTests.cpp.
View newest version in sPHENIX GitHub at line 31 of file ExtentTests.cpp
References Acts::units::_mm, Acts::binPhi, Acts::binR, Acts::binX, Acts::binY, Acts::binZ, Acts::Extent::check(), CHECK_CLOSE_ABS, analysis::e, Acts::Extent::extend(), Acts::Extent::max(), Acts::Extent::min(), phiMin, and v.
Acts::Test::BOOST_AUTO_TEST_CASE (InterpolatedBFieldMap_rz)
Definition at line 31 of file InterpolatedBFieldMapTests.cpp.
View newest version in sPHENIX GitHub at line 31 of file InterpolatedBFieldMapTests.cpp
References b, c, CHECK_CLOSE_REL, configureMap::config, analysis::e, g(), mfContext, Acts::VectorHelpers::perp(), pos, r, Acts::UnitConstants::u, value, and z.
Acts::Test::BOOST_AUTO_TEST_CASE (SimpleGeometryTest)
Unit test for a three layer detector parameters Testing the Tool chain in the geometry building process.
Definition at line 32 of file SimpleGeometryTests.cpp.
View newest version in sPHENIX GitHub at line 32 of file SimpleGeometryTests.cpp
References Acts::units::_mm, Acts::getDefaultLogger(), Acts::Logging::INFO, Acts::CylinderVolumeHelper::Config::layerArrayCreator, Acts::PassiveLayerBuilder::Config::layerIdentification, Acts::LayerCreator::Config::surfaceArrayCreator, Acts::tgContext, Acts::tGeometry, Acts::TrackingGeometryBuilder::trackingGeometry(), Acts::TrackingGeometryBuilder::Config::trackingVolumeBuilders, and Acts::CylinderVolumeBuilder::Config::trackingVolumeHelper.
Acts::Test::BOOST_AUTO_TEST_CASE (PolyhedronTest)
Unit tests for Polyderon construction & operator +=.
Definition at line 32 of file PolyhedronTests.cpp.
View newest version in sPHENIX GitHub at line 32 of file PolyhedronTests.cpp
References Acts::Polyhedron::draw(), Acts::Polyhedron::faces, Acts::Polyhedron::merge(), Acts::PrimitivesVisualization::rectangle, Acts::Polyhedron::triangularMesh, Acts::Polyhedron::vertices, and Acts::ObjVisualization< T >::write().
Acts::Test::BOOST_AUTO_TEST_CASE (LineBoundsRecreation)
Unit test for testing LineBounds recreation from streaming.
Definition at line 33 of file LineBoundsTests.cpp.
View newest version in sPHENIX GitHub at line 33 of file LineBoundsTests.cpp
References Acts::LineBounds::eSize, Acts::LineBounds::values(), and values.
Acts::Test::BOOST_AUTO_TEST_CASE (ConeSurfaceConstruction)
Unit test for creating compliant/non-compliant ConeSurface object.
Constructor with transform pointer, null or valid, alpha and symmetry indicator
Constructor with transform pointer, alpha,z min and max, halfPhiSector
Constructor with transform and ConeBounds pointer
Copy constructor
Copied and transformed
Construct with nullptr bounds
Definition at line 33 of file ConeSurfaceTests.cpp.
View newest version in sPHENIX GitHub at line 33 of file ConeSurfaceTests.cpp
References starlightConstants::alpha, Acts::Surface::Cone, M_PI, and tgContext.
Acts::Test::BOOST_AUTO_TEST_CASE (PlaneSurfaceConstruction)
Unit test for creating compliant/non-compliant PlaneSurface object.
Constructor with transform pointer, null or valid, alpha and symmetry indicator
Copy constructor
Copied and transformed
Construct with nullptr bounds
Definition at line 34 of file PlaneSurfaceTests.cpp.
View newest version in sPHENIX GitHub at line 34 of file PlaneSurfaceTests.cpp
References Acts::Surface::Plane, and tgContext.
Acts::Test::BOOST_AUTO_TEST_CASE (InterpolatedMaterialMap_MaterialCell_test)
Definition at line 34 of file InterpolatedMaterialMapTests.cpp.
View newest version in sPHENIX GitHub at line 34 of file InterpolatedMaterialMapTests.cpp
References CHECK_CLOSE_REL, Acts::MaterialMapper< G >::MaterialCell::getMaterial(), Acts::MaterialMapper< G >::MaterialCell::isInside(), and trafoGlobalToLocal().
Acts::Test::BOOST_AUTO_TEST_CASE (StrawSurfaceConstruction)
Unit test for creating compliant/non-compliant StrawSurface object.
Constructor with transform pointer, null or valid, radius and halfZ
Constructor with transform and LineBounds pointer
Constructor with LineBounds ptr, DetectorElement
Copy constructor
Copied and transformed
Definition at line 34 of file StrawSurfaceTests.cpp.
View newest version in sPHENIX GitHub at line 34 of file StrawSurfaceTests.cpp
References p, Acts::Surface::Straw, and tgContext.
Acts::Test::BOOST_AUTO_TEST_CASE (box_construction)
Definition at line 34 of file BoundingBoxTest.cpp.
View newest version in sPHENIX GitHub at line 34 of file BoundingBoxTest.cpp
References CHECK_CLOSE_ABS, analysis::e, M_PI, Acts::AxisAlignedBoundingBox< entity_t, value_t, DIM >::max(), Acts::AxisAlignedBoundingBox< entity_t, value_t, DIM >::min(), and Acts::AxisAlignedBoundingBox< entity_t, value_t, DIM >::transformed().
Acts::Test::BOOST_AUTO_TEST_CASE (assume_read)
Definition at line 34 of file BenchmarkTools.cpp.
View newest version in sPHENIX GitHub at line 34 of file BenchmarkTools.cpp
References assumeRead(), analysis::f, x, and analysis::y.
Acts::Test::BOOST_AUTO_TEST_CASE (BoundaryCheckBoxToleranceLoc0)
Definition at line 34 of file BoundaryCheckTests.cpp.
View newest version in sPHENIX GitHub at line 34 of file BoundaryCheckTests.cpp
References Acts::BoundaryCheck::isInside().
Acts::Test::BOOST_AUTO_TEST_CASE (CylinderSurfaceConstruction)
Unit test for creating compliant/non-compliant CylinderSurface object.
Constructor with transform pointer, null or valid, radius and halfZ
Constructor with transform pointer, radius, halfZ and halfPhiSector
Constructor with transform and CylinderBounds pointer
Copy constructor
Copied and transformed
Construct with nullptr bounds
Definition at line 34 of file CylinderSurfaceTests.cpp.
View newest version in sPHENIX GitHub at line 34 of file CylinderSurfaceTests.cpp
References Acts::Surface::Cylinder, M_PI, and testContext.
Acts::Test::BOOST_AUTO_TEST_CASE (LineSurface_Constructors_test)
Unit test for creating compliant/non-compliant LineSurface object.
Construct with nullptr bounds
Definition at line 35 of file LineSurfaceTests.cpp.
View newest version in sPHENIX GitHub at line 35 of file LineSurfaceTests.cpp
References tgContext, and transform.
Acts::Test::BOOST_AUTO_TEST_CASE (PerigeeSurfaceConstruction)
Unit test for creating compliant/non-compliant PerigeeSurface object.
Constructor with Vector3D
Constructor with transform pointer, null or valid
Copy constructor
Copied and transformed
Definition at line 35 of file PerigeeSurfaceTests.cpp.
View newest version in sPHENIX GitHub at line 35 of file PerigeeSurfaceTests.cpp
References Acts::Surface::Perigee, and tgContext.
Acts::Test::BOOST_AUTO_TEST_CASE (Square_Grid_test)
Various test for the Material in the case of a Cuboid volume and 2D Grid.
Definition at line 35 of file MaterialGridHelperTests.cpp.
View newest version in sPHENIX GitHub at line 35 of file MaterialGridHelperTests.cpp
References Acts::detail::Grid< T, Axes >::atLocalBins(), Acts::BinUtility::binningData(), Acts::binX, Acts::binY, CHECK_CLOSE_REL, Acts::Material::classificationNumbers(), Acts::createGrid2D(), Acts::detail::Grid< T, Axes >::dimensions(), analysis::e, Acts::index1, Acts::index2, Acts::index3, Acts::detail::Grid< T, Axes >::localBinsFromLowerLeftEdge(), Acts::mapMaterialPoints(), max, Acts::detail::Grid< T, Axes >::maxPosition(), min, Acts::detail::Grid< T, Axes >::minPosition(), Acts::detail::Grid< T, Axes >::numLocalBins(), Acts::open, and pos.
Acts::Test::BOOST_AUTO_TEST_CASE (ConeBoundsConstruction)
Unit test for creating compliant/non-compliant ConeBounds object.
Definition at line 35 of file ConeBoundsTests.cpp.
View newest version in sPHENIX GitHub at line 35 of file ConeBoundsTests.cpp
References starlightConstants::alpha, Acts::SurfaceBounds::eCone, M_PI, and Acts::ConeBounds::type().
Acts::Test::BOOST_AUTO_TEST_CASE (DiscSurface_constructors_test)
Unit tests for creating DiscSurface object.
Test DiscSurface fully specified constructor but no transform
Test DiscSurface constructor with default halfPhiSector
Test DiscSurface constructor with a transform specified
Copy constructed DiscSurface
Copied and transformed DiscSurface
Construct with nullptr bounds
Definition at line 35 of file DiscSurfaceTests.cpp.
View newest version in sPHENIX GitHub at line 35 of file DiscSurfaceTests.cpp
References M_PI, and tgContext.
Acts::Test::BOOST_AUTO_TEST_CASE (GeometryID_max_values)
Definition at line 36 of file GeometryIDTests.cpp.
View newest version in sPHENIX GitHub at line 36 of file GeometryIDTests.cpp
References Acts::UnitConstants::u.
Acts::Test::BOOST_AUTO_TEST_CASE (AnnulusBoundsConstruction)
Definition at line 36 of file AnnulusBoundsTests.cpp.
View newest version in sPHENIX GitHub at line 36 of file AnnulusBoundsTests.cpp
Acts::Test::BOOST_AUTO_TEST_CASE (index_combination_generation_test)
Definition at line 36 of file FittableTypeTests.cpp.
View newest version in sPHENIX GitHub at line 36 of file FittableTypeTests.cpp
References _T.
Acts::Test::BOOST_AUTO_TEST_CASE (construct_with_fractions)
Definition at line 37 of file MaterialCompositionTests.cpp.
View newest version in sPHENIX GitHub at line 37 of file MaterialCompositionTests.cpp
References CHECK_CLOSE_REL, eps, analysis::f, and Acts::UnitConstants::u.
Acts::Test::BOOST_AUTO_TEST_CASE (materialmap_creation)
Definition at line 37 of file MaterialMapUtilsTests.cpp.
View newest version in sPHENIX GitHub at line 37 of file MaterialMapUtilsTests.cpp
References CHECK_CLOSE_ABS, Acts::Material::classificationNumbers(), analysis::e, Acts::materialMapperRZ(), and Acts::materialMapperXYZ().
Acts::Test::BOOST_AUTO_TEST_CASE (all_of_test)
Definition at line 37 of file MPLTests.cpp.
View newest version in sPHENIX GitHub at line 37 of file MPLTests.cpp
References Acts::detail::all_of_v.
Acts::Test::BOOST_AUTO_TEST_CASE (track_state_initialization)
Unit test for creation of Measurement object.
Definition at line 37 of file TrackStateTests.cpp.
View newest version in sPHENIX GitHub at line 37 of file TrackStateTests.cpp
References cov1D, cov2D, generator(), Acts::PrimitivesVisualization::plane, boost::swap(), tgContext, and Acts::UnitConstants::u.
Acts::Test::BOOST_AUTO_TEST_CASE (straight_line_stepper_state_test)
These tests are aiming to test whether the state setup is working properly.
Definition at line 37 of file StraightLineStepperTests.cpp.
View newest version in sPHENIX GitHub at line 37 of file StraightLineStepperTests.cpp
References Acts::backward, charge, Acts::StraightLineStepper::State::cov, Acts::StraightLineStepper::State::covTransport, Acts::StraightLineStepper::State::derivative, Acts::StraightLineStepper::State::dir, Acts::StraightLineStepper::State::jacToGlobal, Acts::StraightLineStepper::State::jacTransport, mfContext, charm_jet_coverage::mom, Acts::StraightLineStepper::State::navDir, Acts::StraightLineStepper::State::p, Acts::StraightLineStepper::State::pathAccumulated, Acts::StraightLineStepper::State::pos, pos, Acts::StraightLineStepper::State::previousStepSize, Acts::StraightLineStepper::State::q, Acts::StraightLineStepper::State::stepSize, Acts::StraightLineStepper::State::t, tgContext, Acts::VectorHelpers::time(), and Acts::StraightLineStepper::State::tolerance.
Acts::Test::BOOST_AUTO_TEST_CASE (EventDataVisualizationPly)
Definition at line 37 of file EventDataVisualizationTests.cpp.
View newest version in sPHENIX GitHub at line 37 of file EventDataVisualizationTests.cpp
References Acts::EventDataVisualization::test(), and testPlyString().
Acts::Test::BOOST_AUTO_TEST_CASE (gain_matrix_smoother)
Definition at line 37 of file GainMatrixSmootherTests.cpp.
View newest version in sPHENIX GitHub at line 37 of file GainMatrixSmootherTests.cpp
References Acts::MultiTrajectory< source_link_t >::addTrackState(), Acts::TrackStatePropMask::All, CHECK_CLOSE_ABS, analysis::e, M_PI, and tgContext.
Acts::Test::BOOST_AUTO_TEST_CASE (atlas_stepper_state_test)
These tests are aiming to test whether the state setup is working properly.
Definition at line 38 of file AtlasStepperTests.cpp.
View newest version in sPHENIX GitHub at line 38 of file AtlasStepperTests.cpp
References Acts::backward, bField, charge, CHECK_CLOSE_ABS, analysis::e, mfContext, charm_jet_coverage::mom, pos, tgContext, and Acts::VectorHelpers::time().
Acts::Test::BOOST_AUTO_TEST_CASE (gain_matrix_updater)
Definition at line 38 of file GainMatrixUpdaterTests.cpp.
View newest version in sPHENIX GitHub at line 38 of file GainMatrixUpdaterTests.cpp
References Acts::MultiTrajectory< source_link_t >::addTrackState(), Acts::TrackStatePropMask::All, CHECK_CLOSE_ABS, analysis::e, Acts::MultiTrajectory< source_link_t >::getTrackState(), eic::m, M_PI, and tgContext.
Acts::Test::BOOST_AUTO_TEST_CASE (CuboidVolumeRecreation)
Definition at line 38 of file CuboidVolumeBoundsTests.cpp.
View newest version in sPHENIX GitHub at line 38 of file CuboidVolumeBoundsTests.cpp
References Acts::CuboidVolumeBounds::eSize, hx, hy, hz, values, and Acts::CuboidVolumeBounds::values().
Acts::Test::BOOST_AUTO_TEST_CASE (interpolation_2d)
Definition at line 39 of file InterpolationTests.cpp.
View newest version in sPHENIX GitHub at line 39 of file InterpolationTests.cpp
References CHECK_CLOSE_REL, analysis::e, Acts::interpolate(), and v.
Acts::Test::BOOST_AUTO_TEST_CASE (TestConstruction)
Definition at line 39 of file ResultTests.cpp.
View newest version in sPHENIX GitHub at line 39 of file ResultTests.cpp
References analysis::res.
Acts::Test::BOOST_AUTO_TEST_CASE (TypeTraitsMethods)
Definition at line 40 of file TypeTraitsTest.cpp.
View newest version in sPHENIX GitHub at line 40 of file TypeTraitsTest.cpp
Acts::Test::BOOST_AUTO_TEST_CASE (track_density_finder_test)
Unit test for TrackDensityVertexFinder using same configuration and values as VertexSeedFinderTestAlg in Athena implementation, i.e. tests if reordering tracks returns the same result.
Definition at line 40 of file TrackDensityVertexFinderTests.cpp.
View newest version in sPHENIX GitHub at line 40 of file TrackDensityVertexFinderTests.cpp
References Acts::units::_MeV, Acts::units::_mm, Acts::TrackDensityVertexFinder< vfitter_t, track_density_t >::find(), geoContext, and magFieldContext.
Acts::Test::BOOST_AUTO_TEST_CASE (CylinderIntersectionTests)
This tests the interseciton with cylinders and looks for valid, non-valid, solutions
Definition at line 41 of file SurfaceIntersectionTests.cpp.
View newest version in sPHENIX GitHub at line 41 of file SurfaceIntersectionTests.cpp
References Acts::units::_cm, Acts::units::_m, aCylinder, Acts::aTransform, CHECK_CLOSE_ABS, Acts::s_onSurfaceTolerance, Acts::tgContext, and transform.
Acts::Test::BOOST_AUTO_TEST_CASE (billoir_vertex_fitter_empty_input_test)
Unit test for FullBilloirVertexFitter.
Definition at line 41 of file FullBilloirVertexFitterTests.cpp.
View newest version in sPHENIX GitHub at line 41 of file FullBilloirVertexFitterTests.cpp
References _T, Acts::IntegrationTest::bField, Acts::FullBilloirVertexFitter< input_track_t, linearizer_t >::fit(), Acts::Vertex< input_track_t >::fullCovariance(), geoContext, magFieldContext, origin(), Acts::Vertex< input_track_t >::position(), Acts::Vertex< input_track_t >::setFullCovariance(), Acts::Vertex< input_track_t >::setFullPosition(), and propagation_timing::stepper.
Acts::Test::BOOST_AUTO_TEST_CASE (cartesian_segmentation)
Unit test for the Cartesian segmentation.
Definition at line 41 of file CartesianSegmentationTests.cpp.
View newest version in sPHENIX GitHub at line 41 of file CartesianSegmentationTests.cpp
References kdfinder::abs(), CHECK_CLOSE_OR_SMALL, CHECK_CLOSE_REL, Acts::CartesianSegmentation::createSegmentationSurfaces(), cSegmentation, analysis::e, hThickness, lAngle, nbinsx, nbinsy, Acts::tgContext, Acts::UnitConstants::u, and z.
Acts::Test::BOOST_AUTO_TEST_CASE (CutoutCylinderVolumeBoundsRecreation)
Definition at line 42 of file CutoutCylinderVolumeBoundsTests.cpp.
View newest version in sPHENIX GitHub at line 42 of file CutoutCylinderVolumeBoundsTests.cpp
References Acts::CutoutCylinderVolumeBounds::eSize, values, and Acts::CutoutCylinderVolumeBounds::values().
Acts::Test::BOOST_AUTO_TEST_CASE (RectangleBoundsConstruction)
Unit test for creating compliant/non-compliant RectangleBounds object.
Definition at line 42 of file RectangleBoundsTests.cpp.
View newest version in sPHENIX GitHub at line 42 of file RectangleBoundsTests.cpp
References Acts::SurfaceBounds::eRectangle, halfX, halfY, inf, and Acts::RectangleBounds::type().
Acts::Test::BOOST_AUTO_TEST_CASE (AuctioneerTest_HighestValidAuctioneer)
Definition at line 42 of file AuctioneerTests.cpp.
View newest version in sPHENIX GitHub at line 42 of file AuctioneerTests.cpp
Acts::Test::BOOST_AUTO_TEST_CASE (phi_helper_test)
Definition at line 42 of file HelpersTests.cpp.
View newest version in sPHENIX GitHub at line 42 of file HelpersTests.cpp
References CHECK_CLOSE_ABS, analysis::e, M_PI, Acts::VectorHelpers::phi(), analysis::s, Acts::UnitConstants::u, v, and v2.
Acts::Test::BOOST_AUTO_TEST_CASE (RealQuadraticEquationProperties)
Unit test for RealQuadraticEquation properties.
Test construction with parameters
Test for solutions
Definition at line 42 of file RealQuadraticEquationTests.cpp.
View newest version in sPHENIX GitHub at line 42 of file RealQuadraticEquationTests.cpp
References a, b, c, CHECK_CLOSE_REL, analysis::e, Acts::detail::RealQuadraticEquation::first, Acts::detail::RealQuadraticEquation::second, and Acts::detail::RealQuadraticEquation::solutions.
Acts::Test::BOOST_AUTO_TEST_CASE (adaptive_multi_vertex_finder_test)
Definition at line 42 of file AdaptiveMultiVertexFinderTests.cpp.
View newest version in sPHENIX GitHub at line 42 of file AdaptiveMultiVertexFinderTests.cpp
References Acts::units::_mm, _T, bField, CHECK_CLOSE_ABS, debugMode, geoContext, getAthenaTracks(), magFieldContext, Acts::Vertex< input_track_t >::setCovariance(), Acts::Vertex< input_track_t >::setPosition(), propagation_timing::stepper, Acts::VertexingOptions< input_track_t >::vertexConstraint, and vtx().
Acts::Test::BOOST_AUTO_TEST_CASE (CylinderBoundsRecreation)
test default construction
Definition at line 42 of file CylinderBoundsTests.cpp.
View newest version in sPHENIX GitHub at line 42 of file CylinderBoundsTests.cpp
References Acts::CylinderBounds::eSize, and values.
Acts::Test::BOOST_AUTO_TEST_CASE (TrapezoidBoundsRecreated)
Unit test for creating compliant/non-compliant TrapezoidBounds object.
Copy constructor
Definition at line 43 of file TrapezoidBoundsTests.cpp.
View newest version in sPHENIX GitHub at line 43 of file TrapezoidBoundsTests.cpp
References Acts::TrapezoidBounds::eSize, halfY, values, and Acts::TrapezoidBounds::values().
Acts::Test::BOOST_AUTO_TEST_CASE (AnnulusBoundsRecreation)
Definition at line 44 of file AnnulusBoundsTests.cpp.
View newest version in sPHENIX GitHub at line 44 of file AnnulusBoundsTests.cpp
References Acts::AnnulusBounds::eSize, maxPhi, maxRadius, minPhi, minRadius, offset(), and values.
Acts::Test::BOOST_AUTO_TEST_CASE (create_Clusters1)
This test tests the clusterization of cells which belong to the same cluster for 8-cell/4-cell merging, digital/analogue readout and with a possible energy cut applied The grid with cells should cover all different cases:
1 0 0 0 2 0 0 0 0 2 0 2 0 1 0 0 0 2 0 2 0 0 0 0 0 0 0 1 1 2 2 0 0 0 0 1 0 0 0 0 1 0 0 1 0 2 0 0 0 2 0 0 2 0 0 1 0 1 0 1 0 0 0 1 1 0 0 2 0 1 0 0 0 0 0 0 0 0 2 0 1 2 2 0 0 0 0 0 0 0
Definition at line 44 of file ClusterizationTests.cpp.
View newest version in sPHENIX GitHub at line 44 of file ClusterizationTests.cpp
References a, b, CHECK_CLOSE_REL, and analysis::e.
Acts::Test::BOOST_AUTO_TEST_CASE (LineBoundsExceptions)
Unit test for testing LineBounds exceptions.
Definition at line 45 of file LineBoundsTests.cpp.
View newest version in sPHENIX GitHub at line 45 of file LineBoundsTests.cpp
Acts::Test::BOOST_AUTO_TEST_CASE (RadialBoundsRecreation)
Definition at line 45 of file RadialBoundsTests.cpp.
View newest version in sPHENIX GitHub at line 45 of file RadialBoundsTests.cpp
References Acts::RadialBounds::eSize, M_PI, maxRadius, minRadius, values, and Acts::RadialBounds::values().
Acts::Test::BOOST_AUTO_TEST_CASE (BoundaryCheckBoxDistance)
Definition at line 45 of file BoundaryCheckTests.cpp.
View newest version in sPHENIX GitHub at line 45 of file BoundaryCheckTests.cpp
References CHECK_CLOSE_REL, Acts::BoundaryCheck::distance(), analysis::e, rectDimensions, rectDistances, rectShiftedDimensions, rectShiftedDistances, rectShiftedTestPoints, and rectTestPoints.
Acts::Test::BOOST_AUTO_TEST_CASE (assume_written)
Definition at line 46 of file BenchmarkTools.cpp.
View newest version in sPHENIX GitHub at line 46 of file BenchmarkTools.cpp
References assumeWritten(), and c.
Acts::Test::BOOST_AUTO_TEST_CASE (FATAL_test)
unit test for FATAL debug level
This test checks for the expected output when using the Acts::Logging::FATAL debug level as threshold. It also tests
ACTS_LOCAL_LOGGER
Acts::getDefaultLogger
Definition at line 46 of file LoggerTests.cpp.
View newest version in sPHENIX GitHub at line 46 of file LoggerTests.cpp
References ACTS_DEBUG, ACTS_ERROR, ACTS_FATAL, ACTS_INFO, ACTS_LOCAL_LOGGER, ACTS_VERBOSE, ACTS_WARNING, FATAL, and getline.
Acts::Test::BOOST_AUTO_TEST_CASE (EllipseBoundsRecreation)
Definition at line 46 of file EllipseBoundsTests.cpp.
View newest version in sPHENIX GitHub at line 46 of file EllipseBoundsTests.cpp
References Acts::EllipseBounds::eSize, M_PI, values, and Acts::EllipseBounds::values().
Acts::Test::BOOST_AUTO_TEST_CASE (CuboidVolumeException)
Definition at line 47 of file CuboidVolumeBoundsTests.cpp.
View newest version in sPHENIX GitHub at line 47 of file CuboidVolumeBoundsTests.cpp
References hx, hy, and hz.
Acts::Test::BOOST_AUTO_TEST_CASE (HomogeneousSurfaceMaterial_scaling_test)
Definition at line 48 of file HomogeneousSurfaceMaterialTests.cpp.
View newest version in sPHENIX GitHub at line 48 of file HomogeneousSurfaceMaterialTests.cpp
References Acts::HomogeneousSurfaceMaterial::materialProperties(), and Acts::MaterialProperties::scaleThickness().
Acts::Test::BOOST_AUTO_TEST_CASE (HomogeneousVolumeMaterial_access_test)
Definition at line 48 of file HomogeneousVolumeMaterialTests.cpp.
View newest version in sPHENIX GitHub at line 48 of file HomogeneousVolumeMaterialTests.cpp
References Acts::HomogeneousVolumeMaterial::material().
Acts::Test::BOOST_AUTO_TEST_CASE (getSize_test)
Definition at line 49 of file MeasurementHelpersTests.cpp.
View newest version in sPHENIX GitHub at line 49 of file MeasurementHelpersTests.cpp
References Acts::UnitConstants::fm, Acts::MeasurementHelpers::getSize(), eic::m, Acts::UnitConstants::m2, and Acts::UnitConstants::u.
Acts::Test::BOOST_AUTO_TEST_CASE (AccumulatedSurfaceMaterial_fill_convert_0D)
Test the filling and conversion.
Definition at line 50 of file AccumulatedSurfaceMaterialTests.cpp.
View newest version in sPHENIX GitHub at line 50 of file AccumulatedSurfaceMaterialTests.cpp
References Acts::AccumulatedSurfaceMaterial::accumulate(), one, Acts::MaterialProperties::thicknessInX0(), two, and Acts::UnitConstants::u.
Acts::Test::BOOST_AUTO_TEST_CASE (SurfaceBoundsConstruction)
Unit test for creating compliant/non-compliant SurfaceBounds object.
Definition at line 50 of file SurfaceBoundsTests.cpp.
View newest version in sPHENIX GitHub at line 50 of file SurfaceBoundsTests.cpp
References analysis::s, t, Acts::UnitConstants::u, and v.
Acts::Test::BOOST_AUTO_TEST_CASE (DiamondBoundsProperties)
Unit tests for DiamondBounds properties.
Test clone
Test type() (redundant; already used in constructor confirmation)
Test the half length at negative y
Test the half length at the x axis
Test the half length at positive y
Test half length into the negative side
Test half length into the positive side
Test boundingBox
Test distanceToBoundary
Test dump
Test inside
Test vertices (does this need to be implemented in this class??
Definition at line 50 of file DiamondBoundsTests.cpp.
View newest version in sPHENIX GitHub at line 50 of file DiamondBoundsTests.cpp
References Acts::DiamondBounds::boundingBox(), CHECK_CLOSE_REL, Acts::DiamondBounds::distanceToBoundary(), analysis::e, Acts::SurfaceBounds::eDiamond, Acts::DiamondBounds::eHalfLengthXnegY, Acts::DiamondBounds::eHalfLengthXposY, Acts::DiamondBounds::eHalfLengthXzeroY, Acts::DiamondBounds::eHalfLengthYneg, Acts::DiamondBounds::eHalfLengthYpos, Acts::DiamondBounds::get(), Acts::DiamondBounds::inside(), origin(), Acts::DiamondBounds::toStream(), Acts::DiamondBounds::type(), and Acts::DiamondBounds::vertices().
Acts::Test::BOOST_AUTO_TEST_CASE (DiscTrapezoidBoundsRecreation)
Definition at line 50 of file DiscTrapezoidBoundsTests.cpp.
View newest version in sPHENIX GitHub at line 50 of file DiscTrapezoidBoundsTests.cpp
References Acts::DiscTrapezoidBounds::eSize, values, and Acts::DiscTrapezoidBounds::values().
Acts::Test::BOOST_AUTO_TEST_CASE (hana_set_union_test)
Definition at line 51 of file MPLTests.cpp.
View newest version in sPHENIX GitHub at line 51 of file MPLTests.cpp
Acts::Test::BOOST_AUTO_TEST_CASE (GeometryID_innervolume_test)
Definition at line 51 of file TrackingGeometryGeoIDTests.cpp.
View newest version in sPHENIX GitHub at line 51 of file TrackingGeometryGeoIDTests.cpp
References iVolume.
Acts::Test::BOOST_AUTO_TEST_CASE (CutoutCylinderVolumeBoundsExceptions)
Definition at line 52 of file CutoutCylinderVolumeBoundsTests.cpp.
View newest version in sPHENIX GitHub at line 52 of file CutoutCylinderVolumeBoundsTests.cpp
References hz, and rmax().
Acts::Test::BOOST_AUTO_TEST_CASE (micro_benchmark_result)
Definition at line 52 of file BenchmarkTools.cpp.
View newest version in sPHENIX GitHub at line 52 of file BenchmarkTools.cpp
References CHECK_CLOSE_REL, analysis::e, Acts::Test::MicroBenchmarkResult::iters_per_run, Acts::Test::MicroBenchmarkResult::iterTimeAverage(), Acts::Test::MicroBenchmarkResult::iterTimeError(), analysis::res, Acts::Test::MicroBenchmarkResult::run_timings, Acts::Test::MicroBenchmarkResult::runTimeMedian(), Acts::Test::MicroBenchmarkResult::runTimeQuartiles(), Acts::Test::MicroBenchmarkResult::runTimeRobustStddev(), Acts::Test::MicroBenchmarkResult::sortedRunTimes(), and Acts::Test::MicroBenchmarkResult::totalTime().
Acts::Test::BOOST_AUTO_TEST_CASE (SurfaceVisualizationPly)
This tests if the corresponding ply output is well formatted.
Definition at line 54 of file SurfaceVisualizationTests.cpp.
View newest version in sPHENIX GitHub at line 54 of file SurfaceVisualizationTests.cpp
References Acts::SurfaceVisualization::test(), and testPlyString().
Acts::Test::BOOST_AUTO_TEST_CASE (AccumulatedMaterialProperties_trackaverage_test)
Test the event averaging behavior.
Definition at line 54 of file AccumulatedMaterialPropertiesTests.cpp.
View newest version in sPHENIX GitHub at line 54 of file AccumulatedMaterialPropertiesTests.cpp
References a, Acts::AccumulatedMaterialProperties::accumulate(), b, c, CHECK_CLOSE_REL, Acts::Material::massDensity(), Acts::MaterialProperties::material(), Acts::MaterialProperties::thickness(), Acts::MaterialProperties::thicknessInL0(), Acts::MaterialProperties::thicknessInX0(), Acts::AccumulatedMaterialProperties::totalAverage(), Acts::AccumulatedMaterialProperties::trackAverage(), and Acts::UnitConstants::u.
Acts::Test::BOOST_AUTO_TEST_CASE (decomposeToSurfaces)
Definition at line 55 of file GenericCuboidVolumeBoundsTests.cpp.
View newest version in sPHENIX GitHub at line 55 of file GenericCuboidVolumeBoundsTests.cpp
References checkCloseAbs(), Acts::GenericCuboidVolumeBounds::decomposeToSurfaces(), analysis::e, gctx, M_PI, and vtx().
Acts::Test::BOOST_AUTO_TEST_CASE (perp_helper_test)
Definition at line 55 of file HelpersTests.cpp.
View newest version in sPHENIX GitHub at line 55 of file HelpersTests.cpp
References CHECK_CLOSE_ABS, analysis::e, Acts::VectorHelpers::perp(), v, and v2.
Acts::Test::BOOST_AUTO_TEST_CASE (RealQuadraticEquationAssignment)
Unit test for testing RealQuadraticEquation assignment.
Test assignment (implicit)
equality not written and not implicit
Definition at line 55 of file RealQuadraticEquationTests.cpp.
View newest version in sPHENIX GitHub at line 55 of file RealQuadraticEquationTests.cpp
References a, b, c, CHECK_CLOSE_REL, analysis::e, Acts::detail::RealQuadraticEquation::first, Acts::detail::RealQuadraticEquation::second, and Acts::detail::RealQuadraticEquation::solutions.
Acts::Test::BOOST_AUTO_TEST_CASE (AnnulusBoundsExcpetion)
Definition at line 55 of file AnnulusBoundsTests.cpp.
View newest version in sPHENIX GitHub at line 55 of file AnnulusBoundsTests.cpp
References maxPhi, maxRadius, minPhi, minRadius, and offset().
Acts::Test::BOOST_AUTO_TEST_CASE (ConvexPolygonBoundsConstruction)
Definition at line 55 of file ConvexPolygonBoundsTests.cpp.
View newest version in sPHENIX GitHub at line 55 of file ConvexPolygonBoundsTests.cpp
References Acts::ConvexPolygonBounds< N >::boundingBox(), Acts::ConvexPolygonBounds< N >::inside(), Acts::RectangleBounds::max(), and Acts::RectangleBounds::min().
Acts::Test::BOOST_AUTO_TEST_CASE (CylinderBoundsException)
Definition at line 55 of file CylinderBoundsTests.cpp.
View newest version in sPHENIX GitHub at line 55 of file CylinderBoundsTests.cpp
References M_PI.
Acts::Test::BOOST_AUTO_TEST_CASE (SurfaceBoundsProperties)
Definition at line 56 of file SurfaceBoundsTests.cpp.
View newest version in sPHENIX GitHub at line 56 of file SurfaceBoundsTests.cpp
References Acts::SurfaceBoundsStub::values().
Acts::Test::BOOST_AUTO_TEST_CASE (SurfaceConstruction)
todo: make test fixture; separate out different cases
Unit test for creating compliant/non-compliant Surface object
Definition at line 56 of file SurfaceTests.cpp.
View newest version in sPHENIX GitHub at line 56 of file SurfaceTests.cpp
References Acts::Surface::Other, p, tgContext, and transform.
Acts::Test::BOOST_AUTO_TEST_CASE (TrapezoidBoundsException)
Definition at line 56 of file TrapezoidBoundsTests.cpp.
View newest version in sPHENIX GitHub at line 56 of file TrapezoidBoundsTests.cpp
References halfY.
Acts::Test::BOOST_AUTO_TEST_CASE (VolumeVisualizationPly)
Definition at line 56 of file VolumeVisualizationTests.cpp.
View newest version in sPHENIX GitHub at line 56 of file VolumeVisualizationTests.cpp
References Acts::VolumeVisualization::test(), and testPlyString().
Acts::Test::BOOST_AUTO_TEST_CASE (RadialBoundsException)
Definition at line 57 of file RadialBoundsTests.cpp.
View newest version in sPHENIX GitHub at line 57 of file RadialBoundsTests.cpp
References M_PI, maxRadius, and minRadius.
Acts::Test::BOOST_AUTO_TEST_CASE (TestConstantBFieldInterfaceConsistency)
Definition at line 57 of file MagneticFieldInterfaceConsistencyTests.cpp.
View newest version in sPHENIX GitHub at line 57 of file MagneticFieldInterfaceConsistencyTests.cpp
References testInterfaceConsistency().
Acts::Test::BOOST_AUTO_TEST_CASE (InterpolatedMaterialMap_MaterialMapper_test)
Definition at line 59 of file InterpolatedMaterialMapTests.cpp.
View newest version in sPHENIX GitHub at line 59 of file InterpolatedMaterialMapTests.cpp
References CHECK_CLOSE_REL, Acts::MaterialMapper< G >::getMaterial(), and trafoGlobalToLocal().
Acts::Test::BOOST_AUTO_TEST_CASE (GeometryID_order)
Definition at line 59 of file GeometryIDTests.cpp.
View newest version in sPHENIX GitHub at line 59 of file GeometryIDTests.cpp
References Acts::GeometryID::setLayer(), Acts::GeometryID::setSensitive(), Acts::GeometryID::setVolume(), and Acts::UnitConstants::u.
Acts::Test::BOOST_AUTO_TEST_CASE (two_materials)
Definition at line 60 of file AccumulatedVolumeMaterialTests.cpp.
View newest version in sPHENIX GitHub at line 60 of file AccumulatedVolumeMaterialTests.cpp
References Acts::AccumulatedVolumeMaterial::accumulate(), Acts::AccumulatedVolumeMaterial::average(), CHECK_CLOSE_REL, and analysis::e.
Acts::Test::BOOST_AUTO_TEST_CASE (CuboidVolumeBuilderTest)
Definition at line 60 of file CuboidVolumeBuilderTests.cpp.
View newest version in sPHENIX GitHub at line 60 of file CuboidVolumeBuilderTests.cpp
References Acts::units::_m, Acts::units::_mm, Acts::units::_um, Acts::active, Acts::CuboidVolumeBuilder::buildLayer(), Acts::CuboidVolumeBuilder::buildSurface(), Acts::CuboidVolumeBuilder::buildVolume(), CHECK_CLOSE_ABS, configureMap::config, cos(), Acts::CuboidVolumeBuilder::SurfaceConfig::detElementConstructor, analysis::e, Acts::CuboidVolumeBuilder::VolumeConfig::layerCfg, Acts::CuboidVolumeBuilder::VolumeConfig::layers, Acts::CuboidVolumeBuilder::VolumeConfig::length, Acts::CuboidVolumeBuilder::Config::length, Acts::UnitConstants::m, M_PI, makeBeryllium(), Acts::CuboidVolumeBuilder::VolumeConfig::name, Acts::CuboidVolumeBuilder::SurfaceConfig::position, Acts::CuboidVolumeBuilder::VolumeConfig::position, Acts::CuboidVolumeBuilder::Config::position, Acts::CuboidVolumeBuilder::SurfaceConfig::rBounds, Acts::CuboidVolumeBuilder::SurfaceConfig::rotation, Acts::CuboidVolumeBuilder::setConfig(), Acts::CuboidVolumeBuilder::LayerConfig::surfaceCfg, Acts::CuboidVolumeBuilder::SurfaceConfig::surMat, Acts::tgContext, thickness, Acts::CuboidVolumeBuilder::SurfaceConfig::thickness, Acts::TrackingGeometryBuilder::trackingGeometry(), Acts::CuboidVolumeBuilder::trackingVolume(), Acts::TrackingGeometryBuilder::Config::trackingVolumeBuilders, Acts::UnitConstants::u, Acts::CuboidVolumeBuilder::Config::volumeCfg, and Acts::CuboidVolumeBuilder::VolumeConfig::volumeMaterial.
Acts::Test::BOOST_AUTO_TEST_CASE (LineBoundsAssignment)
Unit test for testing LineBounds assignment.
Definition at line 61 of file LineBoundsTests.cpp.
View newest version in sPHENIX GitHub at line 61 of file LineBoundsTests.cpp
Acts::Test::BOOST_AUTO_TEST_CASE (construct_with_weights)
Definition at line 61 of file MaterialCompositionTests.cpp.
View newest version in sPHENIX GitHub at line 61 of file MaterialCompositionTests.cpp
References CHECK_CLOSE_REL, eps, analysis::f, and Acts::UnitConstants::u.
Acts::Test::BOOST_AUTO_TEST_CASE (impactpoint_estimator_params_distance_test)
Unit test for ImpactPointEstimator params and distance.
Definition at line 61 of file ImpactPointEstimatorTests.cpp.
View newest version in sPHENIX GitHub at line 61 of file ImpactPointEstimatorTests.cpp
References _T, Acts::IntegrationTest::bField, Acts::ImpactPointEstimator< input_track_t, propagator_t, propagator_options_t >::calculate3dDistance(), CHECK_CLOSE_REL, d0Dist(), debugMode, analysis::e, Acts::eLOC_D0, Acts::eLOC_Z0, Acts::eQOP, Acts::ImpactPointEstimator< input_track_t, propagator_t, propagator_options_t >::estimate3DImpactParameters(), Acts::eTHETA, geoContext, magFieldContext, phiDist(), pTDist(), qDist(), analysis::res, resAngDist(), resIPDist(), resQoPDist(), propagation_timing::stepper, thetaDist(), and z0Dist().
Acts::Test::BOOST_AUTO_TEST_CASE (ConeBoundsRecreation)
Definition at line 61 of file ConeBoundsTests.cpp.
View newest version in sPHENIX GitHub at line 61 of file ConeBoundsTests.cpp
References starlightConstants::alpha, Acts::ConeBounds::eSize, M_PI, values, and Acts::ConeBounds::values().
Acts::Test::BOOST_AUTO_TEST_CASE (TestSolenoidBFieldInterfaceConsistency)
Definition at line 62 of file MagneticFieldInterfaceConsistencyTests.cpp.
View newest version in sPHENIX GitHub at line 62 of file MagneticFieldInterfaceConsistencyTests.cpp
References testInterfaceConsistency().
Acts::Test::BOOST_AUTO_TEST_CASE (RectangleBoundsRecreation)
Recreation.
Definition at line 63 of file RectangleBoundsTests.cpp.
View newest version in sPHENIX GitHub at line 63 of file RectangleBoundsTests.cpp
References Acts::RectangleBounds::eSize, halfX, halfY, values, and Acts::RectangleBounds::values().
Acts::Test::BOOST_AUTO_TEST_CASE (CuboidVolumeProperties)
Definition at line 64 of file CuboidVolumeBoundsTests.cpp.
View newest version in sPHENIX GitHub at line 64 of file CuboidVolumeBoundsTests.cpp
References CHECK_CLOSE_ABS, Acts::VolumeBounds::eCuboid, Acts::CuboidVolumeBounds::eHalfLengthX, Acts::CuboidVolumeBounds::eHalfLengthY, Acts::CuboidVolumeBounds::eHalfLengthZ, Acts::CuboidVolumeBounds::get(), hx, hy, hz, Acts::CuboidVolumeBounds::inside(), Acts::s_epsilon, Acts::s_onSurfaceTolerance, Acts::CuboidVolumeBounds::type(), and Acts::CuboidVolumeBounds::values().
Acts::Test::BOOST_AUTO_TEST_CASE (HomogeneousSurfaceMaterial_access_test)
Definition at line 64 of file HomogeneousSurfaceMaterialTests.cpp.
View newest version in sPHENIX GitHub at line 64 of file HomogeneousSurfaceMaterialTests.cpp
References Acts::backward, CHECK_CLOSE_REL, analysis::e, Acts::ISurfaceMaterial::factor(), Acts::forward, Acts::fullUpdate, Acts::HomogeneousSurfaceMaterial::materialProperties(), Acts::postUpdate, Acts::preUpdate, and Acts::MaterialProperties::scaleThickness().
Acts::Test::BOOST_AUTO_TEST_CASE (SurfaceBoundsEquality)
Unit test for testing SurfaceBounds properties.
Definition at line 64 of file SurfaceBoundsTests.cpp.
View newest version in sPHENIX GitHub at line 64 of file SurfaceBoundsTests.cpp
References Acts::SurfaceBoundsStub::values().
Acts::Test::BOOST_AUTO_TEST_CASE (adaptive_multi_vertex_fitter_test)
Unit test for AdaptiveMultiVertexFitter.
Definition at line 64 of file AdaptiveMultiVertexFitterTests.cpp.
View newest version in sPHENIX GitHub at line 64 of file AdaptiveMultiVertexFitterTests.cpp
References Acts::units::_mm, _T, Acts::AdaptiveMultiVertexFitter< input_track_t, linearizer_t >::State::addVertexToMultiMap(), Acts::AdaptiveMultiVertexFitter< input_track_t, linearizer_t >::addVtxToFit(), bField, c, CHECK_CLOSE_ABS, d0Dist(), debugMode, Acts::AdaptiveMultiVertexFitter< input_track_t, linearizer_t >::Config::doSmoothing, geoContext, magFieldContext, phiDist(), pTDist(), qDist(), resAngDist(), resIPDist(), resQoPDist(), Acts::Vertex< input_track_t >::setFullCovariance(), propagation_timing::stepper, thetaDist(), Acts::AdaptiveMultiVertexFitter< input_track_t, linearizer_t >::State::tracksAtVerticesMap, Acts::AdaptiveMultiVertexFitter< input_track_t, linearizer_t >::State::trackToVerticesMultiMap, vtx(), Acts::AdaptiveMultiVertexFitter< input_track_t, linearizer_t >::State::vtxInfoMap, and z0Dist().
Acts::Test::BOOST_AUTO_TEST_CASE (linearized_track_factory_test)
Unit test for HelicalTrackLinearizer.
Definition at line 64 of file LinearizedTrackFactoryTests.cpp.
View newest version in sPHENIX GitHub at line 64 of file LinearizedTrackFactoryTests.cpp
References _T, Acts::IntegrationTest::bField, Acts::LinearizedTrack::constantTerm, Acts::LinearizedTrack::covarianceAtPCA, d0Dist(), geoContext, Acts::LinearizedTrack::linearizationPoint, Acts::HelicalTrackLinearizer< propagator_t, propagator_options_t >::linearizeTrack(), magFieldContext, Acts::LinearizedTrack::momentumJacobian, Dataset::parameters, Acts::LinearizedTrack::parametersAtPCA, phiDist(), Acts::LinearizedTrack::positionJacobian, pTDist(), qDist(), resAngDist(), resIPDist(), resQoPDist(), propagation_timing::stepper, thetaDist(), vXYDist(), vZDist(), x, analysis::y, z, and z0Dist().
Acts::Test::BOOST_AUTO_TEST_CASE (DiscTrapezoidBoundsExceptions)
Definition at line 64 of file DiscTrapezoidBoundsTests.cpp.
View newest version in sPHENIX GitHub at line 64 of file DiscTrapezoidBoundsTests.cpp
Acts::Test::BOOST_AUTO_TEST_CASE (theta_eta_test_helper)
Definition at line 65 of file HelpersTests.cpp.
View newest version in sPHENIX GitHub at line 65 of file HelpersTests.cpp
References CHECK_CLOSE_ABS, analysis::e, Acts::VectorHelpers::eta(), Acts::VectorHelpers::theta(), v, and v2.
Acts::Test::BOOST_AUTO_TEST_CASE (Kalman_Vertex_TrackUpdater)
Unit test for KalmanVertexTrackUpdater.
Definition at line 65 of file KalmanVertexTrackUpdaterTests.cpp.
View newest version in sPHENIX GitHub at line 65 of file KalmanVertexTrackUpdaterTests.cpp
References _T, Acts::IntegrationTest::bField, Acts::ImpactPointEstimator< input_track_t, propagator_t, propagator_options_t >::calculate3dDistance(), d0Dist(), Acts::IntegrationTest::debug, Acts::TrackAtVertex< input_track_t >::fittedParams, geoContext, Acts::TrackAtVertex< input_track_t >::linearizedState, Acts::HelicalTrackLinearizer< propagator_t, propagator_options_t >::linearizeTrack(), magFieldContext, phiDist(), pTDist(), qDist(), resAngDist(), resIPDist(), resQoPDist(), propagation_timing::stepper, thetaDist(), vtx(), vXYDist(), vZDist(), and z0Dist().
Acts::Test::BOOST_AUTO_TEST_CASE (Kalman_Vertex_Updater)
Unit test for KalmanVertexUpdater.
Definition at line 65 of file KalmanVertexUpdaterTests.cpp.
View newest version in sPHENIX GitHub at line 65 of file KalmanVertexUpdaterTests.cpp
References _T, Acts::IntegrationTest::bField, d0Dist(), Acts::IntegrationTest::debug, geoContext, Acts::TrackAtVertex< input_track_t >::linearizedState, Acts::HelicalTrackLinearizer< propagator_t, propagator_options_t >::linearizeTrack(), magFieldContext, phiDist(), pTDist(), qDist(), resAngDist(), resIPDist(), resQoPDist(), Acts::Vertex< input_track_t >::setFullCovariance(), propagation_timing::stepper, thetaDist(), vtx(), vXYDist(), vZDist(), and z0Dist().
Acts::Test::BOOST_AUTO_TEST_CASE (PerigeeSurfaceProperties)
Unit test for testing PerigeeSurface properties.
Test clone method
Test type (redundant)
Test name
Test dump
Definition at line 66 of file PerigeeSurfaceTests.cpp.
View newest version in sPHENIX GitHub at line 66 of file PerigeeSurfaceTests.cpp
References Acts::Surface::Perigee, and tgContext.
Acts::Test::BOOST_AUTO_TEST_CASE (hana_set_to_tuple_test)
Definition at line 67 of file MPLTests.cpp.
View newest version in sPHENIX GitHub at line 67 of file MPLTests.cpp
Acts::Test::BOOST_AUTO_TEST_CASE (TestInterpolatedBFieldMapInterfaceConsistency)
Definition at line 67 of file MagneticFieldInterfaceConsistencyTests.cpp.
View newest version in sPHENIX GitHub at line 67 of file MagneticFieldInterfaceConsistencyTests.cpp
References b, configureMap::config, eic::m, Acts::InterpolatedBFieldMap< Mapper_t >::Config::scale, and testInterfaceConsistency().
Acts::Test::BOOST_AUTO_TEST_CASE (intersect_points)
Definition at line 68 of file BoundingBoxTest.cpp.
View newest version in sPHENIX GitHub at line 68 of file BoundingBoxTest.cpp
References p.
Acts::Test::BOOST_AUTO_TEST_CASE (zscan_finder_test)
Unit test for ZScanVertexFinder.
Definition at line 68 of file ZScanVertexFinderTests.cpp.
View newest version in sPHENIX GitHub at line 68 of file ZScanVertexFinderTests.cpp
References Acts::units::_mm, _T, Acts::IntegrationTest::bField, CHECK_CLOSE_ABS, d0Dist(), Acts::eZ, geoContext, magFieldContext, phiDist(), pTDist(), qDist(), analysis::res, resAngDist(), resIPDist(), resQoPDist(), propagation_timing::stepper, thetaDist(), vXYDist(), vZDist(), x, analysis::y, z, and z0Dist().
Acts::Test::BOOST_AUTO_TEST_CASE (MinimalSourceLinkTest)
Definition at line 69 of file MeasurementHelpersTests.cpp.
View newest version in sPHENIX GitHub at line 69 of file MeasurementHelpersTests.cpp
References Acts::UnitConstants::fm, eic::m, and Acts::UnitConstants::m2.
Acts::Test::BOOST_AUTO_TEST_CASE (LineBoundsProperties)
Unit tests for LineBounds properties.
test for type()
test for inside()
Test negative redius inside
test for distanceToBoundary
test for r()
test for halflengthZ (NOTE: Naming violation)
test for dump
Definition at line 70 of file LineBoundsTests.cpp.
View newest version in sPHENIX GitHub at line 70 of file LineBoundsTests.cpp
References Acts::SurfaceBounds::eLine, Acts::LineBounds::inside(), origin(), and Acts::LineBounds::type().
Acts::Test::BOOST_AUTO_TEST_CASE (interpolation_3d)
Definition at line 70 of file InterpolationTests.cpp.
View newest version in sPHENIX GitHub at line 70 of file InterpolationTests.cpp
References CHECK_CLOSE_REL, analysis::e, Acts::interpolate(), and v.
Acts::Test::BOOST_AUTO_TEST_CASE (BoundaryCheckBoxCovariance)
Definition at line 70 of file BoundaryCheckTests.cpp.
View newest version in sPHENIX GitHub at line 70 of file BoundaryCheckTests.cpp
References Acts::BoundaryCheck::isInside().
Acts::Test::BOOST_AUTO_TEST_CASE (LineSurface_allNamedMethods_test)
Unit tests of all named methods.
Definition at line 71 of file LineSurfaceTests.cpp.
View newest version in sPHENIX GitHub at line 71 of file LineSurfaceTests.cpp
References Acts::binX, Acts::LineSurface::bounds(), CHECK_CLOSE_ABS, CHECK_CLOSE_OR_SMALL, CHECK_CLOSE_REL, cos(), analysis::e, charm_jet_coverage::mom, momentum, tgContext, transform, and v1.
Acts::Test::BOOST_AUTO_TEST_CASE (PrimitivesVisualizationObj)
Definition at line 71 of file PrimitivesVisualizationTests.cpp.
View newest version in sPHENIX GitHub at line 71 of file PrimitivesVisualizationTests.cpp
References Acts::PrimitivesVisualization::test(), and testObjString().
Acts::Test::BOOST_AUTO_TEST_CASE (AccumulatedSurfaceMaterial_fill_convert_1D)
Test the filling and conversion.
Definition at line 72 of file AccumulatedSurfaceMaterialTests.cpp.
View newest version in sPHENIX GitHub at line 72 of file AccumulatedSurfaceMaterialTests.cpp
References Acts::binX, Acts::binY, four, one, Acts::open, Acts::MaterialProperties::thicknessInX0(), three, two, and Acts::UnitConstants::u.
Acts::Test::BOOST_AUTO_TEST_CASE (PlaneSurfaceProperties)
Unit test for testing PlaneSurface properties.
Test clone method
Test type (redundant)
Test binningPosition
Test referenceFrame
Test normal, given 3D position
Test bounds
Test localToGlobal
Testing globalToLocal
Test isOnSurface
intersectionEstimate
Test pathCorrection
Test name
Test dump
Definition at line 72 of file PlaneSurfaceTests.cpp.
View newest version in sPHENIX GitHub at line 72 of file PlaneSurfaceTests.cpp
References Acts::binX, CHECK_CLOSE_OR_SMALL, CHECK_CLOSE_REL, analysis::e, Acts::SurfaceBounds::eRectangle, momentum, Acts::Surface::Plane, and tgContext.
Acts::Test::BOOST_AUTO_TEST_CASE (CylinderVolumeBoundsRecreation)
Definition at line 73 of file CylinderVolumeBoundsTests.cpp.
View newest version in sPHENIX GitHub at line 73 of file CylinderVolumeBoundsTests.cpp
References Acts::CylinderVolumeBounds::eSize, M_PI, rmax(), values, and Acts::CylinderVolumeBounds::values().
Acts::Test::BOOST_AUTO_TEST_CASE (ConeSurfacePolyhedrons)
Unit tests for Cone Surfaces.
The full cone on one side
The full cone on one side
Definition at line 74 of file PolyhedronSurfacesTests.cpp.
View newest version in sPHENIX GitHub at line 74 of file PolyhedronSurfacesTests.cpp
References Acts::units::_mm, starlightConstants::alpha, Acts::binR, Acts::binX, Acts::binY, Acts::binZ, CHECK_CLOSE_ABS, analysis::e, r, testModes, Acts::tgContext, and transform.
Acts::Test::BOOST_AUTO_TEST_CASE (SurfaceProperties , *utf:: expected_failures1)
Unit test for testing Surface properties.
Definition at line 74 of file SurfaceTests.cpp.
View newest version in sPHENIX GitHub at line 74 of file SurfaceTests.cpp
References Acts::Surface::assignSurfaceMaterial(), Acts::Surface::associatedDetectorElement(), Acts::Surface::associatedLayer(), Acts::Surface::associateLayer(), Acts::Surface::center(), CHECK_CLOSE_OR_SMALL, Acts::PlaneLayer::create(), analysis::e, Acts::Surface::insideBounds(), Acts::PlanarHelper::intersectionEstimate(), Acts::SurfaceStub::intersectionEstimate(), Acts::Surface::isOnSurface(), charm_jet_coverage::mom, Acts::Intersection::position, Acts::Surface::referenceFrame(), Acts::Surface::surfaceMaterial(), tgContext, Acts::Surface::transform(), and zero.
Acts::Test::BOOST_AUTO_TEST_CASE (ConeBoundsExceptions)
Definition at line 74 of file ConeBoundsTests.cpp.
View newest version in sPHENIX GitHub at line 74 of file ConeBoundsTests.cpp
References starlightConstants::alpha, and M_PI.
Acts::Test::BOOST_AUTO_TEST_CASE (ERROR_test)
unit test for ERROR debug level
This test checks for the expected output when using the Acts::Logging::ERROR debug level as threshold. It also tests
ACTS_LOCAL_LOGGER
Acts::getDefaultLogger
Definition at line 75 of file LoggerTests.cpp.
View newest version in sPHENIX GitHub at line 75 of file LoggerTests.cpp
References ACTS_DEBUG, ACTS_ERROR, ACTS_FATAL, ACTS_INFO, ACTS_LOCAL_LOGGER, ACTS_VERBOSE, ACTS_WARNING, ERROR, and getline.
Acts::Test::BOOST_AUTO_TEST_CASE (DiscSurface_properties_test , *utf:: expected_failures2)
Unit tests of all named methods.
Test type
Test normal, no local position specified
Test normal, local position specified
Test binningPosition
Test bounds
Test isOnSurface()
Test localToGlobal
Test globalToLocal
Test localPolarToCartesian
Test localCartesianToPolar
Test localPolarToLocalCartesian
Test localCartesianToGlobal
Test globalToLocalCartesian
Test pathCorrection
intersectionEstimate
Test name
Definition at line 75 of file DiscSurfaceTests.cpp.
View newest version in sPHENIX GitHub at line 75 of file DiscSurfaceTests.cpp
References Acts::binRPhi, CHECK_CLOSE_ABS, CHECK_CLOSE_REL, Acts::Surface::Disc, analysis::e, Acts::SurfaceBounds::eDisc, M_PI, momentum, and tgContext.
Acts::Test::BOOST_AUTO_TEST_CASE (GeometryID_outervolume_test)
Definition at line 76 of file TrackingGeometryGeoIDTests.cpp.
View newest version in sPHENIX GitHub at line 76 of file TrackingGeometryGeoIDTests.cpp
References iVolume, and oVolume.
Acts::Test::BOOST_AUTO_TEST_CASE (TrapezoidBoundsProperties , *utf:: expected_failures3)
Unit tests for TrapezoidBounds properties.
Test type() (redundant; already used in constructor confirmation)
Test minHalflengthX
Test maxHalfLengthX
Test halflengthY
Test distanceToBoundary
Test vertices
for (auto i: trapezoidBoundsObject.vertices()){ std::cout<<i[0]<<", "<<i[1]<<std::endl; }
Test boundingBox
Test dump
Test inside
Definition at line 77 of file TrapezoidBoundsTests.cpp.
View newest version in sPHENIX GitHub at line 77 of file TrapezoidBoundsTests.cpp
References Acts::TrapezoidBounds::boundingBox(), CHECK_CLOSE_REL, Acts::TrapezoidBounds::distanceToBoundary(), analysis::e, Acts::TrapezoidBounds::eHalfLengthXnegY, Acts::TrapezoidBounds::eHalfLengthXposY, Acts::TrapezoidBounds::eHalfLengthY, Acts::SurfaceBounds::eTrapezoid, Acts::TrapezoidBounds::get(), halfY, Acts::TrapezoidBounds::inside(), origin(), Acts::TrapezoidBounds::toStream(), Acts::TrapezoidBounds::type(), and Acts::TrapezoidBounds::vertices().
Acts::Test::BOOST_AUTO_TEST_CASE (cross_test_helper)
Definition at line 77 of file HelpersTests.cpp.
View newest version in sPHENIX GitHub at line 77 of file HelpersTests.cpp
References CHECK_CLOSE_ABS, Acts::VectorHelpers::cross(), analysis::e, and v.
Acts::Test::BOOST_AUTO_TEST_CASE (AnnulusBoundsProperties)
Unit tests for AnnulusBounds properties.
Test construction with radii and default sector
Test type() (redundant; already used in constructor confirmation)
Test positions inside/outside
Definition at line 77 of file AnnulusBoundsTests.cpp.
View newest version in sPHENIX GitHub at line 77 of file AnnulusBoundsTests.cpp
References Acts::SurfaceBounds::eAnnulus, Acts::AnnulusBounds::eMaxPhiRel, Acts::AnnulusBounds::eMaxR, Acts::AnnulusBounds::eMinPhiRel, Acts::AnnulusBounds::eMinR, Acts::AnnulusBounds::get(), Acts::AnnulusBounds::inside(), Acts::AnnulusBounds::insideRadialBounds(), maxPhi, maxRadius, minPhi, minRadius, offset(), Acts::VectorHelpers::perp(), Acts::VectorHelpers::phi(), phi, r, and Acts::AnnulusBounds::type().
Acts::Test::BOOST_AUTO_TEST_CASE (two_materials_different_lengh)
Definition at line 78 of file AccumulatedVolumeMaterialTests.cpp.
View newest version in sPHENIX GitHub at line 78 of file AccumulatedVolumeMaterialTests.cpp
References Acts::AccumulatedVolumeMaterial::accumulate(), Acts::AccumulatedVolumeMaterial::average(), CHECK_CLOSE_REL, and analysis::e.
Acts::Test::BOOST_AUTO_TEST_CASE (StrawSurfaceProperties)
Unit test for testing StrawSurface properties.
Test clone method
Test type (redundant)
Test name
Test dump
Definition at line 78 of file StrawSurfaceTests.cpp.
View newest version in sPHENIX GitHub at line 78 of file StrawSurfaceTests.cpp
References Acts::Surface::Straw, and tgContext.
Acts::Test::BOOST_AUTO_TEST_CASE (PrimitivesVisualizationPly)
Definition at line 81 of file PrimitivesVisualizationTests.cpp.
View newest version in sPHENIX GitHub at line 81 of file PrimitivesVisualizationTests.cpp
References Acts::PrimitivesVisualization::test(), and testPlyString().
Acts::Test::BOOST_AUTO_TEST_CASE (CylinderBoundsProperties)
Unit tests for CylinderBounds properties.
test for type()
test for inside(), 2D coords are r or phi ,z? : needs clarification
test for inside3D() with Vector3D argument
test for distanceToBoundary
test for r()
test for averagePhi
test for halfPhiSector
test for halflengthZ (NOTE: Naming violation)
test for dump
Definition at line 81 of file CylinderBoundsTests.cpp.
View newest version in sPHENIX GitHub at line 81 of file CylinderBoundsTests.cpp
References CHECK_CLOSE_REL, Acts::CylinderBounds::distanceToBoundary(), analysis::e, Acts::CylinderBounds::eAveragePhi, Acts::SurfaceBounds::eCylinder, Acts::CylinderBounds::eHalfLengthZ, Acts::CylinderBounds::eHalfPhiSector, Acts::CylinderBounds::eR, Acts::CylinderBounds::get(), Acts::CylinderBounds::inside(), Acts::CylinderBounds::inside3D(), M_PI, origin(), Acts::CylinderBounds::toStream(), and Acts::CylinderBounds::type().
Acts::Test::BOOST_AUTO_TEST_CASE (BoundaryCheckPolyDistance)
Definition at line 83 of file BoundaryCheckTests.cpp.
View newest version in sPHENIX GitHub at line 83 of file BoundaryCheckTests.cpp
References CHECK_CLOSE_REL, Acts::BoundaryCheck::distance(), analysis::e, rectDistances, rectShiftedDistances, rectShiftedTestPoints, rectShiftedVertices, rectTestPoints, and rectVertices.
Acts::Test::BOOST_AUTO_TEST_CASE (VisualizationTesterPly)
Definition at line 83 of file VisualizationTests.cpp.
View newest version in sPHENIX GitHub at line 83 of file VisualizationTests.cpp
Acts::Test::BOOST_AUTO_TEST_CASE (CylinderVolumeBoundsExceptions)
Definition at line 84 of file CylinderVolumeBoundsTests.cpp.
View newest version in sPHENIX GitHub at line 84 of file CylinderVolumeBoundsTests.cpp
References M_PI, and rmax().
Acts::Test::BOOST_AUTO_TEST_CASE (PolyhedronExtent)
Unit tests for Polyderon construction & operator +=.
Definition at line 84 of file PolyhedronTests.cpp.
View newest version in sPHENIX GitHub at line 84 of file PolyhedronTests.cpp
References Acts::binPhi, Acts::binR, Acts::binX, Acts::binY, Acts::binZ, CHECK_CLOSE_ABS, analysis::e, Acts::Polyhedron::extent(), Acts::VectorHelpers::perp(), Acts::VectorHelpers::phi(), and Acts::PrimitivesVisualization::rectangle.
Acts::Test::BOOST_AUTO_TEST_CASE (TestErrorCodes)
Definition at line 84 of file ResultTests.cpp.
View newest version in sPHENIX GitHub at line 84 of file ResultTests.cpp
References analysis::res, and Acts::UnitConstants::u.
Acts::Test::BOOST_AUTO_TEST_CASE (CylinderSurfaceProperties)
Unit test for testing CylinderSurface properties.
Test clone method
Test type (redundant)
Test binningPosition
Test referenceFrame
Test normal, given 3D position
Test normal given 2D rphi position
Test rotational symmetry axis
Test bounds
Test localToGlobal
Testing globalToLocal
Test isOnSurface
intersectionEstimate
intersect
Test pathCorrection
Test name
Test dump
Definition at line 84 of file CylinderSurfaceTests.cpp.
View newest version in sPHENIX GitHub at line 84 of file CylinderSurfaceTests.cpp
References Acts::binPhi, CHECK_CLOSE_ABS, CHECK_CLOSE_OR_SMALL, CHECK_CLOSE_REL, cos(), Acts::Surface::Cylinder, analysis::e, Acts::SurfaceBounds::eCylinder, momentum, origin(), and testContext.
Acts::Test::BOOST_AUTO_TEST_CASE (iterative_finder_test)
Unit test for IterativeVertexFinder for BoundParameters.
Definition at line 85 of file IterativeVertexFinderTests.cpp.
View newest version in sPHENIX GitHub at line 85 of file IterativeVertexFinderTests.cpp
References Acts::units::_mm, _T, kdfinder::abs(), Acts::IntegrationTest::bField, CHECK_CLOSE_ABS, d0Dist(), Acts::IntegrationTest::debug, Acts::eX, Acts::eY, Acts::eZ, geoContext, magFieldContext, nEvents, nTracksDist(), nVertexDist(), phiDist(), pos, pTDist(), qDist(), analysis::res, resAngDist(), resIPDist(), resQoPDist(), Acts::Vertex< input_track_t >::setTracksAtVertex(), propagation_timing::stepper, thetaDist(), vXYDist(), vZDist(), x, analysis::y, z, and z0Dist().
Acts::Test::BOOST_AUTO_TEST_CASE (RadialBoundsProperties)
Unit tests for RadialBounds properties.
Test type() (redundant; already used in constructor confirmation)
Test distanceToBoundary
Test dump
Test inside
Test rMin
Test rMax
Test averagePhi (should be a redundant method, this is not configurable)
Test halfPhiSector
Definition at line 86 of file RadialBoundsTests.cpp.
View newest version in sPHENIX GitHub at line 86 of file RadialBoundsTests.cpp
References CHECK_CLOSE_REL, Acts::RadialBounds::distanceToBoundary(), analysis::e, Acts::RadialBounds::eAveragePhi, Acts::SurfaceBounds::eDisc, Acts::RadialBounds::eHalfPhiSector, Acts::RadialBounds::eMaxR, Acts::RadialBounds::eMinR, Acts::RadialBounds::get(), Acts::RadialBounds::inside(), M_PI, maxRadius, minRadius, origin(), Acts::RadialBounds::toStream(), and Acts::RadialBounds::type().
Acts::Test::BOOST_AUTO_TEST_CASE (variant_measurement_generation_test)
Definition at line 86 of file FittableTypeTests.cpp.
View newest version in sPHENIX GitHub at line 86 of file FittableTypeTests.cpp
References value.
Acts::Test::BOOST_AUTO_TEST_CASE (atlas_stepper_test)
These tests are aiming to test the functions of the AtlasStepper> The numerical correctness of the stepper is tested in the integration tests
Repeat with surface related methods
Definition at line 86 of file AtlasStepperTests.cpp.
View newest version in sPHENIX GitHub at line 86 of file AtlasStepperTests.cpp
References Acts::ConstrainedStep::actor, Acts::backward, bField, Acts::detail::boundState(), Acts::AtlasStepper< bfield_t >::boundState(), charge, Acts::SingleTrackParameters< ChargePolicy >::charge(), Acts::AtlasStepper< bfield_t >::charge(), CHECK_CLOSE_ABS, CHECK_CLOSE_COVARIANCE, Acts::AtlasStepper< bfield_t >::covarianceTransport(), Acts::AtlasStepper< bfield_t >::curvilinearState(), Acts::AtlasStepper< bfield_t >::direction(), analysis::e, analysis::h, h2, mfContext, charm_jet_coverage::mom, Acts::SingleTrackParameters< ChargePolicy >::momentum(), Acts::AtlasStepper< bfield_t >::momentum(), Acts::AtlasStepper< bfield_t >::outputStepSize(), Acts::PrimitivesVisualization::plane, pos, Acts::SingleTrackParameters< ChargePolicy >::position(), Acts::AtlasStepper< bfield_t >::position(), Acts::UnitConstants::ps, Acts::AtlasStepper< bfield_t >::releaseStepSize(), Acts::AtlasStepper< bfield_t >::setStepSize(), Acts::AtlasStepper< bfield_t >::step(), Acts::Test::PropState::stepping, tgContext, Acts::SingleTrackParameters< ChargePolicy >::time(), Acts::VectorHelpers::time(), Acts::AtlasStepper< bfield_t >::time(), Acts::AtlasStepper< bfield_t >::update(), Acts::AtlasStepper< bfield_t >::updateStepSize(), and Acts::AtlasStepper< bfield_t >::updateSurfaceStatus().
Acts::Test::BOOST_AUTO_TEST_CASE (Transitions)
Definition at line 86 of file FiniteStateMachineTests.cpp.
View newest version in sPHENIX GitHub at line 86 of file FiniteStateMachineTests.cpp
Acts::Test::BOOST_AUTO_TEST_CASE (RectangleBoundsProperties)
Unit test for testing RectangleBounds properties.
Definition at line 87 of file RectangleBoundsTests.cpp.
View newest version in sPHENIX GitHub at line 87 of file RectangleBoundsTests.cpp
References CHECK_CLOSE_ABS, CHECK_CLOSE_REL, Acts::RectangleBounds::distanceToBoundary(), analysis::e, Acts::RectangleBounds::halfLengthX(), Acts::RectangleBounds::halfLengthY(), halfX, halfY, Acts::RectangleBounds::inside(), Acts::RectangleBounds::max(), Acts::RectangleBounds::min(), rectVertices, and Acts::RectangleBounds::vertices().
Acts::Test::BOOST_AUTO_TEST_CASE (ConeSurfaceProperties)
Unit test for testing ConeSurface properties.
Test clone method
Test type (redundant)
Test binningPosition
Test referenceFrame
Test normal, given 3D position
Test normal given 2D rphi position
Test rotational symmetry axis
Test bounds
Test localToGlobal
Testing globalToLocal
Test isOnSurface
Test pathCorrection
Test name
Test dump
Definition at line 87 of file ConeSurfaceTests.cpp.
View newest version in sPHENIX GitHub at line 87 of file ConeSurfaceTests.cpp
References starlightConstants::alpha, Acts::binPhi, CHECK_CLOSE_ABS, CHECK_CLOSE_OR_SMALL, CHECK_CLOSE_REL, Acts::Surface::Cone, analysis::e, Acts::SurfaceBounds::eCone, M_PI, momentum, origin(), and tgContext.
Acts::Test::BOOST_AUTO_TEST_CASE (CutoutCylinderVolumeBoundsAccess)
Definition at line 88 of file CutoutCylinderVolumeBoundsTests.cpp.
View newest version in sPHENIX GitHub at line 88 of file CutoutCylinderVolumeBoundsTests.cpp
References Acts::CutoutCylinderVolumeBounds::eHalfLengthZ, Acts::CutoutCylinderVolumeBounds::eHalfLengthZcutout, Acts::CutoutCylinderVolumeBounds::eMaxR, Acts::CutoutCylinderVolumeBounds::eMedR, Acts::CutoutCylinderVolumeBounds::eMinR, Acts::CutoutCylinderVolumeBounds::get(), hz, and rmax().
Acts::Test::BOOST_AUTO_TEST_CASE (BinningData_BinningValue)
x/y/zData check the global position requests
check the global position requests
check the local position requests
Definition at line 88 of file BinningDataTests.cpp.
View newest version in sPHENIX GitHub at line 88 of file BinningDataTests.cpp
References Acts::binPhi, Acts::BinningData::bins(), Acts::binX, CHECK_CLOSE_REL, CHECK_SMALL, Acts::closed, delta, analysis::e, eta0Position(), etaData_eq, M_PI, nBins_binary, Acts::open, phi0Position(), phiData_arb, phiData_eq, phiDelta, phiMin, phiPihPosition(), rData_eq, rphiPosition(), rphizPosition(), Acts::BinningData::value(), valueMin, xData_add(), xData_arb, xData_eq, xData_mult, xyPosition(), xyzPosition(), yData_eq, and zData_eq.
Acts::Test::BOOST_AUTO_TEST_CASE (unpack_boost_set_as_template_test)
Definition at line 88 of file MPLTests.cpp.
View newest version in sPHENIX GitHub at line 88 of file MPLTests.cpp
References value.
Acts::Test::BOOST_AUTO_TEST_CASE (GeometryID_closeGeometry_test)
Definition at line 89 of file TrackingGeometryClosureTests.cpp.
View newest version in sPHENIX GitHub at line 89 of file TrackingGeometryClosureTests.cpp
References Acts::BinnedArray< T >::arrayObjects(), Acts::TrackingVolume::boundarySurfaces(), Acts::TrackingVolume::confinedLayers(), Acts::GeometryObject::geoID(), Acts::GeometryID::volume(), and world.
Acts::Test::BOOST_AUTO_TEST_CASE (straight_line_stepper_test)
These tests are aiming to test the functions of the StraightLineStepper The numerical correctness of the stepper is tested in the integration tests
Repeat with surface related methods
Definition at line 90 of file StraightLineStepperTests.cpp.
View newest version in sPHENIX GitHub at line 90 of file StraightLineStepperTests.cpp
References Acts::ConstrainedStep::actor, Acts::backward, Acts::detail::boundState(), Acts::StraightLineStepper::boundState(), charge, Acts::SingleTrackParameters< ChargePolicy >::charge(), Acts::StraightLineStepper::charge(), CHECK_CLOSE_ABS, CHECK_CLOSE_COVARIANCE, Acts::StraightLineStepper::State::cov, Acts::StraightLineStepper::covarianceTransport(), Acts::StraightLineStepper::curvilinearState(), Acts::StraightLineStepper::State::derivative, Acts::StraightLineStepper::State::dir, Acts::StraightLineStepper::direction(), analysis::e, Acts::StraightLineStepper::State::geoContext, analysis::h, h2, Acts::StraightLineStepper::State::jacToGlobal, Acts::StraightLineStepper::State::jacTransport, mfContext, charm_jet_coverage::mom, Acts::SingleTrackParameters< ChargePolicy >::momentum(), Acts::StraightLineStepper::momentum(), Acts::StraightLineStepper::State::navDir, Acts::StraightLineStepper::outputStepSize(), Acts::StraightLineStepper::State::p, Acts::PrimitivesVisualization::plane, Acts::StraightLineStepper::State::pos, pos, Acts::SingleTrackParameters< ChargePolicy >::position(), Acts::StraightLineStepper::position(), Acts::StraightLineStepper::State::previousStepSize, Acts::UnitConstants::ps, Acts::StraightLineStepper::State::q, Acts::StraightLineStepper::releaseStepSize(), Acts::StraightLineStepper::setStepSize(), Acts::StraightLineStepper::step(), Acts::StraightLineStepper::State::stepSize, Acts::StraightLineStepper::State::t, tgContext, Acts::SingleTrackParameters< ChargePolicy >::time(), Acts::StraightLineStepper::time(), Acts::VectorHelpers::time(), Acts::ConstrainedStep::toString(), Acts::StraightLineStepper::update(), Acts::StraightLineStepper::updateStepSize(), Acts::StraightLineStepper::updateSurfaceStatus(), and Acts::ConstrainedStep::value().
Acts::Test::BOOST_AUTO_TEST_CASE (visit_measurement_test)
Definition at line 94 of file MeasurementHelpersTests.cpp.
View newest version in sPHENIX GitHub at line 94 of file MeasurementHelpersTests.cpp
References dim, and Acts::visit_measurement().
Acts::Test::BOOST_AUTO_TEST_CASE (TestSharedBFieldInterfaceConsistency)
Definition at line 95 of file MagneticFieldInterfaceConsistencyTests.cpp.
View newest version in sPHENIX GitHub at line 95 of file MagneticFieldInterfaceConsistencyTests.cpp
References testInterfaceConsistency().
Acts::Test::BOOST_AUTO_TEST_CASE (track_density_finder_constr_test)
Unit test for TrackDensityVertexFinder using same configuration and values as VertexSeedFinderTestAlg in Athena implementation.
Definition at line 96 of file TrackDensityVertexFinderTests.cpp.
View newest version in sPHENIX GitHub at line 96 of file TrackDensityVertexFinderTests.cpp
References Acts::units::_MeV, Acts::units::_mm, CHECK_CLOSE_ABS, Acts::eX, Acts::eY, Acts::eZ, Acts::TrackDensityVertexFinder< vfitter_t, track_density_t >::find(), geoContext, magFieldContext, analysis::res, Acts::Vertex< input_track_t >::setCovariance(), and Acts::VertexingOptions< input_track_t >::vertexConstraint.
Acts::Test::BOOST_AUTO_TEST_CASE (ConeBoundsProperties)
Unit tests for properties of ConeBounds object.
test for type (redundant)
test for inside
test for distanceToBoundary
test for r
test for tanAlpha
test for alpha
test for minZ
test for maxZ
test for averagePhi
test for dump
Definition at line 96 of file ConeBoundsTests.cpp.
View newest version in sPHENIX GitHub at line 96 of file ConeBoundsTests.cpp
References starlightConstants::alpha, CHECK_CLOSE_REL, analysis::e, Acts::ConeBounds::eAlpha, Acts::SurfaceBounds::eCone, Acts::ConeBounds::eHalfPhiSector, Acts::ConeBounds::eMaxZ, Acts::ConeBounds::eMinZ, Acts::ConeBounds::get(), Acts::ConeBounds::inside(), M_PI, origin(), Acts::ConeBounds::r(), Acts::ConeBounds::tanAlpha(), Acts::ConeBounds::toStream(), and Acts::ConeBounds::type().
Acts::Test::BOOST_AUTO_TEST_CASE (ConvexPolygonBoundsRecreation)
Definition at line 97 of file ConvexPolygonBoundsTests.cpp.
View newest version in sPHENIX GitHub at line 97 of file ConvexPolygonBoundsTests.cpp
References Acts::ConvexPolygonBoundsBase::values(), and values.
Acts::Test::BOOST_AUTO_TEST_CASE (variable_axis)
Definition at line 98 of file AxesTests.cpp.
View newest version in sPHENIX GitHub at line 98 of file AxesTests.cpp
References a, and Acts::UnitConstants::u.
Acts::Test::BOOST_AUTO_TEST_CASE (SurfaceMaterialMapper_tests)
Test the filling and conversion.
We need a Navigator, Stepper to build a Propagator
The config object
Create some contexts
Now create the mapper state
Test if this is not null
We need a Navigator, Stepper to build a Propagator
The config object
Create some contexts
Now create the mapper state
Test if this is not null
We need a Navigator, Stepper to build a Propagator
The config object
Create some contexts
Now create the mapper state
Test if this is not null
Definition at line 99 of file SurfaceMaterialMapperTests.cpp.
View newest version in sPHENIX GitHub at line 99 of file SurfaceMaterialMapperTests.cpp
References Acts::SurfaceMaterialMapper::createState(), navigator, propagation_timing::stepper, and Acts::UnitConstants::u.
Acts::Test::BOOST_AUTO_TEST_CASE (micro_benchmark)
Definition at line 99 of file BenchmarkTools.cpp.
View newest version in sPHENIX GitHub at line 99 of file BenchmarkTools.cpp
References analysis::input, and microBenchmark().
Acts::Test::BOOST_AUTO_TEST_CASE (AccumulatedMaterialProperties_totalaverage_test)
Test the total averaging behavior.
Test: average a + 3a + v
Test: average 4a + v
Test: average: a + 3a + emptyhit
Definition at line 99 of file AccumulatedMaterialPropertiesTests.cpp.
View newest version in sPHENIX GitHub at line 99 of file AccumulatedMaterialPropertiesTests.cpp
References a, a3, Acts::AccumulatedMaterialProperties::accumulate(), CHECK_CLOSE_REL, Acts::MaterialProperties::material(), Acts::MaterialProperties::thickness(), Acts::AccumulatedMaterialProperties::totalAverage(), Acts::AccumulatedMaterialProperties::trackAverage(), Acts::UnitConstants::u, and v.
Acts::Test::BOOST_AUTO_TEST_CASE (CutoutCylinderVolumeBoundsInside)
Definition at line 100 of file CutoutCylinderVolumeBoundsTests.cpp.
View newest version in sPHENIX GitHub at line 100 of file CutoutCylinderVolumeBoundsTests.cpp
References Acts::CutoutCylinderVolumeBounds::inside().
Acts::Test::BOOST_AUTO_TEST_CASE (GeometryID_containervolume_test)
pre-check on GeometryID
let's check that the geometry ID values are all 0
check the boundaries of the hVolume, should also be 0
let's check everything is set to 0
Definition at line 102 of file TrackingGeometryGeoIDTests.cpp.
View newest version in sPHENIX GitHub at line 102 of file TrackingGeometryGeoIDTests.cpp
References hVolume.
Acts::Test::BOOST_AUTO_TEST_CASE (kalman_extrapolator)
Unit test for Kalman fitter propagation.
Definition at line 102 of file KalmanExtrapolatorTests.cpp.
View newest version in sPHENIX GitHub at line 102 of file KalmanExtrapolatorTests.cpp
References Acts::units::_GeV, Acts::units::_m, Acts::units::_mm, Acts::IntegrationTest::bField, cGeometry, CHECK_CLOSE_OR_SMALL, CHECK_CLOSE_REL, analysis::e, mfContext, charm_jet_coverage::mom, navigator, pos, Acts::Navigator::resolveMaterial, Acts::Navigator::resolvePassive, Acts::Navigator::resolveSensitive, propagation_timing::stepper, and Acts::tgContext.
Acts::Test::BOOST_AUTO_TEST_CASE (AbortListTest_PathLimit)
Definition at line 104 of file AbortListTests.cpp.
View newest version in sPHENIX GitHub at line 104 of file AbortListTests.cpp
References Acts::units::_cm, Acts::units::_m, Acts::units::_um, Acts::AbortList< aborters_t >::append(), Acts::detail::Extendable< aborters_t...>::get(), Acts::Test::PropagatorState::options, Acts::Test::PropagatorState::StepperState::pathAccumulated, Acts::Test::PropagatorState::Options::pathLimit, propagation_timing::stepper, Acts::Test::PropagatorState::stepping, and Acts::Test::PropagatorState::StepperState::stepSize.
Acts::Test::BOOST_AUTO_TEST_CASE (interpolation_mixed_point_values)
Definition at line 104 of file InterpolationTests.cpp.
View newest version in sPHENIX GitHub at line 104 of file InterpolationTests.cpp
References CHECK_CLOSE_REL, analysis::e, Acts::interpolate(), p, and v.
Acts::Test::BOOST_AUTO_TEST_CASE (toString_test_helper)
Definition at line 105 of file HelpersTests.cpp.
View newest version in sPHENIX GitHub at line 105 of file HelpersTests.cpp
References Acts::toString().
Acts::Test::BOOST_AUTO_TEST_CASE (WARNING_test)
unit test for WARNING debug level
This test checks for the expected output when using the Acts::Logging::WARNING debug level as threshold. It also tests
ACTS_LOCAL_LOGGER
Acts::getDefaultLogger
Definition at line 105 of file LoggerTests.cpp.
View newest version in sPHENIX GitHub at line 105 of file LoggerTests.cpp
References ACTS_DEBUG, ACTS_ERROR, ACTS_FATAL, ACTS_INFO, ACTS_LOCAL_LOGGER, ACTS_VERBOSE, ACTS_WARNING, getline, and WARNING.
Acts::Test::BOOST_AUTO_TEST_CASE (DiscTrapezoidBoundsProperties)
Unit tests for DiscTrapezoidBounds properties.
Test clone
Test type() (redundant; already used in constructor confirmation)
Test distanceToBoundary
Test dump
Test inside
Test rMin
Test rMax
Test averagePhi
Test rCenter (redundant; not configurable)
Test halfPhiSector (redundant; not configurable)
Test minHalflengthX
Test maxHalflengthX
Test halflengthY
Definition at line 105 of file DiscTrapezoidBoundsTests.cpp.
View newest version in sPHENIX GitHub at line 105 of file DiscTrapezoidBoundsTests.cpp
References CHECK_CLOSE_REL, CHECK_SMALL, Acts::DiscTrapezoidBounds::distanceToBoundary(), analysis::e, Acts::DiscTrapezoidBounds::eAveragePhi, Acts::SurfaceBounds::eDiscTrapezoid, Acts::DiscTrapezoidBounds::eHalfLengthXmaxR, Acts::DiscTrapezoidBounds::eHalfLengthXminR, Acts::DiscTrapezoidBounds::get(), Acts::DiscTrapezoidBounds::halfLengthY(), Acts::DiscTrapezoidBounds::inside(), origin(), Acts::DiscTrapezoidBounds::rCenter(), Acts::DiscTrapezoidBounds::rMax(), Acts::DiscTrapezoidBounds::rMin(), Acts::DiscTrapezoidBounds::stereo(), Acts::DiscTrapezoidBounds::toStream(), and Acts::DiscTrapezoidBounds::type().
Acts::Test::BOOST_AUTO_TEST_CASE (Terminted)
Definition at line 106 of file FiniteStateMachineTests.cpp.
View newest version in sPHENIX GitHub at line 106 of file FiniteStateMachineTests.cpp
Acts::Test::BOOST_AUTO_TEST_CASE (grid_test_2d_equidistant)
Definition at line 106 of file GridTests.cpp.
View newest version in sPHENIX GitHub at line 106 of file GridTests.cpp
References a, b, g(), Acts::detail::Grid< T, Axes >::globalBinFromLocalBins(), Acts::detail::Grid< T, Axes >::globalBinFromPosition(), Acts::detail::Grid< T, Axes >::localBinsFromGlobalBin(), Acts::detail::Grid< T, Axes >::numLocalBins(), Acts::detail::Grid< T, Axes >::size(), and Acts::UnitConstants::u.
Acts::Test::BOOST_AUTO_TEST_CASE (BoundaryCheckTriangleSimple)
Definition at line 106 of file BoundaryCheckTests.cpp.
View newest version in sPHENIX GitHub at line 106 of file BoundaryCheckTests.cpp
References Acts::BoundaryCheck::isInside().
Acts::Test::BOOST_AUTO_TEST_CASE (EllipseBoundsProperties)
Unit tests for EllipseBounds properties.
Test clone
Test type() (redundant; already used in constructor confirmation)
Test distanceToBoundary
Test rMinX
Test rMinY
Test rMaxX
Test rMaxY
Test averagePhi
Test vertices
Test boundingBox
Test halfPhiSector
Test dump
Test inside
Definition at line 107 of file EllipseBoundsTests.cpp.
View newest version in sPHENIX GitHub at line 107 of file EllipseBoundsTests.cpp
References Acts::EllipseBounds::boundingBox(), CHECK_CLOSE_REL, Acts::EllipseBounds::distanceToBoundary(), analysis::e, Acts::EllipseBounds::eAveragePhi, Acts::SurfaceBounds::eEllipse, Acts::EllipseBounds::eHalfPhiSector, Acts::EllipseBounds::eInnerRx, Acts::EllipseBounds::eInnerRy, Acts::EllipseBounds::eOuterRx, Acts::EllipseBounds::eOuterRy, Acts::EllipseBounds::get(), Acts::EllipseBounds::inside(), M_PI, origin(), Acts::EllipseBounds::toStream(), and Acts::EllipseBounds::type().
Acts::Test::BOOST_AUTO_TEST_CASE (annealing_tool_multiChi2_tests)
Definition at line 109 of file AnnealingUtilityTests.cpp.
View newest version in sPHENIX GitHub at line 109 of file AnnealingUtilityTests.cpp
References Acts::AnnealingUtility::anneal(), configureMap::config, Acts::AnnealingUtility::State::currentTemperatureIndex, Acts::AnnealingUtility::Config::cutOff, Acts::AnnealingUtility::State::equilibriumReached, Acts::AnnealingUtility::getWeight(), and Acts::UnitConstants::u.
Acts::Test::BOOST_AUTO_TEST_CASE (ConvexPolygonBoundsDynamicTest)
Definition at line 109 of file ConvexPolygonBoundsTests.cpp.
View newest version in sPHENIX GitHub at line 109 of file ConvexPolygonBoundsTests.cpp
References Acts::ConvexPolygonBounds< N >::boundingBox(), Acts::ConvexPolygonBounds< N >::inside(), Acts::RectangleBounds::max(), and Acts::RectangleBounds::min().
Acts::Test::BOOST_AUTO_TEST_CASE (RectangleBoundsAssignment)
Definition at line 110 of file RectangleBoundsTests.cpp.
View newest version in sPHENIX GitHub at line 110 of file RectangleBoundsTests.cpp
References halfX, halfY, and Acts::RectangleBounds::vertices().
Acts::Test::BOOST_AUTO_TEST_CASE (PhiZ_Grid_test)
Various test for the Material in the case of a Cylindrical volume with a 2D grid.
Definition at line 111 of file MaterialGridHelperTests.cpp.
View newest version in sPHENIX GitHub at line 111 of file MaterialGridHelperTests.cpp
References Acts::detail::Grid< T, Axes >::atLocalBins(), Acts::BinUtility::binningData(), Acts::binPhi, Acts::binZ, CHECK_CLOSE_REL, Acts::Material::classificationNumbers(), Acts::closed, Acts::createGrid2D(), Acts::detail::Grid< T, Axes >::dimensions(), analysis::e, Acts::index1, Acts::index2, Acts::index3, Acts::detail::Grid< T, Axes >::localBinsFromLowerLeftEdge(), M_PI, Acts::mapMaterialPoints(), max, Acts::detail::Grid< T, Axes >::maxPosition(), min, Acts::detail::Grid< T, Axes >::minPosition(), Acts::detail::Grid< T, Axes >::numLocalBins(), Acts::open, and pos.
Acts::Test::BOOST_AUTO_TEST_CASE (AlignmentContextTests)
Unit test for creating compliant/non-compliant Surface object.
Definition at line 114 of file AlignmentContextTests.cpp.
View newest version in sPHENIX GitHub at line 114 of file AlignmentContextTests.cpp
References Acts::units::_cm, and Acts::units::_mm.
Acts::Test::BOOST_AUTO_TEST_CASE (TypeTraitsMember)
Definition at line 115 of file TypeTraitsTest.cpp.
View newest version in sPHENIX GitHub at line 115 of file TypeTraitsTest.cpp
Acts::Test::BOOST_AUTO_TEST_CASE (BoundaryCheckTriangleCovariance)
Definition at line 115 of file BoundaryCheckTests.cpp.
View newest version in sPHENIX GitHub at line 115 of file BoundaryCheckTests.cpp
References Acts::BoundaryCheck::isInside().
Acts::Test::BOOST_AUTO_TEST_CASE (intersect_rays)
Definition at line 117 of file BoundingBoxTest.cpp.
View newest version in sPHENIX GitHub at line 117 of file BoundingBoxTest.cpp
References p.
Acts::Test::BOOST_AUTO_TEST_CASE (InterpolatedMaterialMap_test)
Definition at line 118 of file InterpolatedMaterialMapTests.cpp.
View newest version in sPHENIX GitHub at line 118 of file InterpolatedMaterialMapTests.cpp
References CHECK_CLOSE_REL, Acts::InterpolatedMaterialMap< Mapper_t >::material(), and trafoGlobalToLocal().
Acts::Test::BOOST_AUTO_TEST_CASE (billoir_vertex_fitter_defaulttrack_test)
Unit test for FullBilloirVertexFitter with default input track type (= BoundParameters)
Definition at line 120 of file FullBilloirVertexFitterTests.cpp.
View newest version in sPHENIX GitHub at line 120 of file FullBilloirVertexFitterTests.cpp
References Acts::units::_mm, _T, Acts::IntegrationTest::bField, CHECK_CLOSE_ABS, d0Dist(), debugMode, Acts::FullBilloirVertexFitter< input_track_t, linearizer_t >::fit(), geoContext, magFieldContext, nEvents, nTracksDist(), phiDist(), Acts::Vertex< input_track_t >::position(), pTDist(), qDist(), resAngDist(), resIPDist(), resQoPDist(), Acts::Vertex< input_track_t >::setFullCovariance(), Acts::Vertex< input_track_t >::setFullPosition(), propagation_timing::stepper, thetaDist(), Acts::Vertex< input_track_t >::tracks(), vXYDist(), vZDist(), x, analysis::y, z, and z0Dist().
Acts::Test::BOOST_AUTO_TEST_CASE (shared_vector_helper_test)
Definition at line 122 of file HelpersTests.cpp.
View newest version in sPHENIX GitHub at line 122 of file HelpersTests.cpp
References Acts::unpack_shared_vector().
Acts::Test::BOOST_AUTO_TEST_CASE (ActionListTest_Distance)
Definition at line 123 of file ActionListTests.cpp.
View newest version in sPHENIX GitHub at line 123 of file ActionListTests.cpp
References Acts::units::_mm, Acts::detail::Extendable< extensions_t >::get(), Acts::detail::Extendable< actors_t...>::get(), and propagation_timing::stepper.
Acts::Test::BOOST_AUTO_TEST_CASE (DiamondBoundsAssignment)
Unit test for testing DiamondBounds assignment.
Test operator ==
Test assignment
Definition at line 123 of file DiamondBoundsTests.cpp.
View newest version in sPHENIX GitHub at line 123 of file DiamondBoundsTests.cpp
Acts::Test::BOOST_AUTO_TEST_CASE (multitrajectory_build)
Definition at line 124 of file MultiTrajectoryTests.cpp.
View newest version in sPHENIX GitHub at line 124 of file MultiTrajectoryTests.cpp
References Acts::MultiTrajectory< source_link_t >::addTrackState(), Acts::MultiTrajectory< source_link_t >::applyBackwards(), make_rand_trackstate(), p, t, and Acts::MultiTrajectory< source_link_t >::visitBackwards().
Acts::Test::BOOST_AUTO_TEST_CASE (ply_test)
Definition at line 124 of file GenericCuboidVolumeBoundsTests.cpp.
View newest version in sPHENIX GitHub at line 124 of file GenericCuboidVolumeBoundsTests.cpp
References Acts::GenericCuboidVolumeBounds::draw().
Acts::Test::BOOST_AUTO_TEST_CASE (eigen_stepper_state_test)
These tests are aiming to test whether the state setup is working properly.
Definition at line 125 of file StepperTests.cpp.
View newest version in sPHENIX GitHub at line 125 of file StepperTests.cpp
References Acts::backward, Acts::IntegrationTest::bField, charge, mfContext, charm_jet_coverage::mom, pos, Acts::tgContext, and Acts::VectorHelpers::time().
Acts::Test::BOOST_AUTO_TEST_CASE (RadialBoundsAssignment)
Unit test for testing RadialBounds assignment.
Test assignment
Definition at line 127 of file RadialBoundsTests.cpp.
View newest version in sPHENIX GitHub at line 127 of file RadialBoundsTests.cpp
References M_PI, maxRadius, and minRadius.
Acts::Test::BOOST_AUTO_TEST_CASE (CylinderVolumeBoundsAccess)
Definition at line 130 of file CylinderVolumeBoundsTests.cpp.
View newest version in sPHENIX GitHub at line 130 of file CylinderVolumeBoundsTests.cpp
References Acts::CylinderVolumeBounds::eAveragePhi, Acts::CylinderVolumeBounds::eHalfLengthZ, Acts::CylinderVolumeBounds::eHalfPhiSector, Acts::CylinderVolumeBounds::eMaxR, Acts::CylinderVolumeBounds::eMinR, Acts::CylinderVolumeBounds::get(), M_PI, and rmax().
Acts::Test::BOOST_AUTO_TEST_CASE (type_collector_test)
Definition at line 130 of file MPLTests.cpp.
View newest version in sPHENIX GitHub at line 130 of file MPLTests.cpp
References Acts::detail::has_action_type_v, Acts::detail::has_result_type_v, Acts::detail::type_collector_t, and value.
Acts::Test::BOOST_AUTO_TEST_CASE (PropagatorOptions_)
Definition at line 130 of file PropagatorTests.cpp.
View newest version in sPHENIX GitHub at line 130 of file PropagatorTests.cpp
References mfContext, eicpy.build::options, and Acts::tgContext.
Acts::Test::BOOST_AUTO_TEST_CASE (INFO_test)
unit test for INFO debug level
This test checks for the expected output when using the Acts::Logging::INFO debug level as threshold. It also tests
ACTS_LOCAL_LOGGER
Acts::getDefaultLogger
Definition at line 136 of file LoggerTests.cpp.
View newest version in sPHENIX GitHub at line 136 of file LoggerTests.cpp
References ACTS_DEBUG, ACTS_ERROR, ACTS_FATAL, ACTS_INFO, ACTS_LOCAL_LOGGER, ACTS_VERBOSE, ACTS_WARNING, getline, and INFO.
Acts::Test::BOOST_AUTO_TEST_CASE (TrapezoidBoundsAssignment)
Unit test for testing TrapezoidBounds assignment.
Test assignment
Definition at line 137 of file TrapezoidBoundsTests.cpp.
View newest version in sPHENIX GitHub at line 137 of file TrapezoidBoundsTests.cpp
References halfY.
Acts::Test::BOOST_AUTO_TEST_CASE (bfield_symmetry)
Definition at line 138 of file BFieldMapUtilsTests.cpp.
View newest version in sPHENIX GitHub at line 138 of file BFieldMapUtilsTests.cpp
References CHECK_CLOSE_REL, analysis::e, Acts::fieldMapperRZ(), Acts::fieldMapperXYZ(), and Acts::VectorHelpers::perp().
Acts::Test::BOOST_AUTO_TEST_CASE (ConeBoundsAssignment)
Definition at line 140 of file ConeBoundsTests.cpp.
View newest version in sPHENIX GitHub at line 140 of file ConeBoundsTests.cpp
References starlightConstants::alpha, and M_PI.
Acts::Test::BOOST_AUTO_TEST_CASE (JacobianCurvilinearToGlobalTest)
This tests the jacobian of local curvilinear -> global.
Definition at line 141 of file JacobianTests.cpp.
View newest version in sPHENIX GitHub at line 141 of file JacobianTests.cpp
References Acts::units::_GeV, Acts::units::_mm, charm_jet_coverage::mom, pos, and testJacobianToGlobal().
Acts::Test::BOOST_AUTO_TEST_CASE (bounding_box_creation)
Definition at line 143 of file GenericCuboidVolumeBoundsTests.cpp.
View newest version in sPHENIX GitHub at line 143 of file GenericCuboidVolumeBoundsTests.cpp
References Acts::GenericCuboidVolumeBounds::boundingBox(), CHECK_CLOSE_ABS, analysis::e, and M_PI.
Acts::Test::BOOST_AUTO_TEST_CASE (ActionListTest_TwoActions)
Definition at line 147 of file ActionListTests.cpp.
View newest version in sPHENIX GitHub at line 147 of file ActionListTests.cpp
References Acts::units::_mm, Acts::detail::Extendable< actors_t...>::get(), propagation_timing::stepper, and Acts::UnitConstants::u.
Acts::Test::BOOST_AUTO_TEST_CASE (BinningData_bins)
x/y/zData check the global position requests
check the local position requests
Definition at line 147 of file BinningDataTests.cpp.
View newest version in sPHENIX GitHub at line 147 of file BinningDataTests.cpp
References Acts::binPhi, Acts::binX, Acts::closed, delta, eta0Position(), etaData_eq, M_PI, nBins_binary, Acts::open, phi0Position(), phiData_eq, phiDelta, phiMin, phiPihPosition(), rData_eq, rphiPosition(), rphizPosition(), Acts::BinningData::search(), Acts::BinningData::searchGlobal(), Acts::BinningData::searchLocal(), valueMin, xData_add(), xData_arb, xData_eq, xData_mult, xyPosition(), xyzPosition(), yData_eq, and zData_eq.
Acts::Test::BOOST_AUTO_TEST_CASE (ObjectIntersectionTest)
test of the object intersection class
Definition at line 148 of file IntersectionTests.cpp.
View newest version in sPHENIX GitHub at line 148 of file IntersectionTests.cpp
References Acts::UnitConstants::u.
Acts::Test::BOOST_AUTO_TEST_CASE (open_axis)
Definition at line 148 of file AxesTests.cpp.
View newest version in sPHENIX GitHub at line 148 of file AxesTests.cpp
References a, b, and Acts::UnitConstants::u.
Acts::Test::BOOST_AUTO_TEST_CASE (Arguments)
Definition at line 148 of file FiniteStateMachineTests.cpp.
View newest version in sPHENIX GitHub at line 148 of file FiniteStateMachineTests.cpp
Acts::Test::BOOST_AUTO_TEST_CASE (LineSurface_assignment_test)
Unit test for testing LineSurface assignment.
Definition at line 150 of file LineSurfaceTests.cpp.
View newest version in sPHENIX GitHub at line 150 of file LineSurfaceTests.cpp
References transform.
Acts::Test::BOOST_AUTO_TEST_CASE (CylinderBoundsAssignment)
Unit test for testing CylinderBounds assignment.
Definition at line 150 of file CylinderBoundsTests.cpp.
View newest version in sPHENIX GitHub at line 150 of file CylinderBoundsTests.cpp
References Acts::CylinderBounds::eR, and Acts::CylinderBounds::get().
Acts::Test::BOOST_AUTO_TEST_CASE (VolumeMaterialMapper_comparison_tests)
Test case for comparison between the mapped material and the associated material by propagation.
Definition at line 152 of file VolumeMaterialMapperTests.cpp.
View newest version in sPHENIX GitHub at line 152 of file VolumeMaterialMapperTests.cpp
References Acts::units::_GeV, Acts::units::_m, CHECK_CLOSE_REL, Acts::createGrid(), Acts::PropagatorOptions< action_list_t, aborter_list_t >::debug, Acts::DebugOutputActor::this_result::debugString, analysis::e, Acts::mapMaterialPoints(), material, Acts::PropagatorOptions< action_list_t, aborter_list_t >::maxSteps, Acts::PropagatorOptions< action_list_t, aborter_list_t >::maxStepSize, charm_jet_coverage::mom, pos, Acts::CuboidVolumeBuilder::VolumeConfig::position, Acts::CuboidVolumeBuilder::Config::position, Acts::Propagator< stepper_t, navigator_t >::propagate(), Acts::TrackingGeometryBuilder::trackingGeometry(), Acts::CuboidVolumeBuilder::trackingVolume(), and Acts::TrackingGeometryBuilder::Config::trackingVolumeBuilders.
Acts::Test::BOOST_AUTO_TEST_CASE (TypeTraitsNestedType)
Definition at line 155 of file TypeTraitsTest.cpp.
View newest version in sPHENIX GitHub at line 155 of file TypeTraitsTest.cpp
Acts::Test::BOOST_AUTO_TEST_CASE (linearized_track_factory_straightline_test)
Unit test for HelicalTrackLinearizer.
Definition at line 155 of file LinearizedTrackFactoryTests.cpp.
View newest version in sPHENIX GitHub at line 155 of file LinearizedTrackFactoryTests.cpp
References Acts::LinearizedTrack::constantTerm, Acts::LinearizedTrack::covarianceAtPCA, d0Dist(), geoContext, Acts::LinearizedTrack::linearizationPoint, magFieldContext, Acts::LinearizedTrack::momentumJacobian, Dataset::parameters, Acts::LinearizedTrack::parametersAtPCA, phiDist(), Acts::LinearizedTrack::positionJacobian, pTDist(), qDist(), resAngDist(), resIPDist(), resQoPDist(), propagation_timing::stepper, thetaDist(), vXYDist(), vZDist(), x, analysis::y, z, and z0Dist().
Acts::Test::BOOST_AUTO_TEST_CASE (JacobianCylinderToGlobalTest)
This tests the jacobian of local cylinder -> global.
Definition at line 159 of file JacobianTests.cpp.
View newest version in sPHENIX GitHub at line 159 of file JacobianTests.cpp
References Acts::units::_GeV, Acts::units::_mm, Acts::IntegrationTest::createCylindricTransform(), cSurface, testJacobianToGlobal(), and Acts::tgContext.
Acts::Test::BOOST_AUTO_TEST_CASE (VisualizationConstruction)
Definition at line 160 of file VisualizationTests.cpp.
View newest version in sPHENIX GitHub at line 160 of file VisualizationTests.cpp
Acts::Test::BOOST_AUTO_TEST_CASE (time_helper_test)
Definition at line 161 of file HelpersTests.cpp.
View newest version in sPHENIX GitHub at line 161 of file HelpersTests.cpp
References Acts::eT, t, t1, t2, and Acts::VectorHelpers::time().
Acts::Test::BOOST_AUTO_TEST_CASE (visit_apply_abort)
Definition at line 162 of file MultiTrajectoryTests.cpp.
View newest version in sPHENIX GitHub at line 162 of file MultiTrajectoryTests.cpp
References Acts::MultiTrajectory< source_link_t >::addTrackState(), Acts::MultiTrajectory< source_link_t >::applyBackwards(), make_rand_trackstate(), n, t, and Acts::UnitConstants::u.
Acts::Test::BOOST_AUTO_TEST_CASE (CylinderSurfacePolyhedrons)
Unit tests for Cylinder Surfaces.
The full cone on one side
The full cone on one side
The full cone on one side
Definition at line 167 of file PolyhedronSurfacesTests.cpp.
View newest version in sPHENIX GitHub at line 167 of file PolyhedronSurfacesTests.cpp
References Acts::units::_mm, Acts::binR, Acts::binX, Acts::binY, Acts::binZ, CHECK_CLOSE_ABS, cos(), analysis::e, r, testModes, Acts::tgContext, and transform.
Acts::Test::BOOST_AUTO_TEST_CASE (DEBUG_test)
unit test for DEBUG debug level
This test checks for the expected output when using the Acts::Logging::DEBUG debug level as threshold. It also tests
ACTS_LOCAL_LOGGER
Acts::getDefaultLogger
Definition at line 168 of file LoggerTests.cpp.
View newest version in sPHENIX GitHub at line 168 of file LoggerTests.cpp
References ACTS_DEBUG, ACTS_ERROR, ACTS_FATAL, ACTS_INFO, ACTS_LOCAL_LOGGER, ACTS_VERBOSE, ACTS_WARNING, DEBUG, and getline.
Acts::Test::BOOST_AUTO_TEST_CASE (DiscTrapezoidBoundsAssignment)
Unit test for testing DiscTrapezoidBounds assignment.
Test assignment
Definition at line 169 of file DiscTrapezoidBoundsTests.cpp.
View newest version in sPHENIX GitHub at line 169 of file DiscTrapezoidBoundsTests.cpp
Acts::Test::BOOST_AUTO_TEST_CASE (CutoutCylinderVolumeBoundsBoundingBox)
Definition at line 170 of file CutoutCylinderVolumeBoundsTests.cpp.
View newest version in sPHENIX GitHub at line 170 of file CutoutCylinderVolumeBoundsTests.cpp
References Acts::CutoutCylinderVolumeBounds::boundingBox(), CHECK_CLOSE_ABS, Acts::CutoutCylinderVolumeBounds::decomposeToSurfaces(), analysis::e, Acts::Polyhedron::merge(), name, tgContext, and nlohmann::to_string().
Acts::Test::BOOST_AUTO_TEST_CASE (ConeIntersectionTest)
This tests the interseciton with cylinders and looks for valid, non-valid, solutions
Definition at line 170 of file SurfaceIntersectionTests.cpp.
View newest version in sPHENIX GitHub at line 170 of file SurfaceIntersectionTests.cpp
References starlightConstants::alpha, Acts::aTransform, CHECK_CLOSE_ABS, M_PI, Acts::s_onSurfaceTolerance, Acts::tgContext, and transform.
Acts::Test::BOOST_AUTO_TEST_CASE (comb_kalman_filter_zero_field)
Unit test for CombinatorialKalmanFilter with measurements along the x-axis.
Definition at line 170 of file CombinatorialKalmanFilterTests.cpp.
View newest version in sPHENIX GitHub at line 170 of file CombinatorialKalmanFilterTests.cpp
References Acts::units::_GeV, Acts::units::_m, Acts::units::_mm, Acts::units::_um, Acts::PropagatorOptions< action_list_t, aborter_list_t >::actionList, Acts::IntegrationTest::bField, calContext, cGeometry, cos(), Acts::PropagatorOptions< action_list_t, aborter_list_t >::debug, debugMode, Acts::Test::MeasurementCreator::detectorResolution, Acts::eLOC_0, Acts::eLOC_1, eps, Acts::CombinatorialKalmanFilter< propagator_t, updater_t, smoother_t, source_link_selector_t, branch_stopper_t, calibrator_t, input_converter_t, output_converter_t >::findTracks(), gauss(), generator(), Acts::getDefaultLogger(), eic::m, mfContext, pos, Acts::SingleCurvilinearTrackParameters< ChargePolicy >::referenceSurface(), Acts::Navigator::resolveMaterial, Acts::Navigator::resolvePassive, Acts::Navigator::resolveSensitive, Acts::tgContext, transform, and Acts::Logging::VERBOSE.
Acts::Test::BOOST_AUTO_TEST_CASE (TrackingGeometry_testVisitSurfaces)
Definition at line 172 of file TrackingGeometryClosureTests.cpp.
View newest version in sPHENIX GitHub at line 172 of file TrackingGeometryClosureTests.cpp
References Acts::tGeometry, and Acts::UnitConstants::u.
Acts::Test::BOOST_AUTO_TEST_CASE (PlyOutputTest)
Definition at line 173 of file VisualizationTests.cpp.
View newest version in sPHENIX GitHub at line 173 of file VisualizationTests.cpp
Acts::Test::BOOST_AUTO_TEST_CASE (closed_axis)
Definition at line 173 of file AxesTests.cpp.
View newest version in sPHENIX GitHub at line 173 of file AxesTests.cpp
References a, b, and Acts::UnitConstants::u.
Acts::Test::BOOST_AUTO_TEST_CASE (EllipseBoundsAssignment)
Unit test for testing EllipseBounds assignment.
Test operator ==
Test assignment
Definition at line 175 of file EllipseBoundsTests.cpp.
View newest version in sPHENIX GitHub at line 175 of file EllipseBoundsTests.cpp
References M_PI.
Acts::Test::BOOST_AUTO_TEST_CASE (track_density_finder_random_test)
Unit test for TrackDensityVertexFinder using same configuration and values as VertexSeedFinderTestAlg in Athena implementation.
Definition at line 176 of file TrackDensityVertexFinderTests.cpp.
View newest version in sPHENIX GitHub at line 176 of file TrackDensityVertexFinderTests.cpp
References Acts::units::_mm, charge, CHECK_CLOSE_ABS, cos(), Acts::VectorHelpers::eta(), etaDist(), Acts::eZ, Acts::TrackDensityVertexFinder< vfitter_t, track_density_t >::find(), geoContext, magFieldContext, charm_jet_coverage::mom, phi, phiDist(), pos, pTDist(), xdist(), ydist(), z1dist(), z2dist(), and zVertexPos.
Acts::Test::BOOST_AUTO_TEST_CASE (eigen_stepper_test)
These tests are aiming to test the functions of the EigenStepper The numerical correctness of the stepper is tested in the integration tests
Repeat with surface related methods
Definition at line 177 of file StepperTests.cpp.
View newest version in sPHENIX GitHub at line 177 of file StepperTests.cpp
References Acts::ConstrainedStep::actor, Acts::backward, Acts::IntegrationTest::bField, Acts::detail::boundState(), Acts::EigenStepper< bfield_t, extensionlist_t, auctioneer_t >::boundState(), charge, Acts::SingleTrackParameters< ChargePolicy >::charge(), Acts::EigenStepper< bfield_t, extensionlist_t, auctioneer_t >::charge(), CHECK_CLOSE_ABS, CHECK_CLOSE_COVARIANCE, Acts::EigenStepper< bfield_t, extensionlist_t, auctioneer_t >::covarianceTransport(), Acts::EigenStepper< bfield_t, extensionlist_t, auctioneer_t >::curvilinearState(), Acts::EigenStepper< bfield_t, extensionlist_t, auctioneer_t >::direction(), analysis::e, Acts::ConstantBField::getField(), Acts::EigenStepper< bfield_t, extensionlist_t, auctioneer_t >::getField(), analysis::h, h2, mfContext, charm_jet_coverage::mom, Acts::SingleTrackParameters< ChargePolicy >::momentum(), Acts::EigenStepper< bfield_t, extensionlist_t, auctioneer_t >::momentum(), Acts::EigenStepper< bfield_t, extensionlist_t, auctioneer_t >::outputStepSize(), Acts::PrimitivesVisualization::plane, pos, Acts::SingleTrackParameters< ChargePolicy >::position(), Acts::EigenStepper< bfield_t, extensionlist_t, auctioneer_t >::position(), Acts::UnitConstants::ps, Acts::EigenStepper< bfield_t, extensionlist_t, auctioneer_t >::releaseStepSize(), Acts::EigenStepper< bfield_t, extensionlist_t, auctioneer_t >::setStepSize(), Acts::EigenStepper< bfield_t, extensionlist_t, auctioneer_t >::step(), Acts::tgContext, Acts::SingleTrackParameters< ChargePolicy >::time(), Acts::EigenStepper< bfield_t, extensionlist_t, auctioneer_t >::time(), Acts::VectorHelpers::time(), Acts::EigenStepper< bfield_t, extensionlist_t, auctioneer_t >::update(), Acts::EigenStepper< bfield_t, extensionlist_t, auctioneer_t >::updateStepSize(), and Acts::EigenStepper< bfield_t, extensionlist_t, auctioneer_t >::updateSurfaceStatus().
Acts::Test::BOOST_AUTO_TEST_CASE (has_duplicates_test)
Definition at line 177 of file MPLTests.cpp.
View newest version in sPHENIX GitHub at line 177 of file MPLTests.cpp
References Acts::detail::has_duplicates_v.
Acts::Test::BOOST_AUTO_TEST_CASE (JacobianDiscToGlobalTest)
This tests the jacobian of local disc -> global.
Definition at line 178 of file JacobianTests.cpp.
View newest version in sPHENIX GitHub at line 178 of file JacobianTests.cpp
References Acts::units::_GeV, Acts::units::_mm, Acts::IntegrationTest::createPlanarTransform(), testJacobianToGlobal(), and Acts::tgContext.
Acts::Test::BOOST_AUTO_TEST_CASE (impactpoint_estimator_compatibility_test)
Unit test for ImpactPointEstimator compatibility estimator.
Definition at line 180 of file ImpactPointEstimatorTests.cpp.
View newest version in sPHENIX GitHub at line 180 of file ImpactPointEstimatorTests.cpp
References Acts::units::_T, Acts::IntegrationTest::bField, Acts::ImpactPointEstimator< input_track_t, propagator_t, propagator_options_t >::calculate3dDistance(), d0Dist(), debugMode, Acts::ImpactPointEstimator< input_track_t, propagator_t, propagator_options_t >::estimate3DImpactParameters(), geoContext, Acts::ImpactPointEstimator< input_track_t, propagator_t, propagator_options_t >::get3dVertexCompatibility(), magFieldContext, phiDist(), pTDist(), qDist(), analysis::res, resAngDist(), resIPDist(), resQoPDist(), propagation_timing::stepper, thetaDist(), and z0Dist().
Acts::Test::BOOST_AUTO_TEST_CASE (EqualityOperators)
Test equality operator
Test assignment
Test equality of assigned to original
Test equality operator
Test assignment
Test equality of assigned to original
Test equality operator
Test assignment
Test equality of assigned to original
Test equality operator
Test assignment
Test equality of assigned to original
Test equality operator
Test assignment
Test equality of assigned to original
Test equality operator
Test assignment
Test equality of assigned to original
Test equality operator
Test assignment
Test equality of assigned to original
Test equality operator
Test assignment
Test equality of assigned to original
Test equality operator
Test assignment
Test equality of assigned to original
Definition at line 183 of file ConeSurfaceTests.cpp.
View newest version in sPHENIX GitHub at line 183 of file ConeSurfaceTests.cpp
References starlightConstants::alpha, and M_PI.
Acts::Test::BOOST_AUTO_TEST_CASE (Cubic_Grid_test)
Various test for the Material in the case of a Cuboid volume.
Definition at line 188 of file MaterialGridHelperTests.cpp.
View newest version in sPHENIX GitHub at line 188 of file MaterialGridHelperTests.cpp
References Acts::detail::Grid< T, Axes >::atLocalBins(), Acts::BinUtility::binningData(), Acts::binX, Acts::binY, Acts::binZ, CHECK_CLOSE_REL, Acts::Material::classificationNumbers(), Acts::createGrid3D(), Acts::detail::Grid< T, Axes >::dimensions(), analysis::e, Acts::index1, Acts::index2, Acts::index3, Acts::detail::Grid< T, Axes >::localBinsFromLowerLeftEdge(), Acts::mapMaterialPoints(), max, Acts::detail::Grid< T, Axes >::maxPosition(), min, Acts::detail::Grid< T, Axes >::minPosition(), Acts::detail::Grid< T, Axes >::numLocalBins(), Acts::open, and pos.
Acts::Test::BOOST_AUTO_TEST_CASE (any_of_test)
Definition at line 191 of file MPLTests.cpp.
View newest version in sPHENIX GitHub at line 191 of file MPLTests.cpp
References Acts::detail::any_of_v.
Acts::Test::BOOST_AUTO_TEST_CASE (zscan_finder_usertrack_test)
Unit test for ZScanVertexFinder with user-defined input track type.
Definition at line 191 of file ZScanVertexFinderTests.cpp.
View newest version in sPHENIX GitHub at line 191 of file ZScanVertexFinderTests.cpp
References Acts::units::_mm, _T, Acts::IntegrationTest::bField, CHECK_CLOSE_ABS, d0Dist(), Acts::eZ, geoContext, magFieldContext, phiDist(), pTDist(), qDist(), analysis::res, resAngDist(), resIPDist(), resQoPDist(), propagation_timing::stepper, thetaDist(), vXYDist(), vZDist(), x, analysis::y, z, and z0Dist().
Acts::Test::BOOST_AUTO_TEST_CASE (trackstate_add_bitmask)
Definition at line 195 of file MultiTrajectoryTests.cpp.
View newest version in sPHENIX GitHub at line 195 of file MultiTrajectoryTests.cpp
References ACTS_CHECK_BIT, Acts::MultiTrajectory< source_link_t >::addTrackState(), Acts::TrackStatePropMask::All, Acts::TrackStatePropMask::Calibrated, Acts::TrackStatePropMask::Filtered, Acts::MultiTrajectory< source_link_t >::getTrackState(), Acts::TrackStatePropMask::None, Acts::TrackStatePropMask::Predicted, Acts::TrackStatePropMask::Smoothed, t, and Acts::TrackStatePropMask::Uncalibrated.
Acts::Test::BOOST_AUTO_TEST_CASE (neighborhood)
Definition at line 198 of file AxesTests.cpp.
View newest version in sPHENIX GitHub at line 198 of file AxesTests.cpp
References Acts::UnitConstants::u.
Acts::Test::BOOST_AUTO_TEST_CASE (JacobianPlaneToGlobalTest)
This tests the jacobian of local plane -> global.
Definition at line 198 of file JacobianTests.cpp.
View newest version in sPHENIX GitHub at line 198 of file JacobianTests.cpp
References Acts::units::_GeV, Acts::units::_mm, testJacobianToGlobal(), and Acts::tgContext.
Acts::Test::BOOST_AUTO_TEST_CASE (DiscSurface_assignment_test)
Unit test for testing DiscSurface assignment and equality.
Definition at line 198 of file DiscSurfaceTests.cpp.
View newest version in sPHENIX GitHub at line 198 of file DiscSurfaceTests.cpp
References M_PI.
Acts::Test::BOOST_AUTO_TEST_CASE (VERBOSE_test)
unit test for VERBOSE debug level
This test checks for the expected output when using the Acts::Logging::VERBOSE debug level as threshold. It also tests
ACTS_LOCAL_LOGGER
Acts::getDefaultLogger
Definition at line 201 of file LoggerTests.cpp.
View newest version in sPHENIX GitHub at line 201 of file LoggerTests.cpp
References ACTS_DEBUG, ACTS_ERROR, ACTS_FATAL, ACTS_INFO, ACTS_LOCAL_LOGGER, ACTS_VERBOSE, ACTS_WARNING, getline, and VERBOSE.
Acts::Test::BOOST_AUTO_TEST_CASE (AbortListSignatureTest)
Definition at line 211 of file AbortListTests.cpp.
View newest version in sPHENIX GitHub at line 211 of file AbortListTests.cpp
References signature_check.
Acts::Test::BOOST_AUTO_TEST_CASE (position_helper_test)
Definition at line 212 of file HelpersTests.cpp.
View newest version in sPHENIX GitHub at line 212 of file HelpersTests.cpp
References pos, and Acts::VectorHelpers::position().
Acts::Test::BOOST_AUTO_TEST_CASE (BinningData_inside_outside)
Definition at line 214 of file BinningDataTests.cpp.
View newest version in sPHENIX GitHub at line 214 of file BinningDataTests.cpp
References Acts::binPhi, Acts::binX, Acts::closed, delta, eta0Position(), etaData_eq, Acts::BinningData::inside(), nBins_binary, Acts::open, phi0Position(), phiData_eq, phiDelta, phiMin, phiPihPosition(), rphizPosition(), valueMin, xData_add(), xData_arb, xData_eq, xData_mult, xyPosition(), xyzPosition(), xyzPositionOutside(), yData_eq, and zData_eq.
Acts::Test::BOOST_AUTO_TEST_CASE (JacobianPerigeeToGlobalTest)
This tests the jacobian of local perigee -> global.
Definition at line 220 of file JacobianTests.cpp.
View newest version in sPHENIX GitHub at line 220 of file JacobianTests.cpp
References Acts::units::_GeV, Acts::units::_mm, testJacobianToGlobal(), and Acts::tgContext.
Acts::Test::BOOST_AUTO_TEST_CASE (CylinderVolumeBoundsBoundingBox)
Definition at line 221 of file CylinderVolumeBoundsTests.cpp.
View newest version in sPHENIX GitHub at line 221 of file CylinderVolumeBoundsTests.cpp
References Acts::CylinderVolumeBounds::boundingBox(), CHECK_CLOSE_ABS, cos(), Acts::CylinderVolumeBounds::decomposeToSurfaces(), analysis::e, M_PI, Acts::Polyhedron::merge(), name, tgContext, nlohmann::to_string(), and Acts::Test::ObjTestWriter::writeObj().
Acts::Test::BOOST_AUTO_TEST_CASE (PlanarIntersectionTest)
This tests the interseciton with planar surfaces (plane, disk) as those share the same PlanarHelper methods, only one test is sufficient
it looks for valid, non-valid, solutions
Forward interseciton test
Definition at line 225 of file SurfaceIntersectionTests.cpp.
View newest version in sPHENIX GitHub at line 225 of file SurfaceIntersectionTests.cpp
References Acts::units::_cm, Acts::units::_m, Acts::units::_mm, kdfinder::abs(), aPlane, Acts::aTransform, halfX, halfY, Acts::s_onSurfaceTolerance, Acts::tgContext, and transform.
Acts::Test::BOOST_AUTO_TEST_CASE (are_sorted_helper_tests)
Unit test for Acts::anonymous_namespace{ParameterSet.h}::are_sorted helper.
The test checks for correct behavior in the following cases (always using int as value type):
test: ordered strictly ascending, input: ordered strictly ascending
test: ordered strictly ascending, input: unordered
test: ordered strictly ascending, input: ordered weakly ascending
test: ordered weakly ascending, input: ordered strictly ascending
test: ordered weakly ascending, input: unordered
test: ordered weakly ascending, input: ordered weakly ascending
test: ordered strictly descending, input: ordered strictly descending
test: ordered strictly descending, input: unordered
test: ordered strictly descending, input: ordered weakly descending
test: ordered weakly descending, input: ordered strictly descending
test: ordered weakly descending, input: unordered
test: ordered weakly descending, input: ordered weakly descending
Definition at line 226 of file MPLTests.cpp.
View newest version in sPHENIX GitHub at line 226 of file MPLTests.cpp
References value.
Acts::Test::BOOST_AUTO_TEST_CASE (TypeTraitsConcepts)
Definition at line 226 of file TypeTraitsTest.cpp.
View newest version in sPHENIX GitHub at line 226 of file TypeTraitsTest.cpp
Acts::Test::BOOST_AUTO_TEST_CASE (Navigator_methods)
Definition at line 229 of file NavigatorTests.cpp.
View newest version in sPHENIX GitHub at line 229 of file NavigatorTests.cpp
References CHECK_CLOSE_ABS, Acts::IntegrationTest::debug, momentum, navigator, Acts::VectorHelpers::perp(), Acts::VectorHelpers::position(), Acts::Navigator::resolveMaterial, Acts::Navigator::resolvePassive, Acts::Navigator::resolveSensitive, Acts::s_onSurfaceTolerance, Acts::Navigator::status(), step(), propagation_timing::stepper, Acts::Navigator::target(), Acts::tGeometry, Acts::toString(), Acts::Navigator::trackingGeometry, and Acts::UnitConstants::u.
Acts::Test::BOOST_AUTO_TEST_CASE (InternalTransitions)
Definition at line 234 of file FiniteStateMachineTests.cpp.
View newest version in sPHENIX GitHub at line 234 of file FiniteStateMachineTests.cpp
References Acts::FiniteStateMachine< Derived, States >::is().
Acts::Test::BOOST_AUTO_TEST_CASE (JacobianStrawToGlobalTest)
This tests the jacobian of local straw -> global.
Definition at line 237 of file JacobianTests.cpp.
View newest version in sPHENIX GitHub at line 237 of file JacobianTests.cpp
References Acts::units::_GeV, Acts::units::_mm, Acts::IntegrationTest::createCylindricTransform(), testJacobianToGlobal(), and Acts::tgContext.
Acts::Test::BOOST_AUTO_TEST_CASE (SurfaceArray_singleElement)
Definition at line 243 of file SurfaceArrayTests.cpp.
View newest version in sPHENIX GitHub at line 243 of file SurfaceArrayTests.cpp
References analysis::h, and Acts::UnitConstants::u.
Acts::Test::BOOST_AUTO_TEST_CASE (parset_consistency_tests)
Unit test for checking consistency of ParameterSet class.
The following functions are tested to yield the expected result/behavior:
ParameterSet::size
ParameterSet::contains
ParameterSet::getParameter
ParameterSet::getParameters
ParameterSet::getCovariance
ParameterSet::setCovariance
ParameterSet::setParameter
ParameterSet::getUncertainty
Definition at line 243 of file ParameterSetTests.cpp.
View newest version in sPHENIX GitHub at line 243 of file ParameterSetTests.cpp
References Acts::ParameterSet< params >::contains(), Acts::eBoundLoc0, Acts::eBoundLoc1, Acts::eBoundPhi, Acts::eBoundQOverP, Acts::eBoundTheta, Acts::eBoundTime, Acts::ParameterSet< params >::getCovariance(), Acts::ParameterSet< params >::getParameter(), Acts::ParameterSet< params >::getParameters(), Acts::ParameterSet< params >::getUncertainty(), M_PI, phi, Acts::ParameterSet< params >::setCovariance(), Acts::ParameterSet< params >::setParameter(), and Acts::ParameterSet< params >::size().
Acts::Test::BOOST_AUTO_TEST_CASE (adaptive_multi_vertex_finder_usertype_test)
Definition at line 247 of file AdaptiveMultiVertexFinderTests.cpp.
View newest version in sPHENIX GitHub at line 247 of file AdaptiveMultiVertexFinderTests.cpp
References Acts::units::_mm, _T, bField, CHECK_CLOSE_ABS, debugMode, geoContext, getAthenaTracks(), magFieldContext, Acts::Vertex< input_track_t >::setCovariance(), Acts::Vertex< input_track_t >::setPosition(), propagation_timing::stepper, Acts::VertexingOptions< input_track_t >::vertexConstraint, and vtx().
Acts::Test::BOOST_AUTO_TEST_CASE (billoir_vertex_fitter_usertrack_test)
Unit test for FullBilloirVertexFitter with user-defined InputTrack type.
Definition at line 249 of file FullBilloirVertexFitterTests.cpp.
View newest version in sPHENIX GitHub at line 249 of file FullBilloirVertexFitterTests.cpp
References Acts::units::_mm, _T, Acts::IntegrationTest::bField, CHECK_CLOSE_ABS, d0Dist(), debugMode, Acts::FullBilloirVertexFitter< input_track_t, linearizer_t >::fit(), geoContext, magFieldContext, nEvents, nTracksDist(), phiDist(), Acts::Vertex< input_track_t >::position(), pTDist(), qDist(), resAngDist(), resIPDist(), resQoPDist(), Acts::Vertex< input_track_t >::setFullCovariance(), Acts::Vertex< input_track_t >::setFullPosition(), propagation_timing::stepper, thetaDist(), Acts::Vertex< input_track_t >::tracks(), vXYDist(), vZDist(), x, analysis::y, z, and z0Dist().
Acts::Test::BOOST_AUTO_TEST_CASE (DiscSurfacePolyhedrons)
Unit tests for Disc Surfaces.
Definition at line 251 of file PolyhedronSurfacesTests.cpp.
View newest version in sPHENIX GitHub at line 251 of file PolyhedronSurfacesTests.cpp
References Acts::units::_mm, Acts::binR, Acts::binX, Acts::binY, Acts::binZ, CHECK_CLOSE_ABS, cos(), analysis::e, maxPhi, maxRadius, minPhi, minRadius, offset, testModes, Acts::tgContext, and transform.
Acts::Test::BOOST_AUTO_TEST_CASE (track_density_finder_usertrack_test)
Unit test for TrackDensityVertexFinder with user-defined input track type with same values as in other tests.
Definition at line 252 of file TrackDensityVertexFinderTests.cpp.
View newest version in sPHENIX GitHub at line 252 of file TrackDensityVertexFinderTests.cpp
References Acts::units::_MeV, Acts::units::_mm, CHECK_CLOSE_ABS, Acts::eX, Acts::eY, Acts::eZ, Acts::TrackDensityVertexFinder< vfitter_t, track_density_t >::find(), geoContext, magFieldContext, analysis::res, Acts::Vertex< input_track_t >::setCovariance(), and Acts::VertexingOptions< input_track_t >::vertexConstraint.
Acts::Test::BOOST_AUTO_TEST_CASE (test_matrix_dimension_switch)
Definition at line 253 of file HelpersTests.cpp.
View newest version in sPHENIX GitHub at line 253 of file HelpersTests.cpp
Acts::Test::BOOST_AUTO_TEST_CASE (CopyBehaviour)
Definition at line 254 of file ResultTests.cpp.
View newest version in sPHENIX GitHub at line 254 of file ResultTests.cpp
References make_nocopy(), n, Acts::Test::NoCopy::num, analysis::res, and value.
Acts::Test::BOOST_AUTO_TEST_CASE (kalman_fitter_zero_field)
Unit test for Kalman fitter with measurements along the x-axis.
Definition at line 256 of file KalmanFitterTests.cpp.
View newest version in sPHENIX GitHub at line 256 of file KalmanFitterTests.cpp
References Acts::units::_GeV, Acts::units::_m, Acts::units::_um, Acts::PropagatorOptions< action_list_t, aborter_list_t >::actionList, Acts::KalmanFitterOptions< outlier_finder_t >::backwardFiltering, Acts::IntegrationTest::bField, calContext, cGeometry, CHECK_CLOSE_ABS, CHECK_CLOSE_REL, checkCloseRel(), Acts::PropagatorOptions< action_list_t, aborter_list_t >::debug, debugMode, Acts::Test::MeasurementCreator::detectorResolution, analysis::e, Acts::eLOC_0, Acts::eLOC_1, Acts::KalmanFitter< propagator_t, updater_t, smoother_t, outlier_finder_t, calibrator_t, input_converter_t, output_converter_t >::fit(), gauss(), generator(), Acts::getDefaultLogger(), eic::m, Acts::Test::MinimalOutlierFinder::measurementSignificanceCutoff, mfContext, Acts::OutlierFlag, Acts::SingleCurvilinearTrackParameters< ChargePolicy >::referenceSurface(), Acts::Navigator::resolveMaterial, Acts::Navigator::resolvePassive, Acts::Navigator::resolveSensitive, Acts::tgContext, transform, Acts::UnitConstants::u, and Acts::Logging::VERBOSE.
Acts::Test::BOOST_AUTO_TEST_CASE (BinningData_open_close)
Definition at line 257 of file BinningDataTests.cpp.
View newest version in sPHENIX GitHub at line 257 of file BinningDataTests.cpp
References Acts::binPhi, Acts::BinningData::bins(), Acts::binX, Acts::closed, Acts::BinningData::decrement(), delta, Acts::BinningData::increment(), nBins_binary, Acts::open, phiData_arb, phiData_eq, phiDelta, phiMin, Acts::BinningData::search(), Acts::BinningData::searchGlobal(), valueMin, xData_arb, xData_eq, xyzPositionOutside(), yData_arb, yData_eq, and zData_eq.
Acts::Test::BOOST_AUTO_TEST_CASE (are_within_helper_tests)
Unit test for Acts::anonymous_namespace{ParameterSet.h}::are_within helper.
The test checks for correct behavior in the following cases (always using int as value type):
all values within (MIN,MAX)
all values within [MIN,MAX)
one value < MIN
multiple values < MIN
one value > MAX
multiple values > Max
one value == MAX
contains values < MIN and >= MAX
Definition at line 262 of file MPLTests.cpp.
View newest version in sPHENIX GitHub at line 262 of file MPLTests.cpp
References value.
Acts::Test::BOOST_AUTO_TEST_CASE (Cylindrical_Grid_test)
Various test for the Material in the case of a Cylindrical volume.
Definition at line 268 of file MaterialGridHelperTests.cpp.
View newest version in sPHENIX GitHub at line 268 of file MaterialGridHelperTests.cpp
References Acts::detail::Grid< T, Axes >::atLocalBins(), Acts::BinUtility::binningData(), Acts::binPhi, Acts::binR, Acts::binZ, CHECK_CLOSE_REL, Acts::Material::classificationNumbers(), Acts::closed, Acts::createGrid3D(), Acts::detail::Grid< T, Axes >::dimensions(), analysis::e, Acts::index1, Acts::index2, Acts::index3, Acts::detail::Grid< T, Axes >::localBinsFromLowerLeftEdge(), M_PI, Acts::mapMaterialPoints(), max, Acts::detail::Grid< T, Axes >::maxPosition(), min, Acts::detail::Grid< T, Axes >::minPosition(), Acts::detail::Grid< T, Axes >::numLocalBins(), Acts::open, and pos.
Acts::Test::BOOST_AUTO_TEST_CASE (at_index_helper_tests)
Unit test for Acts::details::at_index helper.
Definition at line 277 of file MPLTests.cpp.
View newest version in sPHENIX GitHub at line 277 of file MPLTests.cpp
References value.
Acts::Test::BOOST_AUTO_TEST_CASE (grid_test_3d_equidistant)
Definition at line 279 of file GridTests.cpp.
View newest version in sPHENIX GitHub at line 279 of file GridTests.cpp
References a, b, c, g(), Acts::detail::Grid< T, Axes >::globalBinFromLocalBins(), Acts::detail::Grid< T, Axes >::globalBinFromPosition(), Acts::detail::Grid< T, Axes >::localBinsFromGlobalBin(), Acts::detail::Grid< T, Axes >::numLocalBins(), Acts::detail::Grid< T, Axes >::size(), and Acts::UnitConstants::u.
Acts::Test::BOOST_AUTO_TEST_CASE (VoidResult)
Definition at line 291 of file ResultTests.cpp.
View newest version in sPHENIX GitHub at line 291 of file ResultTests.cpp
References analysis::res, and void_res_func().
Acts::Test::BOOST_AUTO_TEST_CASE (ObjOutputTest)
Definition at line 292 of file VisualizationTests.cpp.
View newest version in sPHENIX GitHub at line 292 of file VisualizationTests.cpp
Acts::Test::BOOST_AUTO_TEST_CASE (create_Clusters2)
This test tests the clusterization of cells which belong to the same cluster for 8-cell/4-cell merging, digital/analogue readout and with a possible energy cut applied and a bigger grid than in create_Clusters1
Definition at line 294 of file ClusterizationTests.cpp.
View newest version in sPHENIX GitHub at line 294 of file ClusterizationTests.cpp
References a, b, CHECK_CLOSE_REL, delta, analysis::e, and Acts::UnitConstants::u.
Acts::Test::BOOST_AUTO_TEST_CASE (trackstate_proxy_cross_talk)
Definition at line 298 of file MultiTrajectoryTests.cpp.
View newest version in sPHENIX GitHub at line 298 of file MultiTrajectoryTests.cpp
References Acts::MultiTrajectory< source_link_t >::addTrackState(), Acts::UnitConstants::fm, Acts::MultiTrajectory< source_link_t >::getTrackState(), make_trackstate(), t, Acts::UnitConstants::u, and v.
Acts::Test::BOOST_AUTO_TEST_CASE (iterative_finder_test_user_track_type)
Unit test for IterativeVertexFinder for user defined InputTrack track type.
Definition at line 302 of file IterativeVertexFinderTests.cpp.
View newest version in sPHENIX GitHub at line 302 of file IterativeVertexFinderTests.cpp
References Acts::units::_mm, _T, kdfinder::abs(), Acts::IntegrationTest::bField, CHECK_CLOSE_ABS, d0Dist(), Acts::IntegrationTest::debug, Acts::eX, Acts::eY, Acts::eZ, geoContext, magFieldContext, nEvents, nTracksDist(), nVertexDist(), phiDist(), pos, pTDist(), qDist(), analysis::res, resAngDist(), resIPDist(), resQoPDist(), Acts::Vertex< input_track_t >::setTracksAtVertex(), propagation_timing::stepper, thetaDist(), vXYDist(), vZDist(), x, analysis::y, z, and z0Dist().
Acts::Test::BOOST_AUTO_TEST_CASE (impactpoint_estimator_athena_test)
Unit test for ImpactPoint 3d estimator, using same configuration and test values as in Athena unit test algorithm Tracking/TrkVertexFitter/TrkVertexFitterUtils/test/ImpactPointEstimator_test.
Definition at line 308 of file ImpactPointEstimatorTests.cpp.
View newest version in sPHENIX GitHub at line 308 of file ImpactPointEstimatorTests.cpp
References Acts::units::_MeV, Acts::units::_mm, _T, Acts::IntegrationTest::bField, Acts::ImpactPointEstimator< input_track_t, propagator_t, propagator_options_t >::calculate3dDistance(), CHECK_CLOSE_ABS, Acts::ImpactPointEstimator< input_track_t, propagator_t, propagator_options_t >::estimate3DImpactParameters(), geoContext, magFieldContext, and propagation_timing::stepper.
Acts::Test::BOOST_AUTO_TEST_CASE (adaptive_multi_vertex_fitter_test_athena)
Unit test for AdaptiveMultiVertexFitter based on Athena unit test, i.e. same setting and test values are used here.
Definition at line 313 of file AdaptiveMultiVertexFitterTests.cpp.
View newest version in sPHENIX GitHub at line 313 of file AdaptiveMultiVertexFitterTests.cpp
References Acts::units::_GeV, Acts::units::_MeV, Acts::units::_mm, _T, Acts::AdaptiveMultiVertexFitter< input_track_t, linearizer_t >::State::addVertexToMultiMap(), Acts::AdaptiveMultiVertexFitter< input_track_t, linearizer_t >::Config::annealingTool, bField, CHECK_CLOSE_ABS, Acts::VertexInfo< input_track_t >::constraintVertex, debugMode, analysis::e, Acts::AdaptiveMultiVertexFitter< input_track_t, linearizer_t >::fit(), geoContext, Acts::VertexInfo< input_track_t >::linPoint, magFieldContext, Acts::VertexInfo< input_track_t >::oldPosition, Acts::VertexInfo< input_track_t >::seedPosition, Acts::Vertex< input_track_t >::setFitQuality(), Acts::Vertex< input_track_t >::setFullCovariance(), propagation_timing::stepper, Acts::VertexInfo< input_track_t >::trackLinks, Acts::AdaptiveMultiVertexFitter< input_track_t, linearizer_t >::State::tracksAtVerticesMap, Acts::AdaptiveMultiVertexFitter< input_track_t, linearizer_t >::State::vertexCollection, and Acts::AdaptiveMultiVertexFitter< input_track_t, linearizer_t >::State::vtxInfoMap.
Acts::Test::BOOST_AUTO_TEST_CASE (BoolResult)
Definition at line 316 of file ResultTests.cpp.
View newest version in sPHENIX GitHub at line 316 of file ResultTests.cpp
References analysis::res.
Acts::Test::BOOST_AUTO_TEST_CASE (wrapBin)
Definition at line 318 of file AxesTests.cpp.
View newest version in sPHENIX GitHub at line 318 of file AxesTests.cpp
References a2, a3, a4, a5, a6, and Acts::UnitConstants::u.
Acts::Test::BOOST_AUTO_TEST_CASE (LineIntersectionTest)
This tests the interseciton with line like surfaces (straw, perigee) as those share the same methods, only one test is sufficient
it looks for valid, non-valid, solutions
Forward interseciton test
Definition at line 320 of file SurfaceIntersectionTests.cpp.
View newest version in sPHENIX GitHub at line 320 of file SurfaceIntersectionTests.cpp
References Acts::units::_cm, Acts::units::_m, Acts::units::_mm, Acts::units::_um, kdfinder::abs(), Acts::aTransform, Acts::s_onSurfaceTolerance, Acts::tgContext, and transform.
Acts::Test::BOOST_AUTO_TEST_CASE (parset_copy_assignment_tests)
Unit test for copy/assignment/swap in ParameterSet class.
The behavior of the following functions is checked:
ParameterSet::ParameterSet
ParameterSet::operator=
ParameterSet::swap
Definition at line 324 of file ParameterSetTests.cpp.
View newest version in sPHENIX GitHub at line 324 of file ParameterSetTests.cpp
References M_PI, phi, and boost::swap().
Acts::Test::BOOST_AUTO_TEST_CASE (BinningData_boundaries)
Definition at line 333 of file BinningDataTests.cpp.
View newest version in sPHENIX GitHub at line 333 of file BinningDataTests.cpp
References boundaries, Acts::BinningData::boundaries(), CHECK_CLOSE_REL, analysis::e, M_PI, phiData_eq, and xData_eq.
Acts::Test::BOOST_AUTO_TEST_CASE (step_extension_vacuum_test)
This function tests the EigenStepper with the DefaultExtension and the DenseEnvironmentExtension. The focus of this tests lies in the choosing of the right extension for the individual use case. This is performed with three different detectors: a) Pure vaccuum -> DefaultExtension needs to act b) Pure Be -> DenseEnvironmentExtension needs to act c) Vacuum - Be - Vacuum -> Both should act and switch during the propagation.
Definition at line 345 of file StepperTests.cpp.
View newest version in sPHENIX GitHub at line 345 of file StepperTests.cpp
References Acts::units::_GeV, Acts::units::_keV, Acts::units::_m, Acts::units::_um, Acts::PropagatorOptions< action_list_t, aborter_list_t >::abortList, Acts::PropagatorOptions< action_list_t, aborter_list_t >::actionList, Acts::IntegrationTest::bField, CHECK_CLOSE_ABS, CHECK_SMALL, Acts::CuboidVolumeBuilder::VolumeConfig::length, Acts::CuboidVolumeBuilder::Config::length, Acts::PropagatorOptions< action_list_t, aborter_list_t >::maxSteps, Acts::PropagatorOptions< action_list_t, aborter_list_t >::maxStepSize, mfContext, charm_jet_coverage::mom, Acts::Test::StepCollector::this_result::momentum, pos, Acts::CuboidVolumeBuilder::VolumeConfig::position, Acts::CuboidVolumeBuilder::Config::position, Acts::Test::StepCollector::this_result::position, Acts::Navigator::resolveMaterial, Acts::Navigator::resolvePassive, Acts::Navigator::resolveSensitive, Acts::CuboidVolumeBuilder::setConfig(), Acts::tgContext, Acts::TrackingGeometryBuilder::trackingGeometry(), Acts::CuboidVolumeBuilder::trackingVolume(), Acts::TrackingGeometryBuilder::Config::trackingVolumeBuilders, and Acts::CuboidVolumeBuilder::Config::volumeCfg.
Acts::Test::BOOST_AUTO_TEST_CASE (BinningData_bincenter)
check the global position requests
Definition at line 352 of file BinningDataTests.cpp.
View newest version in sPHENIX GitHub at line 352 of file BinningDataTests.cpp
References Acts::binPhi, Acts::binX, Acts::BinningData::center(), CHECK_CLOSE_ABS, Acts::closed, delta, analysis::e, M_PI, nBins_binary, Acts::open, phiData_eq, phiDelta, phiMin, valueMin, xData_add(), xData_arb, xData_eq, and xData_mult.
Acts::Test::BOOST_AUTO_TEST_CASE (impactpoint_estimator_parameter_estimation_test)
Unit test for impact parameter estimation.
Definition at line 357 of file ImpactPointEstimatorTests.cpp.
View newest version in sPHENIX GitHub at line 357 of file ImpactPointEstimatorTests.cpp
References _T, Acts::IntegrationTest::bField, d0Dist(), Acts::ImpactPointEstimator< input_track_t, propagator_t, propagator_options_t >::estimateImpactParameters(), geoContext, Acts::ImpactParametersAndSigma::IPd0, Acts::ImpactParametersAndSigma::IPz0, magFieldContext, phiDist(), pTDist(), qDist(), resAngDist(), resIPDist(), resQoPDist(), Acts::Vertex< input_track_t >::setFullCovariance(), Acts::Vertex< input_track_t >::setFullPosition(), propagation_timing::stepper, thetaDist(), vXYDist(), vZDist(), x, analysis::y, z, and z0Dist().
Acts::Test::BOOST_AUTO_TEST_CASE (ray_obb_intersect)
Definition at line 373 of file BoundingBoxTest.cpp.
View newest version in sPHENIX GitHub at line 373 of file BoundingBoxTest.cpp
References Acts::PlyVisualization< T >::clear(), Acts::Ray< value_t, DIM >::draw(), Acts::AxisAlignedBoundingBox< entity_t, value_t, DIM >::draw(), M_PI, Acts::Volume::orientedBoundingBox(), origin(), Acts::Ray< value_t, DIM >::transformed(), and vtx().
Acts::Test::BOOST_AUTO_TEST_CASE (trackstate_reassignment)
Definition at line 378 of file MultiTrajectoryTests.cpp.
View newest version in sPHENIX GitHub at line 378 of file MultiTrajectoryTests.cpp
References Acts::MultiTrajectory< source_link_t >::addTrackState(), Acts::UnitConstants::fm, Acts::MultiTrajectory< source_link_t >::getTrackState(), Acts::UnitConstants::m2, make_trackstate(), t, and Acts::UnitConstants::u.
Acts::Test::BOOST_AUTO_TEST_CASE (parset_comparison_tests)
Unit test for comparison operators in ParameterSet.
See Also
ParameterSet::operator==, ParameterSet::operator!=
Definition at line 380 of file ParameterSetTests.cpp.
View newest version in sPHENIX GitHub at line 380 of file ParameterSetTests.cpp
References Acts::eBoundLoc0, Acts::eBoundLoc1, Acts::eBoundPhi, M_PI, phi, Acts::ParameterSet< params >::setCovariance(), and Acts::ParameterSet< params >::setParameter().
Acts::Test::BOOST_AUTO_TEST_CASE (BinningData_phi_modules)
Definition at line 402 of file BinningDataTests.cpp.
View newest version in sPHENIX GitHub at line 402 of file BinningDataTests.cpp
References Acts::binPhi, Acts::BinningData::boundaries(), CHECK_CLOSE_REL, Acts::closed, cos(), analysis::e, M_PI, Acts::BinningData::search(), and Acts::BinningData::searchGlobal().
Acts::Test::BOOST_AUTO_TEST_CASE (PlaneSurfacePolyhedrons)
Unit tests for Plane Surfaces.
Rectangular Plane
Trapezoidal Plane
Ring-like ellispoidal Plane
ConvextPolygonBounds test
Diamond shaped plane
Definition at line 425 of file PolyhedronSurfacesTests.cpp.
View newest version in sPHENIX GitHub at line 425 of file PolyhedronSurfacesTests.cpp
References Acts::units::_mm, Acts::binR, Acts::binX, Acts::binY, Acts::binZ, CHECK_CLOSE_ABS, analysis::e, max, testModes, Acts::tgContext, and transform.
Acts::Test::BOOST_AUTO_TEST_CASE (storage_consistency)
Definition at line 426 of file MultiTrajectoryTests.cpp.
View newest version in sPHENIX GitHub at line 426 of file MultiTrajectoryTests.cpp
References Acts::MultiTrajectory< source_link_t >::addTrackState(), Acts::UnitConstants::fm, Acts::MultiTrajectory< source_link_t >::getTrackState(), make_trackstate(), and t.
Acts::Test::BOOST_AUTO_TEST_CASE (frustum_intersect)
Definition at line 436 of file BoundingBoxTest.cpp.
View newest version in sPHENIX GitHub at line 436 of file BoundingBoxTest.cpp
References Acts::PlyVisualization< T >::clear(), color, Acts::Frustum< value_t, DIM, SIDES >::draw(), Acts::AxisAlignedBoundingBox< entity_t, value_t, DIM >::draw(), analysis::h, incremental_prev_tag::idx, Acts::AxisAlignedBoundingBox< entity_t, value_t, DIM >::intersect(), k, M_PI, max, min, n, pos, analysis::s, and step().
Acts::Test::BOOST_AUTO_TEST_CASE (grid_test_1d_variable)
Definition at line 437 of file GridTests.cpp.
View newest version in sPHENIX GitHub at line 437 of file GridTests.cpp
References a, g(), and Acts::UnitConstants::u.
Acts::Test::BOOST_AUTO_TEST_CASE (parset_projection_tests)
Unit test for projection matrices in ParameterSet.
Checks the correctness of the projection matrices from the full parameter space onto different parameter sub-spaces
See Also
ParameterSet::projector
Definition at line 444 of file ParameterSetTests.cpp.
View newest version in sPHENIX GitHub at line 444 of file ParameterSetTests.cpp
References Acts::eBoundLoc0, Acts::eBoundLoc1, Acts::eBoundPhi, Acts::eBoundQOverP, Acts::eBoundTheta, and Acts::eT.
Acts::Test::BOOST_AUTO_TEST_CASE (step_extension_material_test)
Definition at line 456 of file StepperTests.cpp.
View newest version in sPHENIX GitHub at line 456 of file StepperTests.cpp
References Acts::units::_GeV, Acts::units::_keV, Acts::units::_m, _T, Acts::units::_um, Acts::PropagatorOptions< action_list_t, aborter_list_t >::abortList, kdfinder::abs(), Acts::PropagatorOptions< action_list_t, aborter_list_t >::actionList, Acts::IntegrationTest::bField, CHECK_CLOSE_ABS, CHECK_SMALL, Acts::PropagatorOptions< action_list_t, aborter_list_t >::debug, analysis::e, Acts::CuboidVolumeBuilder::VolumeConfig::length, material, Acts::PropagatorOptions< action_list_t, aborter_list_t >::maxSteps, Acts::PropagatorOptions< action_list_t, aborter_list_t >::maxStepSize, mfContext, charm_jet_coverage::mom, Acts::Test::StepCollector::this_result::momentum, pos, Acts::CuboidVolumeBuilder::VolumeConfig::position, Acts::Test::StepCollector::this_result::position, Acts::Navigator::resolveMaterial, Acts::Navigator::resolvePassive, Acts::Navigator::resolveSensitive, Acts::CuboidVolumeBuilder::setConfig(), Acts::ConstantBField::setField(), Acts::tgContext, Acts::TrackingGeometryBuilder::trackingGeometry(), Acts::CuboidVolumeBuilder::trackingVolume(), Acts::TrackingGeometryBuilder::Config::trackingVolumeBuilders, Acts::CuboidVolumeBuilder::Config::volumeCfg, and Acts::CuboidVolumeBuilder::VolumeConfig::volumeMaterial.
Acts::Test::BOOST_AUTO_TEST_CASE (parset_residual_tests)
Unit test for residuals between different ParameterSet objects.
The result of the residual calculation between two ParameterSet objects is checked. A test of the automatic correction of stored parameter values for out-of-bounds/cyclic corrections is also implemented.
See Also
ParameterSet::residual, ParameterSet::getParameter
Definition at line 499 of file ParameterSetTests.cpp.
View newest version in sPHENIX GitHub at line 499 of file ParameterSetTests.cpp
References kdfinder::abs(), CHECK_CLOSE_REL, QAG4Util::delta_phi(), Acts::eBoundLoc0, Acts::eBoundLoc1, Acts::eBoundPhi, Acts::eBoundQOverP, Acts::eBoundTheta, Acts::ParameterSet< params >::getParameter(), M_PI, min, Acts::ParameterSet< params >::residual(), and Acts::ParameterSet< params >::setParameter().
Acts::Test::BOOST_AUTO_TEST_CASE (grid_test_2d_variable)
Definition at line 505 of file GridTests.cpp.
View newest version in sPHENIX GitHub at line 505 of file GridTests.cpp
References a, b, g(), and Acts::UnitConstants::u.
Acts::Test::BOOST_AUTO_TEST_CASE (parset_parID_mapping)
Unit test for index-/type-based access of coordinates.
See Also
ParameterSet::getIndex
ParameterSet::getParID
Definition at line 588 of file ParameterSetTests.cpp.
View newest version in sPHENIX GitHub at line 588 of file ParameterSetTests.cpp
References Acts::eBoundLoc0, Acts::eBoundLoc1, Acts::eBoundPhi, Acts::eBoundQOverP, Acts::eBoundTheta, Acts::eT, and value.
Acts::Test::BOOST_AUTO_TEST_CASE (step_extension_vacmatvac_test)
Definition at line 620 of file StepperTests.cpp.
View newest version in sPHENIX GitHub at line 620 of file StepperTests.cpp
References Acts::units::_GeV, Acts::units::_m, _T, Acts::units::_um, Acts::PropagatorOptions< action_list_t, aborter_list_t >::abortList, b, Acts::IntegrationTest::bField, boundaries, CHECK_CLOSE_ABS, Acts::PropagatorOptions< action_list_t, aborter_list_t >::debug, analysis::e, Acts::detail::Extendable< aborters_t...>::get(), Acts::CuboidVolumeBuilder::VolumeConfig::length, Acts::CuboidVolumeBuilder::Config::length, Acts::PropagatorOptions< action_list_t, aborter_list_t >::maxSteps, Acts::PropagatorOptions< action_list_t, aborter_list_t >::maxStepSize, mfContext, Acts::Test::StepCollector::this_result::momentum, Acts::CuboidVolumeBuilder::VolumeConfig::name, Acts::CuboidVolumeBuilder::VolumeConfig::position, Acts::CuboidVolumeBuilder::Config::position, Acts::Test::StepCollector::this_result::position, Acts::Navigator::resolveMaterial, Acts::Navigator::resolvePassive, Acts::Navigator::resolveSensitive, Acts::CuboidVolumeBuilder::setConfig(), Acts::tgContext, Acts::PropagatorOptions< action_list_t, aborter_list_t >::tolerance, Acts::TrackingGeometryBuilder::trackingGeometry(), Acts::CuboidVolumeBuilder::trackingVolume(), Acts::TrackingGeometryBuilder::Config::trackingVolumeBuilders, Acts::CuboidVolumeBuilder::Config::volumeCfg, and Acts::CuboidVolumeBuilder::VolumeConfig::volumeMaterial.
Acts::Test::BOOST_AUTO_TEST_CASE (grid_test_3d_variable)
Definition at line 629 of file GridTests.cpp.
View newest version in sPHENIX GitHub at line 629 of file GridTests.cpp
References a, b, c, g(), and Acts::UnitConstants::u.
Acts::Test::BOOST_AUTO_TEST_CASE (grid_test_2d_mixed)
Definition at line 769 of file GridTests.cpp.
View newest version in sPHENIX GitHub at line 769 of file GridTests.cpp
References a, b, g(), and Acts::UnitConstants::u.
Acts::Test::BOOST_AUTO_TEST_CASE (step_extension_trackercalomdt_test)
Definition at line 845 of file StepperTests.cpp.
View newest version in sPHENIX GitHub at line 845 of file StepperTests.cpp
References Acts::units::_GeV, Acts::units::_m, Acts::units::_mm, Acts::PropagatorOptions< action_list_t, aborter_list_t >::abortList, Acts::IntegrationTest::bField, cos(), analysis::e, Acts::CuboidVolumeBuilder::VolumeConfig::layerCfg, Acts::CuboidVolumeBuilder::VolumeConfig::length, Acts::CuboidVolumeBuilder::Config::length, M_PI, mfContext, Acts::Test::StepCollector::this_result::momentum, Acts::CuboidVolumeBuilder::VolumeConfig::name, Acts::CuboidVolumeBuilder::SurfaceConfig::position, Acts::CuboidVolumeBuilder::VolumeConfig::position, Acts::CuboidVolumeBuilder::Config::position, Acts::Test::StepCollector::this_result::position, Acts::CuboidVolumeBuilder::SurfaceConfig::rBounds, Acts::Navigator::resolveMaterial, Acts::Navigator::resolvePassive, Acts::Navigator::resolveSensitive, Acts::CuboidVolumeBuilder::SurfaceConfig::rotation, Acts::CuboidVolumeBuilder::setConfig(), Acts::CuboidVolumeBuilder::LayerConfig::surfaceCfg, Acts::CuboidVolumeBuilder::SurfaceConfig::surMat, Acts::tgContext, Acts::CuboidVolumeBuilder::SurfaceConfig::thickness, Acts::TrackingGeometryBuilder::trackingGeometry(), Acts::CuboidVolumeBuilder::trackingVolume(), Acts::TrackingGeometryBuilder::Config::trackingVolumeBuilders, Acts::CuboidVolumeBuilder::VolumeConfig::volumeCfg, Acts::CuboidVolumeBuilder::Config::volumeCfg, and Acts::CuboidVolumeBuilder::VolumeConfig::volumeMaterial.
Acts::Test::BOOST_AUTO_TEST_CASE (grid_test_2d_mixed_at)
Definition at line 928 of file GridTests.cpp.
View newest version in sPHENIX GitHub at line 928 of file GridTests.cpp
References a, b, g(), and Acts::UnitConstants::u.
Acts::Test::BOOST_AUTO_TEST_CASE (grid_interpolation)
Definition at line 963 of file GridTests.cpp.
View newest version in sPHENIX GitHub at line 963 of file GridTests.cpp
References a, Acts::detail::Grid< T, Axes >::atPosition(), b, c, CHECK_CLOSE_REL, analysis::e, g(), Acts::detail::Grid< T, Axes >::interpolate(), and Acts::UnitConstants::u.
Acts::Test::BOOST_AUTO_TEST_CASE (closestPoints)
Definition at line 1144 of file GridTests.cpp.
View newest version in sPHENIX GitHub at line 1144 of file GridTests.cpp
References a, b, c, and Acts::UnitConstants::u.
Acts::Test::BOOST_DATA_TEST_CASE (CylinderVolumeBuilder_wraps , bdata:: random-11.,-15.)^bdata::random(11., 15.)^bdata::random(-10., 10.)^bdata::random(0., 4.)^bdata::random(11., 15.)^bdata::random(10., 15.)^bdata::xrange(100, left , right , central , inner , outer , length , index)
Unit test for testing the wraps() function of the CylinderVolumeBuilder.
Definition at line 23 of file CylinderVolumeBuilderTests.cpp.
View newest version in sPHENIX GitHub at line 23 of file CylinderVolumeBuilderTests.cpp
References G4BARRELHCAL::length, Acts::VolumeConfig::rMax, Acts::VolumeConfig::rMin, nlohmann::detail::void(), Acts::VolumeConfig::wraps(), Acts::VolumeConfig::zMax, and Acts::VolumeConfig::zMin.
Acts::Test::BOOST_DATA_TEST_CASE (DoubleHitsSpacePointBuilder_basic , bdata:: xrange1, index)
Unit test for testing the main functions of DoubleHitSpacePointBuilder 1) A pair of hits gets added and resolved. 2) A pair of hits gets added and rejected.
Definition at line 32 of file DoubleHitSpacePointBuilderTests.cpp.
View newest version in sPHENIX GitHub at line 32 of file DoubleHitSpacePointBuilderTests.cpp
References Acts::units::_m, Acts::units::_mm, Acts::units::_um, Acts::binX, Acts::binY, cos(), Acts::open, Acts::tgContext, Acts::UnitConstants::u, and nlohmann::detail::void().
Acts::Test::BOOST_DATA_TEST_CASE (SingleHitSpacePointBuilder_basic , bdata:: xrange1, index)
Unit test for testing the main functions of OneHitSpacePointBuilder 1) A resolved dummy hit gets created and added. 2) A hit gets added and resolved.
Definition at line 33 of file SingleHitSpacePointBuilderTests.cpp.
View newest version in sPHENIX GitHub at line 33 of file SingleHitSpacePointBuilderTests.cpp
References Acts::units::_m, Acts::units::_mm, Acts::units::_um, Acts::binX, Acts::binY, cos(), data, Acts::open, tgContext, vector(), and nlohmann::detail::void().
Acts::Test::BOOST_DATA_TEST_CASE (ConstantBField_components , bdata:: random-2_T, 2_T)^bdata::random(-1_T, 4_T)^bdata::random(0_T, 10_T)^bdata::random(-10_m, 10_m)^bdata::random(-10_m, 10_m)^bdata::random(-10_m, 10_m)^bdata::xrange(10, x , y , z , bx , by , bz , index)
unit test for construction of constant magnetic field
Tests the correct behavior and consistency of
ConstantBField::ConstantBField(double Bx,double By,double Bz)
ConstantBField::ConstantBField(Vector3D B)
ConstantBField::getField(const double* xyz, double* B) const
ConstantBField::getField(const Vector3D& pos) const
Definition at line 36 of file ConstantBFieldTests.cpp.
View newest version in sPHENIX GitHub at line 36 of file ConstantBFieldTests.cpp
References Acts::ConstantBField::getField(), mfContext, pos, nlohmann::detail::void(), x, analysis::y, and z.
Acts::Test::BOOST_DATA_TEST_CASE (bound_to_plane_test , bdata:: random(bdata::seed=1240,bdata::distribution=std::uniform_real_distribution<>(-1000., 1000.)))^bdata::random((bdata::seed=2351,bdata::distribution=std::uniform_real_distribution<>(-1000., 1000.)))^bdata::random((bdata::seed=3412,bdata::distribution=std::uniform_real_distribution<>(-1000., 1000.)))^bdata::random((bdata::seed=5732,bdata::distribution=std::uniform_real_distribution<>(0., M_PI)))^bdata::random((bdata::seed=8941,bdata::distribution=std::uniform_real_distribution<>(0., M_PI)))^bdata::random((bdata::seed=1295,bdata::distribution=std::uniform_real_distribution<>(0., M_PI)))^bdata::xrange(100, x , y , z , a , b , c , index)
Unit test for parameters at a plane.
modification test via setter functions
Definition at line 40 of file BoundParametersTests.cpp.
View newest version in sPHENIX GitHub at line 40 of file BoundParametersTests.cpp
References a, b, c, CHECK_CLOSE_REL, consistencyCheck(), cos(), analysis::e, Acts::eLOC_X, Acts::eLOC_Y, Acts::ePHI, Acts::eQOP, Acts::eT, Acts::eTHETA, charm_jet_coverage::mom, Acts::SingleTrackParameters< ChargePolicy >::momentum(), p, phi, pos, Acts::SingleTrackParameters< ChargePolicy >::position(), Acts::SingleBoundTrackParameters< ChargePolicy >::referenceFrame(), Acts::SingleBoundTrackParameters< ChargePolicy >::referenceSurface(), Acts::SingleBoundTrackParameters< ChargePolicy >::set(), tgContext, ds::theta, transform, Acts::UnitConstants::u, ux, uy, nlohmann::detail::void(), x, analysis::y, and z.
Acts::Test::BOOST_DATA_TEST_CASE (readout_counter_test , bdata:: random(bdata::seed=0,bdata::distribution=std::uniform_real_distribution<>(-halfX+sguardX, halfX-sguardX)))^bdata::random((bdata::seed=1,bdata::distribution=std::uniform_real_distribution<>(-halfX+sguardX, halfX-sguardX)))^bdata::random((bdata::seed=2,bdata::distribution=std::uniform_real_distribution<>(-halfY, halfY)))^bdata::random((bdata::seed=3,bdata::distribution=std::uniform_int_distribution<>(-halfY, halfY)))^bdata::xrange(ntests, entryX , entryY , exitX , exitY , index)
The following test checks test cases where the entry and exit is guaranteed to be in on the readout/counter plane
Definition at line 60 of file PlanarModuleStepperTests.cpp.
View newest version in sPHENIX GitHub at line 60 of file PlanarModuleStepperTests.cpp
References Acts::PlanarModuleStepper::cellSteps(), CHECK_CLOSE_REL, analysis::e, exit(), hThickness, pmStepper, testModules, Acts::tgContext, nlohmann::detail::void(), and z.
Acts::Test::BOOST_DATA_TEST_CASE (ConstantBField_update , bdata:: random-2_T, 2_T)^bdata::random(-1_T, 4_T)^bdata::random(0_T, 10_T)^bdata::random(-10_m, 10_m)^bdata::random(-10_m, 10_m)^bdata::random(-10_m, 10_m)^bdata::xrange(10, x , y , z , bx , by , bz , index)
unit test for update of constant magnetic field
Tests the correct behavior and consistency of
ConstantBField::setField(double Bx, double By, double Bz)
ConstantBField::setField(const Vector3D& B)
ConstantBField::getField(const double* xyz, double* B) const
ConstantBField::getField(const Vector3D& pos) const
Definition at line 83 of file ConstantBFieldTests.cpp.
View newest version in sPHENIX GitHub at line 83 of file ConstantBFieldTests.cpp
References Acts::ConstantBField::getField(), mfContext, pos, Acts::ConstantBField::setField(), nlohmann::detail::void(), x, analysis::y, and z.
Acts::Test::BOOST_DATA_TEST_CASE (test_extrapolation_ , bdata:: random(bdata::seed=0,bdata::distribution=std::uniform_real_distribution<>(0.4_GeV, 10_GeV)))^bdata::random((bdata::seed=1,bdata::distribution=std::uniform_real_distribution<>(-M_PI, M_PI)))^bdata::random((bdata::seed=2,bdata::distribution=std::uniform_real_distribution<>(1.0, M_PI-1.0)))^bdata::random((bdata::seed=3,bdata::distribution=std::uniform_int_distribution<>(0, 1)))^bdata::random((bdata::seed=4,bdata::distribution=std::uniform_int_distribution<>(0, 100)))^bdata::xrange(ntests, pT , phi , theta , charge , time , index)
a covariance matrix to transport
Definition at line 77 of file ExtrapolatorTests.cpp.
View newest version in sPHENIX GitHub at line 77 of file ExtrapolatorTests.cpp
References Acts::units::_cm, Acts::units::_GeV, Acts::units::_mm, charge, cos(), Acts::IntegrationTest::epropagator(), Acts::PropagatorOptions< action_list_t, aborter_list_t >::maxStepSize, mfContext, charm_jet_coverage::mom, eicpy.build::options, Acts::PropagatorOptions< action_list_t, aborter_list_t >::pathLimit, phi, pos, Acts::Propagator< stepper_t, navigator_t >::propagate(), ds::pT, Acts::tgContext, ds::theta, Acts::VectorHelpers::time(), nlohmann::detail::void(), x, analysis::y, and z.
Acts::Test::BOOST_DATA_TEST_CASE (bvhnavigation_test , bdata:: random(bdata::seed=7, bdata::engine=std::mt19937(),bdata::distribution=std::uniform_real_distribution<>(-5,5)))^bdata::random((bdata::seed=2, bdata::engine=std::mt19937(),bdata::distribution=std::uniform_real_distribution<>(-M_PI, M_PI)))^bdata::random((bdata::seed=3, bdata::engine=std::mt19937(),bdata::distribution=std::uniform_real_distribution<>(-100, 100)))^bdata::random((bdata::seed=4, bdata::engine=std::mt19937(),bdata::distribution=std::uniform_real_distribution<>(-100, 100)))^bdata::random((bdata::seed=5, bdata::engine=std::mt19937(),bdata::distribution=std::uniform_real_distribution<>(-100, 100)))^bdata::xrange(NTESTS, eta , phi , x , y , z , index)
Definition at line 80 of file TrackingVolumeTests.cpp.
View newest version in sPHENIX GitHub at line 80 of file TrackingVolumeTests.cpp
Acts::Test::BOOST_DATA_TEST_CASE (benchmark_surface_intersections , bdata:: random(bdata::seed=21,bdata::distribution=std::uniform_real_distribution<>(-M_PI, M_PI)))^bdata::random((bdata::seed=22,bdata::distribution=std::uniform_real_distribution<>(-0.3, 0.3)))^bdata::xrange(ntests, phi , theta , index)
Definition at line 93 of file SurfaceIntersectionBenchmark.cpp.
View newest version in sPHENIX GitHub at line 93 of file SurfaceIntersectionBenchmark.cpp
References aCylinder, aDisc, aPlane, aStraw, M_PI, phi, testCylinder, testDisc, testPlane, testStraw, ds::theta, and nlohmann::detail::void().
Acts::Test::BOOST_DATA_TEST_CASE (CylinderVolumeBuilder_containes , bdata:: random-11.,-15.)^bdata::random(11., 15.)^bdata::random(-10., 10.)^bdata::random(0., 4.)^bdata::random(10., 15.)^bdata::random(10., 15.)^bdata::xrange(100, left , right , central , inner , outer , length , index)
Unit test for testing the contains(), containsInR() and containsInZ() function of the CylinderVolumeBuilder
Definition at line 99 of file CylinderVolumeBuilderTests.cpp.
View newest version in sPHENIX GitHub at line 99 of file CylinderVolumeBuilderTests.cpp
References Acts::VolumeConfig::contains(), Acts::VolumeConfig::containsInR(), Acts::VolumeConfig::containsInZ(), G4BARRELHCAL::length, Acts::VolumeConfig::rMax, Acts::VolumeConfig::rMin, nlohmann::detail::void(), Acts::VolumeConfig::zMax, and Acts::VolumeConfig::zMin.
Acts::Test::BOOST_DATA_TEST_CASE (loop_aborter_test , bdata:: random(bdata::seed=21,bdata::distribution=std::uniform_real_distribution<>(-M_PI, M_PI)))^bdata::random((bdata::seed=22,bdata::distribution=std::uniform_real_distribution<>(-M_PI, M_PI)))^bdata::xrange(1, phi , deltaPhi , index)
Definition at line 110 of file LoopProtectionTests.cpp.
View newest version in sPHENIX GitHub at line 110 of file LoopProtectionTests.cpp
References Acts::units::_MeV, cos(), Acts::Test::PropagatorState::options, phi, Acts::Test::PropagatorState::stepping, and nlohmann::detail::void().
Acts::Test::BOOST_DATA_TEST_CASE (test_surface_collection_ , bdata:: random(bdata::seed=10,bdata::distribution=std::uniform_real_distribution<>(0.4_GeV, 10_GeV)))^bdata::random((bdata::seed=11,bdata::distribution=std::uniform_real_distribution<>(-M_PI, M_PI)))^bdata::random((bdata::seed=12,bdata::distribution=std::uniform_real_distribution<>(1.0, M_PI-1.0)))^bdata::random((bdata::seed=13,bdata::distribution=std::uniform_int_distribution<>(0, 1)))^bdata::random((bdata::seed=14,bdata::distribution=std::uniform_int_distribution<>(0, 100)))^bdata::xrange(ntests, pT , phi , theta , charge , time , index)
a covariance matrix to transport
Definition at line 127 of file ExtrapolatorTests.cpp.
View newest version in sPHENIX GitHub at line 127 of file ExtrapolatorTests.cpp
References Acts::units::_cm, Acts::units::_GeV, Acts::units::_mm, charge, cos(), Acts::PropagatorOptions< action_list_t, aborter_list_t >::debug, debugMode, Acts::IntegrationTest::epropagator(), Acts::PropagatorOptions< action_list_t, aborter_list_t >::maxStepSize, mfContext, charm_jet_coverage::mom, eicpy.build::options, Acts::PropagatorOptions< action_list_t, aborter_list_t >::pathLimit, phi, pos, Acts::Propagator< stepper_t, navigator_t >::propagate(), ds::pT, Acts::SingleCurvilinearTrackParameters< ChargePolicy >::referenceSurface(), Acts::tgContext, ds::theta, Acts::VectorHelpers::time(), nlohmann::detail::void(), x, analysis::y, and z.
Acts::Test::BOOST_DATA_TEST_CASE (CylinderVolumeBoundsDecomposeToSurfaces , bdata:: random-M_PI, M_PI)^bdata::random(-M_PI, M_PI)^bdata::random(-M_PI, M_PI)^bdata::random(-10., 10.)^bdata::random(-10., 10.)^bdata::random(-10., 10.)^bdata::xrange(100, alpha , beta , gamma , posX , posY , posZ , index)
Unit test for testing the decomposeToSurfaces() function.
Definition at line 144 of file CylinderVolumeBoundsTests.cpp.
View newest version in sPHENIX GitHub at line 144 of file CylinderVolumeBoundsTests.cpp
References starlightConstants::alpha, CHECK_CLOSE_ABS, CHECK_CLOSE_REL, boost::const_pointer_cast(), Acts::CylinderVolumeBounds::decomposeToSurfaces(), analysis::e, Acts::CylinderVolumeBounds::eHalfLengthZ, gamma(), Acts::CylinderVolumeBounds::get(), pos, rmax(), tgContext, nlohmann::detail::void(), and z.
Acts::Test::BOOST_DATA_TEST_CASE (cylinder_passage_observer_ , bdata:: random(bdata::seed=0,bdata::distribution=std::uniform_real_distribution<>(0.4_GeV, 10_GeV)))^bdata::random((bdata::seed=1,bdata::distribution=std::uniform_real_distribution<>(-M_PI, M_PI)))^bdata::random((bdata::seed=2,bdata::distribution=std::uniform_real_distribution<>(1.0, M_PI-1.0)))^bdata::random((bdata::seed=3,bdata::distribution=std::uniform_int_distribution<>(0, 1)))^bdata::random((bdata::seed=4,bdata::distribution=std::uniform_int_distribution<>(0, 100)))^bdata::xrange(ntests, pT , phi , theta , charge , time , index)
Definition at line 143 of file PropagatorTests.cpp.
View newest version in sPHENIX GitHub at line 143 of file PropagatorTests.cpp
References Acts::units::_cm, Acts::units::_m, Acts::PropagatorOptions< action_list_t, aborter_list_t >::actionList, charge, CHECK_CLOSE_ABS, cos(), cSurface, analysis::e, Acts::IntegrationTest::epropagator(), Acts::PropagatorOptions< action_list_t, aborter_list_t >::maxStepSize, mfContext, charm_jet_coverage::mom, mSurface, eicpy.build::options, Acts::PropagatorOptions< action_list_t, aborter_list_t >::pathLimit, phi, pos, Acts::Propagator< stepper_t, navigator_t >::propagate(), ds::pT, Acts::tgContext, ds::theta, Acts::VectorHelpers::time(), Acts::UnitConstants::u, nlohmann::detail::void(), x, analysis::y, and z.
Acts::Test::BOOST_DATA_TEST_CASE (propagator_loop_protection_test , bdata:: random(bdata::seed=20,bdata::distribution=std::uniform_real_distribution<>(0.5_GeV, 10_GeV)))^bdata::random((bdata::seed=21,bdata::distribution=std::uniform_real_distribution<>(-M_PI, M_PI)))^bdata::random((bdata::seed=22,bdata::distribution=std::uniform_real_distribution<>(1.0, M_PI-1.0)))^bdata::random((bdata::seed=23,bdata::distribution=std::uniform_int_distribution<>(0, 1)))^bdata::xrange(ntests, pT , phi , theta , charge , index)
Definition at line 149 of file LoopProtectionTests.cpp.
View newest version in sPHENIX GitHub at line 149 of file LoopProtectionTests.cpp
References _T, Acts::IntegrationTest::bField, Acts::IntegrationTest::Bz, charge, CHECK_CLOSE_REL, cos(), analysis::e, Acts::IntegrationTest::epropagator(), Acts::IntegrationTest::estepper, mfContext, charm_jet_coverage::mom, eicpy.build::options, phi, pos, ds::pT, Acts::IntegrationTest::skip, Acts::tgContext, ds::theta, x, analysis::y, and z.
Acts::Test::BOOST_DATA_TEST_CASE (bound_to_disc_test , bdata:: random(bdata::seed=9810,bdata::distribution=std::uniform_real_distribution<>(-1000., 1000.)))^bdata::random((bdata::seed=1221,bdata::distribution=std::uniform_real_distribution<>(-1000., 1000.)))^bdata::random((bdata::seed=12132,bdata::distribution=std::uniform_real_distribution<>(-1000., 1000.)))^bdata::random((bdata::seed=16783,bdata::distribution=std::uniform_real_distribution<>(0., M_PI)))^bdata::random((bdata::seed=13984,bdata::distribution=std::uniform_real_distribution<>(0., M_PI)))^bdata::random((bdata::seed=77615,bdata::distribution=std::uniform_real_distribution<>(0., M_PI)))^bdata::xrange(100, x , y , z , a , b , c , index)
Unit test for parameters at a disc.
Definition at line 148 of file BoundParametersTests.cpp.
View newest version in sPHENIX GitHub at line 148 of file BoundParametersTests.cpp
References a, b, c, CHECK_CLOSE_REL, consistencyCheck(), cos(), analysis::e, charm_jet_coverage::mom, p, phi, pos, Acts::SingleBoundTrackParameters< ChargePolicy >::referenceFrame(), Acts::SingleBoundTrackParameters< ChargePolicy >::referenceSurface(), tgContext, ds::theta, transform, Acts::UnitConstants::u, nlohmann::detail::void(), x, analysis::y, and z.
Acts::Test::BOOST_DATA_TEST_CASE (CylinderVolumeBuilder_overlapsInR , bdata:: random0., 4.)^bdata::random(11., 15.)^bdata::xrange(100, inner , outer , index)
Unit test for testing the coverlapsInR() function of the CylinderVolumeBuilder
Definition at line 186 of file CylinderVolumeBuilderTests.cpp.
View newest version in sPHENIX GitHub at line 186 of file CylinderVolumeBuilderTests.cpp
References Acts::VolumeConfig::overlapsInR(), Acts::VolumeConfig::present, Acts::VolumeConfig::rMax, Acts::VolumeConfig::rMin, nlohmann::detail::void(), Acts::VolumeConfig::zMax, and Acts::VolumeConfig::zMin.
Acts::Test::BOOST_DATA_TEST_CASE (test_direct_navigator , bdata:: random(bdata::seed=20,bdata::distribution=std::uniform_real_distribution<>(0.15_GeV, 10_GeV)))^bdata::random((bdata::seed=21,bdata::distribution=std::uniform_real_distribution<>(-M_PI, M_PI)))^bdata::random((bdata::seed=22,bdata::distribution=std::uniform_real_distribution<>(1.0, M_PI-1.0)))^bdata::random((bdata::seed=23,bdata::distribution=std::uniform_int_distribution<>(0, 1)))^bdata::random((bdata::seed=24,bdata::distribution=std::uniform_int_distribution<>(0, 100)))^bdata::xrange(ntests, pT , phi , theta , charge , time , index)
Definition at line 199 of file DirectNavigatorTests.cpp.
View newest version in sPHENIX GitHub at line 199 of file DirectNavigatorTests.cpp
References charge, dpropagator(), phi, ds::pT, rpropagator(), runTest(), ds::theta, and Acts::VectorHelpers::time().
Acts::Test::BOOST_DATA_TEST_CASE (curvilinear_additive_ , bdata:: random(bdata::seed=0,bdata::distribution=std::uniform_real_distribution<>(0.4_GeV, 10_GeV)))^bdata::random((bdata::seed=1,bdata::distribution=std::uniform_real_distribution<>(-M_PI, M_PI)))^bdata::random((bdata::seed=2,bdata::distribution=std::uniform_real_distribution<>(1.0, M_PI-1.0)))^bdata::random((bdata::seed=3,bdata::distribution=std::uniform_int_distribution<>(0, 1)))^bdata::random((bdata::seed=4,bdata::distribution=std::uniform_int_distribution<>(0, 100)))^bdata::xrange(ntests, pT , phi , theta , charge , time , index)
a covariance matrix to transport
Definition at line 200 of file PropagatorTests.cpp.
View newest version in sPHENIX GitHub at line 200 of file PropagatorTests.cpp
References Acts::units::_cm, Acts::units::_GeV, Acts::units::_mm, charge, CHECK_CLOSE_OR_SMALL, CHECK_CLOSE_REL, cos(), analysis::e, Acts::IntegrationTest::epropagator(), Acts::PropagatorOptions< action_list_t, aborter_list_t >::maxStepSize, mfContext, charm_jet_coverage::mom, Acts::PropagatorOptions< action_list_t, aborter_list_t >::pathLimit, phi, pos, Acts::Propagator< stepper_t, navigator_t >::propagate(), ds::pT, Acts::tgContext, ds::theta, Acts::VectorHelpers::time(), nlohmann::detail::void(), x, analysis::y, and z.
Acts::Test::BOOST_DATA_TEST_CASE (test_material_interactor_ , bdata:: random(bdata::seed=20,bdata::distribution=std::uniform_real_distribution<>(0.4_GeV, 10_GeV)))^bdata::random((bdata::seed=21,bdata::distribution=std::uniform_real_distribution<>(-M_PI, M_PI)))^bdata::random((bdata::seed=22,bdata::distribution=std::uniform_real_distribution<>(1.0, M_PI-1.0)))^bdata::random((bdata::seed=23,bdata::distribution=std::uniform_int_distribution<>(0, 1)))^bdata::random((bdata::seed=24,bdata::distribution=std::uniform_int_distribution<>(0, 100)))^bdata::xrange(ntests, pT , phi , theta , charge , time , index)
a covariance matrix to transport
Definition at line 202 of file ExtrapolatorTests.cpp.
View newest version in sPHENIX GitHub at line 202 of file ExtrapolatorTests.cpp
References Acts::units::_cm, Acts::units::_GeV, Acts::units::_mm, charge, cos(), Acts::PropagatorOptions< action_list_t, aborter_list_t >::debug, debugMode, Acts::DebugOutputActor::this_result::debugString, Acts::IntegrationTest::epropagator(), Acts::PropagatorOptions< action_list_t, aborter_list_t >::maxStepSize, mfContext, charm_jet_coverage::mom, Acts::SingleTrackParameters< ChargePolicy >::momentum(), eicpy.build::options, Acts::PropagatorOptions< action_list_t, aborter_list_t >::pathLimit, phi, pos, Acts::Propagator< stepper_t, navigator_t >::propagate(), ds::pT, Acts::tgContext, ds::theta, Acts::VectorHelpers::time(), nlohmann::detail::void(), x, analysis::y, and z.
Acts::Test::BOOST_DATA_TEST_CASE (bfield_symmetry_random , bdata:: random(bdata::seed=0,bdata::distribution=std::uniform_real_distribution<>(-10., 10.)))^bdata::random((bdata::seed=0,bdata::distribution=std::uniform_real_distribution<>(-10., 10.)))^bdata::random((bdata::seed=0,bdata::distribution=std::uniform_real_distribution<>(-20., 20.)))^bdata::xrange(10, x , y , z , index)
Unit test for testing the decomposeToSurfaces() function.
Definition at line 233 of file BFieldMapUtilsTests.cpp.
View newest version in sPHENIX GitHub at line 233 of file BFieldMapUtilsTests.cpp
References CHECK_CLOSE_ABS, CHECK_CLOSE_REL, analysis::e, Acts::fieldMapperRZ(), Acts::fieldMapperXYZ(), Acts::VectorHelpers::perp(), nlohmann::detail::void(), x, analysis::y, and z.
Acts::Test::BOOST_DATA_TEST_CASE (CylinderVolumeBuilder_overlapsInZ , bdata:: random-11.,-15.)^bdata::random(11., 15.)^bdata::random(0., 4.)^bdata::xrange(100, left , right , inner , index)
Unit test for testing the coverlapsInZ() function of the CylinderVolumeBuilder
Definition at line 248 of file CylinderVolumeBuilderTests.cpp.
View newest version in sPHENIX GitHub at line 248 of file CylinderVolumeBuilderTests.cpp
References Acts::VolumeConfig::overlapsInZ(), Acts::VolumeConfig::present, Acts::VolumeConfig::rMax, Acts::VolumeConfig::rMin, nlohmann::detail::void(), Acts::VolumeConfig::zMax, and Acts::VolumeConfig::zMin.
Acts::Test::BOOST_DATA_TEST_CASE (bound_to_cylinder_test , bdata:: random(bdata::seed=39810,bdata::distribution=std::uniform_real_distribution<>(-1000., 1000.)))^bdata::random((bdata::seed=21221,bdata::distribution=std::uniform_real_distribution<>(-1000., 1000.)))^bdata::random((bdata::seed=62132,bdata::distribution=std::uniform_real_distribution<>(-1000., 1000.)))^bdata::random((bdata::seed=91683,bdata::distribution=std::uniform_real_distribution<>(0., M_PI)))^bdata::random((bdata::seed=39847,bdata::distribution=std::uniform_real_distribution<>(0., M_PI)))^bdata::random((bdata::seed=72615,bdata::distribution=std::uniform_real_distribution<>(0., M_PI)))^bdata::xrange(100, x , y , z , a , b , c , index)
Unit test for parameters at a cylinder.
Definition at line 231 of file BoundParametersTests.cpp.
View newest version in sPHENIX GitHub at line 231 of file BoundParametersTests.cpp
References a, b, c, CHECK_CLOSE_REL, consistencyCheck(), cos(), cSurface, analysis::e, Acts::CylinderBounds::eR, charm_jet_coverage::mom, p, phi, pos, Acts::SingleTrackParameters< ChargePolicy >::position(), r, Acts::SingleBoundTrackParameters< ChargePolicy >::referenceFrame(), Acts::SingleBoundTrackParameters< ChargePolicy >::referenceSurface(), tgContext, ds::theta, transform, Acts::UnitConstants::u, nlohmann::detail::void(), x, analysis::y, and z.
Acts::Test::BOOST_DATA_TEST_CASE (loop_protection_test , bdata:: random(bdata::seed=20,bdata::distribution=std::uniform_real_distribution<>(0.1_GeV, 0.5_GeV)))^bdata::random((bdata::seed=21,bdata::distribution=std::uniform_real_distribution<>(-M_PI, M_PI)))^bdata::random((bdata::seed=22,bdata::distribution=std::uniform_real_distribution<>(1.0, M_PI-1.0)))^bdata::random((bdata::seed=23,bdata::distribution=std::uniform_int_distribution<>(0, 1)))^bdata::random((bdata::seed=24,bdata::distribution=std::uniform_int_distribution<>(0, 100)))^bdata::xrange(ntests, pT , phi , theta , charge , time , index)
a covariance matrix to transport
Definition at line 266 of file ExtrapolatorTests.cpp.
View newest version in sPHENIX GitHub at line 266 of file ExtrapolatorTests.cpp
References Acts::units::_cm, Acts::units::_GeV, Acts::units::_mm, Acts::IntegrationTest::bField, charge, CHECK_CLOSE_REL, cos(), analysis::e, Acts::IntegrationTest::epropagator(), Acts::ConstantBField::getField(), M_PI, Acts::PropagatorOptions< action_list_t, aborter_list_t >::maxStepSize, mfContext, charm_jet_coverage::mom, eicpy.build::options, Acts::PropagatorOptions< action_list_t, aborter_list_t >::pathLimit, phi, pos, Acts::Propagator< stepper_t, navigator_t >::propagate(), ds::pT, analysis::status, Acts::tgContext, ds::theta, Acts::VectorHelpers::time(), nlohmann::detail::void(), x, analysis::y, and z.
Acts::Test::BOOST_DATA_TEST_CASE (cylinder_additive_ , bdata:: random(bdata::seed=0,bdata::distribution=std::uniform_real_distribution<>(0.4_GeV, 10_GeV)))^bdata::random((bdata::seed=1,bdata::distribution=std::uniform_real_distribution<>(-M_PI, M_PI)))^bdata::random((bdata::seed=2,bdata::distribution=std::uniform_real_distribution<>(1.0, M_PI-1.0)))^bdata::random((bdata::seed=3,bdata::distribution=std::uniform_int_distribution<>(0, 1)))^bdata::random((bdata::seed=4,bdata::distribution=std::uniform_int_distribution<>(0, 100)))^bdata::xrange(ntests, pT , phi , theta , charge , time , index)
a covariance matrix to transport
Definition at line 273 of file PropagatorTests.cpp.
View newest version in sPHENIX GitHub at line 273 of file PropagatorTests.cpp
References Acts::units::_cm, Acts::units::_GeV, Acts::units::_m, Acts::units::_mm, charge, CHECK_CLOSE_OR_SMALL, CHECK_CLOSE_REL, cos(), cSurface, analysis::e, Acts::IntegrationTest::epropagator(), Acts::PropagatorOptions< action_list_t, aborter_list_t >::maxStepSize, mfContext, charm_jet_coverage::mom, mSurface, Acts::PropagatorOptions< action_list_t, aborter_list_t >::pathLimit, phi, pos, Acts::Propagator< stepper_t, navigator_t >::propagate(), ds::pT, Acts::tgContext, ds::theta, Acts::VectorHelpers::time(), nlohmann::detail::void(), x, analysis::y, and z.
Acts::Test::BOOST_DATA_TEST_CASE (bound_to_perigee_test , bdata:: random(bdata::seed=3980,bdata::distribution=std::uniform_real_distribution<>(-10., 10.)))^bdata::random((bdata::seed=2221,bdata::distribution=std::uniform_real_distribution<>(-10., 10.)))^bdata::random((bdata::seed=2132,bdata::distribution=std::uniform_real_distribution<>(-10., 10.)))^bdata::random((bdata::seed=9183,bdata::distribution=std::uniform_real_distribution<>(0., 0.05)))^bdata::random((bdata::seed=3947,bdata::distribution=std::uniform_real_distribution<>(0., 0.05)))^bdata::xrange(100, x , y , z , a , b , index)
Unit test for parameters at the perigee.
Definition at line 331 of file BoundParametersTests.cpp.
View newest version in sPHENIX GitHub at line 331 of file BoundParametersTests.cpp
References a, b, consistencyCheck(), charm_jet_coverage::mom, Acts::SingleTrackParameters< ChargePolicy >::momentum(), pos, Acts::SingleTrackParameters< ChargePolicy >::position(), Acts::SingleBoundTrackParameters< ChargePolicy >::referenceSurface(), tgContext, transform, Acts::UnitConstants::u, nlohmann::detail::void(), x, analysis::y, and z.
Acts::Test::BOOST_DATA_TEST_CASE (bound_to_line_test , bdata:: random(bdata::seed=73980,bdata::distribution=std::uniform_real_distribution<>(-1000., 1000.)))^bdata::random((bdata::seed=21221,bdata::distribution=std::uniform_real_distribution<>(-1000., 1000.)))^bdata::random((bdata::seed=62992,bdata::distribution=std::uniform_real_distribution<>(-1000., 1000.)))^bdata::random((bdata::seed=900683,bdata::distribution=std::uniform_real_distribution<>(0., M_PI)))^bdata::random((bdata::seed=5439847,bdata::distribution=std::uniform_real_distribution<>(0., M_PI)))^bdata::random((bdata::seed=1972615,bdata::distribution=std::uniform_real_distribution<>(0., M_PI)))^bdata::xrange(100, x , y , z , a , b , c , index)
Unit test for parameters at a line.
Definition at line 399 of file BoundParametersTests.cpp.
View newest version in sPHENIX GitHub at line 399 of file BoundParametersTests.cpp
References Acts::units::_m, Acts::units::_mm, a, b, c, consistencyCheck(), charm_jet_coverage::mom, Acts::SingleTrackParameters< ChargePolicy >::momentum(), pos, Acts::SingleTrackParameters< ChargePolicy >::position(), Acts::SingleBoundTrackParameters< ChargePolicy >::referenceSurface(), tgContext, transform, Acts::UnitConstants::u, nlohmann::detail::void(), x, analysis::y, and z.
Acts::Test::BOOST_DATA_TEST_CASE (test_material_collector , bdata:: random(bdata::seed=20,bdata::distribution=std::uniform_real_distribution<>(0.5_GeV, 10_GeV)))^bdata::random((bdata::seed=21,bdata::distribution=std::uniform_real_distribution<>(-M_PI, M_PI)))^bdata::random((bdata::seed=22,bdata::distribution=std::uniform_real_distribution<>(1.0, M_PI-1.0)))^bdata::random((bdata::seed=23,bdata::distribution=std::uniform_int_distribution<>(0, 1)))^bdata::random((bdata::seed=24,bdata::distribution=std::uniform_int_distribution<>(0, 100)))^bdata::xrange(ntests, pT , phi , theta , charge , time , index)
Definition at line 434 of file MaterialCollectionTests.cpp.
View newest version in sPHENIX GitHub at line 434 of file MaterialCollectionTests.cpp
References charge, Acts::IntegrationTest::epropagator(), phi, ds::pT, runTest(), slpropagator(), ds::theta, and Acts::VectorHelpers::time().
Acts::Test::BOOST_FIXTURE_TEST_CASE (SurfaceArray_create , SurfaceArrayFixture)
Definition at line 182 of file SurfaceArrayTests.cpp.
View newest version in sPHENIX GitHub at line 182 of file SurfaceArrayTests.cpp
References Acts::SurfaceArray::at(), Acts::binR, Acts::SurfaceArray::SurfaceGridLookup< Axes >::completeBinning(), cos(), draw_surfaces(), Acts::SurfaceArray::SurfaceGridLookup< Axes >::fill(), M_PI, Acts::SurfaceArray::neighbors(), phi, pos, Acts::IntegrationTest::R, tgContext, Acts::SurfaceArray::toStream(), transform, Acts::UnitConstants::u, and Acts::unpack_shared_vector().
Acts::Test::BOOST_FIXTURE_TEST_CASE (LayerCreator_createCylinderLayer , LayerCreatorFixture)
Definition at line 236 of file LayerCreatorTests.cpp.
View newest version in sPHENIX GitHub at line 236 of file LayerCreatorTests.cpp
References CHECK_CLOSE_REL, draw_surfaces(), boost::dynamic_pointer_cast(), analysis::e, Acts::CylinderBounds::eHalfLengthZ, Acts::ProtoLayer::envR, Acts::ProtoLayer::envZ, Acts::equidistant, Acts::CylinderBounds::eR, Acts::CylinderBounds::get(), M_PI, Acts::ProtoLayer::minR, tgContext, and Acts::UnitConstants::u.
Acts::Test::BOOST_FIXTURE_TEST_CASE (SurfaceArrayCreator_createEquidistantAxis_Phi , SurfaceArrayCreatorFixture)
Definition at line 259 of file SurfaceArrayCreatorTests.cpp.
View newest version in sPHENIX GitHub at line 259 of file SurfaceArrayCreatorTests.cpp
References Acts::binPhi, CHECK_CLOSE_ABS, CHECK_CLOSE_REL, CHECK_SMALL, draw_surfaces(), analysis::e, Acts::equidistant, M_PI, phi, step(), tgContext, Acts::UnitConstants::u, Acts::unpack_shared_vector(), and z.
Acts::Test::BOOST_FIXTURE_TEST_CASE (LayerCreator_createDiscLayer , LayerCreatorFixture)
Definition at line 330 of file LayerCreatorTests.cpp.
View newest version in sPHENIX GitHub at line 330 of file LayerCreatorTests.cpp
References CHECK_CLOSE_REL, draw_surfaces(), boost::dynamic_pointer_cast(), analysis::e, Acts::ProtoLayer::envR, Acts::ProtoLayer::envZ, Acts::equidistant, M_PI, Acts::ProtoLayer::maxR, Acts::ProtoLayer::maxZ, Acts::ProtoLayer::minR, Acts::ProtoLayer::minZ, Acts::IntegrationTest::nBinsR, tgContext, and Acts::UnitConstants::u.
Acts::Test::BOOST_FIXTURE_TEST_CASE (LayerCreator_barrelStagger , LayerCreatorFixture)
Definition at line 420 of file LayerCreatorTests.cpp.
View newest version in sPHENIX GitHub at line 420 of file LayerCreatorTests.cpp
References Acts::binR, draw_surfaces(), boost::dynamic_pointer_cast(), Acts::ProtoLayer::envR, Acts::ProtoLayer::envZ, Acts::equidistant, Acts::SurfaceArray::getAxes(), M_PI, Acts::Layer::surfaceArray(), tgContext, and Acts::UnitConstants::u.
Acts::Test::BOOST_FIXTURE_TEST_CASE (SurfaceArrayCreator_createEquidistantAxis_Z , SurfaceArrayCreatorFixture)
Definition at line 437 of file SurfaceArrayCreatorTests.cpp.
View newest version in sPHENIX GitHub at line 437 of file SurfaceArrayCreatorTests.cpp
References Acts::binZ, CHECK_CLOSE_ABS, draw_surfaces(), analysis::e, Acts::equidistant, M_PI, tgContext, Acts::UnitConstants::u, and Acts::unpack_shared_vector().
Acts::Test::BOOST_FIXTURE_TEST_CASE (SurfaceArrayCreator_createEquidistantAxis_R , SurfaceArrayCreatorFixture)
Definition at line 489 of file SurfaceArrayCreatorTests.cpp.
View newest version in sPHENIX GitHub at line 489 of file SurfaceArrayCreatorTests.cpp
References Acts::binR, CHECK_CLOSE_ABS, CHECK_CLOSE_REL, draw_surfaces(), analysis::e, Acts::equidistant, Acts::VectorHelpers::perp(), tgContext, Acts::UnitConstants::u, and Acts::unpack_shared_vector().
Acts::Test::BOOST_FIXTURE_TEST_CASE (SurfaceArrayCreator_dependentBinCounts , SurfaceArrayCreatorFixture)
Definition at line 531 of file SurfaceArrayCreatorTests.cpp.
View newest version in sPHENIX GitHub at line 531 of file SurfaceArrayCreatorTests.cpp
References draw_surfaces(), Acts::equidistant, tgContext, and Acts::UnitConstants::u.
Acts::Test::BOOST_FIXTURE_TEST_CASE (SurfaceArrayCreator_completeBinning , SurfaceArrayCreatorFixture)
Definition at line 550 of file SurfaceArrayCreatorTests.cpp.
View newest version in sPHENIX GitHub at line 550 of file SurfaceArrayCreatorTests.cpp
References Acts::SurfaceArray::at(), Acts::binR, cos(), draw_surfaces(), Acts::SurfaceArray::SurfaceGridLookup< Axes >::fill(), M_PI, phi, pos, Acts::IntegrationTest::R, tgContext, Acts::UnitConstants::u, and Acts::unpack_shared_vector().
Acts::Test::BOOST_FIXTURE_TEST_CASE (SurfaceArrayCreator_barrelStagger , SurfaceArrayCreatorFixture)
Definition at line 587 of file SurfaceArrayCreatorTests.cpp.
View newest version in sPHENIX GitHub at line 587 of file SurfaceArrayCreatorTests.cpp
References Acts::SurfaceArray::at(), Acts::binPhi, Acts::binR, Acts::binZ, CHECK_CLOSE_ABS, cos(), draw_surfaces(), analysis::e, Acts::SurfaceArray::getAxes(), M_PI, phi, pos, Acts::IntegrationTest::R, tgContext, Acts::UnitConstants::u, and Acts::unpack_shared_vector().
CylindricalTrackingGeometry Acts::Test::cGeometry (tgContext)
template<typename T , typename U > boost::test_tools::predicate_result Acts::Test::checkCloseAbs (const T & val, const U & ref, double abstol)
Definition at line 239 of file FloatComparisons.hpp.
View newest version in sPHENIX GitHub at line 239 of file FloatComparisons.hpp
References Acts::Test::float_compare_internal::closeAbs(), and Acts::Test::float_compare_internal::compare().
Referenced by BOOST_AUTO_TEST_CASE().
template<typename Scalar , int dim> boost::test_tools::predicate_result Acts::Test::checkCloseCovariance (const ActsSymMatrix< Scalar, dim > & val, const ActsSymMatrix< Scalar, dim > & ref, double tol)
Definition at line 261 of file FloatComparisons.hpp.
View newest version in sPHENIX GitHub at line 261 of file FloatComparisons.hpp
References kdfinder::abs(), dim, and analysis::res.
template<typename T , typename U > boost::test_tools::predicate_result Acts::Test::checkCloseOrSmall (const T & val, const U & ref, double reltol, double small)
Definition at line 252 of file FloatComparisons.hpp.
View newest version in sPHENIX GitHub at line 252 of file FloatComparisons.hpp
References Acts::Test::float_compare_internal::closeOrSmall(), and Acts::Test::float_compare_internal::compare().
template<typename T , typename U > boost::test_tools::predicate_result Acts::Test::checkCloseRel (const T & val, const U & ref, double reltol)
Definition at line 232 of file FloatComparisons.hpp.
View newest version in sPHENIX GitHub at line 232 of file FloatComparisons.hpp
References Acts::Test::float_compare_internal::closeOrSmall(), and Acts::Test::float_compare_internal::compare().
Referenced by BOOST_AUTO_TEST_CASE().
template<typename T > boost::test_tools::predicate_result Acts::Test::checkSmall (const T & val, double small)
Definition at line 246 of file FloatComparisons.hpp.
View newest version in sPHENIX GitHub at line 246 of file FloatComparisons.hpp
References Acts::Test::float_compare_internal::closeOrSmall(), and Acts::Test::float_compare_internal::compare().
template<typename Parameter > void Acts::Test::consistencyCheck (const Parameter & pars, const Vector3D & position, const Vector3D & momentum, double charge, double time, std::array< double, eBoundParametersSize > values)
Definition at line 20 of file ParametersTestHelper.hpp.
View newest version in sPHENIX GitHub at line 20 of file ParametersTestHelper.hpp
References charge, CHECK_CLOSE_ABS, CHECK_CLOSE_REL, analysis::e, Acts::eLOC_0, Acts::eLOC_1, Acts::ePHI, Acts::eQOP, Acts::eT, Acts::eTHETA, momentum, Acts::VectorHelpers::position(), Acts::s_onSurfaceTolerance, and Acts::VectorHelpers::time().
Referenced by BOOST_AUTO_TEST_CASE(), and BOOST_DATA_TEST_CASE().
BoundToFreeMatrix Acts::Test::convertToMatrix (const std::array< double, 60 > P)
Helper method : convert into Acts matrix It takes the double array from AtlasStepper and transforms it into an ActsMatrixD
Parameters
P is the pointer to the array
Translation is (for lookup) /dL0 /dL1 /dPhi /dThe /dCM /dT X ->P[0] dX / P[ 8] P[16] P[24] P[32] P[40] P[48] Y ->P[1] dY / P[ 9] P[17] P[25] P[33] P[41] P[49] Z ->P[2] dZ / P[10] P[18] P[26] P[34] P[42] P[50] T ->P[3] dT/ P[11] P[19] P[27] P[35] P[43] P[51] Ax ->P[4] dAx/ P[12] P[20] P[28] P[36] P[44] P[52] Ay ->P[5] dAy/ P[13] P[21] P[29] P[37] P[45] P[53] Az ->P[6] dAz/ P[14] P[22] P[30] P[38] P[46] P[54] CM ->P[7] dCM/ P[15] P[23] P[31] P[39] P[47] P[55]
Definition at line 108 of file JacobianTests.cpp.
View newest version in sPHENIX GitHub at line 108 of file JacobianTests.cpp
References Acts::eBoundParametersSize, and Acts::eFreeParametersSize.
Referenced by testJacobianToGlobal().
std::shared_ptr<Transform3D> Acts::Test::createCylindricTransform (const Vector3D & nposition, double angleX, double angleY)
Helper method to create a transform for a plane to mimic detector situations, the plane is roughly perpendicular to the track
Parameters
nnomal The nominal normal direction
angleT Rotation around the norminal normal
angleU Roation around the original U axis
Definition at line 49 of file JacobianTests.cpp.
View newest version in sPHENIX GitHub at line 49 of file JacobianTests.cpp
std::shared_ptr<Transform3D> Acts::Test::createPlanarTransform (const Vector3D & nposition, const Vector3D & nnormal, double angleT, double angleU)
Helper method to create a transform for a plane to mimic detector situations, the plane is roughly perpendicular to the track
Parameters
nnomal The nominal normal direction
angleT Rotation around the norminal normal
angleU Roation around the original U axis
Definition at line 67 of file JacobianTests.cpp.
View newest version in sPHENIX GitHub at line 67 of file JacobianTests.cpp
References kdfinder::abs(), and T.
std::uniform_real_distribution Acts::Test::d0Dist (-0. 01_mm, 0. 01_mm)
Referenced by BOOST_AUTO_TEST_CASE(), and FW::ParametricProcessGenerator::operator()().
DirectPropagator Acts::Test::dpropagator (std:: movedstepper, std:: movednavigator)
Referenced by BOOST_DATA_TEST_CASE(), and BOOST_DATA_TEST_CASE().
void Acts::Test::draw_surfaces (const SrfVec & surfaces, const std::string & fname)
Definition at line 48 of file LayerCreatorTests.cpp.
View newest version in sPHENIX GitHub at line 48 of file LayerCreatorTests.cpp
References boost::dynamic_pointer_cast(), tgContext, and vtx().
Referenced by BOOST_FIXTURE_TEST_CASE().
void Acts::Test::draw_surfaces (SrfVec surfaces, const std::string & fname)
Definition at line 225 of file SurfaceArrayCreatorTests.cpp.
View newest version in sPHENIX GitHub at line 225 of file SurfaceArrayCreatorTests.cpp
References boost::dynamic_pointer_cast(), tgContext, and vtx().
void Acts::Test::dumpVertices (const RectangleBounds & r)
Definition at line 27 of file RectangleBoundsTests.cpp.
View newest version in sPHENIX GitHub at line 27 of file RectangleBoundsTests.cpp
References v, and Acts::RectangleBounds::vertices().
EigenPropagatorType Acts::Test::epropagator (std:: moveestepper, std:: movenavigator)
EigenPropagator Acts::Test::epropagator (std:: moveestepper, std:: movenavigatorES)
EigenPropagatorType Acts::Test::epropagator (std:: moveestepper)
EigenStepperType Acts::Test::estepper (bField)
Vector3D Acts::Test::eta0Position (0. 5, 1. 5, 0.)
Referenced by BOOST_AUTO_TEST_CASE().
std::uniform_real_distribution<double> Acts::Test::etaDist (- 4., 4.)
Referenced by BOOST_AUTO_TEST_CASE(), and FW::ParametricProcessGenerator::operator()().
std::normal_distribution< double > Acts::Test::gauss (0. , 1.)
Referenced by BOOST_AUTO_TEST_CASE(), FW::Contextual::AlignmentDecorator::decorate(), FW::HelloRandomAlgorithm::execute(), PHField2D::GetFieldCyl(), PHField3DCylindrical::GetFieldCyl(), Acts::Test::MeasurementCreator::operator()(), Acts::Test::MaterialScattering::operator()(), PHField2D::PHField2D(), PHField3DCylindrical::PHField3DCylindrical(), PHFieldCleo::PHFieldCleo(), PHField3DCylindrical::print_map(), and kdfinder::rnd_gauss().
std::default_random_engine Acts::Test::generator (42)
Referenced by erhic::EventFromAsciiFactory< T >::AddParticle(), BOOST_AUTO_TEST_CASE(), BOOST_DATA_TEST_CASE(), FluxMonitorGrid::FillOutHistograms(), ActsFatras::LandauDistribution::operator()(), Acts::Test::MeasurementCreator::operator()(), Acts::Test::MaterialScattering::operator()(), PHG4PileupGenerator::set_generator(), and ActsFatras::ParticleSimulator< propagator_t, physics_list_t, hit_surface_selector_t >::simulate().
std::vector<BoundParameters> Acts::Test::getAthenaTracks ()
Definition at line 27 of file AMVFTestData.ipp.
View newest version in sPHENIX GitHub at line 27 of file AMVFTestData.ipp
References Acts::units::_MeV, analysis::e, and gctx.
Referenced by BOOST_AUTO_TEST_CASE().
std::tuple<std::vector<const Volume*>, std::shared_ptr<TrackingGeometry> > Acts::Test::gridBoxFactory (size_t n = NBOXES, double hl = 1000, size_t octd = 5)
Definition at line 18 of file TrackingVolumeTests.cpp.
View newest version in sPHENIX GitHub at line 18 of file TrackingVolumeTests.cpp
template<typename surface_t > MicroBenchmarkResult Acts::Test::intersectionTest (const surface_t & surface, double phi, double theta)
Definition at line 76 of file SurfaceIntersectionBenchmark.cpp.
View newest version in sPHENIX GitHub at line 76 of file SurfaceIntersectionBenchmark.cpp
References boundaryCheck, cos(), microBenchmark(), nrepts, origin(), and Acts::tgContext.
Result<NoCopy> Acts::Test::make_nocopy (int i, bool v = true)
Definition at line 247 of file ResultTests.cpp.
View newest version in sPHENIX GitHub at line 247 of file ResultTests.cpp
References v.
Referenced by BOOST_AUTO_TEST_CASE().
CurvilinearParameters Acts::Test::make_params ()
Definition at line 34 of file MultiTrajectoryTests.cpp.
View newest version in sPHENIX GitHub at line 34 of file MultiTrajectoryTests.cpp
Referenced by make_rand_trackstate().
TrackState<SourceLink, CurvilinearParameters> Acts::Test::make_rand_trackstate ()
Definition at line 41 of file MultiTrajectoryTests.cpp.
View newest version in sPHENIX GitHub at line 41 of file MultiTrajectoryTests.cpp
References make_params().
Referenced by BOOST_AUTO_TEST_CASE().
auto Acts::Test::make_trackstate ()
Definition at line 50 of file MultiTrajectoryTests.cpp.
View newest version in sPHENIX GitHub at line 50 of file MultiTrajectoryTests.cpp
References Acts::UnitConstants::fm, gctx, Acts::Surface::getSharedPtr(), M_PI, Acts::PrimitivesVisualization::plane, and Acts::SingleBoundTrackParameters< ChargePolicy >::referenceSurface().
Referenced by BOOST_AUTO_TEST_CASE().
constexpr Material Acts::Test::makeBeryllium ()
Definition at line 21 of file PredefinedMaterials.hpp.
View newest version in sPHENIX GitHub at line 21 of file PredefinedMaterials.hpp
Referenced by BOOST_AUTO_TEST_CASE(), Acts::Test::CubicTrackingGeometry::CubicTrackingGeometry(), and Acts::Test::CylindricalTrackingGeometry::operator()().
MaterialProperties Acts::Test::makePercentSlab ()
Build material slab corresponding to 1% of radiation and interaction length.
Definition at line 39 of file PredefinedMaterials.hpp.
View newest version in sPHENIX GitHub at line 39 of file PredefinedMaterials.hpp
References makeUnitSlab().
Referenced by BOOST_AUTO_TEST_CASE().
constexpr Material Acts::Test::makeSilicon ()
Definition at line 26 of file PredefinedMaterials.hpp.
View newest version in sPHENIX GitHub at line 26 of file PredefinedMaterials.hpp
Referenced by BOOST_AUTO_TEST_CASE(), makeSiClassificationNumbers(), and Acts::Test::CylindricalTrackingGeometry::operator()().
MaterialProperties Acts::Test::makeUnitSlab ()
Build material slab corresponding to 1 radiation and interaction length.
Definition at line 32 of file PredefinedMaterials.hpp.
View newest version in sPHENIX GitHub at line 32 of file PredefinedMaterials.hpp
References Acts::units::_cm.
Referenced by BOOST_AUTO_TEST_CASE(), BOOST_DATA_TEST_CASE(), and makePercentSlab().
Acts::Test::METHOD_TRAIT (foo_method_t , foo)
Acts::Test::METHOD_TRAIT (bar_method_t , bar)
template<typename Callable > MicroBenchmarkResult Acts::Test::microBenchmark (Callable && iteration, size_t iters_per_run, size_t num_runs = 20000, std::chrono::milliseconds warmup_time = std::chrono::milliseconds(2000))
Definition at line 475 of file BenchmarkTools.hpp.
View newest version in sPHENIX GitHub at line 475 of file BenchmarkTools.hpp
References Acts::Test::benchmark_tools_internal::MicroBenchmarkIter< Callable, Input >::iter(), and Acts::Test::benchmark_tools_internal::microBenchmarkImpl().
Referenced by BOOST_AUTO_TEST_CASE(), intersectionTest(), and main().
template<typename Callable , typename Input > MicroBenchmarkResult Acts::Test::microBenchmark (Callable && iterationWithInput, const std::vector< Input > & inputs, size_t num_runs = 20000, std::chrono::milliseconds warmup_time = std::chrono::milliseconds(2000))
Definition at line 495 of file BenchmarkTools.hpp.
View newest version in sPHENIX GitHub at line 495 of file BenchmarkTools.hpp
References analysis::input, Acts::Test::benchmark_tools_internal::MicroBenchmarkIter< Callable, Input >::iter(), and Acts::Test::benchmark_tools_internal::microBenchmarkImpl().
Navigator Acts::Test::navigator (tGeometry)
std::uniform_int_distribution Acts::Test::nTracksDist (3 , 10)
Referenced by BOOST_AUTO_TEST_CASE().
std::uniform_int_distribution Acts::Test::nTracksDist (5 , 15)
std::uniform_int_distribution Acts::Test::nVertexDist (1 , 6)
Referenced by BOOST_AUTO_TEST_CASE().
Vector2D Acts::Test::offset (- 2., 2.)
Referenced by BOOST_AUTO_TEST_CASE(), and Acts::Test::MicroBenchmarkResult::runTimeQuartiles().
constexpr par_t Acts::Test::operator""_p (unsigned long long i)
Definition at line 82 of file FittableTypeTests.cpp.
View newest version in sPHENIX GitHub at line 82 of file FittableTypeTests.cpp
Vector3D Acts::Test::origin (0. , 0. , 0.)
Referenced by Acts::Test::Layers::BOOST_AUTO_TEST_CASE(), BOOST_AUTO_TEST_CASE(), PHG4EtaParameterization::ComputeTransformation(), PHG4EtaPhiParameterization::ComputeTransformation(), EicBeamLineElementMap::ConstructGeometry(), EicBeamLineElementGrad::ConstructGeometry(), PHG4BeamlineMagnetDetector::ConstructMe(), G4JLeicBeamLineMagnetDetector::ConstructMe(), BeamLineMagnetDetector::ConstructMe(), Acts::Polyhedron::extent(), EicCompositeShape::FillBuffer3D(), FairGeaneUtil::FromMARSToSDCoord(), FairGeaneUtil::FromSDToMARSCoord(), EicBeamLineElementMap::Initialize(), Acts::AxisAlignedBoundingBox< entity_t, value_t, DIM >::intersect(), intersectionTest(), FairGeanePro::Propagate(), and Acts::PrimitivesVisualization::test().
Vector3D Acts::Test::originStraw (0. 3_m, -0. 2_m, 11_m)
Vector3D Acts::Test::phi0Position (0. 5, 0. , 2. 5)
Referenced by BOOST_AUTO_TEST_CASE().
std::uniform_real_distribution Acts::Test::phiDist (- M_PI, M_PI)
Referenced by BOOST_AUTO_TEST_CASE(), main(), and FW::ParametricProcessGenerator::operator()().
Vector3D Acts::Test::phiPihPosition (0. , 1. 5, 2. 5)
Referenced by BOOST_AUTO_TEST_CASE().
std::uniform_real_distribution Acts::Test::pTDist (0. 4_GeV, 10. _GeV)
std::uniform_real_distribution Acts::Test::pTDist (1. _GeV, 30. _GeV)
Referenced by BOOST_AUTO_TEST_CASE().
std::uniform_real_distribution Acts::Test::pTDist (0. 4_GeV, 10_GeV)
std::uniform_real_distribution<double> Acts::Test::pTDist (0. 1_GeV, 100_GeV)
std::uniform_real_distribution Acts::Test::qDist (- 1, 1)
Referenced by BOOST_AUTO_TEST_CASE().
std::uniform_real_distribution Acts::Test::resAngDist (0. , 0. 1)
Referenced by BOOST_AUTO_TEST_CASE().
std::uniform_real_distribution Acts::Test::resIPDist (0. , 100. _um)
Referenced by BOOST_AUTO_TEST_CASE().
std::uniform_real_distribution Acts::Test::resIPDist (0. , 100_um)
std::uniform_real_distribution Acts::Test::resQoPDist (-0. 1, 0. 1)
Referenced by BOOST_AUTO_TEST_CASE().
Vector2D Acts::Test::rphiPosition (3. 5, M_PI/ 8.)
Referenced by BOOST_AUTO_TEST_CASE().
Vector2D Acts::Test::rphizPosition (0. 1, 2. 5)
Referenced by BOOST_AUTO_TEST_CASE().
ReferencePropagator Acts::Test::rpropagator (std:: moveestepper, std:: movenavigator)
Referenced by BOOST_DATA_TEST_CASE().
template<typename rpropagator_t , typename dpropagator_t > void Acts::Test::runTest (const rpropagator_t & rprop, const dpropagator_t & dprop, double pT, double phi, double theta, int charge, double time, int index)
The actual test nethod that runs the test can be used with several propagator types
Template Parameters
rpropagator_t is the reference propagator type
dpropagator_t is the direct propagator type
Parameters
rprop is the reference propagator instance
dprop is the direct propagator instance
pT the transverse momentum
phi the azimuthal angle of the track at creation
theta the polar angle of the track at creation
charge is the charge of the particle
index is the run index from the test
Definition at line 81 of file DirectNavigatorTests.cpp.
View newest version in sPHENIX GitHub at line 81 of file DirectNavigatorTests.cpp
References charge, CHECK_CLOSE_REL, cos(), Acts::Test::Options::debug, debugMode, analysis::e, mfContext, charm_jet_coverage::mom, oversteppingMaxStepSize, oversteppingTest, pos, referenceTiming, Acts::IntegrationTest::skip, Acts::tgContext, x, analysis::y, and z.
Referenced by BOOST_DATA_TEST_CASE().
template<typename propagator_t > void Acts::Test::runTest (const propagator_t & prop, double pT, double phi, double theta, int charge, double time, int index)
the actual test nethod that runs the test can be used with several propagator types
Template Parameters
propagator_t is the actual propagator type
Parameters
prop is the propagator instance
pT the transverse momentum
phi the azimuthal angle of the track at creation
theta the polar angle of the track at creation
charge is the charge of the particle
index is the run index from the test
Definition at line 86 of file MaterialCollectionTests.cpp.
View newest version in sPHENIX GitHub at line 86 of file MaterialCollectionTests.cpp
References Acts::units::_cm, Acts::units::_e, Acts::units::_GeV, Acts::units::_mm, Acts::backward, charge, CHECK_CLOSE_REL, cos(), Acts::Test::Options::debug, debugModeBwd, debugModeBwdStep, debugModeFwd, debugModeFwdStep, analysis::e, Acts::GeometryObject::geoID(), Acts::SingleTrackParameters< ChargePolicy >::get(), mfContext, charm_jet_coverage::mom, Acts::Test::Options::pathLimit, pos, Acts::SingleTrackParameters< ChargePolicy >::referenceSurface(), Acts::SingleCurvilinearTrackParameters< ChargePolicy >::referenceSurface(), Acts::IntegrationTest::skip, Acts::tgContext, value, Acts::GeometryID::value(), x, analysis::y, and z.
StraightLinePropagator Acts::Test::slpropagator (std:: moveslstepper, std:: movenavigatorSL)
Referenced by BOOST_DATA_TEST_CASE().
template<typename stepper_state_t > void Acts::Test::step (stepper_state_t & sstate)
Definition at line 214 of file NavigatorTests.cpp.
View newest version in sPHENIX GitHub at line 214 of file NavigatorTests.cpp
Referenced by BOOST_AUTO_TEST_CASE(), BOOST_DATA_TEST_CASE(), BOOST_FIXTURE_TEST_CASE(), checkExtrapolateBy(), convert_cell_list_to_mgrid(), Acts::SurfaceArrayCreator::createEquidistantAxis(), Acts::CylinderVolumeHelper::createGapTrackingVolume(), DoSmearStep(), EicToyModel::DrawAxisTicks(), EicToyModel::DrawColorLegend(), EtmVacuumChamber::DrawMe(), GFMaterialEffects::effects(), EicMoCaPoint::EicMoCaPoint(), genfit::RKTrackRep::extrapolateToLine(), RKTrackRep::extrapolateToLine(), RKTrackRep::extrapolateToPoint(), genfit::RKTrackRep::extrapToPoint(), genfit::TGeoMaterialInterface::findNextBoundary(), fullMaterial(), Acts::FsmwMode1dFinder::getMode(), genfit::GblFitter::getScattererFromMatList(), getScattererFromMatList(), gridBoxFactory(), main(), Acts::VolumeMaterialMapper::mapMaterialTrack(), genfit::MaterialEffects::momentumLoss(), genfit::MaterialEffects::noiseCoulomb(), FairRKPropagator::OneStepRungeKutta(), Acts::detail::SteppingLogger::operator()(), Process(), EicDetector::ProcessHits(), progressIndicator(), EtmAzimuthalScan::SetBfieldScanStep(), EicMoCaPoint::SetStep(), genfit::MaterialEffects::stepper(), vtx_builder(), FW::RootPropagationStepsWriter::writeT(), and FW::Obj::ObjPropagationStepsWriter< step_t >::writeT().
template<class BField_t > void Acts::Test::testInterfaceConsistency (const BField_t & field)
This is the canonical interface that all field implementations need to comply with. This test group is should include ALL field implementations, to make sure they conform to the interface, even if they are not implicitly tested by some of the other tests (e.g. Propagation) The function does not assert any functionality, it just ensures the interface compiles
Definition at line 41 of file MagneticFieldInterfaceConsistencyTests.cpp.
View newest version in sPHENIX GitHub at line 41 of file MagneticFieldInterfaceConsistencyTests.cpp
References mfContext, and pos.
Referenced by BOOST_AUTO_TEST_CASE().
template<typename Parameters > void Acts::Test::testJacobianToGlobal (const Parameters & pars)
Helper method : tests the jacobian to Global for a templated Parameters object
Template Parameters
Parameters the parameter type
Parameters
pars the parameter object
Definition at line 126 of file JacobianTests.cpp.
View newest version in sPHENIX GitHub at line 126 of file JacobianTests.cpp
References CHECK_CLOSE_OR_SMALL, convertToMatrix(), analysis::e, mfContext, Acts::AtlasStepper< bfield_t >::State::pVector, and Acts::tgContext.
Referenced by BOOST_AUTO_TEST_CASE().
static std::vector<std::string> Acts::Test::testObjString (const std::string & tString, bool triMesh = false) inline static
This is a test function that tests the validity of an obj stream It tests for special characters that are not allowed to be contained
It checks for:
Allowed as tags: mtllib, usemtl v, vn, vt, l, f, g, o, s comment lines (starting with #)
v, vn, vt are checked for 3 entries
f is checked for integer > 0 entries only
f is also check for being a triplet if triMesh is true
l is checked for integer > 0 entries only
Parameters
tString is the test string
triMesh ist he test if only triangular surfaces exist
Returns
a vector of failure messages
Definition at line 37 of file VisualizationTester.hpp.
View newest version in sPHENIX GitHub at line 37 of file VisualizationTester.hpp
References getline.
Referenced by BOOST_AUTO_TEST_CASE().
static std::vector<std::string> Acts::Test::testPlyString (const std::string & tString, bool triMesh = false) inline static
This is a test function that tests the validity of an obj stream It tests for special characters that are not allowed to be contained
It checks for:
Parameters
tString is the test string
triMesh ist he test if only triangular surfaces exist
Returns
a vector of failure messages
Definition at line 121 of file VisualizationTester.hpp.
View newest version in sPHENIX GitHub at line 121 of file VisualizationTester.hpp
References Acts::Test::PlyElement::copies, getline, name, Acts::Test::PlyElement::name, Acts::Test::PlyElement::properties, nlohmann::to_string(), and nlohmann::detail::void().
Referenced by BOOST_AUTO_TEST_CASE().
std::uniform_real_distribution Acts::Test::thetaDist (1. 0, M_PI-1. 0)
Referenced by BOOST_AUTO_TEST_CASE().
ActsVectorD<dim> Acts::Test::trafoGlobalToLocal (const Vector3D & global)
Definition at line 30 of file InterpolatedMaterialMapTests.cpp.
View newest version in sPHENIX GitHub at line 30 of file InterpolatedMaterialMapTests.cpp
Referenced by BOOST_AUTO_TEST_CASE().
Result<void> Acts::Test::void_res_func (int b)
Definition at line 283 of file ResultTests.cpp.
View newest version in sPHENIX GitHub at line 283 of file ResultTests.cpp
References nlohmann::detail::void().
Referenced by BOOST_AUTO_TEST_CASE().
std::uniform_real_distribution Acts::Test::vXYDist (-0. 1_mm, 0. 1_mm)
Referenced by BOOST_AUTO_TEST_CASE().
std::uniform_real_distribution Acts::Test::vZDist (- 20_mm, 20_mm)
Referenced by BOOST_AUTO_TEST_CASE().
BinningData Acts::Test::xData_add (open , binX , main_sstr , std:: movexData_sstr_add)
Referenced by BOOST_AUTO_TEST_CASE().
std::normal_distribution<double> Acts::Test::xdist (1_mm , 0. 1_mm)
Referenced by BOOST_AUTO_TEST_CASE().
Vector2D Acts::Test::xyPosition (0. 5, 1. 5)
Referenced by BOOST_AUTO_TEST_CASE().
Vector3D Acts::Test::xyzPosition (0. 5, 1. 5, 2. 5)
Referenced by BOOST_AUTO_TEST_CASE().
Vector3D Acts::Test::xyzPositionOutside (30. , - 30., 200.)
Referenced by BOOST_AUTO_TEST_CASE().
std::normal_distribution<double> Acts::Test::ydist (-0. 7_mm, 0. 1_mm)
Referenced by BOOST_AUTO_TEST_CASE().
std::uniform_real_distribution Acts::Test::z0Dist (-0. 2_mm, 0. 2_mm)
Referenced by BOOST_AUTO_TEST_CASE(), and FW::ParametricProcessGenerator::operator()().
std::normal_distribution<double> Acts::Test::z1dist (zVertexPos * 1_mm, 1_mm)
Referenced by BOOST_AUTO_TEST_CASE().
std::normal_distribution<double> Acts::Test::z2dist (- 3_mm, 0. 5_mm)
Referenced by BOOST_AUTO_TEST_CASE().
Variable Documentation
auto Acts::Test::aCylinder
Initial value:
= Surface::makeShared<CylinderSurface>(
    std::make_shared<Transform3D>(at), std::move(cb))
Definition at line 62 of file SurfaceIntersectionBenchmark.cpp.
View newest version in sPHENIX GitHub at line 62 of file SurfaceIntersectionBenchmark.cpp
Referenced by BOOST_AUTO_TEST_CASE(), and BOOST_DATA_TEST_CASE().
auto Acts::Test::aDisc
Initial value:
= Surface::makeShared<DiscSurface>(std::make_shared<Transform3D>(at),
                                              std::move(db))
Definition at line 57 of file SurfaceIntersectionBenchmark.cpp.
View newest version in sPHENIX GitHub at line 57 of file SurfaceIntersectionBenchmark.cpp
Referenced by BOOST_DATA_TEST_CASE().
auto Acts::Test::aPlane
Initial value:
= Surface::makeShared<PlaneSurface>(
    std::make_shared<Transform3D>(at), std::move(rb))
Definition at line 52 of file SurfaceIntersectionBenchmark.cpp.
View newest version in sPHENIX GitHub at line 52 of file SurfaceIntersectionBenchmark.cpp
Referenced by BOOST_AUTO_TEST_CASE(), BOOST_DATA_TEST_CASE(), GFAbsTrackRep::setFirstPlane(), and GFAbsTrackRep::setLastPlane().
auto Acts::Test::aStraw
Initial value:
= Surface::makeShared<StrawSurface>(
    std::make_shared<Transform3D>(at), 50_cm, 2_m)
Definition at line 66 of file SurfaceIntersectionBenchmark.cpp.
View newest version in sPHENIX GitHub at line 66 of file SurfaceIntersectionBenchmark.cpp
Referenced by BOOST_DATA_TEST_CASE().
Transform3D Acts::Test::at
Initial value:
= Transform3D::Identity() * Translation3D(0_m, 0_m, 10_m) *
                 AngleAxis3D(0.15, Vector3D(1.2, 1.2, 0.12).normalized())
Definition at line 47 of file SurfaceIntersectionBenchmark.cpp.
View newest version in sPHENIX GitHub at line 47 of file SurfaceIntersectionBenchmark.cpp
Referenced by Acts::TrackingVolume::glueTrackingVolume(), Acts::TrackingVolume::glueTrackingVolumes(), TowerBackgroundv1::identify(), FairRKPropagator::OneStepRungeKutta(), EicStlFactory::PreAllocateFacet(), DetermineTowerBackground::process_event(), and oncsSub_idtpcfeev2::tpc_decode().
Acts::Test::auto[volumes, tg] = gridBoxFactory()
Definition at line 78 of file TrackingVolumeTests.cpp.
View newest version in sPHENIX GitHub at line 78 of file TrackingVolumeTests.cpp
constexpr size_t Acts::Test::bench_iters = 1'000
Definition at line 161 of file BenchmarkTools.cpp.
View newest version in sPHENIX GitHub at line 161 of file BenchmarkTools.cpp
BFieldType Acts::Test::bField (0 , 0 , Bz)
Referenced by BOOST_AUTO_TEST_CASE().
const bool Acts::Test::boundaryCheck = false
Definition at line 36 of file SurfaceIntersectionBenchmark.cpp.
View newest version in sPHENIX GitHub at line 36 of file SurfaceIntersectionBenchmark.cpp
Referenced by Acts::CylinderSurface::intersect(), and intersectionTest().
const double Acts::Test::Bz = 2_T
Definition at line 52 of file DirectNavigatorTests.cpp.
View newest version in sPHENIX GitHub at line 52 of file DirectNavigatorTests.cpp
CalibrationContext Acts::Test::calContext = CalibrationContext()
Definition at line 72 of file KalmanFitterTests.cpp.
View newest version in sPHENIX GitHub at line 72 of file KalmanFitterTests.cpp
Referenced by BOOST_AUTO_TEST_CASE().
auto Acts::Test::cb = std::make_shared<CylinderBounds>(10_m, 100_m)
Definition at line 61 of file SurfaceIntersectionBenchmark.cpp.
View newest version in sPHENIX GitHub at line 61 of file SurfaceIntersectionBenchmark.cpp
Referenced by FairGeoTrap::calcVoluParam(), and nlohmann::basic_json::parse().
auto Acts::Test::cCylinder = std::make_shared<CylinderBounds>(150_mm, 1000_mm)
Definition at line 124 of file PropagatorTests.cpp.
View newest version in sPHENIX GitHub at line 124 of file PropagatorTests.cpp
CylindricalTrackingGeometry Acts::Test::cGeometry (tgContext)
Referenced by BOOST_AUTO_TEST_CASE().
ActsSymMatrixD< 1 > Acts::Test::cov1D
Definition at line 64 of file KalmanFitterTests.cpp.
View newest version in sPHENIX GitHub at line 64 of file KalmanFitterTests.cpp
Referenced by BOOST_AUTO_TEST_CASE(), and Acts::Test::MeasurementCreator::operator()().
ActsSymMatrixD< 2 > Acts::Test::cov2D
Definition at line 65 of file KalmanFitterTests.cpp.
View newest version in sPHENIX GitHub at line 65 of file KalmanFitterTests.cpp
Referenced by BOOST_AUTO_TEST_CASE(), and Acts::Test::MeasurementCreator::operator()().
auto Acts::Test::cSegmentation
Initial value:
=
    std::make_shared<const CartesianSegmentation>(moduleBounds, nbinsx, nbinsy)
Definition at line 41 of file PlanarModuleStepperTests.cpp.
View newest version in sPHENIX GitHub at line 41 of file PlanarModuleStepperTests.cpp
Referenced by BOOST_AUTO_TEST_CASE().
auto Acts::Test::cSurface = Surface::makeShared<CylinderSurface>(nullptr, cCylinder)
Definition at line 125 of file PropagatorTests.cpp.
View newest version in sPHENIX GitHub at line 125 of file PropagatorTests.cpp
Referenced by BOOST_AUTO_TEST_CASE(), BOOST_DATA_TEST_CASE(), Acts::CylinderVolumeHelper::glueTrackingVolumes(), and FW::Obj::ObjTrackingGeometryWriter::write().
auto Acts::Test::db = std::make_shared<RadialBounds>(0.2_m, 1.2_m)
Definition at line 56 of file SurfaceIntersectionBenchmark.cpp.
View newest version in sPHENIX GitHub at line 56 of file SurfaceIntersectionBenchmark.cpp
Referenced by BOOST_AUTO_TEST_CASE(), FairParTSQLIo::check(), HelixHough::fillBins(), photonNucleusCrossSection::photonFlux(), Process(), photonNucleusLuminosity::pttablegen(), and PndPidCorrelator::SetParContainers().
bool Acts::Test::debug = true
Definition at line 227 of file NavigatorTests.cpp.
View newest version in sPHENIX GitHub at line 227 of file NavigatorTests.cpp
bool Acts::Test::debugMode = false
Definition at line 67 of file KalmanFitterTests.cpp.
View newest version in sPHENIX GitHub at line 67 of file KalmanFitterTests.cpp
Referenced by BOOST_AUTO_TEST_CASE(), BOOST_DATA_TEST_CASE(), and runTest().
bool Acts::Test::debugModeBwd = false
Definition at line 71 of file MaterialCollectionTests.cpp.
View newest version in sPHENIX GitHub at line 71 of file MaterialCollectionTests.cpp
Referenced by runTest().
bool Acts::Test::debugModeBwdStep = false
Definition at line 73 of file MaterialCollectionTests.cpp.
View newest version in sPHENIX GitHub at line 73 of file MaterialCollectionTests.cpp
Referenced by runTest().
bool Acts::Test::debugModeFwd = false
Definition at line 70 of file MaterialCollectionTests.cpp.
View newest version in sPHENIX GitHub at line 70 of file MaterialCollectionTests.cpp
Referenced by runTest().
bool Acts::Test::debugModeFwdStep = false
Definition at line 72 of file MaterialCollectionTests.cpp.
View newest version in sPHENIX GitHub at line 72 of file MaterialCollectionTests.cpp
Referenced by runTest().
double Acts::Test::delta = 0.5
Definition at line 70 of file BinningDataTests.cpp.
View newest version in sPHENIX GitHub at line 70 of file BinningDataTests.cpp
Referenced by BOOST_AUTO_TEST_CASE().
constexpr unsigned int Acts::Test::dim = 2
Definition at line 26 of file InterpolatedMaterialMapTests.cpp.
View newest version in sPHENIX GitHub at line 26 of file InterpolatedMaterialMapTests.cpp
Referenced by EicGeoParData::AddLogicalVolumeGroup(), EtmPolygonGroup::AddPolygon(), EicGeoParData::AreNeighbours(), EicToyModel::Band(), BeastMagneticField::BeastMagneticField(), genfit::MeasuredStateOnPlane::blowUpCov(), BOOST_AUTO_TEST_CASE(), EtmDetector::BuildCADmodel(), checkCloseCovariance(), genfit::KalmanFitterInfo::checkConsistency(), nanoflann::KDTreeSingleIndexAdaptor< nanoflann::L2_Simple_Adaptor< double, kdfinder::KDPointCloud< double > >, kdfinder::KDPointCloud< double >, 3 >::computeBoundingBox(), nanoflann::KDTreeSingleIndexAdaptor< nanoflann::L2_Simple_Adaptor< double, kdfinder::KDPointCloud< double > >, kdfinder::KDPointCloud< double >, 3 >::computeInitialDistances(), genfit::GblFitter::constructGblInfo(), Smear::Acceptance::CustomCut::Contains(), convert_cell_list_to_mgrid(), Mgrid::cookSequentialFastInterpolation(), Mgrid::cookSequentialHighFitting(), create_element(), CreateBoundaryLayer(), CreateBoundaryLayerDivide(), CreateKnots(), nanoflann::KDTreeSingleIndexAdaptor< nanoflann::L2_Simple_Adaptor< double, kdfinder::KDPointCloud< double > >, kdfinder::KDPointCloud< double >, 3 >::divideTree(), EicToyModel::DrawAxisTicks(), EtmPolygonGroup::DrawPolygon(), EicToyModel::DrawPolygon(), EicHtcHit::EicHtcHit(), EicStlKey::EicStlKey(), genfit::eigenMatrixToRootMatrixSym(), GeaneTrackRep::extrapolateToPoint(), LSLTrackRep::extrapolateToPoint(), fill_lower_triangle(), MgridInterpolation::fillOkArray(), nanoflann::KDTreeSingleIndexAdaptor< nanoflann::L2_Simple_Adaptor< double, kdfinder::KDPointCloud< double > >, kdfinder::KDPointCloud< double >, 3 >::findNeighbors(), FindNewBoundaries(), FindPeriodicNodes(), genfit::KalmanFitterRefTrack::fitTrack(), genfit::GblFitterInfo::GblFitterInfo(), mesh_t::getDim(), EicToyModel::GetIntersection(), GFTrack::getResiduals(), PndGeoHandling::GetSensorDimensionsPath(), ImportMeshDefinition(), EicBeamLineElementMap::Initialize(), Mgrid::initializeAsSingleMgrid(), HtcKalmanFilter::InitializeMgridSlice(), InlineParameters(), mesh_t::isUndefined(), nanoflann::KDTreeSingleIndexAdaptor< nanoflann::L2_Simple_Adaptor< double, kdfinder::KDPointCloud< double > >, kdfinder::KDPointCloud< double >, 3 >::KDTreeSingleIndexAdaptor(), mesh_t::load(), LoadCGsimMesh(), LoadComsolMesh(), LoadElmergrid(), LoadFidapInput(), LoadGidInput(), LoadGmshInput1(), LoadGmshInput2(), nanoflann::KDTreeSingleIndexAdaptor< nanoflann::L2_Simple_Adaptor< double, kdfinder::KDPointCloud< double > >, kdfinder::KDPointCloud< double >, 3 >::loadIndex(), LoadMeditInput(), LoadTriangleInput(), LoadUniversalMesh(), Acts::make_octree(), nanoflann::KDTreeSingleIndexAdaptor< nanoflann::L2_Simple_Adaptor< double, kdfinder::KDPointCloud< double > >, kdfinder::KDPointCloud< double >, 3 >::middleSplit_(), Mgrid::multiAddrToLinear(), EtmDetector::PlaceG4Volume(), genfit::KalmanFitterRefTrack::processTrackPoint(), genfit::KalmanFitterRefTrack::processTrackPointSqrt(), genfit::GFGbl::processTrackWithRep(), ReorderFidapNodes(), ResolutionLevelPattern::ResolutionLevelPattern(), genfit::rootMatrixSymToEigenMatrix(), genfit::rootVectorToEigenVector(), SaveElmergrid(), nanoflann::KDTreeSingleIndexAdaptor< nanoflann::L2_Simple_Adaptor< double, kdfinder::KDPointCloud< double > >, kdfinder::KDPointCloud< double >, 3 >::saveIndex(), nanoflann::KDTreeSingleIndexAdaptor< nanoflann::L2_Simple_Adaptor< double, kdfinder::KDPointCloud< double > >, kdfinder::KDPointCloud< double >, 3 >::searchLevel(), PHG4Reco::set_field_map(), mesh_t::setDefaults(), mesh_t::setDim(), simulation(), SensitiveVolume::TrackToHitDistance(), nanoflann::KDTreeSingleIndexAdaptor< nanoflann::L2_Simple_Adaptor< double, kdfinder::KDPointCloud< double > >, kdfinder::KDPointCloud< double >, 3 >::veclen(), and Acts::visit_measurement().
DirectNavigator Acts::Test::dnavigator
Definition at line 45 of file DirectNavigatorTests.cpp.
View newest version in sPHENIX GitHub at line 45 of file DirectNavigatorTests.cpp
Stepper Acts::Test::dstepper(bField)
double Acts::Test::dX
Definition at line 171 of file KalmanFitterTests.cpp.
View newest version in sPHENIX GitHub at line 171 of file KalmanFitterTests.cpp
Referenced by kdfinder::CircleFit< T >::CircleFitByChernovHoussam().
double Acts::Test::dY
Definition at line 171 of file KalmanFitterTests.cpp.
View newest version in sPHENIX GitHub at line 171 of file KalmanFitterTests.cpp
Referenced by kdfinder::CircleFit< T >::CircleFitByChernovHoussam(), incoherentVMCrossSection::crossSectionCalculation(), wideResonanceCrossSection::crossSectionCalculation(), narrowResonanceCrossSection::crossSectionCalculation(), incoherentPhotonNucleusLuminosity::incoherentPhotonNucleusDifferentialLuminosity(), photonElectronLuminosity::photonNucleusDifferentialLuminosity(), photonNucleusLuminosity::photonNucleusDifferentialLuminosity(), Gammaavectormeson::pickwy(), photonNucleusLuminosity::pttablegen(), and Gammaavectormeson::vmpt().
constexpr float Acts::Test::eps = 1.0f / 255u
Definition at line 19 of file MaterialCompositionTests.cpp.
View newest version in sPHENIX GitHub at line 19 of file MaterialCompositionTests.cpp
Referenced by BOOST_AUTO_TEST_CASE(), and Acts::Test::CubicTrackingGeometry::operator()().
EigenStepperType Acts::Test::estepper (bField)
BinningData Acts::Test::etaData_eq(open, binEta, 5,-2.5, 2.5)
Referenced by BOOST_AUTO_TEST_CASE().
GeometryContext Acts::Test::gctx = GeometryContext()
Definition at line 28 of file MultiTrajectoryTests.cpp.
View newest version in sPHENIX GitHub at line 28 of file MultiTrajectoryTests.cpp
Referenced by BOOST_AUTO_TEST_CASE(), Acts::SurfaceArrayCreator::createEquidistantAxis(), Acts::LayerArrayCreator::createNavigationSurface(), Acts::SurfaceArrayCreator::createVariableAxis(), Acts::SurfaceArrayCreator::determineBinCount(), Acts::detail_lt::TrackStateProxy< source_link_t, N, M, ReadOnly >::filteredParameters(), getAthenaTracks(), make_trackstate(), Acts::detail_lt::TrackStateProxy< source_link_t, N, M, ReadOnly >::predictedParameters(), Acts::SingleCurvilinearTrackParameters< ChargePolicy >::set(), Acts::SingleBoundTrackParameters< ChargedPolicy >::set(), Acts::detail_lt::TrackStateProxy< source_link_t, N, M, ReadOnly >::smoothedParameters(), Acts::SurfaceArrayCreator::surfaceArrayOnDisc(), Acts::VolumeVisualization::test(), Acts::EventDataVisualization::test(), Acts::SurfaceVisualization::test(), FW::Contextual::AlignedDetectorElement::transform(), FW::Contextual::PayloadDetectorElement::transform(), Acts::Test::AlignableDetectorElement::transform(), and FW::RootTrajectoryWriter::writeT().
GeometryContext Acts::Test::geoContext = GeometryContext()
Definition at line 39 of file AdaptiveMultiVertexFinderTests.cpp.
View newest version in sPHENIX GitHub at line 39 of file AdaptiveMultiVertexFinderTests.cpp
Referenced by BOOST_AUTO_TEST_CASE(), Acts::AdaptiveMultiVertexFitter< input_track_t, linearizer_t >::doVertexSmoothing(), Acts::AdaptiveMultiVertexFitter< input_track_t, linearizer_t >::fitImpl(), main(), materialMappingExample(), and Acts::AtlasStepper< bfield_t >::State::State().
double Acts::Test::halfX = 5_mm
Definition at line 29 of file PlanarModuleStepperTests.cpp.
View newest version in sPHENIX GitHub at line 29 of file PlanarModuleStepperTests.cpp
Referenced by Acts::Test::Layers::BOOST_AUTO_TEST_CASE(), BOOST_AUTO_TEST_CASE(), Acts::RectangleBounds::m_max(), and PHG4mRICHDetector::LensPar::Set_halfXYZ().
double Acts::Test::halfY = 10_mm
Definition at line 30 of file PlanarModuleStepperTests.cpp.
View newest version in sPHENIX GitHub at line 30 of file PlanarModuleStepperTests.cpp
Referenced by Acts::Test::Layers::BOOST_AUTO_TEST_CASE(), BOOST_AUTO_TEST_CASE(), Acts::RectangleBounds::m_max(), and Acts::TrapezoidBounds::TrapezoidBounds().
BinningData Acts::Test::hData_eq(open, binH, 5, 0., 10.)
double Acts::Test::hThickness = 75_um
Definition at line 29 of file CartesianSegmentationTests.cpp.
View newest version in sPHENIX GitHub at line 29 of file CartesianSegmentationTests.cpp
Referenced by BOOST_AUTO_TEST_CASE(), and BOOST_DATA_TEST_CASE().
auto Acts::Test::hVolume
Initial value:
= constructContainerVolume(tgContext, iVolume, oVolume, oVvolumeR,
                                        oVvolumeHalfZ, "Container")
Definition at line 98 of file TrackingGeometryGeoIDTests.cpp.
View newest version in sPHENIX GitHub at line 98 of file TrackingGeometryGeoIDTests.cpp
Referenced by BOOST_AUTO_TEST_CASE(), Acts::constructContainerVolume(), and FW::RootMaterialWriter::write().
double Acts::Test::hx {10.}
Definition at line 21 of file CuboidVolumeBoundsTests.cpp.
View newest version in sPHENIX GitHub at line 21 of file CuboidVolumeBoundsTests.cpp
Referenced by BOOST_AUTO_TEST_CASE(), CbmRichRingFitterCircle::DoFit(), and CbmRichRingFitterQa::GenerateEllipse().
double Acts::Test::hy {20.}
Definition at line 21 of file CuboidVolumeBoundsTests.cpp.
View newest version in sPHENIX GitHub at line 21 of file CuboidVolumeBoundsTests.cpp
Referenced by BOOST_AUTO_TEST_CASE(), CbmRichRingFitterCircle::DoFit(), CbmRichRingFitterQa::GenerateEllipse(), and Acts::TrapezoidBounds::vertices().
double Acts::Test::hz {30.}
Definition at line 21 of file CuboidVolumeBoundsTests.cpp.
View newest version in sPHENIX GitHub at line 21 of file CuboidVolumeBoundsTests.cpp
Referenced by BOOST_AUTO_TEST_CASE(), TpcSpaceChargeReconstruction::calculate_distortions(), CbmRichGeoTest::DrawH3(), and EmptyDetector::finalize().
double Acts::Test::iiv_surfaceR = 25_mm
Definition at line 42 of file TrackingGeometryClosureTests.cpp.
View newest version in sPHENIX GitHub at line 42 of file TrackingGeometryClosureTests.cpp
double Acts::Test::iiv_volumeR
Initial value:
=
    iiv_surfaceR + 0.5 * surfaceRstagger + layerEnvelope + volumeEnvelope
Definition at line 43 of file TrackingGeometryClosureTests.cpp.
View newest version in sPHENIX GitHub at line 43 of file TrackingGeometryClosureTests.cpp
auto Acts::Test::iiVolume
Initial value:
= constructCylinderVolume(
    tgContext, surfaceHalfLengthZ, iiv_surfaceR, surfaceRstagger,
    surfaceZoverlap, layerEnvelope, volumeEnvelope, 0., iiv_volumeR,
    "InnerInnerVolume")
inner inner volume
Definition at line 52 of file TrackingGeometryClosureTests.cpp.
View newest version in sPHENIX GitHub at line 52 of file TrackingGeometryClosureTests.cpp
double Acts::Test::iov_surfaceR = 100_mm
inner outer volume defininitions
Definition at line 47 of file TrackingGeometryClosureTests.cpp.
View newest version in sPHENIX GitHub at line 47 of file TrackingGeometryClosureTests.cpp
double Acts::Test::iov_volumeR
Initial value:
=
    iov_surfaceR + 0.5 * surfaceRstagger + layerEnvelope + volumeEnvelope
Definition at line 48 of file TrackingGeometryClosureTests.cpp.
View newest version in sPHENIX GitHub at line 48 of file TrackingGeometryClosureTests.cpp
auto Acts::Test::ioVolume
Initial value:
= constructCylinderVolume(
    tgContext, surfaceHalfLengthZ, iov_surfaceR, surfaceRstagger,
    surfaceZoverlap, layerEnvelope, volumeEnvelope, iiv_volumeR, iov_volumeR,
    "InnerOuterVolume")
inner outer volume
Definition at line 57 of file TrackingGeometryClosureTests.cpp.
View newest version in sPHENIX GitHub at line 57 of file TrackingGeometryClosureTests.cpp
double Acts::Test::iVlayerEnvelope = 0.5_mm
Definition at line 30 of file TrackingGeometryGeoIDTests.cpp.
View newest version in sPHENIX GitHub at line 30 of file TrackingGeometryGeoIDTests.cpp
auto Acts::Test::iVolume
Initial value:
= constructContainerVolume(
    tgContext, iiVolume, ioVolume, iov_volumeR, volumeHalfZ, "InnerVolume")
the inner volume
inner volume
Definition at line 66 of file TrackingGeometryClosureTests.cpp.
View newest version in sPHENIX GitHub at line 66 of file TrackingGeometryClosureTests.cpp
Referenced by BOOST_AUTO_TEST_CASE(), and Acts::constructContainerVolume().
double Acts::Test::iVsurfaceHalfLengthZ = 50_mm
create three cylinder surfaces the surface radius (will also be the layer radius)
Definition at line 26 of file TrackingGeometryGeoIDTests.cpp.
View newest version in sPHENIX GitHub at line 26 of file TrackingGeometryGeoIDTests.cpp
double Acts::Test::iVsurfaceR = 25_mm
Definition at line 27 of file TrackingGeometryGeoIDTests.cpp.
View newest version in sPHENIX GitHub at line 27 of file TrackingGeometryGeoIDTests.cpp
double Acts::Test::iVsurfaceRstagger = 5_mm
Definition at line 28 of file TrackingGeometryGeoIDTests.cpp.
View newest version in sPHENIX GitHub at line 28 of file TrackingGeometryGeoIDTests.cpp
double Acts::Test::iVsurfaceZoverlap = 10_mm
Definition at line 29 of file TrackingGeometryGeoIDTests.cpp.
View newest version in sPHENIX GitHub at line 29 of file TrackingGeometryGeoIDTests.cpp
double Acts::Test::iVvolumeEnvelope = 10_mm
Definition at line 31 of file TrackingGeometryGeoIDTests.cpp.
View newest version in sPHENIX GitHub at line 31 of file TrackingGeometryGeoIDTests.cpp
double Acts::Test::iVvolumeR
Initial value:
=
    iVsurfaceR + 0.5 * iVsurfaceRstagger + iVlayerEnvelope + iVvolumeEnvelope
Definition at line 32 of file TrackingGeometryGeoIDTests.cpp.
View newest version in sPHENIX GitHub at line 32 of file TrackingGeometryGeoIDTests.cpp
double Acts::Test::lAngle = 0.1
Definition at line 30 of file CartesianSegmentationTests.cpp.
View newest version in sPHENIX GitHub at line 30 of file CartesianSegmentationTests.cpp
Referenced by BOOST_AUTO_TEST_CASE().
double Acts::Test::layerEnvelope = 0.5_mm
Definition at line 38 of file TrackingGeometryClosureTests.cpp.
View newest version in sPHENIX GitHub at line 38 of file TrackingGeometryClosureTests.cpp
MagneticFieldContext Acts::Test::magFieldContext = MagneticFieldContext()
Definition at line 40 of file AdaptiveMultiVertexFinderTests.cpp.
View newest version in sPHENIX GitHub at line 40 of file AdaptiveMultiVertexFinderTests.cpp
Referenced by BOOST_AUTO_TEST_CASE(), and main().
std::vector<float> Acts::Test::main_sstr = {0., 3., 4., 5.}
additive
Definition at line 81 of file BinningDataTests.cpp.
View newest version in sPHENIX GitHub at line 81 of file BinningDataTests.cpp
double Acts::Test::maxPhi = 1.33970
Definition at line 31 of file AnnulusBoundsTests.cpp.
View newest version in sPHENIX GitHub at line 31 of file AnnulusBoundsTests.cpp
Referenced by Acts::adjustBinUtility(), BOOST_AUTO_TEST_CASE(), and Acts::SurfaceArrayCreator::createVariableAxis().
double Acts::Test::maxRadius = 12.0
Definition at line 29 of file AnnulusBoundsTests.cpp.
View newest version in sPHENIX GitHub at line 29 of file AnnulusBoundsTests.cpp
Referenced by BOOST_AUTO_TEST_CASE(), and GemGeoParData::ConstructGeometry().
auto Acts::Test::mCylinder = std::make_shared<CylinderBounds>(10_mm, 1000_mm)
Definition at line 122 of file PropagatorTests.cpp.
View newest version in sPHENIX GitHub at line 122 of file PropagatorTests.cpp
MagneticFieldContext Acts::Test::mfContext = MagneticFieldContext()
Definition at line 71 of file KalmanFitterTests.cpp.
View newest version in sPHENIX GitHub at line 71 of file KalmanFitterTests.cpp
Referenced by BOOST_AUTO_TEST_CASE(), and testInterfaceConsistency().
double Acts::Test::minPhi = 0.74195
Definition at line 30 of file AnnulusBoundsTests.cpp.
View newest version in sPHENIX GitHub at line 30 of file AnnulusBoundsTests.cpp
Referenced by Acts::adjustBinUtility(), BOOST_AUTO_TEST_CASE(), FW::Generic::modulePositionsCylinder(), Acts::Test::CylindricalTrackingGeometry::modulePositionsCylinder(), FW::Generic::modulePositionsRing(), and FW::RootBFieldWriter< bfield_t >::run().
double Acts::Test::minRadius = 7.2
Definition at line 28 of file AnnulusBoundsTests.cpp.
View newest version in sPHENIX GitHub at line 28 of file AnnulusBoundsTests.cpp
Referenced by BOOST_AUTO_TEST_CASE(), GemGeoParData::ConstructGeometry(), and create_element().
auto Acts::Test::moduleBounds = std::make_shared<const RectangleBounds>(5_mm, 10_mm)
Definition at line 33 of file CartesianSegmentationTests.cpp.
View newest version in sPHENIX GitHub at line 33 of file CartesianSegmentationTests.cpp
Referenced by FW::Generic::ProtoLayerCreatorT< detector_element_t >::centralProtoLayers(), FW::Generic::ProtoLayerCreatorT< detector_element_t >::createProtoLayers(), and Acts::CartesianSegmentation::createSegmentationSurfaces().
auto Acts::Test::mSurface = Surface::makeShared<CylinderSurface>(nullptr, mCylinder)
Definition at line 123 of file PropagatorTests.cpp.
View newest version in sPHENIX GitHub at line 123 of file PropagatorTests.cpp
Referenced by BOOST_DATA_TEST_CASE(), Acts::SurfaceMaterialMapper::mapMaterialTrack(), and Acts::xmlToProtoSurfaceMaterial().
Navigator Acts::Test::navigator(tGeometry) (tGeometry)
Referenced by BOOST_AUTO_TEST_CASE(), BOOST_DATA_TEST_CASE(), FW::FittingAlgorithm::makeFitterFunction(), materialMappingExample(), and propagationExample().
Navigator Acts::Test::navigatorES(tGeometry)
Navigator Acts::Test::navigatorSL(tGeometry)
size_t Acts::Test::nBins_binary = 59
Definition at line 67 of file BinningDataTests.cpp.
View newest version in sPHENIX GitHub at line 67 of file BinningDataTests.cpp
Referenced by BOOST_AUTO_TEST_CASE().
size_t Acts::Test::nbinsx = 100
Definition at line 27 of file CartesianSegmentationTests.cpp.
View newest version in sPHENIX GitHub at line 27 of file CartesianSegmentationTests.cpp
Referenced by BOOST_AUTO_TEST_CASE().
size_t Acts::Test::nbinsy = 200
Definition at line 28 of file CartesianSegmentationTests.cpp.
View newest version in sPHENIX GitHub at line 28 of file CartesianSegmentationTests.cpp
Referenced by BOOST_AUTO_TEST_CASE().
DigitizationModule Acts::Test::ndModule(cSegmentation, hThickness,-1, lAngle, 0., true)
unsigned int Acts::Test::nrepts = 2000
Definition at line 35 of file SurfaceIntersectionBenchmark.cpp.
View newest version in sPHENIX GitHub at line 35 of file SurfaceIntersectionBenchmark.cpp
Referenced by intersectionTest().
size_t Acts::Test::ntests = 10
Definition at line 34 of file SurfaceIntersectionBenchmark.cpp.
View newest version in sPHENIX GitHub at line 34 of file SurfaceIntersectionBenchmark.cpp
double Acts::Test::ov_surfaceR = 150_mm
Definition at line 70 of file TrackingGeometryClosureTests.cpp.
View newest version in sPHENIX GitHub at line 70 of file TrackingGeometryClosureTests.cpp
double Acts::Test::ov_volumeR
Initial value:
=
    ov_surfaceR + 0.5 * surfaceRstagger + layerEnvelope + volumeEnvelope
Definition at line 71 of file TrackingGeometryClosureTests.cpp.
View newest version in sPHENIX GitHub at line 71 of file TrackingGeometryClosureTests.cpp
double Acts::Test::oversteppingMaxStepSize = 1_mm
Definition at line 65 of file DirectNavigatorTests.cpp.
View newest version in sPHENIX GitHub at line 65 of file DirectNavigatorTests.cpp
Referenced by runTest().
bool Acts::Test::oversteppingTest = false
Definition at line 64 of file DirectNavigatorTests.cpp.
View newest version in sPHENIX GitHub at line 64 of file DirectNavigatorTests.cpp
Referenced by runTest().
double Acts::Test::oVlayerEnvelope = 0.5_mm
Definition at line 40 of file TrackingGeometryGeoIDTests.cpp.
View newest version in sPHENIX GitHub at line 40 of file TrackingGeometryGeoIDTests.cpp
auto Acts::Test::oVolume
Initial value:
= constructCylinderVolume(
    tgContext, surfaceHalfLengthZ, ov_surfaceR, surfaceRstagger,
    surfaceZoverlap, layerEnvelope, volumeEnvelope, iov_volumeR, ov_volumeR,
    "OuterVolume")
inner outer volume
outer volume
Definition at line 75 of file TrackingGeometryClosureTests.cpp.
View newest version in sPHENIX GitHub at line 75 of file TrackingGeometryClosureTests.cpp
Referenced by BOOST_AUTO_TEST_CASE(), and Acts::constructContainerVolume().
double Acts::Test::oVsurfaceHalfLengthZ = 50_mm
the surface radius (will also be the layer radius)
Definition at line 36 of file TrackingGeometryGeoIDTests.cpp.
View newest version in sPHENIX GitHub at line 36 of file TrackingGeometryGeoIDTests.cpp
double Acts::Test::oVsurfaceR = 100_mm
Definition at line 37 of file TrackingGeometryGeoIDTests.cpp.
View newest version in sPHENIX GitHub at line 37 of file TrackingGeometryGeoIDTests.cpp
double Acts::Test::oVsurfaceRstagger = 5_mm
Definition at line 38 of file TrackingGeometryGeoIDTests.cpp.
View newest version in sPHENIX GitHub at line 38 of file TrackingGeometryGeoIDTests.cpp
double Acts::Test::oVsurfaceZoverlap = 10_mm
Definition at line 39 of file TrackingGeometryGeoIDTests.cpp.
View newest version in sPHENIX GitHub at line 39 of file TrackingGeometryGeoIDTests.cpp
double Acts::Test::oVvolumeEnvelope = 10_mm
Definition at line 41 of file TrackingGeometryGeoIDTests.cpp.
View newest version in sPHENIX GitHub at line 41 of file TrackingGeometryGeoIDTests.cpp
double Acts::Test::oVvolumeHalfZ
Initial value:
=
    (4 * oVsurfaceHalfLengthZ - oVsurfaceZoverlap) + oVvolumeEnvelope
Definition at line 95 of file TrackingGeometryGeoIDTests.cpp.
View newest version in sPHENIX GitHub at line 95 of file TrackingGeometryGeoIDTests.cpp
double Acts::Test::oVvolumeR
Initial value:
=
    oVsurfaceR + 0.5 * oVsurfaceRstagger + oVlayerEnvelope + oVvolumeEnvelope
Definition at line 42 of file TrackingGeometryGeoIDTests.cpp.
View newest version in sPHENIX GitHub at line 42 of file TrackingGeometryGeoIDTests.cpp
DigitizationModule Acts::Test::pdModule(cSegmentation, hThickness, 1, lAngle, 0., true)
BinningData Acts::Test::phiData_arb(closed, binPhi, phiValues)
Referenced by BOOST_AUTO_TEST_CASE().
BinningData Acts::Test::phiData_eq(closed, binPhi, 5,-M_PI, M_PI)
Referenced by BOOST_AUTO_TEST_CASE().
double Acts::Test::phiDelta = 0.1064
Definition at line 71 of file BinningDataTests.cpp.
View newest version in sPHENIX GitHub at line 71 of file BinningDataTests.cpp
Referenced by BOOST_AUTO_TEST_CASE().
double Acts::Test::phiMin = -M_PI
Definition at line 69 of file BinningDataTests.cpp.
View newest version in sPHENIX GitHub at line 69 of file BinningDataTests.cpp
Referenced by Acts::BinnedSPGroup< external_spacepoint_t >::BinnedSPGroup(), BOOST_AUTO_TEST_CASE(), Acts::TGeoDetectorElement::construct(), FairTrajFilter::SetMomentumCutP(), and Acts::AnnulusBounds::toStream().
std::vector<float> Acts::Test::phiValues = {-M_PI, -2., -1., 1., 2., M_PI}
Definition at line 62 of file BinningDataTests.cpp.
View newest version in sPHENIX GitHub at line 62 of file BinningDataTests.cpp
PlanarModuleStepper Acts::Test::pmStepper
The Planar module stepper.
Definition at line 53 of file PlanarModuleStepperTests.cpp.
View newest version in sPHENIX GitHub at line 53 of file PlanarModuleStepperTests.cpp
Referenced by BOOST_DATA_TEST_CASE().
Vector3D Acts::Test::pos
Definition at line 172 of file KalmanFitterTests.cpp.
View newest version in sPHENIX GitHub at line 172 of file KalmanFitterTests.cpp
Referenced by PHG4GDMLWriteStructure::AddVolumeAuxiliary(), analysis(), dfe::FlatSet< T, Compare, Container >::at(), PHG4GDMLWriteSolids::BooleanWrite(), BOOST_AUTO_TEST_CASE(), Acts::Test::Layers::BOOST_AUTO_TEST_CASE(), BOOST_DATA_TEST_CASE(), Acts::IntegrationTest::BOOST_DATA_TEST_CASE(), BOOST_FIXTURE_TEST_CASE(), PHG4mRICHDetector::build_mRICH_sector(), PHG4mRICHDetector::build_mRICH_wall_eside(), PHG4mRICHDetector::build_mRICH_wall_hside(), ActsTransformations::calculateDCA(), ActsEvaluator::calculateDCA(), checkErrorPropagation(), checkExtrapolateBy(), checkExtrapolateToCylinder(), checkExtrapolateToLine(), checkExtrapolateToPoint(), checkExtrapolateToSphere(), checkSetGetPosMom(), checkStopAtBoundary(), compareForthBackExtrapolation(), compareForthBackJacNoise(), Acts::IntegrationTest::constant_field_propagation(), Acts::IntegrationTest::covariance_bound(), Acts::IntegrationTest::covariance_curvilinear(), Acts::createGrid2D(), Acts::createGrid3D(), FairGeoRootBuilder::createNode(), KFParticle_DST::createParticleNode(), oncsSub_idcaenv1742::decode(), oncsSub_idfnalmwpc::decode(), oncsSub_idfnalmwpcv2::decode(), Packet_hbd_fpgashort::decode(), Packet_hbd_fpga::decode(), CbmRichTrackExtrapolationIdeal::DoExtrapolation(), CbmRichTrackExtrapolationKF::DoExtrapolation(), CbmRichTrackExtrapolationMirrorIdeal::DoExtrapolation(), Fun4AllHistoManager::dumpHistos(), dfe::SmallVector< T, N, Allocator >::emplace(), FairMCTracks::Exec(), FairMCStack::Exec(), PndRecoKalmanTask::Exec(), FW::HitSmearing::execute(), FW::ParticleSmearing::execute(), ExitWindowV2::ExitWindowV2(), PHTpcEventExporter::exportEvent(), GeaneTrackRep::extrapolate(), genfit::RKTrackRep::extrapolateBy(), genfit::RKTrackRep::extrapolateToCone(), genfit::RKTrackRep::extrapolateToCylinder(), genfit::RKTrackRep::extrapolateToSphere(), Acts::fieldMapperRZ(), Acts::fieldMapperXYZ(), Fill(), Acts::SurfaceArray::SurfaceGridLookup< Axes >::fill(), HelixHough::fillBins(), GFTrack::fillGeoTrack(), SvtxEvaluator::fillOutputNtuples(), KFParticle_DST::fillParticleNode_Particle(), KFParticle_DST::fillParticleNode_Track(), dfe::FlatSet< T, Compare, Container >::find(), kdfinder::find_vertex_seeds(), findByPdg(), sPHENIXTracker::findHelicesParallelOneHelicity(), sPHENIXSeedFinder::findHelicesParallelOneHelicity(), PHG4GDMLWriteStructure::FindOpticalSurface(), PHTpcTrackFollower::followTrack(), Acts::IntegrationTest::foward_backward(), Fun4All_AnaTutorial(), Fun4All_AnaTutorial_Jets(), Fun4All_G4_Babar(), Fun4All_G4_Beast(), Fun4All_G4_Cleo(), Fun4All_G4_EICDetector(), Fun4All_G4_fsPHENIX(), Fun4All_G4_FullDetectorModular(), Fun4All_G4_FullDetectorModularBeast(), Fun4All_G4_JLeic(), Fun4All_G4_LBLDetector(), Fun4All_G4_sPHENIX(), genfit::AbsTrackRep::get6DState(), genfit::AbsTrackRep::get6DStateCov(), PHTpcTrackFollower::get_projected_coordinate(), PHTpcTrackFollower::get_track_layer(), GFTools::getBiasedSmoothedPos(), GFTools::getBiasedSmoothedPosXYZ(), Acts::SurfaceArray::SurfaceGridLookup< Axes >::getBinCenterImpl(), PHG4GDMLWriteStructure::GetBorderSurface(), getClassMethod__(), erhic::FileFactory::GetFile(), LSLTrackRep::getGlobal(), MakeActsGeometry::getInttKeyFromNode(), FairMultiLinkedData::GetLink(), MakeActsGeometry::getMvtxKeyFromNode(), PndPidCandidate::GetNearestParameterization(), FairLogger::GetOutputStream(), genfit::HelixTrackModel::getPos(), PHG4GDMLWriteStructure::GetSkinSurface(), GFTools::getSmoothedChiSqu(), GFTools::getSmoothedPos(), GFTools::getSmoothedPosXYZ(), FairDbSqlValPacket::GetStmtValues(), PndStringSeparator::GetString(), GFPointPath::GFPointPath(), genfit::GFTrackToTrack(), Acts::globalToLocalFromBin(), gridBoxFactory(), PHTpcTrackFollower::hit_to_measurement(), Initialise_info(), FairDetector::Initialize(), KFParticle_nTuple::initializeBranches(), dfe::FlatSet< T, Compare, Container >::insert_or_assign(), PHPointerList< T >::insertAt(), AllSiliconTrackerDetector::InsertVolumes(), genfit::GFRaveMagneticField::inTesla(), main(), genfit::EventDisplay::makeLines(), PHGenFitTrkFitter::MakeSvtxTrack(), PHG4TrackFastSim::MakeSvtxTrack(), Acts::materialMapperRZ(), Acts::materialMapperXYZ(), oncsSub_idmvtxv0::mvtx_decode(), oncsSub_idmvtxv1::mvtx_decode(), FW::Options::operator>>(), PHGenFitTrkProp::OutputPHGenFitTrack(), inputParser::parseString(), PHG4TrackFastSim::PHG4HitToMeasurementCylinder(), PHG4TrackFastSim::PHG4HitToMeasurementVerticalPlane(), PHG4GDMLWriteStructure::PhysvolWrite(), Piston(), FW::HepMC3Vertex::position(), genfit::KalmanFitterRefTrack::prepareTrack(), Fun4AllServer::Print(), genfit::MeasuredStateOnPlane::Print(), genfit::StateOnPlane::Print(), KFParticle_DST::printNode(), PHTruthVertexing::Process(), PHTpcTracker::Process(), PHGenFitTrackProjection::process_event(), PHG4TrackFastSim::process_event(), genfit::KalmanFitter::processTrackPartially(), genfit::KalmanFitterRefTrack::processTrackPoint(), genfit::KalmanFitterRefTrack::processTrackPointSqrt(), genfit::KalmanFitter::processTrackWithRep(), FW::CsvPlanarClusterReader::read(), dfe::io_dsv_impl::DsvReader< Delimiter >::read(), tetgenmesh::recoveredgebyflips(), PHGenFitTrkProp::ReFitTrack(), PHGenFitTrkFitter::ReFitTrack(), Fun4AllHistoManager::registerHisto(), nlohmann::json_pointer< BasicJsonType >::replace_substring(), RKTrackRep::RKTrackRep(), runTest(), tetgenmesh::scoutsegment(), CbmMCEntry::SetPos(), GFPointPath::setPos(), genfit::RKTrackRep::setPosMomCov(), FW::HepMC3Event::shiftPositionTo(), Acts::solenoidFieldMapper(), nlohmann::json_pointer< BasicJsonType >::split(), Acts::AtlasStepper< bfield_t >::State::State(), Acts::EigenStepper< bfield_t, extensionlist_t, auctioneer_t >::State::State(), Acts::AtlasStepper< ConstantBField >::step(), Acts::SurfaceArrayCreator::surfaceArrayOnCylinder(), Acts::SurfaceArrayCreator::surfaceArrayOnDisc(), Acts::SurfaceArrayCreator::surfaceArrayOnPlane(), PHG4GDMLWriteStructure::SurfacesWrite(), PHGenFitTrkProp::SvtxTrackToPHGenFitTracks(), remote_msg_buffer::sync(), testInterfaceConsistency(), Acts::IntegrationTest::to_cylinder(), Acts::IntegrationTest::to_surface(), PHGenFitTrkProp::TrackPropPatRec(), PHRaveVertexing::TranslateSvtxToGenFitTrack(), tetgenmesh::tri_edge_inter_tail(), triplet_rejection(), sPHENIXTrackerTpc::tripletRejection(), sPHENIXTracker::tripletRejection(), sPHENIXSeedFinder::tripletRejection(), PHGenFitTrkProp::TrkrClusterToPHGenFitMeasurement(), Acts::AtlasStepper< ConstantBField >::update(), PHActsVertexFinder::updateTrackDCA(), PHG4TrackFastSim::VertexMeasurement(), and FW::RootPlanarClusterWriter::writeT().
auto Acts::Test::rb = std::make_shared<RectangleBounds>(1_m, 1_m)
Definition at line 51 of file SurfaceIntersectionBenchmark.cpp.
View newest version in sPHENIX GitHub at line 51 of file SurfaceIntersectionBenchmark.cpp
Referenced by Acts::Legacy::AtlasSeedfinder< SpacePoint >::production3Sp().
BinningData Acts::Test::rData_eq(open, binR, 10, 0., 10.)
Referenced by BOOST_AUTO_TEST_CASE().
bool Acts::Test::referenceTiming = false
Definition at line 63 of file DirectNavigatorTests.cpp.
View newest version in sPHENIX GitHub at line 63 of file DirectNavigatorTests.cpp
Referenced by runTest().
BinningData Acts::Test::rPhiData_eq(closed, binRPhi, 5,-M_PI, M_PI)
double Acts::Test::sguardX = 2 * hThickness * abs(tanAlpha)
Definition at line 37 of file PlanarModuleStepperTests.cpp.
View newest version in sPHENIX GitHub at line 37 of file PlanarModuleStepperTests.cpp
template<typename P , typename S , typename... As> constexpr bool Acts::Test::signature_check
Initial value:
=
    detail::all_of_v<concept ::abort_condition_signature_check_v<As, P, S>...>
Definition at line 208 of file AbortListTests.cpp.
View newest version in sPHENIX GitHub at line 208 of file AbortListTests.cpp
Referenced by BOOST_AUTO_TEST_CASE().
const int Acts::Test::skip = 0
Definition at line 61 of file DirectNavigatorTests.cpp.
View newest version in sPHENIX GitHub at line 61 of file DirectNavigatorTests.cpp
StraightLineStepper Acts::Test::slstepper
Definition at line 65 of file MaterialCollectionTests.cpp.
View newest version in sPHENIX GitHub at line 65 of file MaterialCollectionTests.cpp
template<typename T > constexpr bool Acts::Test::SomeConcept
Initial value:
=
    require<has_method<T, double, foo_method_t, double, int>,
            has_method<const T, bool, bar_method_t, double&&>,
            has_member<T, member_t, bool>, exists<nested_t, T>,
            exists<meta_t, T>>
Definition at line 180 of file TypeTraitsTest.cpp.
View newest version in sPHENIX GitHub at line 180 of file TypeTraitsTest.cpp
std::vector<float> Acts::Test::sstr = {0., 1., 1.5, 2., 3.}
Definition at line 74 of file BinningDataTests.cpp.
View newest version in sPHENIX GitHub at line 74 of file BinningDataTests.cpp
std::vector<std::unique_ptr<const Surface> > Acts::Test::stepState
Definition at line 46 of file ExtrapolatorTests.cpp.
View newest version in sPHENIX GitHub at line 46 of file ExtrapolatorTests.cpp
const Surface* Acts::Test::sur
Definition at line 173 of file KalmanFitterTests.cpp.
View newest version in sPHENIX GitHub at line 173 of file KalmanFitterTests.cpp
double Acts::Test::surfaceHalfLengthZ = 50_mm
we test a two-level hierarchy every deeper level hierarchy is a a derivate of this
WorldVolume with volumeID == 1
InnerVolume with volumeID == 2 – InnerInnerVolume with volumeID == 3 – InnerOuterVolume with volumeID == 4
OuterVolume with volumeID == 5
Definition at line 35 of file TrackingGeometryClosureTests.cpp.
View newest version in sPHENIX GitHub at line 35 of file TrackingGeometryClosureTests.cpp
Referenced by Acts::constructCylinderVolume().
double Acts::Test::surfaceRstagger = 5_mm
Definition at line 36 of file TrackingGeometryClosureTests.cpp.
View newest version in sPHENIX GitHub at line 36 of file TrackingGeometryClosureTests.cpp
Referenced by Acts::constructCylinderVolume().
double Acts::Test::surfaceZoverlap = 10_mm
Definition at line 37 of file TrackingGeometryClosureTests.cpp.
View newest version in sPHENIX GitHub at line 37 of file TrackingGeometryClosureTests.cpp
double Acts::Test::tanAlpha = tan(lAngle)
Definition at line 36 of file PlanarModuleStepperTests.cpp.
View newest version in sPHENIX GitHub at line 36 of file PlanarModuleStepperTests.cpp
GeometryContext Acts::Test::testContext = GeometryContext()
Definition at line 30 of file CylinderSurfaceTests.cpp.
View newest version in sPHENIX GitHub at line 30 of file CylinderSurfaceTests.cpp
Referenced by BOOST_AUTO_TEST_CASE().
const bool Acts::Test::testCylinder = true
Definition at line 39 of file SurfaceIntersectionBenchmark.cpp.
View newest version in sPHENIX GitHub at line 39 of file SurfaceIntersectionBenchmark.cpp
Referenced by BOOST_DATA_TEST_CASE().
const bool Acts::Test::testDisc = true
Definition at line 38 of file SurfaceIntersectionBenchmark.cpp.
View newest version in sPHENIX GitHub at line 38 of file SurfaceIntersectionBenchmark.cpp
Referenced by BOOST_DATA_TEST_CASE().
std::vector<std::tuple<std::string, bool, unsigned int> > Acts::Test::testModes
Initial value:
= {
    {"", false, 72}, {"Triangulate", true, 72}, {"Extremas", false, 1}}
Definition at line 66 of file PolyhedronSurfacesTests.cpp.
View newest version in sPHENIX GitHub at line 66 of file PolyhedronSurfacesTests.cpp
Referenced by BOOST_AUTO_TEST_CASE().
std::vector<DigitizationModule> Acts::Test::testModules
Initial value:
= {std::move(pdModule),
                                               std::move(ndModule)}
Definition at line 49 of file PlanarModuleStepperTests.cpp.
View newest version in sPHENIX GitHub at line 49 of file PlanarModuleStepperTests.cpp
Referenced by BOOST_DATA_TEST_CASE().
const bool Acts::Test::testPlane = true
Definition at line 37 of file SurfaceIntersectionBenchmark.cpp.
View newest version in sPHENIX GitHub at line 37 of file SurfaceIntersectionBenchmark.cpp
Referenced by BOOST_DATA_TEST_CASE().
const bool Acts::Test::testStraw = true
Definition at line 40 of file SurfaceIntersectionBenchmark.cpp.
View newest version in sPHENIX GitHub at line 40 of file SurfaceIntersectionBenchmark.cpp
Referenced by BOOST_DATA_TEST_CASE().
GeometryContext Acts::Test::tgContext = GeometryContext()
Definition at line 43 of file SurfaceIntersectionBenchmark.cpp.
View newest version in sPHENIX GitHub at line 43 of file SurfaceIntersectionBenchmark.cpp
Referenced by BOOST_AUTO_TEST_CASE(), BOOST_DATA_TEST_CASE(), BOOST_FIXTURE_TEST_CASE(), draw_surfaces(), Acts::Test::SurfaceArrayFixture::draw_surfaces(), Acts::Test::SurfaceArrayCreatorFixture::makeBarrelStagger(), and Acts::Test::LayerCreatorFixture::makeBarrelStagger().
auto Acts::Test::tGeometry = cGeometry()
Definition at line 41 of file DirectNavigatorTests.cpp.
View newest version in sPHENIX GitHub at line 41 of file DirectNavigatorTests.cpp
Referenced by BOOST_AUTO_TEST_CASE(), main(), materialMappingExample(), processGeometry(), and propagationExample().
auto Acts::Test::transform = std::make_shared<Transform3D>(Transform3D::Identity())
Definition at line 69 of file PolyhedronSurfacesTests.cpp.
View newest version in sPHENIX GitHub at line 69 of file PolyhedronSurfacesTests.cpp
Referenced by BOOST_AUTO_TEST_CASE(), BOOST_DATA_TEST_CASE(), BOOST_FIXTURE_TEST_CASE(), Acts::GenericCuboidVolumeBounds::boundingBox(), Acts::TrapezoidVolumeBounds::boundingBox(), Acts::Surface::center(), Acts::DD4hepLayerBuilder::centralLayers(), Acts::DD4hepVolumeBuilder::centralVolumes(), Acts::DD4hepVolumeBuilder::convertTransform(), Acts::DD4hepLayerBuilder::convertTransform(), Acts::Visualization::createEllipse(), Acts::SurfaceArrayCreator::createEquidistantAxis(), PHCASeeding::CreateLinks(), Acts::detail::VerticesHelper::createSegment(), Acts::SurfaceArrayCreator::createVariableAxis(), Acts::CuboidVolumeBounds::decomposeToSurfaces(), Acts::TrapezoidVolumeBounds::decomposeToSurfaces(), Acts::CylinderVolumeBounds::decomposeToSurfaces(), Acts::DD4hepLayerBuilder::endcapLayers(), Acts::CylinderVolumeHelper::estimateAndCheckDimension(), ExitWindowV2::ExitWindowV2(), Acts::IVisualization::face(), Acts::ObjVisualization< T >::faces(), nlohmann::detail::from_json(), nlohmann::detail::from_json_array_impl(), PHActsInitialVertexFinder::getTrackPointers(), Acts::PlaneSurface::globalToLocal(), Acts::ConeSurface::globalToLocal(), Acts::CylinderSurface::globalToLocal(), Acts::LineSurface::globalToLocal(), Acts::CylinderVolumeHelper::glueTrackingVolumes(), hijfst_control(), Acts::Volume::inside(), Acts::ConeSurface::intersect(), Acts::CylinderSurface::intersect(), Acts::ConeSurface::intersectionEstimate(), Acts::CylinderSurface::intersectionEstimate(), Acts::PlaneSurface::intersectionEstimate(), Acts::LineSurface::intersectionEstimate(), Acts::ConeSurface::intersectionSolver(), Acts::PlaneSurface::localToGlobal(), Acts::ConeSurface::localToGlobal(), Acts::CylinderSurface::localToGlobal(), Acts::LineSurface::localToGlobal(), PHActsTrackProjection::makeCaloSurfacePtrs(), Acts::Polyhedron::merge(), FW::Contextual::AlignedDetectorElement::nominalTransform(), Acts::LineSurface::normal(), Acts::PlaneSurface::normal(), Acts::ConeSurface::normal(), Acts::CylinderSurface::normal(), Acts::ConeSurface::pathCorrection(), Acts::PerigeeSurface::polyhedronRepresentation(), Acts::StrawSurface::polyhedronRepresentation(), Acts::PlaneSurface::polyhedronRepresentation(), Acts::ConeSurface::polyhedronRepresentation(), Acts::CylinderSurface::polyhedronRepresentation(), PHRTreeSeeding::Process(), PHPythia6::ReadConfig(), PHParameters::ReadFromDB(), PHParameters::ReadFromFile(), Acts::LineSurface::referenceFrame(), Acts::Surface::referenceFrame(), Acts::ConeSurface::rotSymmetryAxis(), Acts::CylinderSurface::rotSymmetryAxis(), Acts::AtlasStepper< bfield_t >::State::State(), Acts::SurfaceArrayCreator::surfaceArrayOnCylinder(), Acts::SurfaceArrayCreator::surfaceArrayOnDisc(), Acts::SurfaceArrayCreator::surfaceArrayOnPlane(), Acts::Surface::toStream(), FW::Contextual::PayloadDetectorElement::transform(), Acts::AtlasStepper< ConstantBField >::update(), Acts::AxisAlignedBoundingBox< entity_t, value_t, DIM >::wrap(), PHParametersContainer::WriteToDB(), PHParameters::WriteToDB(), PHParametersContainer::WriteToFile(), PdbParameterMapContainer::WriteToFile(), and PHParameters::WriteToFile().
double Acts::Test::valueMin = 0.
Definition at line 68 of file BinningDataTests.cpp.
View newest version in sPHENIX GitHub at line 68 of file BinningDataTests.cpp
Referenced by BOOST_AUTO_TEST_CASE().
std::vector<float> Acts::Test::values = {0., 1., 2., 3., 4., 10.}
Definition at line 56 of file BinningDataTests.cpp.
View newest version in sPHENIX GitHub at line 56 of file BinningDataTests.cpp
Referenced by BOOST_AUTO_TEST_CASE(), Acts::ConvexPolygonBounds< N >::ConvexPolygonBounds(), makeSiClassificationNumbers(), Acts::ParameterSet< params...>::ParameterSet(), Acts::CartesianSegmentation::pitch(), FairParamList::replace(), Acts::ConvexPolygonBoundsBase::values(), and Smear::ParticleID::Wild().
auto Acts::Test::volume
Initial value:
= constructContainerVolume(tgContext, iVolume, oVolume, ov_volumeR,
                                       volumeHalfZ, "WorldVolume")
the inner volume
Definition at line 80 of file TrackingGeometryClosureTests.cpp.
View newest version in sPHENIX GitHub at line 80 of file TrackingGeometryClosureTests.cpp
Referenced by PHG4Showerv1::add_g4hit_id(), FairModule::AddSensitiveVolume(), Acts::CylinderVolumeBuilder::analyzeContent(), EicCadWizard::AssembleRootFiles(), Acts::BoundarySurfaceT< T >::attachVolume(), HelixHough::attemptClusterMerge(), BOOST_AUTO_TEST_CASE(), KFParticle_Tools::calculateEllipsoidVolume(), EicGeoMap::CalculateMappingTableSignature(), tetgenmesh::carveholes(), CbmRich::ConstructAsciiGeometry(), Acts::constructCylinderVolume(), CbmRich::ConstructGdmlGeometry(), EicDetector::ConstructGeometry(), PHG4EPDetector::ConstructMe(), FairModule::ConstructRootGeometry(), EicHtcTask::DeclareSensitiveVolumes(), Acts::MaterialWiper::decorate(), Acts::JsonMaterialDecorator::decorate(), FW::RootMaterialDecorator::decorate(), genfit::EventDisplay::drawEvent(), PHG4OuterHcalSteppingAction::FieldChecker(), EicGeoParData::FinalizeOutput(), tetgenmesh::flip23(), tetgenmesh::flip32(), CbmRich::GetGasVolume(), PHActsSiliconSeeding::getMvtxSpacePoints(), tetgenmesh::getpointmeshsize(), PHActsTrkFitter::getSurfaceVector(), EicEventManager::Init(), tetgenmesh::insertpoint(), EicRootDetector::IsInDetector(), tetgenio::load_vol(), HelixHough::makeClusters(), PHG4EPDetector::module_id_for(), Acts::MaterialInteractor::operator()(), Cell::ProcessHits(), FairModule::ProcessNodes(), PHTpcResiduals::processTrack(), tetgenmesh::reconstructmesh(), PHG4Showerv1::remove_g4hit_id(), FW::selectLayer(), FW::selectVolume(), SensitiveVolume::SensitiveVolume(), PHG4Showerv1::set_edep(), PHG4Showerv1::set_eh_ratio(), PHG4Showerv1::set_eion(), PHG4Showerv1::set_light_yield(), PHG4Showerv1::set_nhits(), setColors(), PHActsTrkProp::setVolumeLayerMaxChi2(), tetgenmesh::tetaspectratio(), Acts::CuboidVolumeBuilder::trackingVolume(), Acts::CylinderVolumeBuilder::trackingVolume(), PHG4FPbScSteppingAction::UserSteppingAction(), PHG4FCalSteppingAction::UserSteppingAction(), PHG4EPSteppingAction::UserSteppingAction(), PHG4TpcSteppingAction::UserSteppingAction(), PHG4ConeSteppingAction::UserSteppingAction(), G4Example01SteppingAction::UserSteppingAction(), PHG4SectorSteppingAction::UserSteppingAction(), PHG4EnvelopeSteppingAction::UserSteppingAction(), G4JLeicVTXSteppingAction::UserSteppingAction(), BeamLineMagnetSteppingAction::UserSteppingAction(), G4JLeicBeamLineMagnetSteppingAction::UserSteppingAction(), G4LBLVtxSteppingAction::UserSteppingAction(), G4Example03SteppingAction::UserSteppingAction(), PHG4PSTOFSteppingAction::UserSteppingAction(), G4JLeicDIRCSteppingAction::UserSteppingAction(), G4Example02SteppingAction::UserSteppingAction(), PHG4TpcEndCapSteppingAction::UserSteppingAction(), PHG4HcalSteppingAction::UserSteppingAction(), PHG4BlockSteppingAction::UserSteppingAction(), PHG4OuterHcalSteppingAction::UserSteppingAction(), PHG4CEmcTestBeamSteppingAction::UserSteppingAction(), PHG4InnerHcalSteppingAction::UserSteppingAction(), BeastMagnetSteppingAction::UserSteppingAction(), AllSiliconTrackerSteppingAction::UserSteppingAction(), EicFRichSteppingAction::UserSteppingAction(), GdmlImportDetectorSteppingAction::UserSteppingAction(), PHG4BbcSteppingAction::UserSteppingAction(), PHG4InttSteppingAction::UserSteppingAction(), PHG4FPbScRegionSteppingAction::UserSteppingAction(), PHG4CylinderSteppingAction::UserSteppingAction(), PHG4ForwardEcalSteppingAction::UserSteppingAction(), PHG4CrystalCalorimeterSteppingAction::UserSteppingAction(), PHG4ForwardHcalSteppingAction::UserSteppingAction(), PHG4mRICHSteppingAction::UserSteppingAction(), PHG4MicromegasSteppingAction::UserSteppingAction(), PHG4SpacalSteppingAction::UserSteppingAction(), Acts::TrackingVolume::visitSurfaces(), and FW::Obj::ObjTrackingGeometryWriter::write().
double Acts::Test::volumeEnvelope = 10_mm
Definition at line 39 of file TrackingGeometryClosureTests.cpp.
View newest version in sPHENIX GitHub at line 39 of file TrackingGeometryClosureTests.cpp
Referenced by Acts::constructCylinderVolume().
double Acts::Test::volumeHalfZ
Initial value:
=
    (4 * surfaceHalfLengthZ - surfaceZoverlap) + volumeEnvelope
Definition at line 63 of file TrackingGeometryClosureTests.cpp.
View newest version in sPHENIX GitHub at line 63 of file TrackingGeometryClosureTests.cpp
auto Acts::Test::world = tGeometry.highestTrackingVolume()
Definition at line 87 of file TrackingGeometryClosureTests.cpp.
View newest version in sPHENIX GitHub at line 87 of file TrackingGeometryClosureTests.cpp
Referenced by kdfinder::TVector< T >::bad(), BOOST_AUTO_TEST_CASE(), FW::DD4hepG4::GeoConstruction::Construct(), vc2020_03_20::CreateGeometry(), Acts::VolumeMaterialMapper::createState(), Acts::SurfaceMaterialMapper::createState(), EtmVacuumChamber::CreateWorld(), EicToyModel::DefineG4World(), EtmDetector::GetG4Volume(), PHActsSourceLinks::getInttLocalCoords(), PHActsSourceLinks::getMmLocalCoords(), PHActsSourceLinks::getMvtxLocalCoords(), PHActsSourceLinks::getTpcLocalCoords(), EtmDetector::PlaceG4Volume(), PHG4MicromegasHitReco::process_event(), kdfinder::TVector< T >::valid(), kdfinder::Helix< T >::valid(), vc_viewer(), and FW::Obj::ObjTrackingGeometryWriter::write().
BinningData Acts::Test::xData_arb(open, binX, values)
Referenced by BOOST_AUTO_TEST_CASE().
BinningData Acts::Test::xData_eq(open, binX, 10, 0., 10.)
Referenced by BOOST_AUTO_TEST_CASE().
BinningData Acts::Test::xData_mult(open, binX, 3, 0., 9., std::move(xData_sstr_mult))
Referenced by BOOST_AUTO_TEST_CASE().
auto Acts::Test::xData_sstr_add = std::make_unique<const BinningData>(open, binX, sstr)
Definition at line 82 of file BinningDataTests.cpp.
View newest version in sPHENIX GitHub at line 82 of file BinningDataTests.cpp
auto Acts::Test::xData_sstr_mult = std::make_unique<const BinningData>(open, binX, sstr)
Definition at line 76 of file BinningDataTests.cpp.
View newest version in sPHENIX GitHub at line 76 of file BinningDataTests.cpp
BinningData Acts::Test::yData_arb(open, binY, values)
Referenced by BOOST_AUTO_TEST_CASE().
BinningData Acts::Test::yData_eq(open, binY, 10, 0., 10.)
Referenced by BOOST_AUTO_TEST_CASE().
BinningData Acts::Test::zData_eq(open, binZ, 10, 0., 10.)
Referenced by BOOST_AUTO_TEST_CASE().
const double Acts::Test::zVertexPos = 12.
Definition at line 156 of file TrackDensityVertexFinderTests.cpp.
View newest version in sPHENIX GitHub at line 156 of file TrackDensityVertexFinderTests.cpp
Referenced by BOOST_AUTO_TEST_CASE().