EIC Software: Smear::HadronicEventBuilder Class Reference
Smear::HadronicEventBuilder Class Reference
#include <eic-smear/blob/master/include/eicsmear/hadronic/EventSmear.h>
Public Member Functions
virtual ~HadronicEventBuilder ()
HadronicEventBuilder (const Detector &d, TBranch &mcBranch)
virtual EventType * Create ()
Public Member Functions inherited from Smear::EventFactory< erhic::hadronic::EventSmear >
virtual ~EventFactory ()
virtual std::string EventName () const
virtual TBranch * Branch (TTree &tree, const std::string &name)
virtual void Fill (TBranch &branch)
Public Member Functions inherited from erhic::VirtualEventFactory
virtual ~VirtualEventFactory ()
virtual VirtualEvent * GetEvBufferPtr ()
virtual void FindFirstEvent ()
Protected Attributes
Detector mDetector
erhic::hadronic::EventMC * mMcEvent
Additional Inherited Members
Public Types inherited from Smear::EventFactory< erhic::hadronic::EventSmear >
typedef erhic::hadronic::EventSmear EventType
Public Attributes inherited from erhic::VirtualEventFactory
std::vector< NamedObjects > mObjectsToWriteAtTheEnd
std::map< std::string,
std::string > mAdditionalInformation
Detailed Description
Factory class for smeared hadronic events.
Definition at line 74 of file EventSmear.h.
View newest version in sPHENIX GitHub at line 74 of file EventSmear.h
Constructor & Destructor Documentation
virtual Smear::HadronicEventBuilder::~HadronicEventBuilder () inline virtual
Destructor.
Definition at line 79 of file EventSmear.h.
View newest version in sPHENIX GitHub at line 79 of file EventSmear.h
Smear::HadronicEventBuilder::HadronicEventBuilder (const Detector & d, TBranch & mcBranch) inline
Constructor. Initialise with the Detector performing particle smearing and the tree branch providing DIS Monte Carlo events.
Definition at line 86 of file EventSmear.h.
View newest version in sPHENIX GitHub at line 86 of file EventSmear.h
References mMcEvent.
Member Function Documentation
virtual EventType* Smear::HadronicEventBuilder::Create () inline virtual
Create a smeared event corresponding to the current DIS Monte Carlo event in the input branch passed to the constructor. The user should call TTree::GetEntry() themselves between calls to Create().
Implements Smear::EventFactory< erhic::hadronic::EventSmear >.
Definition at line 98 of file EventSmear.h.
View newest version in sPHENIX GitHub at line 98 of file EventSmear.h
References erhic::hadronic::EventMC::GetNTracks(), erhic::hadronic::EventMC::GetTrack(), mDetector, mMcEvent, and Smear::Detector::Smear().
Member Data Documentation
Detector Smear::HadronicEventBuilder::mDetector protected
Definition at line 110 of file EventSmear.h.
View newest version in sPHENIX GitHub at line 110 of file EventSmear.h
Referenced by Create().
erhic::hadronic::EventMC* Smear::HadronicEventBuilder::mMcEvent protected
Definition at line 111 of file EventSmear.h.
View newest version in sPHENIX GitHub at line 111 of file EventSmear.h
Referenced by Create(), and HadronicEventBuilder().
The documentation for this class was generated from the following file:
eic-smear/blob/master/include/eicsmear/hadronic/EventSmear.h