EIC Software: fun4all_eicmacros/blob/master/common/G4_FGEM_fsPHENIX.C File Reference
G4_FGEM_fsPHENIX.C File Reference
#include <GlobalVariables.C>
#include <G4_FEMC.C>
#include <G4_FHCAL.C>
#include <g4detectors/PHG4SectorSubsystem.h>
#include <g4main/PHG4Reco.h>
#include <g4trackfastsim/PHG4TrackFastSim.h>
#include <g4trackfastsim/PHG4TrackFastSimEval.h>
#include <fun4all/Fun4AllServer.h>
Namespaces
namespace Enable
Macros
#define MACRO_G4FGEMFSPHENIX_C
Functions
int make_GEM_station (string name, PHG4Reco *g4Reco, double zpos, double etamin, double etamax, const int N_Sector=8)
void AddLayers_MiniTPCDrift (PHG4SectorSubsystem *gem)
Add drift layers to mini TPC.
void FGEM_Init ()
void FGEMSetup (PHG4Reco *g4Reco, const int N_Sector=8, const double min_eta=1.45)
void FGEM_FastSim_Reco ()
void FGEM_FastSim_Eval (const std::string &outputfile)
Variables
bool Enable::FGEM = false
bool Enable::FGEM_OVERLAPCHECK = false
bool Enable::FGEM_TRACK = false
bool Enable::FGEM_EVAL = false
int Enable::FGEM_VERBOSITY = 0
Macro Definition Documentation
#define MACRO_G4FGEMFSPHENIX_C
Definition at line 2 of file G4_FGEM_fsPHENIX.C.
View newest version in sPHENIX GitHub at line 2 of file G4_FGEM_fsPHENIX.C
Function Documentation
void AddLayers_MiniTPCDrift (PHG4SectorSubsystem * gem)
Add drift layers to mini TPC.
Definition at line 166 of file G4_FGEM_fsPHENIX.C.
View newest version in sPHENIX GitHub at line 166 of file G4_FGEM_fsPHENIX.C
References PHG4Sector::Sector_Geometry::AddLayer(), Acts::UnitConstants::cm, d, Acts::UnitConstants::e, PHG4SectorSubsystem::get_geometry(), Acts::UnitConstants::mm, Acts::UnitConstants::s, thickness, Acts::UnitConstants::um, and PHG4Sector::Sector_Geometry::Unit_cm().
Referenced by FGEMSetup(), and make_GEM_station().
void FGEM_FastSim_Eval (const std::string & outputfile)
Definition at line 342 of file G4_FGEM_fsPHENIX.C.
View newest version in sPHENIX GitHub at line 342 of file G4_FGEM_fsPHENIX.C
References Enable::FGEM_VERBOSITY, Fun4AllServer::instance(), max, Fun4AllServer::registerSubsystem(), PHG4TrackFastSimEval::set_filename(), PHG4TrackFastSimEval::set_trackmapname(), TRACKING::TrackNodeName, and Enable::VERBOSITY.
Referenced by Fun4All_G4_fsPHENIX().
void FGEM_FastSim_Reco ()
Definition at line 235 of file G4_FGEM_fsPHENIX.C.
View newest version in sPHENIX GitHub at line 235 of file G4_FGEM_fsPHENIX.C
References PHG4TrackFastSim::add_phg4hits(), PHG4TrackFastSim::add_state_name(), PHG4TrackFastSim::Cylinder, Acts::UnitConstants::e, Enable::FEMC, Enable::FGEM_VERBOSITY, Enable::FHCAL, Fun4AllServer::instance(), max, Fun4AllServer::registerSubsystem(), PHG4TrackFastSim::set_sub_top_node_name(), PHG4TrackFastSim::set_trackmap_out_name(), PHG4TrackFastSim::set_use_vertex_in_fitting(), PHG4TrackFastSim::set_vertex_xy_resolution(), PHG4TrackFastSim::set_vertex_z_resolution(), TRACKING::TrackNodeName, Enable::VERBOSITY, Fun4AllBase::Verbosity(), and PHG4TrackFastSim::Vertical_Plane.
Referenced by Fun4All_G4_fsPHENIX().
void FGEM_Init ()
Definition at line 35 of file G4_FGEM_fsPHENIX.C.
View newest version in sPHENIX GitHub at line 35 of file G4_FGEM_fsPHENIX.C
References max, BlackHoleGeometry::max_radius, BlackHoleGeometry::max_z, and TRACKING::TrackNodeName.
Referenced by Fun4All_G4_FastMom_GEM(), Fun4All_G4_FastMom_GEM_RICH(), Fun4All_G4_simple_hadron_GEM(), and G4Init().
void FGEMSetup (PHG4Reco * g4Reco, const int N_Sector = 8, const double min_eta = 1.45)
Definition at line 42 of file G4_FGEM_fsPHENIX.C.
View newest version in sPHENIX GitHub at line 42 of file G4_FGEM_fsPHENIX.C
References PHG4Sector::Sector_Geometry::AddLayers_HBD_GEM(), AddLayers_MiniTPCDrift(), cos(), PHG4Sector::Sector_Geometry::eta_to_polar_angle(), Enable::FGEM_OVERLAPCHECK, PHG4Sector::Sector_Geometry::FlatEdge(), PHG4SectorSubsystem::get_geometry(), make_GEM_station(), name, Enable::OVERLAPCHECK, PHG4Subsystem::OverlapCheck(), PHG4Reco::registerSubsystem(), PHG4Sector::Sector_Geometry::set_material(), PHG4Sector::Sector_Geometry::set_max_polar_angle(), PHG4Sector::Sector_Geometry::set_max_polar_edge(), PHG4Sector::Sector_Geometry::set_min_polar_angle(), PHG4Sector::Sector_Geometry::set_min_polar_edge(), PHG4Sector::Sector_Geometry::set_N_Sector(), PHG4Sector::Sector_Geometry::set_normal_polar_angle(), PHG4Sector::Sector_Geometry::set_normal_start(), PHG4SectorSubsystem::SuperDetector(), and PHG4Sector::Sector_Geometry::Unit_cm().
Referenced by Fun4All_G4_FastMom_GEM(), Fun4All_G4_FastMom_GEM_RICH(), Fun4All_G4_simple_hadron_GEM(), and G4Setup().
int make_GEM_station (string name, PHG4Reco * g4Reco, double zpos, double etamin, double etamax, const int N_Sector = 8)
Definition at line 191 of file G4_FGEM_fsPHENIX.C.
View newest version in sPHENIX GitHub at line 191 of file G4_FGEM_fsPHENIX.C
References PHG4Sector::Sector_Geometry::AddLayers_HBD_GEM(), AddLayers_MiniTPCDrift(), PHG4Sector::Sector_Geometry::eta_to_polar_angle(), Enable::FGEM_OVERLAPCHECK, PHG4Sector::Sector_Geometry::FlatEdge(), PHG4SectorSubsystem::get_geometry(), Enable::OVERLAPCHECK, PHG4Subsystem::OverlapCheck(), PHG4Reco::registerSubsystem(), PHG4Sector::Sector_Geometry::set_material(), PHG4Sector::Sector_Geometry::set_max_polar_angle(), PHG4Sector::Sector_Geometry::set_max_polar_edge(), PHG4Sector::Sector_Geometry::set_min_polar_angle(), PHG4Sector::Sector_Geometry::set_min_polar_edge(), PHG4Sector::Sector_Geometry::set_N_Sector(), PHG4Sector::Sector_Geometry::set_normal_polar_angle(), PHG4Sector::Sector_Geometry::set_normal_start(), PHG4SectorSubsystem::SuperDetector(), t, and PHG4Sector::Sector_Geometry::Unit_cm().
Referenced by EGEMSetup(), and FGEMSetup().