EIC Software: fun4all_eic_tutorials/blob/master/ReadEICGeneratorOutput/Fun4All_EIC_Generator_Display.C File Reference
Fun4All_EIC_Generator_Display.C File Reference
#include <fun4all/SubsysReco.h>
#include <fun4all/Fun4AllServer.h>
#include <fun4all/Fun4AllInputManager.h>
#include <fun4all/Fun4AllDummyInputManager.h>
#include <g4main/PHG4Reco.h>
#include <g4main/HepMCNodeReader.h>
#include <g4main/ReadEICFiles.h>
#include <phool/recoConsts.h>
Functions
int Fun4All_EIC_Generator_Display (const std::string &inputFile="MILOU_5x100_TOTAL_01_20evt.root")
void displaycmd ()
Variables
PHG4Reco * g4 = nullptr
const double magfield = 1.5
Function Documentation
void displaycmd ()
Definition at line 66 of file Fun4All_EIC_Generator_Display.C.
View newest version in sPHENIX GitHub at line 66 of file Fun4All_EIC_Generator_Display.C
int Fun4All_EIC_Generator_Display (const std::string & inputFile = "MILOU_5x100_TOTAL_01_20evt.root")
Definition at line 20 of file Fun4All_EIC_Generator_Display.C.
View newest version in sPHENIX GitHub at line 20 of file Fun4All_EIC_Generator_Display.C
References PHG4Reco::ApplyCommand(), PHG4Reco::ApplyDisplayAction(), g4, in, PHG4Reco::InitRun(), Fun4AllServer::instance(), magfield, ReadEICFiles::OpenInputFile(), Fun4AllServer::registerInputManager(), Fun4AllServer::registerSubsystem(), Fun4AllServer::run(), PHG4Reco::save_DST_geometry(), PHG4Reco::set_field(), PHG4Reco::set_rapidity_coverage(), Fun4AllServer::topNode(), and Fun4AllBase::Verbosity().
Variable Documentation
PHG4Reco* g4 = nullptr
Definition at line 17 of file Fun4All_EIC_Generator_Display.C.
View newest version in sPHENIX GitHub at line 17 of file Fun4All_EIC_Generator_Display.C
Referenced by DisplayOn(), LiteCaloEval::End(), Extract_ECCE_gdml(), Fun4All_EIC_Generator_Display(), Fun4All_G4_QtDisplay(), Fun4All_Generator_Display(), g(), G4Cmd(), matscan(), partonx6(), and QTGui().
const double magfield = 1.5
Definition at line 18 of file Fun4All_EIC_Generator_Display.C.
View newest version in sPHENIX GitHub at line 18 of file Fun4All_EIC_Generator_Display.C
Referenced by Fun4All_EIC_Generator_Display(), Fun4All_G4_FullDetectorModular(), Fun4All_G4_sPHENIX_particle_gen(), Fun4All_Generator_Display(), and PHActsInitialVertexFinder::magFieldName().