EIC Software: PndTrackCand Class Reference
PndTrackCand Class Reference
#include <EicRoot/blob/master/pnddata/TrackData/PndTrackCand.h>
Public Member Functions
PndTrackCand ()
~PndTrackCand ()
bool operator== (const PndTrackCand &rhs)
PndTrackCandHit GetSortedHit (UInt_t i)
UInt_t GetNHits () const
int getMcTrackId () const
TVector3 getPosSeed () const
TVector3 getMomSeed () const
double getChargeSeed () const
UInt_t GetNHitsDet (UInt_t detId)
std::vector< PndTrackCandHit > & _GetSortedHits ()
void Sort ()
void AddHit (UInt_t detId, UInt_t hitId, Double_t rho)
void AddHit (TString branchName, UInt_t hitId, Double_t rho)
void AddHit (FairLink link, Double_t rho)
void DeleteHit (UInt_t detId, UInt_t hitId)
Int_t HitInTrack (UInt_t detId, UInt_t hitId)
void setMcTrackId (int i)
void setTrackSeed (const TVector3 &p, const TVector3 &m, double charge)
void CalcTimeStamp ()
void ResetLinks ()
Clears fLinks.
void Print ()
ClassDef (PndTrackCand, 3)
Public Member Functions inherited from FairTimeStamp
FairTimeStamp ()
FairTimeStamp (Double_t time)
FairTimeStamp (Double_t time, Double_t timeerror)
virtual ~FairTimeStamp ()
virtual Double_t GetTimeStamp () const
virtual Double_t GetTimeStampError () const
virtual FairLink GetEntryNr () const
virtual void SetTimeStamp (Double_t t)
virtual void SetTimeStampError (Double_t t)
virtual void SetEntryNr (FairLink entry)
virtual Int_t Compare (const TObject *obj) const
void Print (std::ostream &out=std::cout) const
virtual Bool_t IsSortable () const
virtual bool equal (FairTimeStamp *data)
Public Member Functions inherited from FairMultiLinkedData
FairMultiLinkedData ()
Default constructor.
FairMultiLinkedData (std::set< FairLink > links, Bool_t persistanceCheck=kTRUE)
Constructor.
FairMultiLinkedData (TString dataType, std::vector< Int_t > links, Int_t fileId=-1, Int_t evtId=-1, Bool_t persistanceCheck=kTRUE, Bool_t bypass=kFALSE, Float_t mult=1.0)
Constructor.
FairMultiLinkedData (Int_t dataType, std::vector< Int_t > links, Int_t fileId=-1, Int_t evtId=-1, Bool_t persistanceCheck=kTRUE, Bool_t bypass=kFALSE, Float_t mult=1.0)
Constructor.
virtual ~FairMultiLinkedData ()
virtual std::set< FairLink > GetLinks () const
returns stored links as FairLinks
virtual Int_t GetNLinks () const
returns the number of stored links
virtual FairLink GetLink (Int_t pos) const
returns the FairLink at the given position
virtual FairMultiLinkedData GetLinksWithType (Int_t type) const
Gives you a list of links which contain the given type.
TObject * GetData (FairLink &myLink)
Get the TObject the Link is pointing to.
virtual Int_t GetDefaultType ()
Bool_t GetPersistanceCheck ()
Returns the value of PersistanceCheck.
Int_t GetVerbose ()
Returns the verbosity level.
virtual void SetDefaultType (Int_t type)
virtual void SetPersistanceCheck (Bool_t check)
Controls if a persistance check of a link is done or not.
virtual void SetVerbose (Int_t level)
Sets the verbosity level.
virtual void SetLinks (FairMultiLinkedData links, Float_t mult=1.0)
Sets the links as vector of FairLink.
virtual void SetLink (FairLink link, Bool_t bypass=kFALSE, Float_t mult=1.0)
Sets the Links with a single FairLink.
virtual void AddLinks (FairMultiLinkedData links, Float_t mult=1.0)
Adds a List of FairLinks (FairMultiLinkedData) to fLinks.
virtual void AddLink (FairLink link, Bool_t bypass=kFALSE, Float_t mult=1.0)
Adds a FairLink link at the end of fLinks. If multi is kTRUE a link is allowed more than once otherwise it is stored only once.
virtual void InsertLink (FairLink link)
Inserts a link into the list of links without persistance checking.
virtual void AddAllWeights (Double_t weight)
Adds weight to all Links.
virtual void SetAllWeights (Double_t weight)
Sets a common weight for Links.
virtual void MultiplyAllWeights (Double_t weight)
Multiplies all Links with weight.
virtual Bool_t IsLinkInList (FairLink link)
Test if a given link is in fLinks.
virtual Bool_t IsLinkInList (Int_t type, Int_t index)
Same as IsLinkInList(FairLink) just with type and index given separately.
virtual Int_t LinkPosInList (FairLink link)
returns position of link in fLinks. If it is not in the list -1 is returned
virtual Int_t LinkPosInList (Int_t type, Int_t index)
Same as LinkPosInList(FairLink)
virtual void DeleteLink (FairLink link)
Deletes a link ouf of fLinks.
virtual void DeleteLink (Int_t type, Int_t index)
Deletes a link ouf of fLinks.
virtual void Reset ()
void Print (std::ostream &out=std::cout) const
Output.
Private Attributes
std::vector< PndTrackCandHit > fHitId
first index is detId, second index is hit Id
bool sorted
int fMcTrackId
TVector3 fPosSeed
TVector3 fMomSeed
double fChargeSeed
Int_t fVerbose
Additional Inherited Members
Protected Member Functions inherited from FairTimeStamp
ClassDef (FairTimeStamp, 2)
indicates where the data is stored in the branch
Protected Attributes inherited from FairTimeStamp
Double_t fTimeStamp
Double_t fTimeStampError
FairLink fEntryNr
Detailed Description
Definition at line 35 of file PndTrackCand.h.
View newest version in sPHENIX GitHub at line 35 of file PndTrackCand.h
Constructor & Destructor Documentation
PndTrackCand::PndTrackCand ()
Definition at line 30 of file PndTrackCand.cxx.
View newest version in sPHENIX GitHub at line 30 of file PndTrackCand.cxx
PndTrackCand::~PndTrackCand ()
Definition at line 32 of file PndTrackCand.cxx.
View newest version in sPHENIX GitHub at line 32 of file PndTrackCand.cxx
Member Function Documentation
std::vector< PndTrackCandHit > & PndTrackCand::_GetSortedHits ()
Definition at line 104 of file PndTrackCand.cxx.
View newest version in sPHENIX GitHub at line 104 of file PndTrackCand.cxx
References fHitId, Sort(), and sorted.
Referenced by PndRecoKalmanFit::Fit().
void PndTrackCand::AddHit (UInt_t detId, UInt_t hitId, Double_t rho)
Definition at line 35 of file PndTrackCand.cxx.
View newest version in sPHENIX GitHub at line 35 of file PndTrackCand.cxx
References FairMultiLinkedData::AddLink(), fHitId, and sorted.
Referenced by AddHit(), EicIdealTrackingCode::Exec(), and GenfitTrackCand2PndTrackCand().
void PndTrackCand::AddHit (TString branchName, UInt_t hitId, Double_t rho)
Definition at line 43 of file PndTrackCand.cxx.
View newest version in sPHENIX GitHub at line 43 of file PndTrackCand.cxx
References AddHit(), FairRootManager::GetBranchId(), and FairRootManager::Instance().
void PndTrackCand::AddHit (FairLink link, Double_t rho)
Definition at line 50 of file PndTrackCand.cxx.
View newest version in sPHENIX GitHub at line 50 of file PndTrackCand.cxx
References FairMultiLinkedData::AddLink(), fHitId, FairLink::GetIndex(), FairLink::GetType(), and sorted.
void PndTrackCand::CalcTimeStamp ()
Definition at line 111 of file PndTrackCand.cxx.
View newest version in sPHENIX GitHub at line 111 of file PndTrackCand.cxx
References fVerbose, FairRootManager::GetBranchName(), FairRootManager::GetCloneOfLinkData(), FairLink::GetIndex(), FairMultiLinkedData::GetLink(), FairMultiLinkedData::GetNLinks(), FairRootManager::GetObject(), FairTimeStamp::GetTimeStamp(), FairTimeStamp::GetTimeStampError(), FairLink::GetType(), FairRootManager::Instance(), FairTimeStamp::SetTimeStamp(), and FairTimeStamp::SetTimeStampError().
PndTrackCand::ClassDef (PndTrackCand , 3)
void PndTrackCand::DeleteHit (UInt_t detId, UInt_t hitId)
Definition at line 74 of file PndTrackCand.cxx.
View newest version in sPHENIX GitHub at line 74 of file PndTrackCand.cxx
References fHitId, and HitInTrack().
double PndTrackCand::getChargeSeed () const inline
Definition at line 57 of file PndTrackCand.h.
View newest version in sPHENIX GitHub at line 57 of file PndTrackCand.h
References fChargeSeed.
Referenced by PndTrackCand2GenfitTrackCand().
int PndTrackCand::getMcTrackId () const inline
Definition at line 52 of file PndTrackCand.h.
View newest version in sPHENIX GitHub at line 52 of file PndTrackCand.h
References fMcTrackId.
Referenced by PndPidCorrelator::ConstructChargedCandidate(), and PndTrackCand2GenfitTrackCand().
TVector3 PndTrackCand::getMomSeed () const inline
Definition at line 56 of file PndTrackCand.h.
View newest version in sPHENIX GitHub at line 56 of file PndTrackCand.h
References fMomSeed.
Referenced by PndTrackCand2GenfitTrackCand().
UInt_t PndTrackCand::GetNHits () const inline
Definition at line 51 of file PndTrackCand.h.
View newest version in sPHENIX GitHub at line 51 of file PndTrackCand.h
References fHitId.
Referenced by EicIdealTrackingCode::Exec(), and PndTrackCand2GenfitTrackCand().
UInt_t PndTrackCand::GetNHitsDet (UInt_t detId)
Definition at line 84 of file PndTrackCand.cxx.
View newest version in sPHENIX GitHub at line 84 of file PndTrackCand.cxx
References fHitId, PndTrackCandHit::GetDetId(), and GetSortedHit().
TVector3 PndTrackCand::getPosSeed () const inline
Definition at line 53 of file PndTrackCand.h.
View newest version in sPHENIX GitHub at line 53 of file PndTrackCand.h
References fPosSeed.
Referenced by PndTrackCand2GenfitTrackCand().
PndTrackCandHit PndTrackCand::GetSortedHit (UInt_t i) inline
Definition at line 46 of file PndTrackCand.h.
View newest version in sPHENIX GitHub at line 46 of file PndTrackCand.h
References fHitId, Sort(), and sorted.
Referenced by GetNHitsDet(), and PndTrackCand2GenfitTrackCand().
int PndTrackCand::HitInTrack (UInt_t detId, UInt_t hitId)
Definition at line 64 of file PndTrackCand.cxx.
View newest version in sPHENIX GitHub at line 64 of file PndTrackCand.cxx
References fHitId.
Referenced by DeleteHit().
bool PndTrackCand::operator== (const PndTrackCand & rhs)
Definition at line 154 of file PndTrackCand.cxx.
View newest version in sPHENIX GitHub at line 154 of file PndTrackCand.cxx
References fHitId.
void PndTrackCand::Print (void)
Definition at line 163 of file PndTrackCand.cxx.
View newest version in sPHENIX GitHub at line 163 of file PndTrackCand.cxx
References fHitId, fMcTrackId, fMomSeed, and fPosSeed.
void PndTrackCand::ResetLinks () virtual
Clears fLinks.
Reimplemented from FairMultiLinkedData.
Definition at line 58 of file PndTrackCand.cxx.
View newest version in sPHENIX GitHub at line 58 of file PndTrackCand.cxx
References fHitId, and FairMultiLinkedData::ResetLinks().
void PndTrackCand::setMcTrackId (int i) inline
Definition at line 69 of file PndTrackCand.h.
View newest version in sPHENIX GitHub at line 69 of file PndTrackCand.h
References fMcTrackId.
Referenced by EicIdealTrackingCode::Exec(), and GenfitTrackCand2PndTrackCand().
void PndTrackCand::setTrackSeed (const TVector3 & p, const TVector3 & m, double charge) inline
Definition at line 73 of file PndTrackCand.h.
View newest version in sPHENIX GitHub at line 73 of file PndTrackCand.h
References charge, fChargeSeed, fMomSeed, fPosSeed, Acts::UnitConstants::m, and p.
Referenced by GenfitTrackCand2PndTrackCand().
void PndTrackCand::Sort ()
Definition at line 98 of file PndTrackCand.cxx.
View newest version in sPHENIX GitHub at line 98 of file PndTrackCand.cxx
References fHitId, and sorted.
Referenced by _GetSortedHits(), EicIdealTrackingCode::Exec(), and GetSortedHit().
Member Data Documentation
double PndTrackCand::fChargeSeed private
Definition at line 90 of file PndTrackCand.h.
View newest version in sPHENIX GitHub at line 90 of file PndTrackCand.h
Referenced by getChargeSeed(), and setTrackSeed().
std::vector<PndTrackCandHit> PndTrackCand::fHitId private
first index is detId, second index is hit Id
Definition at line 85 of file PndTrackCand.h.
View newest version in sPHENIX GitHub at line 85 of file PndTrackCand.h
Referenced by _GetSortedHits(), AddHit(), DeleteHit(), GetNHits(), GetNHitsDet(), GetSortedHit(), HitInTrack(), operator==(), Print(), ResetLinks(), and Sort().
int PndTrackCand::fMcTrackId private
Definition at line 87 of file PndTrackCand.h.
View newest version in sPHENIX GitHub at line 87 of file PndTrackCand.h
Referenced by getMcTrackId(), Print(), and setMcTrackId().
TVector3 PndTrackCand::fMomSeed private
Definition at line 89 of file PndTrackCand.h.
View newest version in sPHENIX GitHub at line 89 of file PndTrackCand.h
Referenced by getMomSeed(), Print(), and setTrackSeed().
TVector3 PndTrackCand::fPosSeed private
Definition at line 88 of file PndTrackCand.h.
View newest version in sPHENIX GitHub at line 88 of file PndTrackCand.h
Referenced by getPosSeed(), Print(), and setTrackSeed().
Int_t PndTrackCand::fVerbose private
Definition at line 91 of file PndTrackCand.h.
View newest version in sPHENIX GitHub at line 91 of file PndTrackCand.h
Referenced by CalcTimeStamp().
bool PndTrackCand::sorted private
Definition at line 86 of file PndTrackCand.h.
View newest version in sPHENIX GitHub at line 86 of file PndTrackCand.h
Referenced by _GetSortedHits(), AddHit(), GetSortedHit(), and Sort().
The documentation for this class was generated from the following files:
EicRoot/blob/master/pnddata/TrackData/PndTrackCand.h
EicRoot/blob/master/pnddata/TrackData/PndTrackCand.cxx