EIC Software: FairGeoSet Class Reference
FairGeoSet Class Reference
#include <EicRoot/blob/master/geobase/FairGeoSet.h>
Classes
class FairGeoCopyNode
Public Member Functions
virtual ~FairGeoSet ()
void setShapes (FairGeoShapes *s)
void setMasterNodes (TList *m)
void setGeomFile (const char *filename)
const char * getGeomFile ()
Int_t getMaxSectors (void)
Int_t getMaxModules (void)
Int_t getMaxKeepinVolumes (void)
void setModules (Int_t, Int_t *)
Int_t * getModules (void)
Int_t getModule (Int_t, Int_t)
FairGeoNode * getVolume (const char *name)
FairGeoNode * getMasterNode (const char *name)
TList * getListOfVolumes ()
FairGeoShapes * getShapes ()
void setAuthor (TString &s)
void setDescription (TString &s)
TString & getAuthor ()
TString & getDescription ()
virtual const char * getKeepinName (Int_t, Int_t)
virtual const char * getModuleName (Int_t)
virtual const char * getEleName (Int_t)
virtual Int_t getSecNumInMod (const TString &)
virtual Int_t getModNumInMod (const TString &)
virtual Bool_t read (std::fstream &, FairGeoMedia *)
virtual void addRefNodes ()
virtual void write (std::fstream &)
virtual void print ()
virtual Bool_t create (FairGeoBuilder *)
void compare (FairGeoSet &)
ClassDef(FairGeoSet,
0) private FairGeoSet & operator= (const FairGeoSet &)
Protected Member Functions
FairGeoSet ()
void readInout (std::fstream &)
void readTransform (std::fstream &, FairGeoTransform &)
Bool_t readVolumeParams (std::fstream &, FairGeoMedia *, FairGeoNode *, TList *l=0)
Bool_t readKeepIn (std::fstream &, FairGeoMedia *, TString &)
Bool_t readModule (std::fstream &, FairGeoMedia *, TString &, TString &, Bool_t a=kFALSE)
Protected Attributes
Int_t hadesGeo
TList * volumes
TList * masterNodes
Int_t maxSectors
Int_t maxKeepinVolumes
Int_t maxModules
TArrayI * modules
FairGeoShapes * pShapes
TString geoFile
TString author
TString description
Detailed Description
Base class for geometry of detector parts
Author
Ilse koenig
Definition at line 25 of file FairGeoSet.h.
View newest version in sPHENIX GitHub at line 25 of file FairGeoSet.h
Constructor & Destructor Documentation
FairGeoSet::FairGeoSet () protected
description of the version
FairGeoSet::~FairGeoSet () virtual
Definition at line 50 of file FairGeoSet.cxx.
View newest version in sPHENIX GitHub at line 50 of file FairGeoSet.cxx
References modules, and volumes.
Member Function Documentation
virtual void FairGeoSet::addRefNodes () inline virtual
Reimplemented in PndGeoCave.
Definition at line 89 of file FairGeoSet.h.
View newest version in sPHENIX GitHub at line 89 of file FairGeoSet.h
void FairGeoSet::compare (FairGeoSet & rset)
Definition at line 404 of file FairGeoSet.cxx.
View newest version in sPHENIX GitHub at line 404 of file FairGeoSet.cxx
References FairGeoNode::compare(), getListOfVolumes(), getVolume(), n, and volumes.
Bool_t FairGeoSet::create (FairGeoBuilder * builder) virtual
Reimplemented in PndGeoPipe.
Definition at line 378 of file FairGeoSet.cxx.
View newest version in sPHENIX GitHub at line 378 of file FairGeoSet.cxx
References FairGeoBuilder::createNode(), FairGeoNode::getCenterPosition(), getMasterNode(), FairGeoNode::getRootVolume(), hadesGeo, FairGeoNode::isActive(), FairGeoNode::isRefNode(), FairGeoNode::isTopNode(), n, FairGeoNode::setCenterPosition(), FairGeoNode::setRootVolume(), and volumes.
Referenced by ClassImp(), PndMagnet::ConstructASCIIGeometry(), CbmRich::ConstructAsciiGeometry(), PndTarget::ConstructGeometry(), EicDetector::ConstructGeometry(), PndGeoPipe::create(), FairGeoInterface::createAll(), FairGeoInterface::createGeometry(), and FairGeoInterface::createSet().
TString& FairGeoSet::getAuthor () inline
Definition at line 81 of file FairGeoSet.h.
View newest version in sPHENIX GitHub at line 81 of file FairGeoSet.h
References author.
TString& FairGeoSet::getDescription () inline
Definition at line 82 of file FairGeoSet.h.
View newest version in sPHENIX GitHub at line 82 of file FairGeoSet.h
References description.
virtual const char* FairGeoSet::getEleName (Int_t) inline virtual
Reimplemented in PndGeoMagnet, PndGeoPipe, PndGeoTarget, and CbmGeoRich.
Definition at line 85 of file FairGeoSet.h.
View newest version in sPHENIX GitHub at line 85 of file FairGeoSet.h
Referenced by read().
const char* FairGeoSet::getGeomFile () inline
Definition at line 68 of file FairGeoSet.h.
View newest version in sPHENIX GitHub at line 68 of file FairGeoSet.h
References geoFile.
Referenced by FairGeoInterface::print(), and FairGeoInterface::readSet().
virtual const char* FairGeoSet::getKeepinName (Int_t , Int_t) inline virtual
Definition at line 83 of file FairGeoSet.h.
View newest version in sPHENIX GitHub at line 83 of file FairGeoSet.h
Referenced by read().
TList* FairGeoSet::getListOfVolumes () inline
Definition at line 77 of file FairGeoSet.h.
View newest version in sPHENIX GitHub at line 77 of file FairGeoSet.h
References volumes.
Referenced by ClassImp(), compare(), PndMagnet::ConstructASCIIGeometry(), CbmRich::ConstructAsciiGeometry(), PndTarget::ConstructGeometry(), and EicDetector::ConstructGeometry().
FairGeoNode* FairGeoSet::getMasterNode (const char * name) inline
Definition at line 76 of file FairGeoSet.h.
View newest version in sPHENIX GitHub at line 76 of file FairGeoSet.h
References masterNodes.
Referenced by create(), and readVolumeParams().
Int_t FairGeoSet::getMaxKeepinVolumes (void) inline
Definition at line 71 of file FairGeoSet.h.
View newest version in sPHENIX GitHub at line 71 of file FairGeoSet.h
References maxKeepinVolumes.
Int_t FairGeoSet::getMaxModules (void) inline
Definition at line 70 of file FairGeoSet.h.
View newest version in sPHENIX GitHub at line 70 of file FairGeoSet.h
References maxModules.
Referenced by FairGeoAsciiIo::readDetectorSetup().
Int_t FairGeoSet::getMaxSectors (void) inline
Definition at line 69 of file FairGeoSet.h.
View newest version in sPHENIX GitHub at line 69 of file FairGeoSet.h
References maxSectors.
virtual Int_t FairGeoSet::getModNumInMod (const TString &) inline virtual
Reimplemented in CbmGeoRich.
Definition at line 87 of file FairGeoSet.h.
View newest version in sPHENIX GitHub at line 87 of file FairGeoSet.h
Referenced by readModule().
Int_t FairGeoSet::getModule (Int_t s, Int_t m)
Definition at line 86 of file FairGeoSet.cxx.
View newest version in sPHENIX GitHub at line 86 of file FairGeoSet.cxx
References Acts::UnitConstants::m, maxModules, maxSectors, and modules.
Referenced by read(), and readModule().
virtual const char* FairGeoSet::getModuleName (Int_t) inline virtual
Reimplemented in PndGeoCave, PndGeoMagnet, PndGeoPipe, PndGeoTarget, and CbmGeoRich.
Definition at line 84 of file FairGeoSet.h.
View newest version in sPHENIX GitHub at line 84 of file FairGeoSet.h
Referenced by read().
Int_t * FairGeoSet::getModules (void)
Definition at line 79 of file FairGeoSet.cxx.
View newest version in sPHENIX GitHub at line 79 of file FairGeoSet.cxx
References modules.
virtual Int_t FairGeoSet::getSecNumInMod (const TString &) inline virtual
Definition at line 86 of file FairGeoSet.h.
View newest version in sPHENIX GitHub at line 86 of file FairGeoSet.h
Referenced by readModule().
FairGeoShapes* FairGeoSet::getShapes () inline
Definition at line 78 of file FairGeoSet.h.
View newest version in sPHENIX GitHub at line 78 of file FairGeoSet.h
References pShapes.
FairGeoNode* FairGeoSet::getVolume (const char * name) inline
Definition at line 75 of file FairGeoSet.h.
View newest version in sPHENIX GitHub at line 75 of file FairGeoSet.h
References volumes.
Referenced by compare(), PndGeoPipe::create(), and readVolumeParams().
ClassDef (FairGeoSet,0) private FairGeoSet& FairGeoSet::operator= (const FairGeoSet &)
void FairGeoSet::print () virtual
Reimplemented in PndGeoCave.
Definition at line 347 of file FairGeoSet.cxx.
View newest version in sPHENIX GitHub at line 347 of file FairGeoSet.cxx
References author, description, FairGeoNode::print(), and volumes.
Bool_t FairGeoSet::read (std::fstream & fin, FairGeoMedia * media) virtual
Reimplemented in PndGeoCave.
Definition at line 97 of file FairGeoSet.cxx.
View newest version in sPHENIX GitHub at line 97 of file FairGeoSet.cxx
References getEleName(), getKeepinName(), getModule(), getModuleName(), k, Acts::UnitConstants::m, maxKeepinVolumes, maxModules, maxSectors, readKeepIn(), readModule(), Acts::UnitConstants::s, s1, and s2.
void FairGeoSet::readInout (std::fstream & fin) protected
Definition at line 124 of file FairGeoSet.cxx.
View newest version in sPHENIX GitHub at line 124 of file FairGeoSet.cxx
References c.
Referenced by readKeepIn(), and readModule().
Bool_t FairGeoSet::readKeepIn (std::fstream & fin, FairGeoMedia * media, TString & name) protected
Definition at line 255 of file FairGeoSet.cxx.
View newest version in sPHENIX GitHub at line 255 of file FairGeoSet.cxx
References kFairGeoKeepin, readInout(), readVolumeParams(), FairGeoNode::setVolumeType(), and volumes.
Referenced by read().
Bool_t FairGeoSet::readModule (std::fstream & fin, FairGeoMedia * media, TString & modName, TString & eleName, Bool_t a = kFALSE) protected
Definition at line 291 of file FairGeoSet.cxx.
View newest version in sPHENIX GitHub at line 291 of file FairGeoSet.cxx
References getModNumInMod(), getModule(), getSecNumInMod(), kFairGeoElement, kFairGeoModule, name, readInout(), readVolumeParams(), FairGeoNode::setActive(), FairGeoNode::setVolumeType(), and volumes.
Referenced by read().
void FairGeoSet::readTransform (std::fstream & fin, FairGeoTransform & tf) protected
Definition at line 138 of file FairGeoSet.cxx.
View newest version in sPHENIX GitHub at line 138 of file FairGeoSet.cxx
References FairGeoTransform::setRotMatrix(), FairGeoTransform::setTransVector(), and t.
Referenced by readVolumeParams().
Bool_t FairGeoSet::readVolumeParams (std::fstream & fin, FairGeoMedia * media, FairGeoNode * volu, TList * l = 0) protected
Definition at line 148 of file FairGeoSet.cxx.
View newest version in sPHENIX GitHub at line 148 of file FairGeoSet.cxx
References c, FairGeoVolume::createPoints(), getMasterNode(), FairGeoMedia::getMedium(), FairGeoNode::getMedium(), FairGeoVolume::getNumPoints(), FairGeoVolume::getPoint(), FairGeoNode::getShapePointer(), FairGeoVolume::getTransform(), getVolume(), hadesGeo, FairGeoNode::isActive(), FairGeoNode::isKeepin(), FairGeoNode::isModule(), k, n, name, FairGeoSet::FairGeoCopyNode::pNode, pShapes, FairGeoBasicShape::readPoints(), readTransform(), FairGeoShapes::selectShape(), FairGeoNode::setActive(), FairGeoNode::setCopyNode(), FairGeoNode::setMedium(), FairGeoNode::setMother(), FairGeoVolume::setPoint(), and FairGeoNode::setShape().
Referenced by readKeepIn(), and readModule().
void FairGeoSet::setAuthor (TString & s) inline
Definition at line 79 of file FairGeoSet.h.
View newest version in sPHENIX GitHub at line 79 of file FairGeoSet.h
References author, and Acts::UnitConstants::s.
void FairGeoSet::setDescription (TString & s) inline
Definition at line 80 of file FairGeoSet.h.
View newest version in sPHENIX GitHub at line 80 of file FairGeoSet.h
References description, and Acts::UnitConstants::s.
void FairGeoSet::setGeomFile (const char * filename) inline
Definition at line 67 of file FairGeoSet.h.
View newest version in sPHENIX GitHub at line 67 of file FairGeoSet.h
References INPUTHEPMC::filename, and geoFile.
Referenced by ClassImp(), PndMagnet::ConstructASCIIGeometry(), CbmRich::ConstructAsciiGeometry(), PndTarget::ConstructGeometry(), and EicDetector::ConstructGeometry().
void FairGeoSet::setMasterNodes (TList * m) inline
Definition at line 66 of file FairGeoSet.h.
View newest version in sPHENIX GitHub at line 66 of file FairGeoSet.h
References Acts::UnitConstants::m, and masterNodes.
Referenced by FairGeoInterface::addGeoModule().
void FairGeoSet::setModules (Int_t s, Int_t * m)
Definition at line 64 of file FairGeoSet.cxx.
View newest version in sPHENIX GitHub at line 64 of file FairGeoSet.cxx
References maxModules, maxSectors, modules, and Acts::UnitConstants::s.
void FairGeoSet::setShapes (FairGeoShapes * s) inline
Definition at line 65 of file FairGeoSet.h.
View newest version in sPHENIX GitHub at line 65 of file FairGeoSet.h
References pShapes, and Acts::UnitConstants::s.
Referenced by FairGeoInterface::addGeoModule().
void FairGeoSet::write (std::fstream & fout) virtual
Reimplemented in PndGeoCave.
Definition at line 363 of file FairGeoSet.cxx.
View newest version in sPHENIX GitHub at line 363 of file FairGeoSet.cxx
References author, description, volumes, and FairGeoNode::write().
Member Data Documentation
TString FairGeoSet::author protected
name of geometry input file or Oracle
Definition at line 54 of file FairGeoSet.h.
View newest version in sPHENIX GitHub at line 54 of file FairGeoSet.h
Referenced by getAuthor(), print(), setAuthor(), and write().
TString FairGeoSet::description protected
author of the media version
Definition at line 55 of file FairGeoSet.h.
View newest version in sPHENIX GitHub at line 55 of file FairGeoSet.h
Referenced by getDescription(), print(), setDescription(), and write().
TString FairGeoSet::geoFile protected
pointer to the class FairGeoShapes
Definition at line 53 of file FairGeoSet.h.
View newest version in sPHENIX GitHub at line 53 of file FairGeoSet.h
Referenced by getGeomFile(), and setGeomFile().
Int_t FairGeoSet::hadesGeo protected
Definition at line 29 of file FairGeoSet.h.
View newest version in sPHENIX GitHub at line 29 of file FairGeoSet.h
Referenced by create(), and readVolumeParams().
TList* FairGeoSet::masterNodes protected
list of volumes
Definition at line 47 of file FairGeoSet.h.
View newest version in sPHENIX GitHub at line 47 of file FairGeoSet.h
Referenced by getMasterNode(), and setMasterNodes().
Int_t FairGeoSet::maxKeepinVolumes protected
maximum number of sectors (-1 for detectors outside any sector)
Definition at line 49 of file FairGeoSet.h.
View newest version in sPHENIX GitHub at line 49 of file FairGeoSet.h
Referenced by getMaxKeepinVolumes(), and read().
Int_t FairGeoSet::maxModules protected
maximum number of keepin volumes per sector
Definition at line 50 of file FairGeoSet.h.
View newest version in sPHENIX GitHub at line 50 of file FairGeoSet.h
Referenced by EicGeo::EicGeo(), getMaxModules(), getModule(), read(), and setModules().
Int_t FairGeoSet::maxSectors protected
pointer to list of mother volumes from other detector parts
Definition at line 48 of file FairGeoSet.h.
View newest version in sPHENIX GitHub at line 48 of file FairGeoSet.h
Referenced by EicGeo::EicGeo(), getMaxSectors(), getModule(), read(), and setModules().
TArrayI* FairGeoSet::modules protected
maximum number of modules per sector
Definition at line 51 of file FairGeoSet.h.
View newest version in sPHENIX GitHub at line 51 of file FairGeoSet.h
Referenced by getModule(), getModules(), setModules(), and ~FairGeoSet().
FairGeoShapes* FairGeoSet::pShapes protected
Module's array.
Definition at line 52 of file FairGeoSet.h.
View newest version in sPHENIX GitHub at line 52 of file FairGeoSet.h
Referenced by getShapes(), readVolumeParams(), and setShapes().
TList* FairGeoSet::volumes protected
Definition at line 46 of file FairGeoSet.h.
View newest version in sPHENIX GitHub at line 46 of file FairGeoSet.h
Referenced by compare(), create(), getListOfVolumes(), getVolume(), print(), readKeepIn(), readModule(), write(), and ~FairGeoSet().
The documentation for this class was generated from the following files:
EicRoot/blob/master/geobase/FairGeoSet.h
EicRoot/blob/master/geobase/FairGeoSet.cxx