EIC Software: fun4all_macros/blob/master/common/G4_RICH.C File Reference
G4_RICH.C File Reference
Setup the gas RICH detector as designed in ePHENIX LOI.
#include <GlobalVariables.C>
#include <g4detectors/PHG4RICHSubsystem.h>
#include <g4main/PHG4Reco.h>
Namespaces
namespace Enable
Macros
#define MACRO_G4RICH_C
Functions
void RICHInit ()
void RICHSetup (PHG4Reco *g4Reco, const int N_RICH_Sector=8, const double min_eta=1.3, const double R_mirror_ref=190, const double z_shift=75, const double R_shift=18.5, const double R_beampipe_front=8, const double R_beampipe_back=27)
Variables
bool Enable::RICH = false
Detailed Description
Setup the gas RICH detector as designed in ePHENIX LOI.
Author
Jin Huang jhuan.nosp@m.g@bn.nosp@m.l.gov
Version
Revision:
1.2
Date
Date:
2013/10/09 01:08:17
Definition in file G4_RICH.C.
Macro Definition Documentation
#define MACRO_G4RICH_C
Definition at line 9 of file G4_RICH.C.
View newest version in sPHENIX GitHub at line 9 of file G4_RICH.C
Function Documentation
void RICHInit ()
Definition at line 24 of file G4_RICH.C.
View newest version in sPHENIX GitHub at line 24 of file G4_RICH.C
References max, BlackHoleGeometry::max_radius, and BlackHoleGeometry::max_z.
Referenced by G4Init().
void RICHSetup (PHG4Reco * g4Reco, const int N_RICH_Sector = 8, const double min_eta = 1.3, const double R_mirror_ref = 190, const double z_shift = 75, const double R_shift = 18.5, const double R_beampipe_front = 8, const double R_beampipe_back = 27)
ePHENIX Gas RICH. Ref to Geometry parameter defined in ePHENIXRICH::RICH_Geometry
Parameters
[in] N_RICH_Sector number of RICH sectors
[in] min_eta minimal eta coverage
[in] R_mirror_ref Radius for the reflection layer of the mirror
Definition at line 34 of file G4_RICH.C.
View newest version in sPHENIX GitHub at line 34 of file G4_RICH.C
References PHG4RICHSubsystem::get_RICH_geometry(), Enable::OVERLAPCHECK, PHG4Subsystem::OverlapCheck(), PHG4Reco::registerSubsystem(), rich(), ePHENIXRICH::RICH_Geometry::set_min_eta(), ePHENIXRICH::RICH_Geometry::set_N_RICH_Sector(), ePHENIXRICH::RICH_Geometry::set_R_beam_pipe_back(), ePHENIXRICH::RICH_Geometry::set_R_beam_pipe_front(), ePHENIXRICH::RICH_Geometry::set_R_mirror_ref(), ePHENIXRICH::RICH_Geometry::set_R_shift(), ePHENIXRICH::RICH_Geometry::set_z_shift(), ePHENIXRICH::RICH_Geometry::Unit_cm(), and G4DIRC::z_shift.
Referenced by G4Setup().