EIC Software: Acts::SurfaceVisualization Namespace Reference
Acts::SurfaceVisualization Namespace Reference
Functions
static std::string test (IVisualization &helper, bool triangulate, const std::string &tag)
Function Documentation
static std::string Acts::SurfaceVisualization::test (IVisualization & helper, bool triangulate, const std::string & tag) inline static
Helper method to visualiza all types of surfaces
Parameters
helper The visualziation helper
triangulate The directive whether to create triangular meshes
tag The test tag (mode) identification
Returns
an overall string including all written output
Helper method to prepare the streams & helpers
Parameters
path is the file path
clear ist he indicator to clear the helper
----------— planar bounding box
Parameters
name of the file
Definition at line 46 of file SurfaceVisualizationBase.hpp.
View newest version in sPHENIX GitHub at line 46 of file SurfaceVisualizationBase.hpp
References Acts::IVisualization::clear(), Acts::Visualization::drawSurface(), Acts::Test::gctx, Acts::PrimitivesVisualization::identity, ip(), ir(), M_PI, name, offset, Acts::PrimitivesVisualization::plane, Acts::PrimitivesVisualization::rectangle, tree::write(), and Acts::IVisualization::write().
Referenced by Acts::Test::BOOST_AUTO_TEST_CASE().