EIC Software: FairFileHeader Class Reference
FairFileHeader Class Reference
#include <EicRoot/blob/master/base/FairFileHeader.h>
Public Member Functions
FairFileHeader ()
void AddTaskClassName (TString taskname)
void SetRunId (UInt_t runid)
UInt_t GetRunId ()
TList * GetListOfTasks ()
void AddInputFile (TFile *f, UInt_t id, UInt_t ChId)
virtual ~FairFileHeader ()
FairFileInfo * GetFileInfo (UInt_t id, UInt_t ChId)
Protected Attributes
UInt_t fRunId
TList * fTaskList
TList * fFileList
Private Member Functions
FairFileHeader (const FairFileHeader &)
FairFileHeader & operator= (const FairFileHeader &)
Detailed Description
File Header Class
Author
M.Al-Turany m.al-.nosp@m.tura.nosp@m.ny@gs.nosp@m.i.de
Definition at line 22 of file FairFileHeader.h.
View newest version in sPHENIX GitHub at line 22 of file FairFileHeader.h
Constructor & Destructor Documentation
FairFileHeader::FairFileHeader ()
Default constructor
Definition at line 13 of file FairFileHeader.cxx.
View newest version in sPHENIX GitHub at line 13 of file FairFileHeader.cxx
FairFileHeader::~FairFileHeader () virtual
Destructor
Definition at line 46 of file FairFileHeader.cxx.
View newest version in sPHENIX GitHub at line 46 of file FairFileHeader.cxx
FairFileHeader::FairFileHeader (const FairFileHeader &) private
Member Function Documentation
void FairFileHeader::AddInputFile (TFile * f, UInt_t id, UInt_t ChId)
Definition at line 27 of file FairFileHeader.cxx.
View newest version in sPHENIX GitHub at line 27 of file FairFileHeader.cxx
References fFileList.
Referenced by FairRootManager::AddBackgroundFile(), FairRootManager::SetBackgroundFile(), and FairRootManager::SetSignalFile().
void FairFileHeader::AddTaskClassName (TString taskname)
Add a class name of a task
Definition at line 22 of file FairFileHeader.cxx.
View newest version in sPHENIX GitHub at line 22 of file FairFileHeader.cxx
References fTaskList.
Referenced by FairRun::AddTask(), and FairRun::SetTask().
FairFileInfo * FairFileHeader::GetFileInfo (UInt_t id, UInt_t ChId)
Definition at line 32 of file FairFileHeader.cxx.
View newest version in sPHENIX GitHub at line 32 of file FairFileHeader.cxx
References fFileList, FairFileInfo::GetIdentifier(), FairFileInfo::GetOrderInChain(), and info.
TList* FairFileHeader::GetListOfTasks () inline
Return the list of tasks class names
Definition at line 42 of file FairFileHeader.h.
View newest version in sPHENIX GitHub at line 42 of file FairFileHeader.h
References fTaskList.
UInt_t FairFileHeader::GetRunId () inline
Get the run ID for this run
Definition at line 39 of file FairFileHeader.h.
View newest version in sPHENIX GitHub at line 39 of file FairFileHeader.h
References fRunId.
FairFileHeader& FairFileHeader::operator= (const FairFileHeader &) private
void FairFileHeader::SetRunId (UInt_t runid) inline
Set the run ID for this run
Parameters
runid : unique run id
Definition at line 36 of file FairFileHeader.h.
View newest version in sPHENIX GitHub at line 36 of file FairFileHeader.h
References fRunId.
Referenced by FairRunAna::Init(), and FairRunSim::Init().
Member Data Documentation
TList* FairFileHeader::fFileList protected
list of TObjStrings presenting the input files used to produce this file
Definition at line 65 of file FairFileHeader.h.
View newest version in sPHENIX GitHub at line 65 of file FairFileHeader.h
Referenced by AddInputFile(), and GetFileInfo().
UInt_t FairFileHeader::fRunId protected
Run Id
Definition at line 59 of file FairFileHeader.h.
View newest version in sPHENIX GitHub at line 59 of file FairFileHeader.h
Referenced by GetRunId(), and SetRunId().
TList* FairFileHeader::fTaskList protected
list of TObjStrings presenting the class names of tasks used to produce this file
Definition at line 62 of file FairFileHeader.h.
View newest version in sPHENIX GitHub at line 62 of file FairFileHeader.h
Referenced by AddTaskClassName(), and GetListOfTasks().
The documentation for this class was generated from the following files:
EicRoot/blob/master/base/FairFileHeader.h
EicRoot/blob/master/base/FairFileHeader.cxx