EIC Software: EICG4ZDCRawTowerBuilderByHitIndex Class Reference
EICG4ZDCRawTowerBuilderByHitIndex Class Reference
SubsysReco module creating calorimeter tower objects (RawTowerZDCv1) from hits (PHG4Hit) using j,k,l indeces of these hits.
#include <fun4all_eicdetectors/blob/master/simulation/g4simulation/g4zdc/EICG4ZDCRawTowerBuilderByHitIndex.h>
Public Member Functions
EICG4ZDCRawTowerBuilderByHitIndex (const std::string &name="EICG4ZDCRawTowerBuilderByHitIndex")
~EICG4ZDCRawTowerBuilderByHitIndex () override
int InitRun (PHCompositeNode *topNode) override
int process_event (PHCompositeNode *topNode) override
int End (PHCompositeNode *topNode) override
Called at the end of all processing.
void Detector (const std::string &d)
void SubDetector (const std::string &d)
void GeometryTableFile (const std::string &d)
void EminCut (const double e)
std::string get_sim_tower_node_prefix () const
void set_sim_tower_node_prefix (const std::string &simTowerNodePrefix)
Public Member Functions inherited from SubsysReco
~SubsysReco () override
virtual int EndRun (const int)
Called at the end of each run.
virtual int Init (PHCompositeNode *)
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
void Print (const std::string &="ALL") const override
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Private Member Functions
void CreateNodes (PHCompositeNode *topNode)
bool ReadGeometryFromTable ()
Private Attributes
RawTowerZDCContainer * m_Towers
RawTowerZDCGeomContainer * m_Geoms
std::string m_Detector
std::string m_SubDetector
std::string m_SimTowerNodePrefix
std::string m_MappingTowerFile
int m_SubDetID
RawTowerZDCDefs::CalorimeterId m_CaloId
double m_Emin
double m_TowerDepth
double m_ThicknessAbsorber
double m_ThicknessScintilator
std::map< std::string, double > m_GlobalParameterMap
std::map< int, int > m_TowerIDtoLayerIDMap
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = INT_MAX - 10
}
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Detailed Description
SubsysReco module creating calorimeter tower objects (RawTowerZDCv1) from hits (PHG4Hit) using j,k,l indeces of these hits.
Definition at line 20 of file EICG4ZDCRawTowerBuilderByHitIndex.h.
View newest version in sPHENIX GitHub at line 20 of file EICG4ZDCRawTowerBuilderByHitIndex.h
Constructor & Destructor Documentation
EICG4ZDCRawTowerBuilderByHitIndex::EICG4ZDCRawTowerBuilderByHitIndex (const std::string & name = "EICG4ZDCRawTowerBuilderByHitIndex")
Definition at line 40 of file EICG4ZDCRawTowerBuilderByHitIndex.cc.
View newest version in sPHENIX GitHub at line 40 of file EICG4ZDCRawTowerBuilderByHitIndex.cc
EICG4ZDCRawTowerBuilderByHitIndex::~EICG4ZDCRawTowerBuilderByHitIndex () inline override
Definition at line 24 of file EICG4ZDCRawTowerBuilderByHitIndex.h.
View newest version in sPHENIX GitHub at line 24 of file EICG4ZDCRawTowerBuilderByHitIndex.h
Member Function Documentation
void EICG4ZDCRawTowerBuilderByHitIndex::CreateNodes (PHCompositeNode * topNode) private
Create nodes for output.
Name of output node for RawTowerZDCContainer: "TOWER_" + detector;
Definition at line 223 of file EICG4ZDCRawTowerBuilderByHitIndex.cc.
View newest version in sPHENIX GitHub at line 223 of file EICG4ZDCRawTowerBuilderByHitIndex.cc
References PHCompositeNode::addNode(), PHNodeIterator::findFirst(), m_CaloId, m_Geoms, m_SimTowerNodePrefix, m_SubDetector, m_Towers, and PHWHERE.
Referenced by InitRun().
void EICG4ZDCRawTowerBuilderByHitIndex::Detector (const std::string & d)
Name of the detector node the G4Hits should be taken from.
Definition at line 193 of file EICG4ZDCRawTowerBuilderByHitIndex.cc.
View newest version in sPHENIX GitHub at line 193 of file EICG4ZDCRawTowerBuilderByHitIndex.cc
References d, and m_Detector.
void EICG4ZDCRawTowerBuilderByHitIndex::EminCut (const double e) inline
Define minimum tower energy. After processing an event, towers with lower energy are will be deleted.
Definition at line 48 of file EICG4ZDCRawTowerBuilderByHitIndex.h.
View newest version in sPHENIX GitHub at line 48 of file EICG4ZDCRawTowerBuilderByHitIndex.h
References Acts::UnitConstants::e, and m_Emin.
int EICG4ZDCRawTowerBuilderByHitIndex::End (PHCompositeNode *) override virtual
Called at the end of all processing.
Reimplemented from SubsysReco.
Definition at line 188 of file EICG4ZDCRawTowerBuilderByHitIndex.cc.
View newest version in sPHENIX GitHub at line 188 of file EICG4ZDCRawTowerBuilderByHitIndex.cc
References Fun4AllReturnCodes::EVENT_OK.
void EICG4ZDCRawTowerBuilderByHitIndex::GeometryTableFile (const std::string & d) inline
Specifiy text-file with table for tower mapping
Definition at line 40 of file EICG4ZDCRawTowerBuilderByHitIndex.h.
View newest version in sPHENIX GitHub at line 40 of file EICG4ZDCRawTowerBuilderByHitIndex.h
References d, and m_MappingTowerFile.
std::string EICG4ZDCRawTowerBuilderByHitIndex::get_sim_tower_node_prefix () const inline
Get prefix for tower collection to identify simulated towers before digitization.
Definition at line 54 of file EICG4ZDCRawTowerBuilderByHitIndex.h.
View newest version in sPHENIX GitHub at line 54 of file EICG4ZDCRawTowerBuilderByHitIndex.h
References m_SimTowerNodePrefix.
int EICG4ZDCRawTowerBuilderByHitIndex::InitRun (PHCompositeNode *) override virtual
Called for first event when run number is known. Typically this is where you may want to fetch data from database, because you know the run number.
Reimplemented from SubsysReco.
Definition at line 55 of file EICG4ZDCRawTowerBuilderByHitIndex.cc.
View newest version in sPHENIX GitHub at line 55 of file EICG4ZDCRawTowerBuilderByHitIndex.cc
References CreateNodes(), Acts::UnitConstants::e, Fun4AllReturnCodes::EVENT_OK, exit(), PHNodeIterator::findFirst(), PHWHERE, and ReadGeometryFromTable().
int EICG4ZDCRawTowerBuilderByHitIndex::process_event (PHCompositeNode *) override virtual
Called for each event. This is where you do the real work.
Reimplemented from SubsysReco.
Definition at line 91 of file EICG4ZDCRawTowerBuilderByHitIndex.cc.
View newest version in sPHENIX GitHub at line 91 of file EICG4ZDCRawTowerBuilderByHitIndex.cc
References RawTowerZDCContainer::AddTower(), RawTowerZDCContainer::compress(), ZDCID::Crystal, RawTowerZDCDefs::encode_towerid_zdc(), Fun4AllReturnCodes::EVENT_OK, exit(), PHG4Hit::get_edep(), PHG4Hit::get_hit_type(), PHG4Hit::get_index_i(), PHG4Hit::get_index_j(), PHG4Hit::get_layer(), PHG4Hit::get_light_yield(), PHG4Hit::get_shower_id(), PHG4HitContainer::getHits(), RawTowerZDCContainer::getTotalEdep(), RawTowerZDCContainer::getTower(), RawTowerZDCContainer::getTowers(), RawTowerZDCContainer::identify(), it, m_CaloId, m_Detector, m_Emin, m_SubDetector, m_SubDetID, m_TowerIDtoLayerIDMap, m_Towers, ZDCID::Scintillator, RawTowerZDCContainer::size(), and Fun4AllBase::Verbosity().
bool EICG4ZDCRawTowerBuilderByHitIndex::ReadGeometryFromTable () private
Read geometry information from table stored in text-file
Definition at line 276 of file EICG4ZDCRawTowerBuilderByHitIndex.cc.
View newest version in sPHENIX GitHub at line 276 of file EICG4ZDCRawTowerBuilderByHitIndex.cc
References RawTowerZDCGeomContainer::add_tower_geometry(), RawTowerZDCDefs::encode_towerid_zdc(), exit(), RawTowerZDCGeomContainer::get_tower_geometries(), getline, it, m_CaloId, m_Geoms, m_GlobalParameterMap, m_MappingTowerFile, m_SubDetector, m_TowerIDtoLayerIDMap, RawTowerZDCGeomv1::set_center_x(), RawTowerZDCGeomv1::set_center_y(), RawTowerZDCGeomv1::set_center_z(), RawTowerZDCGeomv1::set_size_x(), RawTowerZDCGeomv1::set_size_y(), RawTowerZDCGeomv1::set_size_z(), G4CTD::size_z, and Fun4AllBase::Verbosity().
Referenced by InitRun().
void EICG4ZDCRawTowerBuilderByHitIndex::set_sim_tower_node_prefix (const std::string & simTowerNodePrefix) inline
Set prefix for tower collection to identify simulated towers before digitization.
Definition at line 63 of file EICG4ZDCRawTowerBuilderByHitIndex.h.
View newest version in sPHENIX GitHub at line 63 of file EICG4ZDCRawTowerBuilderByHitIndex.h
References m_SimTowerNodePrefix.
void EICG4ZDCRawTowerBuilderByHitIndex::SubDetector (const std::string & d)
Definition at line 199 of file EICG4ZDCRawTowerBuilderByHitIndex.cc.
View newest version in sPHENIX GitHub at line 199 of file EICG4ZDCRawTowerBuilderByHitIndex.cc
References RawTowerZDCDefs::convert_name_to_caloid(), ZDCID::Crystal, d, exit(), m_CaloId, m_SubDetector, m_SubDetID, ZDCID::Scintillator, ZDCID::SI_PAD, and ZDCID::SI_PIXEL.
Member Data Documentation
RawTowerZDCDefs::CalorimeterId EICG4ZDCRawTowerBuilderByHitIndex::m_CaloId private
Definition at line 90 of file EICG4ZDCRawTowerBuilderByHitIndex.h.
View newest version in sPHENIX GitHub at line 90 of file EICG4ZDCRawTowerBuilderByHitIndex.h
Referenced by CreateNodes(), process_event(), ReadGeometryFromTable(), and SubDetector().
std::string EICG4ZDCRawTowerBuilderByHitIndex::m_Detector private
Definition at line 82 of file EICG4ZDCRawTowerBuilderByHitIndex.h.
View newest version in sPHENIX GitHub at line 82 of file EICG4ZDCRawTowerBuilderByHitIndex.h
Referenced by Detector(), and process_event().
double EICG4ZDCRawTowerBuilderByHitIndex::m_Emin private
Definition at line 92 of file EICG4ZDCRawTowerBuilderByHitIndex.h.
View newest version in sPHENIX GitHub at line 92 of file EICG4ZDCRawTowerBuilderByHitIndex.h
Referenced by EminCut(), and process_event().
RawTowerZDCGeomContainer* EICG4ZDCRawTowerBuilderByHitIndex::m_Geoms private
Definition at line 80 of file EICG4ZDCRawTowerBuilderByHitIndex.h.
View newest version in sPHENIX GitHub at line 80 of file EICG4ZDCRawTowerBuilderByHitIndex.h
Referenced by CreateNodes(), and ReadGeometryFromTable().
std::map<std::string, double> EICG4ZDCRawTowerBuilderByHitIndex::m_GlobalParameterMap private
Definition at line 96 of file EICG4ZDCRawTowerBuilderByHitIndex.h.
View newest version in sPHENIX GitHub at line 96 of file EICG4ZDCRawTowerBuilderByHitIndex.h
Referenced by ReadGeometryFromTable().
std::string EICG4ZDCRawTowerBuilderByHitIndex::m_MappingTowerFile private
Definition at line 86 of file EICG4ZDCRawTowerBuilderByHitIndex.h.
View newest version in sPHENIX GitHub at line 86 of file EICG4ZDCRawTowerBuilderByHitIndex.h
Referenced by GeometryTableFile(), and ReadGeometryFromTable().
std::string EICG4ZDCRawTowerBuilderByHitIndex::m_SimTowerNodePrefix private
Definition at line 84 of file EICG4ZDCRawTowerBuilderByHitIndex.h.
View newest version in sPHENIX GitHub at line 84 of file EICG4ZDCRawTowerBuilderByHitIndex.h
Referenced by CreateNodes(), get_sim_tower_node_prefix(), and set_sim_tower_node_prefix().
std::string EICG4ZDCRawTowerBuilderByHitIndex::m_SubDetector private
Definition at line 83 of file EICG4ZDCRawTowerBuilderByHitIndex.h.
View newest version in sPHENIX GitHub at line 83 of file EICG4ZDCRawTowerBuilderByHitIndex.h
Referenced by CreateNodes(), process_event(), ReadGeometryFromTable(), and SubDetector().
int EICG4ZDCRawTowerBuilderByHitIndex::m_SubDetID private
Definition at line 88 of file EICG4ZDCRawTowerBuilderByHitIndex.h.
View newest version in sPHENIX GitHub at line 88 of file EICG4ZDCRawTowerBuilderByHitIndex.h
Referenced by process_event(), and SubDetector().
double EICG4ZDCRawTowerBuilderByHitIndex::m_ThicknessAbsorber private
Definition at line 94 of file EICG4ZDCRawTowerBuilderByHitIndex.h.
View newest version in sPHENIX GitHub at line 94 of file EICG4ZDCRawTowerBuilderByHitIndex.h
double EICG4ZDCRawTowerBuilderByHitIndex::m_ThicknessScintilator private
Definition at line 95 of file EICG4ZDCRawTowerBuilderByHitIndex.h.
View newest version in sPHENIX GitHub at line 95 of file EICG4ZDCRawTowerBuilderByHitIndex.h
double EICG4ZDCRawTowerBuilderByHitIndex::m_TowerDepth private
Definition at line 93 of file EICG4ZDCRawTowerBuilderByHitIndex.h.
View newest version in sPHENIX GitHub at line 93 of file EICG4ZDCRawTowerBuilderByHitIndex.h
std::map<int, int> EICG4ZDCRawTowerBuilderByHitIndex::m_TowerIDtoLayerIDMap private
Definition at line 97 of file EICG4ZDCRawTowerBuilderByHitIndex.h.
View newest version in sPHENIX GitHub at line 97 of file EICG4ZDCRawTowerBuilderByHitIndex.h
Referenced by process_event(), and ReadGeometryFromTable().
RawTowerZDCContainer* EICG4ZDCRawTowerBuilderByHitIndex::m_Towers private
Definition at line 79 of file EICG4ZDCRawTowerBuilderByHitIndex.h.
View newest version in sPHENIX GitHub at line 79 of file EICG4ZDCRawTowerBuilderByHitIndex.h
Referenced by CreateNodes(), and process_event().
The documentation for this class was generated from the following files:
fun4all_eicdetectors/blob/master/simulation/g4simulation/g4zdc/EICG4ZDCRawTowerBuilderByHitIndex.h
fun4all_eicdetectors/blob/master/simulation/g4simulation/g4zdc/EICG4ZDCRawTowerBuilderByHitIndex.cc