EIC Software: Module Class Reference
Module Class Reference
#include <delphes_EIC/blob/master/SimpleAnalysis/Module.h>
Public Member Functions
Module (ExRootTreeReader *data)
~Module ()
virtual void initialize ()
virtual bool execute (std::map< std::string, std::any > *DataStore)
virtual void finalize ()
ExRootTreeReader * getData ()
void setJets (TClonesArray *jets)
void setElectrons (TClonesArray *electrons)
void setPhotons (TClonesArray *photons)
void setNeutralHadrons (TClonesArray *neutralhadrons)
void setMuons (TClonesArray *muons)
void setTracks (TClonesArray *tracks)
void setEFlowTracks (TClonesArray *tracks)
void setMET (TClonesArray *met)
void setGenParticles (TClonesArray *particles)
void setGenJets (TClonesArray *genjets)
TClonesArray * getJets ()
TClonesArray * getElectrons ()
TClonesArray * getPhotons ()
TClonesArray * getNeutralHadrons ()
TClonesArray * getMuons ()
TClonesArray * getEFlowTracks ()
TClonesArray * getTracks ()
TClonesArray * getMET ()
TClonesArray * getGenParticles ()
TClonesArray * getGenJets ()
Private Attributes
ExRootTreeReader * _data = nullptr
TClonesArray * _jets = nullptr
TClonesArray * _electrons = nullptr
TClonesArray * _photons = nullptr
TClonesArray * _neutralhadrons = nullptr
TClonesArray * _muons = nullptr
TClonesArray * _tracks = nullptr
TClonesArray * _eflowtracks = nullptr
TClonesArray * _met = nullptr
TClonesArray * _genparticles = nullptr
TClonesArray * _genjets = nullptr
Detailed Description
Definition at line 16 of file Module.h.
View newest version in sPHENIX GitHub at line 16 of file Module.h
Constructor & Destructor Documentation
Module::Module (ExRootTreeReader * data)
Definition at line 3 of file Module.cc.
View newest version in sPHENIX GitHub at line 3 of file Module.cc
References _data, and data.
Module::~Module ()
Definition at line 8 of file Module.cc.
View newest version in sPHENIX GitHub at line 8 of file Module.cc
Member Function Documentation
bool Module::execute (std::map< std::string, std::any > * DataStore) virtual
Reimplemented in EventSelectionModule, ElectronPIDModule, KaonPIDModule, MuonPIDModule, TaggingModule, TaggingStudyModule, and CharmJetModule.
Definition at line 16 of file Module.cc.
View newest version in sPHENIX GitHub at line 16 of file Module.cc
void Module::finalize () virtual
Reimplemented in EventSelectionModule, ElectronPIDModule, KaonPIDModule, MuonPIDModule, TaggingModule, TaggingStudyModule, and CharmJetModule.
Definition at line 21 of file Module.cc.
View newest version in sPHENIX GitHub at line 21 of file Module.cc
ExRootTreeReader* Module::getData () inline
Definition at line 28 of file Module.h.
View newest version in sPHENIX GitHub at line 28 of file Module.h
References _data.
Referenced by CharmJetModule::execute(), ElectronPIDModule::execute(), TaggingModule::execute(), TaggingStudyModule::execute(), KaonPIDModule::execute(), MuonPIDModule::execute(), EventSelectionModule::execute(), and EventSelectionModule::initialize().
TClonesArray* Module::getEFlowTracks () inline
Definition at line 49 of file Module.h.
View newest version in sPHENIX GitHub at line 49 of file Module.h
References _eflowtracks.
Referenced by ElectronPIDModule::execute(), TaggingStudyModule::execute(), TaggingModule::execute(), MuonPIDModule::execute(), KaonPIDModule::execute(), and EventSelectionModule::execute().
TClonesArray* Module::getElectrons () inline
Definition at line 45 of file Module.h.
View newest version in sPHENIX GitHub at line 45 of file Module.h
References _electrons.
Referenced by EventSelectionModule::execute().
TClonesArray* Module::getGenJets () inline
Definition at line 53 of file Module.h.
View newest version in sPHENIX GitHub at line 53 of file Module.h
References _genjets.
TClonesArray* Module::getGenParticles () inline
Definition at line 52 of file Module.h.
View newest version in sPHENIX GitHub at line 52 of file Module.h
References _genparticles.
Referenced by EventSelectionModule::execute().
TClonesArray* Module::getJets () inline
Definition at line 44 of file Module.h.
View newest version in sPHENIX GitHub at line 44 of file Module.h
References _jets.
Referenced by CharmJetModule::execute(), TaggingStudyModule::execute(), TaggingModule::execute(), and EventSelectionModule::execute().
TClonesArray* Module::getMET () inline
Definition at line 51 of file Module.h.
View newest version in sPHENIX GitHub at line 51 of file Module.h
References _met.
Referenced by TaggingStudyModule::execute(), and EventSelectionModule::execute().
TClonesArray* Module::getMuons () inline
Definition at line 48 of file Module.h.
View newest version in sPHENIX GitHub at line 48 of file Module.h
References _muons.
TClonesArray* Module::getNeutralHadrons () inline
Definition at line 47 of file Module.h.
View newest version in sPHENIX GitHub at line 47 of file Module.h
References _neutralhadrons.
Referenced by EventSelectionModule::execute().
TClonesArray* Module::getPhotons () inline
Definition at line 46 of file Module.h.
View newest version in sPHENIX GitHub at line 46 of file Module.h
References _photons.
Referenced by EventSelectionModule::execute().
TClonesArray* Module::getTracks () inline
Definition at line 50 of file Module.h.
View newest version in sPHENIX GitHub at line 50 of file Module.h
References _tracks.
Referenced by EventSelectionModule::execute().
void Module::initialize () virtual
Reimplemented in EventSelectionModule, ElectronPIDModule, KaonPIDModule, MuonPIDModule, TaggingModule, TaggingStudyModule, and CharmJetModule.
Definition at line 12 of file Module.cc.
View newest version in sPHENIX GitHub at line 12 of file Module.cc
void Module::setEFlowTracks (TClonesArray * tracks) inline
Definition at line 38 of file Module.h.
View newest version in sPHENIX GitHub at line 38 of file Module.h
References _eflowtracks.
void Module::setElectrons (TClonesArray * electrons) inline
Definition at line 33 of file Module.h.
View newest version in sPHENIX GitHub at line 33 of file Module.h
References _electrons.
void Module::setGenJets (TClonesArray * genjets) inline
Definition at line 42 of file Module.h.
View newest version in sPHENIX GitHub at line 42 of file Module.h
References _genjets.
void Module::setGenParticles (TClonesArray * particles) inline
Definition at line 41 of file Module.h.
View newest version in sPHENIX GitHub at line 41 of file Module.h
References _genparticles.
void Module::setJets (TClonesArray * jets) inline
Definition at line 32 of file Module.h.
View newest version in sPHENIX GitHub at line 32 of file Module.h
References _jets.
void Module::setMET (TClonesArray * met) inline
Definition at line 39 of file Module.h.
View newest version in sPHENIX GitHub at line 39 of file Module.h
References _met.
void Module::setMuons (TClonesArray * muons) inline
Definition at line 36 of file Module.h.
View newest version in sPHENIX GitHub at line 36 of file Module.h
References _muons.
void Module::setNeutralHadrons (TClonesArray * neutralhadrons) inline
Definition at line 35 of file Module.h.
View newest version in sPHENIX GitHub at line 35 of file Module.h
References _neutralhadrons.
void Module::setPhotons (TClonesArray * photons) inline
Definition at line 34 of file Module.h.
View newest version in sPHENIX GitHub at line 34 of file Module.h
References _photons.
void Module::setTracks (TClonesArray * tracks) inline
Definition at line 37 of file Module.h.
View newest version in sPHENIX GitHub at line 37 of file Module.h
References _tracks.
Member Data Documentation
ExRootTreeReader* Module::_data = nullptr private
Definition at line 57 of file Module.h.
View newest version in sPHENIX GitHub at line 57 of file Module.h
Referenced by getData(), and Module().
TClonesArray* Module::_eflowtracks = nullptr private
Definition at line 67 of file Module.h.
View newest version in sPHENIX GitHub at line 67 of file Module.h
Referenced by getEFlowTracks(), and setEFlowTracks().
TClonesArray* Module::_electrons = nullptr private
Definition at line 62 of file Module.h.
View newest version in sPHENIX GitHub at line 62 of file Module.h
Referenced by getElectrons(), and setElectrons().
TClonesArray* Module::_genjets = nullptr private
Definition at line 72 of file Module.h.
View newest version in sPHENIX GitHub at line 72 of file Module.h
Referenced by getGenJets(), and setGenJets().
TClonesArray* Module::_genparticles = nullptr private
Definition at line 71 of file Module.h.
View newest version in sPHENIX GitHub at line 71 of file Module.h
Referenced by getGenParticles(), and setGenParticles().
TClonesArray* Module::_jets = nullptr private
Definition at line 61 of file Module.h.
View newest version in sPHENIX GitHub at line 61 of file Module.h
Referenced by getJets(), and setJets().
TClonesArray* Module::_met = nullptr private
Definition at line 69 of file Module.h.
View newest version in sPHENIX GitHub at line 69 of file Module.h
Referenced by getMET(), and setMET().
TClonesArray* Module::_muons = nullptr private
Definition at line 65 of file Module.h.
View newest version in sPHENIX GitHub at line 65 of file Module.h
Referenced by getMuons(), and setMuons().
TClonesArray* Module::_neutralhadrons = nullptr private
Definition at line 64 of file Module.h.
View newest version in sPHENIX GitHub at line 64 of file Module.h
Referenced by getNeutralHadrons(), and setNeutralHadrons().
TClonesArray* Module::_photons = nullptr private
Definition at line 63 of file Module.h.
View newest version in sPHENIX GitHub at line 63 of file Module.h
Referenced by getPhotons(), and setPhotons().
TClonesArray* Module::_tracks = nullptr private
Definition at line 66 of file Module.h.
View newest version in sPHENIX GitHub at line 66 of file Module.h
Referenced by getTracks(), and setTracks().
The documentation for this class was generated from the following files:
delphes_EIC/blob/master/SimpleAnalysis/Module.h
delphes_EIC/blob/master/SimpleAnalysis/Module.cc