EIC Software: FW::Options Namespace Reference
FW::Options Namespace Reference
Classes
struct Interval
Typedefs
using BFieldVariant = std::variant< std::shared_ptr< InterpolatedBFieldMap2D >, std::shared_ptr< InterpolatedBFieldMap3D >, std::shared_ptr< Acts::ConstantBField >, std::shared_ptr< FW::BField::ScalableBField >>
using Description = ::boost::program_options::options_description
using Variables = ::boost::program_options::variables_map
Functions
void addFatrasOptions (Description &desc)
template<typename simulator_t >
FatrasAlgorithm< simulator_t >
::Config readFatrasConfig (const Variables &variables, simulator_t &&simulator)
void addParticleGunOptions (boost::program_options::options_description &opt)
Add options for a particle-gun-like event generator.
EventGenerator::Config readParticleGunOptions (const boost::program_options::variables_map &vm)
Create the event generator config from particle-gun options.
void addPythia8Options (boost::program_options::options_description &opt)
EventGenerator::Config readPythia8Options (const boost::program_options::variables_map &vm, Acts::Logging::Level lvl)
template<typename aopt_t >
void addMaterialMappingOptions (aopt_t &opt)
Material mapping options, specially added.
template<typename aopt_t >
void addPropagationOptions (aopt_t &opt)
ExtrapolationAlgorithm options.
template<typename vmap_t , typename propagator_t >
FW::PropagationAlgorithm
< propagator_t >::Config readPropagationConfig (const vmap_t &vm, propagator_t propagator)
void sortFCChhDetElements (std::vector< dd4hep::DetElement > &det)
template<typename aopt_t >
void addDD4hepOptions (aopt_t &opt)
the particle gun options, the are prefixes with gp
template<typename amap_t >
FW::DD4hep::DD4hepGeometryService::Config readDD4hepConfig (const amap_t &vm)
read the particle gun options and return a Config file
template<typename options_t >
void addEmptyGeometryOptions (options_t &opt)
template<typename options_t >
void addGenericGeometryOptions (options_t &opt)
void addBFieldOptions (boost::program_options::options_description &opt)
BFieldVariant readBField (const boost::program_options::variables_map &vm)
template<typename options_t >
void addTGeoGeometryOptions (options_t &opt)
template<typename variable_map_t >
std::vector
< Acts::TGeoLayerBuilder::Config > readTGeoLayerBuilderConfigs (const variable_map_t &vm, std::shared_ptr< const Acts::LayerCreator > layerCreator)
Read the specific options for the ROOT detector.
std::istream & operator>> (std::istream &is, Interval &interval)
std::ostream & operator<< (std::ostream &os, const Interval &interval)
Print an interval as lower:upper.
FW::CsvParticleReader::Config readCsvParticleReaderConfig (const Variables &vm)
Read the CSV particle reader config.
FW::CsvPlanarClusterReader::Config readCsvPlanarClusterReaderConfig (const Variables &vm)
Read the CSV particle reader config.
void addCsvWriterOptions (Description &desc)
FW::CsvParticleWriter::Config readCsvParticleWriterConfig (const Variables &vm)
Read the CSV particle writer options.
FW::CsvPlanarClusterWriter::Config readCsvPlanarClusterWriterConfig (const Variables &vm)
Read the CSV planar cluster writer options.
FW::CsvTrackingGeometryWriter::Config readCsvTrackingGeometryWriterConfig (const Variables &vm)
Read the CSV tracking geometry writer config.
template<typename aopt_t >
void addObjWriterOptions (aopt_t &opt)
template<class AMAP >
FW::Obj::ObjTrackingGeometryWriter::Config readObjTrackingGeometryWriterConfig (const AMAP &vm, const std::string &name, Acts::Logging::Level loglevel=Acts::Logging::INFO)
read the evgen options and return a Config file
template<class AMAP >
FW::Obj::ObjSurfaceWriter::Config readObjSurfaceWriterConfig (const AMAP &vm, const std::string &name, Acts::Logging::Level loglevel)
boost::program_options::options_description makeDefaultOptions (std::string caption=std::string())
void addSequencerOptions (boost::program_options::options_description &opt)
Add sequencer options, e.g. number of events.
void addRandomNumbersOptions (boost::program_options::options_description &opt)
Add random number options such as the global seed.
void addGeometryOptions (boost::program_options::options_description &opt)
Add common geometry-related options.
void addMaterialOptions (boost::program_options::options_description &opt)
Add common material-related options.
void addInputOptions (boost::program_options::options_description &opt)
Add common input-related options.
void addOutputOptions (boost::program_options::options_description &opt)
Add common output-related options.
boost::program_options::variables_map parse (const boost::program_options::options_description &opt, int argc, char *argv[])
Acts::Logging::Level readLogLevel (const boost::program_options::variables_map &vm)
Read the log level.
Sequencer::Config readSequencerConfig (const boost::program_options::variables_map &vm)
Read the sequencer config.
RandomNumbers::Config readRandomNumbersConfig (const boost::program_options::variables_map &vm)
Typedef Documentation
using FW::Options::BFieldVariant = typedef std::variant<std::shared_ptr<InterpolatedBFieldMap2D>, std::shared_ptr<InterpolatedBFieldMap3D>, std::shared_ptr<Acts::ConstantBField>, std::shared_ptr<FW::BField::ScalableBField>>
Definition at line 57 of file BFieldOptions.hpp.
View newest version in sPHENIX GitHub at line 57 of file BFieldOptions.hpp
using FW::Options::Description = typedef ::boost::program_options::options_description
Definition at line 20 of file OptionsFwd.hpp.
View newest version in sPHENIX GitHub at line 20 of file OptionsFwd.hpp
using FW::Options::Variables = typedef ::boost::program_options::variables_map
Definition at line 21 of file OptionsFwd.hpp.
View newest version in sPHENIX GitHub at line 21 of file OptionsFwd.hpp
Function Documentation
void FW::Options::addBFieldOptions (boost::program_options::options_description & opt)
Definition at line 44 of file BFieldOptions.cpp.
View newest version in sPHENIX GitHub at line 44 of file BFieldOptions.cpp
Referenced by AlignedDetector::addOptions(), PayloadDetector::addOptions(), main(), MakeActsGeometry::makeGeometry(), materialValidationExample(), and propagationExample().
void FW::Options::addCsvWriterOptions (Description & desc)
Definition at line 15 of file CsvOptionsWriter.cpp.
View newest version in sPHENIX GitHub at line 15 of file CsvOptionsWriter.cpp
Referenced by processGeometry().
template<typename aopt_t > void FW::Options::addDD4hepOptions (aopt_t & opt)
the particle gun options, the are prefixes with gp
Definition at line 68 of file DD4hepDetectorOptions.hpp.
View newest version in sPHENIX GitHub at line 68 of file DD4hepDetectorOptions.hpp
References Acts::units::_mm, and analysis::e.
Referenced by DD4hepDetector::addOptions(), and main().
template<typename options_t > void FW::Options::addEmptyGeometryOptions (options_t & opt)
The empty geometry options, the are prefixes with geo-generic
Template Parameters
options_t Type of the options object (bound to boost API)
Parameters
opt The provided object, where root specific options are attached
Definition at line 29 of file EmptyDetectorOptions.hpp.
View newest version in sPHENIX GitHub at line 29 of file EmptyDetectorOptions.hpp
References Acts::units::_m.
Referenced by EmptyDetector::addOptions().
void FW::Options::addFatrasOptions (Description & desc)
Add Fatras options.
Parameters
desc The options description to add options to
Definition at line 13 of file FatrasOptions.cpp.
View newest version in sPHENIX GitHub at line 13 of file FatrasOptions.cpp
References value.
template<typename options_t > void FW::Options::addGenericGeometryOptions (options_t & opt)
The generic geometry options, the are prefixes with geo-generic
Template Parameters
options_t Type of the options object (bound to boost API)
Parameters
opt The provided object, where root specific options are attached
Definition at line 29 of file GenericDetectorOptions.hpp.
View newest version in sPHENIX GitHub at line 29 of file GenericDetectorOptions.hpp
Referenced by AlignedDetector::addOptions(), GenericDetector::addOptions(), and PayloadDetector::addOptions().
void FW::Options::addGeometryOptions (boost::program_options::options_description & opt)
Add common geometry-related options.
Definition at line 52 of file CommonOptions.cpp.
View newest version in sPHENIX GitHub at line 52 of file CommonOptions.cpp
Referenced by main(), MakeActsGeometry::makeGeometry(), materialMappingExample(), materialValidationExample(), processGeometry(), and propagationExample().
void FW::Options::addInputOptions (boost::program_options::options_description & opt)
Add common input-related options.
Definition at line 107 of file CommonOptions.cpp.
View newest version in sPHENIX GitHub at line 107 of file CommonOptions.cpp
Referenced by main(), and materialMappingExample().
template<typename aopt_t > void FW::Options::addMaterialMappingOptions (aopt_t & opt)
Material mapping options, specially added.
Template Parameters
aopt_t Type of the options object (API bound to boost)
Parameters
[in] opt_t The options object where the specific digitization options are attached to
Definition at line 29 of file MaterialMappingOptions.hpp.
View newest version in sPHENIX GitHub at line 29 of file MaterialMappingOptions.hpp
Referenced by materialMappingExample().
void FW::Options::addMaterialOptions (boost::program_options::options_description & opt)
Add common material-related options.
Definition at line 65 of file CommonOptions.cpp.
View newest version in sPHENIX GitHub at line 65 of file CommonOptions.cpp
Referenced by main(), MakeActsGeometry::makeGeometry(), materialMappingExample(), materialValidationExample(), processGeometry(), and propagationExample().
template<typename aopt_t > void FW::Options::addObjWriterOptions (aopt_t & opt)
Common obj writing options
Template Parameters
aopt_t Type of the options object (from BOOST)
Parameters
opt The options object, where string based options are attached
Definition at line 30 of file ObjWriterOptions.hpp.
View newest version in sPHENIX GitHub at line 30 of file ObjWriterOptions.hpp
Referenced by MakeActsGeometry::makeGeometry(), and processGeometry().
void FW::Options::addOutputOptions (boost::program_options::options_description & opt)
Add common output-related options.
Definition at line 90 of file CommonOptions.cpp.
View newest version in sPHENIX GitHub at line 90 of file CommonOptions.cpp
Referenced by main(), MakeActsGeometry::makeGeometry(), materialMappingExample(), materialValidationExample(), processGeometry(), and propagationExample().
void FW::Options::addParticleGunOptions (boost::program_options::options_description & opt)
Add options for a particle-gun-like event generator.
Definition at line 17 of file ParticleGunOptions.cpp.
View newest version in sPHENIX GitHub at line 17 of file ParticleGunOptions.cpp
References Acts::eMuon, and M_PI.
Referenced by main().
template<typename aopt_t > void FW::Options::addPropagationOptions (aopt_t & opt)
ExtrapolationAlgorithm options.
Template Parameters
aopt_t Type of the options class from boost
Definition at line 29 of file PropagationOptions.hpp.
View newest version in sPHENIX GitHub at line 29 of file PropagationOptions.hpp
References Acts::units::_GeV, Acts::units::_m, Acts::units::_MeV, Acts::units::_mm, Acts::units::_um, and M_PI.
Referenced by materialMappingExample(), materialValidationExample(), and propagationExample().
void FW::Options::addPythia8Options (boost::program_options::options_description & opt)
Options for a Pythia8-based event-generator w/ hard scatter, variable pile-up, and smeared vertices.
Definition at line 19 of file Pythia8Options.cpp.
View newest version in sPHENIX GitHub at line 19 of file Pythia8Options.cpp
References Acts::eProton.
Referenced by main().
void FW::Options::addRandomNumbersOptions (boost::program_options::options_description & opt)
Add random number options such as the global seed.
Definition at line 46 of file CommonOptions.cpp.
View newest version in sPHENIX GitHub at line 46 of file CommonOptions.cpp
References Acts::UnitConstants::u.
Referenced by main(), materialValidationExample(), and propagationExample().
void FW::Options::addSequencerOptions (boost::program_options::options_description & opt)
Add sequencer options, e.g. number of events.
Definition at line 34 of file CommonOptions.cpp.
View newest version in sPHENIX GitHub at line 34 of file CommonOptions.cpp
Referenced by main(), materialMappingExample(), materialValidationExample(), processGeometry(), and propagationExample().
template<typename options_t > void FW::Options::addTGeoGeometryOptions (options_t & opt)
The root detecotr options, the are prefixes with geo-tgeo
Template Parameters
options_t Type of the options object (bound to boost API)
Parameters
opt The provided object, where root specific options are attached
Definition at line 34 of file TGeoDetectorOptions.hpp.
View newest version in sPHENIX GitHub at line 34 of file TGeoDetectorOptions.hpp
Referenced by TGeoDetector::addOptions().
boost::program_options::options_description FW::Options::makeDefaultOptions (std::string caption = std::string())
Construct the options description with minimal default options.
Parameters
caption Optional help text caption
Definition at line 18 of file CommonOptions.cpp.
View newest version in sPHENIX GitHub at line 18 of file CommonOptions.cpp
Referenced by main(), MakeActsGeometry::makeGeometry(), materialMappingExample(), materialValidationExample(), processGeometry(), and propagationExample().
std::ostream & FW::Options::operator<< (std::ostream & os, const Interval & interval)
Print an interval as lower:upper.
Definition at line 49 of file Options.cpp.
View newest version in sPHENIX GitHub at line 49 of file Options.cpp
References FW::Options::Interval::lower, and FW::Options::Interval::upper.
std::istream & FW::Options::operator>> (std::istream & is, Interval & interval)
Extract an interval from an input of the form 'lower:upper'.
An input of the form lower: or :upper sets just one of the limits. Any other input leads to an unbounded interval. If the input is :SECOND the
Note
The more common range notation uses lower-upper but the - separator complicates the parsing of negative values.
Definition at line 19 of file Options.cpp.
View newest version in sPHENIX GitHub at line 19 of file Options.cpp
References FW::Options::Interval::lower, Acts::Test::pos, and FW::Options::Interval::upper.
boost::program_options::variables_map FW::Options::parse (const boost::program_options::options_description & opt, int argc, char * argv[]) noexcept
Parse options and return the resulting variables map.
Automatically prints the help text if requested.
Returns
Empty variables map if help text was shown.
Definition at line 124 of file CommonOptions.cpp.
View newest version in sPHENIX GitHub at line 124 of file CommonOptions.cpp
References charm_jet_coverage::args, and eicpy.build::options.
Referenced by main(), materialMappingExample(), materialValidationExample(), processGeometry(), and propagationExample().
BFieldVariant FW::Options::readBField (const boost::program_options::variables_map & vm)
Definition at line 84 of file BFieldOptions.cpp.
View newest version in sPHENIX GitHub at line 84 of file BFieldOptions.cpp
References Acts::units::_mm, Acts::units::_T, FW::BField::txt::fieldMapperRZ(), FW::BField::root::fieldMapperRZ(), FW::BField::txt::fieldMapperXYZ(), FW::BField::root::fieldMapperXYZ(), and Acts::InterpolatedBFieldMap< Mapper_t >::Config::scale.
Referenced by main(), MakeActsGeometry::makeGeometry(), materialValidationExample(), propagationExample(), and FW::setupSimulation().
FW::CsvParticleReader::Config FW::Options::readCsvParticleReaderConfig (const Variables & vm)
Read the CSV particle reader config.
Definition at line 13 of file CsvOptionsReader.cpp.
View newest version in sPHENIX GitHub at line 13 of file CsvOptionsReader.cpp
References FW::CsvParticleReader::Config::inputDir.
Referenced by main().
FW::CsvParticleWriter::Config FW::Options::readCsvParticleWriterConfig (const Variables & vm)
Read the CSV particle writer options.
Definition at line 25 of file CsvOptionsWriter.cpp.
View newest version in sPHENIX GitHub at line 25 of file CsvOptionsWriter.cpp
References FW::CsvParticleWriter::Config::outputDir, and FW::CsvParticleWriter::Config::outputPrecision.
FW::CsvPlanarClusterReader::Config FW::Options::readCsvPlanarClusterReaderConfig (const Variables & vm)
Read the CSV particle reader config.
Definition at line 23 of file CsvOptionsReader.cpp.
View newest version in sPHENIX GitHub at line 23 of file CsvOptionsReader.cpp
References FW::CsvPlanarClusterReader::Config::inputDir.
Referenced by main().
FW::CsvPlanarClusterWriter::Config FW::Options::readCsvPlanarClusterWriterConfig (const Variables & vm)
Read the CSV planar cluster writer options.
Definition at line 36 of file CsvOptionsWriter.cpp.
View newest version in sPHENIX GitHub at line 36 of file CsvOptionsWriter.cpp
References FW::CsvPlanarClusterWriter::Config::outputDir, and FW::CsvPlanarClusterWriter::Config::outputPrecision.
FW::CsvTrackingGeometryWriter::Config FW::Options::readCsvTrackingGeometryWriterConfig (const Variables & vm)
Read the CSV tracking geometry writer config.
Definition at line 47 of file CsvOptionsWriter.cpp.
View newest version in sPHENIX GitHub at line 47 of file CsvOptionsWriter.cpp
References FW::CsvTrackingGeometryWriter::Config::outputDir, FW::CsvTrackingGeometryWriter::Config::outputPrecision, and FW::CsvTrackingGeometryWriter::Config::writePerEvent.
template<typename amap_t > FW::DD4hep::DD4hepGeometryService::Config FW::Options::readDD4hepConfig (const amap_t & vm)
read the particle gun options and return a Config file
Definition at line 101 of file DD4hepDetectorOptions.hpp.
View newest version in sPHENIX GitHub at line 101 of file DD4hepDetectorOptions.hpp
References Acts::arbitrary, FW::DD4hep::DD4hepGeometryService::Config::bTypePhi, FW::DD4hep::DD4hepGeometryService::Config::bTypeR, FW::DD4hep::DD4hepGeometryService::Config::bTypeZ, FW::DD4hep::DD4hepGeometryService::Config::defaultLayerThickness, FW::DD4hep::DD4hepGeometryService::Config::envelopeR, FW::DD4hep::DD4hepGeometryService::Config::envelopeZ, Acts::equidistant, FW::DD4hep::DD4hepGeometryService::Config::logLevel, FW::DD4hep::DD4hepGeometryService::Config::sortDetectors, sortFCChhDetElements(), and FW::DD4hep::DD4hepGeometryService::Config::xmlFileNames.
template<typename simulator_t > FatrasAlgorithm<simulator_t>::Config FW::Options::readFatrasConfig (const Variables & variables, simulator_t && simulator)
Read Fatras options to create the algorithm config.
Template Parameters
simulator_t type of the simulation kernel
Parameters
vars the variables to read from
simulator the simulation kernel
Definition at line 35 of file FatrasOptions.hpp.
View newest version in sPHENIX GitHub at line 35 of file FatrasOptions.hpp
References Acts::units::_GeV, ACTS_DEBUG, ACTS_LOCAL_LOGGER, ACTS_WARNING, Acts::getDefaultLogger(), Acts::Logging::INFO, and ActsFatras::makeChargedElectroMagneticPhysicsList().
Acts::Logging::Level FW::Options::readLogLevel (const boost::program_options::variables_map & vm)
Read the log level.
Definition at line 165 of file CommonOptions.cpp.
View newest version in sPHENIX GitHub at line 165 of file CommonOptions.cpp
Referenced by main(), materialMappingExample(), materialValidationExample(), processGeometry(), propagationExample(), and readSequencerConfig().
template<class AMAP > FW::Obj::ObjSurfaceWriter::Config FW::Options::readObjSurfaceWriterConfig (const AMAP & vm, const std::string & name, Acts::Logging::Level loglevel)
Definition at line 68 of file ObjWriterOptions.hpp.
View newest version in sPHENIX GitHub at line 68 of file ObjWriterOptions.hpp
References FW::Obj::ObjSurfaceWriter::Config::filePrefix, Acts::Logging::INFO, FW::Obj::ObjSurfaceWriter::Config::outputLayerSurface, FW::Obj::ObjSurfaceWriter::Config::outputPhiSegemnts, FW::Obj::ObjSurfaceWriter::Config::outputPrecision, FW::Obj::ObjSurfaceWriter::Config::outputScalor, FW::Obj::ObjSurfaceWriter::Config::outputSensitive, and FW::Obj::ObjSurfaceWriter::Config::outputThickness.
Referenced by processGeometry().
template<class AMAP > FW::Obj::ObjTrackingGeometryWriter::Config FW::Options::readObjTrackingGeometryWriterConfig (const AMAP & vm, const std::string & name, Acts::Logging::Level loglevel = Acts::Logging::INFO)
read the evgen options and return a Config file
Definition at line 56 of file ObjWriterOptions.hpp.
View newest version in sPHENIX GitHub at line 56 of file ObjWriterOptions.hpp
References FW::Obj::ObjTrackingGeometryWriter::Config::filePrefix, FW::Obj::ObjTrackingGeometryWriter::Config::layerPrefix, and FW::Obj::ObjTrackingGeometryWriter::Config::sensitiveGroupPrefix.
Referenced by processGeometry().
FW::EventGenerator::Config FW::Options::readParticleGunOptions (const boost::program_options::variables_map & vm)
Create the event generator config from particle-gun options.
Definition at line 49 of file ParticleGunOptions.cpp.
View newest version in sPHENIX GitHub at line 49 of file ParticleGunOptions.cpp
References Acts::units::_GeV, Acts::units::_mm, Acts::VectorHelpers::eta(), FW::EventGenerator::Config::generators, FW::ParametricProcessGenerator::Config::numParticles, and phi.
Referenced by main().
template<typename vmap_t , typename propagator_t > FW::PropagationAlgorithm<propagator_t>::Config FW::Options::readPropagationConfig (const vmap_t & vm, propagator_t propagator)
read the evgen options and return a Config file
Template Parameters
vmap_t is the Type of the Parameter map to be read out
bfield_t is the Type of the Magnetic field
Parameters
vm is the parameter map for the options
magField is the magnetic field objects as shared pointer
tGeometry is the tracking geometry object
Returns
a Config object for the ExtrapolationAlgorithm
Material interaction behavior
Create the config for the Extrapoaltion algorithm
The covariance transport
Set the covariance transport to true
Set the covariance matrix
Some pre-defined values (non-trivial helical correlations)
Definition at line 95 of file PropagationOptions.hpp.
View newest version in sPHENIX GitHub at line 95 of file PropagationOptions.hpp
References Acts::units::_GeV, Acts::units::_mm, FW::PropagationAlgorithm< propagator_t >::Config::correlations, FW::PropagationAlgorithm< propagator_t >::Config::covariances, FW::PropagationAlgorithm< propagator_t >::Config::covarianceTransport, FW::PropagationAlgorithm< propagator_t >::Config::d0Sigma, FW::PropagationAlgorithm< propagator_t >::Config::debugOutput, Acts::eLOC_D0, Acts::eLOC_Z0, FW::PropagationAlgorithm< propagator_t >::Config::energyLoss, Acts::ePHI, Acts::eQOP, Acts::eT, FW::PropagationAlgorithm< propagator_t >::Config::etaRange, Acts::eTHETA, FW::PropagationAlgorithm< propagator_t >::Config::maxStepSize, FW::PropagationAlgorithm< propagator_t >::Config::mode, FW::PropagationAlgorithm< propagator_t >::Config::multipleScattering, FW::PropagationAlgorithm< propagator_t >::Config::ntests, FW::PropagationAlgorithm< propagator_t >::Config::phiRange, FW::PropagationAlgorithm< propagator_t >::Config::phiSigma, FW::PropagationAlgorithm< propagator_t >::Config::propagationMaterialCollection, FW::PropagationAlgorithm< propagator_t >::Config::propagationStepCollection, FW::PropagationAlgorithm< propagator_t >::Config::ptLoopers, FW::PropagationAlgorithm< propagator_t >::Config::ptRange, FW::PropagationAlgorithm< propagator_t >::Config::qpSigma, FW::PropagationAlgorithm< propagator_t >::Config::recordMaterialInteractions, FW::PropagationAlgorithm< propagator_t >::Config::thetaSigma, FW::PropagationAlgorithm< propagator_t >::Config::tSigma, and FW::PropagationAlgorithm< propagator_t >::Config::z0Sigma.
Referenced by propagationExample().
FW::EventGenerator::Config FW::Options::readPythia8Options (const boost::program_options::variables_map & vm, Acts::Logging::Level lvl)
Create the event generator config from the options
This builds a full event generator with separate hard scatter and pileup. Not just the Pythia8 process generators to simplify the handling.
Definition at line 46 of file Pythia8Options.cpp.
View newest version in sPHENIX GitHub at line 46 of file Pythia8Options.cpp
References FW::Pythia8Generator::Config::cmsEnergy, FW::EventGenerator::Config::generators, Acts::UnitConstants::mm, Acts::UnitConstants::ns, FW::Pythia8Generator::Config::pdgBeam0, FW::Pythia8Generator::Config::pdgBeam1, and FW::Pythia8Generator::Config::settings.
Referenced by main().
FW::RandomNumbers::Config FW::Options::readRandomNumbersConfig (const boost::program_options::variables_map & vm)
Definition at line 186 of file CommonOptions.cpp.
View newest version in sPHENIX GitHub at line 186 of file CommonOptions.cpp
References FW::RandomNumbers::Config::seed.
Referenced by main(), materialValidationExample(), and propagationExample().
FW::Sequencer::Config FW::Options::readSequencerConfig (const boost::program_options::variables_map & vm)
Read the sequencer config.
Definition at line 170 of file CommonOptions.cpp.
View newest version in sPHENIX GitHub at line 170 of file CommonOptions.cpp
References FW::Sequencer::Config::events, FW::Sequencer::Config::logLevel, FW::Sequencer::Config::numThreads, FW::Sequencer::Config::outputDir, readLogLevel(), and FW::Sequencer::Config::skip.
Referenced by main(), materialMappingExample(), materialValidationExample(), processGeometry(), and propagationExample().
template<typename variable_map_t > std::vector<Acts::TGeoLayerBuilder::Config> FW::Options::readTGeoLayerBuilderConfigs (const variable_map_t & vm, std::shared_ptr< const Acts::LayerCreator > layerCreator)
Read the specific options for the ROOT detector.
Template Parameters
variable_map_t Type of the variable matp to read out
Parameters
vm The variable map containing the options
layerCreator The provide layer creator
Returns
a configuration object for a TGeoLayerBuilder
Definition at line 92 of file TGeoDetectorOptions.hpp.
View newest version in sPHENIX GitHub at line 92 of file TGeoDetectorOptions.hpp
References Acts::TGeoLayerBuilder::Config::configurationName, ip(), Acts::TGeoLayerBuilder::Config::layerConfigurations, Acts::TGeoLayerBuilder::Config::layerCreator, Acts::TGeoLayerBuilder::LayerConfig::layerName, Acts::TGeoLayerBuilder::LayerConfig::localAxes, Acts::TGeoLayerBuilder::LayerConfig::sensorName, and Acts::TGeoLayerBuilder::Config::unit.
void FW::Options::sortFCChhDetElements (std::vector< dd4hep::DetElement > & det)
Definition at line 26 of file DD4hepDetectorOptions.hpp.
View newest version in sPHENIX GitHub at line 26 of file DD4hepDetectorOptions.hpp
References a, b, and tracker().
Referenced by readDD4hepConfig().