EIC Software: erhic::LogReaderPepsi Class Reference
erhic::LogReaderPepsi Class Reference
#include <eic-smear/blob/master/include/eicsmear/erhic/File.h>
Public Member Functions
LogReaderPepsi ()
virtual ~LogReaderPepsi ()
LogReaderPepsi * Create () const
bool Extract (const std::string &file)
Int_t Save () const
Public Member Functions inherited from erhic::LogReader
LogReader ()
virtual ~LogReader ()
Protected Attributes
TObjString crossSection_
TObjString nEvents_
Total cross section in microbarns
TObjString nTrials_
Total number of events generated and kept
Detailed Description
Processes PEPSI log files.
Reads a log file and finds the total cross section and the number of generated events when Extract() is called. Writes those values as TObjStrings to the current directory when Save() is called, assuming that directory is writeable.
Definition at line 127 of file File.h.
View newest version in sPHENIX GitHub at line 127 of file File.h
Constructor & Destructor Documentation
erhic::LogReaderPepsi::LogReaderPepsi ()
Constructor.
Definition at line 103 of file File.cxx.
View newest version in sPHENIX GitHub at line 103 of file File.cxx
Referenced by Create().
erhic::LogReaderPepsi::~LogReaderPepsi () virtual
Destructor.
Definition at line 105 of file File.cxx.
View newest version in sPHENIX GitHub at line 105 of file File.cxx
Member Function Documentation
LogReaderPepsi * erhic::LogReaderPepsi::Create () const inline virtual
Return a new LogReaderPepsi instance.
Implements erhic::LogReader.
Definition at line 164 of file File.h.
View newest version in sPHENIX GitHub at line 164 of file File.h
References LogReaderPepsi().
bool erhic::LogReaderPepsi::Extract (const std::string & file) virtual
Extract data from the named log file.
Implements erhic::LogReader.
Definition at line 107 of file File.cxx.
View newest version in sPHENIX GitHub at line 107 of file File.cxx
References crossSection_, Acts::UnitConstants::e, getline, in, LogLineParse(), nEvents, nEvents_, and nTrials_.
Int_t erhic::LogReaderPepsi::Save () const virtual
Write the extracted information to the current file, if it is writeable. If you want to write the LogReaderPepsi itself, use LogReaderPepsi::Write().
Implements erhic::LogReader.
Definition at line 131 of file File.cxx.
View newest version in sPHENIX GitHub at line 131 of file File.cxx
References crossSection_, nEvents_, and nTrials_.
Member Data Documentation
TObjString erhic::LogReaderPepsi::crossSection_ protected
Definition at line 157 of file File.h.
View newest version in sPHENIX GitHub at line 157 of file File.h
Referenced by Extract(), and Save().
TObjString erhic::LogReaderPepsi::nEvents_ protected
Total cross section in microbarns
Definition at line 158 of file File.h.
View newest version in sPHENIX GitHub at line 158 of file File.h
Referenced by Extract(), and Save().
TObjString erhic::LogReaderPepsi::nTrials_ protected
Total number of events generated and kept
Definition at line 159 of file File.h.
View newest version in sPHENIX GitHub at line 159 of file File.h
Referenced by Extract(), and Save().
The documentation for this class was generated from the following files:
eic-smear/blob/master/include/eicsmear/erhic/File.h
eic-smear/blob/master/src/erhic/File.cxx