EIC Software: CbmRichRingFinderIdeal Class Reference
CbmRichRingFinderIdeal Class Reference
#include <EicRoot/blob/master/rich/finder/CbmRichRingFinderIdeal.h>
Public Member Functions
CbmRichRingFinderIdeal ()
Default constructor.
virtual ~CbmRichRingFinderIdeal ()
Destructor.
virtual void Init ()
Inherited from CbmRichRingFinder.
virtual int DoFind (TClonesArray *hitArray, TClonesArray *projArray, TClonesArray *ringArray)
Public Member Functions inherited from CbmRichRingFinder
CbmRichRingFinder ()
virtual ~CbmRichRingFinder ()
void SetVerbose (Int_t verbose)
Private Member Functions
CbmRichRingFinderIdeal (const CbmRichRingFinderIdeal &)
Copy constructor.
CbmRichRingFinderIdeal & operator= (const CbmRichRingFinderIdeal &)
Assignment operator.
Private Attributes
TClonesArray * fRichPoints
TClonesArray * fMcTracks
Additional Inherited Members
Protected Attributes inherited from CbmRichRingFinder
Int_t fVerbose
Detailed Description
Definition at line 18 of file CbmRichRingFinderIdeal.h.
View newest version in sPHENIX GitHub at line 18 of file CbmRichRingFinderIdeal.h
Constructor & Destructor Documentation
CbmRichRingFinderIdeal::CbmRichRingFinderIdeal ()
Default constructor.
Definition at line 30 of file CbmRichRingFinderIdeal.cxx.
View newest version in sPHENIX GitHub at line 30 of file CbmRichRingFinderIdeal.cxx
CbmRichRingFinderIdeal::~CbmRichRingFinderIdeal () virtual
Destructor.
Definition at line 37 of file CbmRichRingFinderIdeal.cxx.
View newest version in sPHENIX GitHub at line 37 of file CbmRichRingFinderIdeal.cxx
CbmRichRingFinderIdeal::CbmRichRingFinderIdeal (const CbmRichRingFinderIdeal &) private
Copy constructor.
Member Function Documentation
Int_t CbmRichRingFinderIdeal::DoFind (TClonesArray * hitArray, TClonesArray * projArray, TClonesArray * ringArray) virtual
Inherited from CbmRichRingFinder.
Implements CbmRichRingFinder.
Definition at line 54 of file CbmRichRingFinderIdeal.cxx.
View newest version in sPHENIX GitHub at line 54 of file CbmRichRingFinderIdeal.cxx
References CbmRichRing::AddHit(), fMcTracks, fRichPoints, CbmMCTrack::GetMotherId(), CbmMCTrack::GetPdgCode(), CbmBaseHit::GetRefId(), and FairMCPoint::GetTrackID().
void CbmRichRingFinderIdeal::Init (void) virtual
Inherited from CbmRichRingFinder.
Reimplemented from CbmRichRingFinder.
Definition at line 42 of file CbmRichRingFinderIdeal.cxx.
View newest version in sPHENIX GitHub at line 42 of file CbmRichRingFinderIdeal.cxx
References fMcTracks, fRichPoints, FairRootManager::GetObject(), and FairRootManager::Instance().
CbmRichRingFinderIdeal& CbmRichRingFinderIdeal::operator= (const CbmRichRingFinderIdeal &) private
Assignment operator.
Member Data Documentation
TClonesArray* CbmRichRingFinderIdeal::fMcTracks private
Definition at line 22 of file CbmRichRingFinderIdeal.h.
View newest version in sPHENIX GitHub at line 22 of file CbmRichRingFinderIdeal.h
Referenced by DoFind(), and Init().
TClonesArray* CbmRichRingFinderIdeal::fRichPoints private
Definition at line 21 of file CbmRichRingFinderIdeal.h.
View newest version in sPHENIX GitHub at line 21 of file CbmRichRingFinderIdeal.h
Referenced by DoFind(), and Init().
The documentation for this class was generated from the following files:
EicRoot/blob/master/rich/finder/CbmRichRingFinderIdeal.h
EicRoot/blob/master/rich/finder/CbmRichRingFinderIdeal.cxx