EIC Software: PHG4ForwardHcalDetector Class Reference
PHG4ForwardHcalDetector Class Reference
#include <fun4all_eicdetectors/blob/master/simulation/g4simulation/g4eiccalos/PHG4ForwardHcalDetector.h>
Classes
struct towerposition
Public Member Functions
PHG4ForwardHcalDetector (PHG4Subsystem *subsys, PHCompositeNode *Node, PHParameters *parameters, const std::string &dnam)
constructor
virtual ~PHG4ForwardHcalDetector ()
destructor
virtual void ConstructMe (G4LogicalVolume *world)
construct
Public Member Functions inherited from PHG4Detector
PHG4Detector ()=delete
constructor
PHG4Detector (PHG4Subsystem *subsys, PHCompositeNode *Node, const std::string &nam)
virtual ~PHG4Detector (void)
destructor
virtual void Construct (G4LogicalVolume *world) final
construct method
virtual void PostConstruction ()
Optional PostConstruction call after all geometry is constructed.
virtual void Verbosity (const int v)
virtual int Verbosity () const
virtual G4UserSteppingAction * GetSteppingAction ()
virtual std::string GetName () const
virtual void OverlapCheck (const bool chk)
virtual bool OverlapCheck () const
virtual void Print (const std::string &="ALL") const
virtual int DisplayVolume (G4VSolid *volume, G4LogicalVolume *logvol, G4RotationMatrix *rotm=nullptr)
virtual int DisplayVolume (G4LogicalVolume *checksolid, G4LogicalVolume *logvol, G4RotationMatrix *rotm=nullptr)
virtual PHCompositeNode * topNode ()
virtual PHG4Subsystem * GetMySubsystem ()
volume accessors
PHG4ForwardHcalDisplayAction * m_DisplayAction = nullptr
PHParameters * m_Params = nullptr
int m_ActiveFlag = 1
int m_AbsorberActiveFlag = 0
int m_SupportActiveFlag = 0
int m_Layer = 0
std::string m_TowerLogicNamePrefix
std::string m_SuperDetector
std::map< std::string, G4double > m_GlobalParameterMap
std::map< std::string,
towerposition > m_TowerPostionMap
std::set< G4LogicalVolume * > m_AbsorberLogicalVolSet
std::set< G4LogicalVolume * > m_ScintiLogicalVolSet
std::set< G4LogicalVolume * > m_SupportLogicalVolSet
int IsInForwardHcal (G4VPhysicalVolume *) const
void SuperDetector (const std::string &name)
const std::string SuperDetector () const
int get_Layer () const
G4LogicalVolume * ConstructTower ()
int PlaceTower (G4LogicalVolume *envelope, G4LogicalVolume *tower)
int ParseParametersFromTable ()
Additional Inherited Members
Static Public Member Functions inherited from PHG4Detector
static G4Material * GetDetectorMaterial (const std::string &name, const bool quit=true)
static G4Element * GetDetectorElement (const std::string &name, const bool quit=true)
Detailed Description
Definition at line 27 of file PHG4ForwardHcalDetector.h.
View newest version in sPHENIX GitHub at line 27 of file PHG4ForwardHcalDetector.h
Constructor & Destructor Documentation
PHG4ForwardHcalDetector::PHG4ForwardHcalDetector (PHG4Subsystem * subsys, PHCompositeNode * Node, PHParameters * parameters, const std::string & dnam)
constructor
Definition at line 38 of file PHG4ForwardHcalDetector.cc.
View newest version in sPHENIX GitHub at line 38 of file PHG4ForwardHcalDetector.cc
virtual PHG4ForwardHcalDetector::~PHG4ForwardHcalDetector () inline virtual
destructor
Definition at line 34 of file PHG4ForwardHcalDetector.h.
View newest version in sPHENIX GitHub at line 34 of file PHG4ForwardHcalDetector.h
Member Function Documentation
void PHG4ForwardHcalDetector::ConstructMe (G4LogicalVolume * world) virtual
construct
Implements PHG4Detector.
Definition at line 80 of file PHG4ForwardHcalDetector.cc.
View newest version in sPHENIX GitHub at line 80 of file PHG4ForwardHcalDetector.cc
References PHG4ForwardHcalDisplayAction::AddVolume(), Acts::UnitConstants::cm, ConstructTower(), PHParameters::get_double_param(), PHParameters::get_string_param(), PHFlag::get_StringFlag(), PHG4Detector::GetDetectorMaterial(), recoConsts::instance(), m_DisplayAction, m_Params, M_PI, m_TowerLogicNamePrefix, PHG4Detector::OverlapCheck(), ParseParametersFromTable(), PlaceTower(), PHG4Detector::Verbosity(), and G4WORLD::WorldMaterial.
G4LogicalVolume * PHG4ForwardHcalDetector::ConstructTower () private
Definition at line 142 of file PHG4ForwardHcalDetector.cc.
View newest version in sPHENIX GitHub at line 142 of file PHG4ForwardHcalDetector.cc
References PHG4ForwardHcalDisplayAction::AddVolume(), Acts::UnitConstants::cm, Acts::UnitConstants::cm3, g(), PHParameters::get_double_param(), PHParameters::get_int_param(), PHParameters::get_string_param(), PHFlag::get_StringFlag(), PHG4Detector::GetDetectorMaterial(), recoConsts::instance(), m_AbsorberLogicalVolSet, m_DisplayAction, m_Params, m_ScintiLogicalVolSet, m_SupportLogicalVolSet, m_TowerLogicNamePrefix, PHG4Detector::OverlapCheck(), PHG4Detector::Verbosity(), and G4WORLD::WorldMaterial.
Referenced by ConstructMe().
int PHG4ForwardHcalDetector::get_Layer () const inline
Definition at line 45 of file PHG4ForwardHcalDetector.h.
View newest version in sPHENIX GitHub at line 45 of file PHG4ForwardHcalDetector.h
References m_Layer.
Referenced by PHG4ForwardHcalSteppingAction::UserSteppingAction().
int PHG4ForwardHcalDetector::IsInForwardHcal (G4VPhysicalVolume * volume) const
Definition at line 50 of file PHG4ForwardHcalDetector.cc.
View newest version in sPHENIX GitHub at line 50 of file PHG4ForwardHcalDetector.cc
References m_AbsorberActiveFlag, m_AbsorberLogicalVolSet, m_ActiveFlag, m_ScintiLogicalVolSet, m_SupportActiveFlag, and m_SupportLogicalVolSet.
Referenced by PHG4ForwardHcalSteppingAction::UserSteppingAction().
int PHG4ForwardHcalDetector::ParseParametersFromTable () private
Definition at line 313 of file PHG4ForwardHcalDetector.cc.
View newest version in sPHENIX GitHub at line 313 of file PHG4ForwardHcalDetector.cc
References Acts::UnitConstants::cm, PHParameters::get_string_param(), getline, PHG4ForwardHcalDetector::towerposition::idx_j, PHG4ForwardHcalDetector::towerposition::idx_k, m_GlobalParameterMap, m_Params, m_TowerLogicNamePrefix, m_TowerPostionMap, Acts::UnitConstants::rad, PHParameters::set_double_param(), G4CTD::size_z, PHG4Detector::Verbosity(), PHG4ForwardHcalDetector::towerposition::x, PHG4ForwardHcalDetector::towerposition::y, and PHG4ForwardHcalDetector::towerposition::z.
Referenced by ConstructMe().
int PHG4ForwardHcalDetector::PlaceTower (G4LogicalVolume * envelope, G4LogicalVolume * tower) private
Definition at line 290 of file PHG4ForwardHcalDetector.cc.
View newest version in sPHENIX GitHub at line 290 of file PHG4ForwardHcalDetector.cc
References m_TowerPostionMap, PHG4Detector::OverlapCheck(), and PHG4Detector::Verbosity().
Referenced by ConstructMe().
void PHG4ForwardHcalDetector::SuperDetector (const std::string & name) inline
Definition at line 42 of file PHG4ForwardHcalDetector.h.
View newest version in sPHENIX GitHub at line 42 of file PHG4ForwardHcalDetector.h
References m_SuperDetector, and name.
Referenced by PHG4ForwardHcalSubsystem::InitRunSubsystem().
const std::string PHG4ForwardHcalDetector::SuperDetector () const inline
Definition at line 43 of file PHG4ForwardHcalDetector.h.
View newest version in sPHENIX GitHub at line 43 of file PHG4ForwardHcalDetector.h
References m_SuperDetector.
Member Data Documentation
int PHG4ForwardHcalDetector::m_AbsorberActiveFlag = 0 private
Definition at line 65 of file PHG4ForwardHcalDetector.h.
View newest version in sPHENIX GitHub at line 65 of file PHG4ForwardHcalDetector.h
Referenced by IsInForwardHcal().
std::set<G4LogicalVolume *> PHG4ForwardHcalDetector::m_AbsorberLogicalVolSet private
Definition at line 75 of file PHG4ForwardHcalDetector.h.
View newest version in sPHENIX GitHub at line 75 of file PHG4ForwardHcalDetector.h
Referenced by ConstructTower(), and IsInForwardHcal().
int PHG4ForwardHcalDetector::m_ActiveFlag = 1 private
Definition at line 64 of file PHG4ForwardHcalDetector.h.
View newest version in sPHENIX GitHub at line 64 of file PHG4ForwardHcalDetector.h
Referenced by IsInForwardHcal().
PHG4ForwardHcalDisplayAction* PHG4ForwardHcalDetector::m_DisplayAction = nullptr private
Definition at line 61 of file PHG4ForwardHcalDetector.h.
View newest version in sPHENIX GitHub at line 61 of file PHG4ForwardHcalDetector.h
Referenced by ConstructMe(), and ConstructTower().
std::map<std::string, G4double> PHG4ForwardHcalDetector::m_GlobalParameterMap private
Definition at line 72 of file PHG4ForwardHcalDetector.h.
View newest version in sPHENIX GitHub at line 72 of file PHG4ForwardHcalDetector.h
Referenced by ParseParametersFromTable().
int PHG4ForwardHcalDetector::m_Layer = 0 private
Definition at line 67 of file PHG4ForwardHcalDetector.h.
View newest version in sPHENIX GitHub at line 67 of file PHG4ForwardHcalDetector.h
Referenced by get_Layer().
PHParameters* PHG4ForwardHcalDetector::m_Params = nullptr private
Definition at line 62 of file PHG4ForwardHcalDetector.h.
View newest version in sPHENIX GitHub at line 62 of file PHG4ForwardHcalDetector.h
Referenced by ConstructMe(), ConstructTower(), and ParseParametersFromTable().
std::set<G4LogicalVolume *> PHG4ForwardHcalDetector::m_ScintiLogicalVolSet private
Definition at line 76 of file PHG4ForwardHcalDetector.h.
View newest version in sPHENIX GitHub at line 76 of file PHG4ForwardHcalDetector.h
Referenced by ConstructTower(), and IsInForwardHcal().
std::string PHG4ForwardHcalDetector::m_SuperDetector private
Definition at line 70 of file PHG4ForwardHcalDetector.h.
View newest version in sPHENIX GitHub at line 70 of file PHG4ForwardHcalDetector.h
Referenced by SuperDetector().
int PHG4ForwardHcalDetector::m_SupportActiveFlag = 0 private
Definition at line 66 of file PHG4ForwardHcalDetector.h.
View newest version in sPHENIX GitHub at line 66 of file PHG4ForwardHcalDetector.h
Referenced by IsInForwardHcal().
std::set<G4LogicalVolume *> PHG4ForwardHcalDetector::m_SupportLogicalVolSet private
Definition at line 77 of file PHG4ForwardHcalDetector.h.
View newest version in sPHENIX GitHub at line 77 of file PHG4ForwardHcalDetector.h
Referenced by ConstructTower(), and IsInForwardHcal().
std::string PHG4ForwardHcalDetector::m_TowerLogicNamePrefix private
Definition at line 69 of file PHG4ForwardHcalDetector.h.
View newest version in sPHENIX GitHub at line 69 of file PHG4ForwardHcalDetector.h
Referenced by ConstructMe(), ConstructTower(), and ParseParametersFromTable().
std::map<std::string, towerposition> PHG4ForwardHcalDetector::m_TowerPostionMap private
Definition at line 73 of file PHG4ForwardHcalDetector.h.
View newest version in sPHENIX GitHub at line 73 of file PHG4ForwardHcalDetector.h
Referenced by ParseParametersFromTable(), and PlaceTower().
The documentation for this class was generated from the following files:
fun4all_eicdetectors/blob/master/simulation/g4simulation/g4eiccalos/PHG4ForwardHcalDetector.h
fun4all_eicdetectors/blob/master/simulation/g4simulation/g4eiccalos/PHG4ForwardHcalDetector.cc