EIC Software: EicIdealTrackingCode Class Reference
EicIdealTrackingCode Class Reference
#include <EicRoot/blob/master/eic/tracking/EicIdealTrackingCode.h>
Public Member Functions
EicIdealTrackingCode ()
virtual ~EicIdealTrackingCode ()
int AddDetectorGroup (const char *name)
virtual void Exec (Option_t *option)
virtual InitStatus Init ()
virtual void Finish ()
void Reset ()
virtual void Register ()
void SetTrackOutBranchName (TString name)
void SetMomentumSmearing (Double_t sigmax, Double_t sigmay, Double_t sigmaz)
void SetRelativeMomentumSmearing (Double_t dpop)
void SetVertexSmearing (Double_t sigmax, Double_t sigmay, Double_t sigmaz)
void SetTrackingEfficiency (Double_t eff)
Public Member Functions inherited from FairTask
FairTask ()
FairTask (const char *name, Int_t iVerbose=1)
virtual ~FairTask ()
void InitTask ()
void ReInitTask ()
void SetParTask ()
virtual void FinishTask ()
virtual void FinishEvent ()
void SetVerbose (Int_t iVerbose)
void SetInputPersistance (Bool_t val)
void CheckInputPersistance (TString branchName)
Protected Member Functions
void SmearFWD (TVector3 &vec, const TVector3 &sigma)
EicIdealTrackingCode (const EicIdealTrackingCode &L)
Particle DB.
EicIdealTrackingCode & operator= (const EicIdealTrackingCode &)
ClassDef (EicIdealTrackingCode, 2)
Protected Member Functions inherited from FairTask
virtual InitStatus ReInit ()
virtual void SetParContainers ()
void InitTasks ()
void ReInitTasks ()
void SetParTasks ()
void FinishTasks ()
void FinishEvents ()
Protected Attributes
TClonesArray * fMCTracks
std::vector< EicDetectorGroup > fGroups
Array of PndMCTrack.
TClonesArray * fTrackCands
TClonesArray * fTracks
Array of found track candidates.
TClonesArray * fTrackIds
Array of found tracks.
TVector3 fMomSigma
Array of track IDs (Links)
Double_t fDPoP
Momentum smearing sigma [GeV].
Bool_t fRelative
Relative momentum Smearing.
TVector3 fVtxSigma
falg
Double_t fEfficiency
Vertex smearing sigma [cm].
TString fTracksArrayName
Tracking efficiency - if (0 <= e < 1), some tracks will be discarded.
TDatabasePDG * pdg
Protected Attributes inherited from FairTask
Int_t fVerbose
Int_t fInputPersistance
Indicates if input branch is persistant.
FairLogger * fLogger
Friends
class EicRecoKalmanTask
class EicHtcTask
class FwdTrackFinder
Detailed Description
Definition at line 78 of file EicIdealTrackingCode.h.
View newest version in sPHENIX GitHub at line 78 of file EicIdealTrackingCode.h
Constructor & Destructor Documentation
EicIdealTrackingCode::EicIdealTrackingCode ()
Definition at line 31 of file EicIdealTrackingCode.cxx.
View newest version in sPHENIX GitHub at line 31 of file EicIdealTrackingCode.cxx
References fTrackCands, fTracks, and FairTask::fVerbose.
EicIdealTrackingCode::~EicIdealTrackingCode () virtual
Definition at line 44 of file EicIdealTrackingCode.cxx.
View newest version in sPHENIX GitHub at line 44 of file EicIdealTrackingCode.cxx
EicIdealTrackingCode::EicIdealTrackingCode (const EicIdealTrackingCode & L) protected
Particle DB.
Member Function Documentation
int EicIdealTrackingCode::AddDetectorGroup (const char * name)
Definition at line 61 of file EicIdealTrackingCode.cxx.
View newest version in sPHENIX GitHub at line 61 of file EicIdealTrackingCode.cxx
References fGroups.
Referenced by reconstruction().
EicIdealTrackingCode::ClassDef (EicIdealTrackingCode , 2) protected
void EicIdealTrackingCode::Exec (Option_t * option) virtual
Reimplemented in FwdIdealTrackingCode.
Definition at line 122 of file EicIdealTrackingCode.cxx.
View newest version in sPHENIX GitHub at line 122 of file EicIdealTrackingCode.cxx
References PndTrackCand::AddHit(), charge, fDPoP, fEfficiency, fGroups, fMCTracks, fMomSigma, fRelative, fTrackCands, fTracks, FairTask::fVerbose, fVtxSigma, FairRootManager::GetBranchId(), PndTrackCand::GetNHits(), PndMCTrack::GetPdgCode(), FairHit::GetRefIndex(), FairMCPoint::GetTrackID(), FairHit::GetX(), FairHit::GetY(), FairHit::GetZ(), FairRootManager::Instance(), it, pdg, Reset(), PndTrackCand::setMcTrackId(), lit::Sign(), SmearFWD(), and PndTrackCand::Sort().
void EicIdealTrackingCode::Finish (void) virtual
Action after each event. To be implemented in the derived class
Reimplemented from FairTask.
Reimplemented in FwdIdealTrackingCode.
Definition at line 283 of file EicIdealTrackingCode.cxx.
View newest version in sPHENIX GitHub at line 283 of file EicIdealTrackingCode.cxx
References fTracks, FairRun::GetOutputFile(), and FairRun::Instance().
InitStatus EicIdealTrackingCode::Init (void) virtual
Intialisation at begin of run. To be implemented in the derived class. Success If not kSUCCESS, task will be set inactive.
Reimplemented from FairTask.
Definition at line 72 of file EicIdealTrackingCode.cxx.
View newest version in sPHENIX GitHub at line 72 of file EicIdealTrackingCode.cxx
References FairRootManager::AddDigiLookupEntry(), FairRootManager::AddMoCaLookupEntry(), fGroups, fMCTracks, FairTask::fVerbose, FairRootManager::GetBranchId(), FairRootManager::GetObject(), FairRootManager::Instance(), it, kERROR, kSUCCESS, pdg, and Register().
EicIdealTrackingCode& EicIdealTrackingCode::operator= (const EicIdealTrackingCode &) inline protected
Definition at line 130 of file EicIdealTrackingCode.h.
View newest version in sPHENIX GitHub at line 130 of file EicIdealTrackingCode.h
void EicIdealTrackingCode::Register () virtual
Reimplemented in FwdIdealTrackingCode.
Definition at line 52 of file EicIdealTrackingCode.cxx.
View newest version in sPHENIX GitHub at line 52 of file EicIdealTrackingCode.cxx
References fTrackCands, fTracks, fTracksArrayName, FairTask::fVerbose, FairRootManager::Instance(), and FairRootManager::Register().
Referenced by Init().
void EicIdealTrackingCode::Reset ()
Definition at line 296 of file EicIdealTrackingCode.cxx.
View newest version in sPHENIX GitHub at line 296 of file EicIdealTrackingCode.cxx
References fTrackCands, and fTracks.
Referenced by Exec().
void EicIdealTrackingCode::SetMomentumSmearing (Double_t sigmax, Double_t sigmay, Double_t sigmaz) inline
Definition at line 100 of file EicIdealTrackingCode.h.
View newest version in sPHENIX GitHub at line 100 of file EicIdealTrackingCode.h
References fMomSigma, and fRelative.
void EicIdealTrackingCode::SetRelativeMomentumSmearing (Double_t dpop) inline
Definition at line 102 of file EicIdealTrackingCode.h.
View newest version in sPHENIX GitHub at line 102 of file EicIdealTrackingCode.h
References fDPoP, and fRelative.
Referenced by reconstruction().
void EicIdealTrackingCode::SetTrackingEfficiency (Double_t eff) inline
Definition at line 105 of file EicIdealTrackingCode.h.
View newest version in sPHENIX GitHub at line 105 of file EicIdealTrackingCode.h
References fEfficiency.
Referenced by reconstruction().
void EicIdealTrackingCode::SetTrackOutBranchName (TString name) inline
Definition at line 98 of file EicIdealTrackingCode.h.
View newest version in sPHENIX GitHub at line 98 of file EicIdealTrackingCode.h
References fTracksArrayName, and name.
Referenced by reconstruction().
void EicIdealTrackingCode::SetVertexSmearing (Double_t sigmax, Double_t sigmay, Double_t sigmaz) inline
Definition at line 103 of file EicIdealTrackingCode.h.
View newest version in sPHENIX GitHub at line 103 of file EicIdealTrackingCode.h
References fVtxSigma.
Referenced by reconstruction().
void EicIdealTrackingCode::SmearFWD (TVector3 & vec, const TVector3 & sigma) protected
Definition at line 313 of file EicIdealTrackingCode.cxx.
View newest version in sPHENIX GitHub at line 313 of file EicIdealTrackingCode.cxx
Referenced by Exec().
Friends And Related Function Documentation
friend class EicHtcTask friend
Definition at line 81 of file EicIdealTrackingCode.h.
View newest version in sPHENIX GitHub at line 81 of file EicIdealTrackingCode.h
friend class EicRecoKalmanTask friend
Definition at line 80 of file EicIdealTrackingCode.h.
View newest version in sPHENIX GitHub at line 80 of file EicIdealTrackingCode.h
friend class FwdTrackFinder friend
Definition at line 82 of file EicIdealTrackingCode.h.
View newest version in sPHENIX GitHub at line 82 of file EicIdealTrackingCode.h
Member Data Documentation
Double_t EicIdealTrackingCode::fDPoP protected
Momentum smearing sigma [GeV].
Definition at line 121 of file EicIdealTrackingCode.h.
View newest version in sPHENIX GitHub at line 121 of file EicIdealTrackingCode.h
Referenced by Exec(), and SetRelativeMomentumSmearing().
Double_t EicIdealTrackingCode::fEfficiency protected
Vertex smearing sigma [cm].
Definition at line 124 of file EicIdealTrackingCode.h.
View newest version in sPHENIX GitHub at line 124 of file EicIdealTrackingCode.h
Referenced by Exec(), and SetTrackingEfficiency().
std::vector<EicDetectorGroup> EicIdealTrackingCode::fGroups protected
Array of PndMCTrack.
Definition at line 113 of file EicIdealTrackingCode.h.
View newest version in sPHENIX GitHub at line 113 of file EicIdealTrackingCode.h
Referenced by AddDetectorGroup(), EicHtcTask::ConfigureKalmanFilter(), EicHtcTask::DeclareSensitiveVolumes(), Exec(), FwdTrackFinder::Exec(), EicHtcTask::Exec(), EicRecoKalmanTask::Init(), Init(), and EicHtcTask::Init().
TClonesArray* EicIdealTrackingCode::fMCTracks protected
Definition at line 111 of file EicIdealTrackingCode.h.
View newest version in sPHENIX GitHub at line 111 of file EicIdealTrackingCode.h
Referenced by Exec(), and Init().
TVector3 EicIdealTrackingCode::fMomSigma protected
Array of track IDs (Links)
Definition at line 120 of file EicIdealTrackingCode.h.
View newest version in sPHENIX GitHub at line 120 of file EicIdealTrackingCode.h
Referenced by Exec(), and SetMomentumSmearing().
Bool_t EicIdealTrackingCode::fRelative protected
Relative momentum Smearing.
Definition at line 122 of file EicIdealTrackingCode.h.
View newest version in sPHENIX GitHub at line 122 of file EicIdealTrackingCode.h
Referenced by Exec(), SetMomentumSmearing(), and SetRelativeMomentumSmearing().
TClonesArray* EicIdealTrackingCode::fTrackCands protected
Definition at line 115 of file EicIdealTrackingCode.h.
View newest version in sPHENIX GitHub at line 115 of file EicIdealTrackingCode.h
Referenced by EicIdealTrackingCode(), Exec(), Register(), and Reset().
TClonesArray* EicIdealTrackingCode::fTrackIds protected
Array of found tracks.
Definition at line 117 of file EicIdealTrackingCode.h.
View newest version in sPHENIX GitHub at line 117 of file EicIdealTrackingCode.h
TClonesArray* EicIdealTrackingCode::fTracks protected
Array of found track candidates.
Definition at line 116 of file EicIdealTrackingCode.h.
View newest version in sPHENIX GitHub at line 116 of file EicIdealTrackingCode.h
Referenced by EicIdealTrackingCode(), Exec(), Finish(), Register(), and Reset().
TString EicIdealTrackingCode::fTracksArrayName protected
Tracking efficiency - if (0 <= e < 1), some tracks will be discarded.
Definition at line 126 of file EicIdealTrackingCode.h.
View newest version in sPHENIX GitHub at line 126 of file EicIdealTrackingCode.h
Referenced by EicRecoKalmanTask::Init(), Register(), and SetTrackOutBranchName().
TVector3 EicIdealTrackingCode::fVtxSigma protected
falg
Definition at line 123 of file EicIdealTrackingCode.h.
View newest version in sPHENIX GitHub at line 123 of file EicIdealTrackingCode.h
Referenced by Exec(), and SetVertexSmearing().
TDatabasePDG* EicIdealTrackingCode::pdg protected
Definition at line 127 of file EicIdealTrackingCode.h.
View newest version in sPHENIX GitHub at line 127 of file EicIdealTrackingCode.h
Referenced by Exec(), and Init().
The documentation for this class was generated from the following files:
EicRoot/blob/master/eic/tracking/EicIdealTrackingCode.h
EicRoot/blob/master/eic/tracking/EicIdealTrackingCode.cxx