EIC Software: FairRunIdGenerator Class Reference
FairRunIdGenerator Class Reference
#include <EicRoot/blob/master/base/FairRunIdGenerator.h>
Classes
struct uuid
Public Member Functions
FairRunIdGenerator ()
~FairRunIdGenerator ()
unsigned int generateId (void)
Private Member Functions
int get_random_fd (void)
void get_random_bytes (void *, int)
int get_node_id (unsigned char *)
int get_clock (uint32_t *, uint32_t *, uint16_t *)
void uuid_generate_time (uuid_t)
void uuid_generate_random (uuid_t)
void uuid_generate (uuid_t)
void uuid_pack (const struct uuid *, uuid_t)
void uuid_unpack (const uuid_t, struct uuid *)
Detailed Description
Definition at line 10 of file FairRunIdGenerator.h.
View newest version in sPHENIX GitHub at line 10 of file FairRunIdGenerator.h
Constructor & Destructor Documentation
FairRunIdGenerator::FairRunIdGenerator () inline
Definition at line 29 of file FairRunIdGenerator.h.
View newest version in sPHENIX GitHub at line 29 of file FairRunIdGenerator.h
FairRunIdGenerator::~FairRunIdGenerator () inline
Definition at line 30 of file FairRunIdGenerator.h.
View newest version in sPHENIX GitHub at line 30 of file FairRunIdGenerator.h
Member Function Documentation
unsigned int FairRunIdGenerator::generateId (void)
Definition at line 375 of file FairRunIdGenerator.cxx.
View newest version in sPHENIX GitHub at line 375 of file FairRunIdGenerator.cxx
References uuid_generate(), and v.
Referenced by FairRunAna::Init(), and FairRunSim::Init().
int FairRunIdGenerator::get_clock (uint32_t * clock_high, uint32_t * clock_low, uint16_t * ret_clock_seq) private
Definition at line 195 of file FairRunIdGenerator.cxx.
View newest version in sPHENIX GitHub at line 195 of file FairRunIdGenerator.cxx
References get_random_bytes(), and MAX_ADJUSTMENT.
Referenced by uuid_generate_time().
int FairRunIdGenerator::get_node_id (unsigned char * node_id) private
Definition at line 117 of file FairRunIdGenerator.cxx.
View newest version in sPHENIX GitHub at line 117 of file FairRunIdGenerator.cxx
References n.
Referenced by uuid_generate_time().
void FairRunIdGenerator::get_random_bytes (void * buf, int nbytes) private
Definition at line 83 of file FairRunIdGenerator.cxx.
View newest version in sPHENIX GitHub at line 83 of file FairRunIdGenerator.cxx
References fd, get_random_fd(), rand, and read().
Referenced by get_clock(), uuid_generate_random(), and uuid_generate_time().
int FairRunIdGenerator::get_random_fd (void) private
Definition at line 56 of file FairRunIdGenerator.cxx.
View newest version in sPHENIX GitHub at line 56 of file FairRunIdGenerator.cxx
References fd, Acts::open, rand, and srand.
Referenced by get_random_bytes(), and uuid_generate().
void FairRunIdGenerator::uuid_generate (uuid_t out) private
Definition at line 285 of file FairRunIdGenerator.cxx.
View newest version in sPHENIX GitHub at line 285 of file FairRunIdGenerator.cxx
References get_random_fd(), uuid_generate_random(), and uuid_generate_time().
Referenced by generateId().
void FairRunIdGenerator::uuid_generate_random (uuid_t out) private
Definition at line 266 of file FairRunIdGenerator.cxx.
View newest version in sPHENIX GitHub at line 266 of file FairRunIdGenerator.cxx
References FairRunIdGenerator::uuid::clock_seq, get_random_bytes(), FairRunIdGenerator::uuid::time_hi_and_version, uuid_pack(), and uuid_unpack().
Referenced by uuid_generate().
void FairRunIdGenerator::uuid_generate_time (uuid_t out) private
Definition at line 239 of file FairRunIdGenerator.cxx.
View newest version in sPHENIX GitHub at line 239 of file FairRunIdGenerator.cxx
References FairRunIdGenerator::uuid::clock_seq, get_clock(), get_node_id(), get_random_bytes(), FairRunIdGenerator::uuid::node, FairRunIdGenerator::uuid::time_hi_and_version, FairRunIdGenerator::uuid::time_low, FairRunIdGenerator::uuid::time_mid, and uuid_pack().
Referenced by uuid_generate().
void FairRunIdGenerator::uuid_pack (const struct uuid * uu, uuid_t ptr) private
Definition at line 305 of file FairRunIdGenerator.cxx.
View newest version in sPHENIX GitHub at line 305 of file FairRunIdGenerator.cxx
References FairRunIdGenerator::uuid::clock_seq, FairRunIdGenerator::uuid::node, FairRunIdGenerator::uuid::time_hi_and_version, FairRunIdGenerator::uuid::time_low, and FairRunIdGenerator::uuid::time_mid.
Referenced by uuid_generate_random(), and uuid_generate_time().
void FairRunIdGenerator::uuid_unpack (const uuid_t in, struct uuid * uu) private
Definition at line 349 of file FairRunIdGenerator.cxx.
View newest version in sPHENIX GitHub at line 349 of file FairRunIdGenerator.cxx
References FairRunIdGenerator::uuid::clock_seq, in, FairRunIdGenerator::uuid::node, FairRunIdGenerator::uuid::time_hi_and_version, FairRunIdGenerator::uuid::time_low, and FairRunIdGenerator::uuid::time_mid.
Referenced by uuid_generate_random().
The documentation for this class was generated from the following files:
EicRoot/blob/master/base/FairRunIdGenerator.h
EicRoot/blob/master/base/FairRunIdGenerator.cxx