EIC Software: CbmRichRingSelectAnn Class Reference
CbmRichRingSelectAnn Class Reference
Implementation for concrete RICH ring selection algorithm: reject rings using a trained neural net (input file with weights needed!) store resulting value (0-1) in "SelectionNN": 0 = good rings 1 = rings to be rejected –> choose a value in between depending on required purity/ efficiency.
#include <EicRoot/blob/master/rich/selection/CbmRichRingSelectAnn.h>
Public Member Functions
CbmRichRingSelectAnn ()
Standard constructor.
virtual ~CbmRichRingSelectAnn ()
Destructor.
virtual void Init ()
Initialize ANN.
void DoSelect (CbmRichRingLight *ring)
void SetAnnWeights (const string &fileName)
Set path to the file with ANN weights.
Private Member Functions
CbmRichRingSelectAnn (const CbmRichRingSelectAnn &)
Copy constructor.
CbmRichRingSelectAnn & operator= (const CbmRichRingSelectAnn &)
Assignment operator.
Private Attributes
std::string fAnnWeights
TMultiLayerPerceptron * fNN
CbmRichRingSelectImpl * fSelectImpl
Detailed Description
Implementation for concrete RICH ring selection algorithm: reject rings using a trained neural net (input file with weights needed!) store resulting value (0-1) in "SelectionNN": 0 = good rings 1 = rings to be rejected –> choose a value in between depending on required purity/ efficiency.
Author
Semen Lebedev
Date
2008
Definition at line 39 of file CbmRichRingSelectAnn.h.
View newest version in sPHENIX GitHub at line 39 of file CbmRichRingSelectAnn.h
Constructor & Destructor Documentation
CbmRichRingSelectAnn::CbmRichRingSelectAnn ()
Standard constructor.
Definition at line 14 of file CbmRichRingSelectAnn.cxx.
View newest version in sPHENIX GitHub at line 14 of file CbmRichRingSelectAnn.cxx
References fAnnWeights.
CbmRichRingSelectAnn::~CbmRichRingSelectAnn () virtual
Destructor.
Definition at line 22 of file CbmRichRingSelectAnn.cxx.
View newest version in sPHENIX GitHub at line 22 of file CbmRichRingSelectAnn.cxx
CbmRichRingSelectAnn::CbmRichRingSelectAnn (const CbmRichRingSelectAnn &) private
Copy constructor.
Member Function Documentation
void CbmRichRingSelectAnn::DoSelect (CbmRichRingLight * ring)
selection.
Parameters
[in,out] ring Found and fitted ring.
Definition at line 49 of file CbmRichRingSelectAnn.cxx.
View newest version in sPHENIX GitHub at line 49 of file CbmRichRingSelectAnn.cxx
References fNN, fSelectImpl, CbmRichRingSelectImpl::GetAngle(), CbmRichRingLight::GetAngle(), CbmRichRingLight::GetChi2(), CbmRichRingLight::GetNofHits(), CbmRichRingLight::GetNofHitsOnRing(), CbmRichRingSelectImpl::GetNofHitsOnRingCircle(), CbmRichRingLight::GetRadialPosition(), CbmRichRingLight::GetRadius(), CbmRichRingLight::SetAngle(), CbmRichRingLight::SetNofHitsOnRing(), and CbmRichRingLight::SetSelectionNN().
Referenced by CbmRichRingFinderHoughImpl::FindPeak().
void CbmRichRingSelectAnn::Init (void) virtual
Initialize ANN.
Definition at line 27 of file CbmRichRingSelectAnn.cxx.
View newest version in sPHENIX GitHub at line 27 of file CbmRichRingSelectAnn.cxx
References fAnnWeights, fNN, fSelectImpl, and x.
Referenced by CbmRichRingFinderHoughImpl::Init().
CbmRichRingSelectAnn& CbmRichRingSelectAnn::operator= (const CbmRichRingSelectAnn &) private
Assignment operator.
void CbmRichRingSelectAnn::SetAnnWeights (const string & fileName) inline
Set path to the file with ANN weights.
Parameters
[in] fileName Path to the file name with ANN weights.
Definition at line 73 of file CbmRichRingSelectAnn.h.
View newest version in sPHENIX GitHub at line 73 of file CbmRichRingSelectAnn.h
Member Data Documentation
std::string CbmRichRingSelectAnn::fAnnWeights private
Definition at line 42 of file CbmRichRingSelectAnn.h.
View newest version in sPHENIX GitHub at line 42 of file CbmRichRingSelectAnn.h
Referenced by CbmRichRingSelectAnn(), and Init().
TMultiLayerPerceptron* CbmRichRingSelectAnn::fNN private
Definition at line 43 of file CbmRichRingSelectAnn.h.
View newest version in sPHENIX GitHub at line 43 of file CbmRichRingSelectAnn.h
Referenced by DoSelect(), and Init().
CbmRichRingSelectImpl* CbmRichRingSelectAnn::fSelectImpl private
Definition at line 44 of file CbmRichRingSelectAnn.h.
View newest version in sPHENIX GitHub at line 44 of file CbmRichRingSelectAnn.h
Referenced by DoSelect(), and Init().
The documentation for this class was generated from the following files:
EicRoot/blob/master/rich/selection/CbmRichRingSelectAnn.h
EicRoot/blob/master/rich/selection/CbmRichRingSelectAnn.cxx