EIC Software: AllSiliconTrackerDetector Class Reference
AllSiliconTrackerDetector Class Reference
#include <fun4all_eicdetectors/blob/master/simulation/g4simulation/g4lblvtx/AllSiliconTrackerDetector.h>
Public Member Functions
AllSiliconTrackerDetector (PHG4Subsystem *subsys, PHCompositeNode *Node, PHParameters *parameters, const std::string &dnam)
constructor
virtual ~AllSiliconTrackerDetector ()
destructor
void ConstructMe (G4LogicalVolume *world) override
construct
void Print (const std::string &what="ALL") const override
void SuperDetector (const std::string &name)
const std::string SuperDetector () const
int get_detid (const G4VPhysicalVolume *physvol, const int whichactive)
PHG4HitContainer * get_hitcontainer (const int i)
AllSiliconTrackerDetector (PHG4Subsystem *subsys, PHCompositeNode *Node, PHParameters *parameters, const std::string &dnam)
constructor
virtual ~AllSiliconTrackerDetector ()
destructor
void ConstructMe (G4LogicalVolume *world) override
construct
void Print (const std::string &what="ALL") const override
void SuperDetector (const std::string &name)
const std::string SuperDetector () const
int get_detid (const G4VPhysicalVolume *physvol, const int whichactive)
PHG4HitContainer * get_hitcontainer (const int i)
volume accessors
int IsInDetector (G4VPhysicalVolume *) const
int IsInDetector (G4VPhysicalVolume *) const
Public Member Functions inherited from PHG4Detector
PHG4Detector ()=delete
constructor
PHG4Detector (PHG4Subsystem *subsys, PHCompositeNode *Node, const std::string &nam)
virtual ~PHG4Detector (void)
destructor
virtual void Construct (G4LogicalVolume *world) final
construct method
virtual void PostConstruction ()
Optional PostConstruction call after all geometry is constructed.
virtual void Verbosity (const int v)
virtual int Verbosity () const
virtual G4UserSteppingAction * GetSteppingAction ()
virtual std::string GetName () const
virtual void OverlapCheck (const bool chk)
virtual bool OverlapCheck () const
virtual int DisplayVolume (G4VSolid *volume, G4LogicalVolume *logvol, G4RotationMatrix *rotm=nullptr)
virtual int DisplayVolume (G4LogicalVolume *checksolid, G4LogicalVolume *logvol, G4RotationMatrix *rotm=nullptr)
virtual PHCompositeNode * topNode ()
virtual PHG4Subsystem * GetMySubsystem ()
Private Types
enum { insertassemblies = 1, insertlogicalvolumes = 2 }
enum { insertassemblies = 1, insertlogicalvolumes = 2 }
Private Member Functions
void InsertVolumes (G4VPhysicalVolume *physvol, const int flag)
void AddHitNodes (PHCompositeNode *topNode)
void InsertVolumes (G4VPhysicalVolume *physvol, const int flag)
void AddHitNodes (PHCompositeNode *topNode)
Private Attributes
AllSiliconTrackerDisplayAction * m_DisplayAction
PHParameters * m_Params
std::string m_GDMPath
std::string m_SuperDetector
int m_Active
int m_AbsorberActive
std::map< const
G4VPhysicalVolume *, int > m_ActivePhysicalVolumesSet
std::map< const
G4VPhysicalVolume *, int > m_PassivePhysicalVolumesSet
std::map< int, PHG4HitContainer * > m_HitContainerMap
Additional Inherited Members
Static Public Member Functions inherited from PHG4Detector
static G4Material * GetDetectorMaterial (const std::string &name, const bool quit=true)
static G4Element * GetDetectorElement (const std::string &name, const bool quit=true)
Detailed Description
Definition at line 20 of file AllSiliconTrackerDetector.h.
View newest version in sPHENIX GitHub at line 20 of file AllSiliconTrackerDetector.h
Member Enumeration Documentation
anonymous enum private
Enumerator:
insertassemblies
insertlogicalvolumes
Definition at line 46 of file AllSiliconTrackerDetector.h.
View newest version in sPHENIX GitHub at line 46 of file AllSiliconTrackerDetector.h
anonymous enum private
Enumerator:
insertassemblies
insertlogicalvolumes
Definition at line 46 of file AllSiliconTrackerDetector.h.
View newest version in sPHENIX GitHub at line 46 of file AllSiliconTrackerDetector.h
Constructor & Destructor Documentation
AllSiliconTrackerDetector::AllSiliconTrackerDetector (PHG4Subsystem * subsys, PHCompositeNode * Node, PHParameters * parameters, const std::string & dnam)
constructor
Definition at line 46 of file AllSiliconTrackerDetector.cc.
View newest version in sPHENIX GitHub at line 46 of file AllSiliconTrackerDetector.cc
virtual AllSiliconTrackerDetector::~AllSiliconTrackerDetector () inline virtual
destructor
Definition at line 27 of file AllSiliconTrackerDetector.h.
View newest version in sPHENIX GitHub at line 27 of file AllSiliconTrackerDetector.h
AllSiliconTrackerDetector::AllSiliconTrackerDetector (PHG4Subsystem * subsys, PHCompositeNode * Node, PHParameters * parameters, const std::string & dnam)
constructor
virtual AllSiliconTrackerDetector::~AllSiliconTrackerDetector () inline virtual
destructor
Definition at line 27 of file AllSiliconTrackerDetector.h.
View newest version in sPHENIX GitHub at line 27 of file AllSiliconTrackerDetector.h
Member Function Documentation
void AllSiliconTrackerDetector::AddHitNodes (PHCompositeNode * topNode) private
Definition at line 259 of file AllSiliconTrackerDetector.cc.
View newest version in sPHENIX GitHub at line 259 of file AllSiliconTrackerDetector.cc
References PHCompositeNode::addNode(), PHNodeIterator::findFirst(), PHParameters::get_int_param(), PHG4Detector::GetName(), m_ActivePhysicalVolumesSet, m_HitContainerMap, m_Params, PHCompositeNode::PHCompositeNode(), and SuperDetector().
Referenced by ConstructMe().
void AllSiliconTrackerDetector::AddHitNodes (PHCompositeNode * topNode) private
void AllSiliconTrackerDetector::ConstructMe (G4LogicalVolume * world) override virtual
construct
Implements PHG4Detector.
Definition at line 82 of file AllSiliconTrackerDetector.cc.
View newest version in sPHENIX GitHub at line 82 of file AllSiliconTrackerDetector.cc
References AddHitNodes(), AllSiliconTrackerSubsystem::assembly_iters(), PHParameters::get_double_param(), G4GDMLReadStructure::GetAssembly(), PHG4Detector::GetMySubsystem(), PHG4Detector::GetName(), G4GDMLReadStructure::GetVolume(), insertassemblies, insertlogicalvolumes, InsertVolumes(), it, AllSiliconTrackerSubsystem::logvol_iters(), m_GDMPath, m_Params, PHG4Detector::OverlapCheck(), reader(), G4GDMLParser::SetOverlapCheck(), and PHG4Detector::topNode().
void AllSiliconTrackerDetector::ConstructMe (G4LogicalVolume * world) override virtual
construct
Implements PHG4Detector.
int AllSiliconTrackerDetector::get_detid (const G4VPhysicalVolume * physvol, const int whichactive)
Definition at line 241 of file AllSiliconTrackerDetector.cc.
View newest version in sPHENIX GitHub at line 241 of file AllSiliconTrackerDetector.cc
References m_ActivePhysicalVolumesSet, and m_PassivePhysicalVolumesSet.
Referenced by AllSiliconTrackerSteppingAction::UserSteppingAction().
int AllSiliconTrackerDetector::get_detid (const G4VPhysicalVolume * physvol, const int whichactive)
PHG4HitContainer* AllSiliconTrackerDetector::get_hitcontainer (const int i)
PHG4HitContainer * AllSiliconTrackerDetector::get_hitcontainer (const int i)
Definition at line 326 of file AllSiliconTrackerDetector.cc.
View newest version in sPHENIX GitHub at line 326 of file AllSiliconTrackerDetector.cc
References exit(), and m_HitContainerMap.
Referenced by AllSiliconTrackerSteppingAction::UserSteppingAction().
void AllSiliconTrackerDetector::InsertVolumes (G4VPhysicalVolume * physvol, const int flag) private
Definition at line 147 of file AllSiliconTrackerDetector.cc.
View newest version in sPHENIX GitHub at line 147 of file AllSiliconTrackerDetector.cc
References AllSiliconTrackerDisplayAction::AddLogicalVolume(), insertassemblies, m_AbsorberActive, m_ActivePhysicalVolumesSet, m_DisplayAction, m_PassivePhysicalVolumesSet, and pos().
Referenced by ConstructMe().
void AllSiliconTrackerDetector::InsertVolumes (G4VPhysicalVolume * physvol, const int flag) private
int AllSiliconTrackerDetector::IsInDetector (G4VPhysicalVolume *) const
int AllSiliconTrackerDetector::IsInDetector (G4VPhysicalVolume * volume) const
Definition at line 60 of file AllSiliconTrackerDetector.cc.
View newest version in sPHENIX GitHub at line 60 of file AllSiliconTrackerDetector.cc
References m_AbsorberActive, m_Active, m_ActivePhysicalVolumesSet, and m_PassivePhysicalVolumesSet.
Referenced by AllSiliconTrackerSteppingAction::UserSteppingAction().
void AllSiliconTrackerDetector::Print (const std::string & what = "ALL") const override virtual
Reimplemented from PHG4Detector.
Definition at line 229 of file AllSiliconTrackerDetector.cc.
View newest version in sPHENIX GitHub at line 229 of file AllSiliconTrackerDetector.cc
References m_Params, and PHParameters::Print().
Referenced by AllSiliconTrackerSubsystem::Print().
void AllSiliconTrackerDetector::Print (const std::string & what = "ALL") const override virtual
Reimplemented from PHG4Detector.
void AllSiliconTrackerDetector::SuperDetector (const std::string & name) inline
Definition at line 39 of file AllSiliconTrackerDetector.h.
View newest version in sPHENIX GitHub at line 39 of file AllSiliconTrackerDetector.h
References m_SuperDetector, and name.
Referenced by AllSiliconTrackerSubsystem::InitRunSubsystem().
void AllSiliconTrackerDetector::SuperDetector (const std::string & name) inline
Definition at line 39 of file AllSiliconTrackerDetector.h.
View newest version in sPHENIX GitHub at line 39 of file AllSiliconTrackerDetector.h
References m_SuperDetector, and name.
const std::string AllSiliconTrackerDetector::SuperDetector () const inline
Definition at line 40 of file AllSiliconTrackerDetector.h.
View newest version in sPHENIX GitHub at line 40 of file AllSiliconTrackerDetector.h
References m_SuperDetector.
Referenced by AddHitNodes().
const std::string AllSiliconTrackerDetector::SuperDetector () const inline
Definition at line 40 of file AllSiliconTrackerDetector.h.
View newest version in sPHENIX GitHub at line 40 of file AllSiliconTrackerDetector.h
References m_SuperDetector.
Member Data Documentation
int AllSiliconTrackerDetector::m_AbsorberActive private
Definition at line 60 of file AllSiliconTrackerDetector.h.
View newest version in sPHENIX GitHub at line 60 of file AllSiliconTrackerDetector.h
Referenced by InsertVolumes(), and IsInDetector().
int AllSiliconTrackerDetector::m_Active private
Definition at line 59 of file AllSiliconTrackerDetector.h.
View newest version in sPHENIX GitHub at line 59 of file AllSiliconTrackerDetector.h
Referenced by IsInDetector().
std::map< const G4VPhysicalVolume *, int > AllSiliconTrackerDetector::m_ActivePhysicalVolumesSet private
Definition at line 63 of file AllSiliconTrackerDetector.h.
View newest version in sPHENIX GitHub at line 63 of file AllSiliconTrackerDetector.h
Referenced by AddHitNodes(), get_detid(), InsertVolumes(), and IsInDetector().
AllSiliconTrackerDisplayAction * AllSiliconTrackerDetector::m_DisplayAction private
Definition at line 53 of file AllSiliconTrackerDetector.h.
View newest version in sPHENIX GitHub at line 53 of file AllSiliconTrackerDetector.h
Referenced by InsertVolumes().
std::string AllSiliconTrackerDetector::m_GDMPath private
Definition at line 56 of file AllSiliconTrackerDetector.h.
View newest version in sPHENIX GitHub at line 56 of file AllSiliconTrackerDetector.h
Referenced by ConstructMe().
std::map< int, PHG4HitContainer * > AllSiliconTrackerDetector::m_HitContainerMap private
Definition at line 66 of file AllSiliconTrackerDetector.h.
View newest version in sPHENIX GitHub at line 66 of file AllSiliconTrackerDetector.h
Referenced by AddHitNodes(), and get_hitcontainer().
PHParameters * AllSiliconTrackerDetector::m_Params private
Definition at line 54 of file AllSiliconTrackerDetector.h.
View newest version in sPHENIX GitHub at line 54 of file AllSiliconTrackerDetector.h
Referenced by AddHitNodes(), ConstructMe(), and Print().
std::map< const G4VPhysicalVolume *, int > AllSiliconTrackerDetector::m_PassivePhysicalVolumesSet private
Definition at line 64 of file AllSiliconTrackerDetector.h.
View newest version in sPHENIX GitHub at line 64 of file AllSiliconTrackerDetector.h
Referenced by get_detid(), InsertVolumes(), and IsInDetector().
std::string AllSiliconTrackerDetector::m_SuperDetector private
Definition at line 58 of file AllSiliconTrackerDetector.h.
View newest version in sPHENIX GitHub at line 58 of file AllSiliconTrackerDetector.h
Referenced by SuperDetector().
The documentation for this class was generated from the following files:
fun4all_eicdetectors/blob/master/simulation/g4simulation/g4lblvtx/AllSiliconTrackerDetector.h
g4lblvtx/blob/master/source/AllSiliconTrackerDetector.h
fun4all_eicdetectors/blob/master/simulation/g4simulation/g4lblvtx/AllSiliconTrackerDetector.cc
g4lblvtx/blob/master/source/AllSiliconTrackerDetector.cc