EIC Software: FairGeanePro Class Reference
FairGeanePro Class Reference
#include <EicRoot/blob/master/geane/FairGeanePro.h>
Public Member Functions
FairGeanePro ()
~FairGeanePro ()
Bool_t Propagate (FairTrackParH *TStart, FairTrackParH *TEnd, Int_t PDG)
Bool_t Propagate (FairTrackParP *TStart, FairTrackParH *TEnd, Int_t PDG)
Bool_t Propagate (FairTrackParP *TStart, FairTrackParP *TEnd, Int_t PDG)
Bool_t Propagate (FairTrackParH *TStart, FairTrackParP *TEnd, Int_t PDG)
Bool_t Propagate (Float_t *x1, Float_t *p1, Float_t *x2, Float_t *p2, Int_t PDG)
Bool_t PropagateToPlane (TVector3 &v0, TVector3 &v1, TVector3 &v2)
Bool_t PropagateFromPlane (TVector3 &v1, TVector3 &v2)
Bool_t PropagateToVolume (TString VolName, Int_t CopyNo, Int_t option)
Bool_t PropagateToLength (Float_t length)
Bool_t PropagateOnlyParameters ()
void Init (FairTrackPar *TParam)
Bool_t Propagate (Int_t PDG)
Bool_t SetWire (TVector3 extremity1, TVector3 extremity2)
Bool_t SetPoint (TVector3 pnt)
Bool_t PropagateToPCA (Int_t pca)
Bool_t PropagateToPCA (Int_t pca, Int_t dir)
int FindPCA (Int_t pca, Int_t PDGCode, TVector3 point, TVector3 wire1, TVector3 wire2, Double_t maxdistance, Double_t &Rad, TVector3 &vpf, TVector3 &vwi, Double_t &Di, Float_t &trklength)
TVector3 GetPCAOnWire ()
TVector3 GetPCAOnTrack ()
Float_t GetLengthAtPCA ()
Bool_t PropagateToVirtualPlaneAtPCA (Int_t pca)
Bool_t BackTrackToVertex ()
Bool_t BackTrackToVirtualPlaneAtPCA (Int_t pca)
void setBackProp ()
Bool_t ActualFindPCA (Int_t pca, FairTrackParP *par, Int_t dir)
void GetTransportMatrix (Double_t trm[5][5])
Private Member Functions
void Track2ToLine (TVector3 x1, TVector3 x2, TVector3 w1, TVector3 w2, TVector3 &Pfinal, TVector3 &Pwire, Int_t &Iflag, Double_t &Dist, Double_t &Length)
void Track2ToPoint (TVector3 x1, TVector3 x2, TVector3 w1, TVector3 &Pfinal, Double_t &Dist, Double_t &Length, Int_t &quitFlag)
void Track3ToLine (TVector3 x1, TVector3 x2, TVector3 x3, TVector3 w1, TVector3 w2, TVector3 &Pfinal, TVector3 &Wire, Int_t &Iflag, Double_t &Dist, Double_t &Length, Double_t &Radius)
void Track3ToPoint (TVector3 x1, TVector3 x2, TVector3 x3, TVector3 w1, TVector3 &Pfinal, Int_t &Iflag, Double_t &Dist, Double_t &Length, Double_t &Radius)
FairGeanePro (const FairGeanePro &)
FairGeanePro & operator= (const FairGeanePro &)
ClassDef (FairGeanePro, 1)
Private Attributes
TGeant3 * gMC3
TString fPropOption
Float_t xlf [1]
Float_t ein [15]
Int_t nepred
TDatabasePDG * fdbPDG
Float_t pli [6]
Float_t x2 [3]
Float_t p2 [3]
Ertrio_t * afErtrio
Float_t x1 [3]
Float_t p1 [3]
Int_t GeantCode
Int_t ProMode
Float_t plo [12]
TString VName
Int_t VCopyNo
Bool_t VEnter
TVector3 fpoint
TVector3 fwire1
TVector3 fwire2
Int_t fPCA
Double_t fRad
Double_t fDi
TVector3 fvpf
TVector3 fvwi
Float_t ftrklength
Int_t flag
FairGeaneApplication * fApp
Double_t trpmat [5][5]
Detailed Description
Definition at line 21 of file FairGeanePro.h.
View newest version in sPHENIX GitHub at line 21 of file FairGeanePro.h
Constructor & Destructor Documentation
FairGeanePro::FairGeanePro ()
Default constructor
Definition at line 29 of file FairGeanePro.cxx.
View newest version in sPHENIX GitHub at line 29 of file FairGeanePro.cxx
References afErtrio, ein, gMC3, p1, p2, pli, plo, trpmat, x1, x2, and xlf.
FairGeanePro::~FairGeanePro ()
Destructor
Definition at line 126 of file FairGeanePro.cxx.
View newest version in sPHENIX GitHub at line 126 of file FairGeanePro.cxx
FairGeanePro::FairGeanePro (const FairGeanePro &) private
Member Function Documentation
Bool_t FairGeanePro::ActualFindPCA (Int_t pca, FairTrackParP * par, Int_t dir)
Definition at line 510 of file FairGeanePro.cxx.
View newest version in sPHENIX GitHub at line 510 of file FairGeanePro.cxx
References ein, fDi, fPCA, fPropOption, fRad, ftrklength, fvpf, fvwi, Init(), and ProMode.
Referenced by GeaneTrackRep::extrapolateToLine().
Bool_t FairGeanePro::BackTrackToVertex ()
Definition at line 529 of file FairGeanePro.cxx.
View newest version in sPHENIX GitHub at line 529 of file FairGeanePro.cxx
References fDi, fPCA, fPropOption, fRad, ftrklength, fvpf, fvwi, and ProMode.
Bool_t FairGeanePro::BackTrackToVirtualPlaneAtPCA (Int_t pca)
Definition at line 559 of file FairGeanePro.cxx.
View newest version in sPHENIX GitHub at line 559 of file FairGeanePro.cxx
References fDi, fPCA, fPropOption, fRad, ftrklength, fvpf, fvwi, and ProMode.
Referenced by GeaneTrackRep::extrapolateToPoint(), and GeaneTrackRep::getPocaOnLine().
FairGeanePro::ClassDef (FairGeanePro , 1) private
int FairGeanePro::FindPCA (Int_t pca, Int_t PDGCode, TVector3 point, TVector3 wire1, TVector3 wire2, Double_t maxdistance, Double_t & Rad, TVector3 & vpf, TVector3 & vwi, Double_t & Di, Float_t & trklength)
Definition at line 576 of file FairGeanePro.cxx.
View newest version in sPHENIX GitHub at line 576 of file FairGeanePro.cxx
References ein, fdbPDG, flag, fPropOption, GeantCode, gMC3, p1, p2, Track2ToLine(), Track2ToPoint(), Track3ToLine(), Track3ToPoint(), x1, and x2.
Referenced by GeaneTrackRep::extrapolateToLine(), and Propagate().
Float_t FairGeanePro::GetLengthAtPCA () inline
Definition at line 60 of file FairGeanePro.h.
View newest version in sPHENIX GitHub at line 60 of file FairGeanePro.h
References ftrklength.
Referenced by GeaneTrackRep::extrapolate().
TVector3 FairGeanePro::GetPCAOnTrack () inline
Definition at line 59 of file FairGeanePro.h.
View newest version in sPHENIX GitHub at line 59 of file FairGeanePro.h
References fvpf.
TVector3 FairGeanePro::GetPCAOnWire () inline
Definition at line 58 of file FairGeanePro.h.
View newest version in sPHENIX GitHub at line 58 of file FairGeanePro.h
References fvwi.
Referenced by GeaneTrackRep::getPocaOnLine().
void FairGeanePro::GetTransportMatrix (Double_t trm[5][5])
Definition at line 1288 of file FairGeanePro.cxx.
View newest version in sPHENIX GitHub at line 1288 of file FairGeanePro.cxx
References trpmat.
void FairGeanePro::Init (FairTrackPar * TParam)
Definition at line 371 of file FairGeanePro.cxx.
View newest version in sPHENIX GitHub at line 371 of file FairGeanePro.cxx
References FairTrackPar::GetPx(), FairTrackPar::GetPy(), FairTrackPar::GetPz(), FairTrackPar::GetX(), FairTrackPar::GetY(), FairTrackPar::GetZ(), p1, p2, x1, and x2.
Referenced by ActualFindPCA(), and Propagate().
FairGeanePro& FairGeanePro::operator= (const FairGeanePro &) private
Bool_t FairGeanePro::Propagate (FairTrackParH * TStart, FairTrackParH * TEnd, Int_t PDG)
Definition at line 130 of file FairGeanePro.cxx.
View newest version in sPHENIX GitHub at line 130 of file FairGeanePro.cxx
References afErtrio, Acts::UnitConstants::e, ein, fDi, FindPCA(), fPCA, fpoint, fPropOption, fRad, ftrklength, fvpf, fvwi, fwire1, fwire2, FairTrackParH::GetCovQ(), FairTrackPar::GetQ(), FairTrackParH::GetX(), FairTrackParH::GetY(), FairTrackParH::GetZ(), gMC3, Init(), nepred, p2, ProMode, FairTrackParH::SetTrackPar(), start(), VCopyNo, VEnter, VName, x2, and xlf.
Referenced by CbmRichTrackExtrapolationKF::DoExtrapolation(), FairMCStack::Exec(), GeaneTrackRep::extrapolate(), GeaneTrackRep::extrapolateToPoint(), PndRecoKalmanFit::Fit(), PndRecoDafFit::Fit(), GeaneTrackRep::getPocaOnLine(), PndPidCorrelator::GetTrackInfo(), and Propagate().
Bool_t FairGeanePro::Propagate (FairTrackParP * TStart, FairTrackParH * TEnd, Int_t PDG)
Definition at line 203 of file FairGeanePro.cxx.
View newest version in sPHENIX GitHub at line 203 of file FairGeanePro.cxx
Bool_t FairGeanePro::Propagate (FairTrackParP * TStart, FairTrackParP * TEnd, Int_t PDG)
We have the right representation go further
Definition at line 210 of file FairGeanePro.cxx.
View newest version in sPHENIX GitHub at line 210 of file FairGeanePro.cxx
References afErtrio, Acts::UnitConstants::e, ein, fDi, FindPCA(), fPCA, fpoint, fPropOption, fRad, ftrklength, fvpf, fvwi, fwire1, fwire2, FairTrackParP::GetCovQ(), FairTrackParP::GetJVer(), FairTrackParP::GetKVer(), FairTrackPar::GetPx(), FairTrackPar::GetPy(), FairTrackPar::GetPz(), FairTrackPar::GetQ(), FairTrackPar::GetX(), FairTrackPar::GetY(), FairTrackPar::GetZ(), gMC3, Init(), charm_jet_coverage::mom, nepred, Acts::Test::origin(), p2, pli, plo, ProMode, Propagate(), PropagateFromPlane(), PropagateToPlane(), FairTrackParP::SetTrackPar(), start(), and x2.
Bool_t FairGeanePro::Propagate (FairTrackParH * TStart, FairTrackParP * TEnd, Int_t PDG)
Definition at line 325 of file FairGeanePro.cxx.
View newest version in sPHENIX GitHub at line 325 of file FairGeanePro.cxx
Bool_t FairGeanePro::Propagate (Float_t * x1, Float_t * p1, Float_t * x2, Float_t * p2, Int_t PDG)
Definition at line 332 of file FairGeanePro.cxx.
View newest version in sPHENIX GitHub at line 332 of file FairGeanePro.cxx
References ein, fdbPDG, GeantCode, gMC3, and xlf.
Bool_t FairGeanePro::Propagate (Int_t PDG)
Definition at line 345 of file FairGeanePro.cxx.
View newest version in sPHENIX GitHub at line 345 of file FairGeanePro.cxx
References afErtrio, fdbPDG, fPropOption, FairGeaneUtil::FromVecToMat(), ftrklength, GeantCode, gMC3, p1, p2, trpmat, x1, and x2.
Bool_t FairGeanePro::PropagateFromPlane (TVector3 & v1, TVector3 & v2)
Definition at line 389 of file FairGeanePro.cxx.
View newest version in sPHENIX GitHub at line 389 of file FairGeanePro.cxx
References pli.
Referenced by GeaneTrackRep::extrapolate(), GeaneTrackRep::extrapolateToPoint(), GeaneTrackRep::getPocaOnLine(), and Propagate().
Bool_t FairGeanePro::PropagateOnlyParameters ()
Definition at line 455 of file FairGeanePro.cxx.
View newest version in sPHENIX GitHub at line 455 of file FairGeanePro.cxx
References fPropOption.
Bool_t FairGeanePro::PropagateToLength (Float_t length)
Definition at line 447 of file FairGeanePro.cxx.
View newest version in sPHENIX GitHub at line 447 of file FairGeanePro.cxx
References fPropOption, G4BARRELHCAL::length, ProMode, and xlf.
Referenced by FairMCStack::Exec().
Bool_t FairGeanePro::PropagateToPCA (Int_t pca)
Definition at line 478 of file FairGeanePro.cxx.
View newest version in sPHENIX GitHub at line 478 of file FairGeanePro.cxx
References fDi, fPCA, fPropOption, fRad, ftrklength, fvpf, fvwi, and ProMode.
Referenced by PndRecoDafFit::Fit(), PndRecoKalmanFit::Fit(), and PndPidCorrelator::GetTrackInfo().
Bool_t FairGeanePro::PropagateToPCA (Int_t pca, Int_t dir)
Definition at line 493 of file FairGeanePro.cxx.
View newest version in sPHENIX GitHub at line 493 of file FairGeanePro.cxx
References fDi, fPCA, fPropOption, fRad, ftrklength, fvpf, fvwi, and ProMode.
Bool_t FairGeanePro::PropagateToPlane (TVector3 & v0, TVector3 & v1, TVector3 & v2)
Definition at line 403 of file FairGeanePro.cxx.
View newest version in sPHENIX GitHub at line 403 of file FairGeanePro.cxx
References fPropOption, plo, ProMode, and v3.
Referenced by CbmRichTrackExtrapolationKF::DoExtrapolation(), GeaneTrackRep::extrapolate(), and Propagate().
Bool_t FairGeanePro::PropagateToVirtualPlaneAtPCA (Int_t pca)
Definition at line 544 of file FairGeanePro.cxx.
View newest version in sPHENIX GitHub at line 544 of file FairGeanePro.cxx
References fDi, fPCA, fPropOption, fRad, ftrklength, fvpf, fvwi, and ProMode.
Referenced by GeaneTrackRep::extrapolateToPoint(), and GeaneTrackRep::getPocaOnLine().
Bool_t FairGeanePro::PropagateToVolume (TString VolName, Int_t CopyNo, Int_t option)
Definition at line 434 of file FairGeanePro.cxx.
View newest version in sPHENIX GitHub at line 434 of file FairGeanePro.cxx
References ein, fPropOption, ProMode, VCopyNo, VEnter, and VName.
void FairGeanePro::setBackProp () inline
Definition at line 64 of file FairGeanePro.h.
View newest version in sPHENIX GitHub at line 64 of file FairGeanePro.h
References fPropOption.
Referenced by GeaneTrackRep::extrapolate().
Bool_t FairGeanePro::SetPoint (TVector3 pnt)
Definition at line 471 of file FairGeanePro.cxx.
View newest version in sPHENIX GitHub at line 471 of file FairGeanePro.cxx
References fpoint.
Referenced by GeaneTrackRep::extrapolateToPoint(), PndRecoKalmanFit::Fit(), PndRecoDafFit::Fit(), and PndPidCorrelator::GetTrackInfo().
Bool_t FairGeanePro::SetWire (TVector3 extremity1, TVector3 extremity2)
Definition at line 463 of file FairGeanePro.cxx.
View newest version in sPHENIX GitHub at line 463 of file FairGeanePro.cxx
References fwire1, and fwire2.
Referenced by GeaneTrackRep::getPocaOnLine(), and PndPidCorrelator::GetTrackInfo().
void FairGeanePro::Track2ToLine (TVector3 x1, TVector3 x2, TVector3 w1, TVector3 w2, TVector3 & Pfinal, TVector3 & Pwire, Int_t & Iflag, Double_t & Dist, Double_t & Length) private
Definition at line 748 of file FairGeanePro.cxx.
View newest version in sPHENIX GitHub at line 748 of file FairGeanePro.cxx
References c1, Acts::UnitConstants::e, s1, and t1.
Referenced by FindPCA().
void FairGeanePro::Track2ToPoint (TVector3 x1, TVector3 x2, TVector3 w1, TVector3 & Pfinal, Double_t & Dist, Double_t & Length, Int_t & quitFlag) private
Definition at line 836 of file FairGeanePro.cxx.
View newest version in sPHENIX GitHub at line 836 of file FairGeanePro.cxx
References d, and t1.
Referenced by FindPCA().
void FairGeanePro::Track3ToLine (TVector3 x1, TVector3 x2, TVector3 x3, TVector3 w1, TVector3 w2, TVector3 & Pfinal, TVector3 & Wire, Int_t & Iflag, Double_t & Dist, Double_t & Length, Double_t & Radius) private
Definition at line 880 of file FairGeanePro.cxx.
View newest version in sPHENIX GitHub at line 880 of file FairGeanePro.cxx
References c1, c2, dx, Acts::UnitConstants::e, it, k, M, charm_jet_strange_helicity::N, T, t, and Track3ToPoint().
Referenced by FindPCA().
void FairGeanePro::Track3ToPoint (TVector3 x1, TVector3 x2, TVector3 x3, TVector3 w1, TVector3 & Pfinal, Int_t & Iflag, Double_t & Dist, Double_t & Length, Double_t & Radius) private
Definition at line 1124 of file FairGeanePro.cxx.
View newest version in sPHENIX GitHub at line 1124 of file FairGeanePro.cxx
References Acts::UnitConstants::e, Acts::UnitConstants::m3, and T.
Referenced by FindPCA(), and Track3ToLine().
Member Data Documentation
Ertrio_t* FairGeanePro::afErtrio private
Definition at line 89 of file FairGeanePro.h.
View newest version in sPHENIX GitHub at line 89 of file FairGeanePro.h
Referenced by FairGeanePro(), and Propagate().
Float_t FairGeanePro::ein[15] private
Definition at line 79 of file FairGeanePro.h.
View newest version in sPHENIX GitHub at line 79 of file FairGeanePro.h
Referenced by ActualFindPCA(), FairGeanePro(), FindPCA(), Propagate(), and PropagateToVolume().
FairGeaneApplication* FairGeanePro::fApp private
Definition at line 109 of file FairGeanePro.h.
View newest version in sPHENIX GitHub at line 109 of file FairGeanePro.h
TDatabasePDG* FairGeanePro::fdbPDG private
Definition at line 81 of file FairGeanePro.h.
View newest version in sPHENIX GitHub at line 81 of file FairGeanePro.h
Referenced by FindPCA(), and Propagate().
Double_t FairGeanePro::fDi private
Definition at line 105 of file FairGeanePro.h.
View newest version in sPHENIX GitHub at line 105 of file FairGeanePro.h
Referenced by ActualFindPCA(), BackTrackToVertex(), BackTrackToVirtualPlaneAtPCA(), Propagate(), PropagateToPCA(), and PropagateToVirtualPlaneAtPCA().
Int_t FairGeanePro::flag private
Definition at line 108 of file FairGeanePro.h.
View newest version in sPHENIX GitHub at line 108 of file FairGeanePro.h
Referenced by FindPCA().
Int_t FairGeanePro::fPCA private
Definition at line 104 of file FairGeanePro.h.
View newest version in sPHENIX GitHub at line 104 of file FairGeanePro.h
Referenced by ActualFindPCA(), BackTrackToVertex(), BackTrackToVirtualPlaneAtPCA(), Propagate(), PropagateToPCA(), and PropagateToVirtualPlaneAtPCA().
TVector3 FairGeanePro::fpoint private
Definition at line 103 of file FairGeanePro.h.
View newest version in sPHENIX GitHub at line 103 of file FairGeanePro.h
Referenced by Propagate(), and SetPoint().
TString FairGeanePro::fPropOption private
Definition at line 77 of file FairGeanePro.h.
View newest version in sPHENIX GitHub at line 77 of file FairGeanePro.h
Referenced by ActualFindPCA(), BackTrackToVertex(), BackTrackToVirtualPlaneAtPCA(), FindPCA(), Propagate(), PropagateOnlyParameters(), PropagateToLength(), PropagateToPCA(), PropagateToPlane(), PropagateToVirtualPlaneAtPCA(), PropagateToVolume(), and setBackProp().
Double_t FairGeanePro::fRad private
Definition at line 105 of file FairGeanePro.h.
View newest version in sPHENIX GitHub at line 105 of file FairGeanePro.h
Referenced by ActualFindPCA(), BackTrackToVertex(), BackTrackToVirtualPlaneAtPCA(), Propagate(), PropagateToPCA(), and PropagateToVirtualPlaneAtPCA().
Float_t FairGeanePro::ftrklength private
Definition at line 107 of file FairGeanePro.h.
View newest version in sPHENIX GitHub at line 107 of file FairGeanePro.h
Referenced by ActualFindPCA(), BackTrackToVertex(), BackTrackToVirtualPlaneAtPCA(), GetLengthAtPCA(), Propagate(), PropagateToPCA(), and PropagateToVirtualPlaneAtPCA().
TVector3 FairGeanePro::fvpf private
Definition at line 106 of file FairGeanePro.h.
View newest version in sPHENIX GitHub at line 106 of file FairGeanePro.h
Referenced by ActualFindPCA(), BackTrackToVertex(), BackTrackToVirtualPlaneAtPCA(), GetPCAOnTrack(), Propagate(), PropagateToPCA(), and PropagateToVirtualPlaneAtPCA().
TVector3 FairGeanePro::fvwi private
Definition at line 106 of file FairGeanePro.h.
View newest version in sPHENIX GitHub at line 106 of file FairGeanePro.h
Referenced by ActualFindPCA(), BackTrackToVertex(), BackTrackToVirtualPlaneAtPCA(), GetPCAOnWire(), Propagate(), PropagateToPCA(), and PropagateToVirtualPlaneAtPCA().
TVector3 FairGeanePro::fwire1 private
Definition at line 103 of file FairGeanePro.h.
View newest version in sPHENIX GitHub at line 103 of file FairGeanePro.h
Referenced by Propagate(), and SetWire().
TVector3 FairGeanePro::fwire2 private
Definition at line 103 of file FairGeanePro.h.
View newest version in sPHENIX GitHub at line 103 of file FairGeanePro.h
Referenced by Propagate(), and SetWire().
Int_t FairGeanePro::GeantCode private
Definition at line 92 of file FairGeanePro.h.
View newest version in sPHENIX GitHub at line 92 of file FairGeanePro.h
Referenced by FindPCA(), and Propagate().
TGeant3* FairGeanePro::gMC3 private
Definition at line 76 of file FairGeanePro.h.
View newest version in sPHENIX GitHub at line 76 of file FairGeanePro.h
Referenced by FairGeanePro(), FindPCA(), and Propagate().
Int_t FairGeanePro::nepred private
Definition at line 80 of file FairGeanePro.h.
View newest version in sPHENIX GitHub at line 80 of file FairGeanePro.h
Referenced by Propagate().
Float_t FairGeanePro::p1[3] private
Definition at line 91 of file FairGeanePro.h.
View newest version in sPHENIX GitHub at line 91 of file FairGeanePro.h
Referenced by FairGeanePro(), FindPCA(), Init(), and Propagate().
Float_t FairGeanePro::p2[3] private
Definition at line 84 of file FairGeanePro.h.
View newest version in sPHENIX GitHub at line 84 of file FairGeanePro.h
Referenced by FairGeanePro(), FindPCA(), Init(), and Propagate().
Float_t FairGeanePro::pli[6] private
Definition at line 82 of file FairGeanePro.h.
View newest version in sPHENIX GitHub at line 82 of file FairGeanePro.h
Referenced by FairGeanePro(), Propagate(), and PropagateFromPlane().
Float_t FairGeanePro::plo[12] private
Definition at line 98 of file FairGeanePro.h.
View newest version in sPHENIX GitHub at line 98 of file FairGeanePro.h
Referenced by FairGeanePro(), Propagate(), and PropagateToPlane().
Int_t FairGeanePro::ProMode private
Definition at line 96 of file FairGeanePro.h.
View newest version in sPHENIX GitHub at line 96 of file FairGeanePro.h
Referenced by ActualFindPCA(), BackTrackToVertex(), BackTrackToVirtualPlaneAtPCA(), Propagate(), PropagateToLength(), PropagateToPCA(), PropagateToPlane(), PropagateToVirtualPlaneAtPCA(), and PropagateToVolume().
Double_t FairGeanePro::trpmat[5][5] private
Definition at line 110 of file FairGeanePro.h.
View newest version in sPHENIX GitHub at line 110 of file FairGeanePro.h
Referenced by FairGeanePro(), GetTransportMatrix(), and Propagate().
Int_t FairGeanePro::VCopyNo private
Definition at line 100 of file FairGeanePro.h.
View newest version in sPHENIX GitHub at line 100 of file FairGeanePro.h
Referenced by Propagate(), and PropagateToVolume().
Bool_t FairGeanePro::VEnter private
Definition at line 101 of file FairGeanePro.h.
View newest version in sPHENIX GitHub at line 101 of file FairGeanePro.h
Referenced by Propagate(), and PropagateToVolume().
TString FairGeanePro::VName private
Definition at line 99 of file FairGeanePro.h.
View newest version in sPHENIX GitHub at line 99 of file FairGeanePro.h
Referenced by Propagate(), and PropagateToVolume().
Float_t FairGeanePro::x1[3] private
Definition at line 90 of file FairGeanePro.h.
View newest version in sPHENIX GitHub at line 90 of file FairGeanePro.h
Referenced by FairGeanePro(), FindPCA(), Init(), and Propagate().
Float_t FairGeanePro::x2[3] private
Definition at line 83 of file FairGeanePro.h.
View newest version in sPHENIX GitHub at line 83 of file FairGeanePro.h
Referenced by FairGeanePro(), FindPCA(), Init(), and Propagate().
Float_t FairGeanePro::xlf[1] private
Definition at line 78 of file FairGeanePro.h.
View newest version in sPHENIX GitHub at line 78 of file FairGeanePro.h
Referenced by FairGeanePro(), Propagate(), and PropagateToLength().
The documentation for this class was generated from the following files:
EicRoot/blob/master/geane/FairGeanePro.h
EicRoot/blob/master/geane/FairGeanePro.cxx