EIC Software: erhic::VirtualEvent Class Reference
erhic::VirtualEvent Class Reference abstract
Abstract base class for a physics event.
#include <eic-smear/blob/master/include/eicsmear/erhic/VirtualEvent.h>
Public Types
typedef std::vector< const
erhic::VirtualParticle * > ParticlePtrList
Public Member Functions
virtual ~VirtualEvent ()
virtual const VirtualParticle * GetTrack (UInt_t) const =0
virtual VirtualParticle * GetTrack (UInt_t)=0
virtual UInt_t GetNTracks () const =0
virtual void HadronicFinalState (ParticlePtrList &) const
Detailed Description
Abstract base class for a physics event.
Defines an "event" simply as a collection of tracks.
Definition at line 25 of file VirtualEvent.h.
View newest version in sPHENIX GitHub at line 25 of file VirtualEvent.h
Member Typedef Documentation
typedef std::vector<const erhic::VirtualParticle*> erhic::VirtualEvent::ParticlePtrList
typedef for a track pointer collection.
Definition at line 52 of file VirtualEvent.h.
View newest version in sPHENIX GitHub at line 52 of file VirtualEvent.h
Constructor & Destructor Documentation
virtual erhic::VirtualEvent::~VirtualEvent () inline virtual
Destructor
Definition at line 30 of file VirtualEvent.h.
View newest version in sPHENIX GitHub at line 30 of file VirtualEvent.h
Member Function Documentation
virtual UInt_t erhic::VirtualEvent::GetNTracks () const pure virtual
Returns the number of tracks in the event.
Implemented in erhic::EventMC, erhic::hadronic::EventMC, Smear::Event, erhic::hadronic::EventSmear, and EicRcEvent.
Referenced by Smear::EventDisFactory::Create(), EicSmearTask::Exec(), erhic::Forester::Plant(), and EicEventGenerator::ReadEvent().
virtual const VirtualParticle* erhic::VirtualEvent::GetTrack (UInt_t) const pure virtual
Returns the nth track from the event.
Indices run from 0 to (n-1).
Implemented in erhic::EventMC, Smear::Event, erhic::hadronic::EventMC, EicRcEvent, and erhic::hadronic::EventSmear.
Referenced by Smear::EventDisFactory::Create(), EicSmearTask::Exec(), ParticleIdentifier::IdentifyBeams(), and EicEventGenerator::ReadEvent().
virtual VirtualParticle* erhic::VirtualEvent::GetTrack (UInt_t) pure virtual
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Implemented in erhic::EventMC, Smear::Event, erhic::hadronic::EventMC, erhic::hadronic::EventSmear, and EicRcEvent.
virtual void erhic::VirtualEvent::HadronicFinalState (ParticlePtrList &) const inline virtual
Populate a track list with the hadronic final-state. Note that the method is a bit of a misnomer - it will return ALL final particles other than the scattered lepton (intentionally, since you want to take decay products into account as well)
Reimplemented in erhic::EventMC, Smear::Event, and EicRcEvent.
Definition at line 60 of file VirtualEvent.h.
View newest version in sPHENIX GitHub at line 60 of file VirtualEvent.h
Referenced by erhic::DoubleAngleComputer::DoubleAngleComputer(), and erhic::JacquetBlondelComputer::JacquetBlondelComputer().
The documentation for this class was generated from the following file:
eic-smear/blob/master/include/eicsmear/erhic/VirtualEvent.h