EIC Software: tetgenmesh Class Reference
tetgenmesh Class Reference
#include <EicRoot/blob/master/eic/cad/tetgen/tetgen.h>
Classes
class arraypool
class badface
class face
class flipconstraints
class insertvertexflags
class memorypool
class optparameters
class triface
Public Types
enum verttype {
UNUSEDVERTEX, DUPLICATEDVERTEX, RIDGEVERTEX, ACUTEVERTEX,
FACETVERTEX, VOLVERTEX, FREESEGVERTEX, FREEFACETVERTEX,
FREEVOLVERTEX, NREGULARVERTEX, DEADVERTEX
}
enum interresult {
DISJOINT, INTERSECT, SHAREVERT, SHAREEDGE,
SHAREFACE, TOUCHEDGE, TOUCHFACE, ACROSSVERT,
ACROSSEDGE, ACROSSFACE, COLLISIONFACE, ACROSSSEG,
ACROSSSUB
}
enum locateresult {
UNKNOWN, OUTSIDE, INTETRAHEDRON, ONFACE,
ONEDGE, ONVERTEX, ENCVERTEX, ENCSEGMENT,
ENCSUBFACE, NEARVERTEX, NONREGULAR, INSTAR,
BADELEMENT
}
typedef REAL ** tetrahedron
typedef REAL ** shellface
typedef REAL * point
Public Member Functions
void inittables ()
tetrahedron encode (triface &t)
tetrahedron encode2 (tetrahedron *ptr, int ver)
void decode (tetrahedron ptr, triface &t)
void bond (triface &t1, triface &t2)
void dissolve (triface &t)
void esym (triface &t1, triface &t2)
void esymself (triface &t)
void enext (triface &t1, triface &t2)
void enextself (triface &t)
void eprev (triface &t1, triface &t2)
void eprevself (triface &t)
void enextesym (triface &t1, triface &t2)
void enextesymself (triface &t)
void eprevesym (triface &t1, triface &t2)
void eprevesymself (triface &t)
void eorgoppo (triface &t1, triface &t2)
void eorgoppoself (triface &t)
void edestoppo (triface &t1, triface &t2)
void edestoppoself (triface &t)
void fsym (triface &t1, triface &t2)
void fsymself (triface &t)
void fnext (triface &t1, triface &t2)
void fnextself (triface &t)
point org (triface &t)
point dest (triface &t)
point apex (triface &t)
point oppo (triface &t)
void setorg (triface &t, point p)
void setdest (triface &t, point p)
void setapex (triface &t, point p)
void setoppo (triface &t, point p)
REAL elemattribute (tetrahedron *ptr, int attnum)
void setelemattribute (tetrahedron *ptr, int attnum, REAL value)
REAL volumebound (tetrahedron *ptr)
void setvolumebound (tetrahedron *ptr, REAL value)
int elemindex (tetrahedron *ptr)
void setelemindex (tetrahedron *ptr, int value)
int elemmarker (tetrahedron *ptr)
void setelemmarker (tetrahedron *ptr, int value)
void infect (triface &t)
void uninfect (triface &t)
bool infected (triface &t)
void marktest (triface &t)
void unmarktest (triface &t)
bool marktested (triface &t)
void markface (triface &t)
void unmarkface (triface &t)
bool facemarked (triface &t)
void markedge (triface &t)
void unmarkedge (triface &t)
bool edgemarked (triface &t)
void marktest2 (triface &t)
void unmarktest2 (triface &t)
bool marktest2ed (triface &t)
int elemcounter (triface &t)
void setelemcounter (triface &t, int value)
void increaseelemcounter (triface &t)
void decreaseelemcounter (triface &t)
bool ishulltet (triface &t)
bool isdeadtet (triface &t)
void sdecode (shellface sptr, face &s)
shellface sencode (face &s)
shellface sencode2 (shellface *sh, int shver)
void spivot (face &s1, face &s2)
void spivotself (face &s)
void sbond (face &s1, face &s2)
void sbond1 (face &s1, face &s2)
void sdissolve (face &s)
point sorg (face &s)
point sdest (face &s)
point sapex (face &s)
void setsorg (face &s, point pointptr)
void setsdest (face &s, point pointptr)
void setsapex (face &s, point pointptr)
void sesym (face &s1, face &s2)
void sesymself (face &s)
void senext (face &s1, face &s2)
void senextself (face &s)
void senext2 (face &s1, face &s2)
void senext2self (face &s)
REAL areabound (face &s)
void setareabound (face &s, REAL value)
int shellmark (face &s)
void setshellmark (face &s, int value)
void sinfect (face &s)
void suninfect (face &s)
bool sinfected (face &s)
void smarktest (face &s)
void sunmarktest (face &s)
bool smarktested (face &s)
void smarktest2 (face &s)
void sunmarktest2 (face &s)
bool smarktest2ed (face &s)
void smarktest3 (face &s)
void sunmarktest3 (face &s)
bool smarktest3ed (face &s)
void setfacetindex (face &f, int value)
int getfacetindex (face &f)
void tsbond (triface &t, face &s)
void tsdissolve (triface &t)
void stdissolve (face &s)
void tspivot (triface &t, face &s)
void stpivot (face &s, triface &t)
void tssbond1 (triface &t, face &seg)
void sstbond1 (face &s, triface &t)
void tssdissolve1 (triface &t)
void sstdissolve1 (face &s)
void tsspivot1 (triface &t, face &s)
void sstpivot1 (face &s, triface &t)
void ssbond (face &s, face &edge)
void ssbond1 (face &s, face &edge)
void ssdissolve (face &s)
void sspivot (face &s, face &edge)
int pointmark (point pt)
void setpointmark (point pt, int value)
enum verttype pointtype (point pt)
void setpointtype (point pt, enum verttype value)
int pointgeomtag (point pt)
void setpointgeomtag (point pt, int value)
REAL pointgeomuv (point pt, int i)
void setpointgeomuv (point pt, int i, REAL value)
void pinfect (point pt)
void puninfect (point pt)
bool pinfected (point pt)
void pmarktest (point pt)
void punmarktest (point pt)
bool pmarktested (point pt)
void pmarktest2 (point pt)
void punmarktest2 (point pt)
bool pmarktest2ed (point pt)
void pmarktest3 (point pt)
void punmarktest3 (point pt)
bool pmarktest3ed (point pt)
tetrahedron point2tet (point pt)
void setpoint2tet (point pt, tetrahedron value)
shellface point2sh (point pt)
void setpoint2sh (point pt, shellface value)
point point2ppt (point pt)
void setpoint2ppt (point pt, point value)
tetrahedron point2bgmtet (point pt)
void setpoint2bgmtet (point pt, tetrahedron value)
void setpointinsradius (point pt, REAL value)
REAL getpointinsradius (point pt)
void point2tetorg (point pt, triface &t)
void point2shorg (point pa, face &s)
point farsorg (face &seg)
point farsdest (face &seg)
void tetrahedrondealloc (tetrahedron *)
tetrahedron * tetrahedrontraverse ()
tetrahedron * alltetrahedrontraverse ()
void shellfacedealloc (memorypool *, shellface *)
shellface * shellfacetraverse (memorypool *)
void pointdealloc (point)
point pointtraverse ()
void makeindex2pointmap (point *&)
void makepoint2submap (memorypool *, int *&, face *&)
void maketetrahedron (triface *)
void makeshellface (memorypool *, face *)
void makepoint (point *, enum verttype)
void initializepools ()
REAL insphere_s (REAL *, REAL *, REAL *, REAL *, REAL *)
REAL orient4d_s (REAL *, REAL *, REAL *, REAL *, REAL *, REAL, REAL, REAL, REAL, REAL)
int tri_edge_2d (point, point, point, point, point, point, int, int *, int *)
int tri_edge_tail (point, point, point, point, point, point, REAL, REAL, int, int *, int *)
int tri_edge_test (point, point, point, point, point, point, int, int *, int *)
int tri_edge_inter_tail (point, point, point, point, point, REAL, REAL)
int tri_tri_inter (point, point, point, point, point, point)
REAL dot (REAL *v1, REAL *v2)
void cross (REAL *v1, REAL *v2, REAL *n)
bool lu_decmp (REAL lu[4][4], int n, int *ps, REAL *d, int N)
void lu_solve (REAL lu[4][4], int n, int *ps, REAL *b, int N)
REAL incircle3d (point pa, point pb, point pc, point pd)
REAL orient3dfast (REAL *pa, REAL *pb, REAL *pc, REAL *pd)
REAL norm2 (REAL x, REAL y, REAL z)
REAL distance (REAL *p1, REAL *p2)
void facenormal (point pa, point pb, point pc, REAL *n, int pivot, REAL *lav)
REAL shortdistance (REAL *p, REAL *e1, REAL *e2)
REAL triarea (REAL *pa, REAL *pb, REAL *pc)
REAL interiorangle (REAL *o, REAL *p1, REAL *p2, REAL *n)
void projpt2edge (REAL *p, REAL *e1, REAL *e2, REAL *prj)
void projpt2face (REAL *p, REAL *f1, REAL *f2, REAL *f3, REAL *prj)
REAL facedihedral (REAL *pa, REAL *pb, REAL *pc1, REAL *pc2)
bool tetalldihedral (point, point, point, point, REAL *, REAL *, REAL *)
void tetallnormal (point, point, point, point, REAL N[4][3], REAL *volume)
REAL tetaspectratio (point, point, point, point)
bool circumsphere (REAL *, REAL *, REAL *, REAL *, REAL *cent, REAL *radius)
bool orthosphere (REAL *, REAL *, REAL *, REAL *, REAL, REAL, REAL, REAL, REAL *, REAL *)
void planelineint (REAL *, REAL *, REAL *, REAL *, REAL *, REAL *, REAL *)
int linelineint (REAL *, REAL *, REAL *, REAL *, REAL *, REAL *, REAL *, REAL *)
REAL tetprismvol (REAL *pa, REAL *pb, REAL *pc, REAL *pd)
bool calculateabovepoint (arraypool *, point *, point *, point *)
void calculateabovepoint4 (point, point, point, point)
void flip23 (triface *, int, flipconstraints *fc)
void flip32 (triface *, int, flipconstraints *fc)
void flip41 (triface *, int, flipconstraints *fc)
int flipnm (triface *, int n, int level, int, flipconstraints *fc)
int flipnm_post (triface *, int n, int nn, int, flipconstraints *fc)
int insertpoint (point, triface *, face *, face *, insertvertexflags *)
void insertpoint_abort (face *, insertvertexflags *)
void transfernodes ()
void hilbert_init (int n)
int hilbert_split (point *vertexarray, int arraysize, int gc0, int gc1, REAL, REAL, REAL, REAL, REAL, REAL)
void hilbert_sort3 (point *vertexarray, int arraysize, int e, int d, REAL, REAL, REAL, REAL, REAL, REAL, int depth)
void brio_multiscale_sort (point *, int, int threshold, REAL ratio, int *depth)
unsigned long randomnation (unsigned int choices)
void randomsample (point searchpt, triface *searchtet)
enum locateresult locate (point searchpt, triface *searchtet)
void flippush (badface *&, triface *)
int incrementalflip (point newpt, int, flipconstraints *fc)
void initialdelaunay (point pa, point pb, point pc, point pd)
void incrementaldelaunay (clock_t &)
void flipshpush (face *)
void flip22 (face *, int, int)
void flip31 (face *, int)
long lawsonflip ()
int sinsertvertex (point newpt, face *, face *, int iloc, int bowywat, int)
int sremovevertex (point delpt, face *, face *, int lawson)
enum locateresult slocate (point, face *, int, int, int)
enum interresult sscoutsegment (face *, point)
void scarveholes (int, REAL *)
void triangulate (int, arraypool *, arraypool *, int, REAL *)
void unifysubfaces (face *, face *)
void unifysegments ()
void mergefacets ()
void identifypscedges (point *)
void meshsurface ()
void interecursive (shellface **subfacearray, int arraysize, int axis, REAL, REAL, REAL, REAL, REAL, REAL, int *internum)
void detectinterfaces ()
void makesegmentendpointsmap ()
enum interresult finddirection (triface *searchtet, point endpt)
enum interresult scoutsegment (point, point, triface *, point *, arraypool *)
int getsteinerptonsegment (face *seg, point refpt, point steinpt)
void delaunizesegments ()
enum interresult scoutsubface (face *searchsh, triface *searchtet)
void formregion (face *, arraypool *, arraypool *, arraypool *)
int scoutcrossedge (triface &crosstet, arraypool *, arraypool *)
bool formcavity (triface *, arraypool *, arraypool *, arraypool *, arraypool *, arraypool *, arraypool *)
void delaunizecavity (arraypool *, arraypool *, arraypool *, arraypool *, arraypool *, arraypool *)
bool fillcavity (arraypool *, arraypool *, arraypool *, arraypool *, arraypool *, arraypool *, triface *crossedge)
void carvecavity (arraypool *, arraypool *, arraypool *)
void restorecavity (arraypool *, arraypool *, arraypool *, arraypool *)
void flipcertify (triface *chkface, badface **pqueue, point, point, point)
void flipinsertfacet (arraypool *, arraypool *, arraypool *, arraypool *)
bool fillregion (arraypool *missingshs, arraypool *, arraypool *newshs)
int insertpoint_cdt (point, triface *, face *, face *, insertvertexflags *, arraypool *, arraypool *, arraypool *, arraypool *, arraypool *, arraypool *)
void refineregion (face &, arraypool *, arraypool *, arraypool *, arraypool *, arraypool *, arraypool *)
void constrainedfacets ()
void constraineddelaunay (clock_t &)
int checkflipeligibility (int fliptype, point, point, point, point, point, int level, int edgepivot, flipconstraints *fc)
int removeedgebyflips (triface *, flipconstraints *)
int removefacebyflips (triface *, flipconstraints *)
int recoveredgebyflips (point, point, triface *, int fullsearch)
int add_steinerpt_in_schoenhardtpoly (triface *, int, int chkencflag)
int add_steinerpt_in_segment (face *, int searchlevel)
int addsteiner4recoversegment (face *, int)
int recoversegments (arraypool *, int fullsearch, int steinerflag)
int recoverfacebyflips (point, point, point, face *, triface *)
int recoversubfaces (arraypool *, int steinerflag)
int getvertexstar (int, point searchpt, arraypool *, arraypool *, arraypool *)
int getedge (point, point, triface *)
int reduceedgesatvertex (point startpt, arraypool *endptlist)
int removevertexbyflips (point steinerpt)
int suppressbdrysteinerpoint (point steinerpt)
int suppresssteinerpoints ()
void recoverboundary (clock_t &)
void carveholes ()
void reconstructmesh ()
int scoutpoint (point, triface *, int randflag)
REAL getpointmeshsize (point, triface *, int iloc)
void interpolatemeshsize ()
void insertconstrainedpoints (point *insertarray, int arylen, int rejflag)
void insertconstrainedpoints (tetgenio *addio)
void collectremovepoints (arraypool *remptlist)
void meshcoarsening ()
void makefacetverticesmap ()
int segsegadjacent (face *, face *)
int segfacetadjacent (face *checkseg, face *checksh)
int facetfacetadjacent (face *, face *)
int checkseg4encroach (point pa, point pb, point checkpt)
int checkseg4split (face *chkseg, point &, int &)
int splitsegment (face *splitseg, point encpt, REAL, point, point, int, int)
void repairencsegs (int chkencflag)
void enqueuesubface (memorypool *, face *)
int checkfac4encroach (point, point, point, point checkpt, REAL *, REAL *)
int checkfac4split (face *chkfac, point &encpt, int &qflag, REAL *ccent)
int splitsubface (face *splitfac, point, point, int qflag, REAL *ccent, int)
void repairencfacs (int chkencflag)
void enqueuetetrahedron (triface *)
int checktet4split (triface *chktet, int &qflag, REAL *ccent)
int splittetrahedron (triface *splittet, int qflag, REAL *ccent, int)
void repairbadtets (int chkencflag)
void delaunayrefinement ()
long lawsonflip3d (flipconstraints *fc)
void recoverdelaunay ()
int gettetrahedron (point, point, point, point, triface *)
long improvequalitybyflips ()
int smoothpoint (point smtpt, arraypool *, int ccw, optparameters *opm)
long improvequalitybysmoothing (optparameters *opm)
int splitsliver (triface *, REAL, int)
long removeslivers (int)
void optimizemesh ()
int checkmesh (int topoflag)
int checkshells ()
int checksegments ()
int checkdelaunay ()
int checkregular (int)
int checkconforming (int)
void printfcomma (unsigned long n)
void qualitystatistics ()
void memorystatistics ()
void statistics ()
void jettisonnodes ()
void highorder ()
void numberedges ()
void outnodes (tetgenio *)
void outmetrics (tetgenio *)
void outelements (tetgenio *)
void outfaces (tetgenio *)
void outhullfaces (tetgenio *)
void outsubfaces (tetgenio *)
void outedges (tetgenio *)
void outsubsegments (tetgenio *)
void outneighbors (tetgenio *)
void outvoronoi (tetgenio *)
void outsmesh (char *)
void outmesh2medit (char *)
void outmesh2vtk (char *)
tetgenmesh ()
void freememory ()
~tetgenmesh ()
Public Attributes
tetgenio * in
tetgenio * addin
tetgenbehavior * b
tetgenmesh * bgm
memorypool * tetrahedrons
memorypool * subfaces
memorypool * subsegs
memorypool * points
memorypool * tet2subpool
memorypool * tet2segpool
memorypool * badtetrahedrons
memorypool * badsubfacs
memorypool * badsubsegs
memorypool * flippool
arraypool * unflipqueue
badface * flipstack
arraypool * cavetetlist
arraypool * cavebdrylist
arraypool * caveoldtetlist
arraypool * cavetetshlist
arraypool * cavetetseglist
arraypool * cavetetvertlist
arraypool * caveencshlist
arraypool * caveencseglist
arraypool * caveshlist
arraypool * caveshbdlist
arraypool * cavesegshlist
arraypool * subsegstack
arraypool * subfacstack
arraypool * subvertstack
arraypool * encseglist
arraypool * encshlist
int * idx2facetlist
point * facetverticeslist
point * segmentendpointslist
point dummypoint
triface recenttet
face recentsh
point * highordertable
int numpointattrib
int numelemattrib
int sizeoftensor
int pointmtrindex
int pointparamindex
int point2simindex
int pointmarkindex
int elemattribindex
int volumeboundindex
int elemmarkerindex
int shmarkindex
int areaboundindex
int checksubsegflag
int checksubfaceflag
int checkconstraints
int nonconvex
int autofliplinklevel
int useinsertradius
long samples
unsigned long randomseed
REAL cosmaxdihed
REAL cosmindihed
REAL cossmtdihed
REAL cosslidihed
REAL minfaceang
REAL minfacetdihed
REAL tetprism_vol_sum
REAL longest
REAL xmax
REAL xmin
REAL ymax
REAL ymin
REAL zmax
REAL zmin
long insegments
long hullsize
long meshedges
long meshhulledges
long steinerleft
long dupverts
long unuverts
long nonregularcount
long st_segref_count
long st_facref_count
long st_volref_count
long fillregioncount
long cavitycount
long cavityexpcount
long flip14count
long flip26count
long flipn2ncount
long flip23count
long flip32count
long flip44count
long flip41count
long flip31count
long flip22count
unsigned long totalworkmemory
int transgc [8][3][8]
int tsb1mod3 [8]
Static Public Attributes
static REAL PI = 3.14159265358979323846264338327950288419716939937510582
static int bondtbl [12][12] = {{0,},}
static int fsymtbl [12][12] = {{0,},}
static int esymtbl [12] = {9, 6, 11, 4, 3, 7, 1, 5, 10, 0, 8, 2}
static int enexttbl [12] = {0,}
static int eprevtbl [12] = {0,}
static int enextesymtbl [12] = {0,}
static int eprevesymtbl [12] = {0,}
static int eorgoppotbl [12] = {0,}
static int edestoppotbl [12] = {0,}
static int facepivot1 [12] = {0,}
static int facepivot2 [12][12] = {{0,},}
static int orgpivot [12] = {7, 7, 5, 5, 6, 4, 4, 6, 5, 6, 7, 4}
static int destpivot [12] = {6, 4, 4, 6, 5, 6, 7, 4, 7, 7, 5, 5}
static int apexpivot [12] = {5, 6, 7, 4, 7, 7, 5, 5, 6, 4, 4, 6}
static int oppopivot [12] = {4, 5, 6, 7, 4, 5, 6, 7, 4, 5, 6, 7}
static int tsbondtbl [12][6] = {{0,},}
static int stbondtbl [12][6] = {{0,},}
static int tspivottbl [12][6] = {{0,},}
static int stpivottbl [12][6] = {{0,},}
static int ver2edge [12] = {0, 1, 2, 3, 3, 5, 1, 5, 4, 0, 4, 2}
static int edge2ver [6] = {0, 1, 2, 3, 8, 5}
static int epivot [12] = {4, 5, 2, 11, 4, 5, 2, 11, 4, 5, 2, 11}
static int sorgpivot [6] = {3, 4, 4, 5, 5, 3}
static int sdestpivot [6] = {4, 3, 5, 4, 3, 5}
static int sapexpivot [6] = {5, 5, 3, 3, 4, 4}
static int snextpivot [6] = {2, 5, 4, 1, 0, 3}
Detailed Description
Definition at line 815 of file tetgen.h.
View newest version in sPHENIX GitHub at line 815 of file tetgen.h
Member Typedef Documentation
typedef REAL* tetgenmesh::point
Definition at line 889 of file tetgen.h.
View newest version in sPHENIX GitHub at line 889 of file tetgen.h
typedef REAL** tetgenmesh::shellface
Definition at line 872 of file tetgen.h.
View newest version in sPHENIX GitHub at line 872 of file tetgen.h
typedef REAL** tetgenmesh::tetrahedron
Definition at line 861 of file tetgen.h.
View newest version in sPHENIX GitHub at line 861 of file tetgen.h
Member Enumeration Documentation
enum tetgenmesh::interresult
Enumerator:
DISJOINT
INTERSECT
SHAREVERT
SHAREEDGE
SHAREFACE
TOUCHEDGE
TOUCHFACE
ACROSSVERT
ACROSSEDGE
ACROSSFACE
COLLISIONFACE
ACROSSSEG
ACROSSSUB
Definition at line 1240 of file tetgen.h.
View newest version in sPHENIX GitHub at line 1240 of file tetgen.h
enum tetgenmesh::locateresult
Enumerator:
UNKNOWN
OUTSIDE
INTETRAHEDRON
ONFACE
ONEDGE
ONVERTEX
ENCVERTEX
ENCSEGMENT
ENCSUBFACE
NEARVERTEX
NONREGULAR
INSTAR
BADELEMENT
Definition at line 1245 of file tetgen.h.
View newest version in sPHENIX GitHub at line 1245 of file tetgen.h
enum tetgenmesh::verttype
Enumerator:
UNUSEDVERTEX
DUPLICATEDVERTEX
RIDGEVERTEX
ACUTEVERTEX
FACETVERTEX
VOLVERTEX
FREESEGVERTEX
FREEFACETVERTEX
FREEVOLVERTEX
NREGULARVERTEX
DEADVERTEX
Definition at line 1235 of file tetgen.h.
View newest version in sPHENIX GitHub at line 1235 of file tetgen.h
Constructor & Destructor Documentation
tetgenmesh::tetgenmesh () inline
Definition at line 2076 of file tetgen.h.
View newest version in sPHENIX GitHub at line 2076 of file tetgen.h
References addin, areaboundindex, autofliplinklevel, b, badsubfacs, badsubsegs, badtetrahedrons, bgm, cavebdrylist, caveencseglist, caveencshlist, caveoldtetlist, cavesegshlist, caveshbdlist, caveshlist, cavetetlist, cavetetseglist, cavetetshlist, cavetetvertlist, cavitycount, cavityexpcount, checkconstraints, checksubfaceflag, checksubsegflag, dummypoint, dupverts, elemattribindex, encseglist, encshlist, facetverticeslist, fillregioncount, flip14count, flip22count, flip23count, flip26count, flip31count, flip32count, flip41count, flip44count, flipn2ncount, flippool, flipstack, highordertable, hullsize, idx2facetlist, in, insegments, longest, meshedges, meshhulledges, minfaceang, minfacetdihed, nonconvex, nonregularcount, numelemattrib, numpointattrib, PI, point2simindex, pointmarkindex, pointmtrindex, pointparamindex, points, randomseed, samples, segmentendpointslist, shmarkindex, sizeoftensor, st_facref_count, st_segref_count, st_volref_count, steinerleft, subfaces, subfacstack, subsegs, subsegstack, subvertstack, tet2segpool, tet2subpool, tetprism_vol_sum, tetrahedrons, totalworkmemory, unflipqueue, unuverts, useinsertradius, volumeboundindex, xmax, xmin, ymax, ymin, zmax, and zmin.
Referenced by tetrahedralize().
tetgenmesh::~tetgenmesh () inline
Definition at line 2211 of file tetgen.h.
View newest version in sPHENIX GitHub at line 2211 of file tetgen.h
Member Function Documentation
int tetgenmesh::add_steinerpt_in_schoenhardtpoly (triface * abtets, int n, int chkencflag)
Definition at line 18897 of file tetgen.cxx.
View newest version in sPHENIX GitHub at line 18897 of file tetgen.cxx
References apex(), tetgenmesh::insertvertexflags::assignmeshsize, b, caveoldtetlist, cavetetlist, tetgenmesh::insertvertexflags::chkencflag, dest(), dummypoint, edestoppo(), eorgoppo(), fastlookup, FREEVOLVERTEX, tetgenmesh::insertvertexflags::iloc, tetgenmesh::optparameters::imprval, infect(), tetgenmesh::optparameters::initval, insertpoint(), INSTAR, it, locate(), makepoint(), maketetrahedron(), tetgenmesh::optparameters::max_min_volume, tetgenmesh::optparameters::maxiter, tetgenbehavior::metric, n, charm_jet_strange_helicity::N, tetgenmesh::arraypool::newindex(), tetgenmesh::optparameters::numofsearchdirs, tetgenmesh::arraypool::objects, oppo(), org(), orient3d(), charm_jet_strange_helicity::pc, pointdealloc(), REAL, tetgenmesh::arraypool::restart(), tetgenmesh::optparameters::searchstep, setvertices, smoothpoint(), tetgenmesh::optparameters::smthiter, st_volref_count, steinerleft, tetgenmesh::triface::tet, and tetrahedrondealloc().
Referenced by addsteiner4recoversegment().
int tetgenmesh::add_steinerpt_in_segment (face * misseg, int searchlevel)
Definition at line 19052 of file tetgen.cxx.
View newest version in sPHENIX GitHub at line 19052 of file tetgen.cxx
References ACROSSEDGE, ACROSSFACE, tetgenbehavior::addsteiner_algo, tetgenmesh::insertvertexflags::assignmeshsize, b, tetgenmesh::insertvertexflags::bowywat, caveencseglist, tetgenmesh::flipconstraints::checkflipeligibility, tetgenmesh::insertvertexflags::chkencflag, tetgenmesh::flipconstraints::collectencsegflag, distance(), Acts::UnitConstants::e, enextesymself(), tetgenbehavior::epsilon, fastlookup, finddirection(), tetgenbehavior::fliplinklevel, FREESEGVERTEX, FREEVOLVERTEX, tetgenmesh::insertvertexflags::iloc, insertpoint(), tetgenmesh::insertvertexflags::lawson, linelineint(), makepoint(), tetgenbehavior::metric, tetgenmesh::arraypool::newindex(), tetgenmesh::arraypool::objects, ONEDGE, OUTSIDE, charm_jet_strange_helicity::pc, point2tetorg(), pointdealloc(), REAL, tetgenmesh::insertvertexflags::rejflag, removeedgebyflips(), removefacebyflips(), tetgenmesh::insertvertexflags::respectbdflag, tetgenmesh::arraypool::restart(), tetgenmesh::insertvertexflags::sbowywat, sdest(), tetgenmesh::flipconstraints::seg, tetgenmesh::face::sh, tetgenmesh::insertvertexflags::sloc, sorg(), spivot(), tetgenmesh::insertvertexflags::splitbdflag, st_segref_count, st_volref_count, steinerleft, subsegstack, subvertstack, suninfect(), terminatetetgen(), and tetgenmesh::insertvertexflags::validflag.
Referenced by addsteiner4recoversegment().
int tetgenmesh::addsteiner4recoversegment (face * misseg, int splitsegflag)
Definition at line 19226 of file tetgen.cxx.
View newest version in sPHENIX GitHub at line 19226 of file tetgen.cxx
References ACROSSEDGE, ACROSSFACE, add_steinerpt_in_schoenhardtpoly(), add_steinerpt_in_segment(), tetgenbehavior::addsteiner_algo, apex(), tetgenmesh::insertvertexflags::assignmeshsize, b, tetgenmesh::insertvertexflags::bowywat, tetgenmesh::insertvertexflags::chkencflag, dest(), enextself(), eprevself(), esymself(), farsdest(), farsorg(), finddirection(), fnextself(), FREESEGVERTEX, fsym(), tetgenmesh::insertvertexflags::iloc, insertpoint(), issubseg, tetgenmesh::insertvertexflags::lawson, makepoint(), tetgenbehavior::metric, n, tetgenmesh::arraypool::newindex(), ONEDGE, oppo(), org(), OUTSIDE, point2tetorg(), pointmark(), pointtype(), printf(), tetgenmesh::insertvertexflags::rejflag, tetgenmesh::insertvertexflags::respectbdflag, tetgenmesh::insertvertexflags::sbowywat, sdest(), sesymself(), shellmark(), tetgenmesh::insertvertexflags::sloc, sorg(), spivot(), tetgenmesh::insertvertexflags::splitbdflag, st_segref_count, steinerleft, subsegstack, subvertstack, terminatetetgen(), tetgenmesh::triface::tet, tri_edge_test(), tsspivot1(), tetgenmesh::insertvertexflags::validflag, and tetgenbehavior::verbose.
Referenced by recoversegments().
tetgenmesh::tetrahedron * tetgenmesh::alltetrahedrontraverse ()
Definition at line 4335 of file tetgen.cxx.
View newest version in sPHENIX GitHub at line 4335 of file tetgen.cxx
References tetrahedrons, and tetgenmesh::memorypool::traverse().
Referenced by carveholes(), checkmesh(), outhullfaces(), and outvoronoi().
tetgenmesh::point tetgenmesh::apex (triface & t) inline
Definition at line 2447 of file tetgen.h.
View newest version in sPHENIX GitHub at line 2447 of file tetgen.h
References apexpivot, and t.
Referenced by add_steinerpt_in_schoenhardtpoly(), addsteiner4recoversegment(), carveholes(), checkconforming(), checkdelaunay(), checkmesh(), checkregular(), checkseg4split(), checksegments(), checkshells(), delaunizecavity(), fillcavity(), fillregion(), finddirection(), flip23(), flip32(), flip41(), flipcertify(), flipinsertfacet(), flipnm(), formcavity(), getedge(), getpointmeshsize(), gettetrahedron(), getvertexstar(), incrementalflip(), insertpoint(), lawsonflip3d(), locate(), outfaces(), outmesh2medit(), outsubfaces(), outvoronoi(), qualitystatistics(), reconstructmesh(), recoveredgebyflips(), recoverfacebyflips(), removefacebyflips(), removevertexbyflips(), scoutcrossedge(), scoutpoint(), scoutsegment(), scoutsubface(), smoothpoint(), and suppressbdrysteinerpoint().
REAL tetgenmesh::areabound (face & s) inline
Definition at line 2787 of file tetgen.h.
View newest version in sPHENIX GitHub at line 2787 of file tetgen.h
References areaboundindex, REAL, and tetgenmesh::face::sh.
Referenced by checkfac4split(), checkseg4split(), fillcavity(), fillregion(), flip31(), sinsertvertex(), splitsegment(), splitsubface(), and sremovevertex().
void tetgenmesh::bond (triface & t1, triface & t2) inline
Definition at line 2314 of file tetgen.h.
View newest version in sPHENIX GitHub at line 2314 of file tetgen.h
References bondtbl, encode2(), tetgenmesh::triface::tet, and tetgenmesh::triface::ver.
Referenced by carveholes(), fillcavity(), flip23(), flip32(), flip41(), initialdelaunay(), insertpoint(), reconstructmesh(), restorecavity(), and suppressbdrysteinerpoint().
void tetgenmesh::brio_multiscale_sort (point * vertexarray, int arraysize, int threshold, REAL ratio, int * depth)
Definition at line 10833 of file tetgen.cxx.
View newest version in sPHENIX GitHub at line 10833 of file tetgen.cxx
References hilbert_sort3(), ratio, xmax, xmin, ymax, ymin, zmax, and zmin.
Referenced by incrementaldelaunay(), and insertconstrainedpoints().
bool tetgenmesh::calculateabovepoint (arraypool * facpoints, point * ppa, point * ppb, point * ppc)
Definition at line 6929 of file tetgen.cxx.
View newest version in sPHENIX GitHub at line 6929 of file tetgen.cxx
References b, cross(), dot(), dummypoint, facenormal(), fastlookup, n, tetgenmesh::arraypool::objects, charm_jet_strange_helicity::pc, pointmark(), printf(), tetgenbehavior::quiet, REAL, v1, v2, x, y, and z.
Referenced by flipinsertfacet(), and triangulate().
void tetgenmesh::calculateabovepoint4 (point pa, point pb, point pc, point pd)
Definition at line 7019 of file tetgen.cxx.
View newest version in sPHENIX GitHub at line 7019 of file tetgen.cxx
References distance(), dot(), dummypoint, facenormal(), and REAL.
Referenced by slocate(), splitsubface(), and sremovevertex().
void tetgenmesh::carvecavity (arraypool * crosstets, arraypool * topnewtets, arraypool * botnewtets)
Definition at line 16512 of file tetgen.cxx.
View newest version in sPHENIX GitHub at line 16512 of file tetgen.cxx
References b, caveencseglist, caveencshlist, cavetetseglist, cavetetshlist, decode(), fastlookup, fnextself(), fsym(), hullsize, infect(), infected(), ishulltet(), marktested(), tetgenmesh::arraypool::newindex(), tetgenmesh::arraypool::objects, printf(), recenttet, tetgenmesh::arraypool::restart(), sdecode(), sesymself(), tetgenmesh::face::sh, sinfect(), sinfected(), sstbond1(), sstdissolve1(), sstpivot1(), stdissolve(), stpivot(), suninfect(), tetgenmesh::triface::tet, tetrahedrondealloc(), tsbond(), tssbond1(), uninfect(), unmarktest(), and tetgenbehavior::verbose.
Referenced by constrainedfacets(), and insertpoint_cdt().
void tetgenmesh::carveholes ()
Definition at line 21924 of file tetgen.cxx.
View newest version in sPHENIX GitHub at line 21924 of file tetgen.cxx
References alltetrahedrontraverse(), apex(), b, bond(), cavetetvertlist, tetgenbehavior::convex, decode(), dest(), dummypoint, DUPLICATEDVERTEX, enextself(), tetgenmesh::flipconstraints::enqflag, eprevself(), esym(), esymself(), fastlookup, tetgenio::firstnumber, flippush(), flipstack, fnextself(), FREEFACETVERTEX, FREESEGVERTEX, FREEVOLVERTEX, fsym(), fsymself(), tetgenio::holelist, hullsize, in, infect(), infected(), ishulltet(), issubface, issubseg, k, lawsonflip3d(), locate(), maketetrahedron(), tetgenmesh::arraypool::newindex(), tetgenbehavior::nobisect, tetgenbehavior::nobisect_param, nonconvex, tetgenio::numberofholes, tetgenio::numberofpoints, tetgenio::numberofregions, numelemattrib, tetgenmesh::arraypool::objects, org(), OUTSIDE, charm_jet_strange_helicity::pc, point2tet(), pointmark(), points, pointtraverse(), pointtype(), printf(), tetgenbehavior::quiet, randomsample(), REAL, tetgenbehavior::regionattrib, tetgenio::regionlist, tetgenmesh::arraypool::restart(), sapex(), sbond1(), sdest(), sdissolve(), senextself(), sesymself(), setelemattribute(), setpoint2tet(), setpointtype(), setvertices, setvolumebound(), tetgenmesh::face::sh, shellfacedealloc(), sinfect(), sinfected(), sorg(), spivot(), ssbond(), sspivot(), sstbond1(), st_facref_count, st_segref_count, st_volref_count, steinerleft, subfaces, subfacstack, subsegs, subvertstack, suninfect(), tetgenmesh::triface::tet, tetrahedrondealloc(), tetrahedrons, tetrahedrontraverse(), tetgenmesh::memorypool::traversalinit(), tsbond(), tspivot(), tssbond1(), tsspivot1(), unflipqueue, uninfect(), UNUSEDVERTEX, unuverts, tetgenbehavior::varvolume, tetgenmesh::triface::ver, tetgenbehavior::verbose, and Acts::Test::volume.
Referenced by tetrahedralize().
int tetgenmesh::checkconforming (int flag)
Definition at line 27746 of file tetgen.cxx.
View newest version in sPHENIX GitHub at line 27746 of file tetgen.cxx
References apex(), b, cross(), distance(), dot(), dummypoint, epsilon, tetgenbehavior::epsilon, fnextself(), ishulltet(), lu_decmp(), lu_solve(), oppo(), charm_jet_strange_helicity::pc, pointmark(), printf(), tetgenbehavior::quiet, G4BECAL::radius, REAL, sesymself(), tetgenmesh::face::sh, shellfacetraverse(), sstpivot1(), stpivot(), subfaces, subsegs, tetgenmesh::triface::tet, and tetgenmesh::memorypool::traversalinit().
int tetgenmesh::checkdelaunay ()
Definition at line 27571 of file tetgen.cxx.
View newest version in sPHENIX GitHub at line 27571 of file tetgen.cxx
References apex(), b, checksubfaceflag, dest(), dummypoint, fsym(), insphere_s(), oppo(), org(), charm_jet_strange_helicity::pc, pointmark(), printf(), tetgenbehavior::quiet, REAL, tetgenmesh::face::sh, sign(), tetgenmesh::triface::tet, tetrahedrons, tetrahedrontraverse(), tetgenmesh::memorypool::traversalinit(), tspivot(), and tetgenmesh::triface::ver.
Referenced by tetrahedralize().
int tetgenmesh::checkfac4encroach (point pa, point pb, point pc, point checkpt, REAL * cent, REAL * r)
Definition at line 24491 of file tetgen.cxx.
View newest version in sPHENIX GitHub at line 24491 of file tetgen.cxx
References a2, a3, b, circumsphere(), distance(), dot(), tetgenbehavior::epsilon, facenormal(), tetgenbehavior::metric, n, pointmtrindex, projpt2face(), and REAL.
Referenced by insertpoint().
int tetgenmesh::checkfac4split (face * chkfac, point & encpt, int & qflag, REAL * ccent)
Definition at line 24557 of file tetgen.cxx.
View newest version in sPHENIX GitHub at line 24557 of file tetgen.cxx
References areabound(), b, checkconstraints, cross(), distance(), dot(), tetgenbehavior::epsilon, tetgenbehavior::fixedvolume, fsymself(), ishulltet(), lu_decmp(), lu_solve(), tetgenbehavior::maxvolume, tetgenbehavior::metric, oppo(), charm_jet_strange_helicity::pc, pointmtrindex, REAL, sapex(), sdest(), sesymself(), sorg(), stpivot(), tetgenmesh::triface::tet, tetgenbehavior::varvolume, and volumebound().
Referenced by repairencfacs().
int tetgenmesh::checkflipeligibility (int fliptype, point pa, point pb, point pc, point pd, point pe, int level, int edgepivot, flipconstraints * fc)
Definition at line 18261 of file tetgen.cxx.
View newest version in sPHENIX GitHub at line 18261 of file tetgen.cxx
References ACROSSEDGE, ACROSSFACE, b, tetgenmesh::flipconstraints::cosdihed_in, tetgenmesh::flipconstraints::cosdihed_out, dummypoint, tetgenbehavior::epsilon, tetgenmesh::flipconstraints::fac, charm_jet_strange_helicity::pc, REAL, tetgenmesh::flipconstraints::remove_large_angle, tetgenmesh::flipconstraints::remvert, tetgenmesh::flipconstraints::seg, tetalldihedral(), and tri_edge_test().
Referenced by flipnm().
int tetgenmesh::checkmesh (int topoflag)
Definition at line 26986 of file tetgen.cxx.
View newest version in sPHENIX GitHub at line 26986 of file tetgen.cxx
References alltetrahedrontraverse(), apex(), b, dest(), edge2ver, edgemarked(), facemarked(), fsym(), infected(), ishulltet(), marktested(), oppo(), org(), orient3d(), charm_jet_strange_helicity::pc, pointmark(), printf(), tetgenbehavior::quiet, REAL, tetgenmesh::triface::tet, tetrahedrons, tetgenmesh::memorypool::traversalinit(), and tetgenmesh::triface::ver.
Referenced by tetrahedralize().
int tetgenmesh::checkregular (int type)
Definition at line 27648 of file tetgen.cxx.
View newest version in sPHENIX GitHub at line 27648 of file tetgen.cxx
References apex(), b, checksubfaceflag, dest(), dummypoint, fsym(), insphere(), insphere_s(), oppo(), org(), orient4d(), orient4d_s(), p, pointmark(), printf(), tetgenbehavior::quiet, REAL, tetgenmesh::face::sh, sign(), tetgenmesh::triface::tet, tetrahedrons, tetrahedrontraverse(), tetgenmesh::memorypool::traversalinit(), tspivot(), and tetgenmesh::triface::ver.
int tetgenmesh::checkseg4encroach (point pa, point pb, point checkpt)
Definition at line 24116 of file tetgen.cxx.
View newest version in sPHENIX GitHub at line 24116 of file tetgen.cxx
References b, distance(), dot(), tetgenbehavior::metric, pointmtrindex, projpt2edge(), REAL, t, Acts::UnitConstants::u, v, v1, and v2.
Referenced by insertpoint().
int tetgenmesh::checkseg4split (face * chkseg, point & encpt, int & qflag)
Definition at line 24171 of file tetgen.cxx.
View newest version in sPHENIX GitHub at line 24171 of file tetgen.cxx
References apex(), areabound(), b, checkconstraints, d, distance(), dummypoint, epsilon, tetgenbehavior::fixedvolume, fnextself(), tetgenbehavior::maxvolume, tetgenbehavior::metric, pointmtrindex, REAL, sdest(), sorg(), sstpivot1(), tetgenmesh::triface::tet, and useinsertradius.
Referenced by repairencsegs().
int tetgenmesh::checksegments ()
Definition at line 27309 of file tetgen.cxx.
View newest version in sPHENIX GitHub at line 27309 of file tetgen.cxx
References apex(), b, dest(), edge2ver, edgemarked(), fnextself(), for(), FREESEGVERTEX, oppo(), org(), point2sh(), pointmark(), points, pointtraverse(), pointtype(), printf(), tetgenbehavior::quiet, sapex(), sdecode(), sdest(), senext(), senext2(), tetgenmesh::face::sh, shellfacetraverse(), tetgenmesh::face::shver, sorg(), spivot(), spivotself(), sstpivot1(), stpivot(), subsegs, tetgenmesh::triface::tet, tetrahedrons, tetrahedrontraverse(), tetgenmesh::memorypool::traversalinit(), tspivot(), tsspivot1(), and tetgenmesh::triface::ver.
Referenced by tetrahedralize().
int tetgenmesh::checkshells ()
Definition at line 27122 of file tetgen.cxx.
View newest version in sPHENIX GitHub at line 27122 of file tetgen.cxx
References tetgenmesh::memorypool::alignbytes, apex(), b, dest(), fsym(), oppo(), org(), tetgenmesh::memorypool::pathblock, tetgenmesh::memorypool::pathitem, tetgenmesh::memorypool::pathitemsleft, pointmark(), printf(), tetgenbehavior::quiet, sapex(), sdest(), senextself(), tetgenmesh::face::sh, shellfacetraverse(), tetgenmesh::face::shver, sinfected(), smarktested(), sorg(), spivot(), sspivot(), stpivot(), subfaces, tetgenmesh::triface::tet, tetgenmesh::memorypool::traversalinit(), and tspivot().
Referenced by tetrahedralize().
int tetgenmesh::checktet4split (triface * chktet, int & qflag, REAL * ccent)
Definition at line 24956 of file tetgen.cxx.
View newest version in sPHENIX GitHub at line 24956 of file tetgen.cxx
References b, tetgenbehavior::convex, cosmindihed, dest(), distance(), dot(), dummypoint, edge2ver, elemattribute(), tetgenbehavior::epsilon, tetgenbehavior::fixedvolume, for(), getpointinsradius(), in, Acts::IntegrationTest::L, lu_decmp(), lu_solve(), tetgenbehavior::maxvolume, tetgenbehavior::metric, tetgenbehavior::mindihedral, tetgenbehavior::minratio, charm_jet_strange_helicity::N, numelemattrib, org(), charm_jet_strange_helicity::pc, pointmtrindex, REAL, tetgenmesh::triface::tet, tetgenio::tetunsuitable, useinsertradius, tetgenbehavior::varvolume, tetgenmesh::triface::ver, and volumebound().
Referenced by repairbadtets().
bool tetgenmesh::circumsphere (REAL * pa, REAL * pb, REAL * pc, REAL * pd, REAL * cent, REAL * radius)
Definition at line 6678 of file tetgen.cxx.
View newest version in sPHENIX GitHub at line 6678 of file tetgen.cxx
References cross(), dot(), lu_decmp(), lu_solve(), and REAL.
Referenced by checkfac4encroach(), incircle3d(), and outvoronoi().
void tetgenmesh::collectremovepoints (arraypool * remptlist)
Definition at line 23700 of file tetgen.cxx.
View newest version in sPHENIX GitHub at line 23700 of file tetgen.cxx
References b, cavetetlist, cavetetvertlist, tetgenbehavior::coarsen_param, tetgenbehavior::coarsen_percent, distance(), fastlookup, FREEFACETVERTEX, FREESEGVERTEX, FREEVOLVERTEX, getvertexstar(), in, tetgenbehavior::metric, tetgenmesh::arraypool::newindex(), tetgenmesh::arraypool::objects, pinfect(), pinfected(), tetgenio::pointmarkerlist, pointmtrindex, points, pointtraverse(), pointtype(), printf(), puninfect(), rand, REAL, tetgenmesh::arraypool::restart(), srand, tetgenmesh::memorypool::traversalinit(), tetgenbehavior::verbose, and VOLVERTEX.
Referenced by meshcoarsening().
void tetgenmesh::constraineddelaunay (clock_t & tv)
Definition at line 18147 of file tetgen.cxx.
View newest version in sPHENIX GitHub at line 18147 of file tetgen.cxx
References b, cavitycount, cavityexpcount, checksubfaceflag, checksubsegflag, constrainedfacets(), delaunizesegments(), fastlookup, fillregioncount, tetgenmesh::memorypool::items, makesegmentendpointsmap(), tetgenmesh::arraypool::newindex(), printf(), tetgenbehavior::quiet, randomnation(), Acts::UnitConstants::s, tetgenmesh::face::sh, shellfacetraverse(), st_facref_count, st_segref_count, subfaces, subfacstack, subsegs, subsegstack, tetgenmesh::memorypool::traversalinit(), and tetgenbehavior::verbose.
Referenced by tetrahedralize().
void tetgenmesh::constrainedfacets ()
Definition at line 17912 of file tetgen.cxx.
View newest version in sPHENIX GitHub at line 17912 of file tetgen.cxx
References b, carvecavity(), caveencseglist, caveencshlist, delaunizecavity(), encseglist, fastlookup, fillcavity(), fillregion(), tetgenbehavior::flipinsert, flipinsertfacet(), fnextself(), formcavity(), formregion(), isshsubseg, isshtet, issubseg, tetgenmesh::arraypool::newindex(), tetgenmesh::arraypool::objects, printf(), punmarktest(), recentsh, refineregion(), tetgenmesh::arraypool::restart(), restorecavity(), scoutcrossedge(), scoutsegment(), scoutsubface(), sdest(), senextself(), tetgenmesh::face::sh, SHAREEDGE, SHAREFACE, smarktest(), smarktested(), sorg(), spivot(), sstbond1(), subfacstack, sunmarktest(), tetgenmesh::triface::tet, tetgenmesh::arraypool::totalmemory, totalworkmemory, tssbond1(), and tetgenbehavior::verbose.
Referenced by constraineddelaunay().
void tetgenmesh::cross (REAL * v1, REAL * v2, REAL * n) inline
Definition at line 3312 of file tetgen.h.
View newest version in sPHENIX GitHub at line 3312 of file tetgen.h
Referenced by calculateabovepoint(), checkconforming(), checkfac4split(), circumsphere(), facenormal(), incrementaldelaunay(), outvoronoi(), and triarea().
void tetgenmesh::decode (tetrahedron ptr, triface & t) inline
Definition at line 2306 of file tetgen.h.
View newest version in sPHENIX GitHub at line 2306 of file tetgen.h
References t.
Referenced by carvecavity(), carveholes(), delaunizecavity(), fillcavity(), finddirection(), fnext(), fsym(), insertpoint(), point2tetorg(), reconstructmesh(), recoverdelaunay(), sstpivot1(), and stpivot().
void tetgenmesh::decreaseelemcounter (triface & t) inline
Definition at line 2623 of file tetgen.h.
View newest version in sPHENIX GitHub at line 2623 of file tetgen.h
References c, elemcounter(), and setelemcounter().
Referenced by flipnm().
void tetgenmesh::delaunayrefinement ()
Definition at line 25387 of file tetgen.cxx.
View newest version in sPHENIX GitHub at line 25387 of file tetgen.cxx
References b, badsubfacs, badsubsegs, badtetrahedrons, checkconstraints, cos(), cosmindihed, encseglist, encshlist, enqueuesubface(), enqueuetetrahedron(), flip23count, flip32count, flip44count, tetgenmesh::memorypool::itembytes, tetgenmesh::memorypool::items, makefacetverticesmap(), makesegmentendpointsmap(), tetgenmesh::memorypool::maxitems, tetgenbehavior::mindihedral, tetgenbehavior::minratio, tetgenbehavior::nobisect, PI, tetgenbehavior::plc, points, printf(), tetgenbehavior::quiet, tetgenbehavior::refine, tetgenbehavior::reflevel, repairbadtets(), repairencfacs(), repairencsegs(), tetgenmesh::face::sh, tetgenbehavior::shellfaceperblock, shellfacetraverse(), st_facref_count, st_segref_count, st_volref_count, tetgenbehavior::steinerleft, steinerleft, subfaces, subsegs, tetgenmesh::triface::tet, tetgenbehavior::tetrahedraperblock, tetrahedrons, tetrahedrontraverse(), totalworkmemory, tetgenmesh::memorypool::traversalinit(), useinsertradius, and tetgenbehavior::verbose.
Referenced by tetrahedralize().
void tetgenmesh::delaunizecavity (arraypool * cavpoints, arraypool * cavfaces, arraypool * cavshells, arraypool * newtets, arraypool * crosstets, arraypool * misfaces)
Definition at line 15882 of file tetgen.cxx.
View newest version in sPHENIX GitHub at line 15882 of file tetgen.cxx
References apex(), b, tetgenmesh::insertvertexflags::bowywat, cavityexpcount, checksubfaceflag, checksubsegflag, decode(), dest(), dummypoint, encode(), enextself(), epivot, esym(), fastlookup, fsymself(), hullsize, tetgenmesh::insertvertexflags::iloc, infect(), infected(), initialdelaunay(), insertpoint(), makeshellface(), marktest(), marktested(), tetgenmesh::arraypool::newindex(), tetgenmesh::arraypool::objects, oppo(), org(), orient3d(), OUTSIDE, charm_jet_strange_helicity::pc, pinfect(), pinfected(), tetgenbehavior::plc, printf(), puninfect(), REAL, recenttet, tetgenmesh::arraypool::restart(), scoutsubface(), setshvertices, tetgenmesh::face::sh, SHAREFACE, shellfacedealloc(), stpivot(), subfaces, tetgenmesh::triface::tet, tsdissolve(), tetgenmesh::triface::ver, and tetgenbehavior::verbose.
Referenced by constrainedfacets(), and insertpoint_cdt().
void tetgenmesh::delaunizesegments ()
Definition at line 15193 of file tetgen.cxx.
View newest version in sPHENIX GitHub at line 15193 of file tetgen.cxx
References ACROSSEDGE, ACROSSFACE, tetgenmesh::insertvertexflags::assignmeshsize, b, tetgenmesh::insertvertexflags::bowywat, fastlookup, fnextself(), FREESEGVERTEX, getsteinerptonsegment(), tetgenmesh::insertvertexflags::iloc, insertpoint(), issubseg, makepoint(), tetgenbehavior::metric, NEARVERTEX, tetgenmesh::arraypool::objects, ONEDGE, OUTSIDE, tetgenmesh::insertvertexflags::sbowywat, scoutsegment(), sdest(), SHAREEDGE, tetgenmesh::insertvertexflags::sloc, sorg(), sstbond1(), sstpivot1(), st_segref_count, steinerleft, subsegstack, terminatetetgen(), tetgenmesh::triface::tet, and tssbond1().
Referenced by constraineddelaunay().
tetgenmesh::point tetgenmesh::dest (triface & t) inline
Definition at line 2443 of file tetgen.h.
View newest version in sPHENIX GitHub at line 2443 of file tetgen.h
References destpivot, and t.
Referenced by add_steinerpt_in_schoenhardtpoly(), addsteiner4recoversegment(), carveholes(), checkdelaunay(), checkmesh(), checkregular(), checksegments(), checkshells(), checktet4split(), delaunizecavity(), fillcavity(), fillregion(), finddirection(), flip23(), flip32(), flip41(), flipcertify(), flipinsertfacet(), flipnm(), formcavity(), formregion(), getedge(), getpointmeshsize(), highorder(), incrementalflip(), insertpoint(), lawsonflip3d(), locate(), outedges(), outfaces(), outmesh2medit(), outsubfaces(), outvoronoi(), qualitystatistics(), reconstructmesh(), recoveredgebyflips(), recoverfacebyflips(), recoversubfaces(), reduceedgesatvertex(), removefacebyflips(), removevertexbyflips(), scoutpoint(), scoutsegment(), scoutsubface(), smoothpoint(), splitsliver(), and suppressbdrysteinerpoint().
void tetgenmesh::detectinterfaces ()
Definition at line 14553 of file tetgen.cxx.
View newest version in sPHENIX GitHub at line 14553 of file tetgen.cxx
References b, interecursive(), tetgenmesh::memorypool::items, printf(), tetgenbehavior::quiet, tetgenmesh::memorypool::restart(), tetgenmesh::face::sh, shellfacedealloc(), shellfacetraverse(), sinfected(), subfaces, suninfect(), tetgenmesh::memorypool::traversalinit(), xmax, xmin, ymax, ymin, zmax, and zmin.
Referenced by tetrahedralize().
void tetgenmesh::dissolve (triface & t) inline
Definition at line 2322 of file tetgen.h.
View newest version in sPHENIX GitHub at line 2322 of file tetgen.h
References tetgenmesh::triface::tet, and tetgenmesh::triface::ver.
Referenced by suppressbdrysteinerpoint().
REAL tetgenmesh::distance (REAL * p1, REAL * p2) inline
Definition at line 3320 of file tetgen.h.
View newest version in sPHENIX GitHub at line 3320 of file tetgen.h
Referenced by add_steinerpt_in_segment(), calculateabovepoint4(), checkconforming(), checkfac4encroach(), checkfac4split(), checkseg4encroach(), checkseg4split(), checktet4split(), collectremovepoints(), getpointmeshsize(), getsteinerptonsegment(), incircle3d(), incrementaldelaunay(), insertpoint(), reconstructmesh(), splitsegment(), splitsubface(), splittetrahedron(), sscoutsegment(), suppressbdrysteinerpoint(), tri_edge_2d(), and triangulate().
REAL tetgenmesh::dot (REAL * v1, REAL * v2) inline
Definition at line 3306 of file tetgen.h.
View newest version in sPHENIX GitHub at line 3306 of file tetgen.h
Referenced by calculateabovepoint(), calculateabovepoint4(), checkconforming(), checkfac4encroach(), checkfac4split(), checkseg4encroach(), checktet4split(), circumsphere(), facedihedral(), facenormal(), incircle3d(), interiorangle(), linelineint(), lu_solve(), projpt2edge(), projpt2face(), pyqqbh(), qualitystatistics(), shortdistance(), slocate(), suppressbdrysteinerpoint(), tetalldihedral(), tetaspectratio(), tetprismvol(), tri_edge_2d(), triarea(), and unifysegments().
void tetgenmesh::edestoppo (triface & t1, triface & t2) inline
Definition at line 2398 of file tetgen.h.
View newest version in sPHENIX GitHub at line 2398 of file tetgen.h
References edestoppotbl, tetgenmesh::triface::tet, and tetgenmesh::triface::ver.
Referenced by add_steinerpt_in_schoenhardtpoly(), flip23(), flip32(), formcavity(), insertpoint(), lawsonflip3d(), recoverfacebyflips(), scoutcrossedge(), and splitsliver().
void tetgenmesh::edestoppoself (triface & t) inline
Definition at line 2403 of file tetgen.h.
View newest version in sPHENIX GitHub at line 2403 of file tetgen.h
References edestoppotbl, and tetgenmesh::triface::ver.
Referenced by flipnm().
bool tetgenmesh::edgemarked (triface & t) inline
Definition at line 2582 of file tetgen.h.
View newest version in sPHENIX GitHub at line 2582 of file tetgen.h
References elemmarkerindex, tetgenmesh::triface::tet, and ver2edge.
Referenced by checkmesh(), checksegments(), and formcavity().
REAL tetgenmesh::elemattribute (tetrahedron * ptr, int attnum) inline
Definition at line 2479 of file tetgen.h.
View newest version in sPHENIX GitHub at line 2479 of file tetgen.h
References elemattribindex, and REAL.
Referenced by checktet4split(), flip23(), flip32(), insertpoint(), optimizemesh(), outelements(), outmesh2medit(), outmesh2vtk(), qualitystatistics(), and reconstructmesh().
int tetgenmesh::elemcounter (triface & t) inline
Definition at line 2606 of file tetgen.h.
View newest version in sPHENIX GitHub at line 2606 of file tetgen.h
References elemmarkerindex, and tetgenmesh::triface::tet.
Referenced by decreaseelemcounter(), flipnm(), and increaseelemcounter().
int tetgenmesh::elemindex (tetrahedron * ptr) inline
Definition at line 2501 of file tetgen.h.
View newest version in sPHENIX GitHub at line 2501 of file tetgen.h
Referenced by numberedges(), outedges(), outfaces(), outmesh2medit(), outneighbors(), outsubfaces(), outsubsegments(), and outvoronoi().
int tetgenmesh::elemmarker (tetrahedron * ptr) inline
Definition at line 2514 of file tetgen.h.
View newest version in sPHENIX GitHub at line 2514 of file tetgen.h
References elemmarkerindex.
tetgenmesh::tetrahedron tetgenmesh::encode (triface & t) inline
Definition at line 2295 of file tetgen.h.
View newest version in sPHENIX GitHub at line 2295 of file tetgen.h
Referenced by delaunizecavity(), initialdelaunay(), insertpoint(), interpolatemeshsize(), outvoronoi(), reconstructmesh(), restorecavity(), sstbond1(), and suppressbdrysteinerpoint().
tetgenmesh::tetrahedron tetgenmesh::encode2 (tetrahedron * ptr, int ver) inline
Definition at line 2299 of file tetgen.h.
View newest version in sPHENIX GitHub at line 2299 of file tetgen.h
Referenced by bond(), and tsbond().
void tetgenmesh::enext (triface & t1, triface & t2) inline
Definition at line 2328 of file tetgen.h.
View newest version in sPHENIX GitHub at line 2328 of file tetgen.h
References enexttbl, tetgenmesh::triface::tet, and tetgenmesh::triface::ver.
Referenced by flip23(), flip32(), flip41(), flipnm(), formcavity(), incrementalflip(), outfaces(), reconstructmesh(), removefacebyflips(), and splitsliver().
void tetgenmesh::enextesym (triface & t1, triface & t2) inline
Definition at line 2363 of file tetgen.h.
View newest version in sPHENIX GitHub at line 2363 of file tetgen.h
References enextesymtbl, tetgenmesh::triface::tet, and tetgenmesh::triface::ver.
Referenced by flip23(), flip32(), flipinsertfacet(), initialdelaunay(), recoveredgebyflips(), and scoutsegment().
void tetgenmesh::enextesymself (triface & t) inline
Definition at line 2368 of file tetgen.h.
View newest version in sPHENIX GitHub at line 2368 of file tetgen.h
References enextesymtbl, and tetgenmesh::triface::ver.
Referenced by add_steinerpt_in_segment(), flipinsertfacet(), getedge(), getvertexstar(), locate(), recoveredgebyflips(), and scoutsegment().
void tetgenmesh::enextself (triface & t) inline
Definition at line 2333 of file tetgen.h.
View newest version in sPHENIX GitHub at line 2333 of file tetgen.h
References enexttbl, and tetgenmesh::triface::ver.
Referenced by addsteiner4recoversegment(), carveholes(), delaunizecavity(), fillcavity(), finddirection(), flip23(), flip32(), flip41(), flipinsertfacet(), flipnm(), flipnm_post(), getedge(), getvertexstar(), incrementalflip(), insertpoint(), lawsonflip3d(), locate(), outfaces(), outsubfaces(), outvoronoi(), reconstructmesh(), recoveredgebyflips(), removevertexbyflips(), scoutpoint(), scoutsegment(), scoutsubface(), and suppressbdrysteinerpoint().
void tetgenmesh::enqueuesubface (memorypool * pool, face * chkface)
Definition at line 24476 of file tetgen.cxx.
View newest version in sPHENIX GitHub at line 24476 of file tetgen.cxx
References tetgenmesh::memorypool::alloc(), smarktest2(), and smarktest2ed().
Referenced by delaunayrefinement(), flip22(), flip23(), flip32(), flip41(), and insertpoint().
void tetgenmesh::enqueuetetrahedron (triface * chktet)
Definition at line 24941 of file tetgen.cxx.
View newest version in sPHENIX GitHub at line 24941 of file tetgen.cxx
References tetgenmesh::memorypool::alloc(), badtetrahedrons, marktest2(), and marktest2ed().
Referenced by delaunayrefinement(), flip23(), flip32(), flip41(), insertpoint(), and splittetrahedron().
void tetgenmesh::eorgoppo (triface & t1, triface & t2) inline
Definition at line 2386 of file tetgen.h.
View newest version in sPHENIX GitHub at line 2386 of file tetgen.h
References eorgoppotbl, tetgenmesh::triface::tet, and tetgenmesh::triface::ver.
Referenced by add_steinerpt_in_schoenhardtpoly(), flip23(), flip32(), flipnm(), formcavity(), getedge(), insertpoint(), and lawsonflip3d().
void tetgenmesh::eorgoppoself (triface & t) inline
Definition at line 2391 of file tetgen.h.
View newest version in sPHENIX GitHub at line 2391 of file tetgen.h
References eorgoppotbl, and tetgenmesh::triface::ver.
Referenced by flipnm().
void tetgenmesh::eprev (triface & t1, triface & t2) inline
Definition at line 2339 of file tetgen.h.
View newest version in sPHENIX GitHub at line 2339 of file tetgen.h
References eprevtbl, tetgenmesh::triface::tet, and tetgenmesh::triface::ver.
Referenced by flip23(), flip32(), flip41(), flipnm(), formcavity(), incrementalflip(), reconstructmesh(), removefacebyflips(), removevertexbyflips(), and splitsliver().
void tetgenmesh::eprevesym (triface & t1, triface & t2) inline
Definition at line 2374 of file tetgen.h.
View newest version in sPHENIX GitHub at line 2374 of file tetgen.h
References eprevesymtbl, tetgenmesh::triface::tet, and tetgenmesh::triface::ver.
Referenced by flip23(), flip32(), flipinsertfacet(), initialdelaunay(), recoveredgebyflips(), and scoutsegment().
void tetgenmesh::eprevesymself (triface & t) inline
Definition at line 2379 of file tetgen.h.
View newest version in sPHENIX GitHub at line 2379 of file tetgen.h
References eprevesymtbl, and tetgenmesh::triface::ver.
Referenced by fillcavity(), finddirection(), flip23(), and locate().
void tetgenmesh::eprevself (triface & t) inline
Definition at line 2344 of file tetgen.h.
View newest version in sPHENIX GitHub at line 2344 of file tetgen.h
References eprevtbl, and tetgenmesh::triface::ver.
Referenced by addsteiner4recoversegment(), carveholes(), fillcavity(), finddirection(), flip23(), flip32(), flip41(), flipinsertfacet(), flipnm(), flipnm_post(), locate(), recoverfacebyflips(), removevertexbyflips(), and scoutpoint().
void tetgenmesh::esym (triface & t1, triface & t2) inline
Definition at line 2351 of file tetgen.h.
View newest version in sPHENIX GitHub at line 2351 of file tetgen.h
References esymtbl, and t2.
Referenced by carveholes(), delaunizecavity(), flip23(), flip32(), flip41(), flipinsertfacet(), flipnm(), flipnm_post(), getvertexstar(), incrementalflip(), initialdelaunay(), insertpoint(), outvoronoi(), reconstructmesh(), removevertexbyflips(), and suppressbdrysteinerpoint().
void tetgenmesh::esymself (triface & t) inline
Definition at line 2356 of file tetgen.h.
View newest version in sPHENIX GitHub at line 2356 of file tetgen.h
References esymtbl, and t.
Referenced by addsteiner4recoversegment(), carveholes(), fillcavity(), finddirection(), flip23(), flip32(), flip41(), flipnm(), flipnm_post(), formcavity(), getedge(), getvertexstar(), incrementalflip(), insertpoint(), lawsonflip3d(), locate(), reconstructmesh(), removevertexbyflips(), scoutcrossedge(), scoutpoint(), splitsliver(), and suppressbdrysteinerpoint().
REAL tetgenmesh::facedihedral (REAL * pa, REAL * pb, REAL * pc1, REAL * pc2)
Definition at line 6427 of file tetgen.cxx.
View newest version in sPHENIX GitHub at line 6427 of file tetgen.cxx
References dot(), facenormal(), orient3d(), PI, REAL, and theta().
Referenced by mergefacets(), and reconstructmesh().
bool tetgenmesh::facemarked (triface & t) inline
Definition at line 2565 of file tetgen.h.
View newest version in sPHENIX GitHub at line 2565 of file tetgen.h
References elemmarkerindex, tetgenmesh::triface::tet, and tetgenmesh::triface::ver.
Referenced by checkmesh(), fillcavity(), flippush(), incrementalflip(), lawsonflip3d(), and recoverdelaunay().
void tetgenmesh::facenormal (point pa, point pb, point pc, REAL * n, int pivot, REAL * lav)
Definition at line 6169 of file tetgen.cxx.
View newest version in sPHENIX GitHub at line 6169 of file tetgen.cxx
References cross(), dot(), REAL, v1, v2, and v3.
Referenced by calculateabovepoint(), calculateabovepoint4(), checkfac4encroach(), facedihedral(), incircle3d(), planelineint(), projpt2face(), qualitystatistics(), slocate(), suppressbdrysteinerpoint(), tetalldihedral(), tri_edge_2d(), and unifysegments().
int tetgenmesh::facetfacetadjacent (face * subsh1, face * subsh2)
Definition at line 24085 of file tetgen.cxx.
View newest version in sPHENIX GitHub at line 24085 of file tetgen.cxx
References facetverticeslist, getfacetindex(), idx2facetlist, pinfect(), pinfected(), and puninfect().
Referenced by splitsubface().
tetgenmesh::point tetgenmesh::farsdest (face & seg) inline
Definition at line 3284 of file tetgen.h.
View newest version in sPHENIX GitHub at line 3284 of file tetgen.h
References Acts::UnitConstants::s, sdest(), senext(), sesymself(), tetgenmesh::face::sh, and spivotself().
Referenced by addsteiner4recoversegment(), and recoverfacebyflips().
tetgenmesh::point tetgenmesh::farsorg (face & seg) inline
Definition at line 3269 of file tetgen.h.
View newest version in sPHENIX GitHub at line 3269 of file tetgen.h
References Acts::UnitConstants::s, senext2(), sesymself(), tetgenmesh::face::sh, sorg(), and spivotself().
Referenced by addsteiner4recoversegment(), and recoverfacebyflips().
bool tetgenmesh::fillcavity (arraypool * topshells, arraypool * botshells, arraypool * midfaces, arraypool * missingshs, arraypool * topnewtets, arraypool * botnewtets, triface * crossedge)
Definition at line 16113 of file tetgen.cxx.
View newest version in sPHENIX GitHub at line 16113 of file tetgen.cxx
References apex(), areabound(), b, bond(), checkconstraints, decode(), dest(), dummypoint, enextself(), eprevesymself(), eprevself(), esymself(), facemarked(), fastlookup, fnext(), fnextself(), fsym(), fsymself(), infect(), infected(), makeshellface(), markface(), marktested(), tetgenmesh::arraypool::newindex(), tetgenmesh::arraypool::objects, oppo(), org(), orient3d(), charm_jet_strange_helicity::pc, pmarktested(), printf(), randomnation(), REAL, recentsh, tetgenmesh::arraypool::restart(), sbond(), sbond1(), sdest(), sesymself(), setareabound(), setpoint2tet(), setsapex(), setsdest(), setshellmark(), setsorg(), tetgenmesh::face::sh, shellfacedealloc(), shellmark(), tetgenmesh::face::shver, sinfected(), sorg(), spivot(), ssbond(), ssdissolve(), stpivot(), subfaces, subsegs, tetgenmesh::triface::tet, tri_edge_test(), tsbond(), tsdissolve(), tspivot(), tssdissolve1(), tsspivot1(), unmarkface(), tetgenmesh::triface::ver, and tetgenbehavior::verbose.
Referenced by constrainedfacets(), and insertpoint_cdt().
bool tetgenmesh::fillregion (arraypool * missingshs, arraypool * missingshbds, arraypool * newshs)
Definition at line 17333 of file tetgen.cxx.
View newest version in sPHENIX GitHub at line 17333 of file tetgen.cxx
References tetgenmesh::memorypool::alloc(), apex(), areabound(), checkconstraints, tetgenmesh::memorypool::dealloc(), dest(), fastlookup, fillregioncount, flippool, flipstack, fnextself(), fsymself(), issubface, makeshellface(), tetgenmesh::arraypool::newindex(), tetgenmesh::badface::nextitem, tetgenmesh::arraypool::objects, org(), charm_jet_strange_helicity::pc, pmarktested(), randomnation(), recentsh, tetgenmesh::arraypool::restart(), tetgenmesh::memorypool::restart(), sbond(), sbond1(), senextself(), sesymself(), setareabound(), setsapex(), setsdest(), setshellmark(), setsorg(), tetgenmesh::face::sh, shellfacedealloc(), shellmark(), tetgenmesh::face::shver, sinfect(), sinfected(), sorg(), spivot(), tetgenmesh::badface::ss, ssbond(), ssdissolve(), sspivot(), sstpivot1(), stpivot(), subfaces, subsegs, suninfect(), tetgenmesh::triface::tet, tsbond(), tspivot(), tssdissolve1(), and tsspivot1().
Referenced by constrainedfacets().
enum tetgenmesh::interresult tetgenmesh::finddirection (triface * searchtet, point endpt)
Definition at line 14711 of file tetgen.cxx.
View newest version in sPHENIX GitHub at line 14711 of file tetgen.cxx
References ACROSSEDGE, ACROSSFACE, ACROSSSUB, ACROSSVERT, apex(), decode(), dest(), dummypoint, enextself(), eprevesymself(), eprevself(), esymself(), fnextself(), fsymself(), nonconvex, oppo(), org(), orient3d(), charm_jet_strange_helicity::pc, randomnation(), REAL, Acts::UnitConstants::s, tetgenmesh::triface::tet, and tetgenmesh::triface::ver.
Referenced by add_steinerpt_in_segment(), addsteiner4recoversegment(), formregion(), getedge(), insertpoint(), recoveredgebyflips(), recoverfacebyflips(), recoversubfaces(), reduceedgesatvertex(), removevertexbyflips(), scoutsegment(), and scoutsubface().
void tetgenmesh::flip22 (face * flipfaces, int flipflag, int chkencflag)
Definition at line 11786 of file tetgen.cxx.
View newest version in sPHENIX GitHub at line 11786 of file tetgen.cxx
References badsubfacs, badsubsegs, enqueuesubface(), flip22count, flipshpush(), FREEFACETVERTEX, isshsubseg, outfaces(), charm_jet_strange_helicity::pc, pointtype(), recentsh, sapex(), sbond1(), sdest(), sdissolve(), sencode(), senext(), senext2(), sesymself(), setpoint2sh(), setshvertices, tetgenmesh::face::sh, sorg(), spivot(), ssbond(), ssdissolve(), and sspivot().
Referenced by flip32(), lawsonflip(), sremovevertex(), and sscoutsegment().
void tetgenmesh::flip23 (triface * fliptets, int hullflag, flipconstraints * fc)
Definition at line 7079 of file tetgen.cxx.
View newest version in sPHENIX GitHub at line 7079 of file tetgen.cxx
References apex(), b, badsubfacs, badsubsegs, bond(), checksubfaceflag, checksubsegflag, tetgenmesh::flipconstraints::chkencflag, tetgenmesh::memorypool::dealloc(), dest(), dummypoint, edestoppo(), elemattribute(), enext(), enextesym(), enextself(), tetgenmesh::flipconstraints::enqflag, enqueuesubface(), enqueuetetrahedron(), eorgoppo(), eprev(), eprevesym(), eprevesymself(), eprevself(), esym(), esymself(), flip23count, flippush(), flipstack, fnext(), hullsize, issubface, issubseg, maketetrahedron(), numelemattrib, oppo(), org(), charm_jet_strange_helicity::pc, REAL, recenttet, tetgenmesh::flipconstraints::remove_ndelaunay_edge, sesymself(), setelemattribute(), setelemmarker(), setpoint2tet(), setvertices, setvolumebound(), sstbond1(), tetgenmesh::triface::tet, tet2segpool, tet2subpool, tetgenmesh::flipconstraints::tetprism_vol_sum, tetprismvol(), tsbond(), tspivot(), tssbond1(), tsspivot1(), tetgenbehavior::varvolume, tetgenmesh::triface::ver, Acts::Test::volume, and volumebound().
Referenced by flipinsertfacet(), flipnm(), flipnm_post(), incrementalflip(), lawsonflip3d(), removefacebyflips(), and removevertexbyflips().
void tetgenmesh::flip31 (face * flipfaces, int flipflag)
Definition at line 11908 of file tetgen.cxx.
View newest version in sPHENIX GitHub at line 11908 of file tetgen.cxx
References areabound(), checkconstraints, flip31count, flipshpush(), FREEFACETVERTEX, getfacetindex(), isshsubseg, makeshellface(), outfaces(), charm_jet_strange_helicity::pc, pointtype(), recentsh, sbond1(), sdest(), sencode(), senext(), senext2(), sesymself(), setareabound(), setfacetindex(), setpoint2sh(), setshellmark(), setshvertices, tetgenmesh::face::sh, shellmark(), tetgenmesh::face::shver, sorg(), spivot(), ssbond(), sspivot(), subfaces, and useinsertradius.
Referenced by flip41(), and sremovevertex().
void tetgenmesh::flip32 (triface * fliptets, int hullflag, flipconstraints * fc)
Definition at line 7418 of file tetgen.cxx.
View newest version in sPHENIX GitHub at line 7418 of file tetgen.cxx
References apex(), b, badsubfacs, badsubsegs, bond(), checksubfaceflag, checksubsegflag, tetgenmesh::flipconstraints::chkencflag, tetgenmesh::memorypool::dealloc(), dest(), dummypoint, edestoppo(), elemattribute(), enext(), enextesym(), enextself(), tetgenmesh::flipconstraints::enqflag, enqueuesubface(), enqueuetetrahedron(), eorgoppo(), eprev(), eprevesym(), eprevself(), esym(), esymself(), flip22(), flip32count, flippush(), flipstack, fsym(), fsymself(), hullsize, issubface, issubseg, numelemattrib, org(), charm_jet_strange_helicity::pc, REAL, recenttet, tetgenmesh::flipconstraints::remove_ndelaunay_edge, sesymself(), setelemattribute(), setelemmarker(), setpoint2tet(), setvertices, setvolumebound(), tetgenmesh::face::sh, spivot(), sstbond1(), stdissolve(), terminatetetgen(), tetgenmesh::triface::tet, tet2segpool, tet2subpool, tetgenmesh::flipconstraints::tetprism_vol_sum, tetprismvol(), tetrahedrondealloc(), tsbond(), tspivot(), tssbond1(), tsspivot1(), tetgenbehavior::varvolume, tetgenmesh::triface::ver, Acts::Test::volume, and volumebound().
Referenced by flipinsertfacet(), flipnm(), flipnm_post(), incrementalflip(), lawsonflip3d(), and removevertexbyflips().
void tetgenmesh::flip41 (triface * fliptets, int hullflag, flipconstraints * fc)
Definition at line 7820 of file tetgen.cxx.
View newest version in sPHENIX GitHub at line 7820 of file tetgen.cxx
References apex(), badsubfacs, badsubsegs, bond(), checksubfaceflag, checksubsegflag, tetgenmesh::flipconstraints::chkencflag, tetgenmesh::memorypool::dealloc(), dest(), dummypoint, enext(), enextself(), tetgenmesh::flipconstraints::enqflag, enqueuesubface(), enqueuetetrahedron(), eprev(), eprevself(), esym(), esymself(), flip31(), flip41count, flippush(), flipstack, fnext(), fnextself(), fsym(), hullsize, issubface, issubseg, org(), charm_jet_strange_helicity::pc, REAL, recenttet, tetgenmesh::flipconstraints::remove_ndelaunay_edge, senext2self(), sesym(), sesymself(), setelemmarker(), setpoint2tet(), setpointtype(), setvertices, shellfacedealloc(), spivot(), sstbond1(), subfaces, tetgenmesh::triface::tet, tet2segpool, tet2subpool, tetgenmesh::flipconstraints::tetprism_vol_sum, tetprismvol(), tetrahedrondealloc(), tsbond(), tspivot(), tssbond1(), tsspivot1(), UNUSEDVERTEX, unuverts, and tetgenmesh::triface::ver.
Referenced by removevertexbyflips().
void tetgenmesh::flipcertify (triface * chkface, badface ** pqueue, point plane_pa, point plane_pb, point plane_pc)
Definition at line 16809 of file tetgen.cxx.
View newest version in sPHENIX GitHub at line 16809 of file tetgen.cxx
References tetgenmesh::memorypool::alloc(), apex(), b, dest(), dummypoint, tetgenmesh::badface::fapex, tetgenmesh::badface::fdest, flippool, tetgenmesh::badface::foppo, tetgenmesh::badface::forg, fsym(), insphere(), insphere_s(), tetgenmesh::badface::key, tetgenmesh::badface::nextitem, tetgenmesh::badface::noppo, oppo(), org(), orient3dfast(), orient4d(), p, pmarktest2ed(), pmarktest3ed(), pointmark(), printf(), REAL, tetgenmesh::face::sh, tspivot(), tetgenmesh::badface::tt, and tetgenbehavior::verbose.
Referenced by flipinsertfacet().
void tetgenmesh::flipinsertfacet (arraypool * crosstets, arraypool * toppoints, arraypool * botpoints, arraypool * midpoints)
Definition at line 16974 of file tetgen.cxx.
View newest version in sPHENIX GitHub at line 16974 of file tetgen.cxx
References apex(), b, calculateabovepoint(), cavetetlist, tetgenmesh::memorypool::dealloc(), dest(), enextesym(), enextesymself(), enextself(), eprevesym(), eprevself(), esym(), tetgenmesh::badface::fapex, fastlookup, tetgenmesh::badface::fdest, flip23(), flip23count, flip32(), flip32count, flip44count, flipcertify(), flippool, fnext(), tetgenmesh::badface::foppo, tetgenmesh::badface::forg, fsym(), infected(), isdeadtet(), tetgenmesh::memorypool::items, tetgenmesh::badface::key, marktest(), marktested(), n, tetgenmesh::arraypool::newindex(), tetgenmesh::badface::nextitem, tetgenmesh::badface::noppo, tetgenmesh::arraypool::objects, oppo(), org(), orient3d(), pmarktest2(), pmarktest2ed(), pmarktest3(), pmarktest3ed(), pmarktested(), pointmark(), printf(), punmarktest2(), punmarktest3(), REAL, tetgenmesh::arraypool::restart(), tetgenmesh::face::sh, tetgenmesh::triface::tet, tspivot(), tsspivot1(), tetgenmesh::badface::tt, uninfect(), unmarktest(), tetgenmesh::triface::ver, and tetgenbehavior::verbose.
Referenced by constrainedfacets().
int tetgenmesh::flipnm (triface * abtets, int n, int level, int abedgepivot, flipconstraints * fc)
Definition at line 8141 of file tetgen.cxx.
View newest version in sPHENIX GitHub at line 8141 of file tetgen.cxx
References apex(), autofliplinklevel, b, tetgenmesh::flipconstraints::bak_tetprism_vol, caveencseglist, cavetetlist, tetgenmesh::flipconstraints::checkflipeligibility, checkflipeligibility(), checksubfaceflag, checksubsegflag, tetgenmesh::flipconstraints::collectencsegflag, tetgenmesh::flipconstraints::collectnewtets, decreaseelemcounter(), dest(), dummypoint, edestoppoself(), elemcounter(), enext(), enextself(), eorgoppo(), eorgoppoself(), eprev(), eprevself(), esym(), esymself(), flip23(), flip32(), tetgenbehavior::fliplinklevel, flipnm_post(), tetgenbehavior::flipstarsize, fnext(), fnextself(), fsym(), getedge(), increaseelemcounter(), issubface, issubseg, n, tetgenmesh::arraypool::newindex(), nonconvex, tetgenmesh::arraypool::objects, oppo(), org(), orient3d(), charm_jet_strange_helicity::pc, REAL, tetgenmesh::flipconstraints::remove_ndelaunay_edge, sinfect(), sinfected(), tetgenmesh::triface::tet, tetgenmesh::flipconstraints::tetprism_vol_sum, tsspivot1(), tetgenmesh::flipconstraints::unflip, and tetgenmesh::triface::ver.
Referenced by removeedgebyflips().
int tetgenmesh::flipnm_post (triface * abtets, int n, int nn, int abedgepivot, flipconstraints * fc)
Definition at line 8822 of file tetgen.cxx.
View newest version in sPHENIX GitHub at line 8822 of file tetgen.cxx
References b, cavetetlist, tetgenmesh::flipconstraints::collectnewtets, enextself(), eprevself(), esym(), esymself(), flip23(), flip32(), fnext(), fsym(), n, tetgenmesh::arraypool::objects, printf(), t, tetgenmesh::flipconstraints::unflip, tetgenmesh::triface::ver, and tetgenbehavior::verbose.
Referenced by flipnm(), and removeedgebyflips().
void tetgenmesh::flippush (badface *& fstack, triface * flipface)
Definition at line 11192 of file tetgen.cxx.
View newest version in sPHENIX GitHub at line 11192 of file tetgen.cxx
References tetgenmesh::memorypool::alloc(), facemarked(), flippool, markface(), tetgenmesh::badface::nextitem, and tetgenmesh::badface::tt.
Referenced by carveholes(), flip23(), flip32(), flip41(), insertpoint(), lawsonflip3d(), and recoverdelaunay().
void tetgenmesh::flipshpush (face * flipedge)
Definition at line 11764 of file tetgen.cxx.
View newest version in sPHENIX GitHub at line 11764 of file tetgen.cxx
References tetgenmesh::memorypool::alloc(), tetgenmesh::badface::fdest, flippool, flipstack, tetgenmesh::badface::forg, tetgenmesh::badface::nextitem, sdest(), sorg(), and tetgenmesh::badface::ss.
Referenced by flip22(), flip31(), mergefacets(), and sscoutsegment().
void tetgenmesh::fnext (triface & t1, triface & t2) inline
Definition at line 2424 of file tetgen.h.
View newest version in sPHENIX GitHub at line 2424 of file tetgen.h
References decode(), facepivot1, facepivot2, tetgenmesh::triface::tet, and tetgenmesh::triface::ver.
Referenced by fillcavity(), flip23(), flip41(), flipinsertfacet(), flipnm(), flipnm_post(), getedge(), incrementalflip(), lawsonflip3d(), numberedges(), outedges(), outvoronoi(), and removevertexbyflips().
void tetgenmesh::fnextself (triface & t) inline
Referenced by addsteiner4recoversegment(), carvecavity(), carveholes(), checkconforming(), checkseg4split(), checksegments(), constrainedfacets(), delaunizesegments(), fillcavity(), fillregion(), finddirection(), flip41(), flipnm(), formcavity(), formregion(), gettetrahedron(), highorder(), incrementalflip(), insertconstrainedpoints(), insertpoint(), numberedges(), outedges(), outsubsegments(), outvoronoi(), reconstructmesh(), recoveredgebyflips(), recoverfacebyflips(), recoversegments(), recoversubfaces(), refineregion(), removeedgebyflips(), removevertexbyflips(), restorecavity(), scoutcrossedge(), scoutsegment(), scoutsubface(), splitsliver(), and suppressbdrysteinerpoint().
bool tetgenmesh::formcavity (triface * searchtet, arraypool * missingshs, arraypool * crosstets, arraypool * topfaces, arraypool * botfaces, arraypool * toppoints, arraypool * botpoints)
Definition at line 15571 of file tetgen.cxx.
View newest version in sPHENIX GitHub at line 15571 of file tetgen.cxx
References ACROSSEDGE, ACROSSFACE, apex(), b, cavitycount, dest(), dummypoint, edestoppo(), edgemarked(), enext(), eorgoppo(), eprev(), esymself(), fastlookup, fnextself(), fsym(), infect(), infected(), issubseg, k, markedge(), tetgenmesh::arraypool::newindex(), tetgenmesh::arraypool::objects, org(), pinfect(), pinfected(), pmarktested(), pointmark(), printf(), puninfect(), tetgenbehavior::quiet, randomnation(), recentsh, recenttet, tetgenmesh::arraypool::restart(), sapex(), sdest(), sorg(), terminatetetgen(), tetgenmesh::triface::tet, tri_edge_test(), uninfect(), unmarkedge(), and tetgenbehavior::verbose.
Referenced by constrainedfacets().
void tetgenmesh::formregion (face * missh, arraypool * missingshs, arraypool * missingshbds, arraypool * missingshverts)
Definition at line 15365 of file tetgen.cxx.
View newest version in sPHENIX GitHub at line 15365 of file tetgen.cxx
References ACROSSVERT, dest(), fastlookup, finddirection(), fnextself(), makeshellface(), tetgenmesh::arraypool::newindex(), tetgenmesh::arraypool::objects, pmarktest(), pmarktested(), point2tetorg(), sdest(), senextself(), sesymself(), setsdest(), setsorg(), tetgenmesh::face::sh, sinfect(), smarktest(), smarktested(), sorg(), spivot(), ssbond(), sspivot(), sstbond1(), subsegs, sunmarktest(), terminatetetgen(), tetgenmesh::triface::tet, and tssbond1().
Referenced by constrainedfacets().
void tetgenmesh::freememory () inline
Definition at line 2144 of file tetgen.h.
View newest version in sPHENIX GitHub at line 2144 of file tetgen.h
References bgm, cavebdrylist, caveencseglist, caveencshlist, caveoldtetlist, cavesegshlist, caveshbdlist, caveshlist, cavetetlist, cavetetseglist, cavetetshlist, cavetetvertlist, dummypoint, facetverticeslist, flippool, highordertable, idx2facetlist, points, segmentendpointslist, subfaces, subfacstack, subsegs, subsegstack, subvertstack, tet2segpool, tet2subpool, tetrahedrons, and unflipqueue.
Referenced by terminatetetgen().
void tetgenmesh::fsym (triface & t1, triface & t2) inline
Definition at line 2409 of file tetgen.h.
View newest version in sPHENIX GitHub at line 2409 of file tetgen.h
References decode(), fsymtbl, and tetgenmesh::triface::ver.
Referenced by addsteiner4recoversegment(), carvecavity(), carveholes(), checkdelaunay(), checkmesh(), checkregular(), checkshells(), fillcavity(), flip32(), flip41(), flipcertify(), flipinsertfacet(), flipnm(), flipnm_post(), formcavity(), incrementalflip(), insertpoint(), lawsonflip3d(), outfaces(), outmesh2medit(), outneighbors(), outvoronoi(), qualitystatistics(), reconstructmesh(), removefacebyflips(), removevertexbyflips(), restorecavity(), scoutsegment(), and suppressbdrysteinerpoint().
void tetgenmesh::fsymself (triface & t) inline
Referenced by carveholes(), checkfac4split(), delaunizecavity(), fillcavity(), fillregion(), finddirection(), flip32(), gettetrahedron(), getvertexstar(), insertpoint(), insertpoint_cdt(), lawsonflip3d(), locate(), outsubfaces(), reconstructmesh(), recoveredgebyflips(), recoversubfaces(), removevertexbyflips(), scoutpoint(), scoutsegment(), and scoutsubface().
int tetgenmesh::getedge (point e1, point e2, triface * tedge)
Definition at line 20135 of file tetgen.cxx.
View newest version in sPHENIX GitHub at line 20135 of file tetgen.cxx
References apex(), b, cavebdrylist, dest(), enextesymself(), enextself(), eorgoppo(), esymself(), fastlookup, finddirection(), fnext(), infect(), infected(), isdeadtet(), tetgenmesh::arraypool::newindex(), tetgenmesh::arraypool::objects, org(), point2tetorg(), pointmark(), printf(), tetgenmesh::arraypool::restart(), uninfect(), and tetgenbehavior::verbose.
Referenced by flipnm(), gettetrahedron(), reconstructmesh(), recoverdelaunay(), reduceedgesatvertex(), and removevertexbyflips().
int tetgenmesh::getfacetindex (face & f) inline
Definition at line 2902 of file tetgen.h.
View newest version in sPHENIX GitHub at line 2902 of file tetgen.h
References tetgenmesh::face::sh, and shmarkindex.
Referenced by facetfacetadjacent(), flip31(), getsteinerptonsegment(), segfacetadjacent(), segsegadjacent(), sinsertvertex(), and sremovevertex().
REAL tetgenmesh::getpointinsradius (point pt) inline
Definition at line 3229 of file tetgen.h.
View newest version in sPHENIX GitHub at line 3229 of file tetgen.h
References pointmtrindex, and sizeoftensor.
Referenced by checktet4split(), splitsegment(), and splitsubface().
REAL tetgenmesh::getpointmeshsize (point searchpt, triface * searchtet, int iloc)
Definition at line 23321 of file tetgen.cxx.
View newest version in sPHENIX GitHub at line 23321 of file tetgen.cxx
References apex(), dest(), distance(), dummypoint, INTETRAHEDRON, ONEDGE, ONFACE, ONVERTEX, org(), orient3dfast(), charm_jet_strange_helicity::pc, pointmtrindex, REAL, tetgenmesh::triface::tet, triarea(), and Acts::Test::volume.
Referenced by insertpoint(), and interpolatemeshsize().
int tetgenmesh::getsteinerptonsegment (face * seg, point refpt, point steinpt)
Definition at line 15110 of file tetgen.cxx.
View newest version in sPHENIX GitHub at line 15110 of file tetgen.cxx
References distance(), ei(), FREESEGVERTEX, getfacetindex(), Acts::IntegrationTest::L, point2sh(), pointtype(), projpt2edge(), REAL, sdecode(), sdest(), segmentendpointslist, sorg(), and t.
Referenced by delaunizesegments(), refineregion(), and splitsegment().
int tetgenmesh::gettetrahedron (point pa, point pb, point pc, point pd, triface * searchtet)
Definition at line 26012 of file tetgen.cxx.
View newest version in sPHENIX GitHub at line 26012 of file tetgen.cxx
References apex(), fnextself(), fsymself(), getedge(), oppo(), and tetgenmesh::triface::tet.
Referenced by improvequalitybyflips(), improvequalitybysmoothing(), and removeslivers().
int tetgenmesh::getvertexstar (int fullstar, point searchpt, arraypool * tetlist, arraypool * vertlist, arraypool * shlist)
Definition at line 19993 of file tetgen.cxx.
View newest version in sPHENIX GitHub at line 19993 of file tetgen.cxx
References apex(), enextesymself(), enextself(), esym(), esymself(), fastlookup, fsymself(), infect(), infected(), issubface, tetgenmesh::arraypool::newindex(), tetgenmesh::arraypool::objects, pinfect(), pinfected(), point2tetorg(), puninfect(), sinfected(), suninfect(), tetgenmesh::triface::tet, tspivot(), uninfect(), and tetgenmesh::triface::ver.
Referenced by collectremovepoints(), improvequalitybysmoothing(), outvoronoi(), removevertexbyflips(), suppressbdrysteinerpoint(), and suppresssteinerpoints().
void tetgenmesh::highorder ()
Definition at line 28530 of file tetgen.cxx.
View newest version in sPHENIX GitHub at line 28530 of file tetgen.cxx
References b, tetgenmesh::memorypool::deaditemstack, dest(), edge2ver, fnextself(), for(), FREEVOLVERTEX, highordertable, in, ishulltet(), tetgenmesh::memorypool::items, makepoint(), tetgenio::numberofpointmtrs, numpointattrib, org(), pointmtrindex, points, printf(), tetgenbehavior::quiet, terminatetetgen(), tetgenmesh::triface::tet, tetrahedrons, tetrahedrontraverse(), tetgenmesh::memorypool::traversalinit(), tetgenmesh::triface::ver, and ver2edge.
Referenced by tetrahedralize().
void tetgenmesh::hilbert_init (int n)
Definition at line 10611 of file tetgen.cxx.
View newest version in sPHENIX GitHub at line 10611 of file tetgen.cxx
References c, d, Acts::UnitConstants::e, g(), k, n, charm_jet_strange_helicity::N, transgc, tsb1mod3, and v.
Referenced by incrementaldelaunay(), and insertconstrainedpoints().
void tetgenmesh::hilbert_sort3 (point * vertexarray, int arraysize, int e, int d, REAL bxmin, REAL bxmax, REAL bymin, REAL bymax, REAL bzmin, REAL bzmax, int depth)
Definition at line 10733 of file tetgen.cxx.
View newest version in sPHENIX GitHub at line 10733 of file tetgen.cxx
References b, ei(), tetgenbehavior::hilbert_limit, tetgenbehavior::hilbert_order, hilbert_split(), k, n, p, REAL, transgc, tsb1mod3, x2, z1, and z2.
Referenced by brio_multiscale_sort().
int tetgenmesh::hilbert_split (point * vertexarray, int arraysize, int gc0, int gc1, REAL bxmin, REAL bxmax, REAL bymin, REAL bymax, REAL bzmin, REAL bzmax)
Definition at line 10662 of file tetgen.cxx.
View newest version in sPHENIX GitHub at line 10662 of file tetgen.cxx
References d, and REAL.
Referenced by hilbert_sort3().
void tetgenmesh::identifypscedges (point * idx2verlist)
Definition at line 14002 of file tetgen.cxx.
View newest version in sPHENIX GitHub at line 14002 of file tetgen.cxx
References b, tetgenio::edgelist, tetgenio::edgemarkerlist, tetgenio::firstnumber, FREESEGVERTEX, in, makepoint2submap(), makeshellface(), tetgenio::numberofedges, tetgenio::numberofsegmentconstraints, pointmark(), points, pointtraverse(), pointtype(), printf(), tetgenbehavior::psc, tetgenbehavior::quality, tetgenbehavior::quiet, REAL, sapex(), sbond(), sdest(), tetgenio::segmentconstraintlist, sencode(), senext2(), senextself(), sesymself(), setareabound(), setpoint2sh(), setshellmark(), setshvertices, tetgenmesh::face::sh, shellfacedealloc(), shellfacetraverse(), shellmark(), sorg(), spivot(), ssbond(), sspivot(), subfaces, subsegs, and tetgenmesh::memorypool::traversalinit().
Referenced by meshsurface().
long tetgenmesh::improvequalitybyflips ()
Definition at line 26049 of file tetgen.cxx.
View newest version in sPHENIX GitHub at line 26049 of file tetgen.cxx
References autofliplinklevel, b, cavetetlist, tetgenmesh::badface::cent, tetgenmesh::flipconstraints::checkflipeligibility, tetgenmesh::flipconstraints::collectnewtets, tetgenmesh::flipconstraints::cosdihed_in, tetgenmesh::flipconstraints::cosdihed_out, cosmaxdihed, dummypoint, edge2ver, tetgenmesh::badface::fapex, fastlookup, tetgenmesh::badface::fdest, tetgenbehavior::fliplinklevel, tetgenbehavior::fliplinklevelinc, tetgenbehavior::flipstarsize, tetgenmesh::badface::foppo, tetgenmesh::badface::forg, gettetrahedron(), isdeadtet(), k, tetgenmesh::badface::key, n, tetgenmesh::arraypool::newindex(), tetgenmesh::arraypool::objects, tetgenbehavior::optlevel, printf(), REAL, tetgenmesh::flipconstraints::remove_large_angle, removeedgebyflips(), tetgenmesh::arraypool::restart(), tetgenmesh::triface::tet, tetalldihedral(), tetgenmesh::badface::tt, tetgenmesh::flipconstraints::unflip, unflipqueue, tetgenmesh::triface::ver, and tetgenbehavior::verbose.
Referenced by optimizemesh().
long tetgenmesh::improvequalitybysmoothing (optparameters * opm)
Definition at line 26401 of file tetgen.cxx.
View newest version in sPHENIX GitHub at line 26401 of file tetgen.cxx
References b, cavetetlist, tetgenmesh::badface::cent, cossmtdihed, tetgenmesh::badface::fapex, fastlookup, tetgenmesh::badface::fdest, tetgenmesh::badface::foppo, tetgenmesh::badface::forg, FREEVOLVERTEX, gettetrahedron(), getvertexstar(), tetgenmesh::optparameters::imprval, tetgenmesh::optparameters::initval, isdeadtet(), k, tetgenmesh::badface::key, marktest(), marktested(), tetgenmesh::optparameters::maxiter, tetgenmesh::arraypool::newindex(), tetgenmesh::arraypool::objects, pointtype(), printf(), tetgenmesh::arraypool::restart(), tetgenmesh::optparameters::searchstep, smoothpoint(), tetgenmesh::optparameters::smthiter, tetgenmesh::triface::tet, tetalldihedral(), tetgenmesh::badface::tt, unflipqueue, unmarktest(), tetgenmesh::triface::ver, and tetgenbehavior::verbose.
Referenced by optimizemesh().
REAL tetgenmesh::incircle3d (point pa, point pb, point pc, point pd)
Definition at line 6118 of file tetgen.cxx.
View newest version in sPHENIX GitHub at line 6118 of file tetgen.cxx
References c, circumsphere(), d, distance(), dot(), epsilon, facenormal(), REAL, and sign().
Referenced by insertpoint(), lawsonflip(), and sinsertvertex().
void tetgenmesh::increaseelemcounter (triface & t) inline
Definition at line 2618 of file tetgen.h.
View newest version in sPHENIX GitHub at line 2618 of file tetgen.h
References c, elemcounter(), and setelemcounter().
Referenced by flipnm().
void tetgenmesh::incrementaldelaunay (clock_t & tv)
Definition at line 11545 of file tetgen.cxx.
View newest version in sPHENIX GitHub at line 11545 of file tetgen.cxx
References b, tetgenmesh::insertvertexflags::bowywat, tetgenbehavior::brio_hilbert, brio_multiscale_sort(), tetgenbehavior::brio_ratio, tetgenbehavior::brio_threshold, cross(), distance(), DUPLICATEDVERTEX, dupverts, tetgenmesh::flipconstraints::enqflag, tetgenbehavior::epsilon, flipstack, hilbert_init(), tetgenmesh::insertvertexflags::iloc, in, incrementalflip(), tetgenbehavior::incrflip, initialdelaunay(), insertpoint(), tetgenmesh::insertvertexflags::lawson, tetgenio::mesh_dim, tetgenbehavior::minedgelength, n, NEARVERTEX, tetgenbehavior::no_sort, norm2(), tetgenio::numberofpoints, tetgenbehavior::object, ONVERTEX, org(), orient3dfast(), OUTSIDE, point2ppt(), pointmark(), points, pointtype(), printf(), tetgenbehavior::quiet, rand, REAL, recenttet, setpoint2ppt(), setpointtype(), srand, tetgenbehavior::STL, terminatetetgen(), tetgenmesh::triface::tet, tetgenmesh::memorypool::traversalinit(), tetgenmesh::memorypool::traverse(), UNUSEDVERTEX, v1, v2, tetgenbehavior::verbose, VOLVERTEX, xmax, xmin, ymax, ymin, zmax, and zmin.
Referenced by tetrahedralize().
int tetgenmesh::incrementalflip (point newpt, int hullflag, flipconstraints * fc)
Definition at line 11223 of file tetgen.cxx.
View newest version in sPHENIX GitHub at line 11223 of file tetgen.cxx
References apex(), b, cavebdrylist, cavetetvertlist, tetgenmesh::memorypool::dealloc(), dest(), dummypoint, enext(), enextself(), epivot, eprev(), esym(), esymself(), facemarked(), fastlookup, flip23(), flip32(), flippool, flipstack, fnext(), fnextself(), for(), fsym(), insphere_s(), isdeadtet(), tetgenmesh::memorypool::items, marktest(), marktested(), tetgenmesh::arraypool::newindex(), tetgenmesh::badface::nextitem, tetgenmesh::arraypool::objects, oppo(), org(), orient3d(), orient4d_s(), pinfect(), pinfected(), printf(), puninfect(), REAL, tetgenmesh::arraypool::restart(), sign(), terminatetetgen(), tetgenmesh::triface::tet, tetgenmesh::badface::tt, unmarkface(), unmarktest(), tetgenmesh::triface::ver, tetgenbehavior::verbose, and tetgenbehavior::weighted.
Referenced by incrementaldelaunay().
void tetgenmesh::infect (triface & t) inline
Definition at line 2526 of file tetgen.h.
View newest version in sPHENIX GitHub at line 2526 of file tetgen.h
References elemmarkerindex, and tetgenmesh::triface::tet.
Referenced by add_steinerpt_in_schoenhardtpoly(), carvecavity(), carveholes(), delaunizecavity(), fillcavity(), formcavity(), getedge(), getvertexstar(), insertpoint(), and splitsliver().
bool tetgenmesh::infected (triface & t) inline
Definition at line 2534 of file tetgen.h.
View newest version in sPHENIX GitHub at line 2534 of file tetgen.h
References elemmarkerindex, and tetgenmesh::triface::tet.
Referenced by carvecavity(), carveholes(), checkmesh(), delaunizecavity(), fillcavity(), flipinsertfacet(), formcavity(), getedge(), getvertexstar(), insertpoint(), insertpoint_cdt(), and restorecavity().
void tetgenmesh::initialdelaunay (point pa, point pb, point pc, point pd)
Definition at line 11461 of file tetgen.cxx.
View newest version in sPHENIX GitHub at line 11461 of file tetgen.cxx
References b, bond(), dummypoint, encode(), enextesym(), eprevesym(), esym(), hullsize, maketetrahedron(), pointmark(), pointtype(), printf(), recenttet, setpoint2tet(), setpointtype(), setvertices, UNUSEDVERTEX, tetgenbehavior::verbose, and VOLVERTEX.
Referenced by delaunizecavity(), and incrementaldelaunay().
void tetgenmesh::initializepools ()
Definition at line 4542 of file tetgen.cxx.
View newest version in sPHENIX GitHub at line 4542 of file tetgen.cxx
References addin, areaboundindex, b, bgm, cavebdrylist, caveencseglist, caveencshlist, caveoldtetlist, cavesegshlist, caveshbdlist, caveshlist, cavetetlist, cavetetseglist, cavetetshlist, cavetetvertlist, checkconstraints, dummypoint, elemattribindex, elemmarkerindex, tetgenio::facetconstraintlist, tetgenbehavior::flipinsert, flippool, in, inittables(), tetgenmesh::memorypool::itembytes, tetgenbehavior::metric, tetgenbehavior::nobisect, tetgenio::numberofpointattributes, tetgenio::numberofpointmtrs, tetgenio::numberoftetrahedronattributes, numelemattrib, numpointattrib, tetgenbehavior::plc, point2simindex, pointmarkindex, pointmtrindex, pointparamindex, points, printf(), tetgenbehavior::psc, tetgenbehavior::quality, REAL, tetgenbehavior::refine, tetgenbehavior::regionattrib, tetgenio::segmentconstraintlist, setpoint2bgmtet(), setpoint2ppt(), setpoint2sh(), setpoint2tet(), setpointmark(), setpointtype(), tetgenbehavior::shellfaceperblock, shmarkindex, sizeoftensor, subfaces, subfacstack, subsegs, subsegstack, subvertstack, tet2segpool, tet2subpool, tetgenbehavior::tetrahedraperblock, tetrahedrons, unflipqueue, UNUSEDVERTEX, useinsertradius, tetgenbehavior::varvolume, tetgenbehavior::verbose, tetgenbehavior::vertexperblock, volumeboundindex, tetgenbehavior::voroout, and tetgenbehavior::weighted.
Referenced by tetrahedralize().
void tetgenmesh::inittables ()
Definition at line 3626 of file tetgen.cxx.
View newest version in sPHENIX GitHub at line 3626 of file tetgen.cxx
References bondtbl, edestoppotbl, enextesymtbl, enexttbl, eorgoppotbl, eprevesymtbl, eprevtbl, esymtbl, facepivot1, facepivot2, fsymtbl, stbondtbl, stpivottbl, tsbondtbl, and tspivottbl.
Referenced by initializepools().
void tetgenmesh::insertconstrainedpoints (point * insertarray, int arylen, int rejflag)
Definition at line 23459 of file tetgen.cxx.
View newest version in sPHENIX GitHub at line 23459 of file tetgen.cxx
References tetgenmesh::insertvertexflags::assignmeshsize, b, tetgenmesh::insertvertexflags::bowywat, tetgenbehavior::brio_hilbert, brio_multiscale_sort(), tetgenbehavior::brio_ratio, tetgenbehavior::brio_threshold, tetgenmesh::insertvertexflags::chkencflag, encseglist, encshlist, tetgenmesh::flipconstraints::enqflag, flipstack, fnextself(), FREEFACETVERTEX, FREESEGVERTEX, FREEVOLVERTEX, hilbert_init(), tetgenmesh::insertvertexflags::iloc, in, tetgenbehavior::incrflip, insertpoint(), INSTAR, issubface, issubseg, tetgenmesh::insertvertexflags::lawson, lawsonflip3d(), tetgenio::mesh_dim, tetgenbehavior::metric, tetgenbehavior::no_sort, nonregularcount, ONEDGE, ONFACE, pointtype(), printf(), rand, tetgenmesh::insertvertexflags::rejflag, tetgenmesh::insertvertexflags::respectbdflag, tetgenmesh::arraypool::restart(), samples, tetgenmesh::insertvertexflags::sbowywat, scoutpoint(), setpointtype(), tetgenmesh::face::sh, tetgenmesh::insertvertexflags::sloc, tetgenmesh::insertvertexflags::splitbdflag, srand, st_facref_count, st_segref_count, st_volref_count, tetgenmesh::triface::tet, tspivot(), tsspivot1(), unflipqueue, UNUSEDVERTEX, unuverts, tetgenmesh::insertvertexflags::validflag, and tetgenbehavior::verbose.
Referenced by insertconstrainedpoints(), and tetrahedralize().
void tetgenmesh::insertconstrainedpoints (tetgenio * addio)
Definition at line 23620 of file tetgen.cxx.
View newest version in sPHENIX GitHub at line 23620 of file tetgen.cxx
References b, tetgenio::firstnumber, in, insertconstrainedpoints(), makepoint(), tetgenbehavior::metric, tetgenio::numberofpointattributes, tetgenio::numberofpointmtrs, tetgenio::numberofpoints, tetgenio::pointattributelist, tetgenio::pointlist, pointmtrindex, tetgenio::pointmtrlist, printf(), tetgenbehavior::quiet, REAL, UNUSEDVERTEX, tetgenbehavior::verbose, tetgenbehavior::weighted, tetgenbehavior::weighted_param, x, xmax, xmin, y, ymax, ymin, z, zmax, and zmin.
int tetgenmesh::insertpoint (point insertpt, triface * searchtet, face * splitsh, face * splitseg, insertvertexflags * ivf)
Definition at line 8987 of file tetgen.cxx.
View newest version in sPHENIX GitHub at line 8987 of file tetgen.cxx
References apex(), tetgenmesh::insertvertexflags::assignmeshsize, b, BADELEMENT, badsubfacs, badsubsegs, bgm, bond(), tetgenmesh::insertvertexflags::bowywat, cavebdrylist, caveencseglist, caveencshlist, caveoldtetlist, cavesegshlist, caveshbdlist, caveshlist, cavetetlist, cavetetseglist, cavetetshlist, cavetetvertlist, tetgenmesh::insertvertexflags::cdtflag, tetgenmesh::badface::cent, checkfac4encroach(), checkseg4encroach(), checksubfaceflag, checksubsegflag, tetgenmesh::insertvertexflags::chkencflag, decode(), dest(), distance(), dummypoint, edestoppo(), elemattribute(), encode(), encseglist, ENCSEGMENT, encshlist, ENCSUBFACE, ENCVERTEX, enextself(), enqueuesubface(), enqueuetetrahedron(), eorgoppo(), epivot, tetgenbehavior::epsilon, esym(), esymself(), fastlookup, finddirection(), flip14count, flip26count, flipn2ncount, flippush(), flipstack, fnextself(), for(), tetgenmesh::badface::forg, fsym(), fsymself(), getpointmeshsize(), hullsize, tetgenmesh::insertvertexflags::iloc, incircle3d(), infect(), infected(), insertpoint_abort(), insphere_s(), INSTAR, INTETRAHEDRON, ishulltet(), isshsubseg, k, tetgenmesh::badface::key, tetgenmesh::insertvertexflags::lawson, locate(), maketetrahedron(), marktest(), marktested(), tetgenbehavior::minedgelength, NEARVERTEX, tetgenmesh::arraypool::newindex(), tetgenbehavior::nomergevertex, nonconvex, NONREGULAR, nonregularcount, NREGULARVERTEX, numelemattrib, tetgenmesh::arraypool::objects, ONEDGE, ONFACE, ONVERTEX, oppo(), org(), orient3d(), orient4d_s(), OUTSIDE, tetgenmesh::insertvertexflags::parentpt, charm_jet_strange_helicity::pc, pinfect(), pinfected(), tetgenbehavior::plc, point2bgmtet(), point2tet(), point2tetorg(), pointmark(), pointmtrindex, printf(), puninfect(), tetgenbehavior::quiet, randomnation(), randomsample(), REAL, recenttet, tetgenmesh::insertvertexflags::refineflag, tetgenmesh::insertvertexflags::refinesh, tetgenmesh::insertvertexflags::refinetet, tetgenmesh::insertvertexflags::rejflag, tetgenmesh::insertvertexflags::respectbdflag, tetgenmesh::arraypool::restart(), Acts::UnitConstants::s, sapex(), tetgenmesh::insertvertexflags::sbowywat, scoutpoint(), sdecode(), sdest(), senextself(), sesymself(), setapex(), setdest(), setelemattribute(), setoppo(), setorg(), setpoint2bgmtet(), setpoint2ppt(), setpoint2tet(), setpointtype(), setvolumebound(), tetgenmesh::face::sh, shellfacedealloc(), tetgenmesh::face::shver, sign(), sinfect(), sinfected(), sinsertvertex(), tetgenmesh::insertvertexflags::sloc, smarktest(), smarktested(), tetgenmesh::insertvertexflags::smlen, tetgenmesh::insertvertexflags::smlenflag, sorg(), spivot(), spivotself(), tetgenmesh::insertvertexflags::splitbdflag, tetgenmesh::badface::ss, sstbond1(), sstdissolve1(), sstpivot1(), stdissolve(), stpivot(), subfaces, subfacstack, subsegs, subsegstack, suninfect(), sunmarktest(), tetgenmesh::triface::tet, tetrahedrondealloc(), tsbond(), tsdissolve(), tssbond1(), uninfect(), unmarktest(), tetgenmesh::insertvertexflags::validflag, tetgenbehavior::varvolume, tetgenmesh::triface::ver, tetgenbehavior::verbose, Acts::Test::volume, volumebound(), and tetgenbehavior::weighted.
Referenced by add_steinerpt_in_schoenhardtpoly(), add_steinerpt_in_segment(), addsteiner4recoversegment(), delaunizecavity(), delaunizesegments(), incrementaldelaunay(), insertconstrainedpoints(), insertpoint_cdt(), recoversubfaces(), splitsegment(), splitsliver(), splitsubface(), and splittetrahedron().
void tetgenmesh::insertpoint_abort (face * splitseg, insertvertexflags * ivf)
Definition at line 10447 of file tetgen.cxx.
View newest version in sPHENIX GitHub at line 10447 of file tetgen.cxx
References cavebdrylist, caveoldtetlist, cavesegshlist, caveshlist, cavetetlist, cavetetseglist, cavetetshlist, fastlookup, tetgenmesh::arraypool::objects, tetgenmesh::arraypool::restart(), tetgenmesh::face::sh, smarktested(), tetgenmesh::insertvertexflags::splitbdflag, sunmarktest(), uninfect(), and unmarktest().
Referenced by insertpoint().
int tetgenmesh::insertpoint_cdt (point newpt, triface * searchtet, face * splitsh, face * splitseg, insertvertexflags * ivf, arraypool * cavpoints, arraypool * cavfaces, arraypool * cavshells, arraypool * newtets, arraypool * crosstets, arraypool * misfaces)
Definition at line 17625 of file tetgen.cxx.
View newest version in sPHENIX GitHub at line 17625 of file tetgen.cxx
References b, carvecavity(), cavebdrylist, caveencseglist, caveencshlist, caveoldtetlist, cavesegshlist, caveshbdlist, caveshlist, cavetetvertlist, checksubfaceflag, delaunizecavity(), fastlookup, fillcavity(), fsymself(), infected(), insertpoint(), tetgenmesh::arraypool::newindex(), tetgenmesh::arraypool::objects, pointmark(), printf(), tetgenmesh::arraypool::restart(), tetgenmesh::insertvertexflags::sbowywat, tetgenmesh::face::sh, shellfacedealloc(), sinsertvertex(), tetgenmesh::insertvertexflags::sloc, spivot(), stpivot(), subfaces, subfacstack, subsegs, subsegstack, tetgenmesh::triface::tet, tsdissolve(), and tetgenbehavior::verbose.
Referenced by refineregion().
REAL tetgenmesh::insphere_s (REAL * pa, REAL * pb, REAL * pc, REAL * pd, REAL * pe)
Definition at line 4842 of file tetgen.cxx.
View newest version in sPHENIX GitHub at line 4842 of file tetgen.cxx
References insphere(), n, orient3d(), charm_jet_strange_helicity::pc, pointmark(), REAL, and sign().
Referenced by checkdelaunay(), checkregular(), flipcertify(), incrementalflip(), insertpoint(), and lawsonflip3d().
void tetgenmesh::interecursive (shellface ** subfacearray, int arraysize, int axis, REAL bxmin, REAL bxmax, REAL bymin, REAL bymax, REAL bzmin, REAL bzmax, int * internum)
Definition at line 14383 of file tetgen.cxx.
View newest version in sPHENIX GitHub at line 14383 of file tetgen.cxx
References b, for(), Acts::PlanarHelper::intersect(), INTERSECT, pointmark(), printf(), tetgenbehavior::quiet, REAL, tetgenmesh::face::sh, SHAREFACE, shellmark(), sinfect(), terminatetetgen(), tri_tri_inter(), and tetgenbehavior::verbose.
Referenced by detectinterfaces().
REAL tetgenmesh::interiorangle (REAL * o, REAL * p1, REAL * p2, REAL * n)
Definition at line 6315 of file tetgen.cxx.
View newest version in sPHENIX GitHub at line 6315 of file tetgen.cxx
References dot(), orient3d(), PI, REAL, theta(), v1, and v2.
Referenced by qualitystatistics(), and scoutsegment().
void tetgenmesh::interpolatemeshsize ()
Definition at line 23388 of file tetgen.cxx.
View newest version in sPHENIX GitHub at line 23388 of file tetgen.cxx
References b, bgm, encode(), getpointmeshsize(), nonregularcount, OUTSIDE, pointmark(), pointmtrindex, points, pointtraverse(), printf(), tetgenbehavior::quiet, REAL, samples, scoutpoint(), setpoint2bgmtet(), tetgenmesh::triface::tet, tetgenmesh::memorypool::traversalinit(), and tetgenbehavior::verbose.
Referenced by tetrahedralize().
bool tetgenmesh::isdeadtet (triface & t) inline
Definition at line 2636 of file tetgen.h.
View newest version in sPHENIX GitHub at line 2636 of file tetgen.h
References tetgenmesh::triface::tet.
Referenced by flipinsertfacet(), getedge(), improvequalitybyflips(), improvequalitybysmoothing(), incrementalflip(), lawsonflip3d(), recoverdelaunay(), repairbadtets(), and suppressbdrysteinerpoint().
bool tetgenmesh::ishulltet (triface & t) inline
Definition at line 2630 of file tetgen.h.
View newest version in sPHENIX GitHub at line 2630 of file tetgen.h
References dummypoint, and t.
Referenced by carvecavity(), carveholes(), checkconforming(), checkfac4split(), checkmesh(), highorder(), insertpoint(), lawsonflip3d(), locate(), numberedges(), outedges(), outfaces(), outhullfaces(), outmesh2medit(), outneighbors(), outsubfaces(), outsubsegments(), outvoronoi(), reconstructmesh(), splitsliver(), and suppressbdrysteinerpoint().
void tetgenmesh::jettisonnodes ()
Definition at line 28471 of file tetgen.cxx.
View newest version in sPHENIX GitHub at line 28471 of file tetgen.cxx
References b, tetgenmesh::memorypool::deaditemstack, DUPLICATEDVERTEX, dupverts, tetgenio::firstnumber, in, pointdealloc(), tetgenio::pointmarkerlist, points, pointtraverse(), pointtype(), printf(), tetgenbehavior::quiet, setpointmark(), tetgenmesh::memorypool::traversalinit(), UNUSEDVERTEX, unuverts, and tetgenbehavior::verbose.
Referenced by meshsurface(), and tetrahedralize().
long tetgenmesh::lawsonflip ()
Definition at line 12001 of file tetgen.cxx.
View newest version in sPHENIX GitHub at line 12001 of file tetgen.cxx
References b, tetgenmesh::memorypool::dealloc(), tetgenmesh::badface::fdest, flip22(), flippool, flipstack, tetgenmesh::badface::forg, incircle3d(), isshsubseg, tetgenmesh::memorypool::items, tetgenmesh::badface::nextitem, charm_jet_strange_helicity::pc, printf(), REAL, sapex(), sdest(), sign(), sorg(), spivot(), tetgenmesh::badface::ss, and tetgenbehavior::verbose.
Referenced by mergefacets(), sremovevertex(), and triangulate().
long tetgenmesh::lawsonflip3d (flipconstraints * fc)
Definition at line 25582 of file tetgen.cxx.
View newest version in sPHENIX GitHub at line 25582 of file tetgen.cxx
References apex(), b, checksubfaceflag, checksubsegflag, tetgenmesh::memorypool::dealloc(), dest(), dummypoint, edestoppo(), enextself(), eorgoppo(), esymself(), facemarked(), tetgenmesh::badface::fapex, fastlookup, tetgenmesh::badface::fdest, flip22count, flip23(), flip23count, flip32(), flip32count, flip44count, flippool, flippush(), flipstack, fnext(), tetgenmesh::badface::forg, FREEFACETVERTEX, FREESEGVERTEX, fsym(), fsymself(), insphere_s(), isdeadtet(), ishulltet(), isshsubseg, issubface, issubseg, tetgenmesh::memorypool::items, tetgenmesh::arraypool::newindex(), tetgenmesh::badface::nextitem, nonconvex, tetgenmesh::arraypool::objects, oppo(), org(), orient3d(), pointtype(), printf(), REAL, tetgenmesh::flipconstraints::remove_ndelaunay_edge, removevertexbyflips(), tetgenmesh::arraypool::restart(), sdest(), senextself(), sesymself(), sign(), sorg(), spivot(), stpivot(), tetgenmesh::triface::tet, tetgenmesh::flipconstraints::tetprism_vol_sum, tetprism_vol_sum, tspivot(), tetgenmesh::badface::tt, unflipqueue, unmarkface(), and tetgenbehavior::verbose.
Referenced by carveholes(), insertconstrainedpoints(), recoverdelaunay(), splitsegment(), splitsubface(), and splittetrahedron().
int tetgenmesh::linelineint (REAL * A, REAL * B, REAL * C, REAL * D, REAL * P, REAL * Q, REAL * tp, REAL * tq)
Definition at line 6838 of file tetgen.cxx.
View newest version in sPHENIX GitHub at line 6838 of file tetgen.cxx
References dot(), eps, epsilon, and REAL.
Referenced by add_steinerpt_in_segment().
enum tetgenmesh::locateresult tetgenmesh::locate (point searchpt, triface * searchtet)
Definition at line 11005 of file tetgen.cxx.
View newest version in sPHENIX GitHub at line 11005 of file tetgen.cxx
References apex(), dest(), dummypoint, enextesymself(), enextself(), eprevesymself(), eprevself(), esymself(), fsymself(), INTETRAHEDRON, ishulltet(), ONEDGE, ONFACE, ONVERTEX, oppo(), org(), orient3d(), OUTSIDE, randomnation(), REAL, recenttet, Acts::UnitConstants::s, tetgenmesh::triface::tet, and tetgenmesh::triface::ver.
Referenced by add_steinerpt_in_schoenhardtpoly(), carveholes(), insertpoint(), scoutpoint(), and splitsliver().
bool tetgenmesh::lu_decmp (REAL lu[4][4], int n, int * ps, REAL * d, int N)
Definition at line 6007 of file tetgen.cxx.
View newest version in sPHENIX GitHub at line 6007 of file tetgen.cxx
References k, charm_jet_strange_helicity::N, and REAL.
Referenced by checkconforming(), checkfac4split(), checktet4split(), circumsphere(), orthosphere(), qualitystatistics(), tetallnormal(), and tetaspectratio().
void tetgenmesh::lu_solve (REAL lu[4][4], int n, int * ps, REAL * b, int N)
Definition at line 6080 of file tetgen.cxx.
View newest version in sPHENIX GitHub at line 6080 of file tetgen.cxx
References dot(), charm_jet_strange_helicity::N, and REAL.
Referenced by checkconforming(), checkfac4split(), checktet4split(), circumsphere(), orthosphere(), qualitystatistics(), tetallnormal(), and tetaspectratio().
void tetgenmesh::makefacetverticesmap ()
Definition at line 23923 of file tetgen.cxx.
View newest version in sPHENIX GitHub at line 23923 of file tetgen.cxx
References b, caveshlist, facetverticeslist, fastlookup, for(), FREEFACETVERTEX, FREESEGVERTEX, idx2facetlist, isshsubseg, k, tetgenmesh::arraypool::newindex(), tetgenmesh::arraypool::objects, pinfect(), pinfected(), pointtype(), printf(), puninfect(), tetgenmesh::arraypool::restart(), sapex(), senextself(), setfacetindex(), tetgenmesh::face::sh, shellfacetraverse(), sinfect(), sinfected(), spivot(), subfaces, suninfect(), totalworkmemory, tetgenmesh::memorypool::traversalinit(), and tetgenbehavior::verbose.
Referenced by delaunayrefinement().
void tetgenmesh::makeindex2pointmap (point *& idx2verlist)
Definition at line 4181 of file tetgen.cxx.
View newest version in sPHENIX GitHub at line 4181 of file tetgen.cxx
References b, tetgenio::firstnumber, in, tetgenmesh::memorypool::items, points, pointtraverse(), printf(), tetgenmesh::memorypool::traversalinit(), and tetgenbehavior::verbose.
Referenced by meshsurface(), and reconstructmesh().
void tetgenmesh::makepoint (point * pnewpoint, enum verttype vtype)
Definition at line 4500 of file tetgen.cxx.
View newest version in sPHENIX GitHub at line 4500 of file tetgen.cxx
References tetgenmesh::memorypool::alloc(), b, bgm, tetgenio::firstnumber, in, tetgenmesh::memorypool::items, tetgenbehavior::metric, numpointattrib, tetgenbehavior::plc, pointmarkindex, pointmtrindex, points, tetgenbehavior::refine, setpoint2bgmtet(), setpoint2ppt(), setpoint2sh(), setpoint2tet(), setpointmark(), setpointtype(), and sizeoftensor.
Referenced by add_steinerpt_in_schoenhardtpoly(), add_steinerpt_in_segment(), addsteiner4recoversegment(), delaunizesegments(), highorder(), insertconstrainedpoints(), recoversubfaces(), refineregion(), splitsegment(), splitsliver(), splitsubface(), splittetrahedron(), suppressbdrysteinerpoint(), and transfernodes().
void tetgenmesh::makepoint2submap (memorypool * pool, int *& idx2faclist, face *& facperverlist)
Definition at line 4215 of file tetgen.cxx.
View newest version in sPHENIX GitHub at line 4215 of file tetgen.cxx
References b, tetgenio::firstnumber, in, tetgenmesh::memorypool::items, k, pointmark(), points, printf(), tetgenmesh::face::sh, shellfacetraverse(), tetgenmesh::face::shver, tetgenmesh::memorypool::traversalinit(), and tetgenbehavior::verbose.
Referenced by identifypscedges(), reconstructmesh(), and unifysegments().
void tetgenmesh::makesegmentendpointsmap ()
Definition at line 14628 of file tetgen.cxx.
View newest version in sPHENIX GitHub at line 14628 of file tetgen.cxx
References b, fastlookup, tetgenmesh::arraypool::newindex(), tetgenmesh::arraypool::objects, printf(), sdest(), segmentendpointslist, senext(), senext2(), senextself(), sesymself(), setfacetindex(), tetgenmesh::face::sh, shellfacetraverse(), tetgenmesh::face::shver, sorg(), spivotself(), subsegs, totalworkmemory, tetgenmesh::memorypool::traversalinit(), and tetgenbehavior::verbose.
Referenced by constraineddelaunay(), and delaunayrefinement().
void tetgenmesh::makeshellface (memorypool * pool, face * newface)
Definition at line 4460 of file tetgen.cxx.
View newest version in sPHENIX GitHub at line 4460 of file tetgen.cxx
References tetgenmesh::memorypool::alloc(), checkconstraints, setareabound(), setfacetindex(), setshellmark(), tetgenmesh::face::sh, shmarkindex, tetgenmesh::face::shver, and useinsertradius.
Referenced by delaunizecavity(), fillcavity(), fillregion(), flip31(), formregion(), identifypscedges(), reconstructmesh(), recoversubfaces(), sinsertvertex(), sremovevertex(), sscoutsegment(), and triangulate().
void tetgenmesh::maketetrahedron (triface * newtet)
Definition at line 4423 of file tetgen.cxx.
View newest version in sPHENIX GitHub at line 4423 of file tetgen.cxx
References tetgenmesh::memorypool::alloc(), b, numelemattrib, setelemattribute(), setelemmarker(), setvolumebound(), tetgenmesh::triface::tet, tetrahedrons, tetgenbehavior::varvolume, and tetgenmesh::triface::ver.
Referenced by add_steinerpt_in_schoenhardtpoly(), carveholes(), flip23(), initialdelaunay(), insertpoint(), reconstructmesh(), and suppressbdrysteinerpoint().
void tetgenmesh::markedge (triface & t) inline
Definition at line 2574 of file tetgen.h.
View newest version in sPHENIX GitHub at line 2574 of file tetgen.h
References elemmarkerindex, t, tetgenmesh::triface::tet, and ver2edge.
Referenced by formcavity().
void tetgenmesh::markface (triface & t) inline
Definition at line 2557 of file tetgen.h.
View newest version in sPHENIX GitHub at line 2557 of file tetgen.h
References elemmarkerindex, tetgenmesh::triface::tet, and tetgenmesh::triface::ver.
Referenced by fillcavity(), and flippush().
void tetgenmesh::marktest (triface & t) inline
Definition at line 2541 of file tetgen.h.
View newest version in sPHENIX GitHub at line 2541 of file tetgen.h
References elemmarkerindex, and tetgenmesh::triface::tet.
Referenced by delaunizecavity(), flipinsertfacet(), improvequalitybysmoothing(), incrementalflip(), and insertpoint().
void tetgenmesh::marktest2 (triface & t) inline
Definition at line 2590 of file tetgen.h.
View newest version in sPHENIX GitHub at line 2590 of file tetgen.h
References elemmarkerindex, and tetgenmesh::triface::tet.
Referenced by enqueuetetrahedron().
bool tetgenmesh::marktest2ed (triface & t) inline
Definition at line 2598 of file tetgen.h.
View newest version in sPHENIX GitHub at line 2598 of file tetgen.h
References elemmarkerindex, and tetgenmesh::triface::tet.
Referenced by enqueuetetrahedron(), and repairbadtets().
bool tetgenmesh::marktested (triface & t) inline
Definition at line 2549 of file tetgen.h.
View newest version in sPHENIX GitHub at line 2549 of file tetgen.h
References elemmarkerindex, and tetgenmesh::triface::tet.
Referenced by carvecavity(), checkmesh(), delaunizecavity(), fillcavity(), flipinsertfacet(), improvequalitybysmoothing(), incrementalflip(), and insertpoint().
void tetgenmesh::memorystatistics ()
Definition at line 28288 of file tetgen.cxx.
View newest version in sPHENIX GitHub at line 28288 of file tetgen.cxx
References b, cavebdrylist, caveencseglist, caveencshlist, caveoldtetlist, cavesegshlist, caveshbdlist, caveshlist, cavetetlist, cavetetseglist, cavetetshlist, cavetetvertlist, tetgenmesh::memorypool::firstblock, flippool, tetgenmesh::memorypool::itembytes, tetgenmesh::memorypool::maxitems, tetgenmesh::memorypool::pathblock, tetgenbehavior::plc, points, printf(), printfcomma(), tetgenbehavior::refine, subfaces, subfacstack, subsegs, subsegstack, subvertstack, tet2segpool, tet2subpool, tetgenbehavior::tetrahedraperblock, tetrahedrons, tetgenmesh::arraypool::totalmemory, totalworkmemory, and unflipqueue.
Referenced by statistics().
void tetgenmesh::mergefacets ()
Definition at line 13914 of file tetgen.cxx.
View newest version in sPHENIX GitHub at line 13914 of file tetgen.cxx
References b, facedihedral(), tetgenbehavior::facet_ang_tol, tetgenio::facetmarkerlist, flipshpush(), flipstack, in, lawsonflip(), charm_jet_strange_helicity::pc, PI, printf(), REAL, sapex(), sdest(), tetgenmesh::face::sh, shellfacedealloc(), shellfacetraverse(), shellmark(), sorg(), spivot(), ssdissolve(), subsegs, tetgenmesh::memorypool::traversalinit(), and tetgenbehavior::verbose.
Referenced by meshsurface().
void tetgenmesh::meshcoarsening ()
Definition at line 23820 of file tetgen.cxx.
View newest version in sPHENIX GitHub at line 23820 of file tetgen.cxx
References autofliplinklevel, b, collectremovepoints(), fastlookup, tetgenbehavior::fliplinklevel, tetgenbehavior::fliplinklevelinc, Acts::UnitConstants::ms, tetgenmesh::arraypool::objects, pointtype(), printf(), tetgenbehavior::quiet, removevertexbyflips(), UNUSEDVERTEX, and tetgenbehavior::verbose.
Referenced by tetrahedralize().
void tetgenmesh::meshsurface ()
Definition at line 14184 of file tetgen.cxx.
View newest version in sPHENIX GitHub at line 14184 of file tetgen.cxx
References b, tetgenbehavior::diagnose, DUPLICATEDVERTEX, dupverts, tetgenio::facetlist, fastlookup, tetgenio::firstnumber, tetgenio::facet::holelist, identifypscedges(), in, insegments, tetgenmesh::memorypool::items, jettisonnodes(), makeindex2pointmap(), mergefacets(), tetgenmesh::arraypool::newindex(), tetgenbehavior::nobisect, tetgenbehavior::nomergefacet, tetgenio::numberofedges, tetgenio::numberoffacets, tetgenio::facet::numberofholes, tetgenio::numberofpoints, tetgenio::facet::numberofpolygons, tetgenio::polygon::numberofvertices, tetgenbehavior::object, tetgenmesh::arraypool::objects, p, pinfect(), pinfected(), point2ppt(), pointmark(), pointtype(), tetgenio::facet::polygonlist, printf(), tetgenbehavior::psc, puninfect(), tetgenbehavior::quiet, tetgenmesh::arraypool::restart(), RIDGEVERTEX, setpointtype(), tetgenmesh::face::sh, shellfacetraverse(), tetgenbehavior::STL, subfaces, subsegs, tetgenmesh::memorypool::traversalinit(), triangulate(), unifysegments(), tetgenbehavior::verbose, and tetgenio::polygon::vertexlist.
Referenced by tetrahedralize().
REAL tetgenmesh::norm2 (REAL x, REAL y, REAL z) inline
Definition at line 3327 of file tetgen.h.
View newest version in sPHENIX GitHub at line 3327 of file tetgen.h
References x, y, and z.
Referenced by incrementaldelaunay().
void tetgenmesh::numberedges ()
Definition at line 28628 of file tetgen.cxx.
View newest version in sPHENIX GitHub at line 28628 of file tetgen.cxx
References edge2ver, elemindex(), fnext(), fnextself(), ishulltet(), meshedges, meshhulledges, tetgenmesh::triface::tet, tetrahedrons, tetrahedrontraverse(), tetgenmesh::memorypool::traversalinit(), and tetgenmesh::triface::ver.
Referenced by outedges().
tetgenmesh::point tetgenmesh::oppo (triface & t) inline
Definition at line 2451 of file tetgen.h.
View newest version in sPHENIX GitHub at line 2451 of file tetgen.h
References oppopivot, and t.
Referenced by add_steinerpt_in_schoenhardtpoly(), addsteiner4recoversegment(), checkconforming(), checkdelaunay(), checkfac4split(), checkmesh(), checkregular(), checksegments(), checkshells(), delaunizecavity(), fillcavity(), finddirection(), flip23(), flipcertify(), flipinsertfacet(), flipnm(), gettetrahedron(), incrementalflip(), insertpoint(), lawsonflip3d(), locate(), reconstructmesh(), recoveredgebyflips(), recoverfacebyflips(), removefacebyflips(), removevertexbyflips(), scoutcrossedge(), scoutpoint(), and scoutsegment().
void tetgenmesh::optimizemesh ()
Definition at line 26805 of file tetgen.cxx.
View newest version in sPHENIX GitHub at line 26805 of file tetgen.cxx
References b, badtetrahedrons, tetgenmesh::badface::cent, tetgenbehavior::convex, cos(), cosmaxdihed, cosslidihed, cossmtdihed, elemattribute(), tetgenmesh::badface::fapex, tetgenmesh::badface::fdest, tetgenmesh::badface::foppo, tetgenmesh::badface::forg, improvequalitybyflips(), improvequalitybysmoothing(), tetgenmesh::badface::key, tetgenmesh::optparameters::maxiter, tetgenmesh::optparameters::min_max_dihedangle, n, tetgenmesh::arraypool::newindex(), numelemattrib, tetgenmesh::optparameters::numofsearchdirs, tetgenmesh::arraypool::objects, tetgenbehavior::optlevel, tetgenbehavior::optmaxdihedral, tetgenbehavior::optminslidihed, tetgenbehavior::optminsmtdihed, tetgenbehavior::optscheme, PI, printf(), tetgenbehavior::quiet, REAL, removeslivers(), tetgenmesh::arraypool::restart(), tetgenmesh::triface::tet, tetalldihedral(), tetgenbehavior::tetrahedraperblock, tetrahedrons, tetrahedrontraverse(), tetgenmesh::memorypool::traversalinit(), tetgenmesh::badface::tt, unflipqueue, tetgenmesh::triface::ver, and tetgenbehavior::verbose.
Referenced by tetrahedralize().
tetgenmesh::point tetgenmesh::org (triface & t) inline
Definition at line 2439 of file tetgen.h.
View newest version in sPHENIX GitHub at line 2439 of file tetgen.h
References orgpivot, and t.
Referenced by add_steinerpt_in_schoenhardtpoly(), addsteiner4recoversegment(), carveholes(), checkdelaunay(), checkmesh(), checkregular(), checksegments(), checkshells(), checktet4split(), delaunizecavity(), fillcavity(), fillregion(), finddirection(), flip23(), flip32(), flip41(), flipcertify(), flipinsertfacet(), flipnm(), formcavity(), getedge(), getpointmeshsize(), highorder(), incrementaldelaunay(), incrementalflip(), insertpoint(), lawsonflip3d(), locate(), outedges(), outfaces(), outmesh2medit(), outsubfaces(), outvoronoi(), qualitystatistics(), randomsample(), reconstructmesh(), recoveredgebyflips(), removefacebyflips(), removevertexbyflips(), scoutpoint(), scoutsegment(), smoothpoint(), splitsliver(), splittetrahedron(), and suppressbdrysteinerpoint().
REAL tetgenmesh::orient3dfast (REAL * pa, REAL * pb, REAL * pc, REAL * pd)
Definition at line 6281 of file tetgen.cxx.
View newest version in sPHENIX GitHub at line 6281 of file tetgen.cxx
References REAL.
Referenced by flipcertify(), getpointmeshsize(), incrementaldelaunay(), qualitystatistics(), scoutpoint(), smoothpoint(), and suppresssteinerpoints().
REAL tetgenmesh::orient4d_s (REAL * pa, REAL * pb, REAL * pc, REAL * pd, REAL * pe, REAL aheight, REAL bheight, REAL cheight, REAL dheight, REAL eheight)
Definition at line 4911 of file tetgen.cxx.
View newest version in sPHENIX GitHub at line 4911 of file tetgen.cxx
References n, orient3d(), orient4d(), charm_jet_strange_helicity::pc, pointmark(), REAL, and sign().
Referenced by checkregular(), incrementalflip(), and insertpoint().
bool tetgenmesh::orthosphere (REAL * pa, REAL * pb, REAL * pc, REAL * pd, REAL aheight, REAL bheight, REAL cheight, REAL dheight, REAL * orthocent, REAL * radius)
Definition at line 6736 of file tetgen.cxx.
View newest version in sPHENIX GitHub at line 6736 of file tetgen.cxx
References lu_decmp(), lu_solve(), and REAL.
Referenced by outvoronoi().
void tetgenmesh::outedges (tetgenio * out)
Definition at line 29568 of file tetgen.cxx.
View newest version in sPHENIX GitHub at line 29568 of file tetgen.cxx
References b, tetgenbehavior::commandline, dest(), dupverts, edge2ver, tetgenio::edgeadjtetlist, tetgenio::edgelist, tetgenio::edgemarkerlist, elemindex(), FILENAMESIZE, tetgenio::firstnumber, fnext(), fnextself(), hullsize, in, Acts::index1, Acts::index2, ishulltet(), tetgenmesh::memorypool::items, marker(), meshedges, tetgenbehavior::neighout, tetgenbehavior::nobound, nonconvex, nonregularcount, numberedges(), tetgenio::numberofedges, tetgenio::o2edgelist, tetgenbehavior::order, org(), tetgenbehavior::outfilename, tetgenbehavior::plc, pointmark(), points, printf(), tetgenbehavior::quiet, tetgenbehavior::refine, tetgenmesh::face::sh, shellmark(), terminatetetgen(), tetgenmesh::triface::tet, tetrahedrons, tetrahedrontraverse(), tetgenmesh::memorypool::traversalinit(), tsspivot1(), unuverts, tetgenmesh::triface::ver, ver2edge, tetgenbehavior::weighted, and tetgenbehavior::zeroindex.
Referenced by tetrahedralize().
void tetgenmesh::outelements (tetgenio * out)
Definition at line 28945 of file tetgen.cxx.
View newest version in sPHENIX GitHub at line 28945 of file tetgen.cxx
References b, tetgenbehavior::commandline, elemattribute(), FILENAMESIZE, tetgenio::firstnumber, hullsize, in, tetgenmesh::memorypool::items, tetgenio::numberofcorners, tetgenio::numberoftetrahedra, tetgenio::numberoftetrahedronattributes, numelemattrib, tetgenbehavior::order, tetgenbehavior::outfilename, pointmark(), printf(), tetgenbehavior::quiet, REAL, tetgenbehavior::reversetetori, setelemindex(), terminatetetgen(), tetgenio::tetrahedronattributelist, tetgenio::tetrahedronlist, tetrahedrons, tetrahedrontraverse(), tetgenmesh::memorypool::traversalinit(), and tetgenbehavior::zeroindex.
Referenced by tetrahedralize().
void tetgenmesh::outfaces (tetgenio * out)
Definition at line 29085 of file tetgen.cxx.
View newest version in sPHENIX GitHub at line 29085 of file tetgen.cxx
References tetgenio::adjtetlist, apex(), b, tetgenbehavior::commandline, dest(), elemindex(), enext(), enextself(), tetgenio::facetmarkerlist, FILENAMESIZE, tetgenio::firstnumber, fsym(), hullsize, in, ishulltet(), tetgenmesh::memorypool::items, marker(), tetgenbehavior::neighout, tetgenbehavior::nobound, tetgenio::numberoftrifaces, tetgenio::o2facelist, tetgenbehavior::order, org(), tetgenbehavior::outfilename, tetgenbehavior::plc, pointmark(), printf(), tetgenbehavior::quiet, tetgenbehavior::refine, tetgenmesh::face::sh, shellmark(), terminatetetgen(), tetgenmesh::triface::tet, tetrahedrons, tetrahedrontraverse(), tetgenmesh::memorypool::traversalinit(), tetgenio::trifacelist, tetgenio::trifacemarkerlist, tspivot(), tetgenmesh::triface::ver, ver2edge, and tetgenbehavior::zeroindex.
Referenced by flip22(), flip31(), and tetrahedralize().
void tetgenmesh::outhullfaces (tetgenio * out)
Definition at line 29277 of file tetgen.cxx.
View newest version in sPHENIX GitHub at line 29277 of file tetgen.cxx
References alltetrahedrontraverse(), b, tetgenbehavior::commandline, FILENAMESIZE, tetgenio::firstnumber, hullsize, in, ishulltet(), tetgenio::numberoftrifaces, tetgenbehavior::outfilename, pointmark(), printf(), tetgenbehavior::quiet, terminatetetgen(), tetgenmesh::triface::tet, tetrahedrons, tetgenmesh::memorypool::traversalinit(), tetgenio::trifacelist, and tetgenbehavior::zeroindex.
Referenced by tetrahedralize().
void tetgenmesh::outmesh2medit (char * mfilename)
Definition at line 30562 of file tetgen.cxx.
View newest version in sPHENIX GitHub at line 30562 of file tetgen.cxx
References apex(), b, dest(), elemattribute(), elemindex(), tetgenio::facetmarkerlist, FILENAMESIZE, fsym(), hullsize, in, ishulltet(), tetgenmesh::memorypool::items, marker(), tetgenio::numberofpointattributes, tetgenio::numberofpoints, numelemattrib, org(), tetgenbehavior::outfilename, tetgenbehavior::plc, pointmark(), points, pointtraverse(), printf(), tetgenbehavior::quiet, tetgenbehavior::refine, tetgenbehavior::reversetetori, sdest(), setpointmark(), tetgenmesh::face::sh, shellfacetraverse(), shellmark(), sorg(), subsegs, tetgenmesh::triface::tet, tetrahedrons, tetrahedrontraverse(), tetgenmesh::memorypool::traversalinit(), tspivot(), and tetgenmesh::triface::ver.
Referenced by tetrahedralize().
void tetgenmesh::outmesh2vtk (char * ofilename)
Definition at line 30723 of file tetgen.cxx.
View newest version in sPHENIX GitHub at line 30723 of file tetgen.cxx
References b, elemattribute(), FILENAMESIZE, tetgenio::firstnumber, hullsize, in, tetgenmesh::memorypool::items, numelemattrib, tetgenbehavior::order, tetgenbehavior::outfilename, pointmark(), points, pointtraverse(), printf(), tetgenbehavior::quiet, tetgenbehavior::reversetetori, tetrahedrons, tetrahedrontraverse(), tetgenmesh::memorypool::traversalinit(), x, y, and z.
Referenced by tetrahedralize().
void tetgenmesh::outmetrics (tetgenio * out)
Definition at line 28872 of file tetgen.cxx.
View newest version in sPHENIX GitHub at line 28872 of file tetgen.cxx
References b, tetgenbehavior::commandline, FILENAMESIZE, tetgenmesh::memorypool::items, tetgenio::numberofpointmtrs, tetgenbehavior::outfilename, pointmtrindex, tetgenio::pointmtrlist, points, pointtraverse(), printf(), tetgenbehavior::quiet, REAL, terminatetetgen(), and tetgenmesh::memorypool::traversalinit().
Referenced by tetrahedralize().
void tetgenmesh::outneighbors (tetgenio * out)
Definition at line 29897 of file tetgen.cxx.
View newest version in sPHENIX GitHub at line 29897 of file tetgen.cxx
References b, tetgenbehavior::commandline, elemindex(), FILENAMESIZE, tetgenio::firstnumber, fsym(), hullsize, in, ishulltet(), tetgenmesh::memorypool::items, tetgenio::neighborlist, tetgenbehavior::outfilename, printf(), tetgenbehavior::quiet, terminatetetgen(), tetgenmesh::triface::tet, tetrahedrons, tetrahedrontraverse(), tetgenmesh::memorypool::traversalinit(), tetgenmesh::triface::ver, and tetgenbehavior::zeroindex.
Referenced by tetrahedralize().
void tetgenmesh::outnodes (tetgenio * out)
Definition at line 28674 of file tetgen.cxx.
View newest version in sPHENIX GitHub at line 28674 of file tetgen.cxx
References ACUTEVERTEX, b, tetgenbehavior::commandline, tetgenio::facetmarkerlist, FILENAMESIZE, tetgenio::firstnumber, FREEFACETVERTEX, FREESEGVERTEX, FREEVOLVERTEX, in, tetgenmesh::memorypool::items, marker(), tetgenbehavior::nobound, tetgenio::numberofpointattributes, tetgenio::numberofpoints, numpointattrib, tetgenbehavior::outfilename, point2sh(), tetgenio::pointattributelist, pointgeomtag(), pointgeomuv(), tetgenio::pointlist, tetgenio::pointmarkerlist, tetgenio::pointparamlist, points, pointtraverse(), pointtype(), printf(), tetgenbehavior::psc, tetgenbehavior::quiet, REAL, RIDGEVERTEX, sdecode(), tetgenmesh::face::sh, shellmark(), tetgenio::pointparam::tag, terminatetetgen(), tetgenmesh::memorypool::traversalinit(), tetgenio::pointparam::type, tetgenio::pointparam::uv, tetgenbehavior::weighted, tetgenbehavior::weighted_param, and tetgenbehavior::zeroindex.
Referenced by tetrahedralize().
void tetgenmesh::outsmesh (char * smfilename)
Definition at line 30455 of file tetgen.cxx.
View newest version in sPHENIX GitHub at line 30455 of file tetgen.cxx
References b, tetgenbehavior::commandline, tetgenio::facetmarkerlist, FILENAMESIZE, tetgenio::firstnumber, tetgenio::holelist, in, tetgenmesh::memorypool::items, marker(), tetgenbehavior::nobound, tetgenio::numberofholes, tetgenio::numberofregions, tetgenbehavior::outfilename, pointmark(), printf(), tetgenbehavior::quiet, tetgenio::regionlist, sapex(), sdest(), tetgenmesh::face::sh, shellfacetraverse(), shellmark(), sorg(), subfaces, tetgenmesh::memorypool::traversalinit(), and tetgenbehavior::zeroindex.
Referenced by tetrahedralize().
void tetgenmesh::outsubfaces (tetgenio * out)
Definition at line 29369 of file tetgen.cxx.
View newest version in sPHENIX GitHub at line 29369 of file tetgen.cxx
References tetgenio::adjtetlist, apex(), b, tetgenbehavior::commandline, dest(), elemindex(), enextself(), tetgenio::facetmarkerlist, FILENAMESIZE, tetgenio::firstnumber, fsymself(), in, Acts::index1, Acts::index2, ishulltet(), tetgenmesh::memorypool::items, marker(), tetgenbehavior::neighout, tetgenbehavior::nobound, tetgenio::numberoftrifaces, tetgenio::o2facelist, tetgenbehavior::order, org(), tetgenbehavior::outfilename, pointmark(), printf(), tetgenbehavior::quiet, tetgenbehavior::refine, sapex(), sdest(), tetgenmesh::face::sh, shellfacetraverse(), shellmark(), sorg(), stpivot(), subfaces, terminatetetgen(), tetgenmesh::triface::tet, tetgenmesh::memorypool::traversalinit(), tetgenio::trifacelist, tetgenio::trifacemarkerlist, tetgenmesh::triface::ver, ver2edge, and tetgenbehavior::zeroindex.
Referenced by tetrahedralize().
void tetgenmesh::outsubsegments (tetgenio * out)
Definition at line 29742 of file tetgen.cxx.
View newest version in sPHENIX GitHub at line 29742 of file tetgen.cxx
References b, tetgenbehavior::commandline, tetgenio::edgeadjtetlist, tetgenio::edgelist, tetgenio::edgemarkerlist, elemindex(), FILENAMESIZE, tetgenio::firstnumber, fnextself(), in, Acts::index2, ishulltet(), tetgenmesh::memorypool::items, marker(), tetgenbehavior::neighout, tetgenio::numberofedges, tetgenio::o2edgelist, tetgenbehavior::order, tetgenbehavior::outfilename, pointmark(), printf(), tetgenbehavior::quiet, sdest(), tetgenmesh::face::sh, shellfacetraverse(), shellmark(), sorg(), sstpivot1(), subsegs, terminatetetgen(), tetgenmesh::triface::tet, tetgenmesh::memorypool::traversalinit(), tetgenmesh::triface::ver, ver2edge, and tetgenbehavior::zeroindex.
Referenced by tetrahedralize().
void tetgenmesh::outvoronoi (tetgenio * out)
Definition at line 29998 of file tetgen.cxx.
View newest version in sPHENIX GitHub at line 29998 of file tetgen.cxx
References alltetrahedrontraverse(), apex(), b, tetgenio::vorofacet::c1, tetgenio::vorofacet::c2, cavetetlist, cavetetvertlist, circumsphere(), tetgenbehavior::commandline, cross(), dest(), dummypoint, DUPLICATEDVERTEX, dupverts, edge2ver, elemindex(), tetgenio::vorofacet::elist, encode(), enextself(), esym(), fastlookup, FILENAMESIZE, tetgenio::firstnumber, fnext(), fnextself(), fsym(), getvertexstar(), hullsize, in, ishulltet(), tetgenmesh::memorypool::items, Acts::IntegrationTest::L, nonregularcount, NREGULARVERTEX, tetgenio::numberofvcells, tetgenio::numberofvedges, tetgenio::numberofvfacets, tetgenio::numberofvpoints, tetgenmesh::arraypool::objects, org(), orthosphere(), tetgenbehavior::outfilename, pinfect(), pinfected(), pointmark(), points, pointtraverse(), pointtype(), printf(), puninfect(), tetgenbehavior::quiet, REAL, tetgenmesh::arraypool::restart(), setelemindex(), setpoint2tet(), terminatetetgen(), tetgenmesh::triface::tet, tetrahedrons, tetrahedrontraverse(), tetgenmesh::memorypool::traversalinit(), UNUSEDVERTEX, unuverts, tetgenio::voroedge::v1, tetgenio::voroedge::v2, tetgenio::vcelllist, tetgenio::vedgelist, tetgenmesh::triface::ver, ver2edge, tetgenio::vfacetlist, tetgenio::voroedge::vnormal, tetgenio::vpointlist, tetgenbehavior::weighted, and tetgenbehavior::zeroindex.
Referenced by tetrahedralize().
void tetgenmesh::pinfect (point pt) inline
Definition at line 3135 of file tetgen.h.
View newest version in sPHENIX GitHub at line 3135 of file tetgen.h
References pointmarkindex.
Referenced by collectremovepoints(), delaunizecavity(), facetfacetadjacent(), formcavity(), getvertexstar(), incrementalflip(), insertpoint(), makefacetverticesmap(), meshsurface(), outvoronoi(), segfacetadjacent(), and triangulate().
bool tetgenmesh::pinfected (point pt) inline
Definition at line 3143 of file tetgen.h.
View newest version in sPHENIX GitHub at line 3143 of file tetgen.h
References pointmarkindex.
Referenced by collectremovepoints(), delaunizecavity(), facetfacetadjacent(), formcavity(), getvertexstar(), incrementalflip(), insertpoint(), makefacetverticesmap(), meshsurface(), outvoronoi(), segfacetadjacent(), and triangulate().
void tetgenmesh::planelineint (REAL * pa, REAL * pb, REAL * pc, REAL * e1, REAL * e2, REAL * ip, REAL * u)
Definition at line 6803 of file tetgen.cxx.
View newest version in sPHENIX GitHub at line 6803 of file tetgen.cxx
References facenormal(), n, and REAL.
Referenced by suppressbdrysteinerpoint().
void tetgenmesh::pmarktest (point pt) inline
Definition at line 3150 of file tetgen.h.
View newest version in sPHENIX GitHub at line 3150 of file tetgen.h
References pointmarkindex.
Referenced by formregion().
void tetgenmesh::pmarktest2 (point pt) inline
Definition at line 3162 of file tetgen.h.
View newest version in sPHENIX GitHub at line 3162 of file tetgen.h
References pointmarkindex.
Referenced by flipinsertfacet().
bool tetgenmesh::pmarktest2ed (point pt) inline
Definition at line 3170 of file tetgen.h.
View newest version in sPHENIX GitHub at line 3170 of file tetgen.h
References pointmarkindex.
Referenced by flipcertify(), and flipinsertfacet().
void tetgenmesh::pmarktest3 (point pt) inline
Definition at line 3174 of file tetgen.h.
View newest version in sPHENIX GitHub at line 3174 of file tetgen.h
References pointmarkindex.
Referenced by flipinsertfacet().
bool tetgenmesh::pmarktest3ed (point pt) inline
Definition at line 3182 of file tetgen.h.
View newest version in sPHENIX GitHub at line 3182 of file tetgen.h
References pointmarkindex.
Referenced by flipcertify(), and flipinsertfacet().
bool tetgenmesh::pmarktested (point pt) inline
Definition at line 3158 of file tetgen.h.
View newest version in sPHENIX GitHub at line 3158 of file tetgen.h
References pointmarkindex.
Referenced by fillcavity(), fillregion(), flipinsertfacet(), formcavity(), formregion(), and scoutcrossedge().
tetgenmesh::tetrahedron tetgenmesh::point2bgmtet (point pt) inline
Definition at line 3214 of file tetgen.h.
View newest version in sPHENIX GitHub at line 3214 of file tetgen.h
References point2simindex.
Referenced by insertpoint().
tetgenmesh::point tetgenmesh::point2ppt (point pt) inline
Definition at line 3197 of file tetgen.h.
View newest version in sPHENIX GitHub at line 3197 of file tetgen.h
References point2simindex.
Referenced by incrementaldelaunay(), and meshsurface().
tetgenmesh::shellface tetgenmesh::point2sh (point pt) inline
Definition at line 3205 of file tetgen.h.
View newest version in sPHENIX GitHub at line 3205 of file tetgen.h
References point2simindex.
Referenced by checksegments(), getsteinerptonsegment(), outnodes(), point2shorg(), removevertexbyflips(), splitsegment(), splitsubface(), and suppressbdrysteinerpoint().
void tetgenmesh::point2shorg (point pa, face & s) inline
Definition at line 3253 of file tetgen.h.
View newest version in sPHENIX GitHub at line 3253 of file tetgen.h
References point2sh(), sdecode(), tetgenmesh::face::sh, and tetgenmesh::face::shver.
tetgenmesh::tetrahedron tetgenmesh::point2tet (point pt) inline
Definition at line 3189 of file tetgen.h.
View newest version in sPHENIX GitHub at line 3189 of file tetgen.h
References point2simindex.
Referenced by carveholes(), insertpoint(), point2tetorg(), and reconstructmesh().
void tetgenmesh::point2tetorg (point pt, triface & t) inline
Definition at line 3236 of file tetgen.h.
View newest version in sPHENIX GitHub at line 3236 of file tetgen.h
References decode(), point2tet(), tetgenmesh::triface::tet, and tetgenmesh::triface::ver.
Referenced by add_steinerpt_in_segment(), addsteiner4recoversegment(), formregion(), getedge(), getvertexstar(), insertpoint(), recoveredgebyflips(), recoverfacebyflips(), recoversubfaces(), reduceedgesatvertex(), refineregion(), removevertexbyflips(), scoutsegment(), and scoutsubface().
void tetgenmesh::pointdealloc (point dyingpoint)
Definition at line 4390 of file tetgen.cxx.
View newest version in sPHENIX GitHub at line 4390 of file tetgen.cxx
References DEADVERTEX, tetgenmesh::memorypool::dealloc(), points, and setpointtype().
Referenced by add_steinerpt_in_schoenhardtpoly(), add_steinerpt_in_segment(), jettisonnodes(), refineregion(), splitsegment(), splitsliver(), splitsubface(), splittetrahedron(), and suppressbdrysteinerpoint().
int tetgenmesh::pointgeomtag (point pt) inline
Definition at line 3114 of file tetgen.h.
View newest version in sPHENIX GitHub at line 3114 of file tetgen.h
References pointmarkindex.
Referenced by outnodes().
REAL tetgenmesh::pointgeomuv (point pt, int i) inline
Definition at line 3124 of file tetgen.h.
View newest version in sPHENIX GitHub at line 3124 of file tetgen.h
References pointparamindex.
Referenced by outnodes().
int tetgenmesh::pointmark (point pt) inline
Definition at line 3092 of file tetgen.h.
View newest version in sPHENIX GitHub at line 3092 of file tetgen.h
References pointmarkindex.
Referenced by addsteiner4recoversegment(), calculateabovepoint(), carveholes(), checkconforming(), checkdelaunay(), checkmesh(), checkregular(), checksegments(), checkshells(), flipcertify(), flipinsertfacet(), formcavity(), getedge(), identifypscedges(), incrementaldelaunay(), initialdelaunay(), insertpoint(), insertpoint_cdt(), insphere_s(), interecursive(), interpolatemeshsize(), makepoint2submap(), meshsurface(), orient4d_s(), outedges(), outelements(), outfaces(), outhullfaces(), outmesh2medit(), outmesh2vtk(), outsmesh(), outsubfaces(), outsubsegments(), outvoronoi(), qualitystatistics(), randomsample(), reconstructmesh(), recoverfacebyflips(), recoversegments(), recoversubfaces(), refineregion(), removevertexbyflips(), scoutsegment(), sinsertvertex(), sremovevertex(), sscoutsegment(), suppressbdrysteinerpoint(), unifysegments(), and unifysubfaces().
tetgenmesh::point tetgenmesh::pointtraverse ()
Definition at line 4404 of file tetgen.cxx.
View newest version in sPHENIX GitHub at line 4404 of file tetgen.cxx
References DEADVERTEX, points, pointtype(), and tetgenmesh::memorypool::traverse().
Referenced by carveholes(), checksegments(), collectremovepoints(), identifypscedges(), interpolatemeshsize(), jettisonnodes(), makeindex2pointmap(), outmesh2medit(), outmesh2vtk(), outmetrics(), outnodes(), outvoronoi(), and reconstructmesh().
enum tetgenmesh::verttype tetgenmesh::pointtype (point pt) inline
Definition at line 3103 of file tetgen.h.
View newest version in sPHENIX GitHub at line 3103 of file tetgen.h
References pointmarkindex.
Referenced by addsteiner4recoversegment(), carveholes(), checksegments(), collectremovepoints(), flip22(), flip31(), getsteinerptonsegment(), identifypscedges(), improvequalitybysmoothing(), incrementaldelaunay(), initialdelaunay(), insertconstrainedpoints(), jettisonnodes(), lawsonflip3d(), makefacetverticesmap(), meshcoarsening(), meshsurface(), outnodes(), outvoronoi(), pointtraverse(), reconstructmesh(), recoverfacebyflips(), removevertexbyflips(), sinsertvertex(), splitsegment(), splitsubface(), suppressbdrysteinerpoint(), suppresssteinerpoints(), triangulate(), and unifysegments().
void tetgenmesh::printfcomma (unsigned long n)
Definition at line 26959 of file tetgen.cxx.
View newest version in sPHENIX GitHub at line 26959 of file tetgen.cxx
References printf().
Referenced by memorystatistics().
void tetgenmesh::projpt2edge (REAL * p, REAL * e1, REAL * e2, REAL * prj)
Definition at line 6361 of file tetgen.cxx.
View newest version in sPHENIX GitHub at line 6361 of file tetgen.cxx
References dot(), REAL, v1, and v2.
Referenced by checkseg4encroach(), and getsteinerptonsegment().
void tetgenmesh::projpt2face (REAL * p, REAL * f1, REAL * f2, REAL * f3, REAL * prj)
Definition at line 6391 of file tetgen.cxx.
View newest version in sPHENIX GitHub at line 6391 of file tetgen.cxx
References dot(), facenormal(), REAL, and v1.
Referenced by checkfac4encroach().
void tetgenmesh::puninfect (point pt) inline
Definition at line 3139 of file tetgen.h.
View newest version in sPHENIX GitHub at line 3139 of file tetgen.h
References pointmarkindex.
Referenced by collectremovepoints(), delaunizecavity(), facetfacetadjacent(), formcavity(), getvertexstar(), incrementalflip(), insertpoint(), makefacetverticesmap(), meshsurface(), outvoronoi(), segfacetadjacent(), and triangulate().
void tetgenmesh::punmarktest (point pt) inline
Definition at line 3154 of file tetgen.h.
View newest version in sPHENIX GitHub at line 3154 of file tetgen.h
References pointmarkindex.
Referenced by constrainedfacets().
void tetgenmesh::punmarktest2 (point pt) inline
Definition at line 3166 of file tetgen.h.
View newest version in sPHENIX GitHub at line 3166 of file tetgen.h
References pointmarkindex.
Referenced by flipinsertfacet().
void tetgenmesh::punmarktest3 (point pt) inline
Definition at line 3178 of file tetgen.h.
View newest version in sPHENIX GitHub at line 3178 of file tetgen.h
References pointmarkindex.
Referenced by flipinsertfacet().
void tetgenmesh::qualitystatistics ()
Definition at line 27889 of file tetgen.cxx.
View newest version in sPHENIX GitHub at line 27889 of file tetgen.cxx
References apex(), b, tetgenbehavior::convex, dest(), dot(), dummypoint, Acts::UnitConstants::e, elemattribute(), facenormal(), fsym(), H, interiorangle(), longest, lu_decmp(), lu_solve(), minfaceang, minfacetdihed, charm_jet_strange_helicity::N, numelemattrib, org(), orient3dfast(), p, PI, pointmark(), printf(), REAL, tetgenmesh::triface::tet, tetprismvol(), tetrahedrons, tetrahedrontraverse(), tetgenmesh::memorypool::traversalinit(), tetgenmesh::triface::ver, xmax, xmin, ymax, ymin, zmax, and zmin.
Referenced by statistics().
unsigned long tetgenmesh::randomnation (unsigned int choices)
Definition at line 10855 of file tetgen.cxx.
View newest version in sPHENIX GitHub at line 10855 of file tetgen.cxx
References randomseed.
Referenced by constraineddelaunay(), fillcavity(), fillregion(), finddirection(), formcavity(), insertpoint(), locate(), randomsample(), recoverboundary(), refineregion(), slocate(), smoothpoint(), and sscoutsegment().
void tetgenmesh::randomsample (point searchpt, triface * searchtet)
Definition at line 10885 of file tetgen.cxx.
View newest version in sPHENIX GitHub at line 10885 of file tetgen.cxx
References tetgenmesh::memorypool::alignbytes, b, tetgenmesh::memorypool::firstblock, tetgenmesh::memorypool::itemwords, longest, tetgenmesh::memorypool::maxitems, nonconvex, org(), pointmark(), printf(), randomnation(), REAL, recenttet, samples, tetgenmesh::triface::tet, tetgenbehavior::tetrahedraperblock, tetrahedrons, tetgenmesh::triface::ver, and tetgenbehavior::verbose.
Referenced by carveholes(), insertpoint(), and scoutpoint().
void tetgenmesh::reconstructmesh ()
Definition at line 22520 of file tetgen.cxx.
View newest version in sPHENIX GitHub at line 22520 of file tetgen.cxx
References apex(), b, bond(), checkconstraints, checksubfaceflag, checksubsegflag, tetgenbehavior::convex, decode(), dest(), distance(), dummypoint, tetgenio::edgelist, tetgenio::edgemarkerlist, elemattribute(), encode(), enext(), enextself(), eprev(), tetgenbehavior::epsilon, esym(), esymself(), facedihedral(), tetgenbehavior::facet_ang_tol, tetgenio::facetconstraintlist, FACETVERTEX, tetgenio::firstnumber, fnextself(), FREEFACETVERTEX, FREESEGVERTEX, FREEVOLVERTEX, fsym(), fsymself(), getedge(), hullsize, in, insegments, ishulltet(), tetgenmesh::memorypool::items, k, makeindex2pointmap(), makepoint2submap(), makeshellface(), maketetrahedron(), marker(), tetgenbehavior::nobisect, nonconvex, tetgenio::numberofcorners, tetgenio::numberofedges, tetgenio::numberoffacetconstraints, tetgenio::numberofpoints, tetgenio::numberofsegmentconstraints, tetgenio::numberoftetrahedra, tetgenio::numberoftetrahedronattributes, tetgenio::numberoftrifaces, oppo(), org(), orient3d(), p, PI, point2tet(), pointmark(), points, pointtraverse(), pointtype(), printf(), tetgenbehavior::quality, tetgenbehavior::quiet, REAL, recenttet, RIDGEVERTEX, sapex(), sbond(), sbond1(), sdest(), tetgenio::segmentconstraintlist, sencode(), senext2self(), senextself(), sesymself(), setareabound(), setelemattribute(), setpoint2sh(), setpoint2tet(), setpointtype(), setshellmark(), setshvertices, setvertices, setvolumebound(), tetgenmesh::face::sh, shellfacetraverse(), shellmark(), tetgenmesh::face::shver, sorg(), spivot(), spivotself(), ssbond1(), sspivot(), sstbond1(), st_facref_count, st_segref_count, st_volref_count, stpivot(), subfaces, subsegs, tetgenmesh::triface::tet, tetgenio::tetrahedronattributelist, tetgenio::tetrahedronlist, tetrahedrons, tetrahedrontraverse(), tetgenio::tetrahedronvolumelist, tetgenmesh::memorypool::traversalinit(), tetgenio::trifacelist, tetgenio::trifacemarkerlist, tsbond(), tspivot(), tssbond1(), tetgenbehavior::varvolume, tetgenmesh::triface::ver, Acts::Test::volume, and VOLVERTEX.
Referenced by tetrahedralize().
void tetgenmesh::recoverboundary (clock_t & tv)
Definition at line 21586 of file tetgen.cxx.
View newest version in sPHENIX GitHub at line 21586 of file tetgen.cxx
References autofliplinklevel, b, checksubfaceflag, checksubsegflag, fastlookup, tetgenbehavior::fliplinklevel, tetgenbehavior::fliplinklevelinc, tetgenmesh::memorypool::items, Acts::UnitConstants::ms, tetgenmesh::arraypool::newindex(), tetgenmesh::arraypool::objects, printf(), tetgenbehavior::quiet, randomnation(), recoversegments(), recoversubfaces(), removevertexbyflips(), tetgenmesh::arraypool::restart(), Acts::UnitConstants::s, tetgenmesh::face::sh, shellfacetraverse(), st_facref_count, st_segref_count, st_volref_count, subfaces, subfacstack, subsegs, subsegstack, subvertstack, tetgenmesh::arraypool::totalmemory, totalworkmemory, tetgenmesh::memorypool::traversalinit(), and tetgenbehavior::verbose.
Referenced by tetrahedralize().
void tetgenmesh::recoverdelaunay ()
Definition at line 25843 of file tetgen.cxx.
View newest version in sPHENIX GitHub at line 25843 of file tetgen.cxx
References autofliplinklevel, b, tetgenmesh::flipconstraints::bak_tetprism_vol, cavetetlist, tetgenmesh::flipconstraints::collectnewtets, decode(), tetgenbehavior::delmaxfliplevel, Acts::UnitConstants::e, tetgenmesh::flipconstraints::enqflag, tetgenbehavior::epsilon, facemarked(), fastlookup, tetgenmesh::badface::fdest, tetgenbehavior::fliplinklevel, tetgenbehavior::fliplinklevelinc, flippool, flippush(), flipstack, tetgenbehavior::flipstarsize, tetgenmesh::badface::forg, getedge(), isdeadtet(), tetgenmesh::memorypool::items, lawsonflip3d(), tetgenmesh::arraypool::newindex(), tetgenmesh::arraypool::objects, printf(), tetgenbehavior::quiet, tetgenmesh::flipconstraints::remove_ndelaunay_edge, removeedgebyflips(), tetgenmesh::arraypool::restart(), tetgenmesh::triface::tet, tetgenmesh::flipconstraints::tetprism_vol_sum, tetprism_vol_sum, tetprismvol(), tetrahedrons, tetrahedrontraverse(), tetgenmesh::memorypool::traversalinit(), tetgenmesh::badface::tt, tetgenmesh::flipconstraints::unflip, unflipqueue, tetgenmesh::triface::ver, and tetgenbehavior::verbose.
Referenced by tetrahedralize().
int tetgenmesh::recoveredgebyflips (point startpt, point endpt, triface * searchtet, int fullsearch)
Definition at line 18658 of file tetgen.cxx.
View newest version in sPHENIX GitHub at line 18658 of file tetgen.cxx
References ACROSSEDGE, ACROSSFACE, ACROSSVERT, apex(), tetgenmesh::flipconstraints::checkflipeligibility, dest(), DISJOINT, enextesym(), enextesymself(), enextself(), eprevesym(), tetgenmesh::badface::fapex, tetgenmesh::badface::fdest, finddirection(), fnextself(), tetgenmesh::badface::foppo, tetgenmesh::badface::forg, fsymself(), oppo(), org(), charm_jet_strange_helicity::pc, point2tetorg(), pos(), printf(), removeedgebyflips(), removefacebyflips(), tetgenmesh::flipconstraints::seg, SHAREVERT, terminatetetgen(), tetgenmesh::triface::tet, tri_edge_test(), and tetgenmesh::triface::ver.
Referenced by recoversegments(), and recoversubfaces().
int tetgenmesh::recoverfacebyflips (point pa, point pb, point pc, face * searchsh, triface * searchtet)
Definition at line 19552 of file tetgen.cxx.
View newest version in sPHENIX GitHub at line 19552 of file tetgen.cxx
References ACROSSEDGE, ACROSSFACE, apex(), b, cavesegshlist, caveshbdlist, caveshlist, tetgenmesh::flipconstraints::checkflipeligibility, dest(), dummypoint, edestoppo(), eprevself(), tetgenmesh::flipconstraints::fac, farsdest(), farsorg(), fastlookup, finddirection(), fnextself(), FREEFACETVERTEX, FREESEGVERTEX, FREEVOLVERTEX, issubseg, tetgenmesh::arraypool::newindex(), tetgenmesh::arraypool::objects, ONFACE, oppo(), charm_jet_strange_helicity::pc, point2tetorg(), pointmark(), pointtype(), printf(), tetgenbehavior::quiet, removeedgebyflips(), tetgenmesh::arraypool::restart(), setpointtype(), tetgenmesh::face::sh, shellfacedealloc(), shellmark(), sinsertvertex(), spivot(), st_facref_count, st_volref_count, subfaces, subfacstack, subvertstack, terminatetetgen(), tetgenmesh::triface::tet, TOUCHFACE, tri_edge_test(), and tsspivot1().
Referenced by recoversubfaces().
int tetgenmesh::recoversegments (arraypool * misseglist, int fullsearch, int steinerflag)
Definition at line 19434 of file tetgen.cxx.
View newest version in sPHENIX GitHub at line 19434 of file tetgen.cxx
References addsteiner4recoversegment(), autofliplinklevel, b, fastlookup, tetgenbehavior::fliplinklevel, fnextself(), tetgenmesh::arraypool::newindex(), tetgenmesh::arraypool::objects, pointmark(), printf(), recoveredgebyflips(), sdest(), sorg(), sstbond1(), sstpivot1(), st_segref_count, st_volref_count, subsegstack, tetgenmesh::triface::tet, tssbond1(), and tetgenbehavior::verbose.
Referenced by recoverboundary().
int tetgenmesh::recoversubfaces (arraypool * misshlist, int steinerflag)
Definition at line 19715 of file tetgen.cxx.
View newest version in sPHENIX GitHub at line 19715 of file tetgen.cxx
References ACROSSVERT, tetgenmesh::insertvertexflags::assignmeshsize, autofliplinklevel, b, tetgenmesh::insertvertexflags::bowywat, tetgenmesh::insertvertexflags::chkencflag, dest(), fastlookup, finddirection(), tetgenbehavior::fliplinklevel, fnextself(), FREEFACETVERTEX, fsymself(), tetgenmesh::insertvertexflags::iloc, insertpoint(), tetgenmesh::insertvertexflags::lawson, makepoint(), makeshellface(), tetgenbehavior::metric, tetgenmesh::arraypool::newindex(), tetgenmesh::arraypool::objects, ONEDGE, ONFACE, OUTSIDE, point2tetorg(), pointmark(), printf(), recoveredgebyflips(), recoverfacebyflips(), tetgenmesh::insertvertexflags::rejflag, tetgenmesh::insertvertexflags::respectbdflag, sapex(), tetgenmesh::insertvertexflags::sbowywat, sdest(), senextself(), sesymself(), setshvertices, tetgenmesh::face::sh, shellfacedealloc(), tetgenmesh::insertvertexflags::sloc, smarktest2(), smarktest2ed(), sorg(), spivot(), spivotself(), tetgenmesh::insertvertexflags::splitbdflag, ssbond(), ssdissolve(), sspivot(), sstbond1(), sstpivot1(), st_facref_count, steinerleft, stpivot(), subfacstack, subsegs, subvertstack, terminatetetgen(), tetgenmesh::triface::tet, tsbond(), tssbond1(), tssdissolve1(), tetgenmesh::insertvertexflags::validflag, and tetgenbehavior::verbose.
Referenced by recoverboundary().
int tetgenmesh::reduceedgesatvertex (point startpt, arraypool * endptlist)
Definition at line 20256 of file tetgen.cxx.
View newest version in sPHENIX GitHub at line 20256 of file tetgen.cxx
References ACROSSVERT, tetgenmesh::flipconstraints::checkflipeligibility, dest(), dummypoint, fastlookup, finddirection(), getedge(), INTERSECT, issubseg, n, nonconvex, tetgenmesh::arraypool::objects, point2tetorg(), removeedgebyflips(), and tetgenmesh::flipconstraints::remvert.
Referenced by removevertexbyflips().
void tetgenmesh::refineregion (face & splitsh, arraypool * cavpoints, arraypool * cavfaces, arraypool * cavshells, arraypool * newtets, arraypool * crosstets, arraypool * misfaces)
Definition at line 17772 of file tetgen.cxx.
View newest version in sPHENIX GitHub at line 17772 of file tetgen.cxx
References ACROSSEDGE, ACROSSFACE, tetgenmesh::insertvertexflags::assignmeshsize, b, tetgenmesh::insertvertexflags::bowywat, tetgenmesh::insertvertexflags::cdtflag, encseglist, ENCSEGMENT, fastlookup, fnextself(), FREEFACETVERTEX, FREESEGVERTEX, getsteinerptonsegment(), tetgenmesh::insertvertexflags::iloc, insertpoint_cdt(), issubseg, tetgenmesh::memorypool::items, makepoint(), tetgenbehavior::metric, tetgenmesh::arraypool::objects, ONEDGE, OUTSIDE, point2tetorg(), pointdealloc(), pointmark(), points, printf(), randomnation(), tetgenmesh::insertvertexflags::rejflag, tetgenmesh::arraypool::restart(), sapex(), tetgenmesh::insertvertexflags::sbowywat, scoutsegment(), sdest(), SHAREEDGE, tetgenmesh::insertvertexflags::sloc, sorg(), sstbond1(), sstpivot1(), st_facref_count, st_segref_count, steinerleft, subsegstack, tetgenmesh::triface::tet, tssbond1(), and tetgenbehavior::verbose.
Referenced by constrainedfacets().
int tetgenmesh::removeedgebyflips (triface * flipedge, flipconstraints * fc)
Definition at line 18500 of file tetgen.cxx.
View newest version in sPHENIX GitHub at line 18500 of file tetgen.cxx
References b, caveencseglist, checksubsegflag, tetgenmesh::flipconstraints::collectencsegflag, flipnm(), flipnm_post(), tetgenbehavior::flipstarsize, fnextself(), issubseg, n, tetgenmesh::arraypool::newindex(), setelemcounter(), sinfect(), sinfected(), tetgenmesh::triface::tet, tsspivot1(), and tetgenmesh::flipconstraints::unflip.
Referenced by add_steinerpt_in_segment(), improvequalitybyflips(), recoverdelaunay(), recoveredgebyflips(), recoverfacebyflips(), reduceedgesatvertex(), and removefacebyflips().
int tetgenmesh::removefacebyflips (triface * flipface, flipconstraints * fc)
Definition at line 18589 of file tetgen.cxx.
View newest version in sPHENIX GitHub at line 18589 of file tetgen.cxx
References apex(), checksubfaceflag, dest(), enext(), eprev(), flip23(), fsym(), issubface, oppo(), org(), orient3d(), charm_jet_strange_helicity::pc, REAL, and removeedgebyflips().
Referenced by add_steinerpt_in_segment(), and recoveredgebyflips().
long tetgenmesh::removeslivers (int chkencflag)
Definition at line 26681 of file tetgen.cxx.
View newest version in sPHENIX GitHub at line 26681 of file tetgen.cxx
References b, badtetrahedrons, tetgenmesh::badface::cent, cosslidihed, edge2ver, tetgenmesh::badface::fapex, fastlookup, tetgenmesh::badface::fdest, tetgenmesh::badface::foppo, tetgenmesh::badface::forg, gettetrahedron(), k, tetgenmesh::badface::key, tetgenmesh::arraypool::newindex(), tetgenmesh::arraypool::objects, printf(), REAL, tetgenmesh::arraypool::restart(), tetgenmesh::memorypool::restart(), splitsliver(), steinerleft, tetgenmesh::triface::tet, tetalldihedral(), tetgenmesh::memorypool::traversalinit(), tetgenmesh::memorypool::traverse(), tetgenmesh::badface::tt, unflipqueue, unmarktest2(), tetgenmesh::triface::ver, and tetgenbehavior::verbose.
Referenced by optimizemesh().
int tetgenmesh::removevertexbyflips (point steinerpt)
Definition at line 20345 of file tetgen.cxx.
View newest version in sPHENIX GitHub at line 20345 of file tetgen.cxx
References apex(), b, caveshbdlist, cavetetlist, cavetetvertlist, checksubfaceflag, dest(), enextself(), eprev(), eprevself(), esym(), esymself(), finddirection(), flip23(), flip32(), flip41(), fnext(), fnextself(), FREEFACETVERTEX, FREESEGVERTEX, FREEVOLVERTEX, fsym(), fsymself(), getedge(), getvertexstar(), INTETRAHEDRON, issubface, n, tetgenmesh::arraypool::objects, ONEDGE, ONFACE, oppo(), org(), point2sh(), point2tetorg(), pointmark(), pointtype(), printf(), reduceedgesatvertex(), tetgenmesh::arraypool::restart(), sapex(), sdecode(), sdest(), senext(), senext2(), sesymself(), setpointtype(), tetgenmesh::face::sh, tetgenmesh::face::shver, sorg(), spivot(), spivotself(), sremovevertex(), sstbond1(), sstdissolve1(), sstpivot1(), st_facref_count, st_segref_count, st_volref_count, stdissolve(), steinerleft, stpivot(), tetgenmesh::triface::tet, tsbond(), tsdissolve(), tssbond1(), tssdissolve1(), tsspivot1(), UNUSEDVERTEX, unuverts, tetgenbehavior::verbose, and VOLVERTEX.
Referenced by lawsonflip3d(), meshcoarsening(), recoverboundary(), suppressbdrysteinerpoint(), and suppresssteinerpoints().
void tetgenmesh::repairbadtets (int chkencflag)
Definition at line 25322 of file tetgen.cxx.
View newest version in sPHENIX GitHub at line 25322 of file tetgen.cxx
References b, badtetrahedrons, checktet4split(), tetgenmesh::memorypool::dealloc(), isdeadtet(), tetgenmesh::memorypool::items, marktest2ed(), printf(), REAL, tetgenmesh::memorypool::restart(), splittetrahedron(), steinerleft, tetgenmesh::memorypool::traversalinit(), tetgenmesh::memorypool::traverse(), unmarktest2(), tetgenmesh::triface::ver, and tetgenbehavior::verbose.
Referenced by delaunayrefinement().
void tetgenmesh::repairencfacs (int chkencflag)
Definition at line 24878 of file tetgen.cxx.
View newest version in sPHENIX GitHub at line 24878 of file tetgen.cxx
References b, badsubfacs, checkfac4split(), tetgenmesh::memorypool::dealloc(), tetgenmesh::memorypool::items, printf(), REAL, tetgenmesh::memorypool::restart(), tetgenmesh::face::sh, tetgenmesh::face::shver, smarktest2ed(), splitsubface(), steinerleft, sunmarktest2(), tetgenmesh::memorypool::traversalinit(), tetgenmesh::memorypool::traverse(), and tetgenbehavior::verbose.
Referenced by delaunayrefinement(), and splittetrahedron().
void tetgenmesh::repairencsegs (int chkencflag)
Definition at line 24413 of file tetgen.cxx.
View newest version in sPHENIX GitHub at line 24413 of file tetgen.cxx
References b, badsubsegs, checkseg4split(), tetgenmesh::memorypool::dealloc(), tetgenmesh::memorypool::items, printf(), tetgenmesh::memorypool::restart(), tetgenmesh::face::sh, tetgenmesh::face::shver, smarktest2ed(), splitsegment(), steinerleft, sunmarktest2(), tetgenmesh::memorypool::traversalinit(), tetgenmesh::memorypool::traverse(), and tetgenbehavior::verbose.
Referenced by delaunayrefinement(), splitsubface(), and splittetrahedron().
void tetgenmesh::restorecavity (arraypool * crosstets, arraypool * topnewtets, arraypool * botnewtets, arraypool * missingshbds)
Definition at line 16719 of file tetgen.cxx.
View newest version in sPHENIX GitHub at line 16719 of file tetgen.cxx
References bond(), encode(), fastlookup, fnextself(), fsym(), infected(), tetgenmesh::arraypool::objects, recenttet, tetgenmesh::arraypool::restart(), setpoint2tet(), tetgenmesh::face::sh, shellfacedealloc(), sinfected(), ssdissolve(), sspivot(), sstpivot1(), subsegs, tetgenmesh::triface::tet, tetrahedrondealloc(), tssdissolve1(), uninfect(), and tetgenmesh::triface::ver.
Referenced by constrainedfacets().
tetgenmesh::point tetgenmesh::sapex (face & s) inline
Definition at line 2721 of file tetgen.h.
View newest version in sPHENIX GitHub at line 2721 of file tetgen.h
References sapexpivot, tetgenmesh::face::sh, and tetgenmesh::face::shver.
Referenced by carveholes(), checkfac4split(), checksegments(), checkshells(), flip22(), formcavity(), identifypscedges(), insertpoint(), lawsonflip(), makefacetverticesmap(), mergefacets(), outsmesh(), outsubfaces(), reconstructmesh(), recoversubfaces(), refineregion(), removevertexbyflips(), scoutcrossedge(), scoutsubface(), sinsertvertex(), slocate(), splitsubface(), sremovevertex(), sscoutsegment(), suppressbdrysteinerpoint(), unifysegments(), and unifysubfaces().
void tetgenmesh::sbond (face & s1, face & s2) inline
Definition at line 2670 of file tetgen.h.
View newest version in sPHENIX GitHub at line 2670 of file tetgen.h
References sencode(), tetgenmesh::face::sh, and tetgenmesh::face::shver.
Referenced by fillcavity(), fillregion(), identifypscedges(), reconstructmesh(), sinsertvertex(), sremovevertex(), and unifysegments().
void tetgenmesh::sbond1 (face & s1, face & s2) inline
Definition at line 2680 of file tetgen.h.
View newest version in sPHENIX GitHub at line 2680 of file tetgen.h
References sencode(), tetgenmesh::face::sh, and tetgenmesh::face::shver.
Referenced by carveholes(), fillcavity(), fillregion(), flip22(), flip31(), reconstructmesh(), sinsertvertex(), sremovevertex(), and unifysegments().
void tetgenmesh::scarveholes (int holes, REAL * holelist)
Definition at line 13295 of file tetgen.cxx.
View newest version in sPHENIX GitHub at line 13295 of file tetgen.cxx
References caveshbdlist, caveshlist, fastlookup, isshsubseg, tetgenmesh::arraypool::newindex(), tetgenmesh::arraypool::objects, OUTSIDE, recentsh, tetgenmesh::arraypool::restart(), sdissolve(), senextself(), tetgenmesh::face::sh, shellfacedealloc(), tetgenmesh::face::shver, sinfect(), sinfected(), slocate(), smarktest(), smarktested(), spivot(), subfaces, and sunmarktest().
Referenced by triangulate().
int tetgenmesh::scoutcrossedge (triface & crosstet, arraypool * missingshbds, arraypool * missingshs)
Definition at line 15471 of file tetgen.cxx.
View newest version in sPHENIX GitHub at line 15471 of file tetgen.cxx
References ACROSSEDGE, ACROSSFACE, apex(), dummypoint, edestoppo(), esymself(), fastlookup, fnextself(), issubseg, tetgenmesh::arraypool::objects, oppo(), orient3d(), charm_jet_strange_helicity::pc, pmarktested(), REAL, sapex(), sdest(), sorg(), sspivot(), sstpivot1(), terminatetetgen(), tetgenmesh::triface::tet, and tri_edge_test().
Referenced by constrainedfacets().
int tetgenmesh::scoutpoint (point searchpt, triface * searchtet, int randflag)
Definition at line 23145 of file tetgen.cxx.
View newest version in sPHENIX GitHub at line 23145 of file tetgen.cxx
References apex(), b, tetgenbehavior::convex, dest(), enextself(), eprevself(), tetgenbehavior::epsilon, esymself(), fsymself(), INTETRAHEDRON, locate(), nonregularcount, ONEDGE, ONFACE, ONVERTEX, oppo(), org(), orient3dfast(), OUTSIDE, charm_jet_strange_helicity::pc, randomsample(), REAL, recenttet, tetgenmesh::triface::tet, tetrahedrons, tetrahedrontraverse(), tetgenmesh::memorypool::traversalinit(), and triarea().
Referenced by insertconstrainedpoints(), insertpoint(), and interpolatemeshsize().
enum tetgenmesh::interresult tetgenmesh::scoutsegment (point startpt, point endpt, triface * searchtet, point * refpt, arraypool * intfacelist)
Definition at line 14913 of file tetgen.cxx.
View newest version in sPHENIX GitHub at line 14913 of file tetgen.cxx
References ACROSSEDGE, ACROSSFACE, ACROSSSEG, ACROSSSUB, ACROSSVERT, apex(), b, checksubfaceflag, dest(), DISJOINT, dummypoint, enextesym(), enextesymself(), enextself(), eprevesym(), finddirection(), fnextself(), fsym(), fsymself(), interiorangle(), issubface, issubseg, oppo(), org(), charm_jet_strange_helicity::pc, PI, point2tetorg(), pointmark(), pos(), printf(), REAL, SHAREEDGE, tri_edge_test(), tetgenmesh::triface::ver, and tetgenbehavior::verbose.
Referenced by constrainedfacets(), delaunizesegments(), and refineregion().
enum tetgenmesh::interresult tetgenmesh::scoutsubface (face * searchsh, triface * searchtet)
Definition at line 15284 of file tetgen.cxx.
View newest version in sPHENIX GitHub at line 15284 of file tetgen.cxx
References ACROSSVERT, apex(), COLLISIONFACE, dest(), enextself(), finddirection(), fnextself(), fsymself(), issubface, charm_jet_strange_helicity::pc, point2tetorg(), printf(), sapex(), sdest(), sesymself(), tetgenmesh::face::sh, SHAREFACE, sorg(), terminatetetgen(), tetgenmesh::triface::tet, TOUCHEDGE, tsbond(), and tspivot().
Referenced by constrainedfacets(), and delaunizecavity().
void tetgenmesh::sdecode (shellface sptr, face & s) inline
Definition at line 2654 of file tetgen.h.
View newest version in sPHENIX GitHub at line 2654 of file tetgen.h
References tetgenmesh::face::sh, and tetgenmesh::face::shver.
Referenced by carvecavity(), checksegments(), getsteinerptonsegment(), insertpoint(), outnodes(), point2shorg(), removevertexbyflips(), spivot(), spivotself(), splitsegment(), splitsubface(), sspivot(), suppressbdrysteinerpoint(), tspivot(), and tsspivot1().
tetgenmesh::point tetgenmesh::sdest (face & s) inline
Definition at line 2716 of file tetgen.h.
View newest version in sPHENIX GitHub at line 2716 of file tetgen.h
References sdestpivot, tetgenmesh::face::sh, and tetgenmesh::face::shver.
Referenced by add_steinerpt_in_segment(), addsteiner4recoversegment(), carveholes(), checkfac4split(), checkseg4split(), checksegments(), checkshells(), constrainedfacets(), delaunizesegments(), farsdest(), fillcavity(), flip22(), flip31(), flipshpush(), formcavity(), formregion(), getsteinerptonsegment(), identifypscedges(), insertpoint(), lawsonflip(), lawsonflip3d(), makesegmentendpointsmap(), mergefacets(), outmesh2medit(), outsmesh(), outsubfaces(), outsubsegments(), reconstructmesh(), recoversegments(), recoversubfaces(), refineregion(), removevertexbyflips(), scoutcrossedge(), scoutsubface(), sinsertvertex(), slocate(), splitsegment(), splitsubface(), sremovevertex(), sscoutsegment(), suppressbdrysteinerpoint(), triangulate(), unifysegments(), and unifysubfaces().
void tetgenmesh::sdissolve (face & s) inline
Definition at line 2688 of file tetgen.h.
View newest version in sPHENIX GitHub at line 2688 of file tetgen.h
References tetgenmesh::face::sh, and tetgenmesh::face::shver.
Referenced by carveholes(), flip22(), scarveholes(), sinsertvertex(), and sremovevertex().
int tetgenmesh::segfacetadjacent (face * checkseg, face * checksh)
Definition at line 24063 of file tetgen.cxx.
View newest version in sPHENIX GitHub at line 24063 of file tetgen.cxx
References facetverticeslist, getfacetindex(), idx2facetlist, pinfect(), pinfected(), puninfect(), and segmentendpointslist.
Referenced by splitsegment(), and splitsubface().
int tetgenmesh::segsegadjacent (face * seg1, face * seg2)
Definition at line 24045 of file tetgen.cxx.
View newest version in sPHENIX GitHub at line 24045 of file tetgen.cxx
References getfacetindex(), and segmentendpointslist.
Referenced by splitsegment().
tetgenmesh::shellface tetgenmesh::sencode (face & s) inline
Definition at line 2659 of file tetgen.h.
View newest version in sPHENIX GitHub at line 2659 of file tetgen.h
References tetgenmesh::face::sh, and tetgenmesh::face::shver.
Referenced by flip22(), flip31(), identifypscedges(), reconstructmesh(), sbond(), sbond1(), sinsertvertex(), sremovevertex(), ssbond(), ssbond1(), tssbond1(), and unifysegments().
tetgenmesh::shellface tetgenmesh::sencode2 (shellface * sh, int shver) inline
Definition at line 2663 of file tetgen.h.
View newest version in sPHENIX GitHub at line 2663 of file tetgen.h
Referenced by tsbond().
void tetgenmesh::senext (face & s1, face & s2) inline
Definition at line 2762 of file tetgen.h.
View newest version in sPHENIX GitHub at line 2762 of file tetgen.h
References tetgenmesh::face::sh, tetgenmesh::face::shver, and snextpivot.
Referenced by checksegments(), farsdest(), flip22(), flip31(), makesegmentendpointsmap(), removevertexbyflips(), sinsertvertex(), sremovevertex(), sscoutsegment(), and suppressbdrysteinerpoint().
void tetgenmesh::senext2 (face & s1, face & s2) inline
Definition at line 2773 of file tetgen.h.
View newest version in sPHENIX GitHub at line 2773 of file tetgen.h
References tetgenmesh::face::sh, tetgenmesh::face::shver, and snextpivot.
Referenced by checksegments(), farsorg(), flip22(), flip31(), identifypscedges(), makesegmentendpointsmap(), removevertexbyflips(), sinsertvertex(), sremovevertex(), sscoutsegment(), and suppressbdrysteinerpoint().
void tetgenmesh::senext2self (face & s) inline
Definition at line 2779 of file tetgen.h.
View newest version in sPHENIX GitHub at line 2779 of file tetgen.h
References tetgenmesh::face::shver, and snextpivot.
Referenced by flip41(), reconstructmesh(), sinsertvertex(), slocate(), sremovevertex(), sscoutsegment(), suppressbdrysteinerpoint(), and unifysegments().
void tetgenmesh::senextself (face & s) inline
Definition at line 2768 of file tetgen.h.
View newest version in sPHENIX GitHub at line 2768 of file tetgen.h
References tetgenmesh::face::shver, and snextpivot.
Referenced by carveholes(), checkshells(), constrainedfacets(), fillregion(), formregion(), identifypscedges(), insertpoint(), lawsonflip3d(), makefacetverticesmap(), makesegmentendpointsmap(), reconstructmesh(), recoversubfaces(), scarveholes(), sinsertvertex(), slocate(), sremovevertex(), suppressbdrysteinerpoint(), and triangulate().
void tetgenmesh::sesym (face & s1, face & s2) inline
Definition at line 2748 of file tetgen.h.
View newest version in sPHENIX GitHub at line 2748 of file tetgen.h
References tetgenmesh::face::sh, and tetgenmesh::face::shver.
Referenced by flip41().
void tetgenmesh::sesymself (face & s) inline
Definition at line 2754 of file tetgen.h.
View newest version in sPHENIX GitHub at line 2754 of file tetgen.h
References tetgenmesh::face::shver.
Referenced by addsteiner4recoversegment(), carvecavity(), carveholes(), checkconforming(), checkfac4split(), farsdest(), farsorg(), fillcavity(), fillregion(), flip22(), flip23(), flip31(), flip32(), flip41(), formregion(), identifypscedges(), insertpoint(), lawsonflip3d(), makesegmentendpointsmap(), reconstructmesh(), recoversubfaces(), removevertexbyflips(), scoutsubface(), sinsertvertex(), slocate(), sremovevertex(), sscoutsegment(), suppressbdrysteinerpoint(), and unifysegments().
void tetgenmesh::setapex (triface & t, point p) inline
Definition at line 2463 of file tetgen.h.
View newest version in sPHENIX GitHub at line 2463 of file tetgen.h
References apexpivot, and t.
Referenced by insertpoint(), and suppressbdrysteinerpoint().
void tetgenmesh::setareabound (face & s, REAL value) inline
Definition at line 2792 of file tetgen.h.
View newest version in sPHENIX GitHub at line 2792 of file tetgen.h
References areaboundindex, REAL, and tetgenmesh::face::sh.
Referenced by fillcavity(), fillregion(), flip31(), identifypscedges(), makeshellface(), reconstructmesh(), sinsertvertex(), sremovevertex(), triangulate(), and unifysegments().
void tetgenmesh::setdest (triface & t, point p) inline
Definition at line 2459 of file tetgen.h.
View newest version in sPHENIX GitHub at line 2459 of file tetgen.h
References destpivot, and t.
Referenced by insertpoint().
void tetgenmesh::setelemattribute (tetrahedron * ptr, int attnum, REAL value) inline
Definition at line 2483 of file tetgen.h.
View newest version in sPHENIX GitHub at line 2483 of file tetgen.h
References elemattribindex, and REAL.
Referenced by carveholes(), flip23(), flip32(), insertpoint(), maketetrahedron(), and reconstructmesh().
void tetgenmesh::setelemcounter (triface & t, int value) inline
Definition at line 2610 of file tetgen.h.
View newest version in sPHENIX GitHub at line 2610 of file tetgen.h
References c, elemmarkerindex, and tetgenmesh::triface::tet.
Referenced by decreaseelemcounter(), increaseelemcounter(), and removeedgebyflips().
void tetgenmesh::setelemindex (tetrahedron * ptr, int value) inline
Definition at line 2506 of file tetgen.h.
View newest version in sPHENIX GitHub at line 2506 of file tetgen.h
References value.
Referenced by outelements(), and outvoronoi().
void tetgenmesh::setelemmarker (tetrahedron * ptr, int value) inline
Definition at line 2518 of file tetgen.h.
View newest version in sPHENIX GitHub at line 2518 of file tetgen.h
References elemmarkerindex.
Referenced by flip23(), flip32(), flip41(), and maketetrahedron().
void tetgenmesh::setfacetindex (face & f, int value) inline
Definition at line 2897 of file tetgen.h.
View newest version in sPHENIX GitHub at line 2897 of file tetgen.h
References tetgenmesh::face::sh, and shmarkindex.
Referenced by flip31(), makefacetverticesmap(), makesegmentendpointsmap(), makeshellface(), sinsertvertex(), and sremovevertex().
void tetgenmesh::setoppo (triface & t, point p) inline
Definition at line 2467 of file tetgen.h.
View newest version in sPHENIX GitHub at line 2467 of file tetgen.h
References oppopivot, and t.
Referenced by insertpoint(), and suppressbdrysteinerpoint().
void tetgenmesh::setorg (triface & t, point p) inline
Definition at line 2455 of file tetgen.h.
View newest version in sPHENIX GitHub at line 2455 of file tetgen.h
References orgpivot, and t.
Referenced by insertpoint().
void tetgenmesh::setpoint2bgmtet (point pt, tetrahedron value) inline
Definition at line 3218 of file tetgen.h.
View newest version in sPHENIX GitHub at line 3218 of file tetgen.h
References point2simindex.
Referenced by initializepools(), insertpoint(), interpolatemeshsize(), and makepoint().
void tetgenmesh::setpoint2ppt (point pt, point value) inline
Definition at line 3201 of file tetgen.h.
View newest version in sPHENIX GitHub at line 3201 of file tetgen.h
References point2simindex, and value.
Referenced by incrementaldelaunay(), initializepools(), insertpoint(), and makepoint().
void tetgenmesh::setpoint2sh (point pt, shellface value) inline
Definition at line 3209 of file tetgen.h.
View newest version in sPHENIX GitHub at line 3209 of file tetgen.h
References point2simindex, and value.
Referenced by flip22(), flip31(), identifypscedges(), initializepools(), makepoint(), reconstructmesh(), sinsertvertex(), sremovevertex(), and unifysegments().
void tetgenmesh::setpoint2tet (point pt, tetrahedron value) inline
Definition at line 3193 of file tetgen.h.
View newest version in sPHENIX GitHub at line 3193 of file tetgen.h
References point2simindex.
Referenced by carveholes(), fillcavity(), flip23(), flip32(), flip41(), initialdelaunay(), initializepools(), insertpoint(), makepoint(), outvoronoi(), reconstructmesh(), restorecavity(), and suppressbdrysteinerpoint().
void tetgenmesh::setpointgeomtag (point pt, int value) inline
Definition at line 3118 of file tetgen.h.
View newest version in sPHENIX GitHub at line 3118 of file tetgen.h
References pointmarkindex.
Referenced by transfernodes().
void tetgenmesh::setpointgeomuv (point pt, int i, REAL value) inline
Definition at line 3128 of file tetgen.h.
View newest version in sPHENIX GitHub at line 3128 of file tetgen.h
References pointparamindex, and value.
Referenced by transfernodes().
void tetgenmesh::setpointinsradius (point pt, REAL value) inline
Definition at line 3224 of file tetgen.h.
View newest version in sPHENIX GitHub at line 3224 of file tetgen.h
References pointmtrindex, sizeoftensor, and value.
Referenced by splitsegment(), splitsubface(), and splittetrahedron().
void tetgenmesh::setpointmark (point pt, int value) inline
Definition at line 3096 of file tetgen.h.
View newest version in sPHENIX GitHub at line 3096 of file tetgen.h
References pointmarkindex.
Referenced by initializepools(), jettisonnodes(), makepoint(), and outmesh2medit().
void tetgenmesh::setpointtype (point pt, enum verttype value) inline
Definition at line 3107 of file tetgen.h.
View newest version in sPHENIX GitHub at line 3107 of file tetgen.h
References pointmarkindex.
Referenced by carveholes(), flip41(), incrementaldelaunay(), initialdelaunay(), initializepools(), insertconstrainedpoints(), insertpoint(), makepoint(), meshsurface(), pointdealloc(), reconstructmesh(), recoverfacebyflips(), removevertexbyflips(), suppressbdrysteinerpoint(), transfernodes(), and triangulate().
void tetgenmesh::setsapex (face & s, point pointptr) inline
Definition at line 2736 of file tetgen.h.
View newest version in sPHENIX GitHub at line 2736 of file tetgen.h
References sapexpivot, tetgenmesh::face::sh, and tetgenmesh::face::shver.
Referenced by fillcavity(), and fillregion().
void tetgenmesh::setsdest (face & s, point pointptr) inline
Definition at line 2731 of file tetgen.h.
View newest version in sPHENIX GitHub at line 2731 of file tetgen.h
References sdestpivot, tetgenmesh::face::sh, and tetgenmesh::face::shver.
Referenced by fillcavity(), fillregion(), and formregion().
void tetgenmesh::setshellmark (face & s, int value) inline
Definition at line 2805 of file tetgen.h.
View newest version in sPHENIX GitHub at line 2805 of file tetgen.h
References tetgenmesh::face::sh, and shmarkindex.
Referenced by fillcavity(), fillregion(), flip31(), identifypscedges(), makeshellface(), reconstructmesh(), sinsertvertex(), sremovevertex(), sscoutsegment(), and triangulate().
void tetgenmesh::setsorg (face & s, point pointptr) inline
Definition at line 2726 of file tetgen.h.
View newest version in sPHENIX GitHub at line 2726 of file tetgen.h
References tetgenmesh::face::sh, tetgenmesh::face::shver, and sorgpivot.
Referenced by fillcavity(), fillregion(), and formregion().
void tetgenmesh::setvolumebound (tetrahedron * ptr, REAL value) inline
Definition at line 2494 of file tetgen.h.
View newest version in sPHENIX GitHub at line 2494 of file tetgen.h
References REAL, and volumeboundindex.
Referenced by carveholes(), flip23(), flip32(), insertpoint(), maketetrahedron(), and reconstructmesh().
void tetgenmesh::shellfacedealloc (memorypool * pool, shellface * dyingsh)
Definition at line 4355 of file tetgen.cxx.
View newest version in sPHENIX GitHub at line 4355 of file tetgen.cxx
References tetgenmesh::memorypool::dealloc().
Referenced by carveholes(), delaunizecavity(), detectinterfaces(), fillcavity(), fillregion(), flip41(), identifypscedges(), insertpoint(), insertpoint_cdt(), mergefacets(), recoverfacebyflips(), recoversubfaces(), restorecavity(), scarveholes(), sinsertvertex(), sremovevertex(), triangulate(), and unifysegments().
tetgenmesh::shellface * tetgenmesh::shellfacetraverse (memorypool * pool)
Definition at line 4370 of file tetgen.cxx.
View newest version in sPHENIX GitHub at line 4370 of file tetgen.cxx
References tetgenmesh::memorypool::traverse().
Referenced by checkconforming(), checksegments(), checkshells(), constraineddelaunay(), delaunayrefinement(), detectinterfaces(), identifypscedges(), makefacetverticesmap(), makepoint2submap(), makesegmentendpointsmap(), mergefacets(), meshsurface(), outmesh2medit(), outsmesh(), outsubfaces(), outsubsegments(), reconstructmesh(), recoverboundary(), triangulate(), and unifysegments().
int tetgenmesh::shellmark (face & s) inline
Definition at line 2800 of file tetgen.h.
View newest version in sPHENIX GitHub at line 2800 of file tetgen.h
References tetgenmesh::face::sh, and shmarkindex.
Referenced by addsteiner4recoversegment(), fillcavity(), fillregion(), flip31(), identifypscedges(), interecursive(), mergefacets(), outedges(), outfaces(), outmesh2medit(), outnodes(), outsmesh(), outsubfaces(), outsubsegments(), reconstructmesh(), recoverfacebyflips(), sinsertvertex(), sremovevertex(), triangulate(), unifysegments(), and unifysubfaces().
REAL tetgenmesh::shortdistance (REAL * p, REAL * e1, REAL * e2)
Definition at line 6235 of file tetgen.cxx.
View newest version in sPHENIX GitHub at line 6235 of file tetgen.cxx
References dot(), REAL, v1, and v2.
void tetgenmesh::sinfect (face & s) inline
Definition at line 2815 of file tetgen.h.
View newest version in sPHENIX GitHub at line 2815 of file tetgen.h
References shmarkindex.
Referenced by carvecavity(), carveholes(), fillregion(), flipnm(), formregion(), insertpoint(), interecursive(), makefacetverticesmap(), removeedgebyflips(), scarveholes(), and suppressbdrysteinerpoint().
bool tetgenmesh::sinfected (face & s) inline
Definition at line 2829 of file tetgen.h.
View newest version in sPHENIX GitHub at line 2829 of file tetgen.h
References shmarkindex.
Referenced by carvecavity(), carveholes(), checkshells(), detectinterfaces(), fillcavity(), fillregion(), flipnm(), getvertexstar(), insertpoint(), makefacetverticesmap(), removeedgebyflips(), restorecavity(), scarveholes(), and suppressbdrysteinerpoint().
int tetgenmesh::sinsertvertex (point newpt, face * searchsh, face * splitseg, int iloc, int bowywat, int rflag)
Definition at line 12083 of file tetgen.cxx.
View newest version in sPHENIX GitHub at line 12083 of file tetgen.cxx
References areabound(), b, cavesegshlist, caveshbdlist, caveshlist, checkconstraints, dummypoint, fastlookup, FREEFACETVERTEX, FREESEGVERTEX, getfacetindex(), incircle3d(), INSTAR, isshsubseg, isshtet, makeshellface(), tetgenmesh::arraypool::newindex(), tetgenmesh::arraypool::objects, ONEDGE, ONFACE, ONVERTEX, orient3d(), OUTSIDE, pointmark(), pointtype(), printf(), REAL, recentsh, tetgenmesh::arraypool::restart(), sapex(), sbond(), sbond1(), sdest(), sdissolve(), sencode(), senext(), senext2(), senext2self(), senextself(), sesymself(), setareabound(), setfacetindex(), setpoint2sh(), setshellmark(), setshvertices, tetgenmesh::face::sh, shellfacedealloc(), shellmark(), tetgenmesh::face::shver, sign(), slocate(), smarktest(), smarktested(), sorg(), spivot(), spivotself(), ssbond(), sspivot(), subfaces, subsegs, useinsertradius, and tetgenbehavior::verbose.
Referenced by insertpoint(), insertpoint_cdt(), recoverfacebyflips(), and triangulate().
enum tetgenmesh::locateresult tetgenmesh::slocate (point searchpt, face * searchsh, int aflag, int cflag, int rflag)
Definition at line 12903 of file tetgen.cxx.
View newest version in sPHENIX GitHub at line 12903 of file tetgen.cxx
References b, calculateabovepoint4(), dot(), dummypoint, ENCSEGMENT, tetgenbehavior::epsilon, facenormal(), isshsubseg, n, ONEDGE, ONFACE, ONVERTEX, orient3d(), OUTSIDE, charm_jet_strange_helicity::pc, randomnation(), REAL, sapex(), sdest(), senext2self(), senextself(), sesymself(), tetgenmesh::face::sh, sorg(), and spivot().
Referenced by scarveholes(), sinsertvertex(), splitsubface(), and triangulate().
void tetgenmesh::smarktest (face & s) inline
Definition at line 2837 of file tetgen.h.
View newest version in sPHENIX GitHub at line 2837 of file tetgen.h
References shmarkindex.
Referenced by constrainedfacets(), formregion(), insertpoint(), scarveholes(), sinsertvertex(), and sremovevertex().
void tetgenmesh::smarktest2 (face & s) inline
Definition at line 2857 of file tetgen.h.
View newest version in sPHENIX GitHub at line 2857 of file tetgen.h
References shmarkindex.
Referenced by enqueuesubface(), and recoversubfaces().
bool tetgenmesh::smarktest2ed (face & s) inline
Definition at line 2869 of file tetgen.h.
View newest version in sPHENIX GitHub at line 2869 of file tetgen.h
References shmarkindex.
Referenced by enqueuesubface(), recoversubfaces(), repairencfacs(), and repairencsegs().
void tetgenmesh::smarktest3 (face & s) inline
Definition at line 2876 of file tetgen.h.
View newest version in sPHENIX GitHub at line 2876 of file tetgen.h
References shmarkindex.
bool tetgenmesh::smarktest3ed (face & s) inline
Definition at line 2888 of file tetgen.h.
View newest version in sPHENIX GitHub at line 2888 of file tetgen.h
References shmarkindex.
bool tetgenmesh::smarktested (face & s) inline
Definition at line 2849 of file tetgen.h.
View newest version in sPHENIX GitHub at line 2849 of file tetgen.h
References shmarkindex.
Referenced by checkshells(), constrainedfacets(), formregion(), insertpoint(), insertpoint_abort(), scarveholes(), sinsertvertex(), and sremovevertex().
int tetgenmesh::smoothpoint (point smtpt, arraypool * linkfacelist, int ccw, optparameters * opm)
Definition at line 26239 of file tetgen.cxx.
View newest version in sPHENIX GitHub at line 26239 of file tetgen.cxx
References apex(), dest(), Acts::UnitConstants::e, fastlookup, tetgenmesh::optparameters::imprval, tetgenmesh::optparameters::initval, k, tetgenmesh::optparameters::max_min_aspectratio, tetgenmesh::optparameters::max_min_volume, tetgenmesh::optparameters::maxiter, tetgenmesh::optparameters::min_max_dihedangle, tetgenmesh::optparameters::numofsearchdirs, tetgenmesh::arraypool::objects, org(), orient3d(), orient3dfast(), charm_jet_strange_helicity::pc, randomnation(), REAL, tetgenmesh::optparameters::searchstep, tetgenmesh::optparameters::smthiter, tetalldihedral(), and tetaspectratio().
Referenced by add_steinerpt_in_schoenhardtpoly(), improvequalitybysmoothing(), splitsliver(), and suppresssteinerpoints().
tetgenmesh::point tetgenmesh::sorg (face & s) inline
Definition at line 2711 of file tetgen.h.
View newest version in sPHENIX GitHub at line 2711 of file tetgen.h
References tetgenmesh::face::sh, tetgenmesh::face::shver, and sorgpivot.
Referenced by add_steinerpt_in_segment(), addsteiner4recoversegment(), carveholes(), checkfac4split(), checkseg4split(), checksegments(), checkshells(), constrainedfacets(), delaunizesegments(), farsorg(), fillcavity(), fillregion(), flip22(), flip31(), flipshpush(), formcavity(), formregion(), getsteinerptonsegment(), identifypscedges(), insertpoint(), lawsonflip(), lawsonflip3d(), makesegmentendpointsmap(), mergefacets(), outmesh2medit(), outsmesh(), outsubfaces(), outsubsegments(), reconstructmesh(), recoversegments(), recoversubfaces(), refineregion(), removevertexbyflips(), scoutcrossedge(), scoutsubface(), sinsertvertex(), slocate(), splitsegment(), splitsubface(), sremovevertex(), sscoutsegment(), suppressbdrysteinerpoint(), triangulate(), unifysegments(), and unifysubfaces().
void tetgenmesh::spivot (face & s1, face & s2) inline
Definition at line 2696 of file tetgen.h.
View newest version in sPHENIX GitHub at line 2696 of file tetgen.h
References sdecode(), tetgenmesh::face::sh, and tetgenmesh::face::shver.
Referenced by add_steinerpt_in_segment(), addsteiner4recoversegment(), carveholes(), checksegments(), checkshells(), constrainedfacets(), fillcavity(), fillregion(), flip22(), flip31(), flip32(), flip41(), formregion(), identifypscedges(), insertpoint(), insertpoint_cdt(), lawsonflip(), lawsonflip3d(), makefacetverticesmap(), mergefacets(), reconstructmesh(), recoverfacebyflips(), recoversubfaces(), removevertexbyflips(), scarveholes(), sinsertvertex(), slocate(), splitsegment(), sremovevertex(), sscoutsegment(), and suppressbdrysteinerpoint().
void tetgenmesh::spivotself (face & s) inline
Definition at line 2702 of file tetgen.h.
View newest version in sPHENIX GitHub at line 2702 of file tetgen.h
References sdecode(), tetgenmesh::face::sh, and tetgenmesh::face::shver.
Referenced by checksegments(), farsdest(), farsorg(), insertpoint(), makesegmentendpointsmap(), reconstructmesh(), recoversubfaces(), removevertexbyflips(), sinsertvertex(), splitsegment(), sremovevertex(), sscoutsegment(), and suppressbdrysteinerpoint().
int tetgenmesh::splitsegment (face * splitseg, point encpt, REAL rrp, point encpt1, point encpt2, int qflag, int chkencflag)
Definition at line 24272 of file tetgen.cxx.
View newest version in sPHENIX GitHub at line 24272 of file tetgen.cxx
References areabound(), tetgenmesh::insertvertexflags::assignmeshsize, b, tetgenmesh::insertvertexflags::bowywat, checkconstraints, tetgenmesh::insertvertexflags::chkencflag, tetgenmesh::flipconstraints::chkencflag, distance(), tetgenmesh::flipconstraints::enqflag, tetgenbehavior::epsilon, flipstack, FREEFACETVERTEX, FREESEGVERTEX, getpointinsradius(), getsteinerptonsegment(), tetgenmesh::insertvertexflags::iloc, insertpoint(), INSTAR, tetgenmesh::insertvertexflags::lawson, lawsonflip3d(), makepoint(), tetgenbehavior::metric, tetgenbehavior::nobisect, ONEDGE, tetgenmesh::insertvertexflags::parentpt, point2sh(), pointdealloc(), pointtype(), REAL, tetgenmesh::insertvertexflags::rejflag, tetgenmesh::insertvertexflags::respectbdflag, tetgenmesh::arraypool::restart(), rp(), tetgenmesh::insertvertexflags::sbowywat, sdecode(), sdest(), segfacetadjacent(), segsegadjacent(), setpointinsradius(), tetgenmesh::face::sh, tetgenmesh::insertvertexflags::sloc, tetgenmesh::insertvertexflags::smlen, tetgenmesh::insertvertexflags::smlenflag, sorg(), spivot(), spivotself(), tetgenmesh::insertvertexflags::splitbdflag, sstpivot1(), st_segref_count, steinerleft, unflipqueue, useinsertradius, and tetgenmesh::insertvertexflags::validflag.
Referenced by repairencsegs(), splitsubface(), and splittetrahedron().
int tetgenmesh::splitsliver (triface * slitet, REAL cosd, int chkencflag)
Definition at line 26548 of file tetgen.cxx.
View newest version in sPHENIX GitHub at line 26548 of file tetgen.cxx
References tetgenmesh::insertvertexflags::assignmeshsize, b, caveoldtetlist, cavetetlist, tetgenmesh::insertvertexflags::chkencflag, dest(), edestoppo(), enext(), eprev(), esymself(), fnextself(), FREEVOLVERTEX, tetgenmesh::insertvertexflags::iloc, tetgenmesh::optparameters::imprval, infect(), tetgenmesh::optparameters::initval, insertpoint(), INSTAR, ishulltet(), issubseg, locate(), makepoint(), tetgenmesh::optparameters::maxiter, tetgenbehavior::metric, tetgenmesh::optparameters::min_max_dihedangle, n, tetgenmesh::arraypool::newindex(), tetgenmesh::optparameters::numofsearchdirs, org(), pointdealloc(), REAL, tetgenmesh::arraypool::restart(), tetgenmesh::optparameters::searchstep, smoothpoint(), tetgenmesh::optparameters::smthiter, st_volref_count, steinerleft, and tetgenmesh::triface::tet.
Referenced by removeslivers().
int tetgenmesh::splitsubface (face * splitfac, point encpt, point encpt1, int qflag, REAL * ccent, int chkencflag)
Definition at line 24698 of file tetgen.cxx.
View newest version in sPHENIX GitHub at line 24698 of file tetgen.cxx
References areabound(), tetgenmesh::insertvertexflags::assignmeshsize, b, tetgenmesh::insertvertexflags::bowywat, calculateabovepoint4(), checkconstraints, tetgenmesh::insertvertexflags::chkencflag, tetgenmesh::flipconstraints::chkencflag, distance(), encseglist, ENCSEGMENT, tetgenmesh::flipconstraints::enqflag, facetfacetadjacent(), fastlookup, flipstack, FREEFACETVERTEX, FREESEGVERTEX, getpointinsradius(), tetgenmesh::insertvertexflags::iloc, insertpoint(), INSTAR, tetgenmesh::insertvertexflags::lawson, lawsonflip3d(), makepoint(), tetgenbehavior::metric, tetgenbehavior::nobisect, tetgenmesh::arraypool::objects, ONEDGE, ONFACE, tetgenmesh::insertvertexflags::parentpt, charm_jet_strange_helicity::pc, point2sh(), pointdealloc(), pointtype(), REAL, tetgenmesh::insertvertexflags::refineflag, tetgenmesh::insertvertexflags::refinesh, tetgenmesh::insertvertexflags::rejflag, repairencsegs(), tetgenmesh::insertvertexflags::respectbdflag, tetgenmesh::arraypool::restart(), rp(), sapex(), tetgenmesh::insertvertexflags::sbowywat, sdecode(), sdest(), segfacetadjacent(), setpointinsradius(), tetgenmesh::insertvertexflags::sloc, slocate(), tetgenmesh::insertvertexflags::smlen, tetgenmesh::insertvertexflags::smlenflag, sorg(), tetgenmesh::insertvertexflags::splitbdflag, splitsegment(), st_facref_count, steinerleft, stpivot(), unflipqueue, useinsertradius, and tetgenmesh::insertvertexflags::validflag.
Referenced by repairencfacs(), and splittetrahedron().
int tetgenmesh::splittetrahedron (triface * splittet, int qflag, REAL * ccent, int chkencflag)
Definition at line 25201 of file tetgen.cxx.
View newest version in sPHENIX GitHub at line 25201 of file tetgen.cxx
References tetgenmesh::insertvertexflags::assignmeshsize, b, badsubsegs, tetgenmesh::insertvertexflags::bowywat, tetgenmesh::badface::cent, checkconstraints, tetgenmesh::insertvertexflags::chkencflag, tetgenmesh::flipconstraints::chkencflag, distance(), encseglist, ENCSEGMENT, encshlist, ENCSUBFACE, tetgenmesh::flipconstraints::enqflag, enqueuetetrahedron(), fastlookup, flipstack, FREEVOLVERTEX, tetgenmesh::insertvertexflags::iloc, insertpoint(), tetgenmesh::memorypool::items, tetgenmesh::insertvertexflags::lawson, lawsonflip3d(), makepoint(), tetgenbehavior::metric, tetgenbehavior::nobisect, tetgenmesh::arraypool::objects, org(), OUTSIDE, pointdealloc(), REAL, tetgenmesh::insertvertexflags::refineflag, tetgenmesh::insertvertexflags::refinetet, tetgenmesh::insertvertexflags::rejflag, repairencfacs(), repairencsegs(), tetgenmesh::insertvertexflags::respectbdflag, tetgenmesh::arraypool::restart(), tetgenmesh::insertvertexflags::sbowywat, setpointinsradius(), tetgenmesh::insertvertexflags::sloc, tetgenmesh::insertvertexflags::splitbdflag, splitsegment(), splitsubface(), tetgenmesh::badface::ss, st_volref_count, steinerleft, tetgenmesh::triface::tet, unflipqueue, useinsertradius, and tetgenmesh::insertvertexflags::validflag.
Referenced by repairbadtets().
int tetgenmesh::sremovevertex (point delpt, face * parentsh, face * parentseg, int lawson)
Definition at line 12592 of file tetgen.cxx.
View newest version in sPHENIX GitHub at line 12592 of file tetgen.cxx
References areabound(), b, calculateabovepoint4(), cavesegshlist, caveshbdlist, caveshlist, checkconstraints, dummypoint, fastlookup, flip22(), flip31(), getfacetindex(), it, lawsonflip(), makeshellface(), tetgenmesh::arraypool::newindex(), tetgenmesh::arraypool::objects, orient3d(), charm_jet_strange_helicity::pc, pointmark(), printf(), REAL, tetgenmesh::arraypool::restart(), sapex(), sbond(), sbond1(), sdest(), sdissolve(), sencode(), senext(), senext2(), senext2self(), senextself(), sesymself(), setareabound(), setfacetindex(), setpoint2sh(), setshellmark(), setshvertices, tetgenmesh::face::sh, shellfacedealloc(), shellmark(), tetgenmesh::face::shver, smarktest(), smarktested(), sorg(), spivot(), spivotself(), ssbond(), ssdissolve(), sspivot(), subfaces, subsegs, useinsertradius, and tetgenbehavior::verbose.
Referenced by removevertexbyflips(), and suppressbdrysteinerpoint().
void tetgenmesh::ssbond (face & s, face & edge) inline
Definition at line 3000 of file tetgen.h.
View newest version in sPHENIX GitHub at line 3000 of file tetgen.h
References sencode(), tetgenmesh::face::sh, and tetgenmesh::face::shver.
Referenced by carveholes(), fillcavity(), fillregion(), flip22(), flip31(), formregion(), identifypscedges(), recoversubfaces(), sinsertvertex(), sremovevertex(), sscoutsegment(), triangulate(), and unifysegments().
void tetgenmesh::ssbond1 (face & s, face & edge) inline
Definition at line 3006 of file tetgen.h.
View newest version in sPHENIX GitHub at line 3006 of file tetgen.h
References sencode(), tetgenmesh::face::sh, and tetgenmesh::face::shver.
Referenced by reconstructmesh().
enum tetgenmesh::interresult tetgenmesh::sscoutsegment (face * searchsh, point endpt)
Definition at line 13106 of file tetgen.cxx.
View newest version in sPHENIX GitHub at line 13106 of file tetgen.cxx
References ACROSSEDGE, ACROSSVERT, b, distance(), dummypoint, tetgenbehavior::epsilon, flip22(), flipshpush(), isshsubseg, makeshellface(), orient3d(), charm_jet_strange_helicity::pc, pointmark(), printf(), randomnation(), REAL, sapex(), sdest(), senext(), senext2(), senext2self(), sesymself(), setshellmark(), setshvertices, tetgenmesh::face::sh, SHAREEDGE, sorg(), spivot(), spivotself(), ssbond(), subsegs, terminatetetgen(), triarea(), and tetgenbehavior::verbose.
Referenced by triangulate().
void tetgenmesh::ssdissolve (face & s) inline
Definition at line 3014 of file tetgen.h.
View newest version in sPHENIX GitHub at line 3014 of file tetgen.h
References tetgenmesh::face::sh, and tetgenmesh::face::shver.
Referenced by fillcavity(), fillregion(), flip22(), mergefacets(), recoversubfaces(), restorecavity(), sremovevertex(), and unifysegments().
void tetgenmesh::sspivot (face & s, face & edge) inline
Definition at line 3021 of file tetgen.h.
View newest version in sPHENIX GitHub at line 3021 of file tetgen.h
References sdecode(), tetgenmesh::face::sh, and tetgenmesh::face::shver.
Referenced by carveholes(), checkshells(), fillregion(), flip22(), flip31(), formregion(), identifypscedges(), reconstructmesh(), recoversubfaces(), restorecavity(), scoutcrossedge(), sinsertvertex(), sremovevertex(), suppressbdrysteinerpoint(), and unifysegments().
void tetgenmesh::sstbond1 (face & s, triface & t) inline
Definition at line 3050 of file tetgen.h.
View newest version in sPHENIX GitHub at line 3050 of file tetgen.h
References encode().
Referenced by carvecavity(), carveholes(), constrainedfacets(), delaunizesegments(), flip23(), flip32(), flip41(), formregion(), insertpoint(), reconstructmesh(), recoversegments(), recoversubfaces(), refineregion(), removevertexbyflips(), and suppressbdrysteinerpoint().
void tetgenmesh::sstdissolve1 (face & s) inline
Definition at line 3062 of file tetgen.h.
View newest version in sPHENIX GitHub at line 3062 of file tetgen.h
Referenced by carvecavity(), insertpoint(), and removevertexbyflips().
void tetgenmesh::sstpivot1 (face & s, triface & t) inline
Definition at line 3081 of file tetgen.h.
View newest version in sPHENIX GitHub at line 3081 of file tetgen.h
References decode(), and tetgenmesh::face::sh.
Referenced by carvecavity(), checkconforming(), checkseg4split(), checksegments(), delaunizesegments(), fillregion(), insertpoint(), outsubsegments(), recoversegments(), recoversubfaces(), refineregion(), removevertexbyflips(), restorecavity(), scoutcrossedge(), splitsegment(), and suppressbdrysteinerpoint().
void tetgenmesh::statistics ()
Definition at line 28378 of file tetgen.cxx.
View newest version in sPHENIX GitHub at line 28378 of file tetgen.cxx
References b, dupverts, hullsize, in, insegments, tetgenmesh::memorypool::items, memorystatistics(), meshedges, meshhulledges, nonconvex, nonregularcount, tetgenio::numberoffacets, tetgenio::numberofholes, tetgenio::numberofpoints, tetgenio::numberofregions, tetgenio::numberoftetrahedra, tetgenbehavior::plc, points, printf(), qualitystatistics(), tetgenbehavior::refine, st_facref_count, st_segref_count, st_volref_count, subfaces, subsegs, tetrahedrons, unuverts, tetgenbehavior::verbose, and tetgenbehavior::weighted.
Referenced by tetrahedralize().
void tetgenmesh::stdissolve (face & s) inline
Definition at line 2986 of file tetgen.h.
View newest version in sPHENIX GitHub at line 2986 of file tetgen.h
References Acts::UnitConstants::s.
Referenced by carvecavity(), flip32(), insertpoint(), and removevertexbyflips().
void tetgenmesh::stpivot (face & s, triface & t) inline
Definition at line 2961 of file tetgen.h.
View newest version in sPHENIX GitHub at line 2961 of file tetgen.h
References decode(), tetgenmesh::face::sh, tetgenmesh::face::shver, stpivottbl, t, and tetgenmesh::triface::ver.
Referenced by carvecavity(), checkconforming(), checkfac4split(), checksegments(), checkshells(), delaunizecavity(), fillcavity(), fillregion(), insertpoint(), insertpoint_cdt(), lawsonflip3d(), outsubfaces(), reconstructmesh(), recoversubfaces(), removevertexbyflips(), splitsubface(), and suppressbdrysteinerpoint().
void tetgenmesh::suninfect (face & s) inline
Definition at line 2821 of file tetgen.h.
View newest version in sPHENIX GitHub at line 2821 of file tetgen.h
References shmarkindex.
Referenced by add_steinerpt_in_segment(), carvecavity(), carveholes(), detectinterfaces(), fillregion(), getvertexstar(), insertpoint(), makefacetverticesmap(), and suppressbdrysteinerpoint().
void tetgenmesh::sunmarktest (face & s) inline
Definition at line 2843 of file tetgen.h.
View newest version in sPHENIX GitHub at line 2843 of file tetgen.h
References shmarkindex.
Referenced by constrainedfacets(), formregion(), insertpoint(), insertpoint_abort(), and scarveholes().
void tetgenmesh::sunmarktest2 (face & s) inline
Definition at line 2863 of file tetgen.h.
View newest version in sPHENIX GitHub at line 2863 of file tetgen.h
References shmarkindex.
Referenced by repairencfacs(), and repairencsegs().
void tetgenmesh::sunmarktest3 (face & s) inline
Definition at line 2882 of file tetgen.h.
View newest version in sPHENIX GitHub at line 2882 of file tetgen.h
References shmarkindex.
int tetgenmesh::suppressbdrysteinerpoint (point steinerpt)
Definition at line 20904 of file tetgen.cxx.
View newest version in sPHENIX GitHub at line 20904 of file tetgen.cxx
References apex(), b, bond(), caveoldtetlist, cavesegshlist, caveshbdlist, caveshlist, cavetetlist, dest(), dissolve(), distance(), dot(), dummypoint, encode(), enextself(), esym(), esymself(), facenormal(), fastlookup, tetgenbehavior::fliplinklevel, fnextself(), for(), FREEFACETVERTEX, FREESEGVERTEX, FREEVOLVERTEX, fsym(), getvertexstar(), hullsize, isdeadtet(), ishulltet(), it, k, makepoint(), maketetrahedron(), n, tetgenmesh::arraypool::newindex(), tetgenbehavior::nobisect_param, tetgenmesh::arraypool::objects, org(), orient3d(), charm_jet_strange_helicity::pc, planelineint(), point2sh(), pointdealloc(), pointmark(), pointtype(), printf(), REAL, removevertexbyflips(), tetgenmesh::arraypool::restart(), sapex(), sdecode(), sdest(), senext(), senext2(), senext2self(), senextself(), sesymself(), setapex(), setoppo(), setpoint2tet(), setpointtype(), setvertices, tetgenmesh::face::sh, tetgenmesh::face::shver, sinfect(), sinfected(), sorg(), spivot(), spivotself(), sremovevertex(), sspivot(), sstbond1(), sstpivot1(), st_facref_count, st_segref_count, st_volref_count, steinerleft, stpivot(), subvertstack, suninfect(), tetgenmesh::triface::tet, tetrahedrondealloc(), tsbond(), tsdissolve(), tssbond1(), tssdissolve1(), Acts::UnitConstants::u, UNUSEDVERTEX, unuverts, v1, v2, tetgenmesh::triface::ver, and tetgenbehavior::verbose.
Referenced by suppresssteinerpoints().
int tetgenmesh::suppresssteinerpoints ()
Definition at line 21430 of file tetgen.cxx.
View newest version in sPHENIX GitHub at line 21430 of file tetgen.cxx
References b, cavetetlist, fastlookup, tetgenbehavior::fliplinklevel, FREEFACETVERTEX, FREESEGVERTEX, FREEVOLVERTEX, getvertexstar(), tetgenmesh::optparameters::imprval, tetgenmesh::optparameters::initval, tetgenmesh::optparameters::max_min_volume, tetgenmesh::optparameters::maxiter, tetgenbehavior::nobisect_param, tetgenmesh::optparameters::numofsearchdirs, tetgenmesh::arraypool::objects, orient3dfast(), pointtype(), printf(), tetgenbehavior::quiet, REAL, removevertexbyflips(), tetgenmesh::arraypool::restart(), tetgenmesh::optparameters::searchstep, smoothpoint(), subvertstack, suppressbdrysteinerpoint(), tetgenmesh::triface::tet, UNUSEDVERTEX, and tetgenbehavior::verbose.
Referenced by tetrahedralize().
bool tetgenmesh::tetalldihedral (point pa, point pb, point pc, point pd, REAL * cosdd, REAL * cosmaxd, REAL * cosmind)
Definition at line 6465 of file tetgen.cxx.
View newest version in sPHENIX GitHub at line 6465 of file tetgen.cxx
References dot(), f2(), facenormal(), charm_jet_strange_helicity::N, REAL, and tetallnormal().
Referenced by checkflipeligibility(), improvequalitybyflips(), improvequalitybysmoothing(), optimizemesh(), removeslivers(), and smoothpoint().
void tetgenmesh::tetallnormal (point pa, point pb, point pc, point pd, REAL N[4][3], REAL * volume)
Definition at line 6563 of file tetgen.cxx.
View newest version in sPHENIX GitHub at line 6563 of file tetgen.cxx
References lu_decmp(), lu_solve(), and REAL.
Referenced by tetalldihedral().
REAL tetgenmesh::tetaspectratio (point pa, point pb, point pc, point pd)
Definition at line 6606 of file tetgen.cxx.
View newest version in sPHENIX GitHub at line 6606 of file tetgen.cxx
References dot(), H, lu_decmp(), lu_solve(), charm_jet_strange_helicity::N, REAL, and Acts::Test::volume.
Referenced by smoothpoint().
REAL tetgenmesh::tetprismvol (REAL * pa, REAL * pb, REAL * pc, REAL * pd)
Definition at line 6897 of file tetgen.cxx.
View newest version in sPHENIX GitHub at line 6897 of file tetgen.cxx
References dot(), orient4d(), and REAL.
Referenced by flip23(), flip32(), flip41(), qualitystatistics(), and recoverdelaunay().
void tetgenmesh::tetrahedrondealloc (tetrahedron * dyingtetrahedron)
Definition at line 4298 of file tetgen.cxx.
View newest version in sPHENIX GitHub at line 4298 of file tetgen.cxx
References tetgenmesh::memorypool::dealloc(), tet2segpool, tet2subpool, and tetrahedrons.
Referenced by add_steinerpt_in_schoenhardtpoly(), carvecavity(), carveholes(), flip32(), flip41(), insertpoint(), restorecavity(), and suppressbdrysteinerpoint().
tetgenmesh::tetrahedron * tetgenmesh::tetrahedrontraverse ()
Definition at line 4321 of file tetgen.cxx.
View newest version in sPHENIX GitHub at line 4321 of file tetgen.cxx
References dummypoint, tetrahedrons, and tetgenmesh::memorypool::traverse().
Referenced by carveholes(), checkdelaunay(), checkregular(), checksegments(), delaunayrefinement(), highorder(), numberedges(), optimizemesh(), outedges(), outelements(), outfaces(), outmesh2medit(), outmesh2vtk(), outneighbors(), outvoronoi(), qualitystatistics(), reconstructmesh(), recoverdelaunay(), and scoutpoint().
void tetgenmesh::transfernodes ()
Definition at line 10500 of file tetgen.cxx.
View newest version in sPHENIX GitHub at line 10500 of file tetgen.cxx
References b, tetgenbehavior::epsilon, FREEFACETVERTEX, FREESEGVERTEX, FREEVOLVERTEX, in, longest, makepoint(), tetgenbehavior::minedgelength, tetgenio::numberofpointattributes, tetgenio::numberofpointmtrs, tetgenio::numberofpoints, tetgenio::pointattributelist, tetgenio::pointlist, pointmtrindex, tetgenio::pointmtrlist, tetgenio::pointparamlist, printf(), tetgenbehavior::psc, REAL, RIDGEVERTEX, setpointgeomtag(), setpointgeomuv(), setpointtype(), tetgenio::pointparam::tag, terminatetetgen(), tetgenio::pointparam::type, UNUSEDVERTEX, tetgenio::pointparam::uv, tetgenbehavior::weighted, tetgenbehavior::weighted_param, x, xmax, xmin, y, ymax, ymin, z, zmax, and zmin.
Referenced by tetrahedralize().
int tetgenmesh::tri_edge_2d (point A, point B, point C, point P, point Q, point R, int level, int * types, int * pos)
Definition at line 4992 of file tetgen.cxx.
View newest version in sPHENIX GitHub at line 4992 of file tetgen.cxx
References ACROSSEDGE, ACROSSVERT, DISJOINT, distance(), dot(), facenormal(), n, orient3d(), REAL, s1, s2, s3, s4, SETVECTOR3, SHAREEDGE, SHAREVERT, TOUCHEDGE, TOUCHFACE, and z1.
Referenced by tri_edge_tail().
int tetgenmesh::tri_edge_inter_tail (point A, point B, point C, point P, point Q, REAL s_p, REAL s_q)
Definition at line 5837 of file tetgen.cxx.
View newest version in sPHENIX GitHub at line 5837 of file tetgen.cxx
References DISJOINT, INTERSECT, pos(), SHAREEDGE, SHAREVERT, and tri_edge_tail().
Referenced by tri_tri_inter().
int tetgenmesh::tri_edge_tail (point A, point B, point C, point P, point Q, point R, REAL sP, REAL sQ, int level, int * types, int * pos)
Definition at line 5611 of file tetgen.cxx.
View newest version in sPHENIX GitHub at line 5611 of file tetgen.cxx
References ACROSSEDGE, ACROSSFACE, ACROSSVERT, DISJOINT, orient3d(), REAL, s1, s2, s3, SETVECTOR3, SHAREVERT, TOUCHEDGE, TOUCHFACE, tri_edge_2d(), and z1.
Referenced by tri_edge_inter_tail(), and tri_edge_test().
int tetgenmesh::tri_edge_test (point A, point B, point C, point P, point Q, point R, int level, int * types, int * pos)
Definition at line 5815 of file tetgen.cxx.
View newest version in sPHENIX GitHub at line 5815 of file tetgen.cxx
References orient3d(), REAL, and tri_edge_tail().
Referenced by addsteiner4recoversegment(), checkflipeligibility(), fillcavity(), formcavity(), recoveredgebyflips(), recoverfacebyflips(), scoutcrossedge(), and scoutsegment().
int tetgenmesh::tri_tri_inter (point A, point B, point C, point O, point P, point Q)
Definition at line 5877 of file tetgen.cxx.
View newest version in sPHENIX GitHub at line 5877 of file tetgen.cxx
References DISJOINT, INTERSECT, orient3d(), REAL, SHAREEDGE, SHAREFACE, SHAREVERT, and tri_edge_inter_tail().
Referenced by interecursive().
void tetgenmesh::triangulate (int shmark, arraypool * ptlist, arraypool * conlist, int holes, REAL * holelist)
Definition at line 13389 of file tetgen.cxx.
View newest version in sPHENIX GitHub at line 13389 of file tetgen.cxx
References b, calculateabovepoint(), cavesegshlist, caveshbdlist, caveshlist, distance(), tetgenio::facetconstraintlist, tetgenio::facetmarkerlist, FACETVERTEX, fastlookup, flipstack, in, lawsonflip(), makeshellface(), tetgenio::numberoffacetconstraints, tetgenmesh::arraypool::objects, ONVERTEX, OUTSIDE, charm_jet_strange_helicity::pc, pinfect(), pinfected(), pointtype(), printf(), puninfect(), tetgenbehavior::quality, REAL, recentsh, tetgenmesh::arraypool::restart(), scarveholes(), sdest(), senextself(), setareabound(), setpointtype(), setshellmark(), setshvertices, tetgenmesh::face::sh, shellfacedealloc(), shellfacetraverse(), shellmark(), tetgenmesh::face::shver, sinsertvertex(), slocate(), sorg(), ssbond(), sscoutsegment(), subfaces, subsegs, tetgenmesh::memorypool::traversalinit(), tetgenbehavior::verbose, and VOLVERTEX.
Referenced by meshsurface().
REAL tetgenmesh::triarea (REAL * pa, REAL * pb, REAL * pc)
Definition at line 6264 of file tetgen.cxx.
View newest version in sPHENIX GitHub at line 6264 of file tetgen.cxx
References cross(), dot(), and REAL.
Referenced by getpointmeshsize(), scoutpoint(), and sscoutsegment().
void tetgenmesh::tsbond (triface & t, face & s) inline
Definition at line 2919 of file tetgen.h.
View newest version in sPHENIX GitHub at line 2919 of file tetgen.h
References tetgenmesh::memorypool::alloc(), encode2(), Acts::UnitConstants::s, sencode2(), tetgenmesh::face::sh, tetgenmesh::face::shver, stbondtbl, t, tet2subpool, tsbondtbl, and tetgenmesh::triface::ver.
Referenced by carvecavity(), carveholes(), fillcavity(), fillregion(), flip23(), flip32(), flip41(), insertpoint(), reconstructmesh(), recoversubfaces(), removevertexbyflips(), scoutsubface(), and suppressbdrysteinerpoint().
void tetgenmesh::tsdissolve (triface & t) inline
Definition at line 2977 of file tetgen.h.
View newest version in sPHENIX GitHub at line 2977 of file tetgen.h
Referenced by delaunizecavity(), fillcavity(), insertpoint(), insertpoint_cdt(), removevertexbyflips(), and suppressbdrysteinerpoint().
void tetgenmesh::tspivot (triface & t, face & s) inline
Definition at line 2942 of file tetgen.h.
View newest version in sPHENIX GitHub at line 2942 of file tetgen.h
References Acts::UnitConstants::s, sdecode(), tetgenmesh::face::shver, tspivottbl, and tetgenmesh::triface::ver.
Referenced by carveholes(), checkdelaunay(), checkregular(), checksegments(), checkshells(), fillcavity(), fillregion(), flip23(), flip32(), flip41(), flipcertify(), flipinsertfacet(), getvertexstar(), insertconstrainedpoints(), lawsonflip3d(), outfaces(), outmesh2medit(), reconstructmesh(), and scoutsubface().
void tetgenmesh::tssbond1 (triface & t, face & seg) inline
Definition at line 3037 of file tetgen.h.
View newest version in sPHENIX GitHub at line 3037 of file tetgen.h
References tetgenmesh::memorypool::alloc(), sencode(), t, tet2segpool, and ver2edge.
Referenced by carvecavity(), carveholes(), constrainedfacets(), delaunizesegments(), flip23(), flip32(), flip41(), formregion(), insertpoint(), reconstructmesh(), recoversegments(), recoversubfaces(), refineregion(), removevertexbyflips(), and suppressbdrysteinerpoint().
void tetgenmesh::tssdissolve1 (triface & t) inline
Definition at line 3055 of file tetgen.h.
View newest version in sPHENIX GitHub at line 3055 of file tetgen.h
References ver2edge.
Referenced by fillcavity(), fillregion(), recoversubfaces(), removevertexbyflips(), restorecavity(), and suppressbdrysteinerpoint().
void tetgenmesh::tsspivot1 (triface & t, face & s) inline
Definition at line 3067 of file tetgen.h.
View newest version in sPHENIX GitHub at line 3067 of file tetgen.h
References Acts::UnitConstants::s, sdecode(), and ver2edge.
Referenced by addsteiner4recoversegment(), carveholes(), checksegments(), fillcavity(), fillregion(), flip23(), flip32(), flip41(), flipinsertfacet(), flipnm(), insertconstrainedpoints(), outedges(), recoverfacebyflips(), removeedgebyflips(), and removevertexbyflips().
void tetgenmesh::unifysegments ()
Definition at line 13607 of file tetgen.cxx.
View newest version in sPHENIX GitHub at line 13607 of file tetgen.cxx
References tetgenmesh::memorypool::alloc(), b, dot(), f2(), facenormal(), tetgenio::facetmarkerlist, tetgenio::firstnumber, flippool, FREEFACETVERTEX, FREESEGVERTEX, in, tetgenmesh::memorypool::items, k, Acts::UnitConstants::m, makepoint2submap(), tetgenmesh::badface::nextitem, tetgenio::numberofsegmentconstraints, orient3d(), pointmark(), pointtype(), printf(), tetgenbehavior::psc, tetgenbehavior::quality, REAL, tetgenmesh::memorypool::restart(), sapex(), sbond(), sbond1(), sdest(), tetgenio::segmentconstraintlist, sencode(), senext2self(), sesymself(), setareabound(), setpoint2sh(), tetgenmesh::face::sh, shellfacedealloc(), shellfacetraverse(), shellmark(), tetgenmesh::face::shver, sorg(), ssbond(), ssdissolve(), sspivot(), subfaces, subsegs, tetgenmesh::memorypool::traversalinit(), unifysubfaces(), and tetgenbehavior::verbose.
Referenced by meshsurface().
void tetgenmesh::unifysubfaces (face * f1, face * f2)
Definition at line 13564 of file tetgen.cxx.
View newest version in sPHENIX GitHub at line 13564 of file tetgen.cxx
References b, charm_jet_strange_helicity::pc, pointmark(), printf(), tetgenbehavior::psc, sapex(), sdest(), shellmark(), sorg(), and terminatetetgen().
Referenced by unifysegments().
void tetgenmesh::uninfect (triface & t) inline
Definition at line 2530 of file tetgen.h.
View newest version in sPHENIX GitHub at line 2530 of file tetgen.h
References elemmarkerindex, and tetgenmesh::triface::tet.
Referenced by carvecavity(), carveholes(), flipinsertfacet(), formcavity(), getedge(), getvertexstar(), insertpoint(), insertpoint_abort(), and restorecavity().
void tetgenmesh::unmarkedge (triface & t) inline
Definition at line 2578 of file tetgen.h.
View newest version in sPHENIX GitHub at line 2578 of file tetgen.h
References elemmarkerindex, t, tetgenmesh::triface::tet, and ver2edge.
Referenced by formcavity().
void tetgenmesh::unmarkface (triface & t) inline
Definition at line 2561 of file tetgen.h.
View newest version in sPHENIX GitHub at line 2561 of file tetgen.h
References elemmarkerindex, tetgenmesh::triface::tet, and tetgenmesh::triface::ver.
Referenced by fillcavity(), incrementalflip(), and lawsonflip3d().
void tetgenmesh::unmarktest (triface & t) inline
Definition at line 2545 of file tetgen.h.
View newest version in sPHENIX GitHub at line 2545 of file tetgen.h
References elemmarkerindex, and tetgenmesh::triface::tet.
Referenced by carvecavity(), flipinsertfacet(), improvequalitybysmoothing(), incrementalflip(), insertpoint(), and insertpoint_abort().
void tetgenmesh::unmarktest2 (triface & t) inline
Definition at line 2594 of file tetgen.h.
View newest version in sPHENIX GitHub at line 2594 of file tetgen.h
References elemmarkerindex, and tetgenmesh::triface::tet.
Referenced by removeslivers(), and repairbadtets().
REAL tetgenmesh::volumebound (tetrahedron * ptr) inline
Definition at line 2490 of file tetgen.h.
View newest version in sPHENIX GitHub at line 2490 of file tetgen.h
References REAL, and volumeboundindex.
Referenced by checkfac4split(), checktet4split(), flip23(), flip32(), and insertpoint().
Member Data Documentation
tetgenio * tetgenmesh::addin
Definition at line 1256 of file tetgen.h.
View newest version in sPHENIX GitHub at line 1256 of file tetgen.h
Referenced by initializepools(), main(), tetgenmesh(), and tetrahedralize().
int tetgenmesh::apexpivot = {5, 6, 7, 4, 7, 7, 5, 5, 6, 4, 4, 6} static
Definition at line 1367 of file tetgen.h.
View newest version in sPHENIX GitHub at line 1367 of file tetgen.h
Referenced by apex(), and setapex().
int tetgenmesh::areaboundindex
Definition at line 1321 of file tetgen.h.
View newest version in sPHENIX GitHub at line 1321 of file tetgen.h
Referenced by areabound(), initializepools(), setareabound(), and tetgenmesh().
int tetgenmesh::autofliplinklevel
Definition at line 1326 of file tetgen.h.
View newest version in sPHENIX GitHub at line 1326 of file tetgen.h
Referenced by flipnm(), improvequalitybyflips(), meshcoarsening(), recoverboundary(), recoverdelaunay(), recoversegments(), recoversubfaces(), and tetgenmesh().
tetgenbehavior* tetgenmesh::b
Definition at line 1259 of file tetgen.h.
View newest version in sPHENIX GitHub at line 1259 of file tetgen.h
Referenced by add_steinerpt_in_schoenhardtpoly(), add_steinerpt_in_segment(), addsteiner4recoversegment(), calculateabovepoint(), carvecavity(), carveholes(), checkconforming(), checkdelaunay(), checkfac4encroach(), checkfac4split(), checkflipeligibility(), checkmesh(), checkregular(), checkseg4encroach(), checkseg4split(), checksegments(), checkshells(), checktet4split(), collectremovepoints(), constraineddelaunay(), constrainedfacets(), delaunayrefinement(), delaunizecavity(), delaunizesegments(), detectinterfaces(), fillcavity(), flip23(), flip32(), flipcertify(), flipinsertfacet(), flipnm(), flipnm_post(), formcavity(), getedge(), highorder(), hilbert_sort3(), identifypscedges(), improvequalitybyflips(), improvequalitybysmoothing(), incrementaldelaunay(), incrementalflip(), initialdelaunay(), initializepools(), insertconstrainedpoints(), insertpoint(), insertpoint_cdt(), interecursive(), interpolatemeshsize(), jettisonnodes(), lawsonflip(), lawsonflip3d(), main(), makefacetverticesmap(), makeindex2pointmap(), makepoint(), makepoint2submap(), makesegmentendpointsmap(), maketetrahedron(), memorystatistics(), mergefacets(), meshcoarsening(), meshsurface(), optimizemesh(), outedges(), outelements(), outfaces(), outhullfaces(), outmesh2medit(), outmesh2vtk(), outmetrics(), outneighbors(), outnodes(), outsmesh(), outsubfaces(), outsubsegments(), outvoronoi(), qualitystatistics(), randomsample(), reconstructmesh(), recoverboundary(), recoverdelaunay(), recoverfacebyflips(), recoversegments(), recoversubfaces(), refineregion(), removeedgebyflips(), removeslivers(), removevertexbyflips(), repairbadtets(), repairencfacs(), repairencsegs(), scoutpoint(), scoutsegment(), sinsertvertex(), slocate(), splitsegment(), splitsliver(), splitsubface(), splittetrahedron(), sremovevertex(), sscoutsegment(), statistics(), suppressbdrysteinerpoint(), suppresssteinerpoints(), tetgenmesh(), tetrahedralize(), transfernodes(), triangulate(), unifysegments(), and unifysubfaces().
memorypool * tetgenmesh::badsubfacs
Definition at line 1270 of file tetgen.h.
View newest version in sPHENIX GitHub at line 1270 of file tetgen.h
Referenced by delaunayrefinement(), flip22(), flip23(), flip32(), flip41(), insertpoint(), repairencfacs(), and tetgenmesh().
memorypool * tetgenmesh::badsubsegs
Definition at line 1270 of file tetgen.h.
View newest version in sPHENIX GitHub at line 1270 of file tetgen.h
Referenced by delaunayrefinement(), flip22(), flip23(), flip32(), flip41(), insertpoint(), repairencsegs(), splittetrahedron(), and tetgenmesh().
memorypool* tetgenmesh::badtetrahedrons
Definition at line 1270 of file tetgen.h.
View newest version in sPHENIX GitHub at line 1270 of file tetgen.h
Referenced by delaunayrefinement(), enqueuetetrahedron(), optimizemesh(), removeslivers(), repairbadtets(), and tetgenmesh().
tetgenmesh* tetgenmesh::bgm
Definition at line 1262 of file tetgen.h.
View newest version in sPHENIX GitHub at line 1262 of file tetgen.h
Referenced by freememory(), initializepools(), insertpoint(), interpolatemeshsize(), makepoint(), tetgenmesh(), and tetrahedralize().
int tetgenmesh::bondtbl = {{0,},} static
Definition at line 1362 of file tetgen.h.
View newest version in sPHENIX GitHub at line 1362 of file tetgen.h
Referenced by bond(), and inittables().
arraypool * tetgenmesh::cavebdrylist
Definition at line 1278 of file tetgen.h.
View newest version in sPHENIX GitHub at line 1278 of file tetgen.h
Referenced by freememory(), getedge(), incrementalflip(), initializepools(), insertpoint(), insertpoint_abort(), insertpoint_cdt(), memorystatistics(), and tetgenmesh().
arraypool * tetgenmesh::caveencseglist
Definition at line 1280 of file tetgen.h.
View newest version in sPHENIX GitHub at line 1280 of file tetgen.h
Referenced by add_steinerpt_in_segment(), carvecavity(), constrainedfacets(), flipnm(), freememory(), initializepools(), insertpoint(), insertpoint_cdt(), memorystatistics(), removeedgebyflips(), and tetgenmesh().
arraypool* tetgenmesh::caveencshlist
Definition at line 1280 of file tetgen.h.
View newest version in sPHENIX GitHub at line 1280 of file tetgen.h
Referenced by carvecavity(), constrainedfacets(), freememory(), initializepools(), insertpoint(), insertpoint_cdt(), memorystatistics(), and tetgenmesh().
arraypool * tetgenmesh::caveoldtetlist
Definition at line 1278 of file tetgen.h.
View newest version in sPHENIX GitHub at line 1278 of file tetgen.h
Referenced by add_steinerpt_in_schoenhardtpoly(), freememory(), initializepools(), insertpoint(), insertpoint_abort(), insertpoint_cdt(), memorystatistics(), splitsliver(), suppressbdrysteinerpoint(), and tetgenmesh().
arraypool * tetgenmesh::cavesegshlist
Definition at line 1281 of file tetgen.h.
View newest version in sPHENIX GitHub at line 1281 of file tetgen.h
Referenced by freememory(), initializepools(), insertpoint(), insertpoint_abort(), insertpoint_cdt(), memorystatistics(), recoverfacebyflips(), sinsertvertex(), sremovevertex(), suppressbdrysteinerpoint(), tetgenmesh(), and triangulate().
arraypool * tetgenmesh::caveshbdlist
Definition at line 1281 of file tetgen.h.
View newest version in sPHENIX GitHub at line 1281 of file tetgen.h
Referenced by freememory(), initializepools(), insertpoint(), insertpoint_cdt(), memorystatistics(), recoverfacebyflips(), removevertexbyflips(), scarveholes(), sinsertvertex(), sremovevertex(), suppressbdrysteinerpoint(), tetgenmesh(), and triangulate().
arraypool* tetgenmesh::caveshlist
Definition at line 1281 of file tetgen.h.
View newest version in sPHENIX GitHub at line 1281 of file tetgen.h
Referenced by freememory(), initializepools(), insertpoint(), insertpoint_abort(), insertpoint_cdt(), makefacetverticesmap(), memorystatistics(), recoverfacebyflips(), scarveholes(), sinsertvertex(), sremovevertex(), suppressbdrysteinerpoint(), tetgenmesh(), and triangulate().
arraypool* tetgenmesh::cavetetlist
Definition at line 1278 of file tetgen.h.
View newest version in sPHENIX GitHub at line 1278 of file tetgen.h
Referenced by add_steinerpt_in_schoenhardtpoly(), collectremovepoints(), flipinsertfacet(), flipnm(), flipnm_post(), freememory(), improvequalitybyflips(), improvequalitybysmoothing(), initializepools(), insertpoint(), insertpoint_abort(), memorystatistics(), outvoronoi(), recoverdelaunay(), removevertexbyflips(), splitsliver(), suppressbdrysteinerpoint(), suppresssteinerpoints(), and tetgenmesh().
arraypool * tetgenmesh::cavetetseglist
Definition at line 1279 of file tetgen.h.
View newest version in sPHENIX GitHub at line 1279 of file tetgen.h
Referenced by carvecavity(), freememory(), initializepools(), insertpoint(), insertpoint_abort(), memorystatistics(), and tetgenmesh().
arraypool* tetgenmesh::cavetetshlist
Definition at line 1279 of file tetgen.h.
View newest version in sPHENIX GitHub at line 1279 of file tetgen.h
Referenced by carvecavity(), freememory(), initializepools(), insertpoint(), insertpoint_abort(), memorystatistics(), and tetgenmesh().
arraypool * tetgenmesh::cavetetvertlist
Definition at line 1279 of file tetgen.h.
View newest version in sPHENIX GitHub at line 1279 of file tetgen.h
Referenced by carveholes(), collectremovepoints(), freememory(), incrementalflip(), initializepools(), insertpoint(), insertpoint_cdt(), memorystatistics(), outvoronoi(), removevertexbyflips(), and tetgenmesh().
long tetgenmesh::cavitycount
Definition at line 1348 of file tetgen.h.
View newest version in sPHENIX GitHub at line 1348 of file tetgen.h
Referenced by constraineddelaunay(), formcavity(), and tetgenmesh().
long tetgenmesh::cavityexpcount
Definition at line 1348 of file tetgen.h.
View newest version in sPHENIX GitHub at line 1348 of file tetgen.h
Referenced by constraineddelaunay(), delaunizecavity(), and tetgenmesh().
int tetgenmesh::checkconstraints
Definition at line 1324 of file tetgen.h.
View newest version in sPHENIX GitHub at line 1324 of file tetgen.h
Referenced by checkfac4split(), checkseg4split(), delaunayrefinement(), fillcavity(), fillregion(), flip31(), initializepools(), makeshellface(), reconstructmesh(), sinsertvertex(), splitsegment(), splitsubface(), splittetrahedron(), sremovevertex(), and tetgenmesh().
int tetgenmesh::checksubfaceflag
Definition at line 1323 of file tetgen.h.
View newest version in sPHENIX GitHub at line 1323 of file tetgen.h
Referenced by checkdelaunay(), checkregular(), constraineddelaunay(), delaunizecavity(), flip23(), flip32(), flip41(), flipnm(), insertpoint(), insertpoint_cdt(), lawsonflip3d(), reconstructmesh(), recoverboundary(), removefacebyflips(), removevertexbyflips(), scoutsegment(), and tetgenmesh().
int tetgenmesh::checksubsegflag
Definition at line 1322 of file tetgen.h.
View newest version in sPHENIX GitHub at line 1322 of file tetgen.h
Referenced by constraineddelaunay(), delaunizecavity(), flip23(), flip32(), flip41(), flipnm(), insertpoint(), lawsonflip3d(), reconstructmesh(), recoverboundary(), removeedgebyflips(), and tetgenmesh().
REAL tetgenmesh::cosmaxdihed
Definition at line 1330 of file tetgen.h.
View newest version in sPHENIX GitHub at line 1330 of file tetgen.h
Referenced by improvequalitybyflips(), and optimizemesh().
REAL tetgenmesh::cosmindihed
Definition at line 1330 of file tetgen.h.
View newest version in sPHENIX GitHub at line 1330 of file tetgen.h
Referenced by checktet4split(), and delaunayrefinement().
REAL tetgenmesh::cosslidihed
Definition at line 1332 of file tetgen.h.
View newest version in sPHENIX GitHub at line 1332 of file tetgen.h
Referenced by optimizemesh(), and removeslivers().
REAL tetgenmesh::cossmtdihed
Definition at line 1331 of file tetgen.h.
View newest version in sPHENIX GitHub at line 1331 of file tetgen.h
Referenced by improvequalitybysmoothing(), and optimizemesh().
int tetgenmesh::destpivot = {6, 4, 4, 6, 5, 6, 7, 4, 7, 7, 5, 5} static
Definition at line 1367 of file tetgen.h.
View newest version in sPHENIX GitHub at line 1367 of file tetgen.h
Referenced by dest(), and setdest().
point tetgenmesh::dummypoint
Definition at line 1297 of file tetgen.h.
View newest version in sPHENIX GitHub at line 1297 of file tetgen.h
Referenced by add_steinerpt_in_schoenhardtpoly(), calculateabovepoint(), calculateabovepoint4(), carveholes(), checkconforming(), checkdelaunay(), checkflipeligibility(), checkregular(), checkseg4split(), checktet4split(), delaunizecavity(), fillcavity(), finddirection(), flip23(), flip32(), flip41(), flipcertify(), flipnm(), formcavity(), freememory(), getpointmeshsize(), improvequalitybyflips(), incrementalflip(), initialdelaunay(), initializepools(), insertpoint(), ishulltet(), lawsonflip3d(), locate(), outvoronoi(), qualitystatistics(), reconstructmesh(), recoverfacebyflips(), reduceedgesatvertex(), scoutcrossedge(), scoutsegment(), sinsertvertex(), slocate(), sremovevertex(), sscoutsegment(), suppressbdrysteinerpoint(), tetgenmesh(), and tetrahedrontraverse().
long tetgenmesh::dupverts
Definition at line 1344 of file tetgen.h.
View newest version in sPHENIX GitHub at line 1344 of file tetgen.h
Referenced by incrementaldelaunay(), jettisonnodes(), meshsurface(), outedges(), outvoronoi(), statistics(), tetgenmesh(), and tetrahedralize().
int tetgenmesh::edestoppotbl = {0,} static
Definition at line 1365 of file tetgen.h.
View newest version in sPHENIX GitHub at line 1365 of file tetgen.h
Referenced by edestoppo(), edestoppoself(), and inittables().
int tetgenmesh::edge2ver = {0, 1, 2, 3, 8, 5} static
Definition at line 1370 of file tetgen.h.
View newest version in sPHENIX GitHub at line 1370 of file tetgen.h
Referenced by checkmesh(), checksegments(), checktet4split(), highorder(), improvequalitybyflips(), numberedges(), outedges(), outvoronoi(), and removeslivers().
int tetgenmesh::elemattribindex
Definition at line 1317 of file tetgen.h.
View newest version in sPHENIX GitHub at line 1317 of file tetgen.h
Referenced by elemattribute(), initializepools(), setelemattribute(), and tetgenmesh().
int tetgenmesh::elemmarkerindex
Definition at line 1319 of file tetgen.h.
View newest version in sPHENIX GitHub at line 1319 of file tetgen.h
Referenced by edgemarked(), elemcounter(), elemmarker(), facemarked(), infect(), infected(), initializepools(), markedge(), markface(), marktest(), marktest2(), marktest2ed(), marktested(), setelemcounter(), setelemmarker(), uninfect(), unmarkedge(), unmarkface(), unmarktest(), and unmarktest2().
arraypool* tetgenmesh::encseglist
Definition at line 1287 of file tetgen.h.
View newest version in sPHENIX GitHub at line 1287 of file tetgen.h
Referenced by constrainedfacets(), delaunayrefinement(), insertconstrainedpoints(), insertpoint(), refineregion(), splitsubface(), splittetrahedron(), and tetgenmesh().
arraypool * tetgenmesh::encshlist
Definition at line 1287 of file tetgen.h.
View newest version in sPHENIX GitHub at line 1287 of file tetgen.h
Referenced by delaunayrefinement(), insertconstrainedpoints(), insertpoint(), splittetrahedron(), and tetgenmesh().
int tetgenmesh::enextesymtbl = {0,} static
Definition at line 1364 of file tetgen.h.
View newest version in sPHENIX GitHub at line 1364 of file tetgen.h
Referenced by enextesym(), enextesymself(), and inittables().
int tetgenmesh::enexttbl = {0,} static
Definition at line 1363 of file tetgen.h.
View newest version in sPHENIX GitHub at line 1363 of file tetgen.h
Referenced by enext(), enextself(), and inittables().
int tetgenmesh::eorgoppotbl = {0,} static
Definition at line 1365 of file tetgen.h.
View newest version in sPHENIX GitHub at line 1365 of file tetgen.h
Referenced by eorgoppo(), eorgoppoself(), and inittables().
int tetgenmesh::epivot = {4, 5, 2, 11, 4, 5, 2, 11, 4, 5, 2, 11} static
Definition at line 1370 of file tetgen.h.
View newest version in sPHENIX GitHub at line 1370 of file tetgen.h
Referenced by delaunizecavity(), incrementalflip(), and insertpoint().
int tetgenmesh::eprevesymtbl = {0,} static
Definition at line 1364 of file tetgen.h.
View newest version in sPHENIX GitHub at line 1364 of file tetgen.h
Referenced by eprevesym(), eprevesymself(), and inittables().
int tetgenmesh::eprevtbl = {0,} static
Definition at line 1363 of file tetgen.h.
View newest version in sPHENIX GitHub at line 1363 of file tetgen.h
Referenced by eprev(), eprevself(), and inittables().
int tetgenmesh::esymtbl = {9, 6, 11, 4, 3, 7, 1, 5, 10, 0, 8, 2} static
Definition at line 1363 of file tetgen.h.
View newest version in sPHENIX GitHub at line 1363 of file tetgen.h
Referenced by esym(), esymself(), and inittables().
int tetgenmesh::facepivot1 = {0,} static
Definition at line 1366 of file tetgen.h.
View newest version in sPHENIX GitHub at line 1366 of file tetgen.h
Referenced by fnext(), and inittables().
int tetgenmesh::facepivot2 = {{0,},} static
Definition at line 1366 of file tetgen.h.
View newest version in sPHENIX GitHub at line 1366 of file tetgen.h
Referenced by fnext(), and inittables().
point* tetgenmesh::facetverticeslist
Definition at line 1291 of file tetgen.h.
View newest version in sPHENIX GitHub at line 1291 of file tetgen.h
Referenced by facetfacetadjacent(), freememory(), makefacetverticesmap(), segfacetadjacent(), and tetgenmesh().
long tetgenmesh::fillregioncount
Definition at line 1348 of file tetgen.h.
View newest version in sPHENIX GitHub at line 1348 of file tetgen.h
Referenced by constraineddelaunay(), fillregion(), and tetgenmesh().
long tetgenmesh::flip14count
Definition at line 1349 of file tetgen.h.
View newest version in sPHENIX GitHub at line 1349 of file tetgen.h
Referenced by insertpoint(), and tetgenmesh().
long tetgenmesh::flip22count
Definition at line 1351 of file tetgen.h.
View newest version in sPHENIX GitHub at line 1351 of file tetgen.h
Referenced by flip22(), lawsonflip3d(), and tetgenmesh().
long tetgenmesh::flip23count
Definition at line 1350 of file tetgen.h.
View newest version in sPHENIX GitHub at line 1350 of file tetgen.h
Referenced by delaunayrefinement(), flip23(), flipinsertfacet(), lawsonflip3d(), and tetgenmesh().
long tetgenmesh::flip26count
Definition at line 1349 of file tetgen.h.
View newest version in sPHENIX GitHub at line 1349 of file tetgen.h
Referenced by insertpoint(), and tetgenmesh().
long tetgenmesh::flip31count
Definition at line 1351 of file tetgen.h.
View newest version in sPHENIX GitHub at line 1351 of file tetgen.h
Referenced by flip31(), and tetgenmesh().
long tetgenmesh::flip32count
Definition at line 1350 of file tetgen.h.
View newest version in sPHENIX GitHub at line 1350 of file tetgen.h
Referenced by delaunayrefinement(), flip32(), flipinsertfacet(), lawsonflip3d(), and tetgenmesh().
long tetgenmesh::flip41count
Definition at line 1350 of file tetgen.h.
View newest version in sPHENIX GitHub at line 1350 of file tetgen.h
Referenced by flip41(), and tetgenmesh().
long tetgenmesh::flip44count
Definition at line 1350 of file tetgen.h.
View newest version in sPHENIX GitHub at line 1350 of file tetgen.h
Referenced by delaunayrefinement(), flipinsertfacet(), lawsonflip3d(), and tetgenmesh().
long tetgenmesh::flipn2ncount
Definition at line 1349 of file tetgen.h.
View newest version in sPHENIX GitHub at line 1349 of file tetgen.h
Referenced by insertpoint(), and tetgenmesh().
memorypool* tetgenmesh::flippool
Definition at line 1273 of file tetgen.h.
View newest version in sPHENIX GitHub at line 1273 of file tetgen.h
Referenced by fillregion(), flipcertify(), flipinsertfacet(), flippush(), flipshpush(), freememory(), incrementalflip(), initializepools(), lawsonflip(), lawsonflip3d(), memorystatistics(), recoverdelaunay(), tetgenmesh(), and unifysegments().
badface* tetgenmesh::flipstack
Definition at line 1275 of file tetgen.h.
View newest version in sPHENIX GitHub at line 1275 of file tetgen.h
Referenced by carveholes(), fillregion(), flip23(), flip32(), flip41(), flipshpush(), incrementaldelaunay(), incrementalflip(), insertconstrainedpoints(), insertpoint(), lawsonflip(), lawsonflip3d(), mergefacets(), recoverdelaunay(), splitsegment(), splitsubface(), splittetrahedron(), tetgenmesh(), and triangulate().
int tetgenmesh::fsymtbl = {{0,},} static
Definition at line 1362 of file tetgen.h.
View newest version in sPHENIX GitHub at line 1362 of file tetgen.h
Referenced by fsym(), and inittables().
point* tetgenmesh::highordertable
Definition at line 1307 of file tetgen.h.
View newest version in sPHENIX GitHub at line 1307 of file tetgen.h
Referenced by freememory(), highorder(), and tetgenmesh().
long tetgenmesh::hullsize
Definition at line 1340 of file tetgen.h.
View newest version in sPHENIX GitHub at line 1340 of file tetgen.h
Referenced by carvecavity(), carveholes(), delaunizecavity(), flip23(), flip32(), flip41(), initialdelaunay(), insertpoint(), outedges(), outelements(), outfaces(), outhullfaces(), outmesh2medit(), outmesh2vtk(), outneighbors(), outvoronoi(), reconstructmesh(), statistics(), suppressbdrysteinerpoint(), and tetgenmesh().
int* tetgenmesh::idx2facetlist
Definition at line 1290 of file tetgen.h.
View newest version in sPHENIX GitHub at line 1290 of file tetgen.h
Referenced by facetfacetadjacent(), freememory(), makefacetverticesmap(), segfacetadjacent(), and tetgenmesh().
tetgenio* tetgenmesh::in
Definition at line 1256 of file tetgen.h.
View newest version in sPHENIX GitHub at line 1256 of file tetgen.h
Referenced by carveholes(), checktet4split(), collectremovepoints(), highorder(), identifypscedges(), incrementaldelaunay(), initializepools(), insertconstrainedpoints(), jettisonnodes(), main(), makeindex2pointmap(), makepoint(), makepoint2submap(), mergefacets(), meshsurface(), outedges(), outelements(), outfaces(), outhullfaces(), outmesh2medit(), outmesh2vtk(), outneighbors(), outnodes(), outsmesh(), outsubfaces(), outsubsegments(), outvoronoi(), reconstructmesh(), statistics(), tetgenmesh(), tetrahedralize(), transfernodes(), triangulate(), and unifysegments().
long tetgenmesh::insegments
Definition at line 1339 of file tetgen.h.
View newest version in sPHENIX GitHub at line 1339 of file tetgen.h
Referenced by meshsurface(), reconstructmesh(), statistics(), and tetgenmesh().
REAL tetgenmesh::longest
Definition at line 1335 of file tetgen.h.
View newest version in sPHENIX GitHub at line 1335 of file tetgen.h
Referenced by qualitystatistics(), randomsample(), tetgenmesh(), and transfernodes().
long tetgenmesh::meshedges
Definition at line 1341 of file tetgen.h.
View newest version in sPHENIX GitHub at line 1341 of file tetgen.h
Referenced by numberedges(), outedges(), statistics(), and tetgenmesh().
long tetgenmesh::meshhulledges
Definition at line 1342 of file tetgen.h.
View newest version in sPHENIX GitHub at line 1342 of file tetgen.h
Referenced by numberedges(), statistics(), and tetgenmesh().
REAL tetgenmesh::minfaceang
Definition at line 1333 of file tetgen.h.
View newest version in sPHENIX GitHub at line 1333 of file tetgen.h
Referenced by qualitystatistics(), and tetgenmesh().
REAL tetgenmesh::minfacetdihed
Definition at line 1333 of file tetgen.h.
View newest version in sPHENIX GitHub at line 1333 of file tetgen.h
Referenced by qualitystatistics(), and tetgenmesh().
int tetgenmesh::nonconvex
Definition at line 1325 of file tetgen.h.
View newest version in sPHENIX GitHub at line 1325 of file tetgen.h
Referenced by carveholes(), finddirection(), flipnm(), insertpoint(), lawsonflip3d(), outedges(), randomsample(), reconstructmesh(), reduceedgesatvertex(), statistics(), and tetgenmesh().
long tetgenmesh::nonregularcount
Definition at line 1346 of file tetgen.h.
View newest version in sPHENIX GitHub at line 1346 of file tetgen.h
Referenced by insertconstrainedpoints(), insertpoint(), interpolatemeshsize(), outedges(), outvoronoi(), scoutpoint(), statistics(), and tetgenmesh().
int tetgenmesh::numelemattrib
Definition at line 1311 of file tetgen.h.
View newest version in sPHENIX GitHub at line 1311 of file tetgen.h
Referenced by carveholes(), checktet4split(), flip23(), flip32(), initializepools(), insertpoint(), maketetrahedron(), optimizemesh(), outelements(), outmesh2medit(), outmesh2vtk(), qualitystatistics(), and tetgenmesh().
int tetgenmesh::numpointattrib
Definition at line 1310 of file tetgen.h.
View newest version in sPHENIX GitHub at line 1310 of file tetgen.h
Referenced by highorder(), initializepools(), makepoint(), outnodes(), and tetgenmesh().
int tetgenmesh::oppopivot = {4, 5, 6, 7, 4, 5, 6, 7, 4, 5, 6, 7} static
Definition at line 1367 of file tetgen.h.
View newest version in sPHENIX GitHub at line 1367 of file tetgen.h
Referenced by oppo(), and setoppo().
int tetgenmesh::orgpivot = {7, 7, 5, 5, 6, 4, 4, 6, 5, 6, 7, 4} static
Definition at line 1367 of file tetgen.h.
View newest version in sPHENIX GitHub at line 1367 of file tetgen.h
Referenced by org(), and setorg().
REAL tetgenmesh::PI = 3.14159265358979323846264338327950288419716939937510582 static
Definition at line 1303 of file tetgen.h.
View newest version in sPHENIX GitHub at line 1303 of file tetgen.h
Referenced by delaunayrefinement(), facedihedral(), interiorangle(), mergefacets(), optimizemesh(), qualitystatistics(), reconstructmesh(), scoutsegment(), and tetgenmesh().
int tetgenmesh::point2simindex
Definition at line 1315 of file tetgen.h.
View newest version in sPHENIX GitHub at line 1315 of file tetgen.h
Referenced by initializepools(), point2bgmtet(), point2ppt(), point2sh(), point2tet(), setpoint2bgmtet(), setpoint2ppt(), setpoint2sh(), setpoint2tet(), and tetgenmesh().
int tetgenmesh::pointmarkindex
Definition at line 1316 of file tetgen.h.
View newest version in sPHENIX GitHub at line 1316 of file tetgen.h
Referenced by initializepools(), makepoint(), pinfect(), pinfected(), pmarktest(), pmarktest2(), pmarktest2ed(), pmarktest3(), pmarktest3ed(), pmarktested(), pointgeomtag(), pointmark(), pointtype(), puninfect(), punmarktest(), punmarktest2(), punmarktest3(), setpointgeomtag(), setpointmark(), setpointtype(), and tetgenmesh().
int tetgenmesh::pointmtrindex
Definition at line 1313 of file tetgen.h.
View newest version in sPHENIX GitHub at line 1313 of file tetgen.h
Referenced by checkfac4encroach(), checkfac4split(), checkseg4encroach(), checkseg4split(), checktet4split(), collectremovepoints(), getpointinsradius(), getpointmeshsize(), highorder(), initializepools(), insertconstrainedpoints(), insertpoint(), interpolatemeshsize(), makepoint(), outmetrics(), setpointinsradius(), tetgenmesh(), and transfernodes().
int tetgenmesh::pointparamindex
Definition at line 1314 of file tetgen.h.
View newest version in sPHENIX GitHub at line 1314 of file tetgen.h
Referenced by initializepools(), pointgeomuv(), setpointgeomuv(), and tetgenmesh().
memorypool * tetgenmesh::points
Definition at line 1266 of file tetgen.h.
View newest version in sPHENIX GitHub at line 1266 of file tetgen.h
Referenced by carveholes(), checksegments(), collectremovepoints(), delaunayrefinement(), freememory(), highorder(), identifypscedges(), incrementaldelaunay(), initializepools(), interpolatemeshsize(), jettisonnodes(), makeindex2pointmap(), makepoint(), makepoint2submap(), memorystatistics(), outedges(), outmesh2medit(), outmesh2vtk(), outmetrics(), outnodes(), outvoronoi(), pointdealloc(), pointtraverse(), reconstructmesh(), refineregion(), statistics(), and tetgenmesh().
unsigned long tetgenmesh::randomseed
Definition at line 1329 of file tetgen.h.
View newest version in sPHENIX GitHub at line 1329 of file tetgen.h
Referenced by randomnation(), and tetgenmesh().
face tetgenmesh::recentsh
Definition at line 1300 of file tetgen.h.
View newest version in sPHENIX GitHub at line 1300 of file tetgen.h
Referenced by constrainedfacets(), fillcavity(), fillregion(), flip22(), flip31(), formcavity(), scarveholes(), sinsertvertex(), and triangulate().
triface tetgenmesh::recenttet
Definition at line 1299 of file tetgen.h.
View newest version in sPHENIX GitHub at line 1299 of file tetgen.h
Referenced by carvecavity(), delaunizecavity(), flip23(), flip32(), flip41(), formcavity(), incrementaldelaunay(), initialdelaunay(), insertpoint(), locate(), randomsample(), reconstructmesh(), restorecavity(), and scoutpoint().
long tetgenmesh::samples
Definition at line 1328 of file tetgen.h.
View newest version in sPHENIX GitHub at line 1328 of file tetgen.h
Referenced by insertconstrainedpoints(), interpolatemeshsize(), randomsample(), and tetgenmesh().
int tetgenmesh::sapexpivot = {5, 5, 3, 3, 4, 4} static
Definition at line 1371 of file tetgen.h.
View newest version in sPHENIX GitHub at line 1371 of file tetgen.h
Referenced by sapex(), and setsapex().
int tetgenmesh::sdestpivot = {4, 3, 5, 4, 3, 5} static
Definition at line 1371 of file tetgen.h.
View newest version in sPHENIX GitHub at line 1371 of file tetgen.h
Referenced by sdest(), and setsdest().
point* tetgenmesh::segmentendpointslist
Definition at line 1294 of file tetgen.h.
View newest version in sPHENIX GitHub at line 1294 of file tetgen.h
Referenced by freememory(), getsteinerptonsegment(), makesegmentendpointsmap(), segfacetadjacent(), segsegadjacent(), and tetgenmesh().
int tetgenmesh::shmarkindex
Definition at line 1320 of file tetgen.h.
View newest version in sPHENIX GitHub at line 1320 of file tetgen.h
Referenced by getfacetindex(), initializepools(), makeshellface(), setfacetindex(), setshellmark(), shellmark(), sinfect(), sinfected(), smarktest(), smarktest2(), smarktest2ed(), smarktest3(), smarktest3ed(), smarktested(), suninfect(), sunmarktest(), sunmarktest2(), sunmarktest3(), and tetgenmesh().
int tetgenmesh::sizeoftensor
Definition at line 1312 of file tetgen.h.
View newest version in sPHENIX GitHub at line 1312 of file tetgen.h
Referenced by getpointinsradius(), initializepools(), makepoint(), setpointinsradius(), and tetgenmesh().
int tetgenmesh::snextpivot = {2, 5, 4, 1, 0, 3} static
Definition at line 1372 of file tetgen.h.
View newest version in sPHENIX GitHub at line 1372 of file tetgen.h
Referenced by senext(), senext2(), senext2self(), and senextself().
int tetgenmesh::sorgpivot = {3, 4, 4, 5, 5, 3} static
Definition at line 1371 of file tetgen.h.
View newest version in sPHENIX GitHub at line 1371 of file tetgen.h
Referenced by setsorg(), and sorg().
long tetgenmesh::st_facref_count
Definition at line 1347 of file tetgen.h.
View newest version in sPHENIX GitHub at line 1347 of file tetgen.h
Referenced by carveholes(), constraineddelaunay(), delaunayrefinement(), insertconstrainedpoints(), reconstructmesh(), recoverboundary(), recoverfacebyflips(), recoversubfaces(), refineregion(), removevertexbyflips(), splitsubface(), statistics(), suppressbdrysteinerpoint(), and tetgenmesh().
long tetgenmesh::st_segref_count
Definition at line 1347 of file tetgen.h.
View newest version in sPHENIX GitHub at line 1347 of file tetgen.h
Referenced by add_steinerpt_in_segment(), addsteiner4recoversegment(), carveholes(), constraineddelaunay(), delaunayrefinement(), delaunizesegments(), insertconstrainedpoints(), reconstructmesh(), recoverboundary(), recoversegments(), refineregion(), removevertexbyflips(), splitsegment(), statistics(), suppressbdrysteinerpoint(), and tetgenmesh().
long tetgenmesh::st_volref_count
Definition at line 1347 of file tetgen.h.
View newest version in sPHENIX GitHub at line 1347 of file tetgen.h
Referenced by add_steinerpt_in_schoenhardtpoly(), add_steinerpt_in_segment(), carveholes(), delaunayrefinement(), insertconstrainedpoints(), reconstructmesh(), recoverboundary(), recoverfacebyflips(), recoversegments(), removevertexbyflips(), splitsliver(), splittetrahedron(), statistics(), suppressbdrysteinerpoint(), and tetgenmesh().
int tetgenmesh::stbondtbl = {{0,},} static
Definition at line 1368 of file tetgen.h.
View newest version in sPHENIX GitHub at line 1368 of file tetgen.h
Referenced by inittables(), and tsbond().
long tetgenmesh::steinerleft
Definition at line 1343 of file tetgen.h.
View newest version in sPHENIX GitHub at line 1343 of file tetgen.h
Referenced by add_steinerpt_in_schoenhardtpoly(), add_steinerpt_in_segment(), addsteiner4recoversegment(), carveholes(), delaunayrefinement(), delaunizesegments(), recoversubfaces(), refineregion(), removeslivers(), removevertexbyflips(), repairbadtets(), repairencfacs(), repairencsegs(), splitsegment(), splitsliver(), splitsubface(), splittetrahedron(), suppressbdrysteinerpoint(), and tetgenmesh().
int tetgenmesh::stpivottbl = {{0,},} static
Definition at line 1369 of file tetgen.h.
View newest version in sPHENIX GitHub at line 1369 of file tetgen.h
Referenced by inittables(), and stpivot().
memorypool * tetgenmesh::subfaces
Definition at line 1266 of file tetgen.h.
View newest version in sPHENIX GitHub at line 1266 of file tetgen.h
Referenced by carveholes(), checkconforming(), checkshells(), constraineddelaunay(), delaunayrefinement(), delaunizecavity(), detectinterfaces(), fillcavity(), fillregion(), flip31(), flip41(), freememory(), identifypscedges(), initializepools(), insertpoint(), insertpoint_cdt(), makefacetverticesmap(), memorystatistics(), meshsurface(), outsmesh(), outsubfaces(), reconstructmesh(), recoverboundary(), recoverfacebyflips(), scarveholes(), sinsertvertex(), sremovevertex(), statistics(), tetgenmesh(), tetrahedralize(), triangulate(), and unifysegments().
arraypool * tetgenmesh::subfacstack
Definition at line 1284 of file tetgen.h.
View newest version in sPHENIX GitHub at line 1284 of file tetgen.h
Referenced by carveholes(), constraineddelaunay(), constrainedfacets(), freememory(), initializepools(), insertpoint(), insertpoint_cdt(), memorystatistics(), recoverboundary(), recoverfacebyflips(), recoversubfaces(), and tetgenmesh().
memorypool * tetgenmesh::subsegs
Definition at line 1266 of file tetgen.h.
View newest version in sPHENIX GitHub at line 1266 of file tetgen.h
Referenced by carveholes(), checkconforming(), checksegments(), constraineddelaunay(), delaunayrefinement(), fillcavity(), fillregion(), formregion(), freememory(), identifypscedges(), initializepools(), insertpoint(), insertpoint_cdt(), makesegmentendpointsmap(), memorystatistics(), mergefacets(), meshsurface(), outmesh2medit(), outsubsegments(), reconstructmesh(), recoverboundary(), recoversubfaces(), restorecavity(), sinsertvertex(), sremovevertex(), sscoutsegment(), statistics(), tetgenmesh(), triangulate(), and unifysegments().
arraypool* tetgenmesh::subsegstack
Definition at line 1284 of file tetgen.h.
View newest version in sPHENIX GitHub at line 1284 of file tetgen.h
Referenced by add_steinerpt_in_segment(), addsteiner4recoversegment(), constraineddelaunay(), delaunizesegments(), freememory(), initializepools(), insertpoint(), insertpoint_cdt(), memorystatistics(), recoverboundary(), recoversegments(), refineregion(), and tetgenmesh().
arraypool * tetgenmesh::subvertstack
Definition at line 1284 of file tetgen.h.
View newest version in sPHENIX GitHub at line 1284 of file tetgen.h
Referenced by add_steinerpt_in_segment(), addsteiner4recoversegment(), carveholes(), freememory(), initializepools(), memorystatistics(), recoverboundary(), recoverfacebyflips(), recoversubfaces(), suppressbdrysteinerpoint(), suppresssteinerpoints(), tetgenmesh(), and tetrahedralize().
memorypool * tetgenmesh::tet2segpool
Definition at line 1267 of file tetgen.h.
View newest version in sPHENIX GitHub at line 1267 of file tetgen.h
Referenced by flip23(), flip32(), flip41(), freememory(), initializepools(), memorystatistics(), tetgenmesh(), tetrahedrondealloc(), and tssbond1().
memorypool* tetgenmesh::tet2subpool
Definition at line 1267 of file tetgen.h.
View newest version in sPHENIX GitHub at line 1267 of file tetgen.h
Referenced by flip23(), flip32(), flip41(), freememory(), initializepools(), memorystatistics(), tetgenmesh(), tetrahedrondealloc(), and tsbond().
REAL tetgenmesh::tetprism_vol_sum
Definition at line 1334 of file tetgen.h.
View newest version in sPHENIX GitHub at line 1334 of file tetgen.h
Referenced by lawsonflip3d(), recoverdelaunay(), and tetgenmesh().
memorypool* tetgenmesh::tetrahedrons
Definition at line 1266 of file tetgen.h.
View newest version in sPHENIX GitHub at line 1266 of file tetgen.h
Referenced by alltetrahedrontraverse(), carveholes(), checkdelaunay(), checkmesh(), checkregular(), checksegments(), delaunayrefinement(), freememory(), highorder(), initializepools(), maketetrahedron(), memorystatistics(), numberedges(), optimizemesh(), outedges(), outelements(), outfaces(), outhullfaces(), outmesh2medit(), outmesh2vtk(), outneighbors(), outvoronoi(), qualitystatistics(), randomsample(), reconstructmesh(), recoverdelaunay(), scoutpoint(), statistics(), tetgenmesh(), tetrahedralize(), tetrahedrondealloc(), and tetrahedrontraverse().
unsigned long tetgenmesh::totalworkmemory
Definition at line 1352 of file tetgen.h.
View newest version in sPHENIX GitHub at line 1352 of file tetgen.h
Referenced by constrainedfacets(), delaunayrefinement(), makefacetverticesmap(), makesegmentendpointsmap(), memorystatistics(), recoverboundary(), and tetgenmesh().
int tetgenmesh::transgc[8][3][8]
Definition at line 1734 of file tetgen.h.
View newest version in sPHENIX GitHub at line 1734 of file tetgen.h
Referenced by hilbert_init(), and hilbert_sort3().
int tetgenmesh::tsb1mod3[8]
Definition at line 1734 of file tetgen.h.
View newest version in sPHENIX GitHub at line 1734 of file tetgen.h
Referenced by hilbert_init(), and hilbert_sort3().
int tetgenmesh::tsbondtbl = {{0,},} static
Definition at line 1368 of file tetgen.h.
View newest version in sPHENIX GitHub at line 1368 of file tetgen.h
Referenced by inittables(), and tsbond().
int tetgenmesh::tspivottbl = {{0,},} static
Definition at line 1369 of file tetgen.h.
View newest version in sPHENIX GitHub at line 1369 of file tetgen.h
Referenced by inittables(), and tspivot().
arraypool* tetgenmesh::unflipqueue
Definition at line 1274 of file tetgen.h.
View newest version in sPHENIX GitHub at line 1274 of file tetgen.h
Referenced by carveholes(), freememory(), improvequalitybyflips(), improvequalitybysmoothing(), initializepools(), insertconstrainedpoints(), lawsonflip3d(), memorystatistics(), optimizemesh(), recoverdelaunay(), removeslivers(), splitsegment(), splitsubface(), splittetrahedron(), and tetgenmesh().
long tetgenmesh::unuverts
Definition at line 1345 of file tetgen.h.
View newest version in sPHENIX GitHub at line 1345 of file tetgen.h
Referenced by carveholes(), flip41(), insertconstrainedpoints(), jettisonnodes(), outedges(), outvoronoi(), removevertexbyflips(), statistics(), suppressbdrysteinerpoint(), tetgenmesh(), and tetrahedralize().
int tetgenmesh::useinsertradius
Definition at line 1327 of file tetgen.h.
View newest version in sPHENIX GitHub at line 1327 of file tetgen.h
Referenced by checkseg4split(), checktet4split(), delaunayrefinement(), flip31(), initializepools(), makeshellface(), sinsertvertex(), splitsegment(), splitsubface(), splittetrahedron(), sremovevertex(), and tetgenmesh().
int tetgenmesh::ver2edge = {0, 1, 2, 3, 3, 5, 1, 5, 4, 0, 4, 2} static
Definition at line 1370 of file tetgen.h.
View newest version in sPHENIX GitHub at line 1370 of file tetgen.h
Referenced by edgemarked(), highorder(), markedge(), outedges(), outfaces(), outsubfaces(), outsubsegments(), outvoronoi(), tssbond1(), tssdissolve1(), tsspivot1(), and unmarkedge().
int tetgenmesh::volumeboundindex
Definition at line 1318 of file tetgen.h.
View newest version in sPHENIX GitHub at line 1318 of file tetgen.h
Referenced by initializepools(), setvolumebound(), tetgenmesh(), and volumebound().
REAL tetgenmesh::xmax
Definition at line 1336 of file tetgen.h.
View newest version in sPHENIX GitHub at line 1336 of file tetgen.h
Referenced by brio_multiscale_sort(), detectinterfaces(), incrementaldelaunay(), insertconstrainedpoints(), qualitystatistics(), tetgenmesh(), tetrahedralize(), and transfernodes().
REAL tetgenmesh::xmin
Definition at line 1336 of file tetgen.h.
View newest version in sPHENIX GitHub at line 1336 of file tetgen.h
Referenced by brio_multiscale_sort(), detectinterfaces(), incrementaldelaunay(), insertconstrainedpoints(), qualitystatistics(), tetgenmesh(), tetrahedralize(), and transfernodes().
REAL tetgenmesh::ymax
Definition at line 1336 of file tetgen.h.
View newest version in sPHENIX GitHub at line 1336 of file tetgen.h
Referenced by brio_multiscale_sort(), detectinterfaces(), incrementaldelaunay(), insertconstrainedpoints(), qualitystatistics(), tetgenmesh(), tetrahedralize(), and transfernodes().
REAL tetgenmesh::ymin
Definition at line 1336 of file tetgen.h.
View newest version in sPHENIX GitHub at line 1336 of file tetgen.h
Referenced by brio_multiscale_sort(), detectinterfaces(), incrementaldelaunay(), insertconstrainedpoints(), qualitystatistics(), tetgenmesh(), tetrahedralize(), and transfernodes().
REAL tetgenmesh::zmax
Definition at line 1336 of file tetgen.h.
View newest version in sPHENIX GitHub at line 1336 of file tetgen.h
Referenced by brio_multiscale_sort(), detectinterfaces(), incrementaldelaunay(), insertconstrainedpoints(), qualitystatistics(), tetgenmesh(), tetrahedralize(), and transfernodes().
REAL tetgenmesh::zmin
Definition at line 1336 of file tetgen.h.
View newest version in sPHENIX GitHub at line 1336 of file tetgen.h
Referenced by brio_multiscale_sort(), detectinterfaces(), incrementaldelaunay(), insertconstrainedpoints(), qualitystatistics(), tetgenmesh(), tetrahedralize(), and transfernodes().
The documentation for this class was generated from the following files:
EicRoot/blob/master/eic/cad/tetgen/tetgen.h
EicRoot/blob/master/eic/cad/tetgen/tetgen.cxx