EIC Software: ServiceStructure Class Reference
ServiceStructure Class Reference
Public Member Functions
ServiceStructure ()
ServiceStructure (const string &name, const float &thickness_copper, const float &thickness_water, const float &thickness_plastic, const float &thickness_carbon, const float &zSouth, const float &zNorth, const float &rSouth, const float &rNorth)
virtual ~ServiceStructure ()
const string get_name ()
const float get_thickness_copper ()
const float get_thickness_water ()
const float get_thickness_plastic ()
const float get_thickness_carbon ()
const float get_zSouth ()
const float get_zNorth ()
const float get_rSouth ()
const float get_rNorth ()
Private Attributes
const string m_name = "service"
const float m_thickness_copper = 0.0
const float m_thickness_water = 0.0
const float m_thickness_plastic = 0.0
const float m_thickness_carbon = 0.0
const float m_zSouth = 0.0
const float m_zNorth = 0.0
const float m_rSouth = 0.0
const float m_rNorth = 0.0
Detailed Description
Definition at line 25 of file G4_TrackingService.C.
View newest version in sPHENIX GitHub at line 25 of file G4_TrackingService.C
Constructor & Destructor Documentation
ServiceStructure::ServiceStructure ()
ServiceStructure::ServiceStructure (const string & name, const float & thickness_copper, const float & thickness_water, const float & thickness_plastic, const float & thickness_carbon, const float & zSouth, const float & zNorth, const float & rSouth, const float & rNorth) explicit
Definition at line 64 of file G4_TrackingService.C.
View newest version in sPHENIX GitHub at line 64 of file G4_TrackingService.C
virtual ServiceStructure::~ServiceStructure () inline virtual
Definition at line 40 of file G4_TrackingService.C.
View newest version in sPHENIX GitHub at line 40 of file G4_TrackingService.C
Member Function Documentation
const string ServiceStructure::get_name (void)
Definition at line 85 of file G4_TrackingService.C.
View newest version in sPHENIX GitHub at line 85 of file G4_TrackingService.C
References m_name.
Referenced by TrackingServiceCone(), and TrackingServiceCylinder().
const float ServiceStructure::get_rNorth ()
Definition at line 93 of file G4_TrackingService.C.
View newest version in sPHENIX GitHub at line 93 of file G4_TrackingService.C
References m_rNorth.
const float ServiceStructure::get_rSouth ()
Definition at line 92 of file G4_TrackingService.C.
View newest version in sPHENIX GitHub at line 92 of file G4_TrackingService.C
References m_rSouth.
const float ServiceStructure::get_thickness_carbon ()
Definition at line 89 of file G4_TrackingService.C.
View newest version in sPHENIX GitHub at line 89 of file G4_TrackingService.C
References m_thickness_carbon.
const float ServiceStructure::get_thickness_copper ()
Definition at line 86 of file G4_TrackingService.C.
View newest version in sPHENIX GitHub at line 86 of file G4_TrackingService.C
References m_thickness_copper.
const float ServiceStructure::get_thickness_plastic ()
Definition at line 88 of file G4_TrackingService.C.
View newest version in sPHENIX GitHub at line 88 of file G4_TrackingService.C
References m_thickness_plastic.
const float ServiceStructure::get_thickness_water ()
Definition at line 87 of file G4_TrackingService.C.
View newest version in sPHENIX GitHub at line 87 of file G4_TrackingService.C
References m_thickness_water.
const float ServiceStructure::get_zNorth ()
Definition at line 91 of file G4_TrackingService.C.
View newest version in sPHENIX GitHub at line 91 of file G4_TrackingService.C
References m_zNorth.
Referenced by TrackingServiceCone(), and TrackingServiceCylinder().
const float ServiceStructure::get_zSouth ()
Definition at line 90 of file G4_TrackingService.C.
View newest version in sPHENIX GitHub at line 90 of file G4_TrackingService.C
References m_zSouth.
Referenced by TrackingServiceCone(), and TrackingServiceCylinder().
Member Data Documentation
const string ServiceStructure::m_name = "service" private
Definition at line 53 of file G4_TrackingService.C.
View newest version in sPHENIX GitHub at line 53 of file G4_TrackingService.C
Referenced by get_name().
const float ServiceStructure::m_rNorth = 0.0 private
Definition at line 61 of file G4_TrackingService.C.
View newest version in sPHENIX GitHub at line 61 of file G4_TrackingService.C
Referenced by get_rNorth().
const float ServiceStructure::m_rSouth = 0.0 private
Definition at line 60 of file G4_TrackingService.C.
View newest version in sPHENIX GitHub at line 60 of file G4_TrackingService.C
Referenced by get_rSouth().
const float ServiceStructure::m_thickness_carbon = 0.0 private
Definition at line 57 of file G4_TrackingService.C.
View newest version in sPHENIX GitHub at line 57 of file G4_TrackingService.C
Referenced by get_thickness_carbon().
const float ServiceStructure::m_thickness_copper = 0.0 private
Definition at line 54 of file G4_TrackingService.C.
View newest version in sPHENIX GitHub at line 54 of file G4_TrackingService.C
Referenced by get_thickness_copper().
const float ServiceStructure::m_thickness_plastic = 0.0 private
Definition at line 56 of file G4_TrackingService.C.
View newest version in sPHENIX GitHub at line 56 of file G4_TrackingService.C
Referenced by get_thickness_plastic().
const float ServiceStructure::m_thickness_water = 0.0 private
Definition at line 55 of file G4_TrackingService.C.
View newest version in sPHENIX GitHub at line 55 of file G4_TrackingService.C
Referenced by get_thickness_water().
const float ServiceStructure::m_zNorth = 0.0 private
Definition at line 59 of file G4_TrackingService.C.
View newest version in sPHENIX GitHub at line 59 of file G4_TrackingService.C
Referenced by get_zNorth().
const float ServiceStructure::m_zSouth = 0.0 private
Definition at line 58 of file G4_TrackingService.C.
View newest version in sPHENIX GitHub at line 58 of file G4_TrackingService.C
Referenced by get_zSouth().
The documentation for this class was generated from the following file:
fun4all_macros/blob/master/common/G4_TrackingService.C