EIC Software: Acts::DiscLayer Class Reference
Acts::DiscLayer Class Reference
#include <fun4all_acts/blob/master/Core/include/Acts/Geometry/DiscLayer.hpp>
Public Member Functions
DiscLayer ()=delete
Default Constructor.
DiscLayer (const DiscLayer &cla)=delete
Copy constructor of DiscLayer - deleted.
DiscLayer & operator= (const DiscLayer &)=delete
Assignment operator for DiscLayers - deleted.
~DiscLayer () override=default
Destructor.
const DiscSurface & surfaceRepresentation () const override
DiscSurface & surfaceRepresentation () override
Public Member Functions inherited from Acts::Layer
Layer ()=delete
Default Constructor - deleted.
Layer (const Layer &)=delete
Copy Constructor - deleted.
virtual ~Layer ()=default
Destructor.
Layer & operator= (const Layer &)=delete
const SurfaceArray * surfaceArray () const
Return the entire SurfaceArray, returns a nullptr if no SurfaceArray.
SurfaceArray * surfaceArray ()
Non-const version.
double thickness () const
virtual bool isOnLayer (const GeometryContext &gctx, const Vector3D &position, const BoundaryCheck &bcheck=true) const
const ApproachDescriptor * approachDescriptor () const
Return method for the approach descriptor, can be nullptr.
ApproachDescriptor * approachDescriptor ()
Non-const version of the approach descriptor.
template<typename options_t >
bool resolve (const options_t &options) const
virtual bool resolve (bool resolveSensitive, bool resolveMaterial, bool resolvePassive) const
template<typename options_t >
std::vector< SurfaceIntersection > compatibleSurfaces (const GeometryContext &gctx, const Vector3D &position, const Vector3D &direction, const options_t &options) const
Decompose Layer into (compatible) surfaces.
template<typename options_t >
const SurfaceIntersection surfaceOnApproach (const GeometryContext &gctx, const Vector3D &position, const Vector3D &direction, const options_t &options) const
const Layer * nextLayer (const GeometryContext &gctx, const Vector3D &position, const Vector3D &direction) const
const TrackingVolume * trackingVolume () const
const AbstractVolume * representingVolume () const
LayerType layerType () const
return the LayerType
Public Member Functions inherited from Acts::GeometryObject
GeometryObject ()=default
Defaulted construrctor.
GeometryObject (const GeometryObject &)=default
Defaulted copy constructor.
GeometryObject (const GeometryID &geoID)
GeometryObject & operator= (const GeometryObject &geoID)
const GeometryID & geoID () const
virtual const Vector3D binningPosition (const GeometryContext &gctx, BinningValue bValue) const =0
virtual double binningPositionValue (const GeometryContext &gctx, BinningValue bValue) const
void assignGeoID (const GeometryID &geoID)
Static Public Member Functions
static MutableLayerPtr create (const std::shared_ptr< const Transform3D > &transform, const std::shared_ptr< const DiscBounds > &dbounds, std::unique_ptr< SurfaceArray > surfaceArray=nullptr, double thickness=0., std::unique_ptr< ApproachDescriptor > ad=nullptr, LayerType laytyp=Acts::passive)
Protected Member Functions
DiscLayer (const std::shared_ptr< const Transform3D > &transform, const std::shared_ptr< const DiscBounds > &dbounds, std::unique_ptr< SurfaceArray > surfaceArray=nullptr, double thickness=0., std::unique_ptr< ApproachDescriptor > ades=nullptr, LayerType laytyp=Acts::active)
DiscLayer (const DiscLayer &cla, const Transform3D &tr)
Copy constructor with shift.
Protected Member Functions inherited from Acts::Layer
Layer (std::unique_ptr< SurfaceArray > surfaceArray, double thickness=0., std::unique_ptr< ApproachDescriptor > ades=nullptr, LayerType laytyp=passive)
void encloseTrackingVolume (const TrackingVolume &tvol)
Private Member Functions
void buildApproachDescriptor ()
build approach surfaces
Additional Inherited Members
Protected Attributes inherited from Acts::Layer
NextLayers m_nextLayers
the previous Layer according to BinGenUtils
const BinUtility * m_nextLayerUtility = nullptr
std::unique_ptr< const
SurfaceArray > m_surfaceArray = nullptr
double m_layerThickness = 0.
Thickness of the Layer.
std::unique_ptr< const
ApproachDescriptor > m_approachDescriptor = nullptr
const TrackingVolume * m_trackingVolume = nullptr
the enclosing TrackingVolume
std::unique_ptr< AbstractVolume > m_representingVolume = nullptr
LayerType m_layerType
make a passive/active either way
int m_ssRepresentingSurface = 0
sub structure indication
int m_ssSensitiveSurfaces = 0
int m_ssApproachSurfaces = 0
Detailed Description
Class to describe a disc-like detector layer for tracking, it inhertis from both, Layer base class and DiscSurface class
Definition at line 32 of file DiscLayer.hpp.
View newest version in sPHENIX GitHub at line 32 of file DiscLayer.hpp
Constructor & Destructor Documentation
Acts::DiscLayer::DiscLayer () delete
Default Constructor.
Referenced by create().
Acts::DiscLayer::DiscLayer (const DiscLayer & cla) delete
Copy constructor of DiscLayer - deleted.
Acts::DiscLayer::~DiscLayer () override default
Destructor.
Acts::DiscLayer::DiscLayer (const std::shared_ptr< const Transform3D > & transform, const std::shared_ptr< const DiscBounds > & dbounds, std::unique_ptr< SurfaceArray > surfaceArray = nullptr, double thickness = 0., std::unique_ptr< ApproachDescriptor > ades = nullptr, LayerType laytyp = Acts::active) protected
Parameters
transform is the transform to place the layer in the 3D frame
dbounds are the disc bounds that describe the layer dimensions
surfaceArray is the array of sensitive surfaces
thickness is the layer thickness (along the normal vector)
ad is the approach descriptor that provides the approach surface
laytyp is the layer taype
Definition at line 27 of file DiscLayer.cpp.
View newest version in sPHENIX GitHub at line 27 of file DiscLayer.cpp
References Acts::Layer::approachDescriptor(), buildApproachDescriptor(), Acts::Layer::m_approachDescriptor, Acts::Layer::m_representingVolume, Acts::Layer::m_surfaceArray, Acts::ApproachDescriptor::registerLayer(), and Acts::Layer::thickness().
Acts::DiscLayer::DiscLayer (const DiscLayer & cla, const Transform3D & tr) protected
Copy constructor with shift.
Member Function Documentation
void Acts::DiscLayer::buildApproachDescriptor () private
build approach surfaces
Definition at line 66 of file DiscLayer.cpp.
View newest version in sPHENIX GitHub at line 66 of file DiscLayer.cpp
References Acts::negativeFaceXY, and Acts::positiveFaceXY.
Referenced by DiscLayer().
static MutableLayerPtr Acts::DiscLayer::create (const std::shared_ptr< const Transform3D > & transform, const std::shared_ptr< const DiscBounds > & dbounds, std::unique_ptr< SurfaceArray > surfaceArray = nullptr, double thickness = 0., std::unique_ptr< ApproachDescriptor > ad = nullptr, LayerType laytyp = Acts::passive) inline static
Factory constructor with DiscSurface components
Parameters
transform is the transform to place the layer in the 3D frame
dbounds are the disc bounds that describe the layer dimensions
surfaceArray is the array of sensitive surfaces
thickness is the layer thickness (along the normal vector)
ad is the approach descriptor that provides the approach surface
laytyp is the layer type
Returns
a sharted pointer to the new layer
Definition at line 46 of file DiscLayer.hpp.
View newest version in sPHENIX GitHub at line 46 of file DiscLayer.hpp
References DiscLayer(), Acts::Layer::surfaceArray(), and Acts::Layer::thickness().
Referenced by Acts::Test::Layers::BOOST_AUTO_TEST_CASE(), Acts::CylinderVolumeHelper::createDiscLayer(), Acts::LayerCreator::discLayer(), Acts::PassiveLayerBuilder::endcapLayers(), and Acts::DD4hepLayerBuilder::endcapLayers().
DiscLayer& Acts::DiscLayer::operator= (const DiscLayer &) delete
Assignment operator for DiscLayers - deleted.
const Acts::DiscSurface & Acts::DiscLayer::surfaceRepresentation () const override virtual
Transforms the layer into a Surface representation for extrapolation
Returns
This method returns a surface reference
Implements Acts::Layer.
Definition at line 58 of file DiscLayer.cpp.
View newest version in sPHENIX GitHub at line 58 of file DiscLayer.cpp
Acts::DiscSurface & Acts::DiscLayer::surfaceRepresentation () override virtual
Implements Acts::Layer.
Definition at line 62 of file DiscLayer.cpp.
View newest version in sPHENIX GitHub at line 62 of file DiscLayer.cpp
The documentation for this class was generated from the following files:
fun4all_acts/blob/master/Core/include/Acts/Geometry/DiscLayer.hpp
fun4all_acts/blob/master/Core/src/Geometry/DiscLayer.cpp