EIC Software: erhic::hadronic::Pythia6EventFactory Class Reference
erhic::hadronic::Pythia6EventFactory Class Reference
#include <eic-smear/blob/master/include/eicsmear/hadronic/Pythia6EventFactory.h>
Public Member Functions
virtual ~Pythia6EventFactory ()
Pythia6EventFactory (EventMCFilterABC *filter)
virtual EventPythiaPP * Create ()
virtual std::string EventName () const
virtual TBranch * Branch (TTree &tree, const std::string &branchName)
virtual void Fill (TBranch &)
Public Member Functions inherited from erhic::VirtualEventFactory
virtual ~VirtualEventFactory ()
virtual VirtualEvent * GetEvBufferPtr ()
virtual void FindFirstEvent ()
Protected Member Functions
virtual EventPythiaPP * BuildEvent ()
Protected Attributes
std::unique_ptr
< erhic::EventMCFilterABC > mFilter
EventPythiaPP * mEvent
Additional Inherited Members
Public Types inherited from erhic::VirtualEventFactory
typedef std::pair< TString,
TObject * > NamedObjects
Public Attributes inherited from erhic::VirtualEventFactory
std::vector< NamedObjects > mObjectsToWriteAtTheEnd
std::map< std::string,
std::string > mAdditionalInformation
Detailed Description
A realisation of erhic::VirtualEventFactory generating objects of type hadronic::EventPythiaPP.
Definition at line 31 of file Pythia6EventFactory.h.
View newest version in sPHENIX GitHub at line 31 of file Pythia6EventFactory.h
Constructor & Destructor Documentation
erhic::hadronic::Pythia6EventFactory::~Pythia6EventFactory () virtual
Destructor.
Definition at line 28 of file Pythia6EventFactory.cxx.
View newest version in sPHENIX GitHub at line 28 of file Pythia6EventFactory.cxx
erhic::hadronic::Pythia6EventFactory::Pythia6EventFactory (erhic::EventMCFilterABC * filter) explicit
Constructor.
Definition at line 31 of file Pythia6EventFactory.cxx.
View newest version in sPHENIX GitHub at line 31 of file Pythia6EventFactory.cxx
Member Function Documentation
TBranch * erhic::hadronic::Pythia6EventFactory::Branch (TTree & tree, const std::string & branchName) virtual
Create a new branch on a tree.
Reimplemented from erhic::VirtualEventFactory.
Definition at line 84 of file Pythia6EventFactory.cxx.
View newest version in sPHENIX GitHub at line 84 of file Pythia6EventFactory.cxx
References EventName().
EventPythiaPP * erhic::hadronic::Pythia6EventFactory::BuildEvent () protected virtual
Construct an event from the current state of TPythia6.
Definition at line 46 of file Pythia6EventFactory.cxx.
View newest version in sPHENIX GitHub at line 46 of file Pythia6EventFactory.cxx
References p, and x2.
Referenced by Create().
EventPythiaPP * erhic::hadronic::Pythia6EventFactory::Create () virtual
Returns a new event instance.
Implements erhic::VirtualEventFactory.
Definition at line 36 of file Pythia6EventFactory.cxx.
View newest version in sPHENIX GitHub at line 36 of file Pythia6EventFactory.cxx
References BuildEvent(), and mFilter.
Referenced by Fill().
std::string erhic::hadronic::Pythia6EventFactory::EventName () const virtual
Returns the name of the event class created by this factory.
Implements erhic::VirtualEventFactory.
Definition at line 80 of file Pythia6EventFactory.cxx.
View newest version in sPHENIX GitHub at line 80 of file Pythia6EventFactory.cxx
Referenced by Branch().
void erhic::hadronic::Pythia6EventFactory::Fill (TBranch & branch) virtual
Fill a tree branch with the current event.
Reimplemented from erhic::VirtualEventFactory.
Definition at line 92 of file Pythia6EventFactory.cxx.
View newest version in sPHENIX GitHub at line 92 of file Pythia6EventFactory.cxx
References Create(), and mEvent.
Member Data Documentation
EventPythiaPP* erhic::hadronic::Pythia6EventFactory::mEvent protected
Definition at line 70 of file Pythia6EventFactory.h.
View newest version in sPHENIX GitHub at line 70 of file Pythia6EventFactory.h
Referenced by Fill().
std::unique_ptr<erhic::EventMCFilterABC> erhic::hadronic::Pythia6EventFactory::mFilter protected
Definition at line 69 of file Pythia6EventFactory.h.
View newest version in sPHENIX GitHub at line 69 of file Pythia6EventFactory.h
Referenced by Create().
The documentation for this class was generated from the following files:
eic-smear/blob/master/include/eicsmear/hadronic/Pythia6EventFactory.h
eic-smear/blob/master/src/hadronic/Pythia6EventFactory.cxx