EIC Software: eic-smear/blob/master/src/erhic/TreeToHepMC.cxx File Reference
TreeToHepMC.cxx File Reference
#include <string>
#include <iostream>
#include <TString.h>
#include <TSystem.h>
#include <TBranch.h>
#include <TLeaf.h>
#include <TDatabasePDG.h>
#include "eicsmear/erhic/Forester.h"
#include "eicsmear/erhic/File.h"
#include "HepMC3/GenEvent.h"
#include "HepMC3/GenVertex.h"
#include "HepMC3/GenParticle.h"
#include "HepMC3/GenCrossSection.h"
#include "HepMC3/Attribute.h"
#include "HepMC3/Version.h"
#include "HepMC3/WriterAscii.h"
#include "HepMC3/WriterAsciiHepMC2.h"
#include "HepMC3/WriterRoot.h"
#include "HepMC3/WriterRootTree.h"
#include <map>
Functions
Long64_t TreeToHepMC (const std::string &inputFileName, const std::string &outputDirName, Long64_t maxEvent, const erhic::HepMC_outtype outtype)
Long64_t TreeToHepMC (const std::string &inputFileName, const std::string &outputDirName, Long64_t maxEvent, const bool createHepMC2)
Detailed Description
Defines the main TreeToHepMC function.
Author
Kolja Kauder
Date
2021-07-07
Copyright
2021 Brookhaven National Lab
Definition in file TreeToHepMC.cxx.
Function Documentation
Long64_t TreeToHepMC (const std::string & inputFileName, const std::string & outputDirName, Long64_t maxEvent, const erhic::HepMC_outtype outtype)
This function converts our tree format to HepMC3 It would be better to skip the ROOT step, but that would require a lot of duplication and/or refactorization
Definition at line 56 of file TreeToHepMC.cxx.
View newest version in sPHENIX GitHub at line 56 of file TreeToHepMC.cxx
References kdfinder::abs(), erhic::EventMC::BeamHadron(), erhic::EventMC::BeamLepton(), c, c1, erhic::EventMC::ExchangeBoson(), eicpy.qaplots::file, erhic::ParticleMCbase::GetChild1Index(), erhic::ParticleMCbase::GetChildNIndex(), erhic::ParticleMCbase::GetE(), erhic::ParticleMCbase::GetIndex(), erhic::ParticleMCbase::GetM(), erhic::ParticleMCbase::GetNChildren(), erhic::EventMC::GetNTracks(), erhic::ParticleMC::GetParent(), erhic::ParticleMCbase::GetParentIndex(), erhic::ParticleMCbase::GetParentIndex1(), erhic::ParticleMCbase::GetPx(), erhic::ParticleMCbase::GetPy(), erhic::ParticleMCbase::GetPz(), erhic::ParticleMCbase::GetStatus(), erhic::EventMC::GetTrack(), erhic::ParticleMCbase::GetVertex(), erhic::HepMC2, erhic::HepMC3, erhic::ParticleMCbase::Id(), max, charm_jet_coverage::mom, p, pdg, erhic::ParticleMCbase::Print(), erhic::Root, erhic::RootTree, Acts::PrimitivesView3DTest::run(), erhic::EventMC::ScatteredLepton(), erhic::ParticleMCbase::SetChild1Index(), erhic::ParticleMCbase::SetChildNIndex(), erhic::ParticleMCbase::SetParentIndex(), erhic::ParticleMCbase::SetParentIndex1(), erhic::ParticleMCbase::SetStatus(), boost::swap(), t, and value.
Referenced by TreeToHepMC().
Long64_t TreeToHepMC (const std::string & inputFileName, const std::string & outputDirName, Long64_t maxEvent, const bool createHepMC2)
Deprecated legacy wrapper
Definition at line 808 of file TreeToHepMC.cxx.
View newest version in sPHENIX GitHub at line 808 of file TreeToHepMC.cxx
References erhic::HepMC2, erhic::HepMC3, and TreeToHepMC().