EIC Software: G4LmonSubsystem Class Reference
G4LmonSubsystem Class Reference
example Fun4All module
#include <Fun4All-lmon/blob/master/source/G4LmonSubsystem.h>
Public Member Functions
G4LmonSubsystem (const std::string &name="LMon")
constructor
virtual ~G4LmonSubsystem ()
destructor
virtual int Init (PHCompositeNode *)
virtual int process_event (PHCompositeNode *)
event processing
PHG4Detector * GetDetector () const
accessors (reimplemented)
PHG4SteppingAction * GetSteppingAction () const
return pointer to this subsystem stepping action
PHG4EventAction * GetEventAction (void) const
return pointer to this subsystem event action
virtual void Print (const std::string &what="ALL") const
Print info (from SubsysReco)
void SetFileName (const std::string &fname)
Public Member Functions inherited from PHG4Subsystem
PHG4Subsystem (const std::string &name="Generic Subsystem")
constructor
~PHG4Subsystem (void) override
destructor
virtual int process_after_geant (PHCompositeNode *)
event processing
virtual PHG4TrackingAction * GetTrackingAction (void) const
return pointer to this subsystem stepping action
virtual PHG4DisplayAction * GetDisplayAction () const
return pointer to this subsystem display setting
virtual PHG4StackingAction * GetStackingAction () const
void OverlapCheck (const bool chk=true)
bool CheckOverlap () const
void SetMotherSubsystem (PHG4Subsystem *subsys)
PHG4Subsystem * GetMotherSubsystem () const
void SetLogicalVolume (G4LogicalVolume *vol)
G4LogicalVolume * GetLogicalVolume () const
virtual bool CanBeMotherSubsystem () const
virtual void AddProcesses (G4ParticleDefinition *)
virtual void DefineMaterials ()
Public Member Functions inherited from SubsysReco
~SubsysReco () override
virtual int End (PHCompositeNode *)
Called at the end of all processing.
virtual int EndRun (const int)
Called at the end of each run.
virtual int InitRun (PHCompositeNode *)
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Private Attributes
G4LmonDetector * m_Detector
detector geometry
PHG4SteppingAction * m_SteppingAction
particle tracking "stepping" action
PHG4EventAction * m_EventAction
RootOut * rootoutput
std::string m_rootname
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = INT_MAX - 10
}
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Detailed Description
example Fun4All module
The detector is constructed and registered via G4LmonDetector
See Also
G4LmonDetector
G4LmonSubsystem
Definition at line 27 of file G4LmonSubsystem.h.
View newest version in sPHENIX GitHub at line 27 of file G4LmonSubsystem.h
Constructor & Destructor Documentation
G4LmonSubsystem::G4LmonSubsystem (const std::string & name = "LMon")
constructor
Definition at line 27 of file G4LmonSubsystem.cc.
View newest version in sPHENIX GitHub at line 27 of file G4LmonSubsystem.cc
References Fun4AllBase::Name().
virtual G4LmonSubsystem::~G4LmonSubsystem () inline virtual
destructor
Definition at line 34 of file G4LmonSubsystem.h.
View newest version in sPHENIX GitHub at line 34 of file G4LmonSubsystem.h
Member Function Documentation
PHG4Detector * G4LmonSubsystem::GetDetector (void) const virtual
accessors (reimplemented)
Reimplemented from PHG4Subsystem.
Definition at line 95 of file G4LmonSubsystem.cc.
View newest version in sPHENIX GitHub at line 95 of file G4LmonSubsystem.cc
References m_Detector.
PHG4EventAction* G4LmonSubsystem::GetEventAction (void) const inline virtual
return pointer to this subsystem event action
Reimplemented from PHG4Subsystem.
Definition at line 55 of file G4LmonSubsystem.h.
View newest version in sPHENIX GitHub at line 55 of file G4LmonSubsystem.h
References m_EventAction.
PHG4SteppingAction* G4LmonSubsystem::GetSteppingAction (void) const inline virtual
return pointer to this subsystem stepping action
Reimplemented from PHG4Subsystem.
Definition at line 53 of file G4LmonSubsystem.h.
View newest version in sPHENIX GitHub at line 53 of file G4LmonSubsystem.h
References m_SteppingAction.
int G4LmonSubsystem::Init (PHCompositeNode * topNode) virtual
creates the m_Detector object and place it on the node tree, under "DETECTORS" node (or whatever) reates the stepping action and place it on the node tree, under "ACTIONS" node creates relevant hit nodes that will be populated by the stepping action and stored in the output DST
Reimplemented from SubsysReco.
Definition at line 37 of file G4LmonSubsystem.cc.
View newest version in sPHENIX GitHub at line 37 of file G4LmonSubsystem.cc
References PHCompositeNode::addNode(), PHG4Subsystem::CheckOverlap(), PHNodeIterator::findFirst(), m_Detector, m_EventAction, m_rootname, m_SteppingAction, Fun4AllBase::Name(), RootOut::Open(), PHG4Detector::OverlapCheck(), rootoutput, RootOut::SetFileName(), and G4LmonDetector::SetRootOutput().
void G4LmonSubsystem::Print (const std::string & what = "ALL") const virtual
Print info (from SubsysReco)
Reimplemented from SubsysReco.
Definition at line 84 of file G4LmonSubsystem.cc.
View newest version in sPHENIX GitHub at line 84 of file G4LmonSubsystem.cc
References m_Detector, and G4LmonDetector::Print().
Referenced by Fun4All_G4_Lmon().
int G4LmonSubsystem::process_event (PHCompositeNode * topNode) virtual
event processing
get all relevant nodes from top nodes (namely hit list) and pass that to the stepping action
Reimplemented from SubsysReco.
Definition at line 73 of file G4LmonSubsystem.cc.
View newest version in sPHENIX GitHub at line 73 of file G4LmonSubsystem.cc
References m_SteppingAction, and PHG4SteppingAction::SetInterfacePointers().
void G4LmonSubsystem::SetFileName (const std::string & fname) inline
Definition at line 58 of file G4LmonSubsystem.h.
View newest version in sPHENIX GitHub at line 58 of file G4LmonSubsystem.h
References m_rootname.
Member Data Documentation
G4LmonDetector* G4LmonSubsystem::m_Detector private
detector geometry
defives from PHG4Detector
Definition at line 63 of file G4LmonSubsystem.h.
View newest version in sPHENIX GitHub at line 63 of file G4LmonSubsystem.h
Referenced by GetDetector(), Init(), and Print().
PHG4EventAction* G4LmonSubsystem::m_EventAction private
Definition at line 68 of file G4LmonSubsystem.h.
View newest version in sPHENIX GitHub at line 68 of file G4LmonSubsystem.h
Referenced by GetEventAction(), and Init().
std::string G4LmonSubsystem::m_rootname private
Definition at line 70 of file G4LmonSubsystem.h.
View newest version in sPHENIX GitHub at line 70 of file G4LmonSubsystem.h
Referenced by Init(), and SetFileName().
PHG4SteppingAction* G4LmonSubsystem::m_SteppingAction private
particle tracking "stepping" action
derives from PHG4SteppingActions
Definition at line 67 of file G4LmonSubsystem.h.
View newest version in sPHENIX GitHub at line 67 of file G4LmonSubsystem.h
Referenced by GetSteppingAction(), Init(), and process_event().
RootOut* G4LmonSubsystem::rootoutput private
Definition at line 69 of file G4LmonSubsystem.h.
View newest version in sPHENIX GitHub at line 69 of file G4LmonSubsystem.h
Referenced by Init().
The documentation for this class was generated from the following files:
Fun4All-lmon/blob/master/source/G4LmonSubsystem.h
Fun4All-lmon/blob/master/source/G4LmonSubsystem.cc