EIC Software: fun4all_macros/blob/master/common/G4_Tracking_Genfit.C File Reference
G4_Tracking_Genfit.C File Reference
#include <GlobalVariables.C>
#include <QA.C>
#include <G4_Intt.C>
#include <G4_Micromegas.C>
#include <G4_Mvtx.C>
#include <G4_TPC.C>
#include <fun4all/Fun4AllServer.h>
#include <g4eval/SvtxEvaluator.h>
#include <trackreco/PHCASeeding.h>
#include <trackreco/PHHybridSeeding.h>
#include <trackreco/PHSimpleKFProp.h>
#include <trackreco/PHGenFitTrackProjection.h>
#include <trackreco/PHGenFitTrkFitter.h>
#include <trackreco/PHGenFitTrkProp.h>
#include <trackreco/PHGhostRejection.h>
#include <trackreco/PHHoughSeeding.h>
#include <trackreco/PHMicromegasTpcTrackMatching.h>
#include <trackreco/PHRaveVertexing.h>
#include <trackreco/PHSiliconTpcTrackMatching.h>
#include <trackreco/PHTpcTrackSeedCircleFit.h>
#include <trackreco/PHTrackCleaner.h>
#include <trackreco/PHTrackSeeding.h>
#include <trackreco/PHTruthSiliconAssociation.h>
#include <trackreco/PHTruthTrackSeeding.h>
#include <trackreco/PHTruthVertexing.h>
#include <trackreco/PHActsVertexPropagator.h>
#include <trackreco/MakeActsGeometry.h>
#include <trackreco/PHActsSiliconSeeding.h>
#include <trackreco/PHActsTrkFitter.h>
#include <trackreco/PHSimpleVertexFinder.h>
#include <tpccalib/TpcSpaceChargeReconstruction.h>
#include <tpccalib/PHTpcResiduals.h>
#include <trackbase/TrkrHitTruthAssoc.h>
#include <phtpctracker/PHTpcTracker.h>
#include <qa_modules/QAG4SimulationTracking.h>
#include <qa_modules/QAG4SimulationUpsilon.h>
#include <qa_modules/QAG4SimulationVertex.h>
Namespaces
namespace Enable
namespace G4TRACKING
Macros
#define MACRO_G4TRACKING_C
Functions
std::string G4TRACKING::vmethod ("avf-smoothing:1")
void TrackingInit ()
void Tracking_Reco ()
void Tracking_Eval (const std::string &outputfile)
void Tracking_QA ()
Variables
bool G4TRACKING::use_genfit = false
bool G4TRACKING::use_PHTpcTracker_seeding = false
bool G4TRACKING::use_hybrid_seeding = false
bool G4TRACKING::use_propagator = true
Macro Definition Documentation
#define MACRO_G4TRACKING_C
Definition at line 2 of file G4_Tracking_Genfit.C.
View newest version in sPHENIX GitHub at line 2 of file G4_Tracking_Genfit.C
Function Documentation
void Tracking_Eval (const std::string & outputfile)
Definition at line 645 of file G4_Tracking_Genfit.C.
View newest version in sPHENIX GitHub at line 645 of file G4_Tracking_Genfit.C
References SvtxEvaluator::do_cluster_eval(), SvtxEvaluator::do_eval_light(), SvtxEvaluator::do_g4hit_eval(), SvtxEvaluator::do_gpoint_eval(), SvtxEvaluator::do_hit_eval(), SvtxEvaluator::do_vtx_eval_light(), G4TRACKING::g4eval_use_initial_vertex, Fun4AllServer::instance(), max, G4TPC::n_gas_layer, G4INTT::n_intt_layer, G4MVTX::n_maps_layer, G4MICROMEGAS::n_micromegas_layer, Fun4AllServer::registerSubsystem(), SvtxEvaluator::scan_for_embedded(), SvtxEvaluator::scan_for_primaries(), SvtxEvaluator::set_use_genfit_vertex(), SvtxEvaluator::set_use_initial_vertex(), Enable::TRACKING_VERBOSITY, G4TRACKING::use_genfit, Enable::VERBOSITY, and Fun4AllBase::Verbosity().
void Tracking_QA ()
Definition at line 680 of file G4_Tracking_Genfit.C.
View newest version in sPHENIX GitHub at line 680 of file G4_Tracking_Genfit.C
References QAG4SimulationUpsilon::addEmbeddingID(), Fun4AllServer::instance(), max, Enable::QA_VERBOSITY, Fun4AllServer::registerSubsystem(), QAG4SimulationVertex::setVertexMapName(), Enable::TRACKING_VERBOSITY, Input::UPSILON, Input::UPSILON_EmbedIds, G4TRACKING::use_genfit, G4TRACKING::use_rave_vertexing, and Fun4AllBase::Verbosity().
void Tracking_Reco ()
If running with distortions, fit only the silicon+MMs first
run tpc residual determination with silicon+MM track fit
Propagate track positions to the vertex position
If running with distortions, fit only the silicon+MMs first
run tpc residual determination with silicon+MM track fit
Definition at line 193 of file G4_Tracking_Genfit.C.
View newest version in sPHENIX GitHub at line 193 of file G4_Tracking_Genfit.C
References PHTruthVertexing::associate_tracks(), PHActsTrkFitter::doTimeAnalysis(), PHTpcTracker::enable_json_export(), PHTpcTracker::enable_vertexing(), PHActsSiliconSeeding::fieldMapName(), PHActsTrkFitter::fitSiliconMMs(), Fun4AllServer::instance(), G4TTL::layer, M_PI, G4MAGNET::magfield, G4MAGNET::magfield_rescale, max, G4TPC::n_gas_layer, G4INTT::n_intt_layer, G4MVTX::n_maps_layer, G4MICROMEGAS::n_micromegas_layer, Fun4AllServer::registerSubsystem(), G4TRACKING::SC_CALIBMODE, G4TRACKING::SC_COLLISIONRATE, G4TRACKING::SC_ROOTOUTPUT_FILENAME, PHMicromegasTpcTrackMatching::set_collision_rate(), PHSiliconTpcTrackMatching::set_collision_rate(), PHSiliconTpcTrackMatching::set_eta_search_window(), PHSiliconTpcTrackMatching::set_field(), PHSiliconTpcTrackMatching::set_field_dir(), PHSimpleKFProp::set_field_dir(), PHHybridSeeding::set_field_dir(), PHTruthTrackSeeding::set_max_layer(), PHSimpleKFProp::set_max_window(), PHTruthTrackSeeding::set_min_layer(), PHMicromegasTpcTrackMatching::set_min_tpc_layer(), TpcSpaceChargeReconstruction::set_outputfile(), PHRaveVertexing::set_over_write_svtxvertexmap(), PHSiliconTpcTrackMatching::set_phi_search_window(), PHMicromegasTpcTrackMatching::set_rphi_search_window_lyr1(), PHMicromegasTpcTrackMatching::set_rphi_search_window_lyr2(), PHMicromegasTpcTrackMatching::set_sc_calib_mode(), PHSiliconTpcTrackMatching::set_sc_calib_mode(), PHTpcTracker::set_seed_finder_optimization_remove_loopers(), PHTpcTracker::set_seed_finder_options(), PHRaveVertexing::set_svtxvertexmaprefit_node_name(), PHMicromegasTpcTrackMatching::set_test_windows_printout(), PHSiliconTpcTrackMatching::set_test_windows_printout(), PHTpcTracker::set_track_follower_optimization_helix(), PHTpcTracker::set_track_follower_optimization_precise_fit(), PHTrackSeeding::set_track_map_name(), PHTruthVertexing::set_track_map_name(), PHMicromegasTpcTrackMatching::set_z_search_window_lyr1(), PHMicromegasTpcTrackMatching::set_z_search_window_lyr2(), PHHybridSeeding::setMinTrackSize(), PHHybridSeeding::setNThreads(), PHTpcResiduals::setOutputfile(), PHHybridSeeding::setSearchAngle(), PHHybridSeeding::setSearchRadius(), tracker(), Enable::TRACKING_VERBOSITY, G4TRACKING::use_full_truth_track_seeding, G4TRACKING::use_genfit, G4TRACKING::use_hybrid_seeding, G4TRACKING::use_PHTpcTracker_seeding, G4TRACKING::use_propagator, G4TRACKING::use_rave_vertexing, G4TRACKING::use_truth_si_matching, G4TRACKING::use_truth_silicon_seeding, G4TRACKING::use_truth_tpc_seeding, G4TRACKING::use_truth_vertexing, PHSimpleKFProp::useConstBField(), PHSimpleKFProp::useFixedClusterError(), Enable::VERBOSITY, Fun4AllBase::Verbosity(), and G4TRACKING::vmethod().
void TrackingInit ()
Built the Acts geometry
Definition at line 115 of file G4_Tracking_Genfit.C.
View newest version in sPHENIX GitHub at line 115 of file G4_Tracking_Genfit.C
References G4TRACKING::add_fake_surfaces, MakeActsGeometry::add_fake_surfaces(), G4TPC::ENABLE_CORRECTIONS, G4TPC::ENABLE_STATIC_DISTORTIONS, G4TPC::ENABLE_TIME_ORDERED_DISTORTIONS, Fun4AllServer::instance(), G4MAGNET::magfield, G4MAGNET::magfield_rescale, max, Enable::MICROMEGAS, G4MICROMEGAS::n_micromegas_layer, Fun4AllServer::registerSubsystem(), G4TRACKING::SC_CALIBMODE, MakeActsGeometry::setMagField(), MakeActsGeometry::setMagFieldRescale(), Enable::TRACKING_VERBOSITY, G4TRACKING::use_genfit, G4TRACKING::use_hybrid_seeding, G4TRACKING::use_PHTpcTracker_seeding, Enable::VERBOSITY, and Fun4AllBase::Verbosity().