EIC Software: FW::CsvPlanarClusterReader Exception Reference
FW::CsvPlanarClusterReader Exception Reference final
#include <fun4all_acts/blob/master/Examples/Io/Csv/include/ACTFW/Io/Csv/CsvPlanarClusterReader.hpp>
Classes
struct Config
Public Member Functions
CsvPlanarClusterReader (const Config &cfg, Acts::Logging::Level lvl)
std::string name () const finaloverride
The reader name.
std::pair< size_t, size_t > availableEvents () const finaloverride
Return the available events range.
ProcessCode read (const FW::AlgorithmContext &ctx) finaloverride
Read out data from the input stream.
Public Member Functions inherited from FW::IReader
virtual ~IReader ()=default
Private Member Functions
const Acts::Logger & logger () const
Private Attributes
Config m_cfg
std::unordered_map
< Acts::GeometryID, const
Acts::Surface * > m_surfaces
std::pair< size_t, size_t > m_eventsRange
std::unique_ptr< const
Acts::Logger > m_logger
Detailed Description
Read in a planar cluster collection in comma-separated-value format.
This reads three files per event file in the configured input directory. By default it reads file in the current working directory. Files are assumed to be named using the following schema
event000000001-cells.csv
event000000001-hits.csv
event000000001-truth.csv
event000000002-cells.csv
event000000002-hits.csv
event000000002-truth.csv
and each line in the file corresponds to one hit/cluster.
Definition at line 39 of file CsvPlanarClusterReader.hpp.
View newest version in sPHENIX GitHub at line 39 of file CsvPlanarClusterReader.hpp
Constructor & Destructor Documentation
FW::CsvPlanarClusterReader::CsvPlanarClusterReader (const Config & cfg, Acts::Logging::Level lvl)
Construct the cluster reader.
cfg is the configuration object lvl is the logging level
Definition at line 26 of file CsvPlanarClusterReader.cpp.
View newest version in sPHENIX GitHub at line 26 of file CsvPlanarClusterReader.cpp
References Acts::GeometryObject::geoID(), m_cfg, m_surfaces, FW::CsvPlanarClusterReader::Config::outputClusters, FW::CsvPlanarClusterReader::Config::outputHitIds, FW::CsvPlanarClusterReader::Config::outputHitParticlesMap, FW::CsvPlanarClusterReader::Config::outputSimulatedHits, and FW::CsvPlanarClusterReader::Config::trackingGeometry.
Member Function Documentation
std::pair< size_t, size_t > FW::CsvPlanarClusterReader::availableEvents () const final override virtual
Return the available events range.
Implements FW::IReader.
Definition at line 58 of file CsvPlanarClusterReader.cpp.
View newest version in sPHENIX GitHub at line 58 of file CsvPlanarClusterReader.cpp
const Acts::Logger& FW::CsvPlanarClusterReader::logger () const inline private
Definition at line 76 of file CsvPlanarClusterReader.hpp.
View newest version in sPHENIX GitHub at line 76 of file CsvPlanarClusterReader.hpp
References m_logger.
std::string FW::CsvPlanarClusterReader::name () const final override virtual
The reader name.
Implements FW::IReader.
FW::ProcessCode FW::CsvPlanarClusterReader::read (const FW::AlgorithmContext & ctx) final override virtual
Read out data from the input stream.
Implements FW::IReader.
Definition at line 154 of file CsvPlanarClusterReader.cpp.
View newest version in sPHENIX GitHub at line 154 of file CsvPlanarClusterReader.cpp
References ACTS_FATAL, FW::WhiteBoard::add(), c, FW::AlgorithmContext::eventNumber, FW::AlgorithmContext::eventStore, FW::AlgorithmContext::geoContext, Acts::Surface::getSharedPtr(), Acts::UnitConstants::GeV, Acts::Surface::globalToLocal(), it, FW::makeRange(), Acts::UnitConstants::mm, charm_jet_coverage::mom, Acts::UnitConstants::ns, Acts::Test::pos, SUCCESS, Acts::VectorHelpers::time(), and Acts::GeometryID::value().
Member Data Documentation
Config FW::CsvPlanarClusterReader::m_cfg private
Definition at line 71 of file CsvPlanarClusterReader.hpp.
View newest version in sPHENIX GitHub at line 71 of file CsvPlanarClusterReader.hpp
Referenced by CsvPlanarClusterReader().
std::pair<size_t, size_t> FW::CsvPlanarClusterReader::m_eventsRange private
Definition at line 73 of file CsvPlanarClusterReader.hpp.
View newest version in sPHENIX GitHub at line 73 of file CsvPlanarClusterReader.hpp
std::unique_ptr<const Acts::Logger> FW::CsvPlanarClusterReader::m_logger private
Definition at line 74 of file CsvPlanarClusterReader.hpp.
View newest version in sPHENIX GitHub at line 74 of file CsvPlanarClusterReader.hpp
Referenced by logger().
std::unordered_map<Acts::GeometryID, const Acts::Surface*> FW::CsvPlanarClusterReader::m_surfaces private
Definition at line 72 of file CsvPlanarClusterReader.hpp.
View newest version in sPHENIX GitHub at line 72 of file CsvPlanarClusterReader.hpp
Referenced by CsvPlanarClusterReader().
The documentation for this exception was generated from the following files:
fun4all_acts/blob/master/Examples/Io/Csv/include/ACTFW/Io/Csv/CsvPlanarClusterReader.hpp
fun4all_acts/blob/master/Examples/Io/Csv/src/CsvPlanarClusterReader.cpp