EIC Software: EicPlanarRecoHit Class Reference
EicPlanarRecoHit Class Reference
#include <EicRoot/blob/master/eic/tracking/EicTrackingRecoHit.h>
Public Member Functions
EicPlanarRecoHit ()
EicPlanarRecoHit (EicTrackingDigiHit *hit, void *ptr=0)
~EicPlanarRecoHit ()
Public Member Functions inherited from EicTrackingRecoHit
EicTrackingRecoHit ()
~EicTrackingRecoHit ()
Public Member Functions inherited from GFRecoHitIfc< GFPlanarHitPolicy >
GFRecoHitIfc (int dim)
Constructor specifying dimension of hit coordinate vector.
virtual ~GFRecoHitIfc ()
virtual const GFDetPlane & getDetPlane (GFAbsTrackRep *rep)
Returns the detector plane object for this hit and a given track representation.
virtual void getMeasurement (const GFAbsTrackRep *rep, const GFDetPlane &pl, const TMatrixT< double > &statePred, const TMatrixT< double > &covPred, TMatrixT< double > &m, TMatrixT< double > &V)
Get measurement m,V and HMatrix.
const std::string & getPolicyName ()
ClassDef (GFRecoHitIfc, 1)
Public Member Functions inherited from GFAbsRecoHit
virtual ~GFAbsRecoHit ()
GFAbsRecoHit (int NparHit)
Constructor specifying dimension of coordinate vector.
GFAbsRecoHit ()
Default constructor needed for compatibility with ROOT.
TMatrixT< double > getRawHitCov () const
Get raw hit covariances.
TMatrixT< double > getRawHitCoord () const
Get raw hit coordinates.
double getRho ()
void setRho (double rho)
virtual void Print (const Option_t *option="") const
Print raw hit coordinates.
int getNparHit ()
Private Member Functions
GFAbsRecoHit * clone ()
Get clone of this object.
unsigned GetMdim () const
TMatrixT< double > getHMatrix (const GFAbsTrackRep *stateVector)
Get transformation matrix. Transformation between hit coordinates and track representation coordinates.
ClassDef (EicPlanarRecoHit, 3)
Private Attributes
UChar_t mDim
Additional Inherited Members
Protected Member Functions inherited from EicTrackingRecoHit
const
LogicalVolumeLookupTableEntry * GetLookupTableNode (EicTrackingDigiHit *hit, void *ptr)
TMatrixT< double > getHMatrix (const GFAbsTrackRep *stateVector)
Protected Attributes inherited from GFRecoHitIfc< GFPlanarHitPolicy >
GFPlanarHitPolicy fPolicy
Detailed Description
Definition at line 33 of file EicTrackingRecoHit.h.
View newest version in sPHENIX GitHub at line 33 of file EicTrackingRecoHit.h
Constructor & Destructor Documentation
EicPlanarRecoHit::EicPlanarRecoHit () inline
Definition at line 35 of file EicTrackingRecoHit.h.
View newest version in sPHENIX GitHub at line 35 of file EicTrackingRecoHit.h
Referenced by clone().
EicPlanarRecoHit::EicPlanarRecoHit (EicTrackingDigiHit * hit, void * ptr = 0)
Definition at line 63 of file EicTrackingRecoHit.cxx.
View newest version in sPHENIX GitHub at line 63 of file EicTrackingRecoHit.cxx
References GFAbsRecoHit::fHitCoord, GFAbsRecoHit::fHitCov, GFRecoHitIfc< GFPlanarHitPolicy >::fPolicy, EicTrackingDigiHit::GetCovariance(), EicTrackingDigiHit::GetLocalCoordinates(), EicTrackingRecoHit::GetLookupTableNode(), EicTrackingDigiHit::GetMdim(), LocalToMaster(), LocalToMasterVect(), LogicalVolumeLookupTableEntry::mGeoMtx, EicTrackingDigiHit::mXYmode, and GFPlanarHitPolicy::setDetPlane().
EicPlanarRecoHit::~EicPlanarRecoHit () inline
Definition at line 37 of file EicTrackingRecoHit.h.
View newest version in sPHENIX GitHub at line 37 of file EicTrackingRecoHit.h
Member Function Documentation
EicPlanarRecoHit::ClassDef (EicPlanarRecoHit , 3) private
GFAbsRecoHit* EicPlanarRecoHit::clone () inline private virtual
Get clone of this object.
Virtual abstract method. Has to be implemented by inherting classes. Creates a deep copy of this object. Ownership is trandsferred to the caller!
Implements GFAbsRecoHit.
Definition at line 40 of file EicTrackingRecoHit.h.
View newest version in sPHENIX GitHub at line 40 of file EicTrackingRecoHit.h
References EicPlanarRecoHit().
TMatrixT<double> EicPlanarRecoHit::getHMatrix (const GFAbsTrackRep * stateVector) inline private virtual
Get transformation matrix. Transformation between hit coordinates and track representation coordinates.
This is a virtual abstract method which has to be implemented in the child classes.
In general there is a linear transformation between the coordinate system of the hit (which is defined by the detector plane) and the coordinates of the track representation in that plane. In the most simple case the track representation has 5 parameters (space + momentum) while a hit usually has less (one to three space coordinates).
The transformation matrix is then simply projecting out the space-components of the track representation.
Its dimensions are NxM. Where N is the number of dimensions of the hit in the detector plane (usually 2 or 1) and M is the dimension of the track representation.
In this method a hit has to define with which track representations it can work together. It should be the only point where this explicit coordination is necessary.
For example code see implementing classes below:
Implements GFAbsRecoHit.
Definition at line 47 of file EicTrackingRecoHit.h.
View newest version in sPHENIX GitHub at line 47 of file EicTrackingRecoHit.h
References EicTrackingRecoHit::getHMatrix().
unsigned EicPlanarRecoHit::GetMdim () const inline private virtual
Implements EicTrackingRecoHit.
Definition at line 42 of file EicTrackingRecoHit.h.
View newest version in sPHENIX GitHub at line 42 of file EicTrackingRecoHit.h
Member Data Documentation
UChar_t EicPlanarRecoHit::mDim private
Definition at line 42 of file EicTrackingRecoHit.h.
View newest version in sPHENIX GitHub at line 42 of file EicTrackingRecoHit.h
The documentation for this class was generated from the following files:
EicRoot/blob/master/eic/tracking/EicTrackingRecoHit.h
EicRoot/blob/master/eic/tracking/EicTrackingRecoHit.cxx