EIC Software: FairDbConfigStream Class Reference
FairDbConfigStream Class Reference
#include <EicRoot/blob/master/dbase/dbInterface/FairDbConfigStream.h>
Public Member Functions
FairDbConfigStream ()
FairDbConfigStream (const std::string &SoftwName, const std::string &ConfigName="default", ValContext vc=FairDbConfigStream::fgDefaultContext, FairDb::Task task=0, const std::string &tableName="SOFTWARE_CONFIGURATION")
virtual ~FairDbConfigStream ()
const FairDbConfigStream & operator>> (FairRegistry *reg)
const FairDbConfigSet * GetConfigSet () const
FairDbConfigStream & operator<< (const FairRegistry *reg)
Bool_t IsEmpty ()
FairDbValidityRec & GetValidityRec ()
Bool_t Write (UInt_t dbNo=0, const std::string &logComment="", Bool_t localTest=false)
Static Public Attributes
static ValContext fgDefaultContext
Private Member Functions
FairDbConfigStream (const FairDbConfigStream &)
FairDbConfigStream operator= (const FairDbConfigStream &)
Private Attributes
const FairDbConfigSet * fCFSet
FairDbResultPtr< FairDbConfigSet > fCFSetTable
Pointer to ConfigSet table.
FairDbConfigSet fCFSetModified
Local FairDbConfigSet (empty until/unless filled using operator <<).
FairDbValidityRec fVRec
Associated validity rec (used when writing back to the database).
std::string fConfigName
Name of the configuration set.
std::string fSoftwName
Name of the software system to be configured.
Detailed Description
Definition at line 20 of file FairDbConfigStream.h.
View newest version in sPHENIX GitHub at line 20 of file FairDbConfigStream.h
Constructor & Destructor Documentation
FairDbConfigStream::FairDbConfigStream ()
FairDbConfigStream::FairDbConfigStream (const std::string & SoftwName, const std::string & ConfigName = "default", ValContext vc = FairDbConfigStream::fgDefaultContext, FairDb::Task task = 0, const std::string & tableName = "SOFTWARE_CONFIGURATION")
Definition at line 33 of file FairDbConfigStream.cxx.
View newest version in sPHENIX GitHub at line 33 of file FairDbConfigStream.cxx
References fCFSet, fCFSetTable, fConfigName, fSoftwName, fVRec, FairDbConfigSet::GetAggregateNo(), FairDbResultPtr< T >::GetNumRows(), FairDbConfigSet::GetParamValue(), FairDbResultPtr< T >::GetRow(), FairDbResultPtr< T >::GetValidityRec(), FairDbValidityRec::SetDbNo(), FairDbValidityRec::SetTableProxy(), FairDbValidityRec::SetValRange(), and start().
FairDbConfigStream::~FairDbConfigStream () virtual
Definition at line 82 of file FairDbConfigStream.cxx.
View newest version in sPHENIX GitHub at line 82 of file FairDbConfigStream.cxx
FairDbConfigStream::FairDbConfigStream (const FairDbConfigStream &) private
Member Function Documentation
const FairDbConfigSet* FairDbConfigStream::GetConfigSet () const inline
Definition at line 39 of file FairDbConfigStream.h.
View newest version in sPHENIX GitHub at line 39 of file FairDbConfigStream.h
References fCFSet.
Referenced by operator<<().
FairDbValidityRec& FairDbConfigStream::GetValidityRec () inline
Definition at line 45 of file FairDbConfigStream.h.
View newest version in sPHENIX GitHub at line 45 of file FairDbConfigStream.h
References fVRec.
Bool_t FairDbConfigStream::IsEmpty () inline
Definition at line 44 of file FairDbConfigStream.h.
View newest version in sPHENIX GitHub at line 44 of file FairDbConfigStream.h
References fCFSet.
FairDbConfigStream & FairDbConfigStream::operator<< (const FairRegistry * reg)
Definition at line 135 of file FairDbConfigStream.cxx.
View newest version in sPHENIX GitHub at line 135 of file FairDbConfigStream.cxx
References FairDbConfigSet::Clear(), fCFSet, fCFSetModified, fConfigName, fSoftwName, fVRec, FairDbValidityRec::GetAggregateNo(), FairDb::kString, FairRegistry::PrintStream(), FairDbConfigSet::PushBack(), and FairDbConfigSet::SetAggregateNo().
FairDbConfigStream FairDbConfigStream::operator= (const FairDbConfigStream &) private
const FairDbConfigStream & FairDbConfigStream::operator>> (FairRegistry * reg)
Definition at line 101 of file FairDbConfigStream.cxx.
View newest version in sPHENIX GitHub at line 101 of file FairDbConfigStream.cxx
References FairRegistry::Clear(), fCFSet, FairDbConfigSet::GetNumParams(), FairDbConfigSet::GetParamName(), FairDbConfigSet::GetParamValue(), FairRegistry::KeysLocked(), FairRegistry::LockKeys(), FairRegistry::LockValues(), FairRegistry::ReadStream(), FairRegistry::UnLockKeys(), FairRegistry::UnLockValues(), and FairRegistry::ValuesLocked().
Bool_t FairDbConfigStream::Write (UInt_t dbNo = 0, const std::string & logComment = "", Bool_t localTest = false)
Definition at line 159 of file FairDbConfigStream.cxx.
View newest version in sPHENIX GitHub at line 159 of file FairDbConfigStream.cxx
References FairDbMultConnector::AllocateSeqNo(), FairDbWriter< T >::Close(), fCFSet, fCFSetModified, fConfigName, fSoftwName, fVRec, FairDbValidityRec::GetAggregateNo(), FairDbTableProxyRegistry::GetMultConnector(), FairDbTableProxy::GetTableName(), FairDbValidityRec::GetTableProxy(), FairDbTableProxyRegistry::Instance(), FairDb::kMAXLOCALSEQNO, FairDbConfigSet::SetAggregateNo(), FairDbValidityRec::SetAggregateNo(), FairDbWriter< T >::SetOverlayCreationDate(), and FairDbWriter< T >::SetRequireGlobalSeqno().
Member Data Documentation
const FairDbConfigSet* FairDbConfigStream::fCFSet private
Pointer to the associated configuration set. May point either to a row of fCFSetTable (or 0) or, after operator <<, to fCFSetModified
Definition at line 60 of file FairDbConfigStream.h.
View newest version in sPHENIX GitHub at line 60 of file FairDbConfigStream.h
Referenced by FairDbConfigStream(), GetConfigSet(), IsEmpty(), operator<<(), operator>>(), and Write().
FairDbConfigSet FairDbConfigStream::fCFSetModified private
Local FairDbConfigSet (empty until/unless filled using operator <<).
Definition at line 67 of file FairDbConfigStream.h.
View newest version in sPHENIX GitHub at line 67 of file FairDbConfigStream.h
Referenced by operator<<(), and Write().
FairDbResultPtr<FairDbConfigSet> FairDbConfigStream::fCFSetTable private
Pointer to ConfigSet table.
Definition at line 64 of file FairDbConfigStream.h.
View newest version in sPHENIX GitHub at line 64 of file FairDbConfigStream.h
Referenced by FairDbConfigStream().
std::string FairDbConfigStream::fConfigName private
Name of the configuration set.
Definition at line 73 of file FairDbConfigStream.h.
View newest version in sPHENIX GitHub at line 73 of file FairDbConfigStream.h
Referenced by FairDbConfigStream(), operator<<(), and Write().
ValContext FairDbConfigStream::fgDefaultContext static
Definition at line 26 of file FairDbConfigStream.h.
View newest version in sPHENIX GitHub at line 26 of file FairDbConfigStream.h
std::string FairDbConfigStream::fSoftwName private
Name of the software system to be configured.
Definition at line 76 of file FairDbConfigStream.h.
View newest version in sPHENIX GitHub at line 76 of file FairDbConfigStream.h
Referenced by FairDbConfigStream(), operator<<(), and Write().
FairDbValidityRec FairDbConfigStream::fVRec private
Associated validity rec (used when writing back to the database).
Definition at line 70 of file FairDbConfigStream.h.
View newest version in sPHENIX GitHub at line 70 of file FairDbConfigStream.h
Referenced by FairDbConfigStream(), GetValidityRec(), operator<<(), and Write().
The documentation for this class was generated from the following files:
EicRoot/blob/master/dbase/dbInterface/FairDbConfigStream.h
EicRoot/blob/master/dbase/dbInterface/FairDbConfigStream.cxx