EIC Software: GFPlanarHitPolicy Class Reference
GFPlanarHitPolicy Class Reference
Genfit
Policy class implementing a planar hit geometry.
#include <EicRoot/blob/master/genfit/GFPlanarHitPolicy.h>
Public Member Functions
GFPlanarHitPolicy ()
const GFDetPlane & detPlane (GFAbsRecoHit *, const GFAbsTrackRep *)
Returns the physical detector plane.
void setDetPlane (const GFDetPlane &p)
Set physical detector plane. Needs to be called before hit can be used.
TMatrixT< double > hitCoord (GFAbsRecoHit *, const GFDetPlane &)
Hit coordinates in detector plane.
TMatrixT< double > hitCov (GFAbsRecoHit *, const GFDetPlane &)
Hit covariances in detector plane.
virtual ~GFPlanarHitPolicy ()
const std::string & getName ()
Protected Attributes
GFDetPlane fPhysicalDetPlane
Physical detector plane. Given by detector hardware.
Static Private Attributes
static const std::string fPolicyName = "GFPlanarHitPolicy"
Detailed Description
Policy class implementing a planar hit geometry.
Author
Christian Höppner (Technische Universität München, original author)
Sebastian Neubert (Technische Universität München, original author)
RecoHits for planar detectors should inherit from RecoHitIfc<GFPlanarHitPolicy>.
The main feature of this type of hit is, that the detector plane is completely defined by the detector hardware. Derived RecoHits need only to supply the physical detector plane from their geometry database.
Definition at line 50 of file GFPlanarHitPolicy.h.
View newest version in sPHENIX GitHub at line 50 of file GFPlanarHitPolicy.h
Constructor & Destructor Documentation
GFPlanarHitPolicy::GFPlanarHitPolicy () inline
Definition at line 54 of file GFPlanarHitPolicy.h.
View newest version in sPHENIX GitHub at line 54 of file GFPlanarHitPolicy.h
virtual GFPlanarHitPolicy::~GFPlanarHitPolicy () inline virtual
Definition at line 84 of file GFPlanarHitPolicy.h.
View newest version in sPHENIX GitHub at line 84 of file GFPlanarHitPolicy.h
Member Function Documentation
const GFDetPlane & GFPlanarHitPolicy::detPlane (GFAbsRecoHit * , const GFAbsTrackRep *)
Returns the physical detector plane.
Definition at line 38 of file GFPlanarHitPolicy.cxx.
View newest version in sPHENIX GitHub at line 38 of file GFPlanarHitPolicy.cxx
References fPhysicalDetPlane.
const std::string& GFPlanarHitPolicy::getName () inline
Definition at line 86 of file GFPlanarHitPolicy.h.
View newest version in sPHENIX GitHub at line 86 of file GFPlanarHitPolicy.h
References fPolicyName.
TMatrixT< double > GFPlanarHitPolicy::hitCoord (GFAbsRecoHit * hit, const GFDetPlane &)
Hit coordinates in detector plane.
Definition at line 26 of file GFPlanarHitPolicy.cxx.
View newest version in sPHENIX GitHub at line 26 of file GFPlanarHitPolicy.cxx
References GFAbsRecoHit::getRawHitCoord().
TMatrixT< double > GFPlanarHitPolicy::hitCov (GFAbsRecoHit * hit, const GFDetPlane &)
Hit covariances in detector plane.
Definition at line 32 of file GFPlanarHitPolicy.cxx.
View newest version in sPHENIX GitHub at line 32 of file GFPlanarHitPolicy.cxx
References GFAbsRecoHit::getRawHitCov().
void GFPlanarHitPolicy::setDetPlane (const GFDetPlane & p) inline
Set physical detector plane. Needs to be called before hit can be used.
For the planar detector the detector plane is fixed by the geometry of the detector hardware. This method should be called in the constructor of any derived RecoHit in order to setup the geometry of this hit.
Definition at line 73 of file GFPlanarHitPolicy.h.
View newest version in sPHENIX GitHub at line 73 of file GFPlanarHitPolicy.h
References fPhysicalDetPlane, and p.
Referenced by EicPlanarRecoHit::EicPlanarRecoHit().
Member Data Documentation
GFDetPlane GFPlanarHitPolicy::fPhysicalDetPlane protected
Physical detector plane. Given by detector hardware.
Definition at line 97 of file GFPlanarHitPolicy.h.
View newest version in sPHENIX GitHub at line 97 of file GFPlanarHitPolicy.h
Referenced by detPlane(), and setDetPlane().
const std::string GFPlanarHitPolicy::fPolicyName = "GFPlanarHitPolicy" static private
Definition at line 89 of file GFPlanarHitPolicy.h.
View newest version in sPHENIX GitHub at line 89 of file GFPlanarHitPolicy.h
Referenced by getName().
The documentation for this class was generated from the following files:
EicRoot/blob/master/genfit/GFPlanarHitPolicy.h
EicRoot/blob/master/genfit/GFPlanarHitPolicy.cxx