EIC Software: FairGenericParTSQLIo Class Reference
FairGenericParTSQLIo Class Reference
#include <EicRoot/blob/master/parbase/dbIO/FairGenericParTSQLIo.h>
Public Member Functions
FairGenericParTSQLIo ()
Constructor.
FairGenericParTSQLIo (FairDbMultConnector const &cons, int const dbNum=-1)
virtual ~FairGenericParTSQLIo ()
Destructor.
Bool_t init (FairParSet *pPar)
Bool_t read (FairParGenericSet *pPar)
Read and write functions.
Int_t write (FairParSet *pars)
Int_t writeSet (FairParGenericSet *pars)
Public Member Functions inherited from FairDetParTSQLIo
FairDetParTSQLIo ()
Constructors.
FairDetParTSQLIo (FairDbMultConnector const &cons, int const dbNum=-1)
virtual ~FairDetParTSQLIo ()
Destructor.
Bool_t read (FairParSet *pars)
Int_t getRunStart (FairParSet *pPar=0)
virtual void commit ()
virtual void rollback ()
void print ()
_______________ Inline Implementations ________________
Public Member Functions inherited from FairDetParIo
FairDetParIo ()
virtual ~FairDetParIo ()
void setInputNumber (Int_t n)
Int_t getInputNumber ()
Private Member Functions
FairGenericParTSQLIo (FairGenericParTSQLIo const &ot)
FairGenericParTSQLIo & operator= (FairGenericParTSQLIo const &ot)
Additional Inherited Members
Protected Member Functions inherited from FairDetParTSQLIo
void setChanged (FairParSet *pars)
Protected Attributes inherited from FairDetParTSQLIo
int fDefaultDb
FairDbMultConnector * fConnections
TList * fcontainerList
FairDbConnection.
FairRtdbRun * factContVers
List of parameter containers.
int actRunId
The actual list of container versions.
Detailed Description
Definition at line 21 of file FairGenericParTSQLIo.h.
View newest version in sPHENIX GitHub at line 21 of file FairGenericParTSQLIo.h
Constructor & Destructor Documentation
FairGenericParTSQLIo::FairGenericParTSQLIo ()
Constructor.
FairGenericParTSQLIo::FairGenericParTSQLIo (FairDbMultConnector const & cons, int const dbNum = -1)
Parameters
cons FairDbMultConnector which holds a number of initialized db connections.
dbNum The db which is selected to act as the master for the current operations. Note: A new FairDbMultConnector object is created (to keep the ownership).
Definition at line 32 of file FairGenericParTSQLIo.cxx.
View newest version in sPHENIX GitHub at line 32 of file FairGenericParTSQLIo.cxx
FairGenericParTSQLIo::~FairGenericParTSQLIo () virtual
Destructor.
Definition at line 40 of file FairGenericParTSQLIo.cxx.
View newest version in sPHENIX GitHub at line 40 of file FairGenericParTSQLIo.cxx
FairGenericParTSQLIo::FairGenericParTSQLIo (FairGenericParTSQLIo const & ot) private
Member Function Documentation
Bool_t FairGenericParTSQLIo::init (FairParSet * pPar) virtual
Reimplemented from FairDetParIo.
Definition at line 57 of file FairGenericParTSQLIo.cxx.
View newest version in sPHENIX GitHub at line 57 of file FairGenericParTSQLIo.cxx
References read().
FairGenericParTSQLIo& FairGenericParTSQLIo::operator= (FairGenericParTSQLIo const & ot) private
Bool_t FairGenericParTSQLIo::read (FairParGenericSet * pPar)
Read and write functions.
Definition at line 45 of file FairGenericParTSQLIo.cxx.
View newest version in sPHENIX GitHub at line 45 of file FairGenericParTSQLIo.cxx
Referenced by init().
Int_t FairGenericParTSQLIo::write (FairParSet * pars) virtual
Reimplemented from FairDetParTSQLIo.
Definition at line 70 of file FairGenericParTSQLIo.cxx.
View newest version in sPHENIX GitHub at line 70 of file FairGenericParTSQLIo.cxx
References writeSet().
Int_t FairGenericParTSQLIo::writeSet (FairParGenericSet * pars)
Definition at line 82 of file FairGenericParTSQLIo.cxx.
View newest version in sPHENIX GitHub at line 82 of file FairGenericParTSQLIo.cxx
References FairParamObj::getBytesPerValue(), FairParamObj::getClassVersion(), FairParamObj::getLength(), FairParamList::getList(), FairParamObj::getNumParams(), FairParSet::getParamContext(), FairParamObj::getParamType(), FairParamObj::getParamValue(), FairParamObj::isBasicType(), FairParamObj::print(), and FairParGenericSet::putParams().
Referenced by write().
The documentation for this class was generated from the following files:
EicRoot/blob/master/parbase/dbIO/FairGenericParTSQLIo.h
EicRoot/blob/master/parbase/dbIO/FairGenericParTSQLIo.cxx