EIC Software: GFWireHitPolicy Class Reference
GFWireHitPolicy Class Reference
Genfit
policy class for hits in wire detectors (STT and DCH) which do not measure the coordinate along the wire
#include <EicRoot/blob/master/genfit/GFWireHitPolicy.h>
Public Member Functions
GFWireHitPolicy ()
const GFDetPlane & detPlane (GFAbsRecoHit *, GFAbsTrackRep *)
Get detector plane Calls GFAbsTrackRep::extrapolateToLine for POCA.
TMatrixT< double > hitCoord (GFAbsRecoHit *, const GFDetPlane &)
Hit coordinates in detector plane.
TMatrixT< double > hitCov (GFAbsRecoHit *, const GFDetPlane &)
Hit covariances in detector plane.
void checkPlane (GFAbsRecoHit *, const GFDetPlane &)
Check if the detector plane is valid.
virtual ~GFWireHitPolicy ()
double getMaxDistance ()
void setMaxDistance (double d)
const std::string & getName ()
ClassDef (GFWireHitPolicy, 1)
Private Attributes
GFDetPlane fDetPlane
double fMaxdistance
Static Private Attributes
static const std::string fPolicyName = "GFWireHitPolicy"
Detailed Description
policy class for hits in wire detectors (STT and DCH) which do not measure the coordinate along the wire
Author
Christian Höppner (Technische Universität München, original author)
Lia Lavezzi (INFN Pavia, original author)
Sebastian Neubert (Technische Universität München, original author)
This policy is not valid for any kind of plane orientation choice: to use it you MUST choose a plane described by u and v axes with v coincident with the wire (and u orthogonal to it, obviously). The hit will be described by 7 coordinates: w_x1, w_y1, w_z1, w_x2, w_y2, w_z2, rdrift where w_ji (with j = x, y, z and i = 1, 2) are the wire extremities coordinates; rdrift = distance from the wire (u coordinate in the plane)
Definition at line 52 of file GFWireHitPolicy.h.
View newest version in sPHENIX GitHub at line 52 of file GFWireHitPolicy.h
Constructor & Destructor Documentation
GFWireHitPolicy::GFWireHitPolicy ()
Definition at line 36 of file GFWireHitPolicy.cxx.
View newest version in sPHENIX GitHub at line 36 of file GFWireHitPolicy.cxx
virtual GFWireHitPolicy::~GFWireHitPolicy () inline virtual
Definition at line 76 of file GFWireHitPolicy.h.
View newest version in sPHENIX GitHub at line 76 of file GFWireHitPolicy.h
Member Function Documentation
void GFWireHitPolicy::checkPlane (GFAbsRecoHit * hit, const GFDetPlane & plane)
Check if the detector plane is valid.
Definition at line 67 of file GFWireHitPolicy.cxx.
View newest version in sPHENIX GitHub at line 67 of file GFWireHitPolicy.cxx
References Acts::UnitConstants::e, GFAbsRecoHit::getRawHitCoord(), and GFDetPlane::getV().
Referenced by hitCoord(), and hitCov().
GFWireHitPolicy::ClassDef (GFWireHitPolicy , 1)
const GFDetPlane & GFWireHitPolicy::detPlane (GFAbsRecoHit * hit, GFAbsTrackRep * rep)
Get detector plane Calls GFAbsTrackRep::extrapolateToLine for POCA.
Definition at line 91 of file GFWireHitPolicy.cxx.
View newest version in sPHENIX GitHub at line 91 of file GFWireHitPolicy.cxx
References GFDetPlane::dist(), Acts::UnitConstants::e, GFAbsTrackRep::extrapolateToLine(), fDetPlane, fMaxdistance, GFAbsRecoHit::getRawHitCoord(), and x.
double GFWireHitPolicy::getMaxDistance () inline
Definition at line 78 of file GFWireHitPolicy.h.
View newest version in sPHENIX GitHub at line 78 of file GFWireHitPolicy.h
References fMaxdistance.
const std::string& GFWireHitPolicy::getName () inline
Definition at line 81 of file GFWireHitPolicy.h.
View newest version in sPHENIX GitHub at line 81 of file GFWireHitPolicy.h
References fPolicyName.
TMatrixT< double > GFWireHitPolicy::hitCoord (GFAbsRecoHit * hit, const GFDetPlane & plane)
Hit coordinates in detector plane.
Definition at line 39 of file GFWireHitPolicy.cxx.
View newest version in sPHENIX GitHub at line 39 of file GFWireHitPolicy.cxx
References checkPlane(), and GFAbsRecoHit::getRawHitCoord().
TMatrixT< double > GFWireHitPolicy::hitCov (GFAbsRecoHit * hit, const GFDetPlane & plane)
Hit covariances in detector plane.
Definition at line 53 of file GFWireHitPolicy.cxx.
View newest version in sPHENIX GitHub at line 53 of file GFWireHitPolicy.cxx
References checkPlane(), and GFAbsRecoHit::getRawHitCov().
void GFWireHitPolicy::setMaxDistance (double d) inline
Definition at line 79 of file GFWireHitPolicy.h.
View newest version in sPHENIX GitHub at line 79 of file GFWireHitPolicy.h
References d, and fMaxdistance.
Member Data Documentation
GFDetPlane GFWireHitPolicy::fDetPlane private
Definition at line 87 of file GFWireHitPolicy.h.
View newest version in sPHENIX GitHub at line 87 of file GFWireHitPolicy.h
Referenced by detPlane().
double GFWireHitPolicy::fMaxdistance private
Definition at line 88 of file GFWireHitPolicy.h.
View newest version in sPHENIX GitHub at line 88 of file GFWireHitPolicy.h
Referenced by detPlane(), getMaxDistance(), and setMaxDistance().
const std::string GFWireHitPolicy::fPolicyName = "GFWireHitPolicy" static private
Definition at line 83 of file GFWireHitPolicy.h.
View newest version in sPHENIX GitHub at line 83 of file GFWireHitPolicy.h
Referenced by getName().
The documentation for this class was generated from the following files:
EicRoot/blob/master/genfit/GFWireHitPolicy.h
EicRoot/blob/master/genfit/GFWireHitPolicy.cxx