EIC Software: EicToyModel/blob/master/include/EicGeoParData.h File Reference
EicGeoParData.h File Reference
#include <stdlib.h>
#include <assert.h>
#include <set>
#include <map>
#include <vector>
#include <TString.h>
#include <TObject.h>
#include <TFile.h>
#include <TGeoManager.h>
#include <TTimeStamp.h>
#include <TVector3.h>
#include <EicDetName.h>
#include <EicNamePatternHub.h>
#include <EicGeoMap.h>
Classes
class LogicalVolumeGroupProjection
class LogicalVolumeLookupTableEntry
class LogicalVolumeGroup
class SourceFile
class EicGeoParData
Macros
#define _LOGICAL_VOLUME_GROUP_COORD_NUM_ 3
Functions
TVector3 LocalToMaster (const TGeoMatrix *mtx, const TVector3 &local)
TVector3 LocalToMasterVect (const TGeoMatrix *mtx, const TVector3 &local)
TVector3 MasterToLocal (const TGeoMatrix *mtx, const TVector3 &master)
TVector3 MasterToLocalVect (const TGeoMatrix *mtx, const TVector3 &master)
Macro Definition Documentation
#define _LOGICAL_VOLUME_GROUP_COORD_NUM_ 3
Definition at line 62 of file EicGeoParData.h.
View newest version in sPHENIX GitHub at line 62 of file EicGeoParData.h
Referenced by LogicalVolumeGroup::LogicalVolumeGroup().
Function Documentation
TVector3 LocalToMaster (const TGeoMatrix * mtx, const TVector3 & local)
Definition at line 766 of file EicGeoParData.cxx.
View newest version in sPHENIX GitHub at line 766 of file EicGeoParData.cxx
Referenced by EicHtcTask::DeclareSensitiveVolumes(), EicPlanarRecoHit::EicPlanarRecoHit(), EicSpaceRecoHit::EicSpaceRecoHit(), EicTpcDigiHitProducer::HandleHit(), FwdTrackFinder::Init(), KalmanNodeWrapper::KalmanNodeWrapper(), and FwdHoughNodeGroup::PackFromTo().
TVector3 LocalToMasterVect (const TGeoMatrix * mtx, const TVector3 & local)
Definition at line 777 of file EicGeoParData.cxx.
View newest version in sPHENIX GitHub at line 777 of file EicGeoParData.cxx
Referenced by EicPlanarRecoHit::EicPlanarRecoHit(), and KalmanNodeWrapper::KalmanNodeWrapper().
TVector3 MasterToLocal (const TGeoMatrix * mtx, const TVector3 & master)
Definition at line 788 of file EicGeoParData.cxx.
View newest version in sPHENIX GitHub at line 788 of file EicGeoParData.cxx
Referenced by EicTpcDigiHitProducer::HandleHit(), EicTrackingDigiHitProducer::HandleHit(), FwdTrackFinder::Init(), and FwdHoughNodeGroup::PackCore().
TVector3 MasterToLocalVect (const TGeoMatrix * mtx, const TVector3 & master)
Definition at line 799 of file EicGeoParData.cxx.
View newest version in sPHENIX GitHub at line 799 of file EicGeoParData.cxx