EIC Software: fun4all_eic_qa/blob/master/macros/G4_FEMC_EIC.C File Reference
G4_FEMC_EIC.C File Reference
#include <GlobalVariables.C>
#include <G4_hFarFwdBeamLine_EIC.C>
#include <g4calo/RawTowerBuilderByHitIndex.h>
#include <g4calo/RawTowerDigitizer.h>
#include <g4eiccalos/PHG4ForwardCalCellReco.h>
#include <g4eiccalos/PHG4ForwardEcalSubsystem.h>
#include <g4eval/CaloEvaluator.h>
#include <g4main/PHG4Reco.h>
#include <caloreco/RawClusterBuilderFwd.h>
#include <caloreco/RawClusterBuilderTemplate.h>
#include <caloreco/RawTowerCalibration.h>
#include <fun4all/Fun4AllServer.h>
#include <algorithm>
Namespaces
namespace Enable
namespace G4FEMC
namespace G4FEMC::SETTING
Macros
#define MACRO_G4FEMCEIC_C
Enumerations
enum G4FEMC::enu_Femc_clusterizer {
G4FEMC::kFemcGraphClusterizer, G4FEMC::kFemcTemplateClusterizer, G4FEMC::kFemcGraphClusterizer, G4FEMC::kFemcTemplateClusterizer,
G4FEMC::kFemcGraphClusterizer, G4FEMC::kFemcTemplateClusterizer
}
Functions
void FEMCInit ()
void FEMCSetup (PHG4Reco *g4Reco)
void FEMC_Cells ()
void FEMC_Towers ()
void FEMC_Clusters ()
void FEMC_Eval (const std::string &outputfile)
Variables
double G4FEMC::sampling_fraction = 0.4
Macro Definition Documentation
#define MACRO_G4FEMCEIC_C
Definition at line 2 of file G4_FEMC_EIC.C.
View newest version in sPHENIX GitHub at line 2 of file G4_FEMC_EIC.C
Function Documentation
void FEMC_Cells ()
Definition at line 171 of file G4_FEMC_EIC.C.
View newest version in sPHENIX GitHub at line 171 of file G4_FEMC_EIC.C
void FEMC_Clusters ()
Definition at line 374 of file G4_FEMC_EIC.C.
View newest version in sPHENIX GitHub at line 374 of file G4_FEMC_EIC.C
References RawClusterBuilderTemplate::Detector(), RawClusterBuilderFwd::Detector(), exit(), G4FEMC::Femc_clusterizer, Enable::FEMC_VERBOSITY, Fun4AllServer::instance(), G4FEMC::kFemcGraphClusterizer, G4FEMC::kFemcTemplateClusterizer, RawClusterBuilderTemplate::LoadProfile(), max, Fun4AllServer::registerSubsystem(), RawClusterBuilderFwd::set_threshold_energy(), RawClusterBuilderTemplate::set_threshold_energy(), Enable::VERBOSITY, and Fun4AllBase::Verbosity().
void FEMC_Eval (const std::string & outputfile)
Definition at line 409 of file G4_FEMC_EIC.C.
View newest version in sPHENIX GitHub at line 409 of file G4_FEMC_EIC.C
References Enable::FEMC_VERBOSITY, Fun4AllServer::instance(), max, Fun4AllServer::registerSubsystem(), Enable::VERBOSITY, and Fun4AllBase::Verbosity().
void FEMC_Towers ()
Definition at line 176 of file G4_FEMC_EIC.C.
View newest version in sPHENIX GitHub at line 176 of file G4_FEMC_EIC.C
References G4FEMC::SETTING::asymmetric, RawTowerDigitizer::Detector(), RawTowerCalibration::Detector(), RawTowerBuilderByHitIndex::Detector(), G4FEMC::SETTING::EC2x, Enable::FEMC_VERBOSITY, G4FEMC::SETTING::fsPHENIX, G4FEMC::SETTING::FullEtaAcc, G4FEMC::SETTING::FwdSquare, RawTowerBuilderByHitIndex::GeometryTableFile(), Fun4AllServer::instance(), Enable::IP6, RawTowerDigitizer::kNo_digitization, RawTowerCalibration::kSimple_linear_calibration, max, G4FEMC::SETTING::readoutsplit, Fun4AllServer::registerSubsystem(), G4FHCAL::sampling_fraction, RawTowerCalibration::set_calib_algorithm(), RawTowerCalibration::set_calib_const_GeV_ADC(), RawTowerDigitizer::set_digi_algorithm(), RawTowerCalibration::set_pedstal_ADC(), RawTowerBuilderByHitIndex::set_sim_tower_node_prefix(), RawTowerDigitizer::TowerType(), RawTowerCalibration::TowerType(), Enable::VERBOSITY, Fun4AllBase::Verbosity(), and G4FEMC::SETTING::wDR.
void FEMCInit ()
Definition at line 71 of file G4_FEMC_EIC.C.
View newest version in sPHENIX GitHub at line 71 of file G4_FEMC_EIC.C
References G4FEMC::SETTING::asymmetric, G4FEMC::SETTING::fsPHENIX, G4FEMC::SETTING::FullEtaAcc, G4FEMC::SETTING::FwdSquare, G4FEMC::Gdz, G4FEMC::Gz0, max, BlackHoleGeometry::max_radius, BlackHoleGeometry::max_z, min, BlackHoleGeometry::min_z, G4FEMC::outer_radius, and G4FEMC::SETTING::wDR.
void FEMCSetup (PHG4Reco * g4Reco)
Use dedicated FEMC module
Definition at line 85 of file G4_FEMC_EIC.C.
View newest version in sPHENIX GitHub at line 85 of file G4_FEMC_EIC.C
References Enable::ABSORBER, G4FEMC::SETTING::asymmetric, G4FEMC::SETTING::EC2x, femc(), Enable::FEMC_ABSORBER, Enable::FEMC_OVERLAPCHECK, G4FEMC::SETTING::fsPHENIX, G4FEMC::SETTING::FullEtaAcc, G4FEMC::SETTING::FwdSquare, Fun4AllServer::instance(), Enable::IP6, Enable::OVERLAPCHECK, PHG4DetectorSubsystem::OverlapCheck(), G4FEMC::SETTING::readoutsplit, PHG4Reco::registerSubsystem(), PHG4DetectorSubsystem::SetAbsorberActive(), PHG4DetectorSubsystem::SetActive(), PHG4ForwardEcalSubsystem::SetDetailed(), PHG4ForwardEcalSubsystem::SetTowerMappingFile(), PHG4DetectorSubsystem::SuperDetector(), and G4FEMC::SETTING::wDR.