EIC Software: Acts::PrimitivesVisualization Namespace Reference
Acts::PrimitivesVisualization Namespace Reference
Functions
static std::string test (IVisualization &helper)
Variables
auto identity = std::make_shared<Transform3D>(Transform3D::Identity())
auto rectangle = std::make_shared<RectangleBounds>(10., 10.)
auto plane = Surface::makeShared<PlaneSurface>(identity, rectangle)
GeometryContext gctx = GeometryContext()
Function Documentation
static std::string Acts::PrimitivesVisualization::test (IVisualization & helper) inline static
Helper method to visualiza all types of surfaces
Parameters
helper The visualziation helper
Returns
an overall string including all written output
Definition at line 41 of file PrimitivesVisualizationBase.hpp.
View newest version in sPHENIX GitHub at line 41 of file PrimitivesVisualizationBase.hpp
References Acts::IVisualization::clear(), Acts::Visualization::drawArrowBackward(), Acts::Visualization::drawArrowForward(), Acts::Visualization::drawArrowsBoth(), Acts::Visualization::drawCovarianceAngular(), Acts::Visualization::drawCovarianceCartesian(), Acts::Visualization::drawSegment(), Acts::Visualization::drawSurface(), gctx, Acts::Test::origin(), plane, s1, and Acts::IVisualization::write().
Referenced by Acts::Test::BOOST_AUTO_TEST_CASE().
Variable Documentation
GeometryContext Acts::PrimitivesVisualization::gctx = GeometryContext()
Definition at line 34 of file PrimitivesVisualizationBase.hpp.
View newest version in sPHENIX GitHub at line 34 of file PrimitivesVisualizationBase.hpp
Referenced by test().
auto Acts::PrimitivesVisualization::identity = std::make_shared<Transform3D>(Transform3D::Identity())
Definition at line 29 of file PrimitivesVisualizationBase.hpp.
View newest version in sPHENIX GitHub at line 29 of file PrimitivesVisualizationBase.hpp
Referenced by Acts::VolumeVisualization::test(), Acts::EventDataVisualization::test(), and Acts::SurfaceVisualization::test().
auto Acts::PrimitivesVisualization::plane = Surface::makeShared<PlaneSurface>(identity, rectangle)
Definition at line 31 of file PrimitivesVisualizationBase.hpp.
View newest version in sPHENIX GitHub at line 31 of file PrimitivesVisualizationBase.hpp
Referenced by Acts::Test::BOOST_AUTO_TEST_CASE(), genfit::KalmanFitterInfo::checkConsistency(), checkErrorPropagation(), checkSetGetPosMom(), checkStopAtBoundary(), compareForthBackExtrapolation(), compareForthBackJacNoise(), genfit::GblFitter::constructGblInfo(), genfit::MeasurementCreator::create(), Acts::LayerArrayCreator::createNavigationSurface(), genfit::RKTrackRep::extrapolateBy(), genfit::RKTrackRep::extrapolateToCone(), genfit::RKTrackRep::extrapolateToCylinder(), genfit::RKTrackRep::extrapolateToLine(), genfit::RKTrackRep::extrapolateToPlane(), LSLTrackRep::extrapolateToPoint(), genfit::RKTrackRep::extrapolateToSphere(), genfit::RKTrackRep::extrapToPoint(), GeaneTrackRep::GeaneTrackRep(), GFTools::getBiasedSmoothedPosXYZ(), genfit::KalmanFitterInfo::getResidual(), GFTools::getSmoothedPosXYZ(), PHGenFit::PlanarMeasurement::init(), main(), Acts::Test::make_trackstate(), genfit::KalmanFitterRefTrack::prepareTrack(), genfit::KalmanFitter::processTrackPoint(), genfit::GFGbl::processTrackWithRep(), genfit::StateOnPlane::setPlane(), genfit::AbsFitterInfo::setPlane(), genfit::RKTrackRep::setPosMom(), genfit::StateOnPlane::setStatePlane(), genfit::GblFitter::sortHits(), Acts::EventDataVisualization::test(), test(), Acts::SurfaceVisualization::test(), PHGenFit2::Track::updateOneMeasurementKalman(), and PHGenFit::Track::updateOneMeasurementKalman().
auto Acts::PrimitivesVisualization::rectangle = std::make_shared<RectangleBounds>(10., 10.)
Definition at line 30 of file PrimitivesVisualizationBase.hpp.
View newest version in sPHENIX GitHub at line 30 of file PrimitivesVisualizationBase.hpp
Referenced by Acts::Test::BOOST_AUTO_TEST_CASE(), Acts::EventDataVisualization::test(), and Acts::SurfaceVisualization::test().