EIC Software: Gammagammasingle Class Reference
Gammagammasingle Class Reference
#include <estarlight/blob/master/include/gammagammasingle.h>
Public Member Functions
Gammagammasingle (const inputParameters &input, beamBeamSystem &bbsystem)
~Gammagammasingle ()
void singleCrossSection ()
starlightConstants::event produceEvent (int &ievent)
eXEvent e_produceEvent ()
Public Member Functions inherited from eventChannel
eventChannel (const inputParameters &input, beamBeamSystem &bbsystem)
virtual ~eventChannel ()
unsigned long nmbAttempts () const
returns number of attempted events
unsigned long nmbAccepted () const
returns number of accepted events
double getTotalChannelCrossSection () const
void setTotalChannelCrossSection (double sigma)
Public Member Functions inherited from readLuminosity
readLuminosity (const inputParameters &input)
~readLuminosity ()
void read ()
void e_read ()
Private Member Functions
void pickw (double &w)
void picky (double &y)
void parentMomentum (double w, double y, double &E, double &px, double &py, double &pz)
double pp1 (double E)
double pp2 (double E)
void twoBodyDecay (starlightConstants::particleTypeEnum &ipid, double W, double px0, double py0, double pz0, double &px1, double &py1, double &pz1, double &px2, double &py2, double &pz2, int &iFbadevent)
double getMass ()
double getWidth ()
double getSpin ()
Private Attributes
double _sigmax [starlightLimits::MAXWBINS][starlightLimits::MAXYBINS]
double _wdelta
double _remainwd
int _ivalwd
starlightConstants::particleTypeEnum _GGsingInputpidtest
int _GGsingInputnumw
int _GGsingInputnumy
double _GGsingInputGamma_em
double _axionMass
Additional Inherited Members
Static Public Member Functions inherited from eventChannel
static void transform (const double betax, const double betay, const double betaz, double &E, double &px, double &py, double &pz, int &iFbadevent)
Lorentz-transforms given 4-vector.
static double pseudoRapidity (const double px, const double py, const double pz)
calculates pseudorapidity for given 3-momentum
Public Attributes inherited from eventChannel
beamBeamSystem _bbs
randomGenerator _randy
Protected Attributes inherited from eventChannel
unsigned long _nmbAttempts
number of attempted events
unsigned long _nmbAccepted
number of accepted events
bool _ptCutEnabled
en/disables cut in pt
double _ptCutMin
minimum pt, if cut is enabled
double _ptCutMax
maximum pt, if cut is enabled
bool _etaCutEnabled
en/disables cut in eta
double _etaCutMin
minimum eta, if cut is enabled
double _etaCutMax
maximum eta, if cut is enabled
double _totalChannelCrossSection
Detailed Description
Definition at line 51 of file gammagammasingle.h.
View newest version in sPHENIX GitHub at line 51 of file gammagammasingle.h
Constructor & Destructor Documentation
Gammagammasingle::Gammagammasingle (const inputParameters & input, beamBeamSystem & bbsystem)
Definition at line 47 of file gammagammasingle.cpp.
View newest version in sPHENIX GitHub at line 47 of file gammagammasingle.cpp
References _axionMass, _GGsingInputGamma_em, _GGsingInputnumw, _GGsingInputnumy, _GGsingInputpidtest, inputParameters::axionMass(), inputParameters::beamLorentzGamma(), inputParameters::nmbRapidityBins(), inputParameters::nmbWBins(), inputParameters::prodParticleType(), readLuminosity::read(), and singleCrossSection().
Gammagammasingle::~Gammagammasingle ()
Definition at line 73 of file gammagammasingle.cpp.
View newest version in sPHENIX GitHub at line 73 of file gammagammasingle.cpp
Member Function Documentation
eXEvent Gammagammasingle::e_produceEvent () virtual
Implements eventChannel.
Definition at line 623 of file gammagammasingle.cpp.
View newest version in sPHENIX GitHub at line 623 of file gammagammasingle.cpp
double Gammagammasingle::getMass () private
Definition at line 506 of file gammagammasingle.cpp.
View newest version in sPHENIX GitHub at line 506 of file gammagammasingle.cpp
References _axionMass, _GGsingInputpidtest, starlightConstants::A2, starlightConstants::a2Mass, starlightConstants::AXION, starlightConstants::ETA, starlightConstants::ETAC, starlightConstants::etaCMass, starlightConstants::etaMass, starlightConstants::ETAPRIME, starlightConstants::etaPrimeMass, starlightConstants::F0, starlightConstants::f0Mass, starlightConstants::F2, starlightConstants::f2Mass, starlightConstants::F2PRIME, starlightConstants::f2PrimeMass, starlightConstants::ZOVERZ03, and starlightConstants::zoverz03Mass.
Referenced by singleCrossSection().
double Gammagammasingle::getSpin () private
Definition at line 587 of file gammagammasingle.cpp.
View newest version in sPHENIX GitHub at line 587 of file gammagammasingle.cpp
References _GGsingInputpidtest, starlightConstants::A2, starlightConstants::a2Spin, starlightConstants::AXION, starlightConstants::axionSpin, starlightConstants::ETA, starlightConstants::ETAC, starlightConstants::etaCSpin, starlightConstants::ETAPRIME, starlightConstants::etaPrimeSpin, starlightConstants::etaSpin, starlightConstants::F0, starlightConstants::f0Spin, starlightConstants::F2, starlightConstants::F2PRIME, starlightConstants::f2PrimeSpin, starlightConstants::f2Spin, starlightConstants::ZOVERZ03, and starlightConstants::zoverz03Spin.
Referenced by singleCrossSection().
double Gammagammasingle::getWidth () private
Definition at line 546 of file gammagammasingle.cpp.
View newest version in sPHENIX GitHub at line 546 of file gammagammasingle.cpp
References _axionMass, _GGsingInputpidtest, starlightConstants::A2, starlightConstants::a2PartialggWidth, starlightConstants::AXION, starlightConstants::ETA, starlightConstants::ETAC, starlightConstants::etaCPartialggWidth, starlightConstants::etaPartialggWidth, starlightConstants::ETAPRIME, starlightConstants::etaPrimePartialggWidth, starlightConstants::F0, starlightConstants::f0PartialggWidth, starlightConstants::F2, starlightConstants::f2PartialggWidth, starlightConstants::F2PRIME, starlightConstants::f2PrimePartialggWidth, starlightConstants::pi, starlightConstants::ZOVERZ03, and starlightConstants::zoverz03PartialggWidth.
Referenced by singleCrossSection().
void Gammagammasingle::parentMomentum (double w, double y, double & E, double & px, double & py, double & pz) private
Definition at line 278 of file gammagammasingle.cpp.
View newest version in sPHENIX GitHub at line 278 of file gammagammasingle.cpp
References eventChannel::_randy, cos(), starlightConstants::pi, pp1(), pp2(), and randomGenerator::Rndom().
void Gammagammasingle::pickw (double & w) private
Definition at line 150 of file gammagammasingle.cpp.
View newest version in sPHENIX GitHub at line 150 of file gammagammasingle.cpp
References _GGsingInputnumw, _GGsingInputnumy, _ivalwd, eventChannel::_randy, _remainwd, _sigmax, readLuminosity::_Warray, _wdelta, readLuminosity::_Yarray, c, starlightLimits::MAXWBINS, starlightLimits::MAXYBINS, randomGenerator::Rndom(), and x.
void Gammagammasingle::picky (double & y) private
Definition at line 221 of file gammagammasingle.cpp.
View newest version in sPHENIX GitHub at line 221 of file gammagammasingle.cpp
References _GGsingInputnumy, _ivalwd, eventChannel::_randy, _remainwd, _sigmax, readLuminosity::_Yarray, c, starlightLimits::MAXYBINS, randomGenerator::Rndom(), and x.
double Gammagammasingle::pp1 (double E) private
Definition at line 308 of file gammagammasingle.cpp.
View newest version in sPHENIX GitHub at line 308 of file gammagammasingle.cpp
References eventChannel::_bbs, _GGsingInputGamma_em, eventChannel::_randy, beamBeamSystem::electronBeam(), nucleus::formFactor(), starlightConstants::hbarc, nucleus::nuclearRadius(), starlightConstants::pi, randomGenerator::Rndom(), Acts::UnitConstants::u, and x.
Referenced by parentMomentum().
double Gammagammasingle::pp2 (double E) private
Definition at line 347 of file gammagammasingle.cpp.
View newest version in sPHENIX GitHub at line 347 of file gammagammasingle.cpp
References eventChannel::_bbs, _GGsingInputGamma_em, eventChannel::_randy, nucleus::formFactor(), starlightConstants::hbarc, nucleus::nuclearRadius(), starlightConstants::pi, randomGenerator::Rndom(), beamBeamSystem::targetBeam(), Acts::UnitConstants::u, and x.
Referenced by parentMomentum().
starlightConstants::event Gammagammasingle::produceEvent (int & ievent)
Definition at line 498 of file gammagammasingle.cpp.
View newest version in sPHENIX GitHub at line 498 of file gammagammasingle.cpp
void Gammagammasingle::singleCrossSection ()
Definition at line 78 of file gammagammasingle.cpp.
View newest version in sPHENIX GitHub at line 78 of file gammagammasingle.cpp
References readLuminosity::_f_max, readLuminosity::_Farray, _GGsingInputnumw, _GGsingInputnumy, _GGsingInputpidtest, _ivalwd, _remainwd, _sigmax, readLuminosity::_Warray, _wdelta, readLuminosity::_Yarray, getMass(), getSpin(), getWidth(), starlightConstants::hbarc, starlightConstants::pi, eventChannel::setTotalChannelCrossSection(), and starlightConstants::ZOVERZ03.
Referenced by Gammagammasingle().
void Gammagammasingle::twoBodyDecay (starlightConstants::particleTypeEnum & ipid, double W, double px0, double py0, double pz0, double & px1, double & py1, double & pz1, double & px2, double & py2, double & pz2, int & iFbadevent) private
Definition at line 387 of file gammagammasingle.cpp.
View newest version in sPHENIX GitHub at line 387 of file gammagammasingle.cpp
References _GGsingInputpidtest, eventChannel::_randy, starlightConstants::AXION, cos(), starlightConstants::F2, starlightConstants::F2PRIME, starlightConstants::KAONCHARGE, starlightConstants::kaonChargedMass, starlightConstants::KAONNEUTRAL, phi, starlightConstants::PHOTON, starlightConstants::pi, starlightConstants::PION, starlightConstants::pionChargedMass, randomGenerator::Rndom(), theta(), eventChannel::transform(), and starlightConstants::ZOVERZ03.
Member Data Documentation
double Gammagammasingle::_axionMass private
Definition at line 85 of file gammagammasingle.h.
View newest version in sPHENIX GitHub at line 85 of file gammagammasingle.h
Referenced by Gammagammasingle(), getMass(), and getWidth().
double Gammagammasingle::_GGsingInputGamma_em private
Definition at line 84 of file gammagammasingle.h.
View newest version in sPHENIX GitHub at line 84 of file gammagammasingle.h
Referenced by Gammagammasingle(), pp1(), and pp2().
int Gammagammasingle::_GGsingInputnumw private
Definition at line 82 of file gammagammasingle.h.
View newest version in sPHENIX GitHub at line 82 of file gammagammasingle.h
Referenced by Gammagammasingle(), pickw(), and singleCrossSection().
int Gammagammasingle::_GGsingInputnumy private
Definition at line 83 of file gammagammasingle.h.
View newest version in sPHENIX GitHub at line 83 of file gammagammasingle.h
Referenced by Gammagammasingle(), pickw(), picky(), and singleCrossSection().
starlightConstants::particleTypeEnum Gammagammasingle::_GGsingInputpidtest private
Definition at line 81 of file gammagammasingle.h.
View newest version in sPHENIX GitHub at line 81 of file gammagammasingle.h
Referenced by Gammagammasingle(), getMass(), getSpin(), getWidth(), singleCrossSection(), and twoBodyDecay().
int Gammagammasingle::_ivalwd private
Definition at line 66 of file gammagammasingle.h.
View newest version in sPHENIX GitHub at line 66 of file gammagammasingle.h
Referenced by pickw(), picky(), and singleCrossSection().
double Gammagammasingle::_remainwd private
Definition at line 65 of file gammagammasingle.h.
View newest version in sPHENIX GitHub at line 65 of file gammagammasingle.h
Referenced by pickw(), picky(), and singleCrossSection().
double Gammagammasingle::_sigmax[starlightLimits::MAXWBINS][starlightLimits::MAXYBINS] private
Definition at line 63 of file gammagammasingle.h.
View newest version in sPHENIX GitHub at line 63 of file gammagammasingle.h
Referenced by pickw(), picky(), and singleCrossSection().
double Gammagammasingle::_wdelta private
Definition at line 64 of file gammagammasingle.h.
View newest version in sPHENIX GitHub at line 64 of file gammagammasingle.h
Referenced by pickw(), and singleCrossSection().
The documentation for this class was generated from the following files:
estarlight/blob/master/include/gammagammasingle.h
estarlight/blob/master/src/gammagammasingle.cpp