EIC Software: CbmMCTrack Class Reference
CbmMCTrack Class Reference
#include <EicRoot/blob/master/cbmdata/CbmMCTrack.h>
Public Member Functions
CbmMCTrack ()
CbmMCTrack (Int_t pdgCode, Int_t motherID, Double_t px, Double_t py, Double_t pz, Double_t x, Double_t y, Double_t z, Double_t t, Int_t nPoints)
CbmMCTrack (const CbmMCTrack &track)
CbmMCTrack (TParticle *particle)
virtual ~CbmMCTrack ()
void Print (Int_t iTrack=0) const
Int_t GetPdgCode () const
Int_t GetMotherId () const
Double_t GetPx () const
Double_t GetPy () const
Double_t GetPz () const
Double_t GetStartX () const
Double_t GetStartY () const
Double_t GetStartZ () const
Double_t GetStartT () const
Double_t GetMass () const
Double_t GetEnergy () const
Double_t GetPt () const
Double_t GetP () const
Double_t GetRapidity () const
void GetMomentum (TVector3 &momentum) const
void Get4Momentum (TLorentzVector &momentum) const
void GetStartVertex (TVector3 &vertex) const
Int_t GetNPoints (DetectorId detId) const
void SetMotherId (Int_t id)
void SetNPoints (Int_t iDet, Int_t np)
Private Member Functions
ClassDef (CbmMCTrack, 2)
Private Attributes
Int_t fPdgCode
Int_t fMotherId
Double32_t fPx
Double32_t fPy
Double32_t fPz
Double32_t fStartX
Double32_t fStartY
Double32_t fStartZ
Double32_t fStartT
Int_t fNPoints
Detailed Description
Definition at line 31 of file CbmMCTrack.h.
View newest version in sPHENIX GitHub at line 31 of file CbmMCTrack.h
Constructor & Destructor Documentation
CbmMCTrack::CbmMCTrack ()
Default constructor
Definition at line 20 of file CbmMCTrack.cxx.
View newest version in sPHENIX GitHub at line 20 of file CbmMCTrack.cxx
CbmMCTrack::CbmMCTrack (Int_t pdgCode, Int_t motherID, Double_t px, Double_t py, Double_t pz, Double_t x, Double_t y, Double_t z, Double_t t, Int_t nPoints = 0)
Standard constructor
Definition at line 39 of file CbmMCTrack.cxx.
View newest version in sPHENIX GitHub at line 39 of file CbmMCTrack.cxx
References fNPoints.
CbmMCTrack::CbmMCTrack (const CbmMCTrack & track)
Copy constructor
Definition at line 62 of file CbmMCTrack.cxx.
View newest version in sPHENIX GitHub at line 62 of file CbmMCTrack.cxx
CbmMCTrack::CbmMCTrack (TParticle * particle)
Constructor from TParticle
Definition at line 82 of file CbmMCTrack.cxx.
View newest version in sPHENIX GitHub at line 82 of file CbmMCTrack.cxx
CbmMCTrack::~CbmMCTrack () virtual
Destructor
Definition at line 101 of file CbmMCTrack.cxx.
View newest version in sPHENIX GitHub at line 101 of file CbmMCTrack.cxx
Member Function Documentation
CbmMCTrack::ClassDef (CbmMCTrack , 2) private
void CbmMCTrack::Get4Momentum (TLorentzVector & momentum) const inline
Definition at line 143 of file CbmMCTrack.h.
View newest version in sPHENIX GitHub at line 143 of file CbmMCTrack.h
References fPx, fPy, fPz, and GetEnergy().
Double_t CbmMCTrack::GetEnergy () const inline
Definition at line 132 of file CbmMCTrack.h.
View newest version in sPHENIX GitHub at line 132 of file CbmMCTrack.h
References fPx, fPy, fPz, GetMass(), and mass.
Referenced by Get4Momentum(), and GetRapidity().
Double_t CbmMCTrack::GetMass () const
Definition at line 126 of file CbmMCTrack.cxx.
View newest version in sPHENIX GitHub at line 126 of file CbmMCTrack.cxx
References fPdgCode, and particle.
Referenced by GetEnergy().
void CbmMCTrack::GetMomentum (TVector3 & momentum) const inline
Definition at line 138 of file CbmMCTrack.h.
View newest version in sPHENIX GitHub at line 138 of file CbmMCTrack.h
References fPx, fPy, and fPz.
Referenced by CbmRichTestHits::Exec(), and CbmRichTestSim::Exec().
Int_t CbmMCTrack::GetMotherId () const inline
Definition at line 64 of file CbmMCTrack.h.
View newest version in sPHENIX GitHub at line 64 of file CbmMCTrack.h
References fMotherId.
Referenced by CbmRichTrainAnnElectrons::DiffElandPi(), CbmRichRingFinderIdeal::DoFind(), CbmRichTestHits::Exec(), CbmRichTestSim::Exec(), CbmRichMatchRings::Exec(), CbmRichGeoTest::FillMcHist(), CbmRichUrqmdTest::FillRichRingNofHits(), CbmRichUrqmdTest::NofHits(), CbmRichUrqmdTest::NofRings(), CbmRichGeoTest::RingParameters(), CbmRichTrainAnnSelect::SetRecFlag(), and CbmStack::UpdateTrackIndex().
Int_t CbmMCTrack::GetNPoints (DetectorId detId) const
Accessors to the number of MCPoints in the detectors
Definition at line 151 of file CbmMCTrack.cxx.
View newest version in sPHENIX GitHub at line 151 of file CbmMCTrack.cxx
References FairLogger::endl(), ERROR, fNPoints, kECAL, kMUCH, kMVD, kPSD, kREF, kRICH, kSTS, kTOF, and kTRD.
Referenced by CbmRichTestHits::Exec(), CbmRichTestSim::Exec(), and Print().
Double_t CbmMCTrack::GetP () const inline
Definition at line 75 of file CbmMCTrack.h.
View newest version in sPHENIX GitHub at line 75 of file CbmMCTrack.h
References fPx, fPy, and fPz.
Referenced by CbmRichTrainAnnElectrons::DiffElandPi(), CbmRichGeoTest::FillMcHist(), CbmRichUrqmdTest::NofRings(), and CbmRichGeoTest::RingParameters().
Int_t CbmMCTrack::GetPdgCode () const inline
Accessors
Definition at line 63 of file CbmMCTrack.h.
View newest version in sPHENIX GitHub at line 63 of file CbmMCTrack.h
References fPdgCode.
Referenced by CbmRichTrainAnnElectrons::DiffElandPi(), CbmRichRingFinderIdeal::DoFind(), CbmRichTestHits::Exec(), CbmRichTestSim::Exec(), CbmRichGeoTest::FillMcHist(), CbmRichUrqmdTest::NofHits(), CbmRichUrqmdTest::NofRings(), CbmRichGeoTest::RingParameters(), and CbmRichTrainAnnSelect::SetRecFlag().
Double_t CbmMCTrack::GetPt () const inline
Definition at line 74 of file CbmMCTrack.h.
View newest version in sPHENIX GitHub at line 74 of file CbmMCTrack.h
References fPx, and fPy.
Referenced by CbmRichGeoTest::FillMcHist(), and CbmRichGeoTest::RingParameters().
Double_t CbmMCTrack::GetPx () const inline
Definition at line 65 of file CbmMCTrack.h.
View newest version in sPHENIX GitHub at line 65 of file CbmMCTrack.h
References fPx.
Double_t CbmMCTrack::GetPy () const inline
Definition at line 66 of file CbmMCTrack.h.
View newest version in sPHENIX GitHub at line 66 of file CbmMCTrack.h
References fPy.
Double_t CbmMCTrack::GetPz () const inline
Definition at line 67 of file CbmMCTrack.h.
View newest version in sPHENIX GitHub at line 67 of file CbmMCTrack.h
References fPz.
Double_t CbmMCTrack::GetRapidity () const
Definition at line 140 of file CbmMCTrack.cxx.
View newest version in sPHENIX GitHub at line 140 of file CbmMCTrack.cxx
References Acts::UnitConstants::e, fPz, GetEnergy(), and y.
Referenced by CbmRichGeoTest::FillMcHist(), and CbmRichGeoTest::RingParameters().
Double_t CbmMCTrack::GetStartT () const inline
Definition at line 71 of file CbmMCTrack.h.
View newest version in sPHENIX GitHub at line 71 of file CbmMCTrack.h
References fStartT.
void CbmMCTrack::GetStartVertex (TVector3 & vertex) const inline
Definition at line 148 of file CbmMCTrack.h.
View newest version in sPHENIX GitHub at line 148 of file CbmMCTrack.h
References fStartX, fStartY, and fStartZ.
Referenced by CbmRichTestHits::Exec(), CbmRichTestSim::Exec(), CbmRichUrqmdTest::NofRings(), and CbmRichUrqmdTest::Vertex().
Double_t CbmMCTrack::GetStartX () const inline
Definition at line 68 of file CbmMCTrack.h.
View newest version in sPHENIX GitHub at line 68 of file CbmMCTrack.h
References fStartX.
Double_t CbmMCTrack::GetStartY () const inline
Definition at line 69 of file CbmMCTrack.h.
View newest version in sPHENIX GitHub at line 69 of file CbmMCTrack.h
References fStartY.
Double_t CbmMCTrack::GetStartZ () const inline
Definition at line 70 of file CbmMCTrack.h.
View newest version in sPHENIX GitHub at line 70 of file CbmMCTrack.h
References fStartZ.
void CbmMCTrack::Print (Int_t iTrack = 0) const
Output to screen
Definition at line 107 of file CbmMCTrack.cxx.
View newest version in sPHENIX GitHub at line 107 of file CbmMCTrack.cxx
References DEBUG, FairLogger::endl(), fMotherId, fPdgCode, fPx, fPy, fPz, GetNPoints(), kECAL, kMUCH, kMVD, kPSD, kREF, kRICH, kSTS, kTOF, and kTRD.
void CbmMCTrack::SetMotherId (Int_t id) inline
Modifiers
Definition at line 87 of file CbmMCTrack.h.
View newest version in sPHENIX GitHub at line 87 of file CbmMCTrack.h
References fMotherId.
Referenced by CbmStack::UpdateTrackIndex().
void CbmMCTrack::SetNPoints (Int_t iDet, Int_t np)
Definition at line 172 of file CbmMCTrack.cxx.
View newest version in sPHENIX GitHub at line 172 of file CbmMCTrack.cxx
References FairLogger::endl(), ERROR, fNPoints, kECAL, kMUCH, kMVD, kPSD, kREF, kRICH, kSTS, kTOF, and kTRD.
Referenced by CbmStack::FillTrackArray().
Member Data Documentation
Int_t CbmMCTrack::fMotherId private
Index of mother track. -1 for primary particles.
Definition at line 98 of file CbmMCTrack.h.
View newest version in sPHENIX GitHub at line 98 of file CbmMCTrack.h
Referenced by GetMotherId(), Print(), and SetMotherId().
Int_t CbmMCTrack::fNPoints private
Bitvector representing the number of MCPoints for this track in each subdetector. The detectors are represented by REF: Bit 0 (1 bit, max. value 1) MVD: Bit 1 - 3 (3 bits, max. value 7) STS: Bit 4 - 8 (5 bits, max. value 31) RICH: Bit 9 (1 bit, max. value 1) MUCH: Bit 10 - 14 (5 bits, max. value 31) TRD: Bit 15 - 19 (5 bits, max. value 31) TOF: Bit 20 - 23 (4 bits, max. value 15) ECAL: Bit 24 (1 bit, max. value 1) ZDC: Bit 25 (1 bit, max. value 1) The respective point numbers can be accessed and modified with the inline functions. Bits 26-31 are spare for potential additional detectors.
Definition at line 121 of file CbmMCTrack.h.
View newest version in sPHENIX GitHub at line 121 of file CbmMCTrack.h
Referenced by CbmMCTrack(), GetNPoints(), and SetNPoints().
Int_t CbmMCTrack::fPdgCode private
PDG particle code
Definition at line 95 of file CbmMCTrack.h.
View newest version in sPHENIX GitHub at line 95 of file CbmMCTrack.h
Referenced by GetMass(), GetPdgCode(), and Print().
Double32_t CbmMCTrack::fPx private
Momentum components at start vertex [GeV]
Definition at line 101 of file CbmMCTrack.h.
View newest version in sPHENIX GitHub at line 101 of file CbmMCTrack.h
Referenced by Get4Momentum(), GetEnergy(), GetMomentum(), GetP(), GetPt(), GetPx(), and Print().
Double32_t CbmMCTrack::fPy private
Definition at line 101 of file CbmMCTrack.h.
View newest version in sPHENIX GitHub at line 101 of file CbmMCTrack.h
Referenced by Get4Momentum(), GetEnergy(), GetMomentum(), GetP(), GetPt(), GetPy(), and Print().
Double32_t CbmMCTrack::fPz private
Definition at line 101 of file CbmMCTrack.h.
View newest version in sPHENIX GitHub at line 101 of file CbmMCTrack.h
Referenced by Get4Momentum(), GetEnergy(), GetMomentum(), GetP(), GetPz(), GetRapidity(), and Print().
Double32_t CbmMCTrack::fStartT private
Definition at line 104 of file CbmMCTrack.h.
View newest version in sPHENIX GitHub at line 104 of file CbmMCTrack.h
Referenced by GetStartT().
Double32_t CbmMCTrack::fStartX private
Coordinates of start vertex [cm, ns]
Definition at line 104 of file CbmMCTrack.h.
View newest version in sPHENIX GitHub at line 104 of file CbmMCTrack.h
Referenced by GetStartVertex(), and GetStartX().
Double32_t CbmMCTrack::fStartY private
Definition at line 104 of file CbmMCTrack.h.
View newest version in sPHENIX GitHub at line 104 of file CbmMCTrack.h
Referenced by GetStartVertex(), and GetStartY().
Double32_t CbmMCTrack::fStartZ private
Definition at line 104 of file CbmMCTrack.h.
View newest version in sPHENIX GitHub at line 104 of file CbmMCTrack.h
Referenced by GetStartVertex(), and GetStartZ().
The documentation for this class was generated from the following files:
EicRoot/blob/master/cbmdata/CbmMCTrack.h
EicRoot/blob/master/cbmdata/CbmMCTrack.cxx