EIC Software: Acts::bound_parameter< T, MIN, MAX > Struct Template Reference
Acts::bound_parameter< T, MIN, MAX > Struct Template Reference
type for parameter with restricted value range
#include <fun4all_acts/blob/master/Core/include/Acts/Utilities/ParameterTypes.hpp>
Static Public Member Functions
template<typename U >
static U getValue (const U &input)
retrieve value for constrained parameter value ranges
template<typename U >
static U getDifference (const U &first, const U &second)
Static Public Attributes
static constexpr bool may_modify_value
parameter values may need adjustment
static constexpr T min {MIN()}
lower bound of range
static constexpr T max {MAX()}
upper bound of range
Detailed Description
template<typename T, T(*)() MIN, T(*)() MAX>
struct Acts::bound_parameter< T, MIN, MAX >
type for parameter with restricted value range
This parameter type could be useful to describe parameter with physical meaningful bounds (e.g. radius).
Template Parameters
T type for boundary value (usually double)
MIN pointer to a constexpr function returning the lower bound of the value range
MAX pointer to a constexpr function returning the upper bound of the value range
Definition at line 58 of file ParameterTypes.hpp.
View newest version in sPHENIX GitHub at line 58 of file ParameterTypes.hpp
Member Function Documentation
template<typename T , T(*)() MIN, T(*)() MAX> template<typename U > static U Acts::bound_parameter< T, MIN, MAX >::getDifference (const U & first, const U & second) inline static
Definition at line 80 of file ParameterTypes.hpp.
View newest version in sPHENIX GitHub at line 80 of file ParameterTypes.hpp
References Acts::bound_parameter< T, MIN, MAX >::getValue().
template<typename T , T(*)() MIN, T(*)() MAX> template<typename U > static U Acts::bound_parameter< T, MIN, MAX >::getValue (const U & input) inline static
retrieve value for constrained parameter value ranges
Template Parameters
U type of the input parameter
Parameters
input input parameter value
Returns
input parameter value cut of at the boundaries bound_parameter<U<MIN<MAX>::min and bound_parameter<U,MIN,MAX>::max.
Definition at line 75 of file ParameterTypes.hpp.
View newest version in sPHENIX GitHub at line 75 of file ParameterTypes.hpp
References Acts::bound_parameter< T, MIN, MAX >::max, and Acts::bound_parameter< T, MIN, MAX >::min.
Referenced by Acts::bound_parameter< T, MIN, MAX >::getDifference().
Member Data Documentation
template<typename T , T(*)() MIN, T(*)() MAX> constexpr T Acts::bound_parameter< T, MIN, MAX >::max {MAX()} static
upper bound of range
Definition at line 62 of file ParameterTypes.hpp.
View newest version in sPHENIX GitHub at line 62 of file ParameterTypes.hpp
Referenced by Acts::bound_parameter< T, MIN, MAX >::getValue().
template<typename T , T(*)() MIN, T(*)() MAX> constexpr bool Acts::bound_parameter< T, MIN, MAX >::may_modify_value static
Initial value:
{
      true}
parameter values may need adjustment
Definition at line 59 of file ParameterTypes.hpp.
View newest version in sPHENIX GitHub at line 59 of file ParameterTypes.hpp
template<typename T , T(*)() MIN, T(*)() MAX> constexpr T Acts::bound_parameter< T, MIN, MAX >::min {MIN()} static
lower bound of range
Definition at line 61 of file ParameterTypes.hpp.
View newest version in sPHENIX GitHub at line 61 of file ParameterTypes.hpp
Referenced by Acts::bound_parameter< T, MIN, MAX >::getValue().
The documentation for this struct was generated from the following file:
fun4all_acts/blob/master/Core/include/Acts/Utilities/ParameterTypes.hpp