EIC Software: EicRoot/blob/master/eic/ayk/Mgrid.h File Reference
Mgrid.h File Reference
#include <cstdio>
#include <MgridHeader.h>
#include <MgridInterpolation.h>
#include <Mgrid.h>
#include <ThreeDeePolySpace.h>
Classes
class MgridPosition
struct t_3d_cs_vector
struct t_htc_interpolation
class Mgrid
struct t_ascii_coord
Macros
#define _R_ 0
#define _F_ 1
#define _MODE_OFF_ 0
#define _MODE_HRC_ 1
#define _MODE_ADIM_ 2
Typedefs
typedef double(* conversionfun)(double xx)
Functions
Mgrid * import_field_map (char *file_name)
Mgrid * create_single_mgrid_header (char *name, CoordSystem *coord, CoordSystem *field, MgridDirection *dir[3], unsigned cell_contents_bits)
Mgrid * create_mgrid_heap_header (char *name, int field_calculation_method)
Mgrid * import_ascii_field_map (char *file_name, char *mgrid_name, t_ascii_coord *coord, t_ascii_coord *field, int lines_to_skip)
int basic_types_match (void)
Macro Definition Documentation
#define _F_ 1
Definition at line 20 of file Mgrid.h.
View newest version in sPHENIX GitHub at line 20 of file Mgrid.h
Referenced by Mgrid::convertOutputField(), and transform_coord_type().
#define _MODE_ADIM_ 2
Definition at line 41 of file Mgrid.h.
View newest version in sPHENIX GitHub at line 41 of file Mgrid.h
Referenced by parse_htc_interpolation_string(), runge_kutta_fun(), and Mgrid::setHtcInterpolationMode().
#define _MODE_HRC_ 1
Definition at line 40 of file Mgrid.h.
View newest version in sPHENIX GitHub at line 40 of file Mgrid.h
Referenced by parse_htc_interpolation_string(), and Mgrid::setHtcInterpolationMode().
#define _MODE_OFF_ 0
Definition at line 39 of file Mgrid.h.
View newest version in sPHENIX GitHub at line 39 of file Mgrid.h
Referenced by parse_htc_interpolation_string(), and Mgrid::setHtcInterpolationMode().
#define _R_ 0
Definition at line 19 of file Mgrid.h.
View newest version in sPHENIX GitHub at line 19 of file Mgrid.h
Referenced by main(), and transform_coord_type().
Typedef Documentation
typedef double(* conversionfun)(double xx)
Definition at line 228 of file Mgrid.h.
View newest version in sPHENIX GitHub at line 228 of file Mgrid.h
Function Documentation
int basic_types_match (void)
Definition at line 1098 of file Mgrid.cxx.
View newest version in sPHENIX GitHub at line 1098 of file Mgrid.cxx
Referenced by Mgrid::exportFieldMap(), and import_field_map().
Mgrid* create_mgrid_heap_header (char * name, int field_calculation_method)
Definition at line 162 of file Mgrid.cxx.
View newest version in sPHENIX GitHub at line 162 of file Mgrid.cxx
References _CARTESIAN_, _MGRID_HEAP_, MgridHeader::coord, MgridHeader::field, MgridHeader::field_calculation_method, and CoordSystem::setSystemType().
Referenced by convert_cell_list_to_mgrid().
Mgrid* create_single_mgrid_header (char * name, CoordSystem * coord, CoordSystem * field, MgridDirection * dir[3], unsigned cell_contents_bits)
Definition at line 118 of file Mgrid.cxx.
View newest version in sPHENIX GitHub at line 118 of file Mgrid.cxx
References _MAX_KNOWN_CELL_CONTENTS_BIT_, _RECTANGULAR_MGRID_, MgridHeader::cell_contents_bits, MgridHeader::coord, MgridHeader::dir, CoordSystem::fake, MgridHeader::field, MgridDirection::getStep(), and printf().
Referenced by convert_cell_list_to_mgrid(), EicBeamLineElementMap::Initialize(), and HtcKalmanFilter::InitializeMgridSlice().
Mgrid* import_ascii_field_map (char * file_name, char * mgrid_name, t_ascii_coord * coord, t_ascii_coord * field, int lines_to_skip)
Definition at line 364 of file import.cxx.
View newest version in sPHENIX GitHub at line 364 of file import.cxx
References _ASCII_INPUT_, _CELL_DATA_DIM_MAX_, _FIELD_COMPONENT_VALUES_, _SPLIT_OFF_, calculate_swapping_rules(), convert_cell_list_to_mgrid(), t_ascii_coord::convfun, t_ascii_coord::coord_names, t_ascii_coord::coord_num, Splitter::getArgn(), Splitter::getArgp(), import_value(), release_cell_list_ram(), MgridHeader::setCreationMethod(), Splitter::splitNextString(), splitter, and t_ascii_coord::system_type.
Referenced by main().
Mgrid* import_field_map (char * file_name)
Definition at line 29 of file import.cxx.
View newest version in sPHENIX GitHub at line 29 of file import.cxx
References basic_types_match(), and MgridInterpolation::Mgrid.