EIC Software: CbmRichRingTrackAssignClosestD Class Reference
CbmRichRingTrackAssignClosestD Class Reference
Ring-Track Assignment according to the closest distance criterion.
#include <EicRoot/blob/master/rich/tracks/CbmRichRingTrackAssignClosestD.h>
Public Member Functions
CbmRichRingTrackAssignClosestD ()
Default constructor.
virtual ~CbmRichRingTrackAssignClosestD ()
Destructor.
void Init ()
Inherited from CbmRichRingTrackAssignBase.
void DoAssign (TClonesArray *rings, TClonesArray *richProj)
Inherited from CbmRichRingTrackAssignBase.
Public Member Functions inherited from CbmRichRingTrackAssignBase
CbmRichRingTrackAssignBase ()
virtual ~CbmRichRingTrackAssignBase ()
Destructor.
Private Member Functions
bool IsTrdElectron (int iTrack)
Check if global track was identified as electron in the TRD detector.
CbmRichRingTrackAssignClosestD (const CbmRichRingTrackAssignClosestD &)
Copy constructor.
CbmRichRingTrackAssignClosestD & operator= (const CbmRichRingTrackAssignClosestD &)
Assignment operator.
Private Attributes
TClonesArray * fTrdTracks
double fTrdAnnCut
bool fUseTrd
Additional Inherited Members
Protected Attributes inherited from CbmRichRingTrackAssignBase
double fMaxDistance
int fMinNofHitsInRing
Detailed Description
Ring-Track Assignment according to the closest distance criterion.
Author
Claudia Hoehne and Semen Lebedev
Date
2007
Definition at line 25 of file CbmRichRingTrackAssignClosestD.h.
View newest version in sPHENIX GitHub at line 25 of file CbmRichRingTrackAssignClosestD.h
Constructor & Destructor Documentation
CbmRichRingTrackAssignClosestD::CbmRichRingTrackAssignClosestD ()
Default constructor.
Definition at line 30 of file CbmRichRingTrackAssignClosestD.cxx.
View newest version in sPHENIX GitHub at line 30 of file CbmRichRingTrackAssignClosestD.cxx
CbmRichRingTrackAssignClosestD::~CbmRichRingTrackAssignClosestD () virtual
Destructor.
Definition at line 40 of file CbmRichRingTrackAssignClosestD.cxx.
View newest version in sPHENIX GitHub at line 40 of file CbmRichRingTrackAssignClosestD.cxx
CbmRichRingTrackAssignClosestD::CbmRichRingTrackAssignClosestD (const CbmRichRingTrackAssignClosestD &) private
Copy constructor.
Member Function Documentation
void CbmRichRingTrackAssignClosestD::DoAssign (TClonesArray * rings, TClonesArray * richProj) virtual
Inherited from CbmRichRingTrackAssignBase.
Implements CbmRichRingTrackAssignBase.
Definition at line 59 of file CbmRichRingTrackAssignClosestD.cxx.
View newest version in sPHENIX GitHub at line 59 of file CbmRichRingTrackAssignClosestD.cxx
References CbmRichRingTrackAssignBase::fMinNofHitsInRing, fTrdTracks, fUseTrd, CbmRichRing::GetCenterX(), CbmRichRing::GetCenterY(), CbmRichRing::GetNofHits(), FairTrackParam::GetX(), FairTrackParam::GetY(), IsTrdElectron(), it, CbmRichRing::SetDistance(), CbmGlobalTrack::SetRichRingIndex(), and CbmRichRing::SetTrackID().
void CbmRichRingTrackAssignClosestD::Init (void) virtual
Inherited from CbmRichRingTrackAssignBase.
Reimplemented from CbmRichRingTrackAssignBase.
Definition at line 44 of file CbmRichRingTrackAssignClosestD.cxx.
View newest version in sPHENIX GitHub at line 44 of file CbmRichRingTrackAssignClosestD.cxx
References fTrdTracks, FairRootManager::GetObject(), and FairRootManager::Instance().
Bool_t CbmRichRingTrackAssignClosestD::IsTrdElectron (int iTrack) private
Check if global track was identified as electron in the TRD detector.
Parameters
[in] iTrack Index of global track.
Returns
true if track is identified as electron, else return false.
Definition at line 142 of file CbmRichRingTrackAssignClosestD.cxx.
View newest version in sPHENIX GitHub at line 142 of file CbmRichRingTrackAssignClosestD.cxx
References fTrdAnnCut, fTrdTracks, and CbmGlobalTrack::GetTrdTrackIndex().
Referenced by DoAssign().
CbmRichRingTrackAssignClosestD& CbmRichRingTrackAssignClosestD::operator= (const CbmRichRingTrackAssignClosestD &) private
Assignment operator.
Member Data Documentation
double CbmRichRingTrackAssignClosestD::fTrdAnnCut private
Definition at line 55 of file CbmRichRingTrackAssignClosestD.h.
View newest version in sPHENIX GitHub at line 55 of file CbmRichRingTrackAssignClosestD.h
Referenced by IsTrdElectron().
TClonesArray* CbmRichRingTrackAssignClosestD::fTrdTracks private
Definition at line 53 of file CbmRichRingTrackAssignClosestD.h.
View newest version in sPHENIX GitHub at line 53 of file CbmRichRingTrackAssignClosestD.h
Referenced by DoAssign(), Init(), and IsTrdElectron().
bool CbmRichRingTrackAssignClosestD::fUseTrd private
Definition at line 56 of file CbmRichRingTrackAssignClosestD.h.
View newest version in sPHENIX GitHub at line 56 of file CbmRichRingTrackAssignClosestD.h
Referenced by DoAssign().
The documentation for this class was generated from the following files:
EicRoot/blob/master/rich/tracks/CbmRichRingTrackAssignClosestD.h
EicRoot/blob/master/rich/tracks/CbmRichRingTrackAssignClosestD.cxx