EIC Software: KFParticle_Tools Class Reference
KFParticle_Tools Class Reference
#include <fun4all_coresoftware/blob/master/offline/packages/KFParticle_sPHENIX/KFParticle_Tools.h>
Public Member Functions
KFParticle_Tools ()
KFParticle constructor.
virtual ~KFParticle_Tools ()
KFParticle makeVertex (PHCompositeNode *topNode)
std::vector< KFParticle > makeAllPrimaryVertices (PHCompositeNode *topNode)
KFParticle makeParticle (PHCompositeNode *topNode)
Return a KFPTrack from track vector and covariance matrix. No mass or vertex constraints.
std::vector< KFParticle > makeAllDaughterParticles (PHCompositeNode *topNode)
int getTracksFromVertex (PHCompositeNode *topNode, KFParticle vertex)
const bool isGoodTrack (KFParticle particle, const std::vector< KFParticle > primaryVertices)
int calcMinIP (KFParticle track, std::vector< KFParticle > PVs, float &minimumIP, float &minimumIPchi2)
std::vector< int > findAllGoodTracks (std::vector< KFParticle > daughterParticles, std::vector< KFParticle > primaryVertices)
std::vector< std::vector< int > > findTwoProngs (std::vector< KFParticle > daughterParticles, std::vector< int > goodTrackIndex, int nTracks)
std::vector< std::vector< int > > findNProngs (std::vector< KFParticle > daughterParticles, std::vector< int > goodTrackIndex, std::vector< std::vector< int >> goodTracksThatMeet, int nRequiredTracks, unsigned int nProngs)
std::vector< std::vector< int > > appendTracksToIntermediates (KFParticle intermediateResonances[], std::vector< KFParticle > daughterParticles, std::vector< int > goodTrackIndex, int num_remaining_tracks)
float eventDIRA (KFParticle particle, KFParticle vertex)
Calculates the cosine of the angle betweent the flight direction and momentum.
float flightDistanceChi2 (KFParticle particle, KFParticle vertex)
std::tuple< KFParticle, bool > buildMother (KFParticle vDaughters[], std::string daughterOrder[], bool isIntermediate, int intermediateNumber, int nTracks, bool constrainMass, float required_vertexID)
void constrainToVertex (KFParticle &particle, bool &goodCandidate, KFParticle &vertex)
std::tuple< KFParticle, bool > getCombination (KFParticle vDaughters[], std::string daughterOrder[], KFParticle vertex, bool constrain_to_vertex, bool isIntermediate, int intermediateNumber, int nTracks, bool constrainMass, float required_vertexID)
std::vector< std::vector
< std::string > > findUniqueDaughterCombinations (int start, int end)
double calculateEllipsoidRadius (int posOrNeg, double sigma_ii, double sigma_jj, double sigma_ij)
float calculateEllipsoidVolume (KFParticle particle)
void identify (KFParticle particle)
Public Member Functions inherited from KFParticle_particleList
KFParticle_particleList ()
virtual ~KFParticle_particleList ()
std::map< std::string,
particle_pair > getParticleList ()
float returnPDGMass (const int pdgIndex)
Return mother masses from KFParticleDatabase (pdg.lbl.gov/2019/reviews/rpp2019-rev-monte-carlo-numbering.pdf)
Protected Attributes
std::string m_mother_name_Tools
int m_num_intermediate_states = -1
int m_num_tracks_from_intermediate [max_tracks] = {0}
std::string m_daughter_name [max_tracks]
int m_daughter_charge [max_tracks] = {0}
int m_num_tracks = -1
bool m_has_intermediates
std::string m_intermediate_name [max_tracks]
std::pair< float, float > m_intermediate_mass_range [max_tracks]
float m_intermediate_min_pt [max_tracks] = {0}
float m_intermediate_min_dira [max_tracks] = {-1.}
float m_intermediate_min_fdchi2 [max_tracks] = {-1.}
float m_min_mass = -1
float m_max_mass = -1
float m_min_lifetime = -1
float m_max_lifetime = -1
float m_track_pt = -1
float m_track_ptchi2 = -1
float m_track_ip = -1
float m_track_ipchi2 = -1
float m_track_chi2ndof = -1
float m_comb_DCA = -1
float m_vertex_chi2ndof = -1
float m_fdchi2 = -1
float m_dira_min = -1
float m_dira_max = -1
float m_mother_pt = -1
float m_mother_ipchi2 = -1
float m_mva_cut_value = -1
bool m_get_charge_conjugate = -1
std::string m_vtx_map_node_name
std::string m_trk_map_node_name
SvtxVertexMap * m_dst_vertexmap = nullptr
SvtxTrackMap * m_dst_trackmap = nullptr
SvtxVertex * m_dst_vertex = nullptr
SvtxTrack * m_dst_track = nullptr
Static Protected Attributes
static const int max_tracks = 99
Private Member Functions
void removeDuplicates (std::vector< double > &v)
void removeDuplicates (std::vector< int > &v)
void removeDuplicates (std::vector< std::vector< int >> &v)
void removeDuplicates (std::vector< std::vector< std::string >> &v)
Additional Inherited Members
Protected Member Functions inherited from KFParticle_MVA
KFParticle_MVA ()
virtual ~KFParticle_MVA ()
std::tuple< TMVA::Reader
*, std::vector< Float_t > > initMVA ()
Float_t evaluateMVA (TMVA::Reader *reader, std::vector< Float_t > reader_floats, KFParticle particle, KFPVertex vertex)
Detailed Description
Definition at line 40 of file KFParticle_Tools.h.
View newest version in sPHENIX GitHub at line 40 of file KFParticle_Tools.h
Constructor & Destructor Documentation
KFParticle_Tools::KFParticle_Tools ()
KFParticle constructor.
Definition at line 60 of file KFParticle_Tools.cc.
View newest version in sPHENIX GitHub at line 60 of file KFParticle_Tools.cc
virtual KFParticle_Tools::~KFParticle_Tools () inline virtual
Definition at line 45 of file KFParticle_Tools.h.
View newest version in sPHENIX GitHub at line 45 of file KFParticle_Tools.h
Member Function Documentation
std::vector< std::vector< int > > KFParticle_Tools::appendTracksToIntermediates (KFParticle intermediateResonances[], std::vector< KFParticle > daughterParticles, std::vector< int > goodTrackIndex, int num_remaining_tracks)
Definition at line 339 of file KFParticle_Tools.cc.
View newest version in sPHENIX GitHub at line 339 of file KFParticle_Tools.cc
References findNProngs(), findTwoProngs(), k, m_num_intermediate_states, and p.
Referenced by KFParticle_eventReconstruction::buildChain().
std::tuple< KFParticle, bool > KFParticle_Tools::buildMother (KFParticle vDaughters[], std::string daughterOrder[], bool isIntermediate, int intermediateNumber, int nTracks, bool constrainMass, float required_vertexID)
Definition at line 457 of file KFParticle_Tools.cc.
View newest version in sPHENIX GitHub at line 457 of file KFParticle_Tools.cc
References kdfinder::abs(), eventDIRA(), flightDistanceChi2(), k, m_get_charge_conjugate, m_has_intermediates, m_intermediate_mass_range, m_intermediate_min_dira, m_intermediate_min_fdchi2, m_intermediate_min_pt, m_intermediate_name, m_max_mass, m_min_mass, m_mother_name_Tools, m_mother_pt, m_num_intermediate_states, m_num_tracks, and m_num_tracks_from_intermediate.
Referenced by getCombination().
int KFParticle_Tools::calcMinIP (KFParticle track, std::vector< KFParticle > PVs, float & minimumIP, float & minimumIPchi2)
Definition at line 206 of file KFParticle_Tools.cc.
View newest version in sPHENIX GitHub at line 206 of file KFParticle_Tools.cc
References ip().
Referenced by KFParticle_eventReconstruction::getCandidateDecay(), and isGoodTrack().
double KFParticle_Tools::calculateEllipsoidRadius (int posOrNeg, double sigma_ii, double sigma_jj, double sigma_ij)
Definition at line 576 of file KFParticle_Tools.cc.
View newest version in sPHENIX GitHub at line 576 of file KFParticle_Tools.cc
References kdfinder::abs().
float KFParticle_Tools::calculateEllipsoidVolume (KFParticle particle)
Definition at line 589 of file KFParticle_Tools.cc.
View newest version in sPHENIX GitHub at line 589 of file KFParticle_Tools.cc
References kdfinder::abs(), M_PI, and Acts::Test::volume.
Referenced by KFParticle_nTuple::fillBranch().
void KFParticle_Tools::constrainToVertex (KFParticle & particle, bool & goodCandidate, KFParticle & vertex)
Definition at line 531 of file KFParticle_Tools.cc.
View newest version in sPHENIX GitHub at line 531 of file KFParticle_Tools.cc
References eventDIRA(), flightDistanceChi2(), m_dira_max, m_dira_min, m_fdchi2, and m_mother_ipchi2.
Referenced by getCombination().
float KFParticle_Tools::eventDIRA (KFParticle particle, KFParticle vertex)
Calculates the cosine of the angle betweent the flight direction and momentum.
Definition at line 404 of file KFParticle_Tools.cc.
View newest version in sPHENIX GitHub at line 404 of file KFParticle_Tools.cc
References kdfinder::abs().
Referenced by buildMother(), constrainToVertex(), and KFParticle_nTuple::fillBranch().
std::vector< int > KFParticle_Tools::findAllGoodTracks (std::vector< KFParticle > daughterParticles, std::vector< KFParticle > primaryVertices)
Definition at line 225 of file KFParticle_Tools.cc.
View newest version in sPHENIX GitHub at line 225 of file KFParticle_Tools.cc
References isGoodTrack(), and removeDuplicates().
Referenced by KFParticle_eventReconstruction::createDecay().
std::vector< std::vector< int > > KFParticle_Tools::findNProngs (std::vector< KFParticle > daughterParticles, std::vector< int > goodTrackIndex, std::vector< std::vector< int >> goodTracksThatMeet, int nRequiredTracks, unsigned int nProngs)
Definition at line 277 of file KFParticle_Tools.cc.
View newest version in sPHENIX GitHub at line 277 of file KFParticle_Tools.cc
References m_comb_DCA, m_vertex_chi2ndof, and removeDuplicates().
Referenced by appendTracksToIntermediates(), KFParticle_eventReconstruction::buildBasicChain(), and KFParticle_eventReconstruction::buildChain().
std::vector< std::vector< int > > KFParticle_Tools::findTwoProngs (std::vector< KFParticle > daughterParticles, std::vector< int > goodTrackIndex, int nTracks)
Definition at line 239 of file KFParticle_Tools.cc.
View newest version in sPHENIX GitHub at line 239 of file KFParticle_Tools.cc
References m_comb_DCA, and m_vertex_chi2ndof.
Referenced by appendTracksToIntermediates(), KFParticle_eventReconstruction::buildBasicChain(), and KFParticle_eventReconstruction::buildChain().
std::vector< std::vector< std::string > > KFParticle_Tools::findUniqueDaughterCombinations (int start, int end)
Definition at line 552 of file KFParticle_Tools.cc.
View newest version in sPHENIX GitHub at line 552 of file KFParticle_Tools.cc
References m_daughter_name, and removeDuplicates().
Referenced by KFParticle_eventReconstruction::buildChain(), and KFParticle_eventReconstruction::getCandidateDecay().
float KFParticle_Tools::flightDistanceChi2 (KFParticle particle, KFParticle vertex)
Definition at line 431 of file KFParticle_Tools.cc.
View newest version in sPHENIX GitHub at line 431 of file KFParticle_Tools.cc
Referenced by buildMother(), constrainToVertex(), KFParticle_MVA::evaluateMVA(), and KFParticle_nTuple::fillBranch().
std::tuple< KFParticle, bool > KFParticle_Tools::getCombination (KFParticle vDaughters[], std::string daughterOrder[], KFParticle vertex, bool constrain_to_vertex, bool isIntermediate, int intermediateNumber, int nTracks, bool constrainMass, float required_vertexID)
Definition at line 541 of file KFParticle_Tools.cc.
View newest version in sPHENIX GitHub at line 541 of file KFParticle_Tools.cc
References buildMother(), and constrainToVertex().
Referenced by KFParticle_eventReconstruction::buildChain(), and KFParticle_eventReconstruction::getCandidateDecay().
int KFParticle_Tools::getTracksFromVertex (PHCompositeNode * topNode, KFParticle vertex)
Definition at line 176 of file KFParticle_Tools.cc.
View newest version in sPHENIX GitHub at line 176 of file KFParticle_Tools.cc
References SvtxVertexMap::find(), m_dst_vertexmap, m_vtx_map_node_name, SvtxVertexMap::size(), and SvtxVertex::size_tracks().
Referenced by KFParticle_nTuple::fillBranch().
void KFParticle_Tools::identify (KFParticle particle)
Definition at line 646 of file KFParticle_Tools.cc.
View newest version in sPHENIX GitHub at line 646 of file KFParticle_Tools.cc
Referenced by KFParticle_DST::printNode(), and KFParticle_sPHENIX::printParticles().
const bool KFParticle_Tools::isGoodTrack (KFParticle particle, const std::vector< KFParticle > primaryVertices)
Definition at line 188 of file KFParticle_Tools.cc.
View newest version in sPHENIX GitHub at line 188 of file KFParticle_Tools.cc
References calcMinIP(), m_track_chi2ndof, m_track_ip, m_track_ipchi2, and m_track_pt.
Referenced by findAllGoodTracks().
std::vector< KFParticle > KFParticle_Tools::makeAllDaughterParticles (PHCompositeNode * topNode)
Turn all dst tracks in KFP tracks
Definition at line 159 of file KFParticle_Tools.cc.
View newest version in sPHENIX GitHub at line 159 of file KFParticle_Tools.cc
References SvtxTrackMap::begin(), SvtxTrackMap::end(), m_dst_track, m_dst_trackmap, m_trk_map_node_name, and makeParticle().
Referenced by KFParticle_eventReconstruction::createDecay().
std::vector< KFParticle > KFParticle_Tools::makeAllPrimaryVertices (PHCompositeNode * topNode)
Definition at line 115 of file KFParticle_Tools.cc.
View newest version in sPHENIX GitHub at line 115 of file KFParticle_Tools.cc
References SvtxVertexMap::begin(), SvtxVertexMap::end(), m_dst_vertex, m_dst_vertexmap, m_vtx_map_node_name, and makeVertex().
Referenced by KFParticle_eventReconstruction::createDecay().
KFParticle KFParticle_Tools::makeParticle (PHCompositeNode * topNode)
Return a KFPTrack from track vector and covariance matrix. No mass or vertex constraints.
Definition at line 132 of file KFParticle_Tools.cc.
View newest version in sPHENIX GitHub at line 132 of file KFParticle_Tools.cc
References SvtxTrack::get_charge(), SvtxTrack::get_chisq(), SvtxTrack::get_error(), SvtxTrack::get_id(), SvtxTrack::get_ndf(), SvtxTrack::get_px(), SvtxTrack::get_py(), SvtxTrack::get_pz(), SvtxTrack::get_x(), SvtxTrack::get_y(), SvtxTrack::get_z(), and m_dst_track.
Referenced by makeAllDaughterParticles().
KFParticle KFParticle_Tools::makeVertex (PHCompositeNode * topNode)
Definition at line 91 of file KFParticle_Tools.cc.
View newest version in sPHENIX GitHub at line 91 of file KFParticle_Tools.cc
References SvtxVertex::get_chisq(), SvtxVertex::get_error(), SvtxVertex::get_ndof(), SvtxVertex::get_x(), SvtxVertex::get_y(), SvtxVertex::get_z(), and m_dst_vertex.
Referenced by makeAllPrimaryVertices().
void KFParticle_Tools::removeDuplicates (std::vector< double > & v) private
Definition at line 606 of file KFParticle_Tools.cc.
View newest version in sPHENIX GitHub at line 606 of file KFParticle_Tools.cc
References it.
Referenced by findAllGoodTracks(), findNProngs(), and findUniqueDaughterCombinations().
void KFParticle_Tools::removeDuplicates (std::vector< int > & v) private
Definition at line 616 of file KFParticle_Tools.cc.
View newest version in sPHENIX GitHub at line 616 of file KFParticle_Tools.cc
References it.
void KFParticle_Tools::removeDuplicates (std::vector< std::vector< int >> & v) private
Definition at line 626 of file KFParticle_Tools.cc.
View newest version in sPHENIX GitHub at line 626 of file KFParticle_Tools.cc
References it, and v.
void KFParticle_Tools::removeDuplicates (std::vector< std::vector< std::string >> & v) private
Definition at line 636 of file KFParticle_Tools.cc.
View newest version in sPHENIX GitHub at line 636 of file KFParticle_Tools.cc
References it, and v.
Member Data Documentation
float KFParticle_Tools::m_comb_DCA = -1 protected
Definition at line 129 of file KFParticle_Tools.h.
View newest version in sPHENIX GitHub at line 129 of file KFParticle_Tools.h
Referenced by findNProngs(), findTwoProngs(), and KFParticle_sPHENIX::setMaximumDaughterDCA().
int KFParticle_Tools::m_daughter_charge[max_tracks] = {0} protected
Definition at line 98 of file KFParticle_Tools.h.
View newest version in sPHENIX GitHub at line 98 of file KFParticle_Tools.h
Referenced by KFParticle_eventReconstruction::buildChain(), KFParticle_eventReconstruction::getCandidateDecay(), and KFParticle_sPHENIX::setDaughters().
std::string KFParticle_Tools::m_daughter_name[max_tracks] protected
Definition at line 97 of file KFParticle_Tools.h.
View newest version in sPHENIX GitHub at line 97 of file KFParticle_Tools.h
Referenced by KFParticle_eventReconstruction::buildChain(), findUniqueDaughterCombinations(), KFParticle_eventReconstruction::getCandidateDecay(), KFParticle_sPHENIX::Init(), and KFParticle_sPHENIX::setDaughters().
float KFParticle_Tools::m_dira_max = -1 protected
Definition at line 137 of file KFParticle_Tools.h.
View newest version in sPHENIX GitHub at line 137 of file KFParticle_Tools.h
Referenced by constrainToVertex(), and KFParticle_sPHENIX::setMaxDIRA().
float KFParticle_Tools::m_dira_min = -1 protected
Definition at line 135 of file KFParticle_Tools.h.
View newest version in sPHENIX GitHub at line 135 of file KFParticle_Tools.h
Referenced by constrainToVertex(), and KFParticle_sPHENIX::setMinDIRA().
SvtxTrack* KFParticle_Tools::m_dst_track = nullptr protected
Definition at line 152 of file KFParticle_Tools.h.
View newest version in sPHENIX GitHub at line 152 of file KFParticle_Tools.h
Referenced by makeAllDaughterParticles(), and makeParticle().
SvtxTrackMap* KFParticle_Tools::m_dst_trackmap = nullptr protected
Definition at line 150 of file KFParticle_Tools.h.
View newest version in sPHENIX GitHub at line 150 of file KFParticle_Tools.h
Referenced by makeAllDaughterParticles().
SvtxVertex* KFParticle_Tools::m_dst_vertex = nullptr protected
Definition at line 151 of file KFParticle_Tools.h.
View newest version in sPHENIX GitHub at line 151 of file KFParticle_Tools.h
Referenced by makeAllPrimaryVertices(), and makeVertex().
SvtxVertexMap* KFParticle_Tools::m_dst_vertexmap = nullptr protected
Definition at line 149 of file KFParticle_Tools.h.
View newest version in sPHENIX GitHub at line 149 of file KFParticle_Tools.h
Referenced by getTracksFromVertex(), and makeAllPrimaryVertices().
float KFParticle_Tools::m_fdchi2 = -1 protected
Definition at line 133 of file KFParticle_Tools.h.
View newest version in sPHENIX GitHub at line 133 of file KFParticle_Tools.h
Referenced by constrainToVertex(), and KFParticle_sPHENIX::setFlightDistancechi2().
bool KFParticle_Tools::m_get_charge_conjugate = -1 protected
Definition at line 145 of file KFParticle_Tools.h.
View newest version in sPHENIX GitHub at line 145 of file KFParticle_Tools.h
Referenced by buildMother(), and KFParticle_sPHENIX::getChargeConjugate().
bool KFParticle_Tools::m_has_intermediates protected
Definition at line 101 of file KFParticle_Tools.h.
View newest version in sPHENIX GitHub at line 101 of file KFParticle_Tools.h
Referenced by buildMother(), KFParticle_eventReconstruction::createDecay(), and KFParticle_sPHENIX::hasIntermediateStates().
std::pair<float, float> KFParticle_Tools::m_intermediate_mass_range[max_tracks] protected
Definition at line 104 of file KFParticle_Tools.h.
View newest version in sPHENIX GitHub at line 104 of file KFParticle_Tools.h
Referenced by buildMother(), and KFParticle_sPHENIX::setIntermediateMassRange().
float KFParticle_Tools::m_intermediate_min_dira[max_tracks] = {-1.} protected
Definition at line 107 of file KFParticle_Tools.h.
View newest version in sPHENIX GitHub at line 107 of file KFParticle_Tools.h
Referenced by buildMother(), and KFParticle_sPHENIX::setIntermediateMinDIRA().
float KFParticle_Tools::m_intermediate_min_fdchi2[max_tracks] = {-1.} protected
Definition at line 109 of file KFParticle_Tools.h.
View newest version in sPHENIX GitHub at line 109 of file KFParticle_Tools.h
Referenced by buildMother(), and KFParticle_sPHENIX::setIntermediateMinFDchi2().
float KFParticle_Tools::m_intermediate_min_pt[max_tracks] = {0} protected
Definition at line 105 of file KFParticle_Tools.h.
View newest version in sPHENIX GitHub at line 105 of file KFParticle_Tools.h
Referenced by buildMother(), and KFParticle_sPHENIX::setIntermediateMinPT().
std::string KFParticle_Tools::m_intermediate_name[max_tracks] protected
Definition at line 102 of file KFParticle_Tools.h.
View newest version in sPHENIX GitHub at line 102 of file KFParticle_Tools.h
Referenced by KFParticle_eventReconstruction::buildChain(), buildMother(), and KFParticle_sPHENIX::setIntermediateStates().
float KFParticle_Tools::m_max_lifetime = -1 protected
Definition at line 117 of file KFParticle_Tools.h.
View newest version in sPHENIX GitHub at line 117 of file KFParticle_Tools.h
Referenced by KFParticle_sPHENIX::setMaximumLifetime().
float KFParticle_Tools::m_max_mass = -1 protected
Definition at line 113 of file KFParticle_Tools.h.
View newest version in sPHENIX GitHub at line 113 of file KFParticle_Tools.h
Referenced by buildMother(), and KFParticle_sPHENIX::setMaximumMass().
float KFParticle_Tools::m_min_lifetime = -1 protected
Definition at line 115 of file KFParticle_Tools.h.
View newest version in sPHENIX GitHub at line 115 of file KFParticle_Tools.h
Referenced by KFParticle_sPHENIX::setMinimumLifetime().
float KFParticle_Tools::m_min_mass = -1 protected
Definition at line 111 of file KFParticle_Tools.h.
View newest version in sPHENIX GitHub at line 111 of file KFParticle_Tools.h
Referenced by buildMother(), and KFParticle_sPHENIX::setMinimumMass().
float KFParticle_Tools::m_mother_ipchi2 = -1 protected
Definition at line 141 of file KFParticle_Tools.h.
View newest version in sPHENIX GitHub at line 141 of file KFParticle_Tools.h
Referenced by constrainToVertex(), and KFParticle_sPHENIX::setMotherIPchi2().
std::string KFParticle_Tools::m_mother_name_Tools protected
Definition at line 94 of file KFParticle_Tools.h.
View newest version in sPHENIX GitHub at line 94 of file KFParticle_Tools.h
Referenced by buildMother(), and KFParticle_sPHENIX::setMotherName().
float KFParticle_Tools::m_mother_pt = -1 protected
Definition at line 139 of file KFParticle_Tools.h.
View newest version in sPHENIX GitHub at line 139 of file KFParticle_Tools.h
Referenced by buildMother(), and KFParticle_sPHENIX::setMotherPT().
float KFParticle_Tools::m_mva_cut_value = -1 protected
Definition at line 143 of file KFParticle_Tools.h.
View newest version in sPHENIX GitHub at line 143 of file KFParticle_Tools.h
Referenced by KFParticle_sPHENIX::setMVACutValue().
int KFParticle_Tools::m_num_intermediate_states = -1 protected
Definition at line 95 of file KFParticle_Tools.h.
View newest version in sPHENIX GitHub at line 95 of file KFParticle_Tools.h
Referenced by appendTracksToIntermediates(), KFParticle_eventReconstruction::buildChain(), buildMother(), and KFParticle_sPHENIX::setNumberOfIntermediateStates().
int KFParticle_Tools::m_num_tracks = -1 protected
Definition at line 99 of file KFParticle_Tools.h.
View newest version in sPHENIX GitHub at line 99 of file KFParticle_Tools.h
Referenced by KFParticle_eventReconstruction::buildBasicChain(), KFParticle_eventReconstruction::buildChain(), buildMother(), KFParticle_sPHENIX::Init(), and KFParticle_sPHENIX::setNumberOfTracks().
int KFParticle_Tools::m_num_tracks_from_intermediate[max_tracks] = {0} protected
Definition at line 96 of file KFParticle_Tools.h.
View newest version in sPHENIX GitHub at line 96 of file KFParticle_Tools.h
Referenced by KFParticle_eventReconstruction::buildChain(), buildMother(), and KFParticle_sPHENIX::setNumberTracksFromIntermeditateState().
float KFParticle_Tools::m_track_chi2ndof = -1 protected
Definition at line 127 of file KFParticle_Tools.h.
View newest version in sPHENIX GitHub at line 127 of file KFParticle_Tools.h
Referenced by isGoodTrack(), and KFParticle_sPHENIX::setMaximumTrackchi2nDOF().
float KFParticle_Tools::m_track_ip = -1 protected
Definition at line 123 of file KFParticle_Tools.h.
View newest version in sPHENIX GitHub at line 123 of file KFParticle_Tools.h
Referenced by isGoodTrack(), and KFParticle_sPHENIX::setMinimumTrackIP().
float KFParticle_Tools::m_track_ipchi2 = -1 protected
Definition at line 125 of file KFParticle_Tools.h.
View newest version in sPHENIX GitHub at line 125 of file KFParticle_Tools.h
Referenced by isGoodTrack(), and KFParticle_sPHENIX::setMinimumTrackIPchi2().
float KFParticle_Tools::m_track_pt = -1 protected
Definition at line 119 of file KFParticle_Tools.h.
View newest version in sPHENIX GitHub at line 119 of file KFParticle_Tools.h
Referenced by isGoodTrack(), and KFParticle_sPHENIX::setMinimumTrackPT().
float KFParticle_Tools::m_track_ptchi2 = -1 protected
Definition at line 121 of file KFParticle_Tools.h.
View newest version in sPHENIX GitHub at line 121 of file KFParticle_Tools.h
Referenced by KFParticle_sPHENIX::setMaximumTrackPTchi2().
std::string KFParticle_Tools::m_trk_map_node_name protected
Definition at line 148 of file KFParticle_Tools.h.
View newest version in sPHENIX GitHub at line 148 of file KFParticle_Tools.h
Referenced by makeAllDaughterParticles(), KFParticle_sPHENIX::process_event(), and KFParticle_sPHENIX::setTrackMapNodeName().
float KFParticle_Tools::m_vertex_chi2ndof = -1 protected
Definition at line 131 of file KFParticle_Tools.h.
View newest version in sPHENIX GitHub at line 131 of file KFParticle_Tools.h
Referenced by findNProngs(), findTwoProngs(), and KFParticle_sPHENIX::setMaximumVertexchi2nDOF().
std::string KFParticle_Tools::m_vtx_map_node_name protected
Definition at line 147 of file KFParticle_Tools.h.
View newest version in sPHENIX GitHub at line 147 of file KFParticle_Tools.h
Referenced by getTracksFromVertex(), makeAllPrimaryVertices(), KFParticle_sPHENIX::process_event(), and KFParticle_sPHENIX::setVertexMapNodeName().
const int KFParticle_Tools::max_tracks = 99 static protected
Definition at line 93 of file KFParticle_Tools.h.
View newest version in sPHENIX GitHub at line 93 of file KFParticle_Tools.h
The documentation for this class was generated from the following files:
fun4all_coresoftware/blob/master/offline/packages/KFParticle_sPHENIX/KFParticle_Tools.h
fun4all_coresoftware/blob/master/offline/packages/KFParticle_sPHENIX/KFParticle_Tools.cc