EIC Software: KalmanFilter Class Reference
KalmanFilter Class Reference abstract
#include <EicRoot/blob/master/eic/htc/KalmanFilter.h>
Public Types
enum Direction { Undefined = -1, Forward, Backward }
enum Verbosity { Never, Error, Warning, Info }
Public Member Functions
KalmanFilter (int sdim)
~KalmanFilter ()
void SetVerbosity (Verbosity verb)
void SetXmCalculationFlag (bool flag)
void SetNodeGapMax (double value)
void SetMinFilterChiSquareCCDF (double value)
double GetMinFilterChiSquareCCDF () const
void SetMinSmootherChiSquareCCDF (double value)
void SetPositivityFixParameters (double maxFixablePositivityScrewup, double positivityCorrelationFix)
void SetRFCutoffValue (double value)
KalmanNode * AddNode (const char *name, double z, int mdim, const bool nonLinearTransportFlags[2])
KalmanNode * AddNodeWrapper (const char *name, const char *format, double z, int mdim)
int Configure (const StringList *config)
unsigned FilterPass (KalmanNode *start, KalmanNode *end, KalmanFilter::Direction fb)
unsigned FullChain (KalmanNode *start, KalmanNode *end, KalmanFilter::Direction fb, int mode)
virtual void BuildNodeList ()
void ResetFiredFlags ()
void HackGroupHitCountLimit (unsigned min)
void LatchGroupNdfControlFlags ()
KalmanNode * GetHead () const
KalmanNode * GetTail () const
int GetFilterNdf () const
double GetFilterChiSquare () const
double GetFilterChiSquareCCDF () const
int SmootherPass ()
void SetExtraNdfCount (int count)
Protected Member Functions
virtual KalmanNode * AllocateNode ()
virtual bool NeedNonLinearTransport (double z) const
Protected Attributes
std::multimap< double,
KalmanNode * > mKalmanNodePool
Private Member Functions
unsigned Calculate_x0_FR_Q (KalmanNode *start, KalmanNode *end, KalmanFilter::Direction fb, unsigned mode)
unsigned DoFilterAlgebra (KalmanNode *start, KalmanNode *end, KalmanFilter::Direction fb)
int CalculateFilterStat ()
virtual int CalculateHMatrix (KalmanNode *node)=0
virtual int Transport (KalmanNode *from, KalmanFilter::Direction fb, unsigned mode)=0
virtual int TransportExtra (KalmanNode *from, KalmanFilter::Direction fb, unsigned mode)
Private Attributes
int sDim
Verbosity mVerbosityLevel
bool mXmCalculationFlag
NodeGroup * mNodeGroups
double mNodeGapMax
double mMinSmootherChiSquareCCDF
double mMinFilterChiSquareCCDF
KfMatrix * SMTX
KfVector * SVEC
KfVector * QVEC
KfMatrix * SU
KalmanNode * mHead
KalmanNode * mTail
int mExtraNdfCount
bool mPositivityCheck
bool mForceSymmetrization
double mMaxFixablePositivityScrewup
double mPositivityCorrelationFix
double mRFCutoffValue
KalmanFilter::Direction mLastFilterPass
KalmanNode * mLastStart
KalmanNode * mLastEnd
int mNdf
double mFilterChiSquare
double mFilterChiSquareCCDF
KalmanNode * mWorstSmootherNode
KalmanNode * mWorstResettableSmootherNode
int mChainRejectedNodeNum
unsigned mExtraReturnBits
Detailed Description
Definition at line 81 of file KalmanFilter.h.
View newest version in sPHENIX GitHub at line 81 of file KalmanFilter.h
Member Enumeration Documentation
enum KalmanFilter::Direction
Enumerator:
Undefined
Forward
Backward
Definition at line 91 of file KalmanFilter.h.
View newest version in sPHENIX GitHub at line 91 of file KalmanFilter.h
enum KalmanFilter::Verbosity
Enumerator:
Never
Error
Warning
Info
Definition at line 92 of file KalmanFilter.h.
View newest version in sPHENIX GitHub at line 92 of file KalmanFilter.h
Constructor & Destructor Documentation
KalmanFilter::KalmanFilter (int sdim)
Definition at line 19 of file KalmanFilter.cxx.
View newest version in sPHENIX GitHub at line 19 of file KalmanFilter.cxx
References _MAX_FIXABLE_POSITIVITY_SCREWUP_DEFAULT_, _MIN_FILTER_CHI_SQUARE_CCDF_DEFAULT_, _MIN_SMOOTHER_CHI_SQUARE_CCDF_DEFAULT_, _POSITIVITY_CORRELATION_FIX_DEFAULT_, _RF_CUTOFF_DEFAULT_, mForceSymmetrization, mLastFilterPass, mMaxFixablePositivityScrewup, mMinFilterChiSquareCCDF, mMinSmootherChiSquareCCDF, mPositivityCheck, mPositivityCorrelationFix, mRFCutoffValue, mXmCalculationFlag, QVEC, sDim, SMTX, SU, SVEC, Undefined, and KfMatrix::Unity().
KalmanFilter::~KalmanFilter () inline
Definition at line 87 of file KalmanFilter.h.
View newest version in sPHENIX GitHub at line 87 of file KalmanFilter.h
Member Function Documentation
KalmanNode * KalmanFilter::AddNode (const char * name, double z, int mdim, const bool nonLinearTransportFlags[2])
Definition at line 64 of file KalmanFilter.cxx.
View newest version in sPHENIX GitHub at line 64 of file KalmanFilter.cxx
References KalmanNode::AllocateKfMatrices(), AllocateNode(), Backward, Forward, KalmanNode::mDim, mKalmanNodePool, KalmanNode::mName, KalmanNode::mNonLinearTransportFlags, sDim, and KalmanNode::SetZ().
Referenced by AddNodeWrapper(), and FwdTrackFinder::Init().
KalmanNode * KalmanFilter::AddNodeWrapper (const char * name, const char * format, double z, int mdim)
Definition at line 100 of file KalmanFilter.cxx.
View newest version in sPHENIX GitHub at line 100 of file KalmanFilter.cxx
References AddNode(), NeedNonLinearTransport(), and STRING_LEN_MAX.
Referenced by KalmanNodeWrapper::AllocateNewKfNode(), Configure(), and EicHtcTask::DeclareSensitiveVolumes().
virtual KalmanNode* KalmanFilter::AllocateNode () inline protected virtual
Reimplemented in TrKalmanFilter.
Definition at line 148 of file KalmanFilter.h.
View newest version in sPHENIX GitHub at line 148 of file KalmanFilter.h
Referenced by AddNode().
void KalmanFilter::BuildNodeList () virtual
Reimplemented in TrKalmanFilter.
Definition at line 114 of file KalmanFilter.cxx.
View newest version in sPHENIX GitHub at line 114 of file KalmanFilter.cxx
References KalmanNode::IsActive(), it, mHead, mKalmanNodePool, mTail, KalmanNode::SetNext(), and KalmanNode::SetPrev().
Referenced by TrKalmanFilter::BuildNodeList(), and Configure().
unsigned KalmanFilter::Calculate_x0_FR_Q (KalmanNode * start, KalmanNode * end, KalmanFilter::Direction fb, unsigned mode) private
Definition at line 373 of file KalmanFilter.cxx.
View newest version in sPHENIX GitHub at line 373 of file KalmanFilter.cxx
References _NFUN_FAILURE_, _RETURN_, _TFUN_FAILURE_, KfMatrix::CopyFrom(), KalmanNode::FF, KalmanNode::FM, KalmanNode::FR, KalmanNode::GetNext(), KalmanNode::GetPrev(), KalmanNode::GetZ(), KalmanNode::mNonLinearTransportFlags, KfMatrix::SetToProduct(), SU, Transport(), TransportExtra(), and KalmanNode::x0.
Referenced by FilterPass().
int KalmanFilter::CalculateFilterStat () private
Definition at line 533 of file KalmanFilter.cxx.
View newest version in sPHENIX GitHub at line 533 of file KalmanFilter.cxx
References KalmanNode::GetNext(), mExtraNdfCount, mFilterChiSquare, mFilterChiSquareCCDF, mLastEnd, mLastFilterPass, mLastStart, mNdf, sDim, and Undefined.
Referenced by FilterPass(), and FullChain().
virtual int KalmanFilter::CalculateHMatrix (KalmanNode * node) private pure virtual
Implemented in TrKalmanFilter.
Referenced by DoFilterAlgebra().
int KalmanFilter::Configure (const StringList * config)
Definition at line 145 of file KalmanFilter.cxx.
View newest version in sPHENIX GitHub at line 145 of file KalmanFilter.cxx
References _FIRED_RPLANE_PREFIX_, _RETURN_, AddNodeWrapper(), Backward, BuildNodeList(), check_prefix(), Forward, KalmanNode::GetNext(), charm_jet_coverage::list, NodeGroup::mAllNodeNum, NodeGroup::mFiredNodeNumMin, mHead, NodeGroup::mNextGroup, NodeList::mNextNode, StringList::mNextString, NodeList::mNode, mNodeGapMax, KalmanNode::mNodeGroupNum, mNodeGroups, NodeGroup::mNodeList, NodeGroup::mPrefices, and StringList::mString.
Referenced by TrKalmanFilter::Configure().
unsigned KalmanFilter::DoFilterAlgebra (KalmanNode * start, KalmanNode * end, KalmanFilter::Direction fb) private
Definition at line 418 of file KalmanFilter.cxx.
View newest version in sPHENIX GitHub at line 418 of file KalmanFilter.cxx
References _DSINV_FAILURE_, _HFUN_FAILURE_, _KF_RETURN_, _RETURN_, _TRANSPOSE_IN2_, _TRANSPOSE_IN3_, CalculateHMatrix(), KalmanNode::CF, Error, KalmanNode::FR, KalmanNode::GetNext(), KalmanNode::GetPrev(), mForceSymmetrization, mPositivityCheck, mRFCutoffValue, KalmanNode::Q, KfMatrix::SetToProduct(), SMTX, SU, SVEC, KfMatrix::Symmetric, KalmanNode::xf, and KalmanNode::xp.
Referenced by FilterPass(), and FullChain().
unsigned KalmanFilter::FilterPass (KalmanNode * start, KalmanNode * end, KalmanFilter::Direction fb)
Definition at line 342 of file KalmanFilter.cxx.
View newest version in sPHENIX GitHub at line 342 of file KalmanFilter.cxx
References _CALCULATE_DERIVATIVES_, _CALCULATE_PROCESS_NOISE_, Calculate_x0_FR_Q(), CalculateFilterStat(), DoFilterAlgebra(), Forward, mHead, mLastEnd, mLastFilterPass, mLastStart, mTail, and Undefined.
Referenced by EicHtcTask::Exec(), FullChain(), and FwdHoughTree::ResolveAmbiguitiesNg().
unsigned KalmanFilter::FullChain (KalmanNode * start, KalmanNode * end, KalmanFilter::Direction fb, int mode)
Definition at line 744 of file KalmanFilter.cxx.
View newest version in sPHENIX GitHub at line 744 of file KalmanFilter.cxx
References _CHAIN_FAILURE_, _CHAIN_RETURN_, _NDF_FAILURE_, _STRUST_FAILURE_, _TRUST_FILTER_FCN_, _TRUST_SMOOTHER_FCN_, _WORST_NODE_IMMUTABLE_, CalculateFilterStat(), DoFilterAlgebra(), FilterPass(), Info, mChainRejectedNodeNum, KalmanNode::mDim, mExtraReturnBits, mFilterChiSquare, mFilterChiSquareCCDF, mMinFilterChiSquareCCDF, mMinSmootherChiSquareCCDF, KalmanNode::mName, NodeGroup::mNextGroup, mNodeGroups, KalmanNode::mSmootherChiSquare, mVerbosityLevel, mWorstResettableSmootherNode, mWorstSmootherNode, printf(), KalmanNode::ResetFiredFlag(), and SmootherPass().
Referenced by EicHtcTask::Exec(), and FwdHoughTree::FinalFit().
double KalmanFilter::GetFilterChiSquare () const inline
Definition at line 134 of file KalmanFilter.h.
View newest version in sPHENIX GitHub at line 134 of file KalmanFilter.h
References mFilterChiSquare.
Referenced by EicHtcTask::Exec(), and FwdHoughTree::FinalFit().
double KalmanFilter::GetFilterChiSquareCCDF () const inline
Definition at line 135 of file KalmanFilter.h.
View newest version in sPHENIX GitHub at line 135 of file KalmanFilter.h
References mFilterChiSquareCCDF.
Referenced by EicHtcTask::Exec(), and FwdHoughTree::FinalFit().
int KalmanFilter::GetFilterNdf () const inline
Definition at line 133 of file KalmanFilter.h.
View newest version in sPHENIX GitHub at line 133 of file KalmanFilter.h
References mNdf.
Referenced by EicHtcTask::Exec(), and FwdHoughTree::FinalFit().
KalmanNode* KalmanFilter::GetHead () const inline
Definition at line 130 of file KalmanFilter.h.
View newest version in sPHENIX GitHub at line 130 of file KalmanFilter.h
References mHead.
Referenced by TrKalmanFilter::CalculateMagnetOffTransportMatrices(), EicHtcTask::Exec(), FwdHoughTree::FinalFit(), EicHtcTask::GetFairTrackParP(), FwdHoughTree::ResolveAmbiguitiesNg(), and FwdHoughTree::SetupKalmanFilter().
double KalmanFilter::GetMinFilterChiSquareCCDF () const inline
Definition at line 102 of file KalmanFilter.h.
View newest version in sPHENIX GitHub at line 102 of file KalmanFilter.h
References mMinFilterChiSquareCCDF.
Referenced by FwdHoughTree::FinalFit().
KalmanNode* KalmanFilter::GetTail () const inline
Definition at line 131 of file KalmanFilter.h.
View newest version in sPHENIX GitHub at line 131 of file KalmanFilter.h
References mTail.
Referenced by EicHtcTask::ConstructLinearTrackApproximation(), EicHtcTask::Exec(), FwdHoughTree::FinalFit(), and FwdHoughTree::ResolveAmbiguitiesNg().
void KalmanFilter::HackGroupHitCountLimit (unsigned min)
Definition at line 334 of file KalmanFilter.cxx.
View newest version in sPHENIX GitHub at line 334 of file KalmanFilter.cxx
References NodeGroup::mNextGroup, and mNodeGroups.
Referenced by FwdHoughTree::SetupKalmanFilter().
void KalmanFilter::LatchGroupNdfControlFlags ()
Definition at line 322 of file KalmanFilter.cxx.
View newest version in sPHENIX GitHub at line 322 of file KalmanFilter.cxx
References NodeGroup::mNextGroup, and mNodeGroups.
Referenced by EicHtcTask::Exec(), and FwdHoughTree::SetupKalmanFilter().
virtual bool KalmanFilter::NeedNonLinearTransport (double z) const inline protected virtual
Reimplemented in TrKalmanFilter.
Definition at line 150 of file KalmanFilter.h.
View newest version in sPHENIX GitHub at line 150 of file KalmanFilter.h
Referenced by AddNodeWrapper().
void KalmanFilter::ResetFiredFlags ()
Definition at line 305 of file KalmanFilter.cxx.
View newest version in sPHENIX GitHub at line 305 of file KalmanFilter.cxx
References it, mKalmanNodePool, NodeGroup::mNextGroup, and mNodeGroups.
Referenced by EicHtcTask::Exec(), and FwdHoughTree::SetupKalmanFilter().
void KalmanFilter::SetExtraNdfCount (int count) inline
Definition at line 142 of file KalmanFilter.h.
View newest version in sPHENIX GitHub at line 142 of file KalmanFilter.h
References mExtraNdfCount.
Referenced by FwdTrackFinder::SetExtraNdfCount().
void KalmanFilter::SetMinFilterChiSquareCCDF (double value) inline
Definition at line 101 of file KalmanFilter.h.
View newest version in sPHENIX GitHub at line 101 of file KalmanFilter.h
References mMinFilterChiSquareCCDF, and value.
Referenced by FwdTrackFinder::SetMinFilterChiSquareCCDF(), and FwdHoughTree::SetupTrackQualityIteration().
void KalmanFilter::SetMinSmootherChiSquareCCDF (double value) inline
Definition at line 103 of file KalmanFilter.h.
View newest version in sPHENIX GitHub at line 103 of file KalmanFilter.h
References mMinSmootherChiSquareCCDF, and value.
void KalmanFilter::SetNodeGapMax (double value) inline
Definition at line 99 of file KalmanFilter.h.
View newest version in sPHENIX GitHub at line 99 of file KalmanFilter.h
References mNodeGapMax, and value.
void KalmanFilter::SetPositivityFixParameters (double maxFixablePositivityScrewup, double positivityCorrelationFix) inline
Definition at line 105 of file KalmanFilter.h.
View newest version in sPHENIX GitHub at line 105 of file KalmanFilter.h
References mMaxFixablePositivityScrewup, and mPositivityCorrelationFix.
void KalmanFilter::SetRFCutoffValue (double value) inline
Definition at line 111 of file KalmanFilter.h.
View newest version in sPHENIX GitHub at line 111 of file KalmanFilter.h
References mRFCutoffValue, and value.
void KalmanFilter::SetVerbosity (Verbosity verb) inline
Definition at line 94 of file KalmanFilter.h.
View newest version in sPHENIX GitHub at line 94 of file KalmanFilter.h
References mVerbosityLevel.
void KalmanFilter::SetXmCalculationFlag (bool flag) inline
Definition at line 96 of file KalmanFilter.h.
View newest version in sPHENIX GitHub at line 96 of file KalmanFilter.h
References mXmCalculationFlag.
int KalmanFilter::SmootherPass ()
Definition at line 561 of file KalmanFilter.cxx.
View newest version in sPHENIX GitHub at line 561 of file KalmanFilter.cxx
References _CHAIN_FAILURE_, _DSINV_FAILURE_, _KF_RETURN_, _POSITIVITY_FIX_, _TRANSPOSE_IN1_, _TRANSPOSE_IN3_, Backward, Error, Forward, KalmanNode::GetNext(), KalmanNode::GetPrev(), KalmanNode::L, mExtraReturnBits, NodeGroup::mFiredNodeNum, NodeGroup::mFiredNodeNumMin, mForceSymmetrization, mLastEnd, mLastFilterPass, mLastStart, mMaxFixablePositivityScrewup, NodeGroup::mNdfControlFlag, mPositivityCheck, mPositivityCorrelationFix, KalmanNode::mSmootherChiSquare, mVerbosityLevel, mWorstResettableSmootherNode, mWorstSmootherNode, mXmCalculationFlag, printf(), KalmanNode::qq, KalmanNode::QQ, QVEC, KfMatrix::SetToProduct(), SMTX, KfMatrix::Subtract(), SVEC, KfMatrix::Symmetric, Undefined, and Warning.
Referenced by FullChain(), and FwdHoughTree::ResolveAmbiguitiesNg().
virtual int KalmanFilter::Transport (KalmanNode * from, KalmanFilter::Direction fb, unsigned mode) private pure virtual
Implemented in TrKalmanFilter.
Referenced by Calculate_x0_FR_Q().
virtual int KalmanFilter::TransportExtra (KalmanNode * from, KalmanFilter::Direction fb, unsigned mode) inline private virtual
Reimplemented in TrKalmanFilter.
Definition at line 270 of file KalmanFilter.h.
View newest version in sPHENIX GitHub at line 270 of file KalmanFilter.h
Referenced by Calculate_x0_FR_Q().
Member Data Documentation
int KalmanFilter::mChainRejectedNodeNum private
Definition at line 239 of file KalmanFilter.h.
View newest version in sPHENIX GitHub at line 239 of file KalmanFilter.h
Referenced by FullChain().
int KalmanFilter::mExtraNdfCount private
Definition at line 199 of file KalmanFilter.h.
View newest version in sPHENIX GitHub at line 199 of file KalmanFilter.h
Referenced by CalculateFilterStat(), and SetExtraNdfCount().
unsigned KalmanFilter::mExtraReturnBits private
Definition at line 245 of file KalmanFilter.h.
View newest version in sPHENIX GitHub at line 245 of file KalmanFilter.h
Referenced by FullChain(), and SmootherPass().
double KalmanFilter::mFilterChiSquare private
Definition at line 222 of file KalmanFilter.h.
View newest version in sPHENIX GitHub at line 222 of file KalmanFilter.h
Referenced by CalculateFilterStat(), FullChain(), and GetFilterChiSquare().
double KalmanFilter::mFilterChiSquareCCDF private
Definition at line 222 of file KalmanFilter.h.
View newest version in sPHENIX GitHub at line 222 of file KalmanFilter.h
Referenced by CalculateFilterStat(), FullChain(), and GetFilterChiSquareCCDF().
bool KalmanFilter::mForceSymmetrization private
Definition at line 203 of file KalmanFilter.h.
View newest version in sPHENIX GitHub at line 203 of file KalmanFilter.h
Referenced by DoFilterAlgebra(), KalmanFilter(), and SmootherPass().
KalmanNode* KalmanFilter::mHead private
Definition at line 193 of file KalmanFilter.h.
View newest version in sPHENIX GitHub at line 193 of file KalmanFilter.h
Referenced by BuildNodeList(), Configure(), FilterPass(), and GetHead().
std::multimap<double, KalmanNode*> KalmanFilter::mKalmanNodePool protected
Definition at line 142 of file KalmanFilter.h.
View newest version in sPHENIX GitHub at line 142 of file KalmanFilter.h
Referenced by AddNode(), BuildNodeList(), ResetFiredFlags(), TrKalmanFilter::SelectActiveNodes(), and TrKalmanFilter::SetUpLocations().
KalmanNode * KalmanFilter::mLastEnd private
Definition at line 215 of file KalmanFilter.h.
View newest version in sPHENIX GitHub at line 215 of file KalmanFilter.h
Referenced by CalculateFilterStat(), FilterPass(), and SmootherPass().
KalmanFilter::Direction KalmanFilter::mLastFilterPass private
Definition at line 213 of file KalmanFilter.h.
View newest version in sPHENIX GitHub at line 213 of file KalmanFilter.h
Referenced by CalculateFilterStat(), FilterPass(), KalmanFilter(), and SmootherPass().
KalmanNode* KalmanFilter::mLastStart private
Definition at line 215 of file KalmanFilter.h.
View newest version in sPHENIX GitHub at line 215 of file KalmanFilter.h
Referenced by CalculateFilterStat(), FilterPass(), and SmootherPass().
double KalmanFilter::mMaxFixablePositivityScrewup private
Definition at line 204 of file KalmanFilter.h.
View newest version in sPHENIX GitHub at line 204 of file KalmanFilter.h
Referenced by KalmanFilter(), SetPositivityFixParameters(), and SmootherPass().
double KalmanFilter::mMinFilterChiSquareCCDF private
Definition at line 179 of file KalmanFilter.h.
View newest version in sPHENIX GitHub at line 179 of file KalmanFilter.h
Referenced by FullChain(), GetMinFilterChiSquareCCDF(), KalmanFilter(), and SetMinFilterChiSquareCCDF().
double KalmanFilter::mMinSmootherChiSquareCCDF private
Definition at line 179 of file KalmanFilter.h.
View newest version in sPHENIX GitHub at line 179 of file KalmanFilter.h
Referenced by FullChain(), KalmanFilter(), and SetMinSmootherChiSquareCCDF().
int KalmanFilter::mNdf private
Definition at line 219 of file KalmanFilter.h.
View newest version in sPHENIX GitHub at line 219 of file KalmanFilter.h
Referenced by CalculateFilterStat(), and GetFilterNdf().
double KalmanFilter::mNodeGapMax private
Definition at line 176 of file KalmanFilter.h.
View newest version in sPHENIX GitHub at line 176 of file KalmanFilter.h
Referenced by Configure(), and SetNodeGapMax().
NodeGroup* KalmanFilter::mNodeGroups private
Definition at line 170 of file KalmanFilter.h.
View newest version in sPHENIX GitHub at line 170 of file KalmanFilter.h
Referenced by Configure(), FullChain(), HackGroupHitCountLimit(), LatchGroupNdfControlFlags(), and ResetFiredFlags().
bool KalmanFilter::mPositivityCheck private
Definition at line 203 of file KalmanFilter.h.
View newest version in sPHENIX GitHub at line 203 of file KalmanFilter.h
Referenced by DoFilterAlgebra(), KalmanFilter(), and SmootherPass().
double KalmanFilter::mPositivityCorrelationFix private
Definition at line 205 of file KalmanFilter.h.
View newest version in sPHENIX GitHub at line 205 of file KalmanFilter.h
Referenced by KalmanFilter(), SetPositivityFixParameters(), and SmootherPass().
double KalmanFilter::mRFCutoffValue private
Definition at line 206 of file KalmanFilter.h.
View newest version in sPHENIX GitHub at line 206 of file KalmanFilter.h
Referenced by DoFilterAlgebra(), KalmanFilter(), and SetRFCutoffValue().
KalmanNode * KalmanFilter::mTail private
Definition at line 193 of file KalmanFilter.h.
View newest version in sPHENIX GitHub at line 193 of file KalmanFilter.h
Referenced by BuildNodeList(), FilterPass(), and GetTail().
Verbosity KalmanFilter::mVerbosityLevel private
Definition at line 161 of file KalmanFilter.h.
View newest version in sPHENIX GitHub at line 161 of file KalmanFilter.h
Referenced by FullChain(), SetVerbosity(), and SmootherPass().
KalmanNode* KalmanFilter::mWorstResettableSmootherNode private
Definition at line 232 of file KalmanFilter.h.
View newest version in sPHENIX GitHub at line 232 of file KalmanFilter.h
Referenced by FullChain(), and SmootherPass().
KalmanNode* KalmanFilter::mWorstSmootherNode private
Definition at line 229 of file KalmanFilter.h.
View newest version in sPHENIX GitHub at line 229 of file KalmanFilter.h
Referenced by FullChain(), and SmootherPass().
bool KalmanFilter::mXmCalculationFlag private
Definition at line 165 of file KalmanFilter.h.
View newest version in sPHENIX GitHub at line 165 of file KalmanFilter.h
Referenced by KalmanFilter(), SetXmCalculationFlag(), and SmootherPass().
KfVector * KalmanFilter::QVEC private
Definition at line 186 of file KalmanFilter.h.
View newest version in sPHENIX GitHub at line 186 of file KalmanFilter.h
Referenced by KalmanFilter(), and SmootherPass().
int KalmanFilter::sDim private
Definition at line 150 of file KalmanFilter.h.
View newest version in sPHENIX GitHub at line 150 of file KalmanFilter.h
Referenced by AddNode(), CalculateFilterStat(), and KalmanFilter().
KfMatrix* KalmanFilter::SMTX private
Definition at line 185 of file KalmanFilter.h.
View newest version in sPHENIX GitHub at line 185 of file KalmanFilter.h
Referenced by DoFilterAlgebra(), KalmanFilter(), and SmootherPass().
KfMatrix* KalmanFilter::SU private
Definition at line 187 of file KalmanFilter.h.
View newest version in sPHENIX GitHub at line 187 of file KalmanFilter.h
Referenced by Calculate_x0_FR_Q(), DoFilterAlgebra(), and KalmanFilter().
KfVector* KalmanFilter::SVEC private
Definition at line 186 of file KalmanFilter.h.
View newest version in sPHENIX GitHub at line 186 of file KalmanFilter.h
Referenced by DoFilterAlgebra(), KalmanFilter(), and SmootherPass().
The documentation for this class was generated from the following files:
EicRoot/blob/master/eic/htc/KalmanFilter.h
EicRoot/blob/master/eic/htc/KalmanFilter.cxx