EIC Software: erhic::FileType Class Reference
erhic::FileType Class Reference abstract
#include <eic-smear/blob/master/include/eicsmear/erhic/File.h>
Public Member Functions
virtual ~FileType ()
virtual FileType * Create () const =0
virtual EventBase * AllocateEvent () const =0
virtual std::string GetGeneratorName () const
virtual void SetGeneratorName (const std::string newname="")
virtual LogReader * CreateLogReader () const =0
virtual VirtualEventFactory * CreateEventFactory (std::istream &) const =0
Protected Attributes
std::string generatorname
Detailed Description
Abstract base class for Monte Carlo file types. Describes a Monte Carlo file type and returns objects required for processing or analysis of that file type.
Definition at line 428 of file File.h.
View newest version in sPHENIX GitHub at line 428 of file File.h
Constructor & Destructor Documentation
virtual erhic::FileType::~FileType () inline virtual
Destructor.
Definition at line 433 of file File.h.
View newest version in sPHENIX GitHub at line 433 of file File.h
Member Function Documentation
virtual EventBase* erhic::FileType::AllocateEvent () const pure virtual
Returns a new event object for the generator making this type of file.
Implemented in erhic::File< erhic::EventHepMC >, and erhic::File< T >.
Referenced by erhic::Forester::AllocateEvent().
virtual FileType* erhic::FileType::Create () const pure virtual
Returns a new FileType instance.
Implemented in erhic::File< erhic::EventHepMC >, and erhic::File< T >.
virtual VirtualEventFactory* erhic::FileType::CreateEventFactory (std::istream &) const pure virtual
Returns a new event object for the generator making this type of file.
Implemented in erhic::File< erhic::EventHepMC >, and erhic::File< T >.
Referenced by erhic::Forester::OpenInput().
virtual LogReader* erhic::FileType::CreateLogReader () const pure virtual
Returns a reader to process the log file corresponding to this type of file.
Implemented in erhic::File< erhic::EventHepMC >, and erhic::File< T >.
Referenced by BuildTree().
std::string erhic::FileType::GetGeneratorName () const virtual
Returns the name of the generator. Should be entirely in lower case.
Definition at line 522 of file File.cxx.
View newest version in sPHENIX GitHub at line 522 of file File.cxx
References generatorname.
Referenced by erhic::Forester::OpenInput().
void erhic::FileType::SetGeneratorName (const std::string newname = "") virtual
Sets the name of the generator. Should be entirely in lower case.
Definition at line 527 of file File.cxx.
View newest version in sPHENIX GitHub at line 527 of file File.cxx
References c, and generatorname.
Referenced by erhic::FileFactory::GetFile().
Member Data Documentation
std::string erhic::FileType::generatorname protected
Definition at line 468 of file File.h.
View newest version in sPHENIX GitHub at line 468 of file File.h
Referenced by erhic::File< T >::File(), GetGeneratorName(), and SetGeneratorName().
The documentation for this class was generated from the following files:
eic-smear/blob/master/include/eicsmear/erhic/File.h
eic-smear/blob/master/src/erhic/File.cxx