EIC Software: erhic::EventDEMP Class Reference
erhic::EventDEMP Class Reference
#include <eic-smear/blob/master/include/eicsmear/erhic/EventDEMP.h>
Public Member Functions
EventDEMP ()
virtual bool Parse (const std::string &)
const ParticleMC * ScatteredLepton () const
Public Member Functions inherited from erhic::EventMC
EventMC ()
virtual ~EventMC ()
virtual bool RequiresEaParticleFields ()
virtual ULong64_t GetN () const
virtual Int_t GetProcess () const
virtual UInt_t GetNTracks () const
virtual const ParticleMC * GetTrack (UInt_t) const
virtual ParticleMC * GetTrack (UInt_t)
virtual const ParticleMC * BeamLepton () const
virtual const ParticleMC * BeamHadron () const
virtual const ParticleMC * ExchangeBoson () const
virtual void AddLast (ParticleMC *track)
virtual void Reset ()
void Print (const Option_t *option="") const
virtual void Clear (Option_t *="")
virtual void SetProcess (int code)
virtual void SetN (int n)
virtual void SetNTracks (int n)
virtual void SetELeptonInNuclearFrame (double energy)
virtual void SetEScatteredInNuclearFrame (double energy)
void FinalState (ParticlePtrList &particles) const
void HadronicFinalState (ParticlePtrList &) const
TLorentzVector FinalStateMomentum () const
TLorentzVector HadronicFinalStateMomentum () const
Double_t FinalStateCharge () const
std::vector< const
VirtualParticle * > GetTracks () const
Public Member Functions inherited from erhic::EventDis
virtual ~EventDis ()
EventDis ()
EventDis (const EventDis &)
EventDis & operator= (const EventDis &)
virtual Double_t GetX () const
virtual Double_t GetQ2 () const
virtual Double_t GetY () const
virtual Double_t GetYPlus () const
virtual Double_t GetW2 () const
virtual Double_t GetNu () const
virtual double GetXDoubleAngle () const
virtual double GetQ2DoubleAngle () const
virtual double GetYDoubleAngle () const
virtual double GetW2DoubleAngle () const
virtual double GetXJacquetBlondel () const
virtual double GetQ2JacquetBlondel () const
virtual double GetYJacquetBlondel () const
virtual double GetW2JacquetBlondel () const
virtual void SetLeptonKinematics (const DisKinematics &)
virtual void SetJacquetBlondelKinematics (const DisKinematics &)
virtual void SetDoubleAngleKinematics (const DisKinematics &)
virtual void CopyKinematics (const EventDis &)
Public Member Functions inherited from erhic::VirtualEvent
virtual ~VirtualEvent ()
Public Attributes
Double32_t numParticles
Double32_t weight
Additional Inherited Members
Public Types inherited from erhic::VirtualEvent
typedef std::vector< const
erhic::VirtualParticle * > ParticlePtrList
Protected Attributes inherited from erhic::EventMC
Int_t number
Event number.
Int_t process
PYTHIA code for the physics process producing the event.
Int_t nTracks
Number of Particles in the event (intermediate + final)
Double32_t ELeptonInNucl
Double32_t ELeptonOutNucl
TClonesArray particles
Particle list.
Detailed Description
Describes an event from the generator DEMP.
Definition at line 21 of file EventDEMP.h.
View newest version in sPHENIX GitHub at line 21 of file EventDEMP.h
Constructor & Destructor Documentation
erhic::EventDEMP::EventDEMP ()
Constructor.
Definition at line 16 of file EventDEMP.cxx.
View newest version in sPHENIX GitHub at line 16 of file EventDEMP.cxx
Member Function Documentation
bool erhic::EventDEMP::Parse (const std::string & line) virtual
Parses the event information from a text string.
The string must have the following format (no newlines):
"0 eventnumber numParticles
Returns true in the event of a successful read operation, false in case of an error.
Implements erhic::EventMC.
Definition at line 21 of file EventDEMP.cxx.
View newest version in sPHENIX GitHub at line 21 of file EventDEMP.cxx
References erhic::EventMC::number, numParticles, and weight.
const ParticleMC * erhic::EventDEMP::ScatteredLepton () const virtual
Returns a pointer to the lepton beam particle after scattering. See also notes in BeamLepton().
In the standard eRHIC Monte Carlo format, the scattered lepton beam is assumed to be the first final-state particle in the particle list with the same PDG code as the incident lepton beam.
Please overwrite this method accordingly! By default, it will simply use the fourth particle in the particle list. See e.g. EventPythia, EventSimple.
Reimplemented from erhic::EventMC.
Definition at line 37 of file EventDEMP.cxx.
View newest version in sPHENIX GitHub at line 37 of file EventDEMP.cxx
References erhic::EventMC::BeamLepton(), erhic::Pid::Code(), erhic::EventMC::FinalState(), and erhic::VirtualParticle::Id().
Member Data Documentation
Double32_t erhic::EventDEMP::numParticles
Definition at line 41 of file EventDEMP.h.
View newest version in sPHENIX GitHub at line 41 of file EventDEMP.h
Referenced by Parse().
Double32_t erhic::EventDEMP::weight
Definition at line 42 of file EventDEMP.h.
View newest version in sPHENIX GitHub at line 42 of file EventDEMP.h
Referenced by Parse(), and ReadEICFiles::process_event().
The documentation for this class was generated from the following files:
eic-smear/blob/master/include/eicsmear/erhic/EventDEMP.h
eic-smear/blob/master/src/erhic/EventDEMP.cxx