EIC Software: Acts::AccumulatedVolumeMaterial Class Reference
Acts::AccumulatedVolumeMaterial Class Reference
#include <fun4all_acts/blob/master/Core/include/Acts/Material/AccumulatedVolumeMaterial.hpp>
Public Member Functions
void accumulate (const MaterialProperties &mat)
Add one entry with the given material properties.
Material average ()
Private Attributes
float m_totalX0 {std::numeric_limits<float>::infinity()}
float m_totalL0 {std::numeric_limits<float>::infinity()}
float m_totalAr {0.}
float m_totalZ {0.}
float m_totalRho {0.}
float m_thickness {1.}
unsigned int m_materialEntries {0}
unsigned int m_vacuumEntries {0}
Detailed Description
Accumulate and average volume-based material properties.
This class is intended to be used during the mapping process.
Definition at line 20 of file AccumulatedVolumeMaterial.hpp.
View newest version in sPHENIX GitHub at line 20 of file AccumulatedVolumeMaterial.hpp
Member Function Documentation
void Acts::AccumulatedVolumeMaterial::accumulate (const MaterialProperties & mat)
Add one entry with the given material properties.
Definition at line 12 of file AccumulatedVolumeMaterial.cpp.
View newest version in sPHENIX GitHub at line 12 of file AccumulatedVolumeMaterial.cpp
References Acts::Material::Ar(), Acts::Material::L0(), m_materialEntries, m_thickness, m_totalAr, m_totalL0, m_totalRho, m_totalX0, m_totalZ, Acts::Material::massDensity(), Acts::MaterialProperties::material(), Acts::MaterialProperties::thickness(), Acts::Material::X0(), and Acts::Material::Z().
Referenced by Acts::Test::BOOST_AUTO_TEST_CASE(), and Acts::VolumeMaterialMapper::finalizeMaps().
Acts::Material Acts::AccumulatedVolumeMaterial::average ()
Compute the average material collected so far.
Returns
Vacuum properties if no matter has been accumulated yet.
Definition at line 36 of file AccumulatedVolumeMaterial.cpp.
View newest version in sPHENIX GitHub at line 36 of file AccumulatedVolumeMaterial.cpp
Referenced by Acts::Test::BOOST_AUTO_TEST_CASE(), and Acts::VolumeMaterialMapper::finalizeMaps().
Member Data Documentation
unsigned int Acts::AccumulatedVolumeMaterial::m_materialEntries {0} private
Definition at line 37 of file AccumulatedVolumeMaterial.hpp.
View newest version in sPHENIX GitHub at line 37 of file AccumulatedVolumeMaterial.hpp
Referenced by accumulate().
float Acts::AccumulatedVolumeMaterial::m_thickness {1.} private
Definition at line 36 of file AccumulatedVolumeMaterial.hpp.
View newest version in sPHENIX GitHub at line 36 of file AccumulatedVolumeMaterial.hpp
Referenced by accumulate().
float Acts::AccumulatedVolumeMaterial::m_totalAr {0.} private
Definition at line 33 of file AccumulatedVolumeMaterial.hpp.
View newest version in sPHENIX GitHub at line 33 of file AccumulatedVolumeMaterial.hpp
Referenced by accumulate().
float Acts::AccumulatedVolumeMaterial::m_totalL0 {std::numeric_limits<float>::infinity()} private
Definition at line 32 of file AccumulatedVolumeMaterial.hpp.
View newest version in sPHENIX GitHub at line 32 of file AccumulatedVolumeMaterial.hpp
Referenced by accumulate().
float Acts::AccumulatedVolumeMaterial::m_totalRho {0.} private
Definition at line 35 of file AccumulatedVolumeMaterial.hpp.
View newest version in sPHENIX GitHub at line 35 of file AccumulatedVolumeMaterial.hpp
Referenced by accumulate().
float Acts::AccumulatedVolumeMaterial::m_totalX0 {std::numeric_limits<float>::infinity()} private
Definition at line 31 of file AccumulatedVolumeMaterial.hpp.
View newest version in sPHENIX GitHub at line 31 of file AccumulatedVolumeMaterial.hpp
Referenced by accumulate().
float Acts::AccumulatedVolumeMaterial::m_totalZ {0.} private
Definition at line 34 of file AccumulatedVolumeMaterial.hpp.
View newest version in sPHENIX GitHub at line 34 of file AccumulatedVolumeMaterial.hpp
Referenced by accumulate().
unsigned int Acts::AccumulatedVolumeMaterial::m_vacuumEntries {0} private
Definition at line 38 of file AccumulatedVolumeMaterial.hpp.
View newest version in sPHENIX GitHub at line 38 of file AccumulatedVolumeMaterial.hpp
The documentation for this class was generated from the following files:
fun4all_acts/blob/master/Core/include/Acts/Material/AccumulatedVolumeMaterial.hpp
fun4all_acts/blob/master/Core/src/Material/AccumulatedVolumeMaterial.cpp