EIC Software: ParticleFlowElement Class Reference
ParticleFlowElement Class Reference
#include <fun4all_coresoftware/blob/master/offline/packages/particleflow/ParticleFlowElement.h>
Public Types
enum PFLOWTYPE {
UNASSIGNED = -1, MATCHED_CHARGED_HADRON = 0, UNMATCHED_CHARGED_HADRON = 1, UNMATCHED_EM_PARTICLE = 2,
UNMATCHED_NEUTRAL_HADRON = 3, LEFTOVER_EM_PARTICLE = 4
}
Public Member Functions
ParticleFlowElement ()
virtual ~ParticleFlowElement ()
virtual void identify (std::ostream &os=std::cout) const
virtual void Reset ()
Clear Event.
virtual int isValid () const
isValid returns non zero if object contains vailid data
virtual unsigned int get_id () const
virtual void set_id (unsigned int id)
virtual
ParticleFlowElement::PFLOWTYPE get_type () const
virtual void set_type (ParticleFlowElement::PFLOWTYPE)
virtual float get_px () const
virtual void set_px (float px)
virtual float get_py () const
virtual void set_py (float py)
virtual float get_pz () const
virtual void set_pz (float pz)
virtual float get_e () const
virtual void set_e (float e)
virtual float get_p () const
virtual float get_pt () const
virtual float get_et () const
virtual float get_eta () const
virtual float get_phi () const
virtual float get_mass () const
ClassDef (ParticleFlowElement, 1)
Public Member Functions inherited from PHObject
PHObject ()
ctor
virtual ~PHObject ()
dtor
virtual PHObject * CloneMe () const
Virtual copy constructor.
virtual PHObject * clone () const final
virtual PHObject * Clone (const char *newname="") const final
virtual void Copy (TObject &object) const final
virtual int isValid (const float) const
virtual int isValid (const double) const
virtual int isValid (const int) const
virtual int isValid (const unsigned int) const
virtual int isImplemented (const float f) const
virtual int isImplemented (const double f) const
virtual int isImplemented (const int i) const
virtual int isImplemented (const unsigned int i) const
virtual int Integrate () const
virtual int Integrate (PHObject *obj)
virtual void CopyFrom (const PHObject *obj)
Detailed Description
Definition at line 15 of file ParticleFlowElement.h.
View newest version in sPHENIX GitHub at line 15 of file ParticleFlowElement.h
Member Enumeration Documentation
enum ParticleFlowElement::PFLOWTYPE
Enumerator:
UNASSIGNED
MATCHED_CHARGED_HADRON
UNMATCHED_CHARGED_HADRON
UNMATCHED_EM_PARTICLE
UNMATCHED_NEUTRAL_HADRON
LEFTOVER_EM_PARTICLE
Definition at line 20 of file ParticleFlowElement.h.
View newest version in sPHENIX GitHub at line 20 of file ParticleFlowElement.h
Constructor & Destructor Documentation
ParticleFlowElement::ParticleFlowElement () inline
Definition at line 30 of file ParticleFlowElement.h.
View newest version in sPHENIX GitHub at line 30 of file ParticleFlowElement.h
virtual ParticleFlowElement::~ParticleFlowElement () inline virtual
Definition at line 31 of file ParticleFlowElement.h.
View newest version in sPHENIX GitHub at line 31 of file ParticleFlowElement.h
Member Function Documentation
ParticleFlowElement::ClassDef (ParticleFlowElement , 1)
virtual float ParticleFlowElement::get_e () const inline virtual
Reimplemented in ParticleFlowElementv1.
Definition at line 52 of file ParticleFlowElement.h.
View newest version in sPHENIX GitHub at line 52 of file ParticleFlowElement.h
Referenced by ParticleFlowJetInput::get_input().
virtual float ParticleFlowElement::get_et () const inline virtual
Reimplemented in ParticleFlowElementv1.
Definition at line 57 of file ParticleFlowElement.h.
View newest version in sPHENIX GitHub at line 57 of file ParticleFlowElement.h
virtual float ParticleFlowElement::get_eta () const inline virtual
Reimplemented in ParticleFlowElementv1.
Definition at line 58 of file ParticleFlowElement.h.
View newest version in sPHENIX GitHub at line 58 of file ParticleFlowElement.h
virtual unsigned int ParticleFlowElement::get_id () const inline virtual
Reimplemented in ParticleFlowElementv1.
Definition at line 37 of file ParticleFlowElement.h.
View newest version in sPHENIX GitHub at line 37 of file ParticleFlowElement.h
Referenced by ParticleFlowJetInput::get_input().
virtual float ParticleFlowElement::get_mass () const inline virtual
Reimplemented in ParticleFlowElementv1.
Definition at line 60 of file ParticleFlowElement.h.
View newest version in sPHENIX GitHub at line 60 of file ParticleFlowElement.h
virtual float ParticleFlowElement::get_p () const inline virtual
Reimplemented in ParticleFlowElementv1.
Definition at line 55 of file ParticleFlowElement.h.
View newest version in sPHENIX GitHub at line 55 of file ParticleFlowElement.h
virtual float ParticleFlowElement::get_phi () const inline virtual
Reimplemented in ParticleFlowElementv1.
Definition at line 59 of file ParticleFlowElement.h.
View newest version in sPHENIX GitHub at line 59 of file ParticleFlowElement.h
virtual float ParticleFlowElement::get_pt () const inline virtual
Reimplemented in ParticleFlowElementv1.
Definition at line 56 of file ParticleFlowElement.h.
View newest version in sPHENIX GitHub at line 56 of file ParticleFlowElement.h
virtual float ParticleFlowElement::get_px () const inline virtual
Reimplemented in ParticleFlowElementv1.
Definition at line 43 of file ParticleFlowElement.h.
View newest version in sPHENIX GitHub at line 43 of file ParticleFlowElement.h
Referenced by ParticleFlowJetInput::get_input().
virtual float ParticleFlowElement::get_py () const inline virtual
Reimplemented in ParticleFlowElementv1.
Definition at line 46 of file ParticleFlowElement.h.
View newest version in sPHENIX GitHub at line 46 of file ParticleFlowElement.h
Referenced by ParticleFlowJetInput::get_input().
virtual float ParticleFlowElement::get_pz () const inline virtual
Reimplemented in ParticleFlowElementv1.
Definition at line 49 of file ParticleFlowElement.h.
View newest version in sPHENIX GitHub at line 49 of file ParticleFlowElement.h
Referenced by ParticleFlowJetInput::get_input().
virtual ParticleFlowElement::PFLOWTYPE ParticleFlowElement::get_type () const inline virtual
Reimplemented in ParticleFlowElementv1.
Definition at line 40 of file ParticleFlowElement.h.
View newest version in sPHENIX GitHub at line 40 of file ParticleFlowElement.h
void ParticleFlowElement::identify (std::ostream & os = std::cout) const virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from PHObject.
Reimplemented in ParticleFlowElementv1.
Definition at line 5 of file ParticleFlowElement.cc.
View newest version in sPHENIX GitHub at line 5 of file ParticleFlowElement.cc
virtual int ParticleFlowElement::isValid () const inline virtual
isValid returns non zero if object contains vailid data
Reimplemented from PHObject.
Reimplemented in ParticleFlowElementv1.
Definition at line 35 of file ParticleFlowElement.h.
View newest version in sPHENIX GitHub at line 35 of file ParticleFlowElement.h
virtual void ParticleFlowElement::Reset () inline virtual
Clear Event.
Reimplemented from PHObject.
Reimplemented in ParticleFlowElementv1.
Definition at line 34 of file ParticleFlowElement.h.
View newest version in sPHENIX GitHub at line 34 of file ParticleFlowElement.h
virtual void ParticleFlowElement::set_e (float e) inline virtual
Reimplemented in ParticleFlowElementv1.
Definition at line 53 of file ParticleFlowElement.h.
View newest version in sPHENIX GitHub at line 53 of file ParticleFlowElement.h
Referenced by ParticleFlowReco::process_event().
virtual void ParticleFlowElement::set_id (unsigned int id) inline virtual
Reimplemented in ParticleFlowElementv1.
Definition at line 38 of file ParticleFlowElement.h.
View newest version in sPHENIX GitHub at line 38 of file ParticleFlowElement.h
Referenced by ParticleFlowReco::process_event().
virtual void ParticleFlowElement::set_px (float px) inline virtual
Reimplemented in ParticleFlowElementv1.
Definition at line 44 of file ParticleFlowElement.h.
View newest version in sPHENIX GitHub at line 44 of file ParticleFlowElement.h
Referenced by ParticleFlowReco::process_event().
virtual void ParticleFlowElement::set_py (float py) inline virtual
Reimplemented in ParticleFlowElementv1.
Definition at line 47 of file ParticleFlowElement.h.
View newest version in sPHENIX GitHub at line 47 of file ParticleFlowElement.h
Referenced by ParticleFlowReco::process_event().
virtual void ParticleFlowElement::set_pz (float pz) inline virtual
Reimplemented in ParticleFlowElementv1.
Definition at line 50 of file ParticleFlowElement.h.
View newest version in sPHENIX GitHub at line 50 of file ParticleFlowElement.h
Referenced by ParticleFlowReco::process_event().
virtual void ParticleFlowElement::set_type (ParticleFlowElement::PFLOWTYPE) inline virtual
Reimplemented in ParticleFlowElementv1.
Definition at line 41 of file ParticleFlowElement.h.
View newest version in sPHENIX GitHub at line 41 of file ParticleFlowElement.h
Referenced by ParticleFlowReco::process_event().
The documentation for this class was generated from the following files:
fun4all_coresoftware/blob/master/offline/packages/particleflow/ParticleFlowElement.h
fun4all_coresoftware/blob/master/offline/packages/particleflow/ParticleFlowElement.cc