EIC Software: FairDbConfigSet Class Reference
FairDbConfigSet Class Reference
#include <EicRoot/blob/master/dbase/dbInterface/FairDbConfigSet.h>
Classes
struct Param
Public Member Functions
FairDbConfigSet ()
virtual ~FairDbConfigSet ()
virtual FairDbTableRow * CreateTableRow () const
Int_t GetAggregateNo () const
UInt_t GetNumParams () const
string GetParamName (UInt_t parNo) const
FairDbFieldType GetParamType (UInt_t parNo) const
string GetParamValue (UInt_t parNo) const
void Clear (const Option_t *="")
void PushBack (const string &name, const string &value, const FairDbFieldType &type)
void SetAggregateNo (Int_t aggNo)
virtual void Fill (FairDbResultSet &rs, const FairDbValidityRec *vrec)
virtual void Store (FairDbOutRowStream &ors, const FairDbValidityRec *vrec) const
Public Member Functions inherited from FairDbTableRow
FairDbTableRow ()
FairDbTableRow (const FairDbTableRow &from)
virtual ~FairDbTableRow ()
virtual Bool_t CanL2Cache () const
FairDbResult * GetOwner () const
virtual UInt_t GetIndex (UInt_t defIndex) const
void SetOwner (FairDbResult *owner)
Private Member Functions
FairDbConfigSet (const FairDbConfigSet &from)
Private Attributes
vector< Param * > fParams
Int_t fAggregateNo
Detailed Description
Definition at line 20 of file FairDbConfigSet.h.
View newest version in sPHENIX GitHub at line 20 of file FairDbConfigSet.h
Constructor & Destructor Documentation
FairDbConfigSet::FairDbConfigSet () inline
Definition at line 26 of file FairDbConfigSet.h.
View newest version in sPHENIX GitHub at line 26 of file FairDbConfigSet.h
Referenced by CreateTableRow().
FairDbConfigSet::~FairDbConfigSet () virtual
Definition at line 23 of file FairDbConfigSet.cxx.
View newest version in sPHENIX GitHub at line 23 of file FairDbConfigSet.cxx
References fParams.
FairDbConfigSet::FairDbConfigSet (const FairDbConfigSet & from) private
Member Function Documentation
void FairDbConfigSet::Clear (const Option_t * = "") inline
Definition at line 41 of file FairDbConfigSet.h.
View newest version in sPHENIX GitHub at line 41 of file FairDbConfigSet.h
References fParams.
Referenced by FairDbConfigStream::operator<<().
virtual FairDbTableRow* FairDbConfigSet::CreateTableRow () const inline virtual
Implements FairDbTableRow.
Definition at line 31 of file FairDbConfigSet.h.
View newest version in sPHENIX GitHub at line 31 of file FairDbConfigSet.h
References FairDbConfigSet().
void FairDbConfigSet::Fill (FairDbResultSet & rs, const FairDbValidityRec * vrec) virtual
Implements FairDbTableRow.
Definition at line 52 of file FairDbConfigSet.cxx.
View newest version in sPHENIX GitHub at line 52 of file FairDbConfigSet.cxx
References FairDbRowStream::CurColFieldType(), FairDbRowStream::CurColName(), FairDbResultSet::CurColValue(), fAggregateNo, fParams, FairDbValidityRec::GetAggregateNo(), FairDbRowStream::HasRowCounter(), FairDbRowStream::IncrementCurCol(), FairDbConfigSet::Param::Name, FairDbRowStream::NumCols(), FairDbConfigSet::Param::Type, and FairDbConfigSet::Param::Value.
Int_t FairDbConfigSet::GetAggregateNo () const inline virtual
Reimplemented from FairDbTableRow.
Definition at line 34 of file FairDbConfigSet.h.
View newest version in sPHENIX GitHub at line 34 of file FairDbConfigSet.h
References fAggregateNo.
Referenced by FairDbConfigStream::FairDbConfigStream().
UInt_t FairDbConfigSet::GetNumParams () const inline
Definition at line 35 of file FairDbConfigSet.h.
View newest version in sPHENIX GitHub at line 35 of file FairDbConfigSet.h
References fParams.
Referenced by GetParamName(), GetParamType(), GetParamValue(), operator<<(), and FairDbConfigStream::operator>>().
string FairDbConfigSet::GetParamName (UInt_t parNo) const
Definition at line 75 of file FairDbConfigSet.cxx.
View newest version in sPHENIX GitHub at line 75 of file FairDbConfigSet.cxx
References fParams, and GetNumParams().
Referenced by operator<<(), and FairDbConfigStream::operator>>().
FairDbFieldType FairDbConfigSet::GetParamType (UInt_t parNo) const
Definition at line 83 of file FairDbConfigSet.cxx.
View newest version in sPHENIX GitHub at line 83 of file FairDbConfigSet.cxx
References fParams, GetNumParams(), and FairDb::kUnknown.
Referenced by operator<<().
string FairDbConfigSet::GetParamValue (UInt_t parNo) const
Definition at line 91 of file FairDbConfigSet.cxx.
View newest version in sPHENIX GitHub at line 91 of file FairDbConfigSet.cxx
References fParams, and GetNumParams().
Referenced by FairDbConfigStream::FairDbConfigStream(), operator<<(), and FairDbConfigStream::operator>>().
void FairDbConfigSet::PushBack (const string & name, const string & value, const FairDbFieldType & type)
Definition at line 100 of file FairDbConfigSet.cxx.
View newest version in sPHENIX GitHub at line 100 of file FairDbConfigSet.cxx
References fParams.
Referenced by FairDbConfigStream::operator<<().
void FairDbConfigSet::SetAggregateNo (Int_t aggNo) inline
Definition at line 45 of file FairDbConfigSet.h.
View newest version in sPHENIX GitHub at line 45 of file FairDbConfigSet.h
References fAggregateNo.
Referenced by FairDbConfigStream::operator<<(), and FairDbConfigStream::Write().
void FairDbConfigSet::Store (FairDbOutRowStream & ors, const FairDbValidityRec * vrec) const virtual
Reimplemented from FairDbTableRow.
Definition at line 109 of file FairDbConfigSet.cxx.
View newest version in sPHENIX GitHub at line 109 of file FairDbConfigSet.cxx
References fParams, and FairDbOutRowStream::Store().
Member Data Documentation
Int_t FairDbConfigSet::fAggregateNo private
Definition at line 78 of file FairDbConfigSet.h.
View newest version in sPHENIX GitHub at line 78 of file FairDbConfigSet.h
Referenced by Fill(), GetAggregateNo(), and SetAggregateNo().
vector<Param*> FairDbConfigSet::fParams private
Definition at line 76 of file FairDbConfigSet.h.
View newest version in sPHENIX GitHub at line 76 of file FairDbConfigSet.h
Referenced by Clear(), Fill(), GetNumParams(), GetParamName(), GetParamType(), GetParamValue(), PushBack(), Store(), and ~FairDbConfigSet().
The documentation for this class was generated from the following files:
EicRoot/blob/master/dbase/dbInterface/FairDbConfigSet.h
EicRoot/blob/master/dbase/dbInterface/FairDbConfigSet.cxx