EIC Software: EicRoot/blob/master/GenfitTools/adapters/PndGenfitAdapters.h File Reference
PndGenfitAdapters.h File Reference
Functions
PndTrackCand * GenfitTrackCand2PndTrackCand (const GFTrackCand *)
GFTrackCand * PndTrackCand2GenfitTrackCand (PndTrackCand *)
PndTrack * GenfitTrack2PndTrack (const GFTrack *)
Function Documentation
PndTrack* GenfitTrack2PndTrack (const GFTrack *)
Definition at line 69 of file PndGenfitAdapters.cxx.
View newest version in sPHENIX GitHub at line 69 of file PndGenfitAdapters.cxx
References GFAbsTrackRep::clone(), Acts::UnitConstants::e, GenfitTrackCand2PndTrackCand(), GFTrack::getCand(), GFTrack::getCardinalRep(), GFTrack::getChiSqu(), GFAbsTrackRep::getFirstCov(), GFAbsTrackRep::getFirstPlane(), GFAbsTrackRep::getFirstState(), GFAbsTrackRep::getLastCov(), GFAbsTrackRep::getLastPlane(), GFAbsTrackRep::getLastState(), GFAbsTrackRep::getMom(), GFTrack::getNDF(), GFDetPlane::getNormal(), GFDetPlane::getO(), GFDetPlane::getU(), GFDetPlane::getV(), PndTrack::SetChi2(), PndTrack::SetFlag(), PndTrack::SetNDF(), and GFException::what().
Referenced by PndGFTrackToPndTrackConvertorTask::Exec(), PndRecoKalmanFit::Fit(), and PndRecoDafFit::Fit().
PndTrackCand* GenfitTrackCand2PndTrackCand (const GFTrackCand *)
Definition at line 19 of file PndGenfitAdapters.cxx.
View newest version in sPHENIX GitHub at line 19 of file PndGenfitAdapters.cxx
References PndTrackCand::AddHit(), GFTrackCand::getChargeSeed(), GFTrackCand::getHit(), GFTrackCand::getMcTrackId(), GFTrackCand::getMomSeed(), GFTrackCand::getNHits(), GFTrackCand::getPosSeed(), PndTrackCand::setMcTrackId(), and PndTrackCand::setTrackSeed().
Referenced by GenfitTrack2PndTrack().
GFTrackCand* PndTrackCand2GenfitTrackCand (PndTrackCand *)
Definition at line 40 of file PndGenfitAdapters.cxx.
View newest version in sPHENIX GitHub at line 40 of file PndGenfitAdapters.cxx
References GFTrackCand::addHit(), PndTrackCand::getChargeSeed(), PndTrackCandHit::GetDetId(), PndTrackCandHit::GetHitId(), PndTrackCand::getMcTrackId(), PndTrackCand::getMomSeed(), PndTrackCand::GetNHits(), PndTrackCand::getPosSeed(), PndTrackCandHit::GetRho(), PndTrackCand::GetSortedHit(), charm_jet_coverage::mom, GFTrackCand::setMcTrackId(), and GFTrackCand::setPosMomSeed().
Referenced by PndRecoDafFit::Fit(), and PndRecoKalmanFit::Fit().