EIC Software: fun4all_eicmacros/blob/master/common/G4_LFHCAL.C File Reference
G4_LFHCAL.C File Reference
#include <GlobalVariables.C>
#include <g4calo/RawTowerDigitizer.h>
#include <g4eiccalos/PHG4LFHcalSubsystem.h>
#include <g4eiccalos/RawTowerBuilderByHitIndexLHCal.h>
#include <g4eval/CaloEvaluator.h>
#include <g4main/PHG4Reco.h>
#include <caloreco/RawClusterBuilderFwd.h>
#include <caloreco/RawClusterBuilderTemplate.h>
#include <caloreco/RawTowerCalibration.h>
#include <fun4all/Fun4AllServer.h>
Namespaces
namespace Enable
namespace G4LFHCAL
namespace G4LFHCAL::SETTING
Macros
#define MACRO_G4LFHCAL_C
Enumerations
enum G4LFHCAL::enu_FHcal_clusterizer { G4LFHCAL::kFHcalGraphClusterizer, G4LFHCAL::kFHcalTemplateClusterizer }
Functions
TString GetMappingFile ()
void LFHCALInit ()
void LFHCALSetup (PHG4Reco *g4Reco)
void LFHCAL_Cells (int verbosity=0)
void LFHCAL_Towers ()
void LFHCAL_Clusters ()
void LFHCAL_Eval (const std::string &outputfile)
Variables
bool Enable::LFHCAL = false
bool Enable::LFHCAL_ABSORBER = false
bool Enable::LFHCAL_CELL = false
bool Enable::LFHCAL_TOWER = false
bool Enable::LFHCAL_CLUSTER = false
bool Enable::LFHCAL_EVAL = false
bool Enable::LFHCAL_OVERLAPCHECK = false
int Enable::LFHCAL_VERBOSITY = 0
double G4LFHCAL::Gz0 = 400.
double G4LFHCAL::Gdz = 100.
double G4LFHCAL::outer_radius = 262.
enu_FHcal_clusterizer G4LFHCAL::FHcal_clusterizer = kFHcalTemplateClusterizer
bool G4LFHCAL::SETTING::FullEtaAcc = false
bool G4LFHCAL::SETTING::HC2x = false
bool G4LFHCAL::SETTING::asymmetric = false
bool G4LFHCAL::SETTING::wDR = false
bool G4LFHCAL::SETTING::FwdSquare = false
bool G4LFHCAL::SETTING::FwdConfig = false
bool G4LFHCAL::SETTING::longer = false
Macro Definition Documentation
#define MACRO_G4LFHCAL_C
Definition at line 2 of file G4_LFHCAL.C.
View newest version in sPHENIX GitHub at line 2 of file G4_LFHCAL.C
Function Documentation
TString GetMappingFile ()
Definition at line 65 of file G4_LFHCAL.C.
View newest version in sPHENIX GitHub at line 65 of file G4_LFHCAL.C
References G4LFHCAL::SETTING::asymmetric, G4LFHCAL::SETTING::FwdConfig, G4LFHCAL::SETTING::FwdSquare, G4LFHCAL::SETTING::HC2x, Enable::IP6, G4LFHCAL::SETTING::longer, and G4LFHCAL::SETTING::wDR.
Referenced by LFHCAL_Towers(), and LFHCALSetup().
void LFHCAL_Cells (int verbosity = 0)
Definition at line 169 of file G4_LFHCAL.C.
View newest version in sPHENIX GitHub at line 169 of file G4_LFHCAL.C
void LFHCAL_Clusters ()
Definition at line 210 of file G4_LFHCAL.C.
View newest version in sPHENIX GitHub at line 210 of file G4_LFHCAL.C
Referenced by Extract_ECCE_gdml(), and Fun4All_G4_FullDetectorModular().
void LFHCAL_Eval (const std::string & outputfile)
Definition at line 216 of file G4_LFHCAL.C.
View newest version in sPHENIX GitHub at line 216 of file G4_LFHCAL.C
References Fun4AllServer::instance(), Enable::LFHCAL_VERBOSITY, max, Fun4AllServer::registerSubsystem(), Enable::VERBOSITY, and Fun4AllBase::Verbosity().
void LFHCAL_Towers ()
Definition at line 174 of file G4_LFHCAL.C.
View newest version in sPHENIX GitHub at line 174 of file G4_LFHCAL.C
References RawTowerDigitizer::Detector(), RawTowerCalibration::Detector(), RawTowerBuilderByHitIndexLHCal::Detector(), RawTowerBuilderByHitIndexLHCal::GeometryTableFile(), GetMappingFile(), Fun4AllServer::instance(), RawTowerDigitizer::kNo_digitization, RawTowerCalibration::kSimple_linear_calibration, Enable::LFHCAL_VERBOSITY, max, Fun4AllServer::registerSubsystem(), RawTowerCalibration::set_calib_algorithm(), RawTowerCalibration::set_calib_const_GeV_ADC(), RawTowerDigitizer::set_digi_algorithm(), RawTowerCalibration::set_pedstal_ADC(), RawTowerBuilderByHitIndexLHCal::set_sim_tower_node_prefix(), Enable::VERBOSITY, and Fun4AllBase::Verbosity().
Referenced by Extract_ECCE_gdml(), and Fun4All_G4_FullDetectorModular().
void LFHCALInit ()
Definition at line 127 of file G4_LFHCAL.C.
View newest version in sPHENIX GitHub at line 127 of file G4_LFHCAL.C
References Acts::UnitConstants::cm, G4LFHCAL::SETTING::FullEtaAcc, G4LFHCAL::Gdz, G4LFHCAL::Gz0, G4LFHCAL::SETTING::HC2x, G4LFHCAL::SETTING::longer, max, BlackHoleGeometry::max_radius, BlackHoleGeometry::max_z, min, BlackHoleGeometry::min_z, and G4LFHCAL::outer_radius.
Referenced by G4Init().
void LFHCALSetup (PHG4Reco * g4Reco)
Use dedicated LFHCAL module
Definition at line 145 of file G4_LFHCAL.C.
View newest version in sPHENIX GitHub at line 145 of file G4_LFHCAL.C
References Enable::ABSORBER, GetMappingFile(), Fun4AllServer::instance(), Enable::LFHCAL_ABSORBER, Enable::LFHCAL_OVERLAPCHECK, Enable::OVERLAPCHECK, PHG4DetectorSubsystem::OverlapCheck(), PHG4Reco::registerSubsystem(), PHG4DetectorSubsystem::SetAbsorberActive(), PHG4DetectorSubsystem::SetActive(), PHG4LFHcalSubsystem::SetDetailed(), PHG4LFHcalSubsystem::SetTowerMappingFile(), and PHG4DetectorSubsystem::SuperDetector().
Referenced by G4Setup().