EIC Software: PHG4DisplayAction Class Reference
PHG4DisplayAction Class Reference abstract
#include <fun4all_coresoftware/blob/master/simulation/g4simulation/g4main/PHG4DisplayAction.h>
Public Types
enum CheckReturnCodes { ABORT = -1, FAILED = 0, ACCEPT = 1 }
Public Member Functions
PHG4DisplayAction ()=delete
constructor
PHG4DisplayAction (const std::string &name)
virtual ~PHG4DisplayAction ()
destructor
virtual void ApplyDisplayAction (G4VPhysicalVolume *physvol)=0
ApplyDisplayAction method.
virtual void SetName (const std::string &name)
virtual std::string GetName () const
virtual void Print (const std::string &="ALL")
Protected Member Functions
int FindVolumes (G4VPhysicalVolume *physvol)
find FindVolume method
virtual int CheckVolume (G4VPhysicalVolume *)
find CheckVolume method
virtual void ApplyVisAttributes (G4VPhysicalVolume *)
ApplyVisAttributes method.
Private Attributes
std::string m_Detector
Detailed Description
Definition at line 10 of file PHG4DisplayAction.h.
View newest version in sPHENIX GitHub at line 10 of file PHG4DisplayAction.h
Member Enumeration Documentation
enum PHG4DisplayAction::CheckReturnCodes
Enumerator:
ABORT
FAILED
ACCEPT
Definition at line 40 of file PHG4DisplayAction.h.
View newest version in sPHENIX GitHub at line 40 of file PHG4DisplayAction.h
Constructor & Destructor Documentation
PHG4DisplayAction::PHG4DisplayAction () delete
constructor
PHG4DisplayAction::PHG4DisplayAction (const std::string & name) inline
Definition at line 17 of file PHG4DisplayAction.h.
View newest version in sPHENIX GitHub at line 17 of file PHG4DisplayAction.h
virtual PHG4DisplayAction::~PHG4DisplayAction () inline virtual
destructor
Definition at line 23 of file PHG4DisplayAction.h.
View newest version in sPHENIX GitHub at line 23 of file PHG4DisplayAction.h
Member Function Documentation
virtual void PHG4DisplayAction::ApplyDisplayAction (G4VPhysicalVolume * physvol) pure virtual
ApplyDisplayAction method.
pure virtual - has to be implemented by derived class creates and set VisAttributes for volumes
Parameters
[in] physvol starting volume in hierarchy (typically world volume)
Implemented in PHG4SpacalDisplayAction, PHG4BackwardHcalDisplayAction, PHG4ForwardEcalDisplayAction, PHG4ForwardHcalDisplayAction, PHG4LFHcalDisplayAction, G4EicDircDisplayAction, PHG4TTLDisplayAction, BeamLineMagnetDisplayAction, PHG4BbcDisplayAction, PHG4BlockDisplayAction, PHG4ConeDisplayAction, PHG4CylinderDisplayAction, PHG4InnerHcalDisplayAction, PHG4OuterHcalDisplayAction, PHG4SectorDisplayAction, PHG4ZDCDisplayAction, PHG4EPDDisplayAction, PHG4InttDisplayAction, PHG4PhenixDisplayAction, PHG4MvtxDisplayAction, PHG4TpcDisplayAction, PHG4TpcEndCapDisplayAction, BeastMagnetDisplayAction, PHG4ForwardDualReadoutDisplayAction, PHG4BarrelEcalDisplayAction, PHG4CrystalCalorimeterDisplayAction, PHG4HybridHomogeneousCalorimeterDisplayAction, G4JLeicBeamLineMagnetDisplayAction, G4JLeicDIRCDisplayAction, G4JLeicVTXDisplayAction, AllSi_Al_support_DisplayAction, AllSiliconTrackerDisplayAction, G4LBLVtxDisplayAction, PHG4RICHDisplayAction, G4JLeicBeamLineMagnetDisplayAction, G4JLeicDIRCDisplayAction, G4JLeicVTXDisplayAction, G4Example03DisplayAction, AllSi_Al_support_DisplayAction, AllSiliconTrackerDisplayAction, and G4LBLVtxDisplayAction.
Referenced by PHG4Reco::ApplyDisplayAction().
virtual void PHG4DisplayAction::ApplyVisAttributes (G4VPhysicalVolume *) inline protected virtual
ApplyVisAttributes method.
Parameters
[in] physvol selected physical volume
Definition at line 64 of file PHG4DisplayAction.h.
View newest version in sPHENIX GitHub at line 64 of file PHG4DisplayAction.h
Referenced by FindVolumes().
virtual int PHG4DisplayAction::CheckVolume (G4VPhysicalVolume *) inline protected virtual
find CheckVolume method
Definition at line 58 of file PHG4DisplayAction.h.
View newest version in sPHENIX GitHub at line 58 of file PHG4DisplayAction.h
Referenced by FindVolumes().
int PHG4DisplayAction::FindVolumes (G4VPhysicalVolume * physvol) protected
find FindVolume method
Definition at line 6 of file PHG4DisplayAction.cc.
View newest version in sPHENIX GitHub at line 6 of file PHG4DisplayAction.cc
References ApplyVisAttributes(), and CheckVolume().
virtual std::string PHG4DisplayAction::GetName (void) const inline virtual
Definition at line 36 of file PHG4DisplayAction.h.
View newest version in sPHENIX GitHub at line 36 of file PHG4DisplayAction.h
References m_Detector.
Referenced by PHG4BbcDisplayAction::ApplyDisplayAction(), PHG4EPDDisplayAction::ApplyDisplayAction(), and PHG4ZDCDisplayAction::ApplyDisplayAction().
virtual void PHG4DisplayAction::Print (const std::string & = "ALL") inline virtual
Definition at line 38 of file PHG4DisplayAction.h.
View newest version in sPHENIX GitHub at line 38 of file PHG4DisplayAction.h
virtual void PHG4DisplayAction::SetName (const std::string & name) inline virtual
Definition at line 34 of file PHG4DisplayAction.h.
View newest version in sPHENIX GitHub at line 34 of file PHG4DisplayAction.h
References m_Detector, and name.
Member Data Documentation
std::string PHG4DisplayAction::m_Detector private
Definition at line 67 of file PHG4DisplayAction.h.
View newest version in sPHENIX GitHub at line 67 of file PHG4DisplayAction.h
Referenced by GetName(), and SetName().
The documentation for this class was generated from the following files:
fun4all_coresoftware/blob/master/simulation/g4simulation/g4main/PHG4DisplayAction.h
fun4all_coresoftware/blob/master/simulation/g4simulation/g4main/PHG4DisplayAction.cc