EIC Software: EicAsciiBoxGenerator Class Reference
EicAsciiBoxGenerator Class Reference
#include <EicRoot/blob/master/eic/base/EicAsciiBoxGenerator.h>
Public Member Functions
EicAsciiBoxGenerator (const char *fileName=0)
~EicAsciiBoxGenerator ()
Bool_t ReadEvent (FairPrimaryGenerator *primGen)
void SetPtRange (double min, double max)
void SetTrackMultiplicityLimit (unsigned mult)
bool IsOver ()
Public Member Functions inherited from EicBoxGenerator
EicBoxGenerator ()
void ResetVars ()
EicBoxGenerator (Int_t pdg, UInt_t mult=1)
void AddPDG (int pdg)
void SetThetaRange (double min, double max, bool uniform=false)
void SetTheta (double theta)
void SetPhiRange (double min, double max)
void SetPhi (double phi)
void SetMomentumRange (double min, double max)
void SetMomentum (double momentum)
Public Member Functions inherited from EicProtoGenerator
EicProtoGenerator (const char *name)
~EicProtoGenerator ()
void SetNaiveVerticalBeamDivergence (double value)
void SetNaiveHorizontalBeamDivergence (double value)
void SetNaiveHorizontalBeamRotation (double value)
void SetVertex (double x, double y, double z=0.0)
double GetVx () const
double GetVy () const
double GetVz () const
void SetVertexSmearing (double sx, double sy, double sz=0.0)
void SetVertexRange (double rx, double ry, double rz=0.0)
double GetVxSmearing () const
double GetVySmearing () const
double GetVzSmearing () const
TVector3 GetSimulatedPrimaryVertex (void)
TVector3 GetModifiedTrack (const TVector3 track)
ClassDef (EicProtoGenerator, 1)
Public Member Functions inherited from FairGenerator
FairGenerator ()
FairGenerator (const char *name, const char *title="FAIR Generator")
virtual ~FairGenerator ()
virtual Bool_t Init ()
ClassDef (FairGenerator, 1)
Private Member Functions
ClassDef (EicAsciiBoxGenerator, 4)
Private Attributes
double mPtMin
double mPtMax
std::fstream * mFstream
unsigned mRemainingTrackCounter
Additional Inherited Members
Public Attributes inherited from EicProtoGenerator
double mVerticalBeamDivergence
double mHorizontalBeamDivergence
double mHorizontalBeamRotation
Double_t mCoord [3]
Double_t mCoordSigma [3]
Double_t mCoordRange [3]
Bool_t mGaussianCoordinateSmearing
Protected Attributes inherited from EicBoxGenerator
Double_t mPmin
Double_t mPmax
Double_t mThetaMin
Double_t mThetaMax
bool mUniformTheta
Double_t mPhiMin
Double_t mPhiMax
UInt_t mMult
Detailed Description
Definition at line 17 of file EicAsciiBoxGenerator.h.
View newest version in sPHENIX GitHub at line 17 of file EicAsciiBoxGenerator.h
Constructor & Destructor Documentation
EicAsciiBoxGenerator::EicAsciiBoxGenerator (const char * fileName = 0)
Definition at line 20 of file EicAsciiBoxGenerator.cxx.
View newest version in sPHENIX GitHub at line 20 of file EicAsciiBoxGenerator.cxx
References mFstream, printf(), and title().
EicAsciiBoxGenerator::~EicAsciiBoxGenerator () inline
Definition at line 21 of file EicAsciiBoxGenerator.h.
View newest version in sPHENIX GitHub at line 21 of file EicAsciiBoxGenerator.h
Member Function Documentation
EicAsciiBoxGenerator::ClassDef (EicAsciiBoxGenerator , 4) private
bool EicAsciiBoxGenerator::IsOver () inline
Definition at line 28 of file EicAsciiBoxGenerator.h.
View newest version in sPHENIX GitHub at line 28 of file EicAsciiBoxGenerator.h
Referenced by ReadEvent().
Bool_t EicAsciiBoxGenerator::ReadEvent (FairPrimaryGenerator * primGen) virtual
Abstract method ReadEvent must be implemented by any derived class. It has to handle the generation of input tracks (reading from input file) and the handing of the tracks to the FairPrimaryGenerator. I t is called from FairMCApplication.
Parameters
pStack The stack
Returns
kTRUE if successful, kFALSE if not
Reimplemented from EicBoxGenerator.
Definition at line 40 of file EicAsciiBoxGenerator.cxx.
View newest version in sPHENIX GitHub at line 40 of file EicAsciiBoxGenerator.cxx
References FairPrimaryGenerator::AddTrack(), EicProtoGenerator::GetModifiedTrack(), IsOver(), EicProtoGenerator::mCoord, EicProtoGenerator::mCoordRange, EicProtoGenerator::mCoordSigma, mFstream, EicProtoGenerator::mGaussianCoordinateSmearing, EicBoxGenerator::mMult, EicBoxGenerator::mPhiMax, EicBoxGenerator::mPhiMin, EicBoxGenerator::mPmax, EicBoxGenerator::mPmin, mPtMax, mPtMin, mRemainingTrackCounter, EicBoxGenerator::mThetaMax, EicBoxGenerator::mThetaMin, p, particle, pdg, and vtx().
void EicAsciiBoxGenerator::SetPtRange (double min, double max) inline
Definition at line 24 of file EicAsciiBoxGenerator.h.
View newest version in sPHENIX GitHub at line 24 of file EicAsciiBoxGenerator.h
References max, min, mPtMax, and mPtMin.
void EicAsciiBoxGenerator::SetTrackMultiplicityLimit (unsigned mult) inline
Definition at line 26 of file EicAsciiBoxGenerator.h.
View newest version in sPHENIX GitHub at line 26 of file EicAsciiBoxGenerator.h
References EicBoxGenerator::mMult.
Member Data Documentation
std::fstream* EicAsciiBoxGenerator::mFstream private
Definition at line 33 of file EicAsciiBoxGenerator.h.
View newest version in sPHENIX GitHub at line 33 of file EicAsciiBoxGenerator.h
Referenced by EicAsciiBoxGenerator(), and ReadEvent().
double EicAsciiBoxGenerator::mPtMax private
Definition at line 28 of file EicAsciiBoxGenerator.h.
View newest version in sPHENIX GitHub at line 28 of file EicAsciiBoxGenerator.h
Referenced by ReadEvent(), and SetPtRange().
double EicAsciiBoxGenerator::mPtMin private
Definition at line 28 of file EicAsciiBoxGenerator.h.
View newest version in sPHENIX GitHub at line 28 of file EicAsciiBoxGenerator.h
Referenced by ReadEvent(), and SetPtRange().
unsigned EicAsciiBoxGenerator::mRemainingTrackCounter private
Definition at line 35 of file EicAsciiBoxGenerator.h.
View newest version in sPHENIX GitHub at line 35 of file EicAsciiBoxGenerator.h
Referenced by ReadEvent().
The documentation for this class was generated from the following files:
EicRoot/blob/master/eic/base/EicAsciiBoxGenerator.h
EicRoot/blob/master/eic/base/EicAsciiBoxGenerator.cxx