EIC Software: CbmMCMatchSelectorTask Class Reference
CbmMCMatchSelectorTask Class Reference
#include <EicRoot/blob/master/cbmbase/CbmMCMatchSelectorTask.h>
Public Member Functions
CbmMCMatchSelectorTask ()
CbmMCMatchSelectorTask (DataType start, DataType stop)
virtual ~CbmMCMatchSelectorTask ()
virtual void SetParContainers ()
virtual InitStatus Init ()
virtual void Exec (Option_t *opt)
virtual void Finish ()
virtual void SetStart (DataType type)
virtual void SetStop (DataType type)
virtual void SetAllWeights (Float_t weight)
virtual void SetWeightStage (Int_t type, Float_t weight)
virtual void SetWeights ()
Public Member Functions inherited from FairTask
FairTask ()
FairTask (const char *name, Int_t iVerbose=1)
virtual ~FairTask ()
void InitTask ()
void ReInitTask ()
void SetParTask ()
virtual void FinishTask ()
virtual void FinishEvent ()
void SetVerbose (Int_t iVerbose)
void SetInputPersistance (Bool_t val)
void CheckInputPersistance (TString branchName)
Private Member Functions
void Register ()
void Reset ()
void ProduceHits ()
CbmMCMatchSelectorTask (const CbmMCMatchSelectorTask &)
CbmMCMatchSelectorTask & operator= (const CbmMCMatchSelectorTask &)
ClassDef (CbmMCMatchSelectorTask, 1)
Private Attributes
CbmMCMatch * fMCMatch
DataType fStart
DataType fStop
std::vector< std::pair
< DataType, Float_t > > fStageWeights
Float_t fCommonWeight
Additional Inherited Members
Protected Member Functions inherited from FairTask
virtual InitStatus ReInit ()
void InitTasks ()
void ReInitTasks ()
void SetParTasks ()
void FinishTasks ()
void FinishEvents ()
Protected Attributes inherited from FairTask
Int_t fVerbose
Int_t fInputPersistance
Indicates if input branch is persistant.
FairLogger * fLogger
Detailed Description
Definition at line 30 of file CbmMCMatchSelectorTask.h.
View newest version in sPHENIX GitHub at line 30 of file CbmMCMatchSelectorTask.h
Constructor & Destructor Documentation
CbmMCMatchSelectorTask::CbmMCMatchSelectorTask ()
Default constructor
Definition at line 18 of file CbmMCMatchSelectorTask.cxx.
View newest version in sPHENIX GitHub at line 18 of file CbmMCMatchSelectorTask.cxx
CbmMCMatchSelectorTask::CbmMCMatchSelectorTask (DataType start, DataType stop)
Definition at line 29 of file CbmMCMatchSelectorTask.cxx.
View newest version in sPHENIX GitHub at line 29 of file CbmMCMatchSelectorTask.cxx
CbmMCMatchSelectorTask::~CbmMCMatchSelectorTask () virtual
Destructor
Definition at line 40 of file CbmMCMatchSelectorTask.cxx.
View newest version in sPHENIX GitHub at line 40 of file CbmMCMatchSelectorTask.cxx
CbmMCMatchSelectorTask::CbmMCMatchSelectorTask (const CbmMCMatchSelectorTask &) private
Member Function Documentation
CbmMCMatchSelectorTask::ClassDef (CbmMCMatchSelectorTask , 1) private
void CbmMCMatchSelectorTask::Exec (Option_t * opt) virtual
Virtual method Exec
Definition at line 80 of file CbmMCMatchSelectorTask.cxx.
View newest version in sPHENIX GitHub at line 80 of file CbmMCMatchSelectorTask.cxx
References fMCMatch, fStart, fStop, CbmMCMatch::GetMCInfo(), and SetWeights().
void CbmMCMatchSelectorTask::Finish () virtual
Action after each event. To be implemented in the derived class
Reimplemented from FairTask.
Definition at line 96 of file CbmMCMatchSelectorTask.cxx.
View newest version in sPHENIX GitHub at line 96 of file CbmMCMatchSelectorTask.cxx
InitStatus CbmMCMatchSelectorTask::Init () virtual
Intialisation at begin of run. To be implemented in the derived class. Success If not kSUCCESS, task will be set inactive.
Reimplemented from FairTask.
Definition at line 45 of file CbmMCMatchSelectorTask.cxx.
View newest version in sPHENIX GitHub at line 45 of file CbmMCMatchSelectorTask.cxx
References fMCMatch, FairRootManager::GetObject(), FairRootManager::Instance(), kFATAL, and kSUCCESS.
CbmMCMatchSelectorTask& CbmMCMatchSelectorTask::operator= (const CbmMCMatchSelectorTask &) private
void CbmMCMatchSelectorTask::ProduceHits () private
void CbmMCMatchSelectorTask::Register () private
void CbmMCMatchSelectorTask::Reset () private
virtual void CbmMCMatchSelectorTask::SetAllWeights (Float_t weight) inline virtual
Definition at line 56 of file CbmMCMatchSelectorTask.h.
View newest version in sPHENIX GitHub at line 56 of file CbmMCMatchSelectorTask.h
References fCommonWeight.
void CbmMCMatchSelectorTask::SetParContainers () virtual
Virtual method Init
Reimplemented from FairTask.
Definition at line 70 of file CbmMCMatchSelectorTask.cxx.
View newest version in sPHENIX GitHub at line 70 of file CbmMCMatchSelectorTask.cxx
virtual void CbmMCMatchSelectorTask::SetStart (DataType type) inline virtual
Definition at line 53 of file CbmMCMatchSelectorTask.h.
View newest version in sPHENIX GitHub at line 53 of file CbmMCMatchSelectorTask.h
References fStart.
virtual void CbmMCMatchSelectorTask::SetStop (DataType type) inline virtual
Definition at line 54 of file CbmMCMatchSelectorTask.h.
View newest version in sPHENIX GitHub at line 54 of file CbmMCMatchSelectorTask.h
References fStop.
void CbmMCMatchSelectorTask::SetWeights () virtual
Definition at line 87 of file CbmMCMatchSelectorTask.cxx.
View newest version in sPHENIX GitHub at line 87 of file CbmMCMatchSelectorTask.cxx
References fCommonWeight, fMCMatch, fStageWeights, CbmMCMatch::GetMCStageType(), CbmMCMatch::SetCommonWeightStages(), and CbmMCStage::SetWeight().
Referenced by Exec().
virtual void CbmMCMatchSelectorTask::SetWeightStage (Int_t type, Float_t weight) inline virtual
Definition at line 57 of file CbmMCMatchSelectorTask.h.
View newest version in sPHENIX GitHub at line 57 of file CbmMCMatchSelectorTask.h
References fStageWeights.
Member Data Documentation
Float_t CbmMCMatchSelectorTask::fCommonWeight private
Definition at line 71 of file CbmMCMatchSelectorTask.h.
View newest version in sPHENIX GitHub at line 71 of file CbmMCMatchSelectorTask.h
Referenced by SetAllWeights(), and SetWeights().
CbmMCMatch* CbmMCMatchSelectorTask::fMCMatch private
Definition at line 66 of file CbmMCMatchSelectorTask.h.
View newest version in sPHENIX GitHub at line 66 of file CbmMCMatchSelectorTask.h
Referenced by Exec(), Init(), and SetWeights().
std::vector<std::pair<DataType, Float_t> > CbmMCMatchSelectorTask::fStageWeights private
Definition at line 70 of file CbmMCMatchSelectorTask.h.
View newest version in sPHENIX GitHub at line 70 of file CbmMCMatchSelectorTask.h
Referenced by SetWeights(), and SetWeightStage().
DataType CbmMCMatchSelectorTask::fStart private
Definition at line 67 of file CbmMCMatchSelectorTask.h.
View newest version in sPHENIX GitHub at line 67 of file CbmMCMatchSelectorTask.h
Referenced by Exec(), and SetStart().
DataType CbmMCMatchSelectorTask::fStop private
Definition at line 68 of file CbmMCMatchSelectorTask.h.
View newest version in sPHENIX GitHub at line 68 of file CbmMCMatchSelectorTask.h
Referenced by Exec(), and SetStop().
The documentation for this class was generated from the following files:
EicRoot/blob/master/cbmbase/CbmMCMatchSelectorTask.h
EicRoot/blob/master/cbmbase/CbmMCMatchSelectorTask.cxx