EIC Software: ValValidate Class Reference
ValValidate Class Reference
#include <EicRoot/blob/master/dbase/dbValidation/ValValidate.h>
Public Member Functions
ValValidate ()
virtual ~ValValidate ()
Bool_t RunAllTests ()
Bool_t TestTimeStamp (void)
Bool_t TestContext (void)
Bool_t TestRange (void)
Bool_t TestFileIO (void)
Protected Member Functions
Bool_t CompareTimeStamps (const char *label, ValTimeStamp &test, ValTimeStamp &std)
Detailed Description
Definition at line 8 of file ValValidate.h.
View newest version in sPHENIX GitHub at line 8 of file ValValidate.h
Constructor & Destructor Documentation
ValValidate::ValValidate ()
ValValidate::~ValValidate () virtual
Definition at line 21 of file ValValidate.cxx.
View newest version in sPHENIX GitHub at line 21 of file ValValidate.cxx
Member Function Documentation
Bool_t ValValidate::CompareTimeStamps (const char * label, ValTimeStamp & test, ValTimeStamp & std) protected
Definition at line 217 of file ValValidate.cxx.
View newest version in sPHENIX GitHub at line 217 of file ValValidate.cxx
References ValTimeStamp::AsString().
Referenced by TestTimeStamp().
Bool_t ValValidate::RunAllTests ()
Definition at line 28 of file ValValidate.cxx.
View newest version in sPHENIX GitHub at line 28 of file ValValidate.cxx
References TestContext(), TestFileIO(), TestRange(), and TestTimeStamp().
Bool_t ValValidate::TestContext (void)
Definition at line 232 of file ValValidate.cxx.
View newest version in sPHENIX GitHub at line 232 of file ValValidate.cxx
References ValContext::AsString(), and p.
Referenced by RunAllTests().
Bool_t ValValidate::TestFileIO (void)
Definition at line 312 of file ValValidate.cxx.
View newest version in sPHENIX GitHub at line 312 of file ValValidate.cxx
Referenced by RunAllTests().
Bool_t ValValidate::TestRange (void)
Definition at line 292 of file ValValidate.cxx.
View newest version in sPHENIX GitHub at line 292 of file ValValidate.cxx
References ValRange::Print().
Referenced by RunAllTests().
Bool_t ValValidate::TestTimeStamp (void)
Definition at line 55 of file ValValidate.cxx.
View newest version in sPHENIX GitHub at line 55 of file ValValidate.cxx
References Acts::arbitrary, ValTimeStamp::AsString(), CompareTimeStamps(), ValTimeStamp::GetDate(), ValTimeStamp::GetTime(), ValTimeStamp::GetTimeSpec(), ValTimeStamp::GetZoneOffset(), min, ValTimeStamp::Print(), and Acts::Test::time.
Referenced by RunAllTests().
The documentation for this class was generated from the following files:
EicRoot/blob/master/dbase/dbValidation/ValValidate.h
EicRoot/blob/master/dbase/dbValidation/ValValidate.cxx