EIC Software: EicToyModel/blob/master/scripts/EIC-IR1-XX-v00.C File Reference
EIC-IR1-XX-v00.C File Reference
Functions
eic ip (0.0 *etm::cm) -> width(1200) ->AddEtaLine(0.0) ->SetName("example")
eic acceptance (-4.2,-1.0, 1.1, 4.2)
eic SetAzimuthalSegmentation (12)
eic DefineVacuumChamber (new vc2020_03_20())
vtx offset (0.0 *etm::cm)
vtx add ("Si Tracker", 20 *etm::cm)
mid offset (20 *etm::cm)
mid add ("TRACKER", 75 *etm::cm)
mid add ("Cherenkov", 25 *etm::cm)
mid add ("EmCal", 30 *etm::cm)
mid add ("Cryostat", 40 *etm::cm)
mid add ("HCal", 120 *etm::cm) -> brick()
fwd offset (130 *etm::cm)
fwd add ("TRACKER", 15 *etm::cm) -> brick()
fwd marker ()
fwd add ("HM RICH", 100 *etm::cm) -> trim(0.8, 1.0)
for ()
eic vtx () -> get("Si Tracker") ->stretch(eic->fwd() ->get("HM RICH"))
eic mid () -> get("TRACKER") ->stretch(eic->bck() ->get("TRACKER"))
eic fwd () -> get("HCal") ->stretch(eic->mid() ->get("HCal"), 80 *etm::cm)
eic bck () -> get("HCal") ->stretch(eic->mid() ->get("HCal"), 80 *etm::cm)
eic ApplyStandardTrimming ()
eic hdraw ()
eic write ()
Function Documentation
eic acceptance (-4. 2, -1. 0, 1. 1, 4. 2)
mid add ("Si Tracker" , 20 *etm::cm)
mid add ("TRACKER" , 75 *etm::cm)
mid add ("Cherenkov" , 25 *etm::cm)
mid add ("EmCal" , 30 *etm::cm)
mid add ("Cryostat" , 40 *etm::cm)
mid add ("HCal" , 120 *etm::cm) -> brick()
fwd add ("TRACKER" , 15 *etm::cm) -> brick()
fwd add ("HM RICH" , 100 *etm::cm) -> trim(0.8, 1.0)
eic ApplyStandardTrimming ()
eic bck () -> get("HCal") ->stretch(eic->mid() ->get("HCal"), 80 *etm::cm)
eic DefineVacuumChamber (new vc2020_03_20())
for ()
Definition at line 38 of file EIC-IR1-XX-v00.C.
View newest version in sPHENIX GitHub at line 38 of file EIC-IR1-XX-v00.C
eic fwd () -> get("HCal") ->stretch(eic->mid() ->get("HCal"), 80 *etm::cm)
Referenced by BasicDetectorConstruction::Construct(), and CellularAutomaton_v1::set_propagate_forward().
eic hdraw ()
eic ip (0.0 *etm::cm) -> width(1200) ->AddEtaLine(0.0) ->SetName("example")
fwd marker ()
Referenced by analysis_resolution(), EtmAzimuthalScan::DoIt(), EicToyModel::DrawFlatFieldLines(), EicToyModel::DrawMarkers(), FairDbBinaryFile::operator<<(), FairDbBinaryFile::operator>>(), tetgenmesh::outedges(), tetgenmesh::outfaces(), tetgenmesh::outmesh2medit(), tetgenmesh::outnodes(), tetgenmesh::outsmesh(), tetgenmesh::outsubfaces(), tetgenmesh::outsubsegments(), fileEventiterator::read_next_buffer(), and tetgenmesh::reconstructmesh().
eic mid () -> get("TRACKER") ->stretch(eic->bck() ->get("TRACKER"))
vtx offset (0.0 *etm::cm)
mid offset (20 *etm::cm)
fwd offset (130 *etm::cm)
eic SetAzimuthalSegmentation (12)
eic vtx () -> get("Si Tracker") ->stretch(eic->fwd() ->get("HM RICH"))
Referenced by EicStlFactory::_ConstructGeometry(), Acts::AdaptiveMultiVertexFinder< vfitter_t, sfinder_t >::addCompatibleTracksToVertex(), PHG4TruthTrackingAction::AddParticle(), EicStlMediaGroup::AllocateEdges(), Acts::Test::BOOST_AUTO_TEST_CASE(), Acts::GenericCuboidVolumeBounds::boundingBox(), Acts::TrapezoidVolumeBounds::boundingBox(), EtmDetector::Build(), EicStlFacet::Calculate(), EicStlMediaGroup::CalculateFacets(), Acts::AdaptiveMultiVertexFinder< vfitter_t, sfinder_t >::canPrepareVertexForFit(), Acts::AdaptiveMultiVertexFinder< vfitter_t, sfinder_t >::canRecoverFromNoCompatibleTracks(), Acts::AdaptiveMultiVertexFitter< input_track_t, linearizer_t >::checkSmallShift(), Acts::AdaptiveMultiVertexFinder< vfitter_t, sfinder_t >::checkVertexAndCompatibleTracks(), CreateTetrahedron(), Acts::AdaptiveMultiVertexFinder< vfitter_t, sfinder_t >::deleteLastVertex(), Acts::TGeoSurfaceConverter::discComponents(), Acts::AdaptiveMultiVertexFitter< input_track_t, linearizer_t >::doVertexSmoothing(), Acts::Test::draw_surfaces(), Acts::Test::SurfaceArrayFixture::draw_surfaces(), EtmPolygonGroup::DrawPolygon(), ActsExamples::IterativeVertexFinderAlgorithm::execute(), ActsExamples::AdaptiveMultiVertexFinderAlgorithm::execute(), Acts::PlyVisualization3D< T >::face(), Acts::ObjVisualization3D< T >::face(), B0TrackFastSimEval::fill_track_tree(), PHG4TrackFastSimEval::fill_track_tree(), TrackFastSimEval::fill_track_tree(), B0TrackFastSimEval::fill_vertex_tree(), PHG4TrackFastSimEval::fill_vertex_tree(), TrackFastSimEval::fill_vertex_tree(), ActsEvaluator::fillG4Particle(), CaloEvaluator::fillOutputNtuples(), SvtxEvaluator::fillOutputNtuples(), EventEvaluator::fillOutputNtuples(), EventEvaluatorEIC::fillOutputNtuples(), TowerJetInput::get_input(), ClusterJetInput::get_input(), BaseTruthEval::get_vertex(), AnaTutorial::getEMCalClusters(), Acts::AdaptiveMultiVertexFinder< vfitter_t, sfinder_t >::getIPSignificance(), EicProtoGenerator::GetSimulatedPrimaryVertex(), Acts::AdaptiveMultiVertexFinder< vfitter_t, sfinder_t >::getVertexOutputList(), SvtxClusterEval::gtrackid_and_layer_by_nhit(), Acts::AdaptiveMultiVertexFitter< input_track_t, linearizer_t >::isAlreadyInList(), Acts::AdaptiveMultiVertexFinder< vfitter_t, sfinder_t >::keepNewVertex(), main(), EicStlMediaGroup::MergeDegenerateVertices(), EicStlFactory::PreAllocateFacet(), Acts::AdaptiveMultiVertexFitter< input_track_t, linearizer_t >::prepareVertexForFit(), CaloEvaluator::printOutputInfo(), PHG4InEventReadBack::process_event(), CaloCalibEmc_Pi0::process_event(), PHG4TrackFastSim::process_event(), B0TrackFastSim::process_event(), PHG4TruthEventAction::ProcessShowers(), ActsExamples::HepMC3Vertex::processVertex(), pyevnt(), pyevnw(), EicAsciiBoxGenerator::ReadEvent(), EicBoxGenerator::ReadEvent(), EicEventGenerator::ReadEvent(), Acts::AdaptiveMultiVertexFinder< vfitter_t, sfinder_t >::removeCompatibleTracksFromSeedTracks(), Acts::AdaptiveMultiVertexFinder< vfitter_t, sfinder_t >::removeTrackIfIncompatible(), PHG4ParticleGeneratorBase::ReuseExistingVertex(), Acts::AdaptiveMultiVertexFitter< input_track_t, linearizer_t >::setWeightsAndUpdate(), EicStlMediaGroup::SplitIntoAssemblies(), Acts::ConvexPolygonBoundsBase::toStream(), SensitiveVolume::TrackToHitDistance(), Acts::AxisAlignedBoundingBox< entity_t, value_t, DIM >::transformVertices(), Acts::KalmanVertexTrackUpdater::update(), Acts::KalmanVertexUpdater::detail::update(), Acts::KalmanVertexUpdater::updateVertexWithTrack(), Acts::ConvexPolygonBoundsBase::values(), PHG4TrackFastSim::VertexMeasurement(), B0TrackFastSim::VertexMeasurement(), vtx_builder(), and eventFileWriter::writeEvent().
eic write ()