EIC Software: erhic::EventDis Class Reference
erhic::EventDis Class Reference abstract
#include <eic-smear/blob/master/include/eicsmear/erhic/EventDis.h>
Public Member Functions
virtual ~EventDis ()
EventDis ()
EventDis (const EventDis &)
EventDis & operator= (const EventDis &)
virtual Double_t GetX () const
virtual Double_t GetQ2 () const
virtual Double_t GetY () const
virtual Double_t GetYPlus () const
virtual Double_t GetW2 () const
virtual Double_t GetNu () const
virtual double GetXDoubleAngle () const
virtual double GetQ2DoubleAngle () const
virtual double GetYDoubleAngle () const
virtual double GetW2DoubleAngle () const
virtual double GetXJacquetBlondel () const
virtual double GetQ2JacquetBlondel () const
virtual double GetYJacquetBlondel () const
virtual double GetW2JacquetBlondel () const
virtual void SetLeptonKinematics (const DisKinematics &)
virtual void SetJacquetBlondelKinematics (const DisKinematics &)
virtual void SetDoubleAngleKinematics (const DisKinematics &)
virtual const VirtualParticle * BeamLepton () const =0
virtual const VirtualParticle * BeamHadron () const =0
virtual const VirtualParticle * ExchangeBoson () const =0
virtual const VirtualParticle * ScatteredLepton () const =0
virtual void CopyKinematics (const EventDis &)
Public Member Functions inherited from erhic::VirtualEvent
virtual ~VirtualEvent ()
virtual const VirtualParticle * GetTrack (UInt_t) const =0
virtual VirtualParticle * GetTrack (UInt_t)=0
virtual UInt_t GetNTracks () const =0
virtual void HadronicFinalState (ParticlePtrList &) const
Public Attributes
Double32_t x
Bjorken scaling variable.
Double32_t QSquared
Q2 calculated from scattered electron.
Double32_t y
Inelasticity.
Double32_t WSquared
Invariant mass of the hadronic system.
Double32_t nu
Energy transfer from the electron.
Double32_t yJB
y calculated via the Jacquet-Blondel method
Double32_t QSquaredJB
Q2 calculated via the Jacquet-Blondel method.
Double32_t xJB
x calculated via the Jacquet-Blondel method
Double32_t WSquaredJB
W2 calculated via the Jacquet-Blondel method.
Double32_t yDA
y calculated via the double-angle method
Double32_t QSquaredDA
Q2 calculated via the double-angle method.
Double32_t xDA
x calculated via the double-angle method
Double32_t WSquaredDA
W2 calculated via the double-angle method.
Additional Inherited Members
Public Types inherited from erhic::VirtualEvent
typedef std::vector< const
erhic::VirtualParticle * > ParticlePtrList
Detailed Description
A deeply inelastic scattering event. Stores kinematics computed by different methods:
Using the scattered electron
Jacquet-Blondel method (uses hadrons)
Double-angle method (uses both hadrons and the scattered electron)
This is an abstract class, as it does not implement track methods inherited from VirtualEvent. The user must implement the appropriate methods for their track type in an inheriting class.
Definition at line 37 of file EventDis.h.
View newest version in sPHENIX GitHub at line 37 of file EventDis.h
Constructor & Destructor Documentation
erhic::EventDis::~EventDis () virtual
Destructor.
Definition at line 16 of file EventDis.cxx.
View newest version in sPHENIX GitHub at line 16 of file EventDis.cxx
erhic::EventDis::EventDis ()
Default constructor.
Definition at line 24 of file EventDis.cxx.
View newest version in sPHENIX GitHub at line 24 of file EventDis.cxx
erhic::EventDis::EventDis (const EventDis & that)
Constructor copying another event's kinematics.
Definition at line 40 of file EventDis.cxx.
View newest version in sPHENIX GitHub at line 40 of file EventDis.cxx
References CopyKinematics().
Member Function Documentation
virtual const VirtualParticle* erhic::EventDis::BeamHadron () const pure virtual
Returns a pointer to the incident hadron beam particle. Returns NULL if the particle cannot be located in the event. IMPORTANT - DO NOT DELETE THE POINTER OR BAD THINGS WILL HAPPEN!
Implemented in Smear::Event, erhic::EventMC, EicRcEvent, EventEicMC, and EventProMC.
Referenced by erhic::JacquetBlondelComputer::Calculate(), erhic::DoubleAngleComputer::Calculate(), erhic::JacquetBlondelComputer::ComputeQSquared(), erhic::JacquetBlondelComputer::ComputeX(), erhic::DoubleAngleComputer::ComputeX(), erhic::JacquetBlondelComputer::ComputeY(), Smear::EventDisFactory::Create(), and erhic::LeptonKinematicsComputer::LeptonKinematicsComputer().
virtual const VirtualParticle* erhic::EventDis::BeamLepton () const pure virtual
Returns a pointer to the incident lepton beam particle. Returns NULL if the particle cannot be located in the event. IMPORTANT - DO NOT DELETE THE POINTER OR BAD THINGS WILL HAPPEN!
Implemented in Smear::Event, erhic::EventMC, EicRcEvent, EventEicMC, and EventProMC.
Referenced by erhic::DoubleAngleComputer::ComputeQSquared(), erhic::JacquetBlondelComputer::ComputeX(), erhic::DoubleAngleComputer::ComputeX(), erhic::JacquetBlondelComputer::ComputeY(), Smear::EventDisFactory::Create(), and erhic::LeptonKinematicsComputer::LeptonKinematicsComputer().
void erhic::EventDis::CopyKinematics (const EventDis & that) virtual
Copy the kinematics from another event to this event.
Definition at line 52 of file EventDis.cxx.
View newest version in sPHENIX GitHub at line 52 of file EventDis.cxx
References nu, QSquared, QSquaredDA, QSquaredJB, SetDoubleAngleKinematics(), SetJacquetBlondelKinematics(), SetLeptonKinematics(), WSquared, WSquaredDA, WSquaredJB, x, xDA, xJB, y, yDA, and yJB.
Referenced by EventDis(), and operator=().
virtual const VirtualParticle* erhic::EventDis::ExchangeBoson () const pure virtual
Returns a pointer to the exchanged boson. Returns NULL if the particle cannot be located in the event. IMPORTANT - DO NOT DELETE THE POINTER OR BAD THINGS WILL HAPPEN!
Implemented in Smear::Event, erhic::EventMC, EicRcEvent, EventEicMC, EventProMC, erhic::EventSartre, erhic::EventDjangoh, erhic::EventPepsi, and erhic::EventRapgap.
Referenced by erhic::LeptonKinematicsComputer::LeptonKinematicsComputer().
Double_t erhic::EventDis::GetNu () const inline virtual
Returns the exchange boson energy in the beam hadron rest frame. nu = q.p/M
Definition at line 202 of file EventDis.h.
View newest version in sPHENIX GitHub at line 202 of file EventDis.h
References nu.
Referenced by erhic::ParticleMCbase::Get4VectorInHadronBosonFrame().
Double_t erhic::EventDis::GetQ2 () const inline virtual
Returns the four-momentum transfer (exchange boson mass) Q2. Q2 = 2EE(1+cos(theta)) = (e-e)2
Definition at line 206 of file EventDis.h.
View newest version in sPHENIX GitHub at line 206 of file EventDis.h
References QSquared.
Referenced by FillEventQA(), main(), Smear::Event::Print(), ReadEICFiles::process_event(), and read().
double erhic::EventDis::GetQ2DoubleAngle () const inline virtual
Returns Q-squared computed via the double-angle method.
Definition at line 226 of file EventDis.h.
View newest version in sPHENIX GitHub at line 226 of file EventDis.h
References QSquaredDA.
Referenced by FillEventQA(), and main().
double erhic::EventDis::GetQ2JacquetBlondel () const inline virtual
Returns Q-squared computed via the Jacquet-Blondel method.
Definition at line 242 of file EventDis.h.
View newest version in sPHENIX GitHub at line 242 of file EventDis.h
References QSquaredJB.
Referenced by FillEventQA().
Double_t erhic::EventDis::GetW2 () const inline virtual
Returns the invariant mass of the hadronic final state. W2 = M2 + Q2(1-x)/x
Definition at line 210 of file EventDis.h.
View newest version in sPHENIX GitHub at line 210 of file EventDis.h
References WSquared.
Referenced by erhic::ParticleMCbase::ComputeEventDependentQuantities().
double erhic::EventDis::GetW2DoubleAngle () const inline virtual
Returns W-squared computed via the double-angle method.
Definition at line 234 of file EventDis.h.
View newest version in sPHENIX GitHub at line 234 of file EventDis.h
References WSquaredDA.
double erhic::EventDis::GetW2JacquetBlondel () const inline virtual
Returns W-squared computed via the Jacquet-Blondel method.
Definition at line 250 of file EventDis.h.
View newest version in sPHENIX GitHub at line 250 of file EventDis.h
References WSquaredJB.
Double_t erhic::EventDis::GetX () const inline virtual
Returns Bjorken-x of the event. xB = Q2/(2p.q)
Definition at line 198 of file EventDis.h.
View newest version in sPHENIX GitHub at line 198 of file EventDis.h
References x.
Referenced by FillEventQA(), main(), Smear::Event::Print(), ReadEICFiles::process_event(), and read().
double erhic::EventDis::GetXDoubleAngle () const inline virtual
Returns Bjorken x computed via the double-angle method.
Definition at line 222 of file EventDis.h.
View newest version in sPHENIX GitHub at line 222 of file EventDis.h
References xDA.
Referenced by FillEventQA(), and main().
double erhic::EventDis::GetXJacquetBlondel () const inline virtual
Returns Bjorken x computed via the Jacquet-Blondel method.
Definition at line 238 of file EventDis.h.
View newest version in sPHENIX GitHub at line 238 of file EventDis.h
References xJB.
Referenced by FillEventQA().
Double_t erhic::EventDis::GetY () const inline virtual
Returns the event inelasticity. y = (p.q)/(p.e)
Definition at line 214 of file EventDis.h.
View newest version in sPHENIX GitHub at line 214 of file EventDis.h
References y.
Referenced by FillEventQA(), GetYPlus(), main(), and Smear::Event::Print().
double erhic::EventDis::GetYDoubleAngle () const inline virtual
Returns inelasticity computed via the double-angle method.
Definition at line 230 of file EventDis.h.
View newest version in sPHENIX GitHub at line 230 of file EventDis.h
References yDA.
Referenced by FillEventQA(), and main().
double erhic::EventDis::GetYJacquetBlondel () const inline virtual
Returns inelasticity computed via the Jacquet-Blondel method.
Definition at line 246 of file EventDis.h.
View newest version in sPHENIX GitHub at line 246 of file EventDis.h
References yJB.
Referenced by FillEventQA().
Double_t erhic::EventDis::GetYPlus () const inline virtual
Returns Y+ = y2 / (1 + (1-y)2)
Definition at line 218 of file EventDis.h.
View newest version in sPHENIX GitHub at line 218 of file EventDis.h
References GetY().
EventDis & erhic::EventDis::operator= (const EventDis & that)
Assign another event's kinematics to this EventDis.
Definition at line 45 of file EventDis.cxx.
View newest version in sPHENIX GitHub at line 45 of file EventDis.cxx
References CopyKinematics().
Referenced by erhic::hadronic::EventPythiaPP::operator=().
virtual const VirtualParticle* erhic::EventDis::ScatteredLepton () const pure virtual
Returns a pointer to the lepton beam particle after scattering. Returns NULL if the particle cannot be located in the event. IMPORTANT - DO NOT DELETE THE POINTER OR BAD THINGS WILL HAPPEN!
Implemented in erhic::EventPythia, Smear::Event, erhic::EventMC, EicRcEvent, EventEicMC, erhic::EventDjangoh, EventProMC, erhic::EventPepsi, erhic::EventSartre, erhic::EventDEMP, erhic::EventSimple, and erhic::EventRapgap.
Referenced by erhic::DoubleAngleComputer::ComputeQSquared(), erhic::DoubleAngleComputer::ComputeY(), Smear::EventDisFactory::Create(), and erhic::LeptonKinematicsComputer::LeptonKinematicsComputer().
void erhic::EventDis::SetDoubleAngleKinematics (const DisKinematics & kin) virtual
Set the kinematics computed from the double-angle method.
Definition at line 76 of file EventDis.cxx.
View newest version in sPHENIX GitHub at line 76 of file EventDis.cxx
References erhic::DisKinematics::mQ2, erhic::DisKinematics::mW2, erhic::DisKinematics::mX, erhic::DisKinematics::mY, QSquaredDA, WSquaredDA, xDA, and yDA.
Referenced by CopyKinematics(), and Smear::Detector::FillEventKinematics().
void erhic::EventDis::SetJacquetBlondelKinematics (const DisKinematics & kin) virtual
Set the kinematics computed from the Jacquet-Blondel method.
Definition at line 69 of file EventDis.cxx.
View newest version in sPHENIX GitHub at line 69 of file EventDis.cxx
References erhic::DisKinematics::mQ2, erhic::DisKinematics::mW2, erhic::DisKinematics::mX, erhic::DisKinematics::mY, QSquaredJB, WSquaredJB, xJB, and yJB.
Referenced by CopyKinematics(), and Smear::Detector::FillEventKinematics().
void erhic::EventDis::SetLeptonKinematics (const DisKinematics & kin) virtual
Set the kinematics computed from the scattered lepton.
Definition at line 61 of file EventDis.cxx.
View newest version in sPHENIX GitHub at line 61 of file EventDis.cxx
References erhic::DisKinematics::mNu, erhic::DisKinematics::mQ2, erhic::DisKinematics::mW2, erhic::DisKinematics::mX, erhic::DisKinematics::mY, nu, QSquared, WSquared, x, and y.
Referenced by CopyKinematics(), and Smear::Detector::FillEventKinematics().
Member Data Documentation
Double32_t erhic::EventDis::nu
Energy transfer from the electron.
Definition at line 185 of file EventDis.h.
View newest version in sPHENIX GitHub at line 185 of file EventDis.h
Referenced by CopyKinematics(), GetNu(), erhic::EventMC::Reset(), SetLeptonKinematics(), and Smear::Event::SetNu().
Double32_t erhic::EventDis::QSquared
Q2 calculated from scattered electron.
Definition at line 182 of file EventDis.h.
View newest version in sPHENIX GitHub at line 182 of file EventDis.h
Referenced by CopyKinematics(), GetQ2(), erhic::EventMC::Reset(), SetLeptonKinematics(), and Smear::Event::SetQ2().
Double32_t erhic::EventDis::QSquaredDA
Q2 calculated via the double-angle method.
Definition at line 191 of file EventDis.h.
View newest version in sPHENIX GitHub at line 191 of file EventDis.h
Referenced by CopyKinematics(), GetQ2DoubleAngle(), and SetDoubleAngleKinematics().
Double32_t erhic::EventDis::QSquaredJB
Q2 calculated via the Jacquet-Blondel method.
Definition at line 187 of file EventDis.h.
View newest version in sPHENIX GitHub at line 187 of file EventDis.h
Referenced by CopyKinematics(), GetQ2JacquetBlondel(), and SetJacquetBlondelKinematics().
Double32_t erhic::EventDis::WSquared
Invariant mass of the hadronic system.
Definition at line 184 of file EventDis.h.
View newest version in sPHENIX GitHub at line 184 of file EventDis.h
Referenced by CopyKinematics(), GetW2(), erhic::EventMC::Reset(), SetLeptonKinematics(), and Smear::Event::SetW2().
Double32_t erhic::EventDis::WSquaredDA
W2 calculated via the double-angle method.
Definition at line 193 of file EventDis.h.
View newest version in sPHENIX GitHub at line 193 of file EventDis.h
Referenced by CopyKinematics(), GetW2DoubleAngle(), and SetDoubleAngleKinematics().
Double32_t erhic::EventDis::WSquaredJB
W2 calculated via the Jacquet-Blondel method.
Definition at line 189 of file EventDis.h.
View newest version in sPHENIX GitHub at line 189 of file EventDis.h
Referenced by CopyKinematics(), GetW2JacquetBlondel(), and SetJacquetBlondelKinematics().
Double32_t erhic::EventDis::x
Bjorken scaling variable.
Definition at line 181 of file EventDis.h.
View newest version in sPHENIX GitHub at line 181 of file EventDis.h
Referenced by eicpy.qaplots.LogAxis::apply(), CopyKinematics(), GetX(), eicpy.qaplots.LogAxis::rebin(), erhic::EventMC::Reset(), SetLeptonKinematics(), and Smear::Event::SetX().
Double32_t erhic::EventDis::xDA
x calculated via the double-angle method
Definition at line 192 of file EventDis.h.
View newest version in sPHENIX GitHub at line 192 of file EventDis.h
Referenced by CopyKinematics(), GetXDoubleAngle(), and SetDoubleAngleKinematics().
Double32_t erhic::EventDis::xJB
x calculated via the Jacquet-Blondel method
Definition at line 188 of file EventDis.h.
View newest version in sPHENIX GitHub at line 188 of file EventDis.h
Referenced by CopyKinematics(), GetXJacquetBlondel(), and SetJacquetBlondelKinematics().
Double32_t erhic::EventDis::y
Inelasticity.
Definition at line 183 of file EventDis.h.
View newest version in sPHENIX GitHub at line 183 of file EventDis.h
Referenced by eicpy.qaplots.LogAxis::apply(), CopyKinematics(), GetY(), erhic::EventRapgap::Parse(), eicpy.qaplots.LogAxis::rebin(), erhic::EventMC::Reset(), SetLeptonKinematics(), and Smear::Event::SetY().
Double32_t erhic::EventDis::yDA
y calculated via the double-angle method
Definition at line 190 of file EventDis.h.
View newest version in sPHENIX GitHub at line 190 of file EventDis.h
Referenced by CopyKinematics(), GetYDoubleAngle(), and SetDoubleAngleKinematics().
Double32_t erhic::EventDis::yJB
y calculated via the Jacquet-Blondel method
Definition at line 186 of file EventDis.h.
View newest version in sPHENIX GitHub at line 186 of file EventDis.h
Referenced by CopyKinematics(), GetYJacquetBlondel(), and SetJacquetBlondelKinematics().
The documentation for this class was generated from the following files:
eic-smear/blob/master/include/eicsmear/erhic/EventDis.h
eic-smear/blob/master/src/erhic/EventDis.cxx