EIC Software: RawTowerZDC Class Reference
RawTowerZDC Class Reference
#include <fun4all_eicdetectors/blob/master/reconstruction/eiczdcbase/RawTowerZDC.h>
Public Types
enum PROPERTY { prop_scint_gammas = 1, prop_cerenkov_gammas = 2, prop_MAX_NUMBER = UCHAR_MAX }
typedef unsigned long long CellKeyType
key type for cell map which should be consistent with CellKeyType
typedef std::map< CellKeyType,
float > CellMap
typedef CellMap::iterator CellIterator
typedef CellMap::const_iterator CellConstIterator
typedef std::pair
< CellIterator, CellIterator > CellRange
typedef std::pair
< CellConstIterator,
CellConstIterator > CellConstRange
typedef std::map< int, float > ShowerMap
typedef ShowerMap::iterator ShowerIterator
typedef ShowerMap::const_iterator ShowerConstIterator
typedef std::pair
< ShowerIterator,
ShowerIterator > ShowerRange
typedef std::pair
< ShowerConstIterator,
ShowerConstIterator > ShowerConstRange
Public Member Functions
~RawTowerZDC () override
void Reset () override
Clear Event.
int isValid () const override
isValid returns non zero if object contains vailid data
void identify (std::ostream &=std::cout) const override
virtual void set_id (RawTowerZDCDefs::keytype)
virtual RawTowerZDCDefs::keytype get_id () const
virtual void set_key (RawTowerZDCDefs::keytype id)
virtual RawTowerZDCDefs::keytype get_key () const
virtual int get_bineta () const
virtual int get_bintheta () const
virtual int get_binphi () const
virtual int get_binl () const
return layer ID assigned to tower
virtual int get_column () const
virtual int get_row () const
virtual double get_energy () const
energy assigned to the tower. Depending on stage of process and DST node name, it could be energy deposition, light yield or calibrated energies
virtual void set_energy (const double)
energy assigned to the tower. Depending on stage of process and DST node name, it could be energy deposition, light yield or calibrated energies
virtual double get_scint_gammas () const
energy assigned to the tower. Depending on stage of process and DST node name, it could be energy deposition, light yield or calibrated energies
virtual void set_scint_gammas (const double)
scint_gammas assigned to the tower. Depending on stage of process and DST node name, it could be scint_gammas deposition, light yield or calibrated energies
virtual double get_cerenkov_gammas () const
energy assigned to the tower. Depending on stage of process and DST node name, it could be energy deposition, light yield or calibrated energies
virtual void set_cerenkov_gammas (const double)
cerenkov_gammas assigned to the tower. Depending on stage of process and DST node name, it could be cerenkov_gammas deposition, light yield or calibrated energies
virtual float get_time () const
Time stamp assigned to the tower. Depending on the tower maker, it could be rise time or peak time.
virtual void set_time (const float)
Time stamp assigned to the tower. Depending on the tower maker, it could be rise time or peak time.
virtual bool empty_g4cells () const
virtual size_t size_g4cells () const
virtual CellConstRange get_g4cells () const
virtual CellIterator find_g4cell (CellKeyType id)
virtual CellConstIterator find_g4cell (CellKeyType id) const
virtual void add_ecell (const CellKeyType, const float)
virtual void clear_g4cells ()
virtual bool empty_g4showers () const
virtual size_t size_g4showers () const
virtual ShowerConstRange get_g4showers () const
virtual ShowerIterator find_g4shower (int)
virtual ShowerConstIterator find_g4shower (int) const
virtual void add_eshower (const int, const float)
virtual void clear_g4showers ()
virtual bool has_property (const PROPERTY) const
virtual double get_property (const PROPERTY) const
virtual void set_property (const PROPERTY, const double)
Public Member Functions inherited from PHObject
PHObject ()
ctor
~PHObject () override
dtor
virtual PHObject * CloneMe () const
Virtual copy constructor.
virtual PHObject * clone () const final
PHObject * Clone (const char *newname="") const final
void Copy (TObject &object) const final
virtual int isValid (const float) const
virtual int isValid (const double) const
virtual int isValid (const int) const
virtual int isValid (const unsigned int) const
virtual int isImplemented (const float f) const
virtual int isImplemented (const double f) const
virtual int isImplemented (const int i) const
virtual int isImplemented (const unsigned int i) const
virtual int Integrate () const
virtual int Integrate (PHObject *)
virtual void CopyFrom (const PHObject *obj)
Static Public Member Functions
static const std::string get_property_info (PROPERTY prop_id)
Protected Member Functions
RawTowerZDC ()
virtual unsigned int get_property_nocheck (const PROPERTY) const
virtual void set_property_nocheck (const PROPERTY, const unsigned int)
Detailed Description
Definition at line 17 of file RawTowerZDC.h.
View newest version in sPHENIX GitHub at line 17 of file RawTowerZDC.h
Member Typedef Documentation
typedef CellMap::const_iterator RawTowerZDC::CellConstIterator
Definition at line 25 of file RawTowerZDC.h.
View newest version in sPHENIX GitHub at line 25 of file RawTowerZDC.h
typedef std::pair<CellConstIterator, CellConstIterator> RawTowerZDC::CellConstRange
Definition at line 27 of file RawTowerZDC.h.
View newest version in sPHENIX GitHub at line 27 of file RawTowerZDC.h
typedef CellMap::iterator RawTowerZDC::CellIterator
Definition at line 24 of file RawTowerZDC.h.
View newest version in sPHENIX GitHub at line 24 of file RawTowerZDC.h
typedef unsigned long long RawTowerZDC::CellKeyType
key type for cell map which should be consistent with CellKeyType
Definition at line 21 of file RawTowerZDC.h.
View newest version in sPHENIX GitHub at line 21 of file RawTowerZDC.h
typedef std::map<CellKeyType, float> RawTowerZDC::CellMap
Definition at line 23 of file RawTowerZDC.h.
View newest version in sPHENIX GitHub at line 23 of file RawTowerZDC.h
typedef std::pair<CellIterator, CellIterator> RawTowerZDC::CellRange
Definition at line 26 of file RawTowerZDC.h.
View newest version in sPHENIX GitHub at line 26 of file RawTowerZDC.h
typedef ShowerMap::const_iterator RawTowerZDC::ShowerConstIterator
Definition at line 31 of file RawTowerZDC.h.
View newest version in sPHENIX GitHub at line 31 of file RawTowerZDC.h
typedef std::pair<ShowerConstIterator, ShowerConstIterator> RawTowerZDC::ShowerConstRange
Definition at line 33 of file RawTowerZDC.h.
View newest version in sPHENIX GitHub at line 33 of file RawTowerZDC.h
typedef ShowerMap::iterator RawTowerZDC::ShowerIterator
Definition at line 30 of file RawTowerZDC.h.
View newest version in sPHENIX GitHub at line 30 of file RawTowerZDC.h
typedef std::map<int, float> RawTowerZDC::ShowerMap
Definition at line 29 of file RawTowerZDC.h.
View newest version in sPHENIX GitHub at line 29 of file RawTowerZDC.h
typedef std::pair<ShowerIterator, ShowerIterator> RawTowerZDC::ShowerRange
Definition at line 32 of file RawTowerZDC.h.
View newest version in sPHENIX GitHub at line 32 of file RawTowerZDC.h
Member Enumeration Documentation
enum RawTowerZDC::PROPERTY
Procedure to add a new PROPERTY tag: 1.add new tag below with unique value, 2.add a short name to RawTowerZDC::get_property_info
Enumerator:
prop_scint_gammas
Scintillation photon count or energy.
prop_cerenkov_gammas
Cherenkov photon count or energy.
prop_MAX_NUMBER
max limit in order to fit into 8 bit unsigned number
Definition at line 168 of file RawTowerZDC.h.
View newest version in sPHENIX GitHub at line 168 of file RawTowerZDC.h
Constructor & Destructor Documentation
RawTowerZDC::~RawTowerZDC () inline override
Definition at line 35 of file RawTowerZDC.h.
View newest version in sPHENIX GitHub at line 35 of file RawTowerZDC.h
RawTowerZDC::RawTowerZDC () inline protected
Definition at line 187 of file RawTowerZDC.h.
View newest version in sPHENIX GitHub at line 187 of file RawTowerZDC.h
Member Function Documentation
virtual void RawTowerZDC::add_ecell (const CellKeyType , const float) inline virtual
Reimplemented in RawTowerZDCv1.
Definition at line 146 of file RawTowerZDC.h.
View newest version in sPHENIX GitHub at line 146 of file RawTowerZDC.h
References PHOOL_VIRTUAL_WARN.
virtual void RawTowerZDC::add_eshower (const int , const float) inline virtual
Reimplemented in RawTowerZDCv1.
Definition at line 158 of file RawTowerZDC.h.
View newest version in sPHENIX GitHub at line 158 of file RawTowerZDC.h
References PHOOL_VIRTUAL_WARN.
virtual void RawTowerZDC::clear_g4cells () inline virtual
Reimplemented in RawTowerZDCv1.
Definition at line 151 of file RawTowerZDC.h.
View newest version in sPHENIX GitHub at line 151 of file RawTowerZDC.h
virtual void RawTowerZDC::clear_g4showers () inline virtual
Reimplemented in RawTowerZDCv1.
Definition at line 163 of file RawTowerZDC.h.
View newest version in sPHENIX GitHub at line 163 of file RawTowerZDC.h
virtual bool RawTowerZDC::empty_g4cells () const inline virtual
Reimplemented in RawTowerZDCv1.
Definition at line 141 of file RawTowerZDC.h.
View newest version in sPHENIX GitHub at line 141 of file RawTowerZDC.h
virtual bool RawTowerZDC::empty_g4showers () const inline virtual
Reimplemented in RawTowerZDCv1.
Definition at line 153 of file RawTowerZDC.h.
View newest version in sPHENIX GitHub at line 153 of file RawTowerZDC.h
RawTowerZDC::CellIterator RawTowerZDC::find_g4cell (CellKeyType id) virtual
Reimplemented in RawTowerZDCv1.
Definition at line 10 of file RawTowerZDC.cc.
View newest version in sPHENIX GitHub at line 10 of file RawTowerZDC.cc
References DummyCellMap.
RawTowerZDC::CellConstIterator RawTowerZDC::find_g4cell (CellKeyType id) const virtual
Reimplemented in RawTowerZDCv1.
Definition at line 15 of file RawTowerZDC.cc.
View newest version in sPHENIX GitHub at line 15 of file RawTowerZDC.cc
References DummyCellMap.
RawTowerZDC::ShowerIterator RawTowerZDC::find_g4shower (int) virtual
Reimplemented in RawTowerZDCv1.
Definition at line 32 of file RawTowerZDC.cc.
View newest version in sPHENIX GitHub at line 32 of file RawTowerZDC.cc
References DummyShowerMap.
RawTowerZDC::ShowerConstIterator RawTowerZDC::find_g4shower (int) const virtual
Reimplemented in RawTowerZDCv1.
Definition at line 37 of file RawTowerZDC.cc.
View newest version in sPHENIX GitHub at line 37 of file RawTowerZDC.cc
References DummyShowerMap.
virtual int RawTowerZDC::get_bineta () const inline virtual
Reimplemented in RawTowerZDCv1.
Definition at line 55 of file RawTowerZDC.h.
View newest version in sPHENIX GitHub at line 55 of file RawTowerZDC.h
References PHOOL_VIRTUAL_WARN.
Referenced by get_bintheta(), and RawTowerZDCCalibration::process_event().
virtual int RawTowerZDC::get_binl () const inline virtual
return layer ID assigned to tower
Reimplemented in RawTowerZDCv1.
Definition at line 73 of file RawTowerZDC.h.
View newest version in sPHENIX GitHub at line 73 of file RawTowerZDC.h
References PHOOL_VIRTUAL_WARN.
Referenced by RawTowerZDCCalibration::process_event().
virtual int RawTowerZDC::get_binphi () const inline virtual
Reimplemented in RawTowerZDCv1.
Definition at line 66 of file RawTowerZDC.h.
View newest version in sPHENIX GitHub at line 66 of file RawTowerZDC.h
References PHOOL_VIRTUAL_WARN.
Referenced by RawTowerZDCCalibration::process_event().
virtual int RawTowerZDC::get_bintheta () const inline virtual
Definition at line 61 of file RawTowerZDC.h.
View newest version in sPHENIX GitHub at line 61 of file RawTowerZDC.h
References get_bineta().
virtual double RawTowerZDC::get_cerenkov_gammas () const inline virtual
energy assigned to the tower. Depending on stage of process and DST node name, it could be energy deposition, light yield or calibrated energies
Definition at line 116 of file RawTowerZDC.h.
View newest version in sPHENIX GitHub at line 116 of file RawTowerZDC.h
References PHOOL_VIRTUAL_WARN.
virtual int RawTowerZDC::get_column () const inline virtual
Definition at line 78 of file RawTowerZDC.h.
View newest version in sPHENIX GitHub at line 78 of file RawTowerZDC.h
References PHOOL_VIRTUAL_WARN.
virtual double RawTowerZDC::get_energy () const inline virtual
energy assigned to the tower. Depending on stage of process and DST node name, it could be energy deposition, light yield or calibrated energies
Reimplemented in RawTowerZDCv1.
Definition at line 90 of file RawTowerZDC.h.
View newest version in sPHENIX GitHub at line 90 of file RawTowerZDC.h
References PHOOL_VIRTUAL_WARN.
Referenced by RawTowerZDCContainer::compress(), RawTowerZDCCalibration::process_event(), RawTowerZDCDigitizer::process_event(), RawTowerZDCv1::RawTowerZDCv1(), RawTowerZDCDigitizer::simple_photon_digitization(), and RawTowerZDCDigitizer::sipm_photon_digitization().
RawTowerZDC::CellConstRange RawTowerZDC::get_g4cells () const virtual
Reimplemented in RawTowerZDCv1.
Definition at line 20 of file RawTowerZDC.cc.
View newest version in sPHENIX GitHub at line 20 of file RawTowerZDC.cc
References DummyCellMap, and PHOOL_VIRTUAL_WARN.
Referenced by RawTowerZDCv1::RawTowerZDCv1().
RawTowerZDC::ShowerConstRange RawTowerZDC::get_g4showers () const virtual
Reimplemented in RawTowerZDCv1.
Definition at line 26 of file RawTowerZDC.cc.
View newest version in sPHENIX GitHub at line 26 of file RawTowerZDC.cc
References DummyShowerMap, and PHOOL_VIRTUAL_WARN.
Referenced by RawTowerZDCv1::RawTowerZDCv1().
virtual RawTowerZDCDefs::keytype RawTowerZDC::get_id () const inline virtual
Reimplemented in RawTowerZDCv1.
Definition at line 46 of file RawTowerZDC.h.
View newest version in sPHENIX GitHub at line 46 of file RawTowerZDC.h
References PHOOL_VIRTUAL_WARN.
Referenced by get_key(), RawTowerZDCCalibration::process_event(), and RawTowerZDCv1::RawTowerZDCv1().
virtual RawTowerZDCDefs::keytype RawTowerZDC::get_key () const inline virtual
Definition at line 53 of file RawTowerZDC.h.
View newest version in sPHENIX GitHub at line 53 of file RawTowerZDC.h
References get_id().
virtual double RawTowerZDC::get_property (const PROPERTY) const inline virtual
Definition at line 182 of file RawTowerZDC.h.
View newest version in sPHENIX GitHub at line 182 of file RawTowerZDC.h
const std::string RawTowerZDC::get_property_info (RawTowerZDC::PROPERTY prop_id) static
Definition at line 42 of file RawTowerZDC.cc.
View newest version in sPHENIX GitHub at line 42 of file RawTowerZDC.cc
References exit(), prop_cerenkov_gammas, and prop_scint_gammas.
virtual unsigned int RawTowerZDC::get_property_nocheck (const PROPERTY) const inline protected virtual
Definition at line 189 of file RawTowerZDC.h.
View newest version in sPHENIX GitHub at line 189 of file RawTowerZDC.h
virtual int RawTowerZDC::get_row () const inline virtual
Definition at line 83 of file RawTowerZDC.h.
View newest version in sPHENIX GitHub at line 83 of file RawTowerZDC.h
References PHOOL_VIRTUAL_WARN.
virtual double RawTowerZDC::get_scint_gammas () const inline virtual
energy assigned to the tower. Depending on stage of process and DST node name, it could be energy deposition, light yield or calibrated energies
Definition at line 103 of file RawTowerZDC.h.
View newest version in sPHENIX GitHub at line 103 of file RawTowerZDC.h
References PHOOL_VIRTUAL_WARN.
virtual float RawTowerZDC::get_time () const inline virtual
Time stamp assigned to the tower. Depending on the tower maker, it could be rise time or peak time.
Reimplemented in RawTowerZDCv1.
Definition at line 129 of file RawTowerZDC.h.
View newest version in sPHENIX GitHub at line 129 of file RawTowerZDC.h
References PHOOL_VIRTUAL_WARN.
Referenced by RawTowerZDCv1::RawTowerZDCv1().
virtual bool RawTowerZDC::has_property (const PROPERTY) const inline virtual
Definition at line 181 of file RawTowerZDC.h.
View newest version in sPHENIX GitHub at line 181 of file RawTowerZDC.h
void RawTowerZDC::identify (std::ostream & os = std::cout) const inline override virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from PHObject.
Reimplemented in RawTowerZDCv1.
Definition at line 43 of file RawTowerZDC.h.
View newest version in sPHENIX GitHub at line 43 of file RawTowerZDC.h
References PHOOL_VIRTUAL_WARN.
Referenced by RawTowerZDCDigitizer::process_event(), RawTowerZDCDigitizer::simple_photon_digitization(), and RawTowerZDCDigitizer::sipm_photon_digitization().
int RawTowerZDC::isValid () const inline override virtual
isValid returns non zero if object contains vailid data
Reimplemented from PHObject.
Reimplemented in RawTowerZDCv1.
Definition at line 38 of file RawTowerZDC.h.
View newest version in sPHENIX GitHub at line 38 of file RawTowerZDC.h
References PHOOL_VIRTUAL_WARN.
void RawTowerZDC::Reset () inline override virtual
Clear Event.
Reimplemented from PHObject.
Reimplemented in RawTowerZDCv1.
Definition at line 37 of file RawTowerZDC.h.
View newest version in sPHENIX GitHub at line 37 of file RawTowerZDC.h
References PHOOL_VIRTUAL_WARNING.
virtual void RawTowerZDC::set_cerenkov_gammas (const double) inline virtual
cerenkov_gammas assigned to the tower. Depending on stage of process and DST node name, it could be cerenkov_gammas deposition, light yield or calibrated energies
Definition at line 122 of file RawTowerZDC.h.
View newest version in sPHENIX GitHub at line 122 of file RawTowerZDC.h
References PHOOL_VIRTUAL_WARN.
virtual void RawTowerZDC::set_energy (const double) inline virtual
energy assigned to the tower. Depending on stage of process and DST node name, it could be energy deposition, light yield or calibrated energies
Reimplemented in RawTowerZDCv1.
Definition at line 96 of file RawTowerZDC.h.
View newest version in sPHENIX GitHub at line 96 of file RawTowerZDC.h
References PHOOL_VIRTUAL_WARN.
Referenced by RawTowerZDCCalibration::process_event(), RawTowerZDCDigitizer::simple_photon_digitization(), and RawTowerZDCDigitizer::sipm_photon_digitization().
virtual void RawTowerZDC::set_id (RawTowerZDCDefs::keytype) inline virtual
Reimplemented in RawTowerZDCv1.
Definition at line 45 of file RawTowerZDC.h.
View newest version in sPHENIX GitHub at line 45 of file RawTowerZDC.h
References PHOOL_VIRTUAL_WARN.
Referenced by RawTowerZDCContainer::AddTower(), and set_key().
virtual void RawTowerZDC::set_key (RawTowerZDCDefs::keytype id) inline virtual
Definition at line 52 of file RawTowerZDC.h.
View newest version in sPHENIX GitHub at line 52 of file RawTowerZDC.h
References set_id().
virtual void RawTowerZDC::set_property (const PROPERTY , const double) inline virtual
Definition at line 183 of file RawTowerZDC.h.
View newest version in sPHENIX GitHub at line 183 of file RawTowerZDC.h
virtual void RawTowerZDC::set_property_nocheck (const PROPERTY , const unsigned int) inline protected virtual
Definition at line 190 of file RawTowerZDC.h.
View newest version in sPHENIX GitHub at line 190 of file RawTowerZDC.h
virtual void RawTowerZDC::set_scint_gammas (const double) inline virtual
scint_gammas assigned to the tower. Depending on stage of process and DST node name, it could be scint_gammas deposition, light yield or calibrated energies
Definition at line 109 of file RawTowerZDC.h.
View newest version in sPHENIX GitHub at line 109 of file RawTowerZDC.h
References PHOOL_VIRTUAL_WARN.
virtual void RawTowerZDC::set_time (const float) inline virtual
Time stamp assigned to the tower. Depending on the tower maker, it could be rise time or peak time.
Reimplemented in RawTowerZDCv1.
Definition at line 135 of file RawTowerZDC.h.
View newest version in sPHENIX GitHub at line 135 of file RawTowerZDC.h
References PHOOL_VIRTUAL_WARN.
virtual size_t RawTowerZDC::size_g4cells () const inline virtual
Reimplemented in RawTowerZDCv1.
Definition at line 142 of file RawTowerZDC.h.
View newest version in sPHENIX GitHub at line 142 of file RawTowerZDC.h
virtual size_t RawTowerZDC::size_g4showers () const inline virtual
Reimplemented in RawTowerZDCv1.
Definition at line 154 of file RawTowerZDC.h.
View newest version in sPHENIX GitHub at line 154 of file RawTowerZDC.h
The documentation for this class was generated from the following files:
fun4all_eicdetectors/blob/master/reconstruction/eiczdcbase/RawTowerZDC.h
fun4all_eicdetectors/blob/master/reconstruction/eiczdcbase/RawTowerZDC.cc