EIC Software: Acts::Test::CylindricalTrackingGeometry Struct Reference
Acts::Test::CylindricalTrackingGeometry Struct Reference
#include <fun4all_acts/blob/master/Tests/CommonHelpers/Acts/Tests/CommonHelpers/CylindricalTrackingGeometry.hpp>
Public Member Functions
CylindricalTrackingGeometry (std::reference_wrapper< const GeometryContext > gctx)
Only allowed constructor with reference wrapper.
std::vector< Vector3D > modulePositionsCylinder (double radius, double zStagger, double moduleHalfLength, double lOverlap, const std::pair< int, int > &binningSchema)
std::shared_ptr< const
TrackingGeometry > operator() ()
Public Attributes
std::reference_wrapper< const
GeometryContext > geoContext
std::vector< std::unique_ptr
< const DetectorElementStub > > detectorStore = {}
The detector store for memory management.
Detailed Description
Definition at line 41 of file CylindricalTrackingGeometry.hpp.
View newest version in sPHENIX GitHub at line 41 of file CylindricalTrackingGeometry.hpp
Constructor & Destructor Documentation
Acts::Test::CylindricalTrackingGeometry::CylindricalTrackingGeometry (std::reference_wrapper< const GeometryContext > gctx) inline
Only allowed constructor with reference wrapper.
Definition at line 45 of file CylindricalTrackingGeometry.hpp.
View newest version in sPHENIX GitHub at line 45 of file CylindricalTrackingGeometry.hpp
Member Function Documentation
std::vector<Vector3D> Acts::Test::CylindricalTrackingGeometry::modulePositionsCylinder (double radius, double zStagger, double moduleHalfLength, double lOverlap, const std::pair< int, int > & binningSchema) inline
helper method for cylinder layer create the positions for module surfaces on a cylinder
Definition at line 54 of file CylindricalTrackingGeometry.hpp.
View newest version in sPHENIX GitHub at line 54 of file CylindricalTrackingGeometry.hpp
References kdfinder::abs(), cos(), M_PI, Acts::Test::minPhi, and Acts::UnitConstants::u.
Referenced by operator()().
std::shared_ptr<const TrackingGeometry> Acts::Test::CylindricalTrackingGeometry::operator() (void) inline
now push back the layer
Definition at line 84 of file CylindricalTrackingGeometry.hpp.
View newest version in sPHENIX GitHub at line 84 of file CylindricalTrackingGeometry.hpp
References Acts::units::_mm, Acts::arbitrary, Acts::Surface::assignSurfaceMaterial(), Acts::binR, cos(), Acts::TrackingVolume::create(), detectorStore, Acts::ProtoLayer::envR, geoContext, Acts::getDefaultLogger(), Acts::Logging::INFO, Acts::CylinderVolumeHelper::Config::layerArrayCreator, Acts::PassiveLayerBuilder::Config::layerIdentification, Acts::Test::makeBeryllium(), Acts::Test::makeSilicon(), modulePositionsCylinder(), Acts::VectorHelpers::phi(), Acts::LayerCreator::Config::surfaceArrayCreator, and Acts::CylinderVolumeBuilder::Config::trackingVolumeHelper.
Member Data Documentation
std::vector<std::unique_ptr<const DetectorElementStub> > Acts::Test::CylindricalTrackingGeometry::detectorStore = {}
The detector store for memory management.
Definition at line 50 of file CylindricalTrackingGeometry.hpp.
View newest version in sPHENIX GitHub at line 50 of file CylindricalTrackingGeometry.hpp
Referenced by operator()().
std::reference_wrapper<const GeometryContext> Acts::Test::CylindricalTrackingGeometry::geoContext
Definition at line 42 of file CylindricalTrackingGeometry.hpp.
View newest version in sPHENIX GitHub at line 42 of file CylindricalTrackingGeometry.hpp
Referenced by operator()().
The documentation for this struct was generated from the following file:
fun4all_acts/blob/master/Tests/CommonHelpers/Acts/Tests/CommonHelpers/CylindricalTrackingGeometry.hpp