EIC Software: CbmRichConverter Class Reference
CbmRichConverter Class Reference
Convert internal data classes to cbmroot common data classes.
#include <EicRoot/blob/master/rich/CbmRichConverter.h>
Static Public Member Functions
static void CopyHitsToRingLight (const CbmRichRing *ring1, CbmRichRingLight *ring2)
Copy hits from CbmRichRing to CbmRichRingLight.
static void CopyHitsToRingLight (const vector< double > &hitX, const vector< double > &hitY, CbmRichRingLight *ring)
Copy hits coordinates from vectors to CbmRichRingLight.
static void CopyParamsToRing (const CbmRichRingLight *ring1, CbmRichRing *ring2)
Copy parameters from CbmRichRingLight to CbmRichRing.
static void Init ()
Initialize array of RICH hits.
Static Public Attributes
static TClonesArray * fRichHits = NULL
Detailed Description
Convert internal data classes to cbmroot common data classes.
Author
Semen Lebedev
Date
2012
Definition at line 34 of file CbmRichConverter.h.
View newest version in sPHENIX GitHub at line 34 of file CbmRichConverter.h
Member Function Documentation
static void CbmRichConverter::CopyHitsToRingLight (const CbmRichRing * ring1, CbmRichRingLight * ring2) inline static
Copy hits from CbmRichRing to CbmRichRingLight.
Parameters
[in] ring1 CbmRichRing from which hits are copied
[out] ring2 RICH ring to which hits are added.
Definition at line 42 of file CbmRichConverter.h.
View newest version in sPHENIX GitHub at line 42 of file CbmRichConverter.h
References CbmRichRingLight::AddHit(), fRichHits, CbmRichRing::GetHit(), CbmRichRing::GetNofHits(), CbmPixelHit::GetX(), and CbmPixelHit::GetY().
Referenced by CbmRichTrainAnnSelect::DiffFakeTrueCircle(), CbmRichGeoTest::RingParameters(), and CbmRichReconstruction::RunFitter().
static void CbmRichConverter::CopyHitsToRingLight (const vector< double > & hitX, const vector< double > & hitY, CbmRichRingLight * ring) inline static
Copy hits coordinates from vectors to CbmRichRingLight.
Parameters
[in] hitX Vector of X coordinates.
[in] hitY Vector of Y coordinates.
[out] ring RICH ring to which hits are added.
Definition at line 66 of file CbmRichConverter.h.
View newest version in sPHENIX GitHub at line 66 of file CbmRichConverter.h
References CbmRichRingLight::AddHit().
static void CbmRichConverter::CopyParamsToRing (const CbmRichRingLight * ring1, CbmRichRing * ring2) inline static
Copy parameters from CbmRichRingLight to CbmRichRing.
Parameters
[in] ring1 CbmRichRingLight from which parameters are copied.
[out] ring2 CbmRichRing to which parameters are copied.
Definition at line 83 of file CbmRichConverter.h.
View newest version in sPHENIX GitHub at line 83 of file CbmRichConverter.h
References CbmRichRingLight::GetAaxis(), CbmRichRingLight::GetBaxis(), CbmRichRingLight::GetCenterX(), CbmRichRingLight::GetCenterY(), CbmRichRingLight::GetChi2(), CbmRichRingLight::GetPhi(), CbmRichRingLight::GetRadius(), CbmRichRing::SetAaxis(), CbmRichRing::SetBaxis(), CbmRichRing::SetCenterX(), CbmRichRing::SetCenterY(), CbmRichRing::SetChi2(), CbmRichRing::SetPhi(), and CbmRichRing::SetRadius().
Referenced by CbmRichReconstruction::RunFitter().
static void CbmRichConverter::Init (void) inline static
Initialize array of RICH hits.
Definition at line 102 of file CbmRichConverter.h.
View newest version in sPHENIX GitHub at line 102 of file CbmRichConverter.h
References fRichHits, FairRootManager::GetObject(), and FairRootManager::Instance().
Referenced by CbmRichTrainAnnSelect::Init(), and CbmRichReconstruction::InitFitter().
Member Data Documentation
TClonesArray * CbmRichConverter::fRichHits = NULL static
Definition at line 96 of file CbmRichConverter.h.
View newest version in sPHENIX GitHub at line 96 of file CbmRichConverter.h
Referenced by CopyHitsToRingLight(), and Init().
The documentation for this class was generated from the following files:
EicRoot/blob/master/rich/CbmRichConverter.h
EicRoot/blob/master/rich/CbmRichConverter.cxx