EIC Software: Splitter Class Reference
Splitter Class Reference
#include <EicRoot/blob/master/eic/ayk/Splitter.h>
Public Member Functions
Splitter ()
int splitString (char *str)
int splitNextString (FILE *ff)
int getArgn ()
const char * getArgp (unsigned id)
Private Member Functions
int splitStringCore ()
Private Attributes
unsigned argn
char * argp [SUBSTRINGS_MAX]
char buffer [STRING_LEN_MAX]
Detailed Description
Definition at line 19 of file Splitter.h.
View newest version in sPHENIX GitHub at line 19 of file Splitter.h
Constructor & Destructor Documentation
Splitter::Splitter () inline
Definition at line 21 of file Splitter.h.
View newest version in sPHENIX GitHub at line 21 of file Splitter.h
References argn.
Member Function Documentation
int Splitter::getArgn () inline
Definition at line 27 of file Splitter.h.
View newest version in sPHENIX GitHub at line 27 of file Splitter.h
References argn.
Referenced by import_ascii_field_map().
const char* Splitter::getArgp (unsigned id) inline
Definition at line 29 of file Splitter.h.
View newest version in sPHENIX GitHub at line 29 of file Splitter.h
References argn, and argp.
Referenced by import_ascii_field_map().
int Splitter::splitNextString (FILE * ff)
Definition at line 59 of file Splitter.cxx.
View newest version in sPHENIX GitHub at line 59 of file Splitter.cxx
References splitStringCore(), and STRING_LEN_MAX.
Referenced by import_ascii_field_map().
int Splitter::splitString (char * str)
Definition at line 46 of file Splitter.cxx.
View newest version in sPHENIX GitHub at line 46 of file Splitter.cxx
References splitStringCore(), and STRING_LEN_MAX.
int Splitter::splitStringCore () private
Definition at line 19 of file Splitter.cxx.
View newest version in sPHENIX GitHub at line 19 of file Splitter.cxx
References argn, argp, and SUBSTRINGS_MAX.
Referenced by splitNextString(), and splitString().
Member Data Documentation
unsigned Splitter::argn private
Definition at line 29 of file Splitter.h.
View newest version in sPHENIX GitHub at line 29 of file Splitter.h
Referenced by getArgn(), getArgp(), splitStringCore(), and Splitter().
char* Splitter::argp[SUBSTRINGS_MAX] private
Definition at line 34 of file Splitter.h.
View newest version in sPHENIX GitHub at line 34 of file Splitter.h
Referenced by getArgp(), and splitStringCore().
char Splitter::buffer[STRING_LEN_MAX] private
Definition at line 38 of file Splitter.h.
View newest version in sPHENIX GitHub at line 38 of file Splitter.h
The documentation for this class was generated from the following files:
EicRoot/blob/master/eic/ayk/Splitter.h
EicRoot/blob/master/eic/ayk/Splitter.cxx