EIC Software: EicMCApplication Class Reference
EicMCApplication Class Reference
#include <EicRoot/blob/master/eic/base/EicMCApplication.h>
Public Member Functions
EicMCApplication ()
EicMCApplication (const char *name, const char *title, TObjArray *ModList, const char *MatName)
~EicMCApplication ()
void Stepping ()
Public Member Functions inherited from FairMCApplication
FairMCApplication (const char *name, const char *title, TObjArray *ModList, const char *MatName)
FairMCApplication ()
virtual ~FairMCApplication ()
virtual void AddDecayModes ()
virtual void AddParticles ()
virtual void AddIons ()
void AddTask (TTask *fTask)
virtual void BeginEvent ()
virtual void BeginPrimary ()
virtual void ConstructGeometry ()
virtual void ConstructOpGeometry ()
virtual void Field (const Double_t *x, Double_t *b) const
virtual void FinishEvent ()
virtual void FinishPrimary ()
void FinishRun ()
virtual void GeneratePrimaries ()
FairDetector * GetDetector (const char *DetName)
FairField * GetField ()
FairPrimaryGenerator * GetGenerator ()
TTask * GetListOfTasks ()
FairGenericStack * GetStack ()
TChain * GetChain ()
virtual void InitGeometry ()
void InitMC (const char *setup, const char *cuts)
void InitTasks ()
virtual void PostTrack ()
virtual void PreTrack ()
void RunMC (Int_t nofEvents)
void SetField (FairField *field)
void SetGenerator (FairPrimaryGenerator *fxGenerator)
void SetParTask ()
void SetPythiaDecayer (Bool_t decayer)
void SetPythiaDecayerConfig (const TString decayerConf)
void SetRadiationLengthReg (Bool_t RadLen)
void SetRadiationMapReg (Bool_t RadMap)
void SetTrackingDebugMode (Bool_t set)
void SetUserDecay (Bool_t decay)
void SetUserDecayConfig (const TString decayerConf)
virtual void StopRun ()
virtual Double_t TrackingRmax () const
virtual Double_t TrackingZmax () const
void AddMeshList (TObjArray *meshList)
Additional Inherited Members
Static Public Member Functions inherited from FairMCApplication
static FairMCApplication * Instance ()
Protected Attributes inherited from FairMCApplication
std::map< Int_t, Int_t > fModVolMap
std::map< Int_t, Int_t >::iterator fModVolIter
Detailed Description
Definition at line 13 of file EicMCApplication.h.
View newest version in sPHENIX GitHub at line 13 of file EicMCApplication.h
Constructor & Destructor Documentation
EicMCApplication::EicMCApplication () inline
Definition at line 16 of file EicMCApplication.h.
View newest version in sPHENIX GitHub at line 16 of file EicMCApplication.h
EicMCApplication::EicMCApplication (const char * name, const char * title, TObjArray * ModList, const char * MatName) inline
Definition at line 17 of file EicMCApplication.h.
View newest version in sPHENIX GitHub at line 17 of file EicMCApplication.h
EicMCApplication::~EicMCApplication () inline
Definition at line 19 of file EicMCApplication.h.
View newest version in sPHENIX GitHub at line 19 of file EicMCApplication.h
Member Function Documentation
void EicMCApplication::Stepping () virtual
Define action at each step, dispatch the action to the corresponding detectors
Reimplemented from FairMCApplication.
Definition at line 30 of file EicMCApplication.cxx.
View newest version in sPHENIX GitHub at line 30 of file EicMCApplication.cxx
References FluxMonitorGrid::AddEntry(), EicDetector::CheckEnergyMonitors(), FairMCApplication::fModVolIter, FairMCApplication::fModVolMap, EicRunSim::GetFluxMonitorGrid(), FairRunSim::GetListOfModules(), EicDetector::gptr, EicRunSim::IgnoreBlackHoleVolumesFlag(), EicBlackHole::InsertIntoTrackList(), FairRunSim::Instance(), EicRunSim::Instance(), EicGeoParData::IsBlackHoleVolume(), EicDetector::IsKillerVolume(), particle, FairMCApplication::Stepping(), EicRunSim::SuppressFairRootSteppingCallFlag(), and EicRunSim::SuppressSecondariesFlag().
The documentation for this class was generated from the following files:
EicRoot/blob/master/eic/base/EicMCApplication.h
EicRoot/blob/master/eic/base/EicMCApplication.cxx