EIC Software: EicCadWizardCut Class Reference
EicCadWizardCut Class Reference abstract
#include <EicRoot/blob/master/eic/cad/wizard/EicCadWizardCut.h>
Public Member Functions
EicCadWizardCut ()
~EicCadWizardCut ()
virtual bool IsEqual (const EicCadWizardCut *cut) const =0
virtual TGeoCombiTrans * BuildRootVolume (const char *vname, const char *tname)=0
const TopoDS_Shape & GetSolid (void) const
void IncrementMultiplicity (void)
unsigned GetMultiplicity (void) const
void AddCommonSolid (TopoDS_Shape *solid)
void AddCutSolid (TopoDS_Shape *solid)
unsigned GetCommonSolidsCount (void) const
unsigned GetCutSolidsCount (void) const
Public Attributes
std::vector< TopoDS_Shape * > mCutSolids
std::vector< TopoDS_Shape * > mCommonSolids
Protected Attributes
double mDimension
TopoDS_Shape * mSolid
unsigned mMultiplicity
Detailed Description
Definition at line 19 of file EicCadWizardCut.h.
View newest version in sPHENIX GitHub at line 19 of file EicCadWizardCut.h
Constructor & Destructor Documentation
EicCadWizardCut::EicCadWizardCut () inline
Definition at line 21 of file EicCadWizardCut.h.
View newest version in sPHENIX GitHub at line 21 of file EicCadWizardCut.h
EicCadWizardCut::~EicCadWizardCut () inline
Definition at line 22 of file EicCadWizardCut.h.
View newest version in sPHENIX GitHub at line 22 of file EicCadWizardCut.h
Member Function Documentation
void EicCadWizardCut::AddCommonSolid (TopoDS_Shape * solid) inline
Definition at line 31 of file EicCadWizardCut.h.
View newest version in sPHENIX GitHub at line 31 of file EicCadWizardCut.h
References mCommonSolids.
Referenced by EicCadWizard::FaceGuidedSplit(), and EicCadWizard::FlatSurfaceSplit().
void EicCadWizardCut::AddCutSolid (TopoDS_Shape * solid) inline
Definition at line 32 of file EicCadWizardCut.h.
View newest version in sPHENIX GitHub at line 32 of file EicCadWizardCut.h
References mCutSolids.
Referenced by EicCadWizard::FaceGuidedSplit(), and EicCadWizard::FlatSurfaceSplit().
virtual TGeoCombiTrans* EicCadWizardCut::BuildRootVolume (const char * vname, const char * tname) pure virtual
Implemented in EicCadWizardCone, EicCadWizardCylinder, EicCadWizardPlane, EicCadWizardSphere, and EicCadWizardTorus.
unsigned EicCadWizardCut::GetCommonSolidsCount (void) const inline
Definition at line 34 of file EicCadWizardCut.h.
View newest version in sPHENIX GitHub at line 34 of file EicCadWizardCut.h
References mCommonSolids.
Referenced by EicCadWizard::FaceGuidedSplit(), and EicCadWizard::FlatSurfaceSplit().
unsigned EicCadWizardCut::GetCutSolidsCount (void) const inline
Definition at line 35 of file EicCadWizardCut.h.
View newest version in sPHENIX GitHub at line 35 of file EicCadWizardCut.h
Referenced by EicCadWizard::FaceGuidedSplit(), and EicCadWizard::FlatSurfaceSplit().
unsigned EicCadWizardCut::GetMultiplicity (void) const inline
Definition at line 29 of file EicCadWizardCut.h.
View newest version in sPHENIX GitHub at line 29 of file EicCadWizardCut.h
References mMultiplicity.
Referenced by EicCadWizard::FaceGuidedSplit(), and EicCadWizard::FlatSurfaceSplit().
const TopoDS_Shape& EicCadWizardCut::GetSolid (void) const inline
Definition at line 27 of file EicCadWizardCut.h.
View newest version in sPHENIX GitHub at line 27 of file EicCadWizardCut.h
References mSolid.
Referenced by EicCadWizard::FaceGuidedSplit(), and EicCadWizard::FlatSurfaceSplit().
void EicCadWizardCut::IncrementMultiplicity (void) inline
Definition at line 28 of file EicCadWizardCut.h.
View newest version in sPHENIX GitHub at line 28 of file EicCadWizardCut.h
References mMultiplicity.
Referenced by EicCadWizard::FaceGuidedSplit().
virtual bool EicCadWizardCut::IsEqual (const EicCadWizardCut * cut) const pure virtual
Implemented in EicCadWizardCylinder, EicCadWizardCone, EicCadWizardPlane, EicCadWizardSphere, and EicCadWizardTorus.
Referenced by EicCadWizard::FaceGuidedSplit(), and EicCadWizard::FlatSurfaceSplit().
Member Data Documentation
std::vector<TopoDS_Shape*> EicCadWizardCut::mCommonSolids
Definition at line 47 of file EicCadWizardCut.h.
View newest version in sPHENIX GitHub at line 47 of file EicCadWizardCut.h
Referenced by AddCommonSolid(), EicCadWizard::FaceGuidedSplit(), EicCadWizard::FlatSurfaceSplit(), and GetCommonSolidsCount().
std::vector<TopoDS_Shape*> EicCadWizardCut::mCutSolids
Definition at line 47 of file EicCadWizardCut.h.
View newest version in sPHENIX GitHub at line 47 of file EicCadWizardCut.h
Referenced by AddCutSolid(), EicCadWizard::FaceGuidedSplit(), and EicCadWizard::FlatSurfaceSplit().
double EicCadWizardCut::mDimension protected
Definition at line 35 of file EicCadWizardCut.h.
View newest version in sPHENIX GitHub at line 35 of file EicCadWizardCut.h
Referenced by EicCadWizardCone::BuildRootVolume(), EicCadWizardCylinder::BuildRootVolume(), EicCadWizardCone::EicCadWizardCone(), and EicCadWizardCylinder::EicCadWizardCylinder().
unsigned EicCadWizardCut::mMultiplicity protected
Definition at line 44 of file EicCadWizardCut.h.
View newest version in sPHENIX GitHub at line 44 of file EicCadWizardCut.h
Referenced by GetMultiplicity(), and IncrementMultiplicity().
TopoDS_Shape* EicCadWizardCut::mSolid protected
Definition at line 42 of file EicCadWizardCut.h.
View newest version in sPHENIX GitHub at line 42 of file EicCadWizardCut.h
Referenced by EicCadWizardCone::EicCadWizardCone(), EicCadWizardCylinder::EicCadWizardCylinder(), EicCadWizardPlane::EicCadWizardPlane(), EicCadWizardSphere::EicCadWizardSphere(), EicCadWizardTorus::EicCadWizardTorus(), and GetSolid().
The documentation for this class was generated from the following file:
EicRoot/blob/master/eic/cad/wizard/EicCadWizardCut.h