EIC Software: EtmAzimuthalScan Class Reference
EtmAzimuthalScan Class Reference
#include <EicToyModel/blob/master/include/EtmAzimuthalScan.h>
Public Member Functions
EtmAzimuthalScan (double etamin=0.0, double etamax=0.0, unsigned ntheta=25, unsigned nphi=120)
~EtmAzimuthalScan ()
EtmAzimuthalScan * SetVertexSigma (double sigma)
EtmAzimuthalScan * SetStat (unsigned stat)
EtmAzimuthalScan * SetBfield (double field)
EtmAzimuthalScan * SetBfield (const char *fname)
EtmAzimuthalScan * SetBfieldScanStep (double step)
void DoIt (const char *fout)
Private Member Functions
TVector3 GetBfield (const TVector3 &xx) const
Private Attributes
TH2D * mRL
TH2D * mZL
TH2D * mBdl
double mEtaMin
double mEtaMax
double mVertexSigma
double mBfield
double mBfieldScanStep
unsigned mThetaBinCount
unsigned mPhiBinCount
unsigned mStat
BeastMagneticField * mBeastMagneticField
Detailed Description
Definition at line 10 of file EtmAzimuthalScan.h.
View newest version in sPHENIX GitHub at line 10 of file EtmAzimuthalScan.h
Constructor & Destructor Documentation
EtmAzimuthalScan::EtmAzimuthalScan (double etamin = 0.0, double etamax = 0.0, unsigned ntheta = 25, unsigned nphi = 120)
Definition at line 17 of file EtmAzimuthalScan.cc.
View newest version in sPHENIX GitHub at line 17 of file EtmAzimuthalScan.cc
References mPhiBinCount, and mThetaBinCount.
EtmAzimuthalScan::~EtmAzimuthalScan () inline
Definition at line 15 of file EtmAzimuthalScan.h.
View newest version in sPHENIX GitHub at line 15 of file EtmAzimuthalScan.h
Member Function Documentation
void EtmAzimuthalScan::DoIt (const char * fout)
Definition at line 79 of file EtmAzimuthalScan.cc.
View newest version in sPHENIX GitHub at line 79 of file EtmAzimuthalScan.cc
References _ACCELERATOR_VACUUM_, _MARKER_, _UNIVERSE_VACUUM_, cos(), eic, Eta2Theta(), GetBfield(), EicToyModel::Instance(), M_PI, marker(), material(), mBdl, mBfieldScanStep, mEtaMax, mEtaMin, mPhiBinCount, mRL, mStat, mThetaBinCount, mVertexSigma, mZL, phi, sign(), theta(), thetamin, and thickness.
TVector3 EtmAzimuthalScan::GetBfield (const TVector3 & xx) const private
Definition at line 61 of file EtmAzimuthalScan.cc.
View newest version in sPHENIX GitHub at line 61 of file EtmAzimuthalScan.cc
References BeastMagneticField::GetFieldValue(), mBeastMagneticField, mBfield, and BeastMagneticField::ValidMapImported().
Referenced by DoIt().
EtmAzimuthalScan * EtmAzimuthalScan::SetBfield (double field)
Definition at line 31 of file EtmAzimuthalScan.cc.
View newest version in sPHENIX GitHub at line 31 of file EtmAzimuthalScan.cc
References mBeastMagneticField, and mBfield.
EtmAzimuthalScan * EtmAzimuthalScan::SetBfield (const char * fname)
Definition at line 43 of file EtmAzimuthalScan.cc.
View newest version in sPHENIX GitHub at line 43 of file EtmAzimuthalScan.cc
References mBeastMagneticField, mBfield, BeastMagneticField::UseInterpolation(), and BeastMagneticField::ValidMapImported().
EtmAzimuthalScan* EtmAzimuthalScan::SetBfieldScanStep (double step) inline
Definition at line 22 of file EtmAzimuthalScan.h.
View newest version in sPHENIX GitHub at line 22 of file EtmAzimuthalScan.h
References mBfieldScanStep, and Acts::Test::step().
EtmAzimuthalScan* EtmAzimuthalScan::SetStat (unsigned stat) inline
Definition at line 18 of file EtmAzimuthalScan.h.
View newest version in sPHENIX GitHub at line 18 of file EtmAzimuthalScan.h
References mStat.
EtmAzimuthalScan* EtmAzimuthalScan::SetVertexSigma (double sigma) inline
Definition at line 17 of file EtmAzimuthalScan.h.
View newest version in sPHENIX GitHub at line 17 of file EtmAzimuthalScan.h
References mVertexSigma.
Member Data Documentation
TH2D * EtmAzimuthalScan::mBdl private
Definition at line 31 of file EtmAzimuthalScan.h.
View newest version in sPHENIX GitHub at line 31 of file EtmAzimuthalScan.h
Referenced by DoIt().
BeastMagneticField* EtmAzimuthalScan::mBeastMagneticField private
Definition at line 36 of file EtmAzimuthalScan.h.
View newest version in sPHENIX GitHub at line 36 of file EtmAzimuthalScan.h
Referenced by GetBfield(), and SetBfield().
double EtmAzimuthalScan::mBfield private
Definition at line 33 of file EtmAzimuthalScan.h.
View newest version in sPHENIX GitHub at line 33 of file EtmAzimuthalScan.h
Referenced by GetBfield(), and SetBfield().
double EtmAzimuthalScan::mBfieldScanStep private
Definition at line 33 of file EtmAzimuthalScan.h.
View newest version in sPHENIX GitHub at line 33 of file EtmAzimuthalScan.h
Referenced by DoIt(), and SetBfieldScanStep().
double EtmAzimuthalScan::mEtaMax private
Definition at line 33 of file EtmAzimuthalScan.h.
View newest version in sPHENIX GitHub at line 33 of file EtmAzimuthalScan.h
Referenced by DoIt().
double EtmAzimuthalScan::mEtaMin private
Definition at line 33 of file EtmAzimuthalScan.h.
View newest version in sPHENIX GitHub at line 33 of file EtmAzimuthalScan.h
Referenced by DoIt().
unsigned EtmAzimuthalScan::mPhiBinCount private
Definition at line 34 of file EtmAzimuthalScan.h.
View newest version in sPHENIX GitHub at line 34 of file EtmAzimuthalScan.h
Referenced by DoIt(), and EtmAzimuthalScan().
TH2D* EtmAzimuthalScan::mRL private
Definition at line 31 of file EtmAzimuthalScan.h.
View newest version in sPHENIX GitHub at line 31 of file EtmAzimuthalScan.h
Referenced by DoIt().
unsigned EtmAzimuthalScan::mStat private
Definition at line 34 of file EtmAzimuthalScan.h.
View newest version in sPHENIX GitHub at line 34 of file EtmAzimuthalScan.h
Referenced by DoIt(), and SetStat().
unsigned EtmAzimuthalScan::mThetaBinCount private
Definition at line 34 of file EtmAzimuthalScan.h.
View newest version in sPHENIX GitHub at line 34 of file EtmAzimuthalScan.h
Referenced by DoIt(), and EtmAzimuthalScan().
double EtmAzimuthalScan::mVertexSigma private
Definition at line 33 of file EtmAzimuthalScan.h.
View newest version in sPHENIX GitHub at line 33 of file EtmAzimuthalScan.h
Referenced by DoIt(), and SetVertexSigma().
TH2D * EtmAzimuthalScan::mZL private
Definition at line 31 of file EtmAzimuthalScan.h.
View newest version in sPHENIX GitHub at line 31 of file EtmAzimuthalScan.h
Referenced by DoIt().
The documentation for this class was generated from the following files:
EicToyModel/blob/master/include/EtmAzimuthalScan.h
EicToyModel/blob/master/source/EtmAzimuthalScan.cc