EIC Software: tetgenmesh::arraypool Class Reference
tetgenmesh::arraypool Class Reference
#include <EicRoot/blob/master/eic/cad/tetgen/tetgen.h>
Public Member Functions
void restart ()
void poolinit (int sizeofobject, int log2objperblk)
char * getblock (int objectindex)
void * lookup (int objectindex)
int newindex (void **newptr)
arraypool (int sizeofobject, int log2objperblk)
~arraypool ()
Public Attributes
int objectbytes
int objectsperblock
int log2objectsperblock
int objectsperblockmark
int toparraylen
char ** toparray
long objects
unsigned long totalmemory
Detailed Description
Definition at line 980 of file tetgen.h.
View newest version in sPHENIX GitHub at line 980 of file tetgen.h
Constructor & Destructor Documentation
tetgenmesh::arraypool::arraypool (int sizeofobject, int log2objperblk)
Definition at line 3756 of file tetgen.cxx.
View newest version in sPHENIX GitHub at line 3756 of file tetgen.cxx
tetgenmesh::arraypool::~arraypool ()
Definition at line 3761 of file tetgen.cxx.
View newest version in sPHENIX GitHub at line 3761 of file tetgen.cxx
Member Function Documentation
char * tetgenmesh::arraypool::getblock (int objectindex)
Definition at line 3798 of file tetgen.cxx.
View newest version in sPHENIX GitHub at line 3798 of file tetgen.cxx
void * tetgenmesh::arraypool::lookup (int objectindex)
Definition at line 3863 of file tetgen.cxx.
View newest version in sPHENIX GitHub at line 3863 of file tetgen.cxx
int tetgenmesh::arraypool::newindex (void ** newptr)
Definition at line 3900 of file tetgen.cxx.
View newest version in sPHENIX GitHub at line 3900 of file tetgen.cxx
Referenced by tetgenmesh::add_steinerpt_in_schoenhardtpoly(), tetgenmesh::add_steinerpt_in_segment(), tetgenmesh::addsteiner4recoversegment(), tetgenmesh::carvecavity(), tetgenmesh::carveholes(), tetgenmesh::collectremovepoints(), tetgenmesh::constraineddelaunay(), tetgenmesh::constrainedfacets(), tetgenmesh::delaunizecavity(), tetgenmesh::fillcavity(), tetgenmesh::fillregion(), tetgenmesh::flipinsertfacet(), tetgenmesh::flipnm(), tetgenmesh::formcavity(), tetgenmesh::formregion(), tetgenmesh::getedge(), tetgenmesh::getvertexstar(), tetgenmesh::improvequalitybyflips(), tetgenmesh::improvequalitybysmoothing(), tetgenmesh::incrementalflip(), tetgenmesh::insertpoint(), tetgenmesh::insertpoint_cdt(), tetgenmesh::lawsonflip3d(), tetgenio::load_stl(), tetgenmesh::makefacetverticesmap(), tetgenmesh::makesegmentendpointsmap(), tetgenmesh::meshsurface(), tetgenmesh::optimizemesh(), tetgenmesh::recoverboundary(), tetgenmesh::recoverdelaunay(), tetgenmesh::recoverfacebyflips(), tetgenmesh::recoversegments(), tetgenmesh::recoversubfaces(), tetgenmesh::removeedgebyflips(), tetgenmesh::removeslivers(), tetgenmesh::scarveholes(), tetgenmesh::sinsertvertex(), tetgenmesh::splitsliver(), tetgenmesh::sremovevertex(), and tetgenmesh::suppressbdrysteinerpoint().
void tetgenmesh::arraypool::poolinit (int sizeofobject, int log2objperblk)
Definition at line 3730 of file tetgen.cxx.
View newest version in sPHENIX GitHub at line 3730 of file tetgen.cxx
void tetgenmesh::arraypool::restart ()
Definition at line 3716 of file tetgen.cxx.
View newest version in sPHENIX GitHub at line 3716 of file tetgen.cxx
References objects.
Referenced by tetgenmesh::add_steinerpt_in_schoenhardtpoly(), tetgenmesh::add_steinerpt_in_segment(), tetgenmesh::carvecavity(), tetgenmesh::carveholes(), tetgenmesh::collectremovepoints(), tetgenmesh::constrainedfacets(), tetgenmesh::delaunizecavity(), tetgenmesh::fillcavity(), tetgenmesh::fillregion(), tetgenmesh::flipinsertfacet(), tetgenmesh::formcavity(), tetgenmesh::getedge(), tetgenmesh::improvequalitybyflips(), tetgenmesh::improvequalitybysmoothing(), tetgenmesh::incrementalflip(), tetgenmesh::insertconstrainedpoints(), tetgenmesh::insertpoint(), tetgenmesh::insertpoint_abort(), tetgenmesh::insertpoint_cdt(), tetgenmesh::lawsonflip3d(), tetgenmesh::makefacetverticesmap(), tetgenmesh::meshsurface(), tetgenmesh::optimizemesh(), tetgenmesh::outvoronoi(), tetgenmesh::recoverboundary(), tetgenmesh::recoverdelaunay(), tetgenmesh::recoverfacebyflips(), tetgenmesh::refineregion(), tetgenmesh::removeslivers(), tetgenmesh::removevertexbyflips(), tetgenmesh::restorecavity(), tetgenmesh::scarveholes(), tetgenmesh::sinsertvertex(), tetgenmesh::splitsegment(), tetgenmesh::splitsliver(), tetgenmesh::splitsubface(), tetgenmesh::splittetrahedron(), tetgenmesh::sremovevertex(), tetgenmesh::suppressbdrysteinerpoint(), tetgenmesh::suppresssteinerpoints(), and tetgenmesh::triangulate().
Member Data Documentation
int tetgenmesh::arraypool::log2objectsperblock
Definition at line 986 of file tetgen.h.
View newest version in sPHENIX GitHub at line 986 of file tetgen.h
int tetgenmesh::arraypool::objectbytes
Definition at line 984 of file tetgen.h.
View newest version in sPHENIX GitHub at line 984 of file tetgen.h
long tetgenmesh::arraypool::objects
Definition at line 990 of file tetgen.h.
View newest version in sPHENIX GitHub at line 990 of file tetgen.h
Referenced by tetgenmesh::add_steinerpt_in_schoenhardtpoly(), tetgenmesh::add_steinerpt_in_segment(), tetgenmesh::calculateabovepoint(), tetgenmesh::carvecavity(), tetgenmesh::carveholes(), tetgenmesh::collectremovepoints(), tetgenmesh::constrainedfacets(), tetgenmesh::delaunizecavity(), tetgenmesh::delaunizesegments(), tetgenmesh::fillcavity(), tetgenmesh::fillregion(), tetgenmesh::flipinsertfacet(), tetgenmesh::flipnm(), tetgenmesh::flipnm_post(), tetgenmesh::formcavity(), tetgenmesh::formregion(), tetgenmesh::getedge(), tetgenmesh::getvertexstar(), tetgenmesh::improvequalitybyflips(), tetgenmesh::improvequalitybysmoothing(), tetgenmesh::incrementalflip(), tetgenmesh::insertpoint(), tetgenmesh::insertpoint_abort(), tetgenmesh::insertpoint_cdt(), tetgenmesh::lawsonflip3d(), tetgenio::load_stl(), tetgenmesh::makefacetverticesmap(), tetgenmesh::makesegmentendpointsmap(), tetgenmesh::meshcoarsening(), tetgenmesh::meshsurface(), tetgenmesh::optimizemesh(), tetgenmesh::outvoronoi(), tetgenmesh::recoverboundary(), tetgenmesh::recoverdelaunay(), tetgenmesh::recoverfacebyflips(), tetgenmesh::recoversegments(), tetgenmesh::recoversubfaces(), tetgenmesh::reduceedgesatvertex(), tetgenmesh::refineregion(), tetgenmesh::removeslivers(), tetgenmesh::removevertexbyflips(), restart(), tetgenmesh::restorecavity(), tetgenmesh::scarveholes(), tetgenmesh::scoutcrossedge(), tetgenmesh::sinsertvertex(), tetgenmesh::smoothpoint(), tetgenmesh::splitsubface(), tetgenmesh::splittetrahedron(), tetgenmesh::sremovevertex(), tetgenmesh::suppressbdrysteinerpoint(), tetgenmesh::suppresssteinerpoints(), tetrahedralize(), and tetgenmesh::triangulate().
int tetgenmesh::arraypool::objectsperblock
Definition at line 985 of file tetgen.h.
View newest version in sPHENIX GitHub at line 985 of file tetgen.h
int tetgenmesh::arraypool::objectsperblockmark
Definition at line 987 of file tetgen.h.
View newest version in sPHENIX GitHub at line 987 of file tetgen.h
char** tetgenmesh::arraypool::toparray
Definition at line 989 of file tetgen.h.
View newest version in sPHENIX GitHub at line 989 of file tetgen.h
int tetgenmesh::arraypool::toparraylen
Definition at line 988 of file tetgen.h.
View newest version in sPHENIX GitHub at line 988 of file tetgen.h
unsigned long tetgenmesh::arraypool::totalmemory
Definition at line 991 of file tetgen.h.
View newest version in sPHENIX GitHub at line 991 of file tetgen.h
Referenced by tetgenmesh::constrainedfacets(), tetgenmesh::memorystatistics(), and tetgenmesh::recoverboundary().
The documentation for this class was generated from the following files:
EicRoot/blob/master/eic/cad/tetgen/tetgen.h
EicRoot/blob/master/eic/cad/tetgen/tetgen.cxx