EIC Software: PndConstField Class Reference
PndConstField Class Reference
#include <EicRoot/blob/master/field/PndConstField.h>
Public Member Functions
PndConstField ()
PndConstField (const char *name, Double_t xMin, Double_t xMax, Double_t yMin, Double_t yMax, Double_t zMin, Double_t zMax, Double_t bX, Double_t bY, Double_t bZ)
PndConstField (PndConstPar *fieldPar)
virtual ~PndConstField ()
void FillParContainer ()
void SetFieldRegion (Double_t xMin, Double_t xMax, Double_t yMin, Double_t yMax, Double_t zMin, Double_t zMax)
void SetField (Double_t bX, Double_t bY, Double_t bZ)
virtual Double_t GetBx (Double_t x, Double_t y, Double_t z)
virtual Double_t GetBy (Double_t x, Double_t y, Double_t z)
virtual Double_t GetBz (Double_t x, Double_t y, Double_t z)
virtual void GetBxyz (const Double_t point[3], Double_t *bField)
Double_t GetXmin () const
Double_t GetXmax () const
Double_t GetYmin () const
Double_t GetYmax () const
Double_t GetZmin () const
Double_t GetZmax () const
Double_t GetBx () const
Double_t GetBy () const
Double_t GetBz () const
virtual void Print ()
ClassDef (PndConstField, 1)
Private Attributes
Double_t fXmin
Double_t fXmax
Double_t fYmin
Double_t fYmax
Double_t fZmin
Double_t fZmax
Double_t fBx
Double_t fBy
Double_t fBz
Detailed Description
Definition at line 19 of file PndConstField.h.
View newest version in sPHENIX GitHub at line 19 of file PndConstField.h
Constructor & Destructor Documentation
PndConstField::PndConstField ()
Default constructor
Definition at line 22 of file PndConstField.cxx.
View newest version in sPHENIX GitHub at line 22 of file PndConstField.cxx
PndConstField::PndConstField (const char * name, Double_t xMin, Double_t xMax, Double_t yMin, Double_t yMax, Double_t zMin, Double_t zMax, Double_t bX, Double_t bY, Double_t bZ)
Standard constructor
Parameters
name Object name
xMin,xMax x region of field (global coordinates)
yMin,yMax y region of field (global coordinates)
zMin,zMax z region of field (global coordinates)
bX,bY,bZ Field values [kG]
Definition at line 40 of file PndConstField.cxx.
View newest version in sPHENIX GitHub at line 40 of file PndConstField.cxx
PndConstField::PndConstField (PndConstPar * fieldPar)
Constructor from PndFieldPar
Definition at line 64 of file PndConstField.cxx.
View newest version in sPHENIX GitHub at line 64 of file PndConstField.cxx
References fBx, fBy, fBz, fXmax, fXmin, fYmax, fYmin, fZmax, fZmin, PndConstPar::GetBx(), PndConstPar::GetBy(), PndConstPar::GetBz(), PndMapPar::GetType(), PndMapPar::GetXmax(), PndMapPar::GetXmin(), PndMapPar::GetYmax(), PndMapPar::GetYmin(), PndMapPar::GetZmax(), and PndMapPar::GetZmin().
PndConstField::~PndConstField () virtual
Destructor
Definition at line 98 of file PndConstField.cxx.
View newest version in sPHENIX GitHub at line 98 of file PndConstField.cxx
Member Function Documentation
PndConstField::ClassDef (PndConstField , 1)
void PndConstField::FillParContainer ()
Definition at line 196 of file PndConstField.cxx.
View newest version in sPHENIX GitHub at line 196 of file PndConstField.cxx
References FairRuntimeDb::getContainer(), FairRun::GetRunId(), FairRun::GetRuntimeDb(), FairRun::Instance(), FairParSet::setChanged(), FairParSet::setInputVersion(), and PndConstPar::SetParameters().
Double_t PndConstField::GetBx (Double_t x, Double_t y, Double_t z) virtual
Get X component of field at a given point
Parameters
x,y,z Point coordinates [cm]
Definition at line 129 of file PndConstField.cxx.
View newest version in sPHENIX GitHub at line 129 of file PndConstField.cxx
References fBx, fXmax, fYmax, and fZmax.
Referenced by PndFieldPar::SetParameters(), and PndConstPar::SetParameters().
Double_t PndConstField::GetBx () const inline
Accessors to field values
Definition at line 95 of file PndConstField.h.
View newest version in sPHENIX GitHub at line 95 of file PndConstField.h
References fBx.
void PndConstField::GetBxyz (const Double_t point[3], Double_t * bField) virtual
Get all components of field at a given point
Parameters
x,y,z Point coordinates [cm]
Definition at line 160 of file PndConstField.cxx.
View newest version in sPHENIX GitHub at line 160 of file PndConstField.cxx
References fBx, fBy, fBz, fXmax, fXmin, fYmax, fYmin, fZmax, and fZmin.
Double_t PndConstField::GetBy (Double_t x, Double_t y, Double_t z) virtual
Get Y component of field at a given point
Parameters
x,y,z Point coordinates [cm]
Definition at line 140 of file PndConstField.cxx.
View newest version in sPHENIX GitHub at line 140 of file PndConstField.cxx
References fBy, fXmax, fYmax, and fZmax.
Referenced by PndFieldPar::SetParameters(), and PndConstPar::SetParameters().
Double_t PndConstField::GetBy () const inline
Definition at line 96 of file PndConstField.h.
View newest version in sPHENIX GitHub at line 96 of file PndConstField.h
References fBy.
Double_t PndConstField::GetBz (Double_t x, Double_t y, Double_t z) virtual
Get Z component of field at a given point
Parameters
x,y,z Point coordinates [cm]
Definition at line 151 of file PndConstField.cxx.
View newest version in sPHENIX GitHub at line 151 of file PndConstField.cxx
References fBz, fXmax, fYmax, and fZmax.
Referenced by PndFieldPar::SetParameters(), and PndConstPar::SetParameters().
Double_t PndConstField::GetBz () const inline
Definition at line 97 of file PndConstField.h.
View newest version in sPHENIX GitHub at line 97 of file PndConstField.h
References fBz.
Double_t PndConstField::GetXmax () const inline
Definition at line 87 of file PndConstField.h.
View newest version in sPHENIX GitHub at line 87 of file PndConstField.h
References fXmax.
Referenced by PndFieldPar::SetParameters(), and PndConstPar::SetParameters().
Double_t PndConstField::GetXmin () const inline
Accessors to field region
Definition at line 86 of file PndConstField.h.
View newest version in sPHENIX GitHub at line 86 of file PndConstField.h
References fXmin.
Referenced by PndFieldPar::SetParameters(), and PndConstPar::SetParameters().
Double_t PndConstField::GetYmax () const inline
Definition at line 89 of file PndConstField.h.
View newest version in sPHENIX GitHub at line 89 of file PndConstField.h
References fYmax.
Referenced by PndFieldPar::SetParameters(), and PndConstPar::SetParameters().
Double_t PndConstField::GetYmin () const inline
Definition at line 88 of file PndConstField.h.
View newest version in sPHENIX GitHub at line 88 of file PndConstField.h
References fYmin.
Referenced by PndFieldPar::SetParameters(), and PndConstPar::SetParameters().
Double_t PndConstField::GetZmax () const inline
Definition at line 91 of file PndConstField.h.
View newest version in sPHENIX GitHub at line 91 of file PndConstField.h
References fZmax.
Referenced by PndMultiField::Init(), PndFieldPar::SetParameters(), and PndConstPar::SetParameters().
Double_t PndConstField::GetZmin () const inline
Definition at line 90 of file PndConstField.h.
View newest version in sPHENIX GitHub at line 90 of file PndConstField.h
References fZmin.
Referenced by PndMultiField::Init(), PndFieldPar::SetParameters(), and PndConstPar::SetParameters().
void PndConstField::Print () virtual
Screen output
Definition at line 176 of file PndConstField.cxx.
View newest version in sPHENIX GitHub at line 176 of file PndConstField.cxx
References fBx, fBy, fBz, fXmax, fXmin, fYmax, fYmin, fZmax, and fZmin.
void PndConstField::SetField (Double_t bX, Double_t bY, Double_t bZ)
Set the field values
Parameters
bX,bY,bZ Field values [kG]
Definition at line 119 of file PndConstField.cxx.
View newest version in sPHENIX GitHub at line 119 of file PndConstField.cxx
References fBx, fBy, and fBz.
void PndConstField::SetFieldRegion (Double_t xMin, Double_t xMax, Double_t yMin, Double_t yMax, Double_t zMin, Double_t zMax)
Set the field region
Parameters
xMin,xMax x region of field (global coordinates)
yMin,yMax y region of field (global coordinates)
zMin,zMax z region of field (global coordinates)
Definition at line 104 of file PndConstField.cxx.
View newest version in sPHENIX GitHub at line 104 of file PndConstField.cxx
References fXmax, fXmin, fYmax, fYmin, fZmax, and fZmin.
Member Data Documentation
Double_t PndConstField::fBx private
Field components inside the field region
Definition at line 116 of file PndConstField.h.
View newest version in sPHENIX GitHub at line 116 of file PndConstField.h
Referenced by GetBx(), GetBxyz(), PndConstField(), Print(), and SetField().
Double_t PndConstField::fBy private
Definition at line 117 of file PndConstField.h.
View newest version in sPHENIX GitHub at line 117 of file PndConstField.h
Referenced by GetBxyz(), GetBy(), PndConstField(), Print(), and SetField().
Double_t PndConstField::fBz private
Definition at line 118 of file PndConstField.h.
View newest version in sPHENIX GitHub at line 118 of file PndConstField.h
Referenced by GetBxyz(), GetBz(), PndConstField(), Print(), and SetField().
Double_t PndConstField::fXmax private
Definition at line 109 of file PndConstField.h.
View newest version in sPHENIX GitHub at line 109 of file PndConstField.h
Referenced by GetBx(), GetBxyz(), GetBy(), GetBz(), GetXmax(), PndConstField(), Print(), and SetFieldRegion().
Double_t PndConstField::fXmin private
Limits of the field region
Definition at line 108 of file PndConstField.h.
View newest version in sPHENIX GitHub at line 108 of file PndConstField.h
Referenced by GetBxyz(), GetXmin(), PndConstField(), Print(), and SetFieldRegion().
Double_t PndConstField::fYmax private
Definition at line 111 of file PndConstField.h.
View newest version in sPHENIX GitHub at line 111 of file PndConstField.h
Referenced by GetBx(), GetBxyz(), GetBy(), GetBz(), GetYmax(), PndConstField(), Print(), and SetFieldRegion().
Double_t PndConstField::fYmin private
Definition at line 110 of file PndConstField.h.
View newest version in sPHENIX GitHub at line 110 of file PndConstField.h
Referenced by GetBxyz(), GetYmin(), PndConstField(), Print(), and SetFieldRegion().
Double_t PndConstField::fZmax private
Definition at line 113 of file PndConstField.h.
View newest version in sPHENIX GitHub at line 113 of file PndConstField.h
Referenced by GetBx(), GetBxyz(), GetBy(), GetBz(), GetZmax(), PndConstField(), Print(), and SetFieldRegion().
Double_t PndConstField::fZmin private
Definition at line 112 of file PndConstField.h.
View newest version in sPHENIX GitHub at line 112 of file PndConstField.h
Referenced by GetBxyz(), GetZmin(), PndConstField(), Print(), and SetFieldRegion().
The documentation for this class was generated from the following files:
EicRoot/blob/master/field/PndConstField.h
EicRoot/blob/master/field/PndConstField.cxx