EIC Software: NaiveTrackParameterization Class Reference
NaiveTrackParameterization Class Reference
#include <EicRoot/blob/master/pnddata/TrackData/PndTrack.h>
Public Member Functions
NaiveTrackParameterization (bool valid=false)
~NaiveTrackParameterization ()
bool IsValid (void) const
TVector3 GetMoCaPosition (void) const
TVector3 GetMoCaMomentum (void) const
TVector3 GetRecoPosition (void) const
TVector3 GetRecoMomentum (void) const
double DistanceToPlane (const TVector3 &x0, const TVector3 &n0) const
void SetValid (void)
void SetMoCaPosition (const TVector3 &position)
void SetMoCaMomentum (const TVector3 &momentum)
void SetRecoPosition (const TVector3 &position)
void SetRecoMomentum (const TVector3 &momentum)
Private Member Functions
ClassDef (NaiveTrackParameterization, 1)
Private Attributes
bool mValid
TVector3 mMoCaPosition
TVector3 mMoCaMomentum
TVector3 mRecoPosition
TVector3 mRecoMomentum
Detailed Description
Definition at line 18 of file PndTrack.h.
View newest version in sPHENIX GitHub at line 18 of file PndTrack.h
Constructor & Destructor Documentation
NaiveTrackParameterization::NaiveTrackParameterization (bool valid = false) inline
Definition at line 21 of file PndTrack.h.
View newest version in sPHENIX GitHub at line 21 of file PndTrack.h
NaiveTrackParameterization::~NaiveTrackParameterization () inline
Definition at line 22 of file PndTrack.h.
View newest version in sPHENIX GitHub at line 22 of file PndTrack.h
Member Function Documentation
NaiveTrackParameterization::ClassDef (NaiveTrackParameterization , 1) private
double NaiveTrackParameterization::DistanceToPlane (const TVector3 & x0, const TVector3 & n0) const inline
Definition at line 30 of file PndTrack.h.
View newest version in sPHENIX GitHub at line 30 of file PndTrack.h
References mMoCaPosition.
Referenced by PndPidCandidate::GetNearestParameterization(), and stvector().
TVector3 NaiveTrackParameterization::GetMoCaMomentum (void) const inline
Definition at line 26 of file PndTrack.h.
View newest version in sPHENIX GitHub at line 26 of file PndTrack.h
References mMoCaMomentum.
Referenced by stvector().
TVector3 NaiveTrackParameterization::GetMoCaPosition (void) const inline
Definition at line 25 of file PndTrack.h.
View newest version in sPHENIX GitHub at line 25 of file PndTrack.h
References mMoCaPosition.
Referenced by PndPidCandidate::GetNearestParameterization(), and stvector().
TVector3 NaiveTrackParameterization::GetRecoMomentum (void) const inline
Definition at line 28 of file PndTrack.h.
View newest version in sPHENIX GitHub at line 28 of file PndTrack.h
References mRecoMomentum.
Referenced by stvector().
TVector3 NaiveTrackParameterization::GetRecoPosition (void) const inline
Definition at line 27 of file PndTrack.h.
View newest version in sPHENIX GitHub at line 27 of file PndTrack.h
References mRecoPosition.
Referenced by stvector().
bool NaiveTrackParameterization::IsValid (void) const inline
Definition at line 24 of file PndTrack.h.
View newest version in sPHENIX GitHub at line 24 of file PndTrack.h
References mValid.
void NaiveTrackParameterization::SetMoCaMomentum (const TVector3 & momentum) inline
Definition at line 37 of file PndTrack.h.
View newest version in sPHENIX GitHub at line 37 of file PndTrack.h
References mMoCaMomentum, and momentum.
Referenced by PndRecoKalmanFit::Fit().
void NaiveTrackParameterization::SetMoCaPosition (const TVector3 & position) inline
Definition at line 36 of file PndTrack.h.
View newest version in sPHENIX GitHub at line 36 of file PndTrack.h
References mMoCaPosition, and Acts::VectorHelpers::position().
Referenced by PndRecoKalmanFit::Fit().
void NaiveTrackParameterization::SetRecoMomentum (const TVector3 & momentum) inline
Definition at line 39 of file PndTrack.h.
View newest version in sPHENIX GitHub at line 39 of file PndTrack.h
References momentum, and mRecoMomentum.
Referenced by PndRecoKalmanFit::Fit().
void NaiveTrackParameterization::SetRecoPosition (const TVector3 & position) inline
Definition at line 38 of file PndTrack.h.
View newest version in sPHENIX GitHub at line 38 of file PndTrack.h
References mRecoPosition, and Acts::VectorHelpers::position().
Referenced by PndRecoKalmanFit::Fit().
void NaiveTrackParameterization::SetValid (void) inline
Definition at line 35 of file PndTrack.h.
View newest version in sPHENIX GitHub at line 35 of file PndTrack.h
References mValid.
Member Data Documentation
TVector3 NaiveTrackParameterization::mMoCaMomentum private
Definition at line 45 of file PndTrack.h.
View newest version in sPHENIX GitHub at line 45 of file PndTrack.h
Referenced by GetMoCaMomentum(), and SetMoCaMomentum().
TVector3 NaiveTrackParameterization::mMoCaPosition private
Definition at line 45 of file PndTrack.h.
View newest version in sPHENIX GitHub at line 45 of file PndTrack.h
Referenced by DistanceToPlane(), GetMoCaPosition(), and SetMoCaPosition().
TVector3 NaiveTrackParameterization::mRecoMomentum private
Definition at line 45 of file PndTrack.h.
View newest version in sPHENIX GitHub at line 45 of file PndTrack.h
Referenced by GetRecoMomentum(), and SetRecoMomentum().
TVector3 NaiveTrackParameterization::mRecoPosition private
Definition at line 45 of file PndTrack.h.
View newest version in sPHENIX GitHub at line 45 of file PndTrack.h
Referenced by GetRecoPosition(), and SetRecoPosition().
bool NaiveTrackParameterization::mValid private
Definition at line 39 of file PndTrack.h.
View newest version in sPHENIX GitHub at line 39 of file PndTrack.h
Referenced by IsValid(), and SetValid().
The documentation for this class was generated from the following file:
EicRoot/blob/master/pnddata/TrackData/PndTrack.h