EIC Software: GFException Class Reference
GFException Class Reference
Genfit
Exception class for error handling in GENFIT (provides storage for diagnostic information)
#include <EicRoot/blob/master/genfit/GFException.h>
Public Member Functions
GFException (std::string, int, std::string)
Initializing constructor.
virtual ~GFException () throw ()
void setFatal (bool b=true)
set fatal flag. if this is true, the fit stops for this current track repr.
bool isFatal ()
get fatal flag.
void setNumbers (std::string, const std::vector< double > &)
set list of numbers with description
void setMatrices (std::string, const std::vector< TMatrixT< double > > &)
set list of matrices with description
void info ()
print information in the exception object
virtual const char * what () const throw ()
standard error message handling for exceptions. use like "std::cerr << e.what();"
std::string getExcString ()
Static Public Member Functions
static void quiet (bool b=true)
Private Attributes
std::string fExcString
int fLine
std::string fFile
std::string fErrorMessage
std::string fNumbersLabel
std::string fMatricesLabel
std::vector< double > fNumbers
std::vector< TMatrixT< double > > fMatrices
bool fFatal
Static Private Attributes
static bool fQuiet = false
Detailed Description
Exception class for error handling in GENFIT (provides storage for diagnostic information)
Author
Christian Höppner (Technische Universität München, original author)
Sebastian Neubert (Technische Universität München, original author)
This is the class that is used for all error handling in GENFIT. It is a utility class that allows to store numbers and matrices together with an error string. The exception class can then be thrown when an error is detected and the C++ exception handling facilities can be used to catch and process the exception.
Definition at line 45 of file GFException.h.
View newest version in sPHENIX GitHub at line 45 of file GFException.h
Constructor & Destructor Documentation
GFException::GFException (std::string _excString, int _line, std::string _file)
Initializing constructor.
Parameters
what error message
line line at which the exception is created. Can be set through LINE macro
file sorcefile in which the exception is created. Can be set through FILE macro
Definition at line 23 of file GFException.cxx.
View newest version in sPHENIX GitHub at line 23 of file GFException.cxx
References fErrorMessage, fExcString, fFatal, fFile, and fLine.
GFException::~GFException () throw () virtual
Definition at line 32 of file GFException.cxx.
View newest version in sPHENIX GitHub at line 32 of file GFException.cxx
Member Function Documentation
std::string GFException::getExcString () inline
Definition at line 91 of file GFException.h.
View newest version in sPHENIX GitHub at line 91 of file GFException.h
References fExcString.
void GFException::info ()
print information in the exception object
Definition at line 52 of file GFException.cxx.
View newest version in sPHENIX GitHub at line 52 of file GFException.cxx
References fMatrices, fMatricesLabel, fNumbers, fNumbersLabel, and fQuiet.
Referenced by GFDaf::calcWeights(), GFKalman::fittingPass(), and GFDaf::processTrack().
bool GFException::isFatal () inline
get fatal flag.
Definition at line 79 of file GFException.h.
View newest version in sPHENIX GitHub at line 79 of file GFException.h
References fFatal.
Referenced by GFKalman::fittingPass().
static void GFException::quiet (bool b = true) inline static
Definition at line 93 of file GFException.h.
View newest version in sPHENIX GitHub at line 93 of file GFException.h
References fQuiet.
Referenced by PndRecoDafFit::Init(), and PndRecoKalmanFit::Init().
void GFException::setFatal (bool b = true) inline
set fatal flag. if this is true, the fit stops for this current track repr.
Definition at line 77 of file GFException.h.
View newest version in sPHENIX GitHub at line 77 of file GFException.h
References fFatal.
Referenced by GFRecoHitFactory::addProducer(), GFKalman::chi2Increment(), GFRecoHitFactory::createOne(), RKTrackRep::Extrap(), GeaneTrackRep::extrapolate(), GeaneTrackRep::extrapolateToLine(), GeaneTrackRep::extrapolateToPoint(), GeaneTrackRep::getPocaOnLine(), GFTools::invertMatrix(), GFRecoHitProducer< hit_T, recoHit_T >::produce(), RKTrackRep::RKutta(), GFMaterialEffects::setMscModel(), and GFDaf::setProbCut().
void GFException::setMatrices (std::string _matricesLabel, const std::vector< TMatrixT< double > > & _matrices)
set list of matrices with description
Definition at line 41 of file GFException.cxx.
View newest version in sPHENIX GitHub at line 41 of file GFException.cxx
References fMatrices, and fMatricesLabel.
Referenced by GFKalman::chi2Increment().
void GFException::setNumbers (std::string _numbersLabel, const std::vector< double > & _numbers)
set list of numbers with description
Definition at line 35 of file GFException.cxx.
View newest version in sPHENIX GitHub at line 35 of file GFException.cxx
References fNumbers, and fNumbersLabel.
Referenced by GFRecoHitFactory::addProducer(), and GFRecoHitFactory::createOne().
const char * GFException::what () const throw () virtual
standard error message handling for exceptions. use like "std::cerr << e.what();"
Definition at line 47 of file GFException.cxx.
View newest version in sPHENIX GitHub at line 47 of file GFException.cxx
References fErrorMessage, and fQuiet.
Referenced by GFDaf::calcWeights(), PndGFTrackToPndTrackConvertorTask::Exec(), PrimSelector::Exec(), PndRecoKalmanFit::Fit(), PndRecoDafFit::Fit(), GFKalman::fittingPass(), GenfitTrack2PndTrack(), and GFDaf::processTrack().
Member Data Documentation
std::string GFException::fErrorMessage private
Definition at line 55 of file GFException.h.
View newest version in sPHENIX GitHub at line 55 of file GFException.h
Referenced by GFException(), and what().
std::string GFException::fExcString private
Definition at line 51 of file GFException.h.
View newest version in sPHENIX GitHub at line 51 of file GFException.h
Referenced by getExcString(), and GFException().
bool GFException::fFatal private
Definition at line 62 of file GFException.h.
View newest version in sPHENIX GitHub at line 62 of file GFException.h
Referenced by GFException(), isFatal(), and setFatal().
std::string GFException::fFile private
Definition at line 53 of file GFException.h.
View newest version in sPHENIX GitHub at line 53 of file GFException.h
Referenced by GFException().
int GFException::fLine private
Definition at line 52 of file GFException.h.
View newest version in sPHENIX GitHub at line 52 of file GFException.h
Referenced by GFException().
std::vector< TMatrixT<double> > GFException::fMatrices private
Definition at line 60 of file GFException.h.
View newest version in sPHENIX GitHub at line 60 of file GFException.h
Referenced by info(), and setMatrices().
std::string GFException::fMatricesLabel private
Definition at line 58 of file GFException.h.
View newest version in sPHENIX GitHub at line 58 of file GFException.h
Referenced by info(), and setMatrices().
std::vector<double> GFException::fNumbers private
Definition at line 59 of file GFException.h.
View newest version in sPHENIX GitHub at line 59 of file GFException.h
Referenced by info(), and setNumbers().
std::string GFException::fNumbersLabel private
Definition at line 57 of file GFException.h.
View newest version in sPHENIX GitHub at line 57 of file GFException.h
Referenced by info(), and setNumbers().
bool GFException::fQuiet = false static private
Definition at line 49 of file GFException.h.
View newest version in sPHENIX GitHub at line 49 of file GFException.h
Referenced by info(), quiet(), and what().
The documentation for this class was generated from the following files:
EicRoot/blob/master/genfit/GFException.h
EicRoot/blob/master/genfit/GFException.cxx