EIC Software: erhic::Forester::Status Class Reference
erhic::Forester::Status Class Reference
#include <eic-smear/blob/master/include/eicsmear/erhic/Forester.h>
Public Member Functions
Status ()
virtual ~Status ()
virtual std::ostream & Print (std::ostream &os=std::cout) const
Protected Member Functions
virtual void StartTimer ()
virtual void StopTimer ()
virtual void ModifyEventCount (Long64_t count)
virtual void ModifyParticleCount (Long64_t count)
ClassDef (Status, 1)
Protected Attributes
time_t mStartTime
time_t mEndTime
Long64_t mNEvents
Long64_t mNParticles
TStopwatch mTimer
Friends
class Forester
Detailed Description
Stores summary information about the last call to Forester::Plant(). KK: Made public for rootcint
Definition at line 154 of file Forester.h.
View newest version in sPHENIX GitHub at line 154 of file Forester.h
Constructor & Destructor Documentation
erhic::Forester::Status::Status ()
Definition at line 275 of file Forester.cxx.
View newest version in sPHENIX GitHub at line 275 of file Forester.cxx
References mEndTime, mStartTime, mTimer, and Acts::Test::time.
erhic::Forester::Status::~Status () virtual
Definition at line 285 of file Forester.cxx.
View newest version in sPHENIX GitHub at line 285 of file Forester.cxx
Member Function Documentation
erhic::Forester::Status::ClassDef (Status , 1) protected
void erhic::Forester::Status::ModifyEventCount (Long64_t count) protected virtual
Definition at line 309 of file Forester.cxx.
View newest version in sPHENIX GitHub at line 309 of file Forester.cxx
Referenced by erhic::Forester::Plant().
void erhic::Forester::Status::ModifyParticleCount (Long64_t count) protected virtual
Definition at line 313 of file Forester.cxx.
View newest version in sPHENIX GitHub at line 313 of file Forester.cxx
Referenced by erhic::Forester::Plant().
std::ostream & erhic::Forester::Status::Print (std::ostream & os = std::cout) const virtual
Definition at line 287 of file Forester.cxx.
View newest version in sPHENIX GitHub at line 287 of file Forester.cxx
Referenced by erhic::Forester::Finish().
void erhic::Forester::Status::StartTimer () protected virtual
Definition at line 299 of file Forester.cxx.
View newest version in sPHENIX GitHub at line 299 of file Forester.cxx
References Acts::Test::time.
Referenced by erhic::Forester::SetupOutput().
void erhic::Forester::Status::StopTimer () protected virtual
Definition at line 304 of file Forester.cxx.
View newest version in sPHENIX GitHub at line 304 of file Forester.cxx
References Acts::Test::time.
Referenced by erhic::Forester::Finish().
Friends And Related Function Documentation
friend class Forester friend
Definition at line 174 of file Forester.h.
View newest version in sPHENIX GitHub at line 174 of file Forester.h
Member Data Documentation
time_t erhic::Forester::Status::mEndTime protected
Definition at line 167 of file Forester.h.
View newest version in sPHENIX GitHub at line 167 of file Forester.h
Referenced by Status().
Long64_t erhic::Forester::Status::mNEvents protected
Definition at line 168 of file Forester.h.
View newest version in sPHENIX GitHub at line 168 of file Forester.h
Long64_t erhic::Forester::Status::mNParticles protected
Definition at line 169 of file Forester.h.
View newest version in sPHENIX GitHub at line 169 of file Forester.h
time_t erhic::Forester::Status::mStartTime protected
Definition at line 166 of file Forester.h.
View newest version in sPHENIX GitHub at line 166 of file Forester.h
Referenced by Status().
TStopwatch erhic::Forester::Status::mTimer mutable protected
Definition at line 172 of file Forester.h.
View newest version in sPHENIX GitHub at line 172 of file Forester.h
Referenced by Status().
The documentation for this class was generated from the following files:
eic-smear/blob/master/include/eicsmear/erhic/Forester.h
eic-smear/blob/master/src/erhic/Forester.cxx