EIC Software: EICG4B0ECALDetector Class Reference
EICG4B0ECALDetector Class Reference
#include <fun4all_eicdetectors/blob/master/simulation/g4simulation/g4b0ecal/EICG4B0ECALDetector.h>
Classes
struct towerposition
Public Member Functions
EICG4B0ECALDetector (PHG4Subsystem *subsys, PHCompositeNode *Node, PHParameters *parameters, const std::string &dnam, const int layer=0)
constructor
virtual ~EICG4B0ECALDetector () override
destructor
virtual void ConstructMe (G4LogicalVolume *world) override
construct
void Print (const std::string &what="ALL") const override
int GetDetId (G4VPhysicalVolume *) const
void SuperDetector (const std::string &name)
const std::string SuperDetector () const
int get_Layer () const
PHParameters * getParams ()
void SetTowerMappingFile (const std::string &filename)
volume accessors
int IsInDetector (G4VPhysicalVolume *) const
Public Member Functions inherited from PHG4Detector
PHG4Detector ()=delete
constructor
PHG4Detector (PHG4Subsystem *subsys, PHCompositeNode *Node, const std::string &nam)
virtual ~PHG4Detector (void)
destructor
virtual void Construct (G4LogicalVolume *world) final
construct method
virtual void PostConstruction ()
Optional PostConstruction call after all geometry is constructed.
virtual void Verbosity (const int v)
virtual int Verbosity () const
virtual G4UserSteppingAction * GetSteppingAction ()
virtual std::string GetName () const
virtual void OverlapCheck (const bool chk)
virtual bool OverlapCheck () const
virtual int DisplayVolume (G4VSolid *volume, G4LogicalVolume *logvol, G4RotationMatrix *rotm=nullptr)
virtual int DisplayVolume (G4LogicalVolume *checksolid, G4LogicalVolume *logvol, G4RotationMatrix *rotm=nullptr)
virtual PHCompositeNode * topNode ()
virtual PHG4Subsystem * GetMySubsystem ()
Protected Member Functions
void LogicalVolSetInsert (G4LogicalVolume *logvol)
Private Member Functions
G4LogicalVolume * ConstructTower ()
int PlaceTower (G4LogicalVolume *envelope, G4LogicalVolume *tower)
int ParseParametersFromTable ()
Private Attributes
std::map< std::string,
towerposition > m_TowerPositionMap
PHParameters * m_Params
std::set< G4VPhysicalVolume * > m_PhysicalVolumesSet
std::map< G4VPhysicalVolume
*, int > m_PhysicalVolumesDet
std::set< G4LogicalVolume * > m_LogicalVolSet
int m_Layer
std::string m_SuperDetector
std::string _mapping_tower_file
std::string m_TowerLogicNamePrefix
Additional Inherited Members
Static Public Member Functions inherited from PHG4Detector
static G4Material * GetDetectorMaterial (const std::string &name, const bool quit=true)
static G4Element * GetDetectorElement (const std::string &name, const bool quit=true)
Detailed Description
Definition at line 19 of file EICG4B0ECALDetector.h.
View newest version in sPHENIX GitHub at line 19 of file EICG4B0ECALDetector.h
Constructor & Destructor Documentation
EICG4B0ECALDetector::EICG4B0ECALDetector (PHG4Subsystem * subsys, PHCompositeNode * Node, PHParameters * parameters, const std::string & dnam, const int layer = 0)
constructor
Definition at line 63 of file EICG4B0ECALDetector.cc.
View newest version in sPHENIX GitHub at line 63 of file EICG4B0ECALDetector.cc
virtual EICG4B0ECALDetector::~EICG4B0ECALDetector () inline override virtual
destructor
Definition at line 26 of file EICG4B0ECALDetector.h.
View newest version in sPHENIX GitHub at line 26 of file EICG4B0ECALDetector.h
Member Function Documentation
void EICG4B0ECALDetector::ConstructMe (G4LogicalVolume * world) override virtual
construct
Implements PHG4Detector.
Definition at line 96 of file EICG4B0ECALDetector.cc.
View newest version in sPHENIX GitHub at line 96 of file EICG4B0ECALDetector.cc
References _mapping_tower_file, Acts::UnitConstants::cm, ConstructTower(), Acts::UnitConstants::degree, PHParameters::get_double_param(), PHParameters::get_string_param(), PHFlag::get_StringFlag(), PHG4Detector::GetDetectorMaterial(), recoConsts::instance(), m_Params, m_PhysicalVolumesDet, m_PhysicalVolumesSet, m_TowerLogicNamePrefix, PHG4Detector::OverlapCheck(), ParseParametersFromTable(), PlaceTower(), PHG4Detector::Verbosity(), and G4WORLD::WorldMaterial.
G4LogicalVolume * EICG4B0ECALDetector::ConstructTower () private
Definition at line 190 of file EICG4B0ECALDetector.cc.
View newest version in sPHENIX GitHub at line 190 of file EICG4B0ECALDetector.cc
References Acts::UnitConstants::cm, PHParameters::get_double_param(), PHParameters::get_string_param(), PHG4Detector::GetDetectorMaterial(), m_LogicalVolSet, m_Params, and PHG4Detector::Verbosity().
Referenced by ConstructMe().
int EICG4B0ECALDetector::get_Layer () const inline
Definition at line 42 of file EICG4B0ECALDetector.h.
View newest version in sPHENIX GitHub at line 42 of file EICG4B0ECALDetector.h
References m_Layer.
Referenced by EICG4B0ECALSteppingAction::UserSteppingAction().
int EICG4B0ECALDetector::GetDetId (G4VPhysicalVolume * volume) const
Definition at line 86 of file EICG4B0ECALDetector.cc.
View newest version in sPHENIX GitHub at line 86 of file EICG4B0ECALDetector.cc
References IsInDetector().
PHParameters * EICG4B0ECALDetector::getParams ()
Definition at line 357 of file EICG4B0ECALDetector.cc.
View newest version in sPHENIX GitHub at line 357 of file EICG4B0ECALDetector.cc
References m_Params.
int EICG4B0ECALDetector::IsInDetector (G4VPhysicalVolume * volume) const
Definition at line 76 of file EICG4B0ECALDetector.cc.
View newest version in sPHENIX GitHub at line 76 of file EICG4B0ECALDetector.cc
References m_LogicalVolSet.
Referenced by GetDetId(), and EICG4B0ECALSteppingAction::UserSteppingAction().
void EICG4B0ECALDetector::LogicalVolSetInsert (G4LogicalVolume * logvol) inline protected
Definition at line 80 of file EICG4B0ECALDetector.h.
View newest version in sPHENIX GitHub at line 80 of file EICG4B0ECALDetector.h
References m_LogicalVolSet.
int EICG4B0ECALDetector::ParseParametersFromTable () private
Definition at line 248 of file EICG4B0ECALDetector.cc.
View newest version in sPHENIX GitHub at line 248 of file EICG4B0ECALDetector.cc
References _mapping_tower_file, Acts::UnitConstants::cm, PHParameters::get_double_param(), getline, EICG4B0ECALDetector::towerposition::idx_j, EICG4B0ECALDetector::towerposition::idx_k, m_Params, m_TowerLogicNamePrefix, m_TowerPositionMap, G4CTD::size_z, PHG4Detector::Verbosity(), EICG4B0ECALDetector::towerposition::x, EICG4B0ECALDetector::towerposition::y, and EICG4B0ECALDetector::towerposition::z.
Referenced by ConstructMe().
int EICG4B0ECALDetector::PlaceTower (G4LogicalVolume * envelope, G4LogicalVolume * tower) private
Definition at line 224 of file EICG4B0ECALDetector.cc.
View newest version in sPHENIX GitHub at line 224 of file EICG4B0ECALDetector.cc
References Acts::UnitConstants::cm, m_TowerPositionMap, PHG4Detector::OverlapCheck(), and PHG4Detector::Verbosity().
Referenced by ConstructMe().
void EICG4B0ECALDetector::Print (const std::string & what = "ALL") const override virtual
Reimplemented from PHG4Detector.
Definition at line 345 of file EICG4B0ECALDetector.cc.
View newest version in sPHENIX GitHub at line 345 of file EICG4B0ECALDetector.cc
References m_Params, and PHParameters::Print().
Referenced by EICG4B0ECALSubsystem::Print().
void EICG4B0ECALDetector::SetTowerMappingFile (const std::string & filename) inline
Definition at line 44 of file EICG4B0ECALDetector.h.
View newest version in sPHENIX GitHub at line 44 of file EICG4B0ECALDetector.h
References _mapping_tower_file, and INPUTHEPMC::filename.
Referenced by EICG4B0ECALSubsystem::InitRunSubsystem().
void EICG4B0ECALDetector::SuperDetector (const std::string & name) inline
Definition at line 40 of file EICG4B0ECALDetector.h.
View newest version in sPHENIX GitHub at line 40 of file EICG4B0ECALDetector.h
References m_SuperDetector, and name.
Referenced by EICG4B0ECALSubsystem::InitRunSubsystem(), and EICG4B0ECALSteppingAction::UserSteppingAction().
const std::string EICG4B0ECALDetector::SuperDetector () const inline
Definition at line 41 of file EICG4B0ECALDetector.h.
View newest version in sPHENIX GitHub at line 41 of file EICG4B0ECALDetector.h
References m_SuperDetector.
Member Data Documentation
std::string EICG4B0ECALDetector::_mapping_tower_file private
Definition at line 76 of file EICG4B0ECALDetector.h.
View newest version in sPHENIX GitHub at line 76 of file EICG4B0ECALDetector.h
Referenced by ConstructMe(), ParseParametersFromTable(), and SetTowerMappingFile().
int EICG4B0ECALDetector::m_Layer private
Definition at line 74 of file EICG4B0ECALDetector.h.
View newest version in sPHENIX GitHub at line 74 of file EICG4B0ECALDetector.h
Referenced by get_Layer().
std::set<G4LogicalVolume *> EICG4B0ECALDetector::m_LogicalVolSet private
Definition at line 72 of file EICG4B0ECALDetector.h.
View newest version in sPHENIX GitHub at line 72 of file EICG4B0ECALDetector.h
Referenced by ConstructTower(), IsInDetector(), and LogicalVolSetInsert().
PHParameters* EICG4B0ECALDetector::m_Params private
Definition at line 67 of file EICG4B0ECALDetector.h.
View newest version in sPHENIX GitHub at line 67 of file EICG4B0ECALDetector.h
Referenced by ConstructMe(), ConstructTower(), getParams(), ParseParametersFromTable(), and Print().
std::map<G4VPhysicalVolume *, int> EICG4B0ECALDetector::m_PhysicalVolumesDet private
Definition at line 71 of file EICG4B0ECALDetector.h.
View newest version in sPHENIX GitHub at line 71 of file EICG4B0ECALDetector.h
Referenced by ConstructMe().
std::set<G4VPhysicalVolume *> EICG4B0ECALDetector::m_PhysicalVolumesSet private
Definition at line 69 of file EICG4B0ECALDetector.h.
View newest version in sPHENIX GitHub at line 69 of file EICG4B0ECALDetector.h
Referenced by ConstructMe().
std::string EICG4B0ECALDetector::m_SuperDetector private
Definition at line 75 of file EICG4B0ECALDetector.h.
View newest version in sPHENIX GitHub at line 75 of file EICG4B0ECALDetector.h
Referenced by SuperDetector().
std::string EICG4B0ECALDetector::m_TowerLogicNamePrefix private
Definition at line 77 of file EICG4B0ECALDetector.h.
View newest version in sPHENIX GitHub at line 77 of file EICG4B0ECALDetector.h
Referenced by ConstructMe(), and ParseParametersFromTable().
std::map<std::string, towerposition> EICG4B0ECALDetector::m_TowerPositionMap private
Definition at line 64 of file EICG4B0ECALDetector.h.
View newest version in sPHENIX GitHub at line 64 of file EICG4B0ECALDetector.h
Referenced by ParseParametersFromTable(), and PlaceTower().
The documentation for this class was generated from the following files:
fun4all_eicdetectors/blob/master/simulation/g4simulation/g4b0ecal/EICG4B0ECALDetector.h
fun4all_eicdetectors/blob/master/simulation/g4simulation/g4b0ecal/EICG4B0ECALDetector.cc