EIC Software: FW::DigitizationAlgorithm Exception Reference
FW::DigitizationAlgorithm Exception Reference final
Create planar clusters from simulation hits.
#include <fun4all_acts/blob/master/Examples/Algorithms/Digitization/include/ACTFW/Digitization/DigitizationAlgorithm.hpp>
Classes
struct Config
struct Digitizable
Public Member Functions
DigitizationAlgorithm (Config cfg, Acts::Logging::Level lvl)
ProcessCode execute (const AlgorithmContext &ctx) const finaloverride
Public Member Functions inherited from FW::BareAlgorithm
BareAlgorithm (std::string name, Acts::Logging::Level level=Acts::Logging::INFO)
std::string name () const finaloverride
The algorithm name.
Private Attributes
Config m_cfg
std::unordered_map
< Acts::GeometryID,
Digitizable > m_digitizables
Lookup container for all digitizable surfaces.
Additional Inherited Members
Protected Member Functions inherited from FW::BareAlgorithm
const Acts::Logger & logger () const
Detailed Description
Create planar clusters from simulation hits.
Definition at line 30 of file DigitizationAlgorithm.hpp.
View newest version in sPHENIX GitHub at line 30 of file DigitizationAlgorithm.hpp
Constructor & Destructor Documentation
FW::DigitizationAlgorithm::DigitizationAlgorithm (Config cfg, Acts::Logging::Level lvl)
Construct the digitization algorithm.
Parameters
cfg is the algorithm configuration
lvl is the logging level
Definition at line 32 of file DigitizationAlgorithm.cpp.
View newest version in sPHENIX GitHub at line 32 of file DigitizationAlgorithm.cpp
References Acts::IdentifiedDetectorElement::digitizationModule(), Acts::GeometryObject::geoID(), FW::DigitizationAlgorithm::Config::inputSimulatedHits, m_cfg, m_digitizables, FW::DigitizationAlgorithm::Config::outputClusters, FW::DigitizationAlgorithm::Config::planarModuleStepper, FW::DigitizationAlgorithm::Config::randomNumbers, FW::DigitizationAlgorithm::Digitizable::surface, and FW::DigitizationAlgorithm::Config::trackingGeometry.
Member Function Documentation
FW::ProcessCode FW::DigitizationAlgorithm::execute (const AlgorithmContext & ctx) const final override virtual
Build clusters from input simulation hits.
Parameters
txt is the algorithm context with event information
Returns
a process code indication success or failure
Implements FW::BareAlgorithm.
Definition at line 74 of file DigitizationAlgorithm.cpp.
View newest version in sPHENIX GitHub at line 74 of file DigitizationAlgorithm.cpp
References ACTS_DEBUG, ACTS_VERBOSE, FW::WhiteBoard::add(), Acts::Segmentation::binUtility(), FW::AlgorithmContext::eventStore, FW::AlgorithmContext::geoContext, FW::WhiteBoard::get(), FW::groupByModule(), incremental_prev_tag::idx, it, Acts::UnitConstants::ps, SUCCESS, and thickness.
Member Data Documentation
Config FW::DigitizationAlgorithm::m_cfg private
Definition at line 64 of file DigitizationAlgorithm.hpp.
View newest version in sPHENIX GitHub at line 64 of file DigitizationAlgorithm.hpp
Referenced by DigitizationAlgorithm().
std::unordered_map<Acts::GeometryID, Digitizable> FW::DigitizationAlgorithm::m_digitizables private
Lookup container for all digitizable surfaces.
Definition at line 66 of file DigitizationAlgorithm.hpp.
View newest version in sPHENIX GitHub at line 66 of file DigitizationAlgorithm.hpp
Referenced by DigitizationAlgorithm().
The documentation for this exception was generated from the following files:
fun4all_acts/blob/master/Examples/Algorithms/Digitization/include/ACTFW/Digitization/DigitizationAlgorithm.hpp
fun4all_acts/blob/master/Examples/Algorithms/Digitization/src/DigitizationAlgorithm.cpp