EIC Software: EtmPolygonGroup Class Reference
EtmPolygonGroup Class Reference
#include <EicToyModel/blob/master/include/EtmPolygonGroup.h>
Public Member Functions
EtmPolygonGroup (int fillcolor=0, int linecolor=1)
~EtmPolygonGroup ()
void AddPolygon (const std::vector< TVector2 > &polygon)
void AddPolygon (unsigned dim, const double xx[], const double yy[])
void AddRectangle (double x0, double y0, double xsize, double ysize, unsigned xsplit=1, unsigned ysplit=1)
void AddRectangle (const TVector2 &bl, const TVector2 &tr, unsigned xsplit=1, unsigned ysplit=1)
int GetFillColor (void) const
int GetLineColor (void) const
etm::LineStyle GetLineStyle (void) const
void SetLineColor (int color)
void SetLineWidth (int width)
void SetLineStyle (etm::LineStyle style)
void SetTextColor (int color)
const std::vector< std::vector
< TVector2 > > & Polygons (void) const
void DrawPolygon (unsigned dim, const double xx[], const double yy[], bool line=true) const
void DrawPolygon (const std::vector< TVector2 > &polygon, bool line=true, const TVector2 *shift=0, unsigned tb=0) const
void DrawMe (const TVector2 *shift=0, unsigned tb=0) const
void ClearPolygons (void)
unsigned PolygonCount (void) const
virtual bool IsHighlighted (void) const
virtual double GetColorAlpha (void) const
Protected Attributes
int mFillColor
int mLineColor
int mLineWidth
int mTextColor
etm::LineStyle mLineStyle
std::vector< std::vector
< TVector2 > > mPolygons
Detailed Description
Definition at line 11 of file EtmPolygonGroup.h.
View newest version in sPHENIX GitHub at line 11 of file EtmPolygonGroup.h
Constructor & Destructor Documentation
EtmPolygonGroup::EtmPolygonGroup (int fillcolor = 0, int linecolor = 1) inline
Definition at line 13 of file EtmPolygonGroup.h.
View newest version in sPHENIX GitHub at line 13 of file EtmPolygonGroup.h
Referenced by EtmDetector::insert().
EtmPolygonGroup::~EtmPolygonGroup () inline
Definition at line 16 of file EtmPolygonGroup.h.
View newest version in sPHENIX GitHub at line 16 of file EtmPolygonGroup.h
Member Function Documentation
void EtmPolygonGroup::AddPolygon (const std::vector< TVector2 > & polygon) inline
Definition at line 18 of file EtmPolygonGroup.h.
View newest version in sPHENIX GitHub at line 18 of file EtmPolygonGroup.h
References mPolygons.
Referenced by AddRectangle(), and EtmDetector::Build().
void EtmPolygonGroup::AddPolygon (unsigned dim, const double xx[], const double yy[])
Definition at line 10 of file EtmPolygonGroup.cc.
View newest version in sPHENIX GitHub at line 10 of file EtmPolygonGroup.cc
References Acts::Test::dim, and mPolygons.
void EtmPolygonGroup::AddRectangle (double x0, double y0, double xsize, double ysize, unsigned xsplit = 1, unsigned ysplit = 1)
Definition at line 51 of file EtmPolygonGroup.cc.
View newest version in sPHENIX GitHub at line 51 of file EtmPolygonGroup.cc
void EtmPolygonGroup::AddRectangle (const TVector2 & bl, const TVector2 & tr, unsigned xsplit = 1, unsigned ysplit = 1)
Definition at line 22 of file EtmPolygonGroup.cc.
View newest version in sPHENIX GitHub at line 22 of file EtmPolygonGroup.cc
References AddPolygon(), and buffer.
void EtmPolygonGroup::ClearPolygons (void)
Definition at line 60 of file EtmPolygonGroup.cc.
View newest version in sPHENIX GitHub at line 60 of file EtmPolygonGroup.cc
References mPolygons.
Referenced by EtmDetector::ClearPolygonBuffer().
void EtmPolygonGroup::DrawMe (const TVector2 * shift = 0, unsigned tb = 0) const
Definition at line 124 of file EtmPolygonGroup.cc.
View newest version in sPHENIX GitHub at line 124 of file EtmPolygonGroup.cc
References DrawPolygon(), and mPolygons.
void EtmPolygonGroup::DrawPolygon (unsigned dim, const double xx[], const double yy[], bool line = true) const
Definition at line 71 of file EtmPolygonGroup.cc.
View newest version in sPHENIX GitHub at line 71 of file EtmPolygonGroup.cc
References Acts::Test::dim, eic, GetColorAlpha(), EicToyModel::Instance(), IsHighlighted(), mFillColor, mLineColor, mLineStyle, and mLineWidth.
Referenced by DrawMe(), and DrawPolygon().
void EtmPolygonGroup::DrawPolygon (const std::vector< TVector2 > & polygon, bool line = true, const TVector2 * shift = 0, unsigned tb = 0) const
Definition at line 105 of file EtmPolygonGroup.cc.
View newest version in sPHENIX GitHub at line 105 of file EtmPolygonGroup.cc
References Acts::Test::dim, DrawPolygon(), and vtx().
virtual double EtmPolygonGroup::GetColorAlpha (void) const inline virtual
Reimplemented in EtmDetector.
Definition at line 46 of file EtmPolygonGroup.h.
View newest version in sPHENIX GitHub at line 46 of file EtmPolygonGroup.h
Referenced by DrawPolygon().
int EtmPolygonGroup::GetFillColor (void) const inline
Definition at line 25 of file EtmPolygonGroup.h.
View newest version in sPHENIX GitHub at line 25 of file EtmPolygonGroup.h
References mFillColor.
Referenced by EtmDetector::Build(), EtmDetector::BuildCADmodel(), EtmDetector::PlaceG4Volume(), and EtmDetector::RegisterFillColor().
int EtmPolygonGroup::GetLineColor (void) const inline
Definition at line 26 of file EtmPolygonGroup.h.
View newest version in sPHENIX GitHub at line 26 of file EtmPolygonGroup.h
References mLineColor.
etm::LineStyle EtmPolygonGroup::GetLineStyle (void) const inline
Definition at line 27 of file EtmPolygonGroup.h.
View newest version in sPHENIX GitHub at line 27 of file EtmPolygonGroup.h
References mLineStyle.
virtual bool EtmPolygonGroup::IsHighlighted (void) const inline virtual
Reimplemented in EtmDetector.
Definition at line 45 of file EtmPolygonGroup.h.
View newest version in sPHENIX GitHub at line 45 of file EtmPolygonGroup.h
Referenced by DrawPolygon().
unsigned EtmPolygonGroup::PolygonCount (void) const inline
Definition at line 43 of file EtmPolygonGroup.h.
View newest version in sPHENIX GitHub at line 43 of file EtmPolygonGroup.h
References mPolygons.
const std::vector<std::vector<TVector2> >& EtmPolygonGroup::Polygons (void) const inline
Definition at line 34 of file EtmPolygonGroup.h.
View newest version in sPHENIX GitHub at line 34 of file EtmPolygonGroup.h
References mPolygons.
Referenced by EtmDetector::BuildCADmodel(), and EtmDetector::PlaceG4Volume().
void EtmPolygonGroup::SetLineColor (int color) inline
Definition at line 29 of file EtmPolygonGroup.h.
View newest version in sPHENIX GitHub at line 29 of file EtmPolygonGroup.h
References color, and mLineColor.
void EtmPolygonGroup::SetLineStyle (etm::LineStyle style) inline
Definition at line 31 of file EtmPolygonGroup.h.
View newest version in sPHENIX GitHub at line 31 of file EtmPolygonGroup.h
References mLineStyle.
Referenced by EtmDetector::dashed(), and EtmDetector::dotted().
void EtmPolygonGroup::SetLineWidth (int width) inline
Definition at line 30 of file EtmPolygonGroup.h.
View newest version in sPHENIX GitHub at line 30 of file EtmPolygonGroup.h
References mLineWidth, and width().
void EtmPolygonGroup::SetTextColor (int color) inline
Definition at line 32 of file EtmPolygonGroup.h.
View newest version in sPHENIX GitHub at line 32 of file EtmPolygonGroup.h
References color, and mTextColor.
Referenced by EtmDetector::text().
Member Data Documentation
int EtmPolygonGroup::mFillColor protected
Definition at line 46 of file EtmPolygonGroup.h.
View newest version in sPHENIX GitHub at line 46 of file EtmPolygonGroup.h
Referenced by DrawPolygon(), and GetFillColor().
int EtmPolygonGroup::mLineColor protected
Definition at line 46 of file EtmPolygonGroup.h.
View newest version in sPHENIX GitHub at line 46 of file EtmPolygonGroup.h
Referenced by DrawPolygon(), GetLineColor(), and SetLineColor().
etm::LineStyle EtmPolygonGroup::mLineStyle protected
Definition at line 51 of file EtmPolygonGroup.h.
View newest version in sPHENIX GitHub at line 51 of file EtmPolygonGroup.h
Referenced by DrawPolygon(), GetLineStyle(), and SetLineStyle().
int EtmPolygonGroup::mLineWidth protected
Definition at line 46 of file EtmPolygonGroup.h.
View newest version in sPHENIX GitHub at line 46 of file EtmPolygonGroup.h
Referenced by DrawPolygon(), and SetLineWidth().
std::vector<std::vector<TVector2> > EtmPolygonGroup::mPolygons protected
Definition at line 54 of file EtmPolygonGroup.h.
View newest version in sPHENIX GitHub at line 54 of file EtmPolygonGroup.h
Referenced by AddPolygon(), ClearPolygons(), DrawMe(), PolygonCount(), and Polygons().
int EtmPolygonGroup::mTextColor protected
Definition at line 46 of file EtmPolygonGroup.h.
View newest version in sPHENIX GitHub at line 46 of file EtmPolygonGroup.h
Referenced by SetTextColor().
The documentation for this class was generated from the following files:
EicToyModel/blob/master/include/EtmPolygonGroup.h
EicToyModel/blob/master/source/EtmPolygonGroup.cc