EIC Software: ds Namespace Reference
ds Namespace Reference
Variables
auto pT = bdata::xrange(0.5_GeV, 10_GeV, 500_MeV)
auto phi = bdata::xrange(-180_degree, 180_degree, 30_degree)
auto theta = bdata::xrange(15_degree, 90_degree, 15_degree)
auto charge = bdata::make({1_e, -1_e})
auto trackParameters = (pT * phi * theta * charge)
auto propagationFraction = bdata::xrange(0.0, 1.0, 0.25)
auto propagationLimit = bdata::xrange(10_cm, 1_m, 10_cm)
auto rand1
auto rand2
auto rand3
auto threeRandom = (rand1 ^ rand2 ^ rand2)
Variable Documentation
auto ds::charge = bdata::make({1_e, -1_e})
Definition at line 29 of file PropagationTestBase.hpp.
View newest version in sPHENIX GitHub at line 29 of file PropagationTestBase.hpp
auto ds::phi = bdata::xrange(-180_degree, 180_degree, 30_degree)
Definition at line 27 of file PropagationTestBase.hpp.
View newest version in sPHENIX GitHub at line 27 of file PropagationTestBase.hpp
auto ds::propagationFraction = bdata::xrange(0.0, 1.0, 0.25)
Definition at line 32 of file PropagationTestBase.hpp.
View newest version in sPHENIX GitHub at line 32 of file PropagationTestBase.hpp
auto ds::propagationLimit = bdata::xrange(10_cm, 1_m, 10_cm)
Definition at line 33 of file PropagationTestBase.hpp.
View newest version in sPHENIX GitHub at line 33 of file PropagationTestBase.hpp
auto ds::pT = bdata::xrange(0.5_GeV, 10_GeV, 500_MeV)
Definition at line 26 of file PropagationTestBase.hpp.
View newest version in sPHENIX GitHub at line 26 of file PropagationTestBase.hpp
Referenced by BOOST_DATA_TEST_CASE(), Acts::IntegrationTest::BOOST_DATA_TEST_CASE(), Acts::Test::BOOST_DATA_TEST_CASE(), nBodyPhaseSpaceGen::calcEventKinematics(), HelixKalman::calculate_dApdp(), HelixKalmanFilter::calculate_dApdp(), PHInitZVertexing::export_output(), PHPatternReco::export_output(), PHHoughSeeding::export_output(), flowAfterburner(), QAExample::process_event(), eventChannel::pseudoRapidity(), and Gammaavectormeson::pseudoRapidity().
auto ds::rand1
Initial value:
= bdata::random(
    (bdata::seed = 1515,
     bdata::distribution = std::uniform_real_distribution<>(-1., 1.)))
Definition at line 35 of file PropagationTestBase.hpp.
View newest version in sPHENIX GitHub at line 35 of file PropagationTestBase.hpp
Referenced by BOOST_DATA_TEST_CASE(), Acts::IntegrationTest::covariance_bound(), and Acts::IntegrationTest::to_surface().
auto ds::rand2
Initial value:
= bdata::random(
    (bdata::seed = 1616,
     bdata::distribution = std::uniform_real_distribution<>(-1., 1.)))
Definition at line 38 of file PropagationTestBase.hpp.
View newest version in sPHENIX GitHub at line 38 of file PropagationTestBase.hpp
Referenced by BOOST_DATA_TEST_CASE(), Acts::IntegrationTest::covariance_bound(), and Acts::IntegrationTest::to_surface().
auto ds::rand3
Initial value:
= bdata::random(
    (bdata::seed = 1717,
     bdata::distribution = std::uniform_real_distribution<>(-1., 1.)))
Definition at line 41 of file PropagationTestBase.hpp.
View newest version in sPHENIX GitHub at line 41 of file PropagationTestBase.hpp
Referenced by BOOST_DATA_TEST_CASE(), Acts::IntegrationTest::covariance_bound(), and Acts::IntegrationTest::to_surface().
auto ds::theta = bdata::xrange(15_degree, 90_degree, 15_degree)
Definition at line 28 of file PropagationTestBase.hpp.
View newest version in sPHENIX GitHub at line 28 of file PropagationTestBase.hpp
Referenced by accessStepWise(), analysis_resolution(), BeamLine(), Acts::Test::BOOST_AUTO_TEST_CASE(), BOOST_DATA_TEST_CASE(), Acts::Test::BOOST_DATA_TEST_CASE(), Acts::IntegrationTest::BOOST_DATA_TEST_CASE(), PHG4mRICHDetector::build_mRICH_sector(), PHG4mRICHDetector::build_mRICH_wall_hside(), BuildePHENIX_0_0(), BuildeSTAR_0_0(), PHGenFitTrkProp::BuildLayerZPhiHitMap(), BuildPerfectDetector(), BuildSTAR_0_0(), BuildWithTof(), BuildZEUS_0_0(), EicToyModel::CalculateEtaEndPoint(), EicToyModel::CalculateEtaStartPoint(), Gammagammaleptonpair::calculateTable(), PHActsSiliconSeeding::circleFitSeed(), erhic::DoubleAngleComputer::ComputeQSquared(), erhic::DoubleAngleComputer::ComputeY(), Acts::IntegrationTest::constant_field_propagation(), PHG4InnerHcalDetector::ConstructHcalSingleScintillators(), PHG4OuterHcalDetector::ConstructHcalSingleScintillators(), PHG4PSTOFDetector::ConstructMe(), Smear::Acceptance::Zone::Contains(), Acts::Visualization::decomposeCovariance(), EtmAzimuthalScan::DoIt(), EicToyModel::DrawFlatFieldLines(), Acts::ImpactPointEstimator< input_track_t, propagator_t, propagator_options_t >::estimateImpactParameters(), FW::ParticleSmearing::execute(), tetgenmesh::facedihedral(), FW::ResPlotTool::fill(), eicpy.qaplots.TrackHists::fill(), SvtxEvaluator::fillOutputNtuples(), Acts::FullBilloirVertexFitter< input_track_t, linearizer_t >::fit(), Smear::FixTheta(), for(), fullMaterial(), Gammaavectormeson::Gammaavectormeson(), FW::Geant4::MMPrimaryGeneratorAction::GeneratePrimaries(), PHG4Utils::get_eta(), PHG4InputFilter::get_eta(), RawTowerGeomv1::get_eta(), RawTowerGeomv2::get_eta(), RawTowerGeomv3::get_eta(), PHG4Utils::get_etaphi(), PHG4Utils::get_theta(), RawTowerGeomv1::get_theta(), RawTowerGeomv3::get_theta(), Acts::ImpactPointEstimator< input_track_t, propagator_t, propagator_options_t >::getDistanceAndMomentum(), EicRcParticle::GetEta(), PHG4Utils::GetLengthForRapidityCoverage(), BEmcRec::GetProb(), Gammaavectormeson::getTheta(), ClusterIso::getTowerEta(), PHHepMCGenHelper::HepMC2Lab_boost_rotation_translation(), EicSmearTask::Init(), twoPhotonLuminosity::integrand(), tetgenmesh::interiorangle(), CbmRichRingFitterEllipseTau::Jacobi(), LoadData(), main(), PHActsTrackProjection::makeCaloSurfacePtrs(), FwdHoughTree::MappingCall(), tofBarrel::maxP(), mfield2eve(), momentumDistributions(), tofBarrel::numSigma(), ActsFatras::detail::Scattering< scattering_model_t >::operator()(), ActsFatras::detail::GeneralMixture::operator()(), Acts::Test::MaterialScattering::operator()(), PHG4GDMLWriteParamvol::Para_dimensionsWrite(), PHG4GDMLWriteSolids::ParaWrite(), plot_matscan(), plot_matscan_tdr(), BEmcRec::PredictEnergyProb(), printHits(), G4SnglTree::process_event(), PHG4SimpleEventGenerator::process_event(), G4SnglNtuple::process_event(), photonNucleusLuminosity::pttablegen(), rad_length(), EicBoxGenerator::ReadEvent(), scan_viewer(), EicBoxGenerator::SetTheta(), simulation(), PHG4GDMLWriteParamvol::Trap_dimensionsWrite(), PHG4GDMLWriteSolids::TrapWrite(), Gammaavectormeson::twoBodyDecay(), Gammagammaleptonpair::twoBodyDecay(), Gammagammasingle::twoBodyDecay(), ActsEvaluator::visitTrackStates(), Gammaavectormeson::vmpt(), and FW::RootTrajectoryWriter::writeT().
auto ds::threeRandom = (rand1 ^ rand2 ^ rand2)
Definition at line 44 of file PropagationTestBase.hpp.
View newest version in sPHENIX GitHub at line 44 of file PropagationTestBase.hpp
auto ds::trackParameters = (pT * phi * theta * charge)
Definition at line 31 of file PropagationTestBase.hpp.
View newest version in sPHENIX GitHub at line 31 of file PropagationTestBase.hpp
Referenced by genfit::RaveToGFVertex().