EIC Software: PHPy6JetTrigger Class Reference
PHPy6JetTrigger Class Reference
#include <fun4all_coresoftware/blob/master/generators/PHPythia6/PHPy6JetTrigger.h>
Public Member Functions
PHPy6JetTrigger (const std::string &name="PHPy6JetTrigger")
~PHPy6JetTrigger () override
bool Apply (const HepMC::GenEvent *evt) override
void SetEtaHighLow (double etaHigh, double etaLow)
void SetMinJetPt (double minPt)
void SetJetR (double R)
void SetMinNumConstituents (int nconst)
void PrintConfig ()
Public Member Functions inherited from PHPy6GenTrigger
virtual ~PHPy6GenTrigger ()
virtual std::string GetName ()
std::vector< int > convertToInts (std::string s)
void Verbosity (int v)
int Verbosity () const
Private Attributes
double m_theEtaHigh = 4.
double m_theEtaLow = 1.
double m_minPt = 10.
double m_R = 1.
int m_nconst = 0
Additional Inherited Members
Protected Member Functions inherited from PHPy6GenTrigger
PHPy6GenTrigger (const std::string &name="PHPy6GenTrigger")
constructor
Detailed Description
Definition at line 13 of file PHPy6JetTrigger.h.
View newest version in sPHENIX GitHub at line 13 of file PHPy6JetTrigger.h
Constructor & Destructor Documentation
PHPy6JetTrigger::PHPy6JetTrigger (const std::string & name = "PHPy6JetTrigger")
Definition at line 23 of file PHPy6JetTrigger.cc.
View newest version in sPHENIX GitHub at line 23 of file PHPy6JetTrigger.cc
PHPy6JetTrigger::~PHPy6JetTrigger () override
Definition at line 28 of file PHPy6JetTrigger.cc.
View newest version in sPHENIX GitHub at line 28 of file PHPy6JetTrigger.cc
References PrintConfig(), and PHPy6GenTrigger::Verbosity().
Member Function Documentation
bool PHPy6JetTrigger::Apply (const HepMC::GenEvent * evt) override virtual
Reimplemented from PHPy6GenTrigger.
Definition at line 33 of file PHPy6JetTrigger.cc.
View newest version in sPHENIX GitHub at line 33 of file PHPy6JetTrigger.cc
References kdfinder::abs(), m_minPt, m_nconst, m_R, m_theEtaHigh, m_theEtaLow, p, and PHPy6GenTrigger::Verbosity().
void PHPy6JetTrigger::PrintConfig ()
Definition at line 108 of file PHPy6JetTrigger.cc.
View newest version in sPHENIX GitHub at line 108 of file PHPy6JetTrigger.cc
References m_minPt, m_R, m_theEtaHigh, and m_theEtaLow.
Referenced by ~PHPy6JetTrigger().
void PHPy6JetTrigger::SetEtaHighLow (double etaHigh, double etaLow)
Definition at line 97 of file PHPy6JetTrigger.cc.
View newest version in sPHENIX GitHub at line 97 of file PHPy6JetTrigger.cc
References m_theEtaHigh, m_theEtaLow, and boost::swap().
Referenced by Fun4All_G4_FullDetectorModular(), and Fun4All_G4_FullDetectorModularBeast().
void PHPy6JetTrigger::SetJetR (double R) inline
Definition at line 23 of file PHPy6JetTrigger.h.
View newest version in sPHENIX GitHub at line 23 of file PHPy6JetTrigger.h
References m_R, and Acts::IntegrationTest::R.
Referenced by Fun4All_G4_FullDetectorModular(), and Fun4All_G4_FullDetectorModularBeast().
void PHPy6JetTrigger::SetMinJetPt (double minPt) inline
Definition at line 22 of file PHPy6JetTrigger.h.
View newest version in sPHENIX GitHub at line 22 of file PHPy6JetTrigger.h
References m_minPt.
Referenced by Fun4All_G4_FullDetectorModular(), and Fun4All_G4_FullDetectorModularBeast().
void PHPy6JetTrigger::SetMinNumConstituents (int nconst) inline
Definition at line 24 of file PHPy6JetTrigger.h.
View newest version in sPHENIX GitHub at line 24 of file PHPy6JetTrigger.h
References m_nconst.
Member Data Documentation
double PHPy6JetTrigger::m_minPt = 10. private
Definition at line 31 of file PHPy6JetTrigger.h.
View newest version in sPHENIX GitHub at line 31 of file PHPy6JetTrigger.h
Referenced by Apply(), PrintConfig(), and SetMinJetPt().
int PHPy6JetTrigger::m_nconst = 0 private
Definition at line 33 of file PHPy6JetTrigger.h.
View newest version in sPHENIX GitHub at line 33 of file PHPy6JetTrigger.h
Referenced by Apply(), and SetMinNumConstituents().
double PHPy6JetTrigger::m_R = 1. private
Definition at line 32 of file PHPy6JetTrigger.h.
View newest version in sPHENIX GitHub at line 32 of file PHPy6JetTrigger.h
Referenced by Apply(), PrintConfig(), and SetJetR().
double PHPy6JetTrigger::m_theEtaHigh = 4. private
Definition at line 29 of file PHPy6JetTrigger.h.
View newest version in sPHENIX GitHub at line 29 of file PHPy6JetTrigger.h
Referenced by Apply(), PrintConfig(), and SetEtaHighLow().
double PHPy6JetTrigger::m_theEtaLow = 1. private
Definition at line 30 of file PHPy6JetTrigger.h.
View newest version in sPHENIX GitHub at line 30 of file PHPy6JetTrigger.h
Referenced by Apply(), PrintConfig(), and SetEtaHighLow().
The documentation for this class was generated from the following files:
fun4all_coresoftware/blob/master/generators/PHPythia6/PHPy6JetTrigger.h
fun4all_coresoftware/blob/master/generators/PHPythia6/PHPy6JetTrigger.cc