EIC Software: FW::TrackFitterPerformanceWriter Exception Reference
FW::TrackFitterPerformanceWriter Exception Reference final
#include <fun4all_acts/blob/master/Examples/Io/Performance/ACTFW/Io/Performance/TrackFitterPerformanceWriter.hpp>
Classes
struct Config
Public Member Functions
TrackFitterPerformanceWriter (Config cfg, Acts::Logging::Level lvl)
Construct from configuration and log level.
~TrackFitterPerformanceWriter () override
ProcessCode endRun () finaloverride
Finalize plots.
Public Member Functions inherited from FW::WriterT< TrajectoryContainer >
WriterT (std::string objectName, std::string writerName, Acts::Logging::Level level)
std::string name () const finaloverride
Provide the name of the writer.
ProcessCode write (const AlgorithmContext &context) finaloverride
Read the object and call the type-specific member function.
ProcessCode endRun () override
No-op default implementation.
Public Member Functions inherited from FW::IWriter
virtual ~IWriter ()=default
Private Member Functions
ProcessCode writeT (const AlgorithmContext &ctx, const TrajectoryContainer &trajectories) finaloverride
Private Attributes
Config m_cfg
std::mutex m_writeMutex
Mutex used to protect multi-threaded writes.
TFile * m_outputFile {nullptr}
ResPlotTool m_resPlotTool
Plot tool for residuals and pulls.
ResPlotTool::ResPlotCache m_resPlotCache
EffPlotTool m_effPlotTool
Plot tool for efficiency.
EffPlotTool::EffPlotCache m_effPlotCache
TrackSummaryPlotTool m_trackSummaryPlotTool
Plot tool for track hit info.
TrackSummaryPlotTool::TrackSummaryPlotCache m_trackSummaryPlotCache
Additional Inherited Members
Protected Member Functions inherited from FW::WriterT< TrajectoryContainer >
const Acts::Logger & logger () const
Detailed Description
Write out the residual and pull of track parameters and efficiency.
Efficiency here is the fraction of smoothed tracks compared to all tracks.
A common file can be provided for to the writer to attach his TTree, this is done by setting the Config::rootFile pointer to an existing file
Safe to use from multiple writer threads - uses a std::mutex lock.
Definition at line 32 of file TrackFitterPerformanceWriter.hpp.
View newest version in sPHENIX GitHub at line 32 of file TrackFitterPerformanceWriter.hpp
Constructor & Destructor Documentation
FW::TrackFitterPerformanceWriter::TrackFitterPerformanceWriter (Config cfg, Acts::Logging::Level lvl)
Construct from configuration and log level.
Definition at line 21 of file TrackFitterPerformanceWriter.cpp.
View newest version in sPHENIX GitHub at line 21 of file TrackFitterPerformanceWriter.cpp
References FW::EffPlotTool::book(), FW::TrackSummaryPlotTool::book(), FW::ResPlotTool::book(), FW::TrackFitterPerformanceWriter::Config::inputParticles, FW::TrackFitterPerformanceWriter::Config::inputTrajectories, FW::joinPaths(), m_cfg, m_effPlotCache, m_effPlotTool, m_outputFile, m_resPlotCache, m_resPlotTool, m_trackSummaryPlotCache, m_trackSummaryPlotTool, FW::TrackFitterPerformanceWriter::Config::outputDir, and FW::TrackFitterPerformanceWriter::Config::outputFilename.
FW::TrackFitterPerformanceWriter::~TrackFitterPerformanceWriter () override
Definition at line 56 of file TrackFitterPerformanceWriter.cpp.
View newest version in sPHENIX GitHub at line 56 of file TrackFitterPerformanceWriter.cpp
Member Function Documentation
FW::ProcessCode FW::TrackFitterPerformanceWriter::endRun () final override virtual
Finalize plots.
Implements FW::IWriter.
Definition at line 66 of file TrackFitterPerformanceWriter.cpp.
View newest version in sPHENIX GitHub at line 66 of file TrackFitterPerformanceWriter.cpp
References ACTS_INFO, and SUCCESS.
FW::ProcessCode FW::TrackFitterPerformanceWriter::writeT (const AlgorithmContext & context, const TrajectoryContainer & t) final override private virtual
Type-specific write function implementation this method is implemented in the user implementation
Parameters
[in] context is the algorithm context that guarantees event consistency
Template Parameters
[in] is the templeted collection to be written
Implements FW::WriterT< TrajectoryContainer >.
Definition at line 81 of file TrackFitterPerformanceWriter.cpp.
View newest version in sPHENIX GitHub at line 81 of file TrackFitterPerformanceWriter.cpp
References FW::AlgorithmContext::eventStore, FW::AlgorithmContext::geoContext, FW::WhiteBoard::get(), Acts::HoleFlag, ip(), it, Acts::MeasurementFlag, Acts::OutlierFlag, particle, and SUCCESS.
Member Data Documentation
Config FW::TrackFitterPerformanceWriter::m_cfg private
Definition at line 60 of file TrackFitterPerformanceWriter.hpp.
View newest version in sPHENIX GitHub at line 60 of file TrackFitterPerformanceWriter.hpp
Referenced by TrackFitterPerformanceWriter().
EffPlotTool::EffPlotCache FW::TrackFitterPerformanceWriter::m_effPlotCache private
Definition at line 69 of file TrackFitterPerformanceWriter.hpp.
View newest version in sPHENIX GitHub at line 69 of file TrackFitterPerformanceWriter.hpp
Referenced by TrackFitterPerformanceWriter().
EffPlotTool FW::TrackFitterPerformanceWriter::m_effPlotTool private
Plot tool for efficiency.
Definition at line 68 of file TrackFitterPerformanceWriter.hpp.
View newest version in sPHENIX GitHub at line 68 of file TrackFitterPerformanceWriter.hpp
Referenced by TrackFitterPerformanceWriter().
TFile* FW::TrackFitterPerformanceWriter::m_outputFile {nullptr} private
Definition at line 63 of file TrackFitterPerformanceWriter.hpp.
View newest version in sPHENIX GitHub at line 63 of file TrackFitterPerformanceWriter.hpp
Referenced by TrackFitterPerformanceWriter().
ResPlotTool::ResPlotCache FW::TrackFitterPerformanceWriter::m_resPlotCache private
Definition at line 66 of file TrackFitterPerformanceWriter.hpp.
View newest version in sPHENIX GitHub at line 66 of file TrackFitterPerformanceWriter.hpp
Referenced by TrackFitterPerformanceWriter().
ResPlotTool FW::TrackFitterPerformanceWriter::m_resPlotTool private
Plot tool for residuals and pulls.
Definition at line 65 of file TrackFitterPerformanceWriter.hpp.
View newest version in sPHENIX GitHub at line 65 of file TrackFitterPerformanceWriter.hpp
Referenced by TrackFitterPerformanceWriter().
TrackSummaryPlotTool::TrackSummaryPlotCache FW::TrackFitterPerformanceWriter::m_trackSummaryPlotCache private
Definition at line 72 of file TrackFitterPerformanceWriter.hpp.
View newest version in sPHENIX GitHub at line 72 of file TrackFitterPerformanceWriter.hpp
Referenced by TrackFitterPerformanceWriter().
TrackSummaryPlotTool FW::TrackFitterPerformanceWriter::m_trackSummaryPlotTool private
Plot tool for track hit info.
Definition at line 71 of file TrackFitterPerformanceWriter.hpp.
View newest version in sPHENIX GitHub at line 71 of file TrackFitterPerformanceWriter.hpp
Referenced by TrackFitterPerformanceWriter().
std::mutex FW::TrackFitterPerformanceWriter::m_writeMutex private
Mutex used to protect multi-threaded writes.
Definition at line 62 of file TrackFitterPerformanceWriter.hpp.
View newest version in sPHENIX GitHub at line 62 of file TrackFitterPerformanceWriter.hpp
The documentation for this exception was generated from the following files:
fun4all_acts/blob/master/Examples/Io/Performance/ACTFW/Io/Performance/TrackFitterPerformanceWriter.hpp
fun4all_acts/blob/master/Examples/Io/Performance/ACTFW/Io/Performance/TrackFitterPerformanceWriter.cpp