EIC Software: PHMicromegasTpcTrackMatching Class Reference
PHMicromegasTpcTrackMatching Class Reference
#include <fun4all_coresoftware/blob/master/offline/packages/trackreco/PHMicromegasTpcTrackMatching.h>
Public Member Functions
PHMicromegasTpcTrackMatching (const std::string &name="PHMicromegasTpcTrackMatching")
virtual ~PHMicromegasTpcTrackMatching ()
void set_rphi_search_window_lyr1 (const double win)
void set_z_search_window_lyr1 (const double win)
void set_rphi_search_window_lyr2 (const double win)
void set_z_search_window_lyr2 (const double win)
void set_min_tpc_layer (const unsigned int layer)
void set_test_windows_printout (const bool test)
void set_sc_calib_mode (const bool mode)
void set_collision_rate (const double rate)
Public Member Functions inherited from PHTrackPropagating
PHTrackPropagating (const std::string &name="PHTrackPropagating")
virtual ~PHTrackPropagating ()
int InitRun (PHCompositeNode *topNode)
int process_event (PHCompositeNode *topNode)
int End (PHCompositeNode *topNode)
Called at the end of all processing.
void set_track_map_name (const std::string &map_name)
void SetUseTruthClusters (bool setit)
Public Member Functions inherited from SubsysReco
virtual ~SubsysReco ()
virtual int EndRun (const int)
Called at the end of each run.
virtual int Init (PHCompositeNode *)
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
virtual void Print (const std::string &what="ALL") const
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Protected Member Functions
int Setup (PHCompositeNode *topNode) override
int Process () override
int End () override
Private Member Functions
int GetNodes (PHCompositeNode *topNode)
void CircleFitByTaubin (std::vector< TrkrCluster * > clusters, double &R, double &X0, double &Y0)
void circle_circle_intersection (double r1, double r2, double x2, double y2, double &xplus, double &yplus, double &xminus, double &yminus)
void line_fit (std::vector< TrkrCluster * > clusters, double &a, double &b)
Private Attributes
unsigned int _n_mm_layers = 2
double _rphi_search_win [2] = {0.25, 13.0}
double _z_search_win [2] = {26.0, 0.25}
double _mm_layer_radius [2] = { 82.2565, 82.6998}
double _z_proj [2] ={0,0}
double _y_proj [2] ={0,0}
double _x_proj [2] ={0,0}
double _rphi_proj [2] ={0,0}
unsigned int _min_tpc_layer = 38
unsigned int _min_mm_layer = 55
bool _test_windows = false
bool _sc_calib_mode = false
double _collision_rate = 50e3
double _reference_collision_rate = 50e3
int _event = -1
SvtxTrack * _tracklet_tpc {nullptr}
TF1 * fdrphi {nullptr}
double _par0 = -0.36619
double _par1 = 0.00375714
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = INT_MAX - 10
}
Protected Attributes inherited from PHTrackPropagating
TrkrClusterContainer * _cluster_map
SvtxVertexMap * _vertex_map
SvtxTrackMap * _track_map
AssocInfoContainer * _assoc_container
std::string _track_map_name
bool _use_truth_clusters = false
Detailed Description
Definition at line 17 of file PHMicromegasTpcTrackMatching.h.
View newest version in sPHENIX GitHub at line 17 of file PHMicromegasTpcTrackMatching.h
Constructor & Destructor Documentation
PHMicromegasTpcTrackMatching::PHMicromegasTpcTrackMatching (const std::string & name = "PHMicromegasTpcTrackMatching")
Definition at line 32 of file PHMicromegasTpcTrackMatching.cc.
View newest version in sPHENIX GitHub at line 32 of file PHMicromegasTpcTrackMatching.cc
PHMicromegasTpcTrackMatching::~PHMicromegasTpcTrackMatching () virtual
Definition at line 39 of file PHMicromegasTpcTrackMatching.cc.
View newest version in sPHENIX GitHub at line 39 of file PHMicromegasTpcTrackMatching.cc
Member Function Documentation
void PHMicromegasTpcTrackMatching::circle_circle_intersection (double r1, double r2, double x2, double y2, double & xplus, double & yplus, double & xminus, double & yminus) private
Definition at line 469 of file PHMicromegasTpcTrackMatching.cc.
View newest version in sPHENIX GitHub at line 469 of file PHMicromegasTpcTrackMatching.cc
References a, b, c, and x2.
Referenced by Process().
void PHMicromegasTpcTrackMatching::CircleFitByTaubin (std::vector< TrkrCluster * > clusters, double & R, double & X0, double & Y0) private
Definition at line 372 of file PHMicromegasTpcTrackMatching.cc.
View newest version in sPHENIX GitHub at line 372 of file PHMicromegasTpcTrackMatching.cc
References starlightConstants::A2, Dy, x, and analysis::y.
Referenced by Process().
int PHMicromegasTpcTrackMatching::End () override protected virtual
Implements PHTrackPropagating.
Definition at line 357 of file PHMicromegasTpcTrackMatching.cc.
View newest version in sPHENIX GitHub at line 357 of file PHMicromegasTpcTrackMatching.cc
References Fun4AllReturnCodes::EVENT_OK.
int PHMicromegasTpcTrackMatching::GetNodes (PHCompositeNode * topNode) private
Definition at line 362 of file PHMicromegasTpcTrackMatching.cc.
View newest version in sPHENIX GitHub at line 362 of file PHMicromegasTpcTrackMatching.cc
References Fun4AllReturnCodes::EVENT_OK.
Referenced by Setup().
void PHMicromegasTpcTrackMatching::line_fit (std::vector< TrkrCluster * > clusters, double & a, double & b) private
Definition at line 500 of file PHMicromegasTpcTrackMatching.cc.
View newest version in sPHENIX GitHub at line 500 of file PHMicromegasTpcTrackMatching.cc
References b, r, Fun4AllBase::Verbosity(), and z.
Referenced by Process().
int PHMicromegasTpcTrackMatching::Process () override protected virtual
process event interface for trackers, called in process_event. implemented in derived classes
Implements PHTrackPropagating.
Definition at line 69 of file PHMicromegasTpcTrackMatching.cc.
View newest version in sPHENIX GitHub at line 69 of file PHMicromegasTpcTrackMatching.cc
References PHTrackPropagating::_assoc_container, PHTrackPropagating::_cluster_map, _event, _min_mm_layer, _min_tpc_layer, _mm_layer_radius, _n_mm_layers, _rphi_proj, _rphi_search_win, _sc_calib_mode, _test_windows, PHTrackPropagating::_track_map, _tracklet_tpc, _x_proj, _y_proj, _z_proj, _z_search_win, SvtxTrackMap::begin(), SvtxTrack::begin_cluster_keys(), circle_circle_intersection(), CircleFitByTaubin(), cos(), SvtxTrackMap::end(), SvtxTrack::end_cluster_keys(), Fun4AllReturnCodes::EVENT_OK, fdrphi, TrkrClusterContainer::findCluster(), SvtxTrack::get_id(), SvtxTrack::get_phi(), TrkrClusterContainer::getClusters(), TrkrDefs::getLayer(), MicromegasDefs::getSegmentationType(), TrkrCluster::getX(), TrkrCluster::getY(), TrkrCluster::getZ(), SvtxTrack::identify(), SvtxTrack::insert_cluster_key(), line_fit(), TrkrDefs::micromegasId, PHWHERE, Acts::IntegrationTest::R, PHG4InttDefs::SEGMENTATION_PHI, PHG4InttDefs::SEGMENTATION_Z, AssocInfoContainer::SetClusterTrackAssoc(), TrkrCluster::setX(), TrkrCluster::setY(), TrkrCluster::setZ(), SvtxTrackMap::size(), and Fun4AllBase::Verbosity().
void PHMicromegasTpcTrackMatching::set_collision_rate (const double rate) inline
Definition at line 32 of file PHMicromegasTpcTrackMatching.h.
View newest version in sPHENIX GitHub at line 32 of file PHMicromegasTpcTrackMatching.h
References _collision_rate.
Referenced by Tracking_Reco().
void PHMicromegasTpcTrackMatching::set_min_tpc_layer (const unsigned int layer) inline
Definition at line 29 of file PHMicromegasTpcTrackMatching.h.
View newest version in sPHENIX GitHub at line 29 of file PHMicromegasTpcTrackMatching.h
References _min_tpc_layer.
Referenced by Tracking_Reco().
void PHMicromegasTpcTrackMatching::set_rphi_search_window_lyr1 (const double win) inline
Definition at line 25 of file PHMicromegasTpcTrackMatching.h.
View newest version in sPHENIX GitHub at line 25 of file PHMicromegasTpcTrackMatching.h
References _rphi_search_win.
Referenced by Tracking_Reco().
void PHMicromegasTpcTrackMatching::set_rphi_search_window_lyr2 (const double win) inline
Definition at line 27 of file PHMicromegasTpcTrackMatching.h.
View newest version in sPHENIX GitHub at line 27 of file PHMicromegasTpcTrackMatching.h
References _rphi_search_win.
Referenced by Tracking_Reco().
void PHMicromegasTpcTrackMatching::set_sc_calib_mode (const bool mode) inline
Definition at line 31 of file PHMicromegasTpcTrackMatching.h.
View newest version in sPHENIX GitHub at line 31 of file PHMicromegasTpcTrackMatching.h
References _sc_calib_mode.
Referenced by Tracking_Reco().
void PHMicromegasTpcTrackMatching::set_test_windows_printout (const bool test) inline
Definition at line 30 of file PHMicromegasTpcTrackMatching.h.
View newest version in sPHENIX GitHub at line 30 of file PHMicromegasTpcTrackMatching.h
References _test_windows, and Acts::EventDataVisualization::test().
Referenced by Tracking_Reco().
void PHMicromegasTpcTrackMatching::set_z_search_window_lyr1 (const double win) inline
Definition at line 26 of file PHMicromegasTpcTrackMatching.h.
View newest version in sPHENIX GitHub at line 26 of file PHMicromegasTpcTrackMatching.h
References _z_search_win.
Referenced by Tracking_Reco().
void PHMicromegasTpcTrackMatching::set_z_search_window_lyr2 (const double win) inline
Definition at line 28 of file PHMicromegasTpcTrackMatching.h.
View newest version in sPHENIX GitHub at line 28 of file PHMicromegasTpcTrackMatching.h
References _z_search_win.
Referenced by Tracking_Reco().
int PHMicromegasTpcTrackMatching::Setup (PHCompositeNode * topNode) override protected virtual
setup interface for trackers, called in InitRun, setup things like pointers to nodes. overrided in derived classes
Reimplemented from PHTrackPropagating.
Definition at line 45 of file PHMicromegasTpcTrackMatching.cc.
View newest version in sPHENIX GitHub at line 45 of file PHMicromegasTpcTrackMatching.cc
References _collision_rate, _par0, _par1, _reference_collision_rate, _rphi_search_win, _z_search_win, Fun4AllReturnCodes::EVENT_OK, fdrphi, GetNodes(), PHWHERE, and PHTrackPropagating::Setup().
Member Data Documentation
double PHMicromegasTpcTrackMatching::_collision_rate = 50e3 private
Definition at line 70 of file PHMicromegasTpcTrackMatching.h.
View newest version in sPHENIX GitHub at line 70 of file PHMicromegasTpcTrackMatching.h
Referenced by set_collision_rate(), and Setup().
int PHMicromegasTpcTrackMatching::_event = -1 private
Definition at line 73 of file PHMicromegasTpcTrackMatching.h.
View newest version in sPHENIX GitHub at line 73 of file PHMicromegasTpcTrackMatching.h
Referenced by Process().
unsigned int PHMicromegasTpcTrackMatching::_min_mm_layer = 55 private
Definition at line 65 of file PHMicromegasTpcTrackMatching.h.
View newest version in sPHENIX GitHub at line 65 of file PHMicromegasTpcTrackMatching.h
Referenced by Process().
unsigned int PHMicromegasTpcTrackMatching::_min_tpc_layer = 38 private
Definition at line 64 of file PHMicromegasTpcTrackMatching.h.
View newest version in sPHENIX GitHub at line 64 of file PHMicromegasTpcTrackMatching.h
Referenced by Process(), and set_min_tpc_layer().
double PHMicromegasTpcTrackMatching::_mm_layer_radius[2] = { 82.2565, 82.6998} private
Definition at line 56 of file PHMicromegasTpcTrackMatching.h.
View newest version in sPHENIX GitHub at line 56 of file PHMicromegasTpcTrackMatching.h
Referenced by Process().
unsigned int PHMicromegasTpcTrackMatching::_n_mm_layers = 2 private
Definition at line 49 of file PHMicromegasTpcTrackMatching.h.
View newest version in sPHENIX GitHub at line 49 of file PHMicromegasTpcTrackMatching.h
Referenced by Process().
double PHMicromegasTpcTrackMatching::_par0 = -0.36619 private
Definition at line 78 of file PHMicromegasTpcTrackMatching.h.
View newest version in sPHENIX GitHub at line 78 of file PHMicromegasTpcTrackMatching.h
Referenced by Setup().
double PHMicromegasTpcTrackMatching::_par1 = 0.00375714 private
Definition at line 79 of file PHMicromegasTpcTrackMatching.h.
View newest version in sPHENIX GitHub at line 79 of file PHMicromegasTpcTrackMatching.h
Referenced by Setup().
double PHMicromegasTpcTrackMatching::_reference_collision_rate = 50e3 private
Definition at line 71 of file PHMicromegasTpcTrackMatching.h.
View newest version in sPHENIX GitHub at line 71 of file PHMicromegasTpcTrackMatching.h
Referenced by Setup().
double PHMicromegasTpcTrackMatching::_rphi_proj[2] ={0,0} private
Definition at line 61 of file PHMicromegasTpcTrackMatching.h.
View newest version in sPHENIX GitHub at line 61 of file PHMicromegasTpcTrackMatching.h
Referenced by Process().
double PHMicromegasTpcTrackMatching::_rphi_search_win[2] = {0.25, 13.0} private
Definition at line 53 of file PHMicromegasTpcTrackMatching.h.
View newest version in sPHENIX GitHub at line 53 of file PHMicromegasTpcTrackMatching.h
Referenced by Process(), set_rphi_search_window_lyr1(), set_rphi_search_window_lyr2(), and Setup().
bool PHMicromegasTpcTrackMatching::_sc_calib_mode = false private
Definition at line 68 of file PHMicromegasTpcTrackMatching.h.
View newest version in sPHENIX GitHub at line 68 of file PHMicromegasTpcTrackMatching.h
Referenced by Process(), and set_sc_calib_mode().
bool PHMicromegasTpcTrackMatching::_test_windows = false private
Definition at line 67 of file PHMicromegasTpcTrackMatching.h.
View newest version in sPHENIX GitHub at line 67 of file PHMicromegasTpcTrackMatching.h
Referenced by Process(), and set_test_windows_printout().
SvtxTrack* PHMicromegasTpcTrackMatching::_tracklet_tpc {nullptr} private
Definition at line 75 of file PHMicromegasTpcTrackMatching.h.
View newest version in sPHENIX GitHub at line 75 of file PHMicromegasTpcTrackMatching.h
Referenced by Process().
double PHMicromegasTpcTrackMatching::_x_proj[2] ={0,0} private
Definition at line 60 of file PHMicromegasTpcTrackMatching.h.
View newest version in sPHENIX GitHub at line 60 of file PHMicromegasTpcTrackMatching.h
Referenced by Process().
double PHMicromegasTpcTrackMatching::_y_proj[2] ={0,0} private
Definition at line 59 of file PHMicromegasTpcTrackMatching.h.
View newest version in sPHENIX GitHub at line 59 of file PHMicromegasTpcTrackMatching.h
Referenced by Process().
double PHMicromegasTpcTrackMatching::_z_proj[2] ={0,0} private
Definition at line 58 of file PHMicromegasTpcTrackMatching.h.
View newest version in sPHENIX GitHub at line 58 of file PHMicromegasTpcTrackMatching.h
Referenced by Process().
double PHMicromegasTpcTrackMatching::_z_search_win[2] = {26.0, 0.25} private
Definition at line 54 of file PHMicromegasTpcTrackMatching.h.
View newest version in sPHENIX GitHub at line 54 of file PHMicromegasTpcTrackMatching.h
Referenced by Process(), set_z_search_window_lyr1(), set_z_search_window_lyr2(), and Setup().
TF1* PHMicromegasTpcTrackMatching::fdrphi {nullptr} private
Definition at line 77 of file PHMicromegasTpcTrackMatching.h.
View newest version in sPHENIX GitHub at line 77 of file PHMicromegasTpcTrackMatching.h
Referenced by Process(), and Setup().
The documentation for this class was generated from the following files:
fun4all_coresoftware/blob/master/offline/packages/trackreco/PHMicromegasTpcTrackMatching.h
fun4all_coresoftware/blob/master/offline/packages/trackreco/PHMicromegasTpcTrackMatching.cc