EIC Software: PndPidCorrelator Class Reference
PndPidCorrelator Class Reference
#include <EicRoot/blob/master/pid/PidCorr/PndPidCorrelator.h>
Public Member Functions
virtual void Exec (Option_t *option)
virtual InitStatus Init ()
void Register ()
void Reset ()
PndPidCorrelator ()
virtual ~PndPidCorrelator ()
void SetInputBranch (TString branch)
void SetInputIDBranch (TString branch)
virtual void SetParContainers ()
virtual void Finish ()
Public Member Functions inherited from FairTask
FairTask ()
FairTask (const char *name, Int_t iVerbose=1)
virtual ~FairTask ()
void InitTask ()
void ReInitTask ()
void SetParTask ()
virtual void FinishTask ()
virtual void FinishEvent ()
void SetVerbose (Int_t iVerbose)
void SetInputPersistance (Bool_t val)
void CheckInputPersistance (TString branchName)
Protected Member Functions
void ConstructChargedCandidate ()
PndPidCandidate * AddChargedCandidate (PndPidCandidate *cand)
Bool_t GetTrackInfo (PndTrack *track, PndPidCandidate *pid)
Protected Member Functions inherited from FairTask
virtual InitStatus ReInit ()
void InitTasks ()
void ReInitTasks ()
void SetParTasks ()
void FinishTasks ()
void FinishEvents ()
Protected Attributes
TClonesArray * fTrack
TClonesArray * fTrackID
PndTrack TCA.
TClonesArray * fPidChargedCand
PndTrackID TCA.
TClonesArray * fMcTrack
PndPidCandidate TCA for charged particles.
TString fTrackBranch
PndMCTrack TCA.
TString fTrackIDBranch
TString fTrackOutBranch
Int_t fEventCounter
Int_t fPidHyp
Bool_t fIdealHyp
Bool_t fGeanePro
Bool_t fCorrErrorProp
PndGeoHandling * fGeoH
TString sDir
TString sFile
Protected Attributes inherited from FairTask
Int_t fVerbose
Int_t fInputPersistance
Indicates if input branch is persistant.
FairLogger * fLogger
Detailed Description
Definition at line 47 of file PndPidCorrelator.h.
View newest version in sPHENIX GitHub at line 47 of file PndPidCorrelator.h
Constructor & Destructor Documentation
PndPidCorrelator::PndPidCorrelator ()
Definition at line 59 of file PndPidCorrelator.cxx.
View newest version in sPHENIX GitHub at line 59 of file PndPidCorrelator.cxx
References fGeoH, fPidChargedCand, PndGeoHandling::Instance(), Acts::UnitConstants::mm, Reset(), sDir, and sFile.
PndPidCorrelator::~PndPidCorrelator () virtual
Definition at line 48 of file PndPidCorrelator.cxx.
View newest version in sPHENIX GitHub at line 48 of file PndPidCorrelator.cxx
References FairRootManager::Instance(), and FairRootManager::Write().
Member Function Documentation
PndPidCandidate * PndPidCorrelator::AddChargedCandidate (PndPidCandidate * cand) protected
Definition at line 1507 of file PndPidCorrelator.cxx.
View newest version in sPHENIX GitHub at line 1507 of file PndPidCorrelator.cxx
References fPidChargedCand.
Referenced by ConstructChargedCandidate().
void PndPidCorrelator::ConstructChargedCandidate () protected
Definition at line 735 of file PndPidCorrelator.cxx.
View newest version in sPHENIX GitHub at line 735 of file PndPidCorrelator.cxx
References kdfinder::abs(), AddChargedCandidate(), FairMultiLinkedData::AddLink(), fIdealHyp, fMcTrack, fPidChargedCand, fPidHyp, fTrack, fTrackBranch, fTrackID, fTrackIDBranch, PndTrackID::GetCorrTrackID(), PndTrackCand::getMcTrackId(), FairTrackPar::GetMomentum(), PndTrackID::GetNCorrTrackId(), PndTrack::GetParamLast(), PndMCTrack::GetPdgCode(), PndTrack::GetTrackCand(), GetTrackInfo(), FairRootManager::Instance(), PndTrack::mParameterizations, PndPidCandidate::mParameterizations, PndPidCandidate::SetMcIndex(), PndPidCandidate::SetTrackBranch(), and PndPidCandidate::SetTrackIndex().
Referenced by Exec().
void PndPidCorrelator::Exec (Option_t * option) virtual
Definition at line 686 of file PndPidCorrelator.cxx.
View newest version in sPHENIX GitHub at line 686 of file PndPidCorrelator.cxx
References ConstructChargedCandidate(), fEventCounter, fTrack, and Reset().
void PndPidCorrelator::Finish (void) virtual
Action after each event. To be implemented in the derived class
Reimplemented from FairTask.
Definition at line 1451 of file PndPidCorrelator.cxx.
View newest version in sPHENIX GitHub at line 1451 of file PndPidCorrelator.cxx
Bool_t PndPidCorrelator::GetTrackInfo (PndTrack * track, PndPidCandidate * pid) protected
Definition at line 18 of file PndPidTrackInfo.cxx.
View newest version in sPHENIX GitHub at line 18 of file PndPidTrackInfo.cxx
References charge, cos(), check_license::err(), fGeanePro, fPidHyp, FairTask::fVerbose, PndTrack::GetChi2(), FairTrackParH::GetCov(), FairRunAna::GetField(), PndTrack::GetFlag(), FairTrackParH::GetLambda(), FairTrackParP::GetMARSCov(), FairTrackPar::GetMomentum(), PndTrack::GetNDF(), PndTrack::GetParamFirst(), PndTrack::GetParamLast(), FairTrackPar::GetQ(), FairTrackPar::GetX(), FairTrackParH::GetX(), FairTrackPar::GetY(), FairTrackParH::GetY(), FairTrackParH::GetY_sc(), FairTrackPar::GetZ(), FairTrackParH::GetZ(), FairTrackParH::GetZ_sc(), FairRunAna::Instance(), momentum, FairTrackParH::Print(), FairGeanePro::Propagate(), FairGeanePro::PropagateToPCA(), PndPidCandidate::SetCharge(), PndPidCandidate::SetChiSquared(), PndPidCandidate::SetCov7(), PndPidCandidate::SetDegreesOfFreedom(), PndPidCandidate::SetEnergy(), PndPidCandidate::SetFirstHit(), PndPidCandidate::SetFitStatus(), PndPidCandidate::SetHelixCov(), PndPidCandidate::SetHelixParams(), PndPidCandidate::SetLastHit(), PndPidCandidate::SetMomentum(), FairGeanePro::SetPoint(), PndPidCandidate::SetPosition(), FairGeanePro::SetWire(), and lit::Sign().
Referenced by ConstructChargedCandidate().
InitStatus PndPidCorrelator::Init (void) virtual
Intialisation at begin of run. To be implemented in the derived class. Success If not kSUCCESS, task will be set inactive.
Reimplemented from FairTask.
Definition at line 194 of file PndPidCorrelator.cxx.
View newest version in sPHENIX GitHub at line 194 of file PndPidCorrelator.cxx
References kdfinder::abs(), fCorrErrorProp, fEventCounter, fGeanePro, fIdealHyp, fMcTrack, fPidHyp, fTrack, fTrackBranch, fTrackID, fTrackIDBranch, FairRootManager::GetObject(), FairRootManager::Instance(), kERROR, kFATAL, kSUCCESS, Register(), sDir, and sFile.
void PndPidCorrelator::Register ()
Definition at line 1434 of file PndPidCorrelator.cxx.
View newest version in sPHENIX GitHub at line 1434 of file PndPidCorrelator.cxx
References fPidChargedCand, fTrackOutBranch, FairRootManager::Instance(), and FairRootManager::Register().
Referenced by Init().
void PndPidCorrelator::Reset ()
Definition at line 1490 of file PndPidCorrelator.cxx.
View newest version in sPHENIX GitHub at line 1490 of file PndPidCorrelator.cxx
Referenced by Exec(), and PndPidCorrelator().
void PndPidCorrelator::SetInputBranch (TString branch) inline
Definition at line 186 of file PndPidCorrelator.h.
View newest version in sPHENIX GitHub at line 186 of file PndPidCorrelator.h
References fTrackBranch.
void PndPidCorrelator::SetInputIDBranch (TString branch) inline
Definition at line 187 of file PndPidCorrelator.h.
View newest version in sPHENIX GitHub at line 187 of file PndPidCorrelator.h
References fTrackIDBranch.
void PndPidCorrelator::SetParContainers () virtual
Get parameter containers
Reimplemented from FairTask.
Definition at line 661 of file PndPidCorrelator.cxx.
View newest version in sPHENIX GitHub at line 661 of file PndPidCorrelator.cxx
References Acts::Test::db, FairRuntimeDb::getContainer(), FairRun::GetRuntimeDb(), FairRun::Instance(), and Acts::PrimitivesView3DTest::run().
Member Data Documentation
Bool_t PndPidCorrelator::fCorrErrorProp protected
Definition at line 138 of file PndPidCorrelator.h.
View newest version in sPHENIX GitHub at line 138 of file PndPidCorrelator.h
Referenced by Init().
Int_t PndPidCorrelator::fEventCounter protected
Definition at line 134 of file PndPidCorrelator.h.
View newest version in sPHENIX GitHub at line 134 of file PndPidCorrelator.h
Referenced by Exec(), and Init().
Bool_t PndPidCorrelator::fGeanePro protected
Definition at line 137 of file PndPidCorrelator.h.
View newest version in sPHENIX GitHub at line 137 of file PndPidCorrelator.h
Referenced by GetTrackInfo(), and Init().
PndGeoHandling* PndPidCorrelator::fGeoH protected
Definition at line 139 of file PndPidCorrelator.h.
View newest version in sPHENIX GitHub at line 139 of file PndPidCorrelator.h
Referenced by PndPidCorrelator().
Bool_t PndPidCorrelator::fIdealHyp protected
Definition at line 136 of file PndPidCorrelator.h.
View newest version in sPHENIX GitHub at line 136 of file PndPidCorrelator.h
Referenced by ConstructChargedCandidate(), and Init().
TClonesArray* PndPidCorrelator::fMcTrack protected
PndPidCandidate TCA for charged particles.
Definition at line 53 of file PndPidCorrelator.h.
View newest version in sPHENIX GitHub at line 53 of file PndPidCorrelator.h
Referenced by ConstructChargedCandidate(), and Init().
TClonesArray* PndPidCorrelator::fPidChargedCand protected
PndTrackID TCA.
Definition at line 52 of file PndPidCorrelator.h.
View newest version in sPHENIX GitHub at line 52 of file PndPidCorrelator.h
Referenced by AddChargedCandidate(), ConstructChargedCandidate(), PndPidCorrelator(), and Register().
Int_t PndPidCorrelator::fPidHyp protected
Definition at line 135 of file PndPidCorrelator.h.
View newest version in sPHENIX GitHub at line 135 of file PndPidCorrelator.h
Referenced by ConstructChargedCandidate(), GetTrackInfo(), and Init().
TClonesArray* PndPidCorrelator::fTrack protected
Definition at line 50 of file PndPidCorrelator.h.
View newest version in sPHENIX GitHub at line 50 of file PndPidCorrelator.h
Referenced by ConstructChargedCandidate(), Exec(), and Init().
TString PndPidCorrelator::fTrackBranch protected
PndMCTrack TCA.
Definition at line 113 of file PndPidCorrelator.h.
View newest version in sPHENIX GitHub at line 113 of file PndPidCorrelator.h
Referenced by ConstructChargedCandidate(), Init(), and SetInputBranch().
TClonesArray* PndPidCorrelator::fTrackID protected
PndTrack TCA.
Definition at line 51 of file PndPidCorrelator.h.
View newest version in sPHENIX GitHub at line 51 of file PndPidCorrelator.h
Referenced by ConstructChargedCandidate(), and Init().
TString PndPidCorrelator::fTrackIDBranch protected
Definition at line 114 of file PndPidCorrelator.h.
View newest version in sPHENIX GitHub at line 114 of file PndPidCorrelator.h
Referenced by ConstructChargedCandidate(), Init(), and SetInputIDBranch().
TString PndPidCorrelator::fTrackOutBranch protected
Definition at line 115 of file PndPidCorrelator.h.
View newest version in sPHENIX GitHub at line 115 of file PndPidCorrelator.h
Referenced by Register().
TString PndPidCorrelator::sDir protected
Definition at line 141 of file PndPidCorrelator.h.
View newest version in sPHENIX GitHub at line 141 of file PndPidCorrelator.h
Referenced by Init(), and PndPidCorrelator().
TString PndPidCorrelator::sFile protected
Definition at line 142 of file PndPidCorrelator.h.
View newest version in sPHENIX GitHub at line 142 of file PndPidCorrelator.h
Referenced by Init(), and PndPidCorrelator().
The documentation for this class was generated from the following files:
EicRoot/blob/master/pid/PidCorr/PndPidCorrelator.h
EicRoot/blob/master/pid/PidCorr/PndPidCorrelator.cxx
EicRoot/blob/master/pid/PidCorr/PndPidTrackInfo.cxx