EIC Software: fun4all_tutorials/blob/master/AnaTutorial/macro/Fun4All_G4_EICDetector_AnaTutorial.C File Reference
Fun4All_G4_EICDetector_AnaTutorial.C File Reference
#include <anatutorial/AnaTutorial.h>
#include <GlobalVariables.C>
#include <DisplayOn.C>
#include <G4Setup_EICDetector.C>
#include <G4_Bbc.C>
#include <G4_DSTReader_EICDetector.C>
#include <G4_FwdJets.C>
#include <G4_Global.C>
#include <G4_Input.C>
#include <G4_Jets.C>
#include <G4_Production.C>
#include <G4_User.C>
#include <TROOT.h>
#include <fun4all/Fun4AllDstOutputManager.h>
#include <fun4all/Fun4AllOutputManager.h>
#include <fun4all/Fun4AllServer.h>
#include <phool/recoConsts.h>
Macros
#define MACRO_FUN4ALLG4EICDETECTOR_C
Functions
int Fun4All_G4_EICDetector_AnaTutorial (const int nEvents=1, const string &inputFile="https://www.phenix.bnl.gov/WWW/publish/phnxbld/sPHENIX/files/sPHENIX_G4Hits_sHijing_9-11fm_00000_00010.root", const string &outputFile="G4EICDetector.root", const string &embed_input_file="https://www.phenix.bnl.gov/WWW/publish/phnxbld/sPHENIX/files/sPHENIX_G4Hits_sHijing_9-11fm_00000_00010.root", const int skip=0, const string &outdir=".")
Macro Definition Documentation
#define MACRO_FUN4ALLG4EICDETECTOR_C
Definition at line 2 of file Fun4All_G4_EICDetector_AnaTutorial.C.
View newest version in sPHENIX GitHub at line 2 of file Fun4All_G4_EICDetector_AnaTutorial.C
Function Documentation
int Fun4All_G4_EICDetector_AnaTutorial (const int nEvents = 1, const string & inputFile = "https://www.phenix.bnl.gov/WWW/publish/phnxbld/sPHENIX/files/sPHENIX_G4Hits_sHijing_9-11fm_00000_00010.root", const string & outputFile = "G4EICDetector.root", const string & embed_input_file = "https://www.phenix.bnl.gov/WWW/publish/phnxbld/sPHENIX/files/sPHENIX_G4Hits_sHijing_9-11fm_00000_00010.root", const int skip = 0, const string & outdir = ".")
apply EIC beam parameter following EIC CDR
apply EIC beam parameter following EIC CDR
apply EIC beam parameter following EIC CDR
apply EIC beam parameter following EIC CDR
embedding ID for the event positive ID is the embedded event of interest, e.g. jetty event from pythia negative IDs are backgrounds, .e.g out of time pile up collisions Usually, ID = 0 means the primary Au+Au collision background
apply EIC beam parameter following EIC CDR
Definition at line 29 of file Fun4All_G4_EICDetector_AnaTutorial.C.
View newest version in sPHENIX GitHub at line 29 of file Fun4All_G4_EICDetector_AnaTutorial.C
References Enable::AEROGEL, AnaTutorial::analyzeClusters(), AnaTutorial::analyzeJets(), AnaTutorial::analyzeTracks(), AnaTutorial::analyzeTruth(), Input::ApplyEICBeamParameter(), Enable::BARREL, Enable::BBC, Bbc_Reco(), Enable::BBCFAKE, Enable::BLACKHOLE, Enable::CEMC, Enable::CEMC_CELL, CEMC_Cells(), Enable::CEMC_CLUSTER, CEMC_Clusters(), Enable::CEMC_EVAL, CEMC_Eval(), Enable::CEMC_TOWER, CEMC_Towers(), Enable::DIRC, G4TRACKING::DISPLACED_VERTEX, Enable::DISPLAY, DisplayOn(), DstCompress(), Enable::DSTOUT, Enable::DSTOUT_COMPRESS, Enable::DSTREADER, Enable::EEMC, Enable::EEMC_CLUSTER, EEMC_Clusters(), Enable::EEMC_EVAL, EEMC_Eval(), Enable::EEMC_TOWER, EEMC_Towers(), Enable::EGEM, INPUTGENERATOR::EICFileReader, Input::EMBED, Fun4AllServer::End(), Enable::FEMC, Enable::FEMC_CLUSTER, FEMC_Clusters(), Enable::FEMC_EVAL, FEMC_Eval(), Enable::FEMC_TOWER, FEMC_Towers(), Enable::FGEM, Enable::FGEM_ORIG, Enable::FHCAL, Enable::FHCAL_CLUSTER, FHCAL_Clusters(), Enable::FHCAL_EVAL, FHCAL_Eval(), Enable::FHCAL_TOWER, FHCAL_Towers(), INPUTHEPMC::filename, INPUTREADEIC::filename, INPUTREADHITS::filename, INPUTEMBED::filename, Enable::FST, G4FST::SETTING::FST_TPC, Enable::FWDJETS, Enable::FWDJETS_EVAL, G4DSTreader_EICDetector(), G4Init(), G4Setup(), Enable::GLOBAL_FASTSIM, Global_FastSim(), Enable::GLOBAL_RECO, Global_Reco(), Input::GUN, INPUTGENERATOR::Gun, Enable::HCALIN, Enable::HCALIN_CELL, Enable::HCALIN_CLUSTER, Enable::HCALIN_EVAL, Enable::HCALIN_TOWER, HCALInner_Cells(), HCALInner_Clusters(), HCALInner_Eval(), HCALInner_Towers(), Enable::HCALOUT, Enable::HCALOUT_CELL, Enable::HCALOUT_CLUSTER, Enable::HCALOUT_EVAL, Enable::HCALOUT_TOWER, HCALOuter_Cells(), HCALOuter_Clusters(), HCALOuter_Eval(), HCALOuter_Towers(), Input::HEPMC, INPUTMANAGER::HepMCInputManager, Enable::HFARFWD_MAGNETS_IP6, Enable::HFARFWD_MAGNETS_IP8, Enable::HFARFWD_VIRTUAL_DETECTORS_IP6, Enable::HFARFWD_VIRTUAL_DETECTORS_IP8, InputInit(), InputManagers(), InputRegister(), recoConsts::instance(), Fun4AllServer::instance(), Jet_Eval(), Jet_FwdEval(), Jet_FwdReco(), Jet_Reco(), Enable::JETS, Enable::JETS_EVAL, M_PI, G4MAGNET::magfield_rescale, Enable::MAGNET, Enable::MVTX, DstOut::OutputDir, DstOut::OutputFile, Enable::PIPE, Enable::PLUGDOOR, pos(), Enable::PRODUCTION, Production_CreateOutputDir(), Production_MoveOutput(), G4TRACKING::PROJECTION_CEMC, G4TRACKING::PROJECTION_EEMC, G4TRACKING::PROJECTION_FEMC, G4TRACKING::PROJECTION_FHCAL, Input::PYTHIA6, INPUTGENERATOR::Pythia6, Input::PYTHIA8, INPUTGENERATOR::Pythia8, Input::READEIC, Input::READHITS, Fun4AllServer::registerOutputManager(), Fun4AllServer::registerSubsystem(), Enable::RICH, Fun4AllServer::run(), Input::SARTRE, INPUTGENERATOR::Sartre, PHPythia6::set_config_file(), AnaTutorial::setMinJetPt(), ShowerCompress(), Input::SIMPLE, INPUTGENERATOR::SimpleEventGenerator, Fun4AllServer::skip(), Enable::TPC, Enable::TRACKING, Enable::TRACKING_EVAL, Tracking_Eval(), Tracking_Reco(), PHG4SimpleEventGenerator::Uniform, Input::UPSILON, G4PIPE::use_forward_pipes, Enable::USER, UserAnalysisInit(), INPUTGENERATOR::VectorMesonGenerator, Fun4AllBase::Verbosity(), and Input::VERBOSITY.