EIC Software: TpcDistortionCorrection Class Reference
TpcDistortionCorrection Class Reference
#include <fun4all_coresoftware/blob/master/offline/packages/tpc/TpcDistortionCorrection.h>
Public Types
enum CoordMask {
COORD_PHI = 1<<0, COORD_R = 1<<1, COORD_Z = 1<<2, COORD_PHIZ = COORD_PHI|COORD_Z,
COORD_ALL = COORD_PHI|COORD_R|COORD_Z
}
Public Member Functions
TpcDistortionCorrection ()=default
constructor
Acts::Vector3D get_corrected_position (const Acts::Vector3D &, const TpcDistortionCorrectionContainer *, unsigned int mask=COORD_ALL) const
get cluster corrected 3D position using given DistortionCorrectionObject
Detailed Description
Definition at line 14 of file TpcDistortionCorrection.h.
View newest version in sPHENIX GitHub at line 14 of file TpcDistortionCorrection.h
Member Enumeration Documentation
enum TpcDistortionCorrection::CoordMask
Enumerator:
COORD_PHI
COORD_R
COORD_Z
COORD_PHIZ
COORD_ALL
Definition at line 21 of file TpcDistortionCorrection.h.
View newest version in sPHENIX GitHub at line 21 of file TpcDistortionCorrection.h
Constructor & Destructor Documentation
TpcDistortionCorrection::TpcDistortionCorrection () default
constructor
Member Function Documentation
Acts::Vector3D TpcDistortionCorrection::get_corrected_position (const Acts::Vector3D & source, const TpcDistortionCorrectionContainer * dcc, unsigned int mask = COORD_ALL) const
get cluster corrected 3D position using given DistortionCorrectionObject
Definition at line 19 of file TpcDistortionCorrection.cc.
View newest version in sPHENIX GitHub at line 19 of file TpcDistortionCorrection.cc
References COORD_PHI, COORD_R, COORD_Z, cos(), TpcDistortionCorrectionContainer::m_hDPint, TpcDistortionCorrectionContainer::m_hDRint, TpcDistortionCorrectionContainer::m_hDZint, M_PI, phi, square(), and z.
Referenced by PHTpcTrackSeedCircleFit::getGlobalPosition(), PHCASeeding::getGlobalPosition(), PHSimpleKFProp::getGlobalPosition(), PHTpcClusterMover::process_event(), and PHSimpleKFProp::PropagateTrack().
The documentation for this class was generated from the following files:
fun4all_coresoftware/blob/master/offline/packages/tpc/TpcDistortionCorrection.h
fun4all_coresoftware/blob/master/offline/packages/tpc/TpcDistortionCorrection.cc