EIC Software: photonNucleusCrossSection Class Reference
photonNucleusCrossSection Class Reference
#include <estarlight/blob/master/include/photonNucleusCrossSection.h>
Public Member Functions
photonNucleusCrossSection (const inputParameters &input, const beamBeamSystem &bbsystem)
~photonNucleusCrossSection ()
double slopeParameter () const
returns slope of t-distribution [(GeV/c)^{-2}]
double getChannelMass () const
returns mass of the produced system [GeV/c^2]
double getBNORM () const
beamBeamSystem getbbs () const
returns beamBeamSystem
double vmPhotonCoupling () const
vectormeson-photon coupling constant f_v / 4 pi (cf. Eq. 10 in KN PRC 60 (1999) 014903)
double vmQ2Power (double Q2) const
double getDefaultC () const
double maxPhotonEnergy () const
returns max photon energy in lab frame [GeV] (for vectormesons only)
void crossSectionCalculation (const double bwnormsave)
double backwardsPropagationOmegaCrossSection (const double targetEgamma)
double getcsgA (const double Egamma, const double Q2, const int beam)
double e_getcsgA (const double Egamma, double Q2, const double W, const int beam)
double getcsgA_Q2_dep (const double Q2)
double photonFlux (const double Egamma, const int beam)
double photonFlux (const double Egamma, const double Q2)
double integrated_Q2_dep (const double Egamma, const double _min=0, const double _max=0)
double integrated_x_section (const double Egamma, const double _min=0, const double _max=0)
std::pair< double, double > * Q2arraylimits (double const Egamma)
double g (double const Egamma, double const Q2)
double sigmagp (const double Wgp)
double sigma_A (const double sig_N, const int beam)
double sigma_N (const double Wgp)
double breitWigner (const double W, const double C)
double nepoint (const double Egamma, const double bmin)
double getPhotonNucleusSigma () const
void setPhotonNucleusSigma (double sigma)
Protected Attributes
const unsigned int _nWbins
const unsigned int _nYbins
const double _wMin
const double _wMax
const double _yMax
const double _beamLorentzGamma
double _photonNucleusSigma
int _printDef
int _impulseSelected
int _quantumGlauber
Private Attributes
beamBeamSystem _bbs
double _protonEnergy
double _electronEnergy
starlightConstants::particleTypeEnum _particleType
int _beamBreakupMode
breakup mode for beam particles
bool _backwardsProduction
int _productionMode
int _sigmaNucleus
double _slopeParameter
slope of t-distribution [(GeV/c)^{-2}]
double _vmPhotonCoupling
vectormeson-photon coupling constant f_v / 4 pi (cf. Eq. 10 in KN PRC 60 (1999) 014903)
double _vmQ2Power_c1
VM power law Q2 correction (Mv2/(Q2+Mv2))^n; with n = c1 + c2*(Q2+Mv2)
double _vmQ2Power_c2
VM power law Q2 correction (Mv2/(Q2+Mv2))^.
double _ANORM
double _BNORM
double _defaultC
double _width
width of the produced system [GeV/c^2]
double _channelMass
mass of the produced system [GeV/c^2]
double _fixedQ2range
loads state of Q2 range
double _minQ2
min Q2 range in case it is fixed
double _maxQ2
max Q3 range in case it is fixed
double _maxPhotonEnergy
max photon energy in lab frame [GeV] (for vectormesons only)
double _cmsMinPhotonEnergy
double _targetRadii
double _maxW_GP
max W_GP energy
double _minW_GP
min W_GP energy
Detailed Description
Definition at line 42 of file photonNucleusCrossSection.h.
View newest version in sPHENIX GitHub at line 42 of file photonNucleusCrossSection.h
Constructor & Destructor Documentation
photonNucleusCrossSection::photonNucleusCrossSection (const inputParameters & input, const beamBeamSystem & bbsystem)
Definition at line 48 of file photonNucleusCrossSection.cpp.
View newest version in sPHENIX GitHub at line 48 of file photonNucleusCrossSection.cpp
References _ANORM, _backwardsProduction, _BNORM, _channelMass, _defaultC, _impulseSelected, _particleType, _quantumGlauber, _slopeParameter, _vmPhotonCoupling, _vmQ2Power_c1, _vmQ2Power_c2, _width, starlightConstants::FOURPRONG, inputParameters::impulseVM(), starlightConstants::JPSI, starlightConstants::JPSI2S, starlightConstants::JPSI2S_ee, starlightConstants::JPSI2S_mumu, starlightConstants::JPSI_ee, starlightConstants::JPSI_mumu, starlightConstants::JpsiMass, starlightConstants::JpsiWidth, starlightConstants::OMEGA, starlightConstants::OMEGA_pi0gamma, starlightConstants::OmegaMass, starlightConstants::OmegaWidth, starlightConstants::PHI, starlightConstants::PhiMass, starlightConstants::PhiWidth, starlightConstants::Psi2SMass, starlightConstants::Psi2SWidth, inputParameters::quantumGlauber(), starlightConstants::RHO, starlightConstants::rho0Mass, starlightConstants::rho0PrimeMass, starlightConstants::rho0PrimeWidth, starlightConstants::rho0Width, starlightConstants::RHOZEUS, starlightConstants::UPSILON, starlightConstants::Upsilon1SMass, starlightConstants::Upsilon1SWidth, starlightConstants::UPSILON2S, starlightConstants::UPSILON2S_ee, starlightConstants::UPSILON2S_mumu, starlightConstants::Upsilon2SMass, starlightConstants::Upsilon2SWidth, starlightConstants::UPSILON3S, starlightConstants::UPSILON3S_ee, starlightConstants::UPSILON3S_mumu, starlightConstants::Upsilon3SMass, starlightConstants::Upsilon3SWidth, starlightConstants::UPSILON_ee, and starlightConstants::UPSILON_mumu.
photonNucleusCrossSection::~photonNucleusCrossSection ()
Definition at line 232 of file photonNucleusCrossSection.cpp.
View newest version in sPHENIX GitHub at line 232 of file photonNucleusCrossSection.cpp
Member Function Documentation
double photonNucleusCrossSection::backwardsPropagationOmegaCrossSection (const double targetEgamma)
double photonNucleusCrossSection::breitWigner (const double W, const double C)
Definition at line 1114 of file photonNucleusCrossSection.cpp.
View newest version in sPHENIX GitHub at line 1114 of file photonNucleusCrossSection.cpp
References _ANORM, _BNORM, _channelMass, _particleType, _width, kdfinder::abs(), starlightConstants::FOURPRONG, starlightConstants::JPSI, starlightConstants::JPSI2S, starlightConstants::JPSI2S_ee, starlightConstants::JPSI2S_mumu, starlightConstants::JPSI_ee, starlightConstants::JPSI_mumu, starlightConstants::kaonChargedMass, starlightConstants::mel, starlightConstants::muonMass, starlightConstants::OMEGA, starlightConstants::OMEGA_pi0gamma, starlightConstants::PHI, starlightConstants::pionChargedMass, starlightConstants::pionNeutralMass, starlightConstants::RHO, starlightConstants::RHOZEUS, starlightConstants::UPSILON, starlightConstants::UPSILON2S, starlightConstants::UPSILON2S_ee, starlightConstants::UPSILON2S_mumu, starlightConstants::UPSILON3S, starlightConstants::UPSILON3S_ee, starlightConstants::UPSILON3S_mumu, starlightConstants::UPSILON_ee, and starlightConstants::UPSILON_mumu.
Referenced by e_wideResonanceCrossSection::crossSectionCalculation(), wideResonanceCrossSection::crossSectionCalculation(), incoherentPhotonNucleusLuminosity::incoherentPhotonNucleusDifferentialLuminosity(), photonElectronLuminosity::photonNucleusDifferentialLuminosity(), and photonNucleusLuminosity::photonNucleusDifferentialLuminosity().
void photonNucleusCrossSection::crossSectionCalculation (const double bwnormsave)
Definition at line 238 of file photonNucleusCrossSection.cpp.
View newest version in sPHENIX GitHub at line 238 of file photonNucleusCrossSection.cpp
double photonNucleusCrossSection::e_getcsgA (const double Egamma, double Q2, const double W, const int beam)
Definition at line 362 of file photonNucleusCrossSection.cpp.
View newest version in sPHENIX GitHub at line 362 of file photonNucleusCrossSection.cpp
References _bbs, _beamLorentzGamma, _vmPhotonCoupling, nucleus::A(), starlightConstants::alpha, KF_timing::ax, beamBeamSystem::electronBeam(), nucleus::formFactor(), starlightConstants::hbarc, k, pi, starlightConstants::protonMass, sigma_A(), sigma_N(), sigmagp(), t, and beamBeamSystem::targetBeam().
double photonNucleusCrossSection::g (double const Egamma, double const Q2)
Definition at line 847 of file photonNucleusCrossSection.cpp.
View newest version in sPHENIX GitHub at line 847 of file photonNucleusCrossSection.cpp
References photonFlux().
Referenced by e_narrowResonanceCrossSection::crossSectionCalculation(), e_wideResonanceCrossSection::crossSectionCalculation(), integrated_Q2_dep(), e_narrowResonanceCrossSection::makeGammaPQ2dependence(), photonElectronLuminosity::photonNucleusDifferentialLuminosity(), and Q2arraylimits().
beamBeamSystem photonNucleusCrossSection::getbbs () const inline
returns beamBeamSystem
Definition at line 52 of file photonNucleusCrossSection.h.
View newest version in sPHENIX GitHub at line 52 of file photonNucleusCrossSection.h
References _bbs.
Referenced by e_narrowResonanceCrossSection::crossSectionCalculation(), wideResonanceCrossSection::crossSectionCalculation(), incoherentVMCrossSection::crossSectionCalculation(), narrowResonanceCrossSection::crossSectionCalculation(), e_wideResonanceCrossSection::crossSectionCalculation(), incoherentPhotonNucleusLuminosity::incoherentPhotonNucleusDifferentialLuminosity(), e_narrowResonanceCrossSection::makeGammaPQ2dependence(), photonElectronLuminosity::photonNucleusDifferentialLuminosity(), photonNucleusLuminosity::photonNucleusDifferentialLuminosity(), photonNucleusLuminosity::pttablegen(), and photonNucleusLuminosity::vmsigmapt().
double photonNucleusCrossSection::getBNORM () const inline
Definition at line 51 of file photonNucleusCrossSection.h.
View newest version in sPHENIX GitHub at line 51 of file photonNucleusCrossSection.h
References _BNORM.
Referenced by e_wideResonanceCrossSection::crossSectionCalculation(), and wideResonanceCrossSection::crossSectionCalculation().
double photonNucleusCrossSection::getChannelMass () const inline
returns mass of the produced system [GeV/c^2]
Definition at line 50 of file photonNucleusCrossSection.h.
View newest version in sPHENIX GitHub at line 50 of file photonNucleusCrossSection.h
References _channelMass.
Referenced by incoherentVMCrossSection::crossSectionCalculation(), narrowResonanceCrossSection::crossSectionCalculation(), getcsgA_Q2_dep(), and photonNucleusLuminosity::pttablegen().
double photonNucleusCrossSection::getcsgA (const double Egamma, const double Q2, const int beam)
Definition at line 245 of file photonNucleusCrossSection.cpp.
View newest version in sPHENIX GitHub at line 245 of file photonNucleusCrossSection.cpp
References _bbs, _beamLorentzGamma, _channelMass, _electronEnergy, _impulseSelected, _maxPhotonEnergy, _targetRadii, _vmPhotonCoupling, nucleus::A(), starlightConstants::alpha, KF_timing::ax, beamBeamSystem::electronBeam(), nucleus::formFactor(), getcsgA_Q2_dep(), starlightConstants::hbarc, k, pi, starlightConstants::protonMass, sigma_A(), sigma_N(), sigmagp(), t, and beamBeamSystem::targetBeam().
Referenced by e_narrowResonanceCrossSection::crossSectionCalculation(), wideResonanceCrossSection::crossSectionCalculation(), narrowResonanceCrossSection::crossSectionCalculation(), e_wideResonanceCrossSection::crossSectionCalculation(), e_narrowResonanceCrossSection::makeGammaPQ2dependence(), photonElectronLuminosity::photonNucleusDifferentialLuminosity(), and photonNucleusLuminosity::photonNucleusDifferentialLuminosity().
double photonNucleusCrossSection::getcsgA_Q2_dep (const double Q2)
Definition at line 451 of file photonNucleusCrossSection.cpp.
View newest version in sPHENIX GitHub at line 451 of file photonNucleusCrossSection.cpp
References getChannelMass(), n, and vmQ2Power().
Referenced by e_narrowResonanceCrossSection::crossSectionCalculation(), e_wideResonanceCrossSection::crossSectionCalculation(), getcsgA(), and integrated_x_section().
double photonNucleusCrossSection::getDefaultC () const inline
Definition at line 55 of file photonNucleusCrossSection.h.
View newest version in sPHENIX GitHub at line 55 of file photonNucleusCrossSection.h
References _defaultC.
Referenced by incoherentPhotonNucleusLuminosity::incoherentPhotonNucleusDifferentialLuminosity(), photonNucleusLuminosity::photonNucleusDifferentialLuminosity(), and photonElectronLuminosity::photonNucleusDifferentialLuminosity().
double photonNucleusCrossSection::getPhotonNucleusSigma () const inline
Definition at line 90 of file photonNucleusCrossSection.h.
View newest version in sPHENIX GitHub at line 90 of file photonNucleusCrossSection.h
References _photonNucleusSigma.
Referenced by e_Gammaanarrowvm::e_Gammaanarrowvm(), e_Gammaawidevm::e_Gammaawidevm(), Gammaaincoherentvm::Gammaaincoherentvm(), Gammaanarrowvm::Gammaanarrowvm(), and Gammaawidevm::Gammaawidevm().
double photonNucleusCrossSection::integrated_Q2_dep (const double Egamma, const double _min = 0, const double _max = 0)
Definition at line 733 of file photonNucleusCrossSection.cpp.
View newest version in sPHENIX GitHub at line 733 of file photonNucleusCrossSection.cpp
References _electronEnergy, g(), starlightConstants::mel, ratio, x2, and x3.
Referenced by photonElectronLuminosity::photonNucleusDifferentialLuminosity().
double photonNucleusCrossSection::integrated_x_section (const double Egamma, const double _min = 0, const double _max = 0)
Definition at line 771 of file photonNucleusCrossSection.cpp.
View newest version in sPHENIX GitHub at line 771 of file photonNucleusCrossSection.cpp
References _electronEnergy, getcsgA_Q2_dep(), starlightConstants::mel, ratio, x2, and x3.
double photonNucleusCrossSection::maxPhotonEnergy () const inline
returns max photon energy in lab frame [GeV] (for vectormesons only)
Definition at line 56 of file photonNucleusCrossSection.h.
View newest version in sPHENIX GitHub at line 56 of file photonNucleusCrossSection.h
References _maxPhotonEnergy.
Referenced by incoherentVMCrossSection::crossSectionCalculation(), wideResonanceCrossSection::crossSectionCalculation(), narrowResonanceCrossSection::crossSectionCalculation(), incoherentPhotonNucleusLuminosity::incoherentPhotonNucleusDifferentialLuminosity(), and photonNucleusLuminosity::photonNucleusDifferentialLuminosity().
double photonNucleusCrossSection::nepoint (const double Egamma, const double bmin)
Definition at line 877 of file photonNucleusCrossSection.cpp.
View newest version in sPHENIX GitHub at line 877 of file photonNucleusCrossSection.cpp
References _beamLorentzGamma, starlightConstants::alpha, bessel::dbesk0(), bessel::dbesk1(), starlightConstants::hbarc, and pi.
Referenced by photonFlux().
double photonNucleusCrossSection::photonFlux (const double Egamma, const int beam)
Definition at line 461 of file photonNucleusCrossSection.cpp.
View newest version in sPHENIX GitHub at line 461 of file photonNucleusCrossSection.cpp
References _bbs, _beamBreakupMode, _beamLorentzGamma, _maxPhotonEnergy, _productionMode, nucleus::A(), starlightConstants::alpha, cos(), Acts::Test::db, bessel::dbesk1(), beamBeamSystem::electronBeam(), starlightConstants::hbarc, nepoint(), nucleus::nuclearRadius(), beam::photonDensity(), starlightConstants::PHOTONPOMERONINCOHERENT, starlightConstants::PHOTONPOMERONNARROW, starlightConstants::PHOTONPOMERONWIDE, pi, starlightConstants::pi, printf(), beamBeamSystem::probabilityOfBreakup(), beamBeamSystem::targetBeam(), and nucleus::Z().
Referenced by e_narrowResonanceCrossSection::crossSectionCalculation(), wideResonanceCrossSection::crossSectionCalculation(), e_wideResonanceCrossSection::crossSectionCalculation(), narrowResonanceCrossSection::crossSectionCalculation(), incoherentVMCrossSection::crossSectionCalculation(), g(), incoherentPhotonNucleusLuminosity::incoherentPhotonNucleusDifferentialLuminosity(), e_narrowResonanceCrossSection::makeGammaPQ2dependence(), and photonNucleusLuminosity::photonNucleusDifferentialLuminosity().
double photonNucleusCrossSection::photonFlux (const double Egamma, const double Q2)
Definition at line 856 of file photonNucleusCrossSection.cpp.
View newest version in sPHENIX GitHub at line 856 of file photonNucleusCrossSection.cpp
References _electronEnergy, starlightConstants::alpha, starlightConstants::mel, pi, and ratio.
pair< double, double > * photonNucleusCrossSection::Q2arraylimits (double const Egamma)
Definition at line 804 of file photonNucleusCrossSection.cpp.
View newest version in sPHENIX GitHub at line 804 of file photonNucleusCrossSection.cpp
References _electronEnergy, _fixedQ2range, _maxQ2, _minQ2, g(), starlightConstants::mel, and ratio.
Referenced by photonElectronLuminosity::photonNucleusDifferentialLuminosity().
void photonNucleusCrossSection::setPhotonNucleusSigma (double sigma) inline
Definition at line 91 of file photonNucleusCrossSection.h.
View newest version in sPHENIX GitHub at line 91 of file photonNucleusCrossSection.h
References _photonNucleusSigma.
Referenced by e_narrowResonanceCrossSection::crossSectionCalculation(), wideResonanceCrossSection::crossSectionCalculation(), narrowResonanceCrossSection::crossSectionCalculation(), incoherentVMCrossSection::crossSectionCalculation(), and e_wideResonanceCrossSection::crossSectionCalculation().
double photonNucleusCrossSection::sigma_A (const double sig_N, const int beam)
Definition at line 1001 of file photonNucleusCrossSection.cpp.
View newest version in sPHENIX GitHub at line 1001 of file photonNucleusCrossSection.cpp
References _bbs, _quantumGlauber, nucleus::A(), beamBeamSystem::electronBeam(), pi, nucleus::rho0(), beamBeamSystem::targetBeam(), and nucleus::thickness().
Referenced by incoherentVMCrossSection::crossSectionCalculation(), e_getcsgA(), getcsgA(), incoherentPhotonNucleusLuminosity::incoherentPhotonNucleusDifferentialLuminosity(), and photonNucleusLuminosity::pttablegen().
double photonNucleusCrossSection::sigma_N (const double Wgp)
Definition at line 1104 of file photonNucleusCrossSection.cpp.
View newest version in sPHENIX GitHub at line 1104 of file photonNucleusCrossSection.cpp
References _slopeParameter, _vmPhotonCoupling, starlightConstants::alpha, starlightConstants::hbarc, pi, and sigmagp().
Referenced by incoherentVMCrossSection::crossSectionCalculation(), e_getcsgA(), getcsgA(), and incoherentPhotonNucleusLuminosity::incoherentPhotonNucleusDifferentialLuminosity().
double photonNucleusCrossSection::sigmagp (const double Wgp)
Definition at line 909 of file photonNucleusCrossSection.cpp.
View newest version in sPHENIX GitHub at line 909 of file photonNucleusCrossSection.cpp
References _backwardsProduction, _channelMass, _maxW_GP, _particleType, starlightConstants::FOURPRONG, starlightConstants::JPSI, starlightConstants::JPSI2S, starlightConstants::JPSI2S_ee, starlightConstants::JPSI2S_mumu, starlightConstants::JPSI_ee, starlightConstants::JPSI_mumu, starlightConstants::OMEGA, starlightConstants::OMEGA_pi0gamma, starlightConstants::PHI, starlightConstants::protonMass, starlightConstants::RHO, starlightConstants::RHOZEUS, starlightConstants::UPSILON, starlightConstants::UPSILON2S, starlightConstants::UPSILON2S_ee, starlightConstants::UPSILON2S_mumu, starlightConstants::UPSILON3S, starlightConstants::UPSILON3S_ee, starlightConstants::UPSILON3S_mumu, starlightConstants::UPSILON_ee, and starlightConstants::UPSILON_mumu.
Referenced by incoherentVMCrossSection::crossSectionCalculation(), e_getcsgA(), getcsgA(), incoherentPhotonNucleusLuminosity::incoherentPhotonNucleusDifferentialLuminosity(), photonNucleusLuminosity::pttablegen(), and sigma_N().
double photonNucleusCrossSection::slopeParameter () const inline
returns slope of t-distribution [(GeV/c)^{-2}]
Definition at line 49 of file photonNucleusCrossSection.h.
View newest version in sPHENIX GitHub at line 49 of file photonNucleusCrossSection.h
References _slopeParameter.
Referenced by e_Gammaanarrowvm::e_Gammaanarrowvm(), e_Gammaawidevm::e_Gammaawidevm(), Gammaaincoherentvm::Gammaaincoherentvm(), Gammaanarrowvm::Gammaanarrowvm(), Gammaawidevm::Gammaawidevm(), and photonNucleusLuminosity::pttablegen().
double photonNucleusCrossSection::vmPhotonCoupling () const inline
vectormeson-photon coupling constant f_v / 4 pi (cf. Eq. 10 in KN PRC 60 (1999) 014903)
Definition at line 53 of file photonNucleusCrossSection.h.
View newest version in sPHENIX GitHub at line 53 of file photonNucleusCrossSection.h
References _vmPhotonCoupling.
Referenced by photonNucleusLuminosity::pttablegen().
double photonNucleusCrossSection::vmQ2Power (double Q2) const inline
Definition at line 54 of file photonNucleusCrossSection.h.
View newest version in sPHENIX GitHub at line 54 of file photonNucleusCrossSection.h
References _channelMass, _vmQ2Power_c1, and _vmQ2Power_c2.
Referenced by getcsgA_Q2_dep().
Member Data Documentation
double photonNucleusCrossSection::_ANORM private
Definition at line 127 of file photonNucleusCrossSection.h.
View newest version in sPHENIX GitHub at line 127 of file photonNucleusCrossSection.h
Referenced by breitWigner(), and photonNucleusCrossSection().
bool photonNucleusCrossSection::_backwardsProduction private
Definition at line 118 of file photonNucleusCrossSection.h.
View newest version in sPHENIX GitHub at line 118 of file photonNucleusCrossSection.h
Referenced by photonNucleusCrossSection(), and sigmagp().
beamBeamSystem photonNucleusCrossSection::_bbs private
Definition at line 111 of file photonNucleusCrossSection.h.
View newest version in sPHENIX GitHub at line 111 of file photonNucleusCrossSection.h
Referenced by e_getcsgA(), getbbs(), getcsgA(), photonFlux(), and sigma_A().
int photonNucleusCrossSection::_beamBreakupMode private
breakup mode for beam particles
Definition at line 117 of file photonNucleusCrossSection.h.
View newest version in sPHENIX GitHub at line 117 of file photonNucleusCrossSection.h
Referenced by photonFlux().
const double photonNucleusCrossSection::_beamLorentzGamma protected
Definition at line 101 of file photonNucleusCrossSection.h.
View newest version in sPHENIX GitHub at line 101 of file photonNucleusCrossSection.h
Referenced by e_getcsgA(), getcsgA(), nepoint(), and photonFlux().
double photonNucleusCrossSection::_BNORM private
Definition at line 128 of file photonNucleusCrossSection.h.
View newest version in sPHENIX GitHub at line 128 of file photonNucleusCrossSection.h
Referenced by breitWigner(), getBNORM(), and photonNucleusCrossSection().
double photonNucleusCrossSection::_channelMass private
mass of the produced system [GeV/c^2]
Definition at line 131 of file photonNucleusCrossSection.h.
View newest version in sPHENIX GitHub at line 131 of file photonNucleusCrossSection.h
Referenced by breitWigner(), getChannelMass(), getcsgA(), photonNucleusCrossSection(), sigmagp(), and vmQ2Power().
double photonNucleusCrossSection::_cmsMinPhotonEnergy private
Definition at line 136 of file photonNucleusCrossSection.h.
View newest version in sPHENIX GitHub at line 136 of file photonNucleusCrossSection.h
double photonNucleusCrossSection::_defaultC private
Definition at line 129 of file photonNucleusCrossSection.h.
View newest version in sPHENIX GitHub at line 129 of file photonNucleusCrossSection.h
Referenced by getDefaultC(), and photonNucleusCrossSection().
double photonNucleusCrossSection::_electronEnergy private
Definition at line 115 of file photonNucleusCrossSection.h.
View newest version in sPHENIX GitHub at line 115 of file photonNucleusCrossSection.h
Referenced by getcsgA(), integrated_Q2_dep(), integrated_x_section(), photonFlux(), and Q2arraylimits().
double photonNucleusCrossSection::_fixedQ2range private
loads state of Q2 range
Definition at line 132 of file photonNucleusCrossSection.h.
View newest version in sPHENIX GitHub at line 132 of file photonNucleusCrossSection.h
Referenced by Q2arraylimits().
int photonNucleusCrossSection::_impulseSelected protected
Definition at line 106 of file photonNucleusCrossSection.h.
View newest version in sPHENIX GitHub at line 106 of file photonNucleusCrossSection.h
Referenced by getcsgA(), and photonNucleusCrossSection().
double photonNucleusCrossSection::_maxPhotonEnergy private
max photon energy in lab frame [GeV] (for vectormesons only)
Definition at line 135 of file photonNucleusCrossSection.h.
View newest version in sPHENIX GitHub at line 135 of file photonNucleusCrossSection.h
Referenced by getcsgA(), maxPhotonEnergy(), and photonFlux().
double photonNucleusCrossSection::_maxQ2 private
max Q3 range in case it is fixed
Definition at line 134 of file photonNucleusCrossSection.h.
View newest version in sPHENIX GitHub at line 134 of file photonNucleusCrossSection.h
Referenced by Q2arraylimits().
double photonNucleusCrossSection::_maxW_GP private
max W_GP energy
Definition at line 138 of file photonNucleusCrossSection.h.
View newest version in sPHENIX GitHub at line 138 of file photonNucleusCrossSection.h
Referenced by sigmagp().
double photonNucleusCrossSection::_minQ2 private
min Q2 range in case it is fixed
Definition at line 133 of file photonNucleusCrossSection.h.
View newest version in sPHENIX GitHub at line 133 of file photonNucleusCrossSection.h
Referenced by Q2arraylimits().
double photonNucleusCrossSection::_minW_GP private
min W_GP energy
Definition at line 139 of file photonNucleusCrossSection.h.
View newest version in sPHENIX GitHub at line 139 of file photonNucleusCrossSection.h
const unsigned int photonNucleusCrossSection::_nWbins protected
Definition at line 94 of file photonNucleusCrossSection.h.
View newest version in sPHENIX GitHub at line 94 of file photonNucleusCrossSection.h
Referenced by incoherentPhotonNucleusLuminosity::incoherentPhotonNucleusDifferentialLuminosity(), photonNucleusLuminosity::photonNucleusDifferentialLuminosity(), and photonElectronLuminosity::photonNucleusDifferentialLuminosity().
const unsigned int photonNucleusCrossSection::_nYbins protected
Definition at line 95 of file photonNucleusCrossSection.h.
View newest version in sPHENIX GitHub at line 95 of file photonNucleusCrossSection.h
Referenced by incoherentPhotonNucleusLuminosity::incoherentPhotonNucleusDifferentialLuminosity(), photonNucleusLuminosity::photonNucleusDifferentialLuminosity(), photonElectronLuminosity::photonNucleusDifferentialLuminosity(), and photonNucleusLuminosity::pttablegen().
starlightConstants::particleTypeEnum photonNucleusCrossSection::_particleType private
Definition at line 116 of file photonNucleusCrossSection.h.
View newest version in sPHENIX GitHub at line 116 of file photonNucleusCrossSection.h
Referenced by breitWigner(), photonNucleusCrossSection(), and sigmagp().
double photonNucleusCrossSection::_photonNucleusSigma protected
Definition at line 103 of file photonNucleusCrossSection.h.
View newest version in sPHENIX GitHub at line 103 of file photonNucleusCrossSection.h
Referenced by getPhotonNucleusSigma(), and setPhotonNucleusSigma().
int photonNucleusCrossSection::_printDef protected
Definition at line 105 of file photonNucleusCrossSection.h.
View newest version in sPHENIX GitHub at line 105 of file photonNucleusCrossSection.h
int photonNucleusCrossSection::_productionMode private
Definition at line 119 of file photonNucleusCrossSection.h.
View newest version in sPHENIX GitHub at line 119 of file photonNucleusCrossSection.h
Referenced by photonFlux().
double photonNucleusCrossSection::_protonEnergy private
Definition at line 114 of file photonNucleusCrossSection.h.
View newest version in sPHENIX GitHub at line 114 of file photonNucleusCrossSection.h
int photonNucleusCrossSection::_quantumGlauber protected
Definition at line 107 of file photonNucleusCrossSection.h.
View newest version in sPHENIX GitHub at line 107 of file photonNucleusCrossSection.h
Referenced by photonNucleusCrossSection(), and sigma_A().
int photonNucleusCrossSection::_sigmaNucleus private
Definition at line 120 of file photonNucleusCrossSection.h.
View newest version in sPHENIX GitHub at line 120 of file photonNucleusCrossSection.h
double photonNucleusCrossSection::_slopeParameter private
slope of t-distribution [(GeV/c)^{-2}]
Definition at line 123 of file photonNucleusCrossSection.h.
View newest version in sPHENIX GitHub at line 123 of file photonNucleusCrossSection.h
Referenced by photonNucleusCrossSection(), sigma_N(), and slopeParameter().
double photonNucleusCrossSection::_targetRadii private
Definition at line 137 of file photonNucleusCrossSection.h.
View newest version in sPHENIX GitHub at line 137 of file photonNucleusCrossSection.h
Referenced by getcsgA().
double photonNucleusCrossSection::_vmPhotonCoupling private
vectormeson-photon coupling constant f_v / 4 pi (cf. Eq. 10 in KN PRC 60 (1999) 014903)
Definition at line 124 of file photonNucleusCrossSection.h.
View newest version in sPHENIX GitHub at line 124 of file photonNucleusCrossSection.h
Referenced by e_getcsgA(), getcsgA(), photonNucleusCrossSection(), sigma_N(), and vmPhotonCoupling().
double photonNucleusCrossSection::_vmQ2Power_c1 private
VM power law Q2 correction (Mv2/(Q2+Mv2))^n; with n = c1 + c2*(Q2+Mv2)
Definition at line 125 of file photonNucleusCrossSection.h.
View newest version in sPHENIX GitHub at line 125 of file photonNucleusCrossSection.h
Referenced by photonNucleusCrossSection(), and vmQ2Power().
double photonNucleusCrossSection::_vmQ2Power_c2 private
VM power law Q2 correction (Mv2/(Q2+Mv2))^.
Definition at line 126 of file photonNucleusCrossSection.h.
View newest version in sPHENIX GitHub at line 126 of file photonNucleusCrossSection.h
Referenced by photonNucleusCrossSection(), and vmQ2Power().
double photonNucleusCrossSection::_width private
width of the produced system [GeV/c^2]
Definition at line 130 of file photonNucleusCrossSection.h.
View newest version in sPHENIX GitHub at line 130 of file photonNucleusCrossSection.h
Referenced by breitWigner(), and photonNucleusCrossSection().
const double photonNucleusCrossSection::_wMax protected
Definition at line 98 of file photonNucleusCrossSection.h.
View newest version in sPHENIX GitHub at line 98 of file photonNucleusCrossSection.h
Referenced by e_wideResonanceCrossSection::e_wideResonanceCrossSection(), incoherentPhotonNucleusLuminosity::incoherentPhotonNucleusDifferentialLuminosity(), photonNucleusLuminosity::photonNucleusDifferentialLuminosity(), photonElectronLuminosity::photonNucleusDifferentialLuminosity(), and wideResonanceCrossSection::wideResonanceCrossSection().
const double photonNucleusCrossSection::_wMin protected
Definition at line 97 of file photonNucleusCrossSection.h.
View newest version in sPHENIX GitHub at line 97 of file photonNucleusCrossSection.h
Referenced by e_wideResonanceCrossSection::e_wideResonanceCrossSection(), incoherentPhotonNucleusLuminosity::incoherentPhotonNucleusDifferentialLuminosity(), photonNucleusLuminosity::photonNucleusDifferentialLuminosity(), photonElectronLuminosity::photonNucleusDifferentialLuminosity(), and wideResonanceCrossSection::wideResonanceCrossSection().
const double photonNucleusCrossSection::_yMax protected
Definition at line 99 of file photonNucleusCrossSection.h.
View newest version in sPHENIX GitHub at line 99 of file photonNucleusCrossSection.h
Referenced by incoherentPhotonNucleusLuminosity::incoherentPhotonNucleusDifferentialLuminosity(), photonNucleusLuminosity::photonNucleusDifferentialLuminosity(), photonElectronLuminosity::photonNucleusDifferentialLuminosity(), photonNucleusLuminosity::pttablegen(), and wideResonanceCrossSection::wideResonanceCrossSection().
The documentation for this class was generated from the following files:
estarlight/blob/master/include/photonNucleusCrossSection.h
estarlight/blob/master/src/photonNucleusCrossSection.cpp