EIC Software: EicToyModel/blob/master/examples/tmp.cc File Reference
tmp.cc File Reference
Functions
vst SetGeometryType (EicGeoParData::SimpleStructure)
vst AddBarrelLayer (ibcell, 4 *20, 14, 4 *39.3 *etm::mm, 14.0, 0.0)
vst PlaceG4Volume (mid, true, 0, new G4ThreeVector(0, 0, 0))
Variables
auto ibcell = new MapsMimosaAssembly()
auto mid = eic->mid()->get("TRACKER")->GetG4Volume()
Function Documentation
vst AddBarrelLayer (ibcell , 4 * 20, 14 , 4 *39.3 *etm::mm , 14. 0, 0. 0)
vst PlaceG4Volume (mid , true , 0 , new G4ThreeVector0, 0, 0)
vst SetGeometryType (EicGeoParData::SimpleStructure)
Variable Documentation
auto ibcell = new MapsMimosaAssembly()
Definition at line 6 of file tmp.cc.
View newest version in sPHENIX GitHub at line 6 of file tmp.cc
Referenced by ConfigureAliceCell(), BasicDetectorConstruction::Construct(), fbst(), Fun4All_G4_QtDisplay(), Fun4All_G4_Tracking(), and vst().
eic mid = eic->mid()->get("TRACKER")->GetG4Volume()
Definition at line 11 of file tmp.cc.
View newest version in sPHENIX GitHub at line 11 of file tmp.cc
Referenced by BasicDetectorConstruction::Construct(), EicRootDetector::ConstructMe(), Acts::Sycl::createSeedsForGroupSycl(), for(), get_evt_mnemonic(), kdfinder::LinearFit< T >::select(), Acts::Frustum< value_t, DIM, SIDES >::svg(), and Acts::AxisAlignedBoundingBox< entity_t, value_t, DIM >::svg().