EIC Software: FairDbTimerManager Class Reference
FairDbTimerManager Class Reference
#include <EicRoot/blob/master/dbase/dbInterface/FairDbTimerManager.h>
Public Member Functions
FairDbTimerManager ()
virtual ~FairDbTimerManager ()
void Enable (Bool_t flag=kTRUE, Bool_t enableSubWatch=kFALSE)
void RecBegin (string tableName, UInt_t rowSize)
void RecEnd (UInt_t numRows)
void RecFillAgg (Int_t aggNo)
void RecMainQuery ()
void StartSubWatch (UInt_t subWatch)
Static Public Attributes
static FairDbTimerManager gTimerManager
Private Member Functions
FairDbTimer * GetCurrent ()
FairDbTimer * Pop ()
FairDbTimer * Push ()
Private Attributes
Bool_t fEnabled
Bool_t fSubWatchEnabled
list< FairDbTimer * > fTimers
Detailed Description
Definition at line 15 of file FairDbTimerManager.h.
View newest version in sPHENIX GitHub at line 15 of file FairDbTimerManager.h
Constructor & Destructor Documentation
FairDbTimerManager::FairDbTimerManager ()
FairDbTimerManager::~FairDbTimerManager () virtual
Definition at line 17 of file FairDbTimerManager.cxx.
View newest version in sPHENIX GitHub at line 17 of file FairDbTimerManager.cxx
References GetCurrent(), and Pop().
Member Function Documentation
void FairDbTimerManager::Enable (Bool_t flag = kTRUE, Bool_t enableSubWatch = kFALSE) inline
Definition at line 27 of file FairDbTimerManager.h.
View newest version in sPHENIX GitHub at line 27 of file FairDbTimerManager.h
References fEnabled, and fSubWatchEnabled.
FairDbTimer * FairDbTimerManager::GetCurrent () private
Definition at line 23 of file FairDbTimerManager.cxx.
View newest version in sPHENIX GitHub at line 23 of file FairDbTimerManager.cxx
References fTimers.
Referenced by Pop(), Push(), RecEnd(), RecMainQuery(), StartSubWatch(), and ~FairDbTimerManager().
FairDbTimer * FairDbTimerManager::Pop () private
Definition at line 29 of file FairDbTimerManager.cxx.
View newest version in sPHENIX GitHub at line 29 of file FairDbTimerManager.cxx
References fTimers, GetCurrent(), and FairDbTimer::Resume().
Referenced by RecEnd(), and ~FairDbTimerManager().
FairDbTimer * FairDbTimerManager::Push () private
Definition at line 44 of file FairDbTimerManager.cxx.
View newest version in sPHENIX GitHub at line 44 of file FairDbTimerManager.cxx
References fTimers, GetCurrent(), and FairDbTimer::Suspend().
Referenced by RecBegin().
void FairDbTimerManager::RecBegin (string tableName, UInt_t rowSize)
Definition at line 54 of file FairDbTimerManager.cxx.
View newest version in sPHENIX GitHub at line 54 of file FairDbTimerManager.cxx
References fEnabled, Push(), and FairDbTimer::RecBegin().
void FairDbTimerManager::RecEnd (UInt_t numRows)
Definition at line 62 of file FairDbTimerManager.cxx.
View newest version in sPHENIX GitHub at line 62 of file FairDbTimerManager.cxx
References fEnabled, GetCurrent(), Pop(), and FairDbTimer::RecEnd().
void FairDbTimerManager::RecFillAgg (Int_t aggNo)
Definition at line 74 of file FairDbTimerManager.cxx.
View newest version in sPHENIX GitHub at line 74 of file FairDbTimerManager.cxx
References fEnabled.
Referenced by ClassImp().
void FairDbTimerManager::RecMainQuery ()
Definition at line 82 of file FairDbTimerManager.cxx.
View newest version in sPHENIX GitHub at line 82 of file FairDbTimerManager.cxx
References fEnabled, GetCurrent(), and FairDbTimer::RecMainQuery().
Referenced by FairDbProxy::QuerySeqNo(), FairDbProxy::QuerySeqNos(), FairDbTableProxy::RestoreFromL2Cache(), and FairDbTableProxy::SaveToL2Cache().
void FairDbTimerManager::StartSubWatch (UInt_t subWatch)
Definition at line 92 of file FairDbTimerManager.cxx.
View newest version in sPHENIX GitHub at line 92 of file FairDbTimerManager.cxx
References fEnabled, GetCurrent(), and FairDbTimer::StartSubWatch().
Referenced by ClassImp().
Member Data Documentation
Bool_t FairDbTimerManager::fEnabled private
Definition at line 50 of file FairDbTimerManager.h.
View newest version in sPHENIX GitHub at line 50 of file FairDbTimerManager.h
Referenced by Enable(), RecBegin(), RecEnd(), RecFillAgg(), RecMainQuery(), and StartSubWatch().
Bool_t FairDbTimerManager::fSubWatchEnabled private
Definition at line 51 of file FairDbTimerManager.h.
View newest version in sPHENIX GitHub at line 51 of file FairDbTimerManager.h
Referenced by Enable().
list<FairDbTimer*> FairDbTimerManager::fTimers private
Definition at line 53 of file FairDbTimerManager.h.
View newest version in sPHENIX GitHub at line 53 of file FairDbTimerManager.h
Referenced by GetCurrent(), Pop(), and Push().
FairDbTimerManager FairDbTimerManager::gTimerManager static
Definition at line 40 of file FairDbTimerManager.h.
View newest version in sPHENIX GitHub at line 40 of file FairDbTimerManager.h
Referenced by ClassImp(), FairDbProxy::QuerySeqNo(), FairDbProxy::QuerySeqNos(), FairDbTableProxy::RestoreFromL2Cache(), and FairDbTableProxy::SaveToL2Cache().
The documentation for this class was generated from the following files:
EicRoot/blob/master/dbase/dbInterface/FairDbTimerManager.h
EicRoot/blob/master/dbase/dbInterface/FairDbTimerManager.cxx