EIC Software: Acts::GeometryObject Class Reference
Acts::GeometryObject Class Reference abstract
#include <fun4all_acts/blob/master/Core/include/Acts/Geometry/GeometryObject.hpp>
Public Member Functions
GeometryObject ()=default
Defaulted construrctor.
GeometryObject (const GeometryObject &)=default
Defaulted copy constructor.
GeometryObject (const GeometryID &geoID)
GeometryObject & operator= (const GeometryObject &geoID)
const GeometryID & geoID () const
virtual const Vector3D binningPosition (const GeometryContext &gctx, BinningValue bValue) const =0
virtual double binningPositionValue (const GeometryContext &gctx, BinningValue bValue) const
void assignGeoID (const GeometryID &geoID)
Protected Attributes
GeometryID m_geoID
Detailed Description
Base class to provide GeometryID interface:
simple set and get
It also provides the binningPosition method for Geometry geometrical object to be binned in BinnedArrays
Definition at line 28 of file GeometryObject.hpp.
View newest version in sPHENIX GitHub at line 28 of file GeometryObject.hpp
Constructor & Destructor Documentation
Acts::GeometryObject::GeometryObject () default
Defaulted construrctor.
Acts::GeometryObject::GeometryObject (const GeometryObject &) default
Defaulted copy constructor.
Acts::GeometryObject::GeometryObject (const GeometryID & geoID) inline
Constructor from a value
Parameters
geoID the geometry identifier of the object
Definition at line 39 of file GeometryObject.hpp.
View newest version in sPHENIX GitHub at line 39 of file GeometryObject.hpp
Member Function Documentation
void Acts::GeometryObject::assignGeoID (const GeometryID & geoID) inline
Set the value
Parameters
geoID the geometry identifier to be assigned
Definition at line 85 of file GeometryObject.hpp.
View newest version in sPHENIX GitHub at line 85 of file GeometryObject.hpp
References geoID(), and m_geoID.
Referenced by Acts::Layer::closeGeometry(), and Acts::TrackingVolume::closeGeometry().
virtual const Vector3D Acts::GeometryObject::binningPosition (const GeometryContext & gctx, BinningValue bValue) const pure virtual
Force a binning position method
Parameters
gctx The current geometry context object, e.g. alignment
bValue is the value in which you want to bin
Returns
vector 3D used for the binning schema
Implemented in Acts::PlaneSurface, Acts::Volume, Acts::LineSurface, Acts::CylinderSurface, Acts::ConeSurface, Acts::SurfaceStub, and Acts::NavigationLayer.
Referenced by binningPositionValue(), Acts::SurfaceArrayCreator::createEquidistantAxis(), Acts::SurfaceArrayCreator::createVariableAxis(), and Acts::SurfaceArrayCreator::isSurfaceEquivalent().
double Acts::GeometryObject::binningPositionValue (const GeometryContext & gctx, BinningValue bValue) const inline virtual
Implement the binningValue
Parameters
gctx The current geometry context object, e.g. alignment
bValue is the dobule in which you want to bin
Returns
float to be used for the binning schema
Definition at line 89 of file GeometryObject.hpp.
View newest version in sPHENIX GitHub at line 89 of file GeometryObject.hpp
References binningPosition(), and Acts::VectorHelpers::cast().
const GeometryID & Acts::GeometryObject::geoID () const inline
Returns
the geometry id by reference
Definition at line 81 of file GeometryObject.hpp.
View newest version in sPHENIX GitHub at line 81 of file GeometryObject.hpp
References m_geoID.
Referenced by Acts::JsonGeometryConverter::addSurfaceToJson(), assignGeoID(), Acts::KalmanFitter< propagator_t, updater_t, smoother_t, outlier_finder_t, calibrator_t, input_converter_t, output_converter_t >::Actor< source_link_t, parameters_t >::backwardFilter(), Acts::Test::BOOST_AUTO_TEST_CASE(), Acts::VolumeMaterialMapper::checkAndInsert(), Acts::SurfaceMaterialMapper::checkAndInsert(), FW::RootMaterialWriter::collectMaterial(), Acts::JsonGeometryConverter::convertToRep(), FW::CsvPlanarClusterReader::CsvPlanarClusterReader(), FW::DigitizationAlgorithm::DigitizationAlgorithm(), Acts::KalmanFitter< propagator_t, updater_t, smoother_t, outlier_finder_t, calibrator_t, input_converter_t, output_converter_t >::Actor< source_link_t, parameters_t >::filter(), Acts::CombinatorialKalmanFilter< propagator_t, updater_t, smoother_t, source_link_selector_t, branch_stopper_t, calibrator_t, input_converter_t, output_converter_t >::Actor< source_link_t, parameters_t >::filter(), Acts::KalmanFitter< propagator_t, updater_t, smoother_t, outlier_finder_t, calibrator_t, input_converter_t, output_converter_t >::Actor< source_link_t, parameters_t >::materialInteractor(), Acts::CombinatorialKalmanFilter< propagator_t, updater_t, smoother_t, source_link_selector_t, branch_stopper_t, calibrator_t, input_converter_t, output_converter_t >::Actor< source_link_t, parameters_t >::materialInteractor(), ActsFatras::Interactor< generator_t, physics_list_t, hit_surface_selector_t >::operator()(), Acts::CKFSourceLinkSelector::operator()(), Acts::Test::runTest(), FW::Obj::ObjSurfaceWriter::write(), and FW::RootMaterialTrackWriter::writeT().
GeometryObject& Acts::GeometryObject::operator= (const GeometryObject & geoID) inline
Assignment operator
Parameters
geoID the source geoID
Definition at line 44 of file GeometryObject.hpp.
View newest version in sPHENIX GitHub at line 44 of file GeometryObject.hpp
References m_geoID.
Referenced by Acts::Surface::operator=().
Member Data Documentation
GeometryID Acts::GeometryObject::m_geoID protected
Definition at line 78 of file GeometryObject.hpp.
View newest version in sPHENIX GitHub at line 78 of file GeometryObject.hpp
Referenced by assignGeoID(), geoID(), and operator=().
The documentation for this class was generated from the following file:
fun4all_acts/blob/master/Core/include/Acts/Geometry/GeometryObject.hpp