EIC Software: PndMapPar Class Reference
PndMapPar Class Reference
#include <EicRoot/blob/master/field/PndMapPar.h>
Public Member Functions
PndMapPar (const char *name, const char *title, const char *context)
PndMapPar ()
~PndMapPar ()
virtual void putParams (FairParamList *list)
virtual Bool_t getParams (FairParamList *list)
void SetParameters (FairField *field)
Int_t GetType () const
Double_t GetXmin () const
Double_t GetXmax () const
Double_t GetYmin () const
Double_t GetYmax () const
Double_t GetZmin () const
Double_t GetZmax () const
void MapName (TString &name)
Double_t GetPositionX () const
Double_t GetPositionY () const
Double_t GetPositionZ () const
Double_t GetScale () const
Public Member Functions inherited from FairParGenericSet
FairParGenericSet (const char *name, const char *title, const char *context)
virtual ~FairParGenericSet ()
virtual void printParams ()
Bool_t init (FairParIo *inp)
Int_t write (FairParIo *output)
Public Member Functions inherited from FairParSet
FairParSet (const char *name="", const char *title="", const char *context="")
virtual ~FairParSet ()
virtual Bool_t init ()
virtual Int_t write ()
virtual void clear ()
virtual void print ()
const char * getDetectorName ()
void resetInputVersions ()
void setInputVersion (Int_t v=-1, Int_t i=0)
Int_t getInputVersion (Int_t i)
void setStatic (Bool_t flag=kTRUE)
Bool_t isStatic ()
void setChanged (Bool_t flag=kTRUE)
Bool_t hasChanged ()
const char * getParamContext () const
void setAuthor (const char *s)
const char * getAuthor () const
void setDescription (const char *s)
const char * getDescription () const
void copyComment (FairParSet &r)
Protected Member Functions
ClassDef (PndMapPar, 1)
Protected Member Functions inherited from FairParGenericSet
FairParGenericSet ()
Protected Attributes
Int_t fType
Double_t fXmin
Double_t fXmax
Double_t fYmin
Double_t fYmax
Double_t fZmin
Double_t fZmax
TString fMapName
Double_t fPosX
Double_t fPosY
Double_t fPosZ
Double_t fScale
Detailed Description
Definition at line 22 of file PndMapPar.h.
View newest version in sPHENIX GitHub at line 22 of file PndMapPar.h
Constructor & Destructor Documentation
PndMapPar::PndMapPar (const char * name, const char * title, const char * context)
Standard constructor
Definition at line 10 of file PndMapPar.cxx.
View newest version in sPHENIX GitHub at line 10 of file PndMapPar.cxx
PndMapPar::PndMapPar ()
default constructor
Definition at line 29 of file PndMapPar.cxx.
View newest version in sPHENIX GitHub at line 29 of file PndMapPar.cxx
PndMapPar::~PndMapPar ()
Destructor
Definition at line 48 of file PndMapPar.cxx.
View newest version in sPHENIX GitHub at line 48 of file PndMapPar.cxx
Member Function Documentation
PndMapPar::ClassDef (PndMapPar , 1) protected
Bool_t PndMapPar::getParams (FairParamList * list) virtual
Get parameters
Implements FairParGenericSet.
Reimplemented in PndMultiFieldPar, and PndConstPar.
Definition at line 70 of file PndMapPar.cxx.
View newest version in sPHENIX GitHub at line 70 of file PndMapPar.cxx
References FairParamList::fill(), fMapName, fPosX, fPosY, fPosZ, fScale, and fType.
Double_t PndMapPar::GetPositionX () const inline
Definition at line 59 of file PndMapPar.h.
View newest version in sPHENIX GitHub at line 59 of file PndMapPar.h
References fPosX.
Referenced by PndDipoleMap::PndDipoleMap(), PndSolenoidMap::PndSolenoidMap(), and PndTransMap::PndTransMap().
Double_t PndMapPar::GetPositionY () const inline
Definition at line 60 of file PndMapPar.h.
View newest version in sPHENIX GitHub at line 60 of file PndMapPar.h
References fPosY.
Referenced by PndDipoleMap::PndDipoleMap(), PndSolenoidMap::PndSolenoidMap(), and PndTransMap::PndTransMap().
Double_t PndMapPar::GetPositionZ () const inline
Definition at line 61 of file PndMapPar.h.
View newest version in sPHENIX GitHub at line 61 of file PndMapPar.h
References fPosZ.
Referenced by PndDipoleMap::PndDipoleMap(), PndSolenoidMap::PndSolenoidMap(), and PndTransMap::PndTransMap().
Double_t PndMapPar::GetScale () const inline
Definition at line 62 of file PndMapPar.h.
View newest version in sPHENIX GitHub at line 62 of file PndMapPar.h
References fScale.
Referenced by PndDipoleMap::PndDipoleMap(), PndSolenoidMap::PndSolenoidMap(), and PndTransMap::PndTransMap().
Int_t PndMapPar::GetType () const inline
Accessors
Definition at line 51 of file PndMapPar.h.
View newest version in sPHENIX GitHub at line 51 of file PndMapPar.h
References fType.
Referenced by PndFieldCreator::createFairField(), PndConstField::PndConstField(), PndDipoleMap::PndDipoleMap(), PndSolenoidMap::PndSolenoidMap(), and PndTransMap::PndTransMap().
Double_t PndMapPar::GetXmax () const inline
Definition at line 53 of file PndMapPar.h.
View newest version in sPHENIX GitHub at line 53 of file PndMapPar.h
References fXmax.
Referenced by PndConstField::PndConstField().
Double_t PndMapPar::GetXmin () const inline
Definition at line 52 of file PndMapPar.h.
View newest version in sPHENIX GitHub at line 52 of file PndMapPar.h
References fXmin.
Referenced by PndConstField::PndConstField().
Double_t PndMapPar::GetYmax () const inline
Definition at line 55 of file PndMapPar.h.
View newest version in sPHENIX GitHub at line 55 of file PndMapPar.h
References fYmax.
Referenced by PndConstField::PndConstField().
Double_t PndMapPar::GetYmin () const inline
Definition at line 54 of file PndMapPar.h.
View newest version in sPHENIX GitHub at line 54 of file PndMapPar.h
References fYmin.
Referenced by PndConstField::PndConstField().
Double_t PndMapPar::GetZmax () const inline
Definition at line 57 of file PndMapPar.h.
View newest version in sPHENIX GitHub at line 57 of file PndMapPar.h
References fZmax.
Referenced by PndConstField::PndConstField().
Double_t PndMapPar::GetZmin () const inline
Definition at line 56 of file PndMapPar.h.
View newest version in sPHENIX GitHub at line 56 of file PndMapPar.h
References fZmin.
Referenced by PndConstField::PndConstField().
void PndMapPar::MapName (TString & name) inline
Definition at line 58 of file PndMapPar.h.
View newest version in sPHENIX GitHub at line 58 of file PndMapPar.h
References fMapName.
Referenced by PndDipoleMap::PndDipoleMap(), PndSolenoidMap::PndSolenoidMap(), and PndTransMap::PndTransMap().
void PndMapPar::putParams (FairParamList * list) virtual
Put parameters
Implements FairParGenericSet.
Reimplemented in PndMultiFieldPar, and PndConstPar.
Definition at line 54 of file PndMapPar.cxx.
View newest version in sPHENIX GitHub at line 54 of file PndMapPar.cxx
References FairParamList::add(), fMapName, fPosX, fPosY, fPosZ, fScale, and fType.
void PndMapPar::SetParameters (FairField * field)
Set parameters from FairField
Definition at line 91 of file PndMapPar.cxx.
View newest version in sPHENIX GitHub at line 91 of file PndMapPar.cxx
References fMapName, fPosX, fPosY, fPosZ, fScale, fType, PndFieldMap::GetPositionX(), PndFieldMap::GetPositionY(), PndFieldMap::GetPositionZ(), and PndFieldMap::GetScale().
Referenced by PndTransMap::FillParContainer(), and PndMultiFieldPar::SetParameters().
Member Data Documentation
TString PndMapPar::fMapName protected
Field map name in case of field map
Definition at line 84 of file PndMapPar.h.
View newest version in sPHENIX GitHub at line 84 of file PndMapPar.h
Referenced by getParams(), MapName(), putParams(), PndConstPar::SetParameters(), and SetParameters().
Double_t PndMapPar::fPosX protected
Field centre position for field map
Definition at line 88 of file PndMapPar.h.
View newest version in sPHENIX GitHub at line 88 of file PndMapPar.h
Referenced by getParams(), GetPositionX(), putParams(), PndConstPar::SetParameters(), and SetParameters().
Double_t PndMapPar::fPosY protected
Definition at line 88 of file PndMapPar.h.
View newest version in sPHENIX GitHub at line 88 of file PndMapPar.h
Referenced by getParams(), GetPositionY(), putParams(), PndConstPar::SetParameters(), and SetParameters().
Double_t PndMapPar::fPosZ protected
Definition at line 88 of file PndMapPar.h.
View newest version in sPHENIX GitHub at line 88 of file PndMapPar.h
Referenced by getParams(), GetPositionZ(), putParams(), PndConstPar::SetParameters(), and SetParameters().
Double_t PndMapPar::fScale protected
Scaling factor for field map
Definition at line 92 of file PndMapPar.h.
View newest version in sPHENIX GitHub at line 92 of file PndMapPar.h
Referenced by getParams(), GetScale(), putParams(), PndConstPar::SetParameters(), and SetParameters().
Int_t PndMapPar::fType protected
Field type 0 = constant field 1 = field map 2 = field map sym2 (symmetries in x and y) 3 = field map sym3 (symmetries in x, y and z)
Definition at line 73 of file PndMapPar.h.
View newest version in sPHENIX GitHub at line 73 of file PndMapPar.h
Referenced by PndConstPar::getParams(), PndMultiFieldPar::getParams(), getParams(), GetType(), PndConstPar::PndConstPar(), PndConstPar::putParams(), PndMultiFieldPar::putParams(), putParams(), PndConstPar::SetParameters(), PndMultiFieldPar::SetParameters(), and SetParameters().
Double_t PndMapPar::fXmax protected
Definition at line 77 of file PndMapPar.h.
View newest version in sPHENIX GitHub at line 77 of file PndMapPar.h
Referenced by PndConstPar::getParams(), GetXmax(), PndConstPar::putParams(), and PndConstPar::SetParameters().
Double_t PndMapPar::fXmin protected
Field limits in case of constant field
Definition at line 77 of file PndMapPar.h.
View newest version in sPHENIX GitHub at line 77 of file PndMapPar.h
Referenced by PndConstPar::getParams(), GetXmin(), PndConstPar::putParams(), and PndConstPar::SetParameters().
Double_t PndMapPar::fYmax protected
Definition at line 78 of file PndMapPar.h.
View newest version in sPHENIX GitHub at line 78 of file PndMapPar.h
Referenced by PndConstPar::getParams(), GetYmax(), PndConstPar::putParams(), and PndConstPar::SetParameters().
Double_t PndMapPar::fYmin protected
Definition at line 78 of file PndMapPar.h.
View newest version in sPHENIX GitHub at line 78 of file PndMapPar.h
Referenced by PndConstPar::getParams(), GetYmin(), PndConstPar::putParams(), and PndConstPar::SetParameters().
Double_t PndMapPar::fZmax protected
Definition at line 79 of file PndMapPar.h.
View newest version in sPHENIX GitHub at line 79 of file PndMapPar.h
Referenced by PndConstPar::getParams(), GetZmax(), PndConstPar::putParams(), and PndConstPar::SetParameters().
Double_t PndMapPar::fZmin protected
Definition at line 79 of file PndMapPar.h.
View newest version in sPHENIX GitHub at line 79 of file PndMapPar.h
Referenced by PndConstPar::getParams(), GetZmin(), PndConstPar::putParams(), and PndConstPar::SetParameters().
The documentation for this class was generated from the following files:
EicRoot/blob/master/field/PndMapPar.h
EicRoot/blob/master/field/PndMapPar.cxx