EIC Software: EtmLine2D Class Reference
EtmLine2D Class Reference
#include <EicToyModel/blob/master/include/EtmLine2D.h>
Public Member Functions
EtmLine2D ()
EtmLine2D (const TVector2 &x, const TVector2 &v)
EtmLine2D (const TVector2 &x, double alfa)
~EtmLine2D ()
TVector2 Cross (const EtmLine2D &line) const
double Distance (const TVector2 &point) const
bool IsParallel (const EtmLine2D &line) const
void Shift (const TVector2 &x)
TVector2 X (void) const
TVector2 V (void) const
TVector2 N (void) const
Private Member Functions
void CalculateNormal (void)
Private Attributes
TVector2 mX
TVector2 mV
TVector2 mN
Detailed Description
Definition at line 7 of file EtmLine2D.h.
View newest version in sPHENIX GitHub at line 7 of file EtmLine2D.h
Constructor & Destructor Documentation
EtmLine2D::EtmLine2D () inline
Definition at line 9 of file EtmLine2D.h.
View newest version in sPHENIX GitHub at line 9 of file EtmLine2D.h
EtmLine2D::EtmLine2D (const TVector2 & x, const TVector2 & v)
Definition at line 9 of file EtmLine2D.cc.
View newest version in sPHENIX GitHub at line 9 of file EtmLine2D.cc
References CalculateNormal().
EtmLine2D::EtmLine2D (const TVector2 & x, double alfa)
Definition at line 16 of file EtmLine2D.cc.
View newest version in sPHENIX GitHub at line 16 of file EtmLine2D.cc
References CalculateNormal(), cos(), and mV.
EtmLine2D::~EtmLine2D () inline
Definition at line 12 of file EtmLine2D.h.
View newest version in sPHENIX GitHub at line 12 of file EtmLine2D.h
Member Function Documentation
void EtmLine2D::CalculateNormal (void) private
Definition at line 24 of file EtmLine2D.cc.
View newest version in sPHENIX GitHub at line 24 of file EtmLine2D.cc
References M_PI, mN, and mV.
Referenced by EtmLine2D().
TVector2 EtmLine2D::Cross (const EtmLine2D & line) const
Definition at line 32 of file EtmLine2D.cc.
View newest version in sPHENIX GitHub at line 32 of file EtmLine2D.cc
References mV, mX, t1, v1, v2, and x2.
Referenced by EicToyModel::Band(), EtmDetector::Build(), EicToyModel::GetIntersection(), and EicToyModel::RebuildCrack().
double EtmLine2D::Distance (const TVector2 & point) const
Definition at line 47 of file EtmLine2D.cc.
View newest version in sPHENIX GitHub at line 47 of file EtmLine2D.cc
References mN, and mX.
Referenced by EicToyModel::Band(), EtmDetector::Build(), EicToyModel::GetIntersection(), and EicToyModel::RebuildCrack().
bool EtmLine2D::IsParallel (const EtmLine2D & line) const
Definition at line 54 of file EtmLine2D.cc.
View newest version in sPHENIX GitHub at line 54 of file EtmLine2D.cc
References mV.
Referenced by EicToyModel::Band(), and EicToyModel::GetIntersection().
TVector2 EtmLine2D::N (void) const inline
Definition at line 22 of file EtmLine2D.h.
View newest version in sPHENIX GitHub at line 22 of file EtmLine2D.h
References mN.
Referenced by EtmDetector::Build().
void EtmLine2D::Shift (const TVector2 & x) inline
Definition at line 18 of file EtmLine2D.h.
View newest version in sPHENIX GitHub at line 18 of file EtmLine2D.h
References mX, and x.
TVector2 EtmLine2D::V (void) const inline
Definition at line 21 of file EtmLine2D.h.
View newest version in sPHENIX GitHub at line 21 of file EtmLine2D.h
References mV.
Referenced by EicToyModel::RebuildCrack().
TVector2 EtmLine2D::X (void) const inline
Definition at line 20 of file EtmLine2D.h.
View newest version in sPHENIX GitHub at line 20 of file EtmLine2D.h
References mX.
Referenced by EtmDetector::Build(), and EicToyModel::ExecuteBoundaryModificationRequests().
Member Data Documentation
TVector2 EtmLine2D::mN private
Definition at line 27 of file EtmLine2D.h.
View newest version in sPHENIX GitHub at line 27 of file EtmLine2D.h
Referenced by CalculateNormal(), Distance(), and N().
TVector2 EtmLine2D::mV private
Definition at line 27 of file EtmLine2D.h.
View newest version in sPHENIX GitHub at line 27 of file EtmLine2D.h
Referenced by CalculateNormal(), Cross(), EtmLine2D(), IsParallel(), and V().
TVector2 EtmLine2D::mX private
Definition at line 27 of file EtmLine2D.h.
View newest version in sPHENIX GitHub at line 27 of file EtmLine2D.h
Referenced by Cross(), Distance(), Shift(), and X().
The documentation for this class was generated from the following files:
EicToyModel/blob/master/include/EtmLine2D.h
EicToyModel/blob/master/source/EtmLine2D.cc