EIC Software: erhic::EventSartre Class Reference
erhic::EventSartre Class Reference
#include <eic-smear/blob/master/include/eicsmear/erhic/EventSartre.h>
Public Member Functions
EventSartre ()
virtual bool Parse (const std::string &)
const ParticleMC * ScatteredLepton () const
virtual const ParticleMC * ExchangeBoson () const
Public Member Functions inherited from erhic::EventMC
EventMC ()
virtual ~EventMC ()
virtual bool RequiresEaParticleFields ()
virtual ULong64_t GetN () const
virtual Int_t GetProcess () const
virtual UInt_t GetNTracks () const
virtual const ParticleMC * GetTrack (UInt_t) const
virtual ParticleMC * GetTrack (UInt_t)
virtual const ParticleMC * BeamLepton () const
virtual const ParticleMC * BeamHadron () const
virtual void AddLast (ParticleMC *track)
virtual void Reset ()
void Print (const Option_t *option="") const
virtual void Clear (Option_t *="")
virtual void SetProcess (int code)
virtual void SetN (int n)
virtual void SetNTracks (int n)
virtual void SetELeptonInNuclearFrame (double energy)
virtual void SetEScatteredInNuclearFrame (double energy)
void FinalState (ParticlePtrList &particles) const
void HadronicFinalState (ParticlePtrList &) const
TLorentzVector FinalStateMomentum () const
TLorentzVector HadronicFinalStateMomentum () const
Double_t FinalStateCharge () const
std::vector< const
VirtualParticle * > GetTracks () const
Public Member Functions inherited from erhic::EventDis
virtual ~EventDis ()
EventDis ()
EventDis (const EventDis &)
EventDis & operator= (const EventDis &)
virtual Double_t GetX () const
virtual Double_t GetQ2 () const
virtual Double_t GetY () const
virtual Double_t GetYPlus () const
virtual Double_t GetW2 () const
virtual Double_t GetNu () const
virtual double GetXDoubleAngle () const
virtual double GetQ2DoubleAngle () const
virtual double GetYDoubleAngle () const
virtual double GetW2DoubleAngle () const
virtual double GetXJacquetBlondel () const
virtual double GetQ2JacquetBlondel () const
virtual double GetYJacquetBlondel () const
virtual double GetW2JacquetBlondel () const
virtual void SetLeptonKinematics (const DisKinematics &)
virtual void SetJacquetBlondelKinematics (const DisKinematics &)
virtual void SetDoubleAngleKinematics (const DisKinematics &)
virtual void CopyKinematics (const EventDis &)
Public Member Functions inherited from erhic::VirtualEvent
virtual ~VirtualEvent ()
Protected Attributes
Int_t genevent
Trials required for this event (dummy right now)
Double32_t trueT
Double32_t trueQ2
Double32_t trueX
Double32_t trueY
Double32_t trueW2
Double32_t trueNu
Double32_t trueXpom
Double32_t s_cm
Int_t pol
Int_t dmode
Int_t bup
Protected Attributes inherited from erhic::EventMC
Int_t number
Event number.
Int_t process
PYTHIA code for the physics process producing the event.
Int_t nTracks
Number of Particles in the event (intermediate + final)
Double32_t ELeptonInNucl
Double32_t ELeptonOutNucl
TClonesArray particles
Particle list.
Additional Inherited Members
Public Types inherited from erhic::VirtualEvent
typedef std::vector< const
erhic::VirtualParticle * > ParticlePtrList
Public Attributes inherited from erhic::EventDis
Double32_t x
Bjorken scaling variable.
Double32_t QSquared
Q2 calculated from scattered electron.
Double32_t y
Inelasticity.
Double32_t WSquared
Invariant mass of the hadronic system.
Double32_t nu
Energy transfer from the electron.
Double32_t yJB
y calculated via the Jacquet-Blondel method
Double32_t QSquaredJB
Q2 calculated via the Jacquet-Blondel method.
Double32_t xJB
x calculated via the Jacquet-Blondel method
Double32_t WSquaredJB
W2 calculated via the Jacquet-Blondel method.
Double32_t yDA
y calculated via the double-angle method
Double32_t QSquaredDA
Q2 calculated via the double-angle method.
Double32_t xDA
x calculated via the double-angle method
Double32_t WSquaredDA
W2 calculated via the double-angle method.
Detailed Description
Describes an event from the generator SIMPLE.
Definition at line 19 of file EventSartre.h.
View newest version in sPHENIX GitHub at line 19 of file EventSartre.h
Constructor & Destructor Documentation
erhic::EventSartre::EventSartre ()
Constructor.
Definition at line 15 of file EventSartre.cxx.
View newest version in sPHENIX GitHub at line 15 of file EventSartre.cxx
Member Function Documentation
const ParticleMC * erhic::EventSartre::ExchangeBoson () const virtual
Returns a pointer to the exchanged boson. It would probably be the third track, but we'll go with the first status=21 boson that has particle 1 or 2 as parent
Reimplemented from erhic::EventMC.
Definition at line 81 of file EventSartre.cxx.
View newest version in sPHENIX GitHub at line 81 of file EventSartre.cxx
References kdfinder::abs(), erhic::EventMC::GetTracks(), and particle.
bool erhic::EventSartre::Parse (const std::string & line) virtual
Parses the event information from a text string.
The string must have the following format (no newlines):
"0 ievent genevent truet trueQ2 truex truey trueW2
 truenu truexpom s_cm pol dmode bup"
Returns true in the event of a successful read operation, false in case of an error.
Implements erhic::EventMC.
Definition at line 30 of file EventSartre.cxx.
View newest version in sPHENIX GitHub at line 30 of file EventSartre.cxx
References bup, dmode, genevent, erhic::EventMC::number, pol, s_cm, trueNu, trueQ2, trueT, trueW2, trueX, trueXpom, and trueY.
const ParticleMC * erhic::EventSartre::ScatteredLepton () const virtual
Returns a pointer to the scattered lepton in the event record. This is the first (only?) particle that matches the following: 1) pdg code equals that of incident lepton beam. 2) status code is 1 i.e. it's a stable/final-state particle. 3) the parent is track 1 or 2
Reimplemented from erhic::EventMC.
Definition at line 49 of file EventSartre.cxx.
View newest version in sPHENIX GitHub at line 49 of file EventSartre.cxx
References erhic::EventMC::BeamLepton(), erhic::Pid::Code(), erhic::EventMC::FinalState(), and erhic::VirtualParticle::Id().
Member Data Documentation
Int_t erhic::EventSartre::bup protected
Definition at line 66 of file EventSartre.h.
View newest version in sPHENIX GitHub at line 66 of file EventSartre.h
Referenced by Parse().
Int_t erhic::EventSartre::dmode protected
Definition at line 65 of file EventSartre.h.
View newest version in sPHENIX GitHub at line 65 of file EventSartre.h
Referenced by Parse().
Int_t erhic::EventSartre::genevent protected
Trials required for this event (dummy right now)
Definition at line 55 of file EventSartre.h.
View newest version in sPHENIX GitHub at line 55 of file EventSartre.h
Referenced by Parse().
Int_t erhic::EventSartre::pol protected
Definition at line 64 of file EventSartre.h.
View newest version in sPHENIX GitHub at line 64 of file EventSartre.h
Referenced by Parse().
Double32_t erhic::EventSartre::s_cm protected
Definition at line 63 of file EventSartre.h.
View newest version in sPHENIX GitHub at line 63 of file EventSartre.h
Referenced by Parse().
Double32_t erhic::EventSartre::trueNu protected
Definition at line 61 of file EventSartre.h.
View newest version in sPHENIX GitHub at line 61 of file EventSartre.h
Referenced by Parse().
Double32_t erhic::EventSartre::trueQ2 protected
Definition at line 57 of file EventSartre.h.
View newest version in sPHENIX GitHub at line 57 of file EventSartre.h
Referenced by Parse().
Double32_t erhic::EventSartre::trueT protected
Definition at line 56 of file EventSartre.h.
View newest version in sPHENIX GitHub at line 56 of file EventSartre.h
Referenced by Parse().
Double32_t erhic::EventSartre::trueW2 protected
Definition at line 60 of file EventSartre.h.
View newest version in sPHENIX GitHub at line 60 of file EventSartre.h
Referenced by Parse().
Double32_t erhic::EventSartre::trueX protected
Definition at line 58 of file EventSartre.h.
View newest version in sPHENIX GitHub at line 58 of file EventSartre.h
Referenced by Parse().
Double32_t erhic::EventSartre::trueXpom protected
Definition at line 62 of file EventSartre.h.
View newest version in sPHENIX GitHub at line 62 of file EventSartre.h
Referenced by Parse().
Double32_t erhic::EventSartre::trueY protected
Definition at line 59 of file EventSartre.h.
View newest version in sPHENIX GitHub at line 59 of file EventSartre.h
Referenced by Parse().
The documentation for this class was generated from the following files:
eic-smear/blob/master/include/eicsmear/erhic/EventSartre.h
eic-smear/blob/master/src/erhic/EventSartre.cxx