EIC Software: FairGeoShapes Class Reference
FairGeoShapes Class Reference
#include <EicRoot/blob/master/geobase/FairGeoShapes.h>
Public Member Functions
FairGeoShapes ()
~FairGeoShapes ()
FairGeoBasicShape * selectShape (FairGeoVolume *)
FairGeoBasicShape * selectShape (const TString &)
Int_t readPoints (std::fstream *, FairGeoVolume *)
Bool_t writePoints (std::fstream *, FairGeoVolume *)
void printPoints (FairGeoVolume *volu)
Protected Attributes
TList * shapes
Private Member Functions
FairGeoShapes (const FairGeoShapes &)
FairGeoShapes & operator= (const FairGeoShapes &)
Detailed Description
manager class for geometry shapes
Author
Ilse koenig
Definition at line 20 of file FairGeoShapes.h.
View newest version in sPHENIX GitHub at line 20 of file FairGeoShapes.h
Constructor & Destructor Documentation
FairGeoShapes::FairGeoShapes (const FairGeoShapes &) private
FairGeoShapes::FairGeoShapes ()
FairGeoShapes::~FairGeoShapes ()
Definition at line 59 of file FairGeoShapes.cxx.
View newest version in sPHENIX GitHub at line 59 of file FairGeoShapes.cxx
References shapes.
Member Function Documentation
FairGeoShapes& FairGeoShapes::operator= (const FairGeoShapes &) private
void FairGeoShapes::printPoints (FairGeoVolume * volu)
Definition at line 149 of file FairGeoShapes.cxx.
View newest version in sPHENIX GitHub at line 149 of file FairGeoShapes.cxx
References FairGeoBasicShape::printPoints(), Acts::UnitConstants::s, and selectShape().
Int_t FairGeoShapes::readPoints (std::fstream * pFile, FairGeoVolume * volu)
Definition at line 128 of file FairGeoShapes.cxx.
View newest version in sPHENIX GitHub at line 128 of file FairGeoShapes.cxx
References FairGeoBasicShape::readPoints(), Acts::UnitConstants::s, and selectShape().
FairGeoBasicShape * FairGeoShapes::selectShape (FairGeoVolume * volu)
Definition at line 67 of file FairGeoShapes.cxx.
View newest version in sPHENIX GitHub at line 67 of file FairGeoShapes.cxx
References FairGeoVolume::getShape(), and name.
Referenced by printPoints(), FairGeoOldAsciiIo::read(), readPoints(), FairGeoSet::readVolumeParams(), and writePoints().
FairGeoBasicShape * FairGeoShapes::selectShape (const TString & name)
Definition at line 77 of file FairGeoShapes.cxx.
View newest version in sPHENIX GitHub at line 77 of file FairGeoShapes.cxx
References Acts::UnitConstants::s, and shapes.
Bool_t FairGeoShapes::writePoints (std::fstream * pFile, FairGeoVolume * volu)
Definition at line 139 of file FairGeoShapes.cxx.
View newest version in sPHENIX GitHub at line 139 of file FairGeoShapes.cxx
References Acts::UnitConstants::s, selectShape(), and FairGeoBasicShape::writePoints().
Member Data Documentation
TList* FairGeoShapes::shapes protected
Definition at line 26 of file FairGeoShapes.h.
View newest version in sPHENIX GitHub at line 26 of file FairGeoShapes.h
Referenced by selectShape(), and ~FairGeoShapes().
The documentation for this class was generated from the following files:
EicRoot/blob/master/geobase/FairGeoShapes.h
EicRoot/blob/master/geobase/FairGeoShapes.cxx