EIC Software: MediaSlice Class Reference
MediaSlice Class Reference
#include <EicRoot/blob/master/eic/htc/MediaSlice.h>
Public Member Functions
MediaSlice (const MediaLayer *mlayer, double z0, double thickness)
~MediaSlice ()
const MediaLayer * GetMediaLayer () const
double GetZ0 () const
double GetThickness () const
double GetReducedRadiationLength () const
Public Attributes
double Cms
double _RCxx [2][4][4]
double _RCyy [2][4][4]
double _RCxy [2][4][4]
Private Attributes
const MediaLayer * mMediaLayer
double mZ0
double mThickness
double mReducedRadiationLength
Detailed Description
Definition at line 15 of file MediaSlice.h.
View newest version in sPHENIX GitHub at line 15 of file MediaSlice.h
Constructor & Destructor Documentation
MediaSlice::MediaSlice (const MediaLayer * mlayer, double z0, double thickness) inline
Definition at line 17 of file MediaSlice.h.
View newest version in sPHENIX GitHub at line 17 of file MediaSlice.h
References _RCxx, _RCxy, _RCyy, MediaLayer::GetMaterial(), and mReducedRadiationLength.
MediaSlice::~MediaSlice () inline
Definition at line 27 of file MediaSlice.h.
View newest version in sPHENIX GitHub at line 27 of file MediaSlice.h
Member Function Documentation
const MediaLayer* MediaSlice::GetMediaLayer () const inline
Definition at line 29 of file MediaSlice.h.
View newest version in sPHENIX GitHub at line 29 of file MediaSlice.h
References mMediaLayer.
Referenced by MediaSliceArray::GetDE(), and TrKalmanNodeLocation::InitializeProcessNoiseMatrices().
double MediaSlice::GetReducedRadiationLength () const inline
Definition at line 33 of file MediaSlice.h.
View newest version in sPHENIX GitHub at line 33 of file MediaSlice.h
References mReducedRadiationLength.
Referenced by TrKalmanNodeLocation::InitializeProcessNoiseMatrices().
double MediaSlice::GetThickness () const inline
Definition at line 31 of file MediaSlice.h.
View newest version in sPHENIX GitHub at line 31 of file MediaSlice.h
References mThickness.
Referenced by MediaSliceArray::GetDE(), TrKalmanNodeLocation::InitializeProcessNoiseMatrices(), and MediaSliceArray::MediaSliceArray().
double MediaSlice::GetZ0 () const inline
Definition at line 30 of file MediaSlice.h.
View newest version in sPHENIX GitHub at line 30 of file MediaSlice.h
References mZ0.
Referenced by TrKalmanNodeLocation::InitializeProcessNoiseMatrices().
Member Data Documentation
double MediaSlice::_RCxx[2][4][4]
Definition at line 40 of file MediaSlice.h.
View newest version in sPHENIX GitHub at line 40 of file MediaSlice.h
Referenced by TrKalmanNodeLocation::InitializeProcessNoiseMatrices(), and MediaSlice().
double MediaSlice::_RCxy[2][4][4]
Definition at line 40 of file MediaSlice.h.
View newest version in sPHENIX GitHub at line 40 of file MediaSlice.h
Referenced by TrKalmanNodeLocation::InitializeProcessNoiseMatrices(), and MediaSlice().
double MediaSlice::_RCyy[2][4][4]
Definition at line 40 of file MediaSlice.h.
View newest version in sPHENIX GitHub at line 40 of file MediaSlice.h
Referenced by TrKalmanNodeLocation::InitializeProcessNoiseMatrices(), and MediaSlice().
double MediaSlice::Cms
Definition at line 33 of file MediaSlice.h.
View newest version in sPHENIX GitHub at line 33 of file MediaSlice.h
const MediaLayer* MediaSlice::mMediaLayer private
Definition at line 43 of file MediaSlice.h.
View newest version in sPHENIX GitHub at line 43 of file MediaSlice.h
Referenced by GetMediaLayer().
double MediaSlice::mReducedRadiationLength private
Definition at line 47 of file MediaSlice.h.
View newest version in sPHENIX GitHub at line 47 of file MediaSlice.h
Referenced by GetReducedRadiationLength(), and MediaSlice().
double MediaSlice::mThickness private
Definition at line 45 of file MediaSlice.h.
View newest version in sPHENIX GitHub at line 45 of file MediaSlice.h
Referenced by GetThickness().
double MediaSlice::mZ0 private
Definition at line 45 of file MediaSlice.h.
View newest version in sPHENIX GitHub at line 45 of file MediaSlice.h
Referenced by GetZ0().
The documentation for this class was generated from the following file:
EicRoot/blob/master/eic/htc/MediaSlice.h