EIC Software: PndPidCandidate Class Reference
PndPidCandidate Class Reference
#include <EicRoot/blob/master/pnddata/PidData/PndPidCandidate.h>
Public Member Functions
PndPidCandidate ()
PndPidCandidate (Int_t charge, TVector3 &pos, TLorentzVector &p4, TMatrixD &cov7)
PndPidCandidate (Int_t charge, TVector3 &pos, TLorentzVector &p4)
~PndPidCandidate ()
Int_t GetCharge () const
TVector3 GetPosition () const
TVector3 GetMomentum () const
Double_t GetEnergy () const
TLorentzVector GetLorentzVector () const
TVector3 GetFirstHit () const
TVector3 GetLastHit () const
const Float_t * GetErrorP7 () const
const Float_t * GetParams () const
const Float_t * GetCov () const
TMatrixD & Cov7 () const
TMatrixD & P4Cov () const
Int_t GetMcIndex () const
Int_t GetTrackIndex () const
Int_t GetTrackBranch () const
Int_t GetDegreesOfFreedom () const
Int_t GetFitStatus () const
Float_t GetChiSquared () const
Float_t GetElectronPidLH () const
Float_t GetMuonPidLH () const
Float_t GetPionPidLH () const
Float_t GetKaonPidLH () const
Float_t GetProtonPidLH () const
void Lock ()
void Unlock ()
bool IsLocked ()
void SetCharge (Int_t charge)
void SetPosition (TVector3 &pos)
void SetMomentum (TVector3 &mom)
void SetEnergy (Double_t en)
void SetLorentzVector (TLorentzVector &p4)
void SetFirstHit (TVector3 &pos)
void SetLastHit (TVector3 &pos)
void SetCov7 (const TMatrixD &cov7)
void SetP4Cov (const TMatrixD &covP4)
void SetMcIndex (int idx)
void SetTrackIndex (int idx)
void SetTrackBranch (int idx)
void SetHelixParams (Double_t *par)
void SetHelixCov (Double_t *cov)
void SetDegreesOfFreedom (Int_t val)
void SetFitStatus (Int_t val)
void SetChiSquared (Double_t val)
void SetElectronPidLH (Double_t val)
void SetMuonPidLH (Double_t val)
void SetPionPidLH (Double_t val)
void SetKaonPidLH (Double_t val)
void SetProtonPidLH (Double_t val)
unsigned GetParameterizationCount (void) const
const NaiveTrackParameterization * GetParameterization (unsigned ih) const
const NaiveTrackParameterization * GetNearestParameterization (const TVector3 &x0, const TVector3 &n0)
const NaiveTrackParameterization * GetNearestParameterization (double r)
void SetDefault ()
Public Member Functions inherited from FairRecoCandidate
FairRecoCandidate ()
virtual ~FairRecoCandidate ()
void PrintOn (std::ostream &o=std::cout) const
Public Member Functions inherited from FairMultiLinkedData
FairMultiLinkedData ()
Default constructor.
FairMultiLinkedData (std::set< FairLink > links, Bool_t persistanceCheck=kTRUE)
Constructor.
FairMultiLinkedData (TString dataType, std::vector< Int_t > links, Int_t fileId=-1, Int_t evtId=-1, Bool_t persistanceCheck=kTRUE, Bool_t bypass=kFALSE, Float_t mult=1.0)
Constructor.
FairMultiLinkedData (Int_t dataType, std::vector< Int_t > links, Int_t fileId=-1, Int_t evtId=-1, Bool_t persistanceCheck=kTRUE, Bool_t bypass=kFALSE, Float_t mult=1.0)
Constructor.
virtual ~FairMultiLinkedData ()
virtual std::set< FairLink > GetLinks () const
returns stored links as FairLinks
virtual Int_t GetNLinks () const
returns the number of stored links
virtual FairLink GetLink (Int_t pos) const
returns the FairLink at the given position
virtual FairMultiLinkedData GetLinksWithType (Int_t type) const
Gives you a list of links which contain the given type.
TObject * GetData (FairLink &myLink)
Get the TObject the Link is pointing to.
virtual Int_t GetDefaultType ()
Bool_t GetPersistanceCheck ()
Returns the value of PersistanceCheck.
Int_t GetVerbose ()
Returns the verbosity level.
virtual void SetDefaultType (Int_t type)
virtual void SetPersistanceCheck (Bool_t check)
Controls if a persistance check of a link is done or not.
virtual void SetVerbose (Int_t level)
Sets the verbosity level.
virtual void SetLinks (FairMultiLinkedData links, Float_t mult=1.0)
Sets the links as vector of FairLink.
virtual void SetLink (FairLink link, Bool_t bypass=kFALSE, Float_t mult=1.0)
Sets the Links with a single FairLink.
virtual void AddLinks (FairMultiLinkedData links, Float_t mult=1.0)
Adds a List of FairLinks (FairMultiLinkedData) to fLinks.
virtual void AddLink (FairLink link, Bool_t bypass=kFALSE, Float_t mult=1.0)
Adds a FairLink link at the end of fLinks. If multi is kTRUE a link is allowed more than once otherwise it is stored only once.
virtual void InsertLink (FairLink link)
Inserts a link into the list of links without persistance checking.
virtual void AddAllWeights (Double_t weight)
Adds weight to all Links.
virtual void SetAllWeights (Double_t weight)
Sets a common weight for Links.
virtual void MultiplyAllWeights (Double_t weight)
Multiplies all Links with weight.
virtual Bool_t IsLinkInList (FairLink link)
Test if a given link is in fLinks.
virtual Bool_t IsLinkInList (Int_t type, Int_t index)
Same as IsLinkInList(FairLink) just with type and index given separately.
virtual Int_t LinkPosInList (FairLink link)
returns position of link in fLinks. If it is not in the list -1 is returned
virtual Int_t LinkPosInList (Int_t type, Int_t index)
Same as LinkPosInList(FairLink)
virtual void DeleteLink (FairLink link)
Deletes a link ouf of fLinks.
virtual void DeleteLink (Int_t type, Int_t index)
Deletes a link ouf of fLinks.
virtual void Reset ()
virtual void ResetLinks ()
Clears fLinks.
void Print (std::ostream &out=std::cout) const
Output.
Public Attributes
std::vector
< NaiveTrackParameterization > mParameterizations
Protected Attributes
Bool_t fLocked
Char_t fCharge
Float_t fXposition
Float_t fYposition
Float_t fZposition
Double_t fXmomentum
Double_t fYmomentum
Double_t fZmomentum
Double_t fEnergy
Float_t fFirstHitX
Float_t fFirstHitY
Float_t fFirstHitZ
Float_t fLastHitX
Float_t fLastHitY
Float_t fLastHitZ
Int_t fMcIndex
Int_t fTrackIndex
Int_t fTrackBranch
Float_t fErrP7 [28]
Float_t fParams [5]
Float_t fCov [15]
Int_t fDegreesOfFreedom
Int_t fFitStatus
Float_t fChiSquared
Additional Inherited Members
Protected Member Functions inherited from FairMultiLinkedData
virtual void SimpleAddLinks (Int_t fileId, Int_t evtId, Int_t dataType, std::vector< Int_t > links, Bool_t bypass, Float_t mult)
ClassDef (FairMultiLinkedData, 3)
Detailed Description
Definition at line 34 of file PndPidCandidate.h.
View newest version in sPHENIX GitHub at line 34 of file PndPidCandidate.h
Constructor & Destructor Documentation
PndPidCandidate::PndPidCandidate ()
Definition at line 20 of file PndPidCandidate.cxx.
View newest version in sPHENIX GitHub at line 20 of file PndPidCandidate.cxx
References SetDefault().
PndPidCandidate::PndPidCandidate (Int_t charge, TVector3 & pos, TLorentzVector & p4, TMatrixD & cov7)
Definition at line 94 of file PndPidCandidate.cxx.
View newest version in sPHENIX GitHub at line 94 of file PndPidCandidate.cxx
References SetCharge(), SetCov7(), SetDefault(), SetLorentzVector(), and SetPosition().
PndPidCandidate::PndPidCandidate (Int_t charge, TVector3 & pos, TLorentzVector & p4)
Definition at line 172 of file PndPidCandidate.cxx.
View newest version in sPHENIX GitHub at line 172 of file PndPidCandidate.cxx
References SetCharge(), SetDefault(), SetLorentzVector(), and SetPosition().
PndPidCandidate::~PndPidCandidate ()
Definition at line 250 of file PndPidCandidate.cxx.
View newest version in sPHENIX GitHub at line 250 of file PndPidCandidate.cxx
Member Function Documentation
TMatrixD & PndPidCandidate::Cov7 () const virtual
Implements FairRecoCandidate.
Definition at line 254 of file PndPidCandidate.cxx.
View newest version in sPHENIX GitHub at line 254 of file PndPidCandidate.cxx
References Acts::Test::cov, and fErrP7.
Int_t PndPidCandidate::GetCharge () const inline virtual
Implements FairRecoCandidate.
Definition at line 53 of file PndPidCandidate.h.
View newest version in sPHENIX GitHub at line 53 of file PndPidCandidate.h
References fCharge.
Referenced by EicEventAssembler::PerformPidCalculations().
Float_t PndPidCandidate::GetChiSquared () const inline virtual
Implements FairRecoCandidate.
Definition at line 149 of file PndPidCandidate.h.
View newest version in sPHENIX GitHub at line 149 of file PndPidCandidate.h
References fChiSquared.
const Float_t* PndPidCandidate::GetCov () const inline virtual
Implements FairRecoCandidate.
Definition at line 64 of file PndPidCandidate.h.
View newest version in sPHENIX GitHub at line 64 of file PndPidCandidate.h
References fCov.
Referenced by EicEventAssembler::Exec().
Int_t PndPidCandidate::GetDegreesOfFreedom () const inline virtual
Implements FairRecoCandidate.
Definition at line 147 of file PndPidCandidate.h.
View newest version in sPHENIX GitHub at line 147 of file PndPidCandidate.h
References fDegreesOfFreedom.
Referenced by analysis().
Float_t PndPidCandidate::GetElectronPidLH () const inline virtual
Implements FairRecoCandidate.
Definition at line 152 of file PndPidCandidate.h.
View newest version in sPHENIX GitHub at line 152 of file PndPidCandidate.h
Double_t PndPidCandidate::GetEnergy () const inline virtual
Implements FairRecoCandidate.
Definition at line 56 of file PndPidCandidate.h.
View newest version in sPHENIX GitHub at line 56 of file PndPidCandidate.h
References fEnergy.
const Float_t* PndPidCandidate::GetErrorP7 () const inline virtual
Implements FairRecoCandidate.
Definition at line 62 of file PndPidCandidate.h.
View newest version in sPHENIX GitHub at line 62 of file PndPidCandidate.h
References fErrP7.
TVector3 PndPidCandidate::GetFirstHit () const inline virtual
Implements FairRecoCandidate.
Definition at line 59 of file PndPidCandidate.h.
View newest version in sPHENIX GitHub at line 59 of file PndPidCandidate.h
References fFirstHitX.
Int_t PndPidCandidate::GetFitStatus () const inline virtual
Implements FairRecoCandidate.
Definition at line 148 of file PndPidCandidate.h.
View newest version in sPHENIX GitHub at line 148 of file PndPidCandidate.h
References fFitStatus.
Float_t PndPidCandidate::GetKaonPidLH () const inline virtual
Implements FairRecoCandidate.
Definition at line 155 of file PndPidCandidate.h.
View newest version in sPHENIX GitHub at line 155 of file PndPidCandidate.h
TVector3 PndPidCandidate::GetLastHit () const inline virtual
Implements FairRecoCandidate.
Definition at line 60 of file PndPidCandidate.h.
View newest version in sPHENIX GitHub at line 60 of file PndPidCandidate.h
References fLastHitX, fLastHitY, and fLastHitZ.
TLorentzVector PndPidCandidate::GetLorentzVector () const inline virtual
Implements FairRecoCandidate.
Definition at line 57 of file PndPidCandidate.h.
View newest version in sPHENIX GitHub at line 57 of file PndPidCandidate.h
References fEnergy, fXmomentum, fYmomentum, and fZmomentum.
Referenced by EicSmearTask::Exec().
Int_t PndPidCandidate::GetMcIndex () const inline virtual
Implements FairRecoCandidate.
Definition at line 67 of file PndPidCandidate.h.
View newest version in sPHENIX GitHub at line 67 of file PndPidCandidate.h
References fMcIndex.
Referenced by analysis(), EicSmearTask::Exec(), and EicEventAssembler::Exec().
TVector3 PndPidCandidate::GetMomentum () const inline virtual
Implements FairRecoCandidate.
Definition at line 55 of file PndPidCandidate.h.
View newest version in sPHENIX GitHub at line 55 of file PndPidCandidate.h
References fXmomentum, fYmomentum, and fZmomentum.
Referenced by analysis(), and EicEventAssembler::Exec().
Float_t PndPidCandidate::GetMuonPidLH () const inline virtual
Implements FairRecoCandidate.
Definition at line 153 of file PndPidCandidate.h.
View newest version in sPHENIX GitHub at line 153 of file PndPidCandidate.h
const NaiveTrackParameterization * PndPidCandidate::GetNearestParameterization (const TVector3 & x0, const TVector3 & n0)
Definition at line 428 of file PndPidCandidate.cxx.
View newest version in sPHENIX GitHub at line 428 of file PndPidCandidate.cxx
References NaiveTrackParameterization::DistanceToPlane(), and mParameterizations.
Referenced by analysis(), and stvector().
const NaiveTrackParameterization * PndPidCandidate::GetNearestParameterization (double r)
Definition at line 446 of file PndPidCandidate.cxx.
View newest version in sPHENIX GitHub at line 446 of file PndPidCandidate.cxx
References NaiveTrackParameterization::GetMoCaPosition(), mParameterizations, pos(), x, and y.
const NaiveTrackParameterization* PndPidCandidate::GetParameterization (unsigned ih) const inline
Definition at line 276 of file PndPidCandidate.h.
View newest version in sPHENIX GitHub at line 276 of file PndPidCandidate.h
References mParameterizations.
Referenced by stvector().
unsigned PndPidCandidate::GetParameterizationCount (void) const inline
Definition at line 275 of file PndPidCandidate.h.
View newest version in sPHENIX GitHub at line 275 of file PndPidCandidate.h
References mParameterizations.
Referenced by stvector().
const Float_t* PndPidCandidate::GetParams () const inline virtual
Implements FairRecoCandidate.
Definition at line 63 of file PndPidCandidate.h.
View newest version in sPHENIX GitHub at line 63 of file PndPidCandidate.h
References fParams.
Float_t PndPidCandidate::GetPionPidLH () const inline virtual
Implements FairRecoCandidate.
Definition at line 154 of file PndPidCandidate.h.
View newest version in sPHENIX GitHub at line 154 of file PndPidCandidate.h
TVector3 PndPidCandidate::GetPosition () const inline virtual
Implements FairRecoCandidate.
Definition at line 54 of file PndPidCandidate.h.
View newest version in sPHENIX GitHub at line 54 of file PndPidCandidate.h
References fXposition, fYposition, and fZposition.
Referenced by EicEventAssembler::Exec().
Float_t PndPidCandidate::GetProtonPidLH () const inline virtual
Implements FairRecoCandidate.
Definition at line 156 of file PndPidCandidate.h.
View newest version in sPHENIX GitHub at line 156 of file PndPidCandidate.h
Int_t PndPidCandidate::GetTrackBranch () const inline virtual
Implements FairRecoCandidate.
Definition at line 69 of file PndPidCandidate.h.
View newest version in sPHENIX GitHub at line 69 of file PndPidCandidate.h
References fTrackBranch.
Int_t PndPidCandidate::GetTrackIndex () const inline virtual
Implements FairRecoCandidate.
Definition at line 68 of file PndPidCandidate.h.
View newest version in sPHENIX GitHub at line 68 of file PndPidCandidate.h
References fTrackIndex.
bool PndPidCandidate::IsLocked () inline
Definition at line 166 of file PndPidCandidate.h.
View newest version in sPHENIX GitHub at line 166 of file PndPidCandidate.h
References fLocked.
void PndPidCandidate::Lock () inline
Definition at line 164 of file PndPidCandidate.h.
View newest version in sPHENIX GitHub at line 164 of file PndPidCandidate.h
References fLocked.
TMatrixD & PndPidCandidate::P4Cov () const virtual
Implements FairRecoCandidate.
Definition at line 283 of file PndPidCandidate.cxx.
View newest version in sPHENIX GitHub at line 283 of file PndPidCandidate.cxx
References fErrP7.
void PndPidCandidate::SetCharge (Int_t charge) inline
Definition at line 172 of file PndPidCandidate.h.
View newest version in sPHENIX GitHub at line 172 of file PndPidCandidate.h
References charge, and fCharge.
Referenced by PndPidCorrelator::GetTrackInfo(), and PndPidCandidate().
void PndPidCandidate::SetChiSquared (Double_t val) inline
Definition at line 265 of file PndPidCandidate.h.
View newest version in sPHENIX GitHub at line 265 of file PndPidCandidate.h
References fChiSquared.
Referenced by PndPidCorrelator::GetTrackInfo().
void PndPidCandidate::SetCov7 (const TMatrixD & cov7)
Definition at line 307 of file PndPidCandidate.cxx.
View newest version in sPHENIX GitHub at line 307 of file PndPidCandidate.cxx
References fErrP7.
Referenced by PndPidCorrelator::GetTrackInfo(), and PndPidCandidate().
void PndPidCandidate::SetDefault ()
Definition at line 349 of file PndPidCandidate.cxx.
View newest version in sPHENIX GitHub at line 349 of file PndPidCandidate.cxx
References fCharge, fChiSquared, fCov, fDegreesOfFreedom, fEnergy, fErrP7, fFirstHitX, fFirstHitY, fFirstHitZ, fFitStatus, fLastHitX, fLastHitY, fLastHitZ, fLocked, fMcIndex, fParams, fTrackBranch, fTrackIndex, fXmomentum, fXposition, fYmomentum, fYposition, fZmomentum, and fZposition.
Referenced by PndPidCandidate().
void PndPidCandidate::SetDegreesOfFreedom (Int_t val) inline
Definition at line 263 of file PndPidCandidate.h.
View newest version in sPHENIX GitHub at line 263 of file PndPidCandidate.h
References fDegreesOfFreedom.
Referenced by PndPidCorrelator::GetTrackInfo().
void PndPidCandidate::SetElectronPidLH (Double_t val) inline
Definition at line 268 of file PndPidCandidate.h.
View newest version in sPHENIX GitHub at line 268 of file PndPidCandidate.h
void PndPidCandidate::SetEnergy (Double_t en) inline
Definition at line 175 of file PndPidCandidate.h.
View newest version in sPHENIX GitHub at line 175 of file PndPidCandidate.h
References fEnergy.
Referenced by PndPidCorrelator::GetTrackInfo().
void PndPidCandidate::SetFirstHit (TVector3 & pos) inline
Definition at line 178 of file PndPidCandidate.h.
View newest version in sPHENIX GitHub at line 178 of file PndPidCandidate.h
References fFirstHitX, fFirstHitY, and fFirstHitZ.
Referenced by PndPidCorrelator::GetTrackInfo().
void PndPidCandidate::SetFitStatus (Int_t val) inline
Definition at line 264 of file PndPidCandidate.h.
View newest version in sPHENIX GitHub at line 264 of file PndPidCandidate.h
References fFitStatus.
Referenced by PndPidCorrelator::GetTrackInfo().
void PndPidCandidate::SetHelixCov (Double_t * cov) inline
Definition at line 188 of file PndPidCandidate.h.
View newest version in sPHENIX GitHub at line 188 of file PndPidCandidate.h
References fCov.
Referenced by PndPidCorrelator::GetTrackInfo().
void PndPidCandidate::SetHelixParams (Double_t * par) inline
Definition at line 187 of file PndPidCandidate.h.
View newest version in sPHENIX GitHub at line 187 of file PndPidCandidate.h
References fParams.
Referenced by PndPidCorrelator::GetTrackInfo().
void PndPidCandidate::SetKaonPidLH (Double_t val) inline
Definition at line 271 of file PndPidCandidate.h.
View newest version in sPHENIX GitHub at line 271 of file PndPidCandidate.h
void PndPidCandidate::SetLastHit (TVector3 & pos) inline
Definition at line 179 of file PndPidCandidate.h.
View newest version in sPHENIX GitHub at line 179 of file PndPidCandidate.h
References fLastHitX, fLastHitY, and fLastHitZ.
Referenced by PndPidCorrelator::GetTrackInfo().
void PndPidCandidate::SetLorentzVector (TLorentzVector & p4)
Definition at line 299 of file PndPidCandidate.cxx.
View newest version in sPHENIX GitHub at line 299 of file PndPidCandidate.cxx
References fEnergy, fXmomentum, fYmomentum, and fZmomentum.
Referenced by PndPidCandidate().
void PndPidCandidate::SetMcIndex (int idx) inline
Definition at line 183 of file PndPidCandidate.h.
View newest version in sPHENIX GitHub at line 183 of file PndPidCandidate.h
References fMcIndex.
Referenced by PndPidCorrelator::ConstructChargedCandidate().
void PndPidCandidate::SetMomentum (TVector3 & mom) inline
Definition at line 174 of file PndPidCandidate.h.
View newest version in sPHENIX GitHub at line 174 of file PndPidCandidate.h
References fXmomentum, fYmomentum, and fZmomentum.
Referenced by PndPidCorrelator::GetTrackInfo().
void PndPidCandidate::SetMuonPidLH (Double_t val) inline
Definition at line 269 of file PndPidCandidate.h.
View newest version in sPHENIX GitHub at line 269 of file PndPidCandidate.h
void PndPidCandidate::SetP4Cov (const TMatrixD & covP4)
Definition at line 328 of file PndPidCandidate.cxx.
View newest version in sPHENIX GitHub at line 328 of file PndPidCandidate.cxx
References fErrP7.
void PndPidCandidate::SetPionPidLH (Double_t val) inline
Definition at line 270 of file PndPidCandidate.h.
View newest version in sPHENIX GitHub at line 270 of file PndPidCandidate.h
void PndPidCandidate::SetPosition (TVector3 & pos) inline
Definition at line 173 of file PndPidCandidate.h.
View newest version in sPHENIX GitHub at line 173 of file PndPidCandidate.h
References fXposition, fYposition, and fZposition.
Referenced by PndPidCorrelator::GetTrackInfo(), and PndPidCandidate().
void PndPidCandidate::SetProtonPidLH (Double_t val) inline
Definition at line 272 of file PndPidCandidate.h.
View newest version in sPHENIX GitHub at line 272 of file PndPidCandidate.h
void PndPidCandidate::SetTrackBranch (int idx) inline
Definition at line 185 of file PndPidCandidate.h.
View newest version in sPHENIX GitHub at line 185 of file PndPidCandidate.h
References fTrackBranch.
Referenced by PndPidCorrelator::ConstructChargedCandidate().
void PndPidCandidate::SetTrackIndex (int idx) inline
Definition at line 184 of file PndPidCandidate.h.
View newest version in sPHENIX GitHub at line 184 of file PndPidCandidate.h
References fTrackIndex.
Referenced by PndPidCorrelator::ConstructChargedCandidate().
void PndPidCandidate::Unlock () inline
Definition at line 165 of file PndPidCandidate.h.
View newest version in sPHENIX GitHub at line 165 of file PndPidCandidate.h
References fLocked.
Member Data Documentation
Char_t PndPidCandidate::fCharge protected
Definition at line 289 of file PndPidCandidate.h.
View newest version in sPHENIX GitHub at line 289 of file PndPidCandidate.h
Referenced by GetCharge(), SetCharge(), and SetDefault().
Float_t PndPidCandidate::fChiSquared protected
Definition at line 387 of file PndPidCandidate.h.
View newest version in sPHENIX GitHub at line 387 of file PndPidCandidate.h
Referenced by GetChiSquared(), SetChiSquared(), and SetDefault().
Float_t PndPidCandidate::fCov[15] protected
Definition at line 312 of file PndPidCandidate.h.
View newest version in sPHENIX GitHub at line 312 of file PndPidCandidate.h
Referenced by GetCov(), SetDefault(), and SetHelixCov().
Int_t PndPidCandidate::fDegreesOfFreedom protected
Definition at line 385 of file PndPidCandidate.h.
View newest version in sPHENIX GitHub at line 385 of file PndPidCandidate.h
Referenced by GetDegreesOfFreedom(), SetDefault(), and SetDegreesOfFreedom().
Double_t PndPidCandidate::fEnergy protected
Definition at line 294 of file PndPidCandidate.h.
View newest version in sPHENIX GitHub at line 294 of file PndPidCandidate.h
Referenced by GetEnergy(), GetLorentzVector(), SetDefault(), SetEnergy(), and SetLorentzVector().
Float_t PndPidCandidate::fErrP7[28] protected
Definition at line 310 of file PndPidCandidate.h.
View newest version in sPHENIX GitHub at line 310 of file PndPidCandidate.h
Referenced by Cov7(), GetErrorP7(), P4Cov(), SetCov7(), SetDefault(), and SetP4Cov().
Float_t PndPidCandidate::fFirstHitX protected
Definition at line 299 of file PndPidCandidate.h.
View newest version in sPHENIX GitHub at line 299 of file PndPidCandidate.h
Referenced by GetFirstHit(), SetDefault(), and SetFirstHit().
Float_t PndPidCandidate::fFirstHitY protected
Definition at line 299 of file PndPidCandidate.h.
View newest version in sPHENIX GitHub at line 299 of file PndPidCandidate.h
Referenced by SetDefault(), and SetFirstHit().
Float_t PndPidCandidate::fFirstHitZ protected
Definition at line 299 of file PndPidCandidate.h.
View newest version in sPHENIX GitHub at line 299 of file PndPidCandidate.h
Referenced by SetDefault(), and SetFirstHit().
Int_t PndPidCandidate::fFitStatus protected
Definition at line 386 of file PndPidCandidate.h.
View newest version in sPHENIX GitHub at line 386 of file PndPidCandidate.h
Referenced by GetFitStatus(), SetDefault(), and SetFitStatus().
Float_t PndPidCandidate::fLastHitX protected
Definition at line 303 of file PndPidCandidate.h.
View newest version in sPHENIX GitHub at line 303 of file PndPidCandidate.h
Referenced by GetLastHit(), SetDefault(), and SetLastHit().
Float_t PndPidCandidate::fLastHitY protected
Definition at line 303 of file PndPidCandidate.h.
View newest version in sPHENIX GitHub at line 303 of file PndPidCandidate.h
Referenced by GetLastHit(), SetDefault(), and SetLastHit().
Float_t PndPidCandidate::fLastHitZ protected
Definition at line 303 of file PndPidCandidate.h.
View newest version in sPHENIX GitHub at line 303 of file PndPidCandidate.h
Referenced by GetLastHit(), SetDefault(), and SetLastHit().
Bool_t PndPidCandidate::fLocked protected
Definition at line 286 of file PndPidCandidate.h.
View newest version in sPHENIX GitHub at line 286 of file PndPidCandidate.h
Referenced by IsLocked(), Lock(), SetDefault(), and Unlock().
Int_t PndPidCandidate::fMcIndex protected
Definition at line 307 of file PndPidCandidate.h.
View newest version in sPHENIX GitHub at line 307 of file PndPidCandidate.h
Referenced by GetMcIndex(), SetDefault(), and SetMcIndex().
Float_t PndPidCandidate::fParams[5] protected
Definition at line 311 of file PndPidCandidate.h.
View newest version in sPHENIX GitHub at line 311 of file PndPidCandidate.h
Referenced by GetParams(), SetDefault(), and SetHelixParams().
Int_t PndPidCandidate::fTrackBranch protected
Definition at line 309 of file PndPidCandidate.h.
View newest version in sPHENIX GitHub at line 309 of file PndPidCandidate.h
Referenced by GetTrackBranch(), SetDefault(), and SetTrackBranch().
Int_t PndPidCandidate::fTrackIndex protected
Definition at line 308 of file PndPidCandidate.h.
View newest version in sPHENIX GitHub at line 308 of file PndPidCandidate.h
Referenced by GetTrackIndex(), SetDefault(), and SetTrackIndex().
Double_t PndPidCandidate::fXmomentum protected
Definition at line 294 of file PndPidCandidate.h.
View newest version in sPHENIX GitHub at line 294 of file PndPidCandidate.h
Referenced by GetLorentzVector(), GetMomentum(), SetDefault(), SetLorentzVector(), and SetMomentum().
Float_t PndPidCandidate::fXposition protected
Definition at line 290 of file PndPidCandidate.h.
View newest version in sPHENIX GitHub at line 290 of file PndPidCandidate.h
Referenced by GetPosition(), SetDefault(), and SetPosition().
Double_t PndPidCandidate::fYmomentum protected
Definition at line 294 of file PndPidCandidate.h.
View newest version in sPHENIX GitHub at line 294 of file PndPidCandidate.h
Referenced by GetLorentzVector(), GetMomentum(), SetDefault(), SetLorentzVector(), and SetMomentum().
Float_t PndPidCandidate::fYposition protected
Definition at line 290 of file PndPidCandidate.h.
View newest version in sPHENIX GitHub at line 290 of file PndPidCandidate.h
Referenced by GetPosition(), SetDefault(), and SetPosition().
Double_t PndPidCandidate::fZmomentum protected
Definition at line 294 of file PndPidCandidate.h.
View newest version in sPHENIX GitHub at line 294 of file PndPidCandidate.h
Referenced by GetLorentzVector(), GetMomentum(), SetDefault(), SetLorentzVector(), and SetMomentum().
Float_t PndPidCandidate::fZposition protected
Definition at line 290 of file PndPidCandidate.h.
View newest version in sPHENIX GitHub at line 290 of file PndPidCandidate.h
Referenced by GetPosition(), SetDefault(), and SetPosition().
std::vector<NaiveTrackParameterization> PndPidCandidate::mParameterizations
Definition at line 281 of file PndPidCandidate.h.
View newest version in sPHENIX GitHub at line 281 of file PndPidCandidate.h
Referenced by PndPidCorrelator::ConstructChargedCandidate(), GetNearestParameterization(), GetParameterization(), and GetParameterizationCount().
The documentation for this class was generated from the following files:
EicRoot/blob/master/pnddata/PidData/PndPidCandidate.h
EicRoot/blob/master/pnddata/PidData/PndPidCandidate.cxx