EIC Software: lorentzVector Class Reference
lorentzVector Class Reference
#include <estarlight/blob/master/include/lorentzvector.h>
Public Member Functions
lorentzVector ()
virtual ~lorentzVector ()
lorentzVector (double x, double y, double z, double t)
void SetXYZT (double x, double y, double z, double t)
void SetPxPyPzE (double px, double py, double pz, double e)
double GetPx () const
double GetPy () const
double GetPz () const
double GetE () const
virtual void reflect ()
lorentzVector & operator+= (const lorentzVector &vec)
lorentzVector & operator-= (const lorentzVector &vec)
double M2 () const
double M () const
vector3 BoostVector () const
void Boost (const vector3 &beta)
Private Attributes
vector3 fSpaceVec
double fTime
Friends
std::ostream & operator<< (std::ostream &out, const lorentzVector &vec)
Detailed Description
Definition at line 42 of file lorentzvector.h.
View newest version in sPHENIX GitHub at line 42 of file lorentzvector.h
Constructor & Destructor Documentation
lorentzVector::lorentzVector ()
Definition at line 37 of file lorentzvector.cpp.
View newest version in sPHENIX GitHub at line 37 of file lorentzvector.cpp
lorentzVector::~lorentzVector () virtual
Definition at line 49 of file lorentzvector.cpp.
View newest version in sPHENIX GitHub at line 49 of file lorentzvector.cpp
lorentzVector::lorentzVector (double x, double y, double z, double t)
Definition at line 43 of file lorentzvector.cpp.
View newest version in sPHENIX GitHub at line 43 of file lorentzvector.cpp
Member Function Documentation
void lorentzVector::Boost (const vector3 & beta) inline
Definition at line 82 of file lorentzvector.h.
View newest version in sPHENIX GitHub at line 82 of file lorentzvector.h
References fSpaceVec, fTime, gamma(), vector3::Mag2(), SetXYZT(), vector3::X(), vector3::Y(), and vector3::Z().
Referenced by nBodyPhaseSpaceGen::calcEventKinematics(), and starlightPythia::produceEvent().
vector3 lorentzVector::BoostVector () const inline
Definition at line 80 of file lorentzvector.h.
View newest version in sPHENIX GitHub at line 80 of file lorentzvector.h
References fSpaceVec, fTime, vector3::X(), vector3::Y(), and vector3::Z().
Referenced by nBodyPhaseSpaceGen::calcEventKinematics().
double lorentzVector::GetE () const inline
Definition at line 57 of file lorentzvector.h.
View newest version in sPHENIX GitHub at line 57 of file lorentzvector.h
References fTime.
Referenced by pythiaDecayer::addParticle(), starlightParticle::reflect(), hepMC3Writer::writeEvent(), eventFileWriter::writeEvent(), and eventFileWriter::writeEventLUND().
double lorentzVector::GetPx () const inline
Definition at line 54 of file lorentzvector.h.
View newest version in sPHENIX GitHub at line 54 of file lorentzvector.h
References fSpaceVec, and vector3::GetVector().
Referenced by pythiaDecayer::addParticle(), starlightParticle::reflect(), hepMC3Writer::writeEvent(), eventFileWriter::writeEvent(), and eventFileWriter::writeEventLUND().
double lorentzVector::GetPy () const inline
Definition at line 55 of file lorentzvector.h.
View newest version in sPHENIX GitHub at line 55 of file lorentzvector.h
References fSpaceVec, and vector3::GetVector().
Referenced by pythiaDecayer::addParticle(), starlightParticle::reflect(), hepMC3Writer::writeEvent(), eventFileWriter::writeEvent(), and eventFileWriter::writeEventLUND().
double lorentzVector::GetPz () const inline
Definition at line 56 of file lorentzvector.h.
View newest version in sPHENIX GitHub at line 56 of file lorentzvector.h
References fSpaceVec, and vector3::GetVector().
Referenced by pythiaDecayer::addParticle(), starlightParticle::reflect(), hepMC3Writer::writeEvent(), eventFileWriter::writeEvent(), and eventFileWriter::writeEventLUND().
double lorentzVector::M () const inline
Definition at line 74 of file lorentzvector.h.
View newest version in sPHENIX GitHub at line 74 of file lorentzvector.h
References M2().
Referenced by pythiaDecayer::addParticle(), nBodyPhaseSpaceGen::generateDecay(), and nBodyPhaseSpaceGen::generateDecayAccepted().
double lorentzVector::M2 () const inline
Definition at line 73 of file lorentzvector.h.
View newest version in sPHENIX GitHub at line 73 of file lorentzvector.h
References fSpaceVec, fTime, and vector3::Mag2().
Referenced by M().
lorentzVector& lorentzVector::operator+= (const lorentzVector & vec) inline
Definition at line 60 of file lorentzvector.h.
View newest version in sPHENIX GitHub at line 60 of file lorentzvector.h
References fSpaceVec, and fTime.
lorentzVector& lorentzVector::operator-= (const lorentzVector & vec) inline
Definition at line 66 of file lorentzvector.h.
View newest version in sPHENIX GitHub at line 66 of file lorentzvector.h
References fSpaceVec, and fTime.
virtual void lorentzVector::reflect () inline virtual
Reimplemented in starlightParticle.
Definition at line 58 of file lorentzvector.h.
View newest version in sPHENIX GitHub at line 58 of file lorentzvector.h
References fSpaceVec, vector3::SetVector(), vector3::X(), vector3::Y(), and vector3::Z().
Referenced by starlightParticle::reflect().
void lorentzVector::SetPxPyPzE (double px, double py, double pz, double e) inline
Definition at line 52 of file lorentzvector.h.
View newest version in sPHENIX GitHub at line 52 of file lorentzvector.h
References SetXYZT().
Referenced by nBodyPhaseSpaceGen::calcEventKinematics().
void lorentzVector::SetXYZT (double x, double y, double z, double t)
Definition at line 53 of file lorentzvector.cpp.
View newest version in sPHENIX GitHub at line 53 of file lorentzvector.cpp
References fSpaceVec, fTime, vector3::SetVector(), and t.
Referenced by Boost(), starlightParticle::reflect(), and SetPxPyPzE().
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & out, const lorentzVector & vec) friend
Definition at line 94 of file lorentzvector.h.
View newest version in sPHENIX GitHub at line 94 of file lorentzvector.h
Member Data Documentation
vector3 lorentzVector::fSpaceVec private
Definition at line 104 of file lorentzvector.h.
View newest version in sPHENIX GitHub at line 104 of file lorentzvector.h
Referenced by Boost(), BoostVector(), GetPx(), GetPy(), GetPz(), M2(), operator+=(), operator-=(), reflect(), and SetXYZT().
double lorentzVector::fTime private
Definition at line 105 of file lorentzvector.h.
View newest version in sPHENIX GitHub at line 105 of file lorentzvector.h
Referenced by Boost(), BoostVector(), GetE(), M2(), operator+=(), operator-=(), and SetXYZT().
The documentation for this class was generated from the following files:
estarlight/blob/master/include/lorentzvector.h
estarlight/blob/master/src/lorentzvector.cpp