EIC Software: g4lblvtx/blob/master/macros/G4_Bbc.C File Reference
G4_Bbc.C File Reference
#include <fun4all/Fun4AllServer.h>
#include <g4bbc/BbcVertexFastSimReco.h>
Functions
void BbcInit ()
double Bbc (PHG4Reco *g4Reco, double radius, const int absorberactive=0, int verbosity=0)
void Bbc_Reco (int verbosity=0)
Function Documentation
double Bbc (PHG4Reco * g4Reco, double radius, const int absorberactive = 0, int verbosity = 0)
Definition at line 10 of file G4_Bbc.C.
View newest version in sPHENIX GitHub at line 10 of file G4_Bbc.C
References G4BECAL::radius.
void Bbc_Reco (int verbosity = 0)
Definition at line 21 of file G4_Bbc.C.
View newest version in sPHENIX GitHub at line 21 of file G4_Bbc.C
References Fun4AllServer::instance(), Fun4AllServer::registerSubsystem(), BbcVertexFastSimReco::set_t_smearing(), and BbcVertexFastSimReco::set_z_smearing().
void BbcInit ()
Definition at line 8 of file G4_Bbc.C.
View newest version in sPHENIX GitHub at line 8 of file G4_Bbc.C