EIC Software: RawClusterBuilderHelper Class Reference
RawClusterBuilderHelper Class Reference
#include <fun4all_eicdetectors/blob/master/reconstruction/eiccaloreco/RawClusterBuilderHelper.h>
Classes
struct towersStrct
Public Member Functions
RawClusterBuilderHelper (const std::string &name)
~RawClusterBuilderHelper () override
int InitRun (PHCompositeNode *topNode) override
int process_event (PHCompositeNode *topNode) override
int End (PHCompositeNode *topNode) override
Called at the end of all processing.
void Detector (const std::string &d)
void set_seed_e (const float e)
void set_agg_e (const float e)
Public Member Functions inherited from SubsysReco
~SubsysReco () override
virtual int EndRun (const int)
Called at the end of each run.
virtual int Init (PHCompositeNode *)
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
void Print (const std::string &="ALL") const override
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Static Public Member Functions
static bool towerECompare (towersStrct lhs, towersStrct rhs)
Protected Member Functions
virtual void cluster (std::vector< towersStrct > &input_towers, uint caloId)
int caloTowersPhi (int caloID)
bool IsForwardCalorimeter (int caloID)
void CreateNodes (PHCompositeNode *topNode)
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Protected Member Functions inherited from Fun4AllBase
Fun4AllBase (const std::string &name="NONAME")
Protected Attributes
float _seed_e
float _agg_e
std::string detector
std::string ClusterNodeName
RawClusterContainer * _clusters
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = INT_MAX - 10
}
Detailed Description
Definition at line 14 of file RawClusterBuilderHelper.h.
View newest version in sPHENIX GitHub at line 14 of file RawClusterBuilderHelper.h
Constructor & Destructor Documentation
RawClusterBuilderHelper::RawClusterBuilderHelper (const std::string & name)
Definition at line 35 of file RawClusterBuilderHelper.cc.
View newest version in sPHENIX GitHub at line 35 of file RawClusterBuilderHelper.cc
RawClusterBuilderHelper::~RawClusterBuilderHelper () inline override
Definition at line 29 of file RawClusterBuilderHelper.h.
View newest version in sPHENIX GitHub at line 29 of file RawClusterBuilderHelper.h
Member Function Documentation
int RawClusterBuilderHelper::caloTowersPhi (int caloID) protected
Definition at line 217 of file RawClusterBuilderHelper.cc.
View newest version in sPHENIX GitHub at line 217 of file RawClusterBuilderHelper.cc
References RawTowerDefs::BECAL, RawTowerDefs::CEMC, RawTowerDefs::EEMC_glass, RawTowerDefs::HCALIN, and RawTowerDefs::HCALOUT.
Referenced by RawClusterBuilderkMA::cluster(), and RawClusterBuilderkV3::cluster().
virtual void RawClusterBuilderHelper::cluster (std::vector< towersStrct > & input_towers, uint caloId) inline protected virtual
Reimplemented in RawClusterBuilderkV3, and RawClusterBuilderkMA.
Definition at line 47 of file RawClusterBuilderHelper.h.
View newest version in sPHENIX GitHub at line 47 of file RawClusterBuilderHelper.h
Referenced by process_event().
void RawClusterBuilderHelper::CreateNodes (PHCompositeNode * topNode) protected
Definition at line 236 of file RawClusterBuilderHelper.cc.
View newest version in sPHENIX GitHub at line 236 of file RawClusterBuilderHelper.cc
References _clusters, PHCompositeNode::addNode(), ClusterNodeName, detector, PHNodeIterator::findFirst(), and PHWHERE.
Referenced by InitRun().
void RawClusterBuilderHelper::Detector (const std::string & d) inline
Definition at line 35 of file RawClusterBuilderHelper.h.
View newest version in sPHENIX GitHub at line 35 of file RawClusterBuilderHelper.h
References d, and detector.
int RawClusterBuilderHelper::End (PHCompositeNode *) override virtual
Called at the end of all processing.
Reimplemented from SubsysReco.
Definition at line 177 of file RawClusterBuilderHelper.cc.
View newest version in sPHENIX GitHub at line 177 of file RawClusterBuilderHelper.cc
References Fun4AllReturnCodes::EVENT_OK.
int RawClusterBuilderHelper::InitRun (PHCompositeNode *) override virtual
Called for first event when run number is known. Typically this is where you may want to fetch data from database, because you know the run number.
Reimplemented from SubsysReco.
Definition at line 44 of file RawClusterBuilderHelper.cc.
View newest version in sPHENIX GitHub at line 44 of file RawClusterBuilderHelper.cc
References CreateNodes(), Acts::UnitConstants::e, Fun4AllReturnCodes::EVENT_OK, and PHWHERE.
bool RawClusterBuilderHelper::IsForwardCalorimeter (int caloID) protected
Definition at line 182 of file RawClusterBuilderHelper.cc.
View newest version in sPHENIX GitHub at line 182 of file RawClusterBuilderHelper.cc
References RawTowerDefs::BECAL, RawTowerDefs::CEMC, RawTowerDefs::DRCALO, RawTowerDefs::EEMC, RawTowerDefs::EEMC_crystal, RawTowerDefs::EEMC_glass, RawTowerDefs::EHCAL, RawTowerDefs::FEMC, RawTowerDefs::FHCAL, RawTowerDefs::HCALIN, RawTowerDefs::HCALOUT, and RawTowerDefs::LFHCAL.
Referenced by RawClusterBuilderkMA::cluster(), and RawClusterBuilderkV3::cluster().
int RawClusterBuilderHelper::process_event (PHCompositeNode *) override virtual
Called for each event. This is where you do the real work.
Reimplemented from SubsysReco.
Definition at line 58 of file RawClusterBuilderHelper.cc.
View newest version in sPHENIX GitHub at line 58 of file RawClusterBuilderHelper.cc
References _agg_e, _clusters, Fun4AllReturnCodes::ABORTEVENT, cluster(), detector, Fun4AllReturnCodes::DISCARDEVENT, Acts::UnitConstants::e, Fun4AllReturnCodes::EVENT_OK, RawTower::get_bineta(), RawTower::get_binl(), RawTower::get_binphi(), RawTowerGeom::get_center_x(), RawTowerGeom::get_center_y(), RawTowerGeom::get_center_z(), RawTower::get_energy(), RawCluster::get_id(), RawTowerGeomContainer::get_tower_geometry(), RawCluster::get_towermap(), RawTowerContainer::getCalorimeterID(), RawClusterContainer::getClustersMap(), RawTowerContainer::getTower(), RawTowerContainer::getTowers(), RawCluster::identify(), RawTowerDefs::LFHCAL, Fun4AllBase::Name(), PHWHERE, RawCluster::set_energy(), RawCluster::set_phi(), RawCluster::set_r(), RawCluster::set_z(), RawClusterBuilderHelper::towersStrct::tower_E, RawClusterBuilderHelper::towersStrct::tower_iEta, RawClusterBuilderHelper::towersStrct::tower_iL, RawClusterBuilderHelper::towersStrct::tower_iPhi, RawClusterBuilderHelper::towersStrct::tower_trueID, RawClusterBuilderHelper::towersStrct::twr, and Fun4AllBase::Verbosity().
void RawClusterBuilderHelper::set_agg_e (const float e) inline
Definition at line 37 of file RawClusterBuilderHelper.h.
View newest version in sPHENIX GitHub at line 37 of file RawClusterBuilderHelper.h
References _agg_e, and Acts::UnitConstants::e.
void RawClusterBuilderHelper::set_seed_e (const float e) inline
Definition at line 36 of file RawClusterBuilderHelper.h.
View newest version in sPHENIX GitHub at line 36 of file RawClusterBuilderHelper.h
References _seed_e, and Acts::UnitConstants::e.
static bool RawClusterBuilderHelper::towerECompare (towersStrct lhs, towersStrct rhs) inline static
Definition at line 26 of file RawClusterBuilderHelper.h.
View newest version in sPHENIX GitHub at line 26 of file RawClusterBuilderHelper.h
References RawClusterBuilderHelper::towersStrct::tower_E.
Referenced by RawClusterBuilderkMA::cluster(), and RawClusterBuilderkV3::cluster().
Member Data Documentation
float RawClusterBuilderHelper::_agg_e protected
Definition at line 41 of file RawClusterBuilderHelper.h.
View newest version in sPHENIX GitHub at line 41 of file RawClusterBuilderHelper.h
Referenced by RawClusterBuilderkMA::cluster(), RawClusterBuilderkV3::cluster(), process_event(), and set_agg_e().
RawClusterContainer* RawClusterBuilderHelper::_clusters protected
Definition at line 45 of file RawClusterBuilderHelper.h.
View newest version in sPHENIX GitHub at line 45 of file RawClusterBuilderHelper.h
Referenced by RawClusterBuilderkMA::cluster(), RawClusterBuilderkV3::cluster(), CreateNodes(), and process_event().
float RawClusterBuilderHelper::_seed_e protected
Definition at line 40 of file RawClusterBuilderHelper.h.
View newest version in sPHENIX GitHub at line 40 of file RawClusterBuilderHelper.h
Referenced by RawClusterBuilderkMA::cluster(), RawClusterBuilderkV3::cluster(), and set_seed_e().
std::string RawClusterBuilderHelper::ClusterNodeName protected
Definition at line 43 of file RawClusterBuilderHelper.h.
View newest version in sPHENIX GitHub at line 43 of file RawClusterBuilderHelper.h
Referenced by CreateNodes().
std::string RawClusterBuilderHelper::detector protected
Definition at line 42 of file RawClusterBuilderHelper.h.
View newest version in sPHENIX GitHub at line 42 of file RawClusterBuilderHelper.h
Referenced by CreateNodes(), Detector(), and process_event().
The documentation for this class was generated from the following files:
fun4all_eicdetectors/blob/master/reconstruction/eiccaloreco/RawClusterBuilderHelper.h
fun4all_eicdetectors/blob/master/reconstruction/eiccaloreco/RawClusterBuilderHelper.cc