EIC Software: fun4all_eicmacros/blob/master/common/G4_Mvtx_EIC.C File Reference
G4_Mvtx_EIC.C File Reference
#include <GlobalVariables.C>
#include <g4mvtx/PHG4EICMvtxSubsystem.h>
#include <g4mvtx/PHG4MvtxDefs.h>
#include <g4main/PHG4Reco.h>
#include <fun4all/Fun4AllServer.h>
#include <cmath>
#include <vector>
Namespaces
namespace Enable
namespace G4MVTX
Macros
#define MACRO_G4MVTXEIC_C
Functions
void MvtxInit (int verbosity=0)
double Mvtx (PHG4Reco *g4Reco, double radius, const int absorberactive=0)
Variables
bool Enable::MVTX = false
bool Enable::MVTX_OVERLAPCHECK = false
int Enable::MVTX_VERBOSITY = 0
int G4MVTX::n_maps_layer = 3
vector< int > G4MVTX::N_staves = {18, 24, 30}
vector< double > G4MVTX::nom_radius = {36.4, 48.1, 59.8}
Macro Definition Documentation
#define MACRO_G4MVTXEIC_C
Definition at line 2 of file G4_Mvtx_EIC.C.
View newest version in sPHENIX GitHub at line 2 of file G4_Mvtx_EIC.C
Function Documentation
double Mvtx (PHG4Reco * g4Reco, double radius, const int absorberactive = 0)
Definition at line 40 of file G4_Mvtx_EIC.C.
View newest version in sPHENIX GitHub at line 40 of file G4_Mvtx_EIC.C
References PHG4MvtxDefs::GLOBAL, M_PI, max, Enable::MVTX_OVERLAPCHECK, Enable::MVTX_VERBOSITY, G4MVTX::n_maps_layer, G4MVTX::N_staves, G4MVTX::nom_radius, Enable::OVERLAPCHECK, PHG4DetectorGroupSubsystem::OverlapCheck(), PHG4Reco::registerSubsystem(), PHG4DetectorGroupSubsystem::set_double_param(), PHG4DetectorGroupSubsystem::set_int_param(), PHG4DetectorGroupSubsystem::set_string_param(), PHG4DetectorGroupSubsystem::SetActive(), Enable::VERBOSITY, and Fun4AllBase::Verbosity().
Referenced by G4Setup().
void MvtxInit (int verbosity = 0)
Definition at line 33 of file G4_Mvtx_EIC.C.
View newest version in sPHENIX GitHub at line 33 of file G4_Mvtx_EIC.C
References max, BlackHoleGeometry::max_radius, BlackHoleGeometry::max_z, min, BlackHoleGeometry::min_z, G4MVTX::n_maps_layer, and G4MVTX::nom_radius.
Referenced by G4Init().