EIC Software: CbmRichRingFitterTAU Class Reference
CbmRichRingFitterTAU Class Reference
Here the ring is fitted with the TAU algorithm from A. Ayriyan/ G. Ososkov.
#include <EicRoot/blob/master/rich/fitter/CbmRichRingFitterTAU.h>
Public Member Functions
CbmRichRingFitterTAU ()
Default constructor.
virtual ~CbmRichRingFitterTAU ()
Destructor.
virtual void DoFit (CbmRichRingLight *ring)
Inherited from CbmRichRingFitterBase.
Public Member Functions inherited from CbmRichRingFitterBase
CbmRichRingFitterBase ()
Default constructor.
virtual ~CbmRichRingFitterBase ()
Destructor.
Private Attributes
int fRobust
Additional Inherited Members
Protected Member Functions inherited from CbmRichRingFitterBase
virtual void CalcChi2 (CbmRichRingLight *ring)
Calculate chi2 for circle fitting algorithms.
Static Protected Attributes inherited from CbmRichRingFitterBase
static const int MAX_NOF_HITS_IN_RING = 400
Detailed Description
Here the ring is fitted with the TAU algorithm from A. Ayriyan/ G. Ososkov.
Author
Alexander Ayriyan, Gennadi Ososkov, Claudia Hoehne, Semen Lebedev s.leb.nosp@m.edev.nosp@m.@gsi..nosp@m.de
Date
2012
Definition at line 24 of file CbmRichRingFitterTAU.h.
View newest version in sPHENIX GitHub at line 24 of file CbmRichRingFitterTAU.h
Constructor & Destructor Documentation
CbmRichRingFitterTAU::CbmRichRingFitterTAU ()
Default constructor.
Definition at line 20 of file CbmRichRingFitterTAU.cxx.
View newest version in sPHENIX GitHub at line 20 of file CbmRichRingFitterTAU.cxx
CbmRichRingFitterTAU::~CbmRichRingFitterTAU () virtual
Destructor.
Definition at line 26 of file CbmRichRingFitterTAU.cxx.
View newest version in sPHENIX GitHub at line 26 of file CbmRichRingFitterTAU.cxx
Member Function Documentation
void CbmRichRingFitterTAU::DoFit (CbmRichRingLight * ring) virtual
Inherited from CbmRichRingFitterBase.
Tukey's weight function
Optimal weight function
Implements CbmRichRingFitterBase.
Definition at line 30 of file CbmRichRingFitterTAU.cxx.
View newest version in sPHENIX GitHub at line 30 of file CbmRichRingFitterTAU.cxx
References starlightConstants::A2, CbmRichRingFitterBase::CalcChi2(), d, Dy, epsilon, fRobust, CbmRichHitLight::fX, CbmRichHitLight::fY, CbmRichRingLight::GetHit(), CbmRichRingLight::GetNofHits(), G4BECAL::radius, CbmRichRingLight::SetCenterX(), CbmRichRingLight::SetCenterY(), CbmRichRingLight::SetRadius(), x, y, and zero.
Member Data Documentation
int CbmRichRingFitterTAU::fRobust private
Definition at line 45 of file CbmRichRingFitterTAU.h.
View newest version in sPHENIX GitHub at line 45 of file CbmRichRingFitterTAU.h
Referenced by DoFit().
The documentation for this class was generated from the following files:
EicRoot/blob/master/rich/fitter/CbmRichRingFitterTAU.h
EicRoot/blob/master/rich/fitter/CbmRichRingFitterTAU.cxx