EIC Software: FW::GeantinoRecording Class Reference
FW::GeantinoRecording Class Reference
records the simulation geometry by using geantinos
#include <fun4all_acts/blob/master/Examples/Algorithms/MaterialMapping/include/ACTFW/MaterialMapping/GeantinoRecording.hpp>
Classes
class Config
Public Member Functions
GeantinoRecording (const Config &cnf, Acts::Logging::Level level=Acts::Logging::INFO)
Constructor.
FW::ProcessCode execute (const AlgorithmContext &context) const finaloverride
Public Member Functions inherited from FW::BareAlgorithm
BareAlgorithm (std::string name, Acts::Logging::Level level=Acts::Logging::INFO)
std::string name () const finaloverride
The algorithm name.
Private Attributes
Config m_cfg
The config object.
std::unique_ptr< G4RunManager > m_runManager
G4 run manager.
Additional Inherited Members
Protected Member Functions inherited from FW::BareAlgorithm
const Acts::Logger & logger () const
Detailed Description
records the simulation geometry by using geantinos
The GeantinoRecording algorithm initiates the geant4 simulation of the Geant4materialMapping plugin, creates and writes out the MaterialTrack entities which are needed for material mapping. The input for the geant4 geometry can be either provided by a gdml file or an implementation of the IGeant4Service.
Definition at line 42 of file GeantinoRecording.hpp.
View newest version in sPHENIX GitHub at line 42 of file GeantinoRecording.hpp
Constructor & Destructor Documentation
FW::GeantinoRecording::GeantinoRecording (const Config & cnf, Acts::Logging::Level level = Acts::Logging::INFO)
Constructor.
Check if the geometry should be accessed over the geant4 service
Access the geometry from the gdml file
Now set up the Geant4 simulation
Definition at line 22 of file GeantinoRecording.cpp.
View newest version in sPHENIX GitHub at line 22 of file GeantinoRecording.cpp
References ACTS_INFO, FW::GeantinoRecording::Config::gdmlFile, FW::GeantinoRecording::Config::geant4Service, m_cfg, m_runManager, FW::GeantinoRecording::Config::seed1, and FW::GeantinoRecording::Config::seed2.
Member Function Documentation
FW::ProcessCode FW::GeantinoRecording::execute (const AlgorithmContext & context) const final override virtual
Execute the algorithm for one event.
This function must be implemented by subclasses.
Implements FW::BareAlgorithm.
Definition at line 55 of file GeantinoRecording.cpp.
View newest version in sPHENIX GitHub at line 55 of file GeantinoRecording.cpp
References ACTS_INFO, FW::WhiteBoard::add(), FW::AlgorithmContext::eventStore, FW::Geant4::MMEventAction::Instance(), FW::Geant4::MMEventAction::MaterialTracks(), and SUCCESS.
Member Data Documentation
Config FW::GeantinoRecording::m_cfg private
The config object.
Definition at line 71 of file GeantinoRecording.hpp.
View newest version in sPHENIX GitHub at line 71 of file GeantinoRecording.hpp
Referenced by GeantinoRecording().
std::unique_ptr<G4RunManager> FW::GeantinoRecording::m_runManager private
G4 run manager.
Definition at line 73 of file GeantinoRecording.hpp.
View newest version in sPHENIX GitHub at line 73 of file GeantinoRecording.hpp
Referenced by GeantinoRecording().
The documentation for this class was generated from the following files:
fun4all_acts/blob/master/Examples/Algorithms/MaterialMapping/include/ACTFW/MaterialMapping/GeantinoRecording.hpp
fun4all_acts/blob/master/Examples/Algorithms/MaterialMapping/src/GeantinoRecording.cpp