EIC Software: RawTowerBuilderByHitIndexLHCal Class Reference
RawTowerBuilderByHitIndexLHCal Class Reference
SubsysReco module creating calorimeter tower objects (RawTowerv1) from hits (PHG4Hit) using j,k,l indeces of these hits.
#include <fun4all_eicdetectors/blob/master/simulation/g4simulation/g4eiccalos/RawTowerBuilderByHitIndexLHCal.h>
Public Member Functions
RawTowerBuilderByHitIndexLHCal (const std::string &name="RawTowerBuilderByHitIndexLHCal")
~RawTowerBuilderByHitIndexLHCal () override
int InitRun (PHCompositeNode *topNode) override
int process_event (PHCompositeNode *topNode) override
int End (PHCompositeNode *topNode) override
Called at the end of all processing.
void Detector (const std::string &d)
void GeometryTableFile (const std::string &d)
void EminCut (const double e)
std::string get_sim_tower_node_prefix () const
void set_sim_tower_node_prefix (const std::string &simTowerNodePrefix)
Public Member Functions inherited from SubsysReco
~SubsysReco () override
virtual int EndRun (const int)
Called at the end of each run.
virtual int Init (PHCompositeNode *)
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
void Print (const std::string &="ALL") const override
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Private Member Functions
void CreateNodes (PHCompositeNode *topNode)
bool ReadGeometryFromTable ()
Private Attributes
RawTowerContainer * m_Towers
RawTowerGeomContainer * m_Geoms
std::string m_Detector
std::string m_SimTowerNodePrefix
std::string m_MappingTowerFile
RawTowerDefs::CalorimeterId m_CaloId
double m_GlobalPlaceInX
double m_GlobalPlaceInY
double m_GlobalPlaceInZ
double m_RotInX
double m_RotInY
double m_RotInZ
double m_Emin
double m_TowerDepth
double m_ThicknessAbsorber
double m_ThicknessScintilator
int m_NLayers
int m_NLayersPerTowerSeg
int m_NTowerSeg
std::map< std::string, double > m_GlobalParameterMap
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = INT_MAX - 10
}
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Detailed Description
SubsysReco module creating calorimeter tower objects (RawTowerv1) from hits (PHG4Hit) using j,k,l indeces of these hits.
Definition at line 20 of file RawTowerBuilderByHitIndexLHCal.h.
View newest version in sPHENIX GitHub at line 20 of file RawTowerBuilderByHitIndexLHCal.h
Constructor & Destructor Documentation
RawTowerBuilderByHitIndexLHCal::RawTowerBuilderByHitIndexLHCal (const std::string & name = "RawTowerBuilderByHitIndexLHCal")
Definition at line 42 of file RawTowerBuilderByHitIndexLHCal.cc.
View newest version in sPHENIX GitHub at line 42 of file RawTowerBuilderByHitIndexLHCal.cc
RawTowerBuilderByHitIndexLHCal::~RawTowerBuilderByHitIndexLHCal () inline override
Definition at line 24 of file RawTowerBuilderByHitIndexLHCal.h.
View newest version in sPHENIX GitHub at line 24 of file RawTowerBuilderByHitIndexLHCal.h
Member Function Documentation
void RawTowerBuilderByHitIndexLHCal::CreateNodes (PHCompositeNode * topNode) private
Create nodes for output.
Name of output node for RawTowerContainer: "TOWER_" + detector;
Definition at line 182 of file RawTowerBuilderByHitIndexLHCal.cc.
View newest version in sPHENIX GitHub at line 182 of file RawTowerBuilderByHitIndexLHCal.cc
References PHCompositeNode::addNode(), RawTowerDefs::convert_name_to_caloid(), PHNodeIterator::findFirst(), m_Detector, m_Geoms, m_SimTowerNodePrefix, m_Towers, and PHWHERE.
Referenced by InitRun().
void RawTowerBuilderByHitIndexLHCal::Detector (const std::string & d)
Name of the detector node the G4Hits should be taken from.
Definition at line 176 of file RawTowerBuilderByHitIndexLHCal.cc.
View newest version in sPHENIX GitHub at line 176 of file RawTowerBuilderByHitIndexLHCal.cc
References RawTowerDefs::convert_name_to_caloid(), d, m_CaloId, and m_Detector.
Referenced by LFHCAL_Towers().
void RawTowerBuilderByHitIndexLHCal::EminCut (const double e) inline
Define minimum tower energy. After processing an event, towers with lower energy are will be deleted.
Definition at line 46 of file RawTowerBuilderByHitIndexLHCal.h.
View newest version in sPHENIX GitHub at line 46 of file RawTowerBuilderByHitIndexLHCal.h
References Acts::UnitConstants::e, and m_Emin.
int RawTowerBuilderByHitIndexLHCal::End (PHCompositeNode *) override virtual
Called at the end of all processing.
Reimplemented from SubsysReco.
Definition at line 171 of file RawTowerBuilderByHitIndexLHCal.cc.
View newest version in sPHENIX GitHub at line 171 of file RawTowerBuilderByHitIndexLHCal.cc
References Fun4AllReturnCodes::EVENT_OK.
void RawTowerBuilderByHitIndexLHCal::GeometryTableFile (const std::string & d) inline
Specifiy text-file with table for tower mapping
Definition at line 38 of file RawTowerBuilderByHitIndexLHCal.h.
View newest version in sPHENIX GitHub at line 38 of file RawTowerBuilderByHitIndexLHCal.h
References d, and m_MappingTowerFile.
Referenced by LFHCAL_Towers().
std::string RawTowerBuilderByHitIndexLHCal::get_sim_tower_node_prefix () const inline
Get prefix for tower collection to identify simulated towers before digitization.
Definition at line 52 of file RawTowerBuilderByHitIndexLHCal.h.
View newest version in sPHENIX GitHub at line 52 of file RawTowerBuilderByHitIndexLHCal.h
References m_SimTowerNodePrefix.
int RawTowerBuilderByHitIndexLHCal::InitRun (PHCompositeNode *) override virtual
Called for first event when run number is known. Typically this is where you may want to fetch data from database, because you know the run number.
Reimplemented from SubsysReco.
Definition at line 65 of file RawTowerBuilderByHitIndexLHCal.cc.
View newest version in sPHENIX GitHub at line 65 of file RawTowerBuilderByHitIndexLHCal.cc
References CreateNodes(), Acts::UnitConstants::e, Fun4AllReturnCodes::EVENT_OK, exit(), PHNodeIterator::findFirst(), PHWHERE, and ReadGeometryFromTable().
int RawTowerBuilderByHitIndexLHCal::process_event (PHCompositeNode *) override virtual
Called for each event. This is where you do the real work.
Reimplemented from SubsysReco.
Definition at line 101 of file RawTowerBuilderByHitIndexLHCal.cc.
View newest version in sPHENIX GitHub at line 101 of file RawTowerBuilderByHitIndexLHCal.cc
References RawTowerContainer::AddTower(), RawTowerContainer::compress(), RawTowerDefs::encode_towerid(), Fun4AllReturnCodes::EVENT_OK, exit(), PHG4Hit::get_edep(), PHG4Hit::get_index_j(), PHG4Hit::get_index_k(), PHG4Hit::get_index_l(), PHG4Hit::get_light_yield(), PHG4Hit::get_shower_id(), PHG4HitContainer::getHits(), RawTowerContainer::getTotalEdep(), RawTowerContainer::getTower(), RawTowerContainer::getTowers(), RawTowerContainer::identify(), m_CaloId, m_Detector, m_Emin, m_Towers, RawTowerContainer::size(), and Fun4AllBase::Verbosity().
bool RawTowerBuilderByHitIndexLHCal::ReadGeometryFromTable () private
Read geometry information from table stored in text-file
Definition at line 235 of file RawTowerBuilderByHitIndexLHCal.cc.
View newest version in sPHENIX GitHub at line 235 of file RawTowerBuilderByHitIndexLHCal.cc
References RawTowerGeomContainer::add_tower_geometry(), RawTowerDefs::encode_towerid(), exit(), RawTowerGeomContainer::get_tower_geometries(), getline, it, m_CaloId, m_Geoms, m_GlobalParameterMap, m_GlobalPlaceInX, m_GlobalPlaceInY, m_GlobalPlaceInZ, m_MappingTowerFile, m_NLayers, m_NLayersPerTowerSeg, m_NTowerSeg, m_RotInX, m_RotInY, m_RotInZ, m_ThicknessAbsorber, m_ThicknessScintilator, m_TowerDepth, RawTowerGeom::set_center_x(), RawTowerGeom::set_center_y(), RawTowerGeom::set_center_z(), RawTowerGeom::set_size_x(), RawTowerGeom::set_size_y(), RawTowerGeom::set_size_z(), RawTowerGeom::set_tower_type(), G4CTD::size_z, and Fun4AllBase::Verbosity().
Referenced by InitRun().
void RawTowerBuilderByHitIndexLHCal::set_sim_tower_node_prefix (const std::string & simTowerNodePrefix) inline
Set prefix for tower collection to identify simulated towers before digitization.
Definition at line 61 of file RawTowerBuilderByHitIndexLHCal.h.
View newest version in sPHENIX GitHub at line 61 of file RawTowerBuilderByHitIndexLHCal.h
References m_SimTowerNodePrefix.
Referenced by LFHCAL_Towers().
Member Data Documentation
RawTowerDefs::CalorimeterId RawTowerBuilderByHitIndexLHCal::m_CaloId private
Definition at line 85 of file RawTowerBuilderByHitIndexLHCal.h.
View newest version in sPHENIX GitHub at line 85 of file RawTowerBuilderByHitIndexLHCal.h
Referenced by Detector(), process_event(), and ReadGeometryFromTable().
std::string RawTowerBuilderByHitIndexLHCal::m_Detector private
Definition at line 80 of file RawTowerBuilderByHitIndexLHCal.h.
View newest version in sPHENIX GitHub at line 80 of file RawTowerBuilderByHitIndexLHCal.h
Referenced by CreateNodes(), Detector(), and process_event().
double RawTowerBuilderByHitIndexLHCal::m_Emin private
Definition at line 95 of file RawTowerBuilderByHitIndexLHCal.h.
View newest version in sPHENIX GitHub at line 95 of file RawTowerBuilderByHitIndexLHCal.h
Referenced by EminCut(), and process_event().
RawTowerGeomContainer* RawTowerBuilderByHitIndexLHCal::m_Geoms private
Definition at line 78 of file RawTowerBuilderByHitIndexLHCal.h.
View newest version in sPHENIX GitHub at line 78 of file RawTowerBuilderByHitIndexLHCal.h
Referenced by CreateNodes(), and ReadGeometryFromTable().
std::map<std::string, double> RawTowerBuilderByHitIndexLHCal::m_GlobalParameterMap private
Definition at line 102 of file RawTowerBuilderByHitIndexLHCal.h.
View newest version in sPHENIX GitHub at line 102 of file RawTowerBuilderByHitIndexLHCal.h
Referenced by ReadGeometryFromTable().
double RawTowerBuilderByHitIndexLHCal::m_GlobalPlaceInX private
Definition at line 87 of file RawTowerBuilderByHitIndexLHCal.h.
View newest version in sPHENIX GitHub at line 87 of file RawTowerBuilderByHitIndexLHCal.h
Referenced by ReadGeometryFromTable().
double RawTowerBuilderByHitIndexLHCal::m_GlobalPlaceInY private
Definition at line 88 of file RawTowerBuilderByHitIndexLHCal.h.
View newest version in sPHENIX GitHub at line 88 of file RawTowerBuilderByHitIndexLHCal.h
Referenced by ReadGeometryFromTable().
double RawTowerBuilderByHitIndexLHCal::m_GlobalPlaceInZ private
Definition at line 89 of file RawTowerBuilderByHitIndexLHCal.h.
View newest version in sPHENIX GitHub at line 89 of file RawTowerBuilderByHitIndexLHCal.h
Referenced by ReadGeometryFromTable().
std::string RawTowerBuilderByHitIndexLHCal::m_MappingTowerFile private
Definition at line 83 of file RawTowerBuilderByHitIndexLHCal.h.
View newest version in sPHENIX GitHub at line 83 of file RawTowerBuilderByHitIndexLHCal.h
Referenced by GeometryTableFile(), and ReadGeometryFromTable().
int RawTowerBuilderByHitIndexLHCal::m_NLayers private
Definition at line 99 of file RawTowerBuilderByHitIndexLHCal.h.
View newest version in sPHENIX GitHub at line 99 of file RawTowerBuilderByHitIndexLHCal.h
Referenced by ReadGeometryFromTable().
int RawTowerBuilderByHitIndexLHCal::m_NLayersPerTowerSeg private
Definition at line 100 of file RawTowerBuilderByHitIndexLHCal.h.
View newest version in sPHENIX GitHub at line 100 of file RawTowerBuilderByHitIndexLHCal.h
Referenced by ReadGeometryFromTable().
int RawTowerBuilderByHitIndexLHCal::m_NTowerSeg private
Definition at line 101 of file RawTowerBuilderByHitIndexLHCal.h.
View newest version in sPHENIX GitHub at line 101 of file RawTowerBuilderByHitIndexLHCal.h
Referenced by ReadGeometryFromTable().
double RawTowerBuilderByHitIndexLHCal::m_RotInX private
Definition at line 91 of file RawTowerBuilderByHitIndexLHCal.h.
View newest version in sPHENIX GitHub at line 91 of file RawTowerBuilderByHitIndexLHCal.h
Referenced by ReadGeometryFromTable().
double RawTowerBuilderByHitIndexLHCal::m_RotInY private
Definition at line 92 of file RawTowerBuilderByHitIndexLHCal.h.
View newest version in sPHENIX GitHub at line 92 of file RawTowerBuilderByHitIndexLHCal.h
Referenced by ReadGeometryFromTable().
double RawTowerBuilderByHitIndexLHCal::m_RotInZ private
Definition at line 93 of file RawTowerBuilderByHitIndexLHCal.h.
View newest version in sPHENIX GitHub at line 93 of file RawTowerBuilderByHitIndexLHCal.h
Referenced by ReadGeometryFromTable().
std::string RawTowerBuilderByHitIndexLHCal::m_SimTowerNodePrefix private
Definition at line 81 of file RawTowerBuilderByHitIndexLHCal.h.
View newest version in sPHENIX GitHub at line 81 of file RawTowerBuilderByHitIndexLHCal.h
Referenced by CreateNodes(), get_sim_tower_node_prefix(), and set_sim_tower_node_prefix().
double RawTowerBuilderByHitIndexLHCal::m_ThicknessAbsorber private
Definition at line 97 of file RawTowerBuilderByHitIndexLHCal.h.
View newest version in sPHENIX GitHub at line 97 of file RawTowerBuilderByHitIndexLHCal.h
Referenced by ReadGeometryFromTable().
double RawTowerBuilderByHitIndexLHCal::m_ThicknessScintilator private
Definition at line 98 of file RawTowerBuilderByHitIndexLHCal.h.
View newest version in sPHENIX GitHub at line 98 of file RawTowerBuilderByHitIndexLHCal.h
Referenced by ReadGeometryFromTable().
double RawTowerBuilderByHitIndexLHCal::m_TowerDepth private
Definition at line 96 of file RawTowerBuilderByHitIndexLHCal.h.
View newest version in sPHENIX GitHub at line 96 of file RawTowerBuilderByHitIndexLHCal.h
Referenced by ReadGeometryFromTable().
RawTowerContainer* RawTowerBuilderByHitIndexLHCal::m_Towers private
Definition at line 77 of file RawTowerBuilderByHitIndexLHCal.h.
View newest version in sPHENIX GitHub at line 77 of file RawTowerBuilderByHitIndexLHCal.h
Referenced by CreateNodes(), and process_event().
The documentation for this class was generated from the following files:
fun4all_eicdetectors/blob/master/simulation/g4simulation/g4eiccalos/RawTowerBuilderByHitIndexLHCal.h
fun4all_eicdetectors/blob/master/simulation/g4simulation/g4eiccalos/RawTowerBuilderByHitIndexLHCal.cc