EIC Software: AllSi_Al_support_SteppingAction Class Reference
AllSi_Al_support_SteppingAction Class Reference
#include <fun4all_eicdetectors/blob/master/simulation/g4simulation/g4lblvtx/AllSi_Al_support_SteppingAction.h>
Public Member Functions
AllSi_Al_support_SteppingAction (AllSi_Al_support_Detector *, const PHParameters *parameters)
constructor
virtual ~AllSi_Al_support_SteppingAction ()
destructor
virtual bool UserSteppingAction (const G4Step *, bool)
stepping action
virtual void SetInterfacePointers (PHCompositeNode *)
reimplemented from base class
AllSi_Al_support_SteppingAction (AllSi_Al_support_Detector *, const PHParameters *parameters)
constructor
virtual ~AllSi_Al_support_SteppingAction ()
destructor
virtual bool UserSteppingAction (const G4Step *, bool)
stepping action
virtual void SetInterfacePointers (PHCompositeNode *)
reimplemented from base class
Public Member Functions inherited from PHG4SteppingAction
PHG4SteppingAction (const std::string &name, const int i=0)
virtual ~PHG4SteppingAction ()
virtual void Verbosity (const int i)
virtual int Verbosity () const
virtual int Init ()
virtual double GetScintLightYield (const G4Step *step)
get scintillation photon count. It require a custom set SCINTILLATIONYIELD property to work
virtual double GetVisibleEnergyDeposition (const G4Step *step)
get amount of energy that can make scintillation light, in Unit of GeV.
virtual void StoreLocalCoordinate (PHG4Hit *hit, const G4Step *step, const bool do_prepoint, const bool do_postpoint)
Extract local coordinate of the hit and save to PHG4Hit.
virtual void Print (const std::string &) const
std::string GetName () const
void SetName (const std::string &name)
virtual void SetLightCorrection (const double inner_radius, const double inner_corr, const double outer_radius, const double outer_corr)
virtual double GetLightCorrection (const double r) const
virtual double GetLightCorrection (const double xpos, const double ypos) const
virtual bool ValidCorrection () const
virtual void SetHitNodeName (const std::string &, const std::string &)
Set the G4HIT node names from Subsystem rather than constructing your own.
Private Attributes
AllSi_Al_support_Detector * m_Detector
pointer to the detector
const PHParameters * m_Params
PHG4HitContainer * m_HitContainer
pointer to hit container
PHG4Hit * m_Hit
PHG4HitContainer * m_SaveHitContainer
G4VPhysicalVolume * m_SaveVolPre
G4VPhysicalVolume * m_SaveVolPost
int m_SaveTrackId
int m_SavePreStepStatus
int m_SavePostStepStatus
int m_ActiveFlag
int m_BlackHoleFlag
double m_EdepSum
double m_EionSum
Detailed Description
Definition at line 17 of file AllSi_Al_support_SteppingAction.h.
View newest version in sPHENIX GitHub at line 17 of file AllSi_Al_support_SteppingAction.h
Constructor & Destructor Documentation
AllSi_Al_support_SteppingAction::AllSi_Al_support_SteppingAction (AllSi_Al_support_Detector * detector, const PHParameters * parameters)
constructor
Definition at line 63 of file AllSi_Al_support_SteppingAction.cc.
View newest version in sPHENIX GitHub at line 63 of file AllSi_Al_support_SteppingAction.cc
AllSi_Al_support_SteppingAction::~AllSi_Al_support_SteppingAction () virtual
destructor
Definition at line 83 of file AllSi_Al_support_SteppingAction.cc.
View newest version in sPHENIX GitHub at line 83 of file AllSi_Al_support_SteppingAction.cc
References m_Hit.
AllSi_Al_support_SteppingAction::AllSi_Al_support_SteppingAction (AllSi_Al_support_Detector * , const PHParameters * parameters)
constructor
virtual AllSi_Al_support_SteppingAction::~AllSi_Al_support_SteppingAction () virtual
destructor
Member Function Documentation
void AllSi_Al_support_SteppingAction::SetInterfacePointers (PHCompositeNode * topNode) virtual
reimplemented from base class
Reimplemented from PHG4SteppingAction.
Definition at line 347 of file AllSi_Al_support_SteppingAction.cc.
View newest version in sPHENIX GitHub at line 347 of file AllSi_Al_support_SteppingAction.cc
References PHG4Detector::GetName(), m_Detector, and m_HitContainer.
virtual void AllSi_Al_support_SteppingAction::SetInterfacePointers (PHCompositeNode *) virtual
reimplemented from base class
Reimplemented from PHG4SteppingAction.
virtual bool AllSi_Al_support_SteppingAction::UserSteppingAction (const G4Step * , bool) virtual
stepping action
Implements PHG4SteppingAction.
bool AllSi_Al_support_SteppingAction::UserSteppingAction (const G4Step * aStep, bool was_used) virtual
stepping action
Implements PHG4SteppingAction.
Definition at line 94 of file AllSi_Al_support_SteppingAction.cc.
View newest version in sPHENIX GitHub at line 94 of file AllSi_Al_support_SteppingAction.cc
References PHG4HitContainer::AddHit(), Acts::UnitConstants::cm, PHG4Hit::get_hit_id(), PHG4Hit::get_x(), PHG4HitContainer::GetID(), PHG4SteppingAction::GetName(), PHG4StepStatusDecode::GetStepStatus(), Acts::UnitConstants::GeV, AllSi_Al_support_Detector::IsInDetector(), m_BlackHoleFlag, m_Detector, m_EdepSum, m_EionSum, m_Hit, m_HitContainer, m_SaveHitContainer, m_SavePostStepStatus, m_SavePreStepStatus, m_SaveTrackId, m_SaveVolPost, m_SaveVolPre, p, PHG4Hit::Reset(), PHG4Hit::set_edep(), PHG4Hit::set_eion(), PHG4Hit::set_layer(), PHG4Hit::set_t(), PHG4Hit::set_trkid(), PHG4Hit::set_x(), PHG4Hit::set_y(), PHG4Hit::set_z(), and Acts::Test::volume.
Member Data Documentation
int AllSi_Al_support_SteppingAction::m_ActiveFlag private
Definition at line 46 of file AllSi_Al_support_SteppingAction.h.
View newest version in sPHENIX GitHub at line 46 of file AllSi_Al_support_SteppingAction.h
int AllSi_Al_support_SteppingAction::m_BlackHoleFlag private
Definition at line 47 of file AllSi_Al_support_SteppingAction.h.
View newest version in sPHENIX GitHub at line 47 of file AllSi_Al_support_SteppingAction.h
Referenced by UserSteppingAction().
AllSi_Al_support_Detector * AllSi_Al_support_SteppingAction::m_Detector private
pointer to the detector
Definition at line 34 of file AllSi_Al_support_SteppingAction.h.
View newest version in sPHENIX GitHub at line 34 of file AllSi_Al_support_SteppingAction.h
Referenced by SetInterfacePointers(), and UserSteppingAction().
double AllSi_Al_support_SteppingAction::m_EdepSum private
Definition at line 48 of file AllSi_Al_support_SteppingAction.h.
View newest version in sPHENIX GitHub at line 48 of file AllSi_Al_support_SteppingAction.h
Referenced by UserSteppingAction().
double AllSi_Al_support_SteppingAction::m_EionSum private
Definition at line 49 of file AllSi_Al_support_SteppingAction.h.
View newest version in sPHENIX GitHub at line 49 of file AllSi_Al_support_SteppingAction.h
Referenced by UserSteppingAction().
PHG4Hit * AllSi_Al_support_SteppingAction::m_Hit private
Definition at line 38 of file AllSi_Al_support_SteppingAction.h.
View newest version in sPHENIX GitHub at line 38 of file AllSi_Al_support_SteppingAction.h
Referenced by UserSteppingAction(), and ~AllSi_Al_support_SteppingAction().
PHG4HitContainer * AllSi_Al_support_SteppingAction::m_HitContainer private
pointer to hit container
Definition at line 37 of file AllSi_Al_support_SteppingAction.h.
View newest version in sPHENIX GitHub at line 37 of file AllSi_Al_support_SteppingAction.h
Referenced by SetInterfacePointers(), and UserSteppingAction().
const PHParameters * AllSi_Al_support_SteppingAction::m_Params private
Definition at line 35 of file AllSi_Al_support_SteppingAction.h.
View newest version in sPHENIX GitHub at line 35 of file AllSi_Al_support_SteppingAction.h
PHG4HitContainer * AllSi_Al_support_SteppingAction::m_SaveHitContainer private
Definition at line 39 of file AllSi_Al_support_SteppingAction.h.
View newest version in sPHENIX GitHub at line 39 of file AllSi_Al_support_SteppingAction.h
Referenced by UserSteppingAction().
int AllSi_Al_support_SteppingAction::m_SavePostStepStatus private
Definition at line 45 of file AllSi_Al_support_SteppingAction.h.
View newest version in sPHENIX GitHub at line 45 of file AllSi_Al_support_SteppingAction.h
Referenced by UserSteppingAction().
int AllSi_Al_support_SteppingAction::m_SavePreStepStatus private
Definition at line 44 of file AllSi_Al_support_SteppingAction.h.
View newest version in sPHENIX GitHub at line 44 of file AllSi_Al_support_SteppingAction.h
Referenced by UserSteppingAction().
int AllSi_Al_support_SteppingAction::m_SaveTrackId private
Definition at line 43 of file AllSi_Al_support_SteppingAction.h.
View newest version in sPHENIX GitHub at line 43 of file AllSi_Al_support_SteppingAction.h
Referenced by UserSteppingAction().
G4VPhysicalVolume * AllSi_Al_support_SteppingAction::m_SaveVolPost private
Definition at line 41 of file AllSi_Al_support_SteppingAction.h.
View newest version in sPHENIX GitHub at line 41 of file AllSi_Al_support_SteppingAction.h
Referenced by UserSteppingAction().
G4VPhysicalVolume * AllSi_Al_support_SteppingAction::m_SaveVolPre private
Definition at line 40 of file AllSi_Al_support_SteppingAction.h.
View newest version in sPHENIX GitHub at line 40 of file AllSi_Al_support_SteppingAction.h
Referenced by UserSteppingAction().
The documentation for this class was generated from the following files:
fun4all_eicdetectors/blob/master/simulation/g4simulation/g4lblvtx/AllSi_Al_support_SteppingAction.h
g4lblvtx/blob/master/source/AllSi_Al_support_SteppingAction.h
fun4all_eicdetectors/blob/master/simulation/g4simulation/g4lblvtx/AllSi_Al_support_SteppingAction.cc
g4lblvtx/blob/master/source/AllSi_Al_support_SteppingAction.cc