EIC Software: FW::HitSmearing Exception Reference
FW::HitSmearing Exception Reference final
#include <fun4all_acts/blob/master/Examples/Algorithms/Digitization/include/ACTFW/Digitization/HitSmearing.hpp>
Classes
struct Config
Public Member Functions
HitSmearing (const Config &cfg, Acts::Logging::Level lvl)
ProcessCode execute (const AlgorithmContext &ctx) const finaloverride
Public Member Functions inherited from FW::BareAlgorithm
BareAlgorithm (std::string name, Acts::Logging::Level level=Acts::Logging::INFO)
std::string name () const finaloverride
The algorithm name.
Private Attributes
Config m_cfg
std::unordered_map
< Acts::GeometryID, const
Acts::Surface * > m_surfaces
Lookup container for hit surfaces that generate smeared hits.
Additional Inherited Members
Protected Member Functions inherited from FW::BareAlgorithm
const Acts::Logger & logger () const
Detailed Description
Create fittable measurements using truth smearing.
The truth information is smeared in the local measurement frame using Gaussian noise to generate a fittable measurement, i.e. a source link.
Definition at line 29 of file HitSmearing.hpp.
View newest version in sPHENIX GitHub at line 29 of file HitSmearing.hpp
Constructor & Destructor Documentation
FW::HitSmearing::HitSmearing (const Config & cfg, Acts::Logging::Level lvl)
Definition at line 18 of file HitSmearing.cpp.
View newest version in sPHENIX GitHub at line 18 of file HitSmearing.cpp
References FW::HitSmearing::Config::inputSimulatedHits, m_cfg, m_surfaces, FW::HitSmearing::Config::outputSourceLinks, FW::HitSmearing::Config::randomNumbers, FW::HitSmearing::Config::sigmaLoc0, FW::HitSmearing::Config::sigmaLoc1, and FW::HitSmearing::Config::trackingGeometry.
Member Function Documentation
FW::ProcessCode FW::HitSmearing::execute (const AlgorithmContext & context) const final override virtual
Execute the algorithm for one event.
This function must be implemented by subclasses.
Implements FW::BareAlgorithm.
Definition at line 45 of file HitSmearing.cpp.
View newest version in sPHENIX GitHub at line 45 of file HitSmearing.cpp
References ACTS_FATAL, FW::WhiteBoard::add(), Acts::eLOC_0, Acts::eLOC_1, FW::AlgorithmContext::eventStore, FW::AlgorithmContext::geoContext, FW::WhiteBoard::get(), Acts::Surface::globalToLocal(), FW::groupByModule(), it, Acts::Test::pos, and SUCCESS.
Member Data Documentation
Config FW::HitSmearing::m_cfg private
Definition at line 50 of file HitSmearing.hpp.
View newest version in sPHENIX GitHub at line 50 of file HitSmearing.hpp
Referenced by HitSmearing().
std::unordered_map<Acts::GeometryID, const Acts::Surface*> FW::HitSmearing::m_surfaces private
Lookup container for hit surfaces that generate smeared hits.
Definition at line 52 of file HitSmearing.hpp.
View newest version in sPHENIX GitHub at line 52 of file HitSmearing.hpp
Referenced by HitSmearing().
The documentation for this exception was generated from the following files:
fun4all_acts/blob/master/Examples/Algorithms/Digitization/include/ACTFW/Digitization/HitSmearing.hpp
fun4all_acts/blob/master/Examples/Algorithms/Digitization/src/HitSmearing.cpp