EIC Software: beamBeamSystem Class Reference
beamBeamSystem Class Reference
#include <estarlight/blob/master/include/beambeamsystem.h>
Public Member Functions
beamBeamSystem (const inputParameters &input, const beam &beam1, const beam &beam2)
beamBeamSystem (const inputParameters &input)
~beamBeamSystem ()
const beam & beam1 () const
returns beam particle 1
const beam & beam2 () const
returns beam particle 2
double probabilityOfBreakup (const double D) const
double cmsBoost () const
double beamLorentzGamma () const
void init ()
Private Member Functions
void generateBreakupProbabilities ()
double probabilityOfHadronBreakup (const double impactparameter)
double probabilityOfPhotonBreakup (const double impactparameter, const int mode)
Private Attributes
double _pHadronBreakup
double _pPhotonBreakup
double _beamLorentzGamma
Lorentz gamma factor of beams in collider frame.
const double _beamLorentzGamma1
Lorentz gamma factor of beam1 in collider frame.
const double _beamLorentzGamma2
Lorentz gamma factor of beam2 in collider frame.
const int _beamBreakupMode
breakup mode for beam particles
beam _beam1
beam particle 1
beam _beam2
beam particle 2
double _cmsBoost
Rapidity boost of the CMS wrt the lab system.
std::vector< double > _breakupProbabilities
Vector containing breakup probabilities for impact parameters.
double _breakupImpactParameterStep
Step size in the calculation of the breakup probs.
double _breakupCutOff
Cut off for minimum impact parameter probability.
Detailed Description
Definition at line 44 of file beambeamsystem.h.
View newest version in sPHENIX GitHub at line 44 of file beambeamsystem.h
Constructor & Destructor Documentation
beamBeamSystem::beamBeamSystem (const inputParameters & input, const beam & beam1, const beam & beam2)
Definition at line 50 of file beambeamsystem.cpp.
View newest version in sPHENIX GitHub at line 50 of file beambeamsystem.cpp
References init().
beamBeamSystem::beamBeamSystem (const inputParameters & input)
Definition at line 70 of file beambeamsystem.cpp.
View newest version in sPHENIX GitHub at line 70 of file beambeamsystem.cpp
References init().
beamBeamSystem::~beamBeamSystem ()
Definition at line 93 of file beambeamsystem.cpp.
View newest version in sPHENIX GitHub at line 93 of file beambeamsystem.cpp
Member Function Documentation
const beam& beamBeamSystem::beam1 () const inline
returns beam particle 1
Definition at line 55 of file beambeamsystem.h.
View newest version in sPHENIX GitHub at line 55 of file beambeamsystem.h
References _beam1.
Referenced by converttohepmc(), e_narrowResonanceCrossSection::crossSectionCalculation(), wideResonanceCrossSection::crossSectionCalculation(), e_wideResonanceCrossSection::crossSectionCalculation(), incoherentVMCrossSection::crossSectionCalculation(), narrowResonanceCrossSection::crossSectionCalculation(), twoPhotonLuminosity::D2LDMDY(), photonNucleusCrossSection::e_getcsgA(), spectrumProtonNucleus::generateBreakupProbabilities(), photonNucleusCrossSection::getcsgA(), spectrum::getTransformedNofe(), incoherentPhotonNucleusLuminosity::incoherentPhotonNucleusDifferentialLuminosity(), initpythia(), twoPhotonLuminosity::integral(), e_narrowResonanceCrossSection::makeGammaPQ2dependence(), Gammaavectormeson::momenta(), photonNucleusCrossSection::photonFlux(), photonNucleusLuminosity::photonNucleusDifferentialLuminosity(), photonElectronLuminosity::photonNucleusDifferentialLuminosity(), Gammaavectormeson::pickwy(), Gammagammasingle::pp1(), Gammagammaleptonpair::pp_1(), starlightPythia::produceEvent(), starlightDpmJet::produceSingleEvent(), Gammaavectormeson::pTgamma(), photonNucleusLuminosity::pttablegen(), photonNucleusCrossSection::sigma_A(), twoPhotonLuminosity::twoPhotonDifferentialLuminosity(), and photonNucleusLuminosity::vmsigmapt().
const beam& beamBeamSystem::beam2 () const inline
returns beam particle 2
Definition at line 56 of file beambeamsystem.h.
View newest version in sPHENIX GitHub at line 56 of file beambeamsystem.h
References _beam2.
Referenced by converttohepmc(), e_narrowResonanceCrossSection::crossSectionCalculation(), e_wideResonanceCrossSection::crossSectionCalculation(), wideResonanceCrossSection::crossSectionCalculation(), incoherentVMCrossSection::crossSectionCalculation(), narrowResonanceCrossSection::crossSectionCalculation(), twoPhotonLuminosity::D2LDMDY(), photonNucleusCrossSection::e_getcsgA(), spectrumProtonNucleus::generateBreakupProbabilities(), photonNucleusCrossSection::getcsgA(), incoherentPhotonNucleusLuminosity::incoherentPhotonNucleusDifferentialLuminosity(), initpythia(), twoPhotonLuminosity::integral(), e_narrowResonanceCrossSection::makeGammaPQ2dependence(), Gammaavectormeson::momenta(), photonNucleusCrossSection::photonFlux(), photonNucleusLuminosity::photonNucleusDifferentialLuminosity(), photonElectronLuminosity::photonNucleusDifferentialLuminosity(), Gammaavectormeson::pickwy(), Gammagammasingle::pp2(), Gammagammaleptonpair::pp_2(), Gammaavectormeson::pTgamma(), photonNucleusLuminosity::pttablegen(), photonNucleusCrossSection::sigma_A(), twoPhotonLuminosity::twoPhotonDifferentialLuminosity(), and photonNucleusLuminosity::vmsigmapt().
double beamBeamSystem::beamLorentzGamma () const inline
Definition at line 62 of file beambeamsystem.h.
View newest version in sPHENIX GitHub at line 62 of file beambeamsystem.h
References _beamLorentzGamma.
Referenced by spectrum::getTransformedNofe(), and starlightPythia::produceEvent().
double beamBeamSystem::cmsBoost () const inline
Definition at line 60 of file beambeamsystem.h.
View newest version in sPHENIX GitHub at line 60 of file beambeamsystem.h
References _cmsBoost.
void beamBeamSystem::generateBreakupProbabilities () private
Definition at line 166 of file beambeamsystem.cpp.
View newest version in sPHENIX GitHub at line 166 of file beambeamsystem.cpp
References _beam1, _beam2, _beamBreakupMode, _breakupCutOff, _breakupImpactParameterStep, _breakupProbabilities, _pHadronBreakup, _pPhotonBreakup, nucleus::A(), b, nucleus::nuclearRadius(), printInfo, probabilityOfHadronBreakup(), probabilityOfPhotonBreakup(), and nucleus::Z().
Referenced by init().
void beamBeamSystem::init ()
Definition at line 96 of file beambeamsystem.cpp.
View newest version in sPHENIX GitHub at line 96 of file beambeamsystem.cpp
References _beam1, _beam2, _beamLorentzGamma, _beamLorentzGamma1, _beamLorentzGamma2, _cmsBoost, generateBreakupProbabilities(), and beam::setBeamLorentzGamma().
Referenced by beamBeamSystem().
double beamBeamSystem::probabilityOfBreakup (const double D) const
Definition at line 112 of file beambeamsystem.cpp.
View newest version in sPHENIX GitHub at line 112 of file beambeamsystem.cpp
References _beam1, _beam2, _breakupImpactParameterStep, _breakupProbabilities, nucleus::A(), starlightConstants::hbarc, nucleus::nuclearRadius(), nucleus::rho0(), nucleus::thickness(), and nucleus::Z().
Referenced by twoPhotonLuminosity::D2LDMDY(), spectrum::generateBreakupProbabilities(), twoPhotonLuminosity::integrand(), photonNucleusCrossSection::photonFlux(), and photonNucleusLuminosity::pttablegen().
double beamBeamSystem::probabilityOfHadronBreakup (const double impactparameter) private
Definition at line 244 of file beambeamsystem.cpp.
View newest version in sPHENIX GitHub at line 244 of file beambeamsystem.cpp
References _beam1, _beam2, _beamLorentzGamma, _pHadronBreakup, nucleus::A(), starlightConstants::A2, a2, b, gamma(), nucleus::nuclearRadius(), starlightConstants::pi, T1, and T2.
Referenced by generateBreakupProbabilities().
double beamBeamSystem::probabilityOfPhotonBreakup (const double impactparameter, const int mode) private
Definition at line 370 of file beambeamsystem.cpp.
View newest version in sPHENIX GitHub at line 370 of file beambeamsystem.cpp
References _beam1, _beamLorentzGamma, _pPhotonBreakup, nucleus::A(), b, bessel::dbesk1(), eps, Acts::VectorHelpers::eta(), starlightConstants::hbarcmev, k, min, pi, analysis::s, s1, s2, s3, x, analysis::y, and nucleus::Z().
Referenced by generateBreakupProbabilities().
Member Data Documentation
beam beamBeamSystem::_beam1 private
beam particle 1
Definition at line 85 of file beambeamsystem.h.
View newest version in sPHENIX GitHub at line 85 of file beambeamsystem.h
Referenced by beam1(), generateBreakupProbabilities(), init(), probabilityOfBreakup(), probabilityOfHadronBreakup(), and probabilityOfPhotonBreakup().
beam beamBeamSystem::_beam2 private
beam particle 2
Definition at line 86 of file beambeamsystem.h.
View newest version in sPHENIX GitHub at line 86 of file beambeamsystem.h
Referenced by beam2(), generateBreakupProbabilities(), init(), probabilityOfBreakup(), and probabilityOfHadronBreakup().
const int beamBeamSystem::_beamBreakupMode private
breakup mode for beam particles
1 = hard sphere nuclei (b > 2R), 2 = both nuclei break up (XnXn), 3 = a single neutron from each nucleus (1n1n), 4 = neither nucleon breaks up (with b > 2R), 5 = no hadronic break up (similar to option 1, but with the actual hadronic interaction)
Definition at line 77 of file beambeamsystem.h.
View newest version in sPHENIX GitHub at line 77 of file beambeamsystem.h
Referenced by generateBreakupProbabilities().
double beamBeamSystem::_beamLorentzGamma private
Lorentz gamma factor of beams in collider frame.
Definition at line 74 of file beambeamsystem.h.
View newest version in sPHENIX GitHub at line 74 of file beambeamsystem.h
Referenced by beamLorentzGamma(), init(), probabilityOfHadronBreakup(), and probabilityOfPhotonBreakup().
const double beamBeamSystem::_beamLorentzGamma1 private
Lorentz gamma factor of beam1 in collider frame.
Definition at line 75 of file beambeamsystem.h.
View newest version in sPHENIX GitHub at line 75 of file beambeamsystem.h
Referenced by init().
const double beamBeamSystem::_beamLorentzGamma2 private
Lorentz gamma factor of beam2 in collider frame.
Definition at line 76 of file beambeamsystem.h.
View newest version in sPHENIX GitHub at line 76 of file beambeamsystem.h
Referenced by init().
double beamBeamSystem::_breakupCutOff private
Cut off for minimum impact parameter probability.
Definition at line 92 of file beambeamsystem.h.
View newest version in sPHENIX GitHub at line 92 of file beambeamsystem.h
Referenced by generateBreakupProbabilities().
double beamBeamSystem::_breakupImpactParameterStep private
Step size in the calculation of the breakup probs.
Definition at line 91 of file beambeamsystem.h.
View newest version in sPHENIX GitHub at line 91 of file beambeamsystem.h
Referenced by generateBreakupProbabilities(), and probabilityOfBreakup().
std::vector<double> beamBeamSystem::_breakupProbabilities private
Vector containing breakup probabilities for impact parameters.
Definition at line 90 of file beambeamsystem.h.
View newest version in sPHENIX GitHub at line 90 of file beambeamsystem.h
Referenced by generateBreakupProbabilities(), and probabilityOfBreakup().
double beamBeamSystem::_cmsBoost private
Rapidity boost of the CMS wrt the lab system.
Definition at line 88 of file beambeamsystem.h.
View newest version in sPHENIX GitHub at line 88 of file beambeamsystem.h
Referenced by cmsBoost(), and init().
double beamBeamSystem::_pHadronBreakup private
Definition at line 71 of file beambeamsystem.h.
View newest version in sPHENIX GitHub at line 71 of file beambeamsystem.h
Referenced by generateBreakupProbabilities(), and probabilityOfHadronBreakup().
double beamBeamSystem::_pPhotonBreakup private
Definition at line 72 of file beambeamsystem.h.
View newest version in sPHENIX GitHub at line 72 of file beambeamsystem.h
Referenced by generateBreakupProbabilities(), and probabilityOfPhotonBreakup().
The documentation for this class was generated from the following files:
estarlight/blob/master/include/beambeamsystem.h
estarlight/blob/master/src/beambeamsystem.cpp