EIC Software: PEPSI/blob/master/pepsi/jetseten.F File Reference
jetseten.F File Reference
Functions/Subroutines
subroutine lu1ent (IP, KF, PE, THE, PHI)
subroutine lu2ent (IP, KF1, KF2, PECM)
subroutine lu3ent (IP, KF1, KF2, KF3, PECM, X1, X3)
subroutine lu4ent (IP, KF1, KF2, KF3, KF4, PECM, X1, X2, X4, X12, X14)
subroutine lujoin (NJOIN, IJOIN)
subroutine lugive (CHIN)
subroutine luexec
subroutine luprep (IP)
subroutine lustrf (IP)
subroutine luindf (IP)
subroutine ludecy (IP)
subroutine ludcyk (KFL1, KFL2, KFL3, KF)
subroutine lukfdi (KFL1, KFL2, KFL3, KF)
subroutine luptdi (KFL, PX, PY)
subroutine luzdis (KFL1, KFL2, PR, Z)
subroutine lushow (IP1, IP2, QMAX)
subroutine luboei (NSAV)
function ulmass (KF)
subroutine luname (KF, CHAU)
function luchge (KF)
function lucomp (KF)
subroutine luerrm (MERR, CHMESS)
function ulalem (Q2)
function ulalps (Q2)
function ulangl (X, Y)
function bsrlu (IDUMMY)
subroutine rluget (LFN, MOVE)
subroutine rluset (LFN, MOVE)
subroutine pyrobo (IMI, IMA, THE, PHI, BEX, BEY, BEZ)
subroutine lurobo (THE, PHI, BEX, BEY, BEZ)
subroutine luedit (MEDIT)
subroutine lulist (MLIST)
subroutine lulogo
subroutine luupda (MUPDA, LFN)
function klu (I, J)
function plu (I, J)
subroutine lusphe (SPH, APL)
subroutine luthru (THR, OBL)
subroutine luclus (NJET)
subroutine lucell (NJET)
subroutine lujmas (PMH, PML)
subroutine lufowo (H10, H20, H30, H40)
subroutine lutabu (MTABU)
subroutine lueevt (KFL, ECM)
subroutine luxtot (KFL, ECM, XTOT)
subroutine luradk (ECM, MK, PAK, THEK, PHIK, ALPK)
subroutine luxkfl (KFL, ECM, ECMC, KFLC)
subroutine luxjet (ECM, NJET, CUT)
subroutine lux3jt (NJET, CUT, KFL, ECM, X1, X2)
subroutine lux4jt (NJET, CUT, KFL, ECM, KFLN, X1, X2, X4, X12, X14)
subroutine luxdif (NC, NJET, KFL, ECM, CHI, THE, PHI)
subroutine luonia (KFL, ECM)
subroutine luhepc (MCONV)
subroutine lutest (MTEST)
subroutine lutaud (ITAU, IORIG, KFORIG, NDECAY)
Function/Subroutine Documentation
function bsrlu (IDUMMY)
Definition at line 6546 of file jetseten.F.
View newest version in sPHENIX GitHub at line 6546 of file jetseten.F
References k, s, and t.
function klu (I, J)
Definition at line 7863 of file jetseten.F.
View newest version in sPHENIX GitHub at line 7863 of file jetseten.F
References k, klu(), luchge(), lucomp(), max, n, p, and v.
subroutine lu1ent (IP, KF, PE, THE, PHI)
Definition at line 88 of file jetseten.F.
View newest version in sPHENIX GitHub at line 88 of file jetseten.F
References cos(), ip(), k, lucomp(), luerrm(), luexec(), lulist(), max, n, p, phi, ulmass(), and v.
subroutine lu2ent (IP, KF1, KF2, PECM)
Definition at line 135 of file jetseten.F.
View newest version in sPHENIX GitHub at line 135 of file jetseten.F
References ip(), k, lucomp(), luerrm(), luexec(), lulist(), max, n, p, ulmass(), and v.
subroutine lu3ent (IP, KF1, KF2, KF3, PECM, X1, X3)
Definition at line 219 of file jetseten.F.
View newest version in sPHENIX GitHub at line 219 of file jetseten.F
References ip(), k, lucomp(), luerrm(), luexec(), lulist(), max, min, n, p, ulmass(), v, and x3.
subroutine lu4ent (IP, KF1, KF2, KF3, KF4, PECM, X1, X2, X4, X12, X14)
Definition at line 334 of file jetseten.F.
View newest version in sPHENIX GitHub at line 334 of file jetseten.F
References ip(), k, lucomp(), luerrm(), luexec(), lulist(), max, min, n, p, rlu(), ulmass(), v, and x2.
subroutine luboei (NSAV)
Definition at line 5832 of file jetseten.F.
View newest version in sPHENIX GitHub at line 5832 of file jetseten.F
References k, luerrm(), max, min, n, p, ulmass(), and v.
subroutine lucell (NJET)
Definition at line 8750 of file jetseten.F.
View newest version in sPHENIX GitHub at line 8750 of file jetseten.F
References cos(), k, Acts::Logger::log(), luchge(), lucomp(), luerrm(), max, min, n, HiMain1::np(), p, phi, HiStrng::pt(), rlu(), sign(), ulangl(), and v.
function luchge (KF)
Definition at line 6229 of file jetseten.F.
View newest version in sPHENIX GitHub at line 6229 of file jetseten.F
References luchge(), and lucomp().
subroutine luclus (NJET)
Definition at line 8386 of file jetseten.F.
View newest version in sPHENIX GitHub at line 8386 of file jetseten.F
References k, luchge(), lucomp(), luerrm(), max, min, n, HiMain1::np(), p, r2, and v.
function lucomp (KF)
Definition at line 6262 of file jetseten.F.
View newest version in sPHENIX GitHub at line 6262 of file jetseten.F
References lucomp().
subroutine ludcyk (KFL1, KFL2, KFL3, KF)
Definition at line 4136 of file jetseten.F.
View newest version in sPHENIX GitHub at line 4136 of file jetseten.F
References g(), lucomp(), lukfdi(), luptdi(), luzdis(), min, rlu(), ulmass(), x, and z.
Referenced by luprep().
subroutine ludecy (IP)
Definition at line 3251 of file jetseten.F.
View newest version in sPHENIX GitHub at line 3251 of file jetseten.F
References brat, c, cos(), four, ip(), Acts::FiniteStateMachine< Derived, States >::is(), k, Acts::Logger::log(), lucomp(), luerrm(), lukfdi(), lutaud(), max, mdcy, mdme, min, n, HiMain1::np(), p, phi, rlu(), ulangl(), ulmass(), and v.
subroutine luedit (MEDIT)
Definition at line 6899 of file jetseten.F.
View newest version in sPHENIX GitHub at line 6899 of file jetseten.F
References ActsExamples::HepMC3Particle::id(), Acts::FiniteStateMachine< Derived, States >::is(), k, luchge(), lucomp(), luerrm(), max, n, p, sign(), ulangl(), and v.
subroutine lueevt (KFL, ECM)
Definition at line 9940 of file jetseten.F.
View newest version in sPHENIX GitHub at line 9940 of file jetseten.F
References cos(), ip(), k, lu1ent(), lu2ent(), lu3ent(), lu4ent(), luerrm(), luexec(), lulist(), luprep(), luradk(), lushow(), lux3jt(), lux4jt(), luxdif(), luxjet(), luxkfl(), luxtot(), max, min, n, p, phi, v, x2, and x3.
subroutine luerrm (MERR, character, dimension(*) CHMESS)
Definition at line 6378 of file jetseten.F.
View newest version in sPHENIX GitHub at line 6378 of file jetseten.F
References k, lulist(), n, p, PHTimer::stop(), v, and x.
subroutine luexec ()
Definition at line 955 of file jetseten.F.
View newest version in sPHENIX GitHub at line 955 of file jetseten.F
References brat, ip(), k, luboei(), luchge(), lucomp(), ludecy(), luerrm(), luindf(), lulist(), luprep(), lushow(), lustrf(), max, mdcy, mdme, min, n, p, and v.
subroutine lufowo (H10, H20, H30, H40)
Definition at line 9122 of file jetseten.F.
View newest version in sPHENIX GitHub at line 9122 of file jetseten.F
References k, luchge(), lucomp(), luerrm(), n, HiMain1::np(), p, and v.
subroutine lugive (character, dimension(*) CHIN)
Definition at line 547 of file jetseten.F.
View newest version in sPHENIX GitHub at line 547 of file jetseten.F
References brat, k, lucomp(), luerrm(), lulist(), mdcy, mdme, n, p, v, and x.
subroutine luhepc (MCONV)
Definition at line 11204 of file jetseten.F.
View newest version in sPHENIX GitHub at line 11204 of file jetseten.F
References k, lucomp(), luerrm(), min, n, p, and v.
subroutine luindf (IP)
Definition at line 2788 of file jetseten.F.
View newest version in sPHENIX GitHub at line 2788 of file jetseten.F
References ip(), k, lucomp(), luerrm(), lukfdi(), luptdi(), luzdis(), max, min, n, p, phi, rlu(), ulangl(), ulmass(), v, and z.
subroutine lujmas (PMH, PML)
Definition at line 8955 of file jetseten.F.
View newest version in sPHENIX GitHub at line 8955 of file jetseten.F
References cos(), Acts::FiniteStateMachine< Derived, States >::is(), k, luchge(), lucomp(), luerrm(), max, min, n, HiMain1::np(), p, Acts::InternalSpacePoint< SpacePoint >::sp(), and v.
subroutine lujoin (NJOIN, dimension(*) IJOIN)
Definition at line 494 of file jetseten.F.
View newest version in sPHENIX GitHub at line 494 of file jetseten.F
References in, ip(), k, lucomp(), luerrm(), n, p, rlu(), and v.
subroutine lukfdi (KFL1, KFL2, KFL3, KF)
Definition at line 4271 of file jetseten.F.
View newest version in sPHENIX GitHub at line 4271 of file jetseten.F
References lucomp(), luerrm(), max, min, and rlu().
subroutine lulist (MLIST)
Definition at line 7174 of file jetseten.F.
View newest version in sPHENIX GitHub at line 7174 of file jetseten.F
References brat, k, lucomp(), lulogo(), luname(), max, mdcy, mdme, min, n, p, plu(), ulmass(), v, and x.
subroutine lulogo ()
Definition at line 7447 of file jetseten.F.
View newest version in sPHENIX GitHub at line 7447 of file jetseten.F
References Acts::IVisualization3D::line().
Referenced by lulist().
subroutine luname (KF, character CHAU)
Definition at line 6087 of file jetseten.F.
View newest version in sPHENIX GitHub at line 6087 of file jetseten.F
References luchge(), and lucomp().
subroutine luonia (KFL, ECM)
Definition at line 11052 of file jetseten.F.
View newest version in sPHENIX GitHub at line 11052 of file jetseten.F
References cos(), ip(), k, lu1ent(), lu2ent(), lu3ent(), luerrm(), luexec(), lulist(), luprep(), lushow(), max, n, p, phi, rlu(), ulalps(), v, x2, and x3.
subroutine luprep (IP)
Definition at line 1080 of file jetseten.F.
View newest version in sPHENIX GitHub at line 1080 of file jetseten.F
References brat, cos(), four, ip(), ir(), Acts::Test::benchmark_tools_internal::MicroBenchmarkIterImpl< Callable, Input, Result >::iter(), k, k1, lucomp(), ludcyk(), luerrm(), lukfdi(), max, mdcy, mdme, min, n, HiMain1::np(), p, phi, genfit::EventDisplay::prev(), pt2, pyrobo(), rlu(), ulangl(), ulmass(), and v.
subroutine luptdi (KFL, PX, PY)
Definition at line 4603 of file jetseten.F.
View newest version in sPHENIX GitHub at line 4603 of file jetseten.F
References cos(), Acts::Logger::log(), max, phi, HiStrng::pt(), and rlu().
subroutine luradk (ECM, MK, PAK, THEK, PHIK, ALPK)
Definition at line 10246 of file jetseten.F.
View newest version in sPHENIX GitHub at line 10246 of file jetseten.F
References Acts::Logger::log(), max, min, rlu(), ulangl(), and ulmass().
subroutine lurobo (THE, PHI, BEX, BEY, BEZ)
Definition at line 6792 of file jetseten.F.
View newest version in sPHENIX GitHub at line 6792 of file jetseten.F
References cos(), k, luerrm(), min, n, p, phi, and v.
subroutine lushow (IP1, IP2, QMAX)
Definition at line 4744 of file jetseten.F.
View newest version in sPHENIX GitHub at line 4744 of file jetseten.F
References cos(), ip(), k, Acts::Logger::log(), lucomp(), luerrm(), max, min, n, p, phi, HiStrng::pt(), rlu(), rmax(), ulangl(), ulmass(), v, x2, x3, and z.
subroutine lusphe (SPH, APL)
Definition at line 8066 of file jetseten.F.
View newest version in sPHENIX GitHub at line 8066 of file jetseten.F
References cos(), k, luchge(), lucomp(), luerrm(), max, min, n, HiMain1::np(), p, rlu(), Acts::InternalSpacePoint< SpacePoint >::sp(), and v.
subroutine lustrf (IP)
Definition at line 1673 of file jetseten.F.
View newest version in sPHENIX GitHub at line 1673 of file jetseten.F
References d, fd, four, in, ip(), ir(), Acts::FiniteStateMachine< Derived, States >::is(), k, Acts::Logger::log(), lucomp(), luerrm(), lukfdi(), luptdi(), luzdis(), max, min, n, HiMain1::np(), p, HijJet4::pdr(), genfit::EventDisplay::prev(), pyp(), rlu(), sign(), ulmass(), v, and z.
subroutine lutabu (MTABU)
Definition at line 9200 of file jetseten.F.
View newest version in sPHENIX GitHub at line 9200 of file jetseten.F
References a3, brat, ip(), k, Acts::Logger::log(), luchge(), lucomp(), luerrm(), luname(), max, mdcy, mdme, min, n, HiMain1::np(), p, phi, sign(), ulangl(), ulmass(), v, and x.
subroutine lutaud (ITAU, IORIG, KFORIG, NDECAY)
Definition at line 12020 of file jetseten.F.
View newest version in sPHENIX GitHub at line 12020 of file jetseten.F
References k, n, p, rlu(), PHTimer::stop(), v, and x.
Referenced by ludecy().
subroutine lutest (MTEST)
Definition at line 11354 of file jetseten.F.
View newest version in sPHENIX GitHub at line 11354 of file jetseten.F
References brat, k, lu1ent(), lu2ent(), lu3ent(), lu4ent(), lucomp(), lueevt(), luexec(), lulist(), luonia(), lutabu(), max, mdcy, mdme, n, p, phi, plu(), rlu(), PHTimer::stop(), theta(), ulmass(), v, and x.
subroutine luthru (THR, OBL)
Definition at line 8206 of file jetseten.F.
View newest version in sPHENIX GitHub at line 8206 of file jetseten.F
References k, luchge(), lucomp(), luerrm(), min, n, HiMain1::np(), p, phi, rlu(), sign(), ulangl(), and v.
subroutine luupda (MUPDA, LFN)
Definition at line 7614 of file jetseten.F.
View newest version in sPHENIX GitHub at line 7614 of file jetseten.F
References brat, Acts::GeometryHierarchyMap< value_t >::end(), luchge(), lucomp(), luerrm(), lulist(), max, mdcy, mdme, min, ulmass(), and x.
subroutine lux3jt (NJET, CUT, KFL, ECM, X1, X2)
Definition at line 10555 of file jetseten.F.
View newest version in sPHENIX GitHub at line 10555 of file jetseten.F
References Acts::Logger::log(), max, min, rlu(), sign(), ulmass(), x, x2, and x3.
subroutine lux4jt (NJET, CUT, KFL, ECM, KFLN, X1, X2, X4, X12, X14)
Definition at line 10713 of file jetseten.F.
View newest version in sPHENIX GitHub at line 10713 of file jetseten.F
References cos(), ActsExamples::HepMC3Particle::id(), it, Acts::Logger::log(), max, min, rlu(), ulmass(), and x2.
subroutine luxdif (NC, NJET, KFL, ECM, CHI, THE, PHI)
Definition at line 10921 of file jetseten.F.
View newest version in sPHENIX GitHub at line 10921 of file jetseten.F
References cos(), k, max, n, p, phi, rlu(), sign(), sigp, ulmass(), v, x2, and x3.
subroutine luxjet (ECM, NJET, CUT)
Definition at line 10382 of file jetseten.F.
View newest version in sPHENIX GitHub at line 10382 of file jetseten.F
References Acts::Logger::log(), luerrm(), max, min, rlu(), and ulalps().
subroutine luxkfl (KFL, ECM, ECMC, KFLC)
Definition at line 10316 of file jetseten.F.
View newest version in sPHENIX GitHub at line 10316 of file jetseten.F
References luerrm(), max, min, rlu(), sign(), and ulmass().
subroutine luxtot (KFL, ECM, XTOT)
Definition at line 10090 of file jetseten.F.
View newest version in sPHENIX GitHub at line 10090 of file jetseten.F
References Acts::Logger::log(), max, min, sign(), ulalps(), and ulmass().
subroutine luzdis (KFL1, KFL2, PR, Z)
Definition at line 4624 of file jetseten.F.
View newest version in sPHENIX GitHub at line 4624 of file jetseten.F
References Acts::Logger::log(), max, min, rlu(), and z.
function plu (I, J)
Definition at line 7993 of file jetseten.F.
View newest version in sPHENIX GitHub at line 7993 of file jetseten.F
References k, Acts::Logger::log(), luchge(), max, min, n, p, plu(), sign(), ulangl(), ulmass(), and v.
subroutine pyrobo (IMI, IMA, THE, PHI, BEX, BEY, BEZ)
Definition at line 6690 of file jetseten.F.
View newest version in sPHENIX GitHub at line 6690 of file jetseten.F
References cos(), d, k, luerrm(), min, n, p, phi, and v.
subroutine rluget (LFN, MOVE)
Definition at line 6618 of file jetseten.F.
View newest version in sPHENIX GitHub at line 6618 of file jetseten.F
References luerrm(), min, and Acts::Polyhedron::move().
subroutine rluset (LFN, MOVE)
Definition at line 6651 of file jetseten.F.
View newest version in sPHENIX GitHub at line 6651 of file jetseten.F
References luerrm(), max, min, and Acts::Polyhedron::move().
function ulalem (Q2)
Definition at line 6427 of file jetseten.F.
View newest version in sPHENIX GitHub at line 6427 of file jetseten.F
References Acts::Logger::log().
Referenced by leptox(), polleptox(), and pystel().
function ulalps (Q2)
Definition at line 6463 of file jetseten.F.
View newest version in sPHENIX GitHub at line 6463 of file jetseten.F
References Acts::Logger::log(), max, min, and ulalps().
function ulangl (X, Y)
Definition at line 6521 of file jetseten.F.
View newest version in sPHENIX GitHub at line 6521 of file jetseten.F
References Acts::ConeBounds::r(), sign(), ulangl(), x, and y.
function ulmass (KF)
Definition at line 5997 of file jetseten.F.
View newest version in sPHENIX GitHub at line 5997 of file jetseten.F
References lucomp(), max, rlu(), and ulmass().