EIC Software: FairPointSetDraw Class Reference
FairPointSetDraw Class Reference abstract
#include <EicRoot/blob/master/eventdisplay/FairPointSetDraw.h>
Public Member Functions
FairPointSetDraw ()
FairPointSetDraw (const char *name, Color_t color, Style_t mstyle, Int_t iVerbose=1)
virtual ~FairPointSetDraw ()
void SetVerbose (Int_t iVerbose)
virtual void Exec (Option_t *option)
void Reset ()
Public Member Functions inherited from FairTask
FairTask ()
FairTask (const char *name, Int_t iVerbose=1)
virtual ~FairTask ()
void InitTask ()
void ReInitTask ()
void SetParTask ()
virtual void FinishTask ()
virtual void FinishEvent ()
void SetVerbose (Int_t iVerbose)
void SetInputPersistance (Bool_t val)
void CheckInputPersistance (TString branchName)
Protected Member Functions
virtual TVector3 GetVector (TObject *obj)=0
virtual TObject * GetValue (TObject *obj, Int_t i)
virtual void SetParContainers ()
virtual InitStatus Init ()
virtual void Finish ()
Protected Member Functions inherited from FairTask
virtual InitStatus ReInit ()
void InitTasks ()
void ReInitTasks ()
void SetParTasks ()
void FinishTasks ()
void FinishEvents ()
Protected Attributes
Int_t fVerbose
TClonesArray * fPointList
FairEventManager * fEventManager
TEvePointSet * fq
Color_t fColor
Style_t fStyle
Protected Attributes inherited from FairTask
Int_t fVerbose
Int_t fInputPersistance
Indicates if input branch is persistant.
FairLogger * fLogger
Private Member Functions
FairPointSetDraw (const FairPointSetDraw &)
FairPointSetDraw & operator= (const FairPointSetDraw &)
ClassDef (FairPointSetDraw, 1)
Detailed Description
Definition at line 27 of file FairPointSetDraw.h.
View newest version in sPHENIX GitHub at line 27 of file FairPointSetDraw.h
Constructor & Destructor Documentation
FairPointSetDraw::FairPointSetDraw ()
Default constructor
Definition at line 22 of file FairPointSetDraw.cxx.
View newest version in sPHENIX GitHub at line 22 of file FairPointSetDraw.cxx
FairPointSetDraw::FairPointSetDraw (const char * name, Color_t color, Style_t mstyle, Int_t iVerbose = 1)
Standard constructor
Parameters
name Name of task
iVerbose Verbosity level
Definition at line 37 of file FairPointSetDraw.cxx.
View newest version in sPHENIX GitHub at line 37 of file FairPointSetDraw.cxx
FairPointSetDraw::~FairPointSetDraw () virtual
Destructor
Definition at line 99 of file FairPointSetDraw.cxx.
View newest version in sPHENIX GitHub at line 99 of file FairPointSetDraw.cxx
FairPointSetDraw::FairPointSetDraw (const FairPointSetDraw &) private
Member Function Documentation
FairPointSetDraw::ClassDef (FairPointSetDraw , 1) private
void FairPointSetDraw::Exec (Option_t * option) virtual
Executed task
Definition at line 67 of file FairPointSetDraw.cxx.
View newest version in sPHENIX GitHub at line 67 of file FairPointSetDraw.cxx
References fColor, fPointList, fq, fStyle, GetValue(), GetVector(), p, and Reset().
void FairPointSetDraw::Finish (void) protected virtual
Action after each event
Reimplemented from FairTask.
Definition at line 109 of file FairPointSetDraw.cxx.
View newest version in sPHENIX GitHub at line 109 of file FairPointSetDraw.cxx
TObject * FairPointSetDraw::GetValue (TObject * obj, Int_t i) protected virtual
Definition at line 93 of file FairPointSetDraw.cxx.
View newest version in sPHENIX GitHub at line 93 of file FairPointSetDraw.cxx
Referenced by Exec().
virtual TVector3 FairPointSetDraw::GetVector (TObject * obj) protected pure virtual
Implemented in FairHitPointSetDraw, and FairMCPointDraw.
Referenced by Exec().
InitStatus FairPointSetDraw::Init (void) protected virtual
Intialisation at begin of run. To be implemented in the derived class. Success If not kSUCCESS, task will be set inactive.
Reimplemented from FairTask.
Definition at line 49 of file FairPointSetDraw.cxx.
View newest version in sPHENIX GitHub at line 49 of file FairPointSetDraw.cxx
References fEventManager, fPointList, fq, fVerbose, FairRootManager::GetObject(), FairEventManager::Instance(), FairRootManager::Instance(), and kSUCCESS.
FairPointSetDraw& FairPointSetDraw::operator= (const FairPointSetDraw &) private
void FairPointSetDraw::Reset ()
Definition at line 113 of file FairPointSetDraw.cxx.
View newest version in sPHENIX GitHub at line 113 of file FairPointSetDraw.cxx
References fEventManager, and fq.
Referenced by Exec().
void FairPointSetDraw::SetParContainers () protected virtual
Intialise parameter containers. To be implemented in the derived class.
Reimplemented from FairTask.
Definition at line 103 of file FairPointSetDraw.cxx.
View newest version in sPHENIX GitHub at line 103 of file FairPointSetDraw.cxx
void FairPointSetDraw::SetVerbose (Int_t iVerbose) inline
Set verbosity level. For this task and all of the subtasks.
Definition at line 46 of file FairPointSetDraw.h.
View newest version in sPHENIX GitHub at line 46 of file FairPointSetDraw.h
References fVerbose.
Member Data Documentation
Color_t FairPointSetDraw::fColor protected
Definition at line 63 of file FairPointSetDraw.h.
View newest version in sPHENIX GitHub at line 63 of file FairPointSetDraw.h
Referenced by Exec().
FairEventManager* FairPointSetDraw::fEventManager protected
Definition at line 61 of file FairPointSetDraw.h.
View newest version in sPHENIX GitHub at line 61 of file FairPointSetDraw.h
Referenced by Init(), and Reset().
TClonesArray* FairPointSetDraw::fPointList protected
Definition at line 60 of file FairPointSetDraw.h.
View newest version in sPHENIX GitHub at line 60 of file FairPointSetDraw.h
Referenced by Exec(), and Init().
TEvePointSet* FairPointSetDraw::fq protected
Definition at line 62 of file FairPointSetDraw.h.
View newest version in sPHENIX GitHub at line 62 of file FairPointSetDraw.h
Referenced by Exec(), Init(), and Reset().
Style_t FairPointSetDraw::fStyle protected
Definition at line 64 of file FairPointSetDraw.h.
View newest version in sPHENIX GitHub at line 64 of file FairPointSetDraw.h
Referenced by Exec().
Int_t FairPointSetDraw::fVerbose protected
Definition at line 55 of file FairPointSetDraw.h.
View newest version in sPHENIX GitHub at line 55 of file FairPointSetDraw.h
Referenced by FairHitPointSetDraw::GetVector(), Init(), and SetVerbose().
The documentation for this class was generated from the following files:
EicRoot/blob/master/eventdisplay/FairPointSetDraw.h
EicRoot/blob/master/eventdisplay/FairPointSetDraw.cxx