EIC Software: eicsmeardetectors/blob/master/SmeareSTAR_0_0.cxx File Reference
SmeareSTAR_0_0.cxx File Reference
#include "eicsmear/erhic/VirtualParticle.h"
#include "eicsmear/smear/Acceptance.h"
#include "eicsmear/smear/Device.h"
#include "eicsmear/smear/Detector.h"
#include "eicsmear/smear/Smearer.h"
#include "eicsmear/smear/ParticleMCS.h"
#include "eicsmear/smear/PerfectID.h"
#include <eicsmear/smear/Smear.h>
#include <eicsmear/erhic/ParticleMC.h>
#include "Math/Vector4D.h"
Functions
static double etaToTheta (double eta)
static Smear::Acceptance::Zone zoneEta (double etamin, double etamax)
Smear::Detector BuildeSTAR_0_0 ()
Detailed Description
Example smearing script for the eSTAR detector
Author
Thomas Burton
Date
2014-03-21
Copyright
2014 Brookhaven National Lab
Definition in file SmeareSTAR_0_0.cxx.
Function Documentation
Smear::Detector BuildeSTAR_0_0 ()
Smearing parameterisations for the eSTAR detector.
Based on parameterisations given in Zhangbu Xu's talk here (slide 5): https://wiki.bnl.gov/conferences/index.php/January_2014 This includes momentum and energy resolutions, but no particle identification.
Note: you must gSystem->Load("libeicsmear") BEFORE loading this script, as ROOT needs to understand what a Smear::Detector is.
Definition at line 50 of file SmeareSTAR_0_0.cxx.
View newest version in sPHENIX GitHub at line 50 of file SmeareSTAR_0_0.cxx
References Smear::Smearer::Accept, Smear::Detector::AddDevice(), Smear::Acceptance::AddZone(), Smear::kCharged, Smear::kElectromagnetic, Smear::kHadronic, phi, pid, Smear::Acceptance::SetCharge(), Smear::Detector::SetEventKinematicsCalculator(), theta(), and zoneEta().
Referenced by BuildByName().
static double etaToTheta (double eta) static
Helper function to convert eta to theta (radians)
Detector acceptances require theta, not eta
Definition at line 27 of file SmeareSTAR_0_0.cxx.
View newest version in sPHENIX GitHub at line 27 of file SmeareSTAR_0_0.cxx
Referenced by BuildPerfectDetector(), BuildWithTof(), makeZone(), and zoneEta().
static Smear::Acceptance::Zone zoneEta (double etamin, double etamax) static
Helper function producing a zone in eta
Definition at line 34 of file SmeareSTAR_0_0.cxx.
View newest version in sPHENIX GitHub at line 34 of file SmeareSTAR_0_0.cxx
References etaToTheta().
Referenced by BuildeSTAR_0_0().