EIC Software: fun4all_eicdetectors/blob/master/simulation/g4simulation/g4lblvtx/EicFRichDetector.cc File Reference
EicFRichDetector.cc File Reference
#include "EicFRichDetector.h"
#include <phparameter/PHParameters.h>
#include <g4main/PHG4Detector.h>
#include <Geant4/G4Box.hh>
#include <Geant4/G4Polycone.hh>
#include <Geant4/G4Color.hh>
#include <Geant4/G4LogicalVolume.hh>
#include <Geant4/G4Material.hh>
#include <Geant4/G4PVPlacement.hh>
#include <Geant4/G4SystemOfUnits.hh>
#include <Geant4/G4VisAttributes.hh>
#include <cmath>
#include <iostream>
Functions
double bp_r (double z_cm)
double rmax (double z_cm)
Function Documentation
double bp_r (double z_cm)
Definition at line 45 of file EicFRichDetector.cc.
View newest version in sPHENIX GitHub at line 45 of file EicFRichDetector.cc
Referenced by EicFRichDetector::addDetectorSection().
double rmax (double z_cm)
Definition at line 46 of file EicFRichDetector.cc.
View newest version in sPHENIX GitHub at line 46 of file EicFRichDetector.cc
Referenced by EicFRichDetector::addDetectorSection(), Acts::Test::BOOST_AUTO_TEST_CASE(), Acts::Test::BOOST_DATA_TEST_CASE(), buildBarrelRouting(), buildEndcapRouting(), calcta(), Acts::ConeVolumeBounds::ConeVolumeBounds(), create_element(), vc2020_03_20::CreateGeometry(), Acts::CutoutCylinderVolumeBounds::CutoutCylinderVolumeBounds(), Acts::CylinderVolumeBounds::CylinderVolumeBounds(), EicToyModel::DrawFlatFieldLines(), fordop(), Acts::DiscTrapezoidBounds::halfLengthY(), hijset(), Acts::ConeVolumeBounds::inside(), ip(), lushow(), medinit(), nthick(), pyptis(), pyshow(), radgam_pol(), Acts::DiscTrapezoidBounds::rCenter(), ActsExamples::RootMaterialDecorator::RootMaterialDecorator(), and rv2().