EIC Software: nucleus Class Reference
nucleus Class Reference
#include <estarlight/blob/master/include/nucleus.h>
Public Member Functions
nucleus ()
nucleus (const int Z, const int A, const int productionMode)
~nucleus ()
void init ()
int Z () const
returns atomic number of nucleus
int A () const
returns nucleon number of nucleus
int productionMode () const
double formFactor (const double t) const
double dipoleFormFactor (const double t, const double t0) const
double thickness (const double b) const
double nuclearRadius () const
double rho0 () const
Private Member Functions
double woodSaxonSkinDepth () const
double rws (const double r) const
Private Attributes
int _Z
atomic number of nucleus
int _A
nucleon number of nucleus
int _productionMode
double _r0
double _Radius
double _rho0
Detailed Description
Definition at line 42 of file nucleus.h.
View newest version in sPHENIX GitHub at line 42 of file nucleus.h
Constructor & Destructor Documentation
nucleus::nucleus ()
nucleus::nucleus (const int Z, const int A, const int productionMode)
Definition at line 47 of file nucleus.cpp.
View newest version in sPHENIX GitHub at line 47 of file nucleus.cpp
References init().
nucleus::~nucleus ()
Definition at line 126 of file nucleus.cpp.
View newest version in sPHENIX GitHub at line 126 of file nucleus.cpp
Member Function Documentation
int nucleus::A () const inline
returns nucleon number of nucleus
Definition at line 55 of file nucleus.h.
View newest version in sPHENIX GitHub at line 55 of file nucleus.h
References _A.
Referenced by e_narrowResonanceCrossSection::crossSectionCalculation(), e_wideResonanceCrossSection::crossSectionCalculation(), wideResonanceCrossSection::crossSectionCalculation(), incoherentVMCrossSection::crossSectionCalculation(), narrowResonanceCrossSection::crossSectionCalculation(), photonNucleusCrossSection::e_getcsgA(), photonNucleusCrossSection::getcsgA(), incoherentPhotonNucleusLuminosity::incoherentPhotonNucleusDifferentialLuminosity(), e_narrowResonanceCrossSection::makeGammaPQ2dependence(), Gammaavectormeson::momenta(), photonNucleusCrossSection::photonFlux(), photonElectronLuminosity::photonNucleusDifferentialLuminosity(), photonNucleusLuminosity::photonNucleusDifferentialLuminosity(), beamBeamSystem::probabilityOfHadronBreakup(), Gammaavectormeson::pTgamma(), photonNucleusCrossSection::sigma_A(), and twoPhotonLuminosity::twoPhotonDifferentialLuminosity().
double nucleus::dipoleFormFactor (const double t, const double t0) const
Definition at line 173 of file nucleus.cpp.
View newest version in sPHENIX GitHub at line 173 of file nucleus.cpp
Referenced by Gammaavectormeson::momenta().
double nucleus::formFactor (const double t) const
Definition at line 146 of file nucleus.cpp.
View newest version in sPHENIX GitHub at line 146 of file nucleus.cpp
References _A, _Z, cos(), starlightConstants::hbarc, nuclearRadius(), Acts::IntegrationTest::R, and t.
Referenced by photonNucleusCrossSection::e_getcsgA(), photonNucleusCrossSection::getcsgA(), Gammaavectormeson::momenta(), Gammagammasingle::pp1(), Gammagammasingle::pp2(), Gammaavectormeson::pTgamma(), photonNucleusLuminosity::pttablegen(), and photonNucleusLuminosity::vmsigmapt().
void nucleus::init ()
Definition at line 57 of file nucleus.cpp.
View newest version in sPHENIX GitHub at line 57 of file nucleus.cpp
References _A, _Radius, _rho0, _Z, and printWarn.
Referenced by nucleus().
double nucleus::nuclearRadius () const inline
Definition at line 67 of file nucleus.h.
View newest version in sPHENIX GitHub at line 67 of file nucleus.h
References _Radius.
Referenced by twoPhotonLuminosity::D2LDMDY(), formFactor(), twoPhotonLuminosity::integral(), Gammaavectormeson::momenta(), photonNucleusCrossSection::photonFlux(), Gammagammasingle::pp1(), Gammagammasingle::pp2(), beamBeamSystem::probabilityOfHadronBreakup(), Gammaavectormeson::pTgamma(), photonNucleusLuminosity::pttablegen(), rws(), and photonNucleusLuminosity::vmsigmapt().
int nucleus::productionMode () const inline
Definition at line 56 of file nucleus.h.
View newest version in sPHENIX GitHub at line 56 of file nucleus.h
References _productionMode.
double nucleus::rho0 () const inline
Definition at line 68 of file nucleus.h.
View newest version in sPHENIX GitHub at line 68 of file nucleus.h
References _rho0.
Referenced by photonNucleusCrossSection::sigma_A().
double nucleus::rws (const double r) const private
Definition at line 131 of file nucleus.cpp.
View newest version in sPHENIX GitHub at line 131 of file nucleus.cpp
References _Z, nuclearRadius(), starlightConstants::pi, and woodSaxonSkinDepth().
Referenced by thickness().
double nucleus::thickness (const double b) const
Definition at line 181 of file nucleus.cpp.
View newest version in sPHENIX GitHub at line 181 of file nucleus.cpp
References G4BECAL::radius, and rws().
Referenced by photonNucleusCrossSection::sigma_A().
double nucleus::woodSaxonSkinDepth () const inline private
Definition at line 72 of file nucleus.h.
View newest version in sPHENIX GitHub at line 72 of file nucleus.h
Referenced by rws().
int nucleus::Z () const inline
returns atomic number of nucleus
Definition at line 54 of file nucleus.h.
View newest version in sPHENIX GitHub at line 54 of file nucleus.h
References _Z.
Referenced by twoPhotonLuminosity::D2LDMDY(), incoherentPhotonNucleusLuminosity::incoherentPhotonNucleusDifferentialLuminosity(), beam::photonDensity(), photonNucleusCrossSection::photonFlux(), photonNucleusLuminosity::photonNucleusDifferentialLuminosity(), photonElectronLuminosity::photonNucleusDifferentialLuminosity(), and twoPhotonLuminosity::twoPhotonDifferentialLuminosity().
Member Data Documentation
int nucleus::_A private
nucleon number of nucleus
Definition at line 76 of file nucleus.h.
View newest version in sPHENIX GitHub at line 76 of file nucleus.h
Referenced by A(), formFactor(), and init().
int nucleus::_productionMode private
Definition at line 77 of file nucleus.h.
View newest version in sPHENIX GitHub at line 77 of file nucleus.h
Referenced by productionMode().
double nucleus::_r0 private
Definition at line 79 of file nucleus.h.
View newest version in sPHENIX GitHub at line 79 of file nucleus.h
double nucleus::_Radius private
Definition at line 80 of file nucleus.h.
View newest version in sPHENIX GitHub at line 80 of file nucleus.h
Referenced by init(), and nuclearRadius().
double nucleus::_rho0 private
Definition at line 81 of file nucleus.h.
View newest version in sPHENIX GitHub at line 81 of file nucleus.h
Referenced by init(), and rho0().
int nucleus::_Z private
atomic number of nucleus
Definition at line 75 of file nucleus.h.
View newest version in sPHENIX GitHub at line 75 of file nucleus.h
Referenced by formFactor(), init(), rws(), and Z().
The documentation for this class was generated from the following files:
estarlight/blob/master/include/nucleus.h
estarlight/blob/master/src/nucleus.cpp