EIC Software: g4lblvtx/blob/master/macros/auxiliary_studies/hadron_phi_asymmetry/G4_GEM.C File Reference
G4_GEM.C File Reference
#include <g4detectors/PHG4SectorSubsystem.h>
#include <g4main/PHG4Reco.h>
#include <string>
Namespaces
namespace Enable
Macros
#define MACRO_G4GEM_C
Functions
int make_GEM_station (string name, PHG4Reco *g4Reco, double zpos, double etamin, double etamax, const int N_Sector=8)
void AddLayers_MiniTPCDrift (PHG4SectorSubsystem *gem)
Add drift layers to mini TPC.
void EGEM_Init ()
void FGEM_Init ()
void EGEMSetup (PHG4Reco *g4Reco)
void FGEMSetup (PHG4Reco *g4Reco)
void addPassiveMaterial (PHG4Reco *g4Reco)
Macro Definition Documentation
#define MACRO_G4GEM_C
Definition at line 2 of file G4_GEM.C.
View newest version in sPHENIX GitHub at line 2 of file G4_GEM.C
Function Documentation
void AddLayers_MiniTPCDrift (PHG4SectorSubsystem * gem)
Add drift layers to mini TPC.
void addPassiveMaterial (PHG4Reco * g4Reco)
Definition at line 48 of file G4_GEM.C.
View newest version in sPHENIX GitHub at line 48 of file G4_GEM.C
References kdfinder::abs(), PHG4Reco::registerSubsystem(), PHG4DetectorSubsystem::set_double_param(), PHG4DetectorSubsystem::set_string_param(), and PHG4DetectorSubsystem::SuperDetector().
void EGEM_Init ()
Definition at line 23 of file G4_GEM.C.
View newest version in sPHENIX GitHub at line 23 of file G4_GEM.C
void EGEMSetup (PHG4Reco * g4Reco)
Definition at line 34 of file G4_GEM.C.
View newest version in sPHENIX GitHub at line 34 of file G4_GEM.C
References make_GEM_station(), and thickness.
void FGEM_Init ()
Definition at line 29 of file G4_GEM.C.
View newest version in sPHENIX GitHub at line 29 of file G4_GEM.C
void FGEMSetup (PHG4Reco * g4Reco)
Definition at line 43 of file G4_GEM.C.
View newest version in sPHENIX GitHub at line 43 of file G4_GEM.C
References make_GEM_station(), and thickness.
int make_GEM_station (string name, PHG4Reco * g4Reco, double zpos, double etamin, double etamax, const int N_Sector = 8)