EIC Software: EicProtoGenerator Class Reference
EicProtoGenerator Class Reference
#include <EicRoot/blob/master/eic/proto/EicProtoGenerator.h>
Public Member Functions
EicProtoGenerator (const char *name)
~EicProtoGenerator ()
void SetNaiveVerticalBeamDivergence (double value)
void SetNaiveHorizontalBeamDivergence (double value)
void SetNaiveHorizontalBeamRotation (double value)
void SetVertex (double x, double y, double z=0.0)
double GetVx () const
double GetVy () const
double GetVz () const
void SetVertexSmearing (double sx, double sy, double sz=0.0)
void SetVertexRange (double rx, double ry, double rz=0.0)
double GetVxSmearing () const
double GetVySmearing () const
double GetVzSmearing () const
TVector3 GetSimulatedPrimaryVertex (void)
TVector3 GetModifiedTrack (const TVector3 track)
ClassDef (EicProtoGenerator, 1)
Public Member Functions inherited from FairGenerator
FairGenerator ()
FairGenerator (const char *name, const char *title="FAIR Generator")
virtual ~FairGenerator ()
virtual Bool_t ReadEvent (FairPrimaryGenerator *primGen)=0
virtual Bool_t Init ()
ClassDef (FairGenerator, 1)
Public Attributes
double mVerticalBeamDivergence
double mHorizontalBeamDivergence
double mHorizontalBeamRotation
Double_t mCoord [3]
Double_t mCoordSigma [3]
Double_t mCoordRange [3]
Bool_t mGaussianCoordinateSmearing
Detailed Description
Definition at line 8 of file EicProtoGenerator.h.
View newest version in sPHENIX GitHub at line 8 of file EicProtoGenerator.h
Constructor & Destructor Documentation
EicProtoGenerator::EicProtoGenerator (const char * name) inline
Definition at line 11 of file EicProtoGenerator.h.
View newest version in sPHENIX GitHub at line 11 of file EicProtoGenerator.h
References mCoord, mCoordRange, mCoordSigma, and mGaussianCoordinateSmearing.
EicProtoGenerator::~EicProtoGenerator () inline
Definition at line 19 of file EicProtoGenerator.h.
View newest version in sPHENIX GitHub at line 19 of file EicProtoGenerator.h
Member Function Documentation
EicProtoGenerator::ClassDef (EicProtoGenerator , 1)
TVector3 EicProtoGenerator::GetModifiedTrack (const TVector3 track)
Definition at line 26 of file EicProtoGenerator.cxx.
View newest version in sPHENIX GitHub at line 26 of file EicProtoGenerator.cxx
References in, mHorizontalBeamDivergence, mHorizontalBeamRotation, mVerticalBeamDivergence, and rw.
Referenced by EicAsciiBoxGenerator::ReadEvent(), EicBoxGenerator::ReadEvent(), and EicEventGenerator::ReadEvent().
TVector3 EicProtoGenerator::GetSimulatedPrimaryVertex (void)
Definition at line 10 of file EicProtoGenerator.cxx.
View newest version in sPHENIX GitHub at line 10 of file EicProtoGenerator.cxx
References mCoord, mCoordRange, mCoordSigma, mGaussianCoordinateSmearing, and vtx().
Referenced by EicBoxGenerator::ReadEvent(), and EicEventGenerator::ReadEvent().
double EicProtoGenerator::GetVx () const inline
Definition at line 34 of file EicProtoGenerator.h.
View newest version in sPHENIX GitHub at line 34 of file EicProtoGenerator.h
References mCoord.
Referenced by FwdTrackFinder::ResetVtxNode(), and FwdTrackFinder::UpdateVtxNode().
double EicProtoGenerator::GetVxSmearing () const inline
Definition at line 46 of file EicProtoGenerator.h.
View newest version in sPHENIX GitHub at line 46 of file EicProtoGenerator.h
References mCoordSigma.
Referenced by FwdTrackFinder::ResetVtxNode(), and FwdTrackFinder::UpdateVtxNode().
double EicProtoGenerator::GetVy () const inline
Definition at line 35 of file EicProtoGenerator.h.
View newest version in sPHENIX GitHub at line 35 of file EicProtoGenerator.h
References mCoord.
Referenced by FwdTrackFinder::ResetVtxNode(), and FwdTrackFinder::UpdateVtxNode().
double EicProtoGenerator::GetVySmearing () const inline
Definition at line 47 of file EicProtoGenerator.h.
View newest version in sPHENIX GitHub at line 47 of file EicProtoGenerator.h
References mCoordSigma.
Referenced by FwdTrackFinder::ResetVtxNode(), and FwdTrackFinder::UpdateVtxNode().
double EicProtoGenerator::GetVz () const inline
Definition at line 36 of file EicProtoGenerator.h.
View newest version in sPHENIX GitHub at line 36 of file EicProtoGenerator.h
References mCoord.
Referenced by FwdTrackFinder::ConfigureMediaBank(), and FwdTrackFinder::Init().
double EicProtoGenerator::GetVzSmearing () const inline
Definition at line 48 of file EicProtoGenerator.h.
View newest version in sPHENIX GitHub at line 48 of file EicProtoGenerator.h
References mCoordSigma.
void EicProtoGenerator::SetNaiveHorizontalBeamDivergence (double value) inline
Definition at line 25 of file EicProtoGenerator.h.
View newest version in sPHENIX GitHub at line 25 of file EicProtoGenerator.h
References mHorizontalBeamDivergence, and value.
void EicProtoGenerator::SetNaiveHorizontalBeamRotation (double value) inline
Definition at line 27 of file EicProtoGenerator.h.
View newest version in sPHENIX GitHub at line 27 of file EicProtoGenerator.h
References mHorizontalBeamRotation, and value.
Referenced by simulation().
void EicProtoGenerator::SetNaiveVerticalBeamDivergence (double value) inline
Definition at line 24 of file EicProtoGenerator.h.
View newest version in sPHENIX GitHub at line 24 of file EicProtoGenerator.h
References mVerticalBeamDivergence, and value.
void EicProtoGenerator::SetVertex (double x, double y, double z = 0.0) inline
Definition at line 31 of file EicProtoGenerator.h.
View newest version in sPHENIX GitHub at line 31 of file EicProtoGenerator.h
References mCoord, x, y, and z.
Referenced by simulation().
void EicProtoGenerator::SetVertexRange (double rx, double ry, double rz = 0.0) inline
Definition at line 41 of file EicProtoGenerator.h.
View newest version in sPHENIX GitHub at line 41 of file EicProtoGenerator.h
References mCoordRange, and mGaussianCoordinateSmearing.
void EicProtoGenerator::SetVertexSmearing (double sx, double sy, double sz = 0.0) inline
Definition at line 37 of file EicProtoGenerator.h.
View newest version in sPHENIX GitHub at line 37 of file EicProtoGenerator.h
References mCoordSigma, and mGaussianCoordinateSmearing.
Member Data Documentation
Double_t EicProtoGenerator::mCoord[3]
Definition at line 56 of file EicProtoGenerator.h.
View newest version in sPHENIX GitHub at line 56 of file EicProtoGenerator.h
Referenced by EicProtoGenerator(), GetSimulatedPrimaryVertex(), GetVx(), GetVy(), GetVz(), EicAsciiBoxGenerator::ReadEvent(), EicBoxGenerator::ReadEvent(), and SetVertex().
Double_t EicProtoGenerator::mCoordRange[3]
Definition at line 58 of file EicProtoGenerator.h.
View newest version in sPHENIX GitHub at line 58 of file EicProtoGenerator.h
Referenced by EicProtoGenerator(), GetSimulatedPrimaryVertex(), EicAsciiBoxGenerator::ReadEvent(), EicBoxGenerator::ReadEvent(), and SetVertexRange().
Double_t EicProtoGenerator::mCoordSigma[3]
Definition at line 57 of file EicProtoGenerator.h.
View newest version in sPHENIX GitHub at line 57 of file EicProtoGenerator.h
Referenced by EicProtoGenerator(), GetSimulatedPrimaryVertex(), GetVxSmearing(), GetVySmearing(), GetVzSmearing(), EicAsciiBoxGenerator::ReadEvent(), EicBoxGenerator::ReadEvent(), and SetVertexSmearing().
Bool_t EicProtoGenerator::mGaussianCoordinateSmearing
Definition at line 59 of file EicProtoGenerator.h.
View newest version in sPHENIX GitHub at line 59 of file EicProtoGenerator.h
Referenced by EicProtoGenerator(), GetSimulatedPrimaryVertex(), EicAsciiBoxGenerator::ReadEvent(), EicBoxGenerator::ReadEvent(), SetVertexRange(), and SetVertexSmearing().
double EicProtoGenerator::mHorizontalBeamDivergence
Definition at line 54 of file EicProtoGenerator.h.
View newest version in sPHENIX GitHub at line 54 of file EicProtoGenerator.h
Referenced by GetModifiedTrack(), and SetNaiveHorizontalBeamDivergence().
double EicProtoGenerator::mHorizontalBeamRotation
Definition at line 54 of file EicProtoGenerator.h.
View newest version in sPHENIX GitHub at line 54 of file EicProtoGenerator.h
Referenced by GetModifiedTrack(), and SetNaiveHorizontalBeamRotation().
double EicProtoGenerator::mVerticalBeamDivergence
Definition at line 54 of file EicProtoGenerator.h.
View newest version in sPHENIX GitHub at line 54 of file EicProtoGenerator.h
Referenced by GetModifiedTrack(), and SetNaiveVerticalBeamDivergence().
The documentation for this class was generated from the following files:
EicRoot/blob/master/eic/proto/EicProtoGenerator.h
EicRoot/blob/master/eic/proto/EicProtoGenerator.cxx