EIC Software: EicRoot/blob/master/eic/cad/wizard/EicCadWizardCut.h File Reference
EicCadWizardCut.h File Reference
#include <vector>
Classes
class EicCadWizardCut
Macros
#define _ANGULAR_TOLERANCE_ (1E-10)
#define _SPATIAL_TOLERANCE_ (1E-10)
#define SQR(x) ((x)*(x))
Functions
TGeoCombiTrans * Ax3ToCombiTrans (const char *name, const gp_Ax3 &ax3, double offset)
Macro Definition Documentation
#define _ANGULAR_TOLERANCE_ (1E-10)
Definition at line 12 of file EicCadWizardCut.h.
View newest version in sPHENIX GitHub at line 12 of file EicCadWizardCut.h
#define _SPATIAL_TOLERANCE_ (1E-10)
Definition at line 13 of file EicCadWizardCut.h.
View newest version in sPHENIX GitHub at line 13 of file EicCadWizardCut.h
#define SQR (x) ((x)*(x))
Definition at line 15 of file EicCadWizardCut.h.
View newest version in sPHENIX GitHub at line 15 of file EicCadWizardCut.h
Function Documentation
TGeoCombiTrans* Ax3ToCombiTrans (const char * name, const gp_Ax3 & ax3, double offset)
Definition at line 1141 of file EicCadWizard.cxx.
View newest version in sPHENIX GitHub at line 1141 of file EicCadWizard.cxx
References data.
Referenced by EicCadWizardTorus::BuildRootVolume(), EicCadWizardCone::BuildRootVolume(), and EicCadWizardCylinder::BuildRootVolume().