EIC Software: RawTowerZDCGeom Class Reference
RawTowerZDCGeom Class Reference
#include <fun4all_eicdetectors/blob/master/reconstruction/eiczdcbase/RawTowerZDCGeom.h>
Public Member Functions
~RawTowerZDCGeom () override
void identify (std::ostream &os=std::cout) const override
virtual void set_id (RawTowerZDCDefs::keytype)
virtual RawTowerZDCDefs::keytype get_id () const
virtual int get_bineta () const
virtual int get_binphi () const
virtual int get_binl () const
virtual int get_column () const
virtual int get_row () const
virtual void set_center_x (double)
virtual void set_center_y (double)
virtual void set_center_z (double)
virtual void set_size_x (double)
virtual void set_size_y (double)
virtual void set_size_z (double)
virtual double get_center_x () const
virtual double get_center_y () const
virtual double get_center_z () const
virtual double get_size_x () const
virtual double get_size_y () const
virtual double get_size_z () const
virtual double get_volume () const
virtual double get_center_radius () const
virtual double get_eta () const
virtual double get_theta () const
virtual double get_phi () const
virtual void set_tower_type (int)
virtual int get_tower_type () const
virtual double get_roty () const
virtual double get_rotz () const
virtual void set_roty (double)
virtual void set_rotz (double)
Public Member Functions inherited from PHObject
PHObject ()
ctor
~PHObject () override
dtor
virtual PHObject * CloneMe () const
Virtual copy constructor.
virtual PHObject * clone () const final
PHObject * Clone (const char *newname="") const final
void Copy (TObject &object) const final
virtual void Reset ()
Clear Event.
virtual int isValid () const
isValid returns non zero if object contains vailid data
virtual int isValid (const float) const
virtual int isValid (const double) const
virtual int isValid (const int) const
virtual int isValid (const unsigned int) const
virtual int isImplemented (const float f) const
virtual int isImplemented (const double f) const
virtual int isImplemented (const int i) const
virtual int isImplemented (const unsigned int i) const
virtual int Integrate () const
virtual int Integrate (PHObject *)
virtual void CopyFrom (const PHObject *obj)
Protected Member Functions
RawTowerZDCGeom ()
Detailed Description
Definition at line 12 of file RawTowerZDCGeom.h.
View newest version in sPHENIX GitHub at line 12 of file RawTowerZDCGeom.h
Constructor & Destructor Documentation
RawTowerZDCGeom::~RawTowerZDCGeom () inline override
Definition at line 15 of file RawTowerZDCGeom.h.
View newest version in sPHENIX GitHub at line 15 of file RawTowerZDCGeom.h
RawTowerZDCGeom::RawTowerZDCGeom () inline protected
Definition at line 193 of file RawTowerZDCGeom.h.
View newest version in sPHENIX GitHub at line 193 of file RawTowerZDCGeom.h
Member Function Documentation
virtual int RawTowerZDCGeom::get_bineta () const inline virtual
Reimplemented in RawTowerZDCGeomv1.
Definition at line 27 of file RawTowerZDCGeom.h.
View newest version in sPHENIX GitHub at line 27 of file RawTowerZDCGeom.h
References PHOOL_VIRTUAL_WARN.
virtual int RawTowerZDCGeom::get_binl () const inline virtual
Reimplemented in RawTowerZDCGeomv1.
Definition at line 39 of file RawTowerZDCGeom.h.
View newest version in sPHENIX GitHub at line 39 of file RawTowerZDCGeom.h
References PHOOL_VIRTUAL_WARN.
virtual int RawTowerZDCGeom::get_binphi () const inline virtual
Reimplemented in RawTowerZDCGeomv1.
Definition at line 33 of file RawTowerZDCGeom.h.
View newest version in sPHENIX GitHub at line 33 of file RawTowerZDCGeom.h
References PHOOL_VIRTUAL_WARN.
virtual double RawTowerZDCGeom::get_center_radius () const inline virtual
Reimplemented in RawTowerZDCGeomv1.
Definition at line 135 of file RawTowerZDCGeom.h.
View newest version in sPHENIX GitHub at line 135 of file RawTowerZDCGeom.h
References PHOOL_VIRTUAL_WARN.
virtual double RawTowerZDCGeom::get_center_x () const inline virtual
Reimplemented in RawTowerZDCGeomv1.
Definition at line 93 of file RawTowerZDCGeom.h.
View newest version in sPHENIX GitHub at line 93 of file RawTowerZDCGeom.h
References PHOOL_VIRTUAL_WARN.
virtual double RawTowerZDCGeom::get_center_y () const inline virtual
Reimplemented in RawTowerZDCGeomv1.
Definition at line 99 of file RawTowerZDCGeom.h.
View newest version in sPHENIX GitHub at line 99 of file RawTowerZDCGeom.h
References PHOOL_VIRTUAL_WARN.
virtual double RawTowerZDCGeom::get_center_z () const inline virtual
Reimplemented in RawTowerZDCGeomv1.
Definition at line 105 of file RawTowerZDCGeom.h.
View newest version in sPHENIX GitHub at line 105 of file RawTowerZDCGeom.h
References PHOOL_VIRTUAL_WARN.
virtual int RawTowerZDCGeom::get_column () const inline virtual
Reimplemented in RawTowerZDCGeomv1.
Definition at line 45 of file RawTowerZDCGeom.h.
View newest version in sPHENIX GitHub at line 45 of file RawTowerZDCGeom.h
References PHOOL_VIRTUAL_WARN.
virtual double RawTowerZDCGeom::get_eta () const inline virtual
Reimplemented in RawTowerZDCGeomv1.
Definition at line 141 of file RawTowerZDCGeom.h.
View newest version in sPHENIX GitHub at line 141 of file RawTowerZDCGeom.h
References PHOOL_VIRTUAL_WARN.
virtual RawTowerZDCDefs::keytype RawTowerZDCGeom::get_id () const inline virtual
Reimplemented in RawTowerZDCGeomv1.
Definition at line 21 of file RawTowerZDCGeom.h.
View newest version in sPHENIX GitHub at line 21 of file RawTowerZDCGeom.h
References PHOOL_VIRTUAL_WARN.
Referenced by RawTowerZDCGeomContainer::add_tower_geometry().
virtual double RawTowerZDCGeom::get_phi () const inline virtual
Reimplemented in RawTowerZDCGeomv1.
Definition at line 153 of file RawTowerZDCGeom.h.
View newest version in sPHENIX GitHub at line 153 of file RawTowerZDCGeom.h
References PHOOL_VIRTUAL_WARN.
virtual double RawTowerZDCGeom::get_roty () const inline virtual
Definition at line 170 of file RawTowerZDCGeom.h.
View newest version in sPHENIX GitHub at line 170 of file RawTowerZDCGeom.h
References PHOOL_VIRTUAL_WARN.
virtual double RawTowerZDCGeom::get_rotz () const inline virtual
Definition at line 175 of file RawTowerZDCGeom.h.
View newest version in sPHENIX GitHub at line 175 of file RawTowerZDCGeom.h
References PHOOL_VIRTUAL_WARN.
virtual int RawTowerZDCGeom::get_row () const inline virtual
Reimplemented in RawTowerZDCGeomv1.
Definition at line 51 of file RawTowerZDCGeom.h.
View newest version in sPHENIX GitHub at line 51 of file RawTowerZDCGeom.h
References PHOOL_VIRTUAL_WARN.
virtual double RawTowerZDCGeom::get_size_x () const inline virtual
Reimplemented in RawTowerZDCGeomv1.
Definition at line 111 of file RawTowerZDCGeom.h.
View newest version in sPHENIX GitHub at line 111 of file RawTowerZDCGeom.h
References PHOOL_VIRTUAL_WARN.
virtual double RawTowerZDCGeom::get_size_y () const inline virtual
Reimplemented in RawTowerZDCGeomv1.
Definition at line 117 of file RawTowerZDCGeom.h.
View newest version in sPHENIX GitHub at line 117 of file RawTowerZDCGeom.h
References PHOOL_VIRTUAL_WARN.
virtual double RawTowerZDCGeom::get_size_z () const inline virtual
Reimplemented in RawTowerZDCGeomv1.
Definition at line 123 of file RawTowerZDCGeom.h.
View newest version in sPHENIX GitHub at line 123 of file RawTowerZDCGeom.h
References PHOOL_VIRTUAL_WARN.
virtual double RawTowerZDCGeom::get_theta () const inline virtual
Reimplemented in RawTowerZDCGeomv1.
Definition at line 147 of file RawTowerZDCGeom.h.
View newest version in sPHENIX GitHub at line 147 of file RawTowerZDCGeom.h
References PHOOL_VIRTUAL_WARN.
virtual int RawTowerZDCGeom::get_tower_type () const inline virtual
Reimplemented in RawTowerZDCGeomv1.
Definition at line 164 of file RawTowerZDCGeom.h.
View newest version in sPHENIX GitHub at line 164 of file RawTowerZDCGeom.h
References PHOOL_VIRTUAL_WARN.
Referenced by RawTowerZDCCalibration::process_event().
virtual double RawTowerZDCGeom::get_volume () const inline virtual
Reimplemented in RawTowerZDCGeomv1.
Definition at line 129 of file RawTowerZDCGeom.h.
View newest version in sPHENIX GitHub at line 129 of file RawTowerZDCGeom.h
References PHOOL_VIRTUAL_WARN.
void RawTowerZDCGeom::identify (std::ostream & os = std::cout) const override virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from PHObject.
Reimplemented in RawTowerZDCGeomv1.
Definition at line 5 of file RawTowerZDCGeom.cc.
View newest version in sPHENIX GitHub at line 5 of file RawTowerZDCGeom.cc
Referenced by RawTowerZDCGeomContainer::add_tower_geometry().
virtual void RawTowerZDCGeom::set_center_x (double) inline virtual
Reimplemented in RawTowerZDCGeomv1.
Definition at line 57 of file RawTowerZDCGeom.h.
View newest version in sPHENIX GitHub at line 57 of file RawTowerZDCGeom.h
References PHOOL_VIRTUAL_WARN.
virtual void RawTowerZDCGeom::set_center_y (double) inline virtual
Reimplemented in RawTowerZDCGeomv1.
Definition at line 63 of file RawTowerZDCGeom.h.
View newest version in sPHENIX GitHub at line 63 of file RawTowerZDCGeom.h
References PHOOL_VIRTUAL_WARN.
virtual void RawTowerZDCGeom::set_center_z (double) inline virtual
Reimplemented in RawTowerZDCGeomv1.
Definition at line 69 of file RawTowerZDCGeom.h.
View newest version in sPHENIX GitHub at line 69 of file RawTowerZDCGeom.h
References PHOOL_VIRTUAL_WARN.
virtual void RawTowerZDCGeom::set_id (RawTowerZDCDefs::keytype) inline virtual
Reimplemented in RawTowerZDCGeomv1.
Definition at line 19 of file RawTowerZDCGeom.h.
View newest version in sPHENIX GitHub at line 19 of file RawTowerZDCGeom.h
References PHOOL_VIRTUAL_WARN.
virtual void RawTowerZDCGeom::set_roty (double) inline virtual
Definition at line 181 of file RawTowerZDCGeom.h.
View newest version in sPHENIX GitHub at line 181 of file RawTowerZDCGeom.h
References PHOOL_VIRTUAL_WARN.
virtual void RawTowerZDCGeom::set_rotz (double) inline virtual
Definition at line 186 of file RawTowerZDCGeom.h.
View newest version in sPHENIX GitHub at line 186 of file RawTowerZDCGeom.h
References PHOOL_VIRTUAL_WARN.
virtual void RawTowerZDCGeom::set_size_x (double) inline virtual
Reimplemented in RawTowerZDCGeomv1.
Definition at line 75 of file RawTowerZDCGeom.h.
View newest version in sPHENIX GitHub at line 75 of file RawTowerZDCGeom.h
References PHOOL_VIRTUAL_WARN.
virtual void RawTowerZDCGeom::set_size_y (double) inline virtual
Reimplemented in RawTowerZDCGeomv1.
Definition at line 81 of file RawTowerZDCGeom.h.
View newest version in sPHENIX GitHub at line 81 of file RawTowerZDCGeom.h
References PHOOL_VIRTUAL_WARN.
virtual void RawTowerZDCGeom::set_size_z (double) inline virtual
Reimplemented in RawTowerZDCGeomv1.
Definition at line 87 of file RawTowerZDCGeom.h.
View newest version in sPHENIX GitHub at line 87 of file RawTowerZDCGeom.h
References PHOOL_VIRTUAL_WARN.
virtual void RawTowerZDCGeom::set_tower_type (int) inline virtual
Reimplemented in RawTowerZDCGeomv1.
Definition at line 159 of file RawTowerZDCGeom.h.
View newest version in sPHENIX GitHub at line 159 of file RawTowerZDCGeom.h
References PHOOL_VIRTUAL_WARN.
The documentation for this class was generated from the following files:
fun4all_eicdetectors/blob/master/reconstruction/eiczdcbase/RawTowerZDCGeom.h
fun4all_eicdetectors/blob/master/reconstruction/eiczdcbase/RawTowerZDCGeom.cc