EIC Software: CbmRichEventDisplay Class Reference
CbmRichEventDisplay Class Reference
Event display for the RICH detector.
#include <EicRoot/blob/master/rich/CbmRichEventDisplay.h>
Public Member Functions
CbmRichEventDisplay ()
Default constructor.
virtual ~CbmRichEventDisplay ()
Destructor.
virtual InitStatus Init ()
Inherited from FairTask.
virtual void Exec (Option_t *opt)
Inherited from FairTask.
virtual void Finish ()
Inherited from FairTask.
void SetDrawRings (bool b)
void SetDrawHits (bool b)
void SetDrawPoints (bool b)
void SetDrawProjections (bool b)
Public Member Functions inherited from FairTask
FairTask ()
FairTask (const char *name, Int_t iVerbose=1)
virtual ~FairTask ()
void InitTask ()
void ReInitTask ()
void SetParTask ()
virtual void FinishTask ()
virtual void FinishEvent ()
void SetVerbose (Int_t iVerbose)
void SetInputPersistance (Bool_t val)
void CheckInputPersistance (TString branchName)
Private Member Functions
void DrawOneEvent ()
void DrawOnePmtPlane (const std::string &plane)
void DrawCircle (CbmRichRing *ring)
CbmRichEventDisplay (const CbmRichEventDisplay &)
Copy constructor.
CbmRichEventDisplay & operator= (const CbmRichEventDisplay &)
Assignment operator.
ClassDef (CbmRichEventDisplay, 1)
Private Attributes
TClonesArray * fRichRings
TClonesArray * fRichHits
TClonesArray * fRichPoints
TClonesArray * fRichMatches
TClonesArray * fRichProjections
TClonesArray * fMcTracks
int fEventNum
bool fDrawRings
bool fDrawHits
bool fDrawPoints
bool fDrawProjections
Additional Inherited Members
Protected Member Functions inherited from FairTask
virtual InitStatus ReInit ()
virtual void SetParContainers ()
void InitTasks ()
void ReInitTasks ()
void SetParTasks ()
void FinishTasks ()
void FinishEvents ()
Protected Attributes inherited from FairTask
Int_t fVerbose
Int_t fInputPersistance
Indicates if input branch is persistant.
FairLogger * fLogger
Detailed Description
Event display for the RICH detector.
Author
Semen Lebedev
Date
2012
Definition at line 29 of file CbmRichEventDisplay.h.
View newest version in sPHENIX GitHub at line 29 of file CbmRichEventDisplay.h
Constructor & Destructor Documentation
CbmRichEventDisplay::CbmRichEventDisplay ()
Default constructor.
Definition at line 35 of file CbmRichEventDisplay.cxx.
View newest version in sPHENIX GitHub at line 35 of file CbmRichEventDisplay.cxx
References SetDefaultDrawStyle().
CbmRichEventDisplay::~CbmRichEventDisplay () virtual
Destructor.
Definition at line 52 of file CbmRichEventDisplay.cxx.
View newest version in sPHENIX GitHub at line 52 of file CbmRichEventDisplay.cxx
CbmRichEventDisplay::CbmRichEventDisplay (const CbmRichEventDisplay &) private
Copy constructor.
Member Function Documentation
CbmRichEventDisplay::ClassDef (CbmRichEventDisplay , 1) private
void CbmRichEventDisplay::DrawCircle (CbmRichRing * ring) private
Definition at line 180 of file CbmRichEventDisplay.cxx.
View newest version in sPHENIX GitHub at line 180 of file CbmRichEventDisplay.cxx
References CbmRichRing::GetCenterX(), CbmRichRing::GetCenterY(), and CbmRichRing::GetRadius().
Referenced by DrawOnePmtPlane().
void CbmRichEventDisplay::DrawOneEvent () private
Definition at line 91 of file CbmRichEventDisplay.cxx.
View newest version in sPHENIX GitHub at line 91 of file CbmRichEventDisplay.cxx
References c, DrawH2(), DrawOnePmtPlane(), and fEventNum.
Referenced by Exec().
void CbmRichEventDisplay::DrawOnePmtPlane (const std::string & plane) private
Definition at line 114 of file CbmRichEventDisplay.cxx.
View newest version in sPHENIX GitHub at line 114 of file CbmRichEventDisplay.cxx
References DrawCircle(), fDrawHits, fDrawPoints, fDrawProjections, fDrawRings, fRichHits, fRichPoints, fRichProjections, fRichRings, CbmRichRing::GetCenterY(), FairMCPoint::GetX(), FairTrackParam::GetX(), CbmPixelHit::GetX(), FairMCPoint::GetY(), FairTrackParam::GetY(), CbmPixelHit::GetY(), and Acts::UnitConstants::m.
Referenced by DrawOneEvent().
void CbmRichEventDisplay::Exec (Option_t * opt) virtual
Inherited from FairTask.
Definition at line 83 of file CbmRichEventDisplay.cxx.
View newest version in sPHENIX GitHub at line 83 of file CbmRichEventDisplay.cxx
References DrawOneEvent(), fEventNum, and SetDefaultDrawStyle().
void CbmRichEventDisplay::Finish (void) virtual
Inherited from FairTask.
Reimplemented from FairTask.
Definition at line 194 of file CbmRichEventDisplay.cxx.
View newest version in sPHENIX GitHub at line 194 of file CbmRichEventDisplay.cxx
InitStatus CbmRichEventDisplay::Init (void) virtual
Inherited from FairTask.
Reimplemented from FairTask.
Definition at line 57 of file CbmRichEventDisplay.cxx.
View newest version in sPHENIX GitHub at line 57 of file CbmRichEventDisplay.cxx
References fMcTracks, fRichHits, fRichMatches, fRichPoints, fRichProjections, fRichRings, FairRootManager::GetObject(), FairRootManager::Instance(), and kSUCCESS.
CbmRichEventDisplay& CbmRichEventDisplay::operator= (const CbmRichEventDisplay &) private
Assignment operator.
void CbmRichEventDisplay::SetDrawHits (bool b) inline
Definition at line 60 of file CbmRichEventDisplay.h.
View newest version in sPHENIX GitHub at line 60 of file CbmRichEventDisplay.h
References fDrawHits.
void CbmRichEventDisplay::SetDrawPoints (bool b) inline
Definition at line 61 of file CbmRichEventDisplay.h.
View newest version in sPHENIX GitHub at line 61 of file CbmRichEventDisplay.h
References fDrawPoints.
void CbmRichEventDisplay::SetDrawProjections (bool b) inline
Definition at line 62 of file CbmRichEventDisplay.h.
View newest version in sPHENIX GitHub at line 62 of file CbmRichEventDisplay.h
References fDrawProjections.
void CbmRichEventDisplay::SetDrawRings (bool b) inline
Definition at line 59 of file CbmRichEventDisplay.h.
View newest version in sPHENIX GitHub at line 59 of file CbmRichEventDisplay.h
References fDrawRings.
Member Data Documentation
bool CbmRichEventDisplay::fDrawHits private
Definition at line 77 of file CbmRichEventDisplay.h.
View newest version in sPHENIX GitHub at line 77 of file CbmRichEventDisplay.h
Referenced by DrawOnePmtPlane(), and SetDrawHits().
bool CbmRichEventDisplay::fDrawPoints private
Definition at line 78 of file CbmRichEventDisplay.h.
View newest version in sPHENIX GitHub at line 78 of file CbmRichEventDisplay.h
Referenced by DrawOnePmtPlane(), and SetDrawPoints().
bool CbmRichEventDisplay::fDrawProjections private
Definition at line 79 of file CbmRichEventDisplay.h.
View newest version in sPHENIX GitHub at line 79 of file CbmRichEventDisplay.h
Referenced by DrawOnePmtPlane(), and SetDrawProjections().
bool CbmRichEventDisplay::fDrawRings private
Definition at line 76 of file CbmRichEventDisplay.h.
View newest version in sPHENIX GitHub at line 76 of file CbmRichEventDisplay.h
Referenced by DrawOnePmtPlane(), and SetDrawRings().
int CbmRichEventDisplay::fEventNum private
Definition at line 74 of file CbmRichEventDisplay.h.
View newest version in sPHENIX GitHub at line 74 of file CbmRichEventDisplay.h
Referenced by DrawOneEvent(), and Exec().
TClonesArray* CbmRichEventDisplay::fMcTracks private
Definition at line 72 of file CbmRichEventDisplay.h.
View newest version in sPHENIX GitHub at line 72 of file CbmRichEventDisplay.h
Referenced by Init().
TClonesArray* CbmRichEventDisplay::fRichHits private
Definition at line 67 of file CbmRichEventDisplay.h.
View newest version in sPHENIX GitHub at line 67 of file CbmRichEventDisplay.h
Referenced by DrawOnePmtPlane(), and Init().
TClonesArray* CbmRichEventDisplay::fRichMatches private
Definition at line 69 of file CbmRichEventDisplay.h.
View newest version in sPHENIX GitHub at line 69 of file CbmRichEventDisplay.h
Referenced by Init().
TClonesArray* CbmRichEventDisplay::fRichPoints private
Definition at line 68 of file CbmRichEventDisplay.h.
View newest version in sPHENIX GitHub at line 68 of file CbmRichEventDisplay.h
Referenced by DrawOnePmtPlane(), and Init().
TClonesArray* CbmRichEventDisplay::fRichProjections private
Definition at line 70 of file CbmRichEventDisplay.h.
View newest version in sPHENIX GitHub at line 70 of file CbmRichEventDisplay.h
Referenced by DrawOnePmtPlane(), and Init().
TClonesArray* CbmRichEventDisplay::fRichRings private
Definition at line 66 of file CbmRichEventDisplay.h.
View newest version in sPHENIX GitHub at line 66 of file CbmRichEventDisplay.h
Referenced by DrawOnePmtPlane(), and Init().
The documentation for this class was generated from the following files:
EicRoot/blob/master/rich/CbmRichEventDisplay.h
EicRoot/blob/master/rich/CbmRichEventDisplay.cxx