EIC Software: CbmRichElectronIdAnn Class Reference
CbmRichElectronIdAnn Class Reference
Implementation of the electron identification algorithm in the RICH detector using Artificial Neural Network(ANN).
#include <EicRoot/blob/master/rich/CbmRichElectronIdAnn.h>
Public Member Functions
CbmRichElectronIdAnn ()
Standard constructor.
virtual ~CbmRichElectronIdAnn ()
Destructor.
void Init ()
Initialize ANN before use.
double DoSelect (CbmRichRing *ring, double momentum)
Calculate output value of the ANN.
void SetAnnWeights (const string &fileName)
Set path to the file with ANN weights.
Private Member Functions
CbmRichElectronIdAnn (const CbmRichElectronIdAnn &)
Copy constructor.
CbmRichElectronIdAnn & operator= (const CbmRichElectronIdAnn &)
Assignment operator.
Private Attributes
string fAnnWeights
TMultiLayerPerceptron * fNN
Detailed Description
Implementation of the electron identification algorithm in the RICH detector using Artificial Neural Network(ANN).
Author
Semen Lebedev
Date
2008
Definition at line 30 of file CbmRichElectronIdAnn.h.
View newest version in sPHENIX GitHub at line 30 of file CbmRichElectronIdAnn.h
Constructor & Destructor Documentation
CbmRichElectronIdAnn::CbmRichElectronIdAnn ()
Standard constructor.
Definition at line 20 of file CbmRichElectronIdAnn.cxx.
View newest version in sPHENIX GitHub at line 20 of file CbmRichElectronIdAnn.cxx
References fAnnWeights.
CbmRichElectronIdAnn::~CbmRichElectronIdAnn () virtual
Destructor.
Definition at line 27 of file CbmRichElectronIdAnn.cxx.
View newest version in sPHENIX GitHub at line 27 of file CbmRichElectronIdAnn.cxx
CbmRichElectronIdAnn::CbmRichElectronIdAnn (const CbmRichElectronIdAnn &) private
Copy constructor.
Member Function Documentation
double CbmRichElectronIdAnn::DoSelect (CbmRichRing * ring, double momentum)
Calculate output value of the ANN.
Parameters
[in] ring Found and fitted ring.
[in] momentum Momentum of the track attached to this ring.
Returns
ANN output value.
Definition at line 54 of file CbmRichElectronIdAnn.cxx.
View newest version in sPHENIX GitHub at line 54 of file CbmRichElectronIdAnn.cxx
References fNN, CbmRichRing::GetAaxis(), CbmRichRing::GetBaxis(), CbmRichRing::GetChi2(), CbmRichRing::GetDistance(), CbmRichRing::GetNDF(), CbmRichRing::GetNofHits(), CbmRichRing::GetPhi(), CbmRichRing::GetRadialAngle(), CbmRichRing::GetRadialPosition(), and k.
void CbmRichElectronIdAnn::Init (void)
Initialize ANN before use.
Definition at line 32 of file CbmRichElectronIdAnn.cxx.
View newest version in sPHENIX GitHub at line 32 of file CbmRichElectronIdAnn.cxx
References fAnnWeights, fNN, and x.
CbmRichElectronIdAnn& CbmRichElectronIdAnn::operator= (const CbmRichElectronIdAnn &) private
Assignment operator.
void CbmRichElectronIdAnn::SetAnnWeights (const string & fileName) inline
Set path to the file with ANN weights.
Parameters
[in] fileName path to the file with ANN weights.
Definition at line 66 of file CbmRichElectronIdAnn.h.
View newest version in sPHENIX GitHub at line 66 of file CbmRichElectronIdAnn.h
References fAnnWeights.
Member Data Documentation
string CbmRichElectronIdAnn::fAnnWeights private
Definition at line 33 of file CbmRichElectronIdAnn.h.
View newest version in sPHENIX GitHub at line 33 of file CbmRichElectronIdAnn.h
Referenced by CbmRichElectronIdAnn(), Init(), and SetAnnWeights().
TMultiLayerPerceptron* CbmRichElectronIdAnn::fNN private
Definition at line 34 of file CbmRichElectronIdAnn.h.
View newest version in sPHENIX GitHub at line 34 of file CbmRichElectronIdAnn.h
Referenced by DoSelect(), and Init().
The documentation for this class was generated from the following files:
EicRoot/blob/master/rich/CbmRichElectronIdAnn.h
EicRoot/blob/master/rich/CbmRichElectronIdAnn.cxx