EIC Software: Gammaanarrowvm Class Reference
Gammaanarrowvm Class Reference
#include <estarlight/blob/master/include/gammaavm.h>
Public Member Functions
Gammaanarrowvm (const inputParameters &input, beamBeamSystem &bbsystem)
virtual ~Gammaanarrowvm ()
Public Member Functions inherited from Gammaavectormeson
Gammaavectormeson (const inputParameters &ipnut, beamBeamSystem &bbsystem)
virtual ~Gammaavectormeson ()
eXEvent e_produceEvent ()
void pickwy (double &W, double &Y)
void pickwEgamq2 (double &W, double &cmsEgamma, double &targetEgamma, double &Q2, double &gamma_pz, double &gamma_pt, double &E_prime, double &cos_theta_e)
void momenta (double W, double Y, double &E, double &px, double &py, double &pz, int &tcheck)
void momenta (double W, double Egam, double Q2, double gamma_pz, double gamma_pt, double &rapidity, double &E, double &px, double &py, double &pz, double &t_px, double &t_py, double &t_pz, double &t_E, double &e_phi, int &tcheck)
double pTgamma (double E)
void vmpt (double W, double Y, double &E, double &px, double &py, double &pz, int &tcheck)
void twoBodyDecay (starlightConstants::particleTypeEnum &ipid, double W, double px0, double py0, double pz0, double &px1, double &py1, double &pz1, double &px2, double &py2, double &pz2, int &iFbadevent)
void twoBodyDecay (starlightConstants::particleTypeEnum &ipid, double W, double px0, double py0, double pz0, double spin_element, double &px1, double &py1, double &pz1, double &px2, double &py2, double &pz2, int &iFbadevent)
bool fourBodyDecay (starlightConstants::particleTypeEnum &ipid, const double E, const double W, const double *p, lorentzVector *decayMoms, int &iFbadevent)
void pi0Decay (double &px_pi0, double &py_pi0, double &pz_pi0, double &e_g1, double &px_g1, double &py_g1, double &pz_g1, double &e_g2, double &px_g2, double &py_g2, double &pz_g2, int &iFbadevent)
double getMass ()
double getWidth ()
virtual double getTheta (starlightConstants::particleTypeEnum ipid, double r_04_00)
double getSpinMatrixElement (double W, double Q2, double epsilon)
double getSpin ()
virtual double getDaughterMass (starlightConstants::particleTypeEnum &ipid)
double pseudoRapidity (double px, double py, double pz)
Public Member Functions inherited from eventChannel
eventChannel (const inputParameters &input, beamBeamSystem &bbsystem)
virtual ~eventChannel ()
unsigned long nmbAttempts () const
returns number of attempted events
unsigned long nmbAccepted () const
returns number of accepted events
double getTotalChannelCrossSection () const
void setTotalChannelCrossSection (double sigma)
Public Member Functions inherited from readLuminosity
readLuminosity (const inputParameters &input)
~readLuminosity ()
void read ()
void e_read ()
Additional Inherited Members
Static Public Member Functions inherited from eventChannel
static void transform (const double betax, const double betay, const double betaz, double &E, double &px, double &py, double &pz, int &iFbadevent)
Lorentz-transforms given 4-vector.
static double pseudoRapidity (const double px, const double py, const double pz)
calculates pseudorapidity for given 3-momentum
Public Attributes inherited from Gammaavectormeson
double _VMbslope
Protected Attributes inherited from eventChannel
unsigned long _nmbAttempts
number of attempted events
unsigned long _nmbAccepted
number of accepted events
bool _ptCutEnabled
en/disables cut in pt
double _ptCutMin
minimum pt, if cut is enabled
double _ptCutMax
maximum pt, if cut is enabled
bool _etaCutEnabled
en/disables cut in eta
double _etaCutMin
minimum eta, if cut is enabled
double _etaCutMax
maximum eta, if cut is enabled
double _totalChannelCrossSection
Detailed Description
Definition at line 127 of file gammaavm.h.
View newest version in sPHENIX GitHub at line 127 of file gammaavm.h
Constructor & Destructor Documentation
Gammaanarrowvm::Gammaanarrowvm (const inputParameters & input, beamBeamSystem & bbsystem)
Definition at line 922 of file gammaavm.cpp.
View newest version in sPHENIX GitHub at line 922 of file gammaavm.cpp
References readLuminosity::_bwnormsave, Gammaavectormeson::_VMbslope, narrowResonanceCrossSection::crossSectionCalculation(), photonNucleusCrossSection::getPhotonNucleusSigma(), readLuminosity::read(), eventChannel::setTotalChannelCrossSection(), and photonNucleusCrossSection::slopeParameter().
Gammaanarrowvm::~Gammaanarrowvm () virtual
Definition at line 935 of file gammaavm.cpp.
View newest version in sPHENIX GitHub at line 935 of file gammaavm.cpp
The documentation for this class was generated from the following files:
estarlight/blob/master/include/gammaavm.h
estarlight/blob/master/src/gammaavm.cpp