EIC Software: PHSiliconTpcTrackMatching Class Reference
PHSiliconTpcTrackMatching Class Reference
#include <fun4all_coresoftware/blob/master/offline/packages/trackreco/PHSiliconTpcTrackMatching.h>
Public Member Functions
PHSiliconTpcTrackMatching (const std::string &name="PHSiliconTpcTrackMatching")
~PHSiliconTpcTrackMatching () override
void set_track_map_name_silicon (const std::string &map_name)
void set_phi_search_window (const double win)
void set_eta_search_window (const double win)
void set_x_search_window (const double win)
void set_y_search_window (const double win)
void set_z_search_window (const double win)
void set_search_par_values (const double p0, const double p1, const double p2)
void set_seeder (const bool is_ca_seeder)
void set_field_dir (const double rescale)
void set_field (const std::string &field)
void set_test_windows_printout (const bool test)
void set_sc_calib_mode (const bool flag)
void set_collision_rate (const double rate)
void set_pp_mode (const bool flag)
int InitRun (PHCompositeNode *topNode) override
int process_event (PHCompositeNode *) override
int End (PHCompositeNode *) override
Called at the end of all processing.
void set_silicon_track_map_name (const std::string &map_name)
void set_tpcseed_track_map_name (const std::string &map_name)
void set_track_map_name (const std::string &map_name)
void SetIteration (int iter)
Public Member Functions inherited from SubsysReco
~SubsysReco () override
virtual int EndRun (const int)
Called at the end of each run.
virtual int Init (PHCompositeNode *)
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
void Print (const std::string &="ALL") const override
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Private Member Functions
int GetNodes (PHCompositeNode *topNode)
double getBunchCrossing (unsigned int trid, double z_mismatch)
double getMedian (std::vector< double > &v)
void addSiliconClusters (std::multimap< int, std::pair< unsigned int, unsigned int >> &crossing_matches)
void addSiliconClusters (std::multimap< unsigned int, std::pair< unsigned int, unsigned int >> &vertex_map)
void addSiliconClusters (std::multimap< unsigned int, unsigned int > &tpc_matches)
void correctTpcClusterZ (std::map< unsigned int, double > &vertex_crossings_map, std::multimap< unsigned int, std::pair< unsigned int, unsigned int >> &vertex_map)
void getCrossingNumber (std::vector< double > &vertex_list, std::multimap< unsigned int, std::pair< unsigned int, unsigned int >> &vertex_map, std::map< unsigned int, double > &vertex_crossings_map)
void getSiVertexList (std::multimap< double, std::pair< unsigned int, unsigned int >> &si_sorted_map, std::vector< double > &vertex_list, std::multimap< unsigned int, std::pair< unsigned int, unsigned int >> &vertex_map)
void findEtaPhiMatches (std::set< unsigned int > &tpc_matched_set, std::multimap< unsigned int, unsigned int > &tpc_matches)
void tagInTimeTracks (std::multimap< unsigned int, unsigned int > &tpc_matches, std::set< int > &crossing_set, std::multimap< int, std::pair< unsigned int, unsigned int >> &crossing_matches, std::map< unsigned int, int > &tpc_crossing_map)
void tagMatchCrossing (std::multimap< unsigned int, unsigned int > &tpc_matches, std::set< int > &crossing_set, std::multimap< int, std::pair< unsigned int, unsigned int >> &crossing_matches, std::map< unsigned int, int > &tpc_crossing_map)
void cleanVertexMap (std::map< unsigned int, double > &vertex_crossings_map, std::multimap< unsigned int, std::pair< unsigned int, unsigned int >> &vertex_map, std::map< unsigned int, int > &tpc_crossing_map)
void copySiliconClustersToCorrectedMap ()
Private Attributes
std::string _track_map_name_silicon
double _phi_search_win = 0.01
double _eta_search_win = 0.004
double _x_search_win = 0.3
double _y_search_win = 0.3
double _z_search_win = 0.4
AssocInfoContainer * _assoc_container {nullptr}
SvtxTrackMap * _track_map {nullptr}
SvtxTrackMap * _track_map_silicon {nullptr}
SvtxTrack * _tracklet_tpc {nullptr}
SvtxTrack * _tracklet_si {nullptr}
TrkrClusterContainer * _cluster_map {nullptr}
TrkrClusterContainer * _corrected_cluster_map {nullptr}
ActsSurfaceMaps * _surfmaps {nullptr}
ActsTrackingGeometry * _tGeometry {nullptr}
TpcSeedTrackMap * _seed_track_map {nullptr}
std::map< unsigned int, double > _z_mismatch_map
TF1 * fdphi {nullptr}
double _par0 = -0.000650
double _par1 = 0.13373
double _par2 = 0.98298
TF1 * fscdphi {nullptr}
double _parsc0 = 0.0366293
double _parsc1 = -0.0133073
double _collision_rate = 50e3
double _reference_collision_rate = 50e3
double _si_vertex_dzmax = 0.25
bool _is_ca_seeder = true
bool _sc_calib_flag = false
bool _test_windows = false
bool _pp_mode = false
std::string _field
int _fieldDir = -1
int _n_iteration = 0
std::string _track_map_name = "SvtxTrackMap"
std::string _tpcseed_track_map_name = "TpcSeedTrackMap"
std::string _silicon_track_map_name = "SvtxSiliconTrackMap"
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = INT_MAX - 10
}
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Detailed Description
Definition at line 21 of file PHSiliconTpcTrackMatching.h.
View newest version in sPHENIX GitHub at line 21 of file PHSiliconTpcTrackMatching.h
Constructor & Destructor Documentation
PHSiliconTpcTrackMatching::PHSiliconTpcTrackMatching (const std::string & name = "PHSiliconTpcTrackMatching")
Definition at line 43 of file PHSiliconTpcTrackMatching.cc.
View newest version in sPHENIX GitHub at line 43 of file PHSiliconTpcTrackMatching.cc
PHSiliconTpcTrackMatching::~PHSiliconTpcTrackMatching () override
Definition at line 51 of file PHSiliconTpcTrackMatching.cc.
View newest version in sPHENIX GitHub at line 51 of file PHSiliconTpcTrackMatching.cc
Member Function Documentation
void PHSiliconTpcTrackMatching::addSiliconClusters (std::multimap< int, std::pair< unsigned int, unsigned int >> & crossing_matches) private
Definition at line 431 of file PHSiliconTpcTrackMatching.cc.
View newest version in sPHENIX GitHub at line 431 of file PHSiliconTpcTrackMatching.cc
References _assoc_container, _track_map, _track_map_silicon, SvtxTrack::begin_cluster_keys(), SvtxTrack::end_cluster_keys(), SvtxTrackMap::get(), SvtxTrack::get_id(), SvtxTrack::get_x(), SvtxTrack::get_y(), SvtxTrack::get_z(), SvtxTrack::identify(), SvtxTrack::insert_cluster_key(), it, SvtxTrack::set_x(), SvtxTrack::set_y(), SvtxTrack::set_z(), AssocInfoContainer::SetClusterTrackAssoc(), SvtxTrack::size_cluster_keys(), and Fun4AllBase::Verbosity().
Referenced by process_event().
void PHSiliconTpcTrackMatching::addSiliconClusters (std::multimap< unsigned int, std::pair< unsigned int, unsigned int >> & vertex_map) private
Definition at line 474 of file PHSiliconTpcTrackMatching.cc.
View newest version in sPHENIX GitHub at line 474 of file PHSiliconTpcTrackMatching.cc
References _assoc_container, _track_map, _track_map_silicon, SvtxTrack::begin_cluster_keys(), SvtxTrack::end_cluster_keys(), SvtxTrackMap::get(), SvtxTrack::get_id(), SvtxTrack::get_x(), SvtxTrack::get_y(), SvtxTrack::get_z(), SvtxTrack::identify(), SvtxTrack::insert_cluster_key(), it, SvtxTrack::set_x(), SvtxTrack::set_y(), SvtxTrack::set_z(), AssocInfoContainer::SetClusterTrackAssoc(), SvtxTrack::size_cluster_keys(), and Fun4AllBase::Verbosity().
void PHSiliconTpcTrackMatching::addSiliconClusters (std::multimap< unsigned int, unsigned int > & tpc_matches) private
Definition at line 386 of file PHSiliconTpcTrackMatching.cc.
View newest version in sPHENIX GitHub at line 386 of file PHSiliconTpcTrackMatching.cc
References _assoc_container, _track_map, _track_map_silicon, SvtxTrack::begin_cluster_keys(), SvtxTrack::end_cluster_keys(), SvtxTrackMap::get(), SvtxTrack::get_id(), SvtxTrack::get_x(), SvtxTrack::get_y(), SvtxTrack::get_z(), SvtxTrack::identify(), SvtxTrack::insert_cluster_key(), it, SvtxTrack::set_x(), SvtxTrack::set_y(), SvtxTrack::set_z(), AssocInfoContainer::SetClusterTrackAssoc(), SvtxTrack::size_cluster_keys(), and Fun4AllBase::Verbosity().
void PHSiliconTpcTrackMatching::cleanVertexMap (std::map< unsigned int, double > & vertex_crossings_map, std::multimap< unsigned int, std::pair< unsigned int, unsigned int >> & vertex_map, std::map< unsigned int, int > & tpc_crossing_map) private
Definition at line 606 of file PHSiliconTpcTrackMatching.cc.
View newest version in sPHENIX GitHub at line 606 of file PHSiliconTpcTrackMatching.cc
References kdfinder::abs(), it, and Fun4AllBase::Verbosity().
Referenced by process_event().
void PHSiliconTpcTrackMatching::copySiliconClustersToCorrectedMap () private
Definition at line 1110 of file PHSiliconTpcTrackMatching.cc.
View newest version in sPHENIX GitHub at line 1110 of file PHSiliconTpcTrackMatching.cc
References _cluster_map, _corrected_cluster_map, _track_map, SvtxTrackMap::begin(), SvtxTrack::begin_cluster_keys(), TrkrCluster::CopyFrom(), SvtxTrackMap::end(), SvtxTrack::end_cluster_keys(), TrkrClusterContainer::findCluster(), TrkrClusterContainer::findOrAddCluster(), TrkrDefs::getTrkrId(), TrkrDefs::inttId, and TrkrDefs::mvtxId.
Referenced by process_event().
void PHSiliconTpcTrackMatching::correctTpcClusterZ (std::map< unsigned int, double > & vertex_crossings_map, std::multimap< unsigned int, std::pair< unsigned int, unsigned int >> & vertex_map) private
Definition at line 519 of file PHSiliconTpcTrackMatching.cc.
View newest version in sPHENIX GitHub at line 519 of file PHSiliconTpcTrackMatching.cc
References _cluster_map, _corrected_cluster_map, _surfmaps, _tGeometry, _track_map, SvtxTrack::begin_cluster_keys(), Acts::UnitConstants::cm, SvtxTrack::end_cluster_keys(), TrkrClusterContainer::findCluster(), ActsTrackingGeometry::geoContext, SvtxTrackMap::get(), SvtxTrack::get_z(), ActsTransformations::getGlobalPosition(), TrkrCluster::getLocalY(), ActsTransformations::getSurface(), TrkrDefs::getTrkrId(), it, TrkrCluster::setLocalY(), surface(), TrkrDefs::tpcId, and Fun4AllBase::Verbosity().
Referenced by process_event().
int PHSiliconTpcTrackMatching::End (PHCompositeNode *) override virtual
Called at the end of all processing.
Reimplemented from SubsysReco.
Definition at line 205 of file PHSiliconTpcTrackMatching.cc.
View newest version in sPHENIX GitHub at line 205 of file PHSiliconTpcTrackMatching.cc
References Fun4AllReturnCodes::EVENT_OK.
void PHSiliconTpcTrackMatching::findEtaPhiMatches (std::set< unsigned int > & tpc_matched_set, std::multimap< unsigned int, unsigned int > & tpc_matches) private
Correct the correction for the field direction Kludge to get the phi matching correct based on the field direction
Definition at line 768 of file PHSiliconTpcTrackMatching.cc.
View newest version in sPHENIX GitHub at line 768 of file PHSiliconTpcTrackMatching.cc
References _assoc_container, _eta_search_win, _field, _fieldDir, _is_ca_seeder, _phi_search_win, _pp_mode, _sc_calib_flag, _seed_track_map, _test_windows, _track_map, _track_map_silicon, _tracklet_si, _tracklet_tpc, _x_search_win, _y_search_win, _z_search_win, TpcSeedTrackMap::addAssoc(), SvtxTrackMap::begin(), SvtxTrackMap::empty(), SvtxTrackMap::end(), fdphi, fscdphi, SvtxTrackMap::get(), SvtxTrack::get_charge(), SvtxTrack::get_eta(), SvtxTrack::get_id(), SvtxTrack::get_phi(), SvtxTrack::get_pt(), SvtxTrack::get_px(), SvtxTrack::get_py(), SvtxTrack::get_x(), SvtxTrack::get_y(), SvtxTrack::get_z(), TrkrDefs::getTrkrId(), SvtxTrack::identify(), SvtxTrackMap::insert(), it, M_PI, AssocInfoContainer::SetClusterTrackAssoc(), SvtxTrackMap::size(), SvtxTrack::size_cluster_keys(), TrkrDefs::tpcId, and Fun4AllBase::Verbosity().
Referenced by process_event().
double PHSiliconTpcTrackMatching::getBunchCrossing (unsigned int trid, double z_mismatch) private
Definition at line 299 of file PHSiliconTpcTrackMatching.cc.
View newest version in sPHENIX GitHub at line 299 of file PHSiliconTpcTrackMatching.cc
References _cluster_map, _corrected_cluster_map, _surfmaps, _tGeometry, _track_map, SvtxTrack::begin_cluster_keys(), SvtxTrack::end_cluster_keys(), TrkrClusterContainer::findCluster(), SvtxTrackMap::get(), ActsTransformations::getGlobalPosition(), TrkrDefs::getTrkrId(), TrkrDefs::tpcId, and Fun4AllBase::Verbosity().
Referenced by getCrossingNumber(), and tagMatchCrossing().
void PHSiliconTpcTrackMatching::getCrossingNumber (std::vector< double > & vertex_list, std::multimap< unsigned int, std::pair< unsigned int, unsigned int >> & vertex_map, std::map< unsigned int, double > & vertex_crossings_map) private
Definition at line 671 of file PHSiliconTpcTrackMatching.cc.
View newest version in sPHENIX GitHub at line 671 of file PHSiliconTpcTrackMatching.cc
References _track_map, Acts::VectorHelpers::cross(), SvtxTrackMap::get(), SvtxTrack::get_eta(), SvtxTrack::get_pt(), SvtxTrack::get_z(), getBunchCrossing(), getMedian(), it, round(), and Fun4AllBase::Verbosity().
Referenced by process_event().
double PHSiliconTpcTrackMatching::getMedian (std::vector< double > & v) private
Definition at line 350 of file PHSiliconTpcTrackMatching.cc.
View newest version in sPHENIX GitHub at line 350 of file PHSiliconTpcTrackMatching.cc
References Acts::UnitConstants::m, Acts::UnitConstants::m2, and Fun4AllBase::Verbosity().
Referenced by getCrossingNumber().
int PHSiliconTpcTrackMatching::GetNodes (PHCompositeNode * topNode) private
Get the DST Node
Check that it is there
Get the tracking subnode
Check that it is there
Definition at line 210 of file PHSiliconTpcTrackMatching.cc.
View newest version in sPHENIX GitHub at line 210 of file PHSiliconTpcTrackMatching.cc
References _assoc_container, _cluster_map, _corrected_cluster_map, _seed_track_map, _silicon_track_map_name, _surfmaps, _tGeometry, _tpcseed_track_map_name, _track_map, _track_map_name, _track_map_silicon, Fun4AllReturnCodes::ABORTEVENT, PHCompositeNode::addNode(), Fun4AllReturnCodes::EVENT_OK, PHNodeIterator::findFirst(), and PHWHERE.
Referenced by InitRun().
void PHSiliconTpcTrackMatching::getSiVertexList (std::multimap< double, std::pair< unsigned int, unsigned int >> & si_sorted_map, std::vector< double > & vertex_list, std::multimap< unsigned int, std::pair< unsigned int, unsigned int >> & vertex_map) private
Definition at line 723 of file PHSiliconTpcTrackMatching.cc.
View newest version in sPHENIX GitHub at line 723 of file PHSiliconTpcTrackMatching.cc
References _si_vertex_dzmax, it, and Fun4AllBase::Verbosity().
Referenced by process_event().
int PHSiliconTpcTrackMatching::InitRun (PHCompositeNode *) override virtual
Called for first event when run number is known. Typically this is where you may want to fetch data from database, because you know the run number.
Reimplemented from SubsysReco.
Definition at line 57 of file PHSiliconTpcTrackMatching.cc.
View newest version in sPHENIX GitHub at line 57 of file PHSiliconTpcTrackMatching.cc
References _collision_rate, _eta_search_win, _is_ca_seeder, _par0, _par1, _par2, _parsc0, _parsc1, _phi_search_win, _pp_mode, _reference_collision_rate, Fun4AllReturnCodes::EVENT_OK, fdphi, fscdphi, GetNodes(), and PHWHERE.
int PHSiliconTpcTrackMatching::process_event (PHCompositeNode *) override virtual
Called for each event. This is where you do the real work.
Reimplemented from SubsysReco.
Definition at line 88 of file PHSiliconTpcTrackMatching.cc.
View newest version in sPHENIX GitHub at line 88 of file PHSiliconTpcTrackMatching.cc
References _corrected_cluster_map, _pp_mode, _seed_track_map, _track_map, _track_map_silicon, _tracklet_si, _z_mismatch_map, addSiliconClusters(), SvtxTrackMap::begin(), cleanVertexMap(), copySiliconClustersToCorrectedMap(), correctTpcClusterZ(), SvtxTrackMap::end(), Fun4AllReturnCodes::EVENT_OK, findEtaPhiMatches(), SvtxTrackMap::get(), SvtxTrack::get_eta(), SvtxTrack::get_id(), SvtxTrack::get_pt(), SvtxTrack::get_px(), SvtxTrack::get_py(), SvtxTrack::get_z(), getCrossingNumber(), getSiVertexList(), it, PHWHERE, TpcSeedTrackMap::Reset(), TpcSeedTrackMap::size(), SvtxTrackMap::size(), tagMatchCrossing(), and Fun4AllBase::Verbosity().
void PHSiliconTpcTrackMatching::set_collision_rate (const double rate) inline
Definition at line 48 of file PHSiliconTpcTrackMatching.h.
View newest version in sPHENIX GitHub at line 48 of file PHSiliconTpcTrackMatching.h
References _collision_rate.
Referenced by Tracking_Reco().
void PHSiliconTpcTrackMatching::set_eta_search_window (const double win) inline
Definition at line 31 of file PHSiliconTpcTrackMatching.h.
View newest version in sPHENIX GitHub at line 31 of file PHSiliconTpcTrackMatching.h
References _eta_search_win.
Referenced by Tracking_Reco().
void PHSiliconTpcTrackMatching::set_field (const std::string & field) inline
Definition at line 44 of file PHSiliconTpcTrackMatching.h.
View newest version in sPHENIX GitHub at line 44 of file PHSiliconTpcTrackMatching.h
References _field.
Referenced by Tracking_Reco().
void PHSiliconTpcTrackMatching::set_field_dir (const double rescale) inline
Definition at line 38 of file PHSiliconTpcTrackMatching.h.
View newest version in sPHENIX GitHub at line 38 of file PHSiliconTpcTrackMatching.h
References _fieldDir.
Referenced by Tracking_Reco().
void PHSiliconTpcTrackMatching::set_phi_search_window (const double win) inline
Definition at line 30 of file PHSiliconTpcTrackMatching.h.
View newest version in sPHENIX GitHub at line 30 of file PHSiliconTpcTrackMatching.h
References _phi_search_win.
Referenced by Tracking_Reco().
void PHSiliconTpcTrackMatching::set_pp_mode (const bool flag) inline
Definition at line 49 of file PHSiliconTpcTrackMatching.h.
View newest version in sPHENIX GitHub at line 49 of file PHSiliconTpcTrackMatching.h
References _pp_mode.
void PHSiliconTpcTrackMatching::set_sc_calib_mode (const bool flag) inline
Definition at line 47 of file PHSiliconTpcTrackMatching.h.
View newest version in sPHENIX GitHub at line 47 of file PHSiliconTpcTrackMatching.h
References _sc_calib_flag.
Referenced by Tracking_Reco().
void PHSiliconTpcTrackMatching::set_search_par_values (const double p0, const double p1, const double p2) inline
Definition at line 35 of file PHSiliconTpcTrackMatching.h.
View newest version in sPHENIX GitHub at line 35 of file PHSiliconTpcTrackMatching.h
References _par0, _par1, and _par2.
void PHSiliconTpcTrackMatching::set_seeder (const bool is_ca_seeder) inline
Definition at line 36 of file PHSiliconTpcTrackMatching.h.
View newest version in sPHENIX GitHub at line 36 of file PHSiliconTpcTrackMatching.h
References _is_ca_seeder.
void PHSiliconTpcTrackMatching::set_silicon_track_map_name (const std::string & map_name) inline
Definition at line 57 of file PHSiliconTpcTrackMatching.h.
View newest version in sPHENIX GitHub at line 57 of file PHSiliconTpcTrackMatching.h
References _silicon_track_map_name.
void PHSiliconTpcTrackMatching::set_test_windows_printout (const bool test) inline
Definition at line 46 of file PHSiliconTpcTrackMatching.h.
View newest version in sPHENIX GitHub at line 46 of file PHSiliconTpcTrackMatching.h
References _test_windows.
Referenced by Tracking_Reco().
void PHSiliconTpcTrackMatching::set_tpcseed_track_map_name (const std::string & map_name) inline
Definition at line 58 of file PHSiliconTpcTrackMatching.h.
View newest version in sPHENIX GitHub at line 58 of file PHSiliconTpcTrackMatching.h
References _tpcseed_track_map_name.
void PHSiliconTpcTrackMatching::set_track_map_name (const std::string & map_name) inline
Definition at line 59 of file PHSiliconTpcTrackMatching.h.
View newest version in sPHENIX GitHub at line 59 of file PHSiliconTpcTrackMatching.h
References _track_map_name.
void PHSiliconTpcTrackMatching::set_track_map_name_silicon (const std::string & map_name) inline
Definition at line 29 of file PHSiliconTpcTrackMatching.h.
View newest version in sPHENIX GitHub at line 29 of file PHSiliconTpcTrackMatching.h
References _track_map_name_silicon.
void PHSiliconTpcTrackMatching::set_x_search_window (const double win) inline
Definition at line 32 of file PHSiliconTpcTrackMatching.h.
View newest version in sPHENIX GitHub at line 32 of file PHSiliconTpcTrackMatching.h
References _x_search_win.
void PHSiliconTpcTrackMatching::set_y_search_window (const double win) inline
Definition at line 33 of file PHSiliconTpcTrackMatching.h.
View newest version in sPHENIX GitHub at line 33 of file PHSiliconTpcTrackMatching.h
References _y_search_win.
void PHSiliconTpcTrackMatching::set_z_search_window (const double win) inline
Definition at line 34 of file PHSiliconTpcTrackMatching.h.
View newest version in sPHENIX GitHub at line 34 of file PHSiliconTpcTrackMatching.h
References _z_search_win.
void PHSiliconTpcTrackMatching::SetIteration (int iter) inline
Definition at line 60 of file PHSiliconTpcTrackMatching.h.
View newest version in sPHENIX GitHub at line 60 of file PHSiliconTpcTrackMatching.h
References _n_iteration.
void PHSiliconTpcTrackMatching::tagInTimeTracks (std::multimap< unsigned int, unsigned int > & tpc_matches, std::set< int > & crossing_set, std::multimap< int, std::pair< unsigned int, unsigned int >> & crossing_matches, std::map< unsigned int, int > & tpc_crossing_map) private
Definition at line 1030 of file PHSiliconTpcTrackMatching.cc.
View newest version in sPHENIX GitHub at line 1030 of file PHSiliconTpcTrackMatching.cc
References _track_map, _track_map_silicon, _z_search_win, SvtxTrackMap::get(), SvtxTrack::get_eta(), SvtxTrack::get_id(), SvtxTrack::get_pt(), SvtxTrack::get_z(), and Fun4AllBase::Verbosity().
void PHSiliconTpcTrackMatching::tagMatchCrossing (std::multimap< unsigned int, unsigned int > & tpc_matches, std::set< int > & crossing_set, std::multimap< int, std::pair< unsigned int, unsigned int >> & crossing_matches, std::map< unsigned int, int > & tpc_crossing_map) private
Definition at line 1075 of file PHSiliconTpcTrackMatching.cc.
View newest version in sPHENIX GitHub at line 1075 of file PHSiliconTpcTrackMatching.cc
References _track_map, _track_map_silicon, SvtxTrackMap::get(), SvtxTrack::get_eta(), SvtxTrack::get_id(), SvtxTrack::get_pt(), SvtxTrack::get_z(), getBunchCrossing(), and Fun4AllBase::Verbosity().
Referenced by process_event().
Member Data Documentation
AssocInfoContainer* PHSiliconTpcTrackMatching::_assoc_container {nullptr} private
Definition at line 103 of file PHSiliconTpcTrackMatching.h.
View newest version in sPHENIX GitHub at line 103 of file PHSiliconTpcTrackMatching.h
Referenced by addSiliconClusters(), findEtaPhiMatches(), and GetNodes().
TrkrClusterContainer* PHSiliconTpcTrackMatching::_cluster_map {nullptr} private
Definition at line 108 of file PHSiliconTpcTrackMatching.h.
View newest version in sPHENIX GitHub at line 108 of file PHSiliconTpcTrackMatching.h
Referenced by copySiliconClustersToCorrectedMap(), correctTpcClusterZ(), getBunchCrossing(), and GetNodes().
double PHSiliconTpcTrackMatching::_collision_rate = 50e3 private
Definition at line 130 of file PHSiliconTpcTrackMatching.h.
View newest version in sPHENIX GitHub at line 130 of file PHSiliconTpcTrackMatching.h
Referenced by InitRun(), and set_collision_rate().
TrkrClusterContainer* PHSiliconTpcTrackMatching::_corrected_cluster_map {nullptr} private
Definition at line 109 of file PHSiliconTpcTrackMatching.h.
View newest version in sPHENIX GitHub at line 109 of file PHSiliconTpcTrackMatching.h
Referenced by copySiliconClustersToCorrectedMap(), correctTpcClusterZ(), getBunchCrossing(), GetNodes(), and process_event().
double PHSiliconTpcTrackMatching::_eta_search_win = 0.004 private
Definition at line 98 of file PHSiliconTpcTrackMatching.h.
View newest version in sPHENIX GitHub at line 98 of file PHSiliconTpcTrackMatching.h
Referenced by findEtaPhiMatches(), InitRun(), and set_eta_search_window().
std::string PHSiliconTpcTrackMatching::_field private
Definition at line 139 of file PHSiliconTpcTrackMatching.h.
View newest version in sPHENIX GitHub at line 139 of file PHSiliconTpcTrackMatching.h
Referenced by findEtaPhiMatches(), and set_field().
int PHSiliconTpcTrackMatching::_fieldDir = -1 private
Definition at line 140 of file PHSiliconTpcTrackMatching.h.
View newest version in sPHENIX GitHub at line 140 of file PHSiliconTpcTrackMatching.h
Referenced by findEtaPhiMatches(), and set_field_dir().
bool PHSiliconTpcTrackMatching::_is_ca_seeder = true private
Definition at line 134 of file PHSiliconTpcTrackMatching.h.
View newest version in sPHENIX GitHub at line 134 of file PHSiliconTpcTrackMatching.h
Referenced by findEtaPhiMatches(), InitRun(), and set_seeder().
int PHSiliconTpcTrackMatching::_n_iteration = 0 private
Definition at line 142 of file PHSiliconTpcTrackMatching.h.
View newest version in sPHENIX GitHub at line 142 of file PHSiliconTpcTrackMatching.h
Referenced by SetIteration().
double PHSiliconTpcTrackMatching::_par0 = -0.000650 private
Definition at line 121 of file PHSiliconTpcTrackMatching.h.
View newest version in sPHENIX GitHub at line 121 of file PHSiliconTpcTrackMatching.h
Referenced by InitRun(), and set_search_par_values().
double PHSiliconTpcTrackMatching::_par1 = 0.13373 private
Definition at line 122 of file PHSiliconTpcTrackMatching.h.
View newest version in sPHENIX GitHub at line 122 of file PHSiliconTpcTrackMatching.h
Referenced by InitRun(), and set_search_par_values().
double PHSiliconTpcTrackMatching::_par2 = 0.98298 private
Definition at line 123 of file PHSiliconTpcTrackMatching.h.
View newest version in sPHENIX GitHub at line 123 of file PHSiliconTpcTrackMatching.h
Referenced by InitRun(), and set_search_par_values().
double PHSiliconTpcTrackMatching::_parsc0 = 0.0366293 private
Definition at line 127 of file PHSiliconTpcTrackMatching.h.
View newest version in sPHENIX GitHub at line 127 of file PHSiliconTpcTrackMatching.h
Referenced by InitRun().
double PHSiliconTpcTrackMatching::_parsc1 = -0.0133073 private
Definition at line 128 of file PHSiliconTpcTrackMatching.h.
View newest version in sPHENIX GitHub at line 128 of file PHSiliconTpcTrackMatching.h
Referenced by InitRun().
double PHSiliconTpcTrackMatching::_phi_search_win = 0.01 private
Definition at line 97 of file PHSiliconTpcTrackMatching.h.
View newest version in sPHENIX GitHub at line 97 of file PHSiliconTpcTrackMatching.h
Referenced by findEtaPhiMatches(), InitRun(), and set_phi_search_window().
bool PHSiliconTpcTrackMatching::_pp_mode = false private
Definition at line 137 of file PHSiliconTpcTrackMatching.h.
View newest version in sPHENIX GitHub at line 137 of file PHSiliconTpcTrackMatching.h
Referenced by findEtaPhiMatches(), InitRun(), process_event(), and set_pp_mode().
double PHSiliconTpcTrackMatching::_reference_collision_rate = 50e3 private
Definition at line 131 of file PHSiliconTpcTrackMatching.h.
View newest version in sPHENIX GitHub at line 131 of file PHSiliconTpcTrackMatching.h
Referenced by InitRun().
bool PHSiliconTpcTrackMatching::_sc_calib_flag = false private
Definition at line 135 of file PHSiliconTpcTrackMatching.h.
View newest version in sPHENIX GitHub at line 135 of file PHSiliconTpcTrackMatching.h
Referenced by findEtaPhiMatches(), and set_sc_calib_mode().
TpcSeedTrackMap* PHSiliconTpcTrackMatching::_seed_track_map {nullptr} private
Definition at line 114 of file PHSiliconTpcTrackMatching.h.
View newest version in sPHENIX GitHub at line 114 of file PHSiliconTpcTrackMatching.h
Referenced by findEtaPhiMatches(), GetNodes(), and process_event().
double PHSiliconTpcTrackMatching::_si_vertex_dzmax = 0.25 private
Definition at line 132 of file PHSiliconTpcTrackMatching.h.
View newest version in sPHENIX GitHub at line 132 of file PHSiliconTpcTrackMatching.h
Referenced by getSiVertexList().
std::string PHSiliconTpcTrackMatching::_silicon_track_map_name = "SvtxSiliconTrackMap" private
Definition at line 145 of file PHSiliconTpcTrackMatching.h.
View newest version in sPHENIX GitHub at line 145 of file PHSiliconTpcTrackMatching.h
Referenced by GetNodes(), and set_silicon_track_map_name().
ActsSurfaceMaps* PHSiliconTpcTrackMatching::_surfmaps {nullptr} private
Definition at line 110 of file PHSiliconTpcTrackMatching.h.
View newest version in sPHENIX GitHub at line 110 of file PHSiliconTpcTrackMatching.h
Referenced by correctTpcClusterZ(), getBunchCrossing(), and GetNodes().
bool PHSiliconTpcTrackMatching::_test_windows = false private
Definition at line 136 of file PHSiliconTpcTrackMatching.h.
View newest version in sPHENIX GitHub at line 136 of file PHSiliconTpcTrackMatching.h
Referenced by findEtaPhiMatches(), and set_test_windows_printout().
ActsTrackingGeometry* PHSiliconTpcTrackMatching::_tGeometry {nullptr} private
Definition at line 111 of file PHSiliconTpcTrackMatching.h.
View newest version in sPHENIX GitHub at line 111 of file PHSiliconTpcTrackMatching.h
Referenced by correctTpcClusterZ(), getBunchCrossing(), and GetNodes().
std::string PHSiliconTpcTrackMatching::_tpcseed_track_map_name = "TpcSeedTrackMap" private
Definition at line 144 of file PHSiliconTpcTrackMatching.h.
View newest version in sPHENIX GitHub at line 144 of file PHSiliconTpcTrackMatching.h
Referenced by GetNodes(), and set_tpcseed_track_map_name().
SvtxTrackMap* PHSiliconTpcTrackMatching::_track_map {nullptr} private
Definition at line 104 of file PHSiliconTpcTrackMatching.h.
View newest version in sPHENIX GitHub at line 104 of file PHSiliconTpcTrackMatching.h
Referenced by addSiliconClusters(), copySiliconClustersToCorrectedMap(), correctTpcClusterZ(), findEtaPhiMatches(), getBunchCrossing(), getCrossingNumber(), GetNodes(), process_event(), tagInTimeTracks(), and tagMatchCrossing().
std::string PHSiliconTpcTrackMatching::_track_map_name = "SvtxTrackMap" private
Definition at line 143 of file PHSiliconTpcTrackMatching.h.
View newest version in sPHENIX GitHub at line 143 of file PHSiliconTpcTrackMatching.h
Referenced by GetNodes(), and set_track_map_name().
std::string PHSiliconTpcTrackMatching::_track_map_name_silicon private
Definition at line 94 of file PHSiliconTpcTrackMatching.h.
View newest version in sPHENIX GitHub at line 94 of file PHSiliconTpcTrackMatching.h
Referenced by set_track_map_name_silicon().
SvtxTrackMap* PHSiliconTpcTrackMatching::_track_map_silicon {nullptr} private
Definition at line 105 of file PHSiliconTpcTrackMatching.h.
View newest version in sPHENIX GitHub at line 105 of file PHSiliconTpcTrackMatching.h
Referenced by addSiliconClusters(), findEtaPhiMatches(), GetNodes(), process_event(), tagInTimeTracks(), and tagMatchCrossing().
SvtxTrack* PHSiliconTpcTrackMatching::_tracklet_si {nullptr} private
Definition at line 107 of file PHSiliconTpcTrackMatching.h.
View newest version in sPHENIX GitHub at line 107 of file PHSiliconTpcTrackMatching.h
Referenced by findEtaPhiMatches(), and process_event().
SvtxTrack* PHSiliconTpcTrackMatching::_tracklet_tpc {nullptr} private
Definition at line 106 of file PHSiliconTpcTrackMatching.h.
View newest version in sPHENIX GitHub at line 106 of file PHSiliconTpcTrackMatching.h
Referenced by findEtaPhiMatches().
double PHSiliconTpcTrackMatching::_x_search_win = 0.3 private
Definition at line 99 of file PHSiliconTpcTrackMatching.h.
View newest version in sPHENIX GitHub at line 99 of file PHSiliconTpcTrackMatching.h
Referenced by findEtaPhiMatches(), and set_x_search_window().
double PHSiliconTpcTrackMatching::_y_search_win = 0.3 private
Definition at line 100 of file PHSiliconTpcTrackMatching.h.
View newest version in sPHENIX GitHub at line 100 of file PHSiliconTpcTrackMatching.h
Referenced by findEtaPhiMatches(), and set_y_search_window().
std::map<unsigned int, double> PHSiliconTpcTrackMatching::_z_mismatch_map private
Definition at line 116 of file PHSiliconTpcTrackMatching.h.
View newest version in sPHENIX GitHub at line 116 of file PHSiliconTpcTrackMatching.h
Referenced by process_event().
double PHSiliconTpcTrackMatching::_z_search_win = 0.4 private
Definition at line 101 of file PHSiliconTpcTrackMatching.h.
View newest version in sPHENIX GitHub at line 101 of file PHSiliconTpcTrackMatching.h
Referenced by findEtaPhiMatches(), set_z_search_window(), and tagInTimeTracks().
TF1* PHSiliconTpcTrackMatching::fdphi {nullptr} private
Definition at line 119 of file PHSiliconTpcTrackMatching.h.
View newest version in sPHENIX GitHub at line 119 of file PHSiliconTpcTrackMatching.h
Referenced by findEtaPhiMatches(), and InitRun().
TF1* PHSiliconTpcTrackMatching::fscdphi {nullptr} private
Definition at line 126 of file PHSiliconTpcTrackMatching.h.
View newest version in sPHENIX GitHub at line 126 of file PHSiliconTpcTrackMatching.h
Referenced by findEtaPhiMatches(), and InitRun().
The documentation for this class was generated from the following files:
fun4all_coresoftware/blob/master/offline/packages/trackreco/PHSiliconTpcTrackMatching.h
fun4all_coresoftware/blob/master/offline/packages/trackreco/PHSiliconTpcTrackMatching.cc