EIC Software: fun4all_acts/blob/master/Examples/Run/Common/src/MaterialMappingBase.cpp File Reference
MaterialMappingBase.cpp File Reference
#include <Acts/Geometry/GeometryContext.hpp>
#include <Acts/Geometry/TrackingGeometry.hpp>
#include <Acts/MagneticField/MagneticFieldContext.hpp>
#include <Acts/Material/SurfaceMaterialMapper.hpp>
#include <Acts/Plugins/Json/JsonGeometryConverter.hpp>
#include <Acts/Propagator/Navigator.hpp>
#include <Acts/Propagator/Propagator.hpp>
#include <Acts/Propagator/StraightLineStepper.hpp>
#include <boost/program_options.hpp>
#include <memory>
#include "ACTFW/Detector/IBaseDetector.hpp"
#include "ACTFW/Framework/Sequencer.hpp"
#include "ACTFW/Geometry/CommonGeometry.hpp"
#include "ACTFW/Io/Root/RootMaterialTrackReader.hpp"
#include "ACTFW/Io/Root/RootMaterialTrackWriter.hpp"
#include "ACTFW/Io/Root/RootMaterialWriter.hpp"
#include "ACTFW/MaterialMapping/MaterialMapping.hpp"
#include "ACTFW/MaterialMapping/MaterialMappingOptions.hpp"
#include "ACTFW/Options/CommonOptions.hpp"
#include "ACTFW/Plugins/Json/JsonMaterialWriter.hpp"
#include "ACTFW/Propagation/PropagationOptions.hpp"
#include "ACTFW/Utilities/Paths.hpp"
Functions
int materialMappingExample (int argc, char *argv[], FW::IBaseDetector &detector)
The material validation example, it runs a propagation and then writes out the material information.
Function Documentation
int materialMappingExample (int argc, char * argv[], FW::IBaseDetector & detector)
The material validation example, it runs a propagation and then writes out the material information.
Parameters
argc the number of argumetns of the call
atgv the argument list
detector the detector instance
Default contexts
The material mapper
The material mapping algorithm
The name of the output file
Definition at line 35 of file MaterialMappingBase.cpp.
View newest version in sPHENIX GitHub at line 35 of file MaterialMappingBase.cpp
References FW::Sequencer::addAlgorithm(), FW::Options::addGeometryOptions(), FW::Options::addInputOptions(), FW::Options::addMaterialMappingOptions(), FW::Options::addMaterialOptions(), FW::IBaseDetector::addOptions(), FW::Options::addOutputOptions(), FW::Options::addPropagationOptions(), FW::Sequencer::addReader(), FW::Options::addSequencerOptions(), FW::Sequencer::addWriter(), FW::Geometry::build(), FW::RootMaterialTrackReader::Config::collection, FW::RootMaterialTrackWriter::Config::collection, incremental_prev_tag::desc, FW::RootMaterialTrackReader::Config::fileList, FW::RootMaterialWriter::Config::fileName, FW::RootMaterialTrackWriter::Config::filePath, Acts::Test::geoContext, Acts::getDefaultLogger(), Acts::Logging::INFO, FW::Options::makeDefaultOptions(), mfContext, Acts::Test::navigator, FW::Options::parse(), FW::Options::readLogLevel(), FW::Options::readSequencerConfig(), FW::Sequencer::run(), propagation_timing::stepper, FW::RootMaterialTrackWriter::Config::storesurface, and Acts::Test::tGeometry.
Referenced by main().