EIC Software: RawTowerZDCCalibration Class Reference
RawTowerZDCCalibration Class Reference
#include <fun4all_eicdetectors/blob/master/reconstruction/eiczdcreco/RawTowerZDCCalibration.h>
Public Types
enum enu_calib_algorithm { kNo_calibration = 0, kSimple_linear_calibration = 1, kTower_by_tower_calibration = 2 }
Public Member Functions
RawTowerZDCCalibration (const std::string &name="RawTowerZDCCalibration")
~RawTowerZDCCalibration () override
int InitRun (PHCompositeNode *topNode) override
int process_event (PHCompositeNode *topNode) override
int End (PHCompositeNode *topNode) override
Called at the end of all processing.
void Detector (const std::string &d)
void TowerType (const int type)
enu_calib_algorithm get_calib_algorithm () const
void set_calib_algorithm (enu_calib_algorithm calibAlgorithm)
double get_calib_const_GeV_ADC () const
void set_calib_const_GeV_ADC (double calibConstGeVAdc)
void set_variable_GeV_ADC (const bool value)
std::string get_calib_tower_node_prefix () const
void set_calib_tower_node_prefix (const std::string &calibTowerNodePrefix)
double get_pedestal_ADC () const
void set_pedestal_ADC (double pedestalAdc)
void set_variable_pedestal (const bool value)
std::string get_raw_tower_node_prefix () const
void set_raw_tower_node_prefix (const std::string &rawTowerNodePrefix)
void set_zero_suppression_GeV (double)
PHParameters & GetCalibrationParameters ()
Get the parameters for update. Useful fields are listed in SetDefaultParameters();.
Public Member Functions inherited from SubsysReco
~SubsysReco () override
virtual int EndRun (const int)
Called at the end of each run.
virtual int Init (PHCompositeNode *)
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
void Print (const std::string &="ALL") const override
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Protected Member Functions
void CreateNodes (PHCompositeNode *topNode)
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Protected Member Functions inherited from Fun4AllBase
Fun4AllBase (const std::string &name="NONAME")
Protected Attributes
enu_calib_algorithm _calib_algorithm
RawTowerZDCContainer * _calib_towers
RawTowerZDCContainer * _raw_towers
RawTowerZDCGeomContainer * rawtowergeom
std::string detector
std::string RawTowerNodeName
std::string CaliTowerNodeName
std::string TowerGeomNodeName
std::string _calib_tower_node_prefix
std::string _raw_tower_node_prefix
double _pedestal_ADC
pedestal in unit of ADC
bool _pedestal_file
pedestal from file
double _calib_const_GeV_ADC
calibration constant in unit of GeV per ADC
bool _GeV_ADC_file
GeV per ADC from file.
int _tower_type
tower type to act on
PHParameters _tower_calib_params
Tower by tower calibration parameters.
Detailed Description
calibrate ADC value to measured energy deposition in calorimeter towers default input DST node is TOWER_RAW_DETECTOR default output DST node is TOWER_CALIB_DETECTOR
Definition at line 18 of file RawTowerZDCCalibration.h.
View newest version in sPHENIX GitHub at line 18 of file RawTowerZDCCalibration.h
Member Enumeration Documentation
enum RawTowerZDCCalibration::enu_calib_algorithm
Enumerator:
kNo_calibration
directly pass the energy of raw tower to calibrated tower. Zero suppression is applied
kSimple_linear_calibration
simple calibration with pedestal subtraction and a global energy scale (sampling fraction) correction
kTower_by_tower_calibration
input calibration file for tower by tower calibration. Use GetCalibrationParameters() to set the calibration parameters
Definition at line 41 of file RawTowerZDCCalibration.h.
View newest version in sPHENIX GitHub at line 41 of file RawTowerZDCCalibration.h
Constructor & Destructor Documentation
RawTowerZDCCalibration::RawTowerZDCCalibration (const std::string & name = "RawTowerZDCCalibration")
Definition at line 34 of file RawTowerZDCCalibration.cc.
View newest version in sPHENIX GitHub at line 34 of file RawTowerZDCCalibration.cc
RawTowerZDCCalibration::~RawTowerZDCCalibration () inline override
Definition at line 22 of file RawTowerZDCCalibration.h.
View newest version in sPHENIX GitHub at line 22 of file RawTowerZDCCalibration.h
Member Function Documentation
void RawTowerZDCCalibration::CreateNodes (PHCompositeNode * topNode) protected
Definition at line 191 of file RawTowerZDCCalibration.cc.
View newest version in sPHENIX GitHub at line 191 of file RawTowerZDCCalibration.cc
References _calib_tower_node_prefix, _calib_towers, _raw_tower_node_prefix, _raw_towers, CaliTowerNodeName, detector, PHNodeIterator::findFirst(), RawTowerZDCContainer::getCalorimeterID(), RawTowerZDCGeomContainer::identify(), Fun4AllBase::Name(), rawtowergeom, RawTowerNodeName, TowerGeomNodeName, and Fun4AllBase::Verbosity().
Referenced by InitRun().
void RawTowerZDCCalibration::Detector (const std::string & d) inline
Definition at line 30 of file RawTowerZDCCalibration.h.
View newest version in sPHENIX GitHub at line 30 of file RawTowerZDCCalibration.h
References _tower_calib_params, d, detector, and PHParameters::set_name().
int RawTowerZDCCalibration::End (PHCompositeNode *) override virtual
Called at the end of all processing.
Reimplemented from SubsysReco.
Definition at line 186 of file RawTowerZDCCalibration.cc.
View newest version in sPHENIX GitHub at line 186 of file RawTowerZDCCalibration.cc
References Fun4AllReturnCodes::EVENT_OK.
enu_calib_algorithm RawTowerZDCCalibration::get_calib_algorithm () const inline
Definition at line 54 of file RawTowerZDCCalibration.h.
View newest version in sPHENIX GitHub at line 54 of file RawTowerZDCCalibration.h
References _calib_algorithm.
double RawTowerZDCCalibration::get_calib_const_GeV_ADC () const inline
Definition at line 66 of file RawTowerZDCCalibration.h.
View newest version in sPHENIX GitHub at line 66 of file RawTowerZDCCalibration.h
References _calib_const_GeV_ADC.
std::string RawTowerZDCCalibration::get_calib_tower_node_prefix () const inline
Definition at line 84 of file RawTowerZDCCalibration.h.
View newest version in sPHENIX GitHub at line 84 of file RawTowerZDCCalibration.h
References _calib_tower_node_prefix.
double RawTowerZDCCalibration::get_pedestal_ADC () const inline
Definition at line 96 of file RawTowerZDCCalibration.h.
View newest version in sPHENIX GitHub at line 96 of file RawTowerZDCCalibration.h
References _pedestal_ADC.
std::string RawTowerZDCCalibration::get_raw_tower_node_prefix () const inline
Definition at line 114 of file RawTowerZDCCalibration.h.
View newest version in sPHENIX GitHub at line 114 of file RawTowerZDCCalibration.h
References _raw_tower_node_prefix.
PHParameters& RawTowerZDCCalibration::GetCalibrationParameters () inline
Get the parameters for update. Useful fields are listed in SetDefaultParameters();.
Definition at line 135 of file RawTowerZDCCalibration.h.
View newest version in sPHENIX GitHub at line 135 of file RawTowerZDCCalibration.h
References _tower_calib_params.
int RawTowerZDCCalibration::InitRun (PHCompositeNode *) override virtual
Called for first event when run number is known. Typically this is where you may want to fetch data from database, because you know the run number.
Reimplemented from SubsysReco.
Definition at line 64 of file RawTowerZDCCalibration.cc.
View newest version in sPHENIX GitHub at line 64 of file RawTowerZDCCalibration.cc
References Fun4AllReturnCodes::ABORTRUN, CreateNodes(), detector, Acts::UnitConstants::e, Fun4AllReturnCodes::EVENT_OK, exit(), PHNodeIterator::findFirst(), and Fun4AllBase::Name().
int RawTowerZDCCalibration::process_event (PHCompositeNode *) override virtual
Called for each event. This is where you do the real work.
Reimplemented from SubsysReco.
Definition at line 91 of file RawTowerZDCCalibration.cc.
View newest version in sPHENIX GitHub at line 91 of file RawTowerZDCCalibration.cc
References _calib_algorithm, _calib_const_GeV_ADC, _calib_towers, _GeV_ADC_file, _pedestal_ADC, _pedestal_file, _raw_towers, _tower_calib_params, _tower_type, Fun4AllReturnCodes::ABORTRUN, RawTowerZDCContainer::AddTower(), detector, Acts::VectorHelpers::eta(), Fun4AllReturnCodes::EVENT_OK, RawTowerZDC::get_bineta(), RawTowerZDC::get_binl(), RawTowerZDC::get_binphi(), PHParameters::get_double_param(), RawTowerZDC::get_energy(), RawTowerZDC::get_id(), RawTowerZDCGeomContainer::get_tower_geometry(), RawTowerZDCGeom::get_tower_type(), RawTowerZDCContainer::getTotalEdep(), RawTowerZDCContainer::getTowers(), kNo_calibration, kSimple_linear_calibration, kTower_by_tower_calibration, Fun4AllBase::Name(), phi, rawtowergeom, RawTowerZDC::set_energy(), nlohmann::to_string(), and Fun4AllBase::Verbosity().
void RawTowerZDCCalibration::set_calib_algorithm (enu_calib_algorithm calibAlgorithm) inline
Definition at line 60 of file RawTowerZDCCalibration.h.
View newest version in sPHENIX GitHub at line 60 of file RawTowerZDCCalibration.h
References _calib_algorithm.
void RawTowerZDCCalibration::set_calib_const_GeV_ADC (double calibConstGeVAdc) inline
Definition at line 72 of file RawTowerZDCCalibration.h.
View newest version in sPHENIX GitHub at line 72 of file RawTowerZDCCalibration.h
References _calib_const_GeV_ADC.
void RawTowerZDCCalibration::set_calib_tower_node_prefix (const std::string & calibTowerNodePrefix) inline
Definition at line 90 of file RawTowerZDCCalibration.h.
View newest version in sPHENIX GitHub at line 90 of file RawTowerZDCCalibration.h
References _calib_tower_node_prefix.
void RawTowerZDCCalibration::set_pedestal_ADC (double pedestalAdc) inline
Definition at line 102 of file RawTowerZDCCalibration.h.
View newest version in sPHENIX GitHub at line 102 of file RawTowerZDCCalibration.h
References _pedestal_ADC.
void RawTowerZDCCalibration::set_raw_tower_node_prefix (const std::string & rawTowerNodePrefix) inline
Definition at line 120 of file RawTowerZDCCalibration.h.
View newest version in sPHENIX GitHub at line 120 of file RawTowerZDCCalibration.h
References _raw_tower_node_prefix.
void RawTowerZDCCalibration::set_variable_GeV_ADC (const bool value) inline
Definition at line 78 of file RawTowerZDCCalibration.h.
View newest version in sPHENIX GitHub at line 78 of file RawTowerZDCCalibration.h
References _GeV_ADC_file, and value.
void RawTowerZDCCalibration::set_variable_pedestal (const bool value) inline
Definition at line 108 of file RawTowerZDCCalibration.h.
View newest version in sPHENIX GitHub at line 108 of file RawTowerZDCCalibration.h
References _pedestal_file, and value.
void RawTowerZDCCalibration::set_zero_suppression_GeV (double) inline
Definition at line 126 of file RawTowerZDCCalibration.h.
View newest version in sPHENIX GitHub at line 126 of file RawTowerZDCCalibration.h
void RawTowerZDCCalibration::TowerType (const int type) inline
Definition at line 36 of file RawTowerZDCCalibration.h.
View newest version in sPHENIX GitHub at line 36 of file RawTowerZDCCalibration.h
References _tower_type.
Member Data Documentation
enu_calib_algorithm RawTowerZDCCalibration::_calib_algorithm protected
Definition at line 144 of file RawTowerZDCCalibration.h.
View newest version in sPHENIX GitHub at line 144 of file RawTowerZDCCalibration.h
Referenced by get_calib_algorithm(), process_event(), and set_calib_algorithm().
double RawTowerZDCCalibration::_calib_const_GeV_ADC protected
calibration constant in unit of GeV per ADC
Definition at line 165 of file RawTowerZDCCalibration.h.
View newest version in sPHENIX GitHub at line 165 of file RawTowerZDCCalibration.h
Referenced by get_calib_const_GeV_ADC(), process_event(), and set_calib_const_GeV_ADC().
std::string RawTowerZDCCalibration::_calib_tower_node_prefix protected
Definition at line 155 of file RawTowerZDCCalibration.h.
View newest version in sPHENIX GitHub at line 155 of file RawTowerZDCCalibration.h
Referenced by CreateNodes(), get_calib_tower_node_prefix(), and set_calib_tower_node_prefix().
RawTowerZDCContainer* RawTowerZDCCalibration::_calib_towers protected
Definition at line 146 of file RawTowerZDCCalibration.h.
View newest version in sPHENIX GitHub at line 146 of file RawTowerZDCCalibration.h
Referenced by CreateNodes(), and process_event().
bool RawTowerZDCCalibration::_GeV_ADC_file protected
GeV per ADC from file.
Definition at line 168 of file RawTowerZDCCalibration.h.
View newest version in sPHENIX GitHub at line 168 of file RawTowerZDCCalibration.h
Referenced by process_event(), and set_variable_GeV_ADC().
double RawTowerZDCCalibration::_pedestal_ADC protected
pedestal in unit of ADC
Definition at line 159 of file RawTowerZDCCalibration.h.
View newest version in sPHENIX GitHub at line 159 of file RawTowerZDCCalibration.h
Referenced by get_pedestal_ADC(), process_event(), and set_pedestal_ADC().
bool RawTowerZDCCalibration::_pedestal_file protected
pedestal from file
Definition at line 162 of file RawTowerZDCCalibration.h.
View newest version in sPHENIX GitHub at line 162 of file RawTowerZDCCalibration.h
Referenced by process_event(), and set_variable_pedestal().
std::string RawTowerZDCCalibration::_raw_tower_node_prefix protected
Definition at line 156 of file RawTowerZDCCalibration.h.
View newest version in sPHENIX GitHub at line 156 of file RawTowerZDCCalibration.h
Referenced by CreateNodes(), get_raw_tower_node_prefix(), and set_raw_tower_node_prefix().
RawTowerZDCContainer* RawTowerZDCCalibration::_raw_towers protected
Definition at line 147 of file RawTowerZDCCalibration.h.
View newest version in sPHENIX GitHub at line 147 of file RawTowerZDCCalibration.h
Referenced by CreateNodes(), and process_event().
PHParameters RawTowerZDCCalibration::_tower_calib_params protected
Tower by tower calibration parameters.
Definition at line 174 of file RawTowerZDCCalibration.h.
View newest version in sPHENIX GitHub at line 174 of file RawTowerZDCCalibration.h
Referenced by Detector(), GetCalibrationParameters(), and process_event().
int RawTowerZDCCalibration::_tower_type protected
tower type to act on
Definition at line 171 of file RawTowerZDCCalibration.h.
View newest version in sPHENIX GitHub at line 171 of file RawTowerZDCCalibration.h
Referenced by process_event(), and TowerType().
std::string RawTowerZDCCalibration::CaliTowerNodeName protected
Definition at line 152 of file RawTowerZDCCalibration.h.
View newest version in sPHENIX GitHub at line 152 of file RawTowerZDCCalibration.h
Referenced by CreateNodes().
std::string RawTowerZDCCalibration::detector protected
Definition at line 150 of file RawTowerZDCCalibration.h.
View newest version in sPHENIX GitHub at line 150 of file RawTowerZDCCalibration.h
Referenced by CreateNodes(), Detector(), InitRun(), and process_event().
RawTowerZDCGeomContainer* RawTowerZDCCalibration::rawtowergeom protected
Definition at line 148 of file RawTowerZDCCalibration.h.
View newest version in sPHENIX GitHub at line 148 of file RawTowerZDCCalibration.h
Referenced by CreateNodes(), and process_event().
std::string RawTowerZDCCalibration::RawTowerNodeName protected
Definition at line 151 of file RawTowerZDCCalibration.h.
View newest version in sPHENIX GitHub at line 151 of file RawTowerZDCCalibration.h
Referenced by CreateNodes().
std::string RawTowerZDCCalibration::TowerGeomNodeName protected
Definition at line 153 of file RawTowerZDCCalibration.h.
View newest version in sPHENIX GitHub at line 153 of file RawTowerZDCCalibration.h
Referenced by CreateNodes().
The documentation for this class was generated from the following files:
fun4all_eicdetectors/blob/master/reconstruction/eiczdcreco/RawTowerZDCCalibration.h
fun4all_eicdetectors/blob/master/reconstruction/eiczdcreco/RawTowerZDCCalibration.cc