EIC Software: CbmRichRingFitterEllipseMinuit Class Reference
CbmRichRingFitterEllipseMinuit Class Reference
This is the implementation of ellipse fitting using MINUIT.
#include <EicRoot/blob/master/rich/fitter/CbmRichRingFitterEllipseMinuit.h>
Public Member Functions
CbmRichRingFitterEllipseMinuit ()
Default constructor.
virtual ~CbmRichRingFitterEllipseMinuit ()
Standard destructor.
virtual void DoFit (CbmRichRingLight *ring)
Inherited from CbmRichRingFitterBase.
Public Member Functions inherited from CbmRichRingFitterEllipseBase
CbmRichRingFitterEllipseBase ()
Default constructor.
virtual ~CbmRichRingFitterEllipseBase ()
Destructor.
Public Member Functions inherited from CbmRichRingFitterBase
CbmRichRingFitterBase ()
Default constructor.
virtual ~CbmRichRingFitterBase ()
Destructor.
Private Member Functions
vector< double > DoFit (const vector< double > &x, const vector< double > &y)
Execute ring fitting algorithm.
void TransformToRichRing (CbmRichRingLight *ring, const vector< double > &par)
Transform obtained parameters from MINUIT to CbmRichRingLight.
Additional Inherited Members
Protected Member Functions inherited from CbmRichRingFitterEllipseBase
virtual void CalcChi2 (CbmRichRingLight *ring)
Calculate chi2 of the ellipse fit.
virtual void CalcChi2 (double A, double B, double C, double D, double E, double F, CbmRichRingLight *ring)
Calculate chi2 of the ellipse fitting using parameters of 2D curve.
Static Protected Attributes inherited from CbmRichRingFitterBase
static const int MAX_NOF_HITS_IN_RING = 400
Detailed Description
This is the implementation of ellipse fitting using MINUIT.
Author
Semen Lebedev s.leb.nosp@m.edev.nosp@m.@gsi..nosp@m.de
Date
2011
Definition at line 107 of file CbmRichRingFitterEllipseMinuit.h.
View newest version in sPHENIX GitHub at line 107 of file CbmRichRingFitterEllipseMinuit.h
Constructor & Destructor Documentation
CbmRichRingFitterEllipseMinuit::CbmRichRingFitterEllipseMinuit ()
Default constructor.
Definition at line 13 of file CbmRichRingFitterEllipseMinuit.cxx.
View newest version in sPHENIX GitHub at line 13 of file CbmRichRingFitterEllipseMinuit.cxx
CbmRichRingFitterEllipseMinuit::~CbmRichRingFitterEllipseMinuit () virtual
Standard destructor.
Definition at line 18 of file CbmRichRingFitterEllipseMinuit.cxx.
View newest version in sPHENIX GitHub at line 18 of file CbmRichRingFitterEllipseMinuit.cxx
Member Function Documentation
void CbmRichRingFitterEllipseMinuit::DoFit (CbmRichRingLight * ring) virtual
Inherited from CbmRichRingFitterBase.
Implements CbmRichRingFitterBase.
Definition at line 23 of file CbmRichRingFitterEllipseMinuit.cxx.
View newest version in sPHENIX GitHub at line 23 of file CbmRichRingFitterEllipseMinuit.cxx
References CbmRichRingFitterEllipseBase::CalcChi2(), CbmRichHitLight::fX, CbmRichHitLight::fY, CbmRichRingLight::GetHit(), CbmRichRingLight::GetNofHits(), CbmRichRingLight::SetRadius(), CbmRichRingLight::SetXYABP(), and TransformToRichRing().
vector< double > CbmRichRingFitterEllipseMinuit::DoFit (const vector< double > & x, const vector< double > & y) private
Execute ring fitting algorithm.
Parameters
[in] x X coordinates of hits.
[in] y Y coordinates of hit.
Returns
Vector of fitted parameters.
Definition at line 87 of file CbmRichRingFitterEllipseMinuit.cxx.
View newest version in sPHENIX GitHub at line 87 of file CbmRichRingFitterEllipseMinuit.cxx
void CbmRichRingFitterEllipseMinuit::TransformToRichRing (CbmRichRingLight * ring, const vector< double > & par) private
Transform obtained parameters from MINUIT to CbmRichRingLight.
Parameters
[out] ring Pointer to the RICH ring.
[in] par Parameters obtained from MINUIT.
Definition at line 50 of file CbmRichRingFitterEllipseMinuit.cxx.
View newest version in sPHENIX GitHub at line 50 of file CbmRichRingFitterEllipseMinuit.cxx
References c, k, CbmRichRingLight::SetRadius(), and CbmRichRingLight::SetXYABP().
Referenced by DoFit().
The documentation for this class was generated from the following files:
EicRoot/blob/master/rich/fitter/CbmRichRingFitterEllipseMinuit.h
EicRoot/blob/master/rich/fitter/CbmRichRingFitterEllipseMinuit.cxx