EIC Software: EicRoot/blob/master/base/FairField.h File Reference
FairField.h File Reference
#include "FairLogger.h"
#include "RVersion.h"
#include "TNamed.h"
#include <iostream>
Classes
class TVirtualMagField
Macros
#define ROOT_TVirtualMagField
Functions
ClassImp (TVirtualMagField) class FairField
Macro Definition Documentation
#define ROOT_TVirtualMagField
FairField.h
Author
M.Al-Turany <m.al/turany.de>
V.Friese v.fri.nosp@m.ese@.nosp@m.gsi.d.nosp@m.e
Since
06.01.2004 .0
Abstract base class for magnetic fields in FAIR Concrete field should implement the pure virtual methods GetBx, GetBy and GetBz and/or GetBxyz
Note: Field values should be returned in kG (thanks to GEANT3)
Definition at line 37 of file FairField.h.
View newest version in sPHENIX GitHub at line 37 of file FairField.h
Function Documentation
ClassImp (TVirtualMagField)
Default constructor
Constructor with name and title
Destructor
Intialisation. E.g. read in the field map. If needed, to be implemented in the concrete class.
Test whether field type is Constant
Test whether field typ is Map
Field type (0=constant, 1=map, 2=map sym2, 3 = map sym3)
Get x component of magnetic field [kG]
Parameters
x,y,z Position [cm]
Get y component of magnetic field [kG]
Parameters
x,y,z Position [cm]
Get z component of magnetic field [kG]
Parameters
x,y,z Position [cm]
Get magnetic field. For use of GEANT3
Parameters
point Coordinates [cm]
bField (return) Field components [kG]
Screen output. To be implemented in the concrete class.
Fill Paramater
Field type. 1 = constant field, 2 = field map.
Fair Logger
Definition at line 50 of file FairField.h.
View newest version in sPHENIX GitHub at line 50 of file FairField.h
References Acts::IntegrationTest::bField, TVirtualMagField::Field(), name, Print(), printf(), title(), x, y, and z.