EIC Software: tofBarrel Class Reference
tofBarrel Class Reference
#include <eicsmeardetectors/blob/master/piddetectors/tofBarrel.h>
Public Member Functions
tofBarrel (double radius=100, double etaLow=-1.0, double etaHigh=1.0, double sigmaT=10)
virtual ~tofBarrel ()
bool valid (double eta, double p)
double numSigma (double eta, double p, PID::type PID)
double maxP (double eta, double numSigma, PID::type PID)
double minP (double eta, double numSigma, PID::type PID)
std::string name ()
void description ()
Public Member Functions inherited from PID
PID ()
virtual ~PID ()
Protected Member Functions
double tof (double L, double p, double m)
Protected Attributes
std::string myName
double radius
double etaLow
double etaHigh
double sigmaT
double mPion
double mKaon
double mProton
double c
Additional Inherited Members
Public Types inherited from PID
enum type { pi_k, k_p }
Detailed Description
Definition at line 22 of file tofBarrel.h.
View newest version in sPHENIX GitHub at line 22 of file tofBarrel.h
Constructor & Destructor Documentation
tofBarrel::tofBarrel (double radius = 100, double etaLow = -1.0, double etaHigh = 1.0, double sigmaT = 10)
Definition at line 6 of file tofBarrel.C.
View newest version in sPHENIX GitHub at line 6 of file tofBarrel.C
References c, and G4BECAL::radius.
virtual tofBarrel::~tofBarrel () inline virtual
Definition at line 26 of file tofBarrel.h.
View newest version in sPHENIX GitHub at line 26 of file tofBarrel.h
Member Function Documentation
void tofBarrel::description () virtual
Implements PID.
Definition at line 100 of file tofBarrel.C.
View newest version in sPHENIX GitHub at line 100 of file tofBarrel.C
References G4BECAL::radius.
double tofBarrel::maxP (double eta, double numSigma, PID::type PID) virtual
Implements PID.
Definition at line 48 of file tofBarrel.C.
View newest version in sPHENIX GitHub at line 48 of file tofBarrel.C
References c, denom, Acts::IntegrationTest::L, G4BECAL::radius, theta(), and Acts::IntegrationTest::valid().
double tofBarrel::minP (double eta, double numSigma, PID::type PID) inline virtual
Implements PID.
Definition at line 31 of file tofBarrel.h.
View newest version in sPHENIX GitHub at line 31 of file tofBarrel.h
std::string tofBarrel::name () inline virtual
Implements PID.
Definition at line 32 of file tofBarrel.h.
View newest version in sPHENIX GitHub at line 32 of file tofBarrel.h
References myName.
double tofBarrel::numSigma (double eta, double p, PID::type PID) virtual
Implements PID.
Definition at line 24 of file tofBarrel.C.
View newest version in sPHENIX GitHub at line 24 of file tofBarrel.C
References Acts::IntegrationTest::L, G4BECAL::radius, theta(), and Acts::IntegrationTest::valid().
double tofBarrel::tof (double L, double p, double m) protected
Definition at line 93 of file tofBarrel.C.
View newest version in sPHENIX GitHub at line 93 of file tofBarrel.C
References c, and Acts::UnitConstants::m.
bool tofBarrel::valid (double eta, double p) inline virtual
Implements PID.
Definition at line 28 of file tofBarrel.h.
View newest version in sPHENIX GitHub at line 28 of file tofBarrel.h
References etaHigh, and etaLow.
Member Data Documentation
double tofBarrel::c protected
Definition at line 51 of file tofBarrel.h.
View newest version in sPHENIX GitHub at line 51 of file tofBarrel.h
double tofBarrel::etaHigh protected
Definition at line 44 of file tofBarrel.h.
View newest version in sPHENIX GitHub at line 44 of file tofBarrel.h
Referenced by valid().
double tofBarrel::etaLow protected
Definition at line 43 of file tofBarrel.h.
View newest version in sPHENIX GitHub at line 43 of file tofBarrel.h
Referenced by valid().
double tofBarrel::mKaon protected
Definition at line 49 of file tofBarrel.h.
View newest version in sPHENIX GitHub at line 49 of file tofBarrel.h
double tofBarrel::mPion protected
Definition at line 48 of file tofBarrel.h.
View newest version in sPHENIX GitHub at line 48 of file tofBarrel.h
double tofBarrel::mProton protected
Definition at line 50 of file tofBarrel.h.
View newest version in sPHENIX GitHub at line 50 of file tofBarrel.h
std::string tofBarrel::myName protected
Definition at line 36 of file tofBarrel.h.
View newest version in sPHENIX GitHub at line 36 of file tofBarrel.h
Referenced by name().
double tofBarrel::radius protected
Definition at line 42 of file tofBarrel.h.
View newest version in sPHENIX GitHub at line 42 of file tofBarrel.h
double tofBarrel::sigmaT protected
Definition at line 45 of file tofBarrel.h.
View newest version in sPHENIX GitHub at line 45 of file tofBarrel.h
The documentation for this class was generated from the following files:
eicsmeardetectors/blob/master/piddetectors/tofBarrel.h
eicsmeardetectors/blob/master/piddetectors/tofBarrel.C