EIC Software: fun4all_eicmacros/blob/master/common/G4_FHCAL.C File Reference
G4_FHCAL.C File Reference
#include <GlobalVariables.C>
#include <g4calo/RawTowerBuilderByHitIndex.h>
#include <g4calo/RawTowerDigitizer.h>
#include <g4eiccalos/PHG4ForwardCalCellReco.h>
#include <g4eiccalos/PHG4ForwardHcalSubsystem.h>
#include <g4eval/CaloEvaluator.h>
#include <g4main/PHG4Reco.h>
#include <caloreco/RawClusterBuilderFwd.h>
#include <caloreco/RawClusterBuilderTemplate.h>
#include <caloreco/RawTowerCalibration.h>
#include <fun4all/Fun4AllServer.h>
Namespaces
namespace Enable
namespace G4FHCAL
namespace G4FHCAL::SETTING
Macros
#define MACRO_G4FHCAL_C
Enumerations
enum G4FHCAL::enu_FHcal_clusterizer { G4FHCAL::kFHcalGraphClusterizer, G4FHCAL::kFHcalTemplateClusterizer, G4FHCAL::kFHcalGraphClusterizer, G4FHCAL::kFHcalTemplateClusterizer }
Functions
void FHCALInit ()
void FHCALSetup (PHG4Reco *g4Reco)
void FHCAL_Cells (int verbosity=0)
void FHCAL_Towers ()
void FHCAL_Clusters ()
void FHCAL_Eval (const std::string &outputfile)
Variables
bool Enable::FHCAL = false
bool Enable::FHCAL_ABSORBER = false
bool Enable::FHCAL_SUPPORT = false
bool Enable::FHCAL_CELL = false
bool Enable::FHCAL_TOWER = false
bool Enable::FHCAL_CLUSTER = false
bool Enable::FHCAL_EVAL = false
bool Enable::FHCAL_OVERLAPCHECK = false
int Enable::FHCAL_VERBOSITY = 0
double G4FHCAL::Gz0 = 400.
double G4FHCAL::Gdz = 100.
double G4FHCAL::outer_radius = 262.
double G4FHCAL::sampling_fraction = 0.03898
enu_FHcal_clusterizer G4FHCAL::FHcal_clusterizer = kFHcalTemplateClusterizer
int G4FHCAL::SETTING::Absorber_FeTungsten = 0
bool G4FHCAL::SETTING::FullEtaAcc = false
bool G4FHCAL::SETTING::HC2x = false
bool G4FHCAL::SETTING::HC4x = false
bool G4FHCAL::SETTING::asymmetric = false
bool G4FHCAL::SETTING::extradepth = false
bool G4FHCAL::SETTING::wDR = false
bool G4FHCAL::SETTING::FwdSquare = false
bool G4FHCAL::SETTING::towercalib1 = false
bool G4FHCAL::SETTING::towercalibSiPM = false
bool G4FHCAL::SETTING::towercalibHCALIN = false
bool G4FHCAL::SETTING::towercalib3 = false
Macro Definition Documentation
#define MACRO_G4FHCAL_C
Definition at line 2 of file G4_FHCAL.C.
View newest version in sPHENIX GitHub at line 2 of file G4_FHCAL.C
Function Documentation
void FHCAL_Cells (int verbosity = 0)
Definition at line 171 of file G4_FHCAL.C.
View newest version in sPHENIX GitHub at line 171 of file G4_FHCAL.C
Referenced by Fun4All_G4_LBLDetector().
void FHCAL_Clusters ()
Definition at line 362 of file G4_FHCAL.C.
View newest version in sPHENIX GitHub at line 362 of file G4_FHCAL.C
References RawClusterBuilderTemplate::Detector(), RawClusterBuilderFwd::Detector(), G4FHCAL::FHcal_clusterizer, Enable::FHCAL_VERBOSITY, Fun4AllServer::instance(), G4FHCAL::kFHcalTemplateClusterizer, max, Fun4AllServer::registerSubsystem(), RawClusterBuilderFwd::set_threshold_energy(), RawClusterBuilderTemplate::set_threshold_energy(), RawClusterBuilderTemplate::SetPlanarGeometry(), Enable::VERBOSITY, and Fun4AllBase::Verbosity().
Referenced by Extract_ECCE_gdml(), Fun4All_G4_CEMC(), Fun4All_G4_EICDetector(), Fun4All_G4_EICDetector_AnaTutorial(), Fun4All_G4_FEMC(), Fun4All_G4_FHCAL(), Fun4All_G4_fsPHENIX(), Fun4All_G4_FullDetectorModular(), Fun4All_G4_FullDetectorModularBeast(), Fun4All_G4_HCALIN(), Fun4All_G4_HCALOUT(), and Fun4All_G4_LBLDetector().
void FHCAL_Eval (const std::string & outputfile)
Definition at line 393 of file G4_FHCAL.C.
View newest version in sPHENIX GitHub at line 393 of file G4_FHCAL.C
References Enable::FHCAL_VERBOSITY, Fun4AllServer::instance(), max, Fun4AllServer::registerSubsystem(), Enable::VERBOSITY, and Fun4AllBase::Verbosity().
Referenced by Fun4All_G4_CEMC(), Fun4All_G4_EICDetector(), Fun4All_G4_EICDetector_AnaTutorial(), Fun4All_G4_FEMC(), Fun4All_G4_FHCAL(), Fun4All_G4_fsPHENIX(), Fun4All_G4_HCALIN(), Fun4All_G4_HCALOUT(), and Fun4All_G4_LBLDetector().
void FHCAL_Towers ()
Definition at line 176 of file G4_FHCAL.C.
View newest version in sPHENIX GitHub at line 176 of file G4_FHCAL.C
References G4FHCAL::SETTING::asymmetric, RawTowerDigitizer::Detector(), RawTowerCalibration::Detector(), RawTowerBuilderByHitIndex::Detector(), Acts::UnitConstants::e, G4FHCAL::SETTING::extradepth, Enable::FHCAL_VERBOSITY, G4FHCAL::SETTING::FullEtaAcc, G4FHCAL::SETTING::FwdSquare, RawTowerBuilderByHitIndex::GeometryTableFile(), G4FHCAL::SETTING::HC2x, G4FHCAL::SETTING::HC4x, Fun4AllServer::instance(), RawTowerDigitizer::kNo_digitization, RawTowerCalibration::kSimple_linear_calibration, RawTowerDigitizer::kSimple_photon_digitalization, RawTowerDigitizer::kSiPM_photon_digitization, max, Fun4AllServer::registerSubsystem(), G4FHCAL::sampling_fraction, RawTowerCalibration::set_calib_algorithm(), RawTowerCalibration::set_calib_const_GeV_ADC(), RawTowerDigitizer::set_digi_algorithm(), RawTowerCalibration::set_pedstal_ADC(), RawTowerDigitizer::set_pedstal_central_ADC(), RawTowerDigitizer::set_pedstal_width_ADC(), RawTowerDigitizer::set_photonelec_ADC(), RawTowerDigitizer::set_photonelec_yield_visible_GeV(), RawTowerCalibration::set_raw_tower_node_prefix(), RawTowerDigitizer::set_raw_tower_node_prefix(), RawTowerBuilderByHitIndex::set_sim_tower_node_prefix(), RawTowerDigitizer::set_zero_suppression_ADC(), RawTowerCalibration::set_zero_suppression_GeV(), G4FHCAL::SETTING::towercalib1, G4FHCAL::SETTING::towercalib3, G4FHCAL::SETTING::towercalibHCALIN, G4FHCAL::SETTING::towercalibSiPM, Enable::VERBOSITY, Fun4AllBase::Verbosity(), and G4FHCAL::SETTING::wDR.
Referenced by Extract_ECCE_gdml(), Fun4All_G4_CEMC(), Fun4All_G4_EICDetector(), Fun4All_G4_EICDetector_AnaTutorial(), Fun4All_G4_FEMC(), Fun4All_G4_FHCAL(), Fun4All_G4_fsPHENIX(), Fun4All_G4_FullDetectorModular(), Fun4All_G4_FullDetectorModularBeast(), Fun4All_G4_HCALIN(), Fun4All_G4_HCALOUT(), and Fun4All_G4_LBLDetector().
void FHCALInit ()
Definition at line 73 of file G4_FHCAL.C.
View newest version in sPHENIX GitHub at line 73 of file G4_FHCAL.C
References G4FHCAL::SETTING::asymmetric, G4FHCAL::SETTING::FullEtaAcc, G4FHCAL::SETTING::FwdSquare, G4FHCAL::Gdz, G4FHCAL::Gz0, G4FHCAL::SETTING::HC2x, G4FHCAL::SETTING::HC4x, max, BlackHoleGeometry::max_radius, BlackHoleGeometry::max_z, min, BlackHoleGeometry::min_z, G4FHCAL::outer_radius, G4FHCAL::SETTING::towercalib1, G4FHCAL::SETTING::towercalib3, G4FHCAL::SETTING::towercalibHCALIN, G4FHCAL::SETTING::towercalibSiPM, and G4FHCAL::SETTING::wDR.
Referenced by G4Init().
void FHCALSetup (PHG4Reco * g4Reco)
Use dedicated FHCAL module
Definition at line 95 of file G4_FHCAL.C.
View newest version in sPHENIX GitHub at line 95 of file G4_FHCAL.C
References Enable::ABSORBER, G4FHCAL::SETTING::Absorber_FeTungsten, G4FHCAL::SETTING::asymmetric, G4FHCAL::SETTING::extradepth, Enable::FHCAL_ABSORBER, Enable::FHCAL_OVERLAPCHECK, Enable::FHCAL_SUPPORT, G4FHCAL::SETTING::FullEtaAcc, G4FHCAL::SETTING::FwdSquare, G4FHCAL::SETTING::HC2x, G4FHCAL::SETTING::HC4x, Fun4AllServer::instance(), Enable::OVERLAPCHECK, PHG4DetectorSubsystem::OverlapCheck(), PHG4Reco::registerSubsystem(), PHG4DetectorSubsystem::SetAbsorberActive(), PHG4DetectorSubsystem::SetActive(), PHG4ForwardHcalSubsystem::SetDetailed(), PHG4DetectorSubsystem::SetSupportActive(), PHG4ForwardHcalSubsystem::SetTowerMappingFile(), PHG4ForwardHcalSubsystem::SetUseFeTungstenAbsorber(), PHG4DetectorSubsystem::SuperDetector(), Enable::SUPPORT, and G4FHCAL::SETTING::wDR.
Referenced by G4Setup().