EIC Software: EICG4dRICHTree Class Reference
EICG4dRICHTree Class Reference
#include <fun4all_eicdetectors/blob/master/simulation/g4simulation/g4drich/EICG4dRICHTree.h>
Public Member Functions
EICG4dRICHTree (const std::string &name="EICG4dRICHTree", const std::string &fname="EICG4dRICHTree.root")
virtual ~EICG4dRICHTree ()
int Init (PHCompositeNode *)
int process_event (PHCompositeNode *)
int End (PHCompositeNode *)
Called at the end of all processing.
Public Member Functions inherited from SubsysReco
~SubsysReco () override
virtual int EndRun (const int)
Called at the end of each run.
virtual int InitRun (PHCompositeNode *)
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
void Print (const std::string &="ALL") const override
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Private Member Functions
void getHits (PHCompositeNode *topNode)
void vectorToArray (G4ThreeVector vec, Double_t *arr)
void initTrees ()
Private Attributes
std::string m_outfileN
TFile * m_outfile
TTree * m_tree
Int_t evnum
Int_t trackID
char hitType [128]
char hitSubtype [128]
Int_t petal
Int_t psst
Int_t pdg
char particleName [128]
char process [256]
Int_t parentID
Double_t hitPos [3]
Double_t hitP [3]
Double_t hitPdir [3]
Double_t hitVtxPos [3]
Double_t hitVtxPdir [3]
Double_t deltaT
Double_t edep
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = INT_MAX - 10
}
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Detailed Description
Definition at line 21 of file EICG4dRICHTree.h.
View newest version in sPHENIX GitHub at line 21 of file EICG4dRICHTree.h
Constructor & Destructor Documentation
EICG4dRICHTree::EICG4dRICHTree (const std::string & name = "EICG4dRICHTree", const std::string & fname = "EICG4dRICHTree.root")
Definition at line 43 of file EICG4dRICHTree.cc.
View newest version in sPHENIX GitHub at line 43 of file EICG4dRICHTree.cc
References initTrees().
EICG4dRICHTree::~EICG4dRICHTree () virtual
Definition at line 54 of file EICG4dRICHTree.cc.
View newest version in sPHENIX GitHub at line 54 of file EICG4dRICHTree.cc
References m_tree.
Member Function Documentation
int EICG4dRICHTree::End (PHCompositeNode *) virtual
Called at the end of all processing.
Reimplemented from SubsysReco.
Definition at line 88 of file EICG4dRICHTree.cc.
View newest version in sPHENIX GitHub at line 88 of file EICG4dRICHTree.cc
References m_outfile, m_tree, Fun4AllBase::Verbosity(), and Fun4AllBase::VERBOSITY_MORE.
void EICG4dRICHTree::getHits (PHCompositeNode * topNode) private
Definition at line 104 of file EICG4dRICHTree.cc.
View newest version in sPHENIX GitHub at line 104 of file EICG4dRICHTree.cc
References deltaT, edep, evnum, EICG4dRICHHit::get_delta_t(), EICG4dRICHHit::get_edep(), EICG4dRICHHit::get_hit_subtype_name(), EICG4dRICHHit::get_hit_type_name(), EICG4dRICHHit::get_momentum(), EICG4dRICHHit::get_momentum_dir(), EICG4dRICHHit::get_parent_id(), EICG4dRICHHit::get_particle_name(), EICG4dRICHHit::get_pdg(), EICG4dRICHHit::get_petal(), EICG4dRICHHit::get_position(), EICG4dRICHHit::get_process(), EICG4dRICHHit::get_psst(), EICG4dRICHHit::get_trkid(), EICG4dRICHHit::get_vertex_momentum_dir(), EICG4dRICHHit::get_vertex_position(), PHG4HitContainer::getHits(), hitP, hitPdir, hitPos, hitSubtype, hitType, hitVtxPdir, hitVtxPos, m_tree, parentID, particleName, pdg, petal, EICG4dRICHHit::print(), process, psst, trackID, vectorToArray(), Fun4AllBase::Verbosity(), and Fun4AllBase::VERBOSITY_A_LOT.
Referenced by process_event().
int EICG4dRICHTree::Init (PHCompositeNode *) virtual
Called during initialization. Typically this is where you can book histograms, and e.g. register them to Fun4AllServer (so they can be output to file using Fun4AllServer::dumpHistos() method).
Reimplemented from SubsysReco.
Definition at line 61 of file EICG4dRICHTree.cc.
View newest version in sPHENIX GitHub at line 61 of file EICG4dRICHTree.cc
References m_outfile, m_outfileN, Fun4AllBase::Verbosity(), and Fun4AllBase::VERBOSITY_A_LOT.
void EICG4dRICHTree::initTrees () private
Definition at line 160 of file EICG4dRICHTree.cc.
View newest version in sPHENIX GitHub at line 160 of file EICG4dRICHTree.cc
References deltaT, edep, evnum, hitP, hitPdir, hitPos, hitSubtype, hitType, hitVtxPdir, hitVtxPos, m_tree, parentID, particleName, pdg, petal, process, psst, and trackID.
Referenced by EICG4dRICHTree().
int EICG4dRICHTree::process_event (PHCompositeNode *) virtual
Called for each event. This is where you do the real work.
Reimplemented from SubsysReco.
Definition at line 73 of file EICG4dRICHTree.cc.
View newest version in sPHENIX GitHub at line 73 of file EICG4dRICHTree.cc
References Fun4AllReturnCodes::EVENT_OK, getHits(), Fun4AllBase::Verbosity(), and Fun4AllBase::VERBOSITY_A_LOT.
void EICG4dRICHTree::vectorToArray (G4ThreeVector vec, Double_t * arr) private
Definition at line 152 of file EICG4dRICHTree.cc.
View newest version in sPHENIX GitHub at line 152 of file EICG4dRICHTree.cc
Referenced by getHits().
Member Data Documentation
Double_t EICG4dRICHTree::deltaT private
Definition at line 69 of file EICG4dRICHTree.h.
View newest version in sPHENIX GitHub at line 69 of file EICG4dRICHTree.h
Referenced by getHits(), and initTrees().
Double_t EICG4dRICHTree::edep private
Definition at line 70 of file EICG4dRICHTree.h.
View newest version in sPHENIX GitHub at line 70 of file EICG4dRICHTree.h
Referenced by getHits(), and initTrees().
Int_t EICG4dRICHTree::evnum private
Definition at line 56 of file EICG4dRICHTree.h.
View newest version in sPHENIX GitHub at line 56 of file EICG4dRICHTree.h
Referenced by getHits(), and initTrees().
Double_t EICG4dRICHTree::hitP[3] private
Definition at line 65 of file EICG4dRICHTree.h.
View newest version in sPHENIX GitHub at line 65 of file EICG4dRICHTree.h
Referenced by getHits(), and initTrees().
Double_t EICG4dRICHTree::hitPdir[3] private
Definition at line 66 of file EICG4dRICHTree.h.
View newest version in sPHENIX GitHub at line 66 of file EICG4dRICHTree.h
Referenced by getHits(), and initTrees().
Double_t EICG4dRICHTree::hitPos[3] private
Definition at line 64 of file EICG4dRICHTree.h.
View newest version in sPHENIX GitHub at line 64 of file EICG4dRICHTree.h
Referenced by getHits(), and initTrees().
char EICG4dRICHTree::hitSubtype[128] private
Definition at line 59 of file EICG4dRICHTree.h.
View newest version in sPHENIX GitHub at line 59 of file EICG4dRICHTree.h
Referenced by getHits(), and initTrees().
char EICG4dRICHTree::hitType[128] private
Definition at line 58 of file EICG4dRICHTree.h.
View newest version in sPHENIX GitHub at line 58 of file EICG4dRICHTree.h
Referenced by getHits(), and initTrees().
Double_t EICG4dRICHTree::hitVtxPdir[3] private
Definition at line 68 of file EICG4dRICHTree.h.
View newest version in sPHENIX GitHub at line 68 of file EICG4dRICHTree.h
Referenced by getHits(), and initTrees().
Double_t EICG4dRICHTree::hitVtxPos[3] private
Definition at line 67 of file EICG4dRICHTree.h.
View newest version in sPHENIX GitHub at line 67 of file EICG4dRICHTree.h
Referenced by getHits(), and initTrees().
TFile* EICG4dRICHTree::m_outfile private
Definition at line 38 of file EICG4dRICHTree.h.
View newest version in sPHENIX GitHub at line 38 of file EICG4dRICHTree.h
Referenced by End(), and Init().
std::string EICG4dRICHTree::m_outfileN private
Definition at line 37 of file EICG4dRICHTree.h.
View newest version in sPHENIX GitHub at line 37 of file EICG4dRICHTree.h
Referenced by Init().
TTree* EICG4dRICHTree::m_tree private
Definition at line 39 of file EICG4dRICHTree.h.
View newest version in sPHENIX GitHub at line 39 of file EICG4dRICHTree.h
Referenced by End(), getHits(), initTrees(), and ~EICG4dRICHTree().
Int_t EICG4dRICHTree::parentID private
Definition at line 63 of file EICG4dRICHTree.h.
View newest version in sPHENIX GitHub at line 63 of file EICG4dRICHTree.h
Referenced by getHits(), and initTrees().
char EICG4dRICHTree::particleName[128] private
Definition at line 61 of file EICG4dRICHTree.h.
View newest version in sPHENIX GitHub at line 61 of file EICG4dRICHTree.h
Referenced by getHits(), and initTrees().
Int_t EICG4dRICHTree::pdg private
Definition at line 60 of file EICG4dRICHTree.h.
View newest version in sPHENIX GitHub at line 60 of file EICG4dRICHTree.h
Referenced by getHits(), and initTrees().
Int_t EICG4dRICHTree::petal private
Definition at line 60 of file EICG4dRICHTree.h.
View newest version in sPHENIX GitHub at line 60 of file EICG4dRICHTree.h
Referenced by getHits(), and initTrees().
char EICG4dRICHTree::process[256] private
Definition at line 62 of file EICG4dRICHTree.h.
View newest version in sPHENIX GitHub at line 62 of file EICG4dRICHTree.h
Referenced by getHits(), and initTrees().
Int_t EICG4dRICHTree::psst private
Definition at line 60 of file EICG4dRICHTree.h.
View newest version in sPHENIX GitHub at line 60 of file EICG4dRICHTree.h
Referenced by getHits(), and initTrees().
Int_t EICG4dRICHTree::trackID private
Definition at line 57 of file EICG4dRICHTree.h.
View newest version in sPHENIX GitHub at line 57 of file EICG4dRICHTree.h
Referenced by getHits(), and initTrees().
The documentation for this class was generated from the following files:
fun4all_eicdetectors/blob/master/simulation/g4simulation/g4drich/EICG4dRICHTree.h
fun4all_eicdetectors/blob/master/simulation/g4simulation/g4drich/EICG4dRICHTree.cc