EIC Software: beam Class Reference
beam Class Reference
#include <estarlight/blob/master/include/beam.h>
Public Member Functions
beam (const int Z, const int A, const int productionMode, const double beamLorentzGamma)
~beam ()
double photonDensity (const double impactparameter, const double photonEnergy) const
calculates photon density (number of photons / (energy * area))
double rapidity () const
void setBeamLorentzGamma (double gamma)
Public Member Functions inherited from nucleus
nucleus ()
nucleus (const int Z, const int A, const int productionMode)
~nucleus ()
void init ()
int Z () const
returns atomic number of nucleus
int A () const
returns nucleon number of nucleus
int productionMode () const
double formFactor (const double t) const
double dipoleFormFactor (const double t, const double t0) const
double thickness (const double b) const
double nuclearRadius () const
double rho0 () const
Protected Attributes
double _beamLorentzGamma
Lorentz gamma factor of beams in collider frame (from inputParameters)
Detailed Description
Definition at line 41 of file beam.h.
View newest version in sPHENIX GitHub at line 41 of file beam.h
Constructor & Destructor Documentation
beam::beam (const int Z, const int A, const int productionMode, const double beamLorentzGamma)
Definition at line 48 of file beam.cpp.
View newest version in sPHENIX GitHub at line 48 of file beam.cpp
beam::~beam ()
Definition at line 57 of file beam.cpp.
View newest version in sPHENIX GitHub at line 57 of file beam.cpp
Member Function Documentation
double beam::photonDensity (const double impactparameter, const double photonEnergy) const
calculates photon density (number of photons / (energy * area))
Definition at line 62 of file beam.cpp.
View newest version in sPHENIX GitHub at line 62 of file beam.cpp
References _beamLorentzGamma, starlightConstants::alpha, bessel::dbesk1(), starlightConstants::hbarc, starlightConstants::pi, printWarn, and nucleus::Z().
Referenced by twoPhotonLuminosity::D2LDMDY(), photonNucleusCrossSection::photonFlux(), and photonNucleusLuminosity::pttablegen().
double beam::rapidity () const inline
Definition at line 56 of file beam.h.
View newest version in sPHENIX GitHub at line 56 of file beam.h
References _beamLorentzGamma.
void beam::setBeamLorentzGamma (double gamma) inline
Definition at line 58 of file beam.h.
View newest version in sPHENIX GitHub at line 58 of file beam.h
References _beamLorentzGamma, and gamma().
Referenced by beamBeamSystem::init().
Member Data Documentation
double beam::_beamLorentzGamma protected
Lorentz gamma factor of beams in collider frame (from inputParameters)
Definition at line 61 of file beam.h.
View newest version in sPHENIX GitHub at line 61 of file beam.h
Referenced by photonDensity(), rapidity(), and setBeamLorentzGamma().
The documentation for this class was generated from the following files:
estarlight/blob/master/include/beam.h
estarlight/blob/master/src/beam.cpp