EIC Software: Acts::TrackDensityVertexFinder< vfitter_t, track_density_t > Class Template Reference
Acts::TrackDensityVertexFinder< vfitter_t, track_density_t > Class Template Reference
Finds a vertex seed based on the maximum of a track density function. Each track is modelled as a 2d density function around its d0/z0 perigee parameter values. The z seed position is then found as the position of the maximum of all summed track density functions.
#include <fun4all_acts/blob/master/Core/include/Acts/Vertexing/TrackDensityVertexFinder.hpp>
Classes
struct Config
The Config struct.
Public Member Functions
Result< std::vector< Vertex
< InputTrack_t > > > find (const std::vector< const InputTrack_t * > &trackVector, const VertexingOptions< InputTrack_t > &vertexingOptions) const
Function that finds single vertex candidate.
template<typename T = InputTrack_t, std::enable_if_t< std::is_same< T, BoundParameters >::value, int > = 0>
TrackDensityVertexFinder (const Config &cfg)
Constructor used if InputTrack_t type == BoundParameters.
m_extractParameters (func)
TrackDensityVertexFinder (const std::function< BoundParameters(InputTrack_t)> &func)
Constructor for user-defined InputTrack_t type =! BoundParameters with default Config object.
Private Types
using InputTrack_t = typename vfitter_t::InputTrack_t
Private Attributes
Config m_cfg
std::function< BoundParameters(InputTrack_t)> m_extractParameters
Function to extract track parameters, InputTrack_t objects are BoundParameters by default, function to be overwritten to return BoundParameters for other InputTrack_t objects.
Detailed Description
template<typename vfitter_t, typename track_density_t = GaussianTrackDensity>
class Acts::TrackDensityVertexFinder< vfitter_t, track_density_t >
Finds a vertex seed based on the maximum of a track density function. Each track is modelled as a 2d density function around its d0/z0 perigee parameter values. The z seed position is then found as the position of the maximum of all summed track density functions.
Ref. (1): https://cds.cern.ch/record/2670380
Template Parameters
vfitter_t The vertex fitter type (needed to fulfill concept)
track_density_t The track density type
Definition at line 35 of file TrackDensityVertexFinder.hpp.
View newest version in sPHENIX GitHub at line 35 of file TrackDensityVertexFinder.hpp
Member Typedef Documentation
template<typename vfitter_t, typename track_density_t = GaussianTrackDensity> using Acts::TrackDensityVertexFinder< vfitter_t, track_density_t >::InputTrack_t = typename vfitter_t::InputTrack_t private
Definition at line 42 of file TrackDensityVertexFinder.hpp.
View newest version in sPHENIX GitHub at line 42 of file TrackDensityVertexFinder.hpp
Constructor & Destructor Documentation
template<typename vfitter_t, typename track_density_t = GaussianTrackDensity> template<typename T = InputTrack_t, std::enable_if_t< std::is_same< T, BoundParameters >::value, int > = 0> Acts::TrackDensityVertexFinder< vfitter_t, track_density_t >::TrackDensityVertexFinder (const Config & cfg) inline
Constructor used if InputTrack_t type == BoundParameters.
Parameters
cfg Configuration object
Definition at line 67 of file TrackDensityVertexFinder.hpp.
View newest version in sPHENIX GitHub at line 67 of file TrackDensityVertexFinder.hpp
template<typename vfitter_t, typename track_density_t = GaussianTrackDensity> Acts::TrackDensityVertexFinder< vfitter_t, track_density_t >::TrackDensityVertexFinder (const std::function< BoundParameters(InputTrack_t)> & func) inline
Constructor for user-defined InputTrack_t type =! BoundParameters with default Config object.
Parameters
func Function extracting BoundParameters from InputTrack_t object
Definition at line 89 of file TrackDensityVertexFinder.hpp.
View newest version in sPHENIX GitHub at line 89 of file TrackDensityVertexFinder.hpp
Member Function Documentation
template<typename vfitter_t , typename track_density_t > auto Acts::TrackDensityVertexFinder< vfitter_t, track_density_t >::find (const std::vector< const InputTrack_t * > & trackVector, const VertexingOptions< InputTrack_t > & vertexingOptions) const
Function that finds single vertex candidate.
Parameters
trackVector Input track collection
vertexingOptions Vertexing options
Returns
Vector of vertices, filled with a single vertex (for consistent interfaces)
Definition at line 10 of file TrackDensityVertexFinder.ipp.
View newest version in sPHENIX GitHub at line 10 of file TrackDensityVertexFinder.ipp
References Acts::Vertex< input_track_t >::covariance(), Acts::eZ, Acts::Vertex< input_track_t >::setCovariance(), and z.
Referenced by Acts::Test::BOOST_AUTO_TEST_CASE().
template<typename vfitter_t, typename track_density_t = GaussianTrackDensity> Acts::TrackDensityVertexFinder< vfitter_t, track_density_t >::m_extractParameters (func) inline
Definition at line 83 of file TrackDensityVertexFinder.hpp.
View newest version in sPHENIX GitHub at line 83 of file TrackDensityVertexFinder.hpp
Member Data Documentation
template<typename vfitter_t, typename track_density_t = GaussianTrackDensity> Config Acts::TrackDensityVertexFinder< vfitter_t, track_density_t >::m_cfg private
Definition at line 94 of file TrackDensityVertexFinder.hpp.
View newest version in sPHENIX GitHub at line 94 of file TrackDensityVertexFinder.hpp
template<typename vfitter_t, typename track_density_t = GaussianTrackDensity> std::function<BoundParameters(InputTrack_t)> Acts::TrackDensityVertexFinder< vfitter_t, track_density_t >::m_extractParameters private
Function to extract track parameters, InputTrack_t objects are BoundParameters by default, function to be overwritten to return BoundParameters for other InputTrack_t objects.
Parameters
InputTrack_t object to extract track parameters from
Definition at line 101 of file TrackDensityVertexFinder.hpp.
View newest version in sPHENIX GitHub at line 101 of file TrackDensityVertexFinder.hpp
The documentation for this class was generated from the following files:
fun4all_acts/blob/master/Core/include/Acts/Vertexing/TrackDensityVertexFinder.hpp
fun4all_acts/blob/master/Core/include/Acts/Vertexing/TrackDensityVertexFinder.ipp