EIC Software: CbmStripHit Class Reference
CbmStripHit Class Reference
#include <EicRoot/blob/master/cbmdata/CbmStripHit.h>
Public Member Functions
CbmStripHit ()
Default constructor.
CbmStripHit (Int_t address, Double_t u, Double_t phi, Double_t z, Double_t du, Double_t dphi, Double_t dz, Int_t refId)
Standard constructor.
CbmStripHit (Int_t address, const TVector3 &pos, const TVector3 &err, Int_t refId)
Standard constructor.
virtual ~CbmStripHit ()
Destructor.
virtual string ToString () const
Inherited from CbmBaseHit.
Double_t GetU () const
Double_t GetPhi () const
Double_t GetDu () const
Double_t GetDphi () const
void SetU (Double_t u)
void SetPhi (Double_t phi)
void SetDu (Double_t du)
void SetDphi (Double_t dphi)
Public Member Functions inherited from CbmBaseHit
CbmBaseHit ()
Default constructor.
virtual ~CbmBaseHit ()
Destructor.
HitType GetType () const
Double_t GetZ () const
Double_t GetDz () const
Int_t GetRefId () const
Int_t GetAddress () const
FairMultiLinkedData * GetLinks () const
void SetZ (Double_t z)
void SetDz (Double_t dz)
void SetRefId (Int_t refId)
void SetAddress (Int_t address)
void SetLinks (FairMultiLinkedData *links)
virtual Int_t GetPlaneId () const =0
Private Member Functions
ClassDef (CbmStripHit, 1)
Private Attributes
Double_t fU
U coordinate in the rotated c.s [cm].
Double_t fDu
U error [cm].
Double_t fPhi
strip rotation angle [rad]
Double_t fDphi
strip rotation error [rad]
Additional Inherited Members
Protected Member Functions inherited from CbmBaseHit
void SetType (HitType type)
Sets hit type.
CbmBaseHit (const CbmBaseHit &)
CbmBaseHit & operator= (const CbmBaseHit &)
Detailed Description
Definition at line 17 of file CbmStripHit.h.
View newest version in sPHENIX GitHub at line 17 of file CbmStripHit.h
Constructor & Destructor Documentation
CbmStripHit::CbmStripHit ()
Default constructor.
Definition at line 15 of file CbmStripHit.cxx.
View newest version in sPHENIX GitHub at line 15 of file CbmStripHit.cxx
References kSTRIPHIT, and CbmBaseHit::SetType().
CbmStripHit::CbmStripHit (Int_t address, Double_t u, Double_t phi, Double_t z, Double_t du, Double_t dphi, Double_t dz, Int_t refId)
Standard constructor.
Parameters
address detector unique identifier
u coordinate in the rotated c.s. [cm]
phi strip rotation angle [rad]
z Z position of the hit [cm]
du U measurement error [cm]
dphi PHI measurement error [rad]
z Z position of the hit [cm]
refId some reference ID
Definition at line 25 of file CbmStripHit.cxx.
View newest version in sPHENIX GitHub at line 25 of file CbmStripHit.cxx
References kSTRIPHIT, CbmBaseHit::SetAddress(), CbmBaseHit::SetDz(), CbmBaseHit::SetRefId(), CbmBaseHit::SetType(), and CbmBaseHit::SetZ().
CbmStripHit::CbmStripHit (Int_t address, const TVector3 & pos, const TVector3 & err, Int_t refId)
Standard constructor.
Parameters
address Detector unique identifier.
pos Position of the hit as TVector3 (u, phi, z) [cm].
err Position errors of the hit as TVector3 (du, dphi, dz) [cm].
refId Some reference ID.
Definition at line 47 of file CbmStripHit.cxx.
View newest version in sPHENIX GitHub at line 47 of file CbmStripHit.cxx
References kSTRIPHIT, CbmBaseHit::SetAddress(), CbmBaseHit::SetDz(), CbmBaseHit::SetRefId(), CbmBaseHit::SetType(), and CbmBaseHit::SetZ().
CbmStripHit::~CbmStripHit () virtual
Destructor.
Definition at line 65 of file CbmStripHit.cxx.
View newest version in sPHENIX GitHub at line 65 of file CbmStripHit.cxx
Member Function Documentation
CbmStripHit::ClassDef (CbmStripHit , 1) private
Double_t CbmStripHit::GetDphi () const inline
Definition at line 73 of file CbmStripHit.h.
View newest version in sPHENIX GitHub at line 73 of file CbmStripHit.h
References fDphi.
Referenced by ToString().
Double_t CbmStripHit::GetDu () const inline
Definition at line 72 of file CbmStripHit.h.
View newest version in sPHENIX GitHub at line 72 of file CbmStripHit.h
References fDu.
Referenced by ToString().
Double_t CbmStripHit::GetPhi () const inline
Definition at line 71 of file CbmStripHit.h.
View newest version in sPHENIX GitHub at line 71 of file CbmStripHit.h
References fPhi.
Referenced by ToString().
Double_t CbmStripHit::GetU () const inline
Definition at line 70 of file CbmStripHit.h.
View newest version in sPHENIX GitHub at line 70 of file CbmStripHit.h
References fU.
Referenced by ToString().
void CbmStripHit::SetDphi (Double_t dphi) inline
Definition at line 79 of file CbmStripHit.h.
View newest version in sPHENIX GitHub at line 79 of file CbmStripHit.h
References fDphi.
void CbmStripHit::SetDu (Double_t du) inline
Definition at line 78 of file CbmStripHit.h.
View newest version in sPHENIX GitHub at line 78 of file CbmStripHit.h
References fDu.
void CbmStripHit::SetPhi (Double_t phi) inline
Definition at line 77 of file CbmStripHit.h.
View newest version in sPHENIX GitHub at line 77 of file CbmStripHit.h
References fPhi, and phi.
void CbmStripHit::SetU (Double_t u) inline
Definition at line 76 of file CbmStripHit.h.
View newest version in sPHENIX GitHub at line 76 of file CbmStripHit.h
References fU, and Acts::UnitConstants::u.
string CbmStripHit::ToString () const virtual
Inherited from CbmBaseHit.
Implements CbmBaseHit.
Definition at line 69 of file CbmStripHit.cxx.
View newest version in sPHENIX GitHub at line 69 of file CbmStripHit.cxx
References CbmBaseHit::GetAddress(), GetDphi(), GetDu(), CbmBaseHit::GetDz(), GetPhi(), CbmBaseHit::GetRefId(), GetU(), and CbmBaseHit::GetZ().
Member Data Documentation
Double_t CbmStripHit::fDphi private
strip rotation error [rad]
Definition at line 85 of file CbmStripHit.h.
View newest version in sPHENIX GitHub at line 85 of file CbmStripHit.h
Referenced by GetDphi(), and SetDphi().
Double_t CbmStripHit::fDu private
U error [cm].
Definition at line 83 of file CbmStripHit.h.
View newest version in sPHENIX GitHub at line 83 of file CbmStripHit.h
Referenced by GetDu(), and SetDu().
Double_t CbmStripHit::fPhi private
strip rotation angle [rad]
Definition at line 84 of file CbmStripHit.h.
View newest version in sPHENIX GitHub at line 84 of file CbmStripHit.h
Referenced by GetPhi(), and SetPhi().
Double_t CbmStripHit::fU private
U coordinate in the rotated c.s [cm].
Definition at line 82 of file CbmStripHit.h.
View newest version in sPHENIX GitHub at line 82 of file CbmStripHit.h
Referenced by GetU(), and SetU().
The documentation for this class was generated from the following files:
EicRoot/blob/master/cbmdata/CbmStripHit.h
EicRoot/blob/master/cbmdata/CbmStripHit.cxx