EIC Software: PndFieldCreator Class Reference
PndFieldCreator Class Reference
#include <EicRoot/blob/master/field/PndFieldCreator.h>
Public Member Functions
PndFieldCreator ()
virtual ~PndFieldCreator ()
virtual FairField * createFairField ()
virtual void SetParm ()
Public Member Functions inherited from FairFieldFactory
FairFieldFactory ()
virtual ~FairFieldFactory ()
Protected Attributes
PndFieldPar * fFieldPar
PndSolenoidPar * fSPar
PndDipolePar * fDPar
PndTransPar * fTPar
PndConstPar * fCPar
PndMultiFieldPar * fMPar
Protected Attributes inherited from FairFieldFactory
FairFieldFactory * fCreator
Private Member Functions
PndFieldCreator (const PndFieldCreator &L)
PndFieldCreator & operator= (const PndFieldCreator &)
ClassDef (PndFieldCreator, 1)
Additional Inherited Members
Static Public Member Functions inherited from FairFieldFactory
static FairFieldFactory * Instance ()
Protected Member Functions inherited from FairFieldFactory
ClassDef(FairFieldFactory,
1) private FairFieldFactory & operator= (const FairFieldFactory &)
Static Protected Attributes inherited from FairFieldFactory
static FairFieldFactory * fgRinstance = 0
Detailed Description
Definition at line 20 of file PndFieldCreator.h.
View newest version in sPHENIX GitHub at line 20 of file PndFieldCreator.h
Constructor & Destructor Documentation
PndFieldCreator::PndFieldCreator ()
Definition at line 32 of file PndFieldCreator.cxx.
View newest version in sPHENIX GitHub at line 32 of file PndFieldCreator.cxx
References FairFieldFactory::fCreator.
PndFieldCreator::~PndFieldCreator () virtual
Definition at line 45 of file PndFieldCreator.cxx.
View newest version in sPHENIX GitHub at line 45 of file PndFieldCreator.cxx
PndFieldCreator::PndFieldCreator (const PndFieldCreator & L) inline private
Definition at line 28 of file PndFieldCreator.h.
View newest version in sPHENIX GitHub at line 28 of file PndFieldCreator.h
Member Function Documentation
PndFieldCreator::ClassDef (PndFieldCreator , 1) private
FairField * PndFieldCreator::createFairField () virtual
Reimplemented from FairFieldFactory.
Definition at line 83 of file PndFieldCreator.cxx.
View newest version in sPHENIX GitHub at line 83 of file PndFieldCreator.cxx
References _EIC_MAGNETIC_FIELD_, PndMultiField::AddField(), fCPar, fDPar, fFieldPar, fMPar, fSPar, fTPar, FairRootManager::GetInFile(), PndMultiFieldPar::GetParArray(), PndFieldPar::GetType(), PndMapPar::GetType(), PndMultiField::Init(), and FairRootManager::Instance().
PndFieldCreator& PndFieldCreator::operator= (const PndFieldCreator &) inline private
Definition at line 29 of file PndFieldCreator.h.
View newest version in sPHENIX GitHub at line 29 of file PndFieldCreator.h
void PndFieldCreator::SetParm () virtual
Reimplemented from FairFieldFactory.
Definition at line 48 of file PndFieldCreator.cxx.
View newest version in sPHENIX GitHub at line 48 of file PndFieldCreator.cxx
References fCPar, fDPar, fFieldPar, fMPar, fSPar, fTPar, FairRuntimeDb::getContainer(), FairBaseParSet::GetContList(), FairRun::GetRuntimeDb(), and FairRun::Instance().
Member Data Documentation
PndConstPar* PndFieldCreator::fCPar protected
Definition at line 37 of file PndFieldCreator.h.
View newest version in sPHENIX GitHub at line 37 of file PndFieldCreator.h
Referenced by createFairField(), and SetParm().
PndDipolePar* PndFieldCreator::fDPar protected
Definition at line 35 of file PndFieldCreator.h.
View newest version in sPHENIX GitHub at line 35 of file PndFieldCreator.h
Referenced by createFairField(), and SetParm().
PndFieldPar* PndFieldCreator::fFieldPar protected
Definition at line 33 of file PndFieldCreator.h.
View newest version in sPHENIX GitHub at line 33 of file PndFieldCreator.h
Referenced by createFairField(), and SetParm().
PndMultiFieldPar* PndFieldCreator::fMPar protected
Definition at line 38 of file PndFieldCreator.h.
View newest version in sPHENIX GitHub at line 38 of file PndFieldCreator.h
Referenced by createFairField(), and SetParm().
PndSolenoidPar* PndFieldCreator::fSPar protected
Definition at line 34 of file PndFieldCreator.h.
View newest version in sPHENIX GitHub at line 34 of file PndFieldCreator.h
Referenced by createFairField(), and SetParm().
PndTransPar* PndFieldCreator::fTPar protected
Definition at line 36 of file PndFieldCreator.h.
View newest version in sPHENIX GitHub at line 36 of file PndFieldCreator.h
Referenced by createFairField(), and SetParm().
The documentation for this class was generated from the following files:
EicRoot/blob/master/field/PndFieldCreator.h
EicRoot/blob/master/field/PndFieldCreator.cxx