EIC Software: EicRoot/blob/master/geometry/rad_length.C File Reference
rad_length.C File Reference
Macros
#define _ETA_MODE_
#define _THETA_MIN_ 2.0
#define _ETA_MAX_ 4.0
#define _BIN_NUM_ 200
#define _YAXIS_MAX_ 0.12
Functions
TString RemoveCrap (TString &path)
void rad_length ()
Variables
struct {
char * name
int color
} dets []
Macro Definition Documentation
#define _BIN_NUM_ 200
Definition at line 12 of file rad_length.C.
View newest version in sPHENIX GitHub at line 12 of file rad_length.C
Referenced by rad_length().
#define _ETA_MAX_ 4.0
Definition at line 10 of file rad_length.C.
View newest version in sPHENIX GitHub at line 10 of file rad_length.C
Referenced by rad_length().
#define _ETA_MODE_
Definition at line 6 of file rad_length.C.
View newest version in sPHENIX GitHub at line 6 of file rad_length.C
#define _THETA_MIN_ 2.0
Definition at line 9 of file rad_length.C.
View newest version in sPHENIX GitHub at line 9 of file rad_length.C
Referenced by rad_length().
#define _YAXIS_MAX_ 0.12
Definition at line 14 of file rad_length.C.
View newest version in sPHENIX GitHub at line 14 of file rad_length.C
Referenced by rad_length().
Function Documentation
void rad_length ()
Definition at line 55 of file rad_length.C.
View newest version in sPHENIX GitHub at line 55 of file rad_length.C
References _BIN_NUM_, _ETA_MAX_, _THETA_MIN_, _YAXIS_MAX_, c1, color, dets, Acts::VectorHelpers::eta(), Acts::UnitConstants::h, material(), name, printf(), RemoveCrap(), theta(), and thickness.
TString RemoveCrap (TString & path)
Definition at line 35 of file rad_length.C.
View newest version in sPHENIX GitHub at line 35 of file rad_length.C
References Acts::Test::skip.
Variable Documentation
int color
Definition at line 18 of file rad_length.C.
View newest version in sPHENIX GitHub at line 18 of file rad_length.C
struct { ... } dets[]
Initial value:
= {
  {"cave",          kMagenta},
  {"pipe",          kGray},
  {"vst",           kYellow},
  {"fst",           kGreen},
  {"bst",           kGreen},
  {"TPC/TpcIfc",    kBlue},
  {"TPC/TpcGas",    kCyan},
}
char* name
Definition at line 17 of file rad_length.C.
View newest version in sPHENIX GitHub at line 17 of file rad_length.C