EIC Software: PHG4TTLDetector Class Reference
PHG4TTLDetector Class Reference
#include <fun4all_eicdetectors/blob/master/simulation/g4simulation/g4ttl/PHG4TTLDetector.h>
Public Member Functions
PHG4TTLDetector (PHG4Subsystem *subsys, PHCompositeNode *Node, PHParameters *parameters, const std::string &dnam)
constructor
~PHG4TTLDetector (void) override
destructor
void ConstructMe (G4LogicalVolume *world) override
construct
void SuperDetector (const std::string &name)
const std::string SuperDetector () const
void SetSteppingAction (PHG4TTLSteppingAction *stpact)
void OverlapCheck (bool check=true) override
volume accessors
bool IsInSectorActive (G4VPhysicalVolume *physvol)
Public Member Functions inherited from PHG4Detector
PHG4Detector ()=delete
constructor
PHG4Detector (PHG4Subsystem *subsys, PHCompositeNode *Node, const std::string &nam)
virtual ~PHG4Detector (void)
destructor
virtual void Construct (G4LogicalVolume *world) final
construct method
virtual void PostConstruction ()
Optional PostConstruction call after all geometry is constructed.
virtual void Verbosity (const int v)
virtual int Verbosity () const
virtual G4UserSteppingAction * GetSteppingAction ()
virtual std::string GetName () const
virtual bool OverlapCheck () const
virtual void Print (const std::string &="ALL") const
virtual int DisplayVolume (G4VSolid *volume, G4LogicalVolume *logvol, G4RotationMatrix *rotm=nullptr)
virtual int DisplayVolume (G4LogicalVolume *checksolid, G4LogicalVolume *logvol, G4RotationMatrix *rotm=nullptr)
virtual PHCompositeNode * topNode ()
virtual PHG4Subsystem * GetMySubsystem ()
Public Attributes
std::string name_base
Protected Types
typedef std::map< G4String,
G4LogicalVolume * > map_log_vol_t
typedef std::pair< G4String,
G4int > phy_vol_idx_t
typedef std::map
< phy_vol_idx_t, G4PVPlacement * > map_phy_vol_t
Protected Member Functions
G4LogicalVolume * RegisterLogicalVolume (G4LogicalVolume *)
G4VSolid * Construct_Sectors_Plane (const std::string &name, const double start_z, const double thickness, G4VSolid *SecConeBoundary_Det)
G4PVPlacement * RegisterPhysicalVolume (G4PVPlacement *v, const bool active=false)
void BuildForwardTTL (G4LogicalVolume *world)
void BuildBarrelTTL (G4LogicalVolume *world)
Protected Attributes
bool overlapcheck_sector
map_log_vol_t map_log_vol
map_phy_vol_t map_phy_vol
map_phy_vol_t map_active_phy_vol
all physics volume
Private Attributes
PHG4TTLDisplayAction * m_DisplayAction
PHG4TTLSteppingAction * m_SteppingAction
int m_Verbosity
std::string superdetector
PHParameters * m_Params = nullptr
Additional Inherited Members
Static Public Member Functions inherited from PHG4Detector
static G4Material * GetDetectorMaterial (const std::string &name, const bool quit=true)
static G4Element * GetDetectorElement (const std::string &name, const bool quit=true)
Detailed Description
Definition at line 45 of file PHG4TTLDetector.h.
View newest version in sPHENIX GitHub at line 45 of file PHG4TTLDetector.h
Member Typedef Documentation
typedef std::map<G4String, G4LogicalVolume *> PHG4TTLDetector::map_log_vol_t protected
Definition at line 105 of file PHG4TTLDetector.h.
View newest version in sPHENIX GitHub at line 105 of file PHG4TTLDetector.h
typedef std::map<phy_vol_idx_t, G4PVPlacement *> PHG4TTLDetector::map_phy_vol_t protected
Definition at line 115 of file PHG4TTLDetector.h.
View newest version in sPHENIX GitHub at line 115 of file PHG4TTLDetector.h
typedef std::pair<G4String, G4int> PHG4TTLDetector::phy_vol_idx_t protected
Definition at line 114 of file PHG4TTLDetector.h.
View newest version in sPHENIX GitHub at line 114 of file PHG4TTLDetector.h
Constructor & Destructor Documentation
PHG4TTLDetector::PHG4TTLDetector (PHG4Subsystem * subsys, PHCompositeNode * Node, PHParameters * parameters, const std::string & dnam)
constructor
Definition at line 42 of file PHG4TTLDetector.cc.
View newest version in sPHENIX GitHub at line 42 of file PHG4TTLDetector.cc
PHG4TTLDetector::~PHG4TTLDetector (void) inline override
destructor
Definition at line 52 of file PHG4TTLDetector.h.
View newest version in sPHENIX GitHub at line 52 of file PHG4TTLDetector.h
Member Function Documentation
void PHG4TTLDetector::BuildBarrelTTL (G4LogicalVolume * world) protected
Definition at line 81 of file PHG4TTLDetector.cc.
View newest version in sPHENIX GitHub at line 81 of file PHG4TTLDetector.cc
References PHG4TTLDisplayAction::AddVolume(), Acts::UnitConstants::cm, Acts::UnitConstants::cm3, cos(), g(), PHParameters::get_double_param(), PHG4Detector::GetDetectorMaterial(), m_DisplayAction, m_Params, M_PI, m_SteppingAction, Acts::UnitConstants::mm, overlapcheck_sector, G4DRICH::place_z, RegisterLogicalVolume(), RegisterPhysicalVolume(), PHG4TTLSteppingAction::SetIsForwardTTL(), PHG4TTLSteppingAction::SetNPhiModules(), nlohmann::to_string(), z, and G4DIRC::z_start.
Referenced by ConstructMe().
void PHG4TTLDetector::BuildForwardTTL (G4LogicalVolume * world) protected
Definition at line 569 of file PHG4TTLDetector.cc.
View newest version in sPHENIX GitHub at line 569 of file PHG4TTLDetector.cc
References kdfinder::abs(), PHG4TTLDisplayAction::AddVolume(), Acts::UnitConstants::cm, Acts::UnitConstants::cm3, g(), PHParameters::get_double_param(), PHG4Detector::GetDetectorMaterial(), m_DisplayAction, m_Params, M_PI, m_SteppingAction, Acts::UnitConstants::mm, name_base, overlapcheck_sector, pi, RegisterLogicalVolume(), RegisterPhysicalVolume(), PHG4TTLSteppingAction::SetIsForwardTTL(), PHG4TTLSteppingAction::SetNPhiModules(), PHG4TTLSteppingAction::SetZPositionFwd(), nlohmann::to_string(), z, and G4DIRC::z_start.
Referenced by ConstructMe().
G4VSolid* PHG4TTLDetector::Construct_Sectors_Plane (const std::string & name, const double start_z, const double thickness, G4VSolid * SecConeBoundary_Det) protected
void PHG4TTLDetector::ConstructMe (G4LogicalVolume * world) override virtual
construct
Implements PHG4Detector.
Definition at line 69 of file PHG4TTLDetector.cc.
View newest version in sPHENIX GitHub at line 69 of file PHG4TTLDetector.cc
References BuildBarrelTTL(), BuildForwardTTL(), PHParameters::get_int_param(), and m_Params.
bool PHG4TTLDetector::IsInSectorActive (G4VPhysicalVolume * physvol)
Definition at line 54 of file PHG4TTLDetector.cc.
View newest version in sPHENIX GitHub at line 54 of file PHG4TTLDetector.cc
References it, and map_active_phy_vol.
Referenced by PHG4TTLSteppingAction::UserSteppingAction().
void PHG4TTLDetector::OverlapCheck (bool check = true) inline override virtual
Reimplemented from PHG4Detector.
Definition at line 74 of file PHG4TTLDetector.h.
View newest version in sPHENIX GitHub at line 74 of file PHG4TTLDetector.h
References overlapcheck_sector.
Referenced by PHG4TTLSubsystem::InitRunSubsystem().
G4LogicalVolume * PHG4TTLDetector::RegisterLogicalVolume (G4LogicalVolume * v) protected
Definition at line 1086 of file PHG4TTLDetector.cc.
View newest version in sPHENIX GitHub at line 1086 of file PHG4TTLDetector.cc
References map_log_vol, and v.
Referenced by BuildBarrelTTL(), and BuildForwardTTL().
G4PVPlacement * PHG4TTLDetector::RegisterPhysicalVolume (G4PVPlacement * v, const bool active = false) protected
Definition at line 1106 of file PHG4TTLDetector.cc.
View newest version in sPHENIX GitHub at line 1106 of file PHG4TTLDetector.cc
References map_active_phy_vol, map_phy_vol, and v.
Referenced by BuildBarrelTTL(), and BuildForwardTTL().
void PHG4TTLDetector::SetSteppingAction (PHG4TTLSteppingAction * stpact) inline
Definition at line 66 of file PHG4TTLDetector.h.
View newest version in sPHENIX GitHub at line 66 of file PHG4TTLDetector.h
References m_SteppingAction.
Referenced by PHG4TTLSubsystem::InitRunSubsystem().
void PHG4TTLDetector::SuperDetector (const std::string & name) inline
Definition at line 64 of file PHG4TTLDetector.h.
View newest version in sPHENIX GitHub at line 64 of file PHG4TTLDetector.h
References name, and superdetector.
Referenced by PHG4TTLSubsystem::InitRunSubsystem(), and PHG4TTLSteppingAction::SetInterfacePointers().
const std::string PHG4TTLDetector::SuperDetector () const inline
Definition at line 65 of file PHG4TTLDetector.h.
View newest version in sPHENIX GitHub at line 65 of file PHG4TTLDetector.h
References superdetector.
Member Data Documentation
PHG4TTLDisplayAction* PHG4TTLDetector::m_DisplayAction private
Definition at line 87 of file PHG4TTLDetector.h.
View newest version in sPHENIX GitHub at line 87 of file PHG4TTLDetector.h
Referenced by BuildBarrelTTL(), and BuildForwardTTL().
PHParameters* PHG4TTLDetector::m_Params = nullptr private
Definition at line 91 of file PHG4TTLDetector.h.
View newest version in sPHENIX GitHub at line 91 of file PHG4TTLDetector.h
Referenced by BuildBarrelTTL(), BuildForwardTTL(), and ConstructMe().
PHG4TTLSteppingAction* PHG4TTLDetector::m_SteppingAction private
Definition at line 88 of file PHG4TTLDetector.h.
View newest version in sPHENIX GitHub at line 88 of file PHG4TTLDetector.h
Referenced by BuildBarrelTTL(), BuildForwardTTL(), and SetSteppingAction().
int PHG4TTLDetector::m_Verbosity private
Definition at line 89 of file PHG4TTLDetector.h.
View newest version in sPHENIX GitHub at line 89 of file PHG4TTLDetector.h
map_phy_vol_t PHG4TTLDetector::map_active_phy_vol protected
all physics volume
Definition at line 117 of file PHG4TTLDetector.h.
View newest version in sPHENIX GitHub at line 117 of file PHG4TTLDetector.h
Referenced by IsInSectorActive(), and RegisterPhysicalVolume().
map_log_vol_t PHG4TTLDetector::map_log_vol protected
Definition at line 106 of file PHG4TTLDetector.h.
View newest version in sPHENIX GitHub at line 106 of file PHG4TTLDetector.h
Referenced by RegisterLogicalVolume().
map_phy_vol_t PHG4TTLDetector::map_phy_vol protected
Definition at line 116 of file PHG4TTLDetector.h.
View newest version in sPHENIX GitHub at line 116 of file PHG4TTLDetector.h
Referenced by RegisterPhysicalVolume().
std::string PHG4TTLDetector::name_base
Definition at line 84 of file PHG4TTLDetector.h.
View newest version in sPHENIX GitHub at line 84 of file PHG4TTLDetector.h
Referenced by BuildForwardTTL().
bool PHG4TTLDetector::overlapcheck_sector protected
Definition at line 96 of file PHG4TTLDetector.h.
View newest version in sPHENIX GitHub at line 96 of file PHG4TTLDetector.h
Referenced by BuildBarrelTTL(), BuildForwardTTL(), and OverlapCheck().
std::string PHG4TTLDetector::superdetector private
Definition at line 90 of file PHG4TTLDetector.h.
View newest version in sPHENIX GitHub at line 90 of file PHG4TTLDetector.h
Referenced by SuperDetector().
The documentation for this class was generated from the following files:
fun4all_eicdetectors/blob/master/simulation/g4simulation/g4ttl/PHG4TTLDetector.h
fun4all_eicdetectors/blob/master/simulation/g4simulation/g4ttl/PHG4TTLDetector.cc