EIC Software: EicStlKey Class Reference
EicStlKey Class Reference
Naive multi-float-value key used for ordering objects in CAD-related classes;.
#include <EicRoot/blob/master/eic/cad/EicStlKey.h>
Public Member Functions
EicStlKey (unsigned dim, const double *ptr)
~EicStlKey ()
unsigned GetDim () const
const double * GetData () const
Private Attributes
unsigned mDim
double * mData
Detailed Description
Naive multi-float-value key used for ordering objects in CAD-related classes;.
Basically just packs coordinates of N related 3D vertices into double[3*N] arrays and uses memcmp() call for comparisons; FIXME: consider to use hash tables (?);
Definition at line 16 of file EicStlKey.h.
View newest version in sPHENIX GitHub at line 16 of file EicStlKey.h
Constructor & Destructor Documentation
EicStlKey::EicStlKey (unsigned dim, const double * ptr) inline
Main constructor
Parameters
dim full array dimension (so 3N for an object identified by N 3D points)
ptr pointer to respective double[dim] data array
Definition at line 22 of file EicStlKey.h.
View newest version in sPHENIX GitHub at line 22 of file EicStlKey.h
References Acts::Test::dim, mData, and mDim.
EicStlKey::~EicStlKey () inline
Destructor; just need to clean up the storage
Definition at line 29 of file EicStlKey.h.
View newest version in sPHENIX GitHub at line 29 of file EicStlKey.h
References mData.
Member Function Documentation
const double* EicStlKey::GetData () const inline
Access method; returns read-only mData pointer
Definition at line 36 of file EicStlKey.h.
View newest version in sPHENIX GitHub at line 36 of file EicStlKey.h
Referenced by EicStlFactory::_ConstructGeometry(), EicStlKeyCompare(), EicStlKeyEqual(), EicCompositeShape::LocalFillBuffer3D(), EicStlMediaGroup::MergeDegenerateVertices(), EicStlFactory::PreAllocateFacet(), EicStlVertex::Print(), and EicStlMediaGroup::SplitIntoAssemblies().
unsigned EicStlKey::GetDim () const inline
Access method; returns mDim
Definition at line 33 of file EicStlKey.h.
View newest version in sPHENIX GitHub at line 33 of file EicStlKey.h
References mDim.
Referenced by EicStlKeyCompare(), and EicStlKeyEqual().
Member Data Documentation
double* EicStlKey::mData private
Array of floating point values
Definition at line 43 of file EicStlKey.h.
View newest version in sPHENIX GitHub at line 43 of file EicStlKey.h
Referenced by EicStlKey(), and ~EicStlKey().
unsigned EicStlKey::mDim private
Number of floating point values defining this key
Definition at line 36 of file EicStlKey.h.
View newest version in sPHENIX GitHub at line 36 of file EicStlKey.h
Referenced by EicStlKey(), and GetDim().
The documentation for this class was generated from the following file:
EicRoot/blob/master/eic/cad/EicStlKey.h