EIC Software: FairDbTableProxy Class Reference
FairDbTableProxy Class Reference
#include <EicRoot/blob/master/dbase/dbInterface/FairDbTableProxy.h>
Public Member Functions
const FairDbProxy & GetDBProxy () const
FairDbMultConnector & GetMultConnector ()
const FairDbTableMetaData & GetMetaData () const
const FairDbTableMetaData & GetMetaValid () const
string GetRowName () const
string GetTableName () const
FairDbCache * GetCache ()
const FairDbResult * Query (const ValContext &vc, const FairDb::Task &task, Bool_t findFullTimeWindow=true)
const FairDbResult * Query (const string &context, const FairDb::Task &task, const string &data, const string &fillOpts)
const FairDbResult * Query (UInt_t seqNo, UInt_t dbNo)
const FairDbResult * Query (const FairDbValidityRec &vrec, Bool_t canReuse=kTRUE)
ValTimeStamp QueryOverlayCreationDate (const FairDbValidityRec &vrec, UInt_t dbNo)
void RefreshMetaData ()
void SetSqlCondition (const string &sql)
Bool_t TableExists () const
Protected Member Functions
FairDbTableProxy (FairDbMultConnector *cascader, const string &tableName, const string &vldSuffix, const FairDbTableRow *tableRow)
virtual ~FairDbTableProxy ()
Private Member Functions
FairDbTableProxy (const FairDbTableProxy &)
FairDbTableProxy & operator= (const FairDbTableProxy &)
Bool_t CanReadL2Cache () const
Bool_t CanWriteL2Cache () const
Bool_t RestoreFromL2Cache (const FairDbValidityRecBuilder &builder)
Bool_t SaveToL2Cache (const string &name, FairDbResult &res)
Private Attributes
FairDbMultConnector * fMultConnector
FairDbTableMetaData fMetaData
FairDbTableMetaData fMetaValid
Bool_t fCanL2Cache
FairDbCache * fCache
FairDbProxy fDBProxy
Bool_t fExists
string fTableName
FairDbTableRow * fTableRow
Friends
class FairDbTableProxyRegistry
Detailed Description
Definition at line 23 of file FairDbTableProxy.h.
View newest version in sPHENIX GitHub at line 23 of file FairDbTableProxy.h
Constructor & Destructor Documentation
FairDbTableProxy::FairDbTableProxy (FairDbMultConnector * cascader, const string & tableName, const string & vldSuffix, const FairDbTableRow * tableRow) protected
FairDbTableProxy::~FairDbTableProxy () protected virtual
Definition at line 48 of file FairDbTableProxy.cxx.
View newest version in sPHENIX GitHub at line 48 of file FairDbTableProxy.cxx
References fCache, and fTableRow.
FairDbTableProxy::FairDbTableProxy (const FairDbTableProxy &) private
Member Function Documentation
Bool_t FairDbTableProxy::CanReadL2Cache () const private
Definition at line 55 of file FairDbTableProxy.cxx.
View newest version in sPHENIX GitHub at line 55 of file FairDbTableProxy.cxx
References FairDbBinaryFile::CanReadL2Cache(), and fCanL2Cache.
Referenced by Query(), and RestoreFromL2Cache().
Bool_t FairDbTableProxy::CanWriteL2Cache () const private
Definition at line 60 of file FairDbTableProxy.cxx.
View newest version in sPHENIX GitHub at line 60 of file FairDbTableProxy.cxx
References FairDbBinaryFile::CanWriteL2Cache(), and fCanL2Cache.
Referenced by SaveToL2Cache().
FairDbCache* FairDbTableProxy::GetCache () inline
Definition at line 40 of file FairDbTableProxy.h.
View newest version in sPHENIX GitHub at line 40 of file FairDbTableProxy.h
References fCache.
Referenced by FairDbTableProxyRegistry::PurgeCaches().
const FairDbProxy& FairDbTableProxy::GetDBProxy () const inline
Definition at line 31 of file FairDbTableProxy.h.
View newest version in sPHENIX GitHub at line 31 of file FairDbTableProxy.h
References fDBProxy.
Referenced by ClassImp(), FairDbSqlValPacket::FairDbSqlValPacket(), and FairDbSqlValPacket::Store().
const FairDbTableMetaData& FairDbTableProxy::GetMetaData () const inline
Definition at line 33 of file FairDbTableProxy.h.
View newest version in sPHENIX GitHub at line 33 of file FairDbTableProxy.h
References fMetaData.
Referenced by FairDbSqlValPacket::AddRow(), FairDbTableProxyRegistry::HasRowCounter(), FairDbSqlValPacket::SetMetaData(), and FairDbSqlValPacket::Store().
const FairDbTableMetaData& FairDbTableProxy::GetMetaValid () const inline
Definition at line 34 of file FairDbTableProxy.h.
View newest version in sPHENIX GitHub at line 34 of file FairDbTableProxy.h
References fMetaValid.
Referenced by FairDbSqlValPacket::AddRow(), FairDbSqlValPacket::Recreate(), and FairDbSqlValPacket::SetMetaData().
FairDbMultConnector& FairDbTableProxy::GetMultConnector () inline
Definition at line 32 of file FairDbTableProxy.h.
View newest version in sPHENIX GitHub at line 32 of file FairDbTableProxy.h
References fMultConnector.
Referenced by FairDbLogEntry::Write().
string FairDbTableProxy::GetRowName () const inline
Definition at line 35 of file FairDbTableProxy.h.
View newest version in sPHENIX GitHub at line 35 of file FairDbTableProxy.h
References fTableRow.
Referenced by RestoreFromL2Cache(), and SaveToL2Cache().
string FairDbTableProxy::GetTableName () const inline
Definition at line 38 of file FairDbTableProxy.h.
View newest version in sPHENIX GitHub at line 38 of file FairDbTableProxy.h
References fTableName.
Referenced by FairDbSqlValPacket::AddRow(), FairDbTableProxyRegistry::ApplySqlCondition(), Query(), FairDbTableProxyRegistry::RefreshMetaData(), RestoreFromL2Cache(), SaveToL2Cache(), and FairDbConfigStream::Write().
FairDbTableProxy& FairDbTableProxy::operator= (const FairDbTableProxy &) private
const FairDbResult * FairDbTableProxy::Query (const ValContext & vc, const FairDb::Task & task, Bool_t findFullTimeWindow = true)
Definition at line 65 of file FairDbTableProxy.cxx.
View newest version in sPHENIX GitHub at line 65 of file FairDbTableProxy.cxx
References FairDbCache::Adopt(), CanReadL2Cache(), FairDbResult::CaptureExceptionLog(), Acts::UnitConstants::cm, fCache, fDBProxy, fMultConnector, fTableName, fTableRow, FairDbExceptionLog::GetGELog(), FairDbValidityRecBuilder::GetL2CacheName(), FairDbValidityRecBuilder::GetNumValidityRec(), FairDbValidityRecBuilder::GetValidityRec(), FairDbValidityRec::IsGap(), FairDbValidityRecBuilder::NonAggregated(), RestoreFromL2Cache(), SaveToL2Cache(), FairDbCache::Search(), and FairDbExceptionLog::Size().
Referenced by Query().
const FairDbResult * FairDbTableProxy::Query (const string & context, const FairDb::Task & task, const string & data, const string & fillOpts)
Definition at line 127 of file FairDbTableProxy.cxx.
View newest version in sPHENIX GitHub at line 127 of file FairDbTableProxy.cxx
References FairDbCache::Adopt(), FairDbResult::CaptureExceptionLog(), Acts::UnitConstants::cm, fCache, fDBProxy, fMultConnector, fTableName, fTableRow, FairDbExceptionLog::GetGELog(), FairDb::kAnyTask, FairDbCache::Search(), and FairDbExceptionLog::Size().
const FairDbResult * FairDbTableProxy::Query (UInt_t seqNo, UInt_t dbNo)
Definition at line 173 of file FairDbTableProxy.cxx.
View newest version in sPHENIX GitHub at line 173 of file FairDbTableProxy.cxx
References FairDbCache::Adopt(), FairDbResult::CaptureExceptionLog(), Acts::UnitConstants::cm, fCache, fDBProxy, fMultConnector, FairDbExceptionLog::GetGELog(), FairDbResultNonAgg::GetNumRows(), FairDbResultNonAgg::GetTableRow(), Query(), FairDbProxy::QueryValidity(), and FairDbExceptionLog::Size().
const FairDbResult * FairDbTableProxy::Query (const FairDbValidityRec & vrec, Bool_t canReuse = kTRUE)
Definition at line 210 of file FairDbTableProxy.cxx.
View newest version in sPHENIX GitHub at line 210 of file FairDbTableProxy.cxx
References FairDbCache::Adopt(), FairDbResult::CaptureExceptionLog(), Acts::UnitConstants::cm, fCache, fDBProxy, fMultConnector, fTableRow, FairDbValidityRec::GetDbNo(), FairDbExceptionLog::GetGELog(), FairDbValidityRec::GetL2CacheName(), FairDbValidityRec::GetSeqNo(), GetTableName(), FairDbValidityRec::GetTableProxy(), FairDbProxy::QuerySeqNo(), RestoreFromL2Cache(), SaveToL2Cache(), FairDbCache::Search(), FairDbResult::SetCanReuse(), and FairDbExceptionLog::Size().
ValTimeStamp FairDbTableProxy::QueryOverlayCreationDate (const FairDbValidityRec & vrec, UInt_t dbNo)
Definition at line 286 of file FairDbTableProxy.cxx.
View newest version in sPHENIX GitHub at line 286 of file FairDbTableProxy.cxx
References Acts::UnitConstants::cm, fDBProxy, fMultConnector, FairDbValidityRec::GetAggregateNo(), ValTimeStamp::GetSec(), FairDbValidityRec::GetTask(), and FairDbValidityRec::GetValRange().
void FairDbTableProxy::RefreshMetaData ()
Definition at line 273 of file FairDbTableProxy.cxx.
View newest version in sPHENIX GitHub at line 273 of file FairDbTableProxy.cxx
References fDBProxy, fMetaData, fMetaValid, and FairDbProxy::StoreMetaData().
Referenced by FairDbTableProxyRegistry::RefreshMetaData().
Bool_t FairDbTableProxy::RestoreFromL2Cache (const FairDbValidityRecBuilder & builder) private
Definition at line 321 of file FairDbTableProxy.cxx.
View newest version in sPHENIX GitHub at line 321 of file FairDbTableProxy.cxx
References FairDbCache::Adopt(), CanReadL2Cache(), fCache, FairDbBinaryFile::GetFileName(), FairDbValidityRecBuilder::GetL2CacheName(), GetRowName(), FairDbValidityRec::GetSeqNo(), GetTableName(), FairDbValidityRecBuilder::GetValidityRecFromSeqNo(), FairDbTimerManager::gTimerManager, name, FairDbTimerManager::RecMainQuery(), and FairDbCache::Search().
Referenced by Query().
Bool_t FairDbTableProxy::SaveToL2Cache (const string & name, FairDbResult & res) private
Definition at line 389 of file FairDbTableProxy.cxx.
View newest version in sPHENIX GitHub at line 389 of file FairDbTableProxy.cxx
References FairDbResult::CanSave(), CanWriteL2Cache(), FairDbResult::GetNumRows(), GetRowName(), GetTableName(), FairDbTimerManager::gTimerManager, FairDbTimerManager::RecMainQuery(), and FairDbResult::ResultsFromDb().
Referenced by Query().
void FairDbTableProxy::SetSqlCondition (const string & sql)
Definition at line 423 of file FairDbTableProxy.cxx.
View newest version in sPHENIX GitHub at line 423 of file FairDbTableProxy.cxx
References fDBProxy, and FairDbProxy::SetSqlCondition().
Referenced by FairDbTableProxyRegistry::ApplySqlCondition().
Bool_t FairDbTableProxy::TableExists () const inline
Definition at line 55 of file FairDbTableProxy.h.
View newest version in sPHENIX GitHub at line 55 of file FairDbTableProxy.h
References fExists.
Friends And Related Function Documentation
friend class FairDbTableProxyRegistry friend
Definition at line 26 of file FairDbTableProxy.h.
View newest version in sPHENIX GitHub at line 26 of file FairDbTableProxy.h
Member Data Documentation
FairDbCache* FairDbTableProxy::fCache private
Definition at line 84 of file FairDbTableProxy.h.
View newest version in sPHENIX GitHub at line 84 of file FairDbTableProxy.h
Referenced by GetCache(), Query(), RestoreFromL2Cache(), and ~FairDbTableProxy().
Bool_t FairDbTableProxy::fCanL2Cache private
Definition at line 83 of file FairDbTableProxy.h.
View newest version in sPHENIX GitHub at line 83 of file FairDbTableProxy.h
Referenced by CanReadL2Cache(), and CanWriteL2Cache().
FairDbProxy FairDbTableProxy::fDBProxy private
Definition at line 85 of file FairDbTableProxy.h.
View newest version in sPHENIX GitHub at line 85 of file FairDbTableProxy.h
Referenced by GetDBProxy(), Query(), QueryOverlayCreationDate(), RefreshMetaData(), and SetSqlCondition().
Bool_t FairDbTableProxy::fExists private
Definition at line 86 of file FairDbTableProxy.h.
View newest version in sPHENIX GitHub at line 86 of file FairDbTableProxy.h
Referenced by TableExists().
FairDbTableMetaData FairDbTableProxy::fMetaData private
Definition at line 81 of file FairDbTableProxy.h.
View newest version in sPHENIX GitHub at line 81 of file FairDbTableProxy.h
Referenced by GetMetaData(), and RefreshMetaData().
FairDbTableMetaData FairDbTableProxy::fMetaValid private
Definition at line 82 of file FairDbTableProxy.h.
View newest version in sPHENIX GitHub at line 82 of file FairDbTableProxy.h
Referenced by GetMetaValid(), and RefreshMetaData().
FairDbMultConnector* FairDbTableProxy::fMultConnector private
Definition at line 80 of file FairDbTableProxy.h.
View newest version in sPHENIX GitHub at line 80 of file FairDbTableProxy.h
Referenced by GetMultConnector(), Query(), and QueryOverlayCreationDate().
string FairDbTableProxy::fTableName private
Definition at line 87 of file FairDbTableProxy.h.
View newest version in sPHENIX GitHub at line 87 of file FairDbTableProxy.h
Referenced by GetTableName(), and Query().
FairDbTableRow* FairDbTableProxy::fTableRow private
Definition at line 88 of file FairDbTableProxy.h.
View newest version in sPHENIX GitHub at line 88 of file FairDbTableProxy.h
Referenced by GetRowName(), Query(), and ~FairDbTableProxy().
The documentation for this class was generated from the following files:
EicRoot/blob/master/dbase/dbInterface/FairDbTableProxy.h
EicRoot/blob/master/dbase/dbInterface/FairDbTableProxy.cxx