EIC Software: FairMCPoint Class Reference
FairMCPoint Class Reference abstract
#include <EicRoot/blob/master/base/FairMCPoint.h>
Public Member Functions
FairMCPoint ()
FairMCPoint (Int_t trackID, Int_t detID, TVector3 pos, TVector3 mom, Double_t tof, Double_t length, Double_t eLoss, UInt_t EventId=0)
virtual ~FairMCPoint ()
UInt_t GetEventID () const
Int_t GetTrackID () const
event identifier
Double_t GetPx () const
Double_t GetPy () const
Double_t GetPz () const
Double_t GetTime () const
Double_t GetLength () const
Double_t GetEnergyLoss () const
void Momentum (TVector3 &mom)
Int_t GetDetectorID () const
Double_t GetX () const
Double_t GetY () const
Double_t GetZ () const
void Position (TVector3 &pos) const
void SetEventID (UInt_t eventId)
virtual void SetTrackID (Int_t id)
void SetTime (Double_t time)
void SetLength (Double_t length)
void SetEnergyLoss (Double_t eLoss)
void SetMomentum (const TVector3 &mom)
void SetDetectorID (Int_t detID)
void SetX (Double_t x)
void SetY (Double_t y)
void SetZ (Double_t z)
void SetXYZ (Double_t x, Double_t y, Double_t z)
void SetPosition (const TVector3 &pos)
virtual void Print (const Option_t *opt=0) const =0
Public Member Functions inherited from FairMultiLinkedData
FairMultiLinkedData ()
Default constructor.
FairMultiLinkedData (std::set< FairLink > links, Bool_t persistanceCheck=kTRUE)
Constructor.
FairMultiLinkedData (TString dataType, std::vector< Int_t > links, Int_t fileId=-1, Int_t evtId=-1, Bool_t persistanceCheck=kTRUE, Bool_t bypass=kFALSE, Float_t mult=1.0)
Constructor.
FairMultiLinkedData (Int_t dataType, std::vector< Int_t > links, Int_t fileId=-1, Int_t evtId=-1, Bool_t persistanceCheck=kTRUE, Bool_t bypass=kFALSE, Float_t mult=1.0)
Constructor.
virtual ~FairMultiLinkedData ()
virtual std::set< FairLink > GetLinks () const
returns stored links as FairLinks
virtual Int_t GetNLinks () const
returns the number of stored links
virtual FairLink GetLink (Int_t pos) const
returns the FairLink at the given position
virtual FairMultiLinkedData GetLinksWithType (Int_t type) const
Gives you a list of links which contain the given type.
TObject * GetData (FairLink &myLink)
Get the TObject the Link is pointing to.
virtual Int_t GetDefaultType ()
Bool_t GetPersistanceCheck ()
Returns the value of PersistanceCheck.
Int_t GetVerbose ()
Returns the verbosity level.
virtual void SetDefaultType (Int_t type)
virtual void SetPersistanceCheck (Bool_t check)
Controls if a persistance check of a link is done or not.
virtual void SetVerbose (Int_t level)
Sets the verbosity level.
virtual void SetLinks (FairMultiLinkedData links, Float_t mult=1.0)
Sets the links as vector of FairLink.
virtual void SetLink (FairLink link, Bool_t bypass=kFALSE, Float_t mult=1.0)
Sets the Links with a single FairLink.
virtual void AddLinks (FairMultiLinkedData links, Float_t mult=1.0)
Adds a List of FairLinks (FairMultiLinkedData) to fLinks.
virtual void AddLink (FairLink link, Bool_t bypass=kFALSE, Float_t mult=1.0)
Adds a FairLink link at the end of fLinks. If multi is kTRUE a link is allowed more than once otherwise it is stored only once.
virtual void InsertLink (FairLink link)
Inserts a link into the list of links without persistance checking.
virtual void AddAllWeights (Double_t weight)
Adds weight to all Links.
virtual void SetAllWeights (Double_t weight)
Sets a common weight for Links.
virtual void MultiplyAllWeights (Double_t weight)
Multiplies all Links with weight.
virtual Bool_t IsLinkInList (FairLink link)
Test if a given link is in fLinks.
virtual Bool_t IsLinkInList (Int_t type, Int_t index)
Same as IsLinkInList(FairLink) just with type and index given separately.
virtual Int_t LinkPosInList (FairLink link)
returns position of link in fLinks. If it is not in the list -1 is returned
virtual Int_t LinkPosInList (Int_t type, Int_t index)
Same as LinkPosInList(FairLink)
virtual void DeleteLink (FairLink link)
Deletes a link ouf of fLinks.
virtual void DeleteLink (Int_t type, Int_t index)
Deletes a link ouf of fLinks.
virtual void Reset ()
virtual void ResetLinks ()
Clears fLinks.
void Print (std::ostream &out=std::cout) const
Output.
Protected Attributes
Int_t fTrackID
Track index.
UInt_t fEventId
MC Event id.
Double32_t fPx
Double32_t fPy
Double32_t fPz
Momentum components [GeV].
Double32_t fTime
Time since event start [ns].
Double32_t fLength
Track length since creation [cm].
Double32_t fELoss
Energy loss at this point [GeV].
Int_t fDetectorID
Detector unique identifier.
Double32_t fX
Double32_t fY
Double32_t fZ
Position of hit [cm].
Protected Attributes inherited from FairMultiLinkedData
std::set< FairLink > fLinks
Bool_t fPersistanceCheck
Int_t fVerbose
Int_t fDefaultType
Additional Inherited Members
Protected Member Functions inherited from FairMultiLinkedData
virtual void SimpleAddLinks (Int_t fileId, Int_t evtId, Int_t dataType, std::vector< Int_t > links, Bool_t bypass, Float_t mult)
ClassDef (FairMultiLinkedData, 3)
Detailed Description
FairMCPoint.h This is the base class for all MC Points generated by the transport of tracks through active detectors.
Definition at line 14 of file FairMCPoint.h.
View newest version in sPHENIX GitHub at line 14 of file FairMCPoint.h
Constructor & Destructor Documentation
FairMCPoint::FairMCPoint ()
Default constructor
Definition at line 4 of file FairMCPoint.cxx.
View newest version in sPHENIX GitHub at line 4 of file FairMCPoint.cxx
FairMCPoint::FairMCPoint (Int_t trackID, Int_t detID, TVector3 pos, TVector3 mom, Double_t tof, Double_t length, Double_t eLoss, UInt_t EventId = 0)
Constructor with arguments
Parameters
trackID Index of MCTrack
detID Detector ID
pos Point coordinates [cm]
mom Momentum of track at MCPoint [GeV]
tof Time since event start [ns]
length Track length since creation [cm]
eLoss Energy deposit [GeV]
EventId MC event id
Definition at line 28 of file FairMCPoint.cxx.
View newest version in sPHENIX GitHub at line 28 of file FairMCPoint.cxx
FairMCPoint::~FairMCPoint () virtual
Destructor
Definition at line 51 of file FairMCPoint.cxx.
View newest version in sPHENIX GitHub at line 51 of file FairMCPoint.cxx
Member Function Documentation
Int_t FairMCPoint::GetDetectorID () const inline
Definition at line 51 of file FairMCPoint.h.
View newest version in sPHENIX GitHub at line 51 of file FairMCPoint.h
References fDetectorID.
Referenced by CbmRichHitProducer::Exec().
Double_t FairMCPoint::GetEnergyLoss () const inline
Definition at line 49 of file FairMCPoint.h.
View newest version in sPHENIX GitHub at line 49 of file FairMCPoint.h
References fELoss.
Referenced by EicDetector::EndOfEvent(), and EicCalorimeterDigiHitProducer::HandleHit().
UInt_t FairMCPoint::GetEventID () const inline
Accessors
Definition at line 42 of file FairMCPoint.h.
View newest version in sPHENIX GitHub at line 42 of file FairMCPoint.h
References fEventId.
Double_t FairMCPoint::GetLength () const inline
Definition at line 48 of file FairMCPoint.h.
View newest version in sPHENIX GitHub at line 48 of file FairMCPoint.h
References fLength.
Double_t FairMCPoint::GetPx () const inline
Definition at line 44 of file FairMCPoint.h.
View newest version in sPHENIX GitHub at line 44 of file FairMCPoint.h
References fPx.
Double_t FairMCPoint::GetPy () const inline
Definition at line 45 of file FairMCPoint.h.
View newest version in sPHENIX GitHub at line 45 of file FairMCPoint.h
References fPy.
Double_t FairMCPoint::GetPz () const inline
Definition at line 46 of file FairMCPoint.h.
View newest version in sPHENIX GitHub at line 46 of file FairMCPoint.h
References fPz.
Double_t FairMCPoint::GetTime () const inline
Definition at line 47 of file FairMCPoint.h.
View newest version in sPHENIX GitHub at line 47 of file FairMCPoint.h
References fTime.
Referenced by EicCalorimeterDigiHitProducer::HandleHit().
Int_t FairMCPoint::GetTrackID () const inline
event identifier
Definition at line 43 of file FairMCPoint.h.
View newest version in sPHENIX GitHub at line 43 of file FairMCPoint.h
References fTrackID.
Referenced by CbmRich::CopyClones(), CbmRichTrackExtrapolationIdeal::DoExtrapolation(), CbmRichTrackExtrapolationMirrorIdeal::DoExtrapolation(), CbmRichRingFinderIdeal::DoFind(), CbmRichTestHits::Exec(), CbmRichTestSim::Exec(), CbmRichMatchRings::Exec(), EicIdealTrackingCode::Exec(), CbmRichUrqmdTest::FillRichRingNofHits(), FwdHoughTree::FinalFit(), CbmRichUrqmdTest::NofHits(), CbmRichGeoTest::RingParameters(), FwdHoughTree::SetupKalmanFilter(), CbmStack::UpdateTrackIndex(), and PndStack::UpdateTrackIndex().
Double_t FairMCPoint::GetX () const inline
Definition at line 52 of file FairMCPoint.h.
View newest version in sPHENIX GitHub at line 52 of file FairMCPoint.h
References fX.
Referenced by CbmRichEventDisplay::DrawOnePmtPlane(), FairTimeStampPointDraw::GetVector(), FairMCPointDraw::GetVector(), CbmRichGeoTest::HitsAndPoints(), and PndHitRecoHit::PndHitRecoHit().
Double_t FairMCPoint::GetY () const inline
Definition at line 53 of file FairMCPoint.h.
View newest version in sPHENIX GitHub at line 53 of file FairMCPoint.h
References fY.
Referenced by CbmRichEventDisplay::DrawOnePmtPlane(), FairTimeStampPointDraw::GetVector(), FairMCPointDraw::GetVector(), CbmRichGeoTest::HitsAndPoints(), and PndHitRecoHit::PndHitRecoHit().
Double_t FairMCPoint::GetZ () const inline
Definition at line 54 of file FairMCPoint.h.
View newest version in sPHENIX GitHub at line 54 of file FairMCPoint.h
References fZ.
Referenced by FairTimeStampPointDraw::GetVector(), FairMCPointDraw::GetVector(), CbmRichGeoTest::HitsAndPoints(), and PndHitRecoHit::PndHitRecoHit().
void FairMCPoint::Momentum (TVector3 & mom) inline
Definition at line 50 of file FairMCPoint.h.
View newest version in sPHENIX GitHub at line 50 of file FairMCPoint.h
References fPx, fPy, and fPz.
Referenced by CbmRichTrackExtrapolationIdeal::DoExtrapolation(), CbmRichTrackExtrapolationMirrorIdeal::DoExtrapolation(), and CbmRichHitProducer::Exec().
void FairMCPoint::Position (TVector3 & pos) const inline
Definition at line 103 of file FairMCPoint.h.
View newest version in sPHENIX GitHub at line 103 of file FairMCPoint.h
References fX, fY, and fZ.
Referenced by CbmRichTrackExtrapolationIdeal::DoExtrapolation(), CbmRichTrackExtrapolationMirrorIdeal::DoExtrapolation(), CbmRichHitProducer::Exec(), CbmRichTestSim::Exec(), EicMoCaPoint::GetPosIn(), and CbmRichGeoTest::RingParameters().
virtual void FairMCPoint::Print (const Option_t * opt = 0) const pure virtual
Output to screen
Implemented in CbmRichPoint, FairRadLenPoint, FairRadMapPoint, and EicMoCaPoint.
void FairMCPoint::SetDetectorID (Int_t detID) inline
Definition at line 67 of file FairMCPoint.h.
View newest version in sPHENIX GitHub at line 67 of file FairMCPoint.h
References fDetectorID.
void FairMCPoint::SetEnergyLoss (Double_t eLoss) inline
Definition at line 65 of file FairMCPoint.h.
View newest version in sPHENIX GitHub at line 65 of file FairMCPoint.h
References fELoss.
void FairMCPoint::SetEventID (UInt_t eventId) inline
Modifiers
Definition at line 61 of file FairMCPoint.h.
View newest version in sPHENIX GitHub at line 61 of file FairMCPoint.h
References fEventId.
void FairMCPoint::SetLength (Double_t length) inline
Definition at line 64 of file FairMCPoint.h.
View newest version in sPHENIX GitHub at line 64 of file FairMCPoint.h
References fLength, and G4BARRELHCAL::length.
void FairMCPoint::SetMomentum (const TVector3 & mom) inline
Definition at line 97 of file FairMCPoint.h.
View newest version in sPHENIX GitHub at line 97 of file FairMCPoint.h
References fPx, fPy, and fPz.
void FairMCPoint::SetPosition (const TVector3 & pos) inline
Definition at line 117 of file FairMCPoint.h.
View newest version in sPHENIX GitHub at line 117 of file FairMCPoint.h
References fX, fY, and fZ.
void FairMCPoint::SetTime (Double_t time) inline
Definition at line 63 of file FairMCPoint.h.
View newest version in sPHENIX GitHub at line 63 of file FairMCPoint.h
References fTime, and Acts::Test::time.
virtual void FairMCPoint::SetTrackID (Int_t id) inline virtual
Definition at line 62 of file FairMCPoint.h.
View newest version in sPHENIX GitHub at line 62 of file FairMCPoint.h
References fTrackID.
Referenced by CbmRich::CopyClones(), CbmStack::UpdateTrackIndex(), and PndStack::UpdateTrackIndex().
void FairMCPoint::SetX (Double_t x) inline
Definition at line 68 of file FairMCPoint.h.
View newest version in sPHENIX GitHub at line 68 of file FairMCPoint.h
References fX, and x.
void FairMCPoint::SetXYZ (Double_t x, Double_t y, Double_t z) inline
Definition at line 109 of file FairMCPoint.h.
View newest version in sPHENIX GitHub at line 109 of file FairMCPoint.h
References fX, fY, fZ, x, y, and z.
void FairMCPoint::SetY (Double_t y) inline
Definition at line 69 of file FairMCPoint.h.
View newest version in sPHENIX GitHub at line 69 of file FairMCPoint.h
References fY, and y.
void FairMCPoint::SetZ (Double_t z) inline
Definition at line 70 of file FairMCPoint.h.
View newest version in sPHENIX GitHub at line 70 of file FairMCPoint.h
References fZ, and z.
Member Data Documentation
Int_t FairMCPoint::fDetectorID protected
Detector unique identifier.
Definition at line 88 of file FairMCPoint.h.
View newest version in sPHENIX GitHub at line 88 of file FairMCPoint.h
Referenced by GetDetectorID(), CbmRichPoint::Print(), and SetDetectorID().
Double32_t FairMCPoint::fELoss protected
Energy loss at this point [GeV].
Definition at line 87 of file FairMCPoint.h.
View newest version in sPHENIX GitHub at line 87 of file FairMCPoint.h
Referenced by GetEnergyLoss(), EicMoCaPoint::Print(), CbmRichPoint::Print(), and SetEnergyLoss().
UInt_t FairMCPoint::fEventId protected
MC Event id.
Definition at line 83 of file FairMCPoint.h.
View newest version in sPHENIX GitHub at line 83 of file FairMCPoint.h
Referenced by GetEventID(), and SetEventID().
Double32_t FairMCPoint::fLength protected
Track length since creation [cm].
Definition at line 86 of file FairMCPoint.h.
View newest version in sPHENIX GitHub at line 86 of file FairMCPoint.h
Referenced by GetLength(), CbmRichPoint::Print(), and SetLength().
Double32_t FairMCPoint::fPx protected
Definition at line 84 of file FairMCPoint.h.
View newest version in sPHENIX GitHub at line 84 of file FairMCPoint.h
Referenced by EicMoCaPoint::GetMomAvg(), GetPx(), Momentum(), CbmRichPoint::Print(), and SetMomentum().
Double32_t FairMCPoint::fPy protected
Definition at line 84 of file FairMCPoint.h.
View newest version in sPHENIX GitHub at line 84 of file FairMCPoint.h
Referenced by EicMoCaPoint::GetMomAvg(), GetPy(), Momentum(), CbmRichPoint::Print(), and SetMomentum().
Double32_t FairMCPoint::fPz protected
Momentum components [GeV].
Definition at line 84 of file FairMCPoint.h.
View newest version in sPHENIX GitHub at line 84 of file FairMCPoint.h
Referenced by EicMoCaPoint::GetMomAvg(), GetPz(), Momentum(), CbmRichPoint::Print(), and SetMomentum().
Double32_t FairMCPoint::fTime protected
Time since event start [ns].
Definition at line 85 of file FairMCPoint.h.
View newest version in sPHENIX GitHub at line 85 of file FairMCPoint.h
Referenced by GetTime(), CbmRichPoint::Print(), and SetTime().
Int_t FairMCPoint::fTrackID protected
Track index.
Definition at line 82 of file FairMCPoint.h.
View newest version in sPHENIX GitHub at line 82 of file FairMCPoint.h
Referenced by GetTrackID(), EicMoCaPoint::Print(), CbmRichPoint::Print(), and SetTrackID().
Double32_t FairMCPoint::fX protected
Definition at line 89 of file FairMCPoint.h.
View newest version in sPHENIX GitHub at line 89 of file FairMCPoint.h
Referenced by FairRadLenPoint::GetPosition(), FairRadMapPoint::GetPosition(), GetX(), Position(), EicMoCaPoint::Print(), CbmRichPoint::Print(), SetPosition(), SetX(), and SetXYZ().
Double32_t FairMCPoint::fY protected
Definition at line 89 of file FairMCPoint.h.
View newest version in sPHENIX GitHub at line 89 of file FairMCPoint.h
Referenced by FairRadLenPoint::GetPosition(), FairRadMapPoint::GetPosition(), GetY(), Position(), EicMoCaPoint::Print(), CbmRichPoint::Print(), SetPosition(), SetXYZ(), and SetY().
Double32_t FairMCPoint::fZ protected
Position of hit [cm].
Definition at line 89 of file FairMCPoint.h.
View newest version in sPHENIX GitHub at line 89 of file FairMCPoint.h
Referenced by GetZ(), Position(), EicMoCaPoint::Print(), CbmRichPoint::Print(), SetPosition(), SetXYZ(), and SetZ().
The documentation for this class was generated from the following files:
EicRoot/blob/master/base/FairMCPoint.h
EicRoot/blob/master/base/FairMCPoint.cxx