EIC Software: PndMagnet Class Reference
PndMagnet Class Reference
#include <EicRoot/blob/master/passive/PndMagnet.h>
Public Member Functions
PndMagnet (const char *name, const char *Title="PND Magnet")
PndMagnet ()
virtual ~PndMagnet ()
void ConstructGeometry ()
void ConstructASCIIGeometry ()
Bool_t CheckIfSensitive (std::string name)
Public Member Functions inherited from FairModule
FairModule ()
FairModule (const char *Name, const char *title, Bool_t Active=kFALSE)
virtual ~FairModule ()
virtual void Print (Option_t *option="") const
virtual void SetGeometryFileName (TString fname, TString geoVer="0")
virtual TString GetGeometryFileName ()
virtual TString GetGeometryFileVer ()
virtual void ConstructOpGeometry ()
virtual void ConstructRootGeometry ()
virtual void ExpandNode (TGeoNode *Node)
virtual Int_t getVolId (const TString &vname) const
Int_t GetModId ()
void SetVerboseLevel (Int_t level)
Bool_t IsActive ()
void SetModId (Int_t id)
void SetMotherVolume (TString volName)
void ProcessNodes (TList *aList)
virtual void SetParContainers ()
TList * GetListOfGeoPar ()
FairVolume * getFairVolume (FairGeoNode *fNode)
void AddSensitiveVolume (TGeoVolume *v)
void ImportRootMaterials ()
Additional Inherited Members
Public Attributes inherited from FairModule
TString fMotherVolumeName
Static Public Attributes inherited from FairModule
static FairVolumeList * vList =0
static Int_t fNbOfVolumes =0
static TRefArray * svList =0
static TArrayI * volNumber =0
Protected Attributes inherited from FairModule
TString fgeoVer
TString fgeoName
Int_t fModId
Bool_t fActive
Int_t fNbOfSensitiveVol
Int_t fVerboseLevel
TList * flGeoPar
Bool_t kGeoSaved
list of Detector Geometry parameters
FairLogger * fLogger
flag for initialisation
Bool_t fRootMaterialImportFlag
Detailed Description
Definition at line 11 of file PndMagnet.h.
View newest version in sPHENIX GitHub at line 11 of file PndMagnet.h
Constructor & Destructor Documentation
PndMagnet::PndMagnet (const char * name, const char * Title = "PND Magnet")
Definition at line 22 of file PndMagnet.cxx.
View newest version in sPHENIX GitHub at line 22 of file PndMagnet.cxx
PndMagnet::PndMagnet ()
Definition at line 18 of file PndMagnet.cxx.
View newest version in sPHENIX GitHub at line 18 of file PndMagnet.cxx
PndMagnet::~PndMagnet () virtual
Definition at line 15 of file PndMagnet.cxx.
View newest version in sPHENIX GitHub at line 15 of file PndMagnet.cxx
Member Function Documentation
Bool_t PndMagnet::CheckIfSensitive (std::string name) virtual
Set the sensitivity flag fro volumes, called from ConstructASCIIRootGeometry(), and has to be implimented for detectors which use ConstructASCIIRootGeometry() to build the geometry
Reimplemented from FairModule.
Definition at line 39 of file PndMagnet.cxx.
View newest version in sPHENIX GitHub at line 39 of file PndMagnet.cxx
void PndMagnet::ConstructASCIIGeometry () virtual
construct geometry from standard ASSCII files (Hades Format)
Reimplemented from FairModule.
Definition at line 44 of file PndMagnet.cxx.
View newest version in sPHENIX GitHub at line 44 of file PndMagnet.cxx
References FairGeoInterface::addGeoModule(), FairGeoSet::create(), FairRuntimeDb::getContainer(), FairGeoLoader::getGeoBuilder(), FairGeoLoader::getGeoInterface(), FairModule::GetGeometryFileName(), PndGeoPassivePar::GetGeoPassiveNodes(), PndGeoPassivePar::GetGeoSensitiveNodes(), FairGeoSet::getListOfVolumes(), FairRun::GetRunId(), FairRun::GetRuntimeDb(), FairGeoLoader::Instance(), FairRun::Instance(), FairGeoNode::isSensitive(), loader, FairModule::ProcessNodes(), FairGeoInterface::readSet(), FairParSet::setChanged(), FairGeoSet::setGeomFile(), and FairParSet::setInputVersion().
Referenced by ConstructGeometry().
void PndMagnet::ConstructGeometry () virtual
method called from the MC application to construct the geometry, has to be implimented by user
Reimplemented from FairModule.
Definition at line 27 of file PndMagnet.cxx.
View newest version in sPHENIX GitHub at line 27 of file PndMagnet.cxx
References ConstructASCIIGeometry(), FairModule::ConstructRootGeometry(), and FairModule::GetGeometryFileName().
The documentation for this class was generated from the following files:
EicRoot/blob/master/passive/PndMagnet.h
EicRoot/blob/master/passive/PndMagnet.cxx