EIC Software: EicCadFile Class Reference
EicCadFile Class Reference
#include <EicRoot/blob/master/eic/cad/EicCadFile.h>
Public Member Functions
EicCadFile (const char *Name, char *geometryName, char *mediaName=0, int color=_COLOR_DEFAULT_)
EicCadFile ()
~EicCadFile ()
EicCadFileConfig * GetConfig (void)
EicCadFileConfig * config (void)
void AllowRootSolidCreation (bool what=true)
void AllowStlSolidCreation (bool what=true)
void AllowStepSolidDecomposition (bool what=true)
void SetExtraStlTranslation (double dx, double dy, double dz)
void SetKillerFlag (void)
void SwapXY (void)
void CreateStlMirrorCopyXZ (void)
void CreateStlMirrorCopyXY (void)
void WizardTestbed (void)
Public Member Functions inherited from EicDummyDetector
EicDummyDetector (const char *Name, const char *geometryName)
EicDummyDetector ()
~EicDummyDetector ()
Public Member Functions inherited from EicDetector
EicDetector (const char *Name, const char *geometryName, EicDetectorId dType=qDUMMY, SteppingType stType=qSteppingTypeUndefined, Bool_t Active=kTRUE)
EicDetector ()
void ResetVars ()
~EicDetector ()
virtual void Initialize ()
virtual void FinishRun ()
virtual Bool_t ProcessHits (FairVolume *v=0)
virtual void Register ()
virtual void Print () const
virtual void Reset ()
virtual void BeginEvent ()
void DeclareAllVolumesSensitive ()
int DeclareGeantSensitiveVolume (const char *name, SteppingType stType=qSteppingTypeDefault)
int DeclareGeantSensitiveVolumePrefix (const char *name, SteppingType stType=qSteppingTypeDefault)
bool CheckIfSensitive (std::string name)
ULong64_t GetNodeMultiIndex ()
virtual TClonesArray * GetCollection (Int_t iColl) const
void ResetSteppingVariables ()
virtual void AddMoCaPoint (Int_t trackID, Int_t primaryMotherID, Int_t secondaryMotherID, Int_t detID, ULong64_t multiIndex, TVector3 PosIn, TVector3 PosOut, TVector3 MomIn, TVector3 MomOut, Double_t time, Double_t length, Double_t eLoss, Double_t step)
void EndOfEvent ()
EicDetectorId GetType ()
virtual FairParSet * EicGeoParAllocator (FairContainer *c)
EicDetName * GetDname ()
int createFakeMoCaDatabase (const char *outFileName)
void RequestGeometryInfoPrintout (const char *option=0)
void RequestAttachedFilePrintout (const char *fileName, const char *option=0)
EicEnergyMonitor * AddEnergyMonitorVolume (const char *volumeName, Int_t PDG, char *histogramName, double histogramMin, double histogramMax, unsigned histogramBinNum=1000)
void AddKillerVolume (const char *vname)
Public Member Functions inherited from FairDetector
FairDetector (const char *Name, Bool_t Active, Int_t DetId=0)
FairDetector ()
virtual ~FairDetector ()
virtual void CopyClones (TClonesArray *cl1, TClonesArray *cl2, Int_t offset)
virtual void FinishPrimary ()
virtual void BeginPrimary ()
virtual void PostTrack ()
virtual void PreTrack ()
virtual void FinishEvent ()
virtual void SetSpecialPhysicsCuts ()
void SaveGeoParams ()
Int_t GetDetId ()
Public Member Functions inherited from FairModule
FairModule ()
FairModule (const char *Name, const char *title, Bool_t Active=kFALSE)
virtual ~FairModule ()
virtual void Print (Option_t *option="") const
virtual TString GetGeometryFileName ()
virtual TString GetGeometryFileVer ()
virtual void ConstructOpGeometry ()
virtual void ConstructRootGeometry ()
virtual void ConstructASCIIGeometry ()
virtual void ExpandNode (TGeoNode *Node)
virtual Int_t getVolId (const TString &vname) const
Int_t GetModId ()
void SetVerboseLevel (Int_t level)
Bool_t IsActive ()
void SetModId (Int_t id)
void SetMotherVolume (TString volName)
void ProcessNodes (TList *aList)
virtual void SetParContainers ()
TList * GetListOfGeoPar ()
FairVolume * getFairVolume (FairGeoNode *fNode)
void AddSensitiveVolume (TGeoVolume *v)
void ImportRootMaterials ()
Private Member Functions
void ResetVariables (void)
void ConstructGeometry ()
Private Attributes
FairLogger * mLogger
TGeoVolume * mCave
bool mKillerFlag
unsigned mStlVolumeCounter
bool mRootSolidCreationAllowed
bool mStlSolidCreationAllowed
bool mStepSolidDecompositionAllowed
EicCadFileConfig * mConfig
int mFillColor
bool mSwapXY
TVector3 mExtraStlTranslation
Bool_t mCreateStlMirrorCopyXY
Bool_t mCreateStlMirrorCopyXZ
Additional Inherited Members
Public Attributes inherited from FairModule
TString fMotherVolumeName
Static Public Attributes inherited from FairModule
static FairVolumeList * vList =0
static Int_t fNbOfVolumes =0
static TRefArray * svList =0
static TArrayI * volNumber =0
Protected Member Functions inherited from EicDetector
virtual void SetGeometryFileName (TString fname, TString geoVer="0")
void AddKillerVolume (TGeoVolume *volume)
bool IsKillerVolume (const char *name)
void CheckEnergyMonitors (const char *name, Int_t trackID, Int_t PDG, bool isPrimary, bool isEntering, bool isExiting, double energy)
Protected Attributes inherited from EicDetector
EicDetName * dname
EicContFact * eicContFact
TClonesArray * fEicMoCaPointCollection
bool mPrintGeometryInfoFlag
TString mPrintGeometryInfoOption
TString mAttachedFilePrintoutRequestName
TString mAttachedFilePrintoutOption
TLorentzVector fPosIn
TLorentzVector fMomIn
Double32_t fTime
Double32_t fLength
Double32_t fELoss
Double32_t fStep
Detailed Description
Definition at line 53 of file EicCadFile.h.
View newest version in sPHENIX GitHub at line 53 of file EicCadFile.h
Constructor & Destructor Documentation
EicCadFile::EicCadFile (const char * Name, char * geometryName, char * mediaName = 0, int color = _COLOR_DEFAULT_)
Main constructor
Parameters
Name detector name
geometryName input STL (or SLP) file name
mediaName either media mapping file or single medium name (should then be present in media.geo file)
Definition at line 276 of file EicCadFile.cxx.
View newest version in sPHENIX GitHub at line 276 of file EicCadFile.cxx
References color, EicCadFileConfig::CreateMediaHub(), FairLogger::GetLogger(), mConfig, mFillColor, mLogger, and ResetVariables().
EicCadFile::EicCadFile () inline
Definition at line 63 of file EicCadFile.h.
View newest version in sPHENIX GitHub at line 63 of file EicCadFile.h
References ResetVariables().
EicCadFile::~EicCadFile () inline
Definition at line 65 of file EicCadFile.h.
View newest version in sPHENIX GitHub at line 65 of file EicCadFile.h
References mConfig.
Member Function Documentation
void EicCadFile::AllowRootSolidCreation (bool what = true) inline
Definition at line 71 of file EicCadFile.h.
View newest version in sPHENIX GitHub at line 71 of file EicCadFile.h
References mRootSolidCreationAllowed.
void EicCadFile::AllowStepSolidDecomposition (bool what = true) inline
Definition at line 73 of file EicCadFile.h.
View newest version in sPHENIX GitHub at line 73 of file EicCadFile.h
References mStepSolidDecompositionAllowed.
void EicCadFile::AllowStlSolidCreation (bool what = true) inline
Definition at line 72 of file EicCadFile.h.
View newest version in sPHENIX GitHub at line 72 of file EicCadFile.h
References mStlSolidCreationAllowed.
EicCadFileConfig* EicCadFile::config (void) inline
Definition at line 69 of file EicCadFile.h.
View newest version in sPHENIX GitHub at line 69 of file EicCadFile.h
References mConfig.
Referenced by simulation().
void EicCadFile::ConstructGeometry () private virtual
Create the detector geometry out of STL file;
Reimplemented from EicDetector.
Definition at line 1493 of file EicCadFile.cxx.
View newest version in sPHENIX GitHub at line 1493 of file EicCadFile.cxx
References EicStlFactory::_ConstructGeometry(), EicDetector::AddKillerVolume(), EicDetector::dname, FairLogger::Fatal(), EicMediaHub::fMediaName, EicMediaHub::fSingleMedium, FairModule::GetGeometryFileName(), EicMediaHub::Init(), mCave, mConfig, MESSAGE_ORIGIN, mExtraStlTranslation, EicCadFileConfig::mhub(), mKillerFlag, mLogger, mSwapXY, and EicDetName::Name().
void EicCadFile::CreateStlMirrorCopyXY (void) inline
Definition at line 83 of file EicCadFile.h.
View newest version in sPHENIX GitHub at line 83 of file EicCadFile.h
References mCreateStlMirrorCopyXY.
Referenced by simulation().
void EicCadFile::CreateStlMirrorCopyXZ (void) inline
Definition at line 82 of file EicCadFile.h.
View newest version in sPHENIX GitHub at line 82 of file EicCadFile.h
References mCreateStlMirrorCopyXZ.
Referenced by simulation().
EicCadFileConfig* EicCadFile::GetConfig (void) inline
Definition at line 67 of file EicCadFile.h.
View newest version in sPHENIX GitHub at line 67 of file EicCadFile.h
References mConfig.
void EicCadFile::ResetVariables (void) private
Definition at line 252 of file EicCadFile.cxx.
View newest version in sPHENIX GitHub at line 252 of file EicCadFile.cxx
References _COLOR_DEFAULT_, mConfig, mFillColor, mKillerFlag, mRootSolidCreationAllowed, mStepSolidDecompositionAllowed, mStlSolidCreationAllowed, mStlVolumeCounter, and mSwapXY.
Referenced by EicCadFile().
void EicCadFile::SetExtraStlTranslation (double dx, double dy, double dz) inline
Definition at line 75 of file EicCadFile.h.
View newest version in sPHENIX GitHub at line 75 of file EicCadFile.h
References mExtraStlTranslation.
Referenced by simulation().
void EicCadFile::SetKillerFlag (void) inline
Definition at line 78 of file EicCadFile.h.
View newest version in sPHENIX GitHub at line 78 of file EicCadFile.h
References mKillerFlag.
Referenced by simulation().
void EicCadFile::SwapXY (void) inline
Definition at line 79 of file EicCadFile.h.
View newest version in sPHENIX GitHub at line 79 of file EicCadFile.h
References mSwapXY.
Referenced by simulation().
void EicCadFile::WizardTestbed (void)
Member Data Documentation
TGeoVolume* EicCadFile::mCave private
CAVE volume pointer
Definition at line 92 of file EicCadFile.h.
View newest version in sPHENIX GitHub at line 92 of file EicCadFile.h
Referenced by ConstructGeometry().
EicCadFileConfig* EicCadFile::mConfig private
Definition at line 105 of file EicCadFile.h.
View newest version in sPHENIX GitHub at line 105 of file EicCadFile.h
Referenced by config(), ConstructGeometry(), EicCadFile(), GetConfig(), ResetVariables(), and ~EicCadFile().
Bool_t EicCadFile::mCreateStlMirrorCopyXY private
Definition at line 149 of file EicCadFile.h.
View newest version in sPHENIX GitHub at line 149 of file EicCadFile.h
Referenced by CreateStlMirrorCopyXY().
Bool_t EicCadFile::mCreateStlMirrorCopyXZ private
Definition at line 149 of file EicCadFile.h.
View newest version in sPHENIX GitHub at line 149 of file EicCadFile.h
Referenced by CreateStlMirrorCopyXZ().
TVector3 EicCadFile::mExtraStlTranslation private
Definition at line 148 of file EicCadFile.h.
View newest version in sPHENIX GitHub at line 148 of file EicCadFile.h
Referenced by ConstructGeometry(), and SetExtraStlTranslation().
int EicCadFile::mFillColor private
Definition at line 145 of file EicCadFile.h.
View newest version in sPHENIX GitHub at line 145 of file EicCadFile.h
Referenced by EicCadFile(), and ResetVariables().
bool EicCadFile::mKillerFlag private
Definition at line 94 of file EicCadFile.h.
View newest version in sPHENIX GitHub at line 94 of file EicCadFile.h
Referenced by ConstructGeometry(), ResetVariables(), and SetKillerFlag().
FairLogger* EicCadFile::mLogger private
Duplicate of the FairRoot logger singleton pointer
Definition at line 89 of file EicCadFile.h.
View newest version in sPHENIX GitHub at line 89 of file EicCadFile.h
Referenced by ConstructGeometry(), and EicCadFile().
bool EicCadFile::mRootSolidCreationAllowed private
Definition at line 100 of file EicCadFile.h.
View newest version in sPHENIX GitHub at line 100 of file EicCadFile.h
Referenced by AllowRootSolidCreation(), and ResetVariables().
bool EicCadFile::mStepSolidDecompositionAllowed private
Definition at line 103 of file EicCadFile.h.
View newest version in sPHENIX GitHub at line 103 of file EicCadFile.h
Referenced by AllowStepSolidDecomposition(), and ResetVariables().
bool EicCadFile::mStlSolidCreationAllowed private
Definition at line 100 of file EicCadFile.h.
View newest version in sPHENIX GitHub at line 100 of file EicCadFile.h
Referenced by AllowStlSolidCreation(), and ResetVariables().
unsigned EicCadFile::mStlVolumeCounter private
Definition at line 96 of file EicCadFile.h.
View newest version in sPHENIX GitHub at line 96 of file EicCadFile.h
Referenced by ResetVariables().
bool EicCadFile::mSwapXY private
Definition at line 146 of file EicCadFile.h.
View newest version in sPHENIX GitHub at line 146 of file EicCadFile.h
Referenced by ConstructGeometry(), ResetVariables(), and SwapXY().
The documentation for this class was generated from the following files:
EicRoot/blob/master/eic/cad/EicCadFile.h
EicRoot/blob/master/eic/cad/EicCadFile.cxx