EIC Software: Acts::IntegrationTest Namespace Reference
Acts::IntegrationTest Namespace Reference
Namespaces
namespace ds
Classes
struct StreamWrapper
Typedefs
using Box = Acts::Volume::BoundingBox
using Ray = Acts::Ray< double, 3 >
using Covariance = BoundSymMatrix
using BFieldType = ConstantBField
using EigenStepperType = EigenStepper< BFieldType >
using DenseStepperType = EigenStepper< BFieldType, StepperExtensionList< DenseEnvironmentExtension >>
using AtlasStepperType = AtlasStepper< BFieldType >
using EigenPropagatorType = Propagator< EigenStepperType >
using DensePropagatorType = Propagator< DenseStepperType, Navigator >
using AtlasPropagatorType = Propagator< AtlasStepperType >
using StraightPropagatorType = Propagator< StraightLineStepper >
using RiddersStraightPropagatorType = RiddersPropagator< StraightPropagatorType >
using RiddersEigenPropagatorType = RiddersPropagator< EigenPropagatorType >
using RiddersAtlasPropagatorType = RiddersPropagator< AtlasPropagatorType >
using SharedFieldType = SharedBField< InterpolatedBFieldMap >
Functions
std::tuple< std::vector< const
Volume * >, std::shared_ptr
< TrackingGeometry > > gridBoxFactory (size_t n=NBOXES, double hl=1000, size_t octd=5)
BOOST_DATA_TEST_CASE (bvhnavigation_test, bdata::random((bdata::seed=7, bdata::engine=std::mt19937(), bdata::distribution=std::uniform_real_distribution<>(-5, 5)))^bdata::random((bdata::seed=2, bdata::engine=std::mt19937(), bdata::distribution=std::uniform_real_distribution<>(-M_PI, M_PI)))^bdata::random((bdata::seed=3, bdata::engine=std::mt19937(), bdata::distribution=std::uniform_real_distribution<>(-100, 100)))^bdata::random((bdata::seed=4, bdata::engine=std::mt19937(), bdata::distribution=std::uniform_real_distribution<>(-100, 100)))^bdata::random((bdata::seed=5, bdata::engine=std::mt19937(), bdata::distribution=std::uniform_real_distribution<>(-100, 100)))^bdata::xrange(NTESTS), eta, phi, x, y, z, index)
auto makeFieldMap (const SolenoidBField &field)
StreamWrapper valid (std::ofstream("magfield_lookup.csv"))
BOOST_DATA_TEST_CASE (solenoid_interpolated_bfield_comparison, bdata::random((bdata::seed=1, bdata::engine=std::mt19937(), bdata::distribution=std::uniform_real_distribution<>(1.5 *(-L/2.), 1.5 *L/2.)))^bdata::random((bdata::seed=2, bdata::engine=std::mt19937(), bdata::distribution=std::uniform_real_distribution<>(0, R *1.5)))^bdata::random((bdata::seed=3, bdata::engine=std::mt19937(), bdata::distribution=std::uniform_real_distribution<>(-M_PI, M_PI)))^bdata::xrange(ntests), z, r, phi, index)
std::shared_ptr< Transform3D > createPlanarTransform (const Vector3D &nposition, const Vector3D &nnormal, double angleT, double angleU)
std::shared_ptr< Transform3D > createCylindricTransform (const Vector3D &nposition, double angleX, double angleY)
template<typename Propagator_type >
Vector3D constant_field_propagation (const Propagator_type &propagator, double pT, double phi, double theta, double charge, double time, double Bz, double disttol=0.1 *Acts::UnitConstants::um, bool debug=false)
template<typename Propagator_type >
void foward_backward (const Propagator_type &propagator, double pT, double phi, double theta, double charge, double plimit, double disttol=1 *Acts::UnitConstants::um, double momtol=10 *Acts::UnitConstants::keV, bool debug=false)
template<typename Propagator_type >
std::pair< Vector3D, double > to_cylinder (const Propagator_type &propagator, double pT, double phi, double theta, double charge, double plimit, double rand1, double rand2, double, bool covtransport=false, bool debug=false)
template<typename Propagator_type , typename SurfaceType >
std::pair< Vector3D, double > to_surface (const Propagator_type &propagator, double pT, double phi, double theta, double charge, double plimit, double rand1, double rand2, double rand3, bool planar=true, bool covtransport=false, bool debug=false)
template<typename Propagator_type >
Covariance covariance_curvilinear (const Propagator_type &propagator, double pT, double phi, double theta, double charge, double plimit, bool debug=false)
template<typename Propagator_type , typename StartSurfaceType , typename DestSurfaceType >
Covariance covariance_bound (const Propagator_type &propagator, double pT, double phi, double theta, double charge, double plimit, double rand1, double rand2, double rand3, bool startPlanar=true, bool destPlanar=true, bool debug=false)
EigenPropagatorType epropagator (std::move(estepper))
AtlasPropagatorType apropagator (std::move(astepper))
StraightPropagatorType spropagator (std::move(sstepper))
RiddersStraightPropagatorType rspropagator (std::move(rsstepper))
RiddersEigenPropagatorType repropagator (std::move(restepper))
RiddersAtlasPropagatorType rapropagator (std::move(rastepper))
DensePropagatorType setupDensePropagator ()
BOOST_DATA_TEST_CASE (constant_bfieldforward_propagation_, bdata::random((bdata::seed=0, bdata::distribution=std::uniform_real_distribution<>(0.4_GeV, 10_GeV)))^bdata::random((bdata::seed=1, bdata::distribution=std::uniform_real_distribution<>(-M_PI, M_PI)))^bdata::random((bdata::seed=2, bdata::distribution=std::uniform_real_distribution<>(0.1, M_PI-0.1)))^bdata::random((bdata::seed=3, bdata::distribution=std::uniform_int_distribution<>(0, 1)))^bdata::random((bdata::seed=4, bdata::distribution=std::uniform_int_distribution<>(0, 100)))^bdata::xrange(ntests), pT, phi, theta, charge, time, index)
test forward propagation in constant magnetic field
BOOST_DATA_TEST_CASE (forward_backward_propagation_, ds::trackParameters *ds::propagationLimit, pT, phi, theta, charge, plimit)
test consistency of forward-backward propagation
BOOST_DATA_TEST_CASE (propagation_to_cylinder_, ds::trackParameters *ds::propagationFraction^ds::threeRandom, pT, phi, theta, charge, pfrac, rand1, rand2, rand3)
test consistency of propagators when approaching a cylinder
BOOST_DATA_TEST_CASE (propagation_to_plane_, ds::trackParameters *ds::propagationLimit^ds::threeRandom, pT, phi, theta, charge, plimit, rand1, rand2, rand3)
test consistency of propagators to a plane
BOOST_DATA_TEST_CASE (propagation_to_disc_, ds::trackParameters *ds::propagationLimit^ds::threeRandom, pT, phi, theta, charge, plimit, rand1, rand2, rand3)
test consistency of propagators to a disc
BOOST_DATA_TEST_CASE (propagation_to_line_, ds::trackParameters *ds::propagationLimit^ds::threeRandom, pT, phi, theta, charge, plimit, rand1, rand2, rand3)
test consistency of propagators to a line
BOOST_DATA_TEST_CASE (covariance_transport_curvilinear_curvilinear_, ds::trackParameters *ds::propagationLimit, pT, phi, theta, charge, plimit)
BOOST_DATA_TEST_CASE (covariance_transport_disc_disc_, ds::trackParameters *ds::propagationLimit^ds::threeRandom, pT, phi, theta, charge, plimit, rand1, rand2, rand3)
BOOST_DATA_TEST_CASE (covariance_transport_plane_plane_, ds::trackParameters *ds::propagationLimit^ds::threeRandom, pT, phi, theta, charge, plimit, rand1, rand2, rand3)
BOOST_DATA_TEST_CASE (covariance_transport_line_line_, ds::trackParameters *ds::propagationLimit^ds::threeRandom, pT, phi, theta, charge, plimit, rand1, rand2, rand3)
BOOST_DATA_TEST_CASE (dense_covariance_transport_curvilinear_curvilinear_, ds::pT *ds::propagationLimit^ds::threeRandom, pT, plimit, rand1, rand2, rand3)
InterpolatedBFieldMap::FieldMapper< 3, 3 > readFieldXYZ (std::function< size_t(std::array< size_t, 3 > binsXYZ, std::array< size_t, 3 > nBinsXYZ)> localToGlobalBin, std::string fieldMapFile="Field.txt", double lengthUnit=1., double BFieldUnit=1., size_t nPoints=100000, bool firstOctant=false)
std::shared_ptr< const
InterpolatedBFieldMap > atlasBField (std::string fieldMapFile="Field.txt")
EigenStepperType estepper (bFieldSharedE)
AtlasStepperType astepper (bFieldSharedA)
Variables
GeometryContext tgContext = GeometryContext()
MagneticFieldContext mfContext = MagneticFieldContext()
auto [volumes, tg] = gridBoxFactory()
const double L = 5.8_m
const double R = (2.56 + 2.46) * 0.5 * 0.5_m
const size_t nCoils = 1154
const double bMagCenter = 2_T
const size_t nBinsR = 150
const size_t nBinsZ = 200
Acts::SolenoidBField bSolenoidField ({R, L, nCoils, bMagCenter})
auto bFieldMap = makeFieldMap(bSolenoidField)
const int ntests = 10000
const int skip = 0
const bool covtpr = true
const bool debug = false
const double Bz = 2_T
BFieldType bField (0, 0, Bz) = atlasBField("Field.txt")
EigenStepperType estepper (bField)
DenseStepperType dstepper (bField)
AtlasStepperType astepper (bField)
StraightLineStepper sstepper
StraightLineStepper rsstepper
EigenStepperType restepper (bField)
AtlasStepperType rastepper (bField)
unsigned int itest = 0
auto bFieldSharedA = SharedFieldType(bField)
auto bFieldSharedE = SharedFieldType(bField)
Detailed Description
Get the ATLAS field from : http://acts.web.cern.ch/ACTS/data/AtlasField/AtlasField.tar.gz to run this
Typedef Documentation
typedef Propagator< AtlasStepperType > Acts::IntegrationTest::AtlasPropagatorType
Definition at line 51 of file PropagationTests.cpp.
View newest version in sPHENIX GitHub at line 51 of file PropagationTests.cpp
typedef AtlasStepper< SharedFieldType > Acts::IntegrationTest::AtlasStepperType
Definition at line 48 of file PropagationTests.cpp.
View newest version in sPHENIX GitHub at line 48 of file PropagationTests.cpp
typedef InterpolatedBFieldMap Acts::IntegrationTest::BFieldType
Definition at line 44 of file PropagationTests.cpp.
View newest version in sPHENIX GitHub at line 44 of file PropagationTests.cpp
using Acts::IntegrationTest::Box = typedef Acts::Volume::BoundingBox
Definition at line 11 of file BVHNavigationTest.cpp.
View newest version in sPHENIX GitHub at line 11 of file BVHNavigationTest.cpp
typedef BoundSymMatrix Acts::IntegrationTest::Covariance
Definition at line 25 of file PropagationTestHelper.hpp.
View newest version in sPHENIX GitHub at line 25 of file PropagationTestHelper.hpp
using Acts::IntegrationTest::DensePropagatorType = typedef Propagator<DenseStepperType, Navigator>
Definition at line 50 of file PropagationTests.cpp.
View newest version in sPHENIX GitHub at line 50 of file PropagationTests.cpp
using Acts::IntegrationTest::DenseStepperType = typedef EigenStepper<BFieldType, StepperExtensionList<DenseEnvironmentExtension>>
Definition at line 47 of file PropagationTests.cpp.
View newest version in sPHENIX GitHub at line 47 of file PropagationTests.cpp
typedef Propagator< EigenStepperType > Acts::IntegrationTest::EigenPropagatorType
Definition at line 49 of file PropagationTests.cpp.
View newest version in sPHENIX GitHub at line 49 of file PropagationTests.cpp
typedef EigenStepper< SharedFieldType > Acts::IntegrationTest::EigenStepperType
Definition at line 45 of file PropagationTests.cpp.
View newest version in sPHENIX GitHub at line 45 of file PropagationTests.cpp
using Acts::IntegrationTest::Ray = typedef Acts::Ray<double, 3>
Definition at line 12 of file BVHNavigationTest.cpp.
View newest version in sPHENIX GitHub at line 12 of file BVHNavigationTest.cpp
using Acts::IntegrationTest::RiddersAtlasPropagatorType = typedef RiddersPropagator<AtlasPropagatorType>
Definition at line 55 of file PropagationTests.cpp.
View newest version in sPHENIX GitHub at line 55 of file PropagationTests.cpp
using Acts::IntegrationTest::RiddersEigenPropagatorType = typedef RiddersPropagator<EigenPropagatorType>
Definition at line 54 of file PropagationTests.cpp.
View newest version in sPHENIX GitHub at line 54 of file PropagationTests.cpp
using Acts::IntegrationTest::RiddersStraightPropagatorType = typedef RiddersPropagator<StraightPropagatorType>
Definition at line 53 of file PropagationTests.cpp.
View newest version in sPHENIX GitHub at line 53 of file PropagationTests.cpp
using Acts::IntegrationTest::SharedFieldType = typedef SharedBField<InterpolatedBFieldMap>
Definition at line 108 of file PropagationTestsAtlasField.cpp.
View newest version in sPHENIX GitHub at line 108 of file PropagationTestsAtlasField.cpp
using Acts::IntegrationTest::StraightPropagatorType = typedef Propagator<StraightLineStepper>
Definition at line 52 of file PropagationTests.cpp.
View newest version in sPHENIX GitHub at line 52 of file PropagationTests.cpp
Function Documentation
AtlasPropagatorType Acts::IntegrationTest::apropagator (std:: moveastepper)
Referenced by BOOST_DATA_TEST_CASE(), and BOOST_DATA_TEST_CASE().
AtlasStepperType Acts::IntegrationTest::astepper (bFieldSharedA)
std::shared_ptr<const InterpolatedBFieldMap> Acts::IntegrationTest::atlasBField (std::string fieldMapFile = "Field.txt")
Definition at line 84 of file PropagationTestsAtlasField.cpp.
View newest version in sPHENIX GitHub at line 84 of file PropagationTestsAtlasField.cpp
References configureMap::config, Acts::UnitConstants::mm, readFieldXYZ(), and Acts::UnitConstants::T.
Acts::IntegrationTest::BOOST_DATA_TEST_CASE (forward_backward_propagation_ , ds::trackParameters *ds::propagationLimit , pT , phi , theta , charge , plimit)
test consistency of forward-backward propagation
Definition at line 49 of file PropagationTests.cpp.
View newest version in sPHENIX GitHub at line 49 of file PropagationTests.cpp
Acts::IntegrationTest::BOOST_DATA_TEST_CASE (propagation_to_cylinder_ , ds::trackParameters *ds::propagationFraction^ds::threeRandom , pT , phi , theta , charge , pfrac , rand1 , rand2 , rand3)
test consistency of propagators when approaching a cylinder
Definition at line 66 of file PropagationTests.cpp.
View newest version in sPHENIX GitHub at line 66 of file PropagationTests.cpp
Acts::IntegrationTest::BOOST_DATA_TEST_CASE (propagation_to_plane_ , ds::trackParameters *ds::propagationLimit^ds::threeRandom , pT , phi , theta , charge , plimit , rand1 , rand2 , rand3)
test consistency of propagators to a plane
Definition at line 94 of file PropagationTests.cpp.
View newest version in sPHENIX GitHub at line 94 of file PropagationTests.cpp
References Acts::CuboidVolumeBuilder::trackingVolume().
Acts::IntegrationTest::BOOST_DATA_TEST_CASE (bvhnavigation_test , bdata:: random(bdata::seed=7, bdata::engine=std::mt19937(),bdata::distribution=std::uniform_real_distribution<>(-5,5)))^bdata::random((bdata::seed=2, bdata::engine=std::mt19937(),bdata::distribution=std::uniform_real_distribution<>(-M_PI, M_PI)))^bdata::random((bdata::seed=3, bdata::engine=std::mt19937(),bdata::distribution=std::uniform_real_distribution<>(-100, 100)))^bdata::random((bdata::seed=4, bdata::engine=std::mt19937(),bdata::distribution=std::uniform_real_distribution<>(-100, 100)))^bdata::random((bdata::seed=5, bdata::engine=std::mt19937(),bdata::distribution=std::uniform_real_distribution<>(-100, 100)))^bdata::xrange(NTESTS, eta , phi , x , y , z , index)
Definition at line 80 of file BVHNavigationTest.cpp.
View newest version in sPHENIX GitHub at line 80 of file BVHNavigationTest.cpp
Acts::IntegrationTest::BOOST_DATA_TEST_CASE (solenoid_interpolated_bfield_comparison , bdata:: random(bdata::seed=1, bdata::engine=std::mt19937(),bdata::distribution=std::uniform_real_distribution<>(1.5 *(-L/2.), 1.5 *L/2.)))^bdata::random((bdata::seed=2, bdata::engine=std::mt19937(),bdata::distribution=std::uniform_real_distribution<>(0, R *1.5)))^bdata::random((bdata::seed=3, bdata::engine=std::mt19937(),bdata::distribution=std::uniform_real_distribution<>(-M_PI, M_PI)))^bdata::xrange(ntests, z , r , phi , index)
Definition at line 101 of file InterpolatedSolenoidBFieldTest.cpp.
View newest version in sPHENIX GitHub at line 101 of file InterpolatedSolenoidBFieldTest.cpp
References kdfinder::abs(), bFieldMap, bSolenoidField, CHECK_CLOSE_REL, cos(), Acts::SolenoidBField::getField(), L, Acts::IntegrationTest::StreamWrapper::m_ofstr, phi, Acts::Test::pos, r, R, Acts::UnitConstants::T, valid(), nlohmann::detail::void(), and z.
Acts::IntegrationTest::BOOST_DATA_TEST_CASE (propagation_to_disc_ , ds::trackParameters *ds::propagationLimit^ds::threeRandom , pT , phi , theta , charge , plimit , rand1 , rand2 , rand3)
test consistency of propagators to a disc
Definition at line 120 of file PropagationTests.cpp.
View newest version in sPHENIX GitHub at line 120 of file PropagationTests.cpp
References apropagator(), Bz, charge, CHECK_CLOSE_REL, constant_field_propagation(), analysis::e, epropagator(), phi, ds::pT, skip, ds::theta, and Acts::VectorHelpers::time().
Acts::IntegrationTest::BOOST_DATA_TEST_CASE (constant_bfieldforward_propagation_ , bdata:: random(bdata::seed=0,bdata::distribution=std::uniform_real_distribution<>(0.4_GeV, 10_GeV)))^bdata::random((bdata::seed=1,bdata::distribution=std::uniform_real_distribution<>(-M_PI, M_PI)))^bdata::random((bdata::seed=2,bdata::distribution=std::uniform_real_distribution<>(0.1, M_PI-0.1)))^bdata::random((bdata::seed=3,bdata::distribution=std::uniform_int_distribution<>(0, 1)))^bdata::random((bdata::seed=4,bdata::distribution=std::uniform_int_distribution<>(0, 100)))^bdata::xrange(ntests, pT , phi , theta , charge , time , index)
test forward propagation in constant magnetic field
Definition at line 107 of file PropagationTests.cpp.
View newest version in sPHENIX GitHub at line 107 of file PropagationTests.cpp
Acts::IntegrationTest::BOOST_DATA_TEST_CASE (propagation_to_line_ , ds::trackParameters *ds::propagationLimit^ds::threeRandom , pT , phi , theta , charge , plimit , rand1 , rand2 , rand3)
test consistency of propagators to a line
Definition at line 147 of file PropagationTests.cpp.
View newest version in sPHENIX GitHub at line 147 of file PropagationTests.cpp
Acts::IntegrationTest::BOOST_DATA_TEST_CASE (covariance_transport_curvilinear_curvilinear_ , ds::trackParameters *ds::propagationLimit , pT , phi , theta , charge , plimit)
test correct covariance transport for curvilinear parameters this test only works within the s_curvilinearProjTolerance (in: Definitions.hpp)
Definition at line 185 of file PropagationTests.cpp.
View newest version in sPHENIX GitHub at line 185 of file PropagationTests.cpp
Acts::IntegrationTest::BOOST_DATA_TEST_CASE (covariance_transport_disc_disc_ , ds::trackParameters *ds::propagationLimit^ds::threeRandom , pT , phi , theta , charge , plimit , rand1 , rand2 , rand3)
Definition at line 206 of file PropagationTests.cpp.
View newest version in sPHENIX GitHub at line 206 of file PropagationTests.cpp
Acts::IntegrationTest::BOOST_DATA_TEST_CASE (covariance_transport_plane_plane_ , ds::trackParameters *ds::propagationLimit^ds::threeRandom , pT , phi , theta , charge , plimit , rand1 , rand2 , rand3)
Definition at line 249 of file PropagationTests.cpp.
View newest version in sPHENIX GitHub at line 249 of file PropagationTests.cpp
Acts::IntegrationTest::BOOST_DATA_TEST_CASE (covariance_transport_line_line_ , ds::trackParameters *ds::propagationLimit^ds::threeRandom , pT , phi , theta , charge , plimit , rand1 , rand2 , rand3)
Definition at line 284 of file PropagationTests.cpp.
View newest version in sPHENIX GitHub at line 284 of file PropagationTests.cpp
Acts::IntegrationTest::BOOST_DATA_TEST_CASE (dense_covariance_transport_curvilinear_curvilinear_ , ds::pT *ds::propagationLimit^ds::threeRandom , pT , plimit , rand1 , rand2 , rand3)
test correct covariance transport for curvilinear parameters in dense environment this test only works within the s_curvilinearProjTolerance (in: Definitions.hpp)
Definition at line 326 of file PropagationTests.cpp.
View newest version in sPHENIX GitHub at line 326 of file PropagationTests.cpp
template<typename Propagator_type > Vector3D Acts::IntegrationTest::constant_field_propagation (const Propagator_type & propagator, double pT, double phi, double theta, double charge, double time, double Bz, double disttol = 0.1 * Acts::UnitConstants::um, bool debug = false)
Definition at line 81 of file PropagationTestHelper.hpp.
View newest version in sPHENIX GitHub at line 81 of file PropagationTestHelper.hpp
References Acts::units::_cm, Acts::units::_keV, Acts::units::_m, kdfinder::abs(), charge, CHECK_CLOSE_ABS, cos(), debug, Acts::PropagatorOptions< action_list_t, aborter_list_t >::debug, dx, dy, analysis::e, M_PI, max, Acts::PropagatorOptions< action_list_t, aborter_list_t >::maxStepSize, mfContext, charm_jet_coverage::mom, eicpy.build::options, Acts::PropagatorOptions< action_list_t, aborter_list_t >::pathLimit, Acts::VectorHelpers::perp(), phi, Acts::Test::pos, r, tgContext, ds::theta, x, analysis::y, and z.
Referenced by BOOST_DATA_TEST_CASE().
template<typename Propagator_type , typename StartSurfaceType , typename DestSurfaceType > Covariance Acts::IntegrationTest::covariance_bound (const Propagator_type & propagator, double pT, double phi, double theta, double charge, double plimit, double rand1, double rand2, double rand3, bool startPlanar = true, bool destPlanar = true, bool debug = false)
Definition at line 493 of file PropagationTestHelper.hpp.
View newest version in sPHENIX GitHub at line 493 of file PropagationTestHelper.hpp
References Acts::units::_e, Acts::units::_GeV, Acts::units::_mm, charge, cos(), createCylindricTransform(), createPlanarTransform(), debug, Acts::PropagatorOptions< action_list_t, aborter_list_t >::debug, Acts::PropagatorOptions< action_list_t, aborter_list_t >::maxStepSize, mfContext, charm_jet_coverage::mom, eicpy.build::options, Acts::PropagatorOptions< action_list_t, aborter_list_t >::pathLimit, Acts::Test::pos, ds::rand1, ds::rand2, ds::rand3, tgContext, Acts::VectorHelpers::time(), x, analysis::y, and z.
Referenced by BOOST_DATA_TEST_CASE().
template<typename Propagator_type > Covariance Acts::IntegrationTest::covariance_curvilinear (const Propagator_type & propagator, double pT, double phi, double theta, double charge, double plimit, bool debug = false)
Definition at line 446 of file PropagationTestHelper.hpp.
View newest version in sPHENIX GitHub at line 446 of file PropagationTestHelper.hpp
References Acts::units::_e, Acts::units::_GeV, Acts::units::_mm, charge, cos(), debug, Acts::PropagatorOptions< action_list_t, aborter_list_t >::debug, analysis::e, Acts::PropagatorOptions< action_list_t, aborter_list_t >::maxStepSize, mfContext, charm_jet_coverage::mom, eicpy.build::options, Acts::PropagatorOptions< action_list_t, aborter_list_t >::pathLimit, Acts::Test::pos, tgContext, Acts::VectorHelpers::time(), Acts::PropagatorOptions< action_list_t, aborter_list_t >::tolerance, x, analysis::y, and z.
Referenced by BOOST_DATA_TEST_CASE().
std::shared_ptr<Transform3D> Acts::IntegrationTest::createCylindricTransform (const Vector3D & nposition, double angleX, double angleY)
Helper method to create a transform for a plane to mimic detector situations, the plane is roughly perpendicular to the track
Parameters
nnomal The nominal normal direction
angleT Rotation around the norminal normal
angleU Roation around the original U axis
Definition at line 69 of file PropagationTestHelper.hpp.
View newest version in sPHENIX GitHub at line 69 of file PropagationTestHelper.hpp
Referenced by Acts::Test::BOOST_AUTO_TEST_CASE(), covariance_bound(), to_cylinder(), and to_surface().
std::shared_ptr<Transform3D> Acts::IntegrationTest::createPlanarTransform (const Vector3D & nposition, const Vector3D & nnormal, double angleT, double angleU)
Helper method to create a transform for a plane to mimic detector situations, the plane is roughly perpendicular to the track
Parameters
nnomal The nominal normal direction
angleT Rotation around the norminal normal
angleU Roation around the original U axis
Definition at line 38 of file PropagationTestHelper.hpp.
View newest version in sPHENIX GitHub at line 38 of file PropagationTestHelper.hpp
References kdfinder::abs(), and T.
Referenced by Acts::Test::BOOST_AUTO_TEST_CASE(), covariance_bound(), and to_surface().
EigenPropagatorType Acts::IntegrationTest::epropagator (std:: moveestepper)
Referenced by BOOST_DATA_TEST_CASE(), Acts::Test::BOOST_DATA_TEST_CASE(), and BOOST_DATA_TEST_CASE().
EigenStepperType Acts::IntegrationTest::estepper (bFieldSharedE)
template<typename Propagator_type > void Acts::IntegrationTest::foward_backward (const Propagator_type & propagator, double pT, double phi, double theta, double charge, double plimit, double disttol = 1 * Acts::UnitConstants::um, double momtol = 10 * Acts::UnitConstants::keV, bool debug = false)
Definition at line 167 of file PropagationTestHelper.hpp.
View newest version in sPHENIX GitHub at line 167 of file PropagationTestHelper.hpp
References Acts::units::_cm, Acts::backward, charge, CHECK_CLOSE_ABS, cos(), debug, Acts::PropagatorOptions< action_list_t, aborter_list_t >::debug, Acts::PropagatorOptions< action_list_t, aborter_list_t >::direction, Acts::PropagatorOptions< action_list_t, aborter_list_t >::maxStepSize, mfContext, charm_jet_coverage::mom, Acts::PropagatorOptions< action_list_t, aborter_list_t >::pathLimit, Acts::Test::pos, tgContext, Acts::VectorHelpers::time(), x, analysis::y, and z.
Referenced by BOOST_DATA_TEST_CASE().
std::tuple<std::vector<const Volume*>, std::shared_ptr<TrackingGeometry> > Acts::IntegrationTest::gridBoxFactory (size_t n = NBOXES, double hl = 1000, size_t octd = 5)
Definition at line 18 of file BVHNavigationTest.cpp.
View newest version in sPHENIX GitHub at line 18 of file BVHNavigationTest.cpp
auto Acts::IntegrationTest::makeFieldMap (const SolenoidBField & field)
Definition at line 43 of file InterpolatedSolenoidBFieldTest.cpp.
View newest version in sPHENIX GitHub at line 43 of file InterpolatedSolenoidBFieldTest.cpp
References L, nBinsR, nBinsZ, R, and Acts::solenoidFieldMapper().
RiddersAtlasPropagatorType Acts::IntegrationTest::rapropagator (std:: moverastepper)
Referenced by BOOST_DATA_TEST_CASE().
InterpolatedBFieldMap::FieldMapper<3, 3> Acts::IntegrationTest::readFieldXYZ (std::function< size_t(std::array< size_t, 3 > binsXYZ, std::array< size_t, 3 > nBinsXYZ)> localToGlobalBin, std::string fieldMapFile = "Field.txt", double lengthUnit = 1., double BFieldUnit = 1., size_t nPoints = 100000, bool firstOctant = false)
[1] Read in field map file
Definition at line 42 of file PropagationTestsAtlasField.cpp.
View newest version in sPHENIX GitHub at line 42 of file PropagationTestsAtlasField.cpp
References bField, Acts::fieldMapperXYZ(), getline, x, analysis::y, and z.
Referenced by atlasBField().
RiddersEigenPropagatorType Acts::IntegrationTest::repropagator (std:: moverestepper)
Referenced by BOOST_DATA_TEST_CASE().
RiddersStraightPropagatorType Acts::IntegrationTest::rspropagator (std:: moversstepper)
Referenced by BOOST_DATA_TEST_CASE().
DensePropagatorType Acts::IntegrationTest::setupDensePropagator ()
Definition at line 81 of file PropagationTests.cpp.
View newest version in sPHENIX GitHub at line 81 of file PropagationTests.cpp
References Acts::units::_m, analysis::e, Acts::CuboidVolumeBuilder::VolumeConfig::length, Acts::CuboidVolumeBuilder::VolumeConfig::position, Acts::CuboidVolumeBuilder::Config::volumeCfg, and Acts::CuboidVolumeBuilder::VolumeConfig::volumeMaterial.
Referenced by BOOST_DATA_TEST_CASE().
StraightPropagatorType Acts::IntegrationTest::spropagator (std:: movesstepper)
Referenced by BOOST_DATA_TEST_CASE().
template<typename Propagator_type > std::pair<Vector3D, double> Acts::IntegrationTest::to_cylinder (const Propagator_type & propagator, double pT, double phi, double theta, double charge, double plimit, double rand1, double rand2, double , bool covtransport = false, bool debug = false)
Definition at line 238 of file PropagationTestHelper.hpp.
View newest version in sPHENIX GitHub at line 238 of file PropagationTestHelper.hpp
References Acts::units::_e, Acts::units::_GeV, Acts::units::_mm, charge, cos(), createCylindricTransform(), debug, Acts::PropagatorOptions< action_list_t, aborter_list_t >::debug, max, Acts::PropagatorOptions< action_list_t, aborter_list_t >::maxStepSize, mfContext, charm_jet_coverage::mom, eicpy.build::options, Acts::PropagatorOptions< action_list_t, aborter_list_t >::pathLimit, Acts::Test::pos, tgContext, Acts::VectorHelpers::time(), x, analysis::y, and z.
Referenced by BOOST_DATA_TEST_CASE().
template<typename Propagator_type , typename SurfaceType > std::pair<Vector3D, double> Acts::IntegrationTest::to_surface (const Propagator_type & propagator, double pT, double phi, double theta, double charge, double plimit, double rand1, double rand2, double rand3, bool planar = true, bool covtransport = false, bool debug = false)
Definition at line 313 of file PropagationTestHelper.hpp.
View newest version in sPHENIX GitHub at line 313 of file PropagationTestHelper.hpp
References Acts::units::_e, Acts::units::_GeV, Acts::units::_mm, charge, cos(), createCylindricTransform(), createPlanarTransform(), debug, Acts::PropagatorOptions< action_list_t, aborter_list_t >::debug, Acts::PropagatorOptions< action_list_t, aborter_list_t >::maxStepSize, mfContext, charm_jet_coverage::mom, eicpy.build::options, Acts::PropagatorOptions< action_list_t, aborter_list_t >::pathLimit, Acts::Test::pos, ds::rand1, ds::rand2, ds::rand3, tgContext, Acts::VectorHelpers::time(), x, analysis::y, and z.
StreamWrapper Acts::IntegrationTest::valid (std:: ofstream"magfield_lookup.csv")
Referenced by BOOST_DATA_TEST_CASE(), QAG4Util::interpolate(), tofBarrel::maxP(), and tofBarrel::numSigma().
Variable Documentation
AtlasStepperType Acts::IntegrationTest::astepper(bFieldSharedA) (bField)
Acts::IntegrationTest::auto[volumes, tg] = gridBoxFactory()
Definition at line 78 of file BVHNavigationTest.cpp.
View newest version in sPHENIX GitHub at line 78 of file BVHNavigationTest.cpp
auto Acts::IntegrationTest::bField = atlasBField("Field.txt")
Definition at line 114 of file PropagationTestsAtlasField.cpp.
View newest version in sPHENIX GitHub at line 114 of file PropagationTestsAtlasField.cpp
Referenced by Acts::Test::BOOST_AUTO_TEST_CASE(), Acts::Test::BOOST_DATA_TEST_CASE(), ClassImp(), FWE::VertexFindingAlgorithm::execute(), FWE::VertexFitAlgorithm::execute(), FW::TruthVerticesToTracksAlgorithm::execute(), FW::BField::txt::fieldMapperRZ(), FW::BField::root::fieldMapperRZ(), FW::BField::txt::fieldMapperXYZ(), FW::BField::root::fieldMapperXYZ(), PHActsInitialVertexFinder::findVertices(), PHActsVertexFinder::findVertices(), PHActsVertexFitter::fitVertex(), main(), materialValidationExample(), propagationExample(), readFieldXYZ(), FW::RootBFieldWriter< bfield_t >::run(), and FW::BField::writeField().
auto Acts::IntegrationTest::bFieldMap = makeFieldMap(bSolenoidField)
Definition at line 88 of file InterpolatedSolenoidBFieldTest.cpp.
View newest version in sPHENIX GitHub at line 88 of file InterpolatedSolenoidBFieldTest.cpp
Referenced by BOOST_DATA_TEST_CASE(), and main().
auto Acts::IntegrationTest::bFieldSharedA = SharedFieldType(bField)
Definition at line 115 of file PropagationTestsAtlasField.cpp.
View newest version in sPHENIX GitHub at line 115 of file PropagationTestsAtlasField.cpp
auto Acts::IntegrationTest::bFieldSharedE = SharedFieldType(bField)
Definition at line 116 of file PropagationTestsAtlasField.cpp.
View newest version in sPHENIX GitHub at line 116 of file PropagationTestsAtlasField.cpp
const double Acts::IntegrationTest::bMagCenter = 2_T
Definition at line 39 of file InterpolatedSolenoidBFieldTest.cpp.
View newest version in sPHENIX GitHub at line 39 of file InterpolatedSolenoidBFieldTest.cpp
Referenced by main().
Acts::SolenoidBField Acts::IntegrationTest::bSolenoidField({R, L, nCoils, bMagCenter})
Referenced by BOOST_DATA_TEST_CASE(), and main().
double Acts::IntegrationTest::Bz = 2_T
Definition at line 64 of file PropagationTests.cpp.
View newest version in sPHENIX GitHub at line 64 of file PropagationTests.cpp
Referenced by BOOST_DATA_TEST_CASE(), BOOST_DATA_TEST_CASE(), Acts::Test::BOOST_DATA_TEST_CASE(), LSLEQM::eval(), FW::BField::root::fieldMapperRZ(), FW::BField::root::fieldMapperXYZ(), genfit::Field::get(), genfit::AbsBField::get(), PHTpcTrackFollower::get_projected_coordinate(), GPUTPCBaseTrackParam::GetKappa(), PHTpcTracker::getMagField(), genfit::HelixTrackModel::HelixTrackModel(), Acts::HelicalTrackLinearizer< propagator_t, propagator_options_t >::linearizeTrack(), PHField2D::PHField2D(), PHField3DCylindrical::PHField3DCylindrical(), printBField(), PHGenFitTrackProjection::process_event(), FW::RootBFieldWriter< bfield_t >::run(), Acts::ConstantBField::setField(), FW::BField::ScalableBField::setField(), and GPUTPCTrackParam::TransportToX().
const bool Acts::IntegrationTest::covtpr = true
Definition at line 60 of file PropagationTests.cpp.
View newest version in sPHENIX GitHub at line 60 of file PropagationTests.cpp
Referenced by BOOST_DATA_TEST_CASE().
const bool Acts::IntegrationTest::debug = false
Definition at line 61 of file PropagationTests.cpp.
View newest version in sPHENIX GitHub at line 61 of file PropagationTests.cpp
Referenced by Acts::Test::BOOST_AUTO_TEST_CASE(), BOOST_DATA_TEST_CASE(), constant_field_propagation(), covariance_bound(), covariance_curvilinear(), ElementsToBoundaryConditions(), foward_backward(), LoadCGsimMesh(), LoadComsolMesh(), LoadGidInput(), LoadUniversalMesh(), main(), genfit::MeasurementCreator::setDebug(), to_cylinder(), and to_surface().
DenseStepperType Acts::IntegrationTest::dstepper(bField)
EigenStepperType Acts::IntegrationTest::estepper(bFieldSharedE) (bField)
Referenced by Acts::Test::BOOST_DATA_TEST_CASE().
unsigned int Acts::IntegrationTest::itest = 0
Definition at line 22 of file PropagationTests.cpp.
View newest version in sPHENIX GitHub at line 22 of file PropagationTests.cpp
const double Acts::IntegrationTest::L = 5.8_m
Definition at line 36 of file InterpolatedSolenoidBFieldTest.cpp.
View newest version in sPHENIX GitHub at line 36 of file InterpolatedSolenoidBFieldTest.cpp
Referenced by BOOST_DATA_TEST_CASE(), EicToyModel::CalculateDefaultEtaBoundaries(), tetgenmesh::checktet4split(), oncsSub_iduppetdata_v104::decode(), oncsSub_iduppetdata::decode(), Acts::Polyhedron::extent(), LSLTrackRep::getGlobalCov(), tetgenmesh::getsteinerptonsegment(), main(), makeFieldMap(), tofBarrel::maxP(), tofBarrel::numSigma(), tetgenmesh::outvoronoi(), Acts::ProtoLayer::radialDistance(), EicToyModel::RebuildCrack(), and Similarity().
MagneticFieldContext Acts::IntegrationTest::mfContext = MagneticFieldContext()
Definition at line 15 of file BVHNavigationTest.cpp.
View newest version in sPHENIX GitHub at line 15 of file BVHNavigationTest.cpp
Referenced by constant_field_propagation(), covariance_bound(), covariance_curvilinear(), foward_backward(), to_cylinder(), and to_surface().
const size_t Acts::IntegrationTest::nBinsR = 150
Definition at line 40 of file InterpolatedSolenoidBFieldTest.cpp.
View newest version in sPHENIX GitHub at line 40 of file InterpolatedSolenoidBFieldTest.cpp
Referenced by Acts::Test::BOOST_FIXTURE_TEST_CASE(), Acts::fieldMapperRZ(), main(), makeFieldMap(), Acts::materialMapperRZ(), FW::RootBFieldWriter< bfield_t >::run(), and Acts::solenoidFieldMapper().
const size_t Acts::IntegrationTest::nBinsZ = 200
Definition at line 41 of file InterpolatedSolenoidBFieldTest.cpp.
View newest version in sPHENIX GitHub at line 41 of file InterpolatedSolenoidBFieldTest.cpp
Referenced by Acts::fieldMapperRZ(), Acts::fieldMapperXYZ(), main(), makeFieldMap(), Acts::materialMapperRZ(), Acts::materialMapperXYZ(), FW::RootBFieldWriter< bfield_t >::run(), and Acts::solenoidFieldMapper().
const size_t Acts::IntegrationTest::nCoils = 1154
Definition at line 38 of file InterpolatedSolenoidBFieldTest.cpp.
View newest version in sPHENIX GitHub at line 38 of file InterpolatedSolenoidBFieldTest.cpp
Referenced by main().
const int Acts::IntegrationTest::ntests = 10000
Definition at line 100 of file InterpolatedSolenoidBFieldTest.cpp.
View newest version in sPHENIX GitHub at line 100 of file InterpolatedSolenoidBFieldTest.cpp
const double Acts::IntegrationTest::R = (2.56 + 2.46) * 0.5 * 0.5_m
Definition at line 37 of file InterpolatedSolenoidBFieldTest.cpp.
View newest version in sPHENIX GitHub at line 37 of file InterpolatedSolenoidBFieldTest.cpp
Referenced by dfe::Dispatcher::add(), FluxMonitorGrid::AddEntry(), ALICEKF::ALICEKalmanFilter(), Acts::CylinderSurface::binningPosition(), BOOST_DATA_TEST_CASE(), Acts::Test::BOOST_FIXTURE_TEST_CASE(), CbmRichRingFitterQa::CalculateFitErrors(), GFKalman::chi2Increment(), kdfinder::CircleFit< T >::CircleFitByChernovHoussam(), PHActsSiliconSeeding::circleFitSeed(), InttClusterizer::ClusterLadderCells(), MvtxClusterizer::ClusterMvtx(), PHActsSiliconSeeding::createSvtxTrack(), fbst(), nucleus::formFactor(), Gammaavectormeson::Gammaavectormeson(), CylinderGeom_Mvtx::get_local_from_world_coords(), PHGenFitTrkFitter::get_rotation_matrix(), PHGenFitTrkFitter::get_vertex_error_uvn(), CylinderGeom_Mvtx::get_world_from_local_coords(), PHTpcTrackSeedVertexAssoc::GetCircleClusterResiduals(), PHG4OuterHcalField::GetFieldValue(), GFTools::getSmoothedChiSqu(), Gammaavectormeson::getSpinMatrixElement(), kdfinder::CircleFit< T >::GradientHessian(), EicTpcDigiHitProducer::HandleHit(), EicKfNodeTemplate::IncrementLinearTrackFitMatrices(), Acts::CylinderSurface::intersectionSolver(), linear_expansion_sum(), linear_expansion_sum_zeroelim(), Acts::HelicalTrackLinearizer< propagator_t, propagator_options_t >::linearizeTrack(), main(), makeFieldMap(), FwdHoughTree::MappingCall(), PHSimpleKFProp::MoveToFirstTPCCluster(), PHSimpleKFProp::MoveToVertex(), PHGenFitTrkFitter::pos_cov_uvn_to_rz(), PHGenFitTrkFitter::pos_cov_XYZ_to_RZ(), PHTpcTrackSeedVertexAssoc::Process(), PHMicromegasTpcTrackMatching::Process(), PHTpcClusterMover::process_event(), genfit::KalmanFitter::processTrackPoint(), genfit::KalmanFitterRefTrack::processTrackPointSqrt(), Acts::Legacy::AtlasSeedfinder< SpacePoint >::production3Sp(), genfit::RKTrackRep::RKPropagate(), genfit::RKTrackRep::RKutta(), RKTrackRep::RKutta(), PHPy6JetTrigger::SetJetR(), PHPy8JetTrigger::SetJetR(), Similarity(), Acts::AtlasStepper< ConstantBField >::step(), Acts::SurfaceArrayCreator::surfaceArrayOnCylinder(), PHG4GDMLWriteStructure::TraverseVolumeTree(), and PHG4GDMLWrite::Write().
AtlasStepperType Acts::IntegrationTest::rastepper(bField)
EigenStepperType Acts::IntegrationTest::restepper(bField)
StraightLineStepper Acts::IntegrationTest::rsstepper
Definition at line 74 of file PropagationTests.cpp.
View newest version in sPHENIX GitHub at line 74 of file PropagationTests.cpp
const int Acts::IntegrationTest::skip = 0
Definition at line 59 of file PropagationTests.cpp.
View newest version in sPHENIX GitHub at line 59 of file PropagationTests.cpp
Referenced by AnalyseEvents(), BOOST_DATA_TEST_CASE(), Acts::Test::BOOST_DATA_TEST_CASE(), FindParentSide(), RemoveCrap(), Acts::Test::runTest(), and Acts::AxisAlignedBoundingBox< entity_t, value_t, DIM >::setSkip().
StraightLineStepper Acts::IntegrationTest::sstepper
Definition at line 71 of file PropagationTests.cpp.
View newest version in sPHENIX GitHub at line 71 of file PropagationTests.cpp
GeometryContext Acts::IntegrationTest::tgContext = GeometryContext()
Definition at line 14 of file BVHNavigationTest.cpp.
View newest version in sPHENIX GitHub at line 14 of file BVHNavigationTest.cpp
Referenced by constant_field_propagation(), covariance_bound(), covariance_curvilinear(), foward_backward(), to_cylinder(), and to_surface().