EIC Software: PndTrackCandHit Class Reference
PndTrackCandHit Class Reference
#include <EicRoot/blob/master/pnddata/TrackData/PndTrackCandHit.h>
Public Member Functions
PndTrackCandHit ()
PndTrackCandHit (Int_t detId, Int_t hitId, Double_t rho)
~PndTrackCandHit ()
bool operator< (const PndTrackCandHit &rhs) const
bool operator> (const PndTrackCandHit &rhs) const
bool operator<= (const PndTrackCandHit &rhs) const
bool operator>= (const PndTrackCandHit &rhs) const
bool operator== (const PndTrackCandHit &hit) const
bool operator!= (const PndTrackCandHit &hit) const
Int_t GetHitId () const
Int_t GetDetId () const
Double_t GetRho () const
void Print ()
Public Member Functions inherited from FairLink
FairLink ()
FairLink (Int_t type, Int_t index, Float_t weight=1.)
FairLink (TString branchName, Int_t index, Float_t weight=1.)
FairLink (Int_t file, Int_t entry, Int_t type, Int_t index, Float_t weight=1.)
FairLink (Int_t file, Int_t entry, TString branchName, Int_t index, Float_t weight=1.)
virtual ~FairLink ()
void SetLink (Int_t file, Int_t entry, Int_t type, Int_t index, Float_t weight=1.)
void SetLink (Int_t type, Int_t index, Float_t weight=1.)
Int_t GetFile () const
Int_t GetEntry () const
Int_t GetType () const
Int_t GetIndex () const
Float_t GetWeight () const
void SetWeight (Float_t weight)
void AddWeight (Float_t weight)
virtual void Print (std::ostream &out=std::cout) const
virtual bool operator== (const FairLink &link) const
virtual bool operator< (const FairLink &link) const
ClassDef (FairLink, 3)
Private Member Functions
ClassDef (PndTrackCandHit, 2)
Private Attributes
Double_t fRho
sorting parameter
Detailed Description
Definition at line 30 of file PndTrackCandHit.h.
View newest version in sPHENIX GitHub at line 30 of file PndTrackCandHit.h
Constructor & Destructor Documentation
PndTrackCandHit::PndTrackCandHit () inline
Definition at line 32 of file PndTrackCandHit.h.
View newest version in sPHENIX GitHub at line 32 of file PndTrackCandHit.h
PndTrackCandHit::PndTrackCandHit (Int_t detId, Int_t hitId, Double_t rho) inline
Definition at line 33 of file PndTrackCandHit.h.
View newest version in sPHENIX GitHub at line 33 of file PndTrackCandHit.h
PndTrackCandHit::~PndTrackCandHit () inline
Definition at line 34 of file PndTrackCandHit.h.
View newest version in sPHENIX GitHub at line 34 of file PndTrackCandHit.h
Member Function Documentation
PndTrackCandHit::ClassDef (PndTrackCandHit , 2) private
Int_t PndTrackCandHit::GetDetId () const inline
Definition at line 50 of file PndTrackCandHit.h.
View newest version in sPHENIX GitHub at line 50 of file PndTrackCandHit.h
References FairLink::GetType().
Referenced by PndRecoKalmanFit::Fit(), PndTrackCand::GetNHitsDet(), and PndTrackCand2GenfitTrackCand().
Int_t PndTrackCandHit::GetHitId () const inline
Definition at line 49 of file PndTrackCandHit.h.
View newest version in sPHENIX GitHub at line 49 of file PndTrackCandHit.h
References FairLink::GetIndex().
Referenced by PndRecoKalmanFit::Fit(), and PndTrackCand2GenfitTrackCand().
Double_t PndTrackCandHit::GetRho () const inline
Definition at line 51 of file PndTrackCandHit.h.
View newest version in sPHENIX GitHub at line 51 of file PndTrackCandHit.h
References fRho.
Referenced by PndTrackCand2GenfitTrackCand().
bool PndTrackCandHit::operator!= (const PndTrackCandHit & hit) const inline
Definition at line 46 of file PndTrackCandHit.h.
View newest version in sPHENIX GitHub at line 46 of file PndTrackCandHit.h
bool PndTrackCandHit::operator< (const PndTrackCandHit & rhs) const inline
Definition at line 35 of file PndTrackCandHit.h.
View newest version in sPHENIX GitHub at line 35 of file PndTrackCandHit.h
References fRho.
bool PndTrackCandHit::operator<= (const PndTrackCandHit & rhs) const inline
Definition at line 39 of file PndTrackCandHit.h.
View newest version in sPHENIX GitHub at line 39 of file PndTrackCandHit.h
References fRho.
bool PndTrackCandHit::operator== (const PndTrackCandHit & hit) const inline
Definition at line 43 of file PndTrackCandHit.h.
View newest version in sPHENIX GitHub at line 43 of file PndTrackCandHit.h
References fRho.
bool PndTrackCandHit::operator> (const PndTrackCandHit & rhs) const inline
Definition at line 37 of file PndTrackCandHit.h.
View newest version in sPHENIX GitHub at line 37 of file PndTrackCandHit.h
References fRho.
bool PndTrackCandHit::operator>= (const PndTrackCandHit & rhs) const inline
Definition at line 41 of file PndTrackCandHit.h.
View newest version in sPHENIX GitHub at line 41 of file PndTrackCandHit.h
References fRho.
void PndTrackCandHit::Print (void)
Definition at line 4 of file PndTrackCandHit.cxx.
View newest version in sPHENIX GitHub at line 4 of file PndTrackCandHit.cxx
References fRho, and FairLink::Print().
Member Data Documentation
Double_t PndTrackCandHit::fRho private
sorting parameter
Definition at line 56 of file PndTrackCandHit.h.
View newest version in sPHENIX GitHub at line 56 of file PndTrackCandHit.h
Referenced by GetRho(), operator<(), operator<=(), operator==(), operator>(), operator>=(), and Print().
The documentation for this class was generated from the following files:
EicRoot/blob/master/pnddata/TrackData/PndTrackCandHit.h
EicRoot/blob/master/pnddata/TrackData/PndTrackCandHit.cxx