EIC Software: EicRoot/blob/master/pCDR-2018/madx/extractor.cc File Reference
extractor.cc File Reference
#include <vector>
#include <map>
#include <string>
#include <math.h>
#include <assert.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
Classes
class Bore
class MagElement
class Dipole
class Quadrupole
class BeamLine
Macros
#define _APERTURE_RADIUS_DEFAULT_ (0.01)
#define _ZMIN_ (-40.00)
#define _ZMAX_ (40.00)
Functions
static char * GetTrueElementName (const char *name)
static bool IsElementStartLine (const char *name)
static bool IsElementEndLine (const char *name)
int main (int argc, char **argv)
Variables
static std::map< std::string,
Bore * > bores
Macro Definition Documentation
#define _APERTURE_RADIUS_DEFAULT_ (0.01)
Definition at line 26 of file extractor.cc.
View newest version in sPHENIX GitHub at line 26 of file extractor.cc
#define _ZMAX_ (40.00)
Definition at line 32 of file extractor.cc.
View newest version in sPHENIX GitHub at line 32 of file extractor.cc
Referenced by main().
#define _ZMIN_ (-40.00)
Definition at line 30 of file extractor.cc.
View newest version in sPHENIX GitHub at line 30 of file extractor.cc
Referenced by main().
Function Documentation
static char* GetTrueElementName (const char * name) static
Definition at line 137 of file extractor.cc.
View newest version in sPHENIX GitHub at line 137 of file extractor.cc
Referenced by main().
static bool IsElementEndLine (const char * name) static
Definition at line 167 of file extractor.cc.
View newest version in sPHENIX GitHub at line 167 of file extractor.cc
Referenced by main().
static bool IsElementStartLine (const char * name) static
Definition at line 158 of file extractor.cc.
View newest version in sPHENIX GitHub at line 158 of file extractor.cc
Referenced by main().
int main (int argc, char ** argv)
Definition at line 175 of file extractor.cc.
View newest version in sPHENIX GitHub at line 175 of file extractor.cc
References _ZMAX_, _ZMIN_, BeamLine::AddDataFile(), BeamLine::AddSurveyFile(), BeamLine(), bores, MagElement::Calculate(), exit(), GetTrueElementName(), IsElementEndLine(), IsElementStartLine(), it, Acts::IntegrationTest::L, M_PI, BeamLine::mAllFiles, BeamLine::mBrho, BeamLine::mDataFiles, BeamLine::mDataParNum, MagElement::mLength, BeamLine::mMagElements, BeamLine::mOrderedMagElements, MagElement::mSend, MagElement::mSstart, BeamLine::mSurveyFiles, BeamLine::mSurveyParNum, MagElement::mTHETA, MagElement::mTHETAend, MagElement::mTHETAstart, MagElement::mX, MagElement::mXend, MagElement::mXstart, MagElement::mY, MagElement::mYend, MagElement::mYstart, MagElement::mZ, MagElement::mZend, MagElement::mZstart, name, MagElement::Print(), Dipole::Print(), Quadrupole::Print(), printf(), and value.
Variable Documentation
std::map<std::string, Bore*> bores static
Definition at line 43 of file extractor.cc.
View newest version in sPHENIX GitHub at line 43 of file extractor.cc
Referenced by MagElement::MagElement(), and main().