EIC Software: PndMCTrack Class Reference
PndMCTrack Class Reference
#include <EicRoot/blob/master/pnddata/PndMCTrack.h>
Public Member Functions
PndMCTrack ()
PndMCTrack (const PndMCTrack &track)
PndMCTrack (TParticle *particle)
virtual ~PndMCTrack ()
void Print (Int_t iTrack) const
Int_t GetPdgCode () const
Int_t GetMotherID () const
Int_t GetSecondMotherID () const
TVector3 GetStartVertex () const
Double_t GetStartTime () const
TVector3 GetMomentum () const
Double_t GetPt () const
Bool_t IsGeneratorCreated (void) const
Bool_t IsGeneratorDecayed (void) const
Bool_t IsGeneratorLast (void) const
void SetGeneratorCreated (void)
void SetGeneratorDecayed (void)
Int_t GetNPoints (DetectorId detId) const
void SetMotherID (Int_t id)
void SetSecondMotherID (Int_t id)
void SetNPoints (Int_t iDet, Int_t np)
TLorentzVector Get4Momentum () const
Private Member Functions
ClassDef (PndMCTrack, 1)
Private Attributes
Int_t fPdgCode
Double32_t fPx
Double32_t fPy
Double32_t fPz
Double32_t fE
Int_t fMotherID
Int_t fSecondMotherID
Int_t fGeneratorFlags
Double32_t fStartX
Double32_t fStartY
Double32_t fStartZ
Double32_t fStartT
Int_t fPoints
Detailed Description
PndMCTrack.h
Author
V.Friese v.fri.nosp@m.ese@.nosp@m.gsi.d.nosp@m.e
Data class for storing Monte Carlo tracks processed by the PndStack. A MCTrack can be a primary track put into the simulation or a secondary one produced by the transport through decay or interaction.
Definition at line 33 of file PndMCTrack.h.
View newest version in sPHENIX GitHub at line 33 of file PndMCTrack.h
Constructor & Destructor Documentation
PndMCTrack::PndMCTrack ()
Default constructor
Definition at line 14 of file PndMCTrack.cxx.
View newest version in sPHENIX GitHub at line 14 of file PndMCTrack.cxx
PndMCTrack::PndMCTrack (const PndMCTrack & track)
Standard constructor Copy constructor
Definition at line 53 of file PndMCTrack.cxx.
View newest version in sPHENIX GitHub at line 53 of file PndMCTrack.cxx
PndMCTrack::PndMCTrack (TParticle * particle)
Constructor from TParticle
Definition at line 68 of file PndMCTrack.cxx.
View newest version in sPHENIX GitHub at line 68 of file PndMCTrack.cxx
PndMCTrack::~PndMCTrack () virtual
Destructor
Definition at line 89 of file PndMCTrack.cxx.
View newest version in sPHENIX GitHub at line 89 of file PndMCTrack.cxx
Member Function Documentation
PndMCTrack::ClassDef (PndMCTrack , 1) private
TLorentzVector PndMCTrack::Get4Momentum () const
Definition at line 102 of file PndMCTrack.cxx.
View newest version in sPHENIX GitHub at line 102 of file PndMCTrack.cxx
References fE, fPx, fPy, and fPz.
TVector3 PndMCTrack::GetMomentum () const inline
Definition at line 71 of file PndMCTrack.h.
View newest version in sPHENIX GitHub at line 71 of file PndMCTrack.h
References fPx, fPy, and fPz.
Referenced by analysis(), for(), and EicRcParticle::GetMcVtxMomentum().
Int_t PndMCTrack::GetMotherID () const inline
Definition at line 67 of file PndMCTrack.h.
View newest version in sPHENIX GitHub at line 67 of file PndMCTrack.h
References fMotherID.
Referenced by analysis(), PndStack::SetGeneratorFlags(), and PndStack::UpdateTrackIndex().
Int_t PndMCTrack::GetNPoints (DetectorId detId) const
Definition at line 120 of file PndMCTrack.cxx.
View newest version in sPHENIX GitHub at line 120 of file PndMCTrack.cxx
References fPoints, kDRC, kDSK, kEMC, kFTOF, kFTS, kGEM, kHYP, kHYPG, kLUMI, kMDT, kMVD, kRICH, kRPC, kSTT, and kTOF.
Int_t PndMCTrack::GetPdgCode () const inline
Accessors
Definition at line 66 of file PndMCTrack.h.
View newest version in sPHENIX GitHub at line 66 of file PndMCTrack.h
References fPdgCode.
Referenced by analysis(), PndPidCorrelator::ConstructChargedCandidate(), EicSmearTask::Exec(), PndRecoKalmanTask::Exec(), EicIdealTrackingCode::Exec(), and EicRcParticle::GetMcPdgCode().
Double_t PndMCTrack::GetPt () const inline
Definition at line 72 of file PndMCTrack.h.
View newest version in sPHENIX GitHub at line 72 of file PndMCTrack.h
References fPx, and fPy.
Int_t PndMCTrack::GetSecondMotherID () const inline
Definition at line 68 of file PndMCTrack.h.
View newest version in sPHENIX GitHub at line 68 of file PndMCTrack.h
References fSecondMotherID.
Referenced by PndStack::UpdateTrackIndex().
Double_t PndMCTrack::GetStartTime () const inline
Definition at line 70 of file PndMCTrack.h.
View newest version in sPHENIX GitHub at line 70 of file PndMCTrack.h
References fStartT.
TVector3 PndMCTrack::GetStartVertex () const inline
Definition at line 69 of file PndMCTrack.h.
View newest version in sPHENIX GitHub at line 69 of file PndMCTrack.h
References fStartX, fStartY, and fStartZ.
Referenced by EicRcParticle::GetMcVertex().
Bool_t PndMCTrack::IsGeneratorCreated (void) const inline
Definition at line 77 of file PndMCTrack.h.
View newest version in sPHENIX GitHub at line 77 of file PndMCTrack.h
References fGeneratorFlags.
Bool_t PndMCTrack::IsGeneratorDecayed (void) const inline
Definition at line 78 of file PndMCTrack.h.
View newest version in sPHENIX GitHub at line 78 of file PndMCTrack.h
References fGeneratorFlags, and x2.
Bool_t PndMCTrack::IsGeneratorLast (void) const inline
Definition at line 79 of file PndMCTrack.h.
View newest version in sPHENIX GitHub at line 79 of file PndMCTrack.h
References fGeneratorFlags.
void PndMCTrack::Print (Int_t iTrack) const
Output to screen
Definition at line 95 of file PndMCTrack.cxx.
View newest version in sPHENIX GitHub at line 95 of file PndMCTrack.cxx
References fE, fGeneratorFlags, fMotherID, fPdgCode, fPx, fPy, fPz, and fSecondMotherID.
void PndMCTrack::SetGeneratorCreated (void) inline
Definition at line 80 of file PndMCTrack.h.
View newest version in sPHENIX GitHub at line 80 of file PndMCTrack.h
References fGeneratorFlags.
Referenced by PndStack::SetGeneratorFlags().
void PndMCTrack::SetGeneratorDecayed (void) inline
Definition at line 81 of file PndMCTrack.h.
View newest version in sPHENIX GitHub at line 81 of file PndMCTrack.h
References fGeneratorFlags.
Referenced by PndStack::SetGeneratorFlags().
void PndMCTrack::SetMotherID (Int_t id) inline
Modifiers
Definition at line 86 of file PndMCTrack.h.
View newest version in sPHENIX GitHub at line 86 of file PndMCTrack.h
References fMotherID.
Referenced by PndStack::UpdateTrackIndex().
void PndMCTrack::SetNPoints (Int_t iDet, Int_t np)
Add one detector point to the fPoint variable
Definition at line 143 of file PndMCTrack.cxx.
View newest version in sPHENIX GitHub at line 143 of file PndMCTrack.cxx
References fPoints, kDRC, kDSK, kEMC, kFTOF, kFTS, kGEM, kHYP, kHYPG, kLUMI, kMDT, kMVD, kRICH, kRPC, kSTT, and kTOF.
Referenced by PndStack::FillTrackArray().
void PndMCTrack::SetSecondMotherID (Int_t id) inline
Definition at line 87 of file PndMCTrack.h.
View newest version in sPHENIX GitHub at line 87 of file PndMCTrack.h
References fSecondMotherID.
Referenced by PndStack::UpdateTrackIndex().
Member Data Documentation
Double32_t PndMCTrack::fE private
Definition at line 110 of file PndMCTrack.h.
View newest version in sPHENIX GitHub at line 110 of file PndMCTrack.h
Referenced by Get4Momentum(), and Print().
Int_t PndMCTrack::fGeneratorFlags private
Flag if particle was created (bit 0) and/or decayed (bit 1) by generator
Definition at line 117 of file PndMCTrack.h.
View newest version in sPHENIX GitHub at line 117 of file PndMCTrack.h
Referenced by IsGeneratorCreated(), IsGeneratorDecayed(), IsGeneratorLast(), Print(), SetGeneratorCreated(), and SetGeneratorDecayed().
Int_t PndMCTrack::fMotherID private
Index of mother track. Zero(Minus One???) for primary particles.
Definition at line 113 of file PndMCTrack.h.
View newest version in sPHENIX GitHub at line 113 of file PndMCTrack.h
Referenced by GetMotherID(), Print(), and SetMotherID().
Int_t PndMCTrack::fPdgCode private
PDG particle code
Definition at line 107 of file PndMCTrack.h.
View newest version in sPHENIX GitHub at line 107 of file PndMCTrack.h
Referenced by GetPdgCode(), and Print().
Int_t PndMCTrack::fPoints private
Bitvector representing the number of MCPoints for this track in each subdetector. The detectors are represented by This goes to fPoints: DRC: Bit 0 - 1 (2 bit max. value 3) MDT: Bit 2 - 3 (2 bit max. value 3) MVD: Bit 4 - 5 (2 bit max. value 3) DCH: Bit 6 - 7 (2 bit max. value 3) EMC: Bit 8 - 9 (2 bit max. value 3) STT: Bit 10 - 11 (2 bit max. value 3) TPC: Bit 12 - 13 (2 bit max. value 3) TOF: Bit 14 - 15 (2 bit max. value 3) GEM: Bit 16 - 17 (2 bit max. value 3) DSK: Bit 18 - 19 (2 bit max. value 3) HYP: Bit 20 - 21 (2 bit max. value 3) RPC: Bit 22 - 23 (2 bit max. value 3) LUMI: Bit 24 - 25 (2 bit max. value 3) HYPG: Bit 26 - 27 (2 bit max. value 3) FTS: Bit 28 - 29 (2 bit max. value 3)
The respective point numbers can be accessed and modified
Definition at line 143 of file PndMCTrack.h.
View newest version in sPHENIX GitHub at line 143 of file PndMCTrack.h
Referenced by GetNPoints(), and SetNPoints().
Double32_t PndMCTrack::fPx private
Momentum components at production [GeV]
Definition at line 110 of file PndMCTrack.h.
View newest version in sPHENIX GitHub at line 110 of file PndMCTrack.h
Referenced by Get4Momentum(), GetMomentum(), GetPt(), and Print().
Double32_t PndMCTrack::fPy private
Definition at line 110 of file PndMCTrack.h.
View newest version in sPHENIX GitHub at line 110 of file PndMCTrack.h
Referenced by Get4Momentum(), GetMomentum(), GetPt(), and Print().
Double32_t PndMCTrack::fPz private
Definition at line 110 of file PndMCTrack.h.
View newest version in sPHENIX GitHub at line 110 of file PndMCTrack.h
Referenced by Get4Momentum(), GetMomentum(), and Print().
Int_t PndMCTrack::fSecondMotherID private
Definition at line 114 of file PndMCTrack.h.
View newest version in sPHENIX GitHub at line 114 of file PndMCTrack.h
Referenced by GetSecondMotherID(), Print(), and SetSecondMotherID().
Double32_t PndMCTrack::fStartT private
Definition at line 120 of file PndMCTrack.h.
View newest version in sPHENIX GitHub at line 120 of file PndMCTrack.h
Referenced by GetStartTime().
Double32_t PndMCTrack::fStartX private
Coordinates of start vertex [cm, ns]
Definition at line 120 of file PndMCTrack.h.
View newest version in sPHENIX GitHub at line 120 of file PndMCTrack.h
Referenced by GetStartVertex().
Double32_t PndMCTrack::fStartY private
Definition at line 120 of file PndMCTrack.h.
View newest version in sPHENIX GitHub at line 120 of file PndMCTrack.h
Referenced by GetStartVertex().
Double32_t PndMCTrack::fStartZ private
Definition at line 120 of file PndMCTrack.h.
View newest version in sPHENIX GitHub at line 120 of file PndMCTrack.h
Referenced by GetStartVertex().
The documentation for this class was generated from the following files:
EicRoot/blob/master/pnddata/PndMCTrack.h
EicRoot/blob/master/pnddata/PndMCTrack.cxx