EIC Software: erhic::LogReaderDjangoh Class Reference
erhic::LogReaderDjangoh Class Reference
#include <eic-smear/blob/master/include/eicsmear/erhic/File.h>
Public Member Functions
LogReaderDjangoh ()
virtual ~LogReaderDjangoh ()
LogReaderDjangoh * Create () const
bool Extract (const std::string &file)
Int_t Save () const
Public Member Functions inherited from erhic::LogReader
LogReader ()
virtual ~LogReader ()
Protected Attributes
TObjString crossSection_
TObjString nEvents_
Total cross section in microbarns
TObjString nTrials_
Total number of events generated and kept
Detailed Description
Processes DJANGOH log files.
Reads a log file and finds the total cross section and the number of generated events when Extract() is called. Writes those values as TObjStrings to the current directory when Save() is called, assuming that directory is writeable.
Definition at line 176 of file File.h.
View newest version in sPHENIX GitHub at line 176 of file File.h
Constructor & Destructor Documentation
erhic::LogReaderDjangoh::LogReaderDjangoh ()
Constructor.
Definition at line 143 of file File.cxx.
View newest version in sPHENIX GitHub at line 143 of file File.cxx
Referenced by Create().
erhic::LogReaderDjangoh::~LogReaderDjangoh () virtual
Destructor.
Definition at line 145 of file File.cxx.
View newest version in sPHENIX GitHub at line 145 of file File.cxx
Member Function Documentation
LogReaderDjangoh * erhic::LogReaderDjangoh::Create () const inline virtual
Return a new LogReaderDjangoh instance.
Implements erhic::LogReader.
Definition at line 213 of file File.h.
View newest version in sPHENIX GitHub at line 213 of file File.h
References LogReaderDjangoh().
bool erhic::LogReaderDjangoh::Extract (const std::string & file) virtual
Extract data from the named log file.
Implements erhic::LogReader.
Definition at line 147 of file File.cxx.
View newest version in sPHENIX GitHub at line 147 of file File.cxx
References crossSection_, getline, in, nEvents, nEvents_, Acts::VectorHelpers::position(), and value.
Int_t erhic::LogReaderDjangoh::Save () const virtual
Write the extracted information to the current file, if it is writeable. If you want to write the LogReaderDjangoh itself, use LogReaderDjangoh::Write().
Implements erhic::LogReader.
Definition at line 227 of file File.cxx.
View newest version in sPHENIX GitHub at line 227 of file File.cxx
References crossSection_, and nEvents_.
Member Data Documentation
TObjString erhic::LogReaderDjangoh::crossSection_ protected
Definition at line 206 of file File.h.
View newest version in sPHENIX GitHub at line 206 of file File.h
Referenced by Extract(), and Save().
TObjString erhic::LogReaderDjangoh::nEvents_ protected
Total cross section in microbarns
Definition at line 207 of file File.h.
View newest version in sPHENIX GitHub at line 207 of file File.h
Referenced by Extract(), and Save().
TObjString erhic::LogReaderDjangoh::nTrials_ protected
Total number of events generated and kept
Definition at line 208 of file File.h.
View newest version in sPHENIX GitHub at line 208 of file File.h
The documentation for this class was generated from the following files:
eic-smear/blob/master/include/eicsmear/erhic/File.h
eic-smear/blob/master/src/erhic/File.cxx