EIC Software: e_starlight Class Reference
e_starlight Class Reference
#include <estarlight/blob/master/include/e_starlight.h>
Public Member Functions
e_starlight ()
~e_starlight ()
bool init ()
eXEvent produceEvent ()
std::string baseFileName () const
unsigned long nmbAttempts () const
unsigned long nmbAccepted () const
double getTotalCrossSection () const
void setInputParameters (inputParameters *inputParams)
Private Member Functions
bool luminosityTableIsValid () const
bool createEventChannel ()
Private Attributes
beamBeamSystem * _beamSystem
eventChannel * _eventChannel
unsigned int _nmbEventsPerFile
std::string _baseFileName
std::string _lumLookUpTableFileName
bool _isInitialised
inputParameters * _inputParameters
Detailed Description
Definition at line 49 of file e_starlight.h.
View newest version in sPHENIX GitHub at line 49 of file e_starlight.h
Constructor & Destructor Documentation
e_starlight::e_starlight ()
Definition at line 65 of file e_starlight.cpp.
View newest version in sPHENIX GitHub at line 65 of file e_starlight.cpp
e_starlight::~e_starlight ()
Definition at line 74 of file e_starlight.cpp.
View newest version in sPHENIX GitHub at line 74 of file e_starlight.cpp
Member Function Documentation
std::string e_starlight::baseFileName () const inline
Definition at line 60 of file e_starlight.h.
View newest version in sPHENIX GitHub at line 60 of file e_starlight.h
References _baseFileName.
bool e_starlight::createEventChannel () private
Definition at line 223 of file e_starlight.cpp.
View newest version in sPHENIX GitHub at line 223 of file e_starlight.cpp
References _beamSystem, _eventChannel, _inputParameters, starlightConstants::A2, starlightConstants::AXION, starlightConstants::E_PHOTONPOMERONNARROW, starlightConstants::E_PHOTONPOMERONWIDE, starlightConstants::ELECTRON, starlightConstants::ETA, starlightConstants::ETAC, starlightConstants::ETAPRIME, starlightConstants::F0, F2, starlightConstants::F2PRIME, starlightConstants::FOURPRONG, inputParameters::interactionType(), starlightConstants::JPSI, starlightConstants::JPSI2S, starlightConstants::JPSI2S_ee, starlightConstants::JPSI2S_mumu, starlightConstants::JPSI_ee, starlightConstants::JPSI_mumu, starlightConstants::MUON, starlightConstants::OMEGA, starlightConstants::OMEGA_pi0gamma, starlightConstants::PHI, printWarn, inputParameters::prodParticleType(), starlightConstants::RHO, starlightConstants::RHOZEUS, starlightConstants::TAUON, starlightConstants::TAUONDECAY, starlightConstants::UPSILON, starlightConstants::UPSILON2S, starlightConstants::UPSILON2S_ee, starlightConstants::UPSILON2S_mumu, starlightConstants::UPSILON3S, starlightConstants::UPSILON3S_ee, starlightConstants::UPSILON3S_mumu, starlightConstants::UPSILON_ee, starlightConstants::UPSILON_mumu, and starlightConstants::ZOVERZ03.
Referenced by init().
double e_starlight::getTotalCrossSection () const inline
Definition at line 63 of file e_starlight.h.
View newest version in sPHENIX GitHub at line 63 of file e_starlight.h
References _eventChannel, and eventChannel::getTotalChannelCrossSection().
Referenced by e_starlightStandalone::run().
bool e_starlight::init ()
Definition at line 79 of file e_starlight.cpp.
View newest version in sPHENIX GitHub at line 79 of file e_starlight.cpp
References _baseFileName, _beamSystem, _inputParameters, _isInitialised, _lumLookUpTableFileName, _nmbEventsPerFile, inputParameters::baseFileName(), createEventChannel(), starlightConstants::E_PHOTONPOMERONNARROW, starlightConstants::E_PHOTONPOMERONWIDE, inputParameters::interactionType(), luminosityTableIsValid(), inputParameters::nmbEvents(), printInfo, printWarn, and inputParameters::targetBeamA().
Referenced by e_starlightStandalone::init().
bool e_starlight::luminosityTableIsValid () const private
Definition at line 172 of file e_starlight.cpp.
View newest version in sPHENIX GitHub at line 172 of file e_starlight.cpp
References _inputParameters, _lumLookUpTableFileName, starlightConstants::deuteronSlopePar, inputParameters::parameterValueKey(), printInfo, and inputParameters::randomSeed().
Referenced by init().
unsigned long e_starlight::nmbAccepted () const inline
Definition at line 62 of file e_starlight.h.
View newest version in sPHENIX GitHub at line 62 of file e_starlight.h
References _eventChannel, and eventChannel::nmbAccepted().
Referenced by e_starlightStandalone::run().
unsigned long e_starlight::nmbAttempts () const inline
Definition at line 61 of file e_starlight.h.
View newest version in sPHENIX GitHub at line 61 of file e_starlight.h
References _eventChannel, and eventChannel::nmbAttempts().
Referenced by e_starlightStandalone::run().
eXEvent e_starlight::produceEvent ()
Definition at line 161 of file e_starlight.cpp.
View newest version in sPHENIX GitHub at line 161 of file e_starlight.cpp
References _eventChannel, _isInitialised, eventChannel::e_produceEvent(), and exit().
Referenced by e_starlightStandalone::run().
void e_starlight::setInputParameters (inputParameters * inputParams) inline
Definition at line 64 of file e_starlight.h.
View newest version in sPHENIX GitHub at line 64 of file e_starlight.h
References _inputParameters.
Referenced by e_starlightStandalone::init().
Member Data Documentation
std::string e_starlight::_baseFileName private
Definition at line 75 of file e_starlight.h.
View newest version in sPHENIX GitHub at line 75 of file e_starlight.h
Referenced by baseFileName(), and init().
beamBeamSystem* e_starlight::_beamSystem private
Definition at line 72 of file e_starlight.h.
View newest version in sPHENIX GitHub at line 72 of file e_starlight.h
Referenced by createEventChannel(), and init().
eventChannel* e_starlight::_eventChannel private
Definition at line 73 of file e_starlight.h.
View newest version in sPHENIX GitHub at line 73 of file e_starlight.h
Referenced by createEventChannel(), getTotalCrossSection(), nmbAccepted(), nmbAttempts(), and produceEvent().
inputParameters* e_starlight::_inputParameters private
Definition at line 78 of file e_starlight.h.
View newest version in sPHENIX GitHub at line 78 of file e_starlight.h
Referenced by createEventChannel(), init(), luminosityTableIsValid(), and setInputParameters().
bool e_starlight::_isInitialised private
Definition at line 77 of file e_starlight.h.
View newest version in sPHENIX GitHub at line 77 of file e_starlight.h
Referenced by init(), and produceEvent().
std::string e_starlight::_lumLookUpTableFileName private
Definition at line 76 of file e_starlight.h.
View newest version in sPHENIX GitHub at line 76 of file e_starlight.h
Referenced by init(), and luminosityTableIsValid().
unsigned int e_starlight::_nmbEventsPerFile private
Definition at line 74 of file e_starlight.h.
View newest version in sPHENIX GitHub at line 74 of file e_starlight.h
Referenced by init().
The documentation for this class was generated from the following files:
estarlight/blob/master/include/e_starlight.h
estarlight/blob/master/src/e_starlight.cpp