EIC Software: fun4all_eicmacros/blob/master/detectors/ModularBeast/G4Setup_ModularDetectorBeast.C File Reference
G4Setup_ModularDetectorBeast.C File Reference
#include <GlobalVariables.C>
#include <G4_Aerogel.C>
#include <G4_Barrel_EIC.C>
#include <G4_AllSilicon.C>
#include <G4_FST_EIC.C>
#include <G4_TTL_EIC.C>
#include <G4_GEM_EIC.C>
#include <G4_Bbc.C>
#include <G4_CEmc_EIC.C>
#include <G4_DIRC.C>
#include <G4_EEMC.C>
#include <G4_FEMC_EIC.C>
#include <G4_FHCAL.C>
#include <G4_EHCAL.C>
#include <G4_HcalIn_ref.C>
#include <G4_HcalOut_ref.C>
#include <G4_Mvtx_EIC.C>
#include <G4_RICH.C>
#include <G4_TPC_EIC.C>
#include <G4_Tracking_Modular.C>
#include <G4_BlackHole.C>
#include <G4_Magnet_Beast.C>
#include <G4_Pipe_EIC.C>
#include <G4_PlugDoor_EIC.C>
#include <G4_User.C>
#include <G4_World.C>
#include <G4_Input.C>
#include <g4detectors/PHG4CylinderSubsystem.h>
#include <g4decayer/EDecayType.hh>
#include <g4eval/PHG4DstCompressReco.h>
#include <g4main/PHG4Reco.h>
#include <g4main/PHG4TruthSubsystem.h>
#include <phfield/PHFieldConfig.h>
#include <fun4all/Fun4AllDstOutputManager.h>
#include <fun4all/Fun4AllServer.h>
Macros
#define MACRO_G4SETUPMODULARDETECTORBEAST_C
Functions
void G4Init ()
void G4Setup (TString specialSetting="")
void ShowerCompress ()
void DstCompress (Fun4AllDstOutputManager *out)
Macro Definition Documentation
#define MACRO_G4SETUPMODULARDETECTORBEAST_C
Definition at line 2 of file G4Setup_ModularDetectorBeast.C.
View newest version in sPHENIX GitHub at line 2 of file G4Setup_ModularDetectorBeast.C
Function Documentation
void DstCompress (Fun4AllDstOutputManager * out)
Definition at line 272 of file G4Setup_ModularDetectorBeast.C.
View newest version in sPHENIX GitHub at line 272 of file G4Setup_ModularDetectorBeast.C
References Fun4AllDstOutputManager::StripNode().
void G4Init ()
Definition at line 51 of file G4Setup_ModularDetectorBeast.C.
View newest version in sPHENIX GitHub at line 51 of file G4Setup_ModularDetectorBeast.C
References Enable::AEROGEL, AerogelInit(), Enable::ALLSILICON, AllSiliconInit(), Enable::BARREL, BarrelInit(), Enable::BBC, BbcInit(), Enable::BLACKHOLE, BlackHoleInit(), Enable::CEMC, CEmcInit(), Enable::CTTL, Enable::DIRC, DIRCInit(), Enable::EEMC, EEMCInit(), Enable::EGEM, Enable::EGEM_FULL, EGEM_Init(), Enable::EHCAL, EHCALInit(), Enable::ETTL, Enable::FEMC, FEMCInit(), Enable::FGEM, FGEM_Init(), Enable::FHCAL, FHCALInit(), Enable::FST, FST_Init(), G4FST::SETTING::FST_TPC, Enable::FTTL, Enable::HCALIN, HCalInnerInit(), Enable::HCALOUT, HCalOuterInit(), Enable::MAGNET, MagnetFieldInit(), MagnetInit(), Enable::MVTX, MvtxInit(), Enable::PIPE, PipeInit(), Enable::PLUGDOOR, PlugDoorInit(), Enable::RICH, RICHInit(), Enable::TPC, TPCInit(), Enable::TRACKING, TrackingInit(), TTL_Init(), Enable::USER, and UserInit().
void G4Setup (TString specialSetting = "")
Definition at line 117 of file G4Setup_ModularDetectorBeast.C.
View newest version in sPHENIX GitHub at line 117 of file G4Setup_ModularDetectorBeast.C
References Enable::AEROGEL, AerogelSetup(), Enable::ALLSILICON, AllSiliconSetup(), Enable::BARREL, Barrel(), Enable::BBC, Bbc(), Enable::BLACKHOLE, BlackHole(), Enable::CEMC, CEmc(), Enable::CTTL, CTTLSetup(), G4P6DECAYER::decayType, Enable::DIRC, DIRCSetup(), Enable::EEMC, EEMCSetup(), Enable::EGEM, EGEMSetup(), Enable::EHCAL, EHCALSetup(), Enable::ETTL, ETTLSetup(), Enable::FEMC, FEMCSetup(), Enable::FGEM, FGEMSetup(), Enable::FHCAL, FHCALSetup(), Enable::FST, FSTSetup(), Enable::FTTL, FTTLSetup(), Enable::HCALIN, HCalInner(), Enable::HCALOUT, HCalOuter(), Fun4AllServer::instance(), kAll, PHFieldConfig::kFieldBeast, G4MAGNET::magfield, G4MAGNET::magfield_rescale, Enable::MAGNET, Magnet(), Enable::MVTX, Mvtx(), Enable::PIPE, Pipe(), Enable::PLUGDOOR, PlugDoor(), G4BECAL::radius, Fun4AllServer::registerSubsystem(), PHG4Reco::registerSubsystem(), Enable::RICH, RICHSetup(), PHG4Reco::set_field(), PHG4Reco::set_field_map(), PHG4Reco::set_field_rescale(), PHG4Reco::set_force_decay(), PHG4Reco::set_rapidity_coverage(), Enable::TPC, Enable::USER, UserDetector(), WorldInit(), and WorldSize().
void ShowerCompress ()
Definition at line 208 of file G4Setup_ModularDetectorBeast.C.
View newest version in sPHENIX GitHub at line 208 of file G4Setup_ModularDetectorBeast.C
References PHG4DstCompressReco::AddCellContainer(), PHG4DstCompressReco::AddHitContainer(), PHG4DstCompressReco::AddTowerContainer(), compress(), Fun4AllServer::instance(), and Fun4AllServer::registerSubsystem().