EIC Software: G4JLeicDIRCDetector Class Reference
G4JLeicDIRCDetector Class Reference
#include <fun4all_eicdetectors/blob/master/simulation/g4simulation/g4jleic/G4JLeicDIRCDetector.h>
Public Member Functions
G4JLeicDIRCDetector (PHG4Subsystem *subsys, PHCompositeNode *Node, PHParameters *params_array, const std::string &dnam)
constructor
virtual ~G4JLeicDIRCDetector ()
destructor
virtual void ConstructMe (G4LogicalVolume *world)
construct
virtual void Print (const std::string &what="ALL") const
void SuperDetector (const std::string &name)
const std::string SuperDetector () const
G4JLeicDIRCDetector (PHG4Subsystem *subsys, PHCompositeNode *Node, PHParameters *params_array, const std::string &dnam)
constructor
virtual ~G4JLeicDIRCDetector ()
destructor
virtual void ConstructMe (G4LogicalVolume *world)
construct
virtual void Print (const std::string &what="ALL") const
void SuperDetector (const std::string &name)
const std::string SuperDetector () const
volume accessors
int IsInDIRC (G4VPhysicalVolume *) const
int IsInDIRC (G4VPhysicalVolume *) const
Public Member Functions inherited from PHG4Detector
PHG4Detector ()=delete
constructor
PHG4Detector (PHG4Subsystem *subsys, PHCompositeNode *Node, const std::string &nam)
virtual ~PHG4Detector (void)
destructor
virtual void Construct (G4LogicalVolume *world) final
construct method
virtual void PostConstruction ()
Optional PostConstruction call after all geometry is constructed.
virtual void Verbosity (const int v)
virtual int Verbosity () const
virtual G4UserSteppingAction * GetSteppingAction ()
virtual std::string GetName () const
virtual void OverlapCheck (const bool chk)
virtual bool OverlapCheck () const
virtual int DisplayVolume (G4VSolid *volume, G4LogicalVolume *logvol, G4RotationMatrix *rotm=nullptr)
virtual int DisplayVolume (G4LogicalVolume *checksolid, G4LogicalVolume *logvol, G4RotationMatrix *rotm=nullptr)
virtual PHCompositeNode * topNode ()
virtual PHG4Subsystem * GetMySubsystem ()
Protected Attributes
PHParameters * m_Params
std::set< G4VPhysicalVolume * > m_PhysicalVolumesSet
std::string m_SuperDetector
Additional Inherited Members
Static Public Member Functions inherited from PHG4Detector
static G4Material * GetDetectorMaterial (const std::string &name, const bool quit=true)
static G4Element * GetDetectorElement (const std::string &name, const bool quit=true)
Detailed Description
Definition at line 17 of file G4JLeicDIRCDetector.h.
View newest version in sPHENIX GitHub at line 17 of file G4JLeicDIRCDetector.h
Constructor & Destructor Documentation
G4JLeicDIRCDetector::G4JLeicDIRCDetector (PHG4Subsystem * subsys, PHCompositeNode * Node, PHParameters * params_array, const std::string & dnam)
constructor
Definition at line 25 of file G4JLeicDIRCDetector.cc.
View newest version in sPHENIX GitHub at line 25 of file G4JLeicDIRCDetector.cc
virtual G4JLeicDIRCDetector::~G4JLeicDIRCDetector () inline virtual
destructor
Definition at line 24 of file G4JLeicDIRCDetector.h.
View newest version in sPHENIX GitHub at line 24 of file G4JLeicDIRCDetector.h
G4JLeicDIRCDetector::G4JLeicDIRCDetector (PHG4Subsystem * subsys, PHCompositeNode * Node, PHParameters * params_array, const std::string & dnam)
constructor
virtual G4JLeicDIRCDetector::~G4JLeicDIRCDetector () inline virtual
destructor
Definition at line 24 of file G4JLeicDIRCDetector.h.
View newest version in sPHENIX GitHub at line 24 of file G4JLeicDIRCDetector.h
Member Function Documentation
void G4JLeicDIRCDetector::ConstructMe (G4LogicalVolume * world) virtual
construct
Implements PHG4Detector.
Definition at line 45 of file G4JLeicDIRCDetector.cc.
View newest version in sPHENIX GitHub at line 45 of file G4JLeicDIRCDetector.cc
References Acts::UnitConstants::cm, cos(), PHG4Detector::GetDetectorMaterial(), m_PhysicalVolumesSet, M_PI, PHG4Detector::OverlapCheck(), phi, etm::solid, nlohmann::to_string(), x, and y.
virtual void G4JLeicDIRCDetector::ConstructMe (G4LogicalVolume * world) virtual
construct
Implements PHG4Detector.
int G4JLeicDIRCDetector::IsInDIRC (G4VPhysicalVolume *) const
int G4JLeicDIRCDetector::IsInDIRC (G4VPhysicalVolume * volume) const
Definition at line 33 of file G4JLeicDIRCDetector.cc.
View newest version in sPHENIX GitHub at line 33 of file G4JLeicDIRCDetector.cc
References m_PhysicalVolumesSet.
Referenced by G4JLeicDIRCSteppingAction::UserSteppingAction().
void G4JLeicDIRCDetector::Print (const std::string & what = "ALL") const virtual
Reimplemented from PHG4Detector.
Definition at line 78 of file G4JLeicDIRCDetector.cc.
View newest version in sPHENIX GitHub at line 78 of file G4JLeicDIRCDetector.cc
Referenced by G4JLeicDIRCSubsystem::Print().
virtual void G4JLeicDIRCDetector::Print (const std::string & what = "ALL") const virtual
Reimplemented from PHG4Detector.
void G4JLeicDIRCDetector::SuperDetector (const std::string & name) inline
Definition at line 36 of file G4JLeicDIRCDetector.h.
View newest version in sPHENIX GitHub at line 36 of file G4JLeicDIRCDetector.h
References m_SuperDetector, and name.
Referenced by G4JLeicDIRCSubsystem::InitRunSubsystem(), and G4JLeicDIRCSteppingAction::SetInterfacePointers().
void G4JLeicDIRCDetector::SuperDetector (const std::string & name) inline
Definition at line 36 of file G4JLeicDIRCDetector.h.
View newest version in sPHENIX GitHub at line 36 of file G4JLeicDIRCDetector.h
References m_SuperDetector, and name.
const std::string G4JLeicDIRCDetector::SuperDetector () const inline
Definition at line 37 of file G4JLeicDIRCDetector.h.
View newest version in sPHENIX GitHub at line 37 of file G4JLeicDIRCDetector.h
References m_SuperDetector.
const std::string G4JLeicDIRCDetector::SuperDetector () const inline
Definition at line 37 of file G4JLeicDIRCDetector.h.
View newest version in sPHENIX GitHub at line 37 of file G4JLeicDIRCDetector.h
References m_SuperDetector.
Member Data Documentation
PHParameters * G4JLeicDIRCDetector::m_Params protected
Definition at line 40 of file G4JLeicDIRCDetector.h.
View newest version in sPHENIX GitHub at line 40 of file G4JLeicDIRCDetector.h
std::set< G4VPhysicalVolume * > G4JLeicDIRCDetector::m_PhysicalVolumesSet protected
Definition at line 41 of file G4JLeicDIRCDetector.h.
View newest version in sPHENIX GitHub at line 41 of file G4JLeicDIRCDetector.h
Referenced by ConstructMe(), and IsInDIRC().
std::string G4JLeicDIRCDetector::m_SuperDetector protected
Definition at line 43 of file G4JLeicDIRCDetector.h.
View newest version in sPHENIX GitHub at line 43 of file G4JLeicDIRCDetector.h
Referenced by SuperDetector().
The documentation for this class was generated from the following files:
fun4all_eicdetectors/blob/master/simulation/g4simulation/g4jleic/G4JLeicDIRCDetector.h
fun4all_g4jleic/blob/master/source/G4JLeicDIRCDetector.h
fun4all_eicdetectors/blob/master/simulation/g4simulation/g4jleic/G4JLeicDIRCDetector.cc
fun4all_g4jleic/blob/master/source/G4JLeicDIRCDetector.cc