EIC Software: incoherentPhotonNucleusLuminosity Class Reference
incoherentPhotonNucleusLuminosity Class Reference
#include <estarlight/blob/master/include/incoherentPhotonNucleusLuminosity.h>
Public Member Functions
incoherentPhotonNucleusLuminosity (const inputParameters &input, beamBeamSystem &bbsystem)
~incoherentPhotonNucleusLuminosity ()
Public Member Functions inherited from photonNucleusCrossSection
photonNucleusCrossSection (const inputParameters &input, const beamBeamSystem &bbsystem)
~photonNucleusCrossSection ()
double slopeParameter () const
returns slope of t-distribution [(GeV/c)^{-2}]
double getChannelMass () const
returns mass of the produced system [GeV/c^2]
double getBNORM () const
beamBeamSystem getbbs () const
returns beamBeamSystem
double vmPhotonCoupling () const
vectormeson-photon coupling constant f_v / 4 pi (cf. Eq. 10 in KN PRC 60 (1999) 014903)
double vmQ2Power (double Q2) const
double getDefaultC () const
double maxPhotonEnergy () const
returns max photon energy in lab frame [GeV] (for vectormesons only)
void crossSectionCalculation (const double bwnormsave)
double backwardsPropagationOmegaCrossSection (const double targetEgamma)
double getcsgA (const double Egamma, const double Q2, const int beam)
double e_getcsgA (const double Egamma, double Q2, const double W, const int beam)
double getcsgA_Q2_dep (const double Q2)
double photonFlux (const double Egamma, const int beam)
double photonFlux (const double Egamma, const double Q2)
double integrated_Q2_dep (const double Egamma, const double _min=0, const double _max=0)
double integrated_x_section (const double Egamma, const double _min=0, const double _max=0)
std::pair< double, double > * Q2arraylimits (double const Egamma)
double g (double const Egamma, double const Q2)
double sigmagp (const double Wgp)
double sigma_A (const double sig_N, const int beam)
double sigma_N (const double Wgp)
double breitWigner (const double W, const double C)
double nepoint (const double Egamma, const double bmin)
double getPhotonNucleusSigma () const
void setPhotonNucleusSigma (double sigma)
Private Member Functions
void incoherentPhotonNucleusDifferentialLuminosity ()
Private Attributes
const std::string _baseFileName
const double _beamLorentzGamma
const double _maxW
const double _minW
const unsigned int _nmbWBins
const double _maxRapidity
const unsigned int _nmbRapidityBins
const int _productionMode
const int _beamBreakupMode
const int _interferenceEnabled
const double _interferenceStrength
const double _maxPtInterference
const int _nmbPtBinsInterference
const double _protonEnergy
const std::string _parameterValueKey
Additional Inherited Members
Protected Attributes inherited from photonNucleusCrossSection
const unsigned int _nWbins
const unsigned int _nYbins
const double _wMin
const double _wMax
const double _yMax
const double _beamLorentzGamma
double _photonNucleusSigma
int _printDef
int _impulseSelected
int _quantumGlauber
Detailed Description
Definition at line 43 of file incoherentPhotonNucleusLuminosity.h.
View newest version in sPHENIX GitHub at line 43 of file incoherentPhotonNucleusLuminosity.h
Constructor & Destructor Documentation
incoherentPhotonNucleusLuminosity::incoherentPhotonNucleusLuminosity (const inputParameters & input, beamBeamSystem & bbsystem)
Definition at line 52 of file incoherentPhotonNucleusLuminosity.cpp.
View newest version in sPHENIX GitHub at line 52 of file incoherentPhotonNucleusLuminosity.cpp
References incoherentPhotonNucleusDifferentialLuminosity().
incoherentPhotonNucleusLuminosity::~incoherentPhotonNucleusLuminosity ()
Definition at line 77 of file incoherentPhotonNucleusLuminosity.cpp.
View newest version in sPHENIX GitHub at line 77 of file incoherentPhotonNucleusLuminosity.cpp
Member Function Documentation
void incoherentPhotonNucleusLuminosity::incoherentPhotonNucleusDifferentialLuminosity () private
Definition at line 82 of file incoherentPhotonNucleusLuminosity.cpp.
View newest version in sPHENIX GitHub at line 82 of file incoherentPhotonNucleusLuminosity.cpp
References _baseFileName, _beamBreakupMode, _beamLorentzGamma, _interferenceEnabled, _interferenceStrength, _maxPtInterference, _maxRapidity, _maxW, _minW, _nmbPtBinsInterference, _nmbRapidityBins, _nmbWBins, photonNucleusCrossSection::_nWbins, photonNucleusCrossSection::_nYbins, _parameterValueKey, _productionMode, _protonEnergy, photonNucleusCrossSection::_wMax, photonNucleusCrossSection::_wMin, photonNucleusCrossSection::_yMax, nucleus::A(), photonNucleusCrossSection::breitWigner(), Acts::UnitConstants::C, starlightConstants::deuteronSlopePar, Acts::Test::dY, beamBeamSystem::electronBeam(), photonNucleusCrossSection::getbbs(), photonNucleusCrossSection::getDefaultC(), photonNucleusCrossSection::maxPhotonEnergy(), photonNucleusCrossSection::photonFlux(), starlightConstants::protonMass, photonNucleusCrossSection::sigma_A(), photonNucleusCrossSection::sigma_N(), photonNucleusCrossSection::sigmagp(), beamBeamSystem::targetBeam(), and nucleus::Z().
Referenced by incoherentPhotonNucleusLuminosity().
Member Data Documentation
const std::string incoherentPhotonNucleusLuminosity::_baseFileName private
Definition at line 51 of file incoherentPhotonNucleusLuminosity.h.
View newest version in sPHENIX GitHub at line 51 of file incoherentPhotonNucleusLuminosity.h
Referenced by incoherentPhotonNucleusDifferentialLuminosity().
const int incoherentPhotonNucleusLuminosity::_beamBreakupMode private
Definition at line 59 of file incoherentPhotonNucleusLuminosity.h.
View newest version in sPHENIX GitHub at line 59 of file incoherentPhotonNucleusLuminosity.h
Referenced by incoherentPhotonNucleusDifferentialLuminosity().
const double incoherentPhotonNucleusLuminosity::_beamLorentzGamma private
Definition at line 52 of file incoherentPhotonNucleusLuminosity.h.
View newest version in sPHENIX GitHub at line 52 of file incoherentPhotonNucleusLuminosity.h
Referenced by incoherentPhotonNucleusDifferentialLuminosity().
const int incoherentPhotonNucleusLuminosity::_interferenceEnabled private
Definition at line 60 of file incoherentPhotonNucleusLuminosity.h.
View newest version in sPHENIX GitHub at line 60 of file incoherentPhotonNucleusLuminosity.h
Referenced by incoherentPhotonNucleusDifferentialLuminosity().
const double incoherentPhotonNucleusLuminosity::_interferenceStrength private
Definition at line 61 of file incoherentPhotonNucleusLuminosity.h.
View newest version in sPHENIX GitHub at line 61 of file incoherentPhotonNucleusLuminosity.h
Referenced by incoherentPhotonNucleusDifferentialLuminosity().
const double incoherentPhotonNucleusLuminosity::_maxPtInterference private
Definition at line 62 of file incoherentPhotonNucleusLuminosity.h.
View newest version in sPHENIX GitHub at line 62 of file incoherentPhotonNucleusLuminosity.h
Referenced by incoherentPhotonNucleusDifferentialLuminosity().
const double incoherentPhotonNucleusLuminosity::_maxRapidity private
Definition at line 56 of file incoherentPhotonNucleusLuminosity.h.
View newest version in sPHENIX GitHub at line 56 of file incoherentPhotonNucleusLuminosity.h
Referenced by incoherentPhotonNucleusDifferentialLuminosity().
const double incoherentPhotonNucleusLuminosity::_maxW private
Definition at line 53 of file incoherentPhotonNucleusLuminosity.h.
View newest version in sPHENIX GitHub at line 53 of file incoherentPhotonNucleusLuminosity.h
Referenced by incoherentPhotonNucleusDifferentialLuminosity().
const double incoherentPhotonNucleusLuminosity::_minW private
Definition at line 54 of file incoherentPhotonNucleusLuminosity.h.
View newest version in sPHENIX GitHub at line 54 of file incoherentPhotonNucleusLuminosity.h
Referenced by incoherentPhotonNucleusDifferentialLuminosity().
const int incoherentPhotonNucleusLuminosity::_nmbPtBinsInterference private
Definition at line 63 of file incoherentPhotonNucleusLuminosity.h.
View newest version in sPHENIX GitHub at line 63 of file incoherentPhotonNucleusLuminosity.h
Referenced by incoherentPhotonNucleusDifferentialLuminosity().
const unsigned int incoherentPhotonNucleusLuminosity::_nmbRapidityBins private
Definition at line 57 of file incoherentPhotonNucleusLuminosity.h.
View newest version in sPHENIX GitHub at line 57 of file incoherentPhotonNucleusLuminosity.h
Referenced by incoherentPhotonNucleusDifferentialLuminosity().
const unsigned int incoherentPhotonNucleusLuminosity::_nmbWBins private
Definition at line 55 of file incoherentPhotonNucleusLuminosity.h.
View newest version in sPHENIX GitHub at line 55 of file incoherentPhotonNucleusLuminosity.h
Referenced by incoherentPhotonNucleusDifferentialLuminosity().
const std::string incoherentPhotonNucleusLuminosity::_parameterValueKey private
Definition at line 65 of file incoherentPhotonNucleusLuminosity.h.
View newest version in sPHENIX GitHub at line 65 of file incoherentPhotonNucleusLuminosity.h
Referenced by incoherentPhotonNucleusDifferentialLuminosity().
const int incoherentPhotonNucleusLuminosity::_productionMode private
Definition at line 58 of file incoherentPhotonNucleusLuminosity.h.
View newest version in sPHENIX GitHub at line 58 of file incoherentPhotonNucleusLuminosity.h
Referenced by incoherentPhotonNucleusDifferentialLuminosity().
const double incoherentPhotonNucleusLuminosity::_protonEnergy private
Definition at line 64 of file incoherentPhotonNucleusLuminosity.h.
View newest version in sPHENIX GitHub at line 64 of file incoherentPhotonNucleusLuminosity.h
Referenced by incoherentPhotonNucleusDifferentialLuminosity().
The documentation for this class was generated from the following files:
estarlight/blob/master/include/incoherentPhotonNucleusLuminosity.h
estarlight/blob/master/src/incoherentPhotonNucleusLuminosity.cpp