EIC Software: HoughNodeGroup Class Reference
HoughNodeGroup Class Reference
#include <EicRoot/blob/master/eic/htree/HoughNodeGroup.h>
Public Member Functions
HoughNodeGroup (unsigned id)
void ConfigureCoordinateDescriptors (unsigned cdim, const double min[], const double max[], const double gra[])
virtual ~HoughNodeGroup ()
int AddMember (const std::pair< void *, void * > &ptr, t_hough_range from, t_hough_range to)
void ResetMemberCounter ()
unsigned GetMemberCount () const
GroupMember * GetMember (unsigned mm)
void SetPhaseSpaceSmearing (unsigned smearing)
unsigned GetPhaseSpaceSmearing () const
unsigned GetGroupId () const
unsigned GetCoord (t_hough_range value, EicMagneticField::XYZ id)
const std::vector
< CoordinateDescriptor > & GetCoordDescr ()
t_hough_range OffsetThisValue (t_hough_range value, int offset)
bool Overlap (std::pair< t_hough_range, t_hough_range > r1, std::pair< t_hough_range, t_hough_range > r2)
double GetMin (unsigned iq) const
double GetGra (unsigned iq) const
Protected Member Functions
t_hough_range HoughPack (const int coord[])
Protected Attributes
std::vector< CoordinateDescriptor > mCoordDescr
Private Attributes
unsigned mId
unsigned mPhaseSpaceSmearing
std::vector< GroupMember > mMembers
Detailed Description
Definition at line 167 of file HoughNodeGroup.h.
View newest version in sPHENIX GitHub at line 167 of file HoughNodeGroup.h
Constructor & Destructor Documentation
HoughNodeGroup::HoughNodeGroup (unsigned id) inline
Definition at line 169 of file HoughNodeGroup.h.
View newest version in sPHENIX GitHub at line 169 of file HoughNodeGroup.h
virtual HoughNodeGroup::~HoughNodeGroup () inline virtual
Definition at line 182 of file HoughNodeGroup.h.
View newest version in sPHENIX GitHub at line 182 of file HoughNodeGroup.h
Member Function Documentation
int HoughNodeGroup::AddMember (const std::pair< void *, void * > & ptr, t_hough_range from, t_hough_range to) inline
Definition at line 184 of file HoughNodeGroup.h.
View newest version in sPHENIX GitHub at line 184 of file HoughNodeGroup.h
References mMembers.
Referenced by FwdTrackFinder::Exec().
void HoughNodeGroup::ConfigureCoordinateDescriptors (unsigned cdim, const double min[], const double max[], const double gra[]) inline
Definition at line 171 of file HoughNodeGroup.h.
View newest version in sPHENIX GitHub at line 171 of file HoughNodeGroup.h
References mCoordDescr.
Referenced by HoughTree::AddNodeGroup().
unsigned HoughNodeGroup::GetCoord (t_hough_range value, EicMagneticField::XYZ id) inline
Definition at line 205 of file HoughNodeGroup.h.
View newest version in sPHENIX GitHub at line 205 of file HoughNodeGroup.h
References mCoordDescr.
const std::vector<CoordinateDescriptor>& HoughNodeGroup::GetCoordDescr () inline
Definition at line 211 of file HoughNodeGroup.h.
View newest version in sPHENIX GitHub at line 211 of file HoughNodeGroup.h
References mCoordDescr.
Referenced by HoughCell::UpdateRanges().
double HoughNodeGroup::GetGra (unsigned iq) const inline
Definition at line 261 of file HoughNodeGroup.h.
View newest version in sPHENIX GitHub at line 261 of file HoughNodeGroup.h
References mCoordDescr.
Referenced by FwdHoughNodeGroup::PackCore().
unsigned HoughNodeGroup::GetGroupId () const inline
Definition at line 202 of file HoughNodeGroup.h.
View newest version in sPHENIX GitHub at line 202 of file HoughNodeGroup.h
References mId.
Referenced by HoughTree::CheckCell().
GroupMember* HoughNodeGroup::GetMember (unsigned mm) inline
Definition at line 197 of file HoughNodeGroup.h.
View newest version in sPHENIX GitHub at line 197 of file HoughNodeGroup.h
References Acts::UnitConstants::mm, and mMembers.
Referenced by HoughTree::CheckCell(), and HoughTree::LaunchPatternFinder().
unsigned HoughNodeGroup::GetMemberCount () const inline
Definition at line 196 of file HoughNodeGroup.h.
View newest version in sPHENIX GitHub at line 196 of file HoughNodeGroup.h
References mMembers.
Referenced by HoughTree::CheckCell(), and HoughTree::LaunchPatternFinder().
double HoughNodeGroup::GetMin (unsigned iq) const inline
Definition at line 258 of file HoughNodeGroup.h.
View newest version in sPHENIX GitHub at line 258 of file HoughNodeGroup.h
References mCoordDescr.
Referenced by FwdHoughNodeGroup::PackCore().
unsigned HoughNodeGroup::GetPhaseSpaceSmearing () const inline
Definition at line 200 of file HoughNodeGroup.h.
View newest version in sPHENIX GitHub at line 200 of file HoughNodeGroup.h
References mPhaseSpaceSmearing.
Referenced by HoughTree::CheckCell().
t_hough_range HoughNodeGroup::HoughPack (const int coord[]) inline protected
Definition at line 270 of file HoughNodeGroup.h.
View newest version in sPHENIX GitHub at line 270 of file HoughNodeGroup.h
References mCoordDescr, and value.
Referenced by FwdHoughNodeGroup::PackCore().
t_hough_range HoughNodeGroup::OffsetThisValue (t_hough_range value, int offset) inline
Definition at line 215 of file HoughNodeGroup.h.
View newest version in sPHENIX GitHub at line 215 of file HoughNodeGroup.h
References mCoordDescr.
Referenced by HoughTree::CheckCell().
bool HoughNodeGroup::Overlap (std::pair< t_hough_range, t_hough_range > r1, std::pair< t_hough_range, t_hough_range > r2) inline
Definition at line 226 of file HoughNodeGroup.h.
View newest version in sPHENIX GitHub at line 226 of file HoughNodeGroup.h
References mCoordDescr, and CoordinateDescriptor::UnpackCoord().
Referenced by HoughTree::CheckCell().
void HoughNodeGroup::ResetMemberCounter () inline
Definition at line 195 of file HoughNodeGroup.h.
View newest version in sPHENIX GitHub at line 195 of file HoughNodeGroup.h
References mMembers.
Referenced by FwdTrackFinder::Exec().
void HoughNodeGroup::SetPhaseSpaceSmearing (unsigned smearing) inline
Definition at line 199 of file HoughNodeGroup.h.
View newest version in sPHENIX GitHub at line 199 of file HoughNodeGroup.h
References mPhaseSpaceSmearing.
Referenced by FwdHoughTree::AddNodeGroup().
Member Data Documentation
std::vector<CoordinateDescriptor> HoughNodeGroup::mCoordDescr protected
Definition at line 263 of file HoughNodeGroup.h.
View newest version in sPHENIX GitHub at line 263 of file HoughNodeGroup.h
Referenced by ConfigureCoordinateDescriptors(), GetCoord(), GetCoordDescr(), GetGra(), GetMin(), HoughPack(), OffsetThisValue(), and Overlap().
unsigned HoughNodeGroup::mId private
Definition at line 277 of file HoughNodeGroup.h.
View newest version in sPHENIX GitHub at line 277 of file HoughNodeGroup.h
Referenced by GetGroupId().
std::vector<GroupMember> HoughNodeGroup::mMembers private
Definition at line 291 of file HoughNodeGroup.h.
View newest version in sPHENIX GitHub at line 291 of file HoughNodeGroup.h
Referenced by AddMember(), GetMember(), GetMemberCount(), and ResetMemberCounter().
unsigned HoughNodeGroup::mPhaseSpaceSmearing private
Definition at line 284 of file HoughNodeGroup.h.
View newest version in sPHENIX GitHub at line 284 of file HoughNodeGroup.h
Referenced by GetPhaseSpaceSmearing(), and SetPhaseSpaceSmearing().
The documentation for this class was generated from the following file:
EicRoot/blob/master/eic/htree/HoughNodeGroup.h