EIC Software: PndMultiFieldPar Class Reference
PndMultiFieldPar Class Reference
#include <EicRoot/blob/master/field/PndMultiFieldPar.h>
Public Member Functions
PndMultiFieldPar (const char *name, const char *title, const char *context)
PndMultiFieldPar ()
~PndMultiFieldPar ()
void putParams (FairParamList *list)
Bool_t getParams (FairParamList *list)
void SetParameters (FairField *field)
TObjArray * GetParArray ()
Public Member Functions inherited from PndMapPar
PndMapPar (const char *name, const char *title, const char *context)
PndMapPar ()
~PndMapPar ()
void SetParameters (FairField *field)
Int_t GetType () const
Double_t GetXmin () const
Double_t GetXmax () const
Double_t GetYmin () const
Double_t GetYmax () const
Double_t GetZmin () const
Double_t GetZmax () const
void MapName (TString &name)
Double_t GetPositionX () const
Double_t GetPositionY () const
Double_t GetPositionZ () const
Double_t GetScale () const
Public Member Functions inherited from FairParGenericSet
FairParGenericSet (const char *name, const char *title, const char *context)
virtual ~FairParGenericSet ()
virtual void printParams ()
Bool_t init (FairParIo *inp)
Int_t write (FairParIo *output)
Public Member Functions inherited from FairParSet
FairParSet (const char *name="", const char *title="", const char *context="")
virtual ~FairParSet ()
virtual Bool_t init ()
virtual Int_t write ()
virtual void clear ()
virtual void print ()
const char * getDetectorName ()
void resetInputVersions ()
void setInputVersion (Int_t v=-1, Int_t i=0)
Int_t getInputVersion (Int_t i)
void setStatic (Bool_t flag=kTRUE)
Bool_t isStatic ()
void setChanged (Bool_t flag=kTRUE)
Bool_t hasChanged ()
const char * getParamContext () const
void setAuthor (const char *s)
const char * getAuthor () const
void setDescription (const char *s)
const char * getDescription () const
void copyComment (FairParSet &r)
Protected Member Functions
ClassDef (PndMultiFieldPar, 1)
Protected Member Functions inherited from PndMapPar
ClassDef (PndMapPar, 1)
Protected Member Functions inherited from FairParGenericSet
FairParGenericSet ()
Protected Attributes
TObjArray * fParArray
Protected Attributes inherited from PndMapPar
Int_t fType
Double_t fXmin
Double_t fXmax
Double_t fYmin
Double_t fYmax
Double_t fZmin
Double_t fZmax
TString fMapName
Double_t fPosX
Double_t fPosY
Double_t fPosZ
Double_t fScale
Private Member Functions
PndMultiFieldPar (const PndMultiFieldPar &L)
PndMultiFieldPar & operator= (const PndMultiFieldPar &)
Detailed Description
Definition at line 17 of file PndMultiFieldPar.h.
View newest version in sPHENIX GitHub at line 17 of file PndMultiFieldPar.h
Constructor & Destructor Documentation
PndMultiFieldPar::PndMultiFieldPar (const char * name, const char * title, const char * context)
Standard constructor
Definition at line 17 of file PndMultiFieldPar.cxx.
View newest version in sPHENIX GitHub at line 17 of file PndMultiFieldPar.cxx
References fParArray.
PndMultiFieldPar::PndMultiFieldPar ()
default constructor
Definition at line 24 of file PndMultiFieldPar.cxx.
View newest version in sPHENIX GitHub at line 24 of file PndMultiFieldPar.cxx
PndMultiFieldPar::~PndMultiFieldPar ()
Destructor
Definition at line 29 of file PndMultiFieldPar.cxx.
View newest version in sPHENIX GitHub at line 29 of file PndMultiFieldPar.cxx
PndMultiFieldPar::PndMultiFieldPar (const PndMultiFieldPar & L) inline private
Definition at line 45 of file PndMultiFieldPar.h.
View newest version in sPHENIX GitHub at line 45 of file PndMultiFieldPar.h
Member Function Documentation
PndMultiFieldPar::ClassDef (PndMultiFieldPar , 1) protected
Bool_t PndMultiFieldPar::getParams (FairParamList * list) virtual
Get parameters
Reimplemented from PndMapPar.
Definition at line 40 of file PndMultiFieldPar.cxx.
View newest version in sPHENIX GitHub at line 40 of file PndMultiFieldPar.cxx
References FairParamList::fill(), FairParamList::fillObject(), fParArray, and PndMapPar::fType.
TObjArray* PndMultiFieldPar::GetParArray () inline
Definition at line 43 of file PndMultiFieldPar.h.
View newest version in sPHENIX GitHub at line 43 of file PndMultiFieldPar.h
References fParArray.
Referenced by PndFieldCreator::createFairField(), and PndMultiField::PndMultiField().
PndMultiFieldPar& PndMultiFieldPar::operator= (const PndMultiFieldPar &) inline private
Definition at line 46 of file PndMultiFieldPar.h.
View newest version in sPHENIX GitHub at line 46 of file PndMultiFieldPar.h
void PndMultiFieldPar::putParams (FairParamList * list) virtual
Put parameters
Reimplemented from PndMapPar.
Definition at line 31 of file PndMultiFieldPar.cxx.
View newest version in sPHENIX GitHub at line 31 of file PndMultiFieldPar.cxx
References FairParamList::add(), FairParamList::addObject(), fParArray, and PndMapPar::fType.
void PndMultiFieldPar::SetParameters (FairField * field)
Set parameters from FairField
Definition at line 47 of file PndMultiFieldPar.cxx.
View newest version in sPHENIX GitHub at line 47 of file PndMultiFieldPar.cxx
References fd, PndSolenoidMap::fNumberOfRegions, PndDipoleMap::fNumberOfRegions, fParArray, Acts::UnitConstants::fs, PndMapPar::fType, FairRuntimeDb::getContainer(), PndMultiField::GetFieldList(), PndDipoleMap::GetRegionNo(), PndSolenoidMap::GetRegionNo(), FairRun::GetRunId(), FairRun::Instance(), FairRuntimeDb::instance(), FairParSet::setInputVersion(), PndConstPar::SetParameters(), and PndMapPar::SetParameters().
Referenced by PndMultiField::FillParContainer().
Member Data Documentation
TObjArray* PndMultiFieldPar::fParArray protected
Definition at line 46 of file PndMultiFieldPar.h.
View newest version in sPHENIX GitHub at line 46 of file PndMultiFieldPar.h
Referenced by getParams(), GetParArray(), PndMultiFieldPar(), putParams(), and SetParameters().
The documentation for this class was generated from the following files:
EicRoot/blob/master/field/PndMultiFieldPar.h
EicRoot/blob/master/field/PndMultiFieldPar.cxx