EIC Software: PHG4ForwardHcalSteppingAction Class Reference
PHG4ForwardHcalSteppingAction Class Reference
#include <fun4all_eicdetectors/blob/master/simulation/g4simulation/g4eiccalos/PHG4ForwardHcalSteppingAction.h>
Public Member Functions
PHG4ForwardHcalSteppingAction (PHG4ForwardHcalDetector *, const PHParameters *parameters)
constructor
virtual ~PHG4ForwardHcalSteppingAction ()
destructor
bool UserSteppingAction (const G4Step *, bool) override
stepping action
void SetInterfacePointers (PHCompositeNode *) override
reimplemented from base class
void SetHitNodeName (const std::string &nam)
void SetAbsorberNodeName (const std::string &nam)
void SetSupportNodeName (const std::string &nam)
Public Member Functions inherited from PHG4SteppingAction
PHG4SteppingAction (const std::string &name, const int i=0)
virtual ~PHG4SteppingAction ()
virtual void Verbosity (const int i)
virtual int Verbosity () const
virtual int Init ()
virtual double GetScintLightYield (const G4Step *step)
get scintillation photon count. It require a custom set SCINTILLATIONYIELD property to work
virtual double GetVisibleEnergyDeposition (const G4Step *step)
get amount of energy that can make scintillation light, in Unit of GeV.
virtual void StoreLocalCoordinate (PHG4Hit *hit, const G4Step *step, const bool do_prepoint, const bool do_postpoint)
Extract local coordinate of the hit and save to PHG4Hit.
virtual void Print (const std::string &) const
std::string GetName () const
void SetName (const std::string &name)
virtual void SetLightCorrection (const double inner_radius, const double inner_corr, const double outer_radius, const double outer_corr)
virtual double GetLightCorrection (const double r) const
virtual double GetLightCorrection (const double xpos, const double ypos) const
virtual bool ValidCorrection () const
virtual void SetHitNodeName (const std::string &, const std::string &)
Set the G4HIT node names from Subsystem rather than constructing your own.
Private Attributes
PHG4ForwardHcalDetector * m_Detector = nullptr
pointer to the detector
PHG4HitContainer * m_HitContainer = nullptr
pointer to hit container
PHG4HitContainer * m_AbsorberHitContainer = nullptr
PHG4HitContainer * m_SupportHitContainer = nullptr
PHG4HitContainer * m_SaveHitContainer = nullptr
PHG4Hit * m_Hit = nullptr
PHG4Shower * m_SaveShower = nullptr
int m_ActiveFlag = 0
int m_AbsorberTruthFlag = 0
int m_SupportTruthFlag = 0
int m_BlackHoleFlag = 0
std::string m_HitNodeName
std::string m_AbsorberNodeName
std::string m_SupportNodeName
Detailed Description
Definition at line 19 of file PHG4ForwardHcalSteppingAction.h.
View newest version in sPHENIX GitHub at line 19 of file PHG4ForwardHcalSteppingAction.h
Constructor & Destructor Documentation
PHG4ForwardHcalSteppingAction::PHG4ForwardHcalSteppingAction (PHG4ForwardHcalDetector * detector, const PHParameters * parameters)
constructor
Definition at line 41 of file PHG4ForwardHcalSteppingAction.cc.
View newest version in sPHENIX GitHub at line 41 of file PHG4ForwardHcalSteppingAction.cc
PHG4ForwardHcalSteppingAction::~PHG4ForwardHcalSteppingAction () virtual
destructor
Definition at line 51 of file PHG4ForwardHcalSteppingAction.cc.
View newest version in sPHENIX GitHub at line 51 of file PHG4ForwardHcalSteppingAction.cc
References m_Hit.
Member Function Documentation
void PHG4ForwardHcalSteppingAction::SetAbsorberNodeName (const std::string & nam) inline
Definition at line 36 of file PHG4ForwardHcalSteppingAction.h.
View newest version in sPHENIX GitHub at line 36 of file PHG4ForwardHcalSteppingAction.h
References m_AbsorberNodeName.
Referenced by PHG4ForwardHcalSubsystem::InitRunSubsystem().
void PHG4ForwardHcalSteppingAction::SetHitNodeName (const std::string & nam) inline
Definition at line 35 of file PHG4ForwardHcalSteppingAction.h.
View newest version in sPHENIX GitHub at line 35 of file PHG4ForwardHcalSteppingAction.h
References m_HitNodeName.
Referenced by PHG4ForwardHcalSubsystem::InitRunSubsystem().
void PHG4ForwardHcalSteppingAction::SetInterfacePointers (PHCompositeNode * topNode) override virtual
reimplemented from base class
Reimplemented from PHG4SteppingAction.
Definition at line 282 of file PHG4ForwardHcalSteppingAction.cc.
View newest version in sPHENIX GitHub at line 282 of file PHG4ForwardHcalSteppingAction.cc
References m_AbsorberHitContainer, m_AbsorberNodeName, m_HitContainer, m_HitNodeName, m_SupportHitContainer, m_SupportNodeName, and PHG4SteppingAction::Verbosity().
void PHG4ForwardHcalSteppingAction::SetSupportNodeName (const std::string & nam) inline
Definition at line 37 of file PHG4ForwardHcalSteppingAction.h.
View newest version in sPHENIX GitHub at line 37 of file PHG4ForwardHcalSteppingAction.h
References m_SupportNodeName.
Referenced by PHG4ForwardHcalSubsystem::InitRunSubsystem().
bool PHG4ForwardHcalSteppingAction::UserSteppingAction (const G4Step * aStep, bool) override virtual
stepping action
Implements PHG4SteppingAction.
Definition at line 61 of file PHG4ForwardHcalSteppingAction.cc.
View newest version in sPHENIX GitHub at line 61 of file PHG4ForwardHcalSteppingAction.cc
References PHG4Shower::add_g4hit_id(), PHG4HitContainer::AddHit(), Acts::UnitConstants::cm, PHG4Hit::get_edep(), PHG4Hit::get_eion(), PHG4Hit::get_hit_id(), PHG4ForwardHcalDetector::get_Layer(), PHG4Hit::get_light_yield(), PHG4HitContainer::GetID(), PHG4Detector::GetName(), PHG4SteppingAction::GetVisibleEnergyDeposition(), Acts::UnitConstants::GeV, PHG4ForwardHcalDetector::IsInForwardHcal(), m_AbsorberHitContainer, m_AbsorberTruthFlag, m_ActiveFlag, m_BlackHoleFlag, m_Detector, m_Hit, m_HitContainer, m_SaveHitContainer, m_SaveShower, m_SupportHitContainer, p, PHG4Hit::Reset(), PHG4Hit::set_edep(), PHG4Hit::set_eion(), PHG4Hit::set_index_j(), PHG4Hit::set_index_k(), PHG4Hit::set_light_yield(), PHG4Hit::set_shower_id(), PHG4Hit::set_t(), PHG4Hit::set_trkid(), PHG4Hit::set_x(), PHG4Hit::set_y(), PHG4Hit::set_z(), PHG4SteppingAction::Verbosity(), and Acts::Test::volume.
Member Data Documentation
PHG4HitContainer* PHG4ForwardHcalSteppingAction::m_AbsorberHitContainer = nullptr private
Definition at line 45 of file PHG4ForwardHcalSteppingAction.h.
View newest version in sPHENIX GitHub at line 45 of file PHG4ForwardHcalSteppingAction.h
Referenced by SetInterfacePointers(), and UserSteppingAction().
std::string PHG4ForwardHcalSteppingAction::m_AbsorberNodeName private
Definition at line 57 of file PHG4ForwardHcalSteppingAction.h.
View newest version in sPHENIX GitHub at line 57 of file PHG4ForwardHcalSteppingAction.h
Referenced by SetAbsorberNodeName(), and SetInterfacePointers().
int PHG4ForwardHcalSteppingAction::m_AbsorberTruthFlag = 0 private
Definition at line 52 of file PHG4ForwardHcalSteppingAction.h.
View newest version in sPHENIX GitHub at line 52 of file PHG4ForwardHcalSteppingAction.h
Referenced by UserSteppingAction().
int PHG4ForwardHcalSteppingAction::m_ActiveFlag = 0 private
Definition at line 51 of file PHG4ForwardHcalSteppingAction.h.
View newest version in sPHENIX GitHub at line 51 of file PHG4ForwardHcalSteppingAction.h
Referenced by UserSteppingAction().
int PHG4ForwardHcalSteppingAction::m_BlackHoleFlag = 0 private
Definition at line 54 of file PHG4ForwardHcalSteppingAction.h.
View newest version in sPHENIX GitHub at line 54 of file PHG4ForwardHcalSteppingAction.h
Referenced by UserSteppingAction().
PHG4ForwardHcalDetector* PHG4ForwardHcalSteppingAction::m_Detector = nullptr private
pointer to the detector
Definition at line 41 of file PHG4ForwardHcalSteppingAction.h.
View newest version in sPHENIX GitHub at line 41 of file PHG4ForwardHcalSteppingAction.h
Referenced by UserSteppingAction().
PHG4Hit* PHG4ForwardHcalSteppingAction::m_Hit = nullptr private
Definition at line 48 of file PHG4ForwardHcalSteppingAction.h.
View newest version in sPHENIX GitHub at line 48 of file PHG4ForwardHcalSteppingAction.h
Referenced by UserSteppingAction(), and ~PHG4ForwardHcalSteppingAction().
PHG4HitContainer* PHG4ForwardHcalSteppingAction::m_HitContainer = nullptr private
pointer to hit container
Definition at line 44 of file PHG4ForwardHcalSteppingAction.h.
View newest version in sPHENIX GitHub at line 44 of file PHG4ForwardHcalSteppingAction.h
Referenced by SetInterfacePointers(), and UserSteppingAction().
std::string PHG4ForwardHcalSteppingAction::m_HitNodeName private
Definition at line 56 of file PHG4ForwardHcalSteppingAction.h.
View newest version in sPHENIX GitHub at line 56 of file PHG4ForwardHcalSteppingAction.h
Referenced by SetHitNodeName(), and SetInterfacePointers().
PHG4HitContainer* PHG4ForwardHcalSteppingAction::m_SaveHitContainer = nullptr private
Definition at line 47 of file PHG4ForwardHcalSteppingAction.h.
View newest version in sPHENIX GitHub at line 47 of file PHG4ForwardHcalSteppingAction.h
Referenced by UserSteppingAction().
PHG4Shower* PHG4ForwardHcalSteppingAction::m_SaveShower = nullptr private
Definition at line 49 of file PHG4ForwardHcalSteppingAction.h.
View newest version in sPHENIX GitHub at line 49 of file PHG4ForwardHcalSteppingAction.h
Referenced by UserSteppingAction().
PHG4HitContainer* PHG4ForwardHcalSteppingAction::m_SupportHitContainer = nullptr private
Definition at line 46 of file PHG4ForwardHcalSteppingAction.h.
View newest version in sPHENIX GitHub at line 46 of file PHG4ForwardHcalSteppingAction.h
Referenced by SetInterfacePointers(), and UserSteppingAction().
std::string PHG4ForwardHcalSteppingAction::m_SupportNodeName private
Definition at line 58 of file PHG4ForwardHcalSteppingAction.h.
View newest version in sPHENIX GitHub at line 58 of file PHG4ForwardHcalSteppingAction.h
Referenced by SetInterfacePointers(), and SetSupportNodeName().
int PHG4ForwardHcalSteppingAction::m_SupportTruthFlag = 0 private
Definition at line 53 of file PHG4ForwardHcalSteppingAction.h.
View newest version in sPHENIX GitHub at line 53 of file PHG4ForwardHcalSteppingAction.h
The documentation for this class was generated from the following files:
fun4all_eicdetectors/blob/master/simulation/g4simulation/g4eiccalos/PHG4ForwardHcalSteppingAction.h
fun4all_eicdetectors/blob/master/simulation/g4simulation/g4eiccalos/PHG4ForwardHcalSteppingAction.cc