EIC Software: GFRecoHitFactory Class Reference
GFRecoHitFactory Class Reference
Genfit
Factory object to create RecoHits from digitized and clustered data.
#include <EicRoot/blob/master/genfit/GFRecoHitFactory.h>
Public Member Functions
GFRecoHitFactory ()
virtual ~GFRecoHitFactory ()
void addProducer (int detID, GFAbsRecoHitProducer *hitProd, void *ptr=0)
Register a producer module to the factory.
void clear ()
Clear all hit producers.
GFAbsRecoHit * createOne (int detID, int index)
Create a RecoHit.
std::vector< GFAbsRecoHit * > createMany (const GFTrackCand &cand)
Creat a collection of RecoHits.
Private Attributes
std::map< int, std::pair
< GFAbsRecoHitProducer *, void * > > fHitProdMap
Detailed Description
Factory object to create RecoHits from digitized and clustered data.
The GFRecoHitFactory is used to automatically fill Track objects with hit data. For each detector type that is used, one GFRecoHitProducer has to be registered in the factory. The factory can the use the index information from a GFTrackCand object to load the indexed hits into the Track.
See Also
GFAbsRecoHitProducer
GFTrackCand
Definition at line 51 of file GFRecoHitFactory.h.
View newest version in sPHENIX GitHub at line 51 of file GFRecoHitFactory.h
Constructor & Destructor Documentation
GFRecoHitFactory::GFRecoHitFactory ()
Definition at line 24 of file GFRecoHitFactory.cxx.
View newest version in sPHENIX GitHub at line 24 of file GFRecoHitFactory.cxx
GFRecoHitFactory::~GFRecoHitFactory () virtual
Definition at line 27 of file GFRecoHitFactory.cxx.
View newest version in sPHENIX GitHub at line 27 of file GFRecoHitFactory.cxx
References clear().
Member Function Documentation
void GFRecoHitFactory::addProducer (int detID, GFAbsRecoHitProducer * hitProd, void * ptr = 0)
Register a producer module to the factory.
For each type of hit a separate producer is needed. The type of hit is identified by the detector ID (detID). This index corresponds to the detector ID that is stored in the GFTrackCand object
Definition at line 31 of file GFRecoHitFactory.cxx.
View newest version in sPHENIX GitHub at line 31 of file GFRecoHitFactory.cxx
References fHitProdMap, GFException::setFatal(), and GFException::setNumbers().
Referenced by EicRecoKalmanTask::Init().
void GFRecoHitFactory::clear (void)
Clear all hit producers.
Definition at line 45 of file GFRecoHitFactory.cxx.
View newest version in sPHENIX GitHub at line 45 of file GFRecoHitFactory.cxx
References fHitProdMap, and it.
Referenced by ~GFRecoHitFactory().
std::vector< GFAbsRecoHit * > GFRecoHitFactory::createMany (const GFTrackCand & cand)
Creat a collection of RecoHits.
This is the standard way to prepare the hit collection for a Track. The resulting collection can contain hits from several detectors. The order of the hits is the same as in the GFTrackCand. It is assumed that this order is already along the track.
RecoHits have to implement a constructor which takes the cluster object from which the RecoHit is build as the only parameter. See GFAbsRecoHitProducer for details
Definition at line 70 of file GFRecoHitFactory.cxx.
View newest version in sPHENIX GitHub at line 70 of file GFRecoHitFactory.cxx
References createOne(), GFTrackCand::getHit(), and GFTrackCand::getNHits().
Referenced by PndRecoDafFit::Fit(), and PndRecoKalmanFit::Fit().
GFAbsRecoHit * GFRecoHitFactory::createOne (int detID, int index)
Create a RecoHit.
RecoHits have to implement a Constructor which takes the cluster object from which the RecoHit is build as the only parameter. See GFAbsRecoHitProducer for details
Definition at line 54 of file GFRecoHitFactory.cxx.
View newest version in sPHENIX GitHub at line 54 of file GFRecoHitFactory.cxx
References fHitProdMap, GFException::setFatal(), and GFException::setNumbers().
Referenced by createMany().
Member Data Documentation
std::map<int,std::pair<GFAbsRecoHitProducer*, void*> > GFRecoHitFactory::fHitProdMap private
Definition at line 53 of file GFRecoHitFactory.h.
View newest version in sPHENIX GitHub at line 53 of file GFRecoHitFactory.h
Referenced by addProducer(), clear(), and createOne().
The documentation for this class was generated from the following files:
EicRoot/blob/master/genfit/GFRecoHitFactory.h
EicRoot/blob/master/genfit/GFRecoHitFactory.cxx