EIC Software: FairGeoTorus Class Reference
FairGeoTorus Class Reference
#include <EicRoot/blob/master/geobase/FairGeoTorus.h>
Public Member Functions
FairGeoTorus ()
~FairGeoTorus ()
TArrayD * calcVoluParam (FairGeoVolume *)
void calcVoluPosition (FairGeoVolume *, const FairGeoTransform &, const FairGeoTransform &)
Int_t readPoints (std::fstream *pFile, FairGeoVolume *volu)
Bool_t writePoints (std::fstream *, FairGeoVolume *)
void printPoints (FairGeoVolume *volu)
Public Member Functions inherited from FairGeoBasicShape
FairGeoBasicShape ()
virtual ~FairGeoBasicShape ()
Int_t getNumPoints ()
Int_t getNumParam ()
TArrayD * getParam ()
FairGeoTransform * getCenterPosition ()
FairGeoTransform * getVoluPosition ()
virtual void calcVoluPosition (FairGeoVolume *, const FairGeoTransform &)
void printParam ()
Additional Inherited Members
Protected Member Functions inherited from FairGeoBasicShape
void posInMother (const FairGeoTransform &, const FairGeoTransform &)
ClassDef(FairGeoBasicShape,
0) private FairGeoBasicShape & operator= (const FairGeoBasicShape &)
Protected Attributes inherited from FairGeoBasicShape
Int_t nPoints
Int_t nParam
TArrayD * param
FairGeoTransform * center
FairGeoTransform * position
Detailed Description
Definition at line 9 of file FairGeoTorus.h.
View newest version in sPHENIX GitHub at line 9 of file FairGeoTorus.h
Constructor & Destructor Documentation
FairGeoTorus::FairGeoTorus ()
FairGeoTorus::~FairGeoTorus ()
Definition at line 36 of file FairGeoTorus.cxx.
View newest version in sPHENIX GitHub at line 36 of file FairGeoTorus.cxx
References FairGeoBasicShape::center, FairGeoBasicShape::param, and FairGeoBasicShape::position.
Member Function Documentation
TArrayD * FairGeoTorus::calcVoluParam (FairGeoVolume * volu) virtual
Reimplemented from FairGeoBasicShape.
Definition at line 73 of file FairGeoTorus.cxx.
View newest version in sPHENIX GitHub at line 73 of file FairGeoTorus.cxx
References FairGeoVolume::getPoint(), FairGeoBasicShape::param, and v.
void FairGeoTorus::calcVoluPosition (FairGeoVolume * volu, const FairGeoTransform & dTC, const FairGeoTransform & mTR) virtual
Reimplemented from FairGeoBasicShape.
Definition at line 117 of file FairGeoTorus.cxx.
View newest version in sPHENIX GitHub at line 117 of file FairGeoTorus.cxx
References FairGeoBasicShape::center, FairGeoBasicShape::posInMother(), FairGeoTransform::setTransVector(), and t.
void FairGeoTorus::printPoints (FairGeoVolume * volu) virtual
Reimplemented from FairGeoBasicShape.
Definition at line 106 of file FairGeoTorus.cxx.
View newest version in sPHENIX GitHub at line 106 of file FairGeoTorus.cxx
References FairGeoVolume::getPoint(), FairGeoBasicShape::nPoints, printf(), and v.
Int_t FairGeoTorus::readPoints (std::fstream * pFile, FairGeoVolume * volu) virtual
Reimplemented from FairGeoBasicShape.
Definition at line 53 of file FairGeoTorus.cxx.
View newest version in sPHENIX GitHub at line 53 of file FairGeoTorus.cxx
References FairGeoVolume::createPoints(), FairGeoVolume::getNumPoints(), FairGeoBasicShape::nPoints, FairGeoVolume::setPoint(), and x.
Bool_t FairGeoTorus::writePoints (std::fstream * pFile, FairGeoVolume * volu) virtual
Reimplemented from FairGeoBasicShape.
Definition at line 92 of file FairGeoTorus.cxx.
View newest version in sPHENIX GitHub at line 92 of file FairGeoTorus.cxx
References FairGeoVolume::getPoint(), FairGeoBasicShape::nPoints, and v.
The documentation for this class was generated from the following files:
EicRoot/blob/master/geobase/FairGeoTorus.h
EicRoot/blob/master/geobase/FairGeoTorus.cxx