EIC Software: bessel Namespace Reference
bessel Namespace Reference
Functions
double besI0 (double x)
double dbesk0 (double x)
double dbesk1 (double x)
double besI1 (double x)
Function Documentation
double bessel::besI0 (double x)
Definition at line 45 of file bessel.cpp.
View newest version in sPHENIX GitHub at line 45 of file bessel.cpp
References KF_timing::ax, k1, and y.
Referenced by dbesk0().
double bessel::besI1 (double x)
Definition at line 109 of file bessel.cpp.
View newest version in sPHENIX GitHub at line 109 of file bessel.cpp
References KF_timing::ax, k1, and y.
Referenced by dbesk1().
double bessel::dbesk0 (double x)
Definition at line 74 of file bessel.cpp.
View newest version in sPHENIX GitHub at line 74 of file bessel.cpp
References besI0(), x, and y.
Referenced by photonNucleusCrossSection::nepoint().
double bessel::dbesk1 (double x)
Definition at line 145 of file bessel.cpp.
View newest version in sPHENIX GitHub at line 145 of file bessel.cpp
References besI1(), x, and y.
Referenced by photonNucleusCrossSection::nepoint(), twoPhotonLuminosity::Nphoton(), beam::photonDensity(), photonNucleusCrossSection::photonFlux(), and beamBeamSystem::probabilityOfPhotonBreakup().