EIC Software: DecayFinderContainer_v1 Class Reference
DecayFinderContainer_v1 Class Reference
#include <fun4all_coresoftware/blob/master/generators/decayFinder/DecayFinderContainer_v1.h>
Public Member Functions
DecayFinderContainer_v1 ()
DecayFinderContainer_v1 (const DecayFinderContainer_v1 &decayfindermap)
DecayFinderContainer_v1 & operator= (const DecayFinderContainer_v1 &decayfindermap)
~DecayFinderContainer_v1 () override
void identify (std::ostream &os=std::cout) const override
void Reset () override
Clear Event.
int isValid () const override
isValid returns non zero if object contains vailid data
PHObject * CloneMe () const override
Virtual copy constructor.
bool empty () const override
size_t size () const override
size_t count (unsigned int key) const override
void clear () override
const Decay get (unsigned int key) const override
Decay get (unsigned int key) override
ConstIter begin () const override
ConstIter find (unsigned int key) const override
ConstIter end () const override
Iter begin () override
Iter find (unsigned int key) override
Iter end () override
Decay insert (const Decay decay) override
Map returnDecaysByPDGid (int PDGid) override
size_t erase (unsigned int key) override
Public Member Functions inherited from DecayFinderContainerBase
~DecayFinderContainerBase () override
void identify (std::ostream &os=std::cout) const override
void Reset () override
Clear Event.
int isValid () const override
isValid returns non zero if object contains vailid data
PHObject * CloneMe () const override
Virtual copy constructor.
Public Member Functions inherited from PHObject
PHObject ()
ctor
~PHObject () override
dtor
virtual PHObject * clone () const final
PHObject * Clone (const char *newname="") const final
void Copy (TObject &object) const final
virtual int isValid (const float) const
virtual int isValid (const double) const
virtual int isValid (const int) const
virtual int isValid (const unsigned int) const
virtual int isImplemented (const float f) const
virtual int isImplemented (const double f) const
virtual int isImplemented (const int i) const
virtual int isImplemented (const unsigned int i) const
virtual int Integrate () const
virtual int Integrate (PHObject *)
virtual void CopyFrom (const PHObject *obj)
Private Member Functions
ClassDefOverride (DecayFinderContainer_v1, 1)
Private Attributes
Map m_decaymap
Additional Inherited Members
Public Types inherited from DecayFinderContainerBase
typedef std::vector< std::pair
< int, int > > Decay
typedef std::map< unsigned int,
Decay > Map
typedef std::map< unsigned int,
Decay >::const_iterator ConstIter
typedef std::map< unsigned int,
Decay >::iterator Iter
Protected Member Functions inherited from DecayFinderContainerBase
DecayFinderContainerBase ()
Detailed Description
Definition at line 17 of file DecayFinderContainer_v1.h.
View newest version in sPHENIX GitHub at line 17 of file DecayFinderContainer_v1.h
Constructor & Destructor Documentation
DecayFinderContainer_v1::DecayFinderContainer_v1 ()
Definition at line 14 of file DecayFinderContainer_v1.cc.
View newest version in sPHENIX GitHub at line 14 of file DecayFinderContainer_v1.cc
DecayFinderContainer_v1::DecayFinderContainer_v1 (const DecayFinderContainer_v1 & decayfindermap)
Definition at line 19 of file DecayFinderContainer_v1.cc.
View newest version in sPHENIX GitHub at line 19 of file DecayFinderContainer_v1.cc
References begin(), end(), and m_decaymap.
DecayFinderContainer_v1::~DecayFinderContainer_v1 () override
Definition at line 40 of file DecayFinderContainer_v1.cc.
View newest version in sPHENIX GitHub at line 40 of file DecayFinderContainer_v1.cc
References Reset().
Member Function Documentation
ConstIter DecayFinderContainer_v1::begin () const inline override virtual
Reimplemented from DecayFinderContainerBase.
Definition at line 38 of file DecayFinderContainer_v1.h.
View newest version in sPHENIX GitHub at line 38 of file DecayFinderContainer_v1.h
References m_decaymap.
Referenced by DecayFinderContainer_v1(), operator=(), and DecayFinder::printNode().
Iter DecayFinderContainer_v1::begin () inline override virtual
Reimplemented from DecayFinderContainerBase.
Definition at line 42 of file DecayFinderContainer_v1.h.
View newest version in sPHENIX GitHub at line 42 of file DecayFinderContainer_v1.h
References m_decaymap.
DecayFinderContainer_v1::ClassDefOverride (DecayFinderContainer_v1 , 1) private
void DecayFinderContainer_v1::clear (void) inline override virtual
Reimplemented from DecayFinderContainerBase.
Definition at line 33 of file DecayFinderContainer_v1.h.
View newest version in sPHENIX GitHub at line 33 of file DecayFinderContainer_v1.h
References Reset().
PHObject* DecayFinderContainer_v1::CloneMe () const inline override virtual
Virtual copy constructor.
Reimplemented from PHObject.
Definition at line 28 of file DecayFinderContainer_v1.h.
View newest version in sPHENIX GitHub at line 28 of file DecayFinderContainer_v1.h
References DecayFinderContainerBase::DecayFinderContainerBase().
size_t DecayFinderContainer_v1::count (unsigned int key) const inline override virtual
Reimplemented from DecayFinderContainerBase.
Definition at line 32 of file DecayFinderContainer_v1.h.
View newest version in sPHENIX GitHub at line 32 of file DecayFinderContainer_v1.h
References m_decaymap.
bool DecayFinderContainer_v1::empty () const inline override virtual
Reimplemented from DecayFinderContainerBase.
Definition at line 30 of file DecayFinderContainer_v1.h.
View newest version in sPHENIX GitHub at line 30 of file DecayFinderContainer_v1.h
References m_decaymap.
ConstIter DecayFinderContainer_v1::end () const inline override virtual
Reimplemented from DecayFinderContainerBase.
Definition at line 40 of file DecayFinderContainer_v1.h.
View newest version in sPHENIX GitHub at line 40 of file DecayFinderContainer_v1.h
References m_decaymap.
Referenced by DecayFinderContainer_v1(), operator=(), and DecayFinder::printNode().
Iter DecayFinderContainer_v1::end () inline override virtual
Reimplemented from DecayFinderContainerBase.
Definition at line 44 of file DecayFinderContainer_v1.h.
View newest version in sPHENIX GitHub at line 44 of file DecayFinderContainer_v1.h
References m_decaymap.
size_t DecayFinderContainer_v1::erase (unsigned int key) override virtual
Reimplemented from DecayFinderContainerBase.
Definition at line 92 of file DecayFinderContainer_v1.cc.
View newest version in sPHENIX GitHub at line 92 of file DecayFinderContainer_v1.cc
References m_decaymap.
ConstIter DecayFinderContainer_v1::find (unsigned int key) const inline override virtual
Reimplemented from DecayFinderContainerBase.
Definition at line 39 of file DecayFinderContainer_v1.h.
View newest version in sPHENIX GitHub at line 39 of file DecayFinderContainer_v1.h
References m_decaymap.
Iter DecayFinderContainer_v1::find (unsigned int key) inline override virtual
Reimplemented from DecayFinderContainerBase.
Definition at line 43 of file DecayFinderContainer_v1.h.
View newest version in sPHENIX GitHub at line 43 of file DecayFinderContainer_v1.h
References m_decaymap.
const DecayFinderContainerBase::Decay DecayFinderContainer_v1::get (unsigned int key) const override virtual
Reimplemented from DecayFinderContainerBase.
Definition at line 56 of file DecayFinderContainer_v1.cc.
View newest version in sPHENIX GitHub at line 56 of file DecayFinderContainer_v1.cc
References m_decaymap.
DecayFinderContainerBase::Decay DecayFinderContainer_v1::get (unsigned int key) override virtual
Reimplemented from DecayFinderContainerBase.
Definition at line 64 of file DecayFinderContainer_v1.cc.
View newest version in sPHENIX GitHub at line 64 of file DecayFinderContainer_v1.cc
References m_decaymap.
void DecayFinderContainer_v1::identify (std::ostream & os = std::cout) const override virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from PHObject.
Definition at line 50 of file DecayFinderContainer_v1.cc.
View newest version in sPHENIX GitHub at line 50 of file DecayFinderContainer_v1.cc
References m_decaymap.
DecayFinderContainerBase::Decay DecayFinderContainer_v1::insert (const Decay decay) override virtual
Reimplemented from DecayFinderContainerBase.
Definition at line 72 of file DecayFinderContainer_v1.cc.
View newest version in sPHENIX GitHub at line 72 of file DecayFinderContainer_v1.cc
References m_decaymap.
Referenced by DecayFinder::fillDecayNode().
int DecayFinderContainer_v1::isValid () const inline override virtual
isValid returns non zero if object contains vailid data
Reimplemented from PHObject.
Definition at line 27 of file DecayFinderContainer_v1.h.
View newest version in sPHENIX GitHub at line 27 of file DecayFinderContainer_v1.h
DecayFinderContainer_v1 & DecayFinderContainer_v1::operator= (const DecayFinderContainer_v1 & decayfindermap)
Definition at line 29 of file DecayFinderContainer_v1.cc.
View newest version in sPHENIX GitHub at line 29 of file DecayFinderContainer_v1.cc
References begin(), end(), m_decaymap, and Reset().
void DecayFinderContainer_v1::Reset () override virtual
Clear Event.
Reimplemented from PHObject.
Definition at line 45 of file DecayFinderContainer_v1.cc.
View newest version in sPHENIX GitHub at line 45 of file DecayFinderContainer_v1.cc
References m_decaymap.
Referenced by clear(), operator=(), and ~DecayFinderContainer_v1().
DecayFinderContainerBase::Map DecayFinderContainer_v1::returnDecaysByPDGid (int PDGid) override virtual
Reimplemented from DecayFinderContainerBase.
Definition at line 80 of file DecayFinderContainer_v1.cc.
View newest version in sPHENIX GitHub at line 80 of file DecayFinderContainer_v1.cc
References m_decaymap.
size_t DecayFinderContainer_v1::size () const inline override virtual
Reimplemented from DecayFinderContainerBase.
Definition at line 31 of file DecayFinderContainer_v1.h.
View newest version in sPHENIX GitHub at line 31 of file DecayFinderContainer_v1.h
References m_decaymap.
Member Data Documentation
Map DecayFinderContainer_v1::m_decaymap private
Definition at line 54 of file DecayFinderContainer_v1.h.
View newest version in sPHENIX GitHub at line 54 of file DecayFinderContainer_v1.h
Referenced by begin(), count(), DecayFinderContainer_v1(), empty(), end(), erase(), find(), get(), identify(), insert(), operator=(), Reset(), returnDecaysByPDGid(), and size().
The documentation for this class was generated from the following files:
fun4all_coresoftware/blob/master/generators/decayFinder/DecayFinderContainer_v1.h
fun4all_coresoftware/blob/master/generators/decayFinder/DecayFinderContainer_v1.cc