EIC Software: BeamPipeElement Class Reference
BeamPipeElement Class Reference
#include <EicRoot/blob/master/eic/infrastructure/BeamPipeGeoParData.h>
Public Types
enum SwapSign { NoSwap, Swap }
Public Member Functions
BeamPipeElement ()
BeamPipeElement (TString &material, double thickness)
BeamPipeElement (BeamPipeElement *source, Bool_t ipElement=false, SwapSign swapped=NoSwap)
~BeamPipeElement ()
void AddSection (double offset, double outerDiameter)
Private Member Functions
void ResetVars ()
const BeamPipeSection * GetFirstSection () const
const BeamPipeSection * GetFirstOrientedSection () const
const BeamPipeSection * GetLastSection () const
const BeamPipeSection * GetLastOrientedSection () const
double GetLength () const
ClassDef (BeamPipeElement, 6)
Private Attributes
TString mMaterial
Double_t mThickness
SwapSign mSwapped
Bool_t mIpElement
std::vector< BeamPipeSection * > mSections
Double_t mAccuOffset
Friends
class BeamPipeGeoParData
Detailed Description
Definition at line 59 of file BeamPipeGeoParData.h.
View newest version in sPHENIX GitHub at line 59 of file BeamPipeGeoParData.h
Member Enumeration Documentation
enum BeamPipeElement::SwapSign
Enumerator:
NoSwap
Swap
Definition at line 64 of file BeamPipeGeoParData.h.
View newest version in sPHENIX GitHub at line 64 of file BeamPipeGeoParData.h
Constructor & Destructor Documentation
BeamPipeElement::BeamPipeElement () inline
Definition at line 66 of file BeamPipeGeoParData.h.
View newest version in sPHENIX GitHub at line 66 of file BeamPipeGeoParData.h
References ResetVars().
BeamPipeElement::BeamPipeElement (TString & material, double thickness) inline
Definition at line 67 of file BeamPipeGeoParData.h.
View newest version in sPHENIX GitHub at line 67 of file BeamPipeGeoParData.h
BeamPipeElement::BeamPipeElement (BeamPipeElement * source, Bool_t ipElement = false, SwapSign swapped = NoSwap) inline
Definition at line 69 of file BeamPipeGeoParData.h.
View newest version in sPHENIX GitHub at line 69 of file BeamPipeGeoParData.h
References mIpElement, and mSwapped.
BeamPipeElement::~BeamPipeElement () inline
Definition at line 74 of file BeamPipeGeoParData.h.
View newest version in sPHENIX GitHub at line 74 of file BeamPipeGeoParData.h
Member Function Documentation
void BeamPipeElement::AddSection (double offset, double outerDiameter) inline
Definition at line 76 of file BeamPipeGeoParData.h.
View newest version in sPHENIX GitHub at line 76 of file BeamPipeGeoParData.h
References mSections.
Referenced by beampipe().
BeamPipeElement::ClassDef (BeamPipeElement , 6) private
const BeamPipeSection* BeamPipeElement::GetFirstOrientedSection () const inline private
Definition at line 93 of file BeamPipeGeoParData.h.
View newest version in sPHENIX GitHub at line 93 of file BeamPipeGeoParData.h
References mSections, mSwapped, and Swap.
Referenced by BeamPipeGeoParData::CheckGeometry().
const BeamPipeSection* BeamPipeElement::GetFirstSection () const inline private
Definition at line 88 of file BeamPipeGeoParData.h.
View newest version in sPHENIX GitHub at line 88 of file BeamPipeGeoParData.h
References mSections.
Referenced by BeamPipeGeoParData::ConstructGeometry(), and GetLength().
const BeamPipeSection* BeamPipeElement::GetLastOrientedSection () const inline private
Definition at line 103 of file BeamPipeGeoParData.h.
View newest version in sPHENIX GitHub at line 103 of file BeamPipeGeoParData.h
References mSections, mSwapped, and Swap.
const BeamPipeSection* BeamPipeElement::GetLastSection () const inline private
Definition at line 98 of file BeamPipeGeoParData.h.
View newest version in sPHENIX GitHub at line 98 of file BeamPipeGeoParData.h
References mSections.
Referenced by BeamPipeGeoParData::ConstructGeometry(), and GetLength().
double BeamPipeElement::GetLength () const inline private
Definition at line 116 of file BeamPipeGeoParData.h.
View newest version in sPHENIX GitHub at line 116 of file BeamPipeGeoParData.h
References GetFirstSection(), and GetLastSection().
Referenced by BeamPipeGeoParData::CheckGeometry(), and BeamPipeGeoParData::ConstructGeometry().
void BeamPipeElement::ResetVars () inline private
Definition at line 81 of file BeamPipeGeoParData.h.
View newest version in sPHENIX GitHub at line 81 of file BeamPipeGeoParData.h
References mAccuOffset, mIpElement, mSwapped, mThickness, and NoSwap.
Referenced by BeamPipeElement().
Friends And Related Function Documentation
friend class BeamPipeGeoParData friend
Definition at line 61 of file BeamPipeGeoParData.h.
View newest version in sPHENIX GitHub at line 61 of file BeamPipeGeoParData.h
Member Data Documentation
Double_t BeamPipeElement::mAccuOffset private
Definition at line 133 of file BeamPipeGeoParData.h.
View newest version in sPHENIX GitHub at line 133 of file BeamPipeGeoParData.h
Referenced by BeamPipeGeoParData::CheckGeometry(), BeamPipeGeoParData::ConstructGeometry(), and ResetVars().
Bool_t BeamPipeElement::mIpElement private
Definition at line 127 of file BeamPipeGeoParData.h.
View newest version in sPHENIX GitHub at line 127 of file BeamPipeGeoParData.h
Referenced by BeamPipeElement(), BeamPipeGeoParData::CheckGeometry(), BeamPipeGeoParData::ConstructGeometry(), and ResetVars().
TString BeamPipeElement::mMaterial private
Definition at line 118 of file BeamPipeGeoParData.h.
View newest version in sPHENIX GitHub at line 118 of file BeamPipeGeoParData.h
Referenced by BeamPipeGeoParData::ConstructGeometry().
std::vector<BeamPipeSection*> BeamPipeElement::mSections private
Definition at line 130 of file BeamPipeGeoParData.h.
View newest version in sPHENIX GitHub at line 130 of file BeamPipeGeoParData.h
Referenced by AddSection(), BeamPipeGeoParData::CheckGeometry(), BeamPipeGeoParData::ConstructGeometry(), GetFirstOrientedSection(), GetFirstSection(), GetLastOrientedSection(), and GetLastSection().
SwapSign BeamPipeElement::mSwapped private
Definition at line 125 of file BeamPipeGeoParData.h.
View newest version in sPHENIX GitHub at line 125 of file BeamPipeGeoParData.h
Referenced by BeamPipeElement(), BeamPipeGeoParData::CheckGeometry(), BeamPipeGeoParData::ConstructGeometry(), GetFirstOrientedSection(), GetLastOrientedSection(), and ResetVars().
Double_t BeamPipeElement::mThickness private
Definition at line 121 of file BeamPipeGeoParData.h.
View newest version in sPHENIX GitHub at line 121 of file BeamPipeGeoParData.h
Referenced by BeamPipeGeoParData::CheckGeometry(), BeamPipeGeoParData::ConstructGeometry(), and ResetVars().
The documentation for this class was generated from the following file:
EicRoot/blob/master/eic/infrastructure/BeamPipeGeoParData.h