EIC Software: EicStlVertex Class Reference
EicStlVertex Class Reference
3D vertex defined in STL input file
#include <EicRoot/blob/master/eic/cad/EicStlVertex.h>
Public Member Functions
EicStlVertex (const double coord[3])
~EicStlVertex ()
const EicStlKey * key () const
double DistanceToOrigin (void) const
void SetMergedFlag (void)
void SetMergedVertex (EicStlVertex *vertex)
bool IsMerged (void) const
EicStlVertex * GetMergedVertex (void) const
void AddFacet (EicStlFacet *facet)
std::set< EicStlFacet * > & facets (void)
void IncrementDegenerateNeighbor1D (EicStlVertex *vertex)
const std::map< EicStlVertex
*, unsigned > & DegenerateNeighbors1D (void)
void AddDegenerateNeighbors3D (EicStlVertex *vertex)
const std::vector
< EicStlVertex * > & DegenerateNeighbors3D (void)
void Print () const
Private Attributes
EicStlKey * mKey
double mDistanceToOrigin
std::set< EicStlFacet * > mFacets
bool mMerged
EicStlVertex * mMergedVertex
std::map< EicStlVertex
*, unsigned > mDegenerateNeighbors1D
std::vector< EicStlVertex * > mDegenerateNeighbors3D
Detailed Description
3D vertex defined in STL input file
Definition at line 23 of file EicStlVertex.h.
View newest version in sPHENIX GitHub at line 23 of file EicStlVertex.h
Constructor & Destructor Documentation
EicStlVertex::EicStlVertex (const double coord[3]) inline
Main constructor
Parameters
coord vertex 3D coordinates
Definition at line 28 of file EicStlVertex.h.
View newest version in sPHENIX GitHub at line 28 of file EicStlVertex.h
References mDistanceToOrigin, and mKey.
EicStlVertex::~EicStlVertex () inline
Destructor; just need to clean up the key;
Definition at line 35 of file EicStlVertex.h.
View newest version in sPHENIX GitHub at line 35 of file EicStlVertex.h
References mKey.
Member Function Documentation
void EicStlVertex::AddDegenerateNeighbors3D (EicStlVertex * vertex) inline
Definition at line 55 of file EicStlVertex.h.
View newest version in sPHENIX GitHub at line 55 of file EicStlVertex.h
References mDegenerateNeighbors3D.
Referenced by EicStlMediaGroup::MergeDegenerateVertices().
void EicStlVertex::AddFacet (EicStlFacet * facet) inline
Definition at line 45 of file EicStlVertex.h.
View newest version in sPHENIX GitHub at line 45 of file EicStlVertex.h
References mFacets.
const std::map<EicStlVertex*, unsigned>& EicStlVertex::DegenerateNeighbors1D (void) inline
Definition at line 52 of file EicStlVertex.h.
View newest version in sPHENIX GitHub at line 52 of file EicStlVertex.h
References mDegenerateNeighbors1D.
Referenced by EicStlMediaGroup::MergeDegenerateVertices().
const std::vector<EicStlVertex*>& EicStlVertex::DegenerateNeighbors3D (void) inline
Definition at line 58 of file EicStlVertex.h.
View newest version in sPHENIX GitHub at line 58 of file EicStlVertex.h
References mDegenerateNeighbors3D.
Referenced by EicStlMediaGroup::AddVertexToCurrentGroup(), and EicStlMediaGroup::MergeDegenerateVertices().
double EicStlVertex::DistanceToOrigin (void) const inline
Definition at line 39 of file EicStlVertex.h.
View newest version in sPHENIX GitHub at line 39 of file EicStlVertex.h
References mDistanceToOrigin.
Referenced by EicStlMediaGroup::SplitIntoAssemblies().
std::set<EicStlFacet*>& EicStlVertex::facets (void) inline
Definition at line 46 of file EicStlVertex.h.
View newest version in sPHENIX GitHub at line 46 of file EicStlVertex.h
References mFacets.
Referenced by EicStlMediaGroup::SplitIntoAssemblies().
EicStlVertex* EicStlVertex::GetMergedVertex (void) const inline
Definition at line 43 of file EicStlVertex.h.
View newest version in sPHENIX GitHub at line 43 of file EicStlVertex.h
References mMergedVertex.
Referenced by EicStlFacet::Calculate(), and EicStlMediaGroup::CalculateFacets().
void EicStlVertex::IncrementDegenerateNeighbor1D (EicStlVertex * vertex) inline
Definition at line 49 of file EicStlVertex.h.
View newest version in sPHENIX GitHub at line 49 of file EicStlVertex.h
References mDegenerateNeighbors1D.
Referenced by EicStlMediaGroup::MergeDegenerateVertices().
bool EicStlVertex::IsMerged (void) const inline
Definition at line 42 of file EicStlVertex.h.
View newest version in sPHENIX GitHub at line 42 of file EicStlVertex.h
References mMerged.
Referenced by EicStlMediaGroup::AddVertexToCurrentGroup(), EicStlMediaGroup::CalculateFacets(), and EicStlMediaGroup::MergeDegenerateVertices().
const EicStlKey* EicStlVertex::key () const inline
Definition at line 38 of file EicStlVertex.h.
View newest version in sPHENIX GitHub at line 38 of file EicStlVertex.h
References mKey.
Referenced by EicStlFactory::_ConstructGeometry(), EicStlMediaGroup::AddVertex(), EicStlFacet::Calculate(), EicStlFacetEdge::EicStlFacetEdge(), EicCompositeShape::LocalFillBuffer3D(), EicStlMediaGroup::MergeDegenerateVertices(), EicStlFactory::PreAllocateFacet(), and EicStlMediaGroup::SplitIntoAssemblies().
void EicStlVertex::Print () const inline
Printout method; do not mind to use fixed format
Definition at line 82 of file EicStlVertex.h.
View newest version in sPHENIX GitHub at line 82 of file EicStlVertex.h
References EicStlKey::GetData(), mKey, and printf().
Referenced by EicStlMediaGroup::AllocateEdges().
void EicStlVertex::SetMergedFlag (void) inline
Definition at line 40 of file EicStlVertex.h.
View newest version in sPHENIX GitHub at line 40 of file EicStlVertex.h
References mMerged.
Referenced by EicStlMediaGroup::AddVertexToCurrentGroup().
void EicStlVertex::SetMergedVertex (EicStlVertex * vertex) inline
Definition at line 41 of file EicStlVertex.h.
View newest version in sPHENIX GitHub at line 41 of file EicStlVertex.h
References mMergedVertex.
Referenced by EicStlMediaGroup::MergeDegenerateVertices().
Member Data Documentation
std::map<EicStlVertex*, unsigned> EicStlVertex::mDegenerateNeighbors1D private
Definition at line 76 of file EicStlVertex.h.
View newest version in sPHENIX GitHub at line 76 of file EicStlVertex.h
Referenced by DegenerateNeighbors1D(), and IncrementDegenerateNeighbor1D().
std::vector<EicStlVertex*> EicStlVertex::mDegenerateNeighbors3D private
Definition at line 77 of file EicStlVertex.h.
View newest version in sPHENIX GitHub at line 77 of file EicStlVertex.h
Referenced by AddDegenerateNeighbors3D(), and DegenerateNeighbors3D().
double EicStlVertex::mDistanceToOrigin private
Definition at line 67 of file EicStlVertex.h.
View newest version in sPHENIX GitHub at line 67 of file EicStlVertex.h
Referenced by DistanceToOrigin(), and EicStlVertex().
std::set<EicStlFacet*> EicStlVertex::mFacets private
Definition at line 70 of file EicStlVertex.h.
View newest version in sPHENIX GitHub at line 70 of file EicStlVertex.h
Referenced by AddFacet(), and facets().
EicStlKey* EicStlVertex::mKey private
Vertex unique 3*8-byte STL key
Definition at line 60 of file EicStlVertex.h.
View newest version in sPHENIX GitHub at line 60 of file EicStlVertex.h
Referenced by EicStlVertex(), key(), Print(), and ~EicStlVertex().
bool EicStlVertex::mMerged private
Definition at line 74 of file EicStlVertex.h.
View newest version in sPHENIX GitHub at line 74 of file EicStlVertex.h
Referenced by IsMerged(), and SetMergedFlag().
EicStlVertex* EicStlVertex::mMergedVertex private
Definition at line 75 of file EicStlVertex.h.
View newest version in sPHENIX GitHub at line 75 of file EicStlVertex.h
Referenced by GetMergedVertex(), and SetMergedVertex().
The documentation for this class was generated from the following file:
EicRoot/blob/master/eic/cad/EicStlVertex.h