EIC Software: g4lblvtx/blob/master/macros/auxiliary_studies/simplified_geometry/Fun4All_G4_simplified_v2_DIRC_barrel_GEM.C File Reference
Fun4All_G4_simplified_v2_DIRC_barrel_GEM.C File Reference
#include <phgenfit/Track.h>
#include <fun4all/Fun4AllDstInputManager.h>
#include <fun4all/Fun4AllDstOutputManager.h>
#include <fun4all/Fun4AllDummyInputManager.h>
#include <fun4all/Fun4AllInputManager.h>
#include <fun4all/Fun4AllNoSyncDstInputManager.h>
#include <fun4all/Fun4AllOutputManager.h>
#include <fun4all/Fun4AllServer.h>
#include <fun4all/SubsysReco.h>
#include <g4detectors/PHG4DetectorSubsystem.h>
#include <g4detectors/PHG4CylinderSubsystem.h>
#include <g4histos/G4HitNtuple.h>
#include <g4main/PHG4ParticleGenerator.h>
#include <g4main/PHG4ParticleGeneratorBase.h>
#include <g4main/PHG4Reco.h>
#include <g4main/PHG4TruthSubsystem.h>
#include <g4trackfastsim/PHG4TrackFastSim.h>
#include <g4trackfastsim/PHG4TrackFastSimEval.h>
#include <phool/recoConsts.h>
#include <g4lblvtx/PHG4ParticleGenerator_flat_pT.h>
#include <g4lblvtx/AllSi_Al_support_Subsystem.h>
#include "G4_BlackHole.C"
#include "G4_DIRC_SMALL.C"
Functions
void Fun4All_G4_simplified_v2_DIRC_barrel_GEM (int nEvents=-1, double vtx_matBud=0.05, double barr_matBud=0.55, double disk_matBud=0.25, double pmin=0., double pmax=30., int magnetic_field=4, TString out_name="out_vtx_study")
Function Documentation
void Fun4All_G4_simplified_v2_DIRC_barrel_GEM (int nEvents = -1, double vtx_matBud = 0.05, double barr_matBud = 0.55, double disk_matBud = 0.25, double pmin = 0., double pmax = 30., int magnetic_field = 4, TString out_name = "out_vtx_study")
Definition at line 39 of file Fun4All_G4_simplified_v2_DIRC_barrel_GEM.C.
View newest version in sPHENIX GitHub at line 39 of file Fun4All_G4_simplified_v2_DIRC_barrel_GEM.C
References kdfinder::abs(), PHG4TrackFastSim::add_phg4hits(), G4PIPE::be_pipe_length, G4PIPE::be_pipe_length_neg, G4PIPE::be_pipe_length_plus, G4PIPE::be_pipe_radius, G4PIPE::be_pipe_thickness, PHG4TrackFastSim::Cylinder, DIRCInit(), DIRCSetup(), Acts::UnitConstants::e, PHG4TrackFastSim::enable_vertexing(), Fun4AllServer::End(), exit(), in, Fun4AllServer::instance(), PHFieldConfig::kField2D, PHFieldConfig::kFieldBeast, Fun4AllServer::registerInputManager(), Fun4AllServer::registerOutputManager(), Fun4AllServer::registerSubsystem(), PHG4Reco::registerSubsystem(), Fun4AllServer::run(), PHG4CylinderSubsystem::set_color(), PHG4DetectorSubsystem::set_double_param(), PHG4ParticleGenerator::set_eta_range(), PHG4ParticleGenerator_flat_pT::set_eta_range(), PHG4Reco::set_field(), PHG4Reco::set_field_map(), PHG4Reco::set_field_rescale(), PHG4TrackFastSimEval::set_filename(), PHG4DetectorSubsystem::set_int_param(), PHG4ParticleGenerator::set_mom_range(), PHG4ParticleGeneratorBase::set_name(), PHG4ParticleGenerator_flat_pT::set_phi_range(), PHG4ParticleGenerator::set_phi_range(), PHG4ParticleGenerator_flat_pT::set_pT_range(), PHG4DetectorSubsystem::set_string_param(), PHG4TrackFastSim::set_sub_top_node_name(), PHG4TrackFastSim::set_trackmap_out_name(), PHG4TrackFastSim::set_use_vertex_in_fitting(), PHG4TrackFastSim::set_vertex_min_ndf(), PHG4TrackFastSim::set_vertex_xy_resolution(), PHG4TrackFastSim::set_vertex_z_resolution(), PHG4ParticleGeneratorBase::set_vtx(), PHG4ParticleGenerator::set_z_range(), PHG4ParticleGenerator_flat_pT::set_z_range(), PHG4DetectorSubsystem::SetActive(), PHG4DetectorSubsystem::SuperDetector(), Fun4AllBase::Verbosity(), PHG4TrackFastSim::Vertical_Plane, and wrap_with_cylindrical_blackhole().