EIC Software: fun4all_eicmacros/blob/master/common/G4_DSTReader_LBLDetector.C File Reference
G4_DSTReader_LBLDetector.C File Reference
#include <GlobalVariables.C>
#include <G4_AllSilicon.C>
#include <G4_CEmc_EIC.C>
#include <G4_EEMC.C>
#include <G4_FEMC_EIC.C>
#include <G4_FHCAL.C>
#include <G4_HcalIn_ref.C>
#include <G4_HcalOut_ref.C>
#include <G4_Magnet.C>
#include <g4eval/PHG4DSTReader.h>
#include <fun4all/Fun4AllServer.h>
Namespaces
namespace Enable
namespace G4DSTREADER
Macros
#define MACRO_G4DSTREADERLBLDETECTOR_C
Functions
void G4DSTreader_LBLDetectorInit ()
void G4DSTreader_LBLDetector (const string &outputFile="G4sPHENIXCells.root")
Macro Definition Documentation
#define MACRO_G4DSTREADERLBLDETECTOR_C
Definition at line 2 of file G4_DSTReader_LBLDetector.C.
View newest version in sPHENIX GitHub at line 2 of file G4_DSTReader_LBLDetector.C
Function Documentation
void G4DSTreader_LBLDetector (const string & outputFile = "G4sPHENIXCells.root")
debug output on screen?
Definition at line 43 of file G4_DSTReader_LBLDetector.C.
View newest version in sPHENIX GitHub at line 43 of file G4_DSTReader_LBLDetector.C
References Enable::ABSORBER, PHG4DSTReader::AddNode(), PHG4DSTReader::AddTower(), Enable::ALLSILICON, Enable::ALLSILICON_ABSORBER, Enable::BLACKHOLE, Enable::CEMC, Enable::CEMC_ABSORBER, Enable::CEMC_TOWER, Enable::DSTREADER_VERBOSITY, Enable::EEMC, Enable::FEMC, Enable::FEMC_ABSORBER, Enable::FEMC_TOWER, Enable::FHCAL, Enable::FHCAL_ABSORBER, Enable::FHCAL_TOWER, Enable::HCALIN, Enable::HCALIN_ABSORBER, Enable::HCALIN_TOWER, Enable::HCALOUT, Enable::HCALOUT_ABSORBER, Enable::HCALOUT_TOWER, Fun4AllServer::instance(), Enable::MAGNET, Enable::MAGNET_ABSORBER, max, Fun4AllServer::registerSubsystem(), G4DSTREADER::save_g4_raw, PHG4DSTReader::set_load_active_particle(), PHG4DSTReader::set_load_all_particle(), PHG4DSTReader::set_save_particle(), PHG4DSTReader::set_save_vertex(), PHG4DSTReader::set_tower_zero_sup(), G4DSTREADER::tower_zero_supp, Enable::VERBOSITY, and Fun4AllBase::Verbosity().
Referenced by Fun4All_G4_LBLDetector().
void G4DSTreader_LBLDetectorInit ()
Definition at line 42 of file G4_DSTReader_LBLDetector.C.
View newest version in sPHENIX GitHub at line 42 of file G4_DSTReader_LBLDetector.C