EIC Software: CbmPixelHit Class Reference
CbmPixelHit Class Reference
#include <EicRoot/blob/master/cbmdata/CbmPixelHit.h>
Public Member Functions
CbmPixelHit ()
Default constructor.
CbmPixelHit (Int_t address, Double_t x, Double_t y, Double_t z, Double_t dx, Double_t dy, Double_t dz, Double_t dxy, Int_t refId)
Standard constructor.
CbmPixelHit (Int_t address, const TVector3 &pos, const TVector3 &err, Double_t dxy, Int_t refId)
virtual ~CbmPixelHit ()
virtual string ToString () const
Inherited from CbmBaseHit.
Double_t GetX () const
Double_t GetY () const
Double_t GetDx () const
Double_t GetDy () const
Double_t GetDxy () const
void Position (TVector3 &pos) const
Copies hit position to pos.
void PositionError (TVector3 &dpos) const
Copies hit position error to pos.
void SetX (Double_t x)
void SetY (Double_t y)
void SetDx (Double_t dx)
void SetDy (Double_t dy)
void SetDxy (Double_t dxy)
void SetPosition (const TVector3 &pos)
Sets position of the hit.
void SetPositionError (const TVector3 &dpos)
Public Member Functions inherited from CbmBaseHit
CbmBaseHit ()
Default constructor.
virtual ~CbmBaseHit ()
Destructor.
HitType GetType () const
Double_t GetZ () const
Double_t GetDz () const
Int_t GetRefId () const
Int_t GetAddress () const
FairMultiLinkedData * GetLinks () const
void SetZ (Double_t z)
void SetDz (Double_t dz)
void SetRefId (Int_t refId)
void SetAddress (Int_t address)
void SetLinks (FairMultiLinkedData *links)
virtual Int_t GetPlaneId () const =0
Private Member Functions
ClassDef (CbmPixelHit, 1)
Private Attributes
Double_t fX
Double_t fY
X, Y positions of hit [cm].
Double_t fDx
Double_t fDy
X, Y errors [cm].
Double_t fDxy
XY correlation.
Additional Inherited Members
Protected Member Functions inherited from CbmBaseHit
void SetType (HitType type)
Sets hit type.
CbmBaseHit (const CbmBaseHit &)
CbmBaseHit & operator= (const CbmBaseHit &)
Detailed Description
Definition at line 17 of file CbmPixelHit.h.
View newest version in sPHENIX GitHub at line 17 of file CbmPixelHit.h
Constructor & Destructor Documentation
CbmPixelHit::CbmPixelHit ()
Default constructor.
Definition at line 12 of file CbmPixelHit.cxx.
View newest version in sPHENIX GitHub at line 12 of file CbmPixelHit.cxx
References kPIXELHIT, and CbmBaseHit::SetType().
CbmPixelHit::CbmPixelHit (Int_t address, Double_t x, Double_t y, Double_t z, Double_t dx, Double_t dy, Double_t dz, Double_t dxy, Int_t refId)
Standard constructor.
Parameters
address Detector unique identifier.
x X position of the hit [cm].
y Y position of the hit [cm].
z Z position of the hit [cm].
dx X position error of the hit [cm].
dy Y position error of the hit [cm].
dz Z position error of the hit [cm].
dxy XY correlation of the hit.
refId Some reference ID.
Definition at line 23 of file CbmPixelHit.cxx.
View newest version in sPHENIX GitHub at line 23 of file CbmPixelHit.cxx
References kPIXELHIT, CbmBaseHit::SetAddress(), CbmBaseHit::SetDz(), CbmBaseHit::SetRefId(), CbmBaseHit::SetType(), and CbmBaseHit::SetZ().
CbmPixelHit::CbmPixelHit (Int_t address, const TVector3 & pos, const TVector3 & err, Double_t dxy, Int_t refId)
Standard constructor.
Parameters
address Detector unique identifier.
pos Position of the hit as TVector3 [cm].
err Position errors of the hit as TVector3 [cm].
dxy XY correlation of the hit.
refId Some reference ID.
Definition at line 47 of file CbmPixelHit.cxx.
View newest version in sPHENIX GitHub at line 47 of file CbmPixelHit.cxx
References kPIXELHIT, CbmBaseHit::SetAddress(), CbmBaseHit::SetDz(), CbmBaseHit::SetRefId(), CbmBaseHit::SetType(), and CbmBaseHit::SetZ().
CbmPixelHit::~CbmPixelHit () virtual
brief Destructor.
Definition at line 67 of file CbmPixelHit.cxx.
View newest version in sPHENIX GitHub at line 67 of file CbmPixelHit.cxx
Member Function Documentation
CbmPixelHit::ClassDef (CbmPixelHit , 1) private
Double_t CbmPixelHit::GetDx () const inline
Definition at line 76 of file CbmPixelHit.h.
View newest version in sPHENIX GitHub at line 76 of file CbmPixelHit.h
References fDx.
Referenced by PositionError(), CbmRichHit::ToString(), and ToString().
Double_t CbmPixelHit::GetDxy () const inline
Definition at line 78 of file CbmPixelHit.h.
View newest version in sPHENIX GitHub at line 78 of file CbmPixelHit.h
References fDxy.
Referenced by CbmRichHit::ToString(), and ToString().
Double_t CbmPixelHit::GetDy () const inline
Definition at line 77 of file CbmPixelHit.h.
View newest version in sPHENIX GitHub at line 77 of file CbmPixelHit.h
References fDy.
Referenced by PositionError(), CbmRichHit::ToString(), and ToString().
Double_t CbmPixelHit::GetX () const inline
Definition at line 74 of file CbmPixelHit.h.
View newest version in sPHENIX GitHub at line 74 of file CbmPixelHit.h
References fX.
Referenced by CbmRichConverter::CopyHitsToRingLight(), CbmRichEventDisplay::DrawOnePmtPlane(), CbmRichGeoTest::HitsAndPoints(), CbmRichUrqmdTest::NofHits(), Position(), CbmRichHit::ToString(), and ToString().
Double_t CbmPixelHit::GetY () const inline
Definition at line 75 of file CbmPixelHit.h.
View newest version in sPHENIX GitHub at line 75 of file CbmPixelHit.h
References fY.
Referenced by CbmRichConverter::CopyHitsToRingLight(), CbmRichEventDisplay::DrawOnePmtPlane(), CbmRichGeoTest::HitsAndPoints(), CbmRichUrqmdTest::NofHits(), Position(), CbmRichHit::ToString(), and ToString().
void CbmPixelHit::Position (TVector3 & pos) const
Copies hit position to pos.
Parameters
pos Output hit position.
Definition at line 81 of file CbmPixelHit.cxx.
View newest version in sPHENIX GitHub at line 81 of file CbmPixelHit.cxx
References GetX(), GetY(), and CbmBaseHit::GetZ().
Referenced by CbmRichTestHits::Exec().
void CbmPixelHit::PositionError (TVector3 & dpos) const
Copies hit position error to pos.
Parameters
pos Output hit position error.
Definition at line 86 of file CbmPixelHit.cxx.
View newest version in sPHENIX GitHub at line 86 of file CbmPixelHit.cxx
References GetDx(), GetDy(), and CbmBaseHit::GetDz().
void CbmPixelHit::SetDx (Double_t dx) inline
Definition at line 95 of file CbmPixelHit.h.
View newest version in sPHENIX GitHub at line 95 of file CbmPixelHit.h
References dx, and fDx.
Referenced by SetPositionError().
void CbmPixelHit::SetDxy (Double_t dxy) inline
Definition at line 97 of file CbmPixelHit.h.
View newest version in sPHENIX GitHub at line 97 of file CbmPixelHit.h
References fDxy.
void CbmPixelHit::SetDy (Double_t dy) inline
Definition at line 96 of file CbmPixelHit.h.
View newest version in sPHENIX GitHub at line 96 of file CbmPixelHit.h
References dy, and fDy.
Referenced by SetPositionError().
void CbmPixelHit::SetPosition (const TVector3 & pos)
Sets position of the hit.
Parameters
pos new hit position.
Definition at line 91 of file CbmPixelHit.cxx.
View newest version in sPHENIX GitHub at line 91 of file CbmPixelHit.cxx
References SetX(), SetY(), and CbmBaseHit::SetZ().
Referenced by CbmRichHitProducer::AddHit().
void CbmPixelHit::SetPositionError (const TVector3 & dpos)
Sets position error of the hit.
Parameters
dpos new hit position error
Definition at line 98 of file CbmPixelHit.cxx.
View newest version in sPHENIX GitHub at line 98 of file CbmPixelHit.cxx
References SetDx(), SetDy(), and CbmBaseHit::SetDz().
Referenced by CbmRichHitProducer::AddHit().
void CbmPixelHit::SetX (Double_t x) inline
Definition at line 93 of file CbmPixelHit.h.
View newest version in sPHENIX GitHub at line 93 of file CbmPixelHit.h
References fX, and x.
Referenced by SetPosition().
void CbmPixelHit::SetY (Double_t y) inline
Definition at line 94 of file CbmPixelHit.h.
View newest version in sPHENIX GitHub at line 94 of file CbmPixelHit.h
References fY, and y.
Referenced by SetPosition().
string CbmPixelHit::ToString () const virtual
Inherited from CbmBaseHit.
Implements CbmBaseHit.
Reimplemented in CbmRichHit.
Definition at line 71 of file CbmPixelHit.cxx.
View newest version in sPHENIX GitHub at line 71 of file CbmPixelHit.cxx
References CbmBaseHit::GetAddress(), GetDx(), GetDxy(), GetDy(), CbmBaseHit::GetDz(), CbmBaseHit::GetRefId(), GetX(), GetY(), and CbmBaseHit::GetZ().
Member Data Documentation
Double_t CbmPixelHit::fDx private
Definition at line 113 of file CbmPixelHit.h.
View newest version in sPHENIX GitHub at line 113 of file CbmPixelHit.h
Referenced by GetDx(), and SetDx().
Double_t CbmPixelHit::fDxy private
XY correlation.
Definition at line 114 of file CbmPixelHit.h.
View newest version in sPHENIX GitHub at line 114 of file CbmPixelHit.h
Referenced by GetDxy(), and SetDxy().
Double_t CbmPixelHit::fDy private
X, Y errors [cm].
Definition at line 113 of file CbmPixelHit.h.
View newest version in sPHENIX GitHub at line 113 of file CbmPixelHit.h
Referenced by GetDy(), and SetDy().
Double_t CbmPixelHit::fX private
Definition at line 112 of file CbmPixelHit.h.
View newest version in sPHENIX GitHub at line 112 of file CbmPixelHit.h
Referenced by GetX(), and SetX().
Double_t CbmPixelHit::fY private
X, Y positions of hit [cm].
Definition at line 112 of file CbmPixelHit.h.
View newest version in sPHENIX GitHub at line 112 of file CbmPixelHit.h
Referenced by GetY(), and SetY().
The documentation for this class was generated from the following files:
EicRoot/blob/master/cbmdata/CbmPixelHit.h
EicRoot/blob/master/cbmdata/CbmPixelHit.cxx