EIC Software: CbmRichRingSelectImpl Class Reference
CbmRichRingSelectImpl Class Reference
#include <EicRoot/blob/master/rich/selection/CbmRichRingSelectImpl.h>
Public Member Functions
CbmRichRingSelectImpl ()
Standard constructor.
~CbmRichRingSelectImpl ()
Destructor.
int GetNofHitsOnRingCircle (CbmRichRingLight *ring)
float GetAngle (CbmRichRingLight *ring)
Protected Attributes
std::vector< float > fAlpha
std::vector< float > fPhi
Static Private Attributes
static const int kMAX_NOF_HITS = 100
Detailed Description
Author
Semen Lebedev
Date
2010
Definition at line 28 of file CbmRichRingSelectImpl.h.
View newest version in sPHENIX GitHub at line 28 of file CbmRichRingSelectImpl.h
Constructor & Destructor Documentation
CbmRichRingSelectImpl::CbmRichRingSelectImpl () inline
Standard constructor.
Definition at line 38 of file CbmRichRingSelectImpl.h.
View newest version in sPHENIX GitHub at line 38 of file CbmRichRingSelectImpl.h
References fAlpha, fPhi, and kMAX_NOF_HITS.
CbmRichRingSelectImpl::~CbmRichRingSelectImpl () inline
Destructor.
Definition at line 49 of file CbmRichRingSelectImpl.h.
View newest version in sPHENIX GitHub at line 49 of file CbmRichRingSelectImpl.h
Member Function Documentation
float CbmRichRingSelectImpl::GetAngle (CbmRichRingLight * ring) inline
Calculates the sum of 3 biggest angles between neighboring hits.
Parameters
[in] ring Found and fitted ring.
Definition at line 74 of file CbmRichRingSelectImpl.h.
View newest version in sPHENIX GitHub at line 74 of file CbmRichRingSelectImpl.h
References fAlpha, fPhi, CbmRichHitLight::fX, CbmRichHitLight::fY, CbmRichRingLight::GetCenterX(), CbmRichRingLight::GetCenterY(), CbmRichRingLight::GetHit(), CbmRichRingLight::GetNofHits(), and kMAX_NOF_HITS.
Referenced by CbmRichTrainAnnSelect::DiffFakeTrueCircle(), and CbmRichRingSelectAnn::DoSelect().
int CbmRichRingSelectImpl::GetNofHitsOnRingCircle (CbmRichRingLight * ring) inline
Calculates number of hits on a ring.
Parameters
[in] ring Found and fitted ring.
Definition at line 55 of file CbmRichRingSelectImpl.h.
View newest version in sPHENIX GitHub at line 55 of file CbmRichRingSelectImpl.h
References CbmRichHitLight::fX, CbmRichHitLight::fY, CbmRichRingLight::GetCenterX(), CbmRichRingLight::GetCenterY(), CbmRichRingLight::GetHit(), CbmRichRingLight::GetNofHits(), and CbmRichRingLight::GetRadius().
Referenced by CbmRichTrainAnnSelect::DiffFakeTrueCircle(), and CbmRichRingSelectAnn::DoSelect().
Member Data Documentation
std::vector<float> CbmRichRingSelectImpl::fAlpha protected
Definition at line 121 of file CbmRichRingSelectImpl.h.
View newest version in sPHENIX GitHub at line 121 of file CbmRichRingSelectImpl.h
Referenced by CbmRichRingSelectImpl(), and GetAngle().
std::vector<float> CbmRichRingSelectImpl::fPhi protected
Definition at line 122 of file CbmRichRingSelectImpl.h.
View newest version in sPHENIX GitHub at line 122 of file CbmRichRingSelectImpl.h
Referenced by CbmRichRingSelectImpl(), and GetAngle().
const int CbmRichRingSelectImpl::kMAX_NOF_HITS = 100 static private
Definition at line 32 of file CbmRichRingSelectImpl.h.
View newest version in sPHENIX GitHub at line 32 of file CbmRichRingSelectImpl.h
Referenced by CbmRichRingSelectImpl(), and GetAngle().
The documentation for this class was generated from the following file:
EicRoot/blob/master/rich/selection/CbmRichRingSelectImpl.h