EIC Software: EicMagneticFieldMap Class Reference
EicMagneticFieldMap Class Reference abstract
#include <EicRoot/blob/master/eic/field/EicMagneticFieldMap.h>
Public Member Functions
EicMagneticFieldMap (const char *fileName=0, TGeoMatrix *transformation=0, TGeoShape *shape=0, int color=_DEFAULT_YOKE_COLOR_)
~EicMagneticFieldMap ()
virtual int Initialize ()
bool Initialized () const
virtual int GetFieldValue (const double xx[], double B[]) const =0
TGeoShape * GetShape () const
virtual bool Contains (const double xx[]) const
const TString & GetFileName () const
virtual bool CapableToBuildYoke () const
virtual TString GetDetectorName () const
virtual int ConstructGeometry ()
void SetYokeColor (int color)
int GetYokeColor () const
virtual TGeoVolume * GetYokeVolume () const
Protected Member Functions
const char * BasenameWrapper (const char *fname) const
int GetMD5Signature (unsigned char output[])
Protected Attributes
UInt_t mMD5BufferSize
UChar_t * mMD5Signature
Bool_t mInitialized
TGeoMatrix * mTransformation
indicates whether Initialize() call was made or not
TGeoShape * mShape
Int_t mColor
Private Attributes
TString mFileName
Detailed Description
Definition at line 18 of file EicMagneticFieldMap.h.
View newest version in sPHENIX GitHub at line 18 of file EicMagneticFieldMap.h
Constructor & Destructor Documentation
EicMagneticFieldMap::EicMagneticFieldMap (const char * fileName = 0, TGeoMatrix * transformation = 0, TGeoShape * shape = 0, int color = _DEFAULT_YOKE_COLOR_)
Definition at line 56 of file EicMagneticFieldMap.cxx.
View newest version in sPHENIX GitHub at line 56 of file EicMagneticFieldMap.cxx
References FairLogger::Fatal(), FairLogger::GetLogger(), GetMD5Signature(), MESSAGE_ORIGIN, mFileName, mMD5BufferSize, mMD5Signature, and mShape.
EicMagneticFieldMap::~EicMagneticFieldMap () inline
Definition at line 23 of file EicMagneticFieldMap.h.
View newest version in sPHENIX GitHub at line 23 of file EicMagneticFieldMap.h
Member Function Documentation
const char * EicMagneticFieldMap::BasenameWrapper (const char * fname) const protected
Definition at line 25 of file EicMagneticFieldMap.cxx.
View newest version in sPHENIX GitHub at line 25 of file EicMagneticFieldMap.cxx
Referenced by EicBeamLineElementMap::GetDetectorName().
virtual bool EicMagneticFieldMap::CapableToBuildYoke () const inline virtual
Reimplemented in EicBeamLineElementGrad, and EicBeamLineElementMap.
Definition at line 45 of file EicMagneticFieldMap.h.
View newest version in sPHENIX GitHub at line 45 of file EicMagneticFieldMap.h
Referenced by EicMagneticField::CreateYokeVolumes().
virtual int EicMagneticFieldMap::ConstructGeometry () inline virtual
Reimplemented in EicBeamLineElementGrad, and EicBeamLineElementMap.
Definition at line 50 of file EicMagneticFieldMap.h.
View newest version in sPHENIX GitHub at line 50 of file EicMagneticFieldMap.h
Referenced by EicFieldMapDetector::ConstructGeometry().
bool EicMagneticFieldMap::Contains (const double xx[]) const virtual
Reimplemented in EicPndFieldMap.
Definition at line 119 of file EicMagneticFieldMap.cxx.
View newest version in sPHENIX GitHub at line 119 of file EicMagneticFieldMap.cxx
References mShape, and mTransformation.
Referenced by EicBeamLineElementMap::GetFieldValue(), and EicConstantField::GetFieldValue().
virtual TString EicMagneticFieldMap::GetDetectorName () const inline virtual
Reimplemented in EicBeamLineElementGrad, and EicBeamLineElementMap.
Definition at line 49 of file EicMagneticFieldMap.h.
View newest version in sPHENIX GitHub at line 49 of file EicMagneticFieldMap.h
References GetFileName().
Referenced by EicMagneticField::CreateYokeVolumes().
virtual int EicMagneticFieldMap::GetFieldValue (const double xx[], double B[]) const pure virtual
Implemented in EicPndFieldMap, EicBeamLineElementGrad, EicBeamLineElementMap, and EicConstantField.
Referenced by EicMagneticField::GetFieldSumValue().
const TString& EicMagneticFieldMap::GetFileName (void) const inline
Definition at line 42 of file EicMagneticFieldMap.h.
View newest version in sPHENIX GitHub at line 42 of file EicMagneticFieldMap.h
References mFileName.
Referenced by EicFieldMapDetector::ConstructGeometry(), EicBeamLineElementMap::GetDetectorName(), EicBeamLineElementGrad::GetDetectorName(), GetDetectorName(), EicBeamLineElementMap::Initialize(), and EicMagneticField::InitializeFieldMaps().
int EicMagneticFieldMap::GetMD5Signature (unsigned char output[]) protected
Definition at line 35 of file EicMagneticFieldMap.cxx.
View newest version in sPHENIX GitHub at line 35 of file EicMagneticFieldMap.cxx
References ExpandedFileName(), mFileName, and Acts::open.
Referenced by EicMagneticFieldMap(), and Initialize().
TGeoShape* EicMagneticFieldMap::GetShape () const inline
Definition at line 37 of file EicMagneticFieldMap.h.
View newest version in sPHENIX GitHub at line 37 of file EicMagneticFieldMap.h
References mShape.
Referenced by EicConstantField::GetFieldValue().
int EicMagneticFieldMap::GetYokeColor () const inline
Definition at line 53 of file EicMagneticFieldMap.h.
View newest version in sPHENIX GitHub at line 53 of file EicMagneticFieldMap.h
References mColor.
Referenced by EicBeamLineElementMap::ConstructGeometry(), and EicBeamLineElementGrad::ConstructGeometry().
virtual TGeoVolume* EicMagneticFieldMap::GetYokeVolume () const inline virtual
Reimplemented in EicBeamLineElementGrad, and EicBeamLineElementMap.
Definition at line 55 of file EicMagneticFieldMap.h.
View newest version in sPHENIX GitHub at line 55 of file EicMagneticFieldMap.h
Referenced by EicFieldMapDetector::ConstructGeometry().
int EicMagneticFieldMap::Initialize () virtual
Reimplemented in EicPndFieldMap, EicBeamLineElementGrad, EicConstantField, and EicBeamLineElementMap.
Definition at line 91 of file EicMagneticFieldMap.cxx.
View newest version in sPHENIX GitHub at line 91 of file EicMagneticFieldMap.cxx
References FairLogger::Fatal(), FairLogger::GetLogger(), GetMD5Signature(), MESSAGE_ORIGIN, mFileName, mInitialized, and mMD5Signature.
Referenced by EicBeamLineElementMap::Initialize(), EicConstantField::Initialize(), EicBeamLineElementGrad::Initialize(), EicPndFieldMap::Initialize(), and EicMagneticField::InitializeFieldMaps().
bool EicMagneticFieldMap::Initialized () const inline
Definition at line 31 of file EicMagneticFieldMap.h.
View newest version in sPHENIX GitHub at line 31 of file EicMagneticFieldMap.h
References mInitialized.
Referenced by EicMagneticField::InitializeFieldMaps().
void EicMagneticFieldMap::SetYokeColor (int color) inline
Definition at line 52 of file EicMagneticFieldMap.h.
View newest version in sPHENIX GitHub at line 52 of file EicMagneticFieldMap.h
References color, and mColor.
Referenced by EicMagneticFieldFromGradients::AddBeamLineElementGrads(), EicMagneticField::AddBeamLineElementGrads(), and EicMagneticField::AddBeamLineElementMaps().
Member Data Documentation
Int_t EicMagneticFieldMap::mColor protected
Definition at line 77 of file EicMagneticFieldMap.h.
View newest version in sPHENIX GitHub at line 77 of file EicMagneticFieldMap.h
Referenced by GetYokeColor(), and SetYokeColor().
TString EicMagneticFieldMap::mFileName private
Definition at line 63 of file EicMagneticFieldMap.h.
View newest version in sPHENIX GitHub at line 63 of file EicMagneticFieldMap.h
Referenced by EicMagneticFieldMap(), GetFileName(), GetMD5Signature(), and Initialize().
Bool_t EicMagneticFieldMap::mInitialized protected
Definition at line 68 of file EicMagneticFieldMap.h.
View newest version in sPHENIX GitHub at line 68 of file EicMagneticFieldMap.h
Referenced by EicConstantField::GetFieldValue(), Initialize(), and Initialized().
UInt_t EicMagneticFieldMap::mMD5BufferSize protected
Definition at line 66 of file EicMagneticFieldMap.h.
View newest version in sPHENIX GitHub at line 66 of file EicMagneticFieldMap.h
Referenced by EicMagneticFieldMap().
UChar_t* EicMagneticFieldMap::mMD5Signature protected
Definition at line 67 of file EicMagneticFieldMap.h.
View newest version in sPHENIX GitHub at line 67 of file EicMagneticFieldMap.h
Referenced by EicMagneticFieldMap(), and Initialize().
TGeoShape* EicMagneticFieldMap::mShape protected
Definition at line 75 of file EicMagneticFieldMap.h.
View newest version in sPHENIX GitHub at line 75 of file EicMagneticFieldMap.h
Referenced by Contains(), EicConstantBoxField::EicConstantBoxField(), EicConstantTubeField::EicConstantTubeField(), EicMagneticFieldMap(), GetShape(), and EicBeamLineElementMap::Initialize().
TGeoMatrix* EicMagneticFieldMap::mTransformation protected
indicates whether Initialize() call was made or not
Definition at line 70 of file EicMagneticFieldMap.h.
View newest version in sPHENIX GitHub at line 70 of file EicMagneticFieldMap.h
Referenced by EicBeamLineElementMap::ConstructGeometry(), Contains(), EicConstantBoxField::EicConstantBoxField(), EicConstantTubeField::EicConstantTubeField(), EicBeamLineElementMap::GetFieldValue(), EicBeamLineElementMap::Initialize(), and EicConstantField::Initialize().
The documentation for this class was generated from the following files:
EicRoot/blob/master/eic/field/EicMagneticFieldMap.h
EicRoot/blob/master/eic/field/EicMagneticFieldMap.cxx