EIC Software: VstGeoParData Class Reference
VstGeoParData Class Reference
#include <EicRoot/blob/master/eic/detectors/maps/VstGeoParData.h>
Public Member Functions
VstGeoParData (int version=-1, int subVersion=0)
~VstGeoParData ()
void AddBarrelLayer (MapsMimosaAssembly *chipAssembly, unsigned staveNum, unsigned chipNum, double radius, double slope, double asimuthalOffset=0.0)
unsigned GetNumberOfLayers () const
const VstBarrelLayer * GetBarrelLayer (unsigned layerID) const
int ConstructGeometry (bool root=true, bool gdml=false, bool check=false)
VstGeoParData (int version=-1, int subVersion=0)
~VstGeoParData ()
void AddBarrelLayer (MapsMimosaAssembly *chipAssembly, unsigned staveNum, unsigned chipNum, double radius, double slope, double asimuthalOffset=0.0)
unsigned GetNumberOfLayers () const
const VstBarrelLayer * GetBarrelLayer (unsigned layerID) const
int ConstructGeometry (bool root=true, bool gdml=false, bool check=false)
Public Member Functions inherited from MapsGeoParData
MapsGeoParData (const char *detName=0, int version=-1, int subVersion=0)
~MapsGeoParData ()
void UseTriangularAssemblies (bool yesNo)
bool UseTriangularAssemblies () const
void WithMountingRings (bool yesNo)
bool WithMountingRings () const
void WithEnforcementBrackets (bool yesNo)
bool WithEnforcementBrackets () const
void WithExternalPipes (bool yesNo)
bool WithExternalPipes () const
void SetCarbonFiberMaterial (const char *material)
void SetKaptonMaterial (const char *material)
MapsGeoParData (const char *detName=0, int version=-1, int subVersion=0)
~MapsGeoParData ()
void UseTriangularAssemblies (bool yesNo=true)
void WithMountingRings (bool yesNo=true)
void WithEnforcementBrackets (bool yesNo=true)
void WithExternalPipes (bool yesNo=true)
void SetCarbonFiberMaterial (const char *material)
void SetKaptonMaterial (const char *material)
Public Member Functions inherited from EicGeoParData
EicGeoParData (const char *detName=0, int version=-1, int subVersion=0)
~EicGeoParData ()
void ResetVars ()
void SetGeometryType (GeometryType gType)
GeometryType GetGeometryType () const
void SetTestGeometryFlag (bool flag=true)
bool IsTestGeometry () const
int GetVersion () const
int GetSubVersion () const
void SetFileName (const char *fileName)
void SetFileNameFormat (const char *fileNameFormat)
void SetComment (const char *comment)
int AttachSourceFile (const char *fileName)
void PrintAttachedSourceFile (const char *fileName)
EicGeoMap * CreateNewMap ()
int SetCircularX (unsigned group=0)
int SetCircularY (unsigned group=0)
int SetCircularZ (unsigned group=0)
bool GetCircularX (unsigned group=0) const
bool GetCircularY (unsigned group=0) const
bool GetCircularZ (unsigned group=0) const
bool GetCircular (unsigned group, unsigned what) const
int SetMappingTableEntry (EicGeoMap *map, const unsigned geant[], unsigned group, unsigned logical[])
int AddLogicalVolumeGroup (unsigned dimX=0, unsigned dimY=0, unsigned dimZ=0)
void AddBlackHoleVolume (const char *vName)
void AddStepEnforcedVolume (const char *vName)
void AddStepEnforcedVolumeLookupEntry (int volumeID, double step)
const TGeoMedium * GetMedium (const char *medium)
void SetTopVolumeTransformation (TGeoMatrix *transformation)
const TGeoMatrix * GetTopVolumeTransformation () const
TString GetGeometryFileName (bool root=true) const
virtual void Print (const char *option=0) const
TGeoVolume * GetTopVolume () const
TGeoManager * GetRootGeoManager ()
void FinalizeOutput (bool root=true, bool gdml=false, bool check=false)
UInt_t GetMapNum () const
EicGeoMap * GetMapPtrViaMapID (unsigned mapId) const
const EicGeoMap * GetMapPtrViaHitMultiIndex (ULong64_t multi) const
int CalculateMappingTableSignatures ()
unsigned GetMaxVolumeLevelNum () const
ULogicalIndex_t GeantMultiToLogicalIndex (ULong64_t multi) const
unsigned GetDimX (unsigned group=0) const
unsigned GetDimY (unsigned group=0) const
unsigned GetDimZ (unsigned group=0) const
unsigned GetDim (unsigned group, unsigned what) const
unsigned GetGroup (ULogicalIndex_t logicalID) const
unsigned GetX (ULogicalIndex_t logicalID) const
unsigned GetY (ULogicalIndex_t logicalID) const
unsigned GetZ (ULogicalIndex_t logicalID) const
unsigned GetCoord (unsigned what, ULogicalIndex_t logicalID) const
bool IsBlackHoleVolume (const char *vName) const
const std::set< TString > & GetBlackHoleVolumes () const
double GetEnforcedStep (int volumeID)
const std::set< TString > & GetStepEnforcedVolumes () const
void InitializeLookupTables ()
LogicalVolumeLookupTableEntry * GetLookupTableNode (ULogicalIndex_t xy) const
LogicalVolumeLookupTableEntry * GetLookupTableNode (const TGeoNode *node) const
EicNamePatternHub< Color_t > * GetColorTable ()
EicNamePatternHub< Char_t > * GetTransparencyTable ()
virtual bool AreNeighbours (ULogicalIndex_t l1, ULogicalIndex_t l2, unsigned maxLinearDist=1, unsigned maxChebyshevDist=0) const
const EicDetName * GetDetName () const
void AddWantedParticle (const char *vName, int pdg)
bool IsWantedParticle (const char *vName, int pdg) const
EicGeoParData (const char *detName=0, int version=-1, int subVersion=0)
~EicGeoParData ()
void ResetVars ()
void SetGeometryType (GeometryType gType)
GeometryType GetGeometryType () const
void SetTestGeometryFlag (bool flag=true)
bool IsTestGeometry () const
int GetVersion () const
int GetSubVersion () const
void SetFileName (const char *fileName)
void SetFileNameFormat (const char *fileNameFormat)
void SetTransparency (unsigned value)
void SetComment (const char *comment)
int AttachSourceFile (const char *fileName)
void PrintAttachedSourceFile (const char *fileName)
EicGeoMap * CreateNewMap ()
int SetCircularX (unsigned group=0)
int SetCircularY (unsigned group=0)
int SetCircularZ (unsigned group=0)
bool GetCircularX (unsigned group=0) const
bool GetCircularY (unsigned group=0) const
bool GetCircularZ (unsigned group=0) const
bool GetCircular (unsigned group, unsigned what) const
int SetMappingTableEntry (EicGeoMap *map, const unsigned geant[], unsigned group, unsigned logical[])
int AddLogicalVolumeGroup (unsigned dimX=0, unsigned dimY=0, unsigned dimZ=0)
void AddBlackHoleVolume (const char *vName)
void AddStepEnforcedVolume (const char *vName)
void AddStepEnforcedVolumeLookupEntry (int volumeID, double step)
const TGeoMedium * GetMedium (const char *medium)
void SetTopVolumeTransformation (TGeoMatrix *transformation)
const TGeoMatrix * GetTopVolumeTransformation () const
TString GetGeometryFileName (bool root=true) const
virtual void Print (const char *option=0) const
TGeoVolume * GetTopVolume () const
TGeoManager * GetRootGeoManager ()
void FinalizeOutput (bool root=true, bool gdml=false, bool check=false)
UInt_t GetMapNum () const
EicGeoMap * GetMapPtrViaMapID (unsigned mapId) const
const EicGeoMap * GetMapPtrViaHitMultiIndex (ULong64_t multi) const
int CalculateMappingTableSignatures ()
unsigned GetMaxVolumeLevelNum () const
ULogicalIndex_t GeantMultiToLogicalIndex (ULong64_t multi) const
void PlaceG4Volume (G4LogicalVolume *mother, bool check=false, void *pRot=0, void *tlate=0)
unsigned GetDimX (unsigned group=0) const
unsigned GetDimY (unsigned group=0) const
unsigned GetDimZ (unsigned group=0) const
unsigned GetDim (unsigned group, unsigned what) const
unsigned GetGroup (ULogicalIndex_t logicalID) const
unsigned GetX (ULogicalIndex_t logicalID) const
unsigned GetY (ULogicalIndex_t logicalID) const
unsigned GetZ (ULogicalIndex_t logicalID) const
unsigned GetCoord (unsigned what, ULogicalIndex_t logicalID) const
bool IsBlackHoleVolume (const char *vName) const
const std::set< TString > & GetBlackHoleVolumes () const
double GetEnforcedStep (int volumeID)
const std::set< TString > & GetStepEnforcedVolumes () const
void InitializeLookupTables ()
LogicalVolumeLookupTableEntry * GetLookupTableNode (ULogicalIndex_t xy) const
LogicalVolumeLookupTableEntry * GetLookupTableNode (const TGeoNode *node) const
EicNamePatternHub< Color_t > * GetColorTable ()
EicNamePatternHub< Char_t > * GetTransparencyTable ()
virtual bool AreNeighbours (ULogicalIndex_t l1, ULogicalIndex_t l2, unsigned maxLinearDist=1, unsigned maxChebyshevDist=0) const
const EicDetName * GetDetName () const
void AddWantedParticle (const char *vName, int pdg)
bool IsWantedParticle (const char *vName, int pdg) const
void SetTGeoGeometryCheckPrecision (double value)
void TurnTGeoGeometryCheckOff (void)
const std::vector
< G4VPhysicalVolume * > & GetG4Volumes (void) const
const std::map
< G4VPhysicalVolume
*, unsigned > & GetG4SensitiveVolumes (void) const
ClassDef (EicGeoParData, 51)
Public Attributes
Double_t mMountingRingRadialOffset
Public Attributes inherited from MapsGeoParData
Double_t mMountingRingBeamLineThickness
Double_t mMountingRingRadialThickness
Double_t mWaterPipeExtensionLength
Double_t mEnforcementBracketThickness
Private Member Functions
ClassDef (VstGeoParData, 8)
ClassDef (VstGeoParData, 8)
Private Attributes
std::vector< VstBarrelLayer * > mBarrel
Additional Inherited Members
Public Types inherited from EicGeoParData
enum GeometryType {
Undefined, NoStructure, SimpleStructure, FullStructure,
Undefined, NoStructure, SimpleStructure, FullStructure
}
enum IDXYZ {
IDX =0, IDY, IDZ, IDX =0,
IDY, IDZ
}
enum GeometryType {
Undefined, NoStructure, SimpleStructure, FullStructure,
Undefined, NoStructure, SimpleStructure, FullStructure
}
enum IDXYZ {
IDX =0, IDY, IDZ, IDX =0,
IDY, IDZ
}
Static Public Member Functions inherited from EicGeoParData
static int ImportMediaFile (const char *fname)
Protected Member Functions inherited from MapsGeoParData
TGeoVolume * ConstructMimosaCell (MapsMimosaAssembly *mcell, unsigned id)
double GetExpectedStaveLength (unsigned chipNum, MapsMimosaAssembly *mcell)
double GetAssemblyContainerWidth (const MapsMimosaAssembly *mcell) const
MapsStave * ConstructStave (unsigned chipNum, unsigned id, MapsMimosaAssembly *mcell)
MapsStave * ConstructStaveWithMapping (unsigned chipNum, unsigned id, MapsMimosaAssembly *mcell)
ClassDef (MapsGeoParData, 10)
TGeoVolume * ConstructMimosaCell (MapsMimosaAssembly *mcell, unsigned id)
double GetExpectedStaveLength (unsigned chipNum, MapsMimosaAssembly *mcell)
double GetAssemblyContainerWidth (const MapsMimosaAssembly *mcell) const
MapsStave * ConstructStave (unsigned chipNum, unsigned id, MapsMimosaAssembly *mcell)
MapsStave * ConstructStaveWithMapping (unsigned chipNum, unsigned id, MapsMimosaAssembly *mcell)
ClassDef (MapsGeoParData, 10)
Protected Attributes inherited from MapsGeoParData
TString mCarbonFiberMaterial
TString mKaptonMaterial
char mMimosaCoreName [128]
char mMimosaShellName [128]
char mCellAssemblyName [128]
double mAssemblyHeight
double mAssemblyLength
double mWaterPipeXoffset
double mWaterPipeZoffset
double mMimosaOffset
Detailed Description
Definition at line 40 of file VstGeoParData.h.
View newest version in sPHENIX GitHub at line 40 of file VstGeoParData.h
Constructor & Destructor Documentation
VstGeoParData::VstGeoParData (int version = -1, int subVersion = 0) inline
Definition at line 45 of file VstGeoParData.h.
View newest version in sPHENIX GitHub at line 45 of file VstGeoParData.h
VstGeoParData::~VstGeoParData () inline
Definition at line 47 of file VstGeoParData.h.
View newest version in sPHENIX GitHub at line 47 of file VstGeoParData.h
VstGeoParData::VstGeoParData (int version = -1, int subVersion = 0)
VstGeoParData::~VstGeoParData () inline
Definition at line 46 of file VstGeoParData.h.
View newest version in sPHENIX GitHub at line 46 of file VstGeoParData.h
Member Function Documentation
void VstGeoParData::AddBarrelLayer (MapsMimosaAssembly * chipAssembly, unsigned staveNum, unsigned chipNum, double radius, double slope, double asimuthalOffset = 0.0) inline
Definition at line 48 of file VstGeoParData.h.
View newest version in sPHENIX GitHub at line 48 of file VstGeoParData.h
References mBarrel.
void VstGeoParData::AddBarrelLayer (MapsMimosaAssembly * chipAssembly, unsigned staveNum, unsigned chipNum, double radius, double slope, double asimuthalOffset = 0.0) inline
Definition at line 49 of file VstGeoParData.h.
View newest version in sPHENIX GitHub at line 49 of file VstGeoParData.h
References mBarrel.
Referenced by BasicDetectorConstruction::Construct(), and vst().
VstGeoParData::ClassDef (VstGeoParData , 8) private
VstGeoParData::ClassDef (VstGeoParData , 8) private
int VstGeoParData::ConstructGeometry (bool root = true, bool gdml = false, bool check = false) virtual
Reimplemented from EicGeoParData.
int VstGeoParData::ConstructGeometry (bool root = true, bool gdml = false, bool check = false) virtual
Reimplemented from EicGeoParData.
Definition at line 22 of file VstGeoParData.cxx.
View newest version in sPHENIX GitHub at line 22 of file VstGeoParData.cxx
References EicGeoMap::AddGeantVolumeLevel(), AddLogicalVolumeGroup(), MapsGeoParData::ConstructStave(), cos(), EicGeoParData::CreateNewMap(), exit(), FinalizeOutput(), gamma(), MapsStave::GetLength(), GetMedium, EicGeoParData::GetTopVolume(), MapsStave::GetVolume(), VstBarrelLayer::mAsimuthalOffset, MapsGeoParData::mCarbonFiberMaterial, MapsGeoParData::mCellAssemblyName, VstBarrelLayer::mChipAssembly, VstBarrelLayer::mMimosaChipNum, MapsGeoParData::mMimosaCoreName, MapsGeoParData::mMimosaOffset, MapsGeoParData::mMimosaShellName, MapsGeoParData::mMountingRingBeamLineThickness, MapsGeoParData::mMountingRingRadialThickness, VstBarrelLayer::mRadius, VstBarrelLayer::mStaveNum, VstBarrelLayer::mStaveSlope, printf(), rw, EicGeoParData::SetMappingTableEntry(), EicGeoMap::SetSingleSensorContainerVolume(), and MapsGeoParData::WithMountingRings().
Referenced by vst().
const VstBarrelLayer* VstGeoParData::GetBarrelLayer (unsigned layerID) const inline
Definition at line 57 of file VstGeoParData.h.
View newest version in sPHENIX GitHub at line 57 of file VstGeoParData.h
References mBarrel.
const VstBarrelLayer* VstGeoParData::GetBarrelLayer (unsigned layerID) const inline
Definition at line 58 of file VstGeoParData.h.
View newest version in sPHENIX GitHub at line 58 of file VstGeoParData.h
References mBarrel.
unsigned VstGeoParData::GetNumberOfLayers () const inline
Definition at line 55 of file VstGeoParData.h.
View newest version in sPHENIX GitHub at line 55 of file VstGeoParData.h
References mBarrel.
unsigned VstGeoParData::GetNumberOfLayers () const inline
Definition at line 56 of file VstGeoParData.h.
View newest version in sPHENIX GitHub at line 56 of file VstGeoParData.h
References mBarrel.
Member Data Documentation
std::vector< VstBarrelLayer * > VstGeoParData::mBarrel private
Definition at line 68 of file VstGeoParData.h.
View newest version in sPHENIX GitHub at line 68 of file VstGeoParData.h
Referenced by AddBarrelLayer(), GetBarrelLayer(), and GetNumberOfLayers().
Double_t VstGeoParData::mMountingRingRadialOffset
Definition at line 60 of file VstGeoParData.h.
View newest version in sPHENIX GitHub at line 60 of file VstGeoParData.h
Referenced by vst().
The documentation for this class was generated from the following files:
EicRoot/blob/master/eic/detectors/maps/VstGeoParData.h
EicToyModel/blob/master/include/VstGeoParData.h
EicRoot/blob/master/eic/detectors/maps/VstGeoParData.cxx
EicToyModel/blob/master/source/eicroot/VstGeoParData.cxx