EIC Software: Acts::HelicalTrackLinearizer< propagator_t, propagator_options_t > Class Template Reference
Acts::HelicalTrackLinearizer< propagator_t, propagator_options_t > Class Template Reference
#include <fun4all_acts/blob/master/Core/include/Acts/Vertexing/HelicalTrackLinearizer.hpp>
Classes
struct Config
Configuration struct.
Public Types
using Propagator_t = propagator_t
using BField_t = typename Propagator_t::Stepper::BField
Public Member Functions
HelicalTrackLinearizer (const Config &config)
Constructor.
Result< LinearizedTrack > linearizeTrack (const BoundParameters &params, const SpacePointVector &linPoint, const Acts::GeometryContext &gctx, const Acts::MagneticFieldContext &mctx) const
Function that linearizes BoundParameters at given linearization point.
Private Attributes
const Config m_cfg
Configuration object.
Detailed Description
template<typename propagator_t, typename propagator_options_t = PropagatorOptions<>>
class Acts::HelicalTrackLinearizer< propagator_t, propagator_options_t >
Linearizes the measurement equation (dependance of track parameters on the vertex position and track momentum at vertex) at the vicinity of the user-provided linearization point.
The measurement equation is linearized in the following way:
q_k= A_k (x_k - x_0k) + B_k (p_k - p_0k) + c_k
where q_k are the parameters at perigee nearest to the lin point, x_k is the position of the vertex, p_k the track momentum at the vertex, and c_k is the constant term of expansion. A_k and B_k are matrices of derivatives, denoted hereafter as "positionJacobian" and "momentumJacobian" respectively.
Ref.(1) - CERN-THESIS-2010-027, Giacinto Piacquadio (Freiburg U.)
Template Parameters
propagator_t Propagator type
propagator_options_t Propagator options type
Definition at line 44 of file HelicalTrackLinearizer.hpp.
View newest version in sPHENIX GitHub at line 44 of file HelicalTrackLinearizer.hpp
Member Typedef Documentation
template<typename propagator_t , typename propagator_options_t = PropagatorOptions<>> using Acts::HelicalTrackLinearizer< propagator_t, propagator_options_t >::BField_t = typename Propagator_t::Stepper::BField
Definition at line 47 of file HelicalTrackLinearizer.hpp.
View newest version in sPHENIX GitHub at line 47 of file HelicalTrackLinearizer.hpp
template<typename propagator_t , typename propagator_options_t = PropagatorOptions<>> using Acts::HelicalTrackLinearizer< propagator_t, propagator_options_t >::Propagator_t = propagator_t
Definition at line 46 of file HelicalTrackLinearizer.hpp.
View newest version in sPHENIX GitHub at line 46 of file HelicalTrackLinearizer.hpp
Constructor & Destructor Documentation
template<typename propagator_t , typename propagator_options_t = PropagatorOptions<>> Acts::HelicalTrackLinearizer< propagator_t, propagator_options_t >::HelicalTrackLinearizer (const Config & config) inline
Constructor.
Parameters
config Configuration object
Definition at line 80 of file HelicalTrackLinearizer.hpp.
View newest version in sPHENIX GitHub at line 80 of file HelicalTrackLinearizer.hpp
Member Function Documentation
template<typename propagator_t , typename propagator_options_t > Acts::Result< Acts::LinearizedTrack > Acts::HelicalTrackLinearizer< propagator_t, propagator_options_t >::linearizeTrack (const BoundParameters & params, const SpacePointVector & linPoint, const Acts::GeometryContext & gctx, const Acts::MagneticFieldContext & mctx) const
Function that linearizes BoundParameters at given linearization point.
Parameters
params Parameters to linearize
linPoint Linearization point
gctx The geometry context
mctx The magnetic field context
Returns
Linearized track
F(V, p_i) at PCA in Billoir paper (see FullBilloirVertexFitter.hpp for paper reference, Page 140, Eq. (2))
Definition at line 13 of file HelicalTrackLinearizer.ipp.
View newest version in sPHENIX GitHub at line 13 of file HelicalTrackLinearizer.ipp
References kdfinder::abs(), Acts::backward, Acts::IntegrationTest::Bz, cos(), Acts::SingleTrackParameters< ChargePolicy >::covariance(), Acts::ePHI, Acts::eQOP, Acts::eTHETA, Acts::eZ, Acts::SingleTrackParameters< ChargePolicy >::get(), M_PI, Acts::SingleTrackParameters< ChargePolicy >::parameters(), Acts::SingleTrackParameters< ChargePolicy >::position(), Acts::VectorHelpers::position(), and Acts::IntegrationTest::R.
Referenced by Acts::Test::BOOST_AUTO_TEST_CASE().
Member Data Documentation
template<typename propagator_t , typename propagator_options_t = PropagatorOptions<>> const Config Acts::HelicalTrackLinearizer< propagator_t, propagator_options_t >::m_cfg private
Configuration object.
Definition at line 98 of file HelicalTrackLinearizer.hpp.
View newest version in sPHENIX GitHub at line 98 of file HelicalTrackLinearizer.hpp
The documentation for this class was generated from the following files:
fun4all_acts/blob/master/Core/include/Acts/Vertexing/HelicalTrackLinearizer.hpp
fun4all_acts/blob/master/Core/include/Acts/Vertexing/HelicalTrackLinearizer.ipp