EIC Software: FairParIo Class Reference
FairParIo Class Reference
#include <EicRoot/blob/master/parbase/FairParIo.h>
Public Member Functions
FairParIo ()
virtual ~FairParIo ()
virtual FairDetParIo * getDetParIo (const Text_t *)
virtual void setDetParIo (FairDetParIo *)
virtual void removeDetParIo (Text_t *)
void setInputNumber (Int_t)
virtual void close ()
const char * getFilename ()
virtual void setDetParIo (Text_t *)
virtual void print ()
virtual Bool_t check ()
virtual void readVersions (FairRtdbRun *)
virtual void cd ()
void setAutoWritable (Bool_t f=kTRUE)
Bool_t isAutoWritable ()
Protected Attributes
TList * detParIoList
Bool_t autoWritable
TString filename
Private Member Functions
FairParIo (const FairParIo &)
FairParIo & operator= (const FairParIo &)
Detailed Description
Definition at line 10 of file FairParIo.h.
View newest version in sPHENIX GitHub at line 10 of file FairParIo.h
Constructor & Destructor Documentation
FairParIo::FairParIo ()
FairParIo::~FairParIo () virtual
Definition at line 29 of file FairParIo.cxx.
View newest version in sPHENIX GitHub at line 29 of file FairParIo.cxx
References detParIoList.
FairParIo::FairParIo (const FairParIo &) private
Member Function Documentation
virtual void FairParIo::cd () inline virtual
Reimplemented in FairParRootFileIo.
Definition at line 44 of file FairParIo.h.
View newest version in sPHENIX GitHub at line 44 of file FairParIo.h
Referenced by FairRuntimeDb::closeFirstInput(), FairRuntimeDb::closeSecondInput(), FairRuntimeDb::getFirstInput(), FairRuntimeDb::getOutput(), FairRuntimeDb::getSecondInput(), grv94di(), grv94ho(), grv94lo(), pygrvd(), pygrvl(), pygrvm(), and FairRuntimeDb::writeVersions().
virtual Bool_t FairParIo::check () inline virtual
Reimplemented in FairParTSQLIo, FairParRootFileIo, and FairParAsciiFileIo.
Definition at line 37 of file FairParIo.h.
View newest version in sPHENIX GitHub at line 37 of file FairParIo.h
Referenced by FairRuntimeDb::readAll(), FairRuntimeDb::setFirstInput(), FairRuntimeDb::setOutput(), FairRuntimeDb::setSecondInput(), FairRuntimeDb::writeContainer(), and FairRuntimeDb::writeVersions().
virtual void FairParIo::close () inline virtual
Reimplemented in FairParRootFileIo, and FairParAsciiFileIo.
Definition at line 23 of file FairParIo.h.
View newest version in sPHENIX GitHub at line 23 of file FairParIo.h
Referenced by FairRuntimeDb::closeFirstInput(), FairRuntimeDb::closeOutput(), and FairRuntimeDb::closeSecondInput().
FairDetParIo * FairParIo::getDetParIo (const Text_t * detName) virtual
Definition at line 57 of file FairParIo.cxx.
View newest version in sPHENIX GitHub at line 57 of file FairParIo.cxx
References detParIoList.
Referenced by FairRuntimeDb::activateParIo(), and FairParGenericSet::write().
const char* FairParIo::getFilename () inline
Definition at line 26 of file FairParIo.h.
View newest version in sPHENIX GitHub at line 26 of file FairParIo.h
References filename.
Referenced by FairRunAna::RunOnProof().
Bool_t FairParIo::isAutoWritable () inline
Definition at line 48 of file FairParIo.h.
View newest version in sPHENIX GitHub at line 48 of file FairParIo.h
References autoWritable.
Referenced by FairRuntimeDb::closeOutput(), and FairRuntimeDb::writeContainer().
FairParIo& FairParIo::operator= (const FairParIo &) private
virtual void FairParIo::print () inline virtual
Reimplemented in FairParTSQLIo, FairParRootFileIo, and FairParAsciiFileIo.
Definition at line 34 of file FairParIo.h.
View newest version in sPHENIX GitHub at line 34 of file FairParIo.h
Referenced by FairRuntimeDb::print().
virtual void FairParIo::readVersions (FairRtdbRun *) inline virtual
Reimplemented in FairParRootFileIo.
Definition at line 40 of file FairParIo.h.
View newest version in sPHENIX GitHub at line 40 of file FairParIo.h
Referenced by FairRuntimeDb::initContainers().
void FairParIo::removeDetParIo (Text_t * detName) virtual
Definition at line 63 of file FairParIo.cxx.
View newest version in sPHENIX GitHub at line 63 of file FairParIo.cxx
References detParIoList, and p.
void FairParIo::setAutoWritable (Bool_t f = kTRUE) inline
Definition at line 47 of file FairParIo.h.
View newest version in sPHENIX GitHub at line 47 of file FairParIo.h
References autoWritable.
void FairParIo::setDetParIo (FairDetParIo * detParIo) virtual
Definition at line 39 of file FairParIo.cxx.
View newest version in sPHENIX GitHub at line 39 of file FairParIo.cxx
References detParIoList.
Referenced by FairRuntimeDb::activateParIo().
virtual void FairParIo::setDetParIo (Text_t *) inline virtual
Reimplemented in FairParTSQLIo.
Definition at line 31 of file FairParIo.h.
View newest version in sPHENIX GitHub at line 31 of file FairParIo.h
void FairParIo::setInputNumber (Int_t num)
Definition at line 47 of file FairParIo.cxx.
View newest version in sPHENIX GitHub at line 47 of file FairParIo.cxx
References detParIoList, and FairDetParIo::setInputNumber().
Referenced by FairRuntimeDb::setFirstInput(), and FairRuntimeDb::setSecondInput().
Member Data Documentation
Bool_t FairParIo::autoWritable protected
Definition at line 14 of file FairParIo.h.
View newest version in sPHENIX GitHub at line 14 of file FairParIo.h
Referenced by isAutoWritable(), and setAutoWritable().
TList* FairParIo::detParIoList protected
Definition at line 13 of file FairParIo.h.
View newest version in sPHENIX GitHub at line 13 of file FairParIo.h
Referenced by FairParTSQLIo::activateDetIo(), FairParAsciiFileIo::close(), FairParRootFileIo::close(), getDetParIo(), FairParAsciiFileIo::print(), FairParRootFileIo::print(), FairParTSQLIo::print(), removeDetParIo(), setDetParIo(), FairParTSQLIo::setDetParIo(), setInputNumber(), and ~FairParIo().
TString FairParIo::filename protected
Definition at line 15 of file FairParIo.h.
View newest version in sPHENIX GitHub at line 15 of file FairParIo.h
Referenced by FairParAsciiFileIo::close(), getFilename(), FairParAsciiFileIo::open(), FairParRootFileIo::open(), and FairParAsciiFileIo::print().
The documentation for this class was generated from the following files:
EicRoot/blob/master/parbase/FairParIo.h
EicRoot/blob/master/parbase/FairParIo.cxx