EIC Software: EICAnalysisTools Namespace Reference
EICAnalysisTools Namespace Reference
Functions
def UprootLoad
def TotalXSection
def DISBjorkenX
def DifferentialTaggingYield
Differential Computation Functions.
def DifferentialTaggingEfficiency
def DifferentialTaggingYield
Differential Computation Functions.
def DifferentialTaggingEfficiency
Variables
int u_fb 1
Units.
int u_mb 1
int u_pb 1
int n_gen 10
Function Documentation
def EICAnalysisTools.DifferentialTaggingEfficiency (df, x = 'Jet.PT', xrange = [10, xbins = [10, which = 'all')
Definition at line 167 of file EICAnalysisTools.py.
View newest version in sPHENIX GitHub at line 167 of file EICAnalysisTools.py
References print().
Referenced by DifferentialTaggingEfficiency().
def EICAnalysisTools.DifferentialTaggingEfficiency (df, x = 'jet_pt', xrange = [10, xbins = [10, which = 'all', taggers = "jet_sip3dtag")
Definition at line 178 of file EICAnalysisTools.py.
View newest version in sPHENIX GitHub at line 178 of file EICAnalysisTools.py
References DifferentialTaggingEfficiency(), and print().
def EICAnalysisTools.DifferentialTaggingYield (df, x = 'Jet.PT', xrange = [10, xbins = [10, which = 'all', process = 'CC_DIS_e18_p275', target_lumi = 100)
Differential Computation Functions.
Definition at line 112 of file EICAnalysisTools.py.
View newest version in sPHENIX GitHub at line 112 of file EICAnalysisTools.py
References print(), and TotalXSection().
Referenced by DifferentialTaggingYield().
def EICAnalysisTools.DifferentialTaggingYield (df, x = 'jet_pt', xrange = [10, xbins = [10, which = 'all', process = 'CC_DIS_e18_p275', target_lumi = 100, taggers = "jet_sip3dtag")
Differential Computation Functions.
Definition at line 128 of file EICAnalysisTools.py.
View newest version in sPHENIX GitHub at line 128 of file EICAnalysisTools.py
References DifferentialTaggingYield(), print(), and TotalXSection().
def EICAnalysisTools.DISBjorkenX (row)
pProton      = branchParticle.At(0).P4(); #these numbers 0 , 3, 5 are hardcoded in Pythia8
pleptonIn    = branchParticle.At(3).P4();
pleptonOut   = branchParticle.At(5).P4();
pPhoton      = pleptonIn - pleptonOut;
#Q2, W2, Bjorken x, y, nu.
Q2 = -pPhoton.M2()
W2 = (pProton + pPhoton).M2()
x = Q2 / (2. * pProton.Dot(pPhoton))
y = (pProton.Dot(pPhoton)) / (pProton.Dot(pleptonIn))
Definition at line 66 of file EICAnalysisTools.py.
View newest version in sPHENIX GitHub at line 66 of file EICAnalysisTools.py
def EICAnalysisTools.TotalXSection (process = 'CC_DIS_e18_p275')
Definition at line 40 of file EICAnalysisTools.py.
View newest version in sPHENIX GitHub at line 40 of file EICAnalysisTools.py
References print().
Referenced by DifferentialTaggingYield().
def EICAnalysisTools.UprootLoad (files = [], treename = "", branches = [])
Definition at line 23 of file EICAnalysisTools.py.
View newest version in sPHENIX GitHub at line 23 of file EICAnalysisTools.py
References print().
Variable Documentation
int EICAnalysisTools.n_gen 10
Definition at line 23 of file EICAnalysisTools.py.
View newest version in sPHENIX GitHub at line 23 of file EICAnalysisTools.py
int EICAnalysisTools.u_fb 1
Units.
Definition at line 17 of file EICAnalysisTools.py.
View newest version in sPHENIX GitHub at line 17 of file EICAnalysisTools.py
int EICAnalysisTools.u_mb 1
Definition at line 18 of file EICAnalysisTools.py.
View newest version in sPHENIX GitHub at line 18 of file EICAnalysisTools.py
int EICAnalysisTools.u_pb 1
Definition at line 19 of file EICAnalysisTools.py.
View newest version in sPHENIX GitHub at line 19 of file EICAnalysisTools.py