EIC Software: FW::CsvPlanarClusterWriter Exception Reference
FW::CsvPlanarClusterWriter Exception Reference final
#include <fun4all_acts/blob/master/Examples/Io/Csv/include/ACTFW/Io/Csv/CsvPlanarClusterWriter.hpp>
Classes
struct Config
Public Member Functions
CsvPlanarClusterWriter (const Config &cfg, Acts::Logging::Level lvl)
Public Member Functions inherited from FW::WriterT< GeometryIdMultimap< Acts::PlanarModuleCluster > >
WriterT (std::string objectName, std::string writerName, Acts::Logging::Level level)
std::string name () const finaloverride
Provide the name of the writer.
ProcessCode write (const AlgorithmContext &context) finaloverride
Read the object and call the type-specific member function.
ProcessCode endRun () override
No-op default implementation.
Public Member Functions inherited from FW::IWriter
virtual ~IWriter ()=default
Protected Member Functions
ProcessCode writeT (const AlgorithmContext &ctx, const GeometryIdMultimap< Acts::PlanarModuleCluster > &clusters) finaloverride
Protected Member Functions inherited from FW::WriterT< GeometryIdMultimap< Acts::PlanarModuleCluster > >
const Acts::Logger & logger () const
Private Attributes
Config m_cfg
Detailed Description
Write out a planar cluster collection in comma-separated-value format.
This writes multiples file per event containing information about the space points, local constituent cells, and hit-particle truth mapping into the configured output directory. By default it writes to the current working directory. Files are named using the following schema
event000000001-cells.csv
event000000001-hits.csv
event000000001-truth.csv
event000000002-cells.csv
event000000002-hits.csv
event000000002-truth.csv
...
and each line in the file corresponds to one hit/cluster.
Definition at line 36 of file CsvPlanarClusterWriter.hpp.
View newest version in sPHENIX GitHub at line 36 of file CsvPlanarClusterWriter.hpp
Constructor & Destructor Documentation
FW::CsvPlanarClusterWriter::CsvPlanarClusterWriter (const Config & cfg, Acts::Logging::Level lvl)
Construct the cluster writer.
cfg is the configuration object lvl is the logging level
Definition at line 24 of file CsvPlanarClusterWriter.cpp.
View newest version in sPHENIX GitHub at line 24 of file CsvPlanarClusterWriter.cpp
References FW::CsvPlanarClusterWriter::Config::inputSimulatedHits, and m_cfg.
Member Function Documentation
FW::ProcessCode FW::CsvPlanarClusterWriter::writeT (const AlgorithmContext & ctx, const GeometryIdMultimap< Acts::PlanarModuleCluster > & clusters) final override protected virtual
Type-specific write implementation.
Parameters
[in] ctx is the algorithm context
[in] particles are the particle to be written
Implements FW::WriterT< GeometryIdMultimap< Acts::PlanarModuleCluster > >.
Definition at line 33 of file CsvPlanarClusterWriter.cpp.
View newest version in sPHENIX GitHub at line 33 of file CsvPlanarClusterWriter.cpp
References ACTS_FATAL, dfe::io_dsv_impl::NamedTupleDsvWriter< Delimiter, NamedTuple >::append(), c, FW::CellData::ch0, FW::CellData::ch1, FW::TruthHitData::deltae, FW::TruthHitData::deltapx, FW::TruthHitData::deltapy, FW::TruthHitData::deltapz, Acts::PlanarModuleCluster::digitizationCells(), FW::AlgorithmContext::eventNumber, FW::AlgorithmContext::eventStore, FW::AlgorithmContext::geoContext, FW::TruthHitData::geometry_id, FW::HitData::geometry_id, FW::WhiteBoard::get(), Acts::UnitConstants::GeV, FW::TruthHitData::hit_id, FW::HitData::hit_id, FW::CellData::hit_id, incremental_prev_tag::idx, FW::TruthHitData::index, it, Acts::GeometryID::layer(), FW::HitData::layer_id, Acts::Surface::localToGlobal(), Acts::UnitConstants::mm, FW::HitData::module_id, Acts::UnitConstants::ns, Dataset::parameters, Acts::Measurement< source_link_t, params >::parameters(), FW::TruthHitData::particle_id, FW::perEventFilepath(), Acts::Measurement< source_link_t, params >::referenceSurface(), Acts::GeometryID::sensitive(), Acts::Measurement< source_link_t, params >::sourceLink(), SUCCESS, FW::HitData::t, FW::TruthHitData::te, FW::CellData::timestamp, FW::TruthHitData::tpx, FW::TruthHitData::tpy, FW::TruthHitData::tpz, FW::TruthHitData::tt, FW::TruthHitData::tx, FW::TruthHitData::ty, FW::TruthHitData::tz, Acts::GeometryID::value(), FW::CellData::value, Acts::GeometryID::volume(), FW::HitData::volume_id, FW::HitData::x, FW::HitData::y, and FW::HitData::z.
Member Data Documentation
Config FW::CsvPlanarClusterWriter::m_cfg private
Definition at line 66 of file CsvPlanarClusterWriter.hpp.
View newest version in sPHENIX GitHub at line 66 of file CsvPlanarClusterWriter.hpp
Referenced by CsvPlanarClusterWriter().
The documentation for this exception was generated from the following files:
fun4all_acts/blob/master/Examples/Io/Csv/include/ACTFW/Io/Csv/CsvPlanarClusterWriter.hpp
fun4all_acts/blob/master/Examples/Io/Csv/src/CsvPlanarClusterWriter.cpp