EIC Software: make_release Namespace Reference
make_release Namespace Reference
Classes
class Zenodo
Functions
def split_version
def format_version
def gitlab_instance
def gitlab_option
def get_milestones
def find_milestone
def get_branches
def current_branch
def main
def minor
def patch
def message
def relnotes
def zenodo
Variables
tuple version_ex re.compile(r"^v?(\d+)\.(\d{1,2})\.(\d{1,2})$")
Function Documentation
def make_release.current_branch ()
Definition at line 86 of file make_release.py.
View newest version in sPHENIX GitHub at line 86 of file make_release.py
References print().
Referenced by minor(), and patch().
def make_release.find_milestone (version, milestones)
Definition at line 65 of file make_release.py.
View newest version in sPHENIX GitHub at line 65 of file make_release.py
Referenced by message(), minor(), patch(), and zenodo().
def make_release.format_version (version)
Definition at line 37 of file make_release.py.
View newest version in sPHENIX GitHub at line 37 of file make_release.py
Referenced by message(), minor(), patch(), and zenodo().
def make_release.get_branches ()
Definition at line 79 of file make_release.py.
View newest version in sPHENIX GitHub at line 79 of file make_release.py
Referenced by minor(), and patch().
def make_release.get_milestones (project, kwargs)
Definition at line 54 of file make_release.py.
View newest version in sPHENIX GitHub at line 54 of file make_release.py
References split_version().
Referenced by relnotes().
def make_release.gitlab_instance (ctx, param, token)
Definition at line 41 of file make_release.py.
View newest version in sPHENIX GitHub at line 41 of file make_release.py
def make_release.gitlab_option (f)
Definition at line 47 of file make_release.py.
View newest version in sPHENIX GitHub at line 47 of file make_release.py
def make_release.main (void)
Definition at line 93 of file make_release.py.
View newest version in sPHENIX GitHub at line 93 of file make_release.py
Referenced by zenodo().
def make_release.message (version, gitlab)
Definition at line 247 of file make_release.py.
View newest version in sPHENIX GitHub at line 247 of file make_release.py
References find_milestone(), format_version(), print(), util.Spinner(), and split_version().
Referenced by ConditionChecker(), PHG4FullProjTiltedSpacalDetector.Construct_Tower(), PHG4FullProjSpacalDetector.Construct_Tower(), erhic::Forester.OpenInput(), G4TBMagneticFieldSetup.SetStepper(), erhic::Forester.SetupOutput(), and PHG4GDMLWrite.Write().
def make_release.minor (version, dry_run, gitlab)
Definition at line 101 of file make_release.py.
View newest version in sPHENIX GitHub at line 101 of file make_release.py
References current_branch(), find_milestone(), format_version(), get_branches(), print(), util.Spinner(), and split_version().
def make_release.patch (version, dry_run, gitlab)
Definition at line 182 of file make_release.py.
View newest version in sPHENIX GitHub at line 182 of file make_release.py
References current_branch(), find_milestone(), format_version(), get_branches(), print(), util.Spinner(), and split_version().
def make_release.relnotes (start, end, gitlab)
Definition at line 339 of file make_release.py.
View newest version in sPHENIX GitHub at line 339 of file make_release.py
References release_notes.collect_milestone(), get_milestones(), charm_jet_coverage.list, release_notes.make_release_notes(), print(), util.Spinner(), and split_version().
def make_release.split_version (version)
Definition at line 31 of file make_release.py.
View newest version in sPHENIX GitHub at line 31 of file make_release.py
Referenced by get_milestones(), message(), minor(), patch(), relnotes(), and zenodo().
def make_release.zenodo (version, gitlab, zenodo_token, deposition)
Definition at line 431 of file make_release.py.
View newest version in sPHENIX GitHub at line 431 of file make_release.py
References release_notes.collect_milestone(), find_milestone(), format_version(), main(), Acts.open, print(), util.Spinner(), and split_version().
Variable Documentation
tuple make_release.version_ex re.compile(r"^v?(\d+)\.(\d{1,2})\.(\d{1,2})$")
Definition at line 28 of file make_release.py.
View newest version in sPHENIX GitHub at line 28 of file make_release.py