EIC Software: EicStlFacetEdge Class Reference
EicStlFacetEdge Class Reference
A pair of 3D vertices defining one of the three facet edges in STL input file.
#include <EicRoot/blob/master/eic/cad/EicStlFacetEdge.h>
Public Member Functions
EicStlFacetEdge (EicStlVertex *const v1, EicStlVertex *const v2)
~EicStlFacetEdge ()
const EicStlKey * key () const
void AddFacet (EicStlFacet *facet)
const std::vector< EicStlFacet * > & facets (void) const
const vEntry * vertices (void) const
Private Attributes
EicStlKey * mKey
vEntry * mVertices
std::vector< EicStlFacet * > mFacets
Detailed Description
A pair of 3D vertices defining one of the three facet edges in STL input file.
Note
Triangular STL facet is oriented, so vertex order matters!
Definition at line 18 of file EicStlFacetEdge.h.
View newest version in sPHENIX GitHub at line 18 of file EicStlFacetEdge.h
Constructor & Destructor Documentation
EicStlFacetEdge::EicStlFacetEdge (EicStlVertex *const v1, EicStlVertex *const v2)
Main constructor
Parameters
v1 "from" vertex
v2 "to" vertex (but order is irrelevant)
Definition at line 11 of file EicStlFacetEdge.cxx.
View newest version in sPHENIX GitHub at line 11 of file EicStlFacetEdge.cxx
References EicStlKeyCompare(), GetVertexArrayKey(), EicStlVertex::key(), mKey, mVertices, v1, and v2.
EicStlFacetEdge::~EicStlFacetEdge () inline
Destructor; just need to clean up the keys;
Definition at line 27 of file EicStlFacetEdge.h.
View newest version in sPHENIX GitHub at line 27 of file EicStlFacetEdge.h
References mKey, and mVertices.
Member Function Documentation
void EicStlFacetEdge::AddFacet (EicStlFacet * facet) inline
Definition at line 40 of file EicStlFacetEdge.h.
View newest version in sPHENIX GitHub at line 40 of file EicStlFacetEdge.h
References mFacets.
Referenced by EicStlMediaGroup::AllocateEdges().
const std::vector<EicStlFacet*>& EicStlFacetEdge::facets (void) const inline
Definition at line 41 of file EicStlFacetEdge.h.
View newest version in sPHENIX GitHub at line 41 of file EicStlFacetEdge.h
References mFacets.
Referenced by EicStlMediaGroup::AllocateEdges(), and EicStlMediaGroup::CoupleFacetToAssembly().
const EicStlKey* EicStlFacetEdge::key () const inline
Access method; returns unique read-only STL key for this edge
Definition at line 39 of file EicStlFacetEdge.h.
View newest version in sPHENIX GitHub at line 39 of file EicStlFacetEdge.h
References mKey.
Referenced by EicStlMediaGroup::AllocateEdges(), and EicCompositeShape::LocalFillBuffer3D().
const vEntry* EicStlFacetEdge::vertices (void) const inline
Definition at line 42 of file EicStlFacetEdge.h.
View newest version in sPHENIX GitHub at line 42 of file EicStlFacetEdge.h
References mVertices.
Referenced by EicStlMediaGroup::AllocateEdges(), EicStlMediaGroup::CoupleFacetToAssembly(), and EicCompositeShape::LocalFillBuffer3D().
Member Data Documentation
std::vector<EicStlFacet*> EicStlFacetEdge::mFacets private
Array of facets to which this edge belongs
Definition at line 52 of file EicStlFacetEdge.h.
View newest version in sPHENIX GitHub at line 52 of file EicStlFacetEdge.h
Referenced by AddFacet(), and facets().
EicStlKey* EicStlFacetEdge::mKey private
Edge unique 2*3*4-byte STL key
Definition at line 42 of file EicStlFacetEdge.h.
View newest version in sPHENIX GitHub at line 42 of file EicStlFacetEdge.h
Referenced by EicStlFacetEdge(), key(), and ~EicStlFacetEdge().
vEntry* EicStlFacetEdge::mVertices private
Definition at line 49 of file EicStlFacetEdge.h.
View newest version in sPHENIX GitHub at line 49 of file EicStlFacetEdge.h
Referenced by EicStlFacetEdge(), vertices(), and ~EicStlFacetEdge().
The documentation for this class was generated from the following files:
EicRoot/blob/master/eic/cad/EicStlFacetEdge.h
EicRoot/blob/master/eic/cad/EicStlFacetEdge.cxx