EIC Software: Smear::EventDisFactory Class Reference
Smear::EventDisFactory Class Reference
#include <eic-smear/blob/master/include/eicsmear/smear/EventDisFactory.h>
Public Member Functions
virtual ~EventDisFactory ()
EventDisFactory (const Detector &, TBranch &)
virtual Event * Create ()
erhic::VirtualEvent * GetEvBufferPtr ()
Public Member Functions inherited from Smear::EventFactory< Smear::Event >
virtual ~EventFactory ()
virtual std::string EventName () const
virtual TBranch * Branch (TTree &tree, const std::string &name)
virtual void Fill (TBranch &branch)
Public Member Functions inherited from erhic::VirtualEventFactory
virtual ~VirtualEventFactory ()
virtual void FindFirstEvent ()
Protected Attributes
Detector mDetector
erhic::EventDis * mMcEvent
Additional Inherited Members
Public Types inherited from Smear::EventFactory< Smear::Event >
typedef Smear::Event EventType
Public Attributes inherited from erhic::VirtualEventFactory
std::vector< NamedObjects > mObjectsToWriteAtTheEnd
std::map< std::string,
std::string > mAdditionalInformation
Detailed Description
Factory class for smeared DIS events.
Definition at line 30 of file EventDisFactory.h.
View newest version in sPHENIX GitHub at line 30 of file EventDisFactory.h
Constructor & Destructor Documentation
Smear::EventDisFactory::~EventDisFactory () virtual
Destructor.
Definition at line 34 of file EventDisFactory.cxx.
View newest version in sPHENIX GitHub at line 34 of file EventDisFactory.cxx
Smear::EventDisFactory::EventDisFactory (const Detector & d, TBranch & mcBranch)
Constructor. Initialise with the Detector performing particle smearing and the tree branch providing DIS Monte Carlo events.
Definition at line 37 of file EventDisFactory.cxx.
View newest version in sPHENIX GitHub at line 37 of file EventDisFactory.cxx
References mMcEvent.
Member Function Documentation
Event * Smear::EventDisFactory::Create () virtual
Create a smeared event corresponding to the current DIS Monte Carlo event in the input branch passed to the constructor. The user should call TTree::GetEntry() on the tree with the input branch between calls to Create().
Implements Smear::EventFactory< Smear::Event >.
Definition at line 43 of file EventDisFactory.cxx.
View newest version in sPHENIX GitHub at line 43 of file EventDisFactory.cxx
References erhic::EventDis::BeamHadron(), erhic::EventDis::BeamLepton(), Smear::Detector::FillEventKinematics(), erhic::VirtualEvent::GetNTracks(), erhic::VirtualParticle::GetStatus(), erhic::VirtualEvent::GetTrack(), mDetector, mMcEvent, erhic::EventDis::ScatteredLepton(), Smear::ParticleMCS::SetStatus(), and Smear::Detector::Smear().
erhic::VirtualEvent * Smear::EventDisFactory::GetEvBufferPtr () inline virtual
Returns a pointer to the event buffer.
Reimplemented from erhic::VirtualEventFactory.
Definition at line 59 of file EventDisFactory.h.
View newest version in sPHENIX GitHub at line 59 of file EventDisFactory.h
References mMcEvent.
Member Data Documentation
Detector Smear::EventDisFactory::mDetector protected
Definition at line 55 of file EventDisFactory.h.
View newest version in sPHENIX GitHub at line 55 of file EventDisFactory.h
Referenced by Create().
erhic::EventDis* Smear::EventDisFactory::mMcEvent protected
Definition at line 56 of file EventDisFactory.h.
View newest version in sPHENIX GitHub at line 56 of file EventDisFactory.h
Referenced by Create(), EventDisFactory(), and GetEvBufferPtr().
The documentation for this class was generated from the following files:
eic-smear/blob/master/include/eicsmear/smear/EventDisFactory.h
eic-smear/blob/master/src/smear/EventDisFactory.cxx