EIC Software: CbmRichGeoTestStudyReport Class Reference
CbmRichGeoTestStudyReport Class Reference
Creates study report for RICH geometry testing.
#include <EicRoot/blob/master/rich/qa/CbmRichGeoTestStudyReport.h>
Public Member Functions
CbmRichGeoTestStudyReport ()
Constructor.
virtual ~CbmRichGeoTestStudyReport ()
Destructor.
Public Member Functions inherited from CbmStudyReport
CbmStudyReport ()
Constructor.
virtual ~CbmStudyReport ()
Destructor.
void Create (const vector< CbmHistManager * > &histManagers, const vector< string > &studyNames, const string &outputDir)
Main function which creates report data.
void Create (const vector< string > &fileNames, const vector< string > &studyNames, const string &outputDir)
Main function which creates report data.
const vector< CbmHistManager * > & HM () const
CbmHistManager * HM (Int_t index) const
const vector< string > & GetStudyNames () const
const string & GetStudyName (Int_t index) const
Public Member Functions inherited from CbmReport
CbmReport ()
Constructor.
virtual ~CbmReport ()
Destructor.
const CbmReportElement * R () const
Accessor to CbmReportElement object. User has to write the report using available tags from CbmReportElement class.
ostream & Out () const
All text output goes to this stream.
void SetReportName (const string &name)
void SetReportTitle (const string &title)
void SetOutputDir (const string &outputDir)
const string & GetReportName () const
const string & GetReportTitle () const
const string & GetOutputDir () const
Protected Member Functions
void Create ()
Inherited from CbmLitStudyReport.
void Draw ()
Inherited from CbmLitStudyReport.
virtual string PrintRow (const string &property, const string &name)
Print one row in a table.
virtual string PrintValue (int studyId, const string &valueTitle)
Detailed Description
Creates study report for RICH geometry testing.
Generates report from a number of results of different simulations and reconstructions. Creates comparison tables. Very useful for studies since all numbers are automatically put in the comparison tables.
Author
Semen Lebedev s.leb.nosp@m.edev.nosp@m.@gsi..nosp@m.de
Date
2012
Definition at line 28 of file CbmRichGeoTestStudyReport.h.
View newest version in sPHENIX GitHub at line 28 of file CbmRichGeoTestStudyReport.h
Constructor & Destructor Documentation
CbmRichGeoTestStudyReport::CbmRichGeoTestStudyReport ()
Constructor.
Definition at line 17 of file CbmRichGeoTestStudyReport.cxx.
View newest version in sPHENIX GitHub at line 17 of file CbmRichGeoTestStudyReport.cxx
References CbmReport::SetReportName().
CbmRichGeoTestStudyReport::~CbmRichGeoTestStudyReport () virtual
Destructor.
Definition at line 22 of file CbmRichGeoTestStudyReport.cxx.
View newest version in sPHENIX GitHub at line 22 of file CbmRichGeoTestStudyReport.cxx
Member Function Documentation
void CbmRichGeoTestStudyReport::Create () protected virtual
Inherited from CbmLitStudyReport.
Implements CbmReport.
Definition at line 26 of file CbmRichGeoTestStudyReport.cxx.
View newest version in sPHENIX GitHub at line 26 of file CbmRichGeoTestStudyReport.cxx
References CbmReportElement::DocumentBegin(), CbmReportElement::DocumentEnd(), CbmStudyReport::GetStudyNames(), CbmReport::Out(), PrintRow(), CbmReport::R(), CbmReportElement::TableBegin(), CbmReportElement::TableEnd(), and CbmReportElement::Title().
void CbmRichGeoTestStudyReport::Draw () inline protected virtual
Inherited from CbmLitStudyReport.
Implements CbmReport.
Definition at line 50 of file CbmRichGeoTestStudyReport.h.
View newest version in sPHENIX GitHub at line 50 of file CbmRichGeoTestStudyReport.h
string CbmRichGeoTestStudyReport::PrintRow (const string & property, const string & name) protected virtual
Print one row in a table.
Parameters
[in] property Name of the property in property tree.
[in] name Name of the row.
Returns
String with table row.
Definition at line 90 of file CbmRichGeoTestStudyReport.cxx.
View newest version in sPHENIX GitHub at line 90 of file CbmRichGeoTestStudyReport.cxx
References CbmStudyReport::GetStudyNames(), n, PrintValue(), CbmReport::R(), and CbmReportElement::TableRow().
Referenced by Create().
string CbmRichGeoTestStudyReport::PrintValue (int studyId, const string & valueTitle) protected virtual
Definition at line 101 of file CbmRichGeoTestStudyReport.cxx.
View newest version in sPHENIX GitHub at line 101 of file CbmRichGeoTestStudyReport.cxx
Referenced by PrintRow().
The documentation for this class was generated from the following files:
EicRoot/blob/master/rich/qa/CbmRichGeoTestStudyReport.h
EicRoot/blob/master/rich/qa/CbmRichGeoTestStudyReport.cxx