EIC Software: FairTask Class Reference
FairTask Class Reference
#include <EicRoot/blob/master/base/FairTask.h>
Public Member Functions
FairTask ()
FairTask (const char *name, Int_t iVerbose=1)
virtual ~FairTask ()
void InitTask ()
void ReInitTask ()
void SetParTask ()
virtual void FinishTask ()
virtual void FinishEvent ()
void SetVerbose (Int_t iVerbose)
void SetInputPersistance (Bool_t val)
void CheckInputPersistance (TString branchName)
Protected Member Functions
virtual InitStatus Init ()
virtual InitStatus ReInit ()
virtual void SetParContainers ()
virtual void Finish ()
void InitTasks ()
void ReInitTasks ()
void SetParTasks ()
void FinishTasks ()
void FinishEvents ()
Protected Attributes
Int_t fVerbose
Int_t fInputPersistance
Indicates if input branch is persistant.
FairLogger * fLogger
Private Member Functions
FairTask (const FairTask &)
FairTask & operator= (const FairTask &)
ClassDef (FairTask, 2)
Detailed Description
Definition at line 25 of file FairTask.h.
View newest version in sPHENIX GitHub at line 25 of file FairTask.h
Constructor & Destructor Documentation
FairTask::FairTask ()
Default constructor
Definition at line 14 of file FairTask.cxx.
View newest version in sPHENIX GitHub at line 14 of file FairTask.cxx
Referenced by EicDigiHitProducer::EicDigiHitProducer().
FairTask::FairTask (const char * name, Int_t iVerbose = 1)
Standard constructor
Parameters
name Name of task
iVerbose Verbosity level
Definition at line 26 of file FairTask.cxx.
View newest version in sPHENIX GitHub at line 26 of file FairTask.cxx
FairTask::~FairTask () virtual
Destructor
Definition at line 39 of file FairTask.cxx.
View newest version in sPHENIX GitHub at line 39 of file FairTask.cxx
FairTask::FairTask (const FairTask &) private
Member Function Documentation
void FairTask::CheckInputPersistance (TString branchName) inline
Definition at line 69 of file FairTask.h.
View newest version in sPHENIX GitHub at line 69 of file FairTask.h
References FairRootManager::CheckBranch(), fInputPersistance, and FairRootManager::Instance().
FairTask::ClassDef (FairTask , 2) private
virtual void FairTask::Finish () inline protected virtual
Action after each event. To be implemented in the derived class
Reimplemented in EicTrackingDigiHitProducer, PndPidCorrelator, EicCalorimeterDigiHitProducer, EicCalorimeterReconstruction, EicIdealTrackingCode, FairBoxSetDraw, CbmRichGeoTest, CbmRichReconstruction, CbmRichMatchRings, CbmRichTestSim, CbmRichUrqmdTest, CbmRichTestHits, FairPointSetDraw, CbmRichHitProducer, CbmRichEventDisplay, FairMCStack, FairMCTracks, CbmMCMatchSelectorTask, CbmMCMatchLoaderTask, CbmMCMatchCreatorTask, and FwdIdealTrackingCode.
Definition at line 100 of file FairTask.h.
View newest version in sPHENIX GitHub at line 100 of file FairTask.h
Referenced by FinishTask(), and FinishTasks().
void FairTask::FinishEvent () virtual
Action at end of event. For this task and all of the subtasks.
Reimplemented in EicFluxMonitorTask, FairRingSorterTask, and PndTrackArrayMerger.
Definition at line 84 of file FairTask.cxx.
View newest version in sPHENIX GitHub at line 84 of file FairTask.cxx
References FinishEvents().
Referenced by FairMCApplication::FinishEvent(), EicFluxMonitorTask::FinishEvent(), FinishEvents(), FairRunAna::Run(), EicRunAna::RunCoreProcessNextEvent(), FairRunAna::RunMixed(), FairRunAna::RunOneEvent(), and FairRunAna::RunTSBuffers().
void FairTask::FinishEvents () protected
Recursive FinishEvent of subtasks
Definition at line 159 of file FairTask.cxx.
View newest version in sPHENIX GitHub at line 159 of file FairTask.cxx
References FinishEvent().
Referenced by PndTrackArrayMerger::FinishEvent(), and FinishEvent().
void FairTask::FinishTask () virtual
Action at end of run. For this task and all of the subtasks.
Reimplemented in EicEventGeneratorTask, EicFluxMonitorTask, EicHtcTask, FwdTrackFinder, FairRingSorterTask, CbmRichTrainAnnElectrons, CbmRichTrainAnnSelect, EicEventAssembler, PrimSelector, and EicSmearTask.
Definition at line 92 of file FairTask.cxx.
View newest version in sPHENIX GitHub at line 92 of file FairTask.cxx
References Finish(), and FinishTasks().
Referenced by FairRunAna::DummyRun(), FairMCApplication::FinishRun(), EicSmearTask::FinishTask(), EicEventAssembler::FinishTask(), FwdTrackFinder::FinishTask(), EicHtcTask::FinishTask(), EicFluxMonitorTask::FinishTask(), EicEventGeneratorTask::FinishTask(), FinishTasks(), FairRunAna::Run(), EicRunAna::RunCoreFinish(), FairRunAna::RunMixed(), FairRunAna::RunOnLmdFiles(), FairRunAna::RunTSBuffers(), and FairRunAna::TerminateRun().
void FairTask::FinishTasks () protected
Recursive finish of subtasks
Definition at line 149 of file FairTask.cxx.
View newest version in sPHENIX GitHub at line 149 of file FairTask.cxx
References Finish(), and FinishTask().
Referenced by FinishTask().
virtual InitStatus FairTask::Init () inline protected virtual
Intialisation at begin of run. To be implemented in the derived class. Success If not kSUCCESS, task will be set inactive.
Reimplemented in EicHtcTask, PndPidCorrelator, PndGeoHandling, FwdTrackFinder, EicIdealTrackingCode, EicCalorimeterReconstruction, FairRingSorterTask, FairBoxSetDraw, CbmRichTrainAnnElectrons, CbmRichTrainAnnSelect, CbmDigiManager, PndRecoKalmanTask, EicEventAssembler, CbmRichGeoTest, FairPointSetDraw, EicDigiHitProducer, PndRecoMultiKalmanTask, CbmRichReconstruction, FairMCStack, CbmRichMatchRings, CbmRichTestSim, CbmRichUrqmdTest, FairMCTracks, CbmRichTestHits, PrimSelector, CbmRichHitProducer, CbmRichEventDisplay, CbmMCMatchSelectorTask, CbmMCMatchLoaderTask, CbmMCMatchCreatorTask, PndGFTrackToPndTrackConvertorTask, EicSmearTask, FairGeane, EicRecoKalmanTask, PndMcCloner, PndTrackArrayMerger, PndEventCounterTask, and PndBlackBoxTask.
Definition at line 84 of file FairTask.h.
View newest version in sPHENIX GitHub at line 84 of file FairTask.h
References kSUCCESS.
Referenced by FairAnaSelector::Init(), EicHtcTask::Init(), and InitTask().
void FairTask::InitTask ()
Initialisation at begin of run. For this task and all of the subtasks.
Definition at line 45 of file FairTask.cxx.
View newest version in sPHENIX GitHub at line 45 of file FairTask.cxx
References FairLogger::Fatal(), fLogger, Init(), InitTasks(), kERROR, kFATAL, and MESSAGE_ORIGIN.
Referenced by FairRunAna::Init(), InitTasks(), and FairMCApplication::InitTasks().
void FairTask::InitTasks () protected
Action after each event. To be implemented in the derived class Recursive intialisation of subtasks at begin of run
Definition at line 116 of file FairTask.cxx.
View newest version in sPHENIX GitHub at line 116 of file FairTask.cxx
References InitTask().
Referenced by InitTask().
FairTask& FairTask::operator= (const FairTask &) private
virtual InitStatus FairTask::ReInit () inline protected virtual
Reinitialisation. To be implemented in the derived class. Success If not kSUCCESS, task will be set inactive.
Reimplemented in PndGeoHandling, FairRingSorterTask, PndTrackArrayMerger, PndEventCounterTask, and PndBlackBoxTask.
Definition at line 90 of file FairTask.h.
View newest version in sPHENIX GitHub at line 90 of file FairTask.h
References kSUCCESS.
Referenced by ReInitTask().
void FairTask::ReInitTask ()
Reinitialisation. For this task and all of the subtasks.
Definition at line 60 of file FairTask.cxx.
View newest version in sPHENIX GitHub at line 60 of file FairTask.cxx
References FairLogger::Fatal(), fLogger, kERROR, kFATAL, MESSAGE_ORIGIN, ReInit(), and ReInitTasks().
Referenced by FairRunAna::InitContainers(), ReInitTasks(), FairRunAna::Run(), EicRunAna::RunCoreProcessNextEvent(), and FairRunAna::RunOneEvent().
void FairTask::ReInitTasks () protected
Recursive reinitialisation of subtasks
Definition at line 127 of file FairTask.cxx.
View newest version in sPHENIX GitHub at line 127 of file FairTask.cxx
References ReInitTask().
Referenced by ReInitTask().
void FairTask::SetInputPersistance (Bool_t val) inline
Definition at line 67 of file FairTask.h.
View newest version in sPHENIX GitHub at line 67 of file FairTask.h
References fInputPersistance.
virtual void FairTask::SetParContainers () inline protected virtual
Intialise parameter containers. To be implemented in the derived class.
Reimplemented in PndPidCorrelator, EicDigiHitProducer, FairRingSorterTask, FairBoxSetDraw, PndGeoHandling, PndRecoKalmanTask, PndRecoMultiKalmanTask, FairPointSetDraw, CbmRichGeoTest, FairMCStack, FairMCTracks, CbmRichReconstruction, CbmRichTestSim, CbmRichTestHits, CbmMCMatchSelectorTask, CbmRichHitProducer, CbmMCMatchLoaderTask, CbmMCMatchCreatorTask, EicSmearTask, PndTrackArrayMerger, PndEventCounterTask, and PndBlackBoxTask.
Definition at line 96 of file FairTask.h.
View newest version in sPHENIX GitHub at line 96 of file FairTask.h
Referenced by PndGeoHandling::SetParContainers(), and SetParTask().
void FairTask::SetParTask ()
Set parameters. For this task and all of the subtasks.
Definition at line 75 of file FairTask.cxx.
View newest version in sPHENIX GitHub at line 75 of file FairTask.cxx
References SetParContainers(), and SetParTasks().
Referenced by FairRunAna::Init(), FairMCApplication::SetParTask(), and SetParTasks().
void FairTask::SetParTasks () protected
Recursive parameter initialisation for subtasks
Definition at line 138 of file FairTask.cxx.
View newest version in sPHENIX GitHub at line 138 of file FairTask.cxx
References SetParTask().
Referenced by SetParTask().
void FairTask::SetVerbose (Int_t iVerbose)
Set verbosity level. For this task and all of the subtasks.
Definition at line 103 of file FairTask.cxx.
View newest version in sPHENIX GitHub at line 103 of file FairTask.cxx
References fVerbose, and SetVerbose().
Referenced by FairRingSorterTask::FairRingSorterTask(), and SetVerbose().
Member Data Documentation
Int_t FairTask::fInputPersistance protected
Indicates if input branch is persistant.
Definition at line 78 of file FairTask.h.
View newest version in sPHENIX GitHub at line 78 of file FairTask.h
Referenced by CheckInputPersistance(), and SetInputPersistance().
FairLogger* FairTask::fLogger protected
Definition at line 79 of file FairTask.h.
View newest version in sPHENIX GitHub at line 79 of file FairTask.h
Referenced by EicTrackingDigiHitProducer::AssignDigiHitClassName(), EicHtcTask::Exec(), InitTask(), and ReInitTask().
Int_t FairTask::fVerbose protected
Definition at line 77 of file FairTask.h.
View newest version in sPHENIX GitHub at line 77 of file FairTask.h
Referenced by EicIdealTrackingCode::EicIdealTrackingCode(), PndEventCounterTask::Exec(), PndGFTrackToPndTrackConvertorTask::Exec(), CbmMCMatchCreatorTask::Exec(), FairMCTracks::Exec(), PrimSelector::Exec(), FairMCStack::Exec(), CbmRichHitProducer::Exec(), CbmRichTestHits::Exec(), PndRecoMultiKalmanTask::Exec(), CbmRichTestSim::Exec(), PndRecoKalmanTask::Exec(), EicDigiHitProducer::Exec(), FairRingSorterTask::Exec(), EicIdealTrackingCode::Exec(), CbmRichHitProducer::FindRichHitPositionMAPMT(), FairRingSorterTask::FinishTask(), PndPidCorrelator::GetTrackInfo(), CbmRichHitProducer::Init(), FairMCTracks::Init(), FairMCStack::Init(), PndRecoKalmanTask::Init(), FairRingSorterTask::Init(), EicIdealTrackingCode::Init(), EicIdealTrackingCode::Register(), CbmRichHitProducer::SetPhotoDetPar(), PndBlackBoxTask::SetVerbose(), PndEventCounterTask::SetVerbose(), FairMCTracks::SetVerbose(), and SetVerbose().
The documentation for this class was generated from the following files:
EicRoot/blob/master/base/FairTask.h
EicRoot/blob/master/base/FairTask.cxx