EIC Software: fun4all_macros/blob/master/common/G4_Tracking.C File Reference
G4_Tracking.C File Reference
#include <GlobalVariables.C>
#include <QA.C>
#include <G4_Intt.C>
#include <G4_Micromegas.C>
#include <G4_Mvtx.C>
#include <G4_TPC.C>
#include <fun4all/Fun4AllServer.h>
#include <g4eval/SvtxEvaluator.h>
#include <trackreco/PHCASeeding.h>
#include <trackreco/PHHybridSeeding.h>
#include <trackreco/PHGenFitTrackProjection.h>
#include <trackreco/PHGenFitTrkFitter.h>
#include <trackreco/PHGenFitTrkProp.h>
#include <trackreco/PHHoughSeeding.h>
#include <trackreco/PHInitZVertexing.h>
#include <trackreco/PHMicromegasTpcTrackMatching.h>
#include <trackreco/PHRaveVertexing.h>
#include <trackreco/PHSiliconTpcTrackMatching.h>
#include <trackreco/PHSiliconTruthTrackSeeding.h>
#include <trackreco/PHTpcTrackSeedVertexAssoc.h>
#include <trackreco/PHTrackSeeding.h>
#include <trackreco/PHTruthSiliconAssociation.h>
#include <trackreco/PHTruthTrackSeeding.h>
#include <trackreco/PHTruthVertexing.h>
#include <trackbase/TrkrHitTruthAssoc.h>
#include <phtpctracker/PHTpcTracker.h>
#include <qa_modules/QAG4SimulationTracking.h>
#include <qa_modules/QAG4SimulationUpsilon.h>
#include <qa_modules/QAG4SimulationVertex.h>
Namespaces
namespace Enable
namespace G4TRACKING
Macros
#define MACRO_G4TRACKING_C
Functions
std::string G4TRACKING::vmethod ("avf-smoothing:1")
void TrackingInit ()
void Tracking_Reco ()
void Tracking_Eval (const std::string &outputfile)
void Tracking_QA ()
Variables
bool Enable::TRACKING_TRACK = false
bool Enable::TRACKING_QA = false
bool G4TRACKING::SC_CALIBMODE = true
double G4TRACKING::SC_COLLISIONRATE = 50e3
bool G4TRACKING::g4eval_use_initial_vertex = true
bool G4TRACKING::use_tpc_seed_vertex_assoc = true
bool G4TRACKING::use_PHTpcTracker_seeding = false
bool G4TRACKING::use_hybrid_seeding = false
bool G4TRACKING::use_truth_si_matching = false
bool G4TRACKING::use_truth_track_seeding = false
bool G4TRACKING::use_Genfit = false
bool G4TRACKING::use_acts_silicon_seeding = true
bool G4TRACKING::use_acts_init_vertexing = false
bool G4TRACKING::use_phinit_vertexing = false && !use_acts_init_vertexing
bool G4TRACKING::use_rave_vertexing = true
bool G4TRACKING::use_primary_vertex = false
bool G4TRACKING::use_acts_evaluator = false
int G4TRACKING::init_vertexing_min_zvtx_tracks = 2
Macro Definition Documentation
#define MACRO_G4TRACKING_C
Definition at line 2 of file G4_Tracking.C.
View newest version in sPHENIX GitHub at line 2 of file G4_Tracking.C
Function Documentation
void Tracking_Eval (const std::string & outputfile)
Definition at line 523 of file G4_Tracking.C.
View newest version in sPHENIX GitHub at line 523 of file G4_Tracking.C
References SvtxEvaluator::do_cluster_eval(), SvtxEvaluator::do_eval_light(), SvtxEvaluator::do_g4hit_eval(), SvtxEvaluator::do_gpoint_eval(), SvtxEvaluator::do_hit_eval(), G4TRACKING::g4eval_use_initial_vertex, Fun4AllServer::instance(), max, G4TPC::n_gas_layer, G4INTT::n_intt_layer, G4MVTX::n_maps_layer, G4MICROMEGAS::n_micromegas_layer, Fun4AllServer::registerSubsystem(), G4TRACKING::SC_CALIBMODE, SvtxEvaluator::scan_for_embedded(), SvtxEvaluator::set_use_initial_vertex(), ActsEvaluator::setEvalCKF(), Enable::TRACKING_VERBOSITY, G4TRACKING::use_acts_evaluator, G4TRACKING::use_Genfit, G4TRACKING::use_primary_vertex, Enable::VERBOSITY, and Fun4AllBase::Verbosity().
void Tracking_QA ()
Definition at line 583 of file G4_Tracking.C.
View newest version in sPHENIX GitHub at line 583 of file G4_Tracking.C
References QAG4SimulationUpsilon::addEmbeddingID(), Fun4AllServer::instance(), max, Enable::QA_VERBOSITY, Fun4AllServer::registerSubsystem(), QAG4SimulationVertex::setVertexMapName(), Enable::TRACKING_VERBOSITY, Input::UPSILON, Input::UPSILON_EmbedIds, G4TRACKING::use_Genfit, G4TRACKING::use_rave_vertexing, and Fun4AllBase::Verbosity().
Referenced by Fun4All_AnaTutorial(), Fun4All_AnaTutorial_Jets(), and Fun4All_G4_sPHENIX().
void Tracking_Reco ()
Definition at line 162 of file G4_Tracking.C.
View newest version in sPHENIX GitHub at line 162 of file G4_Tracking.C
References PHActsTrkFitter::doTimeAnalysis(), PHTpcTracker::enable_json_export(), PHTpcTracker::enable_vertexing(), PHActsTrkFitter::fitSiliconMMs(), G4TRACKING::init_vertexing_min_zvtx_tracks, Fun4AllServer::instance(), M_PI, G4MAGNET::magfield, G4MAGNET::magfield_rescale, max, G4TPC::n_gas_layer, G4INTT::n_intt_layer, G4MVTX::n_maps_layer, G4MICROMEGAS::n_micromegas_layer, Fun4AllServer::registerSubsystem(), G4TRACKING::SC_CALIBMODE, G4TRACKING::SC_COLLISIONRATE, PHTruthVertexing::set_acts_silicon(), PHMicromegasTpcTrackMatching::set_collision_rate(), PHSiliconTpcTrackMatching::set_collision_rate(), PHSiliconTpcTrackMatching::set_eta_search_window(), PHSiliconTpcTrackMatching::set_field(), PHSiliconTpcTrackMatching::set_field_dir(), PHHybridSeeding::set_field_dir(), PHGenFitTrkFitter::set_fit_primary_tracks(), PHMicromegasTpcTrackMatching::set_min_tpc_layer(), PHInitZVertexing::set_min_zvtx_tracks(), PHRaveVertexing::set_over_write_svtxvertexmap(), PHSiliconTpcTrackMatching::set_phi_search_window(), PHMicromegasTpcTrackMatching::set_rphi_search_window_lyr1(), PHMicromegasTpcTrackMatching::set_rphi_search_window_lyr2(), PHMicromegasTpcTrackMatching::set_sc_calib_mode(), PHSiliconTpcTrackMatching::set_sc_calib_mode(), PHTpcTracker::set_seed_finder_optimization_remove_loopers(), PHTpcTracker::set_seed_finder_options(), PHSiliconTpcTrackMatching::set_seeder(), PHInitZVertexing::set_seeding_layer(), PHRaveVertexing::set_svtxvertexmaprefit_node_name(), PHMicromegasTpcTrackMatching::set_test_windows_printout(), PHSiliconTpcTrackMatching::set_test_windows_printout(), PHTpcTracker::set_track_follower_optimization_helix(), PHTpcTracker::set_track_follower_optimization_precise_fit(), PHGenFitTrkFitter::set_use_truth_vertex(), PHGenFitTrkFitter::set_vertexing_method(), PHMicromegasTpcTrackMatching::set_z_search_window_lyr1(), PHMicromegasTpcTrackMatching::set_z_search_window_lyr2(), PHActsSourceLinks::setMagField(), MakeActsGeometry::setMagField(), PHActsSourceLinks::setMagFieldRescale(), MakeActsGeometry::setMagFieldRescale(), PHHybridSeeding::setMinTrackSize(), PHHybridSeeding::setNThreads(), PHHybridSeeding::setSearchAngle(), PHHybridSeeding::setSearchRadius(), PHActsTracks::setSecondFit(), tracker(), Enable::TRACKING_VERBOSITY, G4TRACKING::use_acts_init_vertexing, G4TRACKING::use_acts_silicon_seeding, G4TRACKING::use_Genfit, G4TRACKING::use_hybrid_seeding, G4TRACKING::use_phinit_vertexing, G4TRACKING::use_PHTpcTracker_seeding, G4TRACKING::use_primary_vertex, G4TRACKING::use_rave_vertexing, G4TRACKING::use_tpc_seed_vertex_assoc, G4TRACKING::use_truth_si_matching, G4TRACKING::use_truth_track_seeding, Enable::VERBOSITY, Fun4AllBase::Verbosity(), and G4TRACKING::vmethod().
void TrackingInit ()
Definition at line 111 of file G4_Tracking.C.
View newest version in sPHENIX GitHub at line 111 of file G4_Tracking.C
References G4TPC::ENABLE_CORRECTIONS, G4TPC::ENABLE_STATIC_DISTORTIONS, G4TPC::ENABLE_TIME_ORDERED_DISTORTIONS, G4TRACKING::g4eval_use_initial_vertex, Enable::MICROMEGAS, G4MICROMEGAS::n_micromegas_layer, G4TRACKING::SC_CALIBMODE, and G4TRACKING::use_Genfit.