EIC Software: EICPIDParticle Class Reference
EICPIDParticle Class Reference
#include <fun4all_eicdetectors/blob/master/reconstruction/eicpidbase/EICPIDParticle.h>
Public Types
enum PROPERTY_TYPE { type_int = 1, type_uint = 2, type_float = 3, type_unknown = -1 }
enum PROPERTY {
Truth_PID = 0, Truth_momentum, Truth_eta, CTTL_beta = 10,
ETTL_beta, FTTL_beta, prop_MAX_NUMBER = UCHAR_MAX
}
Public Member Functions
EICPIDParticle ()
~EICPIDParticle () override
void identify (std::ostream &os=std::cout) const override
void CopyFrom (const PHObject *phobj) override
void Reset () override
Clear Event.
virtual EICPIDDefs::keytype get_id () const
virtual void set_id (const EICPIDDefs::keytype)
virtual float get_SumLogLikelyhood (EICPIDDefs::PIDCandidate) const
virtual float get_LogLikelyhood (EICPIDDefs::PIDCandidate, EICPIDDefs::PIDDetector) const
virtual void set_LogLikelyhood (EICPIDDefs::PIDCandidate, EICPIDDefs::PIDDetector, float)
virtual bool has_property (const PROPERTY) const
virtual float get_property_float (const PROPERTY) const
virtual int get_property_int (const PROPERTY) const
virtual unsigned int get_property_uint (const PROPERTY) const
virtual void set_property (const PROPERTY, const float)
virtual void set_property (const PROPERTY, const int)
virtual void set_property (const PROPERTY, const unsigned int)
Public Member Functions inherited from PHObject
PHObject ()
ctor
~PHObject () override
dtor
virtual PHObject * CloneMe () const
Virtual copy constructor.
virtual PHObject * clone () const final
PHObject * Clone (const char *newname="") const final
void Copy (TObject &object) const final
virtual int isValid () const
isValid returns non zero if object contains vailid data
virtual int isValid (const float) const
virtual int isValid (const double) const
virtual int isValid (const int) const
virtual int isValid (const unsigned int) const
virtual int isImplemented (const float f) const
virtual int isImplemented (const double f) const
virtual int isImplemented (const int i) const
virtual int isImplemented (const unsigned int i) const
virtual int Integrate () const
virtual int Integrate (PHObject *)
Static Public Member Functions
static std::pair< const
std::string, PROPERTY_TYPE > get_property_info (PROPERTY prop_id)
static bool check_property (const PROPERTY prop_id, const PROPERTY_TYPE prop_type)
static std::string get_property_type (const PROPERTY_TYPE prop_type)
Static Public Attributes
static const std::map
< PROPERTY, std::pair< const
std::string,
EICPIDParticle::PROPERTY_TYPE > > m_propertyInfo
Protected Member Functions
virtual unsigned int get_property_nocheck (const PROPERTY) const
virtual void set_property_nocheck (const PROPERTY, const unsigned int)
Static Protected Attributes
static constexpr float m_minLogLikelihood = -100
Detailed Description
Definition at line 16 of file EICPIDParticle.h.
View newest version in sPHENIX GitHub at line 16 of file EICPIDParticle.h
Member Enumeration Documentation
enum EICPIDParticle::PROPERTY
Procedure to add a new PROPERTY tag: 1.add new tag below with unique value, 2.add a short name to EICPIDParticle::m_propertyInfo
Enumerator:
Truth_PID
Truth_momentum
Truth_eta
CTTL_beta
ETTL_beta
FTTL_beta
prop_MAX_NUMBER
max limit in order to fit into 8 bit unsigned number
Definition at line 44 of file EICPIDParticle.h.
View newest version in sPHENIX GitHub at line 44 of file EICPIDParticle.h
enum EICPIDParticle::PROPERTY_TYPE
Enumerator:
type_int
type_uint
type_float
type_unknown
Definition at line 33 of file EICPIDParticle.h.
View newest version in sPHENIX GitHub at line 33 of file EICPIDParticle.h
Constructor & Destructor Documentation
EICPIDParticle::EICPIDParticle () inline
Definition at line 19 of file EICPIDParticle.h.
View newest version in sPHENIX GitHub at line 19 of file EICPIDParticle.h
EICPIDParticle::~EICPIDParticle () inline override
Definition at line 20 of file EICPIDParticle.h.
View newest version in sPHENIX GitHub at line 20 of file EICPIDParticle.h
Member Function Documentation
bool EICPIDParticle::check_property (const PROPERTY prop_id, const PROPERTY_TYPE prop_type) static
Definition at line 69 of file EICPIDParticle.cc.
View newest version in sPHENIX GitHub at line 69 of file EICPIDParticle.cc
void EICPIDParticle::CopyFrom (const PHObject * phobj) override virtual
Reimplemented from PHObject.
Definition at line 22 of file EICPIDParticle.cc.
View newest version in sPHENIX GitHub at line 22 of file EICPIDParticle.cc
References get_id(), get_property_nocheck(), and has_property().
virtual EICPIDDefs::keytype EICPIDParticle::get_id () const inline virtual
Reimplemented in EICPIDParticlev1.
Definition at line 26 of file EICPIDParticle.h.
View newest version in sPHENIX GitHub at line 26 of file EICPIDParticle.h
References EICPIDDefs::INVALID_KEY.
Referenced by EICPIDParticleContainer::AddPIDParticle(), and CopyFrom().
virtual float EICPIDParticle::get_LogLikelyhood (EICPIDDefs::PIDCandidate , EICPIDDefs::PIDDetector) const inline virtual
Reimplemented in EICPIDParticlev1.
Definition at line 30 of file EICPIDParticle.h.
View newest version in sPHENIX GitHub at line 30 of file EICPIDParticle.h
References m_minLogLikelihood.
virtual float EICPIDParticle::get_property_float (const PROPERTY) const inline virtual
Reimplemented in EICPIDParticlev1.
Definition at line 65 of file EICPIDParticle.h.
View newest version in sPHENIX GitHub at line 65 of file EICPIDParticle.h
std::pair< const std::string, EICPIDParticle::PROPERTY_TYPE > EICPIDParticle::get_property_info (PROPERTY prop_id) static
Definition at line 53 of file EICPIDParticle.cc.
View newest version in sPHENIX GitHub at line 53 of file EICPIDParticle.cc
References exit().
virtual int EICPIDParticle::get_property_int (const PROPERTY) const inline virtual
Reimplemented in EICPIDParticlev1.
Definition at line 66 of file EICPIDParticle.h.
View newest version in sPHENIX GitHub at line 66 of file EICPIDParticle.h
virtual unsigned int EICPIDParticle::get_property_nocheck (const PROPERTY) const inline protected virtual
Reimplemented in EICPIDParticlev1.
Definition at line 78 of file EICPIDParticle.h.
View newest version in sPHENIX GitHub at line 78 of file EICPIDParticle.h
Referenced by CopyFrom().
string EICPIDParticle::get_property_type (const PROPERTY_TYPE prop_type) static
Definition at line 80 of file EICPIDParticle.cc.
View newest version in sPHENIX GitHub at line 80 of file EICPIDParticle.cc
virtual unsigned int EICPIDParticle::get_property_uint (const PROPERTY) const inline virtual
Reimplemented in EICPIDParticlev1.
Definition at line 67 of file EICPIDParticle.h.
View newest version in sPHENIX GitHub at line 67 of file EICPIDParticle.h
virtual float EICPIDParticle::get_SumLogLikelyhood (EICPIDDefs::PIDCandidate) const inline virtual
Reimplemented in EICPIDParticlev1.
Definition at line 29 of file EICPIDParticle.h.
View newest version in sPHENIX GitHub at line 29 of file EICPIDParticle.h
Referenced by EventEvaluatorEIC::fillOutputNtuples().
virtual bool EICPIDParticle::has_property (const PROPERTY) const inline virtual
Reimplemented in EICPIDParticlev1.
Definition at line 64 of file EICPIDParticle.h.
View newest version in sPHENIX GitHub at line 64 of file EICPIDParticle.h
Referenced by CopyFrom().
void EICPIDParticle::identify (std::ostream & os = std::cout) const override virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from PHObject.
Reimplemented in EICPIDParticlev1.
Definition at line 40 of file EICPIDParticle.cc.
View newest version in sPHENIX GitHub at line 40 of file EICPIDParticle.cc
void EICPIDParticle::Reset () override virtual
Clear Event.
Reimplemented from PHObject.
Reimplemented in EICPIDParticlev1.
Definition at line 46 of file EICPIDParticle.cc.
View newest version in sPHENIX GitHub at line 46 of file EICPIDParticle.cc
virtual void EICPIDParticle::set_id (const EICPIDDefs::keytype) inline virtual
Reimplemented in EICPIDParticlev1.
Definition at line 27 of file EICPIDParticle.h.
View newest version in sPHENIX GitHub at line 27 of file EICPIDParticle.h
Referenced by EICPIDParticleContainer::findOrAddPIDParticle().
virtual void EICPIDParticle::set_LogLikelyhood (EICPIDDefs::PIDCandidate , EICPIDDefs::PIDDetector , float) inline virtual
Reimplemented in EICPIDParticlev1.
Definition at line 31 of file EICPIDParticle.h.
View newest version in sPHENIX GitHub at line 31 of file EICPIDParticle.h
virtual void EICPIDParticle::set_property (const PROPERTY , const float) inline virtual
Reimplemented in EICPIDParticlev1.
Definition at line 68 of file EICPIDParticle.h.
View newest version in sPHENIX GitHub at line 68 of file EICPIDParticle.h
virtual void EICPIDParticle::set_property (const PROPERTY , const int) inline virtual
Reimplemented in EICPIDParticlev1.
Definition at line 69 of file EICPIDParticle.h.
View newest version in sPHENIX GitHub at line 69 of file EICPIDParticle.h
virtual void EICPIDParticle::set_property (const PROPERTY , const unsigned int) inline virtual
Reimplemented in EICPIDParticlev1.
Definition at line 70 of file EICPIDParticle.h.
View newest version in sPHENIX GitHub at line 70 of file EICPIDParticle.h
virtual void EICPIDParticle::set_property_nocheck (const PROPERTY , const unsigned int) inline protected virtual
Reimplemented in EICPIDParticlev1.
Definition at line 79 of file EICPIDParticle.h.
View newest version in sPHENIX GitHub at line 79 of file EICPIDParticle.h
Member Data Documentation
constexpr float EICPIDParticle::m_minLogLikelihood = -100 static protected
Definition at line 76 of file EICPIDParticle.h.
View newest version in sPHENIX GitHub at line 76 of file EICPIDParticle.h
Referenced by get_LogLikelyhood().
const std::map< EICPIDParticle::PROPERTY, std::pair< const std::string, EICPIDParticle::PROPERTY_TYPE > > EICPIDParticle::m_propertyInfo static
Initial value:
= {
        {Truth_PID, {"Truth PID", type_int}},
        {Truth_momentum, {"Truth Momentum", type_float}},
        {Truth_eta, {"Truth eta", type_float}},
        {CTTL_beta, {"Beta on CTTL", type_float}},
        {ETTL_beta, {"Beta on ETTL", type_float}},
        {FTTL_beta, {"Beta on FTTL", type_float}}
}
Definition at line 62 of file EICPIDParticle.h.
View newest version in sPHENIX GitHub at line 62 of file EICPIDParticle.h
The documentation for this class was generated from the following files:
fun4all_eicdetectors/blob/master/reconstruction/eicpidbase/EICPIDParticle.h
fun4all_eicdetectors/blob/master/reconstruction/eicpidbase/EICPIDParticle.cc