EIC Software: FairFieldFactory Class Reference
FairFieldFactory Class Reference
#include <EicRoot/blob/master/base/FairFieldFactory.h>
Public Member Functions
FairFieldFactory ()
virtual ~FairFieldFactory ()
virtual FairField * createFairField ()
virtual void SetParm ()
Static Public Member Functions
static FairFieldFactory * Instance ()
Protected Member Functions
ClassDef(FairFieldFactory,
1) private FairFieldFactory & operator= (const FairFieldFactory &)
Protected Attributes
FairFieldFactory * fCreator
Static Protected Attributes
static FairFieldFactory * fgRinstance = 0
Detailed Description
Definition at line 12 of file FairFieldFactory.h.
View newest version in sPHENIX GitHub at line 12 of file FairFieldFactory.h
Constructor & Destructor Documentation
FairFieldFactory::FairFieldFactory ()
Definition at line 12 of file FairFieldFactory.cxx.
View newest version in sPHENIX GitHub at line 12 of file FairFieldFactory.cxx
References fgRinstance.
FairFieldFactory::~FairFieldFactory () virtual
Definition at line 19 of file FairFieldFactory.cxx.
View newest version in sPHENIX GitHub at line 19 of file FairFieldFactory.cxx
Member Function Documentation
virtual FairField* FairFieldFactory::createFairField () inline virtual
Reimplemented in PndFieldCreator.
Definition at line 19 of file FairFieldFactory.h.
View newest version in sPHENIX GitHub at line 19 of file FairFieldFactory.h
References createFairField(), and fCreator.
Referenced by createFairField(), and FairRunAna::Init().
FairFieldFactory * FairFieldFactory::Instance () static
Definition at line 23 of file FairFieldFactory.cxx.
View newest version in sPHENIX GitHub at line 23 of file FairFieldFactory.cxx
References fgRinstance.
Referenced by FairRunAna::Init().
ClassDef (FairFieldFactory,1) private FairFieldFactory& FairFieldFactory::operator= (const FairFieldFactory &) inline protected
Definition at line 35 of file FairFieldFactory.h.
View newest version in sPHENIX GitHub at line 35 of file FairFieldFactory.h
virtual void FairFieldFactory::SetParm () inline virtual
Reimplemented in PndFieldCreator.
Definition at line 24 of file FairFieldFactory.h.
View newest version in sPHENIX GitHub at line 24 of file FairFieldFactory.h
References fCreator, and SetParm().
Referenced by FairRunAna::Init(), and SetParm().
Member Data Documentation
FairFieldFactory* FairFieldFactory::fCreator protected
Definition at line 29 of file FairFieldFactory.h.
View newest version in sPHENIX GitHub at line 29 of file FairFieldFactory.h
Referenced by createFairField(), PndFieldCreator::PndFieldCreator(), and SetParm().
FairFieldFactory * FairFieldFactory::fgRinstance = 0 static protected
Definition at line 30 of file FairFieldFactory.h.
View newest version in sPHENIX GitHub at line 30 of file FairFieldFactory.h
Referenced by FairFieldFactory(), and Instance().
The documentation for this class was generated from the following files:
EicRoot/blob/master/base/FairFieldFactory.h
EicRoot/blob/master/base/FairFieldFactory.cxx