EIC Software: EicRoot/blob/master/geometry/ECAL/cemc.C File Reference
cemc.C File Reference
Macros
#define _VERSION_ 1
#define _SUBVERSION_ 0
#define _NO_STRUCTURE_GEOMETRY_
Functions
gROOT Macro ("$VMCWORKDIR/gconfig/rootlogon.C")
cemc SetGeometryType (EicGeoParData::NoStructure)
cemc AddLogicalVolumeGroup (sectorNum, 0, sliceNum)
cout<< sectorMinR<< endl;const
Double_t sectorMaxR=(sectorMinR+cemc->
mCellLength cos ((sectorAlpha/2)*TMath::Pi()/180.)
rr SetAngles (90., 90., 0., 0., 90., 0.)
for ()
cemc SetTopVolumeTransformation (new TGeoTranslation(0.0, 0.0, 0.1 *beamLineOffset))
cemc GetColorTable () -> AddPatternMatch("CemcSector", kBlue)
cemc FinalizeOutput ()
exit (0)
Variables
CemcGeoParData * cemc = new CemcGeoParData(_VERSION_, _SUBVERSION_)
cemc mType = CalorimeterGeoParData::Fiber
cemc mCellFaceSizeX = 1.049 * 25.4
double cellFaceSize = cemc->mCellFaceSizeY = cemc->mCellFaceSizeX
cemc mCellLength = 200.0
cemc mInterCellGap = 0.0
double beamLineOffset = 1.049 * 25.4 * 2
double sectorNum = 268
double sliceNum = 120-4
const Double_t sectorAlpha = 360. / sectorNum
const Double_t sectorMinR
const Double_t sectorLength = sliceNum * sliceStep
const Double_t towerRearSideSize
cout<< towerRearSideSize
<< endl;TGeoTubeSeg *tubs=new
TGeoTubeSeg("CemcSector",
0.1 *sectorMinR,
0.1 *sectorMaxR,
0.1 *sectorLength/2.,-sectorAlpha/2.,
sectorAlpha/2.);TGeoVolume
*vtubs=new TGeoVolume("CemcSector",
tubs, cemc-> GetMedium ("air"))
TGeoVolume * vtower
TGeoRotation * rr = new TGeoRotation()
Macro Definition Documentation
#define _NO_STRUCTURE_GEOMETRY_
Definition at line 11 of file cemc.C.
View newest version in sPHENIX GitHub at line 11 of file cemc.C
#define _SUBVERSION_ 0
Definition at line 4 of file cemc.C.
View newest version in sPHENIX GitHub at line 4 of file cemc.C
#define _VERSION_ 1
Definition at line 3 of file cemc.C.
View newest version in sPHENIX GitHub at line 3 of file cemc.C
Function Documentation
cemc AddLogicalVolumeGroup (sectorNum , 0 , sliceNum)
Referenced by VstGeoParData::ConstructGeometry(), MuMegasGeoParData::ConstructGeometry(), GemGeoParData::ConstructGeometry(), and MapsGeoParData::ConstructStaveWithMapping().
cout<< sectorMinR << endl; const Double_t sectorMaxR = (sectorMinR + cemc-> mCellLength cos ((sectorAlpha/2)*TMath::Pi()/ 180.)
Referenced by PHG4BlockGeomv1::_build_rot_matrix(), accessStepWise(), TrackEvaluation::add_trk_information(), TrackEvaluation::add_trk_information_micromegas(), TrackEvaluation::add_truth_information(), TrackEvaluation::add_truth_information_micromegas(), MakeActsGeometry::addActsTpcSurfaces(), eASTMagneticFieldMap::AddFieldValue(), CylindricalHough::addHits(), airy1(), airy1d(), airy2(), airy2d(), aiz(), ALICEKF::ALICEKalmanFilter(), PHTruthClustering::all_truth_clusters(), arorie(), atrobo(), Acts::CylinderSurface::binningPosition(), biz(), Acts::Test::BOOST_AUTO_TEST_CASE(), BOOST_DATA_TEST_CASE(), Acts::IntegrationTest::BOOST_DATA_TEST_CASE(), Acts::Test::BOOST_DATA_TEST_CASE(), Acts::Test::BOOST_FIXTURE_TEST_CASE(), Acts::CylinderVolumeBounds::boundingBox(), PHG4mRICHDetector::build_mRICH_wall_hside(), buildBarrelRouting(), PHG4TTLDetector::BuildBarrelTTL(), EtmDetector::BuildCADmodel(), buildCoolingRings(), buildEndcapRouting(), Acts::TrapezoidVolumeBounds::buildSurfaceBounds(), nBodyPhaseSpaceGen::calcEventKinematics(), erhic::LeptonKinematicsComputer::Calculate(), HelixKalman::calculate_dAdAp(), HelixKalmanFilter::calculate_dAdAp(), HelixKalman::calculate_dpdb(), HelixKalmanFilter::calculate_dpdb(), CylinderKalman::calculate_dxda(), HelixKalmanFilter::calculate_dxda(), HelixHoughFuncs_v1::calculate_dzdl_range(), EtmDetectorStack::CalculateAlignmentAxis(), SvtxEvaluator::calculateClusterError(), ActsTransformations::calculateDCA(), ActsEvaluator::calculateDCA(), PHTpcResiduals::calculateTpcResiduals(), PHG4TpcCentralMembrane::CalculateVertices(), HelixDCAFunc::calcValGradHessian(), ActsExamples::Generic::ProtoLayerCreatorT< detector_element_t >::centralProtoLayers(), PHRTreeSeeding::chisq(), PHTruthTrackSeeding::circleFitSeed(), PHActsSiliconSeeding::circleFitSeed(), CMDistortionAnalysis(), CMDistortionAnalysisCart(), CMDistortionReco(), CMDistortionRecoCart(), PHG4FullProjTiltedSpacalDetector::Construct_AzimuthalSeg(), PHG4FullProjSpacalDetector::Construct_Fibers(), PHG4FullProjTiltedSpacalDetector::Construct_Fibers(), PHG4FullProjSpacalDetector::Construct_Fibers_SameLengthFiberPerTower(), PHG4FullProjTiltedSpacalDetector::Construct_Fibers_SameLengthFiberPerTower(), PHG4FullProjTiltedSpacalDetector::Construct_LightGuide(), VstGeoParData::ConstructGeometry(), GemGeoParData::ConstructGeometry(), PHG4OuterHcalDetector::ConstructHcalSingleScintillators(), PHG4InnerHcalDetector::ConstructInnerHcal(), PHG4InttDetector::ConstructIntt(), PHG4PSTOFDetector::ConstructMe(), G4JLeicDIRCDetector::ConstructMe(), G4JLeicVTXDetector::ConstructMe(), PHG4CEmcTestBeamDetector::ConstructMe(), PHG4BbcDetector::ConstructMe(), PHG4ZDCDetector::ConstructMe(), G4EicDircDetector::ConstructMe(), PHG4HcalDetector::ConstructMe(), MapsGeoParData::ConstructMimosaCell(), PHG4MvtxDetector::ConstructMvtx_Layer(), PHG4EICMvtxDetector::ConstructMvtx_Layer(), PHG4OuterHcalDetector::ConstructOuterHcal(), PHG4InnerHcalDetector::ConstructScintillatorBox(), PHG4OuterHcalDetector::ConstructScintillatorBox(), PHG4InnerHcalDetector::ConstructSteelPlate(), PHG4OuterHcalDetector::ConstructSteelPlate(), PHG4BarrelEcalDetector::ConstructTower(), PHG4CEmcTestBeamDetector::ConstructTowerVolume(), PHG4TpcDetector::ConstructTpcExternalSupports(), PHInitZVertexing::convertHelixCovarianceToEuclideanCovariance(), PHPatternReco::convertHelixCovarianceToEuclideanCovariance(), PHHoughSeeding::convertHelixCovarianceToEuclideanCovariance(), Mgrid::convertOutputField(), BEmcRecCEMC::CorrectShowerDepth(), create_element(), Acts::EventDataView3D::createEllipse(), Acts::KalmanVertexTrackUpdater::detail::createFullTrackCovariance(), PHCASeeding::CreateLinks(), RawTowerBuilder::CreateNodes(), ActsExamples::Generic::ProtoLayerCreatorT< detector_element_t >::createProtoLayers(), Acts::detail::VerticesHelper::createSegment(), Acts::CartesianSegmentation::createSegmentationSurfaces(), PHActsSiliconSeeding::createSvtxTrack(), det::createTkLayoutTrackerBarrel(), Acts::Test::CubicTrackingGeometry::CubicTrackingGeometry(), kdfinder::Helix< T >::cy(), CylinderCoordinates(), CylindricalCoordinateCurve(), CylindricalCoordinateTransformation(), twoPhotonLuminosity::D2LDMDY(), sPHENIXTracker::dcaToVertexXY(), sPHENIXSeedFinder::dcaToVertexXY(), tetgenmesh::delaunayrefinement(), Acts::CartesianSegmentation::digitizationStep(), kdfinder::TrackCandidate< T >::dip(), EtmAzimuthalScan::DoIt(), dokinematics(), Acts::GeometryView3D::drawSurfaceArray(), Gammaavectormeson::e_produceEvent(), Rossegger::Er(), Rossegger::Er_(), Acts::ImpactPointEstimator< input_track_t, propagator_t, propagator_options_t >::estimateImpactParameters(), EtmLine2D::EtmLine2D(), ActsExamples::ParticleSmearing::execute(), PHInitZVertexing::export_output(), PHPatternReco::export_output(), PHHoughSeeding::export_output(), genfit::RKTrackRep::extrapolateToCone(), Rossegger::Ez(), Rossegger::Ez_(), FGEMSetup(), fgp3(), fillEvent(), PHG4CylinderGeomv4::find_segment_center(), CylinderGeomIntt::find_segment_center(), PHG4CylinderGeomv4::find_strip_center(), fit_all_update(), SimpleTrack3D::fit_track(), ZHough_Cylindrical::fitTrack(), VtxTrackFinder::fitTrack(), ThreeHitSeedGrower::fitTrack(), NHitSeedFinder::fitTrack(), FourHitSeedFinder::fitTrack(), sPHENIXTrackerTpc::fitTrack(), sPHENIXTracker::fitTrack(), sPHENIXSeedFinder::fitTrack(), FourHitSeedFinder::fitTrackLine(), Smear::Bremsstrahlung::FixParticleKinematics(), flowAfterburner(), nucleus::formFactor(), FairGeaneUtil::FromPtToSC(), FairGeaneUtil::FromSCToPt(), Gammaavectormeson::Gammaavectormeson(), CbmRichRingFitterQa::GenerateEllipse(), ActsExamples::PrimaryGeneratorAction::GeneratePrimaries(), erhic::ParticleMCbase::Get4VectorInHadronBosonFrame(), TpcDistortionCorrection::get_corrected_position(), TowerJetInput::get_input(), CylinderGeom_Mvtx::get_local_from_world_coords(), PHG4Sector::Sector_Geometry::get_max_R(), ePHENIXRICH::RICH_Geometry::get_R_Tip_HBD(), SvtxTrackState_v1::get_rphi_error(), PHG4CylinderGeom_Spacalv3::get_tower_radial_position(), CylinderGeom_Mvtx::get_world_from_local_coords(), RawClusterv1::get_x(), PHG4TpcDistortion::get_x_distortion_cartesian(), PHG4TpcDistortion::get_y_distortion_cartesian(), ePHENIXRICH::RICH_Geometry::get_Z_Tip_HBD(), ALICEKF::getClusterError(), Acts::ImpactPointEstimator< input_track_t, propagator_t, propagator_options_t >::getDistanceAndMomentum(), AnaTutorial::getEMCalClusters(), PHField2D::GetFieldValue(), BeastMagneticField::GetFieldValue(), PHField3DCylindrical::GetFieldValue(), PHG4OuterHcalField::GetFieldValue(), ActsTransformations::getGlobalPosition(), kdfinder::TrackCandidate< T >::getMomForHit(), Smear::ParticleMCS::GetPx(), getqvec(), EtmVacuumChamber::GetRadialSize(), getscatterer(), PHG4TpcCentralMembrane::getSearchResult(), PHG4TpcCentralMembrane::getStripeID(), Gammaavectormeson::getTheta(), PndPidCorrelator::GetTrackInfo(), CbmRichRing::GetXF1(), CbmRichRingLight::GetXF1(), CbmRichRing::GetXF2(), CbmRichRingLight::GetXF2(), EicTpcDigiHitProducer::HandleHit(), hijels(), hijing(), hijsft(), hirobo(), HcalRawTowerBuilder::InitRun(), Acts::CylinderVolumeBounds::inside(), Acts::AnnulusBounds::inside(), twoPhotonLuminosity::integrand(), Acts::Test::intersectionTest(), inttk2(), Acts::DiscTrapezoidBounds::jacobianToLocalCartesian(), lazimu(), Acts::HelicalTrackLinearizer< propagator_t, propagator_options_t >::linearizeTrack(), lmprin(), Acts::ConeSurface::localCartesianToBoundLocalDerivative(), Acts::CylinderSurface::localCartesianToBoundLocalDerivative(), Acts::LineSurface::localCartesianToBoundLocalDerivative(), Acts::ConeSurface::localToGlobal(), Acts::CylinderSurface::localToGlobal(), lqgev(), lqqbev(), lsmall(), lu1ent(), lucell(), ludecy(), lueevt(), lujmas(), luonia(), luprep(), luptdi(), lurobo(), lushow(), lusphe(), lux4jt(), luxdif(), lyremn(), main(), make_GEM_station(), Acts::makeDirectionUnitFromPhiEta(), Acts::makeDirectionUnitFromPhiTheta(), makeinsplit(), genfit::EventDisplay::makeLines(), Dataset::makeParticle(), makesplitting(), FwdHoughTree::MappingCall(), ActsExamples::Generic::modulePositionsCylinder(), Acts::Test::CylindricalTrackingGeometry::modulePositionsCylinder(), ActsExamples::Generic::modulePositionsRing(), Gammaavectormeson::momenta(), kdfinder::Helix< T >::momentum(), MovePointAngle(), PHSimpleKFProp::MoveToFirstTPCCluster(), GFMaterialEffects::noiseCoulomb(), Acts::ConeSurface::normal(), Acts::CylinderSurface::normal(), ActsExamples::ParametricParticleGenerator::operator()(), Acts::Test::MaterialScattering::operator()(), tetgenmesh::optimizemesh(), PHHepMCGenHelper::pair2Hep3Vector(), Gammagammasingle::parentMomentum(), Acts::ConeSurface::pathCorrection(), kdfinder::Helix< T >::pathLength(), Acts::ImpactPointEstimator< input_track_t, propagator_t, propagator_options_t >::performNewtonApproximation(), photonNucleusCrossSection::photonFlux(), Gammaavectormeson::pi0Decay(), PHG4BarrelEcalDetector::PlaceTower(), poissonian(), PolarCoordinates(), pollazimu(), PHG4GDMLWriteSolids::PolyhedraWrite(), PHGenFitTrkFitter::pos_cov_uvn_to_rz(), PHGenFitTrkFitter::pos_cov_XYZ_to_RZ(), PHRTreeSeeding::Process(), PHG4GenHit::process_event(), PHG4ParticleGenerator::process_event(), PHG4ParticleGenerator_flat_pT::process_event(), PHG4ParticleGeneratorD0::process_event(), PHG4SimpleEventGenerator::process_event(), PHTpcTrackSeedCircleFit::process_event(), PHG4ParticleGeneratorVectorMeson::process_event(), SubtractTowers::process_event(), SubtractTowersCS::process_event(), CopyAndSubtractJets::process_event(), DetermineTowerBackground::process_event(), PHG4TpcElectronDrift::process_event(), PHGenFitTrackProjection::process_event(), PHG4MicromegasHitReco::process_event(), PHMicromegasTpcTrackMatching::process_event(), TpcDirectLaserReconstruction::process_track(), TpcSpaceChargeReconstruction::process_track(), sPHENIXTracker::projectToLayer(), sPHENIXSeedFinder::projectToLayer(), PHSimpleKFProp::PropagateTrack(), photonNucleusLuminosity::pttablegen(), pwithpF(), py1ent(), pyapps(), pycell(), pycjdc(), pydecy(), pydisg(), pyeevt(), pyeig4(), pygaga(), pyglui(), pyhext(), pyhimult(), pyhiremn(), pyhiscat(), pyhispen(), pyhixtot(), pyinom(), pyinre(), pyjmas(), pykmap(), pymirm(), pymsin(), pymult(), pynjdc(), pyonia(), pyprep(), pyptdi(), pyptfs(), pyqqbh(), pyreco(), pyremn(), pyresd(), pyrghm(), pyrobo(), pyscat(), pysfdc(), pysgtc(), pyshow(), pyspen(), pysphe(), pystbh(), pysugi(), pytbdy(), pythrg(), pywidt(), pyx4jt(), pyxdif(), quench(), radgam_pol(), EicBoxGenerator::ReadEvent(), RawTowerBuilderByHitIndexBECAL::ReadGeometryFromTable(), Mgrid::recalculatePosition(), Acts::AtlasStepper< bfield_t >::resetState(), FwdTrackFinder::ResetVtxNode(), RosenBrock(), GPUTPCTrackParam::Rotate(), TpcClusterCleaner::rotate_error(), RotateTranslateScale(), kdfinder::TVector< T >::rotateX(), kdfinder::TVector< T >::rotateY(), kdfinder::TVector< T >::rotateZ(), Acts::detail::rotationToLocalAxesDerivative(), ActsExamples::RootBFieldWriter< bfield_t >::run(), PHG4Sector::Sector_Geometry::set_normal_start(), kdfinder::Helix< T >::setDipAngle(), kdfinder::TVector< T >::setMagnitude(), EicHtcTask::SetMediaScanThetaPhi(), kdfinder::Helix< T >::setPhase(), kdfinder::TVector< T >::setPhi(), kdfinder::TVector< T >::setTheta(), PHG4HcalSubsystem::SetTiltViaNcross(), Smear::Detector::Smear(), Acts::AtlasStepper< bfield_t >::State::State(), Acts::SurfaceArrayCreator::surfaceArrayOnCylinder(), Acts::SurfaceArrayCreator::surfaceArrayOnDisc(), Acts::Test::CylindricalTrackingGeometry::surfacesCylinder(), Acts::Test::CylindricalTrackingGeometry::surfacesRing(), tails(), EicKfNodeTemplateRadial1D::TemplateToThreeDee(), EicKfNodeTemplateAsimuthal1D::TemplateToThreeDee(), EicKfNodeTemplateCylindrical2D::TemplateToThreeDee(), Acts::EventDataView3DTest::testMultiTrajectory(), Acts::DiscTrapezoidBounds::toLocalCartesian(), transform_coord_type(), CylinderGeomMicromegas::transformation_matrix(), CbmRichRingFitterEllipseTau::TransformEllipse(), Gammaavectormeson::twoBodyDecay(), Gammagammasingle::twoBodyDecay(), CylinderKalman::updateIntersection(), HelixKalmanFilter::updateIntersection(), PHActsVertexPropagator::updateTrackDCA(), PHActsVertexFinder::updateTrackDCA(), Acts::DiscTrapezoidBounds::vertices(), Gammaavectormeson::vmpt(), vn_func_derivative(), HelixHough::vote_z(), vtx_builder(), kdfinder::Helix< T >::x(), and zdc().
exit (0)
Referenced by PHG4Cellv1::add_property(), RawTowerGeomContainerv1::add_tower_geometry(), RawTowerZDCGeomContainer::add_tower_geometry(), PHG4CellContainer::AddCellSpecifyKey(), TrkrClusterContainerv2::addClusterSpecifyKey(), TrkrClusterContainerv3::addClusterSpecifyKey(), CMFlashClusterContainerv1::addClusterSpecifyKey(), TrkrClusterContainerv1::addClusterSpecifyKey(), PHG4CylinderCellContainer::AddCylinderCellSpecifyKey(), RawTowerDeadMapv1::addDeadTower(), TrkrHitSetContainerv1::addHitSetSpecifyKey(), TrkrHitSetv1::addHitSpecificKey(), Fun4AllEventOutStream::AddPacketRange(), PHG4InEvent::AddParticle(), KFParticle_Container::addParticleSpecifyKey(), PHG4ScintillatorSlatContainer::AddScintillatorSlat(), RawTowerContainer::AddTower(), RawTowerZDCContainer::AddTower(), RawClusterv1::addTower(), aerogel(), JetRecoEval::all_truth_hits(), JetRecoEval::all_truth_particles(), JetTruthEval::all_truth_particles(), JetRecoEval::all_truth_showers(), analysis(), Input::ApplyEICBeamParameter(), Input::ApplysPHENIXBeamParameter(), b0tracker(), beampipe(), Fun4AllServer::BeginRun(), bigerror(), Acts::Test::BOOST_DATA_TEST_CASE(), calorimeter(), CEmc(), CEmc_1DProjectiveSpacal(), CEMC_Clusters(), CEMC_Towers(), CharmTagPlots(), PHG4CylinderCellGeom::check_binning_method(), PHG4BlockCellGeom::check_binning_method(), PHG4CylinderCellGeom::check_binning_method_eta(), PHG4BlockCellGeom::check_binning_method_eta(), PHG4CylinderCellGeom::check_binning_method_phi(), PHG4BlockCellGeom::check_binning_method_x(), PHG4OuterHcalDetector::CheckTiltAngle(), PHG4InnerHcalDetector::CheckTiltAngle(), ClassImp(), PgPostBankBackupManager::CleanTable(), MvtxClusterizer::ClusterMvtx(), PgPostBankWrapper::commit(), PgPostBankBackupManager::commit(), PgPostBankBackupManager::commitAllBankfromTFile(), compressionexitmsg(), PHGeomTGeo::ConsistencyCheck(), BasicDetectorConstruction::Construct(), PHG4PhenixDetector::Construct(), LqstGeoParData::constructEcalLayers(), PHG4TpcEndCapDetector::ConstructElectronics(), VstGeoParData::ConstructGeometry(), EicDetector::ConstructGeometry(), MuMegasGeoParData::ConstructGeometry(), GemGeoParData::ConstructGeometry(), PHG4InttDetector::ConstructIntt(), PHG4BeamlineMagnetDetector::ConstructMe(), PHG4FCalDetector::ConstructMe(), BeamLineMagnetDetector::ConstructMe(), PHG4FPbScDetector::ConstructMe(), PHG4ProjCrystalCalorimeterDetector::ConstructMe(), PHG4CrystalCalorimeterDetector::ConstructMe(), PHG4HybridHomogeneousCalorimeterDetector::ConstructMe(), PHG4GDMLDetector::ConstructMe(), MapsGeoParData::ConstructStaveWithMapping(), PHG4ForwardEcalDetector::ConstructTower(), LqstGeoParData::constructTrackerLayers(), RawTowerZDCDefs::convert_caloid_to_name(), RawTowerDefs::convert_caloid_to_name(), RawTowerZDCDefs::convert_name_to_caloid(), RawTowerDefs::convert_name_to_caloid(), PHParameters::ConvertStringToUint(), PHGenIntegralv1::CopyFrom(), PHHepMCGenHelper::CopyHelperSettings(), PHHepMCGenHelper::CopySettings(), genfit::MeasurementCreator::create(), PHPythia8::create_node_tree(), PHG4TpcDetector::CreateCompositeMaterial(), PHG4TpcEndCapDetector::CreateCompositeMaterial(), CaloTriggerSim::CreateNode(), DetermineTowerBackground::CreateNode(), ParticleFlowReco::CreateNode(), BbcVertexFastSimReco::CreateNodes(), GlobalVertexFastSimReco::CreateNodes(), GlobalVertexReco::CreateNodes(), RawTowerBuilder::CreateNodes(), HcalRawTowerBuilder::CreateNodes(), KFParticle_DST::createParticleNode(), Acts::Sycl::createSeedsForGroupSycl(), PgPostBankBackupManager::deleteODBCPreparedStatement(), PgPostBankBackupManager::deleteSQLStatement(), df2root(), PHG4TpcDigitizer::DigitizeCylinderCells(), PHG4InttDigitizer::DigitizeLadderCells(), PHG4MvtxDigitizer::DigitizeMvtxLadderCells(), Fun4AllEventOutStream::DropPacketRange(), PgPostBankBackupManager::dumpTable(), RawTowerDefs::encode_towerid(), RawTowerZDCDefs::encode_towerid_zdc(), Fun4AllServer::End(), EicDetector::EndOfEvent(), Fun4AllServer::EndRun(), eTTreemaker(), evtcountexitmsg(), exithelp(), exitmsg(), extract_cd_step(), extract_vc_gdml(), f2ascii(), FairGeoLoader::FairGeoLoader(), fbgt(), fbst(), femc(), FEMC_Clusters(), FermiMotion(), PgPostBankBackupManager::fetchAllBank2TFile(), PgPostBankManager::fetchBank(), PgPostBankBackupManager::fetchBank(), PgPostBankManager::fetchClosestBank(), Fun4AllDstInputManager::fileopen(), Fun4AllOscarInputManager::fileopen(), Fun4AllHepMCInputManager::fileopen(), JetReco::FillJetNode(), JetEvaluator::fillOutputNtuples(), CaloEvaluator::fillOutputNtuples(), EventEvaluatorEIC::fillOutputNtuples(), flowAfterburner(), Fun4All_G4_simplified_3vtx(), Fun4All_G4_simplified_v2(), Fun4All_G4_simplified_v2_DIRC_barrel_GEM(), Fun4AllDstOutputManager::Fun4AllDstOutputManager(), Fun4AllHepMCOutputManager::Fun4AllHepMCOutputManager(), PHG4PrimaryGeneratorAction::GeneratePrimaries(), generic_32bit_key(), generic_lower_16bit_key(), generic_upper_16bit_key(), PHG4HitContainer::genkey(), PHG4CylinderCellContainer::genkey(), PHG4TpcDistortion::get_distortion(), PHG4DetectorGroupSubsystem::get_double_param(), PHParameters::get_double_param(), PHG4CylinderCellGeom_Spacalv1::get_etabin(), RawTowerGeomContainer_Cylinderv1::get_etabin(), PHG4CylinderCellGeom_Spacalv1::get_etabounds(), PHG4BlockCellGeom::get_etabounds(), PHG4CylinderCellGeom::get_etabounds(), RawTowerGeomContainer_Cylinderv1::get_etabounds(), PHG4CylinderCellGeom::get_etacenter(), PHG4BlockCellGeom::get_etacenter(), RawTowerGeomContainer_Cylinderv1::get_etacenter(), AllSiliconTrackerDetector::get_hitcontainer(), PHG4DetectorGroupSubsystem::get_int_param(), PHParameters::get_int_param(), PHG4Hitv1::get_local_x(), PHG4Hitv1::get_local_y(), PHG4Hitv1::get_local_z(), BaseTruthEval::get_node_pointers(), JetTruthEval::get_node_pointers(), JetRecoEval::get_node_pointers(), RawTowerGeomContainer_Cylinderv1::get_phibin(), PHG4CylinderCellGeom::get_phibounds(), RawTowerGeomContainer_Cylinderv1::get_phibounds(), PHG4CylinderCellGeom::get_phicenter(), RawTowerGeomContainer_Cylinderv1::get_phicenter(), EicEventHeaderv1::get_property_float(), EICPIDParticlev1::get_property_float(), PHG4Hitv1::get_property_float(), PHG4Cellv1::get_property_float(), RawClusterv1::get_property_float(), EICPIDParticle::get_property_info(), EicEventHeader::get_property_info(), PHG4Cell::get_property_info(), RawTower::get_property_info(), RawTowerZDC::get_property_info(), PHG4Hit::get_property_info(), RawCluster::get_property_info(), EicEventHeaderv1::get_property_int(), EICPIDParticlev1::get_property_int(), PHG4Hitv1::get_property_int(), PHG4Cellv1::get_property_int(), RawClusterv1::get_property_int(), EicEventHeaderv1::get_property_uint(), EICPIDParticlev1::get_property_uint(), PHG4Hitv1::get_property_uint(), PHG4Cellv1::get_property_uint(), RawClusterv1::get_property_uint(), PHG4Hitv1::get_px(), PHG4Hitv1::get_py(), PHG4Hitv1::get_pz(), PHG4DetectorGroupSubsystem::get_string_param(), PHParameters::get_string_param(), PHG4CylinderGeom_Spacalv3::get_tower_radial_position(), PHG4BlockCellGeom::get_xbounds(), PHG4BlockCellGeom::get_xcenter(), PHG4CylinderCellGeom_Spacalv1::get_zbin(), PHG4CylinderCellGeom_Spacalv1::get_zbounds(), PHG4BlockCellGeom::get_zbounds(), PHG4CylinderCellGeom::get_zbounds(), PHG4CylinderCellGeom::get_zcenter(), PHG4BlockCellGeom::get_zcenter(), PHNodeIOManager::getBranchClassName(), FwdHoughTree::GetBzAtIP(), RunToTimePg::GetConnection(), PHG4CylinderCellContainer::getCylinderCells(), PHG4Detector::GetDetectorElement(), PHG4Detector::GetDetectorMaterial(), ePHENIXRICH::ePHENIXRICHConstruction::GetDetectorMaterial(), EicBeamLineElementMap::GetFieldValue(), PHG4OuterHcalField::GetFieldValue(), PHG4HitContainer::getHits(), MakeActsGeometry::getInttKeyFromNode(), PHG4OuterHcalDetector::GetLayerTowerId(), PHG4InnerHcalDetector::GetLayerTowerId(), PHSiliconTruthTrackSeeding::GetNodes(), PHTruthTrackSeeding::GetNodes(), PHParametersContainer::GetParameters(), RunToTimePg::getRunNumber(), PHG4ScintillatorSlatContainer::getScintillatorSlats(), EicRcParticle::GetStatus(), PHGeomUtility::GetTGeoManager(), RunToTimePg::getTime(), EicCalorimeterDigiHitProducer::HandleHit(), handler(), Fun4AllDstInputManager::HasSyncObject(), hcal(), HCALInner_Clusters(), HCALOuter_Clusters(), PHHepMCGenHelper::HepMC2Lab_boost_rotation_translation(), PHG4HeadReco::Init(), PHPythia6::Init(), PgPostCalBankIterator::init(), PHPythia8::Init(), FairRunAna::Init(), PHG4Reco::Init(), KFParticle_sPHENIX::Init(), PgPostBankBackupLog::Init(), CellularAutomaton_v1::init(), PHG4TpcDistortion::Init(), RawTowerBuilder::InitRun(), HcalRawTowerBuilder::InitRun(), RawTowerDeadTowerInterp::InitRun(), PHG4MvtxHitReco::InitRun(), PHG4HcalCellReco::InitRun(), PHG4ForwardCalCellReco::InitRun(), PHG4InttHitReco::InitRun(), PHG4BlockCellReco::InitRun(), PHG4CylinderCellReco::InitRun(), RawTowerCalibration::InitRun(), RawTowerZDCCalibration::InitRun(), B0RawTowerBuilderByHitIndex::InitRun(), BwdRawTowerBuilderByHitIndex::InitRun(), RawTowerBuilderDRCALO::InitRun(), RawTowerBuilderByHitIndexBECAL::InitRun(), RawTowerBuilderByHitIndexLHCal::InitRun(), EICG4ZDCRawTowerBuilderByHitIndex::InitRun(), RawTowerBuilderByHitIndex::InitRun(), PHG4FullProjSpacalCellReco::InitRun(), TpcLoadDistortionCorrection::InitRun(), RawTowerDigitizer::InitRun(), RawTowerZDCDigitizer::InitRun(), BbcVertexFastSimReco::InitRun(), GlobalVertexFastSimReco::InitRun(), TPCDataStreamEmulator::InitRun(), PHG4MicromegasHitReco::InitRun(), PHG4TpcElectronDrift::InitRun(), RawDigitBuilderTTL::InitRun(), RawTowerCombiner::InitRun(), EICG4dRICHSubsystem::InitRunSubsystem(), PHGenIntegralv1::Integrate(), CommandLineArguments::interpret(), Intt_Cells(), ip(), ippt(), JLDIRC(), LoadUniversalMesh(), PgPostBankBackupLog::Log(), lowq2tagger(), lqst(), main(), PHG4CylinderCellGeom_Spacalv1::map_consistency_check(), PHG4Utils::md5sum(), FROG::MinIOSearch(), mumegas(), Fun4AllNoSyncDstInputManager::NoRunTTree(), nrerror(), RootOut::Open(), FairRootManager::OpenOutFile(), PHGenFitTrkProp::OutputPHGenFitTrack(), CommandLineArguments::parse(), PgPostBankBackupStorage::PgPostBankBackupStorage(), PgPostCalBankIterator::PgPostCalBankIterator(), PHField2D::PHField2D(), PHField3DCartesian::PHField3DCartesian(), PHField3DCylindrical::PHField3DCylindrical(), PHFieldCleo::PHFieldCleo(), PHG4EtaParameterization::PHG4EtaParameterization(), PHG4EtaPhiParameterization::PHG4EtaPhiParameterization(), PHG4SpacalDetector::PHG4SpacalDetector(), Pipe(), PgPostBankWrapperManager::print(), PrintHelp(), CaloEvaluator::printInputInfo(), CaloEvaluator::printOutputInfo(), PHSiliconTruthTrackSeeding::Process(), PHTruthTrackSeeding::Process(), PHInitZVertexing::Process(), MomentumEvaluator::process_event(), RawTowerBuilder::process_event(), PHG4InEventCompress::process_event(), RawTowerDeadTowerInterp::process_event(), HcalRawTowerBuilder::process_event(), TPCIntegratedCharge::process_event(), HepMCNodeReader::process_event(), PHG4MvtxHitReco::process_event(), PHG4ForwardCalCellReco::process_event(), PHG4HcalCellReco::process_event(), PHG4InttHitReco::process_event(), BwdRawTowerBuilderByHitIndex::process_event(), RawTowerBuilderDRCALO::process_event(), RawTowerBuilderByHitIndexLHCal::process_event(), EICG4ZDCRawTowerBuilderByHitIndex::process_event(), RawTowerBuilderByHitIndex::process_event(), PHG4BlockCellReco::process_event(), RawTowerBuilderByHitIndexBECAL::process_event(), B0RawTowerBuilderByHitIndex::process_event(), PHG4CylinderCellReco::process_event(), PHG4FullProjSpacalCellReco::process_event(), BbcVertexFastSimReco::process_event(), GlobalVertexReco::process_event(), PHG4TruthSubsystem::process_event(), PHG4SimpleEventGenerator::process_event(), PHG4ParticleGeneratorVectorMeson::process_event(), GlobalVertexFastSimReco::process_event(), TPCDataStreamEmulator::process_event(), LiteCaloEval::process_event(), MyJetAnalysis::process_event(), RawDigitBuilderTTL::process_event(), PHPatternReco::process_event(), Fun4AllServer::process_event(), QAG4SimulationJet::process_Spectrum(), QAG4SimulationJet::process_TruthMatching(), e_starlight::produceEvent(), erhic::Pythia6::Pythia6(), Pythia6::Pythia6(), PHPythia8::read_config(), PHPythia6::ReadConfig(), PHNodeIOManager::readEventFromFile(), PHParameters::ReadFromDB(), RawTowerBuilderDRCALO::ReadGeometryFromTable(), B0RawTowerBuilderByHitIndex::ReadGeometryFromTable(), BwdRawTowerBuilderByHitIndex::ReadGeometryFromTable(), RawTowerBuilderByHitIndexBECAL::ReadGeometryFromTable(), RawTowerBuilderByHitIndexLHCal::ReadGeometryFromTable(), RawTowerBuilderByHitIndex::ReadGeometryFromTable(), EICG4ZDCRawTowerBuilderByHitIndex::ReadGeometryFromTable(), PHG4DetectorGroupSubsystem::ReadParamsFromFile(), PHG4DetectorSubsystem::ReadParamsFromFile(), PndFieldMap::ReadRootFile(), genfit::ReferenceStateOnPlane::ReferenceStateOnPlane(), Fun4AllServer::registerSubsystem(), TrkrHitSetv1::removeHit(), PHG4ParticleGeneratorBase::ReuseExistingVertex(), rich(), romanPot_v2(), Rossegger::Rossegger(), rp(), Fun4AllSyncManager::run(), EicRunAna::Run(), CellularAutomaton_v1::run(), Fun4AllServer::run(), EicRunSim::Run(), FairRunAna::RunWithTimeStamps(), PHG4DetectorGroupSubsystem::SaveParamsToFile(), PHG4DetectorSubsystem::SaveParamsToFile(), scan(), PHG4CylinderGeom_Spacalv2::set_azimuthal_n_sec(), PHG4CylinderGeom_Spacalv2::set_azimuthal_seg_visible(), PHHepMCGenHelper::set_beam_bunch_width(), HelixHoughBin_v1::set_bins(), PHG4DetectorSubsystem::set_default_double_param(), PHG4DetectorGroupSubsystem::set_default_double_param(), PHG4DetectorSubsystem::set_default_int_param(), PHG4DetectorGroupSubsystem::set_default_int_param(), PHG4DetectorSubsystem::set_default_string_param(), PHG4DetectorGroupSubsystem::set_default_string_param(), RawTowerGeomContainer_Cylinderv1::set_etabounds(), PHG4Hitv1::set_local_x(), PHG4Hitv1::set_local_y(), PHG4Hitv1::set_local_z(), PgPostBankBackupStorage::set_obj_info(), RawTowerGeomContainer_Cylinderv1::set_phibounds(), EicEventHeaderv1::set_property(), EICPIDParticlev1::set_property(), PHG4Hitv1::set_property(), PHG4Cellv1::set_property(), RawClusterv1::set_property(), PHG4Hitv1::set_px(), PHG4Hitv1::set_py(), PHG4Hitv1::set_pz(), PHHepMCGenHelper::set_vertex_distribution_function(), PHHepMCGenHelper::set_vertex_distribution_mean(), PHHepMCGenHelper::set_vertex_distribution_width(), FairRunAna::SetGeomFile(), G4TBMagneticFieldSetup::SetStepper(), PHG4OuterHcalDetector::SetTiltViaNcross(), PHG4HcalSubsystem::SetTiltViaNcross(), PHG4InnerHcalDetector::SetTiltViaNcross(), PHG4MicromegasHitReco::setup_tiles(), EicRcParticle::SetVertex(), sf2root(), sig_handler(), smallerror(), PHHepMCGenHelper::smear(), PgPostBankBackupManager::SQLResultSet2BackupStorage(), star(), FairMCApplication::StopRun(), EICG4ZDCRawTowerBuilderByHitIndex::SubDetector(), Fun4AllPrdfInputManager::SyncIt(), terminatetetgen(), Fun4AllServer::topNode(), tpc(), tpc_builder(), tracker(), usage(), PHG4EICMvtxSteppingAction::UserSteppingAction(), PHG4TpcSteppingAction::UserSteppingAction(), PHG4MvtxSteppingAction::UserSteppingAction(), PHG4BlockSteppingAction::UserSteppingAction(), PHG4ECAPToFSteppingAction::UserSteppingAction(), PHG4CylinderSteppingAction::UserSteppingAction(), PHG4TRDSteppingAction::UserSteppingAction(), G4EicDircSteppingAction::UserSteppingAction(), PHG4SpacalSteppingAction::UserSteppingAction(), vst(), VTX(), vtx_builder(), Fun4AllRolloverFileOutStream::WriteEventOut(), Fun4AllFileOutStream::WriteEventOut(), PHParametersContainer::WriteToDB(), PHParameters::WriteToDB(), PHG4OuterHcalDetector::x_at_y(), PHG4InnerHcalDetector::x_at_y(), and zdc().
cemc FinalizeOutput ()
Referenced by VstGeoParData::ConstructGeometry(), MuMegasGeoParData::ConstructGeometry(), and GemGeoParData::ConstructGeometry().
for ()
Definition at line 157 of file cemc.C.
View newest version in sPHENIX GitHub at line 157 of file cemc.C
Referenced by tetgenmesh::checksegments(), tetgenmesh::checktet4split(), oncsSub_iddrs4v1::decode(), oncsSub_iduppetparams::decode(), oncsSub_idfnalmwpc::decode(), oncsSub_idfnalmwpcv2::decode(), KFParticle_eventReconstruction::getCandidateDecay(), tetgenmesh::highorder(), tetgenmesh::incrementalflip(), tetgenmesh::insertpoint(), tetgenmesh::interecursive(), tetgenmesh::makefacetverticesmap(), mkf2(), pepsimainerhic(), pygdir(), r1998(), tetgenmesh::suppressbdrysteinerpoint(), and testEventiterator::testEventiterator().
cemc GetColorTable () -> AddPatternMatch("CemcSector", kBlue)
gROOT Macro ("$VMCWORKDIR/gconfig/rootlogon.C")
rr SetAngles (90. , 90. , 0. , 0. , 90. , 0.)
cemc SetGeometryType (EicGeoParData::NoStructure)
cemc SetTopVolumeTransformation (new TGeoTranslation0.0, 0.0, 0.1 *beamLineOffset)
Variable Documentation
double beamLineOffset = 1.049 * 25.4 * 2
Definition at line 53 of file cemc.C.
View newest version in sPHENIX GitHub at line 53 of file cemc.C
Referenced by MuMegasGeoParData::AddBarrel(), calorimeter(), LqstGeoParData::constructDetector(), femc(), hcal(), lowq2tagger(), romanPot_v2(), tracker(), and zdc().
double cellFaceSize = cemc->mCellFaceSizeY = cemc->mCellFaceSizeX
Definition at line 47 of file cemc.C.
View newest version in sPHENIX GitHub at line 47 of file cemc.C
Referenced by calorimeter(), LqstGeoParData::constructEcalLayers(), LqstGeoParData::constructTrackerLayers(), and lowq2tagger().
CemcGeoParData* cemc = new CemcGeoParData(_VERSION_, _SUBVERSION_)
Definition at line 29 of file cemc.C.
View newest version in sPHENIX GitHub at line 29 of file cemc.C
Referenced by CEmc(), CEmc_1DProjectiveSpacal(), CEmc_2DProjectiveSpacal(), digitization(), and reconstruction().
cout<< towerRearSideSize << endl; TGeoTubeSeg *tubs = new TGeoTubeSeg("CemcSector", 0.1 * sectorMinR, 0.1 * sectorMaxR, 0.1 * sectorLength/2., -sectorAlpha/2., sectorAlpha/2.); TGeoVolume *vtubs = new TGeoVolume("CemcSector", tubs, cemc-> GetMedium("air"))
Definition at line 144 of file cemc.C.
View newest version in sPHENIX GitHub at line 144 of file cemc.C
Referenced by VstGeoParData::ConstructGeometry(), MuMegasGeoParData::ConstructGeometry(), GemGeoParData::ConstructGeometry(), MapsGeoParData::ConstructMimosaCell(), MapsGeoParData::ConstructStave(), MuMegasGeoParData::PlaceMaterialLayer(), and GemGeoParData::PlaceMaterialLayer().
cemc mCellFaceSizeX = 1.049 * 25.4
Definition at line 45 of file cemc.C.
View newest version in sPHENIX GitHub at line 45 of file cemc.C
cemc mCellLength = 200.0
Definition at line 48 of file cemc.C.
View newest version in sPHENIX GitHub at line 48 of file cemc.C
cout<< sectorMaxR << endl; const Double_t sliceStep = cellFaceSize + cemc-> mInterCellGap = 0.0
Definition at line 50 of file cemc.C.
View newest version in sPHENIX GitHub at line 50 of file cemc.C
cemc mType = CalorimeterGeoParData::Fiber
Definition at line 43 of file cemc.C.
View newest version in sPHENIX GitHub at line 43 of file cemc.C
TGeoRotation* rr = new TGeoRotation()
Definition at line 155 of file cemc.C.
View newest version in sPHENIX GitHub at line 155 of file cemc.C
Referenced by FluxMonitorGrid::AddEntry(), EicToyModel::CalculateDefaultEtaBoundaries(), FstGeoParData::ConstructGeometry(), CreateTetrahedron(), femc(), EicTpcDigiHitProducer::HandleHit(), hcal(), hifun(), hijels(), hijwds(), hirnd(), hirnd2(), PHG4Utils::line_and_rectangle_intersect(), mfield2eve(), BEmcProfile::PredictEnergy(), BEmcRec::PredictEnergyProb(), pywidt(), and strf().
const Double_t sectorAlpha = 360. / sectorNum
Definition at line 111 of file cemc.C.
View newest version in sPHENIX GitHub at line 111 of file cemc.C
const Double_t sectorLength = sliceNum * sliceStep
Definition at line 122 of file cemc.C.
View newest version in sPHENIX GitHub at line 122 of file cemc.C
const Double_t sectorMinR
Initial value:
= ((cellFaceSize + cemc->mInterCellGap)/2) *
    tan((90 - sectorAlpha / 2) * TMath::Pi() / 180.)
Definition at line 112 of file cemc.C.
View newest version in sPHENIX GitHub at line 112 of file cemc.C
double sectorNum = 268
Definition at line 101 of file cemc.C.
View newest version in sPHENIX GitHub at line 101 of file cemc.C
double sliceNum = 120-4
Definition at line 103 of file cemc.C.
View newest version in sPHENIX GitHub at line 103 of file cemc.C
const Double_t towerRearSideSize
Initial value:
= cellFaceSize + 2.*cemc->mCellLength*
    tan((sectorAlpha / 2) * TMath::Pi() / 180.)
Definition at line 127 of file cemc.C.
View newest version in sPHENIX GitHub at line 127 of file cemc.C
TGeoVolume* vtower
Initial value:
=
      new TGeoVolume("CemcTower", tower, cemc->GetMedium(cemc->mFiber ? "WEpoxyMix" : "WEpoxySciMix"))
Definition at line 153 of file cemc.C.
View newest version in sPHENIX GitHub at line 153 of file cemc.C
Referenced by femc(), hcal(), and make_single_tower().