EIC Software: CbmRichRingFinderHough Class Reference
CbmRichRingFinderHough Class Reference
Main class for ring finder based on Hough Transform implementation.
#include <EicRoot/blob/master/rich/finder/CbmRichRingFinderHough.h>
Public Member Functions
CbmRichRingFinderHough ()
Standard constructor.
virtual ~CbmRichRingFinderHough ()
Destructor.
virtual void Init ()
Inherited from CbmRichRingFinder.
virtual Int_t DoFind (TClonesArray *rHitArray, TClonesArray *rProjArray, TClonesArray *rRingArray)
Inherited from CbmRichRingFinder.
CbmRichRingFinderHough ()
virtual ~CbmRichRingFinderHough ()
int DoFind (const std::vector< CbmRichHoughHit > &data)
int DoFindParallel (const std::vector< CbmRichHoughHit > &data)
Public Member Functions inherited from CbmRichRingFinder
CbmRichRingFinder ()
virtual ~CbmRichRingFinder ()
void SetVerbose (Int_t verbose)
Protected Attributes
Int_t fNEvent
Int_t fRingCount
CbmRichRingFinderHoughImpl * fHTImpl
int fNEvent
int fRingCount
event number
CbmRichRingFinderHoughImpl * fHTImpl1
CbmRichRingFinderHoughImpl * fHTImpl2
double fExecTime
Protected Attributes inherited from CbmRichRingFinder
Int_t fVerbose
Private Member Functions
void AddRingsToOutputArray (TClonesArray *rRingArray, const vector< CbmRichRingLight * > &rings)
Add found rings to the output TClonesArray.
CbmRichRingFinderHough (const CbmRichRingFinderHough &)
Copy constructor.
CbmRichRingFinderHough & operator= (const CbmRichRingFinderHough &)
Assignment operator.
Detailed Description
Main class for ring finder based on Hough Transform implementation.
Author
Semen Lebedev
Date
2008
Definition at line 36 of file CbmRichRingFinderHough.h.
View newest version in sPHENIX GitHub at line 36 of file CbmRichRingFinderHough.h
Constructor & Destructor Documentation
CbmRichRingFinderHough::CbmRichRingFinderHough ()
Standard constructor.
Definition at line 36 of file CbmRichRingFinderHough.cxx.
View newest version in sPHENIX GitHub at line 36 of file CbmRichRingFinderHough.cxx
References fHTImpl1, fHTImpl2, fNEvent, fRingCount, init(), and CbmRichRingFinderHoughImpl::Init().
CbmRichRingFinderHough::~CbmRichRingFinderHough () virtual
Destructor.
Definition at line 50 of file CbmRichRingFinderHough.cxx.
View newest version in sPHENIX GitHub at line 50 of file CbmRichRingFinderHough.cxx
References fHTImpl1, and fHTImpl2.
CbmRichRingFinderHough::CbmRichRingFinderHough (const CbmRichRingFinderHough &) private
Copy constructor.
CbmRichRingFinderHough::CbmRichRingFinderHough ()
virtual CbmRichRingFinderHough::~CbmRichRingFinderHough () virtual
Member Function Documentation
void CbmRichRingFinderHough::AddRingsToOutputArray (TClonesArray * rRingArray, const vector< CbmRichRingLight * > & rings) private
Add found rings to the output TClonesArray.
Parameters
[out] rRingArray Output array of CbmRichRing.
[in] rings Found rings.
int CbmRichRingFinderHough::DoFind (const std::vector< CbmRichHoughHit > & data)
Definition at line 56 of file CbmRichRingFinderHough.cxx.
View newest version in sPHENIX GitHub at line 56 of file CbmRichRingFinderHough.cxx
References CbmRichRingFinderHoughImpl::DoFind(), CbmRichHoughHit::fHit, fHTImpl1, fNEvent, fRingCount, CbmRichHitLight::fY, CbmRichRingFinderHoughImpl::GetFoundRings(), and CbmRichRingFinderHoughImpl::SetData().
virtual Int_t CbmRichRingFinderHough::DoFind (TClonesArray * rHitArray, TClonesArray * rProjArray, TClonesArray * rRingArray) virtual
Inherited from CbmRichRingFinder.
Implements CbmRichRingFinder.
Referenced by main().
int CbmRichRingFinderHough::DoFindParallel (const std::vector< CbmRichHoughHit > & data)
Definition at line 87 of file CbmRichRingFinderHough.cxx.
View newest version in sPHENIX GitHub at line 87 of file CbmRichRingFinderHough.cxx
References CbmRichHoughHit::fHit, fHTImpl1, fHTImpl2, fNEvent, fRingCount, CbmRichHitLight::fY, CbmRichRingFinderHoughImpl::GetFoundRings(), and CbmRichRingFinderHoughImpl::SetData().
virtual void CbmRichRingFinderHough::Init () virtual
Inherited from CbmRichRingFinder.
Reimplemented from CbmRichRingFinder.
CbmRichRingFinderHough& CbmRichRingFinderHough::operator= (const CbmRichRingFinderHough &) private
Assignment operator.
Member Data Documentation
double CbmRichRingFinderHough::fExecTime protected
Definition at line 24 of file CbmRichRingFinderHough.h.
View newest version in sPHENIX GitHub at line 24 of file CbmRichRingFinderHough.h
CbmRichRingFinderHoughImpl* CbmRichRingFinderHough::fHTImpl protected
Definition at line 44 of file CbmRichRingFinderHough.h.
View newest version in sPHENIX GitHub at line 44 of file CbmRichRingFinderHough.h
CbmRichRingFinderHoughImpl* CbmRichRingFinderHough::fHTImpl1 protected
Definition at line 21 of file CbmRichRingFinderHough.h.
View newest version in sPHENIX GitHub at line 21 of file CbmRichRingFinderHough.h
Referenced by CbmRichRingFinderHough(), DoFind(), DoFindParallel(), and ~CbmRichRingFinderHough().
CbmRichRingFinderHoughImpl* CbmRichRingFinderHough::fHTImpl2 protected
Definition at line 22 of file CbmRichRingFinderHough.h.
View newest version in sPHENIX GitHub at line 22 of file CbmRichRingFinderHough.h
Referenced by CbmRichRingFinderHough(), DoFindParallel(), and ~CbmRichRingFinderHough().
int CbmRichRingFinderHough::fNEvent protected
Definition at line 18 of file CbmRichRingFinderHough.h.
View newest version in sPHENIX GitHub at line 18 of file CbmRichRingFinderHough.h
Int_t CbmRichRingFinderHough::fNEvent protected
Definition at line 39 of file CbmRichRingFinderHough.h.
View newest version in sPHENIX GitHub at line 39 of file CbmRichRingFinderHough.h
Referenced by CbmRichRingFinderHough(), DoFind(), and DoFindParallel().
int CbmRichRingFinderHough::fRingCount protected
event number
Definition at line 19 of file CbmRichRingFinderHough.h.
View newest version in sPHENIX GitHub at line 19 of file CbmRichRingFinderHough.h
Int_t CbmRichRingFinderHough::fRingCount protected
Definition at line 40 of file CbmRichRingFinderHough.h.
View newest version in sPHENIX GitHub at line 40 of file CbmRichRingFinderHough.h
Referenced by CbmRichRingFinderHough(), DoFind(), and DoFindParallel().
The documentation for this class was generated from the following files:
EicRoot/blob/master/rich/finder/CbmRichRingFinderHough.h
EicRoot/blob/master/rich/standalone/algorithm/CbmRichRingFinderHough.h
EicRoot/blob/master/rich/standalone/algorithm/CbmRichRingFinderHough.cxx