EIC Software: Detector Namespace Reference
Detector Namespace Reference
Typedefs
typedef enum Detector::EDetector Detector_t
Enumerations
enum EDetector {
kUnknown = 0x00, kCal = 0x01, kCalCrystal = 0x02, kDch = 0x04,
kGfi = 0x08, kLand = 0x10, kMtof = 0x12, kTof = 0x14,
kTracker = 0x16
}
Functions
Int_t FullMask ()
const Char_t * AsString (Detector_t detector)
Detector::Detector_t CharToEnum (Char_t c)
Char_t * MaskToString (Int_t mask)
Detector::Detector_t StringToEnum (const Char_t *chars, Int_t maxChar=0)
Int_t StringToMask (const Char_t *chars, Int_t maxChar=0)
Typedef Documentation
typedef enum Detector::EDetector Detector::Detector_t
Enumeration Type Documentation
enum Detector::EDetector
Enumerator:
kUnknown
kCal
kCalCrystal
kDch
kGfi
kLand
kMtof
kTof
kTracker
Definition at line 22 of file Detector.h.
View newest version in sPHENIX GitHub at line 22 of file Detector.h
Function Documentation
const Char_t * Detector::AsString (Detector_t detector)
Definition at line 10 of file Detector.cxx.
View newest version in sPHENIX GitHub at line 10 of file Detector.cxx
References kCal, kCalCrystal, kDch, kGfi, kLand, kMtof, kTof, kTracker, and kUnknown.
Referenced by ValContext::AsString(), Smear::Device::Device(), Smear::FormulaString::FormulaString(), Smear::Device::Init(), and MaskToString().
Detector::Detector_t Detector::CharToEnum (Char_t c)
Definition at line 47 of file Detector.cxx.
View newest version in sPHENIX GitHub at line 47 of file Detector.cxx
References kCal, kCalCrystal, kDch, kGfi, kLand, kMtof, kTof, kTracker, and kUnknown.
Int_t Detector::FullMask ()
Definition at line 5 of file Detector.cxx.
View newest version in sPHENIX GitHub at line 5 of file Detector.cxx
References kCal, kCalCrystal, kDch, kGfi, kLand, kMtof, kTof, and kTracker.
Referenced by MaskToString(), and FairDbLogEntry::Recreate().
Char_t * Detector::MaskToString (Int_t mask)
Definition at line 88 of file Detector.cxx.
View newest version in sPHENIX GitHub at line 88 of file Detector.cxx
References AsString(), and FullMask().
Referenced by ValRange::AsString().
Detector::Detector_t Detector::StringToEnum (const Char_t * chars, Int_t maxChar = 0)
Definition at line 118 of file Detector.cxx.
View newest version in sPHENIX GitHub at line 118 of file Detector.cxx
References kCal, kCalCrystal, kDch, kGfi, kLand, kMtof, kTof, kTracker, kUnknown, and StringToMask().
Int_t Detector::StringToMask (const Char_t * chars, Int_t maxChar = 0)
Definition at line 160 of file Detector.cxx.
View newest version in sPHENIX GitHub at line 160 of file Detector.cxx
References kCal, kCalCrystal, kDch, kGfi, kLand, kMtof, kTof, and kTracker.
Referenced by StringToEnum().