EIC Software: delphes_EIC/blob/master/SimpleAnalysis/SimpleAnalysis.cc File Reference
SimpleAnalysis.cc File Reference
#include <TROOT.h>
#include <TFile.h>
#include <TChain.h>
#include <TTree.h>
#include <TString.h>
#include <TObjString.h>
#include "TInterpreter.h"
#include <unistd.h>
#include <stdlib.h>
#include <iostream>
#include <stdio.h>
#include <getopt.h>
#include <glob.h>
#include <vector>
#include <map>
#include <any>
#include "classes/DelphesClasses.h"
#include "external/ExRootAnalysis/ExRootTreeReader.h"
#include "ModuleHandler.h"
#include "TreeHandler.h"
Functions
void PrintHelp ()
std::vector< std::string > fileVector (const std::string &pattern)
int main (int argc, char *argv[])
Variables
static std::string input_dir = ""
static std::string output_file = ""
static std::string module_sequence = ""
static int nevents = -1
Function Documentation
std::vector<std::string> fileVector (const std::string & pattern)
Definition at line 47 of file SimpleAnalysis.cc.
View newest version in sPHENIX GitHub at line 47 of file SimpleAnalysis.cc
References eicpy.build::files.
int main (int argc, char * argv[])
Definition at line 61 of file SimpleAnalysis.cc.
View newest version in sPHENIX GitHub at line 61 of file SimpleAnalysis.cc
References ModuleHandler::addModule(), data, TreeHandler::execute(), exit(), eicpy.qaplots::file, eicpy.build::files, fileVector(), TreeHandler::finalize(), TreeHandler::getInstance(), ModuleHandler::getInstance(), ModuleHandler::getModules(), TreeHandler::initialize(), input_dir, module_sequence, name, nevents, output_file, and PrintHelp().
void PrintHelp ()
Definition at line 36 of file SimpleAnalysis.cc.
View newest version in sPHENIX GitHub at line 36 of file SimpleAnalysis.cc
References exit().
Referenced by main().
Variable Documentation
std::string input_dir = "" static
Definition at line 25 of file SimpleAnalysis.cc.
View newest version in sPHENIX GitHub at line 25 of file SimpleAnalysis.cc
Referenced by main().
std::string module_sequence = "" static
Definition at line 27 of file SimpleAnalysis.cc.
View newest version in sPHENIX GitHub at line 27 of file SimpleAnalysis.cc
Referenced by ModuleHandler::addModule(), ModuleHandler::getModules(), main(), and ModuleHandler::ModuleHandler().
int nevents = -1 static
Definition at line 28 of file SimpleAnalysis.cc.
View newest version in sPHENIX GitHub at line 28 of file SimpleAnalysis.cc
Referenced by main(), pprocess(), pstart(), Fun4AllPrdfInputManager::PushBackEvents(), Fun4AllHepMCInputManager::PushBackEvents(), Fun4AllHepMCPileupInputManager::run(), Fun4AllDummyInputManager::run(), runLCELoop(), and Fun4AllHepMCPileupInputManager::SkipForThisManager().
std::string output_file = "" static
Definition at line 26 of file SimpleAnalysis.cc.
View newest version in sPHENIX GitHub at line 26 of file SimpleAnalysis.cc
Referenced by DelphesSkim(), and main().