EIC Software: EicCalorimeterReconstruction Class Reference
EicCalorimeterReconstruction Class Reference
#include <EicRoot/blob/master/eic/calorimetry/EicCalorimeterReconstruction.h>
Public Member Functions
EicCalorimeterReconstruction ()
EicCalorimeterReconstruction (TString name)
~EicCalorimeterReconstruction ()
void ResetVars ()
InitStatus Init ()
void Exec (Option_t *option)
void AddNeighbors (CalorimeterCellGroup &group, std::multimap< UInt_t, EicCalorimeterDigiHit * >::reverse_iterator it)
bool AreNeighbors (EicCalorimeterDigiHit *h1, EicCalorimeterDigiHit *h2)
void SetClusterAlgorithmThresholds (Double_t clusterSeedThreshold, Double_t neighbourSearchThreshold, Double_t cellAccountingThreshold)
void SetPhotonToEnergyConversionFactor (double factor)
void RequestLightYieldPlot (unsigned nMax=_DEFAULT_LIGHT_YIELD_PLOT_MAX_, unsigned nBins=_DEFAULT_LIGHT_YIELD_PLOT_NBINS_)
virtual void Finish ()
Public Member Functions inherited from FairTask
FairTask ()
FairTask (const char *name, Int_t iVerbose=1)
virtual ~FairTask ()
void InitTask ()
void ReInitTask ()
void SetParTask ()
virtual void FinishTask ()
virtual void FinishEvent ()
void SetVerbose (Int_t iVerbose)
void SetInputPersistance (Bool_t val)
void CheckInputPersistance (TString branchName)
Protected Member Functions
ClassDef (EicCalorimeterReconstruction, 10)
Protected Member Functions inherited from FairTask
virtual InitStatus ReInit ()
virtual void SetParContainers ()
void InitTasks ()
void ReInitTasks ()
void SetParTasks ()
void FinishTasks ()
void FinishEvents ()
Protected Attributes
EicDetName * mDetName
EicGeoParData * mGptr
CalorimeterDigiParData * mDigi
TClonesArray * mDigiHits
TClonesArray * mClusterGroupArray
array of digi hits (input)
std::multimap< UInt_t,
EicCalorimeterDigiHit * > hmap
array of reco hits (output)
std::vector< CalorimeterCellGroup > mCellGroups
TH1F * mLightYieldPlot
unsigned mLightYieldPlotMax
unsigned mLightYieldPlotNbins
CalorimeterRecoParData * mReco
Bool_t mLightYieldPlotRequested
Protected Attributes inherited from FairTask
Int_t fVerbose
Int_t fInputPersistance
Indicates if input branch is persistant.
FairLogger * fLogger
Detailed Description
Definition at line 64 of file EicCalorimeterReconstruction.h.
View newest version in sPHENIX GitHub at line 64 of file EicCalorimeterReconstruction.h
Constructor & Destructor Documentation
EicCalorimeterReconstruction::EicCalorimeterReconstruction () inline
Definition at line 66 of file EicCalorimeterReconstruction.h.
View newest version in sPHENIX GitHub at line 66 of file EicCalorimeterReconstruction.h
References ResetVars().
EicCalorimeterReconstruction::EicCalorimeterReconstruction (TString name)
Definition at line 16 of file EicCalorimeterReconstruction.cxx.
View newest version in sPHENIX GitHub at line 16 of file EicCalorimeterReconstruction.cxx
References mDetName, mReco, and ResetVars().
EicCalorimeterReconstruction::~EicCalorimeterReconstruction () inline
Definition at line 69 of file EicCalorimeterReconstruction.h.
View newest version in sPHENIX GitHub at line 69 of file EicCalorimeterReconstruction.h
Member Function Documentation
void EicCalorimeterReconstruction::AddNeighbors (CalorimeterCellGroup & group, std::multimap< UInt_t, EicCalorimeterDigiHit * >::reverse_iterator it)
Definition at line 241 of file EicCalorimeterReconstruction.cxx.
View newest version in sPHENIX GitHub at line 241 of file EicCalorimeterReconstruction.cxx
References AreNeighbors(), hmap, CalorimeterCellGroup::mCells, CalorimeterCell::mEstimatedEnergyDeposit, CalorimeterRecoParData::mNeighbourSearchThreshold, EicCalorimeterDigiHit::mPtrCell, mReco, and EicCalorimeterDigiHit::mUsed.
Referenced by Exec().
bool EicCalorimeterReconstruction::AreNeighbors (EicCalorimeterDigiHit * h1, EicCalorimeterDigiHit * h2)
Definition at line 268 of file EicCalorimeterReconstruction.cxx.
View newest version in sPHENIX GitHub at line 268 of file EicCalorimeterReconstruction.cxx
References EicGeoParData::AreNeighbours(), EicCalorimeterDigiHit::mCoord, and mGptr.
Referenced by AddNeighbors().
EicCalorimeterReconstruction::ClassDef (EicCalorimeterReconstruction , 10) protected
void EicCalorimeterReconstruction::Exec (Option_t * option)
Definition at line 101 of file EicCalorimeterReconstruction.cxx.
View newest version in sPHENIX GitHub at line 101 of file EicCalorimeterReconstruction.cxx
References AddNeighbors(), CalorimeterDigiParData::APD, CalorimeterCell::GetPhotonCountSum(), EicGeoParData::GetX(), EicGeoParData::GetY(), hmap, it, CalorimeterRecoParData::mCellAccountingThreshold, mCellGroups, CalorimeterCell::mCellParents, CalorimeterCellGroup::mCells, mClusterGroupArray, CalorimeterRecoParData::mClusterSeedThreshold, EicCalorimeterDigiHit::mCoord, mDigi, mDigiHits, CalorimeterCellGroup::mEnergy, CalorimeterCellGroup::mEnergyPerParent, CalorimeterCell::mEstimatedEnergyDeposit, mGptr, mLightYieldPlot, CalorimeterRecoParData::mPhotonToEnergyConversionFactor, EicCalorimeterDigiHit::mPtrCell, mReco, CalorimeterDigiParData::mSensorType, CalorimeterCellParent::mSignalPhotonCount, CalorimeterDigiParData::mSipmSingleCellNoiseLevel, CalorimeterDigiParData::mTimingGateWidth, EicCalorimeterDigiHit::mUsed, printf(), and CalorimeterDigiParData::SiPM.
void EicCalorimeterReconstruction::Finish () virtual
Action after each event. To be implemented in the derived class
Reimplemented from FairTask.
Definition at line 278 of file EicCalorimeterReconstruction.cxx.
View newest version in sPHENIX GitHub at line 278 of file EicCalorimeterReconstruction.cxx
References FairRun::GetOutputFile(), FairRun::Instance(), mDetName, mLightYieldPlot, mReco, and EicDetName::Name().
InitStatus EicCalorimeterReconstruction::Init () virtual
Intialisation at begin of run. To be implemented in the derived class. Success If not kSUCCESS, task will be set inactive.
Reimplemented from FairTask.
Definition at line 28 of file EicCalorimeterReconstruction.cxx.
View newest version in sPHENIX GitHub at line 28 of file EicCalorimeterReconstruction.cxx
References EicRunAna::GetFriendFiles(), EicRunAna::GetInputFileName(), FairRootManager::GetObject(), EicRunAna::Instance(), FairRootManager::Instance(), kERROR, kSUCCESS, CalorimeterRecoParData::mCellAccountingThreshold, mClusterGroupArray, CalorimeterRecoParData::mClusterSeedThreshold, mDetName, mDigi, mDigiHits, mGptr, mLightYieldPlot, mLightYieldPlotMax, mLightYieldPlotNbins, mLightYieldPlotRequested, CalorimeterRecoParData::mNeighbourSearchThreshold, mReco, EicDetName::NAME(), EicDetName::Name(), and FairRootManager::Register().
void EicCalorimeterReconstruction::RequestLightYieldPlot (unsigned nMax = _DEFAULT_LIGHT_YIELD_PLOT_MAX_, unsigned nBins = _DEFAULT_LIGHT_YIELD_PLOT_NBINS_) inline
Definition at line 98 of file EicCalorimeterReconstruction.h.
View newest version in sPHENIX GitHub at line 98 of file EicCalorimeterReconstruction.h
References mLightYieldPlotMax, mLightYieldPlotNbins, and mLightYieldPlotRequested.
Referenced by reconstruction().
void EicCalorimeterReconstruction::ResetVars () inline
Definition at line 71 of file EicCalorimeterReconstruction.h.
View newest version in sPHENIX GitHub at line 71 of file EicCalorimeterReconstruction.h
References _DEFAULT_LIGHT_YIELD_PLOT_MAX_, _DEFAULT_LIGHT_YIELD_PLOT_NBINS_, mDigi, mGptr, mLightYieldPlot, mLightYieldPlotMax, mLightYieldPlotNbins, mLightYieldPlotRequested, and mReco.
Referenced by EicCalorimeterReconstruction().
void EicCalorimeterReconstruction::SetClusterAlgorithmThresholds (Double_t clusterSeedThreshold, Double_t neighbourSearchThreshold, Double_t cellAccountingThreshold) inline
Definition at line 87 of file EicCalorimeterReconstruction.h.
View newest version in sPHENIX GitHub at line 87 of file EicCalorimeterReconstruction.h
References CalorimeterRecoParData::mCellAccountingThreshold, CalorimeterRecoParData::mClusterSeedThreshold, CalorimeterRecoParData::mNeighbourSearchThreshold, and mReco.
Referenced by reconstruction().
void EicCalorimeterReconstruction::SetPhotonToEnergyConversionFactor (double factor) inline
Definition at line 94 of file EicCalorimeterReconstruction.h.
View newest version in sPHENIX GitHub at line 94 of file EicCalorimeterReconstruction.h
References CalorimeterRecoParData::mPhotonToEnergyConversionFactor, and mReco.
Referenced by reconstruction().
Member Data Documentation
std::multimap<UInt_t,EicCalorimeterDigiHit*> EicCalorimeterReconstruction::hmap protected
array of reco hits (output)
Definition at line 120 of file EicCalorimeterReconstruction.h.
View newest version in sPHENIX GitHub at line 120 of file EicCalorimeterReconstruction.h
Referenced by AddNeighbors(), and Exec().
std::vector<CalorimeterCellGroup> EicCalorimeterReconstruction::mCellGroups protected
Definition at line 122 of file EicCalorimeterReconstruction.h.
View newest version in sPHENIX GitHub at line 122 of file EicCalorimeterReconstruction.h
Referenced by Exec().
TClonesArray* EicCalorimeterReconstruction::mClusterGroupArray protected
array of digi hits (input)
Definition at line 117 of file EicCalorimeterReconstruction.h.
View newest version in sPHENIX GitHub at line 117 of file EicCalorimeterReconstruction.h
Referenced by Exec(), and Init().
EicDetName* EicCalorimeterReconstruction::mDetName protected
Definition at line 109 of file EicCalorimeterReconstruction.h.
View newest version in sPHENIX GitHub at line 109 of file EicCalorimeterReconstruction.h
Referenced by EicCalorimeterReconstruction(), Finish(), and Init().
CalorimeterDigiParData* EicCalorimeterReconstruction::mDigi protected
Definition at line 112 of file EicCalorimeterReconstruction.h.
View newest version in sPHENIX GitHub at line 112 of file EicCalorimeterReconstruction.h
Referenced by Exec(), Init(), and ResetVars().
TClonesArray* EicCalorimeterReconstruction::mDigiHits protected
Definition at line 114 of file EicCalorimeterReconstruction.h.
View newest version in sPHENIX GitHub at line 114 of file EicCalorimeterReconstruction.h
Referenced by Exec(), and Init().
EicGeoParData* EicCalorimeterReconstruction::mGptr protected
Definition at line 111 of file EicCalorimeterReconstruction.h.
View newest version in sPHENIX GitHub at line 111 of file EicCalorimeterReconstruction.h
Referenced by AreNeighbors(), Exec(), Init(), and ResetVars().
TH1F* EicCalorimeterReconstruction::mLightYieldPlot protected
Definition at line 124 of file EicCalorimeterReconstruction.h.
View newest version in sPHENIX GitHub at line 124 of file EicCalorimeterReconstruction.h
Referenced by Exec(), Finish(), Init(), and ResetVars().
unsigned EicCalorimeterReconstruction::mLightYieldPlotMax protected
Definition at line 125 of file EicCalorimeterReconstruction.h.
View newest version in sPHENIX GitHub at line 125 of file EicCalorimeterReconstruction.h
Referenced by Init(), RequestLightYieldPlot(), and ResetVars().
unsigned EicCalorimeterReconstruction::mLightYieldPlotNbins protected
Definition at line 125 of file EicCalorimeterReconstruction.h.
View newest version in sPHENIX GitHub at line 125 of file EicCalorimeterReconstruction.h
Referenced by Init(), RequestLightYieldPlot(), and ResetVars().
Bool_t EicCalorimeterReconstruction::mLightYieldPlotRequested protected
Definition at line 130 of file EicCalorimeterReconstruction.h.
View newest version in sPHENIX GitHub at line 130 of file EicCalorimeterReconstruction.h
Referenced by Init(), RequestLightYieldPlot(), and ResetVars().
CalorimeterRecoParData* EicCalorimeterReconstruction::mReco protected
Definition at line 128 of file EicCalorimeterReconstruction.h.
View newest version in sPHENIX GitHub at line 128 of file EicCalorimeterReconstruction.h
Referenced by AddNeighbors(), EicCalorimeterReconstruction(), Exec(), Finish(), Init(), ResetVars(), SetClusterAlgorithmThresholds(), and SetPhotonToEnergyConversionFactor().
The documentation for this class was generated from the following files:
EicRoot/blob/master/eic/calorimetry/EicCalorimeterReconstruction.h
EicRoot/blob/master/eic/calorimetry/EicCalorimeterReconstruction.cxx