EIC Software: BasicDetectorConstruction Class Reference
BasicDetectorConstruction Class Reference
Public Member Functions
BasicDetectorConstruction ()
~BasicDetectorConstruction ()
G4VPhysicalVolume * Construct ()
BasicDetectorConstruction ()
~BasicDetectorConstruction ()
G4VPhysicalVolume * Construct ()
Detailed Description
Definition at line 23 of file main.cc.
View newest version in sPHENIX GitHub at line 23 of file main.cc
Constructor & Destructor Documentation
BasicDetectorConstruction::BasicDetectorConstruction () inline
Definition at line 25 of file main.cc.
View newest version in sPHENIX GitHub at line 25 of file main.cc
BasicDetectorConstruction::~BasicDetectorConstruction () inline
Definition at line 26 of file main.cc.
View newest version in sPHENIX GitHub at line 26 of file main.cc
BasicDetectorConstruction::BasicDetectorConstruction () inline
Definition at line 18 of file main.cc.
View newest version in sPHENIX GitHub at line 18 of file main.cc
BasicDetectorConstruction::~BasicDetectorConstruction () inline
Definition at line 19 of file main.cc.
View newest version in sPHENIX GitHub at line 19 of file main.cc
Member Function Documentation
G4VPhysicalVolume* BasicDetectorConstruction::Construct () inline
Definition at line 21 of file main.cc.
View newest version in sPHENIX GitHub at line 21 of file main.cc
References MuMegasGeoParData::AddBarrel(), VstGeoParData::AddBarrelLayer(), GemGeoParData::AddWheel(), bck(), eic, exit(), fwd(), ibcell, EicToyModel::Instance(), G4TTL::layer, mid, etm::mm, g4::mm, EicGeoParData::PlaceG4Volume(), EicGeoParData::SetTransparency(), and vst().
G4VPhysicalVolume* BasicDetectorConstruction::Construct () inline
Definition at line 28 of file main.cc.
View newest version in sPHENIX GitHub at line 28 of file main.cc
References eic, exit(), EicToyModel::Instance(), it, printf(), and G4GDMLParser::Read().
The documentation for this class was generated from the following files:
EicToyModel/blob/master/examples/basic/main.cc
EicToyModel/blob/master/examples/eicroot/main.cc