EIC Software: fun4all_eicmacros/blob/master/detectors/AllSilicon/Development/Fun4All_G4_sPHENIX_particle_gen.C File Reference
Fun4All_G4_sPHENIX_particle_gen.C File Reference
#include <phool/PHRandomSeed.h>
#include <fun4all/SubsysReco.h>
#include <fun4all/Fun4AllServer.h>
#include <fun4all/Fun4AllInputManager.h>
#include <fun4all/Fun4AllDummyInputManager.h>
#include <fun4all/Fun4AllOutputManager.h>
#include <fun4all/Fun4AllDstInputManager.h>
#include <fun4all/Fun4AllNoSyncDstInputManager.h>
#include <fun4all/Fun4AllDstOutputManager.h>
#include <g4main/PHG4ParticleGeneratorBase.h>
#include <g4main/PHG4ParticleGenerator.h>
#include <g4main/HepMCNodeReader.h>
#include <g4detectors/PHG4DetectorSubsystem.h>
#include <phool/recoConsts.h>
#include "G4Setup_sPHENIX.C"
#include "G4_Global.C"
#include "G4_DSTReader.C"
#include "DisplayOn.C"
Functions
int Fun4All_G4_sPHENIX_particle_gen (const int nEvents=1, const char *outputFile="G4sPHENIX.root", const char *genpar="pi-")
Function Documentation
int Fun4All_G4_sPHENIX_particle_gen (const int nEvents = 1, const char * outputFile = "G4sPHENIX.root", const char * genpar = "pi-")
Definition at line 29 of file Fun4All_G4_sPHENIX_particle_gen.C.
View newest version in sPHENIX GitHub at line 29 of file Fun4All_G4_sPHENIX_particle_gen.C
References DisplayOn(), Fun4AllServer::End(), G4Init(), G4Setup(), Global_FastSim(), in, recoConsts::instance(), Fun4AllServer::instance(), kAll, magfield, G4MAGNET::magfield_rescale, nEvents, Fun4AllServer::registerInputManager(), Fun4AllServer::registerSubsystem(), Fun4AllServer::run(), PHG4ParticleGenerator::set_eta_range(), PHG4ParticleGenerator::set_mom_range(), PHG4ParticleGeneratorBase::set_name(), PHG4ParticleGenerator::set_phi_range(), PHG4ParticleGeneratorBase::set_vtx(), PHG4ParticleGenerator::set_z_range(), Tracking_Eval(), Tracking_Reco(), and Fun4AllBase::Verbosity().