EIC Software: Dipole Class Reference
Dipole Class Reference
Public Member Functions
Dipole (std::string name, double angle)
~Dipole ()
double GetField (void) const
void Calculate (double Brho)
void Print (void)
Public Member Functions inherited from MagElement
MagElement (std::string name)
~MagElement ()
virtual double GetGradient (void) const
virtual void WriteOut (FILE *fout)
Public Attributes
double mANGLE
double mField
Public Attributes inherited from MagElement
std::string mName
double mApertureRadiusZin
double mApertureRadiusZout
double mOutsideDiameter
double mSstart
double mSend
double mTHETAstart
double mTHETAend
double mXstart
double mYstart
double mZstart
double mXend
double mYend
double mZend
double mLength
double mX
double mY
double mZ
double mTHETA
Detailed Description
Definition at line 89 of file extractor.cc.
View newest version in sPHENIX GitHub at line 89 of file extractor.cc
Constructor & Destructor Documentation
Dipole::Dipole (std::string name, double angle) inline
Definition at line 91 of file extractor.cc.
View newest version in sPHENIX GitHub at line 91 of file extractor.cc
Dipole::~Dipole () inline
Definition at line 92 of file extractor.cc.
View newest version in sPHENIX GitHub at line 92 of file extractor.cc
Member Function Documentation
void Dipole::Calculate (double Brho) inline virtual
Implements MagElement.
Definition at line 95 of file extractor.cc.
View newest version in sPHENIX GitHub at line 95 of file extractor.cc
double Dipole::GetField (void) const inline virtual
Reimplemented from MagElement.
Definition at line 94 of file extractor.cc.
View newest version in sPHENIX GitHub at line 94 of file extractor.cc
void Dipole::Print (void) inline virtual
Reimplemented from MagElement.
Definition at line 96 of file extractor.cc.
View newest version in sPHENIX GitHub at line 96 of file extractor.cc
References MagElement::Print(), and printf().
Referenced by main().
Member Data Documentation
double Dipole::mANGLE
Definition at line 96 of file extractor.cc.
View newest version in sPHENIX GitHub at line 96 of file extractor.cc
double Dipole::mField
Definition at line 100 of file extractor.cc.
View newest version in sPHENIX GitHub at line 100 of file extractor.cc
The documentation for this class was generated from the following file:
EicRoot/blob/master/pCDR-2018/madx/extractor.cc