EIC Software: eicsmeardetectors/blob/master/SmearSTAR_0_0.cxx File Reference
SmearSTAR_0_0.cxx File Reference
#include "eicsmear/erhic/VirtualParticle.h"
#include "eicsmear/smear/Acceptance.h"
#include "eicsmear/smear/Device.h"
#include "eicsmear/smear/Detector.h"
#include "eicsmear/smear/Smearer.h"
#include "eicsmear/smear/ParticleMCS.h"
#include "eicsmear/smear/PerfectID.h"
#include <eicsmear/smear/Smear.h>
#include <eicsmear/erhic/ParticleMC.h>
Functions
static double etaToTheta (const double eta)
static Smear::Acceptance::Zone makeZone (double etaMin, double etaMax)
Smear::Detector BuildSTAR_0_0 ()
Detailed Description
Example smearing script for the STAR detector
Author
Thomas Burton
Date
2014-01-10
Copyright
2014 Brookhaven National Lab
Definition in file SmearSTAR_0_0.cxx.
Function Documentation
Smear::Detector BuildSTAR_0_0 ()
Smearing parameterisations for the STAR detector.
These parameterisations are non-exhaustive: they do not cover elements such as particle identification, and they are only for the central elements of the detector - essentially, just TPC and B/EEMC.
Note: you must gSystem->Load("libeicsmear") BEFORE loading this script, as ROOT needs to understand what a Smear::Detector is.
Definition at line 52 of file SmearSTAR_0_0.cxx.
View newest version in sPHENIX GitHub at line 52 of file SmearSTAR_0_0.cxx
References Smear::Smearer::Accept, Smear::Detector::AddDevice(), Smear::Acceptance::AddZone(), Smear::kCharged, Smear::kE, Smear::kElectromagnetic, Smear::kP, Smear::kPhi, Smear::kTheta, makeZone(), momentum, phi, Smear::Acceptance::SetCharge(), Smear::Detector::SetEventKinematicsCalculator(), star(), and theta().
Referenced by BuildByName().
static double etaToTheta (const double eta) static
Convert pseudorapidity (eta) to polar angle (theta) in radians. Make use of TLorentzVector to do eta-to-theta conversion.
Definition at line 25 of file SmearSTAR_0_0.cxx.
View newest version in sPHENIX GitHub at line 25 of file SmearSTAR_0_0.cxx
References v.
static Smear::Acceptance::Zone makeZone (double etaMin, double etaMax) static
Returns an Acceptance::Zone spanning a range in eta.
Definition at line 34 of file SmearSTAR_0_0.cxx.
View newest version in sPHENIX GitHub at line 34 of file SmearSTAR_0_0.cxx
References etaToTheta().
Referenced by BuildSTAR_0_0().