EIC Software: Acts::GeometryID Class Reference
Acts::GeometryID Class Reference
#include <fun4all_acts/blob/master/Core/include/Acts/Geometry/GeometryID.hpp>
Public Types
using Value = uint64_t
using Value = uint64_t
Public Member Functions
constexpr GeometryID (Value encoded)
Construct from an already encoded value.
GeometryID ()=default
Construct default GeometryID with all values set to zero.
GeometryID (GeometryID &&)=default
GeometryID (const GeometryID &)=default
~GeometryID ()=default
GeometryID & operator= (GeometryID &&)=default
GeometryID & operator= (const GeometryID &)=default
constexpr Value value () const
Return the encoded value.
constexpr Value volume () const
Return the volume identifier.
constexpr Value boundary () const
Return the boundary identifier.
constexpr Value layer () const
Return the layer identifier.
constexpr Value approach () const
Return the approach identifier.
constexpr Value sensitive () const
Return the sensitive identifier.
constexpr GeometryID & setVolume (Value volume)
Set the volume identifier.
constexpr GeometryID & setBoundary (Value boundary)
Set the boundary identifier.
constexpr GeometryID & setLayer (Value layer)
Set the layer identifier.
constexpr GeometryID & setApproach (Value approach)
Set the approach identifier.
constexpr GeometryID & setSensitive (Value sensitive)
Set the sensitive identifier.
constexpr GeometryID (Value encoded)
Construct from an already encoded value.
GeometryID ()=default
Construct default GeometryID with all values set to zero.
GeometryID (GeometryID &&)=default
GeometryID (const GeometryID &)=default
~GeometryID ()=default
GeometryID & operator= (GeometryID &&)=default
GeometryID & operator= (const GeometryID &)=default
constexpr Value value () const
Return the encoded value.
constexpr Value volume () const
Return the volume identifier.
constexpr Value boundary () const
Return the boundary identifier.
constexpr Value layer () const
Return the layer identifier.
constexpr Value approach () const
Return the approach identifier.
constexpr Value sensitive () const
Return the sensitive identifier.
Private Member Functions
constexpr Value getBits (Value mask) const
Extract the masked bits from the encoded value.
constexpr GeometryID & setBits (Value mask, Value id)
Set the masked bits to id in the encoded value.
constexpr Value getBits (Value mask) const
Extract the masked bits from the encoded value.
Static Private Member Functions
static constexpr int extractShift (Value mask)
Extract the bit shift necessary to access the masked values.
static constexpr int extractShift (Value mask)
Extract the bit shift necessary to access the masked values.
Private Attributes
Value m_value = 0
Static Private Attributes
static constexpr Value kVolumeMask = 0xff00000000000000
static constexpr Value kBoundaryMask = 0x00ff000000000000
static constexpr Value kLayerMask = 0x0000fff000000000
static constexpr Value kApproachMask = 0x0000000ff0000000
static constexpr Value kSensitiveMask = 0x000000000fffffff
static constexpr Value volume_mask = 0xff00000000000000
static constexpr Value boundary_mask = 0x00ff000000000000
static constexpr Value layer_mask = 0x0000fff000000000
static constexpr Value approach_mask = 0x0000000ff0000000
static constexpr Value sensitive_mask = 0x000000000fffffff
Friends
constexpr bool operator== (GeometryID lhs, GeometryID rhs)
constexpr bool operator< (GeometryID lhs, GeometryID rhs)
constexpr bool operator== (GeometryID lhs, GeometryID rhs)
constexpr bool operator< (GeometryID lhs, GeometryID rhs)
Detailed Description
Identifier for geometry nodes within the geometry hierarchy.
An identifier can be split into the following components. They define a hierarchy of objects starting from the high-level volumes:
Volume
Boundary surfaces (for a volume)
Layers (confined within a volume)
Approach surfaces (for a layer)
Sensitive surfaces (confined to a layer, also called modules)
Reimplementation of GeometryID du to the fact that the default Root C++ version is too old Identifier for geometry nodes.
Each identifier can be split info the following components:
Volumes - uses counting given by TrackingGeometry
(Boundary) Surfaces - counts through boundary surfaces
(Layer) Surfaces - counts confined layers
(Approach) Surfaces - counts approach surfaces
(Sensitive) Surfaces - counts through sensitive surfaces
Definition at line 28 of file GeometryID.hpp.
View newest version in sPHENIX GitHub at line 28 of file GeometryID.hpp
Member Typedef Documentation
using Acts::GeometryID::Value = uint64_t
Definition at line 29 of file materialPlotHelper.hpp.
View newest version in sPHENIX GitHub at line 29 of file materialPlotHelper.hpp
using Acts::GeometryID::Value = uint64_t
Definition at line 30 of file GeometryID.hpp.
View newest version in sPHENIX GitHub at line 30 of file GeometryID.hpp
Constructor & Destructor Documentation
constexpr Acts::GeometryID::GeometryID (Value encoded) inline
Construct from an already encoded value.
Definition at line 33 of file GeometryID.hpp.
View newest version in sPHENIX GitHub at line 33 of file GeometryID.hpp
Acts::GeometryID::GeometryID () default
Construct default GeometryID with all values set to zero.
Acts::GeometryID::GeometryID (GeometryID &&) default
Acts::GeometryID::GeometryID (const GeometryID &) default
Acts::GeometryID::~GeometryID () default
constexpr Acts::GeometryID::GeometryID (Value encoded) inline
Construct from an already encoded value.
Definition at line 32 of file materialPlotHelper.hpp.
View newest version in sPHENIX GitHub at line 32 of file materialPlotHelper.hpp
Acts::GeometryID::GeometryID () default
Construct default GeometryID with all values set to zero.
Acts::GeometryID::GeometryID (GeometryID &&) default
Acts::GeometryID::GeometryID (const GeometryID &) default
Acts::GeometryID::~GeometryID () default
Member Function Documentation
constexpr Value Acts::GeometryID::approach () const inline
Return the approach identifier.
Definition at line 51 of file materialPlotHelper.hpp.
View newest version in sPHENIX GitHub at line 51 of file materialPlotHelper.hpp
References approach_mask, and getBits().
constexpr Value Acts::GeometryID::approach () const inline
Return the approach identifier.
Definition at line 52 of file GeometryID.hpp.
View newest version in sPHENIX GitHub at line 52 of file GeometryID.hpp
References getBits(), and kApproachMask.
Referenced by Acts::JsonGeometryConverter::convertToRep(), and FW::RootMaterialWriter::write().
constexpr Value Acts::GeometryID::boundary () const inline
Return the boundary identifier.
Definition at line 47 of file materialPlotHelper.hpp.
View newest version in sPHENIX GitHub at line 47 of file materialPlotHelper.hpp
References boundary_mask, and getBits().
constexpr Value Acts::GeometryID::boundary () const inline
Return the boundary identifier.
Definition at line 48 of file GeometryID.hpp.
View newest version in sPHENIX GitHub at line 48 of file GeometryID.hpp
References getBits(), and kBoundaryMask.
Referenced by Acts::JsonGeometryConverter::convertToRep(), and FW::RootMaterialWriter::write().
static constexpr int Acts::GeometryID::extractShift (Value mask) inline static private
Extract the bit shift necessary to access the masked values.
Definition at line 67 of file materialPlotHelper.hpp.
View newest version in sPHENIX GitHub at line 67 of file materialPlotHelper.hpp
static constexpr int Acts::GeometryID::extractShift (Value mask) inline static private
Extract the bit shift necessary to access the masked values.
Definition at line 92 of file GeometryID.hpp.
View newest version in sPHENIX GitHub at line 92 of file GeometryID.hpp
Referenced by getBits(), and setBits().
constexpr Value Acts::GeometryID::getBits (Value mask) const inline private
Extract the masked bits from the encoded value.
Definition at line 75 of file materialPlotHelper.hpp.
View newest version in sPHENIX GitHub at line 75 of file materialPlotHelper.hpp
References extractShift(), and m_value.
constexpr Value Acts::GeometryID::getBits (Value mask) const inline private
Extract the masked bits from the encoded value.
Definition at line 100 of file GeometryID.hpp.
View newest version in sPHENIX GitHub at line 100 of file GeometryID.hpp
References extractShift(), and m_value.
Referenced by approach(), boundary(), layer(), sensitive(), and volume().
constexpr Value Acts::GeometryID::layer () const inline
Return the layer identifier.
Definition at line 49 of file materialPlotHelper.hpp.
View newest version in sPHENIX GitHub at line 49 of file materialPlotHelper.hpp
References getBits(), and layer_mask.
constexpr Value Acts::GeometryID::layer () const inline
Return the layer identifier.
Definition at line 50 of file GeometryID.hpp.
View newest version in sPHENIX GitHub at line 50 of file GeometryID.hpp
References getBits(), and kLayerMask.
Referenced by Acts::JsonGeometryConverter::convertToRep(), FW::Obj::ObjSurfaceWriter::write(), FW::RootMaterialWriter::write(), FW::CsvPlanarClusterWriter::writeT(), and FW::RootPlanarClusterWriter::writeT().
GeometryID& Acts::GeometryID::operator= (GeometryID &&) default
GeometryID& Acts::GeometryID::operator= (GeometryID &&) default
GeometryID& Acts::GeometryID::operator= (const GeometryID &) default
GeometryID& Acts::GeometryID::operator= (const GeometryID &) default
constexpr Value Acts::GeometryID::sensitive () const inline
Return the sensitive identifier.
Definition at line 53 of file materialPlotHelper.hpp.
View newest version in sPHENIX GitHub at line 53 of file materialPlotHelper.hpp
References getBits(), and sensitive_mask.
constexpr Value Acts::GeometryID::sensitive () const inline
Return the sensitive identifier.
Definition at line 54 of file GeometryID.hpp.
View newest version in sPHENIX GitHub at line 54 of file GeometryID.hpp
References getBits(), and kSensitiveMask.
Referenced by Acts::JsonGeometryConverter::convertToRep(), FW::RootMaterialWriter::write(), FW::CsvPlanarClusterWriter::writeT(), and FW::RootPlanarClusterWriter::writeT().
constexpr GeometryID& Acts::GeometryID::setApproach (Value approach) inline
Set the approach identifier.
Definition at line 69 of file GeometryID.hpp.
View newest version in sPHENIX GitHub at line 69 of file GeometryID.hpp
References kApproachMask, and setBits().
Referenced by Acts::Layer::closeGeometry(), Acts::JsonGeometryConverter::jsonToMaterialMaps(), FW::RootMaterialDecorator::RootMaterialDecorator(), and FW::RootMaterialTrackWriter::writeT().
constexpr GeometryID& Acts::GeometryID::setBits (Value mask, Value id) inline private
Set the masked bits to id in the encoded value.
Definition at line 104 of file GeometryID.hpp.
View newest version in sPHENIX GitHub at line 104 of file GeometryID.hpp
References extractShift(), m_value, and mask.
Referenced by setApproach(), setBoundary(), setLayer(), setSensitive(), and setVolume().
constexpr GeometryID& Acts::GeometryID::setBoundary (Value boundary) inline
Set the boundary identifier.
Definition at line 61 of file GeometryID.hpp.
View newest version in sPHENIX GitHub at line 61 of file GeometryID.hpp
References kBoundaryMask, and setBits().
Referenced by Acts::TrackingVolume::closeGeometry(), Acts::JsonGeometryConverter::jsonToMaterialMaps(), FW::RootMaterialDecorator::RootMaterialDecorator(), and FW::RootMaterialTrackWriter::writeT().
constexpr GeometryID& Acts::GeometryID::setLayer (Value layer) inline
Set the layer identifier.
Definition at line 65 of file GeometryID.hpp.
View newest version in sPHENIX GitHub at line 65 of file GeometryID.hpp
References kLayerMask, and setBits().
Referenced by Acts::Test::BOOST_AUTO_TEST_CASE(), Acts::TrackingVolume::closeGeometry(), Acts::JsonGeometryConverter::jsonToMaterialMaps(), FW::RootMaterialDecorator::RootMaterialDecorator(), FW::selectLayer(), and FW::RootMaterialTrackWriter::writeT().
constexpr GeometryID& Acts::GeometryID::setSensitive (Value sensitive) inline
Set the sensitive identifier.
Definition at line 73 of file GeometryID.hpp.
View newest version in sPHENIX GitHub at line 73 of file GeometryID.hpp
References kSensitiveMask, and setBits().
Referenced by Acts::Test::BOOST_AUTO_TEST_CASE(), Acts::Layer::closeGeometry(), Acts::TrackingVolume::closeGeometry(), Acts::JsonGeometryConverter::jsonToMaterialMaps(), FW::RootMaterialDecorator::RootMaterialDecorator(), and FW::RootMaterialTrackWriter::writeT().
constexpr GeometryID& Acts::GeometryID::setVolume (Value volume) inline
Set the volume identifier.
Definition at line 57 of file GeometryID.hpp.
View newest version in sPHENIX GitHub at line 57 of file GeometryID.hpp
References kVolumeMask, and setBits().
Referenced by Acts::Test::BOOST_AUTO_TEST_CASE(), Acts::TrackingVolume::closeGeometry(), Acts::JsonGeometryConverter::jsonToMaterialMaps(), FW::RootMaterialDecorator::RootMaterialDecorator(), FW::selectLayer(), FW::selectVolume(), and FW::RootMaterialTrackWriter::writeT().
constexpr Value Acts::GeometryID::value () const inline
Return the encoded value.
Definition at line 42 of file materialPlotHelper.hpp.
View newest version in sPHENIX GitHub at line 42 of file materialPlotHelper.hpp
References m_value.
constexpr Value Acts::GeometryID::value () const inline
Return the encoded value.
Definition at line 43 of file GeometryID.hpp.
View newest version in sPHENIX GitHub at line 43 of file GeometryID.hpp
References m_value.
Referenced by FW::CsvPlanarClusterReader::read(), Acts::Test::runTest(), FW::CsvPlanarClusterWriter::writeT(), and FW::RootMaterialTrackWriter::writeT().
constexpr Value Acts::GeometryID::volume () const inline
Return the volume identifier.
Definition at line 45 of file materialPlotHelper.hpp.
View newest version in sPHENIX GitHub at line 45 of file materialPlotHelper.hpp
References getBits(), and volume_mask.
constexpr Value Acts::GeometryID::volume () const inline
Return the volume identifier.
Definition at line 46 of file GeometryID.hpp.
View newest version in sPHENIX GitHub at line 46 of file GeometryID.hpp
References getBits(), and kVolumeMask.
Referenced by Acts::Test::BOOST_AUTO_TEST_CASE(), Acts::VolumeMaterialMapper::checkAndInsert(), Acts::SurfaceMaterialMapper::checkAndInsert(), Acts::JsonGeometryConverter::convertToRep(), Acts::VolumeMaterialMapper::mapMaterialTrack(), Acts::CKFSourceLinkSelector::operator()(), FW::RootMaterialWriter::write(), FW::CsvPlanarClusterWriter::writeT(), and FW::RootPlanarClusterWriter::writeT().
Friends And Related Function Documentation
constexpr bool operator< (GeometryID lhs, GeometryID rhs) friend
Definition at line 82 of file materialPlotHelper.hpp.
View newest version in sPHENIX GitHub at line 82 of file materialPlotHelper.hpp
constexpr bool operator< (GeometryID lhs, GeometryID rhs) friend
Definition at line 113 of file GeometryID.hpp.
View newest version in sPHENIX GitHub at line 113 of file GeometryID.hpp
constexpr bool operator== (GeometryID lhs, GeometryID rhs) friend
Definition at line 79 of file materialPlotHelper.hpp.
View newest version in sPHENIX GitHub at line 79 of file materialPlotHelper.hpp
constexpr bool operator== (GeometryID lhs, GeometryID rhs) friend
Definition at line 110 of file GeometryID.hpp.
View newest version in sPHENIX GitHub at line 110 of file GeometryID.hpp
Member Data Documentation
constexpr Value Acts::GeometryID::approach_mask = 0x0000000ff0000000 static private
Definition at line 60 of file materialPlotHelper.hpp.
View newest version in sPHENIX GitHub at line 60 of file materialPlotHelper.hpp
Referenced by approach().
constexpr Value Acts::GeometryID::boundary_mask = 0x00ff000000000000 static private
Definition at line 58 of file materialPlotHelper.hpp.
View newest version in sPHENIX GitHub at line 58 of file materialPlotHelper.hpp
Referenced by boundary().
constexpr Value Acts::GeometryID::kApproachMask = 0x0000000ff0000000 static private
Definition at line 85 of file GeometryID.hpp.
View newest version in sPHENIX GitHub at line 85 of file GeometryID.hpp
Referenced by approach(), and setApproach().
constexpr Value Acts::GeometryID::kBoundaryMask = 0x00ff000000000000 static private
Definition at line 81 of file GeometryID.hpp.
View newest version in sPHENIX GitHub at line 81 of file GeometryID.hpp
Referenced by boundary(), and setBoundary().
constexpr Value Acts::GeometryID::kLayerMask = 0x0000fff000000000 static private
Definition at line 83 of file GeometryID.hpp.
View newest version in sPHENIX GitHub at line 83 of file GeometryID.hpp
Referenced by layer(), and setLayer().
constexpr Value Acts::GeometryID::kSensitiveMask = 0x000000000fffffff static private
Definition at line 87 of file GeometryID.hpp.
View newest version in sPHENIX GitHub at line 87 of file GeometryID.hpp
Referenced by sensitive(), and setSensitive().
constexpr Value Acts::GeometryID::kVolumeMask = 0xff00000000000000 static private
Definition at line 79 of file GeometryID.hpp.
View newest version in sPHENIX GitHub at line 79 of file GeometryID.hpp
Referenced by setVolume(), and volume().
constexpr Value Acts::GeometryID::layer_mask = 0x0000fff000000000 static private
Definition at line 59 of file materialPlotHelper.hpp.
View newest version in sPHENIX GitHub at line 59 of file materialPlotHelper.hpp
Referenced by layer().
Value Acts::GeometryID::m_value = 0 private
Definition at line 89 of file GeometryID.hpp.
View newest version in sPHENIX GitHub at line 89 of file GeometryID.hpp
Referenced by getBits(), setBits(), and value().
constexpr Value Acts::GeometryID::sensitive_mask = 0x000000000fffffff static private
Definition at line 61 of file materialPlotHelper.hpp.
View newest version in sPHENIX GitHub at line 61 of file materialPlotHelper.hpp
Referenced by sensitive().
constexpr Value Acts::GeometryID::volume_mask = 0xff00000000000000 static private
Definition at line 57 of file materialPlotHelper.hpp.
View newest version in sPHENIX GitHub at line 57 of file materialPlotHelper.hpp
Referenced by volume().
The documentation for this class was generated from the following files:
fun4all_acts/blob/master/Core/include/Acts/Geometry/GeometryID.hpp
fun4all_acts/blob/master/Examples/Scripts/MaterialMaping/materialPlotHelper.hpp