EIC Software: EicConstantField Class Reference
EicConstantField Class Reference
#include <EicRoot/blob/master/eic/field/EicConstantField.h>
Public Member Functions
EicConstantField (double bX=0.0, double bY=0.0, double bZ=0.0)
~EicConstantField ()
int Initialize ()
int GetFieldValue (const double xx[], double B[]) const
Public Member Functions inherited from EicMagneticFieldMap
EicMagneticFieldMap (const char *fileName=0, TGeoMatrix *transformation=0, TGeoShape *shape=0, int color=_DEFAULT_YOKE_COLOR_)
~EicMagneticFieldMap ()
bool Initialized () const
TGeoShape * GetShape () const
virtual bool Contains (const double xx[]) const
const TString & GetFileName () const
virtual bool CapableToBuildYoke () const
virtual TString GetDetectorName () const
virtual int ConstructGeometry ()
void SetYokeColor (int color)
int GetYokeColor () const
virtual TGeoVolume * GetYokeVolume () const
Protected Attributes
Double_t mFieldLocal [3]
Double_t mFieldGlobal [3]
Protected Attributes inherited from EicMagneticFieldMap
UInt_t mMD5BufferSize
UChar_t * mMD5Signature
Bool_t mInitialized
TGeoMatrix * mTransformation
indicates whether Initialize() call was made or not
TGeoShape * mShape
Int_t mColor
Additional Inherited Members
Protected Member Functions inherited from EicMagneticFieldMap
const char * BasenameWrapper (const char *fname) const
int GetMD5Signature (unsigned char output[])
Detailed Description
Definition at line 18 of file EicConstantField.h.
View newest version in sPHENIX GitHub at line 18 of file EicConstantField.h
Constructor & Destructor Documentation
EicConstantField::EicConstantField (double bX = 0.0, double bY = 0.0, double bZ = 0.0) inline
Definition at line 21 of file EicConstantField.h.
View newest version in sPHENIX GitHub at line 21 of file EicConstantField.h
References mFieldGlobal, and mFieldLocal.
EicConstantField::~EicConstantField () inline
Definition at line 26 of file EicConstantField.h.
View newest version in sPHENIX GitHub at line 26 of file EicConstantField.h
Member Function Documentation
int EicConstantField::GetFieldValue (const double xx[], double B[]) const virtual
Implements EicMagneticFieldMap.
Definition at line 23 of file EicConstantField.cxx.
View newest version in sPHENIX GitHub at line 23 of file EicConstantField.cxx
References EicMagneticFieldMap::Contains(), EicMagneticFieldMap::GetShape(), mFieldGlobal, and EicMagneticFieldMap::mInitialized.
int EicConstantField::Initialize () virtual
Reimplemented from EicMagneticFieldMap.
Definition at line 10 of file EicConstantField.cxx.
View newest version in sPHENIX GitHub at line 10 of file EicConstantField.cxx
References EicMagneticFieldMap::Initialize(), mFieldGlobal, mFieldLocal, and EicMagneticFieldMap::mTransformation.
Member Data Documentation
Double_t EicConstantField::mFieldGlobal[3] mutable protected
Definition at line 36 of file EicConstantField.h.
View newest version in sPHENIX GitHub at line 36 of file EicConstantField.h
Referenced by EicConstantField(), GetFieldValue(), and Initialize().
Double_t EicConstantField::mFieldLocal[3] protected
Definition at line 35 of file EicConstantField.h.
View newest version in sPHENIX GitHub at line 35 of file EicConstantField.h
Referenced by EicConstantField(), and Initialize().
The documentation for this class was generated from the following files:
EicRoot/blob/master/eic/field/EicConstantField.h
EicRoot/blob/master/eic/field/EicConstantField.cxx