EIC Software: eicsmeardetectors/blob/master/SmearJLEIC_0_1.cxx File Reference
SmearJLEIC_0_1.cxx File Reference
#include "eicsmear/erhic/VirtualParticle.h"
#include "eicsmear/smear/Acceptance.h"
#include "eicsmear/smear/Device.h"
#include "eicsmear/smear/Detector.h"
#include "eicsmear/smear/Smearer.h"
#include "eicsmear/smear/ParticleMCS.h"
#include "eicsmear/smear/PerfectID.h"
#include <eicsmear/smear/Smear.h>
#include <eicsmear/erhic/ParticleMC.h>
#include "Math/Vector4D.h"
Functions
static double ThetaFromEta (const double eta)
Smear::Detector BuildJLEIC_0_1 ()
Function Documentation
Smear::Detector BuildJLEIC_0_1 ()
Definition at line 34 of file SmearJLEIC_0_1.cxx.
View newest version in sPHENIX GitHub at line 34 of file SmearJLEIC_0_1.cxx
References Smear::Smearer::Accept, Smear::Detector::AddDevice(), Smear::Acceptance::AddParticle(), Smear::Acceptance::AddZone(), Acts::UnitConstants::e, Smear::kCharged, Smear::kE, Smear::kElectromagnetic, Smear::kHadronic, Smear::kNeutral, Smear::kPhi, Smear::kPt, Smear::kTheta, Smear::Acceptance::SetCharge(), Smear::Detector::SetEventKinematicsCalculator(), Smear::Acceptance::SetGenre(), and ThetaFromEta().
Referenced by BuildByName().
double ThetaFromEta (const double eta) static
Definition at line 175 of file SmearJLEIC_0_1.cxx.
View newest version in sPHENIX GitHub at line 175 of file SmearJLEIC_0_1.cxx
Referenced by BuildJLEIC_0_1().