EIC Software: erhic Namespace Reference
erhic Namespace Reference
Namespaces
namespace hadronic
Classes
class EventDEMP
class EventDis
class EventDjangoh
class EventDpmjet
class VirtualEventFactory
class EventFromAsciiFactory
class EventGmcTrans
class EventHepMC
class EventMC
class Reader
class EventMCFilterABC
class EventMilou
class EventPepsi
class EventPythia
Pythia 6 DIS event.
class EventBeagle
class EventRapgap
class EventSartre
class EventSimple
class LogReader
class LogReaderPythia
class LogReaderPepsi
class LogReaderDjangoh
class LogReaderMilou
class LogReaderGmcTrans
class LogReaderFactory
class FileType
class File
class File< erhic::EventHepMC >
class FileFactory
class Forester
struct DisKinematics
class KinematicsComputer
class LeptonKinematicsComputer
class JacquetBlondelComputer
class DoubleAngleComputer
class ParticleMCeA
class ParticleMCbase
class ParticleMC
class Pid
class Pythia6
class Pythia6EventBuilder
class Pythia6ParticleBuilder
Factory class for Monte Carlo particles.
class VirtualEvent
Abstract base class for a physics event.
class VirtualParticle
Abstract base class for a general particle.
struct TProcessIdObjectCount
Typedefs
typedef std::vector< const
VirtualParticle * > TrackVector
typedef TrackVector::iterator TrackVectorIter
typedef TrackVector::const_iterator TrackVectorCIter
Enumerations
enum HepMC_outtype { HepMC3, HepMC2, RootTree, Root }
Functions
void HandleHepmcParticle (const HepMC3::GenParticlePtr &p, std::map< HepMC3::GenParticlePtr, int > &hepmcp_index, int &particleindex, std::unique_ptr< erhic::EventHepMC > &mEvent)
void HandleAllVertices (HepMC3::GenEvent &evt, std::map< HepMC3::GenParticlePtr, int > &hepmcp_index, int &particleindex, std::unique_ptr< erhic::EventHepMC > &mEvent)
void UpdateRuninfo (std::vector< VirtualEventFactory::NamedObjects > &mObjectsToWriteAtTheEnd, const HepMC3::GenEvent &evt)
Variables
const std::string EicSmearVersionString = "1.1.12"
Typedef Documentation
typedef std::vector<const VirtualParticle*> erhic::TrackVector
Definition at line 30 of file EventMC.cxx.
View newest version in sPHENIX GitHub at line 30 of file EventMC.cxx
typedef TrackVector::const_iterator erhic::TrackVectorCIter
Definition at line 32 of file EventMC.cxx.
View newest version in sPHENIX GitHub at line 32 of file EventMC.cxx
typedef TrackVector::iterator erhic::TrackVectorIter
Definition at line 31 of file EventMC.cxx.
View newest version in sPHENIX GitHub at line 31 of file EventMC.cxx
Enumeration Type Documentation
enum erhic::HepMC_outtype
Enumerator:
HepMC3
HepMC2
RootTree
Root
Definition at line 71 of file functions.h.
View newest version in sPHENIX GitHub at line 71 of file functions.h
Function Documentation
void erhic::HandleAllVertices (HepMC3::GenEvent & evt, std::map< HepMC3::GenParticlePtr, int > & hepmcp_index, int & particleindex, std::unique_ptr< erhic::EventHepMC > & mEvent)
Helper. This clumsy construction would be much better handled with private members, but it doesn't work like that if we want to specialize from EventFromAsciiFactory while keeping some functions.
Definition at line 356 of file EventFactoryHepMC.cxx.
View newest version in sPHENIX GitHub at line 356 of file EventFactoryHepMC.cxx
References erhic::EventMC::GetTrack(), HandleHepmcParticle(), p, and v.
Referenced by erhic::EventFromAsciiFactory< T >::AddParticle().
void erhic::HandleHepmcParticle (const HepMC3::GenParticlePtr & p, std::map< HepMC3::GenParticlePtr, int > & hepmcp_index, int & particleindex, std::unique_ptr< erhic::EventHepMC > & mEvent)
Helper. This clumsy construction would be much better handled with private members, but it doesn't work like that if we want to specialize from EventFromAsciiFactory while keeping some functions.
Definition at line 320 of file EventFactoryHepMC.cxx.
View newest version in sPHENIX GitHub at line 320 of file EventFactoryHepMC.cxx
References erhic::EventMC::AddLast(), it, p, particle, erhic::ParticleMCbase::Set4Vector(), erhic::ParticleMCbase::SetEvent(), erhic::ParticleMCbase::SetId(), erhic::ParticleMCbase::SetIndex(), erhic::ParticleMCbase::SetStatus(), erhic::ParticleMCbase::SetVertex(), and v.
Referenced by erhic::EventFromAsciiFactory< T >::AddParticle(), and HandleAllVertices().
void erhic::UpdateRuninfo (std::vector< VirtualEventFactory::NamedObjects > & mObjectsToWriteAtTheEnd, const HepMC3::GenEvent & evt)
Update run-wise information.
Definition at line 415 of file EventFactoryHepMC.cxx.
View newest version in sPHENIX GitHub at line 415 of file EventFactoryHepMC.cxx
Referenced by erhic::EventFromAsciiFactory< T >::AddParticle().
Variable Documentation
const std::string erhic::EicSmearVersionString = "1.1.12"
Simple namespace-wide constant to determine the version
Definition at line 29 of file functions.h.
View newest version in sPHENIX GitHub at line 29 of file functions.h
Referenced by main().