EIC Software: CbmRichProjectionProducer Class Reference
CbmRichProjectionProducer Class Reference
Project track by straight line from imaginary plane to the mirror and reflect it to the photodetector plane.
#include <EicRoot/blob/master/rich/tracks/CbmRichProjectionProducer.h>
Public Member Functions
CbmRichProjectionProducer (int zflag)
Standard constructor.
virtual ~CbmRichProjectionProducer ()
Destructor.
virtual void Init ()
Initialization of the task.
virtual void SetParContainers ()
Initialization of Parameter Containers.
virtual void DoProjection (TClonesArray *richProj)
Execute task.
Public Member Functions inherited from CbmRichProjectionProducerBase
CbmRichProjectionProducerBase ()
CbmRichProjectionProducerBase (int flag)
virtual ~CbmRichProjectionProducerBase ()
Destructor.
void SetZFlag (int flag)
Set flag whether to use point in imaginary plane (zflag=1) or mirror point (zflag=2) for extrapolation.
Private Member Functions
CbmRichProjectionProducer (const CbmRichProjectionProducer &)
Copy constructor.
CbmRichProjectionProducer & operator= (const CbmRichProjectionProducer &)
Assignment operator.
Private Attributes
TClonesArray * fListRICHImPlanePoint
int fNHits
int fEvent
double fDetX
double fDetY
double fDetZ
double fDetWidthX
double fDetWidthY
double fThetaDet
double fPhiDet
double fDetXTransf
double fDetYTransf
double fDetZTransf
double fZm
double fYm
double fXm
double fR
double fMaxXTrackExtr
double fMaxYTrackExtr
TObjArray * fSensNodes
TObjArray * fPassNodes
CbmGeoRichPar * fPar
Additional Inherited Members
Protected Attributes inherited from CbmRichProjectionProducerBase
int fZflag
Detailed Description
Project track by straight line from imaginary plane to the mirror and reflect it to the photodetector plane.
Author
P.Stolpovsky
Date
2005
Definition at line 29 of file CbmRichProjectionProducer.h.
View newest version in sPHENIX GitHub at line 29 of file CbmRichProjectionProducer.h
Constructor & Destructor Documentation
CbmRichProjectionProducer::CbmRichProjectionProducer (int zflag)
Standard constructor.
Parameters
[in] zflag Flag whether to use point in imaginary plane (zflag=1) or mirror point (zflag=2) for extrapolation.
CbmRichProjectionProducer::~CbmRichProjectionProducer () virtual
Destructor.
Definition at line 66 of file CbmRichProjectionProducer.cxx.
View newest version in sPHENIX GitHub at line 66 of file CbmRichProjectionProducer.cxx
References FairRootManager::Instance(), and FairRootManager::Write().
CbmRichProjectionProducer::CbmRichProjectionProducer (const CbmRichProjectionProducer &) private
Copy constructor.
Member Function Documentation
void CbmRichProjectionProducer::DoProjection (TClonesArray * richProj) virtual
Execute task.
Parameters
[out] richProj Output array of created projections.
Implements CbmRichProjectionProducerBase.
Definition at line 168 of file CbmRichProjectionProducer.cxx.
View newest version in sPHENIX GitHub at line 168 of file CbmRichProjectionProducer.cxx
References fDetWidthX, fDetWidthY, fDetX, fDetY, fDetYTransf, fDetZ, fEvent, fListRICHImPlanePoint, fPhiDet, fR, fThetaDet, fXm, fYm, CbmRichProjectionProducerBase::fZflag, fZm, FairTrackParam::GetQp(), FairTrackParam::GetTx(), FairTrackParam::GetTy(), FairTrackParam::GetX(), FairTrackParam::GetY(), FairTrackParam::GetZ(), p, FairTrackParam::Position(), and CbmRichHitProducer::TiltPoint().
void CbmRichProjectionProducer::Init (void) virtual
Initialization of the task.
Reimplemented from CbmRichProjectionProducerBase.
Definition at line 79 of file CbmRichProjectionProducer.cxx.
View newest version in sPHENIX GitHub at line 79 of file CbmRichProjectionProducer.cxx
References fDetWidthX, fDetWidthY, fDetX, fDetXTransf, fDetY, fDetYTransf, fDetZ, fDetZTransf, fEvent, fListRICHImPlanePoint, fMaxXTrackExtr, fMaxYTrackExtr, fPar, fPassNodes, fPhiDet, fR, fSensNodes, fThetaDet, fXm, fYm, CbmRichProjectionProducerBase::fZflag, fZm, FairGeoNode::getCenterPosition(), CbmGeoRichPar::GetGeoPassiveNodes(), CbmGeoRichPar::GetGeoSensitiveNodes(), FairGeoNode::getLabTransform(), FairRootManager::GetObject(), FairGeoNode::getParameters(), FairGeoTransform::getRotMatrix(), FairGeoTransform::getTranslation(), FairRootManager::Instance(), FairGeoVector::X(), FairGeoVector::Y(), and FairGeoVector::Z().
CbmRichProjectionProducer& CbmRichProjectionProducer::operator= (const CbmRichProjectionProducer &) private
Assignment operator.
void CbmRichProjectionProducer::SetParContainers () virtual
Initialization of Parameter Containers.
Reimplemented from CbmRichProjectionProducerBase.
Definition at line 72 of file CbmRichProjectionProducer.cxx.
View newest version in sPHENIX GitHub at line 72 of file CbmRichProjectionProducer.cxx
References fPar, FairRuntimeDb::getContainer(), FairRun::GetRuntimeDb(), and FairRunAna::Instance().
Member Data Documentation
double CbmRichProjectionProducer::fDetWidthX private
Definition at line 71 of file CbmRichProjectionProducer.h.
View newest version in sPHENIX GitHub at line 71 of file CbmRichProjectionProducer.h
Referenced by DoProjection(), and Init().
double CbmRichProjectionProducer::fDetWidthY private
Definition at line 72 of file CbmRichProjectionProducer.h.
View newest version in sPHENIX GitHub at line 72 of file CbmRichProjectionProducer.h
Referenced by DoProjection(), and Init().
double CbmRichProjectionProducer::fDetX private
Definition at line 68 of file CbmRichProjectionProducer.h.
View newest version in sPHENIX GitHub at line 68 of file CbmRichProjectionProducer.h
Referenced by DoProjection(), and Init().
double CbmRichProjectionProducer::fDetXTransf private
Definition at line 76 of file CbmRichProjectionProducer.h.
View newest version in sPHENIX GitHub at line 76 of file CbmRichProjectionProducer.h
Referenced by Init().
double CbmRichProjectionProducer::fDetY private
Definition at line 69 of file CbmRichProjectionProducer.h.
View newest version in sPHENIX GitHub at line 69 of file CbmRichProjectionProducer.h
Referenced by DoProjection(), and Init().
double CbmRichProjectionProducer::fDetYTransf private
Definition at line 77 of file CbmRichProjectionProducer.h.
View newest version in sPHENIX GitHub at line 77 of file CbmRichProjectionProducer.h
Referenced by DoProjection(), and Init().
double CbmRichProjectionProducer::fDetZ private
Definition at line 70 of file CbmRichProjectionProducer.h.
View newest version in sPHENIX GitHub at line 70 of file CbmRichProjectionProducer.h
Referenced by DoProjection(), and Init().
double CbmRichProjectionProducer::fDetZTransf private
Definition at line 78 of file CbmRichProjectionProducer.h.
View newest version in sPHENIX GitHub at line 78 of file CbmRichProjectionProducer.h
Referenced by Init().
int CbmRichProjectionProducer::fEvent private
Definition at line 66 of file CbmRichProjectionProducer.h.
View newest version in sPHENIX GitHub at line 66 of file CbmRichProjectionProducer.h
Referenced by DoProjection(), and Init().
TClonesArray* CbmRichProjectionProducer::fListRICHImPlanePoint private
Definition at line 63 of file CbmRichProjectionProducer.h.
View newest version in sPHENIX GitHub at line 63 of file CbmRichProjectionProducer.h
Referenced by DoProjection(), and Init().
double CbmRichProjectionProducer::fMaxXTrackExtr private
Definition at line 85 of file CbmRichProjectionProducer.h.
View newest version in sPHENIX GitHub at line 85 of file CbmRichProjectionProducer.h
Referenced by Init().
double CbmRichProjectionProducer::fMaxYTrackExtr private
Definition at line 86 of file CbmRichProjectionProducer.h.
View newest version in sPHENIX GitHub at line 86 of file CbmRichProjectionProducer.h
Referenced by Init().
int CbmRichProjectionProducer::fNHits private
Definition at line 65 of file CbmRichProjectionProducer.h.
View newest version in sPHENIX GitHub at line 65 of file CbmRichProjectionProducer.h
CbmGeoRichPar* CbmRichProjectionProducer::fPar private
Definition at line 90 of file CbmRichProjectionProducer.h.
View newest version in sPHENIX GitHub at line 90 of file CbmRichProjectionProducer.h
Referenced by Init(), and SetParContainers().
TObjArray* CbmRichProjectionProducer::fPassNodes private
Definition at line 89 of file CbmRichProjectionProducer.h.
View newest version in sPHENIX GitHub at line 89 of file CbmRichProjectionProducer.h
Referenced by Init().
double CbmRichProjectionProducer::fPhiDet private
Definition at line 74 of file CbmRichProjectionProducer.h.
View newest version in sPHENIX GitHub at line 74 of file CbmRichProjectionProducer.h
Referenced by DoProjection(), and Init().
double CbmRichProjectionProducer::fR private
Definition at line 83 of file CbmRichProjectionProducer.h.
View newest version in sPHENIX GitHub at line 83 of file CbmRichProjectionProducer.h
Referenced by DoProjection(), and Init().
TObjArray* CbmRichProjectionProducer::fSensNodes private
Definition at line 88 of file CbmRichProjectionProducer.h.
View newest version in sPHENIX GitHub at line 88 of file CbmRichProjectionProducer.h
Referenced by Init().
double CbmRichProjectionProducer::fThetaDet private
Definition at line 73 of file CbmRichProjectionProducer.h.
View newest version in sPHENIX GitHub at line 73 of file CbmRichProjectionProducer.h
Referenced by DoProjection(), and Init().
double CbmRichProjectionProducer::fXm private
Definition at line 82 of file CbmRichProjectionProducer.h.
View newest version in sPHENIX GitHub at line 82 of file CbmRichProjectionProducer.h
Referenced by DoProjection(), and Init().
double CbmRichProjectionProducer::fYm private
Definition at line 81 of file CbmRichProjectionProducer.h.
View newest version in sPHENIX GitHub at line 81 of file CbmRichProjectionProducer.h
Referenced by DoProjection(), and Init().
double CbmRichProjectionProducer::fZm private
Definition at line 80 of file CbmRichProjectionProducer.h.
View newest version in sPHENIX GitHub at line 80 of file CbmRichProjectionProducer.h
Referenced by DoProjection(), and Init().
The documentation for this class was generated from the following files:
EicRoot/blob/master/rich/tracks/CbmRichProjectionProducer.h
EicRoot/blob/master/rich/tracks/CbmRichProjectionProducer.cxx