EIC Software: FW::Geant4::MMSteppingAction Class Reference
FW::Geant4::MMSteppingAction Class Reference
Collects the RecordedMaterialProperties entities.
#include <fun4all_acts/blob/master/Examples/Algorithms/Geant4/include/ACTFW/Plugins/Geant4/MMSteppingAction.hpp>
Public Member Functions
MMSteppingAction ()
Constructor.
~MMSteppingAction () override
Destructor.
void UserSteppingAction (const G4Step *step) finaloverride
Interface Method doing the step.
void Reset ()
std::vector
< Acts::MaterialInteraction > materialSteps ()
Access to the collected Acts::MaterialInteraction entities.
FW::SimHitContainer::sequence_type trackSteps ()
Access to the collected FW::SimHitContainer entities.
Static Public Member Functions
static MMSteppingAction * Instance ()
Static access method to the instance.
Private Attributes
std::vector
< Acts::MaterialInteraction > m_steps = {}
The collected Acts::MaterialInteraction entities.
FW::SimHitContainer::sequence_type m_tracksteps
The collected FW::SimHit entities.
Static Private Attributes
static MMSteppingAction * fgInstance
Instance of the SteppingAction.
Detailed Description
Collects the RecordedMaterialProperties entities.
The MMSteppingAction class is the implementation of the Geant4 class SteppingAction. It extracts the weighted material of every step and collects all material steps.
Definition at line 32 of file MMSteppingAction.hpp.
View newest version in sPHENIX GitHub at line 32 of file MMSteppingAction.hpp
Constructor & Destructor Documentation
FW::Geant4::MMSteppingAction::MMSteppingAction ()
Constructor.
Definition at line 25 of file MMSteppingAction.cpp.
View newest version in sPHENIX GitHub at line 25 of file MMSteppingAction.cpp
References fgInstance.
FW::Geant4::MMSteppingAction::~MMSteppingAction () override
Destructor.
Definition at line 38 of file MMSteppingAction.cpp.
View newest version in sPHENIX GitHub at line 38 of file MMSteppingAction.cpp
Member Function Documentation
FW::Geant4::MMSteppingAction * FW::Geant4::MMSteppingAction::Instance (void) static
Static access method to the instance.
Definition at line 20 of file MMSteppingAction.cpp.
View newest version in sPHENIX GitHub at line 20 of file MMSteppingAction.cpp
References fgInstance.
Referenced by FW::Geant4::MMEventAction::BeginOfEventAction(), and FW::Geant4::MMEventAction::EndOfEventAction().
std::vector<Acts::MaterialInteraction> FW::Geant4::MMSteppingAction::materialSteps () inline
Access to the collected Acts::MaterialInteraction entities.
Definition at line 53 of file MMSteppingAction.hpp.
View newest version in sPHENIX GitHub at line 53 of file MMSteppingAction.hpp
References m_steps.
Referenced by FW::Geant4::MMEventAction::EndOfEventAction().
void FW::Geant4::MMSteppingAction::Reset ()
Interface reset method
Note
it clears the collected step vector
Definition at line 127 of file MMSteppingAction.cpp.
View newest version in sPHENIX GitHub at line 127 of file MMSteppingAction.cpp
Referenced by FW::Geant4::MMEventAction::BeginOfEventAction().
FW::SimHitContainer::sequence_type FW::Geant4::MMSteppingAction::trackSteps () inline
Access to the collected FW::SimHitContainer entities.
Definition at line 56 of file MMSteppingAction.hpp.
View newest version in sPHENIX GitHub at line 56 of file MMSteppingAction.hpp
References m_tracksteps.
void FW::Geant4::MMSteppingAction::UserSteppingAction (const G4Step * step) final override
Interface Method doing the step.
Note
it creates and collects the MaterialInteraction entities
Parameters
step is the Geant4 step of the particle
Definition at line 42 of file MMSteppingAction.cpp.
View newest version in sPHENIX GitHub at line 42 of file MMSteppingAction.cpp
References material, Acts::MaterialInteraction::materialProperties, eic::mm, Acts::UnitConstants::mm3, and Acts::MaterialInteraction::position.
Member Data Documentation
FW::Geant4::MMSteppingAction * FW::Geant4::MMSteppingAction::fgInstance static private
Initial value:
=
    nullptr
Instance of the SteppingAction.
Definition at line 60 of file MMSteppingAction.hpp.
View newest version in sPHENIX GitHub at line 60 of file MMSteppingAction.hpp
Referenced by Instance(), and MMSteppingAction().
std::vector<Acts::MaterialInteraction> FW::Geant4::MMSteppingAction::m_steps = {} private
The collected Acts::MaterialInteraction entities.
Definition at line 63 of file MMSteppingAction.hpp.
View newest version in sPHENIX GitHub at line 63 of file MMSteppingAction.hpp
Referenced by materialSteps().
FW::SimHitContainer::sequence_type FW::Geant4::MMSteppingAction::m_tracksteps private
The collected FW::SimHit entities.
Definition at line 65 of file MMSteppingAction.hpp.
View newest version in sPHENIX GitHub at line 65 of file MMSteppingAction.hpp
Referenced by trackSteps().
The documentation for this class was generated from the following files:
fun4all_acts/blob/master/Examples/Algorithms/Geant4/include/ACTFW/Plugins/Geant4/MMSteppingAction.hpp
fun4all_acts/blob/master/Examples/Algorithms/Geant4/src/MMSteppingAction.cpp