EIC Software: FairDbProxy Class Reference
FairDbProxy Class Reference
#include <EicRoot/blob/master/dbase/dbInterface/FairDbProxy.h>
Public Types
typedef const std::vector< UInt_t > SeqList_t
Public Member Functions
FairDbProxy (FairDbMultConnector &cascader, const string &tableName, const FairDbTableMetaData *metaData, const FairDbTableMetaData *metaValid, const FairDbTableProxy *tableProxy)
virtual ~FairDbProxy ()
UInt_t GetNumDb () const
const string & GetTableName () const
const FairDbTableProxy * GetTableProxy () const
void StoreMetaData (FairDbTableMetaData &metaData) const
Bool_t TableExists (Int_t selectDbNo=-1) const
void FindTimeBoundaries (const ValContext &vc, const FairDb::Task &task, UInt_t dbNo, ValTimeStamp earliestCreate, ValTimeStamp &start, ValTimeStamp &end) const
FairDbResultSet * QueryAllValidities (UInt_t dbNo, UInt_t seqNo=0) const
FairDbResultSet * QuerySeqNo (UInt_t seqNo, UInt_t dbNo) const
FairDbResultSet * QuerySeqNos (SeqList_t &seqNos, UInt_t dbNo, const string &sqlData="", const string &fillOpts="") const
Secondary query for aggregate and extended context queries.
FairDbResultSet * QueryValidity (const ValContext &vc, const FairDb::Task &task, UInt_t dbNo) const
FairDbResultSet * QueryValidity (const string &context, const FairDb::Task &task, UInt_t dbNo) const
FairDbResultSet * QueryValidity (UInt_t seqNo, UInt_t dbNo) const
Bool_t ReplaceInsertDate (const ValTimeStamp &ts, UInt_t SeqNo, UInt_t dbNo) const
Bool_t RemoveSeqNo (UInt_t seqNo, UInt_t dbNo) const
Bool_t ReplaceSeqNo (UInt_t oldSeqNo, UInt_t newSeqNo, UInt_t dbNo) const
void SetSqlCondition (const string &sql)
Private Member Functions
Bool_t ReplaceSeqNoOracle (UInt_t oldSeqNo, UInt_t newSeqNo, UInt_t dbNo) const
FairDbProxy (const FairDbProxy &)
FairDbProxy & operator= (const FairDbProxy &)
Private Attributes
FairDbMultConnector & fMultConnector
const FairDbTableMetaData * fMetaData
const FairDbTableMetaData * fMetaValid
string fSqlCondition
string fTableName
string fTableNameUc
const FairDbTableProxy * fTableProxy
string fValSuffix
Detailed Description
Definition at line 20 of file FairDbProxy.h.
View newest version in sPHENIX GitHub at line 20 of file FairDbProxy.h
Member Typedef Documentation
typedef const std::vector<UInt_t> FairDbProxy::SeqList_t
Definition at line 26 of file FairDbProxy.h.
View newest version in sPHENIX GitHub at line 26 of file FairDbProxy.h
Constructor & Destructor Documentation
FairDbProxy::FairDbProxy (FairDbMultConnector & cascader, const string & tableName, const FairDbTableMetaData * metaData, const FairDbTableMetaData * metaValid, const FairDbTableProxy * tableProxy)
FairDbProxy::~FairDbProxy () virtual
Definition at line 47 of file FairDbProxy.cxx.
View newest version in sPHENIX GitHub at line 47 of file FairDbProxy.cxx
FairDbProxy::FairDbProxy (const FairDbProxy &) private
Member Function Documentation
void FairDbProxy::FindTimeBoundaries (const ValContext & vc, const FairDb::Task & task, UInt_t dbNo, ValTimeStamp earliestCreate, ValTimeStamp & start, ValTimeStamp & end) const
Definition at line 52 of file FairDbProxy.cxx.
View newest version in sPHENIX GitHub at line 52 of file FairDbProxy.cxx
References FairDbString::c_str(), FairDbMultConnector::CreateStatement(), fMultConnector, fTableName, ValContext::GetDetector(), ValTimeStamp::GetSec(), ValContext::GetSimFlag(), GetTableName(), FairDb::GetTimeGate(), ValContext::GetTimeStamp(), FairDb::MakeDateTimeString(), and FairDb::MakeTimeStamp().
UInt_t FairDbProxy::GetNumDb () const
Definition at line 126 of file FairDbProxy.cxx.
View newest version in sPHENIX GitHub at line 126 of file FairDbProxy.cxx
References fMultConnector, and FairDbMultConnector::GetNumDb().
Referenced by FairDbValidityRecBuilder::FairDbValidityRecBuilder().
const string& FairDbProxy::GetTableName () const inline
Definition at line 37 of file FairDbProxy.h.
View newest version in sPHENIX GitHub at line 37 of file FairDbProxy.h
References fTableNameUc.
Referenced by FairDbValidityRecBuilder::FairDbValidityRecBuilder(), FindTimeBoundaries(), and QueryValidity().
const FairDbTableProxy* FairDbProxy::GetTableProxy () const inline
Definition at line 38 of file FairDbProxy.h.
View newest version in sPHENIX GitHub at line 38 of file FairDbProxy.h
References fTableProxy.
FairDbProxy& FairDbProxy::operator= (const FairDbProxy &) private
FairDbResultSet * FairDbProxy::QueryAllValidities (UInt_t dbNo, UInt_t seqNo = 0) const
Definition at line 131 of file FairDbProxy.cxx.
View newest version in sPHENIX GitHub at line 131 of file FairDbProxy.cxx
References FairDbMultConnector::CreateStatement(), fMetaValid, fMultConnector, fSqlCondition, fTableName, fTableProxy, fValSuffix, and FairDbString::GetString().
Referenced by ClassImp().
FairDbResultSet * FairDbProxy::QuerySeqNo (UInt_t seqNo, UInt_t dbNo) const
Definition at line 156 of file FairDbProxy.cxx.
View newest version in sPHENIX GitHub at line 156 of file FairDbProxy.cxx
References FairDbString::c_str(), FairDbMultConnector::CreateStatement(), fMetaData, fMultConnector, fTableName, fTableProxy, FairDbTimerManager::gTimerManager, FairDbTableMetaData::HasRowCounter(), FairDbServices::OrderContextQuery(), and FairDbTimerManager::RecMainQuery().
Referenced by FairDbSqlValPacket::FairDbSqlValPacket(), and FairDbTableProxy::Query().
FairDbResultSet * FairDbProxy::QuerySeqNos (SeqList_t & seqNos, UInt_t dbNo, const string & sqlData = "", const string & fillOpts = "") const
Secondary query for aggregate and extended context queries.
Definition at line 176 of file FairDbProxy.cxx.
View newest version in sPHENIX GitHub at line 176 of file FairDbProxy.cxx
References FairDbString::c_str(), FairDbMultConnector::CreateStatement(), fMetaData, fMultConnector, fTableName, fTableProxy, FairDbTimerManager::gTimerManager, FairDbTableMetaData::HasRowCounter(), FairDbServices::OrderContextQuery(), and FairDbTimerManager::RecMainQuery().
FairDbResultSet * FairDbProxy::QueryValidity (const ValContext & vc, const FairDb::Task & task, UInt_t dbNo) const
Definition at line 229 of file FairDbProxy.cxx.
View newest version in sPHENIX GitHub at line 229 of file FairDbProxy.cxx
References ValContext::GetDetector(), ValTimeStamp::GetSec(), ValContext::GetSimFlag(), GetTableName(), FairDb::GetTimeGate(), ValContext::GetTimeStamp(), and FairDb::MakeDateTimeString().
Referenced by FairDbValidityRecBuilder::FairDbValidityRecBuilder(), FairDbTableProxy::Query(), and ReplaceSeqNoOracle().
FairDbResultSet * FairDbProxy::QueryValidity (const string & context, const FairDb::Task & task, UInt_t dbNo) const
Definition at line 262 of file FairDbProxy.cxx.
View newest version in sPHENIX GitHub at line 262 of file FairDbProxy.cxx
References FairDbString::c_str(), FairDbMultConnector::CreateStatement(), fMetaValid, fMultConnector, fSqlCondition, fTableName, fTableProxy, fValSuffix, and FairDb::kAnyTask.
FairDbResultSet * FairDbProxy::QueryValidity (UInt_t seqNo, UInt_t dbNo) const
Definition at line 302 of file FairDbProxy.cxx.
View newest version in sPHENIX GitHub at line 302 of file FairDbProxy.cxx
References FairDbString::c_str(), FairDbMultConnector::CreateStatement(), fMetaValid, fMultConnector, fSqlCondition, fTableName, fTableProxy, and fValSuffix.
Bool_t FairDbProxy::RemoveSeqNo (UInt_t seqNo, UInt_t dbNo) const
Definition at line 322 of file FairDbProxy.cxx.
View newest version in sPHENIX GitHub at line 322 of file FairDbProxy.cxx
References FairDbString::c_str(), FairDbMultConnector::CreateStatement(), fMultConnector, fTableName, fValSuffix, and FairDbString::GetString().
Referenced by FairDbSqlValPacket::Store().
Bool_t FairDbProxy::ReplaceInsertDate (const ValTimeStamp & ts, UInt_t SeqNo, UInt_t dbNo) const
Definition at line 363 of file FairDbProxy.cxx.
View newest version in sPHENIX GitHub at line 363 of file FairDbProxy.cxx
References ValTimeStamp::AsString(), FairDbString::c_str(), FairDbMultConnector::CreateStatement(), fMultConnector, fTableName, and fValSuffix.
Bool_t FairDbProxy::ReplaceSeqNo (UInt_t oldSeqNo, UInt_t newSeqNo, UInt_t dbNo) const
Definition at line 393 of file FairDbProxy.cxx.
View newest version in sPHENIX GitHub at line 393 of file FairDbProxy.cxx
References FairDbString::c_str(), FairDbMultConnector::CreateStatement(), fMultConnector, fTableName, fValSuffix, FairDbMultConnector::GetConnection(), FairDbConnection::GetDbType(), FairDbString::GetString(), FairDb::kOracle, and ReplaceSeqNoOracle().
Bool_t FairDbProxy::ReplaceSeqNoOracle (UInt_t oldSeqNo, UInt_t newSeqNo, UInt_t dbNo) const private
Definition at line 449 of file FairDbProxy.cxx.
View newest version in sPHENIX GitHub at line 449 of file FairDbProxy.cxx
References FairDbString::c_str(), FairDbMultConnector::CreateStatement(), FairDbRowStream::CurColFieldType(), FairDbResultSet::CurColValue(), FairDbResultSet::FetchRow(), fMultConnector, fTableName, fValSuffix, FairDbFieldType::GetConcept(), FairDbString::GetString(), FairDbRowStream::IncrementCurCol(), FairDbResultSet::IsBeforeFirst(), FairDbResultSet::IsExhausted(), FairDb::kChar, FairDb::kDate, FairDb::kString, FairDbRowStream::NumCols(), and QueryValidity().
Referenced by ReplaceSeqNo().
void FairDbProxy::SetSqlCondition (const string & sql) inline
Definition at line 76 of file FairDbProxy.h.
View newest version in sPHENIX GitHub at line 76 of file FairDbProxy.h
References fSqlCondition.
Referenced by FairDbTableProxy::SetSqlCondition().
void FairDbProxy::StoreMetaData (FairDbTableMetaData & metaData) const
Definition at line 529 of file FairDbProxy.cxx.
View newest version in sPHENIX GitHub at line 529 of file FairDbProxy.cxx
References FairDbTableMetaData::Clear(), FairDbConnection::Connect(), FairDbConnection::DisConnect(), fMultConnector, FairDbMultConnector::GetConnection(), FairDbMultConnector::GetNumDb(), FairDbConnection::GetServer(), name, FairDbTableMetaData::SetColFieldType(), FairDbTableMetaData::SetColIsNullable(), FairDbTableMetaData::SetColName(), FairDbFieldType::SetUnsigned(), FairDbTableMetaData::TableName(), and FairUtilString::ToUpper().
Referenced by FairDbTableProxy::RefreshMetaData().
Bool_t FairDbProxy::TableExists (Int_t selectDbNo = -1) const
Definition at line 589 of file FairDbProxy.cxx.
View newest version in sPHENIX GitHub at line 589 of file FairDbProxy.cxx
References fMultConnector, fTableName, and FairDbMultConnector::TableExists().
Referenced by FairDbValidityRecBuilder::FairDbValidityRecBuilder().
Member Data Documentation
const FairDbTableMetaData* FairDbProxy::fMetaData private
Definition at line 90 of file FairDbProxy.h.
View newest version in sPHENIX GitHub at line 90 of file FairDbProxy.h
Referenced by QuerySeqNo(), and QuerySeqNos().
const FairDbTableMetaData* FairDbProxy::fMetaValid private
Definition at line 91 of file FairDbProxy.h.
View newest version in sPHENIX GitHub at line 91 of file FairDbProxy.h
Referenced by QueryAllValidities(), and QueryValidity().
FairDbMultConnector& FairDbProxy::fMultConnector private
Definition at line 89 of file FairDbProxy.h.
View newest version in sPHENIX GitHub at line 89 of file FairDbProxy.h
Referenced by FindTimeBoundaries(), GetNumDb(), QueryAllValidities(), QuerySeqNo(), QuerySeqNos(), QueryValidity(), RemoveSeqNo(), ReplaceInsertDate(), ReplaceSeqNo(), ReplaceSeqNoOracle(), StoreMetaData(), and TableExists().
string FairDbProxy::fSqlCondition private
Definition at line 92 of file FairDbProxy.h.
View newest version in sPHENIX GitHub at line 92 of file FairDbProxy.h
Referenced by QueryAllValidities(), QueryValidity(), and SetSqlCondition().
string FairDbProxy::fTableName private
Definition at line 93 of file FairDbProxy.h.
View newest version in sPHENIX GitHub at line 93 of file FairDbProxy.h
Referenced by FindTimeBoundaries(), QueryAllValidities(), QuerySeqNo(), QuerySeqNos(), QueryValidity(), RemoveSeqNo(), ReplaceInsertDate(), ReplaceSeqNo(), ReplaceSeqNoOracle(), and TableExists().
string FairDbProxy::fTableNameUc private
Definition at line 94 of file FairDbProxy.h.
View newest version in sPHENIX GitHub at line 94 of file FairDbProxy.h
Referenced by GetTableName().
const FairDbTableProxy* FairDbProxy::fTableProxy private
Definition at line 95 of file FairDbProxy.h.
View newest version in sPHENIX GitHub at line 95 of file FairDbProxy.h
Referenced by GetTableProxy(), QueryAllValidities(), QuerySeqNo(), QuerySeqNos(), and QueryValidity().
string FairDbProxy::fValSuffix private
Definition at line 96 of file FairDbProxy.h.
View newest version in sPHENIX GitHub at line 96 of file FairDbProxy.h
Referenced by QueryAllValidities(), QueryValidity(), RemoveSeqNo(), ReplaceInsertDate(), ReplaceSeqNo(), and ReplaceSeqNoOracle().
The documentation for this class was generated from the following files:
EicRoot/blob/master/dbase/dbInterface/FairDbProxy.h
EicRoot/blob/master/dbase/dbInterface/FairDbProxy.cxx