EIC Software: fun4all_eicmacros/blob/master/common/G4_Piston.C File Reference
G4_Piston.C File Reference
#include <GlobalVariables.C>
#include <G4_Pipe.C>
#include <g4detectors/PHG4ConeSubsystem.h>
#include <g4detectors/PHG4CylinderSubsystem.h>
#include <g4main/PHG4Reco.h>
Namespaces
namespace Enable
namespace G4PISTON
Macros
#define MACRO_G4PISTON_C
Functions
void PistonInit ()
void Piston (PHG4Reco *g4Reco, const int absorberactive=0)
Variables
bool Enable::PISTON = false
bool Enable::PISTON_ABSORBER = false
bool Enable::PISTON_OVERLAPCHECK = false
int Enable::PISTON_VERBOSITY = 0
double G4PISTON::zpos1 = 305. - 20.
double G4PISTON::zpos2 = 335.9 - 10.2 / 2.
double G4PISTON::calorimeter_hole_diameter = 9.92331 * 2
Macro Definition Documentation
#define MACRO_G4PISTON_C
Definition at line 2 of file G4_Piston.C.
View newest version in sPHENIX GitHub at line 2 of file G4_Piston.C
Function Documentation
void Piston (PHG4Reco * g4Reco, const int absorberactive = 0)
Definition at line 36 of file G4_Piston.C.
View newest version in sPHENIX GitHub at line 36 of file G4_Piston.C
References Enable::ABSORBER, G4PIPE::al_pipe_length, G4PIPE::be_pipe_length, G4PIPE::be_pipe_radius, G4PISTON::calorimeter_hole_diameter, PHG4Sector::Sector_Geometry::eta_to_polar_angle(), max, name, Enable::OVERLAPCHECK, PHG4DetectorSubsystem::OverlapCheck(), Enable::PISTON_ABSORBER, Enable::PISTON_OVERLAPCHECK, Enable::PISTON_VERBOSITY, pos(), PHG4Reco::registerSubsystem(), Acts::UnitConstants::s, PHG4DetectorSubsystem::set_double_param(), PHG4DetectorSubsystem::set_string_param(), PHG4DetectorSubsystem::SetActive(), PHG4DetectorSubsystem::SuperDetector(), Enable::VERBOSITY, G4PISTON::zpos1, and G4PISTON::zpos2.
Referenced by G4Setup().
void PistonInit ()
Definition at line 30 of file G4_Piston.C.
View newest version in sPHENIX GitHub at line 30 of file G4_Piston.C
References G4PISTON::calorimeter_hole_diameter, max, BlackHoleGeometry::max_radius, BlackHoleGeometry::max_z, G4PISTON::zpos1, and G4PISTON::zpos2.
Referenced by G4Init().