EIC Software: PHActsVertexPropagator Class Reference
PHActsVertexPropagator Class Reference
#include <fun4all_coresoftware/blob/master/offline/packages/trackreco/PHActsVertexPropagator.h>
Public Member Functions
PHActsVertexPropagator (const std::string &name="PHActsVertexPropagator")
int Init (PHCompositeNode *topNode) override
int InitRun (PHCompositeNode *topNode) override
int process_event (PHCompositeNode *topNode) override
int End (PHCompositeNode *topNode) override
Called at the end of all processing.
Public Member Functions inherited from SubsysReco
~SubsysReco () override
virtual int EndRun (const int)
Called at the end of each run.
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
void Print (const std::string &="ALL") const override
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Private Member Functions
int getNodes (PHCompositeNode *topNode)
void setTrackVertexTo0 ()
BoundTrackParamPtrResult propagateTrack (const Acts::BoundTrackParameters &params, const unsigned int vtxid)
Acts::Vector3D getVertex (const unsigned int vtxid)
void updateSvtxTrack (SvtxTrack *track, const Acts::BoundTrackParameters &params)
void updateTrackDCA (SvtxTrack *track)
Private Attributes
ActsTrackingGeometry * m_tGeometry = nullptr
SvtxVertexMap * m_vertexMap = nullptr
SvtxTrackMap * m_trackMap = nullptr
std::map< const unsigned int,
Trajectory > * m_trajectories = nullptr
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = INT_MAX - 10
}
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Detailed Description
Definition at line 26 of file PHActsVertexPropagator.h.
View newest version in sPHENIX GitHub at line 26 of file PHActsVertexPropagator.h
Constructor & Destructor Documentation
PHActsVertexPropagator::PHActsVertexPropagator (const std::string & name = "PHActsVertexPropagator")
Definition at line 28 of file PHActsVertexPropagator.cc.
View newest version in sPHENIX GitHub at line 28 of file PHActsVertexPropagator.cc
Member Function Documentation
int PHActsVertexPropagator::End (PHCompositeNode *) override virtual
Called at the end of all processing.
Reimplemented from SubsysReco.
Definition at line 267 of file PHActsVertexPropagator.cc.
View newest version in sPHENIX GitHub at line 267 of file PHActsVertexPropagator.cc
References Fun4AllReturnCodes::EVENT_OK.
int PHActsVertexPropagator::getNodes (PHCompositeNode * topNode) private
Definition at line 273 of file PHActsVertexPropagator.cc.
View newest version in sPHENIX GitHub at line 273 of file PHActsVertexPropagator.cc
References Fun4AllReturnCodes::ABORTEVENT, Fun4AllReturnCodes::EVENT_OK, m_tGeometry, m_trackMap, m_trajectories, m_vertexMap, and PHWHERE.
Referenced by InitRun().
Acts::Vector3D PHActsVertexPropagator::getVertex (const unsigned int vtxid) private
Definition at line 233 of file PHActsVertexPropagator.cc.
View newest version in sPHENIX GitHub at line 233 of file PHActsVertexPropagator.cc
References Acts::UnitConstants::cm, SvtxVertexMap::get(), and m_vertexMap.
Referenced by propagateTrack().
int PHActsVertexPropagator::Init (PHCompositeNode *) override virtual
Called during initialization. Typically this is where you can book histograms, and e.g. register them to Fun4AllServer (so they can be output to file using Fun4AllServer::dumpHistos() method).
Reimplemented from SubsysReco.
Definition at line 33 of file PHActsVertexPropagator.cc.
View newest version in sPHENIX GitHub at line 33 of file PHActsVertexPropagator.cc
References Fun4AllReturnCodes::EVENT_OK.
int PHActsVertexPropagator::InitRun (PHCompositeNode *) override virtual
Called for first event when run number is known. Typically this is where you may want to fetch data from database, because you know the run number.
Reimplemented from SubsysReco.
Definition at line 38 of file PHActsVertexPropagator.cc.
View newest version in sPHENIX GitHub at line 38 of file PHActsVertexPropagator.cc
References getNodes().
int PHActsVertexPropagator::process_event (PHCompositeNode *) override virtual
Called for each event. This is where you do the real work.
Key was removed by the track cleaner, remove it from the trajectory list too
Erase the trajectories that were removed from the track cleaner
Reimplemented from SubsysReco.
Definition at line 43 of file PHActsVertexPropagator.cc.
View newest version in sPHENIX GitHub at line 43 of file PHActsVertexPropagator.cc
References Fun4AllReturnCodes::EVENT_OK, SvtxTrackMap::get(), m_trackMap, m_trajectories, m_vertexMap, PHWHERE, propagateTrack(), setTrackVertexTo0(), SvtxVertexMap::size(), updateSvtxTrack(), and Fun4AllBase::Verbosity().
BoundTrackParamPtrResult PHActsVertexPropagator::propagateTrack (const Acts::BoundTrackParameters & params, const unsigned int vtxid) private
create perigee surface
Definition at line 190 of file PHActsVertexPropagator.cc.
View newest version in sPHENIX GitHub at line 190 of file PHActsVertexPropagator.cc
References Acts::Logging::FATAL, ActsTrackingGeometry::geoContext, Acts::getDefaultLogger(), getVertex(), m_tGeometry, ActsTrackingGeometry::magFieldContext, eicpy.build::options, propagation_timing::stepper, Acts::Logging::VERBOSE, and Fun4AllBase::Verbosity().
Referenced by process_event().
void PHActsVertexPropagator::setTrackVertexTo0 () private
If we found no vertices in the event, propagate the tracks to 0,0,0
Definition at line 241 of file PHActsVertexPropagator.cc.
View newest version in sPHENIX GitHub at line 241 of file PHActsVertexPropagator.cc
References SvtxVertexMap::insert(), m_trackMap, and m_vertexMap.
Referenced by process_event().
void PHActsVertexPropagator::updateSvtxTrack (SvtxTrack * track, const Acts::BoundTrackParameters & params) private
Update covariance
Definition at line 96 of file PHActsVertexPropagator.cc.
View newest version in sPHENIX GitHub at line 96 of file PHActsVertexPropagator.cc
References Acts::UnitConstants::cm, Acts::SingleBoundTrackParameters< charge_t >::covariance(), ActsTrackingGeometry::geoContext, SvtxTrack::get_x(), SvtxTrack::get_y(), SvtxTrack::get_z(), m_tGeometry, Acts::SingleBoundTrackParameters< charge_t >::position(), Acts::VectorHelpers::position(), ActsTransformations::rotateActsCovToSvtxTrack(), SvtxTrack::set_acts_covariance(), SvtxTrack::set_error(), SvtxTrack::set_x(), SvtxTrack::set_y(), SvtxTrack::set_z(), ActsTransformations::setVerbosity(), updateTrackDCA(), and Fun4AllBase::Verbosity().
Referenced by process_event().
void PHActsVertexPropagator::updateTrackDCA (SvtxTrack * track) private
Definition at line 133 of file PHActsVertexPropagator.cc.
View newest version in sPHENIX GitHub at line 133 of file PHActsVertexPropagator.cc
References cos(), SvtxVertexMap::get(), SvtxTrack::get_error(), SvtxTrack::get_px(), SvtxTrack::get_py(), SvtxTrack::get_pz(), SvtxTrack::get_vertex_id(), SvtxTrack::get_x(), SvtxTrack::get_y(), SvtxTrack::get_z(), m_vertexMap, charm_jet_coverage::mom, phi, pos(), SvtxTrack::set_dca3d_xy(), SvtxTrack::set_dca3d_xy_error(), SvtxTrack::set_dca3d_z(), and SvtxTrack::set_dca3d_z_error().
Referenced by updateSvtxTrack().
Member Data Documentation
ActsTrackingGeometry* PHActsVertexPropagator::m_tGeometry = nullptr private
Definition at line 46 of file PHActsVertexPropagator.h.
View newest version in sPHENIX GitHub at line 46 of file PHActsVertexPropagator.h
Referenced by getNodes(), propagateTrack(), and updateSvtxTrack().
SvtxTrackMap* PHActsVertexPropagator::m_trackMap = nullptr private
Definition at line 48 of file PHActsVertexPropagator.h.
View newest version in sPHENIX GitHub at line 48 of file PHActsVertexPropagator.h
Referenced by getNodes(), process_event(), and setTrackVertexTo0().
std::map<const unsigned int, Trajectory>* PHActsVertexPropagator::m_trajectories = nullptr private
Definition at line 49 of file PHActsVertexPropagator.h.
View newest version in sPHENIX GitHub at line 49 of file PHActsVertexPropagator.h
Referenced by getNodes(), and process_event().
SvtxVertexMap* PHActsVertexPropagator::m_vertexMap = nullptr private
Definition at line 47 of file PHActsVertexPropagator.h.
View newest version in sPHENIX GitHub at line 47 of file PHActsVertexPropagator.h
Referenced by getNodes(), getVertex(), process_event(), setTrackVertexTo0(), and updateTrackDCA().
The documentation for this class was generated from the following files:
fun4all_coresoftware/blob/master/offline/packages/trackreco/PHActsVertexPropagator.h
fun4all_coresoftware/blob/master/offline/packages/trackreco/PHActsVertexPropagator.cc