EIC Software: PndSensorNameContFact Class Reference
PndSensorNameContFact Class Reference
#include <EicRoot/blob/master/PndTools/generalTools/PndSensorNameContFact.h>
Public Member Functions
PndSensorNameContFact ()
~PndSensorNameContFact ()
FairParSet * createContainer (FairContainer *c)
TList * GetSensorParNames ()
Public Member Functions inherited from FairContFact
FairContFact ()
virtual ~FairContFact ()
Bool_t addContext (const char *name)
void print ()
FairParSet * getContainer (const char *)
virtual void activateParIo (FairParIo *)
Private Member Functions
void setAllContainers ()
PndSensorNameContFact (const PndSensorNameContFact &L)
PndSensorNameContFact & operator= (const PndSensorNameContFact &)
ClassDef (PndSensorNameContFact, 1)
Private Attributes
TList * fSensorParNames
std::vector< std::string > fContainerNames
Additional Inherited Members
Protected Member Functions inherited from FairContFact
const char * getActualContext (const char *name)
ClassDef(FairContFact,
0) private FairContFact & operator= (const FairContFact &)
Protected Attributes inherited from FairContFact
TList * containers
FairLogger * fLogger
Detailed Description
Definition at line 12 of file PndSensorNameContFact.h.
View newest version in sPHENIX GitHub at line 12 of file PndSensorNameContFact.h
Constructor & Destructor Documentation
PndSensorNameContFact::PndSensorNameContFact ()
Definition at line 24 of file PndSensorNameContFact.cxx.
View newest version in sPHENIX GitHub at line 24 of file PndSensorNameContFact.cxx
References FairRuntimeDb::addContFactory(), fContainerNames, fSensorParNames, FairRuntimeDb::instance(), and setAllContainers().
PndSensorNameContFact::~PndSensorNameContFact ()
Definition at line 33 of file PndSensorNameContFact.cxx.
View newest version in sPHENIX GitHub at line 33 of file PndSensorNameContFact.cxx
References fSensorParNames.
PndSensorNameContFact::PndSensorNameContFact (const PndSensorNameContFact & L) private
Member Function Documentation
PndSensorNameContFact::ClassDef (PndSensorNameContFact , 1) private
FairParSet * PndSensorNameContFact::createContainer (FairContainer * c) virtual
Calls the constructor of the corresponding parameter container. For an actual context, which is not an empty string and not the default context of this container, the name is concatinated with the context.
Reimplemented from FairContFact.
Definition at line 53 of file PndSensorNameContFact.cxx.
View newest version in sPHENIX GitHub at line 53 of file PndSensorNameContFact.cxx
References fContainerNames, FairContainer::getConcatName(), FairContainer::getContext(), name, and p.
TList* PndSensorNameContFact::GetSensorParNames () inline
Definition at line 17 of file PndSensorNameContFact.h.
View newest version in sPHENIX GitHub at line 17 of file PndSensorNameContFact.h
References fSensorParNames.
PndSensorNameContFact& PndSensorNameContFact::operator= (const PndSensorNameContFact &) inline private
Definition at line 24 of file PndSensorNameContFact.h.
View newest version in sPHENIX GitHub at line 24 of file PndSensorNameContFact.h
void PndSensorNameContFact::setAllContainers () private
Creates the Container objects with all accepted contexts and adds them to the list of containers for the MVD library.
Definition at line 42 of file PndSensorNameContFact.cxx.
View newest version in sPHENIX GitHub at line 42 of file PndSensorNameContFact.cxx
References FairContFact::containers, fContainerNames, fSensorParNames, FairContainer::getConcatName(), and p.
Referenced by PndSensorNameContFact().
Member Data Documentation
std::vector<std::string> PndSensorNameContFact::fContainerNames private
Definition at line 21 of file PndSensorNameContFact.h.
View newest version in sPHENIX GitHub at line 21 of file PndSensorNameContFact.h
Referenced by createContainer(), PndSensorNameContFact(), and setAllContainers().
TList* PndSensorNameContFact::fSensorParNames private
Definition at line 20 of file PndSensorNameContFact.h.
View newest version in sPHENIX GitHub at line 20 of file PndSensorNameContFact.h
Referenced by GetSensorParNames(), PndSensorNameContFact(), setAllContainers(), and ~PndSensorNameContFact().
The documentation for this class was generated from the following files:
EicRoot/blob/master/PndTools/generalTools/PndSensorNameContFact.h
EicRoot/blob/master/PndTools/generalTools/PndSensorNameContFact.cxx