EIC Software: MediaBank Class Reference
MediaBank Class Reference
#include <EicRoot/blob/master/eic/htc/MediaBank.h>
Public Member Functions
MediaBank (const t_3d_line &axisLine, double maxLength)
void SetScanLine (const t_3d_line &scanLine)
void Print ()
int StartNextLayer (TGeoMaterial *material, TVector3 pt)
void SetCurrentLayerThickness (double thickness)
unsigned GetMediaLayerCount () const
const MediaLayer * GetMediaLayer (unsigned iq) const
MediaLayer * GetCurrentMediaLayer ()
double GetMaxLength () const
bool IsOutOfRange () const
const t_3d_line & GetScanLine () const
Private Attributes
double mMaxLength
bool mOutOfRangeFlag
t_3d_line mScanLine
t_3d_line mAxisLine
double mSlopeCff
std::vector< MediaLayer > mMediaLayers
Detailed Description
Definition at line 17 of file MediaBank.h.
View newest version in sPHENIX GitHub at line 17 of file MediaBank.h
Constructor & Destructor Documentation
MediaBank::MediaBank (const t_3d_line & axisLine, double maxLength) inline
Definition at line 20 of file MediaBank.h.
View newest version in sPHENIX GitHub at line 20 of file MediaBank.h
Member Function Documentation
MediaLayer* MediaBank::GetCurrentMediaLayer () inline
Definition at line 52 of file MediaBank.h.
View newest version in sPHENIX GitHub at line 52 of file MediaBank.h
References GetMediaLayerCount(), and mMediaLayers.
Referenced by SetCurrentLayerThickness(), and StartNextLayer().
double MediaBank::GetMaxLength () const inline
Definition at line 55 of file MediaBank.h.
View newest version in sPHENIX GitHub at line 55 of file MediaBank.h
References mMaxLength.
Referenced by SetCurrentLayerThickness().
const MediaLayer* MediaBank::GetMediaLayer (unsigned iq) const inline
Definition at line 49 of file MediaBank.h.
View newest version in sPHENIX GitHub at line 49 of file MediaBank.h
References mMediaLayers.
Referenced by MediaSliceArray::MediaSliceArray(), and Print().
unsigned MediaBank::GetMediaLayerCount () const inline
Definition at line 48 of file MediaBank.h.
View newest version in sPHENIX GitHub at line 48 of file MediaBank.h
References mMediaLayers.
Referenced by GetCurrentMediaLayer(), MediaSliceArray::MediaSliceArray(), and Print().
const t_3d_line& MediaBank::GetScanLine () const inline
Definition at line 59 of file MediaBank.h.
View newest version in sPHENIX GitHub at line 59 of file MediaBank.h
Referenced by EicHtcTask::PerformMediaScan().
bool MediaBank::IsOutOfRange () const inline
Definition at line 57 of file MediaBank.h.
View newest version in sPHENIX GitHub at line 57 of file MediaBank.h
References mOutOfRangeFlag.
Referenced by EicHtcTask::PerformMediaScan().
void MediaBank::Print ()
Definition at line 36 of file MediaBank.cxx.
View newest version in sPHENIX GitHub at line 36 of file MediaBank.cxx
References MediaLayer::GetMaterial(), GetMediaLayer(), GetMediaLayerCount(), MediaLayer::GetThickness(), MediaLayer::GetZ0(), material(), and printf().
Referenced by EicHtcTask::PerformMediaScan().
void MediaBank::SetCurrentLayerThickness (double thickness) inline
Definition at line 36 of file MediaBank.h.
View newest version in sPHENIX GitHub at line 36 of file MediaBank.h
References GetCurrentMediaLayer(), GetMaxLength(), MediaLayer::GetZ0(), G4TTL::layer, mOutOfRangeFlag, mSlopeCff, and MediaLayer::SetThickness().
Referenced by EicHtcTask::PerformMediaScan().
void MediaBank::SetScanLine (const t_3d_line & scanLine) inline
Definition at line 24 of file MediaBank.h.
View newest version in sPHENIX GitHub at line 24 of file MediaBank.h
References mAxisLine, mScanLine, mSlopeCff, and t_3d_line::nx.
Referenced by EicHtcTask::ConfigureMediaBank().
int MediaBank::StartNextLayer (TGeoMaterial * material, TVector3 pt)
Definition at line 13 of file MediaBank.cxx.
View newest version in sPHENIX GitHub at line 13 of file MediaBank.cxx
References GetCurrentMediaLayer(), MediaLayer::GetZ0(), G4TTL::layer, mAxisLine, mMediaLayers, t_3d_line::nx, printf(), t_3d_line::x, and z.
Referenced by EicHtcTask::PerformMediaScan().
Member Data Documentation
t_3d_line MediaBank::mAxisLine private
Definition at line 72 of file MediaBank.h.
View newest version in sPHENIX GitHub at line 72 of file MediaBank.h
Referenced by SetScanLine(), and StartNextLayer().
double MediaBank::mMaxLength private
Definition at line 59 of file MediaBank.h.
View newest version in sPHENIX GitHub at line 59 of file MediaBank.h
Referenced by GetMaxLength().
std::vector<MediaLayer> MediaBank::mMediaLayers private
Definition at line 75 of file MediaBank.h.
View newest version in sPHENIX GitHub at line 75 of file MediaBank.h
Referenced by GetCurrentMediaLayer(), GetMediaLayer(), GetMediaLayerCount(), and StartNextLayer().
bool MediaBank::mOutOfRangeFlag private
Definition at line 66 of file MediaBank.h.
View newest version in sPHENIX GitHub at line 66 of file MediaBank.h
Referenced by IsOutOfRange(), and SetCurrentLayerThickness().
t_3d_line MediaBank::mScanLine private
Definition at line 72 of file MediaBank.h.
View newest version in sPHENIX GitHub at line 72 of file MediaBank.h
Referenced by SetScanLine().
double MediaBank::mSlopeCff private
Definition at line 73 of file MediaBank.h.
View newest version in sPHENIX GitHub at line 73 of file MediaBank.h
Referenced by SetCurrentLayerThickness(), and SetScanLine().
The documentation for this class was generated from the following files:
EicRoot/blob/master/eic/htc/MediaBank.h
EicRoot/blob/master/eic/htc/MediaBank.cxx