EIC Software: EvalTower Class Reference
EvalTower Class Reference
#include <fun4all_eic_qa/blob/master/source/EvalTower.h>
Public Member Functions
EvalTower ()
EvalTower (const RawTower *twr)
virtual ~EvalTower ()
void set_te (const float f)
float get_te () const
void set_teta (const float f)
float get_teta () const
void set_tt (const float f)
float get_tt () const
void set_ttheta (const float f)
float get_ttheta () const
void set_tphi (const float f)
float get_tphi () const
void set_tx (const float f)
float get_tx () const
void set_ty (const float f)
float get_ty () const
void set_tz (const float f)
float get_tz () const
Public Member Functions inherited from PHObject
PHObject ()
ctor
~PHObject () override
dtor
virtual PHObject * CloneMe () const
Virtual copy constructor.
virtual PHObject * clone () const final
PHObject * Clone (const char *newname="") const final
void Copy (TObject &object) const final
virtual void identify (std::ostream &os=std::cout) const
virtual void Reset ()
Clear Event.
virtual int isValid () const
isValid returns non zero if object contains vailid data
virtual int isValid (const float) const
virtual int isValid (const double) const
virtual int isValid (const int) const
virtual int isValid (const unsigned int) const
virtual int isImplemented (const float f) const
virtual int isImplemented (const double f) const
virtual int isImplemented (const int i) const
virtual int isImplemented (const unsigned int i) const
virtual int Integrate () const
virtual int Integrate (PHObject *)
virtual void CopyFrom (const PHObject *obj)
Private Attributes
float te = NAN
float teta = NAN
float tphi = NAN
float tt = NAN
float ttheta = NAN
float tx = NAN
float ty = NAN
float tz = NAN
Detailed Description
Definition at line 10 of file EvalTower.h.
View newest version in sPHENIX GitHub at line 10 of file EvalTower.h
Constructor & Destructor Documentation
EvalTower::EvalTower () inline
Definition at line 14 of file EvalTower.h.
View newest version in sPHENIX GitHub at line 14 of file EvalTower.h
EvalTower::EvalTower (const RawTower * twr)
Definition at line 5 of file EvalTower.cc.
View newest version in sPHENIX GitHub at line 5 of file EvalTower.cc
References RawTower::get_energy(), RawTower::get_time(), te, and tt.
virtual EvalTower::~EvalTower () inline virtual
Definition at line 16 of file EvalTower.h.
View newest version in sPHENIX GitHub at line 16 of file EvalTower.h
Member Function Documentation
float EvalTower::get_te () const inline
Definition at line 19 of file EvalTower.h.
View newest version in sPHENIX GitHub at line 19 of file EvalTower.h
References te.
Referenced by LoopEvalFR(), LoopEvalHR(), and LoopEvalPortableCircularCut().
float EvalTower::get_teta () const inline
Definition at line 22 of file EvalTower.h.
View newest version in sPHENIX GitHub at line 22 of file EvalTower.h
References teta.
float EvalTower::get_tphi () const inline
Definition at line 31 of file EvalTower.h.
View newest version in sPHENIX GitHub at line 31 of file EvalTower.h
References tphi.
Referenced by LoopEvalFR(), LoopEvalHR(), and LoopEvalPortableCircularCut().
float EvalTower::get_tt () const inline
Definition at line 25 of file EvalTower.h.
View newest version in sPHENIX GitHub at line 25 of file EvalTower.h
References tt.
float EvalTower::get_ttheta () const inline
Definition at line 28 of file EvalTower.h.
View newest version in sPHENIX GitHub at line 28 of file EvalTower.h
References ttheta.
Referenced by LoopEvalFR(), LoopEvalHR(), and LoopEvalPortableCircularCut().
float EvalTower::get_tx () const inline
Definition at line 34 of file EvalTower.h.
View newest version in sPHENIX GitHub at line 34 of file EvalTower.h
References tx.
float EvalTower::get_ty () const inline
Definition at line 37 of file EvalTower.h.
View newest version in sPHENIX GitHub at line 37 of file EvalTower.h
References ty.
float EvalTower::get_tz () const inline
Definition at line 40 of file EvalTower.h.
View newest version in sPHENIX GitHub at line 40 of file EvalTower.h
References tz.
void EvalTower::set_te (const float f) inline
Definition at line 18 of file EvalTower.h.
View newest version in sPHENIX GitHub at line 18 of file EvalTower.h
References te.
void EvalTower::set_teta (const float f) inline
Definition at line 21 of file EvalTower.h.
View newest version in sPHENIX GitHub at line 21 of file EvalTower.h
References teta.
Referenced by EvalRootTTreeReco::process_event().
void EvalTower::set_tphi (const float f) inline
Definition at line 30 of file EvalTower.h.
View newest version in sPHENIX GitHub at line 30 of file EvalTower.h
References tphi.
Referenced by EvalRootTTreeReco::process_event().
void EvalTower::set_tt (const float f) inline
Definition at line 24 of file EvalTower.h.
View newest version in sPHENIX GitHub at line 24 of file EvalTower.h
References tt.
void EvalTower::set_ttheta (const float f) inline
Definition at line 27 of file EvalTower.h.
View newest version in sPHENIX GitHub at line 27 of file EvalTower.h
References ttheta.
Referenced by EvalRootTTreeReco::process_event().
void EvalTower::set_tx (const float f) inline
Definition at line 33 of file EvalTower.h.
View newest version in sPHENIX GitHub at line 33 of file EvalTower.h
References tx.
Referenced by EvalRootTTreeReco::process_event().
void EvalTower::set_ty (const float f) inline
Definition at line 36 of file EvalTower.h.
View newest version in sPHENIX GitHub at line 36 of file EvalTower.h
References ty.
Referenced by EvalRootTTreeReco::process_event().
void EvalTower::set_tz (const float f) inline
Definition at line 39 of file EvalTower.h.
View newest version in sPHENIX GitHub at line 39 of file EvalTower.h
References tz.
Referenced by EvalRootTTreeReco::process_event().
Member Data Documentation
float EvalTower::te = NAN private
Definition at line 43 of file EvalTower.h.
View newest version in sPHENIX GitHub at line 43 of file EvalTower.h
Referenced by EvalTower(), get_te(), and set_te().
float EvalTower::teta = NAN private
Definition at line 44 of file EvalTower.h.
View newest version in sPHENIX GitHub at line 44 of file EvalTower.h
Referenced by get_teta(), and set_teta().
float EvalTower::tphi = NAN private
Definition at line 45 of file EvalTower.h.
View newest version in sPHENIX GitHub at line 45 of file EvalTower.h
Referenced by get_tphi(), and set_tphi().
float EvalTower::tt = NAN private
Definition at line 46 of file EvalTower.h.
View newest version in sPHENIX GitHub at line 46 of file EvalTower.h
Referenced by EvalTower(), get_tt(), and set_tt().
float EvalTower::ttheta = NAN private
Definition at line 47 of file EvalTower.h.
View newest version in sPHENIX GitHub at line 47 of file EvalTower.h
Referenced by get_ttheta(), and set_ttheta().
float EvalTower::tx = NAN private
Definition at line 48 of file EvalTower.h.
View newest version in sPHENIX GitHub at line 48 of file EvalTower.h
Referenced by get_tx(), and set_tx().
float EvalTower::ty = NAN private
Definition at line 49 of file EvalTower.h.
View newest version in sPHENIX GitHub at line 49 of file EvalTower.h
Referenced by get_ty(), and set_ty().
float EvalTower::tz = NAN private
Definition at line 50 of file EvalTower.h.
View newest version in sPHENIX GitHub at line 50 of file EvalTower.h
Referenced by get_tz(), and set_tz().
The documentation for this class was generated from the following files:
fun4all_eic_qa/blob/master/source/EvalTower.h
fun4all_eic_qa/blob/master/source/EvalTower.cc