EIC Software: RawTowerBuilderDRCALO Class Reference
RawTowerBuilderDRCALO Class Reference
SubsysReco module creating calorimeter tower objects (RawTowerv1) from hits (PHG4Hit) using j,k indeces of these hits.
#include <fun4all_eicdetectors/blob/master/simulation/g4simulation/g4drcalo/RawTowerBuilderDRCALO.h>
Public Member Functions
RawTowerBuilderDRCALO (const std::string &name="RawTowerBuilderDRCALO")
~RawTowerBuilderDRCALO () override
int InitRun (PHCompositeNode *topNode) override
int process_event (PHCompositeNode *topNode) override
int End (PHCompositeNode *topNode) override
Called at the end of all processing.
void Detector (const std::string &d)
void GeometryTableFile (const std::string &d)
void EminCut (const double e)
std::string get_sim_tower_node_prefix () const
void set_sim_tower_node_prefix (const std::string &simTowerNodePrefix)
Public Member Functions inherited from SubsysReco
~SubsysReco () override
virtual int EndRun (const int)
Called at the end of each run.
virtual int Init (PHCompositeNode *)
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
void Print (const std::string &="ALL") const override
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Private Member Functions
void CreateNodes (PHCompositeNode *topNode)
bool ReadGeometryFromTable ()
Private Attributes
RawTowerContainer * m_Towers
RawTowerGeomContainer * m_Geoms
std::string m_Detector
std::string m_SimTowerNodePrefix
std::string m_MappingTowerFile
RawTowerDefs::CalorimeterId m_CaloId
double m_GlobalPlaceInX
double m_GlobalPlaceInY
double m_GlobalPlaceInZ
double m_Emin
std::map< std::string, double > m_GlobalParameterMap
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = INT_MAX - 10
}
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Detailed Description
SubsysReco module creating calorimeter tower objects (RawTowerv1) from hits (PHG4Hit) using j,k indeces of these hits.
Definition at line 20 of file RawTowerBuilderDRCALO.h.
View newest version in sPHENIX GitHub at line 20 of file RawTowerBuilderDRCALO.h
Constructor & Destructor Documentation
RawTowerBuilderDRCALO::RawTowerBuilderDRCALO (const std::string & name = "RawTowerBuilderDRCALO")
Definition at line 45 of file RawTowerBuilderDRCALO.cc.
View newest version in sPHENIX GitHub at line 45 of file RawTowerBuilderDRCALO.cc
RawTowerBuilderDRCALO::~RawTowerBuilderDRCALO () inline override
Definition at line 24 of file RawTowerBuilderDRCALO.h.
View newest version in sPHENIX GitHub at line 24 of file RawTowerBuilderDRCALO.h
Member Function Documentation
void RawTowerBuilderDRCALO::CreateNodes (PHCompositeNode * topNode) private
Create nodes for output.
Name of output node for RawTowerContainer: "TOWER_" + detector;
Definition at line 193 of file RawTowerBuilderDRCALO.cc.
View newest version in sPHENIX GitHub at line 193 of file RawTowerBuilderDRCALO.cc
References PHCompositeNode::addNode(), RawTowerDefs::convert_name_to_caloid(), PHNodeIterator::findFirst(), m_Detector, m_Geoms, m_SimTowerNodePrefix, m_Towers, and PHWHERE.
Referenced by InitRun().
void RawTowerBuilderDRCALO::Detector (const std::string & d)
Name of the detector node the G4Hits should be taken from.
Definition at line 187 of file RawTowerBuilderDRCALO.cc.
View newest version in sPHENIX GitHub at line 187 of file RawTowerBuilderDRCALO.cc
References RawTowerDefs::convert_name_to_caloid(), d, m_CaloId, and m_Detector.
Referenced by DRCALO_Towers().
void RawTowerBuilderDRCALO::EminCut (const double e) inline
Define minimum tower energy. After processing an event, towers with lower energy are will be deleted.
Definition at line 44 of file RawTowerBuilderDRCALO.h.
View newest version in sPHENIX GitHub at line 44 of file RawTowerBuilderDRCALO.h
References Acts::UnitConstants::e, and m_Emin.
int RawTowerBuilderDRCALO::End (PHCompositeNode *) override virtual
Called at the end of all processing.
Reimplemented from SubsysReco.
Definition at line 182 of file RawTowerBuilderDRCALO.cc.
View newest version in sPHENIX GitHub at line 182 of file RawTowerBuilderDRCALO.cc
References Fun4AllReturnCodes::EVENT_OK.
void RawTowerBuilderDRCALO::GeometryTableFile (const std::string & d) inline
Specifiy text-file with table for tower mapping
Definition at line 37 of file RawTowerBuilderDRCALO.h.
View newest version in sPHENIX GitHub at line 37 of file RawTowerBuilderDRCALO.h
References d, and m_MappingTowerFile.
Referenced by DRCALO_Towers().
std::string RawTowerBuilderDRCALO::get_sim_tower_node_prefix () const inline
Get prefix for tower collection to identify simulated towers before digitization.
Definition at line 50 of file RawTowerBuilderDRCALO.h.
View newest version in sPHENIX GitHub at line 50 of file RawTowerBuilderDRCALO.h
References m_SimTowerNodePrefix.
int RawTowerBuilderDRCALO::InitRun (PHCompositeNode *) override virtual
Called for first event when run number is known. Typically this is where you may want to fetch data from database, because you know the run number.
Reimplemented from SubsysReco.
Definition at line 59 of file RawTowerBuilderDRCALO.cc.
View newest version in sPHENIX GitHub at line 59 of file RawTowerBuilderDRCALO.cc
References CreateNodes(), Acts::UnitConstants::e, Fun4AllReturnCodes::EVENT_OK, exit(), PHNodeIterator::findFirst(), PHWHERE, and ReadGeometryFromTable().
int RawTowerBuilderDRCALO::process_event (PHCompositeNode *) override virtual
Called for each event. This is where you do the real work.
Reimplemented from SubsysReco.
Definition at line 95 of file RawTowerBuilderDRCALO.cc.
View newest version in sPHENIX GitHub at line 95 of file RawTowerBuilderDRCALO.cc
References RawTowerContainer::AddTower(), RawTowerContainer::compress(), RawTowerDefs::encode_towerid(), Fun4AllReturnCodes::EVENT_OK, exit(), PHG4Hit::get_edep(), PHG4Hit::get_index_j(), PHG4Hit::get_index_k(), PHG4Hit::get_light_yield(), PHG4Hit::get_property_float(), PHG4Hit::get_shower_id(), PHG4HitContainer::getHits(), RawTowerContainer::getTotalEdep(), RawTowerContainer::getTower(), RawTowerContainer::getTowers(), RawTowerContainer::identify(), m_CaloId, m_Detector, m_Emin, m_Towers, and Fun4AllBase::Verbosity().
bool RawTowerBuilderDRCALO::ReadGeometryFromTable () private
Read geometry information from table stored in text-file
Definition at line 246 of file RawTowerBuilderDRCALO.cc.
View newest version in sPHENIX GitHub at line 246 of file RawTowerBuilderDRCALO.cc
References RawTowerGeomContainer::add_tower_geometry(), Acts::UnitConstants::cm, RawTowerDefs::encode_towerid(), exit(), getline, m_CaloId, m_Geoms, m_GlobalParameterMap, m_GlobalPlaceInX, m_GlobalPlaceInY, m_GlobalPlaceInZ, m_MappingTowerFile, RawTowerGeom::set_center_x(), RawTowerGeom::set_center_y(), RawTowerGeom::set_center_z(), RawTowerGeom::set_size_x(), RawTowerGeom::set_size_y(), RawTowerGeom::set_size_z(), RawTowerGeom::set_tower_type(), G4CTD::size_z, and Fun4AllBase::Verbosity().
Referenced by InitRun().
void RawTowerBuilderDRCALO::set_sim_tower_node_prefix (const std::string & simTowerNodePrefix) inline
Set prefix for tower collection to identify simulated towers before digitization.
Definition at line 59 of file RawTowerBuilderDRCALO.h.
View newest version in sPHENIX GitHub at line 59 of file RawTowerBuilderDRCALO.h
References m_SimTowerNodePrefix.
Referenced by DRCALO_Towers().
Member Data Documentation
RawTowerDefs::CalorimeterId RawTowerBuilderDRCALO::m_CaloId private
Definition at line 84 of file RawTowerBuilderDRCALO.h.
View newest version in sPHENIX GitHub at line 84 of file RawTowerBuilderDRCALO.h
Referenced by Detector(), process_event(), and ReadGeometryFromTable().
std::string RawTowerBuilderDRCALO::m_Detector private
Definition at line 78 of file RawTowerBuilderDRCALO.h.
View newest version in sPHENIX GitHub at line 78 of file RawTowerBuilderDRCALO.h
Referenced by CreateNodes(), Detector(), and process_event().
double RawTowerBuilderDRCALO::m_Emin private
Definition at line 90 of file RawTowerBuilderDRCALO.h.
View newest version in sPHENIX GitHub at line 90 of file RawTowerBuilderDRCALO.h
Referenced by EminCut(), and process_event().
RawTowerGeomContainer* RawTowerBuilderDRCALO::m_Geoms private
Definition at line 76 of file RawTowerBuilderDRCALO.h.
View newest version in sPHENIX GitHub at line 76 of file RawTowerBuilderDRCALO.h
Referenced by CreateNodes(), and ReadGeometryFromTable().
std::map<std::string, double> RawTowerBuilderDRCALO::m_GlobalParameterMap private
Definition at line 92 of file RawTowerBuilderDRCALO.h.
View newest version in sPHENIX GitHub at line 92 of file RawTowerBuilderDRCALO.h
Referenced by ReadGeometryFromTable().
double RawTowerBuilderDRCALO::m_GlobalPlaceInX private
Definition at line 86 of file RawTowerBuilderDRCALO.h.
View newest version in sPHENIX GitHub at line 86 of file RawTowerBuilderDRCALO.h
Referenced by ReadGeometryFromTable().
double RawTowerBuilderDRCALO::m_GlobalPlaceInY private
Definition at line 87 of file RawTowerBuilderDRCALO.h.
View newest version in sPHENIX GitHub at line 87 of file RawTowerBuilderDRCALO.h
Referenced by ReadGeometryFromTable().
double RawTowerBuilderDRCALO::m_GlobalPlaceInZ private
Definition at line 88 of file RawTowerBuilderDRCALO.h.
View newest version in sPHENIX GitHub at line 88 of file RawTowerBuilderDRCALO.h
Referenced by ReadGeometryFromTable().
std::string RawTowerBuilderDRCALO::m_MappingTowerFile private
Definition at line 81 of file RawTowerBuilderDRCALO.h.
View newest version in sPHENIX GitHub at line 81 of file RawTowerBuilderDRCALO.h
Referenced by GeometryTableFile(), and ReadGeometryFromTable().
std::string RawTowerBuilderDRCALO::m_SimTowerNodePrefix private
Definition at line 79 of file RawTowerBuilderDRCALO.h.
View newest version in sPHENIX GitHub at line 79 of file RawTowerBuilderDRCALO.h
Referenced by CreateNodes(), get_sim_tower_node_prefix(), and set_sim_tower_node_prefix().
RawTowerContainer* RawTowerBuilderDRCALO::m_Towers private
Definition at line 75 of file RawTowerBuilderDRCALO.h.
View newest version in sPHENIX GitHub at line 75 of file RawTowerBuilderDRCALO.h
Referenced by CreateNodes(), and process_event().
The documentation for this class was generated from the following files:
fun4all_eicdetectors/blob/master/simulation/g4simulation/g4drcalo/RawTowerBuilderDRCALO.h
fun4all_eicdetectors/blob/master/simulation/g4simulation/g4drcalo/RawTowerBuilderDRCALO.cc