EIC Software: PHG4ECAPToFSteppingAction Class Reference
PHG4ECAPToFSteppingAction Class Reference
#include <fun4all_eicdetectors/blob/master/simulation/g4simulation/g4etof/PHG4ECAPToFSteppingAction.h>
Public Member Functions
PHG4ECAPToFSteppingAction (PHG4ECAPToFDetector *detector, const PHParameters *parameters)
constructor
~PHG4ECAPToFSteppingAction () override
destructor
bool UserSteppingAction (const G4Step *, bool) override
stepping action
void SetInterfacePointers (PHCompositeNode *) override
reimplemented from base class
void SaveAllHits (bool i=true)
this is just needed for use as reference plane for projections
Public Member Functions inherited from PHG4SteppingAction
PHG4SteppingAction (const std::string &name, const int i=0)
virtual ~PHG4SteppingAction ()
virtual void Verbosity (const int i)
virtual int Verbosity () const
virtual int Init ()
virtual double GetScintLightYield (const G4Step *step)
get scintillation photon count. It require a custom set SCINTILLATIONYIELD property to work
virtual double GetVisibleEnergyDeposition (const G4Step *step)
get amount of energy that can make scintillation light, in Unit of GeV.
virtual void StoreLocalCoordinate (PHG4Hit *hit, const G4Step *step, const bool do_prepoint, const bool do_postpoint)
Extract local coordinate of the hit and save to PHG4Hit.
virtual void Print (const std::string &) const
std::string GetName () const
void SetName (const std::string &name)
virtual void SetLightCorrection (const double inner_radius, const double inner_corr, const double outer_radius, const double outer_corr)
virtual double GetLightCorrection (const double r) const
virtual double GetLightCorrection (const double xpos, const double ypos) const
virtual bool ValidCorrection () const
virtual void SetHitNodeName (const std::string &, const std::string &)
Set the G4HIT node names from Subsystem rather than constructing your own.
Private Attributes
PHG4ECAPToFDetector * m_Detector
Pointer to subsystem.
const PHParameters * m_Params
PHG4HitContainer * m_HitContainer
pointer to hit container
PHG4HitContainer * m_ActiveGasHits
PHG4Hit * m_Hit
PHG4HitContainer * m_SaveHitContainer
PHG4Shower * m_SaveShower
G4VPhysicalVolume * m_SaveVolPre
G4VPhysicalVolume * m_SaveVolPost
bool m_SaveAllHitsFlag = false
int m_SaveTrackId
int m_SavePreStepStatus
int m_SavePostStepStatus
int m_BlackHoleFlag
int m_ActiveFlag
int m_UseG4StepsFlag
double m_Zmin
double m_Zmax
Detailed Description
Definition at line 18 of file PHG4ECAPToFSteppingAction.h.
View newest version in sPHENIX GitHub at line 18 of file PHG4ECAPToFSteppingAction.h
Constructor & Destructor Documentation
PHG4ECAPToFSteppingAction::PHG4ECAPToFSteppingAction (PHG4ECAPToFDetector * detector, const PHParameters * parameters)
constructor
Definition at line 41 of file PHG4ECAPToFSteppingAction.cc.
View newest version in sPHENIX GitHub at line 41 of file PHG4ECAPToFSteppingAction.cc
References Acts::UnitConstants::cm, m_Zmax, and m_Zmin.
PHG4ECAPToFSteppingAction::~PHG4ECAPToFSteppingAction () override
destructor
Definition at line 66 of file PHG4ECAPToFSteppingAction.cc.
View newest version in sPHENIX GitHub at line 66 of file PHG4ECAPToFSteppingAction.cc
References m_Hit.
Member Function Documentation
void PHG4ECAPToFSteppingAction::SaveAllHits (bool i = true) inline
this is just needed for use as reference plane for projections
Definition at line 43 of file PHG4ECAPToFSteppingAction.h.
View newest version in sPHENIX GitHub at line 43 of file PHG4ECAPToFSteppingAction.h
References m_SaveAllHitsFlag.
void PHG4ECAPToFSteppingAction::SetInterfacePointers (PHCompositeNode * topNode) override virtual
reimplemented from base class
Reimplemented from PHG4SteppingAction.
Definition at line 264 of file PHG4ECAPToFSteppingAction.cc.
View newest version in sPHENIX GitHub at line 264 of file PHG4ECAPToFSteppingAction.cc
References PHG4Detector::GetName(), m_ActiveGasHits, m_Detector, m_HitContainer, PHG4ECAPToFDetector::SuperDetector(), and PHG4SteppingAction::Verbosity().
bool PHG4ECAPToFSteppingAction::UserSteppingAction (const G4Step * aStep, bool) override virtual
stepping action
Implements PHG4SteppingAction.
Definition at line 71 of file PHG4ECAPToFSteppingAction.cc.
View newest version in sPHENIX GitHub at line 71 of file PHG4ECAPToFSteppingAction.cc
References PHG4Shower::add_g4hit_id(), PHG4HitContainer::AddHit(), Acts::UnitConstants::cm, exit(), PHG4Hit::get_edep(), PHG4Hit::get_eion(), PHG4Hit::get_hit_id(), PHG4ECAPToFDetector::get_Layer(), PHG4HitContainer::GetID(), Acts::UnitConstants::GeV, PHG4ECAPToFDetector::IsInToF(), m_ActiveFlag, m_ActiveGasHits, m_BlackHoleFlag, m_Detector, m_Hit, m_HitContainer, m_SaveAllHitsFlag, m_SaveHitContainer, m_SavePostStepStatus, m_SavePreStepStatus, m_SaveShower, m_SaveTrackId, m_SaveVolPost, m_SaveVolPre, m_UseG4StepsFlag, p, PHG4Hit::Reset(), PHG4Hit::set_edep(), PHG4Hit::set_eion(), PHG4Hit::set_layer(), PHG4Hit::set_px(), PHG4Hit::set_py(), PHG4Hit::set_pz(), PHG4Hit::set_shower_id(), PHG4Hit::set_t(), PHG4Hit::set_trkid(), PHG4Hit::set_x(), PHG4Hit::set_y(), PHG4Hit::set_z(), and Acts::Test::volume.
Member Data Documentation
int PHG4ECAPToFSteppingAction::m_ActiveFlag private
Definition at line 68 of file PHG4ECAPToFSteppingAction.h.
View newest version in sPHENIX GitHub at line 68 of file PHG4ECAPToFSteppingAction.h
Referenced by UserSteppingAction().
PHG4HitContainer* PHG4ECAPToFSteppingAction::m_ActiveGasHits private
Definition at line 56 of file PHG4ECAPToFSteppingAction.h.
View newest version in sPHENIX GitHub at line 56 of file PHG4ECAPToFSteppingAction.h
Referenced by SetInterfacePointers(), and UserSteppingAction().
int PHG4ECAPToFSteppingAction::m_BlackHoleFlag private
Definition at line 67 of file PHG4ECAPToFSteppingAction.h.
View newest version in sPHENIX GitHub at line 67 of file PHG4ECAPToFSteppingAction.h
Referenced by UserSteppingAction().
PHG4ECAPToFDetector* PHG4ECAPToFSteppingAction::m_Detector private
Pointer to subsystem.
pointer to the detector
Definition at line 50 of file PHG4ECAPToFSteppingAction.h.
View newest version in sPHENIX GitHub at line 50 of file PHG4ECAPToFSteppingAction.h
Referenced by SetInterfacePointers(), and UserSteppingAction().
PHG4Hit* PHG4ECAPToFSteppingAction::m_Hit private
Definition at line 57 of file PHG4ECAPToFSteppingAction.h.
View newest version in sPHENIX GitHub at line 57 of file PHG4ECAPToFSteppingAction.h
Referenced by UserSteppingAction(), and ~PHG4ECAPToFSteppingAction().
PHG4HitContainer* PHG4ECAPToFSteppingAction::m_HitContainer private
pointer to hit container
Definition at line 54 of file PHG4ECAPToFSteppingAction.h.
View newest version in sPHENIX GitHub at line 54 of file PHG4ECAPToFSteppingAction.h
Referenced by SetInterfacePointers(), and UserSteppingAction().
const PHParameters* PHG4ECAPToFSteppingAction::m_Params private
Definition at line 51 of file PHG4ECAPToFSteppingAction.h.
View newest version in sPHENIX GitHub at line 51 of file PHG4ECAPToFSteppingAction.h
bool PHG4ECAPToFSteppingAction::m_SaveAllHitsFlag = false private
Definition at line 63 of file PHG4ECAPToFSteppingAction.h.
View newest version in sPHENIX GitHub at line 63 of file PHG4ECAPToFSteppingAction.h
Referenced by SaveAllHits(), and UserSteppingAction().
PHG4HitContainer* PHG4ECAPToFSteppingAction::m_SaveHitContainer private
Definition at line 58 of file PHG4ECAPToFSteppingAction.h.
View newest version in sPHENIX GitHub at line 58 of file PHG4ECAPToFSteppingAction.h
Referenced by UserSteppingAction().
int PHG4ECAPToFSteppingAction::m_SavePostStepStatus private
Definition at line 66 of file PHG4ECAPToFSteppingAction.h.
View newest version in sPHENIX GitHub at line 66 of file PHG4ECAPToFSteppingAction.h
Referenced by UserSteppingAction().
int PHG4ECAPToFSteppingAction::m_SavePreStepStatus private
Definition at line 65 of file PHG4ECAPToFSteppingAction.h.
View newest version in sPHENIX GitHub at line 65 of file PHG4ECAPToFSteppingAction.h
Referenced by UserSteppingAction().
PHG4Shower* PHG4ECAPToFSteppingAction::m_SaveShower private
Definition at line 59 of file PHG4ECAPToFSteppingAction.h.
View newest version in sPHENIX GitHub at line 59 of file PHG4ECAPToFSteppingAction.h
Referenced by UserSteppingAction().
int PHG4ECAPToFSteppingAction::m_SaveTrackId private
Definition at line 64 of file PHG4ECAPToFSteppingAction.h.
View newest version in sPHENIX GitHub at line 64 of file PHG4ECAPToFSteppingAction.h
Referenced by UserSteppingAction().
G4VPhysicalVolume* PHG4ECAPToFSteppingAction::m_SaveVolPost private
Definition at line 62 of file PHG4ECAPToFSteppingAction.h.
View newest version in sPHENIX GitHub at line 62 of file PHG4ECAPToFSteppingAction.h
Referenced by UserSteppingAction().
G4VPhysicalVolume* PHG4ECAPToFSteppingAction::m_SaveVolPre private
Definition at line 61 of file PHG4ECAPToFSteppingAction.h.
View newest version in sPHENIX GitHub at line 61 of file PHG4ECAPToFSteppingAction.h
Referenced by UserSteppingAction().
int PHG4ECAPToFSteppingAction::m_UseG4StepsFlag private
Definition at line 69 of file PHG4ECAPToFSteppingAction.h.
View newest version in sPHENIX GitHub at line 69 of file PHG4ECAPToFSteppingAction.h
Referenced by UserSteppingAction().
double PHG4ECAPToFSteppingAction::m_Zmax private
Definition at line 71 of file PHG4ECAPToFSteppingAction.h.
View newest version in sPHENIX GitHub at line 71 of file PHG4ECAPToFSteppingAction.h
Referenced by PHG4ECAPToFSteppingAction().
double PHG4ECAPToFSteppingAction::m_Zmin private
Definition at line 70 of file PHG4ECAPToFSteppingAction.h.
View newest version in sPHENIX GitHub at line 70 of file PHG4ECAPToFSteppingAction.h
Referenced by PHG4ECAPToFSteppingAction().
The documentation for this class was generated from the following files:
fun4all_eicdetectors/blob/master/simulation/g4simulation/g4etof/PHG4ECAPToFSteppingAction.h
fun4all_eicdetectors/blob/master/simulation/g4simulation/g4etof/PHG4ECAPToFSteppingAction.cc