EIC Software: CbmRichHit Class Reference
CbmRichHit Class Reference
#include <EicRoot/blob/master/cbmdata/rich/CbmRichHit.h>
Public Member Functions
CbmRichHit ()
Default constructor.
virtual ~CbmRichHit ()
Destructor.
virtual string ToString () const
Inherited from CbmBaseHit.
virtual Int_t GetPlaneId () const
Inherited from CbmBaseHit.
virtual void SetPmtId (Int_t det)
virtual void SetNPhotons (Int_t n)
virtual void SetAmplitude (Double_t amp)
virtual Int_t GetPmtId () const
virtual Int_t GetNPhotons () const
virtual Double_t GetAmplitude () const
Public Member Functions inherited from CbmPixelHit
CbmPixelHit ()
Default constructor.
CbmPixelHit (Int_t address, Double_t x, Double_t y, Double_t z, Double_t dx, Double_t dy, Double_t dz, Double_t dxy, Int_t refId)
Standard constructor.
CbmPixelHit (Int_t address, const TVector3 &pos, const TVector3 &err, Double_t dxy, Int_t refId)
virtual ~CbmPixelHit ()
Double_t GetX () const
Double_t GetY () const
Double_t GetDx () const
Double_t GetDy () const
Double_t GetDxy () const
void Position (TVector3 &pos) const
Copies hit position to pos.
void PositionError (TVector3 &dpos) const
Copies hit position error to pos.
void SetX (Double_t x)
void SetY (Double_t y)
void SetDx (Double_t dx)
void SetDy (Double_t dy)
void SetDxy (Double_t dxy)
void SetPosition (const TVector3 &pos)
Sets position of the hit.
void SetPositionError (const TVector3 &dpos)
Public Member Functions inherited from CbmBaseHit
CbmBaseHit ()
Default constructor.
virtual ~CbmBaseHit ()
Destructor.
HitType GetType () const
Double_t GetZ () const
Double_t GetDz () const
Int_t GetRefId () const
Int_t GetAddress () const
FairMultiLinkedData * GetLinks () const
void SetZ (Double_t z)
void SetDz (Double_t dz)
void SetRefId (Int_t refId)
void SetAddress (Int_t address)
void SetLinks (FairMultiLinkedData *links)
Private Attributes
Int_t fPmtId
Int_t fNPhotons
Double32_t fAmplitude
Additional Inherited Members
Protected Member Functions inherited from CbmBaseHit
void SetType (HitType type)
Sets hit type.
CbmBaseHit (const CbmBaseHit &)
CbmBaseHit & operator= (const CbmBaseHit &)
Detailed Description
Definition at line 14 of file CbmRichHit.h.
View newest version in sPHENIX GitHub at line 14 of file CbmRichHit.h
Constructor & Destructor Documentation
CbmRichHit::CbmRichHit ()
Default constructor.
Definition at line 11 of file CbmRichHit.cxx.
View newest version in sPHENIX GitHub at line 11 of file CbmRichHit.cxx
References kRICHHIT, and CbmBaseHit::SetType().
CbmRichHit::~CbmRichHit () virtual
Destructor.
Definition at line 20 of file CbmRichHit.cxx.
View newest version in sPHENIX GitHub at line 20 of file CbmRichHit.cxx
Member Function Documentation
virtual Double_t CbmRichHit::GetAmplitude () const inline virtual
Definition at line 46 of file CbmRichHit.h.
View newest version in sPHENIX GitHub at line 46 of file CbmRichHit.h
References fAmplitude.
Referenced by ToString().
virtual Int_t CbmRichHit::GetNPhotons () const inline virtual
Definition at line 45 of file CbmRichHit.h.
View newest version in sPHENIX GitHub at line 45 of file CbmRichHit.h
References fNPhotons.
Referenced by CbmRichHitProducer::AddHit(), CbmRichGeoTest::HitsAndPoints(), and ToString().
virtual Int_t CbmRichHit::GetPlaneId () const inline virtual
Inherited from CbmBaseHit.
Implements CbmBaseHit.
Definition at line 36 of file CbmRichHit.h.
View newest version in sPHENIX GitHub at line 36 of file CbmRichHit.h
virtual Int_t CbmRichHit::GetPmtId () const inline virtual
Accessors
Definition at line 44 of file CbmRichHit.h.
View newest version in sPHENIX GitHub at line 44 of file CbmRichHit.h
References fPmtId.
Referenced by CbmRichHitProducer::AddHit(), and ToString().
virtual void CbmRichHit::SetAmplitude (Double_t amp) inline virtual
Definition at line 41 of file CbmRichHit.h.
View newest version in sPHENIX GitHub at line 41 of file CbmRichHit.h
References fAmplitude.
Referenced by CbmRichHitProducer::AddHit().
virtual void CbmRichHit::SetNPhotons (Int_t n) inline virtual
Definition at line 40 of file CbmRichHit.h.
View newest version in sPHENIX GitHub at line 40 of file CbmRichHit.h
References fNPhotons, and n.
Referenced by CbmRichHitProducer::AddHit().
virtual void CbmRichHit::SetPmtId (Int_t det) inline virtual
Modifiers
Definition at line 39 of file CbmRichHit.h.
View newest version in sPHENIX GitHub at line 39 of file CbmRichHit.h
References fPmtId.
Referenced by CbmRichHitProducer::AddHit().
string CbmRichHit::ToString () const virtual
Inherited from CbmBaseHit.
Reimplemented from CbmPixelHit.
Definition at line 24 of file CbmRichHit.cxx.
View newest version in sPHENIX GitHub at line 24 of file CbmRichHit.cxx
References CbmBaseHit::GetAddress(), GetAmplitude(), CbmPixelHit::GetDx(), CbmPixelHit::GetDxy(), CbmPixelHit::GetDy(), CbmBaseHit::GetDz(), GetNPhotons(), GetPmtId(), CbmBaseHit::GetRefId(), CbmPixelHit::GetX(), CbmPixelHit::GetY(), and CbmBaseHit::GetZ().
Member Data Documentation
Double32_t CbmRichHit::fAmplitude private
Definition at line 52 of file CbmRichHit.h.
View newest version in sPHENIX GitHub at line 52 of file CbmRichHit.h
Referenced by GetAmplitude(), and SetAmplitude().
Int_t CbmRichHit::fNPhotons private
Definition at line 51 of file CbmRichHit.h.
View newest version in sPHENIX GitHub at line 51 of file CbmRichHit.h
Referenced by GetNPhotons(), and SetNPhotons().
Int_t CbmRichHit::fPmtId private
Definition at line 50 of file CbmRichHit.h.
View newest version in sPHENIX GitHub at line 50 of file CbmRichHit.h
Referenced by GetPmtId(), and SetPmtId().
The documentation for this class was generated from the following files:
EicRoot/blob/master/cbmdata/rich/CbmRichHit.h
EicRoot/blob/master/cbmdata/rich/CbmRichHit.cxx