EIC Software: starlightDpmJet Class Reference
starlightDpmJet Class Reference
#include <estarlight/blob/master/include/starlightdpmjet.h>
Public Member Functions
starlightDpmJet (const inputParameters &input, beamBeamSystem &beamsystem)
int init ()
virtual upcEvent produceEvent ()
virtual upcEvent produceSingleEvent (int zdirection, float egamma)
virtual upcEvent produceDoubleEvent ()
virtual starlightConstants::event produceEvent (int &)
void setSingleMode ()
void setDoubleMode ()
void setMinGammaEnergy (double energy)
void setMaxGammaEnergy (double energy)
void setProtonMode (bool v=true)
Public Member Functions inherited from eventChannel
eventChannel (const inputParameters &input, beamBeamSystem &bbsystem)
virtual ~eventChannel ()
unsigned long nmbAttempts () const
returns number of attempted events
unsigned long nmbAccepted () const
returns number of accepted events
virtual eXEvent e_produceEvent ()=0
double getTotalChannelCrossSection () const
void setTotalChannelCrossSection (double sigma)
Public Member Functions inherited from readLuminosity
readLuminosity (const inputParameters &input)
~readLuminosity ()
void read ()
void e_read ()
Private Member Functions
starlightDpmJet ()
Private Attributes
spectrum * _spectrum
bool _doDoubleEvent
double _minGammaEnergy
double _maxGammaEnergy
double _protonMode
Additional Inherited Members
Static Public Member Functions inherited from eventChannel
static void transform (const double betax, const double betay, const double betaz, double &E, double &px, double &py, double &pz, int &iFbadevent)
Lorentz-transforms given 4-vector.
static double pseudoRapidity (const double px, const double py, const double pz)
calculates pseudorapidity for given 3-momentum
Public Attributes inherited from eventChannel
beamBeamSystem _bbs
randomGenerator _randy
Protected Attributes inherited from eventChannel
unsigned long _nmbAttempts
number of attempted events
unsigned long _nmbAccepted
number of accepted events
bool _ptCutEnabled
en/disables cut in pt
double _ptCutMin
minimum pt, if cut is enabled
double _ptCutMax
maximum pt, if cut is enabled
bool _etaCutEnabled
en/disables cut in eta
double _etaCutMin
minimum eta, if cut is enabled
double _etaCutMax
maximum eta, if cut is enabled
double _totalChannelCrossSection
Detailed Description
Definition at line 28 of file starlightdpmjet.h.
View newest version in sPHENIX GitHub at line 28 of file starlightdpmjet.h
Constructor & Destructor Documentation
starlightDpmJet::starlightDpmJet (const inputParameters & input, beamBeamSystem & beamsystem)
Definition at line 48 of file starlightdpmjet.cpp.
View newest version in sPHENIX GitHub at line 48 of file starlightdpmjet.cpp
starlightDpmJet::starlightDpmJet () private
Default constructor not implemented
Member Function Documentation
int starlightDpmJet::init ()
Definition at line 58 of file starlightdpmjet.cpp.
View newest version in sPHENIX GitHub at line 58 of file starlightdpmjet.cpp
References eventChannel::_bbs, _doDoubleEvent, _maxGammaEnergy, _minGammaEnergy, _protonMode, eventChannel::_randy, _spectrum, spectrum::generateKdouble(), spectrum::generateKsingle(), spectrum::setMaxGammaEnergy(), and spectrum::setMinGammaEnergy().
upcEvent starlightDpmJet::produceDoubleEvent () virtual
Definition at line 130 of file starlightdpmjet.cpp.
View newest version in sPHENIX GitHub at line 130 of file starlightdpmjet.cpp
References eventChannel::_randy, _spectrum, spectrum::drawKdouble(), produceSingleEvent(), and randomGenerator::Rndom().
Referenced by produceEvent().
upcEvent starlightDpmJet::produceEvent () virtual
Implements eventChannel.
Definition at line 86 of file starlightdpmjet.cpp.
View newest version in sPHENIX GitHub at line 86 of file starlightdpmjet.cpp
References _doDoubleEvent, _spectrum, spectrum::drawKsingle(), produceDoubleEvent(), and produceSingleEvent().
virtual starlightConstants::event starlightDpmJet::produceEvent (int &) inline virtual
Implements eventChannel.
Definition at line 43 of file starlightdpmjet.h.
View newest version in sPHENIX GitHub at line 43 of file starlightdpmjet.h
upcEvent starlightDpmJet::produceSingleEvent (int zdirection, float egamma) virtual
Definition at line 106 of file starlightdpmjet.cpp.
View newest version in sPHENIX GitHub at line 106 of file starlightdpmjet.cpp
References eventChannel::_bbs, upcEvent::addGamma(), beamBeamSystem::beam1(), lorentzVector::Boost(), dpmjetparticle_, dt_produceevent_(), particle, and beam::rapidity().
Referenced by produceDoubleEvent(), and produceEvent().
void starlightDpmJet::setDoubleMode () inline
Definition at line 47 of file starlightdpmjet.h.
View newest version in sPHENIX GitHub at line 47 of file starlightdpmjet.h
References _doDoubleEvent.
void starlightDpmJet::setMaxGammaEnergy (double energy) inline
Definition at line 51 of file starlightdpmjet.h.
View newest version in sPHENIX GitHub at line 51 of file starlightdpmjet.h
References _maxGammaEnergy.
void starlightDpmJet::setMinGammaEnergy (double energy) inline
Definition at line 49 of file starlightdpmjet.h.
View newest version in sPHENIX GitHub at line 49 of file starlightdpmjet.h
References _minGammaEnergy.
void starlightDpmJet::setProtonMode (bool v = true) inline
Definition at line 53 of file starlightdpmjet.h.
View newest version in sPHENIX GitHub at line 53 of file starlightdpmjet.h
References _protonMode, and v.
void starlightDpmJet::setSingleMode () inline
Definition at line 45 of file starlightdpmjet.h.
View newest version in sPHENIX GitHub at line 45 of file starlightdpmjet.h
References _doDoubleEvent.
Member Data Documentation
bool starlightDpmJet::_doDoubleEvent private
Should we produce a double event?
Definition at line 62 of file starlightdpmjet.h.
View newest version in sPHENIX GitHub at line 62 of file starlightdpmjet.h
Referenced by init(), produceEvent(), setDoubleMode(), and setSingleMode().
double starlightDpmJet::_maxGammaEnergy private
Max gamma energy
Definition at line 68 of file starlightdpmjet.h.
View newest version in sPHENIX GitHub at line 68 of file starlightdpmjet.h
Referenced by init(), and setMaxGammaEnergy().
double starlightDpmJet::_minGammaEnergy private
Min gamma energy
Definition at line 65 of file starlightdpmjet.h.
View newest version in sPHENIX GitHub at line 65 of file starlightdpmjet.h
Referenced by init(), and setMinGammaEnergy().
double starlightDpmJet::_protonMode private
Proton-nucleus mode
Definition at line 72 of file starlightdpmjet.h.
View newest version in sPHENIX GitHub at line 72 of file starlightdpmjet.h
Referenced by init(), and setProtonMode().
spectrum* starlightDpmJet::_spectrum private
Contains the photon spectrum
Definition at line 59 of file starlightdpmjet.h.
View newest version in sPHENIX GitHub at line 59 of file starlightdpmjet.h
Referenced by init(), produceDoubleEvent(), and produceEvent().
The documentation for this class was generated from the following files:
estarlight/blob/master/include/starlightdpmjet.h
estarlight/blob/master/src/starlightdpmjet.cpp