EIC Software: fun4all_acts/blob/master/Tests/UnitTests/Core/Material/MaterialTests.cpp File Reference
MaterialTests.cpp File Reference
#include <boost/test/unit_test.hpp>
#include <limits>
#include "Acts/Material/Material.hpp"
#include "Acts/Tests/CommonHelpers/FloatComparisons.hpp"
#include "Acts/Tests/CommonHelpers/PredefinedMaterials.hpp"
#include "Acts/Utilities/Units.hpp"
Functions
BOOST_AUTO_TEST_CASE (construct_vacuum)
BOOST_AUTO_TEST_CASE (construct_something)
BOOST_AUTO_TEST_CASE (units)
static Acts::ActsVectorF< 5 > makeSiClassificationNumbers ()
BOOST_AUTO_TEST_CASE (classification_numbers)
Variables
static constexpr auto eps = 2 * std::numeric_limits<float>::epsilon()
static constexpr float SiNe = 1.160954941 / 1_cm3
static constexpr float SiI = 172.042290036_eV
Function Documentation
BOOST_AUTO_TEST_CASE (construct_vacuum)
Definition at line 27 of file MaterialTests.cpp.
View newest version in sPHENIX GitHub at line 27 of file MaterialTests.cpp
BOOST_AUTO_TEST_CASE (construct_something)
Definition at line 33 of file MaterialTests.cpp.
View newest version in sPHENIX GitHub at line 33 of file MaterialTests.cpp
BOOST_AUTO_TEST_CASE (units)
Definition at line 39 of file MaterialTests.cpp.
View newest version in sPHENIX GitHub at line 39 of file MaterialTests.cpp
References Acts::Material::Ar(), CHECK_CLOSE_REL, eps, Acts::Material::L0(), Acts::Test::makeSilicon(), Acts::Material::massDensity(), Acts::Material::meanExcitationEnergy(), Acts::Material::molarElectronDensity(), SiI, SiNe, Acts::Material::X0(), and Acts::Material::Z().
BOOST_AUTO_TEST_CASE (classification_numbers)
Definition at line 70 of file MaterialTests.cpp.
View newest version in sPHENIX GitHub at line 70 of file MaterialTests.cpp
References CHECK_CLOSE_REL, Acts::Material::classificationNumbers(), eps, makeSiClassificationNumbers(), and Acts::Test::makeSilicon().
static Acts::ActsVectorF<5> makeSiClassificationNumbers () static
Definition at line 60 of file MaterialTests.cpp.
View newest version in sPHENIX GitHub at line 60 of file MaterialTests.cpp
References Acts::Material::Ar(), Acts::Material::eAr, Acts::Material::eL0, Acts::Material::eRho, Acts::Material::eX0, Acts::Material::eZ, Acts::Material::L0(), Acts::Test::makeSilicon(), Acts::Material::massDensity(), Acts::Test::values, Acts::Material::X0(), and Acts::Material::Z().
Referenced by BOOST_AUTO_TEST_CASE().
Variable Documentation
constexpr auto eps = 2 * std::numeric_limits<float>::epsilon() static
Definition at line 20 of file MaterialTests.cpp.
View newest version in sPHENIX GitHub at line 20 of file MaterialTests.cpp
Referenced by BOOST_AUTO_TEST_CASE().
constexpr float SiI = 172.042290036_eV static
Definition at line 23 of file MaterialTests.cpp.
View newest version in sPHENIX GitHub at line 23 of file MaterialTests.cpp
Referenced by BOOST_AUTO_TEST_CASE().
constexpr float SiNe = 1.160954941 / 1_cm3 static
Definition at line 22 of file MaterialTests.cpp.
View newest version in sPHENIX GitHub at line 22 of file MaterialTests.cpp
Referenced by BOOST_AUTO_TEST_CASE().