EIC Software: LqstCell Class Reference
LqstCell Class Reference
#include <EicRoot/blob/master/eic/detectors/lqst/LqstGeoParData.h>
Public Member Functions
LqstCell ()
LqstCell (const char *name)
virtual ~LqstCell ()
void set_localX (double x)
void set_localY (double y)
void set_localZ (double z)
void set_localAngle (double a)
TGeoVolume * createCell (LqstGeoParData *detector, TString name)
TGeoVolume * createCell (LqstGeoParData *detector, TString name, double length)
Private Member Functions
ClassDef (LqstCell, 1)
Private Attributes
double posX
double posY
double posZ
double angle
TGeoVolume * mCell
Friends
class LqstGeoParData
Detailed Description
Definition at line 127 of file LqstGeoParData.h.
View newest version in sPHENIX GitHub at line 127 of file LqstGeoParData.h
Constructor & Destructor Documentation
LqstCell::LqstCell () inline
Definition at line 133 of file LqstGeoParData.h.
View newest version in sPHENIX GitHub at line 133 of file LqstGeoParData.h
LqstCell::LqstCell (const char * name) inline
Definition at line 135 of file LqstGeoParData.h.
View newest version in sPHENIX GitHub at line 135 of file LqstGeoParData.h
virtual LqstCell::~LqstCell () inline virtual
Definition at line 145 of file LqstGeoParData.h.
View newest version in sPHENIX GitHub at line 145 of file LqstGeoParData.h
Member Function Documentation
LqstCell::ClassDef (LqstCell , 1) private
TGeoVolume * LqstCell::createCell (LqstGeoParData * detector, TString name)
Definition at line 19 of file LqstGeoParData.cxx.
View newest version in sPHENIX GitHub at line 19 of file LqstGeoParData.cxx
References _DIAMOND_, LqstGeoParData::get_cellFaceLength(), LqstGeoParData::get_cellFaceSize(), and EicGeoParData::GetMedium().
TGeoVolume * LqstCell::createCell (LqstGeoParData * detector, TString name, double length)
Definition at line 46 of file LqstGeoParData.cxx.
View newest version in sPHENIX GitHub at line 46 of file LqstGeoParData.cxx
References _DIAMOND_, LqstGeoParData::get_cellFaceSize(), EicGeoParData::GetMedium(), and name.
void LqstCell::set_localAngle (double a) inline
Definition at line 155 of file LqstGeoParData.h.
View newest version in sPHENIX GitHub at line 155 of file LqstGeoParData.h
References angle.
void LqstCell::set_localX (double x) inline
Definition at line 152 of file LqstGeoParData.h.
View newest version in sPHENIX GitHub at line 152 of file LqstGeoParData.h
References posX, and x.
void LqstCell::set_localY (double y) inline
Definition at line 153 of file LqstGeoParData.h.
View newest version in sPHENIX GitHub at line 153 of file LqstGeoParData.h
References posY, and y.
void LqstCell::set_localZ (double z) inline
Definition at line 154 of file LqstGeoParData.h.
View newest version in sPHENIX GitHub at line 154 of file LqstGeoParData.h
References posZ, and z.
Friends And Related Function Documentation
friend class LqstGeoParData friend
Definition at line 130 of file LqstGeoParData.h.
View newest version in sPHENIX GitHub at line 130 of file LqstGeoParData.h
Member Data Documentation
double LqstCell::angle private
Definition at line 166 of file LqstGeoParData.h.
View newest version in sPHENIX GitHub at line 166 of file LqstGeoParData.h
Referenced by LqstGeoParData::set_angle(), and set_localAngle().
TGeoVolume* LqstCell::mCell private
Definition at line 168 of file LqstGeoParData.h.
View newest version in sPHENIX GitHub at line 168 of file LqstGeoParData.h
double LqstCell::posX private
Definition at line 165 of file LqstGeoParData.h.
View newest version in sPHENIX GitHub at line 165 of file LqstGeoParData.h
Referenced by set_localX().
double LqstCell::posY private
Definition at line 165 of file LqstGeoParData.h.
View newest version in sPHENIX GitHub at line 165 of file LqstGeoParData.h
Referenced by set_localY().
double LqstCell::posZ private
Definition at line 165 of file LqstGeoParData.h.
View newest version in sPHENIX GitHub at line 165 of file LqstGeoParData.h
Referenced by set_localZ().
The documentation for this class was generated from the following files:
EicRoot/blob/master/eic/detectors/lqst/LqstGeoParData.h
EicRoot/blob/master/eic/detectors/lqst/LqstGeoParData.cxx