EIC Software: Acts::Test::PropagatorState::Stepper Struct Reference
Acts::Test::PropagatorState::Stepper Struct Reference
This is a simple cache struct to mimic a Stepper.
Classes
struct State
Public Types
using Jacobian = BoundMatrix
using Covariance = BoundSymMatrix
using BoundState = std::tuple< BoundParameters, Jacobian, double >
using CurvilinearState = std::tuple< CurvilinearParameters, Jacobian, double >
using BField = int
template<typename , typename >
using return_parameter_type = void
Public Member Functions
Vector3D position (const State &state) const
Global particle position accessor.
Vector3D direction (const State &state) const
Momentum direction accessor.
double momentum (const State &state) const
Momentum accessor.
double charge (const State &state) const
Charge access.
double time (const State &state) const
Time access.
double overstepLimit (const State &) const
Overstep limit access.
Intersection::Status updateSurfaceStatus (State &state, const Surface &surface, const BoundaryCheck &bcheck) const
template<typename object_intersection_t >
void updateStepSize (State &state, const object_intersection_t &oIntersection, bool release=true) const
void setStepSize (State &state, double stepSize, ConstrainedStep::Type stype=ConstrainedStep::actor) const
void releaseStepSize (State &state) const
std::string outputStepSize (const State &state) const
BoundState boundState (State &state, const Surface &surface) const
CurvilinearState curvilinearState (State &state) const
void update (State &, const BoundParameters &) const
void update (State &, const Vector3D &, const Vector3D &, double, double) const
void covarianceTransport (State &) const
void covarianceTransport (State &, const Surface &) const
Vector3D getField (State &, const Vector3D &) const
Detailed Description
This is a simple cache struct to mimic a Stepper.
Definition at line 44 of file NavigatorTests.cpp.
View newest version in sPHENIX GitHub at line 44 of file NavigatorTests.cpp
Member Typedef Documentation
using Acts::Test::PropagatorState::Stepper::BField = int
Definition at line 51 of file NavigatorTests.cpp.
View newest version in sPHENIX GitHub at line 51 of file NavigatorTests.cpp
using Acts::Test::PropagatorState::Stepper::BoundState = std::tuple<BoundParameters, Jacobian, double>
Definition at line 48 of file NavigatorTests.cpp.
View newest version in sPHENIX GitHub at line 48 of file NavigatorTests.cpp
using Acts::Test::PropagatorState::Stepper::Covariance = BoundSymMatrix
Definition at line 47 of file NavigatorTests.cpp.
View newest version in sPHENIX GitHub at line 47 of file NavigatorTests.cpp
using Acts::Test::PropagatorState::Stepper::CurvilinearState = std::tuple<CurvilinearParameters, Jacobian, double>
Definition at line 50 of file NavigatorTests.cpp.
View newest version in sPHENIX GitHub at line 50 of file NavigatorTests.cpp
using Acts::Test::PropagatorState::Stepper::Jacobian = BoundMatrix
Definition at line 46 of file NavigatorTests.cpp.
View newest version in sPHENIX GitHub at line 46 of file NavigatorTests.cpp
template<typename , typename > using Acts::Test::PropagatorState::Stepper::return_parameter_type = void
Definition at line 54 of file NavigatorTests.cpp.
View newest version in sPHENIX GitHub at line 54 of file NavigatorTests.cpp
Member Function Documentation
BoundState Acts::Test::PropagatorState::Stepper::boundState (State & state, const Surface & surface) const inline
Definition at line 141 of file NavigatorTests.cpp.
View newest version in sPHENIX GitHub at line 141 of file NavigatorTests.cpp
References Acts::Test::PropagatorState::Stepper::State::dir, Acts::Surface::getSharedPtr(), Acts::Test::PropagatorState::Stepper::State::p, Dataset::parameters, Acts::Test::PropagatorState::Stepper::State::pathAccumulated, Acts::Test::PropagatorState::Stepper::State::pos, Acts::Test::PropagatorState::Stepper::State::q, Acts::Test::PropagatorState::Stepper::State::t, and Acts::tgContext.
double Acts::Test::PropagatorState::Stepper::charge (const State & state) const inline
Charge access.
Definition at line 102 of file NavigatorTests.cpp.
View newest version in sPHENIX GitHub at line 102 of file NavigatorTests.cpp
References Acts::Test::PropagatorState::Stepper::State::q.
void Acts::Test::PropagatorState::Stepper::covarianceTransport (State &) const inline
Definition at line 165 of file NavigatorTests.cpp.
View newest version in sPHENIX GitHub at line 165 of file NavigatorTests.cpp
void Acts::Test::PropagatorState::Stepper::covarianceTransport (State & , const Surface &) const inline
Definition at line 167 of file NavigatorTests.cpp.
View newest version in sPHENIX GitHub at line 167 of file NavigatorTests.cpp
CurvilinearState Acts::Test::PropagatorState::Stepper::curvilinearState (State & state) const inline
Definition at line 150 of file NavigatorTests.cpp.
View newest version in sPHENIX GitHub at line 150 of file NavigatorTests.cpp
References Acts::Test::PropagatorState::Stepper::State::dir, Acts::Test::PropagatorState::Stepper::State::p, Dataset::parameters, Acts::Test::PropagatorState::Stepper::State::pathAccumulated, Acts::Test::PropagatorState::Stepper::State::pos, Acts::Test::PropagatorState::Stepper::State::q, and Acts::Test::PropagatorState::Stepper::State::t.
Vector3D Acts::Test::PropagatorState::Stepper::direction (const State & state) const inline
Momentum direction accessor.
Definition at line 96 of file NavigatorTests.cpp.
View newest version in sPHENIX GitHub at line 96 of file NavigatorTests.cpp
References Acts::Test::PropagatorState::Stepper::State::dir.
Vector3D Acts::Test::PropagatorState::Stepper::getField (State & , const Vector3D &) const inline
Definition at line 170 of file NavigatorTests.cpp.
View newest version in sPHENIX GitHub at line 170 of file NavigatorTests.cpp
double Acts::Test::PropagatorState::Stepper::momentum (const State & state) const inline
Momentum accessor.
Definition at line 99 of file NavigatorTests.cpp.
View newest version in sPHENIX GitHub at line 99 of file NavigatorTests.cpp
References Acts::Test::PropagatorState::Stepper::State::p.
std::string Acts::Test::PropagatorState::Stepper::outputStepSize (const State & state) const inline
Definition at line 137 of file NavigatorTests.cpp.
View newest version in sPHENIX GitHub at line 137 of file NavigatorTests.cpp
References Acts::Test::PropagatorState::Stepper::State::stepSize, and Acts::ConstrainedStep::toString().
double Acts::Test::PropagatorState::Stepper::overstepLimit (const State &) const inline
Overstep limit access.
Definition at line 108 of file NavigatorTests.cpp.
View newest version in sPHENIX GitHub at line 108 of file NavigatorTests.cpp
References Acts::s_onSurfaceTolerance.
Vector3D Acts::Test::PropagatorState::Stepper::position (const State & state) const inline
Global particle position accessor.
Definition at line 93 of file NavigatorTests.cpp.
View newest version in sPHENIX GitHub at line 93 of file NavigatorTests.cpp
References Acts::Test::PropagatorState::Stepper::State::pos.
void Acts::Test::PropagatorState::Stepper::releaseStepSize (State & state) const inline
Definition at line 133 of file NavigatorTests.cpp.
View newest version in sPHENIX GitHub at line 133 of file NavigatorTests.cpp
References Acts::ConstrainedStep::actor, Acts::ConstrainedStep::release(), and Acts::Test::PropagatorState::Stepper::State::stepSize.
void Acts::Test::PropagatorState::Stepper::setStepSize (State & state, double stepSize, ConstrainedStep::Type stype = ConstrainedStep::actor) const inline
Definition at line 126 of file NavigatorTests.cpp.
View newest version in sPHENIX GitHub at line 126 of file NavigatorTests.cpp
References Acts::Test::PropagatorState::Stepper::State::previousStepSize, Acts::Test::PropagatorState::Stepper::State::stepSize, and Acts::ConstrainedStep::update().
double Acts::Test::PropagatorState::Stepper::time (const State & state) const inline
Time access.
Definition at line 105 of file NavigatorTests.cpp.
View newest version in sPHENIX GitHub at line 105 of file NavigatorTests.cpp
References Acts::Test::PropagatorState::Stepper::State::t.
void Acts::Test::PropagatorState::Stepper::update (State & , const BoundParameters &) const inline
Definition at line 159 of file NavigatorTests.cpp.
View newest version in sPHENIX GitHub at line 159 of file NavigatorTests.cpp
void Acts::Test::PropagatorState::Stepper::update (State & , const Vector3D & , const Vector3D & , double , double) const inline
Definition at line 161 of file NavigatorTests.cpp.
View newest version in sPHENIX GitHub at line 161 of file NavigatorTests.cpp
template<typename object_intersection_t > void Acts::Test::PropagatorState::Stepper::updateStepSize (State & state, const object_intersection_t & oIntersection, bool release = true) const inline
Definition at line 120 of file NavigatorTests.cpp.
View newest version in sPHENIX GitHub at line 120 of file NavigatorTests.cpp
Intersection::Status Acts::Test::PropagatorState::Stepper::updateSurfaceStatus (State & state, const Surface & surface, const BoundaryCheck & bcheck) const inline
Definition at line 112 of file NavigatorTests.cpp.
View newest version in sPHENIX GitHub at line 112 of file NavigatorTests.cpp
The documentation for this struct was generated from the following file:
fun4all_acts/blob/master/Tests/UnitTests/Core/Propagator/NavigatorTests.cpp