EIC Software: FairMCApplication Class Reference
FairMCApplication Class Reference
#include <EicRoot/blob/master/base/FairMCApplication.h>
Public Member Functions
FairMCApplication (const char *name, const char *title, TObjArray *ModList, const char *MatName)
FairMCApplication ()
virtual ~FairMCApplication ()
virtual void AddDecayModes ()
virtual void AddParticles ()
virtual void AddIons ()
void AddTask (TTask *fTask)
virtual void BeginEvent ()
virtual void BeginPrimary ()
virtual void ConstructGeometry ()
virtual void ConstructOpGeometry ()
virtual void Field (const Double_t *x, Double_t *b) const
virtual void FinishEvent ()
virtual void FinishPrimary ()
void FinishRun ()
virtual void GeneratePrimaries ()
FairDetector * GetDetector (const char *DetName)
FairField * GetField ()
FairPrimaryGenerator * GetGenerator ()
TTask * GetListOfTasks ()
FairGenericStack * GetStack ()
TChain * GetChain ()
virtual void InitGeometry ()
void InitMC (const char *setup, const char *cuts)
void InitTasks ()
virtual void PostTrack ()
virtual void PreTrack ()
void RunMC (Int_t nofEvents)
void SetField (FairField *field)
void SetGenerator (FairPrimaryGenerator *fxGenerator)
void SetParTask ()
void SetPythiaDecayer (Bool_t decayer)
void SetPythiaDecayerConfig (const TString decayerConf)
void SetRadiationLengthReg (Bool_t RadLen)
void SetRadiationMapReg (Bool_t RadMap)
void SetTrackingDebugMode (Bool_t set)
void SetUserDecay (Bool_t decay)
void SetUserDecayConfig (const TString decayerConf)
virtual void Stepping ()
virtual void StopRun ()
virtual Double_t TrackingRmax () const
virtual Double_t TrackingZmax () const
void AddMeshList (TObjArray *meshList)
Static Public Member Functions
static FairMCApplication * Instance ()
Protected Attributes
std::map< Int_t, Int_t > fModVolMap
std::map< Int_t, Int_t >::iterator fModVolIter
Private Member Functions
void RegisterStack ()
Int_t GetIonPdg (Int_t z, Int_t a) const
ClassDef(FairMCApplication,
2) private FairMCApplication & operator= (const FairMCApplication &)
Private Attributes
TIterator * fActDetIter
TRefArray * fActiveDetectors
FairTask * fFairTaskList
TIterator * fDetIter
TRefArray * fDetectors
TRefArray * fDetMap
FairLogger * fLogger
TIterator * fModIter
TObjArray * fModules
Int_t fNoSenVolumes
Bool_t fPythiaDecayer
TString fPythiaDecayerConfig
FairGenericStack * fStack
FairRootManager * fRootManager
TRefArray * fSenVolumes
FairField * fxField
FairPrimaryGenerator * fEvGen
Int_t fMcVersion
FairTrajFilter * fTrajFilter
Bool_t fTrajAccepted
Bool_t fUserDecay
TString fUserDecayConfig
Bool_t fDebug
FairVolume * fDisVol
FairDetector * fDisDet
std::multimap< Int_t,
FairVolume * > fVolMap
std::multimap< Int_t,
FairVolume * >::iterator fVolIter
TLorentzVector fTrkPos
Bool_t fRadLength
FairRadLenManager * fRadLenMan
Bool_t fRadMap
FairRadMapManager * fRadMapMan
FairRadGridManager * fRadGridMan
FairEventHeader * fEventHeader
FairMCEventHeader * fMCEventHeader
FairRunInfo fRunInfo
Detailed Description
The Main Application (Interface to MonteCarlo application)
Author
M. Al-Turany, D. Bertini
Version
0.1
Since
12.01.04
Definition at line 43 of file FairMCApplication.h.
View newest version in sPHENIX GitHub at line 43 of file FairMCApplication.h
Constructor & Destructor Documentation
FairMCApplication::FairMCApplication (const char * name, const char * title, TObjArray * ModList, const char * MatName)
Standard constructor
Parameters
name name
title title
ModList a TObjArray containing all detectors and modules used in this simulation
MatName material file name
Definition at line 58 of file FairMCApplication.cxx.
View newest version in sPHENIX GitHub at line 58 of file FairMCApplication.cxx
References fActDetIter, fActiveDetectors, fDetectors, fDetIter, fDetMap, fDisDet, fDisVol, fFairTaskList, fMcVersion, fModIter, fModules, fRootManager, fTrajFilter, FairRootManager::Instance(), and FairModule::IsActive().
FairMCApplication::FairMCApplication ()
default constructor
Definition at line 135 of file FairMCApplication.cxx.
View newest version in sPHENIX GitHub at line 135 of file FairMCApplication.cxx
FairMCApplication::~FairMCApplication () virtual
default destructor
Definition at line 179 of file FairMCApplication.cxx.
View newest version in sPHENIX GitHub at line 179 of file FairMCApplication.cxx
References fActDetIter, fActiveDetectors, fDetectors, and fStack.
Member Function Documentation
void FairMCApplication::AddDecayModes () virtual
Definition at line 903 of file FairMCApplication.cxx.
View newest version in sPHENIX GitHub at line 903 of file FairMCApplication.cxx
References fPythiaDecayer, fPythiaDecayerConfig, fUserDecay, and fUserDecayConfig.
Referenced by AddParticles().
void FairMCApplication::AddIons () virtual
Add user defined ions (optional)
Initialize the event generator
Definition at line 799 of file FairMCApplication.cxx.
View newest version in sPHENIX GitHub at line 799 of file FairMCApplication.cxx
References fEvGen, fLogger, FairIon::GetA(), FairIon::GetExcEnergy(), GetIonPdg(), FairIon::GetMass(), FairIon::GetQ(), FairRunSim::GetUserDefIons(), FairIon::GetZ(), FairLogger::Info(), FairPrimaryGenerator::Init(), FairRunSim::Instance(), and MESSAGE_ORIGIN.
void FairMCApplication::AddMeshList (TObjArray * meshList)
Definition at line 1062 of file FairMCApplication.cxx.
View newest version in sPHENIX GitHub at line 1062 of file FairMCApplication.cxx
References FairRadGridManager::AddMeshList(), and fRadGridMan.
Referenced by FairRunSim::Init().
void FairMCApplication::AddParticles () virtual
Add user defined particles (optional)
Definition at line 839 of file FairMCApplication.cxx.
View newest version in sPHENIX GitHub at line 839 of file FairMCApplication.cxx
References AddDecayModes(), FairParticle::GetBaryon(), FairParticle::GetCharge(), FairParticle::GetConjugation(), FairParticle::GetDecayTime(), FairParticle::GetgParity(), FairParticle::GetiParity(), FairParticle::GetIsospin(), FairParticle::GetIsospinZ(), FairParticle::GetLepton(), FairParticle::GetMass(), FairParticle::GetMCType(), FairParticle::GetName(), FairParticle::GetPDG(), FairParticle::GetPType(), FairParticle::GetSpin(), FairRunSim::GetUserDefIons(), FairRunSim::GetUserDefParticles(), FairParticle::GetWidth(), FairRunSim::Instance(), FairParticle::IsStable(), and particle.
void FairMCApplication::AddTask (TTask * fTask)
*Add user defined Tasks to be executed after each event (optional)
Parameters
fTask,: Task that has to be excuted during simulation
Definition at line 986 of file FairMCApplication.cxx.
View newest version in sPHENIX GitHub at line 986 of file FairMCApplication.cxx
References fFairTaskList, and SetParTask().
Referenced by FairRunSim::Init().
void FairMCApplication::BeginEvent () virtual
Define actions at the beginning of the event
Definition at line 315 of file FairMCApplication.cxx.
View newest version in sPHENIX GitHub at line 315 of file FairMCApplication.cxx
References FairDetector::BeginEvent(), and fActDetIter.
void FairMCApplication::BeginPrimary () virtual
Define actions at the beginning of primary track
Definition at line 334 of file FairMCApplication.cxx.
View newest version in sPHENIX GitHub at line 334 of file FairMCApplication.cxx
References FairDetector::BeginPrimary(), and fActDetIter.
void FairMCApplication::ConstructGeometry () virtual
Construct user geometry
Definition at line 620 of file FairMCApplication.cxx.
View newest version in sPHENIX GitHub at line 620 of file FairMCApplication.cxx
References FairModule::ConstructGeometry(), fModIter, fModVolMap, fNoSenVolumes, fSenVolumes, FairModule::GetModId(), n, and FairModule::svList.
void FairMCApplication::ConstructOpGeometry () virtual
Define parameters for optical processes (optional)
Definition at line 578 of file FairMCApplication.cxx.
View newest version in sPHENIX GitHub at line 578 of file FairMCApplication.cxx
References FairModule::ConstructOpGeometry(), fModIter, FairGeoMedium::getCerenkovPar(), FairGeoLoader::getGeoInterface(), FairGeoMedia::getListOfMedia(), FairGeoInterface::getMedia(), FairGeoMedium::getMediumIndex(), FairGeoMedium::getNpckov(), FairGeoLoader::Instance(), loader, and p.
virtual void FairMCApplication::Field (const Double_t * x, Double_t * b) const virtual
Calculate user field b at point x
void FairMCApplication::FinishEvent () virtual
Define actions at the end of event
Definition at line 509 of file FairMCApplication.cxx.
View newest version in sPHENIX GitHub at line 509 of file FairMCApplication.cxx
References FairDetector::EndOfEvent(), fActDetIter, fActiveDetectors, fFairTaskList, FairRootManager::Fill(), FairGenericStack::FillTrackArray(), FairTask::FinishEvent(), FairDetector::FinishEvent(), fRadLenMan, fRadMapMan, fRootManager, fRunInfo, fStack, fTrajFilter, FairRadLenManager::Reset(), FairRadMapManager::Reset(), FairGenericStack::Reset(), FairTrajFilter::Reset(), FairRunInfo::StoreInfo(), and FairGenericStack::UpdateTrackIndex().
Referenced by StopRun().
void FairMCApplication::FinishPrimary () virtual
Define actions at the end of primary track
Definition at line 473 of file FairMCApplication.cxx.
View newest version in sPHENIX GitHub at line 473 of file FairMCApplication.cxx
References fActDetIter, and FairDetector::FinishPrimary().
void FairMCApplication::FinishRun ()
Define actions at the end of run
Definition at line 242 of file FairMCApplication.cxx.
View newest version in sPHENIX GitHub at line 242 of file FairMCApplication.cxx
References fActDetIter, fFairTaskList, FairDetector::FinishRun(), FairTask::FinishTask(), fRadGridMan, fRootManager, FairMesh::GetMeshFlu(), FairRadGridManager::GetMeshList(), FairMesh::GetMeshSEU(), FairMesh::GetMeshTid(), FairRunSim::GetPrimaryGenerator(), FairPrimaryGenerator::GetTotPrimary(), FairRunSim::Instance(), FairMesh::Scale(), and FairRootManager::Write().
Referenced by RunMC(), and StopRun().
void FairMCApplication::GeneratePrimaries () virtual
Generate primary particles
Definition at line 782 of file FairMCApplication.cxx.
View newest version in sPHENIX GitHub at line 782 of file FairMCApplication.cxx
References fEvGen, fStack, FairPrimaryGenerator::GenerateEvent(), and StopRun().
TChain * FairMCApplication::GetChain ()
Definition at line 1036 of file FairMCApplication.cxx.
View newest version in sPHENIX GitHub at line 1036 of file FairMCApplication.cxx
References fRootManager, and FairRootManager::GetInChain().
FairDetector * FairMCApplication::GetDetector (const char * DetName)
Return detector by name
Definition at line 794 of file FairMCApplication.cxx.
View newest version in sPHENIX GitHub at line 794 of file FairMCApplication.cxx
References fModules.
FairField* FairMCApplication::GetField () inline
Return Field used in simulation
Definition at line 95 of file FairMCApplication.h.
View newest version in sPHENIX GitHub at line 95 of file FairMCApplication.h
References fxField.
FairPrimaryGenerator * FairMCApplication::GetGenerator ()
Return primary generator
Definition at line 976 of file FairMCApplication.cxx.
View newest version in sPHENIX GitHub at line 976 of file FairMCApplication.cxx
References fEvGen.
Int_t FairMCApplication::GetIonPdg (Int_t z, Int_t a) const private
Definition at line 1071 of file FairMCApplication.cxx.
View newest version in sPHENIX GitHub at line 1071 of file FairMCApplication.cxx
Referenced by AddIons().
TTask * FairMCApplication::GetListOfTasks ()
Return list of tasks
Definition at line 1001 of file FairMCApplication.cxx.
View newest version in sPHENIX GitHub at line 1001 of file FairMCApplication.cxx
References fFairTaskList.
FairGenericStack * FairMCApplication::GetStack ()
Definition at line 996 of file FairMCApplication.cxx.
View newest version in sPHENIX GitHub at line 996 of file FairMCApplication.cxx
References fStack.
void FairMCApplication::InitGeometry () virtual
Initialize geometry
Initialize geometry
Register stack and detector collections
Initialize the event generator
Initialize the detectors.
Tasks has to be initialized here, they have access to the detector branches and still can create objects in the tree
There is always a Main Task ! so .. always a InitTasks() is called <D.B>
save Geo Params in Output file
Definition at line 677 of file FairMCApplication.cxx.
View newest version in sPHENIX GitHub at line 677 of file FairMCApplication.cxx
References fActDetIter, fEvGen, fFairTaskList, fLogger, fMCEventHeader, fModIter, fNoSenVolumes, fRadGridMan, fRadLenMan, fRadMapMan, fRootManager, fSenVolumes, fStack, fTrajFilter, fv(), fVolMap, FairVolume::getGeoNode(), FairRunSim::GetMCEventHeader(), FairVolume::getMCid(), FairVolume::getModId(), FairVolume::GetModule(), FairRun::GetRunId(), FairLogger::Info(), FairRadLenManager::Init(), FairRadMapManager::Init(), FairRadGridManager::Init(), FairTrajFilter::Init(), FairDetector::Initialize(), InitTasks(), FairRunSim::Instance(), FairTrajFilter::Instance(), k, MESSAGE_ORIGIN, FairDetector::Register(), FairMCEventHeader::Register(), FairGenericStack::Register(), FairVolume::setCopyNo(), FairPrimaryGenerator::SetEvent(), FairVolume::setMCid(), FairVolume::setModId(), FairVolume::SetModule(), FairRootManager::SetOutTree(), FairMCEventHeader::SetRunID(), FairDetector::SetSpecialPhysicsCuts(), FairRootManager::TruncateBranchNames(), v, FairLogger::Warning(), and FairRootManager::WriteFolder().
void FairMCApplication::InitMC (const char * setup, const char * cuts)
Initialize MC engine
Definition at line 202 of file FairMCApplication.cxx.
View newest version in sPHENIX GitHub at line 202 of file FairMCApplication.cxx
References fLogger, fMcVersion, fStack, fTrajFilter, fxField, FairLogger::Info(), FairTrajFilter::Instance(), and MESSAGE_ORIGIN.
Referenced by FairRunSim::SetMCConfig().
void FairMCApplication::InitTasks ()
Initialize Tasks if any
Definition at line 1023 of file FairMCApplication.cxx.
View newest version in sPHENIX GitHub at line 1023 of file FairMCApplication.cxx
References fFairTaskList, fLogger, FairLogger::Info(), FairTask::InitTask(), FairRun::Instance(), and MESSAGE_ORIGIN.
Referenced by InitGeometry().
FairMCApplication * FairMCApplication::Instance () inline static
Singelton instance
Definition at line 267 of file FairMCApplication.h.
View newest version in sPHENIX GitHub at line 267 of file FairMCApplication.h
ClassDef (FairMCApplication,2) private FairMCApplication& FairMCApplication::operator= (const FairMCApplication &) private
void FairMCApplication::PostTrack () virtual
Define actions at the end of each track
Definition at line 457 of file FairMCApplication.cxx.
View newest version in sPHENIX GitHub at line 457 of file FairMCApplication.cxx
References fActDetIter, and FairDetector::PostTrack().
void FairMCApplication::PreTrack () virtual
Define actions at the beginning of each track
Definition at line 351 of file FairMCApplication.cxx.
View newest version in sPHENIX GitHub at line 351 of file FairMCApplication.cxx
References FairTrajFilter::AddTrack(), fActDetIter, fStack, fTrajAccepted, fTrajFilter, fTrkPos, FairGenericStack::GetCurrentTrack(), FairTrajFilter::IsAccepted(), particle, and FairDetector::PreTrack().
Referenced by Stepping().
void FairMCApplication::RegisterStack () private
Definition at line 193 of file FairMCApplication.cxx.
View newest version in sPHENIX GitHub at line 193 of file FairMCApplication.cxx
References fEvGen, fStack, and FairGenericStack::Register().
void FairMCApplication::RunMC (Int_t nofEvents)
Run the MC engine
Parameters
nofEvents : number of events to simulate
Definition at line 227 of file FairMCApplication.cxx.
View newest version in sPHENIX GitHub at line 227 of file FairMCApplication.cxx
References FinishRun(), fRunInfo, FairRunSim::Instance(), FairRunInfo::Reset(), and FairRunInfo::WriteInfo().
Referenced by FairRunSim::Run().
void FairMCApplication::SetField (FairField * field)
Set the magnetic field for simulation
Parameters
field,: magnetic field
Definition at line 573 of file FairMCApplication.cxx.
View newest version in sPHENIX GitHub at line 573 of file FairMCApplication.cxx
References fxField.
Referenced by FairRunSim::Init().
void FairMCApplication::SetGenerator (FairPrimaryGenerator * fxGenerator)
Set the event generator for simulation
Parameters
fxGenerator,: Event generator(s)
Definition at line 981 of file FairMCApplication.cxx.
View newest version in sPHENIX GitHub at line 981 of file FairMCApplication.cxx
References fEvGen.
Referenced by FairRunSim::Init().
void FairMCApplication::SetParTask ()
Set the parameter containers needed by Tasks(if any)
Definition at line 1007 of file FairMCApplication.cxx.
View newest version in sPHENIX GitHub at line 1007 of file FairMCApplication.cxx
References fFairTaskList, fModIter, FairRun::GetRuntimeDb(), FairRuntimeDb::initContainers(), FairRunSim::Instance(), FairRun::Instance(), FairModule::SetParContainers(), and FairTask::SetParTask().
Referenced by AddTask().
void FairMCApplication::SetPythiaDecayer (Bool_t decayer) inline
Switch for using Pythia as external decayer
Parameters
decayer,: if TRUE pythia will decay particles specifid in the Decay Config macro (see SetPythiaDecayerConfig)
Definition at line 134 of file FairMCApplication.h.
View newest version in sPHENIX GitHub at line 134 of file FairMCApplication.h
References fPythiaDecayer.
Referenced by FairRunSim::Init().
void FairMCApplication::SetPythiaDecayerConfig (const TString decayerConf) inline
set the decay configuration macro to be used by Pythia
Definition at line 138 of file FairMCApplication.h.
View newest version in sPHENIX GitHub at line 138 of file FairMCApplication.h
References fPythiaDecayerConfig.
void FairMCApplication::SetRadiationLengthReg (Bool_t RadLen)
Switch for using the radiation length manager
Definition at line 1042 of file FairMCApplication.cxx.
View newest version in sPHENIX GitHub at line 1042 of file FairMCApplication.cxx
References fRadLength, and fRadLenMan.
Referenced by FairRunSim::Init().
void FairMCApplication::SetRadiationMapReg (Bool_t RadMap)
Switch for using the radiation map manager
Definition at line 1052 of file FairMCApplication.cxx.
View newest version in sPHENIX GitHub at line 1052 of file FairMCApplication.cxx
References fRadMap, and fRadMapMan.
Referenced by FairRunSim::Init().
void FairMCApplication::SetTrackingDebugMode (Bool_t set) inline
Switch for debuging the tracking
Definition at line 150 of file FairMCApplication.h.
View newest version in sPHENIX GitHub at line 150 of file FairMCApplication.h
References fDebug.
Referenced by FairRunSim::SetTrackingDebugMode().
void FairMCApplication::SetUserDecay (Bool_t decay) inline
Switch for using 2 or 3 body phase-space decay
Parameters
decay,: if TRUE 2/3 body phase space decay will be used for particle specified in the User Decay Config macro (see SetUserDecayConfig)
Definition at line 155 of file FairMCApplication.h.
View newest version in sPHENIX GitHub at line 155 of file FairMCApplication.h
References fUserDecay.
Referenced by FairRunSim::Init().
void FairMCApplication::SetUserDecayConfig (const TString decayerConf) inline
set the decay configuration macro to be used by user decay
Definition at line 159 of file FairMCApplication.h.
View newest version in sPHENIX GitHub at line 159 of file FairMCApplication.h
References fUserDecayConfig.
void FairMCApplication::Stepping () virtual
Define action at each step, dispatch the action to the corresponding detectors
Reimplemented in EicMCApplication.
Definition at line 386 of file FairMCApplication.cxx.
View newest version in sPHENIX GitHub at line 386 of file FairMCApplication.cxx
References FairRadLenManager::AddPoint(), FairRadMapManager::AddPoint(), fDisDet, fDisVol, FairRadGridManager::FillMeshList(), fMcVersion, fModVolIter, fModVolMap, fRadGridMan, fRadLenMan, fRadMapMan, fTrajAccepted, fTrajFilter, fTrkPos, fVolIter, fVolMap, FairVolume::getCopyNo(), FairTrajFilter::GetCurrentTrk(), FairVolume::getModId(), FairVolume::GetModule(), FairTrajFilter::GetStepSizeCut(), PreTrack(), FairDetector::ProcessHits(), FairVolume::setCopyNo(), FairVolume::setMCid(), FairVolume::setModId(), and FairVolume::SetModule().
Referenced by EicMCApplication::Stepping().
void FairMCApplication::StopRun () virtual
Stop the run
Definition at line 492 of file FairMCApplication.cxx.
View newest version in sPHENIX GitHub at line 492 of file FairMCApplication.cxx
References FairRootManager::CloseOutFile(), FairRuntimeDb::closeOutput(), exit(), FinishEvent(), FinishRun(), fLogger, fRootManager, fRunInfo, FairRun::GetRuntimeDb(), FairRunSim::Instance(), MESSAGE_ORIGIN, FairLogger::Warning(), FairRootManager::Write(), and FairRunInfo::WriteInfo().
Referenced by GeneratePrimaries().
Double_t FairMCApplication::TrackingRmax () const virtual
Define maximum radius for tracking (optional)
Definition at line 559 of file FairMCApplication.cxx.
View newest version in sPHENIX GitHub at line 559 of file FairMCApplication.cxx
Double_t FairMCApplication::TrackingZmax () const virtual
Define maximum z for tracking (optional)
Definition at line 566 of file FairMCApplication.cxx.
View newest version in sPHENIX GitHub at line 566 of file FairMCApplication.cxx
Member Data Documentation
TIterator* FairMCApplication::fActDetIter private
Iterator for active detector list
Definition at line 179 of file FairMCApplication.h.
View newest version in sPHENIX GitHub at line 179 of file FairMCApplication.h
Referenced by BeginEvent(), BeginPrimary(), FairMCApplication(), FinishEvent(), FinishPrimary(), FinishRun(), InitGeometry(), PostTrack(), PreTrack(), and ~FairMCApplication().
TRefArray* FairMCApplication::fActiveDetectors private
List of active detector
Definition at line 181 of file FairMCApplication.h.
View newest version in sPHENIX GitHub at line 181 of file FairMCApplication.h
Referenced by FairMCApplication(), FinishEvent(), and ~FairMCApplication().
Bool_t FairMCApplication::fDebug private
Debug flag
Definition at line 223 of file FairMCApplication.h.
View newest version in sPHENIX GitHub at line 223 of file FairMCApplication.h
Referenced by SetTrackingDebugMode().
TRefArray* FairMCApplication::fDetectors private
detector list (Passive and Active)
Definition at line 187 of file FairMCApplication.h.
View newest version in sPHENIX GitHub at line 187 of file FairMCApplication.h
Referenced by FairMCApplication(), and ~FairMCApplication().
TIterator* FairMCApplication::fDetIter private
Iterator for detector list (Passive and Active)
Definition at line 185 of file FairMCApplication.h.
View newest version in sPHENIX GitHub at line 185 of file FairMCApplication.h
Referenced by FairMCApplication().
TRefArray* FairMCApplication::fDetMap private
Map used for dispatcher
Definition at line 189 of file FairMCApplication.h.
View newest version in sPHENIX GitHub at line 189 of file FairMCApplication.h
Referenced by FairMCApplication().
FairDetector* FairMCApplication::fDisDet private
dispatcher internal use
Definition at line 227 of file FairMCApplication.h.
View newest version in sPHENIX GitHub at line 227 of file FairMCApplication.h
Referenced by FairMCApplication(), and Stepping().
FairVolume* FairMCApplication::fDisVol private
dispatcher internal use
Definition at line 225 of file FairMCApplication.h.
View newest version in sPHENIX GitHub at line 225 of file FairMCApplication.h
Referenced by FairMCApplication(), and Stepping().
FairEventHeader* FairMCApplication::fEventHeader private
Definition at line 252 of file FairMCApplication.h.
View newest version in sPHENIX GitHub at line 252 of file FairMCApplication.h
FairPrimaryGenerator* FairMCApplication::fEvGen private
Primary generator
Definition at line 211 of file FairMCApplication.h.
View newest version in sPHENIX GitHub at line 211 of file FairMCApplication.h
Referenced by AddIons(), GeneratePrimaries(), GetGenerator(), InitGeometry(), RegisterStack(), and SetGenerator().
FairTask* FairMCApplication::fFairTaskList private
List of FairTask
Definition at line 183 of file FairMCApplication.h.
View newest version in sPHENIX GitHub at line 183 of file FairMCApplication.h
Referenced by AddTask(), FairMCApplication(), FinishEvent(), FinishRun(), GetListOfTasks(), InitGeometry(), InitTasks(), and SetParTask().
FairLogger* FairMCApplication::fLogger private
Fair Logger
Definition at line 191 of file FairMCApplication.h.
View newest version in sPHENIX GitHub at line 191 of file FairMCApplication.h
Referenced by AddIons(), InitGeometry(), InitMC(), InitTasks(), and StopRun().
FairMCEventHeader* FairMCApplication::fMCEventHeader private
Definition at line 254 of file FairMCApplication.h.
View newest version in sPHENIX GitHub at line 254 of file FairMCApplication.h
Referenced by InitGeometry().
Int_t FairMCApplication::fMcVersion private
MC Engine 1= Geant3, 2 = Geant4
Definition at line 213 of file FairMCApplication.h.
View newest version in sPHENIX GitHub at line 213 of file FairMCApplication.h
Referenced by FairMCApplication(), InitMC(), and Stepping().
TIterator* FairMCApplication::fModIter private
Iterator for Module list
Definition at line 193 of file FairMCApplication.h.
View newest version in sPHENIX GitHub at line 193 of file FairMCApplication.h
Referenced by ConstructGeometry(), ConstructOpGeometry(), FairMCApplication(), InitGeometry(), and SetParTask().
TObjArray* FairMCApplication::fModules private
Module list in simulation
Definition at line 195 of file FairMCApplication.h.
View newest version in sPHENIX GitHub at line 195 of file FairMCApplication.h
Referenced by FairMCApplication(), and GetDetector().
std::map<Int_t, Int_t >::iterator FairMCApplication::fModVolIter protected
dispatcher internal use RadLen
Definition at line 237 of file FairMCApplication.h.
View newest version in sPHENIX GitHub at line 237 of file FairMCApplication.h
Referenced by EicMCApplication::Stepping(), and Stepping().
std::map<Int_t, Int_t > FairMCApplication::fModVolMap protected
Track position dispatcher internal use RadLeng
Definition at line 235 of file FairMCApplication.h.
View newest version in sPHENIX GitHub at line 235 of file FairMCApplication.h
Referenced by ConstructGeometry(), EicMCApplication::Stepping(), and Stepping().
Int_t FairMCApplication::fNoSenVolumes private
Number of sensetive volumes in simulation session
Definition at line 197 of file FairMCApplication.h.
View newest version in sPHENIX GitHub at line 197 of file FairMCApplication.h
Referenced by ConstructGeometry(), and InitGeometry().
Bool_t FairMCApplication::fPythiaDecayer private
flag for using Pythia as external decayer
Definition at line 199 of file FairMCApplication.h.
View newest version in sPHENIX GitHub at line 199 of file FairMCApplication.h
Referenced by AddDecayModes(), and SetPythiaDecayer().
TString FairMCApplication::fPythiaDecayerConfig private
Pythia decay config macro
Definition at line 201 of file FairMCApplication.h.
View newest version in sPHENIX GitHub at line 201 of file FairMCApplication.h
Referenced by AddDecayModes(), and SetPythiaDecayerConfig().
FairRadGridManager* FairMCApplication::fRadGridMan private
Radiation map Grid Manager
Definition at line 250 of file FairMCApplication.h.
View newest version in sPHENIX GitHub at line 250 of file FairMCApplication.h
Referenced by AddMeshList(), FinishRun(), InitGeometry(), and Stepping().
Bool_t FairMCApplication::fRadLength private
Flag for Radiation length register mode
Definition at line 241 of file FairMCApplication.h.
View newest version in sPHENIX GitHub at line 241 of file FairMCApplication.h
Referenced by SetRadiationLengthReg().
FairRadLenManager* FairMCApplication::fRadLenMan private
Radiation length Manager
Definition at line 244 of file FairMCApplication.h.
View newest version in sPHENIX GitHub at line 244 of file FairMCApplication.h
Referenced by FinishEvent(), InitGeometry(), SetRadiationLengthReg(), and Stepping().
Bool_t FairMCApplication::fRadMap private
Flag for Radiation map register mode
Definition at line 246 of file FairMCApplication.h.
View newest version in sPHENIX GitHub at line 246 of file FairMCApplication.h
Referenced by SetRadiationMapReg().
FairRadMapManager* FairMCApplication::fRadMapMan private
Radiation Map Manager
Definition at line 248 of file FairMCApplication.h.
View newest version in sPHENIX GitHub at line 248 of file FairMCApplication.h
Referenced by FinishEvent(), InitGeometry(), SetRadiationMapReg(), and Stepping().
FairRootManager* FairMCApplication::fRootManager private
Pointer to thr I/O Manager
Definition at line 205 of file FairMCApplication.h.
View newest version in sPHENIX GitHub at line 205 of file FairMCApplication.h
Referenced by FairMCApplication(), FinishEvent(), FinishRun(), GetChain(), InitGeometry(), and StopRun().
FairRunInfo FairMCApplication::fRunInfo private
Definition at line 262 of file FairMCApplication.h.
View newest version in sPHENIX GitHub at line 262 of file FairMCApplication.h
Referenced by FinishEvent(), RunMC(), and StopRun().
TRefArray* FairMCApplication::fSenVolumes private
List of sensetive volumes in all detectors
Definition at line 207 of file FairMCApplication.h.
View newest version in sPHENIX GitHub at line 207 of file FairMCApplication.h
Referenced by ConstructGeometry(), and InitGeometry().
FairGenericStack* FairMCApplication::fStack private
Simulation Stack
Definition at line 203 of file FairMCApplication.h.
View newest version in sPHENIX GitHub at line 203 of file FairMCApplication.h
Referenced by FinishEvent(), GeneratePrimaries(), GetStack(), InitGeometry(), InitMC(), PreTrack(), RegisterStack(), and ~FairMCApplication().
Bool_t FairMCApplication::fTrajAccepted private
Flag for accepted tracks for visualization
Definition at line 217 of file FairMCApplication.h.
View newest version in sPHENIX GitHub at line 217 of file FairMCApplication.h
Referenced by PreTrack(), and Stepping().
FairTrajFilter* FairMCApplication::fTrajFilter private
Track visualization manager
Definition at line 215 of file FairMCApplication.h.
View newest version in sPHENIX GitHub at line 215 of file FairMCApplication.h
Referenced by FairMCApplication(), FinishEvent(), InitGeometry(), InitMC(), PreTrack(), and Stepping().
TLorentzVector FairMCApplication::fTrkPos private
Definition at line 239 of file FairMCApplication.h.
View newest version in sPHENIX GitHub at line 239 of file FairMCApplication.h
Referenced by PreTrack(), and Stepping().
Bool_t FairMCApplication::fUserDecay private
Flag for using user decay
Definition at line 219 of file FairMCApplication.h.
View newest version in sPHENIX GitHub at line 219 of file FairMCApplication.h
Referenced by AddDecayModes(), and SetUserDecay().
TString FairMCApplication::fUserDecayConfig private
User decay config macro
Definition at line 221 of file FairMCApplication.h.
View newest version in sPHENIX GitHub at line 221 of file FairMCApplication.h
Referenced by AddDecayModes(), and SetUserDecayConfig().
std::multimap<Int_t, FairVolume* >::iterator FairMCApplication::fVolIter private
dispatcher internal use
Definition at line 231 of file FairMCApplication.h.
View newest version in sPHENIX GitHub at line 231 of file FairMCApplication.h
Referenced by Stepping().
std::multimap<Int_t, FairVolume* > FairMCApplication::fVolMap private
dispatcher internal use
Definition at line 229 of file FairMCApplication.h.
View newest version in sPHENIX GitHub at line 229 of file FairMCApplication.h
Referenced by InitGeometry(), and Stepping().
FairField* FairMCApplication::fxField private
Magnetic Field Pointer
Definition at line 209 of file FairMCApplication.h.
View newest version in sPHENIX GitHub at line 209 of file FairMCApplication.h
Referenced by GetField(), InitMC(), and SetField().
The documentation for this class was generated from the following files:
EicRoot/blob/master/base/FairMCApplication.h
EicRoot/blob/master/base/FairMCApplication.cxx