EIC Software: delphes_EIC/blob/master/SimpleAnalysis/scripts/CharmTagPlots.C File Reference
CharmTagPlots.C File Reference
#include "TROOT.h"
#include "TChain.h"
#include "TEfficiency.h"
#include "TH1.h"
#include "TGraphErrors.h"
#include "TCut.h"
#include "TCanvas.h"
#include "TStyle.h"
#include "TLegend.h"
#include "TMath.h"
#include "TLine.h"
#include "TLatex.h"
#include "TRatioPlot.h"
#include <glob.h>
#include <iostream>
#include <iomanip>
#include <vector>
Classes
struct plot_config
Functions
Int_t getHistUID ()
float smart_legend_x (float x_trial, float x_width)
float smart_legend_y (float y_trial, float y_height)
TLegend * smart_legend (std::string where="upper right", float legend_width=0.30, float legend_height=0.10)
void set_axis_range (TH1F *hist, float min, float max, std::string which="X")
template<class T >
void configure_plot (T *object, plot_config options, std::string which="")
TLatex make_title ()
std::vector< std::string > fileVector (const std::string &pattern)
TEfficiency DifferentialTaggingEfficiency (TTree *data, plot_config draw_config, TString xvar, TString which="all", TString taggers="jet_sip3dtag")
TH1F * DifferentialTaggingYield (TTree *data, plot_config draw_config, TString xvar, TString which="all", TString taggers="jet_sip3dtag")
void DrawTagEfficiencyPlot (TCanvas *pad, TTree *data, plot_config draw_config, TString xvar)
void DrawTagYieldPlot (TCanvas *pad, TTree *data, plot_config draw_config, TString xvar)
float CutEfficiency (TTree *data, TCut cut, TString cutdesc="")
void CharmTagPlots (TString dir, TString input, TString xvar, TString filePattern="*/out.root")
Variables
float u_fb = 1.0
float u_mb = 1.0e12*u_fb
float xsec_e10_p275_CC_DIS = 1.47637e-08*u_mb
float lumi = 100*u_fb
Int_t histUID = 0
float n_gen = -1
Function Documentation
void CharmTagPlots (TString dir, TString input, TString xvar, TString filePattern = "*/out.root")
Definition at line 369 of file CharmTagPlots.C.
View newest version in sPHENIX GitHub at line 369 of file CharmTagPlots.C
References CutEfficiency(), charm_jet_strange_helicity::dA, DifferentialTaggingYield(), charm_jet_strange_helicity::draw_config, DrawTagEfficiencyPlot(), DrawTagYieldPlot(), analysis::e, eicpy.qaplots::file, eicpy.build::files, fileVector(), getHistUID(), plot_config::htemplate, plot_config::logx, plot_config::logy, lumi, make_title(), n_gen, charm_jet_strange_helicity::polarization, charm_jet_strange_helicity::polarization_e, charm_jet_strange_helicity::polarization_p, rp(), set_axis_range(), smart_legend(), charm_jet_strange_helicity::xbins, plot_config::xlimits, xsec_e10_p275_CC_DIS, plot_config::xtitle, plot_config::ylimits, and plot_config::ytitle.
template<class T > void configure_plot (T * object, plot_config options, std::string which = "")
Definition at line 129 of file CharmTagPlots.C.
View newest version in sPHENIX GitHub at line 129 of file CharmTagPlots.C
float CutEfficiency (TTree * data, TCut cut, TString cutdesc = "")
Definition at line 349 of file CharmTagPlots.C.
View newest version in sPHENIX GitHub at line 349 of file CharmTagPlots.C
References incremental_prev_tag::desc, and n_gen.
Referenced by CharmTagPlots().
TEfficiency DifferentialTaggingEfficiency (TTree * data, plot_config draw_config, TString xvar, TString which = "all", TString taggers = "jet_sip3dtag")
Definition at line 176 of file CharmTagPlots.C.
View newest version in sPHENIX GitHub at line 176 of file CharmTagPlots.C
References histUID, and plot_config::htemplate.
Referenced by DrawTagEfficiencyPlot().
TH1F* DifferentialTaggingYield (TTree * data, plot_config draw_config, TString xvar, TString which = "all", TString taggers = "jet_sip3dtag")
Definition at line 215 of file CharmTagPlots.C.
View newest version in sPHENIX GitHub at line 215 of file CharmTagPlots.C
References histUID, plot_config::htemplate, lumi, and xsec_e10_p275_CC_DIS.
Referenced by CharmTagPlots(), and DrawTagYieldPlot().
void DrawTagEfficiencyPlot (TCanvas * pad, TTree * data, plot_config draw_config, TString xvar)
Definition at line 249 of file CharmTagPlots.C.
View newest version in sPHENIX GitHub at line 249 of file CharmTagPlots.C
References DifferentialTaggingEfficiency(), charm_jet_strange_helicity::draw_config, make_title(), set_axis_range(), smart_legend(), plot_config::xlimits, and plot_config::ylimits.
Referenced by CharmTagPlots().
void DrawTagYieldPlot (TCanvas * pad, TTree * data, plot_config draw_config, TString xvar)
Definition at line 298 of file CharmTagPlots.C.
View newest version in sPHENIX GitHub at line 298 of file CharmTagPlots.C
References DifferentialTaggingYield(), charm_jet_strange_helicity::draw_config, make_title(), set_axis_range(), and smart_legend().
Referenced by CharmTagPlots().
std::vector<std::string> fileVector (const std::string & pattern)
Definition at line 165 of file CharmTagPlots.C.
View newest version in sPHENIX GitHub at line 165 of file CharmTagPlots.C
References eicpy.build::files.
Referenced by CharmTagPlots(), and main().
Int_t getHistUID ()
Definition at line 33 of file CharmTagPlots.C.
View newest version in sPHENIX GitHub at line 33 of file CharmTagPlots.C
References histUID.
Referenced by CharmTagPlots().
TLatex make_title ()
Definition at line 154 of file CharmTagPlots.C.
View newest version in sPHENIX GitHub at line 154 of file CharmTagPlots.C
Referenced by CharmTagPlots(), DrawTagEfficiencyPlot(), and DrawTagYieldPlot().
void set_axis_range (TH1F * hist, float min, float max, std::string which = "X")
Definition at line 116 of file CharmTagPlots.C.
View newest version in sPHENIX GitHub at line 116 of file CharmTagPlots.C
Referenced by CharmTagPlots(), DrawTagEfficiencyPlot(), and DrawTagYieldPlot().
TLegend* smart_legend (std::string where = "upper right", float legend_width = 0.30, float legend_height = 0.10)
Definition at line 78 of file CharmTagPlots.C.
View newest version in sPHENIX GitHub at line 78 of file CharmTagPlots.C
References smart_legend_x(), and smart_legend_y().
Referenced by CharmTagPlots(), DrawTagEfficiencyPlot(), and DrawTagYieldPlot().
float smart_legend_x (float x_trial, float x_width)
Definition at line 50 of file CharmTagPlots.C.
View newest version in sPHENIX GitHub at line 50 of file CharmTagPlots.C
Referenced by smart_legend().
float smart_legend_y (float y_trial, float y_height)
Definition at line 64 of file CharmTagPlots.C.
View newest version in sPHENIX GitHub at line 64 of file CharmTagPlots.C
Referenced by smart_legend().
Variable Documentation
Int_t histUID = 0
Definition at line 29 of file CharmTagPlots.C.
View newest version in sPHENIX GitHub at line 29 of file CharmTagPlots.C
Referenced by DifferentialTaggingEfficiency(), DifferentialTaggingYield(), and getHistUID().
float lumi = 100*u_fb
Definition at line 27 of file CharmTagPlots.C.
View newest version in sPHENIX GitHub at line 27 of file CharmTagPlots.C
Referenced by CharmTagPlots(), DifferentialTaggingYield(), and FluxMonitorGrid::FillOutHistograms().
float n_gen = -1
Definition at line 31 of file CharmTagPlots.C.
View newest version in sPHENIX GitHub at line 31 of file CharmTagPlots.C
Referenced by CharmTagPlots(), and CutEfficiency().
float u_fb = 1.0
Definition at line 22 of file CharmTagPlots.C.
View newest version in sPHENIX GitHub at line 22 of file CharmTagPlots.C
float u_mb = 1.0e12*u_fb
Definition at line 23 of file CharmTagPlots.C.
View newest version in sPHENIX GitHub at line 23 of file CharmTagPlots.C
float xsec_e10_p275_CC_DIS = 1.47637e-08*u_mb
Definition at line 25 of file CharmTagPlots.C.
View newest version in sPHENIX GitHub at line 25 of file CharmTagPlots.C
Referenced by CharmTagPlots(), and DifferentialTaggingYield().