EIC Software: SvtxTrackState_v1 Class Reference
SvtxTrackState_v1 Class Reference
#include <fun4all_coresoftware/blob/master/offline/packages/trackbase_historic/SvtxTrackState_v1.h>
Public Member Functions
SvtxTrackState_v1 (float pathlength=0.0)
virtual ~SvtxTrackState_v1 ()
void identify (std::ostream &os=std::cout) const
void Reset ()
Clear Event.
int isValid () const
isValid returns non zero if object contains vailid data
PHObject * CloneMe () const
Virtual copy constructor.
float get_pathlength () const
float get_x () const
void set_x (float x)
float get_y () const
void set_y (float y)
float get_z () const
void set_z (float z)
float get_pos (unsigned int i) const
float get_px () const
void set_px (float px)
float get_py () const
void set_py (float py)
float get_pz () const
void set_pz (float pz)
float get_mom (unsigned int i) const
float get_p () const
float get_pt () const
float get_eta () const
float get_phi () const
float get_error (unsigned int i, unsigned int j) const
void set_error (unsigned int i, unsigned int j, float value)
std::string get_name () const
void set_name (const std::string &name)
virtual float get_rphi_error () const
rphi error
virtual float get_phi_error () const
phi error
virtual float get_z_error () const
z error
Public Member Functions inherited from SvtxTrackState
virtual ~SvtxTrackState ()
Public Member Functions inherited from PHObject
PHObject ()
ctor
virtual ~PHObject ()
dtor
virtual PHObject * clone () const final
virtual PHObject * Clone (const char *newname="") const final
virtual void Copy (TObject &object) const final
virtual int isValid (const float) const
virtual int isValid (const double) const
virtual int isValid (const int) const
virtual int isValid (const unsigned int) const
virtual int isImplemented (const float f) const
virtual int isImplemented (const double f) const
virtual int isImplemented (const int i) const
virtual int isImplemented (const unsigned int i) const
virtual int Integrate () const
virtual int Integrate (PHObject *obj)
virtual void CopyFrom (const PHObject *obj)
Private Attributes
float _pathlength
float _pos [3]
float _mom [3]
float _covar [21]
std::string state_name
Additional Inherited Members
Protected Member Functions inherited from SvtxTrackState
SvtxTrackState (float pathlength=0.0)
ClassDef (SvtxTrackState, 1)
Detailed Description
Definition at line 12 of file SvtxTrackState_v1.h.
View newest version in sPHENIX GitHub at line 12 of file SvtxTrackState_v1.h
Constructor & Destructor Documentation
SvtxTrackState_v1::SvtxTrackState_v1 (float pathlength = 0.0)
Definition at line 24 of file SvtxTrackState_v1.cc.
View newest version in sPHENIX GitHub at line 24 of file SvtxTrackState_v1.cc
References _mom, _pos, set_error(), and state_name.
Referenced by CloneMe(), and Reset().
virtual SvtxTrackState_v1::~SvtxTrackState_v1 () inline virtual
Definition at line 16 of file SvtxTrackState_v1.h.
View newest version in sPHENIX GitHub at line 16 of file SvtxTrackState_v1.h
Member Function Documentation
PHObject* SvtxTrackState_v1::CloneMe () const inline virtual
Virtual copy constructor.
Reimplemented from SvtxTrackState.
Definition at line 22 of file SvtxTrackState_v1.h.
View newest version in sPHENIX GitHub at line 22 of file SvtxTrackState_v1.h
References SvtxTrackState_v1().
float SvtxTrackState_v1::get_error (unsigned int i, unsigned int j) const virtual
Reimplemented from SvtxTrackState.
Definition at line 52 of file SvtxTrackState_v1.cc.
View newest version in sPHENIX GitHub at line 52 of file SvtxTrackState_v1.cc
References _covar.
Referenced by get_rphi_error(), and get_z_error().
float SvtxTrackState_v1::get_eta () const inline virtual
Reimplemented from SvtxTrackState.
Definition at line 50 of file SvtxTrackState_v1.h.
View newest version in sPHENIX GitHub at line 50 of file SvtxTrackState_v1.h
References get_pt(), and get_pz().
float SvtxTrackState_v1::get_mom (unsigned int i) const inline virtual
Reimplemented from SvtxTrackState.
Definition at line 46 of file SvtxTrackState_v1.h.
View newest version in sPHENIX GitHub at line 46 of file SvtxTrackState_v1.h
References _mom.
std::string SvtxTrackState_v1::get_name (void) const inline virtual
Reimplemented from SvtxTrackState.
Definition at line 56 of file SvtxTrackState_v1.h.
View newest version in sPHENIX GitHub at line 56 of file SvtxTrackState_v1.h
References state_name.
float SvtxTrackState_v1::get_p () const inline virtual
Reimplemented from SvtxTrackState.
Definition at line 48 of file SvtxTrackState_v1.h.
View newest version in sPHENIX GitHub at line 48 of file SvtxTrackState_v1.h
References get_px(), get_py(), and get_pz().
float SvtxTrackState_v1::get_pathlength () const inline virtual
Reimplemented from SvtxTrackState.
Definition at line 24 of file SvtxTrackState_v1.h.
View newest version in sPHENIX GitHub at line 24 of file SvtxTrackState_v1.h
References _pathlength.
Referenced by identify().
float SvtxTrackState_v1::get_phi () const inline virtual
Reimplemented from SvtxTrackState.
Definition at line 51 of file SvtxTrackState_v1.h.
View newest version in sPHENIX GitHub at line 51 of file SvtxTrackState_v1.h
References get_px(), and get_py().
float SvtxTrackState_v1::get_phi_error () const virtual
phi error
Reimplemented from SvtxTrackState.
Definition at line 63 of file SvtxTrackState_v1.cc.
View newest version in sPHENIX GitHub at line 63 of file SvtxTrackState_v1.cc
References _pos, get_rphi_error(), r, and square().
float SvtxTrackState_v1::get_pos (unsigned int i) const inline virtual
Reimplemented from SvtxTrackState.
Definition at line 35 of file SvtxTrackState_v1.h.
View newest version in sPHENIX GitHub at line 35 of file SvtxTrackState_v1.h
References _pos.
float SvtxTrackState_v1::get_pt () const inline virtual
Reimplemented from SvtxTrackState.
Definition at line 49 of file SvtxTrackState_v1.h.
View newest version in sPHENIX GitHub at line 49 of file SvtxTrackState_v1.h
References get_px(), and get_py().
Referenced by get_eta().
float SvtxTrackState_v1::get_px () const inline virtual
Reimplemented from SvtxTrackState.
Definition at line 37 of file SvtxTrackState_v1.h.
View newest version in sPHENIX GitHub at line 37 of file SvtxTrackState_v1.h
References _mom.
Referenced by get_p(), get_phi(), get_pt(), and identify().
float SvtxTrackState_v1::get_py () const inline virtual
Reimplemented from SvtxTrackState.
Definition at line 40 of file SvtxTrackState_v1.h.
View newest version in sPHENIX GitHub at line 40 of file SvtxTrackState_v1.h
References _mom.
Referenced by get_p(), get_phi(), get_pt(), and identify().
float SvtxTrackState_v1::get_pz () const inline virtual
Reimplemented from SvtxTrackState.
Definition at line 43 of file SvtxTrackState_v1.h.
View newest version in sPHENIX GitHub at line 43 of file SvtxTrackState_v1.h
References _mom.
Referenced by get_eta(), get_p(), and identify().
float SvtxTrackState_v1::get_rphi_error () const virtual
rphi error
Reimplemented from SvtxTrackState.
Definition at line 70 of file SvtxTrackState_v1.cc.
View newest version in sPHENIX GitHub at line 70 of file SvtxTrackState_v1.cc
References _pos, cos(), get_error(), phi, and square().
Referenced by get_phi_error().
float SvtxTrackState_v1::get_x () const inline virtual
Reimplemented from SvtxTrackState.
Definition at line 26 of file SvtxTrackState_v1.h.
View newest version in sPHENIX GitHub at line 26 of file SvtxTrackState_v1.h
References _pos.
Referenced by identify().
float SvtxTrackState_v1::get_y () const inline virtual
Reimplemented from SvtxTrackState.
Definition at line 29 of file SvtxTrackState_v1.h.
View newest version in sPHENIX GitHub at line 29 of file SvtxTrackState_v1.h
References _pos.
Referenced by identify().
float SvtxTrackState_v1::get_z () const inline virtual
Reimplemented from SvtxTrackState.
Definition at line 32 of file SvtxTrackState_v1.h.
View newest version in sPHENIX GitHub at line 32 of file SvtxTrackState_v1.h
References _pos.
Referenced by identify().
float SvtxTrackState_v1::get_z_error () const virtual
z error
Reimplemented from SvtxTrackState.
Definition at line 81 of file SvtxTrackState_v1.cc.
View newest version in sPHENIX GitHub at line 81 of file SvtxTrackState_v1.cc
References get_error().
void SvtxTrackState_v1::identify (std::ostream & os = std::cout) const virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from SvtxTrackState.
Definition at line 39 of file SvtxTrackState_v1.cc.
View newest version in sPHENIX GitHub at line 39 of file SvtxTrackState_v1.cc
References get_pathlength(), get_px(), get_py(), get_pz(), get_x(), get_y(), and get_z().
int SvtxTrackState_v1::isValid () const inline virtual
isValid returns non zero if object contains vailid data
Reimplemented from SvtxTrackState.
Definition at line 21 of file SvtxTrackState_v1.h.
View newest version in sPHENIX GitHub at line 21 of file SvtxTrackState_v1.h
void SvtxTrackState_v1::Reset () inline virtual
Clear Event.
Reimplemented from SvtxTrackState.
Definition at line 20 of file SvtxTrackState_v1.h.
View newest version in sPHENIX GitHub at line 20 of file SvtxTrackState_v1.h
References SvtxTrackState_v1().
void SvtxTrackState_v1::set_error (unsigned int i, unsigned int j, float value) virtual
Reimplemented from SvtxTrackState.
Definition at line 57 of file SvtxTrackState_v1.cc.
View newest version in sPHENIX GitHub at line 57 of file SvtxTrackState_v1.cc
References _covar, and value.
Referenced by ActsTransformations::fillSvtxTrackStates(), and SvtxTrackState_v1().
void SvtxTrackState_v1::set_name (const std::string & name) inline virtual
Reimplemented from SvtxTrackState.
Definition at line 57 of file SvtxTrackState_v1.h.
View newest version in sPHENIX GitHub at line 57 of file SvtxTrackState_v1.h
References name, and state_name.
void SvtxTrackState_v1::set_px (float px) inline virtual
Reimplemented from SvtxTrackState.
Definition at line 38 of file SvtxTrackState_v1.h.
View newest version in sPHENIX GitHub at line 38 of file SvtxTrackState_v1.h
References _mom.
Referenced by ActsTransformations::fillSvtxTrackStates().
void SvtxTrackState_v1::set_py (float py) inline virtual
Reimplemented from SvtxTrackState.
Definition at line 41 of file SvtxTrackState_v1.h.
View newest version in sPHENIX GitHub at line 41 of file SvtxTrackState_v1.h
References _mom.
Referenced by ActsTransformations::fillSvtxTrackStates().
void SvtxTrackState_v1::set_pz (float pz) inline virtual
Reimplemented from SvtxTrackState.
Definition at line 44 of file SvtxTrackState_v1.h.
View newest version in sPHENIX GitHub at line 44 of file SvtxTrackState_v1.h
References _mom.
Referenced by ActsTransformations::fillSvtxTrackStates().
void SvtxTrackState_v1::set_x (float x) inline virtual
Reimplemented from SvtxTrackState.
Definition at line 27 of file SvtxTrackState_v1.h.
View newest version in sPHENIX GitHub at line 27 of file SvtxTrackState_v1.h
References _pos, and x.
Referenced by PHActsToSvtxTracks::createSvtxTrack(), ActsTransformations::fillSvtxTrackStates(), PHActsTrkFitter::updateSvtxTrack(), and PHActsTrkProp::updateSvtxTrack().
void SvtxTrackState_v1::set_y (float y) inline virtual
Reimplemented from SvtxTrackState.
Definition at line 30 of file SvtxTrackState_v1.h.
View newest version in sPHENIX GitHub at line 30 of file SvtxTrackState_v1.h
References _pos, and analysis::y.
Referenced by PHActsToSvtxTracks::createSvtxTrack(), ActsTransformations::fillSvtxTrackStates(), PHActsTrkFitter::updateSvtxTrack(), and PHActsTrkProp::updateSvtxTrack().
void SvtxTrackState_v1::set_z (float z) inline virtual
Reimplemented from SvtxTrackState.
Definition at line 33 of file SvtxTrackState_v1.h.
View newest version in sPHENIX GitHub at line 33 of file SvtxTrackState_v1.h
References _pos, and z.
Referenced by PHActsToSvtxTracks::createSvtxTrack(), ActsTransformations::fillSvtxTrackStates(), PHActsTrkFitter::updateSvtxTrack(), and PHActsTrkProp::updateSvtxTrack().
Member Data Documentation
float SvtxTrackState_v1::_covar[21] private
Definition at line 69 of file SvtxTrackState_v1.h.
View newest version in sPHENIX GitHub at line 69 of file SvtxTrackState_v1.h
Referenced by get_error(), and set_error().
float SvtxTrackState_v1::_mom[3] private
Definition at line 68 of file SvtxTrackState_v1.h.
View newest version in sPHENIX GitHub at line 68 of file SvtxTrackState_v1.h
Referenced by get_mom(), get_px(), get_py(), get_pz(), set_px(), set_py(), set_pz(), and SvtxTrackState_v1().
float SvtxTrackState_v1::_pathlength private
Definition at line 66 of file SvtxTrackState_v1.h.
View newest version in sPHENIX GitHub at line 66 of file SvtxTrackState_v1.h
Referenced by get_pathlength().
float SvtxTrackState_v1::_pos[3] private
Definition at line 67 of file SvtxTrackState_v1.h.
View newest version in sPHENIX GitHub at line 67 of file SvtxTrackState_v1.h
Referenced by get_phi_error(), get_pos(), get_rphi_error(), get_x(), get_y(), get_z(), set_x(), set_y(), set_z(), and SvtxTrackState_v1().
std::string SvtxTrackState_v1::state_name private
Definition at line 71 of file SvtxTrackState_v1.h.
View newest version in sPHENIX GitHub at line 71 of file SvtxTrackState_v1.h
Referenced by get_name(), set_name(), and SvtxTrackState_v1().
The documentation for this class was generated from the following files:
fun4all_coresoftware/blob/master/offline/packages/trackbase_historic/SvtxTrackState_v1.h
fun4all_coresoftware/blob/master/offline/packages/trackbase_historic/SvtxTrackState_v1.cc