EIC Software: PEPSI/blob/master/pepsi_radgen_extras.f File Reference
pepsi_radgen_extras.f File Reference
Functions/Subroutines
subroutine mkf2 (DQ2, DX, A, Z, DF2, DF1)
subroutine mkr (DQ2, DX, DR)
subroutine r1990 (DQ2, DX, DR, DELTAR)
subroutine r1998 (DQ2, DX, DR, DELTAR)
DOUBLE PRECISION function dr1998 (DX, DQ2)
subroutine mkasym (dQ2, dX, A, Z, dA1, dA2)
subroutine fdilut (dQ2, dx, A, DF)
double precision function f2allm (x, q2)
Function/Subroutine Documentation
DOUBLE PRECISION function dr1998 (double precision DX, double precision DQ2)
Definition at line 234 of file pepsi_radgen_extras.f.
View newest version in sPHENIX GitHub at line 234 of file pepsi_radgen_extras.f
References dx, in, r1998(), genfit::GFRavePropagator::to(), and Acts::Measurement< source_link_t, parameter_indices_t, params >::uncertainty().
Referenced by r1998().
double precision function f2allm (x, q2)
Definition at line 352 of file pepsi_radgen_extras.f.
View newest version in sPHENIX GitHub at line 352 of file pepsi_radgen_extras.f
References b21, c, s, Acts::InternalSpacePoint< SpacePoint >::sp(), x, and z.
Referenced by mkf2().
subroutine fdilut (double precision dQ2, double precision dx, integer A, double precision DF)
Definition at line 309 of file pepsi_radgen_extras.f.
View newest version in sPHENIX GitHub at line 309 of file pepsi_radgen_extras.f
References c, d, dx, dz, Acts::KalmanFitter< propagator_t, updater_t, smoother_t, outlier_finder_t, calibrator_t >::fit(), t1, and genfit::GFRavePropagator::to().
Referenced by pepsimainerhic(), and strf().
subroutine mkasym (double precision dQ2, double precision dX, integer A, integer Z, double precision dA1, double precision dA2)
Definition at line 250 of file pepsi_radgen_extras.f.
View newest version in sPHENIX GitHub at line 250 of file pepsi_radgen_extras.f
References c, dx, mkf2(), parton(), and z.
Referenced by pepsimainerhic(), and strf().
subroutine mkf2 (double precision DQ2, double precision DX, integer A, integer Z, double precision DF2, double precision DF1)
Definition at line 6 of file pepsi_radgen_extras.f.
View newest version in sPHENIX GitHub at line 6 of file pepsi_radgen_extras.f
References c, d, dx, f2(), f2allm(), Acts::KalmanFitter< propagator_t, updater_t, smoother_t, outlier_finder_t, calibrator_t >::fit(), for(), mkr(), n, p, parton(), ratio, genfit::GFRavePropagator::to(), and z.
Referenced by mkasym(), pepsimainerhic(), and strf().
subroutine mkr (double precision DQ2, double precision DX, double precision DR)
Definition at line 97 of file pepsi_radgen_extras.f.
View newest version in sPHENIX GitHub at line 97 of file pepsi_radgen_extras.f
References c, dx, r1990(), and r1998().
Referenced by mkf2(), pepsimainerhic(), and strf().
subroutine r1990 (double precision DQ2, double precision DX, double precision DR, double precision DELTAR)
Definition at line 122 of file pepsi_radgen_extras.f.
View newest version in sPHENIX GitHub at line 122 of file pepsi_radgen_extras.f
References c, d, data, Acts::FiniteStateMachine< Derived, States >::is(), Acts::Logger::log(), of, print(), and Acts::ConeBounds::r().
Referenced by mkr().
subroutine r1998 (double precision DQ2, double precision DX, double precision DR, double precision DELTAR)
Definition at line 177 of file pepsi_radgen_extras.f.
View newest version in sPHENIX GitHub at line 177 of file pepsi_radgen_extras.f
References c, dr1998(), dx, Acts::KalmanFitter< propagator_t, updater_t, smoother_t, outlier_finder_t, calibrator_t >::fit(), for(), Acts::BinnedSPGroupIterator< external_spacepoint_t >::if(), Acts::FiniteStateMachine< Derived, States >::is(), it, Acts::IVisualization3D::line(), Acts::Logger::log(), Acts::ConeBounds::r(), Acts::Extent::range(), genfit::GFRavePropagator::to(), Acts::Measurement< source_link_t, parameter_indices_t, params >::uncertainty(), and x.
Referenced by dr1998(), and mkr().