EIC Software: Acts::PlyVisualization< T > Class Template Reference
Acts::PlyVisualization< T > Class Template Reference
Helper to write out PlyVisualization visualization format.
#include <fun4all_acts/blob/master/Core/include/Acts/Visualization/PlyVisualization.hpp>
Public Types
using ValueType = T
Stored value type, should be double or float.
using VertexType = ActsVector< ValueType, 3 >
Type of a vertex based on the value type.
Public Types inherited from Acts::IVisualization
using ColorType = std::array< int, 3 >
using FaceType = std::vector< size_t >
The face type.
Public Member Functions
void vertex (const Vector3D &vtx, IVisualization::ColorType color={120, 120, 120}) final
void face (const std::vector< Vector3D > &vtxs, IVisualization::ColorType color={120, 120, 120}) final
void faces (const std::vector< Vector3D > &vtxs, const std::vector< FaceType > &, ColorType color={120, 120, 120}) final
void line (const Vector3D &a, const Vector3D &b, IVisualization::ColorType color={120, 120, 120}) final
void write (const std::string &path) const final
void write (std::ostream &os) const final
void clear () final
Public Member Functions inherited from Acts::IVisualization
void vertex (const Vector3F &vtx, ColorType color={120, 120, 120})
void face (const std::vector< Vector3F > &vtxs, ColorType color={120, 120, 120})
void line (const Vector3F &a, const Vector3F &b, ColorType color={120, 120, 120})
(const Vector3F&, const Vector3F&,
Private Attributes
std::vector< std::pair
< VertexType,
IVisualization::ColorType > > m_vertices
std::vector< FaceType > m_faces
std::vector< std::pair
< std::pair< size_t, size_t >
, IVisualization::ColorType > > m_edges
Additional Inherited Members
Protected Member Functions inherited from Acts::IVisualization
bool hasExtension (const std::string &path) const
void replaceExtension (std::string &path, const std::string &suffix) const
Detailed Description
template<typename T = double>
class Acts::PlyVisualization< T >
Helper to write out PlyVisualization visualization format.
Definition at line 25 of file PlyVisualization.hpp.
View newest version in sPHENIX GitHub at line 25 of file PlyVisualization.hpp
Member Typedef Documentation
template<typename T = double> using Acts::PlyVisualization< T >::ValueType = T
Stored value type, should be double or float.
Definition at line 31 of file PlyVisualization.hpp.
View newest version in sPHENIX GitHub at line 31 of file PlyVisualization.hpp
template<typename T = double> using Acts::PlyVisualization< T >::VertexType = ActsVector<ValueType, 3>
Type of a vertex based on the value type.
Definition at line 34 of file PlyVisualization.hpp.
View newest version in sPHENIX GitHub at line 34 of file PlyVisualization.hpp
Member Function Documentation
template<typename T > void Acts::PlyVisualization< T >::clear (void) final virtual
Remove all contents of this helper
Implements Acts::IVisualization.
Definition at line 100 of file PlyVisualization.ipp.
View newest version in sPHENIX GitHub at line 100 of file PlyVisualization.ipp
References Acts::PlyVisualization< T >::clear().
Referenced by Acts::Test::BOOST_AUTO_TEST_CASE(), and Acts::PlyVisualization< T >::clear().
template<typename T > void Acts::PlyVisualization< T >::face (const std::vector< Vector3D > & vtxs, IVisualization::ColorType color = {120, 120, 120}) final virtual
Draw a line from a vertex to another
Parameters
a The start vertex
b The end vertex
color The color of the line
Implements Acts::IVisualization.
Definition at line 16 of file PlyVisualization.ipp.
View newest version in sPHENIX GitHub at line 16 of file PlyVisualization.ipp
References vtx().
template<typename T > void Acts::PlyVisualization< T >::faces (const std::vector< Vector3D > & vtxs, const std::vector< FaceType > & , ColorType color = {120, 120, 120}) final virtual
Draw a faces that connects a list of vertices - expert only
Note
Depending on the helper implementation, out of plane vertices might be handled differently.
Parameters
vtxs The vertices that make up the faceS
faces The face presectiotions (i.e. connecting vertices)
color The color of the face
Implements Acts::IVisualization.
Definition at line 28 of file PlyVisualization.ipp.
View newest version in sPHENIX GitHub at line 28 of file PlyVisualization.ipp
template<typename T > void Acts::PlyVisualization< T >::line (const Vector3D & a, const Vector3D & b, IVisualization::ColorType color = {120, 120, 120}) final virtual
Draw a face that connects a list of vertices.
Note
Depending on the helper implementation, out of plane vertices might be handled differently.
Parameters
vtxs The vertices that make up the face
color The color of the face
Implements Acts::IVisualization.
Definition at line 34 of file PlyVisualization.ipp.
View newest version in sPHENIX GitHub at line 34 of file PlyVisualization.ipp
template<typename T > void Acts::PlyVisualization< T >::vertex (const Vector3D & vtx, IVisualization::ColorType color = {120, 120, 120}) final virtual
Draw a vertex at a given location and a color.
Parameters
vtx The vertex position
color The color
Implements Acts::IVisualization.
Definition at line 10 of file PlyVisualization.ipp.
View newest version in sPHENIX GitHub at line 10 of file PlyVisualization.ipp
template<typename T > void Acts::PlyVisualization< T >::write (const std::string & path) const final virtual
Write the content of the helper to an outstream.
Parameters
os The output stream for file
Implements Acts::IVisualization.
Definition at line 45 of file PlyVisualization.hpp.
View newest version in sPHENIX GitHub at line 45 of file PlyVisualization.hpp
template<typename T > void Acts::PlyVisualization< T >::write (std::ostream & os) const final virtual
Write the content of the helper to an outstream.
Parameters
os The output stream for file
Implements Acts::IVisualization.
Definition at line 57 of file PlyVisualization.hpp.
View newest version in sPHENIX GitHub at line 57 of file PlyVisualization.hpp
Member Data Documentation
template<typename T = double> std::vector<std::pair<std::pair<size_t, size_t>, IVisualization::ColorType> > Acts::PlyVisualization< T >::m_edges private
Definition at line 65 of file PlyVisualization.hpp.
View newest version in sPHENIX GitHub at line 65 of file PlyVisualization.hpp
template<typename T = double> std::vector<FaceType> Acts::PlyVisualization< T >::m_faces private
Definition at line 63 of file PlyVisualization.hpp.
View newest version in sPHENIX GitHub at line 63 of file PlyVisualization.hpp
template<typename T = double> std::vector<std::pair<VertexType, IVisualization::ColorType> > Acts::PlyVisualization< T >::m_vertices private
Definition at line 62 of file PlyVisualization.hpp.
View newest version in sPHENIX GitHub at line 62 of file PlyVisualization.hpp
The documentation for this class was generated from the following files:
fun4all_acts/blob/master/Core/include/Acts/Visualization/PlyVisualization.hpp
fun4all_acts/blob/master/Core/include/Acts/Visualization/detail/PlyVisualization.ipp