EIC Software: FairDbRowStream Class Reference
FairDbRowStream Class Reference
#include <EicRoot/blob/master/dbase/dbInterface/FairDbRowStream.h>
Public Member Functions
FairDbRowStream (const FairDbTableMetaData *metaData)
virtual ~FairDbRowStream ()
virtual const FairDbFieldType & ColFieldType (UInt_t col) const
virtual string ColName (UInt_t col) const
virtual const FairDbFieldType & CurColFieldType () const
virtual string CurColName () const
virtual UInt_t CurColNum () const
Bool_t HasRowCounter () const
virtual UInt_t NumCols () const
virtual string TableName () const
virtual string TableNameTc () const
virtual const FairDbTableMetaData * MetaData () const
virtual void DecrementCurCol ()
virtual void IncrementCurCol ()
Protected Member Functions
virtual void ClearCurCol ()
Private Member Functions
FairDbRowStream (const FairDbRowStream &)
FairDbRowStream operator= (const FairDbRowStream &)
Private Attributes
UShort_t fCurCol
Bool_t fHasRowCounter
const FairDbTableMetaData * fMetaData
Detailed Description
Definition at line 10 of file FairDbRowStream.h.
View newest version in sPHENIX GitHub at line 10 of file FairDbRowStream.h
Constructor & Destructor Documentation
FairDbRowStream::FairDbRowStream (const FairDbTableMetaData * metaData)
FairDbRowStream::~FairDbRowStream () virtual
Definition at line 20 of file FairDbRowStream.cxx.
View newest version in sPHENIX GitHub at line 20 of file FairDbRowStream.cxx
FairDbRowStream::FairDbRowStream (const FairDbRowStream &) private
Member Function Documentation
virtual void FairDbRowStream::ClearCurCol () inline protected virtual
Definition at line 43 of file FairDbRowStream.h.
View newest version in sPHENIX GitHub at line 43 of file FairDbRowStream.h
References fCurCol.
Referenced by FairDbOutRowStream::Clear(), and FairDbResultSet::FetchRow().
const FairDbFieldType & FairDbRowStream::ColFieldType (UInt_t col) const virtual
Definition at line 26 of file FairDbRowStream.cxx.
View newest version in sPHENIX GitHub at line 26 of file FairDbRowStream.cxx
References FairDbTableMetaData::ColFieldType(), and fMetaData.
Referenced by FairDbResultSet::GetStringFromTSQL().
string FairDbRowStream::ColName (UInt_t col) const virtual
Definition at line 32 of file FairDbRowStream.cxx.
View newest version in sPHENIX GitHub at line 32 of file FairDbRowStream.cxx
References FairDbTableMetaData::ColName(), and fMetaData.
const FairDbFieldType & FairDbRowStream::CurColFieldType () const virtual
Definition at line 37 of file FairDbRowStream.cxx.
View newest version in sPHENIX GitHub at line 37 of file FairDbRowStream.cxx
References FairDbTableMetaData::ColFieldType(), fCurCol, and fMetaData.
Referenced by FairDbConfigSet::Fill(), FairDbResultSet::LoadCurValue(), FairDbProxy::ReplaceSeqNoOracle(), FairDbOutRowStream::Store(), and FairDbOutRowStream::StoreDefaultIfInvalid().
string FairDbRowStream::CurColName () const virtual
Definition at line 44 of file FairDbRowStream.cxx.
View newest version in sPHENIX GitHub at line 44 of file FairDbRowStream.cxx
References FairDbTableMetaData::ColName(), fCurCol, and fMetaData.
Referenced by ClassImp(), FairDbConfigSet::Fill(), and FairDbOutRowStream::StoreDefaultIfInvalid().
virtual UInt_t FairDbRowStream::CurColNum () const inline virtual
Definition at line 25 of file FairDbRowStream.h.
View newest version in sPHENIX GitHub at line 25 of file FairDbRowStream.h
References fCurCol.
Referenced by FairDbResultSet::AsString(), FairDbResultSet::CurColExists(), FairDbResultSet::CurColString(), FairDbOutRowStream::IsComplete(), FairDbResultSet::LoadCurValue(), FairDbOutRowStream::Store(), and FairDbOutRowStream::StoreDefaultIfInvalid().
virtual void FairDbRowStream::DecrementCurCol () inline virtual
Definition at line 34 of file FairDbRowStream.h.
View newest version in sPHENIX GitHub at line 34 of file FairDbRowStream.h
References fCurCol.
Referenced by ClassImp().
Bool_t FairDbRowStream::HasRowCounter () const inline
Definition at line 26 of file FairDbRowStream.h.
View newest version in sPHENIX GitHub at line 26 of file FairDbRowStream.h
References fHasRowCounter.
Referenced by FairDbSqlValPacket::AddRow(), ClassImp(), and FairDbConfigSet::Fill().
virtual void FairDbRowStream::IncrementCurCol () inline virtual
Definition at line 39 of file FairDbRowStream.h.
View newest version in sPHENIX GitHub at line 39 of file FairDbRowStream.h
References fCurCol.
Referenced by FairDbResultSet::AsString(), ClassImp(), FairDbConfigSet::Fill(), FairDbProxy::ReplaceSeqNoOracle(), and FairDbOutRowStream::Store().
virtual const FairDbTableMetaData* FairDbRowStream::MetaData () const inline virtual
Definition at line 31 of file FairDbRowStream.h.
View newest version in sPHENIX GitHub at line 31 of file FairDbRowStream.h
References fMetaData.
Referenced by FairDbResultSet::AsString(), and FairDbResultSet::RowAsCsv().
UInt_t FairDbRowStream::NumCols () const virtual
Definition at line 51 of file FairDbRowStream.cxx.
View newest version in sPHENIX GitHub at line 51 of file FairDbRowStream.cxx
References fMetaData, and FairDbTableMetaData::NumCols().
Referenced by FairDbResultSet::CurColExists(), FairDbConfigSet::Fill(), FairDbOutRowStream::IsComplete(), FairDbProxy::ReplaceSeqNoOracle(), and FairDbResultSet::RowAsCsv().
FairDbRowStream FairDbRowStream::operator= (const FairDbRowStream &) private
string FairDbRowStream::TableName () const virtual
Definition at line 59 of file FairDbRowStream.cxx.
View newest version in sPHENIX GitHub at line 59 of file FairDbRowStream.cxx
References fMetaData, FairDbTableMetaData::TableName(), and FairUtilString::ToUpper().
string FairDbRowStream::TableNameTc () const virtual
Definition at line 65 of file FairDbRowStream.cxx.
View newest version in sPHENIX GitHub at line 65 of file FairDbRowStream.cxx
References fMetaData, and FairDbTableMetaData::TableName().
Referenced by FairDbResultSet::AsString(), FairDbResultSet::CurColExists(), FairDbResult::FairDbResult(), and FairDbOutRowStream::StoreDefaultIfInvalid().
Member Data Documentation
UShort_t FairDbRowStream::fCurCol private
Definition at line 47 of file FairDbRowStream.h.
View newest version in sPHENIX GitHub at line 47 of file FairDbRowStream.h
Referenced by ClearCurCol(), CurColFieldType(), CurColName(), CurColNum(), DecrementCurCol(), and IncrementCurCol().
Bool_t FairDbRowStream::fHasRowCounter private
Definition at line 48 of file FairDbRowStream.h.
View newest version in sPHENIX GitHub at line 48 of file FairDbRowStream.h
Referenced by HasRowCounter().
const FairDbTableMetaData* FairDbRowStream::fMetaData private
Definition at line 49 of file FairDbRowStream.h.
View newest version in sPHENIX GitHub at line 49 of file FairDbRowStream.h
Referenced by ColFieldType(), ColName(), CurColFieldType(), CurColName(), MetaData(), NumCols(), TableName(), and TableNameTc().
The documentation for this class was generated from the following files:
EicRoot/blob/master/dbase/dbInterface/FairDbRowStream.h
EicRoot/blob/master/dbase/dbInterface/FairDbRowStream.cxx