EIC Software: FW::TrackSummaryPlotTool Class Reference
FW::TrackSummaryPlotTool Class Reference
#include <fun4all_acts/blob/master/Examples/Framework/include/ACTFW/Validation/TrackSummaryPlotTool.hpp>
Classes
struct Config
The nested configuration struct.
struct TrackSummaryPlotCache
Nested Cache struct.
Public Member Functions
TrackSummaryPlotTool (const Config &cfg, Acts::Logging::Level lvl)
void book (TrackSummaryPlotCache &trackSummaryPlotCache) const
book the track info plots
void fill (TrackSummaryPlotCache &trackSummaryPlotCache, const ActsFatras::Particle &truthParticle, size_t nStates, size_t nMeasurments, size_t Outliers, size_t nHoles) const
fill track info
void write (const TrackSummaryPlotCache &trackSummaryPlotCache) const
write the track info plots to file
void clear (TrackSummaryPlotCache &trackSummaryPlotCache) const
delete the track info plots
Private Member Functions
const Acts::Logger & logger () const
The logger.
Private Attributes
Config m_cfg
The Config class.
std::unique_ptr< const
Acts::Logger > m_logger
The logging instance.
Detailed Description
Definition at line 22 of file TrackSummaryPlotTool.hpp.
View newest version in sPHENIX GitHub at line 22 of file TrackSummaryPlotTool.hpp
Constructor & Destructor Documentation
FW::TrackSummaryPlotTool::TrackSummaryPlotTool (const Config & cfg, Acts::Logging::Level lvl)
Constructor
Parameters
cfg Configuration struct
lvl Message level declaration
Definition at line 13 of file TrackSummaryPlotTool.cpp.
View newest version in sPHENIX GitHub at line 13 of file TrackSummaryPlotTool.cpp
Member Function Documentation
void FW::TrackSummaryPlotTool::book (TrackSummaryPlotTool::TrackSummaryPlotCache & trackSummaryPlotCache) const
book the track info plots
Parameters
trackSummaryPlotCache the cache for track info plots
Definition at line 18 of file TrackSummaryPlotTool.cpp.
View newest version in sPHENIX GitHub at line 18 of file TrackSummaryPlotTool.cpp
References ACTS_DEBUG, FW::PlotHelpers::bookProf(), FW::TrackSummaryPlotTool::TrackSummaryPlotCache::nHoles_vs_eta, FW::TrackSummaryPlotTool::TrackSummaryPlotCache::nHoles_vs_pt, FW::TrackSummaryPlotTool::TrackSummaryPlotCache::nMeasurements_vs_eta, FW::TrackSummaryPlotTool::TrackSummaryPlotCache::nMeasurements_vs_pt, FW::TrackSummaryPlotTool::TrackSummaryPlotCache::nOutliers_vs_eta, FW::TrackSummaryPlotTool::TrackSummaryPlotCache::nOutliers_vs_pt, FW::TrackSummaryPlotTool::TrackSummaryPlotCache::nStates_vs_eta, and FW::TrackSummaryPlotTool::TrackSummaryPlotCache::nStates_vs_pt.
Referenced by FW::TrackFitterPerformanceWriter::TrackFitterPerformanceWriter().
void FW::TrackSummaryPlotTool::clear (TrackSummaryPlotCache & trackSummaryPlotCache) const
delete the track info plots
Parameters
trackSummaryPlotCache cache object for track info plots
Definition at line 50 of file TrackSummaryPlotTool.cpp.
View newest version in sPHENIX GitHub at line 50 of file TrackSummaryPlotTool.cpp
References FW::TrackSummaryPlotTool::TrackSummaryPlotCache::nHoles_vs_eta, FW::TrackSummaryPlotTool::TrackSummaryPlotCache::nHoles_vs_pt, FW::TrackSummaryPlotTool::TrackSummaryPlotCache::nMeasurements_vs_eta, FW::TrackSummaryPlotTool::TrackSummaryPlotCache::nMeasurements_vs_pt, FW::TrackSummaryPlotTool::TrackSummaryPlotCache::nOutliers_vs_eta, FW::TrackSummaryPlotTool::TrackSummaryPlotCache::nOutliers_vs_pt, FW::TrackSummaryPlotTool::TrackSummaryPlotCache::nStates_vs_eta, and FW::TrackSummaryPlotTool::TrackSummaryPlotCache::nStates_vs_pt.
void FW::TrackSummaryPlotTool::fill (TrackSummaryPlotTool::TrackSummaryPlotCache & trackSummaryPlotCache, const ActsFatras::Particle & truthParticle, size_t nStates, size_t nMeasurments, size_t Outliers, size_t nHoles) const
fill track info
Parameters
trackSummaryPlotCache cache object for track info plots
truthParticle truth particle for this track
nStates number of track states
nMeasurements number of measurements
nOutliers number of outliers
nHoles number of holes
Definition at line 76 of file TrackSummaryPlotTool.cpp.
View newest version in sPHENIX GitHub at line 76 of file TrackSummaryPlotTool.cpp
References Acts::VectorHelpers::eta(), FW::PlotHelpers::fillProf(), FW::TrackSummaryPlotTool::TrackSummaryPlotCache::nHoles_vs_eta, FW::TrackSummaryPlotTool::TrackSummaryPlotCache::nHoles_vs_pt, FW::TrackSummaryPlotTool::TrackSummaryPlotCache::nMeasurements_vs_eta, FW::TrackSummaryPlotTool::TrackSummaryPlotCache::nMeasurements_vs_pt, FW::TrackSummaryPlotTool::TrackSummaryPlotCache::nOutliers_vs_eta, FW::TrackSummaryPlotTool::TrackSummaryPlotCache::nOutliers_vs_pt, FW::TrackSummaryPlotTool::TrackSummaryPlotCache::nStates_vs_eta, FW::TrackSummaryPlotTool::TrackSummaryPlotCache::nStates_vs_pt, Acts::VectorHelpers::perp(), ActsFatras::Particle::transverseMomentum(), and ActsFatras::Particle::unitDirection().
const Acts::Logger& FW::TrackSummaryPlotTool::logger () const inline private
The logger.
Definition at line 81 of file TrackSummaryPlotTool.hpp.
View newest version in sPHENIX GitHub at line 81 of file TrackSummaryPlotTool.hpp
References m_logger.
void FW::TrackSummaryPlotTool::write (const TrackSummaryPlotCache & trackSummaryPlotCache) const
write the track info plots to file
Parameters
trackSummaryPlotCache cache object for track info plots
Definition at line 62 of file TrackSummaryPlotTool.cpp.
View newest version in sPHENIX GitHub at line 62 of file TrackSummaryPlotTool.cpp
References ACTS_DEBUG, FW::TrackSummaryPlotTool::TrackSummaryPlotCache::nHoles_vs_eta, FW::TrackSummaryPlotTool::TrackSummaryPlotCache::nHoles_vs_pt, FW::TrackSummaryPlotTool::TrackSummaryPlotCache::nMeasurements_vs_eta, FW::TrackSummaryPlotTool::TrackSummaryPlotCache::nMeasurements_vs_pt, FW::TrackSummaryPlotTool::TrackSummaryPlotCache::nOutliers_vs_eta, FW::TrackSummaryPlotTool::TrackSummaryPlotCache::nOutliers_vs_pt, FW::TrackSummaryPlotTool::TrackSummaryPlotCache::nStates_vs_eta, and FW::TrackSummaryPlotTool::TrackSummaryPlotCache::nStates_vs_pt.
Member Data Documentation
Config FW::TrackSummaryPlotTool::m_cfg private
The Config class.
Definition at line 77 of file TrackSummaryPlotTool.hpp.
View newest version in sPHENIX GitHub at line 77 of file TrackSummaryPlotTool.hpp
std::unique_ptr<const Acts::Logger> FW::TrackSummaryPlotTool::m_logger private
The logging instance.
Definition at line 78 of file TrackSummaryPlotTool.hpp.
View newest version in sPHENIX GitHub at line 78 of file TrackSummaryPlotTool.hpp
Referenced by logger().
The documentation for this class was generated from the following files:
fun4all_acts/blob/master/Examples/Framework/include/ACTFW/Validation/TrackSummaryPlotTool.hpp
fun4all_acts/blob/master/Examples/Framework/src/Validation/TrackSummaryPlotTool.cpp