EIC Software: fun4all_eicmacros/blob/master/common/G4_EndCap_Hadron_JLeic.C File Reference
G4_EndCap_Hadron_JLeic.C File Reference
#include <GlobalVariables.C>
#include <g4detectors/PHG4CylinderSubsystem.h>
#include <g4main/PHG4Reco.h>
Namespaces
namespace Enable
namespace G4ENDCAPHADRON
Macros
#define MACRO_G4ENDCAPHADRON
Functions
void EndCap_HadronInit ()
void EndCap_Hadron (PHG4Reco *g4Reco)
Variables
bool Enable::ENDCAP_HADRON = false
double G4ENDCAPHADRON::outer_radius = 243.
double G4ENDCAPHADRON::length = 250.
double G4ENDCAPHADRON::place_z = 400. / 2. + length / 2. + 170.
Macro Definition Documentation
#define MACRO_G4ENDCAPHADRON
Definition at line 2 of file G4_EndCap_Hadron_JLeic.C.
View newest version in sPHENIX GitHub at line 2 of file G4_EndCap_Hadron_JLeic.C
Function Documentation
void EndCap_Hadron (PHG4Reco * g4Reco)
Definition at line 29 of file G4_EndCap_Hadron_JLeic.C.
View newest version in sPHENIX GitHub at line 29 of file G4_EndCap_Hadron_JLeic.C
References gap(), G4ENDCAPHADRON::length, G4ENDCAPHADRON::outer_radius, G4ENDCAPHADRON::place_z, PHG4Reco::registerSubsystem(), PHG4CylinderSubsystem::set_color(), PHG4DetectorSubsystem::set_double_param(), PHG4DetectorSubsystem::set_string_param(), PHG4DetectorSubsystem::SetActive(), PHG4Subsystem::SetMotherSubsystem(), G4CTD::size_z, PHG4DetectorSubsystem::SuperDetector(), and G4DIRC::z_start.
Referenced by G4Setup().
void EndCap_HadronInit ()
Definition at line 23 of file G4_EndCap_Hadron_JLeic.C.
View newest version in sPHENIX GitHub at line 23 of file G4_EndCap_Hadron_JLeic.C
References G4ENDCAPHADRON::length, max, BlackHoleGeometry::max_radius, BlackHoleGeometry::max_z, G4ENDCAPHADRON::outer_radius, and G4ENDCAPHADRON::place_z.
Referenced by G4Init().