EIC Software: EicRoot/blob/master/eic/cad/elmer/plugins/egconvert.h File Reference
egconvert.h File Reference
Functions
int LoadAbaqusInput (struct FemType *data, struct BoundaryType *bound, char *prefix, int info)
int LoadFidapInput (struct FemType *data, struct BoundaryType *bound, char *prefix, int info)
int LoadAnsysInput (struct FemType *data, struct BoundaryType *bound, char *prefix, int info)
int LoadNastranInput (struct FemType *data, struct BoundaryType *bound, char *prefix, int info)
int LoadFieldviewInput (struct FemType *data, struct BoundaryType *bound, char *prefix, int info)
int LoadTriangleInput (struct FemType *data, struct BoundaryType *bound, char *prefix, int info)
int LoadMeditInput (struct FemType *data, struct BoundaryType *bound, char *prefix, int info)
int LoadComsolMesh (struct FemType *data, struct BoundaryType *bound, char *prefix, int info)
int LoadGidInput (struct FemType *data, struct BoundaryType *bound, char *prefix, int info)
int LoadGmshInput (struct FemType *data, struct BoundaryType *bound, char *prefix, int info)
int LoadUniversalMesh (struct FemType *data, struct BoundaryType *bound, char *prefix, int info)
int LoadCGsimMesh (struct FemType *data, char *prefix, int info)
Function Documentation
int LoadAbaqusInput (struct FemType * data, struct BoundaryType * bound, char * prefix, int info)
Definition at line 286 of file egconvert.cpp.
View newest version in sPHENIX GitHub at line 286 of file egconvert.cpp
References AddExtension(), AllocateBoundary(), AllocateKnots(), COORD_AXIS, COORD_CART2, COORD_POLAR, FemType::coordsystem, FemType::dim, FemType::elementtypes, FALSE, INPUTHEPMC::filename, FindPointParents(), free_Ivector, free_ivector(), Getrow(), in, InitializeKnots(), Ivector, ivector(), material(), FemType::material, MAXDOFS, MAXFILESIZE, MAXLINESIZE, FemType::maxnodes, MAXNODESD2, FemType::noelements, FemType::noknots, printf(), StringToInteger(), StringToReal(), FemType::topology, TRUE, FemType::x, FemType::y, and FemType::z.
Referenced by ImportMeshDefinition().
int LoadAnsysInput (struct FemType * data, struct BoundaryType * bound, char * prefix, int info)
Definition at line 1191 of file egconvert.cpp.
View newest version in sPHENIX GitHub at line 1191 of file egconvert.cpp
References AllocateBoundary(), AllocateKnots(), FemType::bodyname, FemType::bodynamesexist, FemType::boundaryname, FemType::boundarynamesexist, FemType::dim, FALSE, INPUTHEPMC::filename, FindPointParents(), free_Ivector, getline, Getrow(), in, InitializeKnots(), Ivector, k, FemType::material, MAX, MAXFILESIZE, MAXLINESIZE, MAXNAMESIZE, FemType::maxnodes, next_int(), next_real(), FemType::noelements, FemType::noknots, BoundaryType::normal, BoundaryType::nosides, BoundaryType::parent, BoundaryType::parent2, printf(), ReorderAnsysNodes(), BoundaryType::side, BoundaryType::side2, TRUE, BoundaryType::types, x, FemType::x, y, FemType::y, z, and FemType::z.
Referenced by ImportMeshDefinition().
int LoadCGsimMesh (struct FemType * data, char * prefix, int info)
Definition at line 3747 of file egconvert.cpp.
View newest version in sPHENIX GitHub at line 3747 of file egconvert.cpp
References AddExtension(), AllocateKnots(), CreateVariable(), Acts::Test::debug, Acts::Test::dim, FemType::dim, FemType::dofs, FemType::elementtypes, FALSE, INPUTHEPMC::filename, getline, Getrow(), in, InitializeKnots(), material(), FemType::material, MAXFILESIZE, MAXLINESIZE, FemType::maxnodes, MAXNODESD2, next_int(), next_real(), FemType::noelements, FemType::noknots, printf(), FemType::topology, TRUE, FemType::x, FemType::y, and FemType::z.
Referenced by ImportMeshDefinition().
int LoadComsolMesh (struct FemType * data, struct BoundaryType * bound, char * prefix, int info)
Definition at line 2455 of file egconvert.cpp.
View newest version in sPHENIX GitHub at line 2455 of file egconvert.cpp
References AddExtension(), AllocateKnots(), Comsolrow(), Acts::Test::debug, Acts::Test::dim, FemType::dim, ElementsToBoundaryConditions(), FemType::elementtypes, FALSE, INPUTHEPMC::filename, GetElementDimension(), in, InitializeKnots(), k, material(), FemType::material, MAXFILESIZE, MAXLINESIZE, FemType::maxnodes, next_int(), next_real(), FemType::noelements, FemType::noknots, offset, printf(), ReorderComsolNodes(), FemType::topology, TRUE, FemType::x, FemType::y, and FemType::z.
Referenced by ImportMeshDefinition().
int LoadFidapInput (struct FemType * data, struct BoundaryType * bound, char * prefix, int info)
Definition at line 829 of file egconvert.cpp.
View newest version in sPHENIX GitHub at line 829 of file egconvert.cpp
References AddExtension(), AllocateKnots(), FemType::bodyname, FemType::bodynamesexist, CreateVariable(), Acts::Test::dim, FemType::dim, FemType::dofs, ElementsToBoundaryConditions(), FemType::elementtypes, FALSE, INPUTHEPMC::filename, free_Imatrix, getline, Imatrix, in, InitializeKnots(), ivector(), k, FemType::material, MAXFILESIZE, MAXLINESIZE, MAXNAMESIZE, FemType::maxnodes, next_int(), FemType::noelements, FemType::noknots, printf(), RenumberBoundaryTypes(), ReorderFidapNodes(), FemType::topology, TRUE, FemType::x, FemType::y, and FemType::z.
Referenced by ImportMeshDefinition().
int LoadFieldviewInput (struct FemType * data, struct BoundaryType * bound, char * prefix, int info)
Definition at line 1578 of file egconvert.cpp.
View newest version in sPHENIX GitHub at line 1578 of file egconvert.cpp
References AddExtension(), FemType::created, FemType::dim, ElementsToBoundaryConditions(), FemType::elementtypes, FALSE, INPUTHEPMC::filename, getline, Imatrix, in, InitializeKnots(), Ivector, k, FemType::material, MAXFILESIZE, MAXLINESIZE, FemType::maxnodes, next_int(), FemType::noelements, FemType::noknots, printf(), ReorderFieldviewNodes(), Rvector, FemType::topology, TRUE, x, FemType::x, y, FemType::y, z, and FemType::z.
Referenced by ImportMeshDefinition().
int LoadGidInput (struct FemType * data, struct BoundaryType * bound, char * prefix, int info)
Definition at line 2095 of file egconvert.cpp.
View newest version in sPHENIX GitHub at line 2095 of file egconvert.cpp
References AddExtension(), AllocateBoundary(), AllocateKnots(), BoundaryType::created, Acts::Test::debug, Acts::Test::dim, FemType::dim, FemType::elementtypes, FALSE, INPUTHEPMC::filename, free_Imatrix, free_Ivector, GetElementSide(), Getrow(), Imatrix, in, InitializeKnots(), Ivector, k, material(), FemType::material, MAXFILESIZE, MAXLINESIZE, FemType::maxnodes, MAXNODESD1, MAXNODESD2, n, next_int(), next_real(), FemType::noelements, FemType::noknots, BoundaryType::nosides, BoundaryType::parent, BoundaryType::parent2, printf(), BoundaryType::side, BoundaryType::side2, FemType::topology, TRUE, BoundaryType::types, x, FemType::x, y, FemType::y, z, and FemType::z.
Referenced by ImportMeshDefinition().
int LoadGmshInput (struct FemType * data, struct BoundaryType * bound, char * prefix, int info)
Definition at line 3140 of file egconvert.cpp.
View newest version in sPHENIX GitHub at line 3140 of file egconvert.cpp
References FALSE, INPUTHEPMC::filename, Getrow(), in, LoadGmshInput1(), LoadGmshInput2(), MAXFILESIZE, MAXLINESIZE, and printf().
Referenced by ImportMeshDefinition().
int LoadMeditInput (struct FemType * data, struct BoundaryType * bound, char * prefix, int info)
Definition at line 1976 of file egconvert.cpp.
View newest version in sPHENIX GitHub at line 1976 of file egconvert.cpp
References nanoflann::allocate(), AllocateKnots(), Acts::Test::dim, FemType::dim, FemType::elementtypes, FALSE, getline, Getrow(), in, InitializeKnots(), FemType::material, MAXFILESIZE, MAXLINESIZE, FemType::maxnodes, next_int(), next_real(), FemType::noelements, FemType::noknots, printf(), FemType::topology, TRUE, FemType::x, FemType::y, and FemType::z.
Referenced by ImportMeshDefinition().
int LoadNastranInput (struct FemType * data, struct BoundaryType * bound, char * prefix, int info)
Definition at line 556 of file egconvert.cpp.
View newest version in sPHENIX GitHub at line 556 of file egconvert.cpp
References AddExtension(), AllocateKnots(), FemType::dim, FemType::elementtypes, FALSE, INPUTHEPMC::filename, Getrow(), in, InitializeKnots(), k, material(), FemType::material, MAXDOFS, MAXFILESIZE, MAXLINESIZE, FemType::maxnodes, next_int(), next_real(), FemType::noelements, FemType::noknots, printf(), FemType::topology, TRUE, FemType::x, FemType::y, and FemType::z.
Referenced by ImportMeshDefinition().
int LoadTriangleInput (struct FemType * data, struct BoundaryType * bound, char * prefix, int info)
Definition at line 1802 of file egconvert.cpp.
View newest version in sPHENIX GitHub at line 1802 of file egconvert.cpp
References AllocateBoundary(), AllocateKnots(), CreateInverseTopology(), Acts::Test::dim, FemType::dim, FemType::elementtypes, FALSE, GetElementSide(), getline, in, InitializeKnots(), FemType::invtopo, Ivector, k, k2, FemType::material, MAXFILESIZE, FemType::maxinvtopo, MAXLINESIZE, FemType::maxnodes, next_int(), next_real(), FemType::noelements, FemType::noknots, BoundaryType::parent, BoundaryType::parent2, printf(), BoundaryType::side, BoundaryType::side2, FemType::topology, TRUE, BoundaryType::types, FemType::x, and FemType::y.
Referenced by ImportMeshDefinition().
int LoadUniversalMesh (struct FemType * data, struct BoundaryType * bound, char * prefix, int info)
Definition at line 3338 of file egconvert.cpp.
View newest version in sPHENIX GitHub at line 3338 of file egconvert.cpp
References AddExtension(), AllocateKnots(), bigerror(), FemType::bodyname, FemType::bodynamesexist, FemType::boundarynamesexist, Acts::Test::debug, Acts::Test::dim, FemType::dim, ElementsToBoundaryConditions(), FemType::elementtypes, exit(), FALSE, INPUTHEPMC::filename, free_Ivector, Getrow(), GetrowDouble(), in, InitializeKnots(), Ivector, k, FemType::material, MAX, MAXFILESIZE, MAXLINESIZE, MAXNAMESIZE, FemType::maxnodes, MIN, n, next_int(), next_real(), FemType::noelements, FemType::noknots, printf(), FemType::topology, TRUE, UnvRedundantIndexes(), UnvToElmerIndx(), UnvToElmerType(), FemType::x, FemType::y, and FemType::z.
Referenced by ImportMeshDefinition().