EIC Software: ValRange Class Reference
ValRange Class Reference
#include <EicRoot/blob/master/dbase/dbValidation/ValRange.h>
Public Member Functions
ValRange ()
ValRange (const Int_t detMask, const Int_t simMask, const ValTimeStamp &tstart, const ValTimeStamp &tend, const TString &source)
virtual ~ValRange ()
const char * AsString (Option_t *option="") const
Bool_t IsCompatible (const ValContext &vldc) const
Bool_t IsCompatible (const ValContext *vldc) const
Int_t GetDetectorMask () const
Int_t GetSimMask () const
ValTimeStamp GetTimeStart () const
ValTimeStamp GetTimeEnd () const
TString GetDataSource () const
void Print (Option_t *option="") const
Print to stdout. See AsString() for options.
void TrimTo (const ValRange &vldr)
void SetTimeStart (const ValTimeStamp &tstart)
void SetTimeEnd (const ValTimeStamp &tend)
Protected Attributes
Int_t fDetectorMask
Int_t fSimMask
or's Detector::Detector_t
ValTimeStamp fTimeStart
or's of data/mc conditions
ValTimeStamp fTimeEnd
TString fDataSource
Detailed Description
Definition at line 19 of file ValRange.h.
View newest version in sPHENIX GitHub at line 19 of file ValRange.h
Constructor & Destructor Documentation
ValRange::ValRange ()
Definition at line 15 of file ValRange.cxx.
View newest version in sPHENIX GitHub at line 15 of file ValRange.cxx
ValRange::ValRange (const Int_t detMask, const Int_t simMask, const ValTimeStamp & tstart, const ValTimeStamp & tend, const TString & source)
Definition at line 22 of file ValRange.cxx.
View newest version in sPHENIX GitHub at line 22 of file ValRange.cxx
ValRange::~ValRange () virtual
Definition at line 33 of file ValRange.cxx.
View newest version in sPHENIX GitHub at line 33 of file ValRange.cxx
Member Function Documentation
const char * ValRange::AsString (Option_t * option = "") const
Return the ValRange as a string
Result is a pointer to a statically allocated string. User should copy this into their own buffer before calling this method again.
option "a": give detector/simflag masks as alpha chars option "c": compact (single line) option "s": drop nsec part of times option "1": include only "start time" option "-": don't include "source" info
Definition at line 40 of file ValRange.cxx.
View newest version in sPHENIX GitHub at line 40 of file ValRange.cxx
References ValTimeStamp::AsString(), fDataSource, fDetectorMask, fSimMask, fTimeEnd, fTimeStart, SimFlag::MaskToString(), and Detector::MaskToString().
Referenced by FairDbValidityRec::Fill(), FairDbValidityRec::IsCompatible(), and Print().
TString ValRange::GetDataSource () const inline
Definition at line 55 of file ValRange.h.
View newest version in sPHENIX GitHub at line 55 of file ValRange.h
Referenced by FairDbBinaryFile::operator<<(), and FairDbValidityRec::SetTimeWindow().
Int_t ValRange::GetDetectorMask () const inline
Definition at line 51 of file ValRange.h.
View newest version in sPHENIX GitHub at line 51 of file ValRange.h
Referenced by FairDbLogEntry::Fill(), FairDbValidityRec::HasExpired(), FairDbBinaryFile::operator<<(), FairDbValidityRec::SetTimeWindow(), and FairDbValidityRec::Store().
Int_t ValRange::GetSimMask () const inline
Definition at line 52 of file ValRange.h.
View newest version in sPHENIX GitHub at line 52 of file ValRange.h
Referenced by FairDbLogEntry::Fill(), FairDbValidityRec::HasExpired(), FairDbBinaryFile::operator<<(), FairDbValidityRec::SetTimeWindow(), and FairDbValidityRec::Store().
ValTimeStamp ValRange::GetTimeEnd () const inline
Definition at line 54 of file ValRange.h.
View newest version in sPHENIX GitHub at line 54 of file ValRange.h
Referenced by FairDbValidityRec::AndTimeWindow(), ClassImp(), FairDbValidityRec::HasExpired(), FairDbBinaryFile::operator<<(), FairDbValidityRec::Store(), and FairDbValidityRec::Trim().
ValTimeStamp ValRange::GetTimeStart () const inline
Definition at line 53 of file ValRange.h.
View newest version in sPHENIX GitHub at line 53 of file ValRange.h
Referenced by FairDbValidityRec::AndTimeWindow(), ClassImp(), FairDbLogEntry::Fill(), FairDbValidityRec::HasExpired(), FairDbBinaryFile::operator<<(), FairDbValidityRec::Store(), and FairDbValidityRec::Trim().
Bool_t ValRange::IsCompatible (const ValContext & vldc) const
Compare ValContext with this ValRange to see if the the tagged set is compatible.
Definition at line 110 of file ValRange.cxx.
View newest version in sPHENIX GitHub at line 110 of file ValRange.cxx
References fDetectorMask, fSimMask, fTimeEnd, fTimeStart, ValContext::GetDetector(), ValContext::GetSimFlag(), ValContext::GetTimeStamp(), SimFlag::kUnknown, and Detector::kUnknown.
Referenced by IsCompatible(), and FairDbValidityRec::IsCompatible().
Bool_t ValRange::IsCompatible (const ValContext * vldc) const
Compare ValContext with this ValRange to see if the the tagged set is compatible.
Definition at line 136 of file ValRange.cxx.
View newest version in sPHENIX GitHub at line 136 of file ValRange.cxx
References IsCompatible().
void ValRange::Print (Option_t * option = "") const
Print to stdout. See AsString() for options.
Definition at line 145 of file ValRange.cxx.
View newest version in sPHENIX GitHub at line 145 of file ValRange.cxx
References AsString(), and printf().
Referenced by ValValidate::TestRange().
void ValRange::SetTimeEnd (const ValTimeStamp & tend) inline
Definition at line 64 of file ValRange.h.
View newest version in sPHENIX GitHub at line 64 of file ValRange.h
void ValRange::SetTimeStart (const ValTimeStamp & tstart) inline
Definition at line 63 of file ValRange.h.
View newest version in sPHENIX GitHub at line 63 of file ValRange.h
void ValRange::TrimTo (const ValRange & vldr)
Trim this range to the intersection (ie. more restricted) limits of it's initial value and that of the argument
Definition at line 153 of file ValRange.cxx.
View newest version in sPHENIX GitHub at line 153 of file ValRange.cxx
References fDataSource, fDetectorMask, fSimMask, fTimeEnd, and fTimeStart.
Member Data Documentation
TString ValRange::fDataSource protected
Definition at line 72 of file ValRange.h.
View newest version in sPHENIX GitHub at line 72 of file ValRange.h
Referenced by AsString(), and TrimTo().
Int_t ValRange::fDetectorMask protected
Definition at line 68 of file ValRange.h.
View newest version in sPHENIX GitHub at line 68 of file ValRange.h
Referenced by AsString(), IsCompatible(), and TrimTo().
Int_t ValRange::fSimMask protected
or's Detector::Detector_t
Definition at line 69 of file ValRange.h.
View newest version in sPHENIX GitHub at line 69 of file ValRange.h
Referenced by AsString(), IsCompatible(), and TrimTo().
ValTimeStamp ValRange::fTimeEnd protected
Definition at line 71 of file ValRange.h.
View newest version in sPHENIX GitHub at line 71 of file ValRange.h
Referenced by AsString(), IsCompatible(), and TrimTo().
ValTimeStamp ValRange::fTimeStart protected
or's of data/mc conditions
Definition at line 70 of file ValRange.h.
View newest version in sPHENIX GitHub at line 70 of file ValRange.h
Referenced by AsString(), IsCompatible(), and TrimTo().
The documentation for this class was generated from the following files:
EicRoot/blob/master/dbase/dbValidation/ValRange.h
EicRoot/blob/master/dbase/dbValidation/ValRange.cxx