EIC Software: estarlight/blob/master/include/reportingUtils.h File Reference
reportingUtils.h File Reference
#include <iostream>
#include <iomanip>
#include <string>
#include <vector>
Macros
#define printErr std::cerr << "!!! " << __PRETTY_FUNCTION__ << " [" << __FILE__ << ":" << __LINE__ << "]: ERROR: " << std::flush
#define printWarn std::cerr << ">>> " << __PRETTY_FUNCTION__ << " [" << __FILE__ << ":" << __LINE__ << "]: "<<std::endl<<"Warning: " << std::flush
#define printInfo std::cout << ">>> " << getClassMethod__(__PRETTY_FUNCTION__) << "(): Info: " << std::flush
#define SVN_VERSION "undefined"
#define CMAKE_SOURCE_DIR "undefined"
Functions
std::string getClassMethod__ (std::string prettyFunction)
std::string svnVersion ()
void printSvnVersion ()
std::string compileDir ()
void printCompilerInfo ()
template<typename T1 , typename T2 >
std::ostream & operator<< (std::ostream &out, const std::pair< T1, T2 > &pair)
template<typename T >
std::ostream & operator<< (std::ostream &out, const std::vector< T > &vec)
std::ostream & progressIndicator (const unsigned int currentPos, const unsigned int nmbTotal, const bool absolute=false, const unsigned int fieldWidth=3, const unsigned int nmbSteps=10, std::ostream &out=std::cout)
std::string trueFalse (const bool val)
std::string yesNo (const bool val)
std::string onOff (const bool val)
std::string enDisabled (const bool val)
Macro Definition Documentation
#define CMAKE_SOURCE_DIR "undefined"
Definition at line 90 of file reportingUtils.h.
View newest version in sPHENIX GitHub at line 90 of file reportingUtils.h
Referenced by compileDir().
#define printErr std::cerr << "!!! " << __PRETTY_FUNCTION__ << " [" << __FILE__ << ":" << __LINE__ << "]: ERROR: " << std::flush
Definition at line 64 of file reportingUtils.h.
View newest version in sPHENIX GitHub at line 64 of file reportingUtils.h
#define printInfo std::cout << ">>> " << getClassMethod__(__PRETTY_FUNCTION__) << "(): Info: " << std::flush
Definition at line 66 of file reportingUtils.h.
View newest version in sPHENIX GitHub at line 66 of file reportingUtils.h
Referenced by inputParameters::configureFromFile(), e_starlight::init(), inputParameters::init(), e_starlight::luminosityTableIsValid(), printCompilerInfo(), printSvnVersion(), and e_starlightStandalone::run().
#define printWarn std::cerr << ">>> " << __PRETTY_FUNCTION__ << " [" << __FILE__ << ":" << __LINE__ << "]: "<<std::endl<<"Warning: " << std::flush
Definition at line 65 of file reportingUtils.h.
View newest version in sPHENIX GitHub at line 65 of file reportingUtils.h
Referenced by inputParser::addParameter(), nBodyPhaseSpaceGen::calcWeight(), inputParameters::configureFromFile(), e_starlight::createEventChannel(), nBodyPhaseSpaceGen::eventAccepted(), pythiaDecayer::execute(), nBodyPhaseSpaceGen::generateDecay(), nBodyPhaseSpaceGen::generateDecayAccepted(), e_starlightStandalone::init(), nucleus::init(), e_starlight::init(), inputParameters::init(), beam::photonDensity(), e_starlightStandalone::run(), and nBodyPhaseSpaceGen::setDecay().
#define SVN_VERSION "undefined"
Definition at line 73 of file reportingUtils.h.
View newest version in sPHENIX GitHub at line 73 of file reportingUtils.h
Referenced by svnVersion().
Function Documentation
std::string compileDir () inline
Definition at line 92 of file reportingUtils.h.
View newest version in sPHENIX GitHub at line 92 of file reportingUtils.h
References CMAKE_SOURCE_DIR.
Referenced by printCompilerInfo().
std::string enDisabled (const bool val) inline
Definition at line 191 of file reportingUtils.h.
View newest version in sPHENIX GitHub at line 191 of file reportingUtils.h
std::string getClassMethod__ (std::string prettyFunction) inline
Definition at line 51 of file reportingUtils.h.
View newest version in sPHENIX GitHub at line 51 of file reportingUtils.h
References pos().
std::string onOff (const bool val) inline
Definition at line 181 of file reportingUtils.h.
View newest version in sPHENIX GitHub at line 181 of file reportingUtils.h
template<typename T1 , typename T2 > std::ostream& operator<< (std::ostream & out, const std::pair< T1, T2 > & pair) inline
Definition at line 117 of file reportingUtils.h.
View newest version in sPHENIX GitHub at line 117 of file reportingUtils.h
template<typename T > std::ostream& operator<< (std::ostream & out, const std::vector< T > & vec) inline
Definition at line 127 of file reportingUtils.h.
View newest version in sPHENIX GitHub at line 127 of file reportingUtils.h
void printCompilerInfo () inline
Definition at line 96 of file reportingUtils.h.
View newest version in sPHENIX GitHub at line 96 of file reportingUtils.h
References compileDir(), printInfo, and Acts::Test::time.
Referenced by main().
void printSvnVersion () inline
Definition at line 79 of file reportingUtils.h.
View newest version in sPHENIX GitHub at line 79 of file reportingUtils.h
References printInfo, and svnVersion().
Referenced by main().
std::ostream& progressIndicator (const unsigned int currentPos, const unsigned int nmbTotal, const bool absolute = false, const unsigned int fieldWidth = 3, const unsigned int nmbSteps = 10, std::ostream & out = std::cout) inline
Definition at line 141 of file reportingUtils.h.
View newest version in sPHENIX GitHub at line 141 of file reportingUtils.h
References Acts::Test::step().
Referenced by e_starlightStandalone::run().
std::string svnVersion () inline
Definition at line 75 of file reportingUtils.h.
View newest version in sPHENIX GitHub at line 75 of file reportingUtils.h
References SVN_VERSION.
Referenced by printSvnVersion().
std::string trueFalse (const bool val) inline
Definition at line 161 of file reportingUtils.h.
View newest version in sPHENIX GitHub at line 161 of file reportingUtils.h
std::string yesNo (const bool val) inline
Definition at line 171 of file reportingUtils.h.
View newest version in sPHENIX GitHub at line 171 of file reportingUtils.h
Referenced by inputParameters::print(), MapsGeoParData::UseTriangularAssemblies(), MapsGeoParData::WithEnforcementBrackets(), MapsGeoParData::WithExternalPipes(), MapsGeoParData::WithMountingRings(), and GemGeoParData::WithMountingRings().