EIC Software: EicRoot/blob/master/pCDR-2018/lqst/acceptance.C File Reference
acceptance.C File Reference
Macros
#define _THETA_PLOT_
#define _EX_ (22.0E-6)
#define _EY_ (3.3E-6)
#define _DPP_ (10E-4)
#define _X0_ (207.24)
#define _Y0_ (0.00)
#define _SIGMA_CUT_ (10.0)
#define _DX_ (-0.22)
#define _BETA_X_ (87E3)
#define _BETA_Y_ (56E3)
#define _P0_ (18.0)
#define _ME_ (0.5E-4)
Functions
gStyle SetOptStat (0)
gStyle SetPadBottomMargin (0.13)
cbmsim AddFriend ("cbmsim","digitization.root")
cbmsim SetBranchAddress ("LqstTrackingDigiHit",&lqstHitArray)
cbmsim SetBranchAddress ("MCTrack",&mcTrackArray)
th0 SetMinimum (0)
th0 SetLineWidth (2)
th0 SetLineColor (kBlack)
th1 SetLineColor (kGreen)
th2 SetLineColor (kRed)
th3 SetLineColor (kBlue)
q2h0 SetLineWidth (3)
q2h3 SetLineWidth (1)
for (unsigned ev=0;ev< nEvents;ev++)
q2h0 GetXaxis () -> SetTitle("log(Q^
q2h0 GetYaxis () -> SetTitle("Events")
q2h0 Draw ()
q2h1 Draw ("SAME")
gPad SetGrid ()
Variables
TFile * ff = new TFile("simulation.root")
TTree * cbmsim = ff->Get("cbmsim")
TClonesArray * lqstHitArray = new TClonesArray("EicTrackingDigiHitOrth2D")
TClonesArray * mcTrackArray = new TClonesArray("PndMCTrack")
TCanvas * c1 = new TCanvas("c1", "c1", 0, 0, 800, 500)
TH1D * th0 = new TH1D("th0", "", 250, 0., 25.)
TH1D * th1 = new TH1D("th1", "", 250, 0., 25.)
TH1D * th2 = new TH1D("th2", "", 250, 0., 25.)
TH1D * th3 = new TH1D("th3", "", 250, 0., 25.)
TH1D * hxl = new TH1D("hxl", "" , 200, -1.0, 1.0)
TH1D * q2h0 = new TH1D("q2h0", "" , 100, -20.0, 5.0)
TH1D * q2h1 = new TH1D("q2h1", "" , 100, -20.0, 5.0)
TH1D * q2h3 = new TH1D("q2h3", "" , 100, -20.0, 5.0)
double sigx = sqrt(_EX_*_BETA_X_)
double sigy = sqrt(_EY_*_BETA_Y_)
double sigp = _DX_ * _DPP_ * 1E3
int nEvents = cbmsim->GetEntries()
Macro Definition Documentation
#define _BETA_X_ (87E3)
Definition at line 27 of file acceptance.C.
View newest version in sPHENIX GitHub at line 27 of file acceptance.C
#define _BETA_Y_ (56E3)
Definition at line 28 of file acceptance.C.
View newest version in sPHENIX GitHub at line 28 of file acceptance.C
#define _DPP_ (10E-4)
Definition at line 13 of file acceptance.C.
View newest version in sPHENIX GitHub at line 13 of file acceptance.C
#define _DX_ (-0.22)
Definition at line 24 of file acceptance.C.
View newest version in sPHENIX GitHub at line 24 of file acceptance.C
#define _EX_ (22.0E-6)
Definition at line 9 of file acceptance.C.
View newest version in sPHENIX GitHub at line 9 of file acceptance.C
#define _EY_ (3.3E-6)
Definition at line 10 of file acceptance.C.
View newest version in sPHENIX GitHub at line 10 of file acceptance.C
#define _ME_ (0.5E-4)
Definition at line 33 of file acceptance.C.
View newest version in sPHENIX GitHub at line 33 of file acceptance.C
Referenced by for().
#define _P0_ (18.0)
Definition at line 31 of file acceptance.C.
View newest version in sPHENIX GitHub at line 31 of file acceptance.C
Referenced by for().
#define _SIGMA_CUT_ (10.0)
Definition at line 21 of file acceptance.C.
View newest version in sPHENIX GitHub at line 21 of file acceptance.C
Referenced by for().
#define _THETA_PLOT_
Definition at line 2 of file acceptance.C.
View newest version in sPHENIX GitHub at line 2 of file acceptance.C
#define _X0_ (207.24)
Definition at line 17 of file acceptance.C.
View newest version in sPHENIX GitHub at line 17 of file acceptance.C
Referenced by for().
#define _Y0_ (0.00)
Definition at line 18 of file acceptance.C.
View newest version in sPHENIX GitHub at line 18 of file acceptance.C
Referenced by for().
Function Documentation
cbmsim AddFriend ("cbmsim" , "digitization.root")
q2h0 Draw ()
q2h1 Draw ("SAME")
for ()
Definition at line 128 of file acceptance.C.
View newest version in sPHENIX GitHub at line 128 of file acceptance.C
References _ME_, _P0_, _SIGMA_CUT_, _SX0_, _SY0_, _X0_, _Y0_, PndMCTrack::GetMomentum(), p, printf(), sigx, sigy, and theta().
q2h0 GetXaxis () -> SetTitle("log(Q^
Definition at line 238 of file acceptance.C.
View newest version in sPHENIX GitHub at line 238 of file acceptance.C
q2h0 GetYaxis () -> SetTitle("Events")
cbmsim SetBranchAddress ("LqstTrackingDigiHit" , & lqstHitArray)
cbmsim SetBranchAddress ("MCTrack" , & mcTrackArray)
gPad SetGrid ()
th0 SetLineColor (kBlack)
th1 SetLineColor (kGreen)
th2 SetLineColor (kRed)
th3 SetLineColor (kBlue)
th0 SetLineWidth (2)
q2h0 SetLineWidth (3)
q2h3 SetLineWidth (1)
th0 SetMinimum (0)
gStyle SetOptStat (0)
Referenced by analysis_resolution(), LoopEvalFR(), LoopEvalHR(), and LoopEvalPortableCircularCut().
gStyle SetPadBottomMargin (0. 13)
Variable Documentation
TCanvas* c1 = new TCanvas("c1", "c1", 0, 0, 800, 500)
Definition at line 53 of file acceptance.C.
View newest version in sPHENIX GitHub at line 53 of file acceptance.C
TTree* cbmsim = ff->Get("cbmsim")
Definition at line 45 of file acceptance.C.
View newest version in sPHENIX GitHub at line 45 of file acceptance.C
TFile* ff = new TFile("simulation.root")
Definition at line 44 of file acceptance.C.
View newest version in sPHENIX GitHub at line 44 of file acceptance.C
TH1D* hxl = new TH1D("hxl", "" , 200, -1.0, 1.0)
Definition at line 76 of file acceptance.C.
View newest version in sPHENIX GitHub at line 76 of file acceptance.C
TClonesArray* lqstHitArray = new TClonesArray("EicTrackingDigiHitOrth2D")
Definition at line 48 of file acceptance.C.
View newest version in sPHENIX GitHub at line 48 of file acceptance.C
TClonesArray* mcTrackArray = new TClonesArray("PndMCTrack")
Definition at line 50 of file acceptance.C.
View newest version in sPHENIX GitHub at line 50 of file acceptance.C
int nEvents = cbmsim->GetEntries()
Definition at line 127 of file acceptance.C.
View newest version in sPHENIX GitHub at line 127 of file acceptance.C
TH1D* q2h0 = new TH1D("q2h0", "" , 100, -20.0, 5.0)
Definition at line 79 of file acceptance.C.
View newest version in sPHENIX GitHub at line 79 of file acceptance.C
TH1D* q2h1 = new TH1D("q2h1", "" , 100, -20.0, 5.0)
Definition at line 81 of file acceptance.C.
View newest version in sPHENIX GitHub at line 81 of file acceptance.C
TH1D* q2h3 = new TH1D("q2h3", "" , 100, -20.0, 5.0)
Definition at line 83 of file acceptance.C.
View newest version in sPHENIX GitHub at line 83 of file acceptance.C
double sigp = _DX_ * _DPP_ * 1E3
Definition at line 119 of file acceptance.C.
View newest version in sPHENIX GitHub at line 119 of file acceptance.C
sigx = sqrt(_EX_*_BETA_X_)
Definition at line 118 of file acceptance.C.
View newest version in sPHENIX GitHub at line 118 of file acceptance.C
double sigy = sqrt(_EY_*_BETA_Y_)
Definition at line 118 of file acceptance.C.
View newest version in sPHENIX GitHub at line 118 of file acceptance.C
TH1D* th0 = new TH1D("th0", "", 250, 0., 25.)
Definition at line 55 of file acceptance.C.
View newest version in sPHENIX GitHub at line 55 of file acceptance.C
TH1D* th1 = new TH1D("th1", "", 250, 0., 25.)
Definition at line 57 of file acceptance.C.
View newest version in sPHENIX GitHub at line 57 of file acceptance.C
TH1D* th2 = new TH1D("th2", "", 250, 0., 25.)
Definition at line 58 of file acceptance.C.
View newest version in sPHENIX GitHub at line 58 of file acceptance.C
TH1D* th3 = new TH1D("th3", "", 250, 0., 25.)
Definition at line 59 of file acceptance.C.
View newest version in sPHENIX GitHub at line 59 of file acceptance.C