EIC Software: FairDbResultKey Class Reference
FairDbResultKey Class Reference
#include <EicRoot/blob/master/dbase/dbInterface/FairDbResult.h>
Classes
struct VRecKey
Public Member Functions
FairDbResultKey (const FairDbResultKey *that=0)
FairDbResultKey (std::string tableName, std::string rowName, UInt_t seqno, ValTimeStamp ts)
.....................................................................
virtual ~FairDbResultKey ()
std::string AsString () const
Float_t Compare (const FairDbResultKey *that) const
Int_t GetNumVrecs () const
std::string GetTableRowName () const
Bool_t IsEqualTo (const FairDbResultKey *that) const
void AddVRecKey (UInt_t seqno, ValTimeStamp ts)
Static Public Member Functions
static const FairDbResultKey * GetEmptyKey ()
Private Attributes
std::string fTableName
std::string fRowName
std::list
< FairDbResultKey::VRecKey > fVRecKeys
Int_t fNumVRecKeys
Static Private Attributes
static FairDbResultKey fgEmptyKey
Detailed Description
Definition at line 27 of file FairDbResult.h.
View newest version in sPHENIX GitHub at line 27 of file FairDbResult.h
Constructor & Destructor Documentation
FairDbResultKey::FairDbResultKey (const FairDbResultKey * that = 0)
Definition at line 375 of file FairDbResult.cxx.
View newest version in sPHENIX GitHub at line 375 of file FairDbResult.cxx
FairDbResultKey::FairDbResultKey (std::string tableName, std::string rowName, UInt_t seqno, ValTimeStamp ts)
.....................................................................
Definition at line 386 of file FairDbResult.cxx.
View newest version in sPHENIX GitHub at line 386 of file FairDbResult.cxx
References AddVRecKey().
FairDbResultKey::~FairDbResultKey () virtual
Definition at line 401 of file FairDbResult.cxx.
View newest version in sPHENIX GitHub at line 401 of file FairDbResult.cxx
Member Function Documentation
void FairDbResultKey::AddVRecKey (UInt_t seqno, ValTimeStamp ts)
Definition at line 408 of file FairDbResult.cxx.
View newest version in sPHENIX GitHub at line 408 of file FairDbResult.cxx
References fNumVRecKeys, and fVRecKeys.
Referenced by FairDbResultAgg::CreateKey(), and FairDbResultKey().
std::string FairDbResultKey::AsString () const
Definition at line 418 of file FairDbResult.cxx.
View newest version in sPHENIX GitHub at line 418 of file FairDbResult.cxx
References ValTimeStamp::AsString(), fNumVRecKeys, fRowName, fTableName, and fVRecKeys.
Referenced by operator<<().
Float_t FairDbResultKey::Compare (const FairDbResultKey * that) const
Definition at line 462 of file FairDbResult.cxx.
View newest version in sPHENIX GitHub at line 462 of file FairDbResult.cxx
References fRowName, fTableName, fVRecKeys, and GetNumVrecs().
Referenced by IsEqualTo().
static const FairDbResultKey* FairDbResultKey::GetEmptyKey () inline static
Definition at line 45 of file FairDbResult.h.
View newest version in sPHENIX GitHub at line 45 of file FairDbResult.h
References fgEmptyKey.
Referenced by FairDbResult::GetKey().
Int_t FairDbResultKey::GetNumVrecs () const inline
Definition at line 46 of file FairDbResult.h.
View newest version in sPHENIX GitHub at line 46 of file FairDbResult.h
References fNumVRecKeys.
Referenced by Compare().
std::string FairDbResultKey::GetTableRowName () const
Definition at line 504 of file FairDbResult.cxx.
View newest version in sPHENIX GitHub at line 504 of file FairDbResult.cxx
References fRowName, and fTableName.
Bool_t FairDbResultKey::IsEqualTo (const FairDbResultKey * that) const inline
Definition at line 48 of file FairDbResult.h.
View newest version in sPHENIX GitHub at line 48 of file FairDbResult.h
References Compare().
Member Data Documentation
FairDbResultKey FairDbResultKey::fgEmptyKey static private
Definition at line 66 of file FairDbResult.h.
View newest version in sPHENIX GitHub at line 66 of file FairDbResult.h
Referenced by GetEmptyKey().
Int_t FairDbResultKey::fNumVRecKeys private
Definition at line 70 of file FairDbResult.h.
View newest version in sPHENIX GitHub at line 70 of file FairDbResult.h
Referenced by AddVRecKey(), AsString(), and GetNumVrecs().
std::string FairDbResultKey::fRowName private
Definition at line 68 of file FairDbResult.h.
View newest version in sPHENIX GitHub at line 68 of file FairDbResult.h
Referenced by AsString(), Compare(), and GetTableRowName().
std::string FairDbResultKey::fTableName private
Definition at line 67 of file FairDbResult.h.
View newest version in sPHENIX GitHub at line 67 of file FairDbResult.h
Referenced by AsString(), Compare(), and GetTableRowName().
std::list<FairDbResultKey::VRecKey> FairDbResultKey::fVRecKeys private
Definition at line 69 of file FairDbResult.h.
View newest version in sPHENIX GitHub at line 69 of file FairDbResult.h
Referenced by AddVRecKey(), AsString(), and Compare().
The documentation for this class was generated from the following files:
EicRoot/blob/master/dbase/dbInterface/FairDbResult.h
EicRoot/blob/master/dbase/dbInterface/FairDbResult.cxx