EIC Software: fun4all_eicmacros/blob/master/common/G4_EHCAL.C File Reference
G4_EHCAL.C File Reference
#include <GlobalVariables.C>
#include <g4calo/RawTowerBuilderByHitIndex.h>
#include <g4calo/RawTowerDigitizer.h>
#include <g4eiccalos/PHG4BackwardHcalSubsystem.h>
#include <g4eval/CaloEvaluator.h>
#include <g4main/PHG4Reco.h>
#include <caloreco/RawClusterBuilderFwd.h>
#include <caloreco/RawClusterBuilderTemplate.h>
#include <caloreco/RawTowerCalibration.h>
#include <fun4all/Fun4AllServer.h>
Namespaces
namespace Enable
namespace G4EHCAL
namespace G4EHCAL::SETTING
Macros
#define MACRO_G4EHCAL_C
Enumerations
enum G4EHCAL::enu_EHCAL_clusterizer { G4EHCAL::kEHCALGraphClusterizer, G4EHCAL::kEHCALTemplateClusterizer }
Functions
void EHCALInit ()
void EHCALSetup (PHG4Reco *g4Reco)
void EHCAL_Cells (int verbosity=0)
void EHCAL_Towers ()
void EHCAL_Clusters ()
void EHCAL_Eval (const std::string &outputfile)
Variables
bool Enable::EHCAL = false
bool Enable::EHCAL_ABSORBER = false
bool Enable::EHCAL_CELL = false
bool Enable::EHCAL_TOWER = false
bool Enable::EHCAL_CLUSTER = false
bool Enable::EHCAL_EVAL = false
bool Enable::EHCAL_OVERLAPCHECK = false
int Enable::EHCAL_VERBOSITY = 0
double G4EHCAL::Gz0 = -360.0
double G4EHCAL::Gdz = 100.
double G4EHCAL::outer_radius = 260.
enu_EHCAL_clusterizer G4EHCAL::EHCAL_clusterizer = kEHCALTemplateClusterizer
bool G4EHCAL::SETTING::FullEtaAcc = false
bool G4EHCAL::SETTING::HC2x = false
bool G4EHCAL::SETTING::HC4x = false
bool G4EHCAL::SETTING::towercalib1 = false
bool G4EHCAL::SETTING::towercalibSiPM = false
bool G4EHCAL::SETTING::towercalibHCALIN = false
bool G4EHCAL::SETTING::towercalib3 = false
Macro Definition Documentation
#define MACRO_G4EHCAL_C
Definition at line 2 of file G4_EHCAL.C.
View newest version in sPHENIX GitHub at line 2 of file G4_EHCAL.C
Function Documentation
void EHCAL_Cells (int verbosity = 0)
Definition at line 144 of file G4_EHCAL.C.
View newest version in sPHENIX GitHub at line 144 of file G4_EHCAL.C
void EHCAL_Clusters ()
Definition at line 314 of file G4_EHCAL.C.
View newest version in sPHENIX GitHub at line 314 of file G4_EHCAL.C
References RawClusterBuilderTemplate::Detector(), RawClusterBuilderFwd::Detector(), G4EHCAL::EHCAL_clusterizer, Enable::EHCAL_VERBOSITY, Fun4AllServer::instance(), G4EHCAL::kEHCALTemplateClusterizer, max, Fun4AllServer::registerSubsystem(), RawClusterBuilderFwd::set_threshold_energy(), RawClusterBuilderTemplate::set_threshold_energy(), RawClusterBuilderTemplate::SetPlanarGeometry(), Enable::VERBOSITY, and Fun4AllBase::Verbosity().
Referenced by Extract_ECCE_gdml(), Fun4All_G4_FullDetectorModular(), and Fun4All_G4_FullDetectorModularBeast().
void EHCAL_Eval (const std::string & outputfile)
Definition at line 345 of file G4_EHCAL.C.
View newest version in sPHENIX GitHub at line 345 of file G4_EHCAL.C
References Enable::EHCAL_VERBOSITY, Fun4AllServer::instance(), max, Fun4AllServer::registerSubsystem(), Enable::VERBOSITY, and Fun4AllBase::Verbosity().
void EHCAL_Towers ()
Definition at line 149 of file G4_EHCAL.C.
View newest version in sPHENIX GitHub at line 149 of file G4_EHCAL.C
References RawTowerDigitizer::Detector(), RawTowerCalibration::Detector(), RawTowerBuilderByHitIndex::Detector(), Acts::UnitConstants::e, Enable::EHCAL_VERBOSITY, G4EHCAL::SETTING::FullEtaAcc, RawTowerBuilderByHitIndex::GeometryTableFile(), G4EHCAL::SETTING::HC2x, G4EHCAL::SETTING::HC4x, Fun4AllServer::instance(), RawTowerDigitizer::kNo_digitization, RawTowerCalibration::kSimple_linear_calibration, RawTowerDigitizer::kSimple_photon_digitalization, RawTowerDigitizer::kSiPM_photon_digitization, max, Fun4AllServer::registerSubsystem(), G4FHCAL::sampling_fraction, RawTowerCalibration::set_calib_algorithm(), RawTowerCalibration::set_calib_const_GeV_ADC(), RawTowerDigitizer::set_digi_algorithm(), RawTowerCalibration::set_pedstal_ADC(), RawTowerDigitizer::set_pedstal_central_ADC(), RawTowerDigitizer::set_pedstal_width_ADC(), RawTowerDigitizer::set_photonelec_ADC(), RawTowerDigitizer::set_photonelec_yield_visible_GeV(), RawTowerCalibration::set_raw_tower_node_prefix(), RawTowerDigitizer::set_raw_tower_node_prefix(), RawTowerBuilderByHitIndex::set_sim_tower_node_prefix(), RawTowerDigitizer::set_zero_suppression_ADC(), RawTowerCalibration::set_zero_suppression_GeV(), G4EHCAL::SETTING::towercalib1, G4EHCAL::SETTING::towercalib3, G4EHCAL::SETTING::towercalibHCALIN, G4EHCAL::SETTING::towercalibSiPM, Enable::VERBOSITY, and Fun4AllBase::Verbosity().
Referenced by Extract_ECCE_gdml(), Fun4All_G4_FullDetectorModular(), and Fun4All_G4_FullDetectorModularBeast().
void EHCALInit ()
Definition at line 66 of file G4_EHCAL.C.
View newest version in sPHENIX GitHub at line 66 of file G4_EHCAL.C
References Acts::UnitConstants::cm, G4EHCAL::SETTING::FullEtaAcc, G4EHCAL::Gdz, G4EHCAL::Gz0, G4EHCAL::SETTING::HC2x, G4EHCAL::SETTING::HC4x, max, BlackHoleGeometry::max_radius, BlackHoleGeometry::max_z, min, BlackHoleGeometry::min_z, G4EHCAL::outer_radius, G4EHCAL::SETTING::towercalib1, G4EHCAL::SETTING::towercalib3, G4EHCAL::SETTING::towercalibHCALIN, and G4EHCAL::SETTING::towercalibSiPM.
Referenced by G4Init().
void EHCALSetup (PHG4Reco * g4Reco)
Use dedicated EHCAL module
Definition at line 90 of file G4_EHCAL.C.
View newest version in sPHENIX GitHub at line 90 of file G4_EHCAL.C
References Enable::ABSORBER, Enable::EHCAL_ABSORBER, Enable::EHCAL_OVERLAPCHECK, G4EHCAL::SETTING::FullEtaAcc, G4EHCAL::SETTING::HC2x, G4EHCAL::SETTING::HC4x, Fun4AllServer::instance(), Enable::OVERLAPCHECK, PHG4DetectorSubsystem::OverlapCheck(), PHG4Reco::registerSubsystem(), PHG4DetectorSubsystem::SetAbsorberActive(), PHG4DetectorSubsystem::SetActive(), PHG4BackwardHcalSubsystem::SetDetailed(), PHG4BackwardHcalSubsystem::SetTowerMappingFile(), and PHG4DetectorSubsystem::SuperDetector().
Referenced by G4Setup().