EIC Software: fun4all_eicmacros/blob/master/detectors/AllSilicon/Development/vertexing/Fun4All_G4_simple_vertex.C File Reference
Fun4All_G4_simple_vertex.C File Reference
#include <phgenfit/Track.h>
#include <fun4all/Fun4AllDstInputManager.h>
#include <fun4all/Fun4AllDstOutputManager.h>
#include <fun4all/Fun4AllDummyInputManager.h>
#include <fun4all/Fun4AllInputManager.h>
#include <fun4all/Fun4AllNoSyncDstInputManager.h>
#include <fun4all/Fun4AllOutputManager.h>
#include <fun4all/Fun4AllServer.h>
#include <fun4all/SubsysReco.h>
#include <g4detectors/PHG4DetectorSubsystem.h>
#include <g4detectors/PHG4CylinderSubsystem.h>
#include <g4histos/G4HitNtuple.h>
#include <g4main/PHG4ParticleGenerator.h>
#include <g4main/PHG4ParticleGeneratorBase.h>
#include <g4main/PHG4Reco.h>
#include <g4main/PHG4TruthSubsystem.h>
#include <g4trackfastsim/PHG4TrackFastSim.h>
#include <g4trackfastsim/PHG4TrackFastSimEval.h>
#include <phool/recoConsts.h>
Functions
void Fun4All_G4_simple_vertex (int nEvents=-1, bool vtx_lyr_1=true, bool vtx_lyr_2=true, bool vtx_lyr_3=true, double vtx_matBud=0.05, double pix_size=10., TString out_name="out_vtx_study")
Function Documentation
void Fun4All_G4_simple_vertex (int nEvents = -1, bool vtx_lyr_1 = true, bool vtx_lyr_2 = true, bool vtx_lyr_3 = true, double vtx_matBud = 0.05, double pix_size = 10., TString out_name = "out_vtx_study")
Definition at line 27 of file Fun4All_G4_simple_vertex.C.
View newest version in sPHENIX GitHub at line 27 of file Fun4All_G4_simple_vertex.C
References PHG4TrackFastSim::add_phg4hits(), G4PIPE::be_pipe_length, G4PIPE::be_pipe_length_neg, G4PIPE::be_pipe_length_plus, G4PIPE::be_pipe_radius, G4PIPE::be_pipe_thickness, PHG4TrackFastSim::Cylinder, PHG4TrackFastSim::enable_vertexing(), Fun4AllServer::End(), in, Fun4AllServer::instance(), Fun4AllServer::registerInputManager(), Fun4AllServer::registerOutputManager(), Fun4AllServer::registerSubsystem(), PHG4Reco::registerSubsystem(), Fun4AllServer::run(), PHG4DetectorSubsystem::set_double_param(), PHG4ParticleGenerator::set_eta_range(), PHG4Reco::set_field(), PHG4TrackFastSimEval::set_filename(), PHG4DetectorSubsystem::set_int_param(), PHG4ParticleGenerator::set_mom_range(), PHG4ParticleGeneratorBase::set_name(), PHG4ParticleGenerator::set_phi_range(), PHG4DetectorSubsystem::set_string_param(), PHG4TrackFastSim::set_sub_top_node_name(), PHG4TrackFastSim::set_trackmap_out_name(), PHG4TrackFastSim::set_use_vertex_in_fitting(), PHG4TrackFastSim::set_vertex_min_ndf(), PHG4TrackFastSim::set_vertex_xy_resolution(), PHG4TrackFastSim::set_vertex_z_resolution(), PHG4ParticleGeneratorBase::set_vtx(), PHG4ParticleGenerator::set_z_range(), PHG4DetectorSubsystem::SetActive(), PHG4Reco::SetWorldMaterial(), PHG4DetectorSubsystem::SuperDetector(), and Fun4AllBase::Verbosity().