EIC Software: fun4all_coresoftware/blob/master/offline/packages/HelixHough/helix_hough/sPHENIX/sPHENIXTrackerTpc.cpp File Reference
sPHENIXTrackerTpc.cpp File Reference
#include "sPHENIXTrackerTpc.h"
#include "CylinderKalman.h"
#include "Pincushion.h"
#include "SimpleTrack3D.h"
#include "vector_math_inline.h"
#include <Eigen/Core>
#include <Eigen/Dense>
#include <Eigen/LU>
#include <algorithm>
#include <cfloat>
#include <cmath>
#include <cstddef>
#include <iostream>
#include <sys/time.h>
#include <utility>
#include <xmmintrin.h>
Classes
class hitTriplet
Functions
static bool remove_bad_hits (SimpleTrack3D &track, float cut, float scale=1.0)
static bool fit_all_update (vector< vector< int > > &layer_indexes, SimpleTrack3D &temp_track, vector< int > &best_ind, vector< float > &best_chi2, SimpleTrack3D &track, float &, int iter=0, float tempscale=1.0, float scale=1.0)
static bool fit_all (vector< SimpleHit3D > &hits, vector< vector< int > > &layer_indexes, SimpleTrack3D &track, float &chi2)
Function Documentation
static bool fit_all (vector< SimpleHit3D > & hits, vector< vector< int > > & layer_indexes, SimpleTrack3D & track, float & chi2) static
Definition at line 850 of file sPHENIXTrackerTpc.cpp.
View newest version in sPHENIX GitHub at line 850 of file sPHENIXTrackerTpc.cpp
References fit_all_update(), sPHENIXTrackerTpc::fitTrack(), and SimpleTrack3D::hits.
Referenced by sPHENIXTrackerTpc::findTracksByCombinatorialKalman().
static bool fit_all_update (vector< vector< int > > & layer_indexes, SimpleTrack3D & temp_track, vector< int > & best_ind, vector< float > & best_chi2, SimpleTrack3D & track, float & , int iter = 0, float tempscale = 1.0, float scale = 1.0) static
Definition at line 749 of file sPHENIXTrackerTpc.cpp.
View newest version in sPHENIX GitHub at line 749 of file sPHENIXTrackerTpc.cpp
References cos(), SimpleTrack3D::d, d, dx, dy, SimpleTrack3D::dzdl, sPHENIXTrackerTpc::fitTrack(), SimpleTrack3D::hits, k, SimpleTrack3D::kappa, SimpleTrack3D::phi, phi, remove_bad_hits(), Acts::UnitConstants::s, temp1, temp2, v, and SimpleTrack3D::z0.
Referenced by fit_all().
static bool remove_bad_hits (SimpleTrack3D & track, float cut, float scale = 1.0) static
Definition at line 724 of file sPHENIXTrackerTpc.cpp.
View newest version in sPHENIX GitHub at line 724 of file sPHENIXTrackerTpc.cpp
References sPHENIXTrackerTpc::fitTrack(), Acts::UnitConstants::h, and SimpleTrack3D::hits.
Referenced by fit_all_update().