EIC Software: CbmStudyReport Class Reference
CbmStudyReport Class Reference
Base class for study reports.
#include <EicRoot/blob/master/cbmbase/report/CbmStudyReport.h>
Public Member Functions
CbmStudyReport ()
Constructor.
virtual ~CbmStudyReport ()
Destructor.
void Create (const vector< CbmHistManager * > &histManagers, const vector< string > &studyNames, const string &outputDir)
Main function which creates report data.
void Create (const vector< string > &fileNames, const vector< string > &studyNames, const string &outputDir)
Main function which creates report data.
const vector< CbmHistManager * > & HM () const
CbmHistManager * HM (Int_t index) const
const vector< string > & GetStudyNames () const
const string & GetStudyName (Int_t index) const
Public Member Functions inherited from CbmReport
CbmReport ()
Constructor.
virtual ~CbmReport ()
Destructor.
const CbmReportElement * R () const
Accessor to CbmReportElement object. User has to write the report using available tags from CbmReportElement class.
ostream & Out () const
All text output goes to this stream.
void SetReportName (const string &name)
void SetReportTitle (const string &title)
void SetOutputDir (const string &outputDir)
const string & GetReportName () const
const string & GetReportTitle () const
const string & GetOutputDir () const
Private Attributes
vector< CbmHistManager * > fHM
vector< string > fStudyNames
Additional Inherited Members
Protected Member Functions inherited from CbmReport
virtual void Create ()=0
Pure abstract function which is called from public Create() function. This function has to write report using Out() for output stream and R() for report elements. This function is called for each report type.
virtual void Draw ()=0
Pure abstract function which is called from public Create() function. This function has to draw all necessary histograms and graphs. It is called only once before report creation.
void CreateReports ()
Create all available report types.
TCanvas * CreateCanvas (const char *name, const char *title, Int_t ww, Int_t wh)
Create canvas and put it to vector of TCanvases. Canvases created with this function will be automatically saved to image and printed in the report.
void SaveCanvasesAsImages () const
Save all canvases to images.
void WriteCanvases () const
Write canvases to file.
void PrintCanvases () const
Print images created from canvases in the report.
Detailed Description
Base class for study reports.
Author
Semen Lebedev s.leb.nosp@m.edev.nosp@m.@gsi..nosp@m.de
Date
2011
Definition at line 26 of file CbmStudyReport.h.
View newest version in sPHENIX GitHub at line 26 of file CbmStudyReport.h
Constructor & Destructor Documentation
CbmStudyReport::CbmStudyReport ()
Constructor.
Definition at line 20 of file CbmStudyReport.cxx.
View newest version in sPHENIX GitHub at line 20 of file CbmStudyReport.cxx
CbmStudyReport::~CbmStudyReport () virtual
Destructor.
Definition at line 28 of file CbmStudyReport.cxx.
View newest version in sPHENIX GitHub at line 28 of file CbmStudyReport.cxx
Member Function Documentation
void CbmStudyReport::Create (const vector< CbmHistManager * > & histManagers, const vector< string > & studyNames, const string & outputDir)
Main function which creates report data.
Non virtual interface pattern is used here. User always creates simulation report using this public non virtual method. In order to configure concrete report generation class user has to implement protected Create() method and getters for the file names.
Parameters
[in] histManagers Array of histogram managers for which report is created.
[in] studyNames Names of studies.
[in] outputDir name of the output directory.
Definition at line 33 of file CbmStudyReport.cxx.
View newest version in sPHENIX GitHub at line 33 of file CbmStudyReport.cxx
References CbmReport::CreateReports(), fHM, fStudyNames, and CbmReport::SetOutputDir().
Referenced by CbmRichGeoTest::CreateStudyReport().
void CbmStudyReport::Create (const vector< string > & fileNames, const vector< string > & studyNames, const string & outputDir)
Main function which creates report data.
Same pattern is used here.
Parameters
[in] fileNames Array of file names for which report is created.
[in] studyNames Names of studies.
[in] outputDir name of the output directory.
Definition at line 45 of file CbmStudyReport.cxx.
View newest version in sPHENIX GitHub at line 45 of file CbmStudyReport.cxx
References CbmReport::CreateReports(), fHM, eicpy.build::files, fStudyNames, and CbmReport::SetOutputDir().
const string& CbmStudyReport::GetStudyName (Int_t index) const inline
Definition at line 75 of file CbmStudyReport.h.
View newest version in sPHENIX GitHub at line 75 of file CbmStudyReport.h
References fStudyNames.
const vector<string>& CbmStudyReport::GetStudyNames () const inline
Definition at line 74 of file CbmStudyReport.h.
View newest version in sPHENIX GitHub at line 74 of file CbmStudyReport.h
References fStudyNames.
Referenced by CbmRichGeoTestStudyReport::Create(), and CbmRichGeoTestStudyReport::PrintRow().
const vector<CbmHistManager*>& CbmStudyReport::HM () const inline
Definition at line 72 of file CbmStudyReport.h.
View newest version in sPHENIX GitHub at line 72 of file CbmStudyReport.h
References fHM.
CbmHistManager* CbmStudyReport::HM (Int_t index) const inline
Definition at line 73 of file CbmStudyReport.h.
View newest version in sPHENIX GitHub at line 73 of file CbmStudyReport.h
References fHM.
Member Data Documentation
vector<CbmHistManager*> CbmStudyReport::fHM private
Definition at line 78 of file CbmStudyReport.h.
View newest version in sPHENIX GitHub at line 78 of file CbmStudyReport.h
Referenced by Create(), and HM().
vector<string> CbmStudyReport::fStudyNames private
Definition at line 79 of file CbmStudyReport.h.
View newest version in sPHENIX GitHub at line 79 of file CbmStudyReport.h
Referenced by Create(), GetStudyName(), and GetStudyNames().
The documentation for this class was generated from the following files:
EicRoot/blob/master/cbmbase/report/CbmStudyReport.h
EicRoot/blob/master/cbmbase/report/CbmStudyReport.cxx