EIC Software: EicEventManager Class Reference
EicEventManager Class Reference
#include <EicRoot/blob/master/eic/base/EicEventManager.h>
Public Member Functions
EicEventManager ()
~EicEventManager ()
void SetInputFile (TString fname)
void Init ()
void Run (Int_t visopt=0, Int_t vislvl=6, Int_t maxvisnds=10000)
Public Member Functions inherited from FairEventManager
FairEventManager ()
virtual ~FairEventManager ()
virtual void Open ()
virtual void GotoEvent (Int_t event)
virtual void NextEvent ()
virtual void PrevEvent ()
virtual void Close ()
virtual void DisplaySettings ()
virtual Int_t Color (Int_t pdg)
void AddTask (FairTask *t)
virtual Int_t GetCurrentEvent ()
virtual void SetPriOnly (Bool_t Pri)
virtual Bool_t IsPriOnly ()
virtual void SelectPDG (Int_t PDG)
virtual Int_t GetCurrentPDG ()
virtual void SetMaxEnergy (Float_t max)
virtual void SetMinEnergy (Float_t min)
virtual void SetEvtMaxEnergy (Float_t max)
virtual void SetEvtMinEnergy (Float_t min)
virtual Float_t GetEvtMaxEnergy ()
virtual Float_t GetEvtMinEnergy ()
virtual Float_t GetMaxEnergy ()
virtual Float_t GetMinEnergy ()
void UpdateEditor ()
virtual void AddParticlesToPdgDataBase ()
ClassDef (FairEventManager, 1)
Private Member Functions
ClassDef (EicEventManager, 2)
Private Attributes
Bool_t mInitCallHappened
Additional Inherited Members
Static Public Member Functions inherited from FairEventManager
static FairEventManager * Instance ()
Protected Attributes inherited from FairEventManager
FairRunAna * fRunAna
TGListTreeItem * fEvent
Detailed Description
Definition at line 14 of file EicEventManager.h.
View newest version in sPHENIX GitHub at line 14 of file EicEventManager.h
Constructor & Destructor Documentation
EicEventManager::EicEventManager ()
Definition at line 16 of file EicEventManager.cxx.
View newest version in sPHENIX GitHub at line 16 of file EicEventManager.cxx
References FairEventManager::fRunAna, FairRunAna::Instance(), and FairRun::SetOutputFile().
EicEventManager::~EicEventManager () inline
Definition at line 18 of file EicEventManager.h.
View newest version in sPHENIX GitHub at line 18 of file EicEventManager.h
Member Function Documentation
EicEventManager::ClassDef (EicEventManager , 2) private
void EicEventManager::Init () virtual
Reimplemented from FairEventManager.
Definition at line 34 of file EicEventManager.cxx.
View newest version in sPHENIX GitHub at line 34 of file EicEventManager.cxx
References FairEventManager::fRunAna, FairRunAna::Init(), EicRunAna::Init(), mInitCallHappened, and Acts::Test::volume.
Referenced by Run().
void EicEventManager::Run (Int_t visopt = 0, Int_t vislvl = 6, Int_t maxvisnds = 10000)
Definition at line 81 of file EicEventManager.cxx.
View newest version in sPHENIX GitHub at line 81 of file EicEventManager.cxx
References FairEventManager::fEvent, Init(), mInitCallHappened, and charm_jet_strange_helicity::N.
Referenced by eventDisplay().
void EicEventManager::SetInputFile (TString fname)
Definition at line 27 of file EicEventManager.cxx.
View newest version in sPHENIX GitHub at line 27 of file EicEventManager.cxx
References FairEventManager::fRunAna, and FairRunAna::SetInputFile().
Referenced by eventDisplay().
Member Data Documentation
Bool_t EicEventManager::mInitCallHappened private
Definition at line 35 of file EicEventManager.h.
View newest version in sPHENIX GitHub at line 35 of file EicEventManager.h
Referenced by Init(), and Run().
The documentation for this class was generated from the following files:
EicRoot/blob/master/eic/base/EicEventManager.h
EicRoot/blob/master/eic/base/EicEventManager.cxx