EIC Software: EicSmearTask Class Reference
EicSmearTask Class Reference
#include <EicRoot/blob/master/eic/event/EicSmearTask.h>
Public Member Functions
EicSmearTask ()
EicSmearTask (TString _inFileName, Smear::Detector *rDetector=0)
~EicSmearTask ()
InitStatus Init ()
void SetParContainers ()
void Exec (Option_t *opt)
void FinishTask ()
Public Member Functions inherited from FairTask
FairTask ()
FairTask (const char *name, Int_t iVerbose=1)
virtual ~FairTask ()
void InitTask ()
void ReInitTask ()
void SetParTask ()
virtual void FinishEvent ()
void SetVerbose (Int_t iVerbose)
void SetInputPersistance (Bool_t val)
void CheckInputPersistance (TString branchName)
Private Member Functions
ClassDef (EicSmearTask, 12)
Private Attributes
TString inFileName
Smear::Detector * detector
TFile * inFile
TFile * outFile
TTree * mcTree
TTree * smearedTree
TBranch * eventbranch
erhic::VirtualEventFactory * builder
TClonesArray * fMCTracks
TClonesArray * fPidChargedCand
Additional Inherited Members
Protected Member Functions inherited from FairTask
virtual InitStatus ReInit ()
virtual void Finish ()
void InitTasks ()
void ReInitTasks ()
void SetParTasks ()
void FinishTasks ()
void FinishEvents ()
Protected Attributes inherited from FairTask
Int_t fVerbose
Int_t fInputPersistance
Indicates if input branch is persistant.
FairLogger * fLogger
Detailed Description
Definition at line 21 of file EicSmearTask.h.
View newest version in sPHENIX GitHub at line 21 of file EicSmearTask.h
Constructor & Destructor Documentation
EicSmearTask::EicSmearTask () inline
Definition at line 23 of file EicSmearTask.h.
View newest version in sPHENIX GitHub at line 23 of file EicSmearTask.h
EicSmearTask::EicSmearTask (TString _inFileName, Smear::Detector * rDetector = 0) inline
Definition at line 24 of file EicSmearTask.h.
View newest version in sPHENIX GitHub at line 24 of file EicSmearTask.h
EicSmearTask::~EicSmearTask () inline
Definition at line 26 of file EicSmearTask.h.
View newest version in sPHENIX GitHub at line 26 of file EicSmearTask.h
Member Function Documentation
EicSmearTask::ClassDef (EicSmearTask , 12) private
void EicSmearTask::Exec (Option_t * opt)
Definition at line 100 of file EicSmearTask.cxx.
View newest version in sPHENIX GitHub at line 100 of file EicSmearTask.cxx
References builder, eventbranch, erhic::VirtualEventFactory::Fill(), fMCTracks, fPidChargedCand, erhic::VirtualEventFactory::GetEvBufferPtr(), PndPidCandidate::GetLorentzVector(), PndPidCandidate::GetMcIndex(), erhic::VirtualEvent::GetNTracks(), PndMCTrack::GetPdgCode(), erhic::VirtualParticle::GetStatus(), erhic::VirtualEvent::GetTrack(), mcTree, and erhic::VirtualParticle::Set4Vector().
void EicSmearTask::FinishTask () virtual
Action at end of run. For this task and all of the subtasks.
Reimplemented from FairTask.
Definition at line 161 of file EicSmearTask.cxx.
View newest version in sPHENIX GitHub at line 161 of file EicSmearTask.cxx
References detector, FairTask::FinishTask(), Smear::ParticleMCS::GetPx(), Smear::ParticleMCS::GetPy(), Smear::ParticleMCS::GetPz(), Smear::ParticleMCS::GetStatus(), Smear::ParticleMCS::id, outFile, and smearedTree.
InitStatus EicSmearTask::Init () virtual
Intialisation at begin of run. To be implemented in the derived class. Success If not kSUCCESS, task will be set inactive.
Reimplemented from FairTask.
Definition at line 19 of file EicSmearTask.cxx.
View newest version in sPHENIX GitHub at line 19 of file EicSmearTask.cxx
References Smear::Detector::AddDevice(), erhic::VirtualEventFactory::Branch(), builder, detector, eventbranch, fMCTracks, fPidChargedCand, FairRootManager::GetObject(), inFile, inFileName, FairRootManager::Instance(), kERROR, kFATAL, Smear::kP, Smear::kPhi, kSUCCESS, Smear::kTheta, mcTree, momentum, outFile, phi, Smear::Detector::SetEventKinematicsCalculator(), smearedTree, and theta().
void EicSmearTask::SetParContainers () virtual
Intialise parameter containers. To be implemented in the derived class.
Reimplemented from FairTask.
Definition at line 94 of file EicSmearTask.cxx.
View newest version in sPHENIX GitHub at line 94 of file EicSmearTask.cxx
Member Data Documentation
erhic::VirtualEventFactory* EicSmearTask::builder private
Definition at line 42 of file EicSmearTask.h.
View newest version in sPHENIX GitHub at line 42 of file EicSmearTask.h
Referenced by Exec(), and Init().
Smear::Detector* EicSmearTask::detector private
Definition at line 37 of file EicSmearTask.h.
View newest version in sPHENIX GitHub at line 37 of file EicSmearTask.h
Referenced by FinishTask(), and Init().
TBranch* EicSmearTask::eventbranch private
Definition at line 41 of file EicSmearTask.h.
View newest version in sPHENIX GitHub at line 41 of file EicSmearTask.h
Referenced by Exec(), and Init().
TClonesArray* EicSmearTask::fMCTracks private
Definition at line 44 of file EicSmearTask.h.
View newest version in sPHENIX GitHub at line 44 of file EicSmearTask.h
Referenced by Exec(), and Init().
TClonesArray * EicSmearTask::fPidChargedCand private
Definition at line 44 of file EicSmearTask.h.
View newest version in sPHENIX GitHub at line 44 of file EicSmearTask.h
Referenced by Exec(), and Init().
TFile* EicSmearTask::inFile private
Definition at line 39 of file EicSmearTask.h.
View newest version in sPHENIX GitHub at line 39 of file EicSmearTask.h
Referenced by Init().
TString EicSmearTask::inFileName private
Definition at line 36 of file EicSmearTask.h.
View newest version in sPHENIX GitHub at line 36 of file EicSmearTask.h
Referenced by Init().
TTree* EicSmearTask::mcTree private
Definition at line 40 of file EicSmearTask.h.
View newest version in sPHENIX GitHub at line 40 of file EicSmearTask.h
Referenced by Exec(), and Init().
TFile * EicSmearTask::outFile private
Definition at line 39 of file EicSmearTask.h.
View newest version in sPHENIX GitHub at line 39 of file EicSmearTask.h
Referenced by FinishTask(), and Init().
TTree * EicSmearTask::smearedTree private
Definition at line 40 of file EicSmearTask.h.
View newest version in sPHENIX GitHub at line 40 of file EicSmearTask.h
Referenced by FinishTask(), and Init().
The documentation for this class was generated from the following files:
EicRoot/blob/master/eic/event/EicSmearTask.h
EicRoot/blob/master/eic/event/EicSmearTask.cxx