EIC Software: EICPIDParticlev1 Class Reference
EICPIDParticlev1 Class Reference
#include <fun4all_eicdetectors/blob/master/reconstruction/eicpidbase/EICPIDParticlev1.h>
Classes
union u_property
convert between 32bit inputs and storage type prop_storage_t
Public Member Functions
EICPIDParticlev1 ()=default
EICPIDParticlev1 (const EICPIDParticle *g4hit)
~EICPIDParticlev1 () override=default
void identify (std::ostream &os=std::cout) const override
void Reset () override
Clear Event.
EICPIDDefs::keytype get_id () const override
void set_id (const EICPIDDefs::keytype i) override
float get_SumLogLikelyhood (EICPIDDefs::PIDCandidate pid) const override
float get_LogLikelyhood (EICPIDDefs::PIDCandidate pid, EICPIDDefs::PIDDetector det) const override
void set_LogLikelyhood (EICPIDDefs::PIDCandidate pid, EICPIDDefs::PIDDetector det, float LogLikelyhood) override
bool has_property (const PROPERTY prop_id) const override
float get_property_float (const PROPERTY prop_id) const override
int get_property_int (const PROPERTY prop_id) const override
unsigned int get_property_uint (const PROPERTY prop_id) const override
void set_property (const PROPERTY prop_id, const float value) override
void set_property (const PROPERTY prop_id, const int value) override
void set_property (const PROPERTY prop_id, const unsigned int value) override
Public Member Functions inherited from EICPIDParticle
EICPIDParticle ()
~EICPIDParticle () override
void CopyFrom (const PHObject *phobj) override
Public Member Functions inherited from PHObject
PHObject ()
ctor
~PHObject () override
dtor
virtual PHObject * CloneMe () const
Virtual copy constructor.
virtual PHObject * clone () const final
PHObject * Clone (const char *newname="") const final
void Copy (TObject &object) const final
virtual int isValid () const
isValid returns non zero if object contains vailid data
virtual int isValid (const float) const
virtual int isValid (const double) const
virtual int isValid (const int) const
virtual int isValid (const unsigned int) const
virtual int isImplemented (const float f) const
virtual int isImplemented (const double f) const
virtual int isImplemented (const int i) const
virtual int isImplemented (const unsigned int i) const
virtual int Integrate () const
virtual int Integrate (PHObject *)
Protected Types
typedef uint8_t prop_id_t
storage types for additional property
typedef uint32_t prop_storage_t
typedef std::map< prop_id_t,
prop_storage_t > prop_map_t
typedef std::pair
< EICPIDDefs::PIDCandidate,
EICPIDDefs::PIDDetector > LogLikelyhoodMapKey_t
Protected Member Functions
unsigned int get_property_nocheck (const PROPERTY prop_id) const override
void set_property_nocheck (const PROPERTY prop_id, const unsigned int ui) override
Protected Attributes
EICPIDDefs::keytype m_id = -1
prop_map_t prop_map
container for additional property
std::map
< LogLikelyhoodMapKey_t, float > m_LogLikelyhoodMap
Additional Inherited Members
Public Types inherited from EICPIDParticle
enum PROPERTY_TYPE { type_int = 1, type_uint = 2, type_float = 3, type_unknown = -1 }
enum PROPERTY {
Truth_PID = 0, Truth_momentum, Truth_eta, CTTL_beta = 10,
ETTL_beta, FTTL_beta, prop_MAX_NUMBER = UCHAR_MAX
}
Static Public Member Functions inherited from EICPIDParticle
static std::pair< const
std::string, PROPERTY_TYPE > get_property_info (PROPERTY prop_id)
static bool check_property (const PROPERTY prop_id, const PROPERTY_TYPE prop_type)
static std::string get_property_type (const PROPERTY_TYPE prop_type)
Static Public Attributes inherited from EICPIDParticle
static const std::map
< PROPERTY, std::pair< const
std::string,
EICPIDParticle::PROPERTY_TYPE > > m_propertyInfo
Static Protected Attributes inherited from EICPIDParticle
static constexpr float m_minLogLikelihood = -100
Detailed Description
Definition at line 15 of file EICPIDParticlev1.h.
View newest version in sPHENIX GitHub at line 15 of file EICPIDParticlev1.h
Member Typedef Documentation
typedef std::pair<EICPIDDefs::PIDCandidate, EICPIDDefs::PIDDetector> EICPIDParticlev1::LogLikelyhoodMapKey_t protected
Definition at line 80 of file EICPIDParticlev1.h.
View newest version in sPHENIX GitHub at line 80 of file EICPIDParticlev1.h
typedef uint8_t EICPIDParticlev1::prop_id_t protected
storage types for additional property
Definition at line 46 of file EICPIDParticlev1.h.
View newest version in sPHENIX GitHub at line 46 of file EICPIDParticlev1.h
typedef std::map<prop_id_t, prop_storage_t> EICPIDParticlev1::prop_map_t protected
Definition at line 48 of file EICPIDParticlev1.h.
View newest version in sPHENIX GitHub at line 48 of file EICPIDParticlev1.h
typedef uint32_t EICPIDParticlev1::prop_storage_t protected
Definition at line 47 of file EICPIDParticlev1.h.
View newest version in sPHENIX GitHub at line 47 of file EICPIDParticlev1.h
Constructor & Destructor Documentation
EICPIDParticlev1::EICPIDParticlev1 () default
EICPIDParticlev1::EICPIDParticlev1 (const EICPIDParticle * g4hit) explicit
Definition at line 14 of file EICPIDParticlev1.cc.
View newest version in sPHENIX GitHub at line 14 of file EICPIDParticlev1.cc
EICPIDParticlev1::~EICPIDParticlev1 () override default
Member Function Documentation
EICPIDDefs::keytype EICPIDParticlev1::get_id () const inline override virtual
Reimplemented from EICPIDParticle.
Definition at line 24 of file EICPIDParticlev1.h.
View newest version in sPHENIX GitHub at line 24 of file EICPIDParticlev1.h
References m_id.
float EICPIDParticlev1::get_LogLikelyhood (EICPIDDefs::PIDCandidate pid, EICPIDDefs::PIDDetector det) const override virtual
Reimplemented from EICPIDParticle.
Definition at line 76 of file EICPIDParticlev1.cc.
View newest version in sPHENIX GitHub at line 76 of file EICPIDParticlev1.cc
References EICPIDDefs::PIDAll.
float EICPIDParticlev1::get_property_float (const PROPERTY prop_id) const override virtual
Reimplemented from EICPIDParticle.
Definition at line 102 of file EICPIDParticlev1.cc.
View newest version in sPHENIX GitHub at line 102 of file EICPIDParticlev1.cc
References exit(), EICPIDParticlev1::u_property::fdata, and PHWHERE.
int EICPIDParticlev1::get_property_int (const PROPERTY prop_id) const override virtual
Reimplemented from EICPIDParticle.
Definition at line 119 of file EICPIDParticlev1.cc.
View newest version in sPHENIX GitHub at line 119 of file EICPIDParticlev1.cc
References exit(), EICPIDParticlev1::u_property::idata, and PHWHERE.
unsigned int EICPIDParticlev1::get_property_nocheck (const PROPERTY prop_id) const override protected virtual
Reimplemented from EICPIDParticle.
Definition at line 194 of file EICPIDParticlev1.cc.
View newest version in sPHENIX GitHub at line 194 of file EICPIDParticlev1.cc
unsigned int EICPIDParticlev1::get_property_uint (const PROPERTY prop_id) const override virtual
Reimplemented from EICPIDParticle.
Definition at line 137 of file EICPIDParticlev1.cc.
View newest version in sPHENIX GitHub at line 137 of file EICPIDParticlev1.cc
References exit(), PHWHERE, and EICPIDParticlev1::u_property::uidata.
float EICPIDParticlev1::get_SumLogLikelyhood (EICPIDDefs::PIDCandidate pid) const override virtual
Reimplemented from EICPIDParticle.
Definition at line 66 of file EICPIDParticlev1.cc.
View newest version in sPHENIX GitHub at line 66 of file EICPIDParticlev1.cc
bool EICPIDParticlev1::has_property (const PROPERTY prop_id) const override virtual
Reimplemented from EICPIDParticle.
Definition at line 96 of file EICPIDParticlev1.cc.
View newest version in sPHENIX GitHub at line 96 of file EICPIDParticlev1.cc
void EICPIDParticlev1::identify (std::ostream & os = std::cout) const override virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from EICPIDParticle.
Definition at line 26 of file EICPIDParticlev1.cc.
View newest version in sPHENIX GitHub at line 26 of file EICPIDParticlev1.cc
References EICPIDDefs::getPIDDetectorName().
void EICPIDParticlev1::Reset () override virtual
Clear Event.
Reimplemented from EICPIDParticle.
Definition at line 19 of file EICPIDParticlev1.cc.
View newest version in sPHENIX GitHub at line 19 of file EICPIDParticlev1.cc
void EICPIDParticlev1::set_id (const EICPIDDefs::keytype i) inline override virtual
Reimplemented from EICPIDParticle.
Definition at line 25 of file EICPIDParticlev1.h.
View newest version in sPHENIX GitHub at line 25 of file EICPIDParticlev1.h
References m_id.
void EICPIDParticlev1::set_LogLikelyhood (EICPIDDefs::PIDCandidate pid, EICPIDDefs::PIDDetector det, float LogLikelyhood) override virtual
Reimplemented from EICPIDParticle.
Definition at line 89 of file EICPIDParticlev1.cc.
View newest version in sPHENIX GitHub at line 89 of file EICPIDParticlev1.cc
void EICPIDParticlev1::set_property (const PROPERTY prop_id, const float value) override virtual
Reimplemented from EICPIDParticle.
Definition at line 154 of file EICPIDParticlev1.cc.
View newest version in sPHENIX GitHub at line 154 of file EICPIDParticlev1.cc
References exit(), EICPIDParticlev1::u_property::get_storage(), and PHWHERE.
void EICPIDParticlev1::set_property (const PROPERTY prop_id, const int value) override virtual
Reimplemented from EICPIDParticle.
Definition at line 167 of file EICPIDParticlev1.cc.
View newest version in sPHENIX GitHub at line 167 of file EICPIDParticlev1.cc
References exit(), EICPIDParticlev1::u_property::get_storage(), and PHWHERE.
void EICPIDParticlev1::set_property (const PROPERTY prop_id, const unsigned int value) override virtual
Reimplemented from EICPIDParticle.
Definition at line 180 of file EICPIDParticlev1.cc.
View newest version in sPHENIX GitHub at line 180 of file EICPIDParticlev1.cc
References exit(), EICPIDParticlev1::u_property::get_storage(), and PHWHERE.
void EICPIDParticlev1::set_property_nocheck (const PROPERTY prop_id, const unsigned int ui) inline override protected virtual
Reimplemented from EICPIDParticle.
Definition at line 41 of file EICPIDParticlev1.h.
View newest version in sPHENIX GitHub at line 41 of file EICPIDParticlev1.h
References prop_map.
Member Data Documentation
EICPIDDefs::keytype EICPIDParticlev1::m_id = -1 protected
Definition at line 43 of file EICPIDParticlev1.h.
View newest version in sPHENIX GitHub at line 43 of file EICPIDParticlev1.h
Referenced by get_id(), and set_id().
std::map<LogLikelyhoodMapKey_t, float> EICPIDParticlev1::m_LogLikelyhoodMap protected
Definition at line 81 of file EICPIDParticlev1.h.
View newest version in sPHENIX GitHub at line 81 of file EICPIDParticlev1.h
prop_map_t EICPIDParticlev1::prop_map protected
container for additional property
Definition at line 78 of file EICPIDParticlev1.h.
View newest version in sPHENIX GitHub at line 78 of file EICPIDParticlev1.h
Referenced by set_property_nocheck().
The documentation for this class was generated from the following files:
fun4all_eicdetectors/blob/master/reconstruction/eicpidbase/EICPIDParticlev1.h
fun4all_eicdetectors/blob/master/reconstruction/eicpidbase/EICPIDParticlev1.cc