EIC Software: PHG4DetectorSubsystem Class Reference
PHG4DetectorSubsystem Class Reference abstract
#include <fun4all_coresoftware/blob/master/simulation/g4simulation/g4detectors/PHG4DetectorSubsystem.h>
Inherits PHG4Subsystem.
Inherited by AllSi_Al_support_Subsystem, AllSi_Al_support_Subsystem, AllSiliconTrackerSubsystem, AllSiliconTrackerSubsystem, BeamLineMagnetSubsystem, BeastMagnetSubsystem, EicFRichSubsystem, EicFRichSubsystem, EICG4B0ECALSubsystem, EICG4B0Subsystem, EICG4BwdSubsystem, EICG4dRICHSubsystem, EICG4LumiSubsystem, EICG4RPSubsystem, EICG4ZDCSubsystem, EicRootSubsystem, EicToyModelSubsystem, G4EicDircSubsystem, G4Example02Subsystem, G4Example03Subsystem, G4JLeicBeamLineMagnetSubsystem, G4JLeicBeamLineMagnetSubsystem, G4JLeicDIRCSubsystem, G4JLeicDIRCSubsystem, G4LBLVtxSubsystem, G4LBLVtxSubsystem, PHG4BackwardHcalSubsystem, PHG4BarrelEcalSubsystem, PHG4BbcSubsystem, PHG4BeamlineMagnetSubsystem, PHG4BlockSubsystem, PHG4ConeSubsystem, PHG4CrystalCalorimeterSubsystem, PHG4CylinderStripSubsystem, PHG4CylinderSubsystem, PHG4ECAPToFSubsystem, PHG4EPDSubsystem, PHG4ForwardDualReadoutSubsystem, PHG4ForwardEcalSubsystem, PHG4ForwardHcalSubsystem, PHG4GDMLSubsystem, PHG4HybridHomogeneousCalorimeterSubsystem, PHG4InnerHcalSubsystem, PHG4LFHcalSubsystem, PHG4MicromegasSubsystem, PHG4mRICHSubsystem, PHG4OuterHcalSubsystem, PHG4SpacalSubsystem, PHG4TpcEndCapSubsystem, PHG4TpcSubsystem, PHG4TRDSubsystem, PHG4TTLSubsystem, and PHG4ZDCSubsystem.
Public Types
enum FILE_TYPE { none = 0, xml = 1, root = 2 }
Public Member Functions
~PHG4DetectorSubsystem () override
int Init (PHCompositeNode *) final
int InitRun (PHCompositeNode *) final
virtual int InitRunSubsystem (PHCompositeNode *)
virtual int InitSubsystem (PHCompositeNode *)
void OverlapCheck (const bool chk=true)
bool CheckOverlap () const
PHParameters * GetParams () const
void set_double_param (const std::string &name, const double dval)
double get_double_param (const std::string &name) const
void set_int_param (const std::string &name, const int ival)
int get_int_param (const std::string &name) const
void set_string_param (const std::string &name, const std::string &sval)
std::string get_string_param (const std::string &name) const
void UseDB (const int i=1)
int ReadDB () const
FILE_TYPE get_filetype () const
void UseCalibFiles (const FILE_TYPE ftyp)
int SaveParamsToDB ()
int ReadParamsFromDB (const std::string &name, const int issuper)
int SaveParamsToFile (const FILE_TYPE ftyp)
int ReadParamsFromFile (const std::string &name, const FILE_TYPE ftyp, const int issuper)
void SetCalibrationFileDir (const std::string &calibdir)
void UpdateParametersWithMacro ()
void SetActive (const int i=1)
void SetAbsorberActive (const int i=1)
void SetAbsorberTruth (const int i=1)
void BlackHole (const int i=1)
void SetSupportActive (const int i=1)
void SuperDetector (const std::string &name)
const std::string SuperDetector () const
int GetLayer () const
virtual void SetDefaultParameters ()=0
Public Member Functions inherited from PHG4Subsystem
PHG4Subsystem (const std::string &name="Generic Subsystem")
constructor
~PHG4Subsystem (void) override
destructor
virtual int process_after_geant (PHCompositeNode *)
event processing
virtual PHG4Detector * GetDetector (void) const
return pointer to created detector object
virtual PHG4EventAction * GetEventAction (void) const
return pointer to this subsystem event action
virtual PHG4SteppingAction * GetSteppingAction (void) const
return pointer to this subsystem stepping action
virtual PHG4TrackingAction * GetTrackingAction (void) const
return pointer to this subsystem stepping action
virtual PHG4DisplayAction * GetDisplayAction () const
return pointer to this subsystem display setting
virtual PHG4StackingAction * GetStackingAction () const
void OverlapCheck (const bool chk=true)
bool CheckOverlap () const
void SetMotherSubsystem (PHG4Subsystem *subsys)
PHG4Subsystem * GetMotherSubsystem () const
void SetLogicalVolume (G4LogicalVolume *vol)
G4LogicalVolume * GetLogicalVolume () const
virtual bool CanBeMotherSubsystem () const
virtual void AddProcesses (G4ParticleDefinition *)
virtual void DefineMaterials ()
Public Member Functions inherited from SubsysReco
~SubsysReco () override
virtual int End (PHCompositeNode *)
Called at the end of all processing.
virtual int EndRun (const int)
Called at the end of each run.
virtual int process_event (PHCompositeNode *)
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
void Print (const std::string &="ALL") const override
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Protected Member Functions
PHG4DetectorSubsystem (const std::string &name="GenericSubsystem", const int lyr=0)
void InitializeParameters ()
void set_default_double_param (const std::string &name, const double dval)
void set_default_int_param (const std::string &name, const int ival)
void set_default_string_param (const std::string &name, const std::string &sval)
int BeginRunExecuted () const
Private Attributes
PHParameters * params = nullptr
PHParametersContainer * paramscontainer = nullptr
PHCompositeNode * savetopNode = nullptr
bool overlapcheck = false
int layer = -1
int usedb = 0
int beginrunexecuted = 0
FILE_TYPE filetype = PHG4DetectorSubsystem::none
std::string superdetector = "NONE"
std::string calibfiledir = "./"
std::map< const std::string,
double > dparams
std::map< const std::string, int > iparams
std::map< const std::string,
std::string > cparams
std::map< const std::string,
double > default_double
std::map< const std::string, int > default_int
std::map< const std::string,
std::string > default_string
Detailed Description
Definition at line 15 of file PHG4DetectorSubsystem.h.
View newest version in sPHENIX GitHub at line 15 of file PHG4DetectorSubsystem.h
Member Enumeration Documentation
enum PHG4DetectorSubsystem::FILE_TYPE
Enumerator:
none
xml
root
Definition at line 18 of file PHG4DetectorSubsystem.h.
View newest version in sPHENIX GitHub at line 18 of file PHG4DetectorSubsystem.h
Constructor & Destructor Documentation
PHG4DetectorSubsystem::~PHG4DetectorSubsystem () inline override
Definition at line 25 of file PHG4DetectorSubsystem.h.
View newest version in sPHENIX GitHub at line 25 of file PHG4DetectorSubsystem.h
PHG4DetectorSubsystem::PHG4DetectorSubsystem (const std::string & name = "GenericSubsystem", const int lyr = 0) protected
Definition at line 23 of file PHG4DetectorSubsystem.cc.
View newest version in sPHENIX GitHub at line 23 of file PHG4DetectorSubsystem.cc
References Fun4AllBase::Name(), and nlohmann::to_string().
Member Function Documentation
int PHG4DetectorSubsystem::BeginRunExecuted () const inline protected
Definition at line 79 of file PHG4DetectorSubsystem.h.
View newest version in sPHENIX GitHub at line 79 of file PHG4DetectorSubsystem.h
References beginrunexecuted.
Referenced by PHG4ECAPToFSubsystem::Print(), PHG4TRDSubsystem::Print(), PHG4BarrelEcalSubsystem::Print(), PHG4ForwardHcalSubsystem::Print(), BeamLineMagnetSubsystem::Print(), PHG4BeamlineMagnetSubsystem::Print(), PHG4CylinderSubsystem::Print(), G4JLeicBeamLineMagnetSubsystem::Print(), and PHG4CylinderStripSubsystem::Print().
void PHG4DetectorSubsystem::BlackHole (const int i = 1)
Definition at line 398 of file PHG4DetectorSubsystem.cc.
View newest version in sPHENIX GitHub at line 398 of file PHG4DetectorSubsystem.cc
References iparams.
Referenced by BeamLineDefineMagnets(), BlackHole(), Fun4All_G4_EicDirc(), Fun4All_G4_Example02(), Fun4All_G4_Example03(), Fun4All_G4_FastMom(), Fun4All_G4_FastMom_GEM(), Fun4All_G4_FastMom_GEM_RICH(), Fun4All_G4_Momentum(), Fun4All_G4_Momentum_Projection(), Fun4All_G4_Momentum_Projection_Calorimeters(), Fun4All_G4_Momentum_Projection_Detectors(), hFarFwdDefineMagnets(), PlugDoor(), and wrap_with_cylindrical_blackhole().
bool PHG4DetectorSubsystem::CheckOverlap () const inline
Definition at line 34 of file PHG4DetectorSubsystem.h.
View newest version in sPHENIX GitHub at line 34 of file PHG4DetectorSubsystem.h
References overlapcheck.
Referenced by PHG4ECAPToFSubsystem::InitRunSubsystem(), PHG4TRDSubsystem::InitRunSubsystem(), EicRootSubsystem::InitRunSubsystem(), PHG4EPDSubsystem::InitRunSubsystem(), PHG4InnerHcalSubsystem::InitRunSubsystem(), PHG4ZDCSubsystem::InitRunSubsystem(), PHG4TpcSubsystem::InitRunSubsystem(), G4LBLVtxSubsystem::InitRunSubsystem(), PHG4OuterHcalSubsystem::InitRunSubsystem(), BeamLineMagnetSubsystem::InitRunSubsystem(), PHG4BlockSubsystem::InitRunSubsystem(), PHG4ForwardDualReadoutSubsystem::InitRunSubsystem(), PHG4ConeSubsystem::InitRunSubsystem(), PHG4BackwardHcalSubsystem::InitRunSubsystem(), PHG4BarrelEcalSubsystem::InitRunSubsystem(), PHG4CrystalCalorimeterSubsystem::InitRunSubsystem(), PHG4CylinderSubsystem::InitRunSubsystem(), PHG4ForwardHcalSubsystem::InitRunSubsystem(), PHG4HybridHomogeneousCalorimeterSubsystem::InitRunSubsystem(), PHG4LFHcalSubsystem::InitRunSubsystem(), G4JLeicBeamLineMagnetSubsystem::InitRunSubsystem(), PHG4TTLSubsystem::InitRunSubsystem(), EicToyModelSubsystem::InitRunSubsystem(), EICG4dRICHSubsystem::InitRunSubsystem(), PHG4ForwardEcalSubsystem::InitRunSubsystem(), EICG4LumiSubsystem::InitRunSubsystem(), EICG4B0Subsystem::InitRunSubsystem(), AllSi_Al_support_Subsystem::InitRunSubsystem(), EicFRichSubsystem::InitRunSubsystem(), EICG4B0ECALSubsystem::InitRunSubsystem(), EICG4RPSubsystem::InitRunSubsystem(), EICG4ZDCSubsystem::InitRunSubsystem(), EICG4BwdSubsystem::InitRunSubsystem(), PHG4CylinderStripSubsystem::InitRunSubsystem(), BeastMagnetSubsystem::InitRunSubsystem(), PHG4TpcEndCapSubsystem::InitRunSubsystem(), PHG4MicromegasSubsystem::InitRunSubsystem(), G4Example02Subsystem::InitRunSubsystem(), AllSiliconTrackerSubsystem::InitRunSubsystem(), PHG4mRICHSubsystem::InitRunSubsystem(), G4Example03Subsystem::InitRunSubsystem(), PHG4SpacalSubsystem::InitRunSubsystem(), PHG4GDMLSubsystem::InitRunSubsystem(), G4EicDircSubsystem::InitRunSubsystem(), G4JLeicDIRCSubsystem::InitRunSubsystem(), and PHG4BbcSubsystem::InitRunSubsystem().
double PHG4DetectorSubsystem::get_double_param (const std::string & name) const
Definition at line 161 of file PHG4DetectorSubsystem.cc.
View newest version in sPHENIX GitHub at line 161 of file PHG4DetectorSubsystem.cc
References PHParameters::get_double_param(), and params.
Referenced by HCalInner(), HCalOuter(), PHG4BlockSubsystem::InitRunSubsystem(), PHG4CylinderSubsystem::InitRunSubsystem(), and PHG4ConeSubsystem::Set_eta_range().
FILE_TYPE PHG4DetectorSubsystem::get_filetype () const inline
Definition at line 48 of file PHG4DetectorSubsystem.h.
View newest version in sPHENIX GitHub at line 48 of file PHG4DetectorSubsystem.h
References filetype.
Referenced by InitRun().
int PHG4DetectorSubsystem::get_int_param (const std::string & name) const
Definition at line 181 of file PHG4DetectorSubsystem.cc.
View newest version in sPHENIX GitHub at line 181 of file PHG4DetectorSubsystem.cc
References PHParameters::get_int_param(), and params.
Referenced by PHG4ECAPToFSubsystem::InitRunSubsystem(), PHG4TRDSubsystem::InitRunSubsystem(), PHG4EPDSubsystem::InitRunSubsystem(), EicRootSubsystem::InitRunSubsystem(), PHG4ZDCSubsystem::InitRunSubsystem(), PHG4InnerHcalSubsystem::InitRunSubsystem(), G4LBLVtxSubsystem::InitRunSubsystem(), PHG4OuterHcalSubsystem::InitRunSubsystem(), BeamLineMagnetSubsystem::InitRunSubsystem(), PHG4TpcSubsystem::InitRunSubsystem(), PHG4BlockSubsystem::InitRunSubsystem(), PHG4ConeSubsystem::InitRunSubsystem(), PHG4BackwardHcalSubsystem::InitRunSubsystem(), PHG4BarrelEcalSubsystem::InitRunSubsystem(), PHG4CrystalCalorimeterSubsystem::InitRunSubsystem(), PHG4ForwardHcalSubsystem::InitRunSubsystem(), PHG4HybridHomogeneousCalorimeterSubsystem::InitRunSubsystem(), PHG4LFHcalSubsystem::InitRunSubsystem(), PHG4CylinderSubsystem::InitRunSubsystem(), G4JLeicBeamLineMagnetSubsystem::InitRunSubsystem(), EICG4dRICHSubsystem::InitRunSubsystem(), PHG4ForwardEcalSubsystem::InitRunSubsystem(), PHG4CylinderStripSubsystem::InitRunSubsystem(), EICG4B0ECALSubsystem::InitRunSubsystem(), EICG4BwdSubsystem::InitRunSubsystem(), EICG4LumiSubsystem::InitRunSubsystem(), AllSi_Al_support_Subsystem::InitRunSubsystem(), EicFRichSubsystem::InitRunSubsystem(), EICG4RPSubsystem::InitRunSubsystem(), EICG4B0Subsystem::InitRunSubsystem(), EICG4ZDCSubsystem::InitRunSubsystem(), BeastMagnetSubsystem::InitRunSubsystem(), PHG4TpcEndCapSubsystem::InitRunSubsystem(), PHG4MicromegasSubsystem::InitRunSubsystem(), AllSiliconTrackerSubsystem::InitRunSubsystem(), PHG4mRICHSubsystem::InitRunSubsystem(), G4Example02Subsystem::InitRunSubsystem(), PHG4SpacalSubsystem::InitRunSubsystem(), G4Example03Subsystem::InitRunSubsystem(), G4JLeicDIRCSubsystem::InitRunSubsystem(), G4EicDircSubsystem::InitRunSubsystem(), and PHG4BbcSubsystem::InitRunSubsystem().
string PHG4DetectorSubsystem::get_string_param (const std::string & name) const
Definition at line 202 of file PHG4DetectorSubsystem.cc.
View newest version in sPHENIX GitHub at line 202 of file PHG4DetectorSubsystem.cc
References PHParameters::get_string_param(), and params.
Referenced by PHG4CylinderSubsystem::InitRunSubsystem(), PHG4BackwardHcalSubsystem::SetTowerMappingFile(), PHG4LFHcalSubsystem::SetTowerMappingFile(), PHG4ForwardEcalSubsystem::SetTowerMappingFile(), and PHG4ForwardHcalSubsystem::SetTowerMappingFile().
int PHG4DetectorSubsystem::GetLayer () const inline
Definition at line 68 of file PHG4DetectorSubsystem.h.
View newest version in sPHENIX GitHub at line 68 of file PHG4DetectorSubsystem.h
References layer.
Referenced by PHG4ECAPToFSubsystem::InitRunSubsystem(), PHG4TRDSubsystem::InitRunSubsystem(), PHG4ZDCSubsystem::InitRunSubsystem(), BeamLineMagnetSubsystem::InitRunSubsystem(), PHG4ConeSubsystem::InitRunSubsystem(), PHG4BeamlineMagnetSubsystem::InitRunSubsystem(), PHG4BlockSubsystem::InitRunSubsystem(), PHG4CylinderSubsystem::InitRunSubsystem(), PHG4CrystalCalorimeterSubsystem::InitRunSubsystem(), PHG4HybridHomogeneousCalorimeterSubsystem::InitRunSubsystem(), G4JLeicBeamLineMagnetSubsystem::InitRunSubsystem(), PHG4CylinderStripSubsystem::InitRunSubsystem(), EICG4B0Subsystem::InitRunSubsystem(), EICG4RPSubsystem::InitRunSubsystem(), EICG4B0ECALSubsystem::InitRunSubsystem(), EICG4LumiSubsystem::InitRunSubsystem(), EICG4BwdSubsystem::InitRunSubsystem(), PHG4MicromegasSubsystem::InitRunSubsystem(), PHG4mRICHSubsystem::InitRunSubsystem(), and PHG4SpacalSubsystem::InitRunSubsystem().
PHParameters* PHG4DetectorSubsystem::GetParams () const inline
Definition at line 36 of file PHG4DetectorSubsystem.h.
View newest version in sPHENIX GitHub at line 36 of file PHG4DetectorSubsystem.h
References params.
Referenced by EicRootDetector::ConstructMe(), PHG4ECAPToFSubsystem::InitRunSubsystem(), PHG4TRDSubsystem::InitRunSubsystem(), EicRootSubsystem::InitRunSubsystem(), PHG4EPDSubsystem::InitRunSubsystem(), PHG4InnerHcalSubsystem::InitRunSubsystem(), PHG4ZDCSubsystem::InitRunSubsystem(), BeamLineMagnetSubsystem::InitRunSubsystem(), PHG4OuterHcalSubsystem::InitRunSubsystem(), G4LBLVtxSubsystem::InitRunSubsystem(), PHG4TpcSubsystem::InitRunSubsystem(), PHG4BeamlineMagnetSubsystem::InitRunSubsystem(), PHG4BackwardHcalSubsystem::InitRunSubsystem(), PHG4BarrelEcalSubsystem::InitRunSubsystem(), PHG4CrystalCalorimeterSubsystem::InitRunSubsystem(), PHG4ForwardHcalSubsystem::InitRunSubsystem(), PHG4BlockSubsystem::InitRunSubsystem(), PHG4HybridHomogeneousCalorimeterSubsystem::InitRunSubsystem(), PHG4LFHcalSubsystem::InitRunSubsystem(), PHG4ConeSubsystem::InitRunSubsystem(), PHG4CylinderSubsystem::InitRunSubsystem(), G4JLeicBeamLineMagnetSubsystem::InitRunSubsystem(), PHG4TTLSubsystem::InitRunSubsystem(), EICG4dRICHSubsystem::InitRunSubsystem(), PHG4ForwardEcalSubsystem::InitRunSubsystem(), EicToyModelSubsystem::InitRunSubsystem(), EICG4BwdSubsystem::InitRunSubsystem(), EICG4RPSubsystem::InitRunSubsystem(), AllSi_Al_support_Subsystem::InitRunSubsystem(), EicFRichSubsystem::InitRunSubsystem(), EICG4B0Subsystem::InitRunSubsystem(), EICG4LumiSubsystem::InitRunSubsystem(), EICG4B0ECALSubsystem::InitRunSubsystem(), PHG4CylinderStripSubsystem::InitRunSubsystem(), EICG4ZDCSubsystem::InitRunSubsystem(), BeastMagnetSubsystem::InitRunSubsystem(), PHG4TpcEndCapSubsystem::InitRunSubsystem(), PHG4MicromegasSubsystem::InitRunSubsystem(), AllSiliconTrackerSubsystem::InitRunSubsystem(), G4Example02Subsystem::InitRunSubsystem(), PHG4mRICHSubsystem::InitRunSubsystem(), PHG4GDMLSubsystem::InitRunSubsystem(), PHG4SpacalSubsystem::InitRunSubsystem(), G4Example03Subsystem::InitRunSubsystem(), G4EicDircSubsystem::InitRunSubsystem(), G4JLeicDIRCSubsystem::InitRunSubsystem(), PHG4BbcSubsystem::InitRunSubsystem(), PHG4mRICHSubsystem::InitSubsystem(), PHG4TRDSubsystem::Print(), PHG4ECAPToFSubsystem::Print(), PHG4BarrelEcalSubsystem::Print(), PHG4ForwardHcalSubsystem::Print(), PHG4InnerHcalSubsystem::Print(), PHG4OuterHcalSubsystem::Print(), BeamLineMagnetSubsystem::Print(), G4LBLVtxSubsystem::Print(), PHG4TpcSubsystem::Print(), PHG4CylinderSubsystem::Print(), PHG4BeamlineMagnetSubsystem::Print(), G4JLeicBeamLineMagnetSubsystem::Print(), PHG4CylinderStripSubsystem::Print(), PHG4GDMLSubsystem::Print(), PHG4BbcSubsystem::Print(), and EICG4LumiSubsystem::SetParametersFromFile().
int PHG4DetectorSubsystem::Init (PHCompositeNode *) final virtual
Called during initialization. Typically this is where you can book histograms, and e.g. register them to Fun4AllServer (so they can be output to file using Fun4AllServer::dumpHistos() method).
Reimplemented from SubsysReco.
Definition at line 33 of file PHG4DetectorSubsystem.cc.
View newest version in sPHENIX GitHub at line 33 of file PHG4DetectorSubsystem.cc
References InitSubsystem(), Fun4AllBase::Name(), params, savetopNode, and PHParameters::set_name().
void PHG4DetectorSubsystem::InitializeParameters () protected
Definition at line 269 of file PHG4DetectorSubsystem.cc.
View newest version in sPHENIX GitHub at line 269 of file PHG4DetectorSubsystem.cc
References default_double, default_int, default_string, params, set_default_int_param(), PHParameters::set_double_param(), PHParameters::set_int_param(), PHParameters::set_string_param(), and SetDefaultParameters().
Referenced by AllSi_Al_support_Subsystem::AllSi_Al_support_Subsystem(), AllSiliconTrackerSubsystem::AllSiliconTrackerSubsystem(), BeamLineMagnetSubsystem::BeamLineMagnetSubsystem(), BeastMagnetSubsystem::BeastMagnetSubsystem(), EicFRichSubsystem::EicFRichSubsystem(), EICG4B0ECALSubsystem::EICG4B0ECALSubsystem(), EICG4B0Subsystem::EICG4B0Subsystem(), EICG4BwdSubsystem::EICG4BwdSubsystem(), EICG4dRICHSubsystem::EICG4dRICHSubsystem(), EICG4LumiSubsystem::EICG4LumiSubsystem(), EICG4RPSubsystem::EICG4RPSubsystem(), EICG4ZDCSubsystem::EICG4ZDCSubsystem(), EicRootSubsystem::EicRootSubsystem(), EicToyModelSubsystem::EicToyModelSubsystem(), G4EicDircSubsystem::G4EicDircSubsystem(), G4Example02Subsystem::G4Example02Subsystem(), G4Example03Subsystem::G4Example03Subsystem(), G4JLeicBeamLineMagnetSubsystem::G4JLeicBeamLineMagnetSubsystem(), G4JLeicDIRCSubsystem::G4JLeicDIRCSubsystem(), G4LBLVtxSubsystem::G4LBLVtxSubsystem(), PHG4BackwardHcalSubsystem::PHG4BackwardHcalSubsystem(), PHG4BarrelEcalSubsystem::PHG4BarrelEcalSubsystem(), PHG4BbcSubsystem::PHG4BbcSubsystem(), PHG4BeamlineMagnetSubsystem::PHG4BeamlineMagnetSubsystem(), PHG4BlockSubsystem::PHG4BlockSubsystem(), PHG4ConeSubsystem::PHG4ConeSubsystem(), PHG4CrystalCalorimeterSubsystem::PHG4CrystalCalorimeterSubsystem(), PHG4CylinderStripSubsystem::PHG4CylinderStripSubsystem(), PHG4CylinderSubsystem::PHG4CylinderSubsystem(), PHG4ECAPToFSubsystem::PHG4ECAPToFSubsystem(), PHG4EPDSubsystem::PHG4EPDSubsystem(), PHG4ForwardEcalSubsystem::PHG4ForwardEcalSubsystem(), PHG4ForwardHcalSubsystem::PHG4ForwardHcalSubsystem(), PHG4GDMLSubsystem::PHG4GDMLSubsystem(), PHG4HybridHomogeneousCalorimeterSubsystem::PHG4HybridHomogeneousCalorimeterSubsystem(), PHG4InnerHcalSubsystem::PHG4InnerHcalSubsystem(), PHG4LFHcalSubsystem::PHG4LFHcalSubsystem(), PHG4MicromegasSubsystem::PHG4MicromegasSubsystem(), PHG4mRICHSubsystem::PHG4mRICHSubsystem(), PHG4OuterHcalSubsystem::PHG4OuterHcalSubsystem(), PHG4SpacalSubsystem::PHG4SpacalSubsystem(), PHG4TpcEndCapSubsystem::PHG4TpcEndCapSubsystem(), PHG4TpcSubsystem::PHG4TpcSubsystem(), PHG4TRDSubsystem::PHG4TRDSubsystem(), PHG4TTLSubsystem::PHG4TTLSubsystem(), and PHG4ZDCSubsystem::PHG4ZDCSubsystem().
int PHG4DetectorSubsystem::InitRun (PHCompositeNode *) final virtual
Called for first event when run number is known. Typically this is where you may want to fetch data from database, because you know the run number.
Reimplemented from SubsysReco.
Definition at line 41 of file PHG4DetectorSubsystem.cc.
View newest version in sPHENIX GitHub at line 41 of file PHG4DetectorSubsystem.cc
References PHCompositeNode::addNode(), PHParametersContainer::AddPHParameters(), beginrunexecuted, PHG4Subsystem::DefineMaterials(), PHParameters::FillFrom(), PHNodeIterator::findFirst(), get_filetype(), InitRunSubsystem(), layer, Fun4AllBase::Name(), PHParameters::Name(), none, params, paramscontainer, PdbParameterMapContainer::print(), ReadDB(), ReadParamsFromDB(), ReadParamsFromFile(), PHParameters::SaveToNodeTree(), SuperDetector(), superdetector, PHParameters::UpdateNodeTree(), UpdateParametersWithMacro(), and Fun4AllBase::Verbosity().
virtual int PHG4DetectorSubsystem::InitRunSubsystem (PHCompositeNode *) inline virtual
Reimplemented in PHG4BbcSubsystem, G4EicDircSubsystem, G4JLeicDIRCSubsystem, G4JLeicDIRCSubsystem, PHG4GDMLSubsystem, PHG4SpacalSubsystem, G4Example03Subsystem, AllSiliconTrackerSubsystem, PHG4mRICHSubsystem, G4Example02Subsystem, AllSiliconTrackerSubsystem, PHG4MicromegasSubsystem, PHG4TpcEndCapSubsystem, BeastMagnetSubsystem, EICG4B0Subsystem, EICG4B0ECALSubsystem, PHG4CylinderStripSubsystem, EICG4BwdSubsystem, AllSi_Al_support_Subsystem, EicFRichSubsystem, EICG4LumiSubsystem, EICG4RPSubsystem, EICG4ZDCSubsystem, AllSi_Al_support_Subsystem, EicFRichSubsystem, EicToyModelSubsystem, EICG4dRICHSubsystem, PHG4ForwardEcalSubsystem, G4JLeicBeamLineMagnetSubsystem, PHG4TTLSubsystem, PHG4BeamlineMagnetSubsystem, PHG4BlockSubsystem, PHG4ConeSubsystem, PHG4CylinderSubsystem, PHG4ForwardDualReadoutSubsystem, PHG4BackwardHcalSubsystem, PHG4BarrelEcalSubsystem, PHG4CrystalCalorimeterSubsystem, PHG4ForwardHcalSubsystem, PHG4HybridHomogeneousCalorimeterSubsystem, PHG4LFHcalSubsystem, BeamLineMagnetSubsystem, PHG4OuterHcalSubsystem, PHG4TpcSubsystem, G4LBLVtxSubsystem, G4JLeicBeamLineMagnetSubsystem, G4LBLVtxSubsystem, PHG4InnerHcalSubsystem, PHG4ZDCSubsystem, EicRootSubsystem, PHG4EPDSubsystem, PHG4ECAPToFSubsystem, and PHG4TRDSubsystem.
Definition at line 30 of file PHG4DetectorSubsystem.h.
View newest version in sPHENIX GitHub at line 30 of file PHG4DetectorSubsystem.h
Referenced by InitRun().
virtual int PHG4DetectorSubsystem::InitSubsystem (PHCompositeNode *) inline virtual
Reimplemented in PHG4mRICHSubsystem.
Definition at line 31 of file PHG4DetectorSubsystem.h.
View newest version in sPHENIX GitHub at line 31 of file PHG4DetectorSubsystem.h
Referenced by Init().
void PHG4DetectorSubsystem::OverlapCheck (const bool chk = true) inline
Definition at line 33 of file PHG4DetectorSubsystem.h.
View newest version in sPHENIX GitHub at line 33 of file PHG4DetectorSubsystem.h
References overlapcheck.
Referenced by AllSiliconSetup(), Bbc(), BeamLine(), BeamLineDefineBeamPipe(), BeamLineDefineMagnets(), BECALSetup(), BlackHole(), CEmc(), CEmc_1DProjectiveSpacal(), CEmc_2DProjectiveSpacal(), DIRCSetup(), DRCALOSetup(), EEMCHSetup(), EEMCSetup(), EHCALSetup(), EPD(), FEMCSetup(), FHCALSetup(), HCalInner(), HCalOuter(), hFarFwdDefineDetectorsIP6(), hFarFwdDefineDetectorsIP8(), hFarFwdDefineMagnets(), LFHCALSetup(), Magnet(), make_barrel_layer(), make_barrel_layer_basic(), make_barrel_layer_LYSO_basic(), make_barrel_pixel_layer(), make_forward_station(), mRICHSetup(), Pipe(), Piston(), PlugDoor(), RICHSetup(), TPC(), TPC_Endcaps(), TrackingServiceCone(), TrackingServiceCylinder(), and ZDCSetup().
int PHG4DetectorSubsystem::ReadDB () const inline
Definition at line 47 of file PHG4DetectorSubsystem.h.
View newest version in sPHENIX GitHub at line 47 of file PHG4DetectorSubsystem.h
References usedb.
Referenced by InitRun().
int PHG4DetectorSubsystem::ReadParamsFromDB (const std::string & name, const int issuper)
Definition at line 311 of file PHG4DetectorSubsystem.cc.
View newest version in sPHENIX GitHub at line 311 of file PHG4DetectorSubsystem.cc
References layer, params, and PHParameters::ReadFromDB().
Referenced by InitRun().
int PHG4DetectorSubsystem::ReadParamsFromFile (const std::string & name, const FILE_TYPE ftyp, const int issuper)
Definition at line 360 of file PHG4DetectorSubsystem.cc.
View newest version in sPHENIX GitHub at line 360 of file PHG4DetectorSubsystem.cc
References calibfiledir, exit(), layer, params, PHWHERE, PHParameters::ReadFromFile(), root, and xml.
Referenced by InitRun().
int PHG4DetectorSubsystem::SaveParamsToDB ()
Definition at line 293 of file PHG4DetectorSubsystem.cc.
View newest version in sPHENIX GitHub at line 293 of file PHG4DetectorSubsystem.cc
References params, paramscontainer, PHParametersContainer::WriteToDB(), and PHParameters::WriteToDB().
int PHG4DetectorSubsystem::SaveParamsToFile (const FILE_TYPE ftyp)
Definition at line 329 of file PHG4DetectorSubsystem.cc.
View newest version in sPHENIX GitHub at line 329 of file PHG4DetectorSubsystem.cc
References calibfiledir, exit(), params, paramscontainer, PHWHERE, root, PHParametersContainer::WriteToFile(), PHParameters::WriteToFile(), and xml.
void PHG4DetectorSubsystem::set_default_double_param (const std::string & name, const double dval) protected
Definition at line 224 of file PHG4DetectorSubsystem.cc.
View newest version in sPHENIX GitHub at line 224 of file PHG4DetectorSubsystem.cc
References default_double, exit(), and name.
Referenced by PHG4EPDSubsystem::SetDefaultParameters(), EicToyModelSubsystem::SetDefaultParameters(), PHG4ZDCSubsystem::SetDefaultParameters(), PHG4ECAPToFSubsystem::SetDefaultParameters(), PHG4TRDSubsystem::SetDefaultParameters(), PHG4BeamlineMagnetSubsystem::SetDefaultParameters(), EicRootSubsystem::SetDefaultParameters(), G4LBLVtxSubsystem::SetDefaultParameters(), PHG4InnerHcalSubsystem::SetDefaultParameters(), PHG4TpcSubsystem::SetDefaultParameters(), G4JLeicBeamLineMagnetSubsystem::SetDefaultParameters(), PHG4OuterHcalSubsystem::SetDefaultParameters(), AllSi_Al_support_Subsystem::SetDefaultParameters(), EicFRichSubsystem::SetDefaultParameters(), EICG4ZDCSubsystem::SetDefaultParameters(), PHG4BackwardHcalSubsystem::SetDefaultParameters(), PHG4ForwardDualReadoutSubsystem::SetDefaultParameters(), PHG4BarrelEcalSubsystem::SetDefaultParameters(), BeamLineMagnetSubsystem::SetDefaultParameters(), PHG4mRICHSubsystem::SetDefaultParameters(), EICG4dRICHSubsystem::SetDefaultParameters(), PHG4CrystalCalorimeterSubsystem::SetDefaultParameters(), BeastMagnetSubsystem::SetDefaultParameters(), PHG4ForwardEcalSubsystem::SetDefaultParameters(), PHG4CylinderStripSubsystem::SetDefaultParameters(), G4Example02Subsystem::SetDefaultParameters(), PHG4GDMLSubsystem::SetDefaultParameters(), G4JLeicDIRCSubsystem::SetDefaultParameters(), PHG4LFHcalSubsystem::SetDefaultParameters(), PHG4HybridHomogeneousCalorimeterSubsystem::SetDefaultParameters(), PHG4MicromegasSubsystem::SetDefaultParameters(), PHG4ForwardHcalSubsystem::SetDefaultParameters(), PHG4TpcEndCapSubsystem::SetDefaultParameters(), EICG4B0ECALSubsystem::SetDefaultParameters(), EICG4BwdSubsystem::SetDefaultParameters(), EICG4B0Subsystem::SetDefaultParameters(), EICG4LumiSubsystem::SetDefaultParameters(), PHG4BlockSubsystem::SetDefaultParameters(), EICG4RPSubsystem::SetDefaultParameters(), PHG4SpacalSubsystem::SetDefaultParameters(), AllSiliconTrackerSubsystem::SetDefaultParameters(), G4EicDircSubsystem::SetDefaultParameters(), PHG4CylinderSubsystem::SetDefaultParameters(), G4Example03Subsystem::SetDefaultParameters(), PHG4TTLSubsystem::SetDefaultParameters(), and PHG4ConeSubsystem::SetDefaultParameters().
void PHG4DetectorSubsystem::set_default_int_param (const std::string & name, const int ival) protected
Definition at line 239 of file PHG4DetectorSubsystem.cc.
View newest version in sPHENIX GitHub at line 239 of file PHG4DetectorSubsystem.cc
References default_int, exit(), and name.
Referenced by InitializeParameters(), PHG4ECAPToFSubsystem::SetDefaultParameters(), PHG4TRDSubsystem::SetDefaultParameters(), PHG4BeamlineMagnetSubsystem::SetDefaultParameters(), PHG4InnerHcalSubsystem::SetDefaultParameters(), PHG4OuterHcalSubsystem::SetDefaultParameters(), PHG4mRICHSubsystem::SetDefaultParameters(), PHG4CrystalCalorimeterSubsystem::SetDefaultParameters(), PHG4ForwardEcalSubsystem::SetDefaultParameters(), PHG4CylinderStripSubsystem::SetDefaultParameters(), PHG4TpcEndCapSubsystem::SetDefaultParameters(), PHG4ForwardHcalSubsystem::SetDefaultParameters(), PHG4HybridHomogeneousCalorimeterSubsystem::SetDefaultParameters(), PHG4LFHcalSubsystem::SetDefaultParameters(), PHG4GDMLSubsystem::SetDefaultParameters(), G4JLeicDIRCSubsystem::SetDefaultParameters(), EICG4B0ECALSubsystem::SetDefaultParameters(), EICG4BwdSubsystem::SetDefaultParameters(), EICG4B0Subsystem::SetDefaultParameters(), EICG4LumiSubsystem::SetDefaultParameters(), PHG4BlockSubsystem::SetDefaultParameters(), EICG4RPSubsystem::SetDefaultParameters(), PHG4SpacalSubsystem::SetDefaultParameters(), G4EicDircSubsystem::SetDefaultParameters(), PHG4CylinderSubsystem::SetDefaultParameters(), and PHG4TTLSubsystem::SetDefaultParameters().
void PHG4DetectorSubsystem::set_default_string_param (const std::string & name, const std::string & sval) protected
Definition at line 254 of file PHG4DetectorSubsystem.cc.
View newest version in sPHENIX GitHub at line 254 of file PHG4DetectorSubsystem.cc
References default_string, exit(), and name.
Referenced by EicToyModelSubsystem::SetDefaultParameters(), PHG4TRDSubsystem::SetDefaultParameters(), PHG4ECAPToFSubsystem::SetDefaultParameters(), PHG4BeamlineMagnetSubsystem::SetDefaultParameters(), G4LBLVtxSubsystem::SetDefaultParameters(), EicRootSubsystem::SetDefaultParameters(), PHG4InnerHcalSubsystem::SetDefaultParameters(), PHG4TpcSubsystem::SetDefaultParameters(), G4JLeicBeamLineMagnetSubsystem::SetDefaultParameters(), PHG4OuterHcalSubsystem::SetDefaultParameters(), EicFRichSubsystem::SetDefaultParameters(), PHG4BackwardHcalSubsystem::SetDefaultParameters(), AllSi_Al_support_Subsystem::SetDefaultParameters(), PHG4BarrelEcalSubsystem::SetDefaultParameters(), BeamLineMagnetSubsystem::SetDefaultParameters(), EICG4dRICHSubsystem::SetDefaultParameters(), PHG4CrystalCalorimeterSubsystem::SetDefaultParameters(), BeastMagnetSubsystem::SetDefaultParameters(), PHG4ForwardEcalSubsystem::SetDefaultParameters(), G4Example02Subsystem::SetDefaultParameters(), PHG4CylinderStripSubsystem::SetDefaultParameters(), PHG4LFHcalSubsystem::SetDefaultParameters(), PHG4ForwardHcalSubsystem::SetDefaultParameters(), PHG4HybridHomogeneousCalorimeterSubsystem::SetDefaultParameters(), PHG4TpcEndCapSubsystem::SetDefaultParameters(), PHG4GDMLSubsystem::SetDefaultParameters(), EICG4BwdSubsystem::SetDefaultParameters(), EICG4B0Subsystem::SetDefaultParameters(), EICG4B0ECALSubsystem::SetDefaultParameters(), EICG4LumiSubsystem::SetDefaultParameters(), PHG4BlockSubsystem::SetDefaultParameters(), EICG4RPSubsystem::SetDefaultParameters(), PHG4SpacalSubsystem::SetDefaultParameters(), AllSiliconTrackerSubsystem::SetDefaultParameters(), G4EicDircSubsystem::SetDefaultParameters(), PHG4CylinderSubsystem::SetDefaultParameters(), G4Example03Subsystem::SetDefaultParameters(), and PHG4ConeSubsystem::SetDefaultParameters().
void PHG4DetectorSubsystem::set_double_param (const std::string & name, const double dval)
Definition at line 145 of file PHG4DetectorSubsystem.cc.
View newest version in sPHENIX GitHub at line 145 of file PHG4DetectorSubsystem.cc
References default_double, dparams, and name.
Referenced by addPassiveMaterial(), Barrel_Hcal(), BeamLine(), BeamLineDefineBeamPipe(), BeamLineDefineMagnets(), BlackHole(), CEmc(), CEmc_1DProjectiveSpacal(), CEmc_2DProjectiveSpacal(), CEmcAlbedo(), CTD(), DIRCSetup(), DRich(), EndCap_Electron(), EndCap_Hadron(), Fun4All_G4_block(), Fun4All_G4_Cylinder(), Fun4All_G4_EicDirc(), Fun4All_G4_Example02(), Fun4All_G4_Example03(), Fun4All_G4_FastMom(), Fun4All_G4_FastMom_GEM(), Fun4All_G4_FastMom_GEM_RICH(), Fun4All_G4_IonGun(), Fun4All_G4_Magnet(), Fun4All_G4_Momentum(), Fun4All_G4_Momentum_Projection(), Fun4All_G4_Momentum_Projection_Calorimeters(), Fun4All_G4_Momentum_Projection_Detectors(), Fun4All_G4_simple_hadron(), Fun4All_G4_simple_hadron_GEM(), Fun4All_G4_simple_vertex(), Fun4All_G4_simplified_3vtx(), Fun4All_G4_simplified_v2(), Fun4All_G4_simplified_v2_DIRC_barrel_GEM(), Gem(), HCalInner(), HCalInner_SupportRing(), hFarFwdDefineBeamPipe(), hFarFwdDefineDetectorsIP6(), hFarFwdDefineDetectorsIP8(), hFarFwdDefineMagnets(), Magnet(), make_barrel_layer(), make_barrel_layer_basic(), make_barrel_layer_LYSO_basic(), make_barrel_pixel_layer(), make_forward_station(), make_GEM_barrel_section(), Pipe(), Piston(), PlugDoor(), PHG4ConeSubsystem::Set_eta_range(), PHG4InnerHcalSubsystem::SetLightCorrection(), PHG4OuterHcalSubsystem::SetLightCorrection(), EICG4RPSubsystem::SetParametersFromFile(), EICG4LumiSubsystem::SetParametersFromFile(), PHG4ConeSubsystem::SetPhi(), PHG4ConeSubsystem::SetPlace(), PHG4ConeSubsystem::SetPlaceZ(), PHG4ConeSubsystem::SetR1(), PHG4ConeSubsystem::SetR2(), PHG4ConeSubsystem::SetZlength(), PHG4ConeSubsystem::SetZRot(), TPC(), TrackingServiceCylinder(), wrap_with_cylindrical_blackhole(), and ZDCSetup().
void PHG4DetectorSubsystem::set_int_param (const std::string & name, const int ival)
Definition at line 166 of file PHG4DetectorSubsystem.cc.
View newest version in sPHENIX GitHub at line 166 of file PHG4DetectorSubsystem.cc
References default_int, iparams, and name.
Referenced by CEmc(), CEmc_2DProjectiveSpacal(), Fun4All_G4_IonGun(), Fun4All_G4_Magnet(), Fun4All_G4_simple_vertex(), Fun4All_G4_simplified_3vtx(), Fun4All_G4_simplified_v2(), Fun4All_G4_simplified_v2_DIRC_barrel_GEM(), Gem(), HCalInner(), HCalInner_SupportRing(), Magnet(), make_barrel_layer(), make_forward_station(), mRICHSetup(), Pipe(), PHG4LFHcalSubsystem::SetLayerPerTowerSegment(), EICG4LumiSubsystem::SetParametersFromFile(), PHG4CrystalCalorimeterSubsystem::SetProjectiveGeometry(), PHG4HybridHomogeneousCalorimeterSubsystem::SetProjectiveGeometry(), PHG4ForwardHcalSubsystem::SetUseFeTungstenAbsorber(), PHG4BarrelEcalSubsystem::SetUseFeTungstenAbsorber(), and TPC().
void PHG4DetectorSubsystem::set_string_param (const std::string & name, const std::string & sval)
Definition at line 186 of file PHG4DetectorSubsystem.cc.
View newest version in sPHENIX GitHub at line 186 of file PHG4DetectorSubsystem.cc
References cparams, default_string, and name.
Referenced by addPassiveMaterial(), AllSiliconSetup(), Barrel_Hcal(), BeamLine(), BeamLineDefineBeamPipe(), BeamLineDefineMagnets(), BECALSetup(), CEmc(), CEmc_1DProjectiveSpacal(), CEmc_2DProjectiveSpacal(), CEmcAlbedo(), CTD(), DIRCSetup(), DRich(), EEMCHSetup(), EEMCSetup(), EndCap_Electron(), EndCap_Hadron(), Fun4All_G4_block(), Fun4All_G4_Cylinder(), Fun4All_G4_Example02(), Fun4All_G4_Example03(), Fun4All_G4_FastMom(), Fun4All_G4_FastMom_GEM(), Fun4All_G4_FastMom_GEM_RICH(), Fun4All_G4_IonGun(), Fun4All_G4_Magnet(), Fun4All_G4_Momentum(), Fun4All_G4_Momentum_Projection(), Fun4All_G4_Momentum_Projection_Calorimeters(), Fun4All_G4_Momentum_Projection_Detectors(), Fun4All_G4_simple_hadron(), Fun4All_G4_simple_hadron_GEM(), Fun4All_G4_simple_vertex(), Fun4All_G4_simplified_3vtx(), Fun4All_G4_simplified_v2(), Fun4All_G4_simplified_v2_DIRC_barrel_GEM(), Gem(), HCalInner(), HCalInner_SupportRing(), hFarFwdDefineBeamPipe(), hFarFwdDefineMagnets(), EICG4dRICHSubsystem::InitRunSubsystem(), load_AllSi_geom(), Magnet(), make_barrel_layer_basic(), make_barrel_layer_LYSO_basic(), make_barrel_pixel_layer(), make_GEM_barrel_section(), Pipe(), Piston(), PlugDoor(), RICHSetup(), PHG4ConeSubsystem::SetMaterial(), EICG4RPSubsystem::SetParametersFromFile(), EICG4LumiSubsystem::SetParametersFromFile(), PHG4CrystalCalorimeterSubsystem::SetProjectiveGeometry(), PHG4HybridHomogeneousCalorimeterSubsystem::SetProjectiveGeometry(), PHG4HybridHomogeneousCalorimeterSubsystem::SetTowerMappingFile(), PHG4CrystalCalorimeterSubsystem::SetTowerMappingFile(), PHG4BackwardHcalSubsystem::SetTowerMappingFile(), PHG4LFHcalSubsystem::SetTowerMappingFile(), PHG4ForwardHcalSubsystem::SetTowerMappingFile(), PHG4BarrelEcalSubsystem::SetTowerMappingFile(), PHG4ForwardEcalSubsystem::SetTowerMappingFile(), TPC(), TrackingServiceCylinder(), and wrap_with_cylindrical_blackhole().
void PHG4DetectorSubsystem::SetAbsorberActive (const int i = 1)
Definition at line 388 of file PHG4DetectorSubsystem.cc.
View newest version in sPHENIX GitHub at line 388 of file PHG4DetectorSubsystem.cc
References iparams.
Referenced by AllSiliconSetup(), BeamLine(), BeamLineDefineMagnets(), BECALSetup(), CEmc_1DProjectiveSpacal(), CEmc_2DProjectiveSpacal(), EEMCHSetup(), EEMCSetup(), EHCALSetup(), FEMCSetup(), FHCALSetup(), HCalInner(), HCalOuter(), hFarFwdDefineMagnets(), LFHCALSetup(), load_AllSi_geom(), TPC(), and ZDCSetup().
void PHG4DetectorSubsystem::SetAbsorberTruth (const int i = 1)
Definition at line 403 of file PHG4DetectorSubsystem.cc.
View newest version in sPHENIX GitHub at line 403 of file PHG4DetectorSubsystem.cc
References iparams.
void PHG4DetectorSubsystem::SetActive (const int i = 1)
Definition at line 383 of file PHG4DetectorSubsystem.cc.
View newest version in sPHENIX GitHub at line 383 of file PHG4DetectorSubsystem.cc
References iparams.
Referenced by AllSiliconSetup(), Barrel_Hcal(), Bbc(), BeamLine(), BeamLineDefineBeamPipe(), BeamLineDefineMagnets(), BECALSetup(), BlackHole(), CEmc(), CEmc_1DProjectiveSpacal(), CEmc_2DProjectiveSpacal(), CEmcAlbedo(), CTD(), DIRCSetup(), DRich(), EEMCHSetup(), EEMCSetup(), EHCALSetup(), EndCap_Electron(), EndCap_Hadron(), EPD(), FEMCSetup(), FHCALSetup(), Fun4All_G4_block(), Fun4All_G4_Cylinder(), Fun4All_G4_EicDirc(), Fun4All_G4_Example02(), Fun4All_G4_Example03(), Fun4All_G4_FastMom(), Fun4All_G4_FastMom_GEM(), Fun4All_G4_FastMom_GEM_RICH(), Fun4All_G4_IonGun(), Fun4All_G4_Magnet(), Fun4All_G4_Momentum(), Fun4All_G4_Momentum_Projection(), Fun4All_G4_Momentum_Projection_Calorimeters(), Fun4All_G4_Momentum_Projection_Detectors(), Fun4All_G4_simple_hadron(), Fun4All_G4_simple_hadron_GEM(), Fun4All_G4_simple_vertex(), Fun4All_G4_simplified_3vtx(), Fun4All_G4_simplified_v2(), Fun4All_G4_simplified_v2_DIRC_barrel_GEM(), Gem(), HCalInner(), HCalInner_SupportRing(), HCalOuter(), hFarFwdDefineBeamPipe(), hFarFwdDefineDetectorsIP6(), hFarFwdDefineDetectorsIP8(), hFarFwdDefineMagnets(), JLDIRC(), LFHCALSetup(), load_AllSi_geom(), Magnet(), make_barrel_layer_basic(), make_barrel_layer_LYSO_basic(), make_barrel_pixel_layer(), make_GEM_barrel_section(), Pipe(), Piston(), PlugDoor(), RICHSetup(), TPC(), TPC_Endcaps(), TrackingServiceCone(), TrackingServiceCylinder(), and ZDCSetup().
void PHG4DetectorSubsystem::SetCalibrationFileDir (const std::string & calibdir) inline
Definition at line 55 of file PHG4DetectorSubsystem.h.
View newest version in sPHENIX GitHub at line 55 of file PHG4DetectorSubsystem.h
References calibfiledir.
Referenced by CEmc_2DProjectiveSpacal(), and mRICHSetup().
virtual void PHG4DetectorSubsystem::SetDefaultParameters () pure virtual
Implemented in PHG4ConeSubsystem, PHG4TTLSubsystem, G4Example03Subsystem, PHG4BbcSubsystem, PHG4CylinderSubsystem, G4EicDircSubsystem, AllSiliconTrackerSubsystem, AllSiliconTrackerSubsystem, PHG4SpacalSubsystem, EICG4RPSubsystem, PHG4BlockSubsystem, EICG4LumiSubsystem, EICG4B0Subsystem, EICG4B0ECALSubsystem, EICG4BwdSubsystem, PHG4GDMLSubsystem, PHG4MicromegasSubsystem, PHG4TpcEndCapSubsystem, PHG4ForwardHcalSubsystem, PHG4HybridHomogeneousCalorimeterSubsystem, PHG4LFHcalSubsystem, G4JLeicDIRCSubsystem, G4JLeicDIRCSubsystem, PHG4CylinderStripSubsystem, G4Example02Subsystem, BeastMagnetSubsystem, PHG4ForwardEcalSubsystem, EICG4dRICHSubsystem, PHG4CrystalCalorimeterSubsystem, PHG4mRICHSubsystem, BeamLineMagnetSubsystem, PHG4ForwardDualReadoutSubsystem, PHG4BarrelEcalSubsystem, PHG4BackwardHcalSubsystem, AllSi_Al_support_Subsystem, EicFRichSubsystem, EICG4ZDCSubsystem, AllSi_Al_support_Subsystem, EicFRichSubsystem, PHG4OuterHcalSubsystem, PHG4TpcSubsystem, G4JLeicBeamLineMagnetSubsystem, PHG4InnerHcalSubsystem, EicRootSubsystem, G4LBLVtxSubsystem, G4JLeicBeamLineMagnetSubsystem, G4LBLVtxSubsystem, PHG4BeamlineMagnetSubsystem, PHG4ECAPToFSubsystem, PHG4TRDSubsystem, EicToyModelSubsystem, PHG4ZDCSubsystem, and PHG4EPDSubsystem.
Referenced by InitializeParameters().
void PHG4DetectorSubsystem::SetSupportActive (const int i = 1)
Definition at line 393 of file PHG4DetectorSubsystem.cc.
View newest version in sPHENIX GitHub at line 393 of file PHG4DetectorSubsystem.cc
References iparams.
Referenced by Bbc(), FHCALSetup(), and ZDCSetup().
void PHG4DetectorSubsystem::SuperDetector (const std::string & name)
Definition at line 139 of file PHG4DetectorSubsystem.cc.
View newest version in sPHENIX GitHub at line 139 of file PHG4DetectorSubsystem.cc
References name, and superdetector.
Referenced by addPassiveMaterial(), AllSiliconSetup(), Barrel_Hcal(), Bbc(), BeamLine(), BeamLineDefineBeamPipe(), BeamLineDefineMagnets(), BECALSetup(), BlackHole(), CEmc_1DProjectiveSpacal(), CEmc_2DProjectiveSpacal(), CEmcAlbedo(), CTD(), DIRCSetup(), DRCALOSetup(), DRich(), EEMCHSetup(), EEMCSetup(), EHCALSetup(), EndCap_Electron(), EndCap_Hadron(), EPD(), FEMCSetup(), FHCALSetup(), Fun4All_G4_Cylinder(), Fun4All_G4_FastMom(), Fun4All_G4_FastMom_GEM(), Fun4All_G4_FastMom_GEM_RICH(), Fun4All_G4_IonGun(), Fun4All_G4_Magnet(), Fun4All_G4_Momentum(), Fun4All_G4_Momentum_Projection(), Fun4All_G4_Momentum_Projection_Calorimeters(), Fun4All_G4_Momentum_Projection_Detectors(), Fun4All_G4_simple_hadron(), Fun4All_G4_simple_hadron_GEM(), Fun4All_G4_simple_vertex(), Fun4All_G4_simplified_3vtx(), Fun4All_G4_simplified_v2(), Fun4All_G4_simplified_v2_DIRC_barrel_GEM(), Gem(), HCalInner(), HCalInner_SupportRing(), HCalOuter(), hFarFwdDefineMagnets(), JLDIRC(), LFHCALSetup(), load_AllSi_geom(), Magnet(), make_barrel_layer_basic(), make_barrel_layer_LYSO_basic(), make_barrel_pixel_layer(), make_GEM_barrel_section(), Pipe(), Piston(), PlugDoor(), RICHSetup(), TPC(), TPC_Endcaps(), TrackingServiceCone(), TrackingServiceCylinder(), wrap_with_cylindrical_blackhole(), and ZDCSetup().
const std::string PHG4DetectorSubsystem::SuperDetector () const inline
Definition at line 66 of file PHG4DetectorSubsystem.h.
View newest version in sPHENIX GitHub at line 66 of file PHG4DetectorSubsystem.h
References superdetector.
Referenced by EicRootSubsystem::EicRootSubsystem(), G4JLeicDIRCSubsystem::G4JLeicDIRCSubsystem(), InitRun(), PHG4ECAPToFSubsystem::InitRunSubsystem(), PHG4TRDSubsystem::InitRunSubsystem(), EicRootSubsystem::InitRunSubsystem(), PHG4EPDSubsystem::InitRunSubsystem(), PHG4InnerHcalSubsystem::InitRunSubsystem(), PHG4ZDCSubsystem::InitRunSubsystem(), BeamLineMagnetSubsystem::InitRunSubsystem(), PHG4TpcSubsystem::InitRunSubsystem(), G4LBLVtxSubsystem::InitRunSubsystem(), PHG4OuterHcalSubsystem::InitRunSubsystem(), PHG4LFHcalSubsystem::InitRunSubsystem(), PHG4CylinderSubsystem::InitRunSubsystem(), PHG4BlockSubsystem::InitRunSubsystem(), PHG4CrystalCalorimeterSubsystem::InitRunSubsystem(), PHG4ForwardDualReadoutSubsystem::InitRunSubsystem(), PHG4BackwardHcalSubsystem::InitRunSubsystem(), PHG4BarrelEcalSubsystem::InitRunSubsystem(), PHG4ConeSubsystem::InitRunSubsystem(), PHG4ForwardHcalSubsystem::InitRunSubsystem(), PHG4HybridHomogeneousCalorimeterSubsystem::InitRunSubsystem(), G4JLeicBeamLineMagnetSubsystem::InitRunSubsystem(), PHG4ForwardEcalSubsystem::InitRunSubsystem(), EicToyModelSubsystem::InitRunSubsystem(), EICG4LumiSubsystem::InitRunSubsystem(), EICG4RPSubsystem::InitRunSubsystem(), EICG4B0ECALSubsystem::InitRunSubsystem(), EICG4B0Subsystem::InitRunSubsystem(), PHG4CylinderStripSubsystem::InitRunSubsystem(), EICG4BwdSubsystem::InitRunSubsystem(), BeastMagnetSubsystem::InitRunSubsystem(), PHG4MicromegasSubsystem::InitRunSubsystem(), PHG4TpcEndCapSubsystem::InitRunSubsystem(), PHG4mRICHSubsystem::InitRunSubsystem(), AllSiliconTrackerSubsystem::InitRunSubsystem(), PHG4SpacalSubsystem::InitRunSubsystem(), G4JLeicDIRCSubsystem::InitRunSubsystem(), G4EicDircSubsystem::InitRunSubsystem(), PHG4BbcSubsystem::InitRunSubsystem(), and PHG4MicromegasSubsystem::PHG4MicromegasSubsystem().
void PHG4DetectorSubsystem::UpdateParametersWithMacro ()
Definition at line 207 of file PHG4DetectorSubsystem.cc.
View newest version in sPHENIX GitHub at line 207 of file PHG4DetectorSubsystem.cc
References cparams, dparams, iparams, params, PHParameters::set_double_param(), PHParameters::set_int_param(), and PHParameters::set_string_param().
Referenced by InitRun(), and EICG4dRICHSubsystem::InitRunSubsystem().
void PHG4DetectorSubsystem::UseCalibFiles (const FILE_TYPE ftyp) inline
Definition at line 50 of file PHG4DetectorSubsystem.h.
View newest version in sPHENIX GitHub at line 50 of file PHG4DetectorSubsystem.h
References filetype.
Referenced by CEmc_2DProjectiveSpacal(), and mRICHSetup().
void PHG4DetectorSubsystem::UseDB (const int i = 1) inline
Definition at line 46 of file PHG4DetectorSubsystem.h.
View newest version in sPHENIX GitHub at line 46 of file PHG4DetectorSubsystem.h
References usedb.
Member Data Documentation
int PHG4DetectorSubsystem::beginrunexecuted = 0 private
Definition at line 88 of file PHG4DetectorSubsystem.h.
View newest version in sPHENIX GitHub at line 88 of file PHG4DetectorSubsystem.h
Referenced by BeginRunExecuted(), and InitRun().
std::string PHG4DetectorSubsystem::calibfiledir = "./" private
Definition at line 91 of file PHG4DetectorSubsystem.h.
View newest version in sPHENIX GitHub at line 91 of file PHG4DetectorSubsystem.h
Referenced by ReadParamsFromFile(), SaveParamsToFile(), and SetCalibrationFileDir().
std::map<const std::string, std::string> PHG4DetectorSubsystem::cparams private
Definition at line 95 of file PHG4DetectorSubsystem.h.
View newest version in sPHENIX GitHub at line 95 of file PHG4DetectorSubsystem.h
Referenced by set_string_param(), and UpdateParametersWithMacro().
std::map<const std::string, double> PHG4DetectorSubsystem::default_double private
Definition at line 97 of file PHG4DetectorSubsystem.h.
View newest version in sPHENIX GitHub at line 97 of file PHG4DetectorSubsystem.h
Referenced by InitializeParameters(), set_default_double_param(), and set_double_param().
std::map<const std::string, int> PHG4DetectorSubsystem::default_int private
Definition at line 98 of file PHG4DetectorSubsystem.h.
View newest version in sPHENIX GitHub at line 98 of file PHG4DetectorSubsystem.h
Referenced by InitializeParameters(), set_default_int_param(), and set_int_param().
std::map<const std::string, std::string> PHG4DetectorSubsystem::default_string private
Definition at line 99 of file PHG4DetectorSubsystem.h.
View newest version in sPHENIX GitHub at line 99 of file PHG4DetectorSubsystem.h
Referenced by InitializeParameters(), set_default_string_param(), and set_string_param().
std::map<const std::string, double> PHG4DetectorSubsystem::dparams private
Definition at line 93 of file PHG4DetectorSubsystem.h.
View newest version in sPHENIX GitHub at line 93 of file PHG4DetectorSubsystem.h
Referenced by set_double_param(), and UpdateParametersWithMacro().
FILE_TYPE PHG4DetectorSubsystem::filetype = PHG4DetectorSubsystem::none private
Definition at line 89 of file PHG4DetectorSubsystem.h.
View newest version in sPHENIX GitHub at line 89 of file PHG4DetectorSubsystem.h
Referenced by get_filetype(), and UseCalibFiles().
std::map<const std::string, int> PHG4DetectorSubsystem::iparams private
Definition at line 94 of file PHG4DetectorSubsystem.h.
View newest version in sPHENIX GitHub at line 94 of file PHG4DetectorSubsystem.h
Referenced by BlackHole(), set_int_param(), SetAbsorberActive(), SetAbsorberTruth(), SetActive(), SetSupportActive(), and UpdateParametersWithMacro().
int PHG4DetectorSubsystem::layer = -1 private
Definition at line 86 of file PHG4DetectorSubsystem.h.
View newest version in sPHENIX GitHub at line 86 of file PHG4DetectorSubsystem.h
Referenced by GetLayer(), InitRun(), ReadParamsFromDB(), and ReadParamsFromFile().
bool PHG4DetectorSubsystem::overlapcheck = false private
Definition at line 85 of file PHG4DetectorSubsystem.h.
View newest version in sPHENIX GitHub at line 85 of file PHG4DetectorSubsystem.h
Referenced by CheckOverlap(), and OverlapCheck().
PHParameters* PHG4DetectorSubsystem::params = nullptr private
Definition at line 82 of file PHG4DetectorSubsystem.h.
View newest version in sPHENIX GitHub at line 82 of file PHG4DetectorSubsystem.h
Referenced by get_double_param(), get_int_param(), get_string_param(), GetParams(), Init(), InitializeParameters(), InitRun(), ReadParamsFromDB(), ReadParamsFromFile(), SaveParamsToDB(), SaveParamsToFile(), EICG4LumiSubsystem::SetParametersFromFile(), and UpdateParametersWithMacro().
PHParametersContainer* PHG4DetectorSubsystem::paramscontainer = nullptr private
Definition at line 83 of file PHG4DetectorSubsystem.h.
View newest version in sPHENIX GitHub at line 83 of file PHG4DetectorSubsystem.h
Referenced by InitRun(), SaveParamsToDB(), and SaveParamsToFile().
PHCompositeNode* PHG4DetectorSubsystem::savetopNode = nullptr private
Definition at line 84 of file PHG4DetectorSubsystem.h.
View newest version in sPHENIX GitHub at line 84 of file PHG4DetectorSubsystem.h
Referenced by Init().
std::string PHG4DetectorSubsystem::superdetector = "NONE" private
Definition at line 90 of file PHG4DetectorSubsystem.h.
View newest version in sPHENIX GitHub at line 90 of file PHG4DetectorSubsystem.h
Referenced by InitRun(), and SuperDetector().
int PHG4DetectorSubsystem::usedb = 0 private
Definition at line 87 of file PHG4DetectorSubsystem.h.
View newest version in sPHENIX GitHub at line 87 of file PHG4DetectorSubsystem.h
Referenced by ReadDB(), and UseDB().
The documentation for this class was generated from the following files:
fun4all_coresoftware/blob/master/simulation/g4simulation/g4detectors/PHG4DetectorSubsystem.h
fun4all_coresoftware/blob/master/simulation/g4simulation/g4detectors/PHG4DetectorSubsystem.cc