EIC Software: EicRcEvent Class Reference
EicRcEvent Class Reference
#include <EicRoot/blob/master/eic/event/EicRcEvent.h>
Public Member Functions
EicRcEvent ()
virtual ~EicRcEvent ()
virtual void ClearParticles ()
virtual UInt_t GetNTracks () const
virtual const EicRcParticle * GetTrack (UInt_t u) const
virtual EicRcParticle * GetTrack (UInt_t u)
const erhic::EventMC * GetGenMcEvent () const
const erhic::ParticleMC * GetGenMcTrack (int genMcIndex) const
EicRcParticle * GetRcParticleMatchingGenMcTrack (unsigned genMcIndex) const
const erhic::ParticleMC * BeamLepton () const
const erhic::ParticleMC * BeamHadron () const
const erhic::ParticleMC * ExchangeBoson () const
virtual const EicRcParticle * ScatteredLepton () const
void HadronicFinalState (ParticlePtrList &) const
ClassDef (EicRcEvent, 7)
Public Member Functions inherited from erhic::EventDis
virtual ~EventDis ()
EventDis ()
EventDis (const EventDis &)
EventDis & operator= (const EventDis &)
virtual Double_t GetX () const
virtual Double_t GetQ2 () const
virtual Double_t GetY () const
virtual Double_t GetYPlus () const
virtual Double_t GetW2 () const
virtual Double_t GetNu () const
virtual double GetXDoubleAngle () const
virtual double GetQ2DoubleAngle () const
virtual double GetYDoubleAngle () const
virtual double GetW2DoubleAngle () const
virtual double GetXJacquetBlondel () const
virtual double GetQ2JacquetBlondel () const
virtual double GetYJacquetBlondel () const
virtual double GetW2JacquetBlondel () const
virtual void SetLeptonKinematics (const DisKinematics &)
virtual void SetJacquetBlondelKinematics (const DisKinematics &)
virtual void SetDoubleAngleKinematics (const DisKinematics &)
virtual void CopyKinematics (const EventDis &)
Public Member Functions inherited from erhic::VirtualEvent
virtual ~VirtualEvent ()
Private Attributes
Int_t mScatteredLeptonID
std::vector< EicRcParticle * > mParticles
the reconstructed particle list
Friends
class EicEventAssembler
Additional Inherited Members
Public Types inherited from erhic::VirtualEvent
typedef std::vector< const
erhic::VirtualParticle * > ParticlePtrList
Public Attributes inherited from erhic::EventDis
Double32_t x
Bjorken scaling variable.
Double32_t QSquared
Q2 calculated from scattered electron.
Double32_t y
Inelasticity.
Double32_t WSquared
Invariant mass of the hadronic system.
Double32_t nu
Energy transfer from the electron.
Double32_t yJB
y calculated via the Jacquet-Blondel method
Double32_t QSquaredJB
Q2 calculated via the Jacquet-Blondel method.
Double32_t xJB
x calculated via the Jacquet-Blondel method
Double32_t WSquaredJB
W2 calculated via the Jacquet-Blondel method.
Double32_t yDA
y calculated via the double-angle method
Double32_t QSquaredDA
Q2 calculated via the double-angle method.
Double32_t xDA
x calculated via the double-angle method
Double32_t WSquaredDA
W2 calculated via the double-angle method.
Detailed Description
Definition at line 16 of file EicRcEvent.h.
View newest version in sPHENIX GitHub at line 16 of file EicRcEvent.h
Constructor & Destructor Documentation
EicRcEvent::EicRcEvent () inline
Default constructor
Definition at line 22 of file EicRcEvent.h.
View newest version in sPHENIX GitHub at line 22 of file EicRcEvent.h
virtual EicRcEvent::~EicRcEvent () inline virtual
Destructor
Definition at line 25 of file EicRcEvent.h.
View newest version in sPHENIX GitHub at line 25 of file EicRcEvent.h
References ClearParticles().
Member Function Documentation
const erhic::ParticleMC* EicRcEvent::BeamHadron () const inline virtual
Returns a pointer to the incident hadron beam particle. Returns NULL if the particle cannot be located in the event. IMPORTANT - DO NOT DELETE THE POINTER OR BAD THINGS WILL HAPPEN!
Implements erhic::EventDis.
Definition at line 75 of file EicRcEvent.h.
View newest version in sPHENIX GitHub at line 75 of file EicRcEvent.h
References erhic::EventMC::BeamHadron(), and GetGenMcEvent().
const erhic::ParticleMC* EicRcEvent::BeamLepton () const inline virtual
Returns a pointer to the incident lepton beam particle. Returns NULL if the particle cannot be located in the event. IMPORTANT - DO NOT DELETE THE POINTER OR BAD THINGS WILL HAPPEN!
Implements erhic::EventDis.
Definition at line 73 of file EicRcEvent.h.
View newest version in sPHENIX GitHub at line 73 of file EicRcEvent.h
References erhic::EventMC::BeamLepton(), and GetGenMcEvent().
Referenced by EicEventAssembler::AssignScatteredLepton().
EicRcEvent::ClassDef (EicRcEvent , 7)
void EicRcEvent::ClearParticles () virtual
Clears particle array, leaves event variables unchanged
Definition at line 30 of file EicRcEvent.cxx.
View newest version in sPHENIX GitHub at line 30 of file EicRcEvent.cxx
References GetTrack(), mParticles, and particle.
Referenced by ~EicRcEvent().
const erhic::ParticleMC* EicRcEvent::ExchangeBoson () const inline virtual
Returns a pointer to the exchanged boson. Returns NULL if the particle cannot be located in the event. IMPORTANT - DO NOT DELETE THE POINTER OR BAD THINGS WILL HAPPEN!
Implements erhic::EventDis.
Definition at line 76 of file EicRcEvent.h.
View newest version in sPHENIX GitHub at line 76 of file EicRcEvent.h
const erhic::EventMC * EicRcEvent::GetGenMcEvent () const
Definition at line 12 of file EicRcEvent.cxx.
View newest version in sPHENIX GitHub at line 12 of file EicRcEvent.cxx
References EicRootManager::GetGenMcEvent(), and EicRootManager::Instance().
Referenced by analysis(), BeamHadron(), and BeamLepton().
const erhic::ParticleMC * EicRcEvent::GetGenMcTrack (int genMcIndex) const
Definition at line 21 of file EicRcEvent.cxx.
View newest version in sPHENIX GitHub at line 21 of file EicRcEvent.cxx
References EicRootManager::GetGenMcTrack(), and EicRootManager::Instance().
virtual UInt_t EicRcEvent::GetNTracks () const inline virtual
Returns the number of tracks in the event.
Implements erhic::VirtualEvent.
Definition at line 36 of file EicRcEvent.h.
View newest version in sPHENIX GitHub at line 36 of file EicRcEvent.h
References mParticles.
Referenced by analysis(), and HadronicFinalState().
EicRcParticle * EicRcEvent::GetRcParticleMatchingGenMcTrack (unsigned genMcIndex) const
Definition at line 41 of file EicRcEvent.cxx.
View newest version in sPHENIX GitHub at line 41 of file EicRcEvent.cxx
References EicRcParticle::GetGeneratorIndex(), EicRcParticle::GetPndMCTrackIndex(), mParticles, and particle.
virtual const EicRcParticle* EicRcEvent::GetTrack (UInt_t u) const inline virtual
Return the nth track. Return NULL if the track number is out of the range [0, GetNTracks()-1].
Parameters
[in] The track index, in the range [0, GetNTracks()-1].
Implements erhic::VirtualEvent.
Definition at line 43 of file EicRcEvent.h.
View newest version in sPHENIX GitHub at line 43 of file EicRcEvent.h
References mParticles.
Referenced by ClearParticles(), and HadronicFinalState().
virtual EicRcParticle* EicRcEvent::GetTrack (UInt_t) inline virtual
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Implements erhic::VirtualEvent.
Definition at line 46 of file EicRcEvent.h.
View newest version in sPHENIX GitHub at line 46 of file EicRcEvent.h
References mParticles.
void EicRcEvent::HadronicFinalState (ParticlePtrList & final) const virtual
Yields all particles that belong to the hadronic final state. This is the same as the result of FinalState(), minus the scattered beam lepton.
Reimplemented from erhic::VirtualEvent.
Definition at line 62 of file EicRcEvent.cxx.
View newest version in sPHENIX GitHub at line 62 of file EicRcEvent.cxx
References ClassImp(), GetNTracks(), GetTrack(), mScatteredLeptonID, and particle.
virtual const EicRcParticle* EicRcEvent::ScatteredLepton () const inline virtual
Returns a pointer to the lepton beam particle after scattering. Returns NULL if the particle cannot be located in the event. IMPORTANT - DO NOT DELETE THE POINTER OR BAD THINGS WILL HAPPEN!
Implements erhic::EventDis.
Definition at line 78 of file EicRcEvent.h.
View newest version in sPHENIX GitHub at line 78 of file EicRcEvent.h
References mParticles, and mScatteredLeptonID.
Friends And Related Function Documentation
friend class EicEventAssembler friend
Definition at line 17 of file EicRcEvent.h.
View newest version in sPHENIX GitHub at line 17 of file EicRcEvent.h
Member Data Documentation
std::vector<EicRcParticle*> EicRcEvent::mParticles private
the reconstructed particle list
Definition at line 121 of file EicRcEvent.h.
View newest version in sPHENIX GitHub at line 121 of file EicRcEvent.h
Referenced by EicEventAssembler::AssignScatteredLepton(), ClearParticles(), EicEventAssembler::ComposeCalorimeterInformation(), EicEventAssembler::Exec(), GetNTracks(), GetRcParticleMatchingGenMcTrack(), GetTrack(), EicEventAssembler::PerformPidCalculations(), EicEventAssembler::ReAssignMomentumValue(), and ScatteredLepton().
Int_t EicRcEvent::mScatteredLeptonID private
Definition at line 120 of file EicRcEvent.h.
View newest version in sPHENIX GitHub at line 120 of file EicRcEvent.h
Referenced by EicEventAssembler::AssignScatteredLepton(), HadronicFinalState(), and ScatteredLepton().
The documentation for this class was generated from the following files:
EicRoot/blob/master/eic/event/EicRcEvent.h
EicRoot/blob/master/eic/event/EicRcEvent.cxx