EIC Software: EicRoot/blob/master/geometry/TPC/tpc.C File Reference
tpc.C File Reference
Macros
#define _VERSION_ 1
#define _SUBVERSION_ 0
#define _TEST_VERSION_
#define _NO_STRUCTURE_GEOMETRY_
#define _GAS_VOLUME_RADIAL_GAP_ 25.0
Functions
tpc ()
Macro Definition Documentation
#define _GAS_VOLUME_RADIAL_GAP_ 25.0
Definition at line 17 of file tpc.C.
View newest version in sPHENIX GitHub at line 17 of file tpc.C
Referenced by tpc().
#define _NO_STRUCTURE_GEOMETRY_
Definition at line 10 of file tpc.C.
View newest version in sPHENIX GitHub at line 10 of file tpc.C
#define _SUBVERSION_ 0
Definition at line 4 of file tpc.C.
View newest version in sPHENIX GitHub at line 4 of file tpc.C
Referenced by tpc().
#define _TEST_VERSION_
Definition at line 7 of file tpc.C.
View newest version in sPHENIX GitHub at line 7 of file tpc.C
#define _VERSION_ 1
Definition at line 3 of file tpc.C.
View newest version in sPHENIX GitHub at line 3 of file tpc.C
Referenced by tpc().
Function Documentation
tpc ()
Definition at line 21 of file tpc.C.
View newest version in sPHENIX GitHub at line 21 of file tpc.C
References _GAS_VOLUME_RADIAL_GAP_, _SUBVERSION_, _VERSION_, EicGeoMap::AddGeantVolumeLevel(), EicGeoParData::AddLogicalVolumeGroup(), EicNamePatternHub< T >::AddPrefixMatch(), EicGeoParData::AddStepEnforcedVolume(), EicGeoParData::AttachSourceFile(), EicGeoParData::CreateNewMap(), exit(), EicGeoParData::FinalizeOutput(), EicGeoParData::GetColorTable(), EicGeoParData::GetMedium(), EicGeoParData::GetTopVolume(), EicGeoParData::GetTransparencyTable(), TpcGeoParData::mAluBarrelThickness, TpcGeoParData::mAluEndcapThickness, TpcGeoParData::mCentralMembraneThickness, TpcGeoParData::mIfcCarbonFiberThickness, TpcGeoParData::mInnerGasVolumeRadius, TpcGeoParData::mKaptonBarrelThickness, TpcGeoParData::mOfcCarbonFiberThickness, TpcGeoParData::mOuterGasVolumeRadius, TpcGeoParData::mTotalGasVolumeLength, EicGeoParData::NoStructure, rw, EicGeoParData::SetGeometryType(), EicGeoParData::SetMappingTableEntry(), EicGeoMap::SetSingleSensorContainerVolume(), and EicGeoParData::SetTestGeometryFlag().
Referenced by SvtxEvaluator::fillOutputNtuples(), generate_distortion_map(), MakeActsGeometry::makeTGeoNodeMap(), pyreco(), SetupDefaultSphenixTpc(), SetupDigitalCurrentSphenixTpc(), simulation(), TPC(), and tpc_builder().