EIC Software: FW::FakeRatePlotTool Class Reference
FW::FakeRatePlotTool Class Reference
#include <fun4all_acts/blob/master/Examples/Framework/include/ACTFW/Validation/FakeRatePlotTool.hpp>
Classes
struct Config
The nested configuration struct.
struct FakeRatePlotCache
Nested Cache struct.
Public Member Functions
FakeRatePlotTool (const Config &cfg, Acts::Logging::Level lvl)
void book (FakeRatePlotCache &fakeRatePlotCache) const
book the fake rate plots
void fill (FakeRatePlotCache &fakeRatePlotCache, const ActsFatras::Particle &truthParticle, bool status) const
fill fake rate plots
void fill (FakeRatePlotCache &fakeRatePlotCache, const ActsFatras::Particle &truthParticle, size_t nTruthMatchedTracks, size_t nFakeTracks) const
fill number of reco/truth-matched/fake tracks for a single Multi-trajectory
void write (const FakeRatePlotCache &fakeRatePlotCache) const
write the fake rate plots to file
void clear (FakeRatePlotCache &fakeRatePlotCache) const
delete the fake rate plots
Private Member Functions
const Acts::Logger & logger () const
The logger.
Private Attributes
Config m_cfg
The Config class.
std::unique_ptr< const
Acts::Logger > m_logger
The logging instance.
Detailed Description
Definition at line 22 of file FakeRatePlotTool.hpp.
View newest version in sPHENIX GitHub at line 22 of file FakeRatePlotTool.hpp
Constructor & Destructor Documentation
FW::FakeRatePlotTool::FakeRatePlotTool (const Config & cfg, Acts::Logging::Level lvl)
Constructor
Parameters
cfg Configuration struct
lvl Message level declaration
Definition at line 18 of file FakeRatePlotTool.cpp.
View newest version in sPHENIX GitHub at line 18 of file FakeRatePlotTool.cpp
Member Function Documentation
void FW::FakeRatePlotTool::book (FakeRatePlotTool::FakeRatePlotCache & fakeRatePlotCache) const
book the fake rate plots
Parameters
fakeRatePlotCache the cache for fake rate plots
Definition at line 22 of file FakeRatePlotTool.cpp.
View newest version in sPHENIX GitHub at line 22 of file FakeRatePlotTool.cpp
References ACTS_DEBUG, FW::PlotHelpers::bookEff(), FW::PlotHelpers::bookHisto(), FW::PlotHelpers::bookProf(), FW::FakeRatePlotTool::FakeRatePlotCache::duplicationNum_vs_eta, FW::FakeRatePlotTool::FakeRatePlotCache::duplicationNum_vs_phi, FW::FakeRatePlotTool::FakeRatePlotCache::duplicationNum_vs_pT, FW::FakeRatePlotTool::FakeRatePlotCache::fakerate_vs_eta, FW::FakeRatePlotTool::FakeRatePlotCache::fakerate_vs_phi, FW::FakeRatePlotTool::FakeRatePlotCache::fakerate_vs_pT, FW::FakeRatePlotTool::FakeRatePlotCache::nFakeTracks, FW::FakeRatePlotTool::FakeRatePlotCache::nRecoTracks, and FW::FakeRatePlotTool::FakeRatePlotCache::nTruthMatchedTracks.
void FW::FakeRatePlotTool::clear (FakeRatePlotCache & fakeRatePlotCache) const
delete the fake rate plots
Parameters
fakeRatePlotCache cache object for fake rate plots
Definition at line 61 of file FakeRatePlotTool.cpp.
View newest version in sPHENIX GitHub at line 61 of file FakeRatePlotTool.cpp
References FW::FakeRatePlotTool::FakeRatePlotCache::duplicationNum_vs_eta, FW::FakeRatePlotTool::FakeRatePlotCache::duplicationNum_vs_phi, FW::FakeRatePlotTool::FakeRatePlotCache::duplicationNum_vs_pT, FW::FakeRatePlotTool::FakeRatePlotCache::fakerate_vs_eta, FW::FakeRatePlotTool::FakeRatePlotCache::fakerate_vs_phi, FW::FakeRatePlotTool::FakeRatePlotCache::fakerate_vs_pT, FW::FakeRatePlotTool::FakeRatePlotCache::nFakeTracks, FW::FakeRatePlotTool::FakeRatePlotCache::nRecoTracks, and FW::FakeRatePlotTool::FakeRatePlotCache::nTruthMatchedTracks.
void FW::FakeRatePlotTool::fill (FakeRatePlotTool::FakeRatePlotCache & fakeRatePlotCache, const ActsFatras::Particle & truthParticle, bool status) const
fill fake rate plots
Parameters
fakeRatePlotCache cache object for fake rate plots
truthParticle the truth Particle
status the reconstruction status
Definition at line 87 of file FakeRatePlotTool.cpp.
View newest version in sPHENIX GitHub at line 87 of file FakeRatePlotTool.cpp
References Acts::VectorHelpers::eta(), FW::FakeRatePlotTool::FakeRatePlotCache::fakerate_vs_eta, FW::FakeRatePlotTool::FakeRatePlotCache::fakerate_vs_phi, FW::FakeRatePlotTool::FakeRatePlotCache::fakerate_vs_pT, FW::PlotHelpers::fillEff(), phi, ActsFatras::Particle::transverseMomentum(), and ActsFatras::Particle::unitDirection().
void FW::FakeRatePlotTool::fill (FakeRatePlotTool::FakeRatePlotCache & fakeRatePlotCache, const ActsFatras::Particle & truthParticle, size_t nTruthMatchedTracks, size_t nFakeTracks) const
fill number of reco/truth-matched/fake tracks for a single Multi-trajectory
Parameters
fakeRatePlotCache cache object for fake rate plots
truthParticle the truth Particle
nTruthMatchedTracks the number of truth-Matched tracks
nFakeTracks the number of fake tracks
Definition at line 99 of file FakeRatePlotTool.cpp.
View newest version in sPHENIX GitHub at line 99 of file FakeRatePlotTool.cpp
References FW::FakeRatePlotTool::FakeRatePlotCache::duplicationNum_vs_eta, FW::FakeRatePlotTool::FakeRatePlotCache::duplicationNum_vs_phi, FW::FakeRatePlotTool::FakeRatePlotCache::duplicationNum_vs_pT, Acts::VectorHelpers::eta(), FW::PlotHelpers::fillHisto(), FW::PlotHelpers::fillProf(), FW::FakeRatePlotTool::FakeRatePlotCache::nFakeTracks, FW::FakeRatePlotTool::FakeRatePlotCache::nRecoTracks, FW::FakeRatePlotTool::FakeRatePlotCache::nTruthMatchedTracks, phi, ActsFatras::Particle::transverseMomentum(), and ActsFatras::Particle::unitDirection().
const Acts::Logger& FW::FakeRatePlotTool::logger () const inline private
The logger.
Definition at line 89 of file FakeRatePlotTool.hpp.
View newest version in sPHENIX GitHub at line 89 of file FakeRatePlotTool.hpp
References m_logger.
void FW::FakeRatePlotTool::write (const FakeRatePlotCache & fakeRatePlotCache) const
write the fake rate plots to file
Parameters
fakeRatePlotCache cache object for fake rate plots
Definition at line 73 of file FakeRatePlotTool.cpp.
View newest version in sPHENIX GitHub at line 73 of file FakeRatePlotTool.cpp
References ACTS_DEBUG, FW::FakeRatePlotTool::FakeRatePlotCache::duplicationNum_vs_eta, FW::FakeRatePlotTool::FakeRatePlotCache::duplicationNum_vs_phi, FW::FakeRatePlotTool::FakeRatePlotCache::duplicationNum_vs_pT, FW::FakeRatePlotTool::FakeRatePlotCache::fakerate_vs_eta, FW::FakeRatePlotTool::FakeRatePlotCache::fakerate_vs_phi, FW::FakeRatePlotTool::FakeRatePlotCache::fakerate_vs_pT, FW::FakeRatePlotTool::FakeRatePlotCache::nFakeTracks, FW::FakeRatePlotTool::FakeRatePlotCache::nRecoTracks, and FW::FakeRatePlotTool::FakeRatePlotCache::nTruthMatchedTracks.
Member Data Documentation
Config FW::FakeRatePlotTool::m_cfg private
The Config class.
Definition at line 85 of file FakeRatePlotTool.hpp.
View newest version in sPHENIX GitHub at line 85 of file FakeRatePlotTool.hpp
std::unique_ptr<const Acts::Logger> FW::FakeRatePlotTool::m_logger private
The logging instance.
Definition at line 86 of file FakeRatePlotTool.hpp.
View newest version in sPHENIX GitHub at line 86 of file FakeRatePlotTool.hpp
Referenced by logger().
The documentation for this class was generated from the following files:
fun4all_acts/blob/master/Examples/Framework/include/ACTFW/Validation/FakeRatePlotTool.hpp
fun4all_acts/blob/master/Examples/Framework/src/Validation/FakeRatePlotTool.cpp