EIC Software: fun4all_eicmacros/blob/master/detectors/Modular/Fun4All_G4_FullDetectorModular.C File Reference
Fun4All_G4_FullDetectorModular.C File Reference
#include <GlobalVariables.C>
#include <DisplayOn.C>
#include <G4Setup_ModularDetector.C>
#include <G4_Bbc.C>
#include <G4_CaloTrigger.C>
#include <G4_DSTReader_ModularDetector.C>
#include <G4_FwdJets.C>
#include <G4_Global.C>
#include <G4_HIJetReco.C>
#include <G4_Input.C>
#include <G4_Jets.C>
#include <G4_Production.C>
#include <G4_User.C>
#include <QA.C>
#include <TROOT.h>
#include <fun4all/Fun4AllDstOutputManager.h>
#include <fun4all/Fun4AllOutputManager.h>
#include <fun4all/Fun4AllServer.h>
#include <PHPy6GenTrigger.h>
#include <PHPy6ParticleTrigger.h>
#include <PHPy6JetTrigger.h>
#include <phool/recoConsts.h>
#include <eiceval/EventEvaluatorEIC.h>
Macros
#define MACRO_FUN4ALLG4EICDETECTOR_C
Functions
void ParseTString (TString &specialSetting)
int Fun4All_G4_FullDetectorModular (const int nEvents=1, const double particlemomMin=-1, const double particlemomMax=-1, TString specialSetting="ALLSILICON-TTLEM", TString generatorSettings="e10p250MB", const string &inputFile="https://www.phenix.bnl.gov/WWW/publish/phnxbld/sPHENIX/files/sPHENIX_G4Hits_sHijing_9-11fm_00000_00010.root", const string &outputFile="G4EICDetector.root", const string &embed_input_file="https://www.phenix.bnl.gov/WWW/publish/phnxbld/sPHENIX/files/sPHENIX_G4Hits_sHijing_9-11fm_00000_00010.root", const int skip=0, const string &outdir=".")
Macro Definition Documentation
#define MACRO_FUN4ALLG4EICDETECTOR_C
Definition at line 2 of file Fun4All_G4_FullDetectorModular.C.
View newest version in sPHENIX GitHub at line 2 of file Fun4All_G4_FullDetectorModular.C
Function Documentation
int Fun4All_G4_FullDetectorModular (const int nEvents = 1, const double particlemomMin = -1, const double particlemomMax = -1, TString specialSetting = "ALLSILICON-TTLEM", TString generatorSettings = "e10p250MB", const string & inputFile = "https://www.phenix.bnl.gov/WWW/publish/phnxbld/sPHENIX/files/sPHENIX_G4Hits_sHijing_9-11fm_00000_00010.root", const string & outputFile = "G4EICDetector.root", const string & embed_input_file = "https://www.phenix.bnl.gov/WWW/publish/phnxbld/sPHENIX/files/sPHENIX_G4Hits_sHijing_9-11fm_00000_00010.root", const int skip = 0, const string & outdir = ".")
apply EIC beam parameter following EIC CDR
Definition at line 36 of file Fun4All_G4_FullDetectorModular.C.
View newest version in sPHENIX GitHub at line 36 of file Fun4All_G4_FullDetectorModular.C
References Enable::AEROGEL, Enable::ALLSILICON, Enable::ALLSILICON_ABSORBER, Input::ApplyEICBeamParameter(), Enable::BARREL, Enable::BBC, Bbc_Reco(), Enable::BBCFAKE, Enable::BECAL, Enable::BECAL_CELL, Enable::BECAL_CLUSTER, BECAL_Clusters(), Enable::BECAL_EVAL, Enable::BECAL_TOWER, BECAL_Towers(), Enable::BLACKHOLE, Enable::CALOTRIGGER, CaloTrigger_Sim(), Enable::CEMC, Enable::CEMC_CELL, CEMC_Cells(), Enable::CEMC_CLUSTER, CEMC_Clusters(), Enable::CEMC_EVAL, Enable::CEMC_TOWER, CEMC_Towers(), Enable::CTTL, Enable::DIRC, G4TRACKING::DISPLACED_VERTEX, Enable::DISPLAY, DisplayOn(), Enable::DRCALO, Enable::DRCALO_CELL, Enable::DRCALO_CLUSTER, DRCALO_Clusters(), Enable::DRCALO_EVAL, Enable::DRCALO_TOWER, DRCALO_Towers(), Enable::DRCALO_VERBOSITY, DstCompress(), Enable::DSTOUT, Enable::DSTOUT_COMPRESS, Enable::DSTREADER, Enable::EEMC, Enable::EEMC_CELL, EEMC_Cells(), Enable::EEMC_CLUSTER, EEMC_Clusters(), Enable::EEMC_EVAL, Enable::EEMC_TOWER, EEMC_Towers(), Enable::EEMCH, Enable::EEMCH_CELL, EEMCH_Cells(), Enable::EEMCH_CLUSTER, EEMCH_Clusters(), Enable::EEMCH_EVAL, Enable::EEMCH_TOWER, EEMCH_Towers(), Enable::EGEM, Enable::EGEM_FULL, Enable::EHCAL, Enable::EHCAL_CELL, Enable::EHCAL_CLUSTER, EHCAL_Clusters(), Enable::EHCAL_EVAL, Enable::EHCAL_TOWER, EHCAL_Towers(), Enable::EHCAL_VERBOSITY, Fun4AllServer::End(), Enable::ETTL, Enable::ETTL_CLUSTER, ETTL_Clustering(), Enable::FEMC, Enable::FEMC_CELL, Enable::FEMC_CLUSTER, FEMC_Clusters(), Enable::FEMC_EVAL, Enable::FEMC_TOWER, FEMC_Towers(), Enable::FGEM, Enable::FGEM_ORIG, Enable::FHCAL, Enable::FHCAL_CELL, Enable::FHCAL_CLUSTER, FHCAL_Clusters(), Enable::FHCAL_EVAL, Enable::FHCAL_TOWER, FHCAL_Towers(), Enable::FHCAL_VERBOSITY, INPUTHEPMC::filename, Enable::FST, Enable::FTTL, Enable::FTTL_CLUSTER, FTTL_Clustering(), Enable::FWDJETS, Enable::FWDJETS_EVAL, G4DSTreader_EICDetector(), G4Init(), G4Setup(), Enable::GLOBAL_FASTSIM, Global_FastSim(), Enable::GLOBAL_RECO, Global_Reco(), Enable::HCALIN, Enable::HCALIN_CELL, Enable::HCALIN_CLUSTER, Enable::HCALIN_EVAL, Enable::HCALIN_TOWER, HCALInner_Cells(), HCALInner_Clusters(), HCALInner_Towers(), Enable::HCALOUT, Enable::HCALOUT_CELL, Enable::HCALOUT_CLUSTER, Enable::HCALOUT_EVAL, Enable::HCALOUT_TOWER, HCALOuter_Cells(), HCALOuter_Clusters(), HCALOuter_Towers(), Input::HEPMC, Enable::HFARFWD_MAGNETS, Enable::HFARFWD_VIRTUAL_DETECTORS, HIJetReco(), Enable::HIJETS, InputInit(), InputManagers(), InputRegister(), recoConsts::instance(), Fun4AllServer::instance(), Enable::IP6, Jet_FwdReco(), Jet_Reco(), Enable::JETS, Enable::JETS_EVAL, Enable::LFHCAL, Enable::LFHCAL_ABSORBER, Enable::LFHCAL_CELL, Enable::LFHCAL_CLUSTER, LFHCAL_Clusters(), Enable::LFHCAL_EVAL, Enable::LFHCAL_TOWER, LFHCAL_Towers(), M_PI, magfield, G4MAGNET::magfield, G4MAGNET::magfield_rescale, Enable::MAGNET, Enable::mRICH, Enable::MVTX, G4TTL::SETTING::optionCEMC, G4TTL::SETTING::optionDR, DstOut::OutputDir, DstOut::OutputFile, ParseTString(), Enable::PIPE, Enable::PLUGDOOR, pos(), Enable::PRODUCTION, Production_CreateOutputDir(), Production_MoveOutput(), G4TRACKING::PROJECTION_CEMC, G4TRACKING::PROJECTION_DRCALO, G4TRACKING::PROJECTION_EEMC, G4TRACKING::PROJECTION_EHCAL, G4TRACKING::PROJECTION_FEMC, G4TRACKING::PROJECTION_FHCAL, Input::PYTHIA6, INPUTGENERATOR::Pythia6, Enable::QA, QA_Output(), Input::READEIC, Input::READHITS, PHPythia6::register_trigger(), Fun4AllServer::registerOutputManager(), Fun4AllServer::registerSubsystem(), Enable::RICH, Fun4AllServer::run(), PHPythia6::set_config_file(), EventEvaluatorEIC::set_do_BECAL(), EventEvaluatorEIC::set_do_CEMC(), EventEvaluatorEIC::set_do_CLUSTERS(), EventEvaluatorEIC::set_do_DRCALO(), EventEvaluatorEIC::set_do_EEMC(), EventEvaluatorEIC::set_do_EEMCG(), EventEvaluatorEIC::set_do_EHCAL(), EventEvaluatorEIC::set_do_FEMC(), EventEvaluatorEIC::set_do_FHCAL(), EventEvaluatorEIC::set_do_GEOMETRY(), EventEvaluatorEIC::set_do_HCALIN(), EventEvaluatorEIC::set_do_HCALOUT(), EventEvaluatorEIC::set_do_HEPMC(), EventEvaluatorEIC::set_do_HITS(), EventEvaluatorEIC::set_do_LFHCAL(), EventEvaluatorEIC::set_do_MCPARTICLES(), EventEvaluatorEIC::set_do_PROJECTIONS(), EventEvaluatorEIC::set_do_store_event_level_info(), EventEvaluatorEIC::set_do_TRACKS(), EventEvaluatorEIC::set_do_VERTEX(), PHG4ParticleGenerator::set_eta_range(), PHG4ParticleGenerator::set_mom_range(), PHG4ParticleGeneratorBase::set_name(), PHG4ParticleGenerator::set_phi_range(), PHG4ParticleGeneratorBase::set_vtx(), PHPy6JetTrigger::SetEtaHighLow(), PHPy6ParticleTrigger::SetEtaHighLow(), PHPy6JetTrigger::SetJetR(), PHPy6JetTrigger::SetMinJetPt(), PHPy6ParticleTrigger::SetPtLow(), ShowerCompress(), Input::SIMPLE, Input::SIMPLE_VERBOSITY, INPUTGENERATOR::SimpleEventGenerator, Fun4AllServer::skip(), Enable::TPC, Enable::TPC_ENDCAP, Enable::TRACKING, Enable::TRACKING_EVAL, Tracking_Eval(), Enable::TRACKING_EVAL_DETAILED, Enable::TRACKING_INNER, Tracking_Reco(), PHG4SimpleEventGenerator::Uniform, G4PIPE::use_forward_pipes, G4DIRC::SETTING::USECEMCGeo, G4EEMCH::SETTING::USECEMCGeo, G4HCALIN::SETTING::USECEMCGeo, G4EEMCH::SETTING::USEHYBRID, Fun4AllBase::Verbosity(), and Input::VERBOSITY.
void ParseTString (TString & specialSetting)
Definition at line 863 of file Fun4All_G4_FullDetectorModular.C.
View newest version in sPHENIX GitHub at line 863 of file Fun4All_G4_FullDetectorModular.C
References G4FHCAL::SETTING::Absorber_FeTungsten, G4LFHCAL::SETTING::asymmetric, G4FHCAL::SETTING::asymmetric, G4FEMC::SETTING::asymmetric, G4BARREL::SETTING::BARRELV0, G4BARREL::SETTING::BARRELV1, G4BARREL::SETTING::BARRELV2, G4BARREL::SETTING::BARRELV3, G4BARREL::SETTING::BARRELV4, Enable::DRCALO, G4FEMC::SETTING::EC2x, G4FHCAL::SETTING::extradepth, Enable::FEMC, Enable::FHCAL, G4FEMC::SETTING::fsPHENIX, G4FST::SETTING::FST_TPC, G4FST::SETTING::FSTV0, G4FST::SETTING::FSTV1, G4FST::SETTING::FSTV2, G4FST::SETTING::FSTV3, G4FST::SETTING::FSTV4, G4FST::SETTING::FSTV41, G4FST::SETTING::FSTV42, G4FHCAL::SETTING::FullEtaAcc, G4FEMC::SETTING::FullEtaAcc, G4LFHCAL::SETTING::FwdConfig, G4DRCALO::SETTING::FwdConfig, G4LFHCAL::SETTING::FwdSquare, G4DRCALO::SETTING::FwdSquare, G4FHCAL::SETTING::FwdSquare, G4FEMC::SETTING::FwdSquare, G4ALLSILICON::SETTING::geomVersion, G4LFHCAL::SETTING::HC2x, G4FHCAL::SETTING::HC2x, G4FHCAL::SETTING::HC4x, Enable::HFARFWD_MAGNETS, Enable::HFARFWD_VIRTUAL_DETECTORS, Enable::LFHCAL, G4LFHCAL::SETTING::longer, G4DIRC::SETTING::NEWDIRC, G4TTL::SETTING::optionBasicGeo, G4TTL::SETTING::optionCEMC, G4TTL::SETTING::optionDR, G4TTL::SETTING::optionEEMCH, G4TTL::SETTING::optionGeo, G4TTL::SETTING::optionGran, G4TTL::SETTING::optionLYSO, G4DRCALO::SETTING::PMMA, G4DRCALO::SETTING::Quartz, G4FEMC::SETTING::readoutsplit, G4FHCAL::SETTING::towercalib1, G4FHCAL::SETTING::towercalib3, G4FHCAL::SETTING::towercalibHCALIN, G4FHCAL::SETTING::towercalibSiPM, G4DRCALO::SETTING::Tubes, G4DRCALO::SETTING::Tungsten, G4DIRC::SETTING::USECEMCGeo, G4EEMCH::SETTING::USECEMCGeo, G4HCALIN::SETTING::USECEMCGeo, G4EEMCH::SETTING::USEHYBRID, G4DIRC::SETTING::USEskinSupports, G4LFHCAL::SETTING::wDR, G4FHCAL::SETTING::wDR, and G4FEMC::SETTING::wDR.
Referenced by Fun4All_G4_FullDetectorModular(), and Fun4All_G4_FullDetectorModularBeast().