EIC Software: PHG4ForwardDualReadoutSteppingAction Class Reference
PHG4ForwardDualReadoutSteppingAction Class Reference
#include <fun4all_eicdetectors/blob/master/simulation/g4simulation/g4drcalo/PHG4ForwardDualReadoutSteppingAction.h>
Public Member Functions
PHG4ForwardDualReadoutSteppingAction (PHG4ForwardDualReadoutDetector *, const int absorberactive)
constructor
virtual ~PHG4ForwardDualReadoutSteppingAction ()
destructor
virtual bool UserSteppingAction (const G4Step *, bool)
stepping action
virtual void SetInterfacePointers (PHCompositeNode *)
reimplemented from base class
void SetTowerSize (G4double twrsze)
void SetTowerReadout (G4double rdosze)
void SetDetectorSize (G4double detsze)
Public Member Functions inherited from PHG4SteppingAction
PHG4SteppingAction (const std::string &name, const int i=0)
virtual ~PHG4SteppingAction ()
virtual void Verbosity (const int i)
virtual int Verbosity () const
virtual int Init ()
virtual double GetScintLightYield (const G4Step *step)
get scintillation photon count. It require a custom set SCINTILLATIONYIELD property to work
virtual double GetVisibleEnergyDeposition (const G4Step *step)
get amount of energy that can make scintillation light, in Unit of GeV.
virtual void StoreLocalCoordinate (PHG4Hit *hit, const G4Step *step, const bool do_prepoint, const bool do_postpoint)
Extract local coordinate of the hit and save to PHG4Hit.
virtual void Print (const std::string &) const
std::string GetName () const
void SetName (const std::string &name)
virtual void SetLightCorrection (const double inner_radius, const double inner_corr, const double outer_radius, const double outer_corr)
virtual double GetLightCorrection (const double r) const
virtual double GetLightCorrection (const double xpos, const double ypos) const
virtual bool ValidCorrection () const
virtual void SetHitNodeName (const std::string &, const std::string &)
Set the G4HIT node names from Subsystem rather than constructing your own.
Private Member Functions
int FindTowerIndex (G4TouchableHandle touch, int &j, int &k)
int FindTowerIndexFromPosition (G4StepPoint *prePoint, int &j, int &k)
int ParseG4VolumeName (G4VPhysicalVolume *volume, int &j, int &k)
Private Attributes
PHG4ForwardDualReadoutDetector * detector_
pointer to the detector
PHG4HitContainer * hits_
pointer to hit container
PHG4HitContainer * absorberhits_
PHG4HitContainer * hitcontainer
PHG4Hit * hit
PHG4Shower * saveshower
G4double _towerdivision
G4double _tower_size
G4double _readout_size
G4double _detector_size
int absorbertruth
int light_scint_model
Detailed Description
Definition at line 19 of file PHG4ForwardDualReadoutSteppingAction.h.
View newest version in sPHENIX GitHub at line 19 of file PHG4ForwardDualReadoutSteppingAction.h
Constructor & Destructor Documentation
PHG4ForwardDualReadoutSteppingAction::PHG4ForwardDualReadoutSteppingAction (PHG4ForwardDualReadoutDetector * detector, const int absorberactive)
constructor
Definition at line 59 of file PHG4ForwardDualReadoutSteppingAction.cc.
View newest version in sPHENIX GitHub at line 59 of file PHG4ForwardDualReadoutSteppingAction.cc
PHG4ForwardDualReadoutSteppingAction::~PHG4ForwardDualReadoutSteppingAction () virtual
destructor
Definition at line 76 of file PHG4ForwardDualReadoutSteppingAction.cc.
View newest version in sPHENIX GitHub at line 76 of file PHG4ForwardDualReadoutSteppingAction.cc
References hit.
Member Function Documentation
int PHG4ForwardDualReadoutSteppingAction::FindTowerIndex (G4TouchableHandle touch, int & j, int & k) private
Definition at line 485 of file PHG4ForwardDualReadoutSteppingAction.cc.
View newest version in sPHENIX GitHub at line 485 of file PHG4ForwardDualReadoutSteppingAction.cc
References ParseG4VolumeName().
int PHG4ForwardDualReadoutSteppingAction::FindTowerIndexFromPosition (G4StepPoint * prePoint, int & j, int & k) private
Definition at line 464 of file PHG4ForwardDualReadoutSteppingAction.cc.
View newest version in sPHENIX GitHub at line 464 of file PHG4ForwardDualReadoutSteppingAction.cc
References _detector_size, _readout_size, _tower_size, and _towerdivision.
Referenced by UserSteppingAction().
int PHG4ForwardDualReadoutSteppingAction::ParseG4VolumeName (G4VPhysicalVolume * volume, int & j, int & k) private
Definition at line 498 of file PHG4ForwardDualReadoutSteppingAction.cc.
View newest version in sPHENIX GitHub at line 498 of file PHG4ForwardDualReadoutSteppingAction.cc
Referenced by FindTowerIndex().
void PHG4ForwardDualReadoutSteppingAction::SetDetectorSize (G4double detsze) inline
Definition at line 41 of file PHG4ForwardDualReadoutSteppingAction.h.
View newest version in sPHENIX GitHub at line 41 of file PHG4ForwardDualReadoutSteppingAction.h
References _detector_size.
Referenced by PHG4ForwardDualReadoutDetector::ParseParametersFromTable().
void PHG4ForwardDualReadoutSteppingAction::SetInterfacePointers (PHCompositeNode * topNode) virtual
reimplemented from base class
Reimplemented from PHG4SteppingAction.
Definition at line 429 of file PHG4ForwardDualReadoutSteppingAction.cc.
View newest version in sPHENIX GitHub at line 429 of file PHG4ForwardDualReadoutSteppingAction.cc
References absorberhits_, detector_, PHG4Detector::GetName(), hits_, PHG4ForwardDualReadoutDetector::SuperDetector(), and PHG4SteppingAction::Verbosity().
void PHG4ForwardDualReadoutSteppingAction::SetTowerReadout (G4double rdosze) inline
Definition at line 37 of file PHG4ForwardDualReadoutSteppingAction.h.
View newest version in sPHENIX GitHub at line 37 of file PHG4ForwardDualReadoutSteppingAction.h
References _readout_size.
Referenced by PHG4ForwardDualReadoutDetector::ParseParametersFromTable().
void PHG4ForwardDualReadoutSteppingAction::SetTowerSize (G4double twrsze) inline
Definition at line 33 of file PHG4ForwardDualReadoutSteppingAction.h.
View newest version in sPHENIX GitHub at line 33 of file PHG4ForwardDualReadoutSteppingAction.h
References _tower_size.
Referenced by PHG4ForwardDualReadoutDetector::ParseParametersFromTable().
bool PHG4ForwardDualReadoutSteppingAction::UserSteppingAction (const G4Step * aStep, bool) virtual
stepping action
Implements PHG4SteppingAction.
Definition at line 86 of file PHG4ForwardDualReadoutSteppingAction.cc.
View newest version in sPHENIX GitHub at line 86 of file PHG4ForwardDualReadoutSteppingAction.cc
References _detector_size, kdfinder::abs(), absorberhits_, absorbertruth, PHG4Shower::add_g4hit_id(), PHG4HitContainer::AddHit(), Acts::UnitConstants::cm, detector_, FindTowerIndexFromPosition(), PHG4Hit::get_edep(), PHG4Hit::get_eion(), PHG4Hit::get_hit_id(), PHG4ForwardDualReadoutDetector::get_Layer(), PHG4Hit::get_light_yield(), PHG4Hit::get_property_float(), PHG4HitContainer::GetID(), PHG4Detector::GetName(), PHG4SteppingAction::GetVisibleEnergyDeposition(), Acts::UnitConstants::GeV, hit, hitcontainer, hits_, PHG4ForwardDualReadoutDetector::IsActive(), PHG4ForwardDualReadoutDetector::IsBlackHole(), PHG4ForwardDualReadoutDetector::IsInForwardDualReadout(), light_scint_model, p, PHG4Hit::Reset(), saveshower, PHG4Hit::set_edep(), PHG4Hit::set_eion(), PHG4Hit::set_index_j(), PHG4Hit::set_index_k(), PHG4Hit::set_light_yield(), PHG4Hit::set_property(), PHG4Hit::set_shower_id(), PHG4Hit::set_t(), PHG4Hit::set_trkid(), PHG4Hit::set_x(), PHG4Hit::set_y(), PHG4Hit::set_z(), PHG4SteppingAction::Verbosity(), and Acts::Test::volume.
Member Data Documentation
G4double PHG4ForwardDualReadoutSteppingAction::_detector_size private
Definition at line 64 of file PHG4ForwardDualReadoutSteppingAction.h.
View newest version in sPHENIX GitHub at line 64 of file PHG4ForwardDualReadoutSteppingAction.h
Referenced by FindTowerIndexFromPosition(), SetDetectorSize(), and UserSteppingAction().
G4double PHG4ForwardDualReadoutSteppingAction::_readout_size private
Definition at line 63 of file PHG4ForwardDualReadoutSteppingAction.h.
View newest version in sPHENIX GitHub at line 63 of file PHG4ForwardDualReadoutSteppingAction.h
Referenced by FindTowerIndexFromPosition(), and SetTowerReadout().
G4double PHG4ForwardDualReadoutSteppingAction::_tower_size private
Definition at line 62 of file PHG4ForwardDualReadoutSteppingAction.h.
View newest version in sPHENIX GitHub at line 62 of file PHG4ForwardDualReadoutSteppingAction.h
Referenced by FindTowerIndexFromPosition(), and SetTowerSize().
G4double PHG4ForwardDualReadoutSteppingAction::_towerdivision private
Definition at line 61 of file PHG4ForwardDualReadoutSteppingAction.h.
View newest version in sPHENIX GitHub at line 61 of file PHG4ForwardDualReadoutSteppingAction.h
Referenced by FindTowerIndexFromPosition().
PHG4HitContainer* PHG4ForwardDualReadoutSteppingAction::absorberhits_ private
Definition at line 56 of file PHG4ForwardDualReadoutSteppingAction.h.
View newest version in sPHENIX GitHub at line 56 of file PHG4ForwardDualReadoutSteppingAction.h
Referenced by SetInterfacePointers(), and UserSteppingAction().
int PHG4ForwardDualReadoutSteppingAction::absorbertruth private
Definition at line 65 of file PHG4ForwardDualReadoutSteppingAction.h.
View newest version in sPHENIX GitHub at line 65 of file PHG4ForwardDualReadoutSteppingAction.h
Referenced by UserSteppingAction().
PHG4ForwardDualReadoutDetector* PHG4ForwardDualReadoutSteppingAction::detector_ private
pointer to the detector
Definition at line 52 of file PHG4ForwardDualReadoutSteppingAction.h.
View newest version in sPHENIX GitHub at line 52 of file PHG4ForwardDualReadoutSteppingAction.h
Referenced by SetInterfacePointers(), and UserSteppingAction().
PHG4Hit* PHG4ForwardDualReadoutSteppingAction::hit private
Definition at line 58 of file PHG4ForwardDualReadoutSteppingAction.h.
View newest version in sPHENIX GitHub at line 58 of file PHG4ForwardDualReadoutSteppingAction.h
Referenced by UserSteppingAction(), and ~PHG4ForwardDualReadoutSteppingAction().
PHG4HitContainer* PHG4ForwardDualReadoutSteppingAction::hitcontainer private
Definition at line 57 of file PHG4ForwardDualReadoutSteppingAction.h.
View newest version in sPHENIX GitHub at line 57 of file PHG4ForwardDualReadoutSteppingAction.h
Referenced by UserSteppingAction().
PHG4HitContainer* PHG4ForwardDualReadoutSteppingAction::hits_ private
pointer to hit container
Definition at line 55 of file PHG4ForwardDualReadoutSteppingAction.h.
View newest version in sPHENIX GitHub at line 55 of file PHG4ForwardDualReadoutSteppingAction.h
Referenced by SetInterfacePointers(), and UserSteppingAction().
int PHG4ForwardDualReadoutSteppingAction::light_scint_model private
Definition at line 66 of file PHG4ForwardDualReadoutSteppingAction.h.
View newest version in sPHENIX GitHub at line 66 of file PHG4ForwardDualReadoutSteppingAction.h
Referenced by UserSteppingAction().
PHG4Shower* PHG4ForwardDualReadoutSteppingAction::saveshower private
Definition at line 59 of file PHG4ForwardDualReadoutSteppingAction.h.
View newest version in sPHENIX GitHub at line 59 of file PHG4ForwardDualReadoutSteppingAction.h
Referenced by UserSteppingAction().
The documentation for this class was generated from the following files:
fun4all_eicdetectors/blob/master/simulation/g4simulation/g4drcalo/PHG4ForwardDualReadoutSteppingAction.h
fun4all_eicdetectors/blob/master/simulation/g4simulation/g4drcalo/PHG4ForwardDualReadoutSteppingAction.cc