EIC Software: erhic::VirtualParticle Class Reference
erhic::VirtualParticle Class Reference abstract
Abstract base class for a general particle.
#include <eic-smear/blob/master/include/eicsmear/erhic/VirtualParticle.h>
Public Member Functions
virtual ~VirtualParticle ()
virtual Pid Id () const =0
virtual TLorentzVector Get4Vector () const =0
virtual Double_t GetPx () const =0
virtual Double_t GetPy () const =0
virtual Double_t GetPz () const =0
virtual Double_t GetE () const =0
virtual Double_t GetP () const =0
virtual Double_t GetM () const =0
virtual Double_t GetPt () const =0
virtual Double_t GetTheta () const =0
virtual Double_t GetPhi () const =0
virtual Double_t GetRapidity () const =0
virtual Double_t GetEta () const =0
virtual TVector3 GetVertex () const =0
virtual UShort_t GetStatus () const =0
virtual UShort_t GetParentIndex () const =0
virtual void SetVertex (const TVector3 &)=0
virtual void Set4Vector (const TLorentzVector &)=0
Detailed Description
Abstract base class for a general particle.
Definition at line 23 of file VirtualParticle.h.
View newest version in sPHENIX GitHub at line 23 of file VirtualParticle.h
Constructor & Destructor Documentation
virtual erhic::VirtualParticle::~VirtualParticle () inline virtual
Destructor
Definition at line 28 of file VirtualParticle.h.
View newest version in sPHENIX GitHub at line 28 of file VirtualParticle.h
Member Function Documentation
virtual TLorentzVector erhic::VirtualParticle::Get4Vector () const pure virtual
Returns the momentum-energy four-vector (px, py, pz, E).
Implemented in erhic::ParticleMCbase, EicRcParticle, Smear::ParticleMCS, and erhic::hadronic::ParticleMC.
Referenced by erhic::JacquetBlondelComputer::ComputeX(), erhic::DoubleAngleComputer::ComputeX(), and Smear::Tracker::MultipleScatteringContribution().
virtual Double_t erhic::VirtualParticle::GetE () const pure virtual
Returns total energy.
Implemented in erhic::ParticleMCbase, EicRcParticle, erhic::hadronic::ParticleMC, and Smear::ParticleMCS.
Referenced by erhic::DoubleAngleComputer::ComputeQSquared(), erhic::JacquetBlondelComputer::ComputeY(), Smear::Acceptance::Zone::Contains(), Smear::GetVariable(), and EicEventGenerator::ReadEvent().
virtual Double_t erhic::VirtualParticle::GetEta () const pure virtual
Returns the pseudorapidity.
Implemented in erhic::ParticleMCbase, Smear::ParticleMCS, erhic::hadronic::ParticleMC, and EicRcParticle.
Referenced by EPhenixMomentum::computeMultipleScattering(), EicEventGenerator::ReadEvent(), Smear::NumSigmaPid::Smear(), EPhenixMomentum::Smear(), Smear::Device::Smear(), and Smear::Detector::Smear().
virtual Double_t erhic::VirtualParticle::GetM () const pure virtual
Returns invariant mass (GeV/c2).
Implemented in erhic::ParticleMCbase, Smear::ParticleMCS, erhic::hadronic::ParticleMC, and EicRcParticle.
Referenced by erhic::JacquetBlondelComputer::Calculate(), erhic::DoubleAngleComputer::Calculate(), erhic::JacquetBlondelComputer::ComputeY(), and EicEventGenerator::ReadEvent().
virtual Double_t erhic::VirtualParticle::GetP () const pure virtual
Returns the magnitude of 3-momentum (GeV).
Implemented in erhic::ParticleMCbase, Smear::ParticleMCS, erhic::hadronic::ParticleMC, and EicRcParticle.
Referenced by EPhenixMomentum::computeMultipleScattering(), Smear::Acceptance::Zone::Contains(), Smear::GetVariable(), Smear::Tracker::IntrinsicContribution(), Smear::Tracker::MultipleScatteringContribution(), EicEventGenerator::ReadEvent(), Smear::NumSigmaPid::Smear(), EPhenixMomentum::Smear(), and Smear::ParticleID::Smear().
virtual UShort_t erhic::VirtualParticle::GetParentIndex () const pure virtual
Returns the index of the parent particle
Implemented in Smear::ParticleMCS, erhic::hadronic::ParticleMC, EicRcParticle, and erhic::ParticleMCbase.
Referenced by ParticleIdentifier::isBeamLepton(), ParticleIdentifier::isBeamNucleon(), EicEventGenerator::ReadEvent(), and ParticleIdentifier::SkipParticle().
virtual Double_t erhic::VirtualParticle::GetPhi () const pure virtual
Returns the polar angle in the range [0, 2pi] radians.
Implemented in erhic::ParticleMCbase, Smear::ParticleMCS, erhic::hadronic::ParticleMC, and EicRcParticle.
Referenced by Smear::Acceptance::Zone::Contains(), and Smear::GetVariable().
virtual Double_t erhic::VirtualParticle::GetPt () const pure virtual
Returns momentum perpendicular to the beam direction.
Implemented in erhic::ParticleMCbase, Smear::ParticleMCS, erhic::hadronic::ParticleMC, and EicRcParticle.
Referenced by Smear::Acceptance::Zone::Contains(), and Smear::GetVariable().
virtual Double_t erhic::VirtualParticle::GetPx () const pure virtual
Returns the x component of 3-momentum.
Implemented in erhic::ParticleMCbase, erhic::hadronic::ParticleMC, Smear::ParticleMCS, and EicRcParticle.
Referenced by EicEventGenerator::ReadEvent().
virtual Double_t erhic::VirtualParticle::GetPy () const pure virtual
Returns the y component of 3-momentum.
Implemented in erhic::ParticleMCbase, erhic::hadronic::ParticleMC, Smear::ParticleMCS, and EicRcParticle.
Referenced by EicEventGenerator::ReadEvent().
virtual Double_t erhic::VirtualParticle::GetPz () const pure virtual
Returns the z component of 3-momentum.
Implemented in erhic::ParticleMCbase, erhic::hadronic::ParticleMC, Smear::ParticleMCS, and EicRcParticle.
Referenced by erhic::JacquetBlondelComputer::ComputeY(), Smear::Acceptance::Zone::Contains(), Smear::GetVariable(), and EicEventGenerator::ReadEvent().
virtual Double_t erhic::VirtualParticle::GetRapidity () const pure virtual
Returns the rapidity.
Implemented in erhic::ParticleMCbase, Smear::ParticleMCS, erhic::hadronic::ParticleMC, and EicRcParticle.
virtual UShort_t erhic::VirtualParticle::GetStatus () const pure virtual
A general "status" code for the particle (definition depends on implementation).
Implemented in Smear::ParticleMCS, erhic::hadronic::ParticleMC, EicRcParticle, and erhic::ParticleMCbase.
Referenced by Smear::Detector::Accept(), Smear::EventDisFactory::Create(), EicSmearTask::Exec(), ParticleIdentifier::isBeamLepton(), ParticleIdentifier::isBeamNucleon(), ParticleIdentifier::isScatteredLepton(), ParticleIdentifier::IsVirtualPhoton(), Smear::PGenre(), EicEventGenerator::ReadEvent(), and ParticleIdentifier::SkipParticle().
virtual Double_t erhic::VirtualParticle::GetTheta () const pure virtual
Returns the polar angle in the range [0, pi] radians.
Implemented in erhic::ParticleMCbase, Smear::ParticleMCS, erhic::hadronic::ParticleMC, and EicRcParticle.
Referenced by Smear::PlanarTracker::ComputeIntersectionWithPlane(), Smear::RadialTracker::ComputeIntersectionWithPlane(), Smear::RadialTracker::ComputeIntersectionWithRadius(), Smear::PlanarTracker::ComputeIntersectionWithRadius(), erhic::DoubleAngleComputer::ComputeQSquared(), erhic::DoubleAngleComputer::ComputeY(), Smear::Acceptance::Zone::Contains(), Smear::GetVariable(), Smear::PlanarTracker::L(), Smear::PlanarTracker::LPrime(), and Smear::PlanarTracker::NPoints().
virtual TVector3 erhic::VirtualParticle::GetVertex () const pure virtual
Returns the origin point of the particle in cm. (0,0,0) indicates a particle originating in the collision.
Implemented in erhic::ParticleMCbase, erhic::hadronic::ParticleMC, Smear::ParticleMCS, and EicRcParticle.
Referenced by Smear::PlanarTracker::ComputeIntersectionWithPlane(), Smear::RadialTracker::ComputeIntersectionWithPlane(), Smear::RadialTracker::ComputeIntersectionWithRadius(), Smear::PlanarTracker::ComputeIntersectionWithRadius(), and EicEventGenerator::ReadEvent().
virtual Pid erhic::VirtualParticle::Id () const pure virtual
Returns identity information for the Particle species.
Implemented in erhic::ParticleMCbase, Smear::ParticleMCS, EicRcParticle, and erhic::hadronic::ParticleMC.
Referenced by ParticleIdentifier::IdentifyBeams(), Smear::Acceptance::Is(), ParticleIdentifier::isBeamLepton(), ParticleIdentifier::isBeamNucleon(), ParticleIdentifier::isScatteredLepton(), ParticleIdentifier::IsVirtualPhoton(), Smear::PGenre(), EicEventGenerator::ReadEvent(), erhic::EventRapgap::ScatteredLepton(), erhic::EventSimple::ScatteredLepton(), erhic::EventDEMP::ScatteredLepton(), erhic::EventSartre::ScatteredLepton(), erhic::EventPythia::ScatteredLepton(), ParticleIdentifier::SkipParticle(), Smear::PerfectID::Smear(), Smear::Device::Smear(), Smear::Detector::Smear(), and Smear::ParticleID::Smear().
virtual void erhic::VirtualParticle::Set4Vector (const TLorentzVector &) pure virtual
Sets the four-momentum of the particle. Changes are propagated to derived quantities.
Implemented in erhic::ParticleMCbase, Smear::ParticleMCS, erhic::hadronic::ParticleMC, and EicRcParticle.
Referenced by EicSmearTask::Exec().
virtual void erhic::VirtualParticle::SetVertex (const TVector3 &) pure virtual
Sets the origin coordinates
Implemented in erhic::ParticleMCbase, Smear::ParticleMCS, erhic::hadronic::ParticleMC, and EicRcParticle.
The documentation for this class was generated from the following file:
eic-smear/blob/master/include/eicsmear/erhic/VirtualParticle.h