EIC Software: FairVolume Class Reference
FairVolume Class Reference
#include <EicRoot/blob/master/base/FairVolume.h>
Public Member Functions
FairVolume ()
FairVolume (TString name, Int_t id=0, Int_t detid=0, FairModule *fMod=0)
virtual ~FairVolume ()
void setRealName (TString name)
const char * getRealName ()
Int_t getVolumeId ()
Int_t getModId ()
void setModId (Int_t id)
void setCopyNo (Int_t id)
void setVolumeId (Int_t id)
void setGeoNode (FairGeoNode *d)
void setMotherId (Int_t fM)
void setMotherCopyNo (Int_t CopyNo)
FairModule * GetModule ()
void SetModule (FairModule *mod)
Int_t getMCid ()
Int_t getCopyNo ()
void setMCid (Int_t id)
FairGeoNode * getGeoNode ()
Int_t getMotherId ()
Int_t getMotherCopyNo ()
Private Member Functions
FairVolume (const FairVolume &)
FairVolume & operator= (const FairVolume &)
Private Attributes
TString fRealName
Int_t fVolumeId
Int_t fModId
Int_t fMCid
Int_t fCopyNo
Int_t fMotherId
Int_t fMotherCopyNo
FairModule * fModule
FairGeoNode * fNode
Detailed Description
This Object is only used for internal book keeping!
Author
M. Al-Turany, D. Bertini
Version
0.1
Since
12.01.04
Definition at line 21 of file FairVolume.h.
View newest version in sPHENIX GitHub at line 21 of file FairVolume.h
Constructor & Destructor Documentation
FairVolume::FairVolume ()
Volume Name in ASCII file Volume Id in GeoManager Module Id in which this volume exist Volume Id in MC Volume Copy No Mother Volume Id Mother Volume Copy No The Module (detector) which will proccess the hits for this volume Node corre
Definition at line 11 of file FairVolume.cxx.
View newest version in sPHENIX GitHub at line 11 of file FairVolume.cxx
FairVolume::FairVolume (TString name, Int_t id = 0, Int_t ModId = 0, FairModule * fMod = 0)
Volume Name in ASCII file Volume Id in GeoManager Module Id in which this volume exist Volume Id in MC Volume Copy No Mother Volume Id Mother Volume Copy No The Module (detector) which will proccess the hits for this volume Node corre
Definition at line 29 of file FairVolume.cxx.
View newest version in sPHENIX GitHub at line 29 of file FairVolume.cxx
FairVolume::~FairVolume () virtual
Definition at line 48 of file FairVolume.cxx.
View newest version in sPHENIX GitHub at line 48 of file FairVolume.cxx
FairVolume::FairVolume (const FairVolume &) private
Member Function Documentation
Int_t FairVolume::getCopyNo () inline
Definition at line 48 of file FairVolume.h.
View newest version in sPHENIX GitHub at line 48 of file FairVolume.h
References fCopyNo.
Referenced by FairMCApplication::Stepping().
FairGeoNode* FairVolume::getGeoNode () inline
Definition at line 50 of file FairVolume.h.
View newest version in sPHENIX GitHub at line 50 of file FairVolume.h
References fNode.
Referenced by FairModule::getFairVolume(), FairMCApplication::InitGeometry(), and FairDetector::Initialize().
Int_t FairVolume::getMCid () inline
Definition at line 47 of file FairVolume.h.
View newest version in sPHENIX GitHub at line 47 of file FairVolume.h
References fMCid.
Referenced by FairMCApplication::InitGeometry(), CbmRich::ProcessHits(), and EicDetector::ProcessHits().
Int_t FairVolume::getModId () inline
Definition at line 36 of file FairVolume.h.
View newest version in sPHENIX GitHub at line 36 of file FairVolume.h
References fModId.
Referenced by FairMCApplication::InitGeometry(), FairDetector::Initialize(), and FairMCApplication::Stepping().
FairModule* FairVolume::GetModule () inline
Definition at line 44 of file FairVolume.h.
View newest version in sPHENIX GitHub at line 44 of file FairVolume.h
References fModule.
Referenced by FairMCApplication::InitGeometry(), and FairMCApplication::Stepping().
Int_t FairVolume::getMotherCopyNo () inline
Definition at line 52 of file FairVolume.h.
View newest version in sPHENIX GitHub at line 52 of file FairVolume.h
References fMotherCopyNo.
Int_t FairVolume::getMotherId () inline
Definition at line 51 of file FairVolume.h.
View newest version in sPHENIX GitHub at line 51 of file FairVolume.h
References fMotherId.
const char* FairVolume::getRealName () inline
Definition at line 34 of file FairVolume.h.
View newest version in sPHENIX GitHub at line 34 of file FairVolume.h
References fRealName.
Int_t FairVolume::getVolumeId () inline
Definition at line 35 of file FairVolume.h.
View newest version in sPHENIX GitHub at line 35 of file FairVolume.h
References fVolumeId.
Referenced by FairVolumeList::addVolume(), and FairVolumeList::getVolumeId().
FairVolume& FairVolume::operator= (const FairVolume &) private
void FairVolume::setCopyNo (Int_t id) inline
Definition at line 38 of file FairVolume.h.
View newest version in sPHENIX GitHub at line 38 of file FairVolume.h
References fCopyNo.
Referenced by FairMCApplication::InitGeometry(), FairModule::ProcessNodes(), and FairMCApplication::Stepping().
void FairVolume::setGeoNode (FairGeoNode * d) inline
Definition at line 40 of file FairVolume.h.
View newest version in sPHENIX GitHub at line 40 of file FairVolume.h
References d, and fNode.
Referenced by FairModule::ProcessNodes().
void FairVolume::setMCid (Int_t id) inline
Definition at line 49 of file FairVolume.h.
View newest version in sPHENIX GitHub at line 49 of file FairVolume.h
References fMCid.
Referenced by FairMCApplication::InitGeometry(), FairDetector::Initialize(), and FairMCApplication::Stepping().
void FairVolume::setModId (Int_t id) inline
Definition at line 37 of file FairVolume.h.
View newest version in sPHENIX GitHub at line 37 of file FairVolume.h
References fModId.
Referenced by FairModule::AddSensitiveVolume(), FairMCApplication::InitGeometry(), FairModule::ProcessNodes(), and FairMCApplication::Stepping().
void FairVolume::SetModule (FairModule * mod) inline
Definition at line 45 of file FairVolume.h.
View newest version in sPHENIX GitHub at line 45 of file FairVolume.h
References fModule.
Referenced by FairModule::AddSensitiveVolume(), FairMCApplication::InitGeometry(), FairModule::ProcessNodes(), and FairMCApplication::Stepping().
void FairVolume::setMotherCopyNo (Int_t CopyNo) inline
Definition at line 42 of file FairVolume.h.
View newest version in sPHENIX GitHub at line 42 of file FairVolume.h
References fMotherCopyNo.
Referenced by FairModule::ProcessNodes().
void FairVolume::setMotherId (Int_t fM) inline
Definition at line 41 of file FairVolume.h.
View newest version in sPHENIX GitHub at line 41 of file FairVolume.h
References fMotherId.
Referenced by FairModule::ProcessNodes().
void FairVolume::setRealName (TString name) inline
Definition at line 33 of file FairVolume.h.
View newest version in sPHENIX GitHub at line 33 of file FairVolume.h
References fRealName, and name.
Referenced by FairModule::ProcessNodes().
void FairVolume::setVolumeId (Int_t id) inline
Definition at line 39 of file FairVolume.h.
View newest version in sPHENIX GitHub at line 39 of file FairVolume.h
References fVolumeId.
Member Data Documentation
Int_t FairVolume::fCopyNo private
Volume Id in MC
Definition at line 64 of file FairVolume.h.
View newest version in sPHENIX GitHub at line 64 of file FairVolume.h
Referenced by getCopyNo(), and setCopyNo().
Int_t FairVolume::fMCid private
Module Id in which this volume exist
Definition at line 63 of file FairVolume.h.
View newest version in sPHENIX GitHub at line 63 of file FairVolume.h
Referenced by getMCid(), and setMCid().
Int_t FairVolume::fModId private
Volume Id in GeoManager
Definition at line 62 of file FairVolume.h.
View newest version in sPHENIX GitHub at line 62 of file FairVolume.h
Referenced by getModId(), and setModId().
FairModule* FairVolume::fModule private
Mother Volume Copy No
Definition at line 67 of file FairVolume.h.
View newest version in sPHENIX GitHub at line 67 of file FairVolume.h
Referenced by GetModule(), and SetModule().
Int_t FairVolume::fMotherCopyNo private
Mother Volume Id
Definition at line 66 of file FairVolume.h.
View newest version in sPHENIX GitHub at line 66 of file FairVolume.h
Referenced by getMotherCopyNo(), and setMotherCopyNo().
Int_t FairVolume::fMotherId private
Volume Copy No
Definition at line 65 of file FairVolume.h.
View newest version in sPHENIX GitHub at line 65 of file FairVolume.h
Referenced by getMotherId(), and setMotherId().
FairGeoNode* FairVolume::fNode private
The Module (detector) which will proccess the hits for this volume
Definition at line 68 of file FairVolume.h.
View newest version in sPHENIX GitHub at line 68 of file FairVolume.h
Referenced by getGeoNode(), and setGeoNode().
TString FairVolume::fRealName private
Definition at line 60 of file FairVolume.h.
View newest version in sPHENIX GitHub at line 60 of file FairVolume.h
Referenced by getRealName(), and setRealName().
Int_t FairVolume::fVolumeId private
Volume Name in ASCII file
Definition at line 61 of file FairVolume.h.
View newest version in sPHENIX GitHub at line 61 of file FairVolume.h
Referenced by getVolumeId(), and setVolumeId().
The documentation for this class was generated from the following files:
EicRoot/blob/master/base/FairVolume.h
EicRoot/blob/master/base/FairVolume.cxx