EIC Software: erhic::LogReaderPythia Class Reference
erhic::LogReaderPythia Class Reference
#include <eic-smear/blob/master/include/eicsmear/erhic/File.h>
Public Member Functions
LogReaderPythia ()
virtual ~LogReaderPythia ()
LogReaderPythia * Create () const
bool Extract (const std::string &file)
Int_t Save () const
Public Member Functions inherited from erhic::LogReader
LogReader ()
virtual ~LogReader ()
Protected Attributes
TObjString crossSection_
TObjString nEvents_
Total cross section in microbarns
TObjString nTrials_
Total number of events generated and kept
Detailed Description
Processes PYTHIA log files.
Reads a log file and finds the total cross section and the number of generated events when Extract() is called. Writes those values as TObjStrings to the current directory when Save() is called, assuming that directory is writeable.
Definition at line 78 of file File.h.
View newest version in sPHENIX GitHub at line 78 of file File.h
Constructor & Destructor Documentation
erhic::LogReaderPythia::LogReaderPythia ()
Constructor.
Definition at line 62 of file File.cxx.
View newest version in sPHENIX GitHub at line 62 of file File.cxx
Referenced by Create().
erhic::LogReaderPythia::~LogReaderPythia () virtual
Destructor.
Definition at line 64 of file File.cxx.
View newest version in sPHENIX GitHub at line 64 of file File.cxx
Member Function Documentation
LogReaderPythia * erhic::LogReaderPythia::Create () const inline virtual
Return a new LogReaderPythia instance.
Implements erhic::LogReader.
Definition at line 115 of file File.h.
View newest version in sPHENIX GitHub at line 115 of file File.h
References LogReaderPythia().
bool erhic::LogReaderPythia::Extract (const std::string & file) virtual
Extract data from the named log file.
Implements erhic::LogReader.
Definition at line 66 of file File.cxx.
View newest version in sPHENIX GitHub at line 66 of file File.cxx
References crossSection_, getline, in, LogLineParse(), nEvents, nEvents_, and nTrials_.
Int_t erhic::LogReaderPythia::Save () const virtual
Write the extracted information to the current file, if it is writeable. If you want to write the LogReaderPythia itself, use LogReaderPythia::Write().
Implements erhic::LogReader.
Definition at line 91 of file File.cxx.
View newest version in sPHENIX GitHub at line 91 of file File.cxx
References crossSection_, nEvents_, and nTrials_.
Member Data Documentation
TObjString erhic::LogReaderPythia::crossSection_ protected
Definition at line 108 of file File.h.
View newest version in sPHENIX GitHub at line 108 of file File.h
Referenced by Extract(), and Save().
TObjString erhic::LogReaderPythia::nEvents_ protected
Total cross section in microbarns
Definition at line 109 of file File.h.
View newest version in sPHENIX GitHub at line 109 of file File.h
Referenced by Extract(), and Save().
TObjString erhic::LogReaderPythia::nTrials_ protected
Total number of events generated and kept
Definition at line 110 of file File.h.
View newest version in sPHENIX GitHub at line 110 of file File.h
Referenced by Extract(), and Save().
The documentation for this class was generated from the following files:
eic-smear/blob/master/include/eicsmear/erhic/File.h
eic-smear/blob/master/src/erhic/File.cxx