EIC Software: FairHit Class Reference
FairHit Class Reference
#include <EicRoot/blob/master/base/FairHit.h>
Public Member Functions
FairHit ()
FairHit (Int_t detID, TVector3 &pos, TVector3 &dpos, Int_t index)
FairHit (Int_t detID, TVector3 &pos, Int_t index)
virtual ~FairHit ()
Double_t GetDx () const
Double_t GetDy () const
Double_t GetDz () const
Int_t GetRefIndex () const
void PositionError (TVector3 &dpos) const
Int_t GetDetectorID () const
Double_t GetX () const
Double_t GetY () const
Double_t GetZ () const
void Position (TVector3 &pos) const
void SetDx (Double_t dx)
void SetDy (Double_t dy)
void SetDz (Double_t dz)
void SetDxyz (Double_t dx, Double_t dy, Double_t dz)
void SetPositionError (const TVector3 &dpos)
void SetRefIndex (Int_t index)
void SetDetectorID (Int_t detID)
void SetX (Double_t x)
void SetY (Double_t y)
void SetZ (Double_t z)
void SetXYZ (Double_t x, Double_t y, Double_t z)
void SetPosition (const TVector3 &pos)
virtual void Print (const Option_t *opt="") const
Public Member Functions inherited from FairTimeStamp
FairTimeStamp ()
FairTimeStamp (Double_t time)
FairTimeStamp (Double_t time, Double_t timeerror)
virtual ~FairTimeStamp ()
virtual Double_t GetTimeStamp () const
virtual Double_t GetTimeStampError () const
virtual FairLink GetEntryNr () const
virtual void SetTimeStamp (Double_t t)
virtual void SetTimeStampError (Double_t t)
virtual void SetEntryNr (FairLink entry)
virtual Int_t Compare (const TObject *obj) const
void Print (std::ostream &out=std::cout) const
virtual Bool_t IsSortable () const
virtual bool equal (FairTimeStamp *data)
Public Member Functions inherited from FairMultiLinkedData
FairMultiLinkedData ()
Default constructor.
FairMultiLinkedData (std::set< FairLink > links, Bool_t persistanceCheck=kTRUE)
Constructor.
FairMultiLinkedData (TString dataType, std::vector< Int_t > links, Int_t fileId=-1, Int_t evtId=-1, Bool_t persistanceCheck=kTRUE, Bool_t bypass=kFALSE, Float_t mult=1.0)
Constructor.
FairMultiLinkedData (Int_t dataType, std::vector< Int_t > links, Int_t fileId=-1, Int_t evtId=-1, Bool_t persistanceCheck=kTRUE, Bool_t bypass=kFALSE, Float_t mult=1.0)
Constructor.
virtual ~FairMultiLinkedData ()
virtual std::set< FairLink > GetLinks () const
returns stored links as FairLinks
virtual Int_t GetNLinks () const
returns the number of stored links
virtual FairLink GetLink (Int_t pos) const
returns the FairLink at the given position
virtual FairMultiLinkedData GetLinksWithType (Int_t type) const
Gives you a list of links which contain the given type.
TObject * GetData (FairLink &myLink)
Get the TObject the Link is pointing to.
virtual Int_t GetDefaultType ()
Bool_t GetPersistanceCheck ()
Returns the value of PersistanceCheck.
Int_t GetVerbose ()
Returns the verbosity level.
virtual void SetDefaultType (Int_t type)
virtual void SetPersistanceCheck (Bool_t check)
Controls if a persistance check of a link is done or not.
virtual void SetVerbose (Int_t level)
Sets the verbosity level.
virtual void SetLinks (FairMultiLinkedData links, Float_t mult=1.0)
Sets the links as vector of FairLink.
virtual void SetLink (FairLink link, Bool_t bypass=kFALSE, Float_t mult=1.0)
Sets the Links with a single FairLink.
virtual void AddLinks (FairMultiLinkedData links, Float_t mult=1.0)
Adds a List of FairLinks (FairMultiLinkedData) to fLinks.
virtual void AddLink (FairLink link, Bool_t bypass=kFALSE, Float_t mult=1.0)
Adds a FairLink link at the end of fLinks. If multi is kTRUE a link is allowed more than once otherwise it is stored only once.
virtual void InsertLink (FairLink link)
Inserts a link into the list of links without persistance checking.
virtual void AddAllWeights (Double_t weight)
Adds weight to all Links.
virtual void SetAllWeights (Double_t weight)
Sets a common weight for Links.
virtual void MultiplyAllWeights (Double_t weight)
Multiplies all Links with weight.
virtual Bool_t IsLinkInList (FairLink link)
Test if a given link is in fLinks.
virtual Bool_t IsLinkInList (Int_t type, Int_t index)
Same as IsLinkInList(FairLink) just with type and index given separately.
virtual Int_t LinkPosInList (FairLink link)
returns position of link in fLinks. If it is not in the list -1 is returned
virtual Int_t LinkPosInList (Int_t type, Int_t index)
Same as LinkPosInList(FairLink)
virtual void DeleteLink (FairLink link)
Deletes a link ouf of fLinks.
virtual void DeleteLink (Int_t type, Int_t index)
Deletes a link ouf of fLinks.
virtual void Reset ()
virtual void ResetLinks ()
Clears fLinks.
void Print (std::ostream &out=std::cout) const
Output.
Protected Member Functions
ClassDef (FairHit, 2)
Protected Member Functions inherited from FairTimeStamp
ClassDef (FairTimeStamp, 2)
indicates where the data is stored in the branch
Protected Member Functions inherited from FairMultiLinkedData
virtual void SimpleAddLinks (Int_t fileId, Int_t evtId, Int_t dataType, std::vector< Int_t > links, Bool_t bypass, Float_t mult)
ClassDef (FairMultiLinkedData, 3)
Protected Attributes
Double32_t fDx
Double32_t fDy
Double32_t fDz
Errors of position [cm].
Int_t fRefIndex
Index of FairMCPoint for this hit.
Int_t fDetectorID
Detector unique identifier.
Double32_t fX
Double32_t fY
Double32_t fZ
Position of hit [cm].
Protected Attributes inherited from FairTimeStamp
Double_t fTimeStamp
Double_t fTimeStampError
FairLink fEntryNr
Protected Attributes inherited from FairMultiLinkedData
std::set< FairLink > fLinks
Bool_t fPersistanceCheck
Int_t fVerbose
Int_t fDefaultType
Detailed Description
Abstract base class for reconstructed hits in the FAIR detectors.
Author
V.Friese v.fri.nosp@m.ese@.nosp@m.gsi.d.nosp@m.e
D.Bertini d.ber.nosp@m.tini.nosp@m.@gsi..nosp@m.de
M.Al-Turany m.al-.nosp@m.tura.nosp@m.ny@gs.nosp@m.i.de
Definition at line 13 of file FairHit.h.
View newest version in sPHENIX GitHub at line 13 of file FairHit.h
Constructor & Destructor Documentation
FairHit::FairHit ()
Default constructor
Definition at line 5 of file FairHit.cxx.
View newest version in sPHENIX GitHub at line 5 of file FairHit.cxx
FairHit::FairHit (Int_t detID, TVector3 & pos, TVector3 & dpos, Int_t index)
Constructor with hit parameters
Definition at line 38 of file FairHit.cxx.
View newest version in sPHENIX GitHub at line 38 of file FairHit.cxx
FairHit::FairHit (Int_t detID, TVector3 & pos, Int_t index)
Definition at line 20 of file FairHit.cxx.
View newest version in sPHENIX GitHub at line 20 of file FairHit.cxx
FairHit::~FairHit () virtual
Destructor
Definition at line 55 of file FairHit.cxx.
View newest version in sPHENIX GitHub at line 55 of file FairHit.cxx
Member Function Documentation
FairHit::ClassDef (FairHit , 2) protected
Int_t FairHit::GetDetectorID () const inline
Definition at line 37 of file FairHit.h.
View newest version in sPHENIX GitHub at line 37 of file FairHit.h
References fDetectorID.
Double_t FairHit::GetDx () const inline
Accessors
Definition at line 32 of file FairHit.h.
View newest version in sPHENIX GitHub at line 32 of file FairHit.h
References fDx.
Referenced by PndHitRecoHit::PndHitRecoHit().
Double_t FairHit::GetDy () const inline
Definition at line 33 of file FairHit.h.
View newest version in sPHENIX GitHub at line 33 of file FairHit.h
References fDy.
Referenced by PndHitRecoHit::PndHitRecoHit().
Double_t FairHit::GetDz () const inline
Definition at line 34 of file FairHit.h.
View newest version in sPHENIX GitHub at line 34 of file FairHit.h
References fDz.
Referenced by PndHitRecoHit::PndHitRecoHit().
Int_t FairHit::GetRefIndex () const inline
Definition at line 35 of file FairHit.h.
View newest version in sPHENIX GitHub at line 35 of file FairHit.h
References fRefIndex.
Referenced by EicIdealTrackingCode::Exec(), and PndRecoKalmanFit::Fit().
Double_t FairHit::GetX () const inline
Definition at line 38 of file FairHit.h.
View newest version in sPHENIX GitHub at line 38 of file FairHit.h
References fX.
Referenced by EicIdealTrackingCode::Exec(), FairHitPointSetDraw::GetVector(), FairHitDraw::GetVector(), and PndHitRecoHit::PndHitRecoHit().
Double_t FairHit::GetY () const inline
Definition at line 39 of file FairHit.h.
View newest version in sPHENIX GitHub at line 39 of file FairHit.h
References fY.
Referenced by EicIdealTrackingCode::Exec(), FairHitPointSetDraw::GetVector(), FairHitDraw::GetVector(), and PndHitRecoHit::PndHitRecoHit().
Double_t FairHit::GetZ () const inline
Definition at line 40 of file FairHit.h.
View newest version in sPHENIX GitHub at line 40 of file FairHit.h
References fZ.
Referenced by EicIdealTrackingCode::Exec(), EicHtcTask::Exec(), FairHitPointSetDraw::GetVector(), FairHitDraw::GetVector(), and PndHitRecoHit::PndHitRecoHit().
void FairHit::Position (TVector3 & pos) const inline
Definition at line 100 of file FairHit.h.
View newest version in sPHENIX GitHub at line 100 of file FairHit.h
References fX, fY, and fZ.
void FairHit::PositionError (TVector3 & dpos) const inline
Definition at line 79 of file FairHit.h.
View newest version in sPHENIX GitHub at line 79 of file FairHit.h
References fDx, fDy, and fDz.
virtual void FairHit::Print (const Option_t * opt = "") const inline virtual
Reimplemented in EicTrackingDigiHit, and CbmHit.
Definition at line 61 of file FairHit.h.
View newest version in sPHENIX GitHub at line 61 of file FairHit.h
void FairHit::SetDetectorID (Int_t detID) inline
Definition at line 52 of file FairHit.h.
View newest version in sPHENIX GitHub at line 52 of file FairHit.h
References fDetectorID.
void FairHit::SetDx (Double_t dx) inline
Modifiers
Definition at line 46 of file FairHit.h.
View newest version in sPHENIX GitHub at line 46 of file FairHit.h
References dx, and fDx.
void FairHit::SetDxyz (Double_t dx, Double_t dy, Double_t dz) inline
Definition at line 85 of file FairHit.h.
View newest version in sPHENIX GitHub at line 85 of file FairHit.h
References dx, dy, dz, fDx, fDy, and fDz.
void FairHit::SetDy (Double_t dy) inline
Definition at line 47 of file FairHit.h.
View newest version in sPHENIX GitHub at line 47 of file FairHit.h
References dy, and fDy.
void FairHit::SetDz (Double_t dz) inline
Definition at line 48 of file FairHit.h.
View newest version in sPHENIX GitHub at line 48 of file FairHit.h
References dz, and fDz.
void FairHit::SetPosition (const TVector3 & pos) inline
Definition at line 114 of file FairHit.h.
View newest version in sPHENIX GitHub at line 114 of file FairHit.h
References fX, fY, and fZ.
void FairHit::SetPositionError (const TVector3 & dpos) inline
Definition at line 93 of file FairHit.h.
View newest version in sPHENIX GitHub at line 93 of file FairHit.h
References fDx, fDy, and fDz.
void FairHit::SetRefIndex (Int_t index) inline
Definition at line 51 of file FairHit.h.
View newest version in sPHENIX GitHub at line 51 of file FairHit.h
References fRefIndex.
void FairHit::SetX (Double_t x) inline
Definition at line 53 of file FairHit.h.
View newest version in sPHENIX GitHub at line 53 of file FairHit.h
References fX, and x.
Referenced by PndVertex::PndVertex().
void FairHit::SetXYZ (Double_t x, Double_t y, Double_t z) inline
Definition at line 106 of file FairHit.h.
View newest version in sPHENIX GitHub at line 106 of file FairHit.h
References fX, fY, fZ, x, y, and z.
void FairHit::SetY (Double_t y) inline
Definition at line 54 of file FairHit.h.
View newest version in sPHENIX GitHub at line 54 of file FairHit.h
References fY, and y.
Referenced by PndVertex::PndVertex().
void FairHit::SetZ (Double_t z) inline
Definition at line 55 of file FairHit.h.
View newest version in sPHENIX GitHub at line 55 of file FairHit.h
References fZ, and z.
Referenced by PndVertex::PndVertex().
Member Data Documentation
Int_t FairHit::fDetectorID protected
Detector unique identifier.
Definition at line 69 of file FairHit.h.
View newest version in sPHENIX GitHub at line 69 of file FairHit.h
Referenced by GetDetectorID(), CbmHit::Print(), and SetDetectorID().
Double32_t FairHit::fDx protected
Definition at line 67 of file FairHit.h.
View newest version in sPHENIX GitHub at line 67 of file FairHit.h
Referenced by GetDx(), PositionError(), SetDx(), SetDxyz(), and SetPositionError().
Double32_t FairHit::fDy protected
Definition at line 67 of file FairHit.h.
View newest version in sPHENIX GitHub at line 67 of file FairHit.h
Referenced by GetDy(), PositionError(), SetDxyz(), SetDy(), and SetPositionError().
Double32_t FairHit::fDz protected
Errors of position [cm].
Definition at line 67 of file FairHit.h.
View newest version in sPHENIX GitHub at line 67 of file FairHit.h
Referenced by GetDz(), PositionError(), SetDxyz(), SetDz(), and SetPositionError().
Int_t FairHit::fRefIndex protected
Index of FairMCPoint for this hit.
Definition at line 68 of file FairHit.h.
View newest version in sPHENIX GitHub at line 68 of file FairHit.h
Referenced by GetRefIndex(), and SetRefIndex().
Double32_t FairHit::fX protected
Definition at line 70 of file FairHit.h.
View newest version in sPHENIX GitHub at line 70 of file FairHit.h
Referenced by GetX(), Position(), CbmHit::Print(), SetPosition(), SetX(), and SetXYZ().
Double32_t FairHit::fY protected
Definition at line 70 of file FairHit.h.
View newest version in sPHENIX GitHub at line 70 of file FairHit.h
Referenced by GetY(), Position(), CbmHit::Print(), SetPosition(), SetXYZ(), and SetY().
Double32_t FairHit::fZ protected
Position of hit [cm].
Definition at line 70 of file FairHit.h.
View newest version in sPHENIX GitHub at line 70 of file FairHit.h
Referenced by GetZ(), Position(), CbmHit::Print(), SetPosition(), SetXYZ(), and SetZ().
The documentation for this class was generated from the following files:
EicRoot/blob/master/base/FairHit.h
EicRoot/blob/master/base/FairHit.cxx