EIC Software: Acts::Vertex< input_track_t > Class Template Reference
Acts::Vertex< input_track_t > Class Template Reference
Class for storing vertex objects.
#include <fun4all_acts/blob/master/Core/include/Acts/Vertexing/Vertex.hpp>
Public Member Functions
Vertex ()=default
Default constructor.
Vertex (const Vector3D &position)
Construct for vertex at given 3d-position, sets covariance to zero.
Vertex (const SpacePointVector &position)
Construct for vertex at given 4d-position, sets covariance to zero.
Vertex (const Vector3D &position, const ActsSymMatrixD< 3 > &covariance, const std::vector< TrackAtVertex< input_track_t >> &tracks)
Vertex constructor.
Vertex (const SpacePointVector &position, const SpacePointSymMatrix &covariance, const std::vector< TrackAtVertex< input_track_t >> &tracks)
Vertex constructor.
Vector3D position () const
ParValue_t time () const
const SpacePointVector & fullPosition () const
ActsSymMatrixD< 3 > covariance () const
const SpacePointSymMatrix & fullCovariance () const
const std::vector
< TrackAtVertex< input_track_t > > & tracks () const
std::pair< double, double > fitQuality () const
void setPosition (const Vector3D &position, ParValue_t time=0)
Set position and time.
void setFullPosition (const SpacePointVector &fullPosition)
Set position and time.
void setTime (ParValue_t time)
Sets time.
void setCovariance (const ActsSymMatrixD< 3 > &covariance)
Sets 3x3 covariance.
void setFullCovariance (const SpacePointSymMatrix &covariance)
Sets 4x4 covariance.
void setTracksAtVertex (const std::vector< TrackAtVertex< input_track_t >> &tracks)
void setFitQuality (double chiSquared, double numberDoF)
void setFitQuality (std::pair< double, double > fitQuality)
Private Attributes
SpacePointVector m_position = SpacePointVector::Zero()
SpacePointSymMatrix m_covariance = SpacePointSymMatrix::Zero()
std::vector< TrackAtVertex
< input_track_t > > m_tracksAtVertex
double m_chiSquared = 1e9
double m_numberDoF = 0.
Detailed Description
template<typename input_track_t>
class Acts::Vertex< input_track_t >
Class for storing vertex objects.
Template Parameters
input_track_t Track object type
Definition at line 23 of file Vertex.hpp.
View newest version in sPHENIX GitHub at line 23 of file Vertex.hpp
Constructor & Destructor Documentation
template<typename input_track_t> Acts::Vertex< input_track_t >::Vertex () default
Default constructor.
template<typename input_track_t > Acts::Vertex< input_track_t >::Vertex (const Vector3D & position)
Construct for vertex at given 3d-position, sets covariance to zero.
Parameters
position Vertex position
Definition at line 10 of file Vertex.ipp.
View newest version in sPHENIX GitHub at line 10 of file Vertex.ipp
References Acts::VectorHelpers::position().
template<typename input_track_t > Acts::Vertex< input_track_t >::Vertex (const SpacePointVector & position)
Construct for vertex at given 4d-position, sets covariance to zero.
Parameters
position Vertex position
Definition at line 18 of file Vertex.ipp.
View newest version in sPHENIX GitHub at line 18 of file Vertex.ipp
References Acts::VectorHelpers::position().
template<typename input_track_t> Acts::Vertex< input_track_t >::Vertex (const Vector3D & position, const ActsSymMatrixD< 3 > & covariance, const std::vector< TrackAtVertex< input_track_t >> & tracks)
Vertex constructor.
Parameters
position Vertex position
covariance Position covariance matrix
tracks Vector of tracks associated with the vertex
Definition at line 25 of file Vertex.ipp.
View newest version in sPHENIX GitHub at line 25 of file Vertex.ipp
References Acts::Vertex< input_track_t >::m_covariance, Acts::Vertex< input_track_t >::m_position, Acts::Vertex< input_track_t >::position(), and Acts::VectorHelpers::position().
template<typename input_track_t> Acts::Vertex< input_track_t >::Vertex (const SpacePointVector & position, const SpacePointSymMatrix & covariance, const std::vector< TrackAtVertex< input_track_t >> & tracks)
Vertex constructor.
Parameters
position Full vertex position
covariance 4x4 covariance matrix
tracks Vector of tracks associated with the vertex
Definition at line 36 of file Vertex.ipp.
View newest version in sPHENIX GitHub at line 36 of file Vertex.ipp
Member Function Documentation
template<typename input_track_t > Acts::ActsSymMatrixD< 3 > Acts::Vertex< input_track_t >::covariance () const
Returns
Returns position covariance
Definition at line 60 of file Vertex.ipp.
View newest version in sPHENIX GitHub at line 60 of file Vertex.ipp
Referenced by PHActsVertexFitter::createActsSvtxVertex(), Acts::ImpactPointEstimator< input_track_t, propagator_t, propagator_options_t >::estimateImpactParameters(), Acts::TrackDensityVertexFinder< vfitter_t, track_density_t >::find(), Acts::KalmanVertexUpdater::updatePosition(), and PHActsVertexFitter::updateSvtxVertex().
template<typename input_track_t > std::pair< double, double > Acts::Vertex< input_track_t >::fitQuality () const
Returns
Returns pair of (chi2, numberDoF)
Definition at line 77 of file Vertex.ipp.
View newest version in sPHENIX GitHub at line 77 of file Vertex.ipp
Referenced by PHActsVertexFitter::createActsSvtxVertex(), Acts::IterativeVertexFinder< vfitter_t, sfinder_t >::find(), Acts::IterativeVertexFinder< vfitter_t, sfinder_t >::reassignTracksToNewVertex(), Acts::KalmanVertexUpdater::detail::update(), and PHActsVertexFitter::updateSvtxVertex().
template<typename input_track_t > const Acts::SpacePointSymMatrix & Acts::Vertex< input_track_t >::fullCovariance () const
Returns
Returns 4x4 covariance
Definition at line 65 of file Vertex.ipp.
View newest version in sPHENIX GitHub at line 65 of file Vertex.ipp
Referenced by Acts::Test::BOOST_AUTO_TEST_CASE(), Acts::AdaptiveMultiVertexFinder< vfitter_t, sfinder_t >::doSeeding(), Acts::IterativeVertexFinder< vfitter_t, sfinder_t >::getCompatibility(), Acts::AdaptiveMultiVertexFinder< vfitter_t, sfinder_t >::isMergedVertex(), and Acts::KalmanVertexTrackUpdater::update().
template<typename input_track_t > const Acts::SpacePointVector & Acts::Vertex< input_track_t >::fullPosition () const
Returns
Returns 4-position
Definition at line 54 of file Vertex.ipp.
View newest version in sPHENIX GitHub at line 54 of file Vertex.ipp
Referenced by Acts::AdaptiveMultiVertexFinder< vfitter_t, sfinder_t >::doSeeding(), Acts::AdaptiveMultiVertexFinder< vfitter_t, sfinder_t >::find(), Acts::IterativeVertexFinder< vfitter_t, sfinder_t >::getCompatibility(), Acts::IterativeVertexFinder< vfitter_t, sfinder_t >::getVertexSeed(), Acts::AdaptiveMultiVertexFinder< vfitter_t, sfinder_t >::isMergedVertex(), and Acts::KalmanVertexTrackUpdater::update().
template<typename input_track_t > Acts::Vector3D Acts::Vertex< input_track_t >::position () const
Returns
Returns 3-position
Definition at line 44 of file Vertex.ipp.
View newest version in sPHENIX GitHub at line 44 of file Vertex.ipp
References Acts::VectorHelpers::position().
Referenced by Acts::Test::BOOST_AUTO_TEST_CASE(), PHActsVertexFitter::createActsSvtxVertex(), Acts::ImpactPointEstimator< input_track_t, propagator_t, propagator_options_t >::estimateImpactParameters(), FWE::VertexFitAlgorithm::execute(), Acts::IterativeVertexFinder< vfitter_t, sfinder_t >::fillPerigeesToFit(), Acts::AdaptiveMultiVertexFinder< vfitter_t, sfinder_t >::find(), PHActsVertexFitter::fitVertex(), Acts::KalmanVertexUpdater::updatePosition(), PHActsVertexFitter::updateSvtxVertex(), Acts::Vertex< input_track_t >::Vertex(), and Acts::KalmanVertexUpdater::detail::vertexPositionChi2().
template<typename input_track_t > void Acts::Vertex< input_track_t >::setCovariance (const ActsSymMatrixD< 3 > & covariance)
Sets 3x3 covariance.
Parameters
covariance Position covariance matrix
Definition at line 101 of file Vertex.ipp.
View newest version in sPHENIX GitHub at line 101 of file Vertex.ipp
Referenced by Acts::Test::BOOST_AUTO_TEST_CASE(), FWE::VertexFitAlgorithm::execute(), and Acts::TrackDensityVertexFinder< vfitter_t, track_density_t >::find().
template<typename input_track_t > void Acts::Vertex< input_track_t >::setFitQuality (double chiSquared, double numberDoF)
Parameters
chiSquared Chi2 of fit
numberDoF Number of degrees of freedom
Definition at line 120 of file Vertex.ipp.
View newest version in sPHENIX GitHub at line 120 of file Vertex.ipp
Referenced by Acts::Test::BOOST_AUTO_TEST_CASE().
template<typename input_track_t > void Acts::Vertex< input_track_t >::setFitQuality (std::pair< double, double > fitQuality)
Parameters
fitQuality pair of (chi2, numberDoF)
Definition at line 127 of file Vertex.ipp.
View newest version in sPHENIX GitHub at line 127 of file Vertex.ipp
template<typename input_track_t > void Acts::Vertex< input_track_t >::setFullCovariance (const SpacePointSymMatrix & covariance)
Sets 4x4 covariance.
Parameters
covariance The 4x4 covariance matrix
Definition at line 108 of file Vertex.ipp.
View newest version in sPHENIX GitHub at line 108 of file Vertex.ipp
Referenced by Acts::Test::BOOST_AUTO_TEST_CASE(), and Acts::AdaptiveMultiVertexFinder< vfitter_t, sfinder_t >::getIPSignificance().
template<typename input_track_t > void Acts::Vertex< input_track_t >::setFullPosition (const SpacePointVector & fullPosition)
Set position and time.
Parameters
fullPosition Vertex position and time
Definition at line 90 of file Vertex.ipp.
View newest version in sPHENIX GitHub at line 90 of file Vertex.ipp
Referenced by Acts::Test::BOOST_AUTO_TEST_CASE().
template<typename input_track_t > void Acts::Vertex< input_track_t >::setPosition (const Vector3D & position, ParValue_t time = 0)
Set position and time.
Parameters
position Vertex position
time The time
Definition at line 82 of file Vertex.ipp.
View newest version in sPHENIX GitHub at line 82 of file Vertex.ipp
References Acts::VectorHelpers::position(), and Acts::VectorHelpers::time().
Referenced by Acts::Test::BOOST_AUTO_TEST_CASE(), and FWE::VertexFitAlgorithm::execute().
template<typename input_track_t > void Acts::Vertex< input_track_t >::setTime (ParValue_t time)
Sets time.
Parameters
time The time
Definition at line 96 of file Vertex.ipp.
View newest version in sPHENIX GitHub at line 96 of file Vertex.ipp
References Acts::VectorHelpers::time().
template<typename input_track_t> void Acts::Vertex< input_track_t >::setTracksAtVertex (const std::vector< TrackAtVertex< input_track_t >> & tracks)
Parameters
tracks Vector of tracks at vertex
Definition at line 114 of file Vertex.ipp.
View newest version in sPHENIX GitHub at line 114 of file Vertex.ipp
Referenced by Acts::Test::BOOST_AUTO_TEST_CASE(), and Acts::IterativeVertexFinder< vfitter_t, sfinder_t >::removeUsedCompatibleTracks().
template<typename input_track_t > Acts::ParValue_t Acts::Vertex< input_track_t >::time () const
Returns
Returns time
Definition at line 49 of file Vertex.ipp.
View newest version in sPHENIX GitHub at line 49 of file Vertex.ipp
References Acts::VectorHelpers::time().
Referenced by PHActsVertexFitter::createActsSvtxVertex(), Acts::IterativeVertexFinder< vfitter_t, sfinder_t >::getVertexSeed(), and PHActsVertexFitter::updateSvtxVertex().
template<typename input_track_t > const std::vector< Acts::TrackAtVertex< input_track_t > > & Acts::Vertex< input_track_t >::tracks () const
Returns
Returns vector of tracks associated with the vertex
Definition at line 72 of file Vertex.ipp.
View newest version in sPHENIX GitHub at line 72 of file Vertex.ipp
Referenced by Acts::Test::BOOST_AUTO_TEST_CASE(), Acts::IterativeVertexFinder< vfitter_t, sfinder_t >::countSignificantTracks(), and Acts::IterativeVertexFinder< vfitter_t, sfinder_t >::removeUsedCompatibleTracks().
Member Data Documentation
template<typename input_track_t> double Acts::Vertex< input_track_t >::m_chiSquared = 1e9 private
Definition at line 117 of file Vertex.hpp.
View newest version in sPHENIX GitHub at line 117 of file Vertex.hpp
template<typename input_track_t> SpacePointSymMatrix Acts::Vertex< input_track_t >::m_covariance = SpacePointSymMatrix::Zero() private
Definition at line 115 of file Vertex.hpp.
View newest version in sPHENIX GitHub at line 115 of file Vertex.hpp
Referenced by Acts::Vertex< input_track_t >::Vertex().
template<typename input_track_t> double Acts::Vertex< input_track_t >::m_numberDoF = 0. private
Definition at line 118 of file Vertex.hpp.
View newest version in sPHENIX GitHub at line 118 of file Vertex.hpp
template<typename input_track_t> SpacePointVector Acts::Vertex< input_track_t >::m_position = SpacePointVector::Zero() private
Definition at line 114 of file Vertex.hpp.
View newest version in sPHENIX GitHub at line 114 of file Vertex.hpp
Referenced by Acts::Vertex< input_track_t >::Vertex().
template<typename input_track_t> std::vector<TrackAtVertex<input_track_t> > Acts::Vertex< input_track_t >::m_tracksAtVertex private
Definition at line 116 of file Vertex.hpp.
View newest version in sPHENIX GitHub at line 116 of file Vertex.hpp
The documentation for this class was generated from the following files:
fun4all_acts/blob/master/Core/include/Acts/Vertexing/Vertex.hpp
fun4all_acts/blob/master/Core/include/Acts/Vertexing/Vertex.ipp