EIC Software: FairDbResult Class Reference
FairDbResult Class Reference abstract
#include <EicRoot/blob/master/dbase/dbInterface/FairDbResult.h>
Public Member Functions
FairDbResult (FairDbResultSet *resultSet=0, const FairDbValidityRec *vrec=0, const string &sqlQualifiers="")
FairDbResult (const FairDbResult &)
virtual ~FairDbResult ()
virtual Bool_t CanReuse () const
virtual Bool_t CanSave () const
virtual void Connect () const
virtual FairDbResultKey * CreateKey () const =0
virtual void Disconnect () const
Int_t GetID () const
virtual const FairDbResultKey * GetKey () const
virtual UInt_t GetNumAggregates () const =0
virtual UInt_t GetNumClients () const
virtual UInt_t GetNumRows () const =0
const string & GetSqlQualifiers () const
virtual const FairDbTableRow * GetTableRow (UInt_t rowNum) const =0
virtual const FairDbTableRow * GetTableRowByIndex (UInt_t index) const
virtual const FairDbValidityRec & GetValidityRec (const FairDbTableRow *row=0) const
virtual const FairDbValidityRec & GetValidityRecGlobal () const
Bool_t IsExtendedContext () const
virtual Bool_t Owns (const FairDbTableRow *table) const
Bool_t ResultsFromDb () const
virtual const string & TableName () const
virtual Bool_t CanDelete (const FairDbResult *res=0)
virtual Bool_t Satisfies (const ValContext &vc, const FairDb::Task &task)
virtual Bool_t Satisfies (const string &)
virtual Bool_t Satisfies (const FairDbValidityRec &, const string &="")
virtual void DeRegisterKey ()
virtual void RegisterKey ()
virtual void Streamer (FairDbBinaryFile &file)
virtual void SetCanReuse (Bool_t reuse)
void CaptureExceptionLog (UInt_t startFrom)
Protected Member Functions
void SetResultsFromDb ()
void BuildLookUpTable () const
Bool_t LookUpBuilt () const
virtual void SetTableName (const string &tableName)
virtual void SetValidityRec (const FairDbValidityRec &vRec)
Private Attributes
Int_t fID
Bool_t fCanReuse
FairDbValidityRec fEffVRec
IndexToRow_t fIndexKeys
const FairDbResultKey * fKey
Bool_t fResultsFromDb
Int_t fNumClients
string fTableName
string fSqlQualifiers
FairDbExceptionLog fExceptionLog
Static Private Attributes
static Int_t fgLastID
Detailed Description
Definition at line 176 of file FairDbResult.h.
View newest version in sPHENIX GitHub at line 176 of file FairDbResult.h
Constructor & Destructor Documentation
FairDbResult::FairDbResult (FairDbResultSet * resultSet = 0, const FairDbValidityRec * vrec = 0, const string & sqlQualifiers = "")
Definition at line 798 of file FairDbResult.cxx.
View newest version in sPHENIX GitHub at line 798 of file FairDbResult.cxx
References fEffVRec, fTableName, and FairDbRowStream::TableNameTc().
FairDbResult::FairDbResult (const FairDbResult & from)
Definition at line 818 of file FairDbResult.cxx.
View newest version in sPHENIX GitHub at line 818 of file FairDbResult.cxx
FairDbResult::~FairDbResult () virtual
Definition at line 834 of file FairDbResult.cxx.
View newest version in sPHENIX GitHub at line 834 of file FairDbResult.cxx
References DeRegisterKey(), and fNumClients.
Member Function Documentation
void FairDbResult::BuildLookUpTable () const protected
Definition at line 858 of file FairDbResult.cxx.
View newest version in sPHENIX GitHub at line 858 of file FairDbResult.cxx
References fIndexKeys, FairDbTableRow::GetAggregateNo(), FairDbTableRow::GetIndex(), GetNumRows(), FairDbTableRow::GetOwner(), FairDbValidityRec::GetSeqNo(), GetTableRow(), GetTableRowByIndex(), GetValidityRec(), IsExtendedContext(), and TableName().
Referenced by FairDbResultNonAgg::GetTableRowByIndex(), and FairDbResultNonAgg::Streamer().
Bool_t FairDbResult::CanDelete (const FairDbResult * res = 0) virtual
Definition at line 899 of file FairDbResult.cxx.
View newest version in sPHENIX GitHub at line 899 of file FairDbResult.cxx
References CanReuse(), GetNumClients(), GetValidityRec(), and SetCanReuse().
Referenced by FairDbCache::Purge().
virtual Bool_t FairDbResult::CanReuse () const inline virtual
Definition at line 191 of file FairDbResult.h.
View newest version in sPHENIX GitHub at line 191 of file FairDbResult.h
References fCanReuse.
Referenced by CanDelete(), Satisfies(), FairDbResultAgg::Satisfies(), and FairDbResultNonAgg::Satisfies().
virtual Bool_t FairDbResult::CanSave () const inline virtual
Definition at line 192 of file FairDbResult.h.
View newest version in sPHENIX GitHub at line 192 of file FairDbResult.h
Referenced by FairDbTableProxy::SaveToL2Cache().
void FairDbResult::CaptureExceptionLog (UInt_t startFrom)
Definition at line 845 of file FairDbResult.cxx.
View newest version in sPHENIX GitHub at line 845 of file FairDbResult.cxx
References FairDbExceptionLog::Clear(), FairDbExceptionLog::Copy(), fExceptionLog, and FairDbExceptionLog::GetGELog().
Referenced by FairDbTableProxy::Query().
virtual void FairDbResult::Connect () const inline virtual
Definition at line 193 of file FairDbResult.h.
View newest version in sPHENIX GitHub at line 193 of file FairDbResult.h
References fNumClients.
virtual FairDbResultKey* FairDbResult::CreateKey () const pure virtual
Implemented in FairDbResultNonAgg, and FairDbResultAgg.
Referenced by FairDbResultAgg::CreateKey(), and RegisterKey().
void FairDbResult::DeRegisterKey () virtual
Definition at line 909 of file FairDbResult.cxx.
View newest version in sPHENIX GitHub at line 909 of file FairDbResult.cxx
References fKey.
Referenced by ~FairDbResult().
virtual void FairDbResult::Disconnect () const inline virtual
Definition at line 195 of file FairDbResult.h.
View newest version in sPHENIX GitHub at line 195 of file FairDbResult.h
References fNumClients.
Int_t FairDbResult::GetID () const inline
Definition at line 196 of file FairDbResult.h.
View newest version in sPHENIX GitHub at line 196 of file FairDbResult.h
References fID.
const FairDbResultKey * FairDbResult::GetKey () const virtual
Definition at line 925 of file FairDbResult.cxx.
View newest version in sPHENIX GitHub at line 925 of file FairDbResult.cxx
References fKey, and FairDbResultKey::GetEmptyKey().
Referenced by FairDbCache::Adopt().
virtual UInt_t FairDbResult::GetNumAggregates () const pure virtual
Implemented in FairDbResultNonAgg, and FairDbResultAgg.
Referenced by FairDbCache::Search().
virtual UInt_t FairDbResult::GetNumClients () const inline virtual
Definition at line 199 of file FairDbResult.h.
View newest version in sPHENIX GitHub at line 199 of file FairDbResult.h
References fNumClients.
Referenced by CanDelete(), FairDbCache::Purge(), and Satisfies().
virtual UInt_t FairDbResult::GetNumRows () const pure virtual
Implemented in FairDbResultNonAgg, and FairDbResultAgg.
Referenced by BuildLookUpTable(), FairDbValRecSet::GetNumRows(), RegisterKey(), FairDbTableProxy::SaveToL2Cache(), and FairDbCache::Search().
const string& FairDbResult::GetSqlQualifiers () const inline
Definition at line 203 of file FairDbResult.h.
View newest version in sPHENIX GitHub at line 203 of file FairDbResult.h
References fSqlQualifiers.
Referenced by IsExtendedContext(), FairDbResultAgg::Satisfies(), and FairDbResultNonAgg::Satisfies().
virtual const FairDbTableRow* FairDbResult::GetTableRow (UInt_t rowNum) const pure virtual
Implemented in FairDbResultNonAgg, and FairDbResultAgg.
Referenced by BuildLookUpTable(), and FairDbValRecSet::GetTableRow().
const FairDbTableRow * FairDbResult::GetTableRowByIndex (UInt_t index) const virtual
Reimplemented in FairDbResultNonAgg.
Definition at line 932 of file FairDbResult.cxx.
View newest version in sPHENIX GitHub at line 932 of file FairDbResult.cxx
References fIndexKeys.
Referenced by BuildLookUpTable(), and FairDbResultNonAgg::GetTableRowByIndex().
virtual const FairDbValidityRec& FairDbResult::GetValidityRec (const FairDbTableRow * row = 0) const inline virtual
Reimplemented in FairDbResultAgg.
Definition at line 206 of file FairDbResult.h.
View newest version in sPHENIX GitHub at line 206 of file FairDbResult.h
References GetValidityRecGlobal().
Referenced by FairDbCache::Adopt(), BuildLookUpTable(), CanDelete(), FairDbResultAgg::CreateKey(), FairDbResultNonAgg::CreateKey(), FairDbCache::Purge(), Satisfies(), and FairDbResultNonAgg::Satisfies().
virtual const FairDbValidityRec& FairDbResult::GetValidityRecGlobal () const inline virtual
Definition at line 210 of file FairDbResult.h.
View newest version in sPHENIX GitHub at line 210 of file FairDbResult.h
References fEffVRec.
Referenced by FairDbCache::Adopt(), GetValidityRec(), FairDbResultAgg::GetValidityRec(), and FairDbResultAgg::Streamer().
Bool_t FairDbResult::IsExtendedContext () const inline
Definition at line 213 of file FairDbResult.h.
View newest version in sPHENIX GitHub at line 213 of file FairDbResult.h
References GetSqlQualifiers().
Referenced by BuildLookUpTable(), and Satisfies().
Bool_t FairDbResult::LookUpBuilt () const inline protected
Definition at line 237 of file FairDbResult.h.
View newest version in sPHENIX GitHub at line 237 of file FairDbResult.h
References fIndexKeys.
Referenced by FairDbResultNonAgg::GetTableRowByIndex().
virtual Bool_t FairDbResult::Owns (const FairDbTableRow * table) const inline virtual
Reimplemented in FairDbResultNonAgg.
Definition at line 216 of file FairDbResult.h.
View newest version in sPHENIX GitHub at line 216 of file FairDbResult.h
void FairDbResult::RegisterKey () virtual
Definition at line 939 of file FairDbResult.cxx.
View newest version in sPHENIX GitHub at line 939 of file FairDbResult.cxx
References CreateKey(), fKey, and GetNumRows().
Referenced by FairDbCache::Adopt().
Bool_t FairDbResult::ResultsFromDb () const inline
Definition at line 217 of file FairDbResult.h.
View newest version in sPHENIX GitHub at line 217 of file FairDbResult.h
References fResultsFromDb.
Referenced by FairDbTableProxy::SaveToL2Cache().
Bool_t FairDbResult::Satisfies (const ValContext & vc, const FairDb::Task & task) virtual
Definition at line 962 of file FairDbResult.cxx.
View newest version in sPHENIX GitHub at line 962 of file FairDbResult.cxx
References CanReuse(), GetNumClients(), GetValidityRec(), FairDbValidityRec::HasExpired(), FairDbValidityRec::IsCompatible(), IsExtendedContext(), and SetCanReuse().
Referenced by FairDbCache::Search().
virtual Bool_t FairDbResult::Satisfies (const string &) inline virtual
Reimplemented in FairDbResultAgg.
Definition at line 224 of file FairDbResult.h.
View newest version in sPHENIX GitHub at line 224 of file FairDbResult.h
virtual Bool_t FairDbResult::Satisfies (const FairDbValidityRec & , const string & = "") inline virtual
Reimplemented in FairDbResultNonAgg.
Definition at line 225 of file FairDbResult.h.
View newest version in sPHENIX GitHub at line 225 of file FairDbResult.h
virtual void FairDbResult::SetCanReuse (Bool_t reuse) inline virtual
Definition at line 232 of file FairDbResult.h.
View newest version in sPHENIX GitHub at line 232 of file FairDbResult.h
References fCanReuse.
Referenced by CanDelete(), FairDbTableProxy::Query(), and Satisfies().
void FairDbResult::SetResultsFromDb () inline protected
Definition at line 235 of file FairDbResult.h.
View newest version in sPHENIX GitHub at line 235 of file FairDbResult.h
References fResultsFromDb.
virtual void FairDbResult::SetTableName (const string & tableName) inline protected virtual
Definition at line 238 of file FairDbResult.h.
View newest version in sPHENIX GitHub at line 238 of file FairDbResult.h
References fTableName.
virtual void FairDbResult::SetValidityRec (const FairDbValidityRec & vRec) inline protected virtual
Definition at line 241 of file FairDbResult.h.
View newest version in sPHENIX GitHub at line 241 of file FairDbResult.h
References fEffVRec.
void FairDbResult::Streamer (FairDbBinaryFile & file) virtual
Reimplemented in FairDbResultNonAgg, and FairDbResultAgg.
Definition at line 997 of file FairDbResult.cxx.
View newest version in sPHENIX GitHub at line 997 of file FairDbResult.cxx
References fCanReuse, fEffVRec, fNumClients, fResultsFromDb, fTableName, FairDbBinaryFile::IsReading(), FairDbBinaryFile::IsWriting(), and FairDbValidityRec::Streamer().
Referenced by operator<<(), operator>>(), and FairDbResultNonAgg::Streamer().
virtual const string& FairDbResult::TableName () const inline virtual
Definition at line 218 of file FairDbResult.h.
View newest version in sPHENIX GitHub at line 218 of file FairDbResult.h
References fTableName.
Referenced by FairDbCache::Adopt(), BuildLookUpTable(), FairDbResultNonAgg::CreateKey(), FairDbValRecSet::GetTableName(), and FairDbCache::Purge().
Member Data Documentation
Bool_t FairDbResult::fCanReuse private
Definition at line 251 of file FairDbResult.h.
View newest version in sPHENIX GitHub at line 251 of file FairDbResult.h
Referenced by CanReuse(), SetCanReuse(), and Streamer().
FairDbValidityRec FairDbResult::fEffVRec private
Definition at line 252 of file FairDbResult.h.
View newest version in sPHENIX GitHub at line 252 of file FairDbResult.h
Referenced by FairDbResult(), GetValidityRecGlobal(), SetValidityRec(), and Streamer().
FairDbExceptionLog FairDbResult::fExceptionLog private
Definition at line 260 of file FairDbResult.h.
View newest version in sPHENIX GitHub at line 260 of file FairDbResult.h
Referenced by CaptureExceptionLog().
Int_t FairDbResult::fgLastID static private
Definition at line 259 of file FairDbResult.h.
View newest version in sPHENIX GitHub at line 259 of file FairDbResult.h
Int_t FairDbResult::fID private
Definition at line 250 of file FairDbResult.h.
View newest version in sPHENIX GitHub at line 250 of file FairDbResult.h
Referenced by GetID().
IndexToRow_t FairDbResult::fIndexKeys mutable private
Definition at line 253 of file FairDbResult.h.
View newest version in sPHENIX GitHub at line 253 of file FairDbResult.h
Referenced by BuildLookUpTable(), GetTableRowByIndex(), and LookUpBuilt().
const FairDbResultKey* FairDbResult::fKey private
Definition at line 254 of file FairDbResult.h.
View newest version in sPHENIX GitHub at line 254 of file FairDbResult.h
Referenced by DeRegisterKey(), GetKey(), and RegisterKey().
Int_t FairDbResult::fNumClients mutable private
Definition at line 256 of file FairDbResult.h.
View newest version in sPHENIX GitHub at line 256 of file FairDbResult.h
Referenced by Connect(), Disconnect(), GetNumClients(), Streamer(), and ~FairDbResult().
Bool_t FairDbResult::fResultsFromDb private
Definition at line 255 of file FairDbResult.h.
View newest version in sPHENIX GitHub at line 255 of file FairDbResult.h
Referenced by ResultsFromDb(), SetResultsFromDb(), and Streamer().
string FairDbResult::fSqlQualifiers private
Definition at line 258 of file FairDbResult.h.
View newest version in sPHENIX GitHub at line 258 of file FairDbResult.h
Referenced by GetSqlQualifiers().
string FairDbResult::fTableName private
Definition at line 257 of file FairDbResult.h.
View newest version in sPHENIX GitHub at line 257 of file FairDbResult.h
Referenced by FairDbResult(), SetTableName(), Streamer(), and TableName().
The documentation for this class was generated from the following files:
EicRoot/blob/master/dbase/dbInterface/FairDbResult.h
EicRoot/blob/master/dbase/dbInterface/FairDbResult.cxx