EIC Software: fun4all_coresoftware/blob/master/simulation/g4simulation/g4eval/compressor_generator.h File Reference
compressor_generator.h File Reference
#include <map>
#include <set>
#include <utility>
#include <random>
#include <vector>
#include "RtypesCore.h"
Functions
UShort_t residesIn (Float_t raw, vector< Float_t > *dict)
Float_t approx (vector< UShort_t > *order, vector< Float_t > *dict, vector< size_t > *cnt, Int_t n_entries, std::default_random_engine &generator, std::normal_distribution< double > &distribution, size_t maxNumClusters)
Int_t newLoc (vector< Int_t > *loc_vec, vector< vector< Int_t >> *loc_vec_vec)
void removeDiff (Float_t distance, Float_t min, map< Float_t, set< Float_t >> *distance_min_set_map)
void addDiff (Float_t distance, Float_t min, map< Float_t, set< Float_t >> *distance_min_set_map)
Function Documentation
void addDiff (Float_t distance, Float_t min, map< Float_t, set< Float_t >> * distance_min_set_map)
Float_t approx (vector< UShort_t > * order, vector< Float_t > * dict, vector< size_t > * cnt, Int_t n_entries, std::default_random_engine & generator, std::normal_distribution< double > & distribution, size_t maxNumClusters)
approx() compresses data generated by a normal distribution and returns the maximum absolute difference between the actual and approximated data.
Definition at line 49 of file compressor_generator.h.
View newest version in sPHENIX GitHub at line 49 of file compressor_generator.h
References addDiff(), estimate(), max, min, newLoc(), removeDiff(), and Acts::UnitConstants::s.
Int_t newLoc (vector< Int_t > * loc_vec, vector< vector< Int_t >> * loc_vec_vec)
Definition at line 141 of file compressor_generator.h.
View newest version in sPHENIX GitHub at line 141 of file compressor_generator.h
void removeDiff (Float_t distance, Float_t min, map< Float_t, set< Float_t >> * distance_min_set_map)
UShort_t residesIn (Float_t raw, vector< Float_t > * dict)
Definition at line 18 of file compressor_generator.h.
View newest version in sPHENIX GitHub at line 18 of file compressor_generator.h
References Acts::Test::at.
Referenced by DSTCompressor::compressPhi(), and DSTCompressor::compressZ().