EIC Software: lit Namespace Reference
lit Namespace Reference
Functions
litfloat ChiSq (const CbmLitTrackParam *par, const CbmLitHit *hit)
litfloat ChiSq (const CbmLitTrackParam *par, const CbmLitStripHit *hit)
litfloat ChiSq (const CbmLitTrackParam *par, const CbmLitPixelHit *hit)
Int_t NDF (const CbmLitTrack *track)
void SaveCanvasAsImage (TCanvas *c, const std::string &dir)
string FindAndReplace (const string &name, const string &oldSubstr, const string &newSubstr)
vector< string > Split (const string &name, char delimiter)
template<class T >
string ToString (const T &value)
template<class T >
string NumberToString (const T &value, int precision=1)
template<class T >
int Sign (const T &x)
Function Documentation
litfloat lit::ChiSq (const CbmLitTrackParam * par, const CbmLitHit * hit)
Definition at line 15 of file CbmLitMath.cxx.
View newest version in sPHENIX GitHub at line 15 of file CbmLitMath.cxx
litfloat lit::ChiSq (const CbmLitTrackParam * par, const CbmLitStripHit * hit)
Definition at line 28 of file CbmLitMath.cxx.
View newest version in sPHENIX GitHub at line 28 of file CbmLitMath.cxx
litfloat lit::ChiSq (const CbmLitTrackParam * par, const CbmLitPixelHit * hit)
Definition at line 47 of file CbmLitMath.cxx.
View newest version in sPHENIX GitHub at line 47 of file CbmLitMath.cxx
References Acts::UnitConstants::e.
string lit::FindAndReplace (const string & name, const string & oldSubstr, const string & newSubstr)
Definition at line 20 of file CbmLitUtils.cxx.
View newest version in sPHENIX GitHub at line 20 of file CbmLitUtils.cxx
References name.
int lit::NDF (const CbmLitTrack * track)
Definition at line 67 of file CbmLitMath.cxx.
View newest version in sPHENIX GitHub at line 67 of file CbmLitMath.cxx
template<class T > string lit::NumberToString (const T & value, int precision = 1)
Definition at line 27 of file CbmLitUtils.h.
View newest version in sPHENIX GitHub at line 27 of file CbmLitUtils.h
References precision, and value.
Referenced by CbmRichGeoTest::DrawSummaryPlotsTemp(), and CbmRichGeoTest::FitH1OneOverX().
void lit::SaveCanvasAsImage (TCanvas * c, const std::string & dir)
Definition at line 9 of file CbmLitUtils.cxx.
View newest version in sPHENIX GitHub at line 9 of file CbmLitUtils.cxx
Referenced by CbmRichUrqmdTest::SaveCanvasToImage(), and CbmRichGeoTest::SaveCanvasToImage().
template<class T > int lit::Sign (const T & x)
Definition at line 42 of file CbmLitUtils.h.
View newest version in sPHENIX GitHub at line 42 of file CbmLitUtils.h
References T.
Referenced by EicIdealTrackingCode::Exec(), FairTrackParH::FairTrackParH(), FairTrackParP::FairTrackParP(), FairGeaneUtil::FromMarsToSD(), GeaneTrackRep::GeaneTrackRep(), PndPidCorrelator::GetTrackInfo(), FairTrackParP::SetTrackPar(), and FairTrackParH::SetTrackPar().
vector< string > lit::Split (const string & name, char delimiter)
Definition at line 31 of file CbmLitUtils.cxx.
View newest version in sPHENIX GitHub at line 31 of file CbmLitUtils.cxx
template<class T > string lit::ToString (const T & value)
Definition at line 18 of file CbmLitUtils.h.
View newest version in sPHENIX GitHub at line 18 of file CbmLitUtils.h
References T.