EIC Software: EtmPalette Class Reference
EtmPalette Class Reference
#include <EicToyModel/blob/master/include/EtmPalette.h>
Public Member Functions
EtmPalette ()
~EtmPalette ()
bool AddEntry (const char *tag, int color)
int GetColor (const char *tag) const
const char * GetTag (int color) const
Private Member Functions
bool Exists (const char *tag) const
bool Exists (int color) const
Private Attributes
std::map< TString, int > mColors
std::map< int, TString > mTags
Detailed Description
Definition at line 32 of file EtmPalette.h.
View newest version in sPHENIX GitHub at line 32 of file EtmPalette.h
Constructor & Destructor Documentation
EtmPalette::EtmPalette ()
Definition at line 9 of file EtmPalette.cc.
View newest version in sPHENIX GitHub at line 9 of file EtmPalette.cc
References _GAP_COLOR_, _MARKER_, and AddEntry().
EtmPalette::~EtmPalette () inline
Definition at line 35 of file EtmPalette.h.
View newest version in sPHENIX GitHub at line 35 of file EtmPalette.h
Member Function Documentation
bool EtmPalette::AddEntry (const char * tag, int color)
Definition at line 58 of file EtmPalette.cc.
View newest version in sPHENIX GitHub at line 58 of file EtmPalette.cc
References color, mColors, mTags, printf(), and release::tag().
Referenced by EtmPalette().
bool EtmPalette::Exists (const char * tag) const inline private
Definition at line 43 of file EtmPalette.h.
View newest version in sPHENIX GitHub at line 43 of file EtmPalette.h
References mColors.
Referenced by GetColor(), and GetTag().
bool EtmPalette::Exists (int color) const inline private
Definition at line 44 of file EtmPalette.h.
View newest version in sPHENIX GitHub at line 44 of file EtmPalette.h
int EtmPalette::GetColor (const char * tag) const inline
Definition at line 39 of file EtmPalette.h.
View newest version in sPHENIX GitHub at line 39 of file EtmPalette.h
References Exists(), and mColors.
const char* EtmPalette::GetTag (int color) const inline
Definition at line 40 of file EtmPalette.h.
View newest version in sPHENIX GitHub at line 40 of file EtmPalette.h
References Exists(), and mTags.
Member Data Documentation
std::map<TString, int> EtmPalette::mColors private
Definition at line 44 of file EtmPalette.h.
View newest version in sPHENIX GitHub at line 44 of file EtmPalette.h
Referenced by AddEntry(), Exists(), and GetColor().
std::map<int, TString> EtmPalette::mTags private
Definition at line 48 of file EtmPalette.h.
View newest version in sPHENIX GitHub at line 48 of file EtmPalette.h
Referenced by AddEntry(), and GetTag().
The documentation for this class was generated from the following files:
EicToyModel/blob/master/include/EtmPalette.h
EicToyModel/blob/master/source/EtmPalette.cc