EIC Software: eicsmeardetectors/blob/master/SmearPerfectDetector.cxx File Reference
SmearPerfectDetector.cxx File Reference
#include "eicsmear/erhic/VirtualParticle.h"
#include "eicsmear/smear/Acceptance.h"
#include "eicsmear/smear/Device.h"
#include "eicsmear/smear/Detector.h"
#include "eicsmear/smear/Smearer.h"
#include "eicsmear/smear/ParticleMCS.h"
#include "eicsmear/smear/PerfectID.h"
Functions
static double etaToTheta (const double eta)
Smear::Detector BuildPerfectDetector ()
Function Documentation
Smear::Detector BuildPerfectDetector ()
Definition at line 25 of file SmearPerfectDetector.cxx.
View newest version in sPHENIX GitHub at line 25 of file SmearPerfectDetector.cxx
References Smear::Smearer::Accept, Smear::Detector::AddDevice(), Smear::Acceptance::AddZone(), etaToTheta(), Smear::kE, Smear::kP, Smear::kPhi, Smear::kTheta, momentum, phi, pid, Smear::Detector::SetEventKinematicsCalculator(), and theta().
Referenced by BuildByName().
static double etaToTheta (const double eta) static
Definition at line 18 of file SmearPerfectDetector.cxx.
View newest version in sPHENIX GitHub at line 18 of file SmearPerfectDetector.cxx
References v.