EIC Software: eic-smear/blob/master/src/erhic/BuildTree.cxx File Reference
BuildTree.cxx File Reference
#include <string>
#include <TString.h>
#include <TSystem.h>
#include "eicsmear/erhic/Forester.h"
#include "eicsmear/erhic/File.h"
Functions
Long64_t BuildTree (const std::string &inputFileName, const std::string &outputDirName, const Long64_t maxEvent, const std::string &logFileName)
Detailed Description
Defines the main BuildTree function.
Author
Thomas Burton
Date
2011-06-24
Copyright
2011 Brookhaven National Lab
Definition in file BuildTree.cxx.
Function Documentation
Long64_t BuildTree (const std::string & inputFileName, const std::string & outputDirName, const Long64_t maxEvent, const std::string & logFileName)
This is an example function to generate ROOT files. It can be used "out of the box". If more control over the output is desired, then the settings of the Forester can be tweaked to do so.
Definition at line 25 of file BuildTree.cxx.
View newest version in sPHENIX GitHub at line 25 of file BuildTree.cxx
References erhic::FileType::CreateLogReader(), erhic::LogReader::Extract(), erhic::Forester::GetFileType(), erhic::LogReaderFactory::GetInstance(), erhic::LogReaderFactory::Locate(), erhic::Forester::Plant(), reader(), erhic::LogReader::Save(), erhic::Forester::SetBeVerbose(), erhic::Forester::SetBranchName(), erhic::Forester::SetInputFileName(), erhic::Forester::SetMaxNEvents(), erhic::Forester::SetMessageInterval(), and erhic::Forester::SetOutputFileName().
Referenced by build(), ConvertFile(), main(), and make_tree().