EIC Software: inputParameters Class Reference
inputParameters Class Reference
#include <estarlight/blob/master/include/inputParameters.h>
Public Member Functions
inputParameters ()
~inputParameters ()
bool init ()
bool configureFromFile (const std::string &configFileName="./config/slight.in")
std::string baseFileName () const
int targetBeamZ () const
returns atomic number of beam particle 2
unsigned int targetBeamA () const
returns atomic mass number of beam particle 2
double targetLorentzGamma () const
returns Lorentz gamma factor of source in target frame
double beamLorentzGamma () const
returns Lorentz gamma factor of both beams in beam CMS frame
double electronBeamLorentzGamma () const
returns Lorentz gamma factor of beam 1 in collider frame
double targetBeamLorentzGamma () const
returns Lorentz gamma factor of beam 2 in collider frame
double rap_CM () const
returns center-of-mass rapidity
double targetMaxPhotonEnergy () const
returns maximum photon energy
double cmsMaxPhotonEnergy () const
returns maximum photon energy
double targetMinPhotonEnergy () const
returns maximum photon energy
double cmsMinPhotonEnergy () const
returns maximum photon energy
double maxW () const
returns maximum mass W of produced hadronic system [GeV/c^2]
double minW () const
returns minimum mass W of produced hadronic system [GeV/c^2]
double maxW_GP () const
returns maximum W of produced virtual photon and nucleon system [GeV/c^2]
double minW_GP () const
returns minimum W of produced virtual photon and nucleon system [GeV/c^2]
unsigned int nmbWBins () const
returns number of W bins in lookup table
double maxRapidity () const
returns maximum absolute value of rapidity
unsigned int nmbRapidityBins () const
returns number of rapidity bins in lookup table
unsigned int nmbEnergyBins () const
return the number of Egamma bins for eSTARlight lookup
bool ptCutEnabled () const
returns cut in pt
double ptCutMin () const
returns minimum pt
double ptCutMax () const
returns maximum pt
bool etaCutEnabled () const
returns cut in eta
double etaCutMin () const
returns minimum eta
double etaCutMax () const
returns maximum eta
int productionMode () const
returns production mode
unsigned int nmbEvents () const
returns total number of events to generate
int prodParticleId () const
returns PDG particle ID of produced particle
int randomSeed () const
returns seed for random number generator
int beamBreakupMode () const
returns breakup mode for beam particles
bool interferenceEnabled () const
returns whether interference is taken into account
double interferenceStrength () const
returns percentage of interference
double maxPtInterference () const
returns maximum p_T for interference calculation [GeV/c]
int nmbPtBinsInterference () const
returns number of p_T bins for interference calculation
double ptBinWidthInterference () const
returns width of p_T bins for interference calculation [GeV/c]
double minGammaEnergy () const
returns minimum gamma energy in case of photo nuclear processes [GeV]
double maxGammaEnergy () const
returns maximum gamma energy in case of photo nuclear processes [GeV]
double minGammaQ2 () const
return minimum gamma virtuality
double maxGammaQ2 () const
return maximum gamma virtuality
bool fixedQ2Range () const
return state of Q2 range
unsigned int nmbGammaQ2Bins () const
return number of gamma q2 bins
std::string pythiaParams () const
returns parameters to be passed to pythia
bool defaultFullEventRecord () const
returns if the full default event record should be printed
bool pythiaFullEventRecord () const
returns if the full pythia event record should be printed
bool hepmc3FullEventRecord () const
returns if the full hepmc3 event record should be printed
bool lundFullEventRecord () const
returns if the full lund event record should be printed
int outputFormat () const
returns value according to desired output format. 0 for only default, 1 for Pythia, 2 for HepMC, 3 for lund
bool backwardsProduction () const
returns if backwards production
int xsecCalcMethod () const
returns the method used for the x-sec calculation
double axionMass () const
returns axion mass //AXION HACK
int bslopeDefinition () const
returns the definition of b-slope
double bslopeValue () const
returns the value of b-slope
int impulseVM () const
returns the impulseVM value
int quantumGlauber () const
returns the quantum glauber value
starlightConstants::particleTypeEnum prodParticleType () const
returns type of produced particle
starlightConstants::decayTypeEnum prodParticleDecayType () const
returns decay type of produced particle
starlightConstants::interactionTypeEnum interactionType () const
returns interaction type
double protonEnergy () const
double electronEnergy () const
double inputBranchingRatio () const
double targetRadius () const
void setBaseFileName (std::string v)
void setTargetBeamZ (unsigned int v)
sets atomic number of beam particle 2
void setTargetBeamA (unsigned int v)
sets atomic mass number of beam particle 2
void setTargetLorentzGamma (double v)
sets Lorentz gamma factor of both beams in beam CMS frame
void setBeamLorentzGamma (double v)
sets Lorentz gamma factor of both beams in beam CMS frame
void setElectronBeamLorentzGamma (double v)
void setRapCM (double v)
sets center-of-mass rapidity
void setMaxW (double v)
sets maximum mass W of produced hadronic system [GeV/c^2]
void setMinW (double v)
sets minimum mass W of produced hadronic system [GeV/c^2]
void setmaxW_GP (double v)
sets maximum mass W of produced virtual photon and nucleon system [GeV/c^2]
void setminW_GP (double v)
sets minimum mass W of produced virtual photon and nucleon system [GeV/c^2]
void setNmbWBins (unsigned int v)
sets number of W bins in lookup table
void setMaxRapidity (double v)
sets maximum absolute value of rapidity
void setNmbRapidityBins (unsigned int v)
sets number of rapidity bins in lookup table
void setNmbEgaBins (unsigned int v)
sets number of Ega bins for eSTARlight
void setPtCutEnabled (bool v)
sets cut in pt
void setPtCutMin (double v)
sets minimum pt
void setPtCutMax (double v)
sets maximum pt
void setEtaCutEnabled (bool v)
sets cut in eta
void setEtaCutMin (double v)
sets minimum eta
void setEtaCutMax (double v)
sets maximum eta
void setProductionMode (int v)
sets production mode
void setNmbEvents (unsigned int v)
sets total number of events to generate
void setProdParticleId (int v)
sets PDG particle ID of produced particle
void setRandomSeed (int v)
sets seed for random number generator
void setBeamBreakupMode (int v)
sets breakup mode for beam particles
void setInterferenceEnabled (bool v)
sets whether interference is taken into account
void setInterferenceStrength (double v)
sets percentage of interference
void setMaxPtInterference (double v)
sets maximum p_T for voiderference calculation [GeV/c]
void setNmbPtBinsInterference (int v)
sets number of p_T bins for interference calculation
void setPtBinWidthInterference (double v)
sets width of p_T bins for voiderference calculation [GeV/c]
void setMinGammaEnergy (double v)
sets minimum gamma energy in case of photo nuclear processes [GeV]
void setMaxGammaEnergy (double v)
sets maximum gamma energy in case of photo nuclear processes [GeV]
void setMinGammaQ2 (double v)
sets minimum gamma virtuality in case of photo nuclear processes [GeV]
void setMaxGammaQ2 (double v)
sets maximum gamma virtuality in case of photo nuclear processes [GeV]
void setPythiaParams (std::string v)
sets parameters to be passed to pythia
void setOutputFormat (int v)
sets output file format
void setBackwardsProduction (bool v)
sets backwards production
void setXsecCalcMethod (int v)
sets the method used for the x-sec calculation
void setAxionMass (double v)
sets axion mass //AXION HACK
void setbslopeDefinition (int v)
sets the definition of b slope
void setbslopeValue (double v)
sets the value of b slope
void setimpulseVM (int v)
sets the value of _impulseVM
void setquantumGlauber (int v)
sets the value of quantum_glauber
void setProdParticleType (starlightConstants::particleTypeEnum v)
sets type of produced particle
void setProdParticleDecayType (starlightConstants::decayTypeEnum v)
sets decay type of produced particle
void setInteractionType (starlightConstants::interactionTypeEnum v)
sets interaction type
void setProtonEnergy (double v)
sets proton energy
void setElectronEnergy (double v)
sets electron energy
template<typename T >
bool setParameter (std::string expression)
std::ostream & print (std::ostream &out) const
prints parameter summary
std::ostream & write (std::ostream &out) const
writes parameters back to an ostream
std::string parameterValueKey () const
Generates key for the current parameters.
Private Attributes
std::string _configFileName
path to configuration file (default = ./config/slight.in)
parameter< std::string,
NO_VALIDITY_CHECK > _baseFileName
parameter< int, VALIDITY_CHECK > _targetBeamZ
atomic number of beam particle 2
parameter< unsigned int,
VALIDITY_CHECK > _targetBeamA
atomic mass number of beam particle 2
parameter< double, VALIDITY_CHECK > _electronBeamLorentzGamma
Lorentz gamma factor of beam 1 in collider frame.
parameter< double, VALIDITY_CHECK > _targetBeamLorentzGamma
Lorentz gamma factor of beam 2 in collider frame.
parameter< double, VALIDITY_CHECK > _maxW
maximum mass W of produced hadronic system [GeV/c^2]
parameter< double, VALIDITY_CHECK > _minW
minimum mass W of produced hadronic system; if set to -1 default value is taken [GeV/c^2]
parameter< double, VALIDITY_CHECK > _maxW_GP
maximum mass W of produced virtual photon and nucleon system, has no maximum limit [GeV/c^2]
parameter< double, VALIDITY_CHECK > _minW_GP
minimum mass W of produced virtual photon and nucleon system, should be no greater than COM energy of source + traget or code will terminate [GeV/c^2]
parameter< unsigned int,
VALIDITY_CHECK > _nmbWBins
number of W bins in lookup table
parameter< double, VALIDITY_CHECK > _maxRapidity
maximum absolute value of rapidity
parameter< unsigned int,
VALIDITY_CHECK > _nmbRapidityBins
number of rapidity bins in lookup table
parameter< unsigned int,
VALIDITY_CHECK > _nmbEnergyBins
number of Egamma bins in lookup table
parameter< bool, VALIDITY_CHECK > _ptCutEnabled
en/disables cut in pt
parameter< double, VALIDITY_CHECK > _ptCutMin
minimum pt, if cut is enabled
parameter< double, VALIDITY_CHECK > _ptCutMax
maximum pt, if cut is enabled
parameter< bool, VALIDITY_CHECK > _etaCutEnabled
en/disables cut in eta
parameter< double, VALIDITY_CHECK > _etaCutMin
minimum eta, if cut is enabled
parameter< double, VALIDITY_CHECK > _etaCutMax
maximum eta, if cut is enabled
parameter< unsigned int,
VALIDITY_CHECK > _productionMode
production mode
parameter< unsigned int,
VALIDITY_CHECK > _nmbEventsTot
total number of events to generate
parameter< unsigned int,
VALIDITY_CHECK > _prodParticleId
PDG particle ID of produced particle.
parameter< unsigned int,
VALIDITY_CHECK > _randomSeed
parameter< unsigned int,
VALIDITY_CHECK > _beamBreakupMode
breakup mode for beam particles
parameter< bool, VALIDITY_CHECK > _interferenceEnabled
if VALIDITY_CHECK, interference is taken into account
parameter< double, VALIDITY_CHECK > _interferenceStrength
percentage of interference: from 0 = none to 1 = full
parameter< double, VALIDITY_CHECK > _maxPtInterference
maximum p_T for interference calculation [GeV/c]
parameter< unsigned int,
VALIDITY_CHECK > _nmbPtBinsInterference
number of p_T bins for interference calculation
parameter< double, VALIDITY_CHECK > _ptBinWidthInterference
width of p_T bins for interference calculation [GeV/c]
parameter< double, VALIDITY_CHECK > _protonEnergy
parameter< double, VALIDITY_CHECK > _electronEnergy
parameter< double, VALIDITY_CHECK > _minGammaEnergy
minimum gamma energy in case of photo nuclear processes [GeV]
parameter< double, VALIDITY_CHECK > _maxGammaEnergy
maximum gamma energy in case of photo nuclear processes [GeV]
parameter< double, VALIDITY_CHECK > _minGammaQ2
minimum gamma Q2 in case of photo nuclear processes
parameter< double, VALIDITY_CHECK > _maxGammaQ2
maximum gamma Q2 in case of photo nuclear processes
parameter< unsigned int,
VALIDITY_CHECK > _nmbGammaQ2Bins
number of gamma q2 bins
parameter< std::string,
NO_VALIDITY_CHECK > _pythiaParams
semi-colon separated parameters to pass to pythia, e.g. "mstj(1)=0;paru(13)=0.1"
parameter< int, NO_VALIDITY_CHECK > _outputFormat
identifier of output format
parameter< bool,
NO_VALIDITY_CHECK > _backwardsProduction
parameter< unsigned int,
VALIDITY_CHECK > _xsecCalcMethod
Select x-sec calc method. (0 is standard starlight method, 1 must be used for assym. collisions (e.g. p-A), but is slow)
parameter< double, VALIDITY_CHECK > _axionMass
parameter< unsigned int,
VALIDITY_CHECK > _bslopeDefinition
Axion mass//AXION HACK.
parameter< double, VALIDITY_CHECK > _bslopeValue
Value of slope parameter when _bslopeDefinition is set to 1.
parameter< unsigned int,
VALIDITY_CHECK > _impulseVM
Optional parameter to use impulse approximation (no nuclear effects) for VM cross section.
parameter< unsigned int,
VALIDITY_CHECK > _quantumGlauber
Optional parameter. Set = 1 to use Quantum Glauber calculation, rather than Classical Glauber.
starlightConstants::particleTypeEnum _particleType
starlightConstants::decayTypeEnum _decayType
starlightConstants::interactionTypeEnum _interactionType
double _targetLorentzGamma
Lorentz gamma factor of the source in target frame, not an input parameter.
double _beamLorentzGamma
Lorentz gamma factor of the beams in CMS frame, not an input parameter.
double _rap_CM
double _targetR
double _cmsMaxPhotonEnergy
double _cmsMinPhotonEnergy
double _targetMaxPhotonEnergy
double _targetMinPhotonEnergy
double _inputBranchingRatio
Branching ratio defined for each channel.
bool _fixedQ2Range
inputParser _ip
Detailed Description
Definition at line 171 of file inputParameters.h.
View newest version in sPHENIX GitHub at line 171 of file inputParameters.h
Constructor & Destructor Documentation
inputParameters::inputParameters ()
Definition at line 53 of file inputParameters.cpp.
View newest version in sPHENIX GitHub at line 53 of file inputParameters.cpp
References _axionMass, _backwardsProduction, _baseFileName, _beamBreakupMode, _bslopeDefinition, _bslopeValue, _electronBeamLorentzGamma, _etaCutEnabled, _etaCutMax, _etaCutMin, _impulseVM, _interferenceEnabled, _interferenceStrength, _ip, _maxGammaEnergy, _maxGammaQ2, _maxPtInterference, _maxRapidity, _maxW, _maxW_GP, _minGammaEnergy, _minGammaQ2, _minW, _minW_GP, _nmbEnergyBins, _nmbEventsTot, _nmbGammaQ2Bins, _nmbPtBinsInterference, _nmbRapidityBins, _nmbWBins, _outputFormat, _prodParticleId, _productionMode, _ptCutEnabled, _ptCutMax, _ptCutMin, _pythiaParams, _quantumGlauber, _randomSeed, _targetBeamA, _targetBeamLorentzGamma, _targetBeamZ, _xsecCalcMethod, and inputParser::addParameter().
inputParameters::~inputParameters ()
Definition at line 161 of file inputParameters.cpp.
View newest version in sPHENIX GitHub at line 161 of file inputParameters.cpp
Member Function Documentation
double inputParameters::axionMass () const inline
returns axion mass //AXION HACK
Definition at line 231 of file inputParameters.h.
View newest version in sPHENIX GitHub at line 231 of file inputParameters.h
References _axionMass, and parameter< T, validate >::value().
Referenced by Gammagammasingle::Gammagammasingle().
bool inputParameters::backwardsProduction () const inline
returns if backwards production
Definition at line 229 of file inputParameters.h.
View newest version in sPHENIX GitHub at line 229 of file inputParameters.h
References _backwardsProduction, and parameter< T, validate >::value().
Referenced by e_narrowResonanceCrossSection::e_narrowResonanceCrossSection(), and Gammaavectormeson::Gammaavectormeson().
std::string inputParameters::baseFileName () const inline
Definition at line 180 of file inputParameters.h.
View newest version in sPHENIX GitHub at line 180 of file inputParameters.h
References _baseFileName, and parameter< T, validate >::value().
Referenced by e_starlightStandalone::init(), e_starlight::init(), hepMC3Writer::initWriter(), e_starlightStandalone::run(), and write().
int inputParameters::beamBreakupMode () const inline
returns breakup mode for beam particles
Definition at line 211 of file inputParameters.h.
View newest version in sPHENIX GitHub at line 211 of file inputParameters.h
References _beamBreakupMode, and parameter< T, validate >::value().
Referenced by write().
double inputParameters::beamLorentzGamma () const inline
returns Lorentz gamma factor of both beams in beam CMS frame
Definition at line 185 of file inputParameters.h.
View newest version in sPHENIX GitHub at line 185 of file inputParameters.h
References _beamLorentzGamma.
Referenced by e_narrowResonanceCrossSection::e_narrowResonanceCrossSection(), e_wideResonanceCrossSection::e_wideResonanceCrossSection(), Gammaavectormeson::Gammaavectormeson(), Gammagammasingle::Gammagammasingle(), and write().
int inputParameters::bslopeDefinition () const inline
returns the definition of b-slope
Definition at line 232 of file inputParameters.h.
View newest version in sPHENIX GitHub at line 232 of file inputParameters.h
References _bslopeDefinition, and parameter< T, validate >::value().
Referenced by Gammaavectormeson::Gammaavectormeson().
double inputParameters::bslopeValue () const inline
returns the value of b-slope
Definition at line 233 of file inputParameters.h.
View newest version in sPHENIX GitHub at line 233 of file inputParameters.h
References _bslopeValue, and parameter< T, validate >::value().
Referenced by Gammaavectormeson::Gammaavectormeson().
double inputParameters::cmsMaxPhotonEnergy () const inline
returns maximum photon energy
Definition at line 190 of file inputParameters.h.
View newest version in sPHENIX GitHub at line 190 of file inputParameters.h
References _cmsMaxPhotonEnergy.
Referenced by e_narrowResonanceCrossSection::e_narrowResonanceCrossSection(), and Gammaavectormeson::Gammaavectormeson().
double inputParameters::cmsMinPhotonEnergy () const inline
returns maximum photon energy
Definition at line 192 of file inputParameters.h.
View newest version in sPHENIX GitHub at line 192 of file inputParameters.h
References _cmsMinPhotonEnergy.
Referenced by e_narrowResonanceCrossSection::e_narrowResonanceCrossSection(), and Gammaavectormeson::Gammaavectormeson().
bool inputParameters::configureFromFile (const std::string & configFileName = "./config/slight.in")
Definition at line 167 of file inputParameters.cpp.
View newest version in sPHENIX GitHub at line 167 of file inputParameters.cpp
References _ip, inputParser::parseFile(), printInfo, printWarn, and inputParser::validateParameters().
Referenced by e_starlightStandalone::init().
bool inputParameters::defaultFullEventRecord () const inline
returns if the full default event record should be printed
Definition at line 224 of file inputParameters.h.
View newest version in sPHENIX GitHub at line 224 of file inputParameters.h
References _outputFormat, and parameter< T, validate >::value().
double inputParameters::electronBeamLorentzGamma () const inline
returns Lorentz gamma factor of beam 1 in collider frame
Definition at line 186 of file inputParameters.h.
View newest version in sPHENIX GitHub at line 186 of file inputParameters.h
References _electronBeamLorentzGamma, and parameter< T, validate >::value().
Referenced by e_narrowResonanceCrossSection::e_narrowResonanceCrossSection(), init(), hepMC3Writer::initBeamHepMC3(), eventFileWriter::writeInit(), and eventFileWriter::writeInitLUND().
double inputParameters::electronEnergy () const inline
Definition at line 240 of file inputParameters.h.
View newest version in sPHENIX GitHub at line 240 of file inputParameters.h
References _electronEnergy, and parameter< T, validate >::value().
Referenced by e_narrowResonanceCrossSection::e_narrowResonanceCrossSection(), e_wideResonanceCrossSection::e_wideResonanceCrossSection(), and Gammaavectormeson::Gammaavectormeson().
bool inputParameters::etaCutEnabled () const inline
returns cut in eta
Definition at line 204 of file inputParameters.h.
View newest version in sPHENIX GitHub at line 204 of file inputParameters.h
References _etaCutEnabled, and parameter< T, validate >::value().
Referenced by eventChannel::eventChannel(), and write().
double inputParameters::etaCutMax () const inline
returns maximum eta
Definition at line 206 of file inputParameters.h.
View newest version in sPHENIX GitHub at line 206 of file inputParameters.h
References _etaCutMax, and parameter< T, validate >::value().
Referenced by eventChannel::eventChannel(), and write().
double inputParameters::etaCutMin () const inline
returns minimum eta
Definition at line 205 of file inputParameters.h.
View newest version in sPHENIX GitHub at line 205 of file inputParameters.h
References _etaCutMin, and parameter< T, validate >::value().
Referenced by eventChannel::eventChannel(), and write().
bool inputParameters::fixedQ2Range () const inline
return state of Q2 range
Definition at line 221 of file inputParameters.h.
View newest version in sPHENIX GitHub at line 221 of file inputParameters.h
References _fixedQ2Range.
Referenced by e_narrowResonanceCrossSection::e_narrowResonanceCrossSection(), e_wideResonanceCrossSection::e_wideResonanceCrossSection(), and eventFileWriter::writeInit().
bool inputParameters::hepmc3FullEventRecord () const inline
returns if the full hepmc3 event record should be printed
Definition at line 226 of file inputParameters.h.
View newest version in sPHENIX GitHub at line 226 of file inputParameters.h
References _outputFormat, and parameter< T, validate >::value().
Referenced by e_starlightStandalone::run().
int inputParameters::impulseVM () const inline
returns the impulseVM value
Definition at line 234 of file inputParameters.h.
View newest version in sPHENIX GitHub at line 234 of file inputParameters.h
References _impulseVM, and parameter< T, validate >::value().
Referenced by photonNucleusCrossSection::photonNucleusCrossSection(), and eventFileWriter::writeInit().
bool inputParameters::init ()
Definition at line 188 of file inputParameters.cpp.
View newest version in sPHENIX GitHub at line 188 of file inputParameters.cpp
References _axionMass, _beamLorentzGamma, _cmsMaxPhotonEnergy, _cmsMinPhotonEnergy, _decayType, _electronEnergy, _fixedQ2Range, _inputBranchingRatio, _interactionType, _interferenceEnabled, _maxGammaQ2, _maxW, _maxW_GP, _minGammaQ2, _minW, _minW_GP, _particleType, _prodParticleId, _productionMode, _protonEnergy, _ptBinWidthInterference, _rap_CM, _targetLorentzGamma, _targetMaxPhotonEnergy, _targetMinPhotonEnergy, _targetR, starlightConstants::A2, starlightConstants::a2Mass, starlightConstants::a2Width, starlightConstants::AXION, starlightConstants::E_PHOTONPOMERONNARROW, starlightConstants::E_PHOTONPOMERONWIDE, electronBeamLorentzGamma(), starlightConstants::ETA, starlightConstants::ETAC, starlightConstants::etaCMass, starlightConstants::etaCWidth, starlightConstants::etaMass, starlightConstants::ETAPRIME, starlightConstants::etaPrimeMass, starlightConstants::etaPrimeWidth, starlightConstants::etaWidth, starlightConstants::F0, starlightConstants::f0BrPiPi, starlightConstants::f0Mass, starlightConstants::f0Width, F2, starlightConstants::f2BrPiPi, starlightConstants::f2Mass, starlightConstants::F2PRIME, starlightConstants::f2PrimeBrKK, starlightConstants::f2PrimeMass, starlightConstants::f2PrimeWidth, starlightConstants::f2Width, starlightConstants::JPSI, starlightConstants::JPSI2S, starlightConstants::JPSI2S_ee, starlightConstants::JPSI2S_mumu, starlightConstants::JPSI_ee, starlightConstants::JPSI_mumu, starlightConstants::JpsiBree, starlightConstants::JpsiBrmumu, starlightConstants::JpsiMass, starlightConstants::JpsiWidth, starlightConstants::kaonChargedMass, mass, maxPtInterference(), starlightConstants::mel, starlightConstants::NARROWVMDEFAULT, nmbPtBinsInterference(), starlightConstants::OMEGA, starlightConstants::OMEGA_pi0gamma, starlightConstants::OmegaBrPi0Gamma, starlightConstants::OmegaBrPiPi, starlightConstants::OmegaMass, starlightConstants::OmegaWidth, starlightConstants::PHI, starlightConstants::PhiBrKK, starlightConstants::PhiMass, starlightConstants::PhiWidth, starlightConstants::PHOTONPHOTON, starlightConstants::PHOTONPOMERONINCOHERENT, starlightConstants::PHOTONPOMERONNARROW, starlightConstants::PHOTONPOMERONWIDE, starlightConstants::PHOTONUCLEARDOUBLE, starlightConstants::PHOTONUCLEARSINGLE, starlightConstants::PHOTONUCLEARSINGLEPA, starlightConstants::PHOTONUCLEARSINGLEPAPY, starlightConstants::pi, starlightConstants::pionChargedMass, printInfo, printWarn, prodParticleId(), productionMode(), starlightConstants::protonMass, starlightConstants::Psi2SBree, starlightConstants::Psi2SBrmumu, starlightConstants::Psi2SMass, starlightConstants::Psi2SWidth, starlightConstants::RHO, starlightConstants::rho0BrPiPi, starlightConstants::rho0Mass, starlightConstants::rho0Width, starlightConstants::RHOZEUS, starlightConstants::SINGLEMESON, targetBeamA(), targetBeamLorentzGamma(), targetBeamZ(), starlightConstants::UPSILON, starlightConstants::Upsilon1SBree, starlightConstants::Upsilon1SBrmumu, starlightConstants::Upsilon1SMass, starlightConstants::Upsilon1SWidth, starlightConstants::UPSILON2S, starlightConstants::UPSILON2S_ee, starlightConstants::UPSILON2S_mumu, starlightConstants::Upsilon2SBree, starlightConstants::Upsilon2SBrmumu, starlightConstants::Upsilon2SMass, starlightConstants::Upsilon2SWidth, starlightConstants::UPSILON3S, starlightConstants::UPSILON3S_ee, starlightConstants::UPSILON3S_mumu, starlightConstants::Upsilon3SBree, starlightConstants::Upsilon3SBrmumu, starlightConstants::Upsilon3SMass, starlightConstants::Upsilon3SWidth, starlightConstants::UPSILON_ee, starlightConstants::UPSILON_mumu, parameter< T, validate >::value(), starlightConstants::WIDEVMDEFAULT, width(), and starlightConstants::ZOVERZ03.
Referenced by e_starlightStandalone::init().
double inputParameters::inputBranchingRatio () const inline
Definition at line 241 of file inputParameters.h.
View newest version in sPHENIX GitHub at line 241 of file inputParameters.h
References _inputBranchingRatio.
Referenced by e_starlightStandalone::run().
starlightConstants::interactionTypeEnum inputParameters::interactionType () const inline
returns interaction type
Definition at line 238 of file inputParameters.h.
View newest version in sPHENIX GitHub at line 238 of file inputParameters.h
References _interactionType.
Referenced by e_starlight::createEventChannel(), and e_starlight::init().
bool inputParameters::interferenceEnabled () const inline
returns whether interference is taken into account
Definition at line 212 of file inputParameters.h.
View newest version in sPHENIX GitHub at line 212 of file inputParameters.h
References _interferenceEnabled, and parameter< T, validate >::value().
Referenced by Gammaavectormeson::Gammaavectormeson(), and write().
double inputParameters::interferenceStrength () const inline
returns percentage of interference
Definition at line 213 of file inputParameters.h.
View newest version in sPHENIX GitHub at line 213 of file inputParameters.h
References _interferenceStrength, and parameter< T, validate >::value().
Referenced by write().
bool inputParameters::lundFullEventRecord () const inline
returns if the full lund event record should be printed
Definition at line 227 of file inputParameters.h.
View newest version in sPHENIX GitHub at line 227 of file inputParameters.h
References _outputFormat, and parameter< T, validate >::value().
Referenced by e_starlightStandalone::run().
double inputParameters::maxGammaEnergy () const inline
returns maximum gamma energy in case of photo nuclear processes [GeV]
Definition at line 218 of file inputParameters.h.
View newest version in sPHENIX GitHub at line 218 of file inputParameters.h
References _maxGammaEnergy, and parameter< T, validate >::value().
double inputParameters::maxGammaQ2 () const inline
return maximum gamma virtuality
Definition at line 220 of file inputParameters.h.
View newest version in sPHENIX GitHub at line 220 of file inputParameters.h
References _maxGammaQ2, and parameter< T, validate >::value().
Referenced by e_narrowResonanceCrossSection::e_narrowResonanceCrossSection(), e_wideResonanceCrossSection::e_wideResonanceCrossSection(), write(), and eventFileWriter::writeInit().
double inputParameters::maxPtInterference () const inline
returns maximum p_T for interference calculation [GeV/c]
Definition at line 214 of file inputParameters.h.
View newest version in sPHENIX GitHub at line 214 of file inputParameters.h
References _maxPtInterference, and parameter< T, validate >::value().
Referenced by Gammaavectormeson::Gammaavectormeson(), init(), and write().
double inputParameters::maxRapidity () const inline
returns maximum absolute value of rapidity
Definition at line 198 of file inputParameters.h.
View newest version in sPHENIX GitHub at line 198 of file inputParameters.h
References _maxRapidity, and parameter< T, validate >::value().
Referenced by incoherentVMCrossSection::incoherentVMCrossSection(), narrowResonanceCrossSection::narrowResonanceCrossSection(), and write().
double inputParameters::maxW () const inline
returns maximum mass W of produced hadronic system [GeV/c^2]
Definition at line 193 of file inputParameters.h.
View newest version in sPHENIX GitHub at line 193 of file inputParameters.h
References _maxW, and parameter< T, validate >::value().
Referenced by Gammaavectormeson::Gammaavectormeson(), and write().
double inputParameters::maxW_GP () const inline
returns maximum W of produced virtual photon and nucleon system [GeV/c^2]
Definition at line 195 of file inputParameters.h.
View newest version in sPHENIX GitHub at line 195 of file inputParameters.h
References _maxW_GP, and parameter< T, validate >::value().
Referenced by write().
double inputParameters::minGammaEnergy () const inline
returns minimum gamma energy in case of photo nuclear processes [GeV]
Definition at line 217 of file inputParameters.h.
View newest version in sPHENIX GitHub at line 217 of file inputParameters.h
References _minGammaEnergy, and parameter< T, validate >::value().
double inputParameters::minGammaQ2 () const inline
return minimum gamma virtuality
Definition at line 219 of file inputParameters.h.
View newest version in sPHENIX GitHub at line 219 of file inputParameters.h
References _minGammaQ2, and parameter< T, validate >::value().
Referenced by e_narrowResonanceCrossSection::e_narrowResonanceCrossSection(), e_wideResonanceCrossSection::e_wideResonanceCrossSection(), write(), and eventFileWriter::writeInit().
double inputParameters::minW () const inline
returns minimum mass W of produced hadronic system [GeV/c^2]
Definition at line 194 of file inputParameters.h.
View newest version in sPHENIX GitHub at line 194 of file inputParameters.h
References _minW, and parameter< T, validate >::value().
Referenced by Gammaavectormeson::Gammaavectormeson(), and write().
double inputParameters::minW_GP () const inline
returns minimum W of produced virtual photon and nucleon system [GeV/c^2]
Definition at line 196 of file inputParameters.h.
View newest version in sPHENIX GitHub at line 196 of file inputParameters.h
References _minW_GP, and parameter< T, validate >::value().
Referenced by write().
unsigned int inputParameters::nmbEnergyBins () const inline
return the number of Egamma bins for eSTARlight lookup
Definition at line 200 of file inputParameters.h.
View newest version in sPHENIX GitHub at line 200 of file inputParameters.h
References _nmbEnergyBins, and parameter< T, validate >::value().
Referenced by e_narrowResonanceCrossSection::e_narrowResonanceCrossSection(), e_wideResonanceCrossSection::e_wideResonanceCrossSection(), Gammaavectormeson::Gammaavectormeson(), and eventFileWriter::writeInit().
unsigned int inputParameters::nmbEvents () const inline
returns total number of events to generate
Definition at line 208 of file inputParameters.h.
View newest version in sPHENIX GitHub at line 208 of file inputParameters.h
References _nmbEventsTot, and parameter< T, validate >::value().
Referenced by e_starlightStandalone::init(), e_starlight::init(), write(), and eventFileWriter::writeInit().
unsigned int inputParameters::nmbGammaQ2Bins () const inline
return number of gamma q2 bins
Definition at line 222 of file inputParameters.h.
View newest version in sPHENIX GitHub at line 222 of file inputParameters.h
References _nmbGammaQ2Bins, and parameter< T, validate >::value().
Referenced by Gammaavectormeson::Gammaavectormeson(), print(), write(), and eventFileWriter::writeInit().
int inputParameters::nmbPtBinsInterference () const inline
returns number of p_T bins for interference calculation
Definition at line 215 of file inputParameters.h.
View newest version in sPHENIX GitHub at line 215 of file inputParameters.h
References _nmbPtBinsInterference, and parameter< T, validate >::value().
Referenced by Gammaavectormeson::Gammaavectormeson(), init(), and write().
unsigned int inputParameters::nmbRapidityBins () const inline
returns number of rapidity bins in lookup table
Definition at line 199 of file inputParameters.h.
View newest version in sPHENIX GitHub at line 199 of file inputParameters.h
References _nmbRapidityBins, and parameter< T, validate >::value().
Referenced by Gammagammasingle::Gammagammasingle(), incoherentVMCrossSection::incoherentVMCrossSection(), narrowResonanceCrossSection::narrowResonanceCrossSection(), and write().
unsigned int inputParameters::nmbWBins () const inline
returns number of W bins in lookup table
Definition at line 197 of file inputParameters.h.
View newest version in sPHENIX GitHub at line 197 of file inputParameters.h
References _nmbWBins, and parameter< T, validate >::value().
Referenced by Gammaavectormeson::Gammaavectormeson(), Gammagammasingle::Gammagammasingle(), and write().
int inputParameters::outputFormat () const inline
returns value according to desired output format. 0 for only default, 1 for Pythia, 2 for HepMC, 3 for lund
Definition at line 228 of file inputParameters.h.
View newest version in sPHENIX GitHub at line 228 of file inputParameters.h
References _outputFormat, and parameter< T, validate >::value().
std::string inputParameters::parameterValueKey () const
Generates key for the current parameters.
Definition at line 707 of file inputParameters.cpp.
View newest version in sPHENIX GitHub at line 707 of file inputParameters.cpp
References parameterbase::_parameters, and parameterlist::validationKey().
Referenced by e_starlight::luminosityTableIsValid().
ostream & inputParameters::print (std::ostream & out) const
prints parameter summary
Definition at line 618 of file inputParameters.cpp.
View newest version in sPHENIX GitHub at line 618 of file inputParameters.cpp
References _baseFileName, _beamBreakupMode, _beamLorentzGamma, _etaCutEnabled, _etaCutMax, _etaCutMin, _fixedQ2Range, _impulseVM, _interferenceEnabled, _interferenceStrength, _maxGammaQ2, _maxPtInterference, _maxRapidity, _maxW, _minGammaQ2, _minW, _nmbEnergyBins, _nmbEventsTot, _nmbPtBinsInterference, _nmbRapidityBins, _nmbWBins, _prodParticleId, _productionMode, _ptCutEnabled, _ptCutMax, _ptCutMin, _quantumGlauber, _randomSeed, _targetBeamA, _targetBeamZ, nmbGammaQ2Bins(), parameter< T, validate >::value(), and yesNo().
Referenced by operator<<().
starlightConstants::decayTypeEnum inputParameters::prodParticleDecayType () const inline
returns decay type of produced particle
Definition at line 237 of file inputParameters.h.
View newest version in sPHENIX GitHub at line 237 of file inputParameters.h
References _decayType.
int inputParameters::prodParticleId () const inline
returns PDG particle ID of produced particle
Definition at line 209 of file inputParameters.h.
View newest version in sPHENIX GitHub at line 209 of file inputParameters.h
References _prodParticleId, and parameter< T, validate >::value().
Referenced by init(), write(), and eventFileWriter::writeInit().
starlightConstants::particleTypeEnum inputParameters::prodParticleType () const inline
returns type of produced particle
Definition at line 236 of file inputParameters.h.
View newest version in sPHENIX GitHub at line 236 of file inputParameters.h
References _particleType.
Referenced by e_starlight::createEventChannel(), Gammaavectormeson::Gammaavectormeson(), and Gammagammasingle::Gammagammasingle().
int inputParameters::productionMode () const inline
returns production mode
Definition at line 207 of file inputParameters.h.
View newest version in sPHENIX GitHub at line 207 of file inputParameters.h
References _productionMode, and parameter< T, validate >::value().
Referenced by Gammaavectormeson::Gammaavectormeson(), init(), write(), and eventFileWriter::writeInit().
double inputParameters::protonEnergy () const inline
Definition at line 239 of file inputParameters.h.
View newest version in sPHENIX GitHub at line 239 of file inputParameters.h
References _protonEnergy, and parameter< T, validate >::value().
Referenced by e_narrowResonanceCrossSection::e_narrowResonanceCrossSection(), e_wideResonanceCrossSection::e_wideResonanceCrossSection(), Gammaavectormeson::Gammaavectormeson(), incoherentVMCrossSection::incoherentVMCrossSection(), narrowResonanceCrossSection::narrowResonanceCrossSection(), and wideResonanceCrossSection::wideResonanceCrossSection().
double inputParameters::ptBinWidthInterference () const inline
returns width of p_T bins for interference calculation [GeV/c]
Definition at line 216 of file inputParameters.h.
View newest version in sPHENIX GitHub at line 216 of file inputParameters.h
References _ptBinWidthInterference, and parameter< T, validate >::value().
Referenced by Gammaavectormeson::Gammaavectormeson().
bool inputParameters::ptCutEnabled () const inline
returns cut in pt
Definition at line 201 of file inputParameters.h.
View newest version in sPHENIX GitHub at line 201 of file inputParameters.h
References _ptCutEnabled, and parameter< T, validate >::value().
Referenced by eventChannel::eventChannel(), and write().
double inputParameters::ptCutMax () const inline
returns maximum pt
Definition at line 203 of file inputParameters.h.
View newest version in sPHENIX GitHub at line 203 of file inputParameters.h
References _ptCutMax, and parameter< T, validate >::value().
Referenced by eventChannel::eventChannel(), and write().
double inputParameters::ptCutMin () const inline
returns minimum pt
Definition at line 202 of file inputParameters.h.
View newest version in sPHENIX GitHub at line 202 of file inputParameters.h
References _ptCutMin, and parameter< T, validate >::value().
Referenced by eventChannel::eventChannel(), and write().
bool inputParameters::pythiaFullEventRecord () const inline
returns if the full pythia event record should be printed
Definition at line 225 of file inputParameters.h.
View newest version in sPHENIX GitHub at line 225 of file inputParameters.h
References _outputFormat, and parameter< T, validate >::value().
Referenced by e_starlightStandalone::run().
std::string inputParameters::pythiaParams () const inline
returns parameters to be passed to pythia
Definition at line 223 of file inputParameters.h.
View newest version in sPHENIX GitHub at line 223 of file inputParameters.h
References _pythiaParams, and parameter< T, validate >::value().
int inputParameters::quantumGlauber () const inline
returns the quantum glauber value
Definition at line 235 of file inputParameters.h.
View newest version in sPHENIX GitHub at line 235 of file inputParameters.h
References _quantumGlauber, and parameter< T, validate >::value().
Referenced by photonNucleusCrossSection::photonNucleusCrossSection(), and eventFileWriter::writeInit().
int inputParameters::randomSeed () const inline
returns seed for random number generator
Definition at line 210 of file inputParameters.h.
View newest version in sPHENIX GitHub at line 210 of file inputParameters.h
References _randomSeed, and parameter< T, validate >::value().
Referenced by eventChannel::eventChannel(), e_starlight::luminosityTableIsValid(), write(), and eventFileWriter::writeInit().
double inputParameters::rap_CM () const inline
returns center-of-mass rapidity
Definition at line 188 of file inputParameters.h.
View newest version in sPHENIX GitHub at line 188 of file inputParameters.h
References _rap_CM.
Referenced by e_starlightStandalone::boostEvent(), and Gammaavectormeson::Gammaavectormeson().
void inputParameters::setAxionMass (double v) inline
sets axion mass //AXION HACK
Definition at line 284 of file inputParameters.h.
View newest version in sPHENIX GitHub at line 284 of file inputParameters.h
References _axionMass, and v.
void inputParameters::setBackwardsProduction (bool v) inline
sets backwards production
Definition at line 282 of file inputParameters.h.
View newest version in sPHENIX GitHub at line 282 of file inputParameters.h
References _backwardsProduction, and v.
void inputParameters::setBaseFileName (std::string v) inline
Definition at line 244 of file inputParameters.h.
View newest version in sPHENIX GitHub at line 244 of file inputParameters.h
References _baseFileName, and v.
void inputParameters::setBeamBreakupMode (int v) inline
sets breakup mode for beam particles
Definition at line 270 of file inputParameters.h.
View newest version in sPHENIX GitHub at line 270 of file inputParameters.h
References _beamBreakupMode, and v.
void inputParameters::setBeamLorentzGamma (double v) inline
sets Lorentz gamma factor of both beams in beam CMS frame
Definition at line 248 of file inputParameters.h.
View newest version in sPHENIX GitHub at line 248 of file inputParameters.h
References _beamLorentzGamma, and v.
void inputParameters::setbslopeDefinition (int v) inline
sets the definition of b slope
Definition at line 285 of file inputParameters.h.
View newest version in sPHENIX GitHub at line 285 of file inputParameters.h
References _bslopeDefinition, and v.
void inputParameters::setbslopeValue (double v) inline
sets the value of b slope
Definition at line 286 of file inputParameters.h.
View newest version in sPHENIX GitHub at line 286 of file inputParameters.h
References _bslopeValue, and v.
void inputParameters::setElectronBeamLorentzGamma (double v) inline
Definition at line 249 of file inputParameters.h.
View newest version in sPHENIX GitHub at line 249 of file inputParameters.h
References _electronBeamLorentzGamma, and v.
void inputParameters::setElectronEnergy (double v) inline
sets electron energy
Definition at line 295 of file inputParameters.h.
View newest version in sPHENIX GitHub at line 295 of file inputParameters.h
References _electronEnergy, and v.
void inputParameters::setEtaCutEnabled (bool v) inline
sets cut in eta
Definition at line 263 of file inputParameters.h.
View newest version in sPHENIX GitHub at line 263 of file inputParameters.h
References _etaCutEnabled, and v.
void inputParameters::setEtaCutMax (double v) inline
sets maximum eta
Definition at line 265 of file inputParameters.h.
View newest version in sPHENIX GitHub at line 265 of file inputParameters.h
References _etaCutMax, and v.
void inputParameters::setEtaCutMin (double v) inline
sets minimum eta
Definition at line 264 of file inputParameters.h.
View newest version in sPHENIX GitHub at line 264 of file inputParameters.h
References _etaCutMin, and v.
void inputParameters::setimpulseVM (int v) inline
sets the value of _impulseVM
Definition at line 287 of file inputParameters.h.
View newest version in sPHENIX GitHub at line 287 of file inputParameters.h
References _impulseVM, and v.
void inputParameters::setInteractionType (starlightConstants::interactionTypeEnum v) inline
sets interaction type
Definition at line 292 of file inputParameters.h.
View newest version in sPHENIX GitHub at line 292 of file inputParameters.h
References _interactionType, and v.
void inputParameters::setInterferenceEnabled (bool v) inline
sets whether interference is taken into account
Definition at line 271 of file inputParameters.h.
View newest version in sPHENIX GitHub at line 271 of file inputParameters.h
References _interferenceEnabled, and v.
void inputParameters::setInterferenceStrength (double v) inline
sets percentage of interference
Definition at line 272 of file inputParameters.h.
View newest version in sPHENIX GitHub at line 272 of file inputParameters.h
References _interferenceStrength, and v.
void inputParameters::setMaxGammaEnergy (double v) inline
sets maximum gamma energy in case of photo nuclear processes [GeV]
Definition at line 277 of file inputParameters.h.
View newest version in sPHENIX GitHub at line 277 of file inputParameters.h
References _maxGammaEnergy, and v.
void inputParameters::setMaxGammaQ2 (double v) inline
sets maximum gamma virtuality in case of photo nuclear processes [GeV]
Definition at line 279 of file inputParameters.h.
View newest version in sPHENIX GitHub at line 279 of file inputParameters.h
References _maxGammaQ2, and v.
void inputParameters::setMaxPtInterference (double v) inline
sets maximum p_T for voiderference calculation [GeV/c]
Definition at line 273 of file inputParameters.h.
View newest version in sPHENIX GitHub at line 273 of file inputParameters.h
References _maxPtInterference, and v.
void inputParameters::setMaxRapidity (double v) inline
sets maximum absolute value of rapidity
Definition at line 257 of file inputParameters.h.
View newest version in sPHENIX GitHub at line 257 of file inputParameters.h
References _maxRapidity, and v.
void inputParameters::setMaxW (double v) inline
sets maximum mass W of produced hadronic system [GeV/c^2]
Definition at line 252 of file inputParameters.h.
View newest version in sPHENIX GitHub at line 252 of file inputParameters.h
References _maxW, and v.
void inputParameters::setmaxW_GP (double v) inline
sets maximum mass W of produced virtual photon and nucleon system [GeV/c^2]
Definition at line 254 of file inputParameters.h.
View newest version in sPHENIX GitHub at line 254 of file inputParameters.h
References _maxW_GP, and v.
void inputParameters::setMinGammaEnergy (double v) inline
sets minimum gamma energy in case of photo nuclear processes [GeV]
Definition at line 276 of file inputParameters.h.
View newest version in sPHENIX GitHub at line 276 of file inputParameters.h
References _minGammaEnergy, and v.
void inputParameters::setMinGammaQ2 (double v) inline
sets minimum gamma virtuality in case of photo nuclear processes [GeV]
Definition at line 278 of file inputParameters.h.
View newest version in sPHENIX GitHub at line 278 of file inputParameters.h
References _minGammaQ2, and v.
void inputParameters::setMinW (double v) inline
sets minimum mass W of produced hadronic system [GeV/c^2]
Definition at line 253 of file inputParameters.h.
View newest version in sPHENIX GitHub at line 253 of file inputParameters.h
References _minW, and v.
void inputParameters::setminW_GP (double v) inline
sets minimum mass W of produced virtual photon and nucleon system [GeV/c^2]
Definition at line 255 of file inputParameters.h.
View newest version in sPHENIX GitHub at line 255 of file inputParameters.h
References _minW_GP, and v.
void inputParameters::setNmbEgaBins (unsigned int v) inline
sets number of Ega bins for eSTARlight
Definition at line 259 of file inputParameters.h.
View newest version in sPHENIX GitHub at line 259 of file inputParameters.h
References _nmbEnergyBins, and v.
void inputParameters::setNmbEvents (unsigned int v) inline
sets total number of events to generate
Definition at line 267 of file inputParameters.h.
View newest version in sPHENIX GitHub at line 267 of file inputParameters.h
References _nmbEventsTot, and v.
void inputParameters::setNmbPtBinsInterference (int v) inline
sets number of p_T bins for interference calculation
Definition at line 274 of file inputParameters.h.
View newest version in sPHENIX GitHub at line 274 of file inputParameters.h
References _nmbPtBinsInterference, and v.
void inputParameters::setNmbRapidityBins (unsigned int v) inline
sets number of rapidity bins in lookup table
Definition at line 258 of file inputParameters.h.
View newest version in sPHENIX GitHub at line 258 of file inputParameters.h
References _nmbRapidityBins, and v.
void inputParameters::setNmbWBins (unsigned int v) inline
sets number of W bins in lookup table
Definition at line 256 of file inputParameters.h.
View newest version in sPHENIX GitHub at line 256 of file inputParameters.h
References _nmbWBins, and v.
void inputParameters::setOutputFormat (int v) inline
sets output file format
Definition at line 281 of file inputParameters.h.
View newest version in sPHENIX GitHub at line 281 of file inputParameters.h
References _outputFormat, and v.
template<typename T > bool inputParameters::setParameter (std::string expression) inline
Definition at line 399 of file inputParameters.h.
View newest version in sPHENIX GitHub at line 399 of file inputParameters.h
References _ip, and inputParser::parseString().
void inputParameters::setProdParticleDecayType (starlightConstants::decayTypeEnum v) inline
sets decay type of produced particle
Definition at line 291 of file inputParameters.h.
View newest version in sPHENIX GitHub at line 291 of file inputParameters.h
References _decayType, and v.
void inputParameters::setProdParticleId (int v) inline
sets PDG particle ID of produced particle
Definition at line 268 of file inputParameters.h.
View newest version in sPHENIX GitHub at line 268 of file inputParameters.h
References _prodParticleId, and v.
void inputParameters::setProdParticleType (starlightConstants::particleTypeEnum v) inline
sets type of produced particle
Definition at line 290 of file inputParameters.h.
View newest version in sPHENIX GitHub at line 290 of file inputParameters.h
References _particleType, and v.
void inputParameters::setProductionMode (int v) inline
sets production mode
Definition at line 266 of file inputParameters.h.
View newest version in sPHENIX GitHub at line 266 of file inputParameters.h
References _productionMode, and v.
void inputParameters::setProtonEnergy (double v) inline
sets proton energy
Definition at line 294 of file inputParameters.h.
View newest version in sPHENIX GitHub at line 294 of file inputParameters.h
References _protonEnergy, and v.
void inputParameters::setPtBinWidthInterference (double v) inline
sets width of p_T bins for voiderference calculation [GeV/c]
Definition at line 275 of file inputParameters.h.
View newest version in sPHENIX GitHub at line 275 of file inputParameters.h
References _ptBinWidthInterference, and v.
void inputParameters::setPtCutEnabled (bool v) inline
sets cut in pt
Definition at line 260 of file inputParameters.h.
View newest version in sPHENIX GitHub at line 260 of file inputParameters.h
References _ptCutEnabled, and v.
void inputParameters::setPtCutMax (double v) inline
sets maximum pt
Definition at line 262 of file inputParameters.h.
View newest version in sPHENIX GitHub at line 262 of file inputParameters.h
References _ptCutMax, and v.
void inputParameters::setPtCutMin (double v) inline
sets minimum pt
Definition at line 261 of file inputParameters.h.
View newest version in sPHENIX GitHub at line 261 of file inputParameters.h
References _ptCutMin, and v.
void inputParameters::setPythiaParams (std::string v) inline
sets parameters to be passed to pythia
Definition at line 280 of file inputParameters.h.
View newest version in sPHENIX GitHub at line 280 of file inputParameters.h
References _pythiaParams, and v.
void inputParameters::setquantumGlauber (int v) inline
sets the value of quantum_glauber
Definition at line 288 of file inputParameters.h.
View newest version in sPHENIX GitHub at line 288 of file inputParameters.h
References _quantumGlauber, and v.
void inputParameters::setRandomSeed (int v) inline
sets seed for random number generator
Definition at line 269 of file inputParameters.h.
View newest version in sPHENIX GitHub at line 269 of file inputParameters.h
References _randomSeed, and v.
void inputParameters::setRapCM (double v) inline
sets center-of-mass rapidity
Definition at line 250 of file inputParameters.h.
View newest version in sPHENIX GitHub at line 250 of file inputParameters.h
References _rap_CM, and v.
void inputParameters::setTargetBeamA (unsigned int v) inline
sets atomic mass number of beam particle 2
Definition at line 246 of file inputParameters.h.
View newest version in sPHENIX GitHub at line 246 of file inputParameters.h
References _targetBeamA, and v.
void inputParameters::setTargetBeamZ (unsigned int v) inline
sets atomic number of beam particle 2
Definition at line 245 of file inputParameters.h.
View newest version in sPHENIX GitHub at line 245 of file inputParameters.h
References _targetBeamZ, and v.
void inputParameters::setTargetLorentzGamma (double v) inline
sets Lorentz gamma factor of both beams in beam CMS frame
Definition at line 247 of file inputParameters.h.
View newest version in sPHENIX GitHub at line 247 of file inputParameters.h
References _targetLorentzGamma, and v.
void inputParameters::setXsecCalcMethod (int v) inline
sets the method used for the x-sec calculation
Definition at line 283 of file inputParameters.h.
View newest version in sPHENIX GitHub at line 283 of file inputParameters.h
References _xsecCalcMethod, and v.
unsigned int inputParameters::targetBeamA () const inline
returns atomic mass number of beam particle 2
Definition at line 183 of file inputParameters.h.
View newest version in sPHENIX GitHub at line 183 of file inputParameters.h
References _targetBeamA, and parameter< T, validate >::value().
Referenced by Gammaavectormeson::Gammaavectormeson(), e_starlight::init(), init(), hepMC3Writer::initBeamHepMC3(), write(), eventFileWriter::writeInit(), and eventFileWriter::writeInitLUND().
double inputParameters::targetBeamLorentzGamma () const inline
returns Lorentz gamma factor of beam 2 in collider frame
Definition at line 187 of file inputParameters.h.
View newest version in sPHENIX GitHub at line 187 of file inputParameters.h
References _targetBeamLorentzGamma, and parameter< T, validate >::value().
Referenced by e_starlightStandalone::boostEvent(), e_narrowResonanceCrossSection::e_narrowResonanceCrossSection(), Gammaavectormeson::Gammaavectormeson(), init(), hepMC3Writer::initBeamHepMC3(), eventFileWriter::writeInit(), and eventFileWriter::writeInitLUND().
int inputParameters::targetBeamZ () const inline
returns atomic number of beam particle 2
Definition at line 182 of file inputParameters.h.
View newest version in sPHENIX GitHub at line 182 of file inputParameters.h
References _targetBeamZ, and parameter< T, validate >::value().
Referenced by init(), hepMC3Writer::initBeamHepMC3(), write(), eventFileWriter::writeInit(), and eventFileWriter::writeInitLUND().
double inputParameters::targetLorentzGamma () const inline
returns Lorentz gamma factor of source in target frame
Definition at line 184 of file inputParameters.h.
View newest version in sPHENIX GitHub at line 184 of file inputParameters.h
References _targetLorentzGamma.
double inputParameters::targetMaxPhotonEnergy () const inline
returns maximum photon energy
Definition at line 189 of file inputParameters.h.
View newest version in sPHENIX GitHub at line 189 of file inputParameters.h
References _targetMaxPhotonEnergy.
Referenced by e_narrowResonanceCrossSection::e_narrowResonanceCrossSection(), e_wideResonanceCrossSection::e_wideResonanceCrossSection(), and Gammaavectormeson::Gammaavectormeson().
double inputParameters::targetMinPhotonEnergy () const inline
returns maximum photon energy
Definition at line 191 of file inputParameters.h.
View newest version in sPHENIX GitHub at line 191 of file inputParameters.h
References _targetMinPhotonEnergy.
Referenced by e_narrowResonanceCrossSection::e_narrowResonanceCrossSection(), e_wideResonanceCrossSection::e_wideResonanceCrossSection(), and Gammaavectormeson::Gammaavectormeson().
double inputParameters::targetRadius () const inline
Definition at line 242 of file inputParameters.h.
View newest version in sPHENIX GitHub at line 242 of file inputParameters.h
References _targetR.
Referenced by e_narrowResonanceCrossSection::e_narrowResonanceCrossSection(), e_wideResonanceCrossSection::e_wideResonanceCrossSection(), and Gammaavectormeson::Gammaavectormeson().
ostream & inputParameters::write (std::ostream & out) const
writes parameters back to an ostream
Definition at line 668 of file inputParameters.cpp.
View newest version in sPHENIX GitHub at line 668 of file inputParameters.cpp
References _fixedQ2Range, baseFileName(), beamBreakupMode(), beamLorentzGamma(), etaCutEnabled(), etaCutMax(), etaCutMin(), interferenceEnabled(), interferenceStrength(), maxGammaQ2(), maxPtInterference(), maxRapidity(), maxW(), maxW_GP(), minGammaQ2(), minW(), minW_GP(), nmbEvents(), nmbGammaQ2Bins(), nmbPtBinsInterference(), nmbRapidityBins(), nmbWBins(), prodParticleId(), productionMode(), ptCutEnabled(), ptCutMax(), ptCutMin(), randomSeed(), targetBeamA(), and targetBeamZ().
int inputParameters::xsecCalcMethod () const inline
returns the method used for the x-sec calculation
Definition at line 230 of file inputParameters.h.
View newest version in sPHENIX GitHub at line 230 of file inputParameters.h
References _xsecCalcMethod, and parameter< T, validate >::value().
Member Data Documentation
parameter<double, VALIDITY_CHECK> inputParameters::_axionMass private
Definition at line 372 of file inputParameters.h.
View newest version in sPHENIX GitHub at line 372 of file inputParameters.h
Referenced by axionMass(), init(), inputParameters(), and setAxionMass().
parameter<bool, NO_VALIDITY_CHECK> inputParameters::_backwardsProduction private
Definition at line 370 of file inputParameters.h.
View newest version in sPHENIX GitHub at line 370 of file inputParameters.h
Referenced by backwardsProduction(), inputParameters(), and setBackwardsProduction().
parameter<std::string,NO_VALIDITY_CHECK> inputParameters::_baseFileName private
Definition at line 315 of file inputParameters.h.
View newest version in sPHENIX GitHub at line 315 of file inputParameters.h
Referenced by baseFileName(), inputParameters(), print(), and setBaseFileName().
parameter<unsigned int, VALIDITY_CHECK> inputParameters::_beamBreakupMode private
breakup mode for beam particles
1 = hard sphere nuclei (b > 2R), 2 = both nuclei break up (XnXn), 3 = a single neutron from each nucleus (1n1n), 4 = neither nucleon breaks up (with b > 2R), 5 = no hadronic break up (similar to option 1, but with the actual hadronic interaction)
Definition at line 346 of file inputParameters.h.
View newest version in sPHENIX GitHub at line 346 of file inputParameters.h
Referenced by beamBreakupMode(), inputParameters(), print(), and setBeamBreakupMode().
double inputParameters::_beamLorentzGamma private
Lorentz gamma factor of the beams in CMS frame, not an input parameter.
Definition at line 383 of file inputParameters.h.
View newest version in sPHENIX GitHub at line 383 of file inputParameters.h
Referenced by beamLorentzGamma(), init(), print(), and setBeamLorentzGamma().
parameter<unsigned int, VALIDITY_CHECK> inputParameters::_bslopeDefinition private
Axion mass//AXION HACK.
Optional parameter to set different values of slope parameter
Definition at line 373 of file inputParameters.h.
View newest version in sPHENIX GitHub at line 373 of file inputParameters.h
Referenced by bslopeDefinition(), inputParameters(), and setbslopeDefinition().
parameter<double, VALIDITY_CHECK> inputParameters::_bslopeValue private
Value of slope parameter when _bslopeDefinition is set to 1.
Definition at line 374 of file inputParameters.h.
View newest version in sPHENIX GitHub at line 374 of file inputParameters.h
Referenced by bslopeValue(), inputParameters(), and setbslopeValue().
double inputParameters::_cmsMaxPhotonEnergy private
Definition at line 386 of file inputParameters.h.
View newest version in sPHENIX GitHub at line 386 of file inputParameters.h
Referenced by cmsMaxPhotonEnergy(), and init().
double inputParameters::_cmsMinPhotonEnergy private
Definition at line 387 of file inputParameters.h.
View newest version in sPHENIX GitHub at line 387 of file inputParameters.h
Referenced by cmsMinPhotonEnergy(), and init().
std::string inputParameters::_configFileName private
path to configuration file (default = ./config/slight.in)
Definition at line 312 of file inputParameters.h.
View newest version in sPHENIX GitHub at line 312 of file inputParameters.h
starlightConstants::decayTypeEnum inputParameters::_decayType private
Definition at line 379 of file inputParameters.h.
View newest version in sPHENIX GitHub at line 379 of file inputParameters.h
Referenced by init(), prodParticleDecayType(), and setProdParticleDecayType().
parameter<double, VALIDITY_CHECK> inputParameters::_electronBeamLorentzGamma private
Lorentz gamma factor of beam 1 in collider frame.
Definition at line 318 of file inputParameters.h.
View newest version in sPHENIX GitHub at line 318 of file inputParameters.h
Referenced by electronBeamLorentzGamma(), inputParameters(), and setElectronBeamLorentzGamma().
parameter<double, VALIDITY_CHECK> inputParameters::_electronEnergy private
Definition at line 359 of file inputParameters.h.
View newest version in sPHENIX GitHub at line 359 of file inputParameters.h
Referenced by electronEnergy(), init(), and setElectronEnergy().
parameter<bool, VALIDITY_CHECK> inputParameters::_etaCutEnabled private
en/disables cut in eta
Definition at line 331 of file inputParameters.h.
View newest version in sPHENIX GitHub at line 331 of file inputParameters.h
Referenced by etaCutEnabled(), inputParameters(), print(), and setEtaCutEnabled().
parameter<double, VALIDITY_CHECK> inputParameters::_etaCutMax private
maximum eta, if cut is enabled
Definition at line 333 of file inputParameters.h.
View newest version in sPHENIX GitHub at line 333 of file inputParameters.h
Referenced by etaCutMax(), inputParameters(), print(), and setEtaCutMax().
parameter<double, VALIDITY_CHECK> inputParameters::_etaCutMin private
minimum eta, if cut is enabled
Definition at line 332 of file inputParameters.h.
View newest version in sPHENIX GitHub at line 332 of file inputParameters.h
Referenced by etaCutMin(), inputParameters(), print(), and setEtaCutMin().
bool inputParameters::_fixedQ2Range private
Definition at line 391 of file inputParameters.h.
View newest version in sPHENIX GitHub at line 391 of file inputParameters.h
Referenced by fixedQ2Range(), init(), print(), and write().
parameter<unsigned int, VALIDITY_CHECK> inputParameters::_impulseVM private
Optional parameter to use impulse approximation (no nuclear effects) for VM cross section.
Definition at line 375 of file inputParameters.h.
View newest version in sPHENIX GitHub at line 375 of file inputParameters.h
Referenced by impulseVM(), inputParameters(), print(), and setimpulseVM().
double inputParameters::_inputBranchingRatio private
Branching ratio defined for each channel.
Definition at line 390 of file inputParameters.h.
View newest version in sPHENIX GitHub at line 390 of file inputParameters.h
Referenced by init(), and inputBranchingRatio().
starlightConstants::interactionTypeEnum inputParameters::_interactionType private
Definition at line 380 of file inputParameters.h.
View newest version in sPHENIX GitHub at line 380 of file inputParameters.h
Referenced by init(), interactionType(), and setInteractionType().
parameter<bool, VALIDITY_CHECK> inputParameters::_interferenceEnabled private
if VALIDITY_CHECK, interference is taken into account
Definition at line 353 of file inputParameters.h.
View newest version in sPHENIX GitHub at line 353 of file inputParameters.h
Referenced by init(), inputParameters(), interferenceEnabled(), print(), and setInterferenceEnabled().
parameter<double, VALIDITY_CHECK> inputParameters::_interferenceStrength private
percentage of interference: from 0 = none to 1 = full
Definition at line 354 of file inputParameters.h.
View newest version in sPHENIX GitHub at line 354 of file inputParameters.h
Referenced by inputParameters(), interferenceStrength(), print(), and setInterferenceStrength().
inputParser inputParameters::_ip private
Definition at line 392 of file inputParameters.h.
View newest version in sPHENIX GitHub at line 392 of file inputParameters.h
Referenced by configureFromFile(), inputParameters(), and setParameter().
parameter<double, VALIDITY_CHECK> inputParameters::_maxGammaEnergy private
maximum gamma energy in case of photo nuclear processes [GeV]
Definition at line 361 of file inputParameters.h.
View newest version in sPHENIX GitHub at line 361 of file inputParameters.h
Referenced by inputParameters(), maxGammaEnergy(), and setMaxGammaEnergy().
parameter<double, VALIDITY_CHECK> inputParameters::_maxGammaQ2 private
maximum gamma Q2 in case of photo nuclear processes
Definition at line 363 of file inputParameters.h.
View newest version in sPHENIX GitHub at line 363 of file inputParameters.h
Referenced by init(), inputParameters(), maxGammaQ2(), print(), and setMaxGammaQ2().
parameter<double, VALIDITY_CHECK> inputParameters::_maxPtInterference private
maximum p_T for interference calculation [GeV/c]
Definition at line 355 of file inputParameters.h.
View newest version in sPHENIX GitHub at line 355 of file inputParameters.h
Referenced by inputParameters(), maxPtInterference(), print(), and setMaxPtInterference().
parameter<double, VALIDITY_CHECK> inputParameters::_maxRapidity private
maximum absolute value of rapidity
Definition at line 325 of file inputParameters.h.
View newest version in sPHENIX GitHub at line 325 of file inputParameters.h
Referenced by inputParameters(), maxRapidity(), print(), and setMaxRapidity().
parameter<double, VALIDITY_CHECK> inputParameters::_maxW private
maximum mass W of produced hadronic system [GeV/c^2]
Definition at line 320 of file inputParameters.h.
View newest version in sPHENIX GitHub at line 320 of file inputParameters.h
Referenced by init(), inputParameters(), maxW(), print(), and setMaxW().
parameter<double, VALIDITY_CHECK> inputParameters::_maxW_GP private
maximum mass W of produced virtual photon and nucleon system, has no maximum limit [GeV/c^2]
Definition at line 322 of file inputParameters.h.
View newest version in sPHENIX GitHub at line 322 of file inputParameters.h
Referenced by init(), inputParameters(), maxW_GP(), and setmaxW_GP().
parameter<double, VALIDITY_CHECK> inputParameters::_minGammaEnergy private
minimum gamma energy in case of photo nuclear processes [GeV]
Definition at line 360 of file inputParameters.h.
View newest version in sPHENIX GitHub at line 360 of file inputParameters.h
Referenced by inputParameters(), minGammaEnergy(), and setMinGammaEnergy().
parameter<double, VALIDITY_CHECK> inputParameters::_minGammaQ2 private
minimum gamma Q2 in case of photo nuclear processes
Definition at line 362 of file inputParameters.h.
View newest version in sPHENIX GitHub at line 362 of file inputParameters.h
Referenced by init(), inputParameters(), minGammaQ2(), print(), and setMinGammaQ2().
parameter<double, VALIDITY_CHECK> inputParameters::_minW private
minimum mass W of produced hadronic system; if set to -1 default value is taken [GeV/c^2]
Definition at line 321 of file inputParameters.h.
View newest version in sPHENIX GitHub at line 321 of file inputParameters.h
Referenced by init(), inputParameters(), minW(), print(), and setMinW().
parameter<double, VALIDITY_CHECK> inputParameters::_minW_GP private
minimum mass W of produced virtual photon and nucleon system, should be no greater than COM energy of source + traget or code will terminate [GeV/c^2]
Definition at line 323 of file inputParameters.h.
View newest version in sPHENIX GitHub at line 323 of file inputParameters.h
Referenced by init(), inputParameters(), minW_GP(), and setminW_GP().
parameter<unsigned int, VALIDITY_CHECK> inputParameters::_nmbEnergyBins private
number of Egamma bins in lookup table
Definition at line 327 of file inputParameters.h.
View newest version in sPHENIX GitHub at line 327 of file inputParameters.h
Referenced by inputParameters(), nmbEnergyBins(), print(), and setNmbEgaBins().
parameter<unsigned int, VALIDITY_CHECK> inputParameters::_nmbEventsTot private
total number of events to generate
Definition at line 339 of file inputParameters.h.
View newest version in sPHENIX GitHub at line 339 of file inputParameters.h
Referenced by inputParameters(), nmbEvents(), print(), and setNmbEvents().
parameter<unsigned int, VALIDITY_CHECK> inputParameters::_nmbGammaQ2Bins private
number of gamma q2 bins
Definition at line 364 of file inputParameters.h.
View newest version in sPHENIX GitHub at line 364 of file inputParameters.h
Referenced by inputParameters(), and nmbGammaQ2Bins().
parameter<unsigned int, VALIDITY_CHECK> inputParameters::_nmbPtBinsInterference private
number of p_T bins for interference calculation
Definition at line 356 of file inputParameters.h.
View newest version in sPHENIX GitHub at line 356 of file inputParameters.h
Referenced by inputParameters(), nmbPtBinsInterference(), print(), and setNmbPtBinsInterference().
parameter<unsigned int, VALIDITY_CHECK> inputParameters::_nmbRapidityBins private
number of rapidity bins in lookup table
Definition at line 326 of file inputParameters.h.
View newest version in sPHENIX GitHub at line 326 of file inputParameters.h
Referenced by inputParameters(), nmbRapidityBins(), print(), and setNmbRapidityBins().
parameter<unsigned int, VALIDITY_CHECK> inputParameters::_nmbWBins private
number of W bins in lookup table
Definition at line 324 of file inputParameters.h.
View newest version in sPHENIX GitHub at line 324 of file inputParameters.h
Referenced by inputParameters(), nmbWBins(), print(), and setNmbWBins().
parameter<int, NO_VALIDITY_CHECK> inputParameters::_outputFormat private
identifier of output format
Definition at line 369 of file inputParameters.h.
View newest version in sPHENIX GitHub at line 369 of file inputParameters.h
Referenced by defaultFullEventRecord(), hepmc3FullEventRecord(), inputParameters(), lundFullEventRecord(), outputFormat(), pythiaFullEventRecord(), and setOutputFormat().
starlightConstants::particleTypeEnum inputParameters::_particleType private
Definition at line 378 of file inputParameters.h.
View newest version in sPHENIX GitHub at line 378 of file inputParameters.h
Referenced by init(), prodParticleType(), and setProdParticleType().
parameter<unsigned int, VALIDITY_CHECK> inputParameters::_prodParticleId private
PDG particle ID of produced particle.
Definition at line 340 of file inputParameters.h.
View newest version in sPHENIX GitHub at line 340 of file inputParameters.h
Referenced by init(), inputParameters(), print(), prodParticleId(), and setProdParticleId().
parameter<unsigned int, VALIDITY_CHECK> inputParameters::_productionMode private
production mode
1 = photon-photon fusion, 2 = narrow vector meson resonance in photon-Pomeron fusion, 3 = Breit-Wigner vector meson resonance in photon-Pomeron fusion
Definition at line 334 of file inputParameters.h.
View newest version in sPHENIX GitHub at line 334 of file inputParameters.h
Referenced by init(), inputParameters(), print(), productionMode(), and setProductionMode().
parameter<double, VALIDITY_CHECK> inputParameters::_protonEnergy private
Definition at line 358 of file inputParameters.h.
View newest version in sPHENIX GitHub at line 358 of file inputParameters.h
Referenced by init(), protonEnergy(), and setProtonEnergy().
parameter<double, VALIDITY_CHECK> inputParameters::_ptBinWidthInterference private
width of p_T bins for interference calculation [GeV/c]
Definition at line 357 of file inputParameters.h.
View newest version in sPHENIX GitHub at line 357 of file inputParameters.h
Referenced by init(), ptBinWidthInterference(), and setPtBinWidthInterference().
parameter<bool, VALIDITY_CHECK> inputParameters::_ptCutEnabled private
en/disables cut in pt
Definition at line 328 of file inputParameters.h.
View newest version in sPHENIX GitHub at line 328 of file inputParameters.h
Referenced by inputParameters(), print(), ptCutEnabled(), and setPtCutEnabled().
parameter<double, VALIDITY_CHECK> inputParameters::_ptCutMax private
maximum pt, if cut is enabled
Definition at line 330 of file inputParameters.h.
View newest version in sPHENIX GitHub at line 330 of file inputParameters.h
Referenced by inputParameters(), print(), ptCutMax(), and setPtCutMax().
parameter<double, VALIDITY_CHECK> inputParameters::_ptCutMin private
minimum pt, if cut is enabled
Definition at line 329 of file inputParameters.h.
View newest version in sPHENIX GitHub at line 329 of file inputParameters.h
Referenced by inputParameters(), print(), ptCutMin(), and setPtCutMin().
parameter<std::string,NO_VALIDITY_CHECK> inputParameters::_pythiaParams private
semi-colon separated parameters to pass to pythia, e.g. "mstj(1)=0;paru(13)=0.1"
Definition at line 365 of file inputParameters.h.
View newest version in sPHENIX GitHub at line 365 of file inputParameters.h
Referenced by inputParameters(), pythiaParams(), and setPythiaParams().
parameter<unsigned int, VALIDITY_CHECK> inputParameters::_quantumGlauber private
Optional parameter. Set = 1 to use Quantum Glauber calculation, rather than Classical Glauber.
Definition at line 376 of file inputParameters.h.
View newest version in sPHENIX GitHub at line 376 of file inputParameters.h
Referenced by inputParameters(), print(), quantumGlauber(), and setquantumGlauber().
parameter<unsigned int, VALIDITY_CHECK> inputParameters::_randomSeed private
seed for random number generator
                                                                       1 = ASCII
                                                                       2 = GSTARtext,
                                                                       3 = PAW ntuple (not working)
Definition at line 341 of file inputParameters.h.
View newest version in sPHENIX GitHub at line 341 of file inputParameters.h
Referenced by inputParameters(), print(), randomSeed(), and setRandomSeed().
double inputParameters::_rap_CM private
Definition at line 384 of file inputParameters.h.
View newest version in sPHENIX GitHub at line 384 of file inputParameters.h
Referenced by init(), rap_CM(), and setRapCM().
parameter<unsigned int,VALIDITY_CHECK> inputParameters::_targetBeamA private
atomic mass number of beam particle 2
Definition at line 317 of file inputParameters.h.
View newest version in sPHENIX GitHub at line 317 of file inputParameters.h
Referenced by inputParameters(), print(), setTargetBeamA(), and targetBeamA().
parameter<double, VALIDITY_CHECK> inputParameters::_targetBeamLorentzGamma private
Lorentz gamma factor of beam 2 in collider frame.
Definition at line 319 of file inputParameters.h.
View newest version in sPHENIX GitHub at line 319 of file inputParameters.h
Referenced by inputParameters(), and targetBeamLorentzGamma().
parameter<int,VALIDITY_CHECK> inputParameters::_targetBeamZ private
atomic number of beam particle 2
Definition at line 316 of file inputParameters.h.
View newest version in sPHENIX GitHub at line 316 of file inputParameters.h
Referenced by inputParameters(), print(), setTargetBeamZ(), and targetBeamZ().
double inputParameters::_targetLorentzGamma private
Lorentz gamma factor of the source in target frame, not an input parameter.
Definition at line 382 of file inputParameters.h.
View newest version in sPHENIX GitHub at line 382 of file inputParameters.h
Referenced by init(), setTargetLorentzGamma(), and targetLorentzGamma().
double inputParameters::_targetMaxPhotonEnergy private
Definition at line 388 of file inputParameters.h.
View newest version in sPHENIX GitHub at line 388 of file inputParameters.h
Referenced by init(), and targetMaxPhotonEnergy().
double inputParameters::_targetMinPhotonEnergy private
Definition at line 389 of file inputParameters.h.
View newest version in sPHENIX GitHub at line 389 of file inputParameters.h
Referenced by init(), and targetMinPhotonEnergy().
double inputParameters::_targetR private
Definition at line 385 of file inputParameters.h.
View newest version in sPHENIX GitHub at line 385 of file inputParameters.h
Referenced by init(), and targetRadius().
parameter<unsigned int, VALIDITY_CHECK> inputParameters::_xsecCalcMethod private
Select x-sec calc method. (0 is standard starlight method, 1 must be used for assym. collisions (e.g. p-A), but is slow)
Definition at line 371 of file inputParameters.h.
View newest version in sPHENIX GitHub at line 371 of file inputParameters.h
Referenced by inputParameters(), setXsecCalcMethod(), and xsecCalcMethod().
The documentation for this class was generated from the following files:
estarlight/blob/master/include/inputParameters.h
estarlight/blob/master/src/inputParameters.cpp