EIC Software: PndHitRecoHit Class Reference
PndHitRecoHit Class Reference
A planar (x,y) reco hit & its sensor plane.
#include <EicRoot/blob/master/GenfitTools/recohits/PndHitRecoHit.h>
Public Member Functions
PndHitRecoHit ()
PndHitRecoHit (FairMCPoint *point)
PndHitRecoHit (FairHit *hit)
virtual ~PndHitRecoHit ()
virtual GFAbsRecoHit * clone ()
Get clone of this object.
virtual TMatrixT< double > getHMatrix (const GFAbsTrackRep *stateVector)
Get transformation matrix. Transformation between hit coordinates and track representation coordinates.
virtual Double_t residualScalar (GFAbsTrackRep *stateVector, const TMatrixT< Double_t > &state)
Public Member Functions inherited from GFRecoHitIfc< GFSpacepointHitPolicy >
GFRecoHitIfc (int dim)
Constructor specifying dimension of hit coordinate vector.
virtual ~GFRecoHitIfc ()
virtual const GFDetPlane & getDetPlane (GFAbsTrackRep *rep)
Returns the detector plane object for this hit and a given track representation.
virtual void getMeasurement (const GFAbsTrackRep *rep, const GFDetPlane &pl, const TMatrixT< double > &statePred, const TMatrixT< double > &covPred, TMatrixT< double > &m, TMatrixT< double > &V)
Get measurement m,V and HMatrix.
const std::string & getPolicyName ()
ClassDef (GFRecoHitIfc, 1)
Public Member Functions inherited from GFAbsRecoHit
virtual ~GFAbsRecoHit ()
GFAbsRecoHit (int NparHit)
Constructor specifying dimension of coordinate vector.
GFAbsRecoHit ()
Default constructor needed for compatibility with ROOT.
TMatrixT< double > getRawHitCov () const
Get raw hit covariances.
TMatrixT< double > getRawHitCoord () const
Get raw hit coordinates.
double getRho ()
void setRho (double rho)
virtual void Print (const Option_t *option="") const
Print raw hit coordinates.
int getNparHit ()
Private Member Functions
ClassDef (PndHitRecoHit, 1)
Static Private Attributes
static const Int_t fNparHitRep = 3
Additional Inherited Members
Protected Attributes inherited from GFRecoHitIfc< GFSpacepointHitPolicy >
GFSpacepointHitPolicy fPolicy
Detailed Description
A planar (x,y) reco hit & its sensor plane.
Author
Ralf Kliemt Uni Bonn
Definition at line 35 of file PndHitRecoHit.h.
View newest version in sPHENIX GitHub at line 35 of file PndHitRecoHit.h
Constructor & Destructor Documentation
PndHitRecoHit::PndHitRecoHit ()
Definition at line 37 of file PndHitRecoHit.cxx.
View newest version in sPHENIX GitHub at line 37 of file PndHitRecoHit.cxx
Referenced by clone().
PndHitRecoHit::PndHitRecoHit (FairMCPoint * point)
Definition at line 43 of file PndHitRecoHit.cxx.
View newest version in sPHENIX GitHub at line 43 of file PndHitRecoHit.cxx
References GFAbsRecoHit::fHitCoord, GFAbsRecoHit::fHitCov, FairMCPoint::GetX(), FairMCPoint::GetY(), and FairMCPoint::GetZ().
PndHitRecoHit::PndHitRecoHit (FairHit * hit)
Definition at line 61 of file PndHitRecoHit.cxx.
View newest version in sPHENIX GitHub at line 61 of file PndHitRecoHit.cxx
References GFAbsRecoHit::fHitCoord, GFAbsRecoHit::fHitCov, FairHit::GetDx(), FairHit::GetDy(), FairHit::GetDz(), FairHit::GetX(), FairHit::GetY(), and FairHit::GetZ().
PndHitRecoHit::~PndHitRecoHit () virtual
Definition at line 33 of file PndHitRecoHit.cxx.
View newest version in sPHENIX GitHub at line 33 of file PndHitRecoHit.cxx
Member Function Documentation
PndHitRecoHit::ClassDef (PndHitRecoHit , 1) private
virtual GFAbsRecoHit* PndHitRecoHit::clone () inline virtual
Get clone of this object.
Virtual abstract method. Has to be implemented by inherting classes. Creates a deep copy of this object. Ownership is trandsferred to the caller!
Implements GFAbsRecoHit.
Definition at line 46 of file PndHitRecoHit.h.
View newest version in sPHENIX GitHub at line 46 of file PndHitRecoHit.h
References PndHitRecoHit().
TMatrixT< double > PndHitRecoHit::getHMatrix (const GFAbsTrackRep * stateVector) virtual
Get transformation matrix. Transformation between hit coordinates and track representation coordinates.
This is a virtual abstract method which has to be implemented in the child classes.
In general there is a linear transformation between the coordinate system of the hit (which is defined by the detector plane) and the coordinates of the track representation in that plane. In the most simple case the track representation has 5 parameters (space + momentum) while a hit usually has less (one to three space coordinates).
The transformation matrix is then simply projecting out the space-components of the track representation.
Its dimensions are NxM. Where N is the number of dimensions of the hit in the detector plane (usually 2 or 1) and M is the dimension of the track representation.
In this method a hit has to define with which track representations it can work together. It should be the only point where this explicit coordination is necessary.
For example code see implementing classes below:
Implements GFAbsRecoHit.
Definition at line 80 of file PndHitRecoHit.cxx.
View newest version in sPHENIX GitHub at line 80 of file PndHitRecoHit.cxx
References fNparHitRep.
Double_t PndHitRecoHit::residualScalar (GFAbsTrackRep * stateVector, const TMatrixT< Double_t > & state) virtual
Definition at line 129 of file PndHitRecoHit.cxx.
View newest version in sPHENIX GitHub at line 129 of file PndHitRecoHit.cxx
Member Data Documentation
const Int_t PndHitRecoHit::fNparHitRep = 3 static private
Definition at line 61 of file PndHitRecoHit.h.
View newest version in sPHENIX GitHub at line 61 of file PndHitRecoHit.h
Referenced by getHMatrix().
The documentation for this class was generated from the following files:
EicRoot/blob/master/GenfitTools/recohits/PndHitRecoHit.h
EicRoot/blob/master/GenfitTools/recohits/PndHitRecoHit.cxx