EIC Software: Acts::VertexInfo< input_track_t > Struct Template Reference
Acts::VertexInfo< input_track_t > Struct Template Reference
Helper struct for storing vertex related information.
#include <fun4all_acts/blob/master/Core/include/Acts/Vertexing/AMVFInfo.hpp>
Public Member Functions
VertexInfo ()=default
VertexInfo (const Acts::Vertex< input_track_t > &vtx, const Acts::SpacePointVector &pos)
Public Attributes
Acts::Vertex< input_track_t > constraintVertex
Acts::SpacePointVector linPoint {Acts::SpacePointVector::Zero()}
Acts::SpacePointVector oldPosition {Acts::SpacePointVector::Zero()}
Acts::SpacePointVector seedPosition {Acts::SpacePointVector::Zero()}
bool relinearize = true
std::vector< const
input_track_t * > trackLinks
std::map< const input_track_t
*, const BoundParameters > ip3dParams
Detailed Description
template<typename input_track_t>
struct Acts::VertexInfo< input_track_t >
Helper struct for storing vertex related information.
Definition at line 21 of file AMVFInfo.hpp.
View newest version in sPHENIX GitHub at line 21 of file AMVFInfo.hpp
Constructor & Destructor Documentation
template<typename input_track_t> Acts::VertexInfo< input_track_t >::VertexInfo () default
template<typename input_track_t> Acts::VertexInfo< input_track_t >::VertexInfo (const Acts::Vertex< input_track_t > & vtx, const Acts::SpacePointVector & pos) inline
Definition at line 24 of file AMVFInfo.hpp.
View newest version in sPHENIX GitHub at line 24 of file AMVFInfo.hpp
Member Data Documentation
template<typename input_track_t> Acts::Vertex<input_track_t> Acts::VertexInfo< input_track_t >::constraintVertex
Definition at line 32 of file AMVFInfo.hpp.
View newest version in sPHENIX GitHub at line 32 of file AMVFInfo.hpp
Referenced by Acts::Test::BOOST_AUTO_TEST_CASE().
template<typename input_track_t> std::map<const input_track_t*, const BoundParameters> Acts::VertexInfo< input_track_t >::ip3dParams
Definition at line 49 of file AMVFInfo.hpp.
View newest version in sPHENIX GitHub at line 49 of file AMVFInfo.hpp
Referenced by Acts::AdaptiveMultiVertexFitter< input_track_t, linearizer_t >::setAllVertexCompatibilities().
template<typename input_track_t> Acts::SpacePointVector Acts::VertexInfo< input_track_t >::linPoint {Acts::SpacePointVector::Zero()}
Definition at line 35 of file AMVFInfo.hpp.
View newest version in sPHENIX GitHub at line 35 of file AMVFInfo.hpp
Referenced by Acts::Test::BOOST_AUTO_TEST_CASE(), Acts::AdaptiveMultiVertexFitter< input_track_t, linearizer_t >::fitImpl(), and Acts::AdaptiveMultiVertexFitter< input_track_t, linearizer_t >::setAllVertexCompatibilities().
template<typename input_track_t> Acts::SpacePointVector Acts::VertexInfo< input_track_t >::oldPosition {Acts::SpacePointVector::Zero()}
Definition at line 38 of file AMVFInfo.hpp.
View newest version in sPHENIX GitHub at line 38 of file AMVFInfo.hpp
Referenced by Acts::Test::BOOST_AUTO_TEST_CASE(), Acts::AdaptiveMultiVertexFitter< input_track_t, linearizer_t >::fitImpl(), and Acts::AdaptiveMultiVertexFitter< input_track_t, linearizer_t >::setAllVertexCompatibilities().
template<typename input_track_t> bool Acts::VertexInfo< input_track_t >::relinearize = true
Definition at line 44 of file AMVFInfo.hpp.
View newest version in sPHENIX GitHub at line 44 of file AMVFInfo.hpp
Referenced by Acts::AdaptiveMultiVertexFitter< input_track_t, linearizer_t >::fitImpl().
template<typename input_track_t> Acts::SpacePointVector Acts::VertexInfo< input_track_t >::seedPosition {Acts::SpacePointVector::Zero()}
Definition at line 41 of file AMVFInfo.hpp.
View newest version in sPHENIX GitHub at line 41 of file AMVFInfo.hpp
Referenced by Acts::Test::BOOST_AUTO_TEST_CASE().
template<typename input_track_t> std::vector<const input_track_t*> Acts::VertexInfo< input_track_t >::trackLinks
Definition at line 47 of file AMVFInfo.hpp.
View newest version in sPHENIX GitHub at line 47 of file AMVFInfo.hpp
Referenced by Acts::Test::BOOST_AUTO_TEST_CASE(), Acts::AdaptiveMultiVertexFitter< input_track_t, linearizer_t >::setAllVertexCompatibilities(), and Acts::AdaptiveMultiVertexFitter< input_track_t, linearizer_t >::setWeightsAndUpdate().
The documentation for this struct was generated from the following file:
fun4all_acts/blob/master/Core/include/Acts/Vertexing/AMVFInfo.hpp