EIC Software: EtmDetectorStack Class Reference
EtmDetectorStack Class Reference
#include <EicToyModel/blob/master/include/EtmDetectorStack.h>
Public Member Functions
EtmDetectorStack (const char *label=0, double etamin=0.0, double etamax=0.0)
~EtmDetectorStack ()
EtmDetector * add (const char *tag, double length)
EtmDetector * add (const char *tag, int color, double length)
EtmDetector * gap (double length)
EtmDetector * marker (void)
EtmDetector * insert (const char *tag, double length, const char *after, unsigned order=0)
void rm (const char *dname)
void rm (const char *dname, unsigned order)
void offset (double dstart=0.0)
double etamin (void) const
double etamax (void) const
EtmDetector * get (const char *dname, unsigned order=0) const
void SetEtaBoundaries (double min, double max)
EtmEtaBoundary * EtaBoundary (unsigned mm) const
const TVector2 & AlignmentAxis (void) const
const TString & GetLabel (void) const
unsigned DetectorCount (void) const
const EtmDetector * GetDetector (unsigned id) const
Private Member Functions
double FullLength (void) const
void CalculateAlignmentAxis (void)
EtmDetector * CreateDetector (const char *tag, double length)
void Build (void)
void CalculateActualDistances (void)
Private Attributes
TString mLabel
std::vector< EtmDetector * > mDetectors
EtmEtaBoundary * mEtaBoundaries [2]
double mStartingDistance
double mFullLength
TVector2 mAlignmentAxis
EtmDetector * mDummyDetector
Friends
class EicToyModel
class EtmAzimuthalScan
Detailed Description
Definition at line 13 of file EtmDetectorStack.h.
View newest version in sPHENIX GitHub at line 13 of file EtmDetectorStack.h
Constructor & Destructor Documentation
EtmDetectorStack::EtmDetectorStack (const char * label = 0, double etamin = 0.0, double etamax = 0.0)
Definition at line 10 of file EtmDetectorStack.cc.
View newest version in sPHENIX GitHub at line 10 of file EtmDetectorStack.cc
References mDummyDetector, mEtaBoundaries, mLabel, and SetEtaBoundaries().
EtmDetectorStack::~EtmDetectorStack () inline
Definition at line 19 of file EtmDetectorStack.h.
View newest version in sPHENIX GitHub at line 19 of file EtmDetectorStack.h
Member Function Documentation
EtmDetector * EtmDetectorStack::add (const char * tag, double length)
Definition at line 67 of file EtmDetectorStack.cc.
View newest version in sPHENIX GitHub at line 67 of file EtmDetectorStack.cc
References CreateDetector(), EicToyModel::home(), EicToyModel::Instance(), and mDetectors.
Referenced by add(), gap(), and marker().
EtmDetector * EtmDetectorStack::add (const char * tag, int color, double length)
Definition at line 82 of file EtmDetectorStack.cc.
View newest version in sPHENIX GitHub at line 82 of file EtmDetectorStack.cc
References add(), AddEntry(), and EicToyModel::Instance().
const TVector2& EtmDetectorStack::AlignmentAxis (void) const inline
Definition at line 54 of file EtmDetectorStack.h.
View newest version in sPHENIX GitHub at line 54 of file EtmDetectorStack.h
References mAlignmentAxis.
Referenced by EtmDetector::Build(), and EtmDetector::PlaceG4Volume().
void EtmDetectorStack::Build (void) private
Definition at line 215 of file EtmDetectorStack.cc.
View newest version in sPHENIX GitHub at line 215 of file EtmDetectorStack.cc
References mDetectors.
void EtmDetectorStack::CalculateActualDistances (void) private
Definition at line 198 of file EtmDetectorStack.cc.
View newest version in sPHENIX GitHub at line 198 of file EtmDetectorStack.cc
References eic, EicToyModel::Instance(), mDetectors, mFullLength, and mStartingDistance.
void EtmDetectorStack::CalculateAlignmentAxis (void) private
Definition at line 128 of file EtmDetectorStack.cc.
View newest version in sPHENIX GitHub at line 128 of file EtmDetectorStack.cc
References cos(), EtmEtaBoundary::GetEta(), M_PI, mAlignmentAxis, and mEtaBoundaries.
Referenced by SetEtaBoundaries().
EtmDetector * EtmDetectorStack::CreateDetector (const char * tag, double length) private
Definition at line 42 of file EtmDetectorStack.cc.
View newest version in sPHENIX GitHub at line 42 of file EtmDetectorStack.cc
References color, eic, EicToyModel::Instance(), and printf().
Referenced by add(), and insert().
unsigned EtmDetectorStack::DetectorCount (void) const inline
Definition at line 56 of file EtmDetectorStack.h.
View newest version in sPHENIX GitHub at line 56 of file EtmDetectorStack.h
References mDetectors.
Referenced by EtmDetector::GetOrder().
EtmEtaBoundary* EtmDetectorStack::EtaBoundary (unsigned mm) const inline
Definition at line 51 of file EtmDetectorStack.h.
View newest version in sPHENIX GitHub at line 51 of file EtmDetectorStack.h
References mEtaBoundaries.
Referenced by EtmDetector::Build(), EicToyModel::ExecuteBoundaryModificationRequests(), and EicToyModel::GetStack().
double EtmDetectorStack::etamax (void) const inline
Definition at line 43 of file EtmDetectorStack.h.
View newest version in sPHENIX GitHub at line 43 of file EtmDetectorStack.h
References EtmEtaBoundary::GetEta(), and mEtaBoundaries.
Referenced by genevent(), getdeltat(), init(), insudaint(), pdfint(), splitfncint(), and xsecint().
double EtmDetectorStack::etamin (void) const inline
Definition at line 42 of file EtmDetectorStack.h.
View newest version in sPHENIX GitHub at line 42 of file EtmDetectorStack.h
References EtmEtaBoundary::GetEta(), and mEtaBoundaries.
Referenced by EicToyModel::GetStack().
double EtmDetectorStack::FullLength (void) const inline private
Definition at line 62 of file EtmDetectorStack.h.
View newest version in sPHENIX GitHub at line 62 of file EtmDetectorStack.h
References mFullLength.
Referenced by EicToyModel::CalculateDefaultEtaBoundaries().
EtmDetector* EtmDetectorStack::gap (double length) inline
Definition at line 27 of file EtmDetectorStack.h.
View newest version in sPHENIX GitHub at line 27 of file EtmDetectorStack.h
References add().
EtmDetector * EtmDetectorStack::get (const char * dname, unsigned order = 0) const
Definition at line 179 of file EtmDetectorStack.cc.
View newest version in sPHENIX GitHub at line 179 of file EtmDetectorStack.cc
References mDetectors, and mDummyDetector.
Referenced by EtmDetector::stretch().
const EtmDetector* EtmDetectorStack::GetDetector (unsigned id) const inline
Definition at line 57 of file EtmDetectorStack.h.
View newest version in sPHENIX GitHub at line 57 of file EtmDetectorStack.h
References mDetectors.
Referenced by EtmDetector::GetOrder().
const TString& EtmDetectorStack::GetLabel (void) const inline
Definition at line 55 of file EtmDetectorStack.h.
View newest version in sPHENIX GitHub at line 55 of file EtmDetectorStack.h
References mLabel.
Referenced by EtmDetector::PlaceG4Volume().
EtmDetector * EtmDetectorStack::insert (const char * tag, double length, const char * after, unsigned order = 0)
Definition at line 104 of file EtmDetectorStack.cc.
View newest version in sPHENIX GitHub at line 104 of file EtmDetectorStack.cc
References CreateDetector(), eic, EicToyModel::Instance(), it, and mDetectors.
EtmDetector * EtmDetectorStack::marker (void)
Definition at line 90 of file EtmDetectorStack.cc.
View newest version in sPHENIX GitHub at line 90 of file EtmDetectorStack.cc
References _MARKER_, add(), mDummyDetector, and printf().
void EtmDetectorStack::offset (double dstart = 0.0)
Definition at line 35 of file EtmDetectorStack.cc.
View newest version in sPHENIX GitHub at line 35 of file EtmDetectorStack.cc
References mStartingDistance.
void EtmDetectorStack::rm (const char * dname)
Definition at line 144 of file EtmDetectorStack.cc.
View newest version in sPHENIX GitHub at line 144 of file EtmDetectorStack.cc
References eic, EicToyModel::Instance(), it, and mDetectors.
Referenced by pyqqbh(), pyrvg1(), pyrvg2(), pyrvg3(), pyrvg4(), pyrvi1(), pyrvi2(), pyrvi3(), pyrvr(), strc10(), strc11(), strc20(), and strc21().
void EtmDetectorStack::rm (const char * dname, unsigned order)
Definition at line 164 of file EtmDetectorStack.cc.
View newest version in sPHENIX GitHub at line 164 of file EtmDetectorStack.cc
References eic, EicToyModel::Instance(), it, and mDetectors.
void EtmDetectorStack::SetEtaBoundaries (double min, double max)
Definition at line 25 of file EtmDetectorStack.cc.
View newest version in sPHENIX GitHub at line 25 of file EtmDetectorStack.cc
References CalculateAlignmentAxis(), mEtaBoundaries, and EtmEtaBoundary::SetEta().
Referenced by EicToyModel::acceptance(), and EtmDetectorStack().
Friends And Related Function Documentation
friend class EicToyModel friend
Definition at line 14 of file EtmDetectorStack.h.
View newest version in sPHENIX GitHub at line 14 of file EtmDetectorStack.h
friend class EtmAzimuthalScan friend
Definition at line 15 of file EtmDetectorStack.h.
View newest version in sPHENIX GitHub at line 15 of file EtmDetectorStack.h
Member Data Documentation
TVector2 EtmDetectorStack::mAlignmentAxis private
Definition at line 80 of file EtmDetectorStack.h.
View newest version in sPHENIX GitHub at line 80 of file EtmDetectorStack.h
Referenced by AlignmentAxis(), and CalculateAlignmentAxis().
std::vector<EtmDetector*> EtmDetectorStack::mDetectors private
Definition at line 74 of file EtmDetectorStack.h.
View newest version in sPHENIX GitHub at line 74 of file EtmDetectorStack.h
Referenced by add(), Build(), CalculateActualDistances(), DetectorCount(), get(), GetDetector(), insert(), and rm().
EtmDetector* EtmDetectorStack::mDummyDetector private
Definition at line 84 of file EtmDetectorStack.h.
View newest version in sPHENIX GitHub at line 84 of file EtmDetectorStack.h
Referenced by EtmDetectorStack(), get(), and marker().
EtmEtaBoundary* EtmDetectorStack::mEtaBoundaries[2] private
Definition at line 76 of file EtmDetectorStack.h.
View newest version in sPHENIX GitHub at line 76 of file EtmDetectorStack.h
Referenced by CalculateAlignmentAxis(), EicToyModel::CalculateDefaultEtaBoundaries(), EtaBoundary(), etamax(), etamin(), EtmDetectorStack(), and SetEtaBoundaries().
double EtmDetectorStack::mFullLength private
Definition at line 77 of file EtmDetectorStack.h.
View newest version in sPHENIX GitHub at line 77 of file EtmDetectorStack.h
Referenced by CalculateActualDistances(), and FullLength().
TString EtmDetectorStack::mLabel private
Definition at line 70 of file EtmDetectorStack.h.
View newest version in sPHENIX GitHub at line 70 of file EtmDetectorStack.h
Referenced by EtmDetectorStack(), and GetLabel().
double EtmDetectorStack::mStartingDistance private
Definition at line 77 of file EtmDetectorStack.h.
View newest version in sPHENIX GitHub at line 77 of file EtmDetectorStack.h
Referenced by CalculateActualDistances(), EicToyModel::CalculateDefaultEtaBoundaries(), and offset().
The documentation for this class was generated from the following files:
EicToyModel/blob/master/include/EtmDetectorStack.h
EicToyModel/blob/master/source/EtmDetectorStack.cc