EIC Software: Acts::Seedfinder< external_spacepoint_t > Class Template Reference
Acts::Seedfinder< external_spacepoint_t > Class Template Reference
#include <fun4all_acts/blob/master/Core/include/Acts/Seeding/Seedfinder.hpp>
Public Member Functions
Seedfinder (Acts::SeedfinderConfig< external_spacepoint_t > config)
~Seedfinder ()=default
template<typename sp_range_t >
std::vector< Seed
< external_spacepoint_t > > createSeedsForGroup (sp_range_t bottomSPs, sp_range_t middleSPs, sp_range_t topSPs) const
Disallow default instantiation, copy, assignment
Seedfinder ()=delete
Seedfinder (const Seedfinder< external_spacepoint_t > &)=delete
Seedfinder
< external_spacepoint_t > & operator= (const Seedfinder< external_spacepoint_t > &)=delete
Private Member Functions
void transformCoordinates (std::vector< const InternalSpacePoint< external_spacepoint_t > * > &vec, const InternalSpacePoint< external_spacepoint_t > &spM, bool bottom, std::vector< LinCircle > &linCircleVec) const
Private Attributes
Acts::SeedfinderConfig
< external_spacepoint_t > m_config
Detailed Description
template<typename external_spacepoint_t>
class Acts::Seedfinder< external_spacepoint_t >
Definition at line 34 of file Seedfinder.hpp.
View newest version in sPHENIX GitHub at line 34 of file Seedfinder.hpp
Constructor & Destructor Documentation
template<typename external_spacepoint_t > Acts::Seedfinder< external_spacepoint_t >::Seedfinder (Acts::SeedfinderConfig< external_spacepoint_t > config)
The only constructor. Requires a config object.
Parameters
config the configuration for the Seedfinder
Definition at line 18 of file Seedfinder.ipp.
View newest version in sPHENIX GitHub at line 18 of file Seedfinder.ipp
References Acts::SeedfinderConfig< SpacePoint >::bFieldInZ, Acts::SeedfinderConfig< SpacePoint >::highland, Acts::Seedfinder< external_spacepoint_t >::m_config, Acts::SeedfinderConfig< SpacePoint >::maxScatteringAngle2, Acts::SeedfinderConfig< SpacePoint >::minHelixDiameter2, Acts::SeedfinderConfig< SpacePoint >::minPt, Acts::SeedfinderConfig< SpacePoint >::pT2perRadius, Acts::SeedfinderConfig< SpacePoint >::pTPerHelixRadius, and Acts::SeedfinderConfig< SpacePoint >::radLengthPerSeed.
template<typename external_spacepoint_t> Acts::Seedfinder< external_spacepoint_t >::~Seedfinder () default
template<typename external_spacepoint_t> Acts::Seedfinder< external_spacepoint_t >::Seedfinder () delete
template<typename external_spacepoint_t> Acts::Seedfinder< external_spacepoint_t >::Seedfinder (const Seedfinder< external_spacepoint_t > &) delete
Member Function Documentation
template<typename external_spacepoint_t > template<typename sp_range_t > std::vector< Seed< external_spacepoint_t > > Acts::Seedfinder< external_spacepoint_t >::createSeedsForGroup (sp_range_t bottomSPs, sp_range_t middleSPs, sp_range_t topSPs) const
Create all seeds from the space points in the three iterators. Can be used to parallelize the seed creation
Parameters
bottom group of space points to be used as innermost SP in a seed.
middle group of space points to be used as middle SP in a seed.
top group of space points to be used as outermost SP in a seed. Ranges must return pointers. Ranges must be separate objects for each parallel call.
Returns
vector in which all found seeds for this group are stored.
Definition at line 40 of file Seedfinder.ipp.
View newest version in sPHENIX GitHub at line 40 of file Seedfinder.ipp
References kdfinder::abs(), b, deltaR(), t, and vector().
Referenced by main(), and PHActsSiliconSeeding::runSeeder().
template<typename external_spacepoint_t> Seedfinder<external_spacepoint_t>& Acts::Seedfinder< external_spacepoint_t >::operator= (const Seedfinder< external_spacepoint_t > &) delete
template<typename external_spacepoint_t > void Acts::Seedfinder< external_spacepoint_t >::transformCoordinates (std::vector< const InternalSpacePoint< external_spacepoint_t > * > & vec, const InternalSpacePoint< external_spacepoint_t > & spM, bool bottom, std::vector< LinCircle > & linCircleVec) const private
Definition at line 249 of file Seedfinder.ipp.
View newest version in sPHENIX GitHub at line 249 of file Seedfinder.ipp
References Acts::LinCircle::cotTheta, Acts::LinCircle::Er, Acts::LinCircle::iDeltaR, Acts::InternalSpacePoint< SpacePoint >::radius(), Acts::LinCircle::U, Acts::LinCircle::V, Acts::InternalSpacePoint< SpacePoint >::varianceR(), Acts::InternalSpacePoint< SpacePoint >::varianceZ(), Acts::InternalSpacePoint< SpacePoint >::x(), x, Acts::InternalSpacePoint< SpacePoint >::y(), analysis::y, Acts::InternalSpacePoint< SpacePoint >::z(), and Acts::LinCircle::Zo.
Member Data Documentation
template<typename external_spacepoint_t> Acts::SeedfinderConfig<external_spacepoint_t> Acts::Seedfinder< external_spacepoint_t >::m_config private
Definition at line 70 of file Seedfinder.hpp.
View newest version in sPHENIX GitHub at line 70 of file Seedfinder.hpp
Referenced by Acts::Seedfinder< external_spacepoint_t >::Seedfinder().
The documentation for this class was generated from the following files:
fun4all_acts/blob/master/Core/include/Acts/Seeding/Seedfinder.hpp
fun4all_acts/blob/master/Core/include/Acts/Seeding/Seedfinder.ipp