EIC Software: EicRcParticle Class Reference
EicRcParticle Class Reference
#include <EicRoot/blob/master/eic/event/EicRcParticle.h>
Public Types
enum HadronPidType { PionKaonProton, PionKaon, KaonProton, PionProton }
Public Member Functions
EicRcParticle ()
~EicRcParticle ()
virtual Double_t GetPx () const
virtual Double_t GetPy () const
virtual Double_t GetPz () const
virtual Double_t GetP () const
virtual Double_t GetPt () const
virtual Double_t GetTheta () const
virtual Double_t GetPhi () const
virtual Double_t GetRapidity () const
virtual Double_t GetEta () const
virtual TVector3 GetVertex () const
void SetVertex (const TVector3 &)
erhic::Pid Id () const
virtual Double_t GetM () const
virtual Double_t GetE () const
virtual TLorentzVector Get4Vector () const
virtual UShort_t GetStatus () const
void Set4Vector (const TLorentzVector &)
virtual UShort_t GetParentIndex () const
int GetGeneratorIndex () const
int GetPndPidChargedCandIndex () const
int GetPndMCTrackIndex () const
const PndMCTrack * GetPndMcTrack () const
const PndMCTrack * pndmc () const
const PndPidCandidate * GetPndPidCandidate () const
const PndPidCandidate * pndrc () const
const erhic::ParticleMC * GetGeneratorTrack () const
const erhic::ParticleMC * genmc () const
const EicRcParticle * eicrc () const
const TVector3 GetMcVertex () const
const TVector3 GetRcVertex () const
const TVector3 GetMcVtxMomentum () const
const TVector3 GetRcVtxMomentum () const
double GetRcTrackerMomentumSigma () const
void SetRcVtxMomentum (TVector3 &momentum)
int GetMcPdgCode () const
int GetRcPdgCode () const
double GetEmCalEnergy () const
double GetHCalEnergy () const
Public Member Functions inherited from erhic::VirtualParticle
virtual ~VirtualParticle ()
Private Member Functions
ClassDef (EicRcParticle, 16)
Private Attributes
int mGeneratorEventIndex
int mPndMCTrackIndex
int mPndPidChargedCandIndex
int mRcPdgCode
float mChargeDefCL
float mElectronPidCL
std::vector< std::pair
< HadronPidType, float > > mHadronPidCL
TVector3 mRcVertex
TVector3 mRcVtxMomentum
Double_t mRcTrackerMomentumSigma
std::vector< std::pair
< unsigned, unsigned > > mCellGroups
EicRcCalorimeterHit * mEmCal
EicRcCalorimeterHit * mHCal
Friends
class EicEventAssembler
Detailed Description
Definition at line 41 of file EicRcParticle.h.
View newest version in sPHENIX GitHub at line 41 of file EicRcParticle.h
Member Enumeration Documentation
enum EicRcParticle::HadronPidType
Enumerator:
PionKaonProton
PionKaon
KaonProton
PionProton
Definition at line 186 of file EicRcParticle.h.
View newest version in sPHENIX GitHub at line 186 of file EicRcParticle.h
Constructor & Destructor Documentation
EicRcParticle::EicRcParticle () inline
Definition at line 46 of file EicRcParticle.h.
View newest version in sPHENIX GitHub at line 46 of file EicRcParticle.h
References mEmCal, and mHCal.
EicRcParticle::~EicRcParticle () inline
Definition at line 50 of file EicRcParticle.h.
View newest version in sPHENIX GitHub at line 50 of file EicRcParticle.h
Member Function Documentation
EicRcParticle::ClassDef (EicRcParticle , 16) private
const EicRcParticle* EicRcParticle::eicrc () const inline
Definition at line 123 of file EicRcParticle.h.
View newest version in sPHENIX GitHub at line 123 of file EicRcParticle.h
const erhic::ParticleMC* EicRcParticle::genmc () const inline
Definition at line 120 of file EicRcParticle.h.
View newest version in sPHENIX GitHub at line 120 of file EicRcParticle.h
References GetGeneratorTrack().
virtual TLorentzVector EicRcParticle::Get4Vector () const inline virtual
Returns the momentum-energy four-vector (px, py, pz, E).
Implements erhic::VirtualParticle.
Definition at line 89 of file EicRcParticle.h.
View newest version in sPHENIX GitHub at line 89 of file EicRcParticle.h
References GetE(), GetPx(), GetPy(), and GetPz().
virtual Double_t EicRcParticle::GetE () const inline virtual
Returns total energy.
Implements erhic::VirtualParticle.
Definition at line 85 of file EicRcParticle.h.
View newest version in sPHENIX GitHub at line 85 of file EicRcParticle.h
References GetM(), and GetP().
Referenced by EicEventAssembler::AssignScatteredLepton(), EicEventAssembler::Exec(), Get4Vector(), and GetRapidity().
double EicRcParticle::GetEmCalEnergy () const inline
Definition at line 171 of file EicRcParticle.h.
View newest version in sPHENIX GitHub at line 171 of file EicRcParticle.h
References mEmCal, and EicRcCalorimeterHit::mEnergy.
Double_t EicRcParticle::GetEta () const virtual
Returns the pseudorapidity.
Implements erhic::VirtualParticle.
Definition at line 24 of file EicRcParticle.cxx.
View newest version in sPHENIX GitHub at line 24 of file EicRcParticle.cxx
References _DEFAULT_RAPIDITY_, GetTheta(), and theta().
int EicRcParticle::GetGeneratorIndex () const inline
Definition at line 103 of file EicRcParticle.h.
View newest version in sPHENIX GitHub at line 103 of file EicRcParticle.h
References mGeneratorEventIndex.
Referenced by EicRcEvent::GetRcParticleMatchingGenMcTrack().
const erhic::ParticleMC * EicRcParticle::GetGeneratorTrack () const
Definition at line 43 of file EicRcParticle.cxx.
View newest version in sPHENIX GitHub at line 43 of file EicRcParticle.cxx
References EicRootManager::GetGenMcTrack(), EicRootManager::Instance(), and mGeneratorEventIndex.
Referenced by genmc().
double EicRcParticle::GetHCalEnergy () const inline
Definition at line 172 of file EicRcParticle.h.
View newest version in sPHENIX GitHub at line 172 of file EicRcParticle.h
virtual Double_t EicRcParticle::GetM () const inline virtual
Returns invariant mass (GeV/c2).
Implements erhic::VirtualParticle.
Definition at line 80 of file EicRcParticle.h.
View newest version in sPHENIX GitHub at line 80 of file EicRcParticle.h
References Id(), and erhic::Pid::Info().
Referenced by GetE().
int EicRcParticle::GetMcPdgCode () const inline
Definition at line 162 of file EicRcParticle.h.
View newest version in sPHENIX GitHub at line 162 of file EicRcParticle.h
References PndMCTrack::GetPdgCode(), and GetPndMcTrack().
Referenced by EicEventAssembler::AssignScatteredLepton(), and EicEventAssembler::Exec().
const TVector3 EicRcParticle::GetMcVertex () const inline
Definition at line 141 of file EicRcParticle.h.
View newest version in sPHENIX GitHub at line 141 of file EicRcParticle.h
References GetPndMcTrack(), and PndMCTrack::GetStartVertex().
const TVector3 EicRcParticle::GetMcVtxMomentum () const inline
Definition at line 151 of file EicRcParticle.h.
View newest version in sPHENIX GitHub at line 151 of file EicRcParticle.h
References PndMCTrack::GetMomentum(), and GetPndMcTrack().
virtual Double_t EicRcParticle::GetP () const inline virtual
Returns the magnitude of 3-momentum (GeV).
Implements erhic::VirtualParticle.
Definition at line 60 of file EicRcParticle.h.
View newest version in sPHENIX GitHub at line 60 of file EicRcParticle.h
References mRcVtxMomentum.
Referenced by GetE().
virtual UShort_t EicRcParticle::GetParentIndex () const inline virtual
Returns the index of the parent particle
Implements erhic::VirtualParticle.
Definition at line 98 of file EicRcParticle.h.
View newest version in sPHENIX GitHub at line 98 of file EicRcParticle.h
virtual Double_t EicRcParticle::GetPhi () const inline virtual
Returns the polar angle in the range [0, 2pi] radians.
Implements erhic::VirtualParticle.
Definition at line 63 of file EicRcParticle.h.
View newest version in sPHENIX GitHub at line 63 of file EicRcParticle.h
References mRcVtxMomentum.
const PndMCTrack * EicRcParticle::GetPndMcTrack () const
Definition at line 52 of file EicRcParticle.cxx.
View newest version in sPHENIX GitHub at line 52 of file EicRcParticle.cxx
References EicRootManager::GetPndMcBranch(), EicRootManager::GetPndMcTracks(), EicRootManager::Instance(), mPndMCTrackIndex, and EicRootManager::SynchronizeBranch().
Referenced by GetMcPdgCode(), GetMcVertex(), GetMcVtxMomentum(), and pndmc().
int EicRcParticle::GetPndMCTrackIndex () const inline
Definition at line 105 of file EicRcParticle.h.
View newest version in sPHENIX GitHub at line 105 of file EicRcParticle.h
References mPndMCTrackIndex.
Referenced by EicRcEvent::GetRcParticleMatchingGenMcTrack().
const PndPidCandidate * EicRcParticle::GetPndPidCandidate () const
Definition at line 65 of file EicRcParticle.cxx.
View newest version in sPHENIX GitHub at line 65 of file EicRcParticle.cxx
References EicRootManager::GetPndPidBranch(), EicRootManager::GetPndPidCandidates(), EicRootManager::Instance(), mPndPidChargedCandIndex, and EicRootManager::SynchronizeBranch().
Referenced by pndrc().
int EicRcParticle::GetPndPidChargedCandIndex () const inline
Definition at line 104 of file EicRcParticle.h.
View newest version in sPHENIX GitHub at line 104 of file EicRcParticle.h
References mPndPidChargedCandIndex.
virtual Double_t EicRcParticle::GetPt () const inline virtual
Returns momentum perpendicular to the beam direction.
Implements erhic::VirtualParticle.
Definition at line 61 of file EicRcParticle.h.
View newest version in sPHENIX GitHub at line 61 of file EicRcParticle.h
References mRcVtxMomentum.
virtual Double_t EicRcParticle::GetPx () const inline virtual
Returns the x component of 3-momentum.
Implements erhic::VirtualParticle.
Definition at line 57 of file EicRcParticle.h.
View newest version in sPHENIX GitHub at line 57 of file EicRcParticle.h
References mRcVtxMomentum.
Referenced by Get4Vector().
virtual Double_t EicRcParticle::GetPy () const inline virtual
Returns the y component of 3-momentum.
Implements erhic::VirtualParticle.
Definition at line 58 of file EicRcParticle.h.
View newest version in sPHENIX GitHub at line 58 of file EicRcParticle.h
References mRcVtxMomentum.
Referenced by Get4Vector().
virtual Double_t EicRcParticle::GetPz () const inline virtual
Returns the z component of 3-momentum.
Implements erhic::VirtualParticle.
Definition at line 59 of file EicRcParticle.h.
View newest version in sPHENIX GitHub at line 59 of file EicRcParticle.h
References mRcVtxMomentum.
Referenced by Get4Vector(), and GetRapidity().
Double_t EicRcParticle::GetRapidity () const virtual
Returns the rapidity.
Implements erhic::VirtualParticle.
Definition at line 32 of file EicRcParticle.cxx.
View newest version in sPHENIX GitHub at line 32 of file EicRcParticle.cxx
References _DEFAULT_RAPIDITY_, GetE(), and GetPz().
int EicRcParticle::GetRcPdgCode () const inline
Definition at line 169 of file EicRcParticle.h.
View newest version in sPHENIX GitHub at line 169 of file EicRcParticle.h
References mRcPdgCode.
double EicRcParticle::GetRcTrackerMomentumSigma () const inline
Definition at line 157 of file EicRcParticle.h.
View newest version in sPHENIX GitHub at line 157 of file EicRcParticle.h
References mRcTrackerMomentumSigma.
const TVector3 EicRcParticle::GetRcVertex () const inline
Definition at line 147 of file EicRcParticle.h.
View newest version in sPHENIX GitHub at line 147 of file EicRcParticle.h
References mRcVertex.
const TVector3 EicRcParticle::GetRcVtxMomentum () const inline
Definition at line 156 of file EicRcParticle.h.
View newest version in sPHENIX GitHub at line 156 of file EicRcParticle.h
References mRcVtxMomentum.
virtual UShort_t EicRcParticle::GetStatus () const inline virtual
A general "status" code for the particle (definition depends on implementation).
Implements erhic::VirtualParticle.
Definition at line 94 of file EicRcParticle.h.
View newest version in sPHENIX GitHub at line 94 of file EicRcParticle.h
References exit().
virtual Double_t EicRcParticle::GetTheta () const inline virtual
Returns the polar angle in the range [0, pi] radians.
Implements erhic::VirtualParticle.
Definition at line 62 of file EicRcParticle.h.
View newest version in sPHENIX GitHub at line 62 of file EicRcParticle.h
References mRcVtxMomentum.
Referenced by GetEta().
virtual TVector3 EicRcParticle::GetVertex () const inline virtual
Returns the origin point of the particle in cm. (0,0,0) indicates a particle originating in the collision.
Implements erhic::VirtualParticle.
Definition at line 69 of file EicRcParticle.h.
View newest version in sPHENIX GitHub at line 69 of file EicRcParticle.h
References mRcVertex.
erhic::Pid EicRcParticle::Id () const inline virtual
Returns identity information for the Particle species.
Implements erhic::VirtualParticle.
Definition at line 74 of file EicRcParticle.h.
View newest version in sPHENIX GitHub at line 74 of file EicRcParticle.h
References mRcPdgCode.
Referenced by GetM().
const PndMCTrack* EicRcParticle::pndmc () const inline
Definition at line 112 of file EicRcParticle.h.
View newest version in sPHENIX GitHub at line 112 of file EicRcParticle.h
References GetPndMcTrack().
const PndPidCandidate* EicRcParticle::pndrc () const inline
Definition at line 116 of file EicRcParticle.h.
View newest version in sPHENIX GitHub at line 116 of file EicRcParticle.h
References GetPndPidCandidate().
void EicRcParticle::Set4Vector (const TLorentzVector &) inline virtual
Sets the four-momentum of the particle. Changes are propagated to derived quantities.
Implements erhic::VirtualParticle.
Definition at line 96 of file EicRcParticle.h.
View newest version in sPHENIX GitHub at line 96 of file EicRcParticle.h
void EicRcParticle::SetRcVtxMomentum (TVector3 & momentum) inline
Definition at line 159 of file EicRcParticle.h.
View newest version in sPHENIX GitHub at line 159 of file EicRcParticle.h
References momentum, and mRcVtxMomentum.
void EicRcParticle::SetVertex (const TVector3 &) inline virtual
Sets the origin coordinates
Implements erhic::VirtualParticle.
Definition at line 72 of file EicRcParticle.h.
View newest version in sPHENIX GitHub at line 72 of file EicRcParticle.h
References exit().
Friends And Related Function Documentation
friend class EicEventAssembler friend
Definition at line 43 of file EicRcParticle.h.
View newest version in sPHENIX GitHub at line 43 of file EicRcParticle.h
Member Data Documentation
std::vector<std::pair<unsigned, unsigned> > EicRcParticle::mCellGroups private
Definition at line 283 of file EicRcParticle.h.
View newest version in sPHENIX GitHub at line 283 of file EicRcParticle.h
Referenced by EicEventAssembler::ComposeCalorimeterInformation(), and EicEventAssembler::Exec().
float EicRcParticle::mChargeDefCL private
Definition at line 234 of file EicRcParticle.h.
View newest version in sPHENIX GitHub at line 234 of file EicRcParticle.h
float EicRcParticle::mElectronPidCL private
Definition at line 235 of file EicRcParticle.h.
View newest version in sPHENIX GitHub at line 235 of file EicRcParticle.h
EicRcCalorimeterHit* EicRcParticle::mEmCal private
Definition at line 284 of file EicRcParticle.h.
View newest version in sPHENIX GitHub at line 284 of file EicRcParticle.h
Referenced by EicEventAssembler::ComposeCalorimeterInformation(), EicRcParticle(), GetEmCalEnergy(), EicEventAssembler::PerformPidCalculations(), and EicEventAssembler::ReAssignMomentumValue().
int EicRcParticle::mGeneratorEventIndex private
Definition at line 172 of file EicRcParticle.h.
View newest version in sPHENIX GitHub at line 172 of file EicRcParticle.h
Referenced by EicEventAssembler::Exec(), GetGeneratorIndex(), and GetGeneratorTrack().
std::vector< std::pair<HadronPidType, float> > EicRcParticle::mHadronPidCL private
Definition at line 239 of file EicRcParticle.h.
View newest version in sPHENIX GitHub at line 239 of file EicRcParticle.h
EicRcCalorimeterHit * EicRcParticle::mHCal private
Definition at line 284 of file EicRcParticle.h.
View newest version in sPHENIX GitHub at line 284 of file EicRcParticle.h
Referenced by EicEventAssembler::ComposeCalorimeterInformation(), EicRcParticle(), and EicEventAssembler::ReAssignMomentumValue().
int EicRcParticle::mPndMCTrackIndex private
Definition at line 177 of file EicRcParticle.h.
View newest version in sPHENIX GitHub at line 177 of file EicRcParticle.h
Referenced by EicEventAssembler::ComposeCalorimeterInformation(), EicEventAssembler::Exec(), GetPndMcTrack(), and GetPndMCTrackIndex().
int EicRcParticle::mPndPidChargedCandIndex private
Definition at line 178 of file EicRcParticle.h.
View newest version in sPHENIX GitHub at line 178 of file EicRcParticle.h
Referenced by EicEventAssembler::Exec(), GetPndPidCandidate(), GetPndPidChargedCandIndex(), and EicEventAssembler::PerformPidCalculations().
int EicRcParticle::mRcPdgCode private
Definition at line 232 of file EicRcParticle.h.
View newest version in sPHENIX GitHub at line 232 of file EicRcParticle.h
Referenced by EicEventAssembler::AssignScatteredLepton(), GetRcPdgCode(), Id(), EicEventAssembler::PerformPidCalculations(), and EicEventAssembler::ReAssignMomentumValue().
Double_t EicRcParticle::mRcTrackerMomentumSigma private
Definition at line 270 of file EicRcParticle.h.
View newest version in sPHENIX GitHub at line 270 of file EicRcParticle.h
Referenced by EicEventAssembler::Exec(), GetRcTrackerMomentumSigma(), EicEventAssembler::PerformPidCalculations(), and EicEventAssembler::ReAssignMomentumValue().
TVector3 EicRcParticle::mRcVertex private
Definition at line 248 of file EicRcParticle.h.
View newest version in sPHENIX GitHub at line 248 of file EicRcParticle.h
Referenced by EicEventAssembler::Exec(), GetRcVertex(), and GetVertex().
TVector3 EicRcParticle::mRcVtxMomentum private
Definition at line 269 of file EicRcParticle.h.
View newest version in sPHENIX GitHub at line 269 of file EicRcParticle.h
Referenced by EicEventAssembler::Exec(), GetP(), GetPhi(), GetPt(), GetPx(), GetPy(), GetPz(), GetRcVtxMomentum(), GetTheta(), EicEventAssembler::PerformPidCalculations(), EicEventAssembler::ReAssignMomentumValue(), and SetRcVtxMomentum().
The documentation for this class was generated from the following files:
EicRoot/blob/master/eic/event/EicRcParticle.h
EicRoot/blob/master/eic/event/EicRcParticle.cxx