EIC Software: CbmMCMatchCreatorTask Class Reference
CbmMCMatchCreatorTask Class Reference
#include <EicRoot/blob/master/cbmbase/CbmMCMatchCreatorTask.h>
Public Member Functions
CbmMCMatchCreatorTask ()
virtual ~CbmMCMatchCreatorTask ()
virtual void SetParContainers ()
virtual InitStatus Init ()
virtual void Exec (Option_t *opt)
virtual void Finish ()
Public Member Functions inherited from FairTask
FairTask ()
FairTask (const char *name, Int_t iVerbose=1)
virtual ~FairTask ()
void InitTask ()
void ReInitTask ()
void SetParTask ()
virtual void FinishTask ()
virtual void FinishEvent ()
void SetVerbose (Int_t iVerbose)
void SetInputPersistance (Bool_t val)
void CheckInputPersistance (TString branchName)
Private Member Functions
InitStatus InitBranches ()
void Register ()
void Reset ()
void ProduceHits ()
CbmMCMatchCreatorTask (const CbmMCMatchCreatorTask &)
CbmMCMatchCreatorTask & operator= (const CbmMCMatchCreatorTask &)
ClassDef (CbmMCMatchCreatorTask, 1)
Private Attributes
std::map< std::string,
TClonesArray * > fBranches
TClonesArray * fMCLink
int fEventNr
CbmMCMatch * fMCMatch
Additional Inherited Members
Protected Member Functions inherited from FairTask
virtual InitStatus ReInit ()
void InitTasks ()
void ReInitTasks ()
void SetParTasks ()
void FinishTasks ()
void FinishEvents ()
Protected Attributes inherited from FairTask
Int_t fVerbose
Int_t fInputPersistance
Indicates if input branch is persistant.
FairLogger * fLogger
Detailed Description
Definition at line 26 of file CbmMCMatchCreatorTask.h.
View newest version in sPHENIX GitHub at line 26 of file CbmMCMatchCreatorTask.h
Constructor & Destructor Documentation
CbmMCMatchCreatorTask::CbmMCMatchCreatorTask ()
Default constructor
Definition at line 24 of file CbmMCMatchCreatorTask.cxx.
View newest version in sPHENIX GitHub at line 24 of file CbmMCMatchCreatorTask.cxx
CbmMCMatchCreatorTask::~CbmMCMatchCreatorTask () virtual
Destructor
Definition at line 36 of file CbmMCMatchCreatorTask.cxx.
View newest version in sPHENIX GitHub at line 36 of file CbmMCMatchCreatorTask.cxx
CbmMCMatchCreatorTask::CbmMCMatchCreatorTask (const CbmMCMatchCreatorTask &) private
Member Function Documentation
CbmMCMatchCreatorTask::ClassDef (CbmMCMatchCreatorTask , 1) private
void CbmMCMatchCreatorTask::Exec (Option_t * opt) virtual
Virtual method Exec
Definition at line 112 of file CbmMCMatchCreatorTask.cxx.
View newest version in sPHENIX GitHub at line 112 of file CbmMCMatchCreatorTask.cxx
References CbmMCMatch::ClearMCList(), fBranches, fMCLink, fMCMatch, FairTask::fVerbose, CbmMCStage::GetBranchName(), CbmMCStage::GetFill(), CbmMCStage::GetLoaded(), CbmMCObject::GetMCLink(), CbmMCMatch::GetMCStage(), CbmMCObject::GetNEntries(), CbmMCMatch::GetNMCStages(), CbmMCObject::GetStageId(), CbmMCMatch::LoadInMCLists(), CbmMCMatch::Print(), CbmMCMatch::SetElements(), and CbmMCStage::SetLoaded().
void CbmMCMatchCreatorTask::Finish () virtual
Action after each event. To be implemented in the derived class
Reimplemented from FairTask.
Definition at line 155 of file CbmMCMatchCreatorTask.cxx.
View newest version in sPHENIX GitHub at line 155 of file CbmMCMatchCreatorTask.cxx
InitStatus CbmMCMatchCreatorTask::Init () virtual
Intialisation at begin of run. To be implemented in the derived class. Success If not kSUCCESS, task will be set inactive.
Reimplemented from FairTask.
Definition at line 41 of file CbmMCMatchCreatorTask.cxx.
View newest version in sPHENIX GitHub at line 41 of file CbmMCMatchCreatorTask.cxx
References fMCLink, fMCMatch, InitBranches(), CbmMCMatch::InitStage(), FairRootManager::Instance(), kFATAL, kStsCluster, kStsDigi, kStsHit, kStsPoint, and FairRootManager::Register().
InitStatus CbmMCMatchCreatorTask::InitBranches () private
Definition at line 75 of file CbmMCMatchCreatorTask.cxx.
View newest version in sPHENIX GitHub at line 75 of file CbmMCMatchCreatorTask.cxx
References fBranches, fMCMatch, CbmMCStage::GetBranchName(), CbmMCMatch::GetMCStage(), CbmMCMatch::GetNMCStages(), FairRootManager::GetObject(), FairRootManager::Instance(), kFATAL, kSUCCESS, and CbmMCStage::SetFill().
Referenced by Init().
CbmMCMatchCreatorTask& CbmMCMatchCreatorTask::operator= (const CbmMCMatchCreatorTask &) private
void CbmMCMatchCreatorTask::ProduceHits () private
void CbmMCMatchCreatorTask::Register () private
void CbmMCMatchCreatorTask::Reset () private
void CbmMCMatchCreatorTask::SetParContainers () virtual
Virtual method Init
Reimplemented from FairTask.
Definition at line 102 of file CbmMCMatchCreatorTask.cxx.
View newest version in sPHENIX GitHub at line 102 of file CbmMCMatchCreatorTask.cxx
Member Data Documentation
std::map<std::string, TClonesArray*> CbmMCMatchCreatorTask::fBranches private
Definition at line 51 of file CbmMCMatchCreatorTask.h.
View newest version in sPHENIX GitHub at line 51 of file CbmMCMatchCreatorTask.h
Referenced by Exec(), and InitBranches().
int CbmMCMatchCreatorTask::fEventNr private
Definition at line 55 of file CbmMCMatchCreatorTask.h.
View newest version in sPHENIX GitHub at line 55 of file CbmMCMatchCreatorTask.h
TClonesArray* CbmMCMatchCreatorTask::fMCLink private
Definition at line 53 of file CbmMCMatchCreatorTask.h.
View newest version in sPHENIX GitHub at line 53 of file CbmMCMatchCreatorTask.h
Referenced by Exec(), and Init().
CbmMCMatch* CbmMCMatchCreatorTask::fMCMatch private
Definition at line 56 of file CbmMCMatchCreatorTask.h.
View newest version in sPHENIX GitHub at line 56 of file CbmMCMatchCreatorTask.h
Referenced by Exec(), Init(), and InitBranches().
The documentation for this class was generated from the following files:
EicRoot/blob/master/cbmbase/CbmMCMatchCreatorTask.h
EicRoot/blob/master/cbmbase/CbmMCMatchCreatorTask.cxx