EIC Software: EicToyModel Class Reference
EicToyModel Class Reference
#include <EicToyModel/blob/master/include/EicToyModel.h>
Public Member Functions
EicToyModel (double length=_IR_REGION_LENGTH_DEFAULT_, double radius=_IR_REGION_RADIUS_DEFAULT_)
EicToyModel * acceptance (double eta0, double eta1, double eta2, double eta3, bool reset_stacks=false, bool redraw=true)
EicToyModel * DefineVacuumChamber (EtmVacuumChamber *vc)
EicToyModel * ip (double offset, bool redraw=true)
EicToyModel * ir (double length, double radius, bool redraw=true)
EtmDetectorStack * vtx (void)
EtmDetectorStack * vertex (void)
EtmDetectorStack * bck (void)
EtmDetectorStack * backward (void)
EtmDetectorStack * mid (void)
EtmDetectorStack * barrel (void)
EtmDetectorStack * fwd (void)
EtmDetectorStack * forward (void)
EicToyModel * SetCrossingAngle (double value, bool redraw=true)
EicToyModel * width (unsigned width)
EicToyModel * mirror (bool what=true, bool redraw=true)
EicToyModel * full (bool redraw=true)
EicToyModel * left (bool redraw=true)
EicToyModel * right (bool redraw=true)
EicToyModel * legend (bool what=true, bool redraw=true)
void vdraw (void)
void hdraw (void)
void draw (void)
void home (bool redraw=true)
void zoom (double blX, double blY, double trX, double trY, bool redraw=true)
EicToyModel * AddEtaLine (double value, bool line=true, bool label=true, bool redraw=true)
EicToyModel * RemoveEtaLine (double eta)
void DrawIP6boundaries (void)
void write (bool everything=false, bool lock=false)
EicToyModel * SetName (const char *name)
EicToyModel * DrawFlatFieldLines (double eta)
void ApplyStandardTrimming (void)
void UseDetectorHighlighting (void)
TVector2 cnv (const TVector2 &world) const
TVector2 GetIpLocation (void) const
double GetCrossingAngle (void) const
double GetIrRegionLength (void) const
double GetIrRegionRadius (void) const
void Construct (void)
void PlaceG4Volumes (G4LogicalVolume *world)
void PlaceG4Volumes (G4VPhysicalVolume *world)
void Export (const char *fname, bool everything=false, bool lock=false)
void ExportVacuumChamber (const char *fname=0)
G4VPhysicalVolume * ConstructG4World (void)
void DefineG4World (G4LogicalVolume *world)
G4LogicalVolume * GetG4World (void) const
void BuildVacuumChamber (void)
void SetAzimuthalSegmentation (unsigned value)
unsigned GetAzimuthalSegmentation (void) const
Static Public Member Functions
static EicToyModel * Instance (void)
static std::pair< std::vector
< TVector2 >, std::vector
< TVector2 > > GetIntersection (const std::vector< TVector2 > &chain, const EtmLine2D &line)
static EicToyModel * Import (const char *fname)
Public Attributes
bool mDrawIP6boundaries
bool mUseDetectorHighlighting
Private Types
enum OneSide { kOff, kLeft, kRight }
enum View { kUndefined, kCurrent, kHorizontal, kVertical }
Private Member Functions
~EicToyModel ()
EicToyModel::View GetCurrentView (void) const
void DrawPolygon (unsigned dim, const double xx[], const double yy[], int color, bool line=true) const
EtmPalette & Palette (void)
EtmVacuumChamber * GetVacuumChamber (void)
void ExportCADmodel (const char *fname)
void ExportCADmodelCore (std::vector< std::pair< const TColor *, const TopoDS_Shape * > > shapes, const char *fname)
const char * GetName (void) const
void CalculateDefaultEtaBoundaries (EtmDetectorStack *single=0)
std::vector< TVector2 > RebuildCrack (const std::vector< TVector2 > &chain, const EtmLine2D &am, const EtmLine2D &ap, const EtmLine2D &cut, etm::Stretch how)
void AppendChain (std::vector< TVector2 > &chain, const std::vector< TVector2 > &add)
std::vector< TVector2 > Band (const std::vector< TVector2 > &chain, const EtmLine2D &from, const EtmLine2D &to)
TVector2 CalculateEtaStartPoint (double eta, unsigned vh, unsigned tb, bool account_crossing_angle)
std::pair< TVector2, bool > CalculateEtaEndPoint (double eta, unsigned vh, unsigned tb, bool account_crossing_angle)
EtmDetectorStack * GetStack (double eta)
void WriteText (const TVector2 &where, const TString &what, int color=kBlack) const
void DrawSingleLine (const TVector2 &from, const TVector2 &to, int color=kBlack, int width=1, etm::LineStyle style=etm::solid) const
EicToyModel * Enable (const char *tag)
EicToyModel * RebuildEverything (bool redraw)
void DrawMe (EicToyModel::View view=EicToyModel::kCurrent, bool draw=true)
void DrawSingleEtaLine (double eta, const TVector2 &to, std::pair< bool, bool > what, bool side) const
TVector2 GetCanvasCoordinates (const TVector2 &world) const
void DrawRectangle (const TVector2 &bl, const TVector2 &tr, int color, bool line=true) const
void DrawEtaLines (void)
void DrawEtaBoundaries (void)
void DrawBeamLine (void)
void DrawAxisTicks (void)
void DrawColorLegend (unsigned rows=1)
void DrawMarkers (void)
void DrawFlatFieldLines (void)
void AddBoundaryModificationRequest (EtmDetector *hostdet, EtmDetector *refdet, double toffset, etm::Stretch how)
void ExecuteBoundaryModificationRequests (EtmDetectorStack *single=0)
void PurgeBoundaryVertexArrays (void)
void AccountServiceMaterials (void)
Private Attributes
std::vector< EtmDetectorStack * > mStacks
TString mName
double mIrRegionLength
double mIrRegionRadius
unsigned mAzimuthalSegmentation
double mIpOffset
unsigned mXdim
unsigned mYdim
double mXsize
double mYsize
double mX0
double mY0
bool mColorLegendEnabled
bool mZoomedView
std::map< double, std::pair
< bool, bool > > mEtaLines
TCanvas * mCanvas
EtmVacuumChamber * mVacuumChamber
EicToyModel::View mCurrentView
bool mMirrorImage
EicToyModel::OneSide mOneSideMode
EtmPalette mPalette
std::set< TString > mEnabledColorTags
double mCrossingAngle
std::set< double > mFlatFieldLinesEta
std::vector
< EtmBoundaryModificationRequest * > mBoundaryModificationRequests
bool mGeometryLocked
bool mNewCanvasRequired
G4LogicalVolume * mG4LogicalWorld
Static Private Attributes
static EicToyModel * mInstance = 0
Friends
class EtmDetector
class EtmDetectorStack
class EtmAzimuthalScan
class EtmVacuumChamber
Detailed Description
Definition at line 19 of file EicToyModel.h.
View newest version in sPHENIX GitHub at line 19 of file EicToyModel.h
Member Enumeration Documentation
enum EicToyModel::OneSide private
Enumerator:
kOff
kLeft
kRight
Definition at line 157 of file EicToyModel.h.
View newest version in sPHENIX GitHub at line 157 of file EicToyModel.h
enum EicToyModel::View private
Enumerator:
kUndefined
kCurrent
kHorizontal
kVertical
Definition at line 158 of file EicToyModel.h.
View newest version in sPHENIX GitHub at line 158 of file EicToyModel.h
Constructor & Destructor Documentation
EicToyModel::EicToyModel (double length = _IR_REGION_LENGTH_DEFAULT_, double radius = _IR_REGION_RADIUS_DEFAULT_)
Definition at line 76 of file EicToyModel.cc.
View newest version in sPHENIX GitHub at line 76 of file EicToyModel.cc
References acceptance(), mInstance, and printf().
EicToyModel::~EicToyModel () inline private
Definition at line 155 of file EicToyModel.h.
View newest version in sPHENIX GitHub at line 155 of file EicToyModel.h
Member Function Documentation
EicToyModel * EicToyModel::acceptance (double eta0, double eta1, double eta2, double eta3, bool reset_stacks = false, bool redraw = true)
Definition at line 191 of file EicToyModel.cc.
View newest version in sPHENIX GitHub at line 191 of file EicToyModel.cc
References AddEtaLine(), bck(), buffer, DrawMe(), Acts::VectorHelpers::eta(), fwd(), mCanvas, mEtaLines, mid(), mStacks, printf(), EtmDetectorStack::SetEtaBoundaries(), and vtx().
Referenced by EicToyModel().
void EicToyModel::AccountServiceMaterials (void) private
Definition at line 949 of file EicToyModel.cc.
View newest version in sPHENIX GitHub at line 949 of file EicToyModel.cc
Referenced by DrawMe().
void EicToyModel::AddBoundaryModificationRequest (EtmDetector * hostdet, EtmDetector * refdet, double toffset, etm::Stretch how) private
Definition at line 665 of file EicToyModel.cc.
View newest version in sPHENIX GitHub at line 665 of file EicToyModel.cc
References mBoundaryModificationRequests.
EicToyModel * EicToyModel::AddEtaLine (double value, bool line = true, bool label = true, bool redraw = true)
Definition at line 405 of file EicToyModel.cc.
View newest version in sPHENIX GitHub at line 405 of file EicToyModel.cc
References DrawMe(), mCanvas, mEtaLines, and value.
Referenced by acceptance().
void EicToyModel::AppendChain (std::vector< TVector2 > & chain, const std::vector< TVector2 > & add) private
Definition at line 763 of file EicToyModel.cc.
View newest version in sPHENIX GitHub at line 763 of file EicToyModel.cc
Referenced by RebuildCrack().
void EicToyModel::ApplyStandardTrimming (void)
Definition at line 933 of file EicToyModel.cc.
View newest version in sPHENIX GitHub at line 933 of file EicToyModel.cc
References _DEFAULT_TRIM_VALUE_, bck(), fwd(), and mid().
EtmDetectorStack* EicToyModel::backward (void) inline
Definition at line 50 of file EicToyModel.h.
View newest version in sPHENIX GitHub at line 50 of file EicToyModel.h
std::vector< TVector2 > EicToyModel::Band (const std::vector< TVector2 > & chain, const EtmLine2D & from, const EtmLine2D & to) private
Definition at line 674 of file EicToyModel.cc.
View newest version in sPHENIX GitHub at line 674 of file EicToyModel.cc
References EtmLine2D::Cross(), Acts::Test::dim, EtmLine2D::Distance(), and EtmLine2D::IsParallel().
EtmDetectorStack* EicToyModel::barrel (void) inline
Definition at line 51 of file EicToyModel.h.
View newest version in sPHENIX GitHub at line 51 of file EicToyModel.h
EtmDetectorStack * EicToyModel::bck (void)
Definition at line 567 of file EicToyModel.cc.
View newest version in sPHENIX GitHub at line 567 of file EicToyModel.cc
References mStacks.
Referenced by acceptance(), ApplyStandardTrimming(), CalculateDefaultEtaBoundaries(), DrawFlatFieldLines(), and DrawMarkers().
void EicToyModel::BuildVacuumChamber (void) inline
Definition at line 144 of file EicToyModel.h.
View newest version in sPHENIX GitHub at line 144 of file EicToyModel.h
References EtmVacuumChamber::CheckGeometry(), and mVacuumChamber.
void EicToyModel::CalculateDefaultEtaBoundaries (EtmDetectorStack * single = 0) private
Definition at line 238 of file EicToyModel.cc.
View newest version in sPHENIX GitHub at line 238 of file EicToyModel.cc
References bck(), CalculateEtaEndPoint(), CalculateEtaStartPoint(), dx, EtmDetectorStack::FullLength(), fwd(), GetIpLocation(), ip(), Acts::IntegrationTest::L, EtmEtaBoundary::mCrackNodes, EtmDetectorStack::mEtaBoundaries, mid(), mIpOffset, mStacks, EtmDetectorStack::mStartingDistance, n, rr, and vtx().
Referenced by ExecuteBoundaryModificationRequests().
std::pair< TVector2, bool > EicToyModel::CalculateEtaEndPoint (double eta, unsigned vh, unsigned tb, bool account_crossing_angle) private
Definition at line 1143 of file EicToyModel.cc.
View newest version in sPHENIX GitHub at line 1143 of file EicToyModel.cc
References dx, Eta2Theta(), mCrossingAngle, mIpOffset, mIrRegionLength, mIrRegionRadius, and theta().
Referenced by CalculateDefaultEtaBoundaries(), and DrawEtaLines().
TVector2 EicToyModel::CalculateEtaStartPoint (double eta, unsigned vh, unsigned tb, bool account_crossing_angle) private
Definition at line 1130 of file EicToyModel.cc.
View newest version in sPHENIX GitHub at line 1130 of file EicToyModel.cc
References Eta2Theta(), GetIpLocation(), mCrossingAngle, and theta().
Referenced by CalculateDefaultEtaBoundaries().
TVector2 EicToyModel::cnv (const TVector2 & world) const
Definition at line 609 of file EicToyModel.cc.
View newest version in sPHENIX GitHub at line 609 of file EicToyModel.cc
References mX0, mXsize, mY0, and mYsize.
Referenced by DrawMarkers(), DrawPolygon(), DrawSingleLine(), GetCanvasCoordinates(), and WriteText().
void EicToyModel::Construct (void) inline
Definition at line 131 of file EicToyModel.h.
View newest version in sPHENIX GitHub at line 131 of file EicToyModel.h
References DrawMe(), and kUndefined.
G4VPhysicalVolume * EicToyModel::ConstructG4World (void)
Definition at line 151 of file EicToyModel.cc.
View newest version in sPHENIX GitHub at line 151 of file EicToyModel.cc
References etm::cm, Acts::UnitConstants::cm, GetIrRegionLength(), GetIrRegionRadius(), and printf().
void EicToyModel::DefineG4World (G4LogicalVolume * world) inline
Definition at line 138 of file EicToyModel.h.
View newest version in sPHENIX GitHub at line 138 of file EicToyModel.h
References mG4LogicalWorld, and Acts::Test::world.
EicToyModel * EicToyModel::DefineVacuumChamber (EtmVacuumChamber * vc)
Definition at line 133 of file EicToyModel.cc.
View newest version in sPHENIX GitHub at line 133 of file EicToyModel.cc
References EtmVacuumChamber::CrossingAngleResetPossible(), mCrossingAngle, and mVacuumChamber.
void EicToyModel::draw (void) inline
Definition at line 75 of file EicToyModel.h.
View newest version in sPHENIX GitHub at line 75 of file EicToyModel.h
References DrawMe(), and kCurrent.
void EicToyModel::DrawAxisTicks (void) private
Definition at line 1354 of file EicToyModel.cc.
View newest version in sPHENIX GitHub at line 1354 of file EicToyModel.cc
References kdfinder::abs(), etm::cm, Acts::Test::dim, DrawSingleLine(), GetCurrentView(), kHorizontal, mCrossingAngle, mIpOffset, mIrRegionLength, mIrRegionRadius, mMirrorImage, Acts::Test::step(), and WriteText().
Referenced by DrawMe().
void EicToyModel::DrawBeamLine (void) private
Definition at line 1227 of file EicToyModel.cc.
View newest version in sPHENIX GitHub at line 1227 of file EicToyModel.cc
References _HALL_RADIAL_BOUNDARY_, etm::dashdotted, etm::dashed, DrawSingleLine(), GetCurrentView(), GetIpLocation(), kHorizontal, left(), mCrossingAngle, mDrawIP6boundaries, mIrRegionLength, mMirrorImage, right(), and WriteText().
Referenced by DrawMe().
void EicToyModel::DrawColorLegend (unsigned rows = 1) private
Definition at line 1410 of file EicToyModel.cc.
View newest version in sPHENIX GitHub at line 1410 of file EicToyModel.cc
References _COLOR_LEGEND_GAP_, _COLOR_LEGEND_HEIGHT_, _COLOR_LEGEND_STEP_, _GAP_COLOR_, _MARKER_, color, DrawRectangle(), legend(), mEnabledColorTags, mStacks, mX0, mY0, mYsize, Acts::Test::step(), and WriteText().
Referenced by DrawMe().
void EicToyModel::DrawEtaBoundaries (void) private
Definition at line 1204 of file EicToyModel.cc.
View newest version in sPHENIX GitHub at line 1204 of file EicToyModel.cc
References etm::dashdotted, DrawSingleLine(), GetCurrentView(), kHorizontal, mMirrorImage, mStacks, and vtx().
Referenced by DrawMe().
void EicToyModel::DrawEtaLines (void) private
Definition at line 1184 of file EicToyModel.cc.
View newest version in sPHENIX GitHub at line 1184 of file EicToyModel.cc
References CalculateEtaEndPoint(), DrawSingleEtaLine(), Acts::VectorHelpers::eta(), GetCurrentView(), kHorizontal, mEtaLines, and mMirrorImage.
Referenced by DrawMe().
EicToyModel * EicToyModel::DrawFlatFieldLines (double eta)
Definition at line 601 of file EicToyModel.cc.
View newest version in sPHENIX GitHub at line 601 of file EicToyModel.cc
References mFlatFieldLinesEta.
void EicToyModel::DrawFlatFieldLines (void) private
Definition at line 1314 of file EicToyModel.cc.
View newest version in sPHENIX GitHub at line 1314 of file EicToyModel.cc
References _MARKER_, bck(), etm::cm, etm::dotted, DrawSingleLine(), dz, Acts::VectorHelpers::eta(), Eta2Theta(), fwd(), GetIpLocation(), GetStack(), marker(), mFlatFieldLinesEta, mMirrorImage, rmax(), sign(), and theta().
Referenced by DrawMe().
void EicToyModel::DrawIP6boundaries (void) inline
Definition at line 88 of file EicToyModel.h.
View newest version in sPHENIX GitHub at line 88 of file EicToyModel.h
References mDrawIP6boundaries.
void EicToyModel::DrawMarkers (void) private
Definition at line 1271 of file EicToyModel.cc.
View newest version in sPHENIX GitHub at line 1271 of file EicToyModel.cc
References _MARKER_, bck(), etm::cm, cnv(), dy, fwd(), GetIpLocation(), marker(), mIpOffset, and WriteText().
Referenced by DrawMe().
void EicToyModel::DrawMe (EicToyModel::View view = EicToyModel::kCurrent, bool draw = true) private
Definition at line 967 of file EicToyModel.cc.
View newest version in sPHENIX GitHub at line 967 of file EicToyModel.cc
References AccountServiceMaterials(), DrawAxisTicks(), DrawBeamLine(), DrawColorLegend(), DrawEtaBoundaries(), DrawEtaLines(), DrawFlatFieldLines(), DrawMarkers(), EtmVacuumChamber::DrawMe(), ExecuteBoundaryModificationRequests(), GetCurrentView(), GetName(), home(), kCurrent, kOff, kUndefined, kVertical, mCanvas, mColorLegendEnabled, mCurrentView, mEnabledColorTags, mGeometryLocked, mMirrorImage, mNewCanvasRequired, mOneSideMode, mStacks, mVacuumChamber, mXdim, mXsize, mYdim, mYsize, mZoomedView, and vtx().
Referenced by acceptance(), AddEtaLine(), Construct(), draw(), hdraw(), home(), ip(), RebuildEverything(), vdraw(), and zoom().
void EicToyModel::DrawPolygon (unsigned dim, const double xx[], const double yy[], int color, bool line = true) const private
Definition at line 1078 of file EicToyModel.cc.
View newest version in sPHENIX GitHub at line 1078 of file EicToyModel.cc
References cnv(), Acts::Test::dim, and etm::solid.
Referenced by DrawRectangle().
void EicToyModel::DrawRectangle (const TVector2 & bl, const TVector2 & tr, int color, bool line = true) const private
Definition at line 1102 of file EicToyModel.cc.
View newest version in sPHENIX GitHub at line 1102 of file EicToyModel.cc
References DrawPolygon().
Referenced by DrawColorLegend().
void EicToyModel::DrawSingleEtaLine (double eta, const TVector2 & to, std::pair< bool, bool > what, bool side) const private
Definition at line 1165 of file EicToyModel.cc.
View newest version in sPHENIX GitHub at line 1165 of file EicToyModel.cc
References etm::cm, etm::dashdotted, DrawSingleLine(), GetIpLocation(), sign(), and WriteText().
Referenced by DrawEtaLines().
void EicToyModel::DrawSingleLine (const TVector2 & from, const TVector2 & to, int color = kBlack, int width = 1, etm::LineStyle style = etm::solid) const private
Definition at line 1112 of file EicToyModel.cc.
View newest version in sPHENIX GitHub at line 1112 of file EicToyModel.cc
References cnv().
Referenced by DrawAxisTicks(), DrawBeamLine(), DrawEtaBoundaries(), DrawFlatFieldLines(), and DrawSingleEtaLine().
EicToyModel* EicToyModel::Enable (const char * tag) inline private
Definition at line 200 of file EicToyModel.h.
View newest version in sPHENIX GitHub at line 200 of file EicToyModel.h
References mEnabledColorTags.
void EicToyModel::ExecuteBoundaryModificationRequests (EtmDetectorStack * single = 0) private
Definition at line 864 of file EicToyModel.cc.
View newest version in sPHENIX GitHub at line 864 of file EicToyModel.cc
References boundaries, CalculateDefaultEtaBoundaries(), EtmDetectorStack::EtaBoundary(), GetIpLocation(), GetIrRegionLength(), GetIrRegionRadius(), ip(), M_PI, mBoundaryModificationRequests, EtmEtaBoundary::mCrackNodes, mid(), RebuildCrack(), vtx(), and EtmLine2D::X().
Referenced by DrawMe().
void EicToyModel::Export (const char * fname, bool everything = false, bool lock = false)
Definition at line 496 of file EicToyModel.cc.
View newest version in sPHENIX GitHub at line 496 of file EicToyModel.cc
References ExportCADmodel(), EtmVacuumChamber::GetWorld(), mGeometryLocked, mVacuumChamber, printf(), and EtmVacuumChamber::StoreGDMLdump().
Referenced by write().
void EicToyModel::ExportCADmodel (const char * fname) private
Definition at line 479 of file EicToyModel.cc.
View newest version in sPHENIX GitHub at line 479 of file EicToyModel.cc
References ExportCADmodelCore(), and mStacks.
Referenced by Export().
void EicToyModel::ExportCADmodelCore (std::vector< std::pair< const TColor *, const TopoDS_Shape * > > shapes, const char * fname) private
Definition at line 441 of file EicToyModel.cc.
View newest version in sPHENIX GitHub at line 441 of file EicToyModel.cc
References printf().
Referenced by EtmDetector::Export(), and ExportCADmodel().
void EicToyModel::ExportVacuumChamber (const char * fname = 0)
Definition at line 424 of file EicToyModel.cc.
View newest version in sPHENIX GitHub at line 424 of file EicToyModel.cc
References EtmVacuumChamber::Export(), GetName(), mVacuumChamber, and printf().
EtmDetectorStack* EicToyModel::forward (void) inline
Definition at line 52 of file EicToyModel.h.
View newest version in sPHENIX GitHub at line 52 of file EicToyModel.h
EicToyModel* EicToyModel::full (bool redraw = true) inline
Definition at line 65 of file EicToyModel.h.
View newest version in sPHENIX GitHub at line 65 of file EicToyModel.h
References home(), kOff, and mOneSideMode.
EtmDetectorStack * EicToyModel::fwd (void)
Definition at line 581 of file EicToyModel.cc.
View newest version in sPHENIX GitHub at line 581 of file EicToyModel.cc
References mStacks.
Referenced by acceptance(), ApplyStandardTrimming(), CalculateDefaultEtaBoundaries(), DrawFlatFieldLines(), DrawMarkers(), and GetStack().
unsigned EicToyModel::GetAzimuthalSegmentation (void) const inline
Definition at line 149 of file EicToyModel.h.
View newest version in sPHENIX GitHub at line 149 of file EicToyModel.h
References mAzimuthalSegmentation.
TVector2 EicToyModel::GetCanvasCoordinates (const TVector2 & world) const inline private
Definition at line 211 of file EicToyModel.h.
View newest version in sPHENIX GitHub at line 211 of file EicToyModel.h
References cnv().
double EicToyModel::GetCrossingAngle (void) const inline
Definition at line 124 of file EicToyModel.h.
View newest version in sPHENIX GitHub at line 124 of file EicToyModel.h
References mCrossingAngle.
Referenced by EtmVacuumChamber::CheckGeometry().
EicToyModel::View EicToyModel::GetCurrentView (void) const inline private
Definition at line 160 of file EicToyModel.h.
View newest version in sPHENIX GitHub at line 160 of file EicToyModel.h
References mCurrentView.
Referenced by DrawAxisTicks(), DrawBeamLine(), DrawEtaBoundaries(), DrawEtaLines(), and DrawMe().
G4LogicalVolume* EicToyModel::GetG4World (void) const inline
Definition at line 139 of file EicToyModel.h.
View newest version in sPHENIX GitHub at line 139 of file EicToyModel.h
References mG4LogicalWorld.
std::pair< std::vector< TVector2 >, std::vector< TVector2 > > EicToyModel::GetIntersection (const std::vector< TVector2 > & chain, const EtmLine2D & line) static
Definition at line 725 of file EicToyModel.cc.
View newest version in sPHENIX GitHub at line 725 of file EicToyModel.cc
References EtmLine2D::Cross(), Acts::Test::dim, EtmLine2D::Distance(), and EtmLine2D::IsParallel().
Referenced by EtmDetector::Build(), and RebuildCrack().
TVector2 EicToyModel::GetIpLocation (void) const inline
Definition at line 122 of file EicToyModel.h.
View newest version in sPHENIX GitHub at line 122 of file EicToyModel.h
References mIpOffset.
Referenced by CalculateDefaultEtaBoundaries(), CalculateEtaStartPoint(), DrawBeamLine(), DrawFlatFieldLines(), DrawMarkers(), DrawSingleEtaLine(), and ExecuteBoundaryModificationRequests().
double EicToyModel::GetIrRegionLength (void) const inline
Definition at line 125 of file EicToyModel.h.
View newest version in sPHENIX GitHub at line 125 of file EicToyModel.h
References mIrRegionLength.
Referenced by ConstructG4World(), and ExecuteBoundaryModificationRequests().
double EicToyModel::GetIrRegionRadius (void) const inline
Definition at line 126 of file EicToyModel.h.
View newest version in sPHENIX GitHub at line 126 of file EicToyModel.h
References mIrRegionRadius.
Referenced by ConstructG4World(), and ExecuteBoundaryModificationRequests().
const char* EicToyModel::GetName (void) const inline private
Definition at line 176 of file EicToyModel.h.
View newest version in sPHENIX GitHub at line 176 of file EicToyModel.h
References mName.
Referenced by DrawMe(), ExportVacuumChamber(), and write().
EtmDetectorStack * EicToyModel::GetStack (double eta) private
Definition at line 588 of file EicToyModel.cc.
View newest version in sPHENIX GitHub at line 588 of file EicToyModel.cc
References EtmDetectorStack::EtaBoundary(), EtmDetectorStack::etamin(), fwd(), EtmEtaBoundary::GetEta(), mStacks, and vtx().
Referenced by DrawFlatFieldLines().
EtmVacuumChamber* EicToyModel::GetVacuumChamber (void) inline private
Definition at line 167 of file EicToyModel.h.
View newest version in sPHENIX GitHub at line 167 of file EicToyModel.h
References mVacuumChamber.
void EicToyModel::hdraw (void) inline
Definition at line 74 of file EicToyModel.h.
View newest version in sPHENIX GitHub at line 74 of file EicToyModel.h
References DrawMe(), and kHorizontal.
void EicToyModel::home (bool redraw = true)
Definition at line 616 of file EicToyModel.cc.
View newest version in sPHENIX GitHub at line 616 of file EicToyModel.cc
References _COLOR_LEGEND_HEIGHT_, _IR_REGION_BMARGIN_, _IR_REGION_SMARGIN_, DrawMe(), kLeft, kOff, kRight, mCanvas, mColorLegendEnabled, mIrRegionLength, mIrRegionRadius, mMirrorImage, mNewCanvasRequired, mOneSideMode, mX0, mXsize, mY0, mYsize, and mZoomedView.
Referenced by EtmDetectorStack::add(), DrawMe(), full(), ir(), left(), legend(), mirror(), right(), and width().
EicToyModel * EicToyModel::Import (const char * fname) static
Definition at line 106 of file EicToyModel.cc.
View newest version in sPHENIX GitHub at line 106 of file EicToyModel.cc
References mInstance, and printf().
Referenced by EicToyModelDetector::ConstructMe(), main(), reader(), and scan().
static EicToyModel* EicToyModel::Instance (void) inline static
Definition at line 116 of file EicToyModel.h.
View newest version in sPHENIX GitHub at line 116 of file EicToyModel.h
References mInstance.
Referenced by EtmDetectorStack::add(), EtmDetector::Build(), EtmDetector::BuildCADmodel(), EtmDetectorStack::CalculateActualDistances(), EtmVacuumChamber::CheckGeometry(), BasicDetectorConstruction::Construct(), EicRootDetector::ConstructMe(), EtmDetectorStack::CreateDetector(), vc2020_03_20::CreateGeometry(), EtmVacuumChamber::CreateWorld(), EtmAzimuthalScan::DoIt(), EtmVacuumChamber::DrawMe(), EtmPolygonGroup::DrawPolygon(), EtmDetector::Export(), EtmDetector::GetColorAlpha(), EtmDetector::GetG4Volume(), EtmDetectorStack::insert(), EtmDetector::insert(), EtmDetector::IsHighlighted(), EtmDetector::PlaceG4Volume(), EtmDetectorStack::rm(), and EtmDetector::stretch().
EicToyModel * EicToyModel::ip (double offset, bool redraw = true)
Definition at line 322 of file EicToyModel.cc.
View newest version in sPHENIX GitHub at line 322 of file EicToyModel.cc
References EtmVacuumChamber::CheckGeometry(), DrawMe(), mCanvas, mGeometryLocked, mIpOffset, mVacuumChamber, and offset.
Referenced by CalculateDefaultEtaBoundaries(), and ExecuteBoundaryModificationRequests().
EicToyModel * EicToyModel::ir (double length, double radius, bool redraw = true)
Definition at line 336 of file EicToyModel.cc.
View newest version in sPHENIX GitHub at line 336 of file EicToyModel.cc
References home(), G4BARRELHCAL::length, mIrRegionLength, mIrRegionRadius, and G4BECAL::radius.
EicToyModel* EicToyModel::left (bool redraw = true) inline
Definition at line 66 of file EicToyModel.h.
View newest version in sPHENIX GitHub at line 66 of file EicToyModel.h
References home(), kLeft, and mOneSideMode.
Referenced by DrawBeamLine().
EicToyModel * EicToyModel::legend (bool what = true, bool redraw = true)
Definition at line 395 of file EicToyModel.cc.
View newest version in sPHENIX GitHub at line 395 of file EicToyModel.cc
References home(), and mColorLegendEnabled.
Referenced by DrawColorLegend().
EtmDetectorStack * EicToyModel::mid (void)
Definition at line 574 of file EicToyModel.cc.
View newest version in sPHENIX GitHub at line 574 of file EicToyModel.cc
References mStacks.
Referenced by acceptance(), ApplyStandardTrimming(), CalculateDefaultEtaBoundaries(), and ExecuteBoundaryModificationRequests().
EicToyModel * EicToyModel::mirror (bool what = true, bool redraw = true)
Definition at line 382 of file EicToyModel.cc.
View newest version in sPHENIX GitHub at line 382 of file EicToyModel.cc
References home(), mMirrorImage, and mNewCanvasRequired.
EtmPalette& EicToyModel::Palette (void) inline private
Definition at line 165 of file EicToyModel.h.
View newest version in sPHENIX GitHub at line 165 of file EicToyModel.h
References mPalette.
void EicToyModel::PlaceG4Volumes (G4LogicalVolume * world)
Definition at line 173 of file EicToyModel.cc.
View newest version in sPHENIX GitHub at line 173 of file EicToyModel.cc
References mStacks.
Referenced by PlaceG4Volumes().
void EicToyModel::PlaceG4Volumes (G4VPhysicalVolume * world)
Definition at line 182 of file EicToyModel.cc.
View newest version in sPHENIX GitHub at line 182 of file EicToyModel.cc
References PlaceG4Volumes().
void EicToyModel::PurgeBoundaryVertexArrays (void) private
std::vector< TVector2 > EicToyModel::RebuildCrack (const std::vector< TVector2 > & chain, const EtmLine2D & am, const EtmLine2D & ap, const EtmLine2D & cut, etm::Stretch how) private
Definition at line 774 of file EicToyModel.cc.
View newest version in sPHENIX GitHub at line 774 of file EicToyModel.cc
References AppendChain(), Acts::UnitConstants::C, Acts::UnitConstants::cm, EtmLine2D::Cross(), EtmLine2D::Distance(), GetIntersection(), etm::kDent, etm::kRecess, etm::kWall, Acts::IntegrationTest::L, and EtmLine2D::V().
Referenced by ExecuteBoundaryModificationRequests().
EicToyModel * EicToyModel::RebuildEverything (bool redraw) private
Definition at line 346 of file EicToyModel.cc.
View newest version in sPHENIX GitHub at line 346 of file EicToyModel.cc
References EtmVacuumChamber::CheckGeometry(), DrawMe(), mCanvas, and mVacuumChamber.
Referenced by SetCrossingAngle().
EicToyModel* EicToyModel::RemoveEtaLine (double eta) inline
Definition at line 86 of file EicToyModel.h.
View newest version in sPHENIX GitHub at line 86 of file EicToyModel.h
References mEtaLines.
EicToyModel* EicToyModel::right (bool redraw = true) inline
Definition at line 67 of file EicToyModel.h.
View newest version in sPHENIX GitHub at line 67 of file EicToyModel.h
References home(), kRight, and mOneSideMode.
Referenced by d1mach(), and DrawBeamLine().
void EicToyModel::SetAzimuthalSegmentation (unsigned value) inline
Definition at line 146 of file EicToyModel.h.
View newest version in sPHENIX GitHub at line 146 of file EicToyModel.h
References mAzimuthalSegmentation, mGeometryLocked, and value.
EicToyModel * EicToyModel::SetCrossingAngle (double value, bool redraw = true)
Definition at line 357 of file EicToyModel.cc.
View newest version in sPHENIX GitHub at line 357 of file EicToyModel.cc
References EtmVacuumChamber::CrossingAngleResetPossible(), mCrossingAngle, mVacuumChamber, and RebuildEverything().
EicToyModel* EicToyModel::SetName (const char * name) inline
Definition at line 97 of file EicToyModel.h.
View newest version in sPHENIX GitHub at line 97 of file EicToyModel.h
References mName, and name.
void EicToyModel::UseDetectorHighlighting (void) inline
Definition at line 113 of file EicToyModel.h.
View newest version in sPHENIX GitHub at line 113 of file EicToyModel.h
References mUseDetectorHighlighting.
void EicToyModel::vdraw (void) inline
Definition at line 73 of file EicToyModel.h.
View newest version in sPHENIX GitHub at line 73 of file EicToyModel.h
References DrawMe(), and kVertical.
EtmDetectorStack* EicToyModel::vertex (void) inline
Definition at line 49 of file EicToyModel.h.
View newest version in sPHENIX GitHub at line 49 of file EicToyModel.h
EtmDetectorStack * EicToyModel::vtx (void)
Definition at line 560 of file EicToyModel.cc.
View newest version in sPHENIX GitHub at line 560 of file EicToyModel.cc
References mStacks.
Referenced by acceptance(), CalculateDefaultEtaBoundaries(), DrawEtaBoundaries(), DrawMe(), ExecuteBoundaryModificationRequests(), and GetStack().
EicToyModel * EicToyModel::width (unsigned width)
Definition at line 372 of file EicToyModel.cc.
View newest version in sPHENIX GitHub at line 372 of file EicToyModel.cc
References home(), mNewCanvasRequired, and mXdim.
void EicToyModel::write (bool everything = false, bool lock = false)
Definition at line 417 of file EicToyModel.cc.
View newest version in sPHENIX GitHub at line 417 of file EicToyModel.cc
References Export(), and GetName().
void EicToyModel::WriteText (const TVector2 & where, const TString & what, int color = kBlack) const private
Definition at line 1061 of file EicToyModel.cc.
View newest version in sPHENIX GitHub at line 1061 of file EicToyModel.cc
References _CANVAS_WIDTH_DEFAULT_, cnv(), kOff, mOneSideMode, and mXdim.
Referenced by DrawAxisTicks(), DrawBeamLine(), DrawColorLegend(), DrawMarkers(), and DrawSingleEtaLine().
void EicToyModel::zoom (double blX, double blY, double trX, double trY, bool redraw = true)
Definition at line 646 of file EicToyModel.cc.
View newest version in sPHENIX GitHub at line 646 of file EicToyModel.cc
References ConditionChecker(), DrawMe(), mCanvas, mNewCanvasRequired, mX0, mXsize, mY0, mYsize, and mZoomedView.
Referenced by lqcdpr(), and lweits().
Friends And Related Function Documentation
friend class EtmAzimuthalScan friend
Definition at line 25 of file EicToyModel.h.
View newest version in sPHENIX GitHub at line 25 of file EicToyModel.h
friend class EtmDetector friend
Definition at line 23 of file EicToyModel.h.
View newest version in sPHENIX GitHub at line 23 of file EicToyModel.h
friend class EtmDetectorStack friend
Definition at line 24 of file EicToyModel.h.
View newest version in sPHENIX GitHub at line 24 of file EicToyModel.h
friend class EtmVacuumChamber friend
Definition at line 26 of file EicToyModel.h.
View newest version in sPHENIX GitHub at line 26 of file EicToyModel.h
Member Data Documentation
unsigned EicToyModel::mAzimuthalSegmentation private
Definition at line 240 of file EicToyModel.h.
View newest version in sPHENIX GitHub at line 240 of file EicToyModel.h
Referenced by GetAzimuthalSegmentation(), and SetAzimuthalSegmentation().
std::vector<EtmBoundaryModificationRequest*> EicToyModel::mBoundaryModificationRequests private
Definition at line 295 of file EicToyModel.h.
View newest version in sPHENIX GitHub at line 295 of file EicToyModel.h
Referenced by AddBoundaryModificationRequest(), and ExecuteBoundaryModificationRequests().
TCanvas* EicToyModel::mCanvas private
Definition at line 273 of file EicToyModel.h.
View newest version in sPHENIX GitHub at line 273 of file EicToyModel.h
Referenced by acceptance(), AddEtaLine(), DrawMe(), home(), ip(), RebuildEverything(), and zoom().
bool EicToyModel::mColorLegendEnabled private
Definition at line 268 of file EicToyModel.h.
View newest version in sPHENIX GitHub at line 268 of file EicToyModel.h
Referenced by DrawMe(), home(), and legend().
double EicToyModel::mCrossingAngle private
Definition at line 291 of file EicToyModel.h.
View newest version in sPHENIX GitHub at line 291 of file EicToyModel.h
Referenced by CalculateEtaEndPoint(), CalculateEtaStartPoint(), DefineVacuumChamber(), DrawAxisTicks(), DrawBeamLine(), GetCrossingAngle(), and SetCrossingAngle().
EicToyModel::View EicToyModel::mCurrentView private
Definition at line 277 of file EicToyModel.h.
View newest version in sPHENIX GitHub at line 277 of file EicToyModel.h
Referenced by DrawMe(), and GetCurrentView().
bool EicToyModel::mDrawIP6boundaries
Definition at line 310 of file EicToyModel.h.
View newest version in sPHENIX GitHub at line 310 of file EicToyModel.h
Referenced by DrawBeamLine(), and DrawIP6boundaries().
std::set<TString> EicToyModel::mEnabledColorTags private
Definition at line 284 of file EicToyModel.h.
View newest version in sPHENIX GitHub at line 284 of file EicToyModel.h
Referenced by DrawColorLegend(), DrawMe(), and Enable().
std::map<double, std::pair<bool, bool> > EicToyModel::mEtaLines private
Definition at line 271 of file EicToyModel.h.
View newest version in sPHENIX GitHub at line 271 of file EicToyModel.h
Referenced by acceptance(), AddEtaLine(), DrawEtaLines(), and RemoveEtaLine().
std::set<double> EicToyModel::mFlatFieldLinesEta private
Definition at line 293 of file EicToyModel.h.
View newest version in sPHENIX GitHub at line 293 of file EicToyModel.h
Referenced by DrawFlatFieldLines().
G4LogicalVolume* EicToyModel::mG4LogicalWorld private
Definition at line 307 of file EicToyModel.h.
View newest version in sPHENIX GitHub at line 307 of file EicToyModel.h
Referenced by DefineG4World(), and GetG4World().
bool EicToyModel::mGeometryLocked private
Definition at line 303 of file EicToyModel.h.
View newest version in sPHENIX GitHub at line 303 of file EicToyModel.h
Referenced by DrawMe(), Export(), ip(), and SetAzimuthalSegmentation().
EicToyModel * EicToyModel::mInstance = 0 static private
Definition at line 231 of file EicToyModel.h.
View newest version in sPHENIX GitHub at line 231 of file EicToyModel.h
Referenced by EicToyModel(), Import(), and Instance().
double EicToyModel::mIpOffset private
Definition at line 261 of file EicToyModel.h.
View newest version in sPHENIX GitHub at line 261 of file EicToyModel.h
Referenced by CalculateDefaultEtaBoundaries(), CalculateEtaEndPoint(), DrawAxisTicks(), DrawMarkers(), GetIpLocation(), and ip().
double EicToyModel::mIrRegionLength private
Definition at line 238 of file EicToyModel.h.
View newest version in sPHENIX GitHub at line 238 of file EicToyModel.h
Referenced by CalculateEtaEndPoint(), DrawAxisTicks(), DrawBeamLine(), GetIrRegionLength(), home(), and ir().
double EicToyModel::mIrRegionRadius private
Definition at line 238 of file EicToyModel.h.
View newest version in sPHENIX GitHub at line 238 of file EicToyModel.h
Referenced by CalculateEtaEndPoint(), DrawAxisTicks(), GetIrRegionRadius(), home(), and ir().
bool EicToyModel::mMirrorImage private
Definition at line 279 of file EicToyModel.h.
View newest version in sPHENIX GitHub at line 279 of file EicToyModel.h
Referenced by DrawAxisTicks(), DrawBeamLine(), DrawEtaBoundaries(), DrawEtaLines(), DrawFlatFieldLines(), DrawMe(), home(), and mirror().
TString EicToyModel::mName private
Definition at line 236 of file EicToyModel.h.
View newest version in sPHENIX GitHub at line 236 of file EicToyModel.h
Referenced by GetName(), and SetName().
bool EicToyModel::mNewCanvasRequired private
Definition at line 305 of file EicToyModel.h.
View newest version in sPHENIX GitHub at line 305 of file EicToyModel.h
Referenced by DrawMe(), home(), mirror(), width(), and zoom().
EicToyModel::OneSide EicToyModel::mOneSideMode private
Definition at line 280 of file EicToyModel.h.
View newest version in sPHENIX GitHub at line 280 of file EicToyModel.h
Referenced by DrawMe(), full(), home(), left(), right(), and WriteText().
EtmPalette EicToyModel::mPalette private
Definition at line 282 of file EicToyModel.h.
View newest version in sPHENIX GitHub at line 282 of file EicToyModel.h
Referenced by Palette().
std::vector<EtmDetectorStack*> EicToyModel::mStacks private
Definition at line 234 of file EicToyModel.h.
View newest version in sPHENIX GitHub at line 234 of file EicToyModel.h
Referenced by acceptance(), bck(), CalculateDefaultEtaBoundaries(), DrawColorLegend(), DrawEtaBoundaries(), DrawMe(), ExportCADmodel(), fwd(), GetStack(), mid(), PlaceG4Volumes(), and vtx().
bool EicToyModel::mUseDetectorHighlighting
Definition at line 310 of file EicToyModel.h.
View newest version in sPHENIX GitHub at line 310 of file EicToyModel.h
Referenced by UseDetectorHighlighting().
EtmVacuumChamber* EicToyModel::mVacuumChamber private
Definition at line 275 of file EicToyModel.h.
View newest version in sPHENIX GitHub at line 275 of file EicToyModel.h
Referenced by BuildVacuumChamber(), DefineVacuumChamber(), DrawMe(), Export(), ExportVacuumChamber(), GetVacuumChamber(), ip(), RebuildEverything(), and SetCrossingAngle().
double EicToyModel::mX0 private
Definition at line 266 of file EicToyModel.h.
View newest version in sPHENIX GitHub at line 266 of file EicToyModel.h
Referenced by cnv(), DrawColorLegend(), home(), and zoom().
unsigned EicToyModel::mXdim private
Definition at line 264 of file EicToyModel.h.
View newest version in sPHENIX GitHub at line 264 of file EicToyModel.h
Referenced by DrawMe(), width(), and WriteText().
double EicToyModel::mXsize private
Definition at line 266 of file EicToyModel.h.
View newest version in sPHENIX GitHub at line 266 of file EicToyModel.h
Referenced by cnv(), DrawMe(), home(), and zoom().
double EicToyModel::mY0 private
Definition at line 266 of file EicToyModel.h.
View newest version in sPHENIX GitHub at line 266 of file EicToyModel.h
Referenced by cnv(), DrawColorLegend(), home(), and zoom().
unsigned EicToyModel::mYdim private
Definition at line 264 of file EicToyModel.h.
View newest version in sPHENIX GitHub at line 264 of file EicToyModel.h
Referenced by DrawMe().
double EicToyModel::mYsize private
Definition at line 266 of file EicToyModel.h.
View newest version in sPHENIX GitHub at line 266 of file EicToyModel.h
Referenced by cnv(), DrawColorLegend(), DrawMe(), home(), and zoom().
bool EicToyModel::mZoomedView private
Definition at line 268 of file EicToyModel.h.
View newest version in sPHENIX GitHub at line 268 of file EicToyModel.h
Referenced by DrawMe(), home(), and zoom().
The documentation for this class was generated from the following files:
EicToyModel/blob/master/include/EicToyModel.h
EicToyModel/blob/master/source/EicToyModel.cc