EIC Software: FairTrackPar Class Reference
FairTrackPar Class Reference
#include <EicRoot/blob/master/trackbase/FairTrackPar.h>
Public Member Functions
FairTrackPar ()
FairTrackPar (Double_t x, Double_t y, Double_t z, Double_t fx, Double_t fy, Double_t fz, Int_t q)
virtual ~FairTrackPar ()
virtual void Print (Option_t *option="") const
virtual TVector3 GetPosition () const
virtual Double_t GetX ()
virtual Double_t GetY ()
virtual Double_t GetZ ()
Int_t GetQ () const
virtual Double_t GetDX () const
virtual Double_t GetDY () const
virtual Double_t GetDZ () const
virtual TVector3 GetMomentum () const
virtual Double_t GetPx () const
virtual Double_t GetPy () const
virtual Double_t GetPz () const
virtual Double_t GetQp () const
virtual Double_t GetDPx () const
virtual Double_t GetDPy () const
virtual Double_t GetDPz () const
virtual Double_t GetDQp () const
virtual void SetX (Double_t x)
virtual void SetY (Double_t y)
virtual void SetZ (Double_t z)
virtual void SetDX (Double_t dx)
virtual void SetDY (Double_t dy)
virtual void SetDZ (Double_t dz)
virtual void SetPx (Double_t px)
virtual void SetPy (Double_t py)
virtual void SetPz (Double_t pz)
virtual void SetDPx (Double_t dpx)
virtual void SetDPy (Double_t dpy)
virtual void SetDPz (Double_t dpz)
void SetQp (Double_t qp)
Protected Member Functions
ClassDef (FairTrackPar, 1)
/// FairLogger
Protected Attributes
Double_t fX
Double_t fY
Double_t fZ
Double_t fDX
Double_t fDY
Double_t fDZ
Double_t fPx
Double_t fPy
Double_t fPz
Double_t fDPx
Double_t fDPy
Double_t fDPz
Double_t fQp
Double_t fDQp
Int_t fq
FairLogger * fLogger
Detailed Description
Definition at line 9 of file FairTrackPar.h.
View newest version in sPHENIX GitHub at line 9 of file FairTrackPar.h
Constructor & Destructor Documentation
FairTrackPar::FairTrackPar ()
Constructor
Definition at line 12 of file FairTrackPar.cxx.
View newest version in sPHENIX GitHub at line 12 of file FairTrackPar.cxx
FairTrackPar::FairTrackPar (Double_t x, Double_t y, Double_t z, Double_t fx, Double_t fy, Double_t fz, Int_t q)
Constructor with all variables
Definition at line 37 of file FairTrackPar.cxx.
View newest version in sPHENIX GitHub at line 37 of file FairTrackPar.cxx
References fPx, fPy, fPz, fQp, and p.
FairTrackPar::~FairTrackPar () virtual
Destructor
Definition at line 67 of file FairTrackPar.cxx.
View newest version in sPHENIX GitHub at line 67 of file FairTrackPar.cxx
Member Function Documentation
FairTrackPar::ClassDef (FairTrackPar , 1) protected
/// FairLogger
virtual Double_t FairTrackPar::GetDPx () const inline virtual
Definition at line 45 of file FairTrackPar.h.
View newest version in sPHENIX GitHub at line 45 of file FairTrackPar.h
References fDPx.
Referenced by FairTrackParH::CalCov(), FairTrackParH::FairTrackParH(), PndRecoKalmanFit::Fit(), PndRecoDafFit::Fit(), and FairTrackParH::SetTrackPar().
virtual Double_t FairTrackPar::GetDPy () const inline virtual
Definition at line 46 of file FairTrackPar.h.
View newest version in sPHENIX GitHub at line 46 of file FairTrackPar.h
References fDPy.
Referenced by FairTrackParH::CalCov(), FairTrackParH::FairTrackParH(), PndRecoKalmanFit::Fit(), PndRecoDafFit::Fit(), and FairTrackParH::SetTrackPar().
virtual Double_t FairTrackPar::GetDPz () const inline virtual
Definition at line 47 of file FairTrackPar.h.
View newest version in sPHENIX GitHub at line 47 of file FairTrackPar.h
References fDPz.
Referenced by FairTrackParH::CalCov(), FairTrackParH::FairTrackParH(), PndRecoKalmanFit::Fit(), PndRecoDafFit::Fit(), and FairTrackParH::SetTrackPar().
virtual Double_t FairTrackPar::GetDQp () const inline virtual
Definition at line 48 of file FairTrackPar.h.
View newest version in sPHENIX GitHub at line 48 of file FairTrackPar.h
References fDQp.
virtual Double_t FairTrackPar::GetDX () const inline virtual
Definition at line 34 of file FairTrackPar.h.
View newest version in sPHENIX GitHub at line 34 of file FairTrackPar.h
References fDX.
Referenced by FairTrackParH::FairTrackParH(), PndRecoDafFit::Fit(), and PndRecoKalmanFit::Fit().
virtual Double_t FairTrackPar::GetDY () const inline virtual
Definition at line 35 of file FairTrackPar.h.
View newest version in sPHENIX GitHub at line 35 of file FairTrackPar.h
References fDY.
Referenced by FairTrackParH::FairTrackParH(), PndRecoDafFit::Fit(), and PndRecoKalmanFit::Fit().
virtual Double_t FairTrackPar::GetDZ () const inline virtual
Definition at line 36 of file FairTrackPar.h.
View newest version in sPHENIX GitHub at line 36 of file FairTrackPar.h
References fDZ.
Referenced by FairTrackParH::FairTrackParH(), PndRecoDafFit::Fit(), and PndRecoKalmanFit::Fit().
virtual TVector3 FairTrackPar::GetMomentum () const inline virtual
Definition at line 38 of file FairTrackPar.h.
View newest version in sPHENIX GitHub at line 38 of file FairTrackPar.h
References fPx, fPy, and fPz.
Referenced by analysis_vtx(), PndPidCorrelator::ConstructChargedCandidate(), and PndPidCorrelator::GetTrackInfo().
virtual TVector3 FairTrackPar::GetPosition () const inline virtual
Accessors
Definition at line 27 of file FairTrackPar.h.
View newest version in sPHENIX GitHub at line 27 of file FairTrackPar.h
References fX, fY, and fZ.
virtual Double_t FairTrackPar::GetPx () const inline virtual
Definition at line 40 of file FairTrackPar.h.
View newest version in sPHENIX GitHub at line 40 of file FairTrackPar.h
References fPx.
Referenced by CbmRichTrackExtrapolationKF::DoExtrapolation(), FairTrackParH::FairTrackParH(), PndRecoKalmanFit::Fit(), PndRecoDafFit::Fit(), FairGeanePro::Init(), and FairGeanePro::Propagate().
virtual Double_t FairTrackPar::GetPy () const inline virtual
Definition at line 41 of file FairTrackPar.h.
View newest version in sPHENIX GitHub at line 41 of file FairTrackPar.h
References fPy.
Referenced by CbmRichTrackExtrapolationKF::DoExtrapolation(), FairTrackParH::FairTrackParH(), PndRecoKalmanFit::Fit(), PndRecoDafFit::Fit(), FairGeanePro::Init(), and FairGeanePro::Propagate().
virtual Double_t FairTrackPar::GetPz () const inline virtual
Definition at line 42 of file FairTrackPar.h.
View newest version in sPHENIX GitHub at line 42 of file FairTrackPar.h
References fPz.
Referenced by CbmRichTrackExtrapolationKF::DoExtrapolation(), FairTrackParH::FairTrackParH(), PndRecoKalmanFit::Fit(), PndRecoDafFit::Fit(), FairGeanePro::Init(), and FairGeanePro::Propagate().
Int_t FairTrackPar::GetQ () const inline
Definition at line 32 of file FairTrackPar.h.
View newest version in sPHENIX GitHub at line 32 of file FairTrackPar.h
References fq.
Referenced by PndRecoMultiKalmanTask::Exec(), PndRecoKalmanTask::Exec(), FairTrackParH::FairTrackParH(), FairTrackParP::FairTrackParP(), PndRecoDafFit::Fit(), PndRecoKalmanFit::Fit(), PndPidCorrelator::GetTrackInfo(), and FairGeanePro::Propagate().
virtual Double_t FairTrackPar::GetQp () const inline virtual
Definition at line 43 of file FairTrackPar.h.
View newest version in sPHENIX GitHub at line 43 of file FairTrackPar.h
References fQp.
Referenced by CbmRichTrackExtrapolationKF::DoExtrapolation(), GeaneTrackRep::extrapolate(), GeaneTrackRep::extrapolateToPoint(), FairTrackParH::FairTrackParH(), and FairTrackParP::FairTrackParP().
virtual Double_t FairTrackPar::GetX () inline virtual
Reimplemented in FairTrackParH.
Definition at line 29 of file FairTrackPar.h.
View newest version in sPHENIX GitHub at line 29 of file FairTrackPar.h
References fX.
Referenced by CbmRichTrackExtrapolationKF::DoExtrapolation(), GeaneTrackRep::extrapolate(), GeaneTrackRep::extrapolateToPoint(), FairTrackParH::FairTrackParH(), PndRecoDafFit::Fit(), PndRecoKalmanFit::Fit(), PndPidCorrelator::GetTrackInfo(), FairGeanePro::Init(), and FairGeanePro::Propagate().
virtual Double_t FairTrackPar::GetY () inline virtual
Reimplemented in FairTrackParH.
Definition at line 30 of file FairTrackPar.h.
View newest version in sPHENIX GitHub at line 30 of file FairTrackPar.h
References fY.
Referenced by CbmRichTrackExtrapolationKF::DoExtrapolation(), GeaneTrackRep::extrapolate(), GeaneTrackRep::extrapolateToPoint(), FairTrackParH::FairTrackParH(), PndRecoDafFit::Fit(), PndRecoKalmanFit::Fit(), PndPidCorrelator::GetTrackInfo(), FairGeanePro::Init(), and FairGeanePro::Propagate().
virtual Double_t FairTrackPar::GetZ () inline virtual
Reimplemented in FairTrackParH.
Definition at line 31 of file FairTrackPar.h.
View newest version in sPHENIX GitHub at line 31 of file FairTrackPar.h
References fZ.
Referenced by CbmRichTrackExtrapolationKF::DoExtrapolation(), GeaneTrackRep::extrapolate(), GeaneTrackRep::extrapolateToPoint(), FairTrackParH::FairTrackParH(), PndRecoDafFit::Fit(), PndRecoKalmanFit::Fit(), PndPidCorrelator::GetTrackInfo(), FairGeanePro::Init(), and FairGeanePro::Propagate().
void FairTrackPar::Print (Option_t * option = "") const virtual
Output to screen
Reimplemented in FairTrackParP, and FairTrackParH.
Definition at line 71 of file FairTrackPar.cxx.
View newest version in sPHENIX GitHub at line 71 of file FairTrackPar.cxx
References fLogger, fPx, fPy, fPz, fX, fY, fZ, FairLogger::Info(), and MESSAGE_ORIGIN.
virtual void FairTrackPar::SetDPx (Double_t dpx) inline virtual
Definition at line 64 of file FairTrackPar.h.
View newest version in sPHENIX GitHub at line 64 of file FairTrackPar.h
References fDPx.
virtual void FairTrackPar::SetDPy (Double_t dpy) inline virtual
Definition at line 65 of file FairTrackPar.h.
View newest version in sPHENIX GitHub at line 65 of file FairTrackPar.h
References fDPy.
virtual void FairTrackPar::SetDPz (Double_t dpz) inline virtual
Definition at line 66 of file FairTrackPar.h.
View newest version in sPHENIX GitHub at line 66 of file FairTrackPar.h
References fDPz.
virtual void FairTrackPar::SetDX (Double_t dx) inline virtual
Definition at line 56 of file FairTrackPar.h.
View newest version in sPHENIX GitHub at line 56 of file FairTrackPar.h
References dx, and fDX.
virtual void FairTrackPar::SetDY (Double_t dy) inline virtual
Definition at line 57 of file FairTrackPar.h.
View newest version in sPHENIX GitHub at line 57 of file FairTrackPar.h
References dy, and fDY.
virtual void FairTrackPar::SetDZ (Double_t dz) inline virtual
Definition at line 58 of file FairTrackPar.h.
View newest version in sPHENIX GitHub at line 58 of file FairTrackPar.h
References dz, and fDZ.
virtual void FairTrackPar::SetPx (Double_t px) inline virtual
Definition at line 60 of file FairTrackPar.h.
View newest version in sPHENIX GitHub at line 60 of file FairTrackPar.h
References fPx.
Referenced by FairTrackParH::FairTrackParH(), FairTrackParP::FairTrackParP(), FairTrackParP::SetTrackPar(), and FairTrackParH::SetTrackPar().
virtual void FairTrackPar::SetPy (Double_t py) inline virtual
Definition at line 61 of file FairTrackPar.h.
View newest version in sPHENIX GitHub at line 61 of file FairTrackPar.h
References fPy.
Referenced by FairTrackParH::FairTrackParH(), FairTrackParP::FairTrackParP(), FairTrackParP::SetTrackPar(), and FairTrackParH::SetTrackPar().
virtual void FairTrackPar::SetPz (Double_t pz) inline virtual
Definition at line 62 of file FairTrackPar.h.
View newest version in sPHENIX GitHub at line 62 of file FairTrackPar.h
References fPz.
Referenced by FairTrackParH::FairTrackParH(), FairTrackParP::FairTrackParP(), FairTrackParP::SetTrackPar(), and FairTrackParH::SetTrackPar().
void FairTrackPar::SetQp (Double_t qp) inline
Definition at line 68 of file FairTrackPar.h.
View newest version in sPHENIX GitHub at line 68 of file FairTrackPar.h
References fQp.
virtual void FairTrackPar::SetX (Double_t x) inline virtual
Definition at line 52 of file FairTrackPar.h.
View newest version in sPHENIX GitHub at line 52 of file FairTrackPar.h
References fX, and x.
Referenced by FairTrackParH::FairTrackParH(), FairTrackParP::FairTrackParP(), FairTrackParP::SetTrackPar(), and FairTrackParH::SetTrackPar().
virtual void FairTrackPar::SetY (Double_t y) inline virtual
Definition at line 53 of file FairTrackPar.h.
View newest version in sPHENIX GitHub at line 53 of file FairTrackPar.h
References fY, and y.
Referenced by FairTrackParH::FairTrackParH(), FairTrackParP::FairTrackParP(), FairTrackParP::SetTrackPar(), and FairTrackParH::SetTrackPar().
virtual void FairTrackPar::SetZ (Double_t z) inline virtual
Definition at line 54 of file FairTrackPar.h.
View newest version in sPHENIX GitHub at line 54 of file FairTrackPar.h
References fZ, and z.
Referenced by FairTrackParH::FairTrackParH(), FairTrackParP::FairTrackParP(), FairTrackParP::SetTrackPar(), and FairTrackParH::SetTrackPar().
Member Data Documentation
Double_t FairTrackPar::fDPx protected
Error in momentum [GeV]
Definition at line 83 of file FairTrackPar.h.
View newest version in sPHENIX GitHub at line 83 of file FairTrackPar.h
Referenced by FairTrackParH::CalCov(), FairTrackParH::FairTrackParH(), FairTrackParP::FairTrackParP(), GetDPx(), FairTrackParP::Reset(), FairTrackParH::Reset(), SetDPx(), FairTrackParP::SetTrackPar(), and FairTrackParH::SetTrackPar().
Double_t FairTrackPar::fDPy protected
Definition at line 83 of file FairTrackPar.h.
View newest version in sPHENIX GitHub at line 83 of file FairTrackPar.h
Referenced by FairTrackParH::CalCov(), FairTrackParH::FairTrackParH(), FairTrackParP::FairTrackParP(), GetDPy(), FairTrackParP::Reset(), FairTrackParH::Reset(), SetDPy(), FairTrackParP::SetTrackPar(), and FairTrackParH::SetTrackPar().
Double_t FairTrackPar::fDPz protected
Definition at line 83 of file FairTrackPar.h.
View newest version in sPHENIX GitHub at line 83 of file FairTrackPar.h
Referenced by FairTrackParH::CalCov(), FairTrackParH::FairTrackParH(), FairTrackParP::FairTrackParP(), GetDPz(), FairTrackParP::Reset(), FairTrackParH::Reset(), SetDPz(), FairTrackParP::SetTrackPar(), and FairTrackParH::SetTrackPar().
Double_t FairTrackPar::fDQp protected
Error in charge over momentum [1/GeV]
Definition at line 89 of file FairTrackPar.h.
View newest version in sPHENIX GitHub at line 89 of file FairTrackPar.h
Referenced by FairTrackParH::CalCov(), FairTrackParH::FairTrackParH(), FairTrackParP::FairTrackParP(), GetDQp(), FairTrackParP::Reset(), FairTrackParH::Reset(), FairTrackParP::SetTrackPar(), and FairTrackParH::SetTrackPar().
Double_t FairTrackPar::fDX protected
Error in position of track [cm]
Definition at line 77 of file FairTrackPar.h.
View newest version in sPHENIX GitHub at line 77 of file FairTrackPar.h
Referenced by FairTrackParH::FairTrackParH(), FairTrackParP::FairTrackParP(), GetDX(), FairTrackParP::Reset(), FairTrackParH::Reset(), SetDX(), FairTrackParP::SetTrackPar(), and FairTrackParH::SetTrackPar().
Double_t FairTrackPar::fDY protected
Definition at line 77 of file FairTrackPar.h.
View newest version in sPHENIX GitHub at line 77 of file FairTrackPar.h
Referenced by FairTrackParH::FairTrackParH(), FairTrackParP::FairTrackParP(), GetDY(), FairTrackParP::Reset(), FairTrackParH::Reset(), SetDY(), FairTrackParP::SetTrackPar(), and FairTrackParH::SetTrackPar().
Double_t FairTrackPar::fDZ protected
Definition at line 77 of file FairTrackPar.h.
View newest version in sPHENIX GitHub at line 77 of file FairTrackPar.h
Referenced by FairTrackParH::FairTrackParH(), FairTrackParP::FairTrackParP(), GetDZ(), FairTrackParP::Reset(), FairTrackParH::Reset(), SetDZ(), FairTrackParP::SetTrackPar(), and FairTrackParH::SetTrackPar().
FairLogger* FairTrackPar::fLogger protected
Definition at line 94 of file FairTrackPar.h.
View newest version in sPHENIX GitHub at line 94 of file FairTrackPar.h
Referenced by Print().
Double_t FairTrackPar::fPx protected
momentum [GeV]
Definition at line 80 of file FairTrackPar.h.
View newest version in sPHENIX GitHub at line 80 of file FairTrackPar.h
Referenced by FairTrackParH::CalCov(), FairTrackPar(), FairTrackParH::FairTrackParH(), FairTrackParP::FairTrackParP(), GetMomentum(), GetPx(), Print(), FairTrackParP::Reset(), FairTrackParH::Reset(), SetPx(), FairTrackParP::SetTrackPar(), and FairTrackParH::SetTrackPar().
Double_t FairTrackPar::fPy protected
Definition at line 80 of file FairTrackPar.h.
View newest version in sPHENIX GitHub at line 80 of file FairTrackPar.h
Referenced by FairTrackParH::CalCov(), FairTrackPar(), FairTrackParH::FairTrackParH(), FairTrackParP::FairTrackParP(), GetMomentum(), GetPy(), Print(), FairTrackParP::Reset(), FairTrackParH::Reset(), SetPy(), FairTrackParP::SetTrackPar(), and FairTrackParH::SetTrackPar().
Double_t FairTrackPar::fPz protected
Definition at line 80 of file FairTrackPar.h.
View newest version in sPHENIX GitHub at line 80 of file FairTrackPar.h
Referenced by FairTrackParH::CalCov(), FairTrackPar(), FairTrackParH::FairTrackParH(), FairTrackParP::FairTrackParP(), GetMomentum(), GetPz(), Print(), FairTrackParP::Reset(), FairTrackParH::Reset(), SetPz(), FairTrackParP::SetTrackPar(), and FairTrackParH::SetTrackPar().
Int_t FairTrackPar::fq protected
charge
Definition at line 92 of file FairTrackPar.h.
View newest version in sPHENIX GitHub at line 92 of file FairTrackPar.h
Referenced by FairTrackParH::FairTrackParH(), FairTrackParP::FairTrackParP(), FairTrackParH::GetCovQ(), FairTrackParP::GetCovQ(), GetQ(), FairTrackParP::Reset(), FairTrackParH::Reset(), FairTrackParP::SetTrackPar(), and FairTrackParH::SetTrackPar().
Double_t FairTrackPar::fQp protected
Charge over momentum [1/GeV]
Definition at line 86 of file FairTrackPar.h.
View newest version in sPHENIX GitHub at line 86 of file FairTrackPar.h
Referenced by FairTrackPar(), FairTrackParH::FairTrackParH(), FairTrackParP::FairTrackParP(), GetQp(), FairTrackParH::Print(), FairTrackParP::Print(), FairTrackParP::Reset(), FairTrackParH::Reset(), SetQp(), FairTrackParP::SetTrackPar(), and FairTrackParH::SetTrackPar().
Double_t FairTrackPar::fX protected
Position of track [cm]
Definition at line 68 of file FairTrackPar.h.
View newest version in sPHENIX GitHub at line 68 of file FairTrackPar.h
Referenced by FairTrackParH::FairTrackParH(), FairTrackParP::FairTrackParP(), GetPosition(), GetX(), FairTrackParH::GetX(), Print(), FairTrackParH::Print(), FairTrackParP::Print(), FairTrackParP::Reset(), FairTrackParH::Reset(), FairTrackParP::SetTrackPar(), FairTrackParH::SetTrackPar(), and SetX().
Double_t FairTrackPar::fY protected
Definition at line 68 of file FairTrackPar.h.
View newest version in sPHENIX GitHub at line 68 of file FairTrackPar.h
Referenced by FairTrackParH::FairTrackParH(), FairTrackParP::FairTrackParP(), GetPosition(), GetY(), FairTrackParH::GetY(), Print(), FairTrackParH::Print(), FairTrackParP::Print(), FairTrackParP::Reset(), FairTrackParH::Reset(), FairTrackParP::SetTrackPar(), FairTrackParH::SetTrackPar(), and SetY().
Double_t FairTrackPar::fZ protected
Definition at line 68 of file FairTrackPar.h.
View newest version in sPHENIX GitHub at line 68 of file FairTrackPar.h
Referenced by FairTrackParH::CalCov(), FairTrackParH::FairTrackParH(), FairTrackParP::FairTrackParP(), GetPosition(), GetZ(), FairTrackParH::GetZ(), Print(), FairTrackParH::Print(), FairTrackParP::Print(), FairTrackParP::Reset(), FairTrackParH::Reset(), FairTrackParP::SetTrackPar(), FairTrackParH::SetTrackPar(), and SetZ().
The documentation for this class was generated from the following files:
EicRoot/blob/master/trackbase/FairTrackPar.h
EicRoot/blob/master/trackbase/FairTrackPar.cxx