EIC Software: CbmMCStage Class Reference
CbmMCStage Class Reference
#include <EicRoot/blob/master/cbmbase/CbmMCStage.h>
Public Member Functions
CbmMCStage ()
CbmMCStage (DataType id, std::string fileName, std::string branchName, Double_t weight=1.0)
CbmMCStage (const CbmMCStage &mcStage)
virtual ~CbmMCStage ()
void SetBranchName (std::string branchName)
void SetFileName (std::string fileName)
void SetWeight (Double_t weight)
void SetLoaded (Bool_t loaded)
void SetFill (Bool_t fill)
std::string GetBranchName (void) const
std::string GetFileName (void) const
Double_t GetWeight (void) const
Bool_t GetLoaded (void) const
Bool_t GetFill (void) const
CbmMCStage & operator= (const CbmMCStage &result)
virtual void ClearEntries ()
virtual void Print (std::ostream &out)
Public Member Functions inherited from CbmMCObject
CbmMCObject ()
CbmMCObject (DataType type)
CbmMCObject (const CbmMCObject &obj)
CbmMCObject (DataType type, std::vector< CbmMCEntry > stage)
virtual ~CbmMCObject ()
void SetStageId (DataType type)
void SetEntry (std::vector< Int_t > type, std::vector< Int_t > link, int index)
void SetEntry (FairMultiLinkedData *data, int index)
void SetEntry (CbmMCEntry link)
void SetStage (std::vector< CbmMCEntry > stage)
void SetLink (FairLink link, int index)
void AddLink (FairLink link, int index)
CbmMCEntry GetEntry (int index) const
FairLink GetSingleLink (int entryIndex, int linkIndex) const
DataType GetStageId (void) const
CbmMCEntry GetMCLink (Int_t index)
int GetNEntries () const
int GetNLinks (int entryIndex) const
std::vector< CbmMCEntry > GetEntryVector () const
FairMultiLinkedData PosInList (FairLink link)
FairMultiLinkedData GetLinksWithType (DataType type)
CbmMCObject & operator= (const CbmMCObject &obj)
Private Member Functions
ClassDef (CbmMCStage, 1)
Private Attributes
std::string fBranchName
std::string fFileName
Double_t fWeight
Bool_t fLoaded
indicates if this stage was loaded already from a Link file
Bool_t fFill
indicates if a corresponding DataFile with FairLinks exists to fill this stage
Friends
std::ostream & operator<< (std::ostream &out, const CbmMCStage &stage)
Detailed Description
Definition at line 16 of file CbmMCStage.h.
View newest version in sPHENIX GitHub at line 16 of file CbmMCStage.h
Constructor & Destructor Documentation
CbmMCStage::CbmMCStage ()
Definition at line 12 of file CbmMCStage.cxx.
View newest version in sPHENIX GitHub at line 12 of file CbmMCStage.cxx
CbmMCStage::CbmMCStage (DataType id, std::string fileName, std::string branchName, Double_t weight = 1.0)
Definition at line 25 of file CbmMCStage.cxx.
View newest version in sPHENIX GitHub at line 25 of file CbmMCStage.cxx
CbmMCStage::CbmMCStage (const CbmMCStage & mcStage) inline
Definition at line 20 of file CbmMCStage.h.
View newest version in sPHENIX GitHub at line 20 of file CbmMCStage.h
CbmMCStage::~CbmMCStage () virtual
Definition at line 22 of file CbmMCStage.cxx.
View newest version in sPHENIX GitHub at line 22 of file CbmMCStage.cxx
Member Function Documentation
CbmMCStage::ClassDef (CbmMCStage , 1) private
virtual void CbmMCStage::ClearEntries () inline virtual
Reimplemented from CbmMCObject.
Definition at line 54 of file CbmMCStage.h.
View newest version in sPHENIX GitHub at line 54 of file CbmMCStage.h
References CbmMCObject::ClearEntries(), and fLoaded.
std::string CbmMCStage::GetBranchName (void) const inline
Definition at line 37 of file CbmMCStage.h.
View newest version in sPHENIX GitHub at line 37 of file CbmMCStage.h
References fBranchName.
Referenced by CbmMCMatchCreatorTask::Exec(), CbmMCMatchCreatorTask::InitBranches(), and operator=().
std::string CbmMCStage::GetFileName (void) const inline
Definition at line 38 of file CbmMCStage.h.
View newest version in sPHENIX GitHub at line 38 of file CbmMCStage.h
References fFileName.
Referenced by operator=().
Bool_t CbmMCStage::GetFill (void) const inline
Definition at line 41 of file CbmMCStage.h.
View newest version in sPHENIX GitHub at line 41 of file CbmMCStage.h
References fFill.
Referenced by CbmMCMatchCreatorTask::Exec().
Bool_t CbmMCStage::GetLoaded (void) const inline
Definition at line 40 of file CbmMCStage.h.
View newest version in sPHENIX GitHub at line 40 of file CbmMCStage.h
References fLoaded.
Referenced by CbmMCMatchCreatorTask::Exec().
Double_t CbmMCStage::GetWeight (void) const inline
Definition at line 39 of file CbmMCStage.h.
View newest version in sPHENIX GitHub at line 39 of file CbmMCStage.h
References fWeight.
Referenced by CbmMCMatch::GetMCInfoBackward(), CbmMCMatch::GetNextStage(), and operator=().
CbmMCStage& CbmMCStage::operator= (const CbmMCStage & result) inline
Definition at line 43 of file CbmMCStage.h.
View newest version in sPHENIX GitHub at line 43 of file CbmMCStage.h
References fBranchName, fFileName, fFill, fLoaded, fWeight, GetBranchName(), GetFileName(), GetWeight(), and CbmMCObject::operator=().
virtual void CbmMCStage::Print (std::ostream & out) inline virtual
Reimplemented from CbmMCObject.
Definition at line 60 of file CbmMCStage.h.
View newest version in sPHENIX GitHub at line 60 of file CbmMCStage.h
void CbmMCStage::SetBranchName (std::string branchName) inline
Definition at line 31 of file CbmMCStage.h.
View newest version in sPHENIX GitHub at line 31 of file CbmMCStage.h
References fBranchName.
void CbmMCStage::SetFileName (std::string fileName) inline
Definition at line 32 of file CbmMCStage.h.
View newest version in sPHENIX GitHub at line 32 of file CbmMCStage.h
References fFileName.
void CbmMCStage::SetFill (Bool_t fill) inline
Definition at line 35 of file CbmMCStage.h.
View newest version in sPHENIX GitHub at line 35 of file CbmMCStage.h
References fFill.
Referenced by CbmMCMatchCreatorTask::InitBranches().
void CbmMCStage::SetLoaded (Bool_t loaded) inline
Definition at line 34 of file CbmMCStage.h.
View newest version in sPHENIX GitHub at line 34 of file CbmMCStage.h
References fLoaded, and loaded.
Referenced by CbmMCMatchCreatorTask::Exec().
void CbmMCStage::SetWeight (Double_t weight) inline
Definition at line 33 of file CbmMCStage.h.
View newest version in sPHENIX GitHub at line 33 of file CbmMCStage.h
References fWeight.
Referenced by CbmMCMatch::SetCommonWeightStages(), and CbmMCMatchSelectorTask::SetWeights().
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & out, const CbmMCStage & stage) friend
Definition at line 62 of file CbmMCStage.h.
View newest version in sPHENIX GitHub at line 62 of file CbmMCStage.h
Member Data Documentation
std::string CbmMCStage::fBranchName private
Definition at line 69 of file CbmMCStage.h.
View newest version in sPHENIX GitHub at line 69 of file CbmMCStage.h
Referenced by GetBranchName(), operator=(), and SetBranchName().
std::string CbmMCStage::fFileName private
Definition at line 70 of file CbmMCStage.h.
View newest version in sPHENIX GitHub at line 70 of file CbmMCStage.h
Referenced by GetFileName(), operator=(), and SetFileName().
Bool_t CbmMCStage::fFill private
indicates if a corresponding DataFile with FairLinks exists to fill this stage
Definition at line 73 of file CbmMCStage.h.
View newest version in sPHENIX GitHub at line 73 of file CbmMCStage.h
Referenced by GetFill(), operator=(), and SetFill().
Bool_t CbmMCStage::fLoaded private
indicates if this stage was loaded already from a Link file
Definition at line 72 of file CbmMCStage.h.
View newest version in sPHENIX GitHub at line 72 of file CbmMCStage.h
Referenced by ClearEntries(), GetLoaded(), operator=(), and SetLoaded().
Double_t CbmMCStage::fWeight private
Definition at line 71 of file CbmMCStage.h.
View newest version in sPHENIX GitHub at line 71 of file CbmMCStage.h
Referenced by GetWeight(), operator=(), and SetWeight().
The documentation for this class was generated from the following files:
EicRoot/blob/master/cbmbase/CbmMCStage.h
EicRoot/blob/master/cbmbase/CbmMCStage.cxx