EIC Software: FairDetParRootFileIo Class Reference
FairDetParRootFileIo Class Reference
#include <EicRoot/blob/master/parbase/FairDetParRootFileIo.h>
Public Member Functions
FairDetParRootFileIo (FairParRootFile *f)
virtual ~FairDetParRootFileIo ()
virtual Bool_t read (FairParSet *)
Int_t write (FairParSet *)
Public Member Functions inherited from FairDetParIo
FairDetParIo ()
virtual ~FairDetParIo ()
void setInputNumber (Int_t n)
Int_t getInputNumber ()
virtual Bool_t init (FairParSet *)
Protected Member Functions
Int_t findInputVersion (Text_t *contName)
Int_t getMaxVersion (Text_t *contName)
TObject * findContainer (Text_t *contName, Int_t version)
Protected Attributes
FairParRootFile * pFile
Protected Attributes inherited from FairDetParIo
Int_t inputNumber
Private Member Functions
FairDetParRootFileIo (const FairDetParRootFileIo &)
FairDetParRootFileIo & operator= (const FairDetParRootFileIo &)
Detailed Description
Definition at line 9 of file FairDetParRootFileIo.h.
View newest version in sPHENIX GitHub at line 9 of file FairDetParRootFileIo.h
Constructor & Destructor Documentation
FairDetParRootFileIo::FairDetParRootFileIo (FairParRootFile * f)
virtual FairDetParRootFileIo::~FairDetParRootFileIo () inline virtual
Definition at line 15 of file FairDetParRootFileIo.h.
View newest version in sPHENIX GitHub at line 15 of file FairDetParRootFileIo.h
FairDetParRootFileIo::FairDetParRootFileIo (const FairDetParRootFileIo &) private
Member Function Documentation
TObject * FairDetParRootFileIo::findContainer (Text_t * contName, Int_t version) protected
Definition at line 109 of file FairDetParRootFileIo.cxx.
View newest version in sPHENIX GitHub at line 109 of file FairDetParRootFileIo.cxx
References FairParRootFile::cd(), p, and pFile.
Int_t FairDetParRootFileIo::findInputVersion (Text_t * contName) protected
Definition at line 94 of file FairDetParRootFileIo.cxx.
View newest version in sPHENIX GitHub at line 94 of file FairDetParRootFileIo.cxx
References FairRuntimeDb::getCurrentRun(), FairParVersion::getInputVersion(), FairRtdbRun::getParVersion(), FairParVersion::getRootVersion(), FairParRootFile::getRun(), FairDetParIo::inputNumber, FairRuntimeDb::instance(), pFile, and v.
Referenced by read().
Int_t FairDetParRootFileIo::getMaxVersion (Text_t * contName) protected
Definition at line 85 of file FairDetParRootFileIo.cxx.
View newest version in sPHENIX GitHub at line 85 of file FairDetParRootFileIo.cxx
References FairParRootFile::GetKey(), and pFile.
Referenced by write().
FairDetParRootFileIo& FairDetParRootFileIo::operator= (const FairDetParRootFileIo &) private
Bool_t FairDetParRootFileIo::read (FairParSet * pPar) virtual
Definition at line 43 of file FairDetParRootFileIo.cxx.
View newest version in sPHENIX GitHub at line 43 of file FairDetParRootFileIo.cxx
References FairParSet::clear(), findInputVersion(), FairParSet::getInputVersion(), FairDetParIo::inputNumber, name, FairParSet::setChanged(), FairParSet::setInputVersion(), and conf::version.
Referenced by FairGenericParRootFileIo::init().
Int_t FairDetParRootFileIo::write (FairParSet * pPar) virtual
Reimplemented from FairDetParIo.
Definition at line 67 of file FairDetParRootFileIo.cxx.
View newest version in sPHENIX GitHub at line 67 of file FairDetParRootFileIo.cxx
References FairParRootFile::cd(), getMaxVersion(), FairRuntimeDb::instance(), FairParRootFile::IsWritable(), name, pFile, FairParSet::setChanged(), and FairRuntimeDb::setVersionsChanged().
Member Data Documentation
FairParRootFile* FairDetParRootFileIo::pFile protected
Definition at line 12 of file FairDetParRootFileIo.h.
View newest version in sPHENIX GitHub at line 12 of file FairDetParRootFileIo.h
Referenced by findContainer(), findInputVersion(), getMaxVersion(), FairGenericParRootFileIo::init(), and write().
The documentation for this class was generated from the following files:
EicRoot/blob/master/parbase/FairDetParRootFileIo.h
EicRoot/blob/master/parbase/FairDetParRootFileIo.cxx