EIC Software: FairDbString Class Reference
FairDbString Class Reference
#include <EicRoot/blob/master/dbase/dbInterface/FairDbString.h>
Public Member Functions
FairDbString ()
FairDbString (const Char_t *str)
FairDbString (const std::string &str)
virtual ~FairDbString ()
const Char_t * c_str () const
const std::string & GetString () const
FairDbString & operator<< (Int_t data)
FairDbString & operator<< (UInt_t data)
FairDbString & operator<< (Float_t data)
FairDbString & operator<< (Char_t data)
FairDbString & operator<< (const Char_t *data)
FairDbString & operator<< (const std::string &data)
void Clear ()
std::string & GetString ()
Private Attributes
std::string fString
Detailed Description
Definition at line 50 of file FairDbString.h.
View newest version in sPHENIX GitHub at line 50 of file FairDbString.h
Constructor & Destructor Documentation
FairDbString::FairDbString ()
FairDbString::FairDbString (const Char_t * str)
Definition at line 17 of file FairDbString.cxx.
View newest version in sPHENIX GitHub at line 17 of file FairDbString.cxx
FairDbString::FairDbString (const std::string & str)
Definition at line 23 of file FairDbString.cxx.
View newest version in sPHENIX GitHub at line 23 of file FairDbString.cxx
FairDbString::~FairDbString () virtual
Definition at line 27 of file FairDbString.cxx.
View newest version in sPHENIX GitHub at line 27 of file FairDbString.cxx
Member Function Documentation
const Char_t* FairDbString::c_str () const inline
Definition at line 60 of file FairDbString.h.
View newest version in sPHENIX GitHub at line 60 of file FairDbString.h
References fString.
Referenced by FairDbProxy::FindTimeBoundaries(), FairDbProxy::QuerySeqNo(), FairDbProxy::QuerySeqNos(), FairDbProxy::QueryValidity(), FairDbProxy::RemoveSeqNo(), FairDbProxy::ReplaceInsertDate(), FairDbProxy::ReplaceSeqNo(), FairDbProxy::ReplaceSeqNoOracle(), and FairDbMultConnector::ReserveNextSeqNo().
void FairDbString::Clear () inline
Definition at line 70 of file FairDbString.h.
View newest version in sPHENIX GitHub at line 70 of file FairDbString.h
References fString.
Referenced by FairDbMultConnector::ReserveNextSeqNo().
const std::string& FairDbString::GetString () const inline
Definition at line 61 of file FairDbString.h.
View newest version in sPHENIX GitHub at line 61 of file FairDbString.h
References fString.
Referenced by FairDbProxy::QueryAllValidities(), FairDbProxy::RemoveSeqNo(), FairDbProxy::ReplaceSeqNo(), FairDbProxy::ReplaceSeqNoOracle(), and FairDbTableMetaData::Sql().
std::string& FairDbString::GetString () inline
Definition at line 71 of file FairDbString.h.
View newest version in sPHENIX GitHub at line 71 of file FairDbString.h
References fString.
FairDbString & FairDbString::operator<< (Int_t data)
Definition at line 38 of file FairDbString.cxx.
View newest version in sPHENIX GitHub at line 38 of file FairDbString.cxx
References OUT.
FairDbString & FairDbString::operator<< (UInt_t data)
Definition at line 39 of file FairDbString.cxx.
View newest version in sPHENIX GitHub at line 39 of file FairDbString.cxx
References OUT.
FairDbString & FairDbString::operator<< (Float_t data)
Definition at line 40 of file FairDbString.cxx.
View newest version in sPHENIX GitHub at line 40 of file FairDbString.cxx
References OUT.
FairDbString & FairDbString::operator<< (Char_t data)
Definition at line 41 of file FairDbString.cxx.
View newest version in sPHENIX GitHub at line 41 of file FairDbString.cxx
References fString.
FairDbString & FairDbString::operator<< (const Char_t * data)
Definition at line 46 of file FairDbString.cxx.
View newest version in sPHENIX GitHub at line 46 of file FairDbString.cxx
References fString.
FairDbString & FairDbString::operator<< (const std::string & data)
Definition at line 51 of file FairDbString.cxx.
View newest version in sPHENIX GitHub at line 51 of file FairDbString.cxx
References fString.
Member Data Documentation
std::string FairDbString::fString private
Definition at line 77 of file FairDbString.h.
View newest version in sPHENIX GitHub at line 77 of file FairDbString.h
Referenced by c_str(), Clear(), GetString(), and operator<<().
The documentation for this class was generated from the following files:
EicRoot/blob/master/dbase/dbInterface/FairDbString.h
EicRoot/blob/master/dbase/dbInterface/FairDbString.cxx