EIC Software: FairDbValidityRec Class Reference
FairDbValidityRec Class Reference
#include <EicRoot/blob/master/dbase/dbInterface/FairDbValidityRec.h>
Public Member Functions
FairDbValidityRec (Int_t dbNo=-1, Bool_t isGap=kTRUE)
FairDbValidityRec (const FairDbValidityRec &from)
FairDbValidityRec (const ValRange &range, FairDb::Task task, Int_t aggNo, UInt_t seqNo, Int_t dbNo=-1, Bool_t isGap=kFALSE, ValTimeStamp time=ValTimeStamp())
virtual ~FairDbValidityRec ()
virtual FairDbTableRow * CreateTableRow () const
Int_t GetAggregateNo () const
ValTimeStamp GetCreationDate () const
UInt_t GetDbNo () const
ValTimeStamp GetInsertDate () const
FairDb::Task GetTask () const
std::string GetL2CacheName () const
UInt_t GetSeqNo () const
const FairDbTableProxy * GetTableProxy () const
const ValRange & GetValRange () const
Bool_t HasExpired (const FairDbValidityRec &other) const
Bool_t HasExpired (const ValContext &vc, const FairDb::Task &task) const
Bool_t IsCompatible (const ValContext &vc, const FairDb::Task &task) const
Bool_t IsGap () const
void AndTimeWindow (const ValTimeStamp &start, const ValTimeStamp &end)
void SetAggregateNo (Int_t aggNo)
void SetDbNo (Int_t dbNo)
void SetTableProxy (const FairDbTableProxy *tp)
void SetTimeWindow (const ValTimeStamp &start, const ValTimeStamp &end)
void SetValRange (const ValRange &range)
void Trim (const ValTimeStamp &queryTime, const FairDbValidityRec &other)
virtual void Fill (FairDbResultSet &rs, const FairDbValidityRec *vrec)
virtual void Store (FairDbOutRowStream &ors, const FairDbValidityRec *vrec) const
void Streamer (FairDbBinaryFile &file)
Public Member Functions inherited from FairDbTableRow
FairDbTableRow ()
FairDbTableRow (const FairDbTableRow &from)
virtual ~FairDbTableRow ()
virtual Bool_t CanL2Cache () const
FairDbResult * GetOwner () const
virtual UInt_t GetIndex (UInt_t defIndex) const
void SetOwner (FairDbResult *owner)
Static Public Member Functions
static std::string GetL2CacheName (UInt_t seqLo, UInt_t seqHi, ValTimeStamp ts)
Private Attributes
Int_t fAggregateNo
ValTimeStamp fCreationDate
Int_t fDbNo
ValTimeStamp fInsertDate
Bool_t fIsGap
FairDb::Task fTask
Int_t fSeqNo
const FairDbTableProxy * fTableProxy
ValRange fValRange
Detailed Description
Definition at line 18 of file FairDbValidityRec.h.
View newest version in sPHENIX GitHub at line 18 of file FairDbValidityRec.h
Constructor & Destructor Documentation
FairDbValidityRec::FairDbValidityRec (Int_t dbNo = -1, Bool_t isGap = kTRUE)
Definition at line 58 of file FairDbValidityRec.cxx.
View newest version in sPHENIX GitHub at line 58 of file FairDbValidityRec.cxx
Referenced by CreateTableRow().
FairDbValidityRec::FairDbValidityRec (const FairDbValidityRec & from)
Definition at line 73 of file FairDbValidityRec.cxx.
View newest version in sPHENIX GitHub at line 73 of file FairDbValidityRec.cxx
FairDbValidityRec::FairDbValidityRec (const ValRange & range, FairDb::Task task, Int_t aggNo, UInt_t seqNo, Int_t dbNo = -1, Bool_t isGap = kFALSE, ValTimeStamp time = ValTimeStamp())
Definition at line 91 of file FairDbValidityRec.cxx.
View newest version in sPHENIX GitHub at line 91 of file FairDbValidityRec.cxx
FairDbValidityRec::~FairDbValidityRec () virtual
Definition at line 113 of file FairDbValidityRec.cxx.
View newest version in sPHENIX GitHub at line 113 of file FairDbValidityRec.cxx
Member Function Documentation
void FairDbValidityRec::AndTimeWindow (const ValTimeStamp & start, const ValTimeStamp & end)
Definition at line 45 of file FairDbValidityRec.cxx.
View newest version in sPHENIX GitHub at line 45 of file FairDbValidityRec.cxx
References fValRange, ValRange::GetTimeEnd(), ValRange::GetTimeStart(), SetTimeWindow(), and start().
virtual FairDbTableRow* FairDbValidityRec::CreateTableRow () const inline virtual
Implements FairDbTableRow.
Definition at line 39 of file FairDbValidityRec.h.
View newest version in sPHENIX GitHub at line 39 of file FairDbValidityRec.h
References FairDbValidityRec().
void FairDbValidityRec::Fill (FairDbResultSet & rs, const FairDbValidityRec * vrec) virtual
Implements FairDbTableRow.
Definition at line 119 of file FairDbValidityRec.cxx.
View newest version in sPHENIX GitHub at line 119 of file FairDbValidityRec.cxx
References ValRange::AsString(), FairDbResultSet::CurRowNum(), fAggregateNo, fCreationDate, fDbNo, fInsertDate, fIsGap, fSeqNo, fTableProxy, fTask, fValRange, FairDbResultSet::GetDbNo(), FairDbResultSet::GetTableProxy(), and start().
Int_t FairDbValidityRec::GetAggregateNo () const inline virtual
Reimplemented from FairDbTableRow.
Definition at line 42 of file FairDbValidityRec.h.
View newest version in sPHENIX GitHub at line 42 of file FairDbValidityRec.h
References fAggregateNo.
Referenced by FairDbCache::Adopt(), ClassImp(), FairDbValidityRecBuilder::FairDbValidityRecBuilder(), FairDbConfigSet::Fill(), operator<<(), FairDbConfigStream::operator<<(), FairDbTableProxy::QueryOverlayCreationDate(), FairDbCache::Search(), and FairDbConfigStream::Write().
ValTimeStamp FairDbValidityRec::GetCreationDate () const inline
Definition at line 43 of file FairDbValidityRec.h.
View newest version in sPHENIX GitHub at line 43 of file FairDbValidityRec.h
References fCreationDate.
Referenced by ClassImp(), FairDbResultAgg::CreateKey(), FairDbResultNonAgg::CreateKey(), FairDbValidityRecBuilder::GetL2CacheName(), GetL2CacheName(), FairDbResultNonAgg::Satisfies(), and FairDbLogEntry::Write().
UInt_t FairDbValidityRec::GetDbNo () const inline
Definition at line 44 of file FairDbValidityRec.h.
View newest version in sPHENIX GitHub at line 44 of file FairDbValidityRec.h
References fDbNo.
Referenced by FairDbSqlValPacket::FairDbSqlValPacket(), operator<<(), and FairDbTableProxy::Query().
ValTimeStamp FairDbValidityRec::GetInsertDate () const inline
Definition at line 45 of file FairDbValidityRec.h.
View newest version in sPHENIX GitHub at line 45 of file FairDbValidityRec.h
References fInsertDate.
std::string FairDbValidityRec::GetL2CacheName () const
Definition at line 149 of file FairDbValidityRec.cxx.
View newest version in sPHENIX GitHub at line 149 of file FairDbValidityRec.cxx
References GetCreationDate(), and GetSeqNo().
Referenced by FairDbValidityRecBuilder::GetL2CacheName(), and FairDbTableProxy::Query().
std::string FairDbValidityRec::GetL2CacheName (UInt_t seqLo, UInt_t seqHi, ValTimeStamp ts) static
Definition at line 157 of file FairDbValidityRec.cxx.
View newest version in sPHENIX GitHub at line 157 of file FairDbValidityRec.cxx
References ValTimeStamp::AsString().
UInt_t FairDbValidityRec::GetSeqNo () const inline
Definition at line 48 of file FairDbValidityRec.h.
View newest version in sPHENIX GitHub at line 48 of file FairDbValidityRec.h
References fSeqNo.
Referenced by FairDbResult::BuildLookUpTable(), ClassImp(), FairDbResultAgg::CreateKey(), FairDbResultNonAgg::CreateKey(), FairDbSqlValPacket::FairDbSqlValPacket(), FairDbValidityRecBuilder::GetL2CacheName(), GetL2CacheName(), FairDbValRecSet::GetTableRowBySeqNo(), operator<<(), FairDbTableProxy::Query(), FairDbTableProxy::RestoreFromL2Cache(), and FairDbResultNonAgg::Satisfies().
const FairDbTableProxy* FairDbValidityRec::GetTableProxy () const inline
Definition at line 49 of file FairDbValidityRec.h.
View newest version in sPHENIX GitHub at line 49 of file FairDbValidityRec.h
References fTableProxy.
Referenced by FairDbSqlValPacket::FairDbSqlValPacket(), FairDbTableProxy::Query(), and FairDbConfigStream::Write().
FairDb::Task FairDbValidityRec::GetTask () const inline
Definition at line 46 of file FairDbValidityRec.h.
View newest version in sPHENIX GitHub at line 46 of file FairDbValidityRec.h
References fTask.
Referenced by FairDbLogEntry::Fill(), HasExpired(), FairDbTableProxy::QueryOverlayCreationDate(), and FairDbLogEntry::Write().
const ValRange& FairDbValidityRec::GetValRange () const inline
Definition at line 50 of file FairDbValidityRec.h.
View newest version in sPHENIX GitHub at line 50 of file FairDbValidityRec.h
References fValRange.
Referenced by ClassImp(), FairDbValidityRecBuilder::FairDbValidityRecBuilder(), FairDbLogEntry::Fill(), HasExpired(), operator<<(), FairDbTableProxy::QueryOverlayCreationDate(), Trim(), and FairDbLogEntry::Write().
Bool_t FairDbValidityRec::HasExpired (const FairDbValidityRec & other) const
Definition at line 175 of file FairDbValidityRec.cxx.
View newest version in sPHENIX GitHub at line 175 of file FairDbValidityRec.cxx
References fTask, fValRange, ValRange::GetDetectorMask(), ValRange::GetSimMask(), GetTask(), ValRange::GetTimeEnd(), ValRange::GetTimeStart(), and GetValRange().
Referenced by FairDbResult::Satisfies().
Bool_t FairDbValidityRec::HasExpired (const ValContext & vc, const FairDb::Task & task) const
Definition at line 191 of file FairDbValidityRec.cxx.
View newest version in sPHENIX GitHub at line 191 of file FairDbValidityRec.cxx
References ValContext::GetDetector(), ValRange::GetDetectorMask(), ValContext::GetSimFlag(), ValRange::GetSimMask(), GetTask(), ValRange::GetTimeEnd(), ValContext::GetTimeStamp(), ValRange::GetTimeStart(), and GetValRange().
Bool_t FairDbValidityRec::IsCompatible (const ValContext & vc, const FairDb::Task & task) const
Definition at line 210 of file FairDbValidityRec.cxx.
View newest version in sPHENIX GitHub at line 210 of file FairDbValidityRec.cxx
References ValContext::AsString(), ValRange::AsString(), fTask, fValRange, and ValRange::IsCompatible().
Referenced by FairDbResult::Satisfies().
Bool_t FairDbValidityRec::IsGap () const inline
Definition at line 56 of file FairDbValidityRec.h.
View newest version in sPHENIX GitHub at line 56 of file FairDbValidityRec.h
References fIsGap.
Referenced by ClassImp(), FairDbValidityRecBuilder::GetL2CacheName(), operator<<(), FairDbTableProxy::Query(), FairDbResultAgg::Streamer(), and Trim().
void FairDbValidityRec::SetAggregateNo (Int_t aggNo) inline
Definition at line 63 of file FairDbValidityRec.h.
View newest version in sPHENIX GitHub at line 63 of file FairDbValidityRec.h
References fAggregateNo.
Referenced by FairDbConfigStream::Write().
void FairDbValidityRec::SetDbNo (Int_t dbNo) inline
Definition at line 64 of file FairDbValidityRec.h.
View newest version in sPHENIX GitHub at line 64 of file FairDbValidityRec.h
References fDbNo.
Referenced by ClassImp(), and FairDbConfigStream::FairDbConfigStream().
void FairDbValidityRec::SetTableProxy (const FairDbTableProxy * tp) inline
Definition at line 65 of file FairDbValidityRec.h.
View newest version in sPHENIX GitHub at line 65 of file FairDbValidityRec.h
References fTableProxy.
Referenced by FairDbConfigStream::FairDbConfigStream().
void FairDbValidityRec::SetTimeWindow (const ValTimeStamp & start, const ValTimeStamp & end)
Definition at line 224 of file FairDbValidityRec.cxx.
View newest version in sPHENIX GitHub at line 224 of file FairDbValidityRec.cxx
References fValRange, ValRange::GetDataSource(), ValRange::GetDetectorMask(), ValRange::GetSimMask(), and start().
Referenced by AndTimeWindow(), and Trim().
void FairDbValidityRec::SetValRange (const ValRange & range) inline
Definition at line 68 of file FairDbValidityRec.h.
View newest version in sPHENIX GitHub at line 68 of file FairDbValidityRec.h
References fValRange.
Referenced by ClassImp(), and FairDbConfigStream::FairDbConfigStream().
void FairDbValidityRec::Store (FairDbOutRowStream & ors, const FairDbValidityRec * vrec) const virtual
Reimplemented from FairDbTableRow.
Definition at line 237 of file FairDbValidityRec.cxx.
View newest version in sPHENIX GitHub at line 237 of file FairDbValidityRec.cxx
References fAggregateNo, fCreationDate, fInsertDate, fSeqNo, fTask, fValRange, ValRange::GetDetectorMask(), ValRange::GetSimMask(), ValRange::GetTimeEnd(), and ValRange::GetTimeStart().
Referenced by FairDbSqlValPacket::Recreate().
void FairDbValidityRec::Streamer (FairDbBinaryFile & file)
Definition at line 252 of file FairDbValidityRec.cxx.
View newest version in sPHENIX GitHub at line 252 of file FairDbValidityRec.cxx
References fAggregateNo, fCreationDate, fDbNo, fInsertDate, fIsGap, fSeqNo, fTableProxy, fTask, fValRange, FairDbBinaryFile::IsReading(), and FairDbBinaryFile::IsWriting().
Referenced by FairDbResult::Streamer().
void FairDbValidityRec::Trim (const ValTimeStamp & queryTime, const FairDbValidityRec & other)
Definition at line 278 of file FairDbValidityRec.cxx.
View newest version in sPHENIX GitHub at line 278 of file FairDbValidityRec.cxx
References fAggregateNo, fValRange, ValRange::GetTimeEnd(), ValRange::GetTimeStart(), GetValRange(), IsGap(), SetTimeWindow(), and start().
Referenced by ClassImp().
Member Data Documentation
Int_t FairDbValidityRec::fAggregateNo private
Definition at line 80 of file FairDbValidityRec.h.
View newest version in sPHENIX GitHub at line 80 of file FairDbValidityRec.h
Referenced by Fill(), GetAggregateNo(), SetAggregateNo(), Store(), Streamer(), and Trim().
ValTimeStamp FairDbValidityRec::fCreationDate private
Definition at line 81 of file FairDbValidityRec.h.
View newest version in sPHENIX GitHub at line 81 of file FairDbValidityRec.h
Referenced by Fill(), GetCreationDate(), Store(), and Streamer().
Int_t FairDbValidityRec::fDbNo private
Definition at line 82 of file FairDbValidityRec.h.
View newest version in sPHENIX GitHub at line 82 of file FairDbValidityRec.h
Referenced by Fill(), GetDbNo(), SetDbNo(), and Streamer().
ValTimeStamp FairDbValidityRec::fInsertDate private
Definition at line 83 of file FairDbValidityRec.h.
View newest version in sPHENIX GitHub at line 83 of file FairDbValidityRec.h
Referenced by Fill(), GetInsertDate(), Store(), and Streamer().
Bool_t FairDbValidityRec::fIsGap private
Definition at line 84 of file FairDbValidityRec.h.
View newest version in sPHENIX GitHub at line 84 of file FairDbValidityRec.h
Referenced by Fill(), IsGap(), and Streamer().
Int_t FairDbValidityRec::fSeqNo private
Definition at line 86 of file FairDbValidityRec.h.
View newest version in sPHENIX GitHub at line 86 of file FairDbValidityRec.h
Referenced by Fill(), GetSeqNo(), Store(), and Streamer().
const FairDbTableProxy* FairDbValidityRec::fTableProxy private
Definition at line 87 of file FairDbValidityRec.h.
View newest version in sPHENIX GitHub at line 87 of file FairDbValidityRec.h
Referenced by Fill(), GetTableProxy(), SetTableProxy(), and Streamer().
FairDb::Task FairDbValidityRec::fTask private
Definition at line 85 of file FairDbValidityRec.h.
View newest version in sPHENIX GitHub at line 85 of file FairDbValidityRec.h
Referenced by Fill(), GetTask(), HasExpired(), IsCompatible(), Store(), and Streamer().
ValRange FairDbValidityRec::fValRange private
Definition at line 88 of file FairDbValidityRec.h.
View newest version in sPHENIX GitHub at line 88 of file FairDbValidityRec.h
Referenced by AndTimeWindow(), Fill(), GetValRange(), HasExpired(), IsCompatible(), SetTimeWindow(), SetValRange(), Store(), Streamer(), and Trim().
The documentation for this class was generated from the following files:
EicRoot/blob/master/dbase/dbInterface/FairDbValidityRec.h
EicRoot/blob/master/dbase/dbInterface/FairDbValidityRec.cxx