EIC Software: CbmRichProjectionProducerBase Class Reference
CbmRichProjectionProducerBase Class Reference abstract
Base class for STS track projections onto the photodetector plane.
#include <EicRoot/blob/master/rich/tracks/CbmRichProjectionProducerBase.h>
Public Member Functions
CbmRichProjectionProducerBase ()
CbmRichProjectionProducerBase (int flag)
virtual ~CbmRichProjectionProducerBase ()
Destructor.
virtual void SetParContainers ()
Initialization of parameter container.
virtual void Init ()
Initialization in case one needs to initialize some TCloneArrays.
virtual void DoProjection (TClonesArray *richProj)=0
void SetZFlag (int flag)
Set flag whether to use point in imaginary plane (zflag=1) or mirror point (zflag=2) for extrapolation.
Protected Attributes
int fZflag
Private Member Functions
CbmRichProjectionProducerBase (const CbmRichProjectionProducerBase &)
Copy constructor.
CbmRichProjectionProducerBase & operator= (const CbmRichProjectionProducerBase &)
Assignment operator.
Detailed Description
Base class for STS track projections onto the photodetector plane.
Author
Semen Lebedev
Date
2012
Definition at line 23 of file CbmRichProjectionProducerBase.h.
View newest version in sPHENIX GitHub at line 23 of file CbmRichProjectionProducerBase.h
Constructor & Destructor Documentation
CbmRichProjectionProducerBase::CbmRichProjectionProducerBase () inline
brief Default constructor.
Definition at line 29 of file CbmRichProjectionProducerBase.h.
View newest version in sPHENIX GitHub at line 29 of file CbmRichProjectionProducerBase.h
CbmRichProjectionProducerBase::CbmRichProjectionProducerBase (int flag) inline
brief Standard constructor.
Definition at line 34 of file CbmRichProjectionProducerBase.h.
View newest version in sPHENIX GitHub at line 34 of file CbmRichProjectionProducerBase.h
virtual CbmRichProjectionProducerBase::~CbmRichProjectionProducerBase () inline virtual
Destructor.
Definition at line 39 of file CbmRichProjectionProducerBase.h.
View newest version in sPHENIX GitHub at line 39 of file CbmRichProjectionProducerBase.h
CbmRichProjectionProducerBase::CbmRichProjectionProducerBase (const CbmRichProjectionProducerBase &) private
Copy constructor.
Member Function Documentation
virtual void CbmRichProjectionProducerBase::DoProjection (TClonesArray * richProj) pure virtual
Creates track projections onto the photodetector plane.
Parameters
[out] richProj Array of track projections onto the photodetector plane.
Implemented in CbmRichProjectionProducer, and CbmRichProtProjectionProducer.
Referenced by CbmRichReconstruction::RunProjection().
virtual void CbmRichProjectionProducerBase::Init (void) inline virtual
Initialization in case one needs to initialize some TCloneArrays.
Reimplemented in CbmRichProjectionProducer, and CbmRichProtProjectionProducer.
Definition at line 49 of file CbmRichProjectionProducerBase.h.
View newest version in sPHENIX GitHub at line 49 of file CbmRichProjectionProducerBase.h
Referenced by CbmRichReconstruction::InitProjection().
CbmRichProjectionProducerBase& CbmRichProjectionProducerBase::operator= (const CbmRichProjectionProducerBase &) private
Assignment operator.
virtual void CbmRichProjectionProducerBase::SetParContainers () inline virtual
Initialization of parameter container.
Reimplemented in CbmRichProjectionProducer, and CbmRichProtProjectionProducer.
Definition at line 44 of file CbmRichProjectionProducerBase.h.
View newest version in sPHENIX GitHub at line 44 of file CbmRichProjectionProducerBase.h
Referenced by CbmRichReconstruction::SetParContainers().
void CbmRichProjectionProducerBase::SetZFlag (int flag) inline
Set flag whether to use point in imaginary plane (zflag=1) or mirror point (zflag=2) for extrapolation.
Parameters
[in] flag Flag.
Definition at line 63 of file CbmRichProjectionProducerBase.h.
View newest version in sPHENIX GitHub at line 63 of file CbmRichProjectionProducerBase.h
References fZflag.
Referenced by CbmRichReconstruction::InitExtrapolation().
Member Data Documentation
int CbmRichProjectionProducerBase::fZflag protected
Definition at line 66 of file CbmRichProjectionProducerBase.h.
View newest version in sPHENIX GitHub at line 66 of file CbmRichProjectionProducerBase.h
Referenced by CbmRichProjectionProducer::DoProjection(), CbmRichProjectionProducer::Init(), and SetZFlag().
The documentation for this class was generated from the following file:
EicRoot/blob/master/rich/tracks/CbmRichProjectionProducerBase.h