EIC Software: fun4all_eicmacros/blob/master/common/G4_Tracking_LBL.C File Reference
G4_Tracking_LBL.C File Reference
#include <GlobalVariables.C>
#include <G4_AllSilicon.C>
#include <G4_CEmc_EIC.C>
#include <G4_FEMC_EIC.C>
#include <G4_FHCAL.C>
#include <g4trackfastsim/PHG4TrackFastSim.h>
#include <trackreco/PHRaveVertexing.h>
#include <g4trackfastsim/PHG4TrackFastSimEval.h>
#include <fun4all/Fun4AllServer.h>
#include <vector>
Namespaces
namespace Enable
namespace G4TRACKING
Macros
#define MACRO_G4TRACKINGLBL_C
Functions
void TrackingInit ()
void Tracking_Reco ()
void Tracking_Eval (const std::string &outputfile)
Macro Definition Documentation
#define MACRO_G4TRACKINGLBL_C
Definition at line 2 of file G4_Tracking_LBL.C.
View newest version in sPHENIX GitHub at line 2 of file G4_Tracking_LBL.C
Function Documentation
void Tracking_Eval (const std::string & outputfile)
Definition at line 159 of file G4_Tracking_LBL.C.
View newest version in sPHENIX GitHub at line 159 of file G4_Tracking_LBL.C
References Fun4AllServer::instance(), max, Fun4AllServer::registerSubsystem(), PHG4TrackFastSimEval::set_filename(), PHG4TrackFastSimEval::set_trackmapname(), Enable::TRACKING_VERBOSITY, TRACKING::TrackNodeName, and Enable::VERBOSITY.
void Tracking_Reco ()
Definition at line 45 of file G4_Tracking_LBL.C.
View newest version in sPHENIX GitHub at line 45 of file G4_Tracking_LBL.C
References PHG4TrackFastSim::add_phg4hits(), PHG4TrackFastSim::add_state_name(), Enable::ALLSILICON, Enable::CEMC, PHG4TrackFastSim::Cylinder, G4TRACKING::DISPLACED_VERTEX, Acts::UnitConstants::e, PHG4TrackFastSim::enable_vertexing(), Enable::FEMC, Enable::FHCAL, Fun4AllServer::instance(), max, G4TRACKING::PROJECTION_CEMC, G4TRACKING::PROJECTION_FEMC, G4TRACKING::PROJECTION_FHCAL, Fun4AllServer::registerSubsystem(), PHG4TrackFastSim::set_sub_top_node_name(), PHG4TrackFastSim::set_trackmap_out_name(), PHG4TrackFastSim::set_use_vertex_in_fitting(), PHG4TrackFastSim::set_vertex_xy_resolution(), PHG4TrackFastSim::set_vertex_z_resolution(), Enable::TRACKING_VERBOSITY, TRACKING::TrackNodeName, Enable::VERBOSITY, and PHG4TrackFastSim::Vertical_Plane.
void TrackingInit ()
Definition at line 40 of file G4_Tracking_LBL.C.
View newest version in sPHENIX GitHub at line 40 of file G4_Tracking_LBL.C
References TRACKING::TrackNodeName.