EIC Software: ValContext Class Reference
ValContext Class Reference
#include <EicRoot/blob/master/dbase/dbValidation/ValContext.h>
Public Member Functions
ValContext ()
ValContext (const Detector::Detector_t &detector, const SimFlag::SimFlag_t mcflag, const ValTimeStamp &time)
virtual ~ValContext ()
const char * AsString (Option_t *option="") const
Detector::Detector_t GetDetector () const
SimFlag::SimFlag_t GetSimFlag () const
ValTimeStamp GetTimeStamp () const
Bool_t IsNull () const
Bool_t IsValid () const
Return opposite of IsNull()
void Print (Option_t *option="") const
Protected Attributes
Detector::Detector_t fDetector
SimFlag::SimFlag_t fSimFlag
ValTimeStamp fTimeStamp
Friends
Bool_t operator< (const ValContext &lhs, const ValContext &rhs)
Bool_t operator== (const ValContext &lhs, const ValContext &rhs)
Bool_t operator!= (const ValContext &lhs, const ValContext &rhs)
Bool_t operator<= (const ValContext &lhs, const ValContext &rhs)
Bool_t operator> (const ValContext &lhs, const ValContext &rhs)
Bool_t operator>= (const ValContext &lhs, const ValContext &rhs)
Detailed Description
Definition at line 17 of file ValContext.h.
View newest version in sPHENIX GitHub at line 17 of file ValContext.h
Constructor & Destructor Documentation
ValContext::ValContext ()
ValContext::ValContext (const Detector::Detector_t & detector, const SimFlag::SimFlag_t mcflag, const ValTimeStamp & time)
Definition at line 33 of file ValContext.cxx.
View newest version in sPHENIX GitHub at line 33 of file ValContext.cxx
ValContext::~ValContext () virtual
Definition at line 15 of file ValContext.cxx.
View newest version in sPHENIX GitHub at line 15 of file ValContext.cxx
Member Function Documentation
const char * ValContext::AsString (Option_t * option = "") const
Return a formatted string of the contents of this object User should copy result because it points to a statically allocated string.
Definition at line 45 of file ValContext.cxx.
View newest version in sPHENIX GitHub at line 45 of file ValContext.cxx
References SimFlag::AsString(), Detector::AsString(), ValTimeStamp::AsString(), fTimeStamp, GetDetector(), and GetSimFlag().
Referenced by FairDbValidityRec::IsCompatible(), operator<<(), Print(), and ValValidate::TestContext().
Detector::Detector_t ValContext::GetDetector () const inline
Definition at line 33 of file ValContext.h.
View newest version in sPHENIX GitHub at line 33 of file ValContext.h
Referenced by AsString(), FairDbProxy::FindTimeBoundaries(), FairDbValidityRec::HasExpired(), ValRange::IsCompatible(), FairDbValidityRecBuilder::MakeGapRec(), FairDbProxy::QueryValidity(), and FairDbCache::Search().
SimFlag::SimFlag_t ValContext::GetSimFlag () const inline
Definition at line 34 of file ValContext.h.
View newest version in sPHENIX GitHub at line 34 of file ValContext.h
Referenced by AsString(), FairDbProxy::FindTimeBoundaries(), FairDbValidityRec::HasExpired(), ValRange::IsCompatible(), FairDbValidityRecBuilder::MakeGapRec(), FairDbProxy::QueryValidity(), and FairDbCache::Search().
ValTimeStamp ValContext::GetTimeStamp () const inline
Definition at line 35 of file ValContext.h.
View newest version in sPHENIX GitHub at line 35 of file ValContext.h
Referenced by FairDbProxy::FindTimeBoundaries(), FairDbValidityRec::HasExpired(), ValRange::IsCompatible(), FairDbValidityRecBuilder::MakeGapRec(), FairDbProxy::QueryValidity(), and FairDbCache::Search().
Bool_t ValContext::IsNull () const
Return true if this was initialized by default ctor we can only test experiment type and simflag
Definition at line 78 of file ValContext.cxx.
View newest version in sPHENIX GitHub at line 78 of file ValContext.cxx
References fDetector, fSimFlag, SimFlag::kUnknown, and Detector::kUnknown.
Bool_t ValContext::IsValid () const inline
Return opposite of IsNull()
Definition at line 41 of file ValContext.h.
View newest version in sPHENIX GitHub at line 41 of file ValContext.h
void ValContext::Print (Option_t * option = "") const
Definition at line 72 of file ValContext.cxx.
View newest version in sPHENIX GitHub at line 72 of file ValContext.cxx
References AsString(), and printf().
Friends And Related Function Documentation
Bool_t operator!= (const ValContext & lhs, const ValContext & rhs) friend
Definition at line 90 of file ValContext.h.
View newest version in sPHENIX GitHub at line 90 of file ValContext.h
Bool_t operator< (const ValContext & lhs, const ValContext & rhs) friend
Definition at line 66 of file ValContext.h.
View newest version in sPHENIX GitHub at line 66 of file ValContext.h
Bool_t operator<= (const ValContext & lhs, const ValContext & rhs) friend
Definition at line 99 of file ValContext.h.
View newest version in sPHENIX GitHub at line 99 of file ValContext.h
Bool_t operator== (const ValContext & lhs, const ValContext & rhs) friend
Definition at line 81 of file ValContext.h.
View newest version in sPHENIX GitHub at line 81 of file ValContext.h
Bool_t operator> (const ValContext & lhs, const ValContext & rhs) friend
Definition at line 104 of file ValContext.h.
View newest version in sPHENIX GitHub at line 104 of file ValContext.h
Bool_t operator>= (const ValContext & lhs, const ValContext & rhs) friend
Definition at line 109 of file ValContext.h.
View newest version in sPHENIX GitHub at line 109 of file ValContext.h
Member Data Documentation
Detector::Detector_t ValContext::fDetector protected
Definition at line 54 of file ValContext.h.
View newest version in sPHENIX GitHub at line 54 of file ValContext.h
Referenced by IsNull(), operator!=(), operator<(), and operator==().
SimFlag::SimFlag_t ValContext::fSimFlag protected
Definition at line 55 of file ValContext.h.
View newest version in sPHENIX GitHub at line 55 of file ValContext.h
Referenced by IsNull(), operator!=(), operator<(), and operator==().
ValTimeStamp ValContext::fTimeStamp protected
Definition at line 56 of file ValContext.h.
View newest version in sPHENIX GitHub at line 56 of file ValContext.h
Referenced by AsString(), operator!=(), operator<(), and operator==().
The documentation for this class was generated from the following files:
EicRoot/blob/master/dbase/dbValidation/ValContext.h
EicRoot/blob/master/dbase/dbValidation/ValContext.cxx