EIC Software: GFWirepointHitPolicy Class Reference
GFWirepointHitPolicy Class Reference
Genfit
policy class for hits in wire detectors (STT and DCH) which can measure the coordinate along the wire
#include <EicRoot/blob/master/genfit/GFWirepointHitPolicy.h>
Public Member Functions
GFWirepointHitPolicy ()
const GFDetPlane & detPlane (GFAbsRecoHit *, GFAbsTrackRep *)
Get detector plane.
TMatrixT< double > hitCoord (GFAbsRecoHit *, const GFDetPlane &)
Hit coordinates in detector plane.
TMatrixT< double > hitCov (GFAbsRecoHit *, const GFDetPlane &)
Hit covariances in detector plane.
void checkPlane (GFAbsRecoHit *, const GFDetPlane &)
Check if the detector plane is valid.
virtual ~GFWirepointHitPolicy ()
double getMaxDistance ()
void setMaxDistance (double d)
const std::string & getName ()
ClassDef (GFWirepointHitPolicy, 1)
Private Attributes
GFDetPlane fDetPlane
double fMaxdistance
Static Private Attributes
static const std::string fPolicyName = "GFWirepointHitPolicy"
Detailed Description
policy class for hits in wire detectors (STT and DCH) which can measure the coordinate along the wire
Author
Christian Höppner (Technische Universität München, original author)
Lia Lavezzi (INFN Pavia, original author)
Sebastian Neubert (Technische Universität München, original author) This policy is not valid for any kind of plane orientation choice: to use it you MUST choose a plane described by u and v axes with v coincident with the wire (and u orthogonal to it, obviously). The hit will be described by 8 coordinates: w_x1, w_y1, w_z1, w_x2, w_y2, w_z2, rdrift, zreco where w_ji (with j = x, y, z and i = 1, 2) are the wire extremities coordinates; rdrift = distance from the wire (u coordinate in the plane) and zreco = coordinate along the wire (in the plane reference frame, v coordinate).
Definition at line 52 of file GFWirepointHitPolicy.h.
View newest version in sPHENIX GitHub at line 52 of file GFWirepointHitPolicy.h
Constructor & Destructor Documentation
GFWirepointHitPolicy::GFWirepointHitPolicy ()
Definition at line 36 of file GFWirepointHitPolicy.cxx.
View newest version in sPHENIX GitHub at line 36 of file GFWirepointHitPolicy.cxx
virtual GFWirepointHitPolicy::~GFWirepointHitPolicy () inline virtual
Definition at line 75 of file GFWirepointHitPolicy.h.
View newest version in sPHENIX GitHub at line 75 of file GFWirepointHitPolicy.h
Member Function Documentation
void GFWirepointHitPolicy::checkPlane (GFAbsRecoHit * hit, const GFDetPlane & plane)
Check if the detector plane is valid.
Definition at line 71 of file GFWirepointHitPolicy.cxx.
View newest version in sPHENIX GitHub at line 71 of file GFWirepointHitPolicy.cxx
References Acts::UnitConstants::e, GFAbsRecoHit::getRawHitCoord(), and GFDetPlane::getV().
Referenced by hitCoord(), and hitCov().
GFWirepointHitPolicy::ClassDef (GFWirepointHitPolicy , 1)
const GFDetPlane & GFWirepointHitPolicy::detPlane (GFAbsRecoHit * hit, GFAbsTrackRep * rep)
Get detector plane.
Definition at line 95 of file GFWirepointHitPolicy.cxx.
View newest version in sPHENIX GitHub at line 95 of file GFWirepointHitPolicy.cxx
References GFDetPlane::dist(), Acts::UnitConstants::e, GFAbsTrackRep::extrapolateToLine(), fDetPlane, fMaxdistance, GFAbsRecoHit::getRawHitCoord(), and x.
double GFWirepointHitPolicy::getMaxDistance () inline
Definition at line 77 of file GFWirepointHitPolicy.h.
View newest version in sPHENIX GitHub at line 77 of file GFWirepointHitPolicy.h
References fMaxdistance.
const std::string& GFWirepointHitPolicy::getName () inline
Definition at line 80 of file GFWirepointHitPolicy.h.
View newest version in sPHENIX GitHub at line 80 of file GFWirepointHitPolicy.h
References fPolicyName.
TMatrixT< double > GFWirepointHitPolicy::hitCoord (GFAbsRecoHit * hit, const GFDetPlane & plane)
Hit coordinates in detector plane.
Definition at line 39 of file GFWirepointHitPolicy.cxx.
View newest version in sPHENIX GitHub at line 39 of file GFWirepointHitPolicy.cxx
References checkPlane(), and GFAbsRecoHit::getRawHitCoord().
TMatrixT< double > GFWirepointHitPolicy::hitCov (GFAbsRecoHit * hit, const GFDetPlane & plane)
Hit covariances in detector plane.
Definition at line 54 of file GFWirepointHitPolicy.cxx.
View newest version in sPHENIX GitHub at line 54 of file GFWirepointHitPolicy.cxx
References checkPlane(), and GFAbsRecoHit::getRawHitCov().
void GFWirepointHitPolicy::setMaxDistance (double d) inline
Definition at line 78 of file GFWirepointHitPolicy.h.
View newest version in sPHENIX GitHub at line 78 of file GFWirepointHitPolicy.h
References d, and fMaxdistance.
Member Data Documentation
GFDetPlane GFWirepointHitPolicy::fDetPlane private
Definition at line 85 of file GFWirepointHitPolicy.h.
View newest version in sPHENIX GitHub at line 85 of file GFWirepointHitPolicy.h
Referenced by detPlane().
double GFWirepointHitPolicy::fMaxdistance private
Definition at line 86 of file GFWirepointHitPolicy.h.
View newest version in sPHENIX GitHub at line 86 of file GFWirepointHitPolicy.h
Referenced by detPlane(), getMaxDistance(), and setMaxDistance().
const std::string GFWirepointHitPolicy::fPolicyName = "GFWirepointHitPolicy" static private
Definition at line 82 of file GFWirepointHitPolicy.h.
View newest version in sPHENIX GitHub at line 82 of file GFWirepointHitPolicy.h
Referenced by getName().
The documentation for this class was generated from the following files:
EicRoot/blob/master/genfit/GFWirepointHitPolicy.h
EicRoot/blob/master/genfit/GFWirepointHitPolicy.cxx