EIC Software: BeastMagneticField/blob/master/scripts/viewer.C File Reference
viewer.C File Reference
Functions
void viewer (const char *fname, double minR=0.0, double maxR=400.0, double minZ=-450.0, double maxZ=450.0, unsigned cvX=1200, unsigned cvY=1200, bool plotBz=true, bool plotBr=false, bool plotBm=true)
Function Documentation
void viewer (const char * fname, double minR = 0.0, double maxR = 400.0, double minZ = -450.0, double maxZ = 450.0, unsigned cvX = 1200, unsigned cvY = 1200, bool plotBz = true, bool plotBr = false, bool plotBm = true)
Definition at line 2 of file viewer.C.
View newest version in sPHENIX GitHub at line 2 of file viewer.C
References ir(), plot(), and printf().
Referenced by EicCompositeShape::PaintComposite().