EIC Software: EicRoot/blob/master/eic/cad/EicStlFactory.cxx File Reference
EicStlFactory.cxx File Reference
#include <assert.h>
#include <iostream>
#include <asm/types.h>
#include <TGeoManager.h>
#include <TGeoMedium.h>
#include <TRotation.h>
#include <TMath.h>
#include <TGeoVolume.h>
#include <TGeoArb8.h>
#include <TGeoMatrix.h>
#include <FairLogger.h>
#include <EicCadFile.h>
#include <EicStlFactory.h>
Macros
#define _BINARY_STL_HEADER_SIZE_ 80
Functions
TGeoVolume * CreateTetrahedron (TVector3 &p1, TVector3 &p2, TVector3 &p3, TVector3 &p4, char name[], TGeoVolume *fMother, const TGeoMedium *medium, TVector3 shift)
static TVector3 swapXYfun (TVector3 src)
Macro Definition Documentation
#define _BINARY_STL_HEADER_SIZE_ 80
Definition at line 15 of file EicStlFactory.cxx.
View newest version in sPHENIX GitHub at line 15 of file EicStlFactory.cxx
Referenced by EicStlFactory::EicStlFactory().
Function Documentation
TGeoVolume* CreateTetrahedron (TVector3 & p1, TVector3 & p2, TVector3 & p3, TVector3 & p4, char name[], TGeoVolume * fMother, const TGeoMedium * medium, TVector3 shift)
Definition at line 373 of file EicStlFactory.cxx.
View newest version in sPHENIX GitHub at line 373 of file EicStlFactory.cxx
References data, rr, and vtx().
Referenced by EicStlFactory::_ConstructGeometry(), and EicStlFactory::CreateRootFile().
static TVector3 swapXYfun (TVector3 src) static
Definition at line 457 of file EicStlFactory.cxx.
View newest version in sPHENIX GitHub at line 457 of file EicStlFactory.cxx
Referenced by EicStlFactory::_ConstructGeometry().