EIC Software: PEPSI/blob/master/gmc_random.f File Reference
gmc_random.f File Reference
Functions/Subroutines
subroutine rndmq (nseed1, nseed2, nseq, chopt)
real function rndm (dummy)
integer function irndm (dummy)
subroutine nran (r, n)
subroutine rannor (a, b)
real function ranf (dummy)
real function rlu (idummy)
subroutine ranums (r, n)
Function/Subroutine Documentation
integer function irndm (real dummy)
Definition at line 87 of file gmc_random.f.
View newest version in sPHENIX GitHub at line 87 of file gmc_random.f
References Acts::ConeBounds::r().
Referenced by rndmq().
subroutine nran (real, dimension(n) r, integer n)
Definition at line 105 of file gmc_random.f.
View newest version in sPHENIX GitHub at line 105 of file gmc_random.f
References n, and Acts::ConeBounds::r().
Referenced by rannor(), and rndmq().
real function ranf (real dummy)
Definition at line 138 of file gmc_random.f.
View newest version in sPHENIX GitHub at line 138 of file gmc_random.f
References Acts::ConeBounds::r().
Referenced by rndmq().
subroutine rannor (real a, real b)
Definition at line 120 of file gmc_random.f.
View newest version in sPHENIX GitHub at line 120 of file gmc_random.f
References nran(), and Acts::ConeBounds::r().
Referenced by rndmq().
subroutine ranums (real, dimension(n) r, integer n)
Definition at line 171 of file gmc_random.f.
View newest version in sPHENIX GitHub at line 171 of file gmc_random.f
References n, and Acts::ConeBounds::r().
Referenced by rndmq().
real function rlu (integer idummy)
Definition at line 154 of file gmc_random.f.
View newest version in sPHENIX GitHub at line 154 of file gmc_random.f
References Acts::ConeBounds::r(), and rlu().
real function rndm (real dummy)
Definition at line 73 of file gmc_random.f.
View newest version in sPHENIX GitHub at line 73 of file gmc_random.f
References Acts::ConeBounds::r().
Referenced by rndmq().
subroutine rndmq (integer nseed1, integer nseed2, integer nseq, character*(*) chopt)
Definition at line 26 of file gmc_random.f.
View newest version in sPHENIX GitHub at line 26 of file gmc_random.f
References irndm(), nran(), ranf(), rannor(), ranums(), rlu(), rndm(), and PHTimer::stop().
Referenced by pepsimainerhic().