EIC Software: fun4all_eicmacros/blob/master/common/G4_AllSi.C File Reference
G4_AllSi.C File Reference
#include <g4lblvtx/AllSiliconTrackerSubsystem.h>
#include <g4trackfastsim/PHG4TrackFastSim.h>
#include <g4lblvtx/SimpleNtuple.h>
#include <g4main/PHG4Reco.h>
#include <string>
Macros
#define MACRO_G4ALLSI_C
Functions
void load_AllSi_geom (PHG4Reco *g4Reco, int det_ver=3)
void add_AllSi_to_kalman (PHG4TrackFastSim *kalman, double pixel_size=10., int det_ver=3)
void add_AllSi_hits (SimpleNtuple *hits, int det_ver=3)
Macro Definition Documentation
#define MACRO_G4ALLSI_C
Definition at line 2 of file G4_AllSi.C.
View newest version in sPHENIX GitHub at line 2 of file G4_AllSi.C
Function Documentation
void add_AllSi_hits (SimpleNtuple * hits, int det_ver = 3)
Definition at line 94 of file G4_AllSi.C.
View newest version in sPHENIX GitHub at line 94 of file G4_AllSi.C
References SimpleNtuple::AddNode().
Referenced by Fun4All_G4_FastMom(), Fun4All_G4_FastMom_GEM(), and Fun4All_G4_FastMom_GEM_RICH().
void add_AllSi_to_kalman (PHG4TrackFastSim * kalman, double pixel_size = 10., int det_ver = 3)
Definition at line 45 of file G4_AllSi.C.
View newest version in sPHENIX GitHub at line 45 of file G4_AllSi.C
References PHG4TrackFastSim::add_phg4hits(), PHG4TrackFastSim::Cylinder, and PHG4TrackFastSim::Vertical_Plane.
Referenced by Fun4All_G4_FastMom(), Fun4All_G4_FastMom_GEM(), and Fun4All_G4_FastMom_GEM_RICH().
void load_AllSi_geom (PHG4Reco * g4Reco, int det_ver = 3)
Definition at line 13 of file G4_AllSi.C.
View newest version in sPHENIX GitHub at line 13 of file G4_AllSi.C
References AllSiliconTrackerSubsystem::AddAssemblyVolume(), Pipe(), PipeInit(), PHG4DetectorSubsystem::set_string_param(), PHG4DetectorSubsystem::SetAbsorberActive(), PHG4DetectorSubsystem::SetActive(), and PHG4DetectorSubsystem::SuperDetector().
Referenced by Fun4All_G4_FastMom(), Fun4All_G4_FastMom_GEM(), and Fun4All_G4_FastMom_GEM_RICH().