EIC Software: EicFieldMapDetector Class Reference
EicFieldMapDetector Class Reference
#include <EicRoot/blob/master/eic/base/EicFieldMapDetector.h>
Public Member Functions
EicFieldMapDetector (EicMagneticFieldMap *fmap=0, Bool_t Active=kFALSE)
~EicFieldMapDetector ()
void ConstructGeometry ()
Public Member Functions inherited from EicDetector
EicDetector (const char *Name, const char *geometryName, EicDetectorId dType=qDUMMY, SteppingType stType=qSteppingTypeUndefined, Bool_t Active=kTRUE)
EicDetector ()
void ResetVars ()
~EicDetector ()
virtual void Initialize ()
virtual void FinishRun ()
virtual Bool_t ProcessHits (FairVolume *v=0)
virtual void Register ()
virtual void Print () const
virtual void Reset ()
virtual void BeginEvent ()
void DeclareAllVolumesSensitive ()
int DeclareGeantSensitiveVolume (const char *name, SteppingType stType=qSteppingTypeDefault)
int DeclareGeantSensitiveVolumePrefix (const char *name, SteppingType stType=qSteppingTypeDefault)
bool CheckIfSensitive (std::string name)
ULong64_t GetNodeMultiIndex ()
virtual TClonesArray * GetCollection (Int_t iColl) const
void ResetSteppingVariables ()
virtual void AddMoCaPoint (Int_t trackID, Int_t primaryMotherID, Int_t secondaryMotherID, Int_t detID, ULong64_t multiIndex, TVector3 PosIn, TVector3 PosOut, TVector3 MomIn, TVector3 MomOut, Double_t time, Double_t length, Double_t eLoss, Double_t step)
void EndOfEvent ()
EicDetectorId GetType ()
virtual FairParSet * EicGeoParAllocator (FairContainer *c)
EicDetName * GetDname ()
int createFakeMoCaDatabase (const char *outFileName)
void RequestGeometryInfoPrintout (const char *option=0)
void RequestAttachedFilePrintout (const char *fileName, const char *option=0)
EicEnergyMonitor * AddEnergyMonitorVolume (const char *volumeName, Int_t PDG, char *histogramName, double histogramMin, double histogramMax, unsigned histogramBinNum=1000)
void AddKillerVolume (const char *vname)
Public Member Functions inherited from FairDetector
FairDetector (const char *Name, Bool_t Active, Int_t DetId=0)
FairDetector ()
virtual ~FairDetector ()
virtual void CopyClones (TClonesArray *cl1, TClonesArray *cl2, Int_t offset)
virtual void FinishPrimary ()
virtual void BeginPrimary ()
virtual void PostTrack ()
virtual void PreTrack ()
virtual void FinishEvent ()
virtual void SetSpecialPhysicsCuts ()
void SaveGeoParams ()
Int_t GetDetId ()
Public Member Functions inherited from FairModule
FairModule ()
FairModule (const char *Name, const char *title, Bool_t Active=kFALSE)
virtual ~FairModule ()
virtual void Print (Option_t *option="") const
virtual TString GetGeometryFileName ()
virtual TString GetGeometryFileVer ()
virtual void ConstructOpGeometry ()
virtual void ConstructRootGeometry ()
virtual void ConstructASCIIGeometry ()
virtual void ExpandNode (TGeoNode *Node)
virtual Int_t getVolId (const TString &vname) const
Int_t GetModId ()
void SetVerboseLevel (Int_t level)
Bool_t IsActive ()
void SetModId (Int_t id)
void SetMotherVolume (TString volName)
void ProcessNodes (TList *aList)
virtual void SetParContainers ()
TList * GetListOfGeoPar ()
FairVolume * getFairVolume (FairGeoNode *fNode)
void AddSensitiveVolume (TGeoVolume *v)
void ImportRootMaterials ()
Private Member Functions
ClassDef (EicFieldMapDetector, 2)
magnetic field map
Private Attributes
EicMagneticFieldMap * mMap
Additional Inherited Members
Public Attributes inherited from FairModule
TString fMotherVolumeName
Static Public Attributes inherited from FairModule
static FairVolumeList * vList =0
static Int_t fNbOfVolumes =0
static TRefArray * svList =0
static TArrayI * volNumber =0
Protected Member Functions inherited from EicDetector
virtual void SetGeometryFileName (TString fname, TString geoVer="0")
void AddKillerVolume (TGeoVolume *volume)
bool IsKillerVolume (const char *name)
void CheckEnergyMonitors (const char *name, Int_t trackID, Int_t PDG, bool isPrimary, bool isEntering, bool isExiting, double energy)
Protected Attributes inherited from EicDetector
EicDetName * dname
EicContFact * eicContFact
TClonesArray * fEicMoCaPointCollection
bool mPrintGeometryInfoFlag
TString mPrintGeometryInfoOption
TString mAttachedFilePrintoutRequestName
TString mAttachedFilePrintoutOption
TLorentzVector fPosIn
TLorentzVector fMomIn
Double32_t fTime
Double32_t fLength
Double32_t fELoss
Double32_t fStep
Detailed Description
Definition at line 14 of file EicFieldMapDetector.h.
View newest version in sPHENIX GitHub at line 14 of file EicFieldMapDetector.h
Constructor & Destructor Documentation
EicFieldMapDetector::EicFieldMapDetector (EicMagneticFieldMap * fmap = 0, Bool_t Active = kFALSE)
Definition at line 14 of file EicFieldMapDetector.cxx.
View newest version in sPHENIX GitHub at line 14 of file EicFieldMapDetector.cxx
EicFieldMapDetector::~EicFieldMapDetector () inline
Definition at line 17 of file EicFieldMapDetector.h.
View newest version in sPHENIX GitHub at line 17 of file EicFieldMapDetector.h
Member Function Documentation
EicFieldMapDetector::ClassDef (EicFieldMapDetector , 2) private
magnetic field map
void EicFieldMapDetector::ConstructGeometry () virtual
Create the detector geometry;
Reimplemented from EicDetector.
Definition at line 24 of file EicFieldMapDetector.cxx.
View newest version in sPHENIX GitHub at line 24 of file EicFieldMapDetector.cxx
References EicDetector::AddKillerVolume(), EicMagneticFieldMap::ConstructGeometry(), FairLogger::Fatal(), FairDetector::fLogger, EicMagneticFieldMap::GetFileName(), EicMagneticFieldMap::GetYokeVolume(), FairModule::IsActive(), MESSAGE_ORIGIN, and mMap.
Member Data Documentation
EicMagneticFieldMap* EicFieldMapDetector::mMap private
Definition at line 22 of file EicFieldMapDetector.h.
View newest version in sPHENIX GitHub at line 22 of file EicFieldMapDetector.h
Referenced by ConstructGeometry().
The documentation for this class was generated from the following files:
EicRoot/blob/master/eic/base/EicFieldMapDetector.h
EicRoot/blob/master/eic/base/EicFieldMapDetector.cxx