EIC Software: EicRoot/blob/master/eic/cad/EicCadFile.cxx File Reference
EicCadFile.cxx File Reference
#include <assert.h>
#include <TColor.h>
#include <TGeoSphere.h>
#include <TGeoTorus.h>
#include <TGeoCone.h>
#include <TGeoTube.h>
#include <TGeoArb8.h>
#include <TGeoHalfSpace.h>
#include <TGeoCompositeShape.h>
#include <EicCompositeShape.h>
#include <EicCadFile.h>
#include <EicStlFactory.h>
Macros
#define SQR(x) ((x)*(x))
#define _ANGULAR_TOLERANCE_ (1E-10)
#define _SPATIAL_TOLERANCE_ (1E-10)
Functions
bool EicStlKeyCompare (const EicStlKey *lh, const EicStlKey *rh)
bool EicStlKeyEqual (const EicStlKey *lh, const EicStlKey *rh)
Macro Definition Documentation
#define _ANGULAR_TOLERANCE_ (1E-10)
Definition at line 95 of file EicCadFile.cxx.
View newest version in sPHENIX GitHub at line 95 of file EicCadFile.cxx
Referenced by EicCadWizardPlane::EicCadWizardPlane(), EicCadWizardTorus::IsEqual(), EicCadWizardPlane::IsEqual(), EicCadWizardCone::IsEqual(), and EicCadWizardCylinder::IsEqual().
#define _SPATIAL_TOLERANCE_ (1E-10)
Definition at line 96 of file EicCadFile.cxx.
View newest version in sPHENIX GitHub at line 96 of file EicCadFile.cxx
Referenced by EicCadWizardCone::IsEqual(), EicCadWizardTorus::IsEqual(), EicCadWizardSphere::IsEqual(), EicCadWizardPlane::IsEqual(), and EicCadWizardCylinder::IsEqual().
#define SQR (x) ((x)*(x))
Definition at line 92 of file EicCadFile.cxx.
View newest version in sPHENIX GitHub at line 92 of file EicCadFile.cxx
Function Documentation
bool EicStlKeyCompare (const EicStlKey * lh, const EicStlKey * rh)
Definition at line 100 of file EicCadFile.cxx.
View newest version in sPHENIX GitHub at line 100 of file EicCadFile.cxx
References EicStlKey::GetData(), and EicStlKey::GetDim().
Referenced by EicStlFacet::Calculate(), EicStlFacetEdge::EicStlFacetEdge(), EicStlMediaGroup::EicStlMediaGroup(), EicMediaHub::importMediaMapFile(), and EicCompositeShape::LocalFillBuffer3D().
bool EicStlKeyEqual (const EicStlKey * lh, const EicStlKey * rh)
Definition at line 106 of file EicCadFile.cxx.
View newest version in sPHENIX GitHub at line 106 of file EicCadFile.cxx
References EicStlKey::GetData(), and EicStlKey::GetDim().