EIC Software: TrkrClusterv1 Class Reference
TrkrClusterv1 Class Reference
Version 1 of TrkrCluster.
#include <fun4all_coresoftware/blob/master/offline/packages/trackbase/TrkrClusterv1.h>
Public Member Functions
TrkrClusterv1 ()
ctor
~TrkrClusterv1 () override
dtor
void identify (std::ostream &os=std::cout) const override
void Reset () override
Clear Event.
int isValid () const override
isValid returns non zero if object contains vailid data
PHObject * CloneMe () const override
Virtual copy constructor.
void CopyFrom (const TrkrCluster &) override
copy content from base class
void CopyFrom (TrkrCluster *source) override
copy content from base class
void setClusKey (TrkrDefs::cluskey id) override
TrkrDefs::cluskey getClusKey () const override
float getX () const override
void setX (float x) override
float getY () const override
void setY (float y) override
float getZ () const override
void setZ (float z) override
float getPosition (int coor) const override
void setPosition (int coor, float xi) override
void setGlobal () override
void setLocal () override
bool isGlobal () const override
unsigned int getAdc () const override
void setAdc (unsigned int adc) override
float getSize (unsigned int i, unsigned int j) const override
void setSize (unsigned int i, unsigned int j, float value) override
float getError (unsigned int i, unsigned int j) const override
void setError (unsigned int i, unsigned int j, float value) override
float getPhiSize () const override
float getZSize () const override
float getRPhiError () const override
float getPhiError () const override
float getZError () const override
Public Member Functions inherited from TrkrCluster
~TrkrCluster () override
dtor
virtual float getLocalX () const
virtual void setLocalX (float)
virtual float getLocalY () const
virtual void setLocalY (float)
virtual void setActsLocalError (unsigned int, unsigned int, float)
Acts functions, for Acts modules use only.
virtual float getActsLocalError (unsigned int, unsigned int) const
virtual TrkrDefs::subsurfkey getSubSurfKey () const
virtual void setSubSurfKey (TrkrDefs::subsurfkey)
Public Member Functions inherited from PHObject
PHObject ()
ctor
~PHObject () override
dtor
virtual PHObject * clone () const final
PHObject * Clone (const char *newname="") const final
void Copy (TObject &object) const final
virtual int isValid (const float) const
virtual int isValid (const double) const
virtual int isValid (const int) const
virtual int isValid (const unsigned int) const
virtual int isImplemented (const float f) const
virtual int isImplemented (const double f) const
virtual int isImplemented (const int i) const
virtual int isImplemented (const unsigned int i) const
virtual int Integrate () const
virtual int Integrate (PHObject *)
virtual void CopyFrom (const PHObject *obj)
Protected Attributes
TrkrDefs::cluskey m_cluskey
float m_pos [3]
bool m_isGlobal
unsigned int m_adc
float m_size [6]
float m_err [6]
Additional Inherited Members
Protected Member Functions inherited from TrkrCluster
TrkrCluster ()=default
Detailed Description
Version 1 of TrkrCluster.
Note - D. McGlinchey June 2018: CINT does not like "override", so ignore where CINT complains. Should be checked with ROOT 6 once migration occurs.
Definition at line 25 of file TrkrClusterv1.h.
View newest version in sPHENIX GitHub at line 25 of file TrkrClusterv1.h
Constructor & Destructor Documentation
TrkrClusterv1::TrkrClusterv1 ()
ctor
Definition at line 41 of file TrkrClusterv1.cc.
View newest version in sPHENIX GitHub at line 41 of file TrkrClusterv1.cc
References m_pos, setError(), and setSize().
Referenced by CloneMe().
TrkrClusterv1::~TrkrClusterv1 () inline override
dtor
Definition at line 32 of file TrkrClusterv1.h.
View newest version in sPHENIX GitHub at line 32 of file TrkrClusterv1.h
Member Function Documentation
PHObject* TrkrClusterv1::CloneMe () const inline override virtual
Virtual copy constructor.
Reimplemented from PHObject.
Definition at line 37 of file TrkrClusterv1.h.
View newest version in sPHENIX GitHub at line 37 of file TrkrClusterv1.h
References TrkrClusterv1().
void TrkrClusterv1::CopyFrom (const TrkrCluster & source) override virtual
copy content from base class
Reimplemented from TrkrCluster.
Definition at line 128 of file TrkrClusterv1.cc.
View newest version in sPHENIX GitHub at line 128 of file TrkrClusterv1.cc
References TrkrCluster::CopyFrom(), TrkrCluster::getAdc(), TrkrCluster::getClusKey(), TrkrCluster::getError(), TrkrCluster::getSize(), TrkrCluster::getX(), TrkrCluster::getY(), TrkrCluster::getZ(), TrkrCluster::isGlobal(), m_isGlobal, setAdc(), setClusKey(), setError(), setSize(), setX(), setY(), and setZ().
void TrkrClusterv1::CopyFrom (TrkrCluster * source) inline override virtual
copy content from base class
Reimplemented from TrkrCluster.
Definition at line 43 of file TrkrClusterv1.h.
View newest version in sPHENIX GitHub at line 43 of file TrkrClusterv1.h
References CopyFrom().
Referenced by CopyFrom().
unsigned int TrkrClusterv1::getAdc () const inline override virtual
Reimplemented from TrkrCluster.
Definition at line 65 of file TrkrClusterv1.h.
View newest version in sPHENIX GitHub at line 65 of file TrkrClusterv1.h
References m_adc.
Referenced by identify().
TrkrDefs::cluskey TrkrClusterv1::getClusKey () const inline override virtual
Reimplemented from TrkrCluster.
Definition at line 47 of file TrkrClusterv1.h.
View newest version in sPHENIX GitHub at line 47 of file TrkrClusterv1.h
References m_cluskey.
Referenced by identify().
float TrkrClusterv1::getError (unsigned int i, unsigned int j) const override virtual
Reimplemented from TrkrCluster.
Definition at line 166 of file TrkrClusterv1.cc.
View newest version in sPHENIX GitHub at line 166 of file TrkrClusterv1.cc
References m_err.
Referenced by getZError(), identify(), and isValid().
float TrkrClusterv1::getPhiError () const override virtual
Reimplemented from TrkrCluster.
Definition at line 175 of file TrkrClusterv1.cc.
View newest version in sPHENIX GitHub at line 175 of file TrkrClusterv1.cc
References getRPhiError(), m_pos, Acts::UnitConstants::rad, and square().
float TrkrClusterv1::getPhiSize () const override virtual
Reimplemented from TrkrCluster.
Definition at line 169 of file TrkrClusterv1.cc.
View newest version in sPHENIX GitHub at line 169 of file TrkrClusterv1.cc
Referenced by identify().
float TrkrClusterv1::getPosition (int coor) const inline override virtual
Reimplemented from TrkrCluster.
Definition at line 57 of file TrkrClusterv1.h.
View newest version in sPHENIX GitHub at line 57 of file TrkrClusterv1.h
References m_pos.
Referenced by identify(), and isValid().
float TrkrClusterv1::getRPhiError () const override virtual
Reimplemented from TrkrCluster.
Definition at line 182 of file TrkrClusterv1.cc.
View newest version in sPHENIX GitHub at line 182 of file TrkrClusterv1.cc
Referenced by getPhiError().
float TrkrClusterv1::getSize (unsigned int i, unsigned int j) const override virtual
Reimplemented from TrkrCluster.
Definition at line 157 of file TrkrClusterv1.cc.
View newest version in sPHENIX GitHub at line 157 of file TrkrClusterv1.cc
References m_size.
Referenced by getZSize(), identify(), and isValid().
float TrkrClusterv1::getX () const inline override virtual
Reimplemented from TrkrCluster.
Definition at line 51 of file TrkrClusterv1.h.
View newest version in sPHENIX GitHub at line 51 of file TrkrClusterv1.h
References m_pos.
float TrkrClusterv1::getY () const inline override virtual
Reimplemented from TrkrCluster.
Definition at line 53 of file TrkrClusterv1.h.
View newest version in sPHENIX GitHub at line 53 of file TrkrClusterv1.h
References m_pos.
float TrkrClusterv1::getZ () const inline override virtual
Reimplemented from TrkrCluster.
Definition at line 55 of file TrkrClusterv1.h.
View newest version in sPHENIX GitHub at line 55 of file TrkrClusterv1.h
References m_pos.
float TrkrClusterv1::getZError () const override virtual
Reimplemented from TrkrCluster.
Definition at line 185 of file TrkrClusterv1.cc.
View newest version in sPHENIX GitHub at line 185 of file TrkrClusterv1.cc
References getError().
float TrkrClusterv1::getZSize () const override virtual
Reimplemented from TrkrCluster.
Definition at line 172 of file TrkrClusterv1.cc.
View newest version in sPHENIX GitHub at line 172 of file TrkrClusterv1.cc
References getSize().
Referenced by identify().
void TrkrClusterv1::identify (std::ostream & os = std::cout) const override virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from TrkrCluster.
Definition at line 58 of file TrkrClusterv1.cc.
View newest version in sPHENIX GitHub at line 58 of file TrkrClusterv1.cc
References getAdc(), getClusKey(), getError(), getPhiSize(), getPosition(), getSize(), getZSize(), and m_isGlobal.
bool TrkrClusterv1::isGlobal () const inline override virtual
Reimplemented from TrkrCluster.
Definition at line 61 of file TrkrClusterv1.h.
View newest version in sPHENIX GitHub at line 61 of file TrkrClusterv1.h
References m_isGlobal.
int TrkrClusterv1::isValid () const override virtual
isValid returns non zero if object contains vailid data
Reimplemented from TrkrCluster.
Definition at line 108 of file TrkrClusterv1.cc.
View newest version in sPHENIX GitHub at line 108 of file TrkrClusterv1.cc
References getError(), getPosition(), getSize(), m_adc, and m_cluskey.
void TrkrClusterv1::Reset () inline override virtual
Clear Event.
Reimplemented from TrkrCluster.
Definition at line 35 of file TrkrClusterv1.h.
View newest version in sPHENIX GitHub at line 35 of file TrkrClusterv1.h
void TrkrClusterv1::setAdc (unsigned int adc) inline override virtual
Reimplemented from TrkrCluster.
Definition at line 66 of file TrkrClusterv1.h.
View newest version in sPHENIX GitHub at line 66 of file TrkrClusterv1.h
References m_adc.
Referenced by CopyFrom().
void TrkrClusterv1::setClusKey (TrkrDefs::cluskey id) inline override virtual
Reimplemented from TrkrCluster.
Definition at line 46 of file TrkrClusterv1.h.
View newest version in sPHENIX GitHub at line 46 of file TrkrClusterv1.h
References m_cluskey.
Referenced by CopyFrom().
void TrkrClusterv1::setError (unsigned int i, unsigned int j, float value) override virtual
Reimplemented from TrkrCluster.
Definition at line 160 of file TrkrClusterv1.cc.
View newest version in sPHENIX GitHub at line 160 of file TrkrClusterv1.cc
References m_err, and value.
Referenced by CopyFrom(), and TrkrClusterv1().
void TrkrClusterv1::setGlobal () inline override virtual
Reimplemented from TrkrCluster.
Definition at line 59 of file TrkrClusterv1.h.
View newest version in sPHENIX GitHub at line 59 of file TrkrClusterv1.h
References m_isGlobal.
void TrkrClusterv1::setLocal () inline override virtual
Reimplemented from TrkrCluster.
Definition at line 60 of file TrkrClusterv1.h.
View newest version in sPHENIX GitHub at line 60 of file TrkrClusterv1.h
References m_isGlobal.
void TrkrClusterv1::setPosition (int coor, float xi) inline override virtual
Reimplemented from TrkrCluster.
Definition at line 58 of file TrkrClusterv1.h.
View newest version in sPHENIX GitHub at line 58 of file TrkrClusterv1.h
References m_pos.
void TrkrClusterv1::setSize (unsigned int i, unsigned int j, float value) override virtual
Reimplemented from TrkrCluster.
Definition at line 151 of file TrkrClusterv1.cc.
View newest version in sPHENIX GitHub at line 151 of file TrkrClusterv1.cc
References m_size, and value.
Referenced by CopyFrom(), and TrkrClusterv1().
void TrkrClusterv1::setX (float x) inline override virtual
Reimplemented from TrkrCluster.
Definition at line 52 of file TrkrClusterv1.h.
View newest version in sPHENIX GitHub at line 52 of file TrkrClusterv1.h
References m_pos, and x.
Referenced by CopyFrom().
void TrkrClusterv1::setY (float y) inline override virtual
Reimplemented from TrkrCluster.
Definition at line 54 of file TrkrClusterv1.h.
View newest version in sPHENIX GitHub at line 54 of file TrkrClusterv1.h
References m_pos, and y.
Referenced by CopyFrom().
void TrkrClusterv1::setZ (float z) inline override virtual
Reimplemented from TrkrCluster.
Definition at line 56 of file TrkrClusterv1.h.
View newest version in sPHENIX GitHub at line 56 of file TrkrClusterv1.h
References m_pos, and z.
Referenced by CopyFrom().
Member Data Documentation
unsigned int TrkrClusterv1::m_adc protected
Definition at line 88 of file TrkrClusterv1.h.
View newest version in sPHENIX GitHub at line 88 of file TrkrClusterv1.h
Referenced by getAdc(), isValid(), and setAdc().
TrkrDefs::cluskey TrkrClusterv1::m_cluskey protected
Definition at line 85 of file TrkrClusterv1.h.
View newest version in sPHENIX GitHub at line 85 of file TrkrClusterv1.h
Referenced by getClusKey(), isValid(), and setClusKey().
float TrkrClusterv1::m_err[6] protected
Definition at line 90 of file TrkrClusterv1.h.
View newest version in sPHENIX GitHub at line 90 of file TrkrClusterv1.h
Referenced by getError(), and setError().
bool TrkrClusterv1::m_isGlobal protected
Definition at line 87 of file TrkrClusterv1.h.
View newest version in sPHENIX GitHub at line 87 of file TrkrClusterv1.h
Referenced by CopyFrom(), identify(), isGlobal(), setGlobal(), and setLocal().
float TrkrClusterv1::m_pos[3] protected
Definition at line 86 of file TrkrClusterv1.h.
View newest version in sPHENIX GitHub at line 86 of file TrkrClusterv1.h
Referenced by getPhiError(), getPosition(), getX(), getY(), getZ(), setPosition(), setX(), setY(), setZ(), and TrkrClusterv1().
float TrkrClusterv1::m_size[6] protected
Definition at line 89 of file TrkrClusterv1.h.
View newest version in sPHENIX GitHub at line 89 of file TrkrClusterv1.h
Referenced by getSize(), and setSize().
The documentation for this class was generated from the following files:
fun4all_coresoftware/blob/master/offline/packages/trackbase/TrkrClusterv1.h
fun4all_coresoftware/blob/master/offline/packages/trackbase/TrkrClusterv1.cc