EIC Software: EicRoot/blob/master/eic/cad/elmer/plugins/egconvert.cpp File Reference
egconvert.cpp File Reference
#include <stdio.h>
#include <math.h>
#include <stdarg.h>
#include <stdlib.h>
#include <ctype.h>
#include <string.h>
#include "egutils.h"
#include "egdef.h"
#include "egtypes.h"
#include "egmesh.h"
#include "egnative.h"
#include "egconvert.h"
Macros
#define getline fgets(line,MAXLINESIZE,in)
Functions
static int Getrow (char *line1, FILE *io, int upper)
static int GetrowDouble (char *line1, FILE *io)
static int Comsolrow (char *line1, FILE *io)
static void FindPointParents (struct FemType *data, struct BoundaryType *bound, int boundarynodes, int *nodeindx, int *boundindx, int info)
int LoadAbaqusInput (struct FemType *data, struct BoundaryType *bound, char *prefix, int info)
int LoadNastranInput (struct FemType *data, struct BoundaryType *bound, char *prefix, int info)
static void ReorderFidapNodes (struct FemType *data, int element, int nodes, int typeflag)
int LoadFidapInput (struct FemType *data, struct BoundaryType *boundaries, char *prefix, int info)
static void ReorderAnsysNodes (struct FemType *data, int *oldtopology, int element, int dim, int nodes)
int LoadAnsysInput (struct FemType *data, struct BoundaryType *bound, char *prefix, int info)
static void ReorderFieldviewNodes (struct FemType *data, int *oldtopology, int element, int dim, int nodes)
int LoadFieldviewInput (struct FemType *data, struct BoundaryType *bound, char *prefix, int info)
int LoadTriangleInput (struct FemType *data, struct BoundaryType *bound, char *prefix, int info)
int LoadMeditInput (struct FemType *data, struct BoundaryType *bound, char *prefix, int info)
int LoadGidInput (struct FemType *data, struct BoundaryType *bound, char *prefix, int info)
static void ReorderComsolNodes (int elementtype, int *topo)
int LoadComsolMesh (struct FemType *data, struct BoundaryType *bound, char *prefix, int info)
static int GmshToElmerType (int gmshtype)
static void GmshToElmerIndx (int elemtype, int *topology)
static int LoadGmshInput1 (struct FemType *data, struct BoundaryType *bound, char *filename, int info)
static int LoadGmshInput2 (struct FemType *data, struct BoundaryType *bound, char *filename, int info)
int LoadGmshInput (struct FemType *data, struct BoundaryType *bound, char *prefix, int info)
static int UnvToElmerType (int unvtype)
static int UnvRedundantIndexes (int nonodes, int *ind)
static void UnvToElmerIndx (int elemtype, int *topology)
int LoadUniversalMesh (struct FemType *data, struct BoundaryType *bound, char *prefix, int info)
int LoadCGsimMesh (struct FemType *data, char *prefix, int info)
Macro Definition Documentation
#define getline fgets(line,MAXLINESIZE,in)
Definition at line 42 of file egconvert.cpp.
View newest version in sPHENIX GitHub at line 42 of file egconvert.cpp
Referenced by Fun4AllInputManager::AddListFile(), BeamLine(), BeamLineDefineMagnets(), Acts::Test::BOOST_AUTO_TEST_CASE(), PHG4ProjCrystalCalorimeterDetector::ConstructProjectiveCrystals(), Fun4AllOscarInputManager::ConvertFromOscar(), Fun4AllHepMCInputManager::ConvertFromOscar(), ConvertStarlightAsciiToTree(), erhic::EventFromAsciiFactory< T >::Create(), erhic::LogReaderFactory::CreateReader(), HepMC3::deduce_reader(), eTTreemaker(), erhic::LogReaderPythia::Extract(), erhic::LogReaderPepsi::Extract(), erhic::LogReaderDjangoh::Extract(), erhic::LogReaderMilou::Extract(), erhic::LogReaderGmcTrans::Extract(), ActsExamples::BField::txt::fieldMapperRZ(), ActsExamples::BField::txt::fieldMapperXYZ(), FairDbSqlValPacket::Fill(), PHG4ProjCrystalCalorimeterDetector::Fill4x4Unit(), PHG4ProjCrystalCalorimeterDetector::FillSpecialUnit(), erhic::EventFromAsciiFactory< T >::FindFirstEvent(), erhic::Forester::FindFirstEvent(), erhic::FileFactory::GetFile(), GetParameterFromFile(), hFarFwdDefineMagnets(), starlightPythia::init(), LoadAnsysInput(), LoadCGsimMesh(), LoadFidapInput(), LoadFieldviewInput(), LoadGmshInput1(), LoadGmshInput2(), LoadMeditInput(), LoadTriangleInput(), main(), FairDbBinaryFile::operator>>(), EICG4BwdDetector::ParseParametersFromTable(), PHG4BackwardHcalDetector::ParseParametersFromTable(), PHG4EICForwardEcalDetector::ParseParametersFromTable(), PHG4ForwardHcalDetector::ParseParametersFromTable(), EICG4B0ECALDetector::ParseParametersFromTable(), PHG4LFHcalDetector::ParseParametersFromTable(), PHG4CrystalCalorimeterDetector::ParseParametersFromTable(), PHG4HybridHomogeneousCalorimeterDetector::ParseParametersFromTable(), PHG4BarrelEcalDetector::ParseParametersFromTable(), PHG4ForwardDualReadoutDetector::ParseParametersFromTable(), PHG4ForwardEcalDetector::ParseParametersFromTable(), Fun4AllOscarInputManager::PushBackEvents(), dfe::io_dsv_impl::DsvReader< Delimiter >::read(), PHPythia6::ReadConfig(), Acts::IntegrationTest::readFieldXYZ(), readFile(), RawTowerBuilderDRCALO::ReadGeometryFromTable(), B0RawTowerBuilderByHitIndex::ReadGeometryFromTable(), BwdRawTowerBuilderByHitIndex::ReadGeometryFromTable(), RawTowerBuilderByHitIndex::ReadGeometryFromTable(), RawTowerBuilderByHitIndexLHCal::ReadGeometryFromTable(), RawTowerBuilderByHitIndexBECAL::ReadGeometryFromTable(), EICG4ZDCRawTowerBuilderByHitIndex::ReadGeometryFromTable(), Smear::ParticleID::ReadP(), readSeedFile(), ActsExamples::Options::readTGeoLayerBuilderConfigs(), Acts::Test::readTracksAndVertexCSV(), EICG4RPSubsystem::SetParametersFromFile(), EICG4LumiSubsystem::SetParametersFromFile(), FairDbLogEntry::SetReason(), Acts::Test::testObjString(), and Acts::Test::testPlyString().
Function Documentation
static int Comsolrow (char * line1, FILE * io) static
Definition at line 110 of file egconvert.cpp.
View newest version in sPHENIX GitHub at line 110 of file egconvert.cpp
References MAXLINESIZE.
Referenced by LoadComsolMesh().
static void FindPointParents (struct FemType * data, struct BoundaryType * bound, int boundarynodes, int * nodeindx, int * boundindx, int info) static
Definition at line 130 of file egconvert.cpp.
View newest version in sPHENIX GitHub at line 130 of file egconvert.cpp
References FemType::elementtypes, FALSE, free_Ivector, GetElementSide(), Ivector, k, FemType::material, MAXNODESD1, FemType::noelements, FemType::noknots, BoundaryType::nosides, BoundaryType::parent, BoundaryType::parent2, printf(), BoundaryType::side, BoundaryType::side2, FemType::topology, TRUE, and BoundaryType::types.
Referenced by LoadAbaqusInput(), and LoadAnsysInput().
static int Getrow (char * line1, FILE * io, int upper) static
Definition at line 45 of file egconvert.cpp.
View newest version in sPHENIX GitHub at line 45 of file egconvert.cpp
References MAXLINESIZE.
Referenced by LoadAbaqusInput(), LoadAnsysInput(), LoadCGsimMesh(), LoadGidInput(), LoadGmshInput(), LoadGmshInput1(), LoadGmshInput2(), LoadMeditInput(), LoadNastranInput(), and LoadUniversalMesh().
static int GetrowDouble (char * line1, FILE * io) static
Definition at line 78 of file egconvert.cpp.
View newest version in sPHENIX GitHub at line 78 of file egconvert.cpp
References MAXLINESIZE.
Referenced by LoadUniversalMesh().
static void GmshToElmerIndx (int elemtype, int * topology) static
Definition at line 2733 of file egconvert.cpp.
View newest version in sPHENIX GitHub at line 2733 of file egconvert.cpp
References FALSE, MAXNODESD2, and TRUE.
Referenced by LoadGmshInput1(), and LoadGmshInput2().
static int GmshToElmerType (int gmshtype) static
Definition at line 2663 of file egconvert.cpp.
View newest version in sPHENIX GitHub at line 2663 of file egconvert.cpp
References printf().
Referenced by LoadGmshInput1(), and LoadGmshInput2().
int LoadAbaqusInput (struct FemType * data, struct BoundaryType * bound, char * prefix, int info)
Definition at line 286 of file egconvert.cpp.
View newest version in sPHENIX GitHub at line 286 of file egconvert.cpp
References AddExtension(), AllocateBoundary(), AllocateKnots(), COORD_AXIS, COORD_CART2, COORD_POLAR, FemType::coordsystem, FemType::dim, FemType::elementtypes, FALSE, INPUTHEPMC::filename, FindPointParents(), free_Ivector, free_ivector(), Getrow(), in, InitializeKnots(), Ivector, ivector(), material(), FemType::material, MAXDOFS, MAXFILESIZE, MAXLINESIZE, FemType::maxnodes, MAXNODESD2, FemType::noelements, FemType::noknots, printf(), StringToInteger(), StringToReal(), FemType::topology, TRUE, FemType::x, FemType::y, and FemType::z.
Referenced by ImportMeshDefinition().
int LoadAnsysInput (struct FemType * data, struct BoundaryType * bound, char * prefix, int info)
Definition at line 1191 of file egconvert.cpp.
View newest version in sPHENIX GitHub at line 1191 of file egconvert.cpp
References AllocateBoundary(), AllocateKnots(), FemType::bodyname, FemType::bodynamesexist, FemType::boundaryname, FemType::boundarynamesexist, FemType::dim, FALSE, INPUTHEPMC::filename, FindPointParents(), free_Ivector, getline, Getrow(), in, InitializeKnots(), Ivector, k, FemType::material, MAX, MAXFILESIZE, MAXLINESIZE, MAXNAMESIZE, FemType::maxnodes, next_int(), next_real(), FemType::noelements, FemType::noknots, BoundaryType::normal, BoundaryType::nosides, BoundaryType::parent, BoundaryType::parent2, printf(), ReorderAnsysNodes(), BoundaryType::side, BoundaryType::side2, TRUE, BoundaryType::types, x, FemType::x, y, FemType::y, z, and FemType::z.
Referenced by ImportMeshDefinition().
int LoadCGsimMesh (struct FemType * data, char * prefix, int info)
Definition at line 3747 of file egconvert.cpp.
View newest version in sPHENIX GitHub at line 3747 of file egconvert.cpp
References AddExtension(), AllocateKnots(), CreateVariable(), Acts::Test::debug, Acts::Test::dim, FemType::dim, FemType::dofs, FemType::elementtypes, FALSE, INPUTHEPMC::filename, getline, Getrow(), in, InitializeKnots(), material(), FemType::material, MAXFILESIZE, MAXLINESIZE, FemType::maxnodes, MAXNODESD2, next_int(), next_real(), FemType::noelements, FemType::noknots, printf(), FemType::topology, TRUE, FemType::x, FemType::y, and FemType::z.
Referenced by ImportMeshDefinition().
int LoadComsolMesh (struct FemType * data, struct BoundaryType * bound, char * prefix, int info)
Definition at line 2455 of file egconvert.cpp.
View newest version in sPHENIX GitHub at line 2455 of file egconvert.cpp
References AddExtension(), AllocateKnots(), Comsolrow(), Acts::Test::debug, Acts::Test::dim, FemType::dim, ElementsToBoundaryConditions(), FemType::elementtypes, FALSE, INPUTHEPMC::filename, GetElementDimension(), in, InitializeKnots(), k, material(), FemType::material, MAXFILESIZE, MAXLINESIZE, FemType::maxnodes, next_int(), next_real(), FemType::noelements, FemType::noknots, offset, printf(), ReorderComsolNodes(), FemType::topology, TRUE, FemType::x, FemType::y, and FemType::z.
Referenced by ImportMeshDefinition().
int LoadFidapInput (struct FemType * data, struct BoundaryType * boundaries, char * prefix, int info)
Definition at line 829 of file egconvert.cpp.
View newest version in sPHENIX GitHub at line 829 of file egconvert.cpp
References AddExtension(), AllocateKnots(), FemType::bodyname, FemType::bodynamesexist, CreateVariable(), Acts::Test::dim, FemType::dim, FemType::dofs, ElementsToBoundaryConditions(), FemType::elementtypes, FALSE, INPUTHEPMC::filename, free_Imatrix, getline, Imatrix, in, InitializeKnots(), ivector(), k, FemType::material, MAXFILESIZE, MAXLINESIZE, MAXNAMESIZE, FemType::maxnodes, next_int(), FemType::noelements, FemType::noknots, printf(), RenumberBoundaryTypes(), ReorderFidapNodes(), FemType::topology, TRUE, FemType::x, FemType::y, and FemType::z.
Referenced by ImportMeshDefinition().
int LoadFieldviewInput (struct FemType * data, struct BoundaryType * bound, char * prefix, int info)
Definition at line 1578 of file egconvert.cpp.
View newest version in sPHENIX GitHub at line 1578 of file egconvert.cpp
References AddExtension(), FemType::created, FemType::dim, ElementsToBoundaryConditions(), FemType::elementtypes, FALSE, INPUTHEPMC::filename, getline, Imatrix, in, InitializeKnots(), Ivector, k, FemType::material, MAXFILESIZE, MAXLINESIZE, FemType::maxnodes, next_int(), FemType::noelements, FemType::noknots, printf(), ReorderFieldviewNodes(), Rvector, FemType::topology, TRUE, x, FemType::x, y, FemType::y, z, and FemType::z.
Referenced by ImportMeshDefinition().
int LoadGidInput (struct FemType * data, struct BoundaryType * bound, char * prefix, int info)
Definition at line 2095 of file egconvert.cpp.
View newest version in sPHENIX GitHub at line 2095 of file egconvert.cpp
References AddExtension(), AllocateBoundary(), AllocateKnots(), BoundaryType::created, Acts::Test::debug, Acts::Test::dim, FemType::dim, FemType::elementtypes, FALSE, INPUTHEPMC::filename, free_Imatrix, free_Ivector, GetElementSide(), Getrow(), Imatrix, in, InitializeKnots(), Ivector, k, material(), FemType::material, MAXFILESIZE, MAXLINESIZE, FemType::maxnodes, MAXNODESD1, MAXNODESD2, n, next_int(), next_real(), FemType::noelements, FemType::noknots, BoundaryType::nosides, BoundaryType::parent, BoundaryType::parent2, printf(), BoundaryType::side, BoundaryType::side2, FemType::topology, TRUE, BoundaryType::types, x, FemType::x, y, FemType::y, z, and FemType::z.
Referenced by ImportMeshDefinition().
int LoadGmshInput (struct FemType * data, struct BoundaryType * bound, char * prefix, int info)
Definition at line 3140 of file egconvert.cpp.
View newest version in sPHENIX GitHub at line 3140 of file egconvert.cpp
References FALSE, INPUTHEPMC::filename, Getrow(), in, LoadGmshInput1(), LoadGmshInput2(), MAXFILESIZE, MAXLINESIZE, and printf().
Referenced by ImportMeshDefinition().
static int LoadGmshInput1 (struct FemType * data, struct BoundaryType * bound, char * filename, int info) static
Definition at line 2780 of file egconvert.cpp.
View newest version in sPHENIX GitHub at line 2780 of file egconvert.cpp
References nanoflann::allocate(), AllocateKnots(), Acts::Test::dim, FemType::dim, ElementsToBoundaryConditions(), FemType::elementtypes, FALSE, free_Ivector, getline, Getrow(), GmshToElmerIndx(), GmshToElmerType(), in, InitializeKnots(), Ivector, k, FemType::material, MAX, MAXLINESIZE, FemType::maxnodes, MAXNODESD1, MAXNODESD2, next_int(), next_real(), FemType::noelements, FemType::noknots, printf(), FemType::topology, TRUE, FemType::x, FemType::y, and FemType::z.
Referenced by LoadGmshInput().
static int LoadGmshInput2 (struct FemType * data, struct BoundaryType * bound, char * filename, int info) static
Definition at line 2939 of file egconvert.cpp.
View newest version in sPHENIX GitHub at line 2939 of file egconvert.cpp
References AllocateKnots(), Acts::Test::dim, FemType::dim, ElementsToBoundaryConditions(), FemType::elementtypes, FALSE, free_Ivector, getline, Getrow(), GmshToElmerIndx(), GmshToElmerType(), in, InitializeKnots(), Ivector, k, FemType::material, MAX, MAXLINESIZE, FemType::maxnodes, MAXNODESD1, MAXNODESD2, next_int(), next_real(), FemType::noelements, FemType::noknots, printf(), RenumberBoundaryTypes(), RenumberMaterialTypes(), FemType::topology, TRUE, FemType::x, FemType::y, and FemType::z.
Referenced by LoadGmshInput().
int LoadMeditInput (struct FemType * data, struct BoundaryType * bound, char * prefix, int info)
Definition at line 1976 of file egconvert.cpp.
View newest version in sPHENIX GitHub at line 1976 of file egconvert.cpp
References nanoflann::allocate(), AllocateKnots(), Acts::Test::dim, FemType::dim, FemType::elementtypes, FALSE, getline, Getrow(), in, InitializeKnots(), FemType::material, MAXFILESIZE, MAXLINESIZE, FemType::maxnodes, next_int(), next_real(), FemType::noelements, FemType::noknots, printf(), FemType::topology, TRUE, FemType::x, FemType::y, and FemType::z.
Referenced by ImportMeshDefinition().
int LoadNastranInput (struct FemType * data, struct BoundaryType * bound, char * prefix, int info)
Definition at line 556 of file egconvert.cpp.
View newest version in sPHENIX GitHub at line 556 of file egconvert.cpp
References AddExtension(), AllocateKnots(), FemType::dim, FemType::elementtypes, FALSE, INPUTHEPMC::filename, Getrow(), in, InitializeKnots(), k, material(), FemType::material, MAXDOFS, MAXFILESIZE, MAXLINESIZE, FemType::maxnodes, next_int(), next_real(), FemType::noelements, FemType::noknots, printf(), FemType::topology, TRUE, FemType::x, FemType::y, and FemType::z.
Referenced by ImportMeshDefinition().
int LoadTriangleInput (struct FemType * data, struct BoundaryType * bound, char * prefix, int info)
Definition at line 1802 of file egconvert.cpp.
View newest version in sPHENIX GitHub at line 1802 of file egconvert.cpp
References AllocateBoundary(), AllocateKnots(), CreateInverseTopology(), Acts::Test::dim, FemType::dim, FemType::elementtypes, FALSE, GetElementSide(), getline, in, InitializeKnots(), FemType::invtopo, Ivector, k, k2, FemType::material, MAXFILESIZE, FemType::maxinvtopo, MAXLINESIZE, FemType::maxnodes, next_int(), next_real(), FemType::noelements, FemType::noknots, BoundaryType::parent, BoundaryType::parent2, printf(), BoundaryType::side, BoundaryType::side2, FemType::topology, TRUE, BoundaryType::types, FemType::x, and FemType::y.
Referenced by ImportMeshDefinition().
int LoadUniversalMesh (struct FemType * data, struct BoundaryType * bound, char * prefix, int info)
Definition at line 3338 of file egconvert.cpp.
View newest version in sPHENIX GitHub at line 3338 of file egconvert.cpp
References AddExtension(), AllocateKnots(), bigerror(), FemType::bodyname, FemType::bodynamesexist, FemType::boundarynamesexist, Acts::Test::debug, Acts::Test::dim, FemType::dim, ElementsToBoundaryConditions(), FemType::elementtypes, exit(), FALSE, INPUTHEPMC::filename, free_Ivector, Getrow(), GetrowDouble(), in, InitializeKnots(), Ivector, k, FemType::material, MAX, MAXFILESIZE, MAXLINESIZE, MAXNAMESIZE, FemType::maxnodes, MIN, n, next_int(), next_real(), FemType::noelements, FemType::noknots, printf(), FemType::topology, TRUE, UnvRedundantIndexes(), UnvToElmerIndx(), UnvToElmerType(), FemType::x, FemType::y, and FemType::z.
Referenced by ImportMeshDefinition().
static void ReorderAnsysNodes (struct FemType * data, int * oldtopology, int element, int dim, int nodes) static
Definition at line 1086 of file egconvert.cpp.
View newest version in sPHENIX GitHub at line 1086 of file egconvert.cpp
References FemType::elementtypes, printf(), and FemType::topology.
Referenced by LoadAnsysInput().
static void ReorderComsolNodes (int elementtype, int * topo) static
Definition at line 2424 of file egconvert.cpp.
View newest version in sPHENIX GitHub at line 2424 of file egconvert.cpp
References MAXNODESD2.
Referenced by LoadComsolMesh().
static void ReorderFidapNodes (struct FemType * data, int element, int nodes, int typeflag) static
Definition at line 732 of file egconvert.cpp.
View newest version in sPHENIX GitHub at line 732 of file egconvert.cpp
References Acts::Test::dim, FemType::dim, FemType::elementtypes, MAXNODESD2, printf(), and FemType::topology.
Referenced by LoadFidapInput().
static void ReorderFieldviewNodes (struct FemType * data, int * oldtopology, int element, int dim, int nodes) static
Definition at line 1541 of file egconvert.cpp.
View newest version in sPHENIX GitHub at line 1541 of file egconvert.cpp
References FemType::elementtypes, printf(), and FemType::topology.
Referenced by LoadFieldviewInput().
static int UnvRedundantIndexes (int nonodes, int * ind) static
Definition at line 3274 of file egconvert.cpp.
View newest version in sPHENIX GitHub at line 3274 of file egconvert.cpp
References FALSE, printf(), and TRUE.
Referenced by LoadUniversalMesh().
static void UnvToElmerIndx (int elemtype, int * topology) static
Definition at line 3295 of file egconvert.cpp.
View newest version in sPHENIX GitHub at line 3295 of file egconvert.cpp
References FALSE, MAXNODESD2, and TRUE.
Referenced by LoadUniversalMesh().
static int UnvToElmerType (int unvtype) static
Definition at line 3181 of file egconvert.cpp.
View newest version in sPHENIX GitHub at line 3181 of file egconvert.cpp
References printf().
Referenced by LoadUniversalMesh().