EIC Software: fun4all_eic_qa/blob/master/macros/G4_EEMC.C File Reference
G4_EEMC.C File Reference
#include <GlobalVariables.C>
#include <g4calo/RawTowerBuilderByHitIndex.h>
#include <g4calo/RawTowerDigitizer.h>
#include <g4eiccalos/PHG4CrystalCalorimeterSubsystem.h>
#include <g4eiccalos/PHG4ForwardCalCellReco.h>
#include <g4eval/CaloEvaluator.h>
#include <g4main/PHG4Reco.h>
#include <caloreco/RawClusterBuilderFwd.h>
#include <caloreco/RawClusterBuilderTemplate.h>
#include <caloreco/RawTowerCalibration.h>
#include <fun4all/Fun4AllServer.h>
Namespaces
namespace Enable
namespace G4EEMC
Macros
#define MACRO_G4EEMC_C
Enumerations
enum G4EEMC::enu_Eemc_clusterizer { G4EEMC::kEemcGraphClusterizer, G4EEMC::kEemcTemplateClusterizer, G4EEMC::kEemcGraphClusterizer, G4EEMC::kEemcTemplateClusterizer }
Functions
void EEMCInit ()
void EEMCSetup (PHG4Reco *g4Reco)
void EEMC_Cells ()
void EEMC_Towers ()
void EEMC_Clusters ()
void EEMC_Eval (const std::string &outputfile)
Macro Definition Documentation
#define MACRO_G4EEMC_C
Definition at line 2 of file G4_EEMC.C.
View newest version in sPHENIX GitHub at line 2 of file G4_EEMC.C
Function Documentation
void EEMC_Cells ()
Definition at line 125 of file G4_EEMC.C.
View newest version in sPHENIX GitHub at line 125 of file G4_EEMC.C
void EEMC_Clusters ()
Definition at line 182 of file G4_EEMC.C.
View newest version in sPHENIX GitHub at line 182 of file G4_EEMC.C
References RawClusterBuilderTemplate::Detector(), RawClusterBuilderFwd::Detector(), G4EEMC::Eemc_clusterizer, Enable::EEMC_VERBOSITY, Fun4AllServer::instance(), G4EEMC::kEemcGraphClusterizer, G4EEMC::kEemcTemplateClusterizer, max, Fun4AllServer::registerSubsystem(), Enable::VERBOSITY, and Fun4AllBase::Verbosity().
void EEMC_Eval (const std::string & outputfile)
Definition at line 212 of file G4_EEMC.C.
View newest version in sPHENIX GitHub at line 212 of file G4_EEMC.C
References Enable::EEMC_VERBOSITY, Fun4AllServer::instance(), max, Fun4AllServer::registerSubsystem(), Enable::VERBOSITY, and Fun4AllBase::Verbosity().
void EEMC_Towers ()
Definition at line 129 of file G4_EEMC.C.
View newest version in sPHENIX GitHub at line 129 of file G4_EEMC.C
References RawTowerDigitizer::Detector(), RawTowerCalibration::Detector(), RawTowerBuilderByHitIndex::Detector(), Enable::EEMC_VERBOSITY, RawTowerBuilderByHitIndex::GeometryTableFile(), Fun4AllServer::instance(), RawTowerDigitizer::kNo_digitization, RawTowerCalibration::kSimple_linear_calibration, max, Fun4AllServer::registerSubsystem(), RawTowerCalibration::set_calib_algorithm(), RawTowerCalibration::set_calib_const_GeV_ADC(), RawTowerDigitizer::set_digi_algorithm(), RawTowerCalibration::set_pedstal_ADC(), RawTowerDigitizer::set_pedstal_central_ADC(), RawTowerDigitizer::set_pedstal_width_ADC(), RawTowerDigitizer::set_photonelec_ADC(), RawTowerDigitizer::set_photonelec_yield_visible_GeV(), RawTowerDigitizer::set_raw_tower_node_prefix(), RawTowerBuilderByHitIndex::set_sim_tower_node_prefix(), RawTowerDigitizer::set_zero_suppression_ADC(), G4EEMC::TowerDigi, Enable::VERBOSITY, and Fun4AllBase::Verbosity().
void EEMCInit ()
Definition at line 64 of file G4_EEMC.C.
View newest version in sPHENIX GitHub at line 64 of file G4_EEMC.C
References Acts::UnitConstants::cm, G4EEMC::Gdz, G4EEMC::Gz0, max, BlackHoleGeometry::max_radius, BlackHoleGeometry::max_z, min, BlackHoleGeometry::min_z, and G4EEMC::use_projective_geometry.
void EEMCSetup (PHG4Reco * g4Reco)
Use dedicated EEMC module
Definition at line 80 of file G4_EEMC.C.
View newest version in sPHENIX GitHub at line 80 of file G4_EEMC.C
References Enable::ABSORBER, Enable::EEMC_ABSORBER, Enable::EEMC_OVERLAPCHECK, Enable::EEMC_VERBOSITY, max, Enable::OVERLAPCHECK, PHG4DetectorSubsystem::OverlapCheck(), PHG4Reco::registerSubsystem(), PHG4DetectorSubsystem::set_string_param(), PHG4DetectorSubsystem::SetAbsorberActive(), PHG4DetectorSubsystem::SetActive(), PHG4CrystalCalorimeterSubsystem::SetProjectiveGeometry(), PHG4DetectorSubsystem::SuperDetector(), G4EEMC::use_projective_geometry, and Enable::VERBOSITY.