EIC Software: fun4all_eicmacros/blob/master/common/G4_CEmc_EIC.C File Reference
G4_CEmc_EIC.C File Reference
#include <GlobalVariables.C>
#include <g4calo/RawTowerBuilder.h>
#include <g4calo/RawTowerDigitizer.h>
#include <g4detectors/PHG4CylinderCellReco.h>
#include <g4detectors/PHG4CylinderSubsystem.h>
#include <g4eval/CaloEvaluator.h>
#include <g4main/PHG4Reco.h>
#include <caloreco/RawClusterBuilderGraph.h>
#include <caloreco/RawClusterBuilderTemplate.h>
#include <caloreco/RawTowerCalibration.h>
#include <fun4all/Fun4AllServer.h>
#include <cmath>
Namespaces
namespace Enable
namespace G4CEMC
namespace CEMC_TOWER
Macros
#define MACRO_G4CEMCEIC_C
Enumerations
enum G4CEMC::enu_Cemc_clusterizer {
G4CEMC::kCemcGraphClusterizer, G4CEMC::kCemcTemplateClusterizer, G4CEMC::kCemcGraphClusterizer, G4CEMC::kCemcTemplateClusterizer,
G4CEMC::kCemcGraphClusterizer, G4CEMC::kCemcTemplateClusterizer
}
Functions
void CEmcInit (const int nslats=1)
double CEmc (PHG4Reco *g4Reco, double radius)
void CEMC_Cells ()
void CEMC_Towers ()
void CEMC_Clusters ()
void CEMC_Eval (const std::string &outputfile)
Variables
bool Enable::CEMC = false
bool Enable::CEMC_ABSORBER = false
bool Enable::CEMC_OVERLAPCHECK = false
bool Enable::CEMC_CELL = false
bool Enable::CEMC_TOWER = false
bool Enable::CEMC_CLUSTER = false
bool Enable::CEMC_EVAL = false
int Enable::CEMC_VERBOSITY = 0
double G4CEMC::cemcdepth = 9
double G4CEMC::scint_width = 0.05
double G4CEMC::tungs_width = 0.245
double G4CEMC::electronics_width = 0.5
int G4CEMC::min_cemc_layer = 1
int G4CEMC::max_cemc_layer = 41
double G4CEMC::topradius = 106.8
double G4CEMC::bottomradius = 95
double G4CEMC::negrapidity = -1.5
double G4CEMC::posrapidity = 1.24
RawTowerDigitizer::enu_digi_algorithm G4CEMC::TowerDigi = RawTowerDigitizer::kSimple_photon_digitization
enu_Cemc_clusterizer G4CEMC::Cemc_clusterizer = kCemcTemplateClusterizer
template clusterizer, RawClusterBuilderTemplate, as developed by Sasha Bazilevsky
double CEMC_TOWER::emin = NAN
Macro Definition Documentation
#define MACRO_G4CEMCEIC_C
Definition at line 2 of file G4_CEmc_EIC.C.
View newest version in sPHENIX GitHub at line 2 of file G4_CEmc_EIC.C
Function Documentation
double CEmc (PHG4Reco * g4Reco, double radius)
Definition at line 95 of file G4_CEmc_EIC.C.
View newest version in sPHENIX GitHub at line 95 of file G4_CEmc_EIC.C
References Enable::ABSORBER, G4CEMC::bottomradius, cemc, Enable::CEMC_ABSORBER, Enable::CEMC_OVERLAPCHECK, G4CEMC::electronics_width, M_PI, max, G4CEMC::max_cemc_layer, BlackHoleGeometry::max_radius, BlackHoleGeometry::max_z, min, G4CEMC::min_cemc_layer, BlackHoleGeometry::min_z, G4CEMC::negrapidity, no_overlapp, Enable::OVERLAPCHECK, PHG4DetectorSubsystem::OverlapCheck(), G4CEMC::posrapidity, G4BECAL::radius, PHG4Reco::registerSubsystem(), G4CEMC::scint_width, PHG4DetectorSubsystem::set_double_param(), PHG4DetectorSubsystem::set_int_param(), PHG4DetectorSubsystem::set_string_param(), PHG4DetectorSubsystem::SetActive(), G4CEMC::topradius, G4CEMC::tungs_width, z1, and z2.
Referenced by Fun4All_G4_Momentum_Projection_Calorimeters(), and G4Setup().
void CEMC_Cells ()
Definition at line 229 of file G4_CEmc_EIC.C.
View newest version in sPHENIX GitHub at line 229 of file G4_CEmc_EIC.C
References PHG4CylinderCellReco::cellsize(), Enable::CEMC_VERBOSITY, PHG4CylinderCellReco::Detector(), Fun4AllServer::instance(), M_PI, max, G4CEMC::max_cemc_layer, G4CEMC::min_cemc_layer, no_overlapp, G4BECAL::radius, Fun4AllServer::registerSubsystem(), G4CEMC::scint_width, G4CEMC::tungs_width, Enable::VERBOSITY, and Fun4AllBase::Verbosity().
Referenced by Extract_ECCE_gdml(), Fun4All_AnaTutorial_sPHENIX(), Fun4All_AnaTutorial_sPHENIX_Jets(), Fun4All_G4_CEMC(), Fun4All_G4_EICDetector(), Fun4All_G4_EICDetector_AnaTutorial(), Fun4All_G4_FEMC(), Fun4All_G4_FHCAL(), Fun4All_G4_fsPHENIX(), Fun4All_G4_FullDetectorModular(), Fun4All_G4_FullDetectorModularBeast(), Fun4All_G4_HCALIN(), Fun4All_G4_HCALOUT(), Fun4All_G4_LBLDetector(), Fun4All_G4_Momentum_Projection_Calorimeters(), and Fun4All_G4_sPHENIX().
void CEMC_Clusters ()
Definition at line 302 of file G4_CEmc_EIC.C.
View newest version in sPHENIX GitHub at line 302 of file G4_CEmc_EIC.C
References G4CEMC::Cemc_clusterizer, Enable::CEMC_VERBOSITY, RawClusterBuilderGraph::Detector(), RawClusterBuilderTemplate::Detector(), exit(), Fun4AllServer::instance(), G4CEMC::kCemcGraphClusterizer, G4CEMC::kCemcTemplateClusterizer, RawClusterBuilderTemplate::LoadProfile(), max, Fun4AllServer::registerSubsystem(), RawClusterBuilderTemplate::set_threshold_energy(), Enable::VERBOSITY, and Fun4AllBase::Verbosity().
Referenced by Extract_ECCE_gdml(), Fun4All_AnaTutorial_sPHENIX(), Fun4All_AnaTutorial_sPHENIX_Jets(), Fun4All_G4_CEMC(), Fun4All_G4_EICDetector(), Fun4All_G4_EICDetector_AnaTutorial(), Fun4All_G4_FEMC(), Fun4All_G4_FHCAL(), Fun4All_G4_fsPHENIX(), Fun4All_G4_FullDetectorModular(), Fun4All_G4_FullDetectorModularBeast(), Fun4All_G4_HCALIN(), Fun4All_G4_HCALOUT(), Fun4All_G4_LBLDetector(), and Fun4All_G4_sPHENIX().
void CEMC_Eval (const std::string & outputfile)
Definition at line 334 of file G4_CEmc_EIC.C.
View newest version in sPHENIX GitHub at line 334 of file G4_CEmc_EIC.C
References Enable::CEMC_VERBOSITY, Fun4AllServer::instance(), max, Fun4AllServer::registerSubsystem(), Enable::VERBOSITY, and Fun4AllBase::Verbosity().
Referenced by Fun4All_AnaTutorial_sPHENIX(), Fun4All_AnaTutorial_sPHENIX_Jets(), Fun4All_G4_CEMC(), Fun4All_G4_EICDetector(), Fun4All_G4_EICDetector_AnaTutorial(), Fun4All_G4_FEMC(), Fun4All_G4_FHCAL(), Fun4All_G4_fsPHENIX(), Fun4All_G4_HCALIN(), Fun4All_G4_HCALOUT(), Fun4All_G4_LBLDetector(), and Fun4All_G4_sPHENIX().
void CEMC_Towers ()
Definition at line 252 of file G4_CEmc_EIC.C.
View newest version in sPHENIX GitHub at line 252 of file G4_CEmc_EIC.C
References Enable::CEMC_VERBOSITY, RawTowerBuilder::Detector(), RawTowerDigitizer::Detector(), RawTowerCalibration::Detector(), Acts::UnitConstants::e, CEMC_TOWER::emin, RawTowerBuilder::EminCut(), Fun4AllServer::instance(), RawTowerDigitizer::kNo_digitization, RawTowerCalibration::kSimple_linear_calibration, max, Fun4AllServer::registerSubsystem(), G4FHCAL::sampling_fraction, RawTowerCalibration::set_calib_algorithm(), RawTowerCalibration::set_calib_const_GeV_ADC(), RawTowerDigitizer::set_digi_algorithm(), RawTowerCalibration::set_pedstal_ADC(), RawTowerDigitizer::set_pedstal_central_ADC(), RawTowerDigitizer::set_pedstal_width_ADC(), RawTowerDigitizer::set_photonelec_ADC(), RawTowerDigitizer::set_photonelec_yield_visible_GeV(), RawTowerBuilder::set_sim_tower_node_prefix(), RawTowerDigitizer::set_zero_suppression_ADC(), G4CEMC::TowerDigi, Enable::VERBOSITY, and Fun4AllBase::Verbosity().
Referenced by Extract_ECCE_gdml(), Fun4All_AnaTutorial_sPHENIX(), Fun4All_AnaTutorial_sPHENIX_Jets(), Fun4All_G4_CEMC(), Fun4All_G4_EICDetector(), Fun4All_G4_EICDetector_AnaTutorial(), Fun4All_G4_FEMC(), Fun4All_G4_FHCAL(), Fun4All_G4_fsPHENIX(), Fun4All_G4_FullDetectorModular(), Fun4All_G4_FullDetectorModularBeast(), Fun4All_G4_HCALIN(), Fun4All_G4_HCALOUT(), Fun4All_G4_LBLDetector(), Fun4All_G4_Momentum_Projection_Calorimeters(), and Fun4All_G4_sPHENIX().
void CEmcInit (const int nslats = 1)
Definition at line 91 of file G4_CEmc_EIC.C.
View newest version in sPHENIX GitHub at line 91 of file G4_CEmc_EIC.C
Referenced by G4Init().