EIC Software: CbmRichRingFitterBase Class Reference
CbmRichRingFitterBase Class Reference abstract
Abstract base class for concrete Rich Ring fitting algorithms. Each derived class must implement the method DoFit.
#include <EicRoot/blob/master/rich/fitter/CbmRichRingFitterBase.h>
Public Member Functions
CbmRichRingFitterBase ()
Default constructor.
virtual ~CbmRichRingFitterBase ()
Destructor.
virtual void DoFit (CbmRichRingLight *ring)=0
Abstract method DoFit. To be implemented in the concrete class. Perform a fit to the hits attached to the ring by a ring finder. Fill the ring parameters member variables.
Protected Member Functions
virtual void CalcChi2 (CbmRichRingLight *ring)
Calculate chi2 for circle fitting algorithms.
Static Protected Attributes
static const int MAX_NOF_HITS_IN_RING = 400
Detailed Description
Abstract base class for concrete Rich Ring fitting algorithms. Each derived class must implement the method DoFit.
Author
Semen Lebedev
Date
2012
Definition at line 23 of file CbmRichRingFitterBase.h.
View newest version in sPHENIX GitHub at line 23 of file CbmRichRingFitterBase.h
Constructor & Destructor Documentation
CbmRichRingFitterBase::CbmRichRingFitterBase () inline
Default constructor.
Definition at line 30 of file CbmRichRingFitterBase.h.
View newest version in sPHENIX GitHub at line 30 of file CbmRichRingFitterBase.h
virtual CbmRichRingFitterBase::~CbmRichRingFitterBase () inline virtual
Destructor.
Definition at line 35 of file CbmRichRingFitterBase.h.
View newest version in sPHENIX GitHub at line 35 of file CbmRichRingFitterBase.h
Member Function Documentation
virtual void CbmRichRingFitterBase::CalcChi2 (CbmRichRingLight * ring) inline protected virtual
Calculate chi2 for circle fitting algorithms.
Parameters
[in,out] ring Fitted ring.
Reimplemented in CbmRichRingFitterEllipseBase.
Definition at line 52 of file CbmRichRingFitterBase.h.
View newest version in sPHENIX GitHub at line 52 of file CbmRichRingFitterBase.h
References d, CbmRichHitLight::fX, CbmRichHitLight::fY, CbmRichRingLight::GetCenterX(), CbmRichRingLight::GetCenterY(), CbmRichRingLight::GetHit(), CbmRichRingLight::GetNofHits(), CbmRichRingLight::GetRadius(), and CbmRichRingLight::SetChi2().
Referenced by CbmRichRingFitterRobustCOP::DoFit(), CbmRichRingFitterTAU::DoFit(), and CbmRichRingFitterCircle::DoFit().
virtual void CbmRichRingFitterBase::DoFit (CbmRichRingLight * ring) pure virtual
Abstract method DoFit. To be implemented in the concrete class. Perform a fit to the hits attached to the ring by a ring finder. Fill the ring parameters member variables.
Parameters
[in,out] ring Pointer to CbmRichRingLight
Implemented in CbmRichRingFitterEllipseMinuit, CbmRichRingFitterEllipseTau, CbmRichRingFitterCOP, CbmRichRingFitterCircle, CbmRichRingFitterTAU, and CbmRichRingFitterRobustCOP.
Referenced by CbmRichReconstruction::RunFitter().
Member Data Documentation
const int CbmRichRingFitterBase::MAX_NOF_HITS_IN_RING = 400 static protected
Definition at line 76 of file CbmRichRingFitterBase.h.
View newest version in sPHENIX GitHub at line 76 of file CbmRichRingFitterBase.h
The documentation for this class was generated from the following file:
EicRoot/blob/master/rich/fitter/CbmRichRingFitterBase.h