EIC Software: fun4all_macros/blob/master/common/G4_ZDC.C File Reference
G4_ZDC.C File Reference
#include <GlobalVariables.C>
#include <G4_BeamLine.C>
#include <g4calo/RawTowerBuilderByHitIndex.h>
#include <g4calo/RawTowerDigitizer.h>
#include <g4detectors/PHG4DetectorSubsystem.h>
#include <g4detectors/PHG4ZDCDefs.h>
#include <g4detectors/PHG4ZDCSubsystem.h>
#include <g4eval/CaloEvaluator.h>
#include <g4main/PHG4Reco.h>
#include <calobase/RawTowerDefs.h>
#include <caloreco/RawClusterBuilderFwd.h>
#include <caloreco/RawClusterBuilderTemplate.h>
#include <caloreco/RawTowerCalibration.h>
#include <fun4all/Fun4AllServer.h>
Namespaces
namespace Enable
namespace G4ZDC
Macros
#define MACRO_G4ZDC_C
Functions
void ZDCInit ()
void ZDCSetup (PHG4Reco *g4Reco, const int absorberactive=0)
void ZDC_Towers ()
void ZDC_Eval (std::string outputfile)
Variables
bool Enable::ZDC = false
bool Enable::ZDC_ABSORBER = false
bool Enable::ZDC_SUPPORT = false
bool Enable::ZDC_TOWER = false
bool Enable::ZDC_EVAL = false
bool Enable::ZDC_OVERLAPCHECK = false
int Enable::ZDC_VERBOSITY = 0
double G4ZDC::Gz0 = 1900.
double G4ZDC::outer_radius = 180.
string G4ZDC::calibfile = "ZDC/mapping/towerMap_ZDC.txt"
double G4ZDC::ZDCPlaceZ = 1843.0
Macro Definition Documentation
#define MACRO_G4ZDC_C
Definition at line 2 of file G4_ZDC.C.
View newest version in sPHENIX GitHub at line 2 of file G4_ZDC.C
Function Documentation
void ZDC_Eval (std::string outputfile)
Definition at line 137 of file G4_ZDC.C.
View newest version in sPHENIX GitHub at line 137 of file G4_ZDC.C
References Fun4AllServer::instance(), max, Fun4AllServer::registerSubsystem(), CaloEvaluator::set_do_cluster_eval(), Enable::VERBOSITY, Fun4AllBase::Verbosity(), and Enable::ZDC_VERBOSITY.
void ZDC_Towers ()
Definition at line 91 of file G4_ZDC.C.
View newest version in sPHENIX GitHub at line 91 of file G4_ZDC.C
References G4ZDC::calibfile, RawTowerDigitizer::Detector(), RawTowerCalibration::Detector(), RawTowerBuilderByHitIndex::Detector(), RawTowerBuilderByHitIndex::GeometryTableFile(), Fun4AllServer::instance(), RawTowerDigitizer::kNo_digitization, RawTowerCalibration::kSimple_linear_calibration, max, Fun4AllServer::registerSubsystem(), RawTowerCalibration::set_calib_algorithm(), RawTowerCalibration::set_calib_const_GeV_ADC(), RawTowerDigitizer::set_digi_algorithm(), RawTowerCalibration::set_pedstal_ADC(), RawTowerBuilderByHitIndex::set_sim_tower_node_prefix(), RawTowerDigitizer::TowerType(), RawTowerCalibration::TowerType(), Enable::VERBOSITY, Fun4AllBase::Verbosity(), and Enable::ZDC_VERBOSITY.
void ZDCInit ()
Definition at line 52 of file G4_ZDC.C.
View newest version in sPHENIX GitHub at line 52 of file G4_ZDC.C
References G4ZDC::Gz0, max, BlackHoleGeometry::max_radius, BlackHoleGeometry::max_z, min, BlackHoleGeometry::min_z, and G4ZDC::outer_radius.
Referenced by G4Init().
void ZDCSetup (PHG4Reco * g4Reco, const int absorberactive = 0)
Definition at line 59 of file G4_ZDC.C.
View newest version in sPHENIX GitHub at line 59 of file G4_ZDC.C
References Enable::ABSORBER, G4BEAMLINE::BackwardBeamLineEnclosure(), G4BEAMLINE::enclosure_center, G4BEAMLINE::ForwardBeamLineEnclosure(), Fun4AllServer::instance(), Enable::OVERLAPCHECK, PHG4DetectorSubsystem::OverlapCheck(), PHG4Reco::registerSubsystem(), PHG4DetectorSubsystem::set_double_param(), PHG4DetectorSubsystem::SetAbsorberActive(), PHG4DetectorSubsystem::SetActive(), PHG4Subsystem::SetMotherSubsystem(), PHG4DetectorSubsystem::SetSupportActive(), PHG4DetectorSubsystem::SuperDetector(), Enable::SUPPORT, zdc(), Enable::ZDC_ABSORBER, Enable::ZDC_OVERLAPCHECK, Enable::ZDC_SUPPORT, and G4ZDC::ZDCPlaceZ.
Referenced by G4Setup().