EIC Software: FairBaseContFact Class Reference
FairBaseContFact Class Reference
#include <EicRoot/blob/master/base/FairBaseContFact.h>
Public Member Functions
FairBaseContFact ()
~FairBaseContFact ()
FairParSet * createContainer (FairContainer *)
Public Member Functions inherited from FairContFact
FairContFact ()
virtual ~FairContFact ()
Bool_t addContext (const char *name)
void print ()
FairParSet * getContainer (const char *)
virtual void activateParIo (FairParIo *)
Private Member Functions
void setAllContainers ()
Additional Inherited Members
Protected Member Functions inherited from FairContFact
const char * getActualContext (const char *name)
ClassDef(FairContFact,
0) private FairContFact & operator= (const FairContFact &)
Protected Attributes inherited from FairContFact
TList * containers
FairLogger * fLogger
Detailed Description
Definition at line 10 of file FairBaseContFact.h.
View newest version in sPHENIX GitHub at line 10 of file FairBaseContFact.h
Constructor & Destructor Documentation
FairBaseContFact::FairBaseContFact ()
default ctor
Definition at line 18 of file FairBaseContFact.cxx.
View newest version in sPHENIX GitHub at line 18 of file FairBaseContFact.cxx
References FairRuntimeDb::addContFactory(), and FairRuntimeDb::instance().
FairBaseContFact::~FairBaseContFact () inline
default dtor
Definition at line 19 of file FairBaseContFact.h.
View newest version in sPHENIX GitHub at line 19 of file FairBaseContFact.h
Member Function Documentation
FairParSet * FairBaseContFact::createContainer (FairContainer * c) virtual
Calls the constructor of the corresponding parameter container. For an actual context, which is not an empty string and not the default context of this container, the name is concatinated with the context.
Calls the constructor of the corresponding parameter container. For an actual context, which is not an empty string and not the default context of this container, the name is concatinated with the context.
Reimplemented from FairContFact.
Definition at line 39 of file FairBaseContFact.cxx.
View newest version in sPHENIX GitHub at line 39 of file FairBaseContFact.cxx
References FairContainer::getConcatName(), FairContainer::getContext(), name, and p.
void FairBaseContFact::setAllContainers () private
Factory for all Base parameter containers
Creates the Container objects with all accepted contexts and adds them to the list of containers for the base library.
Definition at line 28 of file FairBaseContFact.cxx.
View newest version in sPHENIX GitHub at line 28 of file FairBaseContFact.cxx
References FairContainer::addContext(), and FairContFact::containers.
The documentation for this class was generated from the following files:
EicRoot/blob/master/base/FairBaseContFact.h
EicRoot/blob/master/base/FairBaseContFact.cxx