EIC Software: EicRoot/blob/master/eic/cad/wizard/EicCadWizard.cxx File Reference
EicCadWizard.cxx File Reference
#include <assert.h>
#include <sys/stat.h>
#include <dirent.h>
#include <STEPControl_Reader.hxx>
#include <STEPControl_Writer.hxx>
#include <StlAPI_Writer.hxx>
#include <Message.hxx>
#include <Message_Messenger.hxx>
#include <Message_PrinterOStream.hxx>
#include <TopoDS_Shape.hxx>
#include <TopoDS_Face.hxx>
#include <Geom_Surface.hxx>
#include <Geom_Plane.hxx>
#include <Geom_CylindricalSurface.hxx>
#include <Geom_ConicalSurface.hxx>
#include <Geom_SphericalSurface.hxx>
#include <Geom_ToroidalSurface.hxx>
#include <Geom_BSplineSurface.hxx>
#include <Geom_RectangularTrimmedSurface.hxx>
#include <BRep_Tool.hxx>
#include <BRepBuilderAPI_MakeFace.hxx>
#include <BRepAlgoAPI_Cut.hxx>
#include <BRepAlgoAPI_Common.hxx>
#include <BRepMesh_IncrementalMesh.hxx>
#include <BRepBuilderAPI_Transform.hxx>
#include <Bnd_Box.hxx>
#include <BRepBndLib.hxx>
#include <gp_Pln.hxx>
#include <gp_Cylinder.hxx>
#include <gp_Cone.hxx>
#include <gp_Sphere.hxx>
#include <gp_Torus.hxx>
#include <TopExp_Explorer.hxx>
#include <TGeoCompositeShape.h>
#include <TGeoMatrix.h>
#include <TGeoSphere.h>
#include <EicStlFactory.h>
#include <EicCadWizard.h>
#include <EicCadFileConfig.h>
#include <EicCompositeShape.h>
#include <TKey.h>
#include <TGeoTube.h>
Classes
class ObjectFace
Macros
#define _DOT_STEP_ (".stp")
#define _DOT_ROOT_ (".root")
#define _DOT_SPLIT_ (".split")
Functions
static void SetDefaultMatrixName (TGeoMatrix *matrix)
TGeoCombiTrans * Ax3ToCombiTrans (const char *name, const gp_Ax3 &ax3, double offset)
Macro Definition Documentation
#define _DOT_ROOT_ (".root")
Definition at line 56 of file EicCadWizard.cxx.
View newest version in sPHENIX GitHub at line 56 of file EicCadWizard.cxx
Referenced by EicCadWizard::AddRootDirectory().
#define _DOT_SPLIT_ (".split")
Definition at line 57 of file EicCadWizard.cxx.
View newest version in sPHENIX GitHub at line 57 of file EicCadWizard.cxx
Referenced by EicCadWizard::AddRootDirectory().
#define _DOT_STEP_ (".stp")
Definition at line 55 of file EicCadWizard.cxx.
View newest version in sPHENIX GitHub at line 55 of file EicCadWizard.cxx
Referenced by EicCadWizard::ConvertSourceDirectoryToRoot(), EicCadWizard::ConvertSourceFileToRoot(), and EicCadWizard::SplitAndRescaleSourceFile().
Function Documentation
TGeoCombiTrans* Ax3ToCombiTrans (const char * name, const gp_Ax3 & ax3, double offset)
Definition at line 1141 of file EicCadWizard.cxx.
View newest version in sPHENIX GitHub at line 1141 of file EicCadWizard.cxx
References data.
Referenced by EicCadWizardTorus::BuildRootVolume(), EicCadWizardCone::BuildRootVolume(), and EicCadWizardCylinder::BuildRootVolume().
static void SetDefaultMatrixName (TGeoMatrix * matrix) static
Definition at line 234 of file EicCadWizard.cxx.
View newest version in sPHENIX GitHub at line 234 of file EicCadWizard.cxx
References printf().
Referenced by EicCadWizard::AssembleRootFiles().