EIC Software: EicRoot/blob/master/eic/htc/misc.cxx File Reference
misc.cxx File Reference
#include <cassert>
#include <cstring>
#include <cstdlib>
#include <htclib.h>
Functions
int check_prefix (char *str, char *prefix)
int check_and_remove_suffix (char *ptr, char *suffix)
int assign_dimensional_value (char *string, char *suffix, double *value, double scale)
int cmd_line_variable_parser (char *str, t_cmd_line_variable_array *array)
Variables
char XYZ [3] = {'X', 'Y', 'Z'}
Function Documentation
int assign_dimensional_value (char * string, char * suffix, double * value, double scale)
Definition at line 48 of file misc.cxx.
View newest version in sPHENIX GitHub at line 48 of file misc.cxx
References check_and_remove_suffix().
int check_and_remove_suffix (char * ptr, char * suffix)
Definition at line 33 of file misc.cxx.
View newest version in sPHENIX GitHub at line 33 of file misc.cxx
Referenced by assign_dimensional_value(), and cmd_line_variable_parser().
int check_prefix (char * str, char * prefix)
Definition at line 22 of file misc.cxx.
View newest version in sPHENIX GitHub at line 22 of file misc.cxx
Referenced by KalmanFilter::Configure(), parse_htc_interpolation_string(), and runge_kutta_fun().
int cmd_line_variable_parser (char * str, t_cmd_line_variable_array * array)
Definition at line 69 of file misc.cxx.
View newest version in sPHENIX GitHub at line 69 of file misc.cxx
References t_cmd_line_variable::_assigned, _CMD_LINE_VARIABLE_NUM_MAX_, t_cmd_line_variable_array::actual_variable_num, t_cmd_line_variable::addr, check_and_remove_suffix(), ip(), t_cmd_line_variable::max, t_cmd_line_variable::min, t_cmd_line_variable::plen, t_cmd_line_variable::prefix, printf(), t_cmd_line_variable::suffix, and t_cmd_line_variable_array::variables.
Referenced by runge_kutta_fun().
Variable Documentation
char XYZ[3] = {'X', 'Y', 'Z'}
Definition at line 18 of file misc.cxx.
View newest version in sPHENIX GitHub at line 18 of file misc.cxx