EIC Software: eASTPhysicsList Class Reference
eASTPhysicsList Class Reference
#include <east/blob/main/PhysicsList/Base/include/eASTPhysicsList.hh>
Public Member Functions
eASTPhysicsList ()
~eASTPhysicsList ()
virtual void ConstructParticle ()
virtual void ConstructProcess ()
virtual void SetCuts ()
void AddRDM (G4bool val=true)
G4bool IfRDM () const
void AddOptical (G4bool val=true)
G4bool IfOptical () const
void AddStepLimit (G4int val=0)
G4int IfStepLimit () const
void SetGlobalStepLimit (G4double)
G4double GetGlobalStepLimit () const
G4Region * SetLocalStepLimit (const G4String &, G4double)
G4double GetLocalStepLimit (const G4String &) const
void SetGlobalCuts (G4double)
G4double GetGlobalCuts () const
void SetGlobalCut (G4int, G4double)
G4double GetGlobalCut (G4int i) const
G4Region * SetLocalCuts (const G4String &reg, G4double val)
G4double GetLocalCuts (const G4String &reg) const
G4Region * SetLocalCut (const G4String &, G4int, G4double)
G4double GetLocalCut (const G4String &, G4int) const
Private Member Functions
void SetupProcesses ()
G4Region * FindRegion (const G4String &) const
Private Attributes
G4bool processesAreRegistered = false
eASTPhysicsListMessenger * pMessenger
G4bool addRDM = false
G4bool addOptical = false
G4int stepLimit_opt = -1
std::map< G4Region *, G4double > localStepLimits
G4double globalCuts [4]
std::map< G4Region
*, G4ProductionCuts * > localCuts
Detailed Description
Definition at line 24 of file eASTPhysicsList.hh.
View newest version in sPHENIX GitHub at line 24 of file eASTPhysicsList.hh
Constructor & Destructor Documentation
eASTPhysicsList::eASTPhysicsList ()
Definition at line 52 of file eASTPhysicsList.cc.
View newest version in sPHENIX GitHub at line 52 of file eASTPhysicsList.cc
References Acts::UnitConstants::e, Acts::UnitConstants::eV, globalCuts, Acts::UnitConstants::mm, and pMessenger.
eASTPhysicsList::~eASTPhysicsList ()
Definition at line 88 of file eASTPhysicsList.cc.
View newest version in sPHENIX GitHub at line 88 of file eASTPhysicsList.cc
References pMessenger.
Member Function Documentation
void eASTPhysicsList::AddOptical (G4bool val = true) inline
Definition at line 56 of file eASTPhysicsList.hh.
View newest version in sPHENIX GitHub at line 56 of file eASTPhysicsList.hh
References addOptical.
Referenced by eASTPhysicsListMessenger::SetNewValue().
void eASTPhysicsList::AddRDM (G4bool val = true) inline
Definition at line 54 of file eASTPhysicsList.hh.
View newest version in sPHENIX GitHub at line 54 of file eASTPhysicsList.hh
References addRDM.
Referenced by eASTPhysicsListMessenger::SetNewValue().
void eASTPhysicsList::AddStepLimit (G4int val = 0) inline
Definition at line 59 of file eASTPhysicsList.hh.
View newest version in sPHENIX GitHub at line 59 of file eASTPhysicsList.hh
References stepLimit_opt.
Referenced by eASTPhysicsListMessenger::SetNewValue().
void eASTPhysicsList::ConstructParticle () virtual
Definition at line 91 of file eASTPhysicsList.cc.
View newest version in sPHENIX GitHub at line 91 of file eASTPhysicsList.cc
References processesAreRegistered, and SetupProcesses().
void eASTPhysicsList::ConstructProcess () virtual
Definition at line 151 of file eASTPhysicsList.cc.
View newest version in sPHENIX GitHub at line 151 of file eASTPhysicsList.cc
References verbose.
G4Region * eASTPhysicsList::FindRegion (const G4String & reg) const private
Definition at line 169 of file eASTPhysicsList.cc.
View newest version in sPHENIX GitHub at line 169 of file eASTPhysicsList.cc
Referenced by GetLocalCut(), GetLocalStepLimit(), SetLocalCut(), and SetLocalStepLimit().
G4double eASTPhysicsList::GetGlobalCut (G4int i) const inline
Definition at line 68 of file eASTPhysicsList.hh.
View newest version in sPHENIX GitHub at line 68 of file eASTPhysicsList.hh
References globalCuts.
Referenced by GetGlobalCuts().
G4double eASTPhysicsList::GetGlobalCuts () const inline
Definition at line 66 of file eASTPhysicsList.hh.
View newest version in sPHENIX GitHub at line 66 of file eASTPhysicsList.hh
References GetGlobalCut().
G4double eASTPhysicsList::GetGlobalStepLimit () const
Definition at line 251 of file eASTPhysicsList.cc.
View newest version in sPHENIX GitHub at line 251 of file eASTPhysicsList.cc
References GetLocalStepLimit().
G4double eASTPhysicsList::GetLocalCut (const G4String & reg, G4int i) const
Definition at line 204 of file eASTPhysicsList.cc.
View newest version in sPHENIX GitHub at line 204 of file eASTPhysicsList.cc
References FindRegion().
Referenced by GetLocalCuts().
G4double eASTPhysicsList::GetLocalCuts (const G4String & reg) const inline
Definition at line 79 of file eASTPhysicsList.hh.
View newest version in sPHENIX GitHub at line 79 of file eASTPhysicsList.hh
References GetLocalCut().
G4double eASTPhysicsList::GetLocalStepLimit (const G4String & reg) const
Definition at line 235 of file eASTPhysicsList.cc.
View newest version in sPHENIX GitHub at line 235 of file eASTPhysicsList.cc
References FindRegion().
Referenced by GetGlobalStepLimit().
G4bool eASTPhysicsList::IfOptical () const inline
Definition at line 57 of file eASTPhysicsList.hh.
View newest version in sPHENIX GitHub at line 57 of file eASTPhysicsList.hh
References addOptical.
Referenced by eASTPhysicsListMessenger::GetCurrentValue().
G4bool eASTPhysicsList::IfRDM () const inline
Definition at line 55 of file eASTPhysicsList.hh.
View newest version in sPHENIX GitHub at line 55 of file eASTPhysicsList.hh
References addRDM.
Referenced by eASTPhysicsListMessenger::GetCurrentValue().
G4int eASTPhysicsList::IfStepLimit () const inline
Definition at line 60 of file eASTPhysicsList.hh.
View newest version in sPHENIX GitHub at line 60 of file eASTPhysicsList.hh
References stepLimit_opt.
Referenced by eASTPhysicsListMessenger::GetCurrentValue().
void eASTPhysicsList::SetCuts () virtual
Definition at line 161 of file eASTPhysicsList.cc.
View newest version in sPHENIX GitHub at line 161 of file eASTPhysicsList.cc
References globalCuts.
Referenced by SetGlobalCut(), and SetGlobalCuts().
void eASTPhysicsList::SetGlobalCut (G4int i, G4double val)
Definition at line 182 of file eASTPhysicsList.cc.
View newest version in sPHENIX GitHub at line 182 of file eASTPhysicsList.cc
References globalCuts, and SetCuts().
Referenced by SetGlobalCuts(), and eASTPhysicsListMessenger::SetNewValue().
void eASTPhysicsList::SetGlobalCuts (G4double val)
Definition at line 175 of file eASTPhysicsList.cc.
View newest version in sPHENIX GitHub at line 175 of file eASTPhysicsList.cc
References SetCuts(), and SetGlobalCut().
Referenced by eASTPhysicsListMessenger::SetNewValue().
void eASTPhysicsList::SetGlobalStepLimit (G4double val)
Definition at line 248 of file eASTPhysicsList.cc.
View newest version in sPHENIX GitHub at line 248 of file eASTPhysicsList.cc
References SetLocalStepLimit().
Referenced by eASTPhysicsListMessenger::SetNewValue().
G4Region * eASTPhysicsList::SetLocalCut (const G4String & reg, G4int i, G4double val)
Definition at line 188 of file eASTPhysicsList.cc.
View newest version in sPHENIX GitHub at line 188 of file eASTPhysicsList.cc
References FindRegion().
Referenced by SetLocalCuts(), and eASTPhysicsListMessenger::SetNewValue().
G4Region* eASTPhysicsList::SetLocalCuts (const G4String & reg, G4double val) inline
Definition at line 69 of file eASTPhysicsList.hh.
View newest version in sPHENIX GitHub at line 69 of file eASTPhysicsList.hh
References SetLocalCut().
Referenced by eASTPhysicsListMessenger::SetNewValue().
G4Region * eASTPhysicsList::SetLocalStepLimit (const G4String & reg, G4double val)
Definition at line 218 of file eASTPhysicsList.cc.
View newest version in sPHENIX GitHub at line 218 of file eASTPhysicsList.cc
References FindRegion().
Referenced by SetGlobalStepLimit(), and eASTPhysicsListMessenger::SetNewValue().
void eASTPhysicsList::SetupProcesses () private
Definition at line 114 of file eASTPhysicsList.cc.
View newest version in sPHENIX GitHub at line 114 of file eASTPhysicsList.cc
References addOptical, addRDM, Acts::UnitConstants::mm, processesAreRegistered, and stepLimit_opt.
Referenced by ConstructParticle().
Member Data Documentation
G4bool eASTPhysicsList::addOptical = false private
Definition at line 43 of file eASTPhysicsList.hh.
View newest version in sPHENIX GitHub at line 43 of file eASTPhysicsList.hh
Referenced by AddOptical(), IfOptical(), and SetupProcesses().
G4bool eASTPhysicsList::addRDM = false private
Definition at line 42 of file eASTPhysicsList.hh.
View newest version in sPHENIX GitHub at line 42 of file eASTPhysicsList.hh
Referenced by AddRDM(), IfRDM(), and SetupProcesses().
G4double eASTPhysicsList::globalCuts[4] private
Definition at line 47 of file eASTPhysicsList.hh.
View newest version in sPHENIX GitHub at line 47 of file eASTPhysicsList.hh
Referenced by eASTPhysicsList(), GetGlobalCut(), SetCuts(), and SetGlobalCut().
std::map<G4Region*,G4ProductionCuts*> eASTPhysicsList::localCuts private
Definition at line 48 of file eASTPhysicsList.hh.
View newest version in sPHENIX GitHub at line 48 of file eASTPhysicsList.hh
std::map<G4Region*,G4double> eASTPhysicsList::localStepLimits private
Definition at line 46 of file eASTPhysicsList.hh.
View newest version in sPHENIX GitHub at line 46 of file eASTPhysicsList.hh
eASTPhysicsListMessenger* eASTPhysicsList::pMessenger private
Definition at line 39 of file eASTPhysicsList.hh.
View newest version in sPHENIX GitHub at line 39 of file eASTPhysicsList.hh
Referenced by eASTPhysicsList(), and ~eASTPhysicsList().
G4bool eASTPhysicsList::processesAreRegistered = false private
Definition at line 38 of file eASTPhysicsList.hh.
View newest version in sPHENIX GitHub at line 38 of file eASTPhysicsList.hh
Referenced by ConstructParticle(), and SetupProcesses().
G4int eASTPhysicsList::stepLimit_opt = -1 private
Definition at line 45 of file eASTPhysicsList.hh.
View newest version in sPHENIX GitHub at line 45 of file eASTPhysicsList.hh
Referenced by AddStepLimit(), IfStepLimit(), and SetupProcesses().
The documentation for this class was generated from the following files:
east/blob/main/PhysicsList/Base/include/eASTPhysicsList.hh
east/blob/main/PhysicsList/Base/src/eASTPhysicsList.cc