EIC Software: PndGeoPassivePar Class Reference
PndGeoPassivePar Class Reference
#include <EicRoot/blob/master/passive/PndGeoPassivePar.h>
Public Member Functions
PndGeoPassivePar (const char *name="PndGeoPassivePar", const char *title="Passive Geometry Parameters", const char *context="TestDefaultContext")
~PndGeoPassivePar (void)
void clear (void)
void putParams (FairParamList *)
Bool_t getParams (FairParamList *)
TObjArray * GetGeoSensitiveNodes ()
TObjArray * GetGeoPassiveNodes ()
Public Member Functions inherited from FairParGenericSet
FairParGenericSet (const char *name, const char *title, const char *context)
virtual ~FairParGenericSet ()
virtual void printParams ()
Bool_t init (FairParIo *inp)
Int_t write (FairParIo *output)
Public Member Functions inherited from FairParSet
FairParSet (const char *name="", const char *title="", const char *context="")
virtual ~FairParSet ()
virtual Bool_t init ()
virtual Int_t write ()
virtual void print ()
const char * getDetectorName ()
void resetInputVersions ()
void setInputVersion (Int_t v=-1, Int_t i=0)
Int_t getInputVersion (Int_t i)
void setStatic (Bool_t flag=kTRUE)
Bool_t isStatic ()
void setChanged (Bool_t flag=kTRUE)
Bool_t hasChanged ()
const char * getParamContext () const
void setAuthor (const char *s)
const char * getAuthor () const
void setDescription (const char *s)
const char * getDescription () const
void copyComment (FairParSet &r)
Public Attributes
TObjArray * fGeoSensNodes
TObjArray * fGeoPassNodes
Private Member Functions
PndGeoPassivePar (const PndGeoPassivePar &L)
PndGeoPassivePar & operator= (const PndGeoPassivePar &)
Additional Inherited Members
Protected Member Functions inherited from FairParGenericSet
FairParGenericSet ()
Protected Attributes inherited from FairParSet
TString detName
Int_t versions [3]
name of the detector the container belongs to
Bool_t status
versions of container in the 2 possible inputs
Bool_t changed
static flag
TString paramContext
flag is kTRUE if parameters have changed
TString author
TString description
FairLogger * fLogger
Detailed Description
Definition at line 7 of file PndGeoPassivePar.h.
View newest version in sPHENIX GitHub at line 7 of file PndGeoPassivePar.h
Constructor & Destructor Documentation
PndGeoPassivePar::PndGeoPassivePar (const char * name = "PndGeoPassivePar", const char * title = "Passive Geometry Parameters", const char * context = "TestDefaultContext")
PndGeoPassivePar::~PndGeoPassivePar (void)
Definition at line 18 of file PndGeoPassivePar.cxx.
View newest version in sPHENIX GitHub at line 18 of file PndGeoPassivePar.cxx
PndGeoPassivePar::PndGeoPassivePar (const PndGeoPassivePar & L) inline private
Definition at line 23 of file PndGeoPassivePar.h.
View newest version in sPHENIX GitHub at line 23 of file PndGeoPassivePar.h
Member Function Documentation
void PndGeoPassivePar::clear (void) virtual
Reimplemented from FairParSet.
Definition at line 21 of file PndGeoPassivePar.cxx.
View newest version in sPHENIX GitHub at line 21 of file PndGeoPassivePar.cxx
TObjArray* PndGeoPassivePar::GetGeoPassiveNodes () inline
Definition at line 20 of file PndGeoPassivePar.h.
View newest version in sPHENIX GitHub at line 20 of file PndGeoPassivePar.h
References fGeoPassNodes.
Referenced by ClassImp(), PndMagnet::ConstructASCIIGeometry(), and PndTarget::ConstructGeometry().
TObjArray* PndGeoPassivePar::GetGeoSensitiveNodes () inline
Definition at line 19 of file PndGeoPassivePar.h.
View newest version in sPHENIX GitHub at line 19 of file PndGeoPassivePar.h
References fGeoSensNodes.
Referenced by ClassImp(), PndMagnet::ConstructASCIIGeometry(), and PndTarget::ConstructGeometry().
Bool_t PndGeoPassivePar::getParams (FairParamList * l) virtual
Implements FairParGenericSet.
Definition at line 32 of file PndGeoPassivePar.cxx.
View newest version in sPHENIX GitHub at line 32 of file PndGeoPassivePar.cxx
References FairParamList::fillObject().
PndGeoPassivePar& PndGeoPassivePar::operator= (const PndGeoPassivePar &) inline private
Definition at line 24 of file PndGeoPassivePar.h.
View newest version in sPHENIX GitHub at line 24 of file PndGeoPassivePar.h
void PndGeoPassivePar::putParams (FairParamList * l) virtual
Implements FairParGenericSet.
Definition at line 26 of file PndGeoPassivePar.cxx.
View newest version in sPHENIX GitHub at line 26 of file PndGeoPassivePar.cxx
References FairParamList::addObject().
Member Data Documentation
TObjArray* PndGeoPassivePar::fGeoPassNodes
Definition at line 10 of file PndGeoPassivePar.h.
View newest version in sPHENIX GitHub at line 10 of file PndGeoPassivePar.h
Referenced by GetGeoPassiveNodes().
TObjArray* PndGeoPassivePar::fGeoSensNodes
Definition at line 9 of file PndGeoPassivePar.h.
View newest version in sPHENIX GitHub at line 9 of file PndGeoPassivePar.h
Referenced by GetGeoSensitiveNodes().
The documentation for this class was generated from the following files:
EicRoot/blob/master/passive/PndGeoPassivePar.h
EicRoot/blob/master/passive/PndGeoPassivePar.cxx