EIC Software: Acts::Visualization Namespace Reference
Acts::Visualization Namespace Reference
Functions
static std::array< double, 3 > decomposeCovariance (const ActsSymMatrixD< 2 > &covariance)
static std::vector< Vector3D > createEllipse (double lambda0, double lambda1, double theta, size_t lseg, double outOfPlane, const Vector2D &lposition=Vector2D(0., 0.), const Transform3D &transform=Transform3D::Identity())
static void drawCovarianceCartesian (IVisualization &helper, const Vector2D &lposition, const ActsSymMatrixD< 2 > &covariance, const Transform3D &transform, std::vector< int > nsigma={3}, double locErrorScale=1, size_t lseg=72, const IVisualization::ColorType &color={20, 120, 20}, double outOfPlane=0.1)
static void drawCovarianceAngular (IVisualization &helper, const Vector3D &position, const Vector3D &direction, const ActsSymMatrixD< 2 > &covariance, std::vector< int > nsigma={3}, double directionScale=1, double angularErrorScale=1, size_t lseg=72, const IVisualization::ColorType &color={20, 120, 20})
template<typename parameters_t >
static void drawBoundParameters (IVisualization &helper, const parameters_t &parameters, const GeometryContext &gctx=GeometryContext(), double momentumScale=1., double locErrorScale=1., double angularErrorScale=1., bool drawParameterSurface=true, size_t lseg=72, const IVisualization::ColorType &pcolor={20, 120, 20}, const IVisualization::ColorType &scolor={235, 198, 52})
static void drawSurface (IVisualization &helper, const Surface &surface, const GeometryContext &gctx, const Transform3D &transform=Transform3D::Identity(), size_t lseg=72, bool triangulate=false, const IVisualization::ColorType &color={120, 120, 120})
template<typename volume_t >
void drawVolume (IVisualization &helper, const volume_t &volume, const GeometryContext &gctx, const Transform3D &transform=Transform3D::Identity(), size_t lseg=72, bool triangulate=false, const IVisualization::ColorType &color={120, 120, 120})
static void drawSegmentBase (IVisualization &helper, const Vector3D &start, const Vector3D &end, double thickness, int arrows=0, double arrowLength=0., double arrowWidth=0., size_t lseg=72, const IVisualization::ColorType &color={120, 120, 120})
static void drawSegment (IVisualization &helper, const Vector3D &start, const Vector3D &end, double thickness, size_t lseg=72, const IVisualization::ColorType &color={20, 120, 120})
static void drawArrowBackward (IVisualization &helper, const Vector3D &start, const Vector3D &end, double thickness, double arrowLength, double arrowWidth, size_t lseg=72, const IVisualization::ColorType &color={120, 120, 120})
static void drawArrowForward (IVisualization &helper, const Vector3D &start, const Vector3D &end, double thickness, double arrowLength, double arrowWidth, size_t lseg=72, const IVisualization::ColorType &color={120, 120, 120})
static void drawArrowsBoth (IVisualization &helper, const Vector3D &start, const Vector3D &end, double thickness, double arrowLength, double arrowWidth, size_t lseg=72, const IVisualization::ColorType &color={120, 120, 120})
Function Documentation
static std::vector<Vector3D> Acts::Visualization::createEllipse (double lambda0, double lambda1, double theta, size_t lseg, double outOfPlane, const Vector2D & lposition = Vector2D(0., 0.), const Transform3D & transform = Transform3D::Identity()) inline static
Helper mehod to draw the ellipse points
Parameters
lambda0 The Eigenvalue in 0
lambda1 The Eigenvalue in 1
theta The angle between the x/y frame and EV frame
lseg The number of segments
outOfPlane The out of plane offset for visibility
lposition The local anker point of the ellipse
transform The transform to global
Definition at line 56 of file EventDataVisualization.hpp.
View newest version in sPHENIX GitHub at line 56 of file EventDataVisualization.hpp
References cos(), it, M_PI, phi, Acts::Test::transform, x, and analysis::y.
static std::array<double, 3> Acts::Visualization::decomposeCovariance (const ActsSymMatrixD< 2 > & covariance) inline static
Helper to find the egen values and corr angle
Parameters
covariance The covariance matrix
Definition at line 30 of file EventDataVisualization.hpp.
View newest version in sPHENIX GitHub at line 30 of file EventDataVisualization.hpp
References Acts::eLOC_0, Acts::eLOC_1, and ds::theta.
Referenced by Acts::Test::BOOST_AUTO_TEST_CASE().
static void Acts::Visualization::drawArrowBackward (IVisualization & helper, const Vector3D & start, const Vector3D & end, double thickness, double arrowLength, double arrowWidth, size_t lseg = 72, const IVisualization::ColorType & color = {120, 120, 120}) inline static
Convenience function : arrow pointing back
Parameters
helper [in, out] The visualization helper
start The start point
end The end point
thickness of the line, if bigger 0, approximated by cylinder
arrowLength wrt halflength
arrorWidth wrt thickness
lseg The number of segments for a full arch (if needed)
color the (optional) color of the object to be written
Definition at line 196 of file GeometryVisualization.hpp.
View newest version in sPHENIX GitHub at line 196 of file GeometryVisualization.hpp
Referenced by Acts::PrimitivesVisualization::test().
static void Acts::Visualization::drawArrowForward (IVisualization & helper, const Vector3D & start, const Vector3D & end, double thickness, double arrowLength, double arrowWidth, size_t lseg = 72, const IVisualization::ColorType & color = {120, 120, 120}) inline static
Convenience function : arrow pointing forwad
Parameters
helper [in, out] The visualization helper
start The start point
end The end point
thickness of the line, if bigger 0, approximated by cylinder
arrowLength wrt halflength
arrorWidth wrt thickness
lseg The number of segments for a full arch (if needed)
color the (optional) color of the object to be written
Definition at line 214 of file GeometryVisualization.hpp.
View newest version in sPHENIX GitHub at line 214 of file GeometryVisualization.hpp
Referenced by Acts::PrimitivesVisualization::test().
static void Acts::Visualization::drawArrowsBoth (IVisualization & helper, const Vector3D & start, const Vector3D & end, double thickness, double arrowLength, double arrowWidth, size_t lseg = 72, const IVisualization::ColorType & color = {120, 120, 120}) inline static
Convenience function : arrow pointing both directions
Parameters
helper [in, out] The visualization helper
start The start point
end The end point
thickness of the line, if bigger 0, approximated by cylinder
arrowLength wrt halflength
arrorWidth wrt thickness
lseg The number of segments for a full arch (if needed)
color the (optional) color of the object to be written
Definition at line 232 of file GeometryVisualization.hpp.
View newest version in sPHENIX GitHub at line 232 of file GeometryVisualization.hpp
Referenced by Acts::PrimitivesVisualization::test().
template<typename parameters_t > static void Acts::Visualization::drawBoundParameters (IVisualization & helper, const parameters_t & parameters, const GeometryContext & gctx = GeometryContext(), double momentumScale = 1., double locErrorScale = 1., double angularErrorScale = 1., bool drawParameterSurface = true, size_t lseg = 72, const IVisualization::ColorType & pcolor = {20, 120, 20}, const IVisualization::ColorType & scolor = {235, 198, 52}) inline static
Helper method to Surface objects
Parameters
helper [in, out] The visualization helper
parameters The bound parameters to be drawn
gctx The geometry context for which it is drawn
momentumScale The scale of the momentum
locErrorScale The scale of the local error
angularErrorScale The sclae of the angular error
drawParameterSurface The indicator whether to draw the surface
lseg The number of segments for a full arch (if needed)
pcolor the (optional) color of the parameters to be written
scolor the (optional) color of the surface to be written
Definition at line 170 of file EventDataVisualization.hpp.
View newest version in sPHENIX GitHub at line 170 of file EventDataVisualization.hpp
Referenced by Acts::EventDataVisualization::test().
static void Acts::Visualization::drawCovarianceAngular (IVisualization & helper, const Vector3D & position, const Vector3D & direction, const ActsSymMatrixD< 2 > & covariance, std::vector< int > nsigma = {3}, double directionScale = 1, double angularErrorScale = 1, size_t lseg = 72, const IVisualization::ColorType & color = {20, 120, 20}) inline static
Helper method to error cone of a direction
Parameters
helper [in, out] The visualization helper
position Where the cone originates from
direction The direction parameters
covariance The 2x2 covariance matrix for phi/theta
nsigma The sigmas to be drawn
directionScale The direction arror length
angularErrorScale The local Error scale
lseg The number of segments
color The draw color
Definition at line 121 of file EventDataVisualization.hpp.
View newest version in sPHENIX GitHub at line 121 of file EventDataVisualization.hpp
Referenced by Acts::PrimitivesVisualization::test().
static void Acts::Visualization::drawCovarianceCartesian (IVisualization & helper, const Vector2D & lposition, const ActsSymMatrixD< 2 > & covariance, const Transform3D & transform, std::vector< int > nsigma = {3}, double locErrorScale = 1, size_t lseg = 72, const IVisualization::ColorType & color = {20, 120, 20}, double outOfPlane = 0.1) inline static
Helper method to draw error ellipse
Parameters
helper [in, out] The visualization helper
lposition The local position
covariance The covariance matrix
transform The reference Frame transform
nsigma The sigmas to be drawn
locErrorScale The local Error scale
color The draw color
outOfPlane The out of plane drawning option
Definition at line 91 of file EventDataVisualization.hpp.
View newest version in sPHENIX GitHub at line 91 of file EventDataVisualization.hpp
Referenced by Acts::PrimitivesVisualization::test().
static void Acts::Visualization::drawSegment (IVisualization & helper, const Vector3D & start, const Vector3D & end, double thickness, size_t lseg = 72, const IVisualization::ColorType & color = { 20, 120, 120}) inline static
Convenience function : line
Parameters
helper [in, out] The visualization helper
start The start point
end The end point
thickness of the line, if bigger 0, approximated by cylinder
lseg The number of segments for a full arch (if needed)
color the (optional) color of the object to be written
Definition at line 178 of file GeometryVisualization.hpp.
View newest version in sPHENIX GitHub at line 178 of file GeometryVisualization.hpp
Referenced by Acts::PrimitivesVisualization::test().
static void Acts::Visualization::drawSegmentBase (IVisualization & helper, const Vector3D & start, const Vector3D & end, double thickness, int arrows = 0, double arrowLength = 0., double arrowWidth = 0., size_t lseg = 72, const IVisualization::ColorType & color = {120, 120, 120}) inline static
Helper method to draw lines - base for all lines
Parameters
helper [in, out] The visualization helper
start The start point
end The end point
thickness of the line, if bigger 0, approximated by cylinder
arrows [ -1 | 0 | 1 | 2 ] = [ start | none | end | both ]
arrowLength wrt halflength
arrowWidth wrt thickness
lseg The number of segments for a full arch (if needed)
color the (optional) color of the object to be written
Definition at line 84 of file GeometryVisualization.hpp.
View newest version in sPHENIX GitHub at line 84 of file GeometryVisualization.hpp
static void Acts::Visualization::drawSurface (IVisualization & helper, const Surface & surface, const GeometryContext & gctx, const Transform3D & transform = Transform3D::Identity(), size_t lseg = 72, bool triangulate = false, const IVisualization::ColorType & color = {120, 120, 120}) inline static
Helper method to Surface objects
Parameters
helper [in, out] The visualization helper
surface The surface to be drawn
gctx The geometry context for which it is drawn
transform An option additional transform
lseg The number of segments for a full arch (if needed)
triangulate The (optional) boolean diretive to triangulate the faces
color the (optional) color of the object to be written
Definition at line 36 of file GeometryVisualization.hpp.
View newest version in sPHENIX GitHub at line 36 of file GeometryVisualization.hpp
Referenced by Acts::PrimitivesVisualization::test(), and Acts::SurfaceVisualization::test().
template<typename volume_t > void Acts::Visualization::drawVolume (IVisualization & helper, const volume_t & volume, const GeometryContext & gctx, const Transform3D & transform = Transform3D::Identity(), size_t lseg = 72, bool triangulate = false, const IVisualization::ColorType & color = {120, 120, 120}) inline
Helper method for volume objects
Template Parameters
volume_t the templated volume class
Parameters
helper [in, out] The visualization helper
volume The surface to be drawn
gctx The geometry context for which it is drawn
transform An option additional transform
lseg The number of segments for a full arch (if needed)
triangulate The (optional) boolean diretive to triangulate the faces
color the (optional) color of the object to be written
Definition at line 59 of file GeometryVisualization.hpp.
View newest version in sPHENIX GitHub at line 59 of file GeometryVisualization.hpp
Referenced by Acts::VolumeVisualization::test().