EIC Software: Acts::Volume Class Reference
Acts::Volume Class Reference
#include <fun4all_acts/blob/master/Core/include/Acts/Geometry/Volume.hpp>
Public Types
using BoundingBox = AxisAlignedBoundingBox< Volume, double, 3 >
Public Member Functions
Volume ()
Default constructor.
Volume (const std::shared_ptr< const Transform3D > &htrans, VolumeBoundsPtr volbounds)
Volume (const Volume &vol, const Transform3D *shift=nullptr)
virtual ~Volume ()
Destructor.
Volume & operator= (const Volume &vol)
const Transform3D & transform () const
Return methods for geometry transform.
const Transform3D & itransform () const
Returns the inverted transform of this volume.
const Vector3D & center () const
returns the center of the volume
const VolumeBounds & volumeBounds () const
returns the volumeBounds()
BoundingBox boundingBox (const Vector3D &envelope={0, 0, 0}) const
const BoundingBox & orientedBoundingBox () const
bool inside (const Vector3D &gpos, double tol=0.) const
const Vector3D binningPosition (const GeometryContext &gctx, BinningValue bValue) const override
Public Member Functions inherited from Acts::GeometryObject
GeometryObject ()=default
Defaulted construrctor.
GeometryObject (const GeometryObject &)=default
Defaulted copy constructor.
GeometryObject (const GeometryID &geoID)
GeometryObject & operator= (const GeometryObject &geoID)
const GeometryID & geoID () const
virtual double binningPositionValue (const GeometryContext &gctx, BinningValue bValue) const
void assignGeoID (const GeometryID &geoID)
Protected Attributes
std::shared_ptr< const
Transform3D > m_transform
Transform3D m_itransform
Vector3D m_center
VolumeBoundsPtr m_volumeBounds
BoundingBox m_orientedBoundingBox
Protected Attributes inherited from Acts::GeometryObject
GeometryID m_geoID
Detailed Description
It inhertis of GeometryObject for TDD identification
Base class for all volumes inside the tracking realm, it defines the interface for inherited Volume classes regarding the geometrical information.
Definition at line 34 of file Volume.hpp.
View newest version in sPHENIX GitHub at line 34 of file Volume.hpp
Member Typedef Documentation
using Acts::Volume::BoundingBox = AxisAlignedBoundingBox<Volume, double, 3>
Definition at line 36 of file Volume.hpp.
View newest version in sPHENIX GitHub at line 36 of file Volume.hpp
Constructor & Destructor Documentation
Acts::Volume::Volume ()
Default constructor.
Definition at line 23 of file Volume.cpp.
View newest version in sPHENIX GitHub at line 23 of file Volume.cpp
Acts::Volume::Volume (const std::shared_ptr< const Transform3D > & htrans, VolumeBoundsPtr volbounds)
Explicit constructor with shared arguments
Parameters
htrans is the transform to position the volume in 3D space
volbounds is the volume boundary definitions
Note
This will automatically build an oriented bounding box with an envelope value of (0.05, 0.05, 0.05)mm
Acts::Volume::Volume (const Volume & vol, const Transform3D * shift = nullptr)
Copy Constructor - with optional shift
Parameters
vol is the source volume for the copy
shift is the optional shift applied after copying
Note
This will automatically build an oriented bounding box with an envelope value of (0.05, 0.05, 0.05)mm
virtual Acts::Volume::~Volume () virtual
Destructor.
Member Function Documentation
const Acts::Vector3D Acts::Volume::binningPosition (const GeometryContext & gctx, Acts::BinningValue bValue) const override virtual
The binning position method
as default the center is given, but may be overloaded
Parameters
gctx The current geometry context object, e.g. alignment
bValue is the binning value schema
Returns
vector 3D that can be used for the binning
Implements Acts::GeometryObject.
Definition at line 66 of file Volume.cpp.
View newest version in sPHENIX GitHub at line 66 of file Volume.cpp
References Acts::binR, and Acts::binRPhi.
Referenced by Acts::TrackingVolume::glueTrackingVolume().
Acts::Volume::BoundingBox Acts::Volume::boundingBox (const Vector3D & envelope = {0, 0, 0}) const
Construct bounding box for this shape
Parameters
envelope Optional envelope to add / subtract from min/max
Returns
Constructed bounding box pointing to this volume
Definition at line 101 of file Volume.cpp.
View newest version in sPHENIX GitHub at line 101 of file Volume.cpp
const Vector3D & Acts::Volume::center () const inline
returns the center of the volume
Definition at line 124 of file Volume.hpp.
View newest version in sPHENIX GitHub at line 124 of file Volume.hpp
References m_center.
bool Acts::Volume::inside (const Vector3D & gpos, double tol = 0.) const
Inside() method for checks
Parameters
gpos is the position to be checked
tol is the tolerance parameter
Returns
boolean indicator if the position is inside
Definition at line 88 of file Volume.cpp.
View newest version in sPHENIX GitHub at line 88 of file Volume.cpp
References Acts::Test::transform.
const Transform3D & Acts::Volume::itransform () const inline
Returns the inverted transform of this volume.
Definition at line 120 of file Volume.hpp.
View newest version in sPHENIX GitHub at line 120 of file Volume.hpp
References m_itransform.
Referenced by Acts::TrackingVolume::intersectSearchHierarchy().
Acts::Volume & Acts::Volume::operator= (const Volume & vol)
Assignment operator
Parameters
vol is the source volume to be copied
Definition at line 79 of file Volume.cpp.
View newest version in sPHENIX GitHub at line 79 of file Volume.cpp
References m_center, m_transform, and m_volumeBounds.
const Acts::Volume::BoundingBox & Acts::Volume::orientedBoundingBox () const
Construct oriented bounding box for this shape
Returns
Constructed oriented bounding box pointing to this volume
Definition at line 106 of file Volume.cpp.
View newest version in sPHENIX GitHub at line 106 of file Volume.cpp
Referenced by Acts::Test::BOOST_AUTO_TEST_CASE(), and Acts::TrackingVolume::intersectSearchHierarchy().
const Transform3D & Acts::Volume::transform () const inline
Return methods for geometry transform.
Definition at line 113 of file Volume.hpp.
View newest version in sPHENIX GitHub at line 113 of file Volume.hpp
References m_transform, and Acts::s_idTransform.
const VolumeBounds & Acts::Volume::volumeBounds () const inline
returns the volumeBounds()
Definition at line 128 of file Volume.hpp.
View newest version in sPHENIX GitHub at line 128 of file Volume.hpp
References m_volumeBounds.
Referenced by Acts::adjustBinUtility(), Acts::AbstractVolume::createBoundarySurfaces(), Acts::TrackingVolume::createBoundarySurfaces(), Acts::JsonGeometryConverter::DefaultBin(), and Acts::operator<<().
Member Data Documentation
Vector3D Acts::Volume::m_center protected
Definition at line 108 of file Volume.hpp.
View newest version in sPHENIX GitHub at line 108 of file Volume.hpp
Referenced by center(), and operator=().
Transform3D Acts::Volume::m_itransform protected
Definition at line 107 of file Volume.hpp.
View newest version in sPHENIX GitHub at line 107 of file Volume.hpp
Referenced by itransform().
BoundingBox Acts::Volume::m_orientedBoundingBox protected
Definition at line 110 of file Volume.hpp.
View newest version in sPHENIX GitHub at line 110 of file Volume.hpp
std::shared_ptr<const Transform3D> Acts::Volume::m_transform protected
Definition at line 106 of file Volume.hpp.
View newest version in sPHENIX GitHub at line 106 of file Volume.hpp
Referenced by operator=(), and transform().
VolumeBoundsPtr Acts::Volume::m_volumeBounds protected
Definition at line 109 of file Volume.hpp.
View newest version in sPHENIX GitHub at line 109 of file Volume.hpp
Referenced by operator=(), and volumeBounds().
The documentation for this class was generated from the following files:
fun4all_acts/blob/master/Core/include/Acts/Geometry/Volume.hpp
fun4all_acts/blob/master/Core/src/Geometry/Volume.cpp