EIC Software: PHG4Hit Class Reference
PHG4Hit Class Reference
#include <fun4all_coresoftware/blob/master/simulation/g4simulation/g4main/PHG4Hit.h>
Public Types
enum PROPERTY {
prop_eion = 1, prop_light_yield = 2, scint_gammas = 3, cerenkov_gammas = 4,
prop_px_0 = 10, prop_px_1 = 11, prop_py_0 = 12, prop_py_1 = 13,
prop_pz_0 = 14, prop_pz_1 = 15, prop_path_length = 16, prop_local_x_0 = 20,
prop_local_x_1 = 21, prop_local_y_0 = 22, prop_local_y_1 = 23, prop_local_z_0 = 24,
prop_local_z_1 = 25, prop_layer = 101, prop_scint_id = 102, prop_row = 103,
prop_strip_z_index = 110, prop_strip_y_index = 111, prop_ladder_z_index = 112, prop_ladder_phi_index = 113,
prop_stave_index = 114, prop_half_stave_index = 115, prop_module_index = 116, prop_chip_index = 117,
prop_local_pos_x_0 = 118, prop_local_pos_y_0 = 119, prop_local_pos_z_0 = 120, prop_index_i = 121,
prop_index_j = 122, prop_index_k = 123, prop_index_l = 124, prop_hit_type = 125,
prop_local_pos_x_1 = 128, prop_local_pos_y_1 = 126, prop_local_pos_z_1 = 127, prop_MAX_NUMBER = UCHAR_MAX
}
enum PROPERTY_TYPE { type_int = 1, type_uint = 2, type_float = 3, type_unknown = -1 }
Public Member Functions
PHG4Hit ()
~PHG4Hit () override
void identify (std::ostream &os=std::cout) const override
void CopyFrom (const PHObject *phobj) override
void Reset () override
Clear Event.
virtual float get_x (const int) const
virtual float get_y (const int) const
virtual float get_z (const int) const
virtual float get_px (const int) const
virtual float get_py (const int) const
virtual float get_pz (const int) const
virtual float get_local_x (const int) const
virtual float get_local_y (const int) const
virtual float get_local_z (const int) const
virtual float get_t (const int) const
virtual float get_edep () const
virtual float get_eion () const
virtual float get_light_yield () const
virtual float get_path_length () const
virtual unsigned int get_layer () const
virtual PHG4HitDefs::keytype get_hit_id () const
virtual int get_detid () const
virtual int get_shower_id () const
virtual int get_scint_id () const
virtual int get_row () const
virtual int get_trkid () const
virtual int get_strip_z_index () const
virtual int get_strip_y_index () const
virtual int get_ladder_z_index () const
virtual int get_ladder_phi_index () const
virtual int get_index_i () const
virtual int get_index_j () const
virtual int get_index_k () const
virtual int get_index_l () const
virtual int get_hit_type () const
virtual void set_x (const int, const float)
virtual void set_y (const int, const float)
virtual void set_z (const int, const float)
virtual void set_px (const int, const float)
virtual void set_py (const int, const float)
virtual void set_pz (const int, const float)
virtual void set_local_x (const int, const float)
virtual void set_local_y (const int, const float)
virtual void set_local_z (const int, const float)
virtual void set_t (const int, const float)
virtual void set_edep (const float)
virtual void set_eion (const float)
virtual void set_light_yield (const float)
virtual void set_path_length (const float)
virtual void set_layer (const unsigned int)
virtual void set_hit_id (const PHG4HitDefs::keytype)
virtual void set_shower_id (const int)
virtual void set_scint_id (const int)
virtual void set_row (const int)
virtual void set_trkid (const int)
virtual void set_strip_z_index (const int)
virtual void set_strip_y_index (const int)
virtual void set_ladder_z_index (const int)
virtual void set_ladder_phi_index (const int)
virtual void set_index_i (const int)
virtual void set_index_j (const int)
virtual void set_index_k (const int)
virtual void set_index_l (const int)
virtual void set_hit_type (const int)
virtual float get_avg_x () const
virtual float get_avg_y () const
virtual float get_avg_z () const
virtual float get_avg_t () const
virtual void print () const
virtual bool has_property (const PROPERTY) const
virtual float get_property_float (const PROPERTY) const
virtual int get_property_int (const PROPERTY) const
virtual unsigned int get_property_uint (const PROPERTY) const
virtual void set_property (const PROPERTY, const float)
virtual void set_property (const PROPERTY, const int)
virtual void set_property (const PROPERTY, const unsigned int)
Public Member Functions inherited from PHObject
PHObject ()
ctor
~PHObject () override
dtor
virtual PHObject * CloneMe () const
Virtual copy constructor.
virtual PHObject * clone () const final
PHObject * Clone (const char *newname="") const final
void Copy (TObject &object) const final
virtual int isValid () const
isValid returns non zero if object contains vailid data
virtual int isValid (const float) const
virtual int isValid (const double) const
virtual int isValid (const int) const
virtual int isValid (const unsigned int) const
virtual int isImplemented (const float f) const
virtual int isImplemented (const double f) const
virtual int isImplemented (const int i) const
virtual int isImplemented (const unsigned int i) const
virtual int Integrate () const
virtual int Integrate (PHObject *)
Static Public Member Functions
static std::pair< const
std::string, PROPERTY_TYPE > get_property_info (PROPERTY prop_id)
static bool check_property (const PROPERTY prop_id, const PROPERTY_TYPE prop_type)
static std::string get_property_type (const PROPERTY_TYPE prop_type)
Protected Member Functions
virtual unsigned int get_property_nocheck (const PROPERTY) const
virtual void set_property_nocheck (const PROPERTY, const unsigned int)
Friends
std::ostream & operator<< (std::ostream &stream, const PHG4Hit *hit)
Detailed Description
Definition at line 16 of file PHG4Hit.h.
View newest version in sPHENIX GitHub at line 16 of file PHG4Hit.h
Member Enumeration Documentation
enum PHG4Hit::PROPERTY
Procedure to add a new PROPERTY tag: 1.add new tag below with unique value, 2.add a short name to PHG4Hit::get_property_info
Enumerator:
prop_eion
ionizing energy loss
prop_light_yield
for scintillation detectors, the amount of light produced
scint_gammas
cerenkov_gammas
prop_px_0
momentum
prop_px_1
prop_py_0
prop_py_1
prop_pz_0
prop_pz_1
prop_path_length
pathlength
prop_local_x_0
local coordinate
prop_local_x_1
prop_local_y_0
prop_local_y_1
prop_local_z_0
prop_local_z_1
prop_layer
layer ID
prop_scint_id
scintillator ID
prop_row
row (mother volume or steel plate id)
prop_strip_z_index
SVX stuff.
prop_strip_y_index
prop_ladder_z_index
prop_ladder_phi_index
prop_stave_index
prop_half_stave_index
prop_module_index
prop_chip_index
prop_local_pos_x_0
prop_local_pos_y_0
prop_local_pos_z_0
prop_index_i
generic indexes
prop_index_j
prop_index_k
prop_index_l
prop_hit_type
hit type
prop_local_pos_x_1
prop_local_pos_y_1
prop_local_pos_z_1
prop_MAX_NUMBER
max limit in order to fit into 8 bit unsigned number
Definition at line 100 of file PHG4Hit.h.
View newest version in sPHENIX GitHub at line 100 of file PHG4Hit.h
enum PHG4Hit::PROPERTY_TYPE
Enumerator:
type_int
type_uint
type_float
type_unknown
Definition at line 175 of file PHG4Hit.h.
View newest version in sPHENIX GitHub at line 175 of file PHG4Hit.h
Constructor & Destructor Documentation
PHG4Hit::PHG4Hit () inline
Definition at line 19 of file PHG4Hit.h.
View newest version in sPHENIX GitHub at line 19 of file PHG4Hit.h
PHG4Hit::~PHG4Hit () inline override
Definition at line 20 of file PHG4Hit.h.
View newest version in sPHENIX GitHub at line 20 of file PHG4Hit.h
Member Function Documentation
bool PHG4Hit::check_property (const PROPERTY prop_id, const PROPERTY_TYPE prop_type) static
Definition at line 169 of file PHG4Hit.cc.
View newest version in sPHENIX GitHub at line 169 of file PHG4Hit.cc
void PHG4Hit::CopyFrom (const PHObject * phobj) override virtual
Reimplemented from PHObject.
Reimplemented in PHG4HitEval.
Definition at line 12 of file PHG4Hit.cc.
View newest version in sPHENIX GitHub at line 12 of file PHG4Hit.cc
References get_edep(), get_hit_id(), get_property_nocheck(), get_shower_id(), get_t(), get_trkid(), get_x(), get_y(), get_z(), and has_property().
Referenced by PHG4HitEval::CopyFrom(), and EICG4dRICHHit::EICG4dRICHHit().
float PHG4Hit::get_avg_t () const inline virtual
Definition at line 204 of file PHG4Hit.h.
View newest version in sPHENIX GitHub at line 204 of file PHG4Hit.h
References get_t().
Referenced by SvtxEvaluator::fillOutputNtuples(), PHTruthClustering::LayerClusterG4Hits(), SvtxTruthEval::LayerClusterG4Hits(), QAG4SimulationCalorimeter::process_event_G4Hit(), QAG4SimulationEicCalorimeter::process_event_G4Hit(), PHG4TrackFastSim::PseudoPatternRecognition(), and B0TrackFastSim::PseudoPatternRecognition().
float PHG4Hit::get_avg_x () const inline virtual
Definition at line 201 of file PHG4Hit.h.
View newest version in sPHENIX GitHub at line 201 of file PHG4Hit.h
References get_x().
Referenced by SvtxClusterEval::all_truth_hits_by_nhit(), SvtxEvaluator::fillOutputNtuples(), SvtxClusterEval::gtrackid_and_layer_by_nhit(), PHTruthClustering::LayerClusterG4Hits(), SvtxTruthEval::LayerClusterG4Hits(), CreateCZHitContainer::merge_hits(), operator<<(), PHG4TrackFastSim::PHG4HitToMeasurementCylinder(), B0TrackFastSim::PHG4HitToMeasurementCylinder(), PHG4TrackFastSim::PHG4HitToMeasurementVerticalPlane(), B0TrackFastSim::PHG4HitToMeasurementVerticalPlane(), QAG4SimulationCalorimeter::process_event_G4Hit(), and QAG4SimulationEicCalorimeter::process_event_G4Hit().
float PHG4Hit::get_avg_y () const inline virtual
Definition at line 202 of file PHG4Hit.h.
View newest version in sPHENIX GitHub at line 202 of file PHG4Hit.h
References get_y().
Referenced by SvtxClusterEval::all_truth_hits_by_nhit(), SvtxEvaluator::fillOutputNtuples(), SvtxClusterEval::gtrackid_and_layer_by_nhit(), PHTruthClustering::LayerClusterG4Hits(), SvtxTruthEval::LayerClusterG4Hits(), CreateCZHitContainer::merge_hits(), operator<<(), PHG4TrackFastSim::PHG4HitToMeasurementCylinder(), B0TrackFastSim::PHG4HitToMeasurementCylinder(), PHG4TrackFastSim::PHG4HitToMeasurementVerticalPlane(), B0TrackFastSim::PHG4HitToMeasurementVerticalPlane(), QAG4SimulationCalorimeter::process_event_G4Hit(), and QAG4SimulationEicCalorimeter::process_event_G4Hit().
float PHG4Hit::get_avg_z () const inline virtual
Definition at line 203 of file PHG4Hit.h.
View newest version in sPHENIX GitHub at line 203 of file PHG4Hit.h
References get_z().
Referenced by SvtxClusterEval::all_truth_hits_by_nhit(), SvtxEvaluator::fillOutputNtuples(), SvtxClusterEval::gtrackid_and_layer_by_nhit(), PHTruthClustering::LayerClusterG4Hits(), SvtxTruthEval::LayerClusterG4Hits(), operator<<(), PHG4TrackFastSim::PHG4HitToMeasurementCylinder(), B0TrackFastSim::PHG4HitToMeasurementCylinder(), PHG4TrackFastSim::PHG4HitToMeasurementVerticalPlane(), B0TrackFastSim::PHG4HitToMeasurementVerticalPlane(), QAG4SimulationEicCalorimeter::process_event_G4Hit(), and QAG4SimulationCalorimeter::process_event_G4Hit().
virtual int PHG4Hit::get_detid () const inline virtual
Reimplemented in EICG4dRICHHit, and PHG4Hitv1.
Definition at line 44 of file PHG4Hit.h.
View newest version in sPHENIX GitHub at line 44 of file PHG4Hit.h
Referenced by EvalHit::EvalHit().
virtual float PHG4Hit::get_edep () const inline virtual
Reimplemented in EICG4dRICHHit, and PHG4Hitv1.
Definition at line 38 of file PHG4Hit.h.
View newest version in sPHENIX GitHub at line 38 of file PHG4Hit.h
Referenced by CopyFrom(), EvalHit::EvalHit(), SvtxEvaluator::fillOutputNtuples(), SvtxHitEval::get_energy_contribution(), SvtxClusterEval::get_energy_contribution(), PHTruthClustering::LayerClusterG4Hits(), SvtxTruthEval::LayerClusterG4Hits(), SvtxHitEval::max_truth_hit_by_energy(), SvtxClusterEval::max_truth_hit_by_energy(), G4HitTTree::process_event(), B0RawTowerBuilderByHitIndex::process_event(), BwdRawTowerBuilderByHitIndex::process_event(), RawTowerBuilderDRCALO::process_event(), RawTowerBuilderByHitIndex::process_event(), RawTowerBuilderByHitIndexBECAL::process_event(), RawTowerBuilderByHitIndexLHCal::process_event(), EICG4ZDCRawTowerBuilderByHitIndex::process_event(), RawDigitBuilderTTL::process_event(), QAG4SimulationCalorimeter::process_event_G4Hit(), QAG4SimulationEicCalorimeter::process_event_G4Hit(), PHG4TruthEventAction::ProcessShowers(), PHG4HitContainer::RemoveZeroEDep(), PHG4SectorSteppingAction::UserSteppingAction(), PHG4EnvelopeSteppingAction::UserSteppingAction(), PHG4ConeSteppingAction::UserSteppingAction(), PHG4EICMvtxSteppingAction::UserSteppingAction(), PHG4TpcSteppingAction::UserSteppingAction(), PHG4MvtxSteppingAction::UserSteppingAction(), PHG4FPbScRegionSteppingAction::UserSteppingAction(), PHG4BlockSteppingAction::UserSteppingAction(), PHG4CylinderStripSteppingAction::UserSteppingAction(), PHG4HcalSteppingAction::UserSteppingAction(), PHG4InnerHcalSteppingAction::UserSteppingAction(), PHG4CEmcTestBeamSteppingAction::UserSteppingAction(), PHG4OuterHcalSteppingAction::UserSteppingAction(), PHG4InttSteppingAction::UserSteppingAction(), PHG4EPDSteppingAction::UserSteppingAction(), PHG4BarrelEcalSteppingAction::UserSteppingAction(), PHG4LFHcalSteppingAction::UserSteppingAction(), PHG4ForwardDualReadoutSteppingAction::UserSteppingAction(), PHG4ECAPToFSteppingAction::UserSteppingAction(), PHG4HybridHomogeneousCalorimeterSteppingAction::UserSteppingAction(), PHG4BackwardHcalSteppingAction::UserSteppingAction(), PHG4mRICHSteppingAction::UserSteppingAction(), PHG4CrystalCalorimeterSteppingAction::UserSteppingAction(), PHG4ForwardEcalSteppingAction::UserSteppingAction(), PHG4CylinderSteppingAction::UserSteppingAction(), EICG4RPSteppingAction::UserSteppingAction(), PHG4ForwardHcalSteppingAction::UserSteppingAction(), PHG4TRDSteppingAction::UserSteppingAction(), G4EicDircSteppingAction::UserSteppingAction(), PHG4ZDCSteppingAction::UserSteppingAction(), EICG4B0SteppingAction::UserSteppingAction(), EICG4B0ECALSteppingAction::UserSteppingAction(), EICG4BwdSteppingAction::UserSteppingAction(), EICG4LumiSteppingAction::UserSteppingAction(), PHG4SpacalSteppingAction::UserSteppingAction(), and PHG4TTLSteppingAction::UserSteppingAction().
virtual float PHG4Hit::get_eion () const inline virtual
Reimplemented in PHG4Hitv1, and PHG4HitEval.
Definition at line 39 of file PHG4Hit.h.
View newest version in sPHENIX GitHub at line 39 of file PHG4Hit.h
Referenced by PHG4HitEval::CopyFrom(), EvalHit::EvalHit(), PHG4MicromegasHitReco::get_primary_electrons(), CreateCZHitContainer::merge_hits(), G4HitTTree::process_event(), PHG4TruthEventAction::ProcessShowers(), PHG4TpcSteppingAction::UserSteppingAction(), PHG4SectorSteppingAction::UserSteppingAction(), PHG4EnvelopeSteppingAction::UserSteppingAction(), PHG4CEmcTestBeamSteppingAction::UserSteppingAction(), PHG4BlockSteppingAction::UserSteppingAction(), PHG4HcalSteppingAction::UserSteppingAction(), PHG4EPDSteppingAction::UserSteppingAction(), PHG4CylinderStripSteppingAction::UserSteppingAction(), PHG4InnerHcalSteppingAction::UserSteppingAction(), PHG4InttSteppingAction::UserSteppingAction(), PHG4OuterHcalSteppingAction::UserSteppingAction(), PHG4BarrelEcalSteppingAction::UserSteppingAction(), PHG4LFHcalSteppingAction::UserSteppingAction(), PHG4HybridHomogeneousCalorimeterSteppingAction::UserSteppingAction(), PHG4ECAPToFSteppingAction::UserSteppingAction(), PHG4CrystalCalorimeterSteppingAction::UserSteppingAction(), PHG4ForwardDualReadoutSteppingAction::UserSteppingAction(), PHG4BackwardHcalSteppingAction::UserSteppingAction(), PHG4ForwardEcalSteppingAction::UserSteppingAction(), PHG4mRICHSteppingAction::UserSteppingAction(), EICG4RPSteppingAction::UserSteppingAction(), PHG4ForwardHcalSteppingAction::UserSteppingAction(), PHG4CylinderSteppingAction::UserSteppingAction(), PHG4TRDSteppingAction::UserSteppingAction(), PHG4ZDCSteppingAction::UserSteppingAction(), G4EicDircSteppingAction::UserSteppingAction(), EICG4B0ECALSteppingAction::UserSteppingAction(), EICG4B0SteppingAction::UserSteppingAction(), EICG4BwdSteppingAction::UserSteppingAction(), EICG4LumiSteppingAction::UserSteppingAction(), PHG4SpacalSteppingAction::UserSteppingAction(), and PHG4TTLSteppingAction::UserSteppingAction().
virtual PHG4HitDefs::keytype PHG4Hit::get_hit_id () const inline virtual
Reimplemented in EICG4dRICHHit, and PHG4Hitv1.
Definition at line 43 of file PHG4Hit.h.
View newest version in sPHENIX GitHub at line 43 of file PHG4Hit.h
Referenced by PHG4HitContainer::AddHit(), SvtxClusterEval::all_clusters_from(), SvtxHitEval::all_hits_from(), CopyFrom(), SvtxEvaluator::fillOutputNtuples(), SvtxHitEval::get_energy_contribution(), SvtxClusterEval::get_energy_contribution(), PHG4RICHSteppingAction::MakeHit(), operator<<(), SvtxEvaluator::printOutputInfo(), PHG4DSTReader::process_event(), PHG4TrackFastSim::PseudoPatternRecognition(), B0TrackFastSim::PseudoPatternRecognition(), SvtxClusterEval::reco_cluster_from_truth_cluster(), PHG4FPbScSteppingAction::UserSteppingAction(), PHG4FCalSteppingAction::UserSteppingAction(), PHG4TpcSteppingAction::UserSteppingAction(), G4Example01SteppingAction::UserSteppingAction(), PHG4ConeSteppingAction::UserSteppingAction(), PHG4EnvelopeSteppingAction::UserSteppingAction(), PHG4SectorSteppingAction::UserSteppingAction(), PHG4EICMvtxSteppingAction::UserSteppingAction(), PHG4MvtxSteppingAction::UserSteppingAction(), G4Example03SteppingAction::UserSteppingAction(), G4Example02SteppingAction::UserSteppingAction(), PHG4FPbScRegionSteppingAction::UserSteppingAction(), PHG4PSTOFSteppingAction::UserSteppingAction(), G4JLeicBeamLineMagnetSteppingAction::UserSteppingAction(), G4JLeicDIRCSteppingAction::UserSteppingAction(), G4JLeicVTXSteppingAction::UserSteppingAction(), G4LBLVtxSteppingAction::UserSteppingAction(), PHG4BlockSteppingAction::UserSteppingAction(), EicFRichSteppingAction::UserSteppingAction(), GdmlImportDetectorSteppingAction::UserSteppingAction(), PHG4HcalSteppingAction::UserSteppingAction(), PHG4CylinderStripSteppingAction::UserSteppingAction(), BeastMagnetSteppingAction::UserSteppingAction(), PHG4InnerHcalSteppingAction::UserSteppingAction(), PHG4CEmcTestBeamSteppingAction::UserSteppingAction(), PHG4OuterHcalSteppingAction::UserSteppingAction(), AllSi_Al_support_SteppingAction::UserSteppingAction(), PHG4InttSteppingAction::UserSteppingAction(), AllSiliconTrackerSteppingAction::UserSteppingAction(), PHG4EPDSteppingAction::UserSteppingAction(), BeamLineMagnetSteppingAction::UserSteppingAction(), PHG4BarrelEcalSteppingAction::UserSteppingAction(), EICG4ZDCSteppingAction::UserSteppingAction(), PHG4BbcSteppingAction::UserSteppingAction(), PHG4HybridHomogeneousCalorimeterSteppingAction::UserSteppingAction(), PHG4ECAPToFSteppingAction::UserSteppingAction(), PHG4LFHcalSteppingAction::UserSteppingAction(), PHG4mRICHSteppingAction::UserSteppingAction(), PHG4TpcEndCapSteppingAction::UserSteppingAction(), PHG4ForwardDualReadoutSteppingAction::UserSteppingAction(), PHG4BackwardHcalSteppingAction::UserSteppingAction(), PHG4ForwardEcalSteppingAction::UserSteppingAction(), PHG4CrystalCalorimeterSteppingAction::UserSteppingAction(), PHG4ForwardHcalSteppingAction::UserSteppingAction(), PHG4CylinderSteppingAction::UserSteppingAction(), EICG4RPSteppingAction::UserSteppingAction(), PHG4TRDSteppingAction::UserSteppingAction(), PHG4ZDCSteppingAction::UserSteppingAction(), EICG4B0ECALSteppingAction::UserSteppingAction(), EICG4B0SteppingAction::UserSteppingAction(), EICG4BwdSteppingAction::UserSteppingAction(), PHG4SpacalSteppingAction::UserSteppingAction(), EICG4LumiSteppingAction::UserSteppingAction(), and PHG4TTLSteppingAction::UserSteppingAction().
virtual int PHG4Hit::get_hit_type () const inline virtual
Reimplemented in PHG4Hitv1.
Definition at line 57 of file PHG4Hit.h.
View newest version in sPHENIX GitHub at line 57 of file PHG4Hit.h
Referenced by CreateCZHitContainer::merge_hits(), and EICG4ZDCRawTowerBuilderByHitIndex::process_event().
virtual int PHG4Hit::get_index_i () const inline virtual
Reimplemented in PHG4Hitv1.
Definition at line 53 of file PHG4Hit.h.
View newest version in sPHENIX GitHub at line 53 of file PHG4Hit.h
Referenced by EICG4ZDCRawTowerBuilderByHitIndex::process_event().
virtual int PHG4Hit::get_index_j () const inline virtual
Reimplemented in PHG4Hitv1.
Definition at line 54 of file PHG4Hit.h.
View newest version in sPHENIX GitHub at line 54 of file PHG4Hit.h
Referenced by RawTowerBuilderByHitIndex::process_event(), EICG4ZDCRawTowerBuilderByHitIndex::process_event(), B0RawTowerBuilderByHitIndex::process_event(), RawTowerBuilderByHitIndexLHCal::process_event(), RawTowerBuilderByHitIndexBECAL::process_event(), RawTowerBuilderDRCALO::process_event(), BwdRawTowerBuilderByHitIndex::process_event(), and RawDigitBuilderTTL::process_event().
virtual int PHG4Hit::get_index_k () const inline virtual
Reimplemented in PHG4Hitv1.
Definition at line 55 of file PHG4Hit.h.
View newest version in sPHENIX GitHub at line 55 of file PHG4Hit.h
Referenced by RawTowerBuilderByHitIndex::process_event(), RawTowerBuilderByHitIndexLHCal::process_event(), RawTowerBuilderByHitIndexBECAL::process_event(), RawTowerBuilderDRCALO::process_event(), BwdRawTowerBuilderByHitIndex::process_event(), and B0RawTowerBuilderByHitIndex::process_event().
virtual int PHG4Hit::get_index_l () const inline virtual
Reimplemented in PHG4Hitv1.
Definition at line 56 of file PHG4Hit.h.
View newest version in sPHENIX GitHub at line 56 of file PHG4Hit.h
Referenced by RawTowerBuilderByHitIndexLHCal::process_event().
virtual int PHG4Hit::get_ladder_phi_index () const inline virtual
Reimplemented in PHG4Hitv1.
Definition at line 52 of file PHG4Hit.h.
View newest version in sPHENIX GitHub at line 52 of file PHG4Hit.h
virtual int PHG4Hit::get_ladder_z_index () const inline virtual
Reimplemented in PHG4Hitv1.
Definition at line 51 of file PHG4Hit.h.
View newest version in sPHENIX GitHub at line 51 of file PHG4Hit.h
virtual unsigned int PHG4Hit::get_layer () const inline virtual
Reimplemented in PHG4Hitv1.
Definition at line 42 of file PHG4Hit.h.
View newest version in sPHENIX GitHub at line 42 of file PHG4Hit.h
Referenced by SvtxHitEval::all_hits_from(), SvtxClusterEval::all_truth_hits_by_nhit(), SvtxEvaluator::fillOutputNtuples(), PHG4HitContainer::findOrAddHit(), SvtxClusterEval::gtrackid_and_layer_by_nhit(), PHTruthClustering::LayerClusterG4Hits(), SvtxTruthEval::LayerClusterG4Hits(), CreateCZHitContainer::merge_hits(), operator<<(), SvtxEvaluator::printOutputInfo(), MomentumEvaluator::process_event(), and EICG4ZDCRawTowerBuilderByHitIndex::process_event().
virtual float PHG4Hit::get_light_yield () const inline virtual
Reimplemented in PHG4Hitv1, and PHG4HitEval.
Definition at line 40 of file PHG4Hit.h.
View newest version in sPHENIX GitHub at line 40 of file PHG4Hit.h
Referenced by PHG4HitEval::CopyFrom(), EvalHit::EvalHit(), RawTowerBuilderByHitIndex::process_event(), BwdRawTowerBuilderByHitIndex::process_event(), EICG4ZDCRawTowerBuilderByHitIndex::process_event(), RawTowerBuilderDRCALO::process_event(), B0RawTowerBuilderByHitIndex::process_event(), RawTowerBuilderByHitIndexBECAL::process_event(), RawTowerBuilderByHitIndexLHCal::process_event(), QAG4SimulationCalorimeter::process_event_G4Hit(), QAG4SimulationEicCalorimeter::process_event_G4Hit(), PHG4TruthEventAction::ProcessShowers(), PHG4CylinderStripSteppingAction::UserSteppingAction(), PHG4HcalSteppingAction::UserSteppingAction(), PHG4EPDSteppingAction::UserSteppingAction(), PHG4InnerHcalSteppingAction::UserSteppingAction(), PHG4OuterHcalSteppingAction::UserSteppingAction(), PHG4BarrelEcalSteppingAction::UserSteppingAction(), PHG4BackwardHcalSteppingAction::UserSteppingAction(), PHG4ForwardEcalSteppingAction::UserSteppingAction(), PHG4LFHcalSteppingAction::UserSteppingAction(), PHG4ForwardDualReadoutSteppingAction::UserSteppingAction(), PHG4CrystalCalorimeterSteppingAction::UserSteppingAction(), PHG4HybridHomogeneousCalorimeterSteppingAction::UserSteppingAction(), PHG4ForwardHcalSteppingAction::UserSteppingAction(), EICG4RPSteppingAction::UserSteppingAction(), PHG4CylinderSteppingAction::UserSteppingAction(), PHG4ZDCSteppingAction::UserSteppingAction(), EICG4B0SteppingAction::UserSteppingAction(), EICG4BwdSteppingAction::UserSteppingAction(), EICG4B0ECALSteppingAction::UserSteppingAction(), EICG4LumiSteppingAction::UserSteppingAction(), and PHG4SpacalSteppingAction::UserSteppingAction().
virtual float PHG4Hit::get_local_x (const int) const inline virtual
Reimplemented in PHG4Hitv1.
Definition at line 34 of file PHG4Hit.h.
View newest version in sPHENIX GitHub at line 34 of file PHG4Hit.h
Referenced by RawDigitBuilderTTL::process_event().
virtual float PHG4Hit::get_local_y (const int) const inline virtual
Reimplemented in PHG4Hitv1.
Definition at line 35 of file PHG4Hit.h.
View newest version in sPHENIX GitHub at line 35 of file PHG4Hit.h
Referenced by RawDigitBuilderTTL::process_event().
virtual float PHG4Hit::get_local_z (const int) const inline virtual
Reimplemented in PHG4Hitv1.
Definition at line 36 of file PHG4Hit.h.
View newest version in sPHENIX GitHub at line 36 of file PHG4Hit.h
Referenced by RawDigitBuilderTTL::process_event().
virtual float PHG4Hit::get_path_length () const inline virtual
Reimplemented in PHG4HitEval, and PHG4Hitv1.
Definition at line 41 of file PHG4Hit.h.
View newest version in sPHENIX GitHub at line 41 of file PHG4Hit.h
Referenced by PHG4HitEval::CopyFrom(), and SvtxEvaluator::fillOutputNtuples().
virtual float PHG4Hit::get_property_float (const PROPERTY) const inline virtual
Reimplemented in PHG4Hitv1.
Definition at line 184 of file PHG4Hit.h.
View newest version in sPHENIX GitHub at line 184 of file PHG4Hit.h
Referenced by RawTowerBuilderDRCALO::process_event(), and PHG4ForwardDualReadoutSteppingAction::UserSteppingAction().
std::pair< const std::string, PHG4Hit::PROPERTY_TYPE > PHG4Hit::get_property_info (PROPERTY prop_id) static
Definition at line 77 of file PHG4Hit.cc.
View newest version in sPHENIX GitHub at line 77 of file PHG4Hit.cc
References exit(), type_float, type_int, and type_uint.
Referenced by DumpPHG4HitContainer::process_Node().
virtual int PHG4Hit::get_property_int (const PROPERTY) const inline virtual
Reimplemented in PHG4Hitv1.
Definition at line 185 of file PHG4Hit.h.
View newest version in sPHENIX GitHub at line 185 of file PHG4Hit.h
virtual unsigned int PHG4Hit::get_property_nocheck (const PROPERTY) const inline protected virtual
Reimplemented in PHG4Hitv1.
Definition at line 195 of file PHG4Hit.h.
View newest version in sPHENIX GitHub at line 195 of file PHG4Hit.h
Referenced by CopyFrom().
string PHG4Hit::get_property_type (const PROPERTY_TYPE prop_type) static
Definition at line 180 of file PHG4Hit.cc.
View newest version in sPHENIX GitHub at line 180 of file PHG4Hit.cc
virtual unsigned int PHG4Hit::get_property_uint (const PROPERTY) const inline virtual
Reimplemented in PHG4Hitv1.
Definition at line 186 of file PHG4Hit.h.
View newest version in sPHENIX GitHub at line 186 of file PHG4Hit.h
virtual float PHG4Hit::get_px (const int) const inline virtual
Reimplemented in PHG4Hitv1.
Definition at line 31 of file PHG4Hit.h.
View newest version in sPHENIX GitHub at line 31 of file PHG4Hit.h
Referenced by SvtxEvaluator::fillOutputNtuples().
virtual float PHG4Hit::get_py (const int) const inline virtual
Reimplemented in PHG4Hitv1.
Definition at line 32 of file PHG4Hit.h.
View newest version in sPHENIX GitHub at line 32 of file PHG4Hit.h
Referenced by SvtxEvaluator::fillOutputNtuples().
virtual float PHG4Hit::get_pz (const int) const inline virtual
Reimplemented in PHG4Hitv1.
Definition at line 33 of file PHG4Hit.h.
View newest version in sPHENIX GitHub at line 33 of file PHG4Hit.h
Referenced by SvtxEvaluator::fillOutputNtuples().
virtual int PHG4Hit::get_row () const inline virtual
Reimplemented in PHG4Hitv1.
Definition at line 47 of file PHG4Hit.h.
View newest version in sPHENIX GitHub at line 47 of file PHG4Hit.h
virtual int PHG4Hit::get_scint_id () const inline virtual
Reimplemented in PHG4Hitv1, and PHG4HitEval.
Definition at line 46 of file PHG4Hit.h.
View newest version in sPHENIX GitHub at line 46 of file PHG4Hit.h
Referenced by PHG4HitEval::CopyFrom().
virtual int PHG4Hit::get_shower_id () const inline virtual
Reimplemented in EICG4dRICHHit, and PHG4Hitv1.
Definition at line 45 of file PHG4Hit.h.
View newest version in sPHENIX GitHub at line 45 of file PHG4Hit.h
Referenced by CopyFrom(), BaseTruthEval::get_primary_shower(), BaseTruthEval::is_g4hit_from_primary_shower(), RawTowerBuilderByHitIndexBECAL::process_event(), RawTowerBuilderDRCALO::process_event(), BwdRawTowerBuilderByHitIndex::process_event(), B0RawTowerBuilderByHitIndex::process_event(), RawTowerBuilderByHitIndex::process_event(), RawTowerBuilderByHitIndexLHCal::process_event(), and EICG4ZDCRawTowerBuilderByHitIndex::process_event().
virtual int PHG4Hit::get_strip_y_index () const inline virtual
Reimplemented in PHG4Hitv1.
Definition at line 50 of file PHG4Hit.h.
View newest version in sPHENIX GitHub at line 50 of file PHG4Hit.h
Referenced by RawDigitBuilderTTL::process_event().
virtual int PHG4Hit::get_strip_z_index () const inline virtual
Reimplemented in PHG4Hitv1.
Definition at line 49 of file PHG4Hit.h.
View newest version in sPHENIX GitHub at line 49 of file PHG4Hit.h
Referenced by RawDigitBuilderTTL::process_event().
virtual float PHG4Hit::get_t (const int) const inline virtual
Reimplemented in EICG4dRICHHit, and PHG4Hitv1.
Definition at line 37 of file PHG4Hit.h.
View newest version in sPHENIX GitHub at line 37 of file PHG4Hit.h
Referenced by CopyFrom(), EvalHit::EvalHit(), get_avg_t(), CreateCZHitContainer::merge_hits(), and PHG4MicromegasHitReco::process_event().
virtual int PHG4Hit::get_trkid () const inline virtual
Reimplemented in PHG4Hitv1, and EICG4dRICHHit.
Definition at line 48 of file PHG4Hit.h.
View newest version in sPHENIX GitHub at line 48 of file PHG4Hit.h
Referenced by SvtxClusterEval::all_clusters_from(), SvtxHitEval::all_hits_from(), SvtxTrackEval::all_tracks_from(), PHTruthClustering::all_truth_hits(), CopyFrom(), EvalHit::EvalHit(), SvtxEvaluator::fillOutputNtuples(), SvtxTruthEval::FillTruthHitsFromParticleCache(), BaseTruthEval::get_particle(), PHTruthSiliconAssociation::getG4PrimaryParticle(), PHTruthSiliconAssociation::getSiliconClustersFromParticle(), SvtxClusterEval::gtrackid_and_layer_by_nhit(), BaseTruthEval::is_g4hit_from_particle(), CreateCZHitContainer::merge_hits(), operator<<(), SvtxEvaluator::printOutputInfo(), PHSiliconTruthTrackSeeding::Process(), MomentumEvaluator::process_event(), PHG4DstCompressReco::process_event(), PHG4DSTReader::process_event(), QAG4SimulationEicCalorimeter::process_event_G4Hit(), QAG4SimulationCalorimeter::process_event_G4Hit(), PHG4TruthEventAction::ProcessShowers(), PHG4TrackFastSim::PseudoPatternRecognition(), B0TrackFastSim::PseudoPatternRecognition(), and SvtxClusterEval::reco_cluster_from_truth_cluster().
virtual float PHG4Hit::get_x (const int) const inline virtual
Reimplemented in EICG4dRICHHit, and PHG4Hitv1.
Definition at line 28 of file PHG4Hit.h.
View newest version in sPHENIX GitHub at line 28 of file PHG4Hit.h
Referenced by CylinderGeomMicromegas::convert_to_planar(), CopyFrom(), EvalHit::EvalHit(), SvtxEvaluator::fillOutputNtuples(), get_avg_x(), SvtxTruthEval::get_innermost_truth_hit(), SvtxTruthEval::get_outermost_truth_hit(), PHG4TpcCentralMembrane::GetPHG4HitFromStripe(), PHTruthClustering::LayerClusterG4Hits(), SvtxTruthEval::LayerClusterG4Hits(), CreateCZHitContainer::merge_hits(), SvtxEvaluator::printOutputInfo(), PHG4MicromegasHitReco::process_event(), PHG4TruthEventAction::ProcessShowers(), PHG4TpcSteppingAction::UserSteppingAction(), G4Example01SteppingAction::UserSteppingAction(), PHG4PSTOFSteppingAction::UserSteppingAction(), G4JLeicBeamLineMagnetSteppingAction::UserSteppingAction(), G4JLeicDIRCSteppingAction::UserSteppingAction(), G4JLeicVTXSteppingAction::UserSteppingAction(), G4Example02SteppingAction::UserSteppingAction(), G4LBLVtxSteppingAction::UserSteppingAction(), G4Example03SteppingAction::UserSteppingAction(), PHG4OuterHcalSteppingAction::UserSteppingAction(), PHG4InnerHcalSteppingAction::UserSteppingAction(), AllSi_Al_support_SteppingAction::UserSteppingAction(), AllSiliconTrackerSteppingAction::UserSteppingAction(), PHG4BlockSteppingAction::UserSteppingAction(), EicFRichSteppingAction::UserSteppingAction(), PHG4CylinderStripSteppingAction::UserSteppingAction(), BeastMagnetSteppingAction::UserSteppingAction(), GdmlImportDetectorSteppingAction::UserSteppingAction(), EICG4ZDCSteppingAction::UserSteppingAction(), BeamLineMagnetSteppingAction::UserSteppingAction(), PHG4BbcSteppingAction::UserSteppingAction(), PHG4TpcEndCapSteppingAction::UserSteppingAction(), PHG4mRICHSteppingAction::UserSteppingAction(), EICG4RPSteppingAction::UserSteppingAction(), PHG4CylinderSteppingAction::UserSteppingAction(), G4EicDircSteppingAction::UserSteppingAction(), EICG4B0ECALSteppingAction::UserSteppingAction(), EICG4B0SteppingAction::UserSteppingAction(), EICG4BwdSteppingAction::UserSteppingAction(), EICG4LumiSteppingAction::UserSteppingAction(), and PHG4SpacalSteppingAction::UserSteppingAction().
virtual float PHG4Hit::get_y (const int) const inline virtual
Reimplemented in EICG4dRICHHit, and PHG4Hitv1.
Definition at line 29 of file PHG4Hit.h.
View newest version in sPHENIX GitHub at line 29 of file PHG4Hit.h
Referenced by CylinderGeomMicromegas::convert_to_planar(), CopyFrom(), EvalHit::EvalHit(), SvtxEvaluator::fillOutputNtuples(), get_avg_y(), SvtxTruthEval::get_innermost_truth_hit(), SvtxTruthEval::get_outermost_truth_hit(), PHG4TpcCentralMembrane::GetPHG4HitFromStripe(), PHTruthClustering::LayerClusterG4Hits(), SvtxTruthEval::LayerClusterG4Hits(), CreateCZHitContainer::merge_hits(), SvtxEvaluator::printOutputInfo(), PHG4MicromegasHitReco::process_event(), PHG4TruthEventAction::ProcessShowers(), and PHG4TpcSteppingAction::UserSteppingAction().
virtual float PHG4Hit::get_z (const int) const inline virtual
Reimplemented in EICG4dRICHHit, and PHG4Hitv1.
Definition at line 30 of file PHG4Hit.h.
View newest version in sPHENIX GitHub at line 30 of file PHG4Hit.h
Referenced by CylinderGeomMicromegas::convert_to_planar(), CopyFrom(), EvalHit::EvalHit(), SvtxEvaluator::fillOutputNtuples(), get_avg_z(), PHG4TpcCentralMembrane::GetPHG4HitFromStripe(), PHTruthClustering::LayerClusterG4Hits(), SvtxTruthEval::LayerClusterG4Hits(), CreateCZHitContainer::merge_hits(), SvtxEvaluator::printOutputInfo(), MomentumEvaluator::process_event(), PHG4MicromegasHitReco::process_event(), PHG4TruthEventAction::ProcessShowers(), PHG4TpcSteppingAction::UserSteppingAction(), PHG4HcalSteppingAction::UserSteppingAction(), PHG4CylinderStripSteppingAction::UserSteppingAction(), PHG4CylinderSteppingAction::UserSteppingAction(), EICG4BwdSteppingAction::UserSteppingAction(), EICG4B0SteppingAction::UserSteppingAction(), EICG4B0ECALSteppingAction::UserSteppingAction(), EICG4LumiSteppingAction::UserSteppingAction(), and PHG4SpacalSteppingAction::UserSteppingAction().
virtual bool PHG4Hit::has_property (const PROPERTY) const inline virtual
Reimplemented in PHG4Hitv1.
Definition at line 183 of file PHG4Hit.h.
View newest version in sPHENIX GitHub at line 183 of file PHG4Hit.h
Referenced by CopyFrom().
void PHG4Hit::identify (std::ostream & os = std::cout) const override virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from PHObject.
Reimplemented in PHG4Hitv1.
Definition at line 42 of file PHG4Hit.cc.
View newest version in sPHENIX GitHub at line 42 of file PHG4Hit.cc
Referenced by SvtxEvaluator::printInputInfo(), SvtxEvaluator::printOutputInfo(), QAG4SimulationCalorimeter::process_event_G4Hit(), QAG4SimulationEicCalorimeter::process_event_G4Hit(), PHG4TrackFastSim::PseudoPatternRecognition(), B0TrackFastSim::PseudoPatternRecognition(), PHG4HcalSteppingAction::UserSteppingAction(), and PHG4SpacalSteppingAction::UserSteppingAction().
virtual void PHG4Hit::print (void) const inline virtual
Reimplemented in EICG4dRICHHit, and PHG4Hitv1.
Definition at line 94 of file PHG4Hit.h.
View newest version in sPHENIX GitHub at line 94 of file PHG4Hit.h
Referenced by PHG4EICMvtxSteppingAction::UserSteppingAction(), PHG4MvtxSteppingAction::UserSteppingAction(), and PHG4InttSteppingAction::UserSteppingAction().
void PHG4Hit::Reset () override virtual
Clear Event.
Reimplemented from PHObject.
Reimplemented in EICG4dRICHHit, and PHG4Hitv1.
Definition at line 70 of file PHG4Hit.cc.
View newest version in sPHENIX GitHub at line 70 of file PHG4Hit.cc
Referenced by PHG4ConeSteppingAction::UserSteppingAction(), PHG4SectorSteppingAction::UserSteppingAction(), PHG4EICMvtxSteppingAction::UserSteppingAction(), PHG4MvtxSteppingAction::UserSteppingAction(), PHG4TpcSteppingAction::UserSteppingAction(), G4Example01SteppingAction::UserSteppingAction(), G4JLeicBeamLineMagnetSteppingAction::UserSteppingAction(), G4JLeicDIRCSteppingAction::UserSteppingAction(), G4JLeicVTXSteppingAction::UserSteppingAction(), PHG4PSTOFSteppingAction::UserSteppingAction(), G4LBLVtxSteppingAction::UserSteppingAction(), G4Example03SteppingAction::UserSteppingAction(), G4Example02SteppingAction::UserSteppingAction(), PHG4InnerHcalSteppingAction::UserSteppingAction(), PHG4OuterHcalSteppingAction::UserSteppingAction(), AllSi_Al_support_SteppingAction::UserSteppingAction(), AllSiliconTrackerSteppingAction::UserSteppingAction(), PHG4BlockSteppingAction::UserSteppingAction(), EicFRichSteppingAction::UserSteppingAction(), GdmlImportDetectorSteppingAction::UserSteppingAction(), PHG4CylinderStripSteppingAction::UserSteppingAction(), BeastMagnetSteppingAction::UserSteppingAction(), PHG4HcalSteppingAction::UserSteppingAction(), PHG4EPDSteppingAction::UserSteppingAction(), PHG4InttSteppingAction::UserSteppingAction(), BeamLineMagnetSteppingAction::UserSteppingAction(), EICG4ZDCSteppingAction::UserSteppingAction(), PHG4BarrelEcalSteppingAction::UserSteppingAction(), PHG4BbcSteppingAction::UserSteppingAction(), PHG4LFHcalSteppingAction::UserSteppingAction(), PHG4ECAPToFSteppingAction::UserSteppingAction(), PHG4TpcEndCapSteppingAction::UserSteppingAction(), PHG4HybridHomogeneousCalorimeterSteppingAction::UserSteppingAction(), PHG4mRICHSteppingAction::UserSteppingAction(), PHG4BackwardHcalSteppingAction::UserSteppingAction(), PHG4ForwardDualReadoutSteppingAction::UserSteppingAction(), PHG4CrystalCalorimeterSteppingAction::UserSteppingAction(), PHG4ForwardEcalSteppingAction::UserSteppingAction(), PHG4CylinderSteppingAction::UserSteppingAction(), PHG4ForwardHcalSteppingAction::UserSteppingAction(), EICG4RPSteppingAction::UserSteppingAction(), PHG4TRDSteppingAction::UserSteppingAction(), PHG4ZDCSteppingAction::UserSteppingAction(), G4EicDircSteppingAction::UserSteppingAction(), EICG4BwdSteppingAction::UserSteppingAction(), EICG4B0SteppingAction::UserSteppingAction(), EICG4B0ECALSteppingAction::UserSteppingAction(), PHG4SpacalSteppingAction::UserSteppingAction(), EICG4LumiSteppingAction::UserSteppingAction(), and PHG4TTLSteppingAction::UserSteppingAction().
virtual void PHG4Hit::set_edep (const float) inline virtual
Reimplemented in EICG4dRICHHit, and PHG4Hitv1.
Definition at line 69 of file PHG4Hit.h.
View newest version in sPHENIX GitHub at line 69 of file PHG4Hit.h
Referenced by PHG4HitContainer::findOrAddHit(), PHG4TpcCentralMembrane::GetPHG4HitFromStripe(), PHG4RICHSteppingAction::MakeHit(), PHG4GenHit::process_event(), PHG4FPbScSteppingAction::UserSteppingAction(), PHG4FCalSteppingAction::UserSteppingAction(), PHG4ConeSteppingAction::UserSteppingAction(), PHG4EnvelopeSteppingAction::UserSteppingAction(), PHG4MvtxSteppingAction::UserSteppingAction(), PHG4EICMvtxSteppingAction::UserSteppingAction(), PHG4SectorSteppingAction::UserSteppingAction(), PHG4TpcSteppingAction::UserSteppingAction(), G4Example01SteppingAction::UserSteppingAction(), PHG4FPbScRegionSteppingAction::UserSteppingAction(), G4Example02SteppingAction::UserSteppingAction(), G4JLeicBeamLineMagnetSteppingAction::UserSteppingAction(), G4JLeicDIRCSteppingAction::UserSteppingAction(), G4JLeicVTXSteppingAction::UserSteppingAction(), G4LBLVtxSteppingAction::UserSteppingAction(), PHG4PSTOFSteppingAction::UserSteppingAction(), G4Example03SteppingAction::UserSteppingAction(), PHG4EPDSteppingAction::UserSteppingAction(), PHG4InttSteppingAction::UserSteppingAction(), PHG4BlockSteppingAction::UserSteppingAction(), AllSiliconTrackerSteppingAction::UserSteppingAction(), PHG4HcalSteppingAction::UserSteppingAction(), PHG4CEmcTestBeamSteppingAction::UserSteppingAction(), PHG4InnerHcalSteppingAction::UserSteppingAction(), AllSi_Al_support_SteppingAction::UserSteppingAction(), GdmlImportDetectorSteppingAction::UserSteppingAction(), EicFRichSteppingAction::UserSteppingAction(), PHG4OuterHcalSteppingAction::UserSteppingAction(), PHG4CylinderStripSteppingAction::UserSteppingAction(), BeastMagnetSteppingAction::UserSteppingAction(), PHG4BarrelEcalSteppingAction::UserSteppingAction(), BeamLineMagnetSteppingAction::UserSteppingAction(), EICG4ZDCSteppingAction::UserSteppingAction(), PHG4BbcSteppingAction::UserSteppingAction(), PHG4CrystalCalorimeterSteppingAction::UserSteppingAction(), PHG4ForwardEcalSteppingAction::UserSteppingAction(), PHG4HybridHomogeneousCalorimeterSteppingAction::UserSteppingAction(), PHG4LFHcalSteppingAction::UserSteppingAction(), PHG4TpcEndCapSteppingAction::UserSteppingAction(), PHG4mRICHSteppingAction::UserSteppingAction(), PHG4BackwardHcalSteppingAction::UserSteppingAction(), PHG4ECAPToFSteppingAction::UserSteppingAction(), PHG4ForwardDualReadoutSteppingAction::UserSteppingAction(), PHG4CylinderSteppingAction::UserSteppingAction(), PHG4ForwardHcalSteppingAction::UserSteppingAction(), EICG4RPSteppingAction::UserSteppingAction(), PHG4TRDSteppingAction::UserSteppingAction(), PHG4ZDCSteppingAction::UserSteppingAction(), G4EicDircSteppingAction::UserSteppingAction(), EICG4B0ECALSteppingAction::UserSteppingAction(), EICG4B0SteppingAction::UserSteppingAction(), EICG4BwdSteppingAction::UserSteppingAction(), EICG4LumiSteppingAction::UserSteppingAction(), PHG4SpacalSteppingAction::UserSteppingAction(), and PHG4TTLSteppingAction::UserSteppingAction().
virtual void PHG4Hit::set_eion (const float) inline virtual
Reimplemented in PHG4Hitv1, and PHG4HitEval.
Definition at line 70 of file PHG4Hit.h.
View newest version in sPHENIX GitHub at line 70 of file PHG4Hit.h
Referenced by PHG4TpcCentralMembrane::GetPHG4HitFromStripe(), PHG4SectorSteppingAction::UserSteppingAction(), PHG4TpcSteppingAction::UserSteppingAction(), G4Example01SteppingAction::UserSteppingAction(), PHG4EnvelopeSteppingAction::UserSteppingAction(), G4Example02SteppingAction::UserSteppingAction(), G4JLeicBeamLineMagnetSteppingAction::UserSteppingAction(), G4JLeicDIRCSteppingAction::UserSteppingAction(), G4JLeicVTXSteppingAction::UserSteppingAction(), G4LBLVtxSteppingAction::UserSteppingAction(), PHG4PSTOFSteppingAction::UserSteppingAction(), G4Example03SteppingAction::UserSteppingAction(), PHG4BlockSteppingAction::UserSteppingAction(), AllSi_Al_support_SteppingAction::UserSteppingAction(), EicFRichSteppingAction::UserSteppingAction(), PHG4OuterHcalSteppingAction::UserSteppingAction(), PHG4CylinderStripSteppingAction::UserSteppingAction(), PHG4HcalSteppingAction::UserSteppingAction(), PHG4EPDSteppingAction::UserSteppingAction(), PHG4CEmcTestBeamSteppingAction::UserSteppingAction(), PHG4InttSteppingAction::UserSteppingAction(), PHG4InnerHcalSteppingAction::UserSteppingAction(), EICG4ZDCSteppingAction::UserSteppingAction(), PHG4BbcSteppingAction::UserSteppingAction(), EICG4dRICHSteppingAction::UserSteppingAction(), PHG4BarrelEcalSteppingAction::UserSteppingAction(), PHG4TpcEndCapSteppingAction::UserSteppingAction(), PHG4ECAPToFSteppingAction::UserSteppingAction(), PHG4mRICHSteppingAction::UserSteppingAction(), PHG4ForwardDualReadoutSteppingAction::UserSteppingAction(), PHG4ForwardEcalSteppingAction::UserSteppingAction(), PHG4BackwardHcalSteppingAction::UserSteppingAction(), PHG4CrystalCalorimeterSteppingAction::UserSteppingAction(), PHG4LFHcalSteppingAction::UserSteppingAction(), PHG4HybridHomogeneousCalorimeterSteppingAction::UserSteppingAction(), PHG4CylinderSteppingAction::UserSteppingAction(), EICG4RPSteppingAction::UserSteppingAction(), PHG4ForwardHcalSteppingAction::UserSteppingAction(), PHG4TRDSteppingAction::UserSteppingAction(), PHG4ZDCSteppingAction::UserSteppingAction(), G4EicDircSteppingAction::UserSteppingAction(), EICG4B0ECALSteppingAction::UserSteppingAction(), EICG4B0SteppingAction::UserSteppingAction(), EICG4BwdSteppingAction::UserSteppingAction(), PHG4SpacalSteppingAction::UserSteppingAction(), EICG4LumiSteppingAction::UserSteppingAction(), and PHG4TTLSteppingAction::UserSteppingAction().
virtual void PHG4Hit::set_hit_id (const PHG4HitDefs::keytype) inline virtual
Reimplemented in EICG4dRICHHit, and PHG4Hitv1.
Definition at line 74 of file PHG4Hit.h.
View newest version in sPHENIX GitHub at line 74 of file PHG4Hit.h
Referenced by PHG4HitContainer::AddHit(), and PHG4HitContainer::findOrAddHit().
virtual void PHG4Hit::set_hit_type (const int) inline virtual
Reimplemented in PHG4Hitv1.
Definition at line 87 of file PHG4Hit.h.
View newest version in sPHENIX GitHub at line 87 of file PHG4Hit.h
Referenced by PHG4CylinderStripSteppingAction::UserSteppingAction(), EICG4ZDCSteppingAction::UserSteppingAction(), EICG4RPSteppingAction::UserSteppingAction(), EICG4B0ECALSteppingAction::UserSteppingAction(), EICG4BwdSteppingAction::UserSteppingAction(), EICG4B0SteppingAction::UserSteppingAction(), and EICG4LumiSteppingAction::UserSteppingAction().
virtual void PHG4Hit::set_index_i (const int) inline virtual
Reimplemented in PHG4Hitv1.
Definition at line 83 of file PHG4Hit.h.
View newest version in sPHENIX GitHub at line 83 of file PHG4Hit.h
Referenced by EICG4ZDCSteppingAction::UserSteppingAction(), and PHG4TTLSteppingAction::UserSteppingAction().
virtual void PHG4Hit::set_index_j (const int) inline virtual
Reimplemented in PHG4Hitv1.
Definition at line 84 of file PHG4Hit.h.
View newest version in sPHENIX GitHub at line 84 of file PHG4Hit.h
Referenced by PHG4EnvelopeSteppingAction::UserSteppingAction(), PHG4BarrelEcalSteppingAction::UserSteppingAction(), EICG4ZDCSteppingAction::UserSteppingAction(), PHG4BackwardHcalSteppingAction::UserSteppingAction(), PHG4CrystalCalorimeterSteppingAction::UserSteppingAction(), PHG4ForwardEcalSteppingAction::UserSteppingAction(), PHG4HybridHomogeneousCalorimeterSteppingAction::UserSteppingAction(), PHG4LFHcalSteppingAction::UserSteppingAction(), PHG4ForwardDualReadoutSteppingAction::UserSteppingAction(), PHG4ForwardHcalSteppingAction::UserSteppingAction(), PHG4ZDCSteppingAction::UserSteppingAction(), EICG4B0SteppingAction::UserSteppingAction(), EICG4BwdSteppingAction::UserSteppingAction(), EICG4B0ECALSteppingAction::UserSteppingAction(), and PHG4TTLSteppingAction::UserSteppingAction().
virtual void PHG4Hit::set_index_k (const int) inline virtual
Reimplemented in PHG4Hitv1.
Definition at line 85 of file PHG4Hit.h.
View newest version in sPHENIX GitHub at line 85 of file PHG4Hit.h
Referenced by PHG4EnvelopeSteppingAction::UserSteppingAction(), PHG4BarrelEcalSteppingAction::UserSteppingAction(), PHG4LFHcalSteppingAction::UserSteppingAction(), PHG4CrystalCalorimeterSteppingAction::UserSteppingAction(), PHG4ForwardEcalSteppingAction::UserSteppingAction(), PHG4ForwardDualReadoutSteppingAction::UserSteppingAction(), PHG4HybridHomogeneousCalorimeterSteppingAction::UserSteppingAction(), PHG4BackwardHcalSteppingAction::UserSteppingAction(), PHG4ForwardHcalSteppingAction::UserSteppingAction(), PHG4ZDCSteppingAction::UserSteppingAction(), EICG4B0SteppingAction::UserSteppingAction(), EICG4BwdSteppingAction::UserSteppingAction(), EICG4B0ECALSteppingAction::UserSteppingAction(), and PHG4TTLSteppingAction::UserSteppingAction().
virtual void PHG4Hit::set_index_l (const int) inline virtual
Reimplemented in PHG4Hitv1.
Definition at line 86 of file PHG4Hit.h.
View newest version in sPHENIX GitHub at line 86 of file PHG4Hit.h
Referenced by PHG4EnvelopeSteppingAction::UserSteppingAction(), PHG4LFHcalSteppingAction::UserSteppingAction(), and PHG4TTLSteppingAction::UserSteppingAction().
virtual void PHG4Hit::set_ladder_phi_index (const int) inline virtual
Reimplemented in PHG4Hitv1.
Definition at line 82 of file PHG4Hit.h.
View newest version in sPHENIX GitHub at line 82 of file PHG4Hit.h
Referenced by PHG4InttSteppingAction::UserSteppingAction().
virtual void PHG4Hit::set_ladder_z_index (const int) inline virtual
Reimplemented in PHG4Hitv1.
Definition at line 81 of file PHG4Hit.h.
View newest version in sPHENIX GitHub at line 81 of file PHG4Hit.h
Referenced by PHG4InttSteppingAction::UserSteppingAction().
virtual void PHG4Hit::set_layer (const unsigned int) inline virtual
Reimplemented in PHG4Hitv1.
Definition at line 73 of file PHG4Hit.h.
View newest version in sPHENIX GitHub at line 73 of file PHG4Hit.h
Referenced by PHG4TpcCentralMembrane::GetBotVerticesFromStripe(), PHG4TpcCentralMembrane::GetPHG4HitFromStripe(), PHG4TpcCentralMembrane::GetTopVerticesFromStripe(), CreateCZHitContainer::merge_hits(), PHG4GenHit::process_event(), PHG4TpcSteppingAction::UserSteppingAction(), G4Example01SteppingAction::UserSteppingAction(), PHG4MvtxSteppingAction::UserSteppingAction(), PHG4EICMvtxSteppingAction::UserSteppingAction(), G4LBLVtxSteppingAction::UserSteppingAction(), G4Example03SteppingAction::UserSteppingAction(), PHG4PSTOFSteppingAction::UserSteppingAction(), G4Example02SteppingAction::UserSteppingAction(), G4JLeicBeamLineMagnetSteppingAction::UserSteppingAction(), G4JLeicDIRCSteppingAction::UserSteppingAction(), G4JLeicVTXSteppingAction::UserSteppingAction(), PHG4BlockSteppingAction::UserSteppingAction(), BeastMagnetSteppingAction::UserSteppingAction(), PHG4CylinderStripSteppingAction::UserSteppingAction(), EicFRichSteppingAction::UserSteppingAction(), PHG4HcalSteppingAction::UserSteppingAction(), PHG4CEmcTestBeamSteppingAction::UserSteppingAction(), PHG4InttSteppingAction::UserSteppingAction(), GdmlImportDetectorSteppingAction::UserSteppingAction(), AllSi_Al_support_SteppingAction::UserSteppingAction(), AllSiliconTrackerSteppingAction::UserSteppingAction(), BeamLineMagnetSteppingAction::UserSteppingAction(), PHG4BbcSteppingAction::UserSteppingAction(), EICG4ZDCSteppingAction::UserSteppingAction(), PHG4TpcEndCapSteppingAction::UserSteppingAction(), PHG4ECAPToFSteppingAction::UserSteppingAction(), PHG4CylinderSteppingAction::UserSteppingAction(), EICG4RPSteppingAction::UserSteppingAction(), PHG4TRDSteppingAction::UserSteppingAction(), EICG4B0SteppingAction::UserSteppingAction(), EICG4BwdSteppingAction::UserSteppingAction(), EICG4B0ECALSteppingAction::UserSteppingAction(), PHG4SpacalSteppingAction::UserSteppingAction(), and EICG4LumiSteppingAction::UserSteppingAction().
virtual void PHG4Hit::set_light_yield (const float) inline virtual
Reimplemented in PHG4Hitv1, and PHG4HitEval.
Definition at line 71 of file PHG4Hit.h.
View newest version in sPHENIX GitHub at line 71 of file PHG4Hit.h
Referenced by PHG4HcalSteppingAction::UserSteppingAction(), PHG4OuterHcalSteppingAction::UserSteppingAction(), PHG4CylinderStripSteppingAction::UserSteppingAction(), PHG4InnerHcalSteppingAction::UserSteppingAction(), PHG4EPDSteppingAction::UserSteppingAction(), EICG4ZDCSteppingAction::UserSteppingAction(), PHG4BarrelEcalSteppingAction::UserSteppingAction(), PHG4ForwardEcalSteppingAction::UserSteppingAction(), PHG4CrystalCalorimeterSteppingAction::UserSteppingAction(), PHG4HybridHomogeneousCalorimeterSteppingAction::UserSteppingAction(), PHG4ForwardDualReadoutSteppingAction::UserSteppingAction(), PHG4BackwardHcalSteppingAction::UserSteppingAction(), PHG4LFHcalSteppingAction::UserSteppingAction(), PHG4CylinderSteppingAction::UserSteppingAction(), EICG4RPSteppingAction::UserSteppingAction(), PHG4ForwardHcalSteppingAction::UserSteppingAction(), PHG4ZDCSteppingAction::UserSteppingAction(), EICG4B0ECALSteppingAction::UserSteppingAction(), EICG4B0SteppingAction::UserSteppingAction(), EICG4BwdSteppingAction::UserSteppingAction(), EICG4LumiSteppingAction::UserSteppingAction(), and PHG4SpacalSteppingAction::UserSteppingAction().
virtual void PHG4Hit::set_local_x (const int , const float) inline virtual
Reimplemented in PHG4Hitv1.
Definition at line 65 of file PHG4Hit.h.
View newest version in sPHENIX GitHub at line 65 of file PHG4Hit.h
Referenced by PHG4SteppingAction::StoreLocalCoordinate(), and PHG4TTLSteppingAction::UserSteppingAction().
virtual void PHG4Hit::set_local_y (const int , const float) inline virtual
Reimplemented in PHG4Hitv1.
Definition at line 66 of file PHG4Hit.h.
View newest version in sPHENIX GitHub at line 66 of file PHG4Hit.h
Referenced by PHG4SteppingAction::StoreLocalCoordinate(), and PHG4TTLSteppingAction::UserSteppingAction().
virtual void PHG4Hit::set_local_z (const int , const float) inline virtual
Reimplemented in PHG4Hitv1.
Definition at line 67 of file PHG4Hit.h.
View newest version in sPHENIX GitHub at line 67 of file PHG4Hit.h
Referenced by PHG4SteppingAction::StoreLocalCoordinate(), and PHG4TTLSteppingAction::UserSteppingAction().
virtual void PHG4Hit::set_path_length (const float) inline virtual
Reimplemented in PHG4Hitv1, and PHG4HitEval.
Definition at line 72 of file PHG4Hit.h.
View newest version in sPHENIX GitHub at line 72 of file PHG4Hit.h
Referenced by PHG4SectorSteppingAction::UserSteppingAction(), PHG4HcalSteppingAction::UserSteppingAction(), PHG4BbcSteppingAction::UserSteppingAction(), and PHG4TTLSteppingAction::UserSteppingAction().
virtual void PHG4Hit::set_property (const PROPERTY , const float) inline virtual
Reimplemented in PHG4Hitv1.
Definition at line 187 of file PHG4Hit.h.
View newest version in sPHENIX GitHub at line 187 of file PHG4Hit.h
Referenced by PHG4EICMvtxSteppingAction::UserSteppingAction(), PHG4MvtxSteppingAction::UserSteppingAction(), and PHG4ForwardDualReadoutSteppingAction::UserSteppingAction().
virtual void PHG4Hit::set_property (const PROPERTY , const int) inline virtual
Reimplemented in PHG4Hitv1.
Definition at line 188 of file PHG4Hit.h.
View newest version in sPHENIX GitHub at line 188 of file PHG4Hit.h
virtual void PHG4Hit::set_property (const PROPERTY , const unsigned int) inline virtual
Reimplemented in PHG4Hitv1.
Definition at line 189 of file PHG4Hit.h.
View newest version in sPHENIX GitHub at line 189 of file PHG4Hit.h
virtual void PHG4Hit::set_property_nocheck (const PROPERTY , const unsigned int) inline protected virtual
Reimplemented in PHG4Hitv1.
Definition at line 196 of file PHG4Hit.h.
View newest version in sPHENIX GitHub at line 196 of file PHG4Hit.h
virtual void PHG4Hit::set_px (const int , const float) inline virtual
Reimplemented in PHG4Hitv1.
Definition at line 62 of file PHG4Hit.h.
View newest version in sPHENIX GitHub at line 62 of file PHG4Hit.h
Referenced by PHG4TpcCentralMembrane::GetPHG4HitFromStripe(), PHG4EICMvtxSteppingAction::UserSteppingAction(), PHG4MvtxSteppingAction::UserSteppingAction(), PHG4TpcSteppingAction::UserSteppingAction(), PHG4CylinderStripSteppingAction::UserSteppingAction(), PHG4InttSteppingAction::UserSteppingAction(), PHG4ECAPToFSteppingAction::UserSteppingAction(), PHG4CylinderSteppingAction::UserSteppingAction(), EICG4RPSteppingAction::UserSteppingAction(), PHG4TRDSteppingAction::UserSteppingAction(), G4EicDircSteppingAction::UserSteppingAction(), EICG4B0SteppingAction::UserSteppingAction(), EICG4B0ECALSteppingAction::UserSteppingAction(), EICG4BwdSteppingAction::UserSteppingAction(), and EICG4LumiSteppingAction::UserSteppingAction().
virtual void PHG4Hit::set_py (const int , const float) inline virtual
Reimplemented in PHG4Hitv1.
Definition at line 63 of file PHG4Hit.h.
View newest version in sPHENIX GitHub at line 63 of file PHG4Hit.h
Referenced by PHG4TpcCentralMembrane::GetPHG4HitFromStripe(), PHG4EICMvtxSteppingAction::UserSteppingAction(), PHG4MvtxSteppingAction::UserSteppingAction(), PHG4TpcSteppingAction::UserSteppingAction(), PHG4CylinderStripSteppingAction::UserSteppingAction(), PHG4InttSteppingAction::UserSteppingAction(), PHG4ECAPToFSteppingAction::UserSteppingAction(), PHG4CylinderSteppingAction::UserSteppingAction(), EICG4RPSteppingAction::UserSteppingAction(), PHG4TRDSteppingAction::UserSteppingAction(), G4EicDircSteppingAction::UserSteppingAction(), EICG4B0SteppingAction::UserSteppingAction(), EICG4B0ECALSteppingAction::UserSteppingAction(), EICG4BwdSteppingAction::UserSteppingAction(), and EICG4LumiSteppingAction::UserSteppingAction().
virtual void PHG4Hit::set_pz (const int , const float) inline virtual
Reimplemented in PHG4Hitv1.
Definition at line 64 of file PHG4Hit.h.
View newest version in sPHENIX GitHub at line 64 of file PHG4Hit.h
Referenced by PHG4TpcCentralMembrane::GetPHG4HitFromStripe(), PHG4EICMvtxSteppingAction::UserSteppingAction(), PHG4MvtxSteppingAction::UserSteppingAction(), PHG4TpcSteppingAction::UserSteppingAction(), PHG4CylinderStripSteppingAction::UserSteppingAction(), PHG4InttSteppingAction::UserSteppingAction(), PHG4ECAPToFSteppingAction::UserSteppingAction(), PHG4CylinderSteppingAction::UserSteppingAction(), EICG4RPSteppingAction::UserSteppingAction(), PHG4TRDSteppingAction::UserSteppingAction(), G4EicDircSteppingAction::UserSteppingAction(), EICG4B0SteppingAction::UserSteppingAction(), EICG4B0ECALSteppingAction::UserSteppingAction(), EICG4BwdSteppingAction::UserSteppingAction(), and EICG4LumiSteppingAction::UserSteppingAction().
virtual void PHG4Hit::set_row (const int) inline virtual
Reimplemented in PHG4Hitv1.
Definition at line 77 of file PHG4Hit.h.
View newest version in sPHENIX GitHub at line 77 of file PHG4Hit.h
virtual void PHG4Hit::set_scint_id (const int) inline virtual
Reimplemented in PHG4Hitv1, and PHG4HitEval.
Definition at line 76 of file PHG4Hit.h.
View newest version in sPHENIX GitHub at line 76 of file PHG4Hit.h
Referenced by PHG4EnvelopeSteppingAction::UserSteppingAction(), PHG4HcalSteppingAction::UserSteppingAction(), PHG4EPDSteppingAction::UserSteppingAction(), PHG4InnerHcalSteppingAction::UserSteppingAction(), PHG4OuterHcalSteppingAction::UserSteppingAction(), PHG4CEmcTestBeamSteppingAction::UserSteppingAction(), PHG4BbcSteppingAction::UserSteppingAction(), PHG4mRICHSteppingAction::UserSteppingAction(), and PHG4SpacalSteppingAction::UserSteppingAction().
virtual void PHG4Hit::set_shower_id (const int) inline virtual
Reimplemented in EICG4dRICHHit, and PHG4Hitv1.
Definition at line 75 of file PHG4Hit.h.
View newest version in sPHENIX GitHub at line 75 of file PHG4Hit.h
Referenced by PHG4RICHSteppingAction::MakeHit(), PHG4FPbScSteppingAction::UserSteppingAction(), PHG4FCalSteppingAction::UserSteppingAction(), PHG4EnvelopeSteppingAction::UserSteppingAction(), PHG4SectorSteppingAction::UserSteppingAction(), PHG4EICMvtxSteppingAction::UserSteppingAction(), PHG4ConeSteppingAction::UserSteppingAction(), PHG4MvtxSteppingAction::UserSteppingAction(), PHG4TpcSteppingAction::UserSteppingAction(), PHG4FPbScRegionSteppingAction::UserSteppingAction(), PHG4OuterHcalSteppingAction::UserSteppingAction(), PHG4CylinderStripSteppingAction::UserSteppingAction(), PHG4CEmcTestBeamSteppingAction::UserSteppingAction(), PHG4BlockSteppingAction::UserSteppingAction(), PHG4InttSteppingAction::UserSteppingAction(), PHG4HcalSteppingAction::UserSteppingAction(), PHG4InnerHcalSteppingAction::UserSteppingAction(), EICG4ZDCSteppingAction::UserSteppingAction(), PHG4BarrelEcalSteppingAction::UserSteppingAction(), PHG4ECAPToFSteppingAction::UserSteppingAction(), PHG4mRICHSteppingAction::UserSteppingAction(), PHG4ForwardDualReadoutSteppingAction::UserSteppingAction(), PHG4BackwardHcalSteppingAction::UserSteppingAction(), PHG4CrystalCalorimeterSteppingAction::UserSteppingAction(), PHG4ForwardEcalSteppingAction::UserSteppingAction(), PHG4HybridHomogeneousCalorimeterSteppingAction::UserSteppingAction(), PHG4LFHcalSteppingAction::UserSteppingAction(), PHG4CylinderSteppingAction::UserSteppingAction(), EICG4RPSteppingAction::UserSteppingAction(), PHG4ForwardHcalSteppingAction::UserSteppingAction(), PHG4TRDSteppingAction::UserSteppingAction(), PHG4ZDCSteppingAction::UserSteppingAction(), G4EicDircSteppingAction::UserSteppingAction(), EICG4BwdSteppingAction::UserSteppingAction(), EICG4B0SteppingAction::UserSteppingAction(), EICG4B0ECALSteppingAction::UserSteppingAction(), EICG4LumiSteppingAction::UserSteppingAction(), PHG4SpacalSteppingAction::UserSteppingAction(), and PHG4TTLSteppingAction::UserSteppingAction().
virtual void PHG4Hit::set_strip_y_index (const int) inline virtual
Reimplemented in PHG4Hitv1.
Definition at line 80 of file PHG4Hit.h.
View newest version in sPHENIX GitHub at line 80 of file PHG4Hit.h
Referenced by PHG4TTLSteppingAction::UserSteppingAction().
virtual void PHG4Hit::set_strip_z_index (const int) inline virtual
Reimplemented in PHG4Hitv1.
Definition at line 79 of file PHG4Hit.h.
View newest version in sPHENIX GitHub at line 79 of file PHG4Hit.h
Referenced by PHG4TTLSteppingAction::UserSteppingAction().
virtual void PHG4Hit::set_t (const int , const float) inline virtual
Reimplemented in EICG4dRICHHit, and PHG4Hitv1.
Definition at line 68 of file PHG4Hit.h.
View newest version in sPHENIX GitHub at line 68 of file PHG4Hit.h
Referenced by PHG4TpcCentralMembrane::GetPHG4HitFromStripe(), PHG4RICHSteppingAction::MakeHit(), CreateCZHitContainer::merge_hits(), PHG4ConeSteppingAction::UserSteppingAction(), PHG4EICMvtxSteppingAction::UserSteppingAction(), PHG4MvtxSteppingAction::UserSteppingAction(), PHG4EnvelopeSteppingAction::UserSteppingAction(), PHG4TpcSteppingAction::UserSteppingAction(), PHG4SectorSteppingAction::UserSteppingAction(), G4Example01SteppingAction::UserSteppingAction(), PHG4FPbScRegionSteppingAction::UserSteppingAction(), G4JLeicBeamLineMagnetSteppingAction::UserSteppingAction(), G4JLeicDIRCSteppingAction::UserSteppingAction(), G4JLeicVTXSteppingAction::UserSteppingAction(), G4LBLVtxSteppingAction::UserSteppingAction(), PHG4PSTOFSteppingAction::UserSteppingAction(), G4Example03SteppingAction::UserSteppingAction(), G4Example02SteppingAction::UserSteppingAction(), PHG4EPDSteppingAction::UserSteppingAction(), PHG4InttSteppingAction::UserSteppingAction(), BeastMagnetSteppingAction::UserSteppingAction(), PHG4HcalSteppingAction::UserSteppingAction(), PHG4BlockSteppingAction::UserSteppingAction(), AllSiliconTrackerSteppingAction::UserSteppingAction(), PHG4InnerHcalSteppingAction::UserSteppingAction(), PHG4CEmcTestBeamSteppingAction::UserSteppingAction(), AllSi_Al_support_SteppingAction::UserSteppingAction(), EicFRichSteppingAction::UserSteppingAction(), PHG4OuterHcalSteppingAction::UserSteppingAction(), GdmlImportDetectorSteppingAction::UserSteppingAction(), PHG4CylinderStripSteppingAction::UserSteppingAction(), BeamLineMagnetSteppingAction::UserSteppingAction(), EICG4ZDCSteppingAction::UserSteppingAction(), PHG4BbcSteppingAction::UserSteppingAction(), PHG4BarrelEcalSteppingAction::UserSteppingAction(), PHG4CrystalCalorimeterSteppingAction::UserSteppingAction(), PHG4HybridHomogeneousCalorimeterSteppingAction::UserSteppingAction(), PHG4LFHcalSteppingAction::UserSteppingAction(), PHG4ECAPToFSteppingAction::UserSteppingAction(), PHG4ForwardEcalSteppingAction::UserSteppingAction(), PHG4BackwardHcalSteppingAction::UserSteppingAction(), PHG4mRICHSteppingAction::UserSteppingAction(), PHG4TpcEndCapSteppingAction::UserSteppingAction(), PHG4ForwardDualReadoutSteppingAction::UserSteppingAction(), PHG4ForwardHcalSteppingAction::UserSteppingAction(), EICG4RPSteppingAction::UserSteppingAction(), PHG4CylinderSteppingAction::UserSteppingAction(), PHG4TRDSteppingAction::UserSteppingAction(), PHG4ZDCSteppingAction::UserSteppingAction(), G4EicDircSteppingAction::UserSteppingAction(), EICG4BwdSteppingAction::UserSteppingAction(), EICG4B0ECALSteppingAction::UserSteppingAction(), EICG4B0SteppingAction::UserSteppingAction(), EICG4LumiSteppingAction::UserSteppingAction(), PHG4SpacalSteppingAction::UserSteppingAction(), and PHG4TTLSteppingAction::UserSteppingAction().
virtual void PHG4Hit::set_trkid (const int) inline virtual
Reimplemented in EICG4dRICHHit, and PHG4Hitv1.
Definition at line 78 of file PHG4Hit.h.
View newest version in sPHENIX GitHub at line 78 of file PHG4Hit.h
Referenced by PHG4TpcCentralMembrane::GetPHG4HitFromStripe(), PHG4RICHSteppingAction::MakeHit(), CreateCZHitContainer::merge_hits(), PHG4GenHit::process_event(), PHG4FPbScSteppingAction::UserSteppingAction(), PHG4FCalSteppingAction::UserSteppingAction(), PHG4EnvelopeSteppingAction::UserSteppingAction(), PHG4EICMvtxSteppingAction::UserSteppingAction(), PHG4ConeSteppingAction::UserSteppingAction(), PHG4MvtxSteppingAction::UserSteppingAction(), PHG4TpcSteppingAction::UserSteppingAction(), PHG4SectorSteppingAction::UserSteppingAction(), G4Example01SteppingAction::UserSteppingAction(), PHG4FPbScRegionSteppingAction::UserSteppingAction(), G4JLeicBeamLineMagnetSteppingAction::UserSteppingAction(), G4JLeicDIRCSteppingAction::UserSteppingAction(), G4JLeicVTXSteppingAction::UserSteppingAction(), G4LBLVtxSteppingAction::UserSteppingAction(), G4Example02SteppingAction::UserSteppingAction(), PHG4PSTOFSteppingAction::UserSteppingAction(), G4Example03SteppingAction::UserSteppingAction(), PHG4EPDSteppingAction::UserSteppingAction(), PHG4InttSteppingAction::UserSteppingAction(), PHG4BlockSteppingAction::UserSteppingAction(), PHG4OuterHcalSteppingAction::UserSteppingAction(), PHG4HcalSteppingAction::UserSteppingAction(), PHG4CEmcTestBeamSteppingAction::UserSteppingAction(), AllSi_Al_support_SteppingAction::UserSteppingAction(), AllSiliconTrackerSteppingAction::UserSteppingAction(), PHG4InnerHcalSteppingAction::UserSteppingAction(), EicFRichSteppingAction::UserSteppingAction(), GdmlImportDetectorSteppingAction::UserSteppingAction(), PHG4CylinderStripSteppingAction::UserSteppingAction(), BeastMagnetSteppingAction::UserSteppingAction(), PHG4BarrelEcalSteppingAction::UserSteppingAction(), BeamLineMagnetSteppingAction::UserSteppingAction(), EICG4ZDCSteppingAction::UserSteppingAction(), PHG4BbcSteppingAction::UserSteppingAction(), PHG4BackwardHcalSteppingAction::UserSteppingAction(), PHG4CrystalCalorimeterSteppingAction::UserSteppingAction(), PHG4TpcEndCapSteppingAction::UserSteppingAction(), PHG4HybridHomogeneousCalorimeterSteppingAction::UserSteppingAction(), PHG4LFHcalSteppingAction::UserSteppingAction(), PHG4ForwardEcalSteppingAction::UserSteppingAction(), PHG4mRICHSteppingAction::UserSteppingAction(), PHG4ECAPToFSteppingAction::UserSteppingAction(), PHG4ForwardDualReadoutSteppingAction::UserSteppingAction(), PHG4ForwardHcalSteppingAction::UserSteppingAction(), PHG4CylinderSteppingAction::UserSteppingAction(), EICG4RPSteppingAction::UserSteppingAction(), PHG4TRDSteppingAction::UserSteppingAction(), PHG4ZDCSteppingAction::UserSteppingAction(), G4EicDircSteppingAction::UserSteppingAction(), EICG4B0ECALSteppingAction::UserSteppingAction(), EICG4BwdSteppingAction::UserSteppingAction(), EICG4B0SteppingAction::UserSteppingAction(), PHG4SpacalSteppingAction::UserSteppingAction(), EICG4LumiSteppingAction::UserSteppingAction(), and PHG4TTLSteppingAction::UserSteppingAction().
virtual void PHG4Hit::set_x (const int , const float) inline virtual
Reimplemented in PHG4Hitv1.
Definition at line 59 of file PHG4Hit.h.
View newest version in sPHENIX GitHub at line 59 of file PHG4Hit.h
Referenced by CylinderGeomMicromegas::convert_to_planar(), PHG4TpcCentralMembrane::GetBotVerticesFromStripe(), PHG4TpcCentralMembrane::GetPHG4HitFromStripe(), PHG4TpcCentralMembrane::GetTopVerticesFromStripe(), PHG4RICHSteppingAction::MakeHit(), CreateCZHitContainer::merge_hits(), PHG4GenHit::process_event(), PHG4FPbScSteppingAction::UserSteppingAction(), PHG4FCalSteppingAction::UserSteppingAction(), PHG4EICMvtxSteppingAction::UserSteppingAction(), PHG4MvtxSteppingAction::UserSteppingAction(), PHG4EnvelopeSteppingAction::UserSteppingAction(), PHG4ConeSteppingAction::UserSteppingAction(), PHG4TpcSteppingAction::UserSteppingAction(), PHG4SectorSteppingAction::UserSteppingAction(), G4Example01SteppingAction::UserSteppingAction(), PHG4FPbScRegionSteppingAction::UserSteppingAction(), G4JLeicBeamLineMagnetSteppingAction::UserSteppingAction(), G4JLeicDIRCSteppingAction::UserSteppingAction(), G4JLeicVTXSteppingAction::UserSteppingAction(), G4LBLVtxSteppingAction::UserSteppingAction(), G4Example02SteppingAction::UserSteppingAction(), G4Example03SteppingAction::UserSteppingAction(), PHG4PSTOFSteppingAction::UserSteppingAction(), GdmlImportDetectorSteppingAction::UserSteppingAction(), PHG4EPDSteppingAction::UserSteppingAction(), PHG4InttSteppingAction::UserSteppingAction(), PHG4BlockSteppingAction::UserSteppingAction(), PHG4CylinderStripSteppingAction::UserSteppingAction(), PHG4HcalSteppingAction::UserSteppingAction(), BeastMagnetSteppingAction::UserSteppingAction(), EicFRichSteppingAction::UserSteppingAction(), PHG4InnerHcalSteppingAction::UserSteppingAction(), AllSiliconTrackerSteppingAction::UserSteppingAction(), PHG4OuterHcalSteppingAction::UserSteppingAction(), PHG4CEmcTestBeamSteppingAction::UserSteppingAction(), AllSi_Al_support_SteppingAction::UserSteppingAction(), PHG4BarrelEcalSteppingAction::UserSteppingAction(), PHG4BbcSteppingAction::UserSteppingAction(), BeamLineMagnetSteppingAction::UserSteppingAction(), EICG4ZDCSteppingAction::UserSteppingAction(), PHG4ForwardDualReadoutSteppingAction::UserSteppingAction(), PHG4BackwardHcalSteppingAction::UserSteppingAction(), PHG4CrystalCalorimeterSteppingAction::UserSteppingAction(), PHG4ForwardEcalSteppingAction::UserSteppingAction(), PHG4mRICHSteppingAction::UserSteppingAction(), PHG4HybridHomogeneousCalorimeterSteppingAction::UserSteppingAction(), PHG4ECAPToFSteppingAction::UserSteppingAction(), PHG4LFHcalSteppingAction::UserSteppingAction(), PHG4TpcEndCapSteppingAction::UserSteppingAction(), PHG4CylinderSteppingAction::UserSteppingAction(), PHG4ForwardHcalSteppingAction::UserSteppingAction(), EICG4RPSteppingAction::UserSteppingAction(), PHG4TRDSteppingAction::UserSteppingAction(), G4EicDircSteppingAction::UserSteppingAction(), PHG4ZDCSteppingAction::UserSteppingAction(), EICG4B0ECALSteppingAction::UserSteppingAction(), EICG4BwdSteppingAction::UserSteppingAction(), EICG4B0SteppingAction::UserSteppingAction(), EICG4LumiSteppingAction::UserSteppingAction(), PHG4SpacalSteppingAction::UserSteppingAction(), and PHG4TTLSteppingAction::UserSteppingAction().
virtual void PHG4Hit::set_y (const int , const float) inline virtual
Reimplemented in PHG4Hitv1.
Definition at line 60 of file PHG4Hit.h.
View newest version in sPHENIX GitHub at line 60 of file PHG4Hit.h
Referenced by CylinderGeomMicromegas::convert_to_planar(), PHG4TpcCentralMembrane::GetBotVerticesFromStripe(), PHG4TpcCentralMembrane::GetPHG4HitFromStripe(), PHG4TpcCentralMembrane::GetTopVerticesFromStripe(), PHG4RICHSteppingAction::MakeHit(), CreateCZHitContainer::merge_hits(), PHG4GenHit::process_event(), PHG4FPbScSteppingAction::UserSteppingAction(), PHG4FCalSteppingAction::UserSteppingAction(), PHG4EICMvtxSteppingAction::UserSteppingAction(), PHG4MvtxSteppingAction::UserSteppingAction(), PHG4EnvelopeSteppingAction::UserSteppingAction(), PHG4ConeSteppingAction::UserSteppingAction(), PHG4TpcSteppingAction::UserSteppingAction(), PHG4SectorSteppingAction::UserSteppingAction(), G4Example01SteppingAction::UserSteppingAction(), PHG4FPbScRegionSteppingAction::UserSteppingAction(), G4JLeicBeamLineMagnetSteppingAction::UserSteppingAction(), G4JLeicDIRCSteppingAction::UserSteppingAction(), G4JLeicVTXSteppingAction::UserSteppingAction(), G4LBLVtxSteppingAction::UserSteppingAction(), G4Example02SteppingAction::UserSteppingAction(), G4Example03SteppingAction::UserSteppingAction(), PHG4PSTOFSteppingAction::UserSteppingAction(), GdmlImportDetectorSteppingAction::UserSteppingAction(), PHG4EPDSteppingAction::UserSteppingAction(), PHG4InttSteppingAction::UserSteppingAction(), PHG4BlockSteppingAction::UserSteppingAction(), PHG4CylinderStripSteppingAction::UserSteppingAction(), PHG4HcalSteppingAction::UserSteppingAction(), BeastMagnetSteppingAction::UserSteppingAction(), EicFRichSteppingAction::UserSteppingAction(), PHG4InnerHcalSteppingAction::UserSteppingAction(), AllSiliconTrackerSteppingAction::UserSteppingAction(), PHG4OuterHcalSteppingAction::UserSteppingAction(), PHG4CEmcTestBeamSteppingAction::UserSteppingAction(), AllSi_Al_support_SteppingAction::UserSteppingAction(), PHG4BarrelEcalSteppingAction::UserSteppingAction(), PHG4BbcSteppingAction::UserSteppingAction(), BeamLineMagnetSteppingAction::UserSteppingAction(), EICG4ZDCSteppingAction::UserSteppingAction(), PHG4ForwardDualReadoutSteppingAction::UserSteppingAction(), PHG4BackwardHcalSteppingAction::UserSteppingAction(), PHG4CrystalCalorimeterSteppingAction::UserSteppingAction(), PHG4ForwardEcalSteppingAction::UserSteppingAction(), PHG4mRICHSteppingAction::UserSteppingAction(), PHG4HybridHomogeneousCalorimeterSteppingAction::UserSteppingAction(), PHG4ECAPToFSteppingAction::UserSteppingAction(), PHG4LFHcalSteppingAction::UserSteppingAction(), PHG4TpcEndCapSteppingAction::UserSteppingAction(), PHG4CylinderSteppingAction::UserSteppingAction(), PHG4ForwardHcalSteppingAction::UserSteppingAction(), EICG4RPSteppingAction::UserSteppingAction(), PHG4TRDSteppingAction::UserSteppingAction(), G4EicDircSteppingAction::UserSteppingAction(), PHG4ZDCSteppingAction::UserSteppingAction(), EICG4B0ECALSteppingAction::UserSteppingAction(), EICG4BwdSteppingAction::UserSteppingAction(), EICG4B0SteppingAction::UserSteppingAction(), EICG4LumiSteppingAction::UserSteppingAction(), PHG4SpacalSteppingAction::UserSteppingAction(), and PHG4TTLSteppingAction::UserSteppingAction().
virtual void PHG4Hit::set_z (const int , const float) inline virtual
Reimplemented in PHG4Hitv1.
Definition at line 61 of file PHG4Hit.h.
View newest version in sPHENIX GitHub at line 61 of file PHG4Hit.h
Referenced by CylinderGeomMicromegas::convert_to_planar(), PHG4TpcCentralMembrane::GetBotVerticesFromStripe(), PHG4TpcCentralMembrane::GetPHG4HitFromStripe(), PHG4TpcCentralMembrane::GetTopVerticesFromStripe(), PHG4RICHSteppingAction::MakeHit(), CreateCZHitContainer::merge_hits(), PHG4GenHit::process_event(), PHG4FPbScSteppingAction::UserSteppingAction(), PHG4FCalSteppingAction::UserSteppingAction(), PHG4EICMvtxSteppingAction::UserSteppingAction(), PHG4MvtxSteppingAction::UserSteppingAction(), PHG4EnvelopeSteppingAction::UserSteppingAction(), PHG4ConeSteppingAction::UserSteppingAction(), PHG4TpcSteppingAction::UserSteppingAction(), PHG4SectorSteppingAction::UserSteppingAction(), G4Example01SteppingAction::UserSteppingAction(), PHG4FPbScRegionSteppingAction::UserSteppingAction(), G4JLeicBeamLineMagnetSteppingAction::UserSteppingAction(), G4JLeicDIRCSteppingAction::UserSteppingAction(), G4JLeicVTXSteppingAction::UserSteppingAction(), G4LBLVtxSteppingAction::UserSteppingAction(), G4Example02SteppingAction::UserSteppingAction(), G4Example03SteppingAction::UserSteppingAction(), PHG4PSTOFSteppingAction::UserSteppingAction(), GdmlImportDetectorSteppingAction::UserSteppingAction(), PHG4EPDSteppingAction::UserSteppingAction(), PHG4InttSteppingAction::UserSteppingAction(), PHG4BlockSteppingAction::UserSteppingAction(), PHG4CylinderStripSteppingAction::UserSteppingAction(), PHG4HcalSteppingAction::UserSteppingAction(), BeastMagnetSteppingAction::UserSteppingAction(), EicFRichSteppingAction::UserSteppingAction(), PHG4InnerHcalSteppingAction::UserSteppingAction(), AllSiliconTrackerSteppingAction::UserSteppingAction(), PHG4OuterHcalSteppingAction::UserSteppingAction(), PHG4CEmcTestBeamSteppingAction::UserSteppingAction(), AllSi_Al_support_SteppingAction::UserSteppingAction(), PHG4BarrelEcalSteppingAction::UserSteppingAction(), PHG4BbcSteppingAction::UserSteppingAction(), BeamLineMagnetSteppingAction::UserSteppingAction(), EICG4ZDCSteppingAction::UserSteppingAction(), PHG4ForwardDualReadoutSteppingAction::UserSteppingAction(), PHG4BackwardHcalSteppingAction::UserSteppingAction(), PHG4CrystalCalorimeterSteppingAction::UserSteppingAction(), PHG4ForwardEcalSteppingAction::UserSteppingAction(), PHG4mRICHSteppingAction::UserSteppingAction(), PHG4HybridHomogeneousCalorimeterSteppingAction::UserSteppingAction(), PHG4ECAPToFSteppingAction::UserSteppingAction(), PHG4LFHcalSteppingAction::UserSteppingAction(), PHG4TpcEndCapSteppingAction::UserSteppingAction(), PHG4CylinderSteppingAction::UserSteppingAction(), PHG4ForwardHcalSteppingAction::UserSteppingAction(), EICG4RPSteppingAction::UserSteppingAction(), PHG4TRDSteppingAction::UserSteppingAction(), G4EicDircSteppingAction::UserSteppingAction(), PHG4ZDCSteppingAction::UserSteppingAction(), EICG4B0ECALSteppingAction::UserSteppingAction(), EICG4BwdSteppingAction::UserSteppingAction(), EICG4B0SteppingAction::UserSteppingAction(), EICG4LumiSteppingAction::UserSteppingAction(), PHG4SpacalSteppingAction::UserSteppingAction(), and PHG4TTLSteppingAction::UserSteppingAction().
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & stream, const PHG4Hit * hit) friend
Definition at line 63 of file PHG4Hit.cc.
View newest version in sPHENIX GitHub at line 63 of file PHG4Hit.cc
The documentation for this class was generated from the following files:
fun4all_coresoftware/blob/master/simulation/g4simulation/g4main/PHG4Hit.h
fun4all_coresoftware/blob/master/simulation/g4simulation/g4main/PHG4Hit.cc