EIC Software: fun4all_macros/blob/master/common/G4_Global.C File Reference
G4_Global.C File Reference
#include <g4vertex/GlobalVertexFastSimReco.h>
#include <g4vertex/GlobalVertexReco.h>
#include <fun4all/Fun4AllServer.h>
Namespaces
namespace Enable
namespace G4GLOBAL
Macros
#define MACRO_G4GLOBAL_C
Functions
void GlobalInit ()
void Global_Reco ()
void Global_FastSim ()
Variables
bool Enable::GLOBAL_RECO = false
bool Enable::GLOBAL_FASTSIM = false
double G4GLOBAL::x_smearing = 0.01
double G4GLOBAL::y_smearing = 0.01
double G4GLOBAL::z_smearing = 0.015
double G4GLOBAL::t_smearing = 0.002
Macro Definition Documentation
#define MACRO_G4GLOBAL_C
Definition at line 2 of file G4_Global.C.
View newest version in sPHENIX GitHub at line 2 of file G4_Global.C
Function Documentation
void Global_FastSim ()
Definition at line 41 of file G4_Global.C.
View newest version in sPHENIX GitHub at line 41 of file G4_Global.C
References Fun4AllServer::instance(), Fun4AllServer::registerSubsystem(), GlobalVertexFastSimReco::set_t_smearing(), GlobalVertexFastSimReco::set_x_smearing(), GlobalVertexFastSimReco::set_y_smearing(), GlobalVertexFastSimReco::set_z_smearing(), G4GLOBAL::t_smearing, G4GLOBAL::x_smearing, G4GLOBAL::y_smearing, and G4GLOBAL::z_smearing.
Referenced by Fun4All_AnaTutorial_sPHENIX(), Fun4All_AnaTutorial_sPHENIX_Jets(), Fun4All_G4_CEMC(), Fun4All_G4_EICDetector(), Fun4All_G4_EICDetector_AnaTutorial(), Fun4All_G4_FEMC(), Fun4All_G4_FHCAL(), Fun4All_G4_fsPHENIX(), Fun4All_G4_FullDetectorModular(), Fun4All_G4_FullDetectorModularBeast(), Fun4All_G4_HCALIN(), Fun4All_G4_HCALOUT(), Fun4All_G4_LBLDetector(), Fun4All_G4_sPHENIX(), and Fun4All_G4_sPHENIX_particle_gen().
void Global_Reco ()
Definition at line 27 of file G4_Global.C.
View newest version in sPHENIX GitHub at line 27 of file G4_Global.C
References Fun4AllServer::instance(), and Fun4AllServer::registerSubsystem().
Referenced by Fun4All_AnaTutorial_sPHENIX(), Fun4All_AnaTutorial_sPHENIX_Jets(), Fun4All_G4_CEMC(), Fun4All_G4_EICDetector(), Fun4All_G4_EICDetector_AnaTutorial(), Fun4All_G4_FastMom(), Fun4All_G4_FastMom_GEM(), Fun4All_G4_FastMom_GEM_RICH(), Fun4All_G4_FEMC(), Fun4All_G4_FHCAL(), Fun4All_G4_fsPHENIX(), Fun4All_G4_FullDetectorModular(), Fun4All_G4_FullDetectorModularBeast(), Fun4All_G4_HCALIN(), Fun4All_G4_HCALOUT(), Fun4All_G4_LBLDetector(), and Fun4All_G4_sPHENIX().
void GlobalInit ()
Definition at line 25 of file G4_Global.C.
View newest version in sPHENIX GitHub at line 25 of file G4_Global.C