EIC Software: FairGeoTube Class Reference
FairGeoTube Class Reference
#include <EicRoot/blob/master/geobase/FairGeoTube.h>
Public Member Functions
FairGeoTube ()
~FairGeoTube ()
TArrayD * calcVoluParam (FairGeoVolume *)
void calcVoluPosition (FairGeoVolume *, const FairGeoTransform &, const FairGeoTransform &)
Int_t readPoints (std::fstream *, FairGeoVolume *)
Bool_t writePoints (std::fstream *, FairGeoVolume *)
void printPoints (FairGeoVolume *volu)
Public Member Functions inherited from FairGeoBasicShape
FairGeoBasicShape ()
virtual ~FairGeoBasicShape ()
Int_t getNumPoints ()
Int_t getNumParam ()
TArrayD * getParam ()
FairGeoTransform * getCenterPosition ()
FairGeoTransform * getVoluPosition ()
virtual void calcVoluPosition (FairGeoVolume *, const FairGeoTransform &)
void printParam ()
Additional Inherited Members
Protected Member Functions inherited from FairGeoBasicShape
void posInMother (const FairGeoTransform &, const FairGeoTransform &)
ClassDef(FairGeoBasicShape,
0) private FairGeoBasicShape & operator= (const FairGeoBasicShape &)
Protected Attributes inherited from FairGeoBasicShape
Int_t nPoints
Int_t nParam
TArrayD * param
FairGeoTransform * center
FairGeoTransform * position
Detailed Description
Definition at line 9 of file FairGeoTube.h.
View newest version in sPHENIX GitHub at line 9 of file FairGeoTube.h
Constructor & Destructor Documentation
FairGeoTube::FairGeoTube ()
FairGeoTube::~FairGeoTube ()
Definition at line 45 of file FairGeoTube.cxx.
View newest version in sPHENIX GitHub at line 45 of file FairGeoTube.cxx
References FairGeoBasicShape::center, FairGeoBasicShape::param, and FairGeoBasicShape::position.
Member Function Documentation
TArrayD * FairGeoTube::calcVoluParam (FairGeoVolume * volu) virtual
Reimplemented from FairGeoBasicShape.
Definition at line 114 of file FairGeoTube.cxx.
View newest version in sPHENIX GitHub at line 114 of file FairGeoTube.cxx
References FairGeoVolume::getPoint(), FairGeoBasicShape::param, v, and v1.
void FairGeoTube::calcVoluPosition (FairGeoVolume * volu, const FairGeoTransform & dTC, const FairGeoTransform & mTR) virtual
Reimplemented from FairGeoBasicShape.
Definition at line 127 of file FairGeoTube.cxx.
View newest version in sPHENIX GitHub at line 127 of file FairGeoTube.cxx
References FairGeoBasicShape::center, FairGeoTransform::clear(), FairGeoVolume::getPoint(), FairGeoBasicShape::posInMother(), FairGeoTransform::setTransVector(), t, and v.
void FairGeoTube::printPoints (FairGeoVolume * volu) virtual
Reimplemented from FairGeoBasicShape.
Definition at line 103 of file FairGeoTube.cxx.
View newest version in sPHENIX GitHub at line 103 of file FairGeoTube.cxx
References FairGeoVolume::getPoint(), FairGeoBasicShape::nPoints, printf(), and v.
Int_t FairGeoTube::readPoints (std::fstream * pFile, FairGeoVolume * volu) virtual
Reimplemented from FairGeoBasicShape.
Definition at line 63 of file FairGeoTube.cxx.
View newest version in sPHENIX GitHub at line 63 of file FairGeoTube.cxx
References FairGeoVolume::createPoints(), FairGeoVolume::getNumPoints(), FairGeoBasicShape::nPoints, FairGeoVolume::setPoint(), x, y, and z.
Bool_t FairGeoTube::writePoints (std::fstream * pFile, FairGeoVolume * volu) virtual
Reimplemented from FairGeoBasicShape.
Definition at line 88 of file FairGeoTube.cxx.
View newest version in sPHENIX GitHub at line 88 of file FairGeoTube.cxx
References FairGeoVolume::getPoint(), FairGeoBasicShape::nPoints, and v.
The documentation for this class was generated from the following files:
EicRoot/blob/master/geobase/FairGeoTube.h
EicRoot/blob/master/geobase/FairGeoTube.cxx