EIC Software: CbmRichRingFitterCOPLight Class Reference
CbmRichRingFitterCOPLight Class Reference
#include <EicRoot/blob/master/rich/standalone/algorithm/CbmRichRingFitterCOPLight.h>
Public Member Functions
CbmRichRingFitterCOPLight ()
virtual ~CbmRichRingFitterCOPLight ()
void DoFit (CbmRichRingLight *ring)
Private Member Functions
void CalcChi2 (CbmRichRingLight *ring)
Private Attributes
std::vector< float > fHitX
std::vector< float > fHitY
int fNofHits
Static Private Attributes
static const int MAX_NOF_HITS_IN_RING = 200
Detailed Description
Definition at line 8 of file CbmRichRingFitterCOPLight.h.
View newest version in sPHENIX GitHub at line 8 of file CbmRichRingFitterCOPLight.h
Constructor & Destructor Documentation
CbmRichRingFitterCOPLight::CbmRichRingFitterCOPLight () inline
Definition at line 12 of file CbmRichRingFitterCOPLight.h.
View newest version in sPHENIX GitHub at line 12 of file CbmRichRingFitterCOPLight.h
References fHitX, fHitY, and MAX_NOF_HITS_IN_RING.
virtual CbmRichRingFitterCOPLight::~CbmRichRingFitterCOPLight () inline virtual
Definition at line 16 of file CbmRichRingFitterCOPLight.h.
View newest version in sPHENIX GitHub at line 16 of file CbmRichRingFitterCOPLight.h
References fHitX, and fHitY.
Member Function Documentation
void CbmRichRingFitterCOPLight::CalcChi2 (CbmRichRingLight * ring) inline private
Definition at line 163 of file CbmRichRingFitterCOPLight.h.
View newest version in sPHENIX GitHub at line 163 of file CbmRichRingFitterCOPLight.h
References d, fHitX, fHitY, CbmRichRingLight::GetCenterX(), CbmRichRingLight::GetCenterY(), CbmRichRingLight::GetNofHits(), CbmRichRingLight::GetRadius(), and CbmRichRingLight::SetChi2().
Referenced by DoFit().
void CbmRichRingFitterCOPLight::DoFit (CbmRichRingLight * ring) inline
Definition at line 33 of file CbmRichRingFitterCOPLight.h.
View newest version in sPHENIX GitHub at line 33 of file CbmRichRingFitterCOPLight.h
References starlightConstants::A2, CalcChi2(), Dy, epsilon, fHitX, fHitY, fNofHits, CbmRichHitLight::fX, CbmRichHitLight::fY, CbmRichRingLight::GetHit(), CbmRichRingLight::GetNofHits(), MAX_NOF_HITS_IN_RING, G4BECAL::radius, CbmRichRingLight::SetCenterX(), CbmRichRingLight::SetCenterY(), and CbmRichRingLight::SetRadius().
Member Data Documentation
std::vector<float> CbmRichRingFitterCOPLight::fHitX private
Definition at line 26 of file CbmRichRingFitterCOPLight.h.
View newest version in sPHENIX GitHub at line 26 of file CbmRichRingFitterCOPLight.h
Referenced by CalcChi2(), CbmRichRingFitterCOPLight(), DoFit(), and ~CbmRichRingFitterCOPLight().
std::vector<float> CbmRichRingFitterCOPLight::fHitY private
Definition at line 27 of file CbmRichRingFitterCOPLight.h.
View newest version in sPHENIX GitHub at line 27 of file CbmRichRingFitterCOPLight.h
Referenced by CalcChi2(), CbmRichRingFitterCOPLight(), DoFit(), and ~CbmRichRingFitterCOPLight().
int CbmRichRingFitterCOPLight::fNofHits private
Definition at line 28 of file CbmRichRingFitterCOPLight.h.
View newest version in sPHENIX GitHub at line 28 of file CbmRichRingFitterCOPLight.h
Referenced by DoFit().
const int CbmRichRingFitterCOPLight::MAX_NOF_HITS_IN_RING = 200 static private
Definition at line 25 of file CbmRichRingFitterCOPLight.h.
View newest version in sPHENIX GitHub at line 25 of file CbmRichRingFitterCOPLight.h
Referenced by CbmRichRingFitterCOPLight(), and DoFit().
The documentation for this class was generated from the following file:
EicRoot/blob/master/rich/standalone/algorithm/CbmRichRingFitterCOPLight.h