EIC Software: Acts::KalmanFitter< propagator_t, updater_t, smoother_t, outlier_finder_t, calibrator_t, input_converter_t, output_converter_t >::Actor< source_link_t, parameters_t > Class Template Reference
Acts::KalmanFitter< propagator_t, updater_t, smoother_t, outlier_finder_t, calibrator_t, input_converter_t, output_converter_t >::Actor< source_link_t, parameters_t > Class Template Reference
Propagator Actor plugin for the KalmanFilter.
Public Types
using TrackStateType = TrackState< source_link_t, parameters_t >
using result_type = KalmanFitterResult< source_link_t >
Broadcast the result_type.
Public Member Functions
Actor (updater_t pUpdater=updater_t(), smoother_t pSmoother=smoother_t(), outlier_finder_t pOutlierFinder=outlier_finder_t(), calibrator_t pCalibrator=calibrator_t())
Explicit constructor with updater and calibrator.
template<typename propagator_state_t , typename stepper_t >
void operator() (propagator_state_t &state, const stepper_t &stepper, result_type &result) const
Kalman actor operation.
template<typename propagator_state_t , typename stepper_t >
void initialize (propagator_state_t &, const stepper_t &, result_type &) const
Kalman actor operation : initialize.
template<typename propagator_state_t , typename stepper_t >
void reverse (propagator_state_t &state, stepper_t &stepper, result_type &result) const
Kalman actor operation : reverse direction.
template<typename propagator_state_t , typename stepper_t >
Result< void > filter (const Surface *surface, propagator_state_t &state, const stepper_t &stepper, result_type &result) const
Kalman actor operation : update.
template<typename propagator_state_t , typename stepper_t >
Result< void > backwardFilter (const Surface *surface, propagator_state_t &state, const stepper_t &stepper, result_type &result) const
Kalman actor operation : backward update.
template<typename propagator_state_t , typename stepper_t >
void materialInteractor (const Surface *surface, propagator_state_t &state, stepper_t &stepper, const MaterialUpdateStage &updateStage=fullUpdate) const
Kalman actor operation : material interaction.
template<typename propagator_state_t , typename stepper_t >
Result< void > finalize (propagator_state_t &state, const stepper_t &stepper, result_type &result) const
Kalman actor operation : finalize.
const Logger & logger () const
Getter for the logger, to support logging macros.
Public Attributes
const Surface * targetSurface = nullptr
The target surface.
std::map< const Surface
*, source_link_t > inputMeasurements
Allows retrieving measurements for a surface.
bool multipleScattering = true
Whether to consider multiple scattering.
bool energyLoss = true
Whether to consider energy loss.
bool backwardFiltering = false
Whether run smoothing as backward filtering.
const Logger * m_logger
Pointer to a logger that is owned by the parent, KalmanFilter.
updater_t m_updater
The Kalman updater.
smoother_t m_smoother
The Kalman smoother.
outlier_finder_t m_outlierFinder
The outlier finder.
calibrator_t m_calibrator
The Measuremetn calibrator.
SurfaceReached targetReached
The Surface beeing.
Detailed Description
template<typename propagator_t, typename updater_t = VoidKalmanUpdater, typename smoother_t = VoidKalmanSmoother, typename outlier_finder_t = VoidOutlierFinder, typename calibrator_t = VoidMeasurementCalibrator, typename input_converter_t = VoidKalmanComponents, typename output_converter_t = VoidKalmanComponents>
template<typename source_link_t, typename parameters_t>
class Acts::KalmanFitter< propagator_t, updater_t, smoother_t, outlier_finder_t, calibrator_t, input_converter_t, output_converter_t >::Actor< source_link_t, parameters_t >
Propagator Actor plugin for the KalmanFilter.
Template Parameters
source_link_t is an type fulfilling the SourceLinkConcept
parameters_t The type of parameters used for "local" paremeters.
The KalmanActor does not rely on the measurements to be sorted along the track.
Definition at line 237 of file KalmanFitter.hpp.
View newest version in sPHENIX GitHub at line 237 of file KalmanFitter.hpp
Member Typedef Documentation
template<typename propagator_t , typename updater_t = VoidKalmanUpdater, typename smoother_t = VoidKalmanSmoother, typename outlier_finder_t = VoidOutlierFinder, typename calibrator_t = VoidMeasurementCalibrator, typename input_converter_t = VoidKalmanComponents, typename output_converter_t = VoidKalmanComponents> template<typename source_link_t , typename parameters_t > using Acts::KalmanFitter< propagator_t, updater_t, smoother_t, outlier_finder_t, calibrator_t, input_converter_t, output_converter_t >::Actor< source_link_t, parameters_t >::result_type = KalmanFitterResult<source_link_t>
Broadcast the result_type.
Definition at line 251 of file KalmanFitter.hpp.
View newest version in sPHENIX GitHub at line 251 of file KalmanFitter.hpp
template<typename propagator_t , typename updater_t = VoidKalmanUpdater, typename smoother_t = VoidKalmanSmoother, typename outlier_finder_t = VoidOutlierFinder, typename calibrator_t = VoidMeasurementCalibrator, typename input_converter_t = VoidKalmanComponents, typename output_converter_t = VoidKalmanComponents> template<typename source_link_t , typename parameters_t > using Acts::KalmanFitter< propagator_t, updater_t, smoother_t, outlier_finder_t, calibrator_t, input_converter_t, output_converter_t >::Actor< source_link_t, parameters_t >::TrackStateType = TrackState<source_link_t, parameters_t>
Definition at line 239 of file KalmanFitter.hpp.
View newest version in sPHENIX GitHub at line 239 of file KalmanFitter.hpp
Constructor & Destructor Documentation
template<typename propagator_t , typename updater_t = VoidKalmanUpdater, typename smoother_t = VoidKalmanSmoother, typename outlier_finder_t = VoidOutlierFinder, typename calibrator_t = VoidMeasurementCalibrator, typename input_converter_t = VoidKalmanComponents, typename output_converter_t = VoidKalmanComponents> template<typename source_link_t , typename parameters_t > Acts::KalmanFitter< propagator_t, updater_t, smoother_t, outlier_finder_t, calibrator_t, input_converter_t, output_converter_t >::Actor< source_link_t, parameters_t >::Actor (updater_t pUpdater = updater_t(), smoother_t pSmoother = smoother_t(), outlier_finder_t pOutlierFinder = outlier_finder_t(), calibrator_t pCalibrator = calibrator_t()) inline
Explicit constructor with updater and calibrator.
Definition at line 242 of file KalmanFitter.hpp.
View newest version in sPHENIX GitHub at line 242 of file KalmanFitter.hpp
Member Function Documentation
template<typename propagator_t , typename updater_t = VoidKalmanUpdater, typename smoother_t = VoidKalmanSmoother, typename outlier_finder_t = VoidOutlierFinder, typename calibrator_t = VoidMeasurementCalibrator, typename input_converter_t = VoidKalmanComponents, typename output_converter_t = VoidKalmanComponents> template<typename source_link_t , typename parameters_t > template<typename propagator_state_t , typename stepper_t > Result<void> Acts::KalmanFitter< propagator_t, updater_t, smoother_t, outlier_finder_t, calibrator_t, input_converter_t, output_converter_t >::Actor< source_link_t, parameters_t >::backwardFilter (const Surface * surface, propagator_state_t & state, const stepper_t & stepper, result_type & result) const inline
Kalman actor operation : backward update.
Template Parameters
propagator_state_t is the type of Propagagor state
stepper_t Type of the stepper
Parameters
surface The surface where the update happens
state The mutable propagator state object
stepper The stepper in use
result The mutable result state object
Definition at line 627 of file KalmanFitter.hpp.
View newest version in sPHENIX GitHub at line 627 of file KalmanFitter.hpp
References ACTS_ERROR, ACTS_VERBOSE, Acts::TrackStatePropMask::All, Acts::backward, Acts::KalmanFitterResult< source_link_t >::fittedStates, Acts::GeometryObject::geoID(), Acts::KalmanFitterResult< source_link_t >::passedAgainSurfaces, Acts::postUpdate, Acts::preUpdate, and Acts::KalmanFitterResult< source_link_t >::trackTip.
Referenced by Acts::KalmanFitter< propagator_t, updater_t, smoother_t, outlier_finder_t, calibrator_t, input_converter_t, output_converter_t >::Actor< source_link_t, parameters_t >::operator()().
template<typename propagator_t , typename updater_t = VoidKalmanUpdater, typename smoother_t = VoidKalmanSmoother, typename outlier_finder_t = VoidOutlierFinder, typename calibrator_t = VoidMeasurementCalibrator, typename input_converter_t = VoidKalmanComponents, typename output_converter_t = VoidKalmanComponents> template<typename source_link_t , typename parameters_t > template<typename propagator_state_t , typename stepper_t > Result<void> Acts::KalmanFitter< propagator_t, updater_t, smoother_t, outlier_finder_t, calibrator_t, input_converter_t, output_converter_t >::Actor< source_link_t, parameters_t >::filter (const Surface * surface, propagator_state_t & state, const stepper_t & stepper, result_type & result) const inline
Kalman actor operation : update.
Template Parameters
propagator_state_t is the type of Propagagor state
stepper_t Type of the stepper
Parameters
surface The surface where the update happens
state The mutable propagator state object
stepper The stepper in use
result The mutable result state object
Definition at line 466 of file KalmanFitter.hpp.
View newest version in sPHENIX GitHub at line 466 of file KalmanFitter.hpp
References ACTS_ERROR, ACTS_VERBOSE, Acts::TrackStatePropMask::All, Acts::Surface::associatedDetectorElement(), Acts::TrackStatePropMask::Calibrated, Acts::TrackStatePropMask::Filtered, Acts::KalmanFitterResult< source_link_t >::fittedStates, Acts::forward, Acts::fullUpdate, Acts::GeometryObject::geoID(), Acts::Surface::getSharedPtr(), Acts::HoleFlag, Acts::MaterialFlag, Acts::MeasurementFlag, Acts::KalmanFitterResult< source_link_t >::measurementStates, Acts::KalmanFitterResult< source_link_t >::missedActiveSurfaces, Acts::OutlierFlag, Acts::ParameterFlag, Acts::postUpdate, Acts::preUpdate, Acts::KalmanFitterResult< source_link_t >::processedStates, Acts::Surface::surfaceMaterial(), Acts::KalmanFitterResult< source_link_t >::trackTip, and Acts::TrackStatePropMask::Uncalibrated.
Referenced by Acts::KalmanFitter< propagator_t, updater_t, smoother_t, outlier_finder_t, calibrator_t, input_converter_t, output_converter_t >::Actor< source_link_t, parameters_t >::operator()().
template<typename propagator_t , typename updater_t = VoidKalmanUpdater, typename smoother_t = VoidKalmanSmoother, typename outlier_finder_t = VoidOutlierFinder, typename calibrator_t = VoidMeasurementCalibrator, typename input_converter_t = VoidKalmanComponents, typename output_converter_t = VoidKalmanComponents> template<typename source_link_t , typename parameters_t > template<typename propagator_state_t , typename stepper_t > Result<void> Acts::KalmanFitter< propagator_t, updater_t, smoother_t, outlier_finder_t, calibrator_t, input_converter_t, output_converter_t >::Actor< source_link_t, parameters_t >::finalize (propagator_state_t & state, const stepper_t & stepper, result_type & result) const inline
Kalman actor operation : finalize.
Template Parameters
propagator_state_t is the type of Propagagor state
stepper_t Type of the stepper
Parameters
state is the mutable propagator state object
stepper The stepper in use
result is the mutable result state object
Definition at line 800 of file KalmanFitter.hpp.
View newest version in sPHENIX GitHub at line 800 of file KalmanFitter.hpp
References Acts::KalmanFitterResult< source_link_t >::fittedStates, Acts::MeasurementFlag, Acts::KalmanFitterResult< source_link_t >::measurementStates, Acts::KalmanFitterResult< source_link_t >::smoothed, and Acts::KalmanFitterResult< source_link_t >::trackTip.
Referenced by Acts::KalmanFitter< propagator_t, updater_t, smoother_t, outlier_finder_t, calibrator_t, input_converter_t, output_converter_t >::Actor< source_link_t, parameters_t >::operator()().
template<typename propagator_t , typename updater_t = VoidKalmanUpdater, typename smoother_t = VoidKalmanSmoother, typename outlier_finder_t = VoidOutlierFinder, typename calibrator_t = VoidMeasurementCalibrator, typename input_converter_t = VoidKalmanComponents, typename output_converter_t = VoidKalmanComponents> template<typename source_link_t , typename parameters_t > template<typename propagator_state_t , typename stepper_t > void Acts::KalmanFitter< propagator_t, updater_t, smoother_t, outlier_finder_t, calibrator_t, input_converter_t, output_converter_t >::Actor< source_link_t, parameters_t >::initialize (propagator_state_t & , const stepper_t & , result_type &) const inline
Kalman actor operation : initialize.
Template Parameters
propagator_state_t is the type of Propagagor state
stepper_t Type of the stepper
Parameters
state is the mutable propagator state object
stepper The stepper in use
result is the mutable result state object
Definition at line 390 of file KalmanFitter.hpp.
View newest version in sPHENIX GitHub at line 390 of file KalmanFitter.hpp
Referenced by Acts::KalmanFitter< propagator_t, updater_t, smoother_t, outlier_finder_t, calibrator_t, input_converter_t, output_converter_t >::Actor< source_link_t, parameters_t >::operator()().
template<typename propagator_t , typename updater_t = VoidKalmanUpdater, typename smoother_t = VoidKalmanSmoother, typename outlier_finder_t = VoidOutlierFinder, typename calibrator_t = VoidMeasurementCalibrator, typename input_converter_t = VoidKalmanComponents, typename output_converter_t = VoidKalmanComponents> template<typename source_link_t , typename parameters_t > const Logger& Acts::KalmanFitter< propagator_t, updater_t, smoother_t, outlier_finder_t, calibrator_t, input_converter_t, output_converter_t >::Actor< source_link_t, parameters_t >::logger () const inline
Getter for the logger, to support logging macros.
Definition at line 871 of file KalmanFitter.hpp.
View newest version in sPHENIX GitHub at line 871 of file KalmanFitter.hpp
template<typename propagator_t , typename updater_t = VoidKalmanUpdater, typename smoother_t = VoidKalmanSmoother, typename outlier_finder_t = VoidOutlierFinder, typename calibrator_t = VoidMeasurementCalibrator, typename input_converter_t = VoidKalmanComponents, typename output_converter_t = VoidKalmanComponents> template<typename source_link_t , typename parameters_t > template<typename propagator_state_t , typename stepper_t > void Acts::KalmanFitter< propagator_t, updater_t, smoother_t, outlier_finder_t, calibrator_t, input_converter_t, output_converter_t >::Actor< source_link_t, parameters_t >::materialInteractor (const Surface * surface, propagator_state_t & state, stepper_t & stepper, const MaterialUpdateStage & updateStage = fullUpdate) const inline
Kalman actor operation : material interaction.
Template Parameters
propagator_state_t is the type of Propagagor state
stepper_t Type of the stepper
Parameters
surface The surface where the material interaction happens
state The mutable propagator state object
stepper The stepper in use
updateStage The materal update stage
Definition at line 748 of file KalmanFitter.hpp.
View newest version in sPHENIX GitHub at line 748 of file KalmanFitter.hpp
References ACTS_VERBOSE, Acts::detail::PointwiseMaterialInteraction::Eloss, Acts::detail::PointwiseMaterialInteraction::evaluateMaterialProperties(), Acts::detail::PointwiseMaterialInteraction::evaluatePointwiseMaterialInteraction(), Acts::GeometryObject::geoID(), Acts::Surface::surfaceMaterial(), Acts::detail::PointwiseMaterialInteraction::updateState(), Acts::detail::PointwiseMaterialInteraction::variancePhi, Acts::detail::PointwiseMaterialInteraction::varianceQoverP, and Acts::detail::PointwiseMaterialInteraction::varianceTheta.
template<typename propagator_t , typename updater_t = VoidKalmanUpdater, typename smoother_t = VoidKalmanSmoother, typename outlier_finder_t = VoidOutlierFinder, typename calibrator_t = VoidMeasurementCalibrator, typename input_converter_t = VoidKalmanComponents, typename output_converter_t = VoidKalmanComponents> template<typename source_link_t , typename parameters_t > template<typename propagator_state_t , typename stepper_t > void Acts::KalmanFitter< propagator_t, updater_t, smoother_t, outlier_finder_t, calibrator_t, input_converter_t, output_converter_t >::Actor< source_link_t, parameters_t >::operator() (propagator_state_t & state, const stepper_t & stepper, result_type & result) const inline
Kalman actor operation.
Template Parameters
propagator_state_t is the type of Propagagor state
stepper_t Type of the stepper
Parameters
state is the mutable propagator state object
stepper The stepper in use
result is the mutable result state object
Definition at line 277 of file KalmanFitter.hpp.
View newest version in sPHENIX GitHub at line 277 of file KalmanFitter.hpp
References ACTS_ERROR, ACTS_VERBOSE, Acts::backward, Acts::KalmanFitter< propagator_t, updater_t, smoother_t, outlier_finder_t, calibrator_t, input_converter_t, output_converter_t >::Actor< source_link_t, parameters_t >::backwardFilter(), Acts::KalmanFitter< propagator_t, updater_t, smoother_t, outlier_finder_t, calibrator_t, input_converter_t, output_converter_t >::Actor< source_link_t, parameters_t >::backwardFiltering, Acts::KalmanFitter< propagator_t, updater_t, smoother_t, outlier_finder_t, calibrator_t, input_converter_t, output_converter_t >::Actor< source_link_t, parameters_t >::filter(), Acts::KalmanFitter< propagator_t, updater_t, smoother_t, outlier_finder_t, calibrator_t, input_converter_t, output_converter_t >::Actor< source_link_t, parameters_t >::finalize(), Acts::KalmanFitterResult< source_link_t >::fittedParameters, Acts::KalmanFitterResult< source_link_t >::fittedStates, Acts::forward, Acts::KalmanFitterResult< source_link_t >::forwardFiltered, Acts::KalmanFitter< propagator_t, updater_t, smoother_t, outlier_finder_t, calibrator_t, input_converter_t, output_converter_t >::Actor< source_link_t, parameters_t >::initialize(), Acts::KalmanFitterResult< source_link_t >::initialized, Acts::KalmanFitter< propagator_t, updater_t, smoother_t, outlier_finder_t, calibrator_t, input_converter_t, output_converter_t >::Actor< source_link_t, parameters_t >::inputMeasurements, Acts::detail_lt::IndexData::kInvalid, Acts::KalmanFitterResult< source_link_t >::measurementStates, Acts::KalmanFitterResult< source_link_t >::passedAgainSurfaces, analysis::res, Acts::KalmanFitterResult< source_link_t >::result, Acts::KalmanFitter< propagator_t, updater_t, smoother_t, outlier_finder_t, calibrator_t, input_converter_t, output_converter_t >::Actor< source_link_t, parameters_t >::reverse(), Acts::KalmanFitterResult< source_link_t >::smoothed, Acts::KalmanFitter< propagator_t, updater_t, smoother_t, outlier_finder_t, calibrator_t, input_converter_t, output_converter_t >::Actor< source_link_t, parameters_t >::targetReached, Acts::KalmanFitter< propagator_t, updater_t, smoother_t, outlier_finder_t, calibrator_t, input_converter_t, output_converter_t >::Actor< source_link_t, parameters_t >::targetSurface, and Acts::KalmanFitterResult< source_link_t >::trackTip.
template<typename propagator_t , typename updater_t = VoidKalmanUpdater, typename smoother_t = VoidKalmanSmoother, typename outlier_finder_t = VoidOutlierFinder, typename calibrator_t = VoidMeasurementCalibrator, typename input_converter_t = VoidKalmanComponents, typename output_converter_t = VoidKalmanComponents> template<typename source_link_t , typename parameters_t > template<typename propagator_state_t , typename stepper_t > void Acts::KalmanFitter< propagator_t, updater_t, smoother_t, outlier_finder_t, calibrator_t, input_converter_t, output_converter_t >::Actor< source_link_t, parameters_t >::reverse (propagator_state_t & state, stepper_t & stepper, result_type & result) const inline
Kalman actor operation : reverse direction.
Template Parameters
propagator_state_t is the type of Propagagor state
stepper_t Type of the stepper
Parameters
state is the mutable propagator state object
stepper The stepper in use
result is the mutable result state object
Definition at line 402 of file KalmanFitter.hpp.
View newest version in sPHENIX GitHub at line 402 of file KalmanFitter.hpp
References Acts::backward, Acts::KalmanFitterResult< source_link_t >::fittedStates, Acts::KalmanFitterResult< source_link_t >::passedAgainSurfaces, and Acts::KalmanFitterResult< source_link_t >::trackTip.
Referenced by Acts::KalmanFitter< propagator_t, updater_t, smoother_t, outlier_finder_t, calibrator_t, input_converter_t, output_converter_t >::Actor< source_link_t, parameters_t >::operator()().
Member Data Documentation
template<typename propagator_t , typename updater_t = VoidKalmanUpdater, typename smoother_t = VoidKalmanSmoother, typename outlier_finder_t = VoidOutlierFinder, typename calibrator_t = VoidMeasurementCalibrator, typename input_converter_t = VoidKalmanComponents, typename output_converter_t = VoidKalmanComponents> template<typename source_link_t , typename parameters_t > bool Acts::KalmanFitter< propagator_t, updater_t, smoother_t, outlier_finder_t, calibrator_t, input_converter_t, output_converter_t >::Actor< source_link_t, parameters_t >::backwardFiltering = false
Whether run smoothing as backward filtering.
Definition at line 266 of file KalmanFitter.hpp.
View newest version in sPHENIX GitHub at line 266 of file KalmanFitter.hpp
Referenced by Acts::KalmanFitter< propagator_t, updater_t, smoother_t, outlier_finder_t, calibrator_t, input_converter_t, output_converter_t >::Actor< source_link_t, parameters_t >::operator()().
template<typename propagator_t , typename updater_t = VoidKalmanUpdater, typename smoother_t = VoidKalmanSmoother, typename outlier_finder_t = VoidOutlierFinder, typename calibrator_t = VoidMeasurementCalibrator, typename input_converter_t = VoidKalmanComponents, typename output_converter_t = VoidKalmanComponents> template<typename source_link_t , typename parameters_t > bool Acts::KalmanFitter< propagator_t, updater_t, smoother_t, outlier_finder_t, calibrator_t, input_converter_t, output_converter_t >::Actor< source_link_t, parameters_t >::energyLoss = true
Whether to consider energy loss.
Definition at line 263 of file KalmanFitter.hpp.
View newest version in sPHENIX GitHub at line 263 of file KalmanFitter.hpp
template<typename propagator_t , typename updater_t = VoidKalmanUpdater, typename smoother_t = VoidKalmanSmoother, typename outlier_finder_t = VoidOutlierFinder, typename calibrator_t = VoidMeasurementCalibrator, typename input_converter_t = VoidKalmanComponents, typename output_converter_t = VoidKalmanComponents> template<typename source_link_t , typename parameters_t > std::map<const Surface*, source_link_t> Acts::KalmanFitter< propagator_t, updater_t, smoother_t, outlier_finder_t, calibrator_t, input_converter_t, output_converter_t >::Actor< source_link_t, parameters_t >::inputMeasurements
Allows retrieving measurements for a surface.
Definition at line 257 of file KalmanFitter.hpp.
View newest version in sPHENIX GitHub at line 257 of file KalmanFitter.hpp
Referenced by Acts::KalmanFitter< propagator_t, updater_t, smoother_t, outlier_finder_t, calibrator_t, input_converter_t, output_converter_t >::Actor< source_link_t, parameters_t >::operator()().
template<typename propagator_t , typename updater_t = VoidKalmanUpdater, typename smoother_t = VoidKalmanSmoother, typename outlier_finder_t = VoidOutlierFinder, typename calibrator_t = VoidMeasurementCalibrator, typename input_converter_t = VoidKalmanComponents, typename output_converter_t = VoidKalmanComponents> template<typename source_link_t , typename parameters_t > calibrator_t Acts::KalmanFitter< propagator_t, updater_t, smoother_t, outlier_finder_t, calibrator_t, input_converter_t, output_converter_t >::Actor< source_link_t, parameters_t >::m_calibrator
The Measuremetn calibrator.
Definition at line 883 of file KalmanFitter.hpp.
View newest version in sPHENIX GitHub at line 883 of file KalmanFitter.hpp
template<typename propagator_t , typename updater_t = VoidKalmanUpdater, typename smoother_t = VoidKalmanSmoother, typename outlier_finder_t = VoidOutlierFinder, typename calibrator_t = VoidMeasurementCalibrator, typename input_converter_t = VoidKalmanComponents, typename output_converter_t = VoidKalmanComponents> template<typename source_link_t , typename parameters_t > const Logger* Acts::KalmanFitter< propagator_t, updater_t, smoother_t, outlier_finder_t, calibrator_t, input_converter_t, output_converter_t >::Actor< source_link_t, parameters_t >::m_logger
Pointer to a logger that is owned by the parent, KalmanFilter.
Definition at line 868 of file KalmanFitter.hpp.
View newest version in sPHENIX GitHub at line 868 of file KalmanFitter.hpp
template<typename propagator_t , typename updater_t = VoidKalmanUpdater, typename smoother_t = VoidKalmanSmoother, typename outlier_finder_t = VoidOutlierFinder, typename calibrator_t = VoidMeasurementCalibrator, typename input_converter_t = VoidKalmanComponents, typename output_converter_t = VoidKalmanComponents> template<typename source_link_t , typename parameters_t > outlier_finder_t Acts::KalmanFitter< propagator_t, updater_t, smoother_t, outlier_finder_t, calibrator_t, input_converter_t, output_converter_t >::Actor< source_link_t, parameters_t >::m_outlierFinder
The outlier finder.
Definition at line 880 of file KalmanFitter.hpp.
View newest version in sPHENIX GitHub at line 880 of file KalmanFitter.hpp
template<typename propagator_t , typename updater_t = VoidKalmanUpdater, typename smoother_t = VoidKalmanSmoother, typename outlier_finder_t = VoidOutlierFinder, typename calibrator_t = VoidMeasurementCalibrator, typename input_converter_t = VoidKalmanComponents, typename output_converter_t = VoidKalmanComponents> template<typename source_link_t , typename parameters_t > smoother_t Acts::KalmanFitter< propagator_t, updater_t, smoother_t, outlier_finder_t, calibrator_t, input_converter_t, output_converter_t >::Actor< source_link_t, parameters_t >::m_smoother
The Kalman smoother.
Definition at line 877 of file KalmanFitter.hpp.
View newest version in sPHENIX GitHub at line 877 of file KalmanFitter.hpp
template<typename propagator_t , typename updater_t = VoidKalmanUpdater, typename smoother_t = VoidKalmanSmoother, typename outlier_finder_t = VoidOutlierFinder, typename calibrator_t = VoidMeasurementCalibrator, typename input_converter_t = VoidKalmanComponents, typename output_converter_t = VoidKalmanComponents> template<typename source_link_t , typename parameters_t > updater_t Acts::KalmanFitter< propagator_t, updater_t, smoother_t, outlier_finder_t, calibrator_t, input_converter_t, output_converter_t >::Actor< source_link_t, parameters_t >::m_updater
The Kalman updater.
Definition at line 874 of file KalmanFitter.hpp.
View newest version in sPHENIX GitHub at line 874 of file KalmanFitter.hpp
template<typename propagator_t , typename updater_t = VoidKalmanUpdater, typename smoother_t = VoidKalmanSmoother, typename outlier_finder_t = VoidOutlierFinder, typename calibrator_t = VoidMeasurementCalibrator, typename input_converter_t = VoidKalmanComponents, typename output_converter_t = VoidKalmanComponents> template<typename source_link_t , typename parameters_t > bool Acts::KalmanFitter< propagator_t, updater_t, smoother_t, outlier_finder_t, calibrator_t, input_converter_t, output_converter_t >::Actor< source_link_t, parameters_t >::multipleScattering = true
Whether to consider multiple scattering.
Definition at line 260 of file KalmanFitter.hpp.
View newest version in sPHENIX GitHub at line 260 of file KalmanFitter.hpp
template<typename propagator_t , typename updater_t = VoidKalmanUpdater, typename smoother_t = VoidKalmanSmoother, typename outlier_finder_t = VoidOutlierFinder, typename calibrator_t = VoidMeasurementCalibrator, typename input_converter_t = VoidKalmanComponents, typename output_converter_t = VoidKalmanComponents> template<typename source_link_t , typename parameters_t > SurfaceReached Acts::KalmanFitter< propagator_t, updater_t, smoother_t, outlier_finder_t, calibrator_t, input_converter_t, output_converter_t >::Actor< source_link_t, parameters_t >::targetReached
The Surface beeing.
Definition at line 886 of file KalmanFitter.hpp.
View newest version in sPHENIX GitHub at line 886 of file KalmanFitter.hpp
Referenced by Acts::KalmanFitter< propagator_t, updater_t, smoother_t, outlier_finder_t, calibrator_t, input_converter_t, output_converter_t >::Actor< source_link_t, parameters_t >::operator()().
template<typename propagator_t , typename updater_t = VoidKalmanUpdater, typename smoother_t = VoidKalmanSmoother, typename outlier_finder_t = VoidOutlierFinder, typename calibrator_t = VoidMeasurementCalibrator, typename input_converter_t = VoidKalmanComponents, typename output_converter_t = VoidKalmanComponents> template<typename source_link_t , typename parameters_t > const Surface* Acts::KalmanFitter< propagator_t, updater_t, smoother_t, outlier_finder_t, calibrator_t, input_converter_t, output_converter_t >::Actor< source_link_t, parameters_t >::targetSurface = nullptr
The target surface.
Definition at line 254 of file KalmanFitter.hpp.
View newest version in sPHENIX GitHub at line 254 of file KalmanFitter.hpp
Referenced by Acts::KalmanFitter< propagator_t, updater_t, smoother_t, outlier_finder_t, calibrator_t, input_converter_t, output_converter_t >::Actor< source_link_t, parameters_t >::operator()().
The documentation for this class was generated from the following file:
fun4all_acts/blob/master/Core/include/Acts/Fitter/KalmanFitter.hpp