EIC Software: RawDigitBuilderTTL Class Reference
RawDigitBuilderTTL Class Reference
SubsysReco module creating calorimeter tower objects (RawTowerv1) from hits (PHG4Hit) using j,k indeces of these hits.
#include <fun4all_eicdetectors/blob/master/simulation/g4simulation/g4ttl/RawDigitBuilderTTL.h>
Public Member Functions
RawDigitBuilderTTL (const std::string &name="RawDigitBuilderTTL")
~RawDigitBuilderTTL () override
int Init (PHCompositeNode *topNode) override
module initialization
int InitRun (PHCompositeNode *topNode) override
run initialization
int process_event (PHCompositeNode *topNode) override
event processing
int End (PHCompositeNode *topNode) override
end of process
void SetZClustering (const bool make_z_clustering)
option to turn off z-dimension clustering
bool GetZClustering () const
void Detector (const std::string &d)
Public Member Functions inherited from SubsysReco
~SubsysReco () override
virtual int EndRun (const int)
Called at the end of each run.
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
void Print (const std::string &="ALL") const override
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Private Member Functions
void CreateNodes (PHCompositeNode *topNode)
void PrintClusters (PHCompositeNode *topNode)
Private Attributes
TrkrClusterContainer * m_clusterlist
std::string m_Detector
std::string m_SimTowerNodePrefix
double m_Emin
bool m_makeZClustering
std::map< std::string, double > m_GlobalParameterMap
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = INT_MAX - 10
}
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Detailed Description
SubsysReco module creating calorimeter tower objects (RawTowerv1) from hits (PHG4Hit) using j,k indeces of these hits.
Definition at line 34 of file RawDigitBuilderTTL.h.
View newest version in sPHENIX GitHub at line 34 of file RawDigitBuilderTTL.h
Constructor & Destructor Documentation
RawDigitBuilderTTL::RawDigitBuilderTTL (const std::string & name = "RawDigitBuilderTTL")
Definition at line 50 of file RawDigitBuilderTTL.cc.
View newest version in sPHENIX GitHub at line 50 of file RawDigitBuilderTTL.cc
RawDigitBuilderTTL::~RawDigitBuilderTTL () inline override
Definition at line 38 of file RawDigitBuilderTTL.h.
View newest version in sPHENIX GitHub at line 38 of file RawDigitBuilderTTL.h
Member Function Documentation
void RawDigitBuilderTTL::CreateNodes (PHCompositeNode * topNode) private
Define minimum tower energy. After processing an event, towers with lower energy are will be deleted. Create nodes for output.
Name of output node for RawTowerContainer: "TOWER_" + detector;
Definition at line 173 of file RawDigitBuilderTTL.cc.
View newest version in sPHENIX GitHub at line 173 of file RawDigitBuilderTTL.cc
References PHCompositeNode::addNode(), PHNodeIterator::findFirst(), m_Detector, and PHWHERE.
Referenced by InitRun().
void RawDigitBuilderTTL::Detector (const std::string & d)
Name of the detector node the G4Hits should be taken from.
Definition at line 167 of file RawDigitBuilderTTL.cc.
View newest version in sPHENIX GitHub at line 167 of file RawDigitBuilderTTL.cc
References d, and m_Detector.
Referenced by ETTL_Clustering(), and FTTL_Clustering().
int RawDigitBuilderTTL::End (PHCompositeNode * topNode) inline override virtual
end of process
Reimplemented from SubsysReco.
Definition at line 50 of file RawDigitBuilderTTL.h.
View newest version in sPHENIX GitHub at line 50 of file RawDigitBuilderTTL.h
bool RawDigitBuilderTTL::GetZClustering () const inline
Definition at line 57 of file RawDigitBuilderTTL.h.
View newest version in sPHENIX GitHub at line 57 of file RawDigitBuilderTTL.h
References m_makeZClustering.
int RawDigitBuilderTTL::Init (PHCompositeNode * topNode) inline override virtual
module initialization
Reimplemented from SubsysReco.
Definition at line 41 of file RawDigitBuilderTTL.h.
View newest version in sPHENIX GitHub at line 41 of file RawDigitBuilderTTL.h
int RawDigitBuilderTTL::InitRun (PHCompositeNode * topNode) override virtual
run initialization
Reimplemented from SubsysReco.
Definition at line 62 of file RawDigitBuilderTTL.cc.
View newest version in sPHENIX GitHub at line 62 of file RawDigitBuilderTTL.cc
References PHCompositeNode::addNode(), CreateNodes(), Acts::UnitConstants::e, Fun4AllReturnCodes::EVENT_OK, exit(), PHNodeIterator::findFirst(), and PHWHERE.
void RawDigitBuilderTTL::PrintClusters (PHCompositeNode * topNode) private
Definition at line 203 of file RawDigitBuilderTTL.cc.
View newest version in sPHENIX GitHub at line 203 of file RawDigitBuilderTTL.cc
References TrkrClusterContainer::identify(), TrkrClusterContainer::size(), and Fun4AllBase::Verbosity().
int RawDigitBuilderTTL::process_event (PHCompositeNode * topNode) override virtual
event processing
Reimplemented from SubsysReco.
Definition at line 108 of file RawDigitBuilderTTL.cc.
View newest version in sPHENIX GitHub at line 108 of file RawDigitBuilderTTL.cc
References Fun4AllReturnCodes::ABORTRUN, TrkrClusterContainer::addCluster(), Fun4AllReturnCodes::EVENT_OK, exit(), TrkrDefs::genHitSetKey(), PHG4Hit::get_edep(), PHG4Hit::get_index_j(), PHG4Hit::get_local_x(), PHG4Hit::get_local_y(), PHG4Hit::get_local_z(), PHG4Hit::get_strip_y_index(), PHG4Hit::get_strip_z_index(), PHG4HitContainer::getHits(), m_clusterlist, m_Detector, PHWHERE, and TrkrDefs::ttl.
void RawDigitBuilderTTL::SetZClustering (const bool make_z_clustering) inline
option to turn off z-dimension clustering
Definition at line 53 of file RawDigitBuilderTTL.h.
View newest version in sPHENIX GitHub at line 53 of file RawDigitBuilderTTL.h
References m_makeZClustering.
Member Data Documentation
TrkrClusterContainer* RawDigitBuilderTTL::m_clusterlist private
Definition at line 81 of file RawDigitBuilderTTL.h.
View newest version in sPHENIX GitHub at line 81 of file RawDigitBuilderTTL.h
Referenced by process_event().
std::string RawDigitBuilderTTL::m_Detector private
Read geometry information from table stored in text-file
Definition at line 91 of file RawDigitBuilderTTL.h.
View newest version in sPHENIX GitHub at line 91 of file RawDigitBuilderTTL.h
Referenced by CreateNodes(), Detector(), and process_event().
double RawDigitBuilderTTL::m_Emin private
Definition at line 96 of file RawDigitBuilderTTL.h.
View newest version in sPHENIX GitHub at line 96 of file RawDigitBuilderTTL.h
std::map<std::string, double> RawDigitBuilderTTL::m_GlobalParameterMap private
Definition at line 100 of file RawDigitBuilderTTL.h.
View newest version in sPHENIX GitHub at line 100 of file RawDigitBuilderTTL.h
bool RawDigitBuilderTTL::m_makeZClustering private
Definition at line 99 of file RawDigitBuilderTTL.h.
View newest version in sPHENIX GitHub at line 99 of file RawDigitBuilderTTL.h
Referenced by GetZClustering(), and SetZClustering().
std::string RawDigitBuilderTTL::m_SimTowerNodePrefix private
Definition at line 92 of file RawDigitBuilderTTL.h.
View newest version in sPHENIX GitHub at line 92 of file RawDigitBuilderTTL.h
The documentation for this class was generated from the following files:
fun4all_eicdetectors/blob/master/simulation/g4simulation/g4ttl/RawDigitBuilderTTL.h
fun4all_eicdetectors/blob/master/simulation/g4simulation/g4ttl/RawDigitBuilderTTL.cc