EIC Software: PHG4EICForwardEcalDetector Class Reference
PHG4EICForwardEcalDetector Class Reference
#include <fun4all_eicdetectors/blob/master/simulation/g4simulation/g4eiccalos/PHG4EICForwardEcalDetector.h>
Classes
struct towerposition
Public Member Functions
PHG4EICForwardEcalDetector (PHG4Subsystem *subsys, PHCompositeNode *Node, PHParameters *parameters, const std::string &dnam)
constructor
virtual ~PHG4EICForwardEcalDetector ()
destructor
virtual void ConstructMe (G4LogicalVolume *world) override
construct
void SetTowerDimensions (G4double dx, G4double dy, G4double dz)
void SetMaterialScintillator (G4String material)
void SetMaterialAbsorber (G4String material)
Public Member Functions inherited from PHG4ForwardEcalDetector
PHG4ForwardEcalDetector (PHG4Subsystem *subsys, PHCompositeNode *Node, PHParameters *parameters, const std::string &dnam)
constructor
virtual ~PHG4ForwardEcalDetector ()
destructor
int IsInForwardEcal (G4VPhysicalVolume *) const
void SetTowerDimensions (double dx, double dy, double dz, int type)
void DoFullLightProp (bool doProp)
void SetPlace (double place_in_x, double place_in_y, double place_in_z)
void SetPlaceX (double place_x)
void SetPlaceY (double place_y)
void SetPlaceZ (double place_z)
double GetPlaceX () const
double GetPlaceY () const
double GetPlaceZ () const
void SetXRot (double rot_in_x)
void SetYRot (double rot_in_y)
void SetZRot (double rot_in_z)
double GetXRot () const
double GetYRot () const
double GetZRot () const
double GetRMin (int i) const
double GetRMax (int i) const
void SetRMin (int i, double val)
void SetRMax (int i, double val)
double GetdZ () const
void SetdZ (double val)
void SuperDetector (const std::string &name)
const std::string SuperDetector () const
int get_Layer () const
int get_TowerType () const
PHG4ForwardEcalDisplayAction * GetDisplayAction ()
Public Member Functions inherited from PHG4Detector
PHG4Detector ()=delete
constructor
PHG4Detector (PHG4Subsystem *subsys, PHCompositeNode *Node, const std::string &nam)
virtual ~PHG4Detector (void)
destructor
virtual void Construct (G4LogicalVolume *world) final
construct method
virtual void PostConstruction ()
Optional PostConstruction call after all geometry is constructed.
virtual void Verbosity (const int v)
virtual int Verbosity () const
virtual G4UserSteppingAction * GetSteppingAction ()
virtual std::string GetName () const
virtual void OverlapCheck (const bool chk)
virtual bool OverlapCheck () const
virtual void Print (const std::string &="ALL") const
virtual int DisplayVolume (G4VSolid *volume, G4LogicalVolume *logvol, G4RotationMatrix *rotm=nullptr)
virtual int DisplayVolume (G4LogicalVolume *checksolid, G4LogicalVolume *logvol, G4RotationMatrix *rotm=nullptr)
virtual PHCompositeNode * topNode ()
virtual PHG4Subsystem * GetMySubsystem ()
Private Member Functions
G4LogicalVolume * ConstructTower ()
int PlaceTower (G4LogicalVolume *envelope, G4LogicalVolume *tower)
int ParseParametersFromTable ()
Private Attributes
std::map< std::string,
towerposition > _map_tower
G4double _tower_dx
G4double _tower_dy
G4double _tower_dz
G4String _materialScintillator
G4String _materialAbsorber
Additional Inherited Members
Static Public Member Functions inherited from PHG4Detector
static G4Material * GetDetectorMaterial (const std::string &name, const bool quit=true)
static G4Element * GetDetectorElement (const std::string &name, const bool quit=true)
Protected Member Functions inherited from PHG4ForwardEcalDetector
const std::string TowerLogicNamePrefix () const
PHParameters * GetParams () const
void AbsorberLogicalVolSetInsert (G4LogicalVolume *logvol)
void ScintiLogicalVolSetInsert (G4LogicalVolume *logvol)
std::map< std::string, double >
::const_iterator FindIter (const std::string &name)
std::map< std::string, double >
::const_iterator EndIter ()
void InsertParam (const std::string &parname, double parval)
Protected Attributes inherited from PHG4ForwardEcalDetector
bool m_doLightProp
Detailed Description
Definition at line 25 of file PHG4EICForwardEcalDetector.h.
View newest version in sPHENIX GitHub at line 25 of file PHG4EICForwardEcalDetector.h
Constructor & Destructor Documentation
PHG4EICForwardEcalDetector::PHG4EICForwardEcalDetector (PHG4Subsystem * subsys, PHCompositeNode * Node, PHParameters * parameters, const std::string & dnam)
constructor
Definition at line 34 of file PHG4EICForwardEcalDetector.cc.
View newest version in sPHENIX GitHub at line 34 of file PHG4EICForwardEcalDetector.cc
virtual PHG4EICForwardEcalDetector::~PHG4EICForwardEcalDetector () inline virtual
destructor
Definition at line 32 of file PHG4EICForwardEcalDetector.h.
View newest version in sPHENIX GitHub at line 32 of file PHG4EICForwardEcalDetector.h
Member Function Documentation
void PHG4EICForwardEcalDetector::ConstructMe (G4LogicalVolume * world) override virtual
construct
Reimplemented from PHG4ForwardEcalDetector.
Definition at line 45 of file PHG4EICForwardEcalDetector.cc.
View newest version in sPHENIX GitHub at line 45 of file PHG4EICForwardEcalDetector.cc
References PHG4ForwardEcalDisplayAction::AddVolume(), ConstructTower(), PHG4Detector::GetDetectorMaterial(), PHG4ForwardEcalDetector::GetDisplayAction(), PHG4ForwardEcalDetector::GetdZ(), PHG4ForwardEcalDetector::GetPlaceX(), PHG4ForwardEcalDetector::GetPlaceY(), PHG4ForwardEcalDetector::GetPlaceZ(), PHG4ForwardEcalDetector::GetRMax(), PHG4ForwardEcalDetector::GetRMin(), PHG4ForwardEcalDetector::GetXRot(), PHG4ForwardEcalDetector::GetYRot(), PHG4ForwardEcalDetector::GetZRot(), M_PI, PHG4Detector::OverlapCheck(), ParseParametersFromTable(), PlaceTower(), PHG4ForwardEcalDetector::TowerLogicNamePrefix(), and PHG4Detector::Verbosity().
G4LogicalVolume * PHG4EICForwardEcalDetector::ConstructTower () private
Definition at line 94 of file PHG4EICForwardEcalDetector.cc.
View newest version in sPHENIX GitHub at line 94 of file PHG4EICForwardEcalDetector.cc
References _materialAbsorber, _materialScintillator, _tower_dx, _tower_dy, _tower_dz, PHG4ForwardEcalDetector::AbsorberLogicalVolSetInsert(), PHG4ForwardEcalDisplayAction::AddVolume(), PHG4Detector::GetDetectorMaterial(), PHG4ForwardEcalDetector::GetDisplayAction(), PHG4Detector::OverlapCheck(), PHG4ForwardEcalDetector::ScintiLogicalVolSetInsert(), PHG4ForwardEcalDetector::TowerLogicNamePrefix(), and PHG4Detector::Verbosity().
Referenced by ConstructMe().
int PHG4EICForwardEcalDetector::ParseParametersFromTable () private
Definition at line 218 of file PHG4EICForwardEcalDetector.cc.
View newest version in sPHENIX GitHub at line 218 of file PHG4EICForwardEcalDetector.cc
References _map_tower, _tower_dx, _tower_dy, _tower_dz, Acts::UnitConstants::cm, PHG4ForwardEcalDetector::EndIter(), PHG4ForwardEcalDetector::FindIter(), PHParameters::get_string_param(), getline, PHG4ForwardEcalDetector::GetParams(), PHG4ForwardEcalDetector::InsertParam(), Acts::UnitConstants::rad, PHG4ForwardEcalDetector::SetdZ(), PHG4ForwardEcalDetector::SetPlaceX(), PHG4ForwardEcalDetector::SetPlaceY(), PHG4ForwardEcalDetector::SetPlaceZ(), PHG4ForwardEcalDetector::SetRMax(), PHG4ForwardEcalDetector::SetRMin(), PHG4ForwardEcalDetector::SetXRot(), PHG4ForwardEcalDetector::SetYRot(), PHG4ForwardEcalDetector::SetZRot(), G4CTD::size_z, PHG4ForwardEcalDetector::TowerLogicNamePrefix(), PHG4Detector::Verbosity(), PHG4EICForwardEcalDetector::towerposition::x, PHG4EICForwardEcalDetector::towerposition::y, and PHG4EICForwardEcalDetector::towerposition::z.
Referenced by ConstructMe().
int PHG4EICForwardEcalDetector::PlaceTower (G4LogicalVolume * envelope, G4LogicalVolume * tower) private
Definition at line 195 of file PHG4EICForwardEcalDetector.cc.
View newest version in sPHENIX GitHub at line 195 of file PHG4EICForwardEcalDetector.cc
References _map_tower, PHG4Detector::OverlapCheck(), and PHG4Detector::Verbosity().
Referenced by ConstructMe().
void PHG4EICForwardEcalDetector::SetMaterialAbsorber (G4String material) inline
Definition at line 45 of file PHG4EICForwardEcalDetector.h.
View newest version in sPHENIX GitHub at line 45 of file PHG4EICForwardEcalDetector.h
References _materialAbsorber, and material().
void PHG4EICForwardEcalDetector::SetMaterialScintillator (G4String material) inline
Definition at line 44 of file PHG4EICForwardEcalDetector.h.
View newest version in sPHENIX GitHub at line 44 of file PHG4EICForwardEcalDetector.h
References _materialScintillator, and material().
void PHG4EICForwardEcalDetector::SetTowerDimensions (G4double dx, G4double dy, G4double dz) inline
Definition at line 37 of file PHG4EICForwardEcalDetector.h.
View newest version in sPHENIX GitHub at line 37 of file PHG4EICForwardEcalDetector.h
References _tower_dx, _tower_dy, _tower_dz, dx, dy, and dz.
Member Data Documentation
std::map<std::string, towerposition> PHG4EICForwardEcalDetector::_map_tower private
Definition at line 59 of file PHG4EICForwardEcalDetector.h.
View newest version in sPHENIX GitHub at line 59 of file PHG4EICForwardEcalDetector.h
Referenced by ParseParametersFromTable(), and PlaceTower().
G4String PHG4EICForwardEcalDetector::_materialAbsorber private
Definition at line 67 of file PHG4EICForwardEcalDetector.h.
View newest version in sPHENIX GitHub at line 67 of file PHG4EICForwardEcalDetector.h
Referenced by ConstructTower(), and SetMaterialAbsorber().
G4String PHG4EICForwardEcalDetector::_materialScintillator private
Definition at line 66 of file PHG4EICForwardEcalDetector.h.
View newest version in sPHENIX GitHub at line 66 of file PHG4EICForwardEcalDetector.h
Referenced by ConstructTower(), and SetMaterialScintillator().
G4double PHG4EICForwardEcalDetector::_tower_dx private
Definition at line 62 of file PHG4EICForwardEcalDetector.h.
View newest version in sPHENIX GitHub at line 62 of file PHG4EICForwardEcalDetector.h
Referenced by ConstructTower(), ParseParametersFromTable(), and SetTowerDimensions().
G4double PHG4EICForwardEcalDetector::_tower_dy private
Definition at line 63 of file PHG4EICForwardEcalDetector.h.
View newest version in sPHENIX GitHub at line 63 of file PHG4EICForwardEcalDetector.h
Referenced by ConstructTower(), ParseParametersFromTable(), and SetTowerDimensions().
G4double PHG4EICForwardEcalDetector::_tower_dz private
Definition at line 64 of file PHG4EICForwardEcalDetector.h.
View newest version in sPHENIX GitHub at line 64 of file PHG4EICForwardEcalDetector.h
Referenced by ConstructTower(), ParseParametersFromTable(), and SetTowerDimensions().
The documentation for this class was generated from the following files:
fun4all_eicdetectors/blob/master/simulation/g4simulation/g4eiccalos/PHG4EICForwardEcalDetector.h
fun4all_eicdetectors/blob/master/simulation/g4simulation/g4eiccalos/PHG4EICForwardEcalDetector.cc