EIC Software: fun4all_acts/blob/master/Examples/Run/Vertexing/VertexAndTracksWriterExample.cpp File Reference
VertexAndTracksWriterExample.cpp File Reference
#include <Acts/EventData/TrackParameters.hpp>
#include <boost/program_options.hpp>
#include <memory>
#include "ACTFW/Framework/Sequencer.hpp"
#include "ACTFW/Generators/FlattenEvent.hpp"
#include "ACTFW/Generators/ParticleSelector.hpp"
#include "ACTFW/Generators/Pythia8ProcessGenerator.hpp"
#include "ACTFW/Io/Csv/CsvParticleWriter.hpp"
#include "ACTFW/Io/Root/RootParticleWriter.hpp"
#include "ACTFW/Io/Root/RootVertexAndTracksWriter.hpp"
#include "ACTFW/Options/CommonOptions.hpp"
#include "ACTFW/Options/Pythia8Options.hpp"
#include "ACTFW/TruthTracking/TrackSelector.hpp"
#include "ACTFW/TruthTracking/TruthVerticesToTracks.hpp"
#include "ACTFW/Utilities/Paths.hpp"
Functions
int main (int argc, char *argv[])
Function Documentation
int main (int argc, char * argv[])
Main vertex finder example executable
Parameters
argc The argument count
argv The argument list
Definition at line 33 of file VertexAndTracksWriterExample.cpp.
View newest version in sPHENIX GitHub at line 33 of file VertexAndTracksWriterExample.cpp
References Acts::units::_MeV, Acts::units::_mm, _T, FW::TrackSelector::Config::absEtaMax, FW::ParticleSelector::Config::absEtaMax, FW::Options::addOutputOptions(), FW::Options::addPythia8Options(), FW::Options::addRandomNumbersOptions(), FW::Options::addSequencerOptions(), FW::TruthVerticesToTracksAlgorithm::Config::bField, FW::RootVertexAndTracksWriter::Config::collection, incremental_prev_tag::desc, FW::TruthVerticesToTracksAlgorithm::Config::doSmearing, FW::ensureWritableDirectory(), FW::RootVertexAndTracksWriter::Config::filePath, FW::TrackSelector::Config::input, FW::TruthVerticesToTracksAlgorithm::Config::input, FW::ParticleSelector::Config::inputEvent, FW::joinPaths(), FW::TrackSelector::Config::keepNeutral, FW::Options::makeDefaultOptions(), FW::TrackSelector::Config::output, FW::TruthVerticesToTracksAlgorithm::Config::output, FW::EventGenerator::Config::output, FW::ParticleSelector::Config::outputEvent, FW::Options::parse(), FW::TrackSelector::Config::ptMin, FW::ParticleSelector::Config::ptMin, FW::EventGenerator::Config::randomNumbers, FW::TruthVerticesToTracksAlgorithm::Config::randomNumberSvc, FW::Options::readLogLevel(), FW::Options::readPythia8Options(), FW::Options::readRandomNumbersConfig(), FW::Options::readSequencerConfig(), FW::ParticleSelector::Config::removeNeutral, FW::TrackSelector::Config::rhoMax, and FW::ParticleSelector::Config::rhoMax.