EIC Software: CbmMCEventHeader Class Reference
CbmMCEventHeader Class Reference
#include <EicRoot/blob/master/cbmdata/CbmMCEventHeader.h>
Public Member Functions
CbmMCEventHeader ()
CbmMCEventHeader (UInt_t runId, Int_t iEvent, Double_t x, Double_t y, Double_t z, Double_t t, Double_t b, Double_t phi, Int_t nPrim)
CbmMCEventHeader (UInt_t runId)
virtual ~CbmMCEventHeader ()
Double_t GetPhi () const
void SetPhi (Double_t phi)
virtual void Reset ()
virtual void Register ()
ClassDef (CbmMCEventHeader, 1)
Public Member Functions inherited from FairMCEventHeader
FairMCEventHeader ()
FairMCEventHeader (Int_t iEvent, Double_t x, Double_t y, Double_t z, Double_t t, Double_t b, Int_t nPrim)
FairMCEventHeader (UInt_t runId)
virtual ~FairMCEventHeader ()
UInt_t GetRunID () const
UInt_t GetEventID () const
run identifier
Double_t GetX () const
event identifier
Double_t GetY () const
vertex x [cm]
Double_t GetZ () const
vertex y [cm]
Double_t GetT () const
vertex z [cm]
Double_t GetB () const
event time [ns]
Int_t GetNPrim () const
impact parameter [fm]
Bool_t IsSet () const
number of input tracks
void GetVertex (TVector3 &vertex)
Flag.
void SetEventID (UInt_t eventId)
void SetRunID (UInt_t runId)
void SetTime (Double_t t)
void SetB (Double_t b)
void SetNPrim (Int_t nPrim)
void MarkSet (Bool_t isSet)
void SetVertex (Double_t x, Double_t y, Double_t z)
void SetVertex (const TVector3 &vertex)
void Reset ()
Private Attributes
Double32_t fPhi
Additional Inherited Members
Protected Member Functions inherited from FairMCEventHeader
ClassDef (FairMCEventHeader, 1)
Flag whether variables are filled.
Protected Attributes inherited from FairMCEventHeader
UInt_t fRunId
UInt_t fEventId
Run identifier.
Double32_t fX
Event identifier.
Double32_t fY
Primary vertex x [cm].
Double32_t fZ
Primary vertex y [cm].
Double32_t fT
Primary vertex z [cm].
Double32_t fB
Event time [s].
Int_t fNPrim
Impact parameter [fm] (if relevant)
Bool_t fIsSet
Number of input tracks.
Detailed Description
CbmMCEventHeader.h
Author
F.Uhlig f.uhl.nosp@m.ig@g.nosp@m.si.de Data class (level MC) containing information about the input event. 04.11.2010 New CBM class derived from FairMCEventHeader
Definition at line 14 of file CbmMCEventHeader.h.
View newest version in sPHENIX GitHub at line 14 of file CbmMCEventHeader.h
Constructor & Destructor Documentation
CbmMCEventHeader::CbmMCEventHeader ()
Default constructor
Definition at line 17 of file CbmMCEventHeader.cxx.
View newest version in sPHENIX GitHub at line 17 of file CbmMCEventHeader.cxx
CbmMCEventHeader::CbmMCEventHeader (UInt_t runId, Int_t iEvent, Double_t x, Double_t y, Double_t z, Double_t t, Double_t b, Double_t phi, Int_t nPrim)
Constructor with all members
Parameters
runId run identifier
iEvent event identifier
x,y,z vertex oordinates [cm]
t event time [ns]
b impact parameter [fm] (if relevant)
phi event plane angle [rad]
nPrim number of input tracks
Definition at line 37 of file CbmMCEventHeader.cxx.
View newest version in sPHENIX GitHub at line 37 of file CbmMCEventHeader.cxx
CbmMCEventHeader::CbmMCEventHeader (UInt_t runId)
Standard constructor with run identifier
Definition at line 27 of file CbmMCEventHeader.cxx.
View newest version in sPHENIX GitHub at line 27 of file CbmMCEventHeader.cxx
CbmMCEventHeader::~CbmMCEventHeader () virtual
Destructor
Definition at line 49 of file CbmMCEventHeader.cxx.
View newest version in sPHENIX GitHub at line 49 of file CbmMCEventHeader.cxx
Member Function Documentation
CbmMCEventHeader::ClassDef (CbmMCEventHeader , 1)
Double_t CbmMCEventHeader::GetPhi () const inline
Accessors
Definition at line 47 of file CbmMCEventHeader.h.
View newest version in sPHENIX GitHub at line 47 of file CbmMCEventHeader.h
References fPhi.
void CbmMCEventHeader::Register () virtual
Register the class as data branch to the poutput
Reimplemented from FairMCEventHeader.
Definition at line 61 of file CbmMCEventHeader.cxx.
View newest version in sPHENIX GitHub at line 61 of file CbmMCEventHeader.cxx
References FairRootManager::Instance(), and FairRootManager::Register().
void CbmMCEventHeader::Reset () virtual
Reset all members
Definition at line 55 of file CbmMCEventHeader.cxx.
View newest version in sPHENIX GitHub at line 55 of file CbmMCEventHeader.cxx
References fPhi, and FairMCEventHeader::Reset().
void CbmMCEventHeader::SetPhi (Double_t phi) inline
Modifiers
Definition at line 51 of file CbmMCEventHeader.h.
View newest version in sPHENIX GitHub at line 51 of file CbmMCEventHeader.h
References fPhi, and phi.
Member Data Documentation
Double32_t CbmMCEventHeader::fPhi private
Definition at line 63 of file CbmMCEventHeader.h.
View newest version in sPHENIX GitHub at line 63 of file CbmMCEventHeader.h
Referenced by GetPhi(), Reset(), and SetPhi().
The documentation for this class was generated from the following files:
EicRoot/blob/master/cbmdata/CbmMCEventHeader.h
EicRoot/blob/master/cbmdata/CbmMCEventHeader.cxx