EIC Software: PndFieldContFact Class Reference
PndFieldContFact Class Reference
#include <EicRoot/blob/master/field/PndFieldContFact.h>
Public Member Functions
PndFieldContFact ()
~PndFieldContFact ()
FairParSet * createContainer (FairContainer *container)
Public Member Functions inherited from FairContFact
FairContFact ()
virtual ~FairContFact ()
Bool_t addContext (const char *name)
void print ()
FairParSet * getContainer (const char *)
virtual void activateParIo (FairParIo *)
Private Member Functions
void SetAllContainers ()
ClassDef (PndFieldContFact, 1)
Additional Inherited Members
Protected Member Functions inherited from FairContFact
const char * getActualContext (const char *name)
ClassDef(FairContFact,
0) private FairContFact & operator= (const FairContFact &)
Protected Attributes inherited from FairContFact
TList * containers
FairLogger * fLogger
Detailed Description
Definition at line 13 of file PndFieldContFact.h.
View newest version in sPHENIX GitHub at line 13 of file PndFieldContFact.h
Constructor & Destructor Documentation
PndFieldContFact::PndFieldContFact ()
Constructor
Definition at line 24 of file PndFieldContFact.cxx.
View newest version in sPHENIX GitHub at line 24 of file PndFieldContFact.cxx
References FairRuntimeDb::addContFactory(), and FairRuntimeDb::instance().
PndFieldContFact::~PndFieldContFact ()
Destructor
Definition at line 34 of file PndFieldContFact.cxx.
View newest version in sPHENIX GitHub at line 34 of file PndFieldContFact.cxx
Member Function Documentation
PndFieldContFact::ClassDef (PndFieldContFact , 1) private
FairParSet * PndFieldContFact::createContainer (FairContainer * container) virtual
Create containers Creates the requested parameter sets (PndFieldPar)
Reimplemented from FairContFact.
Definition at line 40 of file PndFieldContFact.cxx.
View newest version in sPHENIX GitHub at line 40 of file PndFieldContFact.cxx
References FairContainer::getConcatName(), FairContainer::getContext(), and name.
void PndFieldContFact::SetAllContainers () private
Set all containers Creates container objects with all accepted contexts and adds them to the list of containers for the field library.
Definition at line 106 of file PndFieldContFact.cxx.
View newest version in sPHENIX GitHub at line 106 of file PndFieldContFact.cxx
The documentation for this class was generated from the following files:
EicRoot/blob/master/field/PndFieldContFact.h
EicRoot/blob/master/field/PndFieldContFact.cxx