EIC Software: mesh_t Class Reference
mesh_t Class Reference
#include <EicRoot/blob/master/eic/cad/elmer/src/meshtype.h>
Public Member Functions
mesh_t ()
~mesh_t ()
bool isUndefined () const
void clear ()
bool load (char *)
bool save (char *)
double * boundingBox ()
void setCdim (int)
int getCdim () const
void setDim (int)
int getDim () const
void setNodes (int)
int getNodes () const
void setPoints (int)
int getPoints () const
void setEdges (int)
int getEdges () const
void setSurfaces (int)
int getSurfaces () const
void setElements (int)
int getElements () const
node_t * getNode (int)
void setNodeArray (node_t *)
void newNodeArray (int)
void deleteNodeArray ()
point_t * getPoint (int)
void setPointArray (point_t *)
void newPointArray (int)
void deletePointArray ()
edge_t * getEdge (int)
void setEdgeArray (edge_t *)
void newEdgeArray (int)
void deleteEdgeArray ()
surface_t * getSurface (int)
void setSurfaceArray (surface_t *)
void newSurfaceArray (int)
void deleteSurfaceArray ()
element_t * getElement (int)
void setElementArray (element_t *)
void newElementArray (int)
void deleteElementArray ()
Private Member Functions
void setDefaults ()
Private Attributes
int cdim
int dim
int nodes
int points
int edges
int surfaces
int elements
node_t * node
point_t * point
edge_t * edge
surface_t * surface
element_t * element
Detailed Description
Definition at line 193 of file meshtype.h.
View newest version in sPHENIX GitHub at line 193 of file meshtype.h
Constructor & Destructor Documentation
mesh_t::mesh_t ()
Definition at line 423 of file meshtype.cpp.
View newest version in sPHENIX GitHub at line 423 of file meshtype.cpp
mesh_t::~mesh_t ()
Definition at line 428 of file meshtype.cpp.
View newest version in sPHENIX GitHub at line 428 of file meshtype.cpp
Member Function Documentation
double * mesh_t::boundingBox ()
Definition at line 1135 of file meshtype.cpp.
View newest version in sPHENIX GitHub at line 1135 of file meshtype.cpp
References node_t::getX(), Acts::UnitConstants::s, xmax, xmin, ymax, and ymin.
void mesh_t::clear (void)
Definition at line 440 of file meshtype.cpp.
View newest version in sPHENIX GitHub at line 440 of file meshtype.cpp
References surface().
void mesh_t::deleteEdgeArray ()
Definition at line 1341 of file meshtype.cpp.
View newest version in sPHENIX GitHub at line 1341 of file meshtype.cpp
void mesh_t::deleteElementArray ()
Definition at line 1381 of file meshtype.cpp.
View newest version in sPHENIX GitHub at line 1381 of file meshtype.cpp
void mesh_t::deleteNodeArray ()
Definition at line 1301 of file meshtype.cpp.
View newest version in sPHENIX GitHub at line 1301 of file meshtype.cpp
void mesh_t::deletePointArray ()
Definition at line 1321 of file meshtype.cpp.
View newest version in sPHENIX GitHub at line 1321 of file meshtype.cpp
void mesh_t::deleteSurfaceArray ()
Definition at line 1361 of file meshtype.cpp.
View newest version in sPHENIX GitHub at line 1361 of file meshtype.cpp
References surface().
int mesh_t::getCdim () const
Definition at line 1221 of file meshtype.cpp.
View newest version in sPHENIX GitHub at line 1221 of file meshtype.cpp
int mesh_t::getDim () const
Definition at line 1231 of file meshtype.cpp.
View newest version in sPHENIX GitHub at line 1231 of file meshtype.cpp
References Acts::Test::dim.
edge_t * mesh_t::getEdge (int n)
Definition at line 1326 of file meshtype.cpp.
View newest version in sPHENIX GitHub at line 1326 of file meshtype.cpp
References n.
Referenced by ConvertEgTypeToMeshType().
int mesh_t::getEdges () const
Definition at line 1261 of file meshtype.cpp.
View newest version in sPHENIX GitHub at line 1261 of file meshtype.cpp
Referenced by ConvertEgTypeToMeshType().
element_t * mesh_t::getElement (int n)
Definition at line 1366 of file meshtype.cpp.
View newest version in sPHENIX GitHub at line 1366 of file meshtype.cpp
References n.
Referenced by ConvertEgTypeToMeshType().
int mesh_t::getElements () const
Definition at line 1281 of file meshtype.cpp.
View newest version in sPHENIX GitHub at line 1281 of file meshtype.cpp
Referenced by ConvertEgTypeToMeshType().
node_t * mesh_t::getNode (int n)
Definition at line 1286 of file meshtype.cpp.
View newest version in sPHENIX GitHub at line 1286 of file meshtype.cpp
References n.
Referenced by ConvertEgTypeToMeshType().
int mesh_t::getNodes () const
Definition at line 1241 of file meshtype.cpp.
View newest version in sPHENIX GitHub at line 1241 of file meshtype.cpp
Referenced by ConvertEgTypeToMeshType().
point_t * mesh_t::getPoint (int n)
Definition at line 1306 of file meshtype.cpp.
View newest version in sPHENIX GitHub at line 1306 of file meshtype.cpp
References n.
int mesh_t::getPoints () const
Definition at line 1251 of file meshtype.cpp.
View newest version in sPHENIX GitHub at line 1251 of file meshtype.cpp
surface_t * mesh_t::getSurface (int n)
Definition at line 1346 of file meshtype.cpp.
View newest version in sPHENIX GitHub at line 1346 of file meshtype.cpp
References n, and surface().
Referenced by ConvertEgTypeToMeshType().
int mesh_t::getSurfaces () const
Definition at line 1271 of file meshtype.cpp.
View newest version in sPHENIX GitHub at line 1271 of file meshtype.cpp
Referenced by ConvertEgTypeToMeshType().
bool mesh_t::isUndefined () const
Definition at line 432 of file meshtype.cpp.
View newest version in sPHENIX GitHub at line 432 of file meshtype.cpp
References Acts::Test::dim.
bool mesh_t::load (char * dirName)
Definition at line 469 of file meshtype.cpp.
View newest version in sPHENIX GitHub at line 469 of file meshtype.cpp
References Acts::Test::dim, element_t::getCode(), point_t::getEdges(), surface_t::getEdges(), surface_t::getElements(), element_t::getNodes(), edge_t::getSurfaces(), k, point_t::newEdgeIndexes(), surface_t::newEdgeIndexes(), surface_t::newElementIndexes(), element_t::newNodeIndexes(), edge_t::newSurfaceIndexes(), PDE_BOUNDARY, PDE_BULK, element_t::setCode(), point_t::setEdgeIndex(), surface_t::setEdgeIndex(), point_t::setEdges(), surface_t::setEdges(), surface_t::setElementIndex(), surface_t::setElements(), node_t::setIndex(), element_t::setIndex(), element_t::setNature(), element_t::setNodeIndex(), element_t::setNodes(), edge_t::setSurfaceIndex(), edge_t::setSurfaces(), node_t::setX(), surface(), x, y, and z.
void mesh_t::newEdgeArray (int n)
Definition at line 1336 of file meshtype.cpp.
View newest version in sPHENIX GitHub at line 1336 of file meshtype.cpp
References n.
Referenced by ConvertEgTypeToMeshType().
void mesh_t::newElementArray (int n)
Definition at line 1376 of file meshtype.cpp.
View newest version in sPHENIX GitHub at line 1376 of file meshtype.cpp
References n.
Referenced by ConvertEgTypeToMeshType().
void mesh_t::newNodeArray (int n)
Definition at line 1296 of file meshtype.cpp.
View newest version in sPHENIX GitHub at line 1296 of file meshtype.cpp
References n.
Referenced by ConvertEgTypeToMeshType().
void mesh_t::newPointArray (int n)
Definition at line 1316 of file meshtype.cpp.
View newest version in sPHENIX GitHub at line 1316 of file meshtype.cpp
References n.
void mesh_t::newSurfaceArray (int n)
Definition at line 1356 of file meshtype.cpp.
View newest version in sPHENIX GitHub at line 1356 of file meshtype.cpp
References n, and surface().
Referenced by ConvertEgTypeToMeshType().
bool mesh_t::save (char * dirName)
Definition at line 796 of file meshtype.cpp.
View newest version in sPHENIX GitHub at line 796 of file meshtype.cpp
References Acts::UnitConstants::e, element_t::getCode(), point_t::getEdgeIndex(), surface_t::getElementIndex(), node_t::getIndex(), element_t::getIndex(), element_t::getNature(), element_t::getNodeIndex(), element_t::getNodes(), edge_t::getSurfaceIndex(), node_t::getX(), p, PDE_BOUNDARY, PDE_BULK, Acts::UnitConstants::s, s1, and surface().
void mesh_t::setCdim (int n)
Definition at line 1216 of file meshtype.cpp.
View newest version in sPHENIX GitHub at line 1216 of file meshtype.cpp
References n.
void mesh_t::setDefaults () private
Definition at line 451 of file meshtype.cpp.
View newest version in sPHENIX GitHub at line 451 of file meshtype.cpp
References Acts::Test::dim, and surface().
void mesh_t::setDim (int n)
Definition at line 1226 of file meshtype.cpp.
View newest version in sPHENIX GitHub at line 1226 of file meshtype.cpp
References Acts::Test::dim, and n.
Referenced by ConvertEgTypeToMeshType().
void mesh_t::setEdgeArray (edge_t * e)
Definition at line 1331 of file meshtype.cpp.
View newest version in sPHENIX GitHub at line 1331 of file meshtype.cpp
References Acts::UnitConstants::e.
void mesh_t::setEdges (int n)
Definition at line 1256 of file meshtype.cpp.
View newest version in sPHENIX GitHub at line 1256 of file meshtype.cpp
References n.
Referenced by ConvertEgTypeToMeshType(), and eg_transfermesh().
void mesh_t::setElementArray (element_t * e)
Definition at line 1371 of file meshtype.cpp.
View newest version in sPHENIX GitHub at line 1371 of file meshtype.cpp
References Acts::UnitConstants::e.
void mesh_t::setElements (int n)
Definition at line 1276 of file meshtype.cpp.
View newest version in sPHENIX GitHub at line 1276 of file meshtype.cpp
References n.
Referenced by ConvertEgTypeToMeshType(), and eg_transfermesh().
void mesh_t::setNodeArray (node_t * n)
Definition at line 1291 of file meshtype.cpp.
View newest version in sPHENIX GitHub at line 1291 of file meshtype.cpp
References n.
void mesh_t::setNodes (int n)
Definition at line 1236 of file meshtype.cpp.
View newest version in sPHENIX GitHub at line 1236 of file meshtype.cpp
References n.
Referenced by ConvertEgTypeToMeshType(), and eg_transfermesh().
void mesh_t::setPointArray (point_t * p)
Definition at line 1311 of file meshtype.cpp.
View newest version in sPHENIX GitHub at line 1311 of file meshtype.cpp
References p.
void mesh_t::setPoints (int n)
Definition at line 1246 of file meshtype.cpp.
View newest version in sPHENIX GitHub at line 1246 of file meshtype.cpp
References n.
Referenced by eg_transfermesh().
void mesh_t::setSurfaceArray (surface_t * s)
Definition at line 1351 of file meshtype.cpp.
View newest version in sPHENIX GitHub at line 1351 of file meshtype.cpp
References Acts::UnitConstants::s, and surface().
void mesh_t::setSurfaces (int n)
Definition at line 1266 of file meshtype.cpp.
View newest version in sPHENIX GitHub at line 1266 of file meshtype.cpp
References n.
Referenced by ConvertEgTypeToMeshType(), and eg_transfermesh().
Member Data Documentation
int mesh_t::cdim private
Definition at line 241 of file meshtype.h.
View newest version in sPHENIX GitHub at line 241 of file meshtype.h
int mesh_t::dim private
Definition at line 242 of file meshtype.h.
View newest version in sPHENIX GitHub at line 242 of file meshtype.h
edge_t* mesh_t::edge private
Definition at line 251 of file meshtype.h.
View newest version in sPHENIX GitHub at line 251 of file meshtype.h
int mesh_t::edges private
Definition at line 245 of file meshtype.h.
View newest version in sPHENIX GitHub at line 245 of file meshtype.h
element_t* mesh_t::element private
Definition at line 253 of file meshtype.h.
View newest version in sPHENIX GitHub at line 253 of file meshtype.h
int mesh_t::elements private
Definition at line 247 of file meshtype.h.
View newest version in sPHENIX GitHub at line 247 of file meshtype.h
node_t* mesh_t::node private
Definition at line 249 of file meshtype.h.
View newest version in sPHENIX GitHub at line 249 of file meshtype.h
int mesh_t::nodes private
Definition at line 243 of file meshtype.h.
View newest version in sPHENIX GitHub at line 243 of file meshtype.h
point_t* mesh_t::point private
Definition at line 250 of file meshtype.h.
View newest version in sPHENIX GitHub at line 250 of file meshtype.h
int mesh_t::points private
Definition at line 244 of file meshtype.h.
View newest version in sPHENIX GitHub at line 244 of file meshtype.h
surface_t* mesh_t::surface private
Definition at line 252 of file meshtype.h.
View newest version in sPHENIX GitHub at line 252 of file meshtype.h
int mesh_t::surfaces private
Definition at line 246 of file meshtype.h.
View newest version in sPHENIX GitHub at line 246 of file meshtype.h
The documentation for this class was generated from the following files:
EicRoot/blob/master/eic/cad/elmer/src/meshtype.h
EicRoot/blob/master/eic/cad/elmer/src/meshtype.cpp