EIC Software: RawTowerZDCGeomContainer Class Reference
RawTowerZDCGeomContainer Class Reference
Generic tower geometry class, store each tower's geometry individually.
#include <fun4all_eicdetectors/blob/master/reconstruction/eiczdcbase/RawTowerZDCGeomContainer.h>
Public Types
typedef std::map
< RawTowerZDCDefs::keytype,
RawTowerZDCGeom * > Map
typedef Map::iterator Iterator
typedef Map::const_iterator ConstIterator
typedef std::pair< Iterator,
Iterator > Range
typedef std::pair
< ConstIterator, ConstIterator > ConstRange
Public Member Functions
RawTowerZDCGeomContainer (RawTowerZDCDefs::CalorimeterId caloid=RawTowerZDCDefs::NONE)
default constructor for ROOT IO
~RawTowerZDCGeomContainer () override
void Reset () override
Clear Event.
int isValid () const override
isValid returns non zero if object contains vailid data
void identify (std::ostream &os=std::cout) const override
void set_calorimeter_id (RawTowerZDCDefs::CalorimeterId caloid)
RawTowerZDCDefs::CalorimeterId get_calorimeter_id ()
ConstIterator add_tower_geometry (RawTowerZDCGeom *geo)
go through all towers
RawTowerZDCGeom * get_tower_geometry (RawTowerZDCDefs::keytype key)
ConstRange get_tower_geometries (void) const
return all tower geometries
Range get_tower_geometries (void)
unsigned int size () const
Public Member Functions inherited from PHObject
PHObject ()
ctor
~PHObject () override
dtor
virtual PHObject * CloneMe () const
Virtual copy constructor.
virtual PHObject * clone () const final
PHObject * Clone (const char *newname="") const final
void Copy (TObject &object) const final
virtual int isValid (const float) const
virtual int isValid (const double) const
virtual int isValid (const int) const
virtual int isValid (const unsigned int) const
virtual int isImplemented (const float f) const
virtual int isImplemented (const double f) const
virtual int isImplemented (const int i) const
virtual int isImplemented (const unsigned int i) const
virtual int Integrate () const
virtual int Integrate (PHObject *)
virtual void CopyFrom (const PHObject *obj)
Protected Attributes
RawTowerZDCDefs::CalorimeterId _caloid
Map _geoms
Detailed Description
Generic tower geometry class, store each tower's geometry individually.
Definition at line 21 of file RawTowerZDCGeomContainer.h.
View newest version in sPHENIX GitHub at line 21 of file RawTowerZDCGeomContainer.h
Member Typedef Documentation
typedef Map::const_iterator RawTowerZDCGeomContainer::ConstIterator
Definition at line 26 of file RawTowerZDCGeomContainer.h.
View newest version in sPHENIX GitHub at line 26 of file RawTowerZDCGeomContainer.h
typedef std::pair<ConstIterator, ConstIterator> RawTowerZDCGeomContainer::ConstRange
Definition at line 28 of file RawTowerZDCGeomContainer.h.
View newest version in sPHENIX GitHub at line 28 of file RawTowerZDCGeomContainer.h
typedef Map::iterator RawTowerZDCGeomContainer::Iterator
Definition at line 25 of file RawTowerZDCGeomContainer.h.
View newest version in sPHENIX GitHub at line 25 of file RawTowerZDCGeomContainer.h
typedef std::map<RawTowerZDCDefs::keytype, RawTowerZDCGeom *> RawTowerZDCGeomContainer::Map
Definition at line 24 of file RawTowerZDCGeomContainer.h.
View newest version in sPHENIX GitHub at line 24 of file RawTowerZDCGeomContainer.h
typedef std::pair<Iterator, Iterator> RawTowerZDCGeomContainer::Range
Definition at line 27 of file RawTowerZDCGeomContainer.h.
View newest version in sPHENIX GitHub at line 27 of file RawTowerZDCGeomContainer.h
Constructor & Destructor Documentation
RawTowerZDCGeomContainer::RawTowerZDCGeomContainer (RawTowerZDCDefs::CalorimeterId caloid = RawTowerZDCDefs::NONE)
default constructor for ROOT IO
Definition at line 10 of file RawTowerZDCGeomContainer.cc.
View newest version in sPHENIX GitHub at line 10 of file RawTowerZDCGeomContainer.cc
RawTowerZDCGeomContainer::~RawTowerZDCGeomContainer () override
Definition at line 15 of file RawTowerZDCGeomContainer.cc.
View newest version in sPHENIX GitHub at line 15 of file RawTowerZDCGeomContainer.cc
References Reset().
Member Function Documentation
RawTowerZDCGeomContainer::ConstIterator RawTowerZDCGeomContainer::add_tower_geometry (RawTowerZDCGeom * geo)
go through all towers
Definition at line 27 of file RawTowerZDCGeomContainer.cc.
View newest version in sPHENIX GitHub at line 27 of file RawTowerZDCGeomContainer.cc
References _geoms, RawTowerZDCDefs::decode_caloid(), exit(), get_calorimeter_id(), RawTowerZDCGeom::get_id(), RawTowerZDCGeom::identify(), and it.
Referenced by EICG4ZDCRawTowerBuilderByHitIndex::ReadGeometryFromTable().
RawTowerZDCDefs::CalorimeterId RawTowerZDCGeomContainer::get_calorimeter_id () inline
Definition at line 40 of file RawTowerZDCGeomContainer.h.
View newest version in sPHENIX GitHub at line 40 of file RawTowerZDCGeomContainer.h
References _caloid.
Referenced by add_tower_geometry().
RawTowerZDCGeomContainer::ConstRange RawTowerZDCGeomContainer::get_tower_geometries (void) const
return all tower geometries
Definition at line 59 of file RawTowerZDCGeomContainer.cc.
View newest version in sPHENIX GitHub at line 59 of file RawTowerZDCGeomContainer.cc
References _geoms.
Referenced by RawTowerZDCDigitizer::process_event(), and EICG4ZDCRawTowerBuilderByHitIndex::ReadGeometryFromTable().
RawTowerZDCGeomContainer::Range RawTowerZDCGeomContainer::get_tower_geometries (void)
Definition at line 65 of file RawTowerZDCGeomContainer.cc.
View newest version in sPHENIX GitHub at line 65 of file RawTowerZDCGeomContainer.cc
References _geoms.
RawTowerZDCGeom * RawTowerZDCGeomContainer::get_tower_geometry (RawTowerZDCDefs::keytype key)
Definition at line 71 of file RawTowerZDCGeomContainer.cc.
View newest version in sPHENIX GitHub at line 71 of file RawTowerZDCGeomContainer.cc
References _geoms, and it.
Referenced by RawTowerZDCCalibration::process_event().
void RawTowerZDCGeomContainer::identify (std::ostream & os = std::cout) const override virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from PHObject.
Definition at line 20 of file RawTowerZDCGeomContainer.cc.
View newest version in sPHENIX GitHub at line 20 of file RawTowerZDCGeomContainer.cc
References size().
Referenced by RawTowerZDCCalibration::CreateNodes(), and RawTowerZDCDigitizer::CreateNodes().
int RawTowerZDCGeomContainer::isValid () const override virtual
isValid returns non zero if object contains vailid data
Reimplemented from PHObject.
Definition at line 81 of file RawTowerZDCGeomContainer.cc.
View newest version in sPHENIX GitHub at line 81 of file RawTowerZDCGeomContainer.cc
References _geoms.
void RawTowerZDCGeomContainer::Reset () override virtual
Clear Event.
Reimplemented from PHObject.
Definition at line 86 of file RawTowerZDCGeomContainer.cc.
View newest version in sPHENIX GitHub at line 86 of file RawTowerZDCGeomContainer.cc
References _geoms.
Referenced by ~RawTowerZDCGeomContainer().
void RawTowerZDCGeomContainer::set_calorimeter_id (RawTowerZDCDefs::CalorimeterId caloid) inline
Definition at line 39 of file RawTowerZDCGeomContainer.h.
View newest version in sPHENIX GitHub at line 39 of file RawTowerZDCGeomContainer.h
References _caloid.
unsigned int RawTowerZDCGeomContainer::size (void) const inline
Definition at line 51 of file RawTowerZDCGeomContainer.h.
View newest version in sPHENIX GitHub at line 51 of file RawTowerZDCGeomContainer.h
References _geoms.
Referenced by identify().
Member Data Documentation
RawTowerZDCDefs::CalorimeterId RawTowerZDCGeomContainer::_caloid protected
Definition at line 54 of file RawTowerZDCGeomContainer.h.
View newest version in sPHENIX GitHub at line 54 of file RawTowerZDCGeomContainer.h
Referenced by get_calorimeter_id(), and set_calorimeter_id().
Map RawTowerZDCGeomContainer::_geoms protected
Definition at line 55 of file RawTowerZDCGeomContainer.h.
View newest version in sPHENIX GitHub at line 55 of file RawTowerZDCGeomContainer.h
Referenced by add_tower_geometry(), get_tower_geometries(), get_tower_geometry(), isValid(), Reset(), and size().
The documentation for this class was generated from the following files:
fun4all_eicdetectors/blob/master/reconstruction/eiczdcbase/RawTowerZDCGeomContainer.h
fun4all_eicdetectors/blob/master/reconstruction/eiczdcbase/RawTowerZDCGeomContainer.cc