EIC Software: EICG4BwdDetector Class Reference
EICG4BwdDetector Class Reference
#include <fun4all_eicdetectors/blob/master/simulation/g4simulation/g4bwd/EICG4BwdDetector.h>
Classes
struct towerposition
Public Member Functions
EICG4BwdDetector (PHG4Subsystem *subsys, PHCompositeNode *Node, PHParameters *parameters, const std::string &dnam, const int layer=0)
constructor
virtual ~EICG4BwdDetector () override
destructor
virtual void ConstructMe (G4LogicalVolume *world) override
construct
void Print (const std::string &what="ALL") const override
int GetDetId (G4VPhysicalVolume *) const
void SuperDetector (const std::string &name)
const std::string SuperDetector () const
int get_Layer () const
PHParameters * getParams ()
void SetTowerMappingFile (const std::string &filename)
volume accessors
int IsInDetector (G4VPhysicalVolume *) const
Public Member Functions inherited from PHG4Detector
PHG4Detector ()=delete
constructor
PHG4Detector (PHG4Subsystem *subsys, PHCompositeNode *Node, const std::string &nam)
virtual ~PHG4Detector (void)
destructor
virtual void Construct (G4LogicalVolume *world) final
construct method
virtual void PostConstruction ()
Optional PostConstruction call after all geometry is constructed.
virtual void Verbosity (const int v)
virtual int Verbosity () const
virtual G4UserSteppingAction * GetSteppingAction ()
virtual std::string GetName () const
virtual void OverlapCheck (const bool chk)
virtual bool OverlapCheck () const
virtual int DisplayVolume (G4VSolid *volume, G4LogicalVolume *logvol, G4RotationMatrix *rotm=nullptr)
virtual int DisplayVolume (G4LogicalVolume *checksolid, G4LogicalVolume *logvol, G4RotationMatrix *rotm=nullptr)
virtual PHCompositeNode * topNode ()
virtual PHG4Subsystem * GetMySubsystem ()
Protected Member Functions
void LogicalVolSetInsert (G4LogicalVolume *logvol)
Private Member Functions
G4LogicalVolume * ConstructTower ()
int PlaceTower (G4LogicalVolume *envelope, G4LogicalVolume *tower)
int ParseParametersFromTable ()
Private Attributes
std::map< std::string,
towerposition > m_TowerPositionMap
PHParameters * m_Params
std::set< G4VPhysicalVolume * > m_PhysicalVolumesSet
std::map< G4VPhysicalVolume
*, int > m_PhysicalVolumesDet
std::set< G4LogicalVolume * > m_LogicalVolSet
int m_Layer
std::string m_SuperDetector
std::string _mapping_tower_file
std::string m_TowerLogicNamePrefix
Additional Inherited Members
Static Public Member Functions inherited from PHG4Detector
static G4Material * GetDetectorMaterial (const std::string &name, const bool quit=true)
static G4Element * GetDetectorElement (const std::string &name, const bool quit=true)
Detailed Description
Definition at line 18 of file EICG4BwdDetector.h.
View newest version in sPHENIX GitHub at line 18 of file EICG4BwdDetector.h
Constructor & Destructor Documentation
EICG4BwdDetector::EICG4BwdDetector (PHG4Subsystem * subsys, PHCompositeNode * Node, PHParameters * parameters, const std::string & dnam, const int layer = 0)
constructor
Definition at line 65 of file EICG4BwdDetector.cc.
View newest version in sPHENIX GitHub at line 65 of file EICG4BwdDetector.cc
virtual EICG4BwdDetector::~EICG4BwdDetector () inline override virtual
destructor
Definition at line 25 of file EICG4BwdDetector.h.
View newest version in sPHENIX GitHub at line 25 of file EICG4BwdDetector.h
Member Function Documentation
void EICG4BwdDetector::ConstructMe (G4LogicalVolume * world) override virtual
construct
Implements PHG4Detector.
Definition at line 98 of file EICG4BwdDetector.cc.
View newest version in sPHENIX GitHub at line 98 of file EICG4BwdDetector.cc
References _mapping_tower_file, Acts::UnitConstants::cm, ConstructTower(), PHParameters::get_double_param(), PHParameters::get_int_param(), PHParameters::get_string_param(), PHFlag::get_StringFlag(), PHG4Detector::GetDetectorMaterial(), recoConsts::instance(), m_Params, m_PhysicalVolumesDet, m_PhysicalVolumesSet, m_TowerLogicNamePrefix, PHG4Detector::OverlapCheck(), ParseParametersFromTable(), PlaceTower(), PHG4Detector::Verbosity(), and G4WORLD::WorldMaterial.
G4LogicalVolume * EICG4BwdDetector::ConstructTower () private
Definition at line 201 of file EICG4BwdDetector.cc.
View newest version in sPHENIX GitHub at line 201 of file EICG4BwdDetector.cc
References Acts::UnitConstants::cm, PHParameters::get_double_param(), PHParameters::get_string_param(), PHG4Detector::GetDetectorMaterial(), m_LogicalVolSet, m_Params, and PHG4Detector::Verbosity().
Referenced by ConstructMe().
int EICG4BwdDetector::get_Layer () const inline
Definition at line 41 of file EICG4BwdDetector.h.
View newest version in sPHENIX GitHub at line 41 of file EICG4BwdDetector.h
References m_Layer.
Referenced by EICG4BwdSteppingAction::UserSteppingAction().
int EICG4BwdDetector::GetDetId (G4VPhysicalVolume * volume) const
Definition at line 88 of file EICG4BwdDetector.cc.
View newest version in sPHENIX GitHub at line 88 of file EICG4BwdDetector.cc
References IsInDetector().
PHParameters * EICG4BwdDetector::getParams ()
Definition at line 364 of file EICG4BwdDetector.cc.
View newest version in sPHENIX GitHub at line 364 of file EICG4BwdDetector.cc
References m_Params.
int EICG4BwdDetector::IsInDetector (G4VPhysicalVolume * volume) const
Definition at line 78 of file EICG4BwdDetector.cc.
View newest version in sPHENIX GitHub at line 78 of file EICG4BwdDetector.cc
References m_LogicalVolSet.
Referenced by GetDetId(), and EICG4BwdSteppingAction::UserSteppingAction().
void EICG4BwdDetector::LogicalVolSetInsert (G4LogicalVolume * logvol) inline protected
Definition at line 77 of file EICG4BwdDetector.h.
View newest version in sPHENIX GitHub at line 77 of file EICG4BwdDetector.h
References m_LogicalVolSet.
int EICG4BwdDetector::ParseParametersFromTable () private
Definition at line 258 of file EICG4BwdDetector.cc.
View newest version in sPHENIX GitHub at line 258 of file EICG4BwdDetector.cc
References _mapping_tower_file, Acts::UnitConstants::cm, PHParameters::get_double_param(), getline, EICG4BwdDetector::towerposition::idx_j, EICG4BwdDetector::towerposition::idx_k, m_Params, m_TowerLogicNamePrefix, m_TowerPositionMap, G4CTD::size_z, PHG4Detector::Verbosity(), EICG4BwdDetector::towerposition::x, EICG4BwdDetector::towerposition::y, and EICG4BwdDetector::towerposition::z.
Referenced by ConstructMe().
int EICG4BwdDetector::PlaceTower (G4LogicalVolume * envelope, G4LogicalVolume * tower) private
Definition at line 234 of file EICG4BwdDetector.cc.
View newest version in sPHENIX GitHub at line 234 of file EICG4BwdDetector.cc
References Acts::UnitConstants::cm, m_TowerPositionMap, PHG4Detector::OverlapCheck(), and PHG4Detector::Verbosity().
Referenced by ConstructMe().
void EICG4BwdDetector::Print (const std::string & what = "ALL") const override virtual
Reimplemented from PHG4Detector.
Definition at line 352 of file EICG4BwdDetector.cc.
View newest version in sPHENIX GitHub at line 352 of file EICG4BwdDetector.cc
References m_Params, and PHParameters::Print().
Referenced by EICG4BwdSubsystem::Print().
void EICG4BwdDetector::SetTowerMappingFile (const std::string & filename) inline
Definition at line 43 of file EICG4BwdDetector.h.
View newest version in sPHENIX GitHub at line 43 of file EICG4BwdDetector.h
References _mapping_tower_file, and INPUTHEPMC::filename.
Referenced by EICG4BwdSubsystem::InitRunSubsystem().
void EICG4BwdDetector::SuperDetector (const std::string & name) inline
Definition at line 39 of file EICG4BwdDetector.h.
View newest version in sPHENIX GitHub at line 39 of file EICG4BwdDetector.h
References m_SuperDetector, and name.
Referenced by EICG4BwdSubsystem::InitRunSubsystem(), and EICG4BwdSteppingAction::UserSteppingAction().
const std::string EICG4BwdDetector::SuperDetector () const inline
Definition at line 40 of file EICG4BwdDetector.h.
View newest version in sPHENIX GitHub at line 40 of file EICG4BwdDetector.h
References m_SuperDetector.
Member Data Documentation
std::string EICG4BwdDetector::_mapping_tower_file private
Definition at line 74 of file EICG4BwdDetector.h.
View newest version in sPHENIX GitHub at line 74 of file EICG4BwdDetector.h
Referenced by ConstructMe(), ParseParametersFromTable(), and SetTowerMappingFile().
int EICG4BwdDetector::m_Layer private
Definition at line 72 of file EICG4BwdDetector.h.
View newest version in sPHENIX GitHub at line 72 of file EICG4BwdDetector.h
Referenced by get_Layer().
std::set<G4LogicalVolume *> EICG4BwdDetector::m_LogicalVolSet private
Definition at line 70 of file EICG4BwdDetector.h.
View newest version in sPHENIX GitHub at line 70 of file EICG4BwdDetector.h
Referenced by ConstructTower(), IsInDetector(), and LogicalVolSetInsert().
PHParameters* EICG4BwdDetector::m_Params private
Definition at line 65 of file EICG4BwdDetector.h.
View newest version in sPHENIX GitHub at line 65 of file EICG4BwdDetector.h
Referenced by ConstructMe(), ConstructTower(), getParams(), ParseParametersFromTable(), and Print().
std::map<G4VPhysicalVolume *, int> EICG4BwdDetector::m_PhysicalVolumesDet private
Definition at line 69 of file EICG4BwdDetector.h.
View newest version in sPHENIX GitHub at line 69 of file EICG4BwdDetector.h
Referenced by ConstructMe().
std::set<G4VPhysicalVolume *> EICG4BwdDetector::m_PhysicalVolumesSet private
Definition at line 67 of file EICG4BwdDetector.h.
View newest version in sPHENIX GitHub at line 67 of file EICG4BwdDetector.h
Referenced by ConstructMe().
std::string EICG4BwdDetector::m_SuperDetector private
Definition at line 73 of file EICG4BwdDetector.h.
View newest version in sPHENIX GitHub at line 73 of file EICG4BwdDetector.h
Referenced by SuperDetector().
std::string EICG4BwdDetector::m_TowerLogicNamePrefix private
Definition at line 75 of file EICG4BwdDetector.h.
View newest version in sPHENIX GitHub at line 75 of file EICG4BwdDetector.h
Referenced by ConstructMe(), and ParseParametersFromTable().
std::map<std::string, towerposition> EICG4BwdDetector::m_TowerPositionMap private
Definition at line 62 of file EICG4BwdDetector.h.
View newest version in sPHENIX GitHub at line 62 of file EICG4BwdDetector.h
Referenced by ParseParametersFromTable(), and PlaceTower().
The documentation for this class was generated from the following files:
fun4all_eicdetectors/blob/master/simulation/g4simulation/g4bwd/EICG4BwdDetector.h
fun4all_eicdetectors/blob/master/simulation/g4simulation/g4bwd/EICG4BwdDetector.cc