EIC Software: delphes_EIC/blob/master/SimpleAnalysis/AnalysisFunctions.cc File Reference
AnalysisFunctions.cc File Reference
#include "TROOT.h"
#include "TLorentzVector.h"
#include "TVector3.h"
#include "TClonesArray.h"
#include "TMath.h"
#include <vector>
#include <string>
#include <map>
#include <iostream>
#include <math.h>
#include "classes/DelphesClasses.h"
Macros
#define ANALYSISFUNCTIONS
Functions
template<class T >
std::vector< T * > SelectorFcn (std::vector< T * >particles, bool selector(T *))
std::map< std::string, float > DISVariables (TClonesArray *branchParticle)
std::map< std::string, float > DISJacquetBlondel (TClonesArray *tracks, TClonesArray *electrons, TClonesArray *photons, TClonesArray *neutral_hadrons)
bool IsTaggingTrack (Track *track)
float sIP3D (Jet *jet, Track *track)
bool Tagged_Kaon (Jet *jet, std::vector< Track * >kaons, float minSignif, float minPT, int minKaons)
bool Tagged_Electron (Jet *jet, std::vector< Track * >electrons, float minSignif, float minPT, int minElectrons)
bool Tagged_Muon (Jet *jet, std::vector< Track * >muons, float minSignif, float minPT, int minMuons)
bool Tagged_sIP3D (Jet *jet, TClonesArray tracks, float minSignif, float minPT, int minTracks)
Macro Definition Documentation
#define ANALYSISFUNCTIONS
Definition at line 2 of file AnalysisFunctions.cc.
View newest version in sPHENIX GitHub at line 2 of file AnalysisFunctions.cc
Function Documentation
std::map<std::string, float> DISJacquetBlondel (TClonesArray * tracks, TClonesArray * electrons, TClonesArray * photons, TClonesArray * neutral_hadrons) inline
Definition at line 70 of file AnalysisFunctions.cc.
View newest version in sPHENIX GitHub at line 70 of file AnalysisFunctions.cc
References Acts::Test::delta, Acts::UnitConstants::e, and Acts::UnitConstants::s.
Referenced by EventSelectionModule::execute().
std::map<std::string, float> DISVariables (TClonesArray * branchParticle) inline
Definition at line 37 of file AnalysisFunctions.cc.
View newest version in sPHENIX GitHub at line 37 of file AnalysisFunctions.cc
References x, and y.
Referenced by EventSelectionModule::execute().
bool IsTaggingTrack (Track * track) inline
Definition at line 152 of file AnalysisFunctions.cc.
View newest version in sPHENIX GitHub at line 152 of file AnalysisFunctions.cc
Referenced by EventSelectionModule::execute(), sIP3D(), Tagged_Electron(), Tagged_Kaon(), Tagged_Muon(), and Tagged_sIP3D().
template<class T > std::vector<T *> SelectorFcn (std::vector< T * > particles, bool selectorT *)
Definition at line 20 of file AnalysisFunctions.cc.
View newest version in sPHENIX GitHub at line 20 of file AnalysisFunctions.cc
References particle, and T.
float sIP3D (Jet * jet, Track * track) inline
Definition at line 175 of file AnalysisFunctions.cc.
View newest version in sPHENIX GitHub at line 175 of file AnalysisFunctions.cc
References dz, IsTaggingTrack(), and sign().
Referenced by EventSelectionModule::execute(), Tagged_Electron(), Tagged_Kaon(), Tagged_Muon(), and Tagged_sIP3D().
bool Tagged_Electron (Jet * jet, std::vector< Track * > electrons, float minSignif, float minPT, int minElectrons) inline
Definition at line 236 of file AnalysisFunctions.cc.
View newest version in sPHENIX GitHub at line 236 of file AnalysisFunctions.cc
References IsTaggingTrack(), and sIP3D().
Referenced by EventSelectionModule::execute().
bool Tagged_Kaon (Jet * jet, std::vector< Track * > kaons, float minSignif, float minPT, int minKaons) inline
Definition at line 206 of file AnalysisFunctions.cc.
View newest version in sPHENIX GitHub at line 206 of file AnalysisFunctions.cc
References IsTaggingTrack(), and sIP3D().
Referenced by EventSelectionModule::execute().
bool Tagged_Muon (Jet * jet, std::vector< Track * > muons, float minSignif, float minPT, int minMuons) inline
Definition at line 265 of file AnalysisFunctions.cc.
View newest version in sPHENIX GitHub at line 265 of file AnalysisFunctions.cc
References IsTaggingTrack(), and sIP3D().
Referenced by EventSelectionModule::execute().
bool Tagged_sIP3D (Jet * jet, TClonesArray tracks, float minSignif, float minPT, int minTracks) inline
Definition at line 295 of file AnalysisFunctions.cc.
View newest version in sPHENIX GitHub at line 295 of file AnalysisFunctions.cc
References IsTaggingTrack(), and sIP3D().
Referenced by TaggingModule::execute(), TaggingStudyModule::execute(), and EventSelectionModule::execute().