EIC Software: FairDbResultNonAgg Class Reference
FairDbResultNonAgg Class Reference
#include <EicRoot/blob/master/dbase/dbInterface/FairDbResult.h>
Public Member Functions
FairDbResultNonAgg (FairDbResultSet *resultSet=0, const FairDbTableRow *tableRow=0, const FairDbValidityRec *vrec=0, Bool_t dropSeqNo=kTRUE, const string &sqlQualifiers="")
virtual ~FairDbResultNonAgg ()
virtual FairDbResultKey * CreateKey () const
virtual UInt_t GetNumAggregates () const
virtual UInt_t GetNumRows () const
virtual const FairDbTableRow * GetTableRow (UInt_t rowNum) const
virtual const FairDbTableRow * GetTableRowByIndex (UInt_t index) const
virtual Bool_t Owns (const FairDbTableRow *row) const
Bool_t Satisfies (const FairDbValidityRec &vrec, const string &sqlQualifiers="")
virtual void Streamer (FairDbBinaryFile &file)
Public Member Functions inherited from FairDbResult
FairDbResult (FairDbResultSet *resultSet=0, const FairDbValidityRec *vrec=0, const string &sqlQualifiers="")
FairDbResult (const FairDbResult &)
virtual ~FairDbResult ()
virtual Bool_t CanReuse () const
virtual Bool_t CanSave () const
virtual void Connect () const
virtual void Disconnect () const
Int_t GetID () const
virtual const FairDbResultKey * GetKey () const
virtual UInt_t GetNumClients () const
const string & GetSqlQualifiers () const
virtual const FairDbValidityRec & GetValidityRec (const FairDbTableRow *row=0) const
virtual const FairDbValidityRec & GetValidityRecGlobal () const
Bool_t IsExtendedContext () const
Bool_t ResultsFromDb () const
virtual const string & TableName () const
virtual Bool_t CanDelete (const FairDbResult *res=0)
virtual Bool_t Satisfies (const ValContext &vc, const FairDb::Task &task)
virtual Bool_t Satisfies (const string &)
virtual void DeRegisterKey ()
virtual void RegisterKey ()
virtual void SetCanReuse (Bool_t reuse)
void CaptureExceptionLog (UInt_t startFrom)
Private Member Functions
void DebugCtor () const
FairDbResultNonAgg (const FairDbResultNonAgg &)
FairDbResultNonAgg operator= (const FairDbResultNonAgg &)
Private Attributes
std::vector< FairDbTableRow * > fRows
Char_t * fBuffer
Additional Inherited Members
Protected Member Functions inherited from FairDbResult
void SetResultsFromDb ()
void BuildLookUpTable () const
Bool_t LookUpBuilt () const
virtual void SetTableName (const string &tableName)
virtual void SetValidityRec (const FairDbValidityRec &vRec)
Detailed Description
Definition at line 324 of file FairDbResult.h.
View newest version in sPHENIX GitHub at line 324 of file FairDbResult.h
Constructor & Destructor Documentation
FairDbResultNonAgg::FairDbResultNonAgg (FairDbResultSet * resultSet = 0, const FairDbTableRow * tableRow = 0, const FairDbValidityRec * vrec = 0, Bool_t dropSeqNo = kTRUE, const string & sqlQualifiers = "")
FairDbResultNonAgg::~FairDbResultNonAgg () virtual
Definition at line 1090 of file FairDbResult.cxx.
View newest version in sPHENIX GitHub at line 1090 of file FairDbResult.cxx
References fBuffer, and fRows.
FairDbResultNonAgg::FairDbResultNonAgg (const FairDbResultNonAgg &) private
Member Function Documentation
FairDbResultKey * FairDbResultNonAgg::CreateKey () const virtual
Implements FairDbResult.
Definition at line 1102 of file FairDbResult.cxx.
View newest version in sPHENIX GitHub at line 1102 of file FairDbResult.cxx
References FairDbValidityRec::GetCreationDate(), FairDbValidityRec::GetSeqNo(), GetTableRow(), FairDbResult::GetValidityRec(), and FairDbResult::TableName().
void FairDbResultNonAgg::DebugCtor () const private
Definition at line 1115 of file FairDbResult.cxx.
View newest version in sPHENIX GitHub at line 1115 of file FairDbResult.cxx
virtual UInt_t FairDbResultNonAgg::GetNumAggregates () const inline virtual
Implements FairDbResult.
Definition at line 343 of file FairDbResult.h.
View newest version in sPHENIX GitHub at line 343 of file FairDbResult.h
virtual UInt_t FairDbResultNonAgg::GetNumRows () const inline virtual
Implements FairDbResult.
Definition at line 344 of file FairDbResult.h.
View newest version in sPHENIX GitHub at line 344 of file FairDbResult.h
References fRows.
Referenced by ClassImp(), FairDbValidityRecBuilder::FairDbValidityRecBuilder(), and FairDbTableProxy::Query().
const FairDbTableRow * FairDbResultNonAgg::GetTableRow (UInt_t rowNum) const virtual
Implements FairDbResult.
Definition at line 1124 of file FairDbResult.cxx.
View newest version in sPHENIX GitHub at line 1124 of file FairDbResult.cxx
References fRows.
Referenced by ClassImp(), CreateKey(), FairDbValidityRecBuilder::FairDbValidityRecBuilder(), and FairDbTableProxy::Query().
const FairDbTableRow * FairDbResultNonAgg::GetTableRowByIndex (UInt_t index) const virtual
Reimplemented from FairDbResult.
Definition at line 1129 of file FairDbResult.cxx.
View newest version in sPHENIX GitHub at line 1129 of file FairDbResult.cxx
References FairDbResult::BuildLookUpTable(), FairDbResult::GetTableRowByIndex(), and FairDbResult::LookUpBuilt().
FairDbResultNonAgg FairDbResultNonAgg::operator= (const FairDbResultNonAgg &) private
Bool_t FairDbResultNonAgg::Owns (const FairDbTableRow * row) const virtual
Reimplemented from FairDbResult.
Definition at line 1137 of file FairDbResult.cxx.
View newest version in sPHENIX GitHub at line 1137 of file FairDbResult.cxx
References fRows.
Bool_t FairDbResultNonAgg::Satisfies (const FairDbValidityRec & vrec, const string & sqlQualifiers = "") virtual
Reimplemented from FairDbResult.
Definition at line 1149 of file FairDbResult.cxx.
View newest version in sPHENIX GitHub at line 1149 of file FairDbResult.cxx
References FairDbResult::CanReuse(), FairDbValidityRec::GetCreationDate(), FairDbValidityRec::GetSeqNo(), FairDbResult::GetSqlQualifiers(), and FairDbResult::GetValidityRec().
void FairDbResultNonAgg::Streamer (FairDbBinaryFile & file) virtual
Reimplemented from FairDbResult.
Definition at line 1169 of file FairDbResult.cxx.
View newest version in sPHENIX GitHub at line 1169 of file FairDbResult.cxx
References FairDbResult::BuildLookUpTable(), fBuffer, fRows, FairDbBinaryFile::IsReading(), FairDbBinaryFile::IsWriting(), FairDbBinaryFile::ReleaseArrayBuffer(), and FairDbResult::Streamer().
Member Data Documentation
Char_t* FairDbResultNonAgg::fBuffer private
Definition at line 360 of file FairDbResult.h.
View newest version in sPHENIX GitHub at line 360 of file FairDbResult.h
Referenced by Streamer(), and ~FairDbResultNonAgg().
std::vector<FairDbTableRow*> FairDbResultNonAgg::fRows private
Definition at line 359 of file FairDbResult.h.
View newest version in sPHENIX GitHub at line 359 of file FairDbResult.h
Referenced by GetNumRows(), GetTableRow(), Owns(), Streamer(), and ~FairDbResultNonAgg().
The documentation for this class was generated from the following files:
EicRoot/blob/master/dbase/dbInterface/FairDbResult.h
EicRoot/blob/master/dbase/dbInterface/FairDbResult.cxx