EIC Software: EicRoot/blob/master/eic/ayk/import.cxx File Reference
import.cxx File Reference
#include <cstdio>
#include <cstdlib>
#include <cassert>
#include <cstring>
#include <ayk.h>
#include <Splitter.h>
#include <Mgrid.h>
Macros
#define _COORD_ROUNDING_ (1E-4)
Functions
Mgrid * import_field_map (char *file_name)
static double tesla2kgs_fun (double val)
static double m2cm_fun (double val)
static double import_value (const char *string, conversionfun fun)
void release_cell_list_ram (MgridCell *cells)
static void calculate_swapping_rules (t_ascii_coord *coord, int swap[])
static Mgrid * convert_cell_list_to_mgrid (MgridCell *cells, char *name, CoordSystem *coord, CoordSystem *field, int split_mode, unsigned cell_contents_bits)
Mgrid * import_ascii_field_map (char *file_name, char *mgrid_name, t_ascii_coord *coord, t_ascii_coord *field, int lines_to_skip)
Macro Definition Documentation
#define _COORD_ROUNDING_ (1E-4)
Definition at line 22 of file import.cxx.
View newest version in sPHENIX GitHub at line 22 of file import.cxx
Referenced by convert_cell_list_to_mgrid().
Function Documentation
static void calculate_swapping_rules (t_ascii_coord * coord, int swap[]) static
Definition at line 104 of file import.cxx.
View newest version in sPHENIX GitHub at line 104 of file import.cxx
References t_ascii_coord::coord_names, t_ascii_coord::coord_num, find_coord_by_name(), t_coord_name::id, MgridInterpolation::left, and t_ascii_coord::system_type.
Referenced by import_ascii_field_map().
static Mgrid* convert_cell_list_to_mgrid (MgridCell * cells, char * name, CoordSystem * coord, CoordSystem * field, int split_mode, unsigned cell_contents_bits) static
Definition at line 148 of file import.cxx.
View newest version in sPHENIX GitHub at line 148 of file import.cxx
References _COORD_ROUNDING_, _FIELD_COMPONENT_VALUES_, _SPLIT_ON_, _SUPERPOSITION_, Mgrid::attachToHeap(), MgridCell::B, Mgrid::children, Mgrid::compressedCoordToLinearAddr(), create_mgrid_heap_header(), create_single_mgrid_header(), Acts::Test::dim, CoordSystem::fake, CoordSystem::getCoordNum(), MgridHeader::getName(), Mgrid::initializeAsHeap(), Mgrid::initializeAsSingleMgrid(), Mgrid::linearAddrToCellPtr(), Mgrid::markCellAsSafe(), max, MGRID_NAME_LENGTH_MAX, min, MgridCell::next, CoordSystem::setCoordNum(), and Acts::Test::step().
Referenced by import_ascii_field_map().
Mgrid* import_ascii_field_map (char * file_name, char * mgrid_name, t_ascii_coord * coord, t_ascii_coord * field, int lines_to_skip)
Definition at line 364 of file import.cxx.
View newest version in sPHENIX GitHub at line 364 of file import.cxx
References _ASCII_INPUT_, _CELL_DATA_DIM_MAX_, _FIELD_COMPONENT_VALUES_, _SPLIT_OFF_, calculate_swapping_rules(), convert_cell_list_to_mgrid(), t_ascii_coord::convfun, t_ascii_coord::coord_names, t_ascii_coord::coord_num, Splitter::getArgn(), Splitter::getArgp(), import_value(), release_cell_list_ram(), MgridHeader::setCreationMethod(), Splitter::splitNextString(), splitter, and t_ascii_coord::system_type.
Referenced by main().
Mgrid* import_field_map (char * file_name)
Definition at line 29 of file import.cxx.
View newest version in sPHENIX GitHub at line 29 of file import.cxx
References basic_types_match(), and MgridInterpolation::Mgrid.
static double import_value (const char * string, conversionfun fun) static
Definition at line 69 of file import.cxx.
View newest version in sPHENIX GitHub at line 69 of file import.cxx
References MgridInterpolation::fun, and value.
Referenced by import_ascii_field_map().
static double m2cm_fun (double val) static
Definition at line 61 of file import.cxx.
View newest version in sPHENIX GitHub at line 61 of file import.cxx
References m2cm.
Referenced by main().
void release_cell_list_ram (MgridCell * cells)
Definition at line 85 of file import.cxx.
View newest version in sPHENIX GitHub at line 85 of file import.cxx
References MgridCell::next.
Referenced by import_ascii_field_map().
static double tesla2kgs_fun (double val) static
Definition at line 54 of file import.cxx.
View newest version in sPHENIX GitHub at line 54 of file import.cxx
References tesla2kgs.