EIC Software: PHActsTrkProp Class Reference
PHActsTrkProp Class Reference
#include <fun4all_coresoftware/blob/master/offline/packages/trackreco/PHActsTrkProp.h>
Public Member Functions
PHActsTrkProp (const std::string &name="PHActsTrkProp")
Default constructor.
~PHActsTrkProp ()
Destructor.
int End ()
End, write and close files.
int Setup (PHCompositeNode *topNode)
Get and create nodes.
int Process ()
Process each event by calling the fitter.
int ResetEvent (PHCompositeNode *topNode)
Reset maps event by event.
void doTimeAnalysis (bool timeAnalysis)
void setVolumeMaxChi2 (const int vol, const float maxChi2)
void setVolumeLayerMaxChi2 (const int vol, const int layer, const float maxChi2)
void resetCovariance (bool resetCovariance)
Public Member Functions inherited from PHTrackPropagating
PHTrackPropagating (const std::string &name="PHTrackPropagating")
virtual ~PHTrackPropagating ()
int InitRun (PHCompositeNode *topNode)
int process_event (PHCompositeNode *topNode)
int End (PHCompositeNode *topNode)
Called at the end of all processing.
void set_track_map_name (const std::string &map_name)
void SetUseTruthClusters (bool setit)
Public Member Functions inherited from SubsysReco
virtual ~SubsysReco ()
virtual int EndRun (const int)
Called at the end of each run.
virtual int Init (PHCompositeNode *)
virtual int Reset (PHCompositeNode *)
Reset.
virtual void Print (const std::string &what="ALL") const
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Private Member Functions
void initializeLayerSelector ()
int getNodes (PHCompositeNode *topNode)
Get all the nodes.
void createNodes (PHCompositeNode *topNode)
Create new nodes.
Acts::GeometryIdentifier makeId (int volume=0, int layer=0, int sensitive=0)
Helper function to make an Acts::GeometryID for SL selection.
void updateSvtxTrack (Trajectory traj, const unsigned int trackKey, Acts::Vector3D vertex)
Wipe and recreate the SvtxTrackMap with Acts output.
std::vector< SourceLink > getEventSourceLinks ()
Get all source links in a given event.
void setupSourceLinkSelection ()
Setup the source link selector criteria.
Private Attributes
int m_event
Event counter.
bool m_timeAnalysis
TFile * m_timeFile
TH1 * h_eventTime
std::map< const int, const float > m_volMaxChi2
std::vector< std::map< const
int, const float > > m_volLayerMaxChi2
int m_nBadFits
Num bad fit counter.
ActsTrackingGeometry * m_tGeometry
bool m_resetCovariance
SvtxTrackMap * m_trackMap
Track map with Svtx objects.
std::map< unsigned int,
ActsTrack > * m_actsProtoTracks
Track map with ActsTracks, created in PHActsTracks.
std::map< const unsigned int,
Trajectory > * m_actsFitResults
Acts MultiTrajectories for ActsEvaluator.
std::map< const unsigned int,
std::map< const size_t, const
unsigned int > > * m_actsTrackKeyMap
CluskeyBimap * m_hitIdClusKey
Map of cluster keys to hit ids, for identifying clusters belonging to track.
std::map< unsigned int,
SourceLink > * m_sourceLinks
PHCompositeNode * m_topNode
SourceLinkSelectorConfig m_sourceLinkSelectorConfig
ActsExamples::TrkrClusterFindingAlgorithm::Config findCfg
Configuration containing the finding function instance.
Acts::PropagatorPlainOptions m_actsPropPlainOptions
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = INT_MAX - 10
}
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Protected Attributes inherited from PHTrackPropagating
TrkrClusterContainer * _cluster_map
SvtxVertexMap * _vertex_map
SvtxTrackMap * _track_map
AssocInfoContainer * _assoc_container
std::string _track_map_name
bool _use_truth_clusters = false
Detailed Description
Definition at line 69 of file PHActsTrkProp.h.
View newest version in sPHENIX GitHub at line 69 of file PHActsTrkProp.h
Constructor & Destructor Documentation
PHActsTrkProp::PHActsTrkProp (const std::string & name = "PHActsTrkProp")
Default constructor.
Definition at line 56 of file PHActsTrkProp.cc.
View newest version in sPHENIX GitHub at line 56 of file PHActsTrkProp.cc
References initializeLayerSelector(), and Fun4AllBase::Verbosity().
PHActsTrkProp::~PHActsTrkProp ()
Destructor.
Definition at line 77 of file PHActsTrkProp.cc.
View newest version in sPHENIX GitHub at line 77 of file PHActsTrkProp.cc
Member Function Documentation
void PHActsTrkProp::createNodes (PHCompositeNode * topNode) private
Create new nodes.
Definition at line 609 of file PHActsTrkProp.cc.
View newest version in sPHENIX GitHub at line 609 of file PHActsTrkProp.cc
References PHCompositeNode::addNode(), PHNodeIterator::findFirst(), findNode::getClass(), m_actsFitResults, and m_actsTrackKeyMap.
Referenced by Setup().
void PHActsTrkProp::doTimeAnalysis (bool timeAnalysis) inline
Definition at line 90 of file PHActsTrkProp.h.
View newest version in sPHENIX GitHub at line 90 of file PHActsTrkProp.h
References m_timeAnalysis.
int PHActsTrkProp::End () virtual
End, write and close files.
Implements PHTrackPropagating.
Definition at line 290 of file PHActsTrkProp.cc.
View newest version in sPHENIX GitHub at line 290 of file PHActsTrkProp.cc
References Fun4AllReturnCodes::EVENT_OK, h_eventTime, m_nBadFits, m_timeAnalysis, m_timeFile, and Fun4AllBase::Verbosity().
std::vector< SourceLink > PHActsTrkProp::getEventSourceLinks () private
Get all source links in a given event.
Definition at line 115 of file PHActsTrkProp.cc.
View newest version in sPHENIX GitHub at line 115 of file PHActsTrkProp.cc
References ActsTrackingGeometry::geoContext, m_sourceLinks, m_tGeometry, and Fun4AllBase::Verbosity().
Referenced by Process().
int PHActsTrkProp::getNodes (PHCompositeNode * topNode) private
Get all the nodes.
Definition at line 660 of file PHActsTrkProp.cc.
View newest version in sPHENIX GitHub at line 660 of file PHActsTrkProp.cc
References Fun4AllReturnCodes::ABORTEVENT, Fun4AllReturnCodes::EVENT_OK, m_actsProtoTracks, m_hitIdClusKey, m_sourceLinks, m_tGeometry, m_topNode, m_trackMap, and PHWHERE.
Referenced by Setup().
void PHActsTrkProp::initializeLayerSelector () private
Definition at line 717 of file PHActsTrkProp.cc.
View newest version in sPHENIX GitHub at line 717 of file PHActsTrkProp.cc
References m_volLayerMaxChi2.
Referenced by PHActsTrkProp().
Acts::GeometryIdentifier PHActsTrkProp::makeId (int volume = 0, int layer = 0, int sensitive = 0) private
Helper function to make an Acts::GeometryID for SL selection.
Definition at line 575 of file PHActsTrkProp.cc.
View newest version in sPHENIX GitHub at line 575 of file PHActsTrkProp.cc
Referenced by setupSourceLinkSelection().
int PHActsTrkProp::Process () virtual
Process each event by calling the fitter.
Collect all source links for the CKF
If we are resetting the covariance and the space point to the vertex, the POCA should have the covariance of the vertex
Construct a perigee surface as the target surface This surface is what Acts fits with respect to, so we set it to the initial vertex estimation
Construct the options to pass to the CKF. SourceLinkSelector set in Init()
Run the CKF for all source links and the constructed track seed CKF runs both track finder and KF track fitter
Implements PHTrackPropagating.
Definition at line 139 of file PHActsTrkProp.cc.
View newest version in sPHENIX GitHub at line 139 of file PHActsTrkProp.cc
References ActsTrackingGeometry::calibContext, Fun4AllReturnCodes::EVENT_OK, findCfg, Acts::CombinatorialKalmanFilterResult< source_link_t >::fittedParameters, Acts::CombinatorialKalmanFilterResult< source_link_t >::fittedStates, ActsTrackingGeometry::geoContext, Acts::getDefaultLogger(), getEventSourceLinks(), ActsTrack::getTrackParams(), ActsTrack::getVertex(), h_eventTime, Acts::Logging::INFO, m_actsFitResults, m_actsPropPlainOptions, m_actsProtoTracks, m_event, m_nBadFits, m_resetCovariance, m_sourceLinkSelectorConfig, m_tGeometry, m_timeAnalysis, ActsTrackingGeometry::magFieldContext, PHWHERE, Acts::SingleTrackParameters< ChargePolicy >::position(), Acts::CombinatorialKalmanFilterResult< source_link_t >::trackTips, Acts::UnitConstants::um, updateSvtxTrack(), Acts::Logging::VERBOSE, and Fun4AllBase::Verbosity().
void PHActsTrkProp::resetCovariance (bool resetCovariance) inline
Definition at line 95 of file PHActsTrkProp.h.
View newest version in sPHENIX GitHub at line 95 of file PHActsTrkProp.h
References m_resetCovariance, and resetCovariance().
Referenced by resetCovariance().
int PHActsTrkProp::ResetEvent (PHCompositeNode * topNode) virtual
Reset maps event by event.
Reimplemented from SubsysReco.
Definition at line 282 of file PHActsTrkProp.cc.
View newest version in sPHENIX GitHub at line 282 of file PHActsTrkProp.cc
References Fun4AllReturnCodes::EVENT_OK, m_actsFitResults, and m_actsTrackKeyMap.
int PHActsTrkProp::Setup (PHCompositeNode * topNode) virtual
Get and create nodes.
Setup the source link selection criteria for the various layers
Setup the Acts general/generic propagator options see struct in acts/Core/include/Acts/Propagator/Propagator.hpp for additional options that can be changed
Reimplemented from PHTrackPropagating.
Definition at line 81 of file PHActsTrkProp.cc.
View newest version in sPHENIX GitHub at line 81 of file PHActsTrkProp.cc
References Fun4AllReturnCodes::ABORTEVENT, createNodes(), Fun4AllReturnCodes::EVENT_OK, findCfg, getNodes(), h_eventTime, m_actsPropPlainOptions, m_tGeometry, m_timeAnalysis, m_timeFile, ActsTrackingGeometry::magField, setupSourceLinkSelection(), ActsTrackingGeometry::tGeometry, and Fun4AllBase::Verbosity().
void PHActsTrkProp::setupSourceLinkSelection () private
Setup the source link selector criteria.
The CKF requires a source link selector which helps it identify possible SLs to the track. The selections can be added like {makeId(volId, layerId), {maxChi2, numSourceLinks}} We'll just put the max chi2 to 10
Global detector criteria
Volume criteria Volume IDs - MVTX = 7, INTT = 9, TPC = 11
Set individual layer criteria (e.g. for first layer of TPC) Individual layers should only have one SL per layer
Vol IDs are 7, 9, 11, hence vol*2+7
Definition at line 532 of file PHActsTrkProp.cc.
View newest version in sPHENIX GitHub at line 532 of file PHActsTrkProp.cc
References m_volLayerMaxChi2, m_volMaxChi2, makeId(), and vector().
Referenced by Setup().
void PHActsTrkProp::setVolumeLayerMaxChi2 (const int vol, const int layer, const float maxChi2)
Definition at line 584 of file PHActsTrkProp.cc.
View newest version in sPHENIX GitHub at line 584 of file PHActsTrkProp.cc
References m_volLayerMaxChi2, and Acts::Test::volume.
void PHActsTrkProp::setVolumeMaxChi2 (const int vol, const float maxChi2)
Definition at line 604 of file PHActsTrkProp.cc.
View newest version in sPHENIX GitHub at line 604 of file PHActsTrkProp.cc
References m_volMaxChi2.
void PHActsTrkProp::updateSvtxTrack (Trajectory traj, const unsigned int trackKey, Acts::Vector3D vertex) private
Wipe and recreate the SvtxTrackMap with Acts output.
There could be multiple tracks per trajectory found from the CKF Therefore we need to get the info from the original SvtxTrack that we need, and then create new tracks
All these tracks should have the same vertexId if they came from the same track seed
hack for now to just set the vertex id to 0 if it is needed
Create a state at 0.0 to propagate out from
This gets the track indexer and associated tracks (Acts::MultiTrajectories)
Iterate over the found tracks via their trackTip index
No trackParameters for this trackTip, so fit failed for this tip
If it is the first track, just update the original track seed
Get the last track key so that we can add new tracks if needed
Otherwise make a new track
Needs to be a new track id
If negative QOP then set charge to negative
Now insert the trajectory + trackTip-trackKey pair
Definition at line 310 of file PHActsTrkProp.cc.
View newest version in sPHENIX GitHub at line 310 of file PHActsTrkProp.cc
References ActsTransformations::calculateDCA(), Acts::UnitConstants::cm, Acts::eBoundQOverP, SvtxTrackMap::end(), ActsTransformations::fillSvtxTrackStates(), SvtxTrackMap::find(), ActsTrackingGeometry::geoContext, SvtxTrack::get_vertex_id(), SvtxTrackMap::insert(), SvtxTrack::insert_state(), m_actsTrackKeyMap, m_hitIdClusKey, m_tGeometry, m_trackMap, lit::NDF(), SvtxTrack::Reset(), ActsTransformations::rotateActsCovToSvtxTrack(), SvtxTrack_v1::set_charge(), SvtxTrack::set_charge(), SvtxTrack_v1::set_chisq(), SvtxTrack::set_chisq(), SvtxTrack_v1::set_dca3d_xy(), SvtxTrack::set_dca3d_xy(), SvtxTrack_v1::set_dca3d_xy_error(), SvtxTrack::set_dca3d_xy_error(), SvtxTrack_v1::set_dca3d_z(), SvtxTrack::set_dca3d_z(), SvtxTrack_v1::set_dca3d_z_error(), SvtxTrack::set_dca3d_z_error(), SvtxTrack_v1::set_error(), SvtxTrack::set_error(), SvtxTrack_v1::set_id(), SvtxTrack::set_id(), SvtxTrack_v1::set_ndf(), SvtxTrack::set_ndf(), SvtxTrack_v1::set_px(), SvtxTrack::set_px(), SvtxTrack_v1::set_py(), SvtxTrack::set_py(), SvtxTrack_v1::set_pz(), SvtxTrack::set_pz(), SvtxTrack_v1::set_vertex_id(), SvtxTrack::set_vertex_id(), SvtxTrackState_v1::set_x(), SvtxTrack_v1::set_x(), SvtxTrack::set_x(), SvtxTrackState_v1::set_y(), SvtxTrack_v1::set_y(), SvtxTrack::set_y(), SvtxTrackState_v1::set_z(), SvtxTrack_v1::set_z(), SvtxTrack::set_z(), ActsTransformations::setVerbosity(), Fun4AllBase::Verbosity(), x, analysis::y, and z.
Referenced by Process().
Member Data Documentation
ActsExamples::TrkrClusterFindingAlgorithm::Config PHActsTrkProp::findCfg private
Configuration containing the finding function instance.
Definition at line 175 of file PHActsTrkProp.h.
View newest version in sPHENIX GitHub at line 175 of file PHActsTrkProp.h
Referenced by Process(), and Setup().
TH1* PHActsTrkProp::h_eventTime private
Definition at line 104 of file PHActsTrkProp.h.
View newest version in sPHENIX GitHub at line 104 of file PHActsTrkProp.h
Referenced by End(), Process(), and Setup().
std::map<const unsigned int, Trajectory>* PHActsTrkProp::m_actsFitResults private
Acts MultiTrajectories for ActsEvaluator.
Definition at line 153 of file PHActsTrkProp.h.
View newest version in sPHENIX GitHub at line 153 of file PHActsTrkProp.h
Referenced by createNodes(), Process(), and ResetEvent().
Acts::PropagatorPlainOptions PHActsTrkProp::m_actsPropPlainOptions private
Definition at line 177 of file PHActsTrkProp.h.
View newest version in sPHENIX GitHub at line 177 of file PHActsTrkProp.h
Referenced by Process(), and Setup().
std::map<unsigned int, ActsTrack>* PHActsTrkProp::m_actsProtoTracks private
Track map with ActsTracks, created in PHActsTracks.
Definition at line 150 of file PHActsTrkProp.h.
View newest version in sPHENIX GitHub at line 150 of file PHActsTrkProp.h
Referenced by getNodes(), and Process().
std::map<const unsigned int, std::map<const size_t, const unsigned int> >* PHActsTrkProp::m_actsTrackKeyMap private
Map that correlates track key with track tip for ActsEvaluator Identifiers are <TrajNum, <trackTip, SvtxTrackKey>> where TrajNum has a one-to-one map to the original seed SvtxTrackKey
Definition at line 159 of file PHActsTrkProp.h.
View newest version in sPHENIX GitHub at line 159 of file PHActsTrkProp.h
Referenced by createNodes(), ResetEvent(), and updateSvtxTrack().
int PHActsTrkProp::m_event private
Event counter.
Definition at line 100 of file PHActsTrkProp.h.
View newest version in sPHENIX GitHub at line 100 of file PHActsTrkProp.h
Referenced by Process().
CluskeyBimap* PHActsTrkProp::m_hitIdClusKey private
Map of cluster keys to hit ids, for identifying clusters belonging to track.
Definition at line 162 of file PHActsTrkProp.h.
View newest version in sPHENIX GitHub at line 162 of file PHActsTrkProp.h
Referenced by getNodes(), and updateSvtxTrack().
int PHActsTrkProp::m_nBadFits private
Num bad fit counter.
Definition at line 118 of file PHActsTrkProp.h.
View newest version in sPHENIX GitHub at line 118 of file PHActsTrkProp.h
Referenced by End(), and Process().
bool PHActsTrkProp::m_resetCovariance private
Definition at line 144 of file PHActsTrkProp.h.
View newest version in sPHENIX GitHub at line 144 of file PHActsTrkProp.h
Referenced by Process(), and resetCovariance().
std::map<unsigned int, SourceLink>* PHActsTrkProp::m_sourceLinks private
Acts source links created by PHActsSourceLinks SourceLink is defined as TrkrClusterSourceLink elsewhere
Definition at line 166 of file PHActsTrkProp.h.
View newest version in sPHENIX GitHub at line 166 of file PHActsTrkProp.h
Referenced by getEventSourceLinks(), and getNodes().
SourceLinkSelectorConfig PHActsTrkProp::m_sourceLinkSelectorConfig private
SourceLinkSelector to help the CKF identify which source links may belong to a track seed based on geometry considerations
Definition at line 172 of file PHActsTrkProp.h.
View newest version in sPHENIX GitHub at line 172 of file PHActsTrkProp.h
Referenced by Process().
ActsTrackingGeometry* PHActsTrkProp::m_tGeometry private
Definition at line 142 of file PHActsTrkProp.h.
View newest version in sPHENIX GitHub at line 142 of file PHActsTrkProp.h
Referenced by getEventSourceLinks(), getNodes(), Process(), Setup(), and updateSvtxTrack().
bool PHActsTrkProp::m_timeAnalysis private
Definition at line 102 of file PHActsTrkProp.h.
View newest version in sPHENIX GitHub at line 102 of file PHActsTrkProp.h
Referenced by doTimeAnalysis(), End(), Process(), and Setup().
TFile* PHActsTrkProp::m_timeFile private
Definition at line 103 of file PHActsTrkProp.h.
View newest version in sPHENIX GitHub at line 103 of file PHActsTrkProp.h
Referenced by End(), and Setup().
PHCompositeNode* PHActsTrkProp::m_topNode private
Definition at line 168 of file PHActsTrkProp.h.
View newest version in sPHENIX GitHub at line 168 of file PHActsTrkProp.h
Referenced by getNodes().
SvtxTrackMap* PHActsTrkProp::m_trackMap private
Track map with Svtx objects.
Definition at line 147 of file PHActsTrkProp.h.
View newest version in sPHENIX GitHub at line 147 of file PHActsTrkProp.h
Referenced by getNodes(), and updateSvtxTrack().
std::vector<std::map<const int, const float> > PHActsTrkProp::m_volLayerMaxChi2 private
array of maps to hold maximum allowable measurement chi 2 in a particular layer of a particular volume id in acts Entries are 0 - MVTX, 1 - INTT, 2 - TPC
Definition at line 115 of file PHActsTrkProp.h.
View newest version in sPHENIX GitHub at line 115 of file PHActsTrkProp.h
Referenced by initializeLayerSelector(), setupSourceLinkSelection(), and setVolumeLayerMaxChi2().
std::map<const int, const float> PHActsTrkProp::m_volMaxChi2 private
Map to hold maximum allowable measurement chi2 in each volume identifier in Acts
Definition at line 110 of file PHActsTrkProp.h.
View newest version in sPHENIX GitHub at line 110 of file PHActsTrkProp.h
Referenced by setupSourceLinkSelection(), and setVolumeMaxChi2().
The documentation for this class was generated from the following files:
fun4all_coresoftware/blob/master/offline/packages/trackreco/PHActsTrkProp.h
fun4all_coresoftware/blob/master/offline/packages/trackreco/PHActsTrkProp.cc