EIC Software: TaggingModule Class Reference
TaggingModule Class Reference
#include <delphes_EIC/blob/master/SimpleAnalysis/TaggingModule.h>
Public Member Functions
TaggingModule (ExRootTreeReader *data)
~TaggingModule ()
void initialize () override
bool execute (std::map< std::string, std::any > *DataStore) override
void finalize () override
Public Member Functions inherited from Module
Module (ExRootTreeReader *data)
~Module ()
ExRootTreeReader * getData ()
void setJets (TClonesArray *jets)
void setElectrons (TClonesArray *electrons)
void setPhotons (TClonesArray *photons)
void setNeutralHadrons (TClonesArray *neutralhadrons)
void setMuons (TClonesArray *muons)
void setTracks (TClonesArray *tracks)
void setEFlowTracks (TClonesArray *tracks)
void setMET (TClonesArray *met)
void setGenParticles (TClonesArray *particles)
void setGenJets (TClonesArray *genjets)
TClonesArray * getJets ()
TClonesArray * getElectrons ()
TClonesArray * getPhotons ()
TClonesArray * getNeutralHadrons ()
TClonesArray * getMuons ()
TClonesArray * getEFlowTracks ()
TClonesArray * getTracks ()
TClonesArray * getMET ()
TClonesArray * getGenParticles ()
TClonesArray * getGenJets ()
Private Attributes
float _jet_pt
float _jet_eta
float _jet_flavor
float _jet_sip3dtagged
float _jet_ktagged
float _jet_etagged
float _jet_mutagged
float _jet_btag
float _bjorken_x
float _bjorken_Q2
float _JB_x
float _JB_Q2
Detailed Description
Definition at line 8 of file TaggingModule.h.
View newest version in sPHENIX GitHub at line 8 of file TaggingModule.h
Constructor & Destructor Documentation
TaggingModule::TaggingModule (ExRootTreeReader * data)
Definition at line 13 of file TaggingModule.cc.
View newest version in sPHENIX GitHub at line 13 of file TaggingModule.cc
TaggingModule::~TaggingModule ()
Definition at line 19 of file TaggingModule.cc.
View newest version in sPHENIX GitHub at line 19 of file TaggingModule.cc
Member Function Documentation
bool TaggingModule::execute (std::map< std::string, std::any > * DataStore) override virtual
Reimplemented from Module.
Definition at line 33 of file TaggingModule.cc.
View newest version in sPHENIX GitHub at line 33 of file TaggingModule.cc
References data, Module::getData(), Module::getEFlowTracks(), Module::getJets(), and Tagged_sIP3D().
void TaggingModule::finalize () override virtual
Reimplemented from Module.
Definition at line 29 of file TaggingModule.cc.
View newest version in sPHENIX GitHub at line 29 of file TaggingModule.cc
void TaggingModule::initialize () override virtual
Reimplemented from Module.
Definition at line 24 of file TaggingModule.cc.
View newest version in sPHENIX GitHub at line 24 of file TaggingModule.cc
Member Data Documentation
float TaggingModule::_bjorken_Q2 private
Definition at line 34 of file TaggingModule.h.
View newest version in sPHENIX GitHub at line 34 of file TaggingModule.h
float TaggingModule::_bjorken_x private
Definition at line 33 of file TaggingModule.h.
View newest version in sPHENIX GitHub at line 33 of file TaggingModule.h
float TaggingModule::_JB_Q2 private
Definition at line 36 of file TaggingModule.h.
View newest version in sPHENIX GitHub at line 36 of file TaggingModule.h
float TaggingModule::_JB_x private
Definition at line 35 of file TaggingModule.h.
View newest version in sPHENIX GitHub at line 35 of file TaggingModule.h
float TaggingModule::_jet_btag private
Definition at line 31 of file TaggingModule.h.
View newest version in sPHENIX GitHub at line 31 of file TaggingModule.h
float TaggingModule::_jet_eta private
Definition at line 25 of file TaggingModule.h.
View newest version in sPHENIX GitHub at line 25 of file TaggingModule.h
float TaggingModule::_jet_etagged private
Definition at line 29 of file TaggingModule.h.
View newest version in sPHENIX GitHub at line 29 of file TaggingModule.h
float TaggingModule::_jet_flavor private
Definition at line 26 of file TaggingModule.h.
View newest version in sPHENIX GitHub at line 26 of file TaggingModule.h
float TaggingModule::_jet_ktagged private
Definition at line 28 of file TaggingModule.h.
View newest version in sPHENIX GitHub at line 28 of file TaggingModule.h
float TaggingModule::_jet_mutagged private
Definition at line 30 of file TaggingModule.h.
View newest version in sPHENIX GitHub at line 30 of file TaggingModule.h
float TaggingModule::_jet_pt private
Definition at line 24 of file TaggingModule.h.
View newest version in sPHENIX GitHub at line 24 of file TaggingModule.h
float TaggingModule::_jet_sip3dtagged private
Definition at line 27 of file TaggingModule.h.
View newest version in sPHENIX GitHub at line 27 of file TaggingModule.h
The documentation for this class was generated from the following files:
delphes_EIC/blob/master/SimpleAnalysis/TaggingModule.h
delphes_EIC/blob/master/SimpleAnalysis/TaggingModule.cc