EIC Software: AllSiliconTrackerSteppingAction Class Reference
AllSiliconTrackerSteppingAction Class Reference
#include <fun4all_eicdetectors/blob/master/simulation/g4simulation/g4lblvtx/AllSiliconTrackerSteppingAction.h>
Public Member Functions
AllSiliconTrackerSteppingAction (AllSiliconTrackerDetector *, const PHParameters *parameters)
constructor
virtual ~AllSiliconTrackerSteppingAction ()
destructor
virtual bool UserSteppingAction (const G4Step *, bool)
stepping action
AllSiliconTrackerSteppingAction (AllSiliconTrackerDetector *, const PHParameters *parameters)
constructor
virtual ~AllSiliconTrackerSteppingAction ()
destructor
virtual bool UserSteppingAction (const G4Step *, bool)
stepping action
Public Member Functions inherited from PHG4SteppingAction
PHG4SteppingAction (const std::string &name, const int i=0)
virtual ~PHG4SteppingAction ()
virtual void Verbosity (const int i)
virtual int Verbosity () const
virtual int Init ()
virtual double GetScintLightYield (const G4Step *step)
get scintillation photon count. It require a custom set SCINTILLATIONYIELD property to work
virtual double GetVisibleEnergyDeposition (const G4Step *step)
get amount of energy that can make scintillation light, in Unit of GeV.
virtual void StoreLocalCoordinate (PHG4Hit *hit, const G4Step *step, const bool do_prepoint, const bool do_postpoint)
Extract local coordinate of the hit and save to PHG4Hit.
virtual void SetInterfacePointers (PHCompositeNode *)
virtual void Print (const std::string &) const
std::string GetName () const
void SetName (const std::string &name)
virtual void SetLightCorrection (const double inner_radius, const double inner_corr, const double outer_radius, const double outer_corr)
virtual double GetLightCorrection (const double r) const
virtual double GetLightCorrection (const double xpos, const double ypos) const
virtual bool ValidCorrection () const
virtual void SetHitNodeName (const std::string &, const std::string &)
Set the G4HIT node names from Subsystem rather than constructing your own.
Private Attributes
AllSiliconTrackerDetector * m_Detector
pointer to the detector
const PHParameters * m_Params
PHG4HitContainer * m_HitContainer
pointer to hit container
PHG4HitContainer * m_AbsorberHitContainer
PHG4Hit * m_Hit
PHG4HitContainer * m_SaveHitContainer
G4VPhysicalVolume * m_SaveVolPre
G4VPhysicalVolume * m_SaveVolPost
int m_SaveTrackId
int m_SavePreStepStatus
int m_SavePostStepStatus
int m_BlackHoleFlag
double m_EdepSum
Detailed Description
Definition at line 17 of file AllSiliconTrackerSteppingAction.h.
View newest version in sPHENIX GitHub at line 17 of file AllSiliconTrackerSteppingAction.h
Constructor & Destructor Documentation
AllSiliconTrackerSteppingAction::AllSiliconTrackerSteppingAction (AllSiliconTrackerDetector * detector, const PHParameters * parameters)
constructor
Definition at line 45 of file AllSiliconTrackerSteppingAction.cc.
View newest version in sPHENIX GitHub at line 45 of file AllSiliconTrackerSteppingAction.cc
AllSiliconTrackerSteppingAction::~AllSiliconTrackerSteppingAction () virtual
destructor
Definition at line 64 of file AllSiliconTrackerSteppingAction.cc.
View newest version in sPHENIX GitHub at line 64 of file AllSiliconTrackerSteppingAction.cc
References m_Hit.
AllSiliconTrackerSteppingAction::AllSiliconTrackerSteppingAction (AllSiliconTrackerDetector * , const PHParameters * parameters)
constructor
virtual AllSiliconTrackerSteppingAction::~AllSiliconTrackerSteppingAction () virtual
destructor
Member Function Documentation
bool AllSiliconTrackerSteppingAction::UserSteppingAction (const G4Step * aStep, bool was_used) virtual
stepping action
Implements PHG4SteppingAction.
Definition at line 75 of file AllSiliconTrackerSteppingAction.cc.
View newest version in sPHENIX GitHub at line 75 of file AllSiliconTrackerSteppingAction.cc
References PHG4HitContainer::AddHit(), Acts::UnitConstants::cm, AllSiliconTrackerDetector::get_detid(), PHG4Hit::get_hit_id(), AllSiliconTrackerDetector::get_hitcontainer(), PHG4Hit::get_x(), PHG4HitContainer::GetID(), PHG4SteppingAction::GetName(), PHG4StepStatusDecode::GetStepStatus(), Acts::UnitConstants::GeV, AllSiliconTrackerDetector::IsInDetector(), m_BlackHoleFlag, m_Detector, m_EdepSum, m_Hit, m_SaveHitContainer, m_SavePostStepStatus, m_SavePreStepStatus, m_SaveTrackId, m_SaveVolPost, m_SaveVolPre, p, PHG4Hit::Reset(), PHG4Hit::set_edep(), PHG4Hit::set_layer(), PHG4Hit::set_t(), PHG4Hit::set_trkid(), PHG4Hit::set_x(), PHG4Hit::set_y(), PHG4Hit::set_z(), and Acts::Test::volume.
virtual bool AllSiliconTrackerSteppingAction::UserSteppingAction (const G4Step * , bool) virtual
stepping action
Implements PHG4SteppingAction.
Member Data Documentation
PHG4HitContainer * AllSiliconTrackerSteppingAction::m_AbsorberHitContainer private
Definition at line 35 of file AllSiliconTrackerSteppingAction.h.
View newest version in sPHENIX GitHub at line 35 of file AllSiliconTrackerSteppingAction.h
int AllSiliconTrackerSteppingAction::m_BlackHoleFlag private
Definition at line 44 of file AllSiliconTrackerSteppingAction.h.
View newest version in sPHENIX GitHub at line 44 of file AllSiliconTrackerSteppingAction.h
Referenced by UserSteppingAction().
AllSiliconTrackerDetector * AllSiliconTrackerSteppingAction::m_Detector private
pointer to the detector
Definition at line 31 of file AllSiliconTrackerSteppingAction.h.
View newest version in sPHENIX GitHub at line 31 of file AllSiliconTrackerSteppingAction.h
Referenced by UserSteppingAction().
double AllSiliconTrackerSteppingAction::m_EdepSum private
Definition at line 45 of file AllSiliconTrackerSteppingAction.h.
View newest version in sPHENIX GitHub at line 45 of file AllSiliconTrackerSteppingAction.h
Referenced by UserSteppingAction().
PHG4Hit * AllSiliconTrackerSteppingAction::m_Hit private
Definition at line 36 of file AllSiliconTrackerSteppingAction.h.
View newest version in sPHENIX GitHub at line 36 of file AllSiliconTrackerSteppingAction.h
Referenced by UserSteppingAction(), and ~AllSiliconTrackerSteppingAction().
PHG4HitContainer * AllSiliconTrackerSteppingAction::m_HitContainer private
pointer to hit container
Definition at line 34 of file AllSiliconTrackerSteppingAction.h.
View newest version in sPHENIX GitHub at line 34 of file AllSiliconTrackerSteppingAction.h
const PHParameters * AllSiliconTrackerSteppingAction::m_Params private
Definition at line 32 of file AllSiliconTrackerSteppingAction.h.
View newest version in sPHENIX GitHub at line 32 of file AllSiliconTrackerSteppingAction.h
PHG4HitContainer * AllSiliconTrackerSteppingAction::m_SaveHitContainer private
Definition at line 37 of file AllSiliconTrackerSteppingAction.h.
View newest version in sPHENIX GitHub at line 37 of file AllSiliconTrackerSteppingAction.h
Referenced by UserSteppingAction().
int AllSiliconTrackerSteppingAction::m_SavePostStepStatus private
Definition at line 43 of file AllSiliconTrackerSteppingAction.h.
View newest version in sPHENIX GitHub at line 43 of file AllSiliconTrackerSteppingAction.h
Referenced by UserSteppingAction().
int AllSiliconTrackerSteppingAction::m_SavePreStepStatus private
Definition at line 42 of file AllSiliconTrackerSteppingAction.h.
View newest version in sPHENIX GitHub at line 42 of file AllSiliconTrackerSteppingAction.h
Referenced by UserSteppingAction().
int AllSiliconTrackerSteppingAction::m_SaveTrackId private
Definition at line 41 of file AllSiliconTrackerSteppingAction.h.
View newest version in sPHENIX GitHub at line 41 of file AllSiliconTrackerSteppingAction.h
Referenced by UserSteppingAction().
G4VPhysicalVolume * AllSiliconTrackerSteppingAction::m_SaveVolPost private
Definition at line 39 of file AllSiliconTrackerSteppingAction.h.
View newest version in sPHENIX GitHub at line 39 of file AllSiliconTrackerSteppingAction.h
Referenced by UserSteppingAction().
G4VPhysicalVolume * AllSiliconTrackerSteppingAction::m_SaveVolPre private
Definition at line 38 of file AllSiliconTrackerSteppingAction.h.
View newest version in sPHENIX GitHub at line 38 of file AllSiliconTrackerSteppingAction.h
Referenced by UserSteppingAction().
The documentation for this class was generated from the following files:
fun4all_eicdetectors/blob/master/simulation/g4simulation/g4lblvtx/AllSiliconTrackerSteppingAction.h
g4lblvtx/blob/master/source/AllSiliconTrackerSteppingAction.h
fun4all_eicdetectors/blob/master/simulation/g4simulation/g4lblvtx/AllSiliconTrackerSteppingAction.cc
g4lblvtx/blob/master/source/AllSiliconTrackerSteppingAction.cc