EIC Software: EicToyModel/blob/master/scripts/eicroot.C File Reference
eicroot.C File Reference
Functions
eic width (1500) -> AddEtaLine(0.0) ->SetName("eicroot")
eic acceptance (-6.2,-1.0, 1.2, 6.2)
mid offset (5 *etm::cm)
mid add ("TRACKER", 100 *etm::cm)
fwd offset (120 *etm::cm)
fwd add ("MPGD", 30 *etm::cm) -> brick()
bck add ("TRD", 15 *etm::cm) -> brick()
eic mid () -> get("TRACKER") ->stretch(eic->fwd() ->get("MPGD"))
eic vdraw ()
eic write ()
Function Documentation
eic acceptance (-6. 2, -1. 0, 1. 2, 6. 2)
mid add ("TRACKER" , 100 *etm::cm)
fwd add ("MPGD" , 30 *etm::cm) -> brick()
bck add ("TRD" , 15 *etm::cm) -> brick()
eic mid () -> get("TRACKER") ->stretch(eic->fwd() ->get("MPGD"))
mid offset (5 *etm::cm)
fwd offset (120 *etm::cm)
eic vdraw ()
eic width (1500) -> AddEtaLine(0.0) ->SetName("eicroot")
Referenced by Acts::Test::BOOST_AUTO_TEST_CASE(), PHG4FullProjTiltedSpacalDetector::Construct_AzimuthalSeg(), MapsGeoParData::ConstructMimosaCell(), CbmRichUrqmdTest::CreateCanvas(), CbmRichGeoTest::CreateCanvas(), G4GDMLReadStructure::DivisionvolRead(), PHG4GDMLWriteStructure::DivisionvolWrite(), Acts::GaussianGridTrackDensity< mainGridSize, trkGridSize >::estimateSeedWidth(), Acts::GridDensityVertexFinder< mainGridSize, trkGridSize, vfitter_t >::find(), EICG4BwdSteppingAction::FindTowerIndexFromPosition(), Acts::GaussianGridTrackDensity< mainGridSize, trkGridSize >::getMaxZPositionAndWidth(), inputParameters::init(), PHG4BlockCellReco::InitRun(), Acts::detail::Grid< external_spacepoint_t >::localBinsFromLowerLeftEdge(), Acts::GaussianGridTrackDensity< mainGridSize, trkGridSize >::modifyMainGridWithTrackGrid(), erhic::Forester::Plant(), oncsSub_idmvtxv0::print_stuff(), oncsSub_idmvtxv1::print_stuff(), oncsSub_idmvtxv2::print_stuff(), G4GDMLReadStructure::ReplicaRead(), PHG4GDMLWriteStructure::ReplicavolWrite(), KFParticle_particleList::returnPDGMass(), PHG4ParticleGeneratorVectorMeson::set_vertex_size_parameters(), PHG4SimpleEventGenerator::set_vertex_size_parameters(), SetCellKnots(), EtmPolygonGroup::SetLineWidth(), PHHepMCGenHelper::smear(), PHG4SimpleEventGenerator::smearvtx(), Acts::Frustum< value_t, DIM, SIDES >::svg(), QAHistManagerDef::useLogBins(), HelixHough::vote(), HelixHough::vote_pairs(), and HelixHough::vote_z().
eic write ()