EIC Software: PndMultiField Class Reference
PndMultiField Class Reference
#include <EicRoot/blob/master/field/PndMultiField.h>
Public Member Functions
PndMultiField ()
PndMultiField (TString Map, Double_t BeamMom=15.0)
PndMultiField (PndMultiFieldPar *fieldPar)
virtual ~PndMultiField ()
void Init ()
void AddField (FairField *field)
TObjArray * GetFieldList ()
void FillParContainer ()
virtual void Print ()
ClassDef (PndMultiField, 2) void GetFieldValue(const Double_t point[3]
Public Attributes
Double_t * bField
Protected Attributes
TObjArray * fMaps
Int_t fNoOfMaps
std::map< PndRegion
*, FairField * > fFieldMaps
std::map< PndRegion
*, FairField * >::iterator fMapIter
Double_t fBeamMom
Private Member Functions
PndMultiField (const PndMultiField &L)
PndMultiField & operator= (const PndMultiField &)
Detailed Description
Definition at line 23 of file PndMultiField.h.
View newest version in sPHENIX GitHub at line 23 of file PndMultiField.h
Constructor & Destructor Documentation
PndMultiField::PndMultiField ()
Default constructor
Definition at line 36 of file PndMultiField.cxx.
View newest version in sPHENIX GitHub at line 36 of file PndMultiField.cxx
PndMultiField::PndMultiField (TString Map, Double_t BeamMom = 15.0)
Definition at line 43 of file PndMultiField.cxx.
View newest version in sPHENIX GitHub at line 43 of file PndMultiField.cxx
References AddField(), and fBeamMom.
PndMultiField::PndMultiField (PndMultiFieldPar * fieldPar)
Constructor from PndFieldPar
Definition at line 97 of file PndMultiField.cxx.
View newest version in sPHENIX GitHub at line 97 of file PndMultiField.cxx
References PndMultiFieldPar::GetParArray().
PndMultiField::~PndMultiField () virtual
Destructor
Definition at line 107 of file PndMultiField.cxx.
View newest version in sPHENIX GitHub at line 107 of file PndMultiField.cxx
References fMaps.
PndMultiField::PndMultiField (const PndMultiField & L) inline private
Definition at line 60 of file PndMultiField.h.
View newest version in sPHENIX GitHub at line 60 of file PndMultiField.h
Member Function Documentation
void PndMultiField::AddField (FairField * field)
Adding a field to the collection
Definition at line 116 of file PndMultiField.cxx.
View newest version in sPHENIX GitHub at line 116 of file PndMultiField.cxx
References fMaps, and fNoOfMaps.
Referenced by EicRunSim::AddField(), PndFieldCreator::createFairField(), and PndMultiField().
PndMultiField::ClassDef (PndMultiField , 2) const
Get magnetic field. For use of GEANT3
Parameters
point Coordinates [cm]
bField (return) Field components [kG]
void PndMultiField::FillParContainer ()
Definition at line 156 of file PndMultiField.cxx.
View newest version in sPHENIX GitHub at line 156 of file PndMultiField.cxx
References FairRuntimeDb::getContainer(), FairRun::GetRunId(), FairRun::GetRuntimeDb(), FairRun::Instance(), FairParSet::setChanged(), FairParSet::setInputVersion(), and PndMultiFieldPar::SetParameters().
TObjArray* PndMultiField::GetFieldList () inline
Definition at line 46 of file PndMultiField.h.
View newest version in sPHENIX GitHub at line 46 of file PndMultiField.h
References fMaps.
Referenced by PndFieldPar::SetParameters(), and PndMultiFieldPar::SetParameters().
void PndMultiField::Init (void)
Initialisation (read map from file)
Definition at line 126 of file PndMultiField.cxx.
View newest version in sPHENIX GitHub at line 126 of file PndMultiField.cxx
References fFieldMaps, fMaps, fNoOfMaps, PndConstField::GetZmax(), PndFieldMap::GetZmax(), PndConstField::GetZmin(), PndFieldMap::GetZmin(), PndFieldMap::Init(), and n.
Referenced by PndFieldCreator::createFairField().
PndMultiField& PndMultiField::operator= (const PndMultiField &) inline private
Definition at line 61 of file PndMultiField.h.
View newest version in sPHENIX GitHub at line 61 of file PndMultiField.h
void PndMultiField::Print () virtual
Screen output
Definition at line 144 of file PndMultiField.cxx.
View newest version in sPHENIX GitHub at line 144 of file PndMultiField.cxx
References fMaps, fNoOfMaps, and n.
Member Data Documentation
Double_t* PndMultiField::bField
Definition at line 58 of file PndMultiField.h.
View newest version in sPHENIX GitHub at line 58 of file PndMultiField.h
Double_t PndMultiField::fBeamMom protected
Definition at line 69 of file PndMultiField.h.
View newest version in sPHENIX GitHub at line 69 of file PndMultiField.h
Referenced by PndMultiField().
std::map<PndRegion*, FairField* > PndMultiField::fFieldMaps protected
Definition at line 67 of file PndMultiField.h.
View newest version in sPHENIX GitHub at line 67 of file PndMultiField.h
Referenced by Init().
std::map<PndRegion*, FairField* >::iterator PndMultiField::fMapIter protected
Definition at line 68 of file PndMultiField.h.
View newest version in sPHENIX GitHub at line 68 of file PndMultiField.h
TObjArray* PndMultiField::fMaps protected
Definition at line 61 of file PndMultiField.h.
View newest version in sPHENIX GitHub at line 61 of file PndMultiField.h
Referenced by AddField(), GetFieldList(), Init(), Print(), and ~PndMultiField().
Int_t PndMultiField::fNoOfMaps protected
Definition at line 66 of file PndMultiField.h.
View newest version in sPHENIX GitHub at line 66 of file PndMultiField.h
Referenced by AddField(), Init(), and Print().
The documentation for this class was generated from the following files:
EicRoot/blob/master/field/PndMultiField.h
EicRoot/blob/master/field/PndMultiField.cxx