EIC Software: Poacher Class Reference
Poacher Class Reference
#include <EicRoot/blob/master/eic/event/EicEventGenerator.h>
Public Member Functions
Poacher ()
Poacher (const TString &fileName)
~Poacher ()
erhic::VirtualEvent * GetNextEvent ()
std::string EventName () const
Public Member Functions inherited from erhic::Forester
Forester ()
virtual ~Forester ()
Long64_t Plant ()
void SetInputFileName (const std::string &)
void SetOutputFileName (const std::string &)
void SetTreeName (const std::string &="EICTree")
void SetBranchName (const std::string &="event")
std::string GetInputFileName () const
std::string GetOutputFileName () const
std::string GetTreeName () const
std::string GetBranchName () const
void SetMaxNEvents (Long64_t=0)
Long64_t GetMaxNEvents () const
void SetMessageInterval (Long64_t=10000)
void Print (std::ostream &stream) const
void Print (Option_t *="not used") const
void SetBeVerbose (bool=false)
bool BeVerbose () const
const erhic::FileType * GetFileType () const
Private Member Functions
void ResetProMC ()
void ResetEicMC ()
ClassDef (Poacher, 3)
Private Attributes
ProMCBook * mProMCBook
double mMomentumUnits
double mLengthUnits
erhic::ParticleMC * mParticle
EventProMC * mEventProMC
EventEicMC * mEventEicMC
EicMC::Reader * mReaderEicMC
Additional Inherited Members
Protected Member Functions inherited from erhic::Forester
const Status & GetGetStatus () const
bool OpenInput ()
bool SetupOutput ()
void Finish ()
bool AllocateEvent ()
bool FindFirstEvent ()
void PrintStatus () const
bool MustQuit () const
void SetMustQuit (bool quit)
Protected Attributes inherited from erhic::Forester
Bool_t mQuit
Quit status. Set to true once EoF or max events reached.
Bool_t mVerbose
Verbosity flag.
TTree * mTree
VirtualEvent * mEvent
< Output TTree, owned by mRootFile
const erhic::FileType * mFile
< Stores event branch address
TFile * mRootFile
< File type information
Long64_t mMaxNEvents
< Pointer to output ROOT file
Long64_t mInterval
Event interval between printing status messages.
std::shared_ptr< std::istream > mTextFile
std::string mInputName
< Input text file
std::string mOutputName
Name of the output ROOT file.
std::string mTreeName
Name of the output TTree.
std::string mBranchName
Name of the event TBranch.
std::string mLine
Stores the latest text line read from the input file.
Status mStatus
Forester status information.
VirtualEventFactory * mFactory
Detailed Description
Definition at line 87 of file EicEventGenerator.h.
View newest version in sPHENIX GitHub at line 87 of file EicEventGenerator.h
Constructor & Destructor Documentation
Poacher::Poacher () inline
Definition at line 90 of file EicEventGenerator.h.
View newest version in sPHENIX GitHub at line 90 of file EicEventGenerator.h
References ResetEicMC(), and ResetProMC().
Poacher::Poacher (const TString & fileName)
Definition at line 32 of file EicEventGenerator.cxx.
View newest version in sPHENIX GitHub at line 32 of file EicEventGenerator.cxx
References erhic::Forester::FindFirstEvent(), mEventEicMC, mEventProMC, mLengthUnits, mMomentumUnits, mParticle, mProMCBook, mReaderEicMC, erhic::Forester::OpenInput(), ResetEicMC(), ResetProMC(), and erhic::Forester::SetInputFileName().
Poacher::~Poacher () inline
Definition at line 93 of file EicEventGenerator.h.
View newest version in sPHENIX GitHub at line 93 of file EicEventGenerator.h
Member Function Documentation
Poacher::ClassDef (Poacher , 3) private
std::string Poacher::EventName () const
Definition at line 179 of file EicEventGenerator.cxx.
View newest version in sPHENIX GitHub at line 179 of file EicEventGenerator.cxx
References erhic::VirtualEventFactory::EventName(), erhic::Forester::mFactory, mProMCBook, and mReaderEicMC.
Referenced by EicEventGenerator::ReadEvent().
erhic::VirtualEvent * Poacher::GetNextEvent ()
Definition at line 84 of file EicEventGenerator.cxx.
View newest version in sPHENIX GitHub at line 84 of file EicEventGenerator.cxx
References erhic::EventMC::AddLast(), erhic::EventMC::Clear(), erhic::VirtualEventFactory::Create(), mEventEicMC, mEventProMC, erhic::Forester::mFactory, mLengthUnits, mMomentumUnits, mParticle, mProMCBook, mReaderEicMC, particle, erhic::ParticleMCbase::Set4Vector(), erhic::ParticleMCbase::SetChild1Index(), erhic::ParticleMCbase::SetChildNIndex(), erhic::ParticleMCbase::SetId(), erhic::ParticleMCbase::SetParentIndex(), erhic::ParticleMCbase::SetStatus(), and erhic::ParticleMCbase::SetVertex().
Referenced by EicEventGenerator::ReadEvent(), and EicEventGenerator::SkipFewEvents().
void Poacher::ResetEicMC () inline private
Definition at line 115 of file EicEventGenerator.h.
View newest version in sPHENIX GitHub at line 115 of file EicEventGenerator.h
References mEventEicMC, and mReaderEicMC.
Referenced by Poacher().
void Poacher::ResetProMC () inline private
Definition at line 110 of file EicEventGenerator.h.
View newest version in sPHENIX GitHub at line 110 of file EicEventGenerator.h
References mEventProMC, mLengthUnits, mMomentumUnits, and mProMCBook.
Referenced by Poacher().
Member Data Documentation
EventEicMC* Poacher::mEventEicMC private
Definition at line 107 of file EicEventGenerator.h.
View newest version in sPHENIX GitHub at line 107 of file EicEventGenerator.h
Referenced by GetNextEvent(), Poacher(), and ResetEicMC().
EventProMC* Poacher::mEventProMC private
Definition at line 104 of file EicEventGenerator.h.
View newest version in sPHENIX GitHub at line 104 of file EicEventGenerator.h
Referenced by GetNextEvent(), Poacher(), and ResetProMC().
double Poacher::mLengthUnits private
Definition at line 102 of file EicEventGenerator.h.
View newest version in sPHENIX GitHub at line 102 of file EicEventGenerator.h
Referenced by GetNextEvent(), Poacher(), and ResetProMC().
double Poacher::mMomentumUnits private
Definition at line 102 of file EicEventGenerator.h.
View newest version in sPHENIX GitHub at line 102 of file EicEventGenerator.h
Referenced by GetNextEvent(), Poacher(), and ResetProMC().
erhic::ParticleMC* Poacher::mParticle private
Definition at line 103 of file EicEventGenerator.h.
View newest version in sPHENIX GitHub at line 103 of file EicEventGenerator.h
Referenced by GetNextEvent(), and Poacher().
ProMCBook* Poacher::mProMCBook private
Definition at line 101 of file EicEventGenerator.h.
View newest version in sPHENIX GitHub at line 101 of file EicEventGenerator.h
Referenced by EventName(), GetNextEvent(), Poacher(), and ResetProMC().
EicMC::Reader* Poacher::mReaderEicMC private
Definition at line 108 of file EicEventGenerator.h.
View newest version in sPHENIX GitHub at line 108 of file EicEventGenerator.h
Referenced by EventName(), GetNextEvent(), Poacher(), and ResetEicMC().
The documentation for this class was generated from the following files:
EicRoot/blob/master/eic/event/EicEventGenerator.h
EicRoot/blob/master/eic/event/EicEventGenerator.cxx