EIC Software: fun4all_eicmacros/blob/master/common/G4_DIRC.C File Reference
G4_DIRC.C File Reference
#include <GlobalVariables.C>
#include <g4detectors/PHG4CylinderSubsystem.h>
#include <g4detectors/PHG4SectorSubsystem.h>
#include <g4detectors/PHG4ConeSubsystem.h>
#include <g4eicdirc/G4EicDircSubsystem.h>
#include <g4main/PHG4Reco.h>
#include <cmath>
Namespaces
namespace Enable
namespace G4DIRC
namespace G4DIRC::SETTING
Macros
#define MACRO_G4DIRC_C
Functions
void DIRCInit ()
double DIRCSetup (PHG4Reco *g4Reco)
Variables
bool Enable::DIRC = false
bool Enable::DIRC_OVERLAPCHECK = false
double G4DIRC::z_prism = 30
double G4DIRC::z_start = -275+z_prism
double G4DIRC::z_end = 125
double G4DIRC::length = 0.
double G4DIRC::z_shift = 0.
double G4DIRC::outer_skin_radius = 89.25
double G4DIRC::dRad = 5.6
double G4DIRC::dInSkin = 7.54
bool G4DIRC::SETTING::USECEMCGeo = true
bool G4DIRC::SETTING::USEskinSupports = true
bool G4DIRC::SETTING::NEWDIRC = true
Macro Definition Documentation
#define MACRO_G4DIRC_C
Definition at line 2 of file G4_DIRC.C.
View newest version in sPHENIX GitHub at line 2 of file G4_DIRC.C
Function Documentation
void DIRCInit ()
Definition at line 52 of file G4_DIRC.C.
View newest version in sPHENIX GitHub at line 52 of file G4_DIRC.C
References G4DIRC::dInSkin, G4DIRC::dRad, G4DIRC::length, max, BlackHoleGeometry::max_radius, BlackHoleGeometry::max_z, min, BlackHoleGeometry::min_z, G4DIRC::outer_skin_radius, G4DIRC::SETTING::USECEMCGeo, G4DIRC::z_end, G4DIRC::z_prism, G4DIRC::z_shift, and G4DIRC::z_start.
Referenced by Fun4All_G4_simplified_v2_DIRC_barrel_GEM(), and G4Init().
double DIRCSetup (PHG4Reco * g4Reco)
Babar DIRC (Without most of support structure) Ref: I. Adam et al. The DIRC particle identification system for the BaBar experiment. Nucl. Instrum. Meth., A538:281-357, 2005. doi:10.1016/j.nima.2004.08.129.
Definition at line 74 of file G4_DIRC.C.
View newest version in sPHENIX GitHub at line 74 of file G4_DIRC.C
References PHG4Sector::Sector_Geometry::AddLayer(), G4DIRC::dInSkin, Enable::DIRC_OVERLAPCHECK, G4DIRC::dRad, PHG4Sector::Sector_Geometry::FlatEdge(), PHG4SectorSubsystem::get_geometry(), G4DIRC::length, M_PI, G4DIRC::SETTING::NEWDIRC, G4DIRC::outer_skin_radius, Enable::OVERLAPCHECK, PHG4DetectorSubsystem::OverlapCheck(), PHG4Subsystem::OverlapCheck(), G4DIRC_SMALL::radiator_R, PHG4Reco::registerSubsystem(), PHG4ConeSubsystem::set_color(), PHG4DetectorSubsystem::set_double_param(), PHG4Sector::Sector_Geometry::set_material(), PHG4Sector::Sector_Geometry::set_max_polar_angle(), PHG4Sector::Sector_Geometry::set_max_polar_edge(), PHG4Sector::Sector_Geometry::set_min_polar_angle(), PHG4Sector::Sector_Geometry::set_min_polar_edge(), PHG4Sector::Sector_Geometry::set_N_Sector(), PHG4Sector::Sector_Geometry::set_normal_polar_angle(), PHG4Sector::Sector_Geometry::set_normal_start(), PHG4DetectorSubsystem::set_string_param(), PHG4DetectorSubsystem::SetActive(), PHG4ConeSubsystem::SetMaterial(), PHG4ConeSubsystem::SetPlaceZ(), PHG4ConeSubsystem::SetR1(), PHG4ConeSubsystem::SetR2(), PHG4ConeSubsystem::SetZlength(), PHG4DetectorSubsystem::SuperDetector(), PHG4Sector::Sector_Geometry::Unit_cm(), G4DIRC::SETTING::USEskinSupports, Fun4AllBase::Verbosity(), G4DIRC::z_end, G4DIRC::z_prism, G4DIRC::z_shift, and G4DIRC::z_start.
Referenced by Fun4All_G4_simplified_v2_DIRC_barrel_GEM(), and G4Setup().