EIC Software: FairDbException Class Reference
FairDbException Class Reference
#include <EicRoot/blob/master/dbase/dbInterface/FairDbException.h>
Public Member Functions
FairDbException (const char *msg=0, Int_t code=-1, Int_t dbType=-1)
FairDbException (const TSQLServer &server, Int_t dbType=-1)
FairDbException (const TSQLStatement &statement, Int_t dbType=-1)
FairDbException (const FairDbException &that)
virtual ~FairDbException ()
const std::string & GetMessage () const
Int_t GetErrorCode () const
Int_t GetDbType () const
Private Attributes
std::string fMessage
The message associated with the exception.
Int_t fErrorCode
The exception error code.
Int_t fDbType
The type of database that issued the exception.
Detailed Description
Definition at line 17 of file FairDbException.h.
View newest version in sPHENIX GitHub at line 17 of file FairDbException.h
Constructor & Destructor Documentation
FairDbException::FairDbException (const char * msg = 0, Int_t code = -1, Int_t dbType = -1)
FairDbException::FairDbException (const TSQLServer & server, Int_t dbType = -1)
Definition at line 27 of file FairDbException.cxx.
View newest version in sPHENIX GitHub at line 27 of file FairDbException.cxx
FairDbException::FairDbException (const TSQLStatement & statement, Int_t dbType = -1)
Definition at line 38 of file FairDbException.cxx.
View newest version in sPHENIX GitHub at line 38 of file FairDbException.cxx
FairDbException::FairDbException (const FairDbException & that)
Definition at line 50 of file FairDbException.cxx.
View newest version in sPHENIX GitHub at line 50 of file FairDbException.cxx
FairDbException::~FairDbException () virtual
Definition at line 63 of file FairDbException.cxx.
View newest version in sPHENIX GitHub at line 63 of file FairDbException.cxx
Member Function Documentation
Int_t FairDbException::GetDbType () const inline
Definition at line 32 of file FairDbException.h.
View newest version in sPHENIX GitHub at line 32 of file FairDbException.h
References fDbType.
Referenced by operator<<().
Int_t FairDbException::GetErrorCode () const inline
Definition at line 31 of file FairDbException.h.
View newest version in sPHENIX GitHub at line 31 of file FairDbException.h
References fErrorCode.
Referenced by operator<<().
const std::string& FairDbException::GetMessage () const inline
Definition at line 30 of file FairDbException.h.
View newest version in sPHENIX GitHub at line 30 of file FairDbException.h
References fMessage.
Referenced by operator<<().
Member Data Documentation
Int_t FairDbException::fDbType private
The type of database that issued the exception.
Definition at line 48 of file FairDbException.h.
View newest version in sPHENIX GitHub at line 48 of file FairDbException.h
Referenced by GetDbType().
Int_t FairDbException::fErrorCode private
The exception error code.
Definition at line 45 of file FairDbException.h.
View newest version in sPHENIX GitHub at line 45 of file FairDbException.h
Referenced by GetErrorCode().
std::string FairDbException::fMessage private
The message associated with the exception.
Definition at line 42 of file FairDbException.h.
View newest version in sPHENIX GitHub at line 42 of file FairDbException.h
Referenced by GetMessage().
The documentation for this class was generated from the following files:
EicRoot/blob/master/dbase/dbInterface/FairDbException.h
EicRoot/blob/master/dbase/dbInterface/FairDbException.cxx