EIC Software: G4LmonDetector Class Reference
G4LmonDetector Class Reference
#include <Fun4All-lmon/blob/master/source/G4LmonDetector.h>
Public Member Functions
G4LmonDetector (PHG4Subsystem *subsys, PHCompositeNode *Node, const std::string &dnam)
constructor
virtual ~G4LmonDetector ()
destructor
virtual void ConstructMe (G4LogicalVolume *world)
construct
virtual void Print (const std::string &what="ALL") const
void SuperDetector (const std::string &name)
const std::string SuperDetector () const
bool ExecuteSteppingActions (const G4Step *aStep)
void ClearEvent ()
void FinishEvent ()
void SetRootOutput (RootOut *rout)
volume accessors
int IsInDetector (G4VPhysicalVolume *) const
Public Member Functions inherited from PHG4Detector
PHG4Detector ()=delete
constructor
PHG4Detector (PHG4Subsystem *subsys, PHCompositeNode *Node, const std::string &nam)
virtual ~PHG4Detector (void)
destructor
virtual void Construct (G4LogicalVolume *world) final
construct method
virtual void PostConstruction ()
Optional PostConstruction call after all geometry is constructed.
virtual void Verbosity (const int v)
virtual int Verbosity () const
virtual G4UserSteppingAction * GetSteppingAction ()
virtual std::string GetName () const
virtual void OverlapCheck (const bool chk)
virtual bool OverlapCheck () const
virtual int DisplayVolume (G4VSolid *volume, G4LogicalVolume *logvol, G4RotationMatrix *rotm=nullptr)
virtual int DisplayVolume (G4LogicalVolume *checksolid, G4LogicalVolume *logvol, G4RotationMatrix *rotm=nullptr)
virtual PHCompositeNode * topNode ()
virtual PHG4Subsystem * GetMySubsystem ()
Protected Attributes
std::set< G4VPhysicalVolume * > m_PhysicalVolumesSet
std::string m_SuperDetector
std::vector< Cell * > m_CellVector
std::vector< CompCal * > m_CompCalVector
std::vector< ExitWindowV2 * > m_ExitWindowV2Vector
std::vector< OpDet * > m_OpDetVector
RootOut * rootoutput
Additional Inherited Members
Static Public Member Functions inherited from PHG4Detector
static G4Material * GetDetectorMaterial (const std::string &name, const bool quit=true)
static G4Element * GetDetectorElement (const std::string &name, const bool quit=true)
Detailed Description
Definition at line 25 of file G4LmonDetector.h.
View newest version in sPHENIX GitHub at line 25 of file G4LmonDetector.h
Constructor & Destructor Documentation
G4LmonDetector::G4LmonDetector (PHG4Subsystem * subsys, PHCompositeNode * Node, const std::string & dnam)
constructor
Definition at line 32 of file G4LmonDetector.cc.
View newest version in sPHENIX GitHub at line 32 of file G4LmonDetector.cc
virtual G4LmonDetector::~G4LmonDetector () inline virtual
destructor
Definition at line 32 of file G4LmonDetector.h.
View newest version in sPHENIX GitHub at line 32 of file G4LmonDetector.h
Member Function Documentation
void G4LmonDetector::ClearEvent ()
Definition at line 94 of file G4LmonDetector.cc.
View newest version in sPHENIX GitHub at line 94 of file G4LmonDetector.cc
References m_CellVector, m_ExitWindowV2Vector, and m_OpDetVector.
Referenced by G4LmonEventAction::BeginOfEventAction().
void G4LmonDetector::ConstructMe (G4LogicalVolume * world) virtual
construct
Implements PHG4Detector.
Definition at line 50 of file G4LmonDetector.cc.
View newest version in sPHENIX GitHub at line 50 of file G4LmonDetector.cc
References Acts::UnitConstants::cm, ExitWindowV2::CreateOutput(), CompCal::CreateOutput(), RootOut::GetTree(), m_CompCalVector, m_ExitWindowV2Vector, Magnet(), and rootoutput.
bool G4LmonDetector::ExecuteSteppingActions (const G4Step * aStep)
Definition at line 75 of file G4LmonDetector.cc.
View newest version in sPHENIX GitHub at line 75 of file G4LmonDetector.cc
References m_CellVector, m_ExitWindowV2Vector, and m_OpDetVector.
Referenced by G4LmonSteppingAction::UserSteppingAction().
void G4LmonDetector::FinishEvent ()
Definition at line 111 of file G4LmonDetector.cc.
View newest version in sPHENIX GitHub at line 111 of file G4LmonDetector.cc
References m_CompCalVector, m_ExitWindowV2Vector, and m_OpDetVector.
Referenced by G4LmonEventAction::EndOfEventAction().
int G4LmonDetector::IsInDetector (G4VPhysicalVolume * volume) const
Definition at line 39 of file G4LmonDetector.cc.
View newest version in sPHENIX GitHub at line 39 of file G4LmonDetector.cc
References m_PhysicalVolumesSet.
void G4LmonDetector::Print (const std::string & what = "ALL") const virtual
Reimplemented from PHG4Detector.
Definition at line 128 of file G4LmonDetector.cc.
View newest version in sPHENIX GitHub at line 128 of file G4LmonDetector.cc
Referenced by G4LmonSubsystem::Print().
void G4LmonDetector::SetRootOutput (RootOut * rout) inline
Definition at line 50 of file G4LmonDetector.h.
View newest version in sPHENIX GitHub at line 50 of file G4LmonDetector.h
References rootoutput.
Referenced by G4LmonSubsystem::Init().
void G4LmonDetector::SuperDetector (const std::string & name) inline
Definition at line 44 of file G4LmonDetector.h.
View newest version in sPHENIX GitHub at line 44 of file G4LmonDetector.h
References m_SuperDetector, and name.
const std::string G4LmonDetector::SuperDetector () const inline
Definition at line 45 of file G4LmonDetector.h.
View newest version in sPHENIX GitHub at line 45 of file G4LmonDetector.h
References m_SuperDetector.
Member Data Documentation
std::vector<Cell *> G4LmonDetector::m_CellVector protected
Definition at line 56 of file G4LmonDetector.h.
View newest version in sPHENIX GitHub at line 56 of file G4LmonDetector.h
Referenced by ClearEvent(), and ExecuteSteppingActions().
std::vector<CompCal *> G4LmonDetector::m_CompCalVector protected
Definition at line 57 of file G4LmonDetector.h.
View newest version in sPHENIX GitHub at line 57 of file G4LmonDetector.h
Referenced by ConstructMe(), and FinishEvent().
std::vector<ExitWindowV2 *> G4LmonDetector::m_ExitWindowV2Vector protected
Definition at line 58 of file G4LmonDetector.h.
View newest version in sPHENIX GitHub at line 58 of file G4LmonDetector.h
Referenced by ClearEvent(), ConstructMe(), ExecuteSteppingActions(), and FinishEvent().
std::vector<OpDet *> G4LmonDetector::m_OpDetVector protected
Definition at line 59 of file G4LmonDetector.h.
View newest version in sPHENIX GitHub at line 59 of file G4LmonDetector.h
Referenced by ClearEvent(), ExecuteSteppingActions(), and FinishEvent().
std::set<G4VPhysicalVolume *> G4LmonDetector::m_PhysicalVolumesSet protected
Definition at line 53 of file G4LmonDetector.h.
View newest version in sPHENIX GitHub at line 53 of file G4LmonDetector.h
Referenced by IsInDetector().
std::string G4LmonDetector::m_SuperDetector protected
Definition at line 55 of file G4LmonDetector.h.
View newest version in sPHENIX GitHub at line 55 of file G4LmonDetector.h
Referenced by SuperDetector().
RootOut* G4LmonDetector::rootoutput protected
Definition at line 60 of file G4LmonDetector.h.
View newest version in sPHENIX GitHub at line 60 of file G4LmonDetector.h
Referenced by ConstructMe(), and SetRootOutput().
The documentation for this class was generated from the following files:
Fun4All-lmon/blob/master/source/G4LmonDetector.h
Fun4All-lmon/blob/master/source/G4LmonDetector.cc