EIC Software: FW::ParticleSelector::Config Struct Reference
FW::ParticleSelector::Config Struct Reference
#include <fun4all_acts/blob/master/Examples/Algorithms/Generators/ACTFW/Generators/ParticleSelector.hpp>
Public Attributes
std::string inputEvent
The input event collection.
std::string outputEvent
The output event collection.
double rhoMin = 0
double rhoMax = std::numeric_limits<double>::infinity()
double absZMin = 0
double absZMax = std::numeric_limits<double>::infinity()
double phiMin = -std::numeric_limits<double>::infinity()
double phiMax = std::numeric_limits<double>::infinity()
double etaMin = -std::numeric_limits<double>::infinity()
double etaMax = std::numeric_limits<double>::infinity()
double absEtaMin = 0
double absEtaMax = std::numeric_limits<double>::infinity()
double ptMin = 0.0
double ptMax = std::numeric_limits<double>::infinity()
bool removeCharged = false
Remove charged particles.
bool removeNeutral = false
Remove neutral particles.
Detailed Description
Definition at line 25 of file ParticleSelector.hpp.
View newest version in sPHENIX GitHub at line 25 of file ParticleSelector.hpp
Member Data Documentation
double FW::ParticleSelector::Config::absEtaMax = std::numeric_limits<double>::infinity()
Definition at line 42 of file ParticleSelector.hpp.
View newest version in sPHENIX GitHub at line 42 of file ParticleSelector.hpp
Referenced by main(), and FW::ParticleSelector::ParticleSelector().
double FW::ParticleSelector::Config::absEtaMin = 0
Definition at line 41 of file ParticleSelector.hpp.
View newest version in sPHENIX GitHub at line 41 of file ParticleSelector.hpp
Referenced by FW::ParticleSelector::ParticleSelector().
double FW::ParticleSelector::Config::absZMax = std::numeric_limits<double>::infinity()
Definition at line 35 of file ParticleSelector.hpp.
View newest version in sPHENIX GitHub at line 35 of file ParticleSelector.hpp
Referenced by FW::ParticleSelector::ParticleSelector().
double FW::ParticleSelector::Config::absZMin = 0
Definition at line 34 of file ParticleSelector.hpp.
View newest version in sPHENIX GitHub at line 34 of file ParticleSelector.hpp
Referenced by FW::ParticleSelector::ParticleSelector().
double FW::ParticleSelector::Config::etaMax = std::numeric_limits<double>::infinity()
Definition at line 40 of file ParticleSelector.hpp.
View newest version in sPHENIX GitHub at line 40 of file ParticleSelector.hpp
Referenced by FW::ParticleSelector::ParticleSelector().
double FW::ParticleSelector::Config::etaMin = -std::numeric_limits<double>::infinity()
Definition at line 39 of file ParticleSelector.hpp.
View newest version in sPHENIX GitHub at line 39 of file ParticleSelector.hpp
Referenced by FW::ParticleSelector::ParticleSelector().
std::string FW::ParticleSelector::Config::inputEvent
The input event collection.
Definition at line 27 of file ParticleSelector.hpp.
View newest version in sPHENIX GitHub at line 27 of file ParticleSelector.hpp
Referenced by main(), and FW::ParticleSelector::ParticleSelector().
std::string FW::ParticleSelector::Config::outputEvent
The output event collection.
Definition at line 29 of file ParticleSelector.hpp.
View newest version in sPHENIX GitHub at line 29 of file ParticleSelector.hpp
Referenced by main(), and FW::ParticleSelector::ParticleSelector().
double FW::ParticleSelector::Config::phiMax = std::numeric_limits<double>::infinity()
Definition at line 38 of file ParticleSelector.hpp.
View newest version in sPHENIX GitHub at line 38 of file ParticleSelector.hpp
Referenced by FW::ParticleSelector::ParticleSelector().
double FW::ParticleSelector::Config::phiMin = -std::numeric_limits<double>::infinity()
Definition at line 37 of file ParticleSelector.hpp.
View newest version in sPHENIX GitHub at line 37 of file ParticleSelector.hpp
Referenced by FW::ParticleSelector::ParticleSelector().
double FW::ParticleSelector::Config::ptMax = std::numeric_limits<double>::infinity()
Definition at line 45 of file ParticleSelector.hpp.
View newest version in sPHENIX GitHub at line 45 of file ParticleSelector.hpp
Referenced by FW::ParticleSelector::ParticleSelector().
double FW::ParticleSelector::Config::ptMin = 0.0
Definition at line 44 of file ParticleSelector.hpp.
View newest version in sPHENIX GitHub at line 44 of file ParticleSelector.hpp
Referenced by main(), and FW::ParticleSelector::ParticleSelector().
bool FW::ParticleSelector::Config::removeCharged = false
Remove charged particles.
Definition at line 47 of file ParticleSelector.hpp.
View newest version in sPHENIX GitHub at line 47 of file ParticleSelector.hpp
Referenced by FW::ParticleSelector::ParticleSelector().
bool FW::ParticleSelector::Config::removeNeutral = false
Remove neutral particles.
Definition at line 49 of file ParticleSelector.hpp.
View newest version in sPHENIX GitHub at line 49 of file ParticleSelector.hpp
Referenced by main(), and FW::ParticleSelector::ParticleSelector().
double FW::ParticleSelector::Config::rhoMax = std::numeric_limits<double>::infinity()
Definition at line 32 of file ParticleSelector.hpp.
View newest version in sPHENIX GitHub at line 32 of file ParticleSelector.hpp
Referenced by main(), and FW::ParticleSelector::ParticleSelector().
double FW::ParticleSelector::Config::rhoMin = 0
Definition at line 31 of file ParticleSelector.hpp.
View newest version in sPHENIX GitHub at line 31 of file ParticleSelector.hpp
Referenced by FW::ParticleSelector::ParticleSelector().
The documentation for this struct was generated from the following file:
fun4all_acts/blob/master/Examples/Algorithms/Generators/ACTFW/Generators/ParticleSelector.hpp