EIC Software: PndSensorNamePar Class Reference
PndSensorNamePar Class Reference
Unique match between SensorID and path in TGeoManager.
#include <EicRoot/blob/master/PndTools/generalTools/PndSensorNamePar.h>
Public Member Functions
PndSensorNamePar (const char *name="PndSensorNamePar", const char *title="Match between GeoManager path and SensorId", const char *context="TestDefaultContext")
~PndSensorNamePar (void)
void clear (void)
void putParams (FairParamList *list)
Bool_t getParams (FairParamList *list)
void Print ()
Int_t AddSensorName (TObjString *name)
Int_t SensorInList (TObjString *name)
void FillMap ()
TString GetSensorName (Int_t index)
TObjArray * GetSensorNames () const
PndSensorNamePar (const PndSensorNamePar &L)
PndSensorNamePar & operator= (const PndSensorNamePar &L)
Public Member Functions inherited from FairParGenericSet
FairParGenericSet (const char *name, const char *title, const char *context)
virtual ~FairParGenericSet ()
virtual void printParams ()
Bool_t init (FairParIo *inp)
Int_t write (FairParIo *output)
Public Member Functions inherited from FairParSet
FairParSet (const char *name="", const char *title="", const char *context="")
virtual ~FairParSet ()
virtual Bool_t init ()
virtual Int_t write ()
virtual void print ()
const char * getDetectorName ()
void resetInputVersions ()
void setInputVersion (Int_t v=-1, Int_t i=0)
Int_t getInputVersion (Int_t i)
void setStatic (Bool_t flag=kTRUE)
Bool_t isStatic ()
void setChanged (Bool_t flag=kTRUE)
Bool_t hasChanged ()
const char * getParamContext () const
void setAuthor (const char *s)
const char * getAuthor () const
void setDescription (const char *s)
const char * getDescription () const
void copyComment (FairParSet &r)
Private Member Functions
ClassDef (PndSensorNamePar, 1)
Private Attributes
TObjArray * fSensorNames
std::map< TString, Int_t > fMapOfSensorNames
std::map< Int_t, TString > fMapOfSensorIndizes
Additional Inherited Members
Protected Member Functions inherited from FairParGenericSet
FairParGenericSet ()
Protected Attributes inherited from FairParSet
TString detName
Int_t versions [3]
name of the detector the container belongs to
Bool_t status
versions of container in the 2 possible inputs
Bool_t changed
static flag
TString paramContext
flag is kTRUE if parameters have changed
TString author
TString description
FairLogger * fLogger
Detailed Description
Unique match between SensorID and path in TGeoManager.
Definition at line 19 of file PndSensorNamePar.h.
View newest version in sPHENIX GitHub at line 19 of file PndSensorNamePar.h
Constructor & Destructor Documentation
PndSensorNamePar::PndSensorNamePar (const char * name = "PndSensorNamePar", const char * title = "Match between GeoManager path and SensorId", const char * context = "TestDefaultContext")
Definition at line 4 of file PndSensorNamePar.cxx.
View newest version in sPHENIX GitHub at line 4 of file PndSensorNamePar.cxx
References clear(), and fSensorNames.
PndSensorNamePar::~PndSensorNamePar (void) inline
Definition at line 25 of file PndSensorNamePar.h.
View newest version in sPHENIX GitHub at line 25 of file PndSensorNamePar.h
References fSensorNames.
PndSensorNamePar::PndSensorNamePar (const PndSensorNamePar & L)
Definition at line 13 of file PndSensorNamePar.cxx.
View newest version in sPHENIX GitHub at line 13 of file PndSensorNamePar.cxx
References fSensorNames, and GetSensorNames().
Member Function Documentation
Int_t PndSensorNamePar::AddSensorName (TObjString * name)
Definition at line 38 of file PndSensorNamePar.cxx.
View newest version in sPHENIX GitHub at line 38 of file PndSensorNamePar.cxx
References fMapOfSensorIndizes, fMapOfSensorNames, fSensorNames, FairRun::GetRunId(), FairRun::Instance(), SensorInList(), FairParSet::setChanged(), and FairParSet::setInputVersion().
Referenced by PndGeoHandling::DiveDownToFillSensNamePar().
PndSensorNamePar::ClassDef (PndSensorNamePar , 1) private
void PndSensorNamePar::clear (void) inline virtual
Reimplemented from FairParSet.
Definition at line 28 of file PndSensorNamePar.h.
View newest version in sPHENIX GitHub at line 28 of file PndSensorNamePar.h
Referenced by PndSensorNamePar().
void PndSensorNamePar::FillMap () inline
Definition at line 51 of file PndSensorNamePar.h.
View newest version in sPHENIX GitHub at line 51 of file PndSensorNamePar.h
References fMapOfSensorIndizes, fMapOfSensorNames, and fSensorNames.
Referenced by getParams(), and PndGeoHandling::Init().
Bool_t PndSensorNamePar::getParams (FairParamList * list) virtual
Implements FairParGenericSet.
Definition at line 30 of file PndSensorNamePar.cxx.
View newest version in sPHENIX GitHub at line 30 of file PndSensorNamePar.cxx
References FillMap(), FairParamList::fillObject(), and fSensorNames.
TString PndSensorNamePar::GetSensorName (Int_t index) inline
Definition at line 59 of file PndSensorNamePar.h.
View newest version in sPHENIX GitHub at line 59 of file PndSensorNamePar.h
References fMapOfSensorIndizes.
Referenced by PndGeoHandling::GetPath().
TObjArray* PndSensorNamePar::GetSensorNames () const inline
Definition at line 80 of file PndSensorNamePar.h.
View newest version in sPHENIX GitHub at line 80 of file PndSensorNamePar.h
References fSensorNames.
Referenced by PndGeoHandling::GetSensorNames(), operator=(), and PndSensorNamePar().
PndSensorNamePar & PndSensorNamePar::operator= (const PndSensorNamePar & L)
Definition at line 18 of file PndSensorNamePar.cxx.
View newest version in sPHENIX GitHub at line 18 of file PndSensorNamePar.cxx
References fSensorNames, and GetSensorNames().
void PndSensorNamePar::Print (void)
Definition at line 56 of file PndSensorNamePar.cxx.
View newest version in sPHENIX GitHub at line 56 of file PndSensorNamePar.cxx
References fMapOfSensorIndizes, and fSensorNames.
Referenced by PndGeoHandling::GetSensorNamePar(), and PndGeoHandling::PrintSensorNames().
void PndSensorNamePar::putParams (FairParamList * list) virtual
Implements FairParGenericSet.
Definition at line 24 of file PndSensorNamePar.cxx.
View newest version in sPHENIX GitHub at line 24 of file PndSensorNamePar.cxx
References FairParamList::addObject(), and fSensorNames.
Int_t PndSensorNamePar::SensorInList (TObjString * name) inline
Definition at line 36 of file PndSensorNamePar.h.
View newest version in sPHENIX GitHub at line 36 of file PndSensorNamePar.h
References fMapOfSensorNames.
Referenced by AddSensorName(), and PndGeoHandling::GetShortID().
Member Data Documentation
std::map<Int_t, TString> PndSensorNamePar::fMapOfSensorIndizes private
Definition at line 88 of file PndSensorNamePar.h.
View newest version in sPHENIX GitHub at line 88 of file PndSensorNamePar.h
Referenced by AddSensorName(), FillMap(), GetSensorName(), and Print().
std::map<TString, Int_t> PndSensorNamePar::fMapOfSensorNames private
Definition at line 87 of file PndSensorNamePar.h.
View newest version in sPHENIX GitHub at line 87 of file PndSensorNamePar.h
Referenced by AddSensorName(), FillMap(), and SensorInList().
TObjArray* PndSensorNamePar::fSensorNames private
Definition at line 86 of file PndSensorNamePar.h.
View newest version in sPHENIX GitHub at line 86 of file PndSensorNamePar.h
Referenced by AddSensorName(), FillMap(), getParams(), GetSensorNames(), operator=(), PndSensorNamePar(), Print(), putParams(), and ~PndSensorNamePar().
The documentation for this class was generated from the following files:
EicRoot/blob/master/PndTools/generalTools/PndSensorNamePar.h
EicRoot/blob/master/PndTools/generalTools/PndSensorNamePar.cxx