EIC Software: FairGeoVector Class Reference
FairGeoVector Class Reference
#include <EicRoot/blob/master/geobase/FairGeoVector.h>
Public Member Functions
FairGeoVector (Double_t dx=0, Double_t dy=0, Double_t dz=0)
FairGeoVector (const FairGeoVector &v)
~FairGeoVector ()
Double_t & X ()
Double_t & Y ()
Double_t & Z ()
Double_t getX () const
Double_t getY () const
Double_t getZ () const
Double_t getValues (Int_t i)
void setXYZ (const Double_t xx, const Double_t yy, const Double_t zz)
void setX (const Double_t a)
void setY (const Double_t a)
void setZ (const Double_t a)
void setVector (const Double_t *a)
void setVector (const Float_t *a)
Double_t operator() (const Int_t i) const
FairGeoVector operator- () const
FairGeoVector & operator= (const FairGeoVector &v)
Bool_t operator== (const FairGeoVector &v) const
Bool_t operator!= (const FairGeoVector &v) const
Bool_t operator< (const Double_t a)
check with ilse
Bool_t operator<= (const Double_t a)
Bool_t operator> (const Double_t a)
Bool_t operator>= (const Double_t a)
FairGeoVector & operator+= (const Double_t a)
FairGeoVector & operator-= (const Double_t a)
FairGeoVector & operator*= (const Double_t a)
FairGeoVector & operator/= (const Double_t a)
FairGeoVector & operator+= (const FairGeoVector &v)
FairGeoVector & operator-= (const FairGeoVector &v)
FairGeoVector operator+ (const FairGeoVector &v) const
FairGeoVector operator- (const FairGeoVector &v) const
FairGeoVector & abs ()
Double_t scalarProduct (const FairGeoVector &v) const
FairGeoVector vectorProduct (const FairGeoVector &v) const
Double_t length () const
void clear ()
void print () const
void round (Int_t n)
Protected Member Functions
void round (Double_t d, Int_t n)
Protected Attributes
Double_t x
Double_t y
Double_t z
Friends
std::ostream & operator<< (std::ostream &put, const FairGeoVector &v)
std::istream & operator>> (std::istream &get, FairGeoVector &v)
Detailed Description
Definition at line 10 of file FairGeoVector.h.
View newest version in sPHENIX GitHub at line 10 of file FairGeoVector.h
Constructor & Destructor Documentation
FairGeoVector::FairGeoVector (Double_t dx = 0, Double_t dy = 0, Double_t dz = 0) inline
Definition at line 18 of file FairGeoVector.h.
View newest version in sPHENIX GitHub at line 18 of file FairGeoVector.h
FairGeoVector::FairGeoVector (const FairGeoVector & v) inline
Definition at line 20 of file FairGeoVector.h.
View newest version in sPHENIX GitHub at line 20 of file FairGeoVector.h
FairGeoVector::~FairGeoVector () inline
Definition at line 22 of file FairGeoVector.h.
View newest version in sPHENIX GitHub at line 22 of file FairGeoVector.h
Member Function Documentation
FairGeoVector & FairGeoVector::abs () inline
Definition at line 214 of file FairGeoVector.h.
View newest version in sPHENIX GitHub at line 214 of file FairGeoVector.h
References x, y, and z.
Referenced by FairGeoBrik::calcVoluParam().
void FairGeoVector::clear (void) inline
Definition at line 71 of file FairGeoVector.h.
View newest version in sPHENIX GitHub at line 71 of file FairGeoVector.h
References x, y, and z.
Referenced by FairGeoTransform::clear().
Double_t FairGeoVector::getValues (Int_t i) inline
Definition at line 30 of file FairGeoVector.h.
View newest version in sPHENIX GitHub at line 30 of file FairGeoVector.h
References x, y, and z.
Referenced by FairGeoVolume::getVolParameter().
Double_t FairGeoVector::getX () const inline
Definition at line 26 of file FairGeoVector.h.
View newest version in sPHENIX GitHub at line 26 of file FairGeoVector.h
References x.
Referenced by FairGeoRootBuilder::createNode(), operator!=(), FairGeoMatrix::operator*(), operator+=(), operator-=(), operator=(), operator==(), scalarProduct(), and vectorProduct().
Double_t FairGeoVector::getY () const inline
Definition at line 27 of file FairGeoVector.h.
View newest version in sPHENIX GitHub at line 27 of file FairGeoVector.h
References y.
Referenced by FairGeoRootBuilder::createNode(), operator!=(), FairGeoMatrix::operator*(), operator+=(), operator-=(), operator=(), operator==(), scalarProduct(), and vectorProduct().
Double_t FairGeoVector::getZ () const inline
Definition at line 28 of file FairGeoVector.h.
View newest version in sPHENIX GitHub at line 28 of file FairGeoVector.h
References z.
Referenced by FairGeoRootBuilder::createNode(), operator!=(), FairGeoMatrix::operator*(), operator+=(), operator-=(), operator=(), operator==(), scalarProduct(), and vectorProduct().
Double_t FairGeoVector::length () const inline
Definition at line 70 of file FairGeoVector.h.
View newest version in sPHENIX GitHub at line 70 of file FairGeoVector.h
References x, y, and z.
Bool_t FairGeoVector::operator!= (const FairGeoVector & v) const inline
Definition at line 129 of file FairGeoVector.h.
View newest version in sPHENIX GitHub at line 129 of file FairGeoVector.h
References getX(), getY(), getZ(), x, y, and z.
Double_t FairGeoVector::operator() (const Int_t i) const inline
Definition at line 95 of file FairGeoVector.h.
View newest version in sPHENIX GitHub at line 95 of file FairGeoVector.h
References x, y, and z.
FairGeoVector & FairGeoVector::operator*= (const Double_t a) inline
Definition at line 170 of file FairGeoVector.h.
View newest version in sPHENIX GitHub at line 170 of file FairGeoVector.h
References x, y, and z.
FairGeoVector FairGeoVector::operator+ (const FairGeoVector & v) const inline
Definition at line 202 of file FairGeoVector.h.
View newest version in sPHENIX GitHub at line 202 of file FairGeoVector.h
References p, and v.
FairGeoVector & FairGeoVector::operator+= (const Double_t a) inline
Definition at line 154 of file FairGeoVector.h.
View newest version in sPHENIX GitHub at line 154 of file FairGeoVector.h
References x, y, and z.
FairGeoVector & FairGeoVector::operator+= (const FairGeoVector & v) inline
Definition at line 186 of file FairGeoVector.h.
View newest version in sPHENIX GitHub at line 186 of file FairGeoVector.h
References getX(), getY(), getZ(), x, y, and z.
FairGeoVector FairGeoVector::operator- () const inline
Definition at line 110 of file FairGeoVector.h.
View newest version in sPHENIX GitHub at line 110 of file FairGeoVector.h
References p, x, y, and z.
FairGeoVector FairGeoVector::operator- (const FairGeoVector & v) const inline
Definition at line 208 of file FairGeoVector.h.
View newest version in sPHENIX GitHub at line 208 of file FairGeoVector.h
References p, and v.
FairGeoVector & FairGeoVector::operator-= (const Double_t a) inline
Definition at line 162 of file FairGeoVector.h.
View newest version in sPHENIX GitHub at line 162 of file FairGeoVector.h
References x, y, and z.
FairGeoVector & FairGeoVector::operator-= (const FairGeoVector & v) inline
Definition at line 194 of file FairGeoVector.h.
View newest version in sPHENIX GitHub at line 194 of file FairGeoVector.h
References getX(), getY(), getZ(), x, y, and z.
FairGeoVector & FairGeoVector::operator/= (const Double_t a) inline
Definition at line 178 of file FairGeoVector.h.
View newest version in sPHENIX GitHub at line 178 of file FairGeoVector.h
References x, y, and z.
Bool_t FairGeoVector::operator< (const Double_t a) inline
check with ilse
Definition at line 134 of file FairGeoVector.h.
View newest version in sPHENIX GitHub at line 134 of file FairGeoVector.h
References x, y, and z.
Bool_t FairGeoVector::operator<= (const Double_t a) inline
Definition at line 139 of file FairGeoVector.h.
View newest version in sPHENIX GitHub at line 139 of file FairGeoVector.h
References x, y, and z.
FairGeoVector & FairGeoVector::operator= (const FairGeoVector & v) inline
Definition at line 116 of file FairGeoVector.h.
View newest version in sPHENIX GitHub at line 116 of file FairGeoVector.h
References getX(), getY(), getZ(), x, y, and z.
Bool_t FairGeoVector::operator== (const FairGeoVector & v) const inline
Definition at line 124 of file FairGeoVector.h.
View newest version in sPHENIX GitHub at line 124 of file FairGeoVector.h
References getX(), getY(), getZ(), x, y, and z.
Bool_t FairGeoVector::operator> (const Double_t a) inline
Definition at line 144 of file FairGeoVector.h.
View newest version in sPHENIX GitHub at line 144 of file FairGeoVector.h
References x, y, and z.
Bool_t FairGeoVector::operator>= (const Double_t a) inline
Definition at line 149 of file FairGeoVector.h.
View newest version in sPHENIX GitHub at line 149 of file FairGeoVector.h
References x, y, and z.
void FairGeoVector::print () const inline
Definition at line 72 of file FairGeoVector.h.
View newest version in sPHENIX GitHub at line 72 of file FairGeoVector.h
References printf(), x, y, and z.
Referenced by FairGeoTransform::print(), and FairGeoNode::print().
void FairGeoVector::round (Double_t d, Int_t n) inline protected
Definition at line 234 of file FairGeoVector.h.
View newest version in sPHENIX GitHub at line 234 of file FairGeoVector.h
Referenced by round().
void FairGeoVector::round (Int_t n) inline
Definition at line 241 of file FairGeoVector.h.
View newest version in sPHENIX GitHub at line 241 of file FairGeoVector.h
References round(), x, y, and z.
Double_t FairGeoVector::scalarProduct (const FairGeoVector & v) const inline
Definition at line 222 of file FairGeoVector.h.
View newest version in sPHENIX GitHub at line 222 of file FairGeoVector.h
References getX(), getY(), getZ(), x, y, and z.
void FairGeoVector::setVector (const Double_t * a) inline
Definition at line 81 of file FairGeoVector.h.
View newest version in sPHENIX GitHub at line 81 of file FairGeoVector.h
References x, y, and z.
Referenced by operator>>(), and FairGeoTransform::setTransVector().
void FairGeoVector::setVector (const Float_t * a) inline
Definition at line 88 of file FairGeoVector.h.
View newest version in sPHENIX GitHub at line 88 of file FairGeoVector.h
References x, y, and z.
void FairGeoVector::setX (const Double_t a) inline
Definition at line 45 of file FairGeoVector.h.
View newest version in sPHENIX GitHub at line 45 of file FairGeoVector.h
References x.
Referenced by FairGeoTrap::calcVoluParam(), FairGeoMatrix::operator*(), and FairGeoVolume::setPoint().
void FairGeoVector::setXYZ (const Double_t xx, const Double_t yy, const Double_t zz) inline
Definition at line 40 of file FairGeoVector.h.
View newest version in sPHENIX GitHub at line 40 of file FairGeoVector.h
References x, y, and z.
void FairGeoVector::setY (const Double_t a) inline
Definition at line 46 of file FairGeoVector.h.
View newest version in sPHENIX GitHub at line 46 of file FairGeoVector.h
References y.
Referenced by FairGeoTrap::calcVoluParam(), FairGeoMatrix::operator*(), and FairGeoVolume::setPoint().
void FairGeoVector::setZ (const Double_t a) inline
Definition at line 47 of file FairGeoVector.h.
View newest version in sPHENIX GitHub at line 47 of file FairGeoVector.h
References z.
Referenced by FairGeoMatrix::operator*(), and FairGeoVolume::setPoint().
FairGeoVector FairGeoVector::vectorProduct (const FairGeoVector & v) const inline
Definition at line 227 of file FairGeoVector.h.
View newest version in sPHENIX GitHub at line 227 of file FairGeoVector.h
References getX(), getY(), getZ(), p, x, y, and z.
Double_t& FairGeoVector::X () inline
Definition at line 23 of file FairGeoVector.h.
View newest version in sPHENIX GitHub at line 23 of file FairGeoVector.h
References x.
Referenced by CbmRichHitProducer::Init(), and CbmRichProjectionProducer::Init().
Double_t& FairGeoVector::Y () inline
Definition at line 24 of file FairGeoVector.h.
View newest version in sPHENIX GitHub at line 24 of file FairGeoVector.h
References y.
Referenced by CbmRichHitProducer::Init(), and CbmRichProjectionProducer::Init().
Double_t& FairGeoVector::Z () inline
Definition at line 25 of file FairGeoVector.h.
View newest version in sPHENIX GitHub at line 25 of file FairGeoVector.h
References z.
Referenced by CbmRichHitProducer::Init(), CbmRichProjectionProducer::Init(), CbmRichTestHits::Init(), CbmRichTestSim::Init(), and CbmRichGeoTest::Init().
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & put, const FairGeoVector & v) friend
Definition at line 249 of file FairGeoVector.h.
View newest version in sPHENIX GitHub at line 249 of file FairGeoVector.h
std::istream& operator>> (std::istream & get, FairGeoVector & v) friend
Definition at line 254 of file FairGeoVector.h.
View newest version in sPHENIX GitHub at line 254 of file FairGeoVector.h
Member Data Documentation
Double_t FairGeoVector::x protected
Definition at line 13 of file FairGeoVector.h.
View newest version in sPHENIX GitHub at line 13 of file FairGeoVector.h
Referenced by abs(), eicpy.qaplots.LogAxis::apply(), clear(), getValues(), getX(), length(), operator!=(), operator()(), operator*=(), operator+=(), operator-(), operator-=(), operator/=(), operator<(), operator<=(), operator=(), operator==(), operator>(), operator>=(), print(), eicpy.qaplots.LogAxis::rebin(), round(), scalarProduct(), setVector(), setX(), setXYZ(), vectorProduct(), and X().
Double_t FairGeoVector::y protected
Definition at line 14 of file FairGeoVector.h.
View newest version in sPHENIX GitHub at line 14 of file FairGeoVector.h
Referenced by abs(), eicpy.qaplots.LogAxis::apply(), clear(), getValues(), getY(), length(), operator!=(), operator()(), operator*=(), operator+=(), operator-(), operator-=(), operator/=(), operator<(), operator<=(), operator=(), operator==(), operator>(), operator>=(), print(), eicpy.qaplots.LogAxis::rebin(), round(), scalarProduct(), setVector(), setXYZ(), setY(), vectorProduct(), and Y().
Double_t FairGeoVector::z protected
Definition at line 15 of file FairGeoVector.h.
View newest version in sPHENIX GitHub at line 15 of file FairGeoVector.h
Referenced by abs(), eicpy.qaplots.LogAxis::apply(), clear(), getValues(), getZ(), length(), operator!=(), operator()(), operator*=(), operator+=(), operator-(), operator-=(), operator/=(), operator<(), operator<=(), operator=(), operator==(), operator>(), operator>=(), print(), eicpy.qaplots.LogAxis::rebin(), round(), scalarProduct(), setVector(), setXYZ(), setZ(), vectorProduct(), and Z().
The documentation for this class was generated from the following file:
EicRoot/blob/master/geobase/FairGeoVector.h