EIC Software: EicTpcDigiHitProducer Class Reference
EicTpcDigiHitProducer Class Reference
#include <EicRoot/blob/master/eic/detectors/tpc/EicTpcDigiHitProducer.h>
Public Member Functions
EicTpcDigiHitProducer ()
~EicTpcDigiHitProducer ()
int HandleHit (const EicMoCaPoint *point)
int exportTpcDigiParameters (const char *fileName)
int importTpcDigiParameters (const char *fileName)
void setTransverseDispersion (Double_t tDispersion)
void setLongitudinalDispersion (Double_t lDispersion)
void setLongitudinalIntrinsicResolution (Double_t lResolution)
void setTransverseIntrinsicResolution (Double_t tResolution)
void setRadialIntrinsicResolution (Double_t tResolution)
void setGemVerticalPadSize (Double_t pitch)
void Print ()
Public Member Functions inherited from EicTrackingDigiHitProducer
EicTrackingDigiHitProducer ()
EicTrackingDigiHitProducer (const char *name, SmearingModel smearingModel=EicDigiHitProducer::Smear)
~EicTrackingDigiHitProducer ()
InitStatus ExtraInit ()
void DefineKfNodeTemplate1D (double angle, double sigmaOrPitch)
void DefineKfNodeTemplateX (double sigmaOrPitch)
void DefineKfNodeTemplateY (double sigmaOrPitch)
void DefineKfNodeTemplateR (double sigmaOrPitch)
void DefineKfNodeTemplateA (double sigmaOrPitch)
void DefineKfNodeTemplateXY (double sigmaOrPitchX, double sigmaOrPitchY)
void DefineKfNodeTemplateTZ (double sigmaOrPitchX, double sigmaOrPitchY)
EicKfNodeTemplateCylindrical2D * DefineKfNodeTemplateRA (double sigmaOrPitchR, double sigmaOrPitchA)
void DefineKfNodeTemplateOrth3D (double sigmaX, double sigmaY, double sigmaZ)
int HandleHit (const EicMoCaPoint *point)
Public Member Functions inherited from EicDigiHitProducer
EicDigiHitProducer ()
EicDigiHitProducer (const char *name)
~EicDigiHitProducer ()
void ResetVars ()
InitStatus Init ()
virtual int PreExec ()
virtual void Exec (Option_t *opt)
virtual int PostExec ()
void SetPersistence (Bool_t persistence)
void DeclareDigiSensitiveVolume (const char *name, Double_t Kb=0.0)
void DeclareDigiSensitiveVolumePrefix (const char *name, Double_t Kb=0.0)
Public Member Functions inherited from FairTask
FairTask ()
FairTask (const char *name, Int_t iVerbose=1)
virtual ~FairTask ()
void InitTask ()
void ReInitTask ()
void SetParTask ()
virtual void FinishTask ()
virtual void FinishEvent ()
void SetVerbose (Int_t iVerbose)
void SetInputPersistance (Bool_t val)
void CheckInputPersistance (TString branchName)
Private Member Functions
EicDigiParData * getEicDigiParDataPtr ()
ClassDef (EicTpcDigiHitProducer, 1)
Private Attributes
TpcDigiParData * digi
Additional Inherited Members
Public Types inherited from EicDigiHitProducer
enum SmearingModel { NoAction, Smear, Quantize, Calculate }
digitization model identifiers
Public Attributes inherited from EicTrackingDigiHitProducer
std::vector< EicKfNodeTemplate * > mKfNodeTemplates
Protected Member Functions inherited from EicTrackingDigiHitProducer
void AssignDigiHitClassName (const char *name)
Protected Attributes inherited from EicDigiHitProducer
EicDetName * mDetName
TClonesArray * mDigiHitArray
EicGeoParData * mGptr
EicNamePatternHub< double > mSensitiveVolumes
Bool_t mPersistence
Detailed Description
Definition at line 42 of file EicTpcDigiHitProducer.h.
View newest version in sPHENIX GitHub at line 42 of file EicTpcDigiHitProducer.h
Constructor & Destructor Documentation
EicTpcDigiHitProducer::EicTpcDigiHitProducer () inline
Definition at line 45 of file EicTpcDigiHitProducer.h.
View newest version in sPHENIX GitHub at line 45 of file EicTpcDigiHitProducer.h
References EicTrackingDigiHitProducer::AssignDigiHitClassName(), and digi.
EicTpcDigiHitProducer::~EicTpcDigiHitProducer () inline
Definition at line 52 of file EicTpcDigiHitProducer.h.
View newest version in sPHENIX GitHub at line 52 of file EicTpcDigiHitProducer.h
Member Function Documentation
EicTpcDigiHitProducer::ClassDef (EicTpcDigiHitProducer , 1) private
int EicTpcDigiHitProducer::exportTpcDigiParameters (const char * fileName)
Definition at line 280 of file EicTpcDigiHitProducer.cxx.
View newest version in sPHENIX GitHub at line 280 of file EicTpcDigiHitProducer.cxx
EicDigiParData* EicTpcDigiHitProducer::getEicDigiParDataPtr () inline private virtual
Reimplemented from EicTrackingDigiHitProducer.
Definition at line 84 of file EicTpcDigiHitProducer.h.
View newest version in sPHENIX GitHub at line 84 of file EicTpcDigiHitProducer.h
References digi.
int EicTpcDigiHitProducer::HandleHit (const EicMoCaPoint * point) virtual
Core routine converting a single MoCa hit into digi
Should be provided for all detectors separately (pure virtual method); in fact there is no one-to-one relationship between MC points and digis for some detectors (say TPC);
Implements EicDigiHitProducer.
Definition at line 23 of file EicTpcDigiHitProducer.cxx.
View newest version in sPHENIX GitHub at line 23 of file EicTpcDigiHitProducer.cxx
References _SQR_, Acts::UnitConstants::C, c, cos(), EicMoCaPoint::GetMultiIndex(), EicMoCaPoint::GetPosIn(), EicMoCaPoint::GetPosOut(), ip(), ir(), it, LocalToMaster(), MasterToLocal(), LogicalVolumeLookupTableEntry::mGeoMtx, min, phi, Acts::IntegrationTest::R, rr, Acts::UnitConstants::s, and x2.
int EicTpcDigiHitProducer::importTpcDigiParameters (const char * fileName)
Definition at line 301 of file EicTpcDigiHitProducer.cxx.
View newest version in sPHENIX GitHub at line 301 of file EicTpcDigiHitProducer.cxx
Referenced by digitization().
void EicTpcDigiHitProducer::Print () inline
Definition at line 78 of file EicTpcDigiHitProducer.h.
View newest version in sPHENIX GitHub at line 78 of file EicTpcDigiHitProducer.h
References digi, and TpcDigiParData::Print().
Referenced by digitization().
void EicTpcDigiHitProducer::setGemVerticalPadSize (Double_t pitch) inline
Definition at line 76 of file EicTpcDigiHitProducer.h.
View newest version in sPHENIX GitHub at line 76 of file EicTpcDigiHitProducer.h
References digi, and TpcDigiParData::fGemVerticalPadSize.
void EicTpcDigiHitProducer::setLongitudinalDispersion (Double_t lDispersion) inline
Definition at line 64 of file EicTpcDigiHitProducer.h.
View newest version in sPHENIX GitHub at line 64 of file EicTpcDigiHitProducer.h
References digi, and TpcDigiParData::fLongitudinalDispersion.
void EicTpcDigiHitProducer::setLongitudinalIntrinsicResolution (Double_t lResolution) inline
Definition at line 67 of file EicTpcDigiHitProducer.h.
View newest version in sPHENIX GitHub at line 67 of file EicTpcDigiHitProducer.h
References digi, and TpcDigiParData::fLongitudinalIntrinsicResolution.
void EicTpcDigiHitProducer::setRadialIntrinsicResolution (Double_t tResolution) inline
Definition at line 73 of file EicTpcDigiHitProducer.h.
View newest version in sPHENIX GitHub at line 73 of file EicTpcDigiHitProducer.h
References digi, and TpcDigiParData::fRadialIntrinsicResolution.
void EicTpcDigiHitProducer::setTransverseDispersion (Double_t tDispersion) inline
Definition at line 61 of file EicTpcDigiHitProducer.h.
View newest version in sPHENIX GitHub at line 61 of file EicTpcDigiHitProducer.h
References digi, and TpcDigiParData::fTransverseDispersion.
void EicTpcDigiHitProducer::setTransverseIntrinsicResolution (Double_t tResolution) inline
Definition at line 70 of file EicTpcDigiHitProducer.h.
View newest version in sPHENIX GitHub at line 70 of file EicTpcDigiHitProducer.h
References digi, and TpcDigiParData::fTransverseIntrinsicResolution.
Member Data Documentation
TpcDigiParData* EicTpcDigiHitProducer::digi private
Definition at line 78 of file EicTpcDigiHitProducer.h.
View newest version in sPHENIX GitHub at line 78 of file EicTpcDigiHitProducer.h
Referenced by EicTpcDigiHitProducer(), getEicDigiParDataPtr(), Print(), setGemVerticalPadSize(), setLongitudinalDispersion(), setLongitudinalIntrinsicResolution(), setRadialIntrinsicResolution(), setTransverseDispersion(), and setTransverseIntrinsicResolution().
The documentation for this class was generated from the following files:
EicRoot/blob/master/eic/detectors/tpc/EicTpcDigiHitProducer.h
EicRoot/blob/master/eic/detectors/tpc/EicTpcDigiHitProducer.cxx