EIC Software: fun4all_coresoftware/blob/master/generators/hijing/src/g.f File Reference
g.f File Reference
Functions/Subroutines
function g (Y1, Y2, PT2)
Function/Subroutine Documentation
function g (Y1, Y2, PT2)
Definition at line 5 of file g.f.
View newest version in sPHENIX GitHub at line 5 of file g.f
References g4, HiParnt::hint1(), HiParnt::hipr1(), HiParnt::ihnt2(), HiParnt::ihpr2(), parton(), pt2, subcrs1(), subcrs2(), subcrs3(), subcrs4(), subcrs5(), subcrs6(), subcrs7(), t, x2, and z.
Referenced by __attribute__(), PHG4GDMLWriteMaterials::AtomWrite(), Acts::Test::BOOST_AUTO_TEST_CASE(), VertexFitFunc::calcValGradHessian(), Cell::Cell(), PHG4MicromegasDetector::create_materials(), PHG4Reco::DefineMaterials(), PHG4GDMLWriteMaterials::DWrite(), EicFRichDetector::element_material(), fjet(), fjetrig(), kdfinder::get_track_color(), PHG4CrystalCalorimeterDetector::GetCarbonFiber(), kdfinder::CircleFit< T >::GradientHessian(), tetgenmesh::hilbert_init(), CbmRichRingFitterEllipseTau::Jacobi(), lmcmnd(), lmidat(), lminew(), lminto(), lmpint(), lmprin(), lmrazz(), lmsimp(), ludcyk(), mrs991(), mrs9910(), mrs9911(), mrs9912(), mrs992(), mrs993(), mrs994(), mrs995(), mrs996(), mrs997(), mrs998(), mrs999(), kdfinder::Helix< T >::pathLengths(), pycbal(), pycrth(), pydcyk(), pygfxx(), pytbbn(), PHG4SectorSubsystem::set_geometry(), PHG4RICHSubsystem::set_RICH_geometry(), PHGeomTGeo::SetGeometry(), GeaneTrackRep::setPropagator(), kdfinder::CircleFit< T >::SigmaWithLargeCircleOption(), strc10(), strc11(), strc20(), and strc21().