EIC Software: fun4all_tutorials/blob/master/eventgenerator_display/Fun4All_Generator_Display.C File Reference
Fun4All_Generator_Display.C File Reference
#include <fun4all/SubsysReco.h>
#include <fun4all/Fun4AllServer.h>
#include <fun4all/Fun4AllInputManager.h>
#include <fun4all/Fun4AllDummyInputManager.h>
#include <g4main/PHG4ParticleGeneratorBase.h>
#include <g4main/PHG4ParticleGenerator.h>
#include <g4main/PHG4SimpleEventGenerator.h>
#include <g4main/PHG4ParticleGeneratorVectorMeson.h>
#include <g4main/PHG4ParticleGun.h>
#include <g4main/PHG4Reco.h>
#include <g4main/HepMCNodeReader.h>
#include <g4main/ReadEICFiles.h>
#include <phhepmc/Fun4AllHepMCInputManager.h>
#include <phool/recoConsts.h>
#include <phpythia6/PHPythia6.h>
#include <phpythia8/PHPythia8.h>
#include <phsartre/PHSartre.h>
Functions
int Fun4All_Generator_Display (const int nEvents=1, const std::string &inputFile="input.root")
void displaycmd ()
Variables
PHG4Reco * g4 = nullptr
Function Documentation
void displaycmd ()
Definition at line 269 of file Fun4All_Generator_Display.C.
View newest version in sPHENIX GitHub at line 269 of file Fun4All_Generator_Display.C
int Fun4All_Generator_Display (const int nEvents = 1, const std::string & inputFile = "input.root")
Definition at line 31 of file Fun4All_Generator_Display.C.
View newest version in sPHENIX GitHub at line 31 of file Fun4All_Generator_Display.C
References PHG4ParticleGeneratorVectorMeson::add_decay_particles(), PHG4SimpleEventGenerator::add_particles(), PHG4Reco::ApplyCommand(), PHG4Reco::ApplyDisplayAction(), Acts::UnitConstants::e, PHG4ParticleGeneratorBase::Embed(), Fun4AllServer::fileopen(), g4, in, PHG4Reco::InitRun(), recoConsts::instance(), Fun4AllServer::instance(), magfield, Fun4AllBase::Name(), ReadEICFiles::OpenInputFile(), Fun4AllServer::registerInputManager(), Fun4AllServer::registerSubsystem(), Fun4AllServer::run(), PHG4Reco::save_DST_geometry(), PHPythia6::set_config_file(), PHSartre::set_config_file(), PHPythia8::set_config_file(), PHG4ParticleGenerator::set_eta_range(), PHG4SimpleEventGenerator::set_eta_range(), PHG4SimpleEventGenerator::set_existing_vertex_offset_vector(), PHG4Reco::set_field(), PHG4ParticleGeneratorVectorMeson::set_mass(), PHG4ParticleGenerator::set_mom_range(), PHG4ParticleGeneratorBase::set_name(), PHG4ParticleGenerator::set_phi_range(), PHG4SimpleEventGenerator::set_phi_range(), PHG4ParticleGeneratorVectorMeson::set_pt_range(), PHG4SimpleEventGenerator::set_pt_range(), PHG4Reco::set_rapidity_coverage(), PHG4ParticleGeneratorVectorMeson::set_rapidity_range(), PHG4ParticleGeneratorBase::set_reuse_existing_vertex(), PHG4SimpleEventGenerator::set_vertex_distribution_function(), PHG4SimpleEventGenerator::set_vertex_distribution_mean(), PHG4SimpleEventGenerator::set_vertex_distribution_width(), PHG4SimpleEventGenerator::set_vertex_size_function(), PHG4SimpleEventGenerator::set_vertex_size_parameters(), PHG4ParticleGeneratorVectorMeson::set_width(), PHG4ParticleGenerator::set_z_range(), Fun4AllServer::topNode(), PHG4SimpleEventGenerator::Uniform, and Fun4AllBase::Verbosity().
Variable Documentation
PHG4Reco* g4 = nullptr
Definition at line 29 of file Fun4All_Generator_Display.C.
View newest version in sPHENIX GitHub at line 29 of file Fun4All_Generator_Display.C