EIC Software: EicMagneticFieldGrad Class Reference
EicMagneticFieldGrad Class Reference abstract
#include <EicRoot/blob/master/eic/field/EicMagneticFieldGrad.h>
Public Member Functions
EicMagneticFieldGrad (const char *fileName=0, TGeoMatrix *transformation=0, TGeoShape *shape=0, int color=_DEFAULT_YOKE_COLOR_)
~EicMagneticFieldGrad ()
virtual int Initialize ()
bool Initialized () const
virtual int GetFieldValue (const double xx[], double B[]) const =0
TGeoShape * GetShape () const
virtual bool Contains (const double xx[]) const
const TString & GetFileName () const
virtual bool CapableToBuildYoke () const
virtual TString GetDetectorName () const
virtual int ConstructGeometry ()
void SetYokeColor (int color)
int GetYokeColor () const
virtual TGeoVolume * GetYokeVolume () const
Protected Attributes
Bool_t mInitialized
TGeoMatrix * mTransformation
indicates whether Initialize() call was made or not
TGeoShape * mShape
Int_t mColor
Private Attributes
TString mFileName
Detailed Description
Definition at line 17 of file EicMagneticFieldGrad.h.
View newest version in sPHENIX GitHub at line 17 of file EicMagneticFieldGrad.h
Constructor & Destructor Documentation
EicMagneticFieldGrad::EicMagneticFieldGrad (const char * fileName = 0, TGeoMatrix * transformation = 0, TGeoShape * shape = 0, int color = _DEFAULT_YOKE_COLOR_)
Definition at line 21 of file EicMagneticFieldGrad.cxx.
View newest version in sPHENIX GitHub at line 21 of file EicMagneticFieldGrad.cxx
References FairLogger::Fatal(), FairLogger::GetLogger(), MESSAGE_ORIGIN, mFileName, and mShape.
EicMagneticFieldGrad::~EicMagneticFieldGrad () inline
Definition at line 22 of file EicMagneticFieldGrad.h.
View newest version in sPHENIX GitHub at line 22 of file EicMagneticFieldGrad.h
Member Function Documentation
virtual bool EicMagneticFieldGrad::CapableToBuildYoke () const inline virtual
Definition at line 44 of file EicMagneticFieldGrad.h.
View newest version in sPHENIX GitHub at line 44 of file EicMagneticFieldGrad.h
Referenced by EicMagneticFieldFromGradients::CreateYokeVolumes().
virtual int EicMagneticFieldGrad::ConstructGeometry () inline virtual
Definition at line 50 of file EicMagneticFieldGrad.h.
View newest version in sPHENIX GitHub at line 50 of file EicMagneticFieldGrad.h
Referenced by EicFieldGradDetector::ConstructGeometry().
bool EicMagneticFieldGrad::Contains (const double xx[]) const virtual
Definition at line 59 of file EicMagneticFieldGrad.cxx.
View newest version in sPHENIX GitHub at line 59 of file EicMagneticFieldGrad.cxx
References mShape, and mTransformation.
virtual TString EicMagneticFieldGrad::GetDetectorName () const inline virtual
Definition at line 49 of file EicMagneticFieldGrad.h.
View newest version in sPHENIX GitHub at line 49 of file EicMagneticFieldGrad.h
References GetFileName().
virtual int EicMagneticFieldGrad::GetFieldValue (const double xx[], double B[]) const pure virtual
Referenced by EicMagneticFieldFromGradients::GetFieldSumValue().
const TString& EicMagneticFieldGrad::GetFileName (void) const inline
Definition at line 41 of file EicMagneticFieldGrad.h.
View newest version in sPHENIX GitHub at line 41 of file EicMagneticFieldGrad.h
References mFileName.
Referenced by EicFieldGradDetector::ConstructGeometry(), GetDetectorName(), and EicMagneticFieldFromGradients::InitializeFieldGradients().
TGeoShape* EicMagneticFieldGrad::GetShape () const inline
Definition at line 36 of file EicMagneticFieldGrad.h.
View newest version in sPHENIX GitHub at line 36 of file EicMagneticFieldGrad.h
References mShape.
int EicMagneticFieldGrad::GetYokeColor () const inline
Definition at line 53 of file EicMagneticFieldGrad.h.
View newest version in sPHENIX GitHub at line 53 of file EicMagneticFieldGrad.h
References mColor.
virtual TGeoVolume* EicMagneticFieldGrad::GetYokeVolume () const inline virtual
Definition at line 55 of file EicMagneticFieldGrad.h.
View newest version in sPHENIX GitHub at line 55 of file EicMagneticFieldGrad.h
Referenced by EicFieldGradDetector::ConstructGeometry().
int EicMagneticFieldGrad::Initialize () virtual
Definition at line 48 of file EicMagneticFieldGrad.cxx.
View newest version in sPHENIX GitHub at line 48 of file EicMagneticFieldGrad.cxx
References mInitialized.
Referenced by EicMagneticFieldFromGradients::InitializeFieldGradients().
bool EicMagneticFieldGrad::Initialized () const inline
Definition at line 30 of file EicMagneticFieldGrad.h.
View newest version in sPHENIX GitHub at line 30 of file EicMagneticFieldGrad.h
References mInitialized.
Referenced by EicMagneticFieldFromGradients::InitializeFieldGradients().
void EicMagneticFieldGrad::SetYokeColor (int color) inline
Definition at line 52 of file EicMagneticFieldGrad.h.
View newest version in sPHENIX GitHub at line 52 of file EicMagneticFieldGrad.h
References color, and mColor.
Member Data Documentation
Int_t EicMagneticFieldGrad::mColor protected
Definition at line 72 of file EicMagneticFieldGrad.h.
View newest version in sPHENIX GitHub at line 72 of file EicMagneticFieldGrad.h
Referenced by GetYokeColor(), and SetYokeColor().
TString EicMagneticFieldGrad::mFileName private
Definition at line 55 of file EicMagneticFieldGrad.h.
View newest version in sPHENIX GitHub at line 55 of file EicMagneticFieldGrad.h
Referenced by EicMagneticFieldGrad(), and GetFileName().
Bool_t EicMagneticFieldGrad::mInitialized protected
Definition at line 63 of file EicMagneticFieldGrad.h.
View newest version in sPHENIX GitHub at line 63 of file EicMagneticFieldGrad.h
Referenced by Initialize(), and Initialized().
TGeoShape* EicMagneticFieldGrad::mShape protected
Definition at line 70 of file EicMagneticFieldGrad.h.
View newest version in sPHENIX GitHub at line 70 of file EicMagneticFieldGrad.h
Referenced by Contains(), EicMagneticFieldGrad(), and GetShape().
TGeoMatrix* EicMagneticFieldGrad::mTransformation protected
indicates whether Initialize() call was made or not
Definition at line 65 of file EicMagneticFieldGrad.h.
View newest version in sPHENIX GitHub at line 65 of file EicMagneticFieldGrad.h
Referenced by Contains().
The documentation for this class was generated from the following files:
EicRoot/blob/master/eic/field/EicMagneticFieldGrad.h
EicRoot/blob/master/eic/field/EicMagneticFieldGrad.cxx