EIC Software: PHActsTracks Class Reference
PHActsTracks Class Reference
#include <fun4all_coresoftware/blob/master/offline/packages/trackreco/PHActsTracks.h>
Public Member Functions
PHActsTracks (const std::string &name="PHActsTracks")
Default constructor and destructor.
virtual ~PHActsTracks ()
int End (PHCompositeNode *topNode)
Inherited SubsysReco functions.
int Init (PHCompositeNode *topNode)
int InitRun (PHCompositeNode *topNode)
int process_event (PHCompositeNode *topNode)
int ResetEvent (PHCompositeNode *topNode)
Clean up after each event.
void setTruthTrackSeeding (bool truthTrackSeeding)
void setSecondFit (bool secondFit)
Public Member Functions inherited from SubsysReco
virtual ~SubsysReco ()
virtual int EndRun (const int)
Called at the end of each run.
virtual int Reset (PHCompositeNode *)
Reset.
virtual void Print (const std::string &what="ALL") const
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Private Member Functions
void createNodes (PHCompositeNode *topNode)
Create track seed node if it doesn't exist yet.
int getNodes (PHCompositeNode *topNode)
Get nodes off node tree needed to execute module.
void printTrackSeed (const ActsExamples::TrackParameters seed)
Private Attributes
std::vector< SourceLink > m_trackSourceLinks
A vector to hold the source links corresponding to a particular SvtxTrack.
std::map< unsigned int,
ActsTrack > * m_actsTrackMap
A map corresponding the ActsTrack instance to the SvtxTrack key.
SvtxTrackMap * m_trackMap
Trackmap that contains SvtxTracks.
SvtxVertexMap * m_vertexMap
VertexMap that contains the initial vertexing estimates.
CluskeyBimap * m_hitIdClusKey
Map between cluster key and arbitrary hit id created in PHActsSourceLinks.
std::map< unsigned int,
SourceLink > * m_sourceLinks
Map of hitid:SourceLinks created in PHActsSourceLinks.
ActsTrackingGeometry * m_tGeometry
Acts TrackingGeometry necessary for various contexts.
bool m_truthTrackSeeding = false
bool m_secondFit = false
Boolean for running the second fit pass.
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = INT_MAX - 10
}
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Detailed Description
This class is responsible for taking SvtxTracks and converting them to track seeds that Acts can take in to the track fitter. It collects SvtxTracks, converts them to Acts tracks, and then finds the corresponding TrkrClusterSourceLinks to that SvtxTrack. The output is a node on the node tree that is a map of Acts track seeds and corresponding source links
Definition at line 44 of file PHActsTracks.h.
View newest version in sPHENIX GitHub at line 44 of file PHActsTracks.h
Constructor & Destructor Documentation
PHActsTracks::PHActsTracks (const std::string & name = "PHActsTracks")
Default constructor and destructor.
Fun4All includes.
Tracking includes std (and the like) includes
Definition at line 33 of file PHActsTracks.cc.
View newest version in sPHENIX GitHub at line 33 of file PHActsTracks.cc
References Fun4AllBase::Verbosity().
virtual PHActsTracks::~PHActsTracks () inline virtual
Definition at line 49 of file PHActsTracks.h.
View newest version in sPHENIX GitHub at line 49 of file PHActsTracks.h
Member Function Documentation
void PHActsTracks::createNodes (PHCompositeNode * topNode) private
Create track seed node if it doesn't exist yet.
Member functions
Definition at line 256 of file PHActsTracks.cc.
View newest version in sPHENIX GitHub at line 256 of file PHActsTracks.cc
References PHCompositeNode::addNode(), PHNodeIterator::findFirst(), and m_actsTrackMap.
Referenced by InitRun().
int PHActsTracks::End (PHCompositeNode * topNode) virtual
Inherited SubsysReco functions.
Reimplemented from SubsysReco.
Definition at line 45 of file PHActsTracks.cc.
View newest version in sPHENIX GitHub at line 45 of file PHActsTracks.cc
References Fun4AllReturnCodes::EVENT_OK, and Fun4AllBase::Verbosity().
int PHActsTracks::getNodes (PHCompositeNode * topNode) private
Get nodes off node tree needed to execute module.
Definition at line 290 of file PHActsTracks.cc.
View newest version in sPHENIX GitHub at line 290 of file PHActsTracks.cc
References Fun4AllReturnCodes::ABORTEVENT, Fun4AllReturnCodes::EVENT_OK, m_hitIdClusKey, m_sourceLinks, m_tGeometry, m_trackMap, m_vertexMap, and PHWHERE.
Referenced by process_event().
int PHActsTracks::Init (PHCompositeNode *) virtual
Called during initialization. Typically this is where you can book histograms, and e.g. register them to Fun4AllServer (so they can be output to file using Fun4AllServer::dumpHistos() method).
Reimplemented from SubsysReco.
Definition at line 56 of file PHActsTracks.cc.
View newest version in sPHENIX GitHub at line 56 of file PHActsTracks.cc
References Fun4AllReturnCodes::EVENT_OK.
int PHActsTracks::InitRun (PHCompositeNode *) virtual
Called for first event when run number is known. Typically this is where you may want to fetch data from database, because you know the run number.
Reimplemented from SubsysReco.
Definition at line 61 of file PHActsTracks.cc.
View newest version in sPHENIX GitHub at line 61 of file PHActsTracks.cc
References createNodes(), and Fun4AllReturnCodes::EVENT_OK.
void PHActsTracks::printTrackSeed (const ActsExamples::TrackParameters seed) private
This will always have a values since we explicitly set it
Definition at line 343 of file PHActsTracks.cc.
View newest version in sPHENIX GitHub at line 343 of file PHActsTracks.cc
References ActsTrackingGeometry::geoContext, m_tGeometry, PHWHERE, and Acts::VectorHelpers::position().
Referenced by process_event().
int PHActsTracks::process_event (PHCompositeNode *) virtual
Called for each event. This is where you do the real work.
Start fresh in this event in this module
Check to get the nodes needed
Vector to hold source links for a particular track
If the vertex is available, use it. Otherwise use track position
Get the necessary parameters and values for the TrackParameters
just set to 10 ns for now. Time isn't needed by Acts, only if TOF is present
Skip this track seed if the seed somehow got screwed up
Start fresh for this track
Reimplemented from SubsysReco.
Definition at line 68 of file PHActsTracks.cc.
View newest version in sPHENIX GitHub at line 68 of file PHActsTracks.cc
References Fun4AllReturnCodes::ABORTEVENT, SvtxTrackMap::begin(), SvtxTrack::begin_cluster_keys(), Acts::UnitConstants::cm, Acts::UnitConstants::e, SvtxTrackMap::end(), SvtxTrack::end_cluster_keys(), Fun4AllReturnCodes::EVENT_OK, ActsTrackingGeometry::geoContext, SvtxVertexMap::get(), SvtxTrack::get_charge(), SvtxTrack::get_p(), SvtxTrack::get_px(), SvtxTrack::get_py(), SvtxTrack::get_pz(), SvtxTrack::get_vertex_id(), SvtxVertex::get_x(), SvtxTrack::get_x(), SvtxVertex::get_y(), SvtxTrack::get_y(), SvtxVertex::get_z(), SvtxTrack::get_z(), TrkrDefs::getLayer(), getNodes(), Acts::UnitConstants::GeV, SvtxTrack::identify(), m_actsTrackMap, m_hitIdClusKey, m_secondFit, m_sourceLinks, m_tGeometry, m_trackMap, m_truthTrackSeeding, m_vertexMap, Acts::UnitConstants::ns, p, PHWHERE, printTrackSeed(), and Fun4AllBase::Verbosity().
int PHActsTracks::ResetEvent (PHCompositeNode *) virtual
Clean up after each event.
Reset the proto track vector after each event
Reimplemented from SubsysReco.
Definition at line 248 of file PHActsTracks.cc.
View newest version in sPHENIX GitHub at line 248 of file PHActsTracks.cc
References Fun4AllReturnCodes::EVENT_OK, and m_actsTrackMap.
void PHActsTracks::setSecondFit (bool secondFit) inline
Definition at line 61 of file PHActsTracks.h.
View newest version in sPHENIX GitHub at line 61 of file PHActsTracks.h
References m_secondFit.
Referenced by Tracking_Reco().
void PHActsTracks::setTruthTrackSeeding (bool truthTrackSeeding) inline
Definition at line 58 of file PHActsTracks.h.
View newest version in sPHENIX GitHub at line 58 of file PHActsTracks.h
References m_truthTrackSeeding.
Member Data Documentation
std::map<unsigned int , ActsTrack>* PHActsTracks::m_actsTrackMap private
A map corresponding the ActsTrack instance to the SvtxTrack key.
Definition at line 85 of file PHActsTracks.h.
View newest version in sPHENIX GitHub at line 85 of file PHActsTracks.h
Referenced by createNodes(), process_event(), and ResetEvent().
CluskeyBimap* PHActsTracks::m_hitIdClusKey private
Map between cluster key and arbitrary hit id created in PHActsSourceLinks.
Definition at line 94 of file PHActsTracks.h.
View newest version in sPHENIX GitHub at line 94 of file PHActsTracks.h
Referenced by getNodes(), and process_event().
bool PHActsTracks::m_secondFit = false private
Boolean for running the second fit pass.
Definition at line 105 of file PHActsTracks.h.
View newest version in sPHENIX GitHub at line 105 of file PHActsTracks.h
Referenced by process_event(), and setSecondFit().
std::map<unsigned int, SourceLink>* PHActsTracks::m_sourceLinks private
Map of hitid:SourceLinks created in PHActsSourceLinks.
Definition at line 97 of file PHActsTracks.h.
View newest version in sPHENIX GitHub at line 97 of file PHActsTracks.h
Referenced by getNodes(), and process_event().
ActsTrackingGeometry* PHActsTracks::m_tGeometry private
Acts TrackingGeometry necessary for various contexts.
Definition at line 100 of file PHActsTracks.h.
View newest version in sPHENIX GitHub at line 100 of file PHActsTracks.h
Referenced by getNodes(), printTrackSeed(), and process_event().
SvtxTrackMap* PHActsTracks::m_trackMap private
Trackmap that contains SvtxTracks.
Definition at line 88 of file PHActsTracks.h.
View newest version in sPHENIX GitHub at line 88 of file PHActsTracks.h
Referenced by getNodes(), and process_event().
std::vector<SourceLink> PHActsTracks::m_trackSourceLinks private
A vector to hold the source links corresponding to a particular SvtxTrack.
Member variables
Definition at line 82 of file PHActsTracks.h.
View newest version in sPHENIX GitHub at line 82 of file PHActsTracks.h
bool PHActsTracks::m_truthTrackSeeding = false private
Definition at line 102 of file PHActsTracks.h.
View newest version in sPHENIX GitHub at line 102 of file PHActsTracks.h
Referenced by process_event(), and setTruthTrackSeeding().
SvtxVertexMap* PHActsTracks::m_vertexMap private
VertexMap that contains the initial vertexing estimates.
Definition at line 91 of file PHActsTracks.h.
View newest version in sPHENIX GitHub at line 91 of file PHActsTracks.h
Referenced by getNodes(), and process_event().
The documentation for this class was generated from the following files:
fun4all_coresoftware/blob/master/offline/packages/trackreco/PHActsTracks.h
fun4all_coresoftware/blob/master/offline/packages/trackreco/PHActsTracks.cc