EIC Software: eASTUserActionDispatcher Class Reference
eASTUserActionDispatcher Class Reference
#include <east/blob/main/Core/include/eASTUserActionDispatcher.hh>
Public Types
using RunActions = std::map< G4Region *, G4UserRunAction * >
using EventActions = std::map< G4Region *, G4UserEventAction * >
using StackingActions = std::map< G4Region *, G4UserStackingAction * >
using TrackingActions = std::map< G4Region *, G4UserTrackingAction * >
Public Member Functions
~eASTUserActionDispatcher ()
RunActions * GetRunActions ()
EventActions * GetEventActions ()
StackingActions * GetStackingActions ()
TrackingActions * GetTrackingActions ()
void RegisterUserAction (G4Region *reg, G4UserRunAction *ua)
void RegisterUserAction (G4Region *reg, G4UserEventAction *ua)
void RegisterUserAction (G4Region *reg, G4UserStackingAction *ua)
void RegisterUserAction (G4Region *reg, G4UserTrackingAction *ua)
Static Public Member Functions
static eASTUserActionDispatcher * Instance ()
Private Member Functions
eASTUserActionDispatcher ()
Private Attributes
RunActions * fpRunActions = nullptr
EventActions * fpEventActions = nullptr
StackingActions * fpStackingActions = nullptr
TrackingActions * fpTrackingActions = nullptr
Static Private Attributes
static G4ThreadLocal
eASTUserActionDispatcher * instance = nullptr
Detailed Description
Definition at line 26 of file eASTUserActionDispatcher.hh.
View newest version in sPHENIX GitHub at line 26 of file eASTUserActionDispatcher.hh
Member Typedef Documentation
using eASTUserActionDispatcher::EventActions = std::map<G4Region*,G4UserEventAction*>
Definition at line 30 of file eASTUserActionDispatcher.hh.
View newest version in sPHENIX GitHub at line 30 of file eASTUserActionDispatcher.hh
using eASTUserActionDispatcher::RunActions = std::map<G4Region*,G4UserRunAction*>
Definition at line 29 of file eASTUserActionDispatcher.hh.
View newest version in sPHENIX GitHub at line 29 of file eASTUserActionDispatcher.hh
using eASTUserActionDispatcher::StackingActions = std::map<G4Region*,G4UserStackingAction*>
Definition at line 31 of file eASTUserActionDispatcher.hh.
View newest version in sPHENIX GitHub at line 31 of file eASTUserActionDispatcher.hh
using eASTUserActionDispatcher::TrackingActions = std::map<G4Region*,G4UserTrackingAction*>
Definition at line 32 of file eASTUserActionDispatcher.hh.
View newest version in sPHENIX GitHub at line 32 of file eASTUserActionDispatcher.hh
Constructor & Destructor Documentation
eASTUserActionDispatcher::eASTUserActionDispatcher () inline private
Definition at line 41 of file eASTUserActionDispatcher.hh.
View newest version in sPHENIX GitHub at line 41 of file eASTUserActionDispatcher.hh
Referenced by Instance().
eASTUserActionDispatcher::~eASTUserActionDispatcher ()
Definition at line 28 of file eASTUserActionDispatcher.cc.
View newest version in sPHENIX GitHub at line 28 of file eASTUserActionDispatcher.cc
References fpEventActions, fpRunActions, fpStackingActions, fpTrackingActions, and instance.
Member Function Documentation
EventActions* eASTUserActionDispatcher::GetEventActions () inline
Definition at line 50 of file eASTUserActionDispatcher.hh.
View newest version in sPHENIX GitHub at line 50 of file eASTUserActionDispatcher.hh
References fpEventActions.
Referenced by eASTEventAction::BeginOfEventAction(), and eASTEventAction::EndOfEventAction().
RunActions* eASTUserActionDispatcher::GetRunActions () inline
Definition at line 48 of file eASTUserActionDispatcher.hh.
View newest version in sPHENIX GitHub at line 48 of file eASTUserActionDispatcher.hh
References fpRunActions.
Referenced by eASTRunAction::BeginOfRunAction(), and eASTRunAction::EndOfRunAction().
StackingActions* eASTUserActionDispatcher::GetStackingActions () inline
Definition at line 52 of file eASTUserActionDispatcher.hh.
View newest version in sPHENIX GitHub at line 52 of file eASTUserActionDispatcher.hh
References fpStackingActions.
Referenced by eASTStackingAction::ClassifyNewTrack(), eASTStackingAction::NewStage(), and eASTStackingAction::PrepareNewEvent().
TrackingActions* eASTUserActionDispatcher::GetTrackingActions () inline
Definition at line 54 of file eASTUserActionDispatcher.hh.
View newest version in sPHENIX GitHub at line 54 of file eASTUserActionDispatcher.hh
References fpTrackingActions.
Referenced by eASTTrackingAction::PostUserTrackingAction(), and eASTTrackingAction::PreUserTrackingAction().
eASTUserActionDispatcher * eASTUserActionDispatcher::Instance () static
Definition at line 21 of file eASTUserActionDispatcher.cc.
View newest version in sPHENIX GitHub at line 21 of file eASTUserActionDispatcher.cc
References eASTUserActionDispatcher(), and instance.
Referenced by eASTEventAction::BeginOfEventAction(), eASTRunAction::BeginOfRunAction(), eASTStackingAction::ClassifyNewTrack(), eASTVDetectorComponent::eASTVDetectorComponent(), eASTEventAction::EndOfEventAction(), eASTRunAction::EndOfRunAction(), eASTStackingAction::NewStage(), eASTTrackingAction::PostUserTrackingAction(), eASTStackingAction::PrepareNewEvent(), and eASTTrackingAction::PreUserTrackingAction().
void eASTUserActionDispatcher::RegisterUserAction (G4Region * reg, G4UserRunAction * ua) inline
Definition at line 58 of file eASTUserActionDispatcher.hh.
View newest version in sPHENIX GitHub at line 58 of file eASTUserActionDispatcher.hh
References fpRunActions.
Referenced by eASTVDetectorComponent::RegisterUserAction().
void eASTUserActionDispatcher::RegisterUserAction (G4Region * reg, G4UserEventAction * ua) inline
Definition at line 63 of file eASTUserActionDispatcher.hh.
View newest version in sPHENIX GitHub at line 63 of file eASTUserActionDispatcher.hh
References fpEventActions.
void eASTUserActionDispatcher::RegisterUserAction (G4Region * reg, G4UserStackingAction * ua) inline
Definition at line 68 of file eASTUserActionDispatcher.hh.
View newest version in sPHENIX GitHub at line 68 of file eASTUserActionDispatcher.hh
References fpStackingActions.
void eASTUserActionDispatcher::RegisterUserAction (G4Region * reg, G4UserTrackingAction * ua) inline
Definition at line 73 of file eASTUserActionDispatcher.hh.
View newest version in sPHENIX GitHub at line 73 of file eASTUserActionDispatcher.hh
References fpTrackingActions.
Member Data Documentation
EventActions* eASTUserActionDispatcher::fpEventActions = nullptr private
Definition at line 81 of file eASTUserActionDispatcher.hh.
View newest version in sPHENIX GitHub at line 81 of file eASTUserActionDispatcher.hh
Referenced by GetEventActions(), RegisterUserAction(), and ~eASTUserActionDispatcher().
RunActions* eASTUserActionDispatcher::fpRunActions = nullptr private
Definition at line 80 of file eASTUserActionDispatcher.hh.
View newest version in sPHENIX GitHub at line 80 of file eASTUserActionDispatcher.hh
Referenced by GetRunActions(), RegisterUserAction(), and ~eASTUserActionDispatcher().
StackingActions* eASTUserActionDispatcher::fpStackingActions = nullptr private
Definition at line 82 of file eASTUserActionDispatcher.hh.
View newest version in sPHENIX GitHub at line 82 of file eASTUserActionDispatcher.hh
Referenced by GetStackingActions(), RegisterUserAction(), and ~eASTUserActionDispatcher().
TrackingActions* eASTUserActionDispatcher::fpTrackingActions = nullptr private
Definition at line 83 of file eASTUserActionDispatcher.hh.
View newest version in sPHENIX GitHub at line 83 of file eASTUserActionDispatcher.hh
Referenced by GetTrackingActions(), RegisterUserAction(), and ~eASTUserActionDispatcher().
G4ThreadLocal eASTUserActionDispatcher * eASTUserActionDispatcher::instance = nullptr static private
Definition at line 38 of file eASTUserActionDispatcher.hh.
View newest version in sPHENIX GitHub at line 38 of file eASTUserActionDispatcher.hh
Referenced by Instance(), and ~eASTUserActionDispatcher().
The documentation for this class was generated from the following files:
east/blob/main/Core/include/eASTUserActionDispatcher.hh
east/blob/main/Core/src/eASTUserActionDispatcher.cc