EIC Software: PndGFTrackToPndTrackConvertorTask Class Reference
PndGFTrackToPndTrackConvertorTask Class Reference
#include <EicRoot/blob/master/GenfitTools/recotasks/PndGFTrackToPndTrackConvertorTask.h>
Public Member Functions
PndGFTrackToPndTrackConvertorTask (const char *name="Track Convertor", Int_t iVerbose=0)
~PndGFTrackToPndTrackConvertorTask ()
void SetTrackInBranchName (const TString &name)
void SetTrackOutBranchName (const TString &name)
virtual InitStatus Init ()
virtual void Exec (Option_t *opt)
Public Member Functions inherited from FairTask
FairTask ()
FairTask (const char *name, Int_t iVerbose=1)
virtual ~FairTask ()
void InitTask ()
void ReInitTask ()
void SetParTask ()
virtual void FinishTask ()
virtual void FinishEvent ()
void SetVerbose (Int_t iVerbose)
void SetInputPersistance (Bool_t val)
void CheckInputPersistance (TString branchName)
Private Member Functions
ClassDef (PndGFTrackToPndTrackConvertorTask, 1)
Name of the output TCA.
Private Attributes
TClonesArray * fInTrackArray
TClonesArray * fOutTrackArray
TString fTrackInBranchName
Output TCA for track.
TString fTrackOutBranchName
Name of the input TCA.
Additional Inherited Members
Protected Member Functions inherited from FairTask
virtual InitStatus ReInit ()
virtual void SetParContainers ()
virtual void Finish ()
void InitTasks ()
void ReInitTasks ()
void SetParTasks ()
void FinishTasks ()
void FinishEvents ()
Protected Attributes inherited from FairTask
Int_t fVerbose
Int_t fInputPersistance
Indicates if input branch is persistant.
FairLogger * fLogger
Detailed Description
Definition at line 17 of file PndGFTrackToPndTrackConvertorTask.h.
View newest version in sPHENIX GitHub at line 17 of file PndGFTrackToPndTrackConvertorTask.h
Constructor & Destructor Documentation
PndGFTrackToPndTrackConvertorTask::PndGFTrackToPndTrackConvertorTask (const char * name = "Track Convertor", Int_t iVerbose = 0)
Definition at line 24 of file PndGFTrackToPndTrackConvertorTask.cxx.
View newest version in sPHENIX GitHub at line 24 of file PndGFTrackToPndTrackConvertorTask.cxx
References fOutTrackArray, fTrackInBranchName, and fTrackOutBranchName.
PndGFTrackToPndTrackConvertorTask::~PndGFTrackToPndTrackConvertorTask ()
Definition at line 33 of file PndGFTrackToPndTrackConvertorTask.cxx.
View newest version in sPHENIX GitHub at line 33 of file PndGFTrackToPndTrackConvertorTask.cxx
Member Function Documentation
PndGFTrackToPndTrackConvertorTask::ClassDef (PndGFTrackToPndTrackConvertorTask , 1) private
Name of the output TCA.
void PndGFTrackToPndTrackConvertorTask::Exec (Option_t * opt) virtual
Definition at line 63 of file PndGFTrackToPndTrackConvertorTask.cxx.
View newest version in sPHENIX GitHub at line 63 of file PndGFTrackToPndTrackConvertorTask.cxx
References Acts::UnitConstants::e, fInTrackArray, fOutTrackArray, fTrackInBranchName, FairTask::fVerbose, GenfitTrack2PndTrack(), FairRootManager::GetBranchId(), PndTrack::GetChi2(), PndTrack::GetFlag(), PndTrack::GetNDF(), PndTrack::GetParamFirst(), PndTrack::GetParamLast(), PndTrack::GetPidHypo(), PndTrack::GetTrackCand(), FairRootManager::Instance(), and GFException::what().
InitStatus PndGFTrackToPndTrackConvertorTask::Init (void) virtual
Intialisation at begin of run. To be implemented in the derived class. Success If not kSUCCESS, task will be set inactive.
Reimplemented from FairTask.
Definition at line 38 of file PndGFTrackToPndTrackConvertorTask.cxx.
View newest version in sPHENIX GitHub at line 38 of file PndGFTrackToPndTrackConvertorTask.cxx
References fInTrackArray, fOutTrackArray, fTrackInBranchName, fTrackOutBranchName, FairRootManager::GetObject(), FairRootManager::Instance(), kERROR, kSUCCESS, and FairRootManager::Register().
void PndGFTrackToPndTrackConvertorTask::SetTrackInBranchName (const TString & name) inline
Definition at line 30 of file PndGFTrackToPndTrackConvertorTask.h.
View newest version in sPHENIX GitHub at line 30 of file PndGFTrackToPndTrackConvertorTask.h
References fTrackInBranchName, and name.
void PndGFTrackToPndTrackConvertorTask::SetTrackOutBranchName (const TString & name) inline
Definition at line 31 of file PndGFTrackToPndTrackConvertorTask.h.
View newest version in sPHENIX GitHub at line 31 of file PndGFTrackToPndTrackConvertorTask.h
References fTrackOutBranchName, and name.
Member Data Documentation
TClonesArray* PndGFTrackToPndTrackConvertorTask::fInTrackArray private
Definition at line 40 of file PndGFTrackToPndTrackConvertorTask.h.
View newest version in sPHENIX GitHub at line 40 of file PndGFTrackToPndTrackConvertorTask.h
Referenced by Exec(), and Init().
TClonesArray* PndGFTrackToPndTrackConvertorTask::fOutTrackArray private
Definition at line 41 of file PndGFTrackToPndTrackConvertorTask.h.
View newest version in sPHENIX GitHub at line 41 of file PndGFTrackToPndTrackConvertorTask.h
Referenced by Exec(), Init(), and PndGFTrackToPndTrackConvertorTask().
TString PndGFTrackToPndTrackConvertorTask::fTrackInBranchName private
Output TCA for track.
Definition at line 43 of file PndGFTrackToPndTrackConvertorTask.h.
View newest version in sPHENIX GitHub at line 43 of file PndGFTrackToPndTrackConvertorTask.h
Referenced by Exec(), Init(), PndGFTrackToPndTrackConvertorTask(), and SetTrackInBranchName().
TString PndGFTrackToPndTrackConvertorTask::fTrackOutBranchName private
Name of the input TCA.
Definition at line 44 of file PndGFTrackToPndTrackConvertorTask.h.
View newest version in sPHENIX GitHub at line 44 of file PndGFTrackToPndTrackConvertorTask.h
Referenced by Init(), PndGFTrackToPndTrackConvertorTask(), and SetTrackOutBranchName().
The documentation for this class was generated from the following files:
EicRoot/blob/master/GenfitTools/recotasks/PndGFTrackToPndTrackConvertorTask.h
EicRoot/blob/master/GenfitTools/recotasks/PndGFTrackToPndTrackConvertorTask.cxx