EIC Software: fun4all_eicmacros/blob/master/common/G4_Barrel_EIC.C File Reference
G4_Barrel_EIC.C File Reference
#include <GlobalVariables.C>
#include <g4detectors/PHG4CylinderSubsystem.h>
#include <g4main/PHG4Reco.h>
#include <fun4all/Fun4AllServer.h>
#include <cmath>
#include <vector>
Namespaces
namespace Enable
namespace G4BARREL
namespace G4BARREL::SETTING
Macros
#define MACRO_G4BARRELEIC_C
Functions
int make_barrel_pixel_layer (const string &name, PHG4Reco *g4Reco, double radius, double halflength, double tSilicon, double tAirgap)
void BarrelInit ()
double Barrel (PHG4Reco *g4Reco, double radius)
Variables
bool Enable::BARREL = false
bool Enable::BARREL_ABSORBER = false
bool G4BARREL::SETTING::BARRELV0 = false
bool G4BARREL::SETTING::BARRELV1 = false
bool G4BARREL::SETTING::BARRELV2 = false
bool G4BARREL::SETTING::BARRELV3 = false
bool G4BARREL::SETTING::BARRELV4 = false
bool G4BARREL::SETTING::BARRELV5 = false
bool G4BARREL::SETTING::BARRELV6 = false
Macro Definition Documentation
#define MACRO_G4BARRELEIC_C
Definition at line 10 of file G4_Barrel_EIC.C.
View newest version in sPHENIX GitHub at line 10 of file G4_Barrel_EIC.C
Function Documentation
double Barrel (PHG4Reco * g4Reco, double radius)
Definition at line 76 of file G4_Barrel_EIC.C.
View newest version in sPHENIX GitHub at line 76 of file G4_Barrel_EIC.C
References Enable::ABSORBER, Enable::BARREL_ABSORBER, G4BARREL::SETTING::BARRELV1, G4BARREL::SETTING::BARRELV2, G4BARREL::SETTING::BARRELV3, G4BARREL::SETTING::BARRELV4, G4BARREL::SETTING::BARRELV5, G4BARREL::SETTING::BARRELV6, make_barrel_pixel_layer(), max, BlackHoleGeometry::max_radius, BlackHoleGeometry::max_z, min, BlackHoleGeometry::min_z, n, and Acts::UnitConstants::um.
Referenced by G4Setup().
void BarrelInit ()
Definition at line 50 of file G4_Barrel_EIC.C.
View newest version in sPHENIX GitHub at line 50 of file G4_Barrel_EIC.C
References G4BARREL::SETTING::BARRELV0, G4BARREL::SETTING::BARRELV1, G4BARREL::SETTING::BARRELV2, G4BARREL::SETTING::BARRELV3, G4BARREL::SETTING::BARRELV4, G4BARREL::SETTING::BARRELV5, and G4BARREL::SETTING::BARRELV6.
Referenced by G4Init().
int make_barrel_pixel_layer (const string & name, PHG4Reco * g4Reco, double radius, double halflength, double tSilicon, double tAirgap)
Definition at line 162 of file G4_Barrel_EIC.C.
View newest version in sPHENIX GitHub at line 162 of file G4_Barrel_EIC.C
References Acts::UnitConstants::cm, Acts::UnitConstants::e, material(), Acts::UnitConstants::mm, PHG4DetectorSubsystem::OverlapCheck(), G4BECAL::radius, PHG4Reco::registerSubsystem(), PHG4DetectorSubsystem::set_double_param(), PHG4DetectorSubsystem::set_string_param(), PHG4DetectorSubsystem::SetActive(), PHG4DetectorSubsystem::SuperDetector(), thickness, Acts::UnitConstants::um, and PHG4Sector::Sector_Geometry::Unit_cm().
Referenced by Barrel().