EIC Software: eic-smear/blob/master/include/eicsmear/smear/functions.h File Reference
functions.h File Reference
#include <Rtypes.h>
#include <TString.h>
Namespaces
namespace Smear
Functions
int SmearTree (const Smear::Detector &, const TString &inFileName, const TString &outFileName="", Long64_t nEvents=-1)
Detailed Description
Declaration of smearing global functions.
Author
Michael Savastio
Date
2011-08-19
Copyright
2011 Brookhaven National Lab
Definition in file functions.h.
Function Documentation
int SmearTree (const Smear::Detector & detector, const TString & inFileName, const TString & outFileName, Long64_t nEvents)
Smear nEvents events from the TTree named EICTree in the named input file, using the smearing definitions in the Detector. Write the resulting Smeared TTree to a file named outFileName. If nEvents <= 0 smear all events in the tree. Returns 0 upon success, 1 upon failure.
Definition at line 44 of file SmearTree.cxx.
View newest version in sPHENIX GitHub at line 44 of file SmearTree.cxx
References erhic::VirtualEventFactory::Branch(), erhic::VirtualEventFactory::Fill(), and nEvents.
Referenced by main().