EIC Software: Quadrupole Class Reference
Quadrupole Class Reference
Public Member Functions
Quadrupole (std::string name, double k1l)
~Quadrupole ()
double GetGradient (void) const
void Calculate (double Brho)
void Print (void)
Public Member Functions inherited from MagElement
MagElement (std::string name)
~MagElement ()
virtual double GetField (void) const
virtual void WriteOut (FILE *fout)
Public Attributes
double mK1L
double mGradient
Public Attributes inherited from MagElement
std::string mName
double mApertureRadiusZin
double mApertureRadiusZout
double mOutsideDiameter
double mSstart
double mSend
double mTHETAstart
double mTHETAend
double mXstart
double mYstart
double mZstart
double mXend
double mYend
double mZend
double mLength
double mX
double mY
double mZ
double mTHETA
Detailed Description
Definition at line 103 of file extractor.cc.
View newest version in sPHENIX GitHub at line 103 of file extractor.cc
Constructor & Destructor Documentation
Quadrupole::Quadrupole (std::string name, double k1l) inline
Definition at line 105 of file extractor.cc.
View newest version in sPHENIX GitHub at line 105 of file extractor.cc
Quadrupole::~Quadrupole () inline
Definition at line 106 of file extractor.cc.
View newest version in sPHENIX GitHub at line 106 of file extractor.cc
Member Function Documentation
void Quadrupole::Calculate (double Brho) inline virtual
Implements MagElement.
Definition at line 109 of file extractor.cc.
View newest version in sPHENIX GitHub at line 109 of file extractor.cc
double Quadrupole::GetGradient (void) const inline virtual
Reimplemented from MagElement.
Definition at line 108 of file extractor.cc.
View newest version in sPHENIX GitHub at line 108 of file extractor.cc
void Quadrupole::Print (void) inline virtual
Reimplemented from MagElement.
Definition at line 110 of file extractor.cc.
View newest version in sPHENIX GitHub at line 110 of file extractor.cc
References MagElement::Print(), and printf().
Referenced by main().
Member Data Documentation
double Quadrupole::mGradient
Definition at line 114 of file extractor.cc.
View newest version in sPHENIX GitHub at line 114 of file extractor.cc
double Quadrupole::mK1L
Definition at line 110 of file extractor.cc.
View newest version in sPHENIX GitHub at line 110 of file extractor.cc
The documentation for this class was generated from the following file:
EicRoot/blob/master/pCDR-2018/madx/extractor.cc