EIC Software: g4lblvtx/blob/master/macros/auxiliary_studies/simplified_geometry/G4_DIRC_SMALL.C File Reference
G4_DIRC_SMALL.C File Reference
Macro setting up the barrel DIRC_SMALL.
#include <GlobalVariables.C>
#include <g4detectors/PHG4CylinderSubsystem.h>
#include <g4detectors/PHG4SectorSubsystem.h>
#include <g4main/PHG4Reco.h>
#include <cmath>
Namespaces
namespace Enable
namespace G4DIRC_SMALL
Macros
#define MACRO_G4DIRC_SMALL_C
Functions
void DIRCInit ()
double DIRCSetup (PHG4Reco *g4Reco)
Variables
bool Enable::DIRC_SMALL = false
bool Enable::DIRC_SMALL_OVERLAPCHECK = false
double G4DIRC_SMALL::radiator_R = 49.90
double G4DIRC_SMALL::length = 400
double G4DIRC_SMALL::z_shift = -75
double G4DIRC_SMALL::z_start = z_shift + length / 2.
double G4DIRC_SMALL::z_end = z_shift - length / 2.
double G4DIRC_SMALL::outer_skin_radius = 58
Detailed Description
Macro setting up the barrel DIRC_SMALL.
*
Author
Jin Huang jhuan.nosp@m.g@bn.nosp@m.l.gov
Version
Revision:
1.3
Date
Date:
2013/10/09 01:08:17
Definition in file G4_DIRC_SMALL.C.
Macro Definition Documentation
#define MACRO_G4DIRC_SMALL_C
Definition at line 2 of file G4_DIRC_SMALL.C.
View newest version in sPHENIX GitHub at line 2 of file G4_DIRC_SMALL.C
Function Documentation
void DIRCInit ()
Definition at line 39 of file G4_DIRC_SMALL.C.
View newest version in sPHENIX GitHub at line 39 of file G4_DIRC_SMALL.C
References max, BlackHoleGeometry::max_radius, BlackHoleGeometry::max_z, min, BlackHoleGeometry::min_z, G4DIRC_SMALL::outer_skin_radius, G4DIRC_SMALL::z_end, and G4DIRC_SMALL::z_start.
double DIRCSetup (PHG4Reco * g4Reco)
Babar DIRC_SMALL (Without most of support structure) Ref: I. Adam et al. The DIRC particle identification system for the BaBar experiment. Nucl. Instrum. Meth., A538:281-357, 2005. doi:10.1016/j.nima.2004.08.129.
Definition at line 49 of file G4_DIRC_SMALL.C.
View newest version in sPHENIX GitHub at line 49 of file G4_DIRC_SMALL.C
References PHG4Sector::Sector_Geometry::AddLayer(), Enable::DIRC_SMALL_OVERLAPCHECK, PHG4Sector::Sector_Geometry::FlatEdge(), PHG4SectorSubsystem::get_geometry(), G4DIRC_SMALL::length, M_PI, G4DIRC_SMALL::outer_skin_radius, Enable::OVERLAPCHECK, PHG4DetectorSubsystem::OverlapCheck(), PHG4Subsystem::OverlapCheck(), G4DIRC_SMALL::radiator_R, PHG4Reco::registerSubsystem(), PHG4DetectorSubsystem::set_double_param(), PHG4Sector::Sector_Geometry::set_material(), PHG4Sector::Sector_Geometry::set_max_polar_angle(), PHG4Sector::Sector_Geometry::set_max_polar_edge(), PHG4Sector::Sector_Geometry::set_min_polar_angle(), PHG4Sector::Sector_Geometry::set_min_polar_edge(), PHG4Sector::Sector_Geometry::set_N_Sector(), PHG4Sector::Sector_Geometry::set_normal_polar_angle(), PHG4Sector::Sector_Geometry::set_normal_start(), PHG4DetectorSubsystem::set_string_param(), PHG4DetectorSubsystem::SetActive(), PHG4DetectorSubsystem::SuperDetector(), PHG4Sector::Sector_Geometry::Unit_cm(), G4DIRC_SMALL::z_end, G4DIRC_SMALL::z_shift, and G4DIRC_SMALL::z_start.