EIC Software: G4JLeicVTXDetector Class Reference
G4JLeicVTXDetector Class Reference
#include <fun4all_eicdetectors/blob/master/simulation/g4simulation/g4jleic/G4JLeicVTXDetector.h>
Public Member Functions
G4JLeicVTXDetector (PHG4Subsystem *subsys, PHCompositeNode *Node, PHParametersContainer *params_array, const std::string &dnam)
constructor
virtual ~G4JLeicVTXDetector ()
destructor
virtual void ConstructMe (G4LogicalVolume *world)
construct
virtual void Print (const std::string &what="ALL") const
void SuperDetector (const std::string &name)
const std::string SuperDetector () const
G4JLeicVTXDetector (PHG4Subsystem *subsys, PHCompositeNode *Node, PHParametersContainer *params_array, const std::string &dnam)
constructor
virtual ~G4JLeicVTXDetector ()
destructor
virtual void ConstructMe (G4LogicalVolume *world)
construct
virtual void Print (const std::string &what="ALL") const
void SuperDetector (const std::string &name)
const std::string SuperDetector () const
volume accessors
int IsInVTX (G4VPhysicalVolume *) const
int IsInVTX (G4VPhysicalVolume *) const
Public Member Functions inherited from PHG4Detector
PHG4Detector ()=delete
constructor
PHG4Detector (PHG4Subsystem *subsys, PHCompositeNode *Node, const std::string &nam)
virtual ~PHG4Detector (void)
destructor
virtual void Construct (G4LogicalVolume *world) final
construct method
virtual void PostConstruction ()
Optional PostConstruction call after all geometry is constructed.
virtual void Verbosity (const int v)
virtual int Verbosity () const
virtual G4UserSteppingAction * GetSteppingAction ()
virtual std::string GetName () const
virtual void OverlapCheck (const bool chk)
virtual bool OverlapCheck () const
virtual int DisplayVolume (G4VSolid *volume, G4LogicalVolume *logvol, G4RotationMatrix *rotm=nullptr)
virtual int DisplayVolume (G4LogicalVolume *checksolid, G4LogicalVolume *logvol, G4RotationMatrix *rotm=nullptr)
virtual PHCompositeNode * topNode ()
virtual PHG4Subsystem * GetMySubsystem ()
Protected Attributes
int m_IsActiveFlag
int m_IsAbsorberActiveFlag
int m_Layers
PHParametersContainer * m_ParamsContainer
std::map< G4VPhysicalVolume
*, int > m_PhysicalVolumesMap
std::string m_SuperDetector
Additional Inherited Members
Static Public Member Functions inherited from PHG4Detector
static G4Material * GetDetectorMaterial (const std::string &name, const bool quit=true)
static G4Element * GetDetectorElement (const std::string &name, const bool quit=true)
Detailed Description
Definition at line 17 of file G4JLeicVTXDetector.h.
View newest version in sPHENIX GitHub at line 17 of file G4JLeicVTXDetector.h
Constructor & Destructor Documentation
G4JLeicVTXDetector::G4JLeicVTXDetector (PHG4Subsystem * subsys, PHCompositeNode * Node, PHParametersContainer * params_array, const std::string & dnam)
constructor
Definition at line 29 of file G4JLeicVTXDetector.cc.
View newest version in sPHENIX GitHub at line 29 of file G4JLeicVTXDetector.cc
References PHParameters::get_int_param(), PHParametersContainer::GetParameters(), m_IsAbsorberActiveFlag, m_IsActiveFlag, m_Layers, and m_ParamsContainer.
virtual G4JLeicVTXDetector::~G4JLeicVTXDetector () inline virtual
destructor
Definition at line 24 of file G4JLeicVTXDetector.h.
View newest version in sPHENIX GitHub at line 24 of file G4JLeicVTXDetector.h
G4JLeicVTXDetector::G4JLeicVTXDetector (PHG4Subsystem * subsys, PHCompositeNode * Node, PHParametersContainer * params_array, const std::string & dnam)
constructor
virtual G4JLeicVTXDetector::~G4JLeicVTXDetector () inline virtual
destructor
Definition at line 24 of file G4JLeicVTXDetector.h.
View newest version in sPHENIX GitHub at line 24 of file G4JLeicVTXDetector.h
Member Function Documentation
void G4JLeicVTXDetector::ConstructMe (G4LogicalVolume * world) virtual
construct
Implements PHG4Detector.
Definition at line 53 of file G4JLeicVTXDetector.cc.
View newest version in sPHENIX GitHub at line 53 of file G4JLeicVTXDetector.cc
References Acts::UnitConstants::cm, cos(), PHParameters::get_double_param(), PHG4Detector::GetDetectorMaterial(), PHParametersContainer::GetParameters(), m_Layers, m_ParamsContainer, m_PhysicalVolumesMap, M_PI, PHG4Detector::OverlapCheck(), phi, etm::solid, nlohmann::to_string(), x, and y.
virtual void G4JLeicVTXDetector::ConstructMe (G4LogicalVolume * world) virtual
construct
Implements PHG4Detector.
int G4JLeicVTXDetector::IsInVTX (G4VPhysicalVolume *) const
int G4JLeicVTXDetector::IsInVTX (G4VPhysicalVolume * volume) const
Definition at line 41 of file G4JLeicVTXDetector.cc.
View newest version in sPHENIX GitHub at line 41 of file G4JLeicVTXDetector.cc
References m_PhysicalVolumesMap.
Referenced by G4JLeicVTXSteppingAction::UserSteppingAction().
void G4JLeicVTXDetector::Print (const std::string & what = "ALL") const virtual
Reimplemented from PHG4Detector.
Definition at line 115 of file G4JLeicVTXDetector.cc.
View newest version in sPHENIX GitHub at line 115 of file G4JLeicVTXDetector.cc
Referenced by G4JLeicVTXSubsystem::Print().
virtual void G4JLeicVTXDetector::Print (const std::string & what = "ALL") const virtual
Reimplemented from PHG4Detector.
void G4JLeicVTXDetector::SuperDetector (const std::string & name) inline
Definition at line 36 of file G4JLeicVTXDetector.h.
View newest version in sPHENIX GitHub at line 36 of file G4JLeicVTXDetector.h
References m_SuperDetector, and name.
Referenced by G4JLeicVTXSubsystem::InitRunSubsystem(), and G4JLeicVTXSteppingAction::SetInterfacePointers().
void G4JLeicVTXDetector::SuperDetector (const std::string & name) inline
Definition at line 36 of file G4JLeicVTXDetector.h.
View newest version in sPHENIX GitHub at line 36 of file G4JLeicVTXDetector.h
References m_SuperDetector, and name.
const std::string G4JLeicVTXDetector::SuperDetector () const inline
Definition at line 37 of file G4JLeicVTXDetector.h.
View newest version in sPHENIX GitHub at line 37 of file G4JLeicVTXDetector.h
References m_SuperDetector.
const std::string G4JLeicVTXDetector::SuperDetector () const inline
Definition at line 37 of file G4JLeicVTXDetector.h.
View newest version in sPHENIX GitHub at line 37 of file G4JLeicVTXDetector.h
References m_SuperDetector.
Member Data Documentation
int G4JLeicVTXDetector::m_IsAbsorberActiveFlag protected
Definition at line 41 of file G4JLeicVTXDetector.h.
View newest version in sPHENIX GitHub at line 41 of file G4JLeicVTXDetector.h
Referenced by G4JLeicVTXDetector().
int G4JLeicVTXDetector::m_IsActiveFlag protected
Definition at line 40 of file G4JLeicVTXDetector.h.
View newest version in sPHENIX GitHub at line 40 of file G4JLeicVTXDetector.h
Referenced by G4JLeicVTXDetector().
int G4JLeicVTXDetector::m_Layers protected
Definition at line 42 of file G4JLeicVTXDetector.h.
View newest version in sPHENIX GitHub at line 42 of file G4JLeicVTXDetector.h
Referenced by ConstructMe(), and G4JLeicVTXDetector().
PHParametersContainer * G4JLeicVTXDetector::m_ParamsContainer protected
Definition at line 43 of file G4JLeicVTXDetector.h.
View newest version in sPHENIX GitHub at line 43 of file G4JLeicVTXDetector.h
Referenced by ConstructMe(), and G4JLeicVTXDetector().
std::map< G4VPhysicalVolume *, int > G4JLeicVTXDetector::m_PhysicalVolumesMap protected
Definition at line 44 of file G4JLeicVTXDetector.h.
View newest version in sPHENIX GitHub at line 44 of file G4JLeicVTXDetector.h
Referenced by ConstructMe(), and IsInVTX().
std::string G4JLeicVTXDetector::m_SuperDetector protected
Definition at line 46 of file G4JLeicVTXDetector.h.
View newest version in sPHENIX GitHub at line 46 of file G4JLeicVTXDetector.h
Referenced by SuperDetector().
The documentation for this class was generated from the following files:
fun4all_eicdetectors/blob/master/simulation/g4simulation/g4jleic/G4JLeicVTXDetector.h
fun4all_g4jleic/blob/master/source/G4JLeicVTXDetector.h
fun4all_eicdetectors/blob/master/simulation/g4simulation/g4jleic/G4JLeicVTXDetector.cc
fun4all_g4jleic/blob/master/source/G4JLeicVTXDetector.cc