EIC Software: FairDbRollbackDates Class Reference
FairDbRollbackDates Class Reference
#include <EicRoot/blob/master/dbase/dbInterface/FairDbRollbackDates.h>
Public Types
typedef std::map< std::string,
std::string > name_map_t
Public Member Functions
FairDbRollbackDates ()
virtual ~FairDbRollbackDates ()
const std::string & GetDate (const std::string &tableName) const
const std::string & GetType (const std::string &tableName) const
void Show () const
void Clear ()
void Set (FairRegistry &reg)
Private Attributes
name_map_t fTableToDate
Look-up table name -> date string.
name_map_t fTableToType
Look-up table name -> time type (either "INSERTDATE" [default] or "CREATIONDATE")
Detailed Description
Definition at line 15 of file FairDbRollbackDates.h.
View newest version in sPHENIX GitHub at line 15 of file FairDbRollbackDates.h
Member Typedef Documentation
typedef std::map<std::string,std::string> FairDbRollbackDates::name_map_t
Definition at line 20 of file FairDbRollbackDates.h.
View newest version in sPHENIX GitHub at line 20 of file FairDbRollbackDates.h
Constructor & Destructor Documentation
FairDbRollbackDates::FairDbRollbackDates ()
FairDbRollbackDates::~FairDbRollbackDates () virtual
Definition at line 19 of file FairDbRollbackDates.cxx.
View newest version in sPHENIX GitHub at line 19 of file FairDbRollbackDates.cxx
Member Function Documentation
void FairDbRollbackDates::Clear () inline
Definition at line 34 of file FairDbRollbackDates.h.
View newest version in sPHENIX GitHub at line 34 of file FairDbRollbackDates.h
References fTableToDate, and fTableToType.
Referenced by FairDbTableProxyRegistry::ClearRollbackDates().
const std::string & FairDbRollbackDates::GetDate (const std::string & tableName) const
Definition at line 24 of file FairDbRollbackDates.cxx.
View newest version in sPHENIX GitHub at line 24 of file FairDbRollbackDates.cxx
References FairUtilString::cmp_wildcard(), and fTableToDate.
Referenced by FairDbTableProxyRegistry::ApplySqlCondition().
const std::string & FairDbRollbackDates::GetType (const std::string & tableName) const
Definition at line 36 of file FairDbRollbackDates.cxx.
View newest version in sPHENIX GitHub at line 36 of file FairDbRollbackDates.cxx
References FairUtilString::cmp_wildcard(), and fTableToType.
Referenced by FairDbTableProxyRegistry::ApplySqlCondition().
void FairDbRollbackDates::Set (FairRegistry & reg)
Definition at line 49 of file FairDbRollbackDates.cxx.
View newest version in sPHENIX GitHub at line 49 of file FairDbRollbackDates.cxx
References fTableToDate, fTableToType, FairRegistry::Get(), FairDb::MakeDateTimeString(), FairDb::MakeTimeStamp(), FairRegistry::RemoveKey(), and Show().
Referenced by FairDbTableProxyRegistry::Config().
void FairDbRollbackDates::Show () const
Definition at line 117 of file FairDbRollbackDates.cxx.
View newest version in sPHENIX GitHub at line 117 of file FairDbRollbackDates.cxx
References fTableToDate, fTableToType, and name.
Referenced by Set().
Member Data Documentation
name_map_t FairDbRollbackDates::fTableToDate private
Look-up table name -> date string.
Definition at line 42 of file FairDbRollbackDates.h.
View newest version in sPHENIX GitHub at line 42 of file FairDbRollbackDates.h
Referenced by Clear(), GetDate(), Set(), and Show().
name_map_t FairDbRollbackDates::fTableToType private
Look-up table name -> time type (either "INSERTDATE" [default] or "CREATIONDATE")
Definition at line 44 of file FairDbRollbackDates.h.
View newest version in sPHENIX GitHub at line 44 of file FairDbRollbackDates.h
Referenced by Clear(), GetType(), Set(), and Show().
The documentation for this class was generated from the following files:
EicRoot/blob/master/dbase/dbInterface/FairDbRollbackDates.h
EicRoot/blob/master/dbase/dbInterface/FairDbRollbackDates.cxx