EIC Software: EICG4dRICHSteppingAction Class Reference
EICG4dRICHSteppingAction Class Reference
#include <fun4all_eicdetectors/blob/master/simulation/g4simulation/g4drich/EICG4dRICHSteppingAction.h>
Public Member Functions
EICG4dRICHSteppingAction (EICG4dRICHDetector *, const PHParameters *parameters)
constructor
virtual ~EICG4dRICHSteppingAction ()
destructor
virtual bool UserSteppingAction (const G4Step *, bool)
stepping action
virtual void SetInterfacePointers (PHCompositeNode *)
reimplemented from base class
Public Member Functions inherited from PHG4SteppingAction
PHG4SteppingAction (const std::string &name, const int i=0)
virtual ~PHG4SteppingAction ()
virtual void Verbosity (const int i)
virtual int Verbosity () const
virtual int Init ()
virtual double GetScintLightYield (const G4Step *step)
get scintillation photon count. It require a custom set SCINTILLATIONYIELD property to work
virtual double GetVisibleEnergyDeposition (const G4Step *step)
get amount of energy that can make scintillation light, in Unit of GeV.
virtual void StoreLocalCoordinate (PHG4Hit *hit, const G4Step *step, const bool do_prepoint, const bool do_postpoint)
Extract local coordinate of the hit and save to PHG4Hit.
virtual void Print (const std::string &) const
std::string GetName () const
void SetName (const std::string &name)
virtual void SetLightCorrection (const double inner_radius, const double inner_corr, const double outer_radius, const double outer_corr)
virtual double GetLightCorrection (const double r) const
virtual double GetLightCorrection (const double xpos, const double ypos) const
virtual bool ValidCorrection () const
virtual void SetHitNodeName (const std::string &, const std::string &)
Set the G4HIT node names from Subsystem rather than constructing your own.
Private Types
enum hitTypes {
hEntrance, hExit, hPSST, hIgnore,
nHitTypes
}
enum hitSubtypes {
entPrimary, entSecondary, entPostStep, exPrimary,
exSecondary, psOptical, psGamma, psOther,
subtypeUnknown, nHitSubtypes
}
Private Member Functions
void InitHit (const G4StepPoint *prePoint_, const G4Track *aTrack_, bool resetAccumulators)
method to initialize a new hit, resetting some things, such
Private Attributes
EICG4dRICHDetector * m_Detector
pointer to the detector
const PHParameters * m_Params
PHG4HitContainer * m_HitContainer
pointer to hit container
EICG4dRICHHit * m_Hit
PHG4HitContainer * m_SaveHitContainer
G4VPhysicalVolume * m_SaveVolPre
G4VPhysicalVolume * m_SaveVolPost
int m_SaveTrackId
int m_SavePreStepStatus
int m_SavePostStepStatus
int m_ActiveFlag
double m_EdepSum
double m_EionSum
int hitType
G4String hitTypeStr [nHitTypes]
int hitSubtype
G4String hitSubtypeStr [nHitSubtypes]
Detailed Description
Definition at line 18 of file EICG4dRICHSteppingAction.h.
View newest version in sPHENIX GitHub at line 18 of file EICG4dRICHSteppingAction.h
Member Enumeration Documentation
enum EICG4dRICHSteppingAction::hitSubtypes private
Enumerator:
entPrimary
entSecondary
entPostStep
exPrimary
exSecondary
psOptical
psGamma
psOther
subtypeUnknown
nHitSubtypes
Definition at line 69 of file EICG4dRICHSteppingAction.h.
View newest version in sPHENIX GitHub at line 69 of file EICG4dRICHSteppingAction.h
enum EICG4dRICHSteppingAction::hitTypes private
Enumerator:
hEntrance
hExit
hPSST
hIgnore
nHitTypes
Definition at line 58 of file EICG4dRICHSteppingAction.h.
View newest version in sPHENIX GitHub at line 58 of file EICG4dRICHSteppingAction.h
Constructor & Destructor Documentation
EICG4dRICHSteppingAction::EICG4dRICHSteppingAction (EICG4dRICHDetector * detector, const PHParameters * parameters)
constructor
Definition at line 43 of file EICG4dRICHSteppingAction.cc.
View newest version in sPHENIX GitHub at line 43 of file EICG4dRICHSteppingAction.cc
References entPostStep, entPrimary, entSecondary, exPrimary, exSecondary, hEntrance, hExit, hIgnore, hitSubtypeStr, hitTypeStr, hPSST, psGamma, psOptical, psOther, and subtypeUnknown.
EICG4dRICHSteppingAction::~EICG4dRICHSteppingAction () virtual
destructor
Definition at line 84 of file EICG4dRICHSteppingAction.cc.
View newest version in sPHENIX GitHub at line 84 of file EICG4dRICHSteppingAction.cc
References m_Hit.
Member Function Documentation
void EICG4dRICHSteppingAction::InitHit (const G4StepPoint * prePoint_, const G4Track * aTrack_, bool resetAccumulators) private
method to initialize a new hit, resetting some things, such
Definition at line 508 of file EICG4dRICHSteppingAction.cc.
View newest version in sPHENIX GitHub at line 508 of file EICG4dRICHSteppingAction.cc
References Acts::UnitConstants::cm, m_EdepSum, m_EionSum, m_Hit, m_HitContainer, m_SaveHitContainer, m_SaveTrackId, EICG4dRICHHit::set_position(), EICG4dRICHHit::set_t(), and EICG4dRICHHit::set_trkid().
Referenced by UserSteppingAction().
void EICG4dRICHSteppingAction::SetInterfacePointers (PHCompositeNode * topNode) virtual
reimplemented from base class
Reimplemented from PHG4SteppingAction.
Definition at line 527 of file EICG4dRICHSteppingAction.cc.
View newest version in sPHENIX GitHub at line 527 of file EICG4dRICHSteppingAction.cc
References PHG4Detector::GetName(), m_Detector, and m_HitContainer.
bool EICG4dRICHSteppingAction::UserSteppingAction (const G4Step * aStep, bool was_used) virtual
stepping action
Implements PHG4SteppingAction.
Definition at line 96 of file EICG4dRICHSteppingAction.cc.
View newest version in sPHENIX GitHub at line 96 of file EICG4dRICHSteppingAction.cc
References PHG4HitContainer::AddHit(), Acts::UnitConstants::cm, entPostStep, entPrimary, entSecondary, exPrimary, exSecondary, EICG4dRICHHit::get_hit_id(), EICG4dRICHHit::get_trkid(), EICG4dRICHHit::get_x(), PHG4HitContainer::GetID(), PHG4SteppingAction::GetName(), EICG4dRICHDetector::GetPetal(), EICG4dRICHDetector::GetPSST(), PHG4StepStatusDecode::GetStepStatus(), Acts::UnitConstants::GeV, hEntrance, hExit, hIgnore, hitSubtype, hitSubtypeStr, hitType, hitTypeStr, hPSST, InitHit(), EICG4dRICHDetector::IsInDetector(), m_Detector, m_EdepSum, m_EionSum, m_Hit, m_SaveHitContainer, m_SavePostStepStatus, m_SavePreStepStatus, m_SaveTrackId, m_SaveVolPost, m_SaveVolPre, p, psGamma, psOptical, psOther, EICG4dRICHHit::Reset(), EICG4dRICHHit::set_edep(), PHG4Hit::set_eion(), EICG4dRICHHit::set_hit_subtype_name(), EICG4dRICHHit::set_hit_type_name(), EICG4dRICHHit::set_momentum(), EICG4dRICHHit::set_momentum_dir(), EICG4dRICHHit::set_parent_id(), EICG4dRICHHit::set_particle_name(), EICG4dRICHHit::set_pdg(), EICG4dRICHHit::set_petal(), EICG4dRICHHit::set_position(), EICG4dRICHHit::set_process(), EICG4dRICHHit::set_psst(), EICG4dRICHHit::set_t(), EICG4dRICHHit::set_trkid(), EICG4dRICHHit::set_vertex_momentum_dir(), EICG4dRICHHit::set_vertex_position(), subtypeUnknown, PHG4SteppingAction::Verbosity(), and Fun4AllBase::VERBOSITY_MORE.
Member Data Documentation
int EICG4dRICHSteppingAction::hitSubtype private
Definition at line 68 of file EICG4dRICHSteppingAction.h.
View newest version in sPHENIX GitHub at line 68 of file EICG4dRICHSteppingAction.h
Referenced by UserSteppingAction().
G4String EICG4dRICHSteppingAction::hitSubtypeStr[nHitSubtypes] private
Definition at line 86 of file EICG4dRICHSteppingAction.h.
View newest version in sPHENIX GitHub at line 86 of file EICG4dRICHSteppingAction.h
Referenced by EICG4dRICHSteppingAction(), and UserSteppingAction().
int EICG4dRICHSteppingAction::hitType private
Definition at line 57 of file EICG4dRICHSteppingAction.h.
View newest version in sPHENIX GitHub at line 57 of file EICG4dRICHSteppingAction.h
Referenced by UserSteppingAction().
G4String EICG4dRICHSteppingAction::hitTypeStr[nHitTypes] private
Definition at line 66 of file EICG4dRICHSteppingAction.h.
View newest version in sPHENIX GitHub at line 66 of file EICG4dRICHSteppingAction.h
Referenced by EICG4dRICHSteppingAction(), and UserSteppingAction().
int EICG4dRICHSteppingAction::m_ActiveFlag private
Definition at line 52 of file EICG4dRICHSteppingAction.h.
View newest version in sPHENIX GitHub at line 52 of file EICG4dRICHSteppingAction.h
EICG4dRICHDetector* EICG4dRICHSteppingAction::m_Detector private
pointer to the detector
Definition at line 40 of file EICG4dRICHSteppingAction.h.
View newest version in sPHENIX GitHub at line 40 of file EICG4dRICHSteppingAction.h
Referenced by SetInterfacePointers(), and UserSteppingAction().
double EICG4dRICHSteppingAction::m_EdepSum private
Definition at line 53 of file EICG4dRICHSteppingAction.h.
View newest version in sPHENIX GitHub at line 53 of file EICG4dRICHSteppingAction.h
Referenced by InitHit(), and UserSteppingAction().
double EICG4dRICHSteppingAction::m_EionSum private
Definition at line 54 of file EICG4dRICHSteppingAction.h.
View newest version in sPHENIX GitHub at line 54 of file EICG4dRICHSteppingAction.h
Referenced by InitHit(), and UserSteppingAction().
EICG4dRICHHit* EICG4dRICHSteppingAction::m_Hit private
Definition at line 44 of file EICG4dRICHSteppingAction.h.
View newest version in sPHENIX GitHub at line 44 of file EICG4dRICHSteppingAction.h
Referenced by InitHit(), UserSteppingAction(), and ~EICG4dRICHSteppingAction().
PHG4HitContainer* EICG4dRICHSteppingAction::m_HitContainer private
pointer to hit container
Definition at line 43 of file EICG4dRICHSteppingAction.h.
View newest version in sPHENIX GitHub at line 43 of file EICG4dRICHSteppingAction.h
Referenced by InitHit(), and SetInterfacePointers().
const PHParameters* EICG4dRICHSteppingAction::m_Params private
Definition at line 41 of file EICG4dRICHSteppingAction.h.
View newest version in sPHENIX GitHub at line 41 of file EICG4dRICHSteppingAction.h
PHG4HitContainer* EICG4dRICHSteppingAction::m_SaveHitContainer private
Definition at line 45 of file EICG4dRICHSteppingAction.h.
View newest version in sPHENIX GitHub at line 45 of file EICG4dRICHSteppingAction.h
Referenced by InitHit(), and UserSteppingAction().
int EICG4dRICHSteppingAction::m_SavePostStepStatus private
Definition at line 51 of file EICG4dRICHSteppingAction.h.
View newest version in sPHENIX GitHub at line 51 of file EICG4dRICHSteppingAction.h
Referenced by UserSteppingAction().
int EICG4dRICHSteppingAction::m_SavePreStepStatus private
Definition at line 50 of file EICG4dRICHSteppingAction.h.
View newest version in sPHENIX GitHub at line 50 of file EICG4dRICHSteppingAction.h
Referenced by UserSteppingAction().
int EICG4dRICHSteppingAction::m_SaveTrackId private
Definition at line 49 of file EICG4dRICHSteppingAction.h.
View newest version in sPHENIX GitHub at line 49 of file EICG4dRICHSteppingAction.h
Referenced by InitHit(), and UserSteppingAction().
G4VPhysicalVolume* EICG4dRICHSteppingAction::m_SaveVolPost private
Definition at line 47 of file EICG4dRICHSteppingAction.h.
View newest version in sPHENIX GitHub at line 47 of file EICG4dRICHSteppingAction.h
Referenced by UserSteppingAction().
G4VPhysicalVolume* EICG4dRICHSteppingAction::m_SaveVolPre private
Definition at line 46 of file EICG4dRICHSteppingAction.h.
View newest version in sPHENIX GitHub at line 46 of file EICG4dRICHSteppingAction.h
Referenced by UserSteppingAction().
The documentation for this class was generated from the following files:
fun4all_eicdetectors/blob/master/simulation/g4simulation/g4drich/EICG4dRICHSteppingAction.h
fun4all_eicdetectors/blob/master/simulation/g4simulation/g4drich/EICG4dRICHSteppingAction.cc