EIC Software: Acts::LinearizedTrack Class Reference
Acts::LinearizedTrack Class Reference
#include <fun4all_acts/blob/master/Core/include/Acts/Vertexing/LinearizedTrack.hpp>
Public Member Functions
LinearizedTrack ()=default
Constructor taking perigee parameters and covariance matrix of track propagated to closest approach (PCA) of linearization point, position and momentum Jacobian and const term.
LinearizedTrack (const BoundVector &paramsAtPCA, const BoundSymMatrix &parCovarianceAtPCA, const BoundSymMatrix &parWeightAtPCA, const SpacePointVector &linPoint, const SpacePointToBoundMatrix &posJacobian, const ActsMatrixD< eBoundParametersSize, 3 > &momJacobian, const SpacePointVector &position, const Vector3D &momentum, const BoundVector &constTerm)
Public Attributes
BoundVector parametersAtPCA {BoundVector::Zero()}
BoundSymMatrix covarianceAtPCA {BoundSymMatrix::Zero()}
BoundSymMatrix weightAtPCA {BoundSymMatrix::Zero()}
SpacePointVector linearizationPoint {SpacePointVector::Zero()}
SpacePointToBoundMatrix positionJacobian {SpacePointToBoundMatrix::Zero()}
ActsMatrixD
< eBoundParametersSize, 3 > momentumJacobian
SpacePointVector positionAtPCA {SpacePointVector::Zero()}
Vector3D momentumAtPCA {Vector3D::Zero()}
BoundVector constantTerm {BoundVector::Zero()}
Detailed Description
Class for linear expansion of track parameters in vicinity of vertex
The measurement equation is linearized in the following way:
F_k= D_k (x_k - x_0k) + E_k (p_k - p_0k) + F^0_k
where F_k are the parameters at perigee nearest to the linearization point, x_k is the position of the vertex, p_k the track momentum at the vertex, and F^0_k is the constant term of expansion. D_k and E_k are matrices of derivatives, denoted hereafter as "positionJacobian" and "momentumJacobian" respectively.
Definition at line 30 of file LinearizedTrack.hpp.
View newest version in sPHENIX GitHub at line 30 of file LinearizedTrack.hpp
Constructor & Destructor Documentation
Acts::LinearizedTrack::LinearizedTrack () default
Constructor taking perigee parameters and covariance matrix of track propagated to closest approach (PCA) of linearization point, position and momentum Jacobian and const term.
Parameters
paramsAtPCA Parameters at point of closest approach
parCovarianceAtPCA Parameter covariance matrix at point of closest approach
linPoint Linearization point
posJacobian Position jacobian
momJacobian Momentum jacobian
position Position at point of closest approach
momentum Momentum at point of closest approach
constTerm Constant term in taylor expansion
Acts::LinearizedTrack::LinearizedTrack (const BoundVector & paramsAtPCA, const BoundSymMatrix & parCovarianceAtPCA, const BoundSymMatrix & parWeightAtPCA, const SpacePointVector & linPoint, const SpacePointToBoundMatrix & posJacobian, const ActsMatrixD< eBoundParametersSize, 3 > & momJacobian, const SpacePointVector & position, const Vector3D & momentum, const BoundVector & constTerm) inline
Definition at line 47 of file LinearizedTrack.hpp.
View newest version in sPHENIX GitHub at line 47 of file LinearizedTrack.hpp
Member Data Documentation
BoundVector Acts::LinearizedTrack::constantTerm {BoundVector::Zero()}
Definition at line 74 of file LinearizedTrack.hpp.
View newest version in sPHENIX GitHub at line 74 of file LinearizedTrack.hpp
Referenced by Acts::Test::BOOST_AUTO_TEST_CASE(), Acts::KalmanVertexUpdater::detail::trackParametersChi2(), and Acts::KalmanVertexUpdater::updatePosition().
BoundSymMatrix Acts::LinearizedTrack::covarianceAtPCA {BoundSymMatrix::Zero()}
Definition at line 66 of file LinearizedTrack.hpp.
View newest version in sPHENIX GitHub at line 66 of file LinearizedTrack.hpp
Referenced by Acts::Test::BOOST_AUTO_TEST_CASE().
SpacePointVector Acts::LinearizedTrack::linearizationPoint {SpacePointVector::Zero()}
Definition at line 68 of file LinearizedTrack.hpp.
View newest version in sPHENIX GitHub at line 68 of file LinearizedTrack.hpp
Referenced by Acts::Test::BOOST_AUTO_TEST_CASE().
Vector3D Acts::LinearizedTrack::momentumAtPCA {Vector3D::Zero()}
Definition at line 73 of file LinearizedTrack.hpp.
View newest version in sPHENIX GitHub at line 73 of file LinearizedTrack.hpp
ActsMatrixD<eBoundParametersSize, 3> Acts::LinearizedTrack::momentumJacobian
Initial value:
{
      ActsMatrixD<eBoundParametersSize, 3>::Zero()}
Definition at line 70 of file LinearizedTrack.hpp.
View newest version in sPHENIX GitHub at line 70 of file LinearizedTrack.hpp
Referenced by Acts::Test::BOOST_AUTO_TEST_CASE(), Acts::KalmanVertexUpdater::detail::trackParametersChi2(), and Acts::KalmanVertexUpdater::updatePosition().
BoundVector Acts::LinearizedTrack::parametersAtPCA {BoundVector::Zero()}
Definition at line 65 of file LinearizedTrack.hpp.
View newest version in sPHENIX GitHub at line 65 of file LinearizedTrack.hpp
Referenced by Acts::Test::BOOST_AUTO_TEST_CASE(), Acts::KalmanVertexUpdater::detail::trackParametersChi2(), and Acts::KalmanVertexUpdater::updatePosition().
SpacePointVector Acts::LinearizedTrack::positionAtPCA {SpacePointVector::Zero()}
Definition at line 72 of file LinearizedTrack.hpp.
View newest version in sPHENIX GitHub at line 72 of file LinearizedTrack.hpp
SpacePointToBoundMatrix Acts::LinearizedTrack::positionJacobian {SpacePointToBoundMatrix::Zero()}
Definition at line 69 of file LinearizedTrack.hpp.
View newest version in sPHENIX GitHub at line 69 of file LinearizedTrack.hpp
Referenced by Acts::Test::BOOST_AUTO_TEST_CASE(), Acts::KalmanVertexUpdater::detail::trackParametersChi2(), and Acts::KalmanVertexUpdater::updatePosition().
BoundSymMatrix Acts::LinearizedTrack::weightAtPCA {BoundSymMatrix::Zero()}
Definition at line 67 of file LinearizedTrack.hpp.
View newest version in sPHENIX GitHub at line 67 of file LinearizedTrack.hpp
Referenced by Acts::KalmanVertexUpdater::detail::trackParametersChi2(), and Acts::KalmanVertexUpdater::updatePosition().
The documentation for this class was generated from the following file:
fun4all_acts/blob/master/Core/include/Acts/Vertexing/LinearizedTrack.hpp