EIC Software: CbmGeoRichPar Class Reference
CbmGeoRichPar Class Reference
#include <EicRoot/blob/master/rich/CbmGeoRichPar.h>
Public Member Functions
CbmGeoRichPar (const char *name="CbmGeoRichPar", const char *title="Rich Geometry Parameters", const char *context="TestDefaultContext")
~CbmGeoRichPar (void)
void clear (void)
void putParams (FairParamList *)
Bool_t getParams (FairParamList *)
TObjArray * GetGeoSensitiveNodes ()
TObjArray * GetGeoPassiveNodes ()
Public Member Functions inherited from FairParGenericSet
FairParGenericSet (const char *name, const char *title, const char *context)
virtual ~FairParGenericSet ()
virtual void printParams ()
Bool_t init (FairParIo *inp)
Int_t write (FairParIo *output)
Public Member Functions inherited from FairParSet
FairParSet (const char *name="", const char *title="", const char *context="")
virtual ~FairParSet ()
virtual Bool_t init ()
virtual Int_t write ()
virtual void print ()
const char * getDetectorName ()
void resetInputVersions ()
void setInputVersion (Int_t v=-1, Int_t i=0)
Int_t getInputVersion (Int_t i)
void setStatic (Bool_t flag=kTRUE)
Bool_t isStatic ()
void setChanged (Bool_t flag=kTRUE)
Bool_t hasChanged ()
const char * getParamContext () const
void setAuthor (const char *s)
const char * getAuthor () const
void setDescription (const char *s)
const char * getDescription () const
void copyComment (FairParSet &r)
Public Attributes
TObjArray * fGeoSensNodes
TObjArray * fGeoPassNodes
Private Member Functions
CbmGeoRichPar (const CbmGeoRichPar &)
Copy constructor.
CbmGeoRichPar & operator= (const CbmGeoRichPar &)
Assignment operator.
Additional Inherited Members
Protected Member Functions inherited from FairParGenericSet
FairParGenericSet ()
Protected Attributes inherited from FairParSet
TString detName
Int_t versions [3]
name of the detector the container belongs to
Bool_t status
versions of container in the 2 possible inputs
Bool_t changed
static flag
TString paramContext
flag is kTRUE if parameters have changed
TString author
TString description
FairLogger * fLogger
Detailed Description
Author
Denis Bertini
Date
2005
Definition at line 25 of file CbmGeoRichPar.h.
View newest version in sPHENIX GitHub at line 25 of file CbmGeoRichPar.h
Constructor & Destructor Documentation
CbmGeoRichPar::CbmGeoRichPar (const char * name = "CbmGeoRichPar", const char * title = "Rich Geometry Parameters", const char * context = "TestDefaultContext")
CbmGeoRichPar::~CbmGeoRichPar (void)
Definition at line 31 of file CbmGeoRichPar.cxx.
View newest version in sPHENIX GitHub at line 31 of file CbmGeoRichPar.cxx
CbmGeoRichPar::CbmGeoRichPar (const CbmGeoRichPar &) private
Copy constructor.
Member Function Documentation
void CbmGeoRichPar::clear (void) virtual
Reimplemented from FairParSet.
Definition at line 35 of file CbmGeoRichPar.cxx.
View newest version in sPHENIX GitHub at line 35 of file CbmGeoRichPar.cxx
References fGeoPassNodes, and fGeoSensNodes.
TObjArray* CbmGeoRichPar::GetGeoPassiveNodes () inline
Definition at line 49 of file CbmGeoRichPar.h.
View newest version in sPHENIX GitHub at line 49 of file CbmGeoRichPar.h
References fGeoPassNodes.
Referenced by CbmRich::ConstructAsciiGeometry(), CbmRichProjectionProducer::Init(), CbmRichHitProducer::Init(), and CbmRichGeoTest::Init().
TObjArray* CbmGeoRichPar::GetGeoSensitiveNodes () inline
Definition at line 47 of file CbmGeoRichPar.h.
View newest version in sPHENIX GitHub at line 47 of file CbmGeoRichPar.h
References fGeoSensNodes.
Referenced by CbmRich::ConstructAsciiGeometry(), CbmRichProjectionProducer::Init(), CbmRichHitProducer::Init(), CbmRichTestHits::Init(), CbmRichTestSim::Init(), CbmRichGeoTest::Init(), and CbmRich::Initialize().
Bool_t CbmGeoRichPar::getParams (FairParamList * l) virtual
Implements FairParGenericSet.
Definition at line 49 of file CbmGeoRichPar.cxx.
View newest version in sPHENIX GitHub at line 49 of file CbmGeoRichPar.cxx
References fGeoPassNodes, fGeoSensNodes, and FairParamList::fillObject().
CbmGeoRichPar& CbmGeoRichPar::operator= (const CbmGeoRichPar &) private
Assignment operator.
void CbmGeoRichPar::putParams (FairParamList * l) virtual
Implements FairParGenericSet.
Definition at line 41 of file CbmGeoRichPar.cxx.
View newest version in sPHENIX GitHub at line 41 of file CbmGeoRichPar.cxx
References FairParamList::addObject(), fGeoPassNodes, and fGeoSensNodes.
Member Data Documentation
TObjArray* CbmGeoRichPar::fGeoPassNodes
Definition at line 30 of file CbmGeoRichPar.h.
View newest version in sPHENIX GitHub at line 30 of file CbmGeoRichPar.h
Referenced by clear(), GetGeoPassiveNodes(), getParams(), and putParams().
TObjArray* CbmGeoRichPar::fGeoSensNodes
Definition at line 29 of file CbmGeoRichPar.h.
View newest version in sPHENIX GitHub at line 29 of file CbmGeoRichPar.h
Referenced by clear(), GetGeoSensitiveNodes(), getParams(), and putParams().
The documentation for this class was generated from the following files:
EicRoot/blob/master/rich/CbmGeoRichPar.h
EicRoot/blob/master/rich/CbmGeoRichPar.cxx