EIC Software: Acts::CKFSourceLinkSelector Struct Reference
Acts::CKFSourceLinkSelector Struct Reference
This struct selects those source links compatible with the given track parameter against provided criteria.
#include <fun4all_acts/blob/master/Core/include/Acts/TrackFinder/CKFSourceLinkSelector.hpp>
Classes
struct Config
nested config struct
Public Member Functions
CKFSourceLinkSelector ()=default
Default constructor.
CKFSourceLinkSelector (Config cfg, std::shared_ptr< const Logger > logger=std::shared_ptr< const Logger >(getDefaultLogger("CKFSourceLinkSelector", Logging::INFO).release()))
Constructor with config and (non-owning) logger.
template<typename calibrator_t , typename source_link_t >
Result< void > operator() (const calibrator_t &calibrator, const BoundParameters &predictedParams, const std::vector< source_link_t > &sourcelinks, std::vector< std::pair< size_t, double >> &sourcelinkChi2, std::vector< size_t > &sourcelinkCandidateIndices, bool &isOutlier) const
Operater that select the source links compatible with the given track parameter on a surface.
const Logger & logger () const
Getter for the logger, to support logging macros.
Public Attributes
Config m_config
The config.
std::shared_ptr< const Logger > m_logger {nullptr}
Pointer to a logger that is owned by the parent, track finder.
Detailed Description
This struct selects those source links compatible with the given track parameter against provided criteria.
The selection criteria could be allowed maximum chi2 and allowed maximum number of source links on one surface
If there is no compatible source link, the source link with the mininum chi2 will be selected and the status will be tagged as an outlier
Definition at line 31 of file CKFSourceLinkSelector.hpp.
View newest version in sPHENIX GitHub at line 31 of file CKFSourceLinkSelector.hpp
Constructor & Destructor Documentation
Acts::CKFSourceLinkSelector::CKFSourceLinkSelector () default
Default constructor.
Acts::CKFSourceLinkSelector::CKFSourceLinkSelector (Config cfg, std::shared_ptr< const Logger > logger = std::shared_ptr<const Logger>(getDefaultLogger("CKFSourceLinkSelector", Logging::INFO).release())) inline
Constructor with config and (non-owning) logger.
Parameters
config a config instance
logger a logger instance
Definition at line 75 of file CKFSourceLinkSelector.hpp.
View newest version in sPHENIX GitHub at line 75 of file CKFSourceLinkSelector.hpp
Member Function Documentation
const Logger& Acts::CKFSourceLinkSelector::logger () const inline
Getter for the logger, to support logging macros.
Definition at line 276 of file CKFSourceLinkSelector.hpp.
View newest version in sPHENIX GitHub at line 276 of file CKFSourceLinkSelector.hpp
References m_logger.
template<typename calibrator_t , typename source_link_t > Result<void> Acts::CKFSourceLinkSelector::operator() (const calibrator_t & calibrator, const BoundParameters & predictedParams, const std::vector< source_link_t > & sourcelinks, std::vector< std::pair< size_t, double >> & sourcelinkChi2, std::vector< size_t > & sourcelinkCandidateIndices, bool & isOutlier) const inline
Operater that select the source links compatible with the given track parameter on a surface.
Template Parameters
calibrator_t The type of calibrator
source_link_t The type of source link
Parameters
calibrator The measurement calibrator
predictedParams The predicted track parameter on a surface
sourcelinks The pool of source links
sourcelinkChi2 The container for index and chi2 of intermediate source link candidates
sourcelinkCandidateIndices The container for index of final source link candidates
isOutlier The indicator for outlier or not
Definition at line 97 of file CKFSourceLinkSelector.hpp.
View newest version in sPHENIX GitHub at line 97 of file CKFSourceLinkSelector.hpp
References ACTS_DEBUG, ACTS_VERBOSE, Acts::SingleTrackParameters< ChargePolicy >::covariance(), Acts::GeometryObject::geoID(), H, Acts::CKFSourceLinkSelector::Config::layerMaxChi2, Acts::CKFSourceLinkSelector::Config::layerMaxNumSourcelinksOnSurface, m_config, max, Acts::CKFSourceLinkSelector::Config::maxChi2, Acts::CKFSourceLinkSelector::Config::maxNumSourcelinksOnSurface, min, Acts::SingleBoundTrackParameters< ChargePolicy >::referenceSurface(), Acts::GeometryID::volume(), Acts::CKFSourceLinkSelector::Config::volumeMaxChi2, and Acts::CKFSourceLinkSelector::Config::volumeMaxNumSourcelinksOnSurface.
Member Data Documentation
Config Acts::CKFSourceLinkSelector::m_config
The config.
Definition at line 270 of file CKFSourceLinkSelector.hpp.
View newest version in sPHENIX GitHub at line 270 of file CKFSourceLinkSelector.hpp
Referenced by operator()().
std::shared_ptr<const Logger> Acts::CKFSourceLinkSelector::m_logger {nullptr}
Pointer to a logger that is owned by the parent, track finder.
Definition at line 273 of file CKFSourceLinkSelector.hpp.
View newest version in sPHENIX GitHub at line 273 of file CKFSourceLinkSelector.hpp
Referenced by logger().
The documentation for this struct was generated from the following file:
fun4all_acts/blob/master/Core/include/Acts/TrackFinder/CKFSourceLinkSelector.hpp