EIC Software: EicCompositeShape Class Reference
EicCompositeShape Class Reference
#include <EicRoot/blob/master/eic/cad/EicCompositeShape.h>
Public Member Functions
EicCompositeShape ()
EicCompositeShape (const char *name, const char *expression, const TopoDS_Shape *solid)
~EicCompositeShape ()
Double_t Capacity () const
void ClearThreadData () const
TGeoBoolNode * GetBoolNode () const
void GetMeshNumbers (Int_t &nvert, Int_t &nsegs, Int_t &npols) const
Int_t GetNmeshVertices () const
Bool_t GetPointsOnSegments (Int_t iq, Double_t *dq) const
Bool_t IsComposite () const
void SetPoints (Double_t *points) const
Bool_t PaintComposite (Option_t *option="") const
void FillBuffer3D (TBuffer3D &buffer, Int_t reqSections, Bool_t localFrame) const
const TBuffer3D & GetBuffer3D (Int_t reqSections, Bool_t localFrame) const
int LocalFillBuffer3D (double stl_quality_coefficient)
void LocalSetPoints (Double_t *points) const
void LocalSetSegsAndPols (TBuffer3D &buff) const
Private Attributes
EicBuffer3D * mLocalBuffer3D
const TopoDS_Shape * mSolid
Detailed Description
Definition at line 50 of file EicCompositeShape.h.
View newest version in sPHENIX GitHub at line 50 of file EicCompositeShape.h
Constructor & Destructor Documentation
EicCompositeShape::EicCompositeShape () inline
Definition at line 52 of file EicCompositeShape.h.
View newest version in sPHENIX GitHub at line 52 of file EicCompositeShape.h
EicCompositeShape::EicCompositeShape (const char * name, const char * expression, const TopoDS_Shape * solid) inline
Definition at line 53 of file EicCompositeShape.h.
View newest version in sPHENIX GitHub at line 53 of file EicCompositeShape.h
References mLocalBuffer3D, mSolid, and etm::solid.
EicCompositeShape::~EicCompositeShape () inline
Definition at line 58 of file EicCompositeShape.h.
View newest version in sPHENIX GitHub at line 58 of file EicCompositeShape.h
Member Function Documentation
Double_t EicCompositeShape::Capacity () const inline
Definition at line 62 of file EicCompositeShape.h.
View newest version in sPHENIX GitHub at line 62 of file EicCompositeShape.h
void EicCompositeShape::ClearThreadData () const inline
Definition at line 63 of file EicCompositeShape.h.
View newest version in sPHENIX GitHub at line 63 of file EicCompositeShape.h
void EicCompositeShape::FillBuffer3D (TBuffer3D & buffer, Int_t reqSections, Bool_t localFrame) const
Definition at line 264 of file EicCompositeShape.cxx.
View newest version in sPHENIX GitHub at line 264 of file EicCompositeShape.cxx
References mLocalBuffer3D, Acts::Test::origin(), EicBuffer3D::xMax, EicBuffer3D::xMin, EicBuffer3D::yMax, EicBuffer3D::yMin, EicBuffer3D::zMax, and EicBuffer3D::zMin.
Referenced by GetBuffer3D().
TGeoBoolNode* EicCompositeShape::GetBoolNode () const inline
Definition at line 64 of file EicCompositeShape.h.
View newest version in sPHENIX GitHub at line 64 of file EicCompositeShape.h
const TBuffer3D & EicCompositeShape::GetBuffer3D (Int_t reqSections, Bool_t localFrame) const
Definition at line 295 of file EicCompositeShape.cxx.
View newest version in sPHENIX GitHub at line 295 of file EicCompositeShape.cxx
References buffer, FillBuffer3D(), LocalSetPoints(), LocalSetSegsAndPols(), mLocalBuffer3D, EicBuffer3D::NbPnts(), EicBuffer3D::NbPols(), and EicBuffer3D::NbSegs().
Referenced by PaintComposite().
void EicCompositeShape::GetMeshNumbers (Int_t & nvert, Int_t & nsegs, Int_t & npols) const inline
Definition at line 65 of file EicCompositeShape.h.
View newest version in sPHENIX GitHub at line 65 of file EicCompositeShape.h
Int_t EicCompositeShape::GetNmeshVertices () const inline
Definition at line 68 of file EicCompositeShape.h.
View newest version in sPHENIX GitHub at line 68 of file EicCompositeShape.h
Bool_t EicCompositeShape::GetPointsOnSegments (Int_t iq, Double_t * dq) const inline
Definition at line 69 of file EicCompositeShape.h.
View newest version in sPHENIX GitHub at line 69 of file EicCompositeShape.h
Bool_t EicCompositeShape::IsComposite () const inline
Definition at line 72 of file EicCompositeShape.h.
View newest version in sPHENIX GitHub at line 72 of file EicCompositeShape.h
int EicCompositeShape::LocalFillBuffer3D (double stl_quality_coefficient)
Definition at line 35 of file EicCompositeShape.cxx.
View newest version in sPHENIX GitHub at line 35 of file EicCompositeShape.cxx
References Add(), EicStlMediaGroup::assemblies(), EicStlFacet::edge(), EicStlKeyCompare(), EicStlMediaGroup::facets(), EicBuffer3D::fNbPnts, EicBuffer3D::fNbPols, EicBuffer3D::fNbSegs, EicBuffer3D::fPnts, EicBuffer3D::fPntsCapacity, EicBuffer3D::fPols, EicBuffer3D::fPolsCapacity, EicBuffer3D::fSegs, EicBuffer3D::fSegsCapacity, EicStlKey::GetData(), it, EicStlVertex::key(), EicStlFacetEdge::key(), EicStlFactory::mgroups(), mLocalBuffer3D, mSolid, EicStlFacet::mVbuffer, printf(), EicStlMediaGroup::SplitIntoAssemblies(), EicStlMediaGroup::vertices(), EicStlFacetEdge::vertices(), EicBuffer3D::xMax, EicBuffer3D::xMin, EicBuffer3D::yMax, EicBuffer3D::yMin, EicBuffer3D::zMax, and EicBuffer3D::zMin.
Referenced by EicCadWizard::CreateBooleanSolidRootFile(), and EicCadWizard::CreateGhostSolidRootFile().
void EicCompositeShape::LocalSetPoints (Double_t * points) const
Definition at line 219 of file EicCompositeShape.cxx.
View newest version in sPHENIX GitHub at line 219 of file EicCompositeShape.cxx
References EicBuffer3D::fNbPnts, EicBuffer3D::fPnts, and mLocalBuffer3D.
Referenced by GetBuffer3D().
void EicCompositeShape::LocalSetSegsAndPols (TBuffer3D & buff) const
Definition at line 233 of file EicCompositeShape.cxx.
View newest version in sPHENIX GitHub at line 233 of file EicCompositeShape.cxx
References c, EicBuffer3D::fNbPols, EicBuffer3D::fNbSegs, EicBuffer3D::fPols, EicBuffer3D::fSegs, and mLocalBuffer3D.
Referenced by GetBuffer3D().
Bool_t EicCompositeShape::PaintComposite (Option_t * option = "") const
Definition at line 331 of file EicCompositeShape.cxx.
View newest version in sPHENIX GitHub at line 331 of file EicCompositeShape.cxx
References GetBuffer3D(), and viewer().
void EicCompositeShape::SetPoints (Double_t * points) const inline
Definition at line 73 of file EicCompositeShape.h.
View newest version in sPHENIX GitHub at line 73 of file EicCompositeShape.h
Member Data Documentation
EicBuffer3D* EicCompositeShape::mLocalBuffer3D private
Definition at line 91 of file EicCompositeShape.h.
View newest version in sPHENIX GitHub at line 91 of file EicCompositeShape.h
Referenced by EicCompositeShape(), FillBuffer3D(), GetBuffer3D(), LocalFillBuffer3D(), LocalSetPoints(), and LocalSetSegsAndPols().
const TopoDS_Shape* EicCompositeShape::mSolid private
Definition at line 92 of file EicCompositeShape.h.
View newest version in sPHENIX GitHub at line 92 of file EicCompositeShape.h
Referenced by EicCompositeShape(), and LocalFillBuffer3D().
The documentation for this class was generated from the following files:
EicRoot/blob/master/eic/cad/EicCompositeShape.h
EicRoot/blob/master/eic/cad/EicCompositeShape.cxx