EIC Software: FairDbSimFlagAssociation Class Reference
FairDbSimFlagAssociation Class Reference
#include <EicRoot/blob/master/dbase/dbInterface/FairDbSimFlagAssociation.h>
Public Types
typedef list< SimFlag::SimFlag_t > SimList_t
typedef map
< SimFlag::SimFlag_t,
SimList_t > SimMap_t
Public Member Functions
FairDbSimFlagAssociation ()
virtual ~FairDbSimFlagAssociation ()
SimList_t Get (const SimFlag::SimFlag_t value) const
void Print (ostream &s) const
void Show ()
void Clear ()
void Set (const SimFlag::SimFlag_t value, SimList_t list)
void Set (FairRegistry &reg)
Static Public Member Functions
static const
FairDbSimFlagAssociation & Instance ()
Get access to the one and only instance.
Private Attributes
SimMap_t fAssociations
Static Private Attributes
static const
FairDbSimFlagAssociation * fgInstance
The one and only instance (owned by FairDbTableProxyFairRegistry).
Detailed Description
Definition at line 20 of file FairDbSimFlagAssociation.h.
View newest version in sPHENIX GitHub at line 20 of file FairDbSimFlagAssociation.h
Member Typedef Documentation
typedef list<SimFlag::SimFlag_t> FairDbSimFlagAssociation::SimList_t
Definition at line 27 of file FairDbSimFlagAssociation.h.
View newest version in sPHENIX GitHub at line 27 of file FairDbSimFlagAssociation.h
typedef map<SimFlag::SimFlag_t,SimList_t > FairDbSimFlagAssociation::SimMap_t
Definition at line 28 of file FairDbSimFlagAssociation.h.
View newest version in sPHENIX GitHub at line 28 of file FairDbSimFlagAssociation.h
Constructor & Destructor Documentation
FairDbSimFlagAssociation::FairDbSimFlagAssociation ()
Definition at line 29 of file FairDbSimFlagAssociation.cxx.
View newest version in sPHENIX GitHub at line 29 of file FairDbSimFlagAssociation.cxx
References fgInstance.
Referenced by Instance().
FairDbSimFlagAssociation::~FairDbSimFlagAssociation () virtual
Definition at line 40 of file FairDbSimFlagAssociation.cxx.
View newest version in sPHENIX GitHub at line 40 of file FairDbSimFlagAssociation.cxx
References fgInstance.
Member Function Documentation
void FairDbSimFlagAssociation::Clear () inline
Definition at line 45 of file FairDbSimFlagAssociation.h.
View newest version in sPHENIX GitHub at line 45 of file FairDbSimFlagAssociation.h
References fAssociations.
Referenced by FairDbTableProxyRegistry::ClearSimFlagAssociation().
FairDbSimFlagAssociation::SimList_t FairDbSimFlagAssociation::Get (const SimFlag::SimFlag_t value) const
Definition at line 49 of file FairDbSimFlagAssociation.cxx.
View newest version in sPHENIX GitHub at line 49 of file FairDbSimFlagAssociation.cxx
References fAssociations.
Referenced by ClassImp(), and FairDbCache::Search().
const FairDbSimFlagAssociation & FairDbSimFlagAssociation::Instance () static
Get access to the one and only instance.
Definition at line 61 of file FairDbSimFlagAssociation.cxx.
View newest version in sPHENIX GitHub at line 61 of file FairDbSimFlagAssociation.cxx
References FairDbSimFlagAssociation(), and fgInstance.
Referenced by ClassImp(), and FairDbCache::Search().
void FairDbSimFlagAssociation::Print (ostream & s) const
Definition at line 70 of file FairDbSimFlagAssociation.cxx.
View newest version in sPHENIX GitHub at line 70 of file FairDbSimFlagAssociation.cxx
References SimFlag::AsString(), fAssociations, n, name, v, and value.
void FairDbSimFlagAssociation::Set (const SimFlag::SimFlag_t value, SimList_t list) inline
Definition at line 46 of file FairDbSimFlagAssociation.h.
View newest version in sPHENIX GitHub at line 46 of file FairDbSimFlagAssociation.h
References fAssociations, charm_jet_coverage::list, and value.
Referenced by FairDbTableProxyRegistry::Config(), and Set().
void FairDbSimFlagAssociation::Set (FairRegistry & reg)
Definition at line 108 of file FairDbSimFlagAssociation.cxx.
View newest version in sPHENIX GitHub at line 108 of file FairDbSimFlagAssociation.cxx
References FairRegistry::Get(), SimFlag::kUnknown, configureMap::Name, FairRegistry::RemoveKey(), Set(), Show(), SimFlag::StringToEnum(), FairUtilString::StringTok(), v, and value.
void FairDbSimFlagAssociation::Show ()
Definition at line 156 of file FairDbSimFlagAssociation.cxx.
View newest version in sPHENIX GitHub at line 156 of file FairDbSimFlagAssociation.cxx
Referenced by Set().
Member Data Documentation
SimMap_t FairDbSimFlagAssociation::fAssociations private
Definition at line 58 of file FairDbSimFlagAssociation.h.
View newest version in sPHENIX GitHub at line 58 of file FairDbSimFlagAssociation.h
Referenced by Clear(), Get(), Print(), and Set().
const FairDbSimFlagAssociation* FairDbSimFlagAssociation::fgInstance static private
The one and only instance (owned by FairDbTableProxyFairRegistry).
Definition at line 54 of file FairDbSimFlagAssociation.h.
View newest version in sPHENIX GitHub at line 54 of file FairDbSimFlagAssociation.h
Referenced by FairDbSimFlagAssociation(), Instance(), and ~FairDbSimFlagAssociation().
The documentation for this class was generated from the following files:
EicRoot/blob/master/dbase/dbInterface/FairDbSimFlagAssociation.h
EicRoot/blob/master/dbase/dbInterface/FairDbSimFlagAssociation.cxx