EIC Software: EicRoot/blob/master/littrack/std/utils/CbmLitMatrixMath.h File Reference
CbmLitMatrixMath.h File Reference
#include "base/CbmLitFloat.h"
#include <vector>
Functions
bool InvSym15 (std::vector< litfloat > &a)
bool Mult25 (const std::vector< litfloat > &a, const std::vector< litfloat > &b, std::vector< litfloat > &c)
bool Mult25On5 (const std::vector< litfloat > &a, const std::vector< litfloat > &b, std::vector< litfloat > &c)
bool Mult15On5 (const std::vector< litfloat > &a, const std::vector< litfloat > &b, std::vector< litfloat > &c)
bool Transpose25 (std::vector< litfloat > &a)
bool Subtract (const std::vector< litfloat > &a, const std::vector< litfloat > &b, std::vector< litfloat > &c)
bool Add (const std::vector< litfloat > &a, const std::vector< litfloat > &b, std::vector< litfloat > &c)
bool Similarity (const std::vector< litfloat > &a, const std::vector< litfloat > &b, std::vector< litfloat > &c)
bool Mult15On25 (const std::vector< litfloat > &a, const std::vector< litfloat > &b, std::vector< litfloat > &c)
bool Mult25On15 (const std::vector< litfloat > &a, const std::vector< litfloat > &b, std::vector< litfloat > &c)
Function Documentation
bool Add (const std::vector< litfloat > & a, const std::vector< litfloat > & b, std::vector< litfloat > & c)
Definition at line 308 of file CbmLitMatrixMath.cxx.
View newest version in sPHENIX GitHub at line 308 of file CbmLitMatrixMath.cxx
Referenced by EicCadWizard::FaceGuidedSplit(), EicCadWizard::FlatSurfaceSplit(), and EicCompositeShape::LocalFillBuffer3D().
bool InvSym15 (std::vector< litfloat > & a)
Definition at line 41 of file CbmLitMatrixMath.cxx.
View newest version in sPHENIX GitHub at line 41 of file CbmLitMatrixMath.cxx
References SM00, SM01, SM02, SM03, SM04, SM10, SM11, SM12, SM13, SM14, SM20, SM21, SM22, SM23, SM24, SM30, SM31, SM32, SM33, SM34, SM40, SM41, SM42, SM43, and SM44.
bool Mult15On25 (const std::vector< litfloat > & a, const std::vector< litfloat > & b, std::vector< litfloat > & c)
Definition at line 385 of file CbmLitMatrixMath.cxx.
View newest version in sPHENIX GitHub at line 385 of file CbmLitMatrixMath.cxx
bool Mult15On5 (const std::vector< litfloat > & a, const std::vector< litfloat > & b, std::vector< litfloat > & c)
Definition at line 276 of file CbmLitMatrixMath.cxx.
View newest version in sPHENIX GitHub at line 276 of file CbmLitMatrixMath.cxx
bool Mult25 (const std::vector< litfloat > & a, const std::vector< litfloat > & b, std::vector< litfloat > & c)
Definition at line 182 of file CbmLitMatrixMath.cxx.
View newest version in sPHENIX GitHub at line 182 of file CbmLitMatrixMath.cxx
bool Mult25On15 (const std::vector< litfloat > & a, const std::vector< litfloat > & b, std::vector< litfloat > & c)
Definition at line 423 of file CbmLitMatrixMath.cxx.
View newest version in sPHENIX GitHub at line 423 of file CbmLitMatrixMath.cxx
bool Mult25On5 (const std::vector< litfloat > & a, const std::vector< litfloat > & b, std::vector< litfloat > & c)
Definition at line 259 of file CbmLitMatrixMath.cxx.
View newest version in sPHENIX GitHub at line 259 of file CbmLitMatrixMath.cxx
bool Similarity (const std::vector< litfloat > & a, const std::vector< litfloat > & b, std::vector< litfloat > & c)
Definition at line 323 of file CbmLitMatrixMath.cxx.
View newest version in sPHENIX GitHub at line 323 of file CbmLitMatrixMath.cxx
References Acts::UnitConstants::C, F, G, H, I, Acts::IntegrationTest::L, M, charm_jet_strange_helicity::N, Acts::IntegrationTest::R, and T.
Referenced by genfit::RKTrackRep::calcForwardJacobianAndNoise().
bool Subtract (const std::vector< litfloat > & a, const std::vector< litfloat > & b, std::vector< litfloat > & c)
Definition at line 293 of file CbmLitMatrixMath.cxx.
View newest version in sPHENIX GitHub at line 293 of file CbmLitMatrixMath.cxx
bool Transpose25 (std::vector< litfloat > & a)
Definition at line 222 of file CbmLitMatrixMath.cxx.
View newest version in sPHENIX GitHub at line 222 of file CbmLitMatrixMath.cxx