EIC Software: eventFileWriter Class Reference
eventFileWriter Class Reference
#include <estarlight/blob/master/include/eventfilewriter.h>
Public Member Functions
eventFileWriter ()
eventFileWriter (std::string filename)
int writeInit (inputParameters &param)
int writeInitLUND (inputParameters &param)
int writeEvent (eXEvent &event, int eventnumber)
int writeEventLUND (eXEvent &event, int eventnumber)
void writeFullPythiaInfo (bool v)
void writeFullHepMC3Info (bool v)
int close ()
Public Member Functions inherited from fileWriter
fileWriter ()
fileWriter (const std::string &fileName)
virtual ~fileWriter ()
int open ()
int open (const std::string &fileName)
void setFileName (const std::string &fileName)
Private Attributes
bool _writeFullPythia
bool _writeFullHepMC3
std::vector< double > _electronBeam_four_vector_
std::vector< double > _targetBeam_four_vector_
int _electronBeam_pdg_id_
int _targetBeam_pdg_id_
Additional Inherited Members
Protected Attributes inherited from fileWriter
std::string _fileName
std::ofstream _fileStream
Detailed Description
Definition at line 46 of file eventfilewriter.h.
View newest version in sPHENIX GitHub at line 46 of file eventfilewriter.h
Constructor & Destructor Documentation
eventFileWriter::eventFileWriter ()
Default constructor
Definition at line 47 of file eventfilewriter.cpp.
View newest version in sPHENIX GitHub at line 47 of file eventfilewriter.cpp
eventFileWriter::eventFileWriter (std::string filename)
Constructor with name
Definition at line 54 of file eventfilewriter.cpp.
View newest version in sPHENIX GitHub at line 54 of file eventfilewriter.cpp
Member Function Documentation
int eventFileWriter::close () virtual
Set if we want to write full lund information close the file
Reimplemented from fileWriter.
Definition at line 258 of file eventfilewriter.cpp.
View newest version in sPHENIX GitHub at line 258 of file eventfilewriter.cpp
References fileWriter::_fileStream, and _writeFullHepMC3.
Referenced by e_starlightStandalone::run().
int eventFileWriter::writeEvent (eXEvent & event, int eventnumber)
Write an eX event to file
Definition at line 113 of file eventfilewriter.cpp.
View newest version in sPHENIX GitHub at line 113 of file eventfilewriter.cpp
References fileWriter::_fileStream, _writeFullHepMC3, _writeFullPythia, lorentzVector::GetE(), eXEvent::getParticles(), lorentzVector::GetPx(), lorentzVector::GetPy(), lorentzVector::GetPz(), starlightParticleCodes::jetsetToGeant(), part, charm_jet_tagging_optimization_study::target, and vtx().
Referenced by e_starlightStandalone::run().
int eventFileWriter::writeEventLUND (eXEvent & event, int eventnumber)
Write an eX event to file in LUND format
Definition at line 189 of file eventfilewriter.cpp.
View newest version in sPHENIX GitHub at line 189 of file eventfilewriter.cpp
References _electronBeam_four_vector_, _electronBeam_pdg_id_, fileWriter::_fileStream, _targetBeam_four_vector_, _targetBeam_pdg_id_, lorentzVector::GetE(), eXEvent::getParticles(), lorentzVector::GetPx(), lorentzVector::GetPy(), lorentzVector::GetPz(), part, and charm_jet_tagging_optimization_study::target.
Referenced by e_starlightStandalone::run().
void eventFileWriter::writeFullHepMC3Info (bool v) inline
Set if we want to write full pythia information
Definition at line 72 of file eventfilewriter.h.
View newest version in sPHENIX GitHub at line 72 of file eventfilewriter.h
References _writeFullHepMC3, and v.
Referenced by e_starlightStandalone::run().
void eventFileWriter::writeFullPythiaInfo (bool v) inline
Set if we want to write full pythia information
Definition at line 69 of file eventfilewriter.h.
View newest version in sPHENIX GitHub at line 69 of file eventfilewriter.h
References _writeFullPythia, and v.
Referenced by e_starlightStandalone::run().
int eventFileWriter::writeInit (inputParameters & param)
Write out simulation set up
Definition at line 59 of file eventfilewriter.cpp.
View newest version in sPHENIX GitHub at line 59 of file eventfilewriter.cpp
References fileWriter::_fileStream, _writeFullHepMC3, inputParameters::electronBeamLorentzGamma(), inputParameters::fixedQ2Range(), inputParameters::impulseVM(), inputParameters::maxGammaQ2(), inputParameters::minGammaQ2(), inputParameters::nmbEnergyBins(), inputParameters::nmbEvents(), inputParameters::nmbGammaQ2Bins(), inputParameters::prodParticleId(), inputParameters::productionMode(), inputParameters::quantumGlauber(), inputParameters::randomSeed(), inputParameters::targetBeamA(), inputParameters::targetBeamLorentzGamma(), and inputParameters::targetBeamZ().
Referenced by e_starlightStandalone::run().
int eventFileWriter::writeInitLUND (inputParameters & param)
Write out LUND simulation set up
Definition at line 83 of file eventfilewriter.cpp.
View newest version in sPHENIX GitHub at line 83 of file eventfilewriter.cpp
References _electronBeam_four_vector_, _electronBeam_pdg_id_, fileWriter::_fileStream, _targetBeam_four_vector_, _targetBeam_pdg_id_, inputParameters::electronBeamLorentzGamma(), inputParameters::targetBeamA(), inputParameters::targetBeamLorentzGamma(), and inputParameters::targetBeamZ().
Referenced by e_starlightStandalone::run().
Member Data Documentation
std::vector<double> eventFileWriter::_electronBeam_four_vector_ private
Definition at line 86 of file eventfilewriter.h.
View newest version in sPHENIX GitHub at line 86 of file eventfilewriter.h
Referenced by writeEventLUND(), and writeInitLUND().
int eventFileWriter::_electronBeam_pdg_id_ private
Definition at line 88 of file eventfilewriter.h.
View newest version in sPHENIX GitHub at line 88 of file eventfilewriter.h
Referenced by writeEventLUND(), and writeInitLUND().
std::vector<double> eventFileWriter::_targetBeam_four_vector_ private
Definition at line 87 of file eventfilewriter.h.
View newest version in sPHENIX GitHub at line 87 of file eventfilewriter.h
Referenced by writeEventLUND(), and writeInitLUND().
int eventFileWriter::_targetBeam_pdg_id_ private
Definition at line 89 of file eventfilewriter.h.
View newest version in sPHENIX GitHub at line 89 of file eventfilewriter.h
Referenced by writeEventLUND(), and writeInitLUND().
bool eventFileWriter::_writeFullHepMC3 private
Definition at line 83 of file eventfilewriter.h.
View newest version in sPHENIX GitHub at line 83 of file eventfilewriter.h
Referenced by close(), writeEvent(), writeFullHepMC3Info(), and writeInit().
bool eventFileWriter::_writeFullPythia private
Definition at line 82 of file eventfilewriter.h.
View newest version in sPHENIX GitHub at line 82 of file eventfilewriter.h
Referenced by writeEvent(), and writeFullPythiaInfo().
The documentation for this class was generated from the following files:
estarlight/blob/master/include/eventfilewriter.h
estarlight/blob/master/src/eventfilewriter.cpp