EIC Software: PndRecoDafFit Class Reference
PndRecoDafFit Class Reference
#include <EicRoot/blob/master/GenfitTools/recotasks/PndRecoDafFit.h>
Public Member Functions
PndRecoDafFit ()
~PndRecoDafFit ()
void SetGeane (Bool_t opt=kTRUE)
void SetPropagateToIP (Bool_t opt=kTRUE)
void SetPerpPlane (Bool_t opt=kTRUE)
void SetNumIterations (Int_t num)
void SetTrackRep (Int_t num)
void SetVerbose (Int_t verb)
void SetMvdBranchName (const TString &name)
void SetCentralTrackerBranchName (const TString &name)
Bool_t Init ()
PndTrack * Fit (PndTrack *tBefore, Int_t PDG)
Private Member Functions
ClassDef (PndRecoDafFit, 0)
Verbose level.
Private Attributes
GFRecoHitFactory * fTheRecoHitFactory
GFDaf fGenFitter
FairGeanePro * fPro
TString fMvdBranchName
Geane Propagator.
TString fCentralTrackerBranchName
Name of the TCA for MVD.
Bool_t fUseGeane
Name of the TCA for central tracker.
Bool_t fPropagateToIP
Flag to use Geane.
Bool_t fPerpPlane
Flag to propagate to the interaction point.
Int_t fNumIt
Flag to use as initial plane the one perpendicular to the track.
Short_t fTrackRep
Number of iterations.
Int_t fVerbose
(0) GeaneTrackRep, 1 RKTrackRep
Detailed Description
Definition at line 31 of file PndRecoDafFit.h.
View newest version in sPHENIX GitHub at line 31 of file PndRecoDafFit.h
Constructor & Destructor Documentation
PndRecoDafFit::PndRecoDafFit ()
Definition at line 59 of file PndRecoDafFit.cxx.
View newest version in sPHENIX GitHub at line 59 of file PndRecoDafFit.cxx
References PndGeoHandling::Instance().
PndRecoDafFit::~PndRecoDafFit ()
Definition at line 102 of file PndRecoDafFit.cxx.
View newest version in sPHENIX GitHub at line 102 of file PndRecoDafFit.cxx
Member Function Documentation
PndRecoDafFit::ClassDef (PndRecoDafFit , 0) private
Verbose level.
PndTrack * PndRecoDafFit::Fit (PndTrack * tBefore, Int_t PDG)
Definition at line 104 of file PndRecoDafFit.cxx.
View newest version in sPHENIX GitHub at line 104 of file PndRecoDafFit.cxx
References GFTrack::addHitVector(), GFRecoHitFactory::createMany(), Acts::UnitConstants::e, fGenFitter, fPerpPlane, fPro, fPropagateToIP, fTheRecoHitFactory, fTrackRep, fVerbose, GenfitTrack2PndTrack(), GFTrack::getCand(), FairTrackPar::GetDPx(), FairTrackPar::GetDPy(), FairTrackPar::GetDPz(), FairTrackPar::GetDX(), FairTrackPar::GetDY(), FairTrackPar::GetDZ(), GFTrack::getNumHits(), PndTrack::GetParamFirst(), FairTrackPar::GetPx(), FairTrackPar::GetPy(), FairTrackPar::GetPz(), FairTrackPar::GetQ(), PndTrack::GetTrackCand(), FairTrackPar::GetX(), FairTrackParH::GetX(), FairTrackPar::GetY(), FairTrackParH::GetY(), FairTrackPar::GetZ(), FairTrackParH::GetZ(), PndTrackCand2GenfitTrackCand(), GFDaf::processTrack(), FairGeanePro::Propagate(), FairGeanePro::PropagateToPCA(), GFTrack::setCandidate(), PndTrack::SetFlag(), FairGeanePro::SetPoint(), GeaneTrackRep::setPropDir(), and GFException::what().
Referenced by PndRecoKalmanTask::Exec().
Bool_t PndRecoDafFit::Init (void)
Definition at line 66 of file PndRecoDafFit.cxx.
View newest version in sPHENIX GitHub at line 66 of file PndRecoDafFit.cxx
References fPro, fTheRecoHitFactory, fTrackRep, fUseGeane, fVerbose, GFFieldManager::getInstance(), GFFieldManager::init(), FairRootManager::Instance(), and GFException::quiet().
Referenced by PndRecoKalmanTask::Init().
void PndRecoDafFit::SetCentralTrackerBranchName (const TString & name) inline
Definition at line 47 of file PndRecoDafFit.h.
View newest version in sPHENIX GitHub at line 47 of file PndRecoDafFit.h
References fCentralTrackerBranchName, and name.
Referenced by PndRecoKalmanTask::Init().
void PndRecoDafFit::SetGeane (Bool_t opt = kTRUE) inline
Definition at line 40 of file PndRecoDafFit.h.
View newest version in sPHENIX GitHub at line 40 of file PndRecoDafFit.h
References fUseGeane.
Referenced by PndRecoKalmanTask::Init().
void PndRecoDafFit::SetMvdBranchName (const TString & name) inline
Definition at line 46 of file PndRecoDafFit.h.
View newest version in sPHENIX GitHub at line 46 of file PndRecoDafFit.h
References fMvdBranchName, and name.
Referenced by PndRecoKalmanTask::Init().
void PndRecoDafFit::SetNumIterations (Int_t num) inline
Definition at line 43 of file PndRecoDafFit.h.
View newest version in sPHENIX GitHub at line 43 of file PndRecoDafFit.h
References fNumIt, and num.
void PndRecoDafFit::SetPerpPlane (Bool_t opt = kTRUE) inline
Definition at line 42 of file PndRecoDafFit.h.
View newest version in sPHENIX GitHub at line 42 of file PndRecoDafFit.h
References fPerpPlane.
Referenced by PndRecoKalmanTask::Init().
void PndRecoDafFit::SetPropagateToIP (Bool_t opt = kTRUE) inline
Definition at line 41 of file PndRecoDafFit.h.
View newest version in sPHENIX GitHub at line 41 of file PndRecoDafFit.h
References fPropagateToIP.
Referenced by PndRecoKalmanTask::Init().
void PndRecoDafFit::SetTrackRep (Int_t num) inline
Definition at line 44 of file PndRecoDafFit.h.
View newest version in sPHENIX GitHub at line 44 of file PndRecoDafFit.h
References fTrackRep, and num.
Referenced by PndRecoKalmanTask::Init().
void PndRecoDafFit::SetVerbose (Int_t verb) inline
Definition at line 45 of file PndRecoDafFit.h.
View newest version in sPHENIX GitHub at line 45 of file PndRecoDafFit.h
References fVerbose.
Referenced by PndRecoKalmanTask::Init().
Member Data Documentation
TString PndRecoDafFit::fCentralTrackerBranchName private
Name of the TCA for MVD.
Definition at line 61 of file PndRecoDafFit.h.
View newest version in sPHENIX GitHub at line 61 of file PndRecoDafFit.h
Referenced by SetCentralTrackerBranchName().
GFDaf PndRecoDafFit::fGenFitter private
Definition at line 56 of file PndRecoDafFit.h.
View newest version in sPHENIX GitHub at line 56 of file PndRecoDafFit.h
Referenced by Fit().
TString PndRecoDafFit::fMvdBranchName private
Geane Propagator.
Definition at line 60 of file PndRecoDafFit.h.
View newest version in sPHENIX GitHub at line 60 of file PndRecoDafFit.h
Referenced by SetMvdBranchName().
Int_t PndRecoDafFit::fNumIt private
Flag to use as initial plane the one perpendicular to the track.
Definition at line 66 of file PndRecoDafFit.h.
View newest version in sPHENIX GitHub at line 66 of file PndRecoDafFit.h
Referenced by SetNumIterations().
Bool_t PndRecoDafFit::fPerpPlane private
Flag to propagate to the interaction point.
Definition at line 65 of file PndRecoDafFit.h.
View newest version in sPHENIX GitHub at line 65 of file PndRecoDafFit.h
Referenced by Fit(), and SetPerpPlane().
FairGeanePro* PndRecoDafFit::fPro private
Definition at line 58 of file PndRecoDafFit.h.
View newest version in sPHENIX GitHub at line 58 of file PndRecoDafFit.h
Referenced by Fit(), and Init().
Bool_t PndRecoDafFit::fPropagateToIP private
Flag to use Geane.
Definition at line 64 of file PndRecoDafFit.h.
View newest version in sPHENIX GitHub at line 64 of file PndRecoDafFit.h
Referenced by Fit(), and SetPropagateToIP().
GFRecoHitFactory* PndRecoDafFit::fTheRecoHitFactory private
Definition at line 55 of file PndRecoDafFit.h.
View newest version in sPHENIX GitHub at line 55 of file PndRecoDafFit.h
Referenced by Fit(), and Init().
Short_t PndRecoDafFit::fTrackRep private
Number of iterations.
Definition at line 67 of file PndRecoDafFit.h.
View newest version in sPHENIX GitHub at line 67 of file PndRecoDafFit.h
Referenced by Fit(), Init(), and SetTrackRep().
Bool_t PndRecoDafFit::fUseGeane private
Name of the TCA for central tracker.
Definition at line 63 of file PndRecoDafFit.h.
View newest version in sPHENIX GitHub at line 63 of file PndRecoDafFit.h
Referenced by Init(), and SetGeane().
Int_t PndRecoDafFit::fVerbose private
(0) GeaneTrackRep, 1 RKTrackRep
Definition at line 68 of file PndRecoDafFit.h.
View newest version in sPHENIX GitHub at line 68 of file PndRecoDafFit.h
Referenced by Fit(), Init(), and SetVerbose().
The documentation for this class was generated from the following files:
EicRoot/blob/master/GenfitTools/recotasks/PndRecoDafFit.h
EicRoot/blob/master/GenfitTools/recotasks/PndRecoDafFit.cxx