EIC Software: SvtxVertex Class Reference
SvtxVertex Class Reference
#include <fun4all_coresoftware/blob/master/offline/packages/trackbase_historic/SvtxVertex.h>
Public Types
typedef std::set< unsigned int > TrackSet
typedef std::set< unsigned int >
::const_iterator ConstTrackIter
typedef std::set< unsigned int >
::iterator TrackIter
Public Member Functions
~SvtxVertex () override
void identify (std::ostream &os=std::cout) const override
int isValid () const override
isValid returns non zero if object contains vailid data
PHObject * CloneMe () const override
Virtual copy constructor.
virtual unsigned int get_id () const
virtual void set_id (unsigned int)
virtual float get_t0 () const
virtual void set_t0 (float)
virtual float get_x () const
virtual void set_x (float)
virtual float get_y () const
virtual void set_y (float)
virtual float get_z () const
virtual void set_z (float)
virtual float get_chisq () const
virtual void set_chisq (float)
virtual unsigned int get_ndof () const
virtual void set_ndof (unsigned int)
virtual float get_position (unsigned int) const
virtual void set_position (unsigned int, float)
virtual float get_error (unsigned int, unsigned int) const
virtual void set_error (unsigned int, unsigned int, float)
virtual void clear_tracks ()
virtual bool empty_tracks ()
virtual size_t size_tracks () const
virtual void insert_track (unsigned int)
virtual size_t erase_track (unsigned int)
virtual ConstTrackIter begin_tracks () const
virtual ConstTrackIter find_track (unsigned int trackid) const
virtual ConstTrackIter end_tracks () const
virtual TrackIter begin_tracks ()
virtual TrackIter find_track (unsigned int trackid)
virtual TrackIter end_tracks ()
Public Member Functions inherited from PHObject
PHObject ()
ctor
~PHObject () override
dtor
virtual PHObject * clone () const final
PHObject * Clone (const char *newname="") const final
void Copy (TObject &object) const final
virtual void Reset ()
Clear Event.
virtual int isValid (const float) const
virtual int isValid (const double) const
virtual int isValid (const int) const
virtual int isValid (const unsigned int) const
virtual int isImplemented (const float f) const
virtual int isImplemented (const double f) const
virtual int isImplemented (const int i) const
virtual int isImplemented (const unsigned int i) const
virtual int Integrate () const
virtual int Integrate (PHObject *)
virtual void CopyFrom (const PHObject *obj)
Protected Member Functions
SvtxVertex ()
ClassDefOverride (SvtxVertex, 1)
Detailed Description
Definition at line 12 of file SvtxVertex.h.
View newest version in sPHENIX GitHub at line 12 of file SvtxVertex.h
Member Typedef Documentation
typedef std::set<unsigned int>::const_iterator SvtxVertex::ConstTrackIter
Definition at line 16 of file SvtxVertex.h.
View newest version in sPHENIX GitHub at line 16 of file SvtxVertex.h
typedef std::set<unsigned int>::iterator SvtxVertex::TrackIter
Definition at line 17 of file SvtxVertex.h.
View newest version in sPHENIX GitHub at line 17 of file SvtxVertex.h
typedef std::set<unsigned int> SvtxVertex::TrackSet
Definition at line 15 of file SvtxVertex.h.
View newest version in sPHENIX GitHub at line 15 of file SvtxVertex.h
Constructor & Destructor Documentation
SvtxVertex::~SvtxVertex () inline override
Definition at line 19 of file SvtxVertex.h.
View newest version in sPHENIX GitHub at line 19 of file SvtxVertex.h
SvtxVertex::SvtxVertex () inline protected
Definition at line 76 of file SvtxVertex.h.
View newest version in sPHENIX GitHub at line 76 of file SvtxVertex.h
Member Function Documentation
SvtxVertex::ConstTrackIter SvtxVertex::begin_tracks () const virtual
Reimplemented in SvtxVertex_v1.
Definition at line 5 of file SvtxVertex.cc.
View newest version in sPHENIX GitHub at line 5 of file SvtxVertex.cc
References DummyTrackSet.
Referenced by SvtxVertexEval::all_truth_particles(), B0TrackFastSimEval::fill_vertex_tree(), PHG4TrackFastSimEval::fill_vertex_tree(), TrackFastSimEval::fill_vertex_tree(), SvtxVertexEval::get_ntracks_contribution(), and QAG4SimulationVertex::process_event().
SvtxVertex::TrackIter SvtxVertex::begin_tracks () virtual
Reimplemented in SvtxVertex_v1.
Definition at line 20 of file SvtxVertex.cc.
View newest version in sPHENIX GitHub at line 20 of file SvtxVertex.cc
References DummyTrackSet.
SvtxVertex::ClassDefOverride (SvtxVertex , 1) protected
virtual void SvtxVertex::clear_tracks () inline virtual
Reimplemented in SvtxVertex_v1.
Definition at line 63 of file SvtxVertex.h.
View newest version in sPHENIX GitHub at line 63 of file SvtxVertex.h
PHObject* SvtxVertex::CloneMe () const inline override virtual
Virtual copy constructor.
Reimplemented from PHObject.
Reimplemented in SvtxVertex_v1.
Definition at line 29 of file SvtxVertex.h.
View newest version in sPHENIX GitHub at line 29 of file SvtxVertex.h
Referenced by SvtxVertexMap_v1::insert_clone().
virtual bool SvtxVertex::empty_tracks () inline virtual
Reimplemented in SvtxVertex_v1.
Definition at line 64 of file SvtxVertex.h.
View newest version in sPHENIX GitHub at line 64 of file SvtxVertex.h
SvtxVertex::ConstTrackIter SvtxVertex::end_tracks () const virtual
Reimplemented in SvtxVertex_v1.
Definition at line 15 of file SvtxVertex.cc.
View newest version in sPHENIX GitHub at line 15 of file SvtxVertex.cc
References DummyTrackSet.
Referenced by SvtxVertexEval::all_truth_particles(), B0TrackFastSimEval::fill_vertex_tree(), PHG4TrackFastSimEval::fill_vertex_tree(), TrackFastSimEval::fill_vertex_tree(), SvtxVertexEval::get_ntracks_contribution(), and QAG4SimulationVertex::process_event().
SvtxVertex::TrackIter SvtxVertex::end_tracks () virtual
Reimplemented in SvtxVertex_v1.
Definition at line 30 of file SvtxVertex.cc.
View newest version in sPHENIX GitHub at line 30 of file SvtxVertex.cc
References DummyTrackSet.
virtual size_t SvtxVertex::erase_track (unsigned int) inline virtual
Reimplemented in SvtxVertex_v1.
Definition at line 67 of file SvtxVertex.h.
View newest version in sPHENIX GitHub at line 67 of file SvtxVertex.h
SvtxVertex::ConstTrackIter SvtxVertex::find_track (unsigned int trackid) const virtual
Reimplemented in SvtxVertex_v1.
Definition at line 10 of file SvtxVertex.cc.
View newest version in sPHENIX GitHub at line 10 of file SvtxVertex.cc
References DummyTrackSet.
SvtxVertex::TrackIter SvtxVertex::find_track (unsigned int trackid) virtual
Reimplemented in SvtxVertex_v1.
Definition at line 25 of file SvtxVertex.cc.
View newest version in sPHENIX GitHub at line 25 of file SvtxVertex.cc
References DummyTrackSet.
virtual float SvtxVertex::get_chisq () const inline virtual
Reimplemented in SvtxVertex_v1.
Definition at line 48 of file SvtxVertex.h.
View newest version in sPHENIX GitHub at line 48 of file SvtxVertex.h
Referenced by SvtxEvaluator::fillOutputNtuples(), KFParticle_Tools::makeVertex(), GlobalVertexReco::process_event(), and PHGenFitTrkFitter::ReFitTrack().
virtual float SvtxVertex::get_error (unsigned int , unsigned int) const inline virtual
Reimplemented in SvtxVertex_v1.
Definition at line 57 of file SvtxVertex.h.
View newest version in sPHENIX GitHub at line 57 of file SvtxVertex.h
Referenced by B0TrackFastSimEval::fill_vertex_tree(), TrackFastSimEval::fill_vertex_tree(), PHG4TrackFastSimEval::fill_vertex_tree(), PHGenFitTrkFitter::MakeSvtxTrack(), KFParticle_Tools::makeVertex(), PHGenFitTrkProp::Process(), PHHybridSeeding::Process(), GlobalVertexReco::process_event(), PHGenFitTrkFitter::ReFitTrack(), RosenBrock(), and PHHoughSeeding::vertexing().
virtual unsigned int SvtxVertex::get_id () const inline virtual
Reimplemented in SvtxVertex_v1.
Definition at line 33 of file SvtxVertex.h.
View newest version in sPHENIX GitHub at line 33 of file SvtxVertex.h
Referenced by PHPatternReco::export_output(), B0TrackFastSimEval::fill_vertex_tree(), TrackFastSimEval::fill_vertex_tree(), PHG4TrackFastSimEval::fill_vertex_tree(), SvtxVertexMap_v1::operator=(), PHHybridSeeding::Process(), GlobalVertexReco::process_event(), and SvtxVertexMap_v1::SvtxVertexMap_v1().
virtual unsigned int SvtxVertex::get_ndof () const inline virtual
Reimplemented in SvtxVertex_v1.
Definition at line 51 of file SvtxVertex.h.
View newest version in sPHENIX GitHub at line 51 of file SvtxVertex.h
Referenced by SvtxEvaluator::fillOutputNtuples(), KFParticle_Tools::makeVertex(), GlobalVertexReco::process_event(), and PHGenFitTrkFitter::ReFitTrack().
virtual float SvtxVertex::get_position (unsigned int) const inline virtual
Reimplemented in SvtxVertex_v1.
Definition at line 54 of file SvtxVertex.h.
View newest version in sPHENIX GitHub at line 54 of file SvtxVertex.h
Referenced by PHPatternReco::export_output(), and GlobalVertexReco::process_event().
virtual float SvtxVertex::get_t0 () const inline virtual
Reimplemented in SvtxVertex_v1.
Definition at line 36 of file SvtxVertex.h.
View newest version in sPHENIX GitHub at line 36 of file SvtxVertex.h
virtual float SvtxVertex::get_x () const inline virtual
Reimplemented in SvtxVertex_v1.
Definition at line 39 of file SvtxVertex.h.
View newest version in sPHENIX GitHub at line 39 of file SvtxVertex.h
Referenced by ActsEvaluator::evaluateTrackFits(), B0TrackFastSimEval::fill_vertex_tree(), TrackFastSimEval::fill_vertex_tree(), PHG4TrackFastSimEval::fill_vertex_tree(), SvtxEvaluator::fillOutputNtuples(), EventEvaluator::fillOutputNtuples(), EventEvaluatorEIC::fillOutputNtuples(), PHRTreeSeeding::FillTree(), KFParticle_truthAndDetTools::fillTruthBranch(), PHActsTrackProjection::getVertex(), PHGenFitTrkFitter::MakeSvtxTrack(), KFParticle_Tools::makeVertex(), SvtxEvaluator::printOutputInfo(), PHGenFitTrkProp::Process(), PHSiliconTruthTrackSeeding::Process(), PHHybridSeeding::Process(), PHRTreeSeeding::Process(), QAG4SimulationVertex::process_event(), PHGenFitTrkFitter::process_event(), PHGenFitTrkFitter::ReFitTrack(), RosenBrock(), and PHHoughSeeding::vertexing().
virtual float SvtxVertex::get_y () const inline virtual
Reimplemented in SvtxVertex_v1.
Definition at line 42 of file SvtxVertex.h.
View newest version in sPHENIX GitHub at line 42 of file SvtxVertex.h
Referenced by ActsEvaluator::evaluateTrackFits(), B0TrackFastSimEval::fill_vertex_tree(), TrackFastSimEval::fill_vertex_tree(), PHG4TrackFastSimEval::fill_vertex_tree(), SvtxEvaluator::fillOutputNtuples(), EventEvaluator::fillOutputNtuples(), EventEvaluatorEIC::fillOutputNtuples(), PHRTreeSeeding::FillTree(), KFParticle_truthAndDetTools::fillTruthBranch(), PHActsTrackProjection::getVertex(), PHGenFitTrkFitter::MakeSvtxTrack(), KFParticle_Tools::makeVertex(), SvtxEvaluator::printOutputInfo(), PHGenFitTrkProp::Process(), PHSiliconTruthTrackSeeding::Process(), PHHybridSeeding::Process(), PHRTreeSeeding::Process(), QAG4SimulationVertex::process_event(), PHGenFitTrkFitter::process_event(), PHGenFitTrkFitter::ReFitTrack(), RosenBrock(), and PHHoughSeeding::vertexing().
virtual float SvtxVertex::get_z () const inline virtual
Reimplemented in SvtxVertex_v1.
Definition at line 45 of file SvtxVertex.h.
View newest version in sPHENIX GitHub at line 45 of file SvtxVertex.h
Referenced by ActsEvaluator::evaluateTrackFits(), B0TrackFastSimEval::fill_vertex_tree(), TrackFastSimEval::fill_vertex_tree(), PHG4TrackFastSimEval::fill_vertex_tree(), SvtxEvaluator::fillOutputNtuples(), EventEvaluator::fillOutputNtuples(), EventEvaluatorEIC::fillOutputNtuples(), PHRTreeSeeding::FillTree(), KFParticle_truthAndDetTools::fillTruthBranch(), PHActsTrackProjection::getVertex(), PHGenFitTrkFitter::MakeSvtxTrack(), KFParticle_Tools::makeVertex(), SvtxEvaluator::printOutputInfo(), PHGenFitTrkProp::Process(), PHSiliconTruthTrackSeeding::Process(), PHHybridSeeding::Process(), PHRTreeSeeding::Process(), QAG4SimulationVertex::process_event(), GlobalVertexReco::process_event(), PHGenFitTrkFitter::process_event(), PHGenFitTrkFitter::ReFitTrack(), RosenBrock(), and PHHoughSeeding::vertexing().
void SvtxVertex::identify (std::ostream & os = std::cout) const inline override virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from PHObject.
Reimplemented in SvtxVertex_v1.
Definition at line 23 of file SvtxVertex.h.
View newest version in sPHENIX GitHub at line 23 of file SvtxVertex.h
Referenced by PHInitZVertexing::export_output(), PHPatternReco::export_output(), PHHoughSeeding::export_output(), PHActsVertexFinder::fillVertexMap(), and SvtxEvaluator::printInputInfo().
virtual void SvtxVertex::insert_track (unsigned int) inline virtual
Reimplemented in SvtxVertex_v1.
Definition at line 66 of file SvtxVertex.h.
View newest version in sPHENIX GitHub at line 66 of file SvtxVertex.h
int SvtxVertex::isValid () const inline override virtual
isValid returns non zero if object contains vailid data
Reimplemented from PHObject.
Reimplemented in SvtxVertex_v1.
Definition at line 28 of file SvtxVertex.h.
View newest version in sPHENIX GitHub at line 28 of file SvtxVertex.h
virtual void SvtxVertex::set_chisq (float) inline virtual
Reimplemented in SvtxVertex_v1.
Definition at line 49 of file SvtxVertex.h.
View newest version in sPHENIX GitHub at line 49 of file SvtxVertex.h
Referenced by PHTruthVertexing::Process().
virtual void SvtxVertex::set_error (unsigned int , unsigned int , float) inline virtual
Reimplemented in SvtxVertex_v1.
Definition at line 58 of file SvtxVertex.h.
View newest version in sPHENIX GitHub at line 58 of file SvtxVertex.h
Referenced by PHTruthVertexing::Process().
virtual void SvtxVertex::set_id (unsigned int) inline virtual
Reimplemented in SvtxVertex_v1.
Definition at line 34 of file SvtxVertex.h.
View newest version in sPHENIX GitHub at line 34 of file SvtxVertex.h
Referenced by PHTruthVertexing::Process().
virtual void SvtxVertex::set_ndof (unsigned int) inline virtual
Reimplemented in SvtxVertex_v1.
Definition at line 52 of file SvtxVertex.h.
View newest version in sPHENIX GitHub at line 52 of file SvtxVertex.h
Referenced by PHTruthVertexing::Process().
virtual void SvtxVertex::set_position (unsigned int , float) inline virtual
Reimplemented in SvtxVertex_v1.
Definition at line 55 of file SvtxVertex.h.
View newest version in sPHENIX GitHub at line 55 of file SvtxVertex.h
virtual void SvtxVertex::set_t0 (float) inline virtual
Reimplemented in SvtxVertex_v1.
Definition at line 37 of file SvtxVertex.h.
View newest version in sPHENIX GitHub at line 37 of file SvtxVertex.h
Referenced by PHTruthVertexing::Process().
virtual void SvtxVertex::set_x (float) inline virtual
Reimplemented in SvtxVertex_v1.
Definition at line 40 of file SvtxVertex.h.
View newest version in sPHENIX GitHub at line 40 of file SvtxVertex.h
Referenced by PHTruthVertexing::Process(), and PHActsVertexFitter::updateSvtxVertex().
virtual void SvtxVertex::set_y (float) inline virtual
Reimplemented in SvtxVertex_v1.
Definition at line 43 of file SvtxVertex.h.
View newest version in sPHENIX GitHub at line 43 of file SvtxVertex.h
Referenced by PHTruthVertexing::Process().
virtual void SvtxVertex::set_z (float) inline virtual
Reimplemented in SvtxVertex_v1.
Definition at line 46 of file SvtxVertex.h.
View newest version in sPHENIX GitHub at line 46 of file SvtxVertex.h
Referenced by PHTruthVertexing::Process().
virtual size_t SvtxVertex::size_tracks () const inline virtual
Reimplemented in SvtxVertex_v1.
Definition at line 65 of file SvtxVertex.h.
View newest version in sPHENIX GitHub at line 65 of file SvtxVertex.h
Referenced by B0TrackFastSimEval::fill_vertex_tree(), TrackFastSimEval::fill_vertex_tree(), PHG4TrackFastSimEval::fill_vertex_tree(), SvtxEvaluator::fillOutputNtuples(), EventEvaluator::fillOutputNtuples(), EventEvaluatorEIC::fillOutputNtuples(), QAG4SimulationVertex::process_event(), PHGenFitTrkFitter::ReFitTrack(), and PHHoughSeeding::vertexing().
The documentation for this class was generated from the following files:
fun4all_coresoftware/blob/master/offline/packages/trackbase_historic/SvtxVertex.h
fun4all_coresoftware/blob/master/offline/packages/trackbase_historic/SvtxVertex.cc