EIC Software: FairUtilString Namespace Reference
FairUtilString Namespace Reference
Functions
Bool_t atob (const Char_t *s)
Bool_t atob (const Char_t *s, Bool_t &isvalid)
Int_t cmp_nocase (const std::string &s1, const std::string &s2)
Int_t cmp_wildcard (const std::string &s, const std::string &w)
void MakePrintable (const Char_t *in, std::string &out)
void StringTok (std::vector< std::string > &ls, const std::string &str, const std::string &tok)
Bool_t IsBool (const Char_t *s)
Bool_t IsInt (const Char_t *s)
Bool_t IsFloat (const Char_t *s)
std::string ToLower (const std::string &str)
std::string ToUpper (const std::string &str)
template<class T >
std::string ToString (const T &t, std::ios_base &(*f)(std::ios_base &)=std::dec)
Function Documentation
Bool_t FairUtilString::atob (const Char_t * s)
Definition at line 160 of file FairDbString.cxx.
View newest version in sPHENIX GitHub at line 160 of file FairDbString.cxx
References value.
Referenced by IsBool(), and FairDbConf::StringToRegistry().
Bool_t FairUtilString::atob (const Char_t * s, Bool_t & isvalid)
Definition at line 173 of file FairDbString.cxx.
View newest version in sPHENIX GitHub at line 173 of file FairDbString.cxx
References v.
Int_t FairUtilString::cmp_nocase (const std::string & s1, const std::string & s2)
Definition at line 198 of file FairDbString.cxx.
View newest version in sPHENIX GitHub at line 198 of file FairDbString.cxx
Int_t FairUtilString::cmp_wildcard (const std::string & s, const std::string & w)
Definition at line 212 of file FairDbString.cxx.
View newest version in sPHENIX GitHub at line 212 of file FairDbString.cxx
Referenced by FairDbRollbackDates::GetDate(), and FairDbRollbackDates::GetType().
Bool_t FairUtilString::IsBool (const Char_t * s)
Definition at line 154 of file FairDbString.cxx.
View newest version in sPHENIX GitHub at line 154 of file FairDbString.cxx
References atob().
Referenced by FairDbConf::StringToRegistry().
Bool_t FairUtilString::IsFloat (const Char_t * s)
Definition at line 145 of file FairDbString.cxx.
View newest version in sPHENIX GitHub at line 145 of file FairDbString.cxx
References d.
Referenced by FairDbConf::StringToRegistry().
Bool_t FairUtilString::IsInt (const Char_t * s)
Definition at line 131 of file FairDbString.cxx.
View newest version in sPHENIX GitHub at line 131 of file FairDbString.cxx
References d.
Referenced by FairDbConf::StringToRegistry().
void FairUtilString::MakePrintable (const Char_t * in, std::string & out)
Definition at line 60 of file FairDbString.cxx.
View newest version in sPHENIX GitHub at line 60 of file FairDbString.cxx
References c, and in.
Referenced by FairDbResultSet::RowAsCsv(), and FairDbOutRowStream::Store().
void FairUtilString::StringTok (std::vector< std::string > & ls, const std::string & str, const std::string & tok)
Definition at line 103 of file FairDbString.cxx.
View newest version in sPHENIX GitHub at line 103 of file FairDbString.cxx
Referenced by ClassImp(), FairDbSqlValPacket::Fill(), FairDbSqlValPacket::GetStmtValues(), FairDbSimFlagAssociation::Set(), FairDbTableProxyRegistry::SetConfigFromEnvironment(), and FairDbStatement::TranslateSQL().
std::string FairUtilString::ToLower (const std::string & str)
Definition at line 231 of file FairDbString.cxx.
View newest version in sPHENIX GitHub at line 231 of file FairDbString.cxx
Referenced by EicDetName::EicDetName().
template<class T > std::string FairUtilString::ToString (const T & t, std::ios_base &(*)(std::ios_base &) f = std::dec)
Definition at line 41 of file FairDbString.h.
View newest version in sPHENIX GitHub at line 41 of file FairDbString.h
References t.
std::string FairUtilString::ToUpper (const std::string & str)
Definition at line 220 of file FairDbString.cxx.
View newest version in sPHENIX GitHub at line 220 of file FairDbString.cxx
Referenced by FairDbMultConnector::CreateTemporaryTable(), EicDetName::EicDetName(), FairDbTableProxyRegistry::GetTableProxy(), FairDbProxy::StoreMetaData(), and FairDbRowStream::TableName().