EIC Software: PndPidProbability Class Reference
PndPidProbability Class Reference
#include <EicRoot/blob/master/pnddata/PidData/PndPidProbability.h>
Public Member Functions
PndPidProbability ()
PndPidProbability (Double_t e, Double_t mu, Double_t pi, Double_t k, Double_t p, Int_t idx=-1)
~PndPidProbability ()
Double_t GetElectronPdf () const
Double_t GetMuonPdf () const
Double_t GetPionPdf () const
Double_t GetKaonPdf () const
Double_t GetProtonPdf () const
Int_t GetIndex () const
Double_t GetElectronPidProb (PndPidProbability *flux=NULL) const
Double_t GetMuonPidProb (PndPidProbability *flux=NULL) const
Double_t GetPionPidProb (PndPidProbability *flux=NULL) const
Double_t GetKaonPidProb (PndPidProbability *flux=NULL) const
Double_t GetProtonPidProb (PndPidProbability *flux=NULL) const
Double_t GetSumProb (PndPidProbability *flux=NULL) const
void NormalizeTo (Double_t N=1.)
void SetElectronPdf (Double_t val)
void SetMuonPdf (Double_t val)
void SetPionPdf (Double_t val)
void SetKaonPdf (Double_t val)
void SetProtonPdf (Double_t val)
void SetIndex (Int_t idx)
PndPidProbability & operator*= (const PndPidProbability &a)
PndPidProbability operator* (const PndPidProbability &a)
void Print ()
void Reset ()
Protected Attributes
Double_t fElectronPdf
Double_t fMuonPdf
Double_t fPionPdf
Double_t fKaonPdf
Double_t fProtonPdf
Int_t fIndex
Detailed Description
Definition at line 16 of file PndPidProbability.h.
View newest version in sPHENIX GitHub at line 16 of file PndPidProbability.h
Constructor & Destructor Documentation
PndPidProbability::PndPidProbability ()
Definition at line 14 of file PndPidProbability.cxx.
View newest version in sPHENIX GitHub at line 14 of file PndPidProbability.cxx
References fElectronPdf, fIndex, fKaonPdf, fMuonPdf, fPionPdf, and fProtonPdf.
Referenced by GetElectronPidProb(), GetKaonPidProb(), GetMuonPidProb(), GetPionPidProb(), GetProtonPidProb(), GetSumProb(), and operator*().
PndPidProbability::PndPidProbability (Double_t e, Double_t mu, Double_t pi, Double_t k, Double_t p, Int_t idx = -1)
Definition at line 24 of file PndPidProbability.cxx.
View newest version in sPHENIX GitHub at line 24 of file PndPidProbability.cxx
References Acts::UnitConstants::e, fElectronPdf, fIndex, fKaonPdf, fMuonPdf, fPionPdf, fProtonPdf, k, p, and pi.
PndPidProbability::~PndPidProbability ()
Definition at line 34 of file PndPidProbability.cxx.
View newest version in sPHENIX GitHub at line 34 of file PndPidProbability.cxx
Member Function Documentation
Double_t PndPidProbability::GetElectronPdf () const inline
Definition at line 25 of file PndPidProbability.h.
View newest version in sPHENIX GitHub at line 25 of file PndPidProbability.h
References fElectronPdf.
Referenced by operator*(), and operator*=().
Double_t PndPidProbability::GetElectronPidProb (PndPidProbability * flux = NULL) const inline
Definition at line 32 of file PndPidProbability.h.
View newest version in sPHENIX GitHub at line 32 of file PndPidProbability.h
References fElectronPdf, GetSumProb(), and PndPidProbability().
Int_t PndPidProbability::GetIndex () const inline
Definition at line 30 of file PndPidProbability.h.
View newest version in sPHENIX GitHub at line 30 of file PndPidProbability.h
References fIndex.
Referenced by operator*().
Double_t PndPidProbability::GetKaonPdf () const inline
Definition at line 28 of file PndPidProbability.h.
View newest version in sPHENIX GitHub at line 28 of file PndPidProbability.h
References fKaonPdf.
Referenced by operator*(), and operator*=().
Double_t PndPidProbability::GetKaonPidProb (PndPidProbability * flux = NULL) const inline
Definition at line 35 of file PndPidProbability.h.
View newest version in sPHENIX GitHub at line 35 of file PndPidProbability.h
References fKaonPdf, GetSumProb(), and PndPidProbability().
Double_t PndPidProbability::GetMuonPdf () const inline
Definition at line 26 of file PndPidProbability.h.
View newest version in sPHENIX GitHub at line 26 of file PndPidProbability.h
References fMuonPdf.
Referenced by operator*(), and operator*=().
Double_t PndPidProbability::GetMuonPidProb (PndPidProbability * flux = NULL) const inline
Definition at line 33 of file PndPidProbability.h.
View newest version in sPHENIX GitHub at line 33 of file PndPidProbability.h
References fMuonPdf, GetSumProb(), and PndPidProbability().
Double_t PndPidProbability::GetPionPdf () const inline
Definition at line 27 of file PndPidProbability.h.
View newest version in sPHENIX GitHub at line 27 of file PndPidProbability.h
References fPionPdf.
Referenced by operator*(), and operator*=().
Double_t PndPidProbability::GetPionPidProb (PndPidProbability * flux = NULL) const inline
Definition at line 34 of file PndPidProbability.h.
View newest version in sPHENIX GitHub at line 34 of file PndPidProbability.h
References fPionPdf, GetSumProb(), and PndPidProbability().
Double_t PndPidProbability::GetProtonPdf () const inline
Definition at line 29 of file PndPidProbability.h.
View newest version in sPHENIX GitHub at line 29 of file PndPidProbability.h
References fProtonPdf.
Referenced by operator*(), and operator*=().
Double_t PndPidProbability::GetProtonPidProb (PndPidProbability * flux = NULL) const inline
Definition at line 36 of file PndPidProbability.h.
View newest version in sPHENIX GitHub at line 36 of file PndPidProbability.h
References fProtonPdf, GetSumProb(), and PndPidProbability().
Double_t PndPidProbability::GetSumProb (PndPidProbability * flux = NULL) const inline
Definition at line 38 of file PndPidProbability.h.
View newest version in sPHENIX GitHub at line 38 of file PndPidProbability.h
References fElectronPdf, fKaonPdf, fMuonPdf, fPionPdf, fProtonPdf, and PndPidProbability().
Referenced by GetElectronPidProb(), GetKaonPidProb(), GetMuonPidProb(), GetPionPidProb(), GetProtonPidProb(), and NormalizeTo().
void PndPidProbability::NormalizeTo (Double_t N = 1.)
Definition at line 80 of file PndPidProbability.cxx.
View newest version in sPHENIX GitHub at line 80 of file PndPidProbability.cxx
References fElectronPdf, fKaonPdf, fMuonPdf, fPionPdf, fProtonPdf, and GetSumProb().
PndPidProbability PndPidProbability::operator* (const PndPidProbability & a)
Definition at line 38 of file PndPidProbability.cxx.
View newest version in sPHENIX GitHub at line 38 of file PndPidProbability.cxx
References fElectronPdf, fKaonPdf, fMuonPdf, fPionPdf, fProtonPdf, GetElectronPdf(), GetIndex(), GetKaonPdf(), GetMuonPdf(), GetPionPdf(), GetProtonPdf(), and PndPidProbability().
PndPidProbability & PndPidProbability::operator*= (const PndPidProbability & a)
Definition at line 48 of file PndPidProbability.cxx.
View newest version in sPHENIX GitHub at line 48 of file PndPidProbability.cxx
References fElectronPdf, fKaonPdf, fMuonPdf, fPionPdf, fProtonPdf, GetElectronPdf(), GetKaonPdf(), GetMuonPdf(), GetPionPdf(), and GetProtonPdf().
void PndPidProbability::Print (void)
Definition at line 58 of file PndPidProbability.cxx.
View newest version in sPHENIX GitHub at line 58 of file PndPidProbability.cxx
References fElectronPdf, fIndex, fKaonPdf, fMuonPdf, fPionPdf, and fProtonPdf.
void PndPidProbability::Reset ()
Definition at line 70 of file PndPidProbability.cxx.
View newest version in sPHENIX GitHub at line 70 of file PndPidProbability.cxx
References fElectronPdf, fIndex, fKaonPdf, fMuonPdf, fPionPdf, and fProtonPdf.
void PndPidProbability::SetElectronPdf (Double_t val) inline
Definition at line 51 of file PndPidProbability.h.
View newest version in sPHENIX GitHub at line 51 of file PndPidProbability.h
References fElectronPdf.
void PndPidProbability::SetIndex (Int_t idx) inline
Definition at line 56 of file PndPidProbability.h.
View newest version in sPHENIX GitHub at line 56 of file PndPidProbability.h
References fIndex.
void PndPidProbability::SetKaonPdf (Double_t val) inline
Definition at line 54 of file PndPidProbability.h.
View newest version in sPHENIX GitHub at line 54 of file PndPidProbability.h
References fKaonPdf.
void PndPidProbability::SetMuonPdf (Double_t val) inline
Definition at line 52 of file PndPidProbability.h.
View newest version in sPHENIX GitHub at line 52 of file PndPidProbability.h
References fMuonPdf.
void PndPidProbability::SetPionPdf (Double_t val) inline
Definition at line 53 of file PndPidProbability.h.
View newest version in sPHENIX GitHub at line 53 of file PndPidProbability.h
References fPionPdf.
void PndPidProbability::SetProtonPdf (Double_t val) inline
Definition at line 55 of file PndPidProbability.h.
View newest version in sPHENIX GitHub at line 55 of file PndPidProbability.h
References fProtonPdf.
Member Data Documentation
Double_t PndPidProbability::fElectronPdf protected
Definition at line 65 of file PndPidProbability.h.
View newest version in sPHENIX GitHub at line 65 of file PndPidProbability.h
Referenced by GetElectronPdf(), GetElectronPidProb(), GetSumProb(), NormalizeTo(), operator*(), operator*=(), PndPidProbability(), Print(), Reset(), and SetElectronPdf().
Int_t PndPidProbability::fIndex protected
Definition at line 70 of file PndPidProbability.h.
View newest version in sPHENIX GitHub at line 70 of file PndPidProbability.h
Referenced by GetIndex(), PndPidProbability(), Print(), Reset(), and SetIndex().
Double_t PndPidProbability::fKaonPdf protected
Definition at line 68 of file PndPidProbability.h.
View newest version in sPHENIX GitHub at line 68 of file PndPidProbability.h
Referenced by GetKaonPdf(), GetKaonPidProb(), GetSumProb(), NormalizeTo(), operator*(), operator*=(), PndPidProbability(), Print(), Reset(), and SetKaonPdf().
Double_t PndPidProbability::fMuonPdf protected
Definition at line 66 of file PndPidProbability.h.
View newest version in sPHENIX GitHub at line 66 of file PndPidProbability.h
Referenced by GetMuonPdf(), GetMuonPidProb(), GetSumProb(), NormalizeTo(), operator*(), operator*=(), PndPidProbability(), Print(), Reset(), and SetMuonPdf().
Double_t PndPidProbability::fPionPdf protected
Definition at line 67 of file PndPidProbability.h.
View newest version in sPHENIX GitHub at line 67 of file PndPidProbability.h
Referenced by GetPionPdf(), GetPionPidProb(), GetSumProb(), NormalizeTo(), operator*(), operator*=(), PndPidProbability(), Print(), Reset(), and SetPionPdf().
Double_t PndPidProbability::fProtonPdf protected
Definition at line 69 of file PndPidProbability.h.
View newest version in sPHENIX GitHub at line 69 of file PndPidProbability.h
Referenced by GetProtonPdf(), GetProtonPidProb(), GetSumProb(), NormalizeTo(), operator*(), operator*=(), PndPidProbability(), Print(), Reset(), and SetProtonPdf().
The documentation for this class was generated from the following files:
EicRoot/blob/master/pnddata/PidData/PndPidProbability.h
EicRoot/blob/master/pnddata/PidData/PndPidProbability.cxx