EIC Software: EicRoot/blob/master/input/dipole.c File Reference
dipole.c File Reference
#include <stdio.h>
#include <assert.h>
#include <mgsystem.h>
Macros
#define _MAP_ID_ 1
#define _CELL_SIZE_ 2.5
Functions
static double tesla2gs_fun (double val)
void main (void)
Macro Definition Documentation
#define _CELL_SIZE_ 2.5
Definition at line 17 of file dipole.c.
View newest version in sPHENIX GitHub at line 17 of file dipole.c
Referenced by main().
#define _MAP_ID_ 1
Definition at line 14 of file dipole.c.
View newest version in sPHENIX GitHub at line 14 of file dipole.c
Referenced by main().
Function Documentation
void main (void)
Definition at line 24 of file dipole.c.
View newest version in sPHENIX GitHub at line 24 of file dipole.c
References _CARTESIAN_, _CELL_SIZE_, _MAP_ID_, _X_, _Y_, _Z_, exit(), import_ascii_field_map(), m2cm_fun(), printf(), tesla2gs_fun(), xmax, and xmin.
static double tesla2gs_fun (double val) static
Definition at line 19 of file dipole.c.
View newest version in sPHENIX GitHub at line 19 of file dipole.c
Referenced by main().