EIC Software: fun4all_eicmacros/blob/master/common/G4_GEM_EIC.C File Reference
G4_GEM_EIC.C File Reference
#include <GlobalVariables.C>
#include <g4detectors/PHG4SectorSubsystem.h>
#include <g4main/PHG4Reco.h>
#include <string>
Namespaces
namespace Enable
Macros
#define MACRO_G4GEMEIC_C
Functions
int make_GEM_station (string name, PHG4Reco *g4Reco, double zpos, double etamin, double etamax, const int N_Sector=8, double tilt=0, bool doTilt=false)
void AddLayers_MiniTPCDrift (PHG4SectorSubsystem *gem)
Add drift layers to mini TPC.
void EGEM_Init ()
void FGEM_Init ()
void EGEMSetup (PHG4Reco *g4Reco)
void FGEMSetup (PHG4Reco *g4Reco, const int N_Sector=8, const double min_eta=1.245)
void addPassiveMaterial (PHG4Reco *g4Reco)
Variables
bool Enable::EGEM = false
bool Enable::EGEM_FULL = false
bool Enable::FGEM_ORIG = false
Macro Definition Documentation
#define MACRO_G4GEMEIC_C
Definition at line 2 of file G4_GEM_EIC.C.
View newest version in sPHENIX GitHub at line 2 of file G4_GEM_EIC.C
Function Documentation
void AddLayers_MiniTPCDrift (PHG4SectorSubsystem * gem)
Add drift layers to mini TPC.
void addPassiveMaterial (PHG4Reco * g4Reco)
Definition at line 100 of file G4_GEM_EIC.C.
View newest version in sPHENIX GitHub at line 100 of file G4_GEM_EIC.C
References kdfinder::abs(), PHG4Reco::registerSubsystem(), PHG4DetectorSubsystem::set_double_param(), PHG4DetectorSubsystem::set_string_param(), and PHG4DetectorSubsystem::SuperDetector().
void EGEM_Init ()
Definition at line 25 of file G4_GEM_EIC.C.
View newest version in sPHENIX GitHub at line 25 of file G4_GEM_EIC.C
References max, BlackHoleGeometry::max_radius, min, and BlackHoleGeometry::min_z.
Referenced by Fun4All_G4_FastMom_GEM(), Fun4All_G4_FastMom_GEM_RICH(), and G4Init().
void EGEMSetup (PHG4Reco * g4Reco)
Definition at line 38 of file G4_GEM_EIC.C.
View newest version in sPHENIX GitHub at line 38 of file G4_GEM_EIC.C
References Enable::EGEM, Enable::EGEM_FULL, make_GEM_station(), and thickness.
Referenced by Fun4All_G4_FastMom_GEM(), Fun4All_G4_FastMom_GEM_RICH(), and G4Setup().
void FGEM_Init ()
Definition at line 32 of file G4_GEM_EIC.C.
View newest version in sPHENIX GitHub at line 32 of file G4_GEM_EIC.C
References max, BlackHoleGeometry::max_radius, and BlackHoleGeometry::max_z.
void FGEMSetup (PHG4Reco * g4Reco, const int N_Sector = 8, const double min_eta = 1.245)
Definition at line 65 of file G4_GEM_EIC.C.
View newest version in sPHENIX GitHub at line 65 of file G4_GEM_EIC.C
References Enable::FGEM_ORIG, and make_GEM_station().
int make_GEM_station (string name, PHG4Reco * g4Reco, double zpos, double etamin, double etamax, const int N_Sector = 8, double tilt = 0, bool doTilt = false)
Definition at line 155 of file G4_GEM_EIC.C.
View newest version in sPHENIX GitHub at line 155 of file G4_GEM_EIC.C
References PHG4Sector::Sector_Geometry::AddLayers_HBD_GEM(), AddLayers_MiniTPCDrift(), cos(), PHG4Sector::Sector_Geometry::eta_to_polar_angle(), PHG4Sector::Sector_Geometry::FlatEdge(), PHG4SectorSubsystem::get_geometry(), M_PI, Enable::OVERLAPCHECK, PHG4Subsystem::OverlapCheck(), PHG4Reco::registerSubsystem(), PHG4Sector::Sector_Geometry::set_material(), PHG4Sector::Sector_Geometry::set_max_polar_angle(), PHG4Sector::Sector_Geometry::set_max_polar_edge(), PHG4Sector::Sector_Geometry::set_min_polar_angle(), PHG4Sector::Sector_Geometry::set_min_polar_edge(), PHG4Sector::Sector_Geometry::set_N_Sector(), PHG4Sector::Sector_Geometry::set_normal_polar_angle(), PHG4Sector::Sector_Geometry::set_normal_start(), PHG4SectorSubsystem::SuperDetector(), t, and PHG4Sector::Sector_Geometry::Unit_cm().