EIC Software: eASTBeamPipe Class Reference
eASTBeamPipe Class Reference
#include <east/blob/main/Components/Beampipe/include/eASTBeamPipe.hh>
Public Member Functions
eASTBeamPipe (G4String compName, G4int vl=0, const G4bool validate_gdml=false)
virtual ~eASTBeamPipe ()
virtual void SetUp ()
virtual void Construct (G4VPhysicalVolume *)
void SetEnvGDML (G4String fn)
void SetGDML (G4String fn)
void SetMatFile (G4String fn)
Public Member Functions inherited from eASTVDetectorComponent
eASTVDetectorComponent (G4String compName, G4int vl=0)
virtual ~eASTVDetectorComponent ()
virtual void ConstructActionForMaster ()
virtual void ConstructSD ()
virtual void ConstructActions ()
void SetUpBase (G4int vl=0)
virtual G4VPhysicalVolume * GetEnvelope ()
virtual G4Region * GetRegion ()
void SetLocation (G4ThreeVector pos)
void SetRotation (G4String ax, G4double ang)
G4ThreeVector GetLocation ()
G4RotationMatrix GetRotation ()
Protected Attributes
const G4bool m_validate_gdml =false
Protected Attributes inherited from eASTVDetectorComponent
G4String componentName
G4String commandDir
G4int verboseLevel
G4VPhysicalVolume * pEnvelopePhys = nullptr
G4Region * pRegion = nullptr
Private Attributes
G4GenericMessenger * messenger = nullptr
G4String envGdmlFileName = "*NOTDEFINED*"
G4String gdmlFileName = "*NOTDEFINED*"
G4String matFileName = "*NOTDEFINED*"
G4bool materialToBeSet = false
Additional Inherited Members
Protected Member Functions inherited from eASTVDetectorComponent
void Locate (G4LogicalVolume *compLogVol, G4VPhysicalVolume *worldPhys)
G4String LocateDataFile (const G4String fn) const
Utility method to locate data files in the MacroSearchPath.
void RegisterUserAction (G4UserRunAction *)
void RegisterUserAction (G4UserEventAction *)
void RegisterUserAction (G4UserStackingAction *)
void RegisterUserAction (G4UserTrackingAction *)
void RegisterUserAction (G4UserSteppingAction *)
void ReadMaterialFile (G4String)
Detailed Description
Definition at line 18 of file eASTBeamPipe.hh.
View newest version in sPHENIX GitHub at line 18 of file eASTBeamPipe.hh
Constructor & Destructor Documentation
eASTBeamPipe::eASTBeamPipe (G4String compName, G4int vl = 0, const G4bool validate_gdml = false)
Definition at line 26 of file eASTBeamPipe.cc.
View newest version in sPHENIX GitHub at line 26 of file eASTBeamPipe.cc
eASTBeamPipe::~eASTBeamPipe () virtual
Definition at line 30 of file eASTBeamPipe.cc.
View newest version in sPHENIX GitHub at line 30 of file eASTBeamPipe.cc
References messenger.
Member Function Documentation
void eASTBeamPipe::Construct (G4VPhysicalVolume * worldPhys) virtual
Implements eASTVDetectorComponent.
Definition at line 56 of file eASTBeamPipe.cc.
View newest version in sPHENIX GitHub at line 56 of file eASTBeamPipe.cc
References G4GDMLParser::Clear(), eASTVDetectorComponent::componentName, envGdmlFileName, gdmlFileName, G4GDMLParser::GetWorldVolume(), eASTVDetectorComponent::Locate(), m_validate_gdml, materialToBeSet, matFileName, charm_jet_coverage::parser, eASTVDetectorComponent::pRegion, G4GDMLParser::Read(), eASTVDetectorComponent::ReadMaterialFile(), G4GDMLParser::SetReverseSearch(), and G4GDMLParser::SetStripFlag().
void eASTBeamPipe::SetEnvGDML (G4String fn) inline
Definition at line 39 of file eASTBeamPipe.hh.
View newest version in sPHENIX GitHub at line 39 of file eASTBeamPipe.hh
References envGdmlFileName, and eASTVDetectorComponent::LocateDataFile().
Referenced by SetUp().
void eASTBeamPipe::SetGDML (G4String fn) inline
Definition at line 41 of file eASTBeamPipe.hh.
View newest version in sPHENIX GitHub at line 41 of file eASTBeamPipe.hh
References gdmlFileName, and eASTVDetectorComponent::LocateDataFile().
Referenced by SetUp().
void eASTBeamPipe::SetMatFile (G4String fn) inline
Definition at line 43 of file eASTBeamPipe.hh.
View newest version in sPHENIX GitHub at line 43 of file eASTBeamPipe.hh
References eASTVDetectorComponent::LocateDataFile(), materialToBeSet, and matFileName.
Referenced by SetUp().
void eASTBeamPipe::SetUp () virtual
Implements eASTVDetectorComponent.
Definition at line 39 of file eASTBeamPipe.cc.
View newest version in sPHENIX GitHub at line 39 of file eASTBeamPipe.cc
References eASTVDetectorComponent::commandDir, messenger, SetEnvGDML(), SetGDML(), and SetMatFile().
Member Data Documentation
G4String eASTBeamPipe::envGdmlFileName = "*NOTDEFINED*" private
Definition at line 30 of file eASTBeamPipe.hh.
View newest version in sPHENIX GitHub at line 30 of file eASTBeamPipe.hh
Referenced by Construct(), and SetEnvGDML().
G4String eASTBeamPipe::gdmlFileName = "*NOTDEFINED*" private
Definition at line 31 of file eASTBeamPipe.hh.
View newest version in sPHENIX GitHub at line 31 of file eASTBeamPipe.hh
Referenced by Construct(), and SetGDML().
const G4bool eASTBeamPipe::m_validate_gdml =false protected
Definition at line 36 of file eASTBeamPipe.hh.
View newest version in sPHENIX GitHub at line 36 of file eASTBeamPipe.hh
Referenced by Construct().
G4bool eASTBeamPipe::materialToBeSet = false private
Definition at line 33 of file eASTBeamPipe.hh.
View newest version in sPHENIX GitHub at line 33 of file eASTBeamPipe.hh
Referenced by Construct(), and SetMatFile().
G4String eASTBeamPipe::matFileName = "*NOTDEFINED*" private
Definition at line 32 of file eASTBeamPipe.hh.
View newest version in sPHENIX GitHub at line 32 of file eASTBeamPipe.hh
Referenced by Construct(), and SetMatFile().
G4GenericMessenger* eASTBeamPipe::messenger = nullptr private
Definition at line 29 of file eASTBeamPipe.hh.
View newest version in sPHENIX GitHub at line 29 of file eASTBeamPipe.hh
Referenced by SetUp(), and ~eASTBeamPipe().
The documentation for this class was generated from the following files:
east/blob/main/Components/Beampipe/include/eASTBeamPipe.hh
east/blob/main/Components/Beampipe/src/eASTBeamPipe.cc