EIC Software: EicCadWizardFile Class Reference
EicCadWizardFile Class Reference
#include <EicRoot/blob/master/eic/cad/wizard/EicCadWizard.h>
Public Member Functions
EicCadWizardFile (const char *fname=0, const char *material=0)
~EicCadWizardFile ()
const TString & GetFileName (void) const
EicCadWizardFileConfig * GetConfig (void)
EicCadWizardFileConfig * config (void)
Public Attributes
TString mFileName
EicCadWizardFileConfig * mConfig
Private Member Functions
ClassDef (EicCadWizardFile, 1)
Detailed Description
Definition at line 54 of file EicCadWizard.h.
View newest version in sPHENIX GitHub at line 54 of file EicCadWizard.h
Constructor & Destructor Documentation
EicCadWizardFile::EicCadWizardFile (const char * fname = 0, const char * material = 0) inline
Definition at line 56 of file EicCadWizard.h.
View newest version in sPHENIX GitHub at line 56 of file EicCadWizard.h
References material(), and mConfig.
EicCadWizardFile::~EicCadWizardFile () inline
Definition at line 59 of file EicCadWizard.h.
View newest version in sPHENIX GitHub at line 59 of file EicCadWizard.h
References mConfig.
Member Function Documentation
EicCadWizardFile::ClassDef (EicCadWizardFile , 1) private
EicCadWizardFileConfig* EicCadWizardFile::config (void) inline
Definition at line 67 of file EicCadWizard.h.
View newest version in sPHENIX GitHub at line 67 of file EicCadWizard.h
Referenced by EicCadWizard::ConvertSourceFileToRoot().
EicCadWizardFileConfig* EicCadWizardFile::GetConfig (void) inline
Definition at line 65 of file EicCadWizard.h.
View newest version in sPHENIX GitHub at line 65 of file EicCadWizard.h
References mConfig.
const TString& EicCadWizardFile::GetFileName (void) const inline
Definition at line 61 of file EicCadWizard.h.
View newest version in sPHENIX GitHub at line 61 of file EicCadWizard.h
Referenced by EicCadWizard::ConvertSourceFileToRoot().
Member Data Documentation
EicCadWizardFileConfig* EicCadWizardFile::mConfig
Definition at line 67 of file EicCadWizard.h.
View newest version in sPHENIX GitHub at line 67 of file EicCadWizard.h
Referenced by EicCadWizardFile(), GetConfig(), and ~EicCadWizardFile().
TString EicCadWizardFile::mFileName
Definition at line 61 of file EicCadWizard.h.
View newest version in sPHENIX GitHub at line 61 of file EicCadWizard.h
The documentation for this class was generated from the following file:
EicRoot/blob/master/eic/cad/wizard/EicCadWizard.h