EIC Software: FW::Obj::ObjSurfaceWriter Class Reference
FW::Obj::ObjSurfaceWriter Class Reference
#include <fun4all_acts/blob/master/Examples/Io/Obj/include/ACTFW/Plugins/Obj/ObjSurfaceWriter.hpp>
Classes
class Config
Public Member Functions
ObjSurfaceWriter (const Config &cfg)
std::string name () const
Framework name() method.
FW::ProcessCode write (const AlgorithmContext &context, const Acts::Surface &surface)
FW::ProcessCode write (const std::string &sinfo)
Private Member Functions
const Acts::Logger & logger () const
Private access to the logging instance.
Private Attributes
Config m_cfg
the config class
Obj::VtnCounter m_vtnCounter
vertex, texture, normal
std::mutex m_write_mutex
mutex to protect multi-threaded writes
Detailed Description
An Obj writer for the geometry: surface section
Definition at line 28 of file ObjSurfaceWriter.hpp.
View newest version in sPHENIX GitHub at line 28 of file ObjSurfaceWriter.hpp
Constructor & Destructor Documentation
FW::Obj::ObjSurfaceWriter::ObjSurfaceWriter (const Config & cfg)
Constructor
Parameters
cfg is the configuration class
Definition at line 21 of file ObjSurfaceWriter.cpp.
View newest version in sPHENIX GitHub at line 21 of file ObjSurfaceWriter.cpp
References FW::Obj::ObjSurfaceWriter::Config::filePrefix, FW::Obj::ObjSurfaceWriter::Config::logger, m_cfg, FW::Obj::ObjSurfaceWriter::Config::name, and FW::Obj::ObjSurfaceWriter::Config::outputStream.
Member Function Documentation
const Acts::Logger& FW::Obj::ObjSurfaceWriter::logger () const inline private
Private access to the logging instance.
Definition at line 90 of file ObjSurfaceWriter.hpp.
View newest version in sPHENIX GitHub at line 90 of file ObjSurfaceWriter.hpp
References FW::Obj::ObjSurfaceWriter::Config::logger, and m_cfg.
std::string FW::Obj::ObjSurfaceWriter::name () const
Framework name() method.
Definition at line 37 of file ObjSurfaceWriter.cpp.
View newest version in sPHENIX GitHub at line 37 of file ObjSurfaceWriter.cpp
FW::ProcessCode FW::Obj::ObjSurfaceWriter::write (const AlgorithmContext & context, const Acts::Surface & surface)
The write interface
Parameters
context the Algorithm/Event context of this call
surface to be written out
Definition at line 41 of file ObjSurfaceWriter.cpp.
View newest version in sPHENIX GitHub at line 41 of file ObjSurfaceWriter.cpp
References ACTS_DEBUG, ACTS_VERBOSE, Acts::Surface::associatedDetectorElement(), Acts::Surface::bounds(), Acts::CylinderBounds::eHalfLengthZ, Acts::CylinderBounds::eR, FW::AlgorithmContext::geoContext, Acts::GeometryObject::geoID(), Acts::CylinderBounds::get(), Acts::GeometryID::layer(), Acts::RadialBounds::rMax(), Acts::RadialBounds::rMin(), SUCCESS, thickness, Acts::DetectorElementBase::thickness(), nlohmann::to_string(), Acts::Surface::transform(), Acts::PlanarBounds::vertices(), FW::Obj::writePlanarFace(), and FW::Obj::writeTube().
FW::ProcessCode FW::Obj::ObjSurfaceWriter::write (const std::string & sinfo) inline
write a bit of string
Parameters
is the string to be written
Definition at line 93 of file ObjSurfaceWriter.hpp.
View newest version in sPHENIX GitHub at line 93 of file ObjSurfaceWriter.hpp
References m_cfg, m_write_mutex, FW::Obj::ObjSurfaceWriter::Config::outputStream, and SUCCESS.
Member Data Documentation
Config FW::Obj::ObjSurfaceWriter::m_cfg private
the config class
Definition at line 85 of file ObjSurfaceWriter.hpp.
View newest version in sPHENIX GitHub at line 85 of file ObjSurfaceWriter.hpp
Referenced by logger(), ObjSurfaceWriter(), and write().
Obj::VtnCounter FW::Obj::ObjSurfaceWriter::m_vtnCounter private
vertex, texture, normal
Definition at line 86 of file ObjSurfaceWriter.hpp.
View newest version in sPHENIX GitHub at line 86 of file ObjSurfaceWriter.hpp
std::mutex FW::Obj::ObjSurfaceWriter::m_write_mutex private
mutex to protect multi-threaded writes
Definition at line 87 of file ObjSurfaceWriter.hpp.
View newest version in sPHENIX GitHub at line 87 of file ObjSurfaceWriter.hpp
Referenced by write().
The documentation for this class was generated from the following files:
fun4all_acts/blob/master/Examples/Io/Obj/include/ACTFW/Plugins/Obj/ObjSurfaceWriter.hpp
fun4all_acts/blob/master/Examples/Io/Obj/src/ObjSurfaceWriter.cpp