EIC Software: fun4all_coresoftware/blob/master/generators/JEWEL/medium-vac.f File Reference
medium-vac.f File Reference
Functions/Subroutines
subroutine medinit
subroutine mednextevt
double precision function getcentrality ()
subroutine pickvtx (X, Y)
subroutine setb (BVAL)
subroutine getscatterer (X, Y, Z, T, TYPE, PX, PY, PZ, E, MS, MD, TEMP)
subroutine avscatcen (X, Y, Z, T, PX, PY, PZ, E, MS)
subroutine maxscatcen (PX, PY, PZ, E, MS)
DOUBLE PRECISION function getneff (X, Y, Z, T)
DOUBLE PRECISION function gettemp (X, Y, Z, T)
DOUBLE PRECISION function gettempmax ()
DOUBLE PRECISION function getmdmax ()
DOUBLE PRECISION function getmdmin ()
DOUBLE PRECISION function getmsmax ()
DOUBLE PRECISION function getneffmax ()
DOUBLE PRECISION function getnatmdmin ()
DOUBLE PRECISION function getltimemax ()
DOUBLE PRECISION function getmd (X, Y, Z, T)
DOUBLE PRECISION function getms (X, Y, Z, T)
DOUBLE PRECISION function medderiv (XVAL, W)
Function/Subroutine Documentation
subroutine avscatcen (double precision X, double precision Y, double precision Z, double precision T, double precision PX, double precision PY, double precision PZ, double precision E, double precision MS)
Definition at line 111 of file medium-vac.f.
View newest version in sPHENIX GitHub at line 111 of file medium-vac.f
double precision function getcentrality ()
Definition at line 79 of file medium-vac.f.
View newest version in sPHENIX GitHub at line 79 of file medium-vac.f
References getcentrality().
DOUBLE PRECISION function getltimemax ()
Definition at line 189 of file medium-vac.f.
View newest version in sPHENIX GitHub at line 189 of file medium-vac.f
References getltimemax().
DOUBLE PRECISION function getmd (double precision X, double precision Y, double precision Z, double precision T)
Definition at line 196 of file medium-vac.f.
View newest version in sPHENIX GitHub at line 196 of file medium-vac.f
References getmd().
DOUBLE PRECISION function getmdmax ()
Definition at line 154 of file medium-vac.f.
View newest version in sPHENIX GitHub at line 154 of file medium-vac.f
References getmdmax().
DOUBLE PRECISION function getmdmin ()
Definition at line 161 of file medium-vac.f.
View newest version in sPHENIX GitHub at line 161 of file medium-vac.f
References getmdmin().
DOUBLE PRECISION function getms (double precision X, double precision Y, double precision Z, double precision T)
Definition at line 204 of file medium-vac.f.
View newest version in sPHENIX GitHub at line 204 of file medium-vac.f
References getms().
DOUBLE PRECISION function getmsmax ()
Definition at line 168 of file medium-vac.f.
View newest version in sPHENIX GitHub at line 168 of file medium-vac.f
References getmsmax().
DOUBLE PRECISION function getnatmdmin ()
Definition at line 182 of file medium-vac.f.
View newest version in sPHENIX GitHub at line 182 of file medium-vac.f
References getnatmdmin().
DOUBLE PRECISION function getneff (double precision X, double precision Y, double precision Z, double precision T)
Definition at line 131 of file medium-vac.f.
View newest version in sPHENIX GitHub at line 131 of file medium-vac.f
References getneff().
DOUBLE PRECISION function getneffmax ()
Definition at line 175 of file medium-vac.f.
View newest version in sPHENIX GitHub at line 175 of file medium-vac.f
References getneffmax().
subroutine getscatterer (double precision X, double precision Y, double precision Z, double precision T, integer TYPE, double precision PX, double precision PY, double precision PZ, double precision E, double precision MS, double precision MD, double precision TEMP)
Definition at line 102 of file medium-vac.f.
View newest version in sPHENIX GitHub at line 102 of file medium-vac.f
DOUBLE PRECISION function gettemp (double precision X, double precision Y, double precision Z, double precision T)
Definition at line 139 of file medium-vac.f.
View newest version in sPHENIX GitHub at line 139 of file medium-vac.f
References gettemp().
DOUBLE PRECISION function gettempmax ()
Definition at line 147 of file medium-vac.f.
View newest version in sPHENIX GitHub at line 147 of file medium-vac.f
References gettempmax().
subroutine maxscatcen (double precision PX, double precision PY, double precision PZ, double precision E, double precision MS)
Definition at line 119 of file medium-vac.f.
View newest version in sPHENIX GitHub at line 119 of file medium-vac.f
DOUBLE PRECISION function medderiv (XVAL, W)
Definition at line 212 of file medium-vac.f.
View newest version in sPHENIX GitHub at line 212 of file medium-vac.f
References medderiv().
subroutine medinit ()
Definition at line 61 of file medium-vac.f.
View newest version in sPHENIX GitHub at line 61 of file medium-vac.f
References false, and Acts::Extent::medium().
subroutine mednextevt ()
Definition at line 73 of file medium-vac.f.
View newest version in sPHENIX GitHub at line 73 of file medium-vac.f
subroutine pickvtx (double precision X, double precision Y)
Definition at line 86 of file medium-vac.f.
View newest version in sPHENIX GitHub at line 86 of file medium-vac.f
References x, and y.
subroutine setb (double precision BVAL)
Definition at line 95 of file medium-vac.f.
View newest version in sPHENIX GitHub at line 95 of file medium-vac.f