EIC Software: EicNamePatternHub< T > Class Template Reference
EicNamePatternHub< T > Class Template Reference
#include <EicRoot/blob/master/eic/base/EicNamePatternHub.h>
Public Member Functions
EicNamePatternHub ()
~EicNamePatternHub ()
void AddExactMatch (const char *match, T value=(T) 0)
void AddPrefixMatch (const char *match, T value=(T) 0)
void AddSuffixMatch (const char *match, T value=(T) 0)
void AddPatternMatch (const char *match, T value=(T) 0)
const std::pair< TString, T > * ExactMatch (const char *name) const
const std::pair< TString, T > * PrefixMatch (const char *name) const
const std::pair< TString, T > * SuffixMatch (const char *name) const
const std::pair< TString, T > * PatternMatch (const char *name) const
const std::pair< TString, T > * AnyMatch (const char *name) const
const bool IsEmpty () const
EicNamePatternHub ()
~EicNamePatternHub ()
void AddExactMatch (const char *match, T value=(T) 0)
void AddPrefixMatch (const char *match, T value=(T) 0)
void AddSuffixMatch (const char *match, T value=(T) 0)
void AddPatternMatch (const char *match, T value=(T) 0)
const std::pair< TString, T > * ExactMatch (const char *name) const
const std::pair< TString, T > * PrefixMatch (const char *name) const
const std::pair< TString, T > * SuffixMatch (const char *name) const
const std::pair< TString, T > * PatternMatch (const char *name) const
const std::pair< TString, T > * AnyMatch (const char *name) const
const bool IsEmpty () const
Private Attributes
std::vector< std::pair
< TString, T > > fExactMatch
std::vector< std::pair
< TString, T > > fPrefixMatch
std::vector< std::pair
< TString, T > > fSuffixMatch
std::vector< std::pair
< TString, T > > fPatternMatch
Detailed Description
template<typename T>
class EicNamePatternHub< T >
Definition at line 14 of file EicNamePatternHub.h.
View newest version in sPHENIX GitHub at line 14 of file EicNamePatternHub.h
Constructor & Destructor Documentation
template<typename T> EicNamePatternHub< T >::EicNamePatternHub () inline
Definition at line 16 of file EicNamePatternHub.h.
View newest version in sPHENIX GitHub at line 16 of file EicNamePatternHub.h
template<typename T> EicNamePatternHub< T >::~EicNamePatternHub () inline
Definition at line 17 of file EicNamePatternHub.h.
View newest version in sPHENIX GitHub at line 17 of file EicNamePatternHub.h
template<typename T> EicNamePatternHub< T >::EicNamePatternHub () inline
Definition at line 16 of file EicNamePatternHub.h.
View newest version in sPHENIX GitHub at line 16 of file EicNamePatternHub.h
template<typename T> EicNamePatternHub< T >::~EicNamePatternHub () inline
Definition at line 17 of file EicNamePatternHub.h.
View newest version in sPHENIX GitHub at line 17 of file EicNamePatternHub.h
Member Function Documentation
template<typename T> void EicNamePatternHub< T >::AddExactMatch (const char * match, T value = (T)0) inline
Definition at line 26 of file EicNamePatternHub.h.
View newest version in sPHENIX GitHub at line 26 of file EicNamePatternHub.h
Referenced by EicDetector::AddKillerVolume(), EicDigiHitProducer::DeclareDigiSensitiveVolume(), and EicDetector::DeclareGeantSensitiveVolume().
template<typename T> void EicNamePatternHub< T >::AddExactMatch (const char * match, T value = (T)0) inline
Definition at line 26 of file EicNamePatternHub.h.
View newest version in sPHENIX GitHub at line 26 of file EicNamePatternHub.h
template<typename T> void EicNamePatternHub< T >::AddPatternMatch (const char * match, T value = (T)0) inline
Definition at line 38 of file EicNamePatternHub.h.
View newest version in sPHENIX GitHub at line 38 of file EicNamePatternHub.h
Referenced by EicCadWizard::AssembleRootFiles(), b0tracker(), EicCadWizard::CreateBooleanSolidRootFile(), EicCadWizard::CreateGhostSolidRootFile(), EicCadWizard::CreateStlSolidRootFile(), fbgt(), femc(), hcal(), ip(), ippt(), lqst(), mumegas(), rich(), rp(), SetMapsColors(), tracker(), and zdc().
template<typename T> void EicNamePatternHub< T >::AddPatternMatch (const char * match, T value = (T)0) inline
Definition at line 38 of file EicNamePatternHub.h.
View newest version in sPHENIX GitHub at line 38 of file EicNamePatternHub.h
template<typename T> void EicNamePatternHub< T >::AddPrefixMatch (const char * match, T value = (T)0) inline
Definition at line 30 of file EicNamePatternHub.h.
View newest version in sPHENIX GitHub at line 30 of file EicNamePatternHub.h
Referenced by aerogel(), beampipe(), EicDigiHitProducer::DeclareDigiSensitiveVolumePrefix(), EicDetector::DeclareGeantSensitiveVolumePrefix(), and tpc().
template<typename T> void EicNamePatternHub< T >::AddPrefixMatch (const char * match, T value = (T)0) inline
Definition at line 30 of file EicNamePatternHub.h.
View newest version in sPHENIX GitHub at line 30 of file EicNamePatternHub.h
template<typename T> void EicNamePatternHub< T >::AddSuffixMatch (const char * match, T value = (T)0) inline
Definition at line 34 of file EicNamePatternHub.h.
View newest version in sPHENIX GitHub at line 34 of file EicNamePatternHub.h
template<typename T> void EicNamePatternHub< T >::AddSuffixMatch (const char * match, T value = (T)0) inline
Definition at line 34 of file EicNamePatternHub.h.
View newest version in sPHENIX GitHub at line 34 of file EicNamePatternHub.h
template<typename T> const std::pair<TString, T>* EicNamePatternHub< T >::AnyMatch (const char * name) const inline
Definition at line 74 of file EicNamePatternHub.h.
View newest version in sPHENIX GitHub at line 74 of file EicNamePatternHub.h
template<typename T> const std::pair<TString, T>* EicNamePatternHub< T >::AnyMatch (const char * name) const inline
Definition at line 74 of file EicNamePatternHub.h.
View newest version in sPHENIX GitHub at line 74 of file EicNamePatternHub.h
Referenced by EicGeoParData::AssignG4Colors(), EicDetector::CheckIfSensitive(), EicCalorimeterDigiHitProducer::ExtraInit(), EicGeoParData::FinalizeOutput(), EicDigiHitProducer::Init(), EicDetector::IsKillerVolume(), and EicDetector::ProcessHits().
template<typename T> const std::pair<TString, T>* EicNamePatternHub< T >::ExactMatch (const char * name) const inline
Definition at line 42 of file EicNamePatternHub.h.
View newest version in sPHENIX GitHub at line 42 of file EicNamePatternHub.h
Referenced by EicNamePatternHub< unsigned >::AnyMatch(), and EicCalorimeterDigiHitProducer::HandleHit().
template<typename T> const std::pair<TString, T>* EicNamePatternHub< T >::ExactMatch (const char * name) const inline
Definition at line 42 of file EicNamePatternHub.h.
View newest version in sPHENIX GitHub at line 42 of file EicNamePatternHub.h
template<typename T> const bool EicNamePatternHub< T >::IsEmpty () const inline
Definition at line 97 of file EicNamePatternHub.h.
View newest version in sPHENIX GitHub at line 97 of file EicNamePatternHub.h
template<typename T> const bool EicNamePatternHub< T >::IsEmpty () const inline
Definition at line 97 of file EicNamePatternHub.h.
View newest version in sPHENIX GitHub at line 97 of file EicNamePatternHub.h
Referenced by EicDigiHitProducer::Init().
template<typename T> const std::pair<TString, T>* EicNamePatternHub< T >::PatternMatch (const char * name) const inline
Definition at line 66 of file EicNamePatternHub.h.
View newest version in sPHENIX GitHub at line 66 of file EicNamePatternHub.h
Referenced by EicNamePatternHub< unsigned >::AnyMatch().
template<typename T> const std::pair<TString, T>* EicNamePatternHub< T >::PatternMatch (const char * name) const inline
Definition at line 66 of file EicNamePatternHub.h.
View newest version in sPHENIX GitHub at line 66 of file EicNamePatternHub.h
template<typename T> const std::pair<TString, T>* EicNamePatternHub< T >::PrefixMatch (const char * name) const inline
Definition at line 50 of file EicNamePatternHub.h.
View newest version in sPHENIX GitHub at line 50 of file EicNamePatternHub.h
template<typename T> const std::pair<TString, T>* EicNamePatternHub< T >::PrefixMatch (const char * name) const inline
Definition at line 50 of file EicNamePatternHub.h.
View newest version in sPHENIX GitHub at line 50 of file EicNamePatternHub.h
Referenced by EicNamePatternHub< unsigned >::AnyMatch(), and EicCalorimeterDigiHitProducer::HandleHit().
template<typename T> const std::pair<TString, T>* EicNamePatternHub< T >::SuffixMatch (const char * name) const inline
Definition at line 58 of file EicNamePatternHub.h.
View newest version in sPHENIX GitHub at line 58 of file EicNamePatternHub.h
Referenced by EicNamePatternHub< unsigned >::AnyMatch().
template<typename T> const std::pair<TString, T>* EicNamePatternHub< T >::SuffixMatch (const char * name) const inline
Definition at line 58 of file EicNamePatternHub.h.
View newest version in sPHENIX GitHub at line 58 of file EicNamePatternHub.h
Member Data Documentation
template<typename T> std::vector< std::pair< TString, T > > EicNamePatternHub< T >::fExactMatch private
Definition at line 99 of file EicNamePatternHub.h.
View newest version in sPHENIX GitHub at line 99 of file EicNamePatternHub.h
Referenced by EicNamePatternHub< unsigned >::AddExactMatch(), EicNamePatternHub< unsigned >::ExactMatch(), EicNamePatternHub< unsigned >::IsEmpty(), and EicNamePatternHub< unsigned >::~EicNamePatternHub().
template<typename T> std::vector< std::pair< TString, T > > EicNamePatternHub< T >::fPatternMatch private
Definition at line 108 of file EicNamePatternHub.h.
View newest version in sPHENIX GitHub at line 108 of file EicNamePatternHub.h
Referenced by EicNamePatternHub< unsigned >::AddPatternMatch(), EicNamePatternHub< unsigned >::IsEmpty(), EicNamePatternHub< unsigned >::PatternMatch(), and EicNamePatternHub< unsigned >::~EicNamePatternHub().
template<typename T> std::vector< std::pair< TString, T > > EicNamePatternHub< T >::fPrefixMatch private
Definition at line 106 of file EicNamePatternHub.h.
View newest version in sPHENIX GitHub at line 106 of file EicNamePatternHub.h
Referenced by EicNamePatternHub< unsigned >::AddPrefixMatch(), EicNamePatternHub< unsigned >::IsEmpty(), EicNamePatternHub< unsigned >::PrefixMatch(), and EicNamePatternHub< unsigned >::~EicNamePatternHub().
template<typename T> std::vector< std::pair< TString, T > > EicNamePatternHub< T >::fSuffixMatch private
Definition at line 107 of file EicNamePatternHub.h.
View newest version in sPHENIX GitHub at line 107 of file EicNamePatternHub.h
Referenced by EicNamePatternHub< unsigned >::AddSuffixMatch(), EicNamePatternHub< unsigned >::IsEmpty(), EicNamePatternHub< unsigned >::SuffixMatch(), and EicNamePatternHub< unsigned >::~EicNamePatternHub().
The documentation for this class was generated from the following files:
EicRoot/blob/master/eic/base/EicNamePatternHub.h
EicToyModel/blob/master/include/EicNamePatternHub.h