EIC Software: AllSi_Al_support_Detector Class Reference
AllSi_Al_support_Detector Class Reference
#include <fun4all_eicdetectors/blob/master/simulation/g4simulation/g4lblvtx/AllSi_Al_support_Detector.h>
Public Member Functions
AllSi_Al_support_Detector (PHG4Subsystem *subsys, PHCompositeNode *Node, PHParameters *parameters, const std::string &dnam)
constructor
virtual ~AllSi_Al_support_Detector ()
destructor
void ConstructMe (G4LogicalVolume *world) override
construct
void Print (const std::string &what="ALL") const override
void SuperDetector (const std::string &name)
const std::string SuperDetector () const
G4Material * element_material (std::string identifier)
void addDetectorSection (G4LogicalVolume *logicWorld, std::string name, double sign)
AllSi_Al_support_Detector (PHG4Subsystem *subsys, PHCompositeNode *Node, PHParameters *parameters, const std::string &dnam)
constructor
virtual ~AllSi_Al_support_Detector ()
destructor
void ConstructMe (G4LogicalVolume *world) override
construct
void Print (const std::string &what="ALL") const override
void SuperDetector (const std::string &name)
const std::string SuperDetector () const
G4Material * element_material (std::string identifier)
void addDetectorSection (G4LogicalVolume *logicWorld, std::string name, double sign)
volume accessors
int IsInDetector (G4VPhysicalVolume *) const
int IsInDetector (G4VPhysicalVolume *) const
Public Member Functions inherited from PHG4Detector
PHG4Detector ()=delete
constructor
PHG4Detector (PHG4Subsystem *subsys, PHCompositeNode *Node, const std::string &nam)
virtual ~PHG4Detector (void)
destructor
virtual void Construct (G4LogicalVolume *world) final
construct method
virtual void PostConstruction ()
Optional PostConstruction call after all geometry is constructed.
virtual void Verbosity (const int v)
virtual int Verbosity () const
virtual G4UserSteppingAction * GetSteppingAction ()
virtual std::string GetName () const
virtual void OverlapCheck (const bool chk)
virtual bool OverlapCheck () const
virtual int DisplayVolume (G4VSolid *volume, G4LogicalVolume *logvol, G4RotationMatrix *rotm=nullptr)
virtual int DisplayVolume (G4LogicalVolume *checksolid, G4LogicalVolume *logvol, G4RotationMatrix *rotm=nullptr)
virtual PHCompositeNode * topNode ()
virtual PHG4Subsystem * GetMySubsystem ()
Private Attributes
PHParameters * m_Params
std::set< G4VPhysicalVolume * > m_PhysicalVolumesSet
std::string m_SuperDetector
Additional Inherited Members
Static Public Member Functions inherited from PHG4Detector
static G4Material * GetDetectorMaterial (const std::string &name, const bool quit=true)
static G4Element * GetDetectorElement (const std::string &name, const bool quit=true)
Detailed Description
Definition at line 18 of file AllSi_Al_support_Detector.h.
View newest version in sPHENIX GitHub at line 18 of file AllSi_Al_support_Detector.h
Constructor & Destructor Documentation
AllSi_Al_support_Detector::AllSi_Al_support_Detector (PHG4Subsystem * subsys, PHCompositeNode * Node, PHParameters * parameters, const std::string & dnam)
constructor
Definition at line 19 of file AllSi_Al_support_Detector.cc.
View newest version in sPHENIX GitHub at line 19 of file AllSi_Al_support_Detector.cc
virtual AllSi_Al_support_Detector::~AllSi_Al_support_Detector () inline virtual
destructor
Definition at line 25 of file AllSi_Al_support_Detector.h.
View newest version in sPHENIX GitHub at line 25 of file AllSi_Al_support_Detector.h
AllSi_Al_support_Detector::AllSi_Al_support_Detector (PHG4Subsystem * subsys, PHCompositeNode * Node, PHParameters * parameters, const std::string & dnam)
constructor
virtual AllSi_Al_support_Detector::~AllSi_Al_support_Detector () inline virtual
destructor
Definition at line 25 of file AllSi_Al_support_Detector.h.
View newest version in sPHENIX GitHub at line 25 of file AllSi_Al_support_Detector.h
Member Function Documentation
void AllSi_Al_support_Detector::addDetectorSection (G4LogicalVolume * logicWorld, std::string name, double sign)
Definition at line 60 of file AllSi_Al_support_Detector.cc.
View newest version in sPHENIX GitHub at line 60 of file AllSi_Al_support_Detector.cc
References kdfinder::abs(), Acts::UnitConstants::degree, PHG4Detector::GetDetectorMaterial(), m_PhysicalVolumesSet, and PHG4Detector::OverlapCheck().
Referenced by ConstructMe().
void AllSi_Al_support_Detector::addDetectorSection (G4LogicalVolume * logicWorld, std::string name, double sign)
void AllSi_Al_support_Detector::ConstructMe (G4LogicalVolume * world) override virtual
construct
Implements PHG4Detector.
void AllSi_Al_support_Detector::ConstructMe (G4LogicalVolume * world) override virtual
construct
Implements PHG4Detector.
Definition at line 38 of file AllSi_Al_support_Detector.cc.
View newest version in sPHENIX GitHub at line 38 of file AllSi_Al_support_Detector.cc
References addDetectorSection().
G4Material* AllSi_Al_support_Detector::element_material (std::string identifier)
G4Material* AllSi_Al_support_Detector::element_material (std::string identifier)
int AllSi_Al_support_Detector::IsInDetector (G4VPhysicalVolume * volume) const
Definition at line 28 of file AllSi_Al_support_Detector.cc.
View newest version in sPHENIX GitHub at line 28 of file AllSi_Al_support_Detector.cc
References m_PhysicalVolumesSet.
Referenced by AllSi_Al_support_SteppingAction::UserSteppingAction().
int AllSi_Al_support_Detector::IsInDetector (G4VPhysicalVolume *) const
void AllSi_Al_support_Detector::Print (const std::string & what = "ALL") const override virtual
Reimplemented from PHG4Detector.
Definition at line 48 of file AllSi_Al_support_Detector.cc.
View newest version in sPHENIX GitHub at line 48 of file AllSi_Al_support_Detector.cc
References m_Params, and PHParameters::Print().
Referenced by AllSi_Al_support_Subsystem::Print().
void AllSi_Al_support_Detector::Print (const std::string & what = "ALL") const override virtual
Reimplemented from PHG4Detector.
void AllSi_Al_support_Detector::SuperDetector (const std::string & name) inline
Definition at line 37 of file AllSi_Al_support_Detector.h.
View newest version in sPHENIX GitHub at line 37 of file AllSi_Al_support_Detector.h
References m_SuperDetector, and name.
void AllSi_Al_support_Detector::SuperDetector (const std::string & name) inline
Definition at line 37 of file AllSi_Al_support_Detector.h.
View newest version in sPHENIX GitHub at line 37 of file AllSi_Al_support_Detector.h
References m_SuperDetector, and name.
const std::string AllSi_Al_support_Detector::SuperDetector () const inline
Definition at line 38 of file AllSi_Al_support_Detector.h.
View newest version in sPHENIX GitHub at line 38 of file AllSi_Al_support_Detector.h
References m_SuperDetector.
const std::string AllSi_Al_support_Detector::SuperDetector () const inline
Definition at line 38 of file AllSi_Al_support_Detector.h.
View newest version in sPHENIX GitHub at line 38 of file AllSi_Al_support_Detector.h
References m_SuperDetector.
Member Data Documentation
PHParameters * AllSi_Al_support_Detector::m_Params private
Definition at line 43 of file AllSi_Al_support_Detector.h.
View newest version in sPHENIX GitHub at line 43 of file AllSi_Al_support_Detector.h
Referenced by Print().
std::set< G4VPhysicalVolume * > AllSi_Al_support_Detector::m_PhysicalVolumesSet private
Definition at line 46 of file AllSi_Al_support_Detector.h.
View newest version in sPHENIX GitHub at line 46 of file AllSi_Al_support_Detector.h
Referenced by addDetectorSection(), and IsInDetector().
std::string AllSi_Al_support_Detector::m_SuperDetector private
Definition at line 48 of file AllSi_Al_support_Detector.h.
View newest version in sPHENIX GitHub at line 48 of file AllSi_Al_support_Detector.h
Referenced by SuperDetector().
The documentation for this class was generated from the following files:
fun4all_eicdetectors/blob/master/simulation/g4simulation/g4lblvtx/AllSi_Al_support_Detector.h
g4lblvtx/blob/master/source/AllSi_Al_support_Detector.h
fun4all_eicdetectors/blob/master/simulation/g4simulation/g4lblvtx/AllSi_Al_support_Detector.cc
g4lblvtx/blob/master/source/AllSi_Al_support_Detector.cc