EIC Software: CbmRichTrackExtrapolationMirrorIdeal Class Reference
CbmRichTrackExtrapolationMirrorIdeal Class Reference
This is the implementation of the TrackExtrapolation from MC points - operating on points in the RICH mirror! It reads the STS track array, gets the corresponding MC MirrorPoint and selects those to be projected to the Rich Photodetector points will be stored on mirror surface again. WARNING!!!: ProjectionProducer needs to be run with zflag==2!!!
#include <EicRoot/blob/master/rich/tracks/CbmRichTrackExtrapolationMirrorIdeal.h>
Public Member Functions
CbmRichTrackExtrapolationMirrorIdeal ()
Default constructor.
virtual ~CbmRichTrackExtrapolationMirrorIdeal ()
Destructor.
virtual void Init ()
Inherited from CbmRichTrackExtrapolationBase.
virtual void DoExtrapolation (TClonesArray *globalTracks, TClonesArray *extrapolatedTrackParams, double z, int minNofStsHits)
Inherited from CbmRichTrackExtrapolationBase.
Public Member Functions inherited from CbmRichTrackExtrapolationBase
CbmRichTrackExtrapolationBase ()
Default constructor.
virtual ~CbmRichTrackExtrapolationBase ()
Distructor.
Private Member Functions
CbmRichTrackExtrapolationMirrorIdeal (const CbmRichTrackExtrapolationMirrorIdeal &)
Copy constructor.
CbmRichTrackExtrapolationMirrorIdeal & operator= (const CbmRichTrackExtrapolationMirrorIdeal &)
Assignment operator.
Private Attributes
TClonesArray * fRichMirrorPoints
TClonesArray * fMcTracks
Detailed Description
This is the implementation of the TrackExtrapolation from MC points - operating on points in the RICH mirror! It reads the STS track array, gets the corresponding MC MirrorPoint and selects those to be projected to the Rich Photodetector points will be stored on mirror surface again. WARNING!!!: ProjectionProducer needs to be run with zflag==2!!!
Author
Claudia Hoehne
Date
2006
Definition at line 35 of file CbmRichTrackExtrapolationMirrorIdeal.h.
View newest version in sPHENIX GitHub at line 35 of file CbmRichTrackExtrapolationMirrorIdeal.h
Constructor & Destructor Documentation
CbmRichTrackExtrapolationMirrorIdeal::CbmRichTrackExtrapolationMirrorIdeal ()
Default constructor.
Definition at line 29 of file CbmRichTrackExtrapolationMirrorIdeal.cxx.
View newest version in sPHENIX GitHub at line 29 of file CbmRichTrackExtrapolationMirrorIdeal.cxx
CbmRichTrackExtrapolationMirrorIdeal::~CbmRichTrackExtrapolationMirrorIdeal () virtual
Destructor.
Definition at line 38 of file CbmRichTrackExtrapolationMirrorIdeal.cxx.
View newest version in sPHENIX GitHub at line 38 of file CbmRichTrackExtrapolationMirrorIdeal.cxx
CbmRichTrackExtrapolationMirrorIdeal::CbmRichTrackExtrapolationMirrorIdeal (const CbmRichTrackExtrapolationMirrorIdeal &) private
Copy constructor.
Member Function Documentation
void CbmRichTrackExtrapolationMirrorIdeal::DoExtrapolation (TClonesArray * globalTracks, TClonesArray * extrapolatedTrackParams, double z, int minNofStsHits) virtual
Inherited from CbmRichTrackExtrapolationBase.
Implements CbmRichTrackExtrapolationBase.
Definition at line 64 of file CbmRichTrackExtrapolationMirrorIdeal.cxx.
View newest version in sPHENIX GitHub at line 64 of file CbmRichTrackExtrapolationMirrorIdeal.cxx
References charge, fRichMirrorPoints, CbmTrackMatch::GetMCTrackId(), CbmGlobalTrack::GetStsTrackIndex(), FairMCPoint::GetTrackID(), charm_jet_coverage::mom, FairMCPoint::Momentum(), pos(), and FairMCPoint::Position().
void CbmRichTrackExtrapolationMirrorIdeal::Init (void) virtual
Inherited from CbmRichTrackExtrapolationBase.
Reimplemented from CbmRichTrackExtrapolationBase.
Definition at line 43 of file CbmRichTrackExtrapolationMirrorIdeal.cxx.
View newest version in sPHENIX GitHub at line 43 of file CbmRichTrackExtrapolationMirrorIdeal.cxx
References fMcTracks, fRichMirrorPoints, FairRootManager::GetObject(), and FairRootManager::Instance().
CbmRichTrackExtrapolationMirrorIdeal& CbmRichTrackExtrapolationMirrorIdeal::operator= (const CbmRichTrackExtrapolationMirrorIdeal &) private
Assignment operator.
Member Data Documentation
TClonesArray* CbmRichTrackExtrapolationMirrorIdeal::fMcTracks private
Definition at line 65 of file CbmRichTrackExtrapolationMirrorIdeal.h.
View newest version in sPHENIX GitHub at line 65 of file CbmRichTrackExtrapolationMirrorIdeal.h
Referenced by Init().
TClonesArray* CbmRichTrackExtrapolationMirrorIdeal::fRichMirrorPoints private
Definition at line 64 of file CbmRichTrackExtrapolationMirrorIdeal.h.
View newest version in sPHENIX GitHub at line 64 of file CbmRichTrackExtrapolationMirrorIdeal.h
Referenced by DoExtrapolation(), and Init().
The documentation for this class was generated from the following files:
EicRoot/blob/master/rich/tracks/CbmRichTrackExtrapolationMirrorIdeal.h
EicRoot/blob/master/rich/tracks/CbmRichTrackExtrapolationMirrorIdeal.cxx