EIC Software: FW::SimVertex Struct Reference
FW::SimVertex Struct Reference
A simultated vertex e.g. from a physics process.
#include <fun4all_acts/blob/master/Examples/Framework/include/ACTFW/EventData/SimVertex.hpp>
Public Types
using Scalar = double
using Vector4 = Acts::ActsVector< Scalar, 4 >
Public Member Functions
SimVertex (const Vector4 &position4_, ActsFatras::ProcessType process_=ActsFatras::ProcessType::eUndefined)
SimVertex ()=default
SimVertex (const SimVertex &)=default
SimVertex (SimVertex &&)=default
SimVertex & operator= (const SimVertex &)=default
SimVertex & operator= (SimVertex &&)=default
auto position () const
The vertex three-position.
Scalar time () const
The vertex time.
Public Attributes
Vector4 position4 = Vector4::Zero()
The vertex four-position.
ActsFatras::ProcessType process = ActsFatras::ProcessType::eUndefined
The vertex process type.
std::vector< ActsFatras::Particle > incoming = {}
The incoming particles into the vertex.
std::vector< ActsFatras::Particle > outgoing = {}
The outgoing particles from the vertex.
Detailed Description
A simultated vertex e.g. from a physics process.
Definition at line 20 of file SimVertex.hpp.
View newest version in sPHENIX GitHub at line 20 of file SimVertex.hpp
Member Typedef Documentation
using FW::SimVertex::Scalar = double
Definition at line 21 of file SimVertex.hpp.
View newest version in sPHENIX GitHub at line 21 of file SimVertex.hpp
using FW::SimVertex::Vector4 = Acts::ActsVector<Scalar, 4>
Definition at line 22 of file SimVertex.hpp.
View newest version in sPHENIX GitHub at line 22 of file SimVertex.hpp
Constructor & Destructor Documentation
FW::SimVertex::SimVertex (const Vector4 & position4_, ActsFatras::ProcessType process_ = ActsFatras::ProcessType::eUndefined) inline
Construct the vertex from a position and optional process type.
Parameters
position4_ the vertex four-position
process_ the process type that generated this vertex
Associated particles are left empty by default and must be filled by the user after construction.
Definition at line 40 of file SimVertex.hpp.
View newest version in sPHENIX GitHub at line 40 of file SimVertex.hpp
FW::SimVertex::SimVertex () default
FW::SimVertex::SimVertex (const SimVertex &) default
FW::SimVertex::SimVertex (SimVertex &&) default
Member Function Documentation
SimVertex& FW::SimVertex::operator= (const SimVertex &) default
SimVertex& FW::SimVertex::operator= (SimVertex &&) default
auto FW::SimVertex::position () const inline
The vertex three-position.
Definition at line 51 of file SimVertex.hpp.
View newest version in sPHENIX GitHub at line 51 of file SimVertex.hpp
References position4.
Scalar FW::SimVertex::time () const inline
The vertex time.
Definition at line 53 of file SimVertex.hpp.
View newest version in sPHENIX GitHub at line 53 of file SimVertex.hpp
References position4.
Member Data Documentation
std::vector<ActsFatras::Particle> FW::SimVertex::incoming = {}
The incoming particles into the vertex.
Definition at line 29 of file SimVertex.hpp.
View newest version in sPHENIX GitHub at line 29 of file SimVertex.hpp
Referenced by FW::ParticleSelector::execute().
std::vector<ActsFatras::Particle> FW::SimVertex::outgoing = {}
The outgoing particles from the vertex.
Definition at line 31 of file SimVertex.hpp.
View newest version in sPHENIX GitHub at line 31 of file SimVertex.hpp
Referenced by FW::ParticleSelector::execute(), and FW::ParametricProcessGenerator::operator()().
Vector4 FW::SimVertex::position4 = Vector4::Zero()
The vertex four-position.
Definition at line 25 of file SimVertex.hpp.
View newest version in sPHENIX GitHub at line 25 of file SimVertex.hpp
Referenced by position(), FW::RootVertexAndTracksReader::read(), and time().
ActsFatras::ProcessType FW::SimVertex::process = ActsFatras::ProcessType::eUndefined
The vertex process type.
Definition at line 27 of file SimVertex.hpp.
View newest version in sPHENIX GitHub at line 27 of file SimVertex.hpp
The documentation for this struct was generated from the following file:
fun4all_acts/blob/master/Examples/Framework/include/ACTFW/EventData/SimVertex.hpp