EIC Software: tree Namespace Reference
tree Namespace Reference
Functions
def load
def build
def write
def read
Function Documentation
def tree.build (inputname, outputdir = '.', nevents = -1)
Example of creating a tree.
Once the eic-smear library, you can just use the
BuildTree routine as usual.
Definition at line 24 of file tree.py.
View newest version in sPHENIX GitHub at line 24 of file tree.py
def tree.load ()
Import the PyROOT module and use ROOT.gSystem.Load
to import the eic-smear class library.
Definition at line 16 of file tree.py.
View newest version in sPHENIX GitHub at line 16 of file tree.py
def tree.read (inputname, treename)
Example of reading back a tree.
Definition at line 61 of file tree.py.
View newest version in sPHENIX GitHub at line 61 of file tree.py
References Draw().
def tree.write (outputname, nevents)
Example of creating a tree.
Creating and writing events manually without the use of BuildTree.
Definition at line 36 of file tree.py.
View newest version in sPHENIX GitHub at line 36 of file tree.py
References charm_jet_strange_helicity.xrange.
Referenced by dfe::io_dsv_impl::DsvWriter< Delimiter >.append(), Acts::AxisAlignedBoundingBox< entity_t, value_t, DIM >.draw(), main(), FairRun.SetWriteRunInfoFile(), ActsExamples::ObjTrackingGeometryWriter.write(), ActsExamples::RootMaterialWriter.write(), remote_msg_buffer.writen(), oamlBuffer.writen(), olzoBuffer.writeout(), ogzBuffer.writeout(), ospBuffer.writeout(), and ophBuffer.writeout().