EIC Software: EicRootInputFile Class Reference
EicRootInputFile Class Reference
#include <EicRoot/blob/master/eic/event/EicRootManager.h>
Public Member Functions
EicRootInputFile ()
EicRootInputFile (const char *fileName)
~EicRootInputFile ()
void ResetVars ()
Private Member Functions
TTree * GetTree (const char *treeName) const
TBranch * SetupBranch (const char *treeName, const char *branchName, void *addr) const
ClassDef (EicRootInputFile, 2)
Private Attributes
TString mFileName
TFile * mFptr
Friends
class EicRootManager
Detailed Description
Definition at line 43 of file EicRootManager.h.
View newest version in sPHENIX GitHub at line 43 of file EicRootManager.h
Constructor & Destructor Documentation
EicRootInputFile::EicRootInputFile () inline
Definition at line 47 of file EicRootManager.h.
View newest version in sPHENIX GitHub at line 47 of file EicRootManager.h
References ResetVars().
EicRootInputFile::EicRootInputFile (const char * fileName)
Definition at line 151 of file EicRootManager.cxx.
View newest version in sPHENIX GitHub at line 151 of file EicRootManager.cxx
References mFileName, mFptr, printf(), and ResetVars().
EicRootInputFile::~EicRootInputFile () inline
Definition at line 49 of file EicRootManager.h.
View newest version in sPHENIX GitHub at line 49 of file EicRootManager.h
References mFptr, and ResetVars().
Member Function Documentation
EicRootInputFile::ClassDef (EicRootInputFile , 2) private
TTree* EicRootInputFile::GetTree (const char * treeName) const inline private
Definition at line 56 of file EicRootManager.h.
View newest version in sPHENIX GitHub at line 56 of file EicRootManager.h
References mFptr.
Referenced by EicRootManager::EicRootManager(), and EicRootManager::SetupBranch().
void EicRootInputFile::ResetVars () inline
Definition at line 51 of file EicRootManager.h.
View newest version in sPHENIX GitHub at line 51 of file EicRootManager.h
References mFptr.
Referenced by EicRootInputFile(), and ~EicRootInputFile().
TBranch * EicRootInputFile::SetupBranch (const char * treeName, const char * branchName, void * addr) const private
Definition at line 167 of file EicRootManager.cxx.
View newest version in sPHENIX GitHub at line 167 of file EicRootManager.cxx
References mFileName, mFptr, and printf().
Referenced by EicRootManager::SetupBranch().
Friends And Related Function Documentation
friend class EicRootManager friend
Definition at line 44 of file EicRootManager.h.
View newest version in sPHENIX GitHub at line 44 of file EicRootManager.h
Member Data Documentation
TString EicRootInputFile::mFileName private
Definition at line 66 of file EicRootManager.h.
View newest version in sPHENIX GitHub at line 66 of file EicRootManager.h
Referenced by EicRootInputFile(), and SetupBranch().
TFile* EicRootInputFile::mFptr private
Definition at line 67 of file EicRootManager.h.
View newest version in sPHENIX GitHub at line 67 of file EicRootManager.h
Referenced by EicRootInputFile(), GetTree(), ResetVars(), SetupBranch(), and ~EicRootInputFile().
The documentation for this class was generated from the following files:
EicRoot/blob/master/eic/event/EicRootManager.h
EicRoot/blob/master/eic/event/EicRootManager.cxx