EIC Software: g4lblvtx/blob/master/analysis_codes/analysis_resolution.C File Reference
analysis_resolution.C File Reference
Functions
void prettyTH1F (TH1F *h1, int color, int marker, float min, float max)
void analysis_resolution ()
Function Documentation
void analysis_resolution ()
Definition at line 9 of file analysis_resolution.C.
View newest version in sPHENIX GitHub at line 9 of file analysis_resolution.C
References kdfinder::abs(), AddEntry(), c1, color, Draw(), F, Fill(), marker(), p, phi, prettyTH1F(), Print(), SetBranchAddress(), SetLineColor(), SetOptStat(), T, and theta().
void prettyTH1F (TH1F * h1, int color, int marker, float min, float max)
Definition at line 327 of file analysis_resolution.C.
View newest version in sPHENIX GitHub at line 327 of file analysis_resolution.C
References GetXaxis(), GetYaxis(), SetLineColor(), SetLineWidth(), and SetMinimum().
Referenced by analysis_resolution().