EIC Software: EvalRootTTreeReco Class Reference
EvalRootTTreeReco Class Reference
#include <fun4all_eic_qa/blob/master/source/EvalRootTTreeReco.h>
Public Member Functions
EvalRootTTreeReco (const std::string &name="EvalRootTTreeReco")
virtual ~EvalRootTTreeReco ()
int Init (PHCompositeNode *topNode) override
int InitRun (PHCompositeNode *topNode) override
int process_event (PHCompositeNode *topNode) override
int ResetEvent (PHCompositeNode *topNode) override
Clean up internals after each event.
int EndRun (const int runnumber) override
Called at the end of each run.
int End (PHCompositeNode *topNode) override
Called at the end of all processing.
int Reset (PHCompositeNode *) override
Reset.
void Print (const std::string &what="ALL") const override
void Detector (const std::string &name)
void DropHits (const bool drp=true)
Public Member Functions inherited from SubsysReco
~SubsysReco () override
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Private Attributes
bool m_DropHitsFlag = false
std::string m_Detector
std::string m_OutputNode
std::string m_HitNodeName
std::string m_TowerNodeName
std::string m_TowerGeoNodeName
std::string m_ClusterNodeName
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = INT_MAX - 10
}
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Detailed Description
Definition at line 12 of file EvalRootTTreeReco.h.
View newest version in sPHENIX GitHub at line 12 of file EvalRootTTreeReco.h
Constructor & Destructor Documentation
EvalRootTTreeReco::EvalRootTTreeReco (const std::string & name = "EvalRootTTreeReco")
Definition at line 32 of file EvalRootTTreeReco.cc.
View newest version in sPHENIX GitHub at line 32 of file EvalRootTTreeReco.cc
EvalRootTTreeReco::~EvalRootTTreeReco () virtual
Definition at line 38 of file EvalRootTTreeReco.cc.
View newest version in sPHENIX GitHub at line 38 of file EvalRootTTreeReco.cc
Member Function Documentation
void EvalRootTTreeReco::Detector (const std::string & name)
Definition at line 201 of file EvalRootTTreeReco.cc.
View newest version in sPHENIX GitHub at line 201 of file EvalRootTTreeReco.cc
References m_ClusterNodeName, m_Detector, m_HitNodeName, m_OutputNode, m_TowerGeoNodeName, m_TowerNodeName, and name.
Referenced by RunEval().
void EvalRootTTreeReco::DropHits (const bool drp = true) inline
Definition at line 54 of file EvalRootTTreeReco.h.
View newest version in sPHENIX GitHub at line 54 of file EvalRootTTreeReco.h
References m_DropHitsFlag.
Referenced by RunEval().
int EvalRootTTreeReco::End (PHCompositeNode * topNode) override virtual
Called at the end of all processing.
Reimplemented from SubsysReco.
Definition at line 184 of file EvalRootTTreeReco.cc.
View newest version in sPHENIX GitHub at line 184 of file EvalRootTTreeReco.cc
References Fun4AllReturnCodes::EVENT_OK.
int EvalRootTTreeReco::EndRun (const int runnumber) override virtual
Called at the end of each run.
Reimplemented from SubsysReco.
Definition at line 178 of file EvalRootTTreeReco.cc.
View newest version in sPHENIX GitHub at line 178 of file EvalRootTTreeReco.cc
References Fun4AllReturnCodes::EVENT_OK.
int EvalRootTTreeReco::Init (PHCompositeNode * topNode) override virtual
Called during initialization. Typically this is where you can book histograms, and e.g. register them to Fun4AllServer (so they can be output to file using Fun4AllServer::dumpHistos() method).
Reimplemented from SubsysReco.
Definition at line 43 of file EvalRootTTreeReco.cc.
View newest version in sPHENIX GitHub at line 43 of file EvalRootTTreeReco.cc
References PHCompositeNode::addNode(), Fun4AllReturnCodes::EVENT_OK, PHNodeIterator::findFirst(), m_Detector, and m_OutputNode.
int EvalRootTTreeReco::InitRun (PHCompositeNode * topNode) override virtual
Called for first event when run number is known. Typically this is where you may want to fetch data from database, because you know the run number. A place to book histograms which have to know the run number.
Reimplemented from SubsysReco.
Definition at line 61 of file EvalRootTTreeReco.cc.
View newest version in sPHENIX GitHub at line 61 of file EvalRootTTreeReco.cc
References Fun4AllReturnCodes::EVENT_OK.
void EvalRootTTreeReco::Print (const std::string & what = "ALL") const override virtual
Print out some info about this module.
Parameters
what can be used to specify what to print exactly.
Reimplemented from SubsysReco.
Definition at line 196 of file EvalRootTTreeReco.cc.
View newest version in sPHENIX GitHub at line 196 of file EvalRootTTreeReco.cc
int EvalRootTTreeReco::process_event (PHCompositeNode * topNode) override virtual
Called for each event. This is where you do the real work.
Reimplemented from SubsysReco.
Definition at line 67 of file EvalRootTTreeReco.cc.
View newest version in sPHENIX GitHub at line 67 of file EvalRootTTreeReco.cc
References Fun4AllReturnCodes::EVENT_OK, RawTowerGeom::get_center_x(), RawTowerGeom::get_center_y(), RawTowerGeom::get_center_z(), PHG4Particle::get_e(), RawCluster::get_energy(), RawTower::get_energy(), RawTowerGeom::get_eta(), RawTower::get_key(), RawTowerGeom::get_phi(), PHG4Particle::get_pid(), PHG4Particle::get_px(), PHG4Particle::get_py(), PHG4Particle::get_pz(), RawTowerGeom::get_theta(), RawTowerGeomContainer::get_tower_geometry(), RawClusterContainer::getClustersMap(), PHG4HitContainer::getHits(), PHG4TruthInfoContainer::GetPrimaryParticleRange(), PHG4TruthInfoContainer::GetPrimaryVertexIndex(), PHG4TruthInfoContainer::GetPrimaryVtx(), RawTowerContainer::getTowers(), m_ClusterNodeName, m_DropHitsFlag, m_HitNodeName, m_OutputNode, m_TowerGeoNodeName, m_TowerNodeName, EvalTower::set_teta(), EvalTower::set_tphi(), EvalTower::set_ttheta(), EvalTower::set_tx(), EvalTower::set_ty(), EvalTower::set_tz(), RawClusterContainer::size(), and PHG4HitContainer::size().
int EvalRootTTreeReco::Reset (PHCompositeNode * topNode) override virtual
Reset.
Reimplemented from SubsysReco.
Definition at line 190 of file EvalRootTTreeReco.cc.
View newest version in sPHENIX GitHub at line 190 of file EvalRootTTreeReco.cc
References Fun4AllReturnCodes::EVENT_OK.
int EvalRootTTreeReco::ResetEvent (PHCompositeNode * topNode) override virtual
Clean up internals after each event.
Reimplemented from SubsysReco.
Definition at line 172 of file EvalRootTTreeReco.cc.
View newest version in sPHENIX GitHub at line 172 of file EvalRootTTreeReco.cc
References Fun4AllReturnCodes::EVENT_OK.
Member Data Documentation
std::string EvalRootTTreeReco::m_ClusterNodeName private
Definition at line 65 of file EvalRootTTreeReco.h.
View newest version in sPHENIX GitHub at line 65 of file EvalRootTTreeReco.h
Referenced by Detector(), and process_event().
std::string EvalRootTTreeReco::m_Detector private
Definition at line 59 of file EvalRootTTreeReco.h.
View newest version in sPHENIX GitHub at line 59 of file EvalRootTTreeReco.h
Referenced by Detector(), and Init().
bool EvalRootTTreeReco::m_DropHitsFlag = false private
Definition at line 57 of file EvalRootTTreeReco.h.
View newest version in sPHENIX GitHub at line 57 of file EvalRootTTreeReco.h
Referenced by DropHits(), and process_event().
std::string EvalRootTTreeReco::m_HitNodeName private
Definition at line 62 of file EvalRootTTreeReco.h.
View newest version in sPHENIX GitHub at line 62 of file EvalRootTTreeReco.h
Referenced by Detector(), and process_event().
std::string EvalRootTTreeReco::m_OutputNode private
Definition at line 61 of file EvalRootTTreeReco.h.
View newest version in sPHENIX GitHub at line 61 of file EvalRootTTreeReco.h
Referenced by Detector(), Init(), and process_event().
std::string EvalRootTTreeReco::m_TowerGeoNodeName private
Definition at line 64 of file EvalRootTTreeReco.h.
View newest version in sPHENIX GitHub at line 64 of file EvalRootTTreeReco.h
Referenced by Detector(), and process_event().
std::string EvalRootTTreeReco::m_TowerNodeName private
Definition at line 63 of file EvalRootTTreeReco.h.
View newest version in sPHENIX GitHub at line 63 of file EvalRootTTreeReco.h
Referenced by Detector(), and process_event().
The documentation for this class was generated from the following files:
fun4all_eic_qa/blob/master/source/EvalRootTTreeReco.h
fun4all_eic_qa/blob/master/source/EvalRootTTreeReco.cc