EIC Software: edge_t Class Reference
edge_t Class Reference
#include <EicRoot/blob/master/eic/cad/elmer/src/meshtype.h>
Public Member Functions
edge_t ()
~edge_t ()
void setSharp (bool)
bool isSharp () const
void setPoints (int)
int getPoints () const
void setPointIndex (int, int)
int getPointIndex (int) const
void newPointIndexes (int)
void deletePointIndexes ()
void setSurfaces (int)
int getSurfaces () const
void setSurfaceIndex (int, int)
int getSurfaceIndex (int) const
void newSurfaceIndexes (int)
void deleteSurfaceIndexes ()
Public Member Functions inherited from element_t
element_t ()
~element_t ()
void setNature (int)
int getNature () const
void setCode (int)
int getCode () const
void setNodes (int)
int getNodes () const
void setIndex (int)
int getIndex () const
void setSelected (int)
int getSelected () const
int getNodeIndex (int) const
void setNodeIndex (int, int)
int * getNodeIndexes () const
void newNodeIndexes (int)
void deleteNodeIndexes ()
Private Attributes
bool sharp_edge
int points
int * point
int surfaces
int * surface
Detailed Description
Definition at line 128 of file meshtype.h.
View newest version in sPHENIX GitHub at line 128 of file meshtype.h
Constructor & Destructor Documentation
edge_t::edge_t ()
Definition at line 225 of file meshtype.cpp.
View newest version in sPHENIX GitHub at line 225 of file meshtype.cpp
edge_t::~edge_t ()
Definition at line 229 of file meshtype.cpp.
View newest version in sPHENIX GitHub at line 229 of file meshtype.cpp
Member Function Documentation
void edge_t::deletePointIndexes ()
Definition at line 268 of file meshtype.cpp.
View newest version in sPHENIX GitHub at line 268 of file meshtype.cpp
void edge_t::deleteSurfaceIndexes ()
Definition at line 298 of file meshtype.cpp.
View newest version in sPHENIX GitHub at line 298 of file meshtype.cpp
References surface().
int edge_t::getPointIndex (int n) const
Definition at line 258 of file meshtype.cpp.
View newest version in sPHENIX GitHub at line 258 of file meshtype.cpp
References n.
int edge_t::getPoints () const
Definition at line 248 of file meshtype.cpp.
View newest version in sPHENIX GitHub at line 248 of file meshtype.cpp
int edge_t::getSurfaceIndex (int n) const
Definition at line 288 of file meshtype.cpp.
View newest version in sPHENIX GitHub at line 288 of file meshtype.cpp
References n, and surface().
Referenced by mesh_t::save().
int edge_t::getSurfaces () const
Definition at line 278 of file meshtype.cpp.
View newest version in sPHENIX GitHub at line 278 of file meshtype.cpp
Referenced by ConvertEgTypeToMeshType(), and mesh_t::load().
bool edge_t::isSharp () const
Definition at line 238 of file meshtype.cpp.
View newest version in sPHENIX GitHub at line 238 of file meshtype.cpp
void edge_t::newPointIndexes (int n)
Definition at line 263 of file meshtype.cpp.
View newest version in sPHENIX GitHub at line 263 of file meshtype.cpp
References n.
void edge_t::newSurfaceIndexes (int n)
Definition at line 293 of file meshtype.cpp.
View newest version in sPHENIX GitHub at line 293 of file meshtype.cpp
References n, and surface().
Referenced by ConvertEgTypeToMeshType(), and mesh_t::load().
void edge_t::setPointIndex (int m, int n)
Definition at line 253 of file meshtype.cpp.
View newest version in sPHENIX GitHub at line 253 of file meshtype.cpp
References Acts::UnitConstants::m, and n.
void edge_t::setPoints (int n)
Definition at line 243 of file meshtype.cpp.
View newest version in sPHENIX GitHub at line 243 of file meshtype.cpp
References n.
void edge_t::setSharp (bool b)
Definition at line 233 of file meshtype.cpp.
View newest version in sPHENIX GitHub at line 233 of file meshtype.cpp
void edge_t::setSurfaceIndex (int m, int n)
Definition at line 283 of file meshtype.cpp.
View newest version in sPHENIX GitHub at line 283 of file meshtype.cpp
References Acts::UnitConstants::m, n, and surface().
Referenced by ConvertEgTypeToMeshType(), and mesh_t::load().
void edge_t::setSurfaces (int n)
Definition at line 273 of file meshtype.cpp.
View newest version in sPHENIX GitHub at line 273 of file meshtype.cpp
References n.
Referenced by ConvertEgTypeToMeshType(), and mesh_t::load().
Member Data Documentation
int* edge_t::point private
Definition at line 151 of file meshtype.h.
View newest version in sPHENIX GitHub at line 151 of file meshtype.h
int edge_t::points private
Definition at line 150 of file meshtype.h.
View newest version in sPHENIX GitHub at line 150 of file meshtype.h
bool edge_t::sharp_edge private
Definition at line 149 of file meshtype.h.
View newest version in sPHENIX GitHub at line 149 of file meshtype.h
int* edge_t::surface private
Definition at line 153 of file meshtype.h.
View newest version in sPHENIX GitHub at line 153 of file meshtype.h
int edge_t::surfaces private
Definition at line 152 of file meshtype.h.
View newest version in sPHENIX GitHub at line 152 of file meshtype.h
The documentation for this class was generated from the following files:
EicRoot/blob/master/eic/cad/elmer/src/meshtype.h
EicRoot/blob/master/eic/cad/elmer/src/meshtype.cpp