EIC Software: FW::FittingAlgorithm Exception Reference
FW::FittingAlgorithm Exception Reference final
#include <fun4all_acts/blob/master/Examples/Algorithms/Fitting/include/ACTFW/Fitting/FittingAlgorithm.hpp>
Classes
struct Config
Public Types
using FitterResult = Acts::Result< Acts::KalmanFitterResult< SimSourceLink >>
using FitterFunction = std::function< FitterResult(const std::vector< SimSourceLink > &, const TrackParameters &, const Acts::KalmanFitterOptions< Acts::VoidOutlierFinder > &)>
Public Member Functions
FittingAlgorithm (Config cfg, Acts::Logging::Level lvl)
FW::ProcessCode execute (const FW::AlgorithmContext &ctx) const finaloverride
Public Member Functions inherited from FW::BareAlgorithm
BareAlgorithm (std::string name, Acts::Logging::Level level=Acts::Logging::INFO)
std::string name () const finaloverride
The algorithm name.
Static Public Member Functions
static FitterFunction makeFitterFunction (std::shared_ptr< const Acts::TrackingGeometry > trackingGeometry, Options::BFieldVariant magneticField, Acts::Logging::Level lvl)
Private Attributes
Config m_cfg
Additional Inherited Members
Protected Member Functions inherited from FW::BareAlgorithm
const Acts::Logger & logger () const
Detailed Description
Definition at line 24 of file FittingAlgorithm.hpp.
View newest version in sPHENIX GitHub at line 24 of file FittingAlgorithm.hpp
Member Typedef Documentation
using FW::FittingAlgorithm::FitterFunction = std::function<FitterResult(const std::vector<SimSourceLink>&, const TrackParameters&, const Acts::KalmanFitterOptions<Acts::VoidOutlierFinder>&)>
Fit function that takes input measurements, initial trackstate and fitter options and returns some fit-specific result.
Definition at line 31 of file FittingAlgorithm.hpp.
View newest version in sPHENIX GitHub at line 31 of file FittingAlgorithm.hpp
using FW::FittingAlgorithm::FitterResult = Acts::Result<Acts::KalmanFitterResult<SimSourceLink>>
Definition at line 26 of file FittingAlgorithm.hpp.
View newest version in sPHENIX GitHub at line 26 of file FittingAlgorithm.hpp
Constructor & Destructor Documentation
FW::FittingAlgorithm::FittingAlgorithm (Config cfg, Acts::Logging::Level lvl)
Constructor of the fitting algorithm
Parameters
cfg is the config struct to configure the algorihtm
level is the logging level
Definition at line 18 of file FittingAlgorithm.cpp.
View newest version in sPHENIX GitHub at line 18 of file FittingAlgorithm.cpp
References FW::FittingAlgorithm::Config::inputInitialTrackParameters, FW::FittingAlgorithm::Config::inputProtoTracks, FW::FittingAlgorithm::Config::inputSourceLinks, m_cfg, and FW::FittingAlgorithm::Config::outputTrajectories.
Member Function Documentation
FW::ProcessCode FW::FittingAlgorithm::execute (const FW::AlgorithmContext & ctx) const final override virtual
Framework execute method of the fitting algorithm
Parameters
ctx is the algorithm context that holds event-wise information
Returns
a process code to steer the algporithm flow
Implements FW::BareAlgorithm.
Definition at line 35 of file FittingAlgorithm.cpp.
View newest version in sPHENIX GitHub at line 35 of file FittingAlgorithm.cpp
References ACTS_DEBUG, ACTS_FATAL, ACTS_VERBOSE, ACTS_WARNING, FW::WhiteBoard::add(), FW::AlgorithmContext::calibContext, FW::AlgorithmContext::eventStore, FW::AlgorithmContext::geoContext, FW::WhiteBoard::get(), FW::AlgorithmContext::magFieldContext, and SUCCESS.
FW::FittingAlgorithm::FitterFunction FW::FittingAlgorithm::makeFitterFunction (std::shared_ptr< const Acts::TrackingGeometry > trackingGeometry, Options::BFieldVariant magneticField, Acts::Logging::Level lvl) static
Create the fitter function implementation.
The magnetic field is intentionally given by-value since the variant contains shared_ptr anyways.
Definition at line 46 of file FittingAlgorithmFitterFunction.cpp.
View newest version in sPHENIX GitHub at line 46 of file FittingAlgorithmFitterFunction.cpp
References Acts::getDefaultLogger(), Acts::Test::navigator, and propagation_timing::stepper.
Member Data Documentation
Config FW::FittingAlgorithm::m_cfg private
Definition at line 67 of file FittingAlgorithm.hpp.
View newest version in sPHENIX GitHub at line 67 of file FittingAlgorithm.hpp
Referenced by FittingAlgorithm().
The documentation for this exception was generated from the following files:
fun4all_acts/blob/master/Examples/Algorithms/Fitting/include/ACTFW/Fitting/FittingAlgorithm.hpp
fun4all_acts/blob/master/Examples/Algorithms/Fitting/src/FittingAlgorithm.cpp
fun4all_acts/blob/master/Examples/Algorithms/Fitting/src/FittingAlgorithmFitterFunction.cpp