EIC Software: CbmRichRingLight Class Reference
CbmRichRingLight Class Reference
#include <EicRoot/blob/master/cbmdata/rich/CbmRichRingLight.h>
Public Member Functions
CbmRichRingLight ()
Standard constructor.
virtual ~CbmRichRingLight ()
Destructor.
void AddHit (CbmRichHitLight hit, unsigned short id=-1)
Add new hit to the ring.
bool RemoveHit (int hitId)
Remove hit from the ring.
int GetNofHits () const
Return number of hits in ring.
CbmRichHitLight GetHit (int ind)
Return hit by the index.
unsigned short GetHitId (int ind)
Return hit index in TClonesArray.
void SetCenterX (float x)
void SetCenterY (float y)
void SetRadius (float r)
void SetXYR (float x, float y, float r)
Set all 3 circle parameters.
void SetXYABP (float x, float y, float a, float b, float p)
Set all 5 ellipse parameters.
void SetChi2 (float chi2)
void SetAngle (float angle)
void SetNofHitsOnRing (unsigned short onring)
void SetSelectionNN (float selectionNN)
float GetCenterX () const
float GetCenterY () const
float GetRadius () const
float GetAaxis () const
float GetBaxis () const
float GetPhi () const
void SetAaxis (double a)
void SetBaxis (double b)
void SetPhi (double phi)
double GetXF1 () const
Calculate and return X coordinate of the first focus.
double GetYF1 () const
Calculate and return Y coordinate of the first focus.
double GetXF2 () const
Calculate and return X coordinate of the second focus.
double GetYF2 () const
Calculate and return Y coordinate of the second focus.
void SetABCDEF (float a, float b, float c, float d, float e, float f)
Set all 6 parameters of curve equation Axx+Bxy+Cyy+Dx+Ey+F.
float GetAPar () const
float GetBPar () const
float GetCPar () const
float GetDPar () const
float GetEPar () const
float GetFPar () const
float GetSelectionNN () const
float GetChi2 () const
float GetRadialPosition () const
Return radial position of the ring.
float GetAngle () const
unsigned short GetNofHitsOnRing () const
int GetRecFlag () const
void SetRecFlag (int r)
CbmRichRingLight ()
~CbmRichRingLight ()
void AddHit (CbmRichHitLight pHit, unsigned short id)
bool RemoveHit (int hitId)
int GetNofHits () const
CbmRichHitLight GetHit (int i)
unsigned short GetHitId (int i)
void SetCenterX (float x)
void SetCenterY (float y)
void SetRadius (float r)
void SetChi2 (float chi2)
void SetAngle (float angle)
void SetNofHitsOnRing (unsigned short onring)
void SetSelectionNN (float selectionNN)
void SetRecFlag (short recFlag)
float GetCenterX () const
float GetCenterY () const
float GetRadius () const
float GetSelectionNN () const
float GetChi2 () const
float GetNDF () const
float GetRadialPosition () const
float GetAngle () const
unsigned short GetNofHitsOnRing () const
short GetRecFlag ()
Protected Attributes
short fRecFlag
Private Attributes
vector< CbmRichHitLight > fHits
vector< unsigned short > fHitIds
float fCenterX
float fCenterY
float fRadius
float fAaxis
float fBaxis
float fPhi
float fAPar
float fBPar
float fCPar
float fDPar
float fEPar
float fFPar
int fRecFlag
float fChi2
float fAngle
unsigned short fNofHitsOnRing
float fSelectionNN
std::vector< CbmRichHitLight > fHitCollection
std::vector< unsigned short > fHitIdCollection
Detailed Description
Definition at line 46 of file CbmRichRingLight.h.
View newest version in sPHENIX GitHub at line 46 of file CbmRichRingLight.h
Constructor & Destructor Documentation
CbmRichRingLight::CbmRichRingLight () inline
Standard constructor.
Definition at line 53 of file CbmRichRingLight.h.
View newest version in sPHENIX GitHub at line 53 of file CbmRichRingLight.h
References fHitIds, and fHits.
virtual CbmRichRingLight::~CbmRichRingLight () inline virtual
Destructor.
Definition at line 87 of file CbmRichRingLight.h.
View newest version in sPHENIX GitHub at line 87 of file CbmRichRingLight.h
References fHitIds, and fHits.
CbmRichRingLight::CbmRichRingLight () inline
Definition at line 24 of file CbmRichRingLight.h.
View newest version in sPHENIX GitHub at line 24 of file CbmRichRingLight.h
References fHitCollection, and fHitIdCollection.
CbmRichRingLight::~CbmRichRingLight () inline
Definition at line 29 of file CbmRichRingLight.h.
View newest version in sPHENIX GitHub at line 29 of file CbmRichRingLight.h
References fHitCollection.
Member Function Documentation
void CbmRichRingLight::AddHit (CbmRichHitLight pHit, unsigned short id) inline
Definition at line 33 of file CbmRichRingLight.h.
View newest version in sPHENIX GitHub at line 33 of file CbmRichRingLight.h
References fHitCollection, and fHitIdCollection.
void CbmRichRingLight::AddHit (CbmRichHitLight hit, unsigned short id = -1) inline
Add new hit to the ring.
Parameters
[in] hit New hit to be added.
[in] id index of hit in TClonesArray.
Definition at line 98 of file CbmRichRingLight.h.
View newest version in sPHENIX GitHub at line 98 of file CbmRichRingLight.h
References fHitIds, and fHits.
Referenced by CbmRichConverter::CopyHitsToRingLight(), CbmRichRingFinderHoughImpl::FindPeak(), CbmRichRingFitterQa::GenerateEllipse(), and CbmRichGeoTest::RingParameters().
float CbmRichRingLight::GetAaxis () const inline
Definition at line 192 of file CbmRichRingLight.h.
View newest version in sPHENIX GitHub at line 192 of file CbmRichRingLight.h
References fAaxis.
Referenced by CbmRichRingFitterEllipseBase::CalcChi2(), CbmRichConverter::CopyParamsToRing(), CbmRichRadiusCorrection::DoCorrection(), CbmRichGeoTest::FillMcVsHitFitEllipse(), CbmRichGeoTest::FitAndFillHistEllipse(), CbmRichRingFitterQa::GenerateEllipse(), CbmRichGeoTest::RingParameters(), and CbmRichRingFitterEllipseTau::TransformEllipse().
float CbmRichRingLight::GetAngle () const inline
Definition at line 78 of file CbmRichRingLight.h.
View newest version in sPHENIX GitHub at line 78 of file CbmRichRingLight.h
References fAngle.
float CbmRichRingLight::GetAngle () const inline
Definition at line 296 of file CbmRichRingLight.h.
View newest version in sPHENIX GitHub at line 296 of file CbmRichRingLight.h
References fAngle.
Referenced by CbmRichRingSelectNeuralNet::DoSelect(), and CbmRichRingSelectAnn::DoSelect().
float CbmRichRingLight::GetAPar () const inline
Definition at line 274 of file CbmRichRingLight.h.
View newest version in sPHENIX GitHub at line 274 of file CbmRichRingLight.h
References fAPar.
float CbmRichRingLight::GetBaxis () const inline
Definition at line 193 of file CbmRichRingLight.h.
View newest version in sPHENIX GitHub at line 193 of file CbmRichRingLight.h
References fBaxis.
Referenced by CbmRichRingFitterEllipseBase::CalcChi2(), CbmRichConverter::CopyParamsToRing(), CbmRichRadiusCorrection::DoCorrection(), CbmRichGeoTest::FillMcVsHitFitEllipse(), CbmRichGeoTest::FitAndFillHistEllipse(), CbmRichRingFitterQa::GenerateEllipse(), CbmRichGeoTest::RingParameters(), and CbmRichRingFitterEllipseTau::TransformEllipse().
float CbmRichRingLight::GetBPar () const inline
Definition at line 275 of file CbmRichRingLight.h.
View newest version in sPHENIX GitHub at line 275 of file CbmRichRingLight.h
References fBPar.
float CbmRichRingLight::GetCenterX () const inline
Definition at line 64 of file CbmRichRingLight.h.
View newest version in sPHENIX GitHub at line 64 of file CbmRichRingLight.h
References fCenterX.
float CbmRichRingLight::GetCenterX () const inline
Definition at line 188 of file CbmRichRingLight.h.
View newest version in sPHENIX GitHub at line 188 of file CbmRichRingLight.h
References fCenterX.
Referenced by CbmRichRingFitterCOPLight::CalcChi2(), CbmRichRingFitterBase::CalcChi2(), CbmRichRingFitterQa::CalculateFitErrors(), CbmRichConverter::CopyParamsToRing(), CbmRichRadiusCorrection::DoCorrection(), CbmRichGeoTest::DrawRing(), CbmRichGeoTest::FillMcVsHitFitCircle(), CbmRichGeoTest::FillMcVsHitFitEllipse(), CbmRichRingFinderHoughImpl::FindPeak(), CbmRichGeoTest::FitAndFillHistCircle(), CbmRichGeoTest::FitAndFillHistEllipse(), CbmRichRingFitterQa::GenerateEllipse(), CbmRichRingSelectImplLight::GetAngle(), CbmRichRingSelectImpl::GetAngle(), CbmRichRingSelectImplLight::GetNofHitsOnRingCircle(), CbmRichRingSelectImpl::GetNofHitsOnRingCircle(), CbmRichRingFinderHoughImpl::ReAssignSharedHits(), CbmRichRingFinderHoughImpl::ReAssingSharedHits(), CbmRichRingFinderHoughImpl::RemoveHitsAroundRing(), and CbmRichGeoTest::RingParameters().
float CbmRichRingLight::GetCenterY () const inline
Definition at line 65 of file CbmRichRingLight.h.
View newest version in sPHENIX GitHub at line 65 of file CbmRichRingLight.h
References fCenterY.
float CbmRichRingLight::GetCenterY () const inline
Definition at line 189 of file CbmRichRingLight.h.
View newest version in sPHENIX GitHub at line 189 of file CbmRichRingLight.h
References fCenterY.
Referenced by CbmRichRingFitterCOPLight::CalcChi2(), CbmRichRingFitterBase::CalcChi2(), CbmRichRingFitterQa::CalculateFitErrors(), CbmRichConverter::CopyParamsToRing(), CbmRichRadiusCorrection::DoCorrection(), CbmRichGeoTest::DrawRing(), CbmRichGeoTest::FillMcVsHitFitCircle(), CbmRichGeoTest::FillMcVsHitFitEllipse(), CbmRichRingFinderHoughImpl::FindPeak(), CbmRichGeoTest::FitAndFillHistCircle(), CbmRichGeoTest::FitAndFillHistEllipse(), CbmRichRingFitterQa::GenerateEllipse(), CbmRichRingSelectImplLight::GetAngle(), CbmRichRingSelectImpl::GetAngle(), CbmRichRingSelectImplLight::GetNofHitsOnRingCircle(), CbmRichRingSelectImpl::GetNofHitsOnRingCircle(), CbmRichRingFinderHoughImpl::ReAssignSharedHits(), CbmRichRingFinderHoughImpl::ReAssingSharedHits(), CbmRichRingFinderHoughImpl::RemoveHitsAroundRing(), and CbmRichGeoTest::RingParameters().
float CbmRichRingLight::GetChi2 () const inline
Definition at line 68 of file CbmRichRingLight.h.
View newest version in sPHENIX GitHub at line 68 of file CbmRichRingLight.h
References fChi2.
float CbmRichRingLight::GetChi2 () const inline
Definition at line 282 of file CbmRichRingLight.h.
View newest version in sPHENIX GitHub at line 282 of file CbmRichRingLight.h
References fChi2.
Referenced by CbmRichConverter::CopyParamsToRing(), CbmRichTrainAnnSelect::DiffFakeTrueCircle(), CbmRichRingSelectNeuralNet::DoSelect(), CbmRichRingSelectAnn::DoSelect(), CbmRichRingFinderHoughImpl::FindPeak(), CbmRichGeoTest::FitAndFillHistCircle(), CbmRichGeoTest::FitAndFillHistEllipse(), and CbmRichRingFinderHoughImpl::RemoveHitsAroundRing().
float CbmRichRingLight::GetCPar () const inline
Definition at line 276 of file CbmRichRingLight.h.
View newest version in sPHENIX GitHub at line 276 of file CbmRichRingLight.h
References fCPar.
float CbmRichRingLight::GetDPar () const inline
Definition at line 277 of file CbmRichRingLight.h.
View newest version in sPHENIX GitHub at line 277 of file CbmRichRingLight.h
References fDPar.
float CbmRichRingLight::GetEPar () const inline
Definition at line 278 of file CbmRichRingLight.h.
View newest version in sPHENIX GitHub at line 278 of file CbmRichRingLight.h
References fEPar.
float CbmRichRingLight::GetFPar () const inline
Definition at line 279 of file CbmRichRingLight.h.
View newest version in sPHENIX GitHub at line 279 of file CbmRichRingLight.h
References fFPar.
CbmRichHitLight CbmRichRingLight::GetHit (int i) inline
Definition at line 51 of file CbmRichRingLight.h.
View newest version in sPHENIX GitHub at line 51 of file CbmRichRingLight.h
References fHitCollection.
CbmRichHitLight CbmRichRingLight::GetHit (int ind) inline
Return hit by the index.
Parameters
[in] ind Index of hit in local array.
Definition at line 133 of file CbmRichRingLight.h.
View newest version in sPHENIX GitHub at line 133 of file CbmRichRingLight.h
References fHits.
Referenced by CbmRichRingFitterEllipseBase::CalcChi2(), CbmRichRingFitterBase::CalcChi2(), CbmRichRingFitterQa::CalculateFitErrors(), CbmRichRingFitterCOPLight::DoFit(), CbmRichRingFitterRobustCOP::DoFit(), CbmRichRingFitterTAU::DoFit(), CbmRichRingFitterCircle::DoFit(), CbmRichRingFitterEllipseMinuit::DoFit(), CbmRichGeoTest::DrawRing(), CbmRichGeoTest::FitAndFillHistCircle(), CbmRichRingFitterCOP::FitRing(), CbmRichRingSelectImplLight::GetAngle(), CbmRichRingSelectImpl::GetAngle(), CbmRichRingSelectImplLight::GetNofHitsOnRingCircle(), CbmRichRingSelectImpl::GetNofHitsOnRingCircle(), CbmRichRingFitterEllipseTau::InitMatrices(), and CbmRichGeoTest::RingParameters().
unsigned short CbmRichRingLight::GetHitId (int i) inline
Definition at line 52 of file CbmRichRingLight.h.
View newest version in sPHENIX GitHub at line 52 of file CbmRichRingLight.h
References fHitIdCollection.
unsigned short CbmRichRingLight::GetHitId (int ind) inline
Return hit index in TClonesArray.
Parameters
[in] ind Index of hit in local array.
Definition at line 139 of file CbmRichRingLight.h.
View newest version in sPHENIX GitHub at line 139 of file CbmRichRingLight.h
References fHitIds.
Referenced by CbmRichRingFinderHoughImpl::ReAssignSharedHits(), CbmRichRingFinderHoughImpl::ReAssingSharedHits(), and CbmRichRingFinderHoughImpl::RingSelection().
float CbmRichRingLight::GetNDF () const inline
Definition at line 69 of file CbmRichRingLight.h.
View newest version in sPHENIX GitHub at line 69 of file CbmRichRingLight.h
References GetNofHits().
Referenced by CbmRichRingSelectNeuralNet::DoSelect().
int CbmRichRingLight::GetNofHits () const inline
Definition at line 50 of file CbmRichRingLight.h.
View newest version in sPHENIX GitHub at line 50 of file CbmRichRingLight.h
References fHitIdCollection.
int CbmRichRingLight::GetNofHits () const inline
Return number of hits in ring.
Definition at line 127 of file CbmRichRingLight.h.
View newest version in sPHENIX GitHub at line 127 of file CbmRichRingLight.h
References fHitIds.
Referenced by CbmRichRingFitterCOPLight::CalcChi2(), CbmRichRingFitterEllipseBase::CalcChi2(), CbmRichRingFitterBase::CalcChi2(), CbmRichRingFitterQa::CalculateFitErrors(), CbmRichTrainAnnSelect::DiffFakeTrueCircle(), CbmRichRingFitterCOPLight::DoFit(), CbmRichRingFitterRobustCOP::DoFit(), CbmRichRingFitterTAU::DoFit(), CbmRichRingFitterCircle::DoFit(), CbmRichRingFitterEllipseTau::DoFit(), CbmRichRingFitterEllipseMinuit::DoFit(), CbmRichRingSelectNeuralNet::DoSelect(), CbmRichRingSelectAnn::DoSelect(), CbmRichGeoTest::DrawRing(), CbmRichGeoTest::FillMcVsHitFitCircle(), CbmRichGeoTest::FillMcVsHitFitEllipse(), CbmRichRingFinderHoughImpl::FindPeak(), CbmRichGeoTest::FitAndFillHistCircle(), CbmRichGeoTest::FitAndFillHistEllipse(), CbmRichRingFitterCOP::FitRing(), CbmRichRingSelectImplLight::GetAngle(), CbmRichRingSelectImpl::GetAngle(), GetNDF(), CbmRichRingSelectImplLight::GetNofHitsOnRingCircle(), CbmRichRingSelectImpl::GetNofHitsOnRingCircle(), CbmRichRingFitterEllipseTau::InitMatrices(), CbmRichRingFinderHoughImpl::ReAssignSharedHits(), CbmRichRingFinderHoughImpl::ReAssingSharedHits(), CbmRichRingFinderHoughImpl::RemoveHitsAroundRing(), CbmRichGeoTest::RingParameters(), and CbmRichRingFinderHoughImpl::RingSelection().
unsigned short CbmRichRingLight::GetNofHitsOnRing () const inline
Definition at line 79 of file CbmRichRingLight.h.
View newest version in sPHENIX GitHub at line 79 of file CbmRichRingLight.h
References fNofHitsOnRing.
unsigned short CbmRichRingLight::GetNofHitsOnRing () const inline
Definition at line 298 of file CbmRichRingLight.h.
View newest version in sPHENIX GitHub at line 298 of file CbmRichRingLight.h
References fNofHitsOnRing.
Referenced by CbmRichRingSelectNeuralNet::DoSelect(), and CbmRichRingSelectAnn::DoSelect().
float CbmRichRingLight::GetPhi () const inline
Definition at line 194 of file CbmRichRingLight.h.
View newest version in sPHENIX GitHub at line 194 of file CbmRichRingLight.h
References fPhi.
Referenced by CbmRichConverter::CopyParamsToRing(), CbmRichRingFitterQa::GenerateEllipse(), and CbmRichRingFitterEllipseTau::TransformEllipse().
float CbmRichRingLight::GetRadialPosition () const inline
Definition at line 70 of file CbmRichRingLight.h.
View newest version in sPHENIX GitHub at line 70 of file CbmRichRingLight.h
References fCenterX, and fCenterY.
float CbmRichRingLight::GetRadialPosition () const inline
Return radial position of the ring.
Definition at line 287 of file CbmRichRingLight.h.
View newest version in sPHENIX GitHub at line 287 of file CbmRichRingLight.h
References fCenterX, and fCenterY.
Referenced by CbmRichTrainAnnSelect::DiffFakeTrueCircle(), CbmRichRingSelectNeuralNet::DoSelect(), and CbmRichRingSelectAnn::DoSelect().
float CbmRichRingLight::GetRadius () const inline
Definition at line 66 of file CbmRichRingLight.h.
View newest version in sPHENIX GitHub at line 66 of file CbmRichRingLight.h
References fRadius.
float CbmRichRingLight::GetRadius () const inline
Definition at line 190 of file CbmRichRingLight.h.
View newest version in sPHENIX GitHub at line 190 of file CbmRichRingLight.h
References fRadius.
Referenced by CbmRichRingFitterCOPLight::CalcChi2(), CbmRichRingFitterBase::CalcChi2(), CbmRichRingFitterQa::CalculateFitErrors(), CbmRichConverter::CopyParamsToRing(), CbmRichTrainAnnSelect::DiffFakeTrueCircle(), CbmRichRingSelectNeuralNet::DoSelect(), CbmRichRingSelectAnn::DoSelect(), CbmRichGeoTest::DrawRing(), CbmRichGeoTest::FillMcVsHitFitCircle(), CbmRichRingFinderHoughImpl::FindPeak(), CbmRichGeoTest::FitAndFillHistCircle(), CbmRichRingFitterQa::GenerateEllipse(), CbmRichRingSelectImplLight::GetNofHitsOnRingCircle(), CbmRichRingSelectImpl::GetNofHitsOnRingCircle(), CbmRichRingFinderHoughImpl::ReAssignSharedHits(), CbmRichRingFinderHoughImpl::ReAssingSharedHits(), CbmRichRingFinderHoughImpl::RemoveHitsAroundRing(), and CbmRichGeoTest::RingParameters().
short CbmRichRingLight::GetRecFlag () inline
Definition at line 80 of file CbmRichRingLight.h.
View newest version in sPHENIX GitHub at line 80 of file CbmRichRingLight.h
References fRecFlag.
int CbmRichRingLight::GetRecFlag () const inline
Definition at line 300 of file CbmRichRingLight.h.
View newest version in sPHENIX GitHub at line 300 of file CbmRichRingLight.h
References fRecFlag.
float CbmRichRingLight::GetSelectionNN () const inline
Definition at line 67 of file CbmRichRingLight.h.
View newest version in sPHENIX GitHub at line 67 of file CbmRichRingLight.h
References fSelectionNN.
float CbmRichRingLight::GetSelectionNN () const inline
Definition at line 281 of file CbmRichRingLight.h.
View newest version in sPHENIX GitHub at line 281 of file CbmRichRingLight.h
References fSelectionNN.
Referenced by CbmRichRingFinderHoughImpl::FindPeak(), and CbmRichRingComparatorMore::operator()().
double CbmRichRingLight::GetXF1 () const inline
Calculate and return X coordinate of the first focus.
Definition at line 202 of file CbmRichRingLight.h.
View newest version in sPHENIX GitHub at line 202 of file CbmRichRingLight.h
References c, cos(), fAaxis, fBaxis, fCenterX, and fPhi.
Referenced by CbmRichRingFitterEllipseBase::CalcChi2().
double CbmRichRingLight::GetXF2 () const inline
Calculate and return X coordinate of the second focus.
Definition at line 227 of file CbmRichRingLight.h.
View newest version in sPHENIX GitHub at line 227 of file CbmRichRingLight.h
References c, cos(), fAaxis, fBaxis, fCenterX, and fPhi.
Referenced by CbmRichRingFitterEllipseBase::CalcChi2().
double CbmRichRingLight::GetYF1 () const inline
Calculate and return Y coordinate of the first focus.
Definition at line 213 of file CbmRichRingLight.h.
View newest version in sPHENIX GitHub at line 213 of file CbmRichRingLight.h
References c, fAaxis, fBaxis, fCenterY, and fPhi.
Referenced by CbmRichRingFitterEllipseBase::CalcChi2().
double CbmRichRingLight::GetYF2 () const inline
Calculate and return Y coordinate of the second focus.
Definition at line 238 of file CbmRichRingLight.h.
View newest version in sPHENIX GitHub at line 238 of file CbmRichRingLight.h
References c, fAaxis, fBaxis, fCenterY, and fPhi.
Referenced by CbmRichRingFitterEllipseBase::CalcChi2().
bool CbmRichRingLight::RemoveHit (int hitId) inline
Definition at line 38 of file CbmRichRingLight.h.
View newest version in sPHENIX GitHub at line 38 of file CbmRichRingLight.h
References fHitIdCollection, and it.
bool CbmRichRingLight::RemoveHit (int hitId) inline
Remove hit from the ring.
Parameters
[in] hitId index of hit in TClonesArray.
Returns
true if hit was removed, false if hit was NOT removed.
Definition at line 111 of file CbmRichRingLight.h.
View newest version in sPHENIX GitHub at line 111 of file CbmRichRingLight.h
References fHitIds, and it.
Referenced by CbmRichRingFinderHoughImpl::ReAssignSharedHits(), and CbmRichRingFinderHoughImpl::ReAssingSharedHits().
void CbmRichRingLight::SetAaxis (double a) inline
Definition at line 195 of file CbmRichRingLight.h.
View newest version in sPHENIX GitHub at line 195 of file CbmRichRingLight.h
References fAaxis.
Referenced by CbmRichRadiusCorrection::DoCorrection(), and CbmRichRingFitterEllipseTau::TransformEllipse().
void CbmRichRingLight::SetABCDEF (float a, float b, float c, float d, float e, float f) inline
Set all 6 parameters of curve equation Axx+Bxy+Cyy+Dx+Ey+F.
Parameters
[in] a A parameter.
[in] b B parameter.
[in] c C parameter.
[in] d D parameter.
[in] e E parameter.
[in] f F parameter.
Definition at line 258 of file CbmRichRingLight.h.
View newest version in sPHENIX GitHub at line 258 of file CbmRichRingLight.h
References c, d, Acts::UnitConstants::e, fAPar, fBPar, fCPar, fDPar, fEPar, and fFPar.
Referenced by CbmRichRingFitterEllipseTau::TransformEllipse().
void CbmRichRingLight::SetAngle (float angle) inline
Definition at line 58 of file CbmRichRingLight.h.
View newest version in sPHENIX GitHub at line 58 of file CbmRichRingLight.h
References fAngle.
void CbmRichRingLight::SetAngle (float angle) inline
Definition at line 184 of file CbmRichRingLight.h.
View newest version in sPHENIX GitHub at line 184 of file CbmRichRingLight.h
References fAngle.
Referenced by CbmRichRingSelectNeuralNet::DoSelect(), and CbmRichRingSelectAnn::DoSelect().
void CbmRichRingLight::SetBaxis (double b) inline
Definition at line 196 of file CbmRichRingLight.h.
View newest version in sPHENIX GitHub at line 196 of file CbmRichRingLight.h
References fBaxis.
Referenced by CbmRichRadiusCorrection::DoCorrection(), and CbmRichRingFitterEllipseTau::TransformEllipse().
void CbmRichRingLight::SetCenterX (float x) inline
Definition at line 54 of file CbmRichRingLight.h.
View newest version in sPHENIX GitHub at line 54 of file CbmRichRingLight.h
References fCenterX, and x.
void CbmRichRingLight::SetCenterX (float x) inline
Definition at line 141 of file CbmRichRingLight.h.
View newest version in sPHENIX GitHub at line 141 of file CbmRichRingLight.h
References fCenterX, and x.
Referenced by CbmRichRingFitterCOPLight::DoFit(), CbmRichRingFitterRobustCOP::DoFit(), CbmRichRingFitterTAU::DoFit(), CbmRichRingFitterCircle::DoFit(), and CbmRichRingFitterCOP::FitRing().
void CbmRichRingLight::SetCenterY (float y) inline
Definition at line 55 of file CbmRichRingLight.h.
View newest version in sPHENIX GitHub at line 55 of file CbmRichRingLight.h
References fCenterY, and y.
void CbmRichRingLight::SetCenterY (float y) inline
Definition at line 142 of file CbmRichRingLight.h.
View newest version in sPHENIX GitHub at line 142 of file CbmRichRingLight.h
References fCenterY, and y.
Referenced by CbmRichRingFitterCOPLight::DoFit(), CbmRichRingFitterRobustCOP::DoFit(), CbmRichRingFitterTAU::DoFit(), CbmRichRingFitterCircle::DoFit(), and CbmRichRingFitterCOP::FitRing().
void CbmRichRingLight::SetChi2 (float chi2) inline
Definition at line 57 of file CbmRichRingLight.h.
View newest version in sPHENIX GitHub at line 57 of file CbmRichRingLight.h
References fChi2.
void CbmRichRingLight::SetChi2 (float chi2) inline
Definition at line 183 of file CbmRichRingLight.h.
View newest version in sPHENIX GitHub at line 183 of file CbmRichRingLight.h
References fChi2.
Referenced by CbmRichRingFitterCOPLight::CalcChi2(), CbmRichRingFitterEllipseBase::CalcChi2(), and CbmRichRingFitterBase::CalcChi2().
void CbmRichRingLight::SetNofHitsOnRing (unsigned short onring) inline
Definition at line 59 of file CbmRichRingLight.h.
View newest version in sPHENIX GitHub at line 59 of file CbmRichRingLight.h
References fNofHitsOnRing.
void CbmRichRingLight::SetNofHitsOnRing (unsigned short onring) inline
Definition at line 185 of file CbmRichRingLight.h.
View newest version in sPHENIX GitHub at line 185 of file CbmRichRingLight.h
References fNofHitsOnRing.
Referenced by CbmRichRingSelectNeuralNet::DoSelect(), and CbmRichRingSelectAnn::DoSelect().
void CbmRichRingLight::SetPhi (double phi) inline
Definition at line 197 of file CbmRichRingLight.h.
View newest version in sPHENIX GitHub at line 197 of file CbmRichRingLight.h
References fPhi, and phi.
Referenced by CbmRichRingFitterEllipseTau::TransformEllipse().
void CbmRichRingLight::SetRadius (float r) inline
Definition at line 56 of file CbmRichRingLight.h.
View newest version in sPHENIX GitHub at line 56 of file CbmRichRingLight.h
References fRadius.
void CbmRichRingLight::SetRadius (float r) inline
Definition at line 143 of file CbmRichRingLight.h.
View newest version in sPHENIX GitHub at line 143 of file CbmRichRingLight.h
References fRadius.
Referenced by CbmRichRingFitterCOPLight::DoFit(), CbmRichRingFitterRobustCOP::DoFit(), CbmRichRingFitterTAU::DoFit(), CbmRichRingFitterCircle::DoFit(), CbmRichRingFitterEllipseTau::DoFit(), CbmRichRingFitterEllipseMinuit::DoFit(), CbmRichRingFitterCOP::FitRing(), CbmRichRingFitterEllipseTau::TransformEllipse(), and CbmRichRingFitterEllipseMinuit::TransformToRichRing().
void CbmRichRingLight::SetRecFlag (short recFlag) inline
Definition at line 62 of file CbmRichRingLight.h.
View newest version in sPHENIX GitHub at line 62 of file CbmRichRingLight.h
References fRecFlag.
void CbmRichRingLight::SetRecFlag (int r) inline
Definition at line 301 of file CbmRichRingLight.h.
View newest version in sPHENIX GitHub at line 301 of file CbmRichRingLight.h
References fRecFlag.
Referenced by CbmRichRingFinderHoughImpl::RingSelection().
void CbmRichRingLight::SetSelectionNN (float selectionNN) inline
number between -1 and 1: -1 = fake ring, 1 = good ring (selection by neural net)
Definition at line 61 of file CbmRichRingLight.h.
View newest version in sPHENIX GitHub at line 61 of file CbmRichRingLight.h
References fSelectionNN.
void CbmRichRingLight::SetSelectionNN (float selectionNN) inline
Definition at line 186 of file CbmRichRingLight.h.
View newest version in sPHENIX GitHub at line 186 of file CbmRichRingLight.h
References fSelectionNN.
Referenced by CbmRichRingSelectNeuralNet::DoSelect(), and CbmRichRingSelectAnn::DoSelect().
void CbmRichRingLight::SetXYABP (float x, float y, float a, float b, float p) inline
Set all 5 ellipse parameters.
Parameters
[in] x X coordinate of ellipse center.
[in] y Y coordinate of ellipse center.
[in] a Major half axis of ellipse.
[in] b Minor half axis of ellipse.
[in] p Rotation angle of ellipse [rad].
Definition at line 169 of file CbmRichRingLight.h.
View newest version in sPHENIX GitHub at line 169 of file CbmRichRingLight.h
References fAaxis, fBaxis, fCenterX, fCenterY, fPhi, p, x, and y.
Referenced by CbmRichRingFitterEllipseTau::DoFit(), CbmRichRingFitterEllipseMinuit::DoFit(), CbmRichRingFitterQa::GenerateEllipse(), CbmRichRingFitterEllipseTau::TransformEllipse(), and CbmRichRingFitterEllipseMinuit::TransformToRichRing().
void CbmRichRingLight::SetXYR (float x, float y, float r) inline
Set all 3 circle parameters.
Parameters
[in] x X coordinate of circle center.
[in] y Y coordinate of circle center.
[in] r Radius of circle.
Definition at line 151 of file CbmRichRingLight.h.
View newest version in sPHENIX GitHub at line 151 of file CbmRichRingLight.h
References fCenterX, fCenterY, fRadius, x, and y.
Member Data Documentation
float CbmRichRingLight::fAaxis private
Definition at line 311 of file CbmRichRingLight.h.
View newest version in sPHENIX GitHub at line 311 of file CbmRichRingLight.h
Referenced by GetAaxis(), GetXF1(), GetXF2(), GetYF1(), GetYF2(), SetAaxis(), and SetXYABP().
float CbmRichRingLight::fAngle private
Definition at line 325 of file CbmRichRingLight.h.
View newest version in sPHENIX GitHub at line 325 of file CbmRichRingLight.h
Referenced by GetAngle(), and SetAngle().
float CbmRichRingLight::fAPar private
Definition at line 315 of file CbmRichRingLight.h.
View newest version in sPHENIX GitHub at line 315 of file CbmRichRingLight.h
Referenced by GetAPar(), and SetABCDEF().
float CbmRichRingLight::fBaxis private
Definition at line 312 of file CbmRichRingLight.h.
View newest version in sPHENIX GitHub at line 312 of file CbmRichRingLight.h
Referenced by GetBaxis(), GetXF1(), GetXF2(), GetYF1(), GetYF2(), SetBaxis(), and SetXYABP().
float CbmRichRingLight::fBPar private
Definition at line 316 of file CbmRichRingLight.h.
View newest version in sPHENIX GitHub at line 316 of file CbmRichRingLight.h
Referenced by GetBPar(), and SetABCDEF().
float CbmRichRingLight::fCenterX private
STL container to hold the hit indexes
Definition at line 307 of file CbmRichRingLight.h.
View newest version in sPHENIX GitHub at line 307 of file CbmRichRingLight.h
Referenced by GetCenterX(), GetRadialPosition(), GetXF1(), GetXF2(), SetCenterX(), SetXYABP(), and SetXYR().
float CbmRichRingLight::fCenterY private
Definition at line 308 of file CbmRichRingLight.h.
View newest version in sPHENIX GitHub at line 308 of file CbmRichRingLight.h
Referenced by GetCenterY(), GetRadialPosition(), GetYF1(), GetYF2(), SetCenterY(), SetXYABP(), and SetXYR().
float CbmRichRingLight::fChi2 private
Definition at line 324 of file CbmRichRingLight.h.
View newest version in sPHENIX GitHub at line 324 of file CbmRichRingLight.h
Referenced by GetChi2(), and SetChi2().
float CbmRichRingLight::fCPar private
Definition at line 317 of file CbmRichRingLight.h.
View newest version in sPHENIX GitHub at line 317 of file CbmRichRingLight.h
Referenced by GetCPar(), and SetABCDEF().
float CbmRichRingLight::fDPar private
Definition at line 318 of file CbmRichRingLight.h.
View newest version in sPHENIX GitHub at line 318 of file CbmRichRingLight.h
Referenced by GetDPar(), and SetABCDEF().
float CbmRichRingLight::fEPar private
Definition at line 319 of file CbmRichRingLight.h.
View newest version in sPHENIX GitHub at line 319 of file CbmRichRingLight.h
Referenced by GetEPar(), and SetABCDEF().
float CbmRichRingLight::fFPar private
Definition at line 320 of file CbmRichRingLight.h.
View newest version in sPHENIX GitHub at line 320 of file CbmRichRingLight.h
Referenced by GetFPar(), and SetABCDEF().
std::vector<CbmRichHitLight> CbmRichRingLight::fHitCollection private
Definition at line 83 of file CbmRichRingLight.h.
View newest version in sPHENIX GitHub at line 83 of file CbmRichRingLight.h
Referenced by AddHit(), CbmRichRingLight(), GetHit(), and ~CbmRichRingLight().
std::vector<unsigned short> CbmRichRingLight::fHitIdCollection private
Definition at line 84 of file CbmRichRingLight.h.
View newest version in sPHENIX GitHub at line 84 of file CbmRichRingLight.h
Referenced by AddHit(), CbmRichRingLight(), GetHitId(), GetNofHits(), and RemoveHit().
vector<unsigned short> CbmRichRingLight::fHitIds private
Definition at line 305 of file CbmRichRingLight.h.
View newest version in sPHENIX GitHub at line 305 of file CbmRichRingLight.h
Referenced by AddHit(), CbmRichRingLight(), GetHitId(), GetNofHits(), RemoveHit(), and ~CbmRichRingLight().
vector<CbmRichHitLight> CbmRichRingLight::fHits private
Definition at line 304 of file CbmRichRingLight.h.
View newest version in sPHENIX GitHub at line 304 of file CbmRichRingLight.h
Referenced by AddHit(), CbmRichRingLight(), GetHit(), and ~CbmRichRingLight().
unsigned short CbmRichRingLight::fNofHitsOnRing private
Definition at line 326 of file CbmRichRingLight.h.
View newest version in sPHENIX GitHub at line 326 of file CbmRichRingLight.h
Referenced by GetNofHitsOnRing(), and SetNofHitsOnRing().
float CbmRichRingLight::fPhi private
Definition at line 313 of file CbmRichRingLight.h.
View newest version in sPHENIX GitHub at line 313 of file CbmRichRingLight.h
Referenced by GetPhi(), GetXF1(), GetXF2(), GetYF1(), GetYF2(), SetPhi(), and SetXYABP().
float CbmRichRingLight::fRadius private
Definition at line 309 of file CbmRichRingLight.h.
View newest version in sPHENIX GitHub at line 309 of file CbmRichRingLight.h
Referenced by GetRadius(), SetRadius(), and SetXYR().
short CbmRichRingLight::fRecFlag protected
Definition at line 92 of file CbmRichRingLight.h.
View newest version in sPHENIX GitHub at line 92 of file CbmRichRingLight.h
int CbmRichRingLight::fRecFlag private
Definition at line 322 of file CbmRichRingLight.h.
View newest version in sPHENIX GitHub at line 322 of file CbmRichRingLight.h
Referenced by GetRecFlag(), and SetRecFlag().
float CbmRichRingLight::fSelectionNN private
Definition at line 327 of file CbmRichRingLight.h.
View newest version in sPHENIX GitHub at line 327 of file CbmRichRingLight.h
Referenced by GetSelectionNN(), and SetSelectionNN().
The documentation for this class was generated from the following files:
EicRoot/blob/master/cbmdata/rich/CbmRichRingLight.h
EicRoot/blob/master/rich/standalone/algorithm/CbmRichRingLight.h