EIC Software: PHActsToSvtxTracks Class Reference
PHActsToSvtxTracks Class Reference
#include <fun4all_coresoftware/blob/master/offline/packages/trackreco/PHActsToSvtxTracks.h>
Public Member Functions
PHActsToSvtxTracks (const std::string &name="PHActsToSvtxTracks")
Default constructor and destructor.
virtual ~PHActsToSvtxTracks ()
int End (PHCompositeNode *topNode)
Inherited SubsysReco functions.
int Init (PHCompositeNode *topNode)
int InitRun (PHCompositeNode *topNode)
int process_event (PHCompositeNode *topNode)
int ResetEvent (PHCompositeNode *topNode)
Clean up after each event.
void setSvtxTrackMapName (std::string &name)
Public Member Functions inherited from SubsysReco
virtual ~SubsysReco ()
virtual int EndRun (const int)
Called at the end of each run.
virtual int Reset (PHCompositeNode *)
Reset.
virtual void Print (const std::string &what="ALL") const
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Private Member Functions
int createNodes (PHCompositeNode *topNode)
Create track seed node if it doesn't exist yet.
int getNodes (PHCompositeNode *topNode)
Get nodes off node tree needed to execute module.
void createSvtxTrack (const unsigned int trackKey, Trajectory traj)
Private Attributes
SvtxTrackMap * m_svtxTrackMap = nullptr
SvtxVertexMap * m_svtxVertexMap = nullptr
ActsTrackingGeometry * m_tGeometry = nullptr
std::map< const unsigned int,
Trajectory > * m_actsFitResults = nullptr
CluskeyBimap * m_hitIdClusKey = nullptr
std::string m_svtxMapName = "SvtxTrackMap"
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = INT_MAX - 10
}
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Detailed Description
Definition at line 38 of file PHActsToSvtxTracks.h.
View newest version in sPHENIX GitHub at line 38 of file PHActsToSvtxTracks.h
Constructor & Destructor Documentation
PHActsToSvtxTracks::PHActsToSvtxTracks (const std::string & name = "PHActsToSvtxTracks")
Default constructor and destructor.
Fun4All includes.
Tracking includes std (and the like) includes
Definition at line 36 of file PHActsToSvtxTracks.cc.
View newest version in sPHENIX GitHub at line 36 of file PHActsToSvtxTracks.cc
References Fun4AllBase::Verbosity().
virtual PHActsToSvtxTracks::~PHActsToSvtxTracks () inline virtual
Definition at line 43 of file PHActsToSvtxTracks.h.
View newest version in sPHENIX GitHub at line 43 of file PHActsToSvtxTracks.h
Member Function Documentation
int PHActsToSvtxTracks::createNodes (PHCompositeNode * topNode) private
Create track seed node if it doesn't exist yet.
Definition at line 183 of file PHActsToSvtxTracks.cc.
View newest version in sPHENIX GitHub at line 183 of file PHActsToSvtxTracks.cc
References PHCompositeNode::addNode(), Fun4AllReturnCodes::EVENT_OK, PHNodeIterator::findFirst(), m_svtxMapName, and m_svtxTrackMap.
Referenced by InitRun().
void PHActsToSvtxTracks::createSvtxTrack (const unsigned int trackKey, Trajectory traj) private
Try to find the track first to update it. Otherwise, if it is a new map, create the track
For a track from the Acts KF, it has only one track tip
Units already considered in rotation
Definition at line 96 of file PHActsToSvtxTracks.cc.
View newest version in sPHENIX GitHub at line 96 of file PHActsToSvtxTracks.cc
References SvtxTrack::clear_cluster_keys(), SvtxTrack::clear_states(), Acts::UnitConstants::cm, SvtxTrackMap::find(), SvtxVertexMap::find(), ActsTrackingGeometry::geoContext, SvtxTrack::get_vertex_id(), SvtxTrack::insert_state(), m_hitIdClusKey, m_svtxTrackMap, m_svtxVertexMap, m_tGeometry, SvtxTrack::set_charge(), SvtxTrack::set_chisq(), SvtxTrack::set_dca3d_xy(), SvtxTrack::set_dca3d_xy_error(), SvtxTrack::set_dca3d_z(), SvtxTrack::set_dca3d_z_error(), SvtxTrack::set_error(), SvtxTrack::set_ndf(), SvtxTrack::set_px(), SvtxTrack::set_py(), SvtxTrack::set_pz(), SvtxTrackState_v1::set_x(), SvtxTrack::set_x(), SvtxTrackState_v1::set_y(), SvtxTrack::set_y(), SvtxTrackState_v1::set_z(), SvtxTrack::set_z(), and Fun4AllBase::Verbosity().
Referenced by process_event().
int PHActsToSvtxTracks::End (PHCompositeNode * topNode) virtual
Inherited SubsysReco functions.
Reimplemented from SubsysReco.
Definition at line 44 of file PHActsToSvtxTracks.cc.
View newest version in sPHENIX GitHub at line 44 of file PHActsToSvtxTracks.cc
References Fun4AllReturnCodes::EVENT_OK, and Fun4AllBase::Verbosity().
int PHActsToSvtxTracks::getNodes (PHCompositeNode * topNode) private
Get nodes off node tree needed to execute module.
Definition at line 219 of file PHActsToSvtxTracks.cc.
View newest version in sPHENIX GitHub at line 219 of file PHActsToSvtxTracks.cc
References Fun4AllReturnCodes::ABORTEVENT, Fun4AllReturnCodes::EVENT_OK, m_actsFitResults, m_hitIdClusKey, m_svtxTrackMap, m_svtxVertexMap, m_tGeometry, and PHWHERE.
Referenced by InitRun().
int PHActsToSvtxTracks::Init (PHCompositeNode *) virtual
Called during initialization. Typically this is where you can book histograms, and e.g. register them to Fun4AllServer (so they can be output to file using Fun4AllServer::dumpHistos() method).
Reimplemented from SubsysReco.
Definition at line 55 of file PHActsToSvtxTracks.cc.
View newest version in sPHENIX GitHub at line 55 of file PHActsToSvtxTracks.cc
References Fun4AllReturnCodes::EVENT_OK.
int PHActsToSvtxTracks::InitRun (PHCompositeNode *) virtual
Called for first event when run number is known. Typically this is where you may want to fetch data from database, because you know the run number.
Reimplemented from SubsysReco.
Definition at line 60 of file PHActsToSvtxTracks.cc.
View newest version in sPHENIX GitHub at line 60 of file PHActsToSvtxTracks.cc
References Fun4AllReturnCodes::ABORTEVENT, createNodes(), Fun4AllReturnCodes::EVENT_OK, and getNodes().
int PHActsToSvtxTracks::process_event (PHCompositeNode *) virtual
Called for each event. This is where you do the real work.
Reimplemented from SubsysReco.
Definition at line 71 of file PHActsToSvtxTracks.cc.
View newest version in sPHENIX GitHub at line 71 of file PHActsToSvtxTracks.cc
References createSvtxTrack(), Fun4AllReturnCodes::EVENT_OK, m_actsFitResults, and Fun4AllBase::Verbosity().
int PHActsToSvtxTracks::ResetEvent (PHCompositeNode *) virtual
Clean up after each event.
Reimplemented from SubsysReco.
Definition at line 91 of file PHActsToSvtxTracks.cc.
View newest version in sPHENIX GitHub at line 91 of file PHActsToSvtxTracks.cc
References Fun4AllReturnCodes::EVENT_OK.
void PHActsToSvtxTracks::setSvtxTrackMapName (std::string & name) inline
Definition at line 52 of file PHActsToSvtxTracks.h.
View newest version in sPHENIX GitHub at line 52 of file PHActsToSvtxTracks.h
References m_svtxMapName, and name.
Member Data Documentation
std::map<const unsigned int, Trajectory>* PHActsToSvtxTracks::m_actsFitResults = nullptr private
Definition at line 68 of file PHActsToSvtxTracks.h.
View newest version in sPHENIX GitHub at line 68 of file PHActsToSvtxTracks.h
Referenced by getNodes(), and process_event().
CluskeyBimap* PHActsToSvtxTracks::m_hitIdClusKey = nullptr private
Definition at line 69 of file PHActsToSvtxTracks.h.
View newest version in sPHENIX GitHub at line 69 of file PHActsToSvtxTracks.h
Referenced by createSvtxTrack(), and getNodes().
std::string PHActsToSvtxTracks::m_svtxMapName = "SvtxTrackMap" private
Definition at line 70 of file PHActsToSvtxTracks.h.
View newest version in sPHENIX GitHub at line 70 of file PHActsToSvtxTracks.h
Referenced by createNodes(), and setSvtxTrackMapName().
SvtxTrackMap* PHActsToSvtxTracks::m_svtxTrackMap = nullptr private
Definition at line 65 of file PHActsToSvtxTracks.h.
View newest version in sPHENIX GitHub at line 65 of file PHActsToSvtxTracks.h
Referenced by createNodes(), createSvtxTrack(), and getNodes().
SvtxVertexMap* PHActsToSvtxTracks::m_svtxVertexMap = nullptr private
Definition at line 66 of file PHActsToSvtxTracks.h.
View newest version in sPHENIX GitHub at line 66 of file PHActsToSvtxTracks.h
Referenced by createSvtxTrack(), and getNodes().
ActsTrackingGeometry* PHActsToSvtxTracks::m_tGeometry = nullptr private
Definition at line 67 of file PHActsToSvtxTracks.h.
View newest version in sPHENIX GitHub at line 67 of file PHActsToSvtxTracks.h
Referenced by createSvtxTrack(), and getNodes().
The documentation for this class was generated from the following files:
fun4all_coresoftware/blob/master/offline/packages/trackreco/PHActsToSvtxTracks.h
fun4all_coresoftware/blob/master/offline/packages/trackreco/PHActsToSvtxTracks.cc