EIC Software: PHTruthSiliconAssociation Class Reference
PHTruthSiliconAssociation Class Reference
#include <fun4all_coresoftware/blob/master/offline/packages/trackreco/PHTruthSiliconAssociation.h>
Public Member Functions
PHTruthSiliconAssociation (const std::string &name="PHTruthSiliconAssociation")
virtual ~PHTruthSiliconAssociation ()
int Init (PHCompositeNode *topNode) override
int InitRun (PHCompositeNode *topNode) override
int process_event (PHCompositeNode *topNode) override
int ResetEvent (PHCompositeNode *topNode) override
Clean up internals after each event.
int EndRun (const int runnumber) override
Called at the end of each run.
int End (PHCompositeNode *topNode) override
Called at the end of all processing.
int Reset (PHCompositeNode *) override
Reset.
void Print (const std::string &what="ALL") const override
Public Member Functions inherited from SubsysReco
virtual ~SubsysReco ()
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Private Member Functions
int GetNodes (PHCompositeNode *topNode)
std::vector< PHG4Particle * > getG4PrimaryParticle (SvtxTrack *track)
std::set< TrkrDefs::cluskey > getSiliconClustersFromParticle (PHG4Particle *g4particle)
Private Attributes
PHG4TruthInfoContainer * _truthinfo {nullptr}
PHG4HitContainer * _g4hits_tpc {nullptr}
PHG4HitContainer * _g4hits_mvtx {nullptr}
PHG4HitContainer * _g4hits_intt {nullptr}
TrkrClusterContainer * _cluster_map {nullptr}
TrkrClusterHitAssoc * _cluster_hit_map {nullptr}
TrkrHitTruthAssoc * _hit_truth_map {nullptr}
SvtxTrackMap * _track_map {nullptr}
AssocInfoContainer * _assoc_container {nullptr}
SvtxTrack * _tracklet {nullptr}
SvtxVertexMap * _vertex_map {nullptr}
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = INT_MAX - 10
}
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Detailed Description
Definition at line 26 of file PHTruthSiliconAssociation.h.
View newest version in sPHENIX GitHub at line 26 of file PHTruthSiliconAssociation.h
Constructor & Destructor Documentation
PHTruthSiliconAssociation::PHTruthSiliconAssociation (const std::string & name = "PHTruthSiliconAssociation")
Definition at line 29 of file PHTruthSiliconAssociation.cc.
View newest version in sPHENIX GitHub at line 29 of file PHTruthSiliconAssociation.cc
PHTruthSiliconAssociation::~PHTruthSiliconAssociation () virtual
Definition at line 36 of file PHTruthSiliconAssociation.cc.
View newest version in sPHENIX GitHub at line 36 of file PHTruthSiliconAssociation.cc
Member Function Documentation
int PHTruthSiliconAssociation::End (PHCompositeNode * topNode) override virtual
Called at the end of all processing.
Reimplemented from SubsysReco.
Definition at line 286 of file PHTruthSiliconAssociation.cc.
View newest version in sPHENIX GitHub at line 286 of file PHTruthSiliconAssociation.cc
References Fun4AllReturnCodes::EVENT_OK.
int PHTruthSiliconAssociation::EndRun (const int runnumber) override virtual
Called at the end of each run.
Reimplemented from SubsysReco.
Definition at line 280 of file PHTruthSiliconAssociation.cc.
View newest version in sPHENIX GitHub at line 280 of file PHTruthSiliconAssociation.cc
References Fun4AllReturnCodes::EVENT_OK.
std::vector< PHG4Particle * > PHTruthSiliconAssociation::getG4PrimaryParticle (SvtxTrack * track) private
Definition at line 359 of file PHTruthSiliconAssociation.cc.
View newest version in sPHENIX GitHub at line 359 of file PHTruthSiliconAssociation.cc
References _cluster_hit_map, _g4hits_intt, _g4hits_mvtx, _g4hits_tpc, _hit_truth_map, _truthinfo, SvtxTrack::begin_cluster_keys(), SvtxTrack::end_cluster_keys(), PHG4HitContainer::findHit(), PHG4Hit::get_trkid(), TrkrHitTruthAssoc::getG4Hits(), TrkrClusterHitAssoc::getHits(), TrkrDefs::getHitSetKeyFromClusKey(), PHG4TruthInfoContainer::GetParticle(), TrkrDefs::getTrkrId(), TrkrDefs::inttId, it, TrkrDefs::mvtxId, pid, TrkrDefs::tpcId, and Fun4AllBase::Verbosity().
Referenced by process_event().
int PHTruthSiliconAssociation::GetNodes (PHCompositeNode * topNode) private
Definition at line 303 of file PHTruthSiliconAssociation.cc.
View newest version in sPHENIX GitHub at line 303 of file PHTruthSiliconAssociation.cc
References _assoc_container, _cluster_hit_map, _cluster_map, _g4hits_intt, _g4hits_mvtx, _g4hits_tpc, _hit_truth_map, _track_map, _truthinfo, _vertex_map, Fun4AllReturnCodes::ABORTEVENT, Fun4AllReturnCodes::EVENT_OK, and PHWHERE.
Referenced by InitRun().
std::set< TrkrDefs::cluskey > PHTruthSiliconAssociation::getSiliconClustersFromParticle (PHG4Particle * g4particle) private
Definition at line 435 of file PHTruthSiliconAssociation.cc.
View newest version in sPHENIX GitHub at line 435 of file PHTruthSiliconAssociation.cc
References _cluster_hit_map, _cluster_map, _g4hits_intt, _g4hits_mvtx, _hit_truth_map, PHG4HitContainer::findHit(), PHG4Particle::get_track_id(), PHG4Hit::get_trkid(), TrkrClusterContainer::getClusters(), TrkrHitTruthAssoc::getG4Hits(), TrkrClusterHitAssoc::getHits(), TrkrDefs::getHitSetKeyFromClusKey(), TrkrDefs::getLayer(), TrkrDefs::getTrkrId(), TrkrDefs::inttId, and TrkrDefs::mvtxId.
Referenced by process_event().
int PHTruthSiliconAssociation::Init (PHCompositeNode * topNode) override virtual
Called during initialization. Typically this is where you can book histograms, and e.g. register them to Fun4AllServer (so they can be output to file using Fun4AllServer::dumpHistos() method).
Reimplemented from SubsysReco.
Definition at line 42 of file PHTruthSiliconAssociation.cc.
View newest version in sPHENIX GitHub at line 42 of file PHTruthSiliconAssociation.cc
References Fun4AllReturnCodes::EVENT_OK.
int PHTruthSiliconAssociation::InitRun (PHCompositeNode * topNode) override virtual
Called for first event when run number is known. Typically this is where you may want to fetch data from database, because you know the run number. A place to book histograms which have to know the run number.
Reimplemented from SubsysReco.
Definition at line 49 of file PHTruthSiliconAssociation.cc.
View newest version in sPHENIX GitHub at line 49 of file PHTruthSiliconAssociation.cc
References GetNodes().
void PHTruthSiliconAssociation::Print (const std::string & what = "ALL") const override virtual
Print out some info about this module.
Parameters
what can be used to specify what to print exactly.
Reimplemented from SubsysReco.
Definition at line 298 of file PHTruthSiliconAssociation.cc.
View newest version in sPHENIX GitHub at line 298 of file PHTruthSiliconAssociation.cc
int PHTruthSiliconAssociation::process_event (PHCompositeNode * topNode) override virtual
Called for each event. This is where you do the real work.
Reimplemented from SubsysReco.
Definition at line 57 of file PHTruthSiliconAssociation.cc.
View newest version in sPHENIX GitHub at line 57 of file PHTruthSiliconAssociation.cc
References _assoc_container, _track_map, _tracklet, _vertex_map, SvtxTrackMap::begin(), SvtxTrack::begin_cluster_keys(), SvtxTrackMap::end(), SvtxTrack::end_cluster_keys(), Fun4AllReturnCodes::EVENT_OK, SvtxVertexMap::get(), SvtxTrack::get_charge(), SvtxTrack::get_error(), SvtxTrack::get_eta(), SvtxTrack::get_id(), SvtxTrack::get_phi(), PHG4Particle::get_px(), SvtxTrack::get_px(), PHG4Particle::get_py(), SvtxTrack::get_py(), SvtxTrack::get_pz(), PHG4Particle::get_track_id(), SvtxTrack::get_vertex_id(), SvtxVertex::get_x(), SvtxTrack::get_x(), SvtxVertex::get_y(), SvtxTrack::get_y(), SvtxVertex::get_z(), SvtxTrack::get_z(), getG4PrimaryParticle(), TrkrDefs::getLayer(), getSiliconClustersFromParticle(), TrkrDefs::getTrkrId(), SvtxTrack::identify(), SvtxTrackMap::insert(), SvtxTrack::insert_cluster_key(), TrkrDefs::inttId, TrkrDefs::mvtxId, SvtxTrack::set_charge(), SvtxTrack::set_error(), SvtxTrack::set_id(), SvtxTrack::set_px(), SvtxTrack::set_py(), SvtxTrack::set_pz(), SvtxTrack::set_vertex_id(), SvtxTrack::set_x(), SvtxTrack::set_y(), SvtxTrack::set_z(), AssocInfoContainer::SetClusterTrackAssoc(), SvtxTrackMap::size(), SvtxTrack::size_cluster_keys(), and Fun4AllBase::Verbosity().
int PHTruthSiliconAssociation::Reset (PHCompositeNode * topNode) override virtual
Reset.
Reimplemented from SubsysReco.
Definition at line 292 of file PHTruthSiliconAssociation.cc.
View newest version in sPHENIX GitHub at line 292 of file PHTruthSiliconAssociation.cc
References Fun4AllReturnCodes::EVENT_OK.
int PHTruthSiliconAssociation::ResetEvent (PHCompositeNode * topNode) override virtual
Clean up internals after each event.
Reimplemented from SubsysReco.
Definition at line 273 of file PHTruthSiliconAssociation.cc.
View newest version in sPHENIX GitHub at line 273 of file PHTruthSiliconAssociation.cc
References Fun4AllReturnCodes::EVENT_OK.
Member Data Documentation
AssocInfoContainer* PHTruthSiliconAssociation::_assoc_container {nullptr} private
Definition at line 83 of file PHTruthSiliconAssociation.h.
View newest version in sPHENIX GitHub at line 83 of file PHTruthSiliconAssociation.h
Referenced by GetNodes(), and process_event().
TrkrClusterHitAssoc* PHTruthSiliconAssociation::_cluster_hit_map {nullptr} private
Definition at line 80 of file PHTruthSiliconAssociation.h.
View newest version in sPHENIX GitHub at line 80 of file PHTruthSiliconAssociation.h
Referenced by getG4PrimaryParticle(), GetNodes(), and getSiliconClustersFromParticle().
TrkrClusterContainer* PHTruthSiliconAssociation::_cluster_map {nullptr} private
Definition at line 79 of file PHTruthSiliconAssociation.h.
View newest version in sPHENIX GitHub at line 79 of file PHTruthSiliconAssociation.h
Referenced by GetNodes(), and getSiliconClustersFromParticle().
PHG4HitContainer* PHTruthSiliconAssociation::_g4hits_intt {nullptr} private
Definition at line 77 of file PHTruthSiliconAssociation.h.
View newest version in sPHENIX GitHub at line 77 of file PHTruthSiliconAssociation.h
Referenced by getG4PrimaryParticle(), GetNodes(), and getSiliconClustersFromParticle().
PHG4HitContainer* PHTruthSiliconAssociation::_g4hits_mvtx {nullptr} private
Definition at line 76 of file PHTruthSiliconAssociation.h.
View newest version in sPHENIX GitHub at line 76 of file PHTruthSiliconAssociation.h
Referenced by getG4PrimaryParticle(), GetNodes(), and getSiliconClustersFromParticle().
PHG4HitContainer* PHTruthSiliconAssociation::_g4hits_tpc {nullptr} private
Definition at line 75 of file PHTruthSiliconAssociation.h.
View newest version in sPHENIX GitHub at line 75 of file PHTruthSiliconAssociation.h
Referenced by getG4PrimaryParticle(), and GetNodes().
TrkrHitTruthAssoc* PHTruthSiliconAssociation::_hit_truth_map {nullptr} private
Definition at line 81 of file PHTruthSiliconAssociation.h.
View newest version in sPHENIX GitHub at line 81 of file PHTruthSiliconAssociation.h
Referenced by getG4PrimaryParticle(), GetNodes(), and getSiliconClustersFromParticle().
SvtxTrackMap* PHTruthSiliconAssociation::_track_map {nullptr} private
Definition at line 82 of file PHTruthSiliconAssociation.h.
View newest version in sPHENIX GitHub at line 82 of file PHTruthSiliconAssociation.h
Referenced by GetNodes(), and process_event().
SvtxTrack* PHTruthSiliconAssociation::_tracklet {nullptr} private
Definition at line 84 of file PHTruthSiliconAssociation.h.
View newest version in sPHENIX GitHub at line 84 of file PHTruthSiliconAssociation.h
Referenced by process_event().
PHG4TruthInfoContainer* PHTruthSiliconAssociation::_truthinfo {nullptr} private
Definition at line 74 of file PHTruthSiliconAssociation.h.
View newest version in sPHENIX GitHub at line 74 of file PHTruthSiliconAssociation.h
Referenced by getG4PrimaryParticle(), and GetNodes().
SvtxVertexMap* PHTruthSiliconAssociation::_vertex_map {nullptr} private
Definition at line 85 of file PHTruthSiliconAssociation.h.
View newest version in sPHENIX GitHub at line 85 of file PHTruthSiliconAssociation.h
Referenced by GetNodes(), and process_event().
The documentation for this class was generated from the following files:
fun4all_coresoftware/blob/master/offline/packages/trackreco/PHTruthSiliconAssociation.h
fun4all_coresoftware/blob/master/offline/packages/trackreco/PHTruthSiliconAssociation.cc