EIC Software: charm_jet_cross_section Namespace Reference
charm_jet_cross_section Namespace Reference
Functions
def DifferentialXS
def DrawDiffXSPlot
def DifferentialTaggingYield
def DrawDiffTagYieldPlot
def DifferentialTaggingEfficiency
Tagging Efficiency Flavour tagging study code.
def DrawDiffTagEfficiencyPlot
Variables
int u_fb 1
int u_mb 1
list branchlist ["Jet.PT", "Jet.Eta", "Jet.Flavor", "Jet.BTag", "GenJet.PT", "GenJet.Eta", "GenJet.Flavor"]
dataset dictionary (cross-sections, etc.) global xs_map xs_map = {} xs_map['CC_DIS_e18_p275_B15'] = 2.408e-08*u_mb # from PYTHIA8 xs_map['NC_DIS_e18_p275_B15'] = 3.671e-06*u_mb # from PYTHIA8
tuple df_ct18nnlo
dictionary draw_config_pt {}
Charged Current Scattering.
Function Documentation
def charm_jet_cross_section.DifferentialTaggingEfficiency (df, x = 'Jet.PT', xrange = [10, xbins = [10, which = 'all')
Tagging Efficiency Flavour tagging study code.
Definition at line 459 of file charm_jet_cross_section.py.
View newest version in sPHENIX GitHub at line 459 of file charm_jet_cross_section.py
References print().
Referenced by DrawDiffTagEfficiencyPlot().
def charm_jet_cross_section.DifferentialTaggingYield (df, x = 'Jet.PT', xrange = [10, xbins = [10, which = 'all', process = 'CC_DIS_e18_p275_B15')
Definition at line 315 of file charm_jet_cross_section.py.
View newest version in sPHENIX GitHub at line 315 of file charm_jet_cross_section.py
References print().
Referenced by DrawDiffTagYieldPlot().
def charm_jet_cross_section.DifferentialXS (df, x = 'GenJet.PT', xrange = [10, xbins = [10, which = 'all', process = 'CC_DIS_e18_p275')
Definition at line 70 of file charm_jet_cross_section.py.
View newest version in sPHENIX GitHub at line 70 of file charm_jet_cross_section.py
References print().
Referenced by DrawDiffXSPlot().
def charm_jet_cross_section.DrawDiffTagEfficiencyPlot (draw_config = {})
Definition at line 523 of file charm_jet_cross_section.py.
View newest version in sPHENIX GitHub at line 523 of file charm_jet_cross_section.py
References DifferentialTaggingEfficiency().
def charm_jet_cross_section.DrawDiffTagYieldPlot (draw_config = {}, process = 'CC_DIS_e18_p275')
Definition at line 385 of file charm_jet_cross_section.py.
View newest version in sPHENIX GitHub at line 385 of file charm_jet_cross_section.py
References DifferentialTaggingYield().
def charm_jet_cross_section.DrawDiffXSPlot (draw_config = {}, process = 'CC_DIS_e18_p275')
Definition at line 134 of file charm_jet_cross_section.py.
View newest version in sPHENIX GitHub at line 134 of file charm_jet_cross_section.py
References DifferentialXS().
Variable Documentation
list charm_jet_cross_section.branchlist ["Jet.PT", "Jet.Eta", "Jet.Flavor", "Jet.BTag", "GenJet.PT", "GenJet.Eta", "GenJet.Flavor"]
dataset dictionary (cross-sections, etc.) global xs_map xs_map = {} xs_map['CC_DIS_e18_p275_B15'] = 2.408e-08*u_mb # from PYTHIA8 xs_map['NC_DIS_e18_p275_B15'] = 3.671e-06*u_mb # from PYTHIA8
Definition at line 43 of file charm_jet_cross_section.py.
View newest version in sPHENIX GitHub at line 43 of file charm_jet_cross_section.py
tuple charm_jet_cross_section.df_ct18nnlo
Initial value:
 eat.UprootLoad([f"../CC_DIS_e10_p275_B15_dR5_maxIP3mm_trkpt10_22sigmin_CT18NNLO/*/out.root"], "Delphes",
                              branches=branchlist)
Definition at line 46 of file charm_jet_cross_section.py.
View newest version in sPHENIX GitHub at line 46 of file charm_jet_cross_section.py
dictionary charm_jet_cross_section.draw_config_pt {}
Charged Current Scattering.
Neutral Current Scattering
Definition at line 303 of file charm_jet_cross_section.py.
View newest version in sPHENIX GitHub at line 303 of file charm_jet_cross_section.py
int charm_jet_cross_section.u_fb 1
Definition at line 30 of file charm_jet_cross_section.py.
View newest version in sPHENIX GitHub at line 30 of file charm_jet_cross_section.py
int charm_jet_cross_section.u_mb 1
Definition at line 31 of file charm_jet_cross_section.py.
View newest version in sPHENIX GitHub at line 31 of file charm_jet_cross_section.py