EIC Software: FairParGenericSet Class Reference
FairParGenericSet Class Reference abstract
#include <EicRoot/blob/master/parbase/FairParGenericSet.h>
Public Member Functions
FairParGenericSet (const char *name, const char *title, const char *context)
virtual ~FairParGenericSet ()
virtual void putParams (FairParamList *)=0
virtual Bool_t getParams (FairParamList *)=0
virtual void printParams ()
Bool_t init (FairParIo *inp)
Int_t write (FairParIo *output)
Public Member Functions inherited from FairParSet
FairParSet (const char *name="", const char *title="", const char *context="")
virtual ~FairParSet ()
virtual Bool_t init ()
virtual Int_t write ()
virtual void clear ()
virtual void print ()
const char * getDetectorName ()
void resetInputVersions ()
void setInputVersion (Int_t v=-1, Int_t i=0)
Int_t getInputVersion (Int_t i)
void setStatic (Bool_t flag=kTRUE)
Bool_t isStatic ()
void setChanged (Bool_t flag=kTRUE)
Bool_t hasChanged ()
const char * getParamContext () const
void setAuthor (const char *s)
const char * getAuthor () const
void setDescription (const char *s)
const char * getDescription () const
void copyComment (FairParSet &r)
Protected Member Functions
FairParGenericSet ()
Additional Inherited Members
Protected Attributes inherited from FairParSet
TString detName
Int_t versions [3]
name of the detector the container belongs to
Bool_t status
versions of container in the 2 possible inputs
Bool_t changed
static flag
TString paramContext
flag is kTRUE if parameters have changed
TString author
TString description
FairLogger * fLogger
Detailed Description
Definition at line 10 of file FairParGenericSet.h.
View newest version in sPHENIX GitHub at line 10 of file FairParGenericSet.h
Constructor & Destructor Documentation
FairParGenericSet::FairParGenericSet (const char * name, const char * title, const char * context) inline
Definition at line 13 of file FairParGenericSet.h.
View newest version in sPHENIX GitHub at line 13 of file FairParGenericSet.h
virtual FairParGenericSet::~FairParGenericSet () inline virtual
Definition at line 15 of file FairParGenericSet.h.
View newest version in sPHENIX GitHub at line 15 of file FairParGenericSet.h
FairParGenericSet::FairParGenericSet () inline protected
Definition at line 25 of file FairParGenericSet.h.
View newest version in sPHENIX GitHub at line 25 of file FairParGenericSet.h
Member Function Documentation
virtual Bool_t FairParGenericSet::getParams (FairParamList *) pure virtual
Implemented in FairBaseParSet, CbmGeoRichPar, PndMapPar, PndMultiFieldPar, PndConstPar, PndFieldPar, PndSensorNamePar, EicGeoPar, and PndGeoPassivePar.
Bool_t FairParGenericSet::init (FairParIo * inp) virtual
Reimplemented from FairParSet.
void FairParGenericSet::printParams () virtual
Definition at line 49 of file FairParGenericSet.cxx.
View newest version in sPHENIX GitHub at line 49 of file FairParGenericSet.cxx
References FairParSet::author, FairParSet::description, FairParSet::paramContext, FairParamList::print(), and putParams().
virtual void FairParGenericSet::putParams (FairParamList *) pure virtual
Implemented in CbmGeoRichPar, FairBaseParSet, PndMapPar, PndMultiFieldPar, PndConstPar, PndSensorNamePar, PndFieldPar, EicGeoPar, and PndGeoPassivePar.
Referenced by printParams(), FairGenericParAsciiFileIo::writeGenericSet(), and FairGenericParTSQLIo::writeSet().
Int_t FairParGenericSet::write (FairParIo * output) virtual
Reimplemented from FairParSet.
Definition at line 41 of file FairParGenericSet.cxx.
View newest version in sPHENIX GitHub at line 41 of file FairParGenericSet.cxx
References FairParIo::getDetParIo(), and FairDetParIo::write().
The documentation for this class was generated from the following files:
EicRoot/blob/master/parbase/FairParGenericSet.h
EicRoot/blob/master/parbase/FairParGenericSet.cxx