EIC Software: CbmMCEntry Class Reference
CbmMCEntry Class Reference
#include <EicRoot/blob/master/cbmbase/CbmMCEntry.h>
Public Member Functions
CbmMCEntry ()
CbmMCEntry (std::set< FairLink > links, Int_t source=-1, Int_t pos=-1)
CbmMCEntry (FairMultiLinkedData links, Int_t source=-1, Int_t pos=-1)
void SetSource (Int_t source)
void SetPos (Int_t pos)
Int_t GetSource () const
Int_t GetPos () const
virtual ~CbmMCEntry ()
virtual void Print (std::ostream &out)
Public Member Functions inherited from FairMultiLinkedData
FairMultiLinkedData ()
Default constructor.
FairMultiLinkedData (std::set< FairLink > links, Bool_t persistanceCheck=kTRUE)
Constructor.
FairMultiLinkedData (TString dataType, std::vector< Int_t > links, Int_t fileId=-1, Int_t evtId=-1, Bool_t persistanceCheck=kTRUE, Bool_t bypass=kFALSE, Float_t mult=1.0)
Constructor.
FairMultiLinkedData (Int_t dataType, std::vector< Int_t > links, Int_t fileId=-1, Int_t evtId=-1, Bool_t persistanceCheck=kTRUE, Bool_t bypass=kFALSE, Float_t mult=1.0)
Constructor.
virtual ~FairMultiLinkedData ()
virtual std::set< FairLink > GetLinks () const
returns stored links as FairLinks
virtual Int_t GetNLinks () const
returns the number of stored links
virtual FairLink GetLink (Int_t pos) const
returns the FairLink at the given position
virtual FairMultiLinkedData GetLinksWithType (Int_t type) const
Gives you a list of links which contain the given type.
TObject * GetData (FairLink &myLink)
Get the TObject the Link is pointing to.
virtual Int_t GetDefaultType ()
Bool_t GetPersistanceCheck ()
Returns the value of PersistanceCheck.
Int_t GetVerbose ()
Returns the verbosity level.
virtual void SetDefaultType (Int_t type)
virtual void SetPersistanceCheck (Bool_t check)
Controls if a persistance check of a link is done or not.
virtual void SetVerbose (Int_t level)
Sets the verbosity level.
virtual void SetLinks (FairMultiLinkedData links, Float_t mult=1.0)
Sets the links as vector of FairLink.
virtual void SetLink (FairLink link, Bool_t bypass=kFALSE, Float_t mult=1.0)
Sets the Links with a single FairLink.
virtual void AddLinks (FairMultiLinkedData links, Float_t mult=1.0)
Adds a List of FairLinks (FairMultiLinkedData) to fLinks.
virtual void AddLink (FairLink link, Bool_t bypass=kFALSE, Float_t mult=1.0)
Adds a FairLink link at the end of fLinks. If multi is kTRUE a link is allowed more than once otherwise it is stored only once.
virtual void InsertLink (FairLink link)
Inserts a link into the list of links without persistance checking.
virtual void AddAllWeights (Double_t weight)
Adds weight to all Links.
virtual void SetAllWeights (Double_t weight)
Sets a common weight for Links.
virtual void MultiplyAllWeights (Double_t weight)
Multiplies all Links with weight.
virtual Bool_t IsLinkInList (FairLink link)
Test if a given link is in fLinks.
virtual Bool_t IsLinkInList (Int_t type, Int_t index)
Same as IsLinkInList(FairLink) just with type and index given separately.
virtual Int_t LinkPosInList (FairLink link)
returns position of link in fLinks. If it is not in the list -1 is returned
virtual Int_t LinkPosInList (Int_t type, Int_t index)
Same as LinkPosInList(FairLink)
virtual void DeleteLink (FairLink link)
Deletes a link ouf of fLinks.
virtual void DeleteLink (Int_t type, Int_t index)
Deletes a link ouf of fLinks.
virtual void Reset ()
virtual void ResetLinks ()
Clears fLinks.
void Print (std::ostream &out=std::cout) const
Output.
Private Member Functions
ClassDef (CbmMCEntry, 1)
Private Attributes
Int_t fSource
Int_t fPos
Friends
std::ostream & operator<< (std::ostream &out, const CbmMCEntry &link)
Additional Inherited Members
Protected Member Functions inherited from FairMultiLinkedData
virtual void SimpleAddLinks (Int_t fileId, Int_t evtId, Int_t dataType, std::vector< Int_t > links, Bool_t bypass, Float_t mult)
ClassDef (FairMultiLinkedData, 3)
Protected Attributes inherited from FairMultiLinkedData
std::set< FairLink > fLinks
Bool_t fPersistanceCheck
Int_t fVerbose
Int_t fDefaultType
Detailed Description
Definition at line 21 of file CbmMCEntry.h.
View newest version in sPHENIX GitHub at line 21 of file CbmMCEntry.h
Constructor & Destructor Documentation
CbmMCEntry::CbmMCEntry ()
Definition at line 12 of file CbmMCEntry.cxx.
View newest version in sPHENIX GitHub at line 12 of file CbmMCEntry.cxx
CbmMCEntry::CbmMCEntry (std::set< FairLink > links, Int_t source = -1, Int_t pos = -1) inline
Definition at line 25 of file CbmMCEntry.h.
View newest version in sPHENIX GitHub at line 25 of file CbmMCEntry.h
CbmMCEntry::CbmMCEntry (FairMultiLinkedData links, Int_t source = -1, Int_t pos = -1) inline
Definition at line 27 of file CbmMCEntry.h.
View newest version in sPHENIX GitHub at line 27 of file CbmMCEntry.h
CbmMCEntry::~CbmMCEntry () virtual
Definition at line 17 of file CbmMCEntry.cxx.
View newest version in sPHENIX GitHub at line 17 of file CbmMCEntry.cxx
Member Function Documentation
CbmMCEntry::ClassDef (CbmMCEntry , 1) private
Int_t CbmMCEntry::GetPos () const inline
Definition at line 37 of file CbmMCEntry.h.
View newest version in sPHENIX GitHub at line 37 of file CbmMCEntry.h
References fPos.
Referenced by CbmMCObject::SetEntry().
Int_t CbmMCEntry::GetSource () const inline
Definition at line 36 of file CbmMCEntry.h.
View newest version in sPHENIX GitHub at line 36 of file CbmMCEntry.h
References fSource.
Referenced by CbmMCMatch::GetNextStage(), and CbmMCMatch::LoadInMCLists().
virtual void CbmMCEntry::Print (std::ostream & out) inline virtual
Definition at line 41 of file CbmMCEntry.h.
View newest version in sPHENIX GitHub at line 41 of file CbmMCEntry.h
void CbmMCEntry::SetPos (Int_t pos) inline
Definition at line 34 of file CbmMCEntry.h.
View newest version in sPHENIX GitHub at line 34 of file CbmMCEntry.h
References fPos, and pos().
Referenced by CbmMCObject::AdoptSize(), CbmMCMatch::GetMCInfoForward(), and CbmMCObject::SetEntry().
void CbmMCEntry::SetSource (Int_t source) inline
Definition at line 33 of file CbmMCEntry.h.
View newest version in sPHENIX GitHub at line 33 of file CbmMCEntry.h
References fSource.
Referenced by CbmMCObject::AdoptSize(), and CbmMCMatch::GetMCInfoForward().
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & out, const CbmMCEntry & link) friend
Definition at line 45 of file CbmMCEntry.h.
View newest version in sPHENIX GitHub at line 45 of file CbmMCEntry.h
Member Data Documentation
Int_t CbmMCEntry::fPos private
Definition at line 54 of file CbmMCEntry.h.
View newest version in sPHENIX GitHub at line 54 of file CbmMCEntry.h
Referenced by GetPos(), and SetPos().
Int_t CbmMCEntry::fSource private
Definition at line 53 of file CbmMCEntry.h.
View newest version in sPHENIX GitHub at line 53 of file CbmMCEntry.h
Referenced by GetSource(), and SetSource().
The documentation for this class was generated from the following files:
EicRoot/blob/master/cbmbase/CbmMCEntry.h
EicRoot/blob/master/cbmbase/CbmMCEntry.cxx