EIC Software: acts/blob/sPHENIX/Core/src/Material/MaterialSlab.cpp File Reference
MaterialSlab.cpp File Reference
#include "Acts/Material/MaterialSlab.hpp"
#include "Acts/Material/detail/AverageMaterials.hpp"
#include <climits>
#include <limits>
#include <ostream>
Variables
static constexpr auto eps = 2 * std::numeric_limits<float>::epsilon()
Variable Documentation
constexpr auto eps = 2 * std::numeric_limits<float>::epsilon() static
Definition at line 17 of file MaterialSlab.cpp.
View newest version in sPHENIX GitHub at line 17 of file MaterialSlab.cpp
Referenced by Acts::Test::BOOST_AUTO_TEST_CASE(), BOOST_AUTO_TEST_CASE(), BOOST_DATA_TEST_CASE(), calcta(), Acts::computeEnergyLossBethe(), Acts::computeEnergyLossLandau(), CreateKnotsExtruded(), CylindricalCoordinateImprove(), CylindricalCoordinateTransformation(), Acts::deriveEnergyLossBetheQOverP(), Acts::deriveEnergyLossLandauQOverP(), expai(), expaid(), fg(), fgp(), FindBoundaryBoundary(), FindBulkBoundary(), FindPeriodicNodes(), flintg(), fltabl(), fordop(), gadap(), gadap2(), gadapf(), gauss1(), gauss2(), gauss3(), gauss4(), generatez(), getmass(), gbl::VSymMatrix::invert(), tetgenmesh::linelineint(), lqcdpr(), lweits(), lxsect(), makesplitting(), odeint(), pepsimainerhic(), beamBeamSystem::probabilityOfPhotonBreakup(), pygaga(), pygau2(), pygaus(), pyhii3au(), pyhisigh(), pyhiw1au(), pyhiw2au(), pyhiwidt(), pyi3au(), pykmap(), pymirm(), pypole(), pyrand(), pyrvgw(), pystat(), pytbdy(), pywaux(), pywidt(), pyxtot(), rkstepper(), SeparateCartesianBoundaries(), SeparateMainaxisBoundaries(), serai(), seraid(), and SetElementDivisionCylinder().