EIC Software: RootOut Class Reference
RootOut Class Reference
#include <Fun4All-lmon/blob/master/source/RootOut.h>
Public Member Functions
RootOut ()
void SetFileName (const std::string &fname)
void Open ()
void Close ()
TTree * GetTree ()
void FillTree ()
Private Attributes
std::string fOutputName
TFile * fOut
TTree * fDetTree
Detailed Description
Definition at line 11 of file RootOut.h.
View newest version in sPHENIX GitHub at line 11 of file RootOut.h
Constructor & Destructor Documentation
RootOut::RootOut ()
Definition at line 25 of file RootOut.cxx.
View newest version in sPHENIX GitHub at line 25 of file RootOut.cxx
References fOutputName.
Member Function Documentation
void RootOut::Close ()
Definition at line 69 of file RootOut.cxx.
View newest version in sPHENIX GitHub at line 69 of file RootOut.cxx
References fDetTree, and fOut.
Referenced by G4LmonEventAction::~G4LmonEventAction().
void RootOut::FillTree ()
Definition at line 62 of file RootOut.cxx.
View newest version in sPHENIX GitHub at line 62 of file RootOut.cxx
References fDetTree.
Referenced by G4LmonEventAction::EndOfEventAction().
TTree* RootOut::GetTree () inline
Definition at line 20 of file RootOut.h.
View newest version in sPHENIX GitHub at line 20 of file RootOut.h
References fDetTree.
Referenced by Cell::Cell(), CompCal::CompCal(), and G4LmonDetector::ConstructMe().
void RootOut::Open (void)
Definition at line 35 of file RootOut.cxx.
View newest version in sPHENIX GitHub at line 35 of file RootOut.cxx
References exit(), fDetTree, fOut, and fOutputName.
Referenced by G4LmonSubsystem::Init().
void RootOut::SetFileName (const std::string & fname) inline
Definition at line 16 of file RootOut.h.
View newest version in sPHENIX GitHub at line 16 of file RootOut.h
References fOutputName.
Referenced by G4LmonSubsystem::Init().
Member Data Documentation
TTree* RootOut::fDetTree private
Definition at line 28 of file RootOut.h.
View newest version in sPHENIX GitHub at line 28 of file RootOut.h
Referenced by Close(), FillTree(), GetTree(), and Open().
TFile* RootOut::fOut private
Definition at line 27 of file RootOut.h.
View newest version in sPHENIX GitHub at line 27 of file RootOut.h
Referenced by Close(), and Open().
std::string RootOut::fOutputName private
Definition at line 25 of file RootOut.h.
View newest version in sPHENIX GitHub at line 25 of file RootOut.h
Referenced by Open(), RootOut(), and SetFileName().
The documentation for this class was generated from the following files:
Fun4All-lmon/blob/master/source/RootOut.h
Fun4All-lmon/blob/master/source/RootOut.cxx