EIC Software: HtcKalmanFilter Class Reference
HtcKalmanFilter Class Reference
#include <EicRoot/blob/master/eic/htc/EicHtcTask.h>
Public Member Functions
HtcKalmanFilter ()
HtcKalmanFilter (MfieldMode mode)
~HtcKalmanFilter ()
int KalmanFilterMagneticField (TVector3 &xx, TVector3 &B)
Public Member Functions inherited from TrKalmanFilter
TrKalmanFilter (MfieldMode fieldMode=WithField)
t_particle_group * SetParticleGroup (const char *group)
MfieldMode GetFieldMode () const
int Configure (MediaBank *media_bank, StringList *config)
int InitializeRungeKuttaFrames ()
int InitializeMediaSlices (MediaBank *media_bank)
void SetLocationSeparationDistance (double value)
int CalculateHMatrix (KalmanNode *node)
int Transport (KalmanNode *from, KalmanFilter::Direction fb, unsigned mode)
int TransportExtra (KalmanNode *from, KalmanFilter::Direction fb, unsigned mode)
void ResetNode (TrKalmanNode *node, double S[], int assignmentMode)
void SelectActiveNodes ()
void SetUpLocations ()
TrKalmanNodeLocation * GetLocationHead () const
void BuildNodeList ()
void AccountEnergyLosses (bool flag)
Public Member Functions inherited from KalmanFilter
KalmanFilter (int sdim)
~KalmanFilter ()
void SetVerbosity (Verbosity verb)
void SetXmCalculationFlag (bool flag)
void SetNodeGapMax (double value)
void SetMinFilterChiSquareCCDF (double value)
double GetMinFilterChiSquareCCDF () const
void SetMinSmootherChiSquareCCDF (double value)
void SetPositivityFixParameters (double maxFixablePositivityScrewup, double positivityCorrelationFix)
void SetRFCutoffValue (double value)
KalmanNode * AddNode (const char *name, double z, int mdim, const bool nonLinearTransportFlags[2])
KalmanNode * AddNodeWrapper (const char *name, const char *format, double z, int mdim)
int Configure (const StringList *config)
unsigned FilterPass (KalmanNode *start, KalmanNode *end, KalmanFilter::Direction fb)
unsigned FullChain (KalmanNode *start, KalmanNode *end, KalmanFilter::Direction fb, int mode)
void ResetFiredFlags ()
void HackGroupHitCountLimit (unsigned min)
void LatchGroupNdfControlFlags ()
KalmanNode * GetHead () const
KalmanNode * GetTail () const
int GetFilterNdf () const
double GetFilterChiSquare () const
double GetFilterChiSquareCCDF () const
int SmootherPass ()
void SetExtraNdfCount (int count)
Private Member Functions
MgridSlice * InitializeMgridSlice (double z0)
Private Attributes
MgridSlice * mMgslices
Additional Inherited Members
Public Types inherited from KalmanFilter
enum Direction { Undefined = -1, Forward, Backward }
enum Verbosity { Never, Error, Warning, Info }
Protected Attributes inherited from TrKalmanFilter
double mLocationSeparationDistance
TrKalmanNodeLocation * mLocationHead
TrKalmanNodeLocation * mLocationTail
Detailed Description
Definition at line 183 of file EicHtcTask.h.
View newest version in sPHENIX GitHub at line 183 of file EicHtcTask.h
Constructor & Destructor Documentation
HtcKalmanFilter::HtcKalmanFilter () inline
Definition at line 185 of file EicHtcTask.h.
View newest version in sPHENIX GitHub at line 185 of file EicHtcTask.h
HtcKalmanFilter::HtcKalmanFilter (MfieldMode mode) inline
Definition at line 186 of file EicHtcTask.h.
View newest version in sPHENIX GitHub at line 186 of file EicHtcTask.h
HtcKalmanFilter::~HtcKalmanFilter () inline
Definition at line 187 of file EicHtcTask.h.
View newest version in sPHENIX GitHub at line 187 of file EicHtcTask.h
Member Function Documentation
MgridSlice * HtcKalmanFilter::InitializeMgridSlice (double z0) private virtual
Implements TrKalmanFilter.
Definition at line 69 of file EicHtcTask.cxx.
View newest version in sPHENIX GitHub at line 69 of file EicHtcTask.cxx
References _CARTESIAN_, _FIELD_COMPONENT_VALUES_, _MG_CELL_SIZE_, _MG_WIDTH_, _X_, _Y_, _Z_, MgridCell::B, create_single_mgrid_header(), Acts::Test::dim, Mgrid::getCellNum(), Mgrid::initializeAsSingleMgrid(), ip(), KalmanFilterMagneticField(), Mgrid::linearAddrToCellPtr(), Mgrid::linearAddrToCoord(), Mgrid::markCellAsSafe(), max, MgridSlice::mGrid, min, mMgslices, MgridSlice::mNext, MgridSlice::mZ0, printf(), RK_htci, Mgrid::setHtcInterpolationMode(), and XYZ.
int HtcKalmanFilter::KalmanFilterMagneticField (TVector3 & xx, TVector3 & B)
Definition at line 287 of file EicHtcTask.cxx.
View newest version in sPHENIX GitHub at line 287 of file EicHtcTask.cxx
References FairRunAna::GetField(), FairRunAna::Instance(), and x.
Referenced by InitializeMgridSlice().
Member Data Documentation
MgridSlice* HtcKalmanFilter::mMgslices private
Definition at line 192 of file EicHtcTask.h.
View newest version in sPHENIX GitHub at line 192 of file EicHtcTask.h
Referenced by InitializeMgridSlice().
The documentation for this class was generated from the following files:
EicRoot/blob/master/eic/htc/EicHtcTask.h
EicRoot/blob/master/eic/htc/EicHtcTask.cxx