EIC Software: Smear::ParticleMCS Class Reference
Smear::ParticleMCS Class Reference
#include <eic-smear/blob/master/include/eicsmear/smear/ParticleMCS.h>
Public Member Functions
virtual ~ParticleMCS ()
ParticleMCS ()
ParticleMCS (const TLorentzVector &, int pdg, int status)
ParticleMCS (const ParticleMCS &)=delete
ParticleMCS & operator= (const ParticleMCS &)=delete
virtual Double_t GetPx () const
virtual Double_t GetPy () const
virtual Double_t GetPz () const
virtual Double_t GetE () const
virtual TLorentzVector Get4Vector () const
virtual TLorentzVector PxPyPzE () const
virtual Double_t GetM () const
virtual Double_t GetPt () const
virtual TVector3 GetVertex () const
virtual Double_t GetP () const
virtual Double_t GetTheta () const
virtual Double_t GetPhi () const
virtual Double_t GetRapidity () const
virtual Double_t GetEta () const
virtual UShort_t GetStatus () const
virtual ::erhic::Pid Id () const
double GetNumSigma () const
int GetNumSigmaType () const
virtual bool IsSmeared () const
virtual bool IsESmeared () const
virtual bool IsPSmeared () const
virtual bool IsPtSmeared () const
virtual bool IsPxSmeared () const
virtual bool IsPySmeared () const
virtual bool IsPzSmeared () const
virtual bool IsThetaSmeared () const
virtual bool IsPhiSmeared () const
virtual bool IsIdSmeared () const
virtual bool IsNumSigmaSmeared () const
virtual void SetE (const Double_t value, const bool CheckSetSmearFlag=true)
virtual void SetP (const Double_t value, const bool CheckSetSmearFlag=true)
virtual void SetPt (const Double_t value, const bool CheckSetSmearFlag=true)
virtual void SetPx (const Double_t value, const bool CheckSetSmearFlag=true)
virtual void SetPy (const Double_t value, const bool CheckSetSmearFlag=true)
virtual void SetPz (const Double_t value, const bool CheckSetSmearFlag=true)
virtual void SetPhi (const Double_t value, const bool CheckSetSmearFlag=true)
virtual void SetTheta (const Double_t value, const bool CheckSetSmearFlag=true)
virtual void SetId (Int_t value, const bool CheckSetSmearFlag=true)
virtual void SetNumSigma (const double d, const bool CheckSetSmearFlag=true)
virtual void SetNumSigmaType (const int i)
virtual void SetSmeared (bool flag=true)
virtual void SetESmeared (bool flag=true)
virtual void SetPSmeared (bool flag=true)
virtual void SetPtSmeared (bool flag=true)
virtual void SetPxSmeared (bool flag=true)
virtual void SetPySmeared (bool flag=true)
virtual void SetPzSmeared (bool flag=true)
virtual void SetThetaSmeared (bool flag=true)
virtual void SetPhiSmeared (bool flag=true)
virtual void SetIdSmeared (bool flag=true)
virtual void SetNumSigmaSmeared (bool flag=true)
void Set4Vector (const TLorentzVector &)
virtual void SetStatus (Int_t)
virtual UShort_t GetParentIndex () const
virtual void Print (Option_t *="") const
virtual void SetVertex (const TVector3 &)
virtual void SetVariable (const double z, const KinType kin)
void HandleBogusValues (const KinType kin)
Public Member Functions inherited from erhic::VirtualParticle
virtual ~VirtualParticle ()
Protected Attributes
bool kParticleSmeared =false
bool kESmeared =false
bool kPSmeared =false
bool kPtSmeared =false
bool kPxSmeared =false
bool kPySmeared =false
bool kPzSmeared =false
bool kThetaSmeared =false
bool kPhiSmeared =false
bool kIdSmeared =false
bool kNumSigmaSmeared =false
UShort_t status
Status code.
Int_t id
PDG particle code.
Double32_t px
x component of particle momentum
Double32_t py
y component of particle momentum
Double32_t pz
z component of particle momentum
Double32_t E
Energy of particle.
Double32_t pt
Transverse momentum of particle.
Double32_t p
Total momentum of particle.
Double32_t theta
Polar angle.
Double32_t phi
Azimuthal angle.
double numSigma
PID: nSigma deviation.
int numSigmaType
PID: nSigma deviation type. pi_k == 1, k_p == 2. : This should be agreed upon and fixed better.
Detailed Description
A smeared Monte Carlo particle.
Definition at line 28 of file ParticleMCS.h.
View newest version in sPHENIX GitHub at line 28 of file ParticleMCS.h
Constructor & Destructor Documentation
Smear::ParticleMCS::~ParticleMCS () virtual
Destructor.
Definition at line 51 of file ParticleMCS.cxx.
View newest version in sPHENIX GitHub at line 51 of file ParticleMCS.cxx
Smear::ParticleMCS::ParticleMCS ()
Default constructor. Initialises the Particle from the argument string with the format I KS id orig daughter ldaughter px py pz m E xv yv zv
Definition at line 19 of file ParticleMCS.cxx.
View newest version in sPHENIX GitHub at line 19 of file ParticleMCS.cxx
Smear::ParticleMCS::ParticleMCS (const TLorentzVector & ep, int pdg, int status)
Construct from an E-p 4-vector, pdg code and status code.
Definition at line 35 of file ParticleMCS.cxx.
View newest version in sPHENIX GitHub at line 35 of file ParticleMCS.cxx
Smear::ParticleMCS::ParticleMCS (const ParticleMCS &) delete
Member Function Documentation
TLorentzVector Smear::ParticleMCS::Get4Vector () const virtual
Returns the (E,p) 4-vector in the lab frame.
Implements erhic::VirtualParticle.
Definition at line 54 of file ParticleMCS.cxx.
View newest version in sPHENIX GitHub at line 54 of file ParticleMCS.cxx
References E, px, py, and pz.
Referenced by DoSmearStep(), and PxPyPzE().
Double_t Smear::ParticleMCS::GetE () const virtual
Returns the energy of the particle in the lab frame.
Implements erhic::VirtualParticle.
Definition at line 117 of file ParticleMCS.cxx.
View newest version in sPHENIX GitHub at line 117 of file ParticleMCS.cxx
References E.
Referenced by DoSmearStep(), FillParticleQA(), Smear::Bremsstrahlung::FixParticleKinematics(), HandleBogusValues(), and main().
Double_t Smear::ParticleMCS::GetEta () const virtual
Returns the pseudorapidity.
Implements erhic::VirtualParticle.
Definition at line 76 of file ParticleMCS.cxx.
View newest version in sPHENIX GitHub at line 76 of file ParticleMCS.cxx
References Acts::VectorHelpers::eta(), GetTheta(), and theta.
Referenced by FillParticleQA().
Double_t Smear::ParticleMCS::GetM () const virtual
Returns the apparent mass of the smeared particle.
Implements erhic::VirtualParticle.
Definition at line 121 of file ParticleMCS.cxx.
View newest version in sPHENIX GitHub at line 121 of file ParticleMCS.cxx
References E, and p.
Referenced by Smear::Bremsstrahlung::FixParticleKinematics().
double Smear::ParticleMCS::GetNumSigma () const
Returns the numSigma deviation of this particle
Definition at line 149 of file ParticleMCS.cxx.
View newest version in sPHENIX GitHub at line 149 of file ParticleMCS.cxx
References numSigma.
int Smear::ParticleMCS::GetNumSigmaType () const
Returns the numSigma deviation type (pi_k, k_p) of this particle
Definition at line 153 of file ParticleMCS.cxx.
View newest version in sPHENIX GitHub at line 153 of file ParticleMCS.cxx
References numSigmaType.
Double_t Smear::ParticleMCS::GetP () const virtual
Returns the total momentum (GeV).
Implements erhic::VirtualParticle.
Definition at line 133 of file ParticleMCS.cxx.
View newest version in sPHENIX GitHub at line 133 of file ParticleMCS.cxx
References p.
Referenced by DoSmearStep(), FillParticleQA(), Smear::Bremsstrahlung::FixParticleKinematics(), HandleBogusValues(), main(), Smear::Tracker::Smear(), Smear::Detector::Smear(), and Smear::ParticleID::Smear().
virtual UShort_t Smear::ParticleMCS::GetParentIndex () const inline virtual
Returns the index of the parent particle
Implements erhic::VirtualParticle.
Definition at line 247 of file ParticleMCS.h.
View newest version in sPHENIX GitHub at line 247 of file ParticleMCS.h
Double_t Smear::ParticleMCS::GetPhi () const virtual
Returns the polar angle in the range [0,2pi] radians.
Implements erhic::VirtualParticle.
Definition at line 141 of file ParticleMCS.cxx.
View newest version in sPHENIX GitHub at line 141 of file ParticleMCS.cxx
References phi.
Referenced by FillParticleQA(), Smear::Device::Smear(), and Smear::Detector::Smear().
Double_t Smear::ParticleMCS::GetPt () const virtual
Returns momentum transverse to the beam direction.
Implements erhic::VirtualParticle.
Definition at line 125 of file ParticleMCS.cxx.
View newest version in sPHENIX GitHub at line 125 of file ParticleMCS.cxx
References pt.
Referenced by HandleBogusValues(), and Smear::Detector::Smear().
Double_t Smear::ParticleMCS::GetPx () const virtual
Returns the x component of 3-momentum.
Implements erhic::VirtualParticle.
Definition at line 105 of file ParticleMCS.cxx.
View newest version in sPHENIX GitHub at line 105 of file ParticleMCS.cxx
References cos(), p, phi, and theta.
Referenced by EicSmearTask::FinishTask(), main(), and Smear::Detector::Smear().
Double_t Smear::ParticleMCS::GetPy () const virtual
Returns the y component of 3-momentum.
Implements erhic::VirtualParticle.
Definition at line 109 of file ParticleMCS.cxx.
View newest version in sPHENIX GitHub at line 109 of file ParticleMCS.cxx
References p, phi, and theta.
Referenced by EicSmearTask::FinishTask(), main(), and Smear::Detector::Smear().
Double_t Smear::ParticleMCS::GetPz () const virtual
Returns the z component of 3-momentum.
Implements erhic::VirtualParticle.
Definition at line 113 of file ParticleMCS.cxx.
View newest version in sPHENIX GitHub at line 113 of file ParticleMCS.cxx
References pz.
Referenced by EicSmearTask::FinishTask(), main(), and Smear::Detector::Smear().
Double_t Smear::ParticleMCS::GetRapidity () const virtual
Returns the rapidity.
Implements erhic::VirtualParticle.
Definition at line 87 of file ParticleMCS.cxx.
View newest version in sPHENIX GitHub at line 87 of file ParticleMCS.cxx
References E, pz, and y.
UShort_t Smear::ParticleMCS::GetStatus () const virtual
Returns a status code following the PYTHIA defintion, where 21 indicates an initial-state particle and 1 indicates a final- state particle
Implements erhic::VirtualParticle.
Definition at line 145 of file ParticleMCS.cxx.
View newest version in sPHENIX GitHub at line 145 of file ParticleMCS.cxx
References status.
Referenced by EicSmearTask::FinishTask(), and main().
Double_t Smear::ParticleMCS::GetTheta () const virtual
Returns the polar angle in the range [0,pi] radians.
Implements erhic::VirtualParticle.
Definition at line 137 of file ParticleMCS.cxx.
View newest version in sPHENIX GitHub at line 137 of file ParticleMCS.cxx
References theta.
Referenced by FillParticleQA(), Smear::Bremsstrahlung::FixParticleKinematics(), GetEta(), Smear::Device::Smear(), and Smear::Detector::Smear().
TVector3 Smear::ParticleMCS::GetVertex () const virtual
Returns the origin point of the particle (cm). (0,0,0) indicates a particle originating in the collision.
Implements erhic::VirtualParticle.
Definition at line 129 of file ParticleMCS.cxx.
View newest version in sPHENIX GitHub at line 129 of file ParticleMCS.cxx
void Smear::ParticleMCS::HandleBogusValues (const KinType kin)
This dictates how the class deals with positive definite variables which have been smeared to negative values.
Definition at line 261 of file ParticleMCS.cxx.
View newest version in sPHENIX GitHub at line 261 of file ParticleMCS.cxx
References GetE(), GetP(), GetPt(), Smear::kE, Smear::kP, Smear::kPt, SetE(), SetP(), and SetPt().
Referenced by Smear::Bremsstrahlung::Smear(), Smear::Tracker::Smear(), and Smear::Device::Smear().
erhic::Pid Smear::ParticleMCS::Id () const virtual
Returns the pdg ID of the particle.
Implements erhic::VirtualParticle.
Definition at line 257 of file ParticleMCS.cxx.
View newest version in sPHENIX GitHub at line 257 of file ParticleMCS.cxx
bool Smear::ParticleMCS::IsESmeared () const virtual
Definition at line 158 of file ParticleMCS.cxx.
View newest version in sPHENIX GitHub at line 158 of file ParticleMCS.cxx
References kESmeared.
Referenced by FillParticleQA().
bool Smear::ParticleMCS::IsIdSmeared () const virtual
Definition at line 166 of file ParticleMCS.cxx.
View newest version in sPHENIX GitHub at line 166 of file ParticleMCS.cxx
References kIdSmeared.
bool Smear::ParticleMCS::IsNumSigmaSmeared () const virtual
Definition at line 167 of file ParticleMCS.cxx.
View newest version in sPHENIX GitHub at line 167 of file ParticleMCS.cxx
References kNumSigmaSmeared.
bool Smear::ParticleMCS::IsPhiSmeared () const virtual
Definition at line 165 of file ParticleMCS.cxx.
View newest version in sPHENIX GitHub at line 165 of file ParticleMCS.cxx
References kPhiSmeared.
Referenced by FillParticleQA(), and Smear::Detector::Smear().
bool Smear::ParticleMCS::IsPSmeared () const virtual
Definition at line 159 of file ParticleMCS.cxx.
View newest version in sPHENIX GitHub at line 159 of file ParticleMCS.cxx
References kPSmeared.
Referenced by FillParticleQA(), and Smear::Detector::Smear().
bool Smear::ParticleMCS::IsPtSmeared () const virtual
Definition at line 160 of file ParticleMCS.cxx.
View newest version in sPHENIX GitHub at line 160 of file ParticleMCS.cxx
References kPtSmeared.
Referenced by Smear::Detector::Smear().
bool Smear::ParticleMCS::IsPxSmeared () const virtual
Definition at line 161 of file ParticleMCS.cxx.
View newest version in sPHENIX GitHub at line 161 of file ParticleMCS.cxx
References kPxSmeared.
Referenced by Smear::Detector::Smear().
bool Smear::ParticleMCS::IsPySmeared () const virtual
Definition at line 162 of file ParticleMCS.cxx.
View newest version in sPHENIX GitHub at line 162 of file ParticleMCS.cxx
References kPySmeared.
Referenced by Smear::Detector::Smear().
bool Smear::ParticleMCS::IsPzSmeared () const virtual
Definition at line 163 of file ParticleMCS.cxx.
View newest version in sPHENIX GitHub at line 163 of file ParticleMCS.cxx
References kPzSmeared.
Referenced by Smear::Detector::Smear().
bool Smear::ParticleMCS::IsSmeared () const virtual
should always be true for a ParticleMCS This replaces the brittle mechanism of checking values against 0 If false, it should indicate an old tree was used.
Definition at line 157 of file ParticleMCS.cxx.
View newest version in sPHENIX GitHub at line 157 of file ParticleMCS.cxx
References kParticleSmeared.
Referenced by Smear::Detector::Smear().
bool Smear::ParticleMCS::IsThetaSmeared () const virtual
Definition at line 164 of file ParticleMCS.cxx.
View newest version in sPHENIX GitHub at line 164 of file ParticleMCS.cxx
References kThetaSmeared.
Referenced by FillParticleQA(), and Smear::Detector::Smear().
ParticleMCS& Smear::ParticleMCS::operator= (const ParticleMCS &) delete
void Smear::ParticleMCS::Print (Option_t * = "") const virtual
Prints the attributes of this particle to standard output. The output format is "status id px py pz E".
Definition at line 58 of file ParticleMCS.cxx.
View newest version in sPHENIX GitHub at line 58 of file ParticleMCS.cxx
References E, ff, px, py, pz, and status.
Referenced by Smear::Event::Print().
virtual TLorentzVector Smear::ParticleMCS::PxPyPzE () const inline virtual
Returns the (E,p) 4-vector in the lab frame.
Definition at line 84 of file ParticleMCS.h.
View newest version in sPHENIX GitHub at line 84 of file ParticleMCS.h
References Get4Vector().
void Smear::ParticleMCS::Set4Vector (const TLorentzVector &) inline virtual
Dummy one; just need to compile;
Implements erhic::VirtualParticle.
Definition at line 243 of file ParticleMCS.h.
View newest version in sPHENIX GitHub at line 243 of file ParticleMCS.h
void Smear::ParticleMCS::SetE (const Double_t value, const bool CheckSetSmearFlag = true) virtual
Set energy. By default, marks it as smeared and checks that it wasn't before.
Parameters
CheckSetSmearFlag=false disables this check (e.g. for adjustments)
Definition at line 189 of file ParticleMCS.cxx.
View newest version in sPHENIX GitHub at line 189 of file ParticleMCS.cxx
References E, kESmeared, and value.
Referenced by HandleBogusValues(), SetVariable(), and Smear::Bremsstrahlung::Smear().
void Smear::ParticleMCS::SetESmeared (bool flag = true) virtual
Definition at line 273 of file ParticleMCS.cxx.
View newest version in sPHENIX GitHub at line 273 of file ParticleMCS.cxx
References kESmeared.
void Smear::ParticleMCS::SetId (Int_t value, const bool CheckSetSmearFlag = true) virtual
Set particle id (pdg code). By default, marks it as smeared and checks that it wasn't before.
Parameters
CheckSetSmearFlag=false disables this check (e.g. for adjustments)
Definition at line 237 of file ParticleMCS.cxx.
View newest version in sPHENIX GitHub at line 237 of file ParticleMCS.cxx
References kIdSmeared.
Referenced by Smear::PerfectID::Smear(), and Smear::ParticleID::Smear().
void Smear::ParticleMCS::SetIdSmeared (bool flag = true) virtual
Definition at line 281 of file ParticleMCS.cxx.
View newest version in sPHENIX GitHub at line 281 of file ParticleMCS.cxx
References kIdSmeared.
void Smear::ParticleMCS::SetNumSigma (const double d, const bool CheckSetSmearFlag = true) virtual
Set the numSigma deviation of this particle
Definition at line 247 of file ParticleMCS.cxx.
View newest version in sPHENIX GitHub at line 247 of file ParticleMCS.cxx
References d, kNumSigmaSmeared, and numSigma.
Referenced by Smear::NumSigmaPid::Smear().
void Smear::ParticleMCS::SetNumSigmaSmeared (bool flag = true) virtual
Definition at line 282 of file ParticleMCS.cxx.
View newest version in sPHENIX GitHub at line 282 of file ParticleMCS.cxx
References kNumSigmaSmeared.
void Smear::ParticleMCS::SetNumSigmaType (const int i) virtual
Set the numSigma deviation type (pi_k, k_p) of this particle
Definition at line 253 of file ParticleMCS.cxx.
View newest version in sPHENIX GitHub at line 253 of file ParticleMCS.cxx
References numSigmaType.
void Smear::ParticleMCS::SetP (const Double_t value, const bool CheckSetSmearFlag = true) virtual
Set total momentum P. By default, marks it as smeared and checks that it wasn't before.
Parameters
CheckSetSmearFlag=false disables this check (e.g. for adjustments)
Definition at line 195 of file ParticleMCS.cxx.
View newest version in sPHENIX GitHub at line 195 of file ParticleMCS.cxx
References kPSmeared, p, and value.
Referenced by Smear::Bremsstrahlung::FixParticleKinematics(), HandleBogusValues(), SetVariable(), EPhenixMomentum::Smear(), and Smear::Detector::Smear().
void Smear::ParticleMCS::SetPhi (const Double_t value, const bool CheckSetSmearFlag = true) virtual
Set azimuth φ. By default, marks it as smeared and checks that it wasn't before.
Parameters
CheckSetSmearFlag=false disables this check (e.g. for adjustments)
Definition at line 225 of file ParticleMCS.cxx.
View newest version in sPHENIX GitHub at line 225 of file ParticleMCS.cxx
References kPhiSmeared, phi, and value.
Referenced by SetVariable(), Smear::Device::Smear(), and Smear::Detector::Smear().
void Smear::ParticleMCS::SetPhiSmeared (bool flag = true) virtual
Definition at line 280 of file ParticleMCS.cxx.
View newest version in sPHENIX GitHub at line 280 of file ParticleMCS.cxx
References kPhiSmeared.
void Smear::ParticleMCS::SetPSmeared (bool flag = true) virtual
Definition at line 274 of file ParticleMCS.cxx.
View newest version in sPHENIX GitHub at line 274 of file ParticleMCS.cxx
References kPSmeared.
void Smear::ParticleMCS::SetPt (const Double_t value, const bool CheckSetSmearFlag = true) virtual
Set transverse momentum Pt. By default, marks it as smeared and checks that it wasn't before.
Parameters
CheckSetSmearFlag=false disables this check (e.g. for adjustments)
Definition at line 201 of file ParticleMCS.cxx.
View newest version in sPHENIX GitHub at line 201 of file ParticleMCS.cxx
References kPtSmeared, pt, and value.
Referenced by Smear::Bremsstrahlung::FixParticleKinematics(), HandleBogusValues(), SetVariable(), and Smear::Detector::Smear().
void Smear::ParticleMCS::SetPtSmeared (bool flag = true) virtual
Definition at line 275 of file ParticleMCS.cxx.
View newest version in sPHENIX GitHub at line 275 of file ParticleMCS.cxx
References kPtSmeared.
void Smear::ParticleMCS::SetPx (const Double_t value, const bool CheckSetSmearFlag = true) virtual
Set P_x. By default, marks it as smeared and checks that it wasn't before.
Parameters
CheckSetSmearFlag=false disables this check (e.g. for adjustments)
Definition at line 207 of file ParticleMCS.cxx.
View newest version in sPHENIX GitHub at line 207 of file ParticleMCS.cxx
References kPxSmeared, px, and value.
Referenced by Smear::Detector::Smear().
void Smear::ParticleMCS::SetPxSmeared (bool flag = true) virtual
Definition at line 276 of file ParticleMCS.cxx.
View newest version in sPHENIX GitHub at line 276 of file ParticleMCS.cxx
References kPxSmeared.
void Smear::ParticleMCS::SetPy (const Double_t value, const bool CheckSetSmearFlag = true) virtual
Set P_y. By default, marks it as smeared and checks that it wasn't before.
Parameters
CheckSetSmearFlag=false disables this check (e.g. for adjustments)
Definition at line 213 of file ParticleMCS.cxx.
View newest version in sPHENIX GitHub at line 213 of file ParticleMCS.cxx
References kPySmeared, py, and value.
Referenced by Smear::Detector::Smear().
void Smear::ParticleMCS::SetPySmeared (bool flag = true) virtual
Definition at line 277 of file ParticleMCS.cxx.
View newest version in sPHENIX GitHub at line 277 of file ParticleMCS.cxx
References kPySmeared.
void Smear::ParticleMCS::SetPz (const Double_t value, const bool CheckSetSmearFlag = true) virtual
Set P_z. By default, marks it as smeared and checks that it wasn't before.
Parameters
CheckSetSmearFlag=false disables this check (e.g. for adjustments)
Definition at line 219 of file ParticleMCS.cxx.
View newest version in sPHENIX GitHub at line 219 of file ParticleMCS.cxx
References kPzSmeared, pz, and value.
Referenced by Smear::Bremsstrahlung::FixParticleKinematics(), SetVariable(), and Smear::Detector::Smear().
void Smear::ParticleMCS::SetPzSmeared (bool flag = true) virtual
Definition at line 278 of file ParticleMCS.cxx.
View newest version in sPHENIX GitHub at line 278 of file ParticleMCS.cxx
References kPzSmeared.
void Smear::ParticleMCS::SetSmeared (bool flag = true) virtual
Definition at line 272 of file ParticleMCS.cxx.
View newest version in sPHENIX GitHub at line 272 of file ParticleMCS.cxx
References kParticleSmeared.
Referenced by Smear::Detector::Smear().
void Smear::ParticleMCS::SetStatus (Int_t i) virtual
Definition at line 243 of file ParticleMCS.cxx.
View newest version in sPHENIX GitHub at line 243 of file ParticleMCS.cxx
References status.
Referenced by Smear::EventDisFactory::Create().
void Smear::ParticleMCS::SetTheta (const Double_t value, const bool CheckSetSmearFlag = true) virtual
Set polar angle θ. By default, marks it as smeared and checks that it wasn't before.
Parameters
CheckSetSmearFlag=false disables this check (e.g. for adjustments)
Definition at line 231 of file ParticleMCS.cxx.
View newest version in sPHENIX GitHub at line 231 of file ParticleMCS.cxx
References kThetaSmeared, theta, and value.
Referenced by SetVariable(), Smear::Device::Smear(), and Smear::Detector::Smear().
void Smear::ParticleMCS::SetThetaSmeared (bool flag = true) virtual
Definition at line 279 of file ParticleMCS.cxx.
View newest version in sPHENIX GitHub at line 279 of file ParticleMCS.cxx
References kThetaSmeared.
void Smear::ParticleMCS::SetVariable (const double z, const KinType kin) virtual
Stores z in the ParticleS.K where K is the kinematic variable associated with kin.
Definition at line 170 of file ParticleMCS.cxx.
View newest version in sPHENIX GitHub at line 170 of file ParticleMCS.cxx
References Smear::kE, Smear::kP, Smear::kPhi, Smear::kPt, Smear::kPz, Smear::kTheta, SetE(), SetP(), SetPhi(), SetPt(), SetPz(), and SetTheta().
Referenced by Smear::Tracker::Smear(), and Smear::Device::Smear().
virtual void Smear::ParticleMCS::SetVertex (const TVector3 &) inline virtual
Sets the origin coordinates. No-op, just required for compilation.
Implements erhic::VirtualParticle.
Definition at line 259 of file ParticleMCS.h.
View newest version in sPHENIX GitHub at line 259 of file ParticleMCS.h
Member Data Documentation
Double32_t Smear::ParticleMCS::E protected
Energy of particle.
Definition at line 297 of file ParticleMCS.h.
View newest version in sPHENIX GitHub at line 297 of file ParticleMCS.h
Referenced by Get4Vector(), GetE(), GetM(), GetRapidity(), Print(), and SetE().
Int_t Smear::ParticleMCS::id protected
PDG particle code.
Definition at line 293 of file ParticleMCS.h.
View newest version in sPHENIX GitHub at line 293 of file ParticleMCS.h
Referenced by EicSmearTask::FinishTask().
bool Smear::ParticleMCS::kESmeared =false protected
Definition at line 280 of file ParticleMCS.h.
View newest version in sPHENIX GitHub at line 280 of file ParticleMCS.h
Referenced by IsESmeared(), SetE(), and SetESmeared().
bool Smear::ParticleMCS::kIdSmeared =false protected
Definition at line 288 of file ParticleMCS.h.
View newest version in sPHENIX GitHub at line 288 of file ParticleMCS.h
Referenced by IsIdSmeared(), SetId(), and SetIdSmeared().
bool Smear::ParticleMCS::kNumSigmaSmeared =false protected
Definition at line 289 of file ParticleMCS.h.
View newest version in sPHENIX GitHub at line 289 of file ParticleMCS.h
Referenced by IsNumSigmaSmeared(), SetNumSigma(), and SetNumSigmaSmeared().
bool Smear::ParticleMCS::kParticleSmeared =false protected
should always be true for a ParticleMCS This replaces the brittle mechanism of checking values against 0 If false, it should indicate an old tree was used.
Definition at line 279 of file ParticleMCS.h.
View newest version in sPHENIX GitHub at line 279 of file ParticleMCS.h
Referenced by IsSmeared(), and SetSmeared().
bool Smear::ParticleMCS::kPhiSmeared =false protected
Definition at line 287 of file ParticleMCS.h.
View newest version in sPHENIX GitHub at line 287 of file ParticleMCS.h
Referenced by IsPhiSmeared(), SetPhi(), and SetPhiSmeared().
bool Smear::ParticleMCS::kPSmeared =false protected
Definition at line 281 of file ParticleMCS.h.
View newest version in sPHENIX GitHub at line 281 of file ParticleMCS.h
Referenced by IsPSmeared(), SetP(), and SetPSmeared().
bool Smear::ParticleMCS::kPtSmeared =false protected
Definition at line 282 of file ParticleMCS.h.
View newest version in sPHENIX GitHub at line 282 of file ParticleMCS.h
Referenced by IsPtSmeared(), SetPt(), and SetPtSmeared().
bool Smear::ParticleMCS::kPxSmeared =false protected
Definition at line 283 of file ParticleMCS.h.
View newest version in sPHENIX GitHub at line 283 of file ParticleMCS.h
Referenced by IsPxSmeared(), SetPx(), and SetPxSmeared().
bool Smear::ParticleMCS::kPySmeared =false protected
Definition at line 284 of file ParticleMCS.h.
View newest version in sPHENIX GitHub at line 284 of file ParticleMCS.h
Referenced by IsPySmeared(), SetPy(), and SetPySmeared().
bool Smear::ParticleMCS::kPzSmeared =false protected
Definition at line 285 of file ParticleMCS.h.
View newest version in sPHENIX GitHub at line 285 of file ParticleMCS.h
Referenced by IsPzSmeared(), SetPz(), and SetPzSmeared().
bool Smear::ParticleMCS::kThetaSmeared =false protected
Definition at line 286 of file ParticleMCS.h.
View newest version in sPHENIX GitHub at line 286 of file ParticleMCS.h
Referenced by IsThetaSmeared(), SetTheta(), and SetThetaSmeared().
double Smear::ParticleMCS::numSigma protected
PID: nSigma deviation.
Definition at line 303 of file ParticleMCS.h.
View newest version in sPHENIX GitHub at line 303 of file ParticleMCS.h
Referenced by GetNumSigma(), and SetNumSigma().
int Smear::ParticleMCS::numSigmaType protected
PID: nSigma deviation type. pi_k == 1, k_p == 2. : This should be agreed upon and fixed better.
Definition at line 304 of file ParticleMCS.h.
View newest version in sPHENIX GitHub at line 304 of file ParticleMCS.h
Referenced by GetNumSigmaType(), and SetNumSigmaType().
Double32_t Smear::ParticleMCS::p protected
Total momentum of particle.
Definition at line 299 of file ParticleMCS.h.
View newest version in sPHENIX GitHub at line 299 of file ParticleMCS.h
Referenced by GetM(), GetP(), GetPx(), GetPy(), and SetP().
Double32_t Smear::ParticleMCS::phi protected
Azimuthal angle.
Definition at line 301 of file ParticleMCS.h.
View newest version in sPHENIX GitHub at line 301 of file ParticleMCS.h
Referenced by GetPhi(), GetPx(), GetPy(), and SetPhi().
Double32_t Smear::ParticleMCS::pt protected
Transverse momentum of particle.
Definition at line 298 of file ParticleMCS.h.
View newest version in sPHENIX GitHub at line 298 of file ParticleMCS.h
Referenced by GetPt(), and SetPt().
Double32_t Smear::ParticleMCS::px protected
x component of particle momentum
Definition at line 294 of file ParticleMCS.h.
View newest version in sPHENIX GitHub at line 294 of file ParticleMCS.h
Referenced by Get4Vector(), Print(), and SetPx().
Double32_t Smear::ParticleMCS::py protected
y component of particle momentum
Definition at line 295 of file ParticleMCS.h.
View newest version in sPHENIX GitHub at line 295 of file ParticleMCS.h
Referenced by Get4Vector(), Print(), and SetPy().
Double32_t Smear::ParticleMCS::pz protected
z component of particle momentum
Definition at line 296 of file ParticleMCS.h.
View newest version in sPHENIX GitHub at line 296 of file ParticleMCS.h
Referenced by Get4Vector(), GetPz(), GetRapidity(), Print(), and SetPz().
UShort_t Smear::ParticleMCS::status protected
Status code.
Definition at line 292 of file ParticleMCS.h.
View newest version in sPHENIX GitHub at line 292 of file ParticleMCS.h
Referenced by GetStatus(), Print(), and SetStatus().
Double32_t Smear::ParticleMCS::theta protected
Polar angle.
Definition at line 300 of file ParticleMCS.h.
View newest version in sPHENIX GitHub at line 300 of file ParticleMCS.h
Referenced by GetEta(), GetPx(), GetPy(), GetTheta(), and SetTheta().
The documentation for this class was generated from the following files:
eic-smear/blob/master/include/eicsmear/smear/ParticleMCS.h
eic-smear/blob/master/src/smear/ParticleMCS.cxx