EIC Software: FW::Obj::ObjTrackingGeometryWriter Class Reference
FW::Obj::ObjTrackingGeometryWriter Class Reference
#include <fun4all_acts/blob/master/Examples/Io/Obj/include/ACTFW/Plugins/Obj/ObjTrackingGeometryWriter.hpp>
Classes
class Config
Public Member Functions
ObjTrackingGeometryWriter (const Config &cfg)
std::string name () const
FW::ProcessCode write (const AlgorithmContext &context, const Acts::TrackingGeometry &tGeometry)
Private Member Functions
void write (const AlgorithmContext &context, const Acts::TrackingVolume &tVolume)
process this volume
const Acts::Logger & logger () const
Private access to the logging instance.
Private Attributes
Config m_cfg
the config class
Detailed Description
An Obj writer for the geometry: TrackingGeometry master It delegates the writing of surfaces to the surface writers
Definition at line 31 of file ObjTrackingGeometryWriter.hpp.
View newest version in sPHENIX GitHub at line 31 of file ObjTrackingGeometryWriter.hpp
Constructor & Destructor Documentation
FW::Obj::ObjTrackingGeometryWriter::ObjTrackingGeometryWriter (const Config & cfg)
Constructor
Parameters
cfg is the configuration class
Definition at line 17 of file ObjTrackingGeometryWriter.cpp.
View newest version in sPHENIX GitHub at line 17 of file ObjTrackingGeometryWriter.cpp
Member Function Documentation
const Acts::Logger& FW::Obj::ObjTrackingGeometryWriter::logger () const inline private
Private access to the logging instance.
Definition at line 80 of file ObjTrackingGeometryWriter.hpp.
View newest version in sPHENIX GitHub at line 80 of file ObjTrackingGeometryWriter.hpp
References FW::Obj::ObjTrackingGeometryWriter::Config::logger, and m_cfg.
std::string FW::Obj::ObjTrackingGeometryWriter::name () const
Framework name() method
Returns
the name of the tool
Definition at line 21 of file ObjTrackingGeometryWriter.cpp.
View newest version in sPHENIX GitHub at line 21 of file ObjTrackingGeometryWriter.cpp
FW::ProcessCode FW::Obj::ObjTrackingGeometryWriter::write (const AlgorithmContext & context, const Acts::TrackingGeometry & tGeometry)
The write interface
Parameters
context the Algorithm/Event context of this call
tGeometry is the geometry to be written out
Returns
ProcessCode to indicate success/failure
Definition at line 25 of file ObjTrackingGeometryWriter.cpp.
View newest version in sPHENIX GitHub at line 25 of file ObjTrackingGeometryWriter.cpp
References ACTS_DEBUG, Acts::TrackingGeometry::highestTrackingVolume(), SUCCESS, Acts::Test::world, and tree::write().
void FW::Obj::ObjTrackingGeometryWriter::write (const AlgorithmContext & context, const Acts::TrackingVolume & tVolume) private
process this volume
process this volume
Parameters
context the Algorithm/Event context for this call
tVolume the volume to be processed
Definition at line 37 of file ObjTrackingGeometryWriter.cpp.
View newest version in sPHENIX GitHub at line 37 of file ObjTrackingGeometryWriter.cpp
References ACTS_DEBUG, ACTS_VERBOSE, Acts::BinnedArray< T >::arrayObjects(), Acts::TrackingVolume::confinedLayers(), Acts::TrackingVolume::confinedVolumes(), Acts::Test::cSurface, Acts::navigation, Acts::Test::volume, Acts::TrackingVolume::volumeName(), and tree::write().
Member Data Documentation
Config FW::Obj::ObjTrackingGeometryWriter::m_cfg private
the config class
Definition at line 71 of file ObjTrackingGeometryWriter.hpp.
View newest version in sPHENIX GitHub at line 71 of file ObjTrackingGeometryWriter.hpp
Referenced by logger().
The documentation for this class was generated from the following files:
fun4all_acts/blob/master/Examples/Io/Obj/include/ACTFW/Plugins/Obj/ObjTrackingGeometryWriter.hpp
fun4all_acts/blob/master/Examples/Io/Obj/src/ObjTrackingGeometryWriter.cpp