EIC Software: tetgenmesh::memorypool Class Reference
tetgenmesh::memorypool Class Reference
#include <EicRoot/blob/master/eic/cad/tetgen/tetgen.h>
Public Member Functions
memorypool ()
memorypool (int, int, int, int)
~memorypool ()
void poolinit (int, int, int, int)
void restart ()
void * alloc ()
void dealloc (void *)
void traversalinit ()
void * traverse ()
Public Attributes
void ** firstblock
void ** nowblock
void * nextitem
void * deaditemstack
void ** pathblock
void * pathitem
int alignbytes
int itembytes
int itemwords
int itemsperblock
long items
long maxitems
int unallocateditems
int pathitemsleft
Detailed Description
Definition at line 1032 of file tetgen.h.
View newest version in sPHENIX GitHub at line 1032 of file tetgen.h
Constructor & Destructor Documentation
tetgenmesh::memorypool::memorypool ()
Definition at line 3918 of file tetgen.cxx.
View newest version in sPHENIX GitHub at line 3918 of file tetgen.cxx
tetgenmesh::memorypool::memorypool (int bytecount, int itemcount, int wsize, int alignment)
Definition at line 3933 of file tetgen.cxx.
View newest version in sPHENIX GitHub at line 3933 of file tetgen.cxx
tetgenmesh::memorypool::~memorypool ()
Definition at line 3945 of file tetgen.cxx.
View newest version in sPHENIX GitHub at line 3945 of file tetgen.cxx
Member Function Documentation
void * tetgenmesh::memorypool::alloc ()
Definition at line 4041 of file tetgen.cxx.
View newest version in sPHENIX GitHub at line 4041 of file tetgen.cxx
References terminatetetgen().
Referenced by tetgenmesh::enqueuesubface(), tetgenmesh::enqueuetetrahedron(), tetgenmesh::fillregion(), tetgenmesh::flipcertify(), tetgenmesh::flippush(), tetgenmesh::flipshpush(), tetgenmesh::makepoint(), tetgenmesh::makeshellface(), tetgenmesh::maketetrahedron(), tetgenmesh::tsbond(), tetgenmesh::tssbond1(), and tetgenmesh::unifysegments().
void tetgenmesh::memorypool::dealloc (void * dyingitem)
Definition at line 4098 of file tetgen.cxx.
View newest version in sPHENIX GitHub at line 4098 of file tetgen.cxx
Referenced by tetgenmesh::fillregion(), tetgenmesh::flip23(), tetgenmesh::flip32(), tetgenmesh::flip41(), tetgenmesh::flipinsertfacet(), tetgenmesh::incrementalflip(), tetgenmesh::lawsonflip(), tetgenmesh::lawsonflip3d(), tetgenmesh::pointdealloc(), tetgenmesh::repairbadtets(), tetgenmesh::repairencfacs(), tetgenmesh::repairencsegs(), tetgenmesh::shellfacedealloc(), and tetgenmesh::tetrahedrondealloc().
void tetgenmesh::memorypool::poolinit (int bytecount, int itemcount, int wordsize, int alignment)
Definition at line 3970 of file tetgen.cxx.
View newest version in sPHENIX GitHub at line 3970 of file tetgen.cxx
References terminatetetgen().
void tetgenmesh::memorypool::restart ()
Definition at line 4014 of file tetgen.cxx.
View newest version in sPHENIX GitHub at line 4014 of file tetgen.cxx
Referenced by tetgenmesh::detectinterfaces(), tetgenmesh::fillregion(), tetgenmesh::removeslivers(), tetgenmesh::repairbadtets(), tetgenmesh::repairencfacs(), tetgenmesh::repairencsegs(), and tetgenmesh::unifysegments().
void tetgenmesh::memorypool::traversalinit ()
Definition at line 4114 of file tetgen.cxx.
View newest version in sPHENIX GitHub at line 4114 of file tetgen.cxx
Referenced by tetgenmesh::carveholes(), tetgenmesh::checkconforming(), tetgenmesh::checkdelaunay(), tetgenmesh::checkmesh(), tetgenmesh::checkregular(), tetgenmesh::checksegments(), tetgenmesh::checkshells(), tetgenmesh::collectremovepoints(), tetgenmesh::constraineddelaunay(), tetgenmesh::delaunayrefinement(), tetgenmesh::detectinterfaces(), tetgenmesh::highorder(), tetgenmesh::identifypscedges(), tetgenmesh::incrementaldelaunay(), tetgenmesh::interpolatemeshsize(), tetgenmesh::jettisonnodes(), tetgenmesh::makefacetverticesmap(), tetgenmesh::makeindex2pointmap(), tetgenmesh::makepoint2submap(), tetgenmesh::makesegmentendpointsmap(), tetgenmesh::mergefacets(), tetgenmesh::meshsurface(), tetgenmesh::numberedges(), tetgenmesh::optimizemesh(), tetgenmesh::outedges(), tetgenmesh::outelements(), tetgenmesh::outfaces(), tetgenmesh::outhullfaces(), tetgenmesh::outmesh2medit(), tetgenmesh::outmesh2vtk(), tetgenmesh::outmetrics(), tetgenmesh::outneighbors(), tetgenmesh::outnodes(), tetgenmesh::outsmesh(), tetgenmesh::outsubfaces(), tetgenmesh::outsubsegments(), tetgenmesh::outvoronoi(), tetgenmesh::qualitystatistics(), tetgenmesh::reconstructmesh(), tetgenmesh::recoverboundary(), tetgenmesh::recoverdelaunay(), tetgenmesh::removeslivers(), tetgenmesh::repairbadtets(), tetgenmesh::repairencfacs(), tetgenmesh::repairencsegs(), tetgenmesh::scoutpoint(), tetgenmesh::triangulate(), and tetgenmesh::unifysegments().
void * tetgenmesh::memorypool::traverse ()
Definition at line 4142 of file tetgen.cxx.
View newest version in sPHENIX GitHub at line 4142 of file tetgen.cxx
Referenced by tetgenmesh::alltetrahedrontraverse(), tetgenmesh::incrementaldelaunay(), tetgenmesh::pointtraverse(), tetgenmesh::removeslivers(), tetgenmesh::repairbadtets(), tetgenmesh::repairencfacs(), tetgenmesh::repairencsegs(), tetgenmesh::shellfacetraverse(), and tetgenmesh::tetrahedrontraverse().
Member Data Documentation
int tetgenmesh::memorypool::alignbytes
Definition at line 1041 of file tetgen.h.
View newest version in sPHENIX GitHub at line 1041 of file tetgen.h
Referenced by tetgenmesh::checkshells(), and tetgenmesh::randomsample().
void* tetgenmesh::memorypool::deaditemstack
Definition at line 1038 of file tetgen.h.
View newest version in sPHENIX GitHub at line 1038 of file tetgen.h
Referenced by tetgenmesh::highorder(), and tetgenmesh::jettisonnodes().
void** tetgenmesh::memorypool::firstblock
Definition at line 1036 of file tetgen.h.
View newest version in sPHENIX GitHub at line 1036 of file tetgen.h
Referenced by tetgenmesh::memorystatistics(), and tetgenmesh::randomsample().
int tetgenmesh::memorypool::itembytes
Definition at line 1042 of file tetgen.h.
View newest version in sPHENIX GitHub at line 1042 of file tetgen.h
Referenced by tetgenmesh::delaunayrefinement(), tetgenmesh::initializepools(), and tetgenmesh::memorystatistics().
long tetgenmesh::memorypool::items
Definition at line 1044 of file tetgen.h.
View newest version in sPHENIX GitHub at line 1044 of file tetgen.h
Referenced by tetgenmesh::constraineddelaunay(), tetgenmesh::delaunayrefinement(), tetgenmesh::detectinterfaces(), tetgenmesh::flipinsertfacet(), tetgenmesh::highorder(), tetgenmesh::incrementalflip(), tetgenmesh::lawsonflip(), tetgenmesh::lawsonflip3d(), tetgenmesh::makeindex2pointmap(), tetgenmesh::makepoint(), tetgenmesh::makepoint2submap(), tetgenmesh::meshsurface(), tetgenmesh::outedges(), tetgenmesh::outelements(), tetgenmesh::outfaces(), tetgenmesh::outmesh2medit(), tetgenmesh::outmesh2vtk(), tetgenmesh::outmetrics(), tetgenmesh::outneighbors(), tetgenmesh::outnodes(), tetgenmesh::outsmesh(), tetgenmesh::outsubfaces(), tetgenmesh::outsubsegments(), tetgenmesh::outvoronoi(), tetgenmesh::reconstructmesh(), tetgenmesh::recoverboundary(), tetgenmesh::recoverdelaunay(), tetgenmesh::refineregion(), tetgenmesh::repairbadtets(), tetgenmesh::repairencfacs(), tetgenmesh::repairencsegs(), tetgenmesh::splittetrahedron(), tetgenmesh::statistics(), tetrahedralize(), and tetgenmesh::unifysegments().
int tetgenmesh::memorypool::itemsperblock
Definition at line 1043 of file tetgen.h.
View newest version in sPHENIX GitHub at line 1043 of file tetgen.h
int tetgenmesh::memorypool::itemwords
Definition at line 1042 of file tetgen.h.
View newest version in sPHENIX GitHub at line 1042 of file tetgen.h
Referenced by tetgenmesh::randomsample().
long tetgenmesh::memorypool::maxitems
Definition at line 1044 of file tetgen.h.
View newest version in sPHENIX GitHub at line 1044 of file tetgen.h
Referenced by tetgenmesh::delaunayrefinement(), tetgenmesh::memorystatistics(), and tetgenmesh::randomsample().
void* tetgenmesh::memorypool::nextitem
Definition at line 1037 of file tetgen.h.
View newest version in sPHENIX GitHub at line 1037 of file tetgen.h
void ** tetgenmesh::memorypool::nowblock
Definition at line 1036 of file tetgen.h.
View newest version in sPHENIX GitHub at line 1036 of file tetgen.h
void** tetgenmesh::memorypool::pathblock
Definition at line 1039 of file tetgen.h.
View newest version in sPHENIX GitHub at line 1039 of file tetgen.h
Referenced by tetgenmesh::checkshells(), and tetgenmesh::memorystatistics().
void* tetgenmesh::memorypool::pathitem
Definition at line 1040 of file tetgen.h.
View newest version in sPHENIX GitHub at line 1040 of file tetgen.h
Referenced by tetgenmesh::checkshells().
int tetgenmesh::memorypool::pathitemsleft
Definition at line 1046 of file tetgen.h.
View newest version in sPHENIX GitHub at line 1046 of file tetgen.h
Referenced by tetgenmesh::checkshells().
int tetgenmesh::memorypool::unallocateditems
Definition at line 1045 of file tetgen.h.
View newest version in sPHENIX GitHub at line 1045 of file tetgen.h
The documentation for this class was generated from the following files:
EicRoot/blob/master/eic/cad/tetgen/tetgen.h
EicRoot/blob/master/eic/cad/tetgen/tetgen.cxx