EIC Software: CbmRichRingTrackAssignIdeal Class Reference
CbmRichRingTrackAssignIdeal Class Reference
Ideal Ring-Track Assignment. CbmRichRingMatch must be run prior to this procedure.
#include <EicRoot/blob/master/rich/tracks/CbmRichRingTrackAssignIdeal.h>
Public Member Functions
CbmRichRingTrackAssignIdeal ()
Default constructor.
virtual ~CbmRichRingTrackAssignIdeal ()
Destructor.
void Init ()
Inherited from CbmRichRingTrackAssignBase.
virtual void DoAssign (TClonesArray *rings, TClonesArray *richProj)
Inherited from CbmRichRingTrackAssignBase.
Public Member Functions inherited from CbmRichRingTrackAssignBase
CbmRichRingTrackAssignBase ()
virtual ~CbmRichRingTrackAssignBase ()
Destructor.
Private Member Functions
CbmRichRingTrackAssignIdeal (const CbmRichRingTrackAssignIdeal &)
Copy constructor.
CbmRichRingTrackAssignIdeal & operator= (const CbmRichRingTrackAssignIdeal &)
Assignment operator.
Private Attributes
TClonesArray * fMcTracks
TClonesArray * fGlobalTracks
TClonesArray * fRingMatches
TClonesArray * fStsTrackMatches
Additional Inherited Members
Protected Attributes inherited from CbmRichRingTrackAssignBase
double fMaxDistance
int fMinNofHitsInRing
Detailed Description
Ideal Ring-Track Assignment. CbmRichRingMatch must be run prior to this procedure.
Author
Claudia Hoehne and Semen Lebedev
Date
2007
Definition at line 26 of file CbmRichRingTrackAssignIdeal.h.
View newest version in sPHENIX GitHub at line 26 of file CbmRichRingTrackAssignIdeal.h
Constructor & Destructor Documentation
CbmRichRingTrackAssignIdeal::CbmRichRingTrackAssignIdeal ()
Default constructor.
Definition at line 26 of file CbmRichRingTrackAssignIdeal.cxx.
View newest version in sPHENIX GitHub at line 26 of file CbmRichRingTrackAssignIdeal.cxx
CbmRichRingTrackAssignIdeal::~CbmRichRingTrackAssignIdeal () virtual
Destructor.
Definition at line 35 of file CbmRichRingTrackAssignIdeal.cxx.
View newest version in sPHENIX GitHub at line 35 of file CbmRichRingTrackAssignIdeal.cxx
CbmRichRingTrackAssignIdeal::CbmRichRingTrackAssignIdeal (const CbmRichRingTrackAssignIdeal &) private
Copy constructor.
Member Function Documentation
void CbmRichRingTrackAssignIdeal::DoAssign (TClonesArray * rings, TClonesArray * richProj) virtual
Inherited from CbmRichRingTrackAssignBase.
Implements CbmRichRingTrackAssignBase.
Definition at line 57 of file CbmRichRingTrackAssignIdeal.cxx.
View newest version in sPHENIX GitHub at line 57 of file CbmRichRingTrackAssignIdeal.cxx
References fGlobalTracks, CbmRichRingTrackAssignBase::fMinNofHitsInRing, fRingMatches, fStsTrackMatches, CbmRichRing::GetCenterX(), CbmRichRing::GetCenterY(), CbmTrackMatch::GetMCTrackId(), CbmRichRing::GetNofHits(), CbmGlobalTrack::GetStsTrackIndex(), FairTrackParam::GetX(), FairTrackParam::GetY(), and CbmRichRing::SetDistance().
void CbmRichRingTrackAssignIdeal::Init (void) virtual
Inherited from CbmRichRingTrackAssignBase.
Reimplemented from CbmRichRingTrackAssignBase.
Definition at line 39 of file CbmRichRingTrackAssignIdeal.cxx.
View newest version in sPHENIX GitHub at line 39 of file CbmRichRingTrackAssignIdeal.cxx
References fGlobalTracks, fMcTracks, fRingMatches, fStsTrackMatches, FairRootManager::GetObject(), and FairRootManager::Instance().
CbmRichRingTrackAssignIdeal& CbmRichRingTrackAssignIdeal::operator= (const CbmRichRingTrackAssignIdeal &) private
Assignment operator.
Member Data Documentation
TClonesArray* CbmRichRingTrackAssignIdeal::fGlobalTracks private
Definition at line 54 of file CbmRichRingTrackAssignIdeal.h.
View newest version in sPHENIX GitHub at line 54 of file CbmRichRingTrackAssignIdeal.h
Referenced by DoAssign(), and Init().
TClonesArray* CbmRichRingTrackAssignIdeal::fMcTracks private
Definition at line 53 of file CbmRichRingTrackAssignIdeal.h.
View newest version in sPHENIX GitHub at line 53 of file CbmRichRingTrackAssignIdeal.h
Referenced by Init().
TClonesArray* CbmRichRingTrackAssignIdeal::fRingMatches private
Definition at line 55 of file CbmRichRingTrackAssignIdeal.h.
View newest version in sPHENIX GitHub at line 55 of file CbmRichRingTrackAssignIdeal.h
Referenced by DoAssign(), and Init().
TClonesArray* CbmRichRingTrackAssignIdeal::fStsTrackMatches private
Definition at line 56 of file CbmRichRingTrackAssignIdeal.h.
View newest version in sPHENIX GitHub at line 56 of file CbmRichRingTrackAssignIdeal.h
Referenced by DoAssign(), and Init().
The documentation for this class was generated from the following files:
EicRoot/blob/master/rich/tracks/CbmRichRingTrackAssignIdeal.h
EicRoot/blob/master/rich/tracks/CbmRichRingTrackAssignIdeal.cxx