EIC Software: FW::TruthVerticesToTracksAlgorithm Class Reference
FW::TruthVerticesToTracksAlgorithm Class Reference
Converter that takes a generator event (i.e. a std::vector<SimVertex>) and produces a std::vector<Acts::BoundParameter>. It also allows the possibility of parameter smearing.
#include <fun4all_acts/blob/master/Examples/Algorithms/TruthTracking/ACTFW/TruthTracking/TruthVerticesToTracks.hpp>
Classes
struct Config
Nested configuration struct.
Public Member Functions
TruthVerticesToTracksAlgorithm (const Config &cfg, Acts::Logging::Level level=Acts::Logging::INFO)
ProcessCode execute (const AlgorithmContext &context) const finaloverride
Public Member Functions inherited from FW::BareAlgorithm
BareAlgorithm (std::string name, Acts::Logging::Level level=Acts::Logging::INFO)
std::string name () const finaloverride
The algorithm name.
Private Member Functions
void correctPhiThetaPeriodicity (double &phiIn, double &thetaIn) const
Function that corrects phi and theta wraps.
Private Attributes
Config m_cfg
Config struct.
Additional Inherited Members
Protected Member Functions inherited from FW::BareAlgorithm
const Acts::Logger & logger () const
Detailed Description
Converter that takes a generator event (i.e. a std::vector<SimVertex>) and produces a std::vector<Acts::BoundParameter>. It also allows the possibility of parameter smearing.
Definition at line 33 of file TruthVerticesToTracks.hpp.
View newest version in sPHENIX GitHub at line 33 of file TruthVerticesToTracks.hpp
Constructor & Destructor Documentation
FW::TruthVerticesToTracksAlgorithm::TruthVerticesToTracksAlgorithm (const Config & cfg, Acts::Logging::Level level = Acts::Logging::INFO)
Constructor of the TruthVerticesToTracks algorithm
Parameters
cfg is the config struct to configure the algorihtm
level is the logging level
Definition at line 24 of file TruthVerticesToTracks.cpp.
View newest version in sPHENIX GitHub at line 24 of file TruthVerticesToTracks.cpp
References FW::TruthVerticesToTracksAlgorithm::Config::input, m_cfg, FW::TruthVerticesToTracksAlgorithm::Config::output, and FW::TruthVerticesToTracksAlgorithm::Config::randomNumberSvc.
Member Function Documentation
void FW::TruthVerticesToTracksAlgorithm::correctPhiThetaPeriodicity (double & phiIn, double & thetaIn) const private
Function that corrects phi and theta wraps.
Parameters
phiIn Phi
thetaIn Theta
Definition at line 153 of file TruthVerticesToTracks.cpp.
View newest version in sPHENIX GitHub at line 153 of file TruthVerticesToTracks.cpp
References kdfinder::abs(), and M_PI.
FW::ProcessCode FW::TruthVerticesToTracksAlgorithm::execute (const AlgorithmContext & context) const final override virtual
Framework execute method of the digitization algorithm
Parameters
context is the algorithm context that holds event-wise information
Returns
a process code to steer the algporithm flow
Implements FW::BareAlgorithm.
Definition at line 37 of file TruthVerticesToTracks.cpp.
View newest version in sPHENIX GitHub at line 37 of file TruthVerticesToTracks.cpp
References FW::WhiteBoard::add(), Acts::backward, Acts::IntegrationTest::bField, Acts::PropagatorOptions< action_list_t, aborter_list_t >::direction, FW::AlgorithmContext::eventStore, FW::AlgorithmContext::geoContext, FW::WhiteBoard::get(), FW::AlgorithmContext::magFieldContext, particle, Acts::VectorHelpers::perp(), Acts::Propagator< stepper_t, navigator_t >::propagate(), propagation_timing::stepper, SUCCESS, FW::VertexAndTracks::tracks, FW::VertexAndTracks::vertex, and vtx().
Member Data Documentation
Config FW::TruthVerticesToTracksAlgorithm::m_cfg private
Config struct.
Definition at line 82 of file TruthVerticesToTracks.hpp.
View newest version in sPHENIX GitHub at line 82 of file TruthVerticesToTracks.hpp
Referenced by TruthVerticesToTracksAlgorithm().
The documentation for this class was generated from the following files:
fun4all_acts/blob/master/Examples/Algorithms/TruthTracking/ACTFW/TruthTracking/TruthVerticesToTracks.hpp
fun4all_acts/blob/master/Examples/Algorithms/TruthTracking/ACTFW/TruthTracking/TruthVerticesToTracks.cpp