EIC Software: EicBlackHole Class Reference
EicBlackHole Class Reference
#include <EicRoot/blob/master/eic/base/EicBlackHole.h>
Public Member Functions
EicBlackHole ()
~EicBlackHole ()
Static Public Member Functions
static std::pair< int, int > GetParentIDs ()
static void ResetTrackList ()
static void InsertIntoTrackList (unsigned id)
static bool IsInTrackList (unsigned id)
Static Private Attributes
static std::set< unsigned > * mTracks = new std::set<unsigned>()
Detailed Description
Definition at line 13 of file EicBlackHole.h.
View newest version in sPHENIX GitHub at line 13 of file EicBlackHole.h
Constructor & Destructor Documentation
EicBlackHole::EicBlackHole () inline
Definition at line 15 of file EicBlackHole.h.
View newest version in sPHENIX GitHub at line 15 of file EicBlackHole.h
EicBlackHole::~EicBlackHole () inline
Definition at line 16 of file EicBlackHole.h.
View newest version in sPHENIX GitHub at line 16 of file EicBlackHole.h
Member Function Documentation
std::pair< int, int > EicBlackHole::GetParentIDs () static
Figure out GEANT primary track ID which produced hit in the current volume
Dig parent tree up to the primary particle; want to store this info with every MC hit; useful at least for calorimeter ideal reconstruction;
Definition at line 18 of file EicBlackHole.cxx.
View newest version in sPHENIX GitHub at line 18 of file EicBlackHole.cxx
References IsInTrackList(), and particle.
Referenced by EicDetector::ProcessHits().
static void EicBlackHole::InsertIntoTrackList (unsigned id) inline static
Definition at line 25 of file EicBlackHole.h.
View newest version in sPHENIX GitHub at line 25 of file EicBlackHole.h
References mTracks.
Referenced by EicMCApplication::Stepping().
static bool EicBlackHole::IsInTrackList (unsigned id) inline static
Definition at line 26 of file EicBlackHole.h.
View newest version in sPHENIX GitHub at line 26 of file EicBlackHole.h
References mTracks.
Referenced by GetParentIDs().
static void EicBlackHole::ResetTrackList () inline static
Definition at line 24 of file EicBlackHole.h.
View newest version in sPHENIX GitHub at line 24 of file EicBlackHole.h
References mTracks.
Referenced by EicDetector::BeginEvent().
Member Data Documentation
std::set< unsigned > * EicBlackHole::mTracks = new std::set<unsigned>() static private
Definition at line 28 of file EicBlackHole.h.
View newest version in sPHENIX GitHub at line 28 of file EicBlackHole.h
Referenced by InsertIntoTrackList(), IsInTrackList(), and ResetTrackList().
The documentation for this class was generated from the following files:
EicRoot/blob/master/eic/base/EicBlackHole.h
EicRoot/blob/master/eic/base/EicBlackHole.cxx