EIC Software: BeastMagneticField Class Reference
BeastMagneticField Class Reference
#include <BeastMagneticField/blob/master/include/BeastMagneticField.h>
Public Member Functions
BeastMagneticField (const char *fname, bool enforce_axial_symmetry=true)
~BeastMagneticField ()
bool ValidMapImported (void) const
void UseInterpolation (void)
void SetScale (double scale)
bool GetFieldValue (double x, double y, double z, double &bx, double &by, double &bz) const
bool GetFieldValue (double r, double z, double &br, double &bz) const
Private Attributes
double mCellSize
double mScale
unsigned mRdim
unsigned mZdim
double mRmin
double mZmin
bool mUseInterpolation
std::pair< double, double > * mFieldMap
Detailed Description
Definition at line 17 of file BeastMagneticField.h.
View newest version in sPHENIX GitHub at line 17 of file BeastMagneticField.h
Constructor & Destructor Documentation
BeastMagneticField::BeastMagneticField (const char * fname, bool enforce_axial_symmetry = true)
Definition at line 23 of file BeastMagneticField.cc.
View newest version in sPHENIX GitHub at line 23 of file BeastMagneticField.cc
References Acts::Test::dim, ir(), mCellSize, mFieldMap, mRdim, mRmin, mZdim, mZmin, printf(), and z.
BeastMagneticField::~BeastMagneticField () inline
Definition at line 21 of file BeastMagneticField.h.
View newest version in sPHENIX GitHub at line 21 of file BeastMagneticField.h
Member Function Documentation
bool BeastMagneticField::GetFieldValue (double x, double y, double z, double & bx, double & by, double & bz) const
Definition at line 118 of file BeastMagneticField.cc.
View newest version in sPHENIX GitHub at line 118 of file BeastMagneticField.cc
References cos().
Referenced by EtmAzimuthalScan::GetBfield(), and PHFieldBeast::GetFieldValue().
bool BeastMagneticField::GetFieldValue (double r, double z, double & br, double & bz) const
Definition at line 134 of file BeastMagneticField.cc.
View newest version in sPHENIX GitHub at line 134 of file BeastMagneticField.cc
References ip(), ir(), mCellSize, mFieldMap, mRdim, mRmin, mScale, mUseInterpolation, mZdim, and mZmin.
void BeastMagneticField::SetScale (double scale) inline
Definition at line 29 of file BeastMagneticField.h.
View newest version in sPHENIX GitHub at line 29 of file BeastMagneticField.h
References mScale.
void BeastMagneticField::UseInterpolation (void) inline
Definition at line 28 of file BeastMagneticField.h.
View newest version in sPHENIX GitHub at line 28 of file BeastMagneticField.h
References mUseInterpolation.
Referenced by PHFieldBeast::PHFieldBeast(), and EtmAzimuthalScan::SetBfield().
bool BeastMagneticField::ValidMapImported (void) const inline
Definition at line 23 of file BeastMagneticField.h.
View newest version in sPHENIX GitHub at line 23 of file BeastMagneticField.h
References mFieldMap.
Referenced by EtmAzimuthalScan::GetBfield(), PHFieldBeast::PHFieldBeast(), and EtmAzimuthalScan::SetBfield().
Member Data Documentation
double BeastMagneticField::mCellSize private
Definition at line 37 of file BeastMagneticField.h.
View newest version in sPHENIX GitHub at line 37 of file BeastMagneticField.h
Referenced by BeastMagneticField(), and GetFieldValue().
std::pair<double, double>* BeastMagneticField::mFieldMap private
Definition at line 51 of file BeastMagneticField.h.
View newest version in sPHENIX GitHub at line 51 of file BeastMagneticField.h
Referenced by BeastMagneticField(), GetFieldValue(), and ValidMapImported().
unsigned BeastMagneticField::mRdim private
Definition at line 44 of file BeastMagneticField.h.
View newest version in sPHENIX GitHub at line 44 of file BeastMagneticField.h
Referenced by BeastMagneticField(), and GetFieldValue().
double BeastMagneticField::mRmin private
Definition at line 47 of file BeastMagneticField.h.
View newest version in sPHENIX GitHub at line 47 of file BeastMagneticField.h
Referenced by BeastMagneticField(), and GetFieldValue().
double BeastMagneticField::mScale private
Definition at line 40 of file BeastMagneticField.h.
View newest version in sPHENIX GitHub at line 40 of file BeastMagneticField.h
Referenced by GetFieldValue(), and SetScale().
bool BeastMagneticField::mUseInterpolation private
Definition at line 50 of file BeastMagneticField.h.
View newest version in sPHENIX GitHub at line 50 of file BeastMagneticField.h
Referenced by GetFieldValue(), and UseInterpolation().
unsigned BeastMagneticField::mZdim private
Definition at line 44 of file BeastMagneticField.h.
View newest version in sPHENIX GitHub at line 44 of file BeastMagneticField.h
Referenced by BeastMagneticField(), and GetFieldValue().
double BeastMagneticField::mZmin private
Definition at line 47 of file BeastMagneticField.h.
View newest version in sPHENIX GitHub at line 47 of file BeastMagneticField.h
Referenced by BeastMagneticField(), and GetFieldValue().
The documentation for this class was generated from the following files:
BeastMagneticField/blob/master/include/BeastMagneticField.h
BeastMagneticField/blob/master/source/BeastMagneticField.cc