EIC Software: online_distribution/blob/master/newbasic/msg_buffer.cc File Reference
msg_buffer.cc File Reference
#include "msg_buffer.h"
#include <strnstr.h>
Functions
void streambuf_add_date (STREAMBUF *sb)
int printf (const char *format,...)
Function Documentation
int printf (const char * format, ...)
Definition at line 202 of file msg_buffer.cc.
View newest version in sPHENIX GitHub at line 202 of file msg_buffer.cc
References COUT, ENDL, and x.
Referenced by EicToyModel::acceptance(), AnnularFieldSim::add_testcharge(), EicMagneticFieldFromGradients::AddBeamLineElementGrads(), EicMagneticField::AddBeamLineElementGrads(), EicMagneticField::AddBeamLineElementMaps(), EtmPalette::AddEntry(), EicGeoMap::AddGeantVolumeLevel(), EicGeoParData::AddLogicalVolumeGroup(), FwdHoughTree::AddNodeGroup(), EicCadWizard::AddRootDirectory(), tetgenmesh::addsteiner4recoversegment(), AllocateBoundary(), EicStlMediaGroup::AllocateEdges(), AllocateKnots(), HoughTree::AllocateLookUpTable(), analysis(), analysis_vtx(), AnnularFieldSim::analyticFieldIntegral(), AnalyticFieldModel::AnalyticFieldModel(), AnnularFieldSim::AnnularFieldSim(), EicCadWizard::AssembleRootFiles(), EicEventAssembler::AssignScatteredLepton(), b0tracker(), BeastMagneticField::BeastMagneticField(), AnnularFieldSim::calc_unit_field(), tetgenmesh::calculateabovepoint(), EicGeoMap::CalculateBitPattern(), EicGeoMap::CalculateMappingTableSignature(), tetgenmesh::carvecavity(), tetgenmesh::carveholes(), FairDetParAsciiFileIo::checkAllFound(), HoughTree::CheckCell(), tetgenmesh::checkconforming(), tetgenmesh::checkdelaunay(), EicDetector::CheckEnergyMonitors(), BeamPipeGeoParData::CheckGeometry(), tetgenmesh::checkmesh(), tetgenmesh::checkregular(), tetgenmesh::checksegments(), tetgenmesh::checkshells(), Rossegger::CheckZeroes(), ClassImp(), PHHoughSeeding::CleanupSeeds(), CloneMeshes(), cmd_line_variable_parser(), tetgenmesh::collectremovepoints(), ConditionChecker(), EicHtcTask::ConfigureKalmanFilter(), tetgenmesh::constraineddelaunay(), tetgenmesh::constrainedfacets(), BasicDetectorConstruction::Construct(), EicToyModel::ConstructG4World(), VstGeoParData::ConstructGeometry(), FstGeoParData::ConstructGeometry(), GemGeoParData::ConstructGeometry(), ConvertEgTypeToMeshType(), EicCadWizard::ConvertSourceFileToRoot(), KfMatrix::CorrelationPrint(), EicStlMediaGroup::CoupleFacetToAssembly(), create_single_mgrid_header(), CreateAllBoundaries(), EicCadWizard::CreateBooleanSolidRootFile(), CreateBoundary(), CreateBoundaryLayer(), CreateBoundaryLayerDivide(), EtmDetectorStack::CreateDetector(), CreateDualGraph(), CreateInverseTopology(), CreateKnots(), CreateKnotsExtruded(), CreateNewNodes(), CreatePoints(), EicStlFactory::CreateRootFile(), CreateVariable(), e_narrowResonanceCrossSection::crossSectionCalculation(), incoherentVMCrossSection::crossSectionCalculation(), narrowResonanceCrossSection::crossSectionCalculation(), CylinderCoordinates(), CylindricalCoordinateCurve(), CylindricalCoordinateImprove(), CylindricalCoordinateTransformation(), declare_keyword(), EicHtcTask::DeclareSensitiveVolumes(), tetgenmesh::delaunayrefinement(), tetgenmesh::delaunizecavity(), DestroyBoundary(), DestroyDualGraph(), tetgenmesh::detectinterfaces(), DetermineFileType(), Packet_cdevmadch::dump(), dumpFrame(), dumpFrameHdr(), dumpFramePackets(), dumpPacket(), ValTimeStamp::DumpTMStruct(), eg_loadmesh(), eg_transfermesh(), EicAsciiBoxGenerator::EicAsciiBoxGenerator(), EicRootInputFile::EicRootInputFile(), EicRootManager::EicRootManager(), EicToyModel::EicToyModel(), EicTrackingDigiHitProducer::EicTrackingDigiHitProducer(), ElementsToBoundaryConditions(), ElementsToTriangles(), EicDetector::EndOfEvent(), Rossegger::Er(), exactinit(), ExampleGrid1D(), ExampleGrid2D(), ExampleGrid3D(), PndEventCounterTask::Exec(), EicEventAssembler::Exec(), PndRecoKalmanTask::Exec(), EicDigiHitProducer::Exec(), EicCalorimeterReconstruction::Exec(), FwdTrackFinder::Exec(), EicHtcTask::Exec(), CbmRich::ExpandNodeForGdml(), EicMagneticField::Export(), EicToyModel::Export(), EicToyModel::ExportCADmodelCore(), EicToyModel::ExportVacuumChamber(), EicCadWizard::FaceGuidedSplit(), fakeFrame(), femc(), AnnularFieldSim::fieldIntegral(), tetgenmesh::fillcavity(), FluxMonitorGrid::FillOutHistograms(), AnnularFieldSim::FilterPhiIndex(), FwdHoughTree::FinalFit(), FindBoundaryBoundary(), FindBulkBoundary(), FindEdges(), Rossegger::FindMunk(), FindNewBoundaries(), Rossegger::FindNextZero(), FindParentSide(), FindPeriodicBoundary(), FindPeriodicNodes(), FindPointParents(), EicJEventProcessor::Finish(), EicFluxMonitorTask::FinishTask(), EicCadWizard::FlatSurfaceSplit(), tetgenmesh::flipcertify(), tetgenmesh::flipinsertfacet(), tetgenmesh::flipnm_post(), for(), tetgenmesh::formcavity(), KalmanFilter::FullChain(), FairGeaneApplication::GeaneStepping(), generate_distortion_map(), AnnularFieldSim::GenerateDistortionMaps(), AnnularFieldSim::GenerateSeparateDistortionMaps(), MultiArray< TVector3 >::Get(), FwdHoughTree::GetBzAtIP(), GetCommand(), tetgenmesh::getedge(), GetElementCoordinates(), GetElementDimension(), GetElementIndices(), GetElementSide(), EicJEventSource::GetEvent(), EicBeamLineElementMap::GetFieldValue(), EtmDetector::GetG4Volume(), AnnularFieldSim::GetGroupCellCenter(), Getline(), EicDetector::GetNodeMultiIndex(), GetSideInfo(), GFTools::getSmoothedData(), AnnularFieldSim::GetStepDistortion(), AnnularFieldSim::GetTotalDistortion(), GmshToElmerType(), EicCalorimeterDigiHitProducer::HandleHit(), hcal(), tetgenmesh::highorder(), HoughDimension::HoughDimension(), tetgenmesh::identifypscedges(), EicToyModel::Import(), EicGeoParData::ImportMediaFile(), ImportMeshDefinition(), tetgenmesh::improvequalitybyflips(), tetgenmesh::improvequalitybysmoothing(), IncreaseElementOrder(), tetgenmesh::incrementaldelaunay(), tetgenmesh::incrementalflip(), EicJEventProcessor::Init(), FwdTrackFinder::Init(), EicRunSim::Init(), tetgenmesh::initialdelaunay(), EicBeamLineElementMap::Initialize(), HtcKalmanFilter::InitializeMgridSlice(), tetgenmesh::initializepools(), InlineParameters(), EtmDetector::insert(), tetgenmesh::insertconstrainedpoints(), tetgenmesh::insertpoint(), tetgenmesh::insertpoint_cdt(), tetgenmesh::interecursive(), AnnularFieldSim::interpolatedFieldIntegral(), tetgenmesh::interpolatemeshsize(), tetgenmesh::jettisonnodes(), HoughTree::LaunchPatternFinder(), tetgenmesh::lawsonflip(), tetgenmesh::lawsonflip3d(), AnnularFieldSim::load_analytic_spacecharge(), AnnularFieldSim::load_and_resample_spacecharge(), tetgenio::load_edge(), tetgenio::load_face(), tetgenio::load_medit(), tetgenio::load_mtr(), tetgenio::load_node(), tetgenio::load_node_call(), tetgenio::load_off(), AnnularFieldSim::load_phislice_lookup(), tetgenio::load_ply(), tetgenio::load_poly(), AnnularFieldSim::load_spacecharge(), tetgenio::load_stl(), tetgenio::load_tet(), tetgenio::load_var(), tetgenio::load_vol(), tetgenio::load_vtk(), LoadAbaqusInput(), LoadAnsysInput(), LoadCGsimMesh(), LoadCommands(), LoadComsolMesh(), LoadElmergrid(), LoadFidapInput(), AnnularFieldSim::loadField(), LoadFieldviewInput(), LoadGidInput(), LoadGmshInput(), LoadGmshInput1(), LoadGmshInput2(), LoadMeditInput(), LoadNastranInput(), LoadTriangleInput(), LoadUniversalMesh(), Rossegger::LoadZeroes(), EicCompositeShape::LocalFillBuffer3D(), main(), make_single_tower(), tetgenmesh::makefacetverticesmap(), tetgenmesh::makeindex2pointmap(), tetgenmesh::makepoint2submap(), tetgenmesh::makesegmentendpointsmap(), EtmDetectorStack::marker(), tetgenmesh::memorystatistics(), MergeBoundaries(), EicStlMediaGroup::MergeDegenerateVertices(), MergeElements(), tetgenmesh::mergefacets(), tetgenmesh::meshcoarsening(), tetgenmesh::meshsurface(), MeshTypeStatistics(), mfield2eve(), MirrorMeshes(), FairRKPropagator::OneStepRungeKutta(), tetgenmesh::optimizemesh(), tetgenmesh::outedges(), tetgenmesh::outelements(), tetgenmesh::outfaces(), tetgenmesh::outhullfaces(), tetgenmesh::outmesh2medit(), tetgenmesh::outmesh2vtk(), tetgenmesh::outmetrics(), tetgenmesh::outneighbors(), tetgenmesh::outnodes(), tetgenmesh::outsmesh(), tetgenmesh::outsubfaces(), tetgenmesh::outsubsegments(), tetgenmesh::outvoronoi(), tetgenbehavior::parse_commandline(), EicHtcTask::PerformMediaScan(), photonNucleusCrossSection::photonFlux(), AnnularFieldSim::PlotFieldSlices(), PolarCoordinates(), AnnularFieldSim::populate_fieldmap(), AnnularFieldSim::populate_full3d_lookup(), AnnularFieldSim::populate_highres_lookup(), AnnularFieldSim::populate_lookup(), AnnularFieldSim::populate_phislice_lookup(), EicCalorimeterDigiHitProducer::PostExec(), Rossegger::PrecalcDerivedConstants(), Rossegger::PrecalcFreeConstants(), TpcDigiParData::Print(), FairFileInfo::Print(), MediaBank::Print(), ValContext::Print(), ValRange::Print(), MagElement::Print(), FairGeoVector::print(), KfMatrix::Print(), SegmentationAlpide::print(), EicStlVertex::Print(), Dipole::Print(), Quadrupole::Print(), SourceFile::Print(), ValTimeStamp::Print(), EicHtcTask::Print(), EicGeoParData::Print(), genfit::Track::Print(), EicGeoParData::PrintAttachedSourceFile(), RKTools::printDim(), genfit::RKTools::printDim(), tetgenmesh::printfcomma(), FairGeoTube::printPoints(), FairGeoAssembly::printPoints(), FairGeoTorus::printPoints(), FairGeoTubs::printPoints(), FairGeoSphe::printPoints(), FairGeoPgon::printPoints(), FairGeoEltu::printPoints(), FairGeoCons::printPoints(), FairGeoPcon::printPoints(), FairGeoCone::printPoints(), FairGeoBasicShape::printPoints(), EicJEventProcessor::Process(), TpcClusterizer::process_event(), PHTpcCentralMembraneClusterizer::process_event(), TPCFEETestRecov1::process_event(), FairRKPropagator::Propagat(), tetgenmesh::qualitystatistics(), rad_length(), tetgenmesh::randomsample(), EicBoxGenerator::ReadEvent(), EicEventGenerator::ReadEvent(), Mgrid::recalculatePosition(), tetgenmesh::reconstructmesh(), tetgenmesh::recoverboundary(), tetgenmesh::recoverdelaunay(), tetgenmesh::recoveredgebyflips(), tetgenmesh::recoverfacebyflips(), tetgenmesh::recoversegments(), tetgenmesh::recoversubfaces(), ReduceElementOrder(), tetgenmesh::refineregion(), RemoveLowerDimensionalBoundaries(), tetgenmesh::removeslivers(), RemoveUnusedNodes(), tetgenmesh::removevertexbyflips(), RenumberBoundaryTypes(), RenumberMaterialTypes(), ReorderAnsysNodes(), ReorderAutomatic(), ReorderElements(), ReorderFidapNodes(), ReorderFieldviewNodes(), tetgenmesh::repairbadtets(), tetgenmesh::repairencfacs(), tetgenmesh::repairencsegs(), FairRadMapManager::Reset(), ResolutionLevel::ResolutionLevel(), FwdHoughTree::ResolveAmbiguitiesNg(), Rossegger::Rnk_for_zeroes(), Rossegger::Rnk_for_zeroes_(), RotateTranslateScale(), EicRunSim::RunCoreStart(), runge_kutta_fun(), tetgenio::save_edges(), tetgenio::save_elements(), tetgenio::save_faces(), tetgenio::save_faces2smesh(), tetgenio::save_neighbors(), tetgenio::save_nodes(), AnnularFieldSim::save_phislice_lookup(), tetgenio::save_poly(), SaveElmergrid(), tetgenmesh::scoutsegment(), tetgenmesh::scoutsubface(), SeparateCartesianBoundaries(), SeparateMainaxisBoundaries(), SetCellData(), SetCellKnots(), SetCellKnots1D(), SetDefaultMatrixName(), SetDiscontinuousBoundary(), SetElementDivision(), SetElementDivisionCylinder(), SetElementDivisionExtruded(), AnnularFieldSim::setFlatFields(), EicGeoMap::SetMappingTableEntry(), EicGeoParData::SetMappingTableEntry(), EicRootInputFile::SetupBranch(), SetupDefaultSphenixTpc(), SetupDigitalCurrentSphenixTpc(), FwdMatchCandidate::SetVtxMomentum(), SideAndBulkMappings(), simulation(), tetgenmesh::sinsertvertex(), KalmanFilter::SmootherPass(), SortIndex(), SourceFile::SourceFile(), EicCadWizard::SplitAndRescaleSourceFile(), EicStlMediaGroup::SplitIntoAssemblies(), tetgenmesh::sremovevertex(), tetgenmesh::sscoutsegment(), star(), MediaBank::StartNextLayer(), tetgenmesh::statistics(), stvector(), AnnularFieldSim::sum_field_at(), AnnularFieldSim::sum_local_field_at(), AnnularFieldSim::sum_nonlocal_field_at(), tetgenmesh::suppressbdrysteinerpoint(), tetgenmesh::suppresssteinerpoints(), SurveyFiles(), AnnularFieldSim::swimToInAnalyticSteps(), tetgenbehavior::syntax(), terminatetetgen(), test_double(), tetrahedralize(), PHGenFitTrkProp::TrackPropPatRec(), tetgenmesh::transfernodes(), tetgenmesh::triangulate(), twoPhotonLuminosity::twoPhotonDifferentialLuminosity(), tetgenmesh::unifysegments(), tetgenmesh::unifysubfaces(), UniteMeshes(), UnvRedundantIndexes(), UnvToElmerType(), usage(), tetgenbehavior::usage(), Rossegger::Verbosity(), viewer(), and VstRadLength().
void streambuf_add_date (STREAMBUF * sb)
Definition at line 170 of file msg_buffer.cc.
View newest version in sPHENIX GitHub at line 170 of file msg_buffer.cc
References G4BARRELHCAL::length.
Referenced by date_filter_msg_buffer::sync().