EIC Software: fun4all_macros/blob/master/common/G4_TrackingService.C File Reference
G4_TrackingService.C File Reference
#include <GlobalVariables.C>
#include <QA.C>
#include <g4detectors/PHG4ConeSubsystem.h>
#include <g4detectors/PHG4CylinderSubsystem.h>
#include <g4main/PHG4Reco.h>
#include <qa_modules/QAG4SimulationMvtx.h>
#include <fun4all/Fun4AllServer.h>
#include <boost/format.hpp>
#include <cmath>
#include <iostream>
#include <string>
#include <vector>
Classes
class ServiceStructure
Namespaces
namespace Enable
namespace G4TrackingService
Macros
#define MACRO_G4TrackingService_C
Functions
vector< float > get_thickness (ServiceStructure *object)
void TrackingServiceInit ()
float TrackingServiceCone (ServiceStructure *object, PHG4Reco *g4Reco, float radius)
float TrackingServiceCylinder (ServiceStructure *object, PHG4Reco *g4Reco, float radius)
float TrackingService (PHG4Reco *g4Reco, float radius)
Variables
bool Enable::TrackingService = false
bool Enable::TrackingService_ABSORBER = false
bool Enable::TrackingService_OVERLAPCHECK = false
int Enable::TrackingService_VERBOSITY = 0
string G4TrackingService::materials [] = {"G4_Cu", "G4_WATER", "G4_POLYETHYLENE", "PEEK"}
const int G4TrackingService::nMaterials = sizeof(materials)/sizeof(materials[0])
float G4TrackingService::GlobalOffset = -15.0
float G4TrackingService::BarrelOffset = 18.679
float G4TrackingService::BarrelRadius = 10.33
float G4TrackingService::BarrelThickness = 0.436
float G4TrackingService::BarrelLength = 121.24
float G4TrackingService::LayerThickness = 0.1
float G4TrackingService::CYSSConeThickness = 0.216
float G4TrackingService::CYSSRibThickness = 0.170
int G4TrackingService::subsysID = 0
std::vector< float > G4TrackingService::grey = {0.4, 0.4, 0.4}
Macro Definition Documentation
#define MACRO_G4TrackingService_C
Definition at line 2 of file G4_TrackingService.C.
View newest version in sPHENIX GitHub at line 2 of file G4_TrackingService.C
Function Documentation
vector<float> get_thickness (ServiceStructure * object)
Definition at line 123 of file G4_TrackingService.C.
View newest version in sPHENIX GitHub at line 123 of file G4_TrackingService.C
References thickness.
Referenced by PHG4TpcDigitizer::CalculateCylinderCellADCScale(), PHG4InttDigitizer::CalculateLadderCellADCScale(), InttClusterizer::CalculateLadderThresholds(), PHG4FullProjTiltedSpacalDetector::Construct_AzimuthalSeg(), PHG4FullProjSpacalDetector::Construct_AzimuthalSeg(), TrackingServiceCone(), and TrackingServiceCylinder().
float TrackingService (PHG4Reco * g4Reco, float radius)
Definition at line 214 of file G4_TrackingService.C.
View newest version in sPHENIX GitHub at line 214 of file G4_TrackingService.C
References G4TrackingService::BarrelLength, G4TrackingService::BarrelOffset, G4TrackingService::BarrelRadius, G4TrackingService::BarrelThickness, G4TrackingService::CYSSConeThickness, G4TrackingService::CYSSRibThickness, G4TrackingService::LayerThickness, G4BECAL::radius, TrackingServiceCone(), and TrackingServiceCylinder().
Referenced by G4Setup().
float TrackingServiceCone (ServiceStructure * object, PHG4Reco * g4Reco, float radius)
Definition at line 142 of file G4_TrackingService.C.
View newest version in sPHENIX GitHub at line 142 of file G4_TrackingService.C
References kdfinder::abs(), Enable::ABSORBER, Acts::UnitConstants::e, ServiceStructure::get_name(), get_thickness(), ServiceStructure::get_zNorth(), ServiceStructure::get_zSouth(), G4TrackingService::GlobalOffset, G4TrackingService::grey, G4BARRELHCAL::length, G4TrackingService::materials, max, G4TrackingService::nMaterials, Enable::OVERLAPCHECK, PHG4DetectorSubsystem::OverlapCheck(), G4BECAL::radius, PHG4Reco::registerSubsystem(), PHG4ConeSubsystem::set_color(), PHG4DetectorSubsystem::SetActive(), PHG4ConeSubsystem::SetMaterial(), PHG4ConeSubsystem::SetPlaceZ(), PHG4ConeSubsystem::SetR1(), PHG4ConeSubsystem::SetR2(), PHG4ConeSubsystem::SetZlength(), G4TrackingService::subsysID, PHG4DetectorSubsystem::SuperDetector(), thickness, Enable::TrackingService_ABSORBER, Enable::TrackingService_OVERLAPCHECK, Enable::TrackingService_VERBOSITY, Enable::VERBOSITY, and Fun4AllBase::Verbosity().
Referenced by TrackingService().
float TrackingServiceCylinder (ServiceStructure * object, PHG4Reco * g4Reco, float radius)
Definition at line 179 of file G4_TrackingService.C.
View newest version in sPHENIX GitHub at line 179 of file G4_TrackingService.C
References kdfinder::abs(), Enable::ABSORBER, Acts::UnitConstants::e, ServiceStructure::get_name(), get_thickness(), ServiceStructure::get_zNorth(), ServiceStructure::get_zSouth(), G4TrackingService::GlobalOffset, G4TrackingService::grey, G4BARRELHCAL::length, G4TrackingService::materials, max, G4TrackingService::nMaterials, Enable::OVERLAPCHECK, PHG4DetectorSubsystem::OverlapCheck(), G4BECAL::radius, PHG4Reco::registerSubsystem(), PHG4CylinderSubsystem::set_color(), PHG4DetectorSubsystem::set_double_param(), PHG4DetectorSubsystem::set_string_param(), PHG4DetectorSubsystem::SetActive(), G4TrackingService::subsysID, PHG4DetectorSubsystem::SuperDetector(), thickness, Enable::TrackingService_ABSORBER, Enable::TrackingService_OVERLAPCHECK, Enable::TrackingService_VERBOSITY, Enable::VERBOSITY, and Fun4AllBase::Verbosity().
Referenced by TrackingService().
void TrackingServiceInit ()
Definition at line 132 of file G4_TrackingService.C.
View newest version in sPHENIX GitHub at line 132 of file G4_TrackingService.C
References G4TrackingService::BarrelLength, G4TrackingService::BarrelOffset, G4TrackingService::BarrelRadius, G4TrackingService::BarrelThickness, G4TrackingService::GlobalOffset, max, BlackHoleGeometry::max_radius, BlackHoleGeometry::max_z, min, and BlackHoleGeometry::min_z.
Referenced by G4Init().