EIC Software: MapsStave Class Reference
MapsStave Class Reference
#include <EicRoot/blob/master/eic/detectors/maps/MapsGeoParData.h>
Public Member Functions
MapsStave ()
MapsStave (const char *name)
~MapsStave ()
TGeoVolume * GetVolume () const
const double GetLength () const
MapsStave ()
MapsStave (const char *name)
~MapsStave ()
TGeoVolume * GetVolume () const
const double GetLength () const
Private Member Functions
void ResetVars ()
calculated stave length
ClassDef (MapsStave, 1)
void ResetVars ()
calculated stave length
ClassDef (MapsStave, 1)
Private Attributes
TGeoVolume * mVolume
double mLength
ROOT TGeoVolume.
Friends
class MapsGeoParData
Detailed Description
Definition at line 20 of file MapsGeoParData.h.
View newest version in sPHENIX GitHub at line 20 of file MapsGeoParData.h
Constructor & Destructor Documentation
MapsStave::MapsStave () inline
Definition at line 25 of file MapsGeoParData.h.
View newest version in sPHENIX GitHub at line 25 of file MapsGeoParData.h
References ResetVars().
MapsStave::MapsStave (const char * name) inline
Definition at line 26 of file MapsGeoParData.h.
View newest version in sPHENIX GitHub at line 26 of file MapsGeoParData.h
References ResetVars().
MapsStave::~MapsStave () inline
Definition at line 27 of file MapsGeoParData.h.
View newest version in sPHENIX GitHub at line 27 of file MapsGeoParData.h
MapsStave::MapsStave () inline
Definition at line 25 of file MapsGeoParData.h.
View newest version in sPHENIX GitHub at line 25 of file MapsGeoParData.h
References ResetVars().
MapsStave::MapsStave (const char * name) inline
Definition at line 26 of file MapsGeoParData.h.
View newest version in sPHENIX GitHub at line 26 of file MapsGeoParData.h
References ResetVars().
MapsStave::~MapsStave () inline
Definition at line 27 of file MapsGeoParData.h.
View newest version in sPHENIX GitHub at line 27 of file MapsGeoParData.h
Member Function Documentation
MapsStave::ClassDef (MapsStave , 1) private
MapsStave::ClassDef (MapsStave , 1) private
const double MapsStave::GetLength () const inline
Definition at line 30 of file MapsGeoParData.h.
View newest version in sPHENIX GitHub at line 30 of file MapsGeoParData.h
Referenced by VstGeoParData::ConstructGeometry(), and FstGeoParData::ConstructGeometry().
const double MapsStave::GetLength () const inline
Definition at line 30 of file MapsGeoParData.h.
View newest version in sPHENIX GitHub at line 30 of file MapsGeoParData.h
References mLength.
TGeoVolume* MapsStave::GetVolume () const inline
Definition at line 29 of file MapsGeoParData.h.
View newest version in sPHENIX GitHub at line 29 of file MapsGeoParData.h
References mVolume.
TGeoVolume* MapsStave::GetVolume () const inline
Definition at line 29 of file MapsGeoParData.h.
View newest version in sPHENIX GitHub at line 29 of file MapsGeoParData.h
References mVolume.
Referenced by VstGeoParData::ConstructGeometry(), and FstGeoParData::ConstructGeometry().
void MapsStave::ResetVars () inline private
calculated stave length
Definition at line 36 of file MapsGeoParData.h.
View newest version in sPHENIX GitHub at line 36 of file MapsGeoParData.h
References mLength, and mVolume.
Referenced by MapsStave().
void MapsStave::ResetVars () inline private
calculated stave length
Definition at line 36 of file MapsGeoParData.h.
View newest version in sPHENIX GitHub at line 36 of file MapsGeoParData.h
References mLength, and mVolume.
Friends And Related Function Documentation
MapsGeoParData friend
Definition at line 22 of file MapsGeoParData.h.
View newest version in sPHENIX GitHub at line 22 of file MapsGeoParData.h
Member Data Documentation
double MapsStave::mLength private
ROOT TGeoVolume.
Definition at line 34 of file MapsGeoParData.h.
View newest version in sPHENIX GitHub at line 34 of file MapsGeoParData.h
Referenced by MapsGeoParData::ConstructStave(), GetLength(), and ResetVars().
TGeoVolume * MapsStave::mVolume private
Definition at line 30 of file MapsGeoParData.h.
View newest version in sPHENIX GitHub at line 30 of file MapsGeoParData.h
Referenced by MapsGeoParData::ConstructStave(), GetVolume(), and ResetVars().
The documentation for this class was generated from the following files:
EicRoot/blob/master/eic/detectors/maps/MapsGeoParData.h
EicToyModel/blob/master/include/MapsGeoParData.h