EIC Software: RawTowerZDCv1 Class Reference
RawTowerZDCv1 Class Reference
#include <fun4all_eicdetectors/blob/master/reconstruction/eiczdcbase/RawTowerZDCv1.h>
Public Member Functions
RawTowerZDCv1 ()
RawTowerZDCv1 (const RawTowerZDC &tower)
RawTowerZDCv1 (RawTowerZDCDefs::keytype id)
~RawTowerZDCv1 () override
void Reset () override
Clear Event.
int isValid () const override
isValid returns non zero if object contains vailid data
void identify (std::ostream &os=std::cout) const override
void set_id (RawTowerZDCDefs::keytype id) override
RawTowerZDCDefs::keytype get_id () const override
int get_bineta () const override
int get_binphi () const override
int get_binl () const override
return layer ID assigned to tower
double get_energy () const override
energy assigned to the tower. Depending on stage of process and DST node name, it could be energy deposition, light yield or calibrated energies
void set_energy (const double e) override
energy assigned to the tower. Depending on stage of process and DST node name, it could be energy deposition, light yield or calibrated energies
float get_time () const override
Time stamp assigned to the tower. Depending on the tower maker, it could be rise time or peak time.
void set_time (const float t) override
Time stamp assigned to the tower. Depending on the tower maker, it could be rise time or peak time.
bool empty_g4cells () const override
size_t size_g4cells () const override
RawTowerZDC::CellConstRange get_g4cells () const override
RawTowerZDC::CellIterator find_g4cell (CellKeyType id) override
RawTowerZDC::CellConstIterator find_g4cell (CellKeyType id) const override
void add_ecell (const CellKeyType g4cellid, const float ecell) override
void clear_g4cells () override
bool empty_g4showers () const override
size_t size_g4showers () const override
RawTowerZDC::ShowerConstRange get_g4showers () const override
RawTowerZDC::ShowerIterator find_g4shower (int id) override
RawTowerZDC::ShowerConstIterator find_g4shower (int id) const override
void add_eshower (const int g4showerid, const float eshower) override
void clear_g4showers () override
Public Member Functions inherited from RawTowerZDC
~RawTowerZDC () override
virtual void set_key (RawTowerZDCDefs::keytype id)
virtual RawTowerZDCDefs::keytype get_key () const
virtual int get_bintheta () const
virtual int get_column () const
virtual int get_row () const
virtual double get_scint_gammas () const
energy assigned to the tower. Depending on stage of process and DST node name, it could be energy deposition, light yield or calibrated energies
virtual void set_scint_gammas (const double)
scint_gammas assigned to the tower. Depending on stage of process and DST node name, it could be scint_gammas deposition, light yield or calibrated energies
virtual double get_cerenkov_gammas () const
energy assigned to the tower. Depending on stage of process and DST node name, it could be energy deposition, light yield or calibrated energies
virtual void set_cerenkov_gammas (const double)
cerenkov_gammas assigned to the tower. Depending on stage of process and DST node name, it could be cerenkov_gammas deposition, light yield or calibrated energies
virtual bool has_property (const PROPERTY) const
virtual double get_property (const PROPERTY) const
virtual void set_property (const PROPERTY, const double)
Public Member Functions inherited from PHObject
PHObject ()
ctor
~PHObject () override
dtor
virtual PHObject * CloneMe () const
Virtual copy constructor.
virtual PHObject * clone () const final
PHObject * Clone (const char *newname="") const final
void Copy (TObject &object) const final
virtual int isValid (const float) const
virtual int isValid (const double) const
virtual int isValid (const int) const
virtual int isValid (const unsigned int) const
virtual int isImplemented (const float f) const
virtual int isImplemented (const double f) const
virtual int isImplemented (const int i) const
virtual int isImplemented (const unsigned int i) const
virtual int Integrate () const
virtual int Integrate (PHObject *)
virtual void CopyFrom (const PHObject *obj)
Protected Attributes
RawTowerZDCDefs::keytype towerid = ~0
double energy = 0.
float time = NAN
CellMap ecells
ShowerMap eshowers
Additional Inherited Members
Public Types inherited from RawTowerZDC
enum PROPERTY { prop_scint_gammas = 1, prop_cerenkov_gammas = 2, prop_MAX_NUMBER = UCHAR_MAX }
typedef unsigned long long CellKeyType
key type for cell map which should be consistent with CellKeyType
typedef std::map< CellKeyType,
float > CellMap
typedef CellMap::iterator CellIterator
typedef CellMap::const_iterator CellConstIterator
typedef std::pair
< CellIterator, CellIterator > CellRange
typedef std::pair
< CellConstIterator,
CellConstIterator > CellConstRange
typedef std::map< int, float > ShowerMap
typedef ShowerMap::iterator ShowerIterator
typedef ShowerMap::const_iterator ShowerConstIterator
typedef std::pair
< ShowerIterator,
ShowerIterator > ShowerRange
typedef std::pair
< ShowerConstIterator,
ShowerConstIterator > ShowerConstRange
Static Public Member Functions inherited from RawTowerZDC
static const std::string get_property_info (PROPERTY prop_id)
Protected Member Functions inherited from RawTowerZDC
RawTowerZDC ()
virtual unsigned int get_property_nocheck (const PROPERTY) const
virtual void set_property_nocheck (const PROPERTY, const unsigned int)
Detailed Description
Definition at line 13 of file RawTowerZDCv1.h.
View newest version in sPHENIX GitHub at line 13 of file RawTowerZDCv1.h
Constructor & Destructor Documentation
RawTowerZDCv1::RawTowerZDCv1 () inline
Definition at line 16 of file RawTowerZDCv1.h.
View newest version in sPHENIX GitHub at line 16 of file RawTowerZDCv1.h
RawTowerZDCv1::RawTowerZDCv1 (const RawTowerZDC & tower)
Definition at line 8 of file RawTowerZDCv1.cc.
View newest version in sPHENIX GitHub at line 8 of file RawTowerZDCv1.cc
References RawTowerZDC::get_energy(), RawTowerZDC::get_g4cells(), RawTowerZDC::get_g4showers(), RawTowerZDC::get_id(), RawTowerZDC::get_time(), and Acts::Test::time.
RawTowerZDCv1::RawTowerZDCv1 (RawTowerZDCDefs::keytype id)
Definition at line 31 of file RawTowerZDCv1.cc.
View newest version in sPHENIX GitHub at line 31 of file RawTowerZDCv1.cc
RawTowerZDCv1::~RawTowerZDCv1 () inline override
Definition at line 19 of file RawTowerZDCv1.h.
View newest version in sPHENIX GitHub at line 19 of file RawTowerZDCv1.h
Member Function Documentation
void RawTowerZDCv1::add_ecell (const CellKeyType g4cellid, const float ecell) override virtual
Reimplemented from RawTowerZDC.
Definition at line 58 of file RawTowerZDCv1.cc.
View newest version in sPHENIX GitHub at line 58 of file RawTowerZDCv1.cc
References ecells.
void RawTowerZDCv1::add_eshower (const int g4showerid, const float eshower) override virtual
Reimplemented from RawTowerZDC.
Definition at line 71 of file RawTowerZDCv1.cc.
View newest version in sPHENIX GitHub at line 71 of file RawTowerZDCv1.cc
References eshowers.
void RawTowerZDCv1::clear_g4cells () inline override virtual
Reimplemented from RawTowerZDC.
Definition at line 48 of file RawTowerZDCv1.h.
View newest version in sPHENIX GitHub at line 48 of file RawTowerZDCv1.h
References ecells.
void RawTowerZDCv1::clear_g4showers () inline override virtual
Reimplemented from RawTowerZDC.
Definition at line 61 of file RawTowerZDCv1.h.
View newest version in sPHENIX GitHub at line 61 of file RawTowerZDCv1.h
References eshowers.
bool RawTowerZDCv1::empty_g4cells () const inline override virtual
Reimplemented from RawTowerZDC.
Definition at line 38 of file RawTowerZDCv1.h.
View newest version in sPHENIX GitHub at line 38 of file RawTowerZDCv1.h
References ecells.
bool RawTowerZDCv1::empty_g4showers () const inline override virtual
Reimplemented from RawTowerZDC.
Definition at line 52 of file RawTowerZDCv1.h.
View newest version in sPHENIX GitHub at line 52 of file RawTowerZDCv1.h
References eshowers.
RawTowerZDC::CellIterator RawTowerZDCv1::find_g4cell (CellKeyType id) inline override virtual
Reimplemented from RawTowerZDC.
Definition at line 44 of file RawTowerZDCv1.h.
View newest version in sPHENIX GitHub at line 44 of file RawTowerZDCv1.h
References ecells.
RawTowerZDC::CellConstIterator RawTowerZDCv1::find_g4cell (CellKeyType id) const inline override virtual
Reimplemented from RawTowerZDC.
Definition at line 45 of file RawTowerZDCv1.h.
View newest version in sPHENIX GitHub at line 45 of file RawTowerZDCv1.h
References ecells.
RawTowerZDC::ShowerIterator RawTowerZDCv1::find_g4shower (int id) inline override virtual
Reimplemented from RawTowerZDC.
Definition at line 58 of file RawTowerZDCv1.h.
View newest version in sPHENIX GitHub at line 58 of file RawTowerZDCv1.h
References eshowers.
RawTowerZDC::ShowerConstIterator RawTowerZDCv1::find_g4shower (int id) const inline override virtual
Reimplemented from RawTowerZDC.
Definition at line 59 of file RawTowerZDCv1.h.
View newest version in sPHENIX GitHub at line 59 of file RawTowerZDCv1.h
References eshowers.
int RawTowerZDCv1::get_bineta () const override virtual
Reimplemented from RawTowerZDC.
Definition at line 83 of file RawTowerZDCv1.cc.
View newest version in sPHENIX GitHub at line 83 of file RawTowerZDCv1.cc
References RawTowerZDCDefs::decode_index1zdc(), and towerid.
Referenced by identify().
int RawTowerZDCv1::get_binl () const override virtual
return layer ID assigned to tower
Reimplemented from RawTowerZDC.
Definition at line 93 of file RawTowerZDCv1.cc.
View newest version in sPHENIX GitHub at line 93 of file RawTowerZDCv1.cc
References RawTowerZDCDefs::decode_index3zdc(), and towerid.
Referenced by identify().
int RawTowerZDCv1::get_binphi () const override virtual
Reimplemented from RawTowerZDC.
Definition at line 88 of file RawTowerZDCv1.cc.
View newest version in sPHENIX GitHub at line 88 of file RawTowerZDCv1.cc
References RawTowerZDCDefs::decode_index2zdc(), and towerid.
Referenced by identify().
double RawTowerZDCv1::get_energy () const inline override virtual
energy assigned to the tower. Depending on stage of process and DST node name, it could be energy deposition, light yield or calibrated energies
Reimplemented from RawTowerZDC.
Definition at line 31 of file RawTowerZDCv1.h.
View newest version in sPHENIX GitHub at line 31 of file RawTowerZDCv1.h
References energy.
Referenced by identify(), and isValid().
RawTowerZDC::CellConstRange RawTowerZDCv1::get_g4cells () const inline override virtual
Reimplemented from RawTowerZDC.
Definition at line 40 of file RawTowerZDCv1.h.
View newest version in sPHENIX GitHub at line 40 of file RawTowerZDCv1.h
References ecells.
RawTowerZDC::ShowerConstRange RawTowerZDCv1::get_g4showers () const inline override virtual
Reimplemented from RawTowerZDC.
Definition at line 54 of file RawTowerZDCv1.h.
View newest version in sPHENIX GitHub at line 54 of file RawTowerZDCv1.h
References eshowers.
RawTowerZDCDefs::keytype RawTowerZDCv1::get_id () const inline override virtual
Reimplemented from RawTowerZDC.
Definition at line 26 of file RawTowerZDCv1.h.
View newest version in sPHENIX GitHub at line 26 of file RawTowerZDCv1.h
References towerid.
float RawTowerZDCv1::get_time () const inline override virtual
Time stamp assigned to the tower. Depending on the tower maker, it could be rise time or peak time.
Reimplemented from RawTowerZDC.
Definition at line 33 of file RawTowerZDCv1.h.
View newest version in sPHENIX GitHub at line 33 of file RawTowerZDCv1.h
References time.
void RawTowerZDCv1::identify (std::ostream & os = std::cout) const override virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from RawTowerZDC.
Definition at line 49 of file RawTowerZDCv1.cc.
View newest version in sPHENIX GitHub at line 49 of file RawTowerZDCv1.cc
References get_bineta(), get_binl(), get_binphi(), and get_energy().
int RawTowerZDCv1::isValid () const override virtual
isValid returns non zero if object contains vailid data
Reimplemented from RawTowerZDC.
Definition at line 44 of file RawTowerZDCv1.cc.
View newest version in sPHENIX GitHub at line 44 of file RawTowerZDCv1.cc
References get_energy().
void RawTowerZDCv1::Reset () override virtual
Clear Event.
Reimplemented from RawTowerZDC.
Definition at line 36 of file RawTowerZDCv1.cc.
View newest version in sPHENIX GitHub at line 36 of file RawTowerZDCv1.cc
References ecells, energy, eshowers, and time.
void RawTowerZDCv1::set_energy (const double) inline override virtual
energy assigned to the tower. Depending on stage of process and DST node name, it could be energy deposition, light yield or calibrated energies
Reimplemented from RawTowerZDC.
Definition at line 32 of file RawTowerZDCv1.h.
View newest version in sPHENIX GitHub at line 32 of file RawTowerZDCv1.h
References Acts::UnitConstants::e, and energy.
void RawTowerZDCv1::set_id (RawTowerZDCDefs::keytype id) inline override virtual
Reimplemented from RawTowerZDC.
Definition at line 25 of file RawTowerZDCv1.h.
View newest version in sPHENIX GitHub at line 25 of file RawTowerZDCv1.h
References towerid.
void RawTowerZDCv1::set_time (const float) inline override virtual
Time stamp assigned to the tower. Depending on the tower maker, it could be rise time or peak time.
Reimplemented from RawTowerZDC.
Definition at line 34 of file RawTowerZDCv1.h.
View newest version in sPHENIX GitHub at line 34 of file RawTowerZDCv1.h
References t, and time.
size_t RawTowerZDCv1::size_g4cells () const inline override virtual
Reimplemented from RawTowerZDC.
Definition at line 39 of file RawTowerZDCv1.h.
View newest version in sPHENIX GitHub at line 39 of file RawTowerZDCv1.h
References ecells.
size_t RawTowerZDCv1::size_g4showers () const inline override virtual
Reimplemented from RawTowerZDC.
Definition at line 53 of file RawTowerZDCv1.h.
View newest version in sPHENIX GitHub at line 53 of file RawTowerZDCv1.h
References eshowers.
Member Data Documentation
CellMap RawTowerZDCv1::ecells protected
Definition at line 73 of file RawTowerZDCv1.h.
View newest version in sPHENIX GitHub at line 73 of file RawTowerZDCv1.h
Referenced by add_ecell(), clear_g4cells(), empty_g4cells(), find_g4cell(), get_g4cells(), Reset(), and size_g4cells().
double RawTowerZDCv1::energy = 0. protected
energy assigned to the tower. Depending on stage of process and DST node name, it could be energy deposition, light yield or calibrated energies
Definition at line 68 of file RawTowerZDCv1.h.
View newest version in sPHENIX GitHub at line 68 of file RawTowerZDCv1.h
Referenced by get_energy(), Reset(), and set_energy().
ShowerMap RawTowerZDCv1::eshowers protected
Definition at line 74 of file RawTowerZDCv1.h.
View newest version in sPHENIX GitHub at line 74 of file RawTowerZDCv1.h
Referenced by add_eshower(), clear_g4showers(), empty_g4showers(), find_g4shower(), get_g4showers(), Reset(), and size_g4showers().
float RawTowerZDCv1::time = NAN protected
Time stamp assigned to the tower. Depending on the tower maker, it could be rise time or peak time.
Definition at line 71 of file RawTowerZDCv1.h.
View newest version in sPHENIX GitHub at line 71 of file RawTowerZDCv1.h
Referenced by get_time(), Reset(), and set_time().
RawTowerZDCDefs::keytype RawTowerZDCv1::towerid = ~0 protected
Definition at line 64 of file RawTowerZDCv1.h.
View newest version in sPHENIX GitHub at line 64 of file RawTowerZDCv1.h
Referenced by get_bineta(), get_binl(), get_binphi(), get_id(), and set_id().
The documentation for this class was generated from the following files:
fun4all_eicdetectors/blob/master/reconstruction/eiczdcbase/RawTowerZDCv1.h
fun4all_eicdetectors/blob/master/reconstruction/eiczdcbase/RawTowerZDCv1.cc