EIC Software: GroupMember Class Reference
GroupMember Class Reference
#include <EicRoot/blob/master/eic/htree/HoughNodeGroup.h>
Public Member Functions
GroupMember (const std::pair< void *, void * > &ptr, t_hough_range from, t_hough_range to)
t_hough_range From () const
t_hough_range To () const
bool IsBusy () const
bool IsBooked () const
void SetBusyFlag ()
void InsertMatchCandidate (MatchCandidate *match)
void EraseMatchCandidate (MatchCandidate *match)
std::set< MatchCandidate * >
::iterator Begin ()
std::set< MatchCandidate * >
::iterator End ()
Public Attributes
std::pair< void *, void * > mPtr
Private Attributes
std::set< MatchCandidate * > mMatchCandidates
bool mBusy
t_hough_range mFrom
t_hough_range mTo
Detailed Description
Definition at line 48 of file HoughNodeGroup.h.
View newest version in sPHENIX GitHub at line 48 of file HoughNodeGroup.h
Constructor & Destructor Documentation
GroupMember::GroupMember (const std::pair< void *, void * > & ptr, t_hough_range from, t_hough_range to) inline
Definition at line 50 of file HoughNodeGroup.h.
View newest version in sPHENIX GitHub at line 50 of file HoughNodeGroup.h
Member Function Documentation
std::set<MatchCandidate*>::iterator GroupMember::Begin () inline
Definition at line 73 of file HoughNodeGroup.h.
View newest version in sPHENIX GitHub at line 73 of file HoughNodeGroup.h
References mMatchCandidates.
Referenced by MatchCandidateGroup::AddCandidate(), and HoughTree::IsSubset().
std::set<MatchCandidate*>::iterator GroupMember::End () inline
Definition at line 74 of file HoughNodeGroup.h.
View newest version in sPHENIX GitHub at line 74 of file HoughNodeGroup.h
Referenced by MatchCandidateGroup::AddCandidate(), and HoughTree::IsSubset().
void GroupMember::EraseMatchCandidate (MatchCandidate * match) inline
Definition at line 70 of file HoughNodeGroup.h.
View newest version in sPHENIX GitHub at line 70 of file HoughNodeGroup.h
References mMatchCandidates.
Referenced by MatchCandidate::ResetMemberPtr().
t_hough_range GroupMember::From () const inline
Definition at line 55 of file HoughNodeGroup.h.
View newest version in sPHENIX GitHub at line 55 of file HoughNodeGroup.h
References mFrom.
Referenced by HoughTree::CheckCell().
void GroupMember::InsertMatchCandidate (MatchCandidate * match) inline
Definition at line 69 of file HoughNodeGroup.h.
View newest version in sPHENIX GitHub at line 69 of file HoughNodeGroup.h
References mMatchCandidates.
Referenced by MatchCandidate::ShapeItUpForInspection().
bool GroupMember::IsBooked () const inline
Definition at line 62 of file HoughNodeGroup.h.
View newest version in sPHENIX GitHub at line 62 of file HoughNodeGroup.h
References mMatchCandidates.
Referenced by FwdHoughTree::FinalFit(), and HoughTree::IsBusy().
bool GroupMember::IsBusy () const inline
Definition at line 61 of file HoughNodeGroup.h.
View newest version in sPHENIX GitHub at line 61 of file HoughNodeGroup.h
References mBusy.
Referenced by FwdHoughTree::FinalFit(), and HoughTree::IsBusy().
void GroupMember::SetBusyFlag () inline
Definition at line 63 of file HoughNodeGroup.h.
View newest version in sPHENIX GitHub at line 63 of file HoughNodeGroup.h
References mBusy.
Referenced by HoughTree::CheckCell().
t_hough_range GroupMember::To () const inline
Definition at line 56 of file HoughNodeGroup.h.
View newest version in sPHENIX GitHub at line 56 of file HoughNodeGroup.h
References mTo.
Referenced by HoughTree::CheckCell().
Member Data Documentation
bool GroupMember::mBusy private
Definition at line 89 of file HoughNodeGroup.h.
View newest version in sPHENIX GitHub at line 89 of file HoughNodeGroup.h
Referenced by IsBusy(), and SetBusyFlag().
t_hough_range GroupMember::mFrom private
Definition at line 93 of file HoughNodeGroup.h.
View newest version in sPHENIX GitHub at line 93 of file HoughNodeGroup.h
Referenced by From().
std::set<MatchCandidate*> GroupMember::mMatchCandidates private
Definition at line 74 of file HoughNodeGroup.h.
View newest version in sPHENIX GitHub at line 74 of file HoughNodeGroup.h
Referenced by Begin(), EraseMatchCandidate(), InsertMatchCandidate(), IsBooked(), and FwdHoughTree::SetupKalmanFilter().
std::pair<void *, void *> GroupMember::mPtr
Definition at line 63 of file HoughNodeGroup.h.
View newest version in sPHENIX GitHub at line 63 of file HoughNodeGroup.h
Referenced by FwdHoughTree::FinalFit(), FwdHoughTree::GetKfNode(), and FwdHoughTree::SetupKalmanFilter().
t_hough_range GroupMember::mTo private
Definition at line 93 of file HoughNodeGroup.h.
View newest version in sPHENIX GitHub at line 93 of file HoughNodeGroup.h
Referenced by To().
The documentation for this class was generated from the following file:
EicRoot/blob/master/eic/htree/HoughNodeGroup.h