EIC Software: PHTpcResiduals Class Reference
PHTpcResiduals Class Reference
#include <fun4all_coresoftware/blob/master/offline/packages/trackreco/PHTpcResiduals.h>
Public Member Functions
PHTpcResiduals (const std::string &name="PHTpcResiduals")
~PHTpcResiduals ()
int Init (PHCompositeNode *topNode)
int InitRun (PHCompositeNode *topNode)
int process_event (PHCompositeNode *topNode)
int End (PHCompositeNode *topNode)
Called at the end of all processing.
void setMaxTrackAlpha (float maxTAlpha)
Option for setting distortion correction calculation limits.
void setMaxTrackResidual (float maxResidual)
void setOutputRoot (bool outputRoot)
Public Member Functions inherited from SubsysReco
virtual ~SubsysReco ()
virtual int EndRun (const int)
Called at the end of each run.
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
virtual void Print (const std::string &what="ALL") const
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Private Member Functions
int getNodes (PHCompositeNode *topNode)
int createNodes (PHCompositeNode *topNode)
int processTracks (PHCompositeNode *topNode)
void processTrack (ActsTrack &track)
void calculateTpcResiduals (const Acts::BoundTrackParameters &params, const SourceLink &sl)
BoundTrackParamPtrResult propagateTrackState (const ActsExamples::TrackParameters &params, const SourceLink &sl)
int getCell (const int actsLayer, const Acts::Vector3D &loc)
Gets distortion cell for identifying bins in TPC.
int getCell (const int iz, const int ir, const int iphi)
void calculateDistortions (PHCompositeNode *topNode)
Calculates distortion matrices and updates pointer to node.
void makeHistograms ()
Private Attributes
std::map< unsigned int,
ActsTrack > * m_actsProtoTracks
ActsTrackingGeometry * m_tGeometry = nullptr
float m_maxTAlpha = 0.6
float m_maxResidual = 5 * Acts::UnitConstants::cm
const unsigned int m_nLayersTpc = 48
Tpc geometry.
const float m_zMin = -2120 / 2.
const float m_zMax = 2120 / 2.
const int m_zBins = 50
These are grid sizes given by the distortion model.
const int m_phiBins = 72
const int m_rBins = 48
const int m_totalBins = m_zBins * m_phiBins * m_rBins
const int m_nCoord = 3
Number of dimensions for the residuals below.
std::vector< Acts::SymMatrix3D > m_lhs
Vectors for collecting TPC residual information.
std::vector< Acts::Vector3D > m_rhs
std::vector< int > m_clusterCount
int m_event = 0
int m_nBadProps = 0
Counter for number of bad propagations from propagateTrackState()
DistortionCorrections * m_distortionCorrections = nullptr
Container for distortion corrections for node tree.
int m_outputRoot = false
Output root histograms.
TFile * outfile = nullptr
TH2 * h_rphiResid = nullptr
TH2 * h_zResid = nullptr
TH2 * h_etaResidLayer = nullptr
TH2 * h_zResidLayer = nullptr
TH2 * h_etaResid = nullptr
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = INT_MAX - 10
}
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Detailed Description
This class takes preliminary fits from PHActsTrkFitter to the silicon + MM clusters and calculates the residuals in the TPC from that track fit. The TPC state has to be explicitly determined here since the Acts::DirectNavigator does not visit the TPC states
Definition at line 56 of file PHTpcResiduals.h.
View newest version in sPHENIX GitHub at line 56 of file PHTpcResiduals.h
Constructor & Destructor Documentation
PHTpcResiduals::PHTpcResiduals (const std::string & name = "PHTpcResiduals")
Definition at line 41 of file PHTpcResiduals.cc.
View newest version in sPHENIX GitHub at line 41 of file PHTpcResiduals.cc
PHTpcResiduals::~PHTpcResiduals ()
Definition at line 46 of file PHTpcResiduals.cc.
View newest version in sPHENIX GitHub at line 46 of file PHTpcResiduals.cc
Member Function Documentation
void PHTpcResiduals::calculateDistortions (PHCompositeNode * topNode) private
Calculates distortion matrices and updates pointer to node.
Three dimensions for the matrices
Get TPC layers in sPHENIX, not Acts, coordinates, hence add 7 to the value
Cut on number of clusters to avoid low statistics bins
Insert correction of 0
Set the DistortionCorrections pointer to be put on the node tree
Create output tgraphs
Definition at line 344 of file PHTpcResiduals.cc.
View newest version in sPHENIX GitHub at line 344 of file PHTpcResiduals.cc
References analysis::delta, getCell(), ir(), m_clusterCount, m_distortionCorrections, DistortionCorrections::m_distortionMap, DistortionCorrections::m_distortionMapErr, m_lhs, DistortionCorrections::m_nCoord, m_nCoord, m_nLayersTpc, DistortionCorrections::m_phiBins, m_phiBins, DistortionCorrections::m_rBins, m_rBins, m_rhs, m_totalBins, DistortionCorrections::m_zBins, m_zBins, Fun4AllBase::Name(), PHWHERE, and r.
Referenced by End().
void PHTpcResiduals::calculateTpcResiduals (const Acts::BoundTrackParameters & params, const SourceLink & sl) private
Calculates TPC residuals given an Acts::Propagation result to a TPC surface
Get all the relevant information for residual calculation
Calculate residuals
Fill distortion matrices
Definition at line 249 of file PHTpcResiduals.cc.
View newest version in sPHENIX GitHub at line 249 of file PHTpcResiduals.cc
References kdfinder::abs(), Acts::UnitConstants::cm, cos(), dz, Acts::eBoundLoc0, Acts::eBoundLoc1, ActsTrackingGeometry::geoContext, getCell(), h_etaResid, h_etaResidLayer, h_rphiResid, h_zResid, h_zResidLayer, m_clusterCount, m_lhs, m_maxResidual, m_maxTAlpha, m_rhs, m_tGeometry, and m_totalBins.
Referenced by processTrack().
int PHTpcResiduals::createNodes (PHCompositeNode * topNode) private
Definition at line 476 of file PHTpcResiduals.cc.
View newest version in sPHENIX GitHub at line 476 of file PHTpcResiduals.cc
References PHCompositeNode::addNode(), Fun4AllReturnCodes::EVENT_OK, PHNodeIterator::findFirst(), and m_distortionCorrections.
Referenced by InitRun().
int PHTpcResiduals::End (PHCompositeNode *) virtual
Called at the end of all processing.
Reimplemented from SubsysReco.
Definition at line 91 of file PHTpcResiduals.cc.
View newest version in sPHENIX GitHub at line 91 of file PHTpcResiduals.cc
References calculateDistortions(), Fun4AllReturnCodes::EVENT_OK, h_etaResid, h_etaResidLayer, h_rphiResid, h_zResid, h_zResidLayer, m_nBadProps, m_outputRoot, outfile, and Fun4AllBase::Verbosity().
int PHTpcResiduals::getCell (const int actsLayer, const Acts::Vector3D & loc) private
Gets distortion cell for identifying bins in TPC.
Divide by two because ACTS definition is twice ours, subtract 1 to get layer number from 0-47 instead of 1-48
Definition at line 451 of file PHTpcResiduals.cc.
View newest version in sPHENIX GitHub at line 451 of file PHTpcResiduals.cc
References ir(), m_nLayersTpc, M_PI, m_rBins, m_zMax, and m_zMin.
Referenced by calculateDistortions(), and calculateTpcResiduals().
int PHTpcResiduals::getCell (const int iz, const int ir, const int iphi) private
Definition at line 467 of file PHTpcResiduals.cc.
View newest version in sPHENIX GitHub at line 467 of file PHTpcResiduals.cc
References m_rBins.
int PHTpcResiduals::getNodes (PHCompositeNode * topNode) private
Definition at line 516 of file PHTpcResiduals.cc.
View newest version in sPHENIX GitHub at line 516 of file PHTpcResiduals.cc
References Fun4AllReturnCodes::ABORTEVENT, Fun4AllReturnCodes::EVENT_OK, m_actsProtoTracks, and m_tGeometry.
Referenced by InitRun().
int PHTpcResiduals::Init (PHCompositeNode *) virtual
Called during initialization. Typically this is where you can book histograms, and e.g. register them to Fun4AllServer (so they can be output to file using Fun4AllServer::dumpHistos() method).
Reimplemented from SubsysReco.
Definition at line 49 of file PHTpcResiduals.cc.
View newest version in sPHENIX GitHub at line 49 of file PHTpcResiduals.cc
References Fun4AllReturnCodes::EVENT_OK, m_clusterCount, m_lhs, m_rhs, m_totalBins, and makeHistograms().
int PHTpcResiduals::InitRun (PHCompositeNode *) virtual
Called for first event when run number is known. Typically this is where you may want to fetch data from database, because you know the run number.
Reimplemented from SubsysReco.
Definition at line 63 of file PHTpcResiduals.cc.
View newest version in sPHENIX GitHub at line 63 of file PHTpcResiduals.cc
References Fun4AllReturnCodes::ABORTEVENT, createNodes(), Fun4AllReturnCodes::EVENT_OK, and getNodes().
void PHTpcResiduals::makeHistograms () private
Definition at line 540 of file PHTpcResiduals.cc.
View newest version in sPHENIX GitHub at line 540 of file PHTpcResiduals.cc
References h_etaResid, h_etaResidLayer, h_rphiResid, h_zResid, h_zResidLayer, m_outputRoot, Fun4AllBase::Name(), and outfile.
Referenced by Init().
int PHTpcResiduals::process_event (PHCompositeNode *) virtual
Called for each event. This is where you do the real work.
Reimplemented from SubsysReco.
Definition at line 74 of file PHTpcResiduals.cc.
View newest version in sPHENIX GitHub at line 74 of file PHTpcResiduals.cc
References m_event, processTracks(), and Fun4AllBase::Verbosity().
void PHTpcResiduals::processTrack (ActsTrack & track) private
Check that there are silicon+MM sourcelinks in this particular track
Only analyze TPC
Definition at line 131 of file PHTpcResiduals.cc.
View newest version in sPHENIX GitHub at line 131 of file PHTpcResiduals.cc
References calculateTpcResiduals(), ActsTrackingGeometry::geoContext, ActsTrack::getSourceLinks(), ActsTrack::getTrackParams(), m_nBadProps, m_tGeometry, propagateTrackState(), Fun4AllBase::Verbosity(), and Acts::Test::volume.
Referenced by processTracks().
int PHTpcResiduals::processTracks (PHCompositeNode * topNode) private
Definition at line 114 of file PHTpcResiduals.cc.
View newest version in sPHENIX GitHub at line 114 of file PHTpcResiduals.cc
References Fun4AllReturnCodes::EVENT_OK, m_actsProtoTracks, and processTrack().
Referenced by process_event().
BoundTrackParamPtrResult PHTpcResiduals::propagateTrackState (const ActsExamples::TrackParameters & params, const SourceLink & sl) private
Propagates the silicon+MM track fit to the surface on which an available source link in the TPC exists, added from the stub matching propagation
Definition at line 205 of file PHTpcResiduals.cc.
View newest version in sPHENIX GitHub at line 205 of file PHTpcResiduals.cc
References Acts::Logging::FATAL, ActsTrackingGeometry::geoContext, Acts::getDefaultLogger(), m_tGeometry, ActsTrackingGeometry::magFieldContext, eicpy.build::options, propagation_timing::stepper, Acts::Logging::VERBOSE, and Fun4AllBase::Verbosity().
Referenced by processTrack().
void PHTpcResiduals::setMaxTrackAlpha (float maxTAlpha) inline
Option for setting distortion correction calculation limits.
Definition at line 70 of file PHTpcResiduals.h.
View newest version in sPHENIX GitHub at line 70 of file PHTpcResiduals.h
References m_maxTAlpha.
void PHTpcResiduals::setMaxTrackResidual (float maxResidual) inline
Definition at line 71 of file PHTpcResiduals.h.
View newest version in sPHENIX GitHub at line 71 of file PHTpcResiduals.h
References m_maxResidual.
void PHTpcResiduals::setOutputRoot (bool outputRoot) inline
Option for outputting some basic cluster-track distortion histograms
Definition at line 76 of file PHTpcResiduals.h.
View newest version in sPHENIX GitHub at line 76 of file PHTpcResiduals.h
References m_outputRoot.
Member Data Documentation
TH2* PHTpcResiduals::h_etaResid = nullptr private
Definition at line 149 of file PHTpcResiduals.h.
View newest version in sPHENIX GitHub at line 149 of file PHTpcResiduals.h
Referenced by calculateTpcResiduals(), End(), and makeHistograms().
TH2* PHTpcResiduals::h_etaResidLayer = nullptr private
Definition at line 147 of file PHTpcResiduals.h.
View newest version in sPHENIX GitHub at line 147 of file PHTpcResiduals.h
Referenced by calculateTpcResiduals(), End(), and makeHistograms().
TH2* PHTpcResiduals::h_rphiResid = nullptr private
Definition at line 145 of file PHTpcResiduals.h.
View newest version in sPHENIX GitHub at line 145 of file PHTpcResiduals.h
Referenced by calculateTpcResiduals(), End(), and makeHistograms().
TH2* PHTpcResiduals::h_zResid = nullptr private
Definition at line 146 of file PHTpcResiduals.h.
View newest version in sPHENIX GitHub at line 146 of file PHTpcResiduals.h
Referenced by calculateTpcResiduals(), End(), and makeHistograms().
TH2* PHTpcResiduals::h_zResidLayer = nullptr private
Definition at line 148 of file PHTpcResiduals.h.
View newest version in sPHENIX GitHub at line 148 of file PHTpcResiduals.h
Referenced by calculateTpcResiduals(), End(), and makeHistograms().
std::map<unsigned int, ActsTrack>* PHTpcResiduals::m_actsProtoTracks private
Node information for Acts tracking geometry and silicon+MM track fit
Definition at line 109 of file PHTpcResiduals.h.
View newest version in sPHENIX GitHub at line 109 of file PHTpcResiduals.h
Referenced by getNodes(), and processTracks().
std::vector<int> PHTpcResiduals::m_clusterCount private
Definition at line 132 of file PHTpcResiduals.h.
View newest version in sPHENIX GitHub at line 132 of file PHTpcResiduals.h
Referenced by calculateDistortions(), calculateTpcResiduals(), and Init().
DistortionCorrections* PHTpcResiduals::m_distortionCorrections = nullptr private
Container for distortion corrections for node tree.
Definition at line 140 of file PHTpcResiduals.h.
View newest version in sPHENIX GitHub at line 140 of file PHTpcResiduals.h
Referenced by calculateDistortions(), and createNodes().
int PHTpcResiduals::m_event = 0 private
Definition at line 134 of file PHTpcResiduals.h.
View newest version in sPHENIX GitHub at line 134 of file PHTpcResiduals.h
Referenced by process_event().
std::vector<Acts::SymMatrix3D> PHTpcResiduals::m_lhs private
Vectors for collecting TPC residual information.
Definition at line 130 of file PHTpcResiduals.h.
View newest version in sPHENIX GitHub at line 130 of file PHTpcResiduals.h
Referenced by calculateDistortions(), calculateTpcResiduals(), and Init().
float PHTpcResiduals::m_maxResidual = 5 * Acts::UnitConstants::cm private
Definition at line 113 of file PHTpcResiduals.h.
View newest version in sPHENIX GitHub at line 113 of file PHTpcResiduals.h
Referenced by calculateTpcResiduals(), and setMaxTrackResidual().
float PHTpcResiduals::m_maxTAlpha = 0.6 private
Definition at line 112 of file PHTpcResiduals.h.
View newest version in sPHENIX GitHub at line 112 of file PHTpcResiduals.h
Referenced by calculateTpcResiduals(), and setMaxTrackAlpha().
int PHTpcResiduals::m_nBadProps = 0 private
Counter for number of bad propagations from propagateTrackState()
Definition at line 137 of file PHTpcResiduals.h.
View newest version in sPHENIX GitHub at line 137 of file PHTpcResiduals.h
Referenced by End(), and processTrack().
const int PHTpcResiduals::m_nCoord = 3 private
Number of dimensions for the residuals below.
Definition at line 127 of file PHTpcResiduals.h.
View newest version in sPHENIX GitHub at line 127 of file PHTpcResiduals.h
Referenced by calculateDistortions().
const unsigned int PHTpcResiduals::m_nLayersTpc = 48 private
Tpc geometry.
Definition at line 116 of file PHTpcResiduals.h.
View newest version in sPHENIX GitHub at line 116 of file PHTpcResiduals.h
Referenced by calculateDistortions(), and getCell().
int PHTpcResiduals::m_outputRoot = false private
Output root histograms.
Definition at line 143 of file PHTpcResiduals.h.
View newest version in sPHENIX GitHub at line 143 of file PHTpcResiduals.h
Referenced by End(), makeHistograms(), and setOutputRoot().
const int PHTpcResiduals::m_phiBins = 72 private
Definition at line 122 of file PHTpcResiduals.h.
View newest version in sPHENIX GitHub at line 122 of file PHTpcResiduals.h
Referenced by calculateDistortions().
const int PHTpcResiduals::m_rBins = 48 private
Definition at line 123 of file PHTpcResiduals.h.
View newest version in sPHENIX GitHub at line 123 of file PHTpcResiduals.h
Referenced by calculateDistortions(), and getCell().
std::vector<Acts::Vector3D> PHTpcResiduals::m_rhs private
Definition at line 131 of file PHTpcResiduals.h.
View newest version in sPHENIX GitHub at line 131 of file PHTpcResiduals.h
Referenced by calculateDistortions(), calculateTpcResiduals(), and Init().
ActsTrackingGeometry* PHTpcResiduals::m_tGeometry = nullptr private
Definition at line 110 of file PHTpcResiduals.h.
View newest version in sPHENIX GitHub at line 110 of file PHTpcResiduals.h
Referenced by calculateTpcResiduals(), getNodes(), processTrack(), and propagateTrackState().
const int PHTpcResiduals::m_totalBins = m_zBins * m_phiBins * m_rBins private
Definition at line 124 of file PHTpcResiduals.h.
View newest version in sPHENIX GitHub at line 124 of file PHTpcResiduals.h
Referenced by calculateDistortions(), calculateTpcResiduals(), and Init().
const int PHTpcResiduals::m_zBins = 50 private
These are grid sizes given by the distortion model.
Definition at line 121 of file PHTpcResiduals.h.
View newest version in sPHENIX GitHub at line 121 of file PHTpcResiduals.h
Referenced by calculateDistortions().
const float PHTpcResiduals::m_zMax = 2120 / 2. private
Definition at line 118 of file PHTpcResiduals.h.
View newest version in sPHENIX GitHub at line 118 of file PHTpcResiduals.h
Referenced by getCell().
const float PHTpcResiduals::m_zMin = -2120 / 2. private
Definition at line 117 of file PHTpcResiduals.h.
View newest version in sPHENIX GitHub at line 117 of file PHTpcResiduals.h
Referenced by getCell().
TFile* PHTpcResiduals::outfile = nullptr private
Definition at line 144 of file PHTpcResiduals.h.
View newest version in sPHENIX GitHub at line 144 of file PHTpcResiduals.h
Referenced by End(), and makeHistograms().
The documentation for this class was generated from the following files:
fun4all_coresoftware/blob/master/offline/packages/trackreco/PHTpcResiduals.h
fun4all_coresoftware/blob/master/offline/packages/trackreco/PHTpcResiduals.cc