EIC Software: KalmanNode Class Reference
KalmanNode Class Reference
#include <EicRoot/blob/master/eic/htc/KalmanNode.h>
Public Member Functions
KalmanNode ()
void SetFiredFlag ()
void ResetFiredFlag ()
virtual bool IsActive () const
bool IsFired () const
void SetZ (double z)
virtual double GetZ () const
unsigned GetMdim () const
double GetV (unsigned ip, unsigned iq) const
double GetX0 (unsigned ip) const
double GetXf (unsigned ip) const
double GetXs (unsigned ip) const
double GetXm (unsigned ip) const
double GetRs (unsigned ip) const
double GetRm (unsigned ip) const
double Getm (unsigned ip) const
double GetSmootherChiSquare () const
double GetSmootherChiSquareCCDF () const
double GetCP (unsigned ip, unsigned iq) const
double GetCF (unsigned ip, unsigned iq) const
double GetCS (unsigned ip, unsigned iq) const
double GetRS (unsigned ip, unsigned iq) const
double GetRM (unsigned ip, unsigned iq) const
KfVector * GetX0 () const
KfVector * GetXf () const
KfVector * GetXp () const
KfVector * GetXs () const
KfMatrix * GetCP () const
KfMatrix * GetCS () const
const char * GetName () const
KalmanNode * GetNext (unsigned fb) const
KalmanNode * GetPrev (unsigned fb) const
void SetPrev (KalmanNode *node)
void SetNext (KalmanNode *node)
void CopyOverGroupInfo (KalmanNode *sample)
Protected Attributes
double mZ
int mDim
KfMatrix * FF [2]
KfVector * m
KfMatrix * V
KfMatrix * H
KfVector * x0
KfMatrix * Q
KfMatrix * FM
KfMatrix * FR
KfMatrix * MMTX
KfVector * MVEC
KfVector * xp
KfVector * xf
KfVector * xm
KfVector * rm
KfMatrix * CP
KfMatrix * CF
KfMatrix * K
KfVector * xs
KfVector * qq
KfVector * ep
KfVector * rf
KfMatrix * RPI
KfMatrix * RF
KfMatrix * CS
KfVector * rs
KfMatrix * RS
KfMatrix * CM
KfMatrix * RM
KfMatrix * LB
KfMatrix * L
KfMatrix * QQ
Private Member Functions
void AllocateKfMatrices (unsigned sdim)
Private Attributes
char * mName
KalmanNode * mPrev
KalmanNode * mNext
bool mNonLinearTransportFlags [2]
int mNodeGroupNum
NodeGroup ** mNodeGroups
bool mFired
double mFilterChiSquareIncrement
double mSmootherChiSquare
double mSmootherChiSquareCCDF
Friends
class KalmanFilter
Detailed Description
Definition at line 96 of file KalmanNode.h.
View newest version in sPHENIX GitHub at line 96 of file KalmanNode.h
Constructor & Destructor Documentation
KalmanNode::KalmanNode () inline
Definition at line 101 of file KalmanNode.h.
View newest version in sPHENIX GitHub at line 101 of file KalmanNode.h
Member Function Documentation
void KalmanNode::AllocateKfMatrices (unsigned sdim) private
Definition at line 19 of file KalmanNode.cxx.
View newest version in sPHENIX GitHub at line 19 of file KalmanNode.cxx
References CF, CM, CP, CS, ep, FF, FM, H, K, L, LB, m, mDim, MMTX, MVEC, Q, qq, QQ, rf, RF, rm, RM, RPI, rs, RS, KfMatrix::Unity(), V, x0, xf, xm, xp, and xs.
Referenced by KalmanFilter::AddNode().
void KalmanNode::CopyOverGroupInfo (KalmanNode * sample) inline
Definition at line 146 of file KalmanNode.h.
View newest version in sPHENIX GitHub at line 146 of file KalmanNode.h
References mNodeGroupNum, and mNodeGroups.
double KalmanNode::GetCF (unsigned ip, unsigned iq) const inline
Definition at line 126 of file KalmanNode.h.
View newest version in sPHENIX GitHub at line 126 of file KalmanNode.h
References CF, and KfMatrix::KFM().
double KalmanNode::GetCP (unsigned ip, unsigned iq) const inline
Definition at line 125 of file KalmanNode.h.
View newest version in sPHENIX GitHub at line 125 of file KalmanNode.h
References CP, and KfMatrix::KFM().
Referenced by FwdTrackFinder::ResetVtxNode(), and FwdTrackFinder::UpdateVtxNode().
KfMatrix* KalmanNode::GetCP () const inline
Definition at line 135 of file KalmanNode.h.
View newest version in sPHENIX GitHub at line 135 of file KalmanNode.h
References CP.
double KalmanNode::GetCS (unsigned ip, unsigned iq) const inline
Definition at line 127 of file KalmanNode.h.
View newest version in sPHENIX GitHub at line 127 of file KalmanNode.h
References CS, and KfMatrix::KFM().
Referenced by EicHtcTask::Exec(), FwdHoughTree::FinalFit(), and FwdTrackFinder::UpdateVtxNode().
KfMatrix* KalmanNode::GetCS () const inline
Definition at line 136 of file KalmanNode.h.
View newest version in sPHENIX GitHub at line 136 of file KalmanNode.h
References CS.
double KalmanNode::Getm (unsigned ip) const inline
Definition at line 122 of file KalmanNode.h.
View newest version in sPHENIX GitHub at line 122 of file KalmanNode.h
References KfMatrix::KFV(), and m.
unsigned KalmanNode::GetMdim () const inline
Definition at line 112 of file KalmanNode.h.
View newest version in sPHENIX GitHub at line 112 of file KalmanNode.h
References mDim.
Referenced by KalmanNodeWrapper::AllocateNewKfNode(), EicHtcTask::Exec(), FwdHoughTree::FinalFit(), and SensitiveVolume::TrackToHitDistance().
const char* KalmanNode::GetName () const inline
Definition at line 138 of file KalmanNode.h.
View newest version in sPHENIX GitHub at line 138 of file KalmanNode.h
References mName.
Referenced by FwdHoughTree::AddNodeGroup(), KalmanNodeWrapper::AllocateNewKfNode(), and EicHtcTask::Exec().
KalmanNode* KalmanNode::GetNext (unsigned fb) const inline
Definition at line 140 of file KalmanNode.h.
View newest version in sPHENIX GitHub at line 140 of file KalmanNode.h
References mNext, and mPrev.
Referenced by KalmanFilter::Calculate_x0_FR_Q(), KalmanFilter::CalculateFilterStat(), KalmanFilter::Configure(), KalmanFilter::DoFilterAlgebra(), TrKalmanNode::GetNext(), and KalmanFilter::SmootherPass().
KalmanNode* KalmanNode::GetPrev (unsigned fb) const inline
Definition at line 141 of file KalmanNode.h.
View newest version in sPHENIX GitHub at line 141 of file KalmanNode.h
References mNext, and mPrev.
Referenced by KalmanFilter::Calculate_x0_FR_Q(), KalmanFilter::DoFilterAlgebra(), TrKalmanNode::GetPrev(), and KalmanFilter::SmootherPass().
double KalmanNode::GetRm (unsigned ip) const inline
Definition at line 121 of file KalmanNode.h.
View newest version in sPHENIX GitHub at line 121 of file KalmanNode.h
References KfMatrix::KFV(), and rm.
Referenced by EicHtcTask::Exec().
double KalmanNode::GetRM (unsigned ip, unsigned iq) const inline
Definition at line 129 of file KalmanNode.h.
View newest version in sPHENIX GitHub at line 129 of file KalmanNode.h
References KfMatrix::KFM(), and RM.
Referenced by EicHtcTask::Exec().
double KalmanNode::GetRs (unsigned ip) const inline
Definition at line 120 of file KalmanNode.h.
View newest version in sPHENIX GitHub at line 120 of file KalmanNode.h
References KfMatrix::KFV(), and rs.
Referenced by EicHtcTask::Exec().
double KalmanNode::GetRS (unsigned ip, unsigned iq) const inline
Definition at line 128 of file KalmanNode.h.
View newest version in sPHENIX GitHub at line 128 of file KalmanNode.h
References KfMatrix::KFM(), and RS.
Referenced by EicHtcTask::Exec().
double KalmanNode::GetSmootherChiSquare () const inline
Definition at line 123 of file KalmanNode.h.
View newest version in sPHENIX GitHub at line 123 of file KalmanNode.h
References mSmootherChiSquare.
Referenced by EicHtcTask::Exec(), and FwdHoughTree::FinalFit().
double KalmanNode::GetSmootherChiSquareCCDF () const inline
Definition at line 124 of file KalmanNode.h.
View newest version in sPHENIX GitHub at line 124 of file KalmanNode.h
References mSmootherChiSquareCCDF.
Referenced by FwdHoughTree::ResolveAmbiguitiesNg().
double KalmanNode::GetV (unsigned ip, unsigned iq) const inline
Definition at line 115 of file KalmanNode.h.
View newest version in sPHENIX GitHub at line 115 of file KalmanNode.h
References KfMatrix::KFM(), and V.
Referenced by EicHtcTask::Exec().
double KalmanNode::GetX0 (unsigned ip) const inline
Definition at line 116 of file KalmanNode.h.
View newest version in sPHENIX GitHub at line 116 of file KalmanNode.h
References KfMatrix::KFV(), and x0.
Referenced by TrKalmanFilter::CalculateProcessNoise(), EicHtcTask::Exec(), FwdHoughTree::FinalFit(), EicHtcTask::GetFairTrackParP(), FwdTrackFinder::ResetVtxNode(), and FwdTrackFinder::UpdateVtxNode().
KfVector* KalmanNode::GetX0 () const inline
Definition at line 131 of file KalmanNode.h.
View newest version in sPHENIX GitHub at line 131 of file KalmanNode.h
References x0.
Referenced by TrKalmanNode::PerformRungeKuttaStep().
double KalmanNode::GetXf (unsigned ip) const inline
Definition at line 117 of file KalmanNode.h.
View newest version in sPHENIX GitHub at line 117 of file KalmanNode.h
References KfMatrix::KFV(), and xf.
KfVector* KalmanNode::GetXf () const inline
Definition at line 132 of file KalmanNode.h.
View newest version in sPHENIX GitHub at line 132 of file KalmanNode.h
References xf.
double KalmanNode::GetXm (unsigned ip) const inline
Definition at line 119 of file KalmanNode.h.
View newest version in sPHENIX GitHub at line 119 of file KalmanNode.h
References KfMatrix::KFV(), and xm.
KfVector* KalmanNode::GetXp () const inline
Definition at line 133 of file KalmanNode.h.
View newest version in sPHENIX GitHub at line 133 of file KalmanNode.h
References xp.
Referenced by FwdTrackFinder::ResetVtxNode(), and FwdTrackFinder::UpdateVtxNode().
double KalmanNode::GetXs (unsigned ip) const inline
Definition at line 118 of file KalmanNode.h.
View newest version in sPHENIX GitHub at line 118 of file KalmanNode.h
References KfMatrix::KFV(), and xs.
Referenced by EicHtcTask::Exec(), FwdHoughTree::FinalFit(), EicHtcTask::GetFairTrackParP(), and FwdTrackFinder::UpdateVtxNode().
KfVector* KalmanNode::GetXs () const inline
Definition at line 134 of file KalmanNode.h.
View newest version in sPHENIX GitHub at line 134 of file KalmanNode.h
References xs.
virtual double KalmanNode::GetZ () const inline virtual
Reimplemented in TrKalmanNode.
Definition at line 111 of file KalmanNode.h.
View newest version in sPHENIX GitHub at line 111 of file KalmanNode.h
References mZ.
Referenced by KalmanFilter::Calculate_x0_FR_Q(), TrKalmanFilter::CalculateProcessNoise(), and TrKalmanNode::PerformRungeKuttaStep().
virtual bool KalmanNode::IsActive () const inline virtual
Reimplemented in TrKalmanNode.
Definition at line 108 of file KalmanNode.h.
View newest version in sPHENIX GitHub at line 108 of file KalmanNode.h
Referenced by KalmanFilter::BuildNodeList().
bool KalmanNode::IsFired () const inline
Definition at line 109 of file KalmanNode.h.
View newest version in sPHENIX GitHub at line 109 of file KalmanNode.h
References mFired.
Referenced by EicHtcTask::Exec(), FwdHoughTree::FinalFit(), TrKalmanNodeLocation::GetFiredNodeCount(), TrKalmanFilter::SelectActiveNodes(), and FwdHoughTree::SetupKalmanFilter().
void KalmanNode::ResetFiredFlag ()
Definition at line 104 of file KalmanNode.cxx.
View newest version in sPHENIX GitHub at line 104 of file KalmanNode.cxx
References mFired, NodeGroup::mFiredNodeNum, mNodeGroupNum, and mNodeGroups.
Referenced by KalmanFilter::FullChain().
void KalmanNode::SetFiredFlag ()
Definition at line 89 of file KalmanNode.cxx.
View newest version in sPHENIX GitHub at line 89 of file KalmanNode.cxx
References mFired, NodeGroup::mFiredNodeNum, mNodeGroupNum, and mNodeGroups.
Referenced by EicHtcTask::Exec(), and FwdHoughTree::SetupKalmanFilter().
void KalmanNode::SetNext (KalmanNode * node) inline
Definition at line 144 of file KalmanNode.h.
View newest version in sPHENIX GitHub at line 144 of file KalmanNode.h
References mNext.
Referenced by KalmanFilter::BuildNodeList().
void KalmanNode::SetPrev (KalmanNode * node) inline
Definition at line 143 of file KalmanNode.h.
View newest version in sPHENIX GitHub at line 143 of file KalmanNode.h
References mPrev.
Referenced by KalmanFilter::BuildNodeList().
void KalmanNode::SetZ (double z) inline
Definition at line 110 of file KalmanNode.h.
View newest version in sPHENIX GitHub at line 110 of file KalmanNode.h
References mZ, and z.
Referenced by KalmanFilter::AddNode().
Friends And Related Function Documentation
friend class KalmanFilter friend
Definition at line 97 of file KalmanNode.h.
View newest version in sPHENIX GitHub at line 97 of file KalmanNode.h
Member Data Documentation
KfMatrix* KalmanNode::CF protected
Definition at line 214 of file KalmanNode.h.
View newest version in sPHENIX GitHub at line 214 of file KalmanNode.h
Referenced by AllocateKfMatrices(), KalmanFilter::DoFilterAlgebra(), and GetCF().
KfMatrix* KalmanNode::CM protected
Definition at line 235 of file KalmanNode.h.
View newest version in sPHENIX GitHub at line 235 of file KalmanNode.h
Referenced by AllocateKfMatrices().
KfMatrix* KalmanNode::CP protected
Definition at line 212 of file KalmanNode.h.
View newest version in sPHENIX GitHub at line 212 of file KalmanNode.h
Referenced by AllocateKfMatrices(), GetCP(), and TrKalmanFilter::ResetNode().
KfMatrix* KalmanNode::CS protected
Definition at line 229 of file KalmanNode.h.
View newest version in sPHENIX GitHub at line 229 of file KalmanNode.h
Referenced by AllocateKfMatrices(), and GetCS().
KfVector* KalmanNode::ep protected
Definition at line 225 of file KalmanNode.h.
View newest version in sPHENIX GitHub at line 225 of file KalmanNode.h
Referenced by AllocateKfMatrices().
KfMatrix* KalmanNode::FF[2] protected
Definition at line 172 of file KalmanNode.h.
View newest version in sPHENIX GitHub at line 172 of file KalmanNode.h
Referenced by AllocateKfMatrices(), KalmanFilter::Calculate_x0_FR_Q(), and TrKalmanFilter::CalculateMagnetOffTransportMatrices().
KfMatrix* KalmanNode::FM protected
Definition at line 191 of file KalmanNode.h.
View newest version in sPHENIX GitHub at line 191 of file KalmanNode.h
Referenced by AllocateKfMatrices(), KalmanFilter::Calculate_x0_FR_Q(), and TrKalmanFilter::Transport().
KfMatrix* KalmanNode::FR protected
Definition at line 192 of file KalmanNode.h.
View newest version in sPHENIX GitHub at line 192 of file KalmanNode.h
Referenced by KalmanFilter::Calculate_x0_FR_Q(), and KalmanFilter::DoFilterAlgebra().
KfMatrix* KalmanNode::H protected
Definition at line 181 of file KalmanNode.h.
View newest version in sPHENIX GitHub at line 181 of file KalmanNode.h
Referenced by AllocateKfMatrices(), and TrKalmanFilter::CalculateHMatrix().
KfMatrix* KalmanNode::K protected
Definition at line 217 of file KalmanNode.h.
View newest version in sPHENIX GitHub at line 217 of file KalmanNode.h
Referenced by AllocateKfMatrices().
KfMatrix * KalmanNode::L protected
Definition at line 242 of file KalmanNode.h.
View newest version in sPHENIX GitHub at line 242 of file KalmanNode.h
Referenced by AllocateKfMatrices(), and KalmanFilter::SmootherPass().
KfMatrix* KalmanNode::LB protected
Definition at line 242 of file KalmanNode.h.
View newest version in sPHENIX GitHub at line 242 of file KalmanNode.h
Referenced by AllocateKfMatrices().
KfVector* KalmanNode::m protected
Definition at line 175 of file KalmanNode.h.
View newest version in sPHENIX GitHub at line 175 of file KalmanNode.h
Referenced by AllocateKfMatrices(), TrKalmanFilter::CalculateHMatrix(), and Getm().
int KalmanNode::mDim protected
Definition at line 158 of file KalmanNode.h.
View newest version in sPHENIX GitHub at line 158 of file KalmanNode.h
Referenced by KalmanFilter::AddNode(), AllocateKfMatrices(), TrKalmanFilter::CalculateHMatrix(), KalmanFilter::FullChain(), GetMdim(), and TrKalmanNode::InflateMeasurementNoise().
double KalmanNode::mFilterChiSquareIncrement private
Definition at line 268 of file KalmanNode.h.
View newest version in sPHENIX GitHub at line 268 of file KalmanNode.h
bool KalmanNode::mFired private
Definition at line 265 of file KalmanNode.h.
View newest version in sPHENIX GitHub at line 265 of file KalmanNode.h
Referenced by IsFired(), ResetFiredFlag(), and SetFiredFlag().
KfMatrix* KalmanNode::MMTX protected
Definition at line 195 of file KalmanNode.h.
View newest version in sPHENIX GitHub at line 195 of file KalmanNode.h
Referenced by AllocateKfMatrices().
char* KalmanNode::mName private
Definition at line 247 of file KalmanNode.h.
View newest version in sPHENIX GitHub at line 247 of file KalmanNode.h
Referenced by KalmanFilter::AddNode(), KalmanFilter::FullChain(), and GetName().
KalmanNode * KalmanNode::mNext private
Definition at line 250 of file KalmanNode.h.
View newest version in sPHENIX GitHub at line 250 of file KalmanNode.h
Referenced by GetNext(), GetPrev(), and SetNext().
int KalmanNode::mNodeGroupNum private
Definition at line 261 of file KalmanNode.h.
View newest version in sPHENIX GitHub at line 261 of file KalmanNode.h
Referenced by KalmanFilter::Configure(), CopyOverGroupInfo(), ResetFiredFlag(), and SetFiredFlag().
NodeGroup** KalmanNode::mNodeGroups private
Definition at line 262 of file KalmanNode.h.
View newest version in sPHENIX GitHub at line 262 of file KalmanNode.h
Referenced by CopyOverGroupInfo(), ResetFiredFlag(), and SetFiredFlag().
bool KalmanNode::mNonLinearTransportFlags[2] private
Definition at line 258 of file KalmanNode.h.
View newest version in sPHENIX GitHub at line 258 of file KalmanNode.h
Referenced by KalmanFilter::AddNode(), and KalmanFilter::Calculate_x0_FR_Q().
KalmanNode* KalmanNode::mPrev private
Definition at line 250 of file KalmanNode.h.
View newest version in sPHENIX GitHub at line 250 of file KalmanNode.h
Referenced by GetNext(), GetPrev(), and SetPrev().
double KalmanNode::mSmootherChiSquare private
Definition at line 271 of file KalmanNode.h.
View newest version in sPHENIX GitHub at line 271 of file KalmanNode.h
Referenced by KalmanFilter::FullChain(), GetSmootherChiSquare(), and KalmanFilter::SmootherPass().
double KalmanNode::mSmootherChiSquareCCDF private
Definition at line 271 of file KalmanNode.h.
View newest version in sPHENIX GitHub at line 271 of file KalmanNode.h
Referenced by GetSmootherChiSquareCCDF().
KfVector* KalmanNode::MVEC protected
Definition at line 196 of file KalmanNode.h.
View newest version in sPHENIX GitHub at line 196 of file KalmanNode.h
Referenced by AllocateKfMatrices().
double KalmanNode::mZ protected
Definition at line 150 of file KalmanNode.h.
View newest version in sPHENIX GitHub at line 150 of file KalmanNode.h
Referenced by TrKalmanNode::GetZ(), GetZ(), and SetZ().
KfMatrix* KalmanNode::Q protected
Definition at line 188 of file KalmanNode.h.
View newest version in sPHENIX GitHub at line 188 of file KalmanNode.h
Referenced by AllocateKfMatrices(), TrKalmanFilter::CalculateProcessNoise(), and KalmanFilter::DoFilterAlgebra().
KfVector* KalmanNode::qq protected
Definition at line 222 of file KalmanNode.h.
View newest version in sPHENIX GitHub at line 222 of file KalmanNode.h
Referenced by AllocateKfMatrices(), and KalmanFilter::SmootherPass().
KfMatrix* KalmanNode::QQ protected
Definition at line 243 of file KalmanNode.h.
View newest version in sPHENIX GitHub at line 243 of file KalmanNode.h
Referenced by AllocateKfMatrices(), and KalmanFilter::SmootherPass().
KfVector * KalmanNode::rf protected
Definition at line 225 of file KalmanNode.h.
View newest version in sPHENIX GitHub at line 225 of file KalmanNode.h
Referenced by AllocateKfMatrices().
KfMatrix * KalmanNode::RF protected
Definition at line 226 of file KalmanNode.h.
View newest version in sPHENIX GitHub at line 226 of file KalmanNode.h
Referenced by AllocateKfMatrices().
KfVector* KalmanNode::rm protected
Definition at line 209 of file KalmanNode.h.
View newest version in sPHENIX GitHub at line 209 of file KalmanNode.h
Referenced by AllocateKfMatrices(), and GetRm().
KfMatrix* KalmanNode::RM protected
Definition at line 237 of file KalmanNode.h.
View newest version in sPHENIX GitHub at line 237 of file KalmanNode.h
Referenced by AllocateKfMatrices(), and GetRM().
KfMatrix* KalmanNode::RPI protected
Definition at line 226 of file KalmanNode.h.
View newest version in sPHENIX GitHub at line 226 of file KalmanNode.h
Referenced by AllocateKfMatrices().
KfVector* KalmanNode::rs protected
Definition at line 231 of file KalmanNode.h.
View newest version in sPHENIX GitHub at line 231 of file KalmanNode.h
Referenced by AllocateKfMatrices(), and GetRs().
KfMatrix* KalmanNode::RS protected
Definition at line 232 of file KalmanNode.h.
View newest version in sPHENIX GitHub at line 232 of file KalmanNode.h
Referenced by AllocateKfMatrices(), and GetRS().
KfMatrix* KalmanNode::V protected
Definition at line 178 of file KalmanNode.h.
View newest version in sPHENIX GitHub at line 178 of file KalmanNode.h
Referenced by AllocateKfMatrices(), GetV(), TrKalmanNode::InflateMeasurementNoise(), and TrKalmanNode::SetMeasurementNoise().
KfVector* KalmanNode::x0 protected
Definition at line 185 of file KalmanNode.h.
View newest version in sPHENIX GitHub at line 185 of file KalmanNode.h
Referenced by TrKalmanFilter::AccountIonizationLosses(), AllocateKfMatrices(), KalmanFilter::Calculate_x0_FR_Q(), TrKalmanFilter::CalculateHMatrix(), TrKalmanFilter::CalculateProcessNoise(), GetX0(), TrKalmanNode::PerformRungeKuttaStep(), TrKalmanFilter::ResetNode(), and TrKalmanFilter::Transport().
KfVector* KalmanNode::xf protected
Definition at line 204 of file KalmanNode.h.
View newest version in sPHENIX GitHub at line 204 of file KalmanNode.h
Referenced by AllocateKfMatrices(), KalmanFilter::DoFilterAlgebra(), GetXf(), eicpy.qaplots.TrackHists::output(), and TrKalmanFilter::ResetNode().
KfVector* KalmanNode::xm protected
Definition at line 207 of file KalmanNode.h.
View newest version in sPHENIX GitHub at line 207 of file KalmanNode.h
Referenced by AllocateKfMatrices(), and GetXm().
KfVector* KalmanNode::xp protected
Definition at line 200 of file KalmanNode.h.
View newest version in sPHENIX GitHub at line 200 of file KalmanNode.h
Referenced by AllocateKfMatrices(), KalmanFilter::DoFilterAlgebra(), GetXp(), and TrKalmanFilter::ResetNode().
KfVector* KalmanNode::xs protected
Definition at line 220 of file KalmanNode.h.
View newest version in sPHENIX GitHub at line 220 of file KalmanNode.h
Referenced by AllocateKfMatrices(), GetXs(), and TrKalmanFilter::ResetNode().
The documentation for this class was generated from the following files:
EicRoot/blob/master/eic/htc/KalmanNode.h
EicRoot/blob/master/eic/htc/KalmanNode.cxx