EIC Software: HelixHoughFuncs Class Reference
HelixHoughFuncs Class Reference
#include <fun4all_coresoftware/blob/master/offline/packages/trackreco/HelixHoughFuncs.h>
Public Member Functions
~HelixHoughFuncs () override
void identify (std::ostream &os=std::cout) const override
int isValid () const override
isValid returns non zero if object contains vailid data
PHObject * CloneMe () const override
Virtual copy constructor.
virtual void set_current_zoom (unsigned int)
virtual void set_hough_space (HelixHoughSpace *)
virtual void calculate_dzdl_range (float *, std::vector< float > &, std::vector< float > &, float *)
virtual void calculate_phi_range (float *, std::vector< float > &, float *, float *)
virtual void calculate_phi_range (float *, std::vector< float > &, int, float *, float *)
virtual void calculate_phi_range (float *, std::vector< float > &, int, float *, float *, float *)
Public Member Functions inherited from PHObject
PHObject ()
ctor
~PHObject () override
dtor
virtual PHObject * clone () const final
PHObject * Clone (const char *newname="") const final
void Copy (TObject &object) const final
virtual void Reset ()
Clear Event.
virtual int isValid (const float) const
virtual int isValid (const double) const
virtual int isValid (const int) const
virtual int isValid (const unsigned int) const
virtual int isImplemented (const float f) const
virtual int isImplemented (const double f) const
virtual int isImplemented (const int i) const
virtual int isImplemented (const unsigned int i) const
virtual int Integrate () const
virtual int Integrate (PHObject *)
virtual void CopyFrom (const PHObject *obj)
Protected Member Functions
HelixHoughFuncs ()
ClassDefOverride (HelixHoughFuncs, 1)
Detailed Description
Definition at line 13 of file HelixHoughFuncs.h.
View newest version in sPHENIX GitHub at line 13 of file HelixHoughFuncs.h
Constructor & Destructor Documentation
HelixHoughFuncs::~HelixHoughFuncs () inline override
Definition at line 16 of file HelixHoughFuncs.h.
View newest version in sPHENIX GitHub at line 16 of file HelixHoughFuncs.h
HelixHoughFuncs::HelixHoughFuncs () inline protected
Definition at line 41 of file HelixHoughFuncs.h.
View newest version in sPHENIX GitHub at line 41 of file HelixHoughFuncs.h
Member Function Documentation
virtual void HelixHoughFuncs::calculate_dzdl_range (float * , std::vector< float > & , std::vector< float > & , float *) inline virtual
Reimplemented in HelixHoughFuncs_v1.
Definition at line 29 of file HelixHoughFuncs.h.
View newest version in sPHENIX GitHub at line 29 of file HelixHoughFuncs.h
Referenced by PHInitZVertexing::vote_z(), PHPatternReco::vote_z(), PHInitZVertexing::vote_z_init(), and PHPatternReco::vote_z_init().
virtual void HelixHoughFuncs::calculate_phi_range (float * , std::vector< float > & , float * , float *) inline virtual
Reimplemented in HelixHoughFuncs_v1.
Definition at line 30 of file HelixHoughFuncs.h.
View newest version in sPHENIX GitHub at line 30 of file HelixHoughFuncs.h
Referenced by PHInitZVertexing::vote_xy(), and PHPatternReco::vote_xy().
virtual void HelixHoughFuncs::calculate_phi_range (float * , std::vector< float > & , int , float * , float *) inline virtual
Reimplemented in HelixHoughFuncs_v1.
Definition at line 31 of file HelixHoughFuncs.h.
View newest version in sPHENIX GitHub at line 31 of file HelixHoughFuncs.h
virtual void HelixHoughFuncs::calculate_phi_range (float * , std::vector< float > & , int , float * , float * , float *) inline virtual
Reimplemented in HelixHoughFuncs_v1.
Definition at line 32 of file HelixHoughFuncs.h.
View newest version in sPHENIX GitHub at line 32 of file HelixHoughFuncs.h
HelixHoughFuncs::ClassDefOverride (HelixHoughFuncs , 1) protected
PHObject* HelixHoughFuncs::CloneMe () const inline override virtual
Virtual copy constructor.
Reimplemented from PHObject.
Reimplemented in HelixHoughFuncs_v1.
Definition at line 24 of file HelixHoughFuncs.h.
View newest version in sPHENIX GitHub at line 24 of file HelixHoughFuncs.h
void HelixHoughFuncs::identify (std::ostream & os = std::cout) const inline override virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from PHObject.
Reimplemented in HelixHoughFuncs_v1.
Definition at line 19 of file HelixHoughFuncs.h.
View newest version in sPHENIX GitHub at line 19 of file HelixHoughFuncs.h
int HelixHoughFuncs::isValid () const inline override virtual
isValid returns non zero if object contains vailid data
Reimplemented from PHObject.
Reimplemented in HelixHoughFuncs_v1.
Definition at line 23 of file HelixHoughFuncs.h.
View newest version in sPHENIX GitHub at line 23 of file HelixHoughFuncs.h
virtual void HelixHoughFuncs::set_current_zoom (unsigned int) inline virtual
Reimplemented in HelixHoughFuncs_v1.
Definition at line 27 of file HelixHoughFuncs.h.
View newest version in sPHENIX GitHub at line 27 of file HelixHoughFuncs.h
Referenced by PHInitZVertexing::vote_xy(), PHPatternReco::vote_xy(), PHInitZVertexing::vote_z(), PHPatternReco::vote_z(), PHInitZVertexing::vote_z_init(), and PHPatternReco::vote_z_init().
virtual void HelixHoughFuncs::set_hough_space (HelixHoughSpace *) inline virtual
Reimplemented in HelixHoughFuncs_v1.
Definition at line 28 of file HelixHoughFuncs.h.
View newest version in sPHENIX GitHub at line 28 of file HelixHoughFuncs.h
Referenced by PHPatternReco::Init(), and PHInitZVertexing::Setup().
The documentation for this class was generated from the following file:
fun4all_coresoftware/blob/master/offline/packages/trackreco/HelixHoughFuncs.h