EIC Software: fun4all_macros/blob/master/common/G4_DSTReader.C File Reference
G4_DSTReader.C File Reference
Convert DST to human command readable TTree for quick poke around the outputs.
#include <GlobalVariables.C>
#include <G4_Bbc.C>
#include <G4_BlackHole.C>
#include <G4_CEmc_Spacal.C>
#include <G4_EPD.C>
#include <G4_HcalIn_ref.C>
#include <G4_HcalOut_ref.C>
#include <G4_Intt.C>
#include <G4_Magnet.C>
#include <G4_Mvtx.C>
#include <G4_TPC.C>
#include <g4eval/PHG4DSTReader.h>
#include <fun4all/Fun4AllServer.h>
Namespaces
namespace Enable
namespace G4DSTREADER
Macros
#define MACRO_G4DSTREADER_C
Functions
void G4DSTreaderInit ()
void G4DSTreader (const string &outputFile="G4sPHENIXCells.root")
Detailed Description
Convert DST to human command readable TTree for quick poke around the outputs.
Author
Jin Huang
Version
Revision:
Date
Date:
Definition in file G4_DSTReader.C.
Macro Definition Documentation
#define MACRO_G4DSTREADER_C
Definition at line 2 of file G4_DSTReader.C.
View newest version in sPHENIX GitHub at line 2 of file G4_DSTReader.C
Function Documentation
void G4DSTreader (const string & outputFile = "G4sPHENIXCells.root")
Definition at line 47 of file G4_DSTReader.C.
View newest version in sPHENIX GitHub at line 47 of file G4_DSTReader.C
References Enable::ABSORBER, PHG4DSTReader::AddNode(), PHG4DSTReader::AddTower(), Enable::BBC, Enable::BLACKHOLE, Enable::CEMC, Enable::CEMC_ABSORBER, Enable::CEMC_TOWER, Enable::DSTREADER_VERBOSITY, Enable::EPD, Enable::HCALIN, Enable::HCALIN_ABSORBER, Enable::HCALIN_TOWER, Enable::HCALOUT, Enable::HCALOUT_ABSORBER, Enable::HCALOUT_TOWER, Fun4AllServer::instance(), Enable::INTT, Enable::MAGNET, Enable::MAGNET_ABSORBER, max, Enable::MVTX, Fun4AllServer::registerSubsystem(), G4DSTREADER::save_g4_raw, PHG4DSTReader::set_load_active_particle(), PHG4DSTReader::set_load_all_particle(), PHG4DSTReader::set_save_particle(), PHG4DSTReader::set_save_vertex(), PHG4DSTReader::set_tower_zero_sup(), G4DSTREADER::tower_zero_supp, Enable::TPC, Enable::VERBOSITY, and Fun4AllBase::Verbosity().
void G4DSTreaderInit ()
Definition at line 45 of file G4_DSTReader.C.
View newest version in sPHENIX GitHub at line 45 of file G4_DSTReader.C