EIC Software: FairDbTableProxyRegistry Class Reference
FairDbTableProxyRegistry Class Reference
#include <EicRoot/blob/master/dbase/dbInterface/FairDbTableProxyRegistry.h>
Classes
struct Cleaner
Public Member Functions
void ShowStatistics () const
void Config ()
void ClearRollbackDates ()
void ClearSimFlagAssociation ()
FairDbMultConnector & GetMultConnector ()
FairDbTableProxy & GetTableProxy (const std::string &tableName, const FairDbTableRow *tableRow)
Bool_t HasRowCounter (const std::string &tableName)
void PurgeCaches ()
void RefreshMetaData (const std::string &tableName)
void SetSqlCondition (const std::string &sql="")
Public Member Functions inherited from FairDbConfigurable
FairDbConfigurable ()
virtual ~FairDbConfigurable ()
virtual const FairRegistry & DefaultConfig () const
FairRegistry & GetConfig ()
const FairRegistry & GetConfig () const
int Update ()
void Set (FairDbConfDialog *d=0)
void Set (const char *s)
Static Public Member Functions
static FairDbTableProxyRegistry & Instance ()
static Bool_t IsActive ()
Public Attributes
FairDbMultConnector * fMultConnector
MultConnector.
Protected Member Functions
FairDbTableProxyRegistry ()
virtual ~FairDbTableProxyRegistry ()
Protected Member Functions inherited from FairDbConfigurable
virtual void CommitDefaultConfig (const FairRegistry &r)
Private Member Functions
void SetConfigFromEnvironment ()
FairDbTableProxyRegistry (const FairDbTableProxyRegistry &)
FairDbTableProxyRegistry & operator= (const FairDbTableProxyRegistry &)
void ApplySqlCondition () const
void ApplySqlCondition (FairDbTableProxy *proxy) const
Private Attributes
std::string fSqlCondition
Default optional condition.
std::map< std::string,
FairDbTableProxy * > fTPmap
TableName::RowName -> TableProxy.
FairDbRollbackDates fRollbackDates
Rollback dates for each table.
FairDbSimFlagAssociation fSimFlagAss
Lists of SimFlag associations.
Static Private Attributes
static FairDbTableProxyRegistry * fgInstance
Holds only instance.
Friends
class Cleaner
Detailed Description
Definition at line 21 of file FairDbTableProxyRegistry.h.
View newest version in sPHENIX GitHub at line 21 of file FairDbTableProxyRegistry.h
Constructor & Destructor Documentation
FairDbTableProxyRegistry::FairDbTableProxyRegistry () protected
Definition at line 23 of file FairDbTableProxyRegistry.cxx.
View newest version in sPHENIX GitHub at line 23 of file FairDbTableProxyRegistry.cxx
References fMultConnector, and SetConfigFromEnvironment().
Referenced by Instance().
FairDbTableProxyRegistry::~FairDbTableProxyRegistry () protected virtual
Definition at line 50 of file FairDbTableProxyRegistry.cxx.
View newest version in sPHENIX GitHub at line 50 of file FairDbTableProxyRegistry.cxx
References fgInstance, fMultConnector, fTPmap, FairDbConfigurable::GetConfig(), FairDbExceptionLog::GetGELog(), FairDbExceptionLog::Print(), FairDbServices::SetRecord(), and FairDbExceptionLog::Size().
FairDbTableProxyRegistry::FairDbTableProxyRegistry (const FairDbTableProxyRegistry &) private
Member Function Documentation
void FairDbTableProxyRegistry::ApplySqlCondition () const private
Definition at line 92 of file FairDbTableProxyRegistry.cxx.
View newest version in sPHENIX GitHub at line 92 of file FairDbTableProxyRegistry.cxx
References fTPmap.
Referenced by ClearRollbackDates(), Config(), GetTableProxy(), and SetSqlCondition().
void FairDbTableProxyRegistry::ApplySqlCondition (FairDbTableProxy * proxy) const private
Definition at line 101 of file FairDbTableProxyRegistry.cxx.
View newest version in sPHENIX GitHub at line 101 of file FairDbTableProxyRegistry.cxx
References fRollbackDates, fSqlCondition, FairDbRollbackDates::GetDate(), FairDbTableProxy::GetTableName(), FairDbRollbackDates::GetType(), and FairDbTableProxy::SetSqlCondition().
void FairDbTableProxyRegistry::ClearRollbackDates ()
Definition at line 119 of file FairDbTableProxyRegistry.cxx.
View newest version in sPHENIX GitHub at line 119 of file FairDbTableProxyRegistry.cxx
References ApplySqlCondition(), FairDbRollbackDates::Clear(), and fRollbackDates.
void FairDbTableProxyRegistry::ClearSimFlagAssociation ()
Definition at line 127 of file FairDbTableProxyRegistry.cxx.
View newest version in sPHENIX GitHub at line 127 of file FairDbTableProxyRegistry.cxx
References FairDbSimFlagAssociation::Clear(), and fSimFlagAss.
void FairDbTableProxyRegistry::Config () virtual
Implements FairDbConfigurable.
Definition at line 133 of file FairDbTableProxyRegistry.cxx.
View newest version in sPHENIX GitHub at line 133 of file FairDbTableProxyRegistry.cxx
References ApplySqlCondition(), FairDbServices::fAsciiDBConectionsTemporary, fMultConnector, FairDbServices::fOrderContextQuery, fRollbackDates, fSimFlagAss, FairRegistry::Get(), FairDbConfigurable::GetConfig(), FairDbMultConnector::GetNumDb(), FairRegistry::RemoveKey(), FairDbRollbackDates::Set(), FairDbSimFlagAssociation::Set(), FairDbMultConnector::SetPermanent(), and FairDbBinaryFile::SetWorkDir().
FairDbMultConnector& FairDbTableProxyRegistry::GetMultConnector () inline
Definition at line 36 of file FairDbTableProxyRegistry.h.
View newest version in sPHENIX GitHub at line 36 of file FairDbTableProxyRegistry.h
References fMultConnector.
Referenced by FairDbSqlValPacket::Recreate(), FairDbSqlValPacket::SetMetaData(), FairDbLogEntry::SetServerName(), ShowStatistics(), and FairDbConfigStream::Write().
FairDbTableProxy & FairDbTableProxyRegistry::GetTableProxy (const std::string & tableName, const FairDbTableRow * tableRow)
Definition at line 228 of file FairDbTableProxyRegistry.cxx.
View newest version in sPHENIX GitHub at line 228 of file FairDbTableProxyRegistry.cxx
References ApplySqlCondition(), fMultConnector, fTPmap, FairDbMultConnector::TableExists(), and FairUtilString::ToUpper().
Referenced by ClassImp(), HasRowCounter(), FairDbSqlValPacket::Recreate(), FairDbSqlValPacket::SetMetaData(), FairDbSqlValPacket::Store(), and FairDbLogEntry::Write().
Bool_t FairDbTableProxyRegistry::HasRowCounter (const std::string & tableName)
Definition at line 255 of file FairDbTableProxyRegistry.cxx.
View newest version in sPHENIX GitHub at line 255 of file FairDbTableProxyRegistry.cxx
References FairDbTableProxy::GetMetaData(), GetTableProxy(), and FairDbTableMetaData::HasRowCounter().
FairDbTableProxyRegistry & FairDbTableProxyRegistry::Instance () static
Definition at line 264 of file FairDbTableProxyRegistry.cxx.
View newest version in sPHENIX GitHub at line 264 of file FairDbTableProxyRegistry.cxx
References FairDbTableProxyRegistry(), and fgInstance.
Referenced by ClassImp(), FairDbSqlValPacket::CreateTable(), FairDbSqlValPacket::Recreate(), FairDbSqlValPacket::SetMetaData(), FairDbLogEntry::SetServerName(), FairDbSqlValPacket::Store(), FairDbConfigStream::Write(), and FairDbLogEntry::Write().
static Bool_t FairDbTableProxyRegistry::IsActive () inline static
Definition at line 31 of file FairDbTableProxyRegistry.h.
View newest version in sPHENIX GitHub at line 31 of file FairDbTableProxyRegistry.h
References fgInstance.
FairDbTableProxyRegistry& FairDbTableProxyRegistry::operator= (const FairDbTableProxyRegistry &) private
void FairDbTableProxyRegistry::PurgeCaches ()
Definition at line 276 of file FairDbTableProxyRegistry.cxx.
View newest version in sPHENIX GitHub at line 276 of file FairDbTableProxyRegistry.cxx
References fTPmap, FairDbTableProxy::GetCache(), and FairDbCache::Purge().
void FairDbTableProxyRegistry::RefreshMetaData (const std::string & tableName)
Definition at line 289 of file FairDbTableProxyRegistry.cxx.
View newest version in sPHENIX GitHub at line 289 of file FairDbTableProxyRegistry.cxx
References fTPmap, FairDbTableProxy::GetTableName(), and FairDbTableProxy::RefreshMetaData().
Referenced by FairDbSqlValPacket::CreateTable().
void FairDbTableProxyRegistry::SetConfigFromEnvironment () private
Definition at line 301 of file FairDbTableProxyRegistry.cxx.
View newest version in sPHENIX GitHub at line 301 of file FairDbTableProxyRegistry.cxx
References FairDbConfigurable::Set(), FairUtilString::StringTok(), and FairDbConfigurable::Update().
Referenced by FairDbTableProxyRegistry().
void FairDbTableProxyRegistry::SetSqlCondition (const std::string & sql = "")
Definition at line 317 of file FairDbTableProxyRegistry.cxx.
View newest version in sPHENIX GitHub at line 317 of file FairDbTableProxyRegistry.cxx
References ApplySqlCondition(), and fSqlCondition.
void FairDbTableProxyRegistry::ShowStatistics () const
Definition at line 324 of file FairDbTableProxyRegistry.cxx.
View newest version in sPHENIX GitHub at line 324 of file FairDbTableProxyRegistry.cxx
References fTPmap, GetMultConnector(), and name.
Friends And Related Function Documentation
friend class Cleaner friend
Definition at line 67 of file FairDbTableProxyRegistry.h.
View newest version in sPHENIX GitHub at line 67 of file FairDbTableProxyRegistry.h
Member Data Documentation
FairDbTableProxyRegistry* FairDbTableProxyRegistry::fgInstance static private
Holds only instance.
Definition at line 103 of file FairDbTableProxyRegistry.h.
View newest version in sPHENIX GitHub at line 103 of file FairDbTableProxyRegistry.h
Referenced by Instance(), IsActive(), FairDbTableProxyRegistry::Cleaner::~Cleaner(), and ~FairDbTableProxyRegistry().
FairDbMultConnector* FairDbTableProxyRegistry::fMultConnector
MultConnector.
Definition at line 71 of file FairDbTableProxyRegistry.h.
View newest version in sPHENIX GitHub at line 71 of file FairDbTableProxyRegistry.h
Referenced by Config(), FairDbTableProxyRegistry(), GetMultConnector(), GetTableProxy(), and ~FairDbTableProxyRegistry().
FairDbRollbackDates FairDbTableProxyRegistry::fRollbackDates private
Rollback dates for each table.
Definition at line 96 of file FairDbTableProxyRegistry.h.
View newest version in sPHENIX GitHub at line 96 of file FairDbTableProxyRegistry.h
Referenced by ApplySqlCondition(), ClearRollbackDates(), and Config().
FairDbSimFlagAssociation FairDbTableProxyRegistry::fSimFlagAss private
Lists of SimFlag associations.
Definition at line 99 of file FairDbTableProxyRegistry.h.
View newest version in sPHENIX GitHub at line 99 of file FairDbTableProxyRegistry.h
Referenced by ClearSimFlagAssociation(), and Config().
std::string FairDbTableProxyRegistry::fSqlCondition private
Default optional condition.
Definition at line 88 of file FairDbTableProxyRegistry.h.
View newest version in sPHENIX GitHub at line 88 of file FairDbTableProxyRegistry.h
Referenced by ApplySqlCondition(), and SetSqlCondition().
std::map<std::string,FairDbTableProxy*> FairDbTableProxyRegistry::fTPmap private
TableName::RowName -> TableProxy.
Definition at line 92 of file FairDbTableProxyRegistry.h.
View newest version in sPHENIX GitHub at line 92 of file FairDbTableProxyRegistry.h
Referenced by ApplySqlCondition(), GetTableProxy(), PurgeCaches(), RefreshMetaData(), ShowStatistics(), and ~FairDbTableProxyRegistry().
The documentation for this class was generated from the following files:
EicRoot/blob/master/dbase/dbInterface/FairDbTableProxyRegistry.h
EicRoot/blob/master/dbase/dbInterface/FairDbTableProxyRegistry.cxx