EIC Software: FairDbStatement Class Reference
FairDbStatement Class Reference
#include <EicRoot/blob/master/dbase/dbInterface/FairDbStatement.h>
Public Member Functions
FairDbStatement (FairDbConnection &conDb)
virtual ~FairDbStatement ()
FairDb::DbTypes GetDBType () const
std::list< TString > TestTranslateSQL (const TString &sql, FairDb::DbTypes type)
TSQLStatement * ExecuteQuery (const TString &sql="")
Bool_t ExecuteUpdate (const TString &sql="")
Bool_t PrintExceptions (Int_t level=3) const
const FairDbExceptionLog & GetExceptionLog () const
Private Member Functions
void AppendExceptionLog (FairDbException *e)
void AppendExceptionLog (TSQLStatement *s)
void AppendExceptionLog (FairDbConnection &c)
void ClearExceptionLog ()
TSQLStatement * CreateProcessedStatement (const TString &sql="")
std::list< TString > TranslateSQL (const TString &sql)
Private Attributes
FairDbConnection & fConDb
FairDb::DbTypes fDbType
FairDbExceptionLog fExceptionLog
Detailed Description
Definition at line 16 of file FairDbStatement.h.
View newest version in sPHENIX GitHub at line 16 of file FairDbStatement.h
Constructor & Destructor Documentation
FairDbStatement::FairDbStatement (FairDbConnection & conDb)
FairDbStatement::~FairDbStatement () virtual
Definition at line 23 of file FairDbStatement.cxx.
View newest version in sPHENIX GitHub at line 23 of file FairDbStatement.cxx
References FairDbConnection::DisConnectStatement(), and fConDb.
Member Function Documentation
void FairDbStatement::AppendExceptionLog (FairDbException * e) inline private
Definition at line 33 of file FairDbStatement.h.
View newest version in sPHENIX GitHub at line 33 of file FairDbStatement.h
References FairDbExceptionLog::AddEntry(), and fExceptionLog.
Referenced by CreateProcessedStatement(), ExecuteQuery(), and ExecuteUpdate().
void FairDbStatement::AppendExceptionLog (TSQLStatement * s) inline private
Definition at line 34 of file FairDbStatement.h.
View newest version in sPHENIX GitHub at line 34 of file FairDbStatement.h
References FairDbExceptionLog::AddEntry(), and fExceptionLog.
void FairDbStatement::AppendExceptionLog (FairDbConnection & c) inline private
Definition at line 35 of file FairDbStatement.h.
View newest version in sPHENIX GitHub at line 35 of file FairDbStatement.h
References FairDbExceptionLog::AddLog(), fExceptionLog, and FairDbConnection::GetExceptionLog().
void FairDbStatement::ClearExceptionLog () inline private
Definition at line 36 of file FairDbStatement.h.
View newest version in sPHENIX GitHub at line 36 of file FairDbStatement.h
References FairDbExceptionLog::Clear(), and fExceptionLog.
Referenced by ExecuteQuery(), and ExecuteUpdate().
TSQLStatement * FairDbStatement::CreateProcessedStatement (const TString & sql = "") private
Definition at line 28 of file FairDbStatement.cxx.
View newest version in sPHENIX GitHub at line 28 of file FairDbStatement.cxx
References AppendExceptionLog(), FairDbConnection::CreatePreparedStatement(), and fConDb.
Referenced by ExecuteQuery().
TSQLStatement * FairDbStatement::ExecuteQuery (const TString & sql = "")
Definition at line 43 of file FairDbStatement.cxx.
View newest version in sPHENIX GitHub at line 43 of file FairDbStatement.cxx
References FairDbExceptionLog::AddEntry(), AppendExceptionLog(), ClearExceptionLog(), CreateProcessedStatement(), fConDb, fExceptionLog, FairDbConnection::GetDbName(), FairDbExceptionLog::IsEmpty(), and TranslateSQL().
Referenced by ClassImp(), and FairDbMultConnector::ReserveNextSeqNo().
Bool_t FairDbStatement::ExecuteUpdate (const TString & sql = "")
Definition at line 87 of file FairDbStatement.cxx.
View newest version in sPHENIX GitHub at line 87 of file FairDbStatement.cxx
References AppendExceptionLog(), ClearExceptionLog(), fConDb, fExceptionLog, FairDbConnection::GetDbName(), FairDbConnection::GetServer(), FairDbExceptionLog::IsEmpty(), FairDbConnection::RecordException(), and TranslateSQL().
Referenced by FairDbSqlValPacket::CreateTable(), FairDbMultConnector::CreateTemporaryTable(), FairDbMultConnector::ReserveNextSeqNo(), and FairDbSqlValPacket::Store().
FairDb::DbTypes FairDbStatement::GetDBType () const inline
Definition at line 25 of file FairDbStatement.h.
View newest version in sPHENIX GitHub at line 25 of file FairDbStatement.h
References fDbType.
Referenced by FairDbSqlValPacket::Store().
const FairDbExceptionLog& FairDbStatement::GetExceptionLog () const inline
Definition at line 31 of file FairDbStatement.h.
View newest version in sPHENIX GitHub at line 31 of file FairDbStatement.h
References fExceptionLog.
Referenced by FairDbMultConnector::CreateTemporaryTable(), and PrintExceptions().
Bool_t FairDbStatement::PrintExceptions (Int_t level = 3) const
Definition at line 107 of file FairDbStatement.cxx.
View newest version in sPHENIX GitHub at line 107 of file FairDbStatement.cxx
References FairDbExceptionLog::AddLog(), GetExceptionLog(), FairDbExceptionLog::GetGELog(), and FairDbExceptionLog::IsEmpty().
Referenced by FairDbMultConnector::CreateStatement(), FairDbSqlValPacket::CreateTable(), FairDbMultConnector::CreateTemporaryTable(), FairDbMultConnector::ReserveNextSeqNo(), and FairDbSqlValPacket::Store().
std::list< TString > FairDbStatement::TestTranslateSQL (const TString & sql, FairDb::DbTypes type)
Definition at line 116 of file FairDbStatement.cxx.
View newest version in sPHENIX GitHub at line 116 of file FairDbStatement.cxx
References fDbType, and TranslateSQL().
std::list< TString > FairDbStatement::TranslateSQL (const TString & sql) private
Definition at line 129 of file FairDbStatement.cxx.
View newest version in sPHENIX GitHub at line 129 of file FairDbStatement.cxx
References fDbType, FairDb::kOracle, name, FairDbTableMetaData::SetFromSql(), FairDbTableMetaData::Sql(), and FairUtilString::StringTok().
Referenced by ExecuteQuery(), ExecuteUpdate(), and TestTranslateSQL().
Member Data Documentation
FairDbConnection& FairDbStatement::fConDb private
Definition at line 42 of file FairDbStatement.h.
View newest version in sPHENIX GitHub at line 42 of file FairDbStatement.h
Referenced by CreateProcessedStatement(), ExecuteQuery(), ExecuteUpdate(), and ~FairDbStatement().
FairDb::DbTypes FairDbStatement::fDbType private
Definition at line 43 of file FairDbStatement.h.
View newest version in sPHENIX GitHub at line 43 of file FairDbStatement.h
Referenced by GetDBType(), TestTranslateSQL(), and TranslateSQL().
FairDbExceptionLog FairDbStatement::fExceptionLog private
Definition at line 44 of file FairDbStatement.h.
View newest version in sPHENIX GitHub at line 44 of file FairDbStatement.h
Referenced by AppendExceptionLog(), ClearExceptionLog(), ExecuteQuery(), ExecuteUpdate(), and GetExceptionLog().
The documentation for this class was generated from the following files:
EicRoot/blob/master/dbase/dbInterface/FairDbStatement.h
EicRoot/blob/master/dbase/dbInterface/FairDbStatement.cxx