EIC Software: FairParAsciiFileIo Class Reference
FairParAsciiFileIo Class Reference
#include <EicRoot/blob/master/parbase/FairParAsciiFileIo.h>
Public Member Functions
FairParAsciiFileIo ()
~FairParAsciiFileIo ()
Bool_t open (const Text_t *fname, const Text_t *status="in")
Bool_t open (const TList *fnamelist, const Text_t *status="in")
void close ()
Bool_t check ()
void print ()
std::fstream * getFile ()
Public Member Functions inherited from FairParIo
FairParIo ()
virtual ~FairParIo ()
virtual FairDetParIo * getDetParIo (const Text_t *)
virtual void setDetParIo (FairDetParIo *)
virtual void removeDetParIo (Text_t *)
void setInputNumber (Int_t)
const char * getFilename ()
virtual void setDetParIo (Text_t *)
virtual void readVersions (FairRtdbRun *)
virtual void cd ()
void setAutoWritable (Bool_t f=kTRUE)
Bool_t isAutoWritable ()
Protected Attributes
std::fstream * file
Protected Attributes inherited from FairParIo
TList * detParIoList
Bool_t autoWritable
TString filename
Private Member Functions
FairParAsciiFileIo (const FairParAsciiFileIo &)
FairParAsciiFileIo & operator= (const FairParAsciiFileIo &)
Detailed Description
Definition at line 10 of file FairParAsciiFileIo.h.
View newest version in sPHENIX GitHub at line 10 of file FairParAsciiFileIo.h
Constructor & Destructor Documentation
FairParAsciiFileIo::FairParAsciiFileIo ()
FairParAsciiFileIo::~FairParAsciiFileIo ()
Definition at line 43 of file FairParAsciiFileIo.cxx.
View newest version in sPHENIX GitHub at line 43 of file FairParAsciiFileIo.cxx
References close().
FairParAsciiFileIo::FairParAsciiFileIo (const FairParAsciiFileIo &) private
Member Function Documentation
Bool_t FairParAsciiFileIo::check () inline virtual
Reimplemented from FairParIo.
Definition at line 35 of file FairParAsciiFileIo.h.
View newest version in sPHENIX GitHub at line 35 of file FairParAsciiFileIo.h
References file.
Referenced by print().
void FairParAsciiFileIo::close () virtual
Reimplemented from FairParIo.
Definition at line 100 of file FairParAsciiFileIo.cxx.
View newest version in sPHENIX GitHub at line 100 of file FairParAsciiFileIo.cxx
References FairParIo::detParIoList, file, and FairParIo::filename.
Referenced by open(), and ~FairParAsciiFileIo().
std::fstream * FairParAsciiFileIo::getFile ()
Definition at line 127 of file FairParAsciiFileIo.cxx.
View newest version in sPHENIX GitHub at line 127 of file FairParAsciiFileIo.cxx
References file.
Bool_t FairParAsciiFileIo::open (const Text_t * fname, const Text_t * status = "in")
Definition at line 49 of file FairParAsciiFileIo.cxx.
View newest version in sPHENIX GitHub at line 49 of file FairParAsciiFileIo.cxx
References FairRuntimeDb::activateParIo(), close(), file, FairParIo::filename, in, and FairRuntimeDb::instance().
Referenced by FairAnaSelector::Init(), and open().
Bool_t FairParAsciiFileIo::open (const TList * fnamelist, const Text_t * status = "in")
Definition at line 74 of file FairParAsciiFileIo.cxx.
View newest version in sPHENIX GitHub at line 74 of file FairParAsciiFileIo.cxx
References open(), writeMapConfig::outFileName, and pid.
FairParAsciiFileIo& FairParAsciiFileIo::operator= (const FairParAsciiFileIo &) private
void FairParAsciiFileIo::print () virtual
Reimplemented from FairParIo.
Definition at line 112 of file FairParAsciiFileIo.cxx.
View newest version in sPHENIX GitHub at line 112 of file FairParAsciiFileIo.cxx
References check(), FairParIo::detParIoList, and FairParIo::filename.
Member Data Documentation
std::fstream* FairParAsciiFileIo::file protected
Definition at line 13 of file FairParAsciiFileIo.h.
View newest version in sPHENIX GitHub at line 13 of file FairParAsciiFileIo.h
Referenced by check(), close(), getFile(), and open().
The documentation for this class was generated from the following files:
EicRoot/blob/master/parbase/FairParAsciiFileIo.h
EicRoot/blob/master/parbase/FairParAsciiFileIo.cxx