EIC Software: erhic::ParticleMC Class Reference
erhic::ParticleMC Class Reference
#include <eic-smear/blob/master/include/eicsmear/erhic/ParticleMC.h>
Public Member Functions
ParticleMC ()
ParticleMC (const std::string &, bool eAflag)
ParticleMC (const ParticleMC &src)
~ParticleMC ()
virtual const ParticleMC * GetParent () const
virtual const ParticleMC * GetChild (UShort_t) const
virtual Bool_t HasChild (Int_t) const
Public Member Functions inherited from erhic::ParticleMCbase
ParticleMCbase ()
virtual ~ParticleMCbase ()
virtual void Print (Option_t *="") const
virtual UInt_t GetIndex () const
virtual UShort_t GetStatus () const
virtual UShort_t GetParentIndex () const
virtual UShort_t GetParentIndex1 () const
virtual UShort_t GetChild1Index () const
virtual UShort_t GetChildNIndex () const
virtual UInt_t GetNChildren () const
virtual Double_t GetPx () const
virtual Double_t GetPy () const
virtual Double_t GetPz () const
virtual Double_t GetM () const
virtual Double_t GetPt () const
virtual TVector3 GetVertex () const
virtual Pid GetParentId () const
virtual Double_t GetP () const
virtual Double_t GetTheta () const
virtual Double_t GetPhi () const
virtual Double_t GetRapidity () const
virtual Double_t GetEta () const
virtual Double_t GetZ () const
virtual Double_t GetXFeynman () const
virtual Double_t GetThetaVsGamma () const
virtual Double_t GetPtVsGamma () const
const EventMC * GetEvent () const
void SetEvent (EventMC *event)
virtual TLorentzVector Get4Vector () const
virtual TLorentzVector PxPyPzE () const
virtual TLorentzVector Get4VectorInHadronBosonFrame () const
virtual Double_t GetE () const
virtual void SetE (Double_t)
virtual void SetM (Double_t)
virtual void SetP (Double_t)
virtual void SetPt (Double_t)
virtual void SetPz (Double_t)
virtual void SetPhi (Double_t)
virtual void SetTheta (Double_t)
virtual void SetStatus (UShort_t)
virtual Pid Id () const
virtual Pid GetPdgCode () const
virtual void ComputeDerivedQuantities ()
virtual void ComputeEventDependentQuantities (EventMC &)
virtual void SetIndex (int i)
virtual void SetStatus (int i)
virtual void SetId (int i)
virtual void SetParentIndex (int i)
virtual void SetParentIndex1 (int i)
virtual void SetChild1Index (int i)
virtual void SetChildNIndex (int i)
virtual void Set4Vector (const TLorentzVector &)
virtual void SetVertex (const TVector3 &)
virtual void SetParentId (int i)
Public Member Functions inherited from erhic::VirtualParticle
virtual ~VirtualParticle ()
Public Attributes
ParticleMCeA * eA
Public Attributes inherited from erhic::ParticleMCbase
UShort_t I
Particle index in event.
Int_t KS
Particle status code: see PYTHIA manual.
Int_t id
PDG particle code.
UShort_t orig
I of parent particle.
UShort_t orig1
I of parent particle1.
UShort_t daughter
I of first child particle.
UShort_t ldaughter
I of last child particle.
Double_t px
x component of particle momentum
Double_t py
y component of particle momentum
Double_t pz
z component of particle momentum
Double32_t E
Energy of particle.
Double32_t m
Invariant mass of particle.
Double32_t pt
Transverse momentum of particle.
Double_t xv
x coordinate of particle production vertex
Double_t yv
y coordinate of particle production vertex
Double_t zv
z coordinate of particle production vertex
Int_t parentId
PDG code of this particle's parent.
Double32_t p
Total momentum of particle.
Double32_t theta
Polar angle.
Double32_t phi
Azimuthal angle.
Double32_t rapidity
Rapidity of particle.
Double32_t eta
Pseudorapidity of particle.
Double32_t z
Double32_t xFeynman
Feynman x = pz/(2sqrt(s))
Double32_t thetaGamma
Double32_t ptVsGamma
Double32_t thetaGammaHCM
Double32_t ptVsGammaHCM
Double32_t phiPrf
TRef event
Detailed Description
Definition at line 411 of file ParticleMC.h.
View newest version in sPHENIX GitHub at line 411 of file ParticleMC.h
Constructor & Destructor Documentation
erhic::ParticleMC::ParticleMC () inline explicit
Default constructor. Optionally pass a string with particle information in a HEPEVT format, namely: "index status id parent firstChild lastChild px py pz E m xv yv zv"
Definition at line 419 of file ParticleMC.h.
View newest version in sPHENIX GitHub at line 419 of file ParticleMC.h
erhic::ParticleMC::ParticleMC (const std::string & line, bool eAflag) explicit
Definition at line 88 of file ParticleMC.cxx.
View newest version in sPHENIX GitHub at line 88 of file ParticleMC.cxx
References erhic::ParticleMCeA::charge, erhic::ParticleMCbase::ComputeDerivedQuantities(), erhic::ParticleMCbase::daughter, erhic::ParticleMCbase::E, eA, erhic::ParticleMCbase::I, erhic::ParticleMCbase::KS, erhic::ParticleMCbase::ldaughter, erhic::ParticleMCbase::m, erhic::ParticleMCeA::massNum, erhic::ParticleMCeA::NoBam, erhic::ParticleMCbase::orig, erhic::ParticleMCbase::orig1, erhic::ParticleMCbase::px, erhic::ParticleMCbase::py, erhic::ParticleMCbase::pz, erhic::ParticleMCbase::xv, erhic::ParticleMCbase::yv, and erhic::ParticleMCbase::zv.
erhic::ParticleMC::ParticleMC (const ParticleMC & src) inline
Definition at line 422 of file ParticleMC.h.
View newest version in sPHENIX GitHub at line 422 of file ParticleMC.h
References eA.
erhic::ParticleMC::~ParticleMC ()
Definition at line 122 of file ParticleMC.cxx.
View newest version in sPHENIX GitHub at line 122 of file ParticleMC.cxx
References eA.
Member Function Documentation
const ParticleMC * erhic::ParticleMC::GetChild (UShort_t u) const virtual
Returns a pointer to the nth child particle of this particle, where n is in the range [0, GetNChildren()). GetChild(0) returns the child whose index in this particle's event is GetChild1Index(). GetChild(GetNChildren()-1) returns the child whose index is GetChildNIndex(). Returns NULL if there is no such child particle or it cannot be accessed via the event for some reason (see GetEvent()).
Definition at line 217 of file ParticleMC.cxx.
View newest version in sPHENIX GitHub at line 217 of file ParticleMC.cxx
References erhic::ParticleMCbase::daughter, erhic::ParticleMCbase::GetEvent(), erhic::ParticleMCbase::GetNChildren(), erhic::EventMC::GetTrack(), erhic::ParticleMCbase::p, and Acts::UnitConstants::u.
Referenced by EventToDot::Generate(), and HasChild().
const ParticleMC * erhic::ParticleMC::GetParent () const virtual
Returns a pointer to the parent of this particle. This is the particle with index GetParentIndex() in the event containing this particle (obtainable via GetEvent()). Returns NULL if this particle has no parent or if it cannot be accessed via GetEvent().
Definition at line 238 of file ParticleMC.cxx.
View newest version in sPHENIX GitHub at line 238 of file ParticleMC.cxx
References erhic::ParticleMCbase::GetEvent(), erhic::ParticleMCbase::GetParentIndex(), erhic::EventMC::GetTrack(), and erhic::ParticleMCbase::p.
Referenced by EventToDot::Generate(), and TreeToHepMC().
Bool_t erhic::ParticleMC::HasChild (Int_t pdg) const virtual
Returns true if n in the range [0, N), where N is the number of children of this particle. Returns false otherwise. Equivalent to GetChild(n) != NULL.
Definition at line 250 of file ParticleMC.cxx.
View newest version in sPHENIX GitHub at line 250 of file ParticleMC.cxx
References GetChild(), erhic::ParticleMCbase::GetNChildren(), and erhic::ParticleMCbase::Id().
Member Data Documentation
ParticleMCeA* erhic::ParticleMC::eA
Definition at line 459 of file ParticleMC.h.
View newest version in sPHENIX GitHub at line 459 of file ParticleMC.h
Referenced by ParticleMC(), and ~ParticleMC().
The documentation for this class was generated from the following files:
eic-smear/blob/master/include/eicsmear/erhic/ParticleMC.h
eic-smear/blob/master/src/erhic/ParticleMC.cxx