EIC Software: EicBeamLineElementGrad Class Reference
EicBeamLineElementGrad Class Reference
#include <EicRoot/blob/master/eic/field/EicBeamLineElementGrad.h>
Public Member Functions
EicBeamLineElementGrad (const char *name=0, double x=0.0, double y=0.0, double z=0.0, double boreZin=0.0, double boreZout=0.0, double dOut=0.0, double l=0.0, double angle=0.0, double b=0.0, double gradient=0.0)
~EicBeamLineElementGrad ()
int Initialize ()
int GetFieldValue (const double xx[], double B[]) const
void SetFieldScale (const double fieldScaler)
bool CapableToBuildYoke () const
TString GetDetectorName () const
const char * BasenameWrapper (const char *fname) const
int ConstructGeometry ()
TGeoVolume * GetYokeVolume () const
Public Member Functions inherited from EicMagneticFieldMap
EicMagneticFieldMap (const char *fileName=0, TGeoMatrix *transformation=0, TGeoShape *shape=0, int color=_DEFAULT_YOKE_COLOR_)
~EicMagneticFieldMap ()
bool Initialized () const
TGeoShape * GetShape () const
virtual bool Contains (const double xx[]) const
const TString & GetFileName () const
void SetYokeColor (int color)
int GetYokeColor () const
Private Member Functions
ClassDef (EicBeamLineElementGrad, 1)
Private Attributes
TString mName
Double_t mCenterX
Double_t mCenterY
Double_t mCenterZ
Double_t mBoreZin
Double_t mBoreZout
Double_t mDiaOut
Double_t mLength
Double_t mAngle
Double_t mB
Double_t mGradient
Double_t mScale
TGeoVolume * mYoke
TGeoCombiTrans * mTransformation
yoke TGeo volume
Additional Inherited Members
Protected Member Functions inherited from EicMagneticFieldMap
const char * BasenameWrapper (const char *fname) const
int GetMD5Signature (unsigned char output[])
Protected Attributes inherited from EicMagneticFieldMap
UInt_t mMD5BufferSize
UChar_t * mMD5Signature
Bool_t mInitialized
TGeoMatrix * mTransformation
indicates whether Initialize() call was made or not
TGeoShape * mShape
Int_t mColor
Detailed Description
Definition at line 16 of file EicBeamLineElementGrad.h.
View newest version in sPHENIX GitHub at line 16 of file EicBeamLineElementGrad.h
Constructor & Destructor Documentation
EicBeamLineElementGrad::EicBeamLineElementGrad (const char * name = 0, double x = 0.0, double y = 0.0, double z = 0.0, double boreZin = 0.0, double boreZout = 0.0, double dOut = 0.0, double l = 0.0, double angle = 0.0, double b = 0.0, double gradient = 0.0) inline
Definition at line 21 of file EicBeamLineElementGrad.h.
View newest version in sPHENIX GitHub at line 21 of file EicBeamLineElementGrad.h
EicBeamLineElementGrad::~EicBeamLineElementGrad () inline
Definition at line 29 of file EicBeamLineElementGrad.h.
View newest version in sPHENIX GitHub at line 29 of file EicBeamLineElementGrad.h
Member Function Documentation
const char * EicBeamLineElementGrad::BasenameWrapper (const char * fname) const
Definition at line 51 of file EicBeamLineElementGrad.cxx.
View newest version in sPHENIX GitHub at line 51 of file EicBeamLineElementGrad.cxx
Referenced by GetDetectorName().
bool EicBeamLineElementGrad::CapableToBuildYoke () const inline virtual
Reimplemented from EicMagneticFieldMap.
Definition at line 39 of file EicBeamLineElementGrad.h.
View newest version in sPHENIX GitHub at line 39 of file EicBeamLineElementGrad.h
EicBeamLineElementGrad::ClassDef (EicBeamLineElementGrad , 1) private
int EicBeamLineElementGrad::ConstructGeometry () virtual
Reimplemented from EicMagneticFieldMap.
Definition at line 132 of file EicBeamLineElementGrad.cxx.
View newest version in sPHENIX GitHub at line 132 of file EicBeamLineElementGrad.cxx
References _EXTRA_BORE_WIDTH_, _IRON_, _VACUUM_, GetDetectorName(), EicMediaHub::GetMedium(), EicMagneticFieldMap::GetYokeColor(), EicMediaHub::Init(), mB, mBoreZin, mBoreZout, mDiaOut, mLength, mTransformation, mYoke, and Acts::Test::origin().
TString EicBeamLineElementGrad::GetDetectorName () const inline virtual
Reimplemented from EicMagneticFieldMap.
Definition at line 40 of file EicBeamLineElementGrad.h.
View newest version in sPHENIX GitHub at line 40 of file EicBeamLineElementGrad.h
References BasenameWrapper(), and EicMagneticFieldMap::GetFileName().
Referenced by ConstructGeometry().
int EicBeamLineElementGrad::GetFieldValue (const double xx[], double B[]) const virtual
Implements EicMagneticFieldMap.
Definition at line 67 of file EicBeamLineElementGrad.cxx.
View newest version in sPHENIX GitHub at line 67 of file EicBeamLineElementGrad.cxx
References mB, mBoreZout, mGradient, mLength, mScale, and mTransformation.
TGeoVolume* EicBeamLineElementGrad::GetYokeVolume () const inline virtual
Reimplemented from EicMagneticFieldMap.
Definition at line 46 of file EicBeamLineElementGrad.h.
View newest version in sPHENIX GitHub at line 46 of file EicBeamLineElementGrad.h
int EicBeamLineElementGrad::Initialize () virtual
Reimplemented from EicMagneticFieldMap.
Definition at line 35 of file EicBeamLineElementGrad.cxx.
View newest version in sPHENIX GitHub at line 35 of file EicBeamLineElementGrad.cxx
References EicMagneticFieldMap::Initialize(), mAngle, mCenterX, mCenterY, mCenterZ, mTransformation, and rw.
void EicBeamLineElementGrad::SetFieldScale (const double fieldScaler)
Definition at line 59 of file EicBeamLineElementGrad.cxx.
View newest version in sPHENIX GitHub at line 59 of file EicBeamLineElementGrad.cxx
References mScale.
Referenced by EicMagneticFieldFromGradients::AddBeamLineElementGrads(), and EicMagneticField::AddBeamLineElementGrads().
Member Data Documentation
Double_t EicBeamLineElementGrad::mAngle private
Definition at line 55 of file EicBeamLineElementGrad.h.
View newest version in sPHENIX GitHub at line 55 of file EicBeamLineElementGrad.h
Referenced by Initialize().
Double_t EicBeamLineElementGrad::mB private
Definition at line 56 of file EicBeamLineElementGrad.h.
View newest version in sPHENIX GitHub at line 56 of file EicBeamLineElementGrad.h
Referenced by ConstructGeometry(), and GetFieldValue().
Double_t EicBeamLineElementGrad::mBoreZin private
Definition at line 53 of file EicBeamLineElementGrad.h.
View newest version in sPHENIX GitHub at line 53 of file EicBeamLineElementGrad.h
Referenced by ConstructGeometry().
Double_t EicBeamLineElementGrad::mBoreZout private
Definition at line 53 of file EicBeamLineElementGrad.h.
View newest version in sPHENIX GitHub at line 53 of file EicBeamLineElementGrad.h
Referenced by ConstructGeometry(), and GetFieldValue().
Double_t EicBeamLineElementGrad::mCenterX private
Definition at line 50 of file EicBeamLineElementGrad.h.
View newest version in sPHENIX GitHub at line 50 of file EicBeamLineElementGrad.h
Referenced by Initialize().
Double_t EicBeamLineElementGrad::mCenterY private
Definition at line 51 of file EicBeamLineElementGrad.h.
View newest version in sPHENIX GitHub at line 51 of file EicBeamLineElementGrad.h
Referenced by Initialize().
Double_t EicBeamLineElementGrad::mCenterZ private
Definition at line 52 of file EicBeamLineElementGrad.h.
View newest version in sPHENIX GitHub at line 52 of file EicBeamLineElementGrad.h
Referenced by Initialize().
Double_t EicBeamLineElementGrad::mDiaOut private
Definition at line 53 of file EicBeamLineElementGrad.h.
View newest version in sPHENIX GitHub at line 53 of file EicBeamLineElementGrad.h
Referenced by ConstructGeometry().
Double_t EicBeamLineElementGrad::mGradient private
Definition at line 57 of file EicBeamLineElementGrad.h.
View newest version in sPHENIX GitHub at line 57 of file EicBeamLineElementGrad.h
Referenced by GetFieldValue().
Double_t EicBeamLineElementGrad::mLength private
Definition at line 54 of file EicBeamLineElementGrad.h.
View newest version in sPHENIX GitHub at line 54 of file EicBeamLineElementGrad.h
Referenced by ConstructGeometry(), and GetFieldValue().
TString EicBeamLineElementGrad::mName private
Definition at line 46 of file EicBeamLineElementGrad.h.
View newest version in sPHENIX GitHub at line 46 of file EicBeamLineElementGrad.h
Double_t EicBeamLineElementGrad::mScale private
Definition at line 58 of file EicBeamLineElementGrad.h.
View newest version in sPHENIX GitHub at line 58 of file EicBeamLineElementGrad.h
Referenced by GetFieldValue(), and SetFieldScale().
TGeoCombiTrans* EicBeamLineElementGrad::mTransformation private
yoke TGeo volume
Definition at line 62 of file EicBeamLineElementGrad.h.
View newest version in sPHENIX GitHub at line 62 of file EicBeamLineElementGrad.h
Referenced by ConstructGeometry(), GetFieldValue(), and Initialize().
TGeoVolume* EicBeamLineElementGrad::mYoke private
Definition at line 60 of file EicBeamLineElementGrad.h.
View newest version in sPHENIX GitHub at line 60 of file EicBeamLineElementGrad.h
Referenced by ConstructGeometry().
The documentation for this class was generated from the following files:
EicRoot/blob/master/eic/field/EicBeamLineElementGrad.h
EicRoot/blob/master/eic/field/EicBeamLineElementGrad.cxx