EIC Software: FairBoxSet Class Reference
FairBoxSet Class Reference
#include <EicRoot/blob/master/eventdisplay/FairBoxSet.h>
Public Member Functions
FairBoxSet (FairBoxSetDraw *drawer, const char *name="FairBoxSet", const char *t="")
void SetTimeWindowPlus (Double_t time)
void SetTimeWindowMinus (Double_t time)
Double_t GetTimeWindowPlus ()
Double_t GetTimeWindowMinus ()
virtual ~FairBoxSet ()
Private Member Functions
FairBoxSet (const FairBoxSet &)
FairBoxSet operator= (const FairBoxSet &)
ClassDef (FairBoxSet, 1)
Private Attributes
FairBoxSetDraw * fDraw
Detailed Description
FairBoxSet
Author
T. Stockmanns
Since
26.3.2009 Base class to display 3D Points in Eve as a BoxSet One has to overwrite the method GetVector which takes a TObject and writes out a TVector3 which is then taken as an input to place the points. If one wants to change the color of the points one has to overwrite the method GetValue. This method takes a TObject and an integer and translates this into an integer as input for the EveBoxSet method DigitValue
Definition at line 26 of file FairBoxSet.h.
View newest version in sPHENIX GitHub at line 26 of file FairBoxSet.h
Constructor & Destructor Documentation
FairBoxSet::FairBoxSet (FairBoxSetDraw * drawer, const char * name = "FairBoxSet", const char * t = "")
Standard constructor
Definition at line 14 of file FairBoxSet.cxx.
View newest version in sPHENIX GitHub at line 14 of file FairBoxSet.cxx
virtual FairBoxSet::~FairBoxSet () inline virtual
Destructor
Definition at line 43 of file FairBoxSet.h.
View newest version in sPHENIX GitHub at line 43 of file FairBoxSet.h
FairBoxSet::FairBoxSet (const FairBoxSet &) private
Member Function Documentation
FairBoxSet::ClassDef (FairBoxSet , 1) private
Double_t FairBoxSet::GetTimeWindowMinus () inline
Definition at line 39 of file FairBoxSet.h.
View newest version in sPHENIX GitHub at line 39 of file FairBoxSet.h
References fDraw, and FairBoxSetDraw::GetTimeWindowMinus().
Referenced by FairBoxSetEditor::SetModel().
Double_t FairBoxSet::GetTimeWindowPlus () inline
Definition at line 38 of file FairBoxSet.h.
View newest version in sPHENIX GitHub at line 38 of file FairBoxSet.h
References fDraw, and FairBoxSetDraw::GetTimeWindowPlus().
Referenced by FairBoxSetEditor::SetModel().
FairBoxSet FairBoxSet::operator= (const FairBoxSet &) private
void FairBoxSet::SetTimeWindowMinus (Double_t time) inline
Definition at line 36 of file FairBoxSet.h.
View newest version in sPHENIX GitHub at line 36 of file FairBoxSet.h
References fDraw, and FairBoxSetDraw::SetTimeWindowMinus().
Referenced by FairBoxSetEditor::TimeWindow().
void FairBoxSet::SetTimeWindowPlus (Double_t time) inline
Definition at line 35 of file FairBoxSet.h.
View newest version in sPHENIX GitHub at line 35 of file FairBoxSet.h
References fDraw, and FairBoxSetDraw::SetTimeWindowPlus().
Referenced by FairBoxSetEditor::TimeWindow().
Member Data Documentation
FairBoxSetDraw* FairBoxSet::fDraw private
Definition at line 43 of file FairBoxSet.h.
View newest version in sPHENIX GitHub at line 43 of file FairBoxSet.h
Referenced by GetTimeWindowMinus(), GetTimeWindowPlus(), SetTimeWindowMinus(), and SetTimeWindowPlus().
The documentation for this class was generated from the following files:
EicRoot/blob/master/eventdisplay/FairBoxSet.h
EicRoot/blob/master/eventdisplay/FairBoxSet.cxx