EIC Software: EicRecoKalmanTask Class Reference
EicRecoKalmanTask Class Reference
#include <EicRoot/blob/master/eic/tracking/EicRecoKalmanTask.h>
Public Member Functions
EicRecoKalmanTask (EicIdealTrackingCode *ideal=0)
~EicRecoKalmanTask ()
InitStatus Init ()
void Exec (Option_t *opt)
void SetNumIterations (Int_t numIt)
Public Member Functions inherited from PndRecoKalmanTask
PndRecoKalmanTask (const char *name="Genfit", Int_t iVerbose=0)
~PndRecoKalmanTask ()
void SetTrackInBranchName (const TString &name)
void SetTrackInIDBranchName (const TString &name)
void SetTrackOutBranchName (const TString &name)
void SetMvdBranchName (const TString &name)
void SetCentralTrackerBranchName (const TString &name)
void SetPersistence (Bool_t opt=kTRUE)
void SetGeane (Bool_t opt=kTRUE)
void SetIdealHyp (Bool_t opt=kTRUE)
void SetDaf (Bool_t opt=kTRUE)
void SetPropagateToIP (Bool_t opt=kTRUE)
void SetPerpPlane (Bool_t opt=kTRUE)
void SetTrackRep (Short_t num)
void SetParticleHypo (TString s)
void SetParticleHypo (Int_t h)
void SetBusyCut (Int_t b)
void SetParContainers ()
void StoreTrackParameterization (void)
Public Member Functions inherited from FairTask
FairTask ()
FairTask (const char *name, Int_t iVerbose=1)
virtual ~FairTask ()
void InitTask ()
void ReInitTask ()
void SetParTask ()
virtual void FinishTask ()
virtual void FinishEvent ()
void SetVerbose (Int_t iVerbose)
void SetInputPersistance (Bool_t val)
void CheckInputPersistance (TString branchName)
Private Member Functions
ClassDef (EicRecoKalmanTask, 2)
Private Attributes
EicIdealTrackingCode * fIdeal
Additional Inherited Members
Protected Member Functions inherited from PndRecoKalmanTask
ClassDef (PndRecoKalmanTask, 2)
Protected Attributes inherited from PndRecoKalmanTask
TClonesArray * fTrackArray
TClonesArray * fTrackIDArray
Input TCA for PndTrack.
TClonesArray * fMCTrackArray
Input TCA for PndTrackID.
TClonesArray * fFitTrackArray
Input TCA for PndMCTrack.
TString fTrackInBranchName
Output TCA for track.
TString fTrackInIDBranchName
Name of the input TCA.
TString fTrackOutBranchName
Name of the input TCA.
TString fMvdBranchName
Name of the output TCA.
TString fCentralTrackerBranchName
Name of the TCA for MVD.
PndRecoKalmanFit * fFitter
Name of the TCA for central tracker.
PndRecoDafFit * fDafFitter
TDatabasePDG * pdg
Bool_t fPersistence
Particle DB.
Bool_t fUseGeane
Persistence.
Bool_t fSmoothing
Flag to use Geane.
Bool_t fIdealHyp
Flag to set on smoothing (not used)
Bool_t fDaf
Flag to use MC particle hypothesis.
Bool_t fPropagateToIP
Flag to use Deterministic Annealing.
Bool_t fPerpPlane
Flag to propagate the parameters to the interaction point (kTRUE)
Short_t fTrackRep
Flag to use as initial plane the one perpendicular to the track (kFALSE)
Int_t fNumIt
(0) GeaneTrackRep, 1 RKTrackRep
Int_t fPDGHyp
Number of iterations.
Int_t fBusyCut
Hypothesis.
bool mStoreTrackParameterization
Skip too busy events with more tracks.
Detailed Description
Definition at line 14 of file EicRecoKalmanTask.h.
View newest version in sPHENIX GitHub at line 14 of file EicRecoKalmanTask.h
Constructor & Destructor Documentation
EicRecoKalmanTask::EicRecoKalmanTask (EicIdealTrackingCode * ideal = 0)
Definition at line 22 of file EicRecoKalmanTask.cxx.
View newest version in sPHENIX GitHub at line 22 of file EicRecoKalmanTask.cxx
References _BUSY_CUT_DEFAULT_, _ITERATIONS_DEFAULT_, FairRun::AddTask(), fIdeal, PndRecoKalmanTask::fTrackOutBranchName, FairRunAna::Instance(), PndRecoKalmanTask::SetBusyCut(), and SetNumIterations().
EicRecoKalmanTask::~EicRecoKalmanTask () inline
Definition at line 21 of file EicRecoKalmanTask.h.
View newest version in sPHENIX GitHub at line 21 of file EicRecoKalmanTask.h
Member Function Documentation
EicRecoKalmanTask::ClassDef (EicRecoKalmanTask , 2) private
void EicRecoKalmanTask::Exec (Option_t * opt) virtual
Reimplemented from PndRecoKalmanTask.
Definition at line 111 of file EicRecoKalmanTask.cxx.
View newest version in sPHENIX GitHub at line 111 of file EicRecoKalmanTask.cxx
References PndRecoKalmanTask::Exec().
InitStatus EicRecoKalmanTask::Init (void) virtual
Intialisation at begin of run. To be implemented in the derived class. Success If not kSUCCESS, task will be set inactive.
Reimplemented from PndRecoKalmanTask.
Definition at line 36 of file EicRecoKalmanTask.cxx.
View newest version in sPHENIX GitHub at line 36 of file EicRecoKalmanTask.cxx
References GFRecoHitFactory::addProducer(), ff, PndRecoKalmanTask::fFitter, EicIdealTrackingCode::fGroups, fIdeal, EicIdealTrackingCode::fTracksArrayName, FairRootManager::GetInFile(), FairRootManager::GetObject(), PndRecoKalmanFit::GetRecoHitFactory(), PndRecoKalmanTask::Init(), FairRootManager::Instance(), it, kERROR, kSUCCESS, PndRecoKalmanTask::SetDaf(), and PndRecoKalmanTask::SetTrackInBranchName().
void EicRecoKalmanTask::SetNumIterations (Int_t numIt) inline
Definition at line 28 of file EicRecoKalmanTask.h.
View newest version in sPHENIX GitHub at line 28 of file EicRecoKalmanTask.h
References PndRecoKalmanTask::fNumIt.
Referenced by EicRecoKalmanTask().
Member Data Documentation
EicIdealTrackingCode* EicRecoKalmanTask::fIdeal private
Definition at line 28 of file EicRecoKalmanTask.h.
View newest version in sPHENIX GitHub at line 28 of file EicRecoKalmanTask.h
Referenced by EicRecoKalmanTask(), and Init().
The documentation for this class was generated from the following files:
EicRoot/blob/master/eic/tracking/EicRecoKalmanTask.h
EicRoot/blob/master/eic/tracking/EicRecoKalmanTask.cxx