EIC Software: Acts::SurfaceStub Class Reference
Acts::SurfaceStub Class Reference
Surface derived class stub.
#include <fun4all_acts/blob/master/Tests/UnitTests/Core/Surfaces/SurfaceStub.hpp>
Public Member Functions
SurfaceStub (std::shared_ptr< const Transform3D > htrans=nullptr)
SurfaceStub (const GeometryContext &gctx, const SurfaceStub &sf, const Transform3D &transf)
SurfaceStub (const DetectorElementBase &detelement)
~SurfaceStub () override
SurfaceType type () const final
Return method for the Surface type to avoid dynamic casts.
const Vector3D normal (const GeometryContext &gctx, const Vector2D &) const final
Return method for the normal vector of the surface.
const Vector3D normal (const GeometryContext &gctx, const Vector3D &) const final
const Vector3D normal (const GeometryContext &) const final
const SurfaceBounds & bounds () const final
Return method for SurfaceBounds.
void localToGlobal (const GeometryContext &, const Vector2D &, const Vector3D &, Vector3D &) const final
Local to global transformation.
bool globalToLocal (const GeometryContext &, const Vector3D &, const Vector3D &, Vector2D &lpos) const final
Global to local transformation.
double pathCorrection (const GeometryContext &, const Vector3D &, const Vector3D &) const final
Calculation of the path correction for incident.
Intersection intersectionEstimate (const GeometryContext &, const Vector3D &, const Vector3D &, const BoundaryCheck &) const final
Straight line intersection schema from parameters.
const Vector3D binningPosition (const GeometryContext &, BinningValue) const final
Inherited from GeometryObject base.
std::string name () const final
Return properly formatted class name.
bool constructedOk () const
Simply return true to check a method can be called on a constructed object.
Polyhedron polyhedronRepresentation (const GeometryContext &, size_t) const final
Return a Polyhedron for the surfaces.
Public Member Functions inherited from Acts::Surface
virtual ~Surface ()
std::shared_ptr< Surface > getSharedPtr ()
std::shared_ptr< const Surface > getSharedPtr () const
Surface & operator= (const Surface &other)
virtual bool operator== (const Surface &other) const
virtual bool operator!= (const Surface &sf) const
virtual const Transform3D & transform (const GeometryContext &gctx) const
virtual const Vector3D center (const GeometryContext &gctx) const
const DetectorElementBase * associatedDetectorElement () const
const Layer * associatedLayer () const
void associateLayer (const Layer &lay)
const ISurfaceMaterial * surfaceMaterial () const
const std::shared_ptr< const
ISurfaceMaterial > & surfaceMaterialSharedPtr () const
void assignSurfaceMaterial (std::shared_ptr< const ISurfaceMaterial > material)
bool isOnSurface (const GeometryContext &gctx, const Vector3D &position, const Vector3D &momentum, const BoundaryCheck &bcheck=true) const
virtual bool insideBounds (const Vector2D &lposition, const BoundaryCheck &bcheck=true) const
virtual const
Acts::RotationMatrix3D referenceFrame (const GeometryContext &gctx, const Vector3D &position, const Vector3D &momentum) const
virtual void initJacobianToGlobal (const GeometryContext &gctx, BoundToFreeMatrix &jacobian, const Vector3D &position, const Vector3D &direction, const BoundVector &pars) const
virtual const RotationMatrix3D initJacobianToLocal (const GeometryContext &gctx, FreeToBoundMatrix &jacobian, const Vector3D &position, const Vector3D &direction) const
virtual const BoundRowVector derivativeFactors (const GeometryContext &gctx, const Vector3D &position, const Vector3D &direction, const RotationMatrix3D &rft, const BoundToFreeMatrix &jacobian) const
virtual SurfaceIntersection intersect (const GeometryContext &gctx, const Vector3D &position, const Vector3D &direction, const BoundaryCheck &bcheck) const
virtual std::ostream & toStream (const GeometryContext &gctx, std::ostream &sl) const
Public Member Functions inherited from Acts::GeometryObject
GeometryObject ()=default
Defaulted construrctor.
GeometryObject (const GeometryObject &)=default
Defaulted copy constructor.
GeometryObject (const GeometryID &geoID)
GeometryObject & operator= (const GeometryObject &geoID)
const GeometryID & geoID () const
virtual double binningPositionValue (const GeometryContext &gctx, BinningValue bValue) const
void assignGeoID (const GeometryID &geoID)
Private Attributes
std::shared_ptr< const
PlanarBounds > m_bounds
the bounds of this surface
Additional Inherited Members
Public Types inherited from Acts::Surface
enum SurfaceType {
Cone = 0, Cylinder = 1, Disc = 2, Perigee = 3,
Plane = 4, Straw = 5, Curvilinear = 6, Other = 7
}
Static Public Member Functions inherited from Acts::Surface
template<class T , typename... Args>
static std::shared_ptr< T > makeShared (Args &&...args)
Protected Member Functions inherited from Acts::Surface
Surface (std::shared_ptr< const Transform3D > tform=nullptr)
Surface (const Surface &other)
Surface (const DetectorElementBase &detelement)
Surface (const GeometryContext &gctx, const Surface &other, const Transform3D &shift)
Protected Attributes inherited from Acts::Surface
std::shared_ptr< const
Transform3D > m_transform
const DetectorElementBase * m_associatedDetElement {nullptr}
Pointer to the a DetectorElementBase.
const Layer * m_associatedLayer {nullptr}
const TrackingVolume * m_associatedTrackingVolume {nullptr}
std::shared_ptr< const
ISurfaceMaterial > m_surfaceMaterial
Possibility to attach a material descrption.
Detailed Description
Surface derived class stub.
Definition at line 19 of file SurfaceStub.hpp.
View newest version in sPHENIX GitHub at line 19 of file SurfaceStub.hpp
Constructor & Destructor Documentation
Acts::SurfaceStub::SurfaceStub (std::shared_ptr< const Transform3D > htrans = nullptr) inline
Definition at line 21 of file SurfaceStub.hpp.
View newest version in sPHENIX GitHub at line 21 of file SurfaceStub.hpp
Acts::SurfaceStub::SurfaceStub (const GeometryContext & gctx, const SurfaceStub & sf, const Transform3D & transf) inline
Definition at line 23 of file SurfaceStub.hpp.
View newest version in sPHENIX GitHub at line 23 of file SurfaceStub.hpp
Acts::SurfaceStub::SurfaceStub (const DetectorElementBase & detelement) inline
Definition at line 26 of file SurfaceStub.hpp.
View newest version in sPHENIX GitHub at line 26 of file SurfaceStub.hpp
Acts::SurfaceStub::~SurfaceStub () inline override
Definition at line 29 of file SurfaceStub.hpp.
View newest version in sPHENIX GitHub at line 29 of file SurfaceStub.hpp
Member Function Documentation
const Vector3D Acts::SurfaceStub::binningPosition (const GeometryContext & , BinningValue) const inline final virtual
Inherited from GeometryObject base.
Implements Acts::GeometryObject.
Definition at line 85 of file SurfaceStub.hpp.
View newest version in sPHENIX GitHub at line 85 of file SurfaceStub.hpp
References v.
const SurfaceBounds& Acts::SurfaceStub::bounds () const inline final virtual
Return method for SurfaceBounds.
Implements Acts::Surface.
Definition at line 51 of file SurfaceStub.hpp.
View newest version in sPHENIX GitHub at line 51 of file SurfaceStub.hpp
References Acts::s_noBounds.
bool Acts::SurfaceStub::constructedOk () const inline
Simply return true to check a method can be called on a constructed object.
Definition at line 95 of file SurfaceStub.hpp.
View newest version in sPHENIX GitHub at line 95 of file SurfaceStub.hpp
bool Acts::SurfaceStub::globalToLocal (const GeometryContext & , const Vector3D & , const Vector3D & , Vector2D & lpos) const inline final virtual
Global to local transformation.
Implements Acts::Surface.
Definition at line 62 of file SurfaceStub.hpp.
View newest version in sPHENIX GitHub at line 62 of file SurfaceStub.hpp
Intersection Acts::SurfaceStub::intersectionEstimate (const GeometryContext & , const Vector3D & , const Vector3D & , const BoundaryCheck &) const inline final virtual
Straight line intersection schema from parameters.
Implements Acts::Surface.
Definition at line 76 of file SurfaceStub.hpp.
View newest version in sPHENIX GitHub at line 76 of file SurfaceStub.hpp
Referenced by Acts::Test::BOOST_AUTO_TEST_CASE().
void Acts::SurfaceStub::localToGlobal (const GeometryContext & , const Vector2D & , const Vector3D & , Vector3D &) const inline final virtual
Local to global transformation.
Implements Acts::Surface.
Definition at line 56 of file SurfaceStub.hpp.
View newest version in sPHENIX GitHub at line 56 of file SurfaceStub.hpp
std::string Acts::SurfaceStub::name () const inline final virtual
Return properly formatted class name.
Implements Acts::Surface.
Definition at line 92 of file SurfaceStub.hpp.
View newest version in sPHENIX GitHub at line 92 of file SurfaceStub.hpp
const Vector3D Acts::SurfaceStub::normal (const GeometryContext & gctx, const Vector2D &) const inline final virtual
Return method for the normal vector of the surface.
Implements Acts::Surface.
Definition at line 36 of file SurfaceStub.hpp.
View newest version in sPHENIX GitHub at line 36 of file SurfaceStub.hpp
Referenced by normal().
const Vector3D Acts::SurfaceStub::normal (const GeometryContext & gctx, const Vector3D & position) const inline final virtual
Return method for the normal vector of the surface The normal vector can only be generally defined at a given local position It requires a local position to be given (in general)
Parameters
position is the global position where the normal vector is constructed
gctx The current geometry context object, e.g. alignment
Returns
normal vector by value
Reimplemented from Acts::Surface.
Definition at line 41 of file SurfaceStub.hpp.
View newest version in sPHENIX GitHub at line 41 of file SurfaceStub.hpp
References normal().
const Vector3D Acts::SurfaceStub::normal (const GeometryContext & gctx) const inline final virtual
Return method for the normal vector of the surface
It will return a normal vector at the center() position
Parameters
gctx The current geometry context object, e.g. alignment
Returns
normal vector by value
Reimplemented from Acts::Surface.
Definition at line 46 of file SurfaceStub.hpp.
View newest version in sPHENIX GitHub at line 46 of file SurfaceStub.hpp
double Acts::SurfaceStub::pathCorrection (const GeometryContext & , const Vector3D & , const Vector3D &) const inline final virtual
Calculation of the path correction for incident.
Implements Acts::Surface.
Definition at line 69 of file SurfaceStub.hpp.
View newest version in sPHENIX GitHub at line 69 of file SurfaceStub.hpp
Polyhedron Acts::SurfaceStub::polyhedronRepresentation (const GeometryContext & , size_t) const inline final virtual
Return a Polyhedron for the surfaces.
Implements Acts::Surface.
Definition at line 98 of file SurfaceStub.hpp.
View newest version in sPHENIX GitHub at line 98 of file SurfaceStub.hpp
SurfaceType Acts::SurfaceStub::type () const inline final virtual
Return method for the Surface type to avoid dynamic casts.
Implements Acts::Surface.
Definition at line 33 of file SurfaceStub.hpp.
View newest version in sPHENIX GitHub at line 33 of file SurfaceStub.hpp
References Acts::Surface::Other.
Member Data Documentation
std::shared_ptr<const PlanarBounds> Acts::SurfaceStub::m_bounds private
the bounds of this surface
Definition at line 109 of file SurfaceStub.hpp.
View newest version in sPHENIX GitHub at line 109 of file SurfaceStub.hpp
The documentation for this class was generated from the following file:
fun4all_acts/blob/master/Tests/UnitTests/Core/Surfaces/SurfaceStub.hpp