EIC Software: EicMediaHub Class Reference
EicMediaHub Class Reference
#include <EicRoot/blob/master/eic/field/EicMediaHub.h>
Public Member Functions
EicMediaHub (char *mediaName)
EicMediaHub ()
~EicMediaHub ()
TGeoMedium * GetMedium (const char *medium)
Media creation/access method.
void Init ()
int importMediaMapFile (TString &mediaMapFileName)
Public Attributes
TGeoMedium * fSingleMedium
TString fMediaName
Private Attributes
FairGeoLoader * geoLoad
FairGeoInterface * geoFace
FairGeoMedia * Media
FairGeoBuilder * geobuild
Friends
class EicStlFile
Detailed Description
Definition at line 30 of file EicMediaHub.h.
View newest version in sPHENIX GitHub at line 30 of file EicMediaHub.h
Constructor & Destructor Documentation
EicMediaHub::EicMediaHub (char * mediaName)
Definition at line 19 of file EicMediaHub.cxx.
View newest version in sPHENIX GitHub at line 19 of file EicMediaHub.cxx
References fMediaName.
EicMediaHub::EicMediaHub () inline
Definition at line 36 of file EicMediaHub.h.
View newest version in sPHENIX GitHub at line 36 of file EicMediaHub.h
EicMediaHub::~EicMediaHub () inline
Definition at line 41 of file EicMediaHub.h.
View newest version in sPHENIX GitHub at line 41 of file EicMediaHub.h
Member Function Documentation
TGeoMedium * EicMediaHub::GetMedium (const char * medium)
Media creation/access method.
Note
Need to unify with EicGeoParDataHelper code at some point
Definition at line 139 of file EicMediaHub.cxx.
View newest version in sPHENIX GitHub at line 139 of file EicMediaHub.cxx
References FairGeoBuilder::createMedium(), geobuild, FairGeoMedia::getMedium(), and Media.
Referenced by EicBeamLineElementMap::ConstructGeometry(), EicBeamLineElementGrad::ConstructGeometry(), EicStlFactory::ImportAsciiStlSlpFile(), importMediaMapFile(), and Init().
int EicMediaHub::importMediaMapFile (TString & mediaMapFileName)
Media map import routine
Note
3-d parameter to EicCadFile(const char *, char *, char *) constructor can be name of media remapping file rather than a single media name; this routine is supposed to read in and parse this file;
Definition at line 31 of file EicMediaHub.cxx.
View newest version in sPHENIX GitHub at line 31 of file EicMediaHub.cxx
References buffer, color, EicStlKeyCompare(), and GetMedium().
Referenced by Init().
void EicMediaHub::Init ()
Definition at line 80 of file EicMediaHub.cxx.
View newest version in sPHENIX GitHub at line 80 of file EicMediaHub.cxx
References ExpandedFileName(), FairLogger::Fatal(), fMediaName, fSingleMedium, geobuild, geoFace, geoLoad, FairGeoLoader::getGeoBuilder(), FairGeoLoader::getGeoInterface(), FairLogger::GetLogger(), FairGeoInterface::getMedia(), GetMedium(), importMediaMapFile(), FairGeoLoader::Instance(), Media, and MESSAGE_ORIGIN.
Referenced by EicCadWizard::AssembleRootFiles(), EicBeamLineElementMap::ConstructGeometry(), EicBeamLineElementGrad::ConstructGeometry(), EicCadFile::ConstructGeometry(), EicCadWizard::CreateBooleanSolidRootFile(), EicCadWizard::CreateGhostSolidRootFile(), and EicCadWizard::CreateStlSolidRootFile().
Friends And Related Function Documentation
friend class EicStlFile friend
Definition at line 32 of file EicMediaHub.h.
View newest version in sPHENIX GitHub at line 32 of file EicMediaHub.h
Member Data Documentation
TString EicMediaHub::fMediaName
Either a single medium or media transcript file
Definition at line 52 of file EicMediaHub.h.
View newest version in sPHENIX GitHub at line 52 of file EicMediaHub.h
Referenced by EicCadFile::ConstructGeometry(), EicMediaHub(), and Init().
TGeoMedium* EicMediaHub::fSingleMedium
A single medium pointer to be used (if not 0) for all volumes of this STL file
Definition at line 49 of file EicMediaHub.h.
View newest version in sPHENIX GitHub at line 49 of file EicMediaHub.h
Referenced by EicCadFile::ConstructGeometry(), EicCadWizard::CreateBooleanSolidRootFile(), EicCadWizard::CreateGhostSolidRootFile(), EicStlFactory::CreateRootFile(), EicStlFactory::EicStlFactory(), EicStlFactory::ImportAsciiStlSlpFile(), EicStlFactory::ImportBinaryStlFile(), and Init().
FairGeoBuilder* EicMediaHub::geobuild private
FairRoot geo loader media builder pointer
Definition at line 71 of file EicMediaHub.h.
View newest version in sPHENIX GitHub at line 71 of file EicMediaHub.h
Referenced by GetMedium(), and Init().
FairGeoInterface* EicMediaHub::geoFace private
FairRoot geo interface pointer
Definition at line 67 of file EicMediaHub.h.
View newest version in sPHENIX GitHub at line 67 of file EicMediaHub.h
Referenced by Init().
FairGeoLoader* EicMediaHub::geoLoad private
Duplicate of the FairRoot geo loader singleton pointer
Definition at line 65 of file EicMediaHub.h.
View newest version in sPHENIX GitHub at line 65 of file EicMediaHub.h
Referenced by Init().
FairGeoMedia* EicMediaHub::Media private
Definition at line 69 of file EicMediaHub.h.
View newest version in sPHENIX GitHub at line 69 of file EicMediaHub.h
Referenced by GetMedium(), and Init().
The documentation for this class was generated from the following files:
EicRoot/blob/master/eic/field/EicMediaHub.h
EicRoot/blob/master/eic/field/EicMediaHub.cxx