EIC Software: G4EicDircSteppingAction Class Reference
G4EicDircSteppingAction Class Reference
#include <fun4all_eicdetectors/blob/master/simulation/g4simulation/g4eicdirc/G4EicDircSteppingAction.h>
Public Member Functions
G4EicDircSteppingAction (G4EicDircDetector *, const PHParameters *parameters)
constructor
~G4EicDircSteppingAction () override
destructor
bool UserSteppingAction (const G4Step *, bool) override
stepping action
void SetInterfacePointers (PHCompositeNode *) override
reimplemented from base class
void SetHitNodeName (const std::string &nam)
void SetAbsorberNodeName (const std::string &nam)
void SetSupportNodeName (const std::string &nam)
Public Member Functions inherited from PHG4SteppingAction
PHG4SteppingAction (const std::string &name, const int i=0)
virtual ~PHG4SteppingAction ()
virtual void Verbosity (const int i)
virtual int Verbosity () const
virtual int Init ()
virtual double GetScintLightYield (const G4Step *step)
get scintillation photon count. It require a custom set SCINTILLATIONYIELD property to work
virtual double GetVisibleEnergyDeposition (const G4Step *step)
get amount of energy that can make scintillation light, in Unit of GeV.
virtual void StoreLocalCoordinate (PHG4Hit *hit, const G4Step *step, const bool do_prepoint, const bool do_postpoint)
Extract local coordinate of the hit and save to PHG4Hit.
virtual void Print (const std::string &) const
std::string GetName () const
void SetName (const std::string &name)
virtual void SetLightCorrection (const double inner_radius, const double inner_corr, const double outer_radius, const double outer_corr)
virtual double GetLightCorrection (const double r) const
virtual double GetLightCorrection (const double xpos, const double ypos) const
virtual bool ValidCorrection () const
virtual void SetHitNodeName (const std::string &, const std::string &)
Set the G4HIT node names from Subsystem rather than constructing your own.
Public Attributes
std::vector< Int_t > vector_nid
std::vector< Int_t > vector_trackid
Private Attributes
G4EicDircDetector * m_Detector = nullptr
pointer to the detector
const PHParameters * m_Params
PHG4HitContainer * m_HitContainer = nullptr
pointer to hit container
PHG4HitContainer * m_AbsorberHitContainer = nullptr
PHG4HitContainer * m_SupportHitContainer = nullptr
PHG4Hit * m_Hit = nullptr
G4VPhysicalVolume * m_SaveVolPre = nullptr
G4VPhysicalVolume * m_SaveVolPost = nullptr
int m_SaveTrackId = -1
int m_SavePreStepStatus = -1
int m_SavePostStepStatus = -1
int m_ActiveFlag = 0
int m_BlackHoleFlag = 0
std::string m_HitNodeName
std::string m_AbsorberNodeName
std::string m_SupportNodeName
Detailed Description
Definition at line 22 of file G4EicDircSteppingAction.h.
View newest version in sPHENIX GitHub at line 22 of file G4EicDircSteppingAction.h
Constructor & Destructor Documentation
G4EicDircSteppingAction::G4EicDircSteppingAction (G4EicDircDetector * detector, const PHParameters * parameters)
constructor
Definition at line 47 of file G4EicDircSteppingAction.cc.
View newest version in sPHENIX GitHub at line 47 of file G4EicDircSteppingAction.cc
G4EicDircSteppingAction::~G4EicDircSteppingAction () override
destructor
Definition at line 57 of file G4EicDircSteppingAction.cc.
View newest version in sPHENIX GitHub at line 57 of file G4EicDircSteppingAction.cc
References m_Hit.
Member Function Documentation
void G4EicDircSteppingAction::SetAbsorberNodeName (const std::string & nam) inline
Definition at line 38 of file G4EicDircSteppingAction.h.
View newest version in sPHENIX GitHub at line 38 of file G4EicDircSteppingAction.h
References m_AbsorberNodeName.
Referenced by G4EicDircSubsystem::InitRunSubsystem().
void G4EicDircSteppingAction::SetHitNodeName (const std::string & nam) inline
Definition at line 37 of file G4EicDircSteppingAction.h.
View newest version in sPHENIX GitHub at line 37 of file G4EicDircSteppingAction.h
References m_HitNodeName.
Referenced by G4EicDircSubsystem::InitRunSubsystem().
void G4EicDircSteppingAction::SetInterfacePointers (PHCompositeNode * topNode) override virtual
reimplemented from base class
Reimplemented from PHG4SteppingAction.
Definition at line 278 of file G4EicDircSteppingAction.cc.
View newest version in sPHENIX GitHub at line 278 of file G4EicDircSteppingAction.cc
References m_AbsorberHitContainer, m_AbsorberNodeName, m_HitContainer, m_HitNodeName, m_SupportHitContainer, m_SupportNodeName, and PHG4SteppingAction::Verbosity().
void G4EicDircSteppingAction::SetSupportNodeName (const std::string & nam) inline
Definition at line 39 of file G4EicDircSteppingAction.h.
View newest version in sPHENIX GitHub at line 39 of file G4EicDircSteppingAction.h
References m_SupportNodeName.
Referenced by G4EicDircSubsystem::InitRunSubsystem().
bool G4EicDircSteppingAction::UserSteppingAction (const G4Step * aStep, bool was_used) override virtual
stepping action
Implements PHG4SteppingAction.
Definition at line 67 of file G4EicDircSteppingAction.cc.
View newest version in sPHENIX GitHub at line 67 of file G4EicDircSteppingAction.cc
References PHG4HitContainer::AddHit(), Acts::UnitConstants::cm, exit(), PHG4Hit::get_edep(), PHG4Hit::get_eion(), PHG4Hit::get_x(), PHG4SteppingAction::GetName(), PHG4StepStatusDecode::GetStepStatus(), Acts::UnitConstants::GeV, G4EicDircDetector::IsInDetector(), m_ActiveFlag, m_BlackHoleFlag, m_Detector, m_Hit, m_HitContainer, m_SavePostStepStatus, m_SavePreStepStatus, m_SaveTrackId, m_SaveVolPost, m_SaveVolPre, p, PHG4Hit::Reset(), PHG4Hit::set_edep(), PHG4Hit::set_eion(), PHG4Hit::set_px(), PHG4Hit::set_py(), PHG4Hit::set_pz(), PHG4Hit::set_shower_id(), PHG4Hit::set_t(), PHG4Hit::set_trkid(), PHG4Hit::set_x(), PHG4Hit::set_y(), PHG4Hit::set_z(), and Acts::Test::volume.
Member Data Documentation
PHG4HitContainer* G4EicDircSteppingAction::m_AbsorberHitContainer = nullptr private
Definition at line 54 of file G4EicDircSteppingAction.h.
View newest version in sPHENIX GitHub at line 54 of file G4EicDircSteppingAction.h
Referenced by SetInterfacePointers().
std::string G4EicDircSteppingAction::m_AbsorberNodeName private
Definition at line 71 of file G4EicDircSteppingAction.h.
View newest version in sPHENIX GitHub at line 71 of file G4EicDircSteppingAction.h
Referenced by SetAbsorberNodeName(), and SetInterfacePointers().
int G4EicDircSteppingAction::m_ActiveFlag = 0 private
Definition at line 65 of file G4EicDircSteppingAction.h.
View newest version in sPHENIX GitHub at line 65 of file G4EicDircSteppingAction.h
Referenced by UserSteppingAction().
int G4EicDircSteppingAction::m_BlackHoleFlag = 0 private
Definition at line 66 of file G4EicDircSteppingAction.h.
View newest version in sPHENIX GitHub at line 66 of file G4EicDircSteppingAction.h
Referenced by UserSteppingAction().
G4EicDircDetector* G4EicDircSteppingAction::m_Detector = nullptr private
pointer to the detector
Definition at line 50 of file G4EicDircSteppingAction.h.
View newest version in sPHENIX GitHub at line 50 of file G4EicDircSteppingAction.h
Referenced by UserSteppingAction().
PHG4Hit* G4EicDircSteppingAction::m_Hit = nullptr private
Definition at line 56 of file G4EicDircSteppingAction.h.
View newest version in sPHENIX GitHub at line 56 of file G4EicDircSteppingAction.h
Referenced by UserSteppingAction(), and ~G4EicDircSteppingAction().
PHG4HitContainer* G4EicDircSteppingAction::m_HitContainer = nullptr private
pointer to hit container
Definition at line 53 of file G4EicDircSteppingAction.h.
View newest version in sPHENIX GitHub at line 53 of file G4EicDircSteppingAction.h
Referenced by SetInterfacePointers(), and UserSteppingAction().
std::string G4EicDircSteppingAction::m_HitNodeName private
Definition at line 70 of file G4EicDircSteppingAction.h.
View newest version in sPHENIX GitHub at line 70 of file G4EicDircSteppingAction.h
Referenced by SetHitNodeName(), and SetInterfacePointers().
const PHParameters* G4EicDircSteppingAction::m_Params private
Definition at line 51 of file G4EicDircSteppingAction.h.
View newest version in sPHENIX GitHub at line 51 of file G4EicDircSteppingAction.h
int G4EicDircSteppingAction::m_SavePostStepStatus = -1 private
Definition at line 64 of file G4EicDircSteppingAction.h.
View newest version in sPHENIX GitHub at line 64 of file G4EicDircSteppingAction.h
Referenced by UserSteppingAction().
int G4EicDircSteppingAction::m_SavePreStepStatus = -1 private
Definition at line 63 of file G4EicDircSteppingAction.h.
View newest version in sPHENIX GitHub at line 63 of file G4EicDircSteppingAction.h
Referenced by UserSteppingAction().
int G4EicDircSteppingAction::m_SaveTrackId = -1 private
Definition at line 62 of file G4EicDircSteppingAction.h.
View newest version in sPHENIX GitHub at line 62 of file G4EicDircSteppingAction.h
Referenced by UserSteppingAction().
G4VPhysicalVolume* G4EicDircSteppingAction::m_SaveVolPost = nullptr private
Definition at line 61 of file G4EicDircSteppingAction.h.
View newest version in sPHENIX GitHub at line 61 of file G4EicDircSteppingAction.h
Referenced by UserSteppingAction().
G4VPhysicalVolume* G4EicDircSteppingAction::m_SaveVolPre = nullptr private
Definition at line 60 of file G4EicDircSteppingAction.h.
View newest version in sPHENIX GitHub at line 60 of file G4EicDircSteppingAction.h
Referenced by UserSteppingAction().
PHG4HitContainer* G4EicDircSteppingAction::m_SupportHitContainer = nullptr private
Definition at line 55 of file G4EicDircSteppingAction.h.
View newest version in sPHENIX GitHub at line 55 of file G4EicDircSteppingAction.h
Referenced by SetInterfacePointers().
std::string G4EicDircSteppingAction::m_SupportNodeName private
Definition at line 72 of file G4EicDircSteppingAction.h.
View newest version in sPHENIX GitHub at line 72 of file G4EicDircSteppingAction.h
Referenced by SetInterfacePointers(), and SetSupportNodeName().
std::vector<Int_t> G4EicDircSteppingAction::vector_nid
Definition at line 41 of file G4EicDircSteppingAction.h.
View newest version in sPHENIX GitHub at line 41 of file G4EicDircSteppingAction.h
std::vector<Int_t> G4EicDircSteppingAction::vector_trackid
Definition at line 42 of file G4EicDircSteppingAction.h.
View newest version in sPHENIX GitHub at line 42 of file G4EicDircSteppingAction.h
The documentation for this class was generated from the following files:
fun4all_eicdetectors/blob/master/simulation/g4simulation/g4eicdirc/G4EicDircSteppingAction.h
fun4all_eicdetectors/blob/master/simulation/g4simulation/g4eicdirc/G4EicDircSteppingAction.cc