EIC Software: g4lblvtx/blob/master/macros/G4_Jets.C File Reference
G4_Jets.C File Reference
#include <fun4all/Fun4AllServer.h>
#include <g4jets/ClusterJetInput.h>
#include <g4jets/FastJetAlgo.h>
#include <g4jets/JetReco.h>
#include <g4jets/TowerJetInput.h>
#include <g4jets/TrackJetInput.h>
#include <g4jets/TruthJetInput.h>
#include <g4eval/JetEvaluator.h>
Functions
void JetInit ()
void Jet_Reco (int verbosity=0)
void Jet_Eval (std::string outfilename="g4jets_eval.root", int verbosity=0)
Function Documentation
void Jet_Eval (std::string outfilename = "g4jets_eval.root", int verbosity = 0)
Definition at line 92 of file G4_Jets.C.
View newest version in sPHENIX GitHub at line 92 of file G4_Jets.C
References Fun4AllServer::instance(), Fun4AllServer::registerSubsystem(), and Fun4AllBase::Verbosity().
void Jet_Reco (int verbosity = 0)
Definition at line 17 of file G4_Jets.C.
View newest version in sPHENIX GitHub at line 17 of file G4_Jets.C
References JetReco::add_algo(), JetReco::add_input(), Jet::ANTIKT, Fun4AllServer::instance(), Jet::PARTICLE, Fun4AllServer::registerSubsystem(), JetReco::set_algo_node(), JetReco::set_input_node(), Jet::TRACK, and Fun4AllBase::Verbosity().
void JetInit ()
Definition at line 15 of file G4_Jets.C.
View newest version in sPHENIX GitHub at line 15 of file G4_Jets.C