EIC Software: FW::RootMaterialWriter Class Reference
FW::RootMaterialWriter Class Reference
Material decorator from Root format.
#include <fun4all_acts/blob/master/Examples/Io/Root/include/ACTFW/Io/Root/RootMaterialWriter.hpp>
Classes
class Config
Public Member Functions
RootMaterialWriter (const Config &cfg)
~RootMaterialWriter ()=default
Virtual destructor.
void write (const Acts::DetectorMaterialMaps &detMaterial)
void write (const Acts::TrackingGeometry &tGeometry)
Private Member Functions
void collectMaterial (const Acts::TrackingVolume &tVolume, Acts::DetectorMaterialMaps &detMatMap)
void collectMaterial (const Acts::Layer &tLayer, Acts::DetectorMaterialMaps &detMatMap)
const Acts::Logger & logger () const
Private access to the logging instance.
Private Attributes
Config m_cfg
The config class.
Detailed Description
Material decorator from Root format.
This reads in material maps for surfaces and volumes from a root file
Definition at line 43 of file RootMaterialWriter.hpp.
View newest version in sPHENIX GitHub at line 43 of file RootMaterialWriter.hpp
Constructor & Destructor Documentation
FW::RootMaterialWriter::RootMaterialWriter (const Config & cfg)
Constructor
Parameters
cfg The configuration struct
Definition at line 19 of file RootMaterialWriter.cpp.
View newest version in sPHENIX GitHub at line 19 of file RootMaterialWriter.cpp
References FW::RootMaterialWriter::Config::fileName, FW::RootMaterialWriter::Config::folderNameBase, FW::RootMaterialWriter::Config::logger, m_cfg, and FW::RootMaterialWriter::Config::name.
FW::RootMaterialWriter::~RootMaterialWriter () default
Virtual destructor.
Member Function Documentation
void FW::RootMaterialWriter::collectMaterial (const Acts::TrackingVolume & tVolume, Acts::DetectorMaterialMaps & detMatMap) private
Collect the material from the tracking geometry
Parameters
tVolume The TrackingVolume for the material to be collected
[in,out] detMatMap the map to be filled
Definition at line 173 of file RootMaterialWriter.cpp.
View newest version in sPHENIX GitHub at line 173 of file RootMaterialWriter.cpp
References Acts::BinnedArray< T >::arrayObjects(), Acts::TrackingVolume::boundarySurfaces(), Acts::TrackingVolume::confinedLayers(), Acts::TrackingVolume::confinedVolumes(), Acts::GeometryObject::geoID(), and Acts::TrackingVolume::volumeMaterialSharedPtr().
void FW::RootMaterialWriter::collectMaterial (const Acts::Layer & tLayer, Acts::DetectorMaterialMaps & detMatMap) private
Collect the material from the tracking geometry
Parameters
tLayer The TrackingVolume for the material to be collected
[in,out] detMatMap the map to be filled
Definition at line 206 of file RootMaterialWriter.cpp.
View newest version in sPHENIX GitHub at line 206 of file RootMaterialWriter.cpp
References Acts::Layer::approachDescriptor(), Acts::ApproachDescriptor::containedSurfaces(), Acts::Layer::surfaceArray(), Acts::Surface::surfaceMaterialSharedPtr(), Acts::Layer::surfaceRepresentation(), and Acts::SurfaceArray::surfaces().
const Acts::Logger& FW::RootMaterialWriter::logger () const inline private
Private access to the logging instance.
Definition at line 151 of file RootMaterialWriter.hpp.
View newest version in sPHENIX GitHub at line 151 of file RootMaterialWriter.hpp
References FW::RootMaterialWriter::Config::logger, and m_cfg.
void FW::RootMaterialWriter::write (const Acts::DetectorMaterialMaps & detMaterial)
Write out the material map
Parameters
detMaterial is the SurfaceMaterial and VolumeMaterial maps
Definition at line 34 of file RootMaterialWriter.cpp.
View newest version in sPHENIX GitHub at line 34 of file RootMaterialWriter.cpp
References ACTS_VERBOSE, Acts::GeometryID::approach(), b, Acts::BinUtility::binningData(), Acts::BinUtility::bins(), charm_jet_strange_helicity::bins, Acts::BinnedSurfaceMaterial::binUtility(), Acts::GeometryID::boundary(), Acts::GeometryID::layer(), Acts::ISurfaceMaterial::materialProperties(), max, min, n, Acts::GeometryID::sensitive(), t, nlohmann::to_string(), v, value, and Acts::GeometryID::volume().
Referenced by processGeometry().
void FW::RootMaterialWriter::write (const Acts::TrackingGeometry & tGeometry)
Write out the material map from Geometry
Parameters
tGeometry is the TrackingGeometry
Definition at line 162 of file RootMaterialWriter.cpp.
View newest version in sPHENIX GitHub at line 162 of file RootMaterialWriter.cpp
References Acts::TrackingGeometry::highestTrackingVolume(), Acts::Test::hVolume, and tree::write().
Member Data Documentation
Config FW::RootMaterialWriter::m_cfg private
The config class.
Definition at line 148 of file RootMaterialWriter.hpp.
View newest version in sPHENIX GitHub at line 148 of file RootMaterialWriter.hpp
Referenced by logger(), and RootMaterialWriter().
The documentation for this class was generated from the following files:
fun4all_acts/blob/master/Examples/Io/Root/include/ACTFW/Io/Root/RootMaterialWriter.hpp
fun4all_acts/blob/master/Examples/Io/Root/src/RootMaterialWriter.cpp