EIC Software: EICG4B0ECALSteppingAction Class Reference
EICG4B0ECALSteppingAction Class Reference
#include <fun4all_eicdetectors/blob/master/simulation/g4simulation/g4b0ecal/EICG4B0ECALSteppingAction.h>
Public Member Functions
EICG4B0ECALSteppingAction (EICG4B0ECALSubsystem *subsys, EICG4B0ECALDetector *detector, const PHParameters *parameters)
constructor
virtual ~EICG4B0ECALSteppingAction () override
destructor
virtual bool UserSteppingAction (const G4Step *, bool) override
stepping action
virtual void SetInterfacePointers (PHCompositeNode *) override
reimplemented from base class
virtual void SaveLightYield (const int i=1)
virtual bool hasMotherSubsystem () const
virtual void SaveAllHits (bool i=true)
virtual void HitNodeName (const std::string &name)
Public Member Functions inherited from PHG4SteppingAction
PHG4SteppingAction (const std::string &name, const int i=0)
virtual ~PHG4SteppingAction ()
virtual void Verbosity (const int i)
virtual int Verbosity () const
virtual int Init ()
virtual double GetScintLightYield (const G4Step *step)
get scintillation photon count. It require a custom set SCINTILLATIONYIELD property to work
virtual double GetVisibleEnergyDeposition (const G4Step *step)
get amount of energy that can make scintillation light, in Unit of GeV.
virtual void StoreLocalCoordinate (PHG4Hit *hit, const G4Step *step, const bool do_prepoint, const bool do_postpoint)
Extract local coordinate of the hit and save to PHG4Hit.
virtual void Print (const std::string &) const
std::string GetName () const
void SetName (const std::string &name)
virtual void SetLightCorrection (const double inner_radius, const double inner_corr, const double outer_radius, const double outer_corr)
virtual double GetLightCorrection (const double r) const
virtual double GetLightCorrection (const double xpos, const double ypos) const
virtual bool ValidCorrection () const
virtual void SetHitNodeName (const std::string &, const std::string &)
Set the G4HIT node names from Subsystem rather than constructing your own.
Private Member Functions
int FindTowerIndexFromPosition (G4StepPoint *prePoint, int &j, int &k)
Private Attributes
EICG4B0ECALSubsystem * m_Subsystem
pointer to the detector
EICG4B0ECALDetector * m_Detector
const PHParameters * m_Params
PHG4HitContainer * m_HitContainer = nullptr
pointer to hit container
PHG4Hit * m_Hit
PHG4Shower * m_SaveShower
G4VPhysicalVolume * m_SaveVolPre
G4VPhysicalVolume * m_SaveVolPost
bool m_SaveAllHitsFlag = false
int m_SaveLightYieldFlag
int m_SaveTrackId
int m_SavePreStepStatus
int m_SavePostStepStatus
int m_ActiveFlag = 0
int m_BlackHoleFlag = 0
int m_UseG4StepsFlag
double m_Zmin
double m_Zmax
double m_Tmin
double m_Tmax
double m_EdepSum
double m_EabsSum
std::string m_HitNodeName
Detailed Description
Definition at line 23 of file EICG4B0ECALSteppingAction.h.
View newest version in sPHENIX GitHub at line 23 of file EICG4B0ECALSteppingAction.h
Constructor & Destructor Documentation
EICG4B0ECALSteppingAction::EICG4B0ECALSteppingAction (EICG4B0ECALSubsystem * subsys, EICG4B0ECALDetector * detector, const PHParameters * parameters)
constructor
Definition at line 66 of file EICG4B0ECALSteppingAction.cc.
View newest version in sPHENIX GitHub at line 66 of file EICG4B0ECALSteppingAction.cc
References Acts::UnitConstants::cm, m_Zmax, and m_Zmin.
EICG4B0ECALSteppingAction::~EICG4B0ECALSteppingAction () override virtual
destructor
Definition at line 96 of file EICG4B0ECALSteppingAction.cc.
View newest version in sPHENIX GitHub at line 96 of file EICG4B0ECALSteppingAction.cc
References m_Hit.
Member Function Documentation
int EICG4B0ECALSteppingAction::FindTowerIndexFromPosition (G4StepPoint * prePoint, int & j, int & k) private
Definition at line 414 of file EICG4B0ECALSteppingAction.cc.
View newest version in sPHENIX GitHub at line 414 of file EICG4B0ECALSteppingAction.cc
References Acts::UnitConstants::cm, PHParameters::get_double_param(), m_Params, and G4BECAL::radius.
Referenced by UserSteppingAction().
bool EICG4B0ECALSteppingAction::hasMotherSubsystem () const virtual
Definition at line 440 of file EICG4B0ECALSteppingAction.cc.
View newest version in sPHENIX GitHub at line 440 of file EICG4B0ECALSteppingAction.cc
References PHG4Subsystem::GetMotherSubsystem(), and m_Subsystem.
Referenced by UserSteppingAction().
virtual void EICG4B0ECALSteppingAction::HitNodeName (const std::string & name) inline virtual
Definition at line 44 of file EICG4B0ECALSteppingAction.h.
View newest version in sPHENIX GitHub at line 44 of file EICG4B0ECALSteppingAction.h
References m_HitNodeName, and name.
virtual void EICG4B0ECALSteppingAction::SaveAllHits (bool i = true) inline virtual
Definition at line 42 of file EICG4B0ECALSteppingAction.h.
View newest version in sPHENIX GitHub at line 42 of file EICG4B0ECALSteppingAction.h
References m_SaveAllHitsFlag.
virtual void EICG4B0ECALSteppingAction::SaveLightYield (const int i = 1) inline virtual
Definition at line 38 of file EICG4B0ECALSteppingAction.h.
View newest version in sPHENIX GitHub at line 38 of file EICG4B0ECALSteppingAction.h
References m_SaveLightYieldFlag.
void EICG4B0ECALSteppingAction::SetInterfacePointers (PHCompositeNode * topNode) override virtual
reimplemented from base class
Reimplemented from PHG4SteppingAction.
Definition at line 430 of file EICG4B0ECALSteppingAction.cc.
View newest version in sPHENIX GitHub at line 430 of file EICG4B0ECALSteppingAction.cc
References m_HitContainer, and m_HitNodeName.
bool EICG4B0ECALSteppingAction::UserSteppingAction (const G4Step * aStep, bool was_used) override virtual
stepping action
m_EdepSum += edep; if (whichactive > 0) { m_EionSum += eion; }
Implements PHG4SteppingAction.
Definition at line 107 of file EICG4B0ECALSteppingAction.cc.
View newest version in sPHENIX GitHub at line 107 of file EICG4B0ECALSteppingAction.cc
References PHG4Shower::add_g4hit_id(), PHG4HitContainer::AddHit(), Acts::UnitConstants::cm, FindTowerIndexFromPosition(), PHG4Hit::get_edep(), PHG4Hit::get_eion(), PHG4Hit::get_hit_id(), EICG4B0ECALDetector::get_Layer(), PHG4Hit::get_light_yield(), PHG4Hit::get_x(), PHG4Hit::get_z(), PHG4HitContainer::GetID(), PHG4SteppingAction::GetName(), PHG4StepStatusDecode::GetStepStatus(), PHG4SteppingAction::GetVisibleEnergyDeposition(), Acts::UnitConstants::GeV, hasMotherSubsystem(), EICG4B0ECALDetector::IsInDetector(), m_ActiveFlag, m_BlackHoleFlag, m_Detector, m_EabsSum, m_EdepSum, m_Hit, m_HitContainer, m_SaveAllHitsFlag, m_SaveLightYieldFlag, m_SavePostStepStatus, m_SavePreStepStatus, m_SaveShower, m_SaveTrackId, m_SaveVolPost, m_SaveVolPre, m_Tmax, m_Tmin, m_UseG4StepsFlag, m_Zmax, m_Zmin, p, PHG4Hit::Reset(), PHG4Hit::set_edep(), PHG4Hit::set_eion(), PHG4Hit::set_hit_type(), PHG4Hit::set_index_j(), PHG4Hit::set_index_k(), PHG4Hit::set_layer(), PHG4Hit::set_light_yield(), PHG4Hit::set_px(), PHG4Hit::set_py(), PHG4Hit::set_pz(), PHG4Hit::set_shower_id(), PHG4Hit::set_t(), PHG4Hit::set_trkid(), PHG4Hit::set_x(), PHG4Hit::set_y(), PHG4Hit::set_z(), EICG4B0ECALDetector::SuperDetector(), and Acts::Test::volume.
Member Data Documentation
int EICG4B0ECALSteppingAction::m_ActiveFlag = 0 private
Definition at line 66 of file EICG4B0ECALSteppingAction.h.
View newest version in sPHENIX GitHub at line 66 of file EICG4B0ECALSteppingAction.h
Referenced by UserSteppingAction().
int EICG4B0ECALSteppingAction::m_BlackHoleFlag = 0 private
Definition at line 67 of file EICG4B0ECALSteppingAction.h.
View newest version in sPHENIX GitHub at line 67 of file EICG4B0ECALSteppingAction.h
Referenced by UserSteppingAction().
EICG4B0ECALDetector* EICG4B0ECALSteppingAction::m_Detector private
Definition at line 51 of file EICG4B0ECALSteppingAction.h.
View newest version in sPHENIX GitHub at line 51 of file EICG4B0ECALSteppingAction.h
Referenced by UserSteppingAction().
double EICG4B0ECALSteppingAction::m_EabsSum private
Definition at line 74 of file EICG4B0ECALSteppingAction.h.
View newest version in sPHENIX GitHub at line 74 of file EICG4B0ECALSteppingAction.h
Referenced by UserSteppingAction().
double EICG4B0ECALSteppingAction::m_EdepSum private
Definition at line 73 of file EICG4B0ECALSteppingAction.h.
View newest version in sPHENIX GitHub at line 73 of file EICG4B0ECALSteppingAction.h
Referenced by UserSteppingAction().
PHG4Hit* EICG4B0ECALSteppingAction::m_Hit private
Definition at line 56 of file EICG4B0ECALSteppingAction.h.
View newest version in sPHENIX GitHub at line 56 of file EICG4B0ECALSteppingAction.h
Referenced by UserSteppingAction(), and ~EICG4B0ECALSteppingAction().
PHG4HitContainer* EICG4B0ECALSteppingAction::m_HitContainer = nullptr private
pointer to hit container
Definition at line 55 of file EICG4B0ECALSteppingAction.h.
View newest version in sPHENIX GitHub at line 55 of file EICG4B0ECALSteppingAction.h
Referenced by SetInterfacePointers(), and UserSteppingAction().
std::string EICG4B0ECALSteppingAction::m_HitNodeName private
Definition at line 75 of file EICG4B0ECALSteppingAction.h.
View newest version in sPHENIX GitHub at line 75 of file EICG4B0ECALSteppingAction.h
Referenced by HitNodeName(), and SetInterfacePointers().
const PHParameters* EICG4B0ECALSteppingAction::m_Params private
Definition at line 53 of file EICG4B0ECALSteppingAction.h.
View newest version in sPHENIX GitHub at line 53 of file EICG4B0ECALSteppingAction.h
Referenced by FindTowerIndexFromPosition().
bool EICG4B0ECALSteppingAction::m_SaveAllHitsFlag = false private
Definition at line 61 of file EICG4B0ECALSteppingAction.h.
View newest version in sPHENIX GitHub at line 61 of file EICG4B0ECALSteppingAction.h
Referenced by SaveAllHits(), and UserSteppingAction().
int EICG4B0ECALSteppingAction::m_SaveLightYieldFlag private
Definition at line 62 of file EICG4B0ECALSteppingAction.h.
View newest version in sPHENIX GitHub at line 62 of file EICG4B0ECALSteppingAction.h
Referenced by SaveLightYield(), and UserSteppingAction().
int EICG4B0ECALSteppingAction::m_SavePostStepStatus private
Definition at line 65 of file EICG4B0ECALSteppingAction.h.
View newest version in sPHENIX GitHub at line 65 of file EICG4B0ECALSteppingAction.h
Referenced by UserSteppingAction().
int EICG4B0ECALSteppingAction::m_SavePreStepStatus private
Definition at line 64 of file EICG4B0ECALSteppingAction.h.
View newest version in sPHENIX GitHub at line 64 of file EICG4B0ECALSteppingAction.h
Referenced by UserSteppingAction().
PHG4Shower* EICG4B0ECALSteppingAction::m_SaveShower private
Definition at line 57 of file EICG4B0ECALSteppingAction.h.
View newest version in sPHENIX GitHub at line 57 of file EICG4B0ECALSteppingAction.h
Referenced by UserSteppingAction().
int EICG4B0ECALSteppingAction::m_SaveTrackId private
Definition at line 63 of file EICG4B0ECALSteppingAction.h.
View newest version in sPHENIX GitHub at line 63 of file EICG4B0ECALSteppingAction.h
Referenced by UserSteppingAction().
G4VPhysicalVolume* EICG4B0ECALSteppingAction::m_SaveVolPost private
Definition at line 59 of file EICG4B0ECALSteppingAction.h.
View newest version in sPHENIX GitHub at line 59 of file EICG4B0ECALSteppingAction.h
Referenced by UserSteppingAction().
G4VPhysicalVolume* EICG4B0ECALSteppingAction::m_SaveVolPre private
Definition at line 58 of file EICG4B0ECALSteppingAction.h.
View newest version in sPHENIX GitHub at line 58 of file EICG4B0ECALSteppingAction.h
Referenced by UserSteppingAction().
EICG4B0ECALSubsystem* EICG4B0ECALSteppingAction::m_Subsystem private
pointer to the detector
Definition at line 50 of file EICG4B0ECALSteppingAction.h.
View newest version in sPHENIX GitHub at line 50 of file EICG4B0ECALSteppingAction.h
Referenced by hasMotherSubsystem().
double EICG4B0ECALSteppingAction::m_Tmax private
Definition at line 72 of file EICG4B0ECALSteppingAction.h.
View newest version in sPHENIX GitHub at line 72 of file EICG4B0ECALSteppingAction.h
Referenced by UserSteppingAction().
double EICG4B0ECALSteppingAction::m_Tmin private
Definition at line 71 of file EICG4B0ECALSteppingAction.h.
View newest version in sPHENIX GitHub at line 71 of file EICG4B0ECALSteppingAction.h
Referenced by UserSteppingAction().
int EICG4B0ECALSteppingAction::m_UseG4StepsFlag private
Definition at line 68 of file EICG4B0ECALSteppingAction.h.
View newest version in sPHENIX GitHub at line 68 of file EICG4B0ECALSteppingAction.h
Referenced by UserSteppingAction().
double EICG4B0ECALSteppingAction::m_Zmax private
Definition at line 70 of file EICG4B0ECALSteppingAction.h.
View newest version in sPHENIX GitHub at line 70 of file EICG4B0ECALSteppingAction.h
Referenced by EICG4B0ECALSteppingAction(), and UserSteppingAction().
double EICG4B0ECALSteppingAction::m_Zmin private
Definition at line 69 of file EICG4B0ECALSteppingAction.h.
View newest version in sPHENIX GitHub at line 69 of file EICG4B0ECALSteppingAction.h
Referenced by EICG4B0ECALSteppingAction(), and UserSteppingAction().
The documentation for this class was generated from the following files:
fun4all_eicdetectors/blob/master/simulation/g4simulation/g4b0ecal/EICG4B0ECALSteppingAction.h
fun4all_eicdetectors/blob/master/simulation/g4simulation/g4b0ecal/EICG4B0ECALSteppingAction.cc