EIC Software: PHTpcDeltaZCorrection Class Reference
PHTpcDeltaZCorrection Class Reference
#include <fun4all_coresoftware/blob/master/offline/packages/trackreco/PHTpcDeltaZCorrection.h>
Public Member Functions
PHTpcDeltaZCorrection (const std::string &name="PHTpcDeltaZCorrection")
constructor
~PHTpcDeltaZCorrection () override=default
destructor
int InitRun (PHCompositeNode *topNode) override
int process_event (PHCompositeNode *topNode) override
int End (PHCompositeNode *topNode) override
Called at the end of all processing.
void SetDefaultParameters () override
Public Member Functions inherited from SubsysReco
~SubsysReco () override
virtual int EndRun (const int)
Called at the end of each run.
virtual int Init (PHCompositeNode *)
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
void Print (const std::string &="ALL") const override
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Public Member Functions inherited from PHParameterInterface
PHParameterInterface (const std::string &name)
PHParameterInterface (const PHParameterInterface &)=delete
virtual ~PHParameterInterface ()
void set_paramname (const std::string &name)
void set_double_param (const std::string &name, const double dval)
double get_double_param (const std::string &name) const
void set_int_param (const std::string &name, const int ival)
int get_int_param (const std::string &name) const
void set_string_param (const std::string &name, const std::string &sval)
std::string get_string_param (const std::string &name) const
void UpdateParametersWithMacro ()
void SaveToNodeTree (PHCompositeNode *runNode, const std::string &nodename)
void PutOnParNode (PHCompositeNode *parNode, const std::string &nodename)
Private Member Functions
int load_nodes (PHCompositeNode *)
load nodes
void process_tracks ()
process tracks
void process_track (unsigned int, SvtxTrack *)
process track
Private Attributes
ActsSurfaceMaps * m_surfmaps = nullptr
Acts surface maps for surface lookup.
ActsTrackingGeometry * m_tGeometry = nullptr
Acts tracking geometry for surface lookup.
ActsTransformations m_transformer
acts transformation
SvtxTrackMap * m_track_map = nullptr
track map
TrkrClusterContainer * m_cluster_map = nullptr
cluster map
std::set< TrkrDefs::cluskey > m_corrected_clusters
list of corrected cluster keys
double m_bz_const = 1.4
constant magnetic field
double m_drift_velocity = NAN
electron drift velocity in gas
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = INT_MAX - 10
}
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Protected Member Functions inherited from PHParameterInterface
void set_default_double_param (const std::string &name, const double dval)
void set_default_int_param (const std::string &name, const int ival)
void set_default_string_param (const std::string &name, const std::string &sval)
void InitializeParameters ()
Detailed Description
Definition at line 21 of file PHTpcDeltaZCorrection.h.
View newest version in sPHENIX GitHub at line 21 of file PHTpcDeltaZCorrection.h
Constructor & Destructor Documentation
PHTpcDeltaZCorrection::PHTpcDeltaZCorrection (const std::string & name = "PHTpcDeltaZCorrection")
constructor
Definition at line 35 of file PHTpcDeltaZCorrection.cc.
View newest version in sPHENIX GitHub at line 35 of file PHTpcDeltaZCorrection.cc
References PHParameterInterface::InitializeParameters().
PHTpcDeltaZCorrection::~PHTpcDeltaZCorrection () override default
destructor
Member Function Documentation
int PHTpcDeltaZCorrection::End (PHCompositeNode *) override virtual
Called at the end of all processing.
Reimplemented from SubsysReco.
Definition at line 62 of file PHTpcDeltaZCorrection.cc.
View newest version in sPHENIX GitHub at line 62 of file PHTpcDeltaZCorrection.cc
References Fun4AllReturnCodes::EVENT_OK.
int PHTpcDeltaZCorrection::InitRun (PHCompositeNode *) override virtual
Called for first event when run number is known. Typically this is where you may want to fetch data from database, because you know the run number.
Reimplemented from SubsysReco.
Definition at line 42 of file PHTpcDeltaZCorrection.cc.
View newest version in sPHENIX GitHub at line 42 of file PHTpcDeltaZCorrection.cc
References Fun4AllReturnCodes::EVENT_OK, PHParameterInterface::get_double_param(), m_bz_const, m_drift_velocity, and PHParameterInterface::UpdateParametersWithMacro().
int PHTpcDeltaZCorrection::load_nodes (PHCompositeNode * topNode) private
load nodes
Definition at line 78 of file PHTpcDeltaZCorrection.cc.
View newest version in sPHENIX GitHub at line 78 of file PHTpcDeltaZCorrection.cc
References Fun4AllReturnCodes::EVENT_OK, m_cluster_map, m_surfmaps, m_tGeometry, m_track_map, and Fun4AllBase::Verbosity().
Referenced by process_event().
int PHTpcDeltaZCorrection::process_event (PHCompositeNode *) override virtual
Called for each event. This is where you do the real work.
Reimplemented from SubsysReco.
Definition at line 51 of file PHTpcDeltaZCorrection.cc.
View newest version in sPHENIX GitHub at line 51 of file PHTpcDeltaZCorrection.cc
References Fun4AllReturnCodes::EVENT_OK, load_nodes(), and process_tracks().
void PHTpcDeltaZCorrection::process_track (unsigned int key, SvtxTrack * track) private
process track
Definition at line 118 of file PHTpcDeltaZCorrection.cc.
View newest version in sPHENIX GitHub at line 118 of file PHTpcDeltaZCorrection.cc
References SvtxTrack::begin_cluster_keys(), QAG4Util::delta_phi(), SvtxTrack::end_cluster_keys(), TrkrClusterContainer::findCluster(), SvtxTrack::get_positive_charge(), SvtxTrack::get_px(), SvtxTrack::get_py(), SvtxTrack::get_x(), SvtxTrack::get_y(), SvtxTrack::get_z(), ActsTransformations::getGlobalPosition(), TrkrDefs::getTrkrId(), m_bz_const, m_cluster_map, m_corrected_clusters, m_drift_velocity, m_surfmaps, m_tGeometry, m_transformer, Acts::Test::origin(), G4BECAL::radius, square(), TrkrDefs::tpcId, and Fun4AllBase::Verbosity().
Referenced by process_tracks().
void PHTpcDeltaZCorrection::process_tracks () private
process tracks
Definition at line 108 of file PHTpcDeltaZCorrection.cc.
View newest version in sPHENIX GitHub at line 108 of file PHTpcDeltaZCorrection.cc
References SvtxTrackMap::begin(), SvtxTrackMap::end(), m_cluster_map, m_corrected_clusters, m_track_map, and process_track().
Referenced by process_event().
void PHTpcDeltaZCorrection::SetDefaultParameters () override virtual
Implements PHParameterInterface.
Definition at line 66 of file PHTpcDeltaZCorrection.cc.
View newest version in sPHENIX GitHub at line 66 of file PHTpcDeltaZCorrection.cc
References PHParameterInterface::set_default_double_param().
Member Data Documentation
double PHTpcDeltaZCorrection::m_bz_const = 1.4 private
constant magnetic field
it is used to get helix trajectory from momentum at origin
Definition at line 68 of file PHTpcDeltaZCorrection.h.
View newest version in sPHENIX GitHub at line 68 of file PHTpcDeltaZCorrection.h
Referenced by InitRun(), and process_track().
TrkrClusterContainer* PHTpcDeltaZCorrection::m_cluster_map = nullptr private
cluster map
Definition at line 60 of file PHTpcDeltaZCorrection.h.
View newest version in sPHENIX GitHub at line 60 of file PHTpcDeltaZCorrection.h
Referenced by load_nodes(), process_track(), and process_tracks().
std::set<TrkrDefs::cluskey> PHTpcDeltaZCorrection::m_corrected_clusters private
list of corrected cluster keys
needed to prevent clusters to be corrected twice, when same cluster is used for two different tracks
Definition at line 64 of file PHTpcDeltaZCorrection.h.
View newest version in sPHENIX GitHub at line 64 of file PHTpcDeltaZCorrection.h
Referenced by process_track(), and process_tracks().
double PHTpcDeltaZCorrection::m_drift_velocity = NAN private
electron drift velocity in gas
Definition at line 71 of file PHTpcDeltaZCorrection.h.
View newest version in sPHENIX GitHub at line 71 of file PHTpcDeltaZCorrection.h
Referenced by InitRun(), and process_track().
ActsSurfaceMaps* PHTpcDeltaZCorrection::m_surfmaps = nullptr private
Acts surface maps for surface lookup.
Definition at line 48 of file PHTpcDeltaZCorrection.h.
View newest version in sPHENIX GitHub at line 48 of file PHTpcDeltaZCorrection.h
Referenced by load_nodes(), and process_track().
ActsTrackingGeometry* PHTpcDeltaZCorrection::m_tGeometry = nullptr private
Acts tracking geometry for surface lookup.
Definition at line 51 of file PHTpcDeltaZCorrection.h.
View newest version in sPHENIX GitHub at line 51 of file PHTpcDeltaZCorrection.h
Referenced by load_nodes(), and process_track().
SvtxTrackMap* PHTpcDeltaZCorrection::m_track_map = nullptr private
track map
Definition at line 57 of file PHTpcDeltaZCorrection.h.
View newest version in sPHENIX GitHub at line 57 of file PHTpcDeltaZCorrection.h
Referenced by load_nodes(), and process_tracks().
ActsTransformations PHTpcDeltaZCorrection::m_transformer private
acts transformation
Definition at line 54 of file PHTpcDeltaZCorrection.h.
View newest version in sPHENIX GitHub at line 54 of file PHTpcDeltaZCorrection.h
Referenced by process_track().
The documentation for this class was generated from the following files:
fun4all_coresoftware/blob/master/offline/packages/trackreco/PHTpcDeltaZCorrection.h
fun4all_coresoftware/blob/master/offline/packages/trackreco/PHTpcDeltaZCorrection.cc