EIC Software: element_t Class Reference
element_t Class Reference
#include <EicRoot/blob/master/eic/cad/elmer/src/meshtype.h>
Public Member Functions
element_t ()
~element_t ()
void setNature (int)
int getNature () const
void setCode (int)
int getCode () const
void setNodes (int)
int getNodes () const
void setIndex (int)
int getIndex () const
void setSelected (int)
int getSelected () const
int getNodeIndex (int) const
void setNodeIndex (int, int)
int * getNodeIndexes () const
void newNodeIndexes (int)
void deleteNodeIndexes ()
Private Attributes
int nature
int code
int nodes
int index
int selected
int * node
Detailed Description
Definition at line 76 of file meshtype.h.
View newest version in sPHENIX GitHub at line 76 of file meshtype.h
Constructor & Destructor Documentation
element_t::element_t ()
Definition at line 90 of file meshtype.cpp.
View newest version in sPHENIX GitHub at line 90 of file meshtype.cpp
element_t::~element_t ()
Definition at line 94 of file meshtype.cpp.
View newest version in sPHENIX GitHub at line 94 of file meshtype.cpp
Member Function Documentation
void element_t::deleteNodeIndexes ()
Definition at line 163 of file meshtype.cpp.
View newest version in sPHENIX GitHub at line 163 of file meshtype.cpp
int element_t::getCode () const
Definition at line 113 of file meshtype.cpp.
View newest version in sPHENIX GitHub at line 113 of file meshtype.cpp
Referenced by ConvertEgTypeToMeshType(), mesh_t::load(), and mesh_t::save().
int element_t::getIndex () const
Definition at line 133 of file meshtype.cpp.
View newest version in sPHENIX GitHub at line 133 of file meshtype.cpp
Referenced by mesh_t::save().
int element_t::getNature () const
Definition at line 103 of file meshtype.cpp.
View newest version in sPHENIX GitHub at line 103 of file meshtype.cpp
Referenced by mesh_t::save().
int element_t::getNodeIndex (int n) const
Definition at line 148 of file meshtype.cpp.
View newest version in sPHENIX GitHub at line 148 of file meshtype.cpp
References n.
Referenced by mesh_t::save().
int * element_t::getNodeIndexes () const
Definition at line 168 of file meshtype.cpp.
View newest version in sPHENIX GitHub at line 168 of file meshtype.cpp
int element_t::getNodes () const
Definition at line 123 of file meshtype.cpp.
View newest version in sPHENIX GitHub at line 123 of file meshtype.cpp
Referenced by ConvertEgTypeToMeshType(), mesh_t::load(), and mesh_t::save().
int element_t::getSelected () const
Definition at line 143 of file meshtype.cpp.
View newest version in sPHENIX GitHub at line 143 of file meshtype.cpp
void element_t::newNodeIndexes (int n)
Definition at line 158 of file meshtype.cpp.
View newest version in sPHENIX GitHub at line 158 of file meshtype.cpp
References n.
Referenced by ConvertEgTypeToMeshType(), and mesh_t::load().
void element_t::setCode (int n)
Definition at line 108 of file meshtype.cpp.
View newest version in sPHENIX GitHub at line 108 of file meshtype.cpp
References n.
Referenced by ConvertEgTypeToMeshType(), and mesh_t::load().
void element_t::setIndex (int n)
Definition at line 128 of file meshtype.cpp.
View newest version in sPHENIX GitHub at line 128 of file meshtype.cpp
References n.
Referenced by ConvertEgTypeToMeshType(), and mesh_t::load().
void element_t::setNature (int n)
Definition at line 98 of file meshtype.cpp.
View newest version in sPHENIX GitHub at line 98 of file meshtype.cpp
References n.
Referenced by ConvertEgTypeToMeshType(), and mesh_t::load().
void element_t::setNodeIndex (int m, int n)
Definition at line 153 of file meshtype.cpp.
View newest version in sPHENIX GitHub at line 153 of file meshtype.cpp
References Acts::UnitConstants::m, and n.
Referenced by ConvertEgTypeToMeshType(), and mesh_t::load().
void element_t::setNodes (int n)
Definition at line 118 of file meshtype.cpp.
View newest version in sPHENIX GitHub at line 118 of file meshtype.cpp
References n.
Referenced by ConvertEgTypeToMeshType(), and mesh_t::load().
void element_t::setSelected (int n)
Definition at line 138 of file meshtype.cpp.
View newest version in sPHENIX GitHub at line 138 of file meshtype.cpp
References n.
Member Data Documentation
int element_t::code private
Definition at line 99 of file meshtype.h.
View newest version in sPHENIX GitHub at line 99 of file meshtype.h
int element_t::index private
Definition at line 101 of file meshtype.h.
View newest version in sPHENIX GitHub at line 101 of file meshtype.h
int element_t::nature private
Definition at line 98 of file meshtype.h.
View newest version in sPHENIX GitHub at line 98 of file meshtype.h
int* element_t::node private
Definition at line 103 of file meshtype.h.
View newest version in sPHENIX GitHub at line 103 of file meshtype.h
int element_t::nodes private
Definition at line 100 of file meshtype.h.
View newest version in sPHENIX GitHub at line 100 of file meshtype.h
int element_t::selected private
Definition at line 102 of file meshtype.h.
View newest version in sPHENIX GitHub at line 102 of file meshtype.h
The documentation for this class was generated from the following files:
EicRoot/blob/master/eic/cad/elmer/src/meshtype.h
EicRoot/blob/master/eic/cad/elmer/src/meshtype.cpp