EIC Software: CbmRichRingSelectImplLight Class Reference
CbmRichRingSelectImplLight Class Reference
#include <EicRoot/blob/master/rich/standalone/algorithm/CbmRichRingSelectImplLight.h>
Public Member Functions
CbmRichRingSelectImplLight ()
~CbmRichRingSelectImplLight ()
int GetNofHitsOnRingCircle (CbmRichRingLight *ring)
float GetAngle (CbmRichRingLight *ring)
Public Attributes
int kMAX_NOF_HITS
Protected Attributes
std::vector< float > fAlpha
std::vector< float > fPhi
Detailed Description
Definition at line 18 of file CbmRichRingSelectImplLight.h.
View newest version in sPHENIX GitHub at line 18 of file CbmRichRingSelectImplLight.h
Constructor & Destructor Documentation
CbmRichRingSelectImplLight::CbmRichRingSelectImplLight () inline
Definition at line 23 of file CbmRichRingSelectImplLight.h.
View newest version in sPHENIX GitHub at line 23 of file CbmRichRingSelectImplLight.h
References fAlpha, fPhi, and kMAX_NOF_HITS.
CbmRichRingSelectImplLight::~CbmRichRingSelectImplLight () inline
Definition at line 28 of file CbmRichRingSelectImplLight.h.
View newest version in sPHENIX GitHub at line 28 of file CbmRichRingSelectImplLight.h
Member Function Documentation
float CbmRichRingSelectImplLight::GetAngle (CbmRichRingLight * ring) inline
Definition at line 52 of file CbmRichRingSelectImplLight.h.
View newest version in sPHENIX GitHub at line 52 of file CbmRichRingSelectImplLight.h
References fAlpha, fPhi, CbmRichHitLight::fX, CbmRichHitLight::fY, CbmRichRingLight::GetCenterX(), CbmRichRingLight::GetCenterY(), CbmRichRingLight::GetHit(), CbmRichRingLight::GetNofHits(), and kMAX_NOF_HITS.
Referenced by CbmRichRingSelectNeuralNet::DoSelect().
int CbmRichRingSelectImplLight::GetNofHitsOnRingCircle (CbmRichRingLight * ring) inline
Definition at line 38 of file CbmRichRingSelectImplLight.h.
View newest version in sPHENIX GitHub at line 38 of file CbmRichRingSelectImplLight.h
References CbmRichHitLight::fX, CbmRichHitLight::fY, CbmRichRingLight::GetCenterX(), CbmRichRingLight::GetCenterY(), CbmRichRingLight::GetHit(), CbmRichRingLight::GetNofHits(), and CbmRichRingLight::GetRadius().
Referenced by CbmRichRingSelectNeuralNet::DoSelect().
Member Data Documentation
std::vector<float> CbmRichRingSelectImplLight::fAlpha protected
Definition at line 33 of file CbmRichRingSelectImplLight.h.
View newest version in sPHENIX GitHub at line 33 of file CbmRichRingSelectImplLight.h
Referenced by CbmRichRingSelectImplLight(), and GetAngle().
std::vector<float> CbmRichRingSelectImplLight::fPhi protected
Definition at line 34 of file CbmRichRingSelectImplLight.h.
View newest version in sPHENIX GitHub at line 34 of file CbmRichRingSelectImplLight.h
Referenced by CbmRichRingSelectImplLight(), and GetAngle().
int CbmRichRingSelectImplLight::kMAX_NOF_HITS
Definition at line 21 of file CbmRichRingSelectImplLight.h.
View newest version in sPHENIX GitHub at line 21 of file CbmRichRingSelectImplLight.h
Referenced by CbmRichRingSelectImplLight(), and GetAngle().
The documentation for this class was generated from the following file:
EicRoot/blob/master/rich/standalone/algorithm/CbmRichRingSelectImplLight.h