EIC Software: SimFlag Namespace Reference
SimFlag Namespace Reference
Typedefs
typedef enum SimFlag::ESimFlag SimFlag_t
Enumerations
enum ESimFlag {
kUnknown = 0x00, kData = 0x01, kDaqSimData = 0x02, kMC = 0x04,
kReroot = 0x08
}
Functions
Int_t FullMask ()
const Char_t * AsString (SimFlag_t detector)
const Char_t * MaskToString (Int_t mask)
SimFlag::SimFlag_t StringToEnum (const Char_t *chars, Int_t maxChar=0)
Int_t StringToMask (const Char_t *chars, Int_t maxChar=0)
Int_t Compact (SimFlag_t simFlag)
SimFlag::SimFlag_t Expand (Int_t compactSimFlag)
Typedef Documentation
typedef enum SimFlag::ESimFlag SimFlag::SimFlag_t
Enumeration Type Documentation
enum SimFlag::ESimFlag
Enumerator:
kUnknown
kData
kDaqSimData
kMC
kReroot
Definition at line 14 of file SimFlag.h.
View newest version in sPHENIX GitHub at line 14 of file SimFlag.h
Function Documentation
const Char_t * SimFlag::AsString (SimFlag_t detector)
Definition at line 14 of file SimFlag.cxx.
View newest version in sPHENIX GitHub at line 14 of file SimFlag.cxx
References kDaqSimData, kData, kMC, kReroot, and kUnknown.
Referenced by ValContext::AsString(), ClassImp(), MaskToString(), FairDbSimFlagAssociation::Print(), and FairDbCache::Search().
Int_t SimFlag::Compact (SimFlag_t simFlag)
Definition at line 125 of file SimFlag.cxx.
View newest version in sPHENIX GitHub at line 125 of file SimFlag.cxx
References kDaqSimData, kData, kMC, kReroot, and kUnknown.
SimFlag::SimFlag_t SimFlag::Expand (Int_t compactSimFlag)
Definition at line 154 of file SimFlag.cxx.
View newest version in sPHENIX GitHub at line 154 of file SimFlag.cxx
References kDaqSimData, kData, kMC, kReroot, and kUnknown.
Int_t SimFlag::FullMask ()
Definition at line 7 of file SimFlag.cxx.
View newest version in sPHENIX GitHub at line 7 of file SimFlag.cxx
References kDaqSimData, kData, kMC, and kReroot.
Referenced by MaskToString(), and FairDbLogEntry::Recreate().
const Char_t * SimFlag::MaskToString (Int_t mask)
Definition at line 42 of file SimFlag.cxx.
View newest version in sPHENIX GitHub at line 42 of file SimFlag.cxx
References AsString(), and FullMask().
Referenced by ValRange::AsString().
SimFlag::SimFlag_t SimFlag::StringToEnum (const Char_t * chars, Int_t maxChar = 0)
Definition at line 73 of file SimFlag.cxx.
View newest version in sPHENIX GitHub at line 73 of file SimFlag.cxx
References kDaqSimData, kData, kMC, kReroot, kUnknown, and StringToMask().
Referenced by FairDbSimFlagAssociation::Set().
Int_t SimFlag::StringToMask (const Char_t * chars, Int_t maxChar = 0)
Definition at line 104 of file SimFlag.cxx.
View newest version in sPHENIX GitHub at line 104 of file SimFlag.cxx
References kDaqSimData, kData, kMC, and kReroot.
Referenced by StringToEnum().