EIC Software: MakeActsGeometry Class Reference
MakeActsGeometry Class Reference
#include <fun4all_coresoftware/blob/master/offline/packages/trackreco/MakeActsGeometry.h>
Public Member Functions
MakeActsGeometry (const std::string &name="MakeActsGeometry")
Default constructor.
~MakeActsGeometry ()
Destructor.
int Init (PHCompositeNode *topNode)
int InitRun (PHCompositeNode *topNode)
int process_event (PHCompositeNode *topNode)
int End (PHCompositeNode *topNode)
Called at the end of all processing.
std::vector< std::shared_ptr
< ActsExamples::IContextDecorator > > getContextDecorators ()
void setMagField (const std::string &magField)
void setMagFieldRescale (double magFieldRescale)
double getSurfStepPhi ()
double getSurfStepZ ()
Public Member Functions inherited from SubsysReco
virtual ~SubsysReco ()
virtual int EndRun (const int)
Called at the end of each run.
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
virtual void Print (const std::string &what="ALL") const
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Private Member Functions
int buildAllGeometry (PHCompositeNode *topNode)
Main function to build all acts geometry for use in the fitting modules.
int getNodes (PHCompositeNode *)
Get all the nodes.
int createNodes (PHCompositeNode *)
Create New nodes.
void setPlanarSurfaceDivisions ()
Functions to edit TGeoManager to include TPC boxes.
void editTPCGeometry (PHCompositeNode *topNode)
void addActsTpcSurfaces (TGeoVolume *tpc_gas_vol, TGeoManager *geoManager)
void addActsMicromegasSurfaces (int mm_layer, TGeoVolume *micromegas_vol, TGeoManager *geoManager)
void buildActsSurfaces ()
Silicon layers made by BuildSiliconLayers and its helper functions.
void makeGeometry (int argc, char *argv[], ActsExamples::IBaseDetector &detector)
Function that mimics ActsFW::GeometryExampleBase.
void getInttKeyFromNode (TGeoNode *gnode)
Get hitsetkey from TGeoNode for each detector geometry.
void getMvtxKeyFromNode (TGeoNode *gnode)
void getTpcKeyFromNode (TGeoNode *gnode)
void makeMvtxMapPairs (TrackingVolumePtr &mvtxVolume)
void makeInttMapPairs (TrackingVolumePtr &inttVolume)
void makeTpcMapPairs (TrackingVolumePtr &tpcVolume)
void makeMmMapPairs (TrackingVolumePtr &tpcVolume)
TrkrDefs::hitsetkey getMvtxHitSetKeyFromCoords (unsigned int layer, std::vector< double > &world)
Get subdetector hitsetkey from the local sensor unit coordinates.
TrkrDefs::hitsetkey getInttHitSetKeyFromCoords (unsigned int layer, std::vector< double > &world)
TrkrDefs::hitsetkey getTpcHitSetKeyFromCoords (std::vector< double > &world)
TrkrDefs::hitsetkey getMmHitSetKeyFromCoords (std::vector< double > &world)
void isActive (TGeoNode *gnode, int nmax_print)
Helper diagnostic function for identifying active layers in subdetectors.
void makeTGeoNodeMap (PHCompositeNode *topNode)
Makes map of TrkrHitSetKey<–>TGeoNode.
void unpackVolumes ()
Private Attributes
PHG4CylinderGeomContainer * m_geomContainerMvtx = nullptr
Subdetector geometry containers for getting layer information.
PHG4CylinderGeomContainer * m_geomContainerIntt = nullptr
PHG4CylinderCellGeomContainer * m_geomContainerTpc = nullptr
TGeoManager * m_geoManager = nullptr
std::vector< std::shared_ptr
< ActsExamples::IContextDecorator > > m_contextDecorators
Acts Context decorators, which may contain e.g. calibration information.
std::map< TrkrDefs::hitsetkey,
TGeoNode * > m_clusterNodeMap
Several maps that connect Acts world to sPHENIX G4 world.
std::map< TrkrDefs::hitsetkey,
Surface > m_clusterSurfaceMapSilicon
std::map< TrkrDefs::hitsetkey,
std::vector< Surface > > m_clusterSurfaceMapTpcEdit
std::map< TrkrDefs::hitsetkey,
std::vector< Surface > > m_clusterSurfaceMapMmEdit
const unsigned int m_nTpcModulesPerLayer = 12
const unsigned int m_nTpcSides = 2
double m_minSurfZ = 0.
TPC Acts::Surface subdivisions.
double m_maxSurfZ = 105.5
unsigned int m_nSurfZ = 1
unsigned int m_nSurfPhi = 12
double m_surfStepPhi
double m_surfStepZ
double m_moduleStepPhi
double m_modulePhiStart
int nprint_tpc
Debugger for printing out tpc active volumes.
const double m_minRadius [m_nTpcSectors] = {30.0, 40.0, 60.0}
const double m_maxRadius [m_nTpcSectors] = {40.0, 60.0, 77.0}
double layer_thickness_sector [m_nTpcSectors] = {0}
double m_layerRadius [m_nTpcLayers] = {0}
double m_layerThickness [m_nTpcLayers] = {0}
const unsigned int m_mmLayerNumber [m_nMmLayers] = {55, 56}
double m_mmLayerRadius [m_nMmLayers] = {82.2565, 82.6998}
double m_mmLayerThickness [m_nMmLayers] = {0.3, 0.3}
const double half_width_clearance_thick = 0.4999
const double half_width_clearance_phi = 0.4999
const double half_width_clearance_z = 0.4999
TGeoDetector m_detector
The acts geometry object.
TrackingGeometry m_tGeometry
Acts geometry objects that are needed to create (for example) the fitter.
ActsExamples::Options::BFieldVariant m_magneticField
Acts::GeometryContext m_geoCtxt
Acts::CalibrationContext m_calibContext
Acts::MagneticFieldContext m_magFieldContext
ActsTrackingGeometry * m_actsGeometry = nullptr
Structs to put on the node tree which carry around ActsGeom info.
ActsSurfaceMaps * m_surfMaps = nullptr
int m_verbosity = 0
Verbosity value handed from PHActsSourceLinks.
std::string m_magField ="1.4"
Magnetic field components to set Acts magnetic field.
double m_magFieldRescale = -1.
bool m_buildMMs = false
Static Private Attributes
static const unsigned int m_nTpcLayers = 48
These don't change, we are building the tpc this way!
static const int m_nTpcSectors = 3
TPC TGeoManager editing box surfaces subdivisions.
static const int m_nMmLayers = 2
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = INT_MAX - 10
}
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Detailed Description
This class is responsible for building the ActsGeometry from the sPHENIX TGeometry. The code largely follows examples within the ACTFW code, specifically GeometryExampleBase.cpp. This class puts several nodes on the node tree which relate Acts::Surfaces to sPHENIX TGeo objects, for use in building Acts SourceLinks.
Definition at line 63 of file MakeActsGeometry.h.
View newest version in sPHENIX GitHub at line 63 of file MakeActsGeometry.h
Constructor & Destructor Documentation
MakeActsGeometry::MakeActsGeometry (const std::string & name = "MakeActsGeometry")
Default constructor.
Definition at line 74 of file MakeActsGeometry.cc.
View newest version in sPHENIX GitHub at line 74 of file MakeActsGeometry.cc
References nprint_tpc, and setPlanarSurfaceDivisions().
MakeActsGeometry::~MakeActsGeometry ()
Destructor.
Definition at line 81 of file MakeActsGeometry.cc.
View newest version in sPHENIX GitHub at line 81 of file MakeActsGeometry.cc
Member Function Documentation
void MakeActsGeometry::addActsMicromegasSurfaces (int mm_layer, TGeoVolume * micromegas_vol, TGeoManager * geoManager) private
Definition at line 305 of file MakeActsGeometry.cc.
View newest version in sPHENIX GitHub at line 305 of file MakeActsGeometry.cc
References cos(), m_mmLayerRadius, m_mmLayerThickness, m_modulePhiStart, m_moduleStepPhi, m_nSurfPhi, m_nSurfZ, m_nTpcModulesPerLayer, M_PI, m_surfStepPhi, and Fun4AllBase::Verbosity().
Referenced by editTPCGeometry().
void MakeActsGeometry::addActsTpcSurfaces (TGeoVolume * tpc_gas_vol, TGeoManager * geoManager) private
Definition at line 407 of file MakeActsGeometry.cc.
View newest version in sPHENIX GitHub at line 407 of file MakeActsGeometry.cc
References cos(), half_width_clearance_phi, half_width_clearance_thick, half_width_clearance_z, m_layerRadius, m_layerThickness, m_modulePhiStart, m_moduleStepPhi, m_nSurfPhi, m_nSurfZ, m_nTpcLayers, m_nTpcModulesPerLayer, M_PI, m_surfStepPhi, m_surfStepZ, and Fun4AllBase::Verbosity().
Referenced by editTPCGeometry().
void MakeActsGeometry::buildActsSurfaces () private
Silicon layers made by BuildSiliconLayers and its helper functions.
Builds silicon layers and TPC geometry in the ACTS surface world
If the 2d fieldmap is provided, for now we just assume a 1.4T field (which will be properly scaled by 1.4/1.5) from magFieldRescale
The acts constant field and geant field are backwards in convention
Check to see if files exist locally - if not, use defaults
Definition at line 504 of file MakeActsGeometry.cc.
View newest version in sPHENIX GitHub at line 504 of file MakeActsGeometry.cc
References eicpy.qaplots::file, m_buildMMs, m_detector, m_magField, m_magFieldRescale, makeGeometry(), PHWHERE, nlohmann::to_string(), and Fun4AllBase::Verbosity().
Referenced by buildAllGeometry().
int MakeActsGeometry::buildAllGeometry (PHCompositeNode * topNode) private
Main function to build all acts geometry for use in the fitting modules.
Add the TPC surfaces to the copy of the TGeoManager.
Run Acts layer builder
Create a map of sensor TGeoNode pointers using the TrkrDefs:: hitsetkey as the key
Export the new geometry to a root file for examination
Definition at line 120 of file MakeActsGeometry.cc.
View newest version in sPHENIX GitHub at line 120 of file MakeActsGeometry.cc
References Fun4AllReturnCodes::ABORTEVENT, buildActsSurfaces(), createNodes(), editTPCGeometry(), Fun4AllReturnCodes::EVENT_OK, PHGeomUtility::ExportGeomtry(), getNodes(), makeTGeoNodeMap(), and Fun4AllBase::Verbosity().
Referenced by InitRun().
int MakeActsGeometry::createNodes (PHCompositeNode * topNode) private
Create New nodes.
Get the DST Node
Check that it is there
Get the tracking subnode
Check that it is there
Definition at line 1521 of file MakeActsGeometry.cc.
View newest version in sPHENIX GitHub at line 1521 of file MakeActsGeometry.cc
References PHCompositeNode::addNode(), Fun4AllReturnCodes::EVENT_OK, PHNodeIterator::findFirst(), m_actsGeometry, and m_surfMaps.
Referenced by buildAllGeometry().
void MakeActsGeometry::editTPCGeometry (PHCompositeNode * topNode) private
Reset the geometry node, which we will recreate with the TPC edits
If the node was found, we're building the MMs
Definition at line 150 of file MakeActsGeometry.cc.
View newest version in sPHENIX GitHub at line 150 of file MakeActsGeometry.cc
References addActsMicromegasSurfaces(), addActsTpcSurfaces(), PHGeomIOTGeo::ConstructTGeoManager(), PHGeomUtility::GetGeomIOTGeoNode(), PHGeomUtility::GetGeomTGeoNode(), PHGeomTGeo::isValid(), PHGeomIOTGeo::isValid(), m_buildMMs, PHGeomTGeo::Reset(), PHGeomTGeo::SetGeometry(), PHGeomUtility::UpdateIONode(), and Fun4AllBase::Verbosity().
Referenced by buildAllGeometry().
int MakeActsGeometry::End (PHCompositeNode *) virtual
Called at the end of all processing.
Reimplemented from SubsysReco.
Definition at line 115 of file MakeActsGeometry.cc.
View newest version in sPHENIX GitHub at line 115 of file MakeActsGeometry.cc
References Fun4AllReturnCodes::EVENT_OK.
std::vector<std::shared_ptr<ActsExamples::IContextDecorator> > MakeActsGeometry::getContextDecorators () inline
Definition at line 78 of file MakeActsGeometry.h.
View newest version in sPHENIX GitHub at line 78 of file MakeActsGeometry.h
References m_contextDecorators.
TrkrDefs::hitsetkey MakeActsGeometry::getInttHitSetKeyFromCoords (unsigned int layer, std::vector< double > & world) private
Definition at line 1143 of file MakeActsGeometry.cc.
View newest version in sPHENIX GitHub at line 1143 of file MakeActsGeometry.cc
References CylinderGeomIntt::find_indices_from_segment_center(), CylinderGeomIntt::find_segment_center(), InttDefs::genHitSetKey(), PHG4CylinderGeomContainer::GetLayerGeom(), m_geomContainerIntt, and PHWHERE.
Referenced by makeInttMapPairs().
void MakeActsGeometry::getInttKeyFromNode (TGeoNode * gnode) private
Get hitsetkey from TGeoNode for each detector geometry.
Definition at line 1257 of file MakeActsGeometry.cc.
View newest version in sPHENIX GitHub at line 1257 of file MakeActsGeometry.cc
References exit(), InttDefs::genHitSetKey(), m_clusterNodeMap, PHWHERE, Acts::Test::pos, analysis::s, and Fun4AllBase::Verbosity().
Referenced by makeTGeoNodeMap().
TrkrDefs::hitsetkey MakeActsGeometry::getMmHitSetKeyFromCoords (std::vector< double > & world) private
Get the surface key to find the surface from the map
Definition at line 1073 of file MakeActsGeometry.cc.
View newest version in sPHENIX GitHub at line 1073 of file MakeActsGeometry.cc
References Fun4AllReturnCodes::ABORTEVENT, MicromegasDefs::genHitSetKey(), m_mmLayerNumber, m_mmLayerRadius, m_mmLayerThickness, m_nMmLayers, PHWHERE, PHG4InttDefs::SEGMENTATION_PHI, PHG4InttDefs::SEGMENTATION_Z, and Fun4AllBase::Verbosity().
Referenced by makeMmMapPairs().
TrkrDefs::hitsetkey MakeActsGeometry::getMvtxHitSetKeyFromCoords (unsigned int layer, std::vector< double > & world) private
Get subdetector hitsetkey from the local sensor unit coordinates.
Definition at line 1120 of file MakeActsGeometry.cc.
View newest version in sPHENIX GitHub at line 1120 of file MakeActsGeometry.cc
References CylinderGeom_Mvtx::find_sensor_center(), MvtxDefs::genHitSetKey(), CylinderGeom_Mvtx::get_sensor_indices_from_world_coords(), PHG4CylinderGeomContainer::GetLayerGeom(), m_geomContainerMvtx, and PHWHERE.
Referenced by makeMvtxMapPairs().
void MakeActsGeometry::getMvtxKeyFromNode (TGeoNode * gnode) private
Definition at line 1336 of file MakeActsGeometry.cc.
View newest version in sPHENIX GitHub at line 1336 of file MakeActsGeometry.cc
References MvtxDefs::genHitSetKey(), m_clusterNodeMap, Acts::Test::pos, analysis::s, and Fun4AllBase::Verbosity().
Referenced by makeTGeoNodeMap().
int MakeActsGeometry::getNodes (PHCompositeNode * topNode) private
Get all the nodes.
Definition at line 1573 of file MakeActsGeometry.cc.
View newest version in sPHENIX GitHub at line 1573 of file MakeActsGeometry.cc
References Fun4AllReturnCodes::ABORTEVENT, Fun4AllReturnCodes::ABORTRUN, Fun4AllReturnCodes::EVENT_OK, findNode::getClass(), PHGeomUtility::GetTGeoManager(), m_geoManager, m_geomContainerIntt, m_geomContainerMvtx, m_geomContainerTpc, and PHWHERE.
Referenced by buildAllGeometry().
double MakeActsGeometry::getSurfStepPhi () inline
Definition at line 86 of file MakeActsGeometry.h.
View newest version in sPHENIX GitHub at line 86 of file MakeActsGeometry.h
References m_surfStepPhi.
double MakeActsGeometry::getSurfStepZ () inline
Definition at line 87 of file MakeActsGeometry.h.
View newest version in sPHENIX GitHub at line 87 of file MakeActsGeometry.h
References m_surfStepZ.
TrkrDefs::hitsetkey MakeActsGeometry::getTpcHitSetKeyFromCoords (std::vector< double > & world) private
Definition at line 1003 of file MakeActsGeometry.cc.
View newest version in sPHENIX GitHub at line 1003 of file MakeActsGeometry.cc
References Fun4AllReturnCodes::ABORTEVENT, TpcDefs::genHitSetKey(), m_layerRadius, m_layerThickness, m_modulePhiStart, m_moduleStepPhi, m_nTpcLayers, m_nTpcModulesPerLayer, PHWHERE, and Fun4AllBase::Verbosity().
Referenced by makeTpcMapPairs().
void MakeActsGeometry::getTpcKeyFromNode (TGeoNode * gnode) private
Definition at line 1332 of file MakeActsGeometry.cc.
View newest version in sPHENIX GitHub at line 1332 of file MakeActsGeometry.cc
int MakeActsGeometry::Init (PHCompositeNode *) virtual
Called during initialization. Typically this is where you can book histograms, and e.g. register them to Fun4AllServer (so they can be output to file using Fun4AllServer::dumpHistos() method).
Reimplemented from SubsysReco.
Definition at line 84 of file MakeActsGeometry.cc.
View newest version in sPHENIX GitHub at line 84 of file MakeActsGeometry.cc
References Fun4AllReturnCodes::EVENT_OK.
int MakeActsGeometry::InitRun (PHCompositeNode *) virtual
Called for first event when run number is known. Typically this is where you may want to fetch data from database, because you know the run number.
Set the actsGeometry struct to be put on the node tree
Same for the surface maps
Reimplemented from SubsysReco.
Definition at line 88 of file MakeActsGeometry.cc.
View newest version in sPHENIX GitHub at line 88 of file MakeActsGeometry.cc
References Fun4AllReturnCodes::ABORTEVENT, buildAllGeometry(), ActsTrackingGeometry::calibContext, Fun4AllReturnCodes::EVENT_OK, ActsTrackingGeometry::geoContext, m_actsGeometry, m_calibContext, m_clusterNodeMap, m_clusterSurfaceMapMmEdit, m_clusterSurfaceMapSilicon, m_clusterSurfaceMapTpcEdit, m_geoCtxt, m_magFieldContext, m_magneticField, m_surfMaps, m_tGeometry, ActsTrackingGeometry::magField, ActsTrackingGeometry::magFieldContext, ActsSurfaceMaps::mmSurfaceMap, ActsSurfaceMaps::siliconSurfaceMap, ActsTrackingGeometry::tGeometry, ActsSurfaceMaps::tGeoNodeMap, and ActsSurfaceMaps::tpcSurfaceMap.
void MakeActsGeometry::isActive (TGeoNode * gnode, int nmax_print) private
Helper diagnostic function for identifying active layers in subdetectors.
Definition at line 1416 of file MakeActsGeometry.cc.
View newest version in sPHENIX GitHub at line 1416 of file MakeActsGeometry.cc
References nprint_tpc.
Referenced by makeTGeoNodeMap().
void MakeActsGeometry::makeGeometry (int argc, char * argv[], ActsExamples::IBaseDetector & detector) private
Function that mimics ActsFW::GeometryExampleBase.
setup and parse options
Add specific options for this geometry
The geometry, material and decoration
Geometry is a pair of (tgeoTrackingGeometry, tgeoContextDecorators)
Setup the event and algorithm context
The geometry context
Definition at line 594 of file MakeActsGeometry.cc.
View newest version in sPHENIX GitHub at line 594 of file MakeActsGeometry.cc
References FW::Options::addBFieldOptions(), FW::Options::addGeometryOptions(), FW::Options::addMaterialOptions(), FW::Options::addObjWriterOptions(), FW::Options::addOutputOptions(), build(), incremental_prev_tag::desc, Acts::getDefaultLogger(), INFO, m_calibContext, m_contextDecorators, m_geoCtxt, m_magFieldContext, m_magneticField, m_tGeometry, FW::Options::makeDefaultOptions(), eicpy.build::parse(), FW::Options::readBField(), nlohmann::to_string(), and unpackVolumes().
Referenced by buildActsSurfaces().
void MakeActsGeometry::makeInttMapPairs (TrackingVolumePtr & inttVolume) private
The Acts geometry builder combines layers 4 and 5 together, and layers 6 and 7 together. We need to use the radius to figure out which layer to use to get the layergeom
Definition at line 839 of file MakeActsGeometry.cc.
View newest version in sPHENIX GitHub at line 839 of file MakeActsGeometry.cc
References getInttHitSetKeyFromCoords(), InttDefs::getLadderPhiId(), InttDefs::getLadderZId(), m_clusterSurfaceMapSilicon, m_geoCtxt, and Fun4AllBase::Verbosity().
Referenced by unpackVolumes().
void MakeActsGeometry::makeMmMapPairs (TrackingVolumePtr & tpcVolume) private
Need to unfold each layer that Acts builds
surfaceVector is a vector of surfaces corresponding to the micromegas layer that acts builds
convert to cm
If there is already an entry for this hitsetkey, add the surface to its corresponding vector
Otherwise make a new map entry
Definition at line 784 of file MakeActsGeometry.cc.
View newest version in sPHENIX GitHub at line 784 of file MakeActsGeometry.cc
References getMmHitSetKeyFromCoords(), m_clusterSurfaceMapMmEdit, m_geoCtxt, and Fun4AllBase::Verbosity().
Referenced by unpackVolumes().
void MakeActsGeometry::makeMvtxMapPairs (TrackingVolumePtr & mvtxVolume) private
Make the Surface<–>TrkrDef::hitsetkey map pairs for each of the various subdetectors
Definition at line 920 of file MakeActsGeometry.cc.
View newest version in sPHENIX GitHub at line 920 of file MakeActsGeometry.cc
References MvtxDefs::getChipId(), getMvtxHitSetKeyFromCoords(), MvtxDefs::getStaveId(), m_clusterSurfaceMapSilicon, m_geoCtxt, and Fun4AllBase::Verbosity().
Referenced by unpackVolumes().
void MakeActsGeometry::makeTGeoNodeMap (PHCompositeNode * topNode) private
Makes map of TrkrHitSetKey<–>TGeoNode.
The Mvtx has an additional wrapper that needs to be unpacked
We only want the av_1 nodes
Put placeholders for the TPC and MMs. Because we modify the geometry within TGeoVolume, we don't need a mapping to the TGeoNode
Definition at line 1169 of file MakeActsGeometry.cc.
View newest version in sPHENIX GitHub at line 1169 of file MakeActsGeometry.cc
References getInttKeyFromNode(), getMvtxKeyFromNode(), isActive(), m_geoManager, PHWHERE, tpc(), and Fun4AllBase::Verbosity().
Referenced by buildAllGeometry().
void MakeActsGeometry::makeTpcMapPairs (TrackingVolumePtr & tpcVolume) private
Need to unfold each layer that Acts builds
surfaceVector is a vector of surfaces corresponding to the tpc layer that acts builds
convert to cm
If there is already an entry for this hitsetkey, add the surface to its corresponding vector
Otherwise make a new map entry
Definition at line 730 of file MakeActsGeometry.cc.
View newest version in sPHENIX GitHub at line 730 of file MakeActsGeometry.cc
References getTpcHitSetKeyFromCoords(), m_clusterSurfaceMapTpcEdit, m_geoCtxt, and Fun4AllBase::Verbosity().
Referenced by unpackVolumes().
int MakeActsGeometry::process_event (PHCompositeNode *) virtual
Called for each event. This is where you do the real work.
Reimplemented from SubsysReco.
Definition at line 111 of file MakeActsGeometry.cc.
View newest version in sPHENIX GitHub at line 111 of file MakeActsGeometry.cc
References Fun4AllReturnCodes::EVENT_OK.
void MakeActsGeometry::setMagField (const std::string & magField) inline
Definition at line 81 of file MakeActsGeometry.h.
View newest version in sPHENIX GitHub at line 81 of file MakeActsGeometry.h
References m_magField.
Referenced by Tracking_Reco().
void MakeActsGeometry::setMagFieldRescale (double magFieldRescale) inline
Definition at line 83 of file MakeActsGeometry.h.
View newest version in sPHENIX GitHub at line 83 of file MakeActsGeometry.h
References m_magFieldRescale.
Referenced by Tracking_Reco().
void MakeActsGeometry::setPlanarSurfaceDivisions () private
Functions to edit TGeoManager to include TPC boxes.
These are arbitrary tpc subdivisions, and may change Setup how TPC boxes will be built for Acts::Surfaces
Definition at line 1496 of file MakeActsGeometry.cc.
View newest version in sPHENIX GitHub at line 1496 of file MakeActsGeometry.cc
References layer_thickness_sector, m_layerRadius, m_layerThickness, m_maxRadius, m_maxSurfZ, m_minRadius, m_minSurfZ, m_modulePhiStart, m_moduleStepPhi, m_nSurfPhi, m_nSurfZ, m_nTpcModulesPerLayer, M_PI, m_surfStepPhi, and m_surfStepZ.
Referenced by MakeActsGeometry().
void MakeActsGeometry::unpackVolumes () private
m_tGeometry is a TrackingGeometry pointer vol is a TrackingVolume pointer
volumeVector is a std::vector<TrackingVolumePtrs>
We have several volumes to walk through with the tpc and silicon
Depending on whether or not the MMs are being built, the Silicon and TPC volumes are packed differently This actually contains the silicon volumes
INTT only has one volume, so there is not an added volume extraction like for the MVTX
Same for the TPC - only one volume
Additional layer unpacking if MMs were built
INTT only has one volume, so there is not an added volume extraction like for the MVTX
Same for the TPC - only one volume. Buried under silicon volume array
Definition at line 638 of file MakeActsGeometry.cc.
View newest version in sPHENIX GitHub at line 638 of file MakeActsGeometry.cc
References m_buildMMs, m_tGeometry, makeInttMapPairs(), makeMmMapPairs(), makeMvtxMapPairs(), makeTpcMapPairs(), and Fun4AllBase::Verbosity().
Referenced by makeGeometry().
Member Data Documentation
const double MakeActsGeometry::half_width_clearance_phi = 0.4999 private
Definition at line 194 of file MakeActsGeometry.h.
View newest version in sPHENIX GitHub at line 194 of file MakeActsGeometry.h
Referenced by addActsTpcSurfaces().
const double MakeActsGeometry::half_width_clearance_thick = 0.4999 private
Definition at line 193 of file MakeActsGeometry.h.
View newest version in sPHENIX GitHub at line 193 of file MakeActsGeometry.h
Referenced by addActsTpcSurfaces().
const double MakeActsGeometry::half_width_clearance_z = 0.4999 private
Definition at line 195 of file MakeActsGeometry.h.
View newest version in sPHENIX GitHub at line 195 of file MakeActsGeometry.h
Referenced by addActsTpcSurfaces().
double MakeActsGeometry::layer_thickness_sector[m_nTpcSectors] = {0} private
Definition at line 182 of file MakeActsGeometry.h.
View newest version in sPHENIX GitHub at line 182 of file MakeActsGeometry.h
Referenced by setPlanarSurfaceDivisions().
ActsTrackingGeometry* MakeActsGeometry::m_actsGeometry = nullptr private
Structs to put on the node tree which carry around ActsGeom info.
Definition at line 208 of file MakeActsGeometry.h.
View newest version in sPHENIX GitHub at line 208 of file MakeActsGeometry.h
Referenced by createNodes(), and InitRun().
bool MakeActsGeometry::m_buildMMs = false private
Definition at line 218 of file MakeActsGeometry.h.
View newest version in sPHENIX GitHub at line 218 of file MakeActsGeometry.h
Referenced by buildActsSurfaces(), editTPCGeometry(), and unpackVolumes().
Acts::CalibrationContext MakeActsGeometry::m_calibContext private
Definition at line 204 of file MakeActsGeometry.h.
View newest version in sPHENIX GitHub at line 204 of file MakeActsGeometry.h
Referenced by InitRun(), and makeGeometry().
std::map<TrkrDefs::hitsetkey, TGeoNode*> MakeActsGeometry::m_clusterNodeMap private
Several maps that connect Acts world to sPHENIX G4 world.
Definition at line 155 of file MakeActsGeometry.h.
View newest version in sPHENIX GitHub at line 155 of file MakeActsGeometry.h
Referenced by getInttKeyFromNode(), getMvtxKeyFromNode(), and InitRun().
std::map<TrkrDefs::hitsetkey, std::vector<Surface> > MakeActsGeometry::m_clusterSurfaceMapMmEdit private
Definition at line 158 of file MakeActsGeometry.h.
View newest version in sPHENIX GitHub at line 158 of file MakeActsGeometry.h
Referenced by InitRun(), and makeMmMapPairs().
std::map<TrkrDefs::hitsetkey, Surface> MakeActsGeometry::m_clusterSurfaceMapSilicon private
Definition at line 156 of file MakeActsGeometry.h.
View newest version in sPHENIX GitHub at line 156 of file MakeActsGeometry.h
Referenced by InitRun(), makeInttMapPairs(), and makeMvtxMapPairs().
std::map<TrkrDefs::hitsetkey, std::vector<Surface> > MakeActsGeometry::m_clusterSurfaceMapTpcEdit private
Definition at line 157 of file MakeActsGeometry.h.
View newest version in sPHENIX GitHub at line 157 of file MakeActsGeometry.h
Referenced by InitRun(), and makeTpcMapPairs().
std::vector<std::shared_ptr<ActsExamples::IContextDecorator> > MakeActsGeometry::m_contextDecorators private
Acts Context decorators, which may contain e.g. calibration information.
Definition at line 152 of file MakeActsGeometry.h.
View newest version in sPHENIX GitHub at line 152 of file MakeActsGeometry.h
Referenced by getContextDecorators(), and makeGeometry().
TGeoDetector MakeActsGeometry::m_detector private
The acts geometry object.
Definition at line 198 of file MakeActsGeometry.h.
View newest version in sPHENIX GitHub at line 198 of file MakeActsGeometry.h
Referenced by buildActsSurfaces().
Acts::GeometryContext MakeActsGeometry::m_geoCtxt private
Definition at line 203 of file MakeActsGeometry.h.
View newest version in sPHENIX GitHub at line 203 of file MakeActsGeometry.h
Referenced by InitRun(), makeGeometry(), makeInttMapPairs(), makeMmMapPairs(), makeMvtxMapPairs(), and makeTpcMapPairs().
TGeoManager* MakeActsGeometry::m_geoManager = nullptr private
Definition at line 148 of file MakeActsGeometry.h.
View newest version in sPHENIX GitHub at line 148 of file MakeActsGeometry.h
Referenced by getNodes(), and makeTGeoNodeMap().
PHG4CylinderGeomContainer* MakeActsGeometry::m_geomContainerIntt = nullptr private
Definition at line 145 of file MakeActsGeometry.h.
View newest version in sPHENIX GitHub at line 145 of file MakeActsGeometry.h
Referenced by getInttHitSetKeyFromCoords(), and getNodes().
PHG4CylinderGeomContainer* MakeActsGeometry::m_geomContainerMvtx = nullptr private
Subdetector geometry containers for getting layer information.
Definition at line 144 of file MakeActsGeometry.h.
View newest version in sPHENIX GitHub at line 144 of file MakeActsGeometry.h
Referenced by getMvtxHitSetKeyFromCoords(), and getNodes().
PHG4CylinderCellGeomContainer* MakeActsGeometry::m_geomContainerTpc = nullptr private
Definition at line 146 of file MakeActsGeometry.h.
View newest version in sPHENIX GitHub at line 146 of file MakeActsGeometry.h
Referenced by getNodes().
double MakeActsGeometry::m_layerRadius[m_nTpcLayers] = {0} private
Definition at line 183 of file MakeActsGeometry.h.
View newest version in sPHENIX GitHub at line 183 of file MakeActsGeometry.h
Referenced by addActsTpcSurfaces(), getTpcHitSetKeyFromCoords(), and setPlanarSurfaceDivisions().
double MakeActsGeometry::m_layerThickness[m_nTpcLayers] = {0} private
Definition at line 184 of file MakeActsGeometry.h.
View newest version in sPHENIX GitHub at line 184 of file MakeActsGeometry.h
Referenced by addActsTpcSurfaces(), getTpcHitSetKeyFromCoords(), and setPlanarSurfaceDivisions().
std::string MakeActsGeometry::m_magField ="1.4" private
Magnetic field components to set Acts magnetic field.
Definition at line 215 of file MakeActsGeometry.h.
View newest version in sPHENIX GitHub at line 215 of file MakeActsGeometry.h
Referenced by buildActsSurfaces(), and setMagField().
Acts::MagneticFieldContext MakeActsGeometry::m_magFieldContext private
Definition at line 205 of file MakeActsGeometry.h.
View newest version in sPHENIX GitHub at line 205 of file MakeActsGeometry.h
Referenced by InitRun(), and makeGeometry().
double MakeActsGeometry::m_magFieldRescale = -1. private
Definition at line 216 of file MakeActsGeometry.h.
View newest version in sPHENIX GitHub at line 216 of file MakeActsGeometry.h
Referenced by buildActsSurfaces(), and setMagFieldRescale().
ActsExamples::Options::BFieldVariant MakeActsGeometry::m_magneticField private
Definition at line 202 of file MakeActsGeometry.h.
View newest version in sPHENIX GitHub at line 202 of file MakeActsGeometry.h
Referenced by InitRun(), and makeGeometry().
const double MakeActsGeometry::m_maxRadius[m_nTpcSectors] = {40.0, 60.0, 77.0} private
Definition at line 181 of file MakeActsGeometry.h.
View newest version in sPHENIX GitHub at line 181 of file MakeActsGeometry.h
Referenced by setPlanarSurfaceDivisions().
double MakeActsGeometry::m_maxSurfZ = 105.5 private
Definition at line 167 of file MakeActsGeometry.h.
View newest version in sPHENIX GitHub at line 167 of file MakeActsGeometry.h
Referenced by setPlanarSurfaceDivisions().
const double MakeActsGeometry::m_minRadius[m_nTpcSectors] = {30.0, 40.0, 60.0} private
Definition at line 180 of file MakeActsGeometry.h.
View newest version in sPHENIX GitHub at line 180 of file MakeActsGeometry.h
Referenced by setPlanarSurfaceDivisions().
double MakeActsGeometry::m_minSurfZ = 0. private
TPC Acts::Surface subdivisions.
Definition at line 166 of file MakeActsGeometry.h.
View newest version in sPHENIX GitHub at line 166 of file MakeActsGeometry.h
Referenced by setPlanarSurfaceDivisions().
const unsigned int MakeActsGeometry::m_mmLayerNumber[m_nMmLayers] = {55, 56} private
Definition at line 188 of file MakeActsGeometry.h.
View newest version in sPHENIX GitHub at line 188 of file MakeActsGeometry.h
Referenced by getMmHitSetKeyFromCoords().
double MakeActsGeometry::m_mmLayerRadius[m_nMmLayers] = {82.2565, 82.6998} private
Definition at line 189 of file MakeActsGeometry.h.
View newest version in sPHENIX GitHub at line 189 of file MakeActsGeometry.h
Referenced by addActsMicromegasSurfaces(), and getMmHitSetKeyFromCoords().
double MakeActsGeometry::m_mmLayerThickness[m_nMmLayers] = {0.3, 0.3} private
Definition at line 190 of file MakeActsGeometry.h.
View newest version in sPHENIX GitHub at line 190 of file MakeActsGeometry.h
Referenced by addActsMicromegasSurfaces(), and getMmHitSetKeyFromCoords().
double MakeActsGeometry::m_modulePhiStart private
Definition at line 173 of file MakeActsGeometry.h.
View newest version in sPHENIX GitHub at line 173 of file MakeActsGeometry.h
Referenced by addActsMicromegasSurfaces(), addActsTpcSurfaces(), getTpcHitSetKeyFromCoords(), and setPlanarSurfaceDivisions().
double MakeActsGeometry::m_moduleStepPhi private
Definition at line 172 of file MakeActsGeometry.h.
View newest version in sPHENIX GitHub at line 172 of file MakeActsGeometry.h
Referenced by addActsMicromegasSurfaces(), addActsTpcSurfaces(), getTpcHitSetKeyFromCoords(), and setPlanarSurfaceDivisions().
const int MakeActsGeometry::m_nMmLayers = 2 static private
Definition at line 187 of file MakeActsGeometry.h.
View newest version in sPHENIX GitHub at line 187 of file MakeActsGeometry.h
Referenced by getMmHitSetKeyFromCoords().
unsigned int MakeActsGeometry::m_nSurfPhi = 12 private
Definition at line 169 of file MakeActsGeometry.h.
View newest version in sPHENIX GitHub at line 169 of file MakeActsGeometry.h
Referenced by addActsMicromegasSurfaces(), addActsTpcSurfaces(), and setPlanarSurfaceDivisions().
unsigned int MakeActsGeometry::m_nSurfZ = 1 private
Definition at line 168 of file MakeActsGeometry.h.
View newest version in sPHENIX GitHub at line 168 of file MakeActsGeometry.h
Referenced by addActsMicromegasSurfaces(), addActsTpcSurfaces(), and setPlanarSurfaceDivisions().
const unsigned int MakeActsGeometry::m_nTpcLayers = 48 static private
These don't change, we are building the tpc this way!
Definition at line 161 of file MakeActsGeometry.h.
View newest version in sPHENIX GitHub at line 161 of file MakeActsGeometry.h
Referenced by addActsTpcSurfaces(), and getTpcHitSetKeyFromCoords().
const unsigned int MakeActsGeometry::m_nTpcModulesPerLayer = 12 private
Definition at line 162 of file MakeActsGeometry.h.
View newest version in sPHENIX GitHub at line 162 of file MakeActsGeometry.h
Referenced by addActsMicromegasSurfaces(), addActsTpcSurfaces(), getTpcHitSetKeyFromCoords(), and setPlanarSurfaceDivisions().
const int MakeActsGeometry::m_nTpcSectors = 3 static private
TPC TGeoManager editing box surfaces subdivisions.
Definition at line 179 of file MakeActsGeometry.h.
View newest version in sPHENIX GitHub at line 179 of file MakeActsGeometry.h
const unsigned int MakeActsGeometry::m_nTpcSides = 2 private
Definition at line 163 of file MakeActsGeometry.h.
View newest version in sPHENIX GitHub at line 163 of file MakeActsGeometry.h
ActsSurfaceMaps* MakeActsGeometry::m_surfMaps = nullptr private
Definition at line 209 of file MakeActsGeometry.h.
View newest version in sPHENIX GitHub at line 209 of file MakeActsGeometry.h
Referenced by createNodes(), and InitRun().
double MakeActsGeometry::m_surfStepPhi private
Definition at line 170 of file MakeActsGeometry.h.
View newest version in sPHENIX GitHub at line 170 of file MakeActsGeometry.h
Referenced by addActsMicromegasSurfaces(), addActsTpcSurfaces(), getSurfStepPhi(), and setPlanarSurfaceDivisions().
double MakeActsGeometry::m_surfStepZ private
Definition at line 171 of file MakeActsGeometry.h.
View newest version in sPHENIX GitHub at line 171 of file MakeActsGeometry.h
Referenced by addActsTpcSurfaces(), getSurfStepZ(), and setPlanarSurfaceDivisions().
TrackingGeometry MakeActsGeometry::m_tGeometry private
Acts geometry objects that are needed to create (for example) the fitter.
Definition at line 201 of file MakeActsGeometry.h.
View newest version in sPHENIX GitHub at line 201 of file MakeActsGeometry.h
Referenced by InitRun(), makeGeometry(), and unpackVolumes().
int MakeActsGeometry::m_verbosity = 0 private
Verbosity value handed from PHActsSourceLinks.
Definition at line 212 of file MakeActsGeometry.h.
View newest version in sPHENIX GitHub at line 212 of file MakeActsGeometry.h
int MakeActsGeometry::nprint_tpc private
Debugger for printing out tpc active volumes.
Definition at line 176 of file MakeActsGeometry.h.
View newest version in sPHENIX GitHub at line 176 of file MakeActsGeometry.h
Referenced by isActive(), and MakeActsGeometry().
The documentation for this class was generated from the following files:
fun4all_coresoftware/blob/master/offline/packages/trackreco/MakeActsGeometry.h
fun4all_coresoftware/blob/master/offline/packages/trackreco/MakeActsGeometry.cc