EIC Software: starlightPythia Class Reference
starlightPythia Class Reference
#include <estarlight/blob/master/include/starlightpythia.h>
Public Member Functions
starlightPythia (const inputParameters &input, beamBeamSystem &bbsystem)
virtual ~starlightPythia ()
int init (std::string pythiaParams, bool fullEventRecord=false)
virtual eXEvent produceEvent ()
virtual eXEvent produceSingleEvent (int, float)
virtual eXEvent produceDoubleEvent ()
virtual starlightConstants::event produceEvent (int &)
void setSingleMode ()
void setDoubleMode ()
void setMinGammaEnergy (double energy)
void setMaxGammaEnergy (double energy)
void setFullEventRecord (bool fer=true)
Public Member Functions inherited from eventChannel
eventChannel (const inputParameters &input, beamBeamSystem &bbsystem)
virtual ~eventChannel ()
unsigned long nmbAttempts () const
returns number of attempted events
unsigned long nmbAccepted () const
returns number of accepted events
virtual eXEvent e_produceEvent ()=0
double getTotalChannelCrossSection () const
void setTotalChannelCrossSection (double sigma)
Public Member Functions inherited from readLuminosity
readLuminosity (const inputParameters &input)
~readLuminosity ()
void read ()
void e_read ()
Private Member Functions
starlightPythia ()
starlightPythia (const starlightPythia &other)
starlightPythia & operator= (const starlightPythia &other)
bool operator== (const starlightPythia &other) const
Private Attributes
spectrum * _spectrum
bool _doDoubleEvent
double _minGammaEnergy
double _maxGammaEnergy
bool _fullEventRecord
Additional Inherited Members
Static Public Member Functions inherited from eventChannel
static void transform (const double betax, const double betay, const double betaz, double &E, double &px, double &py, double &pz, int &iFbadevent)
Lorentz-transforms given 4-vector.
static double pseudoRapidity (const double px, const double py, const double pz)
calculates pseudorapidity for given 3-momentum
Public Attributes inherited from eventChannel
beamBeamSystem _bbs
randomGenerator _randy
Protected Attributes inherited from eventChannel
unsigned long _nmbAttempts
number of attempted events
unsigned long _nmbAccepted
number of accepted events
bool _ptCutEnabled
en/disables cut in pt
double _ptCutMin
minimum pt, if cut is enabled
double _ptCutMax
maximum pt, if cut is enabled
bool _etaCutEnabled
en/disables cut in eta
double _etaCutMin
minimum eta, if cut is enabled
double _etaCutMax
maximum eta, if cut is enabled
double _totalChannelCrossSection
Detailed Description
Definition at line 31 of file starlightpythia.h.
View newest version in sPHENIX GitHub at line 31 of file starlightpythia.h
Constructor & Destructor Documentation
starlightPythia::starlightPythia (const inputParameters & input, beamBeamSystem & bbsystem)
Definition at line 29 of file starlightpythia.cpp.
View newest version in sPHENIX GitHub at line 29 of file starlightpythia.cpp
starlightPythia::~starlightPythia () virtual
Definition at line 38 of file starlightpythia.cpp.
View newest version in sPHENIX GitHub at line 38 of file starlightpythia.cpp
starlightPythia::starlightPythia () private
Prohibited
starlightPythia::starlightPythia (const starlightPythia & other) private
Member Function Documentation
int starlightPythia::init (std::string pythiaParams, bool fullEventRecord = false)
Definition at line 43 of file starlightpythia.cpp.
View newest version in sPHENIX GitHub at line 43 of file starlightpythia.cpp
References eventChannel::_bbs, _doDoubleEvent, _fullEventRecord, _maxGammaEnergy, _minGammaEnergy, eventChannel::_randy, _spectrum, spectrum::generateKdouble(), spectrum::generateKsingle(), getline, p, pythiaInterface::pygive(), pythiaInterface::pyinit(), spectrum::setMaxGammaEnergy(), and spectrum::setMinGammaEnergy().
starlightPythia& starlightPythia::operator= (const starlightPythia & other) private
bool starlightPythia::operator== (const starlightPythia & other) const private
virtual eXEvent starlightPythia::produceDoubleEvent () inline virtual
Definition at line 45 of file starlightpythia.h.
View newest version in sPHENIX GitHub at line 45 of file starlightpythia.h
eXEvent starlightPythia::produceEvent () virtual
Definition at line 79 of file starlightpythia.cpp.
View newest version in sPHENIX GitHub at line 79 of file starlightpythia.cpp
References eventChannel::_bbs, _doDoubleEvent, _fullEventRecord, _maxGammaEnergy, _spectrum, beamBeamSystem::beamLorentzGamma(), lorentzVector::Boost(), charge, spectrum::drawKsingle(), particle, pythiaInterface::pyevnt(), pythiaInterface::pygive(), pyjets_, starlightParticle::setFirstDaughter(), starlightParticle::setLastDaughter(), and starlightParticle::setStatus().
virtual starlightConstants::event starlightPythia::produceEvent (int &) inline virtual
Definition at line 47 of file starlightpythia.h.
View newest version in sPHENIX GitHub at line 47 of file starlightpythia.h
virtual eXEvent starlightPythia::produceSingleEvent (int , float) inline virtual
Definition at line 43 of file starlightpythia.h.
View newest version in sPHENIX GitHub at line 43 of file starlightpythia.h
void starlightPythia::setDoubleMode () inline
Definition at line 53 of file starlightpythia.h.
View newest version in sPHENIX GitHub at line 53 of file starlightpythia.h
References _doDoubleEvent.
void starlightPythia::setFullEventRecord (bool fer = true) inline
Definition at line 65 of file starlightpythia.h.
View newest version in sPHENIX GitHub at line 65 of file starlightpythia.h
References _fullEventRecord.
void starlightPythia::setMaxGammaEnergy (double energy) inline
Definition at line 61 of file starlightpythia.h.
View newest version in sPHENIX GitHub at line 61 of file starlightpythia.h
References _maxGammaEnergy.
void starlightPythia::setMinGammaEnergy (double energy) inline
Definition at line 57 of file starlightpythia.h.
View newest version in sPHENIX GitHub at line 57 of file starlightpythia.h
References _minGammaEnergy.
void starlightPythia::setSingleMode () inline
Definition at line 49 of file starlightpythia.h.
View newest version in sPHENIX GitHub at line 49 of file starlightpythia.h
References _doDoubleEvent.
Member Data Documentation
bool starlightPythia::_doDoubleEvent private
Should we produce a double event?
Definition at line 73 of file starlightpythia.h.
View newest version in sPHENIX GitHub at line 73 of file starlightpythia.h
Referenced by init(), produceEvent(), setDoubleMode(), and setSingleMode().
bool starlightPythia::_fullEventRecord private
Full event record or not
Definition at line 82 of file starlightpythia.h.
View newest version in sPHENIX GitHub at line 82 of file starlightpythia.h
Referenced by init(), produceEvent(), and setFullEventRecord().
double starlightPythia::_maxGammaEnergy private
Max gamma energy
Definition at line 79 of file starlightpythia.h.
View newest version in sPHENIX GitHub at line 79 of file starlightpythia.h
Referenced by init(), produceEvent(), and setMaxGammaEnergy().
double starlightPythia::_minGammaEnergy private
Min gamma energy
Definition at line 76 of file starlightpythia.h.
View newest version in sPHENIX GitHub at line 76 of file starlightpythia.h
Referenced by init(), and setMinGammaEnergy().
spectrum* starlightPythia::_spectrum private
Contains the photon spectrum
Definition at line 70 of file starlightpythia.h.
View newest version in sPHENIX GitHub at line 70 of file starlightpythia.h
Referenced by init(), and produceEvent().
The documentation for this class was generated from the following files:
estarlight/blob/master/include/starlightpythia.h
estarlight/blob/master/src/starlightpythia.cpp