EIC Software: estarlight/blob/master/utils/ConvertStarlightAsciiToTree.C File Reference
ConvertStarlightAsciiToTree.C File Reference
#include <iostream>
#include <fstream>
#include <sstream>
#include <string>
#include "TLorentzVector.h"
#include "TClonesArray.h"
#include "TTree.h"
#include "TFile.h"
Classes
struct source_electron
Functions
double IDtoMass (int particleCode)
TLorentzVector * make_beam_particle (double lorentz, int Z, int A, int dir)
void ConvertStarlightAsciiToTree (const char *inFileName="slight.out", const char *outFileName="starlight.root")
Function Documentation
void ConvertStarlightAsciiToTree (const char * inFileName = "slight.out", const char * outFileName = "starlight.root")
Definition at line 59 of file ConvertStarlightAsciiToTree.C.
View newest version in sPHENIX GitHub at line 59 of file ConvertStarlightAsciiToTree.C
References getline, IDtoMass(), configureMap::inFileName, make_beam_particle(), momentum, writeMapConfig::outFileName, and charm_jet_tagging_optimization_study::target.
double IDtoMass (int particleCode)
Definition at line 261 of file ConvertStarlightAsciiToTree.C.
View newest version in sPHENIX GitHub at line 261 of file ConvertStarlightAsciiToTree.C
References mass.
Referenced by ConvertStarlightAsciiToTree().
TLorentzVector* make_beam_particle (double lorentz, int Z, int A, int dir)
Definition at line 41 of file ConvertStarlightAsciiToTree.C.
View newest version in sPHENIX GitHub at line 41 of file ConvertStarlightAsciiToTree.C
References kdfinder::abs(), and mass.
Referenced by ConvertStarlightAsciiToTree().