EIC Software: eventChannel Class Reference
eventChannel Class Reference abstract
#include <estarlight/blob/master/include/eventchannel.h>
Public Member Functions
eventChannel (const inputParameters &input, beamBeamSystem &bbsystem)
virtual ~eventChannel ()
unsigned long nmbAttempts () const
returns number of attempted events
unsigned long nmbAccepted () const
returns number of accepted events
virtual eXEvent e_produceEvent ()=0
double getTotalChannelCrossSection () const
void setTotalChannelCrossSection (double sigma)
Public Member Functions inherited from readLuminosity
readLuminosity (const inputParameters &input)
~readLuminosity ()
void read ()
void e_read ()
Static Public Member Functions
static void transform (const double betax, const double betay, const double betaz, double &E, double &px, double &py, double &pz, int &iFbadevent)
Lorentz-transforms given 4-vector.
static double pseudoRapidity (const double px, const double py, const double pz)
calculates pseudorapidity for given 3-momentum
Public Attributes
beamBeamSystem _bbs
randomGenerator _randy
Public Attributes inherited from readLuminosity
double * _Warray
double * _BWarray
double * _Yarray
double ** _Farray
double ** _Farray1
double ** _Farray2
double ** _f_WYarray
double ** _g_Earray
std::vector< std::pair< double,
std::vector< double > > > * _g_EQ2array
double _f_max
double _f_max1
double _f_max2
double _f_WYmax
double _g_Emax
double _g_EQ2max
double _fptarray [500][500]
double _bwnormsave
Protected Attributes
unsigned long _nmbAttempts
number of attempted events
unsigned long _nmbAccepted
number of accepted events
bool _ptCutEnabled
en/disables cut in pt
double _ptCutMin
minimum pt, if cut is enabled
double _ptCutMax
maximum pt, if cut is enabled
bool _etaCutEnabled
en/disables cut in eta
double _etaCutMin
minimum eta, if cut is enabled
double _etaCutMax
maximum eta, if cut is enabled
double _totalChannelCrossSection
Protected Attributes inherited from readLuminosity
const int _ReadInputNPT
const int _ReadInputnumy
const int _ReadInputnumw
const int _ReadInputnumega
const int _ReadInputnumQ2
const int _ReadInputgg_or_gP
const int _ReadInputinterferencemode
const std::string _baseFileName
Detailed Description
Definition at line 47 of file eventchannel.h.
View newest version in sPHENIX GitHub at line 47 of file eventchannel.h
Constructor & Destructor Documentation
eventChannel::eventChannel (const inputParameters & input, beamBeamSystem & bbsystem)
Definition at line 45 of file eventchannel.cpp.
View newest version in sPHENIX GitHub at line 45 of file eventchannel.cpp
References _etaCutEnabled, _etaCutMax, _etaCutMin, _ptCutEnabled, _ptCutMax, _ptCutMin, _randy, inputParameters::etaCutEnabled(), inputParameters::etaCutMax(), inputParameters::etaCutMin(), inputParameters::ptCutEnabled(), inputParameters::ptCutMax(), inputParameters::ptCutMin(), inputParameters::randomSeed(), and randomGenerator::SetSeed().
eventChannel::~eventChannel () virtual
Definition at line 63 of file eventchannel.cpp.
View newest version in sPHENIX GitHub at line 63 of file eventchannel.cpp
Member Function Documentation
virtual eXEvent eventChannel::e_produceEvent () pure virtual
Implemented in Gammagammasingle, and Gammaavectormeson.
Referenced by e_starlight::produceEvent().
double eventChannel::getTotalChannelCrossSection () const inline
Definition at line 75 of file eventchannel.h.
View newest version in sPHENIX GitHub at line 75 of file eventchannel.h
References _totalChannelCrossSection.
Referenced by e_starlight::getTotalCrossSection().
unsigned long eventChannel::nmbAccepted () const inline
returns number of accepted events
Definition at line 56 of file eventchannel.h.
View newest version in sPHENIX GitHub at line 56 of file eventchannel.h
References _nmbAccepted.
Referenced by e_starlight::nmbAccepted().
unsigned long eventChannel::nmbAttempts () const inline
returns number of attempted events
Definition at line 55 of file eventchannel.h.
View newest version in sPHENIX GitHub at line 55 of file eventchannel.h
References _nmbAttempts.
Referenced by e_starlight::nmbAttempts().
double eventChannel::pseudoRapidity (const double px, const double py, const double pz) static
calculates pseudorapidity for given 3-momentum
Definition at line 102 of file eventchannel.cpp.
View newest version in sPHENIX GitHub at line 102 of file eventchannel.cpp
References Acts::VectorHelpers::eta(), and p.
void eventChannel::setTotalChannelCrossSection (double sigma) inline
Definition at line 76 of file eventchannel.h.
View newest version in sPHENIX GitHub at line 76 of file eventchannel.h
References _totalChannelCrossSection.
Referenced by e_Gammaanarrowvm::e_Gammaanarrowvm(), e_Gammaawidevm::e_Gammaawidevm(), Gammaaincoherentvm::Gammaaincoherentvm(), Gammaanarrowvm::Gammaanarrowvm(), Gammaawidevm::Gammaawidevm(), and Gammagammasingle::singleCrossSection().
void eventChannel::transform (const double betax, const double betay, const double betaz, double & E, double & px, double & py, double & pz, int & iFbadevent) static
Lorentz-transforms given 4-vector.
Definition at line 69 of file eventchannel.cpp.
View newest version in sPHENIX GitHub at line 69 of file eventchannel.cpp
References gamma().
Referenced by Gammaavectormeson::momenta(), Gammaavectormeson::pi0Decay(), Gammaavectormeson::twoBodyDecay(), and Gammagammasingle::twoBodyDecay().
Member Data Documentation
beamBeamSystem eventChannel::_bbs
Definition at line 69 of file eventchannel.h.
View newest version in sPHENIX GitHub at line 69 of file eventchannel.h
Referenced by starlightPythia::init(), Gammaavectormeson::momenta(), Gammagammasingle::pp1(), Gammagammasingle::pp2(), starlightPythia::produceEvent(), and Gammaavectormeson::pTgamma().
bool eventChannel::_etaCutEnabled protected
en/disables cut in eta
Definition at line 86 of file eventchannel.h.
View newest version in sPHENIX GitHub at line 86 of file eventchannel.h
Referenced by Gammaavectormeson::e_produceEvent(), and eventChannel().
double eventChannel::_etaCutMax protected
maximum eta, if cut is enabled
Definition at line 88 of file eventchannel.h.
View newest version in sPHENIX GitHub at line 88 of file eventchannel.h
Referenced by Gammaavectormeson::e_produceEvent(), and eventChannel().
double eventChannel::_etaCutMin protected
minimum eta, if cut is enabled
Definition at line 87 of file eventchannel.h.
View newest version in sPHENIX GitHub at line 87 of file eventchannel.h
Referenced by Gammaavectormeson::e_produceEvent(), and eventChannel().
unsigned long eventChannel::_nmbAccepted protected
number of accepted events
Definition at line 81 of file eventchannel.h.
View newest version in sPHENIX GitHub at line 81 of file eventchannel.h
Referenced by Gammaavectormeson::e_produceEvent(), and nmbAccepted().
unsigned long eventChannel::_nmbAttempts protected
number of attempted events
Definition at line 80 of file eventchannel.h.
View newest version in sPHENIX GitHub at line 80 of file eventchannel.h
Referenced by Gammaavectormeson::e_produceEvent(), and nmbAttempts().
bool eventChannel::_ptCutEnabled protected
en/disables cut in pt
Definition at line 83 of file eventchannel.h.
View newest version in sPHENIX GitHub at line 83 of file eventchannel.h
Referenced by Gammaavectormeson::e_produceEvent(), and eventChannel().
double eventChannel::_ptCutMax protected
maximum pt, if cut is enabled
Definition at line 85 of file eventchannel.h.
View newest version in sPHENIX GitHub at line 85 of file eventchannel.h
Referenced by Gammaavectormeson::e_produceEvent(), and eventChannel().
double eventChannel::_ptCutMin protected
minimum pt, if cut is enabled
Definition at line 84 of file eventchannel.h.
View newest version in sPHENIX GitHub at line 84 of file eventchannel.h
Referenced by Gammaavectormeson::e_produceEvent(), and eventChannel().
randomGenerator eventChannel::_randy
Definition at line 70 of file eventchannel.h.
View newest version in sPHENIX GitHub at line 70 of file eventchannel.h
Referenced by Gammaavectormeson::e_produceEvent(), eventChannel(), Gammaavectormeson::Gammaavectormeson(), Gammaavectormeson::getTheta(), starlightPythia::init(), Gammaavectormeson::momenta(), Gammagammasingle::parentMomentum(), Gammaavectormeson::pi0Decay(), Gammagammasingle::pickw(), Gammaavectormeson::pickwEgamq2(), Gammaavectormeson::pickwy(), Gammagammasingle::picky(), Gammagammasingle::pp1(), Gammagammasingle::pp2(), Gammaavectormeson::pTgamma(), Gammaavectormeson::twoBodyDecay(), Gammagammasingle::twoBodyDecay(), and Gammaavectormeson::vmpt().
double eventChannel::_totalChannelCrossSection protected
Definition at line 90 of file eventchannel.h.
View newest version in sPHENIX GitHub at line 90 of file eventchannel.h
Referenced by getTotalChannelCrossSection(), and setTotalChannelCrossSection().
The documentation for this class was generated from the following files:
estarlight/blob/master/include/eventchannel.h
estarlight/blob/master/src/eventchannel.cpp