EIC Software: EicRoot/blob/master/pCDR-2018/b0rp/acceptance.C File Reference
acceptance.C File Reference
Macros
#define _41_GEV_
#define _EX_ (45.9E-6)
#define _EY_ (2.6E-6)
#define _DPP_ (10.3E-4)
#define _X0_ (-0.73)
#define _Y0_ (0.00)
#define _SX0_ (38.76)
#define _SY0_ (0.00)
#define _SIGMA_CUT_ (10.0)
#define _DX_ (-0.19)
#define _BETA_X_ (475E3)
#define _BETA_Y_ (520E3)
Functions
gStyle SetPadLeftMargin (0.13)
gStyle SetPadBottomMargin (0.13)
cbmsim AddFriend ("cbmsim","digitization.root")
cbmsim SetBranchAddress ("RpTrackingDigiHit",&rpHitArray)
cbmsim SetBranchAddress ("B0trackerTrackingDigiHit",&b0HitArray)
cbmsim SetBranchAddress ("MCTrack",&mcTrackArray)
th0 SetMinimum (0)
th0 SetLineWidth (2)
th0 SetLineColor (kBlack)
th1 SetLineColor (kGreen)
th2 SetLineColor (kRed)
th3 SetLineColor (kBlue)
pt0 SetLineWidth (1)
pt1 SetLineWidth (3)
rw RotateY (_22mrad_)
for (unsigned ev=0;ev< nEvents;ev++)
pt0 GetXaxis () -> SetTitle("DVCS proton P_
pt0 GetYaxis () -> SetTitle("Events")
pt0 Draw ()
pt2 Draw ("SAME")
gPad SetGrid ()
Variables
TFile * ff = new TFile("simulation.root")
TTree * cbmsim = ff->Get("cbmsim")
TClonesArray * rpHitArray = new TClonesArray("EicTrackingDigiHitOrth2D")
TClonesArray * b0HitArray = new TClonesArray("EicTrackingDigiHitOrth2D")
TClonesArray * mcTrackArray = new TClonesArray("PndMCTrack")
TCanvas * c1 = new TCanvas("c1", "c1", 0, 0, 800, 500)
TH1D * th0 = new TH1D("th0", "", 250, 0., 25.)
TH1D * th1 = new TH1D("th1", "", 250, 0., 25.)
TH1D * th2 = new TH1D("th2", "", 250, 0., 25.)
TH1D * th3 = new TH1D("th3", "", 250, 0., 25.)
TH1D * pt0 = new TH1D("pt0", "" ,150, 0., 1.5)
TH1D * pt1 = new TH1D("pt1", "", 150, 0., 1.5)
TH1D * pt2 = new TH1D("pt2", "", 150, 0., 1.5)
TH1D * pt3 = new TH1D("pt3", "", 150, 0., 1.5)
TH1D * tst = new TH1D("tst", "", 10000, -300., 300.)
TGeoRotation * rw = new TGeoRotation()
double _22mrad_ = 0.022 * TMath::RadToDeg()
double sigx = sqrt(_EX_*_BETA_X_)
double sigy = sqrt(_EY_*_BETA_Y_)
double sigp = _DX_ * _DPP_ * 1E3
int nEvents = cbmsim->GetEntries()
Macro Definition Documentation
#define _41_GEV_
Definition at line 2 of file acceptance.C.
View newest version in sPHENIX GitHub at line 2 of file acceptance.C
#define _BETA_X_ (475E3)
Definition at line 49 of file acceptance.C.
View newest version in sPHENIX GitHub at line 49 of file acceptance.C
#define _BETA_Y_ (520E3)
Definition at line 50 of file acceptance.C.
View newest version in sPHENIX GitHub at line 50 of file acceptance.C
#define _DPP_ (10.3E-4)
Definition at line 15 of file acceptance.C.
View newest version in sPHENIX GitHub at line 15 of file acceptance.C
#define _DX_ (-0.19)
Definition at line 46 of file acceptance.C.
View newest version in sPHENIX GitHub at line 46 of file acceptance.C
#define _EX_ (45.9E-6)
Definition at line 11 of file acceptance.C.
View newest version in sPHENIX GitHub at line 11 of file acceptance.C
#define _EY_ (2.6E-6)
Definition at line 12 of file acceptance.C.
View newest version in sPHENIX GitHub at line 12 of file acceptance.C
#define _SIGMA_CUT_ (10.0)
Definition at line 43 of file acceptance.C.
View newest version in sPHENIX GitHub at line 43 of file acceptance.C
Referenced by for().
#define _SX0_ (38.76)
Definition at line 39 of file acceptance.C.
View newest version in sPHENIX GitHub at line 39 of file acceptance.C
Referenced by for().
#define _SY0_ (0.00)
Definition at line 40 of file acceptance.C.
View newest version in sPHENIX GitHub at line 40 of file acceptance.C
Referenced by for().
#define _X0_ (-0.73)
Definition at line 37 of file acceptance.C.
View newest version in sPHENIX GitHub at line 37 of file acceptance.C
Referenced by for().
#define _Y0_ (0.00)
Definition at line 38 of file acceptance.C.
View newest version in sPHENIX GitHub at line 38 of file acceptance.C
Referenced by for().
Function Documentation
cbmsim AddFriend ("cbmsim" , "digitization.root")
tst Draw ()
Referenced by analysis_resolution(), LoopEvalFR(), LoopEvalHR(), LoopEvalPortableCircularCut(), material_scan(), and tree::read().
q2h3 Draw ("SAME")
for ()
Definition at line 123 of file acceptance.C.
View newest version in sPHENIX GitHub at line 123 of file acceptance.C
References EicTrackingDigiHitOrth2D::_GetCoord(), _SIGMA_CUT_, _X0_, _Y0_, PndMCTrack::GetMomentum(), printf(), sigx, sigy, and theta().
q2h0 GetXaxis () -> SetTitle("DVCS proton P_
Definition at line 279 of file acceptance.C.
View newest version in sPHENIX GitHub at line 279 of file acceptance.C
Referenced by PrettyTGraphErrors(), and prettyTH1F().
q2h0 GetYaxis () -> SetTitle("Events")
Referenced by PrettyTGraphErrors(), and prettyTH1F().
rw RotateY (_22mrad_)
cbmsim SetBranchAddress ("RpTrackingDigiHit" , & rpHitArray)
Referenced by analysis_resolution().
cbmsim SetBranchAddress ("B0trackerTrackingDigiHit" , & b0HitArray)
cbmsim SetBranchAddress ("MCTrack" , & mcTrackArray)
gPad SetGrid ()
q2h0 SetLineColor (kBlack)
Referenced by analysis_resolution(), material_scan(), PrettyTGraphErrors(), prettyTH1F(), FairVTrack::SetParticle(), and FairVTrack::SetTrack().
q2h1 SetLineColor (kGreen)
pt2 SetLineColor (kRed)
q2h3 SetLineColor (kBlue)
q2h1 SetLineWidth (2)
Referenced by PrettyTGraphErrors(), and prettyTH1F().
pt0 SetLineWidth (1)
pt3 SetLineWidth (3)
q2h0 SetMinimum (0)
Referenced by PrettyTGraphErrors(), and prettyTH1F().
gStyle SetPadBottomMargin (0. 13)
gStyle SetPadLeftMargin (0. 13)
Variable Documentation
double _22mrad_ = 0.022 * TMath::RadToDeg()
Definition at line 103 of file acceptance.C.
View newest version in sPHENIX GitHub at line 103 of file acceptance.C
TClonesArray* b0HitArray = new TClonesArray("EicTrackingDigiHitOrth2D")
Definition at line 67 of file acceptance.C.
View newest version in sPHENIX GitHub at line 67 of file acceptance.C
TCanvas* c1 = new TCanvas("c1", "c1", 0, 0, 800, 500)
Definition at line 72 of file acceptance.C.
View newest version in sPHENIX GitHub at line 72 of file acceptance.C
TTree* cbmsim = ff->Get("cbmsim")
Definition at line 62 of file acceptance.C.
View newest version in sPHENIX GitHub at line 62 of file acceptance.C
Referenced by analysis(), analysis_vtx(), and stvector().
TFile* ff = new TFile("simulation.root")
Definition at line 61 of file acceptance.C.
View newest version in sPHENIX GitHub at line 61 of file acceptance.C
Referenced by analysis(), analysis_vtx(), EicRecoKalmanTask::Init(), partonx6(), Smear::ParticleMCS::Print(), pysghf(), pytbbn(), scan_viewer(), strf(), and stvector().
TClonesArray* mcTrackArray = new TClonesArray("PndMCTrack")
Definition at line 69 of file acceptance.C.
View newest version in sPHENIX GitHub at line 69 of file acceptance.C
Referenced by analysis(), analysis_vtx(), and stvector().
int nEvents = cbmsim->GetEntries()
Definition at line 122 of file acceptance.C.
View newest version in sPHENIX GitHub at line 122 of file acceptance.C
Referenced by analysis(), analysis_vtx(), Acts::Test::BOOST_AUTO_TEST_CASE(), CMDistortionAnalysis(), CMDistortionAnalysisCart(), CMDistortionAnalysisPhiR(), CMDistortionReco(), CMDistortionRecoCart(), CMDistortionRecoPhiR(), erhic::LogReaderPythia::Extract(), erhic::LogReaderPepsi::Extract(), erhic::LogReaderDjangoh::Extract(), Fun4All_G4_block(), Fun4All_G4_Clusters(), Fun4All_G4_Cylinder(), Fun4All_G4_IonGun(), Fun4All_G4_Lmon(), Fun4All_G4_sPHENIX_particle_gen(), main(), processGeometry(), read(), ReadFieldMap(), EicEventGenerator::RestrictEventChunkSize(), simulation(), SmearTree(), and stvector().
TH1D* pt0 = new TH1D("pt0", "" ,150, 0., 1.5)
Definition at line 84 of file acceptance.C.
View newest version in sPHENIX GitHub at line 84 of file acceptance.C
TH1D* pt1 = new TH1D("pt1", "", 150, 0., 1.5)
Definition at line 86 of file acceptance.C.
View newest version in sPHENIX GitHub at line 86 of file acceptance.C
Referenced by arorie(), pymirm(), Gammaavectormeson::vmpt(), and photonNucleusLuminosity::vmsigmapt().
TH1D* pt2 = new TH1D("pt2", "", 150, 0., 1.5)
Definition at line 87 of file acceptance.C.
View newest version in sPHENIX GitHub at line 87 of file acceptance.C
Referenced by dokinematics(), fjet(), fjetrig(), g(), getqvec(), gphoton(), lqev(), lqgev(), lqqbev(), luprep(), lyremn(), Gammaavectormeson::momenta(), pyevwt(), pyhiremn(), pykcut(), pymirm(), pyprep(), pyptfs(), pyptis(), pyptmi(), erhic::EventPythia::SetHardPt2(), Gammaavectormeson::vmpt(), and photonNucleusLuminosity::vmsigmapt().
TH1D* pt3 = new TH1D("pt3", "", 150, 0., 1.5)
Definition at line 88 of file acceptance.C.
View newest version in sPHENIX GitHub at line 88 of file acceptance.C
Referenced by arorie().
TClonesArray* rpHitArray = new TClonesArray("EicTrackingDigiHitOrth2D")
Definition at line 65 of file acceptance.C.
View newest version in sPHENIX GitHub at line 65 of file acceptance.C
TGeoRotation* rw = new TGeoRotation()
Definition at line 102 of file acceptance.C.
View newest version in sPHENIX GitHub at line 102 of file acceptance.C
Referenced by aerogel(), EicCadWizard::AssembleRootFiles(), VstGeoParData::ConstructGeometry(), FstGeoParData::ConstructGeometry(), MuMegasGeoParData::ConstructGeometry(), GemGeoParData::ConstructGeometry(), MapsGeoParData::ConstructMimosaCell(), MapsGeoParData::ConstructStave(), vc2020_03_20::CreateGeometry(), fbgt(), femc(), FstDisc::FstDisc(), GemWheel::GemWheel(), EicProtoGenerator::GetModifiedTrack(), hcal(), EicBeamLineElementMap::Initialize(), EicBeamLineElementGrad::Initialize(), AnnularFieldSim::interpolatedFieldIntegral(), MuMegasBarrel::MuMegasBarrel(), GemGeoParData::PlaceMaterialLayer(), pyrvr(), AnnularFieldSim::sum_nonlocal_field_at(), tpc(), tpc_builder(), vtx_builder(), and zdc().
double sigp = _DX_ * _DPP_ * 1E3
Definition at line 116 of file acceptance.C.
View newest version in sPHENIX GitHub at line 116 of file acceptance.C
Referenced by luxdif(), pyhixtot(), and pyxdif().
sigx = sqrt(_EX_*_BETA_X_)
Definition at line 115 of file acceptance.C.
View newest version in sPHENIX GitHub at line 115 of file acceptance.C
Referenced by for(), LSLTrackRep::init(), and LSLTrackRep::LSLTrackRep().
double sigy = sqrt(_EY_*_BETA_Y_)
Definition at line 115 of file acceptance.C.
View newest version in sPHENIX GitHub at line 115 of file acceptance.C
Referenced by for(), LSLTrackRep::init(), and LSLTrackRep::LSLTrackRep().
TH1D* th0 = new TH1D("th0", "", 250, 0., 25.)
Definition at line 74 of file acceptance.C.
View newest version in sPHENIX GitHub at line 74 of file acceptance.C
TH1D* th1 = new TH1D("th1", "", 250, 0., 25.)
Definition at line 76 of file acceptance.C.
View newest version in sPHENIX GitHub at line 76 of file acceptance.C
Referenced by BEmcProfile::PredictEnergy(), BEmcProfile::PredictEnergyR(), PHG4ParticleGeneratorD0::process_event(), and PHG4ParticleGeneratorVectorMeson::process_event().
TH1D* th2 = new TH1D("th2", "", 250, 0., 25.)
Definition at line 77 of file acceptance.C.
View newest version in sPHENIX GitHub at line 77 of file acceptance.C
Referenced by BEmcProfile::PredictEnergy(), BEmcProfile::PredictEnergyR(), pyhisigh(), pysgex(), pysghf(), pysghg(), pysgqc(), pysgsu(), pysgtc(), pysgwz(), pysigh(), pystbh(), and pyxued().
TH1D* th3 = new TH1D("th3", "", 250, 0., 25.)
Definition at line 78 of file acceptance.C.
View newest version in sPHENIX GitHub at line 78 of file acceptance.C
TH1D* tst = new TH1D("tst", "", 10000, -300., 300.)
Definition at line 91 of file acceptance.C.
View newest version in sPHENIX GitHub at line 91 of file acceptance.C