EIC Software: TpcDirectLaserReconstruction Class Reference
TpcDirectLaserReconstruction Class Reference
#include <fun4all_coresoftware/blob/master/offline/packages/tpccalib/TpcDirectLaserReconstruction.h>
Public Member Functions
TpcDirectLaserReconstruction (const std::string &="TpcDirectLaserReconstruction")
constructor
int Init (PHCompositeNode *) override
global initialization
int InitRun (PHCompositeNode *) override
run initialization
int process_event (PHCompositeNode *) override
event processing
int End (PHCompositeNode *) override
end of processing
void SetDefaultParameters () override
parameters
void set_outputfile (const std::string &filename)
output file
void set_savehistograms (bool value)
set to true to store evaluation histograms and ntuples
void set_histogram_outputfile (const std::string &outputfile)
output file name for evaluation histograms
void set_grid_dimensions (int phibins, int rbins, int zbins)
set grid dimensions
Public Member Functions inherited from SubsysReco
~SubsysReco () override
virtual int EndRun (const int)
Called at the end of each run.
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
void Print (const std::string &="ALL") const override
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Public Member Functions inherited from PHParameterInterface
PHParameterInterface (const std::string &name)
PHParameterInterface (const PHParameterInterface &)=delete
virtual ~PHParameterInterface ()
void set_paramname (const std::string &name)
void set_double_param (const std::string &name, const double dval)
double get_double_param (const std::string &name) const
void set_int_param (const std::string &name, const int ival)
int get_int_param (const std::string &name) const
void set_string_param (const std::string &name, const std::string &sval)
std::string get_string_param (const std::string &name) const
void UpdateParametersWithMacro ()
void SaveToNodeTree (PHCompositeNode *runNode, const std::string &nodename)
void PutOnParNode (PHCompositeNode *parNode, const std::string &nodename)
Private Member Functions
int load_nodes (PHCompositeNode *)
load nodes
void create_histograms ()
create evaluation histograms
void process_tracks ()
process tracks
void process_track (SvtxTrack *)
process track
int get_cell_index (const Acts::Vector3D &) const
get relevant cell for a given cluster
Private Attributes
std::string m_outputfile = "TpcSpaceChargeMatrices.root"
output file
std::unique_ptr
< TpcSpaceChargeMatrixContainer > m_matrix_container
matrix container
selection parameters
float m_max_dca = 1.5
float m_max_drphi = 0.5
residual cuts in r, phi plane
float m_max_dz = 0.5
residual cuts in r, z plane
counters
int m_total_clusters = 0
int m_accepted_clusters = 0
nodes
ActsSurfaceMaps * m_surfmaps = nullptr
Acts surface maps for surface lookup.
ActsTrackingGeometry * m_tGeometry = nullptr
Acts tracking geometry for surface lookup.
ActsTransformations m_transformer
acts transformation
TrkrHitSetContainer * m_hitsetcontainer = nullptr
hitset containers
SvtxTrackMap * m_track_map = nullptr
tracks
TrkrClusterContainer * m_cluster_map = nullptr
evaluation
bool m_savehistograms = false
std::string m_histogramfilename = "TpcDirectLaserReconstruction.root"
std::unique_ptr< TFile > m_histogramfile = nullptr
TH2 * h_dca_layer = nullptr
dca vs layer number
TH2 * h_deltarphi_layer = nullptr
delta rphi vs layer number
TH2 * h_deltaz_layer = nullptr
delta z vs layer number
TH3 * h_entries = nullptr
number of entries per cell
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = INT_MAX - 10
}
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Protected Member Functions inherited from PHParameterInterface
void set_default_double_param (const std::string &name, const double dval)
void set_default_int_param (const std::string &name, const int ival)
void set_default_string_param (const std::string &name, const std::string &sval)
void InitializeParameters ()
Detailed Description
Definition at line 30 of file TpcDirectLaserReconstruction.h.
View newest version in sPHENIX GitHub at line 30 of file TpcDirectLaserReconstruction.h
Constructor & Destructor Documentation
TpcDirectLaserReconstruction::TpcDirectLaserReconstruction (const std::string & name = "TpcDirectLaserReconstruction")
constructor
Definition at line 105 of file TpcDirectLaserReconstruction.cc.
View newest version in sPHENIX GitHub at line 105 of file TpcDirectLaserReconstruction.cc
References PHParameterInterface::InitializeParameters().
Member Function Documentation
void TpcDirectLaserReconstruction::create_histograms () private
create evaluation histograms
Definition at line 236 of file TpcDirectLaserReconstruction.cc.
View newest version in sPHENIX GitHub at line 236 of file TpcDirectLaserReconstruction.cc
References h_dca_layer, h_deltarphi_layer, h_deltaz_layer, h_entries, m_histogramfile, m_histogramfilename, m_matrix_container, and phibins.
Referenced by Init().
int TpcDirectLaserReconstruction::End (PHCompositeNode *) override virtual
end of processing
Reimplemented from SubsysReco.
Definition at line 161 of file TpcDirectLaserReconstruction.cc.
View newest version in sPHENIX GitHub at line 161 of file TpcDirectLaserReconstruction.cc
References Fun4AllReturnCodes::EVENT_OK, h_dca_layer, h_deltarphi_layer, h_deltaz_layer, h_entries, m_accepted_clusters, m_histogramfile, m_matrix_container, m_outputfile, m_savehistograms, m_total_clusters, and run_skim::outputfile.
int TpcDirectLaserReconstruction::get_cell_index (const Acts::Vector3D & global) const private
get relevant cell for a given cluster
Definition at line 483 of file TpcDirectLaserReconstruction.cc.
View newest version in sPHENIX GitHub at line 483 of file TpcDirectLaserReconstruction.cc
References QAG4Util::get_r(), ir(), m_matrix_container, M_PI, phibins, and z.
Referenced by process_track().
int TpcDirectLaserReconstruction::Init (PHCompositeNode *) override virtual
global initialization
Reimplemented from SubsysReco.
Definition at line 114 of file TpcDirectLaserReconstruction.cc.
View newest version in sPHENIX GitHub at line 114 of file TpcDirectLaserReconstruction.cc
References create_histograms(), Fun4AllReturnCodes::EVENT_OK, m_accepted_clusters, m_savehistograms, and m_total_clusters.
int TpcDirectLaserReconstruction::InitRun (PHCompositeNode *) override virtual
run initialization
Reimplemented from SubsysReco.
Definition at line 124 of file TpcDirectLaserReconstruction.cc.
View newest version in sPHENIX GitHub at line 124 of file TpcDirectLaserReconstruction.cc
References Fun4AllReturnCodes::EVENT_OK, PHParameterInterface::get_double_param(), m_matrix_container, m_max_dca, m_max_drphi, m_max_dz, m_outputfile, PHParameterInterface::UpdateParametersWithMacro(), and Fun4AllBase::Verbosity().
int TpcDirectLaserReconstruction::load_nodes (PHCompositeNode * topNode) private
load nodes
Definition at line 212 of file TpcDirectLaserReconstruction.cc.
View newest version in sPHENIX GitHub at line 212 of file TpcDirectLaserReconstruction.cc
References Fun4AllReturnCodes::EVENT_OK, m_cluster_map, m_hitsetcontainer, m_surfmaps, m_tGeometry, and m_track_map.
Referenced by process_event().
int TpcDirectLaserReconstruction::process_event (PHCompositeNode * topNode) override virtual
event processing
Reimplemented from SubsysReco.
Definition at line 150 of file TpcDirectLaserReconstruction.cc.
View newest version in sPHENIX GitHub at line 150 of file TpcDirectLaserReconstruction.cc
References Fun4AllReturnCodes::EVENT_OK, load_nodes(), and process_tracks().
void TpcDirectLaserReconstruction::process_track (SvtxTrack * track) private
process track
Definition at line 279 of file TpcDirectLaserReconstruction.cc.
View newest version in sPHENIX GitHub at line 279 of file TpcDirectLaserReconstruction.cc
References cos(), QAG4Util::delta_phi(), dz, get_cell_index(), SvtxTrackState_v1::get_px(), SvtxTrack::get_px(), SvtxTrackState_v1::get_py(), SvtxTrack::get_py(), SvtxTrackState_v1::get_pz(), SvtxTrack::get_pz(), QAG4Util::get_r(), SvtxTrack::get_x(), SvtxTrack::get_y(), SvtxTrack::get_z(), TrkrClusterContainer::getClusters(), ActsTransformations::getGlobalPosition(), TrkrHitSetContainer::getHitSets(), TrkrDefs::getLayer(), TrkrDefs::getTrkrId(), h_dca_layer, h_deltarphi_layer, h_deltaz_layer, h_entries, SvtxTrack::insert_cluster_key(), SvtxTrack::insert_state(), G4TTL::layer, m_accepted_clusters, m_cluster_map, m_hitsetcontainer, m_matrix_container, m_max_dca, M_PI, m_savehistograms, m_surfmaps, m_tGeometry, m_transformer, Acts::Test::origin(), SvtxTrackState_v1::set_px(), SvtxTrackState_v1::set_py(), SvtxTrackState_v1::set_pz(), SvtxTrackState_v1::set_x(), SvtxTrackState_v1::set_y(), SvtxTrackState_v1::set_z(), square(), t, TrkrDefs::tpcId, and Fun4AllBase::Verbosity().
Referenced by process_tracks().
void TpcDirectLaserReconstruction::process_tracks () private
process tracks
Definition at line 260 of file TpcDirectLaserReconstruction.cc.
View newest version in sPHENIX GitHub at line 260 of file TpcDirectLaserReconstruction.cc
References SvtxTrackMap::begin(), SvtxTrackMap::end(), TrkrClusterContainer::getClusters(), TrkrHitSetContainer::getHitSets(), TrkrDefs::getTrkrId(), m_cluster_map, m_hitsetcontainer, m_total_clusters, m_track_map, process_track(), and TrkrDefs::tpcId.
Referenced by process_event().
void TpcDirectLaserReconstruction::set_grid_dimensions (int phibins, int rbins, int zbins)
set grid dimensions
Definition at line 208 of file TpcDirectLaserReconstruction.cc.
View newest version in sPHENIX GitHub at line 208 of file TpcDirectLaserReconstruction.cc
References m_matrix_container.
void TpcDirectLaserReconstruction::set_histogram_outputfile (const std::string & outputfile) inline
output file name for evaluation histograms
Definition at line 64 of file TpcDirectLaserReconstruction.h.
View newest version in sPHENIX GitHub at line 64 of file TpcDirectLaserReconstruction.h
References m_histogramfilename, and run_skim::outputfile.
void TpcDirectLaserReconstruction::set_outputfile (const std::string & filename) inline
output file
this is the file where space charge matrix container is stored
Definition at line 57 of file TpcDirectLaserReconstruction.h.
View newest version in sPHENIX GitHub at line 57 of file TpcDirectLaserReconstruction.h
References INPUTHEPMC::filename, and m_outputfile.
Referenced by TPC_Clustering().
void TpcDirectLaserReconstruction::set_savehistograms (bool value) inline
set to true to store evaluation histograms and ntuples
Definition at line 61 of file TpcDirectLaserReconstruction.h.
View newest version in sPHENIX GitHub at line 61 of file TpcDirectLaserReconstruction.h
References m_savehistograms, and value.
void TpcDirectLaserReconstruction::SetDefaultParameters () override virtual
parameters
Implements PHParameterInterface.
Definition at line 192 of file TpcDirectLaserReconstruction.cc.
View newest version in sPHENIX GitHub at line 192 of file TpcDirectLaserReconstruction.cc
References PHParameterInterface::set_default_double_param().
Member Data Documentation
TH2* TpcDirectLaserReconstruction::h_dca_layer = nullptr private
dca vs layer number
Definition at line 140 of file TpcDirectLaserReconstruction.h.
View newest version in sPHENIX GitHub at line 140 of file TpcDirectLaserReconstruction.h
Referenced by create_histograms(), End(), and process_track().
TH2* TpcDirectLaserReconstruction::h_deltarphi_layer = nullptr private
delta rphi vs layer number
Definition at line 143 of file TpcDirectLaserReconstruction.h.
View newest version in sPHENIX GitHub at line 143 of file TpcDirectLaserReconstruction.h
Referenced by create_histograms(), End(), and process_track().
TH2* TpcDirectLaserReconstruction::h_deltaz_layer = nullptr private
delta z vs layer number
Definition at line 146 of file TpcDirectLaserReconstruction.h.
View newest version in sPHENIX GitHub at line 146 of file TpcDirectLaserReconstruction.h
Referenced by create_histograms(), End(), and process_track().
TH3* TpcDirectLaserReconstruction::h_entries = nullptr private
number of entries per cell
Definition at line 149 of file TpcDirectLaserReconstruction.h.
View newest version in sPHENIX GitHub at line 149 of file TpcDirectLaserReconstruction.h
Referenced by create_histograms(), End(), and process_track().
int TpcDirectLaserReconstruction::m_accepted_clusters = 0 private
Definition at line 108 of file TpcDirectLaserReconstruction.h.
View newest version in sPHENIX GitHub at line 108 of file TpcDirectLaserReconstruction.h
Referenced by End(), Init(), and process_track().
TrkrClusterContainer* TpcDirectLaserReconstruction::m_cluster_map = nullptr private
Definition at line 130 of file TpcDirectLaserReconstruction.h.
View newest version in sPHENIX GitHub at line 130 of file TpcDirectLaserReconstruction.h
Referenced by load_nodes(), process_track(), and process_tracks().
std::unique_ptr<TFile> TpcDirectLaserReconstruction::m_histogramfile = nullptr private
Definition at line 137 of file TpcDirectLaserReconstruction.h.
View newest version in sPHENIX GitHub at line 137 of file TpcDirectLaserReconstruction.h
Referenced by create_histograms(), and End().
std::string TpcDirectLaserReconstruction::m_histogramfilename = "TpcDirectLaserReconstruction.root" private
Definition at line 136 of file TpcDirectLaserReconstruction.h.
View newest version in sPHENIX GitHub at line 136 of file TpcDirectLaserReconstruction.h
Referenced by create_histograms(), and set_histogram_outputfile().
TrkrHitSetContainer* TpcDirectLaserReconstruction::m_hitsetcontainer = nullptr private
hitset containers
Definition at line 124 of file TpcDirectLaserReconstruction.h.
View newest version in sPHENIX GitHub at line 124 of file TpcDirectLaserReconstruction.h
Referenced by load_nodes(), process_track(), and process_tracks().
std::unique_ptr<TpcSpaceChargeMatrixContainer> TpcDirectLaserReconstruction::m_matrix_container private
matrix container
Definition at line 103 of file TpcDirectLaserReconstruction.h.
View newest version in sPHENIX GitHub at line 103 of file TpcDirectLaserReconstruction.h
Referenced by create_histograms(), End(), get_cell_index(), InitRun(), process_track(), and set_grid_dimensions().
float TpcDirectLaserReconstruction::m_max_dca = 1.5 private
Definition at line 93 of file TpcDirectLaserReconstruction.h.
View newest version in sPHENIX GitHub at line 93 of file TpcDirectLaserReconstruction.h
Referenced by InitRun(), and process_track().
float TpcDirectLaserReconstruction::m_max_drphi = 0.5 private
residual cuts in r, phi plane
Definition at line 96 of file TpcDirectLaserReconstruction.h.
View newest version in sPHENIX GitHub at line 96 of file TpcDirectLaserReconstruction.h
Referenced by InitRun().
float TpcDirectLaserReconstruction::m_max_dz = 0.5 private
residual cuts in r, z plane
Definition at line 99 of file TpcDirectLaserReconstruction.h.
View newest version in sPHENIX GitHub at line 99 of file TpcDirectLaserReconstruction.h
Referenced by InitRun().
std::string TpcDirectLaserReconstruction::m_outputfile = "TpcSpaceChargeMatrices.root" private
output file
Definition at line 88 of file TpcDirectLaserReconstruction.h.
View newest version in sPHENIX GitHub at line 88 of file TpcDirectLaserReconstruction.h
Referenced by End(), InitRun(), and set_outputfile().
bool TpcDirectLaserReconstruction::m_savehistograms = false private
Definition at line 135 of file TpcDirectLaserReconstruction.h.
View newest version in sPHENIX GitHub at line 135 of file TpcDirectLaserReconstruction.h
Referenced by End(), Init(), process_track(), and set_savehistograms().
ActsSurfaceMaps* TpcDirectLaserReconstruction::m_surfmaps = nullptr private
Acts surface maps for surface lookup.
Definition at line 115 of file TpcDirectLaserReconstruction.h.
View newest version in sPHENIX GitHub at line 115 of file TpcDirectLaserReconstruction.h
Referenced by load_nodes(), and process_track().
ActsTrackingGeometry* TpcDirectLaserReconstruction::m_tGeometry = nullptr private
Acts tracking geometry for surface lookup.
Definition at line 118 of file TpcDirectLaserReconstruction.h.
View newest version in sPHENIX GitHub at line 118 of file TpcDirectLaserReconstruction.h
Referenced by load_nodes(), and process_track().
int TpcDirectLaserReconstruction::m_total_clusters = 0 private
Definition at line 107 of file TpcDirectLaserReconstruction.h.
View newest version in sPHENIX GitHub at line 107 of file TpcDirectLaserReconstruction.h
Referenced by End(), Init(), and process_tracks().
SvtxTrackMap* TpcDirectLaserReconstruction::m_track_map = nullptr private
tracks
Definition at line 127 of file TpcDirectLaserReconstruction.h.
View newest version in sPHENIX GitHub at line 127 of file TpcDirectLaserReconstruction.h
Referenced by load_nodes(), and process_tracks().
ActsTransformations TpcDirectLaserReconstruction::m_transformer private
acts transformation
Definition at line 121 of file TpcDirectLaserReconstruction.h.
View newest version in sPHENIX GitHub at line 121 of file TpcDirectLaserReconstruction.h
Referenced by process_track().
The documentation for this class was generated from the following files:
fun4all_coresoftware/blob/master/offline/packages/tpccalib/TpcDirectLaserReconstruction.h
fun4all_coresoftware/blob/master/offline/packages/tpccalib/TpcDirectLaserReconstruction.cc