EIC Software: Acts::PlaneLayer Class Reference
Acts::PlaneLayer Class Reference
#include <fun4all_acts/blob/master/Core/include/Acts/Geometry/PlaneLayer.hpp>
Public Member Functions
PlaneLayer ()=delete
Default Constructor - deleted.
PlaneLayer (const PlaneLayer &pla)=delete
Copy constructor of PlaneLayer - deleted.
PlaneLayer & operator= (const PlaneLayer &)=delete
Assignment operator for PlaneLayers - deleted.
~PlaneLayer () override=default
Destructor.
const PlaneSurface & surfaceRepresentation () const override
PlaneSurface & surfaceRepresentation () override
Public Member Functions inherited from Acts::PlaneSurface
~PlaneSurface () override=default
Destructor - defaulted.
PlaneSurface & operator= (const PlaneSurface &other)
const Vector3D normal (const GeometryContext &gctx, const Vector2D &lposition) const final
const Vector3D binningPosition (const GeometryContext &gctx, BinningValue bValue) const final
SurfaceType type () const override
Return the surface type.
const SurfaceBounds & bounds () const override
Return method for bounds object of this surfrace.
void localToGlobal (const GeometryContext &gctx, const Vector2D &lposition, const Vector3D &momentum, Vector3D &position) const override
bool globalToLocal (const GeometryContext &gctx, const Vector3D &position, const Vector3D &momentum, Vector2D &lposition) const override
double pathCorrection (const GeometryContext &gctx, const Vector3D &position, const Vector3D &direction) const final
Intersection intersectionEstimate (const GeometryContext &gctx, const Vector3D &position, const Vector3D &direction, const BoundaryCheck &bcheck=false) const final
Straight line intersection schema.
Polyhedron polyhedronRepresentation (const GeometryContext &gctx, size_t lseg) const override
std::string name () const override
Return properly formatted class name for screen output.
Public Member Functions inherited from Acts::Surface
virtual ~Surface ()
std::shared_ptr< Surface > getSharedPtr ()
std::shared_ptr< const Surface > getSharedPtr () const
Surface & operator= (const Surface &other)
virtual bool operator== (const Surface &other) const
virtual bool operator!= (const Surface &sf) const
virtual const Transform3D & transform (const GeometryContext &gctx) const
virtual const Vector3D center (const GeometryContext &gctx) const
virtual const Vector3D normal (const GeometryContext &gctx, const Vector3D &position) const
virtual const Vector3D normal (const GeometryContext &gctx) const
const DetectorElementBase * associatedDetectorElement () const
const Layer * associatedLayer () const
void associateLayer (const Layer &lay)
const ISurfaceMaterial * surfaceMaterial () const
const std::shared_ptr< const
ISurfaceMaterial > & surfaceMaterialSharedPtr () const
void assignSurfaceMaterial (std::shared_ptr< const ISurfaceMaterial > material)
bool isOnSurface (const GeometryContext &gctx, const Vector3D &position, const Vector3D &momentum, const BoundaryCheck &bcheck=true) const
virtual bool insideBounds (const Vector2D &lposition, const BoundaryCheck &bcheck=true) const
virtual const
Acts::RotationMatrix3D referenceFrame (const GeometryContext &gctx, const Vector3D &position, const Vector3D &momentum) const
virtual void initJacobianToGlobal (const GeometryContext &gctx, BoundToFreeMatrix &jacobian, const Vector3D &position, const Vector3D &direction, const BoundVector &pars) const
virtual const RotationMatrix3D initJacobianToLocal (const GeometryContext &gctx, FreeToBoundMatrix &jacobian, const Vector3D &position, const Vector3D &direction) const
virtual const BoundRowVector derivativeFactors (const GeometryContext &gctx, const Vector3D &position, const Vector3D &direction, const RotationMatrix3D &rft, const BoundToFreeMatrix &jacobian) const
virtual SurfaceIntersection intersect (const GeometryContext &gctx, const Vector3D &position, const Vector3D &direction, const BoundaryCheck &bcheck) const
virtual std::ostream & toStream (const GeometryContext &gctx, std::ostream &sl) const
Public Member Functions inherited from Acts::GeometryObject
GeometryObject ()=default
Defaulted construrctor.
GeometryObject (const GeometryObject &)=default
Defaulted copy constructor.
GeometryObject (const GeometryID &geoID)
GeometryObject & operator= (const GeometryObject &geoID)
const GeometryID & geoID () const
virtual double binningPositionValue (const GeometryContext &gctx, BinningValue bValue) const
void assignGeoID (const GeometryID &geoID)
Public Member Functions inherited from Acts::Layer
Layer ()=delete
Default Constructor - deleted.
Layer (const Layer &)=delete
Copy Constructor - deleted.
virtual ~Layer ()=default
Destructor.
Layer & operator= (const Layer &)=delete
const SurfaceArray * surfaceArray () const
Return the entire SurfaceArray, returns a nullptr if no SurfaceArray.
SurfaceArray * surfaceArray ()
Non-const version.
double thickness () const
virtual bool isOnLayer (const GeometryContext &gctx, const Vector3D &position, const BoundaryCheck &bcheck=true) const
const ApproachDescriptor * approachDescriptor () const
Return method for the approach descriptor, can be nullptr.
ApproachDescriptor * approachDescriptor ()
Non-const version of the approach descriptor.
template<typename options_t >
bool resolve (const options_t &options) const
virtual bool resolve (bool resolveSensitive, bool resolveMaterial, bool resolvePassive) const
template<typename options_t >
std::vector< SurfaceIntersection > compatibleSurfaces (const GeometryContext &gctx, const Vector3D &position, const Vector3D &direction, const options_t &options) const
Decompose Layer into (compatible) surfaces.
template<typename options_t >
const SurfaceIntersection surfaceOnApproach (const GeometryContext &gctx, const Vector3D &position, const Vector3D &direction, const options_t &options) const
const Layer * nextLayer (const GeometryContext &gctx, const Vector3D &position, const Vector3D &direction) const
const TrackingVolume * trackingVolume () const
const AbstractVolume * representingVolume () const
LayerType layerType () const
return the LayerType
Static Public Member Functions
static MutableLayerPtr create (std::shared_ptr< const Transform3D > transform, std::shared_ptr< const PlanarBounds > pbounds, std::unique_ptr< SurfaceArray > surfaceArray=nullptr, double thickness=0., std::unique_ptr< ApproachDescriptor > ad=nullptr, LayerType laytyp=Acts::active)
Protected Member Functions
PlaneLayer (std::shared_ptr< const Transform3D > transform, std::shared_ptr< const PlanarBounds > &pbounds, std::unique_ptr< SurfaceArray > surfaceArray=nullptr, double thickness=0., std::unique_ptr< ApproachDescriptor > ades=nullptr, LayerType laytyp=Acts::active)
PlaneLayer (const PlaneLayer &pla, const Transform3D &shift)
Protected Member Functions inherited from Acts::PlaneSurface
PlaneSurface ()
Default Constructor - needed for persistency.
PlaneSurface (const PlaneSurface &other)
PlaneSurface (const GeometryContext &gctx, const PlaneSurface &other, const Transform3D &transf)
PlaneSurface (const Vector3D &center, const Vector3D &normal)
PlaneSurface (const std::shared_ptr< const PlanarBounds > &pbounds, const DetectorElementBase &detelement)
PlaneSurface (std::shared_ptr< const Transform3D > htrans, std::shared_ptr< const PlanarBounds > pbounds=nullptr)
Protected Member Functions inherited from Acts::Surface
Surface (std::shared_ptr< const Transform3D > tform=nullptr)
Surface (const Surface &other)
Surface (const DetectorElementBase &detelement)
Surface (const GeometryContext &gctx, const Surface &other, const Transform3D &shift)
Protected Member Functions inherited from Acts::Layer
Layer (std::unique_ptr< SurfaceArray > surfaceArray, double thickness=0., std::unique_ptr< ApproachDescriptor > ades=nullptr, LayerType laytyp=passive)
void encloseTrackingVolume (const TrackingVolume &tvol)
Private Member Functions
void buildApproachDescriptor ()
private helper method to build approach surfaces
Additional Inherited Members
Public Types inherited from Acts::Surface
enum SurfaceType {
Cone = 0, Cylinder = 1, Disc = 2, Perigee = 3,
Plane = 4, Straw = 5, Curvilinear = 6, Other = 7
}
Protected Attributes inherited from Acts::PlaneSurface
std::shared_ptr< const
PlanarBounds > m_bounds
the bounds of this surface
Protected Attributes inherited from Acts::Layer
NextLayers m_nextLayers
the previous Layer according to BinGenUtils
const BinUtility * m_nextLayerUtility = nullptr
std::unique_ptr< const
SurfaceArray > m_surfaceArray = nullptr
double m_layerThickness = 0.
Thickness of the Layer.
std::unique_ptr< const
ApproachDescriptor > m_approachDescriptor = nullptr
const TrackingVolume * m_trackingVolume = nullptr
the enclosing TrackingVolume
std::unique_ptr< AbstractVolume > m_representingVolume = nullptr
LayerType m_layerType
make a passive/active either way
int m_ssRepresentingSurface = 0
sub structure indication
int m_ssSensitiveSurfaces = 0
int m_ssApproachSurfaces = 0
Detailed Description
Class to describe a planar detector layer for tracking, it inhertis from both, Layer base class and PlaneSurface class
Definition at line 28 of file PlaneLayer.hpp.
View newest version in sPHENIX GitHub at line 28 of file PlaneLayer.hpp
Constructor & Destructor Documentation
Acts::PlaneLayer::PlaneLayer () delete
Default Constructor - deleted.
Referenced by create().
Acts::PlaneLayer::PlaneLayer (const PlaneLayer & pla) delete
Copy constructor of PlaneLayer - deleted.
Acts::PlaneLayer::~PlaneLayer () override default
Destructor.
Acts::PlaneLayer::PlaneLayer (std::shared_ptr< const Transform3D > transform, std::shared_ptr< const PlanarBounds > & pbounds, std::unique_ptr< SurfaceArray > surfaceArray = nullptr, double thickness = 0., std::unique_ptr< ApproachDescriptor > ades = nullptr, LayerType laytyp = Acts::active) protected
Private constructor for a PlaneLayer is called by create(args*)
Parameters
transform which places the layer in the global frame
pbounds the planar bounds that define the layer dimensions
surfaceArray is the surface array that holds the sensitive surfaces
thickness is the thickness of the layer (normal direction to plane)
ades is the approach descriptor for describing the approach surface
laytyp is the layer type
Returns
shared pointer to a PlaneLayer
Definition at line 21 of file PlaneLayer.cpp.
View newest version in sPHENIX GitHub at line 21 of file PlaneLayer.cpp
References Acts::Layer::approachDescriptor(), Acts::Surface::associateLayer(), buildApproachDescriptor(), Acts::Layer::m_approachDescriptor, Acts::Layer::m_surfaceArray, and Acts::ApproachDescriptor::registerLayer().
Acts::PlaneLayer::PlaneLayer (const PlaneLayer & pla, const Transform3D & shift) protected
Private constructor for a PlaneLayer, is called by create(arge*
Parameters
pla is the plain layer to be coped
shift is the additional shift applied after copying
Member Function Documentation
void Acts::PlaneLayer::buildApproachDescriptor () private
private helper method to build approach surfaces
Definition at line 50 of file PlaneLayer.cpp.
View newest version in sPHENIX GitHub at line 50 of file PlaneLayer.cpp
References Acts::Surface::associateLayer(), Acts::Surface::center(), Acts::PlaneSurface::m_bounds, Acts::Layer::m_layerThickness, Acts::Surface::normal(), and Acts::Surface::transform().
Referenced by PlaneLayer().
static MutableLayerPtr Acts::PlaneLayer::create (std::shared_ptr< const Transform3D > transform, std::shared_ptr< const PlanarBounds > pbounds, std::unique_ptr< SurfaceArray > surfaceArray = nullptr, double thickness = 0., std::unique_ptr< ApproachDescriptor > ad = nullptr, LayerType laytyp = Acts::active) inline static
Factory for a shared plane layer
Parameters
transform which places the layer in the global frame
pbounds the planar bounds that define the layer dimensions
surfaceArray is the surface array that holds the sensitive surfaces
thickness is the thickness of the layer (normal direction to plane)
ad is the approach descriptor for describing the approach surface
laytyp is the layer type
Returns
shared pointer to a PlaneLayer
Definition at line 40 of file PlaneLayer.hpp.
View newest version in sPHENIX GitHub at line 40 of file PlaneLayer.hpp
References PlaneLayer(), Acts::Layer::surfaceArray(), and Acts::Layer::thickness().
Referenced by Acts::Test::Layers::BOOST_AUTO_TEST_CASE(), Acts::Test::BOOST_AUTO_TEST_CASE(), Acts::Test::CubicTrackingGeometry::operator()(), and Acts::LayerCreator::planeLayer().
PlaneLayer& Acts::PlaneLayer::operator= (const PlaneLayer &) delete
Assignment operator for PlaneLayers - deleted.
const Acts::PlaneSurface & Acts::PlaneLayer::surfaceRepresentation () const override virtual
Transforms the layer into a Surface representation for extrapolation
Returns
returns a reference to a PlaneSurface
Implements Acts::Layer.
Definition at line 42 of file PlaneLayer.cpp.
View newest version in sPHENIX GitHub at line 42 of file PlaneLayer.cpp
Acts::PlaneSurface & Acts::PlaneLayer::surfaceRepresentation () override virtual
Implements Acts::Layer.
Definition at line 46 of file PlaneLayer.cpp.
View newest version in sPHENIX GitHub at line 46 of file PlaneLayer.cpp
The documentation for this class was generated from the following files:
fun4all_acts/blob/master/Core/include/Acts/Geometry/PlaneLayer.hpp
fun4all_acts/blob/master/Core/src/Geometry/PlaneLayer.cpp