EIC Software: eASTDetectorConstruction Class Reference
eASTDetectorConstruction Class Reference
#include <east/blob/main/Core/include/eASTDetectorConstruction.hh>
Public Member Functions
eASTDetectorConstruction ()
virtual ~eASTDetectorConstruction ()
virtual G4VPhysicalVolume * Construct () override
virtual void ConstructSDandField () override
void RegisterComponent (G4String, eASTVDetectorComponent *)
void ListSolids (G4int)
void ListLogVols (G4int)
void ListPhysVols (G4int)
void ListRegions (G4int)
G4bool CheckOverlap (G4String &, G4int, G4int, G4double)
void ListAllMaterial ()
G4bool ListMaterial (G4String &)
void DumpNistMaterials ()
G4bool CreateMaterial (G4String &)
G4bool GetMaterial (G4String &)
G4int SetMaterial (G4String &, G4String &)
void SetMagneticField (eASTMagneticField *field)
Static Public Member Functions
static eASTDetectorConstruction * Instance ()
Private Attributes
eASTDetectorConstructionMessenger * messenger
G4VPhysicalVolume * fWorld = nullptr
eASTMagneticField * fField = nullptr
std::map< G4String,
eASTVDetectorComponent * > components
Static Private Attributes
static eASTDetectorConstruction * instance = nullptr
Detailed Description
Definition at line 24 of file eASTDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 24 of file eASTDetectorConstruction.hh
Constructor & Destructor Documentation
eASTDetectorConstruction::eASTDetectorConstruction ()
Definition at line 39 of file eASTDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 39 of file eASTDetectorConstruction.cc
References instance, and messenger.
Referenced by Instance().
eASTDetectorConstruction::~eASTDetectorConstruction () virtual
Definition at line 51 of file eASTDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 51 of file eASTDetectorConstruction.cc
References components, instance, and messenger.
Member Function Documentation
G4bool eASTDetectorConstruction::CheckOverlap (G4String & physVolName, G4int nSpots, G4int maxErr, G4double tol)
Definition at line 259 of file eASTDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 259 of file eASTDetectorConstruction.cc
References G4PhysicalVolumeStore::GetInstance().
Referenced by eASTDetectorConstructionMessenger::SetNewValue().
G4VPhysicalVolume * eASTDetectorConstruction::Construct () override virtual
Definition at line 66 of file eASTDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 66 of file eASTDetectorConstruction.cc
References components, eASTVDetectorComponent::Construct(), eASTVDetectorComponent::ConstructActionForMaster(), fWorld, and Acts::UnitConstants::m.
void eASTDetectorConstruction::ConstructSDandField () override virtual
Definition at line 115 of file eASTDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 115 of file eASTDetectorConstruction.cc
References eASTMagneticField::Activate(), components, eASTVDetectorComponent::ConstructActions(), eASTVDetectorComponent::ConstructSD(), and fField.
G4bool eASTDetectorConstruction::CreateMaterial (G4String & matName)
Definition at line 362 of file eASTDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 362 of file eASTDetectorConstruction.cc
Referenced by eASTDetectorConstructionMessenger::SetNewValue().
void eASTDetectorConstruction::DumpNistMaterials ()
Definition at line 349 of file eASTDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 349 of file eASTDetectorConstruction.cc
Referenced by eASTDetectorConstructionMessenger::SetNewValue().
G4bool eASTDetectorConstruction::GetMaterial (G4String & logVol)
Definition at line 368 of file eASTDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 368 of file eASTDetectorConstruction.cc
References G4LogicalVolumeStore::GetInstance().
Referenced by eASTDetectorConstructionMessenger::SetNewValue().
eASTDetectorConstruction * eASTDetectorConstruction::Instance () static
Definition at line 32 of file eASTDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 32 of file eASTDetectorConstruction.cc
References eASTDetectorConstruction(), and instance.
Referenced by eASTVDetectorComponent::SetUpBase().
void eASTDetectorConstruction::ListAllMaterial ()
Definition at line 319 of file eASTDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 319 of file eASTDetectorConstruction.cc
Referenced by eASTDetectorConstructionMessenger::SetNewValue().
void eASTDetectorConstruction::ListLogVols (G4int lvl)
Definition at line 162 of file eASTDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 162 of file eASTDetectorConstruction.cc
References G4LogicalVolumeStore::GetInstance().
Referenced by eASTDetectorConstructionMessenger::SetNewValue().
G4bool eASTDetectorConstruction::ListMaterial (G4String & matName)
Definition at line 333 of file eASTDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 333 of file eASTDetectorConstruction.cc
Referenced by eASTDetectorConstructionMessenger::SetNewValue().
void eASTDetectorConstruction::ListPhysVols (G4int lvl)
Definition at line 212 of file eASTDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 212 of file eASTDetectorConstruction.cc
References G4PhysicalVolumeStore::GetInstance().
Referenced by eASTDetectorConstructionMessenger::SetNewValue().
void eASTDetectorConstruction::ListRegions (G4int lvl)
Definition at line 282 of file eASTDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 282 of file eASTDetectorConstruction.cc
Referenced by eASTDetectorConstructionMessenger::SetNewValue().
void eASTDetectorConstruction::ListSolids (G4int lvl)
Definition at line 133 of file eASTDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 133 of file eASTDetectorConstruction.cc
References G4SolidStore::GetInstance().
Referenced by eASTDetectorConstructionMessenger::SetNewValue().
void eASTDetectorConstruction::RegisterComponent (G4String compName, eASTVDetectorComponent * comp)
Definition at line 61 of file eASTDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 61 of file eASTDetectorConstruction.cc
Referenced by eASTVDetectorComponent::SetUpBase().
void eASTDetectorConstruction::SetMagneticField (eASTMagneticField * field) inline
Definition at line 63 of file eASTDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 63 of file eASTDetectorConstruction.hh
References fField.
Referenced by eASTInitialization::eASTInitialization().
G4int eASTDetectorConstruction::SetMaterial (G4String & logVolName, G4String & matName)
Definition at line 384 of file eASTDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 384 of file eASTDetectorConstruction.cc
References G4LogicalVolumeStore::GetInstance().
Referenced by eASTDetectorConstructionMessenger::SetNewValue().
Member Data Documentation
std::map<G4String,eASTVDetectorComponent*> eASTDetectorConstruction::components private
Definition at line 47 of file eASTDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 47 of file eASTDetectorConstruction.hh
Referenced by Construct(), ConstructSDandField(), and ~eASTDetectorConstruction().
eASTMagneticField* eASTDetectorConstruction::fField = nullptr private
Definition at line 41 of file eASTDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 41 of file eASTDetectorConstruction.hh
Referenced by ConstructSDandField(), and SetMagneticField().
G4VPhysicalVolume* eASTDetectorConstruction::fWorld = nullptr private
Definition at line 40 of file eASTDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 40 of file eASTDetectorConstruction.hh
Referenced by Construct().
eASTDetectorConstruction * eASTDetectorConstruction::instance = nullptr static private
Definition at line 36 of file eASTDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 36 of file eASTDetectorConstruction.hh
Referenced by eASTDetectorConstruction(), Instance(), and ~eASTDetectorConstruction().
eASTDetectorConstructionMessenger* eASTDetectorConstruction::messenger private
Definition at line 39 of file eASTDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 39 of file eASTDetectorConstruction.hh
Referenced by eASTDetectorConstruction(), and ~eASTDetectorConstruction().
The documentation for this class was generated from the following files:
east/blob/main/Core/include/eASTDetectorConstruction.hh
east/blob/main/Core/src/eASTDetectorConstruction.cc