EIC Software: EicRoot/blob/master/dbase/dbInterface/FairDbResult.cxx File Reference
FairDbResult.cxx File Reference
#include <sstream>
#include "FairDbBinaryFile.h"
#include "FairDbResult.h"
#include "FairDbServices.h"
#include "FairDbTableRow.h"
#include "FairDbFieldType.h"
#include "FairDbString.h"
#include "FairDbStatement.h"
#include "FairDbTableMetaData.h"
#include "FairDbProxy.h"
#include "FairDbCache.h"
#include "FairDbTimerManager.h"
#include "FairDbValidityRecBuilder.h"
#include "FairDbExceptionLog.h"
#include "ValTimeStamp.h"
Macros
#define IN(t) istringstream in(AsString(t)); in
#define IN2(t, m)
#define IN3(t)
Functions
ClassImp (FairDbResultSet) FairDbResultSet
ClassImp(FairDbResultKey)
FairDbResultKey
FairDbResultKey std::ostream & operator<< (std::ostream &os, const FairDbResultKey &key)
ClassImp(FairDbResult) Int_t
FairDbResult FairDbBinaryFile & operator<< (FairDbBinaryFile &bf, const FairDbResult &res)
FairDbBinaryFile & operator>> (FairDbBinaryFile &bf, FairDbResult &res)
ClassImp (FairDbResultNonAgg) FairDbResultNonAgg
Macro Definition Documentation
#define IN (t) istringstream in(AsString(t)); in
Definition at line 62 of file FairDbResult.cxx.
View newest version in sPHENIX GitHub at line 62 of file FairDbResult.cxx
Referenced by caen_correction::caen_correction(), FairDbResultSet::operator>>(), and EICG4dRICHPhotosensor::setOpticalParams().
#define IN2 (t, m)
Value:
int col = CurColNum()-1;                  \
  if ( CurRowNum() == 0 ) {                 \
    istringstream in(AsString(t));          \
    in >> dest;                             \
  }                                         \
  else {                                    \
    dest = fTSQLStatement->m(col);          \
    IncrementCurCol();                      \
  }                                         \
Definition at line 66 of file FairDbResult.cxx.
View newest version in sPHENIX GitHub at line 66 of file FairDbResult.cxx
Referenced by FairDbResultSet::operator>>().
#define IN3 (t)
Value:
int col = this->CurColNum()-1;                                      \
const FairDbFieldType& fType = this->ColFieldType(col+1);              \
if (fType.GetSize() == 8) {                                       \
  dest=fTSQLStatement->GetUInt(col);            \
}                                                                   \
else {                                                              \
  t dest_signed;                                                    \
  *this >> dest_signed;                                             \
  dest = dest_signed;                                               \
  if ( fType.GetSize() == 1 ) dest &= 0xff;                         \
  if ( fType.GetSize() == 2 ) dest &= 0xffff;                       \
  if ( fType.GetSize() == 4 ) dest &= 0xffffffff;                   \
}\
Definition at line 86 of file FairDbResult.cxx.
View newest version in sPHENIX GitHub at line 86 of file FairDbResult.cxx
Referenced by FairDbResultSet::operator>>().
Function Documentation
ClassImp (FairDbResultSet)
Definition at line 24 of file FairDbResult.cxx.
View newest version in sPHENIX GitHub at line 24 of file FairDbResult.cxx
ClassImp (FairDbResultNonAgg)
Definition at line 1020 of file FairDbResult.cxx.
View newest version in sPHENIX GitHub at line 1020 of file FairDbResult.cxx
References FairDbTableRow::CreateTableRow(), FairDbRowStream::CurColName(), FairDbRowStream::DecrementCurCol(), FairDbResultSet::FetchRow(), FairDbTableRow::Fill(), FairDbTimerManager::gTimerManager, FairDbRowStream::HasRowCounter(), FairDbRowStream::IncrementCurCol(), FairDbResultSet::IsBeforeFirst(), FairDbResultSet::IsExhausted(), FairDbTimerManager::RecFillAgg(), FairDbTableRow::SetOwner(), and FairDbTimerManager::StartSubWatch().
ClassImp (FairDbResultKey) FairDbResultKey FairDbResultKey std::ostream& operator<< (std::ostream & os, const FairDbResultKey & key)
Definition at line 368 of file FairDbResult.cxx.
View newest version in sPHENIX GitHub at line 368 of file FairDbResult.cxx
References FairDbResultKey::AsString().
ClassImp (FairDbResult) Int_t FairDbResult FairDbBinaryFile& operator<< (FairDbBinaryFile & bf, const FairDbResult & res)
Definition at line 781 of file FairDbResult.cxx.
View newest version in sPHENIX GitHub at line 781 of file FairDbResult.cxx
References FairDbResult::Streamer().
FairDbBinaryFile& operator>> (FairDbBinaryFile & bf, FairDbResult & res)
Definition at line 790 of file FairDbResult.cxx.
View newest version in sPHENIX GitHub at line 790 of file FairDbResult.cxx
References FairDbResult::Streamer().