EIC Software: eicpy Namespace Reference
eicpy Namespace Reference
Namespaces
namespace binning
namespace build
namespace cpplint
namespace qaplots
namespace verify
Functions
def initialise
def set_rootlib_path
def find_root_lib_dir
def root_logon
Detailed Description
eicpy package-level code.
Used for initialising the ROOT environment with eic-smear code.
Function Documentation
def eicpy.find_root_lib_dir ()
Attempt to locate the ROOT library directory.
Return the path to it, or raise an exception if it cannot be found.
Definition at line 48 of file __init__.py.
View newest version in sPHENIX GitHub at line 48 of file __init__.py
Referenced by set_rootlib_path().
def eicpy.initialise (logon = False)
Initialise the ROOT environment and load eic-smear code.
Optionally load the ROOT logon script.
Definition at line 8 of file __init__.py.
View newest version in sPHENIX GitHub at line 8 of file __init__.py
References root_logon(), and set_rootlib_path().
def eicpy.root_logon ()
Load the user's ROOT logon script, if it can be located.
Raise an IOError if it cannot.
Definition at line 85 of file __init__.py.
View newest version in sPHENIX GitHub at line 85 of file __init__.py
Referenced by eicpy.qaplots.execute(), and initialise().
def eicpy.set_rootlib_path ()
Add the ROOT library path to the Python module search path
if it is not already in it.
Raises an exception if the path cannot be determined or
ROOT cannot be imported.
Definition at line 28 of file __init__.py.
View newest version in sPHENIX GitHub at line 28 of file __init__.py
References find_root_lib_dir().
Referenced by initialise().