EIC Software: FairDbExceptionLog Class Reference
FairDbExceptionLog Class Reference
#include <EicRoot/blob/master/dbase/dbInterface/FairDbExceptionLog.h>
Public Member Functions
FairDbExceptionLog (const FairDbException *e=0)
virtual ~FairDbExceptionLog ()
Bool_t IsEmpty () const
const std::vector
< FairDbException > & GetEntries () const
void Print () const
UInt_t Size () const
void Copy (FairDbExceptionLog &that, UInt_t start=0) const
void AddLog (const FairDbExceptionLog &el)
void AddEntry (const FairDbException &e)
void AddEntry (const char *errMsg, Int_t code=-1, Int_t dbType=-1)
void AddEntry (const std::string &errMsg, Int_t code=-1, Int_t dbType=-1)
void AddEntry (const TSQLServer &server, Int_t dbType=-1)
void AddEntry (const TSQLStatement &statement, Int_t dbType=-1)
void Clear ()
Static Public Member Functions
static FairDbExceptionLog & GetGELog ()
Private Attributes
std::vector< FairDbException > fEntries
The exception entries.
Static Private Attributes
static FairDbExceptionLog fgGELog
Global Exception Log.
Detailed Description
Definition at line 19 of file FairDbExceptionLog.h.
View newest version in sPHENIX GitHub at line 19 of file FairDbExceptionLog.h
Constructor & Destructor Documentation
FairDbExceptionLog::FairDbExceptionLog (const FairDbException * e = 0)
FairDbExceptionLog::~FairDbExceptionLog () virtual
Definition at line 22 of file FairDbExceptionLog.cxx.
View newest version in sPHENIX GitHub at line 22 of file FairDbExceptionLog.cxx
Member Function Documentation
void FairDbExceptionLog::AddEntry (const FairDbException & e) inline
Definition at line 39 of file FairDbExceptionLog.h.
View newest version in sPHENIX GitHub at line 39 of file FairDbExceptionLog.h
References fEntries.
Referenced by AddEntry(), FairDbStatement::AppendExceptionLog(), Copy(), FairDbStatement::ExecuteQuery(), and FairDbConnection::RecordException().
void FairDbExceptionLog::AddEntry (const char * errMsg, Int_t code = -1, Int_t dbType = -1) inline
Definition at line 40 of file FairDbExceptionLog.h.
View newest version in sPHENIX GitHub at line 40 of file FairDbExceptionLog.h
References AddEntry().
void FairDbExceptionLog::AddEntry (const std::string & errMsg, Int_t code = -1, Int_t dbType = -1) inline
Definition at line 43 of file FairDbExceptionLog.h.
View newest version in sPHENIX GitHub at line 43 of file FairDbExceptionLog.h
References AddEntry().
void FairDbExceptionLog::AddEntry (const TSQLServer & server, Int_t dbType = -1) inline
Definition at line 46 of file FairDbExceptionLog.h.
View newest version in sPHENIX GitHub at line 46 of file FairDbExceptionLog.h
References AddEntry().
void FairDbExceptionLog::AddEntry (const TSQLStatement & statement, Int_t dbType = -1) inline
Definition at line 49 of file FairDbExceptionLog.h.
View newest version in sPHENIX GitHub at line 49 of file FairDbExceptionLog.h
References AddEntry().
void FairDbExceptionLog::AddLog (const FairDbExceptionLog & el)
Definition at line 50 of file FairDbExceptionLog.cxx.
View newest version in sPHENIX GitHub at line 50 of file FairDbExceptionLog.cxx
References AddEntry(), and GetEntries().
Referenced by FairDbStatement::AppendExceptionLog(), and FairDbStatement::PrintExceptions().
void FairDbExceptionLog::Clear () inline
Definition at line 52 of file FairDbExceptionLog.h.
View newest version in sPHENIX GitHub at line 52 of file FairDbExceptionLog.h
References fEntries.
Referenced by FairDbResult::CaptureExceptionLog(), and FairDbStatement::ClearExceptionLog().
void FairDbExceptionLog::Copy (FairDbExceptionLog & that, UInt_t start = 0) const
Definition at line 60 of file FairDbExceptionLog.cxx.
View newest version in sPHENIX GitHub at line 60 of file FairDbExceptionLog.cxx
References AddEntry().
Referenced by FairDbResult::CaptureExceptionLog().
const std::vector<FairDbException>& FairDbExceptionLog::GetEntries () const inline
Definition at line 31 of file FairDbExceptionLog.h.
View newest version in sPHENIX GitHub at line 31 of file FairDbExceptionLog.h
References fEntries.
Referenced by AddLog(), and operator<<().
static FairDbExceptionLog& FairDbExceptionLog::GetGELog () inline static
Definition at line 55 of file FairDbExceptionLog.h.
View newest version in sPHENIX GitHub at line 55 of file FairDbExceptionLog.h
References fgGELog.
Referenced by FairDbResult::CaptureExceptionLog(), FairDbStatement::PrintExceptions(), FairDbTableProxy::Query(), and FairDbTableProxyRegistry::~FairDbTableProxyRegistry().
Bool_t FairDbExceptionLog::IsEmpty () const inline
Definition at line 29 of file FairDbExceptionLog.h.
View newest version in sPHENIX GitHub at line 29 of file FairDbExceptionLog.h
References fEntries.
Referenced by FairDbMultConnector::CreateTemporaryTable(), FairDbStatement::ExecuteQuery(), FairDbStatement::ExecuteUpdate(), operator<<(), and FairDbStatement::PrintExceptions().
void FairDbExceptionLog::Print () const
Definition at line 68 of file FairDbExceptionLog.cxx.
View newest version in sPHENIX GitHub at line 68 of file FairDbExceptionLog.cxx
Referenced by FairDbTableProxyRegistry::~FairDbTableProxyRegistry().
UInt_t FairDbExceptionLog::Size () const inline
Definition at line 33 of file FairDbExceptionLog.h.
View newest version in sPHENIX GitHub at line 33 of file FairDbExceptionLog.h
References fEntries.
Referenced by FairDbConnection::PrintExceptionLog(), FairDbTableProxy::Query(), and FairDbTableProxyRegistry::~FairDbTableProxyRegistry().
Member Data Documentation
std::vector<FairDbException> FairDbExceptionLog::fEntries private
The exception entries.
Definition at line 65 of file FairDbExceptionLog.h.
View newest version in sPHENIX GitHub at line 65 of file FairDbExceptionLog.h
Referenced by AddEntry(), Clear(), GetEntries(), IsEmpty(), and Size().
FairDbExceptionLog FairDbExceptionLog::fgGELog static private
Global Exception Log.
Definition at line 68 of file FairDbExceptionLog.h.
View newest version in sPHENIX GitHub at line 68 of file FairDbExceptionLog.h
Referenced by GetGELog().
The documentation for this class was generated from the following files:
EicRoot/blob/master/dbase/dbInterface/FairDbExceptionLog.h
EicRoot/blob/master/dbase/dbInterface/FairDbExceptionLog.cxx