EIC Software: fun4all_eicmacros/blob/master/common/G4_EEMC_hybrid.C File Reference
G4_EEMC_hybrid.C File Reference
#include <GlobalVariables.C>
#include <g4calo/RawTowerBuilderByHitIndex.h>
#include <g4calo/RawTowerDigitizer.h>
#include <g4eiccalos/PHG4HybridHomogeneousCalorimeterSubsystem.h>
#include <g4eiccalos/PHG4ForwardCalCellReco.h>
#include <g4eval/CaloEvaluator.h>
#include <g4main/PHG4Reco.h>
#include <caloreco/RawClusterBuilderFwd.h>
#include <caloreco/RawClusterBuilderTemplate.h>
#include <caloreco/RawTowerCalibration.h>
#include <fun4all/Fun4AllServer.h>
Namespaces
namespace Enable
namespace G4EEMCH
namespace G4EEMCH::SETTING
Macros
#define MACRO_G4EEMCHYBRID_C
Enumerations
enum G4EEMCH::enu_Eemc_clusterizer { G4EEMCH::kEemcGraphClusterizer, G4EEMCH::kEemcTemplateClusterizer }
Functions
void EEMCHInit ()
void EEMCHSetup (PHG4Reco *g4Reco)
void EEMCH_Cells ()
void EEMCH_Towers ()
void EEMCH_Clusters ()
void EEMCH_Eval (const std::string &outputfile)
Variables
bool Enable::EEMCH = false
bool Enable::EEMCH_ABSORBER = false
bool Enable::EEMCH_CELL = false
bool Enable::EEMCH_TOWER = false
bool Enable::EEMCH_CLUSTER = false
bool Enable::EEMCH_EVAL = false
bool Enable::EEMCH_OVERLAPCHECK = false
int Enable::EEMCH_VERBOSITY = 0
int G4EEMCH::use_projective_geometry = 0
double G4EEMCH::Gdz = 20. + 0.1
double G4EEMCH::Gz0 = -180.
bool G4EEMCH::SETTING::USEHYBRID = true
bool G4EEMCH::SETTING::USECEMCGeo = false
RawTowerDigitizer::enu_digi_algorithm G4EEMCH::TowerDigi = RawTowerDigitizer::kSimple_photon_digitization
enu_Eemc_clusterizer G4EEMCH::Eemc_clusterizer = kEemcTemplateClusterizer
Macro Definition Documentation
#define MACRO_G4EEMCHYBRID_C
Definition at line 2 of file G4_EEMC_hybrid.C.
View newest version in sPHENIX GitHub at line 2 of file G4_EEMC_hybrid.C
Function Documentation
void EEMCH_Cells ()
Definition at line 151 of file G4_EEMC_hybrid.C.
View newest version in sPHENIX GitHub at line 151 of file G4_EEMC_hybrid.C
Referenced by Fun4All_G4_FullDetectorModular().
void EEMCH_Clusters ()
Definition at line 249 of file G4_EEMC_hybrid.C.
View newest version in sPHENIX GitHub at line 249 of file G4_EEMC_hybrid.C
References RawClusterBuilderTemplate::Detector(), RawClusterBuilderFwd::Detector(), G4EEMCH::Eemc_clusterizer, Enable::EEMCH_VERBOSITY, Fun4AllServer::instance(), G4EEMCH::kEemcGraphClusterizer, G4EEMCH::kEemcTemplateClusterizer, max, Fun4AllServer::registerSubsystem(), G4EEMCH::SETTING::USEHYBRID, Enable::VERBOSITY, and Fun4AllBase::Verbosity().
Referenced by Extract_ECCE_gdml(), and Fun4All_G4_FullDetectorModular().
void EEMCH_Eval (const std::string & outputfile)
Definition at line 294 of file G4_EEMC_hybrid.C.
View newest version in sPHENIX GitHub at line 294 of file G4_EEMC_hybrid.C
References Enable::EEMCH_VERBOSITY, Fun4AllServer::instance(), max, run_skim::outputfile, pos(), Fun4AllServer::registerSubsystem(), CaloEvaluator::set_do_cluster_eval(), G4EEMCH::SETTING::USEHYBRID, Enable::VERBOSITY, and Fun4AllBase::Verbosity().
void EEMCH_Towers ()
Definition at line 154 of file G4_EEMC_hybrid.C.
View newest version in sPHENIX GitHub at line 154 of file G4_EEMC_hybrid.C
References RawTowerDigitizer::Detector(), RawTowerCalibration::Detector(), RawTowerBuilderByHitIndex::Detector(), Enable::EEMCH_VERBOSITY, RawTowerBuilderByHitIndex::GeometryTableFile(), Fun4AllServer::instance(), RawTowerDigitizer::kNo_digitization, RawTowerCalibration::kSimple_linear_calibration, max, Fun4AllServer::registerSubsystem(), RawTowerCalibration::set_calib_algorithm(), RawTowerCalibration::set_calib_const_GeV_ADC(), RawTowerDigitizer::set_digi_algorithm(), RawTowerCalibration::set_pedstal_ADC(), RawTowerDigitizer::set_pedstal_central_ADC(), RawTowerDigitizer::set_pedstal_width_ADC(), RawTowerDigitizer::set_photonelec_ADC(), RawTowerDigitizer::set_photonelec_yield_visible_GeV(), RawTowerDigitizer::set_raw_tower_node_prefix(), RawTowerBuilderByHitIndex::set_sim_tower_node_prefix(), RawTowerDigitizer::set_zero_suppression_ADC(), G4EEMCH::TowerDigi, G4EEMCH::SETTING::USECEMCGeo, G4EEMCH::SETTING::USEHYBRID, Enable::VERBOSITY, and Fun4AllBase::Verbosity().
Referenced by Extract_ECCE_gdml(), and Fun4All_G4_FullDetectorModular().
void EEMCHInit ()
Definition at line 76 of file G4_EEMC_hybrid.C.
View newest version in sPHENIX GitHub at line 76 of file G4_EEMC_hybrid.C
References G4EEMCH::Gdz, G4EEMCH::Gz0, max, BlackHoleGeometry::max_radius, min, and BlackHoleGeometry::min_z.
Referenced by G4Init().
void EEMCHSetup (PHG4Reco * g4Reco)
Use dedicated EEMCH module
Definition at line 84 of file G4_EEMC_hybrid.C.
View newest version in sPHENIX GitHub at line 84 of file G4_EEMC_hybrid.C
References Enable::ABSORBER, Enable::EEMCH_ABSORBER, Enable::EEMCH_OVERLAPCHECK, Enable::EEMCH_VERBOSITY, max, Enable::OVERLAPCHECK, PHG4DetectorSubsystem::OverlapCheck(), PHG4Reco::registerSubsystem(), PHG4DetectorSubsystem::set_string_param(), PHG4DetectorSubsystem::SetAbsorberActive(), PHG4DetectorSubsystem::SetActive(), PHG4DetectorSubsystem::SuperDetector(), G4EEMCH::SETTING::USECEMCGeo, G4EEMCH::SETTING::USEHYBRID, and Enable::VERBOSITY.
Referenced by G4Setup().