EIC Software: SensitiveVolume Class Reference
SensitiveVolume Class Reference
#include <EicRoot/blob/master/eic/htc/SensitiveVolume.h>
Public Member Functions
SensitiveVolume (LogicalVolumeLookupTableEntry *lNode, const TGeoNode *node, double z0)
~SensitiveVolume ()
int TrackToHitDistance (t_3d_line *line, EicTrackingDigiHit *hit, double qdist[])
unsigned GetKfNodeWrapperCount () const
KalmanNodeWrapper * GetKfNodeWrapper (unsigned id)
void SetNodeGroup (unsigned wr, FwdHoughNodeGroup *ngroup)
FwdHoughNodeGroup * GetNodeGroup (unsigned wr)
double GetXmin () const
double GetXmax () const
double GetYmin () const
double GetYmax () const
const
LogicalVolumeLookupTableEntry * GetLogicalNode () const
Private Attributes
std::vector< KalmanNodeWrapper > mKfNodeWrappers
double mXmin
double mXmax
double mYmin
double mYmax
LogicalVolumeLookupTableEntry * mLogicalNode
Friends
class EicKfNodeTemplate
class EicHtcTask
Detailed Description
Definition at line 121 of file SensitiveVolume.h.
View newest version in sPHENIX GitHub at line 121 of file SensitiveVolume.h
Constructor & Destructor Documentation
SensitiveVolume::SensitiveVolume (LogicalVolumeLookupTableEntry * lNode, const TGeoNode * node, double z0) inline
Definition at line 127 of file SensitiveVolume.h.
View newest version in sPHENIX GitHub at line 127 of file SensitiveVolume.h
References mXmax, mXmin, mYmax, mYmin, and Acts::Test::volume.
SensitiveVolume::~SensitiveVolume () inline
Definition at line 144 of file SensitiveVolume.h.
View newest version in sPHENIX GitHub at line 144 of file SensitiveVolume.h
Member Function Documentation
KalmanNodeWrapper* SensitiveVolume::GetKfNodeWrapper (unsigned id) inline
Definition at line 149 of file SensitiveVolume.h.
View newest version in sPHENIX GitHub at line 149 of file SensitiveVolume.h
References mKfNodeWrappers.
Referenced by FwdHoughTree::AddNodeGroup(), FwdTrackFinder::Exec(), FwdHoughTree::FinalFit(), FwdHoughTree::GetKfNode(), and FwdHoughTree::SetupKalmanFilter().
unsigned SensitiveVolume::GetKfNodeWrapperCount () const inline
Definition at line 148 of file SensitiveVolume.h.
View newest version in sPHENIX GitHub at line 148 of file SensitiveVolume.h
References mKfNodeWrappers.
const LogicalVolumeLookupTableEntry* SensitiveVolume::GetLogicalNode () const inline
Definition at line 166 of file SensitiveVolume.h.
View newest version in sPHENIX GitHub at line 166 of file SensitiveVolume.h
Referenced by FwdTrackFinder::Init().
FwdHoughNodeGroup* SensitiveVolume::GetNodeGroup (unsigned wr) inline
Definition at line 156 of file SensitiveVolume.h.
View newest version in sPHENIX GitHub at line 156 of file SensitiveVolume.h
References mKfNodeWrappers.
Referenced by FwdTrackFinder::Exec().
double SensitiveVolume::GetXmax () const inline
Definition at line 162 of file SensitiveVolume.h.
View newest version in sPHENIX GitHub at line 162 of file SensitiveVolume.h
References mXmax.
Referenced by FwdTrackFinder::Init().
double SensitiveVolume::GetXmin () const inline
Definition at line 161 of file SensitiveVolume.h.
View newest version in sPHENIX GitHub at line 161 of file SensitiveVolume.h
References mXmin.
Referenced by FwdTrackFinder::Init().
double SensitiveVolume::GetYmax () const inline
Definition at line 164 of file SensitiveVolume.h.
View newest version in sPHENIX GitHub at line 164 of file SensitiveVolume.h
References mYmax.
Referenced by FwdTrackFinder::Init().
double SensitiveVolume::GetYmin () const inline
Definition at line 163 of file SensitiveVolume.h.
View newest version in sPHENIX GitHub at line 163 of file SensitiveVolume.h
References mYmin.
Referenced by FwdTrackFinder::Init().
void SensitiveVolume::SetNodeGroup (unsigned wr, FwdHoughNodeGroup * ngroup) inline
Definition at line 153 of file SensitiveVolume.h.
View newest version in sPHENIX GitHub at line 153 of file SensitiveVolume.h
References mKfNodeWrappers.
int SensitiveVolume::TrackToHitDistance (t_3d_line * line, EicTrackingDigiHit * hit, double qdist[])
Definition at line 25 of file SensitiveVolume.cxx.
View newest version in sPHENIX GitHub at line 25 of file SensitiveVolume.cxx
References EicTrackingDigiHit::_GetCoord(), cross_p_l(), Acts::Test::dim, KalmanNodeWrapper::GetKfNode(), EicTrackingDigiHit::GetKfNodeID(), KalmanNodeWrapper::GetKfNodeTemplate(), KalmanNode::GetMdim(), KalmanNodeWrapper::GetNodeToMasterMtx(), mKfNodeWrappers, t_3d_line::nx, EicKfNodeTemplate::ThreeDeeToTemplate(), vtx(), and t_3d_line::x.
Referenced by TrKalmanFilter::CalculateHMatrix().
Friends And Related Function Documentation
friend class EicHtcTask friend
Definition at line 124 of file SensitiveVolume.h.
View newest version in sPHENIX GitHub at line 124 of file SensitiveVolume.h
friend class EicKfNodeTemplate friend
Definition at line 123 of file SensitiveVolume.h.
View newest version in sPHENIX GitHub at line 123 of file SensitiveVolume.h
Member Data Documentation
std::vector<KalmanNodeWrapper> SensitiveVolume::mKfNodeWrappers private
Definition at line 166 of file SensitiveVolume.h.
View newest version in sPHENIX GitHub at line 166 of file SensitiveVolume.h
Referenced by EicHtcTask::DeclareSensitiveVolumes(), EicHtcTask::Exec(), GetKfNodeWrapper(), GetKfNodeWrapperCount(), GetNodeGroup(), EicKfNodeTemplate::IncrementLinearTrackFitMatrices(), SetNodeGroup(), and TrackToHitDistance().
LogicalVolumeLookupTableEntry* SensitiveVolume::mLogicalNode private
Definition at line 177 of file SensitiveVolume.h.
View newest version in sPHENIX GitHub at line 177 of file SensitiveVolume.h
Referenced by EicHtcTask::DeclareSensitiveVolumes().
double SensitiveVolume::mXmax private
Definition at line 175 of file SensitiveVolume.h.
View newest version in sPHENIX GitHub at line 175 of file SensitiveVolume.h
Referenced by GetXmax(), and SensitiveVolume().
double SensitiveVolume::mXmin private
Definition at line 175 of file SensitiveVolume.h.
View newest version in sPHENIX GitHub at line 175 of file SensitiveVolume.h
Referenced by GetXmin(), and SensitiveVolume().
double SensitiveVolume::mYmax private
Definition at line 175 of file SensitiveVolume.h.
View newest version in sPHENIX GitHub at line 175 of file SensitiveVolume.h
Referenced by GetYmax(), and SensitiveVolume().
double SensitiveVolume::mYmin private
Definition at line 175 of file SensitiveVolume.h.
View newest version in sPHENIX GitHub at line 175 of file SensitiveVolume.h
Referenced by GetYmin(), and SensitiveVolume().
The documentation for this class was generated from the following files:
EicRoot/blob/master/eic/htc/SensitiveVolume.h
EicRoot/blob/master/eic/htc/SensitiveVolume.cxx