EIC Software: HoughCell Class Reference
HoughCell Class Reference
#include <EicRoot/blob/master/eic/htree/HoughCell.h>
Public Member Functions
HoughCell (const HoughTree *tree)
~HoughCell ()
bool DaughtersArrayAllocated () const
void SetDaughter (unsigned iq, HoughCell *ptr)
HoughCell ** GetDaughterPtr (unsigned iq) const
void UpdateRanges (const HoughTree *tree, const t_hough_range id[])
void AllocateDaughterCells (unsigned num)
void ResetRanges (const HoughTree *tree, bool immunity[]=0)
t_hough_range From (unsigned gr) const
t_hough_range To (unsigned gr) const
const t_hough_range * From () const
const t_hough_range * To () const
Private Attributes
t_hough_range * mFrom
t_hough_range * mTo
HoughCell ** mDaughters
Detailed Description
Definition at line 14 of file HoughCell.h.
View newest version in sPHENIX GitHub at line 14 of file HoughCell.h
Constructor & Destructor Documentation
HoughCell::HoughCell (const HoughTree * tree)
Definition at line 14 of file HoughCell.cxx.
View newest version in sPHENIX GitHub at line 14 of file HoughCell.cxx
References HoughTree::GetGdim(), mFrom, mTo, and ResetRanges().
HoughCell::~HoughCell () inline
Definition at line 17 of file HoughCell.h.
View newest version in sPHENIX GitHub at line 17 of file HoughCell.h
References mDaughters, mFrom, and mTo.
Member Function Documentation
void HoughCell::AllocateDaughterCells (unsigned num) inline
Definition at line 32 of file HoughCell.h.
View newest version in sPHENIX GitHub at line 32 of file HoughCell.h
References mDaughters, and num.
Referenced by HoughTree::CheckCell(), and HoughTree::GetInitializedCell().
bool HoughCell::DaughtersArrayAllocated () const inline
Definition at line 24 of file HoughCell.h.
View newest version in sPHENIX GitHub at line 24 of file HoughCell.h
References mDaughters.
Referenced by HoughTree::CheckCell(), and HoughTree::GetInitializedCell().
t_hough_range HoughCell::From (unsigned gr) const inline
Definition at line 40 of file HoughCell.h.
View newest version in sPHENIX GitHub at line 40 of file HoughCell.h
References mFrom.
Referenced by HoughTree::CheckCell(), HoughTree::GetInitializedCell(), and HoughTree::GetUsefulGroupCount().
const t_hough_range* HoughCell::From () const inline
Definition at line 43 of file HoughCell.h.
View newest version in sPHENIX GitHub at line 43 of file HoughCell.h
References mFrom.
HoughCell** HoughCell::GetDaughterPtr (unsigned iq) const inline
Definition at line 28 of file HoughCell.h.
View newest version in sPHENIX GitHub at line 28 of file HoughCell.h
References mDaughters.
Referenced by HoughTree::CheckCell().
void HoughCell::ResetRanges (const HoughTree * tree, bool immunity[] = 0)
Definition at line 27 of file HoughCell.cxx.
View newest version in sPHENIX GitHub at line 27 of file HoughCell.cxx
References __OUT_OF_RANGE_BIT_, HoughTree::GetGdim(), mFrom, and mTo.
Referenced by HoughTree::GetInitializedCell(), and HoughCell().
void HoughCell::SetDaughter (unsigned iq, HoughCell * ptr) inline
Definition at line 26 of file HoughCell.h.
View newest version in sPHENIX GitHub at line 26 of file HoughCell.h
References mDaughters.
Referenced by HoughTree::GetInitializedCell().
t_hough_range HoughCell::To (unsigned gr) const inline
Definition at line 41 of file HoughCell.h.
View newest version in sPHENIX GitHub at line 41 of file HoughCell.h
References mTo.
Referenced by HoughTree::CheckCell(), and HoughTree::GetInitializedCell().
const t_hough_range* HoughCell::To () const inline
Definition at line 44 of file HoughCell.h.
View newest version in sPHENIX GitHub at line 44 of file HoughCell.h
References mTo.
void HoughCell::UpdateRanges (const HoughTree * tree, const t_hough_range id[])
Definition at line 38 of file HoughCell.cxx.
View newest version in sPHENIX GitHub at line 38 of file HoughCell.cxx
References __OUT_OF_RANGE_BIT_, HoughNodeGroup::GetCoordDescr(), HoughTree::GetGdim(), HoughTree::GetGroup(), mFrom, mTo, CoordinateDescriptor::PackCoord(), CoordinateDescriptor::UnpackCoord(), and value.
Referenced by HoughTree::GetInitializedCell().
Member Data Documentation
HoughCell** HoughCell::mDaughters private
Definition at line 52 of file HoughCell.h.
View newest version in sPHENIX GitHub at line 52 of file HoughCell.h
Referenced by AllocateDaughterCells(), DaughtersArrayAllocated(), GetDaughterPtr(), SetDaughter(), and ~HoughCell().
t_hough_range* HoughCell::mFrom private
Definition at line 44 of file HoughCell.h.
View newest version in sPHENIX GitHub at line 44 of file HoughCell.h
Referenced by From(), HoughCell(), ResetRanges(), UpdateRanges(), and ~HoughCell().
t_hough_range * HoughCell::mTo private
Definition at line 44 of file HoughCell.h.
View newest version in sPHENIX GitHub at line 44 of file HoughCell.h
Referenced by HoughCell(), ResetRanges(), To(), UpdateRanges(), and ~HoughCell().
The documentation for this class was generated from the following files:
EicRoot/blob/master/eic/htree/HoughCell.h
EicRoot/blob/master/eic/htree/HoughCell.cxx