EIC Software: MapsGeoParData Class Reference
MapsGeoParData Class Reference
#include <EicRoot/blob/master/eic/detectors/maps/MapsGeoParData.h>
Public Member Functions
MapsGeoParData (const char *detName=0, int version=-1, int subVersion=0)
~MapsGeoParData ()
void UseTriangularAssemblies (bool yesNo)
bool UseTriangularAssemblies () const
void WithMountingRings (bool yesNo)
bool WithMountingRings () const
void WithEnforcementBrackets (bool yesNo)
bool WithEnforcementBrackets () const
void WithExternalPipes (bool yesNo)
bool WithExternalPipes () const
void SetCarbonFiberMaterial (const char *material)
void SetKaptonMaterial (const char *material)
MapsGeoParData (const char *detName=0, int version=-1, int subVersion=0)
~MapsGeoParData ()
void UseTriangularAssemblies (bool yesNo=true)
void WithMountingRings (bool yesNo=true)
void WithEnforcementBrackets (bool yesNo=true)
void WithExternalPipes (bool yesNo=true)
void SetCarbonFiberMaterial (const char *material)
void SetKaptonMaterial (const char *material)
Public Member Functions inherited from EicGeoParData
EicGeoParData (const char *detName=0, int version=-1, int subVersion=0)
~EicGeoParData ()
void ResetVars ()
void SetGeometryType (GeometryType gType)
GeometryType GetGeometryType () const
void SetTestGeometryFlag (bool flag=true)
bool IsTestGeometry () const
int GetVersion () const
int GetSubVersion () const
void SetFileName (const char *fileName)
void SetFileNameFormat (const char *fileNameFormat)
void SetComment (const char *comment)
int AttachSourceFile (const char *fileName)
void PrintAttachedSourceFile (const char *fileName)
EicGeoMap * CreateNewMap ()
int SetCircularX (unsigned group=0)
int SetCircularY (unsigned group=0)
int SetCircularZ (unsigned group=0)
bool GetCircularX (unsigned group=0) const
bool GetCircularY (unsigned group=0) const
bool GetCircularZ (unsigned group=0) const
bool GetCircular (unsigned group, unsigned what) const
int SetMappingTableEntry (EicGeoMap *map, const unsigned geant[], unsigned group, unsigned logical[])
int AddLogicalVolumeGroup (unsigned dimX=0, unsigned dimY=0, unsigned dimZ=0)
void AddBlackHoleVolume (const char *vName)
void AddStepEnforcedVolume (const char *vName)
void AddStepEnforcedVolumeLookupEntry (int volumeID, double step)
const TGeoMedium * GetMedium (const char *medium)
void SetTopVolumeTransformation (TGeoMatrix *transformation)
const TGeoMatrix * GetTopVolumeTransformation () const
TString GetGeometryFileName (bool root=true) const
virtual void Print (const char *option=0) const
virtual int ConstructGeometry (bool root=true, bool gdml=false, bool check=false)
TGeoVolume * GetTopVolume () const
TGeoManager * GetRootGeoManager ()
void FinalizeOutput (bool root=true, bool gdml=false, bool check=false)
UInt_t GetMapNum () const
EicGeoMap * GetMapPtrViaMapID (unsigned mapId) const
const EicGeoMap * GetMapPtrViaHitMultiIndex (ULong64_t multi) const
int CalculateMappingTableSignatures ()
unsigned GetMaxVolumeLevelNum () const
ULogicalIndex_t GeantMultiToLogicalIndex (ULong64_t multi) const
unsigned GetDimX (unsigned group=0) const
unsigned GetDimY (unsigned group=0) const
unsigned GetDimZ (unsigned group=0) const
unsigned GetDim (unsigned group, unsigned what) const
unsigned GetGroup (ULogicalIndex_t logicalID) const
unsigned GetX (ULogicalIndex_t logicalID) const
unsigned GetY (ULogicalIndex_t logicalID) const
unsigned GetZ (ULogicalIndex_t logicalID) const
unsigned GetCoord (unsigned what, ULogicalIndex_t logicalID) const
bool IsBlackHoleVolume (const char *vName) const
const std::set< TString > & GetBlackHoleVolumes () const
double GetEnforcedStep (int volumeID)
const std::set< TString > & GetStepEnforcedVolumes () const
void InitializeLookupTables ()
LogicalVolumeLookupTableEntry * GetLookupTableNode (ULogicalIndex_t xy) const
LogicalVolumeLookupTableEntry * GetLookupTableNode (const TGeoNode *node) const
EicNamePatternHub< Color_t > * GetColorTable ()
EicNamePatternHub< Char_t > * GetTransparencyTable ()
virtual bool AreNeighbours (ULogicalIndex_t l1, ULogicalIndex_t l2, unsigned maxLinearDist=1, unsigned maxChebyshevDist=0) const
const EicDetName * GetDetName () const
void AddWantedParticle (const char *vName, int pdg)
bool IsWantedParticle (const char *vName, int pdg) const
EicGeoParData (const char *detName=0, int version=-1, int subVersion=0)
~EicGeoParData ()
void ResetVars ()
void SetGeometryType (GeometryType gType)
GeometryType GetGeometryType () const
void SetTestGeometryFlag (bool flag=true)
bool IsTestGeometry () const
int GetVersion () const
int GetSubVersion () const
void SetFileName (const char *fileName)
void SetFileNameFormat (const char *fileNameFormat)
void SetTransparency (unsigned value)
void SetComment (const char *comment)
int AttachSourceFile (const char *fileName)
void PrintAttachedSourceFile (const char *fileName)
EicGeoMap * CreateNewMap ()
int SetCircularX (unsigned group=0)
int SetCircularY (unsigned group=0)
int SetCircularZ (unsigned group=0)
bool GetCircularX (unsigned group=0) const
bool GetCircularY (unsigned group=0) const
bool GetCircularZ (unsigned group=0) const
bool GetCircular (unsigned group, unsigned what) const
int SetMappingTableEntry (EicGeoMap *map, const unsigned geant[], unsigned group, unsigned logical[])
int AddLogicalVolumeGroup (unsigned dimX=0, unsigned dimY=0, unsigned dimZ=0)
void AddBlackHoleVolume (const char *vName)
void AddStepEnforcedVolume (const char *vName)
void AddStepEnforcedVolumeLookupEntry (int volumeID, double step)
const TGeoMedium * GetMedium (const char *medium)
void SetTopVolumeTransformation (TGeoMatrix *transformation)
const TGeoMatrix * GetTopVolumeTransformation () const
TString GetGeometryFileName (bool root=true) const
virtual void Print (const char *option=0) const
virtual int ConstructGeometry (bool root=true, bool gdml=false, bool check=false)
TGeoVolume * GetTopVolume () const
TGeoManager * GetRootGeoManager ()
void FinalizeOutput (bool root=true, bool gdml=false, bool check=false)
UInt_t GetMapNum () const
EicGeoMap * GetMapPtrViaMapID (unsigned mapId) const
const EicGeoMap * GetMapPtrViaHitMultiIndex (ULong64_t multi) const
int CalculateMappingTableSignatures ()
unsigned GetMaxVolumeLevelNum () const
ULogicalIndex_t GeantMultiToLogicalIndex (ULong64_t multi) const
void PlaceG4Volume (G4LogicalVolume *mother, bool check=false, void *pRot=0, void *tlate=0)
unsigned GetDimX (unsigned group=0) const
unsigned GetDimY (unsigned group=0) const
unsigned GetDimZ (unsigned group=0) const
unsigned GetDim (unsigned group, unsigned what) const
unsigned GetGroup (ULogicalIndex_t logicalID) const
unsigned GetX (ULogicalIndex_t logicalID) const
unsigned GetY (ULogicalIndex_t logicalID) const
unsigned GetZ (ULogicalIndex_t logicalID) const
unsigned GetCoord (unsigned what, ULogicalIndex_t logicalID) const
bool IsBlackHoleVolume (const char *vName) const
const std::set< TString > & GetBlackHoleVolumes () const
double GetEnforcedStep (int volumeID)
const std::set< TString > & GetStepEnforcedVolumes () const
void InitializeLookupTables ()
LogicalVolumeLookupTableEntry * GetLookupTableNode (ULogicalIndex_t xy) const
LogicalVolumeLookupTableEntry * GetLookupTableNode (const TGeoNode *node) const
EicNamePatternHub< Color_t > * GetColorTable ()
EicNamePatternHub< Char_t > * GetTransparencyTable ()
virtual bool AreNeighbours (ULogicalIndex_t l1, ULogicalIndex_t l2, unsigned maxLinearDist=1, unsigned maxChebyshevDist=0) const
const EicDetName * GetDetName () const
void AddWantedParticle (const char *vName, int pdg)
bool IsWantedParticle (const char *vName, int pdg) const
void SetTGeoGeometryCheckPrecision (double value)
void TurnTGeoGeometryCheckOff (void)
const std::vector
< G4VPhysicalVolume * > & GetG4Volumes (void) const
const std::map
< G4VPhysicalVolume
*, unsigned > & GetG4SensitiveVolumes (void) const
ClassDef (EicGeoParData, 51)
Public Attributes
Double_t mMountingRingBeamLineThickness
Double_t mMountingRingRadialThickness
Double_t mWaterPipeExtensionLength
Double_t mEnforcementBracketThickness
Protected Member Functions
TGeoVolume * ConstructMimosaCell (MapsMimosaAssembly *mcell, unsigned id)
double GetExpectedStaveLength (unsigned chipNum, MapsMimosaAssembly *mcell)
double GetAssemblyContainerWidth (const MapsMimosaAssembly *mcell) const
MapsStave * ConstructStave (unsigned chipNum, unsigned id, MapsMimosaAssembly *mcell)
MapsStave * ConstructStaveWithMapping (unsigned chipNum, unsigned id, MapsMimosaAssembly *mcell)
ClassDef (MapsGeoParData, 10)
TGeoVolume * ConstructMimosaCell (MapsMimosaAssembly *mcell, unsigned id)
double GetExpectedStaveLength (unsigned chipNum, MapsMimosaAssembly *mcell)
double GetAssemblyContainerWidth (const MapsMimosaAssembly *mcell) const
MapsStave * ConstructStave (unsigned chipNum, unsigned id, MapsMimosaAssembly *mcell)
MapsStave * ConstructStaveWithMapping (unsigned chipNum, unsigned id, MapsMimosaAssembly *mcell)
ClassDef (MapsGeoParData, 10)
Protected Attributes
TString mCarbonFiberMaterial
TString mKaptonMaterial
char mMimosaCoreName [128]
char mMimosaShellName [128]
char mCellAssemblyName [128]
double mAssemblyHeight
double mAssemblyLength
double mWaterPipeXoffset
double mWaterPipeZoffset
double mMimosaOffset
Protected Attributes inherited from EicGeoParData
GeometryType mGeometryType
Bool_t mTestGeometryFlag
EicDetName * mDetName
respective lookup table (for efficiency)
unsigned char mTransparency
Private Attributes
Bool_t mUseTriangularAssemblies
Bool_t mWithMountingRings
Bool_t mWithEnforcementBrackets
Bool_t mWithExternalPipes
Additional Inherited Members
Public Types inherited from EicGeoParData
enum GeometryType {
Undefined, NoStructure, SimpleStructure, FullStructure,
Undefined, NoStructure, SimpleStructure, FullStructure
}
enum IDXYZ {
IDX =0, IDY, IDZ, IDX =0,
IDY, IDZ
}
enum GeometryType {
Undefined, NoStructure, SimpleStructure, FullStructure,
Undefined, NoStructure, SimpleStructure, FullStructure
}
enum IDXYZ {
IDX =0, IDY, IDZ, IDX =0,
IDY, IDZ
}
Static Public Member Functions inherited from EicGeoParData
static int ImportMediaFile (const char *fname)
Detailed Description
Definition at line 44 of file MapsGeoParData.h.
View newest version in sPHENIX GitHub at line 44 of file MapsGeoParData.h
Constructor & Destructor Documentation
MapsGeoParData::MapsGeoParData (const char * detName = 0, int version = -1, int subVersion = 0) inline
Definition at line 49 of file MapsGeoParData.h.
View newest version in sPHENIX GitHub at line 49 of file MapsGeoParData.h
References EicGeoParData::FullStructure, mAssemblyHeight, mAssemblyLength, mCellAssemblyName, EicGeoParData::mGeometryType, mMimosaCoreName, mMimosaOffset, mMimosaShellName, mWaterPipeXoffset, and mWaterPipeZoffset.
MapsGeoParData::~MapsGeoParData () inline
Definition at line 61 of file MapsGeoParData.h.
View newest version in sPHENIX GitHub at line 61 of file MapsGeoParData.h
MapsGeoParData::MapsGeoParData (const char * detName = 0, int version = -1, int subVersion = 0)
MapsGeoParData::~MapsGeoParData () inline
Definition at line 50 of file MapsGeoParData.h.
View newest version in sPHENIX GitHub at line 50 of file MapsGeoParData.h
Member Function Documentation
MapsGeoParData::ClassDef (MapsGeoParData , 10) protected
MapsGeoParData::ClassDef (MapsGeoParData , 10) protected
TGeoVolume* MapsGeoParData::ConstructMimosaCell (MapsMimosaAssembly * mcell, unsigned id) protected
TGeoVolume * MapsGeoParData::ConstructMimosaCell (MapsMimosaAssembly * mcell, unsigned id) protected
Definition at line 26 of file MapsGeoParData.cxx.
View newest version in sPHENIX GitHub at line 26 of file MapsGeoParData.cxx
References _AIR_, _ALUMINUM_, _SILICON_, _WATER_, cos(), EicGeoParData::FullStructure, MapsMimosaAssembly::GetAssemblyHeight(), MapsMimosaAssembly::GetAssemblyLength(), GetMedium, G4BARRELHCAL::length, MapsMimosaAssembly::mApexEnforcementBeamDiameter, MapsMimosaAssembly::mAssemblyBaseWidth, MapsMimosaAssembly::mAssemblyDeadMaterialWidth, MapsMimosaAssembly::mAssemblySideSlope, MapsMimosaAssembly::mBaseEnforcementBeamWidth, MapsMimosaAssembly::mChipActiveZoneThickness, MapsMimosaAssembly::mChipDeadAreaWidth, MapsMimosaAssembly::mChipLength, MapsMimosaAssembly::mChipThickness, MapsMimosaAssembly::mChipWidth, MapsMimosaAssembly::mColdPlateThickness, MapsMimosaAssembly::mEnforcementStripThickness, MapsMimosaAssembly::mEnforcementStripWidth, MapsMimosaAssembly::mFlexCableAluThickness, MapsMimosaAssembly::mFlexCableKaptonThickness, MapsMimosaAssembly::mSideWallThickness, MapsMimosaAssembly::mWaterPipeInnerDiameter, MapsMimosaAssembly::mWaterPipeWallThickness, EicGeoParData::NoStructure, rw, EicGeoParData::SimpleStructure, tmp1, tmp2, and width().
MapsStave* MapsGeoParData::ConstructStave (unsigned chipNum, unsigned id, MapsMimosaAssembly * mcell) protected
MapsStave * MapsGeoParData::ConstructStave (unsigned chipNum, unsigned id, MapsMimosaAssembly * mcell) protected
Definition at line 456 of file MapsGeoParData.cxx.
View newest version in sPHENIX GitHub at line 456 of file MapsGeoParData.cxx
References _AIR_, _WATER_, EicGeoParData::FullStructure, GetMedium, MapsMimosaAssembly::mAssemblyBaseWidth, MapsMimosaAssembly::mAssemblyDeadMaterialWidth, MapsStave::mLength, MapsStave::mVolume, MapsMimosaAssembly::mWaterPipeInnerDiameter, MapsMimosaAssembly::mWaterPipeWallThickness, rw, tmp1, and tmp2.
Referenced by VstGeoParData::ConstructGeometry().
MapsStave* MapsGeoParData::ConstructStaveWithMapping (unsigned chipNum, unsigned id, MapsMimosaAssembly * mcell) protected
MapsStave * MapsGeoParData::ConstructStaveWithMapping (unsigned chipNum, unsigned id, MapsMimosaAssembly * mcell) protected
Definition at line 601 of file MapsGeoParData.cxx.
View newest version in sPHENIX GitHub at line 601 of file MapsGeoParData.cxx
References EicGeoMap::AddGeantVolumeLevel(), AddLogicalVolumeGroup(), exit(), and EicGeoMap::SetSingleSensorContainerVolume().
Referenced by FstGeoParData::ConstructGeometry().
double MapsGeoParData::GetAssemblyContainerWidth (const MapsMimosaAssembly * mcell) const inline protected
Definition at line 105 of file MapsGeoParData.h.
View newest version in sPHENIX GitHub at line 105 of file MapsGeoParData.h
References MapsMimosaAssembly::mAssemblyBaseWidth, MapsMimosaAssembly::mAssemblyDeadMaterialWidth, and mUseTriangularAssemblies.
double MapsGeoParData::GetAssemblyContainerWidth (const MapsMimosaAssembly * mcell) const inline protected
Definition at line 115 of file MapsGeoParData.h.
View newest version in sPHENIX GitHub at line 115 of file MapsGeoParData.h
References MapsMimosaAssembly::mAssemblyBaseWidth, MapsMimosaAssembly::mAssemblyDeadMaterialWidth, and UseTriangularAssemblies().
Referenced by FstGeoParData::ConstructGeometry().
double MapsGeoParData::GetExpectedStaveLength (unsigned chipNum, MapsMimosaAssembly * mcell) inline protected
Definition at line 99 of file MapsGeoParData.h.
View newest version in sPHENIX GitHub at line 99 of file MapsGeoParData.h
References MapsMimosaAssembly::GetAssemblyLength(), mEnforcementBracketThickness, mWaterPipeExtensionLength, mWithEnforcementBrackets, and mWithExternalPipes.
double MapsGeoParData::GetExpectedStaveLength (unsigned chipNum, MapsMimosaAssembly * mcell) inline protected
Definition at line 110 of file MapsGeoParData.h.
View newest version in sPHENIX GitHub at line 110 of file MapsGeoParData.h
References MapsMimosaAssembly::GetAssemblyLength(), mEnforcementBracketThickness, and mWaterPipeExtensionLength.
Referenced by FstGeoParData::ConstructGeometry().
void MapsGeoParData::SetCarbonFiberMaterial (const char * material) inline
Definition at line 72 of file MapsGeoParData.h.
View newest version in sPHENIX GitHub at line 72 of file MapsGeoParData.h
References mCarbonFiberMaterial.
void MapsGeoParData::SetCarbonFiberMaterial (const char * material) inline
Definition at line 83 of file MapsGeoParData.h.
View newest version in sPHENIX GitHub at line 83 of file MapsGeoParData.h
References mCarbonFiberMaterial.
void MapsGeoParData::SetKaptonMaterial (const char * material) inline
Definition at line 73 of file MapsGeoParData.h.
View newest version in sPHENIX GitHub at line 73 of file MapsGeoParData.h
References mKaptonMaterial.
void MapsGeoParData::SetKaptonMaterial (const char * material) inline
Definition at line 84 of file MapsGeoParData.h.
View newest version in sPHENIX GitHub at line 84 of file MapsGeoParData.h
References mKaptonMaterial.
void MapsGeoParData::UseTriangularAssemblies (bool yesNo = true) inline
Definition at line 60 of file MapsGeoParData.h.
View newest version in sPHENIX GitHub at line 60 of file MapsGeoParData.h
References mUseTriangularAssemblies, and yesNo().
void MapsGeoParData::UseTriangularAssemblies (bool yesNo) inline
Definition at line 71 of file MapsGeoParData.h.
View newest version in sPHENIX GitHub at line 71 of file MapsGeoParData.h
References mUseTriangularAssemblies, and yesNo().
Referenced by DefinitionParser().
bool MapsGeoParData::UseTriangularAssemblies () const inline
Definition at line 72 of file MapsGeoParData.h.
View newest version in sPHENIX GitHub at line 72 of file MapsGeoParData.h
References mUseTriangularAssemblies.
Referenced by GetAssemblyContainerWidth().
void MapsGeoParData::WithEnforcementBrackets (bool yesNo = true) inline
Definition at line 66 of file MapsGeoParData.h.
View newest version in sPHENIX GitHub at line 66 of file MapsGeoParData.h
References mWithEnforcementBrackets, and yesNo().
void MapsGeoParData::WithEnforcementBrackets (bool yesNo) inline
Definition at line 77 of file MapsGeoParData.h.
View newest version in sPHENIX GitHub at line 77 of file MapsGeoParData.h
References mWithEnforcementBrackets, and yesNo().
Referenced by DefinitionParser(), fbst(), and vst().
bool MapsGeoParData::WithEnforcementBrackets () const inline
Definition at line 78 of file MapsGeoParData.h.
View newest version in sPHENIX GitHub at line 78 of file MapsGeoParData.h
References mWithEnforcementBrackets.
void MapsGeoParData::WithExternalPipes (bool yesNo = true) inline
Definition at line 69 of file MapsGeoParData.h.
View newest version in sPHENIX GitHub at line 69 of file MapsGeoParData.h
References mWithExternalPipes, and yesNo().
void MapsGeoParData::WithExternalPipes (bool yesNo) inline
Definition at line 80 of file MapsGeoParData.h.
View newest version in sPHENIX GitHub at line 80 of file MapsGeoParData.h
References mWithExternalPipes, and yesNo().
Referenced by DefinitionParser(), fbst(), and vst().
bool MapsGeoParData::WithExternalPipes () const inline
Definition at line 81 of file MapsGeoParData.h.
View newest version in sPHENIX GitHub at line 81 of file MapsGeoParData.h
References mWithExternalPipes.
void MapsGeoParData::WithMountingRings (bool yesNo = true) inline
Definition at line 63 of file MapsGeoParData.h.
View newest version in sPHENIX GitHub at line 63 of file MapsGeoParData.h
References mWithMountingRings, and yesNo().
void MapsGeoParData::WithMountingRings (bool yesNo) inline
Definition at line 74 of file MapsGeoParData.h.
View newest version in sPHENIX GitHub at line 74 of file MapsGeoParData.h
References mWithMountingRings, and yesNo().
Referenced by DefinitionParser(), fbst(), and vst().
bool MapsGeoParData::WithMountingRings () const inline
Definition at line 75 of file MapsGeoParData.h.
View newest version in sPHENIX GitHub at line 75 of file MapsGeoParData.h
References mWithMountingRings.
Referenced by VstGeoParData::ConstructGeometry(), and FstGeoParData::ConstructGeometry().
Member Data Documentation
double MapsGeoParData::mAssemblyHeight protected
Definition at line 102 of file MapsGeoParData.h.
View newest version in sPHENIX GitHub at line 102 of file MapsGeoParData.h
Referenced by MapsGeoParData().
double MapsGeoParData::mAssemblyLength protected
Definition at line 103 of file MapsGeoParData.h.
View newest version in sPHENIX GitHub at line 103 of file MapsGeoParData.h
Referenced by MapsGeoParData().
TString MapsGeoParData::mCarbonFiberMaterial protected
Definition at line 94 of file MapsGeoParData.h.
View newest version in sPHENIX GitHub at line 94 of file MapsGeoParData.h
Referenced by VstGeoParData::ConstructGeometry(), FstGeoParData::ConstructGeometry(), and SetCarbonFiberMaterial().
char MapsGeoParData::mCellAssemblyName protected
Definition at line 101 of file MapsGeoParData.h.
View newest version in sPHENIX GitHub at line 101 of file MapsGeoParData.h
Referenced by VstGeoParData::ConstructGeometry(), FstGeoParData::ConstructGeometry(), and MapsGeoParData().
Double_t MapsGeoParData::mEnforcementBracketThickness
Definition at line 69 of file MapsGeoParData.h.
View newest version in sPHENIX GitHub at line 69 of file MapsGeoParData.h
Referenced by fbst(), GetExpectedStaveLength(), and vst().
TString MapsGeoParData::mKaptonMaterial protected
Definition at line 95 of file MapsGeoParData.h.
View newest version in sPHENIX GitHub at line 95 of file MapsGeoParData.h
Referenced by SetKaptonMaterial().
char MapsGeoParData::mMimosaCoreName protected
Definition at line 99 of file MapsGeoParData.h.
View newest version in sPHENIX GitHub at line 99 of file MapsGeoParData.h
Referenced by VstGeoParData::ConstructGeometry(), FstGeoParData::ConstructGeometry(), and MapsGeoParData().
double MapsGeoParData::mMimosaOffset protected
Definition at line 106 of file MapsGeoParData.h.
View newest version in sPHENIX GitHub at line 106 of file MapsGeoParData.h
Referenced by VstGeoParData::ConstructGeometry(), and MapsGeoParData().
char MapsGeoParData::mMimosaShellName protected
Definition at line 100 of file MapsGeoParData.h.
View newest version in sPHENIX GitHub at line 100 of file MapsGeoParData.h
Referenced by VstGeoParData::ConstructGeometry(), FstGeoParData::ConstructGeometry(), and MapsGeoParData().
Double_t MapsGeoParData::mMountingRingBeamLineThickness
Definition at line 61 of file MapsGeoParData.h.
View newest version in sPHENIX GitHub at line 61 of file MapsGeoParData.h
Referenced by VstGeoParData::ConstructGeometry(), FstGeoParData::ConstructGeometry(), fbst(), and vst().
Double_t MapsGeoParData::mMountingRingRadialThickness
Definition at line 66 of file MapsGeoParData.h.
View newest version in sPHENIX GitHub at line 66 of file MapsGeoParData.h
Referenced by VstGeoParData::ConstructGeometry(), FstGeoParData::ConstructGeometry(), fbst(), and vst().
Bool_t MapsGeoParData::mUseTriangularAssemblies private
Definition at line 84 of file MapsGeoParData.h.
View newest version in sPHENIX GitHub at line 84 of file MapsGeoParData.h
Referenced by GetAssemblyContainerWidth(), and UseTriangularAssemblies().
Double_t MapsGeoParData::mWaterPipeExtensionLength
Definition at line 68 of file MapsGeoParData.h.
View newest version in sPHENIX GitHub at line 68 of file MapsGeoParData.h
Referenced by fbst(), GetExpectedStaveLength(), and vst().
double MapsGeoParData::mWaterPipeXoffset protected
Definition at line 104 of file MapsGeoParData.h.
View newest version in sPHENIX GitHub at line 104 of file MapsGeoParData.h
Referenced by MapsGeoParData().
double MapsGeoParData::mWaterPipeZoffset protected
Definition at line 105 of file MapsGeoParData.h.
View newest version in sPHENIX GitHub at line 105 of file MapsGeoParData.h
Referenced by MapsGeoParData().
Bool_t MapsGeoParData::mWithEnforcementBrackets private
Definition at line 90 of file MapsGeoParData.h.
View newest version in sPHENIX GitHub at line 90 of file MapsGeoParData.h
Referenced by GetExpectedStaveLength(), and WithEnforcementBrackets().
Bool_t MapsGeoParData::mWithExternalPipes private
Definition at line 91 of file MapsGeoParData.h.
View newest version in sPHENIX GitHub at line 91 of file MapsGeoParData.h
Referenced by GetExpectedStaveLength(), and WithExternalPipes().
Bool_t MapsGeoParData::mWithMountingRings private
Definition at line 89 of file MapsGeoParData.h.
View newest version in sPHENIX GitHub at line 89 of file MapsGeoParData.h
Referenced by WithMountingRings().
The documentation for this class was generated from the following files:
EicRoot/blob/master/eic/detectors/maps/MapsGeoParData.h
EicToyModel/blob/master/include/MapsGeoParData.h
EicRoot/blob/master/eic/detectors/maps/MapsGeoParData.cxx
EicToyModel/blob/master/source/eicroot/MapsGeoParData.cxx