EIC Software: FairDetector Class Reference
FairDetector Class Reference abstract
#include <EicRoot/blob/master/base/FairDetector.h>
Public Member Functions
FairDetector (const char *Name, Bool_t Active, Int_t DetId=0)
FairDetector ()
virtual ~FairDetector ()
virtual void Initialize ()
virtual Bool_t ProcessHits (FairVolume *v=0)=0
virtual void EndOfEvent ()
virtual void Register ()=0
virtual TClonesArray * GetCollection (Int_t iColl) const =0
virtual void Reset ()=0
virtual void CopyClones (TClonesArray *cl1, TClonesArray *cl2, Int_t offset)
virtual void FinishPrimary ()
virtual void FinishRun ()
virtual void BeginPrimary ()
virtual void PostTrack ()
virtual void PreTrack ()
virtual void BeginEvent ()
virtual void FinishEvent ()
virtual void SetSpecialPhysicsCuts ()
void SaveGeoParams ()
Int_t GetDetId ()
Public Member Functions inherited from FairModule
FairModule ()
FairModule (const char *Name, const char *title, Bool_t Active=kFALSE)
virtual ~FairModule ()
virtual void Print (Option_t *option="") const
virtual void SetGeometryFileName (TString fname, TString geoVer="0")
virtual TString GetGeometryFileName ()
virtual TString GetGeometryFileVer ()
virtual void ConstructGeometry ()
virtual void ConstructOpGeometry ()
virtual void ConstructRootGeometry ()
virtual void ConstructASCIIGeometry ()
virtual Bool_t CheckIfSensitive (std::string name)
virtual void ExpandNode (TGeoNode *Node)
virtual Int_t getVolId (const TString &vname) const
Int_t GetModId ()
void SetVerboseLevel (Int_t level)
Bool_t IsActive ()
void SetModId (Int_t id)
void SetMotherVolume (TString volName)
void ProcessNodes (TList *aList)
virtual void SetParContainers ()
TList * GetListOfGeoPar ()
FairVolume * getFairVolume (FairGeoNode *fNode)
void AddSensitiveVolume (TGeoVolume *v)
void ImportRootMaterials ()
Protected Attributes
Int_t fDetId
FairLogger * fLogger
Protected Attributes inherited from FairModule
TString fgeoVer
TString fgeoName
Int_t fModId
Bool_t fActive
Int_t fNbOfSensitiveVol
Int_t fVerboseLevel
TList * flGeoPar
Bool_t kGeoSaved
list of Detector Geometry parameters
FairLogger * fLogger
flag for initialisation
Bool_t fRootMaterialImportFlag
Private Member Functions
FairDetector (const FairDetector &M)
FairDetector & operator= (const FairDetector &)
Additional Inherited Members
Public Attributes inherited from FairModule
TString fMotherVolumeName
Static Public Attributes inherited from FairModule
static FairVolumeList * vList =0
static Int_t fNbOfVolumes =0
static TRefArray * svList =0
static TArrayI * volNumber =0
Detailed Description
Base class for constructing detecors
Author
M. Al-Turany, Denis Bertini
Version
0.1
Since
12.01.04
Definition at line 17 of file FairDetector.h.
View newest version in sPHENIX GitHub at line 17 of file FairDetector.h
Constructor & Destructor Documentation
FairDetector::FairDetector (const char * Name, Bool_t Active, Int_t DetId = 0)
constructor Name : Detector Name Active: kTRUE for active detectors (ProcessHits() will be called) kFALSE for inactive detectors
Definition at line 23 of file FairDetector.cxx.
View newest version in sPHENIX GitHub at line 23 of file FairDetector.cxx
References FairModule::flGeoPar, and FairModule::kGeoSaved.
FairDetector::FairDetector ()
default constructor
Definition at line 46 of file FairDetector.cxx.
View newest version in sPHENIX GitHub at line 46 of file FairDetector.cxx
FairDetector::~FairDetector () virtual
destructor
Definition at line 38 of file FairDetector.cxx.
View newest version in sPHENIX GitHub at line 38 of file FairDetector.cxx
References FairModule::flGeoPar.
FairDetector::FairDetector (const FairDetector & M) private
Member Function Documentation
virtual void FairDetector::BeginEvent () inline virtual
Reimplemented in EicDetector.
Definition at line 83 of file FairDetector.h.
View newest version in sPHENIX GitHub at line 83 of file FairDetector.h
Referenced by FairMCApplication::BeginEvent().
virtual void FairDetector::BeginPrimary () inline virtual
Definition at line 74 of file FairDetector.h.
View newest version in sPHENIX GitHub at line 74 of file FairDetector.h
Referenced by FairMCApplication::BeginPrimary().
virtual void FairDetector::CopyClones (TClonesArray * cl1, TClonesArray * cl2, Int_t offset) inline virtual
Reimplemented in CbmRich.
Definition at line 64 of file FairDetector.h.
View newest version in sPHENIX GitHub at line 64 of file FairDetector.h
virtual void FairDetector::EndOfEvent () inline virtual
this is called at the end of an event
Reimplemented in EicDetector, and CbmRich.
Definition at line 48 of file FairDetector.h.
View newest version in sPHENIX GitHub at line 48 of file FairDetector.h
Referenced by FairMCApplication::FinishEvent().
virtual void FairDetector::FinishEvent () inline virtual
Definition at line 86 of file FairDetector.h.
View newest version in sPHENIX GitHub at line 86 of file FairDetector.h
Referenced by FairMCApplication::FinishEvent().
virtual void FairDetector::FinishPrimary () inline virtual
Definition at line 68 of file FairDetector.h.
View newest version in sPHENIX GitHub at line 68 of file FairDetector.h
Referenced by FairMCApplication::FinishPrimary().
virtual void FairDetector::FinishRun () inline virtual
Reimplemented in EicDetector.
Definition at line 71 of file FairDetector.h.
View newest version in sPHENIX GitHub at line 71 of file FairDetector.h
Referenced by FairMCApplication::FinishRun().
virtual TClonesArray* FairDetector::GetCollection (Int_t iColl) const pure virtual
Gets the produced collections
Implemented in EicDetector, and CbmRich.
Referenced by CbmStack::UpdateTrackIndex(), and PndStack::UpdateTrackIndex().
Int_t FairDetector::GetDetId () inline
Definition at line 93 of file FairDetector.h.
View newest version in sPHENIX GitHub at line 93 of file FairDetector.h
References fDetId.
void FairDetector::Initialize () virtual
Initialization of the detector is done here
Reimplemented in EicDetector, and CbmRich.
Definition at line 53 of file FairDetector.cxx.
View newest version in sPHENIX GitHub at line 53 of file FairDetector.cxx
References FairVolume::getGeoNode(), FairVolume::getModId(), FairModule::GetModId(), pos(), FairVolume::setMCid(), FairGeoVolume::setMCid(), and FairModule::svList.
Referenced by FairMCApplication::InitGeometry(), CbmRich::Initialize(), and EicDetector::Initialize().
FairDetector& FairDetector::operator= (const FairDetector &) inline private
Definition at line 99 of file FairDetector.h.
View newest version in sPHENIX GitHub at line 99 of file FairDetector.h
virtual void FairDetector::PostTrack () inline virtual
Definition at line 77 of file FairDetector.h.
View newest version in sPHENIX GitHub at line 77 of file FairDetector.h
Referenced by FairMCApplication::PostTrack().
virtual void FairDetector::PreTrack () inline virtual
Definition at line 80 of file FairDetector.h.
View newest version in sPHENIX GitHub at line 80 of file FairDetector.h
Referenced by FairMCApplication::PreTrack().
virtual Bool_t FairDetector::ProcessHits (FairVolume * v = 0) pure virtual
this method is called for each step during simulation (see FairMCApplication::Stepping())
Implemented in EicDetector, and CbmRich.
Referenced by FairMCApplication::Stepping().
virtual void FairDetector::Register () pure virtual
Registers the produced collections in FAIRRootManager.
Implemented in EicDetector, and CbmRich.
Referenced by FairMCApplication::InitGeometry().
virtual void FairDetector::Reset () pure virtual
has to be called after each event to reset the containers
Implemented in CbmRich, and EicDetector.
void FairDetector::SaveGeoParams ()
Definition at line 79 of file FairDetector.cxx.
View newest version in sPHENIX GitHub at line 79 of file FairDetector.cxx
References FairModule::flGeoPar, fLogger, FairLogger::Info(), FairModule::kGeoSaved, and MESSAGE_ORIGIN.
virtual void FairDetector::SetSpecialPhysicsCuts () inline virtual
Definition at line 89 of file FairDetector.h.
View newest version in sPHENIX GitHub at line 89 of file FairDetector.h
Referenced by FairMCApplication::InitGeometry().
Member Data Documentation
Int_t FairDetector::fDetId protected
Definition at line 106 of file FairDetector.h.
View newest version in sPHENIX GitHub at line 106 of file FairDetector.h
Referenced by GetDetId().
FairLogger* FairDetector::fLogger protected
Definition at line 107 of file FairDetector.h.
View newest version in sPHENIX GitHub at line 107 of file FairDetector.h
Referenced by EicFieldGradDetector::ConstructGeometry(), EicFieldMapDetector::ConstructGeometry(), EicDetector::ConstructGeometry(), EicDetector::ProcessHits(), and SaveGeoParams().
The documentation for this class was generated from the following files:
EicRoot/blob/master/base/FairDetector.h
EicRoot/blob/master/base/FairDetector.cxx