EIC Software: RawTowerZDCGeomv1 Class Reference
RawTowerZDCGeomv1 Class Reference
#include <fun4all_eicdetectors/blob/master/reconstruction/eiczdcbase/RawTowerZDCGeomv1.h>
Public Member Functions
RawTowerZDCGeomv1 ()
RawTowerZDCGeomv1 (RawTowerZDCDefs::keytype id)
~RawTowerZDCGeomv1 () override
void identify (std::ostream &os=std::cout) const override
void set_id (RawTowerZDCDefs::keytype key) override
RawTowerZDCDefs::keytype get_id () const override
int get_bineta () const override
int get_binphi () const override
int get_column () const override
int get_row () const override
int get_binl () const override
void set_center_x (double x) override
void set_center_y (double y) override
void set_center_z (double z) override
void set_size_x (double dx) override
void set_size_y (double dy) override
void set_size_z (double dz) override
double get_center_x () const override
double get_center_y () const override
double get_center_z () const override
double get_size_x () const override
double get_size_y () const override
double get_size_z () const override
double get_volume () const override
double get_center_radius () const override
double get_eta () const override
double get_phi () const override
double get_theta () const override
void set_tower_type (int tt) override
int get_tower_type () const override
Public Member Functions inherited from RawTowerZDCGeom
~RawTowerZDCGeom () override
virtual double get_roty () const
virtual double get_rotz () const
virtual void set_roty (double)
virtual void set_rotz (double)
Public Member Functions inherited from PHObject
PHObject ()
ctor
~PHObject () override
dtor
virtual PHObject * CloneMe () const
Virtual copy constructor.
virtual PHObject * clone () const final
PHObject * Clone (const char *newname="") const final
void Copy (TObject &object) const final
virtual void Reset ()
Clear Event.
virtual int isValid () const
isValid returns non zero if object contains vailid data
virtual int isValid (const float) const
virtual int isValid (const double) const
virtual int isValid (const int) const
virtual int isValid (const unsigned int) const
virtual int isImplemented (const float f) const
virtual int isImplemented (const double f) const
virtual int isImplemented (const int i) const
virtual int isImplemented (const unsigned int i) const
virtual int Integrate () const
virtual int Integrate (PHObject *)
virtual void CopyFrom (const PHObject *obj)
Protected Attributes
RawTowerZDCDefs::keytype _towerid = ~0
double _center_x = NAN
double _center_y = NAN
double _center_z = NAN
double _size_x = NAN
double _size_y = NAN
double _size_z = NAN
int _tower_type = -1
Additional Inherited Members
Protected Member Functions inherited from RawTowerZDCGeom
RawTowerZDCGeom ()
Detailed Description
Definition at line 11 of file RawTowerZDCGeomv1.h.
View newest version in sPHENIX GitHub at line 11 of file RawTowerZDCGeomv1.h
Constructor & Destructor Documentation
RawTowerZDCGeomv1::RawTowerZDCGeomv1 () inline
Definition at line 14 of file RawTowerZDCGeomv1.h.
View newest version in sPHENIX GitHub at line 14 of file RawTowerZDCGeomv1.h
RawTowerZDCGeomv1::RawTowerZDCGeomv1 (RawTowerZDCDefs::keytype id)
Definition at line 6 of file RawTowerZDCGeomv1.cc.
View newest version in sPHENIX GitHub at line 6 of file RawTowerZDCGeomv1.cc
RawTowerZDCGeomv1::~RawTowerZDCGeomv1 () inline override
Definition at line 16 of file RawTowerZDCGeomv1.h.
View newest version in sPHENIX GitHub at line 16 of file RawTowerZDCGeomv1.h
Member Function Documentation
int RawTowerZDCGeomv1::get_bineta () const override virtual
Reimplemented from RawTowerZDCGeom.
Definition at line 37 of file RawTowerZDCGeomv1.cc.
View newest version in sPHENIX GitHub at line 37 of file RawTowerZDCGeomv1.cc
References _towerid, and RawTowerZDCDefs::decode_index1zdc().
Referenced by get_column().
int RawTowerZDCGeomv1::get_binl () const override virtual
Reimplemented from RawTowerZDCGeom.
Definition at line 47 of file RawTowerZDCGeomv1.cc.
View newest version in sPHENIX GitHub at line 47 of file RawTowerZDCGeomv1.cc
References _towerid, and RawTowerZDCDefs::decode_index3zdc().
int RawTowerZDCGeomv1::get_binphi () const override virtual
Reimplemented from RawTowerZDCGeom.
Definition at line 42 of file RawTowerZDCGeomv1.cc.
View newest version in sPHENIX GitHub at line 42 of file RawTowerZDCGeomv1.cc
References _towerid, and RawTowerZDCDefs::decode_index2zdc().
Referenced by get_row().
double RawTowerZDCGeomv1::get_center_radius () const override virtual
Reimplemented from RawTowerZDCGeom.
Definition at line 11 of file RawTowerZDCGeomv1.cc.
View newest version in sPHENIX GitHub at line 11 of file RawTowerZDCGeomv1.cc
References _center_x, and _center_y.
double RawTowerZDCGeomv1::get_center_x () const inline override virtual
Reimplemented from RawTowerZDCGeom.
Definition at line 63 of file RawTowerZDCGeomv1.h.
View newest version in sPHENIX GitHub at line 63 of file RawTowerZDCGeomv1.h
References _center_x.
Referenced by identify().
double RawTowerZDCGeomv1::get_center_y () const inline override virtual
Reimplemented from RawTowerZDCGeom.
Definition at line 64 of file RawTowerZDCGeomv1.h.
View newest version in sPHENIX GitHub at line 64 of file RawTowerZDCGeomv1.h
References _center_y.
Referenced by identify().
double RawTowerZDCGeomv1::get_center_z () const inline override virtual
Reimplemented from RawTowerZDCGeom.
Definition at line 65 of file RawTowerZDCGeomv1.h.
View newest version in sPHENIX GitHub at line 65 of file RawTowerZDCGeomv1.h
References _center_z.
Referenced by identify().
int RawTowerZDCGeomv1::get_column () const inline override virtual
Reimplemented from RawTowerZDCGeom.
Definition at line 26 of file RawTowerZDCGeomv1.h.
View newest version in sPHENIX GitHub at line 26 of file RawTowerZDCGeomv1.h
References get_bineta().
double RawTowerZDCGeomv1::get_eta () const override virtual
Reimplemented from RawTowerZDCGeom.
Definition at line 24 of file RawTowerZDCGeomv1.cc.
View newest version in sPHENIX GitHub at line 24 of file RawTowerZDCGeomv1.cc
References Acts::VectorHelpers::eta(), get_theta(), and theta().
RawTowerZDCDefs::keytype RawTowerZDCGeomv1::get_id () const inline override virtual
Reimplemented from RawTowerZDCGeom.
Definition at line 21 of file RawTowerZDCGeomv1.h.
View newest version in sPHENIX GitHub at line 21 of file RawTowerZDCGeomv1.h
References _towerid.
double RawTowerZDCGeomv1::get_phi () const override virtual
Reimplemented from RawTowerZDCGeom.
Definition at line 31 of file RawTowerZDCGeomv1.cc.
View newest version in sPHENIX GitHub at line 31 of file RawTowerZDCGeomv1.cc
References _center_x, and _center_y.
int RawTowerZDCGeomv1::get_row () const inline override virtual
Reimplemented from RawTowerZDCGeom.
Definition at line 27 of file RawTowerZDCGeomv1.h.
View newest version in sPHENIX GitHub at line 27 of file RawTowerZDCGeomv1.h
References get_binphi().
double RawTowerZDCGeomv1::get_size_x () const inline override virtual
Reimplemented from RawTowerZDCGeom.
Definition at line 67 of file RawTowerZDCGeomv1.h.
View newest version in sPHENIX GitHub at line 67 of file RawTowerZDCGeomv1.h
References _size_x.
Referenced by identify().
double RawTowerZDCGeomv1::get_size_y () const inline override virtual
Reimplemented from RawTowerZDCGeom.
Definition at line 68 of file RawTowerZDCGeomv1.h.
View newest version in sPHENIX GitHub at line 68 of file RawTowerZDCGeomv1.h
References _size_y.
Referenced by identify().
double RawTowerZDCGeomv1::get_size_z () const inline override virtual
Reimplemented from RawTowerZDCGeom.
Definition at line 69 of file RawTowerZDCGeomv1.h.
View newest version in sPHENIX GitHub at line 69 of file RawTowerZDCGeomv1.h
References _size_z.
Referenced by identify().
double RawTowerZDCGeomv1::get_theta () const override virtual
Reimplemented from RawTowerZDCGeom.
Definition at line 17 of file RawTowerZDCGeomv1.cc.
View newest version in sPHENIX GitHub at line 17 of file RawTowerZDCGeomv1.cc
References _center_x, _center_y, _center_z, G4BECAL::radius, and theta().
Referenced by get_eta().
int RawTowerZDCGeomv1::get_tower_type () const inline override virtual
Reimplemented from RawTowerZDCGeom.
Definition at line 78 of file RawTowerZDCGeomv1.h.
View newest version in sPHENIX GitHub at line 78 of file RawTowerZDCGeomv1.h
References _tower_type.
double RawTowerZDCGeomv1::get_volume () const inline override virtual
Reimplemented from RawTowerZDCGeom.
Definition at line 70 of file RawTowerZDCGeomv1.h.
View newest version in sPHENIX GitHub at line 70 of file RawTowerZDCGeomv1.h
References _size_x, _size_y, and _size_z.
void RawTowerZDCGeomv1::identify (std::ostream & os = std::cout) const override virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from RawTowerZDCGeom.
Definition at line 52 of file RawTowerZDCGeomv1.cc.
View newest version in sPHENIX GitHub at line 52 of file RawTowerZDCGeomv1.cc
References _tower_type, get_center_x(), get_center_y(), get_center_z(), get_size_x(), get_size_y(), and get_size_z().
void RawTowerZDCGeomv1::set_center_x (double x) inline override virtual
Reimplemented from RawTowerZDCGeom.
Definition at line 31 of file RawTowerZDCGeomv1.h.
View newest version in sPHENIX GitHub at line 31 of file RawTowerZDCGeomv1.h
References _center_x, and x.
Referenced by EICG4ZDCRawTowerBuilderByHitIndex::ReadGeometryFromTable().
void RawTowerZDCGeomv1::set_center_y (double y) inline override virtual
Reimplemented from RawTowerZDCGeom.
Definition at line 36 of file RawTowerZDCGeomv1.h.
View newest version in sPHENIX GitHub at line 36 of file RawTowerZDCGeomv1.h
References _center_y, and y.
Referenced by EICG4ZDCRawTowerBuilderByHitIndex::ReadGeometryFromTable().
void RawTowerZDCGeomv1::set_center_z (double z) inline override virtual
Reimplemented from RawTowerZDCGeom.
Definition at line 41 of file RawTowerZDCGeomv1.h.
View newest version in sPHENIX GitHub at line 41 of file RawTowerZDCGeomv1.h
References _center_z, and z.
Referenced by EICG4ZDCRawTowerBuilderByHitIndex::ReadGeometryFromTable().
void RawTowerZDCGeomv1::set_id (RawTowerZDCDefs::keytype key) inline override virtual
Reimplemented from RawTowerZDCGeom.
Definition at line 20 of file RawTowerZDCGeomv1.h.
View newest version in sPHENIX GitHub at line 20 of file RawTowerZDCGeomv1.h
References _towerid.
void RawTowerZDCGeomv1::set_size_x (double dx) inline override virtual
Reimplemented from RawTowerZDCGeom.
Definition at line 47 of file RawTowerZDCGeomv1.h.
View newest version in sPHENIX GitHub at line 47 of file RawTowerZDCGeomv1.h
References _size_x, and dx.
Referenced by EICG4ZDCRawTowerBuilderByHitIndex::ReadGeometryFromTable().
void RawTowerZDCGeomv1::set_size_y (double dy) inline override virtual
Reimplemented from RawTowerZDCGeom.
Definition at line 52 of file RawTowerZDCGeomv1.h.
View newest version in sPHENIX GitHub at line 52 of file RawTowerZDCGeomv1.h
References _size_y, and dy.
Referenced by EICG4ZDCRawTowerBuilderByHitIndex::ReadGeometryFromTable().
void RawTowerZDCGeomv1::set_size_z (double dz) inline override virtual
Reimplemented from RawTowerZDCGeom.
Definition at line 57 of file RawTowerZDCGeomv1.h.
View newest version in sPHENIX GitHub at line 57 of file RawTowerZDCGeomv1.h
References _size_z, and dz.
Referenced by EICG4ZDCRawTowerBuilderByHitIndex::ReadGeometryFromTable().
void RawTowerZDCGeomv1::set_tower_type (int tt) inline override virtual
Reimplemented from RawTowerZDCGeom.
Definition at line 77 of file RawTowerZDCGeomv1.h.
View newest version in sPHENIX GitHub at line 77 of file RawTowerZDCGeomv1.h
References _tower_type.
Member Data Documentation
double RawTowerZDCGeomv1::_center_x = NAN protected
Definition at line 83 of file RawTowerZDCGeomv1.h.
View newest version in sPHENIX GitHub at line 83 of file RawTowerZDCGeomv1.h
Referenced by get_center_radius(), get_center_x(), get_phi(), get_theta(), and set_center_x().
double RawTowerZDCGeomv1::_center_y = NAN protected
Definition at line 84 of file RawTowerZDCGeomv1.h.
View newest version in sPHENIX GitHub at line 84 of file RawTowerZDCGeomv1.h
Referenced by get_center_radius(), get_center_y(), get_phi(), get_theta(), and set_center_y().
double RawTowerZDCGeomv1::_center_z = NAN protected
Definition at line 85 of file RawTowerZDCGeomv1.h.
View newest version in sPHENIX GitHub at line 85 of file RawTowerZDCGeomv1.h
Referenced by get_center_z(), get_theta(), and set_center_z().
double RawTowerZDCGeomv1::_size_x = NAN protected
Definition at line 87 of file RawTowerZDCGeomv1.h.
View newest version in sPHENIX GitHub at line 87 of file RawTowerZDCGeomv1.h
Referenced by get_size_x(), get_volume(), and set_size_x().
double RawTowerZDCGeomv1::_size_y = NAN protected
Definition at line 88 of file RawTowerZDCGeomv1.h.
View newest version in sPHENIX GitHub at line 88 of file RawTowerZDCGeomv1.h
Referenced by get_size_y(), get_volume(), and set_size_y().
double RawTowerZDCGeomv1::_size_z = NAN protected
Definition at line 89 of file RawTowerZDCGeomv1.h.
View newest version in sPHENIX GitHub at line 89 of file RawTowerZDCGeomv1.h
Referenced by get_size_z(), get_volume(), and set_size_z().
int RawTowerZDCGeomv1::_tower_type = -1 protected
Definition at line 91 of file RawTowerZDCGeomv1.h.
View newest version in sPHENIX GitHub at line 91 of file RawTowerZDCGeomv1.h
Referenced by get_tower_type(), identify(), and set_tower_type().
RawTowerZDCDefs::keytype RawTowerZDCGeomv1::_towerid = ~0 protected
Definition at line 81 of file RawTowerZDCGeomv1.h.
View newest version in sPHENIX GitHub at line 81 of file RawTowerZDCGeomv1.h
Referenced by get_bineta(), get_binl(), get_binphi(), get_id(), and set_id().
The documentation for this class was generated from the following files:
fun4all_eicdetectors/blob/master/reconstruction/eiczdcbase/RawTowerZDCGeomv1.h
fun4all_eicdetectors/blob/master/reconstruction/eiczdcbase/RawTowerZDCGeomv1.cc