EIC Software: PHFieldConfigv1 Class Reference
PHFieldConfigv1 Class Reference
PHFieldConfigv1 implements field configuration information for input a field map file.
#include <fun4all_coresoftware/blob/master/offline/packages/PHField/PHFieldConfigv1.h>
Public Member Functions
PHFieldConfigv1 (FieldConfigTypes field_config, const std::string &filename, double magfield_rescale=1.)
PHFieldConfigv1 ()
default constructor for ROOT file IO
virtual ~PHFieldConfigv1 ()
virtual PHObject * CloneMe () const
Virtual copy constructor.
virtual void identify (std::ostream &os=std::cout) const
virtual void Reset ()
Clear Content.
virtual int isValid () const
isValid returns non zero if object contains vailid data
FieldConfigTypes get_field_config () const
void set_field_config (FieldConfigTypes fieldConfig)
const std::string & get_filename () const
void set_filename (const std::string &filename)
double get_magfield_rescale () const
void set_magfield_rescale (double magfieldRescale)
Public Member Functions inherited from PHFieldConfig
virtual ~PHFieldConfig ()
std::string get_field_config_description () const
virtual void set_field_config (FieldConfigTypes fieldConfig)
virtual double get_field_mag_x () const
field value in Tesla for uniform field model ONLY for PHFieldConfig_v2
virtual void set_field_mag_x (double fieldMagX)
field value in Tesla for uniform field model ONLY for PHFieldConfig_v2
virtual double get_field_mag_y () const
field value in Tesla for uniform field model ONLY for PHFieldConfig_v2
virtual void set_field_mag_y (double fieldMagY)
field value in Tesla for uniform field model ONLY for PHFieldConfig_v2
virtual double get_field_mag_z () const
field value in Tesla for uniform field model ONLY for PHFieldConfig_v2
virtual void set_field_mag_z (double fieldMagZ)
field value in Tesla for uniform field model ONLY for PHFieldConfig_v2
Public Member Functions inherited from PHObject
PHObject ()
ctor
virtual ~PHObject ()
dtor
virtual PHObject * clone () const final
virtual PHObject * Clone (const char *newname="") const final
virtual void Copy (TObject &object) const final
virtual int isValid (const float) const
virtual int isValid (const double) const
virtual int isValid (const int) const
virtual int isValid (const unsigned int) const
virtual int isImplemented (const float f) const
virtual int isImplemented (const double f) const
virtual int isImplemented (const int i) const
virtual int isImplemented (const unsigned int i) const
virtual int Integrate () const
virtual int Integrate (PHObject *obj)
virtual void CopyFrom (const PHObject *obj)
Protected Attributes
FieldConfigTypes field_config_
std::string filename_
double magfield_rescale_
Additional Inherited Members
Public Types inherited from PHFieldConfig
enum FieldConfigTypes {
kFieldUniform = 0, kField2D = 2, kField3DCylindrical = 3, kFieldBeast = 4,
kFieldCleo = 5, Field3DCartesian = 1, kFieldInvalid = 9999
}
Protected Member Functions inherited from PHFieldConfig
PHFieldConfig ()
pure virtual interface class. not for direct use
Static Protected Attributes inherited from PHFieldConfig
static const std::string kInvalid_FileName
Detailed Description
PHFieldConfigv1 implements field configuration information for input a field map file.
Definition at line 23 of file PHFieldConfigv1.h.
View newest version in sPHENIX GitHub at line 23 of file PHFieldConfigv1.h
Constructor & Destructor Documentation
PHFieldConfigv1::PHFieldConfigv1 (FieldConfigTypes field_config, const std::string & filename, double magfield_rescale = 1.)
Definition at line 15 of file PHFieldConfigv1.cc.
View newest version in sPHENIX GitHub at line 15 of file PHFieldConfigv1.cc
PHFieldConfigv1::PHFieldConfigv1 () inline
default constructor for ROOT file IO
Definition at line 32 of file PHFieldConfigv1.h.
View newest version in sPHENIX GitHub at line 32 of file PHFieldConfigv1.h
Referenced by CloneMe().
virtual PHFieldConfigv1::~PHFieldConfigv1 () inline virtual
Definition at line 37 of file PHFieldConfigv1.h.
View newest version in sPHENIX GitHub at line 37 of file PHFieldConfigv1.h
Member Function Documentation
virtual PHObject* PHFieldConfigv1::CloneMe () const inline virtual
Virtual copy constructor.
Reimplemented from PHObject.
Definition at line 40 of file PHFieldConfigv1.h.
View newest version in sPHENIX GitHub at line 40 of file PHFieldConfigv1.h
References PHFieldConfigv1().
FieldConfigTypes PHFieldConfigv1::get_field_config () const inline virtual
Reimplemented from PHFieldConfig.
Definition at line 56 of file PHFieldConfigv1.h.
View newest version in sPHENIX GitHub at line 56 of file PHFieldConfigv1.h
References field_config_.
const std::string& PHFieldConfigv1::get_filename () const inline virtual
Reimplemented from PHFieldConfig.
Definition at line 65 of file PHFieldConfigv1.h.
View newest version in sPHENIX GitHub at line 65 of file PHFieldConfigv1.h
References filename_.
Referenced by identify().
double PHFieldConfigv1::get_magfield_rescale () const inline virtual
Reimplemented from PHFieldConfig.
Definition at line 75 of file PHFieldConfigv1.h.
View newest version in sPHENIX GitHub at line 75 of file PHFieldConfigv1.h
References magfield_rescale_.
Referenced by identify().
void PHFieldConfigv1::identify (std::ostream & os = std::cout) const virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from PHFieldConfig.
Definition at line 27 of file PHFieldConfigv1.cc.
View newest version in sPHENIX GitHub at line 27 of file PHFieldConfigv1.cc
References PHFieldConfig::get_field_config_description(), get_filename(), get_magfield_rescale(), and isValid().
int PHFieldConfigv1::isValid () const virtual
isValid returns non zero if object contains vailid data
isValid returns non zero if object contains valid data
Reimplemented from PHObject.
Definition at line 44 of file PHFieldConfigv1.cc.
View newest version in sPHENIX GitHub at line 44 of file PHFieldConfigv1.cc
References filename_.
Referenced by identify().
virtual void PHFieldConfigv1::Reset () inline virtual
Clear Content.
Reimplemented from PHObject.
Definition at line 50 of file PHFieldConfigv1.h.
View newest version in sPHENIX GitHub at line 50 of file PHFieldConfigv1.h
void PHFieldConfigv1::set_field_config (FieldConfigTypes fieldConfig) inline
Definition at line 60 of file PHFieldConfigv1.h.
View newest version in sPHENIX GitHub at line 60 of file PHFieldConfigv1.h
References field_config_.
void PHFieldConfigv1::set_filename (const std::string & filename) inline virtual
Reimplemented from PHFieldConfig.
Definition at line 70 of file PHFieldConfigv1.h.
View newest version in sPHENIX GitHub at line 70 of file PHFieldConfigv1.h
References INPUTHEPMC::filename, and filename_.
void PHFieldConfigv1::set_magfield_rescale (double magfieldRescale) inline virtual
Reimplemented from PHFieldConfig.
Definition at line 80 of file PHFieldConfigv1.h.
View newest version in sPHENIX GitHub at line 80 of file PHFieldConfigv1.h
References magfield_rescale_.
Member Data Documentation
FieldConfigTypes PHFieldConfigv1::field_config_ protected
Definition at line 86 of file PHFieldConfigv1.h.
View newest version in sPHENIX GitHub at line 86 of file PHFieldConfigv1.h
Referenced by get_field_config(), and set_field_config().
std::string PHFieldConfigv1::filename_ protected
Definition at line 87 of file PHFieldConfigv1.h.
View newest version in sPHENIX GitHub at line 87 of file PHFieldConfigv1.h
Referenced by get_filename(), isValid(), and set_filename().
double PHFieldConfigv1::magfield_rescale_ protected
Definition at line 88 of file PHFieldConfigv1.h.
View newest version in sPHENIX GitHub at line 88 of file PHFieldConfigv1.h
Referenced by get_magfield_rescale(), and set_magfield_rescale().
The documentation for this class was generated from the following files:
fun4all_coresoftware/blob/master/offline/packages/PHField/PHFieldConfigv1.h
fun4all_coresoftware/blob/master/offline/packages/PHField/PHFieldConfigv1.cc