EIC Software: FairBaseParSet Class Reference
FairBaseParSet Class Reference
#include <EicRoot/blob/master/base/FairBaseParSet.h>
Public Member Functions
FairBaseParSet (const char *name="FairBaseParSet", const char *title="Class for base parameter io", const char *context="BaseDefaultContext")
~FairBaseParSet (void)
void clear (void)
void putParams (FairParamList *)
Bool_t getParams (FairParamList *)
void SetDetList (TObjArray *array)
void SetGeoNodes (TObjArray *array)
void SetGen (FairPrimaryGenerator *gen)
void SetBeamMom (Double_t BMom)
void SetGeometry (TGeoManager *Geom)
void SetContListStr (TObjArray *list)
TObjArray * GetDetList ()
TObjArray * GetGeoNodes ()
FairPrimaryGenerator * GetPriGen ()
Double_t GetBeamMom ()
TGeoManager * GetGeometry ()
TObjArray * GetContList ()
Public Member Functions inherited from FairParGenericSet
FairParGenericSet (const char *name, const char *title, const char *context)
virtual ~FairParGenericSet ()
virtual void printParams ()
Bool_t init (FairParIo *inp)
Int_t write (FairParIo *output)
Public Member Functions inherited from FairParSet
FairParSet (const char *name="", const char *title="", const char *context="")
virtual ~FairParSet ()
virtual Bool_t init ()
virtual Int_t write ()
virtual void print ()
const char * getDetectorName ()
void resetInputVersions ()
void setInputVersion (Int_t v=-1, Int_t i=0)
Int_t getInputVersion (Int_t i)
void setStatic (Bool_t flag=kTRUE)
Bool_t isStatic ()
void setChanged (Bool_t flag=kTRUE)
Bool_t hasChanged ()
const char * getParamContext () const
void setAuthor (const char *s)
const char * getAuthor () const
void setDescription (const char *s)
const char * getDescription () const
void copyComment (FairParSet &r)
Protected Member Functions
ClassDef(FairBaseParSet,
4) private FairBaseParSet & operator= (const FairBaseParSet &)
Protected Member Functions inherited from FairParGenericSet
FairParGenericSet ()
Protected Attributes
TObjArray * fDetList
Detectors used in the simulation.
TObjArray * fGeoNodes
List of FairGeoNodes for sensitive volumes.
FairPrimaryGenerator * fPriGen
Generator used for simulation.
Double_t fBeamMom
Beam momentum (GeV/c)
TGeoManager * fGeom
Full Geometry.
TObjArray * fContNameList
List of parameter container names in the RUN.
Detailed Description
Definition at line 18 of file FairBaseParSet.h.
View newest version in sPHENIX GitHub at line 18 of file FairBaseParSet.h
Constructor & Destructor Documentation
FairBaseParSet::FairBaseParSet (const char * name = "FairBaseParSet", const char * title = "Class for base parameter io", const char * context = "BaseDefaultContext")
constructor
Parameters
name : Parameter set name
title,: Parameter set title
context,: Parameter set context
FairBaseParSet::~FairBaseParSet (void)
dtor
Definition at line 28 of file FairBaseParSet.cxx.
View newest version in sPHENIX GitHub at line 28 of file FairBaseParSet.cxx
Member Function Documentation
void FairBaseParSet::clear (void) virtual
clear
Reimplemented from FairParSet.
Definition at line 32 of file FairBaseParSet.cxx.
View newest version in sPHENIX GitHub at line 32 of file FairBaseParSet.cxx
References fContNameList, fDetList, fGeoNodes, and fPriGen.
Double_t FairBaseParSet::GetBeamMom () inline
Get the Beam Momentum used in the simulation (GeV/c)
Definition at line 93 of file FairBaseParSet.h.
View newest version in sPHENIX GitHub at line 93 of file FairBaseParSet.h
References fBeamMom.
TObjArray* FairBaseParSet::GetContList () inline
Get the parameter container list used in this run
Definition at line 101 of file FairBaseParSet.h.
View newest version in sPHENIX GitHub at line 101 of file FairBaseParSet.h
References fContNameList.
Referenced by PndFieldCreator::SetParm().
TObjArray* FairBaseParSet::GetDetList () inline
Get the detector list used in the simulation
Definition at line 81 of file FairBaseParSet.h.
View newest version in sPHENIX GitHub at line 81 of file FairBaseParSet.h
References fDetList.
TGeoManager* FairBaseParSet::GetGeometry () inline
Get the geometry (TGeoManager) used in the simulation
Definition at line 97 of file FairBaseParSet.h.
View newest version in sPHENIX GitHub at line 97 of file FairBaseParSet.h
References fGeom.
Referenced by FairRunAna::Init(), and FairRunAna::InitContainers().
TObjArray* FairBaseParSet::GetGeoNodes () inline
Get the Geometry Nodes list used in the simulation
Definition at line 85 of file FairBaseParSet.h.
View newest version in sPHENIX GitHub at line 85 of file FairBaseParSet.h
References fGeoNodes.
Referenced by FairModule::ProcessNodes().
Bool_t FairBaseParSet::getParams (FairParamList * l) virtual
Fills all persistent data members from the list after reading. The function returns false, when a data member is not in the list.
Parameters
FairParamList : Parameter list to be filled
Implements FairParGenericSet.
Definition at line 53 of file FairBaseParSet.cxx.
View newest version in sPHENIX GitHub at line 53 of file FairBaseParSet.cxx
References fBeamMom, fContNameList, fDetList, fGeom, fGeoNodes, FairParamList::fill(), FairParamList::fillObject(), and fPriGen.
FairPrimaryGenerator* FairBaseParSet::GetPriGen () inline
Get the Primery generator used in the simulation
Definition at line 89 of file FairBaseParSet.h.
View newest version in sPHENIX GitHub at line 89 of file FairBaseParSet.h
References fPriGen.
Referenced by FwdTrackFinder::Init().
ClassDef (FairBaseParSet,4) private FairBaseParSet& FairBaseParSet::operator= (const FairBaseParSet &) inline protected
Definition at line 122 of file FairBaseParSet.h.
View newest version in sPHENIX GitHub at line 122 of file FairBaseParSet.h
void FairBaseParSet::putParams (FairParamList * l) virtual
Fills all persistent data members into the list for write.
Parameters
FairParamList : Parameter list to be filled
Implements FairParGenericSet.
Definition at line 42 of file FairBaseParSet.cxx.
View newest version in sPHENIX GitHub at line 42 of file FairBaseParSet.cxx
References FairParamList::add(), FairParamList::addObject(), fBeamMom, fContNameList, fDetList, fGeom, fGeoNodes, and fPriGen.
void FairBaseParSet::SetBeamMom (Double_t BMom) inline
Set the beam momentum (if any) used in the simulation
Parameters
BMom,: Beam Momentum in GeV/c
Definition at line 67 of file FairBaseParSet.h.
View newest version in sPHENIX GitHub at line 67 of file FairBaseParSet.h
References fBeamMom.
Referenced by FairRunSim::Init().
void FairBaseParSet::SetContListStr (TObjArray * list) inline
Set the list of parameter containers used in a run
Parameters
array,: TObjArray of containers
Definition at line 77 of file FairBaseParSet.h.
View newest version in sPHENIX GitHub at line 77 of file FairBaseParSet.h
References fContNameList, and charm_jet_coverage::list.
Referenced by FairRunSim::Init().
void FairBaseParSet::SetDetList (TObjArray * array) inline
Set the detector list used in the simulation
Parameters
array,: TObjArray of detector
Definition at line 52 of file FairBaseParSet.h.
View newest version in sPHENIX GitHub at line 52 of file FairBaseParSet.h
References fDetList.
Referenced by FairRunSim::Init().
void FairBaseParSet::SetGen (FairPrimaryGenerator * gen) inline
Set the Generator used in the simulation
Parameters
gen,: Primary generator used in simulation
Definition at line 62 of file FairBaseParSet.h.
View newest version in sPHENIX GitHub at line 62 of file FairBaseParSet.h
References fPriGen.
Referenced by FairRunSim::Init().
void FairBaseParSet::SetGeometry (TGeoManager * Geom) inline
Set the Geometry (TGeoManager) used in the simulation
Parameters
Geom,: TGeoManager of the full geometry
Definition at line 72 of file FairBaseParSet.h.
View newest version in sPHENIX GitHub at line 72 of file FairBaseParSet.h
References fGeom.
Referenced by FairRunSim::Init().
void FairBaseParSet::SetGeoNodes (TObjArray * array) inline
Set the Geometry node list used in the simulation
Parameters
array,: TObjArray of Geometry nodes
Definition at line 57 of file FairBaseParSet.h.
View newest version in sPHENIX GitHub at line 57 of file FairBaseParSet.h
References fGeoNodes.
Member Data Documentation
Double_t FairBaseParSet::fBeamMom protected
Beam momentum (GeV/c)
Definition at line 112 of file FairBaseParSet.h.
View newest version in sPHENIX GitHub at line 112 of file FairBaseParSet.h
Referenced by GetBeamMom(), getParams(), putParams(), and SetBeamMom().
TObjArray* FairBaseParSet::fContNameList protected
List of parameter container names in the RUN.
Definition at line 116 of file FairBaseParSet.h.
View newest version in sPHENIX GitHub at line 116 of file FairBaseParSet.h
Referenced by clear(), GetContList(), getParams(), putParams(), and SetContListStr().
TObjArray* FairBaseParSet::fDetList protected
Detectors used in the simulation.
Definition at line 106 of file FairBaseParSet.h.
View newest version in sPHENIX GitHub at line 106 of file FairBaseParSet.h
Referenced by clear(), GetDetList(), getParams(), putParams(), and SetDetList().
TGeoManager* FairBaseParSet::fGeom protected
Full Geometry.
Definition at line 114 of file FairBaseParSet.h.
View newest version in sPHENIX GitHub at line 114 of file FairBaseParSet.h
Referenced by GetGeometry(), getParams(), putParams(), and SetGeometry().
TObjArray* FairBaseParSet::fGeoNodes protected
List of FairGeoNodes for sensitive volumes.
Definition at line 108 of file FairBaseParSet.h.
View newest version in sPHENIX GitHub at line 108 of file FairBaseParSet.h
Referenced by clear(), GetGeoNodes(), getParams(), putParams(), and SetGeoNodes().
FairPrimaryGenerator* FairBaseParSet::fPriGen protected
Generator used for simulation.
Definition at line 110 of file FairBaseParSet.h.
View newest version in sPHENIX GitHub at line 110 of file FairBaseParSet.h
Referenced by clear(), getParams(), GetPriGen(), putParams(), and SetGen().
The documentation for this class was generated from the following files:
EicRoot/blob/master/base/FairBaseParSet.h
EicRoot/blob/master/base/FairBaseParSet.cxx