EIC Software: point_t Class Reference
point_t Class Reference
#include <EicRoot/blob/master/eic/cad/elmer/src/meshtype.h>
Public Member Functions
point_t ()
~point_t ()
void setSharp (bool)
bool isSharp () const
void setEdges (int)
int getEdges () const
void setEdgeIndex (int, int)
int getEdgeIndex (int) const
void newEdgeIndexes (int)
void deleteEdgeIndexes ()
Public Member Functions inherited from element_t
element_t ()
~element_t ()
void setNature (int)
int getNature () const
void setCode (int)
int getCode () const
void setNodes (int)
int getNodes () const
void setIndex (int)
int getIndex () const
void setSelected (int)
int getSelected () const
int getNodeIndex (int) const
void setNodeIndex (int, int)
int * getNodeIndexes () const
void newNodeIndexes (int)
void deleteNodeIndexes ()
Private Attributes
bool sharp_point
int edges
int * edge
Detailed Description
Definition at line 107 of file meshtype.h.
View newest version in sPHENIX GitHub at line 107 of file meshtype.h
Constructor & Destructor Documentation
point_t::point_t ()
Definition at line 175 of file meshtype.cpp.
View newest version in sPHENIX GitHub at line 175 of file meshtype.cpp
point_t::~point_t ()
Definition at line 179 of file meshtype.cpp.
View newest version in sPHENIX GitHub at line 179 of file meshtype.cpp
Member Function Documentation
void point_t::deleteEdgeIndexes ()
Definition at line 218 of file meshtype.cpp.
View newest version in sPHENIX GitHub at line 218 of file meshtype.cpp
int point_t::getEdgeIndex (int n) const
Definition at line 203 of file meshtype.cpp.
View newest version in sPHENIX GitHub at line 203 of file meshtype.cpp
References n.
Referenced by mesh_t::save().
int point_t::getEdges () const
Definition at line 198 of file meshtype.cpp.
View newest version in sPHENIX GitHub at line 198 of file meshtype.cpp
Referenced by mesh_t::load().
bool point_t::isSharp () const
Definition at line 188 of file meshtype.cpp.
View newest version in sPHENIX GitHub at line 188 of file meshtype.cpp
void point_t::newEdgeIndexes (int n)
Definition at line 213 of file meshtype.cpp.
View newest version in sPHENIX GitHub at line 213 of file meshtype.cpp
References n.
Referenced by mesh_t::load().
void point_t::setEdgeIndex (int m, int n)
Definition at line 208 of file meshtype.cpp.
View newest version in sPHENIX GitHub at line 208 of file meshtype.cpp
References Acts::UnitConstants::m, and n.
Referenced by mesh_t::load().
void point_t::setEdges (int n)
Definition at line 193 of file meshtype.cpp.
View newest version in sPHENIX GitHub at line 193 of file meshtype.cpp
References n.
Referenced by mesh_t::load().
void point_t::setSharp (bool b)
Definition at line 183 of file meshtype.cpp.
View newest version in sPHENIX GitHub at line 183 of file meshtype.cpp
Member Data Documentation
int* point_t::edge private
Definition at line 124 of file meshtype.h.
View newest version in sPHENIX GitHub at line 124 of file meshtype.h
int point_t::edges private
Definition at line 123 of file meshtype.h.
View newest version in sPHENIX GitHub at line 123 of file meshtype.h
bool point_t::sharp_point private
Definition at line 122 of file meshtype.h.
View newest version in sPHENIX GitHub at line 122 of file meshtype.h
The documentation for this class was generated from the following files:
EicRoot/blob/master/eic/cad/elmer/src/meshtype.h
EicRoot/blob/master/eic/cad/elmer/src/meshtype.cpp