EIC Software: PndTrack Class Reference
PndTrack Class Reference
#include <EicRoot/blob/master/pnddata/TrackData/PndTrack.h>
Public Member Functions
PndTrack ()
PndTrack (const FairTrackParP &first, const FairTrackParP &last, const PndTrackCand &cand, Int_t flag=0, Double_t chi2=-1., Int_t ndf=0, Int_t pid=0, Int_t id=-1, Int_t type=-1)
void Print ()
Int_t GetPidHypo () const
Int_t GetFlag () const
Double_t GetChi2 () const
Int_t GetNDF () const
Int_t GetRefIndex () const
void SetPidHypo (Int_t i)
void SetFlag (Int_t i)
void SetChi2 (Double_t d)
void SetChiSquareCCDF (Double_t d)
void SetNDF (Int_t i)
void SetRefIndex (TString branch, Int_t i)
void SetRefIndex (Int_t i)
void SetTrackCand (const PndTrackCand &cand)
void SetTrackCandRef (PndTrackCand *candPointer)
PndTrackCand * GetPndTrackCandViaRef ()
PndTrackCand GetTrackCand ()
PndTrackCand * GetTrackCandPtr ()
FairTrackParP GetParamFirst ()
FairTrackParP GetParamLast ()
Public Member Functions inherited from FairTimeStamp
FairTimeStamp ()
FairTimeStamp (Double_t time)
FairTimeStamp (Double_t time, Double_t timeerror)
virtual ~FairTimeStamp ()
virtual Double_t GetTimeStamp () const
virtual Double_t GetTimeStampError () const
virtual FairLink GetEntryNr () const
virtual void SetTimeStamp (Double_t t)
virtual void SetTimeStampError (Double_t t)
virtual void SetEntryNr (FairLink entry)
virtual Int_t Compare (const TObject *obj) const
void Print (std::ostream &out=std::cout) const
virtual Bool_t IsSortable () const
virtual bool equal (FairTimeStamp *data)
Public Member Functions inherited from FairMultiLinkedData
FairMultiLinkedData ()
Default constructor.
FairMultiLinkedData (std::set< FairLink > links, Bool_t persistanceCheck=kTRUE)
Constructor.
FairMultiLinkedData (TString dataType, std::vector< Int_t > links, Int_t fileId=-1, Int_t evtId=-1, Bool_t persistanceCheck=kTRUE, Bool_t bypass=kFALSE, Float_t mult=1.0)
Constructor.
FairMultiLinkedData (Int_t dataType, std::vector< Int_t > links, Int_t fileId=-1, Int_t evtId=-1, Bool_t persistanceCheck=kTRUE, Bool_t bypass=kFALSE, Float_t mult=1.0)
Constructor.
virtual ~FairMultiLinkedData ()
virtual std::set< FairLink > GetLinks () const
returns stored links as FairLinks
virtual Int_t GetNLinks () const
returns the number of stored links
virtual FairLink GetLink (Int_t pos) const
returns the FairLink at the given position
virtual FairMultiLinkedData GetLinksWithType (Int_t type) const
Gives you a list of links which contain the given type.
TObject * GetData (FairLink &myLink)
Get the TObject the Link is pointing to.
virtual Int_t GetDefaultType ()
Bool_t GetPersistanceCheck ()
Returns the value of PersistanceCheck.
Int_t GetVerbose ()
Returns the verbosity level.
virtual void SetDefaultType (Int_t type)
virtual void SetPersistanceCheck (Bool_t check)
Controls if a persistance check of a link is done or not.
virtual void SetVerbose (Int_t level)
Sets the verbosity level.
virtual void SetLinks (FairMultiLinkedData links, Float_t mult=1.0)
Sets the links as vector of FairLink.
virtual void SetLink (FairLink link, Bool_t bypass=kFALSE, Float_t mult=1.0)
Sets the Links with a single FairLink.
virtual void AddLinks (FairMultiLinkedData links, Float_t mult=1.0)
Adds a List of FairLinks (FairMultiLinkedData) to fLinks.
virtual void AddLink (FairLink link, Bool_t bypass=kFALSE, Float_t mult=1.0)
Adds a FairLink link at the end of fLinks. If multi is kTRUE a link is allowed more than once otherwise it is stored only once.
virtual void InsertLink (FairLink link)
Inserts a link into the list of links without persistance checking.
virtual void AddAllWeights (Double_t weight)
Adds weight to all Links.
virtual void SetAllWeights (Double_t weight)
Sets a common weight for Links.
virtual void MultiplyAllWeights (Double_t weight)
Multiplies all Links with weight.
virtual Bool_t IsLinkInList (FairLink link)
Test if a given link is in fLinks.
virtual Bool_t IsLinkInList (Int_t type, Int_t index)
Same as IsLinkInList(FairLink) just with type and index given separately.
virtual Int_t LinkPosInList (FairLink link)
returns position of link in fLinks. If it is not in the list -1 is returned
virtual Int_t LinkPosInList (Int_t type, Int_t index)
Same as LinkPosInList(FairLink)
virtual void DeleteLink (FairLink link)
Deletes a link ouf of fLinks.
virtual void DeleteLink (Int_t type, Int_t index)
Deletes a link ouf of fLinks.
virtual void Reset ()
virtual void ResetLinks ()
Clears fLinks.
void Print (std::ostream &out=std::cout) const
Output.
Public Attributes
std::vector
< NaiveTrackParameterization > mParameterizations
Private Attributes
FairTrackParP fTrackParamFirst
FairTrackParP fTrackParamLast
PndTrackCand fTrackCand
TRef fRefToPndTrackCand
Int_t fPidHypo
Int_t fFlag
Double_t fChi2
Double_t fChiSquareCCDF
Int_t fNDF
Int_t fRefIndex
Additional Inherited Members
Protected Member Functions inherited from FairTimeStamp
ClassDef (FairTimeStamp, 2)
indicates where the data is stored in the branch
Protected Attributes inherited from FairTimeStamp
Double_t fTimeStamp
Double_t fTimeStampError
FairLink fEntryNr
Detailed Description
Definition at line 50 of file PndTrack.h.
View newest version in sPHENIX GitHub at line 50 of file PndTrack.h
Constructor & Destructor Documentation
PndTrack::PndTrack ()
Definition at line 14 of file PndTrack.cxx.
View newest version in sPHENIX GitHub at line 14 of file PndTrack.cxx
References fChi2, fChiSquareCCDF, fFlag, fNDF, fPidHypo, and fRefIndex.
PndTrack::PndTrack (const FairTrackParP & first, const FairTrackParP & last, const PndTrackCand & cand, Int_t flag = 0, Double_t chi2 = -1., Int_t ndf = 0, Int_t pid = 0, Int_t id = -1, Int_t type = -1)
Definition at line 25 of file PndTrack.cxx.
View newest version in sPHENIX GitHub at line 25 of file PndTrack.cxx
References fChi2, fChiSquareCCDF, fNDF, FairTimeStamp::GetTimeStamp(), FairTimeStamp::GetTimeStampError(), FairMultiLinkedData::SetLink(), FairTimeStamp::SetTimeStamp(), and FairTimeStamp::SetTimeStampError().
Member Function Documentation
Double_t PndTrack::GetChi2 () const inline
Definition at line 61 of file PndTrack.h.
View newest version in sPHENIX GitHub at line 61 of file PndTrack.h
References fChi2.
Referenced by PndTrackArrayMerger::Exec(), PndGFTrackToPndTrackConvertorTask::Exec(), PndRecoMultiKalmanTask::Exec(), PndRecoKalmanTask::Exec(), and PndPidCorrelator::GetTrackInfo().
Int_t PndTrack::GetFlag () const inline
Definition at line 60 of file PndTrack.h.
View newest version in sPHENIX GitHub at line 60 of file PndTrack.h
References fFlag.
Referenced by PndTrackArrayMerger::Exec(), PndGFTrackToPndTrackConvertorTask::Exec(), PndRecoMultiKalmanTask::Exec(), PndRecoKalmanTask::Exec(), and PndPidCorrelator::GetTrackInfo().
Int_t PndTrack::GetNDF () const inline
Definition at line 62 of file PndTrack.h.
View newest version in sPHENIX GitHub at line 62 of file PndTrack.h
References fNDF.
Referenced by PndTrackArrayMerger::Exec(), PndGFTrackToPndTrackConvertorTask::Exec(), PndRecoMultiKalmanTask::Exec(), PndRecoKalmanTask::Exec(), and PndPidCorrelator::GetTrackInfo().
FairTrackParP PndTrack::GetParamFirst () inline
Definition at line 77 of file PndTrack.h.
View newest version in sPHENIX GitHub at line 77 of file PndTrack.h
References fTrackParamFirst.
Referenced by PndTrackArrayMerger::Exec(), PndGFTrackToPndTrackConvertorTask::Exec(), PndRecoMultiKalmanTask::Exec(), PndRecoKalmanTask::Exec(), PndRecoDafFit::Fit(), PndRecoKalmanFit::Fit(), and PndPidCorrelator::GetTrackInfo().
FairTrackParP PndTrack::GetParamLast () inline
Definition at line 78 of file PndTrack.h.
View newest version in sPHENIX GitHub at line 78 of file PndTrack.h
References fTrackParamLast.
Referenced by PndPidCorrelator::ConstructChargedCandidate(), CbmRichTrackExtrapolationKF::DoExtrapolation(), PndTrackArrayMerger::Exec(), PndGFTrackToPndTrackConvertorTask::Exec(), PndRecoMultiKalmanTask::Exec(), PndRecoKalmanTask::Exec(), and PndPidCorrelator::GetTrackInfo().
Int_t PndTrack::GetPidHypo () const inline
Definition at line 59 of file PndTrack.h.
View newest version in sPHENIX GitHub at line 59 of file PndTrack.h
References fPidHypo.
Referenced by PndTrackArrayMerger::Exec(), PndGFTrackToPndTrackConvertorTask::Exec(), PndRecoMultiKalmanTask::Exec(), and PndRecoKalmanTask::Exec().
PndTrackCand* PndTrack::GetPndTrackCandViaRef () inline
Definition at line 73 of file PndTrack.h.
View newest version in sPHENIX GitHub at line 73 of file PndTrack.h
References fRefToPndTrackCand.
Int_t PndTrack::GetRefIndex () const inline
Definition at line 63 of file PndTrack.h.
View newest version in sPHENIX GitHub at line 63 of file PndTrack.h
References fRefIndex.
PndTrackCand PndTrack::GetTrackCand () inline
Definition at line 75 of file PndTrack.h.
View newest version in sPHENIX GitHub at line 75 of file PndTrack.h
References fTrackCand.
Referenced by PndPidCorrelator::ConstructChargedCandidate(), PndGFTrackToPndTrackConvertorTask::Exec(), PndRecoMultiKalmanTask::Exec(), PndRecoKalmanTask::Exec(), EicHtcTask::Exec(), PndRecoDafFit::Fit(), and PndRecoKalmanFit::Fit().
PndTrackCand* PndTrack::GetTrackCandPtr () inline
Definition at line 76 of file PndTrack.h.
View newest version in sPHENIX GitHub at line 76 of file PndTrack.h
References fTrackCand.
Referenced by PndTrackArrayMerger::Exec(), and PndRecoKalmanFit::Fit().
void PndTrack::Print (void)
Definition at line 37 of file PndTrack.cxx.
View newest version in sPHENIX GitHub at line 37 of file PndTrack.cxx
References fChi2, fNDF, fRefIndex, fTrackParamFirst, fTrackParamLast, and FairTrackParP::Print().
void PndTrack::SetChi2 (Double_t d) inline
Definition at line 66 of file PndTrack.h.
View newest version in sPHENIX GitHub at line 66 of file PndTrack.h
References d, and fChi2.
Referenced by GenfitTrack2PndTrack().
void PndTrack::SetChiSquareCCDF (Double_t d) inline
Definition at line 67 of file PndTrack.h.
View newest version in sPHENIX GitHub at line 67 of file PndTrack.h
References d, and fChiSquareCCDF.
void PndTrack::SetFlag (Int_t i) inline
Definition at line 65 of file PndTrack.h.
View newest version in sPHENIX GitHub at line 65 of file PndTrack.h
References fFlag.
Referenced by PndRecoKalmanTask::Exec(), PndRecoDafFit::Fit(), PndRecoKalmanFit::Fit(), and GenfitTrack2PndTrack().
void PndTrack::SetNDF (Int_t i) inline
Definition at line 68 of file PndTrack.h.
View newest version in sPHENIX GitHub at line 68 of file PndTrack.h
References fNDF.
Referenced by GenfitTrack2PndTrack().
void PndTrack::SetPidHypo (Int_t i) inline
Definition at line 64 of file PndTrack.h.
View newest version in sPHENIX GitHub at line 64 of file PndTrack.h
References fPidHypo.
void PndTrack::SetRefIndex (TString branch, Int_t i) inline
Definition at line 69 of file PndTrack.h.
View newest version in sPHENIX GitHub at line 69 of file PndTrack.h
References fRefIndex, and FairMultiLinkedData::SetLink().
void PndTrack::SetRefIndex (Int_t i) inline
Definition at line 70 of file PndTrack.h.
View newest version in sPHENIX GitHub at line 70 of file PndTrack.h
References fRefIndex.
void PndTrack::SetTrackCand (const PndTrackCand & cand) inline
Definition at line 71 of file PndTrack.h.
View newest version in sPHENIX GitHub at line 71 of file PndTrack.h
References fTrackCand.
void PndTrack::SetTrackCandRef (PndTrackCand * candPointer) inline
Definition at line 72 of file PndTrack.h.
View newest version in sPHENIX GitHub at line 72 of file PndTrack.h
References fRefToPndTrackCand.
Member Data Documentation
Double_t PndTrack::fChi2 private
Definition at line 89 of file PndTrack.h.
View newest version in sPHENIX GitHub at line 89 of file PndTrack.h
Referenced by GetChi2(), PndTrack(), Print(), and SetChi2().
Double_t PndTrack::fChiSquareCCDF private
Definition at line 92 of file PndTrack.h.
View newest version in sPHENIX GitHub at line 92 of file PndTrack.h
Referenced by PndTrack(), and SetChiSquareCCDF().
Int_t PndTrack::fFlag private
Definition at line 88 of file PndTrack.h.
View newest version in sPHENIX GitHub at line 88 of file PndTrack.h
Referenced by GetFlag(), PndTrack(), and SetFlag().
Int_t PndTrack::fNDF private
Definition at line 93 of file PndTrack.h.
View newest version in sPHENIX GitHub at line 93 of file PndTrack.h
Referenced by GetNDF(), PndTrack(), Print(), and SetNDF().
Int_t PndTrack::fPidHypo private
Definition at line 87 of file PndTrack.h.
View newest version in sPHENIX GitHub at line 87 of file PndTrack.h
Referenced by GetPidHypo(), PndTrack(), and SetPidHypo().
Int_t PndTrack::fRefIndex private
Definition at line 94 of file PndTrack.h.
View newest version in sPHENIX GitHub at line 94 of file PndTrack.h
Referenced by GetRefIndex(), PndTrack(), Print(), and SetRefIndex().
TRef PndTrack::fRefToPndTrackCand private
Definition at line 85 of file PndTrack.h.
View newest version in sPHENIX GitHub at line 85 of file PndTrack.h
Referenced by GetPndTrackCandViaRef(), and SetTrackCandRef().
PndTrackCand PndTrack::fTrackCand private
Definition at line 84 of file PndTrack.h.
View newest version in sPHENIX GitHub at line 84 of file PndTrack.h
Referenced by GetTrackCand(), GetTrackCandPtr(), and SetTrackCand().
FairTrackParP PndTrack::fTrackParamFirst private
Definition at line 81 of file PndTrack.h.
View newest version in sPHENIX GitHub at line 81 of file PndTrack.h
Referenced by GetParamFirst(), and Print().
FairTrackParP PndTrack::fTrackParamLast private
Definition at line 82 of file PndTrack.h.
View newest version in sPHENIX GitHub at line 82 of file PndTrack.h
Referenced by GetParamLast(), and Print().
std::vector<NaiveTrackParameterization> PndTrack::mParameterizations
Definition at line 98 of file PndTrack.h.
View newest version in sPHENIX GitHub at line 98 of file PndTrack.h
Referenced by PndPidCorrelator::ConstructChargedCandidate(), PndRecoKalmanTask::Exec(), and PndRecoKalmanFit::Fit().
The documentation for this class was generated from the following files:
EicRoot/blob/master/pnddata/TrackData/PndTrack.h
EicRoot/blob/master/pnddata/TrackData/PndTrack.cxx