EIC Software: eicsmeardetectors/blob/master/tests/qaplots.cxx File Reference
qaplots.cxx File Reference
#include "qaplots.hh"
#include <eicsmear/functions.h>
#include <eicsmear/smear/functions.h>
#include "eicsmear/erhic/EventBase.h"
#include "eicsmear/erhic/EventPythia.h"
#include "eicsmear/erhic/Particle.h"
#include "eicsmear/smear/EventSmear.h"
#include "eicsmear/smear/EventS.h"
#include "eicsmear/smear/Smear.h"
#include "eicsmear/smear/ParticleMCS.h"
#include "eicsmear/smear/Detector.h"
#include "eicsmeardetectors.hh"
#include <TSystem.h>
#include <TDatabasePDG.h>
#include <TFile.h>
#include <TChain.h>
#include <TCanvas.h>
#include <TProfile.h>
#include <TLegend.h>
#include <TText.h>
#include <TStyle.h>
#include <string>
#include <iomanip>
#include <cctype>
#include <exception>
#include <vector>
#include <map>
Functions
static const TString getrootname (const qaparameters &qapars)
static void initializepidqabook (const qaparameters &qapars, map< int, pidqacollection > &qabook)
static void initializeeventqa (const qaparameters &qapars, eventqacollection &eventqa)
static void FillEventQA (eventqacollection &eventqa, const erhic::EventMC *const inEvent, const Smear::Event *const inEventS)
static void FillParticleQA (map< int, pidqacollection > &qabook, const Particle *const inParticle, const Smear::ParticleMCS *const inParticleS)
static void PlotQA (const qaparameters &qapars, eventqacollection &eventqa, map< int, pidqacollection > &qabook)
int main (int argc, char *argv[])
qaparameters ParseArguments (int argc, char *argv[])
Function Documentation
void FillEventQA (eventqacollection & eventqa, const erhic::EventMC *const inEvent, const Smear::Event *const inEventS) static
Definition at line 182 of file qaplots.cxx.
View newest version in sPHENIX GitHub at line 182 of file qaplots.cxx
References kdfinder::abs(), eventqacollection::delQ2_DA, eventqacollection::delQ2_JB, eventqacollection::delQ2_NM, eventqacollection::delx_DA, eventqacollection::delx_JB, eventqacollection::delx_NM, eventqacollection::dely_DA, eventqacollection::dely_JB, eventqacollection::dely_NM, erhic::EventDis::GetQ2(), erhic::EventDis::GetQ2DoubleAngle(), erhic::EventDis::GetQ2JacquetBlondel(), erhic::EventDis::GetX(), erhic::EventDis::GetXDoubleAngle(), erhic::EventDis::GetXJacquetBlondel(), erhic::EventDis::GetY(), erhic::EventDis::GetYDoubleAngle(), erhic::EventDis::GetYJacquetBlondel(), eventqacollection::missedQ2_DA, eventqacollection::missedQ2_JB, eventqacollection::missedQ2_NM, eventqacollection::missedx_DA, eventqacollection::missedx_JB, eventqacollection::missedx_NM, eventqacollection::missedy_DA, eventqacollection::missedy_JB, eventqacollection::missedy_NM, eventqacollection::Q2_DA, eventqacollection::Q2_JB, eventqacollection::Q2_NM, eventqacollection::x_DA, eventqacollection::x_JB, eventqacollection::x_NM, eventqacollection::y_DA, eventqacollection::y_JB, and eventqacollection::y_NM.
void FillParticleQA (map< int, pidqacollection > & qabook, const Particle *const inParticle, const Smear::ParticleMCS *const inParticleS) static
Definition at line 222 of file qaplots.cxx.
View newest version in sPHENIX GitHub at line 222 of file qaplots.cxx
References Smear::ParticleMCS::GetE(), erhic::ParticleMCbase::GetE(), Smear::ParticleMCS::GetEta(), erhic::ParticleMCbase::GetEta(), Smear::ParticleMCS::GetP(), erhic::ParticleMCbase::GetP(), erhic::ParticleMCbase::GetPdgCode(), Smear::ParticleMCS::GetPhi(), erhic::ParticleMCbase::GetPhi(), Smear::ParticleMCS::GetTheta(), erhic::ParticleMCbase::GetTheta(), Smear::ParticleMCS::IsESmeared(), Smear::ParticleMCS::IsPhiSmeared(), Smear::ParticleMCS::IsPSmeared(), Smear::ParticleMCS::IsThetaSmeared(), and pid.
const TString getrootname (const qaparameters & qapars) static
Definition at line 322 of file qaplots.cxx.
View newest version in sPHENIX GitHub at line 322 of file qaplots.cxx
References qaparameters::nevents, qaparameters::outpath, and qaparameters::txtfilename.
Referenced by main().
void initializeeventqa (const qaparameters & qapars, eventqacollection & eventqa) static
Definition at line 430 of file qaplots.cxx.
View newest version in sPHENIX GitHub at line 430 of file qaplots.cxx
References eventqacollection::delQ2_DA, eventqacollection::delQ2_JB, eventqacollection::delQ2_NM, eventqacollection::delx_DA, eventqacollection::delx_JB, eventqacollection::delx_NM, eventqacollection::dely_DA, eventqacollection::dely_JB, eventqacollection::dely_NM, qaparameters::detstring, Acts::UnitConstants::e, eventqacollection::Q2_DA, eventqacollection::Q2_JB, eventqacollection::Q2_NM, Acts::UnitConstants::s, eventqacollection::x_DA, eventqacollection::x_JB, eventqacollection::x_NM, xmax, xmin, eventqacollection::y_DA, eventqacollection::y_JB, eventqacollection::y_NM, ymax, and ymin.
Referenced by main().
void initializepidqabook (const qaparameters & qapars, map< int, pidqacollection > & qabook) static
Definition at line 354 of file qaplots.cxx.
View newest version in sPHENIX GitHub at line 354 of file qaplots.cxx
References kdfinder::abs(), qaparameters::detstring, CEMC_TOWER::emin, phibins, phimin, pid, qaparameters::pids, and Acts::UnitConstants::s.
int main (int argc, char * argv[])
Definition at line 56 of file qaplots.cxx.
View newest version in sPHENIX GitHub at line 56 of file qaplots.cxx
References qaparameters::beam_mom_nn, BuildByName(), BuildTree(), qaparameters::detstring, Smear::Detector::GetNDevices(), getrootname(), initializeeventqa(), qaparameters::nevents, qaparameters::outfilebase, qaparameters::outpath, ParseArguments(), qaparameters::pids, SmearTree(), and qaparameters::txtfilename.
qaparameters ParseArguments (int argc, char * argv[])
Definition at line 261 of file qaplots.cxx.
View newest version in sPHENIX GitHub at line 261 of file qaplots.cxx
References qaparameters::beam_mom_nn, c, qaparameters::detstring, Acts::UnitConstants::e, qaparameters::nevents, qaparameters::outfilebase, qaparameters::pids, and qaparameters::txtfilename.
void PlotQA (const qaparameters & qapars, eventqacollection & eventqa, map< int, pidqacollection > & qabook) static
Definition at line 529 of file qaplots.cxx.
View newest version in sPHENIX GitHub at line 529 of file qaplots.cxx
References qaparameters::detstring, eventqacollection::missedQ2_DA, eventqacollection::missedQ2_JB, eventqacollection::missedQ2_NM, eventqacollection::missedx_DA, eventqacollection::missedx_JB, eventqacollection::missedx_NM, eventqacollection::missedy_DA, eventqacollection::missedy_JB, eventqacollection::missedy_NM, qaparameters::outfilebase, pid, eventqacollection::Q2_DA, eventqacollection::Q2_JB, eventqacollection::Q2_NM, t, qaparameters::usedevents, eventqacollection::x_DA, eventqacollection::x_JB, eventqacollection::x_NM, eventqacollection::y_DA, eventqacollection::y_JB, and eventqacollection::y_NM.