EIC Software: eicpy.verify Namespace Reference
eicpy.verify Namespace Reference
Classes
class Histograms
class PythiaHistograms
class DjangohHistograms
Functions
def parse
def build
def histogram
def th1d
def th2d
def fill_histogram_from_tree
def event_type
Variables
dictionary HISTOGRAMS
tuple options parse()
list names
list root_files [ROOT.TFile(name, 'update') for name in names]
list histograms [HISTOGRAMS[event_type(file)](file) for file in root_files]
Function Documentation
def eicpy.verify.build (filename, outdir = '.', nevents = -1)
Build a ROOT tree from the named text file.
Returns the name of the resultant ROOT file.
Definition at line 27 of file verify.py.
View newest version in sPHENIX GitHub at line 27 of file verify.py
def eicpy.verify.event_type (file)
Return the event type for a ROOT file.
e.g. 'pythia', 'lepto'.
Definition at line 239 of file verify.py.
View newest version in sPHENIX GitHub at line 239 of file verify.py
def eicpy.verify.fill_histogram_from_tree (self, tree)
Fill a histogram from a tree.
Uses the histogram's 'select' and 'cut' attributes to determine
what is plotted.
Definition at line 64 of file verify.py.
View newest version in sPHENIX GitHub at line 64 of file verify.py
def eicpy.verify.histogram (typename, args, kwargs)
Return a histogram of the requested type.
args -- normal histogram constructor arguments
kwargs -- additional attributes to attach to the histogram
e.g. to create a TH1D with a 'cut' attribute:
histogram(ROOT.TH1D, 'myhist', '', 10, 0, 10, cut='x>10')
Definition at line 37 of file verify.py.
View newest version in sPHENIX GitHub at line 37 of file verify.py
Referenced by eicpy.verify.th1d(), and eicpy.verify.th2d().
def eicpy.verify.parse ()
Parse command line arguments and return in an argparse.Namespace.
Definition at line 14 of file verify.py.
View newest version in sPHENIX GitHub at line 14 of file verify.py
def eicpy.verify.th1d (args, kwargs)
Return a TH1D
Definition at line 56 of file verify.py.
View newest version in sPHENIX GitHub at line 56 of file verify.py
References eicpy.verify.histogram().
def eicpy.verify.th2d (args, kwargs)
Return a TH2D
Definition at line 60 of file verify.py.
View newest version in sPHENIX GitHub at line 60 of file verify.py
References eicpy.verify.histogram().
Referenced by eicpy.verify.PythiaHistograms.__init__(), and eicpy.verify.DjangohHistograms.__init__().
Variable Documentation
dictionary eicpy.verify.HISTOGRAMS
Initial value:
 {'pythia': PythiaHistograms,
               'lepto': Histograms,
               'milou': Histograms,
               'djangoh': DjangohHistograms,
               'pepsi': Histograms,
               'gmc_trans': Histograms}
Definition at line 232 of file verify.py.
View newest version in sPHENIX GitHub at line 232 of file verify.py
list eicpy.verify.histograms [HISTOGRAMS[event_type(file)](file) for file in root_files]
Definition at line 256 of file verify.py.
View newest version in sPHENIX GitHub at line 256 of file verify.py
Referenced by QAG4SimulationIntt.evaluate_clusters(), QAG4SimulationMvtx.evaluate_clusters(), QAG4SimulationMicromegas.evaluate_clusters(), QAG4SimulationTpc.evaluate_clusters(), and QAG4SimulationMicromegas.evaluate_hits().
list eicpy.verify.names
Initial value:
 [build(name, options.outdir, options.nevents)
              for name in options.file]
Definition at line 251 of file verify.py.
View newest version in sPHENIX GitHub at line 251 of file verify.py
Referenced by dfe::io_dsv_impl::NamedTupleDsvWriter< Delimiter, NamedTuple >.colum_names(), PHG4CylinderStripDetector.ConstructMe(), dfe::io_npy_impl.dtypes_description(), KFParticle_eventReconstruction.getCandidateDecay(), ActsExamples::Sequencer.listAlgorithmNames(), dfe::io_dsv_impl::NamedTupleDsvReader< Delimiter, NamedTuple >.parse_header(), ActsExamples::Sequencer.run(), dfe::NamedTupleRootWriter< NamedTuple >.setup_branches(), and dfe::NamedTupleRootReader< NamedTuple >.setup_branches().
tuple eicpy.verify.options parse()
Definition at line 249 of file verify.py.
View newest version in sPHENIX GitHub at line 249 of file verify.py
list eicpy.verify.root_files [ROOT.TFile(name, 'update') for name in names]
Definition at line 254 of file verify.py.
View newest version in sPHENIX GitHub at line 254 of file verify.py