EIC Software: FairDbTableRow Class Reference
FairDbTableRow Class Reference abstract
#include <EicRoot/blob/master/dbase/dbInterface/FairDbTableRow.h>
Public Member Functions
FairDbTableRow ()
FairDbTableRow (const FairDbTableRow &from)
virtual ~FairDbTableRow ()
virtual Bool_t CanL2Cache () const
virtual Int_t GetAggregateNo () const
FairDbResult * GetOwner () const
virtual FairDbTableRow * CreateTableRow () const =0
virtual UInt_t GetIndex (UInt_t defIndex) const
void SetOwner (FairDbResult *owner)
virtual void Fill (FairDbResultSet &rs, const FairDbValidityRec *vrec)=0
virtual void Store (FairDbOutRowStream &, const FairDbValidityRec *) const
Private Attributes
FairDbResult * fOwner
The owning FairDbResult, if any.
Detailed Description
Definition at line 14 of file FairDbTableRow.h.
View newest version in sPHENIX GitHub at line 14 of file FairDbTableRow.h
Constructor & Destructor Documentation
FairDbTableRow::FairDbTableRow ()
FairDbTableRow::FairDbTableRow (const FairDbTableRow & from)
Definition at line 12 of file FairDbTableRow.cxx.
View newest version in sPHENIX GitHub at line 12 of file FairDbTableRow.cxx
FairDbTableRow::~FairDbTableRow () virtual
Definition at line 18 of file FairDbTableRow.cxx.
View newest version in sPHENIX GitHub at line 18 of file FairDbTableRow.cxx
Member Function Documentation
virtual Bool_t FairDbTableRow::CanL2Cache () const inline virtual
Definition at line 25 of file FairDbTableRow.h.
View newest version in sPHENIX GitHub at line 25 of file FairDbTableRow.h
virtual FairDbTableRow* FairDbTableRow::CreateTableRow () const pure virtual
Implemented in FairDbLogEntry, FairDbValidityRec, and FairDbConfigSet.
Referenced by ClassImp().
virtual void FairDbTableRow::Fill (FairDbResultSet & rs, const FairDbValidityRec * vrec) pure virtual
Implemented in FairDbLogEntry, FairDbValidityRec, and FairDbConfigSet.
Referenced by ClassImp().
virtual Int_t FairDbTableRow::GetAggregateNo () const inline virtual
Reimplemented in FairDbLogEntry, FairDbValidityRec, and FairDbConfigSet.
Definition at line 26 of file FairDbTableRow.h.
View newest version in sPHENIX GitHub at line 26 of file FairDbTableRow.h
Referenced by FairDbResult::BuildLookUpTable().
virtual UInt_t FairDbTableRow::GetIndex (UInt_t defIndex) const inline virtual
Definition at line 29 of file FairDbTableRow.h.
View newest version in sPHENIX GitHub at line 29 of file FairDbTableRow.h
Referenced by FairDbResult::BuildLookUpTable().
FairDbResult* FairDbTableRow::GetOwner () const inline
Definition at line 27 of file FairDbTableRow.h.
View newest version in sPHENIX GitHub at line 27 of file FairDbTableRow.h
References fOwner.
Referenced by FairDbResult::BuildLookUpTable(), and FairDbResultAgg::GetValidityRec().
void FairDbTableRow::SetOwner (FairDbResult * owner) inline
Definition at line 32 of file FairDbTableRow.h.
View newest version in sPHENIX GitHub at line 32 of file FairDbTableRow.h
References fOwner.
Referenced by ClassImp().
virtual void FairDbTableRow::Store (FairDbOutRowStream & , const FairDbValidityRec *) const inline virtual
Reimplemented in FairDbLogEntry, FairDbValidityRec, and FairDbConfigSet.
Definition at line 37 of file FairDbTableRow.h.
View newest version in sPHENIX GitHub at line 37 of file FairDbTableRow.h
Referenced by FairDbSqlValPacket::AddRow().
Member Data Documentation
FairDbResult* FairDbTableRow::fOwner private
The owning FairDbResult, if any.
Definition at line 45 of file FairDbTableRow.h.
View newest version in sPHENIX GitHub at line 45 of file FairDbTableRow.h
Referenced by GetOwner(), and SetOwner().
The documentation for this class was generated from the following files:
EicRoot/blob/master/dbase/dbInterface/FairDbTableRow.h
EicRoot/blob/master/dbase/dbInterface/FairDbTableRow.cxx