EIC Software: fun4all_eicmacros/blob/master/common/G4_DRCALO.C File Reference
G4_DRCALO.C File Reference
#include <GlobalVariables.C>
#include <g4calo/RawTowerDigitizer.h>
#include <g4eiccalos/PHG4ForwardCalCellReco.h>
#include <drcalo/PHG4ForwardDualReadoutSubsystem.h>
#include <drcalo/RawTowerBuilderDRCALO.h>
#include <g4eval/CaloEvaluator.h>
#include <g4main/PHG4Reco.h>
#include <caloreco/RawClusterBuilderFwd.h>
#include <caloreco/RawClusterBuilderTemplate.h>
#include <caloreco/RawTowerCalibration.h>
#include <fun4all/Fun4AllServer.h>
Namespaces
namespace Enable
namespace G4DRCALO
namespace G4DRCALO::SETTING
Macros
#define MACRO_G4DR_C
Enumerations
enum G4DRCALO::enu_FHcal_clusterizer { G4DRCALO::kFHcalGraphClusterizer, G4DRCALO::kFHcalTemplateClusterizer }
Functions
void DRCALOInit ()
void DRCALOSetup (PHG4Reco *g4Reco)
void DRCALO_Cells (int verbosity=0)
void DRCALO_Towers ()
void DRCALO_Clusters ()
void DRCALO_Eval (const std::string &outputfile)
Variables
bool Enable::DRCALO = false
bool Enable::DRCALO_ABSORBER = false
bool Enable::DRCALO_CELL = false
bool Enable::DRCALO_TOWER = false
bool Enable::DRCALO_CLUSTER = false
bool Enable::DRCALO_EVAL = false
bool Enable::DRCALO_OVERLAPCHECK = false
int Enable::DRCALO_VERBOSITY = 0
double G4DRCALO::Gz0 = 400.
double G4DRCALO::Gdz = 100.
double G4DRCALO::outer_radius = 262.
enu_FHcal_clusterizer G4DRCALO::FHcal_clusterizer = kFHcalTemplateClusterizer
bool G4DRCALO::SETTING::Tungsten = false
bool G4DRCALO::SETTING::Quartz = false
bool G4DRCALO::SETTING::PMMA = false
bool G4DRCALO::SETTING::Tubes = false
bool G4DRCALO::SETTING::FwdConfig = false
bool G4DRCALO::SETTING::FwdSquare = false
Macro Definition Documentation
#define MACRO_G4DR_C
Definition at line 2 of file G4_DRCALO.C.
View newest version in sPHENIX GitHub at line 2 of file G4_DRCALO.C
Function Documentation
void DRCALO_Cells (int verbosity = 0)
Definition at line 144 of file G4_DRCALO.C.
View newest version in sPHENIX GitHub at line 144 of file G4_DRCALO.C
void DRCALO_Clusters ()
Definition at line 207 of file G4_DRCALO.C.
View newest version in sPHENIX GitHub at line 207 of file G4_DRCALO.C
Referenced by Extract_ECCE_gdml(), and Fun4All_G4_FullDetectorModular().
void DRCALO_Eval (const std::string & outputfile)
Definition at line 238 of file G4_DRCALO.C.
View newest version in sPHENIX GitHub at line 238 of file G4_DRCALO.C
void DRCALO_Towers ()
Definition at line 149 of file G4_DRCALO.C.
View newest version in sPHENIX GitHub at line 149 of file G4_DRCALO.C
References RawTowerDigitizer::Detector(), RawTowerCalibration::Detector(), RawTowerBuilderDRCALO::Detector(), Enable::DRCALO_VERBOSITY, G4DRCALO::SETTING::FwdConfig, G4DRCALO::SETTING::FwdSquare, RawTowerBuilderDRCALO::GeometryTableFile(), Fun4AllServer::instance(), RawTowerDigitizer::kNo_digitization, RawTowerCalibration::kSimple_linear_calibration, max, G4DRCALO::SETTING::PMMA, G4DRCALO::SETTING::Quartz, Fun4AllServer::registerSubsystem(), RawTowerCalibration::set_calib_algorithm(), RawTowerCalibration::set_calib_const_GeV_ADC(), RawTowerDigitizer::set_digi_algorithm(), RawTowerCalibration::set_pedstal_ADC(), RawTowerBuilderDRCALO::set_sim_tower_node_prefix(), G4DRCALO::SETTING::Tungsten, Enable::VERBOSITY, and Fun4AllBase::Verbosity().
Referenced by Extract_ECCE_gdml(), and Fun4All_G4_FullDetectorModular().
void DRCALOInit ()
Definition at line 65 of file G4_DRCALO.C.
View newest version in sPHENIX GitHub at line 65 of file G4_DRCALO.C
References Acts::UnitConstants::cm, G4DRCALO::SETTING::FwdConfig, G4DRCALO::SETTING::FwdSquare, G4DRCALO::Gdz, G4DRCALO::Gz0, max, BlackHoleGeometry::max_radius, BlackHoleGeometry::max_z, min, BlackHoleGeometry::min_z, G4DRCALO::outer_radius, G4DRCALO::SETTING::PMMA, G4DRCALO::SETTING::Quartz, and G4DRCALO::SETTING::Tungsten.
Referenced by G4Init().
void DRCALOSetup (PHG4Reco * g4Reco)
Use dedicated DRCALO module
Definition at line 84 of file G4_DRCALO.C.
View newest version in sPHENIX GitHub at line 84 of file G4_DRCALO.C
References Enable::ABSORBER, Enable::DRCALO_ABSORBER, Enable::DRCALO_OVERLAPCHECK, G4DRCALO::SETTING::FwdConfig, G4DRCALO::SETTING::FwdSquare, Fun4AllServer::instance(), Enable::OVERLAPCHECK, PHG4DetectorSubsystem::OverlapCheck(), G4DRCALO::SETTING::PMMA, G4DRCALO::SETTING::Quartz, PHG4Reco::registerSubsystem(), PHG4ForwardDualReadoutSubsystem::SetAbsorberActive(), PHG4ForwardDualReadoutSubsystem::SetActive(), PHG4ForwardDualReadoutSubsystem::SetTowerMappingFile(), PHG4DetectorSubsystem::SuperDetector(), G4DRCALO::SETTING::Tubes, and G4DRCALO::SETTING::Tungsten.
Referenced by G4Setup().