EIC Software: Smear::Acceptance::CustomCut Class Reference
Smear::Acceptance::CustomCut Class Reference
#include <eic-smear/blob/master/include/eicsmear/smear/Acceptance.h>
Public Member Functions
virtual ~CustomCut ()
CustomCut ()
CustomCut (const TString &, double min, double max)
virtual bool Contains (const erhic::VirtualParticle &) const
Protected Attributes
TFormula mFormula
int dim
KinType Kin1
KinType Kin2
double Min
double Max
Detailed Description
A (min, max) range in some variable evaluated as an arbitrary function of theta, phi, E and p (up to two supported). For example, if you want to set the acceptance in pT to [0.,100.] CustomCut("P*sin(theta)", 0., 100.);
Definition at line 46 of file Acceptance.h.
View newest version in sPHENIX GitHub at line 46 of file Acceptance.h
Constructor & Destructor Documentation
Smear::Acceptance::CustomCut::~CustomCut () virtual
Definition at line 93 of file Acceptance.cxx.
View newest version in sPHENIX GitHub at line 93 of file Acceptance.cxx
Smear::Acceptance::CustomCut::CustomCut ()
Definition at line 96 of file Acceptance.cxx.
View newest version in sPHENIX GitHub at line 96 of file Acceptance.cxx
Smear::Acceptance::CustomCut::CustomCut (const TString & formula, double min, double max)
Definition at line 116 of file Acceptance.cxx.
View newest version in sPHENIX GitHub at line 116 of file Acceptance.cxx
References dim, Smear::IsCoreType(), Kin1, Kin2, mFormula, Smear::ParseInputFunction(), and Acts::UnitConstants::s.
Member Function Documentation
bool Smear::Acceptance::CustomCut::Contains (const erhic::VirtualParticle & prt) const virtual
Definition at line 142 of file Acceptance.cxx.
View newest version in sPHENIX GitHub at line 142 of file Acceptance.cxx
References Acts::Test::dim, Smear::GetVariable(), x, y, and z.
Member Data Documentation
int Smear::Acceptance::CustomCut::dim protected
Definition at line 54 of file Acceptance.h.
View newest version in sPHENIX GitHub at line 54 of file Acceptance.h
Referenced by CustomCut().
KinType Smear::Acceptance::CustomCut::Kin1 protected
Definition at line 55 of file Acceptance.h.
View newest version in sPHENIX GitHub at line 55 of file Acceptance.h
Referenced by CustomCut().
KinType Smear::Acceptance::CustomCut::Kin2 protected
Definition at line 56 of file Acceptance.h.
View newest version in sPHENIX GitHub at line 56 of file Acceptance.h
Referenced by CustomCut().
double Smear::Acceptance::CustomCut::Max protected
Definition at line 58 of file Acceptance.h.
View newest version in sPHENIX GitHub at line 58 of file Acceptance.h
TFormula Smear::Acceptance::CustomCut::mFormula protected
Definition at line 53 of file Acceptance.h.
View newest version in sPHENIX GitHub at line 53 of file Acceptance.h
Referenced by CustomCut().
double Smear::Acceptance::CustomCut::Min protected
Definition at line 57 of file Acceptance.h.
View newest version in sPHENIX GitHub at line 57 of file Acceptance.h
The documentation for this class was generated from the following files:
eic-smear/blob/master/include/eicsmear/smear/Acceptance.h
eic-smear/blob/master/src/smear/Acceptance.cxx