EIC Software: FW::Generic::GenericDetectorElement Class Reference
FW::Generic::GenericDetectorElement Class Reference
#include <fun4all_acts/blob/master/Examples/Detectors/GenericDetector/include/ACTFW/GenericDetector/GenericDetectorElement.hpp>
Public Types
using ContextType = Acts::GeometryContext
Broadcast the ContextType.
Public Member Functions
GenericDetectorElement (const Identifier identifier, std::shared_ptr< const Acts::Transform3D > transform, std::shared_ptr< const Acts::PlanarBounds > pBounds, double thickness, std::shared_ptr< const Acts::ISurfaceMaterial > material=nullptr, std::shared_ptr< const Acts::DigitizationModule > digitzationModule=nullptr)
GenericDetectorElement (const Identifier identifier, std::shared_ptr< const Acts::Transform3D > transform, std::shared_ptr< const Acts::DiscBounds > dBounds, double thickness, std::shared_ptr< const Acts::ISurfaceMaterial > material=nullptr, std::shared_ptr< const Acts::DigitizationModule > digitzationModule=nullptr)
Identifier identifier () const overridefinal
Identifier.
const Acts::Transform3D & transform (const Acts::GeometryContext &gctx) const override
const Acts::Surface & surface () const finaloverride
Return surface associated with this identifier,.
void assignIdentifier (const Identifier &identifier)
Set the identifier after construction (sometimes needed)
double thickness () const finaloverride
The maximal thickness of the detector element wrt normal axis.
const std::shared_ptr< const
Acts::DigitizationModule > digitizationModule () const finaloverride
Retrieve the DigitizationModule.
Private Attributes
Identifier m_elementIdentifier
std::shared_ptr< const
Acts::Transform3D > m_elementTransform
the transform for positioning in 3D space
std::shared_ptr< const
Acts::Surface > m_elementSurface
the surface represented by it
double m_elementThickness
the element thickness
std::shared_ptr< const
Acts::PlanarBounds > m_elementPlanarBounds = nullptr
store either
std::shared_ptr< const
Acts::DiscBounds > m_elementDiscBounds = nullptr
std::shared_ptr< const
Acts::DigitizationModule > m_digitizationModule
The Digitization module.
Detailed Description
This is a lightweight type of detector element, it simply implements the base class.
Definition at line 34 of file GenericDetectorElement.hpp.
View newest version in sPHENIX GitHub at line 34 of file GenericDetectorElement.hpp
Member Typedef Documentation
using FW::Generic::GenericDetectorElement::ContextType = Acts::GeometryContext
Broadcast the ContextType.
Definition at line 37 of file GenericDetectorElement.hpp.
View newest version in sPHENIX GitHub at line 37 of file GenericDetectorElement.hpp
Constructor & Destructor Documentation
FW::Generic::GenericDetectorElement::GenericDetectorElement (const Identifier identifier, std::shared_ptr< const Acts::Transform3D > transform, std::shared_ptr< const Acts::PlanarBounds > pBounds, double thickness, std::shared_ptr< const Acts::ISurfaceMaterial > material = nullptr, std::shared_ptr< const Acts::DigitizationModule > digitzationModule = nullptr)
Constructor for single sided detector element
bound to a Plane Surface
Parameters
identifier is the module identifier
transform is the transform that element the layer in 3D frame
pBounds is the planar bounds for the planar detector element
thickness is the module thickness
material is the (optional) Surface material associated to it
Definition at line 16 of file GenericDetectorElement.cpp.
View newest version in sPHENIX GitHub at line 16 of file GenericDetectorElement.cpp
References Acts::Surface::assignSurfaceMaterial(), boost::const_pointer_cast(), and m_elementSurface.
FW::Generic::GenericDetectorElement::GenericDetectorElement (const Identifier identifier, std::shared_ptr< const Acts::Transform3D > transform, std::shared_ptr< const Acts::DiscBounds > dBounds, double thickness, std::shared_ptr< const Acts::ISurfaceMaterial > material = nullptr, std::shared_ptr< const Acts::DigitizationModule > digitzationModule = nullptr)
Constructor for single sided detector element
bound to a Disc Surface
Parameters
identifier is the module identifier
transform is the transform that element the layer in 3D frame
dBounds is the planar bounds for the disc like detector element
thickness is the module thickness
material is the (optional) Surface material associated to it
Definition at line 36 of file GenericDetectorElement.cpp.
View newest version in sPHENIX GitHub at line 36 of file GenericDetectorElement.cpp
References Acts::Surface::assignSurfaceMaterial(), boost::const_pointer_cast(), and m_elementSurface.
Member Function Documentation
void FW::Generic::GenericDetectorElement::assignIdentifier (const Identifier & identifier) inline
Set the identifier after construction (sometimes needed)
Definition at line 114 of file GenericDetectorElement.hpp.
View newest version in sPHENIX GitHub at line 114 of file GenericDetectorElement.hpp
References identifier().
const std::shared_ptr< const Acts::DigitizationModule > FW::Generic::GenericDetectorElement::digitizationModule () const inline final override virtual
Retrieve the DigitizationModule.
Implements Acts::IdentifiedDetectorElement.
Definition at line 138 of file GenericDetectorElement.hpp.
View newest version in sPHENIX GitHub at line 138 of file GenericDetectorElement.hpp
References m_digitizationModule.
Identifier FW::Generic::GenericDetectorElement::identifier () const inline final override virtual
Identifier.
Implements Acts::IdentifiedDetectorElement.
Definition at line 119 of file GenericDetectorElement.hpp.
View newest version in sPHENIX GitHub at line 119 of file GenericDetectorElement.hpp
References m_elementIdentifier.
Referenced by assignIdentifier(), and FW::Contextual::PayloadDetectorElement::transform().
const Acts::Surface & FW::Generic::GenericDetectorElement::surface () const inline final override virtual
Return surface associated with this identifier,.
Implements Acts::DetectorElementBase.
Definition at line 128 of file GenericDetectorElement.hpp.
View newest version in sPHENIX GitHub at line 128 of file GenericDetectorElement.hpp
References m_elementSurface.
double FW::Generic::GenericDetectorElement::thickness () const inline final override virtual
The maximal thickness of the detector element wrt normal axis.
Implements Acts::DetectorElementBase.
Definition at line 133 of file GenericDetectorElement.hpp.
View newest version in sPHENIX GitHub at line 133 of file GenericDetectorElement.hpp
References m_elementThickness.
const Acts::Transform3D & FW::Generic::GenericDetectorElement::transform (const Acts::GeometryContext & gctx) const inline override virtual
Return local to global transform associated with this identifier
Parameters
gctx The current geometry context object, e.g. alignment
Note
this is called from the surface().transform(gctx) in the PROXY mode
Implements Acts::DetectorElementBase.
Definition at line 123 of file GenericDetectorElement.hpp.
View newest version in sPHENIX GitHub at line 123 of file GenericDetectorElement.hpp
References m_elementTransform.
Member Data Documentation
std::shared_ptr<const Acts::DigitizationModule> FW::Generic::GenericDetectorElement::m_digitizationModule private
Initial value:
=
      nullptr
The Digitization module.
Definition at line 110 of file GenericDetectorElement.hpp.
View newest version in sPHENIX GitHub at line 110 of file GenericDetectorElement.hpp
Referenced by digitizationModule().
std::shared_ptr<const Acts::DiscBounds> FW::Generic::GenericDetectorElement::m_elementDiscBounds = nullptr private
Definition at line 108 of file GenericDetectorElement.hpp.
View newest version in sPHENIX GitHub at line 108 of file GenericDetectorElement.hpp
Identifier FW::Generic::GenericDetectorElement::m_elementIdentifier private
the element representation identifier
Definition at line 99 of file GenericDetectorElement.hpp.
View newest version in sPHENIX GitHub at line 99 of file GenericDetectorElement.hpp
Referenced by identifier().
std::shared_ptr<const Acts::PlanarBounds> FW::Generic::GenericDetectorElement::m_elementPlanarBounds = nullptr private
store either
Definition at line 107 of file GenericDetectorElement.hpp.
View newest version in sPHENIX GitHub at line 107 of file GenericDetectorElement.hpp
std::shared_ptr<const Acts::Surface> FW::Generic::GenericDetectorElement::m_elementSurface private
the surface represented by it
Definition at line 103 of file GenericDetectorElement.hpp.
View newest version in sPHENIX GitHub at line 103 of file GenericDetectorElement.hpp
Referenced by GenericDetectorElement(), and surface().
double FW::Generic::GenericDetectorElement::m_elementThickness private
the element thickness
Definition at line 105 of file GenericDetectorElement.hpp.
View newest version in sPHENIX GitHub at line 105 of file GenericDetectorElement.hpp
Referenced by thickness().
std::shared_ptr<const Acts::Transform3D> FW::Generic::GenericDetectorElement::m_elementTransform private
the transform for positioning in 3D space
Definition at line 101 of file GenericDetectorElement.hpp.
View newest version in sPHENIX GitHub at line 101 of file GenericDetectorElement.hpp
Referenced by transform().
The documentation for this class was generated from the following files:
fun4all_acts/blob/master/Examples/Detectors/GenericDetector/include/ACTFW/GenericDetector/GenericDetectorElement.hpp
fun4all_acts/blob/master/Examples/Detectors/GenericDetector/src/GenericDetectorElement.cpp