EIC Software: FairDbWriter< T > Class Template Reference
FairDbWriter< T > Class Template Reference
#include <EicRoot/blob/master/dbase/dbInterface/FairDbWriter.h>
Public Member Functions
FairDbWriter ()
FairDbWriter (const ValRange &vr, Int_t aggNo, FairDb::Task task, ValTimeStamp creationDate, const std::string &dbName, const std::string &logComment="", const std::string &tableName="")
FairDbWriter (const ValRange &vr, Int_t aggNo, FairDb::Task task=0, ValTimeStamp creationDate=ValTimeStamp(0, 0), UInt_t dbNo=0, const std::string &logComment="", const std::string &tableName="")
FairDbWriter (const FairDbValidityRec &vrec, const std::string &dbName, const std::string &logComment="")
FairDbWriter (const FairDbValidityRec &vrec, UInt_t dbNo=0, const std::string &logComment="")
virtual ~FairDbWriter ()
FairDbTableProxy & TableProxy () const
Bool_t IsOpen (Bool_t reportErrors=kTRUE) const
Open and ready to receive data.
Bool_t CanOutput (Bool_t reportErrors=kTRUE) const
Open and ready to receive/output data.
void SetDbNo (UInt_t dbNo)
void SetDbName (const string &dbName)
void SetLogComment (const std::string &reason)
void SetRequireGlobalSeqno (Int_t requireGlobal)
void SetOverlayCreationDate ()
void Abort ()
Bool_t Close (const char *fileSpec=0)
Bool_t Open (const ValRange &vr, Int_t aggNo, FairDb::Task task, ValTimeStamp creationDate, const string &dbName, const std::string &logComment="")
Bool_t Open (const ValRange &vr, Int_t aggNo, FairDb::Task task=0, ValTimeStamp creationDate=ValTimeStamp(), UInt_t dbNo=0, const std::string &logComment="")
Bool_t Open (const FairDbValidityRec &vrec, const string &dbName, const std::string &logComment="")
Bool_t Open (const FairDbValidityRec &vrec, UInt_t dbNo=0, const std::string &logComment="")
FairDbWriter< T > & operator<< (const T &row)
Private Member Functions
Bool_t NeedsLogEntry () const
Bool_t WritingToMaster () const
FairDbWriter (const FairDbWriter &)
FairDbWriter & operator= (const FairDbWriter &)
void CompleteOpen (UInt_t dbNo=0, const std::string &logComment="")
void Reset ()
Static Private Member Functions
static FairDbTableProxy & GetTableProxy ()
static FairDbTableProxy & GetTableProxy (const std::string &tableName)
Private Attributes
Int_t fAggregateNo
Aggregate noumber for set.
UInt_t fDbNo
Database number in cascade.
FairDbSqlValPacket * fPacket
The assembled record to be output. Never null.
Int_t fRequireGlobalSeqno
Controls SEQNO type (see FairDbCascader::AllocateSeqNo)
FairDbTableProxy * fTableProxy
Proxy to associated table.
std::string fTableName
Associated table name.
Bool_t fUseOverlayCreationDate
Use overlay creation date if true.
FairDbValidityRec * fValidRec
Validity record. May be =0 if closed.
FairDbLogEntry fLogEntry
Associated log entry (if any) for update.
Detailed Description
template<class T>
class FairDbWriter< T >
Definition at line 17 of file FairDbWriter.h.
View newest version in sPHENIX GitHub at line 17 of file FairDbWriter.h
Constructor & Destructor Documentation
template<class T> FairDbWriter< T >::FairDbWriter ()
template<class T> FairDbWriter< T >::FairDbWriter (const ValRange & vr, Int_t aggNo, FairDb::Task task, ValTimeStamp creationDate, const std::string & dbName, const std::string & logComment = "", const std::string & tableName = "")
template<class T> FairDbWriter< T >::FairDbWriter (const ValRange & vr, Int_t aggNo, FairDb::Task task = 0, ValTimeStamp creationDate = ValTimeStamp(0, 0), UInt_t dbNo = 0, const std::string & logComment = "", const std::string & tableName = "")
template<class T> FairDbWriter< T >::FairDbWriter (const FairDbValidityRec & vrec, const std::string & dbName, const std::string & logComment = "")
template<class T> FairDbWriter< T >::FairDbWriter (const FairDbValidityRec & vrec, UInt_t dbNo = 0, const std::string & logComment = "")
template<class T> virtual FairDbWriter< T >::~FairDbWriter () virtual
template<class T> FairDbWriter< T >::FairDbWriter (const FairDbWriter< T > &) private
Member Function Documentation
template<class T> void FairDbWriter< T >::Abort () inline
Definition at line 66 of file FairDbWriter.h.
View newest version in sPHENIX GitHub at line 66 of file FairDbWriter.h
References FairDbWriter< T >::Reset().
template<class T> Bool_t FairDbWriter< T >::CanOutput (Bool_t reportErrors = kTRUE) const
Open and ready to receive/output data.
template<class T> Bool_t FairDbWriter< T >::Close (const char * fileSpec = 0)
Referenced by FairDbConfigStream::Write().
template<class T> void FairDbWriter< T >::CompleteOpen (UInt_t dbNo = 0, const std::string & logComment = "") private
template<class T> static FairDbTableProxy& FairDbWriter< T >::GetTableProxy () static private
template<class T> static FairDbTableProxy& FairDbWriter< T >::GetTableProxy (const std::string & tableName) static private
template<class T> Bool_t FairDbWriter< T >::IsOpen (Bool_t reportErrors = kTRUE) const
Open and ready to receive data.
template<class T> Bool_t FairDbWriter< T >::NeedsLogEntry () const private
template<class T> Bool_t FairDbWriter< T >::Open (const ValRange & vr, Int_t aggNo, FairDb::Task task, ValTimeStamp creationDate, const string & dbName, const std::string & logComment = "")
template<class T> Bool_t FairDbWriter< T >::Open (const ValRange & vr, Int_t aggNo, FairDb::Task task = 0, ValTimeStamp creationDate = ValTimeStamp(), UInt_t dbNo = 0, const std::string & logComment = "")
template<class T> Bool_t FairDbWriter< T >::Open (const FairDbValidityRec & vrec, const string & dbName, const std::string & logComment = "")
template<class T> Bool_t FairDbWriter< T >::Open (const FairDbValidityRec & vrec, UInt_t dbNo = 0, const std::string & logComment = "")
template<class T> FairDbWriter<T>& FairDbWriter< T >::operator<< (const T & row)
template<class T> FairDbWriter& FairDbWriter< T >::operator= (const FairDbWriter< T > &) private
template<class T> void FairDbWriter< T >::Reset () private
Referenced by FairDbWriter< T >::Abort().
template<class T> void FairDbWriter< T >::SetDbName (const string & dbName)
template<class T> void FairDbWriter< T >::SetDbNo (UInt_t dbNo) inline
Definition at line 58 of file FairDbWriter.h.
View newest version in sPHENIX GitHub at line 58 of file FairDbWriter.h
References FairDbWriter< T >::fDbNo.
template<class T> void FairDbWriter< T >::SetLogComment (const std::string & reason)
template<class T> void FairDbWriter< T >::SetOverlayCreationDate () inline
Definition at line 63 of file FairDbWriter.h.
View newest version in sPHENIX GitHub at line 63 of file FairDbWriter.h
References FairDbWriter< T >::fUseOverlayCreationDate.
Referenced by FairDbConfigStream::Write().
template<class T> void FairDbWriter< T >::SetRequireGlobalSeqno (Int_t requireGlobal) inline
Definition at line 62 of file FairDbWriter.h.
View newest version in sPHENIX GitHub at line 62 of file FairDbWriter.h
References FairDbWriter< T >::fRequireGlobalSeqno.
Referenced by FairDbConfigStream::Write().
template<class T> FairDbTableProxy& FairDbWriter< T >::TableProxy () const
template<class T> Bool_t FairDbWriter< T >::WritingToMaster () const private
Member Data Documentation
template<class T> Int_t FairDbWriter< T >::fAggregateNo private
Aggregate noumber for set.
Definition at line 111 of file FairDbWriter.h.
View newest version in sPHENIX GitHub at line 111 of file FairDbWriter.h
template<class T> UInt_t FairDbWriter< T >::fDbNo private
Database number in cascade.
Definition at line 114 of file FairDbWriter.h.
View newest version in sPHENIX GitHub at line 114 of file FairDbWriter.h
Referenced by FairDbWriter< T >::SetDbNo().
template<class T> FairDbLogEntry FairDbWriter< T >::fLogEntry private
Associated log entry (if any) for update.
Definition at line 135 of file FairDbWriter.h.
View newest version in sPHENIX GitHub at line 135 of file FairDbWriter.h
template<class T> FairDbSqlValPacket* FairDbWriter< T >::fPacket private
The assembled record to be output. Never null.
Definition at line 117 of file FairDbWriter.h.
View newest version in sPHENIX GitHub at line 117 of file FairDbWriter.h
template<class T> Int_t FairDbWriter< T >::fRequireGlobalSeqno private
Controls SEQNO type (see FairDbCascader::AllocateSeqNo)
Definition at line 120 of file FairDbWriter.h.
View newest version in sPHENIX GitHub at line 120 of file FairDbWriter.h
Referenced by FairDbWriter< T >::SetRequireGlobalSeqno().
template<class T> std::string FairDbWriter< T >::fTableName private
Associated table name.
Definition at line 126 of file FairDbWriter.h.
View newest version in sPHENIX GitHub at line 126 of file FairDbWriter.h
template<class T> FairDbTableProxy* FairDbWriter< T >::fTableProxy private
Proxy to associated table.
Definition at line 123 of file FairDbWriter.h.
View newest version in sPHENIX GitHub at line 123 of file FairDbWriter.h
template<class T> Bool_t FairDbWriter< T >::fUseOverlayCreationDate private
Use overlay creation date if true.
Definition at line 129 of file FairDbWriter.h.
View newest version in sPHENIX GitHub at line 129 of file FairDbWriter.h
Referenced by FairDbWriter< T >::SetOverlayCreationDate().
template<class T> FairDbValidityRec* FairDbWriter< T >::fValidRec private
Validity record. May be =0 if closed.
Definition at line 132 of file FairDbWriter.h.
View newest version in sPHENIX GitHub at line 132 of file FairDbWriter.h
The documentation for this class was generated from the following file:
EicRoot/blob/master/dbase/dbInterface/FairDbWriter.h