EIC Software: FwdHoughNodeGroup Class Reference
FwdHoughNodeGroup Class Reference
#include <EicRoot/blob/master/eic/htree/FwdHoughNodeGroup.h>
Public Member Functions
FwdHoughNodeGroup (unsigned id)
~FwdHoughNodeGroup ()
void SetLocation (TrKalmanNodeLocation *location)
TrKalmanNodeLocation * GetLocation () const
t_hough_range Pack (const TVector3 &vtx)
t_hough_range PackFromTo (const EicTrackingDigiHit *hit, double nSigma, double spSmearing, const KalmanNodeWrapper *kfwrapper, double sign)
t_hough_range PackFrom (const EicTrackingDigiHit *hit, double nSigma, double spSmearing, const KalmanNodeWrapper *kfwrapper)
t_hough_range PackTo (const EicTrackingDigiHit *hit, double nSigma, double spSmearing, const KalmanNodeWrapper *kfwrapper)
void SetTemplate (const EicKfNodeTemplate *tmpl)
void SetMarsToTemplateMtx (const TGeoHMatrix *mtx)
const TGeoHMatrix * GetMarsToTemplateMtx () const
void SetCartesianFlag (bool useCartesian)
bool GetCartesianFlag () const
Public Member Functions inherited from HoughNodeGroup
HoughNodeGroup (unsigned id)
void ConfigureCoordinateDescriptors (unsigned cdim, const double min[], const double max[], const double gra[])
virtual ~HoughNodeGroup ()
int AddMember (const std::pair< void *, void * > &ptr, t_hough_range from, t_hough_range to)
void ResetMemberCounter ()
unsigned GetMemberCount () const
GroupMember * GetMember (unsigned mm)
void SetPhaseSpaceSmearing (unsigned smearing)
unsigned GetPhaseSpaceSmearing () const
unsigned GetGroupId () const
unsigned GetCoord (t_hough_range value, EicMagneticField::XYZ id)
const std::vector
< CoordinateDescriptor > & GetCoordDescr ()
t_hough_range OffsetThisValue (t_hough_range value, int offset)
bool Overlap (std::pair< t_hough_range, t_hough_range > r1, std::pair< t_hough_range, t_hough_range > r2)
double GetMin (unsigned iq) const
double GetGra (unsigned iq) const
Private Member Functions
t_hough_range PackCore (const TVector3 &vvGl, const EicKfNodeTemplate *kftmpl)
Private Attributes
bool mCylindricalCoordSystem
bool mUseCartesian
TrKalmanNodeLocation * mLocation
const TGeoHMatrix * mMarsToTemplate
const EicKfNodeTemplate * mTemplate
Additional Inherited Members
Protected Member Functions inherited from HoughNodeGroup
t_hough_range HoughPack (const int coord[])
Protected Attributes inherited from HoughNodeGroup
std::vector< CoordinateDescriptor > mCoordDescr
Detailed Description
Definition at line 14 of file FwdHoughNodeGroup.h.
View newest version in sPHENIX GitHub at line 14 of file FwdHoughNodeGroup.h
Constructor & Destructor Documentation
FwdHoughNodeGroup::FwdHoughNodeGroup (unsigned id) inline
Definition at line 17 of file FwdHoughNodeGroup.h.
View newest version in sPHENIX GitHub at line 17 of file FwdHoughNodeGroup.h
FwdHoughNodeGroup::~FwdHoughNodeGroup () inline
Definition at line 19 of file FwdHoughNodeGroup.h.
View newest version in sPHENIX GitHub at line 19 of file FwdHoughNodeGroup.h
Member Function Documentation
bool FwdHoughNodeGroup::GetCartesianFlag () const inline
Definition at line 64 of file FwdHoughNodeGroup.h.
View newest version in sPHENIX GitHub at line 64 of file FwdHoughNodeGroup.h
References mUseCartesian.
TrKalmanNodeLocation* FwdHoughNodeGroup::GetLocation () const inline
Definition at line 22 of file FwdHoughNodeGroup.h.
View newest version in sPHENIX GitHub at line 22 of file FwdHoughNodeGroup.h
References mLocation.
Referenced by FwdHoughTree::MappingCall().
const TGeoHMatrix* FwdHoughNodeGroup::GetMarsToTemplateMtx () const inline
Definition at line 61 of file FwdHoughNodeGroup.h.
View newest version in sPHENIX GitHub at line 61 of file FwdHoughNodeGroup.h
References mMarsToTemplate.
t_hough_range FwdHoughNodeGroup::Pack (const TVector3 & vtx) inline
Definition at line 24 of file FwdHoughNodeGroup.h.
View newest version in sPHENIX GitHub at line 24 of file FwdHoughNodeGroup.h
References mTemplate, and PackCore().
Referenced by FwdHoughTree::MappingCall().
t_hough_range FwdHoughNodeGroup::PackCore (const TVector3 & vvGl, const EicKfNodeTemplate * kftmpl) inline private
Definition at line 80 of file FwdHoughNodeGroup.h.
View newest version in sPHENIX GitHub at line 80 of file FwdHoughNodeGroup.h
References EicKfNodeTemplate::CartesianToCylindrical(), HoughNodeGroup::GetGra(), EicKfNodeTemplate::GetMdim(), HoughNodeGroup::GetMin(), HoughNodeGroup::HoughPack(), MasterToLocal(), mMarsToTemplate, and mUseCartesian.
Referenced by Pack(), and PackFromTo().
t_hough_range FwdHoughNodeGroup::PackFrom (const EicTrackingDigiHit * hit, double nSigma, double spSmearing, const KalmanNodeWrapper * kfwrapper) inline
Definition at line 45 of file FwdHoughNodeGroup.h.
View newest version in sPHENIX GitHub at line 45 of file FwdHoughNodeGroup.h
References PackFromTo().
Referenced by FwdTrackFinder::Exec().
t_hough_range FwdHoughNodeGroup::PackFromTo (const EicTrackingDigiHit * hit, double nSigma, double spSmearing, const KalmanNodeWrapper * kfwrapper, double sign) inline
Definition at line 27 of file FwdHoughNodeGroup.h.
View newest version in sPHENIX GitHub at line 27 of file FwdHoughNodeGroup.h
References EicTrackingDigiHit::_GetCoord(), KalmanNodeWrapper::GetKfNodeTemplate(), EicTrackingDigiHit::GetMdim(), KalmanNodeWrapper::GetNodeToMasterMtx(), EicKfNodeTemplate::GetSigma(), EicKfNodeTemplate::GetSmearingValue(), LocalToMaster(), PackCore(), and EicKfNodeTemplate::TemplateToThreeDee().
Referenced by PackFrom(), and PackTo().
t_hough_range FwdHoughNodeGroup::PackTo (const EicTrackingDigiHit * hit, double nSigma, double spSmearing, const KalmanNodeWrapper * kfwrapper) inline
Definition at line 49 of file FwdHoughNodeGroup.h.
View newest version in sPHENIX GitHub at line 49 of file FwdHoughNodeGroup.h
References PackFromTo().
Referenced by FwdTrackFinder::Exec().
void FwdHoughNodeGroup::SetCartesianFlag (bool useCartesian) inline
Definition at line 63 of file FwdHoughNodeGroup.h.
View newest version in sPHENIX GitHub at line 63 of file FwdHoughNodeGroup.h
References mUseCartesian.
Referenced by FwdHoughTree::AddNodeGroup().
void FwdHoughNodeGroup::SetLocation (TrKalmanNodeLocation * location) inline
Definition at line 21 of file FwdHoughNodeGroup.h.
View newest version in sPHENIX GitHub at line 21 of file FwdHoughNodeGroup.h
References mLocation.
Referenced by FwdHoughTree::AddNodeGroup().
void FwdHoughNodeGroup::SetMarsToTemplateMtx (const TGeoHMatrix * mtx) inline
Definition at line 60 of file FwdHoughNodeGroup.h.
View newest version in sPHENIX GitHub at line 60 of file FwdHoughNodeGroup.h
References mMarsToTemplate.
Referenced by FwdHoughTree::AddNodeGroup().
void FwdHoughNodeGroup::SetTemplate (const EicKfNodeTemplate * tmpl) inline
Definition at line 58 of file FwdHoughNodeGroup.h.
View newest version in sPHENIX GitHub at line 58 of file FwdHoughNodeGroup.h
References mTemplate.
Referenced by FwdHoughTree::AddNodeGroup().
Member Data Documentation
bool FwdHoughNodeGroup::mCylindricalCoordSystem private
Definition at line 67 of file FwdHoughNodeGroup.h.
View newest version in sPHENIX GitHub at line 67 of file FwdHoughNodeGroup.h
TrKalmanNodeLocation* FwdHoughNodeGroup::mLocation private
Definition at line 71 of file FwdHoughNodeGroup.h.
View newest version in sPHENIX GitHub at line 71 of file FwdHoughNodeGroup.h
Referenced by GetLocation(), and SetLocation().
const TGeoHMatrix* FwdHoughNodeGroup::mMarsToTemplate private
Definition at line 74 of file FwdHoughNodeGroup.h.
View newest version in sPHENIX GitHub at line 74 of file FwdHoughNodeGroup.h
Referenced by GetMarsToTemplateMtx(), PackCore(), and SetMarsToTemplateMtx().
const EicKfNodeTemplate* FwdHoughNodeGroup::mTemplate private
Definition at line 76 of file FwdHoughNodeGroup.h.
View newest version in sPHENIX GitHub at line 76 of file FwdHoughNodeGroup.h
Referenced by Pack(), and SetTemplate().
bool FwdHoughNodeGroup::mUseCartesian private
Definition at line 69 of file FwdHoughNodeGroup.h.
View newest version in sPHENIX GitHub at line 69 of file FwdHoughNodeGroup.h
Referenced by GetCartesianFlag(), PackCore(), and SetCartesianFlag().
The documentation for this class was generated from the following file:
EicRoot/blob/master/eic/htree/FwdHoughNodeGroup.h