EIC Software: Acts::GaussianTrackDensity Class Reference
Acts::GaussianTrackDensity Class Reference
Class to model tracks as 2D Gaussian-shaped density functions based on their d0 and z0 perigee parameters (mean value) and covariance matrices (determining the width of the function)
#include <fun4all_acts/blob/master/Core/include/Acts/Vertexing/GaussianTrackDensity.hpp>
Classes
struct Config
The Config struct.
struct State
The State struct.
Public Member Functions
GaussianTrackDensity ()=default
Default constructor.
GaussianTrackDensity (const Config &cfg)
Constructor with config.
double globalMaximum (const std::vector< Acts::BoundParameters > &trackList, State &state) const
Calculates the global maximum.
std::pair< double, double > globalMaximumWithWidth (const std::vector< Acts::BoundParameters > &trackList, State &state) const
Calculates the global maximum with width.
Private Member Functions
void addTracks (const std::vector< Acts::BoundParameters > &trackList, State &state) const
Adds tracks based on a significance cut.
Private Attributes
Config m_cfg
The configuration.
Detailed Description
Class to model tracks as 2D Gaussian-shaped density functions based on their d0 and z0 perigee parameters (mean value) and covariance matrices (determining the width of the function)
Definition at line 20 of file GaussianTrackDensity.hpp.
View newest version in sPHENIX GitHub at line 20 of file GaussianTrackDensity.hpp
Constructor & Destructor Documentation
Acts::GaussianTrackDensity::GaussianTrackDensity () default
Default constructor.
Acts::GaussianTrackDensity::GaussianTrackDensity (const Config & cfg) inline
Constructor with config.
Definition at line 46 of file GaussianTrackDensity.hpp.
View newest version in sPHENIX GitHub at line 46 of file GaussianTrackDensity.hpp
Member Function Documentation
void Acts::GaussianTrackDensity::addTracks (const std::vector< Acts::BoundParameters > & trackList, State & state) const private
Adds tracks based on a significance cut.
Parameters
trackList The list of tracks
state The GaussianTrackDensity state
Definition at line 23 of file GaussianTrackDensity.cpp.
View newest version in sPHENIX GitHub at line 23 of file GaussianTrackDensity.cpp
References Acts::TrackDensity::addTrack(), Acts::GaussianTrackDensity::State::trackDensity, and Acts::GaussianTrackDensity::State::trackDensityState.
Referenced by globalMaximum().
double Acts::GaussianTrackDensity::globalMaximum (const std::vector< Acts::BoundParameters > & trackList, State & state) const
Calculates the global maximum.
Parameters
trackList The list of tracks
state The GaussianTrackDensity state
Returns
The z position of the maximum
Definition at line 11 of file GaussianTrackDensity.cpp.
View newest version in sPHENIX GitHub at line 11 of file GaussianTrackDensity.cpp
References addTracks(), Acts::TrackDensity::globalMaximum(), Acts::GaussianTrackDensity::State::trackDensity, and Acts::GaussianTrackDensity::State::trackDensityState.
std::pair< double, double > Acts::GaussianTrackDensity::globalMaximumWithWidth (const std::vector< Acts::BoundParameters > & trackList, State & state) const
Calculates the global maximum with width.
Parameters
trackList The list of tracks
state The GaussianTrackDensity state
Returns
The z position of the maximum and its width
Definition at line 17 of file GaussianTrackDensity.cpp.
View newest version in sPHENIX GitHub at line 17 of file GaussianTrackDensity.cpp
References Acts::TrackDensity::globalMaximumWithWidth(), Acts::GaussianTrackDensity::State::trackDensity, and Acts::GaussianTrackDensity::State::trackDensityState.
Member Data Documentation
Config Acts::GaussianTrackDensity::m_cfg private
The configuration.
Definition at line 68 of file GaussianTrackDensity.hpp.
View newest version in sPHENIX GitHub at line 68 of file GaussianTrackDensity.hpp
The documentation for this class was generated from the following files:
fun4all_acts/blob/master/Core/include/Acts/Vertexing/GaussianTrackDensity.hpp
fun4all_acts/blob/master/Core/src/Vertexing/GaussianTrackDensity.cpp