EIC Software: fun4all_eicmacros/blob/master/detectors/AllSilicon/Development/Fun4All_G4_FastMom_GEM.C File Reference
Fun4All_G4_FastMom_GEM.C File Reference
#include <phgenfit/Track.h>
#include <fun4all/Fun4AllDstInputManager.h>
#include <fun4all/Fun4AllDstOutputManager.h>
#include <fun4all/Fun4AllDummyInputManager.h>
#include <fun4all/Fun4AllInputManager.h>
#include <fun4all/Fun4AllNoSyncDstInputManager.h>
#include <fun4all/Fun4AllOutputManager.h>
#include <fun4all/Fun4AllServer.h>
#include <fun4all/SubsysReco.h>
#include <g4detectors/PHG4DetectorSubsystem.h>
#include <g4detectors/PHG4CylinderSubsystem.h>
#include <phpythia8/PHPythia8.h>
#include <g4histos/G4HitNtuple.h>
#include <g4lblvtx/AllSiliconTrackerSubsystem.h>
#include <g4main/HepMCNodeReader.h>
#include <g4main/PHG4ParticleGenerator.h>
#include <g4main/PHG4ParticleGeneratorBase.h>
#include <g4main/PHG4ParticleGun.h>
#include <g4main/PHG4Reco.h>
#include <g4main/PHG4SimpleEventGenerator.h>
#include <g4main/PHG4TruthSubsystem.h>
#include <g4trackfastsim/PHG4TrackFastSim.h>
#include <g4trackfastsim/PHG4TrackFastSimEval.h>
#include <phool/recoConsts.h>
#include <G4_Jets.C>
#include <G4_Bbc.C>
#include <G4_Global.C>
#include <G4_Pipe_EIC.C>
#include <G4_AllSi.C>
#include <G4_GEM_EIC.C>
#include <g4lblvtx/G4LBLVtxSubsystem.h>
#include <g4lblvtx/SimpleNtuple.h>
#include <g4lblvtx/TrackFastSimEval.h>
#include <myjetanalysis/MyJetAnalysis_AllSi.h>
Functions
void Fun4All_G4_FastMom_GEM (int nEvents=-1, const char *outputFile="out_allSi", const char *genpar="pi-", const int det_ver=2, const double pixel_size=10.)
Function Documentation
void Fun4All_G4_FastMom_GEM (int nEvents = -1, const char * outputFile = "out_allSi", const char * genpar = "pi-", const int det_ver = 2, const double pixel_size = 10.)
Definition at line 45 of file Fun4All_G4_FastMom_GEM.C.
View newest version in sPHENIX GitHub at line 45 of file Fun4All_G4_FastMom_GEM.C
References add_AllSi_hits(), add_AllSi_to_kalman(), PHG4TrackFastSim::add_cylinder_state(), PHG4SimpleEventGenerator::add_particles(), PHG4TrackFastSim::add_phg4hits(), PHG4TrackFastSim::add_zplane_state(), SimpleNtuple::AddNode(), TrackFastSimEval::AddProjection(), Bbc_Reco(), PHG4DetectorSubsystem::BlackHole(), G4TRACKING::DISPLACED_VERTEX, Acts::UnitConstants::e, EGEM_Init(), EGEMSetup(), PHG4TrackFastSim::enable_vertexing(), Fun4AllServer::End(), FGEM_Init(), FGEMSetup(), Global_Reco(), in, Fun4AllServer::instance(), Jet_Eval(), Jet_Reco(), PHFieldConfig::kField2D, PHFieldConfig::kFieldBeast, load_AllSi_geom(), Fun4AllServer::registerInputManager(), Fun4AllServer::registerOutputManager(), Fun4AllServer::registerSubsystem(), PHG4Reco::registerSubsystem(), Fun4AllServer::run(), PHG4CylinderSubsystem::set_color(), PHPythia8::set_config_file(), PHG4DetectorSubsystem::set_double_param(), PHG4ParticleGenerator::set_eta_range(), PHG4SimpleEventGenerator::set_eta_range(), PHG4Reco::set_field(), PHG4Reco::set_field_map(), PHG4Reco::set_field_rescale(), TrackFastSimEval::set_filename(), PHG4ParticleGeneratorBase::set_mom(), PHG4ParticleGenerator::set_mom_range(), PHG4ParticleGeneratorBase::set_name(), PHG4SimpleEventGenerator::set_p_range(), PHG4ParticleGenerator::set_phi_range(), PHG4SimpleEventGenerator::set_phi_range(), PHG4DetectorSubsystem::set_string_param(), PHG4TrackFastSim::set_sub_top_node_name(), PHG4TrackFastSim::set_trackmap_out_name(), PHG4TrackFastSim::set_use_vertex_in_fitting(), PHG4SimpleEventGenerator::set_vertex_distribution_function(), PHG4SimpleEventGenerator::set_vertex_distribution_mean(), PHG4SimpleEventGenerator::set_vertex_distribution_width(), PHG4TrackFastSim::set_vertex_min_ndf(), PHG4SimpleEventGenerator::set_vertex_size_function(), PHG4SimpleEventGenerator::set_vertex_size_parameters(), PHG4TrackFastSim::set_vertex_xy_resolution(), PHG4TrackFastSim::set_vertex_z_resolution(), PHG4ParticleGeneratorBase::set_vtx(), PHG4ParticleGenerator::set_z_range(), PHG4DetectorSubsystem::SetActive(), PHG4DetectorSubsystem::SuperDetector(), PHG4SimpleEventGenerator::Uniform, Fun4AllBase::Verbosity(), and PHG4TrackFastSim::Vertical_Plane.