EIC Software: EicRoot/blob/master/cbmbase/CbmDrawHist.h File Reference
CbmDrawHist.h File Reference
Helper functions for drawing 1D and 2D histograms and graphs.
#include "TH1.h"
#include "TH1D.h"
#include "TH2.h"
#include "TPad.h"
#include "TLegend.h"
#include "TGraph.h"
#include "TGraph2D.h"
#include <string>
#include <vector>
Classes
class CbmDrawingOptions
Default options for drawing.
Enumerations
enum HistScale { kLog = 0, kLinear = 1 }
Define linear or logarithmic scale for drawing.
Functions
void SetDefaultDrawStyle ()
void DrawH1 (TH1 *hist, HistScale logx=kLinear, HistScale logy=kLinear, const string &drawOpt="", Int_t color=CbmDrawingOptions::Color(0), Int_t lineWidth=CbmDrawingOptions::LineWidth(), Int_t lineStyle=CbmDrawingOptions::LineStyle(0), Int_t markerSize=CbmDrawingOptions::MarkerSize(), Int_t markerStyle=CbmDrawingOptions::MarkerStyle(0))
void DrawH2 (TH2 *hist, HistScale logx=kLinear, HistScale logy=kLinear, HistScale logz=kLinear, const string &drawOpt="COLZ")
void DrawH1 (const vector< TH1 * > &histos, const vector< string > &histLabels, HistScale logx=kLinear, HistScale logy=kLinear, Bool_t drawLegend=true, Double_t x1=0.25, Double_t y1=0.99, Double_t x2=0.55, Double_t y2=0.75, const string &drawOpt="")
void DrawGraph (TGraph *graph, HistScale logx=kLinear, HistScale logy=kLinear, const string &drawOpt="AC", Int_t color=CbmDrawingOptions::Color(0), Int_t lineWidth=CbmDrawingOptions::LineWidth(), Int_t lineStyle=CbmDrawingOptions::LineStyle(0), Int_t markerSize=CbmDrawingOptions::MarkerSize(), Int_t markerStyle=CbmDrawingOptions::MarkerStyle(0))
void DrawGraph (const vector< TGraph * > &graphs, const vector< string > &graphLabels, HistScale logx=kLinear, HistScale logy=kLinear, Bool_t drawLegend=true, Double_t x1=0.25, Double_t y1=0.99, Double_t x2=0.55, Double_t y2=0.75)
void DrawGraph2D (TGraph2D *graph, HistScale logx=kLinear, HistScale logy=kLinear, HistScale logz=kLinear, const string &drawOpt="colz")
Detailed Description
Helper functions for drawing 1D and 2D histograms and graphs.
Author
Andrey Lebedev andre.nosp@m.y.le.nosp@m.bedev.nosp@m.@gsi.nosp@m..de
Date
2008
Definition in file CbmDrawHist.h.
Enumeration Type Documentation
enum HistScale
Define linear or logarithmic scale for drawing.
Enumerator:
kLog
kLinear
Linear scale.
Definition at line 67 of file CbmDrawHist.h.
View newest version in sPHENIX GitHub at line 67 of file CbmDrawHist.h
Function Documentation
void DrawGraph (TGraph * graph, HistScale logx = kLinear, HistScale logy = kLinear, const string & drawOpt = "AC", Int_t color = CbmDrawingOptions::Color(0), Int_t lineWidth = CbmDrawingOptions::LineWidth(), Int_t lineStyle = CbmDrawingOptions::LineStyle(0), Int_t markerSize = CbmDrawingOptions::MarkerSize(), Int_t markerStyle = CbmDrawingOptions::MarkerStyle(0))
Referenced by CbmRichGeoTest::DrawSummaryPlotsTemp().
void DrawGraph (const vector< TGraph * > & graphs, const vector< string > & graphLabels, HistScale logx = kLinear, HistScale logy = kLinear, Bool_t drawLegend = true, Double_t x1 = 0.25, Double_t y1 = 0.99, Double_t x2 = 0.55, Double_t y2 = 0.75)
void DrawGraph2D (TGraph2D * graph, HistScale logx = kLinear, HistScale logy = kLinear, HistScale logz = kLinear, const string & drawOpt = "colz")
void DrawH1 (TH1 * hist, HistScale logx = kLinear, HistScale logy = kLinear, const string & drawOpt = "", Int_t color = CbmDrawingOptions::Color(0), Int_t lineWidth = CbmDrawingOptions::LineWidth(), Int_t lineStyle = CbmDrawingOptions::LineStyle(0), Int_t markerSize = CbmDrawingOptions::MarkerSize(), Int_t markerStyle = CbmDrawingOptions::MarkerStyle(0))
Referenced by CbmRichTrainAnnSelect::Draw(), CbmRichTrainAnnElectrons::Draw(), CbmRichGeoTest::DrawH1andFit(), CbmRichGeoTest::DrawH2MeanRms(), CbmRichUrqmdTest::DrawHist(), CbmRichGeoTest::DrawHist(), and CbmRichGeoTest::FitH1OneOverX().
void DrawH1 (const vector< TH1 * > & histos, const vector< string > & histLabels, HistScale logx = kLinear, HistScale logy = kLinear, Bool_t drawLegend = true, Double_t x1 = 0.25, Double_t y1 = 0.99, Double_t x2 = 0.55, Double_t y2 = 0.75, const string & drawOpt = "")
void DrawH2 (TH2 * hist, HistScale logx = kLinear, HistScale logy = kLinear, HistScale logz = kLinear, const string & drawOpt = "COLZ")
Referenced by CbmRichTrainAnnElectrons::Draw(), CbmRichGeoTest::DrawH3(), CbmRichUrqmdTest::DrawHist(), CbmRichGeoTest::DrawHist(), and CbmRichEventDisplay::DrawOneEvent().
void SetDefaultDrawStyle ()
Referenced by CbmRichEventDisplay::CbmRichEventDisplay(), CbmRichTrainAnnElectrons::Draw(), CbmRichUrqmdTest::DrawHist(), CbmRichGeoTest::DrawHist(), and CbmRichEventDisplay::Exec().