EIC Software: PHG4Detector Class Reference
PHG4Detector Class Reference abstract
base class for phenix detector creation
#include <fun4all_coresoftware/blob/master/simulation/g4simulation/g4main/PHG4Detector.h>
Inherited by AllSi_Al_support_Detector, AllSi_Al_support_Detector, AllSiliconTrackerDetector, AllSiliconTrackerDetector, BeamLineMagnetDetector, BeastMagnetDetector, EicFRichDetector, EicFRichDetector, EICG4B0Detector, EICG4B0ECALDetector, EICG4BwdDetector, EICG4dRICHDetector, EICG4LumiDetector, EICG4RPDetector, EICG4ZDCDetector, EicRootDetector, EicToyModelDetector, G4EicDircDetector, G4Example01Detector, G4Example02Detector, G4Example03Detector, G4JLeicBeamLineMagnetDetector, G4JLeicBeamLineMagnetDetector, G4JLeicDIRCDetector, G4JLeicDIRCDetector, G4JLeicVTXDetector, G4JLeicVTXDetector, G4LBLVtxDetector, G4LBLVtxDetector, G4LmonDetector, PHG4BackwardHcalDetector, PHG4BarrelEcalDetector, PHG4BbcDetector, PHG4BeamlineMagnetDetector, PHG4BlockDetector, PHG4CEmcTestBeamDetector, PHG4ConeDetector, PHG4CrystalCalorimeterDetector, PHG4CylinderDetector, PHG4CylinderStripDetector, PHG4ECAPToFDetector, PHG4EICMvtxDetector, PHG4EnvelopeDetector, PHG4EPDDetector, PHG4FCalDetector, PHG4ForwardDualReadoutDetector, PHG4ForwardEcalDetector, PHG4ForwardHcalDetector, PHG4FPbScDetector, PHG4GDMLDetector, PHG4HcalDetector, PHG4HybridHomogeneousCalorimeterDetector, PHG4InnerHcalDetector, PHG4InttDetector, PHG4LFHcalDetector, PHG4MicromegasDetector, PHG4mRICHDetector, PHG4MvtxDetector, PHG4OuterHcalDetector, PHG4PSTOFDetector, PHG4RICHDetector, PHG4SectorDetector, PHG4SpacalDetector, PHG4TpcDetector, PHG4TpcEndCapDetector, PHG4TRDDetector, PHG4TTLDetector, and PHG4ZDCDetector.
Public Member Functions
PHG4Detector ()=delete
constructor
PHG4Detector (PHG4Subsystem *subsys, PHCompositeNode *Node, const std::string &nam)
virtual ~PHG4Detector (void)
destructor
virtual void Construct (G4LogicalVolume *world) final
construct method
virtual void ConstructMe (G4LogicalVolume *mothervolume)=0
virtual void PostConstruction ()
Optional PostConstruction call after all geometry is constructed.
virtual void Verbosity (const int v)
virtual int Verbosity () const
virtual G4UserSteppingAction * GetSteppingAction ()
virtual std::string GetName () const
virtual void OverlapCheck (const bool chk)
virtual bool OverlapCheck () const
virtual void Print (const std::string &="ALL") const
virtual int DisplayVolume (G4VSolid *volume, G4LogicalVolume *logvol, G4RotationMatrix *rotm=nullptr)
virtual int DisplayVolume (G4LogicalVolume *checksolid, G4LogicalVolume *logvol, G4RotationMatrix *rotm=nullptr)
virtual PHCompositeNode * topNode ()
virtual PHG4Subsystem * GetMySubsystem ()
Static Public Member Functions
static G4Material * GetDetectorMaterial (const std::string &name, const bool quit=true)
static G4Element * GetDetectorElement (const std::string &name, const bool quit=true)
Private Attributes
PHCompositeNode * m_topNode = nullptr
PHG4Subsystem * m_MySubsystem = nullptr
int m_Verbosity = 0
bool m_OverlapCheck = false
int m_ColorIndex = 0
std::string m_Name
Detailed Description
base class for phenix detector creation
derived classes must implement construct method, which takes the "world" logical volume as argument
Definition at line 21 of file PHG4Detector.h.
View newest version in sPHENIX GitHub at line 21 of file PHG4Detector.h
Constructor & Destructor Documentation
PHG4Detector::PHG4Detector () delete
constructor
PHG4Detector::PHG4Detector (PHG4Subsystem * subsys, PHCompositeNode * Node, const std::string & nam) explicit
Definition at line 18 of file PHG4Detector.cc.
View newest version in sPHENIX GitHub at line 18 of file PHG4Detector.cc
virtual PHG4Detector::~PHG4Detector (void) inline virtual
destructor
Definition at line 31 of file PHG4Detector.h.
View newest version in sPHENIX GitHub at line 31 of file PHG4Detector.h
Member Function Documentation
void PHG4Detector::Construct (G4LogicalVolume * world) final virtual
construct method
construct all logical and physical volumes relevant for given detector and place them inside the world logical volume
Definition at line 25 of file PHG4Detector.cc.
View newest version in sPHENIX GitHub at line 25 of file PHG4Detector.cc
References ConstructMe(), PHG4Subsystem::GetLogicalVolume(), PHG4Subsystem::GetMotherSubsystem(), and m_MySubsystem.
Referenced by PHG4PhenixDetector::Construct().
virtual void PHG4Detector::ConstructMe (G4LogicalVolume * mothervolume) pure virtual
Implemented in EICG4LumiDetector, PHG4TTLDetector, PHG4RICHDetector, PHG4SpacalDetector, PHG4FullProjSpacalDetector, PHG4FullProjTiltedSpacalDetector, PHG4BarrelEcalDetector, PHG4GDMLDetector, PHG4OuterHcalDetector, PHG4ForwardEcalDetector, PHG4InnerHcalDetector, PHG4ForwardDualReadoutDetector, PHG4CrystalCalorimeterDetector, PHG4HybridHomogeneousCalorimeterDetector, PHG4LFHcalDetector, PHG4BackwardHcalDetector, PHG4ForwardHcalDetector, PHG4ProjCrystalCalorimeterDetector, PHG4mRICHDetector, PHG4EICForwardEcalDetector, G4LmonDetector, PHG4HcalDetector, PHG4EICMvtxDetector, PHG4MvtxDetector, G4EicDircDetector, PHG4ZDCDetector, PHG4TpcDetector, PHG4FPbScDetector, G4LBLVtxDetector, G4LBLVtxDetector, PHG4BbcDetector, PHG4EPDDetector, PHG4InttDetector, PHG4MicromegasDetector, PHG4TpcEndCapDetector, BeamLineMagnetDetector, PHG4CEmcTestBeamDetector, PHG4SectorDetector, PHG4FCalDetector, AllSiliconTrackerDetector, AllSiliconTrackerDetector, PHG4BlockDetector, PHG4ConeDetector, PHG4CylinderDetector, EICG4B0ECALDetector, PHG4CylinderStripDetector, G4JLeicBeamLineMagnetDetector, G4JLeicBeamLineMagnetDetector, PHG4BeamlineMagnetDetector, PHG4EnvelopeDetector, EICG4B0Detector, BeastMagnetDetector, EICG4BwdDetector, EICG4dRICHDetector, AllSi_Al_support_Detector, EicFRichDetector, EICG4ZDCDetector, G4Example03Detector, AllSi_Al_support_Detector, EicFRichDetector, EicToyModelDetector, PHG4PSTOFDetector, PHG4ECAPToFDetector, G4JLeicDIRCDetector, G4JLeicVTXDetector, EICG4RPDetector, PHG4TRDDetector, G4JLeicDIRCDetector, G4JLeicVTXDetector, G4Example02Detector, EicRootDetector, and G4Example01Detector.
Referenced by Construct().
int PHG4Detector::DisplayVolume (G4VSolid * volume, G4LogicalVolume * logvol, G4RotationMatrix * rotm = nullptr) virtual
Definition at line 39 of file PHG4Detector.cc.
View newest version in sPHENIX GitHub at line 39 of file PHG4Detector.cc
Referenced by PHG4OuterHcalDetector::ConstructHcalSingleScintillators().
int PHG4Detector::DisplayVolume (G4LogicalVolume * checksolid, G4LogicalVolume * logvol, G4RotationMatrix * rotm = nullptr) virtual
Definition at line 46 of file PHG4Detector.cc.
View newest version in sPHENIX GitHub at line 46 of file PHG4Detector.cc
References m_ColorIndex.
G4Element * PHG4Detector::GetDetectorElement (const std::string & name, const bool quit = true) static
Definition at line 109 of file PHG4Detector.cc.
View newest version in sPHENIX GitHub at line 109 of file PHG4Detector.cc
References exit().
Referenced by PHG4BarrelEcalDetector::GetCarbonFiber(), PHG4LFHcalDetector::GetCoatingMaterial(), PHG4ForwardEcalDetector::GetCoatingMaterial(), PHG4BarrelEcalDetector::GetSciGlass(), PHG4LFHcalDetector::GetScintillatorMaterial(), PHG4ForwardEcalDetector::GetScintillatorMaterial(), PHG4ForwardEcalDetector::GetWLSFiberFEMCMaterial(), and PHG4LFHcalDetector::GetWLSFiberMaterial().
G4Material * PHG4Detector::GetDetectorMaterial (const std::string & name, const bool quit = true) static
Definition at line 84 of file PHG4Detector.cc.
View newest version in sPHENIX GitHub at line 84 of file PHG4Detector.cc
References exit().
Referenced by EICG4LumiDetector::AddCuboid(), AllSi_Al_support_Detector::addDetectorSection(), EICG4LumiDetector::AddExitWindowForV2(), EICG4LumiDetector::AddExitWindowForV3(), PHG4TpcEndCapDetector::AddLayer(), EICG4LumiDetector::AddLumiExitWindow(), EICG4LumiDetector::AddLumiMag_MagCore(), EICG4LumiDetector::AddLumiMag_OuterVessel(), EICG4LumiDetector::AddLumiWindow(), EICG4LumiDetector::AddRecCone(), EICG4LumiDetector::AddTriangularTrapezoid(), PHG4TTLDetector::BuildBarrelTTL(), PHG4TTLDetector::BuildForwardTTL(), PHG4CylinderStripDetector::BuildMaterials(), PHG4FullProjTiltedSpacalDetector::Construct_AzimuthalSeg(), PHG4FullProjSpacalDetector::Construct_AzimuthalSeg(), PHG4SpacalDetector::Construct_AzimuthalSeg(), PHG4SpacalDetector::Construct_Fiber(), PHG4FullProjTiltedSpacalDetector::Construct_LightGuide(), PHG4MicromegasDetector::construct_micromegas(), PHG4Sector::PHG4SectorConstructor::Construct_Sectors(), PHG4FullProjTiltedSpacalDetector::Construct_Tower(), PHG4FullProjSpacalDetector::Construct_Tower(), PHG4BarrelEcalDetector::ConstructCarbon(), PHG4TpcEndCapDetector::ConstructElectronics(), PHG4TpcEndCapDetector::ConstructEndCapAssembly(), PHG4InnerHcalDetector::ConstructHcalScintillatorAssembly(), PHG4OuterHcalDetector::ConstructHcalScintillatorAssembly(), PHG4InnerHcalDetector::ConstructInnerHcal(), PHG4InttDetector::ConstructIntt(), PHG4BarrelEcalDetector::ConstructKapton(), PHG4ECAPToFDetector::ConstructMe(), G4JLeicDIRCDetector::ConstructMe(), G4JLeicVTXDetector::ConstructMe(), PHG4PSTOFDetector::ConstructMe(), PHG4TRDDetector::ConstructMe(), EICG4RPDetector::ConstructMe(), PHG4BeamlineMagnetDetector::ConstructMe(), EICG4B0Detector::ConstructMe(), PHG4EnvelopeDetector::ConstructMe(), EICG4BwdDetector::ConstructMe(), EICG4ZDCDetector::ConstructMe(), PHG4CylinderDetector::ConstructMe(), PHG4ConeDetector::ConstructMe(), PHG4CylinderStripDetector::ConstructMe(), G4JLeicBeamLineMagnetDetector::ConstructMe(), PHG4BlockDetector::ConstructMe(), EICG4B0ECALDetector::ConstructMe(), PHG4CEmcTestBeamDetector::ConstructMe(), BeamLineMagnetDetector::ConstructMe(), PHG4BbcDetector::ConstructMe(), PHG4EPDDetector::ConstructMe(), PHG4TpcDetector::ConstructMe(), PHG4ZDCDetector::ConstructMe(), PHG4HcalDetector::ConstructMe(), PHG4EICForwardEcalDetector::ConstructMe(), PHG4ForwardHcalDetector::ConstructMe(), PHG4ProjCrystalCalorimeterDetector::ConstructMe(), PHG4BackwardHcalDetector::ConstructMe(), PHG4LFHcalDetector::ConstructMe(), PHG4ForwardDualReadoutDetector::ConstructMe(), PHG4CrystalCalorimeterDetector::ConstructMe(), PHG4InnerHcalDetector::ConstructMe(), PHG4OuterHcalDetector::ConstructMe(), PHG4ForwardEcalDetector::ConstructMe(), PHG4BarrelEcalDetector::ConstructMe(), PHG4SpacalDetector::ConstructMe(), PHG4OuterHcalDetector::ConstructOuterHcal(), PHG4ProjCrystalCalorimeterDetector::ConstructProjectiveCrystals(), PHG4CEmcTestBeamDetector::ConstructSandwichVolume(), PHG4BarrelEcalDetector::ConstructSi(), PHG4BarrelEcalDetector::ConstructSIO2(), PHG4HybridHomogeneousCalorimeterDetector::ConstructSupportFrame(), PHG4ForwardHcalDetector::ConstructTower(), PHG4EICForwardEcalDetector::ConstructTower(), EICG4BwdDetector::ConstructTower(), PHG4BackwardHcalDetector::ConstructTower(), EICG4B0ECALDetector::ConstructTower(), PHG4LFHcalDetector::ConstructTower(), PHG4CrystalCalorimeterDetector::ConstructTower(), PHG4HybridHomogeneousCalorimeterDetector::ConstructTower(), PHG4ForwardDualReadoutDetector::ConstructTower(), PHG4ForwardEcalDetector::ConstructTower(), PHG4ForwardDualReadoutDetector::ConstructTowerFCStyle(), PHG4CEmcTestBeamDetector::ConstructTowerVolume(), PHG4TpcDetector::ConstructTpcCageVolume(), PHG4TpcDetector::ConstructTpcExternalSupports(), PHG4TpcDetector::ConstructTpcGasVolume(), PHG4TpcEndCapDetector::ConstructWagonWheel(), PHG4MicromegasDetector::create_materials(), PHG4TpcDetector::CreateCompositeMaterial(), PHG4TpcEndCapDetector::CreateCompositeMaterial(), EicFRichDetector::element_material(), PHG4ProjCrystalCalorimeterDetector::Fill4x4Unit(), PHG4ProjCrystalCalorimeterDetector::FillSpecialUnit(), PHG4CrystalCalorimeterDetector::GetCarbonFiber(), PHG4HybridHomogeneousCalorimeterDetector::GetCarbonFiber(), PHG4BarrelEcalDetector::GetCarbonFiber(), PHG4LFHcalDetector::GetCoatingMaterial(), PHG4ForwardEcalDetector::GetCoatingMaterial(), PHG4MvtxDetector::GetMvtxOuterShell(), PHG4BarrelEcalDetector::GetSciGlass(), PHG4HybridHomogeneousCalorimeterDetector::GetScintillatorMaterial(), PHG4HybridHomogeneousCalorimeterDetector::GetTedlarMaterial(), PHG4HybridHomogeneousCalorimeterDetector::GetVM2000Material(), EICG4LumiDetector::MakeTower(), PHG4mRICHDetector::mRichParameter::mRichParameter(), PHG4FCalDetector::SetMaterial(), and PHG4FPbScDetector::SetMaterial().
virtual PHG4Subsystem* PHG4Detector::GetMySubsystem () inline virtual
Definition at line 61 of file PHG4Detector.h.
View newest version in sPHENIX GitHub at line 61 of file PHG4Detector.h
References m_MySubsystem.
Referenced by EicRootDetector::ConstructMe(), PHG4BlockDetector::ConstructMe(), PHG4CylinderStripDetector::ConstructMe(), PHG4ConeDetector::ConstructMe(), PHG4CylinderDetector::ConstructMe(), AllSiliconTrackerDetector::ConstructMe(), BeamLineMagnetDetector::ConstructMe(), G4LBLVtxDetector::ConstructMe(), PHG4GDMLDetector::ConstructMe(), and EicRootDetector::IsInDetector().
virtual std::string PHG4Detector::GetName (void) const inline virtual
Definition at line 51 of file PHG4Detector.h.
View newest version in sPHENIX GitHub at line 51 of file PHG4Detector.h
References m_Name.
Referenced by AllSiliconTrackerDetector::AddHitNodes(), PHG4TpcEndCapDetector::AddLayer(), PHG4FullProjTiltedSpacalDetector::Construct_AzimuthalSeg(), PHG4FullProjSpacalDetector::Construct_AzimuthalSeg(), PHG4SpacalDetector::Construct_AzimuthalSeg(), PHG4SpacalDetector::Construct_Fiber(), PHG4FullProjSpacalDetector::Construct_Fibers(), PHG4FullProjTiltedSpacalDetector::Construct_Fibers(), PHG4FullProjSpacalDetector::Construct_Fibers_SameLengthFiberPerTower(), PHG4FullProjTiltedSpacalDetector::Construct_Fibers_SameLengthFiberPerTower(), PHG4FullProjTiltedSpacalDetector::Construct_LightGuide(), PHG4MicromegasDetector::construct_micromegas(), PHG4FullProjTiltedSpacalDetector::Construct_Tower(), PHG4FullProjSpacalDetector::Construct_Tower(), PHG4TpcEndCapDetector::ConstructElectronics(), PHG4BeamlineMagnetDetector::ConstructMe(), G4JLeicBeamLineMagnetDetector::ConstructMe(), PHG4CylinderDetector::ConstructMe(), PHG4ConeDetector::ConstructMe(), PHG4CylinderStripDetector::ConstructMe(), PHG4BlockDetector::ConstructMe(), BeamLineMagnetDetector::ConstructMe(), AllSiliconTrackerDetector::ConstructMe(), G4LBLVtxDetector::ConstructMe(), PHG4HcalDetector::ConstructMe(), PHG4GDMLDetector::ConstructMe(), PHG4FullProjTiltedSpacalDetector::ConstructMe(), PHG4FullProjSpacalDetector::ConstructMe(), PHG4SpacalDetector::ConstructMe(), PHG4TpcEndCapDetector::ConstructWagonWheel(), PHG4OuterHcalSteppingAction::PHG4OuterHcalSteppingAction(), PHG4TpcSteppingAction::PHG4TpcSteppingAction(), G4LBLVtxDetector::Print(), PHG4GDMLDetector::Print(), Print(), PHG4FullProjSpacalDetector::Print(), PHG4FullProjTiltedSpacalDetector::Print(), PHG4SpacalDetector::Print(), PHG4FPbScSteppingAction::SetInterfacePointers(), PHG4EnvelopeSteppingAction::SetInterfacePointers(), G4Example01SteppingAction::SetInterfacePointers(), PHG4EICMvtxSteppingAction::SetInterfacePointers(), PHG4MvtxSteppingAction::SetInterfacePointers(), PHG4ConeSteppingAction::SetInterfacePointers(), PHG4SectorSteppingAction::SetInterfacePointers(), PHG4PSTOFSteppingAction::SetInterfacePointers(), G4JLeicVTXSteppingAction::SetInterfacePointers(), PHG4FPbScRegionSteppingAction::SetInterfacePointers(), G4JLeicDIRCSteppingAction::SetInterfacePointers(), G4LBLVtxSteppingAction::SetInterfacePointers(), PHG4InttSteppingAction::SetInterfacePointers(), G4Example03SteppingAction::SetInterfacePointers(), G4JLeicBeamLineMagnetSteppingAction::SetInterfacePointers(), G4Example02SteppingAction::SetInterfacePointers(), PHG4BlockSteppingAction::SetInterfacePointers(), PHG4CEmcTestBeamSteppingAction::SetInterfacePointers(), PHG4InnerHcalSteppingAction::SetInterfacePointers(), EicFRichSteppingAction::SetInterfacePointers(), PHG4CylinderStripSteppingAction::SetInterfacePointers(), AllSi_Al_support_SteppingAction::SetInterfacePointers(), BeastMagnetSteppingAction::SetInterfacePointers(), PHG4HcalSteppingAction::SetInterfacePointers(), EICG4dRICHSteppingAction::SetInterfacePointers(), EICG4ZDCSteppingAction::SetInterfacePointers(), PHG4ForwardDualReadoutSteppingAction::SetInterfacePointers(), PHG4BackwardHcalSteppingAction::SetInterfacePointers(), PHG4HybridHomogeneousCalorimeterSteppingAction::SetInterfacePointers(), PHG4ECAPToFSteppingAction::SetInterfacePointers(), PHG4ForwardEcalSteppingAction::SetInterfacePointers(), PHG4OuterHcalSteppingAction::SetInterfacePointers(), PHG4LFHcalSteppingAction::SetInterfacePointers(), PHG4CrystalCalorimeterSteppingAction::SetInterfacePointers(), PHG4TRDSteppingAction::SetInterfacePointers(), PHG4SpacalSteppingAction::SetInterfacePointers(), PHG4TTLSteppingAction::SetInterfacePointers(), PHG4LFHcalSteppingAction::UserSteppingAction(), PHG4ForwardDualReadoutSteppingAction::UserSteppingAction(), PHG4BackwardHcalSteppingAction::UserSteppingAction(), PHG4ForwardEcalSteppingAction::UserSteppingAction(), PHG4ForwardHcalSteppingAction::UserSteppingAction(), PHG4ZDCSteppingAction::UserSteppingAction(), and PHG4SpacalSteppingAction::UserSteppingAction().
virtual G4UserSteppingAction* PHG4Detector::GetSteppingAction (void) inline virtual
Reimplemented in PHG4HcalDetector, PHG4RICHDetector, PHG4GDMLDetector, PHG4FPbScDetector, and PHG4FCalDetector.
Definition at line 50 of file PHG4Detector.h.
View newest version in sPHENIX GitHub at line 50 of file PHG4Detector.h
virtual void PHG4Detector::OverlapCheck (const bool chk) inline virtual
Reimplemented in PHG4TTLDetector, PHG4RICHDetector, and PHG4SectorDetector.
Definition at line 52 of file PHG4Detector.h.
View newest version in sPHENIX GitHub at line 52 of file PHG4Detector.h
References m_OverlapCheck.
Referenced by PHG4EnvelopeSubsystem::Init(), PHG4CEmcTestBeamSubsystem::Init(), G4Example01Subsystem::Init(), G4LmonSubsystem::Init(), PHG4HcalSubsystem::InitRun(), PHG4ECAPToFSubsystem::InitRunSubsystem(), PHG4TRDSubsystem::InitRunSubsystem(), PHG4EPDSubsystem::InitRunSubsystem(), EicRootSubsystem::InitRunSubsystem(), PHG4ZDCSubsystem::InitRunSubsystem(), PHG4InnerHcalSubsystem::InitRunSubsystem(), BeamLineMagnetSubsystem::InitRunSubsystem(), PHG4TpcSubsystem::InitRunSubsystem(), G4LBLVtxSubsystem::InitRunSubsystem(), PHG4OuterHcalSubsystem::InitRunSubsystem(), PHG4ConeSubsystem::InitRunSubsystem(), PHG4BarrelEcalSubsystem::InitRunSubsystem(), PHG4CrystalCalorimeterSubsystem::InitRunSubsystem(), PHG4ForwardHcalSubsystem::InitRunSubsystem(), PHG4CylinderSubsystem::InitRunSubsystem(), PHG4HybridHomogeneousCalorimeterSubsystem::InitRunSubsystem(), PHG4LFHcalSubsystem::InitRunSubsystem(), PHG4BlockSubsystem::InitRunSubsystem(), PHG4ForwardDualReadoutSubsystem::InitRunSubsystem(), PHG4BackwardHcalSubsystem::InitRunSubsystem(), PHG4EICMvtxSubsystem::InitRunSubsystem(), G4JLeicBeamLineMagnetSubsystem::InitRunSubsystem(), PHG4MvtxSubsystem::InitRunSubsystem(), PHG4ForwardEcalSubsystem::InitRunSubsystem(), EicToyModelSubsystem::InitRunSubsystem(), EICG4dRICHSubsystem::InitRunSubsystem(), PHG4CylinderStripSubsystem::InitRunSubsystem(), AllSi_Al_support_Subsystem::InitRunSubsystem(), EicFRichSubsystem::InitRunSubsystem(), EICG4B0ECALSubsystem::InitRunSubsystem(), EICG4LumiSubsystem::InitRunSubsystem(), EICG4B0Subsystem::InitRunSubsystem(), EICG4ZDCSubsystem::InitRunSubsystem(), EICG4BwdSubsystem::InitRunSubsystem(), EICG4RPSubsystem::InitRunSubsystem(), BeastMagnetSubsystem::InitRunSubsystem(), PHG4MicromegasSubsystem::InitRunSubsystem(), PHG4TpcEndCapSubsystem::InitRunSubsystem(), PHG4mRICHSubsystem::InitRunSubsystem(), G4Example02Subsystem::InitRunSubsystem(), AllSiliconTrackerSubsystem::InitRunSubsystem(), PHG4SpacalSubsystem::InitRunSubsystem(), PHG4GDMLSubsystem::InitRunSubsystem(), G4Example03Subsystem::InitRunSubsystem(), G4EicDircSubsystem::InitRunSubsystem(), G4JLeicDIRCSubsystem::InitRunSubsystem(), G4JLeicVTXSubsystem::InitRunSubsystem(), PHG4BbcSubsystem::InitRunSubsystem(), and PHG4PSTOFSubsystem::InitRunSubsystem().
virtual bool PHG4Detector::OverlapCheck () const inline virtual
Definition at line 53 of file PHG4Detector.h.
View newest version in sPHENIX GitHub at line 53 of file PHG4Detector.h
References m_OverlapCheck.
Referenced by EICG4LumiDetector::AddCAL(), EICG4LumiDetector::AddCuboid(), AllSi_Al_support_Detector::addDetectorSection(), EicFRichDetector::addDetectorSection(), EICG4LumiDetector::AddExitWindowForV2(), EICG4LumiDetector::AddExitWindowForV3(), EICG4LumiDetector::AddLumiExitWindow(), EICG4LumiDetector::AddLumiMag_MagCore(), EICG4LumiDetector::AddLumiMag_OuterVessel(), EICG4LumiDetector::AddLumiTracker(), EICG4LumiDetector::AddLumiWindow(), EICG4LumiDetector::AddRecCone(), EICG4LumiDetector::AddTriangularTrapezoid(), PHG4mRICHDetector::build_box(), PHG4mRICHDetector::build_lens(), PHG4mRICHDetector::build_mRICH_sector(), PHG4mRICHDetector::build_mRICH_sector2(), PHG4mRICHDetector::build_mRICH_wall_eside(), PHG4mRICHDetector::build_mRICH_wall_eside_proj(), PHG4mRICHDetector::build_mRICH_wall_hside(), PHG4mRICHDetector::build_polyhedra(), PHG4FullProjTiltedSpacalDetector::Construct_AzimuthalSeg(), PHG4FullProjSpacalDetector::Construct_AzimuthalSeg(), PHG4SpacalDetector::Construct_AzimuthalSeg(), PHG4SpacalDetector::Construct_Fiber(), PHG4FullProjSpacalDetector::Construct_Fibers(), PHG4FullProjTiltedSpacalDetector::Construct_Fibers(), PHG4FullProjSpacalDetector::Construct_Fibers_SameLengthFiberPerTower(), PHG4FullProjTiltedSpacalDetector::Construct_Fibers_SameLengthFiberPerTower(), PHG4MicromegasDetector::construct_micromegas(), PHG4InnerHcalDetector::ConstructInnerHcal(), PHG4InttDetector::ConstructIntt(), G4Example01Detector::ConstructMe(), PHG4ECAPToFDetector::ConstructMe(), G4JLeicDIRCDetector::ConstructMe(), G4JLeicVTXDetector::ConstructMe(), PHG4PSTOFDetector::ConstructMe(), PHG4TRDDetector::ConstructMe(), EICG4RPDetector::ConstructMe(), G4Example02Detector::ConstructMe(), PHG4BeamlineMagnetDetector::ConstructMe(), EICG4B0Detector::ConstructMe(), PHG4EnvelopeDetector::ConstructMe(), BeastMagnetDetector::ConstructMe(), EICG4BwdDetector::ConstructMe(), G4Example03Detector::ConstructMe(), EICG4ZDCDetector::ConstructMe(), PHG4ConeDetector::ConstructMe(), PHG4CylinderDetector::ConstructMe(), G4JLeicBeamLineMagnetDetector::ConstructMe(), EICG4B0ECALDetector::ConstructMe(), PHG4CylinderStripDetector::ConstructMe(), PHG4BlockDetector::ConstructMe(), AllSiliconTrackerDetector::ConstructMe(), BeamLineMagnetDetector::ConstructMe(), PHG4CEmcTestBeamDetector::ConstructMe(), PHG4BbcDetector::ConstructMe(), PHG4TpcEndCapDetector::ConstructMe(), PHG4EPDDetector::ConstructMe(), PHG4TpcDetector::ConstructMe(), G4LBLVtxDetector::ConstructMe(), PHG4ZDCDetector::ConstructMe(), G4EicDircDetector::ConstructMe(), PHG4HcalDetector::ConstructMe(), PHG4EICForwardEcalDetector::ConstructMe(), PHG4ForwardHcalDetector::ConstructMe(), PHG4ProjCrystalCalorimeterDetector::ConstructMe(), PHG4BackwardHcalDetector::ConstructMe(), PHG4LFHcalDetector::ConstructMe(), PHG4ForwardDualReadoutDetector::ConstructMe(), PHG4CrystalCalorimeterDetector::ConstructMe(), PHG4InnerHcalDetector::ConstructMe(), PHG4GDMLDetector::ConstructMe(), PHG4OuterHcalDetector::ConstructMe(), PHG4ForwardEcalDetector::ConstructMe(), PHG4BarrelEcalDetector::ConstructMe(), PHG4SpacalDetector::ConstructMe(), PHG4EICMvtxDetector::ConstructMvtx_Layer(), PHG4MvtxDetector::ConstructMvtx_Layer(), PHG4MvtxDetector::ConstructMvtxPassiveVol(), PHG4OuterHcalDetector::ConstructOuterHcal(), PHG4ProjCrystalCalorimeterDetector::ConstructProjectiveCrystals(), PHG4CEmcTestBeamDetector::ConstructSandwichVolume(), PHG4HybridHomogeneousCalorimeterDetector::ConstructSupportFrame(), PHG4BackwardHcalDetector::ConstructTower(), PHG4ForwardHcalDetector::ConstructTower(), PHG4EICForwardEcalDetector::ConstructTower(), PHG4LFHcalDetector::ConstructTower(), PHG4CrystalCalorimeterDetector::ConstructTower(), PHG4HybridHomogeneousCalorimeterDetector::ConstructTower(), PHG4ForwardDualReadoutDetector::ConstructTower(), PHG4ForwardEcalDetector::ConstructTower(), PHG4ForwardDualReadoutDetector::ConstructTowerFCStyle(), PHG4CEmcTestBeamDetector::ConstructTowerVolume(), PHG4TpcDetector::ConstructTpcCageVolume(), PHG4TpcDetector::ConstructTpcExternalSupports(), PHG4TpcDetector::ConstructTpcGasVolume(), PHG4ProjCrystalCalorimeterDetector::Fill4x4Unit(), PHG4ProjCrystalCalorimeterDetector::FillSpecialUnit(), PHG4MvtxDetector::GetMvtxOuterShell(), EICG4LumiDetector::MakeTower(), PHG4SectorDetector::OverlapCheck(), PHG4RICHDetector::OverlapCheck(), PHG4EICForwardEcalDetector::PlaceTower(), PHG4ForwardHcalDetector::PlaceTower(), EICG4BwdDetector::PlaceTower(), PHG4BackwardHcalDetector::PlaceTower(), EICG4B0ECALDetector::PlaceTower(), PHG4LFHcalDetector::PlaceTower(), PHG4CrystalCalorimeterDetector::PlaceTower(), PHG4HybridHomogeneousCalorimeterDetector::PlaceTower(), PHG4BarrelEcalDetector::PlaceTower(), and PHG4ForwardEcalDetector::PlaceTower().
virtual void PHG4Detector::PostConstruction () inline virtual
Optional PostConstruction call after all geometry is constructed.
Reimplemented in BeamLineMagnetDetector.
Definition at line 45 of file PHG4Detector.h.
View newest version in sPHENIX GitHub at line 45 of file PHG4Detector.h
Referenced by PHG4PhenixDetector::Construct().
virtual void PHG4Detector::Print (const std::string & = "ALL") const inline virtual
Reimplemented in PHG4SpacalDetector, PHG4HcalDetector, EICG4LumiDetector, PHG4FullProjTiltedSpacalDetector, PHG4FullProjSpacalDetector, PHG4GDMLDetector, PHG4OuterHcalDetector, PHG4InnerHcalDetector, G4LBLVtxDetector, G4LBLVtxDetector, G4EicDircDetector, G4LmonDetector, PHG4BbcDetector, PHG4MicromegasDetector, PHG4TpcEndCapDetector, AllSiliconTrackerDetector, AllSiliconTrackerDetector, EICG4B0ECALDetector, EICG4B0Detector, BeastMagnetDetector, EICG4BwdDetector, EICG4dRICHDetector, AllSi_Al_support_Detector, EicFRichDetector, EICG4ZDCDetector, G4Example03Detector, AllSi_Al_support_Detector, EicFRichDetector, EicToyModelDetector, PHG4PSTOFDetector, G4JLeicDIRCDetector, G4JLeicVTXDetector, EICG4RPDetector, G4JLeicDIRCDetector, G4JLeicVTXDetector, G4Example02Detector, EicRootDetector, and G4Example01Detector.
Definition at line 54 of file PHG4Detector.h.
View newest version in sPHENIX GitHub at line 54 of file PHG4Detector.h
References GetName().
Referenced by PHG4TpcSubsystem::Print().
virtual PHCompositeNode* PHG4Detector::topNode () inline virtual
Definition at line 60 of file PHG4Detector.h.
View newest version in sPHENIX GitHub at line 60 of file PHG4Detector.h
References m_topNode.
Referenced by PHG4MicromegasDetector::add_geometry_node(), PHG4MvtxDetector::AddGeometryNode(), PHG4EICMvtxDetector::AddGeometryNode(), PHG4InttDetector::AddGeometryNode(), AllSiliconTrackerDetector::ConstructMe(), PHG4HcalDetector::ConstructMe(), PHG4SpacalDetector::ConstructMe(), PHG4FCalSubsystem::Init(), PHG4SectorSubsystem::Init(), PHG4FPbScSubsystem::Init(), PHG4RICHSubsystem::Init(), PHG4ZDCSubsystem::InitRunSubsystem(), PHG4InnerHcalSubsystem::InitRunSubsystem(), BeamLineMagnetSubsystem::InitRunSubsystem(), PHG4TpcSubsystem::InitRunSubsystem(), PHG4OuterHcalSubsystem::InitRunSubsystem(), PHG4BackwardHcalSubsystem::InitRunSubsystem(), PHG4BarrelEcalSubsystem::InitRunSubsystem(), PHG4LFHcalSubsystem::InitRunSubsystem(), PHG4ForwardDualReadoutSubsystem::InitRunSubsystem(), PHG4BlockSubsystem::InitRunSubsystem(), PHG4CylinderSubsystem::InitRunSubsystem(), PHG4CrystalCalorimeterSubsystem::InitRunSubsystem(), PHG4ConeSubsystem::InitRunSubsystem(), PHG4ForwardHcalSubsystem::InitRunSubsystem(), PHG4HybridHomogeneousCalorimeterSubsystem::InitRunSubsystem(), PHG4TTLSubsystem::InitRunSubsystem(), PHG4EICMvtxSubsystem::InitRunSubsystem(), PHG4MvtxSubsystem::InitRunSubsystem(), G4JLeicBeamLineMagnetSubsystem::InitRunSubsystem(), PHG4ForwardEcalSubsystem::InitRunSubsystem(), PHG4CylinderStripSubsystem::InitRunSubsystem(), PHG4InttSubsystem::InitRunSubsystem(), PHG4mRICHSubsystem::InitRunSubsystem(), and PHG4SpacalSubsystem::InitRunSubsystem().
virtual void PHG4Detector::Verbosity (const int v) inline virtual
Definition at line 47 of file PHG4Detector.h.
View newest version in sPHENIX GitHub at line 47 of file PHG4Detector.h
References m_Verbosity, and v.
Referenced by PHG4FCalSubsystem::Init(), PHG4FPbScSubsystem::Init(), PHG4RICHSubsystem::Init(), PHG4ZDCSubsystem::InitRunSubsystem(), BeamLineMagnetSubsystem::InitRunSubsystem(), PHG4BackwardHcalSubsystem::InitRunSubsystem(), PHG4BarrelEcalSubsystem::InitRunSubsystem(), PHG4ForwardDualReadoutSubsystem::InitRunSubsystem(), PHG4ForwardHcalSubsystem::InitRunSubsystem(), PHG4LFHcalSubsystem::InitRunSubsystem(), PHG4EICMvtxSubsystem::InitRunSubsystem(), PHG4MvtxSubsystem::InitRunSubsystem(), PHG4ForwardEcalSubsystem::InitRunSubsystem(), PHG4TpcEndCapSubsystem::InitRunSubsystem(), PHG4MicromegasSubsystem::InitRunSubsystem(), and G4EicDircSubsystem::InitRunSubsystem().
virtual int PHG4Detector::Verbosity () const inline virtual
Definition at line 49 of file PHG4Detector.h.
View newest version in sPHENIX GitHub at line 49 of file PHG4Detector.h
References m_Verbosity.
Referenced by EICG4dRICHDetector::ActivateVolumeTree(), PHG4MvtxDetector::AddGeometryNode(), PHG4EICMvtxDetector::AddGeometryNode(), PHG4InttDetector::AddGeometryNode(), PHG4mRICHDetector::build_foamHolder(), PHG4mRICHDetector::build_mRICH_sector2(), PHG4mRICHDetector::build_mRICH_wall_eside(), PHG4mRICHDetector::build_mRICH_wall_eside_proj(), PHG4FullProjTiltedSpacalDetector::Construct_AzimuthalSeg(), PHG4SpacalDetector::Construct_AzimuthalSeg(), PHG4SpacalDetector::Construct_Fiber(), PHG4TpcEndCapDetector::ConstructElectronics(), PHG4InttDetector::ConstructIntt(), PHG4ECAPToFDetector::ConstructMe(), EICG4RPDetector::ConstructMe(), EICG4B0Detector::ConstructMe(), EICG4BwdDetector::ConstructMe(), PHG4BeamlineMagnetDetector::ConstructMe(), EICG4dRICHDetector::ConstructMe(), EICG4B0ECALDetector::ConstructMe(), G4JLeicBeamLineMagnetDetector::ConstructMe(), BeamLineMagnetDetector::ConstructMe(), PHG4InttDetector::ConstructMe(), G4LBLVtxDetector::ConstructMe(), PHG4ZDCDetector::ConstructMe(), PHG4EICMvtxDetector::ConstructMe(), G4EicDircDetector::ConstructMe(), PHG4MvtxDetector::ConstructMe(), PHG4EICForwardEcalDetector::ConstructMe(), PHG4ForwardHcalDetector::ConstructMe(), PHG4ProjCrystalCalorimeterDetector::ConstructMe(), PHG4BackwardHcalDetector::ConstructMe(), PHG4CrystalCalorimeterDetector::ConstructMe(), PHG4HybridHomogeneousCalorimeterDetector::ConstructMe(), PHG4LFHcalDetector::ConstructMe(), PHG4ForwardDualReadoutDetector::ConstructMe(), PHG4ForwardEcalDetector::ConstructMe(), PHG4GDMLDetector::ConstructMe(), PHG4BarrelEcalDetector::ConstructMe(), PHG4SpacalDetector::ConstructMe(), EICG4LumiDetector::ConstructMe(), PHG4EICMvtxDetector::ConstructMvtx(), PHG4MvtxDetector::ConstructMvtx(), PHG4EICMvtxDetector::ConstructMvtx_Layer(), PHG4MvtxDetector::ConstructMvtx_Layer(), PHG4MvtxDetector::ConstructMvtxPassiveVol(), PHG4EICForwardEcalDetector::ConstructTower(), PHG4ForwardHcalDetector::ConstructTower(), EICG4BwdDetector::ConstructTower(), PHG4BackwardHcalDetector::ConstructTower(), EICG4B0ECALDetector::ConstructTower(), PHG4LFHcalDetector::ConstructTower(), PHG4CrystalCalorimeterDetector::ConstructTower(), PHG4HybridHomogeneousCalorimeterDetector::ConstructTower(), PHG4ForwardDualReadoutDetector::ConstructTower(), PHG4ForwardEcalDetector::ConstructTower(), PHG4ForwardDualReadoutDetector::ConstructTowerFCStyle(), PHG4TpcEndCapDetector::ConstructWagonWheel(), PHG4EICMvtxDetector::FillPVArray(), PHG4MvtxDetector::FillPVArray(), PHG4EICMvtxDetector::FindSensor(), PHG4MvtxDetector::FindSensor(), PHG4ForwardDualReadoutDetector::GetPMMAMaterial(), PHG4ForwardDualReadoutDetector::GetQuartzMaterial(), PHG4HybridHomogeneousCalorimeterDetector::GetScintillatorMaterial(), PHG4ForwardDualReadoutDetector::GetScintillatorMaterial(), PHG4ForwardEcalDetector::GetWLSFiberFEMCMaterial(), PHG4LFHcalDetector::GetWLSFiberMaterial(), PHG4MvtxDetector::IsInMvtx(), PHG4EICMvtxDetector::IsInMvtx(), PHG4EICMvtxDetector::IsSensor(), PHG4MvtxDetector::IsSensor(), PHG4EICForwardEcalDetector::ParseParametersFromTable(), PHG4BackwardHcalDetector::ParseParametersFromTable(), PHG4ForwardHcalDetector::ParseParametersFromTable(), EICG4BwdDetector::ParseParametersFromTable(), EICG4B0ECALDetector::ParseParametersFromTable(), PHG4LFHcalDetector::ParseParametersFromTable(), PHG4CrystalCalorimeterDetector::ParseParametersFromTable(), PHG4HybridHomogeneousCalorimeterDetector::ParseParametersFromTable(), PHG4ForwardDualReadoutDetector::ParseParametersFromTable(), PHG4ForwardEcalDetector::ParseParametersFromTable(), PHG4EICMvtxDetector::PHG4EICMvtxDetector(), PHG4MvtxDetector::PHG4MvtxDetector(), PHG4TpcEndCapDetector::PHG4TpcEndCapDetector(), EICG4BwdDetector::PlaceTower(), PHG4BackwardHcalDetector::PlaceTower(), PHG4EICForwardEcalDetector::PlaceTower(), PHG4ForwardHcalDetector::PlaceTower(), EICG4B0ECALDetector::PlaceTower(), PHG4LFHcalDetector::PlaceTower(), PHG4CrystalCalorimeterDetector::PlaceTower(), PHG4HybridHomogeneousCalorimeterDetector::PlaceTower(), PHG4BarrelEcalDetector::PlaceTower(), PHG4ForwardEcalDetector::PlaceTower(), BeamLineMagnetDetector::PostConstruction(), PHG4GDMLDetector::SetDisplayProperty(), PHG4EICMvtxDetector::SetDisplayProperty(), PHG4MvtxDetector::SetDisplayProperty(), PHG4OuterHcalDetector::SetTiltViaNcross(), PHG4InnerHcalDetector::SetTiltViaNcross(), and PHG4TpcEndCapDetector::~PHG4TpcEndCapDetector().
Member Data Documentation
int PHG4Detector::m_ColorIndex = 0 private
Definition at line 70 of file PHG4Detector.h.
View newest version in sPHENIX GitHub at line 70 of file PHG4Detector.h
Referenced by DisplayVolume().
PHG4Subsystem* PHG4Detector::m_MySubsystem = nullptr private
Definition at line 67 of file PHG4Detector.h.
View newest version in sPHENIX GitHub at line 67 of file PHG4Detector.h
Referenced by Construct(), and GetMySubsystem().
std::string PHG4Detector::m_Name private
Definition at line 71 of file PHG4Detector.h.
View newest version in sPHENIX GitHub at line 71 of file PHG4Detector.h
Referenced by GetName().
bool PHG4Detector::m_OverlapCheck = false private
Definition at line 69 of file PHG4Detector.h.
View newest version in sPHENIX GitHub at line 69 of file PHG4Detector.h
Referenced by OverlapCheck().
PHCompositeNode* PHG4Detector::m_topNode = nullptr private
Definition at line 66 of file PHG4Detector.h.
View newest version in sPHENIX GitHub at line 66 of file PHG4Detector.h
Referenced by topNode().
int PHG4Detector::m_Verbosity = 0 private
Definition at line 68 of file PHG4Detector.h.
View newest version in sPHENIX GitHub at line 68 of file PHG4Detector.h
Referenced by Verbosity().
The documentation for this class was generated from the following files:
fun4all_coresoftware/blob/master/simulation/g4simulation/g4main/PHG4Detector.h
fun4all_coresoftware/blob/master/simulation/g4simulation/g4main/PHG4Detector.cc