EIC Software: eicsmeardetectors/blob/master/BuildByName.cxx File Reference
BuildByName.cxx File Reference
#include "eicsmeardetectors.hh"
Functions
Smear::Detector BuildByName (std::string dname)
Smear::Detector BuildByName (std::string dname, const int i)
Smear::Detector BuildByName (std::string dname, const double d)
Function Documentation
Smear::Detector BuildByName (std::string dname)
For convenience. Not case-sensitive.Should be all upper case. Use like this: Smear::Detector detector = BuildByName("MATRIX");
Provides multiple aliases
Definition at line 3 of file BuildByName.cxx.
View newest version in sPHENIX GitHub at line 3 of file BuildByName.cxx
References BuildBeAST_0_1(), BuildCore_0_1_B3T(), BuildePHENIX_0_0(), BuildeSTAR_0_0(), BuildHandBook_1_2(), BuildJLEIC_0_1(), BuildMatrixDetector_0_1(), BuildMatrixDetector_0_2_B1_5T(), BuildMatrixDetector_0_2_B3T(), BuildPerfectDetector(), BuildSTAR_0_0(), BuildTrackingPreview_0_2_B1_5T(), BuildTrackingPreview_0_2_B3T(), BuildZEUS_0_0(), and c.
Referenced by main().
Smear::Detector BuildByName (std::string dname, const int i)
Overloaded version of Smear::Detector BuildByName (std::string dname) for detectors with an int parameter
Definition at line 82 of file BuildByName.cxx.
View newest version in sPHENIX GitHub at line 82 of file BuildByName.cxx
References c.
Smear::Detector BuildByName (std::string dname, const double d)
Overloaded version of Smear::Detector BuildByName (std::string dname) for detectors with a parameter
Definition at line 96 of file BuildByName.cxx.
View newest version in sPHENIX GitHub at line 96 of file BuildByName.cxx
References BuildCore_0_1(), BuildePHENIX_0_0(), BuildMatrixDetector_0_1_FF(), and c.