EIC Software: PHG4HybridHomogeneousCalorimeterSteppingAction Class Reference
PHG4HybridHomogeneousCalorimeterSteppingAction Class Reference
#include <fun4all_eicdetectors/blob/master/simulation/g4simulation/g4eiccalos/PHG4HybridHomogeneousCalorimeterSteppingAction.h>
Public Member Functions
PHG4HybridHomogeneousCalorimeterSteppingAction (PHG4HybridHomogeneousCalorimeterDetector *detector, const PHParameters *parameters)
constructor
virtual ~PHG4HybridHomogeneousCalorimeterSteppingAction ()
destroctor
virtual bool UserSteppingAction (const G4Step *, bool)
stepping action
virtual void SetInterfacePointers (PHCompositeNode *)
reimplemented from base class
Public Member Functions inherited from PHG4SteppingAction
PHG4SteppingAction (const std::string &name, const int i=0)
virtual ~PHG4SteppingAction ()
virtual void Verbosity (const int i)
virtual int Verbosity () const
virtual int Init ()
virtual double GetScintLightYield (const G4Step *step)
get scintillation photon count. It require a custom set SCINTILLATIONYIELD property to work
virtual double GetVisibleEnergyDeposition (const G4Step *step)
get amount of energy that can make scintillation light, in Unit of GeV.
virtual void StoreLocalCoordinate (PHG4Hit *hit, const G4Step *step, const bool do_prepoint, const bool do_postpoint)
Extract local coordinate of the hit and save to PHG4Hit.
virtual void Print (const std::string &) const
std::string GetName () const
void SetName (const std::string &name)
virtual void SetLightCorrection (const double inner_radius, const double inner_corr, const double outer_radius, const double outer_corr)
virtual double GetLightCorrection (const double r) const
virtual double GetLightCorrection (const double xpos, const double ypos) const
virtual bool ValidCorrection () const
virtual void SetHitNodeName (const std::string &, const std::string &)
Set the G4HIT node names from Subsystem rather than constructing your own.
Private Attributes
PHG4HybridHomogeneousCalorimeterDetector * m_Detector = nullptr
pointer to the detector
PHG4HitContainer * m_HitContainer = nullptr
pointer to hit container
PHG4HitContainer * m_AbsorberHitContainer = nullptr
PHG4Hit * m_Hit = nullptr
PHG4HitContainer * m_SaveHitContainer = nullptr
PHG4Shower * m_SaveShower = nullptr
int m_ActiveFlag = 0
int m_BlackHoleFlag = 0
Detailed Description
Definition at line 19 of file PHG4HybridHomogeneousCalorimeterSteppingAction.h.
View newest version in sPHENIX GitHub at line 19 of file PHG4HybridHomogeneousCalorimeterSteppingAction.h
Constructor & Destructor Documentation
PHG4HybridHomogeneousCalorimeterSteppingAction::PHG4HybridHomogeneousCalorimeterSteppingAction (PHG4HybridHomogeneousCalorimeterDetector * detector, const PHParameters * parameters)
constructor
Definition at line 41 of file PHG4HybridHomogeneousCalorimeterSteppingAction.cc.
View newest version in sPHENIX GitHub at line 41 of file PHG4HybridHomogeneousCalorimeterSteppingAction.cc
PHG4HybridHomogeneousCalorimeterSteppingAction::~PHG4HybridHomogeneousCalorimeterSteppingAction () virtual
destroctor
Definition at line 49 of file PHG4HybridHomogeneousCalorimeterSteppingAction.cc.
View newest version in sPHENIX GitHub at line 49 of file PHG4HybridHomogeneousCalorimeterSteppingAction.cc
References m_Hit.
Member Function Documentation
void PHG4HybridHomogeneousCalorimeterSteppingAction::SetInterfacePointers (PHCompositeNode * topNode) virtual
reimplemented from base class
Reimplemented from PHG4SteppingAction.
Definition at line 269 of file PHG4HybridHomogeneousCalorimeterSteppingAction.cc.
View newest version in sPHENIX GitHub at line 269 of file PHG4HybridHomogeneousCalorimeterSteppingAction.cc
References PHG4Detector::GetName(), m_AbsorberHitContainer, m_Detector, m_HitContainer, PHG4HybridHomogeneousCalorimeterDetector::SuperDetector(), and PHG4SteppingAction::Verbosity().
bool PHG4HybridHomogeneousCalorimeterSteppingAction::UserSteppingAction (const G4Step * aStep, bool) virtual
stepping action
Implements PHG4SteppingAction.
Definition at line 59 of file PHG4HybridHomogeneousCalorimeterSteppingAction.cc.
View newest version in sPHENIX GitHub at line 59 of file PHG4HybridHomogeneousCalorimeterSteppingAction.cc
References PHG4Shower::add_g4hit_id(), PHG4HitContainer::AddHit(), Acts::UnitConstants::cm, PHG4HybridHomogeneousCalorimeterDetector::get_DetectorId(), PHG4Hit::get_edep(), PHG4Hit::get_eion(), PHG4Hit::get_hit_id(), PHG4Hit::get_light_yield(), PHG4HitContainer::GetID(), PHG4SteppingAction::GetVisibleEnergyDeposition(), Acts::UnitConstants::GeV, PHG4HybridHomogeneousCalorimeterDetector::IsInCrystalCalorimeter(), k, m_AbsorberHitContainer, m_ActiveFlag, m_BlackHoleFlag, m_Detector, m_Hit, m_HitContainer, m_SaveHitContainer, m_SaveShower, PHG4CrystalCalorimeterDefs::nonprojective, p, PHG4CrystalCalorimeterDefs::projective, PHG4Hit::Reset(), PHG4Hit::set_edep(), PHG4Hit::set_eion(), PHG4Hit::set_index_j(), PHG4Hit::set_index_k(), PHG4Hit::set_light_yield(), PHG4Hit::set_shower_id(), PHG4Hit::set_t(), PHG4Hit::set_trkid(), PHG4Hit::set_x(), PHG4Hit::set_y(), PHG4Hit::set_z(), and Acts::Test::volume.
Member Data Documentation
PHG4HitContainer* PHG4HybridHomogeneousCalorimeterSteppingAction::m_AbsorberHitContainer = nullptr private
Definition at line 40 of file PHG4HybridHomogeneousCalorimeterSteppingAction.h.
View newest version in sPHENIX GitHub at line 40 of file PHG4HybridHomogeneousCalorimeterSteppingAction.h
Referenced by SetInterfacePointers(), and UserSteppingAction().
int PHG4HybridHomogeneousCalorimeterSteppingAction::m_ActiveFlag = 0 private
Definition at line 45 of file PHG4HybridHomogeneousCalorimeterSteppingAction.h.
View newest version in sPHENIX GitHub at line 45 of file PHG4HybridHomogeneousCalorimeterSteppingAction.h
Referenced by UserSteppingAction().
int PHG4HybridHomogeneousCalorimeterSteppingAction::m_BlackHoleFlag = 0 private
Definition at line 46 of file PHG4HybridHomogeneousCalorimeterSteppingAction.h.
View newest version in sPHENIX GitHub at line 46 of file PHG4HybridHomogeneousCalorimeterSteppingAction.h
Referenced by UserSteppingAction().
PHG4HybridHomogeneousCalorimeterDetector* PHG4HybridHomogeneousCalorimeterSteppingAction::m_Detector = nullptr private
pointer to the detector
Definition at line 36 of file PHG4HybridHomogeneousCalorimeterSteppingAction.h.
View newest version in sPHENIX GitHub at line 36 of file PHG4HybridHomogeneousCalorimeterSteppingAction.h
Referenced by SetInterfacePointers(), and UserSteppingAction().
PHG4Hit* PHG4HybridHomogeneousCalorimeterSteppingAction::m_Hit = nullptr private
Definition at line 41 of file PHG4HybridHomogeneousCalorimeterSteppingAction.h.
View newest version in sPHENIX GitHub at line 41 of file PHG4HybridHomogeneousCalorimeterSteppingAction.h
Referenced by UserSteppingAction(), and ~PHG4HybridHomogeneousCalorimeterSteppingAction().
PHG4HitContainer* PHG4HybridHomogeneousCalorimeterSteppingAction::m_HitContainer = nullptr private
pointer to hit container
Definition at line 39 of file PHG4HybridHomogeneousCalorimeterSteppingAction.h.
View newest version in sPHENIX GitHub at line 39 of file PHG4HybridHomogeneousCalorimeterSteppingAction.h
Referenced by SetInterfacePointers(), and UserSteppingAction().
PHG4HitContainer* PHG4HybridHomogeneousCalorimeterSteppingAction::m_SaveHitContainer = nullptr private
Definition at line 42 of file PHG4HybridHomogeneousCalorimeterSteppingAction.h.
View newest version in sPHENIX GitHub at line 42 of file PHG4HybridHomogeneousCalorimeterSteppingAction.h
Referenced by UserSteppingAction().
PHG4Shower* PHG4HybridHomogeneousCalorimeterSteppingAction::m_SaveShower = nullptr private
Definition at line 43 of file PHG4HybridHomogeneousCalorimeterSteppingAction.h.
View newest version in sPHENIX GitHub at line 43 of file PHG4HybridHomogeneousCalorimeterSteppingAction.h
Referenced by UserSteppingAction().
The documentation for this class was generated from the following files:
fun4all_eicdetectors/blob/master/simulation/g4simulation/g4eiccalos/PHG4HybridHomogeneousCalorimeterSteppingAction.h
fun4all_eicdetectors/blob/master/simulation/g4simulation/g4eiccalos/PHG4HybridHomogeneousCalorimeterSteppingAction.cc