EIC Software: CbmRichMatchRings Class Reference
CbmRichMatchRings Class Reference
Task class for matching a reconstructed CbmRichRings with a simulated CbmMCTrack. The matching criterion is a maximal number of common hits/points. The task fills the data class CbmRichRingMatch for each CbmRichRing.
#include <EicRoot/blob/master/rich/CbmRichMatchRings.h>
Public Member Functions
CbmRichMatchRings ()
Default constructor.
virtual ~CbmRichMatchRings ()
Destructor.
virtual InitStatus Init ()
Inherited from FairTask.
virtual void Exec (Option_t *opt)
Inherited from FairTask.
virtual void Finish ()
Inherited from FairTask.
Public Member Functions inherited from FairTask
FairTask ()
FairTask (const char *name, Int_t iVerbose=1)
virtual ~FairTask ()
void InitTask ()
void ReInitTask ()
void SetParTask ()
virtual void FinishTask ()
virtual void FinishEvent ()
void SetVerbose (Int_t iVerbose)
void SetInputPersistance (Bool_t val)
void CheckInputPersistance (TString branchName)
Private Member Functions
CbmRichMatchRings (const CbmRichMatchRings &)
Copy constructor.
CbmRichMatchRings & operator= (const CbmRichMatchRings &)
Assignment operator.
ClassDef (CbmRichMatchRings, 1)
Private Attributes
TClonesArray * fRings
TClonesArray * fPoints
TClonesArray * fTracks
TClonesArray * fHits
TClonesArray * fMatches
std::map< Int_t, Int_t > fMatchMap
Additional Inherited Members
Protected Member Functions inherited from FairTask
virtual InitStatus ReInit ()
virtual void SetParContainers ()
void InitTasks ()
void ReInitTasks ()
void SetParTasks ()
void FinishTasks ()
void FinishEvents ()
Protected Attributes inherited from FairTask
Int_t fVerbose
Int_t fInputPersistance
Indicates if input branch is persistant.
FairLogger * fLogger
Detailed Description
Task class for matching a reconstructed CbmRichRings with a simulated CbmMCTrack. The matching criterion is a maximal number of common hits/points. The task fills the data class CbmRichRingMatch for each CbmRichRing.
Author
Supriya Das
Date
2006
Definition at line 34 of file CbmRichMatchRings.h.
View newest version in sPHENIX GitHub at line 34 of file CbmRichMatchRings.h
Constructor & Destructor Documentation
CbmRichMatchRings::CbmRichMatchRings ()
Default constructor.
Definition at line 29 of file CbmRichMatchRings.cxx.
View newest version in sPHENIX GitHub at line 29 of file CbmRichMatchRings.cxx
CbmRichMatchRings::~CbmRichMatchRings () virtual
Destructor.
Definition at line 43 of file CbmRichMatchRings.cxx.
View newest version in sPHENIX GitHub at line 43 of file CbmRichMatchRings.cxx
CbmRichMatchRings::CbmRichMatchRings (const CbmRichMatchRings &) private
Copy constructor.
Member Function Documentation
CbmRichMatchRings::ClassDef (CbmRichMatchRings , 1) private
void CbmRichMatchRings::Exec (Option_t * opt) virtual
Inherited from FairTask.
Definition at line 72 of file CbmRichMatchRings.cxx.
View newest version in sPHENIX GitHub at line 72 of file CbmRichMatchRings.cxx
References fHits, fMatches, fMatchMap, fPoints, fRings, fTracks, CbmRichRing::GetHit(), CbmMCTrack::GetMotherId(), CbmRichRing::GetNofHits(), CbmBaseHit::GetRefId(), FairMCPoint::GetTrackID(), and it.
void CbmRichMatchRings::Finish (void) virtual
Inherited from FairTask.
Reimplemented from FairTask.
Definition at line 164 of file CbmRichMatchRings.cxx.
View newest version in sPHENIX GitHub at line 164 of file CbmRichMatchRings.cxx
InitStatus CbmRichMatchRings::Init (void) virtual
Inherited from FairTask.
Reimplemented from FairTask.
Definition at line 48 of file CbmRichMatchRings.cxx.
View newest version in sPHENIX GitHub at line 48 of file CbmRichMatchRings.cxx
References fHits, fMatches, fPoints, fRings, fTracks, FairRootManager::GetObject(), FairRootManager::Instance(), kSUCCESS, and FairRootManager::Register().
CbmRichMatchRings& CbmRichMatchRings::operator= (const CbmRichMatchRings &) private
Assignment operator.
Member Data Documentation
TClonesArray* CbmRichMatchRings::fHits private
Definition at line 71 of file CbmRichMatchRings.h.
View newest version in sPHENIX GitHub at line 71 of file CbmRichMatchRings.h
Referenced by Exec(), and Init().
TClonesArray* CbmRichMatchRings::fMatches private
Definition at line 72 of file CbmRichMatchRings.h.
View newest version in sPHENIX GitHub at line 72 of file CbmRichMatchRings.h
Referenced by Exec(), and Init().
std::map<Int_t, Int_t> CbmRichMatchRings::fMatchMap private
Definition at line 74 of file CbmRichMatchRings.h.
View newest version in sPHENIX GitHub at line 74 of file CbmRichMatchRings.h
Referenced by Exec().
TClonesArray* CbmRichMatchRings::fPoints private
Definition at line 69 of file CbmRichMatchRings.h.
View newest version in sPHENIX GitHub at line 69 of file CbmRichMatchRings.h
Referenced by Exec(), and Init().
TClonesArray* CbmRichMatchRings::fRings private
Definition at line 68 of file CbmRichMatchRings.h.
View newest version in sPHENIX GitHub at line 68 of file CbmRichMatchRings.h
Referenced by Exec(), and Init().
TClonesArray* CbmRichMatchRings::fTracks private
Definition at line 70 of file CbmRichMatchRings.h.
View newest version in sPHENIX GitHub at line 70 of file CbmRichMatchRings.h
Referenced by Exec(), and Init().
The documentation for this class was generated from the following files:
EicRoot/blob/master/rich/CbmRichMatchRings.h
EicRoot/blob/master/rich/CbmRichMatchRings.cxx