EIC Software: ResolutionLevel Class Reference
ResolutionLevel Class Reference
#include <EicRoot/blob/master/eic/htree/ResolutionLevel.h>
Public Member Functions
ResolutionLevel (const HoughTree *tree, const unsigned div[])
~ResolutionLevel ()
double GetParameterSplitFactor (unsigned ip) const
double GetCellSize (unsigned ip) const
unsigned GetTotalDivisionNumber (unsigned ip) const
unsigned GetDaughterCellNumber () const
unsigned Remap (unsigned i, unsigned ip) const
Private Attributes
unsigned * mParameterSplit
unsigned mDaughterCellNum
unsigned * mTotalDivisionNum
unsigned mTotalCellNum
double * mCellSize
unsigned * mRemap
Detailed Description
Definition at line 14 of file ResolutionLevel.h.
View newest version in sPHENIX GitHub at line 14 of file ResolutionLevel.h
Constructor & Destructor Documentation
ResolutionLevel::ResolutionLevel (const HoughTree * tree, const unsigned div[])
Definition at line 15 of file ResolutionLevel.cxx.
View newest version in sPHENIX GitHub at line 15 of file ResolutionLevel.cxx
References HoughTree::GetDdim(), HoughTree::GetDimension(), HoughTree::GetLdim(), HoughTree::GetLevel(), HoughDimension::GetMax(), HoughDimension::GetMin(), HoughTree::GetVerbosityLevel(), ip(), mCellSize, mDaughterCellNum, mParameterSplit, mRemap, mTotalCellNum, mTotalDivisionNum, and printf().
ResolutionLevel::~ResolutionLevel () inline
Definition at line 18 of file ResolutionLevel.h.
View newest version in sPHENIX GitHub at line 18 of file ResolutionLevel.h
Member Function Documentation
double ResolutionLevel::GetCellSize (unsigned ip) const inline
Definition at line 22 of file ResolutionLevel.h.
View newest version in sPHENIX GitHub at line 22 of file ResolutionLevel.h
References ip(), and mCellSize.
Referenced by HoughTree::GetInitializedCell(), FwdTrackFinder::Init(), FwdTrackFinder::ResetVtxNode(), and FwdHoughTree::SetupKalmanFilter().
unsigned ResolutionLevel::GetDaughterCellNumber () const inline
Definition at line 25 of file ResolutionLevel.h.
View newest version in sPHENIX GitHub at line 25 of file ResolutionLevel.h
References mDaughterCellNum.
Referenced by HoughTree::CheckCell().
double ResolutionLevel::GetParameterSplitFactor (unsigned ip) const inline
Definition at line 21 of file ResolutionLevel.h.
View newest version in sPHENIX GitHub at line 21 of file ResolutionLevel.h
References ip(), and mParameterSplit.
Referenced by HoughTree::CheckCell().
unsigned ResolutionLevel::GetTotalDivisionNumber (unsigned ip) const inline
Definition at line 24 of file ResolutionLevel.h.
View newest version in sPHENIX GitHub at line 24 of file ResolutionLevel.h
References ip(), and mTotalDivisionNum.
Referenced by HoughTree::AllocateLookUpTable(), and HoughTree::GetInitializedCell().
unsigned ResolutionLevel::Remap (unsigned i, unsigned ip) const inline
Definition at line 29 of file ResolutionLevel.h.
View newest version in sPHENIX GitHub at line 29 of file ResolutionLevel.h
References mDaughterCellNum, and mRemap.
Referenced by HoughTree::CheckCell().
Member Data Documentation
double* ResolutionLevel::mCellSize private
Definition at line 41 of file ResolutionLevel.h.
View newest version in sPHENIX GitHub at line 41 of file ResolutionLevel.h
Referenced by GetCellSize(), and ResolutionLevel().
unsigned ResolutionLevel::mDaughterCellNum private
Definition at line 29 of file ResolutionLevel.h.
View newest version in sPHENIX GitHub at line 29 of file ResolutionLevel.h
Referenced by GetDaughterCellNumber(), Remap(), and ResolutionLevel().
unsigned* ResolutionLevel::mParameterSplit private
Definition at line 29 of file ResolutionLevel.h.
View newest version in sPHENIX GitHub at line 29 of file ResolutionLevel.h
Referenced by GetParameterSplitFactor(), and ResolutionLevel().
unsigned* ResolutionLevel::mRemap private
Definition at line 43 of file ResolutionLevel.h.
View newest version in sPHENIX GitHub at line 43 of file ResolutionLevel.h
Referenced by Remap(), and ResolutionLevel().
unsigned ResolutionLevel::mTotalCellNum private
Definition at line 38 of file ResolutionLevel.h.
View newest version in sPHENIX GitHub at line 38 of file ResolutionLevel.h
Referenced by ResolutionLevel().
unsigned* ResolutionLevel::mTotalDivisionNum private
Definition at line 38 of file ResolutionLevel.h.
View newest version in sPHENIX GitHub at line 38 of file ResolutionLevel.h
Referenced by GetTotalDivisionNumber(), and ResolutionLevel().
The documentation for this class was generated from the following files:
EicRoot/blob/master/eic/htree/ResolutionLevel.h
EicRoot/blob/master/eic/htree/ResolutionLevel.cxx