EIC Software: charm_jet_tagging_optimization_study Namespace Reference
charm_jet_tagging_optimization_study Namespace Reference
Variables
tuple parser argparse.ArgumentParser()
string help "Main input subfolder"
tuple args parser.parse_args()
tuple csvfiles glob.glob(f"{args.input}/*/tagging_study.csv")
list dataframes []
tuple data pd.concat(dataframes)
float DiscoverySignificance 5.0
tuple xsection eat.TotalXSection('CC_DIS_e10_p275_CT18NNLO')
int lumi 100
tuple n_gen len(dataframes)
tuple allLight float(data[data["Variation"] == "all" ]["Light"])
tuple allCharm float(data[data["Variation"] == "all" ]["Charm"])
string FOM_choice "CharmErrFOM"
list optimal_row data[FOM_choice]
tuple target float(data.iloc[optimal_row][FOM_choice])
int tolerance 2
Variable Documentation
tuple charm_jet_tagging_optimization_study.allCharm float(data[data["Variation"] == "all" ]["Charm"])
Definition at line 66 of file charm_jet_tagging_optimization_study.py.
View newest version in sPHENIX GitHub at line 66 of file charm_jet_tagging_optimization_study.py
Referenced by TaggingStudyModule.finalize().
tuple charm_jet_tagging_optimization_study.allLight float(data[data["Variation"] == "all" ]["Light"])
Definition at line 65 of file charm_jet_tagging_optimization_study.py.
View newest version in sPHENIX GitHub at line 65 of file charm_jet_tagging_optimization_study.py
Referenced by TaggingStudyModule.finalize().
tuple charm_jet_tagging_optimization_study.args parser.parse_args()
Definition at line 37 of file charm_jet_tagging_optimization_study.py.
View newest version in sPHENIX GitHub at line 37 of file charm_jet_tagging_optimization_study.py
tuple charm_jet_tagging_optimization_study.csvfiles glob.glob(f"{args.input}/*/tagging_study.csv")
Definition at line 41 of file charm_jet_tagging_optimization_study.py.
View newest version in sPHENIX GitHub at line 41 of file charm_jet_tagging_optimization_study.py
list charm_jet_tagging_optimization_study.data pd.concat(dataframes)
Definition at line 52 of file charm_jet_tagging_optimization_study.py.
View newest version in sPHENIX GitHub at line 52 of file charm_jet_tagging_optimization_study.py
list charm_jet_tagging_optimization_study.dataframes []
Definition at line 46 of file charm_jet_tagging_optimization_study.py.
View newest version in sPHENIX GitHub at line 46 of file charm_jet_tagging_optimization_study.py
float charm_jet_tagging_optimization_study.DiscoverySignificance 5.0
Definition at line 60 of file charm_jet_tagging_optimization_study.py.
View newest version in sPHENIX GitHub at line 60 of file charm_jet_tagging_optimization_study.py
string charm_jet_tagging_optimization_study.FOM_choice "CharmErrFOM"
Definition at line 88 of file charm_jet_tagging_optimization_study.py.
View newest version in sPHENIX GitHub at line 88 of file charm_jet_tagging_optimization_study.py
string charm_jet_tagging_optimization_study.help "Main input subfolder"
Definition at line 35 of file charm_jet_tagging_optimization_study.py.
View newest version in sPHENIX GitHub at line 35 of file charm_jet_tagging_optimization_study.py
int charm_jet_tagging_optimization_study.lumi 100
Definition at line 62 of file charm_jet_tagging_optimization_study.py.
View newest version in sPHENIX GitHub at line 62 of file charm_jet_tagging_optimization_study.py
Referenced by FluxMonitorGrid.FillOutHistograms().
tuple charm_jet_tagging_optimization_study.n_gen len(dataframes)
Definition at line 63 of file charm_jet_tagging_optimization_study.py.
View newest version in sPHENIX GitHub at line 63 of file charm_jet_tagging_optimization_study.py
list charm_jet_tagging_optimization_study.optimal_row data[FOM_choice]
Definition at line 93 of file charm_jet_tagging_optimization_study.py.
View newest version in sPHENIX GitHub at line 93 of file charm_jet_tagging_optimization_study.py
tuple charm_jet_tagging_optimization_study.parser argparse.ArgumentParser()
Definition at line 32 of file charm_jet_tagging_optimization_study.py.
View newest version in sPHENIX GitHub at line 32 of file charm_jet_tagging_optimization_study.py
tuple charm_jet_tagging_optimization_study.target float(data.iloc[optimal_row][FOM_choice])
Definition at line 103 of file charm_jet_tagging_optimization_study.py.
View newest version in sPHENIX GitHub at line 103 of file charm_jet_tagging_optimization_study.py
Referenced by eXEvent.boost(), Acts::Test.BOOST_AUTO_TEST_CASE(), compareRootFiles(), ConvertStarlightAsciiToTree(), Gammaavectormeson.e_produceEvent(), dfe::SmallVector< T, N, Allocator >.emplace(), eASTRunAction.MergeNtuple(), Acts::RiddersPropagator< propagator_t >.propagate(), Acts::Propagator< stepper_t, navigator_t >.propagate(), nlohmann::detail::dtoa_impl.reinterpret_bits(), runpythia(), eventFileWriter.writeEvent(), and eventFileWriter.writeEventLUND().
int charm_jet_tagging_optimization_study.tolerance 2
Definition at line 104 of file charm_jet_tagging_optimization_study.py.
View newest version in sPHENIX GitHub at line 104 of file charm_jet_tagging_optimization_study.py
tuple charm_jet_tagging_optimization_study.xsection eat.TotalXSection('CC_DIS_e10_p275_CT18NNLO')
Definition at line 61 of file charm_jet_tagging_optimization_study.py.
View newest version in sPHENIX GitHub at line 61 of file charm_jet_tagging_optimization_study.py
Referenced by LookupCrossSection().