EIC Software: FW::ParticleSelector Class Reference
FW::ParticleSelector Class Reference
Select particles by applying some selection cuts.
#include <fun4all_acts/blob/master/Examples/Algorithms/Generators/ACTFW/Generators/ParticleSelector.hpp>
Classes
struct Config
Public Member Functions
ParticleSelector (const Config &cfg, Acts::Logging::Level lvl)
ProcessCode execute (const AlgorithmContext &ctx) const
Public Member Functions inherited from FW::BareAlgorithm
BareAlgorithm (std::string name, Acts::Logging::Level level=Acts::Logging::INFO)
std::string name () const finaloverride
The algorithm name.
Static Public Member Functions
static void addOptions (Options::Description &desc)
Add options for the particle selector.
static Config readConfig (const Options::Variables &vars)
Construct particle selector config from user variables.
Private Attributes
Config m_cfg
Additional Inherited Members
Protected Member Functions inherited from FW::BareAlgorithm
const Acts::Logger & logger () const
Detailed Description
Select particles by applying some selection cuts.
Definition at line 23 of file ParticleSelector.hpp.
View newest version in sPHENIX GitHub at line 23 of file ParticleSelector.hpp
Constructor & Destructor Documentation
ParticleSelector::ParticleSelector (const Config & cfg, Acts::Logging::Level lvl)
Definition at line 71 of file ParticleSelector.cpp.
View newest version in sPHENIX GitHub at line 71 of file ParticleSelector.cpp
References FW::ParticleSelector::Config::absEtaMax, FW::ParticleSelector::Config::absEtaMin, FW::ParticleSelector::Config::absZMax, FW::ParticleSelector::Config::absZMin, ACTS_DEBUG, FW::ParticleSelector::Config::etaMax, FW::ParticleSelector::Config::etaMin, FW::ParticleSelector::Config::inputEvent, m_cfg, FW::ParticleSelector::Config::outputEvent, FW::ParticleSelector::Config::phiMax, FW::ParticleSelector::Config::phiMin, FW::ParticleSelector::Config::ptMax, FW::ParticleSelector::Config::ptMin, FW::ParticleSelector::Config::removeCharged, FW::ParticleSelector::Config::removeNeutral, FW::ParticleSelector::Config::rhoMax, and FW::ParticleSelector::Config::rhoMin.
Member Function Documentation
void ParticleSelector::addOptions (Options::Description & desc) static
Add options for the particle selector.
Definition at line 22 of file ParticleSelector.cpp.
View newest version in sPHENIX GitHub at line 22 of file ParticleSelector.cpp
References value.
FW::ProcessCode ParticleSelector::execute (const AlgorithmContext & context) const virtual
Execute the algorithm for one event.
This function must be implemented by subclasses.
Implements FW::BareAlgorithm.
Definition at line 96 of file ParticleSelector.cpp.
View newest version in sPHENIX GitHub at line 96 of file ParticleSelector.cpp
References kdfinder::abs(), ACTS_DEBUG, FW::WhiteBoard::add(), Acts::VectorHelpers::eta(), FW::AlgorithmContext::eventNumber, FW::AlgorithmContext::eventStore, FW::WhiteBoard::get(), FW::SimVertex::incoming, analysis::input, max, min, FW::SimVertex::outgoing, p, Acts::VectorHelpers::perp(), Acts::VectorHelpers::phi(), phi, SUCCESS, and x.
FW::ParticleSelector::Config ParticleSelector::readConfig (const Options::Variables & vars) static
Construct particle selector config from user variables.
Definition at line 44 of file ParticleSelector.cpp.
View newest version in sPHENIX GitHub at line 44 of file ParticleSelector.cpp
References Acts::units::_GeV, Acts::units::_mm, FW::Options::Interval::lower, and name.
Member Data Documentation
Config FW::ParticleSelector::m_cfg private
Definition at line 62 of file ParticleSelector.hpp.
View newest version in sPHENIX GitHub at line 62 of file ParticleSelector.hpp
Referenced by ParticleSelector().
The documentation for this class was generated from the following files:
fun4all_acts/blob/master/Examples/Algorithms/Generators/ACTFW/Generators/ParticleSelector.hpp
fun4all_acts/blob/master/Examples/Algorithms/Generators/ACTFW/Generators/ParticleSelector.cpp