EIC Software: PndConstPar Class Reference
PndConstPar Class Reference
#include <EicRoot/blob/master/field/PndConstPar.h>
Public Member Functions
PndConstPar (const char *name, const char *title, const char *context)
PndConstPar ()
~PndConstPar ()
void putParams (FairParamList *list)
Bool_t getParams (FairParamList *list)
void SetParameters (FairField *field)
Double_t GetBx () const
Double_t GetBy () const
Double_t GetBz () const
Public Member Functions inherited from PndMapPar
PndMapPar (const char *name, const char *title, const char *context)
PndMapPar ()
~PndMapPar ()
void SetParameters (FairField *field)
Int_t GetType () const
Double_t GetXmin () const
Double_t GetXmax () const
Double_t GetYmin () const
Double_t GetYmax () const
Double_t GetZmin () const
Double_t GetZmax () const
void MapName (TString &name)
Double_t GetPositionX () const
Double_t GetPositionY () const
Double_t GetPositionZ () const
Double_t GetScale () const
Public Member Functions inherited from FairParGenericSet
FairParGenericSet (const char *name, const char *title, const char *context)
virtual ~FairParGenericSet ()
virtual void printParams ()
Bool_t init (FairParIo *inp)
Int_t write (FairParIo *output)
Public Member Functions inherited from FairParSet
FairParSet (const char *name="", const char *title="", const char *context="")
virtual ~FairParSet ()
virtual Bool_t init ()
virtual Int_t write ()
virtual void clear ()
virtual void print ()
const char * getDetectorName ()
void resetInputVersions ()
void setInputVersion (Int_t v=-1, Int_t i=0)
Int_t getInputVersion (Int_t i)
void setStatic (Bool_t flag=kTRUE)
Bool_t isStatic ()
void setChanged (Bool_t flag=kTRUE)
Bool_t hasChanged ()
const char * getParamContext () const
void setAuthor (const char *s)
const char * getAuthor () const
void setDescription (const char *s)
const char * getDescription () const
void copyComment (FairParSet &r)
Protected Member Functions
ClassDef (PndConstPar, 1)
Protected Member Functions inherited from PndMapPar
ClassDef (PndMapPar, 1)
Protected Member Functions inherited from FairParGenericSet
FairParGenericSet ()
Protected Attributes
Double_t fBx
Double_t fBy
Double_t fBz
Protected Attributes inherited from PndMapPar
Int_t fType
Double_t fXmin
Double_t fXmax
Double_t fYmin
Double_t fYmax
Double_t fZmin
Double_t fZmax
TString fMapName
Double_t fPosX
Double_t fPosY
Double_t fPosZ
Double_t fScale
Detailed Description
Definition at line 15 of file PndConstPar.h.
View newest version in sPHENIX GitHub at line 15 of file PndConstPar.h
Constructor & Destructor Documentation
PndConstPar::PndConstPar (const char * name, const char * title, const char * context)
Standard constructor
Definition at line 5 of file PndConstPar.cxx.
View newest version in sPHENIX GitHub at line 5 of file PndConstPar.cxx
References PndMapPar::fType.
PndConstPar::PndConstPar ()
default constructor
Definition at line 11 of file PndConstPar.cxx.
View newest version in sPHENIX GitHub at line 11 of file PndConstPar.cxx
References PndMapPar::fType.
PndConstPar::~PndConstPar ()
Destructor
Definition at line 17 of file PndConstPar.cxx.
View newest version in sPHENIX GitHub at line 17 of file PndConstPar.cxx
Member Function Documentation
PndConstPar::ClassDef (PndConstPar , 1) protected
Double_t PndConstPar::GetBx () const inline
Definition at line 41 of file PndConstPar.h.
View newest version in sPHENIX GitHub at line 41 of file PndConstPar.h
References fBx.
Referenced by PndConstField::PndConstField().
Double_t PndConstPar::GetBy () const inline
Definition at line 42 of file PndConstPar.h.
View newest version in sPHENIX GitHub at line 42 of file PndConstPar.h
References fBy.
Referenced by PndConstField::PndConstField().
Double_t PndConstPar::GetBz () const inline
Definition at line 43 of file PndConstPar.h.
View newest version in sPHENIX GitHub at line 43 of file PndConstPar.h
References fBz.
Referenced by PndConstField::PndConstField().
Bool_t PndConstPar::getParams (FairParamList * list) virtual
Get parameters
Reimplemented from PndMapPar.
Definition at line 39 of file PndConstPar.cxx.
View newest version in sPHENIX GitHub at line 39 of file PndConstPar.cxx
References fBx, fBy, fBz, FairParamList::fill(), PndMapPar::fType, PndMapPar::fXmax, PndMapPar::fXmin, PndMapPar::fYmax, PndMapPar::fYmin, PndMapPar::fZmax, and PndMapPar::fZmin.
void PndConstPar::putParams (FairParamList * list) virtual
Put parameters
Reimplemented from PndMapPar.
Definition at line 19 of file PndConstPar.cxx.
View newest version in sPHENIX GitHub at line 19 of file PndConstPar.cxx
References FairParamList::add(), fBx, fBy, fBz, PndMapPar::fType, PndMapPar::fXmax, PndMapPar::fXmin, PndMapPar::fYmax, PndMapPar::fYmin, PndMapPar::fZmax, and PndMapPar::fZmin.
void PndConstPar::SetParameters (FairField * field)
Set parameters from FairField
Definition at line 54 of file PndConstPar.cxx.
View newest version in sPHENIX GitHub at line 54 of file PndConstPar.cxx
References fBx, fBy, fBz, PndMapPar::fMapName, PndMapPar::fPosX, PndMapPar::fPosY, PndMapPar::fPosZ, PndMapPar::fScale, PndMapPar::fType, PndMapPar::fXmax, PndMapPar::fXmin, PndMapPar::fYmax, PndMapPar::fYmin, PndMapPar::fZmax, PndMapPar::fZmin, PndConstField::GetBx(), PndConstField::GetBy(), PndConstField::GetBz(), PndConstField::GetXmax(), PndConstField::GetXmin(), PndConstField::GetYmax(), PndConstField::GetYmin(), PndConstField::GetZmax(), and PndConstField::GetZmin().
Referenced by PndConstField::FillParContainer(), and PndMultiFieldPar::SetParameters().
Member Data Documentation
Double_t PndConstPar::fBx protected
Field values in [kG]
Definition at line 48 of file PndConstPar.h.
View newest version in sPHENIX GitHub at line 48 of file PndConstPar.h
Referenced by GetBx(), getParams(), putParams(), and SetParameters().
Double_t PndConstPar::fBy protected
Definition at line 48 of file PndConstPar.h.
View newest version in sPHENIX GitHub at line 48 of file PndConstPar.h
Referenced by GetBy(), getParams(), putParams(), and SetParameters().
Double_t PndConstPar::fBz protected
Definition at line 48 of file PndConstPar.h.
View newest version in sPHENIX GitHub at line 48 of file PndConstPar.h
Referenced by GetBz(), getParams(), putParams(), and SetParameters().
The documentation for this class was generated from the following files:
EicRoot/blob/master/field/PndConstPar.h
EicRoot/blob/master/field/PndConstPar.cxx