EIC Software: e_wideResonanceCrossSection Class Reference
e_wideResonanceCrossSection Class Reference
#include <estarlight/blob/master/include/e_wideResonanceCrossSection.h>
Public Member Functions
e_wideResonanceCrossSection (const inputParameters &input, const beamBeamSystem &bbsystem)
~e_wideResonanceCrossSection ()
void crossSectionCalculation (const double bwnormsave)
void makeGammaPQ2dependence (const double bwnormsave)
void printCrossSection (const std::string name, const double x_section)
Public Member Functions inherited from photonNucleusCrossSection
photonNucleusCrossSection (const inputParameters &input, const beamBeamSystem &bbsystem)
~photonNucleusCrossSection ()
double slopeParameter () const
returns slope of t-distribution [(GeV/c)^{-2}]
double getChannelMass () const
returns mass of the produced system [GeV/c^2]
double getBNORM () const
beamBeamSystem getbbs () const
returns beamBeamSystem
double vmPhotonCoupling () const
vectormeson-photon coupling constant f_v / 4 pi (cf. Eq. 10 in KN PRC 60 (1999) 014903)
double vmQ2Power (double Q2) const
double getDefaultC () const
double maxPhotonEnergy () const
returns max photon energy in lab frame [GeV] (for vectormesons only)
void crossSectionCalculation (const double bwnormsave)
double backwardsPropagationOmegaCrossSection (const double targetEgamma)
double getcsgA (const double Egamma, const double Q2, const int beam)
double e_getcsgA (const double Egamma, double Q2, const double W, const int beam)
double getcsgA_Q2_dep (const double Q2)
double photonFlux (const double Egamma, const int beam)
double photonFlux (const double Egamma, const double Q2)
double integrated_Q2_dep (const double Egamma, const double _min=0, const double _max=0)
double integrated_x_section (const double Egamma, const double _min=0, const double _max=0)
std::pair< double, double > * Q2arraylimits (double const Egamma)
double g (double const Egamma, double const Q2)
double sigmagp (const double Wgp)
double sigma_A (const double sig_N, const int beam)
double sigma_N (const double Wgp)
double breitWigner (const double W, const double C)
double nepoint (const double Egamma, const double bmin)
double getPhotonNucleusSigma () const
void setPhotonNucleusSigma (double sigma)
Private Attributes
double _wideWmax
double _wideWmin
double _targetMaxPhotonEnergy
double _targetMinPhotonEnergy
double _Ep
double _electronEnergy
double _target_beamLorentz
double _VMnumEgamma
double _useFixedRange
double _gammaMinQ2
double _gammaMaxQ2
double _targetRadii
Additional Inherited Members
Protected Attributes inherited from photonNucleusCrossSection
const unsigned int _nWbins
const unsigned int _nYbins
const double _wMin
const double _wMax
const double _yMax
const double _beamLorentzGamma
double _photonNucleusSigma
int _printDef
int _impulseSelected
int _quantumGlauber
Detailed Description
Definition at line 41 of file e_wideResonanceCrossSection.h.
View newest version in sPHENIX GitHub at line 41 of file e_wideResonanceCrossSection.h
Constructor & Destructor Documentation
e_wideResonanceCrossSection::e_wideResonanceCrossSection (const inputParameters & input, const beamBeamSystem & bbsystem)
Definition at line 47 of file e_wideResonanceCrossSection.cpp.
View newest version in sPHENIX GitHub at line 47 of file e_wideResonanceCrossSection.cpp
References _electronEnergy, _Ep, _gammaMaxQ2, _gammaMinQ2, _target_beamLorentz, _targetMaxPhotonEnergy, _targetMinPhotonEnergy, _targetRadii, _useFixedRange, _VMnumEgamma, _wideWmax, _wideWmin, photonNucleusCrossSection::_wMax, photonNucleusCrossSection::_wMin, inputParameters::beamLorentzGamma(), inputParameters::electronEnergy(), inputParameters::fixedQ2Range(), inputParameters::maxGammaQ2(), inputParameters::minGammaQ2(), inputParameters::nmbEnergyBins(), inputParameters::protonEnergy(), inputParameters::targetMaxPhotonEnergy(), inputParameters::targetMinPhotonEnergy(), and inputParameters::targetRadius().
e_wideResonanceCrossSection::~e_wideResonanceCrossSection ()
Definition at line 66 of file e_wideResonanceCrossSection.cpp.
View newest version in sPHENIX GitHub at line 66 of file e_wideResonanceCrossSection.cpp
Member Function Documentation
void e_wideResonanceCrossSection::crossSectionCalculation (const double bwnormsave)
Definition at line 74 of file e_wideResonanceCrossSection.cpp.
View newest version in sPHENIX GitHub at line 74 of file e_wideResonanceCrossSection.cpp
References _electronEnergy, _gammaMaxQ2, _gammaMinQ2, _targetMaxPhotonEnergy, _targetMinPhotonEnergy, _useFixedRange, _wideWmax, _wideWmin, nucleus::A(), photonNucleusCrossSection::breitWigner(), beamBeamSystem::electronBeam(), photonNucleusCrossSection::g(), photonNucleusCrossSection::getbbs(), photonNucleusCrossSection::getBNORM(), photonNucleusCrossSection::getcsgA(), photonNucleusCrossSection::getcsgA_Q2_dep(), makeGammaPQ2dependence(), starlightConstants::mel, photonNucleusCrossSection::photonFlux(), printCrossSection(), photonNucleusCrossSection::setPhotonNucleusSigma(), and beamBeamSystem::targetBeam().
Referenced by e_Gammaawidevm::e_Gammaawidevm().
void e_wideResonanceCrossSection::makeGammaPQ2dependence (const double bwnormsave)
Referenced by crossSectionCalculation().
void e_wideResonanceCrossSection::printCrossSection (const std::string name, const double x_section)
Definition at line 328 of file e_wideResonanceCrossSection.cpp.
View newest version in sPHENIX GitHub at line 328 of file e_wideResonanceCrossSection.cpp
Referenced by crossSectionCalculation().
Member Data Documentation
double e_wideResonanceCrossSection::_electronEnergy private
Definition at line 58 of file e_wideResonanceCrossSection.h.
View newest version in sPHENIX GitHub at line 58 of file e_wideResonanceCrossSection.h
Referenced by crossSectionCalculation(), and e_wideResonanceCrossSection().
double e_wideResonanceCrossSection::_Ep private
Definition at line 57 of file e_wideResonanceCrossSection.h.
View newest version in sPHENIX GitHub at line 57 of file e_wideResonanceCrossSection.h
Referenced by e_wideResonanceCrossSection().
double e_wideResonanceCrossSection::_gammaMaxQ2 private
Definition at line 63 of file e_wideResonanceCrossSection.h.
View newest version in sPHENIX GitHub at line 63 of file e_wideResonanceCrossSection.h
Referenced by crossSectionCalculation(), and e_wideResonanceCrossSection().
double e_wideResonanceCrossSection::_gammaMinQ2 private
Definition at line 62 of file e_wideResonanceCrossSection.h.
View newest version in sPHENIX GitHub at line 62 of file e_wideResonanceCrossSection.h
Referenced by crossSectionCalculation(), and e_wideResonanceCrossSection().
double e_wideResonanceCrossSection::_target_beamLorentz private
Definition at line 59 of file e_wideResonanceCrossSection.h.
View newest version in sPHENIX GitHub at line 59 of file e_wideResonanceCrossSection.h
Referenced by e_wideResonanceCrossSection().
double e_wideResonanceCrossSection::_targetMaxPhotonEnergy private
Definition at line 55 of file e_wideResonanceCrossSection.h.
View newest version in sPHENIX GitHub at line 55 of file e_wideResonanceCrossSection.h
Referenced by crossSectionCalculation(), and e_wideResonanceCrossSection().
double e_wideResonanceCrossSection::_targetMinPhotonEnergy private
Definition at line 56 of file e_wideResonanceCrossSection.h.
View newest version in sPHENIX GitHub at line 56 of file e_wideResonanceCrossSection.h
Referenced by crossSectionCalculation(), and e_wideResonanceCrossSection().
double e_wideResonanceCrossSection::_targetRadii private
Definition at line 64 of file e_wideResonanceCrossSection.h.
View newest version in sPHENIX GitHub at line 64 of file e_wideResonanceCrossSection.h
Referenced by e_wideResonanceCrossSection().
double e_wideResonanceCrossSection::_useFixedRange private
Definition at line 61 of file e_wideResonanceCrossSection.h.
View newest version in sPHENIX GitHub at line 61 of file e_wideResonanceCrossSection.h
Referenced by crossSectionCalculation(), and e_wideResonanceCrossSection().
double e_wideResonanceCrossSection::_VMnumEgamma private
Definition at line 60 of file e_wideResonanceCrossSection.h.
View newest version in sPHENIX GitHub at line 60 of file e_wideResonanceCrossSection.h
Referenced by e_wideResonanceCrossSection().
double e_wideResonanceCrossSection::_wideWmax private
Definition at line 53 of file e_wideResonanceCrossSection.h.
View newest version in sPHENIX GitHub at line 53 of file e_wideResonanceCrossSection.h
Referenced by crossSectionCalculation(), and e_wideResonanceCrossSection().
double e_wideResonanceCrossSection::_wideWmin private
Definition at line 54 of file e_wideResonanceCrossSection.h.
View newest version in sPHENIX GitHub at line 54 of file e_wideResonanceCrossSection.h
Referenced by crossSectionCalculation(), and e_wideResonanceCrossSection().
The documentation for this class was generated from the following files:
estarlight/blob/master/include/e_wideResonanceCrossSection.h
estarlight/blob/master/src/e_wideResonanceCrossSection.cpp