EIC Software: FairDbResultPtr< T > Class Template Reference
FairDbResultPtr< T > Class Template Reference
#include <EicRoot/blob/master/dbase/dbInterface/FairDbResPtr.h>
Public Member Functions
FairDbResultPtr ()
FairDbResultPtr (const FairDbResultPtr &that)
FairDbResultPtr (const ValContext &vc, FairDb::Task task=FairDb::kDefaultTask, FairDb::AbortTest abortTest=FairDb::kTableMissing, Bool_t findFullTimeWindow=true)
FairDbResultPtr (const string &tableName, const ValContext &vc, FairDb::Task task=FairDb::kDefaultTask, FairDb::AbortTest abortTest=FairDb::kTableMissing, Bool_t findFullTimeWindow=true)
FairDbResultPtr (const string &tableName, const FairDbSqlContext &context, const FairDb::Task &task=FairDb::kAnyTask, const string &data="", const string &fillOpts="", FairDb::AbortTest abortTest=FairDb::kTableMissing)
FairDbResultPtr (const string &tableName, const FairDbValidityRec &vrec, FairDb::AbortTest abortTest=FairDb::kTableMissing)
FairDbResultPtr (const string &tableName, UInt_t seqNo, UInt_t dbNo, FairDb::AbortTest abortTest=FairDb::kTableMissing)
virtual ~FairDbResultPtr ()
const FairDbResultKey * GetKey () const
UInt_t GetNumRows () const
const FairDbResult * GetResult () const
Int_t GetResultID () const
const T * GetRow (UInt_t rowNum) const
const T * GetRowByIndex (UInt_t index) const
const FairDbValidityRec * GetValidityRec (const FairDbTableRow *row=0) const
FairDbTableProxy & TableProxy () const
Bool_t ResultsFromDb () const
UInt_t NextQuery (Bool_t forwards=kTRUE)
UInt_t NewQuery (ValContext vc, FairDb::Task task=0, Bool_t findFullTimeWindow=true)
UInt_t NewQuery (const FairDbSqlContext &context, const FairDb::Task &task=0, const string &data="", const string &fillOpts="")
UInt_t NewQuery (const FairDbValidityRec &vrec)
UInt_t NewQuery (UInt_t seqNo, UInt_t dbNo)
Static Public Member Functions
static FairDbTableProxy & GetTableProxy ()
static FairDbTableProxy & GetTableProxy (const string &tableName)
Private Member Functions
void Disconnect ()
void SetContext (const FairDbValidityRec &vrec)
Bool_t ApplyAbortTest ()
FairDbResultPtr & operator= (const FairDbResultPtr &)
Private Attributes
FairDb::AbortTest fAbortTest
FairDbTableProxy & fTableProxy
const FairDbResult * fResult
Detector::Detector_t fDetType
SimFlag::SimFlag_t fSimType
Static Private Attributes
static std::map< string,
FairDbTableProxy * > fgNameToProxy
static FairDbTableProxy * fgTableProxy
Detailed Description
template<class T>
class FairDbResultPtr< T >
Definition at line 18 of file FairDbResPtr.h.
View newest version in sPHENIX GitHub at line 18 of file FairDbResPtr.h
Constructor & Destructor Documentation
template<class T> FairDbResultPtr< T >::FairDbResultPtr ()
template<class T> FairDbResultPtr< T >::FairDbResultPtr (const FairDbResultPtr< T > & that)
template<class T> FairDbResultPtr< T >::FairDbResultPtr (const ValContext & vc, FairDb::Task task = FairDb::kDefaultTask, FairDb::AbortTest abortTest = FairDb::kTableMissing, Bool_t findFullTimeWindow = true)
template<class T> FairDbResultPtr< T >::FairDbResultPtr (const string & tableName, const ValContext & vc, FairDb::Task task = FairDb::kDefaultTask, FairDb::AbortTest abortTest = FairDb::kTableMissing, Bool_t findFullTimeWindow = true)
template<class T> FairDbResultPtr< T >::FairDbResultPtr (const string & tableName, const FairDbSqlContext & context, const FairDb::Task & task = FairDb::kAnyTask, const string & data = "", const string & fillOpts = "", FairDb::AbortTest abortTest = FairDb::kTableMissing)
template<class T> FairDbResultPtr< T >::FairDbResultPtr (const string & tableName, const FairDbValidityRec & vrec, FairDb::AbortTest abortTest = FairDb::kTableMissing)
template<class T> FairDbResultPtr< T >::FairDbResultPtr (const string & tableName, UInt_t seqNo, UInt_t dbNo, FairDb::AbortTest abortTest = FairDb::kTableMissing)
template<class T> virtual FairDbResultPtr< T >::~FairDbResultPtr () virtual
Member Function Documentation
template<class T> Bool_t FairDbResultPtr< T >::ApplyAbortTest () private
template<class T> void FairDbResultPtr< T >::Disconnect () private
template<class T> const FairDbResultKey* FairDbResultPtr< T >::GetKey () const
template<class T> UInt_t FairDbResultPtr< T >::GetNumRows () const
Referenced by FairDbConfigStream::FairDbConfigStream().
template<class T> const FairDbResult* FairDbResultPtr< T >::GetResult () const inline
Definition at line 54 of file FairDbResPtr.h.
View newest version in sPHENIX GitHub at line 54 of file FairDbResPtr.h
template<class T> Int_t FairDbResultPtr< T >::GetResultID () const
template<class T> const T* FairDbResultPtr< T >::GetRow (UInt_t rowNum) const
Referenced by FairDbConfigStream::FairDbConfigStream().
template<class T> const T* FairDbResultPtr< T >::GetRowByIndex (UInt_t index) const
template<class T> static FairDbTableProxy& FairDbResultPtr< T >::GetTableProxy () static
template<class T> static FairDbTableProxy& FairDbResultPtr< T >::GetTableProxy (const string & tableName) static
template<class T> const FairDbValidityRec* FairDbResultPtr< T >::GetValidityRec (const FairDbTableRow * row = 0) const
Referenced by FairDbConfigStream::FairDbConfigStream().
template<class T> UInt_t FairDbResultPtr< T >::NewQuery (ValContext vc, FairDb::Task task = 0, Bool_t findFullTimeWindow = true)
template<class T> UInt_t FairDbResultPtr< T >::NewQuery (const FairDbSqlContext & context, const FairDb::Task & task = 0, const string & data = "", const string & fillOpts = "")
template<class T> UInt_t FairDbResultPtr< T >::NewQuery (const FairDbValidityRec & vrec)
template<class T> UInt_t FairDbResultPtr< T >::NewQuery (UInt_t seqNo, UInt_t dbNo)
template<class T> UInt_t FairDbResultPtr< T >::NextQuery (Bool_t forwards = kTRUE)
template<class T> FairDbResultPtr& FairDbResultPtr< T >::operator= (const FairDbResultPtr< T > &) private
template<class T> Bool_t FairDbResultPtr< T >::ResultsFromDb () const
template<class T> void FairDbResultPtr< T >::SetContext (const FairDbValidityRec & vrec) private
template<class T> FairDbTableProxy& FairDbResultPtr< T >::TableProxy () const
Member Data Documentation
template<class T> FairDb::AbortTest FairDbResultPtr< T >::fAbortTest private
Definition at line 85 of file FairDbResPtr.h.
View newest version in sPHENIX GitHub at line 85 of file FairDbResPtr.h
template<class T> Detector::Detector_t FairDbResultPtr< T >::fDetType private
Definition at line 88 of file FairDbResPtr.h.
View newest version in sPHENIX GitHub at line 88 of file FairDbResPtr.h
template<class T> std::map<string,FairDbTableProxy*> FairDbResultPtr< T >::fgNameToProxy static private
Definition at line 92 of file FairDbResPtr.h.
View newest version in sPHENIX GitHub at line 92 of file FairDbResPtr.h
template<class T> FairDbTableProxy* FairDbResultPtr< T >::fgTableProxy static private
Definition at line 94 of file FairDbResPtr.h.
View newest version in sPHENIX GitHub at line 94 of file FairDbResPtr.h
template<class T> const FairDbResult* FairDbResultPtr< T >::fResult private
Definition at line 87 of file FairDbResPtr.h.
View newest version in sPHENIX GitHub at line 87 of file FairDbResPtr.h
Referenced by FairDbResultPtr< FairDbConfigSet >::GetResult().
template<class T> SimFlag::SimFlag_t FairDbResultPtr< T >::fSimType private
Definition at line 89 of file FairDbResPtr.h.
View newest version in sPHENIX GitHub at line 89 of file FairDbResPtr.h
template<class T> FairDbTableProxy& FairDbResultPtr< T >::fTableProxy private
Definition at line 86 of file FairDbResPtr.h.
View newest version in sPHENIX GitHub at line 86 of file FairDbResPtr.h
The documentation for this class was generated from the following file:
EicRoot/blob/master/dbase/dbInterface/FairDbResPtr.h