EIC Software: CbmRichTrainAnnSelect Class Reference
CbmRichTrainAnnSelect Class Reference
Train ANN for fake rejection.
#include <EicRoot/blob/master/rich/CbmRichTrainAnnSelect.h>
Public Member Functions
CbmRichTrainAnnSelect ()
Default constructor.
virtual ~CbmRichTrainAnnSelect ()
Destructor.
virtual InitStatus Init ()
Inherited from FairTask.
virtual void Exec (Option_t *option)
Inherited from FairTask.
virtual void FinishTask ()
Inherited from FairTask.
Public Member Functions inherited from FairTask
FairTask ()
FairTask (const char *name, Int_t iVerbose=1)
virtual ~FairTask ()
void InitTask ()
void ReInitTask ()
void SetParTask ()
virtual void FinishEvent ()
void SetVerbose (Int_t iVerbose)
void SetInputPersistance (Bool_t val)
void CheckInputPersistance (TString branchName)
Private Member Functions
void SetRecFlag ()
Set recFlag weather ring was found correctly or not.
void DiffFakeTrueCircle ()
Fill ring selection parameters in array and histograms.
void TrainAndTestAnn ()
Train and test ANN.
void Draw ()
Draw results.
CbmRichTrainAnnSelect (const CbmRichTrainAnnSelect &)
Copy constructor.
CbmRichTrainAnnSelect & operator= (const CbmRichTrainAnnSelect &)
Assignment operator.
Private Attributes
TClonesArray * fRichRings
TClonesArray * fMcTracks
TClonesArray * fRichRingMatches
Int_t fEventNumber
Double_t fQuota
Int_t fMaxNofTrainSamples
Int_t fNofFakeLikeTrue
Int_t fNofTrueLikeFake
Double_t fAnnCut
vector< TH1D * > fhNofHits
vector< TH1D * > fhAngle
vector< TH1D * > fhNofHitsOnRing
vector< TH1D * > fhChi2
vector< TH1D * > fhRadPos
vector< TH1D * > fhRadius
vector< TH1D * > fhAnnOutput
vector< TH1D * > fhCumProb
vector< vector< RingSelectParam > > fRSParams
CbmRichRingFitterCOP * fFitCOP
CbmRichRingSelectImpl * fSelectImpl
vector< TH1 * > fHists
Additional Inherited Members
Protected Member Functions inherited from FairTask
virtual InitStatus ReInit ()
virtual void SetParContainers ()
virtual void Finish ()
void InitTasks ()
void ReInitTasks ()
void SetParTasks ()
void FinishTasks ()
void FinishEvents ()
Protected Attributes inherited from FairTask
Int_t fVerbose
Int_t fInputPersistance
Indicates if input branch is persistant.
FairLogger * fLogger
Detailed Description
Train ANN for fake rejection.
Author
Semen Lebedev s.leb.nosp@m.edev.nosp@m.@gsi..nosp@m.de
Date
2005
Definition at line 53 of file CbmRichTrainAnnSelect.h.
View newest version in sPHENIX GitHub at line 53 of file CbmRichTrainAnnSelect.h
Constructor & Destructor Documentation
CbmRichTrainAnnSelect::CbmRichTrainAnnSelect ()
Default constructor.
Definition at line 36 of file CbmRichTrainAnnSelect.cxx.
View newest version in sPHENIX GitHub at line 36 of file CbmRichTrainAnnSelect.cxx
References fhAngle, fhAnnOutput, fhChi2, fhCumProb, fHists, fhNofHits, fhNofHitsOnRing, fhRadius, fhRadPos, and fRSParams.
CbmRichTrainAnnSelect::~CbmRichTrainAnnSelect () virtual
Destructor.
Definition at line 100 of file CbmRichTrainAnnSelect.cxx.
View newest version in sPHENIX GitHub at line 100 of file CbmRichTrainAnnSelect.cxx
CbmRichTrainAnnSelect::CbmRichTrainAnnSelect (const CbmRichTrainAnnSelect &) private
Copy constructor.
Member Function Documentation
void CbmRichTrainAnnSelect::DiffFakeTrueCircle () private
Fill ring selection parameters in array and histograms.
Definition at line 184 of file CbmRichTrainAnnSelect.cxx.
View newest version in sPHENIX GitHub at line 184 of file CbmRichTrainAnnSelect.cxx
References CbmRichConverter::CopyHitsToRingLight(), CbmRichRingFitterCOP::DoFit(), RingSelectParam::fAngle, RingSelectParam::fChi2, fFitCOP, fhAngle, fhChi2, RingSelectParam::fHitsOnRing, fhNofHits, fhNofHitsOnRing, fhRadius, fhRadPos, RingSelectParam::fNofHits, RingSelectParam::fRadius, RingSelectParam::fRadPos, fRichRingMatches, fRichRings, fRSParams, fSelectImpl, CbmRichRingSelectImpl::GetAngle(), CbmRichRingLight::GetChi2(), CbmRichRingLight::GetNofHits(), CbmRichRingSelectImpl::GetNofHitsOnRingCircle(), CbmRichRingLight::GetRadialPosition(), CbmRichRingLight::GetRadius(), CbmRichRing::GetRecFlag(), p, and G4BECAL::radius.
Referenced by Exec().
void CbmRichTrainAnnSelect::Draw () private
Draw results.
Definition at line 309 of file CbmRichTrainAnnSelect.cxx.
View newest version in sPHENIX GitHub at line 309 of file CbmRichTrainAnnSelect.cxx
References c1, c2, c3, DrawH1(), fAnnCut, fhAngle, fhAnnOutput, fhChi2, fhCumProb, fhNofHits, fhNofHitsOnRing, fhRadius, fhRadPos, fNofFakeLikeTrue, fNofTrueLikeFake, fRSParams, kLinear, and kLog.
Referenced by FinishTask().
void CbmRichTrainAnnSelect::Exec (Option_t * option) virtual
Inherited from FairTask.
Definition at line 127 of file CbmRichTrainAnnSelect.cxx.
View newest version in sPHENIX GitHub at line 127 of file CbmRichTrainAnnSelect.cxx
References DiffFakeTrueCircle(), fEventNumber, fRSParams, and SetRecFlag().
void CbmRichTrainAnnSelect::FinishTask () virtual
Inherited from FairTask.
Reimplemented from FairTask.
Definition at line 353 of file CbmRichTrainAnnSelect.cxx.
View newest version in sPHENIX GitHub at line 353 of file CbmRichTrainAnnSelect.cxx
References Draw(), fFitCOP, fHists, fSelectImpl, rich(), and TrainAndTestAnn().
InitStatus CbmRichTrainAnnSelect::Init (void) virtual
Inherited from FairTask.
Reimplemented from FairTask.
Definition at line 105 of file CbmRichTrainAnnSelect.cxx.
View newest version in sPHENIX GitHub at line 105 of file CbmRichTrainAnnSelect.cxx
References fFitCOP, fMcTracks, fRichRingMatches, fRichRings, fSelectImpl, FairRootManager::GetObject(), CbmRichConverter::Init(), FairRootManager::Instance(), and kSUCCESS.
CbmRichTrainAnnSelect& CbmRichTrainAnnSelect::operator= (const CbmRichTrainAnnSelect &) private
Assignment operator.
void CbmRichTrainAnnSelect::SetRecFlag () private
Set recFlag weather ring was found correctly or not.
Definition at line 140 of file CbmRichTrainAnnSelect.cxx.
View newest version in sPHENIX GitHub at line 140 of file CbmRichTrainAnnSelect.cxx
References fMcTracks, fQuota, fRichRingMatches, fRichRings, CbmTrackMatch::GetMCTrackId(), CbmMCTrack::GetMotherId(), CbmTrackMatch::GetNofFakeHits(), CbmTrackMatch::GetNofTrueHits(), CbmTrackMatch::GetNofWrongHits(), CbmMCTrack::GetPdgCode(), and CbmRichRing::SetRecFlag().
Referenced by Exec().
void CbmRichTrainAnnSelect::TrainAndTestAnn () private
Train and test ANN.
Definition at line 237 of file CbmRichTrainAnnSelect.cxx.
View newest version in sPHENIX GitHub at line 237 of file CbmRichTrainAnnSelect.cxx
References fAnnCut, fhAnnOutput, fMaxNofTrainSamples, fNofFakeLikeTrue, fNofTrueLikeFake, fRSParams, k, and x.
Referenced by FinishTask().
Member Data Documentation
Double_t CbmRichTrainAnnSelect::fAnnCut private
Definition at line 93 of file CbmRichTrainAnnSelect.h.
View newest version in sPHENIX GitHub at line 93 of file CbmRichTrainAnnSelect.h
Referenced by Draw(), and TrainAndTestAnn().
Int_t CbmRichTrainAnnSelect::fEventNumber private
Definition at line 88 of file CbmRichTrainAnnSelect.h.
View newest version in sPHENIX GitHub at line 88 of file CbmRichTrainAnnSelect.h
Referenced by Exec().
CbmRichRingFitterCOP* CbmRichTrainAnnSelect::fFitCOP private
Definition at line 113 of file CbmRichTrainAnnSelect.h.
View newest version in sPHENIX GitHub at line 113 of file CbmRichTrainAnnSelect.h
Referenced by DiffFakeTrueCircle(), FinishTask(), and Init().
vector<TH1D*> CbmRichTrainAnnSelect::fhAngle private
Definition at line 98 of file CbmRichTrainAnnSelect.h.
View newest version in sPHENIX GitHub at line 98 of file CbmRichTrainAnnSelect.h
Referenced by CbmRichTrainAnnSelect(), DiffFakeTrueCircle(), and Draw().
vector<TH1D*> CbmRichTrainAnnSelect::fhAnnOutput private
Definition at line 106 of file CbmRichTrainAnnSelect.h.
View newest version in sPHENIX GitHub at line 106 of file CbmRichTrainAnnSelect.h
Referenced by CbmRichTrainAnnSelect(), Draw(), and TrainAndTestAnn().
vector<TH1D*> CbmRichTrainAnnSelect::fhChi2 private
Definition at line 100 of file CbmRichTrainAnnSelect.h.
View newest version in sPHENIX GitHub at line 100 of file CbmRichTrainAnnSelect.h
Referenced by CbmRichTrainAnnSelect(), DiffFakeTrueCircle(), and Draw().
vector<TH1D*> CbmRichTrainAnnSelect::fhCumProb private
Definition at line 107 of file CbmRichTrainAnnSelect.h.
View newest version in sPHENIX GitHub at line 107 of file CbmRichTrainAnnSelect.h
Referenced by CbmRichTrainAnnSelect(), and Draw().
vector<TH1*> CbmRichTrainAnnSelect::fHists private
Definition at line 116 of file CbmRichTrainAnnSelect.h.
View newest version in sPHENIX GitHub at line 116 of file CbmRichTrainAnnSelect.h
Referenced by CbmRichTrainAnnSelect(), and FinishTask().
vector<TH1D*> CbmRichTrainAnnSelect::fhNofHits private
Definition at line 97 of file CbmRichTrainAnnSelect.h.
View newest version in sPHENIX GitHub at line 97 of file CbmRichTrainAnnSelect.h
Referenced by CbmRichTrainAnnSelect(), DiffFakeTrueCircle(), and Draw().
vector<TH1D*> CbmRichTrainAnnSelect::fhNofHitsOnRing private
Definition at line 99 of file CbmRichTrainAnnSelect.h.
View newest version in sPHENIX GitHub at line 99 of file CbmRichTrainAnnSelect.h
Referenced by CbmRichTrainAnnSelect(), DiffFakeTrueCircle(), and Draw().
vector<TH1D*> CbmRichTrainAnnSelect::fhRadius private
Definition at line 102 of file CbmRichTrainAnnSelect.h.
View newest version in sPHENIX GitHub at line 102 of file CbmRichTrainAnnSelect.h
Referenced by CbmRichTrainAnnSelect(), DiffFakeTrueCircle(), and Draw().
vector<TH1D*> CbmRichTrainAnnSelect::fhRadPos private
Definition at line 101 of file CbmRichTrainAnnSelect.h.
View newest version in sPHENIX GitHub at line 101 of file CbmRichTrainAnnSelect.h
Referenced by CbmRichTrainAnnSelect(), DiffFakeTrueCircle(), and Draw().
Int_t CbmRichTrainAnnSelect::fMaxNofTrainSamples private
Definition at line 90 of file CbmRichTrainAnnSelect.h.
View newest version in sPHENIX GitHub at line 90 of file CbmRichTrainAnnSelect.h
Referenced by TrainAndTestAnn().
TClonesArray* CbmRichTrainAnnSelect::fMcTracks private
Definition at line 85 of file CbmRichTrainAnnSelect.h.
View newest version in sPHENIX GitHub at line 85 of file CbmRichTrainAnnSelect.h
Referenced by Init(), and SetRecFlag().
Int_t CbmRichTrainAnnSelect::fNofFakeLikeTrue private
Definition at line 91 of file CbmRichTrainAnnSelect.h.
View newest version in sPHENIX GitHub at line 91 of file CbmRichTrainAnnSelect.h
Referenced by Draw(), and TrainAndTestAnn().
Int_t CbmRichTrainAnnSelect::fNofTrueLikeFake private
Definition at line 92 of file CbmRichTrainAnnSelect.h.
View newest version in sPHENIX GitHub at line 92 of file CbmRichTrainAnnSelect.h
Referenced by Draw(), and TrainAndTestAnn().
Double_t CbmRichTrainAnnSelect::fQuota private
Definition at line 89 of file CbmRichTrainAnnSelect.h.
View newest version in sPHENIX GitHub at line 89 of file CbmRichTrainAnnSelect.h
Referenced by SetRecFlag().
TClonesArray* CbmRichTrainAnnSelect::fRichRingMatches private
Definition at line 86 of file CbmRichTrainAnnSelect.h.
View newest version in sPHENIX GitHub at line 86 of file CbmRichTrainAnnSelect.h
Referenced by DiffFakeTrueCircle(), Init(), and SetRecFlag().
TClonesArray* CbmRichTrainAnnSelect::fRichRings private
Definition at line 84 of file CbmRichTrainAnnSelect.h.
View newest version in sPHENIX GitHub at line 84 of file CbmRichTrainAnnSelect.h
Referenced by DiffFakeTrueCircle(), Init(), and SetRecFlag().
vector<vector<RingSelectParam> > CbmRichTrainAnnSelect::fRSParams private
Definition at line 111 of file CbmRichTrainAnnSelect.h.
View newest version in sPHENIX GitHub at line 111 of file CbmRichTrainAnnSelect.h
Referenced by CbmRichTrainAnnSelect(), DiffFakeTrueCircle(), Draw(), Exec(), and TrainAndTestAnn().
CbmRichRingSelectImpl* CbmRichTrainAnnSelect::fSelectImpl private
Definition at line 114 of file CbmRichTrainAnnSelect.h.
View newest version in sPHENIX GitHub at line 114 of file CbmRichTrainAnnSelect.h
Referenced by DiffFakeTrueCircle(), FinishTask(), and Init().
The documentation for this class was generated from the following files:
EicRoot/blob/master/rich/CbmRichTrainAnnSelect.h
EicRoot/blob/master/rich/CbmRichTrainAnnSelect.cxx