EIC Software: e_narrowResonanceCrossSection Class Reference
e_narrowResonanceCrossSection Class Reference
#include <estarlight/blob/master/include/e_narrowResonanceCrossSection.h>
Public Member Functions
e_narrowResonanceCrossSection (const inputParameters &input, const beamBeamSystem &bbsystem)
~e_narrowResonanceCrossSection ()
void crossSectionCalculation (const double bwnormsave)
void makeGammaPQ2dependence ()
void printCrossSection (const std::string name, const double x_section)
Public Member Functions inherited from photonNucleusCrossSection
photonNucleusCrossSection (const inputParameters &input, const beamBeamSystem &bbsystem)
~photonNucleusCrossSection ()
double slopeParameter () const
returns slope of t-distribution [(GeV/c)^{-2}]
double getChannelMass () const
returns mass of the produced system [GeV/c^2]
double getBNORM () const
beamBeamSystem getbbs () const
returns beamBeamSystem
double vmPhotonCoupling () const
vectormeson-photon coupling constant f_v / 4 pi (cf. Eq. 10 in KN PRC 60 (1999) 014903)
double vmQ2Power (double Q2) const
double getDefaultC () const
double maxPhotonEnergy () const
returns max photon energy in lab frame [GeV] (for vectormesons only)
void crossSectionCalculation (const double bwnormsave)
double backwardsPropagationOmegaCrossSection (const double targetEgamma)
double getcsgA (const double Egamma, const double Q2, const int beam)
double e_getcsgA (const double Egamma, double Q2, const double W, const int beam)
double getcsgA_Q2_dep (const double Q2)
double photonFlux (const double Egamma, const int beam)
double photonFlux (const double Egamma, const double Q2)
double integrated_Q2_dep (const double Egamma, const double _min=0, const double _max=0)
double integrated_x_section (const double Egamma, const double _min=0, const double _max=0)
std::pair< double, double > * Q2arraylimits (double const Egamma)
double g (double const Egamma, double const Q2)
double sigmagp (const double Wgp)
double sigma_A (const double sig_N, const int beam)
double sigma_N (const double Wgp)
double breitWigner (const double W, const double C)
double nepoint (const double Egamma, const double bmin)
double getPhotonNucleusSigma () const
void setPhotonNucleusSigma (double sigma)
Private Attributes
double _Ep
double _electronEnergy
double _target_beamLorentz
double _boost
double _targetMaxPhotonEnergy
double _targetMinPhotonEnergy
double _cmsMaxPhotonEnergy
double _cmsMinPhotonEnergy
double _VMnumEgamma
double _useFixedRange
double _gammaMinQ2
double _gammaMaxQ2
double _targetRadii
bool _backwardsProduction
Additional Inherited Members
Protected Attributes inherited from photonNucleusCrossSection
const unsigned int _nWbins
const unsigned int _nYbins
const double _wMin
const double _wMax
const double _yMax
const double _beamLorentzGamma
double _photonNucleusSigma
int _printDef
int _impulseSelected
int _quantumGlauber
Detailed Description
Definition at line 41 of file e_narrowResonanceCrossSection.h.
View newest version in sPHENIX GitHub at line 41 of file e_narrowResonanceCrossSection.h
Constructor & Destructor Documentation
e_narrowResonanceCrossSection::e_narrowResonanceCrossSection (const inputParameters & input, const beamBeamSystem & bbsystem)
Definition at line 46 of file e_narrowResonanceCrossSection.cpp.
View newest version in sPHENIX GitHub at line 46 of file e_narrowResonanceCrossSection.cpp
References _backwardsProduction, _boost, _cmsMaxPhotonEnergy, _cmsMinPhotonEnergy, _electronEnergy, _Ep, _gammaMaxQ2, _gammaMinQ2, _target_beamLorentz, _targetMaxPhotonEnergy, _targetMinPhotonEnergy, _targetRadii, _useFixedRange, _VMnumEgamma, inputParameters::backwardsProduction(), inputParameters::beamLorentzGamma(), inputParameters::cmsMaxPhotonEnergy(), inputParameters::cmsMinPhotonEnergy(), inputParameters::electronBeamLorentzGamma(), inputParameters::electronEnergy(), inputParameters::fixedQ2Range(), inputParameters::maxGammaQ2(), inputParameters::minGammaQ2(), inputParameters::nmbEnergyBins(), inputParameters::protonEnergy(), inputParameters::targetBeamLorentzGamma(), inputParameters::targetMaxPhotonEnergy(), inputParameters::targetMinPhotonEnergy(), and inputParameters::targetRadius().
e_narrowResonanceCrossSection::~e_narrowResonanceCrossSection ()
Definition at line 73 of file e_narrowResonanceCrossSection.cpp.
View newest version in sPHENIX GitHub at line 73 of file e_narrowResonanceCrossSection.cpp
Member Function Documentation
void e_narrowResonanceCrossSection::crossSectionCalculation (const double bwnormsave)
Definition at line 79 of file e_narrowResonanceCrossSection.cpp.
View newest version in sPHENIX GitHub at line 79 of file e_narrowResonanceCrossSection.cpp
References _backwardsProduction, _cmsMinPhotonEnergy, _electronEnergy, _gammaMaxQ2, _gammaMinQ2, _targetMaxPhotonEnergy, _targetMinPhotonEnergy, _useFixedRange, nucleus::A(), beamBeamSystem::electronBeam(), photonNucleusCrossSection::g(), photonNucleusCrossSection::getbbs(), photonNucleusCrossSection::getcsgA(), photonNucleusCrossSection::getcsgA_Q2_dep(), makeGammaPQ2dependence(), starlightConstants::mel, photonNucleusCrossSection::photonFlux(), printCrossSection(), printf(), photonNucleusCrossSection::setPhotonNucleusSigma(), and beamBeamSystem::targetBeam().
Referenced by e_Gammaanarrowvm::e_Gammaanarrowvm().
void e_narrowResonanceCrossSection::makeGammaPQ2dependence ()
Definition at line 220 of file e_narrowResonanceCrossSection.cpp.
View newest version in sPHENIX GitHub at line 220 of file e_narrowResonanceCrossSection.cpp
References _targetMaxPhotonEnergy, _targetMinPhotonEnergy, nucleus::A(), beamBeamSystem::electronBeam(), photonNucleusCrossSection::g(), photonNucleusCrossSection::getbbs(), photonNucleusCrossSection::getcsgA(), photonNucleusCrossSection::photonFlux(), and beamBeamSystem::targetBeam().
Referenced by crossSectionCalculation().
void e_narrowResonanceCrossSection::printCrossSection (const std::string name, const double x_section)
Definition at line 341 of file e_narrowResonanceCrossSection.cpp.
View newest version in sPHENIX GitHub at line 341 of file e_narrowResonanceCrossSection.cpp
Referenced by crossSectionCalculation().
Member Data Documentation
bool e_narrowResonanceCrossSection::_backwardsProduction private
Definition at line 72 of file e_narrowResonanceCrossSection.h.
View newest version in sPHENIX GitHub at line 72 of file e_narrowResonanceCrossSection.h
Referenced by crossSectionCalculation(), and e_narrowResonanceCrossSection().
double e_narrowResonanceCrossSection::_boost private
Definition at line 60 of file e_narrowResonanceCrossSection.h.
View newest version in sPHENIX GitHub at line 60 of file e_narrowResonanceCrossSection.h
Referenced by e_narrowResonanceCrossSection().
double e_narrowResonanceCrossSection::_cmsMaxPhotonEnergy private
Definition at line 64 of file e_narrowResonanceCrossSection.h.
View newest version in sPHENIX GitHub at line 64 of file e_narrowResonanceCrossSection.h
Referenced by e_narrowResonanceCrossSection().
double e_narrowResonanceCrossSection::_cmsMinPhotonEnergy private
Definition at line 65 of file e_narrowResonanceCrossSection.h.
View newest version in sPHENIX GitHub at line 65 of file e_narrowResonanceCrossSection.h
Referenced by crossSectionCalculation(), and e_narrowResonanceCrossSection().
double e_narrowResonanceCrossSection::_electronEnergy private
Definition at line 58 of file e_narrowResonanceCrossSection.h.
View newest version in sPHENIX GitHub at line 58 of file e_narrowResonanceCrossSection.h
Referenced by crossSectionCalculation(), and e_narrowResonanceCrossSection().
double e_narrowResonanceCrossSection::_Ep private
Definition at line 54 of file e_narrowResonanceCrossSection.h.
View newest version in sPHENIX GitHub at line 54 of file e_narrowResonanceCrossSection.h
Referenced by e_narrowResonanceCrossSection().
double e_narrowResonanceCrossSection::_gammaMaxQ2 private
Definition at line 70 of file e_narrowResonanceCrossSection.h.
View newest version in sPHENIX GitHub at line 70 of file e_narrowResonanceCrossSection.h
Referenced by crossSectionCalculation(), and e_narrowResonanceCrossSection().
double e_narrowResonanceCrossSection::_gammaMinQ2 private
Definition at line 69 of file e_narrowResonanceCrossSection.h.
View newest version in sPHENIX GitHub at line 69 of file e_narrowResonanceCrossSection.h
Referenced by crossSectionCalculation(), and e_narrowResonanceCrossSection().
double e_narrowResonanceCrossSection::_target_beamLorentz private
Definition at line 59 of file e_narrowResonanceCrossSection.h.
View newest version in sPHENIX GitHub at line 59 of file e_narrowResonanceCrossSection.h
Referenced by e_narrowResonanceCrossSection().
double e_narrowResonanceCrossSection::_targetMaxPhotonEnergy private
Definition at line 62 of file e_narrowResonanceCrossSection.h.
View newest version in sPHENIX GitHub at line 62 of file e_narrowResonanceCrossSection.h
Referenced by crossSectionCalculation(), e_narrowResonanceCrossSection(), and makeGammaPQ2dependence().
double e_narrowResonanceCrossSection::_targetMinPhotonEnergy private
Definition at line 63 of file e_narrowResonanceCrossSection.h.
View newest version in sPHENIX GitHub at line 63 of file e_narrowResonanceCrossSection.h
Referenced by crossSectionCalculation(), e_narrowResonanceCrossSection(), and makeGammaPQ2dependence().
double e_narrowResonanceCrossSection::_targetRadii private
Definition at line 71 of file e_narrowResonanceCrossSection.h.
View newest version in sPHENIX GitHub at line 71 of file e_narrowResonanceCrossSection.h
Referenced by e_narrowResonanceCrossSection().
double e_narrowResonanceCrossSection::_useFixedRange private
Definition at line 68 of file e_narrowResonanceCrossSection.h.
View newest version in sPHENIX GitHub at line 68 of file e_narrowResonanceCrossSection.h
Referenced by crossSectionCalculation(), and e_narrowResonanceCrossSection().
double e_narrowResonanceCrossSection::_VMnumEgamma private
Definition at line 67 of file e_narrowResonanceCrossSection.h.
View newest version in sPHENIX GitHub at line 67 of file e_narrowResonanceCrossSection.h
Referenced by e_narrowResonanceCrossSection().
The documentation for this class was generated from the following files:
estarlight/blob/master/include/e_narrowResonanceCrossSection.h
estarlight/blob/master/src/e_narrowResonanceCrossSection.cpp