EIC Software: KalmanNodeWrapper Class Reference
KalmanNodeWrapper Class Reference
#include <EicRoot/blob/master/eic/htc/SensitiveVolume.h>
Public Member Functions
KalmanNodeWrapper (KalmanNode *node, EicKfNodeTemplate *kftmpl, TGeoMatrix *sv2master)
~KalmanNodeWrapper ()
EicKfNodeTemplate * GetKfNodeTemplate () const
KalmanNode * GetKfNode (unsigned id) const
void AllocateNewKfNode (HtcKalmanFilter *kf, SensitiveVolume *sv)
const TVector3 & GetOrigin () const
const TVector3 * GetAxis (unsigned iq) const
double GetAxisComponent (unsigned iq, unsigned xyz) const
const TGeoHMatrix * GetNodeToMasterMtx () const
void SetNodeGroup (FwdHoughNodeGroup *ngroup)
FwdHoughNodeGroup * GetNodeGroup () const
unsigned GetMdim () const
Private Attributes
EicKfNodeTemplate * mKFtmpl
FwdHoughNodeGroup * mNodeGroup
std::vector< KalmanNode * > mKfNodes
TGeoHMatrix * mNodeToMaster
TVector3 mOrigin
TVector3 mBasis [3]
Detailed Description
Definition at line 22 of file SensitiveVolume.h.
View newest version in sPHENIX GitHub at line 22 of file SensitiveVolume.h
Constructor & Destructor Documentation
KalmanNodeWrapper::KalmanNodeWrapper (KalmanNode * node, EicKfNodeTemplate * kftmpl, TGeoMatrix * sv2master) inline
Definition at line 24 of file SensitiveVolume.h.
View newest version in sPHENIX GitHub at line 24 of file SensitiveVolume.h
References LocalToMaster(), LocalToMasterVect(), mBasis, mKfNodes, mNodeGroup, mNodeToMaster, EicKfNodeTemplate::mNodeToSensitiveVolume, and mOrigin.
KalmanNodeWrapper::~KalmanNodeWrapper () inline
Definition at line 71 of file SensitiveVolume.h.
View newest version in sPHENIX GitHub at line 71 of file SensitiveVolume.h
Member Function Documentation
void KalmanNodeWrapper::AllocateNewKfNode (HtcKalmanFilter * kf, SensitiveVolume * sv) inline
Definition at line 77 of file SensitiveVolume.h.
View newest version in sPHENIX GitHub at line 77 of file SensitiveVolume.h
References TrKalmanNodeLocation::AddNode(), KalmanFilter::AddNodeWrapper(), TrKalmanNode::GetLocation(), KalmanNode::GetMdim(), KalmanNode::GetName(), TrKalmanNode::GetZ(), mKfNodes, name, and TrKalmanNode::SetSensitiveVolume().
Referenced by FwdHoughTree::SetupKalmanFilter().
const TVector3* KalmanNodeWrapper::GetAxis (unsigned iq) const inline
Definition at line 98 of file SensitiveVolume.h.
View newest version in sPHENIX GitHub at line 98 of file SensitiveVolume.h
References mBasis.
Referenced by EicKfNodeTemplate::IncrementLinearTrackFitMatrices().
double KalmanNodeWrapper::GetAxisComponent (unsigned iq, unsigned xyz) const inline
Definition at line 99 of file SensitiveVolume.h.
View newest version in sPHENIX GitHub at line 99 of file SensitiveVolume.h
References mBasis.
Referenced by EicKfNodeTemplate::IncrementLinearTrackFitMatrices().
KalmanNode* KalmanNodeWrapper::GetKfNode (unsigned id) const inline
Definition at line 75 of file SensitiveVolume.h.
View newest version in sPHENIX GitHub at line 75 of file SensitiveVolume.h
References mKfNodes.
Referenced by FwdHoughTree::FinalFit(), FwdHoughTree::GetKfNode(), FwdHoughTree::SetupKalmanFilter(), and SensitiveVolume::TrackToHitDistance().
EicKfNodeTemplate* KalmanNodeWrapper::GetKfNodeTemplate () const inline
Definition at line 73 of file SensitiveVolume.h.
View newest version in sPHENIX GitHub at line 73 of file SensitiveVolume.h
References mKFtmpl.
Referenced by FwdHoughTree::AddNodeGroup(), FwdHoughNodeGroup::PackFromTo(), and SensitiveVolume::TrackToHitDistance().
unsigned KalmanNodeWrapper::GetMdim () const inline
Definition at line 106 of file SensitiveVolume.h.
View newest version in sPHENIX GitHub at line 106 of file SensitiveVolume.h
FwdHoughNodeGroup* KalmanNodeWrapper::GetNodeGroup () const inline
Definition at line 104 of file SensitiveVolume.h.
View newest version in sPHENIX GitHub at line 104 of file SensitiveVolume.h
References mNodeGroup.
const TGeoHMatrix* KalmanNodeWrapper::GetNodeToMasterMtx () const inline
Definition at line 101 of file SensitiveVolume.h.
View newest version in sPHENIX GitHub at line 101 of file SensitiveVolume.h
References mNodeToMaster.
Referenced by FwdHoughNodeGroup::PackFromTo(), and SensitiveVolume::TrackToHitDistance().
const TVector3& KalmanNodeWrapper::GetOrigin () const inline
Definition at line 97 of file SensitiveVolume.h.
View newest version in sPHENIX GitHub at line 97 of file SensitiveVolume.h
References mOrigin.
Referenced by EicKfNodeTemplate::IncrementLinearTrackFitMatrices().
void KalmanNodeWrapper::SetNodeGroup (FwdHoughNodeGroup * ngroup) inline
Definition at line 103 of file SensitiveVolume.h.
View newest version in sPHENIX GitHub at line 103 of file SensitiveVolume.h
References mNodeGroup.
Member Data Documentation
TVector3 KalmanNodeWrapper::mBasis[3] private
Definition at line 118 of file SensitiveVolume.h.
View newest version in sPHENIX GitHub at line 118 of file SensitiveVolume.h
Referenced by GetAxis(), GetAxisComponent(), and KalmanNodeWrapper().
std::vector<KalmanNode*> KalmanNodeWrapper::mKfNodes private
Definition at line 114 of file SensitiveVolume.h.
View newest version in sPHENIX GitHub at line 114 of file SensitiveVolume.h
Referenced by AllocateNewKfNode(), GetKfNode(), and KalmanNodeWrapper().
EicKfNodeTemplate* KalmanNodeWrapper::mKFtmpl private
Definition at line 106 of file SensitiveVolume.h.
View newest version in sPHENIX GitHub at line 106 of file SensitiveVolume.h
Referenced by GetKfNodeTemplate().
FwdHoughNodeGroup* KalmanNodeWrapper::mNodeGroup private
Definition at line 111 of file SensitiveVolume.h.
View newest version in sPHENIX GitHub at line 111 of file SensitiveVolume.h
Referenced by GetNodeGroup(), KalmanNodeWrapper(), and SetNodeGroup().
TGeoHMatrix* KalmanNodeWrapper::mNodeToMaster private
Definition at line 116 of file SensitiveVolume.h.
View newest version in sPHENIX GitHub at line 116 of file SensitiveVolume.h
Referenced by GetNodeToMasterMtx(), and KalmanNodeWrapper().
TVector3 KalmanNodeWrapper::mOrigin private
Definition at line 118 of file SensitiveVolume.h.
View newest version in sPHENIX GitHub at line 118 of file SensitiveVolume.h
Referenced by GetOrigin(), and KalmanNodeWrapper().
The documentation for this class was generated from the following file:
EicRoot/blob/master/eic/htc/SensitiveVolume.h