EIC Software: EICG4ZDCSteppingAction Class Reference
EICG4ZDCSteppingAction Class Reference
#include <fun4all_eicdetectors/blob/master/simulation/g4simulation/g4zdc/EICG4ZDCSteppingAction.h>
Public Member Functions
EICG4ZDCSteppingAction (EICG4ZDCDetector *, const PHParameters *parameters)
constructor
virtual ~EICG4ZDCSteppingAction ()
destructor
virtual bool UserSteppingAction (const G4Step *, bool)
stepping action
virtual void SetInterfacePointers (PHCompositeNode *)
reimplemented from base class
Public Member Functions inherited from PHG4SteppingAction
PHG4SteppingAction (const std::string &name, const int i=0)
virtual ~PHG4SteppingAction ()
virtual void Verbosity (const int i)
virtual int Verbosity () const
virtual int Init ()
virtual double GetScintLightYield (const G4Step *step)
get scintillation photon count. It require a custom set SCINTILLATIONYIELD property to work
virtual double GetVisibleEnergyDeposition (const G4Step *step)
get amount of energy that can make scintillation light, in Unit of GeV.
virtual void StoreLocalCoordinate (PHG4Hit *hit, const G4Step *step, const bool do_prepoint, const bool do_postpoint)
Extract local coordinate of the hit and save to PHG4Hit.
virtual void Print (const std::string &) const
std::string GetName () const
void SetName (const std::string &name)
virtual void SetLightCorrection (const double inner_radius, const double inner_corr, const double outer_radius, const double outer_corr)
virtual double GetLightCorrection (const double r) const
virtual double GetLightCorrection (const double xpos, const double ypos) const
virtual bool ValidCorrection () const
virtual void SetHitNodeName (const std::string &, const std::string &)
Set the G4HIT node names from Subsystem rather than constructing your own.
Private Attributes
EICG4ZDCDetector * m_Detector
pointer to the detector
const PHParameters * m_Params
PHG4HitContainer * m_HitContainer
pointer to hit container
PHG4Hit * m_Hit
PHG4HitContainer * m_SaveHitContainer
G4VPhysicalVolume * m_SaveVolPre
G4VPhysicalVolume * m_SaveVolPost
PHG4Shower * m_SaveShower
int m_SaveTrackId
int m_SavePreStepStatus
int m_SavePostStepStatus
int m_ActiveFlag
int m_BlackHoleFlag
double m_EdepSum
double m_EionSum
double m_LightYield
Detailed Description
Definition at line 18 of file EICG4ZDCSteppingAction.h.
View newest version in sPHENIX GitHub at line 18 of file EICG4ZDCSteppingAction.h
Constructor & Destructor Documentation
EICG4ZDCSteppingAction::EICG4ZDCSteppingAction (EICG4ZDCDetector * detector, const PHParameters * parameters)
constructor
Definition at line 66 of file EICG4ZDCSteppingAction.cc.
View newest version in sPHENIX GitHub at line 66 of file EICG4ZDCSteppingAction.cc
EICG4ZDCSteppingAction::~EICG4ZDCSteppingAction () virtual
destructor
Definition at line 89 of file EICG4ZDCSteppingAction.cc.
View newest version in sPHENIX GitHub at line 89 of file EICG4ZDCSteppingAction.cc
References m_Hit.
Member Function Documentation
void EICG4ZDCSteppingAction::SetInterfacePointers (PHCompositeNode * topNode) virtual
reimplemented from base class
Reimplemented from PHG4SteppingAction.
Definition at line 410 of file EICG4ZDCSteppingAction.cc.
View newest version in sPHENIX GitHub at line 410 of file EICG4ZDCSteppingAction.cc
References PHG4Detector::GetName(), m_Detector, and m_HitContainer.
bool EICG4ZDCSteppingAction::UserSteppingAction (const G4Step * aStep, bool was_used) virtual
stepping action
Implements PHG4SteppingAction.
Definition at line 100 of file EICG4ZDCSteppingAction.cc.
View newest version in sPHENIX GitHub at line 100 of file EICG4ZDCSteppingAction.cc
References PHG4Shower::add_g4hit_id(), PHG4HitContainer::AddHit(), Acts::UnitConstants::cm, ZDCID::Crystal, ZDCID::CrystalTower, ZDCID::EMLayer, PHG4Hit::get_hit_id(), PHG4Hit::get_x(), EICG4ZDCDetector::GetAbsorberVolumeInfo(), EICG4ZDCDetector::GetActiveVolumeInfo(), PHG4HitContainer::GetID(), PHG4SteppingAction::GetName(), PHG4StepStatusDecode::GetStepStatus(), PHG4SteppingAction::GetVisibleEnergyDeposition(), Acts::UnitConstants::GeV, ZDCID::HCPadLayer, ZDCID::HCSciLayer, EICG4ZDCDetector::IsInDetector(), m_BlackHoleFlag, m_Detector, m_EdepSum, m_EionSum, m_Hit, m_HitContainer, m_LightYield, m_SaveHitContainer, m_SavePostStepStatus, m_SavePreStepStatus, m_SaveShower, m_SaveTrackId, m_SaveVolPost, m_SaveVolPre, p, PHG4Hit::Reset(), ZDCID::Scintillator, PHG4Hit::set_edep(), PHG4Hit::set_eion(), PHG4Hit::set_hit_type(), PHG4Hit::set_index_i(), PHG4Hit::set_index_j(), PHG4Hit::set_layer(), PHG4Hit::set_light_yield(), PHG4Hit::set_shower_id(), PHG4Hit::set_t(), PHG4Hit::set_trkid(), PHG4Hit::set_x(), PHG4Hit::set_y(), PHG4Hit::set_z(), ZDCID::SI_PAD, ZDCID::SI_PIXEL, and Acts::Test::volume.
Member Data Documentation
int EICG4ZDCSteppingAction::m_ActiveFlag private
Definition at line 48 of file EICG4ZDCSteppingAction.h.
View newest version in sPHENIX GitHub at line 48 of file EICG4ZDCSteppingAction.h
int EICG4ZDCSteppingAction::m_BlackHoleFlag private
Definition at line 49 of file EICG4ZDCSteppingAction.h.
View newest version in sPHENIX GitHub at line 49 of file EICG4ZDCSteppingAction.h
Referenced by UserSteppingAction().
EICG4ZDCDetector* EICG4ZDCSteppingAction::m_Detector private
pointer to the detector
Definition at line 35 of file EICG4ZDCSteppingAction.h.
View newest version in sPHENIX GitHub at line 35 of file EICG4ZDCSteppingAction.h
Referenced by SetInterfacePointers(), and UserSteppingAction().
double EICG4ZDCSteppingAction::m_EdepSum private
Definition at line 50 of file EICG4ZDCSteppingAction.h.
View newest version in sPHENIX GitHub at line 50 of file EICG4ZDCSteppingAction.h
Referenced by UserSteppingAction().
double EICG4ZDCSteppingAction::m_EionSum private
Definition at line 51 of file EICG4ZDCSteppingAction.h.
View newest version in sPHENIX GitHub at line 51 of file EICG4ZDCSteppingAction.h
Referenced by UserSteppingAction().
PHG4Hit* EICG4ZDCSteppingAction::m_Hit private
Definition at line 39 of file EICG4ZDCSteppingAction.h.
View newest version in sPHENIX GitHub at line 39 of file EICG4ZDCSteppingAction.h
Referenced by UserSteppingAction(), and ~EICG4ZDCSteppingAction().
PHG4HitContainer* EICG4ZDCSteppingAction::m_HitContainer private
pointer to hit container
Definition at line 38 of file EICG4ZDCSteppingAction.h.
View newest version in sPHENIX GitHub at line 38 of file EICG4ZDCSteppingAction.h
Referenced by SetInterfacePointers(), and UserSteppingAction().
double EICG4ZDCSteppingAction::m_LightYield private
Definition at line 52 of file EICG4ZDCSteppingAction.h.
View newest version in sPHENIX GitHub at line 52 of file EICG4ZDCSteppingAction.h
Referenced by UserSteppingAction().
const PHParameters* EICG4ZDCSteppingAction::m_Params private
Definition at line 36 of file EICG4ZDCSteppingAction.h.
View newest version in sPHENIX GitHub at line 36 of file EICG4ZDCSteppingAction.h
PHG4HitContainer* EICG4ZDCSteppingAction::m_SaveHitContainer private
Definition at line 40 of file EICG4ZDCSteppingAction.h.
View newest version in sPHENIX GitHub at line 40 of file EICG4ZDCSteppingAction.h
Referenced by UserSteppingAction().
int EICG4ZDCSteppingAction::m_SavePostStepStatus private
Definition at line 47 of file EICG4ZDCSteppingAction.h.
View newest version in sPHENIX GitHub at line 47 of file EICG4ZDCSteppingAction.h
Referenced by UserSteppingAction().
int EICG4ZDCSteppingAction::m_SavePreStepStatus private
Definition at line 46 of file EICG4ZDCSteppingAction.h.
View newest version in sPHENIX GitHub at line 46 of file EICG4ZDCSteppingAction.h
Referenced by UserSteppingAction().
PHG4Shower* EICG4ZDCSteppingAction::m_SaveShower private
Definition at line 43 of file EICG4ZDCSteppingAction.h.
View newest version in sPHENIX GitHub at line 43 of file EICG4ZDCSteppingAction.h
Referenced by UserSteppingAction().
int EICG4ZDCSteppingAction::m_SaveTrackId private
Definition at line 45 of file EICG4ZDCSteppingAction.h.
View newest version in sPHENIX GitHub at line 45 of file EICG4ZDCSteppingAction.h
Referenced by UserSteppingAction().
G4VPhysicalVolume* EICG4ZDCSteppingAction::m_SaveVolPost private
Definition at line 42 of file EICG4ZDCSteppingAction.h.
View newest version in sPHENIX GitHub at line 42 of file EICG4ZDCSteppingAction.h
Referenced by UserSteppingAction().
G4VPhysicalVolume* EICG4ZDCSteppingAction::m_SaveVolPre private
Definition at line 41 of file EICG4ZDCSteppingAction.h.
View newest version in sPHENIX GitHub at line 41 of file EICG4ZDCSteppingAction.h
Referenced by UserSteppingAction().
The documentation for this class was generated from the following files:
fun4all_eicdetectors/blob/master/simulation/g4simulation/g4zdc/EICG4ZDCSteppingAction.h
fun4all_eicdetectors/blob/master/simulation/g4simulation/g4zdc/EICG4ZDCSteppingAction.cc