EIC Software: CbmBaseHit Class Reference
CbmBaseHit Class Reference abstract
#include <EicRoot/blob/master/cbmdata/CbmBaseHit.h>
Public Member Functions
CbmBaseHit ()
Default constructor.
virtual ~CbmBaseHit ()
Destructor.
HitType GetType () const
Double_t GetZ () const
Double_t GetDz () const
Int_t GetRefId () const
Int_t GetAddress () const
FairMultiLinkedData * GetLinks () const
void SetZ (Double_t z)
void SetDz (Double_t dz)
void SetRefId (Int_t refId)
void SetAddress (Int_t address)
void SetLinks (FairMultiLinkedData *links)
virtual Int_t GetPlaneId () const =0
virtual string ToString () const =0
Pure virtual function. Must be implemented in derived class. Has to return string representation of the object.
Protected Member Functions
void SetType (HitType type)
Sets hit type.
CbmBaseHit (const CbmBaseHit &)
CbmBaseHit & operator= (const CbmBaseHit &)
Private Member Functions
ClassDef (CbmBaseHit, 1)
Private Attributes
HitType fType
hit type
Double_t fZ
Z position of hit [cm].
Double_t fDz
Z position error [cm].
Int_t fRefId
some reference id (usually to cluster, digi or MC point)
Int_t fAddress
detector unique identifier
FairMultiLinkedData * fLinks
Monte-Carlo link collection.
Detailed Description
Definition at line 33 of file CbmBaseHit.h.
View newest version in sPHENIX GitHub at line 33 of file CbmBaseHit.h
Constructor & Destructor Documentation
CbmBaseHit::CbmBaseHit ()
Default constructor.
Definition at line 12 of file CbmBaseHit.cxx.
View newest version in sPHENIX GitHub at line 12 of file CbmBaseHit.cxx
CbmBaseHit::~CbmBaseHit () virtual
Destructor.
Definition at line 61 of file CbmBaseHit.cxx.
View newest version in sPHENIX GitHub at line 61 of file CbmBaseHit.cxx
CbmBaseHit::CbmBaseHit (const CbmBaseHit & rhs) protected
Definition at line 23 of file CbmBaseHit.cxx.
View newest version in sPHENIX GitHub at line 23 of file CbmBaseHit.cxx
References fLinks.
Member Function Documentation
CbmBaseHit::ClassDef (CbmBaseHit , 1) private
Int_t CbmBaseHit::GetAddress () const inline
Definition at line 51 of file CbmBaseHit.h.
View newest version in sPHENIX GitHub at line 51 of file CbmBaseHit.h
References fAddress.
Referenced by CbmRichHitProducer::AddHit(), CbmRichHit::ToString(), CbmStripHit::ToString(), and CbmPixelHit::ToString().
Double_t CbmBaseHit::GetDz () const inline
Definition at line 49 of file CbmBaseHit.h.
View newest version in sPHENIX GitHub at line 49 of file CbmBaseHit.h
References fDz.
Referenced by CbmPixelHit::PositionError(), CbmRichHit::ToString(), CbmStripHit::ToString(), and CbmPixelHit::ToString().
FairMultiLinkedData* CbmBaseHit::GetLinks () const inline
Definition at line 52 of file CbmBaseHit.h.
View newest version in sPHENIX GitHub at line 52 of file CbmBaseHit.h
References fLinks.
virtual Int_t CbmBaseHit::GetPlaneId () const pure virtual
Pure virtual function. Must be implemented in derived class. Should return plane identifier of the hit. Usually this is station or layer number of the detector. Can be calculated using unique detector identifier or can use additional class member from the derived class to store the plane identifier.
Implemented in CbmRichHit.
Int_t CbmBaseHit::GetRefId () const inline
Definition at line 50 of file CbmBaseHit.h.
View newest version in sPHENIX GitHub at line 50 of file CbmBaseHit.h
References fRefId.
Referenced by CbmRichRingFinderIdeal::DoFind(), CbmRichTestHits::Exec(), CbmRichMatchRings::Exec(), CbmRichUrqmdTest::FillRichRingNofHits(), CbmRichGeoTest::HitsAndPoints(), CbmRichUrqmdTest::NofHits(), CbmRichHit::ToString(), CbmStripHit::ToString(), and CbmPixelHit::ToString().
HitType CbmBaseHit::GetType () const inline
Definition at line 47 of file CbmBaseHit.h.
View newest version in sPHENIX GitHub at line 47 of file CbmBaseHit.h
References fType.
Double_t CbmBaseHit::GetZ () const inline
Definition at line 48 of file CbmBaseHit.h.
View newest version in sPHENIX GitHub at line 48 of file CbmBaseHit.h
References fZ.
Referenced by CbmPixelHit::Position(), CbmRichHit::ToString(), CbmStripHit::ToString(), and CbmPixelHit::ToString().
CbmBaseHit & CbmBaseHit::operator= (const CbmBaseHit & rhs) protected
Definition at line 37 of file CbmBaseHit.cxx.
View newest version in sPHENIX GitHub at line 37 of file CbmBaseHit.cxx
References fAddress, fDz, fLinks, fRefId, fType, and fZ.
void CbmBaseHit::SetAddress (Int_t address) inline
Definition at line 58 of file CbmBaseHit.h.
View newest version in sPHENIX GitHub at line 58 of file CbmBaseHit.h
References fAddress.
Referenced by CbmRichHitProducer::AddHit(), CbmPixelHit::CbmPixelHit(), and CbmStripHit::CbmStripHit().
void CbmBaseHit::SetDz (Double_t dz) inline
Definition at line 56 of file CbmBaseHit.h.
View newest version in sPHENIX GitHub at line 56 of file CbmBaseHit.h
References dz, and fDz.
Referenced by CbmPixelHit::CbmPixelHit(), CbmStripHit::CbmStripHit(), and CbmPixelHit::SetPositionError().
void CbmBaseHit::SetLinks (FairMultiLinkedData * links) inline
Definition at line 59 of file CbmBaseHit.h.
View newest version in sPHENIX GitHub at line 59 of file CbmBaseHit.h
References fLinks.
void CbmBaseHit::SetRefId (Int_t refId) inline
Definition at line 57 of file CbmBaseHit.h.
View newest version in sPHENIX GitHub at line 57 of file CbmBaseHit.h
References fRefId.
Referenced by CbmRichHitProducer::AddHit(), CbmPixelHit::CbmPixelHit(), and CbmStripHit::CbmStripHit().
void CbmBaseHit::SetType (HitType type) inline protected
Sets hit type.
Parameters
type hit type
Definition at line 80 of file CbmBaseHit.h.
View newest version in sPHENIX GitHub at line 80 of file CbmBaseHit.h
References fType.
Referenced by CbmPixelHit::CbmPixelHit(), CbmRichHit::CbmRichHit(), and CbmStripHit::CbmStripHit().
void CbmBaseHit::SetZ (Double_t z) inline
Definition at line 55 of file CbmBaseHit.h.
View newest version in sPHENIX GitHub at line 55 of file CbmBaseHit.h
References fZ, and z.
Referenced by CbmPixelHit::CbmPixelHit(), CbmStripHit::CbmStripHit(), and CbmPixelHit::SetPosition().
virtual string CbmBaseHit::ToString () const pure virtual
Pure virtual function. Must be implemented in derived class. Has to return string representation of the object.
Implemented in CbmPixelHit, CbmStripHit, and CbmRichHit.
Member Data Documentation
Int_t CbmBaseHit::fAddress private
detector unique identifier
Definition at line 90 of file CbmBaseHit.h.
View newest version in sPHENIX GitHub at line 90 of file CbmBaseHit.h
Referenced by GetAddress(), operator=(), and SetAddress().
Double_t CbmBaseHit::fDz private
Z position error [cm].
Definition at line 88 of file CbmBaseHit.h.
View newest version in sPHENIX GitHub at line 88 of file CbmBaseHit.h
Referenced by GetDz(), operator=(), and SetDz().
FairMultiLinkedData* CbmBaseHit::fLinks private
Monte-Carlo link collection.
Definition at line 91 of file CbmBaseHit.h.
View newest version in sPHENIX GitHub at line 91 of file CbmBaseHit.h
Referenced by CbmBaseHit(), GetLinks(), operator=(), and SetLinks().
Int_t CbmBaseHit::fRefId private
some reference id (usually to cluster, digi or MC point)
Definition at line 89 of file CbmBaseHit.h.
View newest version in sPHENIX GitHub at line 89 of file CbmBaseHit.h
Referenced by GetRefId(), operator=(), and SetRefId().
HitType CbmBaseHit::fType private
hit type
Definition at line 86 of file CbmBaseHit.h.
View newest version in sPHENIX GitHub at line 86 of file CbmBaseHit.h
Referenced by GetType(), operator=(), and SetType().
Double_t CbmBaseHit::fZ private
Z position of hit [cm].
Definition at line 87 of file CbmBaseHit.h.
View newest version in sPHENIX GitHub at line 87 of file CbmBaseHit.h
Referenced by GetZ(), operator=(), and SetZ().
The documentation for this class was generated from the following files:
EicRoot/blob/master/cbmdata/CbmBaseHit.h
EicRoot/blob/master/cbmdata/CbmBaseHit.cxx