EIC Software: EICG4dRICHHit Class Reference
EICG4dRICHHit Class Reference
#include <fun4all_eicdetectors/blob/master/simulation/g4simulation/g4drich/EICG4dRICHHit.h>
Public Member Functions
EICG4dRICHHit ()=default
EICG4dRICHHit (const PHG4Hit *g4hit)
virtual ~EICG4dRICHHit ()=default
void Reset ()
Clear Event.
int get_trkid () const
G4ThreeVector get_position (const int i) const
float get_x (const int i) const
float get_y (const int i) const
float get_z (const int i) const
float get_t (const int i) const
G4ThreeVector get_momentum () const
G4ThreeVector get_momentum_dir () const
G4ThreeVector get_vertex_position () const
G4ThreeVector get_vertex_momentum_dir () const
float get_delta_t () const
G4String get_hit_type_name () const
G4String get_hit_subtype_name () const
int get_petal () const
int get_psst () const
int get_pdg () const
G4String get_particle_name () const
G4String get_process () const
int get_parent_id () const
float get_edep () const
PHG4HitDefs::keytype get_hit_id () const
int get_detid () const
int get_shower_id () const
void set_position (const int i, const G4ThreeVector v)
void set_momentum (const G4ThreeVector v)
void set_momentum_dir (const G4ThreeVector v)
void set_vertex_position (const G4ThreeVector v)
void set_vertex_momentum_dir (const G4ThreeVector v)
void set_t (const int i, const float f)
void set_hit_type_name (const G4String s)
void set_hit_subtype_name (const G4String s)
void set_petal (const int i)
void set_psst (const int i)
void set_pdg (const int i)
void set_particle_name (const G4String s)
void set_process (const G4String s)
void set_parent_id (const int i)
void set_edep (const float f)
void set_hit_id (const PHG4HitDefs::keytype i)
void set_shower_id (const int i)
void set_trkid (const int i)
virtual void print () const
Public Member Functions inherited from PHG4Hit
PHG4Hit ()
~PHG4Hit () override
void identify (std::ostream &os=std::cout) const override
void CopyFrom (const PHObject *phobj) override
virtual float get_px (const int) const
virtual float get_py (const int) const
virtual float get_pz (const int) const
virtual float get_local_x (const int) const
virtual float get_local_y (const int) const
virtual float get_local_z (const int) const
virtual float get_eion () const
virtual float get_light_yield () const
virtual float get_path_length () const
virtual unsigned int get_layer () const
virtual int get_scint_id () const
virtual int get_row () const
virtual int get_strip_z_index () const
virtual int get_strip_y_index () const
virtual int get_ladder_z_index () const
virtual int get_ladder_phi_index () const
virtual int get_index_i () const
virtual int get_index_j () const
virtual int get_index_k () const
virtual int get_index_l () const
virtual int get_hit_type () const
virtual void set_x (const int, const float)
virtual void set_y (const int, const float)
virtual void set_z (const int, const float)
virtual void set_px (const int, const float)
virtual void set_py (const int, const float)
virtual void set_pz (const int, const float)
virtual void set_local_x (const int, const float)
virtual void set_local_y (const int, const float)
virtual void set_local_z (const int, const float)
virtual void set_eion (const float)
virtual void set_light_yield (const float)
virtual void set_path_length (const float)
virtual void set_layer (const unsigned int)
virtual void set_scint_id (const int)
virtual void set_row (const int)
virtual void set_strip_z_index (const int)
virtual void set_strip_y_index (const int)
virtual void set_ladder_z_index (const int)
virtual void set_ladder_phi_index (const int)
virtual void set_index_i (const int)
virtual void set_index_j (const int)
virtual void set_index_k (const int)
virtual void set_index_l (const int)
virtual void set_hit_type (const int)
virtual float get_avg_x () const
virtual float get_avg_y () const
virtual float get_avg_z () const
virtual float get_avg_t () const
virtual bool has_property (const PROPERTY) const
virtual float get_property_float (const PROPERTY) const
virtual int get_property_int (const PROPERTY) const
virtual unsigned int get_property_uint (const PROPERTY) const
virtual void set_property (const PROPERTY, const float)
virtual void set_property (const PROPERTY, const int)
virtual void set_property (const PROPERTY, const unsigned int)
Public Member Functions inherited from PHObject
PHObject ()
ctor
~PHObject () override
dtor
virtual PHObject * CloneMe () const
Virtual copy constructor.
virtual PHObject * clone () const final
PHObject * Clone (const char *newname="") const final
void Copy (TObject &object) const final
virtual int isValid () const
isValid returns non zero if object contains vailid data
virtual int isValid (const float) const
virtual int isValid (const double) const
virtual int isValid (const int) const
virtual int isValid (const unsigned int) const
virtual int isImplemented (const float f) const
virtual int isImplemented (const double f) const
virtual int isImplemented (const int i) const
virtual int isImplemented (const unsigned int i) const
virtual int Integrate () const
virtual int Integrate (PHObject *)
Protected Attributes
float x [2] = {NAN, NAN}
float y [2] = {NAN, NAN}
float z [2] = {NAN, NAN}
float t [2] = {NAN, NAN}
G4ThreeVector hitPos [2]
G4ThreeVector momVec
G4ThreeVector momDir
G4ThreeVector vtxPos
G4ThreeVector vtxMomDir
G4String hitTypeName
G4String hitSubtypeName
int petal = INT_MIN
int psst = INT_MIN
int pdg = INT_MIN
G4String pname
G4String process
int parentID = -1
PHG4HitDefs::keytype hitid = ULONG_LONG_MAX
int trackid = INT_MIN
int showerid = INT_MIN
float edep = NAN
Additional Inherited Members
Public Types inherited from PHG4Hit
enum PROPERTY {
prop_eion = 1, prop_light_yield = 2, scint_gammas = 3, cerenkov_gammas = 4,
prop_px_0 = 10, prop_px_1 = 11, prop_py_0 = 12, prop_py_1 = 13,
prop_pz_0 = 14, prop_pz_1 = 15, prop_path_length = 16, prop_local_x_0 = 20,
prop_local_x_1 = 21, prop_local_y_0 = 22, prop_local_y_1 = 23, prop_local_z_0 = 24,
prop_local_z_1 = 25, prop_layer = 101, prop_scint_id = 102, prop_row = 103,
prop_strip_z_index = 110, prop_strip_y_index = 111, prop_ladder_z_index = 112, prop_ladder_phi_index = 113,
prop_stave_index = 114, prop_half_stave_index = 115, prop_module_index = 116, prop_chip_index = 117,
prop_local_pos_x_0 = 118, prop_local_pos_y_0 = 119, prop_local_pos_z_0 = 120, prop_index_i = 121,
prop_index_j = 122, prop_index_k = 123, prop_index_l = 124, prop_hit_type = 125,
prop_local_pos_x_1 = 128, prop_local_pos_y_1 = 126, prop_local_pos_z_1 = 127, prop_MAX_NUMBER = UCHAR_MAX
}
enum PROPERTY_TYPE { type_int = 1, type_uint = 2, type_float = 3, type_unknown = -1 }
Static Public Member Functions inherited from PHG4Hit
static std::pair< const
std::string, PROPERTY_TYPE > get_property_info (PROPERTY prop_id)
static bool check_property (const PROPERTY prop_id, const PROPERTY_TYPE prop_type)
static std::string get_property_type (const PROPERTY_TYPE prop_type)
Protected Member Functions inherited from PHG4Hit
virtual unsigned int get_property_nocheck (const PROPERTY) const
virtual void set_property_nocheck (const PROPERTY, const unsigned int)
Detailed Description
Definition at line 19 of file EICG4dRICHHit.h.
View newest version in sPHENIX GitHub at line 19 of file EICG4dRICHHit.h
Constructor & Destructor Documentation
EICG4dRICHHit::EICG4dRICHHit () default
EICG4dRICHHit::EICG4dRICHHit (const PHG4Hit * g4hit) explicit
Definition at line 5 of file EICG4dRICHHit.cc.
View newest version in sPHENIX GitHub at line 5 of file EICG4dRICHHit.cc
References PHG4Hit::CopyFrom().
virtual EICG4dRICHHit::~EICG4dRICHHit () virtual default
Member Function Documentation
float EICG4dRICHHit::get_delta_t () const inline
Definition at line 38 of file EICG4dRICHHit.h.
View newest version in sPHENIX GitHub at line 38 of file EICG4dRICHHit.h
References t.
Referenced by EICG4dRICHTree::getHits().
int EICG4dRICHHit::get_detid () const virtual
Reimplemented from PHG4Hit.
Definition at line 20 of file EICG4dRICHHit.cc.
View newest version in sPHENIX GitHub at line 20 of file EICG4dRICHHit.cc
References PHG4HitDefs::hit_idbits, and hitid.
float EICG4dRICHHit::get_edep () const inline virtual
Reimplemented from PHG4Hit.
Definition at line 48 of file EICG4dRICHHit.h.
View newest version in sPHENIX GitHub at line 48 of file EICG4dRICHHit.h
References edep.
Referenced by EICG4dRICHTree::getHits().
PHG4HitDefs::keytype EICG4dRICHHit::get_hit_id () const inline virtual
Reimplemented from PHG4Hit.
Definition at line 49 of file EICG4dRICHHit.h.
View newest version in sPHENIX GitHub at line 49 of file EICG4dRICHHit.h
References hitid.
Referenced by EICG4dRICHSteppingAction::UserSteppingAction().
G4String EICG4dRICHHit::get_hit_subtype_name () const inline
Definition at line 40 of file EICG4dRICHHit.h.
View newest version in sPHENIX GitHub at line 40 of file EICG4dRICHHit.h
References hitSubtypeName.
Referenced by EICG4dRICHTree::getHits().
G4String EICG4dRICHHit::get_hit_type_name () const inline
Definition at line 39 of file EICG4dRICHHit.h.
View newest version in sPHENIX GitHub at line 39 of file EICG4dRICHHit.h
References hitTypeName.
Referenced by EICG4dRICHTree::getHits().
G4ThreeVector EICG4dRICHHit::get_momentum () const inline
Definition at line 34 of file EICG4dRICHHit.h.
View newest version in sPHENIX GitHub at line 34 of file EICG4dRICHHit.h
References momVec.
Referenced by EICG4dRICHTree::getHits().
G4ThreeVector EICG4dRICHHit::get_momentum_dir () const inline
Definition at line 35 of file EICG4dRICHHit.h.
View newest version in sPHENIX GitHub at line 35 of file EICG4dRICHHit.h
References momDir.
Referenced by EICG4dRICHTree::getHits().
int EICG4dRICHHit::get_parent_id () const inline
Definition at line 46 of file EICG4dRICHHit.h.
View newest version in sPHENIX GitHub at line 46 of file EICG4dRICHHit.h
References parentID.
Referenced by EICG4dRICHTree::getHits().
G4String EICG4dRICHHit::get_particle_name () const inline
Definition at line 44 of file EICG4dRICHHit.h.
View newest version in sPHENIX GitHub at line 44 of file EICG4dRICHHit.h
References pname.
Referenced by EICG4dRICHTree::getHits().
int EICG4dRICHHit::get_pdg () const inline
Definition at line 43 of file EICG4dRICHHit.h.
View newest version in sPHENIX GitHub at line 43 of file EICG4dRICHHit.h
References pdg.
Referenced by EICG4dRICHTree::getHits().
int EICG4dRICHHit::get_petal () const inline
Definition at line 41 of file EICG4dRICHHit.h.
View newest version in sPHENIX GitHub at line 41 of file EICG4dRICHHit.h
References petal.
Referenced by EICG4dRICHTree::getHits().
G4ThreeVector EICG4dRICHHit::get_position (const int i) const inline
Definition at line 29 of file EICG4dRICHHit.h.
View newest version in sPHENIX GitHub at line 29 of file EICG4dRICHHit.h
References hitPos.
Referenced by EICG4dRICHTree::getHits().
G4String EICG4dRICHHit::get_process () const inline
Definition at line 45 of file EICG4dRICHHit.h.
View newest version in sPHENIX GitHub at line 45 of file EICG4dRICHHit.h
References process.
Referenced by EICG4dRICHTree::getHits().
int EICG4dRICHHit::get_psst () const inline
Definition at line 42 of file EICG4dRICHHit.h.
View newest version in sPHENIX GitHub at line 42 of file EICG4dRICHHit.h
References psst.
Referenced by EICG4dRICHTree::getHits().
int EICG4dRICHHit::get_shower_id () const inline virtual
Reimplemented from PHG4Hit.
Definition at line 51 of file EICG4dRICHHit.h.
View newest version in sPHENIX GitHub at line 51 of file EICG4dRICHHit.h
References showerid.
float EICG4dRICHHit::get_t (const int i) const inline virtual
Reimplemented from PHG4Hit.
Definition at line 33 of file EICG4dRICHHit.h.
View newest version in sPHENIX GitHub at line 33 of file EICG4dRICHHit.h
References t.
int EICG4dRICHHit::get_trkid () const inline virtual
Reimplemented from PHG4Hit.
Definition at line 28 of file EICG4dRICHHit.h.
View newest version in sPHENIX GitHub at line 28 of file EICG4dRICHHit.h
References trackid.
Referenced by EICG4dRICHTree::getHits(), and EICG4dRICHSteppingAction::UserSteppingAction().
G4ThreeVector EICG4dRICHHit::get_vertex_momentum_dir () const inline
Definition at line 37 of file EICG4dRICHHit.h.
View newest version in sPHENIX GitHub at line 37 of file EICG4dRICHHit.h
References vtxMomDir.
Referenced by EICG4dRICHTree::getHits().
G4ThreeVector EICG4dRICHHit::get_vertex_position () const inline
Definition at line 36 of file EICG4dRICHHit.h.
View newest version in sPHENIX GitHub at line 36 of file EICG4dRICHHit.h
References vtxPos.
Referenced by EICG4dRICHTree::getHits().
float EICG4dRICHHit::get_x (const int i) const inline virtual
Reimplemented from PHG4Hit.
Definition at line 30 of file EICG4dRICHHit.h.
View newest version in sPHENIX GitHub at line 30 of file EICG4dRICHHit.h
References hitPos.
Referenced by EICG4dRICHSteppingAction::UserSteppingAction().
float EICG4dRICHHit::get_y (const int i) const inline virtual
Reimplemented from PHG4Hit.
Definition at line 31 of file EICG4dRICHHit.h.
View newest version in sPHENIX GitHub at line 31 of file EICG4dRICHHit.h
References hitPos.
float EICG4dRICHHit::get_z (const int i) const inline virtual
Reimplemented from PHG4Hit.
Definition at line 32 of file EICG4dRICHHit.h.
View newest version in sPHENIX GitHub at line 32 of file EICG4dRICHHit.h
References hitPos.
void EICG4dRICHHit::print (void) const virtual
Reimplemented from PHG4Hit.
Definition at line 29 of file EICG4dRICHHit.cc.
View newest version in sPHENIX GitHub at line 29 of file EICG4dRICHHit.cc
References edep, hitid, t, trackid, x, y, and z.
Referenced by EICG4dRICHTree::getHits().
void EICG4dRICHHit::Reset () virtual
Clear Event.
Reimplemented from PHG4Hit.
Definition at line 7 of file EICG4dRICHHit.cc.
View newest version in sPHENIX GitHub at line 7 of file EICG4dRICHHit.cc
References edep, hitid, set_position(), set_t(), and showerid.
Referenced by EICG4dRICHSteppingAction::UserSteppingAction().
void EICG4dRICHHit::set_edep (const float f) inline virtual
Reimplemented from PHG4Hit.
Definition at line 69 of file EICG4dRICHHit.h.
View newest version in sPHENIX GitHub at line 69 of file EICG4dRICHHit.h
References edep.
Referenced by EICG4dRICHSteppingAction::UserSteppingAction().
void EICG4dRICHHit::set_hit_id (const PHG4HitDefs::keytype i) inline virtual
Reimplemented from PHG4Hit.
Definition at line 70 of file EICG4dRICHHit.h.
View newest version in sPHENIX GitHub at line 70 of file EICG4dRICHHit.h
References hitid.
void EICG4dRICHHit::set_hit_subtype_name (const G4String s) inline
Definition at line 61 of file EICG4dRICHHit.h.
View newest version in sPHENIX GitHub at line 61 of file EICG4dRICHHit.h
References hitSubtypeName, and Acts::UnitConstants::s.
Referenced by EICG4dRICHSteppingAction::UserSteppingAction().
void EICG4dRICHHit::set_hit_type_name (const G4String s) inline
Definition at line 60 of file EICG4dRICHHit.h.
View newest version in sPHENIX GitHub at line 60 of file EICG4dRICHHit.h
References hitTypeName, and Acts::UnitConstants::s.
Referenced by EICG4dRICHSteppingAction::UserSteppingAction().
void EICG4dRICHHit::set_momentum (const G4ThreeVector v) inline
Definition at line 55 of file EICG4dRICHHit.h.
View newest version in sPHENIX GitHub at line 55 of file EICG4dRICHHit.h
References momVec, and v.
Referenced by EICG4dRICHSteppingAction::UserSteppingAction().
void EICG4dRICHHit::set_momentum_dir (const G4ThreeVector v) inline
Definition at line 56 of file EICG4dRICHHit.h.
View newest version in sPHENIX GitHub at line 56 of file EICG4dRICHHit.h
References momDir, and v.
Referenced by EICG4dRICHSteppingAction::UserSteppingAction().
void EICG4dRICHHit::set_parent_id (const int i) inline
Definition at line 67 of file EICG4dRICHHit.h.
View newest version in sPHENIX GitHub at line 67 of file EICG4dRICHHit.h
References parentID.
Referenced by EICG4dRICHSteppingAction::UserSteppingAction().
void EICG4dRICHHit::set_particle_name (const G4String s) inline
Definition at line 65 of file EICG4dRICHHit.h.
View newest version in sPHENIX GitHub at line 65 of file EICG4dRICHHit.h
References pname, and Acts::UnitConstants::s.
Referenced by EICG4dRICHSteppingAction::UserSteppingAction().
void EICG4dRICHHit::set_pdg (const int i) inline
Definition at line 64 of file EICG4dRICHHit.h.
View newest version in sPHENIX GitHub at line 64 of file EICG4dRICHHit.h
References pdg.
Referenced by EICG4dRICHSteppingAction::UserSteppingAction().
void EICG4dRICHHit::set_petal (const int i) inline
Definition at line 62 of file EICG4dRICHHit.h.
View newest version in sPHENIX GitHub at line 62 of file EICG4dRICHHit.h
References petal.
Referenced by EICG4dRICHSteppingAction::UserSteppingAction().
void EICG4dRICHHit::set_position (const int i, const G4ThreeVector v) inline
Definition at line 54 of file EICG4dRICHHit.h.
View newest version in sPHENIX GitHub at line 54 of file EICG4dRICHHit.h
References hitPos, and v.
Referenced by EICG4dRICHSteppingAction::InitHit(), Reset(), and EICG4dRICHSteppingAction::UserSteppingAction().
void EICG4dRICHHit::set_process (const G4String s) inline
Definition at line 66 of file EICG4dRICHHit.h.
View newest version in sPHENIX GitHub at line 66 of file EICG4dRICHHit.h
References process, and Acts::UnitConstants::s.
Referenced by EICG4dRICHSteppingAction::UserSteppingAction().
void EICG4dRICHHit::set_psst (const int i) inline
Definition at line 63 of file EICG4dRICHHit.h.
View newest version in sPHENIX GitHub at line 63 of file EICG4dRICHHit.h
References psst.
Referenced by EICG4dRICHSteppingAction::UserSteppingAction().
void EICG4dRICHHit::set_shower_id (const int i) inline virtual
Reimplemented from PHG4Hit.
Definition at line 71 of file EICG4dRICHHit.h.
View newest version in sPHENIX GitHub at line 71 of file EICG4dRICHHit.h
References showerid.
void EICG4dRICHHit::set_t (const int i, const float f) inline virtual
Reimplemented from PHG4Hit.
Definition at line 59 of file EICG4dRICHHit.h.
View newest version in sPHENIX GitHub at line 59 of file EICG4dRICHHit.h
References t.
Referenced by EICG4dRICHSteppingAction::InitHit(), Reset(), and EICG4dRICHSteppingAction::UserSteppingAction().
void EICG4dRICHHit::set_trkid (const int i) inline virtual
Reimplemented from PHG4Hit.
Definition at line 72 of file EICG4dRICHHit.h.
View newest version in sPHENIX GitHub at line 72 of file EICG4dRICHHit.h
References trackid.
Referenced by EICG4dRICHSteppingAction::InitHit(), and EICG4dRICHSteppingAction::UserSteppingAction().
void EICG4dRICHHit::set_vertex_momentum_dir (const G4ThreeVector v) inline
Definition at line 58 of file EICG4dRICHHit.h.
View newest version in sPHENIX GitHub at line 58 of file EICG4dRICHHit.h
References v, and vtxMomDir.
Referenced by EICG4dRICHSteppingAction::UserSteppingAction().
void EICG4dRICHHit::set_vertex_position (const G4ThreeVector v) inline
Definition at line 57 of file EICG4dRICHHit.h.
View newest version in sPHENIX GitHub at line 57 of file EICG4dRICHHit.h
References v, and vtxPos.
Referenced by EICG4dRICHSteppingAction::UserSteppingAction().
Member Data Documentation
float EICG4dRICHHit::edep = NAN protected
Definition at line 93 of file EICG4dRICHHit.h.
View newest version in sPHENIX GitHub at line 93 of file EICG4dRICHHit.h
Referenced by get_edep(), print(), Reset(), and set_edep().
PHG4HitDefs::keytype EICG4dRICHHit::hitid = ULONG_LONG_MAX protected
Definition at line 90 of file EICG4dRICHHit.h.
View newest version in sPHENIX GitHub at line 90 of file EICG4dRICHHit.h
Referenced by get_detid(), get_hit_id(), print(), Reset(), and set_hit_id().
G4ThreeVector EICG4dRICHHit::hitPos[2] protected
Definition at line 82 of file EICG4dRICHHit.h.
View newest version in sPHENIX GitHub at line 82 of file EICG4dRICHHit.h
Referenced by get_position(), get_x(), get_y(), get_z(), and set_position().
G4String EICG4dRICHHit::hitSubtypeName protected
Definition at line 84 of file EICG4dRICHHit.h.
View newest version in sPHENIX GitHub at line 84 of file EICG4dRICHHit.h
Referenced by get_hit_subtype_name(), and set_hit_subtype_name().
G4String EICG4dRICHHit::hitTypeName protected
Definition at line 84 of file EICG4dRICHHit.h.
View newest version in sPHENIX GitHub at line 84 of file EICG4dRICHHit.h
Referenced by get_hit_type_name(), and set_hit_type_name().
G4ThreeVector EICG4dRICHHit::momDir protected
Definition at line 83 of file EICG4dRICHHit.h.
View newest version in sPHENIX GitHub at line 83 of file EICG4dRICHHit.h
Referenced by get_momentum_dir(), and set_momentum_dir().
G4ThreeVector EICG4dRICHHit::momVec protected
Definition at line 83 of file EICG4dRICHHit.h.
View newest version in sPHENIX GitHub at line 83 of file EICG4dRICHHit.h
Referenced by get_momentum(), and set_momentum().
int EICG4dRICHHit::parentID = -1 protected
Definition at line 89 of file EICG4dRICHHit.h.
View newest version in sPHENIX GitHub at line 89 of file EICG4dRICHHit.h
Referenced by get_parent_id(), and set_parent_id().
int EICG4dRICHHit::pdg = INT_MIN protected
Definition at line 87 of file EICG4dRICHHit.h.
View newest version in sPHENIX GitHub at line 87 of file EICG4dRICHHit.h
Referenced by get_pdg(), and set_pdg().
int EICG4dRICHHit::petal = INT_MIN protected
Definition at line 85 of file EICG4dRICHHit.h.
View newest version in sPHENIX GitHub at line 85 of file EICG4dRICHHit.h
Referenced by get_petal(), and set_petal().
G4String EICG4dRICHHit::pname protected
Definition at line 88 of file EICG4dRICHHit.h.
View newest version in sPHENIX GitHub at line 88 of file EICG4dRICHHit.h
Referenced by get_particle_name(), and set_particle_name().
G4String EICG4dRICHHit::process protected
Definition at line 88 of file EICG4dRICHHit.h.
View newest version in sPHENIX GitHub at line 88 of file EICG4dRICHHit.h
Referenced by get_process(), and set_process().
int EICG4dRICHHit::psst = INT_MIN protected
Definition at line 86 of file EICG4dRICHHit.h.
View newest version in sPHENIX GitHub at line 86 of file EICG4dRICHHit.h
Referenced by get_psst(), and set_psst().
int EICG4dRICHHit::showerid = INT_MIN protected
Definition at line 92 of file EICG4dRICHHit.h.
View newest version in sPHENIX GitHub at line 92 of file EICG4dRICHHit.h
Referenced by get_shower_id(), Reset(), and set_shower_id().
float EICG4dRICHHit::t[2] = {NAN, NAN} protected
Definition at line 81 of file EICG4dRICHHit.h.
View newest version in sPHENIX GitHub at line 81 of file EICG4dRICHHit.h
Referenced by get_delta_t(), get_t(), print(), and set_t().
int EICG4dRICHHit::trackid = INT_MIN protected
Definition at line 91 of file EICG4dRICHHit.h.
View newest version in sPHENIX GitHub at line 91 of file EICG4dRICHHit.h
Referenced by get_trkid(), print(), and set_trkid().
G4ThreeVector EICG4dRICHHit::vtxMomDir protected
Definition at line 83 of file EICG4dRICHHit.h.
View newest version in sPHENIX GitHub at line 83 of file EICG4dRICHHit.h
Referenced by get_vertex_momentum_dir(), and set_vertex_momentum_dir().
G4ThreeVector EICG4dRICHHit::vtxPos protected
Definition at line 83 of file EICG4dRICHHit.h.
View newest version in sPHENIX GitHub at line 83 of file EICG4dRICHHit.h
Referenced by get_vertex_position(), and set_vertex_position().
float EICG4dRICHHit::x[2] = {NAN, NAN} protected
Definition at line 78 of file EICG4dRICHHit.h.
View newest version in sPHENIX GitHub at line 78 of file EICG4dRICHHit.h
Referenced by eicpy.qaplots.LogAxis::apply(), print(), and eicpy.qaplots.LogAxis::rebin().
float EICG4dRICHHit::y[2] = {NAN, NAN} protected
Definition at line 79 of file EICG4dRICHHit.h.
View newest version in sPHENIX GitHub at line 79 of file EICG4dRICHHit.h
Referenced by eicpy.qaplots.LogAxis::apply(), print(), and eicpy.qaplots.LogAxis::rebin().
float EICG4dRICHHit::z[2] = {NAN, NAN} protected
Definition at line 80 of file EICG4dRICHHit.h.
View newest version in sPHENIX GitHub at line 80 of file EICG4dRICHHit.h
Referenced by eicpy.qaplots.LogAxis::apply(), print(), and eicpy.qaplots.LogAxis::rebin().
The documentation for this class was generated from the following files:
fun4all_eicdetectors/blob/master/simulation/g4simulation/g4drich/EICG4dRICHHit.h
fun4all_eicdetectors/blob/master/simulation/g4simulation/g4drich/EICG4dRICHHit.cc