EIC Software: EicRoot/blob/master/examples/tracking/config.1b/ip.C File Reference
ip.C File Reference
Functions
void ip ()
Function Documentation
void ip ()
Definition at line 6 of file ip.C.
View newest version in sPHENIX GitHub at line 6 of file ip.C
References EicGeoMap::AddGeantVolumeLevel(), EicGeoParData::AddLogicalVolumeGroup(), EicNamePatternHub< T >::AddPatternMatch(), EicGeoParData::CreateNewMap(), exit(), EicGeoParData::FinalizeOutput(), EicGeoParData::GetColorTable(), EicGeoParData::GetMedium(), EicGeoParData::GetTopVolume(), EicGeoParData::GetTransparencyTable(), eic::mm, rmax(), EicGeoParData::SetFileName(), EicGeoParData::SetMappingTableEntry(), and EicGeoMap::SetSingleSensorContainerVolume().
Referenced by allocate_2dim_array(), analysis(), beampipe(), BEmcProfile::BEmcProfile(), EtmDetector::Build(), KFParticle_Tools::calcMinIP(), CoordSystem::calculateExpansionRules(), TrKalmanFilter::CalculateHMatrix(), TrKalmanFilter::CalculateProcessNoise(), HoughTree::CheckCell(), KfMatrix::CheckPositivity(), genfit::GblFitter::cleanGblInfo(), cmd_line_variable_parser(), genfit::GblFitter::collectGblPoints(), EicHtcTask::ConstructLinearTrackApproximation(), CoordSystem::CoordSystem(), KfMatrix::CorrelationPrint(), digitization(), Mgrid::directFieldValue(), dqcd(), dqcdi(), dsigma(), EicSpaceRecoHit::EicSpaceRecoHit(), EicTrackingDigiHit3D::EicTrackingDigiHit3D(), fill_lower_triangle(), KfMatrix::FixPositivity(), KfMatrix::ForceSymmetric(), AnnularFieldSim::GenerateDistortionMaps(), AnnularFieldSim::GenerateSeparateDistortionMaps(), ResolutionLevel::GetCellSize(), BeastMagneticField::GetFieldValue(), EicTrackingRecoHit::getHMatrix(), HoughTree::GetInitializedCell(), EicKfNodeTemplateOrth3D::GetMeasurementNoise(), ResolutionLevel::GetParameterSplitFactor(), BEmcProfile::GetProb(), BEmcRec::GetProb(), ResolutionLevel::GetTotalDivisionNumber(), GFBookkeeping::GFBookkeeping(), EicTpcDigiHitProducer::HandleHit(), hijhrd(), hijsrt(), EicStlFactory::ImportAsciiStlSlpFile(), EicKfNodeTemplate::IncrementLinearTrackFitMatrices(), Mgrid::initializeAsSingleMgrid(), HtcKalmanFilter::InitializeMgridSlice(), TrKalmanNodeLocation::InitializeProcessNoiseMatrices(), KfMatrix::Invert(), CbmRichRingFitterEllipseTau::Jacobi(), KfMatrix::KFV(), linit(), lprwts(), lqcdpr(), lu1ent(), lu2ent(), lu3ent(), lu4ent(), ludecy(), lueevt(), luexec(), luindf(), lujoin(), luonia(), luprep(), lushow(), lustrf(), lutabu(), lweits(), lxp(), lyremn(), main(), Acts::detail::VerticesHelper::onHyperPlane(), ActsExamples::Pythia8Generator::operator()(), ActsExamples::ParametricParticleGenerator::operator()(), partonx(), partonx5(), partonx6(), TrKalmanNode::PerformRungeKuttaStep(), EtmDetector::PlaceG4Volume(), poldqcd(), poldqcdi(), poldsigma(), pollinit(), MgridInterpolation::postcookSequentialHighCommon(), BEmcRec::PredictEnergyProb(), KfMatrix::Print(), RawClusterBuilderTemplate::PrintCylGeom(), PHHepMCParticleSelectorDecayProductChain::process_event(), genfit::GblFitter::processTrackWithRep(), py1ent(), py2ent(), py3ent(), py4ent(), pycteq(), pyctq2(), pydecy(), pyeevt(), pyexec(), pyfscr(), pyhiremn(), pyhiresd(), pyhistfu(), pyindf(), pyjoin(), pymaxi(), pymihk(), pyonia(), pypdpi(), pypdpo(), pyprep(), pyptfs(), pyresd(), pysgex(), pyshow(), pyslha(), pystpi(), pystpr(), pystrf(), pysugi(), pytabu(), rcdaqopen(), oncsEventiterator::read_next_buffer(), fileEventiterator::read_next_buffer(), TrKalmanFilter::ResetNode(), FwdTrackFinder::ResetVtxNode(), ResolutionLevel::ResolutionLevel(), Acts::SurfaceView3DTest::run(), KFParticle_sPHENIX::setMinimumTrackIP(), KfMatrix::SetToProduct(), TrKalmanFilter::Transport(), genfit::GblFitterInfo::updateFitResults(), genfit::GblFitter::updateGblInfo(), FwdTrackFinder::UpdateVtxNode(), ogzBuffer::writeout(), olzoBuffer::writeout(), ospBuffer::writeout(), ophBuffer::writeout(), ActsExamples::TrackFitterPerformanceWriter::writeT(), and ActsExamples::RootTrajectoryWriter::writeT().