EIC Software: EicCadFileConfig Class Reference
EicCadFileConfig Class Reference
#include <EicRoot/blob/master/eic/cad/EicCadFileConfig.h>
Public Types
enum XYZ { _X_, _Y_, _Z_, _UNDEFINED_ }
Public Member Functions
EicCadFileConfig ()
~EicCadFileConfig ()
void SetUnits (double units)
void SetScale (double scale)
void SetStlVertexMergingTolerance (double tolerance)
void CreateMediaHub (char *media_name=0)
void SetStlQualityCoefficient (double cff)
double GetScale () const
double GetUnits () const
EicMediaHub * GetMediaHub (void) const
double scale () const
double units () const
EicMediaHub * mhub (void) const
double GetStlVertexMergingTolerance (void) const
double GetStlQualityCoefficient (void) const
void SetRotationY (double angle)
unsigned GetRotationAxis (void) const
double GetRotationAngle (void) const
Private Attributes
double mScale
double mUnits
double mStlVertexMergingTolerance
XYZ mRotationAxis
double mRotationAngle
double mStlQualityCoefficient
EicMediaHub * mMediaHub
Detailed Description
Definition at line 11 of file EicCadFileConfig.h.
View newest version in sPHENIX GitHub at line 11 of file EicCadFileConfig.h
Member Enumeration Documentation
enum EicCadFileConfig::XYZ
Enumerator:
_X_
_Y_
_Z_
_UNDEFINED_
Definition at line 13 of file EicCadFileConfig.h.
View newest version in sPHENIX GitHub at line 13 of file EicCadFileConfig.h
Constructor & Destructor Documentation
EicCadFileConfig::EicCadFileConfig () inline
Definition at line 16 of file EicCadFileConfig.h.
View newest version in sPHENIX GitHub at line 16 of file EicCadFileConfig.h
EicCadFileConfig::~EicCadFileConfig () inline
Definition at line 19 of file EicCadFileConfig.h.
View newest version in sPHENIX GitHub at line 19 of file EicCadFileConfig.h
Member Function Documentation
void EicCadFileConfig::CreateMediaHub (char * media_name = 0) inline
Definition at line 28 of file EicCadFileConfig.h.
View newest version in sPHENIX GitHub at line 28 of file EicCadFileConfig.h
References mMediaHub.
Referenced by EicCadWizard::AssembleRootFiles(), EicCadWizard::CreateBooleanSolidRootFile(), EicCadWizard::CreateGhostSolidRootFile(), EicCadWizard::CreateStlSolidRootFile(), and EicCadFile::EicCadFile().
EicMediaHub* EicCadFileConfig::GetMediaHub (void) const inline
Definition at line 33 of file EicCadFileConfig.h.
View newest version in sPHENIX GitHub at line 33 of file EicCadFileConfig.h
References mMediaHub.
double EicCadFileConfig::GetRotationAngle (void) const inline
Definition at line 45 of file EicCadFileConfig.h.
View newest version in sPHENIX GitHub at line 45 of file EicCadFileConfig.h
unsigned EicCadFileConfig::GetRotationAxis (void) const inline
Definition at line 44 of file EicCadFileConfig.h.
View newest version in sPHENIX GitHub at line 44 of file EicCadFileConfig.h
References mRotationAxis.
double EicCadFileConfig::GetScale () const inline
Definition at line 31 of file EicCadFileConfig.h.
View newest version in sPHENIX GitHub at line 31 of file EicCadFileConfig.h
References mScale.
double EicCadFileConfig::GetStlQualityCoefficient (void) const inline
Definition at line 40 of file EicCadFileConfig.h.
View newest version in sPHENIX GitHub at line 40 of file EicCadFileConfig.h
References mStlQualityCoefficient.
double EicCadFileConfig::GetStlVertexMergingTolerance (void) const inline
Definition at line 39 of file EicCadFileConfig.h.
View newest version in sPHENIX GitHub at line 39 of file EicCadFileConfig.h
References mStlVertexMergingTolerance.
Referenced by EicStlFactory::_ConstructGeometry(), and EicStlFactory::CreateRootFile().
double EicCadFileConfig::GetUnits () const inline
Definition at line 32 of file EicCadFileConfig.h.
View newest version in sPHENIX GitHub at line 32 of file EicCadFileConfig.h
References mUnits.
EicMediaHub* EicCadFileConfig::mhub (void) const inline
Definition at line 37 of file EicCadFileConfig.h.
View newest version in sPHENIX GitHub at line 37 of file EicCadFileConfig.h
References mMediaHub.
Referenced by EicCadWizard::AssembleRootFiles(), EicCadFile::ConstructGeometry(), EicCadWizard::CreateBooleanSolidRootFile(), EicCadWizard::CreateGhostSolidRootFile(), EicStlFactory::CreateRootFile(), EicCadWizard::CreateStlSolidRootFile(), EicStlFactory::EicStlFactory(), EicStlFactory::ImportAsciiStlSlpFile(), and EicStlFactory::ImportBinaryStlFile().
double EicCadFileConfig::scale () const inline
Definition at line 35 of file EicCadFileConfig.h.
View newest version in sPHENIX GitHub at line 35 of file EicCadFileConfig.h
References mScale.
Referenced by EicStlFactory::EicStlFactory(), mrseb(), pycba2(), pycbal(), pycrth(), SetScale(), strc10(), strc11(), strc20(), and strc21().
void EicCadFileConfig::SetRotationY (double angle) inline
Definition at line 43 of file EicCadFileConfig.h.
View newest version in sPHENIX GitHub at line 43 of file EicCadFileConfig.h
References _Y_, mRotationAngle, and mRotationAxis.
void EicCadFileConfig::SetScale (double scale) inline
Definition at line 25 of file EicCadFileConfig.h.
View newest version in sPHENIX GitHub at line 25 of file EicCadFileConfig.h
References mScale, and scale().
void EicCadFileConfig::SetStlQualityCoefficient (double cff) inline
Definition at line 29 of file EicCadFileConfig.h.
View newest version in sPHENIX GitHub at line 29 of file EicCadFileConfig.h
References mStlQualityCoefficient.
void EicCadFileConfig::SetStlVertexMergingTolerance (double tolerance) inline
Definition at line 27 of file EicCadFileConfig.h.
View newest version in sPHENIX GitHub at line 27 of file EicCadFileConfig.h
References mStlVertexMergingTolerance, and Acts::Test::tolerance.
void EicCadFileConfig::SetUnits (double units) inline
Definition at line 22 of file EicCadFileConfig.h.
View newest version in sPHENIX GitHub at line 22 of file EicCadFileConfig.h
References mUnits, and units().
Referenced by simulation().
double EicCadFileConfig::units () const inline
Definition at line 36 of file EicCadFileConfig.h.
View newest version in sPHENIX GitHub at line 36 of file EicCadFileConfig.h
References mUnits.
Referenced by EicStlFactory::EicStlFactory(), and SetUnits().
Member Data Documentation
EicMediaHub* EicCadFileConfig::mMediaHub private
Definition at line 61 of file EicCadFileConfig.h.
View newest version in sPHENIX GitHub at line 61 of file EicCadFileConfig.h
Referenced by CreateMediaHub(), GetMediaHub(), and mhub().
double EicCadFileConfig::mRotationAngle private
Definition at line 53 of file EicCadFileConfig.h.
View newest version in sPHENIX GitHub at line 53 of file EicCadFileConfig.h
Referenced by SetRotationY().
XYZ EicCadFileConfig::mRotationAxis private
Definition at line 52 of file EicCadFileConfig.h.
View newest version in sPHENIX GitHub at line 52 of file EicCadFileConfig.h
Referenced by GetRotationAxis(), and SetRotationY().
double EicCadFileConfig::mScale private
Definition at line 45 of file EicCadFileConfig.h.
View newest version in sPHENIX GitHub at line 45 of file EicCadFileConfig.h
Referenced by GetScale(), scale(), and SetScale().
double EicCadFileConfig::mStlQualityCoefficient private
Definition at line 59 of file EicCadFileConfig.h.
View newest version in sPHENIX GitHub at line 59 of file EicCadFileConfig.h
Referenced by GetStlQualityCoefficient(), and SetStlQualityCoefficient().
double EicCadFileConfig::mStlVertexMergingTolerance private
Definition at line 45 of file EicCadFileConfig.h.
View newest version in sPHENIX GitHub at line 45 of file EicCadFileConfig.h
Referenced by GetStlVertexMergingTolerance(), and SetStlVertexMergingTolerance().
double EicCadFileConfig::mUnits private
Definition at line 45 of file EicCadFileConfig.h.
View newest version in sPHENIX GitHub at line 45 of file EicCadFileConfig.h
Referenced by GetUnits(), SetUnits(), and units().
The documentation for this class was generated from the following file:
EicRoot/blob/master/eic/cad/EicCadFileConfig.h