EIC Software: RKTools Namespace Reference
RKTools Namespace Reference
RKTrackRep
Functions
void J_pMTxcov5xJ_pM (const M5x7 &J_pM, const M5x5 &cov5, M7x7 &out7)
void J_pMTxcov5xJ_pM (const M5x6 &J_pM, const M5x5 &cov5, M6x6 &out6)
void J_MpTxcov7xJ_Mp (const M7x5 &J_Mp, const M7x7 &cov7, M5x5 &out5)
void J_MpTxcov6xJ_Mp (const M6x5 &J_Mp, const M6x6 &cov6, M5x5 &out5)
void J_MMTxcov7xJ_MM (const M7x7 &J_MM, const M7x7 &cov7, M7x7 &out7)
void J_MMxJ_MM (M7x7 &J_MM, const M7x7 &J_MM_old)
void printDim (const double *mat, unsigned int dimX, unsigned int dimY)
Function Documentation
void RKTools::J_MMTxcov7xJ_MM (const M7x7 & J_MM, const M7x7 & cov7, M7x7 & out7)
Definition at line 276 of file RKTools.cxx.
View newest version in sPHENIX GitHub at line 276 of file RKTools.cxx
Referenced by RKTrackRep::Extrap().
void RKTools::J_MMxJ_MM (M7x7 & J_MM, const M7x7 & J_MM_old)
Definition at line 348 of file RKTools.cxx.
View newest version in sPHENIX GitHub at line 348 of file RKTools.cxx
void RKTools::J_MpTxcov6xJ_Mp (const M6x5 & J_Mp, const M6x6 & cov6, M5x5 & out5)
Definition at line 211 of file RKTools.cxx.
View newest version in sPHENIX GitHub at line 211 of file RKTools.cxx
Referenced by RKTrackRep::transformM6P().
void RKTools::J_MpTxcov7xJ_Mp (const M7x5 & J_Mp, const M7x7 & cov7, M5x5 & out5)
Definition at line 151 of file RKTools.cxx.
View newest version in sPHENIX GitHub at line 151 of file RKTools.cxx
Referenced by RKTrackRep::transformM7P().
void RKTools::J_pMTxcov5xJ_pM (const M5x7 & J_pM, const M5x5 & cov5, M7x7 & out7)
Definition at line 9 of file RKTools.cxx.
View newest version in sPHENIX GitHub at line 9 of file RKTools.cxx
Referenced by RKTrackRep::transformPM6(), and RKTrackRep::transformPM7().
void RKTools::J_pMTxcov5xJ_pM (const M5x6 & J_pM, const M5x5 & cov5, M6x6 & out6)
Definition at line 82 of file RKTools.cxx.
View newest version in sPHENIX GitHub at line 82 of file RKTools.cxx
void RKTools::printDim (const double * mat, unsigned int dimX, unsigned int dimY)
Definition at line 421 of file RKTools.cxx.
View newest version in sPHENIX GitHub at line 421 of file RKTools.cxx
References printf().