EIC Software: photonElectronLuminosity Class Reference
photonElectronLuminosity Class Reference
#include <estarlight/blob/master/include/gammaeluminosity.h>
Public Member Functions
photonElectronLuminosity (const inputParameters &input, beamBeamSystem &bbsystem)
~photonElectronLuminosity ()
Public Member Functions inherited from photonNucleusCrossSection
photonNucleusCrossSection (const inputParameters &input, const beamBeamSystem &bbsystem)
~photonNucleusCrossSection ()
double slopeParameter () const
returns slope of t-distribution [(GeV/c)^{-2}]
double getChannelMass () const
returns mass of the produced system [GeV/c^2]
double getBNORM () const
beamBeamSystem getbbs () const
returns beamBeamSystem
double vmPhotonCoupling () const
vectormeson-photon coupling constant f_v / 4 pi (cf. Eq. 10 in KN PRC 60 (1999) 014903)
double vmQ2Power (double Q2) const
double getDefaultC () const
double maxPhotonEnergy () const
returns max photon energy in lab frame [GeV] (for vectormesons only)
void crossSectionCalculation (const double bwnormsave)
double backwardsPropagationOmegaCrossSection (const double targetEgamma)
double getcsgA (const double Egamma, const double Q2, const int beam)
double e_getcsgA (const double Egamma, double Q2, const double W, const int beam)
double getcsgA_Q2_dep (const double Q2)
double photonFlux (const double Egamma, const int beam)
double photonFlux (const double Egamma, const double Q2)
double integrated_Q2_dep (const double Egamma, const double _min=0, const double _max=0)
double integrated_x_section (const double Egamma, const double _min=0, const double _max=0)
std::pair< double, double > * Q2arraylimits (double const Egamma)
double g (double const Egamma, double const Q2)
double sigmagp (const double Wgp)
double sigma_A (const double sig_N, const int beam)
double sigma_N (const double Wgp)
double breitWigner (const double W, const double C)
double nepoint (const double Egamma, const double bmin)
double getPhotonNucleusSigma () const
void setPhotonNucleusSigma (double sigma)
Private Member Functions
void photonNucleusDifferentialLuminosity ()
std::string gammaTableParse (int ii, int jj)
Private Attributes
const double _protonEnergy
const double _electronEnergy
const double _beamLorentzGamma
const std::string _baseFileName
const double _maxW
const double _minW
const unsigned int _nmbWBins
const double _maxRapidity
const unsigned int _nmbRapidityBins
const int _nEBins
const double _minGammaQ2
const double _maxGammaQ2
const unsigned int _nmbGammaQ2Bins
const double _cmsMaxPhotonEnergy
const double _cmsMinPhotonEnergy
const double _targetMaxPhotonEnergy
const double _targetMinPhotonEnergy
const int _productionMode
const int _beamBreakupMode
Additional Inherited Members
Protected Attributes inherited from photonNucleusCrossSection
const unsigned int _nWbins
const unsigned int _nYbins
const double _wMin
const double _wMax
const double _yMax
const double _beamLorentzGamma
double _photonNucleusSigma
int _printDef
int _impulseSelected
int _quantumGlauber
Detailed Description
Definition at line 43 of file gammaeluminosity.h.
View newest version in sPHENIX GitHub at line 43 of file gammaeluminosity.h
Constructor & Destructor Documentation
photonElectronLuminosity::photonElectronLuminosity (const inputParameters & input, beamBeamSystem & bbsystem)
Definition at line 52 of file gammaeluminosity.cpp.
View newest version in sPHENIX GitHub at line 52 of file gammaeluminosity.cpp
References photonNucleusDifferentialLuminosity().
photonElectronLuminosity::~photonElectronLuminosity ()
Definition at line 81 of file gammaeluminosity.cpp.
View newest version in sPHENIX GitHub at line 81 of file gammaeluminosity.cpp
Member Function Documentation
string photonElectronLuminosity::gammaTableParse (int ii, int jj) private
Definition at line 201 of file gammaeluminosity.cpp.
View newest version in sPHENIX GitHub at line 201 of file gammaeluminosity.cpp
void photonElectronLuminosity::photonNucleusDifferentialLuminosity () private
Definition at line 86 of file gammaeluminosity.cpp.
View newest version in sPHENIX GitHub at line 86 of file gammaeluminosity.cpp
References _baseFileName, _beamBreakupMode, _beamLorentzGamma, _maxRapidity, _maxW, _minW, _nEBins, _nmbGammaQ2Bins, _nmbRapidityBins, _nmbWBins, photonNucleusCrossSection::_nWbins, photonNucleusCrossSection::_nYbins, _productionMode, _targetMaxPhotonEnergy, _targetMinPhotonEnergy, photonNucleusCrossSection::_wMax, photonNucleusCrossSection::_wMin, photonNucleusCrossSection::_yMax, nucleus::A(), photonNucleusCrossSection::breitWigner(), Acts::UnitConstants::C, starlightConstants::deuteronSlopePar, Acts::Test::dY, beamBeamSystem::electronBeam(), photonNucleusCrossSection::g(), photonNucleusCrossSection::getbbs(), photonNucleusCrossSection::getcsgA(), photonNucleusCrossSection::getDefaultC(), photonNucleusCrossSection::integrated_Q2_dep(), photonNucleusCrossSection::Q2arraylimits(), beamBeamSystem::targetBeam(), and nucleus::Z().
Referenced by photonElectronLuminosity().
Member Data Documentation
const std::string photonElectronLuminosity::_baseFileName private
Definition at line 56 of file gammaeluminosity.h.
View newest version in sPHENIX GitHub at line 56 of file gammaeluminosity.h
Referenced by photonNucleusDifferentialLuminosity().
const int photonElectronLuminosity::_beamBreakupMode private
Definition at line 71 of file gammaeluminosity.h.
View newest version in sPHENIX GitHub at line 71 of file gammaeluminosity.h
Referenced by photonNucleusDifferentialLuminosity().
const double photonElectronLuminosity::_beamLorentzGamma private
Definition at line 55 of file gammaeluminosity.h.
View newest version in sPHENIX GitHub at line 55 of file gammaeluminosity.h
Referenced by photonNucleusDifferentialLuminosity().
const double photonElectronLuminosity::_cmsMaxPhotonEnergy private
Definition at line 66 of file gammaeluminosity.h.
View newest version in sPHENIX GitHub at line 66 of file gammaeluminosity.h
const double photonElectronLuminosity::_cmsMinPhotonEnergy private
Definition at line 67 of file gammaeluminosity.h.
View newest version in sPHENIX GitHub at line 67 of file gammaeluminosity.h
const double photonElectronLuminosity::_electronEnergy private
Definition at line 54 of file gammaeluminosity.h.
View newest version in sPHENIX GitHub at line 54 of file gammaeluminosity.h
const double photonElectronLuminosity::_maxGammaQ2 private
Definition at line 64 of file gammaeluminosity.h.
View newest version in sPHENIX GitHub at line 64 of file gammaeluminosity.h
const double photonElectronLuminosity::_maxRapidity private
Definition at line 60 of file gammaeluminosity.h.
View newest version in sPHENIX GitHub at line 60 of file gammaeluminosity.h
Referenced by photonNucleusDifferentialLuminosity().
const double photonElectronLuminosity::_maxW private
Definition at line 57 of file gammaeluminosity.h.
View newest version in sPHENIX GitHub at line 57 of file gammaeluminosity.h
Referenced by photonNucleusDifferentialLuminosity().
const double photonElectronLuminosity::_minGammaQ2 private
Definition at line 63 of file gammaeluminosity.h.
View newest version in sPHENIX GitHub at line 63 of file gammaeluminosity.h
const double photonElectronLuminosity::_minW private
Definition at line 58 of file gammaeluminosity.h.
View newest version in sPHENIX GitHub at line 58 of file gammaeluminosity.h
Referenced by photonNucleusDifferentialLuminosity().
const int photonElectronLuminosity::_nEBins private
Definition at line 62 of file gammaeluminosity.h.
View newest version in sPHENIX GitHub at line 62 of file gammaeluminosity.h
Referenced by photonNucleusDifferentialLuminosity().
const unsigned int photonElectronLuminosity::_nmbGammaQ2Bins private
Definition at line 65 of file gammaeluminosity.h.
View newest version in sPHENIX GitHub at line 65 of file gammaeluminosity.h
Referenced by photonNucleusDifferentialLuminosity().
const unsigned int photonElectronLuminosity::_nmbRapidityBins private
Definition at line 61 of file gammaeluminosity.h.
View newest version in sPHENIX GitHub at line 61 of file gammaeluminosity.h
Referenced by photonNucleusDifferentialLuminosity().
const unsigned int photonElectronLuminosity::_nmbWBins private
Definition at line 59 of file gammaeluminosity.h.
View newest version in sPHENIX GitHub at line 59 of file gammaeluminosity.h
Referenced by photonNucleusDifferentialLuminosity().
const int photonElectronLuminosity::_productionMode private
Definition at line 70 of file gammaeluminosity.h.
View newest version in sPHENIX GitHub at line 70 of file gammaeluminosity.h
Referenced by photonNucleusDifferentialLuminosity().
const double photonElectronLuminosity::_protonEnergy private
Definition at line 53 of file gammaeluminosity.h.
View newest version in sPHENIX GitHub at line 53 of file gammaeluminosity.h
const double photonElectronLuminosity::_targetMaxPhotonEnergy private
Definition at line 68 of file gammaeluminosity.h.
View newest version in sPHENIX GitHub at line 68 of file gammaeluminosity.h
Referenced by photonNucleusDifferentialLuminosity().
const double photonElectronLuminosity::_targetMinPhotonEnergy private
Definition at line 69 of file gammaeluminosity.h.
View newest version in sPHENIX GitHub at line 69 of file gammaeluminosity.h
Referenced by photonNucleusDifferentialLuminosity().
The documentation for this class was generated from the following files:
estarlight/blob/master/include/gammaeluminosity.h
estarlight/blob/master/src/gammaeluminosity.cpp