EIC Software: PndRecoKalmanTask Class Reference
PndRecoKalmanTask Class Reference
#include <EicRoot/blob/master/GenfitTools/recotasks/PndRecoKalmanTask.h>
Public Member Functions
PndRecoKalmanTask (const char *name="Genfit", Int_t iVerbose=0)
~PndRecoKalmanTask ()
void SetTrackInBranchName (const TString &name)
void SetTrackInIDBranchName (const TString &name)
void SetTrackOutBranchName (const TString &name)
void SetMvdBranchName (const TString &name)
void SetCentralTrackerBranchName (const TString &name)
void SetPersistence (Bool_t opt=kTRUE)
void SetGeane (Bool_t opt=kTRUE)
void SetIdealHyp (Bool_t opt=kTRUE)
void SetDaf (Bool_t opt=kTRUE)
void SetPropagateToIP (Bool_t opt=kTRUE)
void SetPerpPlane (Bool_t opt=kTRUE)
void SetTrackRep (Short_t num)
void SetParticleHypo (TString s)
void SetParticleHypo (Int_t h)
void SetBusyCut (Int_t b)
virtual InitStatus Init ()
void SetParContainers ()
virtual void Exec (Option_t *opt)
void StoreTrackParameterization (void)
Public Member Functions inherited from FairTask
FairTask ()
FairTask (const char *name, Int_t iVerbose=1)
virtual ~FairTask ()
void InitTask ()
void ReInitTask ()
void SetParTask ()
virtual void FinishTask ()
virtual void FinishEvent ()
void SetVerbose (Int_t iVerbose)
void SetInputPersistance (Bool_t val)
void CheckInputPersistance (TString branchName)
Protected Member Functions
ClassDef (PndRecoKalmanTask, 2)
Protected Member Functions inherited from FairTask
virtual InitStatus ReInit ()
virtual void Finish ()
void InitTasks ()
void ReInitTasks ()
void SetParTasks ()
void FinishTasks ()
void FinishEvents ()
Protected Attributes
TClonesArray * fTrackArray
TClonesArray * fTrackIDArray
Input TCA for PndTrack.
TClonesArray * fMCTrackArray
Input TCA for PndTrackID.
TClonesArray * fFitTrackArray
Input TCA for PndMCTrack.
TString fTrackInBranchName
Output TCA for track.
TString fTrackInIDBranchName
Name of the input TCA.
TString fTrackOutBranchName
Name of the input TCA.
TString fMvdBranchName
Name of the output TCA.
TString fCentralTrackerBranchName
Name of the TCA for MVD.
PndRecoKalmanFit * fFitter
Name of the TCA for central tracker.
PndRecoDafFit * fDafFitter
TDatabasePDG * pdg
Bool_t fPersistence
Particle DB.
Bool_t fUseGeane
Persistence.
Bool_t fSmoothing
Flag to use Geane.
Bool_t fIdealHyp
Flag to set on smoothing (not used)
Bool_t fDaf
Flag to use MC particle hypothesis.
Bool_t fPropagateToIP
Flag to use Deterministic Annealing.
Bool_t fPerpPlane
Flag to propagate the parameters to the interaction point (kTRUE)
Short_t fTrackRep
Flag to use as initial plane the one perpendicular to the track (kFALSE)
Int_t fNumIt
(0) GeaneTrackRep, 1 RKTrackRep
Int_t fPDGHyp
Number of iterations.
Int_t fBusyCut
Hypothesis.
bool mStoreTrackParameterization
Skip too busy events with more tracks.
Protected Attributes inherited from FairTask
Int_t fVerbose
Int_t fInputPersistance
Indicates if input branch is persistant.
FairLogger * fLogger
Detailed Description
Definition at line 33 of file PndRecoKalmanTask.h.
View newest version in sPHENIX GitHub at line 33 of file PndRecoKalmanTask.h
Constructor & Destructor Documentation
PndRecoKalmanTask::PndRecoKalmanTask (const char * name = "Genfit", Int_t iVerbose = 0)
Definition at line 38 of file PndRecoKalmanTask.cxx.
View newest version in sPHENIX GitHub at line 38 of file PndRecoKalmanTask.cxx
References fDafFitter, fFitter, and fFitTrackArray.
PndRecoKalmanTask::~PndRecoKalmanTask ()
Definition at line 52 of file PndRecoKalmanTask.cxx.
View newest version in sPHENIX GitHub at line 52 of file PndRecoKalmanTask.cxx
Member Function Documentation
PndRecoKalmanTask::ClassDef (PndRecoKalmanTask , 2) protected
void PndRecoKalmanTask::Exec (Option_t * opt) virtual
Reimplemented in EicRecoKalmanTask.
Definition at line 144 of file PndRecoKalmanTask.cxx.
View newest version in sPHENIX GitHub at line 144 of file PndRecoKalmanTask.cxx
References fBusyCut, fDaf, fDafFitter, fFitter, fFitTrackArray, fIdealHyp, PndRecoDafFit::Fit(), PndRecoKalmanFit::Fit(), fMCTrackArray, fPDGHyp, fTrackArray, fTrackIDArray, fTrackInBranchName, FairTask::fVerbose, FairRootManager::GetBranchId(), PndTrack::GetChi2(), PndTrackID::GetCorrTrackID(), PndTrack::GetFlag(), PndTrackID::GetNCorrTrackId(), PndTrack::GetNDF(), PndTrack::GetParamFirst(), PndTrack::GetParamLast(), PndMCTrack::GetPdgCode(), PndTrack::GetPidHypo(), FairTrackPar::GetQ(), PndTrack::GetTrackCand(), FairRootManager::Instance(), charm_jet_coverage::mom, PndTrack::mParameterizations, mStoreTrackParameterization, pdg, pos(), printf(), and PndTrack::SetFlag().
Referenced by EicRecoKalmanTask::Exec().
InitStatus PndRecoKalmanTask::Init (void) virtual
Intialisation at begin of run. To be implemented in the derived class. Success If not kSUCCESS, task will be set inactive.
Reimplemented from FairTask.
Reimplemented in EicRecoKalmanTask.
Definition at line 57 of file PndRecoKalmanTask.cxx.
View newest version in sPHENIX GitHub at line 57 of file PndRecoKalmanTask.cxx
References fCentralTrackerBranchName, fDaf, fDafFitter, fFitter, fFitTrackArray, fIdealHyp, fMCTrackArray, fMvdBranchName, fNumIt, fPerpPlane, fPersistence, fPropagateToIP, fTrackArray, fTrackIDArray, fTrackInBranchName, fTrackInIDBranchName, fTrackOutBranchName, fTrackRep, fUseGeane, FairTask::fVerbose, FairRootManager::GetObject(), PndRecoKalmanFit::Init(), PndRecoDafFit::Init(), FairRootManager::Instance(), kERROR, kFATAL, kSUCCESS, pdg, FairRootManager::Register(), PndRecoKalmanFit::SetCentralTrackerBranchName(), PndRecoDafFit::SetCentralTrackerBranchName(), PndRecoKalmanFit::SetGeane(), PndRecoDafFit::SetGeane(), PndRecoDafFit::SetMvdBranchName(), PndRecoKalmanFit::SetMvdBranchName(), PndRecoKalmanFit::SetNumIterations(), PndRecoKalmanFit::SetPerpPlane(), PndRecoDafFit::SetPerpPlane(), PndRecoDafFit::SetPropagateToIP(), PndRecoKalmanFit::SetPropagateToIP(), PndRecoKalmanFit::SetTrackRep(), PndRecoDafFit::SetTrackRep(), PndRecoDafFit::SetVerbose(), and PndRecoKalmanFit::SetVerbose().
Referenced by EicRecoKalmanTask::Init().
void PndRecoKalmanTask::SetBusyCut (Int_t b) inline
Definition at line 60 of file PndRecoKalmanTask.h.
View newest version in sPHENIX GitHub at line 60 of file PndRecoKalmanTask.h
References fBusyCut.
Referenced by EicRecoKalmanTask::EicRecoKalmanTask().
void PndRecoKalmanTask::SetCentralTrackerBranchName (const TString & name) inline
Definition at line 50 of file PndRecoKalmanTask.h.
View newest version in sPHENIX GitHub at line 50 of file PndRecoKalmanTask.h
References fCentralTrackerBranchName, and name.
void PndRecoKalmanTask::SetDaf (Bool_t opt = kTRUE) inline
Definition at line 54 of file PndRecoKalmanTask.h.
View newest version in sPHENIX GitHub at line 54 of file PndRecoKalmanTask.h
References fDaf.
Referenced by EicRecoKalmanTask::Init().
void PndRecoKalmanTask::SetGeane (Bool_t opt = kTRUE) inline
Definition at line 52 of file PndRecoKalmanTask.h.
View newest version in sPHENIX GitHub at line 52 of file PndRecoKalmanTask.h
References fUseGeane.
void PndRecoKalmanTask::SetIdealHyp (Bool_t opt = kTRUE) inline
Definition at line 53 of file PndRecoKalmanTask.h.
View newest version in sPHENIX GitHub at line 53 of file PndRecoKalmanTask.h
References fIdealHyp.
void PndRecoKalmanTask::SetMvdBranchName (const TString & name) inline
Definition at line 49 of file PndRecoKalmanTask.h.
View newest version in sPHENIX GitHub at line 49 of file PndRecoKalmanTask.h
References fMvdBranchName, and name.
void PndRecoKalmanTask::SetParContainers () virtual
Intialise parameter containers. To be implemented in the derived class.
Reimplemented from FairTask.
Definition at line 136 of file PndRecoKalmanTask.cxx.
View newest version in sPHENIX GitHub at line 136 of file PndRecoKalmanTask.cxx
References FairRuntimeDb::getContainer(), FairRun::GetRuntimeDb(), and FairRunAna::Instance().
void PndRecoKalmanTask::SetParticleHypo (TString s)
Definition at line 256 of file PndRecoKalmanTask.cxx.
View newest version in sPHENIX GitHub at line 256 of file PndRecoKalmanTask.cxx
References fPDGHyp.
void PndRecoKalmanTask::SetParticleHypo (Int_t h)
Definition at line 275 of file PndRecoKalmanTask.cxx.
View newest version in sPHENIX GitHub at line 275 of file PndRecoKalmanTask.cxx
References kdfinder::abs(), and fPDGHyp.
void PndRecoKalmanTask::SetPerpPlane (Bool_t opt = kTRUE) inline
Definition at line 56 of file PndRecoKalmanTask.h.
View newest version in sPHENIX GitHub at line 56 of file PndRecoKalmanTask.h
References fPerpPlane.
void PndRecoKalmanTask::SetPersistence (Bool_t opt = kTRUE) inline
Definition at line 51 of file PndRecoKalmanTask.h.
View newest version in sPHENIX GitHub at line 51 of file PndRecoKalmanTask.h
References fPersistence.
void PndRecoKalmanTask::SetPropagateToIP (Bool_t opt = kTRUE) inline
Definition at line 55 of file PndRecoKalmanTask.h.
View newest version in sPHENIX GitHub at line 55 of file PndRecoKalmanTask.h
References fPropagateToIP.
void PndRecoKalmanTask::SetTrackInBranchName (const TString & name) inline
Definition at line 46 of file PndRecoKalmanTask.h.
View newest version in sPHENIX GitHub at line 46 of file PndRecoKalmanTask.h
References fTrackInBranchName, and name.
Referenced by EicRecoKalmanTask::Init().
void PndRecoKalmanTask::SetTrackInIDBranchName (const TString & name) inline
Definition at line 47 of file PndRecoKalmanTask.h.
View newest version in sPHENIX GitHub at line 47 of file PndRecoKalmanTask.h
References fTrackInIDBranchName, and name.
void PndRecoKalmanTask::SetTrackOutBranchName (const TString & name) inline
Definition at line 48 of file PndRecoKalmanTask.h.
View newest version in sPHENIX GitHub at line 48 of file PndRecoKalmanTask.h
References fTrackOutBranchName, and name.
void PndRecoKalmanTask::SetTrackRep (Short_t num) inline
Definition at line 57 of file PndRecoKalmanTask.h.
View newest version in sPHENIX GitHub at line 57 of file PndRecoKalmanTask.h
References fTrackRep, and num.
void PndRecoKalmanTask::StoreTrackParameterization (void) inline
Definition at line 67 of file PndRecoKalmanTask.h.
View newest version in sPHENIX GitHub at line 67 of file PndRecoKalmanTask.h
References mStoreTrackParameterization.
Referenced by reconstruction().
Member Data Documentation
Int_t PndRecoKalmanTask::fBusyCut protected
Hypothesis.
Definition at line 99 of file PndRecoKalmanTask.h.
View newest version in sPHENIX GitHub at line 99 of file PndRecoKalmanTask.h
Referenced by Exec(), and SetBusyCut().
TString PndRecoKalmanTask::fCentralTrackerBranchName protected
Name of the TCA for MVD.
Definition at line 82 of file PndRecoKalmanTask.h.
View newest version in sPHENIX GitHub at line 82 of file PndRecoKalmanTask.h
Referenced by Init(), and SetCentralTrackerBranchName().
Bool_t PndRecoKalmanTask::fDaf protected
Flag to use MC particle hypothesis.
Definition at line 93 of file PndRecoKalmanTask.h.
View newest version in sPHENIX GitHub at line 93 of file PndRecoKalmanTask.h
Referenced by Exec(), Init(), and SetDaf().
PndRecoDafFit* PndRecoKalmanTask::fDafFitter protected
Definition at line 85 of file PndRecoKalmanTask.h.
View newest version in sPHENIX GitHub at line 85 of file PndRecoKalmanTask.h
Referenced by Exec(), Init(), and PndRecoKalmanTask().
PndRecoKalmanFit* PndRecoKalmanTask::fFitter protected
Name of the TCA for central tracker.
Definition at line 84 of file PndRecoKalmanTask.h.
View newest version in sPHENIX GitHub at line 84 of file PndRecoKalmanTask.h
Referenced by Exec(), EicRecoKalmanTask::Init(), Init(), and PndRecoKalmanTask().
TClonesArray* PndRecoKalmanTask::fFitTrackArray protected
Input TCA for PndMCTrack.
Definition at line 75 of file PndRecoKalmanTask.h.
View newest version in sPHENIX GitHub at line 75 of file PndRecoKalmanTask.h
Referenced by Exec(), Init(), and PndRecoKalmanTask().
Bool_t PndRecoKalmanTask::fIdealHyp protected
Flag to set on smoothing (not used)
Definition at line 92 of file PndRecoKalmanTask.h.
View newest version in sPHENIX GitHub at line 92 of file PndRecoKalmanTask.h
Referenced by Exec(), Init(), and SetIdealHyp().
TClonesArray* PndRecoKalmanTask::fMCTrackArray protected
Input TCA for PndTrackID.
Definition at line 74 of file PndRecoKalmanTask.h.
View newest version in sPHENIX GitHub at line 74 of file PndRecoKalmanTask.h
Referenced by Exec(), and Init().
TString PndRecoKalmanTask::fMvdBranchName protected
Name of the output TCA.
Definition at line 81 of file PndRecoKalmanTask.h.
View newest version in sPHENIX GitHub at line 81 of file PndRecoKalmanTask.h
Referenced by Init(), and SetMvdBranchName().
Int_t PndRecoKalmanTask::fNumIt protected
(0) GeaneTrackRep, 1 RKTrackRep
Definition at line 97 of file PndRecoKalmanTask.h.
View newest version in sPHENIX GitHub at line 97 of file PndRecoKalmanTask.h
Referenced by Init(), and EicRecoKalmanTask::SetNumIterations().
Int_t PndRecoKalmanTask::fPDGHyp protected
Number of iterations.
Definition at line 98 of file PndRecoKalmanTask.h.
View newest version in sPHENIX GitHub at line 98 of file PndRecoKalmanTask.h
Referenced by Exec(), and SetParticleHypo().
Bool_t PndRecoKalmanTask::fPerpPlane protected
Flag to propagate the parameters to the interaction point (kTRUE)
Definition at line 95 of file PndRecoKalmanTask.h.
View newest version in sPHENIX GitHub at line 95 of file PndRecoKalmanTask.h
Referenced by Init(), and SetPerpPlane().
Bool_t PndRecoKalmanTask::fPersistence protected
Particle DB.
Definition at line 88 of file PndRecoKalmanTask.h.
View newest version in sPHENIX GitHub at line 88 of file PndRecoKalmanTask.h
Referenced by Init(), and SetPersistence().
Bool_t PndRecoKalmanTask::fPropagateToIP protected
Flag to use Deterministic Annealing.
Definition at line 94 of file PndRecoKalmanTask.h.
View newest version in sPHENIX GitHub at line 94 of file PndRecoKalmanTask.h
Referenced by Init(), and SetPropagateToIP().
Bool_t PndRecoKalmanTask::fSmoothing protected
Flag to use Geane.
Definition at line 91 of file PndRecoKalmanTask.h.
View newest version in sPHENIX GitHub at line 91 of file PndRecoKalmanTask.h
TClonesArray* PndRecoKalmanTask::fTrackArray protected
Definition at line 67 of file PndRecoKalmanTask.h.
View newest version in sPHENIX GitHub at line 67 of file PndRecoKalmanTask.h
Referenced by Exec(), and Init().
TClonesArray* PndRecoKalmanTask::fTrackIDArray protected
Input TCA for PndTrack.
Definition at line 73 of file PndRecoKalmanTask.h.
View newest version in sPHENIX GitHub at line 73 of file PndRecoKalmanTask.h
Referenced by Exec(), and Init().
TString PndRecoKalmanTask::fTrackInBranchName protected
Output TCA for track.
Definition at line 77 of file PndRecoKalmanTask.h.
View newest version in sPHENIX GitHub at line 77 of file PndRecoKalmanTask.h
Referenced by Exec(), Init(), and SetTrackInBranchName().
TString PndRecoKalmanTask::fTrackInIDBranchName protected
Name of the input TCA.
Definition at line 78 of file PndRecoKalmanTask.h.
View newest version in sPHENIX GitHub at line 78 of file PndRecoKalmanTask.h
Referenced by Init(), and SetTrackInIDBranchName().
TString PndRecoKalmanTask::fTrackOutBranchName protected
Name of the input TCA.
Definition at line 79 of file PndRecoKalmanTask.h.
View newest version in sPHENIX GitHub at line 79 of file PndRecoKalmanTask.h
Referenced by EicRecoKalmanTask::EicRecoKalmanTask(), Init(), and SetTrackOutBranchName().
Short_t PndRecoKalmanTask::fTrackRep protected
Flag to use as initial plane the one perpendicular to the track (kFALSE)
Definition at line 96 of file PndRecoKalmanTask.h.
View newest version in sPHENIX GitHub at line 96 of file PndRecoKalmanTask.h
Referenced by Init(), and SetTrackRep().
Bool_t PndRecoKalmanTask::fUseGeane protected
Persistence.
Definition at line 90 of file PndRecoKalmanTask.h.
View newest version in sPHENIX GitHub at line 90 of file PndRecoKalmanTask.h
Referenced by Init(), and SetGeane().
bool PndRecoKalmanTask::mStoreTrackParameterization protected
Skip too busy events with more tracks.
Definition at line 103 of file PndRecoKalmanTask.h.
View newest version in sPHENIX GitHub at line 103 of file PndRecoKalmanTask.h
Referenced by Exec(), and StoreTrackParameterization().
TDatabasePDG* PndRecoKalmanTask::pdg protected
Definition at line 86 of file PndRecoKalmanTask.h.
View newest version in sPHENIX GitHub at line 86 of file PndRecoKalmanTask.h
Referenced by Exec(), and Init().
The documentation for this class was generated from the following files:
EicRoot/blob/master/GenfitTools/recotasks/PndRecoKalmanTask.h
EicRoot/blob/master/GenfitTools/recotasks/PndRecoKalmanTask.cxx