EIC Software: Acts::TrackDensity::TrackDensityStore Class Reference
Acts::TrackDensity::TrackDensityStore Class Reference
Public Member Functions
TrackDensityStore (double z_coordinate)
void addTrackToDensity (const TrackEntry &entry)
double density () const
double firstDerivative () const
double secondDerivative () const
Private Attributes
double m_z
double m_density {0}
double m_firstDerivative {0}
double m_secondDerivative {0}
Detailed Description
Definition at line 130 of file TrackDensity.hpp.
View newest version in sPHENIX GitHub at line 130 of file TrackDensity.hpp
Constructor & Destructor Documentation
Acts::TrackDensity::TrackDensityStore::TrackDensityStore (double z_coordinate) inline
Definition at line 133 of file TrackDensity.hpp.
View newest version in sPHENIX GitHub at line 133 of file TrackDensity.hpp
Member Function Documentation
void Acts::TrackDensity::TrackDensityStore::addTrackToDensity (const TrackEntry & entry)
Definition at line 130 of file TrackDensity.cpp.
View newest version in sPHENIX GitHub at line 130 of file TrackDensity.cpp
References Acts::TrackDensity::TrackEntry::c0, Acts::TrackDensity::TrackEntry::c1, Acts::TrackDensity::TrackEntry::c2, analysis::delta, Acts::TrackDensity::TrackEntry::lowerBound, and Acts::TrackDensity::TrackEntry::upperBound.
Referenced by Acts::TrackDensity::trackDensity().
double Acts::TrackDensity::TrackDensityStore::density () const inline
Definition at line 139 of file TrackDensity.hpp.
View newest version in sPHENIX GitHub at line 139 of file TrackDensity.hpp
References m_density.
Referenced by Acts::TrackDensity::trackDensity().
double Acts::TrackDensity::TrackDensityStore::firstDerivative () const inline
Definition at line 140 of file TrackDensity.hpp.
View newest version in sPHENIX GitHub at line 140 of file TrackDensity.hpp
References m_firstDerivative.
Referenced by Acts::TrackDensity::trackDensity().
double Acts::TrackDensity::TrackDensityStore::secondDerivative () const inline
Definition at line 141 of file TrackDensity.hpp.
View newest version in sPHENIX GitHub at line 141 of file TrackDensity.hpp
References m_secondDerivative.
Referenced by Acts::TrackDensity::trackDensity().
Member Data Documentation
double Acts::TrackDensity::TrackDensityStore::m_density {0} private
Definition at line 146 of file TrackDensity.hpp.
View newest version in sPHENIX GitHub at line 146 of file TrackDensity.hpp
Referenced by density().
double Acts::TrackDensity::TrackDensityStore::m_firstDerivative {0} private
Definition at line 147 of file TrackDensity.hpp.
View newest version in sPHENIX GitHub at line 147 of file TrackDensity.hpp
Referenced by firstDerivative().
double Acts::TrackDensity::TrackDensityStore::m_secondDerivative {0} private
Definition at line 148 of file TrackDensity.hpp.
View newest version in sPHENIX GitHub at line 148 of file TrackDensity.hpp
Referenced by secondDerivative().
double Acts::TrackDensity::TrackDensityStore::m_z private
Definition at line 145 of file TrackDensity.hpp.
View newest version in sPHENIX GitHub at line 145 of file TrackDensity.hpp
The documentation for this class was generated from the following files:
fun4all_acts/blob/master/Core/include/Acts/Vertexing/TrackDensity.hpp
fun4all_acts/blob/master/Core/src/Vertexing/TrackDensity.cpp