EIC Software: PHG4BackwardHcalDetector Class Reference
PHG4BackwardHcalDetector Class Reference
#include <fun4all_eicdetectors/blob/master/simulation/g4simulation/g4eiccalos/PHG4BackwardHcalDetector.h>
Classes
struct towerposition
Public Member Functions
PHG4BackwardHcalDetector (PHG4Subsystem *subsys, PHCompositeNode *Node, PHParameters *parameters, const std::string &dnam)
constructor
virtual ~PHG4BackwardHcalDetector ()
destructor
virtual void ConstructMe (G4LogicalVolume *world)
construct
Public Member Functions inherited from PHG4Detector
PHG4Detector ()=delete
constructor
PHG4Detector (PHG4Subsystem *subsys, PHCompositeNode *Node, const std::string &nam)
virtual ~PHG4Detector (void)
destructor
virtual void Construct (G4LogicalVolume *world) final
construct method
virtual void PostConstruction ()
Optional PostConstruction call after all geometry is constructed.
virtual void Verbosity (const int v)
virtual int Verbosity () const
virtual G4UserSteppingAction * GetSteppingAction ()
virtual std::string GetName () const
virtual void OverlapCheck (const bool chk)
virtual bool OverlapCheck () const
virtual void Print (const std::string &="ALL") const
virtual int DisplayVolume (G4VSolid *volume, G4LogicalVolume *logvol, G4RotationMatrix *rotm=nullptr)
virtual int DisplayVolume (G4LogicalVolume *checksolid, G4LogicalVolume *logvol, G4RotationMatrix *rotm=nullptr)
virtual PHCompositeNode * topNode ()
virtual PHG4Subsystem * GetMySubsystem ()
volume accessors
PHG4BackwardHcalDisplayAction * m_DisplayAction = nullptr
PHParameters * m_Params = nullptr
int m_ActiveFlag = 1
int m_AbsorberActiveFlag = 0
int m_Layer = 0
std::string m_TowerLogicNamePrefix
std::string m_SuperDetector
std::map< std::string, G4double > m_GlobalParameterMap
std::map< std::string,
towerposition > m_TowerPostionMap
std::set< G4LogicalVolume * > m_AbsorberLogicalVolSet
std::set< G4LogicalVolume * > m_ScintiLogicalVolSet
int IsInBackwardHcal (G4VPhysicalVolume *) const
void SuperDetector (const std::string &name)
const std::string SuperDetector () const
int get_Layer () const
G4LogicalVolume * ConstructTower ()
int PlaceTower (G4LogicalVolume *envelope, G4LogicalVolume *tower)
int ParseParametersFromTable ()
Additional Inherited Members
Static Public Member Functions inherited from PHG4Detector
static G4Material * GetDetectorMaterial (const std::string &name, const bool quit=true)
static G4Element * GetDetectorElement (const std::string &name, const bool quit=true)
Detailed Description
Definition at line 27 of file PHG4BackwardHcalDetector.h.
View newest version in sPHENIX GitHub at line 27 of file PHG4BackwardHcalDetector.h
Constructor & Destructor Documentation
PHG4BackwardHcalDetector::PHG4BackwardHcalDetector (PHG4Subsystem * subsys, PHCompositeNode * Node, PHParameters * parameters, const std::string & dnam)
constructor
Definition at line 39 of file PHG4BackwardHcalDetector.cc.
View newest version in sPHENIX GitHub at line 39 of file PHG4BackwardHcalDetector.cc
virtual PHG4BackwardHcalDetector::~PHG4BackwardHcalDetector () inline virtual
destructor
Definition at line 34 of file PHG4BackwardHcalDetector.h.
View newest version in sPHENIX GitHub at line 34 of file PHG4BackwardHcalDetector.h
Member Function Documentation
void PHG4BackwardHcalDetector::ConstructMe (G4LogicalVolume * world) virtual
construct
Implements PHG4Detector.
Definition at line 72 of file PHG4BackwardHcalDetector.cc.
View newest version in sPHENIX GitHub at line 72 of file PHG4BackwardHcalDetector.cc
References PHG4BackwardHcalDisplayAction::AddVolume(), Acts::UnitConstants::cm, ConstructTower(), PHParameters::get_double_param(), PHParameters::get_string_param(), PHFlag::get_StringFlag(), PHG4Detector::GetDetectorMaterial(), recoConsts::instance(), m_DisplayAction, m_Params, M_PI, m_TowerLogicNamePrefix, PHG4Detector::OverlapCheck(), ParseParametersFromTable(), PlaceTower(), PHG4Detector::Verbosity(), and G4WORLD::WorldMaterial.
G4LogicalVolume * PHG4BackwardHcalDetector::ConstructTower () private
Definition at line 130 of file PHG4BackwardHcalDetector.cc.
View newest version in sPHENIX GitHub at line 130 of file PHG4BackwardHcalDetector.cc
References PHG4BackwardHcalDisplayAction::AddVolume(), Acts::UnitConstants::cm, PHParameters::get_double_param(), PHParameters::get_string_param(), PHFlag::get_StringFlag(), PHG4Detector::GetDetectorMaterial(), recoConsts::instance(), m_AbsorberLogicalVolSet, m_DisplayAction, m_Params, m_ScintiLogicalVolSet, m_TowerLogicNamePrefix, PHG4Detector::OverlapCheck(), PHG4Detector::Verbosity(), and G4WORLD::WorldMaterial.
Referenced by ConstructMe().
int PHG4BackwardHcalDetector::get_Layer () const inline
Definition at line 45 of file PHG4BackwardHcalDetector.h.
View newest version in sPHENIX GitHub at line 45 of file PHG4BackwardHcalDetector.h
References m_Layer.
Referenced by PHG4BackwardHcalSteppingAction::UserSteppingAction().
int PHG4BackwardHcalDetector::IsInBackwardHcal (G4VPhysicalVolume * volume) const
Definition at line 50 of file PHG4BackwardHcalDetector.cc.
View newest version in sPHENIX GitHub at line 50 of file PHG4BackwardHcalDetector.cc
References m_AbsorberActiveFlag, m_AbsorberLogicalVolSet, m_ActiveFlag, and m_ScintiLogicalVolSet.
Referenced by PHG4BackwardHcalSteppingAction::UserSteppingAction().
int PHG4BackwardHcalDetector::ParseParametersFromTable () private
Definition at line 292 of file PHG4BackwardHcalDetector.cc.
View newest version in sPHENIX GitHub at line 292 of file PHG4BackwardHcalDetector.cc
References Acts::UnitConstants::cm, PHParameters::get_string_param(), getline, PHG4BackwardHcalDetector::towerposition::idx_j, PHG4BackwardHcalDetector::towerposition::idx_k, m_GlobalParameterMap, m_Params, m_TowerLogicNamePrefix, m_TowerPostionMap, Acts::UnitConstants::rad, PHParameters::set_double_param(), G4CTD::size_z, PHG4Detector::Verbosity(), PHG4BackwardHcalDetector::towerposition::x, PHG4BackwardHcalDetector::towerposition::y, and PHG4BackwardHcalDetector::towerposition::z.
Referenced by ConstructMe().
int PHG4BackwardHcalDetector::PlaceTower (G4LogicalVolume * envelope, G4LogicalVolume * tower) private
Definition at line 269 of file PHG4BackwardHcalDetector.cc.
View newest version in sPHENIX GitHub at line 269 of file PHG4BackwardHcalDetector.cc
References m_TowerPostionMap, PHG4Detector::OverlapCheck(), and PHG4Detector::Verbosity().
Referenced by ConstructMe().
void PHG4BackwardHcalDetector::SuperDetector (const std::string & name) inline
Definition at line 42 of file PHG4BackwardHcalDetector.h.
View newest version in sPHENIX GitHub at line 42 of file PHG4BackwardHcalDetector.h
References m_SuperDetector, and name.
Referenced by PHG4BackwardHcalSubsystem::InitRunSubsystem(), and PHG4BackwardHcalSteppingAction::SetInterfacePointers().
const std::string PHG4BackwardHcalDetector::SuperDetector () const inline
Definition at line 43 of file PHG4BackwardHcalDetector.h.
View newest version in sPHENIX GitHub at line 43 of file PHG4BackwardHcalDetector.h
References m_SuperDetector.
Member Data Documentation
int PHG4BackwardHcalDetector::m_AbsorberActiveFlag = 0 private
Definition at line 65 of file PHG4BackwardHcalDetector.h.
View newest version in sPHENIX GitHub at line 65 of file PHG4BackwardHcalDetector.h
Referenced by IsInBackwardHcal().
std::set<G4LogicalVolume *> PHG4BackwardHcalDetector::m_AbsorberLogicalVolSet private
Definition at line 74 of file PHG4BackwardHcalDetector.h.
View newest version in sPHENIX GitHub at line 74 of file PHG4BackwardHcalDetector.h
Referenced by ConstructTower(), and IsInBackwardHcal().
int PHG4BackwardHcalDetector::m_ActiveFlag = 1 private
Definition at line 64 of file PHG4BackwardHcalDetector.h.
View newest version in sPHENIX GitHub at line 64 of file PHG4BackwardHcalDetector.h
Referenced by IsInBackwardHcal().
PHG4BackwardHcalDisplayAction* PHG4BackwardHcalDetector::m_DisplayAction = nullptr private
Definition at line 61 of file PHG4BackwardHcalDetector.h.
View newest version in sPHENIX GitHub at line 61 of file PHG4BackwardHcalDetector.h
Referenced by ConstructMe(), and ConstructTower().
std::map<std::string, G4double> PHG4BackwardHcalDetector::m_GlobalParameterMap private
Definition at line 71 of file PHG4BackwardHcalDetector.h.
View newest version in sPHENIX GitHub at line 71 of file PHG4BackwardHcalDetector.h
Referenced by ParseParametersFromTable().
int PHG4BackwardHcalDetector::m_Layer = 0 private
Definition at line 66 of file PHG4BackwardHcalDetector.h.
View newest version in sPHENIX GitHub at line 66 of file PHG4BackwardHcalDetector.h
Referenced by get_Layer().
PHParameters* PHG4BackwardHcalDetector::m_Params = nullptr private
Definition at line 62 of file PHG4BackwardHcalDetector.h.
View newest version in sPHENIX GitHub at line 62 of file PHG4BackwardHcalDetector.h
Referenced by ConstructMe(), ConstructTower(), and ParseParametersFromTable().
std::set<G4LogicalVolume *> PHG4BackwardHcalDetector::m_ScintiLogicalVolSet private
Definition at line 75 of file PHG4BackwardHcalDetector.h.
View newest version in sPHENIX GitHub at line 75 of file PHG4BackwardHcalDetector.h
Referenced by ConstructTower(), and IsInBackwardHcal().
std::string PHG4BackwardHcalDetector::m_SuperDetector private
Definition at line 69 of file PHG4BackwardHcalDetector.h.
View newest version in sPHENIX GitHub at line 69 of file PHG4BackwardHcalDetector.h
Referenced by SuperDetector().
std::string PHG4BackwardHcalDetector::m_TowerLogicNamePrefix private
Definition at line 68 of file PHG4BackwardHcalDetector.h.
View newest version in sPHENIX GitHub at line 68 of file PHG4BackwardHcalDetector.h
Referenced by ConstructMe(), ConstructTower(), and ParseParametersFromTable().
std::map<std::string, towerposition> PHG4BackwardHcalDetector::m_TowerPostionMap private
Definition at line 72 of file PHG4BackwardHcalDetector.h.
View newest version in sPHENIX GitHub at line 72 of file PHG4BackwardHcalDetector.h
Referenced by ParseParametersFromTable(), and PlaceTower().
The documentation for this class was generated from the following files:
fun4all_eicdetectors/blob/master/simulation/g4simulation/g4eiccalos/PHG4BackwardHcalDetector.h
fun4all_eicdetectors/blob/master/simulation/g4simulation/g4eiccalos/PHG4BackwardHcalDetector.cc