EIC Software: EicKfNodeTemplateCylindrical2D Class Reference
EicKfNodeTemplateCylindrical2D Class Reference
#include <EicRoot/blob/master/eic/tracking/EicTrackingDigiHitProducer.h>
Public Member Functions
EicKfNodeTemplateCylindrical2D (TGeoMatrix *transformation=0)
~EicKfNodeTemplateCylindrical2D ()
double GetSpatialSigma () const
double GetAngularSigma () const
double GetSmearingValue (double spSmearing, const EicTrackingDigiHit *hit, unsigned iq) const
TVector3 TemplateToThreeDee (const double tmplCoord[]) const
void ThreeDeeToTemplate (const TVector3 &crs, double tmplCoord[]) const
void SmearLocalCoord (TVector3 &local, EicDigiHitProducer::SmearingModel smearing_model)
void SetStereoSkewRadius (double radius)
void SetPixelCenterOffsets (double offsetR, double offsetA=0.0)
Public Member Functions inherited from EicKfNodeTemplateOrth2D
EicKfNodeTemplateOrth2D (TGeoMatrix *transformation=0, bool xy_mode=true)
~EicKfNodeTemplateOrth2D ()
unsigned GetMdim () const
double GetSigma (unsigned iq) const
double GetPitch (unsigned iq) const
double GetPixelCenterOffset (unsigned iq) const
void FillGranularityArray (bool useCartesian, double spGranularity, double aGranularity, double gra[]) const
void FillMinMaxArrays (bool useCartesian, const std::set< double > &xMin, const std::set< double > &xMax, const std::set< double > &yMin, const std::set< double > &yMax, const std::set< double > &rMin, const std::set< double > &rMax, double min[], double max[]) const
void PackSmearedHit (TClonesArray *arr, const TString &detName, const EicMoCaPoint *point, unsigned kfNodeID, TVector3 &global, TVector3 &local)
KfMatrix * GetMeasurementNoise (const EicTrackingDigiHit *hit) const
void CartesianToCylindrical (const TVector3 &crs, double tmplCoord[]) const
Public Member Functions inherited from EicKfNodeTemplate
EicKfNodeTemplate (TGeoMatrix *node2sv=0)
~EicKfNodeTemplate ()
virtual bool CylindricalThreeDeeOnly () const
virtual bool CartesianThreeDeeOnly () const
bool IsCompatible (const EicKfNodeTemplate *sample)
int IncrementLinearTrackFitMatrices (SensitiveVolume *sv, EicTrackingDigiHit *hit, double zRef, KfMatrix *A, KfMatrix *b)
Private Member Functions
ClassDef (EicKfNodeTemplateCylindrical2D, 2)
Private Attributes
double mStereoSkewRadius
Additional Inherited Members
Public Attributes inherited from EicKfNodeTemplateOrth2D
bool mXYmode
Protected Member Functions inherited from EicKfNodeTemplate
double GetSmearedValue (double value, unsigned iq, EicDigiHitProducer::SmearingModel smearing_model)
void StoreDigiHit (TClonesArray *arr, const TString &detName, const EicMoCaPoint *point, unsigned kfNodeID, TVector3 &global, TVector3 &local, EicDigiHitProducer::SmearingModel smearing_model)
Protected Attributes inherited from EicKfNodeTemplateOrth2D
Double_t mSigma [2]
Double_t mPixelCenterOffset [2]
Detailed Description
Definition at line 459 of file EicTrackingDigiHitProducer.h.
View newest version in sPHENIX GitHub at line 459 of file EicTrackingDigiHitProducer.h
Constructor & Destructor Documentation
EicKfNodeTemplateCylindrical2D::EicKfNodeTemplateCylindrical2D (TGeoMatrix * transformation = 0) inline
Definition at line 462 of file EicTrackingDigiHitProducer.h.
View newest version in sPHENIX GitHub at line 462 of file EicTrackingDigiHitProducer.h
EicKfNodeTemplateCylindrical2D::~EicKfNodeTemplateCylindrical2D () inline
Definition at line 464 of file EicTrackingDigiHitProducer.h.
View newest version in sPHENIX GitHub at line 464 of file EicTrackingDigiHitProducer.h
Member Function Documentation
EicKfNodeTemplateCylindrical2D::ClassDef (EicKfNodeTemplateCylindrical2D , 2) private
double EicKfNodeTemplateCylindrical2D::GetAngularSigma () const inline virtual
Reimplemented from EicKfNodeTemplate.
Definition at line 467 of file EicTrackingDigiHitProducer.h.
View newest version in sPHENIX GitHub at line 467 of file EicTrackingDigiHitProducer.h
References EicKfNodeTemplateOrth2D::mSigma.
double EicKfNodeTemplateCylindrical2D::GetSmearingValue (double spSmearing, const EicTrackingDigiHit * hit, unsigned iq) const inline virtual
Implements EicKfNodeTemplate.
Definition at line 469 of file EicTrackingDigiHitProducer.h.
View newest version in sPHENIX GitHub at line 469 of file EicTrackingDigiHitProducer.h
References EicTrackingDigiHit::_GetCoord().
double EicKfNodeTemplateCylindrical2D::GetSpatialSigma () const inline virtual
Reimplemented from EicKfNodeTemplate.
Definition at line 466 of file EicTrackingDigiHitProducer.h.
View newest version in sPHENIX GitHub at line 466 of file EicTrackingDigiHitProducer.h
References EicKfNodeTemplateOrth2D::mSigma.
void EicKfNodeTemplateCylindrical2D::SetPixelCenterOffsets (double offsetR, double offsetA = 0.0) inline
Definition at line 525 of file EicTrackingDigiHitProducer.h.
View newest version in sPHENIX GitHub at line 525 of file EicTrackingDigiHitProducer.h
References EicKfNodeTemplateOrth2D::mPixelCenterOffset.
void EicKfNodeTemplateCylindrical2D::SetStereoSkewRadius (double radius) inline
Definition at line 523 of file EicTrackingDigiHitProducer.h.
View newest version in sPHENIX GitHub at line 523 of file EicTrackingDigiHitProducer.h
References mStereoSkewRadius, and G4BECAL::radius.
void EicKfNodeTemplateCylindrical2D::SmearLocalCoord (TVector3 & local, EicDigiHitProducer::SmearingModel smearing_model) inline virtual
Implements EicKfNodeTemplate.
Definition at line 511 of file EicTrackingDigiHitProducer.h.
View newest version in sPHENIX GitHub at line 511 of file EicTrackingDigiHitProducer.h
TVector3 EicKfNodeTemplateCylindrical2D::TemplateToThreeDee (const double tmplCoord[]) const inline virtual
Reimplemented from EicKfNodeTemplate.
Definition at line 482 of file EicTrackingDigiHitProducer.h.
View newest version in sPHENIX GitHub at line 482 of file EicTrackingDigiHitProducer.h
References cos(), mStereoSkewRadius, and phi.
void EicKfNodeTemplateCylindrical2D::ThreeDeeToTemplate (const TVector3 & crs, double tmplCoord[]) const inline virtual
Reimplemented from EicKfNodeTemplate.
Definition at line 498 of file EicTrackingDigiHitProducer.h.
View newest version in sPHENIX GitHub at line 498 of file EicTrackingDigiHitProducer.h
References EicKfNodeTemplateOrth2D::CartesianToCylindrical(), and mStereoSkewRadius.
Member Data Documentation
double EicKfNodeTemplateCylindrical2D::mStereoSkewRadius private
Definition at line 528 of file EicTrackingDigiHitProducer.h.
View newest version in sPHENIX GitHub at line 528 of file EicTrackingDigiHitProducer.h
Referenced by SetStereoSkewRadius(), TemplateToThreeDee(), and ThreeDeeToTemplate().
The documentation for this class was generated from the following file:
EicRoot/blob/master/eic/tracking/EicTrackingDigiHitProducer.h