EIC Software: Acts::Intersection Struct Reference
Acts::Intersection Struct Reference
#include <fun4all_acts/blob/master/Core/include/Acts/Utilities/Intersection.hpp>
Public Types
enum Status : int
Nested Status enum.
Public Member Functions
Intersection (const Vector3D &sinter, double slength, Status sstatus)
Intersection ()=default
Default constructor.
operator bool () const
Bool() operator for validity checking.
bool operator< (const Intersection &si) const
bool operator> (const Intersection &si) const
Public Attributes
Vector3D position {0., 0., 0.}
Position of the intersection.
double pathLength {std::numeric_limits<double>::infinity()}
Signed path length to the intersection (if valid)
Status status {Status::unreachable}
The Status of the intersection.
Detailed Description
Intersection struct used for position
Definition at line 22 of file Intersection.hpp.
View newest version in sPHENIX GitHub at line 22 of file Intersection.hpp
Member Enumeration Documentation
enum Acts::Intersection::Status : int
Nested Status enum.
Definition at line 24 of file Intersection.hpp.
View newest version in sPHENIX GitHub at line 24 of file Intersection.hpp
Constructor & Destructor Documentation
Acts::Intersection::Intersection (const Vector3D & sinter, double slength, Status sstatus) inline
Constructor with arguments
Parameters
sinter is the position of the intersection
slength is the path length to the intersection
svalid is a boolean indicating if intersection is valid
Definition at line 43 of file Intersection.hpp.
View newest version in sPHENIX GitHub at line 43 of file Intersection.hpp
Acts::Intersection::Intersection () default
Default constructor.
Member Function Documentation
Acts::Intersection::operator bool () const inline explicit
Bool() operator for validity checking.
Definition at line 50 of file Intersection.hpp.
View newest version in sPHENIX GitHub at line 50 of file Intersection.hpp
References status.
bool Acts::Intersection::operator< (const Intersection & si) const inline
Smaller operator for sorting,
it respects the validity of the intersection
Parameters
si is the intersection for testing
Definition at line 55 of file Intersection.hpp.
View newest version in sPHENIX GitHub at line 55 of file Intersection.hpp
References pathLength, and status.
bool Acts::Intersection::operator> (const Intersection & si) const inline
Greater operator for sorting,
it respects the validity of the intersection
Parameters
si is the intersection for testing
Definition at line 70 of file Intersection.hpp.
View newest version in sPHENIX GitHub at line 70 of file Intersection.hpp
References pathLength, and status.
Member Data Documentation
double Acts::Intersection::pathLength {std::numeric_limits<double>::infinity()}
Signed path length to the intersection (if valid)
Definition at line 34 of file Intersection.hpp.
View newest version in sPHENIX GitHub at line 34 of file Intersection.hpp
Referenced by Acts::TrackingVolume::compatibleBoundaries(), Acts::TrackingVolume::compatibleLayers(), Acts::Layer::compatibleSurfaces(), Acts::SurfaceReached::operator()(), operator<(), operator>(), and Acts::Layer::surfaceOnApproach().
Vector3D Acts::Intersection::position {0., 0., 0.}
Position of the intersection.
Definition at line 32 of file Intersection.hpp.
View newest version in sPHENIX GitHub at line 32 of file Intersection.hpp
Referenced by Acts::Test::BOOST_AUTO_TEST_CASE(), Acts::PlanarModuleStepper::cellSteps(), and FW::RootMaterialTrackWriter::writeT().
Status Acts::Intersection::status {Status::unreachable}
The Status of the intersection.
Definition at line 36 of file Intersection.hpp.
View newest version in sPHENIX GitHub at line 36 of file Intersection.hpp
Referenced by operator bool(), operator<(), and operator>().
The documentation for this struct was generated from the following file:
fun4all_acts/blob/master/Core/include/Acts/Utilities/Intersection.hpp