EIC Software: Smear Namespace Reference
Smear Namespace Reference
Classes
class HadronicEventBuilder
class Acceptance
struct Bremsstrahlung
A specialized Device class for modelling radiative losses.
class Detector
class Device
class Distributor
class EventDisFactory
class EventFactory
class Event
class FormulaString
class NumSigmaPid
struct ParticleID
class ParticleMCS
class PerfectID
class PlanarTracker
class RadialTracker
class Smearer
class Tracker
class TofBarrelSmearer
Enumerations
enum KinType {
kE, kP, kTheta, kPhi,
kPz, kPt, kInvalidKinType
}
enum EGenre { kAll = 0, kElectromagnetic = 1, kHadronic = 2 }
enum ECharge { kNeutral, kCharged, kAllCharges }
Functions
int PGenre (const erhic::VirtualParticle &prt)
double FixTheta (double theta)
double FixPhi (double phi)
double GetVariable (const erhic::VirtualParticle &prt, KinType kin)
bool IsCoreType (KinType kin)
int ParseInputFunction (TString &s, KinType &kin1, KinType &kin2)
Enumeration Type Documentation
enum Smear::ECharge
Particle charged
Enumerator:
kNeutral
kCharged
kAllCharges
Definition at line 31 of file SmearConstants.h.
View newest version in sPHENIX GitHub at line 31 of file SmearConstants.h
enum Smear::EGenre
Classes of particles
Enumerator:
kAll
kElectromagnetic
kHadronic
Definition at line 26 of file SmearConstants.h.
View newest version in sPHENIX GitHub at line 26 of file SmearConstants.h
enum Smear::KinType
Enumerator listing particle wise kinematic variables. Naming is self explanitory. These will be used when specifying arguments and outputs for device parametrizations.
Enumerator:
kE
kP
kTheta
kPhi
kPz
kPt
kInvalidKinType
Definition at line 21 of file SmearConstants.h.
View newest version in sPHENIX GitHub at line 21 of file SmearConstants.h
Function Documentation
double Smear::FixPhi (double phi) inline
Fix an azimuthal angle so that it lies within [0,2*pi). TODO Nothing Smear-specific here - move to general functions file.
Definition at line 83 of file Smear.h.
View newest version in sPHENIX GitHub at line 83 of file Smear.h
Referenced by Smear::Acceptance::Zone::Contains(), and Smear::Device::Smear().
double Smear::FixTheta (double theta) inline
Fix a polar angle so that it lies within [0,pi]. TODO Nothing Smear-specific here - move to general functions file.
Definition at line 66 of file Smear.h.
View newest version in sPHENIX GitHub at line 66 of file Smear.h
References theta().
Referenced by Smear::Acceptance::Zone::Contains(), and Smear::Device::Smear().
double Smear::GetVariable (const erhic::VirtualParticle & prt, KinType kin) inline
Returns the kinematic variable associated with kin from the input particle.
Definition at line 90 of file Smear.h.
View newest version in sPHENIX GitHub at line 90 of file Smear.h
References erhic::VirtualParticle::GetE(), erhic::VirtualParticle::GetP(), erhic::VirtualParticle::GetPhi(), erhic::VirtualParticle::GetPt(), erhic::VirtualParticle::GetPz(), erhic::VirtualParticle::GetTheta(), kE, kP, kPhi, kPt, kPz, kTheta, and z.
Referenced by Smear::Acceptance::CustomCut::Contains(), Smear::Tracker::Smear(), and Smear::Device::Smear().
bool Smear::IsCoreType (KinType kin) inline
Definition at line 111 of file Smear.h.
View newest version in sPHENIX GitHub at line 111 of file Smear.h
References kE, kP, kPhi, and kTheta.
Referenced by Smear::Acceptance::CustomCut::CustomCut().
int Smear::ParseInputFunction (TString & s, KinType & kin1, KinType & kin2)
Definition at line 18 of file Smear.cxx.
View newest version in sPHENIX GitHub at line 18 of file Smear.cxx
References d, kE, kP, kPhi, kPt, kPz, and kTheta.
Referenced by Smear::Acceptance::CustomCut::CustomCut().
int Smear::PGenre (const erhic::VirtualParticle & prt) inline
Determine particle "genre".
This refers to whether the particle in the argument is "electromagnetic" or "hadronic" from the perspective of calorimetry.
Returns one of the following (see enum EGenre): kElectromagnetic: photon or electron/positron. kHadronic: stable hadron. kAll: neither of the above.
Definition at line 49 of file Smear.h.
View newest version in sPHENIX GitHub at line 49 of file Smear.h
References kdfinder::abs(), erhic::VirtualParticle::GetStatus(), erhic::VirtualParticle::Id(), kAll, kElectromagnetic, and kHadronic.
Referenced by Smear::Acceptance::Is().