EIC Software: EicRoot/blob/master/eic/cad/EicStlKey.h File Reference
EicStlKey.h File Reference
#include <cstring>
Classes
class EicStlKey
Naive multi-float-value key used for ordering objects in CAD-related classes;.
Functions
bool EicStlKeyCompare (const EicStlKey *lh, const EicStlKey *rh)
bool EicStlKeyEqual (const EicStlKey *lh, const EicStlKey *rh)
Function Documentation
bool EicStlKeyCompare (const EicStlKey * lh, const EicStlKey * rh)
Definition at line 100 of file EicCadFile.cxx.
View newest version in sPHENIX GitHub at line 100 of file EicCadFile.cxx
References EicStlKey::GetData(), and EicStlKey::GetDim().
Referenced by EicStlFacet::Calculate(), EicStlFacetEdge::EicStlFacetEdge(), EicStlMediaGroup::EicStlMediaGroup(), EicMediaHub::importMediaMapFile(), and EicCompositeShape::LocalFillBuffer3D().
bool EicStlKeyEqual (const EicStlKey * lh, const EicStlKey * rh)
Definition at line 106 of file EicCadFile.cxx.
View newest version in sPHENIX GitHub at line 106 of file EicCadFile.cxx
References EicStlKey::GetData(), and EicStlKey::GetDim().