EIC Software: GFBookkeeping Class Reference
GFBookkeeping Class Reference
#include <EicRoot/blob/master/genfit/GFBookkeeping.h>
Public Member Functions
void reset ()
void setNhits (int n)
void bookMatrices (std::string key)
void bookGFDetPlanes (std::string key)
void bookNumbers (std::string key, double val=0.)
void setMatrix (std::string key, unsigned int index, const TMatrixT< double > &mat)
void setDetPlane (std::string key, unsigned int index, const GFDetPlane &pl)
void setNumber (std::string key, unsigned int index, const double &num)
bool getMatrix (std::string key, unsigned int index, TMatrixT< double > &mat) const
bool getDetPlane (std::string key, unsigned int index, GFDetPlane &pl) const
bool getNumber (std::string key, unsigned int index, double &num) const
std::vector< std::string > getMatrixKeys () const
std::vector< std::string > getGFDetPlaneKeys () const
std::vector< std::string > getNumberKeys () const
void addFailedHit (unsigned int)
unsigned int hitFailed (unsigned int)
unsigned int getNumFailed ()
GFBookkeeping ()
GFBookkeeping (const GFBookkeeping &)
virtual ~GFBookkeeping ()
void clearAll ()
void clearFailedHits ()
void Print (const Option_t *="") const
Private Member Functions
GFBookkeeping & operator= (const GFBookkeeping &)
Private Attributes
std::map< std::string,
TMatrixT< double > * > fMatrices
std::map< std::string,
GFDetPlane * > fPlanes
std::map< std::string,
TMatrixT< double > * > fNumbers
std::vector< unsigned int > fFailedHits
int fNhits
Detailed Description
Definition at line 34 of file GFBookkeeping.h.
View newest version in sPHENIX GitHub at line 34 of file GFBookkeeping.h
Constructor & Destructor Documentation
GFBookkeeping::GFBookkeeping () inline
Definition at line 72 of file GFBookkeeping.h.
View newest version in sPHENIX GitHub at line 72 of file GFBookkeeping.h
References fNhits.
GFBookkeeping::GFBookkeeping (const GFBookkeeping & bk)
Definition at line 26 of file GFBookkeeping.cxx.
View newest version in sPHENIX GitHub at line 26 of file GFBookkeeping.cxx
References fFailedHits, fMatrices, fNhits, fNumbers, fPlanes, ip(), and it.
virtual GFBookkeeping::~GFBookkeeping () inline virtual
Definition at line 74 of file GFBookkeeping.h.
View newest version in sPHENIX GitHub at line 74 of file GFBookkeeping.h
References clearAll().
Member Function Documentation
void GFBookkeeping::addFailedHit (unsigned int id)
Definition at line 368 of file GFBookkeeping.cxx.
View newest version in sPHENIX GitHub at line 368 of file GFBookkeeping.cxx
References fFailedHits.
void GFBookkeeping::bookGFDetPlanes (std::string key)
Definition at line 214 of file GFBookkeeping.cxx.
View newest version in sPHENIX GitHub at line 214 of file GFBookkeeping.cxx
References fNhits, and fPlanes.
Referenced by GFDaf::copySmoothing(), GFKalman::processTrack(), and reset().
void GFBookkeeping::bookMatrices (std::string key)
Definition at line 199 of file GFBookkeeping.cxx.
View newest version in sPHENIX GitHub at line 199 of file GFBookkeeping.cxx
References fMatrices, and fNhits.
Referenced by GFDaf::copySmoothing(), GFKalman::processTrack(), and reset().
void GFBookkeeping::bookNumbers (std::string key, double val = 0.)
Definition at line 230 of file GFBookkeeping.cxx.
View newest version in sPHENIX GitHub at line 230 of file GFBookkeeping.cxx
References fNhits, and fNumbers.
Referenced by GFKalman::processTrack(), reset(), and GFDaf::saveWeights().
void GFBookkeeping::clearAll ()
Definition at line 410 of file GFBookkeeping.cxx.
View newest version in sPHENIX GitHub at line 410 of file GFBookkeeping.cxx
References fMatrices, fNumbers, and fPlanes.
Referenced by reset(), and ~GFBookkeeping().
void GFBookkeeping::clearFailedHits ()
Definition at line 386 of file GFBookkeeping.cxx.
View newest version in sPHENIX GitHub at line 386 of file GFBookkeeping.cxx
References fFailedHits.
Referenced by GFKalman::fittingPass(), and reset().
bool GFBookkeeping::getDetPlane (std::string key, unsigned int index, GFDetPlane & pl) const
Definition at line 325 of file GFBookkeeping.cxx.
View newest version in sPHENIX GitHub at line 325 of file GFBookkeeping.cxx
References fNhits, fPlanes, and it.
Referenced by GFDaf::copySmoothing(), GFTools::getBiasedSmoothedData(), GFTools::getSmoothedData(), GFTools::getSmoothingPlane(), and Print().
std::vector< std::string > GFBookkeeping::getGFDetPlaneKeys () const
Definition at line 436 of file GFBookkeeping.cxx.
View newest version in sPHENIX GitHub at line 436 of file GFBookkeeping.cxx
References fPlanes, and it.
Referenced by Print(), and reset().
bool GFBookkeeping::getMatrix (std::string key, unsigned int index, TMatrixT< double > & mat) const
Definition at line 303 of file GFBookkeeping.cxx.
View newest version in sPHENIX GitHub at line 303 of file GFBookkeeping.cxx
References fMatrices, fNhits, and it.
Referenced by GFDaf::copySmoothing(), GFTools::getBiasedSmoothedData(), GFTools::getSmoothedData(), and Print().
std::vector< std::string > GFBookkeeping::getMatrixKeys () const
Definition at line 428 of file GFBookkeeping.cxx.
View newest version in sPHENIX GitHub at line 428 of file GFBookkeeping.cxx
References fMatrices, and it.
Referenced by GFDaf::copySmoothing(), Print(), GFKalman::processTrack(), and reset().
bool GFBookkeeping::getNumber (std::string key, unsigned int index, double & num) const
Definition at line 346 of file GFBookkeeping.cxx.
View newest version in sPHENIX GitHub at line 346 of file GFBookkeeping.cxx
References fNhits, fNumbers, and it.
Referenced by GFTools::getTrackLength(), and Print().
std::vector< std::string > GFBookkeeping::getNumberKeys () const
Definition at line 444 of file GFBookkeeping.cxx.
View newest version in sPHENIX GitHub at line 444 of file GFBookkeeping.cxx
References fNumbers, and it.
Referenced by Print(), and reset().
unsigned int GFBookkeeping::getNumFailed ()
Definition at line 372 of file GFBookkeeping.cxx.
View newest version in sPHENIX GitHub at line 372 of file GFBookkeeping.cxx
References fFailedHits.
unsigned int GFBookkeeping::hitFailed (unsigned int id)
Definition at line 376 of file GFBookkeeping.cxx.
View newest version in sPHENIX GitHub at line 376 of file GFBookkeeping.cxx
References fFailedHits.
GFBookkeeping& GFBookkeeping::operator= (const GFBookkeeping &) inline private
Definition at line 83 of file GFBookkeeping.h.
View newest version in sPHENIX GitHub at line 83 of file GFBookkeeping.h
void GFBookkeeping::Print (const Option_t * option = "") const
Definition at line 454 of file GFBookkeeping.cxx.
View newest version in sPHENIX GitHub at line 454 of file GFBookkeeping.cxx
References fFailedHits, fNhits, getDetPlane(), getGFDetPlaneKeys(), getMatrix(), getMatrixKeys(), getNumber(), getNumberKeys(), Acts::UnitConstants::m, n, p, and GFDetPlane::Print().
void GFBookkeeping::reset ()
Definition at line 390 of file GFBookkeeping.cxx.
View newest version in sPHENIX GitHub at line 390 of file GFBookkeeping.cxx
References bookGFDetPlanes(), bookMatrices(), bookNumbers(), clearAll(), clearFailedHits(), getGFDetPlaneKeys(), getMatrixKeys(), and getNumberKeys().
Referenced by setNhits().
void GFBookkeeping::setDetPlane (std::string key, unsigned int index, const GFDetPlane & pl)
Definition at line 268 of file GFBookkeeping.cxx.
View newest version in sPHENIX GitHub at line 268 of file GFBookkeeping.cxx
References fNhits, and fPlanes.
Referenced by GFDaf::copySmoothing(), and GFKalman::processHit().
void GFBookkeeping::setMatrix (std::string key, unsigned int index, const TMatrixT< double > & mat)
Definition at line 250 of file GFBookkeeping.cxx.
View newest version in sPHENIX GitHub at line 250 of file GFBookkeeping.cxx
References fMatrices, and fNhits.
Referenced by GFDaf::copySmoothing(), and GFKalman::processHit().
void GFBookkeeping::setNhits (int n) inline
Definition at line 50 of file GFBookkeeping.h.
View newest version in sPHENIX GitHub at line 50 of file GFBookkeeping.h
References fNhits, n, and reset().
Referenced by GFDaf::processTrack(), and GFKalman::processTrack().
void GFBookkeeping::setNumber (std::string key, unsigned int index, const double & num)
Definition at line 285 of file GFBookkeeping.cxx.
View newest version in sPHENIX GitHub at line 285 of file GFBookkeeping.cxx
References fNhits, fNumbers, and num.
Referenced by GFKalman::processHit(), and GFDaf::saveWeights().
Member Data Documentation
std::vector< unsigned int > GFBookkeeping::fFailedHits private
Definition at line 45 of file GFBookkeeping.h.
View newest version in sPHENIX GitHub at line 45 of file GFBookkeeping.h
Referenced by addFailedHit(), clearFailedHits(), getNumFailed(), GFBookkeeping(), hitFailed(), and Print().
std::map<std::string, TMatrixT<double>* > GFBookkeeping::fMatrices private
Definition at line 39 of file GFBookkeeping.h.
View newest version in sPHENIX GitHub at line 39 of file GFBookkeeping.h
Referenced by bookMatrices(), clearAll(), getMatrix(), getMatrixKeys(), GFBookkeeping(), and setMatrix().
int GFBookkeeping::fNhits private
Definition at line 46 of file GFBookkeeping.h.
View newest version in sPHENIX GitHub at line 46 of file GFBookkeeping.h
Referenced by bookGFDetPlanes(), bookMatrices(), bookNumbers(), getDetPlane(), getMatrix(), getNumber(), GFBookkeeping(), Print(), setDetPlane(), setMatrix(), setNhits(), and setNumber().
std::map<std::string, TMatrixT<double>* > GFBookkeeping::fNumbers private
Definition at line 44 of file GFBookkeeping.h.
View newest version in sPHENIX GitHub at line 44 of file GFBookkeeping.h
Referenced by bookNumbers(), clearAll(), getNumber(), getNumberKeys(), GFBookkeeping(), and setNumber().
std::map<std::string, GFDetPlane* > GFBookkeeping::fPlanes private
Definition at line 40 of file GFBookkeeping.h.
View newest version in sPHENIX GitHub at line 40 of file GFBookkeeping.h
Referenced by bookGFDetPlanes(), clearAll(), getDetPlane(), getGFDetPlaneKeys(), GFBookkeeping(), and setDetPlane().
The documentation for this class was generated from the following files:
EicRoot/blob/master/genfit/GFBookkeeping.h
EicRoot/blob/master/genfit/GFBookkeeping.cxx