EIC Software: EicRootManager Class Reference
EicRootManager Class Reference
#include <EicRoot/blob/master/eic/event/EicRootManager.h>
Public Member Functions
EicRootManager ()
EicRootManager (const char *mocaInFile, const char *digiInFile, const char *recoInFile, const char *assyInFile=0)
EicRootManager (erhic::EventMC **generatorEventHack, TClonesArray *PndMCTracks, TClonesArray *PndPidChargedCand, EicRcEvent **EicRcEventHack)
~EicRootManager ()
void ResetVars ()
void SynchronizeBranch (TBranch *branch)
const TClonesArray * GetPndMcTracks () const
const TClonesArray * GetPndPidCandidates () const
TBranch * GetGenBranch () const
TBranch * GetPndMcBranch () const
TBranch * GetPndPidBranch () const
TBranch * GetEicRcEventBranch () const
const TTree * GetEicRcTree () const
const erhic::EventMC * GetGenMcEvent () const
const erhic::ParticleMC * GetGenMcTrack (int genMcIndex) const
const EicRcEvent * GetEicRcEvent () const
Long64_t GetEicRcTreeEntries () const
Int_t GetEicRcTreeEntry (unsigned ev) const
Static Public Member Functions
static EicRootManager * Instance ()
Private Member Functions
TBranch * SetupBranch (const EicRootInputFile *tfile, const char *treeName, const char *branchName, void *addr)
const erhic::EventMC * GetGeneratorEventPtr () const
ClassDef (EicRootManager, 25)
Private Attributes
std::map< const TBranch *, int > mBranchStatus
TClonesArray * mPndMCTracks
TClonesArray * mPndPidChargedCand
TBranch * mPndPidBranch
TBranch * mPndMcBranch
erhic::EventMC * mGeneratorEvent
erhic::EventMC ** mGeneratorEventHack
EicRcEvent * mEicRcEvent
EicRcEvent ** mEicRcEventHack
reconstructed event as a whole
TTree * mEicRcTree
TBranch * mGeneratorBranch
TBranch * mEicRcEventBranch
EicRootInputFile * mMoCaFile
EicRootInputFile * mDigiFile
EicRootInputFile * mRecoFile
EicRootInputFile * mAssyFile
Static Private Attributes
static EicRootManager * mInstance = 0
Detailed Description
Definition at line 72 of file EicRootManager.h.
View newest version in sPHENIX GitHub at line 72 of file EicRootManager.h
Constructor & Destructor Documentation
EicRootManager::EicRootManager () inline
Definition at line 74 of file EicRootManager.h.
View newest version in sPHENIX GitHub at line 74 of file EicRootManager.h
References ResetVars().
EicRootManager::EicRootManager (const char * mocaInFile, const char * digiInFile, const char * recoInFile, const char * assyInFile = 0)
Definition at line 15 of file EicRootManager.cxx.
View newest version in sPHENIX GitHub at line 15 of file EicRootManager.cxx
References _CBM_TREE_, _EIC_GENERATOR_EVENT_BRANCH_, _EIC_GENERATOR_TREE_, _EIC_RC_BRANCH_, _EIC_RC_TREE_, _PND_MC_BRANCH_, _PND_RC_TRACK_BRANCH_, EicRootInputFile::GetTree(), mAssyFile, mDigiFile, mEicRcEvent, mEicRcEventBranch, mEicRcTree, mGeneratorBranch, mGeneratorEvent, mInstance, mMoCaFile, mPndMcBranch, mPndMCTracks, mPndPidBranch, mPndPidChargedCand, mRecoFile, printf(), ResetVars(), and SetupBranch().
EicRootManager::EicRootManager (erhic::EventMC ** generatorEventHack, TClonesArray * PndMCTracks, TClonesArray * PndPidChargedCand, EicRcEvent ** EicRcEventHack)
Definition at line 59 of file EicRootManager.cxx.
View newest version in sPHENIX GitHub at line 59 of file EicRootManager.cxx
References mEicRcEventHack, mGeneratorEventHack, mInstance, mPndMCTracks, mPndPidChargedCand, printf(), and ResetVars().
EicRootManager::~EicRootManager () inline
Definition at line 80 of file EicRootManager.h.
View newest version in sPHENIX GitHub at line 80 of file EicRootManager.h
References mAssyFile, mDigiFile, mInstance, mMoCaFile, mPndMCTracks, mPndPidChargedCand, mRecoFile, and ResetVars().
Member Function Documentation
EicRootManager::ClassDef (EicRootManager , 25) private
const EicRcEvent* EicRootManager::GetEicRcEvent () const inline
Definition at line 131 of file EicRootManager.h.
View newest version in sPHENIX GitHub at line 131 of file EicRootManager.h
References mEicRcEvent, and mEicRcEventHack.
Referenced by analysis().
TBranch* EicRootManager::GetEicRcEventBranch () const inline
Definition at line 123 of file EicRootManager.h.
View newest version in sPHENIX GitHub at line 123 of file EicRootManager.h
References mEicRcEventBranch.
Referenced by analysis().
const TTree* EicRootManager::GetEicRcTree () const inline
Definition at line 125 of file EicRootManager.h.
View newest version in sPHENIX GitHub at line 125 of file EicRootManager.h
References mEicRcTree.
Long64_t EicRootManager::GetEicRcTreeEntries () const inline
Definition at line 137 of file EicRootManager.h.
View newest version in sPHENIX GitHub at line 137 of file EicRootManager.h
References mEicRcTree.
Referenced by analysis().
Int_t EicRootManager::GetEicRcTreeEntry (unsigned ev) const inline
Definition at line 138 of file EicRootManager.h.
View newest version in sPHENIX GitHub at line 138 of file EicRootManager.h
References mEicRcTree.
Referenced by analysis().
TBranch* EicRootManager::GetGenBranch () const inline
Definition at line 120 of file EicRootManager.h.
View newest version in sPHENIX GitHub at line 120 of file EicRootManager.h
References mGeneratorBranch.
Referenced by GetGenMcEvent(), and GetGenMcTrack().
const erhic::EventMC* EicRootManager::GetGeneratorEventPtr () const inline private
Definition at line 169 of file EicRootManager.h.
View newest version in sPHENIX GitHub at line 169 of file EicRootManager.h
References mGeneratorEvent, and mGeneratorEventHack.
Referenced by GetGenMcEvent(), and GetGenMcTrack().
const erhic::EventMC * EicRootManager::GetGenMcEvent () const
Definition at line 126 of file EicRootManager.cxx.
View newest version in sPHENIX GitHub at line 126 of file EicRootManager.cxx
References GetGenBranch(), GetGeneratorEventPtr(), Instance(), and SynchronizeBranch().
Referenced by EicRcEvent::GetGenMcEvent().
const erhic::ParticleMC * EicRootManager::GetGenMcTrack (int genMcIndex) const
Definition at line 138 of file EicRootManager.cxx.
View newest version in sPHENIX GitHub at line 138 of file EicRootManager.cxx
References GetGenBranch(), GetGeneratorEventPtr(), Instance(), and SynchronizeBranch().
Referenced by EicRcParticle::GetGeneratorTrack(), and EicRcEvent::GetGenMcTrack().
TBranch* EicRootManager::GetPndMcBranch () const inline
Definition at line 121 of file EicRootManager.h.
View newest version in sPHENIX GitHub at line 121 of file EicRootManager.h
References mPndMcBranch.
Referenced by EicRcParticle::GetPndMcTrack().
const TClonesArray* EicRootManager::GetPndMcTracks () const inline
Definition at line 117 of file EicRootManager.h.
View newest version in sPHENIX GitHub at line 117 of file EicRootManager.h
References mPndMCTracks.
Referenced by EicRcParticle::GetPndMcTrack().
TBranch* EicRootManager::GetPndPidBranch () const inline
Definition at line 122 of file EicRootManager.h.
View newest version in sPHENIX GitHub at line 122 of file EicRootManager.h
References mPndPidBranch.
Referenced by EicRcParticle::GetPndPidCandidate().
const TClonesArray* EicRootManager::GetPndPidCandidates () const inline
Definition at line 118 of file EicRootManager.h.
View newest version in sPHENIX GitHub at line 118 of file EicRootManager.h
References mPndPidChargedCand.
Referenced by EicRcParticle::GetPndPidCandidate().
static EicRootManager* EicRootManager::Instance () inline static
Definition at line 113 of file EicRootManager.h.
View newest version in sPHENIX GitHub at line 113 of file EicRootManager.h
References mInstance.
Referenced by EicRcParticle::GetGeneratorTrack(), EicRcEvent::GetGenMcEvent(), GetGenMcEvent(), EicRcEvent::GetGenMcTrack(), GetGenMcTrack(), EicRcParticle::GetPndMcTrack(), and EicRcParticle::GetPndPidCandidate().
void EicRootManager::ResetVars () inline
Definition at line 100 of file EicRootManager.h.
View newest version in sPHENIX GitHub at line 100 of file EicRootManager.h
References mAssyFile, mDigiFile, mEicRcEvent, mEicRcEventBranch, mEicRcEventHack, mEicRcTree, mGeneratorBranch, mGeneratorEvent, mGeneratorEventHack, mMoCaFile, mPndMcBranch, mPndMCTracks, mPndPidBranch, mPndPidChargedCand, and mRecoFile.
Referenced by EicRootManager(), and ~EicRootManager().
TBranch * EicRootManager::SetupBranch (const EicRootInputFile * tfile, const char * treeName, const char * branchName, void * addr) private
Definition at line 103 of file EicRootManager.cxx.
View newest version in sPHENIX GitHub at line 103 of file EicRootManager.cxx
References EicRootInputFile::GetTree(), mBranchStatus, mEicRcTree, and EicRootInputFile::SetupBranch().
Referenced by EicRootManager().
void EicRootManager::SynchronizeBranch (TBranch * branch)
Definition at line 84 of file EicRootManager.cxx.
View newest version in sPHENIX GitHub at line 84 of file EicRootManager.cxx
References mBranchStatus, and mEicRcTree.
Referenced by GetGenMcEvent(), GetGenMcTrack(), EicRcParticle::GetPndMcTrack(), and EicRcParticle::GetPndPidCandidate().
Member Data Documentation
EicRootInputFile* EicRootManager::mAssyFile private
Definition at line 163 of file EicRootManager.h.
View newest version in sPHENIX GitHub at line 163 of file EicRootManager.h
Referenced by EicRootManager(), ResetVars(), and ~EicRootManager().
std::map<const TBranch*, int> EicRootManager::mBranchStatus private
Definition at line 145 of file EicRootManager.h.
View newest version in sPHENIX GitHub at line 145 of file EicRootManager.h
Referenced by SetupBranch(), and SynchronizeBranch().
EicRootInputFile* EicRootManager::mDigiFile private
Definition at line 161 of file EicRootManager.h.
View newest version in sPHENIX GitHub at line 161 of file EicRootManager.h
Referenced by EicRootManager(), ResetVars(), and ~EicRootManager().
EicRcEvent* EicRootManager::mEicRcEvent private
Definition at line 153 of file EicRootManager.h.
View newest version in sPHENIX GitHub at line 153 of file EicRootManager.h
Referenced by EicRootManager(), GetEicRcEvent(), and ResetVars().
TBranch * EicRootManager::mEicRcEventBranch private
Definition at line 156 of file EicRootManager.h.
View newest version in sPHENIX GitHub at line 156 of file EicRootManager.h
Referenced by EicRootManager(), GetEicRcEventBranch(), and ResetVars().
EicRcEvent** EicRootManager::mEicRcEventHack private
reconstructed event as a whole
Definition at line 154 of file EicRootManager.h.
View newest version in sPHENIX GitHub at line 154 of file EicRootManager.h
Referenced by EicRootManager(), GetEicRcEvent(), and ResetVars().
TTree* EicRootManager::mEicRcTree private
Definition at line 155 of file EicRootManager.h.
View newest version in sPHENIX GitHub at line 155 of file EicRootManager.h
Referenced by EicRootManager(), GetEicRcTree(), GetEicRcTreeEntries(), GetEicRcTreeEntry(), ResetVars(), SetupBranch(), and SynchronizeBranch().
TBranch* EicRootManager::mGeneratorBranch private
Definition at line 156 of file EicRootManager.h.
View newest version in sPHENIX GitHub at line 156 of file EicRootManager.h
Referenced by EicRootManager(), GetGenBranch(), and ResetVars().
erhic::EventMC* EicRootManager::mGeneratorEvent private
Definition at line 150 of file EicRootManager.h.
View newest version in sPHENIX GitHub at line 150 of file EicRootManager.h
Referenced by EicRootManager(), GetGeneratorEventPtr(), and ResetVars().
erhic::EventMC** EicRootManager::mGeneratorEventHack private
Definition at line 151 of file EicRootManager.h.
View newest version in sPHENIX GitHub at line 151 of file EicRootManager.h
Referenced by EicRootManager(), GetGeneratorEventPtr(), and ResetVars().
EicRootManager * EicRootManager::mInstance = 0 static private
Definition at line 141 of file EicRootManager.h.
View newest version in sPHENIX GitHub at line 141 of file EicRootManager.h
Referenced by EicRootManager(), Instance(), and ~EicRootManager().
EicRootInputFile* EicRootManager::mMoCaFile private
Definition at line 160 of file EicRootManager.h.
View newest version in sPHENIX GitHub at line 160 of file EicRootManager.h
Referenced by EicRootManager(), ResetVars(), and ~EicRootManager().
TBranch * EicRootManager::mPndMcBranch private
Definition at line 149 of file EicRootManager.h.
View newest version in sPHENIX GitHub at line 149 of file EicRootManager.h
Referenced by EicRootManager(), GetPndMcBranch(), and ResetVars().
TClonesArray* EicRootManager::mPndMCTracks private
Definition at line 147 of file EicRootManager.h.
View newest version in sPHENIX GitHub at line 147 of file EicRootManager.h
Referenced by EicRootManager(), GetPndMcTracks(), ResetVars(), and ~EicRootManager().
TBranch* EicRootManager::mPndPidBranch private
Definition at line 149 of file EicRootManager.h.
View newest version in sPHENIX GitHub at line 149 of file EicRootManager.h
Referenced by EicRootManager(), GetPndPidBranch(), and ResetVars().
TClonesArray * EicRootManager::mPndPidChargedCand private
Definition at line 147 of file EicRootManager.h.
View newest version in sPHENIX GitHub at line 147 of file EicRootManager.h
Referenced by EicRootManager(), GetPndPidCandidates(), ResetVars(), and ~EicRootManager().
EicRootInputFile* EicRootManager::mRecoFile private
Definition at line 162 of file EicRootManager.h.
View newest version in sPHENIX GitHub at line 162 of file EicRootManager.h
Referenced by EicRootManager(), ResetVars(), and ~EicRootManager().
The documentation for this class was generated from the following files:
EicRoot/blob/master/eic/event/EicRootManager.h
EicRoot/blob/master/eic/event/EicRootManager.cxx