EIC Software: TrKalmanNode Class Reference
TrKalmanNode Class Reference
#include <EicRoot/blob/master/eic/htc/TrKalmanNode.h>
Public Member Functions
TrKalmanNode ()
void SetMomentum (double value)
double GetInversedMomentum () const
void UpdateInversedMomentum (double value)
int SetMeasurementNoise (KfMatrix *W)
void InflateMeasurementNoise (double scale)
int GetMagneticField (double xy[2], TVector3 &B)
void SetHit (EicTrackingDigiHit *hit)
bool HasHit () const
double GetZ () const
void SetLocation (TrKalmanNodeLocation *location)
TrKalmanNodeLocation * GetLocation () const
void SetActiveFlag (bool flag)
bool IsActive () const
void SetSensitiveVolume (SensitiveVolume *sv)
SensitiveVolume * GetSensitiveVolume () const
TrKalmanNode * GetPrev (KalmanFilter::Direction fb)
TrKalmanNode * GetNext (KalmanFilter::Direction fb)
int PerformRungeKuttaStep (KalmanFilter::Direction fb, double pout[], double rkd[5][5])
Public Member Functions inherited from KalmanNode
KalmanNode ()
void SetFiredFlag ()
void ResetFiredFlag ()
bool IsFired () const
void SetZ (double z)
unsigned GetMdim () const
double GetV (unsigned ip, unsigned iq) const
double GetX0 (unsigned ip) const
double GetXf (unsigned ip) const
double GetXs (unsigned ip) const
double GetXm (unsigned ip) const
double GetRs (unsigned ip) const
double GetRm (unsigned ip) const
double Getm (unsigned ip) const
double GetSmootherChiSquare () const
double GetSmootherChiSquareCCDF () const
double GetCP (unsigned ip, unsigned iq) const
double GetCF (unsigned ip, unsigned iq) const
double GetCS (unsigned ip, unsigned iq) const
double GetRS (unsigned ip, unsigned iq) const
double GetRM (unsigned ip, unsigned iq) const
KfVector * GetX0 () const
KfVector * GetXf () const
KfVector * GetXp () const
KfVector * GetXs () const
KfMatrix * GetCP () const
KfMatrix * GetCS () const
const char * GetName () const
KalmanNode * GetNext (unsigned fb) const
KalmanNode * GetPrev (unsigned fb) const
void SetPrev (KalmanNode *node)
void SetNext (KalmanNode *node)
void CopyOverGroupInfo (KalmanNode *sample)
Public Attributes
double mInversedMomentum
EicTrackingDigiHit * mHit
TrKalmanNodeLocation * mLocation
SensitiveVolume * mSensitiveVolume
bool mActive
Friends
class TrKalmanFilter
Additional Inherited Members
Protected Attributes inherited from KalmanNode
double mZ
int mDim
KfMatrix * FF [2]
KfVector * m
KfMatrix * V
KfMatrix * H
KfVector * x0
KfMatrix * Q
KfMatrix * FM
KfMatrix * FR
KfMatrix * MMTX
KfVector * MVEC
KfVector * xp
KfVector * xf
KfVector * xm
KfVector * rm
KfMatrix * CP
KfMatrix * CF
KfMatrix * K
KfVector * xs
KfVector * qq
KfVector * ep
KfVector * rf
KfMatrix * RPI
KfMatrix * RF
KfMatrix * CS
KfVector * rs
KfMatrix * RS
KfMatrix * CM
KfMatrix * RM
KfMatrix * LB
KfMatrix * L
KfMatrix * QQ
Detailed Description
Definition at line 22 of file TrKalmanNode.h.
View newest version in sPHENIX GitHub at line 22 of file TrKalmanNode.h
Constructor & Destructor Documentation
TrKalmanNode::TrKalmanNode () inline
Definition at line 28 of file TrKalmanNode.h.
View newest version in sPHENIX GitHub at line 28 of file TrKalmanNode.h
Member Function Documentation
double TrKalmanNode::GetInversedMomentum () const inline
Definition at line 32 of file TrKalmanNode.h.
View newest version in sPHENIX GitHub at line 32 of file TrKalmanNode.h
References mInversedMomentum.
Referenced by EicHtcTask::Exec(), FwdHoughTree::FinalFit(), and EicHtcTask::GetFairTrackParP().
TrKalmanNodeLocation* TrKalmanNode::GetLocation () const inline
Definition at line 48 of file TrKalmanNode.h.
View newest version in sPHENIX GitHub at line 48 of file TrKalmanNode.h
References mLocation.
Referenced by KalmanNodeWrapper::AllocateNewKfNode().
int TrKalmanNode::GetMagneticField (double xy[2], TVector3 & B)
Definition at line 70 of file TrKalmanNode.cxx.
View newest version in sPHENIX GitHub at line 70 of file TrKalmanNode.cxx
References KalmanFilter::Forward, Mgrid::getCartesianFieldValue(), GetZ(), RungeKutta::m1, MgridSlice::mGrid, mLocation, TrKalmanNodeLocation::mRungeKutta, and VZERO.
TrKalmanNode* TrKalmanNode::GetNext (KalmanFilter::Direction fb) inline
Definition at line 72 of file TrKalmanNode.h.
View newest version in sPHENIX GitHub at line 72 of file TrKalmanNode.h
References KalmanNode::GetNext().
Referenced by TrKalmanFilter::AccountIonizationLosses(), TrKalmanFilter::CalculateMagnetOffTransportMatrices(), TrKalmanFilter::CalculateProcessNoise(), PerformRungeKuttaStep(), and TrKalmanFilter::Transport().
TrKalmanNode* TrKalmanNode::GetPrev (KalmanFilter::Direction fb) inline
Definition at line 69 of file TrKalmanNode.h.
View newest version in sPHENIX GitHub at line 69 of file TrKalmanNode.h
References KalmanNode::GetPrev().
Referenced by TrKalmanFilter::Transport().
SensitiveVolume* TrKalmanNode::GetSensitiveVolume () const inline
Definition at line 54 of file TrKalmanNode.h.
View newest version in sPHENIX GitHub at line 54 of file TrKalmanNode.h
Referenced by FwdHoughTree::AddNodeGroup(), FwdTrackFinder::Init(), and TrKalmanFilter::SetUpLocations().
double TrKalmanNode::GetZ () const inline virtual
Reimplemented from KalmanNode.
Definition at line 45 of file TrKalmanNode.h.
View newest version in sPHENIX GitHub at line 45 of file TrKalmanNode.h
References KalmanNode::mZ.
Referenced by TrKalmanFilter::AccountIonizationLosses(), KalmanNodeWrapper::AllocateNewKfNode(), TrKalmanFilter::CalculateHMatrix(), TrKalmanFilter::CalculateMagnetOffTransportMatrices(), TrKalmanFilter::CalculateProcessNoise(), FwdHoughTree::FinalFit(), EicHtcTask::GetFairTrackParP(), GetMagneticField(), FwdHoughTree::MappingCall(), PerformRungeKuttaStep(), and TrKalmanFilter::SetUpLocations().
bool TrKalmanNode::HasHit () const inline
Definition at line 43 of file TrKalmanNode.h.
View newest version in sPHENIX GitHub at line 43 of file TrKalmanNode.h
References mHit.
Referenced by FwdHoughTree::FinalFit().
void TrKalmanNode::InflateMeasurementNoise (double scale)
Definition at line 86 of file TrKalmanNode.cxx.
View newest version in sPHENIX GitHub at line 86 of file TrKalmanNode.cxx
References KfMatrix::KFM(), KalmanNode::mDim, and KalmanNode::V.
Referenced by FwdHoughTree::SetupKalmanFilter().
bool TrKalmanNode::IsActive () const inline virtual
Reimplemented from KalmanNode.
Definition at line 51 of file TrKalmanNode.h.
View newest version in sPHENIX GitHub at line 51 of file TrKalmanNode.h
References mActive.
Referenced by TrKalmanNodeLocation::GetFiredNodeCount().
int TrKalmanNode::PerformRungeKuttaStep (KalmanFilter::Direction fb, double pout[], double rkd[5][5])
Definition at line 22 of file TrKalmanNode.cxx.
View newest version in sPHENIX GitHub at line 22 of file TrKalmanNode.cxx
References _drv_steps, _PSTEP_, KfMatrix::ARR(), GetNext(), KalmanNode::GetX0(), GetZ(), KalmanNode::GetZ(), RungeKuttaRequest::h, in, ip(), mInversedMomentum, mLocation, TrKalmanNodeLocation::mRungeKutta, RungeKuttaRequest::rk, RungeKuttaRequest::serveRequest(), KalmanNode::x0, and RungeKuttaRequest::z0.
void TrKalmanNode::SetActiveFlag (bool flag) inline
Definition at line 50 of file TrKalmanNode.h.
View newest version in sPHENIX GitHub at line 50 of file TrKalmanNode.h
References mActive.
Referenced by TrKalmanFilter::SelectActiveNodes().
void TrKalmanNode::SetHit (EicTrackingDigiHit * hit) inline
Definition at line 42 of file TrKalmanNode.h.
View newest version in sPHENIX GitHub at line 42 of file TrKalmanNode.h
References mHit.
Referenced by EicHtcTask::Exec(), and FwdHoughTree::SetupKalmanFilter().
void TrKalmanNode::SetLocation (TrKalmanNodeLocation * location) inline
Definition at line 47 of file TrKalmanNode.h.
View newest version in sPHENIX GitHub at line 47 of file TrKalmanNode.h
References mLocation.
int TrKalmanNode::SetMeasurementNoise (KfMatrix * W) inline
Definition at line 35 of file TrKalmanNode.h.
View newest version in sPHENIX GitHub at line 35 of file TrKalmanNode.h
References KfMatrix::CopyFrom(), and KalmanNode::V.
Referenced by EicHtcTask::Exec(), and FwdHoughTree::SetupKalmanFilter().
void TrKalmanNode::SetMomentum (double value) inline
Definition at line 31 of file TrKalmanNode.h.
View newest version in sPHENIX GitHub at line 31 of file TrKalmanNode.h
References mInversedMomentum, and value.
Referenced by EicHtcTask::ConstructLinearTrackApproximation(), FwdTrackFinder::ResetVtxNode(), and FwdHoughTree::SetupKalmanFilter().
void TrKalmanNode::SetSensitiveVolume (SensitiveVolume * sv) inline
Definition at line 53 of file TrKalmanNode.h.
View newest version in sPHENIX GitHub at line 53 of file TrKalmanNode.h
References mSensitiveVolume.
Referenced by KalmanNodeWrapper::AllocateNewKfNode().
void TrKalmanNode::UpdateInversedMomentum (double value) inline
Definition at line 33 of file TrKalmanNode.h.
View newest version in sPHENIX GitHub at line 33 of file TrKalmanNode.h
References mInversedMomentum, and value.
Referenced by FwdTrackFinder::UpdateVtxNode().
Friends And Related Function Documentation
friend class TrKalmanFilter friend
Definition at line 25 of file TrKalmanNode.h.
View newest version in sPHENIX GitHub at line 25 of file TrKalmanNode.h
Member Data Documentation
bool TrKalmanNode::mActive
Definition at line 67 of file TrKalmanNode.h.
View newest version in sPHENIX GitHub at line 67 of file TrKalmanNode.h
Referenced by IsActive(), and SetActiveFlag().
EicTrackingDigiHit* TrKalmanNode::mHit
Definition at line 60 of file TrKalmanNode.h.
View newest version in sPHENIX GitHub at line 60 of file TrKalmanNode.h
Referenced by TrKalmanFilter::CalculateHMatrix(), HasHit(), and SetHit().
double TrKalmanNode::mInversedMomentum
Definition at line 54 of file TrKalmanNode.h.
View newest version in sPHENIX GitHub at line 54 of file TrKalmanNode.h
Referenced by TrKalmanFilter::AccountIonizationLosses(), TrKalmanFilter::CalculateProcessNoise(), GetInversedMomentum(), PerformRungeKuttaStep(), TrKalmanFilter::ResetNode(), SetMomentum(), and UpdateInversedMomentum().
TrKalmanNodeLocation* TrKalmanNode::mLocation
Definition at line 62 of file TrKalmanNode.h.
View newest version in sPHENIX GitHub at line 62 of file TrKalmanNode.h
Referenced by TrKalmanFilter::AccountIonizationLosses(), TrKalmanFilter::CalculateProcessNoise(), GetLocation(), GetMagneticField(), PerformRungeKuttaStep(), SetLocation(), and TrKalmanFilter::SetUpLocations().
SensitiveVolume* TrKalmanNode::mSensitiveVolume
Definition at line 64 of file TrKalmanNode.h.
View newest version in sPHENIX GitHub at line 64 of file TrKalmanNode.h
Referenced by TrKalmanFilter::CalculateHMatrix(), and SetSensitiveVolume().
The documentation for this class was generated from the following files:
EicRoot/blob/master/eic/htc/TrKalmanNode.h
EicRoot/blob/master/eic/htc/TrKalmanNode.cxx