EIC Software: Acts::CylinderSurface Class Reference
Acts::CylinderSurface Class Reference
#include <fun4all_acts/blob/master/Core/include/Acts/Surfaces/CylinderSurface.hpp>
Public Member Functions
~CylinderSurface () override=default
Destructor - defaulted.
CylinderSurface ()=delete
Deleted default constructor.
CylinderSurface & operator= (const CylinderSurface &other)
const Vector3D binningPosition (const GeometryContext &gctx, BinningValue bValue) const final
const RotationMatrix3D referenceFrame (const GeometryContext &gctx, const Vector3D &position, const Vector3D &momentum) const final
SurfaceType type () const override
Return the surface type.
const Vector3D normal (const GeometryContext &gctx, const Vector2D &lposition) const final
const Vector3D normal (const GeometryContext &gctx, const Vector3D &position) const final
virtual const Vector3D rotSymmetryAxis (const GeometryContext &gctx) const
const CylinderBounds & bounds () const final
This method returns the CylinderBounds by reference.
void localToGlobal (const GeometryContext &gctx, const Vector2D &lposition, const Vector3D &momentum, Vector3D &position) const final
bool globalToLocal (const GeometryContext &gctx, const Vector3D &position, const Vector3D &momentum, Vector2D &lposition) const final
Intersection intersectionEstimate (const GeometryContext &gctx, const Vector3D &position, const Vector3D &direction, const BoundaryCheck &bcheck) const final
SurfaceIntersection intersect (const GeometryContext &gctx, const Vector3D &position, const Vector3D &direction, const BoundaryCheck &bcheck) const final
double pathCorrection (const GeometryContext &gctx, const Vector3D &position, const Vector3D &direction) const final
std::string name () const override
Return method for properly formatted output string.
Polyhedron polyhedronRepresentation (const GeometryContext &gctx, size_t lseg) const override
Public Member Functions inherited from Acts::Surface
virtual ~Surface ()
std::shared_ptr< Surface > getSharedPtr ()
std::shared_ptr< const Surface > getSharedPtr () const
Surface & operator= (const Surface &other)
virtual bool operator== (const Surface &other) const
virtual bool operator!= (const Surface &sf) const
virtual const Transform3D & transform (const GeometryContext &gctx) const
virtual const Vector3D center (const GeometryContext &gctx) const
virtual const Vector3D normal (const GeometryContext &gctx) const
const DetectorElementBase * associatedDetectorElement () const
const Layer * associatedLayer () const
void associateLayer (const Layer &lay)
const ISurfaceMaterial * surfaceMaterial () const
const std::shared_ptr< const
ISurfaceMaterial > & surfaceMaterialSharedPtr () const
void assignSurfaceMaterial (std::shared_ptr< const ISurfaceMaterial > material)
bool isOnSurface (const GeometryContext &gctx, const Vector3D &position, const Vector3D &momentum, const BoundaryCheck &bcheck=true) const
virtual bool insideBounds (const Vector2D &lposition, const BoundaryCheck &bcheck=true) const
virtual void initJacobianToGlobal (const GeometryContext &gctx, BoundToFreeMatrix &jacobian, const Vector3D &position, const Vector3D &direction, const BoundVector &pars) const
virtual const RotationMatrix3D initJacobianToLocal (const GeometryContext &gctx, FreeToBoundMatrix &jacobian, const Vector3D &position, const Vector3D &direction) const
virtual const BoundRowVector derivativeFactors (const GeometryContext &gctx, const Vector3D &position, const Vector3D &direction, const RotationMatrix3D &rft, const BoundToFreeMatrix &jacobian) const
virtual std::ostream & toStream (const GeometryContext &gctx, std::ostream &sl) const
Public Member Functions inherited from Acts::GeometryObject
GeometryObject ()=default
Defaulted construrctor.
GeometryObject (const GeometryObject &)=default
Defaulted copy constructor.
GeometryObject (const GeometryID &geoID)
GeometryObject & operator= (const GeometryObject &geoID)
const GeometryID & geoID () const
virtual double binningPositionValue (const GeometryContext &gctx, BinningValue bValue) const
void assignGeoID (const GeometryID &geoID)
Protected Member Functions
CylinderSurface (std::shared_ptr< const CylinderBounds > cbounds, const DetectorElementBase &detelement)
CylinderSurface (std::shared_ptr< const Transform3D > htrans, double radius, double halfz, double halfphi=M_PI, double avphi=0.)
CylinderSurface (std::shared_ptr< const Transform3D > htrans, const std::shared_ptr< const CylinderBounds > &cbounds)
CylinderSurface (const CylinderSurface &other)
CylinderSurface (const GeometryContext &gctx, const CylinderSurface &other, const Transform3D &transf)
Protected Member Functions inherited from Acts::Surface
Surface (std::shared_ptr< const Transform3D > tform=nullptr)
Surface (const Surface &other)
Surface (const DetectorElementBase &detelement)
Surface (const GeometryContext &gctx, const Surface &other, const Transform3D &shift)
Protected Attributes
std::shared_ptr< const
CylinderBounds > m_bounds
bounds (shared)
Protected Attributes inherited from Acts::Surface
std::shared_ptr< const
Transform3D > m_transform
const DetectorElementBase * m_associatedDetElement {nullptr}
Pointer to the a DetectorElementBase.
const Layer * m_associatedLayer {nullptr}
const TrackingVolume * m_associatedTrackingVolume {nullptr}
std::shared_ptr< const
ISurfaceMaterial > m_surfaceMaterial
Possibility to attach a material descrption.
Protected Attributes inherited from Acts::GeometryObject
GeometryID m_geoID
Private Member Functions
detail::RealQuadraticEquation intersectionSolver (const Transform3D &transform, const Vector3D &position, const Vector3D &direction) const
Private Attributes
friend Surface
Additional Inherited Members
Public Types inherited from Acts::Surface
enum SurfaceType {
Cone = 0, Cylinder = 1, Disc = 2, Perigee = 3,
Plane = 4, Straw = 5, Curvilinear = 6, Other = 7
}
Static Public Member Functions inherited from Acts::Surface
template<class T , typename... Args>
static std::shared_ptr< T > makeShared (Args &&...args)
Detailed Description
Class for a CylinderSurface in the TrackingGeometry. It inherits from Surface.
The cylinder surface has a special role in the TrackingGeometry, since it builds the surfaces of all TrackingVolumes at container level for a cylindrical tracking geometry.
Definition at line 34 of file CylinderSurface.hpp.
View newest version in sPHENIX GitHub at line 34 of file CylinderSurface.hpp
Constructor & Destructor Documentation
Acts::CylinderSurface::CylinderSurface (std::shared_ptr< const CylinderBounds > cbounds, const DetectorElementBase & detelement) protected
Constructor from DetectorElementBase: Element proxy
Parameters
cbounds are the provided cylinder bounds (shared)
detelement is the linked detector element to this surface
surfaces representing a detector element must have bounds
Definition at line 40 of file CylinderSurface.cpp.
View newest version in sPHENIX GitHub at line 40 of file CylinderSurface.cpp
Acts::CylinderSurface::CylinderSurface (std::shared_ptr< const Transform3D > htrans, double radius, double halfz, double halfphi = M_PI, double avphi = 0.) protected
Constructor from Transform3D and CylinderBounds
Parameters
htrans transform to position the surface, can be nullptr
radius The radius of the cylinder
halfz The half length in z
halfphi The half opening angle
avphi The phi value from which the opening angle spans (both sides)
Definition at line 33 of file CylinderSurface.cpp.
View newest version in sPHENIX GitHub at line 33 of file CylinderSurface.cpp
Acts::CylinderSurface::CylinderSurface (std::shared_ptr< const Transform3D > htrans, const std::shared_ptr< const CylinderBounds > & cbounds) protected
Constructor from Transform3D and CylinderBounds arguments
Parameters
htrans transform to position the surface, can be nullptr
Note
if htrans == nullptr, the cylinder is positioned around (0.,0.,0.)
Parameters
cbounds is a shared pointer to a cylindeer bounds object, it must exist (assert test)
Definition at line 48 of file CylinderSurface.cpp.
View newest version in sPHENIX GitHub at line 48 of file CylinderSurface.cpp
References throw_assert.
Acts::CylinderSurface::CylinderSurface (const CylinderSurface & other) protected
Copy constructor
Parameters
other is the source cylinder for the copy
Definition at line 23 of file CylinderSurface.cpp.
View newest version in sPHENIX GitHub at line 23 of file CylinderSurface.cpp
Acts::CylinderSurface::CylinderSurface (const GeometryContext & gctx, const CylinderSurface & other, const Transform3D & transf) protected
Copy constructor - with shift
Parameters
gctx The current geometry context object, e.g. alignment
other is the source cone surface
transf is the additional transfrom applied after copying
Definition at line 26 of file CylinderSurface.cpp.
View newest version in sPHENIX GitHub at line 26 of file CylinderSurface.cpp
Acts::CylinderSurface::~CylinderSurface () override default
Destructor - defaulted.
Acts::CylinderSurface::CylinderSurface () delete
Deleted default constructor.
Member Function Documentation
const Acts::Vector3D Acts::CylinderSurface::binningPosition (const GeometryContext & gctx, BinningValue bValue) const final virtual
The binning position method - is overloaded for r-type binning
Parameters
gctx The current geometry context object, e.g. alignment
bValue is the type of global binning to be done
Returns
is the global position to be used for binning
Implements Acts::GeometryObject.
Definition at line 65 of file CylinderSurface.cpp.
View newest version in sPHENIX GitHub at line 65 of file CylinderSurface.cpp
References Acts::binR, Acts::binRPhi, cos(), Acts::CylinderBounds::eAveragePhi, Acts::CylinderBounds::eR, phi, and Acts::IntegrationTest::R.
const Acts::CylinderBounds & Acts::CylinderSurface::bounds () const final virtual
This method returns the CylinderBounds by reference.
Implements Acts::Surface.
Definition at line 171 of file CylinderSurface.cpp.
View newest version in sPHENIX GitHub at line 171 of file CylinderSurface.cpp
Referenced by Acts::CylinderVolumeBuilder::analyzeContent(), and Acts::ProtoLayer::measure().
bool Acts::CylinderSurface::globalToLocal (const GeometryContext & gctx, const Vector3D & position, const Vector3D & momentum, Vector2D & lposition) const final virtual
Global to local transformation
Parameters
gctx The current geometry context object, e.g. alignment
position is the global position to be transformed
momentum is the global momentum (ignored in this operation)
lposition is the local position to be filled
Returns
is a boolean indicating if the transformation succeeded
Implements Acts::Surface.
Definition at line 115 of file CylinderSurface.cpp.
View newest version in sPHENIX GitHub at line 115 of file CylinderSurface.cpp
References kdfinder::abs(), Acts::CylinderBounds::eR, Acts::VectorHelpers::perp(), phi, and Acts::Test::transform.
SurfaceIntersection CylinderSurface::intersect (const GeometryContext & gctx, const Vector3D & position, const Vector3D & direction, const BoundaryCheck & bcheck) const inline final virtual
Straight line intersection schema from position/direction
Parameters
gctx The current geometry context object, e.g. alignment
position The position to start from
direction The direction at start
bcheck the Boundary Check
If possible returns both solutions for the cylinder
Returns
SurfaceIntersection object (contains intersection & surface)
Reimplemented from Acts::Surface.
Definition at line 71 of file CylinderSurface.ipp.
View newest version in sPHENIX GitHub at line 71 of file CylinderSurface.ipp
References Acts::ObjectIntersection< object_t, representation_t >::alternative, Acts::Test::boundaryCheck, Acts::eLOC_Z, Acts::ObjectIntersection< object_t, representation_t >::intersection, Acts::s_onSurfaceTolerance, analysis::status, Acts::BoundaryCheck::tolerance(), Acts::Test::transform, and Acts::BoundaryCheck::type().
Intersection CylinderSurface::intersectionEstimate (const GeometryContext & gctx, const Vector3D & position, const Vector3D & direction, const BoundaryCheck & bcheck) const inline final virtual
Straight line intersection schema - provides closest intersection and (signed) path length
Parameters
gctx The current geometry context object, e.g. alignment
position The global position as a starting point
direction The global direction at starting point (
Note
expected to be normalised)
Parameters
bcheck The boundary check presection
Returns
is the closest intersection (fwd or bwd)
Implements Acts::Surface.
Definition at line 41 of file CylinderSurface.ipp.
View newest version in sPHENIX GitHub at line 41 of file CylinderSurface.ipp
References Acts::s_onSurfaceTolerance, analysis::status, and Acts::Test::transform.
detail::RealQuadraticEquation CylinderSurface::intersectionSolver (const Transform3D & transform, const Vector3D & position, const Vector3D & direction) const inline private
Implementation of the intersection solver
mathematical motivation:
The cylinder is given by :
cylinder center: ccenter (C)
the direction of the cylinder axis: cdirection (DZ)
the radius r The line is given by :
a reference position : lposition (L0)
the line direction: ldirection (DL) the parametric form for the line is then : L(t) = L0 + t * DL
Any point P on infinite cylinder if : ((P - C) x DZ)^2 = r^2 * DZ^2 We know that DZ is a unit vector: DZ^2 == 1 When expanded with the line equation, this is : ((L0 - C) x DZ + t * (DL x DZ))^2 = r^2 * DZ^2 which is a quadratic equation in the form (X + t * Y)^2 = d, where : X = (L0 - C) x DZ Y = DL x DZ d = r^2 * (DZ)^2 Now, expand the equation : t^2 * (Y . Y) + t * (2 * (X . Y)) + (X . X) - d = 0 => second order equation in the form : a*t^2 + b*t + c = 0 where a = (Y . Y) b = 2 * (X . Y) c = (X . X) - d finally solve the second order equation : a*t^2 + b*t + c = 0 reinsertion into the line equation.
Returns
the quadratic equation
Definition at line 19 of file CylinderSurface.ipp.
View newest version in sPHENIX GitHub at line 19 of file CylinderSurface.ipp
References a, b, c, charm_jet_strange_helicity::pc, and Acts::IntegrationTest::R.
void Acts::CylinderSurface::localToGlobal (const GeometryContext & gctx, const Vector2D & lposition, const Vector3D & momentum, Vector3D & position) const final virtual
Local to global transformation
Parameters
gctx The current geometry context object, e.g. alignment
lposition is the local position to be transformed
momentum is the global momentum (ignored in this operation)
position is the global position which is filled
Implements Acts::Surface.
Definition at line 104 of file CylinderSurface.cpp.
View newest version in sPHENIX GitHub at line 104 of file CylinderSurface.cpp
References cos(), Acts::eLOC_RPHI, Acts::eLOC_Z, Acts::CylinderBounds::eR, phi, Acts::VectorHelpers::position(), r, and Acts::Test::transform.
std::string Acts::CylinderSurface::name () const override virtual
Return method for properly formatted output string.
Implements Acts::Surface.
Definition at line 141 of file CylinderSurface.cpp.
View newest version in sPHENIX GitHub at line 141 of file CylinderSurface.cpp
const Acts::Vector3D Acts::CylinderSurface::normal (const GeometryContext & gctx, const Vector2D & lposition) const final virtual
Return method for surface normal information
Note
for a Cylinder a local position is always required for the normal vector
Parameters
gctx The current geometry context object, e.g. alignment
lposition is the local postion for which the normal vector is requested
Returns
normal vector at the local position
Implements Acts::Surface.
Definition at line 145 of file CylinderSurface.cpp.
View newest version in sPHENIX GitHub at line 145 of file CylinderSurface.cpp
References cos(), Acts::eLOC_RPHI, Acts::CylinderBounds::eR, matrix(), phi, and Acts::Test::transform.
const Acts::Vector3D Acts::CylinderSurface::normal (const GeometryContext & gctx, const Vector3D & position) const final virtual
Return method for surface normal information
Note
for a Cylinder a local position is always required for the normal vector
Parameters
gctx The current geometry context object, e.g. alignment
position is the global postion for which the normal vector is requested
Returns
normal vector at the global position
Reimplemented from Acts::Surface.
Definition at line 152 of file CylinderSurface.cpp.
View newest version in sPHENIX GitHub at line 152 of file CylinderSurface.cpp
References Acts::VectorHelpers::position(), and Acts::Test::transform.
Acts::CylinderSurface & Acts::CylinderSurface::operator= (const CylinderSurface & other)
Assignment operator
Parameters
other is the source cylinder for the copy
Definition at line 55 of file CylinderSurface.cpp.
View newest version in sPHENIX GitHub at line 55 of file CylinderSurface.cpp
References m_bounds, and Acts::Surface::operator=().
double Acts::CylinderSurface::pathCorrection (const GeometryContext & gctx, const Vector3D & position, const Vector3D & direction) const final virtual
Path correction due to incident of the track
Parameters
gctx The current geometry context object, e.g. alignment
position is the global position as a starting point
direction is the global momentum at the starting point
Returns
is the correction factor due to incident
Implements Acts::Surface.
Definition at line 163 of file CylinderSurface.cpp.
View newest version in sPHENIX GitHub at line 163 of file CylinderSurface.cpp
Acts::Polyhedron Acts::CylinderSurface::polyhedronRepresentation (const GeometryContext & gctx, size_t lseg) const override virtual
Return a Polyhedron for a cylinder
Parameters
gctx The current geometry context object, e.g. alignment
lseg Number of segments along curved lines, it represents the full 2*M_PI coverange, if lseg is set to 1 only the extrema are given
Returns
A list of vertices and a face/facett description of it
Helper method to create the segment
Implements Acts::Surface.
Definition at line 175 of file CylinderSurface.cpp.
View newest version in sPHENIX GitHub at line 175 of file CylinderSurface.cpp
References Acts::detail::VerticesHelper::createSegment(), Acts::detail::FacesHelper::cylindricalFaceMesh(), Acts::CylinderBounds::eAveragePhi, Acts::CylinderBounds::eHalfLengthZ, Acts::CylinderBounds::eHalfPhiSector, Acts::CylinderBounds::eR, Acts::detail::VerticesHelper::phiSegments(), and Acts::Test::transform.
Referenced by Acts::ProtoLayer::measure().
const Acts::RotationMatrix3D Acts::CylinderSurface::referenceFrame (const GeometryContext & gctx, const Vector3D & position, const Vector3D & momentum) const final virtual
Return the measurement frame - this is needed for alignment, in particular The measurement frame of a cylinder is the tangential plane at a given position
Parameters
gctx The current geometry context object, e.g. alignment
position is the position where the measurement frame is defined
momentum is the momentum vector (ignored)
Returns
rotation matrix that defines the measurement frame
Reimplemented from Acts::Surface.
Definition at line 81 of file CylinderSurface.cpp.
View newest version in sPHENIX GitHub at line 81 of file CylinderSurface.cpp
const Vector3D CylinderSurface::rotSymmetryAxis (const GeometryContext & gctx) const inline virtual
Return method for the rotational symmetry axis
Parameters
gctx The current geometry context object, e.g. alignment
Returns
the z-Axis of transform
Definition at line 13 of file CylinderSurface.ipp.
View newest version in sPHENIX GitHub at line 13 of file CylinderSurface.ipp
References Acts::Test::transform.
Acts::Surface::SurfaceType Acts::CylinderSurface::type () const override virtual
Return the surface type.
Implements Acts::Surface.
Definition at line 100 of file CylinderSurface.cpp.
View newest version in sPHENIX GitHub at line 100 of file CylinderSurface.cpp
References Acts::Surface::Cylinder.
Member Data Documentation
std::shared_ptr<const CylinderBounds> Acts::CylinderSurface::m_bounds protected
bounds (shared)
Definition at line 223 of file CylinderSurface.hpp.
View newest version in sPHENIX GitHub at line 223 of file CylinderSurface.hpp
Referenced by Acts::CylinderLayer::CylinderLayer(), and operator=().
friend Acts::CylinderSurface::Surface private
Definition at line 35 of file CylinderSurface.hpp.
View newest version in sPHENIX GitHub at line 35 of file CylinderSurface.hpp
The documentation for this class was generated from the following files:
fun4all_acts/blob/master/Core/include/Acts/Surfaces/CylinderSurface.hpp
fun4all_acts/blob/master/Core/include/Acts/Surfaces/detail/CylinderSurface.ipp
fun4all_acts/blob/master/Core/src/Surfaces/CylinderSurface.cpp