EIC Software: GFAbsTrackRep Class Reference
GFAbsTrackRep Class Reference abstract
Genfit
Base Class for genfit track representations. Defines interface for track parameterizations.
#include <EicRoot/blob/master/genfit/GFAbsTrackRep.h>
Public Member Functions
virtual GFAbsTrackRep * clone () const =0
virtual GFAbsTrackRep * prototype () const =0
virtual double extrapolate (const GFDetPlane &plane, TMatrixT< double > &statePred)
returns the tracklength spanned in this extrapolation
GFAbsTrackRep ()
GFAbsTrackRep (int)
virtual ~GFAbsTrackRep ()
virtual void extrapolateToPoint (const TVector3 &point, TVector3 &poca, TVector3 &normVec)
This method is to extrapolate the track to point of closest approach to a point in space.
virtual void extrapolateToLine (const TVector3 &point1, const TVector3 &point2, TVector3 &poca, TVector3 &normVec, TVector3 &poca_onwire)
This method extrapolates to the point of closest approach to a line.
virtual double stepalong (double h, TVector3 &point, TVector3 &dir)
make step of h cm along the track
virtual double extrapolate (const GFDetPlane &plane, TMatrixT< double > &statePred, TMatrixT< double > &covPred)=0
Extrapolates the track to the given detectorplane.
double extrapolate (const GFDetPlane &plane)
This changes the state and cov and plane of the rep.
unsigned int getDim () const
returns dimension of state vector
virtual void Print (const Option_t *="") const
TMatrixT< double > getState () const
TMatrixT< double > getCov () const
double getStateElem (int i) const
double getCovElem (int i, int j) const
virtual TVector3 getPos (const GFDetPlane &pl)=0
virtual TVector3 getMom (const GFDetPlane &pl)=0
virtual void getPosMom (const GFDetPlane &pl, TVector3 &pos, TVector3 &mom)=0
virtual void getPosMomCov (const GFDetPlane &pl, TVector3 &pos, TVector3 &mom, TMatrixT< double > &cov)
method which gets position, momentum and 6x6 covariance matrix
virtual double getCharge () const =0
virtual int getPDG ()
method which gets pdg particle code
TVector3 getPos ()
TVector3 getMom ()
void getPosMomCov (TVector3 &pos, TVector3 &mom, TMatrixT< double > &c)
TMatrixT< double > getFirstState () const
TMatrixT< double > getFirstCov () const
GFDetPlane getFirstPlane () const
TMatrixT< double > getLastState () const
TMatrixT< double > getLastCov () const
GFDetPlane getLastPlane () const
double getChiSqu () const
double getForwardChiSqu () const
double getRedChiSqu () const
returns chi2/ndf
double getPVal () const
unsigned int getNDF () const
double getXX0 () const
X/X0 (total fraction of radiation length passed), cumulated during last extrapolation. The fitter has to reset XX0 via resetXX0()
virtual void setData (const TMatrixT< double > &st, const GFDetPlane &pl, const TMatrixT< double > *cov=NULL, const TMatrixT< double > *aux=NULL)
Puts the track representation in a given state.
void setCov (const TMatrixT< double > &aCov)
void setFirstState (const TMatrixT< double > &aState)
void setFirstCov (const TMatrixT< double > &aCov)
void setFirstPlane (const GFDetPlane &aPlane)
void setLastState (const TMatrixT< double > &aState)
void setLastCov (const TMatrixT< double > &aCov)
void setLastPlane (const GFDetPlane &aPlane)
virtual void setPosMomCov (const TVector3 &pos, const TVector3 &mom, const TMatrixT< double > &cov)
method which sets position, momentum and 6x6 covariance matrix
const GFDetPlane & getReferencePlane () const
void setChiSqu (double aChiSqu)
void setForwardChiSqu (double aChiSqu)
void setNDF (unsigned int n)
void addChiSqu (double aChiSqu)
void addForwardChiSqu (double aChiSqu)
void addNDF (unsigned int n)
void setStatusFlag (int _val)
virtual void switchDirection ()=0
bool setInverted (bool f=true)
Deprecated. Should be removed soon.
bool getStatusFlag ()
virtual void reset ()
virtual bool hasAuxInfo ()
See if the track representation has auxillary information stored.
virtual const TMatrixT< double > * getAuxInfo (const GFDetPlane &)
Get auxillary information from the track representation.
void resetXX0 ()
Protected Attributes
unsigned int fDimension
Dimensionality of track representation.
TMatrixT< double > fState
The vector of track parameters.
TMatrixT< double > fCov
The covariance matrix.
double fChiSqu
chiSqu of the track fit
double fForwardChiSqu
unsigned int fNdf
int fStatusFlag
status of track representation: 0 means everything's OK
bool fInverted
specifies the direction of flight of the particle
TMatrixT< double > fFirstState
state, cov and plane for first and last point in fit
TMatrixT< double > fFirstCov
TMatrixT< double > fLastState
TMatrixT< double > fLastCov
GFDetPlane fFirstPlane
GFDetPlane fLastPlane
GFDetPlane fRefPlane
double fXX0
Private Member Functions
void Abort (std::string method)
Detailed Description
Base Class for genfit track representations. Defines interface for track parameterizations.
Author
Christian Höppner (Technische Universität München, original author)
Sebastian Neubert (Technische Universität München, original author)
It is important to understand the difference between a track and a track representation in genfit:
A track representation is a specific parameterization of a trajectory. It contains the parameters that describe the track at some point and code for the extrapolation of the track parameters through space. The actual extrapolation code is not part of genfit but has to be supplied in some additional package (e.g. GEANE). LSLTrackRep is a very basic example of a track representation.
A Track is a collection of RecoHits (see GFAbsRecoHit) plus a collection of track representation objects. The hits can be from different detectors. There can be several representations of the same track. This makes it possible to perform several fits in parallel, for example to compare different parameterizations or to fit different particle hypotheses.
All track tepresentations must inherit GFAbsTrackRep to be available in genfit. Algorithms in genfit use this class as interface to access track parameters
Provides:
Matrix objects to store track parameters
... and covariances
interface to track extrapolation code
The track extrapolation engine can be exchanged in genfit. Or one can even use more than one engine in parallel! In order to use a track extrapolation engine (like e.g. GEANE) with genfit one has to write a TrackRep class that inherits from GFAbsTrackRep. This makes it possible to uses different track extrapolation codes within a unified framework without major changes in the detector code.
There is only one thing one has to do to use a specific track representation together with the hits from a detector: add the respective code in the GFAbsRecoHit::getHMatrix method implementation of the RecoHit in question.
Definition at line 81 of file GFAbsTrackRep.h.
View newest version in sPHENIX GitHub at line 81 of file GFAbsTrackRep.h
Constructor & Destructor Documentation
GFAbsTrackRep::GFAbsTrackRep ()
Definition at line 23 of file GFAbsTrackRep.cxx.
View newest version in sPHENIX GitHub at line 23 of file GFAbsTrackRep.cxx
GFAbsTrackRep::GFAbsTrackRep (int dim)
Definition at line 27 of file GFAbsTrackRep.cxx.
View newest version in sPHENIX GitHub at line 27 of file GFAbsTrackRep.cxx
GFAbsTrackRep::~GFAbsTrackRep () virtual
Definition at line 31 of file GFAbsTrackRep.cxx.
View newest version in sPHENIX GitHub at line 31 of file GFAbsTrackRep.cxx
Member Function Documentation
void GFAbsTrackRep::Abort (std::string method) private
Definition at line 47 of file GFAbsTrackRep.cxx.
View newest version in sPHENIX GitHub at line 47 of file GFAbsTrackRep.cxx
Referenced by extrapolateToLine(), extrapolateToPoint(), getPDG(), getPosMomCov(), setPosMomCov(), and stepalong().
void GFAbsTrackRep::addChiSqu (double aChiSqu) inline
Definition at line 339 of file GFAbsTrackRep.h.
View newest version in sPHENIX GitHub at line 339 of file GFAbsTrackRep.h
References fChiSqu.
Referenced by GFKalman::processHit().
void GFAbsTrackRep::addForwardChiSqu (double aChiSqu) inline
Definition at line 342 of file GFAbsTrackRep.h.
View newest version in sPHENIX GitHub at line 342 of file GFAbsTrackRep.h
References fForwardChiSqu.
Referenced by GFKalman::processHit().
void GFAbsTrackRep::addNDF (unsigned int n) inline
Definition at line 345 of file GFAbsTrackRep.h.
View newest version in sPHENIX GitHub at line 345 of file GFAbsTrackRep.h
References fNdf, and n.
Referenced by GFKalman::processHit().
virtual GFAbsTrackRep* GFAbsTrackRep::clone () const pure virtual
Implemented in LSLTrackRep, RKTrackRep, and GeaneTrackRep.
Referenced by GenfitTrack2PndTrack(), GFTools::getBiasedSmoothedData(), GFTools::getBiasedSmoothedMomXYZ(), GFTools::getSmoothedData(), and GFTrack::operator=().
double GFAbsTrackRep::extrapolate (const GFDetPlane & plane, TMatrixT< double > & statePred) virtual
returns the tracklength spanned in this extrapolation
There is a default implementation in GFAbsTrackRep.cxx which just drops the predicted covaraiance. If your trackrep has a way to extrapolate without giving a correct cov (that would be faster probably), please overwrite it. This method does NOT alter the state of the object!
Reimplemented in LSLTrackRep, and GeaneTrackRep.
Definition at line 42 of file GFAbsTrackRep.cxx.
View newest version in sPHENIX GitHub at line 42 of file GFAbsTrackRep.cxx
References Acts::Test::cov, and fDimension.
Referenced by extrapolate(), GFKalman::getChi2Hit(), GFTrack::getResiduals(), GFKalman::processHit(), and LSLTrackRep::stepalong().
virtual double GFAbsTrackRep::extrapolate (const GFDetPlane & plane, TMatrixT< double > & statePred, TMatrixT< double > & covPred) pure virtual
Extrapolates the track to the given detectorplane.
Results are put into statePred and covPred This method does NOT alter the state of the object!
Implemented in LSLTrackRep, and GeaneTrackRep.
double GFAbsTrackRep::extrapolate (const GFDetPlane & plane)
This changes the state and cov and plane of the rep.
This method extrapolates to to the plane and sets the results of state, cov and also plane in itself.
Definition at line 33 of file GFAbsTrackRep.cxx.
View newest version in sPHENIX GitHub at line 33 of file GFAbsTrackRep.cxx
References extrapolate(), fDimension, and setData().
void GFAbsTrackRep::extrapolateToLine (const TVector3 & point1, const TVector3 & point2, TVector3 & poca, TVector3 & normVec, TVector3 & poca_onwire) virtual
This method extrapolates to the point of closest approach to a line.
This method extrapolates to the POCA to a line, i.e. a wire. There is a default implementation just like for the extrapolateToPoca for trackReps which do not need this feature, which will abort the execution if it is ever called. This method does NOT alter the state of the object!
Reimplemented in RKTrackRep, and GeaneTrackRep.
Definition at line 62 of file GFAbsTrackRep.cxx.
View newest version in sPHENIX GitHub at line 62 of file GFAbsTrackRep.cxx
References Abort().
Referenced by GFWirepointHitPolicy::detPlane(), GFWireHitPolicy::detPlane(), and GFPseudoSpacepointWireHitPolicy::detPlane().
void GFAbsTrackRep::extrapolateToPoint (const TVector3 & point, TVector3 & poca, TVector3 & normVec) virtual
This method is to extrapolate the track to point of closest approach to a point in space.
There is an empty implementation of this method in GFAbsTrackRep.cxx, which will just abort with an error message. One can overwrite this method if one wishes to implement a track representation, which should have this feature. An example of an experiment in which you would not need this feature would be track fitting (not so much vertexing) in an experiment with only planar trackers like silicons or planar wire chambers and such. An example where you would need it, would be a TPC where you have to fit the track to space points, or other drift chambers with complicated hit topology. This method does NOT alter the state of the object!
Reimplemented in RKTrackRep, LSLTrackRep, and GeaneTrackRep.
Definition at line 56 of file GFAbsTrackRep.cxx.
View newest version in sPHENIX GitHub at line 56 of file GFAbsTrackRep.cxx
References Abort().
Referenced by GFSpacepointHitPolicy::detPlane(), PrimSelector::Exec(), and trackProximity().
virtual const TMatrixT<double>* GFAbsTrackRep::getAuxInfo (const GFDetPlane &) inline virtual
Get auxillary information from the track representation.
AuxInfo is a mechanism which allows creators of track repersentations to hand out any information they like (as long as it is compatible with a TMatrixT<double>). It should be used if setData requires additional information to update the representation, but it can also be used for debugging information if needed. See also the documentation of GFAbsTrackRep::setData().
Reimplemented in RKTrackRep.
Definition at line 381 of file GFAbsTrackRep.h.
View newest version in sPHENIX GitHub at line 381 of file GFAbsTrackRep.h
Referenced by GFKalman::processHit().
virtual double GFAbsTrackRep::getCharge () const pure virtual
Implemented in RKTrackRep, LSLTrackRep, and GeaneTrackRep.
Referenced by GFTrack::getCharge().
double GFAbsTrackRep::getChiSqu () const inline
Definition at line 257 of file GFAbsTrackRep.h.
View newest version in sPHENIX GitHub at line 257 of file GFAbsTrackRep.h
References fChiSqu.
Referenced by GFTrack::getChiSqu(), getPVal(), and getRedChiSqu().
TMatrixT<double> GFAbsTrackRep::getCov () const inline
Definition at line 205 of file GFAbsTrackRep.h.
View newest version in sPHENIX GitHub at line 205 of file GFAbsTrackRep.h
References fCov.
Referenced by GFTrack::blowUpCovs(), GFKalman::processHit(), and GFKalman::processTrack().
double GFAbsTrackRep::getCovElem (int i, int j) const inline
Definition at line 210 of file GFAbsTrackRep.h.
View newest version in sPHENIX GitHub at line 210 of file GFAbsTrackRep.h
References fCov.
unsigned int GFAbsTrackRep::getDim () const inline
returns dimension of state vector
Definition at line 198 of file GFAbsTrackRep.h.
View newest version in sPHENIX GitHub at line 198 of file GFAbsTrackRep.h
References fDimension.
Referenced by GeaneTrackRep::extrapolateToPoint(), LSLTrackRep::extrapolateToPoint(), GFKalman::getChi2Hit(), getNDF(), GFTrack::getResiduals(), and GFKalman::processHit().
TMatrixT<double> GFAbsTrackRep::getFirstCov () const inline
Definition at line 242 of file GFAbsTrackRep.h.
View newest version in sPHENIX GitHub at line 242 of file GFAbsTrackRep.h
References fFirstCov.
Referenced by GenfitTrack2PndTrack().
GFDetPlane GFAbsTrackRep::getFirstPlane () const inline
Definition at line 245 of file GFAbsTrackRep.h.
View newest version in sPHENIX GitHub at line 245 of file GFAbsTrackRep.h
References fFirstPlane.
Referenced by GenfitTrack2PndTrack().
TMatrixT<double> GFAbsTrackRep::getFirstState () const inline
Definition at line 239 of file GFAbsTrackRep.h.
View newest version in sPHENIX GitHub at line 239 of file GFAbsTrackRep.h
References fFirstState.
Referenced by GenfitTrack2PndTrack().
double GFAbsTrackRep::getForwardChiSqu () const inline
Definition at line 260 of file GFAbsTrackRep.h.
View newest version in sPHENIX GitHub at line 260 of file GFAbsTrackRep.h
References fForwardChiSqu.
Referenced by GFTrack::getForwardChiSqu().
TMatrixT<double> GFAbsTrackRep::getLastCov () const inline
Definition at line 251 of file GFAbsTrackRep.h.
View newest version in sPHENIX GitHub at line 251 of file GFAbsTrackRep.h
References fLastCov.
Referenced by GenfitTrack2PndTrack().
GFDetPlane GFAbsTrackRep::getLastPlane () const inline
Definition at line 254 of file GFAbsTrackRep.h.
View newest version in sPHENIX GitHub at line 254 of file GFAbsTrackRep.h
References fLastPlane.
Referenced by GenfitTrack2PndTrack().
TMatrixT<double> GFAbsTrackRep::getLastState () const inline
Definition at line 248 of file GFAbsTrackRep.h.
View newest version in sPHENIX GitHub at line 248 of file GFAbsTrackRep.h
References fLastState.
Referenced by GenfitTrack2PndTrack().
virtual TVector3 GFAbsTrackRep::getMom (const GFDetPlane & pl) pure virtual
Implemented in RKTrackRep, LSLTrackRep, and GeaneTrackRep.
Referenced by PrimSelector::Exec(), GenfitTrack2PndTrack(), and GFTrack::getMom().
TVector3 GFAbsTrackRep::getMom () inline
Definition at line 234 of file GFAbsTrackRep.h.
View newest version in sPHENIX GitHub at line 234 of file GFAbsTrackRep.h
References fRefPlane, and getMom().
Referenced by GeaneTrackRep::extrapolate(), GeaneTrackRep::extrapolateToLine(), GeaneTrackRep::extrapolateToPoint(), LSLTrackRep::getGlobal(), and getMom().
unsigned int GFAbsTrackRep::getNDF () const inline
Definition at line 272 of file GFAbsTrackRep.h.
View newest version in sPHENIX GitHub at line 272 of file GFAbsTrackRep.h
References fNdf, and getDim().
Referenced by GFTrack::getNDF(), getPVal(), and getRedChiSqu().
int GFAbsTrackRep::getPDG () virtual
method which gets pdg particle code
default implementation in cxx; should be implemented in a ConcreteTrackRep
Reimplemented in RKTrackRep, and GeaneTrackRep.
Definition at line 79 of file GFAbsTrackRep.cxx.
View newest version in sPHENIX GitHub at line 79 of file GFAbsTrackRep.cxx
References Abort().
virtual TVector3 GFAbsTrackRep::getPos (const GFDetPlane & pl) pure virtual
Implemented in RKTrackRep, LSLTrackRep, and GeaneTrackRep.
Referenced by GFTrack::fillGeoTrack(), GFTrack::getPos(), and trkDist().
TVector3 GFAbsTrackRep::getPos () inline
Definition at line 233 of file GFAbsTrackRep.h.
View newest version in sPHENIX GitHub at line 233 of file GFAbsTrackRep.h
References fRefPlane, and getPos().
Referenced by GeaneTrackRep::extrapolateToLine(), LSLTrackRep::getGlobal(), and getPos().
virtual void GFAbsTrackRep::getPosMom (const GFDetPlane & pl, TVector3 & pos, TVector3 & mom) pure virtual
Implemented in RKTrackRep, LSLTrackRep, and GeaneTrackRep.
void GFAbsTrackRep::getPosMomCov (const GFDetPlane & pl, TVector3 & pos, TVector3 & mom, TMatrixT< double > & cov) virtual
method which gets position, momentum and 6x6 covariance matrix
default implementation in cxx file, if a ConcreteTrackRep can not implement this functionality
Reimplemented in GeaneTrackRep.
Definition at line 85 of file GFAbsTrackRep.cxx.
View newest version in sPHENIX GitHub at line 85 of file GFAbsTrackRep.cxx
References Abort().
Referenced by getPosMomCov(), and GFTrack::getPosMomCov().
void GFAbsTrackRep::getPosMomCov (TVector3 & pos, TVector3 & mom, TMatrixT< double > & c) inline
Definition at line 235 of file GFAbsTrackRep.h.
View newest version in sPHENIX GitHub at line 235 of file GFAbsTrackRep.h
References fRefPlane, and getPosMomCov().
double GFAbsTrackRep::getPVal () const inline
Definition at line 269 of file GFAbsTrackRep.h.
View newest version in sPHENIX GitHub at line 269 of file GFAbsTrackRep.h
References getChiSqu(), and getNDF().
double GFAbsTrackRep::getRedChiSqu () const inline
returns chi2/ndf
Definition at line 264 of file GFAbsTrackRep.h.
View newest version in sPHENIX GitHub at line 264 of file GFAbsTrackRep.h
References getChiSqu(), and getNDF().
Referenced by GFTrack::getRedChiSqu().
const GFDetPlane& GFAbsTrackRep::getReferencePlane () const inline
Definition at line 328 of file GFAbsTrackRep.h.
View newest version in sPHENIX GitHub at line 328 of file GFAbsTrackRep.h
References fRefPlane.
Referenced by GFKalman::processHit(), and GFKalman::processTrack().
TMatrixT<double> GFAbsTrackRep::getState () const inline
Definition at line 202 of file GFAbsTrackRep.h.
View newest version in sPHENIX GitHub at line 202 of file GFAbsTrackRep.h
References fState.
Referenced by GFTrack::fillGeoTrack(), GFTrack::getResiduals(), GFKalman::processHit(), and GFKalman::processTrack().
double GFAbsTrackRep::getStateElem (int i) const inline
Definition at line 209 of file GFAbsTrackRep.h.
View newest version in sPHENIX GitHub at line 209 of file GFAbsTrackRep.h
References fState.
bool GFAbsTrackRep::getStatusFlag () inline
Definition at line 357 of file GFAbsTrackRep.h.
View newest version in sPHENIX GitHub at line 357 of file GFAbsTrackRep.h
References fStatusFlag.
Referenced by GFTrack::blowUpCovs(), GFKalman::fittingPass(), and GFDaf::processTrack().
double GFAbsTrackRep::getXX0 () const inline
X/X0 (total fraction of radiation length passed), cumulated during last extrapolation. The fitter has to reset XX0 via resetXX0()
Definition at line 279 of file GFAbsTrackRep.h.
View newest version in sPHENIX GitHub at line 279 of file GFAbsTrackRep.h
References fXX0.
virtual bool GFAbsTrackRep::hasAuxInfo () inline virtual
See if the track representation has auxillary information stored.
See if auxillary information is stored in the track representation. See the documentation of GFAbsTrackRep::getAuxInfo() for details.
Reimplemented in RKTrackRep.
Definition at line 368 of file GFAbsTrackRep.h.
View newest version in sPHENIX GitHub at line 368 of file GFAbsTrackRep.h
Referenced by GFDaf::copySmoothing(), GFTools::getBiasedSmoothedData(), GFTools::getSmoothedData(), GFKalman::processHit(), GFKalman::processTrack(), and GFTools::updateRepSmoothed().
void GFAbsTrackRep::Print (const Option_t * option = "") const virtual
Definition at line 107 of file GFAbsTrackRep.cxx.
View newest version in sPHENIX GitHub at line 107 of file GFAbsTrackRep.cxx
References fChiSqu, fCov, fRefPlane, fState, and GFDetPlane::Print().
Referenced by GFTrack::Print().
virtual GFAbsTrackRep* GFAbsTrackRep::prototype () const pure virtual
Implemented in LSLTrackRep, RKTrackRep, and GeaneTrackRep.
void GFAbsTrackRep::reset () virtual
Definition at line 94 of file GFAbsTrackRep.cxx.
View newest version in sPHENIX GitHub at line 94 of file GFAbsTrackRep.cxx
References fCov, fFirstCov, fFirstState, fLastCov, fLastState, fRefPlane, fState, and GFDetPlane::set().
void GFAbsTrackRep::resetXX0 () inline
Definition at line 386 of file GFAbsTrackRep.h.
View newest version in sPHENIX GitHub at line 386 of file GFAbsTrackRep.h
References fXX0.
Referenced by GFKalman::processTrack().
void GFAbsTrackRep::setChiSqu (double aChiSqu) inline
Definition at line 330 of file GFAbsTrackRep.h.
View newest version in sPHENIX GitHub at line 330 of file GFAbsTrackRep.h
References fChiSqu.
Referenced by GFKalman::fittingPass().
void GFAbsTrackRep::setCov (const TMatrixT< double > & aCov) inline
Definition at line 299 of file GFAbsTrackRep.h.
View newest version in sPHENIX GitHub at line 299 of file GFAbsTrackRep.h
References fCov.
Referenced by GFTrack::blowUpCovs().
virtual void GFAbsTrackRep::setData (const TMatrixT< double > & st, const GFDetPlane & pl, const TMatrixT< double > * cov = NULL, const TMatrixT< double > * aux = NULL) inline virtual
Puts the track representation in a given state.
This is used to update the track representation after the update of the Kalman filter was calculated.
IMPORTANT: One should be able to set the track representation to arbitraty values using this method. If the track representation needs additional information beside the state vector, the plane and the covariance, it has to be handed over via the "aux" Matrix. GFAbsTrackRep::getAuxInfo() should return the appropriate information. This is mandatory if smoothing is used.
Definition at line 293 of file GFAbsTrackRep.h.
View newest version in sPHENIX GitHub at line 293 of file GFAbsTrackRep.h
References Acts::Test::cov, fCov, fRefPlane, and fState.
Referenced by extrapolate(), GFTools::getBiasedSmoothedData(), GFTools::getSmoothedData(), GFKalman::processHit(), LSLTrackRep::setData(), RKTrackRep::setData(), and GFTools::updateRepSmoothed().
void GFAbsTrackRep::setFirstCov (const TMatrixT< double > & aCov) inline
Definition at line 305 of file GFAbsTrackRep.h.
View newest version in sPHENIX GitHub at line 305 of file GFAbsTrackRep.h
References fFirstCov.
void GFAbsTrackRep::setFirstPlane (const GFDetPlane & aPlane) inline
Definition at line 308 of file GFAbsTrackRep.h.
View newest version in sPHENIX GitHub at line 308 of file GFAbsTrackRep.h
References Acts::Test::aPlane, and fFirstPlane.
void GFAbsTrackRep::setFirstState (const TMatrixT< double > & aState) inline
Definition at line 302 of file GFAbsTrackRep.h.
View newest version in sPHENIX GitHub at line 302 of file GFAbsTrackRep.h
References fFirstState.
void GFAbsTrackRep::setForwardChiSqu (double aChiSqu) inline
Definition at line 333 of file GFAbsTrackRep.h.
View newest version in sPHENIX GitHub at line 333 of file GFAbsTrackRep.h
References fForwardChiSqu.
Referenced by GFKalman::fittingPass().
bool GFAbsTrackRep::setInverted (bool f = true) inline
Deprecated. Should be removed soon.
Definition at line 355 of file GFAbsTrackRep.h.
View newest version in sPHENIX GitHub at line 355 of file GFAbsTrackRep.h
References fInverted.
void GFAbsTrackRep::setLastCov (const TMatrixT< double > & aCov) inline
Definition at line 314 of file GFAbsTrackRep.h.
View newest version in sPHENIX GitHub at line 314 of file GFAbsTrackRep.h
References fLastCov.
void GFAbsTrackRep::setLastPlane (const GFDetPlane & aPlane) inline
Definition at line 317 of file GFAbsTrackRep.h.
View newest version in sPHENIX GitHub at line 317 of file GFAbsTrackRep.h
References Acts::Test::aPlane, and fLastPlane.
void GFAbsTrackRep::setLastState (const TMatrixT< double > & aState) inline
Definition at line 311 of file GFAbsTrackRep.h.
View newest version in sPHENIX GitHub at line 311 of file GFAbsTrackRep.h
References fLastState.
void GFAbsTrackRep::setNDF (unsigned int n) inline
Definition at line 336 of file GFAbsTrackRep.h.
View newest version in sPHENIX GitHub at line 336 of file GFAbsTrackRep.h
References fNdf, and n.
Referenced by GFKalman::fittingPass().
void GFAbsTrackRep::setPosMomCov (const TVector3 & pos, const TVector3 & mom, const TMatrixT< double > & cov) virtual
method which sets position, momentum and 6x6 covariance matrix
default implementation in cxx file, if a ConcreteTrackRep can not implement this functionality
Definition at line 89 of file GFAbsTrackRep.cxx.
View newest version in sPHENIX GitHub at line 89 of file GFAbsTrackRep.cxx
References Abort().
void GFAbsTrackRep::setStatusFlag (int _val) inline
Definition at line 348 of file GFAbsTrackRep.h.
View newest version in sPHENIX GitHub at line 348 of file GFAbsTrackRep.h
References fStatusFlag.
Referenced by GFKalman::fittingPass(), and GFDaf::processTrack().
double GFAbsTrackRep::stepalong (double h, TVector3 & point, TVector3 & dir) virtual
make step of h cm along the track
There is an empty implementation in GFAbsTrackRep.cxx which will abort (see one of the extrapolate methods above). This can be overwritten, if this feature is needed. This method does NOT alter the state of the object!
Reimplemented in RKTrackRep.
Definition at line 71 of file GFAbsTrackRep.cxx.
View newest version in sPHENIX GitHub at line 71 of file GFAbsTrackRep.cxx
References Abort().
Referenced by trackProximity().
virtual void GFAbsTrackRep::switchDirection () pure virtual
Implemented in RKTrackRep, LSLTrackRep, and GeaneTrackRep.
Referenced by GFKalman::switchDirection().
Member Data Documentation
double GFAbsTrackRep::fChiSqu protected
chiSqu of the track fit
Definition at line 95 of file GFAbsTrackRep.h.
View newest version in sPHENIX GitHub at line 95 of file GFAbsTrackRep.h
Referenced by addChiSqu(), getChiSqu(), Print(), and setChiSqu().
TMatrixT<double> GFAbsTrackRep::fCov protected
The covariance matrix.
Definition at line 92 of file GFAbsTrackRep.h.
View newest version in sPHENIX GitHub at line 92 of file GFAbsTrackRep.h
Referenced by RKTrackRep::calcStateCov(), GeaneTrackRep::extrapolate(), LSLTrackRep::extrapolate(), RKTrackRep::extrapolate(), GeaneTrackRep::extrapolateToLine(), GeaneTrackRep::extrapolateToPoint(), GeaneTrackRep::GeaneTrackRep(), getCov(), getCovElem(), LSLTrackRep::getGlobalCov(), GeaneTrackRep::getPocaOnLine(), GeaneTrackRep::getPosMomCov(), RKTrackRep::getPosMomCov(), LSLTrackRep::init(), LSLTrackRep::LSLTrackRep(), Print(), reset(), RKTrackRep::RKTrackRep(), setCov(), setData(), and RKTrackRep::setPosMomCov().
unsigned int GFAbsTrackRep::fDimension protected
Dimensionality of track representation.
Definition at line 86 of file GFAbsTrackRep.h.
View newest version in sPHENIX GitHub at line 86 of file GFAbsTrackRep.h
Referenced by GeaneTrackRep::extrapolate(), LSLTrackRep::extrapolate(), extrapolate(), and getDim().
TMatrixT<double> GFAbsTrackRep::fFirstCov protected
Definition at line 106 of file GFAbsTrackRep.h.
View newest version in sPHENIX GitHub at line 106 of file GFAbsTrackRep.h
Referenced by getFirstCov(), reset(), and setFirstCov().
GFDetPlane GFAbsTrackRep::fFirstPlane protected
Definition at line 110 of file GFAbsTrackRep.h.
View newest version in sPHENIX GitHub at line 110 of file GFAbsTrackRep.h
Referenced by getFirstPlane(), and setFirstPlane().
TMatrixT<double> GFAbsTrackRep::fFirstState protected
state, cov and plane for first and last point in fit
Definition at line 105 of file GFAbsTrackRep.h.
View newest version in sPHENIX GitHub at line 105 of file GFAbsTrackRep.h
Referenced by getFirstState(), reset(), and setFirstState().
double GFAbsTrackRep::fForwardChiSqu protected
Definition at line 96 of file GFAbsTrackRep.h.
View newest version in sPHENIX GitHub at line 96 of file GFAbsTrackRep.h
Referenced by addForwardChiSqu(), getForwardChiSqu(), and setForwardChiSqu().
bool GFAbsTrackRep::fInverted protected
specifies the direction of flight of the particle
Definition at line 102 of file GFAbsTrackRep.h.
View newest version in sPHENIX GitHub at line 102 of file GFAbsTrackRep.h
Referenced by LSLTrackRep::getCharge(), LSLTrackRep::getMom(), LSLTrackRep::getPosMom(), and setInverted().
TMatrixT<double> GFAbsTrackRep::fLastCov protected
Definition at line 109 of file GFAbsTrackRep.h.
View newest version in sPHENIX GitHub at line 109 of file GFAbsTrackRep.h
Referenced by getLastCov(), reset(), and setLastCov().
GFDetPlane GFAbsTrackRep::fLastPlane protected
Definition at line 111 of file GFAbsTrackRep.h.
View newest version in sPHENIX GitHub at line 111 of file GFAbsTrackRep.h
Referenced by getLastPlane(), and setLastPlane().
TMatrixT<double> GFAbsTrackRep::fLastState protected
Definition at line 108 of file GFAbsTrackRep.h.
View newest version in sPHENIX GitHub at line 108 of file GFAbsTrackRep.h
Referenced by getLastState(), reset(), and setLastState().
unsigned int GFAbsTrackRep::fNdf protected
Definition at line 97 of file GFAbsTrackRep.h.
View newest version in sPHENIX GitHub at line 97 of file GFAbsTrackRep.h
Referenced by addNDF(), getNDF(), and setNDF().
GFDetPlane GFAbsTrackRep::fRefPlane protected
Definition at line 114 of file GFAbsTrackRep.h.
View newest version in sPHENIX GitHub at line 114 of file GFAbsTrackRep.h
Referenced by RKTrackRep::calcState(), RKTrackRep::calcStateCov(), GeaneTrackRep::extrapolate(), RKTrackRep::extrapolate(), GeaneTrackRep::extrapolateToLine(), GeaneTrackRep::extrapolateToPoint(), GeaneTrackRep::GeaneTrackRep(), GeaneTrackRep::getMom(), RKTrackRep::getMom(), getMom(), GeaneTrackRep::getPocaOnLine(), GeaneTrackRep::getPos(), RKTrackRep::getPos(), getPos(), GeaneTrackRep::getPosMom(), RKTrackRep::getPosMom(), GeaneTrackRep::getPosMomCov(), RKTrackRep::getPosMomCov(), getPosMomCov(), getReferencePlane(), RKTrackRep::getState7(), LSLTrackRep::init(), LSLTrackRep::LSLTrackRep(), Print(), reset(), setData(), RKTrackRep::setPosMomCov(), and LSLTrackRep::stepalong().
TMatrixT<double> GFAbsTrackRep::fState protected
The vector of track parameters.
Definition at line 89 of file GFAbsTrackRep.h.
View newest version in sPHENIX GitHub at line 89 of file GFAbsTrackRep.h
Referenced by RKTrackRep::calcState(), GeaneTrackRep::checkState(), GeaneTrackRep::extrapolate(), LSLTrackRep::extrapolate(), RKTrackRep::extrapolate(), GeaneTrackRep::extrapolateToLine(), GeaneTrackRep::extrapolateToPoint(), GeaneTrackRep::GeaneTrackRep(), GeaneTrackRep::getCharge(), LSLTrackRep::getCharge(), LSLTrackRep::getGlobalCov(), GeaneTrackRep::getMom(), LSLTrackRep::getMom(), GeaneTrackRep::getPocaOnLine(), GeaneTrackRep::getPos(), LSLTrackRep::getPos(), GeaneTrackRep::getPosMom(), LSLTrackRep::getPosMom(), GeaneTrackRep::getPosMomCov(), RKTrackRep::getPosMomCov(), getState(), RKTrackRep::getState7(), getStateElem(), LSLTrackRep::init(), LSLTrackRep::Jacobian(), LSLTrackRep::LSLTrackRep(), Print(), reset(), RKTrackRep::setData(), and setData().
int GFAbsTrackRep::fStatusFlag protected
status of track representation: 0 means everything's OK
Definition at line 100 of file GFAbsTrackRep.h.
View newest version in sPHENIX GitHub at line 100 of file GFAbsTrackRep.h
Referenced by getStatusFlag(), and setStatusFlag().
double GFAbsTrackRep::fXX0 protected
Definition at line 116 of file GFAbsTrackRep.h.
View newest version in sPHENIX GitHub at line 116 of file GFAbsTrackRep.h
Referenced by RKTrackRep::Extrap(), getXX0(), and resetXX0().
The documentation for this class was generated from the following files:
EicRoot/blob/master/genfit/GFAbsTrackRep.h
EicRoot/blob/master/genfit/GFAbsTrackRep.cxx