EIC Software: fun4all_eicmacros/blob/master/detectors/Beast/G4Setup_Beast.C File Reference
G4Setup_Beast.C File Reference
#include <GlobalVariables.C>
#include <G4_BlackHole.C>
#include <G4_Magnet_Beast.C>
#include <G4_Pipe_EIC.C>
#include <G4_User.C>
#include <G4_World.C>
#include <g4decayer/EDecayType.hh>
#include <g4main/PHG4Reco.h>
#include <g4main/PHG4TruthSubsystem.h>
#include <phfield/PHFieldConfig.h>
#include <fun4all/Fun4AllDstOutputManager.h>
#include <fun4all/Fun4AllServer.h>
Macros
#define MACRO_G4SETUPBEAST_C
Functions
void G4Init ()
void G4Setup ()
void DstCompress (Fun4AllDstOutputManager *out)
Macro Definition Documentation
#define MACRO_G4SETUPBEAST_C
Definition at line 2 of file G4Setup_Beast.C.
View newest version in sPHENIX GitHub at line 2 of file G4Setup_Beast.C
Function Documentation
void DstCompress (Fun4AllDstOutputManager * out)
Definition at line 87 of file G4Setup_Beast.C.
View newest version in sPHENIX GitHub at line 87 of file G4Setup_Beast.C
References Fun4AllDstOutputManager::StripNode().
void G4Init ()
Definition at line 24 of file G4Setup_Beast.C.
View newest version in sPHENIX GitHub at line 24 of file G4Setup_Beast.C
References Enable::MAGNET, MagnetFieldInit(), MagnetInit(), Enable::PIPE, and PipeInit().
void G4Setup ()
Definition at line 33 of file G4Setup_Beast.C.
View newest version in sPHENIX GitHub at line 33 of file G4Setup_Beast.C
References Enable::BLACKHOLE, BlackHole(), G4P6DECAYER::decayType, Fun4AllServer::instance(), kAll, PHFieldConfig::kFieldBeast, G4MAGNET::magfield, G4MAGNET::magfield_rescale, Enable::MAGNET, Magnet(), Enable::PIPE, Pipe(), G4BECAL::radius, Fun4AllServer::registerSubsystem(), PHG4Reco::registerSubsystem(), PHG4Reco::set_field(), PHG4Reco::set_field_map(), PHG4Reco::set_field_rescale(), PHG4Reco::set_force_decay(), PHG4Reco::set_rapidity_coverage(), Enable::USER, UserDetector(), WorldInit(), and WorldSize().