EIC Software: CbmReportElement Class Reference
CbmReportElement Class Reference abstract
Abstract class for basic report elements (headers, tables, images etc.).
#include <EicRoot/blob/master/cbmbase/report/CbmReportElement.h>
Public Member Functions
CbmReportElement ()
Constructor.
virtual ~CbmReportElement ()
Destructor.
virtual string TableBegin (const string &caption, const vector< string > &colNames) const =0
Return string with table open tag.
virtual string TableEnd () const =0
Return string with table close tag.
virtual string TableEmptyRow (int nofCols, const string &name) const =0
Return string with table row which spans over all columns.
virtual string TableRow (const vector< string > &row) const =0
Return string with table row tags.
virtual string Image (const string &title, const string &file) const =0
Return string with image tags.
virtual string DocumentBegin () const =0
Return string with open tags for document.
virtual string DocumentEnd () const =0
Return string with close tags of the document.
virtual string Title (int size, const string &title) const =0
Return string with title.
Detailed Description
Abstract class for basic report elements (headers, tables, images etc.).
Each concrete implementation for report elements has to implement this interface (e.g. Latex, text, HTML). Report has to be written using functionality of this interface class in order to be able to automatically produce reports in different representations (e.g. Latex, text, HTML).
Author
Semen Lebedev s.leb.nosp@m.edev.nosp@m.@gsi..nosp@m.de
Date
2011
Definition at line 32 of file CbmReportElement.h.
View newest version in sPHENIX GitHub at line 32 of file CbmReportElement.h
Constructor & Destructor Documentation
CbmReportElement::CbmReportElement () inline
Constructor.
Definition at line 38 of file CbmReportElement.h.
View newest version in sPHENIX GitHub at line 38 of file CbmReportElement.h
virtual CbmReportElement::~CbmReportElement () inline virtual
Destructor.
Definition at line 43 of file CbmReportElement.h.
View newest version in sPHENIX GitHub at line 43 of file CbmReportElement.h
Member Function Documentation
virtual string CbmReportElement::DocumentBegin () const pure virtual
Return string with open tags for document.
Returns
string with open tags for document.
Implemented in CbmTextReportElement, CbmHtmlReportElement, and CbmLatexReportElement.
Referenced by CbmRichGeoTestStudyReport::Create().
virtual string CbmReportElement::DocumentEnd () const pure virtual
Return string with close tags of the document.
Returns
string with close tags of the document.
Implemented in CbmTextReportElement, CbmHtmlReportElement, and CbmLatexReportElement.
Referenced by CbmRichGeoTestStudyReport::Create().
virtual string CbmReportElement::Image (const string & title, const string & file) const pure virtual
Return string with image tags.
Parameters
[in] title Title of the image.
[in] file Name of the image file.
Returns
string with image tags.
Implemented in CbmTextReportElement, CbmHtmlReportElement, and CbmLatexReportElement.
Referenced by CbmReport::PrintCanvases().
virtual string CbmReportElement::TableBegin (const string & caption, const vector< string > & colNames) const pure virtual
Return string with table open tag.
Parameters
[in] caption Table caption.
[in] colNames Names of the columns in table.
Returns
String with table open tag.
Implemented in CbmTextReportElement, CbmHtmlReportElement, and CbmLatexReportElement.
Referenced by CbmRichGeoTestStudyReport::Create().
virtual string CbmReportElement::TableEmptyRow (int nofCols, const string & name) const pure virtual
Return string with table row which spans over all columns.
Parameters
[in] nofCols number of columns in table.
[in] name Name of the row.
Returns
string with table row which spans over all columns.
Implemented in CbmHtmlReportElement, and CbmLatexReportElement.
virtual string CbmReportElement::TableEnd () const pure virtual
Return string with table close tag.
Returns
String with table close tag.
Implemented in CbmTextReportElement, CbmHtmlReportElement, and CbmLatexReportElement.
Referenced by CbmRichGeoTestStudyReport::Create().
virtual string CbmReportElement::TableRow (const vector< string > & row) const pure virtual
Return string with table row tags.
Parameters
[in] data Array of strings with data for each cell in a row.
Returns
string with table row tags.
Implemented in CbmTextReportElement, CbmHtmlReportElement, and CbmLatexReportElement.
Referenced by CbmRichGeoTestStudyReport::PrintRow().
virtual string CbmReportElement::Title (int size, const string & title) const pure virtual
Return string with title.
Parameters
[in] size Size of the title. [0-5]. 0 is the largest size.
[in] title Title string.
Returns
string with subtitle.
Implemented in CbmHtmlReportElement, and CbmLatexReportElement.
Referenced by CbmRichGeoTestStudyReport::Create().
The documentation for this class was generated from the following file:
EicRoot/blob/master/cbmbase/report/CbmReportElement.h