EIC Software: FairDbResultSet Class Reference
FairDbResultSet Class Reference
#include <EicRoot/blob/master/dbase/dbInterface/FairDbResult.h>
Public Member Functions
FairDbResultSet (FairDbStatement *stmtDb, const FairDbString &sql, const FairDbTableMetaData *metaData, const FairDbTableProxy *tableProxy, UInt_t dbNo, const string &fillOpts="")
virtual ~FairDbResultSet ()
Bool_t CurColExists () const
string CurColString () const
string CurColValue () const
UInt_t CurRowNum () const
UInt_t GetDbNo () const
FairDb::DbTypes GetDBType () const
string GetFillOpts () const
const FairDbTableProxy * GetTableProxy () const
Bool_t IsBeforeFirst () const
Bool_t IsExhausted () const
void RowAsCsv (string &row) const
FairDbResultSet & operator>> (Bool_t &dest)
FairDbResultSet & operator>> (Char_t &dest)
FairDbResultSet & operator>> (Short_t &dest)
FairDbResultSet & operator>> (UShort_t &dest)
FairDbResultSet & operator>> (Int_t &dest)
FairDbResultSet & operator>> (UInt_t &dest)
FairDbResultSet & operator>> (Long_t &dest)
FairDbResultSet & operator>> (ULong_t &dest)
FairDbResultSet & operator>> (Float_t &dest)
FairDbResultSet & operator>> (Double_t &dest)
FairDbResultSet & operator>> (string &dest)
FairDbResultSet & operator>> (ValTimeStamp &dest)
Bool_t FetchRow ()
Public Member Functions inherited from FairDbRowStream
FairDbRowStream (const FairDbTableMetaData *metaData)
virtual ~FairDbRowStream ()
virtual const FairDbFieldType & ColFieldType (UInt_t col) const
virtual string ColName (UInt_t col) const
virtual const FairDbFieldType & CurColFieldType () const
virtual string CurColName () const
virtual UInt_t CurColNum () const
Bool_t HasRowCounter () const
virtual UInt_t NumCols () const
virtual string TableName () const
virtual string TableNameTc () const
virtual const FairDbTableMetaData * MetaData () const
virtual void DecrementCurCol ()
virtual void IncrementCurCol ()
Private Member Functions
string & AsString (FairDb::DataTypes type)
Bool_t LoadCurValue () const
TString GetStringFromTSQL (Int_t col) const
FairDbResultSet (const FairDbResultSet &)
FairDbResultSet operator= (const FairDbResultSet &)
Private Attributes
Int_t fCurRow
UInt_t fDbNo
FairDb::DbTypes fDbType
FairDbStatement * fStatement
TSQLStatement * fTSQLStatement
Bool_t fExhausted
const FairDbTableProxy * fTableProxy
string fValString
string fFillOpts
Additional Inherited Members
Protected Member Functions inherited from FairDbRowStream
virtual void ClearCurCol ()
Detailed Description
Definition at line 85 of file FairDbResult.h.
View newest version in sPHENIX GitHub at line 85 of file FairDbResult.h
Constructor & Destructor Documentation
FairDbResultSet::FairDbResultSet (FairDbStatement * stmtDb, const FairDbString & sql, const FairDbTableMetaData * metaData, const FairDbTableProxy * tableProxy, UInt_t dbNo, const string & fillOpts = "")
FairDbResultSet::~FairDbResultSet () virtual
Definition at line 53 of file FairDbResult.cxx.
View newest version in sPHENIX GitHub at line 53 of file FairDbResult.cxx
References fStatement, and fTSQLStatement.
FairDbResultSet::FairDbResultSet (const FairDbResultSet &) private
Member Function Documentation
string & FairDbResultSet::AsString (FairDb::DataTypes type) private
Definition at line 165 of file FairDbResult.cxx.
View newest version in sPHENIX GitHub at line 165 of file FairDbResult.cxx
References FairDbFieldType::AsString(), FairDbTableMetaData::ColFieldType(), FairDbTableMetaData::ColName(), FairDbRowStream::CurColNum(), fCurRow, fValString, FairDbFieldType::GetConcept(), FairDbRowStream::IncrementCurCol(), FairDbFieldType::IsCompatible(), FairDbFieldType::IsSmaller(), FairDb::kChar, LoadCurValue(), FairDbRowStream::MetaData(), FairDbRowStream::TableNameTc(), and FairDbFieldType::UndefinedValue().
Referenced by operator>>().
Bool_t FairDbResultSet::CurColExists () const
Definition at line 224 of file FairDbResult.cxx.
View newest version in sPHENIX GitHub at line 224 of file FairDbResult.cxx
References FairDbRowStream::CurColNum(), fCurRow, IsExhausted(), FairDbRowStream::NumCols(), and FairDbRowStream::TableNameTc().
Referenced by CurColString(), and LoadCurValue().
string FairDbResultSet::CurColString () const
Definition at line 251 of file FairDbResult.cxx.
View newest version in sPHENIX GitHub at line 251 of file FairDbResult.cxx
References CurColExists(), FairDbRowStream::CurColNum(), and GetStringFromTSQL().
string FairDbResultSet::CurColValue () const inline
Definition at line 101 of file FairDbResult.h.
View newest version in sPHENIX GitHub at line 101 of file FairDbResult.h
References fValString, and LoadCurValue().
Referenced by FairDbConfigSet::Fill(), and FairDbProxy::ReplaceSeqNoOracle().
UInt_t FairDbResultSet::CurRowNum () const inline
Definition at line 102 of file FairDbResult.h.
View newest version in sPHENIX GitHub at line 102 of file FairDbResult.h
References fCurRow.
Referenced by FairDbValidityRec::Fill().
Bool_t FairDbResultSet::FetchRow ()
Definition at line 261 of file FairDbResult.cxx.
View newest version in sPHENIX GitHub at line 261 of file FairDbResult.cxx
References FairDbRowStream::ClearCurCol(), fCurRow, fExhausted, fTSQLStatement, and IsExhausted().
Referenced by ClassImp(), FairDbSqlValPacket::FairDbSqlValPacket(), and FairDbProxy::ReplaceSeqNoOracle().
UInt_t FairDbResultSet::GetDbNo () const inline
Definition at line 103 of file FairDbResult.h.
View newest version in sPHENIX GitHub at line 103 of file FairDbResult.h
References fDbNo.
Referenced by FairDbValidityRec::Fill().
FairDb::DbTypes FairDbResultSet::GetDBType () const inline
Definition at line 104 of file FairDbResult.h.
View newest version in sPHENIX GitHub at line 104 of file FairDbResult.h
References fDbType.
Referenced by GetStringFromTSQL().
string FairDbResultSet::GetFillOpts () const inline
Definition at line 105 of file FairDbResult.h.
View newest version in sPHENIX GitHub at line 105 of file FairDbResult.h
References fFillOpts.
TString FairDbResultSet::GetStringFromTSQL (Int_t col) const private
Definition at line 270 of file FairDbResult.cxx.
View newest version in sPHENIX GitHub at line 270 of file FairDbResult.cxx
References FairDbRowStream::ColFieldType(), fTSQLStatement, GetDBType(), FairDb::kOracle, and FairDb::kString.
Referenced by CurColString(), LoadCurValue(), and RowAsCsv().
const FairDbTableProxy* FairDbResultSet::GetTableProxy () const inline
Definition at line 106 of file FairDbResult.h.
View newest version in sPHENIX GitHub at line 106 of file FairDbResult.h
References fTableProxy.
Referenced by FairDbValidityRec::Fill().
Bool_t FairDbResultSet::IsBeforeFirst () const inline
IsBeforeFirst not needed for ROOT API, but leave a dummy for now so as not to disturb FairDbResultSet API.
Definition at line 109 of file FairDbResult.h.
View newest version in sPHENIX GitHub at line 109 of file FairDbResult.h
Referenced by ClassImp(), and FairDbProxy::ReplaceSeqNoOracle().
Bool_t FairDbResultSet::IsExhausted () const inline
Definition at line 110 of file FairDbResult.h.
View newest version in sPHENIX GitHub at line 110 of file FairDbResult.h
References fExhausted.
Referenced by ClassImp(), CurColExists(), FairDbSqlValPacket::FairDbSqlValPacket(), FetchRow(), and FairDbProxy::ReplaceSeqNoOracle().
Bool_t FairDbResultSet::LoadCurValue () const private
Definition at line 286 of file FairDbResult.cxx.
View newest version in sPHENIX GitHub at line 286 of file FairDbResult.cxx
References CurColExists(), FairDbRowStream::CurColFieldType(), FairDbRowStream::CurColNum(), fTSQLStatement, fValString, GetStringFromTSQL(), FairDb::kDouble, and FairDb::kFloat.
Referenced by AsString(), and CurColValue().
FairDbResultSet FairDbResultSet::operator= (const FairDbResultSet &) private
FairDbResultSet & FairDbResultSet::operator>> (Bool_t & dest)
Definition at line 101 of file FairDbResult.cxx.
View newest version in sPHENIX GitHub at line 101 of file FairDbResult.cxx
References IN, and FairDb::kBool.
FairDbResultSet & FairDbResultSet::operator>> (Char_t & dest)
Definition at line 106 of file FairDbResult.cxx.
View newest version in sPHENIX GitHub at line 106 of file FairDbResult.cxx
References IN, and FairDb::kChar.
FairDbResultSet & FairDbResultSet::operator>> (Short_t & dest)
Definition at line 111 of file FairDbResult.cxx.
View newest version in sPHENIX GitHub at line 111 of file FairDbResult.cxx
References IN2, and FairDb::kInt.
FairDbResultSet & FairDbResultSet::operator>> (UShort_t & dest)
Definition at line 116 of file FairDbResult.cxx.
View newest version in sPHENIX GitHub at line 116 of file FairDbResult.cxx
References IN3.
FairDbResultSet & FairDbResultSet::operator>> (Int_t & dest)
Definition at line 121 of file FairDbResult.cxx.
View newest version in sPHENIX GitHub at line 121 of file FairDbResult.cxx
References IN2, and FairDb::kInt.
FairDbResultSet & FairDbResultSet::operator>> (UInt_t & dest)
Definition at line 126 of file FairDbResult.cxx.
View newest version in sPHENIX GitHub at line 126 of file FairDbResult.cxx
References IN3.
FairDbResultSet & FairDbResultSet::operator>> (Long_t & dest)
Definition at line 131 of file FairDbResult.cxx.
View newest version in sPHENIX GitHub at line 131 of file FairDbResult.cxx
References IN2, and FairDb::kLong.
FairDbResultSet & FairDbResultSet::operator>> (ULong_t & dest)
Definition at line 136 of file FairDbResult.cxx.
View newest version in sPHENIX GitHub at line 136 of file FairDbResult.cxx
References IN3.
FairDbResultSet & FairDbResultSet::operator>> (Float_t & dest)
Definition at line 141 of file FairDbResult.cxx.
View newest version in sPHENIX GitHub at line 141 of file FairDbResult.cxx
References IN2, and FairDb::kFloat.
FairDbResultSet & FairDbResultSet::operator>> (Double_t & dest)
Definition at line 146 of file FairDbResult.cxx.
View newest version in sPHENIX GitHub at line 146 of file FairDbResult.cxx
References IN2, and FairDb::kDouble.
FairDbResultSet & FairDbResultSet::operator>> (string & dest)
Definition at line 154 of file FairDbResult.cxx.
View newest version in sPHENIX GitHub at line 154 of file FairDbResult.cxx
References AsString(), and FairDb::kString.
FairDbResultSet & FairDbResultSet::operator>> (ValTimeStamp & dest)
Definition at line 159 of file FairDbResult.cxx.
View newest version in sPHENIX GitHub at line 159 of file FairDbResult.cxx
References AsString(), FairDb::kDate, and FairDb::MakeTimeStamp().
void FairDbResultSet::RowAsCsv (string & row) const
Definition at line 323 of file FairDbResult.cxx.
View newest version in sPHENIX GitHub at line 323 of file FairDbResult.cxx
References FairDbTableMetaData::ColFieldConcept(), FairDbTableMetaData::ColFieldType(), FairDbTableMetaData::ColMustDelimit(), fTSQLStatement, GetStringFromTSQL(), FairDbFieldType::GetType(), FairDb::kDouble, FairDb::kFloat, FairDb::kString, FairUtilString::MakePrintable(), FairDbRowStream::MetaData(), FairDbRowStream::NumCols(), and value.
Referenced by FairDbSqlValPacket::FairDbSqlValPacket().
Member Data Documentation
Int_t FairDbResultSet::fCurRow private
Definition at line 135 of file FairDbResult.h.
View newest version in sPHENIX GitHub at line 135 of file FairDbResult.h
Referenced by AsString(), CurColExists(), CurRowNum(), and FetchRow().
UInt_t FairDbResultSet::fDbNo private
Definition at line 136 of file FairDbResult.h.
View newest version in sPHENIX GitHub at line 136 of file FairDbResult.h
Referenced by GetDbNo().
FairDb::DbTypes FairDbResultSet::fDbType private
Definition at line 137 of file FairDbResult.h.
View newest version in sPHENIX GitHub at line 137 of file FairDbResult.h
Referenced by GetDBType().
Bool_t FairDbResultSet::fExhausted private
Definition at line 140 of file FairDbResult.h.
View newest version in sPHENIX GitHub at line 140 of file FairDbResult.h
Referenced by FetchRow(), and IsExhausted().
string FairDbResultSet::fFillOpts private
Definition at line 143 of file FairDbResult.h.
View newest version in sPHENIX GitHub at line 143 of file FairDbResult.h
Referenced by GetFillOpts().
FairDbStatement* FairDbResultSet::fStatement private
Definition at line 138 of file FairDbResult.h.
View newest version in sPHENIX GitHub at line 138 of file FairDbResult.h
Referenced by ~FairDbResultSet().
const FairDbTableProxy* FairDbResultSet::fTableProxy private
Definition at line 141 of file FairDbResult.h.
View newest version in sPHENIX GitHub at line 141 of file FairDbResult.h
Referenced by GetTableProxy().
TSQLStatement* FairDbResultSet::fTSQLStatement private
Definition at line 139 of file FairDbResult.h.
View newest version in sPHENIX GitHub at line 139 of file FairDbResult.h
Referenced by FetchRow(), GetStringFromTSQL(), LoadCurValue(), RowAsCsv(), and ~FairDbResultSet().
string FairDbResultSet::fValString mutable private
Definition at line 142 of file FairDbResult.h.
View newest version in sPHENIX GitHub at line 142 of file FairDbResult.h
Referenced by AsString(), CurColValue(), and LoadCurValue().
The documentation for this class was generated from the following files:
EicRoot/blob/master/dbase/dbInterface/FairDbResult.h
EicRoot/blob/master/dbase/dbInterface/FairDbResult.cxx