EIC Software: CbmRichRing Class Reference
CbmRichRing Class Reference
#include <EicRoot/blob/master/cbmdata/rich/CbmRichRing.h>
Public Member Functions
CbmRichRing ()
CbmRichRing (Float_t x, Float_t y, Float_t r)
virtual ~CbmRichRing ()
void AddHit (UShort_t pHit)
Bool_t RemoveHit (UShort_t hitId)
Int_t GetNofHits () const
UShort_t GetHit (Int_t i) const
void Print ()
void SetAPar (Double_t a)
void SetBPar (Double_t b)
void SetCPar (Double_t c)
void SetDPar (Double_t d)
void SetEPar (Double_t e)
void SetFPar (Double_t f)
void SetCenterX (Float_t x)
void SetCenterY (Float_t y)
void SetRadius (Float_t r)
void SetAaxis (Double_t a)
void SetBaxis (Double_t b)
void SetAaxisCor (Double_t a)
void SetBaxisCor (Double_t b)
void SetXYABPhi (Double_t x, Double_t y, Double_t a, Double_t b, Double_t phi)
void SetPhi (Double_t phi)
void SetTrackID (Int_t track)
void SetDistance (Double_t d)
void SetChi2 (Double_t chi2)
void SetRecFlag (Int_t recflag)
void SetAngle (Double_t angle)
void SetNofHitsOnRing (Int_t onring)
void SetSelectionNN (Double_t selectionNN)
Double_t GetAPar () const
Double_t GetBPar () const
Double_t GetCPar () const
Double_t GetDPar () const
Double_t GetEPar () const
Double_t GetFPar () const
Float_t GetCenterX () const
Float_t GetCenterY () const
Float_t GetRadius () const
Double_t GetAaxis () const
Double_t GetBaxis () const
Double_t GetAaxisCor () const
Double_t GetBaxisCor () const
Double_t GetPhi () const
Double_t GetXF1 () const
Double_t GetYF1 () const
Double_t GetXF2 () const
Double_t GetYF2 () const
Int_t GetTrackID () const
Double_t GetSelectionNN () const
Double_t GetDistance () const
Double_t GetChi2 () const
Double_t GetNDF () const
Float_t GetRadialPosition () const
Double_t GetAngle () const
Int_t GetNofHitsOnRing () const
Double_t GetRadialAngle () const
Int_t GetRecFlag () const
Protected Attributes
Double_t fAPar
Double_t fBPar
Double_t fCPar
Double_t fDPar
Double_t fEPar
Double_t fFPar
Float_t fCenterX
Float_t fCenterY
Float_t fRadius
Double_t fAaxis
Double_t fBaxis
Double_t fAaxisCor
Double_t fBaxisCor
Double_t fPhi
Int_t fTrackID
Double_t fDistance
Double_t fChi2
Double_t fAngle
Int_t fNofHitsOnRing
Double_t fSelectionNN
Int_t fRecFlag
Private Attributes
std::vector< UShort_t > fHitCollection
Detailed Description
Definition at line 17 of file CbmRichRing.h.
View newest version in sPHENIX GitHub at line 17 of file CbmRichRing.h
Constructor & Destructor Documentation
CbmRichRing::CbmRichRing ()
Default constructor
Definition at line 52 of file CbmRichRing.cxx.
View newest version in sPHENIX GitHub at line 52 of file CbmRichRing.cxx
References fHitCollection.
CbmRichRing::CbmRichRing (Float_t x, Float_t y, Float_t r)
Constructor with arguments
Parameters
x x Position of ring center [cm]
y y Position of ring center [cm]
r radius of ring [cm]
Definition at line 83 of file CbmRichRing.cxx.
View newest version in sPHENIX GitHub at line 83 of file CbmRichRing.cxx
References fHitCollection.
CbmRichRing::~CbmRichRing () virtual
Destructor
Definition at line 116 of file CbmRichRing.cxx.
View newest version in sPHENIX GitHub at line 116 of file CbmRichRing.cxx
References fHitCollection.
Member Function Documentation
void CbmRichRing::AddHit (UShort_t pHit) inline
to attach the rich hit to the ring
Definition at line 35 of file CbmRichRing.h.
View newest version in sPHENIX GitHub at line 35 of file CbmRichRing.h
References fHitCollection.
Referenced by CbmRichRingFinderIdeal::DoFind().
Double_t CbmRichRing::GetAaxis () const inline
Definition at line 87 of file CbmRichRing.h.
View newest version in sPHENIX GitHub at line 87 of file CbmRichRing.h
References fAaxis.
Referenced by CbmRichTrainAnnElectrons::DiffElandPi(), CbmRichElectronIdAnn::DoSelect(), and Print().
Double_t CbmRichRing::GetAaxisCor () const inline
Definition at line 89 of file CbmRichRing.h.
View newest version in sPHENIX GitHub at line 89 of file CbmRichRing.h
References fAaxisCor.
Referenced by CbmRichTrainAnnElectrons::DiffElandPi().
Double_t CbmRichRing::GetAngle () const inline
Definition at line 104 of file CbmRichRing.h.
View newest version in sPHENIX GitHub at line 104 of file CbmRichRing.h
References fAngle.
Referenced by Print().
Double_t CbmRichRing::GetAPar () const inline
Accessors
Definition at line 77 of file CbmRichRing.h.
View newest version in sPHENIX GitHub at line 77 of file CbmRichRing.h
References fAPar.
Double_t CbmRichRing::GetBaxis () const inline
Definition at line 88 of file CbmRichRing.h.
View newest version in sPHENIX GitHub at line 88 of file CbmRichRing.h
References fBaxis.
Referenced by CbmRichTrainAnnElectrons::DiffElandPi(), CbmRichElectronIdAnn::DoSelect(), and Print().
Double_t CbmRichRing::GetBaxisCor () const inline
Definition at line 90 of file CbmRichRing.h.
View newest version in sPHENIX GitHub at line 90 of file CbmRichRing.h
References fBaxisCor.
Referenced by CbmRichTrainAnnElectrons::DiffElandPi().
Double_t CbmRichRing::GetBPar () const inline
Definition at line 78 of file CbmRichRing.h.
View newest version in sPHENIX GitHub at line 78 of file CbmRichRing.h
References fBPar.
Float_t CbmRichRing::GetCenterX () const inline
Definition at line 84 of file CbmRichRing.h.
View newest version in sPHENIX GitHub at line 84 of file CbmRichRing.h
References fCenterX.
Referenced by CbmRichRingTrackAssignClosestD::DoAssign(), CbmRichRingTrackAssignIdeal::DoAssign(), CbmRichEventDisplay::DrawCircle(), and Print().
Float_t CbmRichRing::GetCenterY () const inline
Definition at line 85 of file CbmRichRing.h.
View newest version in sPHENIX GitHub at line 85 of file CbmRichRing.h
References fCenterY.
Referenced by CbmRichRingTrackAssignClosestD::DoAssign(), CbmRichRingTrackAssignIdeal::DoAssign(), CbmRichEventDisplay::DrawCircle(), CbmRichEventDisplay::DrawOnePmtPlane(), and Print().
Double_t CbmRichRing::GetChi2 () const inline
Definition at line 101 of file CbmRichRing.h.
View newest version in sPHENIX GitHub at line 101 of file CbmRichRing.h
References fChi2.
Referenced by CbmRichTrainAnnElectrons::DiffElandPi(), CbmRichElectronIdAnn::DoSelect(), and Print().
Double_t CbmRichRing::GetCPar () const inline
Definition at line 79 of file CbmRichRing.h.
View newest version in sPHENIX GitHub at line 79 of file CbmRichRing.h
References fCPar.
Double_t CbmRichRing::GetDistance () const inline
Definition at line 100 of file CbmRichRing.h.
View newest version in sPHENIX GitHub at line 100 of file CbmRichRing.h
References fDistance.
Referenced by CbmRichTrainAnnElectrons::DiffElandPi(), CbmRichElectronIdAnn::DoSelect(), and Print().
Double_t CbmRichRing::GetDPar () const inline
Definition at line 80 of file CbmRichRing.h.
View newest version in sPHENIX GitHub at line 80 of file CbmRichRing.h
References fDPar.
Double_t CbmRichRing::GetEPar () const inline
Definition at line 81 of file CbmRichRing.h.
View newest version in sPHENIX GitHub at line 81 of file CbmRichRing.h
References fEPar.
Double_t CbmRichRing::GetFPar () const inline
Definition at line 82 of file CbmRichRing.h.
View newest version in sPHENIX GitHub at line 82 of file CbmRichRing.h
References fFPar.
UShort_t CbmRichRing::GetHit (Int_t i) const inline
to obtain the rich hit at a particular index
Definition at line 43 of file CbmRichRing.h.
View newest version in sPHENIX GitHub at line 43 of file CbmRichRing.h
References fHitCollection.
Referenced by CbmRichConverter::CopyHitsToRingLight(), and CbmRichMatchRings::Exec().
Double_t CbmRichRing::GetNDF () const inline
Definition at line 102 of file CbmRichRing.h.
View newest version in sPHENIX GitHub at line 102 of file CbmRichRing.h
References GetNofHits().
Referenced by CbmRichTrainAnnElectrons::DiffElandPi(), and CbmRichElectronIdAnn::DoSelect().
Int_t CbmRichRing::GetNofHits () const inline
to obtain the number of hits associated to the ring
Definition at line 41 of file CbmRichRing.h.
View newest version in sPHENIX GitHub at line 41 of file CbmRichRing.h
References fHitCollection.
Referenced by CbmRichConverter::CopyHitsToRingLight(), CbmRichTrainAnnElectrons::DiffElandPi(), CbmRichRingTrackAssignClosestD::DoAssign(), CbmRichRingTrackAssignIdeal::DoAssign(), CbmRichElectronIdAnn::DoSelect(), CbmRichMatchRings::Exec(), GetNDF(), CbmRichUrqmdTest::NofRings(), Print(), and CbmRichGeoTest::RingParameters().
Int_t CbmRichRing::GetNofHitsOnRing () const inline
Definition at line 105 of file CbmRichRing.h.
View newest version in sPHENIX GitHub at line 105 of file CbmRichRing.h
References fNofHitsOnRing.
Referenced by Print().
Double_t CbmRichRing::GetPhi () const inline
Definition at line 91 of file CbmRichRing.h.
View newest version in sPHENIX GitHub at line 91 of file CbmRichRing.h
References fPhi.
Referenced by CbmRichTrainAnnElectrons::DiffElandPi(), CbmRichElectronIdAnn::DoSelect(), and Print().
Double_t CbmRichRing::GetRadialAngle () const
Definition at line 209 of file CbmRichRing.cxx.
View newest version in sPHENIX GitHub at line 209 of file CbmRichRing.cxx
References fCenterX, and fCenterY.
Referenced by CbmRichTrainAnnElectrons::DiffElandPi(), and CbmRichElectronIdAnn::DoSelect().
Float_t CbmRichRing::GetRadialPosition () const
Definition at line 200 of file CbmRichRing.cxx.
View newest version in sPHENIX GitHub at line 200 of file CbmRichRing.cxx
References fCenterX, and fCenterY.
Referenced by CbmRichTrainAnnElectrons::DiffElandPi(), CbmRichElectronIdAnn::DoSelect(), and Print().
Float_t CbmRichRing::GetRadius () const inline
Definition at line 86 of file CbmRichRing.h.
View newest version in sPHENIX GitHub at line 86 of file CbmRichRing.h
References fRadius.
Referenced by CbmRichEventDisplay::DrawCircle(), and Print().
Int_t CbmRichRing::GetRecFlag () const inline
Definition at line 107 of file CbmRichRing.h.
View newest version in sPHENIX GitHub at line 107 of file CbmRichRing.h
References fRecFlag.
Referenced by CbmRichTrainAnnSelect::DiffFakeTrueCircle().
Double_t CbmRichRing::GetSelectionNN () const inline
Definition at line 99 of file CbmRichRing.h.
View newest version in sPHENIX GitHub at line 99 of file CbmRichRing.h
References fSelectionNN.
Int_t CbmRichRing::GetTrackID () const inline
Definition at line 97 of file CbmRichRing.h.
View newest version in sPHENIX GitHub at line 97 of file CbmRichRing.h
References fTrackID.
Double_t CbmRichRing::GetXF1 () const
Definition at line 146 of file CbmRichRing.cxx.
View newest version in sPHENIX GitHub at line 146 of file CbmRichRing.cxx
References c, cos(), fAaxis, fBaxis, fCenterX, and fPhi.
Double_t CbmRichRing::GetXF2 () const
Definition at line 165 of file CbmRichRing.cxx.
View newest version in sPHENIX GitHub at line 165 of file CbmRichRing.cxx
References c, cos(), fAaxis, fBaxis, fCenterX, and fPhi.
Double_t CbmRichRing::GetYF1 () const
Definition at line 154 of file CbmRichRing.cxx.
View newest version in sPHENIX GitHub at line 154 of file CbmRichRing.cxx
References c, fAaxis, fBaxis, fCenterY, and fPhi.
Double_t CbmRichRing::GetYF2 () const
Definition at line 173 of file CbmRichRing.cxx.
View newest version in sPHENIX GitHub at line 173 of file CbmRichRing.cxx
References c, fAaxis, fBaxis, fCenterY, and fPhi.
void CbmRichRing::Print ()
to print ring parameters
Definition at line 184 of file CbmRichRing.cxx.
View newest version in sPHENIX GitHub at line 184 of file CbmRichRing.cxx
References GetAaxis(), GetAngle(), GetBaxis(), GetCenterX(), GetCenterY(), GetChi2(), GetDistance(), GetNofHits(), GetNofHitsOnRing(), GetPhi(), GetRadialPosition(), and GetRadius().
Bool_t CbmRichRing::RemoveHit (UShort_t hitId)
remove hit from ring hitId is the index in the RICH hit array return false if hit is not found in ring
Definition at line 133 of file CbmRichRing.cxx.
View newest version in sPHENIX GitHub at line 133 of file CbmRichRing.cxx
References fHitCollection, and it.
void CbmRichRing::SetAaxis (Double_t a) inline
Definition at line 59 of file CbmRichRing.h.
View newest version in sPHENIX GitHub at line 59 of file CbmRichRing.h
References fAaxis.
Referenced by CbmRichConverter::CopyParamsToRing().
void CbmRichRing::SetAaxisCor (Double_t a) inline
Definition at line 61 of file CbmRichRing.h.
View newest version in sPHENIX GitHub at line 61 of file CbmRichRing.h
References fAaxisCor.
void CbmRichRing::SetAngle (Double_t angle) inline
Definition at line 71 of file CbmRichRing.h.
View newest version in sPHENIX GitHub at line 71 of file CbmRichRing.h
References fAngle.
void CbmRichRing::SetAPar (Double_t a) inline
Modifiers
Definition at line 49 of file CbmRichRing.h.
View newest version in sPHENIX GitHub at line 49 of file CbmRichRing.h
References fAPar.
void CbmRichRing::SetBaxis (Double_t b) inline
Definition at line 60 of file CbmRichRing.h.
View newest version in sPHENIX GitHub at line 60 of file CbmRichRing.h
References fBaxis.
Referenced by CbmRichConverter::CopyParamsToRing().
void CbmRichRing::SetBaxisCor (Double_t b) inline
Definition at line 62 of file CbmRichRing.h.
View newest version in sPHENIX GitHub at line 62 of file CbmRichRing.h
References fBaxisCor.
void CbmRichRing::SetBPar (Double_t b) inline
Definition at line 50 of file CbmRichRing.h.
View newest version in sPHENIX GitHub at line 50 of file CbmRichRing.h
References fBPar.
void CbmRichRing::SetCenterX (Float_t x) inline
Definition at line 56 of file CbmRichRing.h.
View newest version in sPHENIX GitHub at line 56 of file CbmRichRing.h
References fCenterX, and x.
Referenced by CbmRichConverter::CopyParamsToRing().
void CbmRichRing::SetCenterY (Float_t y) inline
Definition at line 57 of file CbmRichRing.h.
View newest version in sPHENIX GitHub at line 57 of file CbmRichRing.h
References fCenterY, and y.
Referenced by CbmRichConverter::CopyParamsToRing().
void CbmRichRing::SetChi2 (Double_t chi2) inline
Definition at line 69 of file CbmRichRing.h.
View newest version in sPHENIX GitHub at line 69 of file CbmRichRing.h
References fChi2.
Referenced by CbmRichConverter::CopyParamsToRing().
void CbmRichRing::SetCPar (Double_t c) inline
Definition at line 51 of file CbmRichRing.h.
View newest version in sPHENIX GitHub at line 51 of file CbmRichRing.h
References c, and fCPar.
void CbmRichRing::SetDistance (Double_t d) inline
Definition at line 68 of file CbmRichRing.h.
View newest version in sPHENIX GitHub at line 68 of file CbmRichRing.h
References d, and fDistance.
Referenced by CbmRichRingTrackAssignClosestD::DoAssign(), and CbmRichRingTrackAssignIdeal::DoAssign().
void CbmRichRing::SetDPar (Double_t d) inline
Definition at line 52 of file CbmRichRing.h.
View newest version in sPHENIX GitHub at line 52 of file CbmRichRing.h
References d, and fDPar.
void CbmRichRing::SetEPar (Double_t e) inline
Definition at line 53 of file CbmRichRing.h.
View newest version in sPHENIX GitHub at line 53 of file CbmRichRing.h
References Acts::UnitConstants::e, and fEPar.
void CbmRichRing::SetFPar (Double_t f) inline
Definition at line 54 of file CbmRichRing.h.
View newest version in sPHENIX GitHub at line 54 of file CbmRichRing.h
References fFPar.
void CbmRichRing::SetNofHitsOnRing (Int_t onring) inline
Definition at line 72 of file CbmRichRing.h.
View newest version in sPHENIX GitHub at line 72 of file CbmRichRing.h
References fNofHitsOnRing.
void CbmRichRing::SetPhi (Double_t phi) inline
Definition at line 66 of file CbmRichRing.h.
View newest version in sPHENIX GitHub at line 66 of file CbmRichRing.h
References fPhi, and phi.
Referenced by CbmRichConverter::CopyParamsToRing().
void CbmRichRing::SetRadius (Float_t r) inline
Definition at line 58 of file CbmRichRing.h.
View newest version in sPHENIX GitHub at line 58 of file CbmRichRing.h
References fRadius.
Referenced by CbmRichConverter::CopyParamsToRing().
void CbmRichRing::SetRecFlag (Int_t recflag) inline
Definition at line 70 of file CbmRichRing.h.
View newest version in sPHENIX GitHub at line 70 of file CbmRichRing.h
References fRecFlag.
Referenced by CbmRichTrainAnnSelect::SetRecFlag().
void CbmRichRing::SetSelectionNN (Double_t selectionNN) inline
number between -1 and 1: -1 = fake ring, 1 = good ring (selection by neural net)
Definition at line 74 of file CbmRichRing.h.
View newest version in sPHENIX GitHub at line 74 of file CbmRichRing.h
References fSelectionNN.
void CbmRichRing::SetTrackID (Int_t track) inline
Definition at line 67 of file CbmRichRing.h.
View newest version in sPHENIX GitHub at line 67 of file CbmRichRing.h
References fTrackID.
Referenced by CbmRichRingTrackAssignClosestD::DoAssign().
void CbmRichRing::SetXYABPhi (Double_t x, Double_t y, Double_t a, Double_t b, Double_t phi)
Definition at line 122 of file CbmRichRing.cxx.
View newest version in sPHENIX GitHub at line 122 of file CbmRichRing.cxx
References fAaxis, fBaxis, fCenterX, fCenterY, fPhi, phi, x, and y.
Member Data Documentation
Double_t CbmRichRing::fAaxis protected
Definition at line 126 of file CbmRichRing.h.
View newest version in sPHENIX GitHub at line 126 of file CbmRichRing.h
Referenced by GetAaxis(), GetXF1(), GetXF2(), GetYF1(), GetYF2(), SetAaxis(), and SetXYABPhi().
Double_t CbmRichRing::fAaxisCor protected
Definition at line 128 of file CbmRichRing.h.
View newest version in sPHENIX GitHub at line 128 of file CbmRichRing.h
Referenced by GetAaxisCor(), and SetAaxisCor().
Double_t CbmRichRing::fAngle protected
Definition at line 137 of file CbmRichRing.h.
View newest version in sPHENIX GitHub at line 137 of file CbmRichRing.h
Referenced by GetAngle(), and SetAngle().
Double_t CbmRichRing::fAPar protected
STL container to hold the hits
Definition at line 115 of file CbmRichRing.h.
View newest version in sPHENIX GitHub at line 115 of file CbmRichRing.h
Referenced by GetAPar(), and SetAPar().
Double_t CbmRichRing::fBaxis protected
Definition at line 127 of file CbmRichRing.h.
View newest version in sPHENIX GitHub at line 127 of file CbmRichRing.h
Referenced by GetBaxis(), GetXF1(), GetXF2(), GetYF1(), GetYF2(), SetBaxis(), and SetXYABPhi().
Double_t CbmRichRing::fBaxisCor protected
Definition at line 129 of file CbmRichRing.h.
View newest version in sPHENIX GitHub at line 129 of file CbmRichRing.h
Referenced by GetBaxisCor(), and SetBaxisCor().
Double_t CbmRichRing::fBPar protected
Definition at line 116 of file CbmRichRing.h.
View newest version in sPHENIX GitHub at line 116 of file CbmRichRing.h
Referenced by GetBPar(), and SetBPar().
Float_t CbmRichRing::fCenterX protected
Definition at line 122 of file CbmRichRing.h.
View newest version in sPHENIX GitHub at line 122 of file CbmRichRing.h
Referenced by GetCenterX(), GetRadialAngle(), GetRadialPosition(), GetXF1(), GetXF2(), SetCenterX(), and SetXYABPhi().
Float_t CbmRichRing::fCenterY protected
Definition at line 123 of file CbmRichRing.h.
View newest version in sPHENIX GitHub at line 123 of file CbmRichRing.h
Referenced by GetCenterY(), GetRadialAngle(), GetRadialPosition(), GetYF1(), GetYF2(), SetCenterY(), and SetXYABPhi().
Double_t CbmRichRing::fChi2 protected
Definition at line 136 of file CbmRichRing.h.
View newest version in sPHENIX GitHub at line 136 of file CbmRichRing.h
Referenced by GetChi2(), and SetChi2().
Double_t CbmRichRing::fCPar protected
Definition at line 117 of file CbmRichRing.h.
View newest version in sPHENIX GitHub at line 117 of file CbmRichRing.h
Referenced by GetCPar(), and SetCPar().
Double_t CbmRichRing::fDistance protected
Definition at line 135 of file CbmRichRing.h.
View newest version in sPHENIX GitHub at line 135 of file CbmRichRing.h
Referenced by GetDistance(), and SetDistance().
Double_t CbmRichRing::fDPar protected
Definition at line 118 of file CbmRichRing.h.
View newest version in sPHENIX GitHub at line 118 of file CbmRichRing.h
Referenced by GetDPar(), and SetDPar().
Double_t CbmRichRing::fEPar protected
Definition at line 119 of file CbmRichRing.h.
View newest version in sPHENIX GitHub at line 119 of file CbmRichRing.h
Referenced by GetEPar(), and SetEPar().
Double_t CbmRichRing::fFPar protected
Definition at line 120 of file CbmRichRing.h.
View newest version in sPHENIX GitHub at line 120 of file CbmRichRing.h
Referenced by GetFPar(), and SetFPar().
std::vector<UShort_t> CbmRichRing::fHitCollection private
Definition at line 111 of file CbmRichRing.h.
View newest version in sPHENIX GitHub at line 111 of file CbmRichRing.h
Referenced by AddHit(), CbmRichRing(), GetHit(), GetNofHits(), RemoveHit(), and ~CbmRichRing().
Int_t CbmRichRing::fNofHitsOnRing protected
Definition at line 138 of file CbmRichRing.h.
View newest version in sPHENIX GitHub at line 138 of file CbmRichRing.h
Referenced by GetNofHitsOnRing(), and SetNofHitsOnRing().
Double_t CbmRichRing::fPhi protected
Definition at line 131 of file CbmRichRing.h.
View newest version in sPHENIX GitHub at line 131 of file CbmRichRing.h
Referenced by GetPhi(), GetXF1(), GetXF2(), GetYF1(), GetYF2(), SetPhi(), and SetXYABPhi().
Float_t CbmRichRing::fRadius protected
Definition at line 124 of file CbmRichRing.h.
View newest version in sPHENIX GitHub at line 124 of file CbmRichRing.h
Referenced by GetRadius(), and SetRadius().
Int_t CbmRichRing::fRecFlag protected
Definition at line 142 of file CbmRichRing.h.
View newest version in sPHENIX GitHub at line 142 of file CbmRichRing.h
Referenced by GetRecFlag(), and SetRecFlag().
Double_t CbmRichRing::fSelectionNN protected
Definition at line 140 of file CbmRichRing.h.
View newest version in sPHENIX GitHub at line 140 of file CbmRichRing.h
Referenced by GetSelectionNN(), and SetSelectionNN().
Int_t CbmRichRing::fTrackID protected
Definition at line 133 of file CbmRichRing.h.
View newest version in sPHENIX GitHub at line 133 of file CbmRichRing.h
Referenced by GetTrackID(), and SetTrackID().
The documentation for this class was generated from the following files:
EicRoot/blob/master/cbmdata/rich/CbmRichRing.h
EicRoot/blob/master/cbmdata/rich/CbmRichRing.cxx