EIC Software: Smear::PerfectID Class Reference
Smear::PerfectID Class Reference
#include <eic-smear/blob/master/include/eicsmear/smear/PerfectID.h>
Public Member Functions
PerfectID (const std::vector< Int_t > &pdg=std::vector< int >())
virtual ~PerfectID ()
virtual PerfectID * Clone (const char *="") const
virtual void Smear (const erhic::VirtualParticle &, ParticleMCS &)
virtual void Print (Option_t *="") const
virtual void Insert (Int_t)
Public Member Functions inherited from Smear::Smearer
virtual ~Smearer ()
Protected Attributes
std::set< Int_t > mPdg
PDG codes to copy. Does not operate on particles with other codes.
Additional Inherited Members
Public Attributes inherited from Smear::Smearer
Acceptance Accept
Detailed Description
Smearer that copies the PDG ID of a particle to a smeared particle with no modification. Use this to represent perfect particle identification performance, or if you don't care about modelling ID performance but want PID copied to the output smeared tree.
Definition at line 27 of file PerfectID.h.
View newest version in sPHENIX GitHub at line 27 of file PerfectID.h
Constructor & Destructor Documentation
Smear::PerfectID::PerfectID (const std::vector< Int_t > & pdg = std::vector<int>())
Constructor
Parameters
pdg [in] An optional list of PDG codes with which the PerfectID works. The ID will not be copied for particles with other PDG codes. If the list is empty the PerfectID operates on all PDG codes.
Definition at line 40 of file PerfectID.cxx.
View newest version in sPHENIX GitHub at line 40 of file PerfectID.cxx
Referenced by Clone().
Smear::PerfectID::~PerfectID () virtual
Destructor.
Definition at line 44 of file PerfectID.cxx.
View newest version in sPHENIX GitHub at line 44 of file PerfectID.cxx
Member Function Documentation
PerfectID * Smear::PerfectID::Clone (const char * = "") const virtual
Returns a new copy of this object. The argument has no effect.
Implements Smear::Smearer.
Definition at line 56 of file PerfectID.cxx.
View newest version in sPHENIX GitHub at line 56 of file PerfectID.cxx
References PerfectID().
void Smear::PerfectID::Insert (Int_t i) virtual
Add a PDG code to the list.
Definition at line 78 of file PerfectID.cxx.
View newest version in sPHENIX GitHub at line 78 of file PerfectID.cxx
References mPdg.
void Smear::PerfectID::Print (Option_t * = "") const virtual
Prints information about this object.
Definition at line 60 of file PerfectID.cxx.
View newest version in sPHENIX GitHub at line 60 of file PerfectID.cxx
References mPdg.
void Smear::PerfectID::Smear (const erhic::VirtualParticle & in, ParticleMCS & out) virtual
Copies the PDG code from the ParticleMC to the ParticleMCS if either the PDG code is in the initialisation list or if the list was empty. Otherwise, does nothing.
Implements Smear::Smearer.
Definition at line 47 of file PerfectID.cxx.
View newest version in sPHENIX GitHub at line 47 of file PerfectID.cxx
References erhic::VirtualParticle::Id(), mPdg, and Smear::ParticleMCS::SetId().
Member Data Documentation
std::set<Int_t> Smear::PerfectID::mPdg protected
PDG codes to copy. Does not operate on particles with other codes.
Definition at line 67 of file PerfectID.h.
View newest version in sPHENIX GitHub at line 67 of file PerfectID.h
Referenced by Insert(), Print(), and Smear().
The documentation for this class was generated from the following files:
eic-smear/blob/master/include/eicsmear/smear/PerfectID.h
eic-smear/blob/master/src/smear/PerfectID.cxx