EIC Software: FW::Generic::ProtoLayerCreatorT< detector_element_t > Class Template Reference
FW::Generic::ProtoLayerCreatorT< detector_element_t > Class Template Reference
#include <fun4all_acts/blob/master/Examples/Detectors/GenericDetector/include/ACTFW/GenericDetector/ProtoLayerCreatorT.hpp>
Classes
struct Config
Public Types
using LayerStore = std::vector< std::shared_ptr< detector_element_t >>
using DetectorStore = std::vector< LayerStore >
Public Member Functions
ProtoLayerCreatorT (const Config &glbConfig, std::unique_ptr< const Acts::Logger > logger=Acts::getDefaultLogger("ProtoLayerCreatorT", Acts::Logging::INFO))
std::vector< ProtoLayerSurfaces > negativeProtoLayers (const Acts::GeometryContext &gctx, DetectorStore &detectorStore) const
construct the negative side layers
std::vector< ProtoLayerSurfaces > centralProtoLayers (const Acts::GeometryContext &gctx, DetectorStore &detectorStore) const
construct the central layers
std::vector< ProtoLayerSurfaces > positiveProtoLayers (const Acts::GeometryContext &gctx, DetectorStore &detectorStore) const
construct the positive side layers
Private Member Functions
std::vector< ProtoLayerSurfaces > createProtoLayers (const Acts::GeometryContext &gctx, DetectorStore &detectorStore, int side) const
private helper method to create the proto layers on the left respectively right side
const Acts::Logger & logger () const
Private access to the logging instance.
Private Attributes
Config m_cfg
Configuration member.
std::unique_ptr< const
Acts::Logger > m_logger
the logging instance
Detailed Description
template<typename detector_element_t>
class FW::Generic::ProtoLayerCreatorT< detector_element_t >
The ProtoLayerCreatorT is the first setp in creating a geometry from code input, it creates the ProtoLayer and returns the created detector elements for the DetectorStore emulation
Definition at line 62 of file ProtoLayerCreatorT.hpp.
View newest version in sPHENIX GitHub at line 62 of file ProtoLayerCreatorT.hpp
Member Typedef Documentation
template<typename detector_element_t > using FW::Generic::ProtoLayerCreatorT< detector_element_t >::DetectorStore = std::vector<LayerStore>
Definition at line 66 of file ProtoLayerCreatorT.hpp.
View newest version in sPHENIX GitHub at line 66 of file ProtoLayerCreatorT.hpp
template<typename detector_element_t > using FW::Generic::ProtoLayerCreatorT< detector_element_t >::LayerStore = std::vector<std::shared_ptr<detector_element_t>>
Definition at line 64 of file ProtoLayerCreatorT.hpp.
View newest version in sPHENIX GitHub at line 64 of file ProtoLayerCreatorT.hpp
Constructor & Destructor Documentation
template<typename detector_element_t > FW::Generic::ProtoLayerCreatorT< detector_element_t >::ProtoLayerCreatorT (const Config & glbConfig, std::unique_ptr< const Acts::Logger > logger = Acts::getDefaultLogger("ProtoLayerCreatorT< detector_element_t >", Acts::Logging::INFO))
Constructor
Parameters
glbConfig is the configuration class
logger is the logging class for screen output
Definition at line 394 of file ProtoLayerCreatorT.hpp.
View newest version in sPHENIX GitHub at line 394 of file ProtoLayerCreatorT.hpp
Member Function Documentation
template<typename detector_element_t > std::vector< ProtoLayerSurfaces > FW::Generic::ProtoLayerCreatorT< detector_element_t >::centralProtoLayers (const Acts::GeometryContext & gctx, DetectorStore & detectorStore) const
construct the central layers
Parameters
gctx The geometry context for this construction call
detectorStore The reference store for the detector elements
Returns
the protolayers and surfaces on the central detector side
Definition at line 201 of file ProtoLayerCreatorT.hpp.
View newest version in sPHENIX GitHub at line 201 of file ProtoLayerCreatorT.hpp
References ACTS_DEBUG, ACTS_VERBOSE, ACTS_WARNING, boost::const_pointer_cast(), cos(), Acts::ProtoLayer::envR, Acts::ProtoLayer::envZ, Acts::Test::moduleBounds, and phi.
template<typename detector_element_t > std::vector< ProtoLayerSurfaces > FW::Generic::ProtoLayerCreatorT< detector_element_t >::createProtoLayers (const Acts::GeometryContext & gctx, DetectorStore & detectorStore, int side) const private
private helper method to create the proto layers on the left respectively right side
Parameters
gctx The geometry context for this construction call
detectorStore The reference store for the detector elements
side is the indiciator whether to build on negative/positive
Returns
the protolayers and surfaces on the neg/pos detector side
this is the loop over th elayer positions
some preparation work
Definition at line 401 of file ProtoLayerCreatorT.hpp.
View newest version in sPHENIX GitHub at line 401 of file ProtoLayerCreatorT.hpp
References ACTS_DEBUG, ACTS_VERBOSE, boost::const_pointer_cast(), cos(), Acts::ProtoLayer::envR, Acts::ProtoLayer::envZ, Acts::Test::moduleBounds, and phi.
template<typename detector_element_t > const Acts::Logger& FW::Generic::ProtoLayerCreatorT< detector_element_t >::logger () const inline private
Private access to the logging instance.
Definition at line 196 of file ProtoLayerCreatorT.hpp.
View newest version in sPHENIX GitHub at line 196 of file ProtoLayerCreatorT.hpp
References FW::Generic::ProtoLayerCreatorT< detector_element_t >::m_logger.
template<typename detector_element_t > std::vector< ProtoLayerSurfaces > FW::Generic::ProtoLayerCreatorT< detector_element_t >::negativeProtoLayers (const Acts::GeometryContext & gctx, DetectorStore & detectorStore) const
construct the negative side layers
Parameters
gctx The geometry context for this construction call
detectorStore The reference store for the detector elements
Returns
the protolayers and surfaces on the negative detector side
Definition at line 381 of file ProtoLayerCreatorT.hpp.
View newest version in sPHENIX GitHub at line 381 of file ProtoLayerCreatorT.hpp
template<typename detector_element_t > std::vector< ProtoLayerSurfaces > FW::Generic::ProtoLayerCreatorT< detector_element_t >::positiveProtoLayers (const Acts::GeometryContext & gctx, DetectorStore & detectorStore) const
construct the positive side layers
Parameters
gctx The geometry context for this construction call
detectorStore The reference store for the detector elements
Returns
the protolayers and surfaces on the positive detector side
Definition at line 388 of file ProtoLayerCreatorT.hpp.
View newest version in sPHENIX GitHub at line 388 of file ProtoLayerCreatorT.hpp
Member Data Documentation
template<typename detector_element_t > Config FW::Generic::ProtoLayerCreatorT< detector_element_t >::m_cfg private
Configuration member.
Definition at line 190 of file ProtoLayerCreatorT.hpp.
View newest version in sPHENIX GitHub at line 190 of file ProtoLayerCreatorT.hpp
template<typename detector_element_t > std::unique_ptr<const Acts::Logger> FW::Generic::ProtoLayerCreatorT< detector_element_t >::m_logger private
the logging instance
Definition at line 193 of file ProtoLayerCreatorT.hpp.
View newest version in sPHENIX GitHub at line 193 of file ProtoLayerCreatorT.hpp
Referenced by FW::Generic::ProtoLayerCreatorT< detector_element_t >::logger().
The documentation for this class was generated from the following file:
fun4all_acts/blob/master/Examples/Detectors/GenericDetector/include/ACTFW/GenericDetector/ProtoLayerCreatorT.hpp