EIC Software: CbmRichRingFitterEllipseBase Class Reference
CbmRichRingFitterEllipseBase Class Reference
Base class for concrete ellipse fitting algorithms. Each derived class must implement the method DoFit.
#include <EicRoot/blob/master/rich/fitter/CbmRichRingFitterEllipseBase.h>
Public Member Functions
CbmRichRingFitterEllipseBase ()
Default constructor.
virtual ~CbmRichRingFitterEllipseBase ()
Destructor.
Public Member Functions inherited from CbmRichRingFitterBase
CbmRichRingFitterBase ()
Default constructor.
virtual ~CbmRichRingFitterBase ()
Destructor.
virtual void DoFit (CbmRichRingLight *ring)=0
Abstract method DoFit. To be implemented in the concrete class. Perform a fit to the hits attached to the ring by a ring finder. Fill the ring parameters member variables.
Protected Member Functions
virtual void CalcChi2 (CbmRichRingLight *ring)
Calculate chi2 of the ellipse fit.
virtual void CalcChi2 (double A, double B, double C, double D, double E, double F, CbmRichRingLight *ring)
Calculate chi2 of the ellipse fitting using parameters of 2D curve.
Additional Inherited Members
Static Protected Attributes inherited from CbmRichRingFitterBase
static const int MAX_NOF_HITS_IN_RING = 400
Detailed Description
Base class for concrete ellipse fitting algorithms. Each derived class must implement the method DoFit.
Author
Semen Lebedev s.leb.nosp@m.edev.nosp@m.@gsi..nosp@m.de
Date
2011
Definition at line 25 of file CbmRichRingFitterEllipseBase.h.
View newest version in sPHENIX GitHub at line 25 of file CbmRichRingFitterEllipseBase.h
Constructor & Destructor Documentation
CbmRichRingFitterEllipseBase::CbmRichRingFitterEllipseBase () inline
Default constructor.
Definition at line 30 of file CbmRichRingFitterEllipseBase.h.
View newest version in sPHENIX GitHub at line 30 of file CbmRichRingFitterEllipseBase.h
virtual CbmRichRingFitterEllipseBase::~CbmRichRingFitterEllipseBase () inline virtual
Destructor.
Definition at line 35 of file CbmRichRingFitterEllipseBase.h.
View newest version in sPHENIX GitHub at line 35 of file CbmRichRingFitterEllipseBase.h
Member Function Documentation
virtual void CbmRichRingFitterEllipseBase::CalcChi2 (CbmRichRingLight * ring) inline protected virtual
Calculate chi2 of the ellipse fit.
Parameters
[in,out] ring Fitted RICH ring with ellipse fitter.
Reimplemented from CbmRichRingFitterBase.
Definition at line 43 of file CbmRichRingFitterEllipseBase.h.
View newest version in sPHENIX GitHub at line 43 of file CbmRichRingFitterEllipseBase.h
References CbmRichHitLight::fX, CbmRichHitLight::fY, CbmRichRingLight::GetAaxis(), CbmRichRingLight::GetBaxis(), CbmRichRingLight::GetHit(), CbmRichRingLight::GetNofHits(), CbmRichRingLight::GetXF1(), CbmRichRingLight::GetXF2(), CbmRichRingLight::GetYF1(), CbmRichRingLight::GetYF2(), CbmRichRingLight::SetChi2(), x, and y.
Referenced by CbmRichRingFitterEllipseTau::DoFit(), CbmRichRingFitterEllipseMinuit::DoFit(), and CbmRichRingFitterEllipseTau::TransformEllipse().
virtual void CbmRichRingFitterEllipseBase::CalcChi2 (double A, double B, double C, double D, double E, double F, CbmRichRingLight * ring) inline protected virtual
Calculate chi2 of the ellipse fitting using parameters of 2D curve.
Parameters
[in] A A parameter of curve.
[in] B B parameter of curve.
[in] C C parameter of curve.
[in] D D parameter of curve.
[in] E E parameter of curve.
[in] F F parameter of curve.
[in] ring Fitted RICH ring with ellipse fitter.
Definition at line 90 of file CbmRichRingFitterEllipseBase.h.
View newest version in sPHENIX GitHub at line 90 of file CbmRichRingFitterEllipseBase.h
References CbmRichHitLight::fX, CbmRichHitLight::fY, CbmRichRingLight::GetHit(), CbmRichRingLight::GetNofHits(), CbmRichRingLight::SetChi2(), x, and y.
The documentation for this class was generated from the following file:
EicRoot/blob/master/rich/fitter/CbmRichRingFitterEllipseBase.h