EIC Software: EtmVacuumChamber Class Reference
EtmVacuumChamber Class Reference abstract
#include <EicToyModel/blob/master/include/EtmVacuumChamber.h>
Public Member Functions
EtmVacuumChamber (void)
~EtmVacuumChamber ()
void DrawMe (void)
void SetHadronBeamPipeOpening (double value)
double GetHadronBeamPipeOpening (void) const
double GetRadialSize (double z, double phi)
TGeoManager * GetWorld (void) const
void CheckGeometry (bool force=false)
void Export (const char *fname)
virtual bool ConfigurableCrossingAngle (void) const =0
virtual double FixedCrossingAngle (void) const
bool CrossingAngleResetPossible (double value) const
G4VSolid * CutThisSolid (G4VSolid *solid, double dz)
void StoreGDMLdump (void)
*, const std::vector<TVector2> &polygon*/);
Protected Member Functions
virtual void CreateGeometry (void)=0
Protected Attributes
TGeoManager * mTGeoModel
double mHadronBeamPipeOpening
double mActualCrossingAngle
Private Member Functions
void CreateWorld (void)
void CreateMedium (const char *name, double A, double Z, double density)
Private Attributes
bool mStandaloneMode
void * g4Factory
Detailed Description
Definition at line 17 of file EtmVacuumChamber.h.
View newest version in sPHENIX GitHub at line 17 of file EtmVacuumChamber.h
Constructor & Destructor Documentation
EtmVacuumChamber::EtmVacuumChamber (void)
Definition at line 28 of file EtmVacuumChamber.cc.
View newest version in sPHENIX GitHub at line 28 of file EtmVacuumChamber.cc
EtmVacuumChamber::~EtmVacuumChamber () inline
Definition at line 20 of file EtmVacuumChamber.h.
View newest version in sPHENIX GitHub at line 20 of file EtmVacuumChamber.h
Member Function Documentation
void EtmVacuumChamber::CheckGeometry (bool force = false)
Definition at line 103 of file EtmVacuumChamber.cc.
View newest version in sPHENIX GitHub at line 103 of file EtmVacuumChamber.cc
References CreateGeometry(), CreateWorld(), EicToyModel::GetCrossingAngle(), EicToyModel::Instance(), and mActualCrossingAngle.
Referenced by EicToyModel::BuildVacuumChamber(), CutThisSolid(), DrawMe(), Export(), GetRadialSize(), EicToyModel::ip(), EicToyModel::RebuildEverything(), and StoreGDMLdump().
virtual bool EtmVacuumChamber::ConfigurableCrossingAngle (void) const pure virtual
Implemented in vc2020_03_20.
Referenced by CrossingAngleResetPossible().
virtual void EtmVacuumChamber::CreateGeometry (void) protected pure virtual
Implemented in vc2020_03_20.
Referenced by CheckGeometry().
void EtmVacuumChamber::CreateMedium (const char * name, double A, double Z, double density) private
Definition at line 37 of file EtmVacuumChamber.cc.
View newest version in sPHENIX GitHub at line 37 of file EtmVacuumChamber.cc
Referenced by CreateWorld().
void EtmVacuumChamber::CreateWorld (void) private
Definition at line 47 of file EtmVacuumChamber.cc.
View newest version in sPHENIX GitHub at line 47 of file EtmVacuumChamber.cc
References _ACCELERATOR_VACUUM_, _UNIVERSE_VACUUM_, CreateMedium(), eic, EicToyModel::Instance(), mStandaloneMode, mTGeoModel, and Acts::Test::world.
Referenced by CheckGeometry().
bool EtmVacuumChamber::CrossingAngleResetPossible (double value) const
Definition at line 90 of file EtmVacuumChamber.cc.
View newest version in sPHENIX GitHub at line 90 of file EtmVacuumChamber.cc
References ConfigurableCrossingAngle(), FixedCrossingAngle(), mStandaloneMode, and mTGeoModel.
Referenced by EicToyModel::DefineVacuumChamber(), and EicToyModel::SetCrossingAngle().
G4VSolid * EtmVacuumChamber::CutThisSolid (G4VSolid * solid, double dz)
Definition at line 238 of file EtmVacuumChamber.cc.
View newest version in sPHENIX GitHub at line 238 of file EtmVacuumChamber.cc
References CheckGeometry(), g4Factory, and etm::solid.
void EtmVacuumChamber::DrawMe (void)
Definition at line 167 of file EtmVacuumChamber.cc.
View newest version in sPHENIX GitHub at line 167 of file EtmVacuumChamber.cc
References CheckGeometry(), etm::cm, eic, GetRadialSize(), EicToyModel::Instance(), EicToyModel::kHorizontal, M_PI, and Acts::Test::step().
Referenced by EicToyModel::DrawMe().
void EtmVacuumChamber::Export (const char * fname)
Definition at line 120 of file EtmVacuumChamber.cc.
View newest version in sPHENIX GitHub at line 120 of file EtmVacuumChamber.cc
References CheckGeometry(), mStandaloneMode, and mTGeoModel.
Referenced by EicToyModel::ExportVacuumChamber().
virtual double EtmVacuumChamber::FixedCrossingAngle (void) const inline virtual
Definition at line 37 of file EtmVacuumChamber.h.
View newest version in sPHENIX GitHub at line 37 of file EtmVacuumChamber.h
Referenced by CrossingAngleResetPossible().
double EtmVacuumChamber::GetHadronBeamPipeOpening (void) const inline
Definition at line 25 of file EtmVacuumChamber.h.
View newest version in sPHENIX GitHub at line 25 of file EtmVacuumChamber.h
References mHadronBeamPipeOpening.
double EtmVacuumChamber::GetRadialSize (double z, double phi)
Definition at line 199 of file EtmVacuumChamber.cc.
View newest version in sPHENIX GitHub at line 199 of file EtmVacuumChamber.cc
References _ACCELERATOR_VACUUM_, _UNIVERSE_VACUUM_, CheckGeometry(), cos(), material(), and mTGeoModel.
Referenced by DrawMe().
TGeoManager* EtmVacuumChamber::GetWorld (void) const inline
Definition at line 29 of file EtmVacuumChamber.h.
View newest version in sPHENIX GitHub at line 29 of file EtmVacuumChamber.h
References mTGeoModel.
Referenced by vc2020_03_20::CreateGeometry(), and EicToyModel::Export().
void EtmVacuumChamber::SetHadronBeamPipeOpening (double value) inline
Definition at line 24 of file EtmVacuumChamber.h.
View newest version in sPHENIX GitHub at line 24 of file EtmVacuumChamber.h
References mHadronBeamPipeOpening, and value.
void EtmVacuumChamber::StoreGDMLdump (void)
*, const std::vector<TVector2> &polygon*/);
Definition at line 133 of file EtmVacuumChamber.cc.
View newest version in sPHENIX GitHub at line 133 of file EtmVacuumChamber.cc
References CheckGeometry(), mStandaloneMode, and mTGeoModel.
Referenced by EicToyModel::Export().
Member Data Documentation
void* EtmVacuumChamber::g4Factory private
Definition at line 67 of file EtmVacuumChamber.h.
View newest version in sPHENIX GitHub at line 67 of file EtmVacuumChamber.h
Referenced by CutThisSolid().
double EtmVacuumChamber::mActualCrossingAngle protected
Definition at line 55 of file EtmVacuumChamber.h.
View newest version in sPHENIX GitHub at line 55 of file EtmVacuumChamber.h
Referenced by CheckGeometry().
double EtmVacuumChamber::mHadronBeamPipeOpening protected
Definition at line 53 of file EtmVacuumChamber.h.
View newest version in sPHENIX GitHub at line 53 of file EtmVacuumChamber.h
Referenced by vc2020_03_20::CreateGeometry(), GetHadronBeamPipeOpening(), SetHadronBeamPipeOpening(), and vc2020_03_20::vc2020_03_20().
bool EtmVacuumChamber::mStandaloneMode private
Definition at line 63 of file EtmVacuumChamber.h.
View newest version in sPHENIX GitHub at line 63 of file EtmVacuumChamber.h
Referenced by CreateWorld(), CrossingAngleResetPossible(), Export(), and StoreGDMLdump().
TGeoManager* EtmVacuumChamber::mTGeoModel protected
Definition at line 50 of file EtmVacuumChamber.h.
View newest version in sPHENIX GitHub at line 50 of file EtmVacuumChamber.h
Referenced by CreateWorld(), CrossingAngleResetPossible(), Export(), GetRadialSize(), GetWorld(), and StoreGDMLdump().
The documentation for this class was generated from the following files:
EicToyModel/blob/master/include/EtmVacuumChamber.h
EicToyModel/blob/master/source/EtmVacuumChamber.cc