EIC Software: FW::ResPlotTool Class Reference
FW::ResPlotTool Class Reference
#include <fun4all_acts/blob/master/Examples/Framework/include/ACTFW/Validation/ResPlotTool.hpp>
Classes
struct Config
Nested configuration struct.
struct ResPlotCache
Nested Cache struct.
Public Member Functions
ResPlotTool (const Config &cfg, Acts::Logging::Level lvl)
void book (ResPlotCache &resPlotCache) const
book the histograms
void fill (ResPlotCache &resPlotCache, const Acts::GeometryContext &gctx, const ActsFatras::Particle &truthParticle, const Acts::BoundParameters &fittedParamters) const
fill the histograms
void refinement (ResPlotCache &resPlotCache) const
extract the details of the residual/pull plots and fill details into separate histograms
void write (const ResPlotCache &resPlotCache) const
write the histograms to output file
void clear (ResPlotCache &resPlotCache) const
delele the histograms
Private Types
using ParVector_t = typename Acts::BoundParameters::ParVector_t
Private Member Functions
const Acts::Logger & logger () const
The logger.
Private Attributes
Config m_cfg
The config class.
std::unique_ptr< const
Acts::Logger > m_logger
The logging instance.
Detailed Description
Definition at line 26 of file ResPlotTool.hpp.
View newest version in sPHENIX GitHub at line 26 of file ResPlotTool.hpp
Member Typedef Documentation
using FW::ResPlotTool::ParVector_t = typename Acts::BoundParameters::ParVector_t private
Definition at line 27 of file ResPlotTool.hpp.
View newest version in sPHENIX GitHub at line 27 of file ResPlotTool.hpp
Constructor & Destructor Documentation
FW::ResPlotTool::ResPlotTool (const Config & cfg, Acts::Logging::Level lvl)
Constructor
Parameters
cfg Configuration struct
level Message level declaration
Definition at line 14 of file ResPlotTool.cpp.
View newest version in sPHENIX GitHub at line 14 of file ResPlotTool.cpp
Member Function Documentation
void FW::ResPlotTool::book (ResPlotTool::ResPlotCache & resPlotCache) const
book the histograms
Parameters
resPlotCache the cache for residual/pull histograms
Definition at line 18 of file ResPlotTool.cpp.
View newest version in sPHENIX GitHub at line 18 of file ResPlotTool.cpp
References ACTS_DEBUG, FW::PlotHelpers::bookHisto(), Acts::eBoundParametersSize, FW::ResPlotTool::ResPlotCache::pull, FW::ResPlotTool::ResPlotCache::pull_vs_eta, FW::ResPlotTool::ResPlotCache::pull_vs_pT, FW::ResPlotTool::ResPlotCache::pullmean_vs_eta, FW::ResPlotTool::ResPlotCache::pullmean_vs_pT, FW::ResPlotTool::ResPlotCache::pullwidth_vs_eta, FW::ResPlotTool::ResPlotCache::pullwidth_vs_pT, FW::ResPlotTool::ResPlotCache::res, FW::ResPlotTool::ResPlotCache::res_vs_eta, FW::ResPlotTool::ResPlotCache::res_vs_pT, FW::ResPlotTool::ResPlotCache::resmean_vs_eta, FW::ResPlotTool::ResPlotCache::resmean_vs_pT, FW::ResPlotTool::ResPlotCache::reswidth_vs_eta, and FW::ResPlotTool::ResPlotCache::reswidth_vs_pT.
Referenced by FW::TrackFitterPerformanceWriter::TrackFitterPerformanceWriter().
void FW::ResPlotTool::clear (ResPlotCache & resPlotCache) const
delele the histograms
Parameters
resPlotCache the cache object for residual/pull histograms
Definition at line 91 of file ResPlotTool.cpp.
View newest version in sPHENIX GitHub at line 91 of file ResPlotTool.cpp
References ACTS_DEBUG, Acts::eBoundParametersSize, FW::ResPlotTool::ResPlotCache::pull, FW::ResPlotTool::ResPlotCache::pull_vs_eta, FW::ResPlotTool::ResPlotCache::pull_vs_pT, FW::ResPlotTool::ResPlotCache::pullmean_vs_eta, FW::ResPlotTool::ResPlotCache::pullmean_vs_pT, FW::ResPlotTool::ResPlotCache::pullwidth_vs_eta, FW::ResPlotTool::ResPlotCache::pullwidth_vs_pT, FW::ResPlotTool::ResPlotCache::res, FW::ResPlotTool::ResPlotCache::res_vs_eta, FW::ResPlotTool::ResPlotCache::res_vs_pT, FW::ResPlotTool::ResPlotCache::resmean_vs_eta, FW::ResPlotTool::ResPlotCache::resmean_vs_pT, FW::ResPlotTool::ResPlotCache::reswidth_vs_eta, and FW::ResPlotTool::ResPlotCache::reswidth_vs_pT.
void FW::ResPlotTool::fill (ResPlotTool::ResPlotCache & resPlotCache, const Acts::GeometryContext & gctx, const ActsFatras::Particle & truthParticle, const Acts::BoundParameters & fittedParamters) const
fill the histograms
Parameters
resPlotCache the cache for residual/pull histograms
gctx the geometry context
truthParticle the truth particle
fittedParamters the fitted parameters at perigee surface
Definition at line 134 of file ResPlotTool.cpp.
View newest version in sPHENIX GitHub at line 134 of file ResPlotTool.cpp
References ActsFatras::Particle::absMomentum(), ACTS_WARNING, ActsFatras::Particle::charge(), Acts::SingleTrackParameters< ChargePolicy >::covariance(), Acts::eBoundParametersSize, Acts::eLOC_D0, Acts::eLOC_Z0, Acts::ePHI, Acts::eQOP, Acts::eT, Acts::VectorHelpers::eta(), Acts::eTHETA, FW::PlotHelpers::fillHisto(), Acts::SingleTrackParameters< ChargePolicy >::parameters(), Acts::VectorHelpers::perp(), Acts::VectorHelpers::phi(), phi, ActsFatras::Particle::position(), FW::ResPlotTool::ResPlotCache::pull, FW::ResPlotTool::ResPlotCache::pull_vs_eta, FW::ResPlotTool::ResPlotCache::pull_vs_pT, Acts::SingleBoundTrackParameters< ChargePolicy >::referenceSurface(), FW::ResPlotTool::ResPlotCache::res, FW::ResPlotTool::ResPlotCache::res_vs_eta, FW::ResPlotTool::ResPlotCache::res_vs_pT, ds::theta, Acts::VectorHelpers::theta(), ActsFatras::Particle::time(), ActsFatras::Particle::transverseMomentum(), and ActsFatras::Particle::unitDirection().
const Acts::Logger& FW::ResPlotTool::logger () const inline private
The logger.
Definition at line 116 of file ResPlotTool.hpp.
View newest version in sPHENIX GitHub at line 116 of file ResPlotTool.hpp
References m_logger.
void FW::ResPlotTool::refinement (ResPlotTool::ResPlotCache & resPlotCache) const
extract the details of the residual/pull plots and fill details into separate histograms
Parameters
resPlotCache the cache object for residual/pull histograms
Definition at line 195 of file ResPlotTool.cpp.
View newest version in sPHENIX GitHub at line 195 of file ResPlotTool.cpp
References FW::PlotHelpers::anaHisto(), Acts::eBoundParametersSize, FW::PlotHelpers::Binning::nBins, FW::ResPlotTool::ResPlotCache::pull_vs_eta, FW::ResPlotTool::ResPlotCache::pull_vs_pT, FW::ResPlotTool::ResPlotCache::pullmean_vs_eta, FW::ResPlotTool::ResPlotCache::pullmean_vs_pT, FW::ResPlotTool::ResPlotCache::pullwidth_vs_eta, FW::ResPlotTool::ResPlotCache::pullwidth_vs_pT, FW::ResPlotTool::ResPlotCache::res_vs_eta, FW::ResPlotTool::ResPlotCache::res_vs_pT, FW::ResPlotTool::ResPlotCache::resmean_vs_eta, FW::ResPlotTool::ResPlotCache::resmean_vs_pT, FW::ResPlotTool::ResPlotCache::reswidth_vs_eta, and FW::ResPlotTool::ResPlotCache::reswidth_vs_pT.
void FW::ResPlotTool::write (const ResPlotCache & resPlotCache) const
write the histograms to output file
Parameters
resPlotCache the cache object for residual/pull histograms
Definition at line 112 of file ResPlotTool.cpp.
View newest version in sPHENIX GitHub at line 112 of file ResPlotTool.cpp
References ACTS_DEBUG, Acts::eBoundParametersSize, FW::ResPlotTool::ResPlotCache::pull, FW::ResPlotTool::ResPlotCache::pull_vs_eta, FW::ResPlotTool::ResPlotCache::pull_vs_pT, FW::ResPlotTool::ResPlotCache::pullmean_vs_eta, FW::ResPlotTool::ResPlotCache::pullmean_vs_pT, FW::ResPlotTool::ResPlotCache::pullwidth_vs_eta, FW::ResPlotTool::ResPlotCache::pullwidth_vs_pT, FW::ResPlotTool::ResPlotCache::res, FW::ResPlotTool::ResPlotCache::res_vs_eta, FW::ResPlotTool::ResPlotCache::res_vs_pT, FW::ResPlotTool::ResPlotCache::resmean_vs_eta, FW::ResPlotTool::ResPlotCache::resmean_vs_pT, FW::ResPlotTool::ResPlotCache::reswidth_vs_eta, and FW::ResPlotTool::ResPlotCache::reswidth_vs_pT.
Member Data Documentation
Config FW::ResPlotTool::m_cfg private
The config class.
Definition at line 112 of file ResPlotTool.hpp.
View newest version in sPHENIX GitHub at line 112 of file ResPlotTool.hpp
std::unique_ptr<const Acts::Logger> FW::ResPlotTool::m_logger private
The logging instance.
Definition at line 113 of file ResPlotTool.hpp.
View newest version in sPHENIX GitHub at line 113 of file ResPlotTool.hpp
Referenced by logger().
The documentation for this class was generated from the following files:
fun4all_acts/blob/master/Examples/Framework/include/ACTFW/Validation/ResPlotTool.hpp
fun4all_acts/blob/master/Examples/Framework/src/Validation/ResPlotTool.cpp