EIC Software: NNfunction Class Reference
NNfunction Class Reference
#include <EicRoot/blob/master/rich/standalone/algorithm/NNfunction.h>
Public Member Functions
NNfunction ()
~NNfunction ()
double Value (int index, double in0, double in1, double in2, double in3, double in4, double in5)
double Value (int index, double *input)
Private Member Functions
double neuron0x85fe910 ()
double neuron0x85feae8 ()
double neuron0x860cfa8 ()
double neuron0x860d180 ()
double neuron0x860d358 ()
double neuron0x860d530 ()
double input0x860d840 ()
double neuron0x860d840 ()
double input0x860dab8 ()
double neuron0x860dab8 ()
double input0x860dda0 ()
double neuron0x860dda0 ()
double input0x860e110 ()
double neuron0x860e110 ()
double input0x860e3b0 ()
double neuron0x860e3b0 ()
double input0x860e698 ()
double neuron0x860e698 ()
double synapse0x85fe830 ()
double synapse0x860d9f0 ()
double synapse0x860da18 ()
double synapse0x860da40 ()
double synapse0x860da68 ()
double synapse0x860da90 ()
double synapse0x860dcb0 ()
double synapse0x860dcd8 ()
double synapse0x860dd00 ()
double synapse0x860dd28 ()
double synapse0x860dd50 ()
double synapse0x860dd78 ()
double synapse0x860df98 ()
double synapse0x860dfc0 ()
double synapse0x860dfe8 ()
double synapse0x860e010 ()
double synapse0x860e038 ()
double synapse0x860e0e8 ()
double synapse0x860e2c0 ()
double synapse0x860e2e8 ()
double synapse0x860e310 ()
double synapse0x860e338 ()
double synapse0x860e360 ()
double synapse0x860e388 ()
double synapse0x860e5a8 ()
double synapse0x860e5d0 ()
double synapse0x860e5f8 ()
double synapse0x860e620 ()
double synapse0x860e648 ()
double synapse0x860e670 ()
double synapse0x860e798 ()
double synapse0x860e7c0 ()
double synapse0x860e7e8 ()
double synapse0x860e060 ()
double synapse0x860e088 ()
Private Attributes
double input0
double input1
double input2
double input3
double input4
double input5
Detailed Description
Definition at line 4 of file NNfunction.h.
View newest version in sPHENIX GitHub at line 4 of file NNfunction.h
Constructor & Destructor Documentation
NNfunction::NNfunction () inline
Definition at line 6 of file NNfunction.h.
View newest version in sPHENIX GitHub at line 6 of file NNfunction.h
NNfunction::~NNfunction () inline
Definition at line 7 of file NNfunction.h.
View newest version in sPHENIX GitHub at line 7 of file NNfunction.h
Member Function Documentation
double NNfunction::input0x860d840 () private
Definition at line 58 of file NNfunction.cxx.
View newest version in sPHENIX GitHub at line 58 of file NNfunction.cxx
References synapse0x85fe830(), synapse0x860d9f0(), synapse0x860da18(), synapse0x860da40(), synapse0x860da68(), and synapse0x860da90().
Referenced by neuron0x860d840().
double NNfunction::input0x860dab8 () private
Definition at line 74 of file NNfunction.cxx.
View newest version in sPHENIX GitHub at line 74 of file NNfunction.cxx
References synapse0x860dcb0(), synapse0x860dcd8(), synapse0x860dd00(), synapse0x860dd28(), synapse0x860dd50(), and synapse0x860dd78().
Referenced by neuron0x860dab8().
double NNfunction::input0x860dda0 () private
Definition at line 90 of file NNfunction.cxx.
View newest version in sPHENIX GitHub at line 90 of file NNfunction.cxx
References synapse0x860df98(), synapse0x860dfc0(), synapse0x860dfe8(), synapse0x860e010(), synapse0x860e038(), and synapse0x860e0e8().
Referenced by neuron0x860dda0().
double NNfunction::input0x860e110 () private
Definition at line 106 of file NNfunction.cxx.
View newest version in sPHENIX GitHub at line 106 of file NNfunction.cxx
References synapse0x860e2c0(), synapse0x860e2e8(), synapse0x860e310(), synapse0x860e338(), synapse0x860e360(), and synapse0x860e388().
Referenced by neuron0x860e110().
double NNfunction::input0x860e3b0 () private
Definition at line 122 of file NNfunction.cxx.
View newest version in sPHENIX GitHub at line 122 of file NNfunction.cxx
References synapse0x860e5a8(), synapse0x860e5d0(), synapse0x860e5f8(), synapse0x860e620(), synapse0x860e648(), and synapse0x860e670().
Referenced by neuron0x860e3b0().
double NNfunction::input0x860e698 () private
Definition at line 138 of file NNfunction.cxx.
View newest version in sPHENIX GitHub at line 138 of file NNfunction.cxx
References synapse0x860e060(), synapse0x860e088(), synapse0x860e798(), synapse0x860e7c0(), and synapse0x860e7e8().
Referenced by neuron0x860e698().
double NNfunction::neuron0x85fe910 () private
Definition at line 34 of file NNfunction.cxx.
View newest version in sPHENIX GitHub at line 34 of file NNfunction.cxx
References input0.
Referenced by synapse0x85fe830(), synapse0x860dcb0(), synapse0x860df98(), synapse0x860e2c0(), and synapse0x860e5a8().
double NNfunction::neuron0x85feae8 () private
Definition at line 38 of file NNfunction.cxx.
View newest version in sPHENIX GitHub at line 38 of file NNfunction.cxx
References input1.
Referenced by synapse0x860d9f0(), synapse0x860dcd8(), synapse0x860dfc0(), synapse0x860e2e8(), and synapse0x860e5d0().
double NNfunction::neuron0x860cfa8 () private
Definition at line 42 of file NNfunction.cxx.
View newest version in sPHENIX GitHub at line 42 of file NNfunction.cxx
References input2.
Referenced by synapse0x860da18(), synapse0x860dd00(), synapse0x860dfe8(), synapse0x860e310(), and synapse0x860e5f8().
double NNfunction::neuron0x860d180 () private
Definition at line 46 of file NNfunction.cxx.
View newest version in sPHENIX GitHub at line 46 of file NNfunction.cxx
References input3.
Referenced by synapse0x860da40(), synapse0x860dd28(), synapse0x860e010(), synapse0x860e338(), and synapse0x860e620().
double NNfunction::neuron0x860d358 () private
Definition at line 50 of file NNfunction.cxx.
View newest version in sPHENIX GitHub at line 50 of file NNfunction.cxx
References input4.
Referenced by synapse0x860da68(), synapse0x860dd50(), synapse0x860e038(), synapse0x860e360(), and synapse0x860e648().
double NNfunction::neuron0x860d530 () private
Definition at line 54 of file NNfunction.cxx.
View newest version in sPHENIX GitHub at line 54 of file NNfunction.cxx
References input5.
Referenced by synapse0x860da90(), synapse0x860dd78(), synapse0x860e0e8(), synapse0x860e388(), and synapse0x860e670().
double NNfunction::neuron0x860d840 () private
Definition at line 69 of file NNfunction.cxx.
View newest version in sPHENIX GitHub at line 69 of file NNfunction.cxx
References input0x860d840().
Referenced by synapse0x860e798().
double NNfunction::neuron0x860dab8 () private
Definition at line 85 of file NNfunction.cxx.
View newest version in sPHENIX GitHub at line 85 of file NNfunction.cxx
References input0x860dab8().
Referenced by synapse0x860e7c0().
double NNfunction::neuron0x860dda0 () private
Definition at line 101 of file NNfunction.cxx.
View newest version in sPHENIX GitHub at line 101 of file NNfunction.cxx
References input0x860dda0().
Referenced by synapse0x860e7e8().
double NNfunction::neuron0x860e110 () private
Definition at line 117 of file NNfunction.cxx.
View newest version in sPHENIX GitHub at line 117 of file NNfunction.cxx
References input0x860e110().
Referenced by synapse0x860e060().
double NNfunction::neuron0x860e3b0 () private
Definition at line 133 of file NNfunction.cxx.
View newest version in sPHENIX GitHub at line 133 of file NNfunction.cxx
References input0x860e3b0().
Referenced by synapse0x860e088().
double NNfunction::neuron0x860e698 () private
Definition at line 148 of file NNfunction.cxx.
View newest version in sPHENIX GitHub at line 148 of file NNfunction.cxx
References input0x860e698().
Referenced by Value().
double NNfunction::synapse0x85fe830 () private
Definition at line 153 of file NNfunction.cxx.
View newest version in sPHENIX GitHub at line 153 of file NNfunction.cxx
References neuron0x85fe910().
Referenced by input0x860d840().
double NNfunction::synapse0x860d9f0 () private
Definition at line 157 of file NNfunction.cxx.
View newest version in sPHENIX GitHub at line 157 of file NNfunction.cxx
References neuron0x85feae8().
Referenced by input0x860d840().
double NNfunction::synapse0x860da18 () private
Definition at line 161 of file NNfunction.cxx.
View newest version in sPHENIX GitHub at line 161 of file NNfunction.cxx
References neuron0x860cfa8().
Referenced by input0x860d840().
double NNfunction::synapse0x860da40 () private
Definition at line 165 of file NNfunction.cxx.
View newest version in sPHENIX GitHub at line 165 of file NNfunction.cxx
References neuron0x860d180().
Referenced by input0x860d840().
double NNfunction::synapse0x860da68 () private
Definition at line 169 of file NNfunction.cxx.
View newest version in sPHENIX GitHub at line 169 of file NNfunction.cxx
References neuron0x860d358().
Referenced by input0x860d840().
double NNfunction::synapse0x860da90 () private
Definition at line 173 of file NNfunction.cxx.
View newest version in sPHENIX GitHub at line 173 of file NNfunction.cxx
References neuron0x860d530().
Referenced by input0x860d840().
double NNfunction::synapse0x860dcb0 () private
Definition at line 177 of file NNfunction.cxx.
View newest version in sPHENIX GitHub at line 177 of file NNfunction.cxx
References neuron0x85fe910().
Referenced by input0x860dab8().
double NNfunction::synapse0x860dcd8 () private
Definition at line 181 of file NNfunction.cxx.
View newest version in sPHENIX GitHub at line 181 of file NNfunction.cxx
References neuron0x85feae8().
Referenced by input0x860dab8().
double NNfunction::synapse0x860dd00 () private
Definition at line 185 of file NNfunction.cxx.
View newest version in sPHENIX GitHub at line 185 of file NNfunction.cxx
References neuron0x860cfa8().
Referenced by input0x860dab8().
double NNfunction::synapse0x860dd28 () private
Definition at line 189 of file NNfunction.cxx.
View newest version in sPHENIX GitHub at line 189 of file NNfunction.cxx
References neuron0x860d180().
Referenced by input0x860dab8().
double NNfunction::synapse0x860dd50 () private
Definition at line 193 of file NNfunction.cxx.
View newest version in sPHENIX GitHub at line 193 of file NNfunction.cxx
References neuron0x860d358().
Referenced by input0x860dab8().
double NNfunction::synapse0x860dd78 () private
Definition at line 197 of file NNfunction.cxx.
View newest version in sPHENIX GitHub at line 197 of file NNfunction.cxx
References neuron0x860d530().
Referenced by input0x860dab8().
double NNfunction::synapse0x860df98 () private
Definition at line 201 of file NNfunction.cxx.
View newest version in sPHENIX GitHub at line 201 of file NNfunction.cxx
References neuron0x85fe910().
Referenced by input0x860dda0().
double NNfunction::synapse0x860dfc0 () private
Definition at line 205 of file NNfunction.cxx.
View newest version in sPHENIX GitHub at line 205 of file NNfunction.cxx
References neuron0x85feae8().
Referenced by input0x860dda0().
double NNfunction::synapse0x860dfe8 () private
Definition at line 209 of file NNfunction.cxx.
View newest version in sPHENIX GitHub at line 209 of file NNfunction.cxx
References neuron0x860cfa8().
Referenced by input0x860dda0().
double NNfunction::synapse0x860e010 () private
Definition at line 213 of file NNfunction.cxx.
View newest version in sPHENIX GitHub at line 213 of file NNfunction.cxx
References neuron0x860d180().
Referenced by input0x860dda0().
double NNfunction::synapse0x860e038 () private
Definition at line 217 of file NNfunction.cxx.
View newest version in sPHENIX GitHub at line 217 of file NNfunction.cxx
References neuron0x860d358().
Referenced by input0x860dda0().
double NNfunction::synapse0x860e060 () private
Definition at line 285 of file NNfunction.cxx.
View newest version in sPHENIX GitHub at line 285 of file NNfunction.cxx
References neuron0x860e110().
Referenced by input0x860e698().
double NNfunction::synapse0x860e088 () private
Definition at line 289 of file NNfunction.cxx.
View newest version in sPHENIX GitHub at line 289 of file NNfunction.cxx
References neuron0x860e3b0().
Referenced by input0x860e698().
double NNfunction::synapse0x860e0e8 () private
Definition at line 221 of file NNfunction.cxx.
View newest version in sPHENIX GitHub at line 221 of file NNfunction.cxx
References neuron0x860d530().
Referenced by input0x860dda0().
double NNfunction::synapse0x860e2c0 () private
Definition at line 225 of file NNfunction.cxx.
View newest version in sPHENIX GitHub at line 225 of file NNfunction.cxx
References neuron0x85fe910().
Referenced by input0x860e110().
double NNfunction::synapse0x860e2e8 () private
Definition at line 229 of file NNfunction.cxx.
View newest version in sPHENIX GitHub at line 229 of file NNfunction.cxx
References neuron0x85feae8().
Referenced by input0x860e110().
double NNfunction::synapse0x860e310 () private
Definition at line 233 of file NNfunction.cxx.
View newest version in sPHENIX GitHub at line 233 of file NNfunction.cxx
References neuron0x860cfa8().
Referenced by input0x860e110().
double NNfunction::synapse0x860e338 () private
Definition at line 237 of file NNfunction.cxx.
View newest version in sPHENIX GitHub at line 237 of file NNfunction.cxx
References neuron0x860d180().
Referenced by input0x860e110().
double NNfunction::synapse0x860e360 () private
Definition at line 241 of file NNfunction.cxx.
View newest version in sPHENIX GitHub at line 241 of file NNfunction.cxx
References neuron0x860d358().
Referenced by input0x860e110().
double NNfunction::synapse0x860e388 () private
Definition at line 245 of file NNfunction.cxx.
View newest version in sPHENIX GitHub at line 245 of file NNfunction.cxx
References neuron0x860d530().
Referenced by input0x860e110().
double NNfunction::synapse0x860e5a8 () private
Definition at line 249 of file NNfunction.cxx.
View newest version in sPHENIX GitHub at line 249 of file NNfunction.cxx
References neuron0x85fe910().
Referenced by input0x860e3b0().
double NNfunction::synapse0x860e5d0 () private
Definition at line 253 of file NNfunction.cxx.
View newest version in sPHENIX GitHub at line 253 of file NNfunction.cxx
References neuron0x85feae8().
Referenced by input0x860e3b0().
double NNfunction::synapse0x860e5f8 () private
Definition at line 257 of file NNfunction.cxx.
View newest version in sPHENIX GitHub at line 257 of file NNfunction.cxx
References neuron0x860cfa8().
Referenced by input0x860e3b0().
double NNfunction::synapse0x860e620 () private
Definition at line 261 of file NNfunction.cxx.
View newest version in sPHENIX GitHub at line 261 of file NNfunction.cxx
References neuron0x860d180().
Referenced by input0x860e3b0().
double NNfunction::synapse0x860e648 () private
Definition at line 265 of file NNfunction.cxx.
View newest version in sPHENIX GitHub at line 265 of file NNfunction.cxx
References neuron0x860d358().
Referenced by input0x860e3b0().
double NNfunction::synapse0x860e670 () private
Definition at line 269 of file NNfunction.cxx.
View newest version in sPHENIX GitHub at line 269 of file NNfunction.cxx
References neuron0x860d530().
Referenced by input0x860e3b0().
double NNfunction::synapse0x860e798 () private
Definition at line 273 of file NNfunction.cxx.
View newest version in sPHENIX GitHub at line 273 of file NNfunction.cxx
References neuron0x860d840().
Referenced by input0x860e698().
double NNfunction::synapse0x860e7c0 () private
Definition at line 277 of file NNfunction.cxx.
View newest version in sPHENIX GitHub at line 277 of file NNfunction.cxx
References neuron0x860dab8().
Referenced by input0x860e698().
double NNfunction::synapse0x860e7e8 () private
Definition at line 281 of file NNfunction.cxx.
View newest version in sPHENIX GitHub at line 281 of file NNfunction.cxx
References neuron0x860dda0().
Referenced by input0x860e698().
double NNfunction::Value (int index, double in0, double in1, double in2, double in3, double in4, double in5)
Definition at line 4 of file NNfunction.cxx.
View newest version in sPHENIX GitHub at line 4 of file NNfunction.cxx
References input0, input1, input2, input3, input4, input5, and neuron0x860e698().
Referenced by CbmRichRingSelectNeuralNet::DoSelect().
double NNfunction::Value (int index, double * input)
Definition at line 19 of file NNfunction.cxx.
View newest version in sPHENIX GitHub at line 19 of file NNfunction.cxx
References input0, input1, input2, input3, input4, input5, and neuron0x860e698().
Member Data Documentation
double NNfunction::input0 private
Definition at line 11 of file NNfunction.h.
View newest version in sPHENIX GitHub at line 11 of file NNfunction.h
Referenced by neuron0x85fe910(), and Value().
double NNfunction::input1 private
Definition at line 12 of file NNfunction.h.
View newest version in sPHENIX GitHub at line 12 of file NNfunction.h
Referenced by neuron0x85feae8(), and Value().
double NNfunction::input2 private
Definition at line 13 of file NNfunction.h.
View newest version in sPHENIX GitHub at line 13 of file NNfunction.h
Referenced by neuron0x860cfa8(), and Value().
double NNfunction::input3 private
Definition at line 14 of file NNfunction.h.
View newest version in sPHENIX GitHub at line 14 of file NNfunction.h
Referenced by neuron0x860d180(), and Value().
double NNfunction::input4 private
Definition at line 15 of file NNfunction.h.
View newest version in sPHENIX GitHub at line 15 of file NNfunction.h
Referenced by neuron0x860d358(), and Value().
double NNfunction::input5 private
Definition at line 16 of file NNfunction.h.
View newest version in sPHENIX GitHub at line 16 of file NNfunction.h
Referenced by neuron0x860d530(), and Value().
The documentation for this class was generated from the following files:
EicRoot/blob/master/rich/standalone/algorithm/NNfunction.h
EicRoot/blob/master/rich/standalone/algorithm/NNfunction.cxx