EIC Software: GFSpacepointHitPolicy Class Reference
GFSpacepointHitPolicy Class Reference
Genfit
Policy class implementing a space point hit geometry.
#include <EicRoot/blob/master/genfit/GFSpacepointHitPolicy.h>
Public Member Functions
GFSpacepointHitPolicy ()
const GFDetPlane & detPlane (GFAbsRecoHit *, GFAbsTrackRep *)
Get detector plane perpendicular to track.
TMatrixT< double > hitCoord (GFAbsRecoHit *, const GFDetPlane &)
Hit coordinates in detector plane.
TMatrixT< double > hitCov (GFAbsRecoHit *, const GFDetPlane &)
Hit covariances in detector plane.
virtual ~GFSpacepointHitPolicy ()
const std::string & getName ()
ClassDef (GFSpacepointHitPolicy, 1)
Private Attributes
GFDetPlane fPlane
Static Private Attributes
static const std::string fPolicyName = "GFSpacepointHitPolicy"
Detailed Description
Policy class implementing a space point hit geometry.
Author
Christian Höppner (Technische Universität München, original author)
Sebastian Neubert (Technische Universität München, original author)
RecoHits for detectors measuring 3D space points should inherit from RecoHitIfc<GFSpacepointHitPolicy>.
For a space point the detector plane has to be defined with respect to a track representation. GFSpacepointHitPolicy implements a scheme where the detectorplane is chosen perpendicular to the track. In a track fit only 2 of the three coordinates of a space point are independent (the track is a one-dimensional object). Therefore the 3D data of the hit is used to define a proper detector plane into which the hit coordinates are then projected.
Definition at line 52 of file GFSpacepointHitPolicy.h.
View newest version in sPHENIX GitHub at line 52 of file GFSpacepointHitPolicy.h
Constructor & Destructor Documentation
GFSpacepointHitPolicy::GFSpacepointHitPolicy () inline
Definition at line 56 of file GFSpacepointHitPolicy.h.
View newest version in sPHENIX GitHub at line 56 of file GFSpacepointHitPolicy.h
virtual GFSpacepointHitPolicy::~GFSpacepointHitPolicy () inline virtual
Definition at line 75 of file GFSpacepointHitPolicy.h.
View newest version in sPHENIX GitHub at line 75 of file GFSpacepointHitPolicy.h
Member Function Documentation
GFSpacepointHitPolicy::ClassDef (GFSpacepointHitPolicy , 1)
const GFDetPlane & GFSpacepointHitPolicy::detPlane (GFAbsRecoHit * hit, GFAbsTrackRep * rep)
Get detector plane perpendicular to track.
The detector plane is contructed from the position of the hit and the track representation. For this the track is extrapolated to the point of closest approach to the hit.
Definition at line 89 of file GFSpacepointHitPolicy.cxx.
View newest version in sPHENIX GitHub at line 89 of file GFSpacepointHitPolicy.cxx
References GFAbsTrackRep::extrapolateToPoint(), fPlane, GFAbsRecoHit::getRawHitCoord(), GFDetPlane::setNormal(), and GFDetPlane::setO().
const std::string& GFSpacepointHitPolicy::getName () inline
Definition at line 77 of file GFSpacepointHitPolicy.h.
View newest version in sPHENIX GitHub at line 77 of file GFSpacepointHitPolicy.h
References fPolicyName.
TMatrixT< double > GFSpacepointHitPolicy::hitCoord (GFAbsRecoHit * hit, const GFDetPlane & plane)
Hit coordinates in detector plane.
Definition at line 30 of file GFSpacepointHitPolicy.cxx.
View newest version in sPHENIX GitHub at line 30 of file GFSpacepointHitPolicy.cxx
References GFDetPlane::getO(), GFAbsRecoHit::getRawHitCoord(), GFDetPlane::getU(), and GFDetPlane::getV().
TMatrixT< double > GFSpacepointHitPolicy::hitCov (GFAbsRecoHit * hit, const GFDetPlane & plane)
Hit covariances in detector plane.
Definition at line 59 of file GFSpacepointHitPolicy.cxx.
View newest version in sPHENIX GitHub at line 59 of file GFSpacepointHitPolicy.cxx
References GFAbsRecoHit::getRawHitCov(), GFDetPlane::getU(), and GFDetPlane::getV().
Member Data Documentation
GFDetPlane GFSpacepointHitPolicy::fPlane private
Definition at line 82 of file GFSpacepointHitPolicy.h.
View newest version in sPHENIX GitHub at line 82 of file GFSpacepointHitPolicy.h
Referenced by detPlane().
const std::string GFSpacepointHitPolicy::fPolicyName = "GFSpacepointHitPolicy" static private
Definition at line 79 of file GFSpacepointHitPolicy.h.
View newest version in sPHENIX GitHub at line 79 of file GFSpacepointHitPolicy.h
Referenced by getName().
The documentation for this class was generated from the following files:
EicRoot/blob/master/genfit/GFSpacepointHitPolicy.h
EicRoot/blob/master/genfit/GFSpacepointHitPolicy.cxx