EIC Software: FW::TruthTrackFinder Exception Reference
FW::TruthTrackFinder Exception Reference final
#include <fun4all_acts/blob/master/Examples/Algorithms/TruthTracking/ACTFW/TruthTracking/TruthTrackFinder.hpp>
Classes
struct Config
Public Member Functions
TruthTrackFinder (const Config &cfg, Acts::Logging::Level lvl)
ProcessCode execute (const AlgorithmContext &ctx) const overridefinal
Public Member Functions inherited from FW::BareAlgorithm
BareAlgorithm (std::string name, Acts::Logging::Level level=Acts::Logging::INFO)
std::string name () const finaloverride
The algorithm name.
Private Attributes
Config m_cfg
Additional Inherited Members
Protected Member Functions inherited from FW::BareAlgorithm
const Acts::Logger & logger () const
Detailed Description
Convert true particle tracks into "reconstructed" proto tracks.
For numbering consistency, this creates a proto track for each input particle. Depending on the input particle selection it can contain zero hits. This algorithm should be able to replace any other real track finder in the reconstruction chain e.g. to validate algorithms further down the chain.
Definition at line 22 of file TruthTrackFinder.hpp.
View newest version in sPHENIX GitHub at line 22 of file TruthTrackFinder.hpp
Constructor & Destructor Documentation
TruthTrackFinder::TruthTrackFinder (const Config & cfg, Acts::Logging::Level lvl)
Definition at line 23 of file TruthTrackFinder.cpp.
View newest version in sPHENIX GitHub at line 23 of file TruthTrackFinder.cpp
References FW::TruthTrackFinder::Config::inputHitParticlesMap, FW::TruthTrackFinder::Config::inputParticles, m_cfg, and FW::TruthTrackFinder::Config::outputProtoTracks.
Member Function Documentation
ProcessCode TruthTrackFinder::execute (const AlgorithmContext & context) const final override virtual
Execute the algorithm for one event.
This function must be implemented by subclasses.
Implements FW::BareAlgorithm.
Definition at line 36 of file TruthTrackFinder.cpp.
View newest version in sPHENIX GitHub at line 36 of file TruthTrackFinder.cpp
References FW::WhiteBoard::add(), FW::AlgorithmContext::eventStore, FW::WhiteBoard::get(), FW::TruthTrackFinder::Config::inputHitParticlesMap, FW::TruthTrackFinder::Config::inputParticles, FW::invertIndexMultimap(), m_cfg, FW::makeRange(), FW::TruthTrackFinder::Config::outputProtoTracks, particle, and SUCCESS.
Member Data Documentation
Config FW::TruthTrackFinder::m_cfg private
Definition at line 38 of file TruthTrackFinder.hpp.
View newest version in sPHENIX GitHub at line 38 of file TruthTrackFinder.hpp
Referenced by execute(), and TruthTrackFinder().
The documentation for this exception was generated from the following files:
fun4all_acts/blob/master/Examples/Algorithms/TruthTracking/ACTFW/TruthTracking/TruthTrackFinder.hpp
fun4all_acts/blob/master/Examples/Algorithms/TruthTracking/ACTFW/TruthTracking/TruthTrackFinder.cpp