EIC Software: BeamParticles Class Reference
BeamParticles Class Reference
#include <eic-smear/blob/master/include/eicsmear/erhic/BeamParticles.h>
Public Member Functions
BeamParticles ()
BeamParticles (const TLorentzVector &hadronBeam, const TLorentzVector &leptonBeam, const TLorentzVector &scatteredHadron, const TLorentzVector &scatteredLepton, const TLorentzVector &exchangedBoson)
virtual ~BeamParticles ()
void Reset ()
void SetBeamHadron (const TLorentzVector &)
void SetBeamLepton (const TLorentzVector &)
void SetScatteredHadron (const TLorentzVector &)
void SetScatteredLepton (const TLorentzVector &)
void SetBoson (const TLorentzVector &)
const TLorentzVector & BeamHadron () const
const TLorentzVector & BeamLepton () const
const TLorentzVector & GetScatteredHadron () const
const TLorentzVector & ScatteredLepton () const
const TLorentzVector & GetBoson () const
Protected Attributes
TLorentzVector mBeamHadron
Incident hadron beam.
TLorentzVector mBeamLepton
Incident lepton beam.
TLorentzVector mScatteredHadron
Scattered hadron beam.
TLorentzVector mScatteredLepton
Scattered lepton beam.
TLorentzVector mBoson
Exchanged boson.
Detailed Description
Wrapper class around energy-momentum 4-vectors defining the incident and scattered beams and the exchanged boson.
Definition at line 20 of file BeamParticles.h.
View newest version in sPHENIX GitHub at line 20 of file BeamParticles.h
Constructor & Destructor Documentation
BeamParticles::BeamParticles ()
Default constructor. Initialises all vector components to not-a-number.
Definition at line 14 of file BeamParticles.cxx.
View newest version in sPHENIX GitHub at line 14 of file BeamParticles.cxx
References Reset().
BeamParticles::BeamParticles (const TLorentzVector & hadronBeam, const TLorentzVector & leptonBeam, const TLorentzVector & scatteredHadron, const TLorentzVector & scatteredLepton, const TLorentzVector & exchangedBoson)
Constructor initialsing all particles.
Definition at line 18 of file BeamParticles.cxx.
View newest version in sPHENIX GitHub at line 18 of file BeamParticles.cxx
BeamParticles::~BeamParticles () virtual
Destructor.
Definition at line 30 of file BeamParticles.cxx.
View newest version in sPHENIX GitHub at line 30 of file BeamParticles.cxx
Member Function Documentation
const TLorentzVector & BeamParticles::BeamHadron () const inline
Definition at line 77 of file BeamParticles.h.
View newest version in sPHENIX GitHub at line 77 of file BeamParticles.h
References mBeamHadron.
Referenced by erhic::Pythia6EventBuilder::BuildEvent(), and erhic::EventFromAsciiFactory< T >::FinishEvent().
const TLorentzVector & BeamParticles::BeamLepton () const inline
Definition at line 81 of file BeamParticles.h.
View newest version in sPHENIX GitHub at line 81 of file BeamParticles.h
References mBeamLepton.
Referenced by erhic::Pythia6EventBuilder::BuildEvent(), and erhic::EventFromAsciiFactory< T >::FinishEvent().
const TLorentzVector & BeamParticles::GetBoson () const inline
Definition at line 93 of file BeamParticles.h.
View newest version in sPHENIX GitHub at line 93 of file BeamParticles.h
References mBoson.
const TLorentzVector & BeamParticles::GetScatteredHadron () const inline
Definition at line 85 of file BeamParticles.h.
View newest version in sPHENIX GitHub at line 85 of file BeamParticles.h
References mScatteredHadron.
void BeamParticles::Reset ()
Sets all the 4-vectors' components to not-a-number.
Definition at line 33 of file BeamParticles.cxx.
View newest version in sPHENIX GitHub at line 33 of file BeamParticles.cxx
References mBeamHadron, mBeamLepton, mBoson, mScatteredHadron, and mScatteredLepton.
Referenced by BeamParticles(), and ParticleIdentifier::IdentifyBeams().
const TLorentzVector & BeamParticles::ScatteredLepton () const inline
Definition at line 89 of file BeamParticles.h.
View newest version in sPHENIX GitHub at line 89 of file BeamParticles.h
References mScatteredLepton.
Referenced by erhic::Pythia6EventBuilder::BuildEvent(), and erhic::EventFromAsciiFactory< T >::FinishEvent().
void BeamParticles::SetBeamHadron (const TLorentzVector & vec) inline
Definition at line 97 of file BeamParticles.h.
View newest version in sPHENIX GitHub at line 97 of file BeamParticles.h
References mBeamHadron.
Referenced by ParticleIdentifier::IdentifyBeams().
void BeamParticles::SetBeamLepton (const TLorentzVector & vec) inline
Definition at line 101 of file BeamParticles.h.
View newest version in sPHENIX GitHub at line 101 of file BeamParticles.h
References mBeamLepton.
Referenced by ParticleIdentifier::IdentifyBeams().
void BeamParticles::SetBoson (const TLorentzVector & vec) inline
Definition at line 113 of file BeamParticles.h.
View newest version in sPHENIX GitHub at line 113 of file BeamParticles.h
References mBoson.
Referenced by ParticleIdentifier::IdentifyBeams().
void BeamParticles::SetScatteredHadron (const TLorentzVector & vec) inline
Definition at line 105 of file BeamParticles.h.
View newest version in sPHENIX GitHub at line 105 of file BeamParticles.h
References mScatteredHadron.
void BeamParticles::SetScatteredLepton (const TLorentzVector & vec) inline
Definition at line 109 of file BeamParticles.h.
View newest version in sPHENIX GitHub at line 109 of file BeamParticles.h
References mScatteredLepton.
Referenced by ParticleIdentifier::IdentifyBeams().
Member Data Documentation
TLorentzVector BeamParticles::mBeamHadron protected
Incident hadron beam.
Definition at line 68 of file BeamParticles.h.
View newest version in sPHENIX GitHub at line 68 of file BeamParticles.h
Referenced by BeamHadron(), Reset(), and SetBeamHadron().
TLorentzVector BeamParticles::mBeamLepton protected
Incident lepton beam.
Definition at line 69 of file BeamParticles.h.
View newest version in sPHENIX GitHub at line 69 of file BeamParticles.h
Referenced by BeamLepton(), Reset(), and SetBeamLepton().
TLorentzVector BeamParticles::mBoson protected
Exchanged boson.
Definition at line 72 of file BeamParticles.h.
View newest version in sPHENIX GitHub at line 72 of file BeamParticles.h
Referenced by GetBoson(), Reset(), and SetBoson().
TLorentzVector BeamParticles::mScatteredHadron protected
Scattered hadron beam.
Definition at line 70 of file BeamParticles.h.
View newest version in sPHENIX GitHub at line 70 of file BeamParticles.h
Referenced by GetScatteredHadron(), Reset(), and SetScatteredHadron().
TLorentzVector BeamParticles::mScatteredLepton protected
Scattered lepton beam.
Definition at line 71 of file BeamParticles.h.
View newest version in sPHENIX GitHub at line 71 of file BeamParticles.h
Referenced by Reset(), ScatteredLepton(), and SetScatteredLepton().
The documentation for this class was generated from the following files:
eic-smear/blob/master/include/eicsmear/erhic/BeamParticles.h
eic-smear/blob/master/src/erhic/BeamParticles.cxx