EIC Software: FairDbLogEntry Class Reference
FairDbLogEntry Class Reference
#include <EicRoot/blob/master/dbase/dbInterface/FairDbLogEntry.h>
Public Member Functions
FairDbLogEntry (const string &tableName="", const string &reason="", Int_t detMask=Detector::FullMask(), Int_t simMask=SimFlag::FullMask(), FairDb::Task task=0, Int_t logSeqNoMin=0, Int_t logSeqNoMax=0, Int_t logNumSeqNo=0)
virtual ~FairDbLogEntry ()
virtual FairDbTableRow * CreateTableRow () const
Int_t GetAggregateNo () const
const string & GetLogTableName () const
Int_t GetDetectorMask () const
Int_t GetLogSeqNoMin () const
Int_t GetLogSeqNoMax () const
Int_t GetLogNumSeqNo () const
Int_t GetSimMask () const
FairDb::Task GetTask () const
const string & GetUserName () const
const string & GetProcessName () const
const string & GetHostName () const
const string & GetServerName () const
const string & GetReason () const
ValTimeStamp GetUpdateTime () const
Bool_t HasReason () const
void SetReason (const string &reason)
void SetDetectorMask (Int_t detMask)
void SetSimMask (Int_t simMask)
void SetTask (FairDb::Task task)
void SetUpdateTime (const ValTimeStamp &updateTime)
void Recreate (const string &tableName="", const string &reason="", Int_t detMask=Detector::FullMask(), Int_t simMask=SimFlag::FullMask(), FairDb::Task task=0, Int_t logSeqNoMin=0, Int_t logSeqNoMax=0, Int_t logNumSeqNo=0)
virtual void Fill (FairDbResultSet &rs, const FairDbValidityRec *vrec)
virtual void Store (FairDbOutRowStream &ors, const FairDbValidityRec *vrec) const
Bool_t Write (UInt_t dbNo, Int_t logSeqNo=0)
Public Member Functions inherited from FairDbTableRow
FairDbTableRow ()
FairDbTableRow (const FairDbTableRow &from)
virtual ~FairDbTableRow ()
virtual Bool_t CanL2Cache () const
FairDbResult * GetOwner () const
virtual UInt_t GetIndex (UInt_t defIndex) const
void SetOwner (FairDbResult *owner)
Private Member Functions
FairDbLogEntry (const FairDbLogEntry &from)
void SetServerName ()
Private Attributes
UInt_t fDbNo
Database no. written to. =0 if not output.
Int_t fSeqNo
Seq. No. used to write this object. =0 if not output.
string fLogTableName
Table being updated.
Int_t fLogDetMask
Detector type mask of update.
Int_t fLogSimMask
SimFlag mask of update.
FairDb::Task fLogTask
Task of update.
Int_t fLogSeqNoMin
Minimum Seq. No. being updated.
Int_t fLogSeqNoMax
Maximum Seq. No. being updated.
Int_t fLogNumSeqNo
Number of Seq. Nos. being updated.
ValTimeStamp fUpdateTime
Time of update.
string fUserName
User performing update.
string fProcessName
Process performing update.
string fHostName
Host performing update.
string fServerName
Db server being updated.
string fReason
Reason for update.
Detailed Description
Definition at line 25 of file FairDbLogEntry.h.
View newest version in sPHENIX GitHub at line 25 of file FairDbLogEntry.h
Constructor & Destructor Documentation
FairDbLogEntry::FairDbLogEntry (const string & tableName = "", const string & reason = "", Int_t detMask = Detector::FullMask(), Int_t simMask = SimFlag::FullMask(), FairDb::Task task = 0, Int_t logSeqNoMin = 0, Int_t logSeqNoMax = 0, Int_t logNumSeqNo = 0)
Definition at line 33 of file FairDbLogEntry.cxx.
View newest version in sPHENIX GitHub at line 33 of file FairDbLogEntry.cxx
References fLogNumSeqNo, fLogSeqNoMax, fLogSeqNoMin, fUserName, SetReason(), and SetServerName().
Referenced by CreateTableRow().
FairDbLogEntry::~FairDbLogEntry () virtual
Definition at line 75 of file FairDbLogEntry.cxx.
View newest version in sPHENIX GitHub at line 75 of file FairDbLogEntry.cxx
FairDbLogEntry::FairDbLogEntry (const FairDbLogEntry & from) private
Member Function Documentation
virtual FairDbTableRow* FairDbLogEntry::CreateTableRow () const inline virtual
Implements FairDbTableRow.
Definition at line 46 of file FairDbLogEntry.h.
View newest version in sPHENIX GitHub at line 46 of file FairDbLogEntry.h
References FairDbLogEntry().
void FairDbLogEntry::Fill (FairDbResultSet & rs, const FairDbValidityRec * vrec) virtual
Implements FairDbTableRow.
Definition at line 105 of file FairDbLogEntry.cxx.
View newest version in sPHENIX GitHub at line 105 of file FairDbLogEntry.cxx
References fHostName, fLogDetMask, fLogNumSeqNo, fLogSeqNoMax, fLogSeqNoMin, fLogSimMask, fLogTableName, fLogTask, fProcessName, fReason, fServerName, fUpdateTime, fUserName, ValRange::GetDetectorMask(), ValRange::GetSimMask(), FairDbValidityRec::GetTask(), ValRange::GetTimeStart(), and FairDbValidityRec::GetValRange().
Int_t FairDbLogEntry::GetAggregateNo () const inline virtual
Reimplemented from FairDbTableRow.
Definition at line 49 of file FairDbLogEntry.h.
View newest version in sPHENIX GitHub at line 49 of file FairDbLogEntry.h
Int_t FairDbLogEntry::GetDetectorMask () const inline
Definition at line 53 of file FairDbLogEntry.h.
View newest version in sPHENIX GitHub at line 53 of file FairDbLogEntry.h
References fLogDetMask.
Referenced by operator<<().
const string& FairDbLogEntry::GetHostName () const inline
Definition at line 61 of file FairDbLogEntry.h.
View newest version in sPHENIX GitHub at line 61 of file FairDbLogEntry.h
References fHostName.
Referenced by operator<<().
Int_t FairDbLogEntry::GetLogNumSeqNo () const inline
Definition at line 56 of file FairDbLogEntry.h.
View newest version in sPHENIX GitHub at line 56 of file FairDbLogEntry.h
References fLogNumSeqNo.
Referenced by operator<<().
Int_t FairDbLogEntry::GetLogSeqNoMax () const inline
Definition at line 55 of file FairDbLogEntry.h.
View newest version in sPHENIX GitHub at line 55 of file FairDbLogEntry.h
References fLogSeqNoMax.
Referenced by operator<<().
Int_t FairDbLogEntry::GetLogSeqNoMin () const inline
Definition at line 54 of file FairDbLogEntry.h.
View newest version in sPHENIX GitHub at line 54 of file FairDbLogEntry.h
References fLogSeqNoMin.
Referenced by operator<<().
const string& FairDbLogEntry::GetLogTableName () const inline
Definition at line 52 of file FairDbLogEntry.h.
View newest version in sPHENIX GitHub at line 52 of file FairDbLogEntry.h
References fLogTableName.
Referenced by operator<<().
const string& FairDbLogEntry::GetProcessName () const inline
Definition at line 60 of file FairDbLogEntry.h.
View newest version in sPHENIX GitHub at line 60 of file FairDbLogEntry.h
References fProcessName.
Referenced by operator<<().
const string& FairDbLogEntry::GetReason () const inline
Definition at line 63 of file FairDbLogEntry.h.
View newest version in sPHENIX GitHub at line 63 of file FairDbLogEntry.h
References fReason.
Referenced by operator<<().
const string& FairDbLogEntry::GetServerName () const inline
Definition at line 62 of file FairDbLogEntry.h.
View newest version in sPHENIX GitHub at line 62 of file FairDbLogEntry.h
References fServerName.
Referenced by operator<<().
Int_t FairDbLogEntry::GetSimMask () const inline
Definition at line 57 of file FairDbLogEntry.h.
View newest version in sPHENIX GitHub at line 57 of file FairDbLogEntry.h
References fLogSimMask.
Referenced by operator<<().
FairDb::Task FairDbLogEntry::GetTask () const inline
Definition at line 58 of file FairDbLogEntry.h.
View newest version in sPHENIX GitHub at line 58 of file FairDbLogEntry.h
References fLogTask.
Referenced by operator<<().
ValTimeStamp FairDbLogEntry::GetUpdateTime () const inline
Definition at line 64 of file FairDbLogEntry.h.
View newest version in sPHENIX GitHub at line 64 of file FairDbLogEntry.h
References fUpdateTime.
Referenced by operator<<().
const string& FairDbLogEntry::GetUserName () const inline
Definition at line 59 of file FairDbLogEntry.h.
View newest version in sPHENIX GitHub at line 59 of file FairDbLogEntry.h
References fUserName.
Referenced by operator<<().
Bool_t FairDbLogEntry::HasReason () const inline
Definition at line 66 of file FairDbLogEntry.h.
View newest version in sPHENIX GitHub at line 66 of file FairDbLogEntry.h
References fReason.
Referenced by Write().
void FairDbLogEntry::Recreate (const string & tableName = "", const string & reason = "", Int_t detMask = Detector::FullMask(), Int_t simMask = SimFlag::FullMask(), FairDb::Task task = 0, Int_t logSeqNoMin = 0, Int_t logSeqNoMax = 0, Int_t logNumSeqNo = 0)
Definition at line 127 of file FairDbLogEntry.cxx.
View newest version in sPHENIX GitHub at line 127 of file FairDbLogEntry.cxx
References fDbNo, fLogDetMask, fLogNumSeqNo, fLogSeqNoMax, fLogSeqNoMin, fLogSimMask, fLogTableName, fLogTask, fSeqNo, SimFlag::FullMask(), Detector::FullMask(), and SetReason().
void FairDbLogEntry::SetDetectorMask (Int_t detMask) inline
Definition at line 70 of file FairDbLogEntry.h.
View newest version in sPHENIX GitHub at line 70 of file FairDbLogEntry.h
References fLogDetMask.
void FairDbLogEntry::SetReason (const string & reason)
Definition at line 164 of file FairDbLogEntry.cxx.
View newest version in sPHENIX GitHub at line 164 of file FairDbLogEntry.cxx
References fReason, and getline.
Referenced by FairDbLogEntry(), and Recreate().
void FairDbLogEntry::SetServerName () private
Definition at line 194 of file FairDbLogEntry.cxx.
View newest version in sPHENIX GitHub at line 194 of file FairDbLogEntry.cxx
References fDbNo, fServerName, FairDbTableProxyRegistry::GetMultConnector(), FairDbMultConnector::GetURL(), and FairDbTableProxyRegistry::Instance().
Referenced by FairDbLogEntry().
void FairDbLogEntry::SetSimMask (Int_t simMask) inline
Definition at line 71 of file FairDbLogEntry.h.
View newest version in sPHENIX GitHub at line 71 of file FairDbLogEntry.h
References fLogSimMask.
void FairDbLogEntry::SetTask (FairDb::Task task) inline
Definition at line 72 of file FairDbLogEntry.h.
View newest version in sPHENIX GitHub at line 72 of file FairDbLogEntry.h
References fLogTask.
void FairDbLogEntry::SetUpdateTime (const ValTimeStamp & updateTime) inline
Definition at line 73 of file FairDbLogEntry.h.
View newest version in sPHENIX GitHub at line 73 of file FairDbLogEntry.h
References fUpdateTime.
void FairDbLogEntry::Store (FairDbOutRowStream & ors, const FairDbValidityRec * vrec) const virtual
Reimplemented from FairDbTableRow.
Definition at line 204 of file FairDbLogEntry.cxx.
View newest version in sPHENIX GitHub at line 204 of file FairDbLogEntry.cxx
References fHostName, fLogNumSeqNo, fLogSeqNoMax, fLogSeqNoMin, fLogTableName, fProcessName, fReason, fServerName, and fUserName.
Bool_t FairDbLogEntry::Write (UInt_t dbNo, Int_t logSeqNo = 0)
Definition at line 221 of file FairDbLogEntry.cxx.
View newest version in sPHENIX GitHub at line 221 of file FairDbLogEntry.cxx
References FairDbSqlValPacket::AddDataRow(), FairDbMultConnector::AllocateSeqNo(), fDbNo, fLogDetMask, fLogNumSeqNo, fLogSeqNoMax, fLogSeqNoMin, fLogSimMask, fLogTask, fSeqNo, fUpdateTime, FairDbValidityRec::GetCreationDate(), FairDbTableProxy::GetMultConnector(), FairDbTableProxyRegistry::GetTableProxy(), FairDbValidityRec::GetTask(), FairDbValidityRec::GetValRange(), HasReason(), FairDbTableProxyRegistry::Instance(), FairDbSqlValPacket::Recreate(), FairDbSqlValPacket::SetSeqNo(), and FairDbSqlValPacket::Store().
Member Data Documentation
UInt_t FairDbLogEntry::fDbNo private
Database no. written to. =0 if not output.
Definition at line 101 of file FairDbLogEntry.h.
View newest version in sPHENIX GitHub at line 101 of file FairDbLogEntry.h
Referenced by Recreate(), SetServerName(), and Write().
string FairDbLogEntry::fHostName private
Host performing update.
Definition at line 137 of file FairDbLogEntry.h.
View newest version in sPHENIX GitHub at line 137 of file FairDbLogEntry.h
Referenced by Fill(), GetHostName(), and Store().
Int_t FairDbLogEntry::fLogDetMask private
Detector type mask of update.
Definition at line 110 of file FairDbLogEntry.h.
View newest version in sPHENIX GitHub at line 110 of file FairDbLogEntry.h
Referenced by Fill(), GetDetectorMask(), Recreate(), SetDetectorMask(), and Write().
Int_t FairDbLogEntry::fLogNumSeqNo private
Number of Seq. Nos. being updated.
Definition at line 125 of file FairDbLogEntry.h.
View newest version in sPHENIX GitHub at line 125 of file FairDbLogEntry.h
Referenced by FairDbLogEntry(), Fill(), GetLogNumSeqNo(), Recreate(), Store(), and Write().
Int_t FairDbLogEntry::fLogSeqNoMax private
Maximum Seq. No. being updated.
Definition at line 122 of file FairDbLogEntry.h.
View newest version in sPHENIX GitHub at line 122 of file FairDbLogEntry.h
Referenced by FairDbLogEntry(), Fill(), GetLogSeqNoMax(), Recreate(), Store(), and Write().
Int_t FairDbLogEntry::fLogSeqNoMin private
Minimum Seq. No. being updated.
Definition at line 119 of file FairDbLogEntry.h.
View newest version in sPHENIX GitHub at line 119 of file FairDbLogEntry.h
Referenced by FairDbLogEntry(), Fill(), GetLogSeqNoMin(), Recreate(), Store(), and Write().
Int_t FairDbLogEntry::fLogSimMask private
SimFlag mask of update.
Definition at line 113 of file FairDbLogEntry.h.
View newest version in sPHENIX GitHub at line 113 of file FairDbLogEntry.h
Referenced by Fill(), GetSimMask(), Recreate(), SetSimMask(), and Write().
string FairDbLogEntry::fLogTableName private
Table being updated.
Definition at line 107 of file FairDbLogEntry.h.
View newest version in sPHENIX GitHub at line 107 of file FairDbLogEntry.h
Referenced by Fill(), GetLogTableName(), Recreate(), and Store().
FairDb::Task FairDbLogEntry::fLogTask private
Task of update.
Definition at line 116 of file FairDbLogEntry.h.
View newest version in sPHENIX GitHub at line 116 of file FairDbLogEntry.h
Referenced by Fill(), GetTask(), Recreate(), SetTask(), and Write().
string FairDbLogEntry::fProcessName private
Process performing update.
Definition at line 134 of file FairDbLogEntry.h.
View newest version in sPHENIX GitHub at line 134 of file FairDbLogEntry.h
Referenced by Fill(), GetProcessName(), and Store().
string FairDbLogEntry::fReason private
Reason for update.
Definition at line 143 of file FairDbLogEntry.h.
View newest version in sPHENIX GitHub at line 143 of file FairDbLogEntry.h
Referenced by Fill(), GetReason(), HasReason(), SetReason(), and Store().
Int_t FairDbLogEntry::fSeqNo private
Seq. No. used to write this object. =0 if not output.
Definition at line 104 of file FairDbLogEntry.h.
View newest version in sPHENIX GitHub at line 104 of file FairDbLogEntry.h
Referenced by Recreate(), and Write().
string FairDbLogEntry::fServerName private
Db server being updated.
Definition at line 140 of file FairDbLogEntry.h.
View newest version in sPHENIX GitHub at line 140 of file FairDbLogEntry.h
Referenced by Fill(), GetServerName(), SetServerName(), and Store().
ValTimeStamp FairDbLogEntry::fUpdateTime private
Time of update.
Definition at line 128 of file FairDbLogEntry.h.
View newest version in sPHENIX GitHub at line 128 of file FairDbLogEntry.h
Referenced by Fill(), GetUpdateTime(), SetUpdateTime(), and Write().
string FairDbLogEntry::fUserName private
User performing update.
Definition at line 131 of file FairDbLogEntry.h.
View newest version in sPHENIX GitHub at line 131 of file FairDbLogEntry.h
Referenced by FairDbLogEntry(), Fill(), GetUserName(), and Store().
The documentation for this class was generated from the following files:
EicRoot/blob/master/dbase/dbInterface/FairDbLogEntry.h
EicRoot/blob/master/dbase/dbInterface/FairDbLogEntry.cxx