EIC Software: PndFieldMapData Class Reference
PndFieldMapData Class Reference
#include <EicRoot/blob/master/field/PndFieldMapData.h>
Public Member Functions
PndFieldMapData ()
PndFieldMapData (const char *name)
PndFieldMapData (const char *name, const PndFieldMap &map)
virtual ~PndFieldMapData ()
Int_t GetType () const
Double_t GetXmin () const
Double_t GetYmin () const
Double_t GetZmin () const
Double_t GetXmax () const
Double_t GetYmax () const
Double_t GetZmax () const
Int_t GetNx () const
Int_t GetNy () const
Int_t GetNz () const
TArrayF * GetBx () const
TArrayF * GetBy () const
TArrayF * GetBz () const
Private Member Functions
PndFieldMapData (const PndFieldMapData &L)
PndFieldMapData & operator= (const PndFieldMapData &)
Private Attributes
Int_t fType
Double_t fXmin
Double_t fXmax
Double_t fYmin
Double_t fYmax
Double_t fZmin
Double_t fZmax
Double_t fUnit
Int_t fNx
Int_t fNy
Int_t fNz
TArrayF * fBx
TArrayF * fBy
TArrayF * fBz
Detailed Description
Definition at line 32 of file PndFieldMapData.h.
View newest version in sPHENIX GitHub at line 32 of file PndFieldMapData.h
Constructor & Destructor Documentation
PndFieldMapData::PndFieldMapData ()
Default constructor
Definition at line 8 of file PndFieldMapData.cxx.
View newest version in sPHENIX GitHub at line 8 of file PndFieldMapData.cxx
PndFieldMapData::PndFieldMapData (const char * name)
Standard constructor
Definition at line 31 of file PndFieldMapData.cxx.
View newest version in sPHENIX GitHub at line 31 of file PndFieldMapData.cxx
PndFieldMapData::PndFieldMapData (const char * name, const PndFieldMap & map)
Constructor from an existing PndFieldMap
Definition at line 54 of file PndFieldMapData.cxx.
View newest version in sPHENIX GitHub at line 54 of file PndFieldMapData.cxx
References fBx, fBy, fBz, fNx, fNy, fNz, and PndFieldMap::GetScale().
PndFieldMapData::~PndFieldMapData () virtual
Destructor
Definition at line 94 of file PndFieldMapData.cxx.
View newest version in sPHENIX GitHub at line 94 of file PndFieldMapData.cxx
References fBx, fBy, and fBz.
PndFieldMapData::PndFieldMapData (const PndFieldMapData & L) inline private
Definition at line 71 of file PndFieldMapData.h.
View newest version in sPHENIX GitHub at line 71 of file PndFieldMapData.h
Member Function Documentation
TArrayF* PndFieldMapData::GetBx () const inline
Accessors to the field value arrays
Definition at line 67 of file PndFieldMapData.h.
View newest version in sPHENIX GitHub at line 67 of file PndFieldMapData.h
References fBx.
Referenced by PndFieldMap::SetField().
TArrayF* PndFieldMapData::GetBy () const inline
Definition at line 68 of file PndFieldMapData.h.
View newest version in sPHENIX GitHub at line 68 of file PndFieldMapData.h
References fBy.
Referenced by PndFieldMap::SetField().
TArrayF* PndFieldMapData::GetBz () const inline
Definition at line 69 of file PndFieldMapData.h.
View newest version in sPHENIX GitHub at line 69 of file PndFieldMapData.h
References fBz.
Referenced by PndFieldMap::SetField().
Int_t PndFieldMapData::GetNx () const inline
Definition at line 61 of file PndFieldMapData.h.
View newest version in sPHENIX GitHub at line 61 of file PndFieldMapData.h
References fNx.
Referenced by PndFieldMap::SetField().
Int_t PndFieldMapData::GetNy () const inline
Definition at line 62 of file PndFieldMapData.h.
View newest version in sPHENIX GitHub at line 62 of file PndFieldMapData.h
References fNy.
Referenced by PndFieldMap::SetField().
Int_t PndFieldMapData::GetNz () const inline
Definition at line 63 of file PndFieldMapData.h.
View newest version in sPHENIX GitHub at line 63 of file PndFieldMapData.h
References fNz.
Referenced by PndFieldMap::SetField().
Int_t PndFieldMapData::GetType () const inline
Accessors to field parameters in local coordinate system
Definition at line 54 of file PndFieldMapData.h.
View newest version in sPHENIX GitHub at line 54 of file PndFieldMapData.h
References fType.
Referenced by PndFieldMap::SetField().
Double_t PndFieldMapData::GetXmax () const inline
Definition at line 58 of file PndFieldMapData.h.
View newest version in sPHENIX GitHub at line 58 of file PndFieldMapData.h
References fXmax.
Referenced by PndFieldMap::SetField().
Double_t PndFieldMapData::GetXmin () const inline
Definition at line 55 of file PndFieldMapData.h.
View newest version in sPHENIX GitHub at line 55 of file PndFieldMapData.h
References fXmin.
Referenced by PndFieldMap::SetField().
Double_t PndFieldMapData::GetYmax () const inline
Definition at line 59 of file PndFieldMapData.h.
View newest version in sPHENIX GitHub at line 59 of file PndFieldMapData.h
References fYmax.
Referenced by PndFieldMap::SetField().
Double_t PndFieldMapData::GetYmin () const inline
Definition at line 56 of file PndFieldMapData.h.
View newest version in sPHENIX GitHub at line 56 of file PndFieldMapData.h
References fYmin.
Referenced by PndFieldMap::SetField().
Double_t PndFieldMapData::GetZmax () const inline
Definition at line 60 of file PndFieldMapData.h.
View newest version in sPHENIX GitHub at line 60 of file PndFieldMapData.h
References fZmax.
Referenced by PndFieldMap::SetField().
Double_t PndFieldMapData::GetZmin () const inline
Definition at line 57 of file PndFieldMapData.h.
View newest version in sPHENIX GitHub at line 57 of file PndFieldMapData.h
References fZmin.
Referenced by PndFieldMap::SetField().
PndFieldMapData& PndFieldMapData::operator= (const PndFieldMapData &) inline private
Definition at line 72 of file PndFieldMapData.h.
View newest version in sPHENIX GitHub at line 72 of file PndFieldMapData.h
Member Data Documentation
TArrayF* PndFieldMapData::fBx private
Arrays with the field values in T
Definition at line 93 of file PndFieldMapData.h.
View newest version in sPHENIX GitHub at line 93 of file PndFieldMapData.h
Referenced by GetBx(), PndFieldMapData(), and ~PndFieldMapData().
TArrayF* PndFieldMapData::fBy private
Definition at line 94 of file PndFieldMapData.h.
View newest version in sPHENIX GitHub at line 94 of file PndFieldMapData.h
Referenced by GetBy(), PndFieldMapData(), and ~PndFieldMapData().
TArrayF* PndFieldMapData::fBz private
Definition at line 95 of file PndFieldMapData.h.
View newest version in sPHENIX GitHub at line 95 of file PndFieldMapData.h
Referenced by GetBz(), PndFieldMapData(), and ~PndFieldMapData().
Int_t PndFieldMapData::fNx private
Number of grid points
Definition at line 89 of file PndFieldMapData.h.
View newest version in sPHENIX GitHub at line 89 of file PndFieldMapData.h
Referenced by GetNx(), and PndFieldMapData().
Int_t PndFieldMapData::fNy private
Definition at line 89 of file PndFieldMapData.h.
View newest version in sPHENIX GitHub at line 89 of file PndFieldMapData.h
Referenced by GetNy(), and PndFieldMapData().
Int_t PndFieldMapData::fNz private
Definition at line 89 of file PndFieldMapData.h.
View newest version in sPHENIX GitHub at line 89 of file PndFieldMapData.h
Referenced by GetNz(), and PndFieldMapData().
Int_t PndFieldMapData::fType private
Type of map. 1 = PndFieldMap, 2 = Sym2, 3 = Sym3
Definition at line 72 of file PndFieldMapData.h.
View newest version in sPHENIX GitHub at line 72 of file PndFieldMapData.h
Referenced by GetType().
Double_t PndFieldMapData::fUnit private
Original units of the map
Definition at line 85 of file PndFieldMapData.h.
View newest version in sPHENIX GitHub at line 85 of file PndFieldMapData.h
Double_t PndFieldMapData::fXmax private
Definition at line 80 of file PndFieldMapData.h.
View newest version in sPHENIX GitHub at line 80 of file PndFieldMapData.h
Referenced by GetXmax().
Double_t PndFieldMapData::fXmin private
Field limits in local coordinate system
Definition at line 80 of file PndFieldMapData.h.
View newest version in sPHENIX GitHub at line 80 of file PndFieldMapData.h
Referenced by GetXmin().
Double_t PndFieldMapData::fYmax private
Definition at line 81 of file PndFieldMapData.h.
View newest version in sPHENIX GitHub at line 81 of file PndFieldMapData.h
Referenced by GetYmax().
Double_t PndFieldMapData::fYmin private
Definition at line 81 of file PndFieldMapData.h.
View newest version in sPHENIX GitHub at line 81 of file PndFieldMapData.h
Referenced by GetYmin().
Double_t PndFieldMapData::fZmax private
Definition at line 82 of file PndFieldMapData.h.
View newest version in sPHENIX GitHub at line 82 of file PndFieldMapData.h
Referenced by GetZmax().
Double_t PndFieldMapData::fZmin private
Definition at line 82 of file PndFieldMapData.h.
View newest version in sPHENIX GitHub at line 82 of file PndFieldMapData.h
Referenced by GetZmin().
The documentation for this class was generated from the following files:
EicRoot/blob/master/field/PndFieldMapData.h
EicRoot/blob/master/field/PndFieldMapData.cxx