EIC Software: eASTVDetectorComponent Class Reference
eASTVDetectorComponent Class Reference abstract
#include <east/blob/main/Components/Base/include/eASTVDetectorComponent.hh>
Public Member Functions
eASTVDetectorComponent (G4String compName, G4int vl=0)
virtual ~eASTVDetectorComponent ()
virtual void SetUp ()=0
virtual void Construct (G4VPhysicalVolume *)=0
virtual void ConstructActionForMaster ()
virtual void ConstructSD ()
virtual void ConstructActions ()
void SetUpBase (G4int vl=0)
virtual G4VPhysicalVolume * GetEnvelope ()
virtual G4Region * GetRegion ()
void SetLocation (G4ThreeVector pos)
void SetRotation (G4String ax, G4double ang)
G4ThreeVector GetLocation ()
G4RotationMatrix GetRotation ()
Protected Member Functions
void Locate (G4LogicalVolume *compLogVol, G4VPhysicalVolume *worldPhys)
G4String LocateDataFile (const G4String fn) const
Utility method to locate data files in the MacroSearchPath.
void RegisterUserAction (G4UserRunAction *)
void RegisterUserAction (G4UserEventAction *)
void RegisterUserAction (G4UserStackingAction *)
void RegisterUserAction (G4UserTrackingAction *)
void RegisterUserAction (G4UserSteppingAction *)
void ReadMaterialFile (G4String)
Protected Attributes
G4String componentName
G4String commandDir
G4int verboseLevel
G4VPhysicalVolume * pEnvelopePhys = nullptr
G4Region * pRegion = nullptr
Private Member Functions
G4bool CheckRegion ()
Private Attributes
eASTDetectorComponentMessenger * baseMessenger
eASTUserActionDispatcher * userActionDispatcher
G4ThreeVector fPosition
G4RotationMatrix fRotation
Detailed Description
Definition at line 30 of file eASTVDetectorComponent.hh.
View newest version in sPHENIX GitHub at line 30 of file eASTVDetectorComponent.hh
Constructor & Destructor Documentation
eASTVDetectorComponent::eASTVDetectorComponent (G4String compName, G4int vl = 0)
Definition at line 23 of file eASTVDetectorComponent.cc.
View newest version in sPHENIX GitHub at line 23 of file eASTVDetectorComponent.cc
References baseMessenger, commandDir, eASTUserActionDispatcher::Instance(), and userActionDispatcher.
eASTVDetectorComponent::~eASTVDetectorComponent () virtual
Definition at line 31 of file eASTVDetectorComponent.cc.
View newest version in sPHENIX GitHub at line 31 of file eASTVDetectorComponent.cc
References baseMessenger.
Member Function Documentation
G4bool eASTVDetectorComponent::CheckRegion () private
Definition at line 120 of file eASTVDetectorComponent.cc.
View newest version in sPHENIX GitHub at line 120 of file eASTVDetectorComponent.cc
References componentName, and pRegion.
Referenced by RegisterUserAction().
virtual void eASTVDetectorComponent::Construct (G4VPhysicalVolume *) pure virtual
Implemented in eASTDetectorComponentGDML, eASTBeamPipe, and eASTSupportStructure.
Referenced by eASTDetectorConstruction::Construct().
virtual void eASTVDetectorComponent::ConstructActionForMaster () inline virtual
Definition at line 40 of file eASTVDetectorComponent.hh.
View newest version in sPHENIX GitHub at line 40 of file eASTVDetectorComponent.hh
Referenced by eASTDetectorConstruction::Construct().
virtual void eASTVDetectorComponent::ConstructActions () inline virtual
Definition at line 46 of file eASTVDetectorComponent.hh.
View newest version in sPHENIX GitHub at line 46 of file eASTVDetectorComponent.hh
Referenced by eASTDetectorConstruction::ConstructSDandField().
virtual void eASTVDetectorComponent::ConstructSD () inline virtual
Definition at line 44 of file eASTVDetectorComponent.hh.
View newest version in sPHENIX GitHub at line 44 of file eASTVDetectorComponent.hh
Referenced by eASTDetectorConstruction::ConstructSDandField().
virtual G4VPhysicalVolume* eASTVDetectorComponent::GetEnvelope () inline virtual
Definition at line 86 of file eASTVDetectorComponent.hh.
View newest version in sPHENIX GitHub at line 86 of file eASTVDetectorComponent.hh
References pEnvelopePhys.
G4ThreeVector eASTVDetectorComponent::GetLocation () inline
Definition at line 108 of file eASTVDetectorComponent.hh.
View newest version in sPHENIX GitHub at line 108 of file eASTVDetectorComponent.hh
References fPosition.
Referenced by eASTDetectorComponentGDML::Construct(), and eASTSupportStructure::Construct().
virtual G4Region* eASTVDetectorComponent::GetRegion () inline virtual
Definition at line 88 of file eASTVDetectorComponent.hh.
View newest version in sPHENIX GitHub at line 88 of file eASTVDetectorComponent.hh
References pRegion.
G4RotationMatrix eASTVDetectorComponent::GetRotation () inline
Definition at line 110 of file eASTVDetectorComponent.hh.
View newest version in sPHENIX GitHub at line 110 of file eASTVDetectorComponent.hh
References fRotation.
Referenced by eASTDetectorComponentGDML::Construct(), and eASTSupportStructure::Construct().
void eASTVDetectorComponent::Locate (G4LogicalVolume * compLogVol, G4VPhysicalVolume * worldPhys) protected
Definition at line 42 of file eASTVDetectorComponent.cc.
View newest version in sPHENIX GitHub at line 42 of file eASTVDetectorComponent.cc
References componentName, fPosition, fRotation, and pEnvelopePhys.
Referenced by eASTBeamPipe::Construct().
G4String eASTVDetectorComponent::LocateDataFile (const G4String fn) const protected
Utility method to locate data files in the MacroSearchPath.
Definition at line 49 of file eASTVDetectorComponent.cc.
View newest version in sPHENIX GitHub at line 49 of file eASTVDetectorComponent.cc
References verboseLevel.
Referenced by eASTBeamPipe::SetEnvGDML(), eASTDetectorComponentGDML::SetGDML(), eASTSupportStructure::SetGDML(), eASTBeamPipe::SetGDML(), eASTDetectorComponentGDML::SetMatFile(), eASTSupportStructure::SetMatFile(), and eASTBeamPipe::SetMatFile().
void eASTVDetectorComponent::ReadMaterialFile (G4String fileName) protected
Definition at line 67 of file eASTVDetectorComponent.cc.
View newest version in sPHENIX GitHub at line 67 of file eASTVDetectorComponent.cc
References in, and verboseLevel.
Referenced by eASTDetectorComponentGDML::Construct(), eASTSupportStructure::Construct(), and eASTBeamPipe::Construct().
void eASTVDetectorComponent::RegisterUserAction (G4UserRunAction * ua) protected
Definition at line 105 of file eASTVDetectorComponent.cc.
View newest version in sPHENIX GitHub at line 105 of file eASTVDetectorComponent.cc
References CheckRegion(), pRegion, eASTUserActionDispatcher::RegisterUserAction(), and userActionDispatcher.
void eASTVDetectorComponent::RegisterUserAction (G4UserEventAction * ua) protected
Definition at line 108 of file eASTVDetectorComponent.cc.
View newest version in sPHENIX GitHub at line 108 of file eASTVDetectorComponent.cc
References CheckRegion(), pRegion, eASTUserActionDispatcher::RegisterUserAction(), and userActionDispatcher.
void eASTVDetectorComponent::RegisterUserAction (G4UserStackingAction * ua) protected
Definition at line 111 of file eASTVDetectorComponent.cc.
View newest version in sPHENIX GitHub at line 111 of file eASTVDetectorComponent.cc
References CheckRegion(), pRegion, eASTUserActionDispatcher::RegisterUserAction(), and userActionDispatcher.
void eASTVDetectorComponent::RegisterUserAction (G4UserTrackingAction * ua) protected
Definition at line 114 of file eASTVDetectorComponent.cc.
View newest version in sPHENIX GitHub at line 114 of file eASTVDetectorComponent.cc
References CheckRegion(), pRegion, eASTUserActionDispatcher::RegisterUserAction(), and userActionDispatcher.
void eASTVDetectorComponent::RegisterUserAction (G4UserSteppingAction * ua) protected
Definition at line 117 of file eASTVDetectorComponent.cc.
View newest version in sPHENIX GitHub at line 117 of file eASTVDetectorComponent.cc
References CheckRegion(), and pRegion.
void eASTVDetectorComponent::SetLocation (G4ThreeVector pos) inline
Definition at line 100 of file eASTVDetectorComponent.hh.
View newest version in sPHENIX GitHub at line 100 of file eASTVDetectorComponent.hh
References fPosition, and pos().
Referenced by eASTDetectorComponentMessenger::SetNewValue().
void eASTVDetectorComponent::SetRotation (G4String ax, G4double ang) inline
Definition at line 102 of file eASTVDetectorComponent.hh.
View newest version in sPHENIX GitHub at line 102 of file eASTVDetectorComponent.hh
References fRotation.
Referenced by eASTDetectorComponentMessenger::SetNewValue().
virtual void eASTVDetectorComponent::SetUp () pure virtual
Implemented in eASTDetectorComponentGDML, eASTBeamPipe, and eASTSupportStructure.
Referenced by SetUpBase().
void eASTVDetectorComponent::SetUpBase (G4int vl = 0)
Definition at line 34 of file eASTVDetectorComponent.cc.
View newest version in sPHENIX GitHub at line 34 of file eASTVDetectorComponent.cc
References baseMessenger, commandDir, componentName, eASTDetectorConstruction::Instance(), eASTDetectorConstruction::RegisterComponent(), SetUp(), eASTDetectorComponentMessenger::SetUpBaseCommands(), and verboseLevel.
Referenced by eASTDetectorComponentMessenger::SetNewValue().
Member Data Documentation
eASTDetectorComponentMessenger* eASTVDetectorComponent::baseMessenger private
Definition at line 92 of file eASTVDetectorComponent.hh.
View newest version in sPHENIX GitHub at line 92 of file eASTVDetectorComponent.hh
Referenced by eASTVDetectorComponent(), SetUpBase(), and ~eASTVDetectorComponent().
G4String eASTVDetectorComponent::commandDir protected
Definition at line 77 of file eASTVDetectorComponent.hh.
View newest version in sPHENIX GitHub at line 77 of file eASTVDetectorComponent.hh
Referenced by eASTVDetectorComponent(), eASTSupportStructure::SetUp(), eASTBeamPipe::SetUp(), eASTDetectorComponentGDML::SetUp(), and SetUpBase().
G4String eASTVDetectorComponent::componentName protected
Definition at line 76 of file eASTVDetectorComponent.hh.
View newest version in sPHENIX GitHub at line 76 of file eASTVDetectorComponent.hh
Referenced by CheckRegion(), eASTDetectorComponentGDML::Construct(), eASTBeamPipe::Construct(), eASTSupportStructure::Construct(), Locate(), and SetUpBase().
G4ThreeVector eASTVDetectorComponent::fPosition private
Definition at line 96 of file eASTVDetectorComponent.hh.
View newest version in sPHENIX GitHub at line 96 of file eASTVDetectorComponent.hh
Referenced by GetLocation(), Locate(), and SetLocation().
G4RotationMatrix eASTVDetectorComponent::fRotation private
Definition at line 97 of file eASTVDetectorComponent.hh.
View newest version in sPHENIX GitHub at line 97 of file eASTVDetectorComponent.hh
Referenced by GetRotation(), Locate(), and SetRotation().
G4VPhysicalVolume* eASTVDetectorComponent::pEnvelopePhys = nullptr protected
Definition at line 79 of file eASTVDetectorComponent.hh.
View newest version in sPHENIX GitHub at line 79 of file eASTVDetectorComponent.hh
Referenced by GetEnvelope(), and Locate().
G4Region* eASTVDetectorComponent::pRegion = nullptr protected
Definition at line 80 of file eASTVDetectorComponent.hh.
View newest version in sPHENIX GitHub at line 80 of file eASTVDetectorComponent.hh
Referenced by CheckRegion(), eASTDetectorComponentGDML::Construct(), eASTBeamPipe::Construct(), eASTSupportStructure::Construct(), GetRegion(), and RegisterUserAction().
eASTUserActionDispatcher* eASTVDetectorComponent::userActionDispatcher private
Definition at line 93 of file eASTVDetectorComponent.hh.
View newest version in sPHENIX GitHub at line 93 of file eASTVDetectorComponent.hh
Referenced by eASTVDetectorComponent(), and RegisterUserAction().
G4int eASTVDetectorComponent::verboseLevel protected
Definition at line 78 of file eASTVDetectorComponent.hh.
View newest version in sPHENIX GitHub at line 78 of file eASTVDetectorComponent.hh
Referenced by LocateDataFile(), ReadMaterialFile(), and SetUpBase().
The documentation for this class was generated from the following files:
east/blob/main/Components/Base/include/eASTVDetectorComponent.hh
east/blob/main/Components/Base/src/eASTVDetectorComponent.cc