EIC Software: FW::EffPlotTool Class Reference
FW::EffPlotTool Class Reference
#include <fun4all_acts/blob/master/Examples/Framework/include/ACTFW/Validation/EffPlotTool.hpp>
Classes
struct Config
The nested configuration struct.
struct EffPlotCache
Nested Cache struct.
Public Member Functions
EffPlotTool (const Config &cfg, Acts::Logging::Level lvl)
void book (EffPlotCache &effPlotCache) const
book the efficiency plots
void fill (EffPlotCache &effPlotCache, const ActsFatras::Particle &truthParticle, bool status) const
fill efficiency plots
void write (const EffPlotCache &effPlotCache) const
write the efficiency plots to file
void clear (EffPlotCache &effPlotCache) const
delete the efficiency plots
Private Member Functions
const Acts::Logger & logger () const
The logger.
Private Attributes
Config m_cfg
The Config class.
std::unique_ptr< const
Acts::Logger > m_logger
The logging instance.
Detailed Description
Definition at line 24 of file EffPlotTool.hpp.
View newest version in sPHENIX GitHub at line 24 of file EffPlotTool.hpp
Constructor & Destructor Documentation
FW::EffPlotTool::EffPlotTool (const Config & cfg, Acts::Logging::Level lvl)
Constructor
Parameters
cfg Configuration struct
lvl Message level declaration
Definition at line 17 of file EffPlotTool.cpp.
View newest version in sPHENIX GitHub at line 17 of file EffPlotTool.cpp
Member Function Documentation
void FW::EffPlotTool::book (EffPlotTool::EffPlotCache & effPlotCache) const
book the efficiency plots
Parameters
effPlotCache the cache for efficiency plots
Definition at line 21 of file EffPlotTool.cpp.
View newest version in sPHENIX GitHub at line 21 of file EffPlotTool.cpp
References ACTS_DEBUG, FW::PlotHelpers::bookEff(), FW::EffPlotTool::EffPlotCache::trackeff_vs_eta, FW::EffPlotTool::EffPlotCache::trackeff_vs_phi, and FW::EffPlotTool::EffPlotCache::trackeff_vs_pT.
Referenced by FW::TrackFitterPerformanceWriter::TrackFitterPerformanceWriter().
void FW::EffPlotTool::clear (EffPlotCache & effPlotCache) const
delete the efficiency plots
Parameters
effPlotCache cache object for efficiency plots
Definition at line 37 of file EffPlotTool.cpp.
View newest version in sPHENIX GitHub at line 37 of file EffPlotTool.cpp
References FW::EffPlotTool::EffPlotCache::trackeff_vs_eta, FW::EffPlotTool::EffPlotCache::trackeff_vs_phi, and FW::EffPlotTool::EffPlotCache::trackeff_vs_pT.
void FW::EffPlotTool::fill (EffPlotTool::EffPlotCache & effPlotCache, const ActsFatras::Particle & truthParticle, bool status) const
fill efficiency plots
Parameters
effPlotCache cache object for efficiency plots
truthParticle the truth Particle
status the reconstruction status
Definition at line 51 of file EffPlotTool.cpp.
View newest version in sPHENIX GitHub at line 51 of file EffPlotTool.cpp
References Acts::VectorHelpers::eta(), FW::PlotHelpers::fillEff(), phi, FW::EffPlotTool::EffPlotCache::trackeff_vs_eta, FW::EffPlotTool::EffPlotCache::trackeff_vs_phi, FW::EffPlotTool::EffPlotCache::trackeff_vs_pT, ActsFatras::Particle::transverseMomentum(), and ActsFatras::Particle::unitDirection().
const Acts::Logger& FW::EffPlotTool::logger () const inline private
The logger.
Definition at line 72 of file EffPlotTool.hpp.
View newest version in sPHENIX GitHub at line 72 of file EffPlotTool.hpp
References m_logger.
void FW::EffPlotTool::write (const EffPlotCache & effPlotCache) const
write the efficiency plots to file
Parameters
effPlotCache cache object for efficiency plots
Definition at line 43 of file EffPlotTool.cpp.
View newest version in sPHENIX GitHub at line 43 of file EffPlotTool.cpp
References ACTS_DEBUG, FW::EffPlotTool::EffPlotCache::trackeff_vs_eta, FW::EffPlotTool::EffPlotCache::trackeff_vs_phi, and FW::EffPlotTool::EffPlotCache::trackeff_vs_pT.
Member Data Documentation
Config FW::EffPlotTool::m_cfg private
The Config class.
Definition at line 68 of file EffPlotTool.hpp.
View newest version in sPHENIX GitHub at line 68 of file EffPlotTool.hpp
std::unique_ptr<const Acts::Logger> FW::EffPlotTool::m_logger private
The logging instance.
Definition at line 69 of file EffPlotTool.hpp.
View newest version in sPHENIX GitHub at line 69 of file EffPlotTool.hpp
Referenced by logger().
The documentation for this class was generated from the following files:
fun4all_acts/blob/master/Examples/Framework/include/ACTFW/Validation/EffPlotTool.hpp
fun4all_acts/blob/master/Examples/Framework/src/Validation/EffPlotTool.cpp