EIC Software: PndRecoMultiKalmanTask Class Reference
PndRecoMultiKalmanTask Class Reference
#include <EicRoot/blob/master/GenfitTools/recotasks/PndRecoMultiKalmanTask.h>
Public Member Functions
PndRecoMultiKalmanTask (const char *name="Genfit", Int_t iVerbose=0)
~PndRecoMultiKalmanTask ()
void SetTrackInBranchName (const TString &name)
void SetTrackOutBranchName (const TString &name)
void SetMvdBranchName (const TString &name)
void SetCentralTrackerBranchName (const TString &name)
void SetPersistence (Bool_t opt=kTRUE)
void SetGeane (Bool_t opt=kTRUE)
void SetNumIterations (Int_t num)
virtual InitStatus Init ()
virtual void Exec (Option_t *opt)
void SetParContainers ()
Public Member Functions inherited from FairTask
FairTask ()
FairTask (const char *name, Int_t iVerbose=1)
virtual ~FairTask ()
void InitTask ()
void ReInitTask ()
void SetParTask ()
virtual void FinishTask ()
virtual void FinishEvent ()
void SetVerbose (Int_t iVerbose)
void SetInputPersistance (Bool_t val)
void CheckInputPersistance (TString branchName)
Private Member Functions
ClassDef (PndRecoMultiKalmanTask, 1)
Number of iterations.
Private Attributes
TClonesArray * fTrackArray
TClonesArray * fFitTrackArrayElectron
TClonesArray * fFitTrackArrayMuon
Output TCA for track.
TClonesArray * fFitTrackArrayPion
Output TCA for track.
TClonesArray * fFitTrackArrayKaon
Output TCA for track.
TClonesArray * fFitTrackArrayProton
Output TCA for track.
TString fTrackInBranchName
Output TCA for track.
TString fTrackOutBranchName
Name of the input TCA.
TString fMvdBranchName
Name of the output TCA.
TString fCentralTrackerBranchName
Name of the TCA for MVD.
PndRecoKalmanFit * fFitter
Name of the TCA for central tracker.
Bool_t fPersistence
Bool_t fUseGeane
Bool_t fSmoothing
Flag to use Geane.
Int_t fNumIt
Flag to set on smoothing.
Additional Inherited Members
Protected Member Functions inherited from FairTask
virtual InitStatus ReInit ()
virtual void Finish ()
void InitTasks ()
void ReInitTasks ()
void SetParTasks ()
void FinishTasks ()
void FinishEvents ()
Protected Attributes inherited from FairTask
Int_t fVerbose
Int_t fInputPersistance
Indicates if input branch is persistant.
FairLogger * fLogger
Detailed Description
Definition at line 34 of file PndRecoMultiKalmanTask.h.
View newest version in sPHENIX GitHub at line 34 of file PndRecoMultiKalmanTask.h
Constructor & Destructor Documentation
PndRecoMultiKalmanTask::PndRecoMultiKalmanTask (const char * name = "Genfit", Int_t iVerbose = 0)
Definition at line 35 of file PndRecoMultiKalmanTask.cxx.
View newest version in sPHENIX GitHub at line 35 of file PndRecoMultiKalmanTask.cxx
References fCentralTrackerBranchName, fFitter, fFitTrackArrayElectron, fFitTrackArrayKaon, fFitTrackArrayMuon, fFitTrackArrayPion, fFitTrackArrayProton, fMvdBranchName, fNumIt, fTrackInBranchName, fTrackOutBranchName, and fUseGeane.
PndRecoMultiKalmanTask::~PndRecoMultiKalmanTask ()
Definition at line 53 of file PndRecoMultiKalmanTask.cxx.
View newest version in sPHENIX GitHub at line 53 of file PndRecoMultiKalmanTask.cxx
Member Function Documentation
PndRecoMultiKalmanTask::ClassDef (PndRecoMultiKalmanTask , 1) private
Number of iterations.
void PndRecoMultiKalmanTask::Exec (Option_t * opt) virtual
Definition at line 100 of file PndRecoMultiKalmanTask.cxx.
View newest version in sPHENIX GitHub at line 100 of file PndRecoMultiKalmanTask.cxx
References fFitter, fFitTrackArrayElectron, fFitTrackArrayKaon, fFitTrackArrayMuon, fFitTrackArrayPion, fFitTrackArrayProton, PndRecoKalmanFit::Fit(), fTrackArray, FairTask::fVerbose, PndTrack::GetChi2(), PndTrack::GetFlag(), PndTrack::GetNDF(), PndTrack::GetParamFirst(), PndTrack::GetParamLast(), PndTrack::GetPidHypo(), FairTrackPar::GetQ(), PndTrack::GetTrackCand(), and kLheTrack.
InitStatus PndRecoMultiKalmanTask::Init (void) virtual
Intialisation at begin of run. To be implemented in the derived class. Success If not kSUCCESS, task will be set inactive.
Reimplemented from FairTask.
Definition at line 58 of file PndRecoMultiKalmanTask.cxx.
View newest version in sPHENIX GitHub at line 58 of file PndRecoMultiKalmanTask.cxx
References fCentralTrackerBranchName, fFitter, fFitTrackArrayElectron, fFitTrackArrayKaon, fFitTrackArrayMuon, fFitTrackArrayPion, fFitTrackArrayProton, fMvdBranchName, fNumIt, fTrackArray, fTrackInBranchName, fTrackOutBranchName, fUseGeane, FairRootManager::GetObject(), PndRecoKalmanFit::Init(), FairRootManager::Instance(), kERROR, kFATAL, kSUCCESS, FairRootManager::Register(), PndRecoKalmanFit::SetCentralTrackerBranchName(), PndRecoKalmanFit::SetGeane(), PndRecoKalmanFit::SetMvdBranchName(), and PndRecoKalmanFit::SetNumIterations().
void PndRecoMultiKalmanTask::SetCentralTrackerBranchName (const TString & name) inline
Definition at line 50 of file PndRecoMultiKalmanTask.h.
View newest version in sPHENIX GitHub at line 50 of file PndRecoMultiKalmanTask.h
References fCentralTrackerBranchName, and name.
void PndRecoMultiKalmanTask::SetGeane (Bool_t opt = kTRUE) inline
Definition at line 52 of file PndRecoMultiKalmanTask.h.
View newest version in sPHENIX GitHub at line 52 of file PndRecoMultiKalmanTask.h
References fUseGeane.
void PndRecoMultiKalmanTask::SetMvdBranchName (const TString & name) inline
Definition at line 49 of file PndRecoMultiKalmanTask.h.
View newest version in sPHENIX GitHub at line 49 of file PndRecoMultiKalmanTask.h
References fMvdBranchName, and name.
void PndRecoMultiKalmanTask::SetNumIterations (Int_t num) inline
Definition at line 53 of file PndRecoMultiKalmanTask.h.
View newest version in sPHENIX GitHub at line 53 of file PndRecoMultiKalmanTask.h
References fNumIt, and num.
void PndRecoMultiKalmanTask::SetParContainers () virtual
Intialise parameter containers. To be implemented in the derived class.
Reimplemented from FairTask.
Definition at line 92 of file PndRecoMultiKalmanTask.cxx.
View newest version in sPHENIX GitHub at line 92 of file PndRecoMultiKalmanTask.cxx
References FairRuntimeDb::getContainer(), FairRun::GetRuntimeDb(), and FairRunAna::Instance().
void PndRecoMultiKalmanTask::SetPersistence (Bool_t opt = kTRUE) inline
Definition at line 51 of file PndRecoMultiKalmanTask.h.
View newest version in sPHENIX GitHub at line 51 of file PndRecoMultiKalmanTask.h
References fPersistence.
void PndRecoMultiKalmanTask::SetTrackInBranchName (const TString & name) inline
Definition at line 47 of file PndRecoMultiKalmanTask.h.
View newest version in sPHENIX GitHub at line 47 of file PndRecoMultiKalmanTask.h
References fTrackInBranchName, and name.
void PndRecoMultiKalmanTask::SetTrackOutBranchName (const TString & name) inline
Definition at line 48 of file PndRecoMultiKalmanTask.h.
View newest version in sPHENIX GitHub at line 48 of file PndRecoMultiKalmanTask.h
References fTrackOutBranchName, and name.
Member Data Documentation
TString PndRecoMultiKalmanTask::fCentralTrackerBranchName private
Name of the TCA for MVD.
Definition at line 75 of file PndRecoMultiKalmanTask.h.
View newest version in sPHENIX GitHub at line 75 of file PndRecoMultiKalmanTask.h
Referenced by Init(), PndRecoMultiKalmanTask(), and SetCentralTrackerBranchName().
PndRecoKalmanFit* PndRecoMultiKalmanTask::fFitter private
Name of the TCA for central tracker.
Definition at line 77 of file PndRecoMultiKalmanTask.h.
View newest version in sPHENIX GitHub at line 77 of file PndRecoMultiKalmanTask.h
Referenced by Exec(), Init(), and PndRecoMultiKalmanTask().
TClonesArray* PndRecoMultiKalmanTask::fFitTrackArrayElectron private
Definition at line 65 of file PndRecoMultiKalmanTask.h.
View newest version in sPHENIX GitHub at line 65 of file PndRecoMultiKalmanTask.h
Referenced by Exec(), Init(), and PndRecoMultiKalmanTask().
TClonesArray* PndRecoMultiKalmanTask::fFitTrackArrayKaon private
Output TCA for track.
Definition at line 68 of file PndRecoMultiKalmanTask.h.
View newest version in sPHENIX GitHub at line 68 of file PndRecoMultiKalmanTask.h
Referenced by Exec(), Init(), and PndRecoMultiKalmanTask().
TClonesArray* PndRecoMultiKalmanTask::fFitTrackArrayMuon private
Output TCA for track.
Definition at line 66 of file PndRecoMultiKalmanTask.h.
View newest version in sPHENIX GitHub at line 66 of file PndRecoMultiKalmanTask.h
Referenced by Exec(), Init(), and PndRecoMultiKalmanTask().
TClonesArray* PndRecoMultiKalmanTask::fFitTrackArrayPion private
Output TCA for track.
Definition at line 67 of file PndRecoMultiKalmanTask.h.
View newest version in sPHENIX GitHub at line 67 of file PndRecoMultiKalmanTask.h
Referenced by Exec(), Init(), and PndRecoMultiKalmanTask().
TClonesArray* PndRecoMultiKalmanTask::fFitTrackArrayProton private
Output TCA for track.
Definition at line 69 of file PndRecoMultiKalmanTask.h.
View newest version in sPHENIX GitHub at line 69 of file PndRecoMultiKalmanTask.h
Referenced by Exec(), Init(), and PndRecoMultiKalmanTask().
TString PndRecoMultiKalmanTask::fMvdBranchName private
Name of the output TCA.
Definition at line 74 of file PndRecoMultiKalmanTask.h.
View newest version in sPHENIX GitHub at line 74 of file PndRecoMultiKalmanTask.h
Referenced by Init(), PndRecoMultiKalmanTask(), and SetMvdBranchName().
Int_t PndRecoMultiKalmanTask::fNumIt private
Flag to set on smoothing.
Definition at line 83 of file PndRecoMultiKalmanTask.h.
View newest version in sPHENIX GitHub at line 83 of file PndRecoMultiKalmanTask.h
Referenced by Init(), PndRecoMultiKalmanTask(), and SetNumIterations().
Bool_t PndRecoMultiKalmanTask::fPersistence private
Definition at line 79 of file PndRecoMultiKalmanTask.h.
View newest version in sPHENIX GitHub at line 79 of file PndRecoMultiKalmanTask.h
Referenced by SetPersistence().
Bool_t PndRecoMultiKalmanTask::fSmoothing private
Flag to use Geane.
Definition at line 82 of file PndRecoMultiKalmanTask.h.
View newest version in sPHENIX GitHub at line 82 of file PndRecoMultiKalmanTask.h
TClonesArray* PndRecoMultiKalmanTask::fTrackArray private
Definition at line 64 of file PndRecoMultiKalmanTask.h.
View newest version in sPHENIX GitHub at line 64 of file PndRecoMultiKalmanTask.h
Referenced by Exec(), and Init().
TString PndRecoMultiKalmanTask::fTrackInBranchName private
Output TCA for track.
Definition at line 71 of file PndRecoMultiKalmanTask.h.
View newest version in sPHENIX GitHub at line 71 of file PndRecoMultiKalmanTask.h
Referenced by Init(), PndRecoMultiKalmanTask(), and SetTrackInBranchName().
TString PndRecoMultiKalmanTask::fTrackOutBranchName private
Name of the input TCA.
Definition at line 72 of file PndRecoMultiKalmanTask.h.
View newest version in sPHENIX GitHub at line 72 of file PndRecoMultiKalmanTask.h
Referenced by Init(), PndRecoMultiKalmanTask(), and SetTrackOutBranchName().
Bool_t PndRecoMultiKalmanTask::fUseGeane private
Definition at line 81 of file PndRecoMultiKalmanTask.h.
View newest version in sPHENIX GitHub at line 81 of file PndRecoMultiKalmanTask.h
Referenced by Init(), PndRecoMultiKalmanTask(), and SetGeane().
The documentation for this class was generated from the following files:
EicRoot/blob/master/GenfitTools/recotasks/PndRecoMultiKalmanTask.h
EicRoot/blob/master/GenfitTools/recotasks/PndRecoMultiKalmanTask.cxx