EIC Software: FairDbValidityRecBuilder Class Reference
FairDbValidityRecBuilder Class Reference
#include <EicRoot/blob/master/dbase/dbInterface/FairDbValidityRecBuilder.h>
Public Types
enum { kMAX_AGGREGATE_NO = 1000 }
Public Member Functions
FairDbValidityRecBuilder (const FairDbProxy &proxy, const ValContext &vc, const FairDb::Task &task, Int_t selectDbNo=-1, Bool_t findFullTimeWindow=true)
FairDbValidityRecBuilder (const FairDbProxy &proxy, const string &context, const FairDb::Task &task)
FairDbValidityRecBuilder (const FairDbValidityRec &vr, const std::string tableName)
virtual ~FairDbValidityRecBuilder ()
std::string GetL2CacheName () const
FairDb::Task GetTask () const
UInt_t GetNumValidityRec () const
Int_t IndexOfAggno (Int_t aggNo) const
Get index of AggNo or -1 if missing.
Bool_t IsExtendedContext () const
const FairDbValidityRec & GetValidityRec (Int_t rowNo) const
const FairDbValidityRec & GetValidityRecFromAggNo (Int_t aggNo) const
const FairDbValidityRec & GetValidityRecFromSeqNo (UInt_t SeqNo) const
Bool_t NonAggregated () const
Private Member Functions
UInt_t AddNewAgg (const FairDbValidityRec &vrec, Int_t aggNo)
UInt_t AddNewGap (Int_t aggNo)
void MakeGapRec (const ValContext &vc, const string &tableName, Bool_t findFullTimeWindow=true)
Private Attributes
FairDbValidityRec fGap
Bool_t fIsExtendedContext
FairDb::Task fTask
std::vector< FairDbValidityRec > fVRecs
std::map< Int_t, UInt_t > fAggNoToIndex
Detailed Description
Definition at line 14 of file FairDbValidityRecBuilder.h.
View newest version in sPHENIX GitHub at line 14 of file FairDbValidityRecBuilder.h
Member Enumeration Documentation
anonymous enum
Enumerator:
kMAX_AGGREGATE_NO
Definition at line 22 of file FairDbValidityRecBuilder.h.
View newest version in sPHENIX GitHub at line 22 of file FairDbValidityRecBuilder.h
Constructor & Destructor Documentation
FairDbValidityRecBuilder::FairDbValidityRecBuilder (const FairDbProxy & proxy, const ValContext & vc, const FairDb::Task & task, Int_t selectDbNo = -1, Bool_t findFullTimeWindow = true)
FairDbValidityRecBuilder::FairDbValidityRecBuilder (const FairDbProxy & proxy, const string & context, const FairDb::Task & task)
Definition at line 214 of file FairDbValidityRecBuilder.cxx.
View newest version in sPHENIX GitHub at line 214 of file FairDbValidityRecBuilder.cxx
References AddNewGap(), fAggNoToIndex, fGap, fTask, fVRecs, FairDbValidityRec::GetAggregateNo(), FairDbProxy::GetNumDb(), FairDbResultNonAgg::GetNumRows(), GetNumValidityRec(), FairDbProxy::GetTableName(), FairDbResultNonAgg::GetTableRow(), GetValidityRec(), FairDbProxy::QueryValidity(), and FairDbProxy::TableExists().
FairDbValidityRecBuilder::FairDbValidityRecBuilder (const FairDbValidityRec & vr, const std::string tableName)
Definition at line 307 of file FairDbValidityRecBuilder.cxx.
View newest version in sPHENIX GitHub at line 307 of file FairDbValidityRecBuilder.cxx
References AddNewAgg(), FairDbValidityRec::GetAggregateNo(), FairDbValidityRec::GetValRange(), and MakeGapRec().
FairDbValidityRecBuilder::~FairDbValidityRecBuilder () virtual
Definition at line 327 of file FairDbValidityRecBuilder.cxx.
View newest version in sPHENIX GitHub at line 327 of file FairDbValidityRecBuilder.cxx
Member Function Documentation
UInt_t FairDbValidityRecBuilder::AddNewAgg (const FairDbValidityRec & vrec, Int_t aggNo) private
Definition at line 366 of file FairDbValidityRecBuilder.cxx.
View newest version in sPHENIX GitHub at line 366 of file FairDbValidityRecBuilder.cxx
References fAggNoToIndex, fVRecs, and IndexOfAggno().
Referenced by AddNewGap(), and FairDbValidityRecBuilder().
UInt_t FairDbValidityRecBuilder::AddNewGap (Int_t aggNo) private
Definition at line 383 of file FairDbValidityRecBuilder.cxx.
View newest version in sPHENIX GitHub at line 383 of file FairDbValidityRecBuilder.cxx
References AddNewAgg(), fGap, and fVRecs.
Referenced by FairDbValidityRecBuilder().
std::string FairDbValidityRecBuilder::GetL2CacheName () const
Definition at line 333 of file FairDbValidityRecBuilder.cxx.
View newest version in sPHENIX GitHub at line 333 of file FairDbValidityRecBuilder.cxx
References fVRecs, FairDbValidityRec::GetCreationDate(), FairDbValidityRec::GetL2CacheName(), FairDbValidityRec::GetSeqNo(), IsExtendedContext(), and FairDbValidityRec::IsGap().
Referenced by FairDbTableProxy::Query(), and FairDbTableProxy::RestoreFromL2Cache().
UInt_t FairDbValidityRecBuilder::GetNumValidityRec () const inline
Definition at line 41 of file FairDbValidityRecBuilder.h.
View newest version in sPHENIX GitHub at line 41 of file FairDbValidityRecBuilder.h
References fVRecs.
Referenced by FairDbValidityRecBuilder(), NonAggregated(), and FairDbTableProxy::Query().
FairDb::Task FairDbValidityRecBuilder::GetTask () const inline
Definition at line 40 of file FairDbValidityRecBuilder.h.
View newest version in sPHENIX GitHub at line 40 of file FairDbValidityRecBuilder.h
References fTask.
const FairDbValidityRec & FairDbValidityRecBuilder::GetValidityRec (Int_t rowNo) const
Definition at line 395 of file FairDbValidityRecBuilder.cxx.
View newest version in sPHENIX GitHub at line 395 of file FairDbValidityRecBuilder.cxx
References fGap, and fVRecs.
Referenced by FairDbValidityRecBuilder(), GetValidityRecFromAggNo(), and FairDbTableProxy::Query().
const FairDbValidityRec& FairDbValidityRecBuilder::GetValidityRecFromAggNo (Int_t aggNo) const inline
Definition at line 50 of file FairDbValidityRecBuilder.h.
View newest version in sPHENIX GitHub at line 50 of file FairDbValidityRecBuilder.h
References GetValidityRec(), and IndexOfAggno().
const FairDbValidityRec & FairDbValidityRecBuilder::GetValidityRecFromSeqNo (UInt_t SeqNo) const
Definition at line 404 of file FairDbValidityRecBuilder.cxx.
View newest version in sPHENIX GitHub at line 404 of file FairDbValidityRecBuilder.cxx
References fGap, and fVRecs.
Referenced by FairDbTableProxy::RestoreFromL2Cache().
Int_t FairDbValidityRecBuilder::IndexOfAggno (Int_t aggNo) const
Get index of AggNo or -1 if missing.
Definition at line 416 of file FairDbValidityRecBuilder.cxx.
View newest version in sPHENIX GitHub at line 416 of file FairDbValidityRecBuilder.cxx
References fAggNoToIndex.
Referenced by AddNewAgg(), and GetValidityRecFromAggNo().
Bool_t FairDbValidityRecBuilder::IsExtendedContext () const inline
Definition at line 46 of file FairDbValidityRecBuilder.h.
View newest version in sPHENIX GitHub at line 46 of file FairDbValidityRecBuilder.h
References fIsExtendedContext.
Referenced by GetL2CacheName(), and NonAggregated().
void FairDbValidityRecBuilder::MakeGapRec (const ValContext & vc, const string & tableName, Bool_t findFullTimeWindow = true) private
Definition at line 426 of file FairDbValidityRecBuilder.cxx.
View newest version in sPHENIX GitHub at line 426 of file FairDbValidityRecBuilder.cxx
References fGap, fTask, ValContext::GetDetector(), ValTimeStamp::GetSec(), ValContext::GetSimFlag(), FairDb::GetTimeGate(), and ValContext::GetTimeStamp().
Referenced by FairDbValidityRecBuilder().
Bool_t FairDbValidityRecBuilder::NonAggregated () const inline
Definition at line 54 of file FairDbValidityRecBuilder.h.
View newest version in sPHENIX GitHub at line 54 of file FairDbValidityRecBuilder.h
References GetNumValidityRec(), and IsExtendedContext().
Referenced by FairDbTableProxy::Query().
Member Data Documentation
std::map<Int_t,UInt_t> FairDbValidityRecBuilder::fAggNoToIndex private
Definition at line 79 of file FairDbValidityRecBuilder.h.
View newest version in sPHENIX GitHub at line 79 of file FairDbValidityRecBuilder.h
Referenced by AddNewAgg(), FairDbValidityRecBuilder(), and IndexOfAggno().
FairDbValidityRec FairDbValidityRecBuilder::fGap private
Definition at line 74 of file FairDbValidityRecBuilder.h.
View newest version in sPHENIX GitHub at line 74 of file FairDbValidityRecBuilder.h
Referenced by AddNewGap(), FairDbValidityRecBuilder(), GetValidityRec(), GetValidityRecFromSeqNo(), and MakeGapRec().
Bool_t FairDbValidityRecBuilder::fIsExtendedContext private
Definition at line 75 of file FairDbValidityRecBuilder.h.
View newest version in sPHENIX GitHub at line 75 of file FairDbValidityRecBuilder.h
Referenced by IsExtendedContext().
FairDb::Task FairDbValidityRecBuilder::fTask private
Definition at line 76 of file FairDbValidityRecBuilder.h.
View newest version in sPHENIX GitHub at line 76 of file FairDbValidityRecBuilder.h
Referenced by FairDbValidityRecBuilder(), GetTask(), and MakeGapRec().
std::vector<FairDbValidityRec> FairDbValidityRecBuilder::fVRecs private
Definition at line 78 of file FairDbValidityRecBuilder.h.
View newest version in sPHENIX GitHub at line 78 of file FairDbValidityRecBuilder.h
Referenced by AddNewAgg(), AddNewGap(), FairDbValidityRecBuilder(), GetL2CacheName(), GetNumValidityRec(), GetValidityRec(), and GetValidityRecFromSeqNo().
The documentation for this class was generated from the following files:
EicRoot/blob/master/dbase/dbInterface/FairDbValidityRecBuilder.h
EicRoot/blob/master/dbase/dbInterface/FairDbValidityRecBuilder.cxx