EIC Software: fun4all_eicmacros/blob/master/common/G4_Aerogel.C File Reference
G4_Aerogel.C File Reference
Aerogel RICH for EIC detector.
#include <GlobalVariables.C>
#include <g4detectors/PHG4SectorSubsystem.h>
#include <g4main/PHG4Reco.h>
Namespaces
namespace Enable
Macros
#define MACRO_G4AEROGEL_C
Functions
void AerogelInit ()
void AerogelSetup (PHG4Reco *g4Reco, const int N_Sector=8, const double min_eta=1.242)
Variables
bool Enable::AEROGEL = false
bool Enable::AEROGEL_OVERLAPCHECK = false
Detailed Description
Aerogel RICH for EIC detector.
Author
Jin Huang jhuan.nosp@m.g@bn.nosp@m.l.gov
Version
Revision:
1.2
Date
Date:
2013/10/09 01:08:17
Definition in file G4_Aerogel.C.
Macro Definition Documentation
#define MACRO_G4AEROGEL_C
Definition at line 2 of file G4_Aerogel.C.
View newest version in sPHENIX GitHub at line 2 of file G4_Aerogel.C
Function Documentation
void AerogelInit ()
Definition at line 24 of file G4_Aerogel.C.
View newest version in sPHENIX GitHub at line 24 of file G4_Aerogel.C
References max, BlackHoleGeometry::max_radius, and BlackHoleGeometry::max_z.
Referenced by G4Init().
void AerogelSetup (PHG4Reco * g4Reco, const int N_Sector = 8, const double min_eta = 1.242)
Definition at line 30 of file G4_Aerogel.C.
View newest version in sPHENIX GitHub at line 30 of file G4_Aerogel.C
References PHG4Sector::Sector_Geometry::AddLayers_AeroGel_ePHENIX(), Enable::AEROGEL_OVERLAPCHECK, PHG4Sector::Sector_Geometry::eta_to_polar_angle(), PHG4Sector::Sector_Geometry::FlatEdge(), PHG4SectorSubsystem::get_geometry(), Enable::OVERLAPCHECK, PHG4Subsystem::OverlapCheck(), PHG4Reco::registerSubsystem(), PHG4Sector::Sector_Geometry::set_material(), PHG4Sector::Sector_Geometry::set_max_polar_angle(), PHG4Sector::Sector_Geometry::set_min_polar_angle(), PHG4Sector::Sector_Geometry::set_min_polar_edge(), PHG4Sector::Sector_Geometry::set_N_Sector(), PHG4Sector::Sector_Geometry::set_normal_polar_angle(), PHG4Sector::Sector_Geometry::set_normal_start(), and PHG4Sector::Sector_Geometry::Unit_cm().
Referenced by G4Setup().