EIC Software: EicToyModel/blob/master/include/EtmOrphans.h File Reference
EtmOrphans.h File Reference
Namespaces
namespace etm
namespace g4
Enumerations
enum etm::Stretch { etm::kDent, etm::kRecess, etm::kWall }
enum etm::LineStyle { etm::solid = 1, etm::dashed = 7, etm::dotted = 3, etm::dashdotted = 8 }
Functions
double Eta2Theta (double eta)
double Theta2Eta (double theta)
bool ConditionChecker (bool condition, const char *fmt, const char *message=0)
Variables
static const double etm::cm = 1.0
static const double etm::mm = 0.1
static const double etm::um = 1E-4
static const double etm::m = 100.0
static const double etm::inch = 2.54
static const double g4::cm = 10.0
static const double g4::mm = 1.0
static const double g4::m = 1000.0
Function Documentation
bool ConditionChecker (bool condition, const char * fmt, const char * message = 0)
Definition at line 16 of file EtmOrphans.cc.
View newest version in sPHENIX GitHub at line 16 of file EtmOrphans.cc
References printf().
Referenced by EicToyModel::zoom().
double Eta2Theta (double eta)
Definition at line 28 of file EtmOrphans.cc.
View newest version in sPHENIX GitHub at line 28 of file EtmOrphans.cc
Referenced by EicToyModel::CalculateEtaEndPoint(), EicToyModel::CalculateEtaStartPoint(), EtmAzimuthalScan::DoIt(), and EicToyModel::DrawFlatFieldLines().
double Theta2Eta (double theta)
Definition at line 35 of file EtmOrphans.cc.
View newest version in sPHENIX GitHub at line 35 of file EtmOrphans.cc