EIC Software: EicToyModelDetector Class Reference
EicToyModelDetector Class Reference
#include <EicToyModel/blob/master/fun4all_with_eicroot/sandbox/EicToyModelDetector.h>
Public Member Functions
EicToyModelDetector (PHG4Subsystem *subsys, PHCompositeNode *Node, PHParameters *parameters, const std::string &dnam)
constructor
virtual ~EicToyModelDetector ()
destructor
void ConstructMe (G4LogicalVolume *world) override
construct
void Print (const std::string &what="ALL") const override
void SuperDetector (const std::string &name)
const std::string SuperDetector () const
volume accessors
int IsInDetector (G4VPhysicalVolume *) const
Public Member Functions inherited from PHG4Detector
PHG4Detector ()=delete
constructor
PHG4Detector (PHG4Subsystem *subsys, PHCompositeNode *Node, const std::string &nam)
virtual ~PHG4Detector (void)
destructor
virtual void Construct (G4LogicalVolume *world) final
construct method
virtual void PostConstruction ()
Optional PostConstruction call after all geometry is constructed.
virtual void Verbosity (const int v)
virtual int Verbosity () const
virtual G4UserSteppingAction * GetSteppingAction ()
virtual std::string GetName () const
virtual void OverlapCheck (const bool chk)
virtual bool OverlapCheck () const
virtual int DisplayVolume (G4VSolid *volume, G4LogicalVolume *logvol, G4RotationMatrix *rotm=nullptr)
virtual int DisplayVolume (G4LogicalVolume *checksolid, G4LogicalVolume *logvol, G4RotationMatrix *rotm=nullptr)
virtual PHCompositeNode * topNode ()
virtual PHG4Subsystem * GetMySubsystem ()
Private Attributes
PHParameters * m_Params
std::set< G4VPhysicalVolume * > m_PhysicalVolumesSet
std::string m_SuperDetector
Additional Inherited Members
Static Public Member Functions inherited from PHG4Detector
static G4Material * GetDetectorMaterial (const std::string &name, const bool quit=true)
static G4Element * GetDetectorElement (const std::string &name, const bool quit=true)
Detailed Description
Definition at line 17 of file EicToyModelDetector.h.
View newest version in sPHENIX GitHub at line 17 of file EicToyModelDetector.h
Constructor & Destructor Documentation
EicToyModelDetector::EicToyModelDetector (PHG4Subsystem * subsys, PHCompositeNode * Node, PHParameters * parameters, const std::string & dnam)
constructor
Definition at line 10 of file EicToyModelDetector.cc.
View newest version in sPHENIX GitHub at line 10 of file EicToyModelDetector.cc
virtual EicToyModelDetector::~EicToyModelDetector () inline virtual
destructor
Definition at line 24 of file EicToyModelDetector.h.
View newest version in sPHENIX GitHub at line 24 of file EicToyModelDetector.h
Member Function Documentation
void EicToyModelDetector::ConstructMe (G4LogicalVolume * world) override virtual
construct
Implements PHG4Detector.
Definition at line 31 of file EicToyModelDetector.cc.
View newest version in sPHENIX GitHub at line 31 of file EicToyModelDetector.cc
References eic, PHParameters::get_string_param(), EicToyModel::Import(), and m_Params.
int EicToyModelDetector::IsInDetector (G4VPhysicalVolume * volume) const
Definition at line 20 of file EicToyModelDetector.cc.
View newest version in sPHENIX GitHub at line 20 of file EicToyModelDetector.cc
References m_PhysicalVolumesSet.
void EicToyModelDetector::Print (const std::string & what = "ALL") const override virtual
Reimplemented from PHG4Detector.
Definition at line 46 of file EicToyModelDetector.cc.
View newest version in sPHENIX GitHub at line 46 of file EicToyModelDetector.cc
References m_Params, and PHParameters::Print().
Referenced by EicToyModelSubsystem::Print().
void EicToyModelDetector::SuperDetector (const std::string & name) inline
Definition at line 36 of file EicToyModelDetector.h.
View newest version in sPHENIX GitHub at line 36 of file EicToyModelDetector.h
References m_SuperDetector, and name.
Referenced by EicToyModelSubsystem::InitRunSubsystem().
const std::string EicToyModelDetector::SuperDetector () const inline
Definition at line 37 of file EicToyModelDetector.h.
View newest version in sPHENIX GitHub at line 37 of file EicToyModelDetector.h
References m_SuperDetector.
Member Data Documentation
PHParameters* EicToyModelDetector::m_Params private
Definition at line 40 of file EicToyModelDetector.h.
View newest version in sPHENIX GitHub at line 40 of file EicToyModelDetector.h
Referenced by ConstructMe(), and Print().
std::set<G4VPhysicalVolume *> EicToyModelDetector::m_PhysicalVolumesSet private
Definition at line 43 of file EicToyModelDetector.h.
View newest version in sPHENIX GitHub at line 43 of file EicToyModelDetector.h
Referenced by IsInDetector().
std::string EicToyModelDetector::m_SuperDetector private
Definition at line 45 of file EicToyModelDetector.h.
View newest version in sPHENIX GitHub at line 45 of file EicToyModelDetector.h
Referenced by SuperDetector().
The documentation for this class was generated from the following files:
EicToyModel/blob/master/fun4all_with_eicroot/sandbox/EicToyModelDetector.h
EicToyModel/blob/master/fun4all_with_eicroot/sandbox/EicToyModelDetector.cc