EIC Software: CbmRichTrackExtrapolationKF Class Reference
CbmRichTrackExtrapolationKF Class Reference
"TrackExtrapolation" from STS tracks (Kalman Fitter) It reads the track array form STS and extrapolates those to be projected to the Rich Photodetector to some z-Plane in RICH
#include <EicRoot/blob/master/rich/tracks/CbmRichTrackExtrapolationKF.h>
Public Member Functions
CbmRichTrackExtrapolationKF ()
Default constructor.
virtual ~CbmRichTrackExtrapolationKF ()
Destructor.
virtual void Init ()
Inherited from CbmRichTrackExtrapolationBase.
virtual void DoExtrapolation (TClonesArray *globalTracks, TClonesArray *extrapolatedTrackParams, double z, int minNofStsHits)
Inherited from CbmRichTrackExtrapolationBase.
Public Member Functions inherited from CbmRichTrackExtrapolationBase
CbmRichTrackExtrapolationBase ()
Default constructor.
virtual ~CbmRichTrackExtrapolationBase ()
Distructor.
Private Member Functions
CbmRichTrackExtrapolationKF (const CbmRichTrackExtrapolationKF &)
Copy constructor.
void operator= (const CbmRichTrackExtrapolationKF &)
Assignment operator.
Private Attributes
TClonesArray * fEicTracks
Detailed Description
"TrackExtrapolation" from STS tracks (Kalman Fitter) It reads the track array form STS and extrapolates those to be projected to the Rich Photodetector to some z-Plane in RICH
Author
Claudia Hoehne
Date
206
Definition at line 29 of file CbmRichTrackExtrapolationKF.h.
View newest version in sPHENIX GitHub at line 29 of file CbmRichTrackExtrapolationKF.h
Constructor & Destructor Documentation
CbmRichTrackExtrapolationKF::CbmRichTrackExtrapolationKF ()
Default constructor.
Definition at line 28 of file CbmRichTrackExtrapolationKF.cxx.
View newest version in sPHENIX GitHub at line 28 of file CbmRichTrackExtrapolationKF.cxx
CbmRichTrackExtrapolationKF::~CbmRichTrackExtrapolationKF () virtual
Destructor.
Definition at line 34 of file CbmRichTrackExtrapolationKF.cxx.
View newest version in sPHENIX GitHub at line 34 of file CbmRichTrackExtrapolationKF.cxx
CbmRichTrackExtrapolationKF::CbmRichTrackExtrapolationKF (const CbmRichTrackExtrapolationKF &) private
Copy constructor.
Member Function Documentation
void CbmRichTrackExtrapolationKF::DoExtrapolation (TClonesArray * globalTracks, TClonesArray * extrapolatedTrackParams, double z, int minNofStsHits) virtual
Inherited from CbmRichTrackExtrapolationBase.
Implements CbmRichTrackExtrapolationBase.
Definition at line 49 of file CbmRichTrackExtrapolationKF.cxx.
View newest version in sPHENIX GitHub at line 49 of file CbmRichTrackExtrapolationKF.cxx
References fEicTracks, PndTrack::GetParamLast(), FairTrackPar::GetPx(), FairTrackPar::GetPy(), FairTrackPar::GetPz(), FairTrackPar::GetQp(), CbmGlobalTrack::GetStsTrackIndex(), FairTrackPar::GetX(), FairTrackPar::GetY(), FairTrackPar::GetZ(), charm_jet_coverage::mom, pos(), FairGeanePro::Propagate(), and FairGeanePro::PropagateToPlane().
void CbmRichTrackExtrapolationKF::Init (void) virtual
Inherited from CbmRichTrackExtrapolationBase.
Reimplemented from CbmRichTrackExtrapolationBase.
Definition at line 38 of file CbmRichTrackExtrapolationKF.cxx.
View newest version in sPHENIX GitHub at line 38 of file CbmRichTrackExtrapolationKF.cxx
References fEicTracks, FairRootManager::GetObject(), and FairRootManager::Instance().
void CbmRichTrackExtrapolationKF::operator= (const CbmRichTrackExtrapolationKF &) private
Assignment operator.
Member Data Documentation
TClonesArray* CbmRichTrackExtrapolationKF::fEicTracks private
Definition at line 59 of file CbmRichTrackExtrapolationKF.h.
View newest version in sPHENIX GitHub at line 59 of file CbmRichTrackExtrapolationKF.h
Referenced by DoExtrapolation(), and Init().
The documentation for this class was generated from the following files:
EicRoot/blob/master/rich/tracks/CbmRichTrackExtrapolationKF.h
EicRoot/blob/master/rich/tracks/CbmRichTrackExtrapolationKF.cxx