EIC Software: Acts::EventDataVisualization Namespace Reference
Acts::EventDataVisualization Namespace Reference
Functions
static std::string test (IVisualization &helper)
Function Documentation
static std::string Acts::EventDataVisualization::test (IVisualization & helper) inline static
Helper method to visualiza all types of surfaces
Parameters
helper The visualziation helper
Returns
an overall string including all written output
Definition at line 38 of file EventDataVisualizationBase.hpp.
View newest version in sPHENIX GitHub at line 38 of file EventDataVisualizationBase.hpp
References Acts::Visualization::drawBoundParameters(), Acts::Test::gctx, Acts::PrimitivesVisualization::identity, Acts::PrimitivesVisualization::plane, Acts::PrimitivesVisualization::rectangle, and Acts::IVisualization::write().
Referenced by FairPrimaryGenerator::AddTrack(), Acts::Test::BOOST_AUTO_TEST_CASE(), BOOST_DATA_TEST_CASE(), Acts::BoundaryCheck::computeEuclideanClosestPointOnRectangle(), FairPrimaryGenerator::GenerateEvent(), PndTrackCand::HitInTrack(), nlohmann::basic_json::patch(), Gammagammasingle::pp1(), Gammagammasingle::pp2(), Gammagammaleptonpair::pp_1(), Gammagammaleptonpair::pp_2(), Gammaavectormeson::pTgamma(), PHMicromegasTpcTrackMatching::set_test_windows_printout(), PHSiliconTpcTrackMatching::set_test_windows_printout(), G4LBLVtxDetector::SetActiveVolumes(), FairDbConnection::TableExists(), and Acts::CylinderVolumeBuilder::trackingVolume().