EIC Software: G4JLeicBeamLineMagnetDetector Class Reference
G4JLeicBeamLineMagnetDetector Class Reference
#include <fun4all_eicdetectors/blob/master/simulation/g4simulation/g4jleic/G4JLeicBeamLineMagnetDetector.h>
Public Member Functions
G4JLeicBeamLineMagnetDetector (PHG4Subsystem *subsys, PHCompositeNode *Node, PHParameters *parameters, const std::string &dnam, const int layer=0)
constructor
virtual ~G4JLeicBeamLineMagnetDetector (void)
destructor
void ConstructMe (G4LogicalVolume *world)
construct
int IsInBeamLineMagnet (const G4VPhysicalVolume *) const
void SuperDetector (const std::string &name)
const std::string SuperDetector () const
int get_Layer () const
G4JLeicBeamLineMagnetDetector (PHG4Subsystem *subsys, PHCompositeNode *Node, PHParameters *parameters, const std::string &dnam, const int layer=0)
constructor
virtual ~G4JLeicBeamLineMagnetDetector (void)
destructor
void ConstructMe (G4LogicalVolume *world)
construct
int IsInBeamLineMagnet (const G4VPhysicalVolume *) const
void SuperDetector (const std::string &name)
const std::string SuperDetector () const
int get_Layer () const
Public Member Functions inherited from PHG4Detector
PHG4Detector ()=delete
constructor
PHG4Detector (PHG4Subsystem *subsys, PHCompositeNode *Node, const std::string &nam)
virtual ~PHG4Detector (void)
destructor
virtual void Construct (G4LogicalVolume *world) final
construct method
virtual void PostConstruction ()
Optional PostConstruction call after all geometry is constructed.
virtual void Verbosity (const int v)
virtual int Verbosity () const
virtual G4UserSteppingAction * GetSteppingAction ()
virtual std::string GetName () const
virtual void OverlapCheck (const bool chk)
virtual bool OverlapCheck () const
virtual void Print (const std::string &="ALL") const
virtual int DisplayVolume (G4VSolid *volume, G4LogicalVolume *logvol, G4RotationMatrix *rotm=nullptr)
virtual int DisplayVolume (G4LogicalVolume *checksolid, G4LogicalVolume *logvol, G4RotationMatrix *rotm=nullptr)
virtual PHCompositeNode * topNode ()
virtual PHG4Subsystem * GetMySubsystem ()
Private Attributes
PHParameters * params
G4VPhysicalVolume * magnet_physi
G4VPhysicalVolume * magnet_iron_physi
G4JLeicBeamLineMagnetDisplayAction * m_DisplayAction
int layer
std::string superdetector
Additional Inherited Members
Static Public Member Functions inherited from PHG4Detector
static G4Material * GetDetectorMaterial (const std::string &name, const bool quit=true)
static G4Element * GetDetectorElement (const std::string &name, const bool quit=true)
Detailed Description
Definition at line 17 of file G4JLeicBeamLineMagnetDetector.h.
View newest version in sPHENIX GitHub at line 17 of file G4JLeicBeamLineMagnetDetector.h
Constructor & Destructor Documentation
G4JLeicBeamLineMagnetDetector::G4JLeicBeamLineMagnetDetector (PHG4Subsystem * subsys, PHCompositeNode * Node, PHParameters * parameters, const std::string & dnam, const int layer = 0)
constructor
Definition at line 45 of file G4JLeicBeamLineMagnetDetector.cc.
View newest version in sPHENIX GitHub at line 45 of file G4JLeicBeamLineMagnetDetector.cc
virtual G4JLeicBeamLineMagnetDetector::~G4JLeicBeamLineMagnetDetector (void) inline virtual
destructor
Definition at line 24 of file G4JLeicBeamLineMagnetDetector.h.
View newest version in sPHENIX GitHub at line 24 of file G4JLeicBeamLineMagnetDetector.h
G4JLeicBeamLineMagnetDetector::G4JLeicBeamLineMagnetDetector (PHG4Subsystem * subsys, PHCompositeNode * Node, PHParameters * parameters, const std::string & dnam, const int layer = 0)
constructor
virtual G4JLeicBeamLineMagnetDetector::~G4JLeicBeamLineMagnetDetector (void) inline virtual
destructor
Definition at line 24 of file G4JLeicBeamLineMagnetDetector.h.
View newest version in sPHENIX GitHub at line 24 of file G4JLeicBeamLineMagnetDetector.h
Member Function Documentation
void G4JLeicBeamLineMagnetDetector::ConstructMe (G4LogicalVolume * world) virtual
construct
Implements PHG4Detector.
Definition at line 70 of file G4JLeicBeamLineMagnetDetector.cc.
View newest version in sPHENIX GitHub at line 70 of file G4JLeicBeamLineMagnetDetector.cc
References G4JLeicBeamLineMagnetDisplayAction::AddVolume(), Acts::UnitConstants::cm, PHParameters::get_double_param(), PHParameters::get_string_param(), PHG4Detector::GetDetectorMaterial(), PHG4Detector::GetName(), m_DisplayAction, magnet_iron_physi, magnet_physi, Acts::UnitConstants::mm, Acts::Test::origin(), PHG4Detector::OverlapCheck(), params, PHWHERE, twopi, and PHG4Detector::Verbosity().
void G4JLeicBeamLineMagnetDetector::ConstructMe (G4LogicalVolume * world) virtual
construct
Implements PHG4Detector.
int G4JLeicBeamLineMagnetDetector::get_Layer () const inline
Definition at line 34 of file G4JLeicBeamLineMagnetDetector.h.
View newest version in sPHENIX GitHub at line 34 of file G4JLeicBeamLineMagnetDetector.h
References layer.
int G4JLeicBeamLineMagnetDetector::get_Layer () const inline
Definition at line 34 of file G4JLeicBeamLineMagnetDetector.h.
View newest version in sPHENIX GitHub at line 34 of file G4JLeicBeamLineMagnetDetector.h
References layer.
int G4JLeicBeamLineMagnetDetector::IsInBeamLineMagnet (const G4VPhysicalVolume *) const
int G4JLeicBeamLineMagnetDetector::IsInBeamLineMagnet (const G4VPhysicalVolume * volume) const
Definition at line 56 of file G4JLeicBeamLineMagnetDetector.cc.
View newest version in sPHENIX GitHub at line 56 of file G4JLeicBeamLineMagnetDetector.cc
References magnet_iron_physi, and magnet_physi.
Referenced by G4JLeicBeamLineMagnetSteppingAction::UserSteppingAction().
void G4JLeicBeamLineMagnetDetector::SuperDetector (const std::string & name) inline
Definition at line 32 of file G4JLeicBeamLineMagnetDetector.h.
View newest version in sPHENIX GitHub at line 32 of file G4JLeicBeamLineMagnetDetector.h
References name, and superdetector.
void G4JLeicBeamLineMagnetDetector::SuperDetector (const std::string & name) inline
Definition at line 32 of file G4JLeicBeamLineMagnetDetector.h.
View newest version in sPHENIX GitHub at line 32 of file G4JLeicBeamLineMagnetDetector.h
References name, and superdetector.
Referenced by G4JLeicBeamLineMagnetSubsystem::InitRunSubsystem(), and G4JLeicBeamLineMagnetSteppingAction::SetInterfacePointers().
const std::string G4JLeicBeamLineMagnetDetector::SuperDetector () const inline
Definition at line 33 of file G4JLeicBeamLineMagnetDetector.h.
View newest version in sPHENIX GitHub at line 33 of file G4JLeicBeamLineMagnetDetector.h
References superdetector.
const std::string G4JLeicBeamLineMagnetDetector::SuperDetector () const inline
Definition at line 33 of file G4JLeicBeamLineMagnetDetector.h.
View newest version in sPHENIX GitHub at line 33 of file G4JLeicBeamLineMagnetDetector.h
References superdetector.
Member Data Documentation
int G4JLeicBeamLineMagnetDetector::layer private
Definition at line 43 of file G4JLeicBeamLineMagnetDetector.h.
View newest version in sPHENIX GitHub at line 43 of file G4JLeicBeamLineMagnetDetector.h
Referenced by get_Layer().
G4JLeicBeamLineMagnetDisplayAction * G4JLeicBeamLineMagnetDetector::m_DisplayAction private
Definition at line 41 of file G4JLeicBeamLineMagnetDetector.h.
View newest version in sPHENIX GitHub at line 41 of file G4JLeicBeamLineMagnetDetector.h
Referenced by ConstructMe().
G4VPhysicalVolume * G4JLeicBeamLineMagnetDetector::magnet_iron_physi private
Definition at line 40 of file G4JLeicBeamLineMagnetDetector.h.
View newest version in sPHENIX GitHub at line 40 of file G4JLeicBeamLineMagnetDetector.h
Referenced by ConstructMe(), and IsInBeamLineMagnet().
G4VPhysicalVolume * G4JLeicBeamLineMagnetDetector::magnet_physi private
Definition at line 39 of file G4JLeicBeamLineMagnetDetector.h.
View newest version in sPHENIX GitHub at line 39 of file G4JLeicBeamLineMagnetDetector.h
Referenced by ConstructMe(), and IsInBeamLineMagnet().
PHParameters * G4JLeicBeamLineMagnetDetector::params private
Definition at line 37 of file G4JLeicBeamLineMagnetDetector.h.
View newest version in sPHENIX GitHub at line 37 of file G4JLeicBeamLineMagnetDetector.h
Referenced by ConstructMe().
std::string G4JLeicBeamLineMagnetDetector::superdetector private
Definition at line 44 of file G4JLeicBeamLineMagnetDetector.h.
View newest version in sPHENIX GitHub at line 44 of file G4JLeicBeamLineMagnetDetector.h
Referenced by SuperDetector().
The documentation for this class was generated from the following files:
fun4all_eicdetectors/blob/master/simulation/g4simulation/g4jleic/G4JLeicBeamLineMagnetDetector.h
fun4all_g4jleic/blob/master/source/G4JLeicBeamLineMagnetDetector.h
fun4all_eicdetectors/blob/master/simulation/g4simulation/g4jleic/G4JLeicBeamLineMagnetDetector.cc
fun4all_g4jleic/blob/master/source/G4JLeicBeamLineMagnetDetector.cc