EIC Software: FW::Geant4::MMEventAction Class Reference
FW::Geant4::MMEventAction Class Reference
Writes out material track records.
#include <fun4all_acts/blob/master/Examples/Algorithms/Geant4/include/ACTFW/Plugins/Geant4/MMEventAction.hpp>
Public Member Functions
MMEventAction ()
Constructor.
~MMEventAction () override
Virtual destructor.
void BeginOfEventAction (const G4Event *event) finaloverride
void EndOfEventAction (const G4Event *event) finaloverride
void Reset ()
std::vector
< Acts::RecordedMaterialTrack >
const MaterialTracks ()
FW::SimHitContainer const TrackSteps ()
Static Public Member Functions
static MMEventAction * Instance ()
Static access method.
Private Attributes
std::vector
< Acts::RecordedMaterialTrack > m_records
The materialTrackWriter.
FW::SimHitContainer m_tracksteps
Static Private Attributes
static MMEventAction * fgInstance = nullptr
Instance of the EventAction.
Detailed Description
Writes out material track records.
The MMEventAction class is the realization of the Geant4 class G4UserEventAction and is writing out the collected RecordedMaterialTrack entities needed for material mapping once per event.
Definition at line 37 of file MMEventAction.hpp.
View newest version in sPHENIX GitHub at line 37 of file MMEventAction.hpp
Constructor & Destructor Documentation
FW::Geant4::MMEventAction::MMEventAction ()
Constructor.
Definition at line 25 of file MMEventAction.cpp.
View newest version in sPHENIX GitHub at line 25 of file MMEventAction.cpp
References fgInstance.
FW::Geant4::MMEventAction::~MMEventAction () override
Virtual destructor.
Definition at line 33 of file MMEventAction.cpp.
View newest version in sPHENIX GitHub at line 33 of file MMEventAction.cpp
Member Function Documentation
void FW::Geant4::MMEventAction::BeginOfEventAction (const G4Event * event) final override
Interface method for begin of the event
Parameters
event is the G4Event to be processed
Note
resets the material step action
Definition at line 37 of file MMEventAction.cpp.
View newest version in sPHENIX GitHub at line 37 of file MMEventAction.cpp
References FW::Geant4::MMSteppingAction::Instance(), and FW::Geant4::MMSteppingAction::Reset().
void FW::Geant4::MMEventAction::EndOfEventAction (const G4Event * event) final override
Interface method for end of event
Parameters
event is the G4Event to be processed
Note
this method is writing out the material track records
Definition at line 42 of file MMEventAction.cpp.
View newest version in sPHENIX GitHub at line 42 of file MMEventAction.cpp
References FW::Geant4::MMPrimaryGeneratorAction::direction(), FW::Geant4::MMSteppingAction::Instance(), FW::Geant4::MMPrimaryGeneratorAction::Instance(), and FW::Geant4::MMSteppingAction::materialSteps().
FW::Geant4::MMEventAction * FW::Geant4::MMEventAction::Instance (void) static
Static access method.
Definition at line 20 of file MMEventAction.cpp.
View newest version in sPHENIX GitHub at line 20 of file MMEventAction.cpp
References fgInstance.
Referenced by FW::Geant4::MMRunAction::BeginOfRunAction(), and FW::GeantinoRecording::execute().
std::vector< Acts::RecordedMaterialTrack > const FW::Geant4::MMEventAction::MaterialTracks () inline
Definition at line 78 of file MMEventAction.hpp.
View newest version in sPHENIX GitHub at line 78 of file MMEventAction.hpp
References m_records.
Referenced by FW::GeantinoRecording::execute().
void FW::Geant4::MMEventAction::Reset ()
Interface method
Note
does nothing
Definition at line 61 of file MMEventAction.cpp.
View newest version in sPHENIX GitHub at line 61 of file MMEventAction.cpp
Referenced by FW::Geant4::MMRunAction::BeginOfRunAction().
FW::SimHitContainer const FW::Geant4::MMEventAction::TrackSteps () inline
Definition at line 84 of file MMEventAction.hpp.
View newest version in sPHENIX GitHub at line 84 of file MMEventAction.hpp
References m_tracksteps.
Member Data Documentation
FW::Geant4::MMEventAction * FW::Geant4::MMEventAction::fgInstance = nullptr static private
Instance of the EventAction.
Definition at line 70 of file MMEventAction.hpp.
View newest version in sPHENIX GitHub at line 70 of file MMEventAction.hpp
Referenced by Instance(), and MMEventAction().
std::vector<Acts::RecordedMaterialTrack> FW::Geant4::MMEventAction::m_records private
The materialTrackWriter.
Definition at line 73 of file MMEventAction.hpp.
View newest version in sPHENIX GitHub at line 73 of file MMEventAction.hpp
Referenced by MaterialTracks().
FW::SimHitContainer FW::Geant4::MMEventAction::m_tracksteps private
Definition at line 74 of file MMEventAction.hpp.
View newest version in sPHENIX GitHub at line 74 of file MMEventAction.hpp
Referenced by TrackSteps().
The documentation for this class was generated from the following files:
fun4all_acts/blob/master/Examples/Algorithms/Geant4/include/ACTFW/Plugins/Geant4/MMEventAction.hpp
fun4all_acts/blob/master/Examples/Algorithms/Geant4/src/MMEventAction.cpp