EIC Software: node_t Class Reference
node_t Class Reference
#include <EicRoot/blob/master/eic/cad/elmer/src/meshtype.h>
Public Member Functions
node_t ()
~node_t ()
void setX (int, double)
double getX (int) const
void setXvec (double *)
double * getXvec ()
void setIndex (int)
int getIndex () const
Private Attributes
double x [3]
int index
Detailed Description
Definition at line 58 of file meshtype.h.
View newest version in sPHENIX GitHub at line 58 of file meshtype.h
Constructor & Destructor Documentation
node_t::node_t ()
Definition at line 47 of file meshtype.cpp.
View newest version in sPHENIX GitHub at line 47 of file meshtype.cpp
node_t::~node_t ()
Definition at line 51 of file meshtype.cpp.
View newest version in sPHENIX GitHub at line 51 of file meshtype.cpp
Member Function Documentation
int node_t::getIndex () const
Definition at line 83 of file meshtype.cpp.
View newest version in sPHENIX GitHub at line 83 of file meshtype.cpp
Referenced by mesh_t::save().
double node_t::getX (int n) const
Definition at line 72 of file meshtype.cpp.
View newest version in sPHENIX GitHub at line 72 of file meshtype.cpp
References n, and x.
Referenced by mesh_t::boundingBox(), and mesh_t::save().
double * node_t::getXvec ()
Definition at line 62 of file meshtype.cpp.
View newest version in sPHENIX GitHub at line 62 of file meshtype.cpp
References x.
void node_t::setIndex (int n)
Definition at line 77 of file meshtype.cpp.
View newest version in sPHENIX GitHub at line 77 of file meshtype.cpp
References n.
Referenced by ConvertEgTypeToMeshType(), and mesh_t::load().
void node_t::setX (int n, double y)
Definition at line 67 of file meshtype.cpp.
View newest version in sPHENIX GitHub at line 67 of file meshtype.cpp
References n, x, and y.
Referenced by ConvertEgTypeToMeshType(), and mesh_t::load().
void node_t::setXvec (double * y)
Definition at line 55 of file meshtype.cpp.
View newest version in sPHENIX GitHub at line 55 of file meshtype.cpp
References x.
Member Data Documentation
int node_t::index private
Definition at line 72 of file meshtype.h.
View newest version in sPHENIX GitHub at line 72 of file meshtype.h
double node_t::x[3] private
Definition at line 71 of file meshtype.h.
View newest version in sPHENIX GitHub at line 71 of file meshtype.h
Referenced by eicpy.qaplots.LogAxis::apply(), and eicpy.qaplots.LogAxis::rebin().
The documentation for this class was generated from the following files:
EicRoot/blob/master/eic/cad/elmer/src/meshtype.h
EicRoot/blob/master/eic/cad/elmer/src/meshtype.cpp