EIC Software: PHG4ForwardDualReadoutDetector Class Reference
PHG4ForwardDualReadoutDetector Class Reference
#include <fun4all_eicdetectors/blob/master/simulation/g4simulation/g4drcalo/PHG4ForwardDualReadoutDetector.h>
Classes
struct towerposition
Public Member Functions
PHG4ForwardDualReadoutDetector (PHG4Subsystem *subsys, PHCompositeNode *Node, const std::string &dnam)
constructor
virtual ~PHG4ForwardDualReadoutDetector ()
destructor
virtual void ConstructMe (G4LogicalVolume *world)
construct
Public Member Functions inherited from PHG4Detector
PHG4Detector ()=delete
constructor
PHG4Detector (PHG4Subsystem *subsys, PHCompositeNode *Node, const std::string &nam)
virtual ~PHG4Detector (void)
destructor
virtual void Construct (G4LogicalVolume *world) final
construct method
virtual void PostConstruction ()
Optional PostConstruction call after all geometry is constructed.
virtual void Verbosity (const int v)
virtual int Verbosity () const
virtual G4UserSteppingAction * GetSteppingAction ()
virtual std::string GetName () const
virtual void OverlapCheck (const bool chk)
virtual bool OverlapCheck () const
virtual void Print (const std::string &="ALL") const
virtual int DisplayVolume (G4VSolid *volume, G4LogicalVolume *logvol, G4RotationMatrix *rotm=nullptr)
virtual int DisplayVolume (G4LogicalVolume *checksolid, G4LogicalVolume *logvol, G4RotationMatrix *rotm=nullptr)
virtual PHCompositeNode * topNode ()
virtual PHG4Subsystem * GetMySubsystem ()
volume accessors
PHG4ForwardDualReadoutDisplayAction * m_DisplayAction
PHG4ForwardDualReadoutSteppingAction * m_SteppingAction
G4double _place_in_x
G4double _place_in_y
G4double _place_in_z
G4double _center_offset_x
G4double _center_offset_y
int _quadratic_detector
G4double _rot_in_x
G4double _rot_in_y
G4double _rot_in_z
G4double _rMin1
G4double _rMax1
G4double _rMin2
G4double _rMax2
G4double _dZ
G4double _sPhi
G4double _dPhi
int _tower_type
G4double _tower_readout
G4double _tower_dx
G4double _tower_dy
G4double _tower_dz
G4double _scintFiber_diam
G4double _cerenkovFiber_diam
int _cerenkovFiber_material
int _tower_makeNotched
int _absorber_Material
G4double _wls_dw
G4double _support_dw
G4String _materialScintillator
G4String _materialAbsorber
int _active
int _absorberactive
int _layer
int _blackhole
std::string _towerlogicnameprefix
std::string _superdetector
std::string _mapping_tower_file
std::map< std::string, G4double > m_GlobalParameterMap
std::map< std::string,
towerposition > _map_tower
int IsInForwardDualReadout (G4VPhysicalVolume *) const
void SetTowerMappingFile (const std::string &filename)
Select mapping file for calorimeter tower.
void SetTowerDimensions (G4double dx, G4double dy, G4double dz)
void SetPlace (G4double place_in_x, G4double place_in_y, G4double place_in_z)
void SetXRot (G4double rot_in_x)
void SetYRot (G4double rot_in_y)
void SetZRot (G4double rot_in_z)
void SetMaterialScintillator (G4String material)
void SetMaterialAbsorber (G4String material)
void SetActive (const int i=1)
void SetAbsorberActive (const int i=1)
int IsActive () const
void SuperDetector (const std::string &name)
void SetSteppingAction (PHG4ForwardDualReadoutSteppingAction *stpact)
const std::string SuperDetector () const
int get_Layer () const
void BlackHole (const int i=1)
int IsBlackHole () const
G4LogicalVolume * ConstructTower (int type)
G4LogicalVolume * ConstructTowerFCStyle (int type)
G4Material * GetScintillatorMaterial ()
G4Material * GetQuartzMaterial ()
G4Material * GetPMMAMaterial ()
int PlaceTower (G4LogicalVolume *envelope, G4LogicalVolume *tower)
int ParseParametersFromTable ()
Additional Inherited Members
Static Public Member Functions inherited from PHG4Detector
static G4Material * GetDetectorMaterial (const std::string &name, const bool quit=true)
static G4Element * GetDetectorElement (const std::string &name, const bool quit=true)
Detailed Description
Definition at line 28 of file PHG4ForwardDualReadoutDetector.h.
View newest version in sPHENIX GitHub at line 28 of file PHG4ForwardDualReadoutDetector.h
Constructor & Destructor Documentation
PHG4ForwardDualReadoutDetector::PHG4ForwardDualReadoutDetector (PHG4Subsystem * subsys, PHCompositeNode * Node, const std::string & dnam)
constructor
Definition at line 44 of file PHG4ForwardDualReadoutDetector.cc.
View newest version in sPHENIX GitHub at line 44 of file PHG4ForwardDualReadoutDetector.cc
virtual PHG4ForwardDualReadoutDetector::~PHG4ForwardDualReadoutDetector () inline virtual
destructor
Definition at line 35 of file PHG4ForwardDualReadoutDetector.h.
View newest version in sPHENIX GitHub at line 35 of file PHG4ForwardDualReadoutDetector.h
Member Function Documentation
void PHG4ForwardDualReadoutDetector::BlackHole (const int i = 1) inline
Definition at line 81 of file PHG4ForwardDualReadoutDetector.h.
View newest version in sPHENIX GitHub at line 81 of file PHG4ForwardDualReadoutDetector.h
References _blackhole.
Referenced by PHG4ForwardDualReadoutSubsystem::InitRunSubsystem().
void PHG4ForwardDualReadoutDetector::ConstructMe (G4LogicalVolume * world) virtual
construct
Implements PHG4Detector.
Definition at line 122 of file PHG4ForwardDualReadoutDetector.cc.
View newest version in sPHENIX GitHub at line 122 of file PHG4ForwardDualReadoutDetector.cc
References _center_offset_x, _dPhi, _dZ, _place_in_x, _place_in_y, _place_in_z, _quadratic_detector, _rMax1, _rMax2, _rMin1, _rMin2, _rot_in_x, _rot_in_y, _rot_in_z, _sPhi, _tower_dx, _tower_dy, _tower_dz, _tower_type, _towerlogicnameprefix, kdfinder::abs(), PHG4ForwardDualReadoutDisplayAction::AddVolume(), ConstructTower(), ConstructTowerFCStyle(), PHG4Detector::GetDetectorMaterial(), m_DisplayAction, PHG4Detector::OverlapCheck(), ParseParametersFromTable(), nlohmann::to_string(), and PHG4Detector::Verbosity().
G4LogicalVolume * PHG4ForwardDualReadoutDetector::ConstructTower (int type) private
Definition at line 306 of file PHG4ForwardDualReadoutDetector.cc.
View newest version in sPHENIX GitHub at line 306 of file PHG4ForwardDualReadoutDetector.cc
References _absorber_Material, _cerenkovFiber_diam, _cerenkovFiber_material, _materialAbsorber, _scintFiber_diam, _tower_dx, _tower_dy, _tower_dz, _tower_makeNotched, _tower_readout, _towerlogicnameprefix, PHG4ForwardDualReadoutDisplayAction::AddVolume(), PHG4Detector::GetDetectorMaterial(), GetPMMAMaterial(), GetQuartzMaterial(), GetScintillatorMaterial(), m_DisplayAction, M_PI, Acts::UnitConstants::mm, PHG4Detector::OverlapCheck(), Acts::UnitConstants::rad, nlohmann::to_string(), and PHG4Detector::Verbosity().
Referenced by ConstructMe().
G4LogicalVolume * PHG4ForwardDualReadoutDetector::ConstructTowerFCStyle (int type) private
Definition at line 566 of file PHG4ForwardDualReadoutDetector.cc.
View newest version in sPHENIX GitHub at line 566 of file PHG4ForwardDualReadoutDetector.cc
References _absorber_Material, _cerenkovFiber_diam, _cerenkovFiber_material, _materialAbsorber, _scintFiber_diam, _tower_dx, _tower_dy, _tower_dz, _tower_readout, _towerlogicnameprefix, PHG4ForwardDualReadoutDisplayAction::AddVolume(), PHG4Detector::GetDetectorMaterial(), GetPMMAMaterial(), GetQuartzMaterial(), GetScintillatorMaterial(), m_DisplayAction, M_PI, PHG4Detector::OverlapCheck(), Acts::UnitConstants::rad, and PHG4Detector::Verbosity().
Referenced by ConstructMe().
int PHG4ForwardDualReadoutDetector::get_Layer () const inline
Definition at line 79 of file PHG4ForwardDualReadoutDetector.h.
View newest version in sPHENIX GitHub at line 79 of file PHG4ForwardDualReadoutDetector.h
References _layer.
Referenced by PHG4ForwardDualReadoutSteppingAction::UserSteppingAction().
G4Material * PHG4ForwardDualReadoutDetector::GetPMMAMaterial () private
Definition at line 817 of file PHG4ForwardDualReadoutDetector.cc.
View newest version in sPHENIX GitHub at line 817 of file PHG4ForwardDualReadoutDetector.cc
References Acts::UnitConstants::cm3, Acts::UnitConstants::eV, g(), Acts::UnitConstants::m, and PHG4Detector::Verbosity().
Referenced by ConstructTower(), and ConstructTowerFCStyle().
G4Material * PHG4ForwardDualReadoutDetector::GetQuartzMaterial () private
Definition at line 867 of file PHG4ForwardDualReadoutDetector.cc.
View newest version in sPHENIX GitHub at line 867 of file PHG4ForwardDualReadoutDetector.cc
References Acts::UnitConstants::cm3, Acts::UnitConstants::eV, g(), Acts::UnitConstants::mm, and PHG4Detector::Verbosity().
Referenced by ConstructTower(), and ConstructTowerFCStyle().
G4Material * PHG4ForwardDualReadoutDetector::GetScintillatorMaterial () private
Definition at line 756 of file PHG4ForwardDualReadoutDetector.cc.
View newest version in sPHENIX GitHub at line 756 of file PHG4ForwardDualReadoutDetector.cc
References Acts::UnitConstants::cm3, Acts::UnitConstants::eV, g(), Acts::UnitConstants::m, Acts::UnitConstants::MeV, Acts::UnitConstants::mm, Acts::UnitConstants::ns, and PHG4Detector::Verbosity().
Referenced by ConstructTower(), and ConstructTowerFCStyle().
int PHG4ForwardDualReadoutDetector::IsActive () const inline
Definition at line 73 of file PHG4ForwardDualReadoutDetector.h.
View newest version in sPHENIX GitHub at line 73 of file PHG4ForwardDualReadoutDetector.h
References _active.
Referenced by PHG4ForwardDualReadoutSteppingAction::UserSteppingAction().
int PHG4ForwardDualReadoutDetector::IsBlackHole () const inline
Definition at line 82 of file PHG4ForwardDualReadoutDetector.h.
View newest version in sPHENIX GitHub at line 82 of file PHG4ForwardDualReadoutDetector.h
References _blackhole.
Referenced by PHG4ForwardDualReadoutSteppingAction::UserSteppingAction().
int PHG4ForwardDualReadoutDetector::IsInForwardDualReadout (G4VPhysicalVolume * volume) const
Definition at line 86 of file PHG4ForwardDualReadoutDetector.cc.
View newest version in sPHENIX GitHub at line 86 of file PHG4ForwardDualReadoutDetector.cc
References _absorberactive, _active, and _towerlogicnameprefix.
Referenced by PHG4ForwardDualReadoutSteppingAction::UserSteppingAction().
int PHG4ForwardDualReadoutDetector::ParseParametersFromTable () private
Definition at line 967 of file PHG4ForwardDualReadoutDetector.cc.
View newest version in sPHENIX GitHub at line 967 of file PHG4ForwardDualReadoutDetector.cc
References _absorber_Material, _center_offset_x, _center_offset_y, _cerenkovFiber_diam, _cerenkovFiber_material, _dZ, _mapping_tower_file, _place_in_x, _place_in_y, _place_in_z, _quadratic_detector, _rMax1, _rMax2, _rMin1, _rMin2, _rot_in_x, _rot_in_y, _rot_in_z, _scintFiber_diam, _tower_dx, _tower_dy, _tower_dz, _tower_makeNotched, _tower_readout, _tower_type, Acts::UnitConstants::cm, getline, m_GlobalParameterMap, m_SteppingAction, PHG4ForwardDualReadoutSteppingAction::SetDetectorSize(), PHG4ForwardDualReadoutSteppingAction::SetTowerReadout(), PHG4ForwardDualReadoutSteppingAction::SetTowerSize(), and PHG4Detector::Verbosity().
Referenced by ConstructMe().
int PHG4ForwardDualReadoutDetector::PlaceTower (G4LogicalVolume * envelope, G4LogicalVolume * tower) private
void PHG4ForwardDualReadoutDetector::SetAbsorberActive (const int i = 1) inline
Definition at line 71 of file PHG4ForwardDualReadoutDetector.h.
View newest version in sPHENIX GitHub at line 71 of file PHG4ForwardDualReadoutDetector.h
References _absorberactive.
Referenced by PHG4ForwardDualReadoutSubsystem::InitRunSubsystem().
void PHG4ForwardDualReadoutDetector::SetActive (const int i = 1) inline
Definition at line 70 of file PHG4ForwardDualReadoutDetector.h.
View newest version in sPHENIX GitHub at line 70 of file PHG4ForwardDualReadoutDetector.h
References _active.
Referenced by PHG4ForwardDualReadoutSubsystem::InitRunSubsystem().
void PHG4ForwardDualReadoutDetector::SetMaterialAbsorber (G4String material) inline
Definition at line 68 of file PHG4ForwardDualReadoutDetector.h.
View newest version in sPHENIX GitHub at line 68 of file PHG4ForwardDualReadoutDetector.h
References _materialAbsorber, and material().
void PHG4ForwardDualReadoutDetector::SetMaterialScintillator (G4String material) inline
Definition at line 67 of file PHG4ForwardDualReadoutDetector.h.
View newest version in sPHENIX GitHub at line 67 of file PHG4ForwardDualReadoutDetector.h
References _materialScintillator, and material().
void PHG4ForwardDualReadoutDetector::SetPlace (G4double place_in_x, G4double place_in_y, G4double place_in_z) inline
Definition at line 56 of file PHG4ForwardDualReadoutDetector.h.
View newest version in sPHENIX GitHub at line 56 of file PHG4ForwardDualReadoutDetector.h
References _place_in_x, _place_in_y, and _place_in_z.
void PHG4ForwardDualReadoutDetector::SetSteppingAction (PHG4ForwardDualReadoutSteppingAction * stpact) inline
Definition at line 76 of file PHG4ForwardDualReadoutDetector.h.
View newest version in sPHENIX GitHub at line 76 of file PHG4ForwardDualReadoutDetector.h
References m_SteppingAction.
Referenced by PHG4ForwardDualReadoutSubsystem::InitRunSubsystem().
void PHG4ForwardDualReadoutDetector::SetTowerDimensions (G4double dx, G4double dy, G4double dz) inline
Definition at line 49 of file PHG4ForwardDualReadoutDetector.h.
View newest version in sPHENIX GitHub at line 49 of file PHG4ForwardDualReadoutDetector.h
References _tower_dx, _tower_dy, _tower_dz, dx, dy, and dz.
void PHG4ForwardDualReadoutDetector::SetTowerMappingFile (const std::string & filename) inline
Select mapping file for calorimeter tower.
Definition at line 44 of file PHG4ForwardDualReadoutDetector.h.
View newest version in sPHENIX GitHub at line 44 of file PHG4ForwardDualReadoutDetector.h
References _mapping_tower_file, and INPUTHEPMC::filename.
Referenced by PHG4ForwardDualReadoutSubsystem::InitRunSubsystem().
void PHG4ForwardDualReadoutDetector::SetXRot (G4double rot_in_x) inline
Definition at line 63 of file PHG4ForwardDualReadoutDetector.h.
View newest version in sPHENIX GitHub at line 63 of file PHG4ForwardDualReadoutDetector.h
References _rot_in_x.
void PHG4ForwardDualReadoutDetector::SetYRot (G4double rot_in_y) inline
Definition at line 64 of file PHG4ForwardDualReadoutDetector.h.
View newest version in sPHENIX GitHub at line 64 of file PHG4ForwardDualReadoutDetector.h
References _rot_in_y.
void PHG4ForwardDualReadoutDetector::SetZRot (G4double rot_in_z) inline
Definition at line 65 of file PHG4ForwardDualReadoutDetector.h.
View newest version in sPHENIX GitHub at line 65 of file PHG4ForwardDualReadoutDetector.h
References _rot_in_z.
void PHG4ForwardDualReadoutDetector::SuperDetector (const std::string & name) inline
Definition at line 75 of file PHG4ForwardDualReadoutDetector.h.
View newest version in sPHENIX GitHub at line 75 of file PHG4ForwardDualReadoutDetector.h
References _superdetector, and name.
Referenced by PHG4ForwardDualReadoutSubsystem::InitRunSubsystem(), and PHG4ForwardDualReadoutSteppingAction::SetInterfacePointers().
const std::string PHG4ForwardDualReadoutDetector::SuperDetector () const inline
Definition at line 77 of file PHG4ForwardDualReadoutDetector.h.
View newest version in sPHENIX GitHub at line 77 of file PHG4ForwardDualReadoutDetector.h
References _superdetector.
Member Data Documentation
int PHG4ForwardDualReadoutDetector::_absorber_Material private
Definition at line 141 of file PHG4ForwardDualReadoutDetector.h.
View newest version in sPHENIX GitHub at line 141 of file PHG4ForwardDualReadoutDetector.h
Referenced by ConstructTower(), ConstructTowerFCStyle(), and ParseParametersFromTable().
int PHG4ForwardDualReadoutDetector::_absorberactive private
Definition at line 150 of file PHG4ForwardDualReadoutDetector.h.
View newest version in sPHENIX GitHub at line 150 of file PHG4ForwardDualReadoutDetector.h
Referenced by IsInForwardDualReadout(), and SetAbsorberActive().
int PHG4ForwardDualReadoutDetector::_active private
Definition at line 149 of file PHG4ForwardDualReadoutDetector.h.
View newest version in sPHENIX GitHub at line 149 of file PHG4ForwardDualReadoutDetector.h
Referenced by IsActive(), IsInForwardDualReadout(), and SetActive().
int PHG4ForwardDualReadoutDetector::_blackhole private
Definition at line 152 of file PHG4ForwardDualReadoutDetector.h.
View newest version in sPHENIX GitHub at line 152 of file PHG4ForwardDualReadoutDetector.h
Referenced by BlackHole(), and IsBlackHole().
G4double PHG4ForwardDualReadoutDetector::_center_offset_x private
Definition at line 113 of file PHG4ForwardDualReadoutDetector.h.
View newest version in sPHENIX GitHub at line 113 of file PHG4ForwardDualReadoutDetector.h
Referenced by ConstructMe(), and ParseParametersFromTable().
G4double PHG4ForwardDualReadoutDetector::_center_offset_y private
Definition at line 114 of file PHG4ForwardDualReadoutDetector.h.
View newest version in sPHENIX GitHub at line 114 of file PHG4ForwardDualReadoutDetector.h
Referenced by ParseParametersFromTable().
G4double PHG4ForwardDualReadoutDetector::_cerenkovFiber_diam private
Definition at line 138 of file PHG4ForwardDualReadoutDetector.h.
View newest version in sPHENIX GitHub at line 138 of file PHG4ForwardDualReadoutDetector.h
Referenced by ConstructTower(), ConstructTowerFCStyle(), and ParseParametersFromTable().
int PHG4ForwardDualReadoutDetector::_cerenkovFiber_material private
Definition at line 139 of file PHG4ForwardDualReadoutDetector.h.
View newest version in sPHENIX GitHub at line 139 of file PHG4ForwardDualReadoutDetector.h
Referenced by ConstructTower(), ConstructTowerFCStyle(), and ParseParametersFromTable().
G4double PHG4ForwardDualReadoutDetector::_dPhi private
Definition at line 128 of file PHG4ForwardDualReadoutDetector.h.
View newest version in sPHENIX GitHub at line 128 of file PHG4ForwardDualReadoutDetector.h
Referenced by ConstructMe().
G4double PHG4ForwardDualReadoutDetector::_dZ private
Definition at line 126 of file PHG4ForwardDualReadoutDetector.h.
View newest version in sPHENIX GitHub at line 126 of file PHG4ForwardDualReadoutDetector.h
Referenced by ConstructMe(), and ParseParametersFromTable().
int PHG4ForwardDualReadoutDetector::_layer private
Definition at line 151 of file PHG4ForwardDualReadoutDetector.h.
View newest version in sPHENIX GitHub at line 151 of file PHG4ForwardDualReadoutDetector.h
Referenced by get_Layer().
std::map<std::string, towerposition> PHG4ForwardDualReadoutDetector::_map_tower private
Definition at line 159 of file PHG4ForwardDualReadoutDetector.h.
View newest version in sPHENIX GitHub at line 159 of file PHG4ForwardDualReadoutDetector.h
std::string PHG4ForwardDualReadoutDetector::_mapping_tower_file private
Definition at line 156 of file PHG4ForwardDualReadoutDetector.h.
View newest version in sPHENIX GitHub at line 156 of file PHG4ForwardDualReadoutDetector.h
Referenced by ParseParametersFromTable(), and SetTowerMappingFile().
G4String PHG4ForwardDualReadoutDetector::_materialAbsorber private
Definition at line 147 of file PHG4ForwardDualReadoutDetector.h.
View newest version in sPHENIX GitHub at line 147 of file PHG4ForwardDualReadoutDetector.h
Referenced by ConstructTower(), ConstructTowerFCStyle(), and SetMaterialAbsorber().
G4String PHG4ForwardDualReadoutDetector::_materialScintillator private
Definition at line 146 of file PHG4ForwardDualReadoutDetector.h.
View newest version in sPHENIX GitHub at line 146 of file PHG4ForwardDualReadoutDetector.h
Referenced by SetMaterialScintillator().
G4double PHG4ForwardDualReadoutDetector::_place_in_x private
Definition at line 110 of file PHG4ForwardDualReadoutDetector.h.
View newest version in sPHENIX GitHub at line 110 of file PHG4ForwardDualReadoutDetector.h
Referenced by ConstructMe(), ParseParametersFromTable(), and SetPlace().
G4double PHG4ForwardDualReadoutDetector::_place_in_y private
Definition at line 111 of file PHG4ForwardDualReadoutDetector.h.
View newest version in sPHENIX GitHub at line 111 of file PHG4ForwardDualReadoutDetector.h
Referenced by ConstructMe(), ParseParametersFromTable(), and SetPlace().
G4double PHG4ForwardDualReadoutDetector::_place_in_z private
Definition at line 112 of file PHG4ForwardDualReadoutDetector.h.
View newest version in sPHENIX GitHub at line 112 of file PHG4ForwardDualReadoutDetector.h
Referenced by ConstructMe(), ParseParametersFromTable(), and SetPlace().
int PHG4ForwardDualReadoutDetector::_quadratic_detector private
Definition at line 115 of file PHG4ForwardDualReadoutDetector.h.
View newest version in sPHENIX GitHub at line 115 of file PHG4ForwardDualReadoutDetector.h
Referenced by ConstructMe(), and ParseParametersFromTable().
G4double PHG4ForwardDualReadoutDetector::_rMax1 private
Definition at line 122 of file PHG4ForwardDualReadoutDetector.h.
View newest version in sPHENIX GitHub at line 122 of file PHG4ForwardDualReadoutDetector.h
Referenced by ConstructMe(), and ParseParametersFromTable().
G4double PHG4ForwardDualReadoutDetector::_rMax2 private
Definition at line 124 of file PHG4ForwardDualReadoutDetector.h.
View newest version in sPHENIX GitHub at line 124 of file PHG4ForwardDualReadoutDetector.h
Referenced by ConstructMe(), and ParseParametersFromTable().
G4double PHG4ForwardDualReadoutDetector::_rMin1 private
Definition at line 121 of file PHG4ForwardDualReadoutDetector.h.
View newest version in sPHENIX GitHub at line 121 of file PHG4ForwardDualReadoutDetector.h
Referenced by ConstructMe(), and ParseParametersFromTable().
G4double PHG4ForwardDualReadoutDetector::_rMin2 private
Definition at line 123 of file PHG4ForwardDualReadoutDetector.h.
View newest version in sPHENIX GitHub at line 123 of file PHG4ForwardDualReadoutDetector.h
Referenced by ConstructMe(), and ParseParametersFromTable().
G4double PHG4ForwardDualReadoutDetector::_rot_in_x private
Definition at line 117 of file PHG4ForwardDualReadoutDetector.h.
View newest version in sPHENIX GitHub at line 117 of file PHG4ForwardDualReadoutDetector.h
Referenced by ConstructMe(), ParseParametersFromTable(), and SetXRot().
G4double PHG4ForwardDualReadoutDetector::_rot_in_y private
Definition at line 118 of file PHG4ForwardDualReadoutDetector.h.
View newest version in sPHENIX GitHub at line 118 of file PHG4ForwardDualReadoutDetector.h
Referenced by ConstructMe(), ParseParametersFromTable(), and SetYRot().
G4double PHG4ForwardDualReadoutDetector::_rot_in_z private
Definition at line 119 of file PHG4ForwardDualReadoutDetector.h.
View newest version in sPHENIX GitHub at line 119 of file PHG4ForwardDualReadoutDetector.h
Referenced by ConstructMe(), ParseParametersFromTable(), and SetZRot().
G4double PHG4ForwardDualReadoutDetector::_scintFiber_diam private
Definition at line 137 of file PHG4ForwardDualReadoutDetector.h.
View newest version in sPHENIX GitHub at line 137 of file PHG4ForwardDualReadoutDetector.h
Referenced by ConstructTower(), ConstructTowerFCStyle(), and ParseParametersFromTable().
G4double PHG4ForwardDualReadoutDetector::_sPhi private
Definition at line 127 of file PHG4ForwardDualReadoutDetector.h.
View newest version in sPHENIX GitHub at line 127 of file PHG4ForwardDualReadoutDetector.h
Referenced by ConstructMe().
std::string PHG4ForwardDualReadoutDetector::_superdetector private
Definition at line 155 of file PHG4ForwardDualReadoutDetector.h.
View newest version in sPHENIX GitHub at line 155 of file PHG4ForwardDualReadoutDetector.h
Referenced by SuperDetector().
G4double PHG4ForwardDualReadoutDetector::_support_dw private
Definition at line 144 of file PHG4ForwardDualReadoutDetector.h.
View newest version in sPHENIX GitHub at line 144 of file PHG4ForwardDualReadoutDetector.h
G4double PHG4ForwardDualReadoutDetector::_tower_dx private
Definition at line 133 of file PHG4ForwardDualReadoutDetector.h.
View newest version in sPHENIX GitHub at line 133 of file PHG4ForwardDualReadoutDetector.h
Referenced by ConstructMe(), ConstructTower(), ConstructTowerFCStyle(), ParseParametersFromTable(), and SetTowerDimensions().
G4double PHG4ForwardDualReadoutDetector::_tower_dy private
Definition at line 134 of file PHG4ForwardDualReadoutDetector.h.
View newest version in sPHENIX GitHub at line 134 of file PHG4ForwardDualReadoutDetector.h
Referenced by ConstructMe(), ConstructTower(), ConstructTowerFCStyle(), ParseParametersFromTable(), and SetTowerDimensions().
G4double PHG4ForwardDualReadoutDetector::_tower_dz private
Definition at line 135 of file PHG4ForwardDualReadoutDetector.h.
View newest version in sPHENIX GitHub at line 135 of file PHG4ForwardDualReadoutDetector.h
Referenced by ConstructMe(), ConstructTower(), ConstructTowerFCStyle(), ParseParametersFromTable(), and SetTowerDimensions().
int PHG4ForwardDualReadoutDetector::_tower_makeNotched private
Definition at line 140 of file PHG4ForwardDualReadoutDetector.h.
View newest version in sPHENIX GitHub at line 140 of file PHG4ForwardDualReadoutDetector.h
Referenced by ConstructTower(), and ParseParametersFromTable().
G4double PHG4ForwardDualReadoutDetector::_tower_readout private
Definition at line 132 of file PHG4ForwardDualReadoutDetector.h.
View newest version in sPHENIX GitHub at line 132 of file PHG4ForwardDualReadoutDetector.h
Referenced by ConstructTower(), ConstructTowerFCStyle(), and ParseParametersFromTable().
int PHG4ForwardDualReadoutDetector::_tower_type private
Definition at line 131 of file PHG4ForwardDualReadoutDetector.h.
View newest version in sPHENIX GitHub at line 131 of file PHG4ForwardDualReadoutDetector.h
Referenced by ConstructMe(), and ParseParametersFromTable().
std::string PHG4ForwardDualReadoutDetector::_towerlogicnameprefix private
Definition at line 154 of file PHG4ForwardDualReadoutDetector.h.
View newest version in sPHENIX GitHub at line 154 of file PHG4ForwardDualReadoutDetector.h
Referenced by ConstructMe(), ConstructTower(), ConstructTowerFCStyle(), and IsInForwardDualReadout().
G4double PHG4ForwardDualReadoutDetector::_wls_dw private
Definition at line 143 of file PHG4ForwardDualReadoutDetector.h.
View newest version in sPHENIX GitHub at line 143 of file PHG4ForwardDualReadoutDetector.h
PHG4ForwardDualReadoutDisplayAction* PHG4ForwardDualReadoutDetector::m_DisplayAction private
Definition at line 106 of file PHG4ForwardDualReadoutDetector.h.
View newest version in sPHENIX GitHub at line 106 of file PHG4ForwardDualReadoutDetector.h
Referenced by ConstructMe(), ConstructTower(), and ConstructTowerFCStyle().
std::map<std::string, G4double> PHG4ForwardDualReadoutDetector::m_GlobalParameterMap private
Definition at line 157 of file PHG4ForwardDualReadoutDetector.h.
View newest version in sPHENIX GitHub at line 157 of file PHG4ForwardDualReadoutDetector.h
Referenced by ParseParametersFromTable().
PHG4ForwardDualReadoutSteppingAction* PHG4ForwardDualReadoutDetector::m_SteppingAction private
Definition at line 107 of file PHG4ForwardDualReadoutDetector.h.
View newest version in sPHENIX GitHub at line 107 of file PHG4ForwardDualReadoutDetector.h
Referenced by ParseParametersFromTable(), and SetSteppingAction().
The documentation for this class was generated from the following files:
fun4all_eicdetectors/blob/master/simulation/g4simulation/g4drcalo/PHG4ForwardDualReadoutDetector.h
fun4all_eicdetectors/blob/master/simulation/g4simulation/g4drcalo/PHG4ForwardDualReadoutDetector.cc