EIC Software: QAExample Class Reference
QAExample Class Reference
#include <fun4all_eic_qa/blob/master/source/QAExample.h>
Public Member Functions
QAExample (const std::string &name="QAExample")
virtual ~QAExample ()=default
int Init (PHCompositeNode *topNode)
int InitRun (PHCompositeNode *topNode)
int process_event (PHCompositeNode *topNode)
std::string get_histo_prefix ()
Public Member Functions inherited from SubsysReco
~SubsysReco () override
virtual int End (PHCompositeNode *)
Called at the end of all processing.
virtual int EndRun (const int)
Called at the end of each run.
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
void Print (const std::string &="ALL") const override
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Private Member Functions
int load_nodes (PHCompositeNode *)
load nodes
Private Attributes
PHG4TruthInfoContainer * m_truthContainer = nullptr
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = INT_MAX - 10
}
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Detailed Description
Definition at line 19 of file QAExample.h.
View newest version in sPHENIX GitHub at line 19 of file QAExample.h
Constructor & Destructor Documentation
QAExample::QAExample (const std::string & name = "QAExample")
Definition at line 26 of file QAExample.cc.
View newest version in sPHENIX GitHub at line 26 of file QAExample.cc
virtual QAExample::~QAExample () virtual default
Member Function Documentation
string QAExample::get_histo_prefix ()
Definition at line 120 of file QAExample.cc.
View newest version in sPHENIX GitHub at line 120 of file QAExample.cc
References Fun4AllBase::Name().
Referenced by Init(), and process_event().
int QAExample::Init (PHCompositeNode *) virtual
Called during initialization. Typically this is where you can book histograms, and e.g. register them to Fun4AllServer (so they can be output to file using Fun4AllServer::dumpHistos() method).
Reimplemented from SubsysReco.
Definition at line 36 of file QAExample.cc.
View newest version in sPHENIX GitHub at line 36 of file QAExample.cc
References Fun4AllReturnCodes::EVENT_OK, get_histo_prefix(), QAHistManagerDef::getHistoManager(), Acts::UnitConstants::h, and Fun4AllHistoManager::registerHisto().
int QAExample::InitRun (PHCompositeNode *) virtual
Called for first event when run number is known. Typically this is where you may want to fetch data from database, because you know the run number.
Reimplemented from SubsysReco.
Definition at line 31 of file QAExample.cc.
View newest version in sPHENIX GitHub at line 31 of file QAExample.cc
References Fun4AllReturnCodes::EVENT_OK.
int QAExample::load_nodes (PHCompositeNode * topNode) private
load nodes
Definition at line 105 of file QAExample.cc.
View newest version in sPHENIX GitHub at line 105 of file QAExample.cc
References Fun4AllReturnCodes::EVENT_OK, and m_truthContainer.
Referenced by process_event().
int QAExample::process_event (PHCompositeNode *) virtual
Called for each event. This is where you do the real work.
Reimplemented from SubsysReco.
Definition at line 56 of file QAExample.cc.
View newest version in sPHENIX GitHub at line 56 of file QAExample.cc
References Fun4AllReturnCodes::ABORTRUN, Fun4AllReturnCodes::EVENT_OK, get_histo_prefix(), PHG4Particle::get_px(), PHG4Particle::get_py(), PHG4Particle::get_pz(), Fun4AllHistoManager::getHisto(), QAHistManagerDef::getHistoManager(), PHG4TruthInfoContainer::GetPrimaryParticleRange(), PHG4Particle::identify(), load_nodes(), m_truthContainer, and Fun4AllBase::Verbosity().
Member Data Documentation
PHG4TruthInfoContainer* QAExample::m_truthContainer = nullptr private
Definition at line 36 of file QAExample.h.
View newest version in sPHENIX GitHub at line 36 of file QAExample.h
Referenced by load_nodes(), and process_event().
The documentation for this class was generated from the following files:
fun4all_eic_qa/blob/master/source/QAExample.h
fun4all_eic_qa/blob/master/source/QAExample.cc