EIC Software: KFParticle_truthAndDetTools Class Reference
KFParticle_truthAndDetTools Class Reference
#include <fun4all_coresoftware/blob/master/offline/packages/KFParticle_sPHENIX/KFParticle_truthAndDetTools.h>
Public Member Functions
KFParticle_truthAndDetTools ()
virtual ~KFParticle_truthAndDetTools ()
SvtxTrack * getTrack (unsigned int track_id, SvtxTrackMap *trackmap)
SvtxVertex * getVertex (unsigned int vertex_id, SvtxVertexMap *vertexmap)
void initializeTruthBranches (TTree *m_tree, int daughter_id, std::string daughter_number, bool m_constrain_to_vertex_truthMatch)
void fillTruthBranch (PHCompositeNode *topNode, TTree *m_tree, KFParticle daughter, int daughter_id, KFParticle vertex, bool m_constrain_to_vertex_truthMatch)
void initializeDetectorBranches (TTree *m_tree, int daughter_id, std::string daughter_number)
void initializeSubDetectorBranches (TTree *m_tree, std::string detectorName, int daughter_id, std::string daughter_number)
void fillDetectorBranch (PHCompositeNode *topNode, TTree *m_tree, KFParticle daughter, int daughter_id)
Protected Attributes
SvtxEvalStack * m_svtx_evalstack = nullptr
SvtxClusterEval * clustereval = nullptr
SvtxTruthEval * trutheval = nullptr
SvtxVertexEval * vertexeval = nullptr
SvtxTrackMap * dst_trackmap = nullptr
SvtxTrack * track = nullptr
PHG4Particle * g4particle = nullptr
PHG4VtxPoint * g4vertex_point = nullptr
SvtxVertexMap * dst_vertexmap = nullptr
SvtxVertex * vertex = nullptr
TrkrClusterContainer * dst_clustermap = nullptr
Private Attributes
float m_true_daughter_vertex_x [max_tracks] = {0}
float m_true_daughter_vertex_y [max_tracks] = {0}
float m_true_daughter_vertex_z [max_tracks] = {0}
float m_true_daughter_ip [max_tracks] = {0}
float m_true_daughter_ip_xy [max_tracks] = {0}
float m_true_daughter_px [max_tracks] = {0}
float m_true_daughter_py [max_tracks] = {0}
float m_true_daughter_pz [max_tracks] = {0}
float m_true_daughter_p [max_tracks] = {0}
float m_true_daughter_pt [max_tracks] = {0}
int m_true_daughter_id [max_tracks] = {0}
std::vector< float > detector_local_x [max_tracks]
std::vector< float > detector_local_y [max_tracks]
std::vector< float > detector_local_z [max_tracks]
std::vector< int > detector_layer [max_tracks]
std::vector< int > mvtx_staveID [max_tracks]
std::vector< int > mvtx_chipID [max_tracks]
std::vector< int > intt_ladderZID [max_tracks]
std::vector< int > intt_ladderPhiID [max_tracks]
std::vector< int > tpc_sectorID [max_tracks]
std::vector< int > tpc_side [max_tracks]
Static Private Attributes
static const int max_tracks = 20
Detailed Description
Definition at line 25 of file KFParticle_truthAndDetTools.h.
View newest version in sPHENIX GitHub at line 25 of file KFParticle_truthAndDetTools.h
Constructor & Destructor Documentation
KFParticle_truthAndDetTools::KFParticle_truthAndDetTools ()
Definition at line 40 of file KFParticle_truthAndDetTools.cc.
View newest version in sPHENIX GitHub at line 40 of file KFParticle_truthAndDetTools.cc
KFParticle_truthAndDetTools::~KFParticle_truthAndDetTools () virtual
Definition at line 45 of file KFParticle_truthAndDetTools.cc.
View newest version in sPHENIX GitHub at line 45 of file KFParticle_truthAndDetTools.cc
Member Function Documentation
void KFParticle_truthAndDetTools::fillDetectorBranch (PHCompositeNode * topNode, TTree * m_tree, KFParticle daughter, int daughter_id)
Definition at line 236 of file KFParticle_truthAndDetTools.cc.
View newest version in sPHENIX GitHub at line 236 of file KFParticle_truthAndDetTools.cc
References SvtxTrack::begin_cluster_keys(), detector_layer, detector_local_x, detector_local_y, detector_local_z, dst_clustermap, dst_trackmap, SvtxTrack::end_cluster_keys(), TrkrClusterContainer::findCluster(), PHNodeIterator::findFirst(), MvtxDefs::getChipId(), InttDefs::getLadderPhiId(), InttDefs::getLadderZId(), TrkrDefs::getLayer(), TpcDefs::getSectorId(), TpcDefs::getSide(), MvtxDefs::getStaveId(), getTrack(), TrkrDefs::getTrkrId(), TrkrCluster::getX(), TrkrCluster::getY(), TrkrCluster::getZ(), intt_ladderPhiID, intt_ladderZID, TrkrDefs::inttId, mvtx_chipID, mvtx_staveID, TrkrDefs::mvtxId, tpc_sectorID, tpc_side, TrkrDefs::tpcId, and track.
Referenced by KFParticle_nTuple::fillBranch().
void KFParticle_truthAndDetTools::fillTruthBranch (PHCompositeNode * topNode, TTree * m_tree, KFParticle daughter, int daughter_id, KFParticle vertex, bool m_constrain_to_vertex_truthMatch)
Definition at line 90 of file KFParticle_truthAndDetTools.cc.
View newest version in sPHENIX GitHub at line 90 of file KFParticle_truthAndDetTools.cc
References SvtxTrack::begin_cluster_keys(), clustereval, dst_trackmap, dst_vertexmap, PHNodeIterator::findFirst(), g4particle, g4vertex_point, SvtxEvalStack::get_cluster_eval(), PHG4Particle::get_pid(), PHG4Particle::get_px(), PHG4Particle::get_py(), PHG4Particle::get_pz(), SvtxEvalStack::get_truth_eval(), SvtxTruthEval::get_vertex(), SvtxEvalStack::get_vertex_eval(), PHG4VtxPoint::get_x(), SvtxVertex::get_x(), PHG4VtxPoint::get_y(), SvtxVertex::get_y(), PHG4VtxPoint::get_z(), SvtxVertex::get_z(), getTrack(), getVertex(), m_svtx_evalstack, m_true_daughter_id, m_true_daughter_ip, m_true_daughter_ip_xy, m_true_daughter_p, m_true_daughter_pt, m_true_daughter_px, m_true_daughter_py, m_true_daughter_pz, m_true_daughter_vertex_x, m_true_daughter_vertex_y, m_true_daughter_vertex_z, SvtxClusterEval::max_truth_particle_by_cluster_energy(), SvtxVertexEval::max_truth_point_by_ntracks(), SvtxEvalStack::next_event(), track, trutheval, and vertexeval.
Referenced by KFParticle_nTuple::fillBranch().
SvtxTrack * KFParticle_truthAndDetTools::getTrack (unsigned int track_id, SvtxTrackMap * trackmap)
Definition at line 47 of file KFParticle_truthAndDetTools.cc.
View newest version in sPHENIX GitHub at line 47 of file KFParticle_truthAndDetTools.cc
References SvtxTrackMap::begin(), and SvtxTrackMap::end().
Referenced by fillDetectorBranch(), KFParticle_DST::fillParticleNode_Track(), and fillTruthBranch().
SvtxVertex * KFParticle_truthAndDetTools::getVertex (unsigned int vertex_id, SvtxVertexMap * vertexmap)
Definition at line 61 of file KFParticle_truthAndDetTools.cc.
View newest version in sPHENIX GitHub at line 61 of file KFParticle_truthAndDetTools.cc
References SvtxVertexMap::begin(), and SvtxVertexMap::end().
Referenced by fillTruthBranch().
void KFParticle_truthAndDetTools::initializeDetectorBranches (TTree * m_tree, int daughter_id, std::string daughter_number)
Definition at line 204 of file KFParticle_truthAndDetTools.cc.
View newest version in sPHENIX GitHub at line 204 of file KFParticle_truthAndDetTools.cc
References detector_layer, detector_local_x, detector_local_y, detector_local_z, and initializeSubDetectorBranches().
Referenced by KFParticle_nTuple::initializeBranches().
void KFParticle_truthAndDetTools::initializeSubDetectorBranches (TTree * m_tree, std::string detectorName, int daughter_id, std::string daughter_number)
Definition at line 217 of file KFParticle_truthAndDetTools.cc.
View newest version in sPHENIX GitHub at line 217 of file KFParticle_truthAndDetTools.cc
References intt_ladderPhiID, intt_ladderZID, mvtx_chipID, mvtx_staveID, tpc_sectorID, and tpc_side.
Referenced by initializeDetectorBranches().
void KFParticle_truthAndDetTools::initializeTruthBranches (TTree * m_tree, int daughter_id, std::string daughter_number, bool m_constrain_to_vertex_truthMatch)
Definition at line 75 of file KFParticle_truthAndDetTools.cc.
View newest version in sPHENIX GitHub at line 75 of file KFParticle_truthAndDetTools.cc
References m_true_daughter_id, m_true_daughter_ip, m_true_daughter_ip_xy, m_true_daughter_p, m_true_daughter_pt, m_true_daughter_px, m_true_daughter_py, m_true_daughter_pz, m_true_daughter_vertex_x, m_true_daughter_vertex_y, and m_true_daughter_vertex_z.
Referenced by KFParticle_nTuple::initializeBranches().
Member Data Documentation
SvtxClusterEval* KFParticle_truthAndDetTools::clustereval = nullptr protected
Definition at line 43 of file KFParticle_truthAndDetTools.h.
View newest version in sPHENIX GitHub at line 43 of file KFParticle_truthAndDetTools.h
Referenced by fillTruthBranch().
std::vector<int> KFParticle_truthAndDetTools::detector_layer[max_tracks] private
Definition at line 76 of file KFParticle_truthAndDetTools.h.
View newest version in sPHENIX GitHub at line 76 of file KFParticle_truthAndDetTools.h
Referenced by fillDetectorBranch(), and initializeDetectorBranches().
std::vector<float> KFParticle_truthAndDetTools::detector_local_x[max_tracks] private
Definition at line 73 of file KFParticle_truthAndDetTools.h.
View newest version in sPHENIX GitHub at line 73 of file KFParticle_truthAndDetTools.h
Referenced by fillDetectorBranch(), and initializeDetectorBranches().
std::vector<float> KFParticle_truthAndDetTools::detector_local_y[max_tracks] private
Definition at line 74 of file KFParticle_truthAndDetTools.h.
View newest version in sPHENIX GitHub at line 74 of file KFParticle_truthAndDetTools.h
Referenced by fillDetectorBranch(), and initializeDetectorBranches().
std::vector<float> KFParticle_truthAndDetTools::detector_local_z[max_tracks] private
Definition at line 75 of file KFParticle_truthAndDetTools.h.
View newest version in sPHENIX GitHub at line 75 of file KFParticle_truthAndDetTools.h
Referenced by fillDetectorBranch(), and initializeDetectorBranches().
TrkrClusterContainer* KFParticle_truthAndDetTools::dst_clustermap = nullptr protected
Definition at line 56 of file KFParticle_truthAndDetTools.h.
View newest version in sPHENIX GitHub at line 56 of file KFParticle_truthAndDetTools.h
Referenced by fillDetectorBranch().
SvtxTrackMap* KFParticle_truthAndDetTools::dst_trackmap = nullptr protected
Definition at line 47 of file KFParticle_truthAndDetTools.h.
View newest version in sPHENIX GitHub at line 47 of file KFParticle_truthAndDetTools.h
Referenced by fillDetectorBranch(), and fillTruthBranch().
SvtxVertexMap* KFParticle_truthAndDetTools::dst_vertexmap = nullptr protected
Definition at line 53 of file KFParticle_truthAndDetTools.h.
View newest version in sPHENIX GitHub at line 53 of file KFParticle_truthAndDetTools.h
Referenced by fillTruthBranch().
PHG4Particle* KFParticle_truthAndDetTools::g4particle = nullptr protected
Definition at line 50 of file KFParticle_truthAndDetTools.h.
View newest version in sPHENIX GitHub at line 50 of file KFParticle_truthAndDetTools.h
Referenced by fillTruthBranch().
PHG4VtxPoint* KFParticle_truthAndDetTools::g4vertex_point = nullptr protected
Definition at line 51 of file KFParticle_truthAndDetTools.h.
View newest version in sPHENIX GitHub at line 51 of file KFParticle_truthAndDetTools.h
Referenced by fillTruthBranch().
std::vector<int> KFParticle_truthAndDetTools::intt_ladderPhiID[max_tracks] private
Definition at line 80 of file KFParticle_truthAndDetTools.h.
View newest version in sPHENIX GitHub at line 80 of file KFParticle_truthAndDetTools.h
Referenced by fillDetectorBranch(), and initializeSubDetectorBranches().
std::vector<int> KFParticle_truthAndDetTools::intt_ladderZID[max_tracks] private
Definition at line 79 of file KFParticle_truthAndDetTools.h.
View newest version in sPHENIX GitHub at line 79 of file KFParticle_truthAndDetTools.h
Referenced by fillDetectorBranch(), and initializeSubDetectorBranches().
SvtxEvalStack* KFParticle_truthAndDetTools::m_svtx_evalstack = nullptr protected
Definition at line 42 of file KFParticle_truthAndDetTools.h.
View newest version in sPHENIX GitHub at line 42 of file KFParticle_truthAndDetTools.h
Referenced by fillTruthBranch().
int KFParticle_truthAndDetTools::m_true_daughter_id[max_tracks] = {0} private
Definition at line 71 of file KFParticle_truthAndDetTools.h.
View newest version in sPHENIX GitHub at line 71 of file KFParticle_truthAndDetTools.h
Referenced by fillTruthBranch(), and initializeTruthBranches().
float KFParticle_truthAndDetTools::m_true_daughter_ip[max_tracks] = {0} private
Definition at line 64 of file KFParticle_truthAndDetTools.h.
View newest version in sPHENIX GitHub at line 64 of file KFParticle_truthAndDetTools.h
Referenced by fillTruthBranch(), and initializeTruthBranches().
float KFParticle_truthAndDetTools::m_true_daughter_ip_xy[max_tracks] = {0} private
Definition at line 65 of file KFParticle_truthAndDetTools.h.
View newest version in sPHENIX GitHub at line 65 of file KFParticle_truthAndDetTools.h
Referenced by fillTruthBranch(), and initializeTruthBranches().
float KFParticle_truthAndDetTools::m_true_daughter_p[max_tracks] = {0} private
Definition at line 69 of file KFParticle_truthAndDetTools.h.
View newest version in sPHENIX GitHub at line 69 of file KFParticle_truthAndDetTools.h
Referenced by fillTruthBranch(), and initializeTruthBranches().
float KFParticle_truthAndDetTools::m_true_daughter_pt[max_tracks] = {0} private
Definition at line 70 of file KFParticle_truthAndDetTools.h.
View newest version in sPHENIX GitHub at line 70 of file KFParticle_truthAndDetTools.h
Referenced by fillTruthBranch(), and initializeTruthBranches().
float KFParticle_truthAndDetTools::m_true_daughter_px[max_tracks] = {0} private
Definition at line 66 of file KFParticle_truthAndDetTools.h.
View newest version in sPHENIX GitHub at line 66 of file KFParticle_truthAndDetTools.h
Referenced by fillTruthBranch(), and initializeTruthBranches().
float KFParticle_truthAndDetTools::m_true_daughter_py[max_tracks] = {0} private
Definition at line 67 of file KFParticle_truthAndDetTools.h.
View newest version in sPHENIX GitHub at line 67 of file KFParticle_truthAndDetTools.h
Referenced by fillTruthBranch(), and initializeTruthBranches().
float KFParticle_truthAndDetTools::m_true_daughter_pz[max_tracks] = {0} private
Definition at line 68 of file KFParticle_truthAndDetTools.h.
View newest version in sPHENIX GitHub at line 68 of file KFParticle_truthAndDetTools.h
Referenced by fillTruthBranch(), and initializeTruthBranches().
float KFParticle_truthAndDetTools::m_true_daughter_vertex_x[max_tracks] = {0} private
Definition at line 61 of file KFParticle_truthAndDetTools.h.
View newest version in sPHENIX GitHub at line 61 of file KFParticle_truthAndDetTools.h
Referenced by fillTruthBranch(), and initializeTruthBranches().
float KFParticle_truthAndDetTools::m_true_daughter_vertex_y[max_tracks] = {0} private
Definition at line 62 of file KFParticle_truthAndDetTools.h.
View newest version in sPHENIX GitHub at line 62 of file KFParticle_truthAndDetTools.h
Referenced by fillTruthBranch(), and initializeTruthBranches().
float KFParticle_truthAndDetTools::m_true_daughter_vertex_z[max_tracks] = {0} private
Definition at line 63 of file KFParticle_truthAndDetTools.h.
View newest version in sPHENIX GitHub at line 63 of file KFParticle_truthAndDetTools.h
Referenced by fillTruthBranch(), and initializeTruthBranches().
const int KFParticle_truthAndDetTools::max_tracks = 20 static private
Definition at line 59 of file KFParticle_truthAndDetTools.h.
View newest version in sPHENIX GitHub at line 59 of file KFParticle_truthAndDetTools.h
std::vector<int> KFParticle_truthAndDetTools::mvtx_chipID[max_tracks] private
Definition at line 78 of file KFParticle_truthAndDetTools.h.
View newest version in sPHENIX GitHub at line 78 of file KFParticle_truthAndDetTools.h
Referenced by fillDetectorBranch(), and initializeSubDetectorBranches().
std::vector<int> KFParticle_truthAndDetTools::mvtx_staveID[max_tracks] private
Definition at line 77 of file KFParticle_truthAndDetTools.h.
View newest version in sPHENIX GitHub at line 77 of file KFParticle_truthAndDetTools.h
Referenced by fillDetectorBranch(), and initializeSubDetectorBranches().
std::vector<int> KFParticle_truthAndDetTools::tpc_sectorID[max_tracks] private
Definition at line 81 of file KFParticle_truthAndDetTools.h.
View newest version in sPHENIX GitHub at line 81 of file KFParticle_truthAndDetTools.h
Referenced by fillDetectorBranch(), and initializeSubDetectorBranches().
std::vector<int> KFParticle_truthAndDetTools::tpc_side[max_tracks] private
Definition at line 82 of file KFParticle_truthAndDetTools.h.
View newest version in sPHENIX GitHub at line 82 of file KFParticle_truthAndDetTools.h
Referenced by fillDetectorBranch(), and initializeSubDetectorBranches().
SvtxTrack* KFParticle_truthAndDetTools::track = nullptr protected
Definition at line 48 of file KFParticle_truthAndDetTools.h.
View newest version in sPHENIX GitHub at line 48 of file KFParticle_truthAndDetTools.h
Referenced by fillDetectorBranch(), and fillTruthBranch().
SvtxTruthEval* KFParticle_truthAndDetTools::trutheval = nullptr protected
Definition at line 44 of file KFParticle_truthAndDetTools.h.
View newest version in sPHENIX GitHub at line 44 of file KFParticle_truthAndDetTools.h
Referenced by fillTruthBranch().
SvtxVertex* KFParticle_truthAndDetTools::vertex = nullptr protected
Definition at line 54 of file KFParticle_truthAndDetTools.h.
View newest version in sPHENIX GitHub at line 54 of file KFParticle_truthAndDetTools.h
Referenced by KFParticle_sPHENIX::process_event().
SvtxVertexEval* KFParticle_truthAndDetTools::vertexeval = nullptr protected
Definition at line 45 of file KFParticle_truthAndDetTools.h.
View newest version in sPHENIX GitHub at line 45 of file KFParticle_truthAndDetTools.h
Referenced by fillTruthBranch().
The documentation for this class was generated from the following files:
fun4all_coresoftware/blob/master/offline/packages/KFParticle_sPHENIX/KFParticle_truthAndDetTools.h
fun4all_coresoftware/blob/master/offline/packages/KFParticle_sPHENIX/KFParticle_truthAndDetTools.cc