EIC Software: Acts::CylinderLayer Class Reference
Acts::CylinderLayer Class Reference
#include <fun4all_acts/blob/master/Core/include/Acts/Geometry/CylinderLayer.hpp>
Public Member Functions
CylinderLayer (const CylinderLayer &cla)=delete
Copy constructor - deleted.
CylinderLayer & operator= (const CylinderLayer &)=delete
Assignment operator for CylinderLayers - deleted.
CylinderLayer ()=delete
Default Constructor.
~CylinderLayer () override=default
Destructor.
const CylinderSurface & surfaceRepresentation () const override
CylinderSurface & surfaceRepresentation () override
Public Member Functions inherited from Acts::CylinderSurface
~CylinderSurface () override=default
Destructor - defaulted.
CylinderSurface ()=delete
Deleted default constructor.
CylinderSurface & operator= (const CylinderSurface &other)
const Vector3D binningPosition (const GeometryContext &gctx, BinningValue bValue) const final
const RotationMatrix3D referenceFrame (const GeometryContext &gctx, const Vector3D &position, const Vector3D &momentum) const final
SurfaceType type () const override
Return the surface type.
const Vector3D normal (const GeometryContext &gctx, const Vector2D &lposition) const final
const Vector3D normal (const GeometryContext &gctx, const Vector3D &position) const final
virtual const Vector3D rotSymmetryAxis (const GeometryContext &gctx) const
const CylinderBounds & bounds () const final
This method returns the CylinderBounds by reference.
void localToGlobal (const GeometryContext &gctx, const Vector2D &lposition, const Vector3D &momentum, Vector3D &position) const final
bool globalToLocal (const GeometryContext &gctx, const Vector3D &position, const Vector3D &momentum, Vector2D &lposition) const final
Intersection intersectionEstimate (const GeometryContext &gctx, const Vector3D &position, const Vector3D &direction, const BoundaryCheck &bcheck) const final
SurfaceIntersection intersect (const GeometryContext &gctx, const Vector3D &position, const Vector3D &direction, const BoundaryCheck &bcheck) const final
double pathCorrection (const GeometryContext &gctx, const Vector3D &position, const Vector3D &direction) const final
std::string name () const override
Return method for properly formatted output string.
Polyhedron polyhedronRepresentation (const GeometryContext &gctx, size_t lseg) const override
Public Member Functions inherited from Acts::Surface
virtual ~Surface ()
std::shared_ptr< Surface > getSharedPtr ()
std::shared_ptr< const Surface > getSharedPtr () const
Surface & operator= (const Surface &other)
virtual bool operator== (const Surface &other) const
virtual bool operator!= (const Surface &sf) const
virtual const Transform3D & transform (const GeometryContext &gctx) const
virtual const Vector3D center (const GeometryContext &gctx) const
virtual const Vector3D normal (const GeometryContext &gctx) const
const DetectorElementBase * associatedDetectorElement () const
const Layer * associatedLayer () const
void associateLayer (const Layer &lay)
const ISurfaceMaterial * surfaceMaterial () const
const std::shared_ptr< const
ISurfaceMaterial > & surfaceMaterialSharedPtr () const
void assignSurfaceMaterial (std::shared_ptr< const ISurfaceMaterial > material)
bool isOnSurface (const GeometryContext &gctx, const Vector3D &position, const Vector3D &momentum, const BoundaryCheck &bcheck=true) const
virtual bool insideBounds (const Vector2D &lposition, const BoundaryCheck &bcheck=true) const
virtual void initJacobianToGlobal (const GeometryContext &gctx, BoundToFreeMatrix &jacobian, const Vector3D &position, const Vector3D &direction, const BoundVector &pars) const
virtual const RotationMatrix3D initJacobianToLocal (const GeometryContext &gctx, FreeToBoundMatrix &jacobian, const Vector3D &position, const Vector3D &direction) const
virtual const BoundRowVector derivativeFactors (const GeometryContext &gctx, const Vector3D &position, const Vector3D &direction, const RotationMatrix3D &rft, const BoundToFreeMatrix &jacobian) const
virtual std::ostream & toStream (const GeometryContext &gctx, std::ostream &sl) const
Public Member Functions inherited from Acts::GeometryObject
GeometryObject ()=default
Defaulted construrctor.
GeometryObject (const GeometryObject &)=default
Defaulted copy constructor.
GeometryObject (const GeometryID &geoID)
GeometryObject & operator= (const GeometryObject &geoID)
const GeometryID & geoID () const
virtual double binningPositionValue (const GeometryContext &gctx, BinningValue bValue) const
void assignGeoID (const GeometryID &geoID)
Public Member Functions inherited from Acts::Layer
Layer ()=delete
Default Constructor - deleted.
Layer (const Layer &)=delete
Copy Constructor - deleted.
virtual ~Layer ()=default
Destructor.
Layer & operator= (const Layer &)=delete
const SurfaceArray * surfaceArray () const
Return the entire SurfaceArray, returns a nullptr if no SurfaceArray.
SurfaceArray * surfaceArray ()
Non-const version.
double thickness () const
virtual bool isOnLayer (const GeometryContext &gctx, const Vector3D &position, const BoundaryCheck &bcheck=true) const
const ApproachDescriptor * approachDescriptor () const
Return method for the approach descriptor, can be nullptr.
ApproachDescriptor * approachDescriptor ()
Non-const version of the approach descriptor.
template<typename options_t >
bool resolve (const options_t &options) const
virtual bool resolve (bool resolveSensitive, bool resolveMaterial, bool resolvePassive) const
template<typename options_t >
std::vector< SurfaceIntersection > compatibleSurfaces (const GeometryContext &gctx, const Vector3D &position, const Vector3D &direction, const options_t &options) const
Decompose Layer into (compatible) surfaces.
template<typename options_t >
const SurfaceIntersection surfaceOnApproach (const GeometryContext &gctx, const Vector3D &position, const Vector3D &direction, const options_t &options) const
const Layer * nextLayer (const GeometryContext &gctx, const Vector3D &position, const Vector3D &direction) const
const TrackingVolume * trackingVolume () const
const AbstractVolume * representingVolume () const
LayerType layerType () const
return the LayerType
Static Public Member Functions
static MutableLayerPtr create (const std::shared_ptr< const Transform3D > &transform, const std::shared_ptr< const CylinderBounds > &cbounds, std::unique_ptr< SurfaceArray > surfaceArray=nullptr, double thickness=0., std::unique_ptr< ApproachDescriptor > ad=nullptr, LayerType laytyp=passive)
Protected Member Functions
CylinderLayer (const std::shared_ptr< const Transform3D > &transform, const std::shared_ptr< const CylinderBounds > &cBounds, std::unique_ptr< SurfaceArray > surfaceArray=nullptr, double thickness=0., std::unique_ptr< ApproachDescriptor > ades=nullptr, LayerType laytyp=passive)
CylinderLayer (const CylinderLayer &cla, const Transform3D &shift)
Protected Member Functions inherited from Acts::CylinderSurface
CylinderSurface (std::shared_ptr< const CylinderBounds > cbounds, const DetectorElementBase &detelement)
CylinderSurface (std::shared_ptr< const Transform3D > htrans, double radius, double halfz, double halfphi=M_PI, double avphi=0.)
CylinderSurface (std::shared_ptr< const Transform3D > htrans, const std::shared_ptr< const CylinderBounds > &cbounds)
CylinderSurface (const CylinderSurface &other)
CylinderSurface (const GeometryContext &gctx, const CylinderSurface &other, const Transform3D &transf)
Protected Member Functions inherited from Acts::Surface
Surface (std::shared_ptr< const Transform3D > tform=nullptr)
Surface (const Surface &other)
Surface (const DetectorElementBase &detelement)
Surface (const GeometryContext &gctx, const Surface &other, const Transform3D &shift)
Protected Member Functions inherited from Acts::Layer
Layer (std::unique_ptr< SurfaceArray > surfaceArray, double thickness=0., std::unique_ptr< ApproachDescriptor > ades=nullptr, LayerType laytyp=passive)
void encloseTrackingVolume (const TrackingVolume &tvol)
Private Member Functions
void buildApproachDescriptor ()
build approach surfaces */
Additional Inherited Members
Public Types inherited from Acts::Surface
enum SurfaceType {
Cone = 0, Cylinder = 1, Disc = 2, Perigee = 3,
Plane = 4, Straw = 5, Curvilinear = 6, Other = 7
}
Protected Attributes inherited from Acts::CylinderSurface
std::shared_ptr< const
CylinderBounds > m_bounds
bounds (shared)
Protected Attributes inherited from Acts::Layer
NextLayers m_nextLayers
the previous Layer according to BinGenUtils
const BinUtility * m_nextLayerUtility = nullptr
std::unique_ptr< const
SurfaceArray > m_surfaceArray = nullptr
double m_layerThickness = 0.
Thickness of the Layer.
std::unique_ptr< const
ApproachDescriptor > m_approachDescriptor = nullptr
const TrackingVolume * m_trackingVolume = nullptr
the enclosing TrackingVolume
std::unique_ptr< AbstractVolume > m_representingVolume = nullptr
LayerType m_layerType
make a passive/active either way
int m_ssRepresentingSurface = 0
sub structure indication
int m_ssSensitiveSurfaces = 0
int m_ssApproachSurfaces = 0
Detailed Description
Class to describe a cylindrical detector layer for tracking, it inhertis from both, Layer base class and CylinderSurface class
Definition at line 34 of file CylinderLayer.hpp.
View newest version in sPHENIX GitHub at line 34 of file CylinderLayer.hpp
Constructor & Destructor Documentation
Acts::CylinderLayer::CylinderLayer (const CylinderLayer & cla) delete
Copy constructor - deleted.
Acts::CylinderLayer::CylinderLayer () delete
Default Constructor.
Referenced by create().
Acts::CylinderLayer::~CylinderLayer () override default
Destructor.
Acts::CylinderLayer::CylinderLayer (const std::shared_ptr< const Transform3D > & transform, const std::shared_ptr< const CylinderBounds > & cBounds, std::unique_ptr< SurfaceArray > surfaceArray = nullptr, double thickness = 0., std::unique_ptr< ApproachDescriptor > ades = nullptr, LayerType laytyp = passive) protected
Private constructor for CylinderLayer, called by create(args*) factory
Parameters
transform is the 3D transform that places the layer in 3D space
cbounds are the cylindrical bounds of the layer
surfaceArray is the Binned Array that holds the sensitive surfaces
thickness is the layer thickness (along the normal)
ad is the approach descriptor for approaching the layer
laytyp is the layer type
Returns
The return object is a shared poiter to the layer.
Definition at line 24 of file CylinderLayer.cpp.
View newest version in sPHENIX GitHub at line 24 of file CylinderLayer.cpp
References Acts::Layer::approachDescriptor(), Acts::Surface::associateLayer(), buildApproachDescriptor(), Acts::Layer::m_approachDescriptor, Acts::CylinderSurface::m_bounds, Acts::Layer::m_representingVolume, Acts::Layer::m_surfaceArray, Acts::Surface::m_transform, Acts::ApproachDescriptor::registerLayer(), and Acts::Layer::thickness().
Acts::CylinderLayer::CylinderLayer (const CylinderLayer & cla, const Transform3D & shift) protected
Private copy constructor with shift, called by create(args*)
Parameters
cla is the source cylinder layer for the copy
shift is the additional transform applied after cloning
Returns
The return object is a shared pointer to the layer.
Member Function Documentation
void Acts::CylinderLayer::buildApproachDescriptor () private
build approach surfaces */
Definition at line 59 of file CylinderLayer.cpp.
View newest version in sPHENIX GitHub at line 59 of file CylinderLayer.cpp
References Acts::tubeInnerCover, and Acts::tubeOuterCover.
Referenced by CylinderLayer().
static MutableLayerPtr Acts::CylinderLayer::create (const std::shared_ptr< const Transform3D > & transform, const std::shared_ptr< const CylinderBounds > & cbounds, std::unique_ptr< SurfaceArray > surfaceArray = nullptr, double thickness = 0., std::unique_ptr< ApproachDescriptor > ad = nullptr, LayerType laytyp = passive) inline static
Factory for shared Layer pointer create a shared, fully deployed CylinderLayer
Parameters
transform is the 3D transform that places the layer in 3D space
cbounds are the cylindrical bounds of the layer
surfaceArray is the Binned Array that holds the sensitive surfaces
thickness is the layer thickness (along the normal)
ad is the approach descriptor for approaching the layer
laytyp is the layer type
Returns
The return object is a shared poiter to the layer.
Definition at line 49 of file CylinderLayer.hpp.
View newest version in sPHENIX GitHub at line 49 of file CylinderLayer.hpp
References CylinderLayer(), Acts::Layer::surfaceArray(), and Acts::Layer::thickness().
Referenced by Acts::Test::Layers::BOOST_AUTO_TEST_CASE(), Acts::PassiveLayerBuilder::centralLayers(), Acts::DD4hepLayerBuilder::centralLayers(), Acts::constructCylinderVolume(), Acts::CylinderVolumeHelper::createCylinderLayer(), and Acts::LayerCreator::cylinderLayer().
CylinderLayer& Acts::CylinderLayer::operator= (const CylinderLayer &) delete
Assignment operator for CylinderLayers - deleted.
const Acts::CylinderSurface & Acts::CylinderLayer::surfaceRepresentation () const override virtual
Transforms the layer into a Surface representation This is for positioning and extrapolation
Implements Acts::Layer.
Definition at line 50 of file CylinderLayer.cpp.
View newest version in sPHENIX GitHub at line 50 of file CylinderLayer.cpp
Referenced by Acts::CylinderVolumeBuilder::analyzeContent().
Acts::CylinderSurface & Acts::CylinderLayer::surfaceRepresentation () override virtual
Implements Acts::Layer.
Definition at line 55 of file CylinderLayer.cpp.
View newest version in sPHENIX GitHub at line 55 of file CylinderLayer.cpp
The documentation for this class was generated from the following files:
fun4all_acts/blob/master/Core/include/Acts/Geometry/CylinderLayer.hpp
fun4all_acts/blob/master/Core/src/Geometry/CylinderLayer.cpp