EIC Software: RawTowerZDCDeadMap Class Reference
RawTowerZDCDeadMap Class Reference
#include <fun4all_eicdetectors/blob/master/reconstruction/eiczdcbase/RawTowerZDCDeadMap.h>
Public Types
typedef std::set
< RawTowerZDCDefs::keytype > Map
Public Member Functions
~RawTowerZDCDeadMap () override
void Reset () override
Clear Event.
int isValid () const override
isValid returns non zero if object contains vailid data
void identify (std::ostream &os=std::cout) const override
virtual void setCalorimeterID (RawTowerZDCDefs::CalorimeterId)
virtual
RawTowerZDCDefs::CalorimeterId getCalorimeterID ()
virtual void addDeadTower (const unsigned int ieta, const unsigned int iphi)
virtual void addDeadTower (RawTowerZDCDefs::keytype key)
virtual bool isDeadTower (RawTowerZDCDefs::keytype key)
virtual bool isDeadTower (const unsigned int ieta, const unsigned int iphi)
virtual const Map & getDeadTowers (void) const
return all towers
virtual Map & getDeadTowers (void)
virtual unsigned int size () const
Public Member Functions inherited from PHObject
PHObject ()
ctor
~PHObject () override
dtor
virtual PHObject * CloneMe () const
Virtual copy constructor.
virtual PHObject * clone () const final
PHObject * Clone (const char *newname="") const final
void Copy (TObject &object) const final
virtual int isValid (const float) const
virtual int isValid (const double) const
virtual int isValid (const int) const
virtual int isValid (const unsigned int) const
virtual int isImplemented (const float f) const
virtual int isImplemented (const double f) const
virtual int isImplemented (const int i) const
virtual int isImplemented (const unsigned int i) const
virtual int Integrate () const
virtual int Integrate (PHObject *)
virtual void CopyFrom (const PHObject *obj)
Protected Member Functions
RawTowerZDCDeadMap (RawTowerZDCDefs::CalorimeterId=RawTowerZDCDefs::NONE)
Detailed Description
Definition at line 11 of file RawTowerZDCDeadMap.h.
View newest version in sPHENIX GitHub at line 11 of file RawTowerZDCDeadMap.h
Member Typedef Documentation
typedef std::set<RawTowerZDCDefs::keytype> RawTowerZDCDeadMap::Map
Definition at line 14 of file RawTowerZDCDeadMap.h.
View newest version in sPHENIX GitHub at line 14 of file RawTowerZDCDeadMap.h
Constructor & Destructor Documentation
RawTowerZDCDeadMap::~RawTowerZDCDeadMap () inline override
Definition at line 16 of file RawTowerZDCDeadMap.h.
View newest version in sPHENIX GitHub at line 16 of file RawTowerZDCDeadMap.h
RawTowerZDCDeadMap::RawTowerZDCDeadMap (RawTowerZDCDefs::CalorimeterId = RawTowerZDCDefs::NONE) inline protected
Definition at line 37 of file RawTowerZDCDeadMap.h.
View newest version in sPHENIX GitHub at line 37 of file RawTowerZDCDeadMap.h
Member Function Documentation
virtual void RawTowerZDCDeadMap::addDeadTower (const unsigned int ieta, const unsigned int iphi) virtual
void RawTowerZDCDeadMap::addDeadTower (RawTowerZDCDefs::keytype key) virtual
Definition at line 23 of file RawTowerZDCDeadMap.cc.
View newest version in sPHENIX GitHub at line 23 of file RawTowerZDCDeadMap.cc
virtual RawTowerZDCDefs::CalorimeterId RawTowerZDCDeadMap::getCalorimeterID () inline virtual
Definition at line 24 of file RawTowerZDCDeadMap.h.
View newest version in sPHENIX GitHub at line 24 of file RawTowerZDCDeadMap.h
References RawTowerZDCDefs::NONE.
const RawTowerZDCDeadMap::Map & RawTowerZDCDeadMap::getDeadTowers (void) const virtual
return all towers
Definition at line 6 of file RawTowerZDCDeadMap.cc.
View newest version in sPHENIX GitHub at line 6 of file RawTowerZDCDeadMap.cc
RawTowerZDCDeadMap::Map & RawTowerZDCDeadMap::getDeadTowers (void) virtual
Definition at line 13 of file RawTowerZDCDeadMap.cc.
View newest version in sPHENIX GitHub at line 13 of file RawTowerZDCDeadMap.cc
void RawTowerZDCDeadMap::identify (std::ostream & os = std::cout) const override virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from PHObject.
Definition at line 46 of file RawTowerZDCDeadMap.cc.
View newest version in sPHENIX GitHub at line 46 of file RawTowerZDCDeadMap.cc
Referenced by RawTowerZDCDigitizer::CreateNodes().
bool RawTowerZDCDeadMap::isDeadTower (RawTowerZDCDefs::keytype key) virtual
Definition at line 27 of file RawTowerZDCDeadMap.cc.
View newest version in sPHENIX GitHub at line 27 of file RawTowerZDCDeadMap.cc
Referenced by RawTowerZDCDigitizer::process_event().
bool RawTowerZDCDeadMap::isDeadTower (const unsigned int ieta, const unsigned int iphi) virtual
Definition at line 32 of file RawTowerZDCDeadMap.cc.
View newest version in sPHENIX GitHub at line 32 of file RawTowerZDCDeadMap.cc
int RawTowerZDCDeadMap::isValid () const override virtual
isValid returns non zero if object contains vailid data
Reimplemented from PHObject.
Definition at line 37 of file RawTowerZDCDeadMap.cc.
View newest version in sPHENIX GitHub at line 37 of file RawTowerZDCDeadMap.cc
References size().
void RawTowerZDCDeadMap::Reset () override virtual
Clear Event.
Reimplemented from PHObject.
Definition at line 42 of file RawTowerZDCDeadMap.cc.
View newest version in sPHENIX GitHub at line 42 of file RawTowerZDCDeadMap.cc
virtual void RawTowerZDCDeadMap::setCalorimeterID (RawTowerZDCDefs::CalorimeterId) inline virtual
Definition at line 23 of file RawTowerZDCDeadMap.h.
View newest version in sPHENIX GitHub at line 23 of file RawTowerZDCDeadMap.h
virtual unsigned int RawTowerZDCDeadMap::size (void) const inline virtual
Definition at line 34 of file RawTowerZDCDeadMap.h.
View newest version in sPHENIX GitHub at line 34 of file RawTowerZDCDeadMap.h
Referenced by isValid().
The documentation for this class was generated from the following files:
fun4all_eicdetectors/blob/master/reconstruction/eiczdcbase/RawTowerZDCDeadMap.h
fun4all_eicdetectors/blob/master/reconstruction/eiczdcbase/RawTowerZDCDeadMap.cc