EIC Software: PndDipoleMap Class Reference
PndDipoleMap Class Reference
#include <EicRoot/blob/master/field/PndDipoleMap.h>
Public Member Functions
PndDipoleMap ()
PndDipoleMap (const char *mapName, const char *fileType="R", Double_t BeamMom=15.0)
PndDipoleMap (PndMapPar *fieldPar)
virtual ~PndDipoleMap ()
virtual Bool_t IsInside (Double_t x, Double_t y, Double_t z, Int_t &ix, Int_t &iy, Int_t &iz, Double_t &dx, Double_t &dy, Double_t &dz)
Int_t GetRegionNo ()
void GetBxyz (const Double_t point[3], Double_t *bField)
void FillParContainer ()
Public Member Functions inherited from PndFieldMap
PndFieldMap ()
PndFieldMap (const char *mapName, const char *fileType="R")
PndFieldMap (PndFieldPar *fieldPar)
virtual ~PndFieldMap ()
virtual void Init ()
virtual Double_t GetBx (Double_t x, Double_t y, Double_t z)
virtual Double_t GetBy (Double_t x, Double_t y, Double_t z)
virtual Double_t GetBz (Double_t x, Double_t y, Double_t z)
void WriteAsciiFile (const char *fileName)
void WriteRootFile (const char *fileName, const char *mapName)
void SetPosition (Double_t x, Double_t y, Double_t z)
void SetScale (Double_t factor)
Double_t GetXmin () const
Double_t GetYmin () const
Double_t GetZmin () const
Double_t GetXmax () const
Double_t GetYmax () const
Double_t GetZmax () const
Double_t GetXstep () const
Double_t GetYstep () const
Double_t GetZstep () const
Int_t GetNx () const
Int_t GetNy () const
Int_t GetNz () const
Double_t GetUnit () const
Double_t GetPositionX () const
Double_t GetPositionY () const
Double_t GetPositionZ () const
Double_t GetScale () const
TArrayF * GetBx () const
TArrayF * GetBy () const
TArrayF * GetBz () const
const char * GetFileName ()
virtual void Print ()
Public Attributes
Int_t fRegionNo
Static Public Attributes
static Int_t fNumberOfRegions =0
Protected Attributes
Double_t fHemiX
Double_t fHemiY
Double_t fBeamMom
Protected Attributes inherited from PndFieldMap
TString fFileName
Double_t fScale
Double_t funit
Double_t fPosX
Double_t fPosY
Double_t fPosZ
Double_t fXmin
Double_t fXmax
Double_t fXstep
Double_t fYmin
Double_t fYmax
Double_t fYstep
Double_t fZmin
Double_t fZmax
Double_t fZstep
Int_t fNx
Int_t fNy
Int_t fNz
TArrayF * fBx
TArrayF * fBy
TArrayF * fBz
Double_t fHa [2][2][2]
Double_t fHb [2][2]
Field at corners of a grid cell.
Double_t fHc [2]
Interpolated field (2-dim)
Additional Inherited Members
Protected Member Functions inherited from PndFieldMap
void Reset ()
void ReadAsciiFile (const char *fileName)
void ReadRootFile (const char *fileName, const char *mapName)
void SetField (const PndFieldMapData *data)
Double_t Interpolate (Double_t dx, Double_t dy, Double_t dz)
Detailed Description
Definition at line 27 of file PndDipoleMap.h.
View newest version in sPHENIX GitHub at line 27 of file PndDipoleMap.h
Constructor & Destructor Documentation
PndDipoleMap::PndDipoleMap ()
Default constructor
Definition at line 14 of file PndDipoleMap.cxx.
View newest version in sPHENIX GitHub at line 14 of file PndDipoleMap.cxx
PndDipoleMap::PndDipoleMap (const char * mapName, const char * fileType = "R", Double_t BeamMom = 15.0)
Standard constructor
Parameters
name Name of field map
fileType R = ROOT file, A = ASCII
Definition at line 24 of file PndDipoleMap.cxx.
View newest version in sPHENIX GitHub at line 24 of file PndDipoleMap.cxx
References fBeamMom, PndFieldMap::fFileName, fNumberOfRegions, fRegionNo, FairRunSim::GetBeamMom(), and FairRunSim::Instance().
PndDipoleMap::PndDipoleMap (PndMapPar * fieldPar)
Constructor from PndFieldPar
Definition at line 59 of file PndDipoleMap.cxx.
View newest version in sPHENIX GitHub at line 59 of file PndDipoleMap.cxx
References PndFieldMap::fBx, PndFieldMap::fBy, PndFieldMap::fBz, PndFieldMap::fFileName, PndFieldMap::fNx, PndFieldMap::fNy, PndFieldMap::fNz, PndFieldMap::fPosX, PndFieldMap::fPosY, PndFieldMap::fPosZ, PndFieldMap::fScale, PndFieldMap::funit, PndFieldMap::fXmax, PndFieldMap::fXmin, PndFieldMap::fXstep, PndFieldMap::fYmax, PndFieldMap::fYmin, PndFieldMap::fYstep, PndFieldMap::fZmax, PndFieldMap::fZmin, PndFieldMap::fZstep, PndMapPar::GetPositionX(), PndMapPar::GetPositionY(), PndMapPar::GetPositionZ(), PndMapPar::GetScale(), PndMapPar::GetType(), and PndMapPar::MapName().
PndDipoleMap::~PndDipoleMap () virtual
Destructor
Definition at line 96 of file PndDipoleMap.cxx.
View newest version in sPHENIX GitHub at line 96 of file PndDipoleMap.cxx
Member Function Documentation
void PndDipoleMap::FillParContainer ()
Definition at line 210 of file PndDipoleMap.cxx.
View newest version in sPHENIX GitHub at line 210 of file PndDipoleMap.cxx
void PndDipoleMap::GetBxyz (const Double_t point[3], Double_t * bField)
Definition at line 99 of file PndDipoleMap.cxx.
View newest version in sPHENIX GitHub at line 99 of file PndDipoleMap.cxx
References dx, dy, dz, PndFieldMap::fBx, PndFieldMap::fBy, PndFieldMap::fBz, PndFieldMap::fHa, fHemiX, fHemiY, PndFieldMap::fNy, PndFieldMap::fNz, PndFieldMap::Interpolate(), IsInside(), x, y, and z.
Int_t PndDipoleMap::GetRegionNo () inline
Definition at line 65 of file PndDipoleMap.h.
View newest version in sPHENIX GitHub at line 65 of file PndDipoleMap.h
References fRegionNo.
Referenced by PndMultiFieldPar::SetParameters().
Bool_t PndDipoleMap::IsInside (Double_t x, Double_t y, Double_t z, Int_t & ix, Int_t & iy, Int_t & iz, Double_t & dx, Double_t & dy, Double_t & dz) virtual
Determine whether a point is inside the field map
Parameters
x,y,z Point coordinates (global) [cm]
ix,iy,iz (return) Grid cell
dx,dy,dz (return) Distance from grid point [cm] if inside kTRUE if inside map, else kFALSE
Reimplemented from PndFieldMap.
Definition at line 166 of file PndDipoleMap.cxx.
View newest version in sPHENIX GitHub at line 166 of file PndDipoleMap.cxx
References fHemiX, fHemiY, PndFieldMap::fPosX, PndFieldMap::fPosY, PndFieldMap::fPosZ, PndFieldMap::fXmin, PndFieldMap::fXstep, PndFieldMap::fYmax, PndFieldMap::fYmin, PndFieldMap::fYstep, PndFieldMap::fZmax, PndFieldMap::fZmin, and PndFieldMap::fZstep.
Referenced by GetBxyz().
Member Data Documentation
Double_t PndDipoleMap::fBeamMom protected
Definition at line 76 of file PndDipoleMap.h.
View newest version in sPHENIX GitHub at line 76 of file PndDipoleMap.h
Referenced by PndDipoleMap().
Double_t PndDipoleMap::fHemiX protected
Definition at line 75 of file PndDipoleMap.h.
View newest version in sPHENIX GitHub at line 75 of file PndDipoleMap.h
Referenced by GetBxyz(), and IsInside().
Double_t PndDipoleMap::fHemiY protected
Definition at line 75 of file PndDipoleMap.h.
View newest version in sPHENIX GitHub at line 75 of file PndDipoleMap.h
Referenced by GetBxyz(), and IsInside().
Int_t PndDipoleMap::fNumberOfRegions =0 static
Definition at line 62 of file PndDipoleMap.h.
View newest version in sPHENIX GitHub at line 62 of file PndDipoleMap.h
Referenced by PndDipoleMap(), and PndMultiFieldPar::SetParameters().
Int_t PndDipoleMap::fRegionNo
Definition at line 63 of file PndDipoleMap.h.
View newest version in sPHENIX GitHub at line 63 of file PndDipoleMap.h
Referenced by GetRegionNo(), and PndDipoleMap().
The documentation for this class was generated from the following files:
EicRoot/blob/master/field/PndDipoleMap.h
EicRoot/blob/master/field/PndDipoleMap.cxx