EIC Software: fun4all_eicmacros/blob/master/common/G4_Pipe_EIC.C File Reference
G4_Pipe_EIC.C File Reference
#include <GlobalVariables.C>
#include <g4detectors/PHG4CylinderSubsystem.h>
#include <g4detectors/PHG4GDMLSubsystem.h>
#include <g4main/PHG4Reco.h>
#include <TSystem.h>
Namespaces
namespace Enable
namespace G4PIPE
Macros
#define MACRO_G4PIPEEIC_C
Functions
void PipeInit ()
double Pipe (PHG4Reco *g4Reco, double radius)
construct beam pipe
Variables
bool Enable::PIPE = false
bool Enable::PIPE_ABSORBER = false
bool Enable::PIPE_OVERLAPCHECK = false
int Enable::PIPE_VERBOSITY = 0
double G4PIPE::be_pipe_radius = 3.1000
double G4PIPE::be_pipe_thickness = 3.1762 - be_pipe_radius
double G4PIPE::be_pipe_length_plus = 66.8
double G4PIPE::be_pipe_length_neg = -79.8
bool G4PIPE::use_forward_pipes = false
Macro Definition Documentation
#define MACRO_G4PIPEEIC_C
Definition at line 2 of file G4_Pipe_EIC.C.
View newest version in sPHENIX GitHub at line 2 of file G4_Pipe_EIC.C
Function Documentation
double Pipe (PHG4Reco * g4Reco, double radius)
construct beam pipe
Definition at line 54 of file G4_Pipe_EIC.C.
View newest version in sPHENIX GitHub at line 54 of file G4_Pipe_EIC.C
References Enable::ABSORBER, G4PIPE::be_pipe_length, G4PIPE::be_pipe_length_neg, G4PIPE::be_pipe_length_plus, G4PIPE::be_pipe_radius, G4PIPE::be_pipe_thickness, max, no_overlapp, Enable::OVERLAPCHECK, PHG4DetectorSubsystem::OverlapCheck(), Enable::PIPE_ABSORBER, Enable::PIPE_OVERLAPCHECK, Enable::PIPE_VERBOSITY, G4BECAL::radius, PHG4Reco::registerSubsystem(), PHG4DetectorSubsystem::set_double_param(), PHG4DetectorSubsystem::set_int_param(), PHG4DetectorSubsystem::set_string_param(), PHG4DetectorSubsystem::SetActive(), PHG4DetectorSubsystem::SuperDetector(), G4PIPE::use_forward_pipes, and Enable::VERBOSITY.
Referenced by G4Setup(), and load_AllSi_geom().
void PipeInit ()
Definition at line 37 of file G4_Pipe_EIC.C.
View newest version in sPHENIX GitHub at line 37 of file G4_Pipe_EIC.C
References G4PIPE::be_pipe_length_neg, G4PIPE::be_pipe_length_plus, G4PIPE::be_pipe_radius, G4PIPE::be_pipe_thickness, max, BlackHoleGeometry::max_radius, BlackHoleGeometry::max_z, min, BlackHoleGeometry::min_z, and G4PIPE::use_forward_pipes.
Referenced by G4Init(), and load_AllSi_geom().