EIC Software: run_study Namespace Reference
run_study Namespace Reference
Functions
def LoadParamsTcl
def LoadParamsPythia
def WriteTclFile
def WritePythiaFile
def TransferTclFile
Variables
dictionary tclparams {}
dictionary pythiaparams {}
tuple parser argparse.ArgumentParser()
string help "name for this study set (e.g. bfield)"
tuple args parser.parse_args()
string SLURM_ARRAY_TASK_ID "0"
tuple value_index int(SLURM_ARRAY_TASK_ID)
int random_seed 0
string taskdir "%s/%d"
string tclfile "%s/customizations.tcl"
string cmndfile "%s/%s"
list copy_files [args.template]
tuple rndm_file open(taskdir+"/random_seed.dat", "w")
Function Documentation
def run_study.LoadParamsPythia (cmndfile)
Definition at line 66 of file run_study.py.
View newest version in sPHENIX GitHub at line 66 of file run_study.py
References Acts.open, and print().
def run_study.LoadParamsTcl (tclfile)
Definition at line 53 of file run_study.py.
View newest version in sPHENIX GitHub at line 53 of file run_study.py
References Acts.open, and print().
def run_study.TransferTclFile (tclfile, taskdir)
Definition at line 121 of file run_study.py.
View newest version in sPHENIX GitHub at line 121 of file run_study.py
References Acts.open.
def run_study.WritePythiaFile (output_filename)
Definition at line 100 of file run_study.py.
View newest version in sPHENIX GitHub at line 100 of file run_study.py
References Acts.open, and print().
def run_study.WriteTclFile (filename)
Definition at line 84 of file run_study.py.
View newest version in sPHENIX GitHub at line 84 of file run_study.py
References Acts.open, and print().
Variable Documentation
tuple run_study.args parser.parse_args()
Definition at line 147 of file run_study.py.
View newest version in sPHENIX GitHub at line 147 of file run_study.py
string run_study.cmndfile "%s/%s"
Definition at line 193 of file run_study.py.
View newest version in sPHENIX GitHub at line 193 of file run_study.py
list run_study.copy_files [args.template]
Definition at line 207 of file run_study.py.
View newest version in sPHENIX GitHub at line 207 of file run_study.py
string run_study.help "name for this study set (e.g. bfield)"
Definition at line 134 of file run_study.py.
View newest version in sPHENIX GitHub at line 134 of file run_study.py
tuple run_study.parser argparse.ArgumentParser()
Definition at line 131 of file run_study.py.
View newest version in sPHENIX GitHub at line 131 of file run_study.py
dictionary run_study.pythiaparams {}
Definition at line 50 of file run_study.py.
View newest version in sPHENIX GitHub at line 50 of file run_study.py
tuple run_study.random_seed 0
Definition at line 184 of file run_study.py.
View newest version in sPHENIX GitHub at line 184 of file run_study.py
tuple run_study.rndm_file open(taskdir+"/random_seed.dat", "w")
Definition at line 212 of file run_study.py.
View newest version in sPHENIX GitHub at line 212 of file run_study.py
list run_study.SLURM_ARRAY_TASK_ID "0"
Definition at line 158 of file run_study.py.
View newest version in sPHENIX GitHub at line 158 of file run_study.py
string run_study.taskdir "%s/%d"
Definition at line 191 of file run_study.py.
View newest version in sPHENIX GitHub at line 191 of file run_study.py
string run_study.tclfile "%s/customizations.tcl"
Definition at line 192 of file run_study.py.
View newest version in sPHENIX GitHub at line 192 of file run_study.py
dictionary run_study.tclparams {}
Definition at line 49 of file run_study.py.
View newest version in sPHENIX GitHub at line 49 of file run_study.py
tuple run_study.value_index int(SLURM_ARRAY_TASK_ID)
Definition at line 171 of file run_study.py.
View newest version in sPHENIX GitHub at line 171 of file run_study.py