EIC Software: FW::HepMC3Particle Struct Reference
FW::HepMC3Particle Struct Reference
Helper struct to convert HepMC3 particles to internal format.
#include <fun4all_acts/blob/master/Examples/Io/HepMC3/include/ACTFW/Plugins/HepMC3/HepMC3Particle.hpp>
Public Member Functions
std::unique_ptr< SimParticle > particle (const std::shared_ptr< HepMC3::GenParticle > particle)
Returns the particle translated into Acts.
int id (const std::shared_ptr< HepMC3::GenParticle > particle)
Returns the id of the particle translated into Acts.
std::unique_ptr< SimVertex > productionVertex (const std::shared_ptr< HepMC3::GenParticle > particle)
Returns the production vertex of the particle translated into Acts.
std::unique_ptr< SimVertex > endVertex (const std::shared_ptr< HepMC3::GenParticle > particle)
Returns the end vertex of the particle translated into Acts.
int pdgID (const std::shared_ptr< HepMC3::GenParticle > particle)
Returns the PDG code of a particle translated into Acts.
Acts::Vector3D momentum (const std::shared_ptr< HepMC3::GenParticle > particle)
Returns the momentum of a particle translated into Acts.
double energy (const std::shared_ptr< HepMC3::GenParticle > particle)
Returns the energy of a particle translated into Acts.
double mass (const std::shared_ptr< HepMC3::GenParticle > particle)
Returns the mass of a particle translated into Acts.
double charge (const std::shared_ptr< HepMC3::GenParticle > particle)
Returns the charge of a particle translated into Acts.
void pdgID (std::shared_ptr< HepMC3::GenParticle > particle, const int pid)
Sets the PDG code of a particle translated from Acts.
void momentum (std::shared_ptr< HepMC3::GenParticle > particle, const Acts::Vector3D &mom)
Sets the momentum of a particle translated from Acts.
void energy (std::shared_ptr< HepMC3::GenParticle > particle, const double energy)
Sets the energy of a particle translated from Acts.
void mass (std::shared_ptr< HepMC3::GenParticle > particle, const double mass)
Sets the mass of a particle translated from Acts.
Detailed Description
Helper struct to convert HepMC3 particles to internal format.
Definition at line 22 of file HepMC3Particle.hpp.
View newest version in sPHENIX GitHub at line 22 of file HepMC3Particle.hpp
Member Function Documentation
double FW::HepMC3Particle::charge (const std::shared_ptr< HepMC3::GenParticle > particle)
Returns the charge of a particle translated into Acts.
Parameters
particle HepMC3::GenParticle particle
Returns
charge of the particle
Definition at line 79 of file HepMC3Particle.cpp.
View newest version in sPHENIX GitHub at line 79 of file HepMC3Particle.cpp
References charge.
std::unique_ptr< FW::SimVertex > FW::HepMC3Particle::endVertex (const std::shared_ptr< HepMC3::GenParticle > particle)
Returns the end vertex of the particle translated into Acts.
Parameters
particle HepMC3::GenParticle particle
Returns
end vertex of the particle
Definition at line 43 of file HepMC3Particle.cpp.
View newest version in sPHENIX GitHub at line 43 of file HepMC3Particle.cpp
References FW::HepMC3Vertex::processVertex().
double FW::HepMC3Particle::energy (const std::shared_ptr< HepMC3::GenParticle > particle)
Returns the energy of a particle translated into Acts.
Parameters
particle HepMC3::GenParticle particle
Returns
energy of the particle
Definition at line 69 of file HepMC3Particle.cpp.
View newest version in sPHENIX GitHub at line 69 of file HepMC3Particle.cpp
Referenced by lepto(), lsmall(), and pepsimainerhic().
void FW::HepMC3Particle::energy (std::shared_ptr< HepMC3::GenParticle > particle, const double energy)
Sets the energy of a particle translated from Acts.
Parameters
particle HepMC3::GenParticle particle
energy energy that will be set
Definition at line 95 of file HepMC3Particle.cpp.
View newest version in sPHENIX GitHub at line 95 of file HepMC3Particle.cpp
int FW::HepMC3Particle::id (const std::shared_ptr< HepMC3::GenParticle > particle)
Returns the id of the particle translated into Acts.
Parameters
particle HepMC3::GenParticle particle
Returns
id of the particle
Definition at line 26 of file HepMC3Particle.cpp.
View newest version in sPHENIX GitHub at line 26 of file HepMC3Particle.cpp
Referenced by __example_6.f__(), __example_7.f__(), __example_8.f__(), attflv(), hijflv(), isdiquark(), ishadron(), islepton(), isparton(), luedit(), lux4jt(), medinit(), pybook(), pydump(), pyedit(), pyfact(), pyfill(), pyhiresd(), pyhist(), pykfin(), pynull(), pyplot(), pyresd(), pyrnmq(), pytbdy(), pytbhs(), and pyx4jt().
double FW::HepMC3Particle::mass (const std::shared_ptr< HepMC3::GenParticle > particle)
Returns the mass of a particle translated into Acts.
Parameters
particle HepMC3::GenParticle particle
Returns
mass of the particle
Definition at line 74 of file HepMC3Particle.cpp.
View newest version in sPHENIX GitHub at line 74 of file HepMC3Particle.cpp
void FW::HepMC3Particle::mass (std::shared_ptr< HepMC3::GenParticle > particle, const double mass)
Sets the mass of a particle translated from Acts.
Parameters
particle HepMC3::GenParticle particle
mass mass that will be set
Definition at line 102 of file HepMC3Particle.cpp.
View newest version in sPHENIX GitHub at line 102 of file HepMC3Particle.cpp
Acts::Vector3D FW::HepMC3Particle::momentum (const std::shared_ptr< HepMC3::GenParticle > particle)
Returns the momentum of a particle translated into Acts.
Parameters
particle HepMC3::GenParticle particle
Returns
momentum of the particle
Definition at line 60 of file HepMC3Particle.cpp.
View newest version in sPHENIX GitHub at line 60 of file HepMC3Particle.cpp
References charm_jet_coverage::mom.
void FW::HepMC3Particle::momentum (std::shared_ptr< HepMC3::GenParticle > particle, const Acts::Vector3D & mom)
Sets the momentum of a particle translated from Acts.
Parameters
particle HepMC3::GenParticle particle
mom momentum that will be set
Definition at line 89 of file HepMC3Particle.cpp.
View newest version in sPHENIX GitHub at line 89 of file HepMC3Particle.cpp
References charm_jet_coverage::mom.
std::unique_ptr< FW::SimParticle > FW::HepMC3Particle::particle (const std::shared_ptr< HepMC3::GenParticle > particle)
Returns the particle translated into Acts.
Parameters
particle HepMC3::GenParticle particle
Returns
corresponding Acts particle
Definition at line 13 of file HepMC3Particle.cpp.
View newest version in sPHENIX GitHub at line 13 of file HepMC3Particle.cpp
References charge, fw(), and ActsFatras::Barcode::setParticle().
Referenced by FW::HepMC3Event::beams(), FW::HepMC3Event::finalState(), FW::HepMC3Vertex::genParticlesToActs(), and FW::HepMC3Event::particles().
int FW::HepMC3Particle::pdgID (const std::shared_ptr< HepMC3::GenParticle > particle)
Returns the PDG code of a particle translated into Acts.
Parameters
particle HepMC3::GenParticle particle
Returns
PDG code of the particle
Definition at line 55 of file HepMC3Particle.cpp.
View newest version in sPHENIX GitHub at line 55 of file HepMC3Particle.cpp
void FW::HepMC3Particle::pdgID (std::shared_ptr< HepMC3::GenParticle > particle, const int pid)
Sets the PDG code of a particle translated from Acts.
Parameters
particle HepMC3::GenParticle particle
pid PDG code that will be set
Definition at line 84 of file HepMC3Particle.cpp.
View newest version in sPHENIX GitHub at line 84 of file HepMC3Particle.cpp
std::unique_ptr< FW::SimVertex > FW::HepMC3Particle::productionVertex (const std::shared_ptr< HepMC3::GenParticle > particle)
Returns the production vertex of the particle translated into Acts.
Parameters
particle HepMC3::GenParticle particle
Returns
production vertex of the particle
Definition at line 31 of file HepMC3Particle.cpp.
View newest version in sPHENIX GitHub at line 31 of file HepMC3Particle.cpp
References FW::HepMC3Vertex::processVertex().
The documentation for this struct was generated from the following files:
fun4all_acts/blob/master/Examples/Io/HepMC3/include/ACTFW/Plugins/HepMC3/HepMC3Particle.hpp
fun4all_acts/blob/master/Examples/Io/HepMC3/src/HepMC3Particle.cpp