EIC Software: EicFRichSteppingAction Class Reference
EicFRichSteppingAction Class Reference
#include <fun4all_eicdetectors/blob/master/simulation/g4simulation/g4lblvtx/EicFRichSteppingAction.h>
Public Member Functions
EicFRichSteppingAction (EicFRichDetector *, const PHParameters *parameters)
constructor
virtual ~EicFRichSteppingAction ()
destructor
virtual bool UserSteppingAction (const G4Step *, bool)
stepping action
virtual void SetInterfacePointers (PHCompositeNode *)
reimplemented from base class
EicFRichSteppingAction (EicFRichDetector *, const PHParameters *parameters)
constructor
virtual ~EicFRichSteppingAction ()
destructor
virtual bool UserSteppingAction (const G4Step *, bool)
stepping action
virtual void SetInterfacePointers (PHCompositeNode *)
reimplemented from base class
Public Member Functions inherited from PHG4SteppingAction
PHG4SteppingAction (const std::string &name, const int i=0)
virtual ~PHG4SteppingAction ()
virtual void Verbosity (const int i)
virtual int Verbosity () const
virtual int Init ()
virtual double GetScintLightYield (const G4Step *step)
get scintillation photon count. It require a custom set SCINTILLATIONYIELD property to work
virtual double GetVisibleEnergyDeposition (const G4Step *step)
get amount of energy that can make scintillation light, in Unit of GeV.
virtual void StoreLocalCoordinate (PHG4Hit *hit, const G4Step *step, const bool do_prepoint, const bool do_postpoint)
Extract local coordinate of the hit and save to PHG4Hit.
virtual void Print (const std::string &) const
std::string GetName () const
void SetName (const std::string &name)
virtual void SetLightCorrection (const double inner_radius, const double inner_corr, const double outer_radius, const double outer_corr)
virtual double GetLightCorrection (const double r) const
virtual double GetLightCorrection (const double xpos, const double ypos) const
virtual bool ValidCorrection () const
virtual void SetHitNodeName (const std::string &, const std::string &)
Set the G4HIT node names from Subsystem rather than constructing your own.
Private Attributes
EicFRichDetector * m_Detector
pointer to the detector
const PHParameters * m_Params
PHG4HitContainer * m_HitContainer
pointer to hit container
PHG4Hit * m_Hit
PHG4HitContainer * m_SaveHitContainer
G4VPhysicalVolume * m_SaveVolPre
G4VPhysicalVolume * m_SaveVolPost
int m_SaveTrackId
int m_SavePreStepStatus
int m_SavePostStepStatus
int m_ActiveFlag
int m_BlackHoleFlag
double m_EdepSum
double m_EionSum
Detailed Description
Definition at line 17 of file EicFRichSteppingAction.h.
View newest version in sPHENIX GitHub at line 17 of file EicFRichSteppingAction.h
Constructor & Destructor Documentation
EicFRichSteppingAction::EicFRichSteppingAction (EicFRichDetector * detector, const PHParameters * parameters)
constructor
Definition at line 63 of file EicFRichSteppingAction.cc.
View newest version in sPHENIX GitHub at line 63 of file EicFRichSteppingAction.cc
EicFRichSteppingAction::~EicFRichSteppingAction () virtual
destructor
Definition at line 83 of file EicFRichSteppingAction.cc.
View newest version in sPHENIX GitHub at line 83 of file EicFRichSteppingAction.cc
References m_Hit.
EicFRichSteppingAction::EicFRichSteppingAction (EicFRichDetector * , const PHParameters * parameters)
constructor
virtual EicFRichSteppingAction::~EicFRichSteppingAction () virtual
destructor
Member Function Documentation
void EicFRichSteppingAction::SetInterfacePointers (PHCompositeNode * topNode) virtual
reimplemented from base class
Reimplemented from PHG4SteppingAction.
Definition at line 347 of file EicFRichSteppingAction.cc.
View newest version in sPHENIX GitHub at line 347 of file EicFRichSteppingAction.cc
References PHG4Detector::GetName(), m_Detector, and m_HitContainer.
virtual void EicFRichSteppingAction::SetInterfacePointers (PHCompositeNode *) virtual
reimplemented from base class
Reimplemented from PHG4SteppingAction.
virtual bool EicFRichSteppingAction::UserSteppingAction (const G4Step * , bool) virtual
stepping action
Implements PHG4SteppingAction.
bool EicFRichSteppingAction::UserSteppingAction (const G4Step * aStep, bool was_used) virtual
stepping action
Implements PHG4SteppingAction.
Definition at line 94 of file EicFRichSteppingAction.cc.
View newest version in sPHENIX GitHub at line 94 of file EicFRichSteppingAction.cc
References PHG4HitContainer::AddHit(), Acts::UnitConstants::cm, PHG4Hit::get_hit_id(), PHG4Hit::get_x(), PHG4HitContainer::GetID(), PHG4SteppingAction::GetName(), PHG4StepStatusDecode::GetStepStatus(), Acts::UnitConstants::GeV, EicFRichDetector::IsInDetector(), m_BlackHoleFlag, m_Detector, m_EdepSum, m_EionSum, m_Hit, m_HitContainer, m_SaveHitContainer, m_SavePostStepStatus, m_SavePreStepStatus, m_SaveTrackId, m_SaveVolPost, m_SaveVolPre, p, PHG4Hit::Reset(), PHG4Hit::set_edep(), PHG4Hit::set_eion(), PHG4Hit::set_layer(), PHG4Hit::set_t(), PHG4Hit::set_trkid(), PHG4Hit::set_x(), PHG4Hit::set_y(), PHG4Hit::set_z(), and Acts::Test::volume.
Member Data Documentation
int EicFRichSteppingAction::m_ActiveFlag private
Definition at line 46 of file EicFRichSteppingAction.h.
View newest version in sPHENIX GitHub at line 46 of file EicFRichSteppingAction.h
int EicFRichSteppingAction::m_BlackHoleFlag private
Definition at line 47 of file EicFRichSteppingAction.h.
View newest version in sPHENIX GitHub at line 47 of file EicFRichSteppingAction.h
Referenced by UserSteppingAction().
EicFRichDetector * EicFRichSteppingAction::m_Detector private
pointer to the detector
Definition at line 34 of file EicFRichSteppingAction.h.
View newest version in sPHENIX GitHub at line 34 of file EicFRichSteppingAction.h
Referenced by SetInterfacePointers(), and UserSteppingAction().
double EicFRichSteppingAction::m_EdepSum private
Definition at line 48 of file EicFRichSteppingAction.h.
View newest version in sPHENIX GitHub at line 48 of file EicFRichSteppingAction.h
Referenced by UserSteppingAction().
double EicFRichSteppingAction::m_EionSum private
Definition at line 49 of file EicFRichSteppingAction.h.
View newest version in sPHENIX GitHub at line 49 of file EicFRichSteppingAction.h
Referenced by UserSteppingAction().
PHG4Hit * EicFRichSteppingAction::m_Hit private
Definition at line 38 of file EicFRichSteppingAction.h.
View newest version in sPHENIX GitHub at line 38 of file EicFRichSteppingAction.h
Referenced by UserSteppingAction(), and ~EicFRichSteppingAction().
PHG4HitContainer * EicFRichSteppingAction::m_HitContainer private
pointer to hit container
Definition at line 37 of file EicFRichSteppingAction.h.
View newest version in sPHENIX GitHub at line 37 of file EicFRichSteppingAction.h
Referenced by SetInterfacePointers(), and UserSteppingAction().
const PHParameters * EicFRichSteppingAction::m_Params private
Definition at line 35 of file EicFRichSteppingAction.h.
View newest version in sPHENIX GitHub at line 35 of file EicFRichSteppingAction.h
PHG4HitContainer * EicFRichSteppingAction::m_SaveHitContainer private
Definition at line 39 of file EicFRichSteppingAction.h.
View newest version in sPHENIX GitHub at line 39 of file EicFRichSteppingAction.h
Referenced by UserSteppingAction().
int EicFRichSteppingAction::m_SavePostStepStatus private
Definition at line 45 of file EicFRichSteppingAction.h.
View newest version in sPHENIX GitHub at line 45 of file EicFRichSteppingAction.h
Referenced by UserSteppingAction().
int EicFRichSteppingAction::m_SavePreStepStatus private
Definition at line 44 of file EicFRichSteppingAction.h.
View newest version in sPHENIX GitHub at line 44 of file EicFRichSteppingAction.h
Referenced by UserSteppingAction().
int EicFRichSteppingAction::m_SaveTrackId private
Definition at line 43 of file EicFRichSteppingAction.h.
View newest version in sPHENIX GitHub at line 43 of file EicFRichSteppingAction.h
Referenced by UserSteppingAction().
G4VPhysicalVolume * EicFRichSteppingAction::m_SaveVolPost private
Definition at line 41 of file EicFRichSteppingAction.h.
View newest version in sPHENIX GitHub at line 41 of file EicFRichSteppingAction.h
Referenced by UserSteppingAction().
G4VPhysicalVolume * EicFRichSteppingAction::m_SaveVolPre private
Definition at line 40 of file EicFRichSteppingAction.h.
View newest version in sPHENIX GitHub at line 40 of file EicFRichSteppingAction.h
Referenced by UserSteppingAction().
The documentation for this class was generated from the following files:
fun4all_eicdetectors/blob/master/simulation/g4simulation/g4lblvtx/EicFRichSteppingAction.h
g4lblvtx/blob/master/source/EicFRichSteppingAction.h
fun4all_eicdetectors/blob/master/simulation/g4simulation/g4lblvtx/EicFRichSteppingAction.cc
g4lblvtx/blob/master/source/EicFRichSteppingAction.cc