EIC Software: BeamPipeGeoParData Class Reference
BeamPipeGeoParData Class Reference
#include <EicRoot/blob/master/eic/infrastructure/BeamPipeGeoParData.h>
Public Member Functions
BeamPipeGeoParData (int version=-1, int subVersion=0)
~BeamPipeGeoParData ()
void AddElement (BeamPipeElement *element, BeamPipeElement::SwapSign swapped=BeamPipeElement::NoSwap)
void AddIpElement (BeamPipeElement *element)
int ConstructGeometry ()
Public Member Functions inherited from EicGeoParData
EicGeoParData (const char *detName=0, int version=-1, int subVersion=0)
~EicGeoParData ()
void ResetVars ()
void SetGeometryType (GeometryType gType)
GeometryType GetGeometryType () const
void SetTestGeometryFlag (bool flag=true)
bool IsTestGeometry () const
int GetVersion () const
int GetSubVersion () const
void SetFileName (const char *fileName)
void SetFileNameFormat (const char *fileNameFormat)
void SetComment (const char *comment)
int AttachSourceFile (const char *fileName)
void PrintAttachedSourceFile (const char *fileName)
EicGeoMap * CreateNewMap ()
int SetCircularX (unsigned group=0)
int SetCircularY (unsigned group=0)
int SetCircularZ (unsigned group=0)
bool GetCircularX (unsigned group=0) const
bool GetCircularY (unsigned group=0) const
bool GetCircularZ (unsigned group=0) const
bool GetCircular (unsigned group, unsigned what) const
int SetMappingTableEntry (EicGeoMap *map, const unsigned geant[], unsigned group, unsigned logical[])
int AddLogicalVolumeGroup (unsigned dimX=0, unsigned dimY=0, unsigned dimZ=0)
void AddBlackHoleVolume (const char *vName)
void AddStepEnforcedVolume (const char *vName)
void AddStepEnforcedVolumeLookupEntry (int volumeID, double step)
const TGeoMedium * GetMedium (const char *medium)
void SetTopVolumeTransformation (TGeoMatrix *transformation)
const TGeoMatrix * GetTopVolumeTransformation () const
TString GetGeometryFileName (bool root=true) const
virtual void Print (const char *option=0) const
virtual int ConstructGeometry (bool root=true, bool gdml=false, bool check=false)
TGeoVolume * GetTopVolume () const
TGeoManager * GetRootGeoManager ()
void FinalizeOutput (bool root=true, bool gdml=false, bool check=false)
UInt_t GetMapNum () const
EicGeoMap * GetMapPtrViaMapID (unsigned mapId) const
const EicGeoMap * GetMapPtrViaHitMultiIndex (ULong64_t multi) const
int CalculateMappingTableSignatures ()
unsigned GetMaxVolumeLevelNum () const
ULogicalIndex_t GeantMultiToLogicalIndex (ULong64_t multi) const
unsigned GetDimX (unsigned group=0) const
unsigned GetDimY (unsigned group=0) const
unsigned GetDimZ (unsigned group=0) const
unsigned GetDim (unsigned group, unsigned what) const
unsigned GetGroup (ULogicalIndex_t logicalID) const
unsigned GetX (ULogicalIndex_t logicalID) const
unsigned GetY (ULogicalIndex_t logicalID) const
unsigned GetZ (ULogicalIndex_t logicalID) const
unsigned GetCoord (unsigned what, ULogicalIndex_t logicalID) const
bool IsBlackHoleVolume (const char *vName) const
const std::set< TString > & GetBlackHoleVolumes () const
double GetEnforcedStep (int volumeID)
const std::set< TString > & GetStepEnforcedVolumes () const
void InitializeLookupTables ()
LogicalVolumeLookupTableEntry * GetLookupTableNode (ULogicalIndex_t xy) const
LogicalVolumeLookupTableEntry * GetLookupTableNode (const TGeoNode *node) const
EicNamePatternHub< Color_t > * GetColorTable ()
EicNamePatternHub< Char_t > * GetTransparencyTable ()
virtual bool AreNeighbours (ULogicalIndex_t l1, ULogicalIndex_t l2, unsigned maxLinearDist=1, unsigned maxChebyshevDist=0) const
const EicDetName * GetDetName () const
void AddWantedParticle (const char *vName, int pdg)
bool IsWantedParticle (const char *vName, int pdg) const
EicGeoParData (const char *detName=0, int version=-1, int subVersion=0)
~EicGeoParData ()
void ResetVars ()
void SetGeometryType (GeometryType gType)
GeometryType GetGeometryType () const
void SetTestGeometryFlag (bool flag=true)
bool IsTestGeometry () const
int GetVersion () const
int GetSubVersion () const
void SetFileName (const char *fileName)
void SetFileNameFormat (const char *fileNameFormat)
void SetTransparency (unsigned value)
void SetComment (const char *comment)
int AttachSourceFile (const char *fileName)
void PrintAttachedSourceFile (const char *fileName)
EicGeoMap * CreateNewMap ()
int SetCircularX (unsigned group=0)
int SetCircularY (unsigned group=0)
int SetCircularZ (unsigned group=0)
bool GetCircularX (unsigned group=0) const
bool GetCircularY (unsigned group=0) const
bool GetCircularZ (unsigned group=0) const
bool GetCircular (unsigned group, unsigned what) const
int SetMappingTableEntry (EicGeoMap *map, const unsigned geant[], unsigned group, unsigned logical[])
int AddLogicalVolumeGroup (unsigned dimX=0, unsigned dimY=0, unsigned dimZ=0)
void AddBlackHoleVolume (const char *vName)
void AddStepEnforcedVolume (const char *vName)
void AddStepEnforcedVolumeLookupEntry (int volumeID, double step)
const TGeoMedium * GetMedium (const char *medium)
void SetTopVolumeTransformation (TGeoMatrix *transformation)
const TGeoMatrix * GetTopVolumeTransformation () const
TString GetGeometryFileName (bool root=true) const
virtual void Print (const char *option=0) const
virtual int ConstructGeometry (bool root=true, bool gdml=false, bool check=false)
TGeoVolume * GetTopVolume () const
TGeoManager * GetRootGeoManager ()
void FinalizeOutput (bool root=true, bool gdml=false, bool check=false)
UInt_t GetMapNum () const
EicGeoMap * GetMapPtrViaMapID (unsigned mapId) const
const EicGeoMap * GetMapPtrViaHitMultiIndex (ULong64_t multi) const
int CalculateMappingTableSignatures ()
unsigned GetMaxVolumeLevelNum () const
ULogicalIndex_t GeantMultiToLogicalIndex (ULong64_t multi) const
void PlaceG4Volume (G4LogicalVolume *mother, bool check=false, void *pRot=0, void *tlate=0)
unsigned GetDimX (unsigned group=0) const
unsigned GetDimY (unsigned group=0) const
unsigned GetDimZ (unsigned group=0) const
unsigned GetDim (unsigned group, unsigned what) const
unsigned GetGroup (ULogicalIndex_t logicalID) const
unsigned GetX (ULogicalIndex_t logicalID) const
unsigned GetY (ULogicalIndex_t logicalID) const
unsigned GetZ (ULogicalIndex_t logicalID) const
unsigned GetCoord (unsigned what, ULogicalIndex_t logicalID) const
bool IsBlackHoleVolume (const char *vName) const
const std::set< TString > & GetBlackHoleVolumes () const
double GetEnforcedStep (int volumeID)
const std::set< TString > & GetStepEnforcedVolumes () const
void InitializeLookupTables ()
LogicalVolumeLookupTableEntry * GetLookupTableNode (ULogicalIndex_t xy) const
LogicalVolumeLookupTableEntry * GetLookupTableNode (const TGeoNode *node) const
EicNamePatternHub< Color_t > * GetColorTable ()
EicNamePatternHub< Char_t > * GetTransparencyTable ()
virtual bool AreNeighbours (ULogicalIndex_t l1, ULogicalIndex_t l2, unsigned maxLinearDist=1, unsigned maxChebyshevDist=0) const
const EicDetName * GetDetName () const
void AddWantedParticle (const char *vName, int pdg)
bool IsWantedParticle (const char *vName, int pdg) const
void SetTGeoGeometryCheckPrecision (double value)
void TurnTGeoGeometryCheckOff (void)
const std::vector
< G4VPhysicalVolume * > & GetG4Volumes (void) const
const std::map
< G4VPhysicalVolume
*, unsigned > & GetG4SensitiveVolumes (void) const
ClassDef (EicGeoParData, 51)
Private Member Functions
bool CheckGeometry ()
ClassDef (BeamPipeGeoParData, 8)
Private Attributes
Int_t mIpElementID
std::vector< BeamPipeElement * > mElements
IP element ID in mElements[].
Additional Inherited Members
Public Types inherited from EicGeoParData
enum GeometryType {
Undefined, NoStructure, SimpleStructure, FullStructure,
Undefined, NoStructure, SimpleStructure, FullStructure
}
enum IDXYZ {
IDX =0, IDY, IDZ, IDX =0,
IDY, IDZ
}
enum GeometryType {
Undefined, NoStructure, SimpleStructure, FullStructure,
Undefined, NoStructure, SimpleStructure, FullStructure
}
enum IDXYZ {
IDX =0, IDY, IDZ, IDX =0,
IDY, IDZ
}
Static Public Member Functions inherited from EicGeoParData
static int ImportMediaFile (const char *fname)
Protected Attributes inherited from EicGeoParData
GeometryType mGeometryType
Bool_t mTestGeometryFlag
EicDetName * mDetName
respective lookup table (for efficiency)
unsigned char mTransparency
Detailed Description
Definition at line 138 of file BeamPipeGeoParData.h.
View newest version in sPHENIX GitHub at line 138 of file BeamPipeGeoParData.h
Constructor & Destructor Documentation
BeamPipeGeoParData::BeamPipeGeoParData (int version = -1, int subVersion = 0) inline
Definition at line 143 of file BeamPipeGeoParData.h.
View newest version in sPHENIX GitHub at line 143 of file BeamPipeGeoParData.h
BeamPipeGeoParData::~BeamPipeGeoParData () inline
Definition at line 145 of file BeamPipeGeoParData.h.
View newest version in sPHENIX GitHub at line 145 of file BeamPipeGeoParData.h
Member Function Documentation
void BeamPipeGeoParData::AddElement (BeamPipeElement * element, BeamPipeElement::SwapSign swapped = BeamPipeElement::NoSwap) inline
Definition at line 149 of file BeamPipeGeoParData.h.
View newest version in sPHENIX GitHub at line 149 of file BeamPipeGeoParData.h
References mElements, and BeamPipeElement::NoSwap.
Referenced by beampipe().
void BeamPipeGeoParData::AddIpElement (BeamPipeElement * element) inline
Definition at line 154 of file BeamPipeGeoParData.h.
View newest version in sPHENIX GitHub at line 154 of file BeamPipeGeoParData.h
References mElements.
Referenced by beampipe().
bool BeamPipeGeoParData::CheckGeometry () private
Definition at line 17 of file BeamPipeGeoParData.cxx.
View newest version in sPHENIX GitHub at line 17 of file BeamPipeGeoParData.cxx
References BeamPipeElement::GetFirstOrientedSection(), BeamPipeElement::GetLength(), BeamPipeElement::mAccuOffset, mElements, BeamPipeElement::mIpElement, mIpElementID, BeamPipeSection::mOffset, BeamPipeSection::mOuterDiameter, BeamPipeElement::mSections, BeamPipeElement::mSwapped, BeamPipeElement::mThickness, printf(), and BeamPipeElement::Swap.
Referenced by ConstructGeometry().
BeamPipeGeoParData::ClassDef (BeamPipeGeoParData , 8) private
int BeamPipeGeoParData::ConstructGeometry ()
Definition at line 103 of file BeamPipeGeoParData.cxx.
View newest version in sPHENIX GitHub at line 103 of file BeamPipeGeoParData.cxx
References CheckGeometry(), EicGeoParData::FinalizeOutput(), BeamPipeElement::GetFirstSection(), BeamPipeElement::GetLastSection(), BeamPipeElement::GetLength(), EicGeoParData::GetMedium(), EicGeoParData::GetTopVolume(), BeamPipeElement::mAccuOffset, EicGeoParData::mDetName, mElements, BeamPipeElement::mIpElement, BeamPipeElement::mMaterial, BeamPipeSection::mOffset, BeamPipeSection::mOuterDiameter, BeamPipeElement::mSections, BeamPipeElement::mSwapped, BeamPipeElement::mThickness, name, EicDetName::Name(), and BeamPipeElement::Swap.
Referenced by beampipe().
Member Data Documentation
std::vector<BeamPipeElement*> BeamPipeGeoParData::mElements private
IP element ID in mElements[].
Definition at line 170 of file BeamPipeGeoParData.h.
View newest version in sPHENIX GitHub at line 170 of file BeamPipeGeoParData.h
Referenced by AddElement(), AddIpElement(), CheckGeometry(), and ConstructGeometry().
Int_t BeamPipeGeoParData::mIpElementID private
Definition at line 164 of file BeamPipeGeoParData.h.
View newest version in sPHENIX GitHub at line 164 of file BeamPipeGeoParData.h
Referenced by CheckGeometry().
The documentation for this class was generated from the following files:
EicRoot/blob/master/eic/infrastructure/BeamPipeGeoParData.h
EicRoot/blob/master/eic/infrastructure/BeamPipeGeoParData.cxx