EIC Software: FairBoxSetDraw Class Reference
FairBoxSetDraw Class Reference abstract
#include <EicRoot/blob/master/eventdisplay/FairBoxSetDraw.h>
Public Member Functions
FairBoxSetDraw ()
FairBoxSetDraw (const char *name, Int_t iVerbose=1)
virtual ~FairBoxSetDraw ()
virtual Double_t GetTimeWindowPlus ()
virtual Double_t GetTimeWindowMinus ()
virtual void SetVerbose (Int_t iVerbose)
virtual void SetBoxDimensions (Double_t x, Double_t y, Double_t z)
virtual void SetTimeWindowMinus (Double_t val)
virtual void SetTimeWindowPlus (Double_t val)
virtual void SetStartTime (Double_t val)
virtual void UseEventTimeAsStartTime (Bool_t val=kTRUE)
virtual void Exec (Option_t *option)
FairBoxSet * CreateBoxSet ()
void Reset ()
Public Member Functions inherited from FairTask
FairTask ()
FairTask (const char *name, Int_t iVerbose=1)
virtual ~FairTask ()
void InitTask ()
void ReInitTask ()
void SetParTask ()
virtual void FinishTask ()
virtual void FinishEvent ()
void SetVerbose (Int_t iVerbose)
void SetInputPersistance (Bool_t val)
void CheckInputPersistance (TString branchName)
Protected Member Functions
virtual void SetParContainers ()
virtual InitStatus Init ()
virtual void Finish ()
virtual TVector3 GetVector (TObject *obj)=0
virtual Int_t GetValue (TObject *obj, Int_t i)
virtual void AddBoxes (FairBoxSet *set, TObject *obj, Int_t i=0)
Protected Member Functions inherited from FairTask
virtual InitStatus ReInit ()
void InitTasks ()
void ReInitTasks ()
void SetParTasks ()
void FinishTasks ()
void FinishEvents ()
Protected Attributes
Int_t fVerbose
TClonesArray * fList
FairEventManager * fEventManager
FairRootManager * fManager
FairBoxSet * fq
Double_t fX
Double_t fY
Double_t fZ
Double_t fTimeWindowPlus
Double_t fTimeWindowMinus
Double_t fStartTime
Bool_t fUseEventTime
Protected Attributes inherited from FairTask
Int_t fVerbose
Int_t fInputPersistance
Indicates if input branch is persistant.
FairLogger * fLogger
Private Member Functions
FairBoxSetDraw (const FairBoxSetDraw &)
FairBoxSetDraw & operator= (const FairBoxSetDraw &)
ClassDef (FairBoxSetDraw, 1)
Private Attributes
BinaryFunctor * fStartFunctor
BinaryFunctor * fStopFunctor
Detailed Description
Definition at line 33 of file FairBoxSetDraw.h.
View newest version in sPHENIX GitHub at line 33 of file FairBoxSetDraw.h
Constructor & Destructor Documentation
FairBoxSetDraw::FairBoxSetDraw ()
Default constructor
Definition at line 24 of file FairBoxSetDraw.cxx.
View newest version in sPHENIX GitHub at line 24 of file FairBoxSetDraw.cxx
FairBoxSetDraw::FairBoxSetDraw (const char * name, Int_t iVerbose = 1)
Standard constructor
Parameters
name Name of task
iVerbose Verbosity level
Definition at line 47 of file FairBoxSetDraw.cxx.
View newest version in sPHENIX GitHub at line 47 of file FairBoxSetDraw.cxx
FairBoxSetDraw::~FairBoxSetDraw () virtual
Destructor
Definition at line 168 of file FairBoxSetDraw.cxx.
View newest version in sPHENIX GitHub at line 168 of file FairBoxSetDraw.cxx
FairBoxSetDraw::FairBoxSetDraw (const FairBoxSetDraw &) private
Member Function Documentation
void FairBoxSetDraw::AddBoxes (FairBoxSet * set, TObject * obj, Int_t i = 0) protected virtual
Definition at line 129 of file FairBoxSetDraw.cxx.
View newest version in sPHENIX GitHub at line 129 of file FairBoxSetDraw.cxx
References fVerbose, GetValue(), and GetVector().
Referenced by Exec().
FairBoxSetDraw::ClassDef (FairBoxSetDraw , 1) private
FairBoxSet * FairBoxSetDraw::CreateBoxSet ()
Definition at line 145 of file FairBoxSetDraw.cxx.
View newest version in sPHENIX GitHub at line 145 of file FairBoxSetDraw.cxx
Referenced by Exec().
void FairBoxSetDraw::Exec (Option_t * option) virtual
Executed task
Definition at line 95 of file FairBoxSetDraw.cxx.
View newest version in sPHENIX GitHub at line 95 of file FairBoxSetDraw.cxx
References AddBoxes(), CreateBoxSet(), data, fEventManager, fList, fStartFunctor, fStartTime, fStopFunctor, fTimeWindowMinus, fTimeWindowPlus, fUseEventTime, fVerbose, FairRootManager::GetData(), FairRootManager::GetEventTime(), FairRunAna::Instance(), FairRootManager::Instance(), p, and Reset().
void FairBoxSetDraw::Finish (void) protected virtual
Action after each event
Reimplemented from FairTask.
Definition at line 178 of file FairBoxSetDraw.cxx.
View newest version in sPHENIX GitHub at line 178 of file FairBoxSetDraw.cxx
virtual Double_t FairBoxSetDraw::GetTimeWindowMinus () inline virtual
Definition at line 52 of file FairBoxSetDraw.h.
View newest version in sPHENIX GitHub at line 52 of file FairBoxSetDraw.h
References fTimeWindowMinus.
Referenced by FairBoxSet::GetTimeWindowMinus().
virtual Double_t FairBoxSetDraw::GetTimeWindowPlus () inline virtual
Definition at line 51 of file FairBoxSetDraw.h.
View newest version in sPHENIX GitHub at line 51 of file FairBoxSetDraw.h
References fTimeWindowPlus.
Referenced by FairBoxSet::GetTimeWindowPlus().
Int_t FairBoxSetDraw::GetValue (TObject * obj, Int_t i) protected virtual
Reimplemented in FairTimeStampPointDraw.
Definition at line 140 of file FairBoxSetDraw.cxx.
View newest version in sPHENIX GitHub at line 140 of file FairBoxSetDraw.cxx
Referenced by AddBoxes().
virtual TVector3 FairBoxSetDraw::GetVector (TObject * obj) protected pure virtual
Implemented in FairHitDraw, and FairTimeStampPointDraw.
Referenced by AddBoxes().
InitStatus FairBoxSetDraw::Init (void) protected virtual
Intialisation at begin of run. To be implemented in the derived class. Success If not kSUCCESS, task will be set inactive.
Reimplemented from FairTask.
Definition at line 66 of file FairBoxSetDraw.cxx.
View newest version in sPHENIX GitHub at line 66 of file FairBoxSetDraw.cxx
References fEventManager, fList, fManager, fStartFunctor, fStopFunctor, fVerbose, FairRootManager::GetObject(), FairEventManager::Instance(), FairRootManager::Instance(), kERROR, and kSUCCESS.
FairBoxSetDraw& FairBoxSetDraw::operator= (const FairBoxSetDraw &) private
void FairBoxSetDraw::Reset ()
Definition at line 182 of file FairBoxSetDraw.cxx.
View newest version in sPHENIX GitHub at line 182 of file FairBoxSetDraw.cxx
References fEventManager.
Referenced by Exec().
virtual void FairBoxSetDraw::SetBoxDimensions (Double_t x, Double_t y, Double_t z) inline virtual
Definition at line 56 of file FairBoxSetDraw.h.
View newest version in sPHENIX GitHub at line 56 of file FairBoxSetDraw.h
References fX, fY, fZ, x, y, and z.
void FairBoxSetDraw::SetParContainers () protected virtual
Intialise parameter containers. To be implemented in the derived class.
Reimplemented from FairTask.
Definition at line 172 of file FairBoxSetDraw.cxx.
View newest version in sPHENIX GitHub at line 172 of file FairBoxSetDraw.cxx
virtual void FairBoxSetDraw::SetStartTime (Double_t val) inline virtual
Definition at line 64 of file FairBoxSetDraw.h.
View newest version in sPHENIX GitHub at line 64 of file FairBoxSetDraw.h
References fStartTime.
void FairBoxSetDraw::SetTimeWindowMinus (Double_t val) virtual
Definition at line 157 of file FairBoxSetDraw.cxx.
View newest version in sPHENIX GitHub at line 157 of file FairBoxSetDraw.cxx
References fTimeWindowMinus.
Referenced by FairBoxSet::SetTimeWindowMinus().
void FairBoxSetDraw::SetTimeWindowPlus (Double_t val) virtual
Definition at line 162 of file FairBoxSetDraw.cxx.
View newest version in sPHENIX GitHub at line 162 of file FairBoxSetDraw.cxx
References fTimeWindowPlus.
Referenced by FairBoxSet::SetTimeWindowPlus().
virtual void FairBoxSetDraw::SetVerbose (Int_t iVerbose) inline virtual
Set verbosity level. For this task and all of the subtasks.
Definition at line 55 of file FairBoxSetDraw.h.
View newest version in sPHENIX GitHub at line 55 of file FairBoxSetDraw.h
References fVerbose.
virtual void FairBoxSetDraw::UseEventTimeAsStartTime (Bool_t val = kTRUE) inline virtual
Definition at line 65 of file FairBoxSetDraw.h.
View newest version in sPHENIX GitHub at line 65 of file FairBoxSetDraw.h
References fUseEventTime.
Member Data Documentation
FairEventManager* FairBoxSetDraw::fEventManager protected
Definition at line 87 of file FairBoxSetDraw.h.
View newest version in sPHENIX GitHub at line 87 of file FairBoxSetDraw.h
Referenced by Exec(), Init(), and Reset().
TClonesArray* FairBoxSetDraw::fList protected
Definition at line 86 of file FairBoxSetDraw.h.
View newest version in sPHENIX GitHub at line 86 of file FairBoxSetDraw.h
Referenced by Exec(), and Init().
FairRootManager* FairBoxSetDraw::fManager protected
Definition at line 88 of file FairBoxSetDraw.h.
View newest version in sPHENIX GitHub at line 88 of file FairBoxSetDraw.h
Referenced by Init().
FairBoxSet* FairBoxSetDraw::fq protected
Definition at line 89 of file FairBoxSetDraw.h.
View newest version in sPHENIX GitHub at line 89 of file FairBoxSetDraw.h
BinaryFunctor* FairBoxSetDraw::fStartFunctor private
Definition at line 101 of file FairBoxSetDraw.h.
View newest version in sPHENIX GitHub at line 101 of file FairBoxSetDraw.h
Referenced by Exec(), and Init().
Double_t FairBoxSetDraw::fStartTime protected
Definition at line 94 of file FairBoxSetDraw.h.
View newest version in sPHENIX GitHub at line 94 of file FairBoxSetDraw.h
Referenced by Exec(), and SetStartTime().
BinaryFunctor* FairBoxSetDraw::fStopFunctor private
Definition at line 102 of file FairBoxSetDraw.h.
View newest version in sPHENIX GitHub at line 102 of file FairBoxSetDraw.h
Referenced by Exec(), and Init().
Double_t FairBoxSetDraw::fTimeWindowMinus protected
Definition at line 93 of file FairBoxSetDraw.h.
View newest version in sPHENIX GitHub at line 93 of file FairBoxSetDraw.h
Referenced by Exec(), GetTimeWindowMinus(), and SetTimeWindowMinus().
Double_t FairBoxSetDraw::fTimeWindowPlus protected
Definition at line 92 of file FairBoxSetDraw.h.
View newest version in sPHENIX GitHub at line 92 of file FairBoxSetDraw.h
Referenced by Exec(), GetTimeWindowPlus(), and SetTimeWindowPlus().
Bool_t FairBoxSetDraw::fUseEventTime protected
Definition at line 95 of file FairBoxSetDraw.h.
View newest version in sPHENIX GitHub at line 95 of file FairBoxSetDraw.h
Referenced by Exec(), and UseEventTimeAsStartTime().
Int_t FairBoxSetDraw::fVerbose protected
Definition at line 76 of file FairBoxSetDraw.h.
View newest version in sPHENIX GitHub at line 76 of file FairBoxSetDraw.h
Referenced by AddBoxes(), Exec(), Init(), and SetVerbose().
Double_t FairBoxSetDraw::fX protected
Definition at line 90 of file FairBoxSetDraw.h.
View newest version in sPHENIX GitHub at line 90 of file FairBoxSetDraw.h
Referenced by SetBoxDimensions().
Double_t FairBoxSetDraw::fY protected
Definition at line 90 of file FairBoxSetDraw.h.
View newest version in sPHENIX GitHub at line 90 of file FairBoxSetDraw.h
Referenced by SetBoxDimensions().
Double_t FairBoxSetDraw::fZ protected
Definition at line 90 of file FairBoxSetDraw.h.
View newest version in sPHENIX GitHub at line 90 of file FairBoxSetDraw.h
Referenced by SetBoxDimensions().
The documentation for this class was generated from the following files:
EicRoot/blob/master/eventdisplay/FairBoxSetDraw.h
EicRoot/blob/master/eventdisplay/FairBoxSetDraw.cxx