EIC Software: EicToyModel/blob/master/source/EtmOrphans.cc File Reference
EtmOrphans.cc File Reference
#include <math.h>
#include <TString.h>
#include <EtmOrphans.h>
Functions
bool ConditionChecker (bool condition, const char *fmt, const char *message)
double Eta2Theta (double eta)
double Theta2Eta (double theta)
Function Documentation
bool ConditionChecker (bool condition, const char * fmt, const char * message)
Definition at line 16 of file EtmOrphans.cc.
View newest version in sPHENIX GitHub at line 16 of file EtmOrphans.cc
References printf().
Referenced by EicToyModel::zoom().
double Eta2Theta (double eta)
Definition at line 28 of file EtmOrphans.cc.
View newest version in sPHENIX GitHub at line 28 of file EtmOrphans.cc
Referenced by EicToyModel::CalculateEtaEndPoint(), EicToyModel::CalculateEtaStartPoint(), EtmAzimuthalScan::DoIt(), and EicToyModel::DrawFlatFieldLines().
double Theta2Eta (double theta)
Definition at line 35 of file EtmOrphans.cc.
View newest version in sPHENIX GitHub at line 35 of file EtmOrphans.cc