EIC Software: eicpy.build Namespace Reference
eicpy.build Namespace Reference
Classes
class File
Functions
def processor
def build_list
def parse
Variables
dictionary ZIP {'.gz': 'gzip', '.bz2': 'bzip2'}
dictionary UNZIP {'.gz': 'gunzip', '.bz2': 'bunzip2'}
tuple options parse()
tuple files file.read()
Function Documentation
def eicpy.build.build_list (filelist, outdir = '.', nevents = -1, nthreads = 1, rezip = True)
Build ROOT tree files from all the listed files.
Arguments:
filelist -- a list of file names
outdir -- the directory to which to write ROOT files [current directory]
nevents -- the maximum number of events per file to process [all]
nthreads -- the maximum number of threads permitted to run [1]
Zipped files (either gzip or bzip2) are unzipped then rezipped
after the ROOT file has been made.
Definition at line 103 of file build.py.
View newest version in sPHENIX GitHub at line 103 of file build.py
def eicpy.build.parse ()
Process command line arguments and return argparse Namespace.
Definition at line 128 of file build.py.
View newest version in sPHENIX GitHub at line 128 of file build.py
def eicpy.build.processor ()
Function run by each thread.
Pops Files from the queue and processes them until there are no files
remaining.
Definition at line 91 of file build.py.
View newest version in sPHENIX GitHub at line 91 of file build.py
Variable Documentation
list eicpy.build.files file.read()
Definition at line 171 of file build.py.
View newest version in sPHENIX GitHub at line 171 of file build.py
Referenced by CharmJetClassification(), CharmJetGlobalTagger(), CharmTagPlots(), compareRootFiles(), CbmStudyReport.Create(), fileVector(), KaonIDStudy(), main(), StrangeJetClassification(), and StrangeTagPlots().
tuple eicpy.build.options parse()
Definition at line 148 of file build.py.
View newest version in sPHENIX GitHub at line 148 of file build.py
Referenced by Acts::Test.BOOST_AUTO_TEST_CASE(), Acts::Test.BOOST_DATA_TEST_CASE(), BOOST_DATA_TEST_CASE(), Acts::Layer.compatibleSurfaces(), ActsExamples::PropagationAlgorithm< propagator_t >.executeTest(), main(), Acts::VolumeMaterialMapper.mapMaterialTrack(), Acts::SurfaceMaterialMapper.mapMaterialTrack(), ActsExamples::Options.parse(), Acts::RiddersPropagator< propagator_t >.propagate(), Acts::Propagator< stepper_t, navigator_t >.propagate(), PHActsVertexPropagator.propagateTrack(), PHActsTrackProjection.propagateTrack(), PHTpcResiduals.propagateTrackState(), ActsFatras::ParticleSimulator< propagator_t, physics_list_t, hit_surface_selector_t >.simulate(), transportFreely(), and transportToSurface().
dictionary eicpy.build.UNZIP {'.gz': 'gunzip', '.bz2': 'bunzip2'}
Definition at line 26 of file build.py.
View newest version in sPHENIX GitHub at line 26 of file build.py
dictionary eicpy.build.ZIP {'.gz': 'gzip', '.bz2': 'bzip2'}
Definition at line 25 of file build.py.
View newest version in sPHENIX GitHub at line 25 of file build.py