EIC Software: eicsmeardetectors/blob/master/eicsmeardetectors.hh File Reference
eicsmeardetectors.hh File Reference
#include <string>
#include <iostream>
#include <cctype>
#include "eicsmear/smear/Detector.h"
Functions
Smear::Detector BuildMatrixDetector_0_2_B1_5T ()
Smear::Detector BuildMatrixDetector_0_2_B3T ()
Smear::Detector BuildMatrixDetector_0_1 ()
Smear::Detector BuildMatrixDetector_0_1_FF (const int beam_mom_nn=100)
Smear::Detector BuildHandBook_1_2 ()
Smear::Detector BuildPerfectDetector ()
Smear::Detector BuildJLEIC_0_1 ()
Smear::Detector BuildBeAST_0_1 ()
Smear::Detector BuildBeAST_0_0 ()
Smear::Detector BuildSTAR_0_0 ()
Smear::Detector BuildZEUS_0_0 ()
Smear::Detector BuildeSTAR_0_0 ()
Smear::Detector BuildePHENIX_0_0 (bool multipleScattering=true)
Smear::Detector BuildTrackingPreview_0_2_B1_5T ()
Smear::Detector BuildTrackingPreview_0_2_B3T ()
Smear::Detector BuildCore_0_1_B3T ()
Smear::Detector BuildCore_0_1 (const double Bfield)
Smear::Detector BuildByName (std::string dname)
Smear::Detector BuildByName (std::string dname, const double d)
Function Documentation
Smear::Detector BuildBeAST_0_0 ()
Definition at line 12 of file SmearBeAST_0_0.cxx.
View newest version in sPHENIX GitHub at line 12 of file SmearBeAST_0_0.cxx
References Smear::Smearer::Accept, Smear::Detector::AddDevice(), Smear::Acceptance::AddParticle(), Smear::Acceptance::AddZone(), Smear::kCharged, Smear::kE, Smear::kElectromagnetic, Smear::kHadronic, Smear::kP, Smear::kPhi, Smear::kTheta, momentum, Smear::Acceptance::SetCharge(), Smear::Detector::SetEventKinematicsCalculator(), and Smear::Acceptance::SetGenre().
Smear::Detector BuildBeAST_0_1 ()
Definition at line 20 of file SmearBeAST_0_1.cxx.
View newest version in sPHENIX GitHub at line 20 of file SmearBeAST_0_1.cxx
References Smear::Smearer::Accept, Smear::Detector::AddDevice(), Smear::Acceptance::AddParticle(), Smear::Acceptance::AddZone(), Smear::kCharged, Smear::kE, Smear::kElectromagnetic, Smear::kHadronic, Smear::kNeutral, Smear::kP, Smear::kPhi, Smear::kTheta, momentum, Smear::Acceptance::SetCharge(), Smear::Detector::SetEventKinematicsCalculator(), Smear::Acceptance::SetGenre(), and ThetaFromEta().
Referenced by BuildByName().
Smear::Detector BuildByName (std::string dname)
For convenience. Not case-sensitive.Should be all upper case. Use like this: Smear::Detector detector = BuildByName("MATRIX");
Provides multiple aliases
Definition at line 3 of file BuildByName.cxx.
View newest version in sPHENIX GitHub at line 3 of file BuildByName.cxx
References BuildBeAST_0_1(), BuildCore_0_1_B3T(), BuildePHENIX_0_0(), BuildeSTAR_0_0(), BuildHandBook_1_2(), BuildJLEIC_0_1(), BuildMatrixDetector_0_1(), BuildMatrixDetector_0_2_B1_5T(), BuildMatrixDetector_0_2_B3T(), BuildPerfectDetector(), BuildSTAR_0_0(), BuildTrackingPreview_0_2_B1_5T(), BuildTrackingPreview_0_2_B3T(), BuildZEUS_0_0(), and c.
Referenced by main().
Smear::Detector BuildByName (std::string dname, const double d)
Overloaded version of Smear::Detector BuildByName (std::string dname) for detectors with a parameter
Definition at line 96 of file BuildByName.cxx.
View newest version in sPHENIX GitHub at line 96 of file BuildByName.cxx
References BuildCore_0_1(), BuildePHENIX_0_0(), BuildMatrixDetector_0_1_FF(), and c.
Smear::Detector BuildCore_0_1 (const double Bfield)
Definition at line 63 of file SmearCore_0_1.cxx.
View newest version in sPHENIX GitHub at line 63 of file SmearCore_0_1.cxx
References Smear::Smearer::Accept, Smear::Detector::AddDevice(), Smear::Acceptance::AddZone(), AssembleCoreTracker(), CalcA(), CalcB(), Smear::kAll, Smear::kCharged, Smear::kE, Smear::kElectromagnetic, Smear::kHadronic, Smear::kPhi, Smear::kTheta, Smear::Acceptance::SetCharge(), Smear::Detector::SetEventKinematicsCalculator(), Smear::Acceptance::SetGenre(), and ThetaFromEta().
Referenced by BuildByName().
Smear::Detector BuildCore_0_1_B3T ()
Definition at line 33 of file SmearCore_0_1_B3T.cxx.
View newest version in sPHENIX GitHub at line 33 of file SmearCore_0_1_B3T.cxx
References Smear::Smearer::Accept, Smear::Detector::AddDevice(), Smear::Acceptance::AddZone(), Smear::kAll, Smear::kCharged, Smear::kE, Smear::kElectromagnetic, Smear::kHadronic, Smear::kP, Smear::kPhi, Smear::kTheta, Smear::Acceptance::SetCharge(), Smear::Detector::SetEventKinematicsCalculator(), Smear::Acceptance::SetGenre(), and ThetaFromEta().
Referenced by BuildByName().
Smear::Detector BuildePHENIX_0_0 (bool multipleScattering)
Smearing parameterisations for the ePHENIX detector.
These parameterisations are non-exhaustive: they do not cover elements such as particle identification, and they are only for the central elements of the detector - essentially, just TPC and B/EEMC.
If multipleScattering == true, apply multiple scattering term to momentum resolution (currently only implemented for 2 < eta < 4). Otherwise just use the linear resolution term.
Note: you must gSystem->Load("libeicsmear") BEFORE loading this script, as ROOT needs to understand what a Smear::Detector is.
Definition at line 272 of file SmearePHENIX_0_0.cxx.
View newest version in sPHENIX GitHub at line 272 of file SmearePHENIX_0_0.cxx
References Smear::Smearer::Accept, Smear::Detector::AddDevice(), Smear::Acceptance::AddZone(), EPhenixMomentum::etaToTheta(), Smear::kElectromagnetic, Smear::kHadronic, momentum, phi, pid, Smear::Detector::SetEventKinematicsCalculator(), and theta().
Referenced by BuildByName().
Smear::Detector BuildeSTAR_0_0 ()
Smearing parameterisations for the eSTAR detector.
Based on parameterisations given in Zhangbu Xu's talk here (slide 5): https://wiki.bnl.gov/conferences/index.php/January_2014 This includes momentum and energy resolutions, but no particle identification.
Note: you must gSystem->Load("libeicsmear") BEFORE loading this script, as ROOT needs to understand what a Smear::Detector is.
Definition at line 50 of file SmeareSTAR_0_0.cxx.
View newest version in sPHENIX GitHub at line 50 of file SmeareSTAR_0_0.cxx
References Smear::Smearer::Accept, Smear::Detector::AddDevice(), Smear::Acceptance::AddZone(), Smear::kCharged, Smear::kElectromagnetic, Smear::kHadronic, phi, pid, Smear::Acceptance::SetCharge(), Smear::Detector::SetEventKinematicsCalculator(), theta(), and zoneEta().
Referenced by BuildByName().
Smear::Detector BuildHandBook_1_2 ()
Definition at line 41 of file SmearHandBook_1_2.cxx.
View newest version in sPHENIX GitHub at line 41 of file SmearHandBook_1_2.cxx
References Smear::Smearer::Accept, Smear::Detector::AddDevice(), Smear::Acceptance::AddParticle(), Smear::Acceptance::AddZone(), Smear::kCharged, Smear::kE, Smear::kElectromagnetic, Smear::kHadronic, Smear::kP, Smear::kPhi, Smear::kTheta, Smear::Acceptance::SetCharge(), Smear::Detector::SetEventKinematicsCalculator(), Smear::Acceptance::SetGenre(), and ThetaFromEta().
Referenced by BuildByName().
Smear::Detector BuildJLEIC_0_1 ()
Definition at line 34 of file SmearJLEIC_0_1.cxx.
View newest version in sPHENIX GitHub at line 34 of file SmearJLEIC_0_1.cxx
References Smear::Smearer::Accept, Smear::Detector::AddDevice(), Smear::Acceptance::AddParticle(), Smear::Acceptance::AddZone(), Acts::UnitConstants::e, Smear::kCharged, Smear::kE, Smear::kElectromagnetic, Smear::kHadronic, Smear::kNeutral, Smear::kPhi, Smear::kPt, Smear::kTheta, Smear::Acceptance::SetCharge(), Smear::Detector::SetEventKinematicsCalculator(), Smear::Acceptance::SetGenre(), and ThetaFromEta().
Referenced by BuildByName().
Smear::Detector BuildMatrixDetector_0_1 ()
Definition at line 37 of file SmearMatrixDetector_0_1.cxx.
View newest version in sPHENIX GitHub at line 37 of file SmearMatrixDetector_0_1.cxx
References Smear::Smearer::Accept, Smear::Detector::AddDevice(), Smear::Acceptance::AddParticle(), Smear::Acceptance::AddZone(), Smear::kCharged, Smear::kE, Smear::kElectromagnetic, Smear::kHadronic, Smear::kP, Smear::kPhi, Smear::kTheta, Smear::Acceptance::SetCharge(), Smear::Detector::SetEventKinematicsCalculator(), Smear::Acceptance::SetGenre(), and ThetaFromEta().
Referenced by BuildByName().
Smear::Detector BuildMatrixDetector_0_1_FF (const int beam_mom_nn)
beam_mom_nn: ion beam momentum per nucleon in GeV. Using int to avoid rounding issues in switch
Definition at line 28 of file SmearMatrixDetector_0_1_FF.cxx.
View newest version in sPHENIX GitHub at line 28 of file SmearMatrixDetector_0_1_FF.cxx
References Smear::Smearer::Accept, Smear::Detector::AddDevice(), Smear::Acceptance::AddParticle(), Smear::Acceptance::AddZone(), Acts::UnitConstants::e, Smear::kCharged, Smear::kE, Smear::kElectromagnetic, Smear::kHadronic, Smear::kP, Smear::kPhi, Smear::kPt, Smear::kTheta, Smear::Acceptance::SetCharge(), Smear::Detector::SetEventKinematicsCalculator(), Smear::Acceptance::SetGenre(), ThetaFromEta(), thetamin, and RawTowerDefs::ZDC.
Referenced by BuildByName().
Smear::Detector BuildMatrixDetector_0_2_B1_5T ()
Definition at line 32 of file SmearMatrixDetector_0_2_B1_5T.cxx.
View newest version in sPHENIX GitHub at line 32 of file SmearMatrixDetector_0_2_B1_5T.cxx
References Smear::Smearer::Accept, Smear::Detector::AddDevice(), Smear::Acceptance::AddZone(), Smear::kAll, Smear::kCharged, Smear::kE, Smear::kElectromagnetic, Smear::kHadronic, Smear::kP, Smear::kPhi, Smear::kTheta, Smear::Acceptance::SetCharge(), Smear::Detector::SetEventKinematicsCalculator(), Smear::Acceptance::SetGenre(), and ThetaFromEta().
Referenced by BuildByName().
Smear::Detector BuildMatrixDetector_0_2_B3T ()
Definition at line 32 of file SmearMatrixDetector_0_2_B3T.cxx.
View newest version in sPHENIX GitHub at line 32 of file SmearMatrixDetector_0_2_B3T.cxx
References Smear::Smearer::Accept, Smear::Detector::AddDevice(), Smear::Acceptance::AddZone(), Smear::kAll, Smear::kCharged, Smear::kE, Smear::kElectromagnetic, Smear::kHadronic, Smear::kP, Smear::kPhi, Smear::kTheta, Smear::Acceptance::SetCharge(), Smear::Detector::SetEventKinematicsCalculator(), Smear::Acceptance::SetGenre(), and ThetaFromEta().
Referenced by BuildByName().
Smear::Detector BuildPerfectDetector ()
Definition at line 25 of file SmearPerfectDetector.cxx.
View newest version in sPHENIX GitHub at line 25 of file SmearPerfectDetector.cxx
References Smear::Smearer::Accept, Smear::Detector::AddDevice(), Smear::Acceptance::AddZone(), etaToTheta(), Smear::kE, Smear::kP, Smear::kPhi, Smear::kTheta, momentum, phi, pid, Smear::Detector::SetEventKinematicsCalculator(), and theta().
Referenced by BuildByName().
Smear::Detector BuildSTAR_0_0 ()
Smearing parameterisations for the STAR detector.
These parameterisations are non-exhaustive: they do not cover elements such as particle identification, and they are only for the central elements of the detector - essentially, just TPC and B/EEMC.
Note: you must gSystem->Load("libeicsmear") BEFORE loading this script, as ROOT needs to understand what a Smear::Detector is.
Definition at line 52 of file SmearSTAR_0_0.cxx.
View newest version in sPHENIX GitHub at line 52 of file SmearSTAR_0_0.cxx
References Smear::Smearer::Accept, Smear::Detector::AddDevice(), Smear::Acceptance::AddZone(), Smear::kCharged, Smear::kE, Smear::kElectromagnetic, Smear::kP, Smear::kPhi, Smear::kTheta, makeZone(), momentum, phi, Smear::Acceptance::SetCharge(), Smear::Detector::SetEventKinematicsCalculator(), star(), and theta().
Referenced by BuildByName().
Smear::Detector BuildTrackingPreview_0_2_B1_5T ()
Definition at line 31 of file SmearTrackingPreview_0_2_B1_5T.cxx.
View newest version in sPHENIX GitHub at line 31 of file SmearTrackingPreview_0_2_B1_5T.cxx
References Smear::Smearer::Accept, Smear::Detector::AddDevice(), Smear::Acceptance::AddZone(), Smear::kAll, Smear::kCharged, Smear::kE, Smear::kElectromagnetic, Smear::kHadronic, Smear::kP, Smear::kPhi, Smear::kTheta, Smear::Acceptance::SetCharge(), Smear::Detector::SetEventKinematicsCalculator(), Smear::Acceptance::SetGenre(), and ThetaFromEta().
Referenced by BuildByName().
Smear::Detector BuildTrackingPreview_0_2_B3T ()
Definition at line 31 of file SmearTrackingPreview_0_2_B3T.cxx.
View newest version in sPHENIX GitHub at line 31 of file SmearTrackingPreview_0_2_B3T.cxx
References Smear::Smearer::Accept, Smear::Detector::AddDevice(), Smear::Acceptance::AddZone(), Smear::kAll, Smear::kCharged, Smear::kE, Smear::kElectromagnetic, Smear::kHadronic, Smear::kP, Smear::kPhi, Smear::kTheta, Smear::Acceptance::SetCharge(), Smear::Detector::SetEventKinematicsCalculator(), Smear::Acceptance::SetGenre(), and ThetaFromEta().
Referenced by BuildByName().
Smear::Detector BuildZEUS_0_0 ()
Smearing parameterisations for the ZEUS detector.
See JHEP05 (2009) 108.
Note: you must gSystem->Load("libeicsmear") BEFORE loading this script.
Definition at line 45 of file SmearZEUS_0_0.cxx.
View newest version in sPHENIX GitHub at line 45 of file SmearZEUS_0_0.cxx
References Smear::Smearer::Accept, Smear::Detector::AddDevice(), Smear::Acceptance::AddZone(), degreesToRadians(), etaToTheta(), Smear::kE, Smear::kElectromagnetic, Smear::kHadronic, Smear::kP, Smear::kPhi, Smear::kTheta, momentum, phi, Smear::Detector::SetEventKinematicsCalculator(), and theta().
Referenced by BuildByName().