EIC Software: parameter< T, validate > Class Template Reference
parameter< T, validate > Class Template Reference
#include <estarlight/blob/master/include/inputParameters.h>
Public Member Functions
parameter (const std::string &name, T value, bool required=true)
parameter & operator= (T v)
T * ptr () const
T value () const
std::string name () const
bool required () const
void setValue (T v)
void setName (std::string name)
void setRequired (bool r)
std::string validationkey ()
Public Member Functions inherited from parameterbase
parameterbase ()
template<typename T >
std::string toString (T v)
Private Member Functions
parameter ()
Private Attributes
std::string _name
T _value
bool _validate
bool _required
Friends
template<typename S , bool v>
std::ostream & operator<< (std::ostream &os, const parameter< S, v > &par)
Additional Inherited Members
Static Public Attributes inherited from parameterbase
static parameterlist _parameters
Detailed Description
template<typename T, bool validate>
class parameter< T, validate >
Definition at line 103 of file inputParameters.h.
View newest version in sPHENIX GitHub at line 103 of file inputParameters.h
Constructor & Destructor Documentation
template<typename T, bool validate> parameter< T, validate >::parameter (const std::string & name, T value, bool required = true) inline
Definition at line 108 of file inputParameters.h.
View newest version in sPHENIX GitHub at line 108 of file inputParameters.h
template<typename T, bool validate> parameter< T, validate >::parameter () private
Member Function Documentation
template<typename T, bool validate> std::string parameter< T, validate >::name () const inline
Definition at line 118 of file inputParameters.h.
View newest version in sPHENIX GitHub at line 118 of file inputParameters.h
Referenced by parameter< bool, NO_VALIDITY_CHECK >::setName().
template<typename T, bool validate> parameter& parameter< T, validate >::operator= (T v) inline
Definition at line 111 of file inputParameters.h.
View newest version in sPHENIX GitHub at line 111 of file inputParameters.h
template<typename T, bool validate> T* parameter< T, validate >::ptr () const inline
Definition at line 112 of file inputParameters.h.
View newest version in sPHENIX GitHub at line 112 of file inputParameters.h
Referenced by __example_2.f__(), and __example_3.f__().
template<typename T, bool validate> bool parameter< T, validate >::required () const inline
Definition at line 120 of file inputParameters.h.
View newest version in sPHENIX GitHub at line 120 of file inputParameters.h
template<typename T, bool validate> void parameter< T, validate >::setName (std::string name) inline
Definition at line 124 of file inputParameters.h.
View newest version in sPHENIX GitHub at line 124 of file inputParameters.h
template<typename T, bool validate> void parameter< T, validate >::setRequired (bool r) inline
Definition at line 126 of file inputParameters.h.
View newest version in sPHENIX GitHub at line 126 of file inputParameters.h
template<typename T, bool validate> void parameter< T, validate >::setValue (T v) inline
Definition at line 122 of file inputParameters.h.
View newest version in sPHENIX GitHub at line 122 of file inputParameters.h
template<typename T, bool validate> std::string parameter< T, validate >::validationkey () inline virtual
Implements parameterbase.
Definition at line 129 of file inputParameters.h.
View newest version in sPHENIX GitHub at line 129 of file inputParameters.h
template<typename T, bool validate> T parameter< T, validate >::value () const inline
Definition at line 116 of file inputParameters.h.
View newest version in sPHENIX GitHub at line 116 of file inputParameters.h
Referenced by inputParameters::axionMass(), inputParameters::backwardsProduction(), inputParameters::baseFileName(), inputParameters::beamBreakupMode(), inputParameters::bslopeDefinition(), inputParameters::bslopeValue(), inputParameters::defaultFullEventRecord(), inputParameters::electronBeamLorentzGamma(), inputParameters::electronEnergy(), inputParameters::etaCutEnabled(), inputParameters::etaCutMax(), inputParameters::etaCutMin(), inputParameters::hepmc3FullEventRecord(), inputParameters::impulseVM(), inputParameters::init(), inputParameters::interferenceEnabled(), inputParameters::interferenceStrength(), inputParameters::lundFullEventRecord(), inputParameters::maxGammaEnergy(), inputParameters::maxGammaQ2(), inputParameters::maxPtInterference(), inputParameters::maxRapidity(), inputParameters::maxW(), inputParameters::maxW_GP(), inputParameters::minGammaEnergy(), inputParameters::minGammaQ2(), inputParameters::minW(), inputParameters::minW_GP(), inputParameters::nmbEnergyBins(), inputParameters::nmbEvents(), inputParameters::nmbGammaQ2Bins(), inputParameters::nmbPtBinsInterference(), inputParameters::nmbRapidityBins(), inputParameters::nmbWBins(), inputParameters::outputFormat(), inputParameters::print(), inputParameters::prodParticleId(), inputParameters::productionMode(), inputParameters::protonEnergy(), inputParameters::ptBinWidthInterference(), inputParameters::ptCutEnabled(), inputParameters::ptCutMax(), inputParameters::ptCutMin(), inputParameters::pythiaFullEventRecord(), inputParameters::pythiaParams(), inputParameters::quantumGlauber(), inputParameters::randomSeed(), inputParameters::targetBeamA(), inputParameters::targetBeamLorentzGamma(), inputParameters::targetBeamZ(), and inputParameters::xsecCalcMethod().
Friends And Related Function Documentation
template<typename T, bool validate> template<typename S , bool v> std::ostream& operator<< (std::ostream & os, const parameter< S, v > & par) friend
Definition at line 150 of file inputParameters.h.
View newest version in sPHENIX GitHub at line 150 of file inputParameters.h
Member Data Documentation
template<typename T, bool validate> std::string parameter< T, validate >::_name private
Definition at line 140 of file inputParameters.h.
View newest version in sPHENIX GitHub at line 140 of file inputParameters.h
Referenced by parameter< bool, NO_VALIDITY_CHECK >::name(), parameter< bool, NO_VALIDITY_CHECK >::setName(), and parameter< bool, NO_VALIDITY_CHECK >::validationkey().
template<typename T, bool validate> bool parameter< T, validate >::_required private
Definition at line 144 of file inputParameters.h.
View newest version in sPHENIX GitHub at line 144 of file inputParameters.h
Referenced by parameter< bool, NO_VALIDITY_CHECK >::required(), and parameter< bool, NO_VALIDITY_CHECK >::setRequired().
template<typename T, bool validate> bool parameter< T, validate >::_validate private
Definition at line 143 of file inputParameters.h.
View newest version in sPHENIX GitHub at line 143 of file inputParameters.h
Referenced by parameter< bool, NO_VALIDITY_CHECK >::validationkey().
template<typename T, bool validate> T parameter< T, validate >::_value private
Definition at line 142 of file inputParameters.h.
View newest version in sPHENIX GitHub at line 142 of file inputParameters.h
Referenced by parameter< bool, NO_VALIDITY_CHECK >::operator=(), parameter< bool, NO_VALIDITY_CHECK >::ptr(), parameter< bool, NO_VALIDITY_CHECK >::setValue(), parameter< bool, NO_VALIDITY_CHECK >::validationkey(), and parameter< bool, NO_VALIDITY_CHECK >::value().
The documentation for this class was generated from the following file:
estarlight/blob/master/include/inputParameters.h