EIC Software: MediaLayer Class Reference
MediaLayer Class Reference
#include <EicRoot/blob/master/eic/htc/MediaLayer.h>
Public Member Functions
MediaLayer (TGeoMaterial *material, double z0)
~MediaLayer ()
void SetThickness (double thickness)
double GetThickness () const
TGeoMaterial * GetMaterial () const
double GetZ0 () const
double GetMoliereChc () const
Private Attributes
TGeoMaterial * mMaterial
double mMoliereChc
double mZ0
double mThickness
Detailed Description
Definition at line 12 of file MediaLayer.h.
View newest version in sPHENIX GitHub at line 12 of file MediaLayer.h
Constructor & Destructor Documentation
MediaLayer::MediaLayer (TGeoMaterial * material, double z0)
Definition at line 13 of file MediaLayer.cxx.
View newest version in sPHENIX GitHub at line 13 of file MediaLayer.cxx
References G3MOLI, mMoliereChc, and mThickness.
MediaLayer::~MediaLayer () inline
Definition at line 15 of file MediaLayer.h.
View newest version in sPHENIX GitHub at line 15 of file MediaLayer.h
Member Function Documentation
TGeoMaterial* MediaLayer::GetMaterial () const inline
Definition at line 20 of file MediaLayer.h.
View newest version in sPHENIX GitHub at line 20 of file MediaLayer.h
References mMaterial.
Referenced by MediaSliceArray::GetDE(), TrKalmanNodeLocation::InitializeProcessNoiseMatrices(), MediaSlice::MediaSlice(), and MediaBank::Print().
double MediaLayer::GetMoliereChc () const inline
Definition at line 22 of file MediaLayer.h.
View newest version in sPHENIX GitHub at line 22 of file MediaLayer.h
Referenced by TrKalmanNodeLocation::InitializeProcessNoiseMatrices().
double MediaLayer::GetThickness () const inline
Definition at line 18 of file MediaLayer.h.
View newest version in sPHENIX GitHub at line 18 of file MediaLayer.h
References mThickness.
Referenced by MediaSliceArray::MediaSliceArray(), and MediaBank::Print().
double MediaLayer::GetZ0 () const inline
Definition at line 21 of file MediaLayer.h.
View newest version in sPHENIX GitHub at line 21 of file MediaLayer.h
References mZ0.
Referenced by MediaSliceArray::MediaSliceArray(), MediaBank::Print(), MediaBank::SetCurrentLayerThickness(), and MediaBank::StartNextLayer().
void MediaLayer::SetThickness (double thickness) inline
Definition at line 17 of file MediaLayer.h.
View newest version in sPHENIX GitHub at line 17 of file MediaLayer.h
References mThickness, and thickness.
Referenced by MediaBank::SetCurrentLayerThickness().
Member Data Documentation
TGeoMaterial* MediaLayer::mMaterial private
Definition at line 22 of file MediaLayer.h.
View newest version in sPHENIX GitHub at line 22 of file MediaLayer.h
Referenced by GetMaterial().
double MediaLayer::mMoliereChc private
Definition at line 28 of file MediaLayer.h.
View newest version in sPHENIX GitHub at line 28 of file MediaLayer.h
Referenced by MediaLayer().
double MediaLayer::mThickness private
Definition at line 33 of file MediaLayer.h.
View newest version in sPHENIX GitHub at line 33 of file MediaLayer.h
Referenced by GetThickness(), MediaLayer(), and SetThickness().
double MediaLayer::mZ0 private
Definition at line 33 of file MediaLayer.h.
View newest version in sPHENIX GitHub at line 33 of file MediaLayer.h
Referenced by GetZ0().
The documentation for this class was generated from the following files:
EicRoot/blob/master/eic/htc/MediaLayer.h
EicRoot/blob/master/eic/htc/MediaLayer.cxx