EIC Software: GFAbsFinitePlane Class Reference
GFAbsFinitePlane Class Reference abstract
Genfit
Abstract base class for implementing arbitrarily shaped finite detector planes.
#include <EicRoot/blob/master/genfit/GFAbsFinitePlane.h>
Public Member Functions
virtual bool inActive (const double &u, const double &v) const =0
virtual void Print (const Option_t *="") const =0
virtual GFAbsFinitePlane * clone () const =0
Deep copy ctor for polymorphic class.
virtual ~GFAbsFinitePlane ()
Detailed Description
Abstract base class for implementing arbitrarily shaped finite detector planes.
Finite detector planes could have any shape, e.g. rectangular, trapezoidal, ... Define them by inheriting from this class. Example, see GFRectFinitePlane This is an optional feature for the GFDetPlane class for avoiding fake intersection points in the fitting of loopers.
Definition at line 42 of file GFAbsFinitePlane.h.
View newest version in sPHENIX GitHub at line 42 of file GFAbsFinitePlane.h
Constructor & Destructor Documentation
GFAbsFinitePlane::~GFAbsFinitePlane () virtual
Definition at line 22 of file GFAbsFinitePlane.cxx.
View newest version in sPHENIX GitHub at line 22 of file GFAbsFinitePlane.cxx
Member Function Documentation
virtual GFAbsFinitePlane* GFAbsFinitePlane::clone () const pure virtual
Deep copy ctor for polymorphic class.
Implemented in GFRectFinitePlane.
Referenced by GFDetPlane::GFDetPlane(), and GFDetPlane::operator=().
virtual bool GFAbsFinitePlane::inActive (const double & u, const double & v) const pure virtual
Returns whether a u,v point is in the active plane or not. Needs to be implemented in child class.
Implemented in GFRectFinitePlane.
Referenced by GFDetPlane::inActive().
virtual void GFAbsFinitePlane::Print (const Option_t * = "") const pure virtual
Implemented in GFRectFinitePlane.
Referenced by GFDetPlane::Print().
The documentation for this class was generated from the following files:
EicRoot/blob/master/genfit/GFAbsFinitePlane.h
EicRoot/blob/master/genfit/GFAbsFinitePlane.cxx