EIC Software: acts/blob/sPHENIX/Examples/Run/Misc/TabulateEnergyLoss.cpp File Reference
TabulateEnergyLoss.cpp File Reference
#include "Acts/Material/Interactions.hpp"
#include "Acts/Material/Material.hpp"
#include "Acts/Material/MaterialSlab.hpp"
#include "Acts/Utilities/PdgParticle.hpp"
#include "Acts/Utilities/Units.hpp"
#include "ActsFatras/Utilities/ParticleData.hpp"
#include <cstddef>
#include <cstdlib>
#include <iomanip>
#include <iostream>
Functions
static void printHeader (std::ostream &os, const Acts::MaterialSlab &slab, Acts::PdgParticle pdg, float mass, float charge)
static void printLine (std::ostream &os, float mass, float momentum, float delta, float deltaIon, float deltaRad, float sigma)
int main (int argc, char const *argv[])
Variables
static constexpr int width = 11
static constexpr int precision = 3
static constexpr char separator = ' '
Function Documentation
int main (int argc, char const * argv[])
Definition at line 67 of file TabulateEnergyLoss.cpp.
View newest version in sPHENIX GitHub at line 67 of file TabulateEnergyLoss.cpp
References charge, Acts::computeEnergyLossBethe(), Acts::computeEnergyLossLandauSigma(), Acts::computeEnergyLossMean(), Acts::computeEnergyLossRadiative(), Acts::Test::delta, ActsFatras::findCharge(), ActsFatras::findMass(), Acts::Material::fromMassDensity(), mass, material(), p, pdg, printHeader(), printLine(), and thickness.
static void printHeader (std::ostream & os, const Acts::MaterialSlab & slab, Acts::PdgParticle pdg, float mass, float charge) static
Definition at line 29 of file TabulateEnergyLoss.cpp.
View newest version in sPHENIX GitHub at line 29 of file TabulateEnergyLoss.cpp
References separator, and width.
Referenced by main().
static void printLine (std::ostream & os, float mass, float momentum, float delta, float deltaIon, float deltaRad, float sigma) static
Definition at line 52 of file TabulateEnergyLoss.cpp.
View newest version in sPHENIX GitHub at line 52 of file TabulateEnergyLoss.cpp
References mass, precision, separator, and width.
Referenced by main().
Variable Documentation
constexpr int precision = 3 static
Definition at line 26 of file TabulateEnergyLoss.cpp.
View newest version in sPHENIX GitHub at line 26 of file TabulateEnergyLoss.cpp
Referenced by lit::NumberToString(), printLine(), Rossegger::Rossegger(), FairDbTableMetaData::SetFromSql(), EicGeoMedium::setMediumPar(), FairGeoMedium::setMediumPar(), and Acts::toString().
constexpr char separator = ' ' static
Definition at line 27 of file TabulateEnergyLoss.cpp.
View newest version in sPHENIX GitHub at line 27 of file TabulateEnergyLoss.cpp
Referenced by PHTpcTrackerUtil::convert_clusters_to_hits(), PHTpcEventExporter::exportEvent(), printHeader(), and printLine().
constexpr int width = 11 static
Definition at line 25 of file TabulateEnergyLoss.cpp.
View newest version in sPHENIX GitHub at line 25 of file TabulateEnergyLoss.cpp
Referenced by printHeader(), printLine(), pyslha(), and xytabl().