EIC Software: Acts::BoundarySurfaceT< T > Class Template Reference
Acts::BoundarySurfaceT< T > Class Template Reference
#include <fun4all_acts/blob/master/Core/include/Acts/Geometry/BoundarySurfaceT.hpp>
Public Member Functions
BoundarySurfaceT ()
Default Constructor.
BoundarySurfaceT (std::shared_ptr< const Surface > surface, const T *inside, const T *outside)
BoundarySurfaceT (std::shared_ptr< const Surface > surface, VolumePtr inside, VolumePtr outside)
BoundarySurfaceT (std::shared_ptr< const Surface > surface, std::shared_ptr< const VolumeArray > insideArray, std::shared_ptr< const VolumeArray > outsideArray)
virtual const T * attachedVolume (const GeometryContext &gctx, const Vector3D &pos, const Vector3D &mom, NavigationDirection pdir) const
template<class P >
bool onBoundary (const GeometryContext &gctx, const P &pars) const
virtual const Surface & surfaceRepresentation () const
The Surface Representation of this.
virtual ~BoundarySurfaceT ()=default
Virtual Destructor.
void attachVolume (const T *volume, BoundaryOrientation inout)
void attachVolumeArray (std::shared_ptr< const VolumeArray > volumes, BoundaryOrientation inout)
Protected Attributes
std::shared_ptr< const Surface > m_surface
the represented surface by this
const T * m_insideVolume
the inside (w.r.t. normal vector) volume to point to if only one exists
const T * m_outsideVolume
the outside (w.r.t. normal vector) volume to point to if only one exists
std::shared_ptr< const
VolumeArray > m_insideVolumeArray
the inside (w.r.t. normal vector) volume array to point to
std::shared_ptr< const
VolumeArray > m_outsideVolumeArray
the outside (w.r.t. normal vector) volume array to point to
Private Types
using VolumePtr = std::shared_ptr< const T >
using VolumeArray = BinnedArray< VolumePtr >
Private Attributes
friend T
declare the TrackingVolume as friend
Detailed Description
template<class T>
class Acts::BoundarySurfaceT< T >
The boundary surface class combines a Surface with the information of a volume. It's templated in the type of volume in order to allow for a return type tat is usable in the navigation stream.
Note
inside/outside definitions are given by the normal vector of the surface
Definition at line 40 of file BoundarySurfaceT.hpp.
View newest version in sPHENIX GitHub at line 40 of file BoundarySurfaceT.hpp
Member Typedef Documentation
template<class T > using Acts::BoundarySurfaceT< T >::VolumeArray = BinnedArray<VolumePtr> private
Definition at line 45 of file BoundarySurfaceT.hpp.
View newest version in sPHENIX GitHub at line 45 of file BoundarySurfaceT.hpp
template<class T > using Acts::BoundarySurfaceT< T >::VolumePtr = std::shared_ptr<const T> private
Definition at line 44 of file BoundarySurfaceT.hpp.
View newest version in sPHENIX GitHub at line 44 of file BoundarySurfaceT.hpp
Constructor & Destructor Documentation
template<class T > Acts::BoundarySurfaceT< T >::BoundarySurfaceT () inline
Default Constructor.
Definition at line 49 of file BoundarySurfaceT.hpp.
View newest version in sPHENIX GitHub at line 49 of file BoundarySurfaceT.hpp
template<class T > Acts::BoundarySurfaceT< T >::BoundarySurfaceT (std::shared_ptr< const Surface > surface, const T * inside, const T * outside) inline
Constructor for a Boundary with exact two Volumes attached to it
usually used in a volume constructor
Parameters
surface The unqiue surface the boundary represents
inside The inside volume the bounday surface points to
outside The outside volume the boundary surface points to
Definition at line 62 of file BoundarySurfaceT.hpp.
View newest version in sPHENIX GitHub at line 62 of file BoundarySurfaceT.hpp
template<class T > Acts::BoundarySurfaceT< T >::BoundarySurfaceT (std::shared_ptr< const Surface > surface, VolumePtr inside, VolumePtr outside) inline
Constructor for a Boundary with exact two Volumes attached to it
usually used in a volume constructor
Parameters
surface The unqiue surface the boundary represents
inside The inside volume the bounday surface points to
outside The outside volume the boundary surface points to
Definition at line 76 of file BoundarySurfaceT.hpp.
View newest version in sPHENIX GitHub at line 76 of file BoundarySurfaceT.hpp
template<class T > Acts::BoundarySurfaceT< T >::BoundarySurfaceT (std::shared_ptr< const Surface > surface, std::shared_ptr< const VolumeArray > insideArray, std::shared_ptr< const VolumeArray > outsideArray) inline
Constructor for a Boundary with exact multiple Volumes attached to it
usually used in a volume constructor
Parameters
surface The unqiue surface the boundary represents
insideArray The inside volume array the bounday surface points to
outsideArray The outside volume array the boundary surface points to
Definition at line 91 of file BoundarySurfaceT.hpp.
View newest version in sPHENIX GitHub at line 91 of file BoundarySurfaceT.hpp
template<class T > virtual Acts::BoundarySurfaceT< T >::~BoundarySurfaceT () virtual default
Virtual Destructor.
Member Function Documentation
template<class T > const T * Acts::BoundarySurfaceT< T >::attachedVolume (const GeometryContext & gctx, const Vector3D & pos, const Vector3D & mom, NavigationDirection pdir) const virtual
Get the next Volume depending on GlobalPosition, GlobalMomentum, dir on the TrackParameters and the requested direction
Parameters
gctx The current geometry context object, e.g. alignment
pos The global position on surface
mom The direction on the surface
dir is an aditional direction corrective
Returns
The attached volume at that position
Definition at line 186 of file BoundarySurfaceT.hpp.
View newest version in sPHENIX GitHub at line 186 of file BoundarySurfaceT.hpp
References analysis::dot, and T.
template<class T > void Acts::BoundarySurfaceT< T >::attachVolume (const T * volume, BoundaryOrientation inout)
Helper method: attach a Volume to this BoundarySurfaceT this is done during the geometry construction.
Parameters
gctx The current geometry context object, e.g. alignment
volume The volume to be attached
inout The boundary orientation
Definition at line 165 of file BoundarySurfaceT.hpp.
View newest version in sPHENIX GitHub at line 165 of file BoundarySurfaceT.hpp
References Acts::insideVolume, and Acts::Test::volume.
Referenced by Acts::TrackingVolume::glueTrackingVolume().
template<class T > void Acts::BoundarySurfaceT< T >::attachVolumeArray (std::shared_ptr< const VolumeArray > volumes, BoundaryOrientation inout)
Helper method: attach a Volume to this BoundarySurfaceT this is done during the geometry construction.
Parameters
volumes The volume array to be attached
inout The boundary orientation
Definition at line 175 of file BoundarySurfaceT.hpp.
View newest version in sPHENIX GitHub at line 175 of file BoundarySurfaceT.hpp
References Acts::insideVolume.
Referenced by Acts::TrackingVolume::glueTrackingVolumes().
template<class T > template<class P > bool Acts::BoundarySurfaceT< T >::onBoundary (const GeometryContext & gctx, const P & pars) const inline
templated onBoundary method
Template Parameters
pars are the parameters to be checked
Parameters
gctx The current geometry context object, e.g. alignment
pars The parameters used for this call
Definition at line 120 of file BoundarySurfaceT.hpp.
View newest version in sPHENIX GitHub at line 120 of file BoundarySurfaceT.hpp
References Acts::Surface::isOnSurface(), and Acts::BoundarySurfaceT< T >::surfaceRepresentation().
template<class T > const Surface & Acts::BoundarySurfaceT< T >::surfaceRepresentation () const inline virtual
The Surface Representation of this.
Definition at line 160 of file BoundarySurfaceT.hpp.
View newest version in sPHENIX GitHub at line 160 of file BoundarySurfaceT.hpp
Referenced by Acts::BoundarySurfaceT< T >::onBoundary().
Member Data Documentation
template<class T > const T* Acts::BoundarySurfaceT< T >::m_insideVolume protected
the inside (w.r.t. normal vector) volume to point to if only one exists
Definition at line 150 of file BoundarySurfaceT.hpp.
View newest version in sPHENIX GitHub at line 150 of file BoundarySurfaceT.hpp
template<class T > std::shared_ptr<const VolumeArray> Acts::BoundarySurfaceT< T >::m_insideVolumeArray protected
the inside (w.r.t. normal vector) volume array to point to
Definition at line 154 of file BoundarySurfaceT.hpp.
View newest version in sPHENIX GitHub at line 154 of file BoundarySurfaceT.hpp
template<class T > const T* Acts::BoundarySurfaceT< T >::m_outsideVolume protected
the outside (w.r.t. normal vector) volume to point to if only one exists
Definition at line 152 of file BoundarySurfaceT.hpp.
View newest version in sPHENIX GitHub at line 152 of file BoundarySurfaceT.hpp
template<class T > std::shared_ptr<const VolumeArray> Acts::BoundarySurfaceT< T >::m_outsideVolumeArray protected
the outside (w.r.t. normal vector) volume array to point to
Definition at line 156 of file BoundarySurfaceT.hpp.
View newest version in sPHENIX GitHub at line 156 of file BoundarySurfaceT.hpp
template<class T > std::shared_ptr<const Surface> Acts::BoundarySurfaceT< T >::m_surface protected
the represented surface by this
Definition at line 148 of file BoundarySurfaceT.hpp.
View newest version in sPHENIX GitHub at line 148 of file BoundarySurfaceT.hpp
template<class T > friend Acts::BoundarySurfaceT< T >::T private
declare the TrackingVolume as friend
Definition at line 42 of file BoundarySurfaceT.hpp.
View newest version in sPHENIX GitHub at line 42 of file BoundarySurfaceT.hpp
The documentation for this class was generated from the following file:
fun4all_acts/blob/master/Core/include/Acts/Geometry/BoundarySurfaceT.hpp