EIC Software: fun4all_eicmacros/blob/master/common/G4_TTL_EIC.C File Reference
G4_TTL_EIC.C File Reference
#include "GlobalVariables.C"
#include <g4ttl/PHG4TTLSubsystem.h>
#include <g4ttl/RawDigitBuilderTTL.h>
#include <g4detectors/PHG4CylinderSubsystem.h>
#include <g4main/PHG4Reco.h>
#include <string>
Namespaces
namespace Enable
namespace G4TTL
namespace G4TTL::SETTING
Macros
#define MACRO_G4TTLEIC_C
Functions
int make_forward_station (string name, PHG4Reco *g4Reco, double zpos, double Rmin, double Rmax, double tSilicon, double xoffset=0)
int make_forward_station_basic (string name, PHG4Reco *g4Reco, double zpos, double Rmin, double Rmax, double tSilicon)
int make_barrel_layer_basic (string name, PHG4Reco *g4Reco, double radius, double halflength, double tSilicon, double zOffset)
int make_barrel_layer_LYSO_basic (string name, PHG4Reco *g4Reco, double radius, double halflength, double tSilicon, double zOffset)
int make_barrel_layer (string name, PHG4Reco *g4Reco, double radius, double halflength, double tSilicon, double zOffset)
void TTL_Init ()
void FTTLSetup (PHG4Reco *g4Reco, TString fttloption="")
void ETTLSetup (PHG4Reco *g4Reco, TString ettloption="")
void CTTLSetup (PHG4Reco *g4Reco, TString cttloption="")
void FTTL_Clustering ()
void ETTL_Clustering ()
Variables
bool Enable::FTTL = false
bool Enable::ETTL = false
bool Enable::CTTL = false
bool Enable::FTTL_CLUSTER = false
bool Enable::ETTL_CLUSTER = false
int G4TTL::layer [3] = { 2, 1, 2}
double G4TTL::positionToVtx [3][3] = { {-169., -172., -309.5}, {80., 114.7, 0. }, { 287., 289., 340.} }
double G4TTL::minExtension [3][3] = { {8, 8, 15.3}, {218, 180, 0 }, {11.62, 11.7, 13.8 } }
double G4TTL::maxExtension [3][3] = { {61., 61. , 200}, {-40, 0, 0 }, {170., 170., 250 } }
bool G4TTL::SETTING::optionCEMC = true
bool G4TTL::SETTING::optionEEMCH = true
bool G4TTL::SETTING::optionBasicGeo = false
bool G4TTL::SETTING::optionLYSO = false
int G4TTL::SETTING::optionDR = 0
int G4TTL::SETTING::optionGeo = 1
int G4TTL::SETTING::optionGran = 1
Macro Definition Documentation
#define MACRO_G4TTLEIC_C
Definition at line 2 of file G4_TTL_EIC.C.
View newest version in sPHENIX GitHub at line 2 of file G4_TTL_EIC.C
Function Documentation
void CTTLSetup (PHG4Reco * g4Reco, TString cttloption = "")
Definition at line 155 of file G4_TTL_EIC.C.
View newest version in sPHENIX GitHub at line 155 of file G4_TTL_EIC.C
References Acts::UnitConstants::cm, Acts::UnitConstants::e, G4TTL::layer, make_barrel_layer(), make_barrel_layer_basic(), make_barrel_layer_LYSO_basic(), G4TTL::maxExtension, G4TTL::minExtension, Acts::UnitConstants::mm, G4TTL::SETTING::optionBasicGeo, G4TTL::SETTING::optionLYSO, G4TTL::positionToVtx, Acts::UnitConstants::um, and PHG4Sector::Sector_Geometry::Unit_cm().
Referenced by G4Setup().
void ETTL_Clustering ()
Definition at line 392 of file G4_TTL_EIC.C.
View newest version in sPHENIX GitHub at line 392 of file G4_TTL_EIC.C
References RawDigitBuilderTTL::Detector(), Fun4AllServer::instance(), G4TTL::layer, G4TTL::SETTING::optionBasicGeo, and Fun4AllServer::registerSubsystem().
Referenced by Fun4All_G4_FullDetectorModular().
void ETTLSetup (PHG4Reco * g4Reco, TString ettloption = "")
Definition at line 139 of file G4_TTL_EIC.C.
View newest version in sPHENIX GitHub at line 139 of file G4_TTL_EIC.C
References Acts::UnitConstants::cm, Acts::UnitConstants::e, G4TTL::layer, make_forward_station(), make_forward_station_basic(), G4TTL::maxExtension, G4TTL::minExtension, Acts::UnitConstants::mm, G4TTL::SETTING::optionBasicGeo, G4TTL::positionToVtx, Acts::UnitConstants::um, and PHG4Sector::Sector_Geometry::Unit_cm().
Referenced by G4Setup().
void FTTL_Clustering ()
Definition at line 377 of file G4_TTL_EIC.C.
View newest version in sPHENIX GitHub at line 377 of file G4_TTL_EIC.C
References RawDigitBuilderTTL::Detector(), Fun4AllServer::instance(), G4TTL::layer, G4TTL::SETTING::optionBasicGeo, and Fun4AllServer::registerSubsystem().
Referenced by Fun4All_G4_FullDetectorModular().
void FTTLSetup (PHG4Reco * g4Reco, TString fttloption = "")
Definition at line 121 of file G4_TTL_EIC.C.
View newest version in sPHENIX GitHub at line 121 of file G4_TTL_EIC.C
References Acts::UnitConstants::cm, Acts::UnitConstants::e, G4TTL::layer, make_forward_station(), make_forward_station_basic(), G4TTL::maxExtension, G4TTL::minExtension, Acts::UnitConstants::mm, G4TTL::SETTING::optionBasicGeo, G4TTL::positionToVtx, Acts::UnitConstants::um, and PHG4Sector::Sector_Geometry::Unit_cm().
Referenced by G4Setup().
int make_barrel_layer (string name, PHG4Reco * g4Reco, double radius, double halflength, double tSilicon, double zOffset)
Definition at line 266 of file G4_TTL_EIC.C.
View newest version in sPHENIX GitHub at line 266 of file G4_TTL_EIC.C
References Acts::UnitConstants::cm, G4TTL::SETTING::optionCEMC, Enable::OVERLAPCHECK, PHG4DetectorSubsystem::OverlapCheck(), PHG4Reco::registerSubsystem(), PHG4DetectorSubsystem::set_double_param(), PHG4DetectorSubsystem::set_int_param(), PHG4TTLSubsystem::SetDetailed(), PHG4TTLSubsystem::SuperDetector(), and TrkrDefs::ttl.
Referenced by CTTLSetup().
int make_barrel_layer_basic (string name, PHG4Reco * g4Reco, double radius, double halflength, double tSilicon, double zOffset)
Definition at line 292 of file G4_TTL_EIC.C.
View newest version in sPHENIX GitHub at line 292 of file G4_TTL_EIC.C
References material(), Enable::OVERLAPCHECK, PHG4DetectorSubsystem::OverlapCheck(), G4BECAL::radius, PHG4Reco::registerSubsystem(), PHG4DetectorSubsystem::set_double_param(), PHG4DetectorSubsystem::set_string_param(), PHG4DetectorSubsystem::SetActive(), PHG4DetectorSubsystem::SuperDetector(), thickness, and Acts::UnitConstants::um.
Referenced by CTTLSetup().
int make_barrel_layer_LYSO_basic (string name, PHG4Reco * g4Reco, double radius, double halflength, double tSilicon, double zOffset)
Definition at line 336 of file G4_TTL_EIC.C.
View newest version in sPHENIX GitHub at line 336 of file G4_TTL_EIC.C
References Acts::UnitConstants::cm, material(), Enable::OVERLAPCHECK, PHG4DetectorSubsystem::OverlapCheck(), G4BECAL::radius, PHG4Reco::registerSubsystem(), PHG4DetectorSubsystem::set_double_param(), PHG4DetectorSubsystem::set_string_param(), PHG4DetectorSubsystem::SetActive(), PHG4DetectorSubsystem::SuperDetector(), and thickness.
Referenced by CTTLSetup().
int make_forward_station (string name, PHG4Reco * g4Reco, double zpos, double Rmin, double Rmax, double tSilicon, double xoffset = 0)
Definition at line 175 of file G4_TTL_EIC.C.
View newest version in sPHENIX GitHub at line 175 of file G4_TTL_EIC.C
References Acts::UnitConstants::cm, M_PI, Enable::OVERLAPCHECK, PHG4DetectorSubsystem::OverlapCheck(), PHG4Reco::registerSubsystem(), PHG4DetectorSubsystem::set_double_param(), PHG4DetectorSubsystem::set_int_param(), PHG4TTLSubsystem::SetDetailed(), PHG4TTLSubsystem::SuperDetector(), and TrkrDefs::ttl.
Referenced by ETTLSetup(), and FTTLSetup().
int make_forward_station_basic (string name, PHG4Reco * g4Reco, double zpos, double Rmin, double Rmax, double tSilicon)
Definition at line 208 of file G4_TTL_EIC.C.
View newest version in sPHENIX GitHub at line 208 of file G4_TTL_EIC.C
References PHG4Sector::Sector_Geometry::AddLayer(), Acts::UnitConstants::cm, PHG4Sector::Sector_Geometry::ConeEdge(), Acts::UnitConstants::e, PHG4Sector::Sector_Geometry::eta_to_polar_angle(), PHG4SectorSubsystem::get_geometry(), M_PI, Acts::UnitConstants::mm, Enable::OVERLAPCHECK, PHG4Subsystem::OverlapCheck(), PHG4Reco::registerSubsystem(), PHG4Sector::Sector_Geometry::set_material(), PHG4Sector::Sector_Geometry::set_max_polar_angle(), PHG4Sector::Sector_Geometry::set_max_polar_edge(), PHG4Sector::Sector_Geometry::set_min_polar_angle(), PHG4Sector::Sector_Geometry::set_min_polar_edge(), PHG4Sector::Sector_Geometry::set_N_Sector(), PHG4Sector::Sector_Geometry::set_normal_polar_angle(), PHG4Sector::Sector_Geometry::set_normal_start(), PHG4SectorSubsystem::SuperDetector(), t, TrkrDefs::ttl, Acts::UnitConstants::um, and PHG4Sector::Sector_Geometry::Unit_cm().
Referenced by ETTLSetup(), and FTTLSetup().
void TTL_Init ()
Definition at line 57 of file G4_TTL_EIC.C.
View newest version in sPHENIX GitHub at line 57 of file G4_TTL_EIC.C
References G4TTL::layer, max, BlackHoleGeometry::max_radius, BlackHoleGeometry::max_z, G4TTL::maxExtension, G4TTL::minExtension, G4TTL::SETTING::optionBasicGeo, G4TTL::SETTING::optionCEMC, G4TTL::SETTING::optionDR, G4TTL::SETTING::optionEEMCH, G4TTL::SETTING::optionGeo, and G4TTL::positionToVtx.
Referenced by G4Init().