EIC Software: ActsTrack Class Reference
ActsTrack Class Reference
#include <fun4all_coresoftware/blob/master/offline/packages/trackreco/ActsTrack.h>
Public Member Functions
ActsTrack ()
ActsTrack (ActsExamples::TrackParameters params, const std::vector< SourceLink > &links, Acts::Vector3D vertex)
~ActsTrack ()
ActsExamples::TrackParameters getTrackParams ()
void setTrackParams (ActsExamples::TrackParameters params)
std::vector< SourceLink > getSourceLinks ()
void setSourceLinks (const std::vector< SourceLink > &srcLinks)
Acts::Vector3D getVertex ()
void setVertex (Acts::Vector3D vertex)
Private Attributes
ActsExamples::TrackParameters m_trackParams
Initial track seed parameters.
std::vector< SourceLink > m_sourceLinks
SourceLinks associated to this track.
Acts::Vector3D m_vertex
Initial x,y,z vertex estimate.
Detailed Description
A class that contains an Acts track seed and the corresponding source links. Also contains a vertex id corresponding to the original track seed vertex id. Used by a variety of the Acts track fitting classes.
Definition at line 20 of file ActsTrack.h.
View newest version in sPHENIX GitHub at line 20 of file ActsTrack.h
Constructor & Destructor Documentation
ActsTrack::ActsTrack ()
ActsTrack::ActsTrack (ActsExamples::TrackParameters params, const std::vector< SourceLink > & links, Acts::Vector3D vertex) inline
Definition at line 26 of file ActsTrack.h.
View newest version in sPHENIX GitHub at line 26 of file ActsTrack.h
ActsTrack::~ActsTrack () inline
Definition at line 34 of file ActsTrack.h.
View newest version in sPHENIX GitHub at line 34 of file ActsTrack.h
Member Function Documentation
std::vector<SourceLink> ActsTrack::getSourceLinks () inline
Definition at line 41 of file ActsTrack.h.
View newest version in sPHENIX GitHub at line 41 of file ActsTrack.h
References m_sourceLinks.
Referenced by ActsEvaluator::fillProtoTrack(), PHActsTrkFitter::loopTracks(), and PHTpcResiduals::processTrack().
ActsExamples::TrackParameters ActsTrack::getTrackParams () inline
Definition at line 36 of file ActsTrack.h.
View newest version in sPHENIX GitHub at line 36 of file ActsTrack.h
References m_trackParams.
Referenced by ActsEvaluator::fillProtoTrack(), PHActsTrkFitter::loopTracks(), PHActsTrkProp::Process(), and PHTpcResiduals::processTrack().
Acts::Vector3D ActsTrack::getVertex () inline
Definition at line 45 of file ActsTrack.h.
View newest version in sPHENIX GitHub at line 45 of file ActsTrack.h
References m_vertex.
Referenced by PHActsTrkFitter::loopTracks(), and PHActsTrkProp::Process().
void ActsTrack::setSourceLinks (const std::vector< SourceLink > & srcLinks) inline
Definition at line 42 of file ActsTrack.h.
View newest version in sPHENIX GitHub at line 42 of file ActsTrack.h
References m_sourceLinks.
void ActsTrack::setTrackParams (ActsExamples::TrackParameters params) inline
Definition at line 38 of file ActsTrack.h.
View newest version in sPHENIX GitHub at line 38 of file ActsTrack.h
References m_trackParams.
void ActsTrack::setVertex (Acts::Vector3D vertex) inline
Definition at line 46 of file ActsTrack.h.
View newest version in sPHENIX GitHub at line 46 of file ActsTrack.h
References m_vertex.
Member Data Documentation
std::vector<SourceLink> ActsTrack::m_sourceLinks private
SourceLinks associated to this track.
Definition at line 53 of file ActsTrack.h.
View newest version in sPHENIX GitHub at line 53 of file ActsTrack.h
Referenced by getSourceLinks(), and setSourceLinks().
ActsExamples::TrackParameters ActsTrack::m_trackParams private
Initial track seed parameters.
Definition at line 50 of file ActsTrack.h.
View newest version in sPHENIX GitHub at line 50 of file ActsTrack.h
Referenced by getTrackParams(), and setTrackParams().
Acts::Vector3D ActsTrack::m_vertex private
Initial x,y,z vertex estimate.
Definition at line 56 of file ActsTrack.h.
View newest version in sPHENIX GitHub at line 56 of file ActsTrack.h
Referenced by getVertex(), and setVertex().
The documentation for this class was generated from the following file:
fun4all_coresoftware/blob/master/offline/packages/trackreco/ActsTrack.h