EIC Software: EicTrackingRecoHit Class Reference
EicTrackingRecoHit Class Reference abstract
#include <EicRoot/blob/master/eic/tracking/EicTrackingRecoHit.h>
Public Member Functions
EicTrackingRecoHit ()
~EicTrackingRecoHit ()
Protected Member Functions
const
LogicalVolumeLookupTableEntry * GetLookupTableNode (EicTrackingDigiHit *hit, void *ptr)
TMatrixT< double > getHMatrix (const GFAbsTrackRep *stateVector)
virtual unsigned GetMdim () const =0
Detailed Description
Definition at line 20 of file EicTrackingRecoHit.h.
View newest version in sPHENIX GitHub at line 20 of file EicTrackingRecoHit.h
Constructor & Destructor Documentation
EicTrackingRecoHit::EicTrackingRecoHit () inline
Definition at line 22 of file EicTrackingRecoHit.h.
View newest version in sPHENIX GitHub at line 22 of file EicTrackingRecoHit.h
EicTrackingRecoHit::~EicTrackingRecoHit () inline
Definition at line 23 of file EicTrackingRecoHit.h.
View newest version in sPHENIX GitHub at line 23 of file EicTrackingRecoHit.h
Member Function Documentation
TMatrixT< double > EicTrackingRecoHit::getHMatrix (const GFAbsTrackRep * stateVector) protected
Definition at line 18 of file EicTrackingRecoHit.cxx.
View newest version in sPHENIX GitHub at line 18 of file EicTrackingRecoHit.cxx
References GetMdim(), and ip().
Referenced by EicPlanarRecoHit::getHMatrix(), and EicSpaceRecoHit::getHMatrix().
const LogicalVolumeLookupTableEntry * EicTrackingRecoHit::GetLookupTableNode (EicTrackingDigiHit * hit, void * ptr) protected
Definition at line 53 of file EicTrackingRecoHit.cxx.
View newest version in sPHENIX GitHub at line 53 of file EicTrackingRecoHit.cxx
References EicGeoParData::GeantMultiToLogicalIndex(), EicGeoParData::GetLookupTableNode(), and EicTrackingDigiHit::GetMultiIndex().
Referenced by EicPlanarRecoHit::EicPlanarRecoHit(), and EicSpaceRecoHit::EicSpaceRecoHit().
virtual unsigned EicTrackingRecoHit::GetMdim () const protected pure virtual
Implemented in EicSpaceRecoHit, and EicPlanarRecoHit.
Referenced by getHMatrix().
The documentation for this class was generated from the following files:
EicRoot/blob/master/eic/tracking/EicTrackingRecoHit.h
EicRoot/blob/master/eic/tracking/EicTrackingRecoHit.cxx