EIC Software: PHG4SteppingAction Class Reference
PHG4SteppingAction Class Reference abstract
#include <fun4all_coresoftware/blob/master/simulation/g4simulation/g4main/PHG4SteppingAction.h>
Inherited by AllSi_Al_support_SteppingAction, AllSi_Al_support_SteppingAction, AllSiliconTrackerSteppingAction, AllSiliconTrackerSteppingAction, BeamLineMagnetSteppingAction, BeastMagnetSteppingAction, EicFRichSteppingAction, EicFRichSteppingAction, EICG4B0ECALSteppingAction, EICG4B0SteppingAction, EICG4BwdSteppingAction, EICG4dRICHSteppingAction, EICG4LumiSteppingAction, EICG4RPSteppingAction, EICG4ZDCSteppingAction, G4EicDircSteppingAction, G4Example01SteppingAction, G4Example02SteppingAction, G4Example03SteppingAction, G4JLeicBeamLineMagnetSteppingAction, G4JLeicBeamLineMagnetSteppingAction, G4JLeicDIRCSteppingAction, G4JLeicDIRCSteppingAction, G4JLeicVTXSteppingAction, G4JLeicVTXSteppingAction, G4LBLVtxSteppingAction, G4LBLVtxSteppingAction, G4LmonSteppingAction, GdmlImportDetectorSteppingAction, PHG4BackwardHcalSteppingAction, PHG4BarrelEcalSteppingAction, PHG4BbcSteppingAction, PHG4BlockSteppingAction, PHG4CEmcTestBeamSteppingAction, PHG4ConeSteppingAction, PHG4CrystalCalorimeterSteppingAction, PHG4CylinderSteppingAction, PHG4CylinderStripSteppingAction, PHG4ECAPToFSteppingAction, PHG4EICMvtxSteppingAction, PHG4EnvelopeSteppingAction, PHG4EPDSteppingAction, PHG4ForwardDualReadoutSteppingAction, PHG4ForwardEcalSteppingAction, PHG4ForwardHcalSteppingAction, PHG4FPbScSteppingAction, PHG4HcalSteppingAction, PHG4HybridHomogeneousCalorimeterSteppingAction, PHG4InnerHcalSteppingAction, PHG4InttSteppingAction, PHG4LFHcalSteppingAction, PHG4MicromegasSteppingAction, PHG4mRICHSteppingAction, PHG4MvtxSteppingAction, PHG4OuterHcalSteppingAction, PHG4PSTOFSteppingAction, PHG4SectorSteppingAction, PHG4SpacalSteppingAction, PHG4TpcEndCapSteppingAction, PHG4TpcSteppingAction, PHG4TRDSteppingAction, PHG4TTLSteppingAction, and PHG4ZDCSteppingAction.
Public Member Functions
PHG4SteppingAction (const std::string &name, const int i=0)
virtual ~PHG4SteppingAction ()
virtual bool UserSteppingAction (const G4Step *step, bool was_used)=0
stepping action. This defines processing of a single step in a given volume
virtual void Verbosity (const int i)
virtual int Verbosity () const
virtual int Init ()
virtual double GetScintLightYield (const G4Step *step)
get scintillation photon count. It require a custom set SCINTILLATIONYIELD property to work
virtual double GetVisibleEnergyDeposition (const G4Step *step)
get amount of energy that can make scintillation light, in Unit of GeV.
virtual void StoreLocalCoordinate (PHG4Hit *hit, const G4Step *step, const bool do_prepoint, const bool do_postpoint)
Extract local coordinate of the hit and save to PHG4Hit.
virtual void SetInterfacePointers (PHCompositeNode *)
virtual void Print (const std::string &) const
std::string GetName () const
void SetName (const std::string &name)
virtual void SetLightCorrection (const double inner_radius, const double inner_corr, const double outer_radius, const double outer_corr)
virtual double GetLightCorrection (const double r) const
virtual double GetLightCorrection (const double xpos, const double ypos) const
virtual bool ValidCorrection () const
virtual void SetHitNodeName (const std::string &, const std::string &)
Set the G4HIT node names from Subsystem rather than constructing your own.
Private Attributes
int m_Verbosity
double m_LightBalanceInnerRadius
double m_LightBalanceInnerCorr
double m_LightBalanceOuterRadius
double m_LightBalanceOuterCorr
std::string m_Name
std::set< std::string > m_ScintLightYieldMissingMaterialSet
Detailed Description
Definition at line 13 of file PHG4SteppingAction.h.
View newest version in sPHENIX GitHub at line 13 of file PHG4SteppingAction.h
Constructor & Destructor Documentation
PHG4SteppingAction::PHG4SteppingAction (const std::string & name, const int i = 0)
Definition at line 36 of file PHG4SteppingAction.cc.
View newest version in sPHENIX GitHub at line 36 of file PHG4SteppingAction.cc
virtual PHG4SteppingAction::~PHG4SteppingAction () inline virtual
Definition at line 17 of file PHG4SteppingAction.h.
View newest version in sPHENIX GitHub at line 17 of file PHG4SteppingAction.h
Member Function Documentation
double PHG4SteppingAction::GetLightCorrection (const double r) const virtual
Definition at line 184 of file PHG4SteppingAction.cc.
View newest version in sPHENIX GitHub at line 184 of file PHG4SteppingAction.cc
References Acts::UnitConstants::m, m_LightBalanceInnerCorr, m_LightBalanceInnerRadius, m_LightBalanceOuterCorr, m_LightBalanceOuterRadius, max, min, and ValidCorrection().
Referenced by GetLightCorrection(), PHG4InnerHcalSteppingAction::UserSteppingAction(), PHG4EPDSteppingAction::UserSteppingAction(), PHG4OuterHcalSteppingAction::UserSteppingAction(), and PHG4HcalSteppingAction::UserSteppingAction().
double PHG4SteppingAction::GetLightCorrection (const double xpos, const double ypos) const virtual
Definition at line 177 of file PHG4SteppingAction.cc.
View newest version in sPHENIX GitHub at line 177 of file PHG4SteppingAction.cc
References GetLightCorrection().
std::string PHG4SteppingAction::GetName (void) const inline
Definition at line 43 of file PHG4SteppingAction.h.
View newest version in sPHENIX GitHub at line 43 of file PHG4SteppingAction.h
References m_Name.
Referenced by PHG4TpcSteppingAction::UserSteppingAction(), G4Example01SteppingAction::UserSteppingAction(), G4JLeicBeamLineMagnetSteppingAction::UserSteppingAction(), G4Example03SteppingAction::UserSteppingAction(), G4Example02SteppingAction::UserSteppingAction(), G4JLeicDIRCSteppingAction::UserSteppingAction(), G4JLeicVTXSteppingAction::UserSteppingAction(), PHG4PSTOFSteppingAction::UserSteppingAction(), G4LBLVtxSteppingAction::UserSteppingAction(), PHG4CylinderStripSteppingAction::UserSteppingAction(), PHG4BlockSteppingAction::UserSteppingAction(), BeastMagnetSteppingAction::UserSteppingAction(), PHG4EPDSteppingAction::UserSteppingAction(), GdmlImportDetectorSteppingAction::UserSteppingAction(), EicFRichSteppingAction::UserSteppingAction(), AllSi_Al_support_SteppingAction::UserSteppingAction(), AllSiliconTrackerSteppingAction::UserSteppingAction(), PHG4InnerHcalSteppingAction::UserSteppingAction(), PHG4OuterHcalSteppingAction::UserSteppingAction(), PHG4BbcSteppingAction::UserSteppingAction(), BeamLineMagnetSteppingAction::UserSteppingAction(), EICG4dRICHSteppingAction::UserSteppingAction(), EICG4ZDCSteppingAction::UserSteppingAction(), PHG4TpcEndCapSteppingAction::UserSteppingAction(), PHG4mRICHSteppingAction::UserSteppingAction(), PHG4CylinderSteppingAction::UserSteppingAction(), EICG4RPSteppingAction::UserSteppingAction(), G4EicDircSteppingAction::UserSteppingAction(), EICG4BwdSteppingAction::UserSteppingAction(), PHG4MicromegasSteppingAction::UserSteppingAction(), EICG4B0SteppingAction::UserSteppingAction(), EICG4B0ECALSteppingAction::UserSteppingAction(), EICG4LumiSteppingAction::UserSteppingAction(), and PHG4SpacalSteppingAction::UserSteppingAction().
double PHG4SteppingAction::GetScintLightYield (const G4Step * step) virtual
get scintillation photon count. It require a custom set SCINTILLATIONYIELD property to work
Definition at line 47 of file PHG4SteppingAction.cc.
View newest version in sPHENIX GitHub at line 47 of file PHG4SteppingAction.cc
References GetVisibleEnergyDeposition(), Acts::UnitConstants::GeV, it, and m_ScintLightYieldMissingMaterialSet.
double PHG4SteppingAction::GetVisibleEnergyDeposition (const G4Step * step) virtual
get amount of energy that can make scintillation light, in Unit of GeV.
Definition at line 111 of file PHG4SteppingAction.cc.
View newest version in sPHENIX GitHub at line 111 of file PHG4SteppingAction.cc
References Acts::UnitConstants::GeV, and m_Verbosity.
Referenced by GetScintLightYield(), PHG4HcalSteppingAction::UserSteppingAction(), PHG4OuterHcalSteppingAction::UserSteppingAction(), PHG4CylinderStripSteppingAction::UserSteppingAction(), PHG4InnerHcalSteppingAction::UserSteppingAction(), PHG4EPDSteppingAction::UserSteppingAction(), EICG4ZDCSteppingAction::UserSteppingAction(), PHG4HybridHomogeneousCalorimeterSteppingAction::UserSteppingAction(), PHG4LFHcalSteppingAction::UserSteppingAction(), PHG4ForwardDualReadoutSteppingAction::UserSteppingAction(), PHG4BackwardHcalSteppingAction::UserSteppingAction(), PHG4ForwardEcalSteppingAction::UserSteppingAction(), EICG4RPSteppingAction::UserSteppingAction(), PHG4CylinderSteppingAction::UserSteppingAction(), PHG4ForwardHcalSteppingAction::UserSteppingAction(), PHG4ZDCSteppingAction::UserSteppingAction(), EICG4B0ECALSteppingAction::UserSteppingAction(), EICG4BwdSteppingAction::UserSteppingAction(), EICG4LumiSteppingAction::UserSteppingAction(), and PHG4SpacalSteppingAction::UserSteppingAction().
virtual int PHG4SteppingAction::Init (void) inline virtual
Reimplemented in PHG4OuterHcalSteppingAction.
Definition at line 31 of file PHG4SteppingAction.h.
View newest version in sPHENIX GitHub at line 31 of file PHG4SteppingAction.h
Referenced by PHG4OuterHcalSubsystem::InitRunSubsystem(), G4JLeicVTXSubsystem::InitRunSubsystem(), and PHG4PSTOFSubsystem::InitRunSubsystem().
virtual void PHG4SteppingAction::Print (const std::string &) const inline virtual
Definition at line 42 of file PHG4SteppingAction.h.
View newest version in sPHENIX GitHub at line 42 of file PHG4SteppingAction.h
Referenced by PHG4ECAPToFSubsystem::Print(), PHG4TRDSubsystem::Print(), PHG4BarrelEcalSubsystem::Print(), PHG4ForwardHcalSubsystem::Print(), PHG4InnerHcalSubsystem::Print(), PHG4TpcSubsystem::Print(), PHG4CylinderSubsystem::Print(), PHG4CylinderStripSubsystem::Print(), and PHG4BbcSubsystem::Print().
virtual void PHG4SteppingAction::SetHitNodeName (const std::string & , const std::string &) inline virtual
Set the G4HIT node names from Subsystem rather than constructing your own.
Reimplemented in PHG4ZDCSteppingAction, PHG4TpcEndCapSteppingAction, BeamLineMagnetSteppingAction, PHG4BbcSteppingAction, PHG4EPDSteppingAction, and PHG4TpcSteppingAction.
Definition at line 51 of file PHG4SteppingAction.h.
View newest version in sPHENIX GitHub at line 51 of file PHG4SteppingAction.h
Referenced by PHG4EPDSubsystem::InitRunSubsystem(), PHG4ZDCSubsystem::InitRunSubsystem(), PHG4TpcSubsystem::InitRunSubsystem(), BeamLineMagnetSubsystem::InitRunSubsystem(), PHG4TpcEndCapSubsystem::InitRunSubsystem(), and PHG4BbcSubsystem::InitRunSubsystem().
virtual void PHG4SteppingAction::SetInterfacePointers (PHCompositeNode *) inline virtual
Reimplemented in PHG4TTLSteppingAction, PHG4SpacalSteppingAction, EICG4LumiSteppingAction, PHG4MicromegasSteppingAction, EICG4B0SteppingAction, EICG4B0ECALSteppingAction, EICG4BwdSteppingAction, PHG4ZDCSteppingAction, G4EicDircSteppingAction, PHG4TRDSteppingAction, PHG4CylinderSteppingAction, PHG4ForwardHcalSteppingAction, EICG4RPSteppingAction, PHG4OuterHcalSteppingAction, PHG4TpcEndCapSteppingAction, PHG4ForwardDualReadoutSteppingAction, PHG4BackwardHcalSteppingAction, PHG4BarrelEcalSteppingAction, PHG4CrystalCalorimeterSteppingAction, PHG4ForwardEcalSteppingAction, PHG4HybridHomogeneousCalorimeterSteppingAction, PHG4LFHcalSteppingAction, PHG4ECAPToFSteppingAction, PHG4mRICHSteppingAction, BeamLineMagnetSteppingAction, PHG4BbcSteppingAction, EICG4dRICHSteppingAction, EICG4ZDCSteppingAction, PHG4BlockSteppingAction, PHG4CEmcTestBeamSteppingAction, PHG4HcalSteppingAction, PHG4InnerHcalSteppingAction, PHG4CylinderStripSteppingAction, BeastMagnetSteppingAction, AllSi_Al_support_SteppingAction, EicFRichSteppingAction, AllSi_Al_support_SteppingAction, EicFRichSteppingAction, PHG4PSTOFSteppingAction, PHG4EPDSteppingAction, PHG4InttSteppingAction, G4JLeicBeamLineMagnetSteppingAction, G4JLeicDIRCSteppingAction, G4JLeicVTXSteppingAction, G4LBLVtxSteppingAction, G4JLeicBeamLineMagnetSteppingAction, G4JLeicDIRCSteppingAction, G4JLeicVTXSteppingAction, G4Example03SteppingAction, G4Example02SteppingAction, G4LBLVtxSteppingAction, PHG4ConeSteppingAction, PHG4EnvelopeSteppingAction, PHG4SectorSteppingAction, PHG4EICMvtxSteppingAction, PHG4MvtxSteppingAction, PHG4TpcSteppingAction, G4Example01SteppingAction, and PHG4FPbScSteppingAction.
Definition at line 41 of file PHG4SteppingAction.h.
View newest version in sPHENIX GitHub at line 41 of file PHG4SteppingAction.h
Referenced by EicRootSubsystem::process_event(), PHG4ECAPToFSubsystem::process_event(), PHG4TRDSubsystem::process_event(), PHG4EPDSubsystem::process_event(), PHG4ZDCSubsystem::process_event(), PHG4HybridHomogeneousCalorimeterSubsystem::process_event(), PHG4LFHcalSubsystem::process_event(), PHG4ForwardDualReadoutSubsystem::process_event(), PHG4BackwardHcalSubsystem::process_event(), PHG4BarrelEcalSubsystem::process_event(), PHG4CrystalCalorimeterSubsystem::process_event(), PHG4ForwardHcalSubsystem::process_event(), PHG4InnerHcalSubsystem::process_event(), PHG4OuterHcalSubsystem::process_event(), PHG4TpcSubsystem::process_event(), G4LBLVtxSubsystem::process_event(), BeamLineMagnetSubsystem::process_event(), PHG4ForwardEcalSubsystem::process_event(), PHG4BlockSubsystem::process_event(), PHG4ConeSubsystem::process_event(), PHG4CylinderSubsystem::process_event(), PHG4EICMvtxSubsystem::process_event(), PHG4FPbScSubsystem::process_event(), PHG4MvtxSubsystem::process_event(), G4JLeicBeamLineMagnetSubsystem::process_event(), PHG4SectorSubsystem::process_event(), PHG4TTLSubsystem::process_event(), EICG4dRICHSubsystem::process_event(), EICG4RPSubsystem::process_event(), AllSi_Al_support_Subsystem::process_event(), EICG4B0Subsystem::process_event(), EICG4LumiSubsystem::process_event(), PHG4CylinderStripSubsystem::process_event(), EICG4ZDCSubsystem::process_event(), EICG4BwdSubsystem::process_event(), EicFRichSubsystem::process_event(), EICG4B0ECALSubsystem::process_event(), BeastMagnetSubsystem::process_event(), PHG4InttSubsystem::process_event(), PHG4TpcEndCapSubsystem::process_event(), PHG4mRICHSubsystem::process_event(), AllSiliconTrackerSubsystem::process_event(), G4Example01Subsystem::process_event(), G4Example02Subsystem::process_event(), PHG4SpacalSubsystem::process_event(), G4Example03Subsystem::process_event(), G4LmonSubsystem::process_event(), G4JLeicVTXSubsystem::process_event(), G4JLeicDIRCSubsystem::process_event(), G4EicDircSubsystem::process_event(), PHG4BbcSubsystem::process_event(), and PHG4PSTOFSubsystem::process_event().
void PHG4SteppingAction::SetLightCorrection (const double inner_radius, const double inner_corr, const double outer_radius, const double outer_corr) virtual
Definition at line 168 of file PHG4SteppingAction.cc.
View newest version in sPHENIX GitHub at line 168 of file PHG4SteppingAction.cc
References G4BARRELHCAL::inner_radius, m_LightBalanceInnerCorr, m_LightBalanceInnerRadius, m_LightBalanceOuterCorr, m_LightBalanceOuterRadius, and G4BARRELHCAL::outer_radius.
Referenced by PHG4OuterHcalSteppingAction::Init(), PHG4HcalSubsystem::InitRun(), and PHG4InnerHcalSteppingAction::PHG4InnerHcalSteppingAction().
void PHG4SteppingAction::SetName (const std::string & name) inline
Definition at line 44 of file PHG4SteppingAction.h.
View newest version in sPHENIX GitHub at line 44 of file PHG4SteppingAction.h
References m_Name, and name.
Referenced by PHG4OuterHcalSteppingAction::PHG4OuterHcalSteppingAction(), and PHG4TpcSteppingAction::PHG4TpcSteppingAction().
void PHG4SteppingAction::StoreLocalCoordinate (PHG4Hit * hit, const G4Step * step, const bool do_prepoint, const bool do_postpoint) virtual
Extract local coordinate of the hit and save to PHG4Hit.
Definition at line 133 of file PHG4SteppingAction.cc.
View newest version in sPHENIX GitHub at line 133 of file PHG4SteppingAction.cc
References Acts::UnitConstants::cm, PHG4Hit::set_local_x(), PHG4Hit::set_local_y(), and PHG4Hit::set_local_z().
Referenced by PHG4EICMvtxSteppingAction::UserSteppingAction(), PHG4MvtxSteppingAction::UserSteppingAction(), PHG4InttSteppingAction::UserSteppingAction(), and PHG4SpacalSteppingAction::UserSteppingAction().
virtual bool PHG4SteppingAction::UserSteppingAction (const G4Step * step, bool was_used) pure virtual
stepping action. This defines processing of a single step in a given volume
returns true if hits associated to this step was processed by this detector
Parameters
step pointer to the geant 4 step class
was_used,: true if the hit was already used by a previously registered subsystem
Implemented in PHG4TTLSteppingAction, PHG4SpacalSteppingAction, EICG4LumiSteppingAction, PHG4MicromegasSteppingAction, EICG4B0SteppingAction, EICG4B0ECALSteppingAction, EICG4BwdSteppingAction, PHG4ZDCSteppingAction, G4EicDircSteppingAction, PHG4TRDSteppingAction, PHG4CylinderSteppingAction, PHG4ForwardHcalSteppingAction, EICG4RPSteppingAction, PHG4TpcEndCapSteppingAction, PHG4ForwardDualReadoutSteppingAction, PHG4BackwardHcalSteppingAction, PHG4CrystalCalorimeterSteppingAction, PHG4ForwardEcalSteppingAction, PHG4HybridHomogeneousCalorimeterSteppingAction, PHG4LFHcalSteppingAction, PHG4ECAPToFSteppingAction, PHG4mRICHSteppingAction, BeamLineMagnetSteppingAction, PHG4BbcSteppingAction, EICG4dRICHSteppingAction, PHG4BarrelEcalSteppingAction, EICG4ZDCSteppingAction, GdmlImportDetectorSteppingAction, PHG4BlockSteppingAction, PHG4CEmcTestBeamSteppingAction, PHG4HcalSteppingAction, PHG4InnerHcalSteppingAction, PHG4OuterHcalSteppingAction, PHG4EPDSteppingAction, PHG4InttSteppingAction, PHG4CylinderStripSteppingAction, BeastMagnetSteppingAction, AllSi_Al_support_SteppingAction, AllSiliconTrackerSteppingAction, EicFRichSteppingAction, AllSi_Al_support_SteppingAction, AllSiliconTrackerSteppingAction, EicFRichSteppingAction, PHG4PSTOFSteppingAction, G4JLeicBeamLineMagnetSteppingAction, G4JLeicDIRCSteppingAction, G4JLeicVTXSteppingAction, G4LBLVtxSteppingAction, G4JLeicBeamLineMagnetSteppingAction, G4JLeicDIRCSteppingAction, G4JLeicVTXSteppingAction, G4LmonSteppingAction, G4Example03SteppingAction, G4Example02SteppingAction, G4LBLVtxSteppingAction, PHG4ConeSteppingAction, PHG4EnvelopeSteppingAction, PHG4SectorSteppingAction, PHG4EICMvtxSteppingAction, PHG4MvtxSteppingAction, PHG4TpcSteppingAction, G4Example01SteppingAction, and PHG4FPbScSteppingAction.
bool PHG4SteppingAction::ValidCorrection () const virtual
Definition at line 198 of file PHG4SteppingAction.cc.
View newest version in sPHENIX GitHub at line 198 of file PHG4SteppingAction.cc
References m_LightBalanceInnerCorr, m_LightBalanceInnerRadius, m_LightBalanceOuterCorr, and m_LightBalanceOuterRadius.
Referenced by GetLightCorrection(), PHG4HcalSteppingAction::UserSteppingAction(), and PHG4OuterHcalSteppingAction::UserSteppingAction().
virtual void PHG4SteppingAction::Verbosity (const int i) inline virtual
Definition at line 29 of file PHG4SteppingAction.h.
View newest version in sPHENIX GitHub at line 29 of file PHG4SteppingAction.h
References m_Verbosity.
Referenced by PHG4EICMvtxSubsystem::InitRunSubsystem(), PHG4MvtxSubsystem::InitRunSubsystem(), and PHG4InttSubsystem::InitRunSubsystem().
virtual int PHG4SteppingAction::Verbosity () const inline virtual
Definition at line 30 of file PHG4SteppingAction.h.
View newest version in sPHENIX GitHub at line 30 of file PHG4SteppingAction.h
References m_Verbosity.
Referenced by PHG4mRICHSteppingAction::GetModuleID(), PHG4EICMvtxSteppingAction::SetInterfacePointers(), PHG4MvtxSteppingAction::SetInterfacePointers(), PHG4TpcSteppingAction::SetInterfacePointers(), G4LBLVtxSteppingAction::SetInterfacePointers(), G4JLeicBeamLineMagnetSteppingAction::SetInterfacePointers(), PHG4EPDSteppingAction::SetInterfacePointers(), PHG4InttSteppingAction::SetInterfacePointers(), PHG4CEmcTestBeamSteppingAction::SetInterfacePointers(), PHG4HcalSteppingAction::SetInterfacePointers(), PHG4InnerHcalSteppingAction::SetInterfacePointers(), PHG4BbcSteppingAction::SetInterfacePointers(), BeamLineMagnetSteppingAction::SetInterfacePointers(), PHG4LFHcalSteppingAction::SetInterfacePointers(), PHG4ECAPToFSteppingAction::SetInterfacePointers(), PHG4CrystalCalorimeterSteppingAction::SetInterfacePointers(), PHG4mRICHSteppingAction::SetInterfacePointers(), PHG4ForwardDualReadoutSteppingAction::SetInterfacePointers(), PHG4BackwardHcalSteppingAction::SetInterfacePointers(), PHG4BarrelEcalSteppingAction::SetInterfacePointers(), PHG4OuterHcalSteppingAction::SetInterfacePointers(), PHG4ForwardEcalSteppingAction::SetInterfacePointers(), PHG4HybridHomogeneousCalorimeterSteppingAction::SetInterfacePointers(), PHG4ForwardHcalSteppingAction::SetInterfacePointers(), PHG4TRDSteppingAction::SetInterfacePointers(), PHG4ZDCSteppingAction::SetInterfacePointers(), G4EicDircSteppingAction::SetInterfacePointers(), PHG4SpacalSteppingAction::SetInterfacePointers(), PHG4MvtxSteppingAction::UserSteppingAction(), PHG4EICMvtxSteppingAction::UserSteppingAction(), PHG4TpcSteppingAction::UserSteppingAction(), PHG4InttSteppingAction::UserSteppingAction(), EICG4dRICHSteppingAction::UserSteppingAction(), PHG4ForwardEcalSteppingAction::UserSteppingAction(), PHG4ForwardDualReadoutSteppingAction::UserSteppingAction(), PHG4BackwardHcalSteppingAction::UserSteppingAction(), PHG4LFHcalSteppingAction::UserSteppingAction(), PHG4ForwardHcalSteppingAction::UserSteppingAction(), PHG4ZDCSteppingAction::UserSteppingAction(), and PHG4SpacalSteppingAction::UserSteppingAction().
Member Data Documentation
double PHG4SteppingAction::m_LightBalanceInnerCorr private
Definition at line 56 of file PHG4SteppingAction.h.
View newest version in sPHENIX GitHub at line 56 of file PHG4SteppingAction.h
Referenced by GetLightCorrection(), SetLightCorrection(), and ValidCorrection().
double PHG4SteppingAction::m_LightBalanceInnerRadius private
Definition at line 55 of file PHG4SteppingAction.h.
View newest version in sPHENIX GitHub at line 55 of file PHG4SteppingAction.h
Referenced by GetLightCorrection(), SetLightCorrection(), and ValidCorrection().
double PHG4SteppingAction::m_LightBalanceOuterCorr private
Definition at line 58 of file PHG4SteppingAction.h.
View newest version in sPHENIX GitHub at line 58 of file PHG4SteppingAction.h
Referenced by GetLightCorrection(), SetLightCorrection(), and ValidCorrection().
double PHG4SteppingAction::m_LightBalanceOuterRadius private
Definition at line 57 of file PHG4SteppingAction.h.
View newest version in sPHENIX GitHub at line 57 of file PHG4SteppingAction.h
Referenced by GetLightCorrection(), SetLightCorrection(), and ValidCorrection().
std::string PHG4SteppingAction::m_Name private
Definition at line 59 of file PHG4SteppingAction.h.
View newest version in sPHENIX GitHub at line 59 of file PHG4SteppingAction.h
Referenced by GetName(), and SetName().
std::set<std::string> PHG4SteppingAction::m_ScintLightYieldMissingMaterialSet private
Definition at line 60 of file PHG4SteppingAction.h.
View newest version in sPHENIX GitHub at line 60 of file PHG4SteppingAction.h
Referenced by GetScintLightYield().
int PHG4SteppingAction::m_Verbosity private
Definition at line 54 of file PHG4SteppingAction.h.
View newest version in sPHENIX GitHub at line 54 of file PHG4SteppingAction.h
Referenced by GetVisibleEnergyDeposition(), and Verbosity().
The documentation for this class was generated from the following files:
fun4all_coresoftware/blob/master/simulation/g4simulation/g4main/PHG4SteppingAction.h
fun4all_coresoftware/blob/master/simulation/g4simulation/g4main/PHG4SteppingAction.cc