EIC Software: EicBitMask< T > Class Template Reference
EicBitMask< T > Class Template Reference
#include <EicRoot/blob/master/eic/base/EicGeoMap.h>
Public Member Functions
EicBitMask ()
EicBitMask (unsigned maxEntryNum)
~EicBitMask ()
void ResetVars ()
void SetShift (unsigned shift)
void SetBitNum (unsigned bitNum)
unsigned GetBitNum () const
unsigned GetShift () const
T GetBitMask () const
T GetMaskedBits (T value) const
EicBitMask ()
EicBitMask (unsigned maxEntryNum)
~EicBitMask ()
void ResetVars ()
void SetShift (unsigned shift)
void SetBitNum (unsigned bitNum)
unsigned GetBitNum () const
unsigned GetShift () const
T GetBitMask () const
T GetMaskedBits (T value) const
Private Member Functions
void SetMask ()
ClassDef (EicBitMask< T >, 1)
void SetMask ()
ClassDef (EicBitMask< T >, 1)
Private Attributes
UInt_t mBitNum
UInt_t mShift
T mMask
Detailed Description
template<typename T>
class EicBitMask< T >
Definition at line 68 of file EicGeoMap.h.
View newest version in sPHENIX GitHub at line 68 of file EicGeoMap.h
Constructor & Destructor Documentation
template<typename T> EicBitMask< T >::EicBitMask () inline
Definition at line 71 of file EicGeoMap.h.
View newest version in sPHENIX GitHub at line 71 of file EicGeoMap.h
template<typename T> EicBitMask< T >::EicBitMask (unsigned maxEntryNum) inline
Definition at line 72 of file EicGeoMap.h.
View newest version in sPHENIX GitHub at line 72 of file EicGeoMap.h
template<typename T> EicBitMask< T >::~EicBitMask () inline
Definition at line 87 of file EicGeoMap.h.
View newest version in sPHENIX GitHub at line 87 of file EicGeoMap.h
template<typename T> EicBitMask< T >::EicBitMask () inline
Definition at line 71 of file EicGeoMap.h.
View newest version in sPHENIX GitHub at line 71 of file EicGeoMap.h
template<typename T> EicBitMask< T >::EicBitMask (unsigned maxEntryNum) inline
Definition at line 72 of file EicGeoMap.h.
View newest version in sPHENIX GitHub at line 72 of file EicGeoMap.h
template<typename T> EicBitMask< T >::~EicBitMask () inline
Definition at line 87 of file EicGeoMap.h.
View newest version in sPHENIX GitHub at line 87 of file EicGeoMap.h
Member Function Documentation
template<typename T> EicBitMask< T >::ClassDef (EicBitMask< T > , 1) private
template<typename T> EicBitMask< T >::ClassDef (EicBitMask< T > , 1) private
template<typename T> T EicBitMask< T >::GetBitMask () const inline
Definition at line 96 of file EicGeoMap.h.
View newest version in sPHENIX GitHub at line 96 of file EicGeoMap.h
Referenced by EicGeoParData::GetLogicalCoordCore(), EicDetector::GetNodeMultiIndex(), and EicGeoParData::SetMappingTableEntry().
template<typename T> T EicBitMask< T >::GetBitMask () const inline
Definition at line 96 of file EicGeoMap.h.
View newest version in sPHENIX GitHub at line 96 of file EicGeoMap.h
template<typename T> unsigned EicBitMask< T >::GetBitNum () const inline
Definition at line 94 of file EicGeoMap.h.
View newest version in sPHENIX GitHub at line 94 of file EicGeoMap.h
template<typename T> unsigned EicBitMask< T >::GetBitNum () const inline
Definition at line 94 of file EicGeoMap.h.
View newest version in sPHENIX GitHub at line 94 of file EicGeoMap.h
Referenced by EicGeoParData::AddLogicalVolumeGroup(), and EicGeoMap::CalculateBitPattern().
template<typename T> T EicBitMask< T >::GetMaskedBits (T value) const inline
Definition at line 98 of file EicGeoMap.h.
View newest version in sPHENIX GitHub at line 98 of file EicGeoMap.h
template<typename T> T EicBitMask< T >::GetMaskedBits (T value) const inline
Definition at line 98 of file EicGeoMap.h.
View newest version in sPHENIX GitHub at line 98 of file EicGeoMap.h
Referenced by GeantVolumeLevel::GetMaskedBits().
template<typename T> unsigned EicBitMask< T >::GetShift () const inline
Definition at line 95 of file EicGeoMap.h.
View newest version in sPHENIX GitHub at line 95 of file EicGeoMap.h
Referenced by EicGeoParData::GetLogicalCoordCore(), EicDetector::GetNodeMultiIndex(), EicGeoMap::SetMappingTableEntry(), and EicGeoParData::SetMappingTableEntry().
template<typename T> unsigned EicBitMask< T >::GetShift () const inline
Definition at line 95 of file EicGeoMap.h.
View newest version in sPHENIX GitHub at line 95 of file EicGeoMap.h
template<typename T> void EicBitMask< T >::ResetVars () inline
Definition at line 89 of file EicGeoMap.h.
View newest version in sPHENIX GitHub at line 89 of file EicGeoMap.h
Referenced by EicBitMask< ULogicalIndex_t >::EicBitMask().
template<typename T> void EicBitMask< T >::ResetVars () inline
Definition at line 89 of file EicGeoMap.h.
View newest version in sPHENIX GitHub at line 89 of file EicGeoMap.h
template<typename T> void EicBitMask< T >::SetBitNum (unsigned bitNum) inline
Definition at line 92 of file EicGeoMap.h.
View newest version in sPHENIX GitHub at line 92 of file EicGeoMap.h
template<typename T> void EicBitMask< T >::SetBitNum (unsigned bitNum) inline
Definition at line 92 of file EicGeoMap.h.
View newest version in sPHENIX GitHub at line 92 of file EicGeoMap.h
template<typename T> void EicBitMask< T >::SetMask () inline private
Definition at line 105 of file EicGeoMap.h.
View newest version in sPHENIX GitHub at line 105 of file EicGeoMap.h
Referenced by EicBitMask< ULogicalIndex_t >::EicBitMask(), and EicBitMask< ULogicalIndex_t >::SetBitNum().
template<typename T> void EicBitMask< T >::SetMask () inline private
Definition at line 105 of file EicGeoMap.h.
View newest version in sPHENIX GitHub at line 105 of file EicGeoMap.h
template<typename T> void EicBitMask< T >::SetShift (unsigned shift) inline
Definition at line 91 of file EicGeoMap.h.
View newest version in sPHENIX GitHub at line 91 of file EicGeoMap.h
template<typename T> void EicBitMask< T >::SetShift (unsigned shift) inline
Definition at line 91 of file EicGeoMap.h.
View newest version in sPHENIX GitHub at line 91 of file EicGeoMap.h
Referenced by EicGeoParData::AddLogicalVolumeGroup(), and EicGeoMap::CalculateBitPattern().
Member Data Documentation
template<typename T> UInt_t EicBitMask< T >::mBitNum private
Definition at line 98 of file EicGeoMap.h.
View newest version in sPHENIX GitHub at line 98 of file EicGeoMap.h
Referenced by EicBitMask< ULogicalIndex_t >::EicBitMask(), EicBitMask< ULogicalIndex_t >::GetBitNum(), EicBitMask< ULogicalIndex_t >::ResetVars(), EicBitMask< ULogicalIndex_t >::SetBitNum(), and EicBitMask< ULogicalIndex_t >::SetMask().
template<typename T> T EicBitMask< T >::mMask private
Definition at line 103 of file EicGeoMap.h.
View newest version in sPHENIX GitHub at line 103 of file EicGeoMap.h
Referenced by EicBitMask< ULogicalIndex_t >::GetBitMask(), EicBitMask< ULogicalIndex_t >::GetMaskedBits(), EicBitMask< ULogicalIndex_t >::ResetVars(), and EicBitMask< ULogicalIndex_t >::SetMask().
template<typename T> UInt_t EicBitMask< T >::mShift private
Definition at line 102 of file EicGeoMap.h.
View newest version in sPHENIX GitHub at line 102 of file EicGeoMap.h
Referenced by EicBitMask< ULogicalIndex_t >::GetMaskedBits(), EicBitMask< ULogicalIndex_t >::GetShift(), EicBitMask< ULogicalIndex_t >::ResetVars(), and EicBitMask< ULogicalIndex_t >::SetShift().
The documentation for this class was generated from the following files:
EicRoot/blob/master/eic/base/EicGeoMap.h
EicToyModel/blob/master/include/EicGeoMap.h