EIC Software: ParticleFlowElementv1 Class Reference
ParticleFlowElementv1 Class Reference
#include <fun4all_coresoftware/blob/master/offline/packages/particleflow/ParticleFlowElementv1.h>
Public Member Functions
ParticleFlowElementv1 ()
virtual ~ParticleFlowElementv1 ()
void identify (std::ostream &os=std::cout) const
void Reset ()
Clear Event.
int isValid () const
isValid returns non zero if object contains vailid data
ParticleFlowElement::PFLOWTYPE get_type () const
void set_type (ParticleFlowElement::PFLOWTYPE type)
unsigned int get_id () const
void set_id (unsigned int id)
float get_px () const
void set_px (float px)
float get_py () const
void set_py (float py)
float get_pz () const
void set_pz (float pz)
float get_e () const
void set_e (float e)
float get_p () const
float get_pt () const
float get_et () const
float get_eta () const
float get_phi () const
float get_mass () const
Public Member Functions inherited from ParticleFlowElement
ParticleFlowElement ()
virtual ~ParticleFlowElement ()
ClassDef (ParticleFlowElement, 1)
Public Member Functions inherited from PHObject
PHObject ()
ctor
virtual ~PHObject ()
dtor
virtual PHObject * CloneMe () const
Virtual copy constructor.
virtual PHObject * clone () const final
virtual PHObject * Clone (const char *newname="") const final
virtual void Copy (TObject &object) const final
virtual int isValid (const float) const
virtual int isValid (const double) const
virtual int isValid (const int) const
virtual int isValid (const unsigned int) const
virtual int isImplemented (const float f) const
virtual int isImplemented (const double f) const
virtual int isImplemented (const int i) const
virtual int isImplemented (const unsigned int i) const
virtual int Integrate () const
virtual int Integrate (PHObject *obj)
virtual void CopyFrom (const PHObject *obj)
Private Member Functions
ClassDef (ParticleFlowElementv1, 1)
Private Attributes
unsigned int _id
unique identifier within container
ParticleFlowElement::PFLOWTYPE _type
float _mom [3]
pflow momentum vector (px,py,pz)
float _e
pflow energy
Additional Inherited Members
Public Types inherited from ParticleFlowElement
enum PFLOWTYPE {
UNASSIGNED = -1, MATCHED_CHARGED_HADRON = 0, UNMATCHED_CHARGED_HADRON = 1, UNMATCHED_EM_PARTICLE = 2,
UNMATCHED_NEUTRAL_HADRON = 3, LEFTOVER_EM_PARTICLE = 4
}
Detailed Description
Definition at line 17 of file ParticleFlowElementv1.h.
View newest version in sPHENIX GitHub at line 17 of file ParticleFlowElementv1.h
Constructor & Destructor Documentation
ParticleFlowElementv1::ParticleFlowElementv1 ()
Definition at line 6 of file ParticleFlowElementv1.cc.
View newest version in sPHENIX GitHub at line 6 of file ParticleFlowElementv1.cc
References _id, _mom, and _type.
virtual ParticleFlowElementv1::~ParticleFlowElementv1 () inline virtual
Definition at line 21 of file ParticleFlowElementv1.h.
View newest version in sPHENIX GitHub at line 21 of file ParticleFlowElementv1.h
Member Function Documentation
ParticleFlowElementv1::ClassDef (ParticleFlowElementv1 , 1) private
float ParticleFlowElementv1::get_e () const inline virtual
Reimplemented from ParticleFlowElement.
Definition at line 46 of file ParticleFlowElementv1.h.
View newest version in sPHENIX GitHub at line 46 of file ParticleFlowElementv1.h
References _e.
Referenced by get_et(), get_mass(), and identify().
float ParticleFlowElementv1::get_et () const virtual
Reimplemented from ParticleFlowElement.
Definition at line 53 of file ParticleFlowElementv1.cc.
View newest version in sPHENIX GitHub at line 53 of file ParticleFlowElementv1.cc
References get_e(), get_p(), and get_pt().
float ParticleFlowElementv1::get_eta () const virtual
Reimplemented from ParticleFlowElement.
Definition at line 58 of file ParticleFlowElementv1.cc.
View newest version in sPHENIX GitHub at line 58 of file ParticleFlowElementv1.cc
References get_pt(), and get_pz().
unsigned int ParticleFlowElementv1::get_id () const inline virtual
Reimplemented from ParticleFlowElement.
Definition at line 34 of file ParticleFlowElementv1.h.
View newest version in sPHENIX GitHub at line 34 of file ParticleFlowElementv1.h
References _id.
Referenced by identify().
float ParticleFlowElementv1::get_mass () const virtual
Reimplemented from ParticleFlowElement.
Definition at line 68 of file ParticleFlowElementv1.cc.
View newest version in sPHENIX GitHub at line 68 of file ParticleFlowElementv1.cc
References get_e(), get_px(), get_py(), and get_pz().
float ParticleFlowElementv1::get_p () const virtual
Reimplemented from ParticleFlowElement.
Definition at line 43 of file ParticleFlowElementv1.cc.
View newest version in sPHENIX GitHub at line 43 of file ParticleFlowElementv1.cc
References get_px(), get_py(), and get_pz().
Referenced by get_et().
float ParticleFlowElementv1::get_phi () const virtual
Reimplemented from ParticleFlowElement.
Definition at line 63 of file ParticleFlowElementv1.cc.
View newest version in sPHENIX GitHub at line 63 of file ParticleFlowElementv1.cc
References get_px(), and get_py().
float ParticleFlowElementv1::get_pt () const virtual
Reimplemented from ParticleFlowElement.
Definition at line 48 of file ParticleFlowElementv1.cc.
View newest version in sPHENIX GitHub at line 48 of file ParticleFlowElementv1.cc
References get_px(), and get_py().
Referenced by get_et(), and get_eta().
float ParticleFlowElementv1::get_px () const inline virtual
Reimplemented from ParticleFlowElement.
Definition at line 37 of file ParticleFlowElementv1.h.
View newest version in sPHENIX GitHub at line 37 of file ParticleFlowElementv1.h
References _mom.
Referenced by get_mass(), get_p(), get_phi(), get_pt(), and identify().
float ParticleFlowElementv1::get_py () const inline virtual
Reimplemented from ParticleFlowElement.
Definition at line 40 of file ParticleFlowElementv1.h.
View newest version in sPHENIX GitHub at line 40 of file ParticleFlowElementv1.h
References _mom.
Referenced by get_mass(), get_p(), get_phi(), get_pt(), and identify().
float ParticleFlowElementv1::get_pz () const inline virtual
Reimplemented from ParticleFlowElement.
Definition at line 43 of file ParticleFlowElementv1.h.
View newest version in sPHENIX GitHub at line 43 of file ParticleFlowElementv1.h
References _mom.
Referenced by get_eta(), get_mass(), get_p(), and identify().
ParticleFlowElement::PFLOWTYPE ParticleFlowElementv1::get_type () const inline virtual
Reimplemented from ParticleFlowElement.
Definition at line 31 of file ParticleFlowElementv1.h.
View newest version in sPHENIX GitHub at line 31 of file ParticleFlowElementv1.h
References _type.
Referenced by identify().
void ParticleFlowElementv1::identify (std::ostream & os = std::cout) const virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from ParticleFlowElement.
Definition at line 16 of file ParticleFlowElementv1.cc.
View newest version in sPHENIX GitHub at line 16 of file ParticleFlowElementv1.cc
References get_e(), get_id(), get_px(), get_py(), get_pz(), and get_type().
int ParticleFlowElementv1::isValid () const virtual
isValid returns non zero if object contains vailid data
Reimplemented from ParticleFlowElement.
Definition at line 32 of file ParticleFlowElementv1.cc.
View newest version in sPHENIX GitHub at line 32 of file ParticleFlowElementv1.cc
References _e, and _mom.
void ParticleFlowElementv1::Reset () virtual
Clear Event.
Reimplemented from ParticleFlowElement.
Definition at line 26 of file ParticleFlowElementv1.cc.
View newest version in sPHENIX GitHub at line 26 of file ParticleFlowElementv1.cc
References _e, and _mom.
void ParticleFlowElementv1::set_e (float e) inline virtual
Reimplemented from ParticleFlowElement.
Definition at line 47 of file ParticleFlowElementv1.h.
View newest version in sPHENIX GitHub at line 47 of file ParticleFlowElementv1.h
References _e, and analysis::e.
void ParticleFlowElementv1::set_id (unsigned int id) inline virtual
Reimplemented from ParticleFlowElement.
Definition at line 35 of file ParticleFlowElementv1.h.
View newest version in sPHENIX GitHub at line 35 of file ParticleFlowElementv1.h
References _id.
void ParticleFlowElementv1::set_px (float px) inline virtual
Reimplemented from ParticleFlowElement.
Definition at line 38 of file ParticleFlowElementv1.h.
View newest version in sPHENIX GitHub at line 38 of file ParticleFlowElementv1.h
References _mom.
void ParticleFlowElementv1::set_py (float py) inline virtual
Reimplemented from ParticleFlowElement.
Definition at line 41 of file ParticleFlowElementv1.h.
View newest version in sPHENIX GitHub at line 41 of file ParticleFlowElementv1.h
References _mom.
void ParticleFlowElementv1::set_pz (float pz) inline virtual
Reimplemented from ParticleFlowElement.
Definition at line 44 of file ParticleFlowElementv1.h.
View newest version in sPHENIX GitHub at line 44 of file ParticleFlowElementv1.h
References _mom.
void ParticleFlowElementv1::set_type (ParticleFlowElement::PFLOWTYPE type) inline virtual
Reimplemented from ParticleFlowElement.
Definition at line 32 of file ParticleFlowElementv1.h.
View newest version in sPHENIX GitHub at line 32 of file ParticleFlowElementv1.h
References _type.
Member Data Documentation
float ParticleFlowElementv1::_e private
pflow energy
Definition at line 67 of file ParticleFlowElementv1.h.
View newest version in sPHENIX GitHub at line 67 of file ParticleFlowElementv1.h
Referenced by get_e(), isValid(), Reset(), and set_e().
unsigned int ParticleFlowElementv1::_id private
unique identifier within container
Definition at line 58 of file ParticleFlowElementv1.h.
View newest version in sPHENIX GitHub at line 58 of file ParticleFlowElementv1.h
Referenced by get_id(), ParticleFlowElementv1(), and set_id().
float ParticleFlowElementv1::_mom[3] private
pflow momentum vector (px,py,pz)
Definition at line 64 of file ParticleFlowElementv1.h.
View newest version in sPHENIX GitHub at line 64 of file ParticleFlowElementv1.h
Referenced by get_px(), get_py(), get_pz(), isValid(), ParticleFlowElementv1(), Reset(), set_px(), set_py(), and set_pz().
ParticleFlowElement::PFLOWTYPE ParticleFlowElementv1::_type private
Definition at line 61 of file ParticleFlowElementv1.h.
View newest version in sPHENIX GitHub at line 61 of file ParticleFlowElementv1.h
Referenced by get_type(), ParticleFlowElementv1(), and set_type().
The documentation for this class was generated from the following files:
fun4all_coresoftware/blob/master/offline/packages/particleflow/ParticleFlowElementv1.h
fun4all_coresoftware/blob/master/offline/packages/particleflow/ParticleFlowElementv1.cc