EIC Software: erhic::DoubleAngleComputer Class Reference
erhic::DoubleAngleComputer Class Reference
#include <eic-smear/blob/master/include/eicsmear/erhic/Kinematics.h>
Public Member Functions
virtual ~DoubleAngleComputer ()
DoubleAngleComputer (const EventDis &)
virtual DisKinematics * Calculate ()
Public Member Functions inherited from erhic::KinematicsComputer
virtual ~KinematicsComputer ()
Protected Member Functions
virtual Double_t ComputeQuarkAngle () const
virtual Double_t ComputeY () const
virtual Double_t ComputeQSquared () const
virtual Double_t ComputeX () const
Protected Attributes
const EventDis & mEvent
Bool_t mHasChanged
Double_t mAngle
Caches the quark angle.
std::vector< const
VirtualParticle * > mParticles
Detailed Description
Computes DIS event kinematics from a mixture of hadronic and lepton variables using the double-angle method.
Definition at line 119 of file Kinematics.h.
View newest version in sPHENIX GitHub at line 119 of file Kinematics.h
Constructor & Destructor Documentation
erhic::DoubleAngleComputer::~DoubleAngleComputer () virtual
Definition at line 410 of file Kinematics.cxx.
View newest version in sPHENIX GitHub at line 410 of file Kinematics.cxx
References mParticles.
erhic::DoubleAngleComputer::DoubleAngleComputer (const EventDis & event) explicit
Initialise with the event to compute. If the second argument is non-NULL, use the beam information from it in the computation. If it is NULL, determine the beam information automatically from the event. This allows the same class to be used with smeared calculations, where the beam information isn't associated with the smeared event itself.
Definition at line 424 of file Kinematics.cxx.
View newest version in sPHENIX GitHub at line 424 of file Kinematics.cxx
References erhic::VirtualEvent::HadronicFinalState(), it, mEvent, and mParticles.
Member Function Documentation
DisKinematics * erhic::DoubleAngleComputer::Calculate (void) virtual
Implements erhic::KinematicsComputer.
Definition at line 440 of file Kinematics.cxx.
View newest version in sPHENIX GitHub at line 440 of file Kinematics.cxx
References erhic::EventDis::BeamHadron(), ComputeQSquared(), ComputeX(), ComputeY(), erhic::VirtualParticle::GetM(), mEvent, mHasChanged, erhic::DisKinematics::mQ2, erhic::DisKinematics::mW2, erhic::DisKinematics::mX, and erhic::DisKinematics::mY.
Referenced by erhic::Pythia6EventBuilder::BuildEvent(), Smear::Detector::FillEventKinematics(), and erhic::EventFromAsciiFactory< T >::FinishEvent().
Double_t erhic::DoubleAngleComputer::ComputeQSquared () const protected virtual
Definition at line 500 of file Kinematics.cxx.
View newest version in sPHENIX GitHub at line 500 of file Kinematics.cxx
References erhic::EventDis::BeamLepton(), ComputeQuarkAngle(), gamma(), erhic::VirtualParticle::GetE(), erhic::VirtualParticle::GetTheta(), max, mEvent, erhic::EventDis::ScatteredLepton(), and theta().
Referenced by Calculate(), and ComputeX().
Double_t erhic::DoubleAngleComputer::ComputeQuarkAngle () const protected virtual
Scattering angle of struck quark.
Definition at line 459 of file Kinematics.cxx.
View newest version in sPHENIX GitHub at line 459 of file Kinematics.cxx
References Acts::UnitConstants::h, it, mAngle, mHasChanged, and mParticles.
Referenced by ComputeQSquared(), and ComputeY().
Double_t erhic::DoubleAngleComputer::ComputeX () const protected virtual
Definition at line 519 of file Kinematics.cxx.
View newest version in sPHENIX GitHub at line 519 of file Kinematics.cxx
References erhic::EventDis::BeamHadron(), erhic::EventDis::BeamLepton(), ComputeQSquared(), ComputeY(), erhic::VirtualParticle::Get4Vector(), mEvent, Acts::UnitConstants::s, x, and y.
Referenced by Calculate().
Double_t erhic::DoubleAngleComputer::ComputeY () const protected virtual
Definition at line 483 of file Kinematics.cxx.
View newest version in sPHENIX GitHub at line 483 of file Kinematics.cxx
References ComputeQuarkAngle(), gamma(), erhic::VirtualParticle::GetTheta(), mEvent, erhic::EventDis::ScatteredLepton(), theta(), and y.
Referenced by Calculate(), and ComputeX().
Member Data Documentation
Double_t erhic::DoubleAngleComputer::mAngle mutable protected
Caches the quark angle.
Definition at line 147 of file Kinematics.h.
View newest version in sPHENIX GitHub at line 147 of file Kinematics.h
Referenced by ComputeQuarkAngle().
const EventDis& erhic::DoubleAngleComputer::mEvent protected
Definition at line 135 of file Kinematics.h.
View newest version in sPHENIX GitHub at line 135 of file Kinematics.h
Referenced by Calculate(), ComputeQSquared(), ComputeX(), ComputeY(), and DoubleAngleComputer().
Bool_t erhic::DoubleAngleComputer::mHasChanged mutable protected
Stores whether the particle list has changed since the last computation of the quark angle.
Definition at line 145 of file Kinematics.h.
View newest version in sPHENIX GitHub at line 145 of file Kinematics.h
Referenced by Calculate(), and ComputeQuarkAngle().
std::vector<const VirtualParticle*> erhic::DoubleAngleComputer::mParticles protected
Definition at line 148 of file Kinematics.h.
View newest version in sPHENIX GitHub at line 148 of file Kinematics.h
Referenced by ComputeQuarkAngle(), DoubleAngleComputer(), and ~DoubleAngleComputer().
The documentation for this class was generated from the following files:
eic-smear/blob/master/include/eicsmear/erhic/Kinematics.h
eic-smear/blob/master/src/erhic/Kinematics.cxx