EIC Software: TpcSpaceChargeReconstruction Class Reference
TpcSpaceChargeReconstruction Class Reference
performs space charge distortion reconstruction using tracks To reconstruct the distortions dr0, drphi0 and dz0 in a given volume element, the following chisquare is minimized chisquare = sum_cluster (drphi - (drphi0 + dr0 tan alpha))**2/error**2 + sum_cluster (dz - (dz0 + dr0 tan beta))**2/error**2 with
#include <fun4all_coresoftware/blob/master/offline/packages/tpccalib/TpcSpaceChargeReconstruction.h>
Public Member Functions
TpcSpaceChargeReconstruction (const std::string &="TPCSPACECHARGERECONSTRUCTION")
constructor
int Init (PHCompositeNode *) override
global initialization
int InitRun (PHCompositeNode *) override
run initialization
int process_event (PHCompositeNode *) override
event processing
int End (PHCompositeNode *) override
end of processing
void SetDefaultParameters () override
parameters
configuration
void set_use_micromegas (bool value)
set whether to use only tracks with micromegas or not
void set_grid_dimensions (int phibins, int rbins, int zbins)
set grid dimensions
void set_outputfile (const std::string &filename)
output file
Public Member Functions inherited from SubsysReco
virtual ~SubsysReco ()
virtual int EndRun (const int)
Called at the end of each run.
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
virtual void Print (const std::string &what="ALL") const
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Public Member Functions inherited from PHParameterInterface
PHParameterInterface (const std::string &name)
virtual ~PHParameterInterface ()
void set_paramname (const std::string &name)
void set_double_param (const std::string &name, const double dval)
double get_double_param (const std::string &name) const
void set_int_param (const std::string &name, const int ival)
int get_int_param (const std::string &name) const
void set_string_param (const std::string &name, const std::string &sval)
std::string get_string_param (const std::string &name) const
void UpdateParametersWithMacro ()
void SaveToNodeTree (PHCompositeNode *runNode, const std::string &nodename)
void PutOnParNode (PHCompositeNode *parNode, const std::string &nodename)
Private Types
using matrix_t = Eigen::Matrix< float, m_ncoord, m_ncoord >
using column_t = Eigen::Matrix< float, m_ncoord, 1 >
Private Member Functions
int load_nodes (PHCompositeNode *)
load nodes
void process_tracks ()
process tracks
bool accept_track (SvtxTrack *) const
returns true if track fulfills basic requirement for distortion calculations
void process_track (SvtxTrack *)
process track
void calculate_distortions (PHCompositeNode *)
calculate distortions
int get_cell (int iphi, int ir, int iz) const
get cell from phi, r and z index
int get_cell (float phi, float r, float z) const
get cell from phi, r and z values
int get_cell (TrkrCluster *) const
get relevant cell for a given cluster
Private Attributes
std::string m_outputfile = "TpcSpaceChargeReconstruction.root"
output file
bool m_use_micromegas = true
true if only tracks with micromegas must be used
std::vector< matrix_t > m_lhs
left hand side matrices for distortion inversions
std::vector< column_t > m_rhs
right hand side matrices for distortion inversions
std::vector< int > m_cluster_count
keep track of how many clusters are used per cell
grid size
int m_phibins = 36
int m_rbins = 16
int m_zbins = 80
int m_totalbins = m_phibins*m_rbins*m_zbins
selection parameters
float m_max_talpha = 0.6
float m_max_drphi = 0.5
float m_max_tbeta = 1.5
float m_max_dz = 0.5
counters
int m_total_tracks = 0
int m_accepted_tracks = 0
int m_total_clusters = 0
int m_accepted_clusters = 0
nodes
SvtxTrackMap * m_track_map = nullptr
TrkrClusterContainer * m_cluster_map = nullptr
Static Private Attributes
static constexpr int m_ncoord = 3
grid dimensions
static constexpr float m_phimin = 0
static constexpr float m_phimax = 2.*M_PI
static constexpr float m_rmin = 20
static constexpr float m_rmax = 78
static constexpr float m_zmin = -105.5
static constexpr float m_zmax = 105.5
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = INT_MAX - 10
}
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Protected Member Functions inherited from PHParameterInterface
void set_default_double_param (const std::string &name, const double dval)
void set_default_int_param (const std::string &name, const int ival)
void set_default_string_param (const std::string &name, const std::string &sval)
void InitializeParameters ()
Detailed Description
performs space charge distortion reconstruction using tracks To reconstruct the distortions dr0, drphi0 and dz0 in a given volume element, the following chisquare is minimized chisquare = sum_cluster (drphi - (drphi0 + dr0 tan alpha))**2/error**2 + sum_cluster (dz - (dz0 + dr0 tan beta))**2/error**2 with
drphi and dz the residuals (track - cluster) measured for a given cluster
alpha and beta the track angles at the cluster in the rphi,r plane and the z,r plane, respectively The chisquare being quadratic in dr0, drphi0 and dz0, it can be minimized analytically. This results in a linear equation lhs[i].[corrections] = rhs[i], and thus [corrections] = lhs[i]**(-1).rhs[i] The lhs and rhs matrices are filled in TpcSpaceChargeReconstruction::process_track The inversion is performed in TpcSpaceChargeReconstruction::calculate_distortions
Definition at line 39 of file TpcSpaceChargeReconstruction.h.
View newest version in sPHENIX GitHub at line 39 of file TpcSpaceChargeReconstruction.h
Member Typedef Documentation
using TpcSpaceChargeReconstruction::column_t = Eigen::Matrix<float, m_ncoord, 1 > private
Definition at line 156 of file TpcSpaceChargeReconstruction.h.
View newest version in sPHENIX GitHub at line 156 of file TpcSpaceChargeReconstruction.h
using TpcSpaceChargeReconstruction::matrix_t = Eigen::Matrix<float, m_ncoord, m_ncoord > private
Definition at line 155 of file TpcSpaceChargeReconstruction.h.
View newest version in sPHENIX GitHub at line 155 of file TpcSpaceChargeReconstruction.h
Constructor & Destructor Documentation
TpcSpaceChargeReconstruction::TpcSpaceChargeReconstruction (const std::string & name = "TPCSPACECHARGERECONSTRUCTION")
constructor
Definition at line 49 of file TpcSpaceChargeReconstruction.cc.
View newest version in sPHENIX GitHub at line 49 of file TpcSpaceChargeReconstruction.cc
References PHParameterInterface::InitializeParameters().
Member Function Documentation
bool TpcSpaceChargeReconstruction::accept_track (SvtxTrack * track) const private
returns true if track fulfills basic requirement for distortion calculations
Definition at line 186 of file TpcSpaceChargeReconstruction.cc.
View newest version in sPHENIX GitHub at line 186 of file TpcSpaceChargeReconstruction.cc
References SvtxTrack::get_px(), SvtxTrack::get_py(), m_use_micromegas, and square().
Referenced by process_tracks().
void TpcSpaceChargeReconstruction::calculate_distortions (PHCompositeNode * topNode) private
calculate distortions
Definition at line 371 of file TpcSpaceChargeReconstruction.cc.
View newest version in sPHENIX GitHub at line 371 of file TpcSpaceChargeReconstruction.cc
References TpcSpaceChargeReconstructionHelper::copy_histogram(), TpcSpaceChargeReconstructionHelper::extrapolate_phi1(), TpcSpaceChargeReconstructionHelper::extrapolate_phi2(), TpcSpaceChargeReconstructionHelper::extrapolate_z(), get_cell(), analysis::h, Acts::Test::hz, ir(), m_cluster_count, m_lhs, m_outputfile, m_phibins, m_phimax, m_phimin, m_rbins, m_rhs, m_rmax, m_rmin, m_use_micromegas, m_zbins, m_zmax, m_zmin, name, run_skim::outputfile, TpcSpaceChargeReconstructionHelper::split(), and Fun4AllBase::Verbosity().
Referenced by End().
int TpcSpaceChargeReconstruction::End (PHCompositeNode * topNode) override virtual
end of processing
Reimplemented from SubsysReco.
Definition at line 126 of file TpcSpaceChargeReconstruction.cc.
View newest version in sPHENIX GitHub at line 126 of file TpcSpaceChargeReconstruction.cc
References calculate_distortions(), Fun4AllReturnCodes::EVENT_OK, m_accepted_clusters, m_accepted_tracks, m_total_clusters, and m_total_tracks.
int TpcSpaceChargeReconstruction::get_cell (int iphi, int ir, int iz) const private
get cell from phi, r and z index
Definition at line 478 of file TpcSpaceChargeReconstruction.cc.
View newest version in sPHENIX GitHub at line 478 of file TpcSpaceChargeReconstruction.cc
References m_phibins, m_rbins, and m_zbins.
Referenced by calculate_distortions(), get_cell(), and process_track().
int TpcSpaceChargeReconstruction::get_cell (float phi, float r, float z) const private
get cell from phi, r and z values
Definition at line 487 of file TpcSpaceChargeReconstruction.cc.
View newest version in sPHENIX GitHub at line 487 of file TpcSpaceChargeReconstruction.cc
References get_cell(), ir(), m_phibins, m_phimax, m_phimin, M_PI, m_rbins, m_rmax, m_rmin, m_zbins, m_zmax, and m_zmin.
int TpcSpaceChargeReconstruction::get_cell (TrkrCluster * cluster) const private
get relevant cell for a given cluster
Definition at line 509 of file TpcSpaceChargeReconstruction.cc.
View newest version in sPHENIX GitHub at line 509 of file TpcSpaceChargeReconstruction.cc
References get_cell(), QAG4Util::get_r(), TrkrCluster::getX(), TrkrCluster::getY(), TrkrCluster::getZ(), r, and z.
int TpcSpaceChargeReconstruction::Init (PHCompositeNode * topNode) override virtual
global initialization
Reimplemented from SubsysReco.
Definition at line 68 of file TpcSpaceChargeReconstruction.cc.
View newest version in sPHENIX GitHub at line 68 of file TpcSpaceChargeReconstruction.cc
References Fun4AllReturnCodes::EVENT_OK, m_accepted_clusters, m_accepted_tracks, m_cluster_count, m_lhs, m_rhs, m_total_clusters, m_total_tracks, and m_totalbins.
int TpcSpaceChargeReconstruction::InitRun (PHCompositeNode *) override virtual
run initialization
Reimplemented from SubsysReco.
Definition at line 86 of file TpcSpaceChargeReconstruction.cc.
View newest version in sPHENIX GitHub at line 86 of file TpcSpaceChargeReconstruction.cc
References Fun4AllReturnCodes::EVENT_OK, PHParameterInterface::get_double_param(), m_max_drphi, m_max_dz, m_max_talpha, m_max_tbeta, m_outputfile, m_phibins, m_rbins, m_totalbins, m_use_micromegas, m_zbins, and PHParameterInterface::UpdateParametersWithMacro().
int TpcSpaceChargeReconstruction::load_nodes (PHCompositeNode * topNode) private
load nodes
Definition at line 159 of file TpcSpaceChargeReconstruction.cc.
View newest version in sPHENIX GitHub at line 159 of file TpcSpaceChargeReconstruction.cc
References Fun4AllReturnCodes::EVENT_OK, m_cluster_map, and m_track_map.
Referenced by process_event().
int TpcSpaceChargeReconstruction::process_event (PHCompositeNode * topNode) override virtual
event processing
Reimplemented from SubsysReco.
Definition at line 115 of file TpcSpaceChargeReconstruction.cc.
View newest version in sPHENIX GitHub at line 115 of file TpcSpaceChargeReconstruction.cc
References Fun4AllReturnCodes::EVENT_OK, load_nodes(), process_tracks(), and analysis::res.
void TpcSpaceChargeReconstruction::process_track (SvtxTrack * track) private
process track
Definition at line 202 of file TpcSpaceChargeReconstruction.cc.
View newest version in sPHENIX GitHub at line 202 of file TpcSpaceChargeReconstruction.cc
References kdfinder::abs(), SvtxTrack::begin_cluster_keys(), SvtxTrack::begin_states(), cos(), QAG4Util::delta_phi(), dz, SvtxTrack::end_cluster_keys(), SvtxTrack::end_states(), TrkrClusterContainer::findCluster(), get_cell(), QAG4Util::get_r(), TrkrDefs::getTrkrId(), m_accepted_clusters, m_cluster_count, m_cluster_map, m_lhs, m_max_drphi, m_max_dz, m_max_talpha, m_max_tbeta, m_rhs, m_total_clusters, m_totalbins, PHWHERE, square(), and TrkrDefs::tpcId.
Referenced by process_tracks().
void TpcSpaceChargeReconstruction::process_tracks () private
process tracks
Definition at line 171 of file TpcSpaceChargeReconstruction.cc.
View newest version in sPHENIX GitHub at line 171 of file TpcSpaceChargeReconstruction.cc
References accept_track(), SvtxTrackMap::begin(), SvtxTrackMap::end(), m_accepted_tracks, m_cluster_map, m_total_tracks, m_track_map, and process_track().
Referenced by process_event().
void TpcSpaceChargeReconstruction::set_grid_dimensions (int phibins, int rbins, int zbins)
set grid dimensions
Parameters
phibins the number of bins in the azimuth direction
zbins the number of bins along z
Definition at line 55 of file TpcSpaceChargeReconstruction.cc.
View newest version in sPHENIX GitHub at line 55 of file TpcSpaceChargeReconstruction.cc
References m_phibins, m_rbins, m_totalbins, m_zbins, and phibins.
void TpcSpaceChargeReconstruction::set_outputfile (const std::string & filename)
output file
for now only TGraphs of space charge corrections vs r are stored ultimately one wants to save the data in a format that is suitable for use in the reconstruction
Definition at line 64 of file TpcSpaceChargeReconstruction.cc.
View newest version in sPHENIX GitHub at line 64 of file TpcSpaceChargeReconstruction.cc
References INPUTHEPMC::filename, and m_outputfile.
void TpcSpaceChargeReconstruction::set_use_micromegas (bool value) inline
set whether to use only tracks with micromegas or not
Definition at line 50 of file TpcSpaceChargeReconstruction.h.
View newest version in sPHENIX GitHub at line 50 of file TpcSpaceChargeReconstruction.h
References m_use_micromegas, and value.
void TpcSpaceChargeReconstruction::SetDefaultParameters () override virtual
parameters
Implements PHParameterInterface.
Definition at line 149 of file TpcSpaceChargeReconstruction.cc.
View newest version in sPHENIX GitHub at line 149 of file TpcSpaceChargeReconstruction.cc
References PHParameterInterface::set_default_double_param().
Member Data Documentation
int TpcSpaceChargeReconstruction::m_accepted_clusters = 0 private
Definition at line 173 of file TpcSpaceChargeReconstruction.h.
View newest version in sPHENIX GitHub at line 173 of file TpcSpaceChargeReconstruction.h
Referenced by End(), Init(), and process_track().
int TpcSpaceChargeReconstruction::m_accepted_tracks = 0 private
Definition at line 170 of file TpcSpaceChargeReconstruction.h.
View newest version in sPHENIX GitHub at line 170 of file TpcSpaceChargeReconstruction.h
Referenced by End(), Init(), and process_tracks().
std::vector<int> TpcSpaceChargeReconstruction::m_cluster_count private
keep track of how many clusters are used per cell
Definition at line 165 of file TpcSpaceChargeReconstruction.h.
View newest version in sPHENIX GitHub at line 165 of file TpcSpaceChargeReconstruction.h
Referenced by calculate_distortions(), Init(), and process_track().
TrkrClusterContainer* TpcSpaceChargeReconstruction::m_cluster_map = nullptr private
Definition at line 179 of file TpcSpaceChargeReconstruction.h.
View newest version in sPHENIX GitHub at line 179 of file TpcSpaceChargeReconstruction.h
Referenced by load_nodes(), process_track(), and process_tracks().
std::vector<matrix_t> TpcSpaceChargeReconstruction::m_lhs private
left hand side matrices for distortion inversions
Definition at line 159 of file TpcSpaceChargeReconstruction.h.
View newest version in sPHENIX GitHub at line 159 of file TpcSpaceChargeReconstruction.h
Referenced by calculate_distortions(), Init(), and process_track().
float TpcSpaceChargeReconstruction::m_max_drphi = 0.5 private
Definition at line 146 of file TpcSpaceChargeReconstruction.h.
View newest version in sPHENIX GitHub at line 146 of file TpcSpaceChargeReconstruction.h
Referenced by InitRun(), and process_track().
float TpcSpaceChargeReconstruction::m_max_dz = 0.5 private
Definition at line 150 of file TpcSpaceChargeReconstruction.h.
View newest version in sPHENIX GitHub at line 150 of file TpcSpaceChargeReconstruction.h
Referenced by InitRun(), and process_track().
float TpcSpaceChargeReconstruction::m_max_talpha = 0.6 private
Definition at line 145 of file TpcSpaceChargeReconstruction.h.
View newest version in sPHENIX GitHub at line 145 of file TpcSpaceChargeReconstruction.h
Referenced by InitRun(), and process_track().
float TpcSpaceChargeReconstruction::m_max_tbeta = 1.5 private
Definition at line 149 of file TpcSpaceChargeReconstruction.h.
View newest version in sPHENIX GitHub at line 149 of file TpcSpaceChargeReconstruction.h
Referenced by InitRun(), and process_track().
constexpr int TpcSpaceChargeReconstruction::m_ncoord = 3 static private
Definition at line 154 of file TpcSpaceChargeReconstruction.h.
View newest version in sPHENIX GitHub at line 154 of file TpcSpaceChargeReconstruction.h
std::string TpcSpaceChargeReconstruction::m_outputfile = "TpcSpaceChargeReconstruction.root" private
output file
Definition at line 111 of file TpcSpaceChargeReconstruction.h.
View newest version in sPHENIX GitHub at line 111 of file TpcSpaceChargeReconstruction.h
Referenced by calculate_distortions(), InitRun(), and set_outputfile().
int TpcSpaceChargeReconstruction::m_phibins = 36 private
Definition at line 136 of file TpcSpaceChargeReconstruction.h.
View newest version in sPHENIX GitHub at line 136 of file TpcSpaceChargeReconstruction.h
Referenced by calculate_distortions(), get_cell(), InitRun(), and set_grid_dimensions().
constexpr float TpcSpaceChargeReconstruction::m_phimax = 2.*M_PI static private
Definition at line 121 of file TpcSpaceChargeReconstruction.h.
View newest version in sPHENIX GitHub at line 121 of file TpcSpaceChargeReconstruction.h
Referenced by calculate_distortions(), and get_cell().
constexpr float TpcSpaceChargeReconstruction::m_phimin = 0 static private
Definition at line 120 of file TpcSpaceChargeReconstruction.h.
View newest version in sPHENIX GitHub at line 120 of file TpcSpaceChargeReconstruction.h
Referenced by calculate_distortions(), and get_cell().
int TpcSpaceChargeReconstruction::m_rbins = 16 private
Definition at line 137 of file TpcSpaceChargeReconstruction.h.
View newest version in sPHENIX GitHub at line 137 of file TpcSpaceChargeReconstruction.h
Referenced by calculate_distortions(), get_cell(), InitRun(), and set_grid_dimensions().
std::vector<column_t> TpcSpaceChargeReconstruction::m_rhs private
right hand side matrices for distortion inversions
Definition at line 162 of file TpcSpaceChargeReconstruction.h.
View newest version in sPHENIX GitHub at line 162 of file TpcSpaceChargeReconstruction.h
Referenced by calculate_distortions(), Init(), and process_track().
constexpr float TpcSpaceChargeReconstruction::m_rmax = 78 static private
Definition at line 126 of file TpcSpaceChargeReconstruction.h.
View newest version in sPHENIX GitHub at line 126 of file TpcSpaceChargeReconstruction.h
Referenced by calculate_distortions(), and get_cell().
constexpr float TpcSpaceChargeReconstruction::m_rmin = 20 static private
Definition at line 125 of file TpcSpaceChargeReconstruction.h.
View newest version in sPHENIX GitHub at line 125 of file TpcSpaceChargeReconstruction.h
Referenced by calculate_distortions(), and get_cell().
int TpcSpaceChargeReconstruction::m_total_clusters = 0 private
Definition at line 172 of file TpcSpaceChargeReconstruction.h.
View newest version in sPHENIX GitHub at line 172 of file TpcSpaceChargeReconstruction.h
Referenced by End(), Init(), and process_track().
int TpcSpaceChargeReconstruction::m_total_tracks = 0 private
Definition at line 169 of file TpcSpaceChargeReconstruction.h.
View newest version in sPHENIX GitHub at line 169 of file TpcSpaceChargeReconstruction.h
Referenced by End(), Init(), and process_tracks().
int TpcSpaceChargeReconstruction::m_totalbins = m_phibins*m_rbins*m_zbins private
Definition at line 139 of file TpcSpaceChargeReconstruction.h.
View newest version in sPHENIX GitHub at line 139 of file TpcSpaceChargeReconstruction.h
Referenced by Init(), InitRun(), process_track(), and set_grid_dimensions().
SvtxTrackMap* TpcSpaceChargeReconstruction::m_track_map = nullptr private
Definition at line 178 of file TpcSpaceChargeReconstruction.h.
View newest version in sPHENIX GitHub at line 178 of file TpcSpaceChargeReconstruction.h
Referenced by load_nodes(), and process_tracks().
bool TpcSpaceChargeReconstruction::m_use_micromegas = true private
true if only tracks with micromegas must be used
Definition at line 114 of file TpcSpaceChargeReconstruction.h.
View newest version in sPHENIX GitHub at line 114 of file TpcSpaceChargeReconstruction.h
Referenced by accept_track(), calculate_distortions(), InitRun(), and set_use_micromegas().
int TpcSpaceChargeReconstruction::m_zbins = 80 private
Definition at line 138 of file TpcSpaceChargeReconstruction.h.
View newest version in sPHENIX GitHub at line 138 of file TpcSpaceChargeReconstruction.h
Referenced by calculate_distortions(), get_cell(), InitRun(), and set_grid_dimensions().
constexpr float TpcSpaceChargeReconstruction::m_zmax = 105.5 static private
Definition at line 130 of file TpcSpaceChargeReconstruction.h.
View newest version in sPHENIX GitHub at line 130 of file TpcSpaceChargeReconstruction.h
Referenced by calculate_distortions(), and get_cell().
constexpr float TpcSpaceChargeReconstruction::m_zmin = -105.5 static private
Definition at line 129 of file TpcSpaceChargeReconstruction.h.
View newest version in sPHENIX GitHub at line 129 of file TpcSpaceChargeReconstruction.h
Referenced by calculate_distortions(), and get_cell().
The documentation for this class was generated from the following files:
fun4all_coresoftware/blob/master/offline/packages/tpccalib/TpcSpaceChargeReconstruction.h
fun4all_coresoftware/blob/master/offline/packages/tpccalib/TpcSpaceChargeReconstruction.cc