EIC Software: twoPhotonLuminosity Class Reference
twoPhotonLuminosity Class Reference
#include <estarlight/blob/master/include/twophotonluminosity.h>
Classes
struct difflumiargs
Public Member Functions
twoPhotonLuminosity (const inputParameters &input, beam beam_1, beam beam_2)
~twoPhotonLuminosity ()
Public Member Functions inherited from beamBeamSystem
beamBeamSystem (const inputParameters &input, const beam &electronBeam, const beam &targetBeam)
beamBeamSystem (const inputParameters &input)
~beamBeamSystem ()
const beam & electronBeam () const
returns beam particle 1
const beam & targetBeam () const
returns beam particle 2
double probabilityOfBreakup (const double D) const
double cmsBoost () const
double beamLorentzGamma () const
void init ()
Private Member Functions
void twoPhotonDifferentialLuminosity ()
double D2LDMDY (double M, double Y, double &Normalize)
double D2LDMDY (double M, double Y) const
double integral (double Normalize)
double radmul (int N, double *Lower, double *Upper, int NIterMin, int NIterMax, double EPS, double *WK, int NIter, double &Result, double &ResErr, double &NFNEVL, double &Summary)
double integrand (double N, double X[15])
double Nphoton (double W, double gamma, double Rho)
Static Private Member Functions
static void * D2LDMDY_Threaded (void *a)
Private Attributes
double _W1
double _W2
double _gamma
const unsigned int _nWbins
const unsigned int _nYbins
const double _wMin
const double _yMin
const double _wMax
const double _yMax
const int _productionMode
const int _beamBreakupMode
const int _interferenceEnabled
const double _interferenceStrength
const double _maxPtInterference
const int _nmbPtBinsInterference
const int _xsecCalcMethod
const std::string _baseFileName
Detailed Description
Definition at line 43 of file twophotonluminosity.h.
View newest version in sPHENIX GitHub at line 43 of file twophotonluminosity.h
Constructor & Destructor Documentation
twoPhotonLuminosity::twoPhotonLuminosity (const inputParameters & input, beam beam_1, beam beam_2)
Definition at line 52 of file twophotonluminosity.cpp.
View newest version in sPHENIX GitHub at line 52 of file twophotonluminosity.cpp
References twoPhotonDifferentialLuminosity().
twoPhotonLuminosity::~twoPhotonLuminosity ()
Definition at line 76 of file twophotonluminosity.cpp.
View newest version in sPHENIX GitHub at line 76 of file twophotonluminosity.cpp
Member Function Documentation
double twoPhotonLuminosity::D2LDMDY (double M, double Y, double & Normalize) private
Definition at line 154 of file twophotonluminosity.cpp.
View newest version in sPHENIX GitHub at line 154 of file twophotonluminosity.cpp
References _W1, _W2, starlightConstants::alpha, beamBeamSystem::electronBeam(), integral(), beamBeamSystem::targetBeam(), and nucleus::Z().
Referenced by D2LDMDY_Threaded(), and twoPhotonDifferentialLuminosity().
double twoPhotonLuminosity::D2LDMDY (double M, double Y) const private
Definition at line 173 of file twophotonluminosity.cpp.
View newest version in sPHENIX GitHub at line 173 of file twophotonluminosity.cpp
References _gamma, cos(), beamBeamSystem::electronBeam(), starlightConstants::hbarc, k, max, nucleus::nuclearRadius(), beam::photonDensity(), pi, beamBeamSystem::probabilityOfBreakup(), and beamBeamSystem::targetBeam().
void * twoPhotonLuminosity::D2LDMDY_Threaded (void * a) static private
Definition at line 250 of file twophotonluminosity.cpp.
View newest version in sPHENIX GitHub at line 250 of file twophotonluminosity.cpp
References charm_jet_coverage::args, D2LDMDY(), twoPhotonLuminosity::difflumiargs::m, M, twoPhotonLuminosity::difflumiargs::res, twoPhotonLuminosity::difflumiargs::self, and twoPhotonLuminosity::difflumiargs::y.
double twoPhotonLuminosity::integral (double Normalize) private
Definition at line 262 of file twophotonluminosity.cpp.
View newest version in sPHENIX GitHub at line 262 of file twophotonluminosity.cpp
References _gamma, _W1, _W2, beamBeamSystem::electronBeam(), starlightConstants::hbarcmev, nucleus::nuclearRadius(), starlightConstants::pi, radmul(), and beamBeamSystem::targetBeam().
Referenced by D2LDMDY().
double twoPhotonLuminosity::integrand (double N, double X[15]) private
Definition at line 643 of file twophotonluminosity.cpp.
View newest version in sPHENIX GitHub at line 643 of file twophotonluminosity.cpp
References _gamma, _W1, _W2, cos(), starlightConstants::hbarcmev, Nphoton(), beamBeamSystem::probabilityOfBreakup(), and theta().
Referenced by radmul().
double twoPhotonLuminosity::Nphoton (double W, double gamma, double Rho) private
Definition at line 657 of file twophotonluminosity.cpp.
View newest version in sPHENIX GitHub at line 657 of file twophotonluminosity.cpp
References bessel::dbesk1(), gamma(), and starlightConstants::pi.
Referenced by integrand().
double twoPhotonLuminosity::radmul (int N, double * Lower, double * Upper, int NIterMin, int NIterMax, double EPS, double * WK, int NIter, double & Result, double & ResErr, double & NFNEVL, double & Summary) private
Definition at line 419 of file twophotonluminosity.cpp.
View newest version in sPHENIX GitHub at line 419 of file twophotonluminosity.cpp
References F2, F3, integrand(), k, Acts::UnitConstants::m, max, charm_jet_strange_helicity::N, and z.
Referenced by integral().
void twoPhotonLuminosity::twoPhotonDifferentialLuminosity () private
Definition at line 81 of file twophotonluminosity.cpp.
View newest version in sPHENIX GitHub at line 81 of file twophotonluminosity.cpp
References _baseFileName, _beamBreakupMode, _gamma, _interferenceEnabled, _interferenceStrength, _maxPtInterference, _nmbPtBinsInterference, _nWbins, _nYbins, _productionMode, _wMax, _wMin, _xsecCalcMethod, _yMax, nucleus::A(), D2LDMDY(), starlightConstants::deuteronSlopePar, beamBeamSystem::electronBeam(), printf(), beamBeamSystem::targetBeam(), y, and nucleus::Z().
Referenced by twoPhotonLuminosity().
Member Data Documentation
const std::string twoPhotonLuminosity::_baseFileName private
Definition at line 89 of file twophotonluminosity.h.
View newest version in sPHENIX GitHub at line 89 of file twophotonluminosity.h
Referenced by twoPhotonDifferentialLuminosity().
const int twoPhotonLuminosity::_beamBreakupMode private
Definition at line 83 of file twophotonluminosity.h.
View newest version in sPHENIX GitHub at line 83 of file twophotonluminosity.h
Referenced by twoPhotonDifferentialLuminosity().
double twoPhotonLuminosity::_gamma private
Definition at line 73 of file twophotonluminosity.h.
View newest version in sPHENIX GitHub at line 73 of file twophotonluminosity.h
Referenced by D2LDMDY(), integral(), integrand(), and twoPhotonDifferentialLuminosity().
const int twoPhotonLuminosity::_interferenceEnabled private
Definition at line 84 of file twophotonluminosity.h.
View newest version in sPHENIX GitHub at line 84 of file twophotonluminosity.h
Referenced by twoPhotonDifferentialLuminosity().
const double twoPhotonLuminosity::_interferenceStrength private
Definition at line 85 of file twophotonluminosity.h.
View newest version in sPHENIX GitHub at line 85 of file twophotonluminosity.h
Referenced by twoPhotonDifferentialLuminosity().
const double twoPhotonLuminosity::_maxPtInterference private
Definition at line 86 of file twophotonluminosity.h.
View newest version in sPHENIX GitHub at line 86 of file twophotonluminosity.h
Referenced by twoPhotonDifferentialLuminosity().
const int twoPhotonLuminosity::_nmbPtBinsInterference private
Definition at line 87 of file twophotonluminosity.h.
View newest version in sPHENIX GitHub at line 87 of file twophotonluminosity.h
Referenced by twoPhotonDifferentialLuminosity().
const unsigned int twoPhotonLuminosity::_nWbins private
Definition at line 75 of file twophotonluminosity.h.
View newest version in sPHENIX GitHub at line 75 of file twophotonluminosity.h
Referenced by twoPhotonDifferentialLuminosity().
const unsigned int twoPhotonLuminosity::_nYbins private
Definition at line 76 of file twophotonluminosity.h.
View newest version in sPHENIX GitHub at line 76 of file twophotonluminosity.h
Referenced by twoPhotonDifferentialLuminosity().
const int twoPhotonLuminosity::_productionMode private
Definition at line 82 of file twophotonluminosity.h.
View newest version in sPHENIX GitHub at line 82 of file twophotonluminosity.h
Referenced by twoPhotonDifferentialLuminosity().
double twoPhotonLuminosity::_W1 private
Definition at line 71 of file twophotonluminosity.h.
View newest version in sPHENIX GitHub at line 71 of file twophotonluminosity.h
Referenced by D2LDMDY(), integral(), and integrand().
double twoPhotonLuminosity::_W2 private
Definition at line 72 of file twophotonluminosity.h.
View newest version in sPHENIX GitHub at line 72 of file twophotonluminosity.h
Referenced by D2LDMDY(), integral(), and integrand().
const double twoPhotonLuminosity::_wMax private
Definition at line 80 of file twophotonluminosity.h.
View newest version in sPHENIX GitHub at line 80 of file twophotonluminosity.h
Referenced by twoPhotonDifferentialLuminosity().
const double twoPhotonLuminosity::_wMin private
Definition at line 78 of file twophotonluminosity.h.
View newest version in sPHENIX GitHub at line 78 of file twophotonluminosity.h
Referenced by twoPhotonDifferentialLuminosity().
const int twoPhotonLuminosity::_xsecCalcMethod private
Definition at line 88 of file twophotonluminosity.h.
View newest version in sPHENIX GitHub at line 88 of file twophotonluminosity.h
Referenced by twoPhotonDifferentialLuminosity().
const double twoPhotonLuminosity::_yMax private
Definition at line 81 of file twophotonluminosity.h.
View newest version in sPHENIX GitHub at line 81 of file twophotonluminosity.h
Referenced by twoPhotonDifferentialLuminosity().
const double twoPhotonLuminosity::_yMin private
Definition at line 79 of file twophotonluminosity.h.
View newest version in sPHENIX GitHub at line 79 of file twophotonluminosity.h
The documentation for this class was generated from the following files:
estarlight/blob/master/include/twophotonluminosity.h
estarlight/blob/master/src/twophotonluminosity.cpp